### ISSUE TITLE
Show error don't use import "name" from './sss' 

### ISSUE THREAD

**Issue by pMonfared** [eslint/eslint#10005]
i used library but get error don't used
![image](https://user-images.githubusercontent.com/10448255/36605082-e0acb64e-18d4-11e8-99d5-8dbbbe3269e8.png)

**Comment by pMonfared** [comment]
@eslint
I use v4.16.0

eslint.json config : 
```
{
    "extends": "standard"
}
```
I get error line when use some component when import to other component, i used but get you don't use this component like that photo (import datePicker) and used <DatePicker /> but don't recognized by eslint

**Comment by pMonfared** [comment]
@not-an-aardvark 

see this photo (1) import (2) used - but get error you don't use this ?

![image](https://user-images.githubusercontent.com/10448255/36626705-ac85da8a-194c-11e8-8da1-0925a1e8eea4.png)

**Comment by platinumazure** [comment]
Hi @pMonfared, thanks for the issue.

It looks like you need to install eslint-plugin-react (if you haven't done so already), and then enable rule `react/jsx-uses-vars`. This should prevent the lint errors.

Please feel free to stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need any more help with this. Thanks!
