### ISSUE TITLE
Unexpected token, expected ";" after react render function

### ISSUE THREAD

**Issue by emekaokoli** [eslint/eslint#10027]
eslint throws error after declaration of react render() {}

It wants me to insert semi colon like below
render(); 
{
return(<div></div>)
}

> this is my eslintrc

{
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 8,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "impliedStrict": true,
      "classes": true
    }
  },
  "env": {
    "browser": true,
    "node": true
  },
  "rules": {
    "no-unused-vars": [
      1,
      {
        "argsIgnorePattern": "res|next|^err"
      }
    ],
    "arrow-body-style": [
      2,
      "as-needed"
    ],
    "no-param-reassign": [
      2,
      {
        "props": false
      }
    ],
    "no-console": 0,
    "import/prefer-default-export": 0,
    "import": 0,
    "func-names": 0,
    "space-before-function-paren": 0,
    "comma-dangle": 0,
    "max-len": 0,
    "import/extensions": 0,
    "no-underscore-dangle": 0,
    "consistent-return": 0,
    "react/display-name": 1,
    "react/react-in-jsx-scope": 0,
    "react/forbid-prop-types": 0,
    "react/no-unescaped-entities": 0,
    "jsx-a11y/accessible-emoji": 0,
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    ],
    "radix": 0,
    "no-shadow": [
      2,
      {
        "hoist": "all",
        "allow": [
          "resolve",
          "reject",
          "done",
          "next",
          "err",
          "error"
        ]
      }
    ],
    "quotes": [
      2,
      "single",
      {
        "avoidEscape": true,
        "allowTemplateLiterals": true
      }
    ],
    "prettier/prettier": [
      "error",
      {
        "trailingComma": "es5",
        "singleQuote": true,
        "printWidth": 120
      }
    ],
    "jsx-a11y/href-no-hash": "off",
    "jsx-a11y/anchor-is-valid": [
      "warn",
      {
        "aspects": [
          "invalidHref"
        ]
      }
    ]
  },
  "plugins": [
    "html",
    "prettier"
  ]
}

> Error message

`
[eslint]
Parsing error: Unexpected token, expected ";"
  2 | 
  3 | const Routes = function(props) {
> 4 | render() {
    |          ^
  5 |     return ( <div></div>)}
  6 |        
  7 |

`

**Comment by not-an-aardvark** [comment]
Hi,

This is happening because your code contains invalid syntax. It's not valid JavaScript to have a method directly inside of a function. When using functions as components in React, the return value of the function itself is used for rendering, so no explicit `render` method is necessary.

Instead, you should replace this:

```js
const Routes = function(props) {
  render() {
    return (...);
  }
}
```

...with this:

```js
const routes = function(props) {
  return (...)
}
```

**Comment by emekaokoli** [comment]
Thanks @not-an-aardvark totally missed that.
