### ISSUE TITLE
prefer-template autofixer should not convert a string to a template if it contains an octal escape sequence

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#10031]
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 9.6.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  prefer-template: error
parserOptions:
  ecmaVersion: 6
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
'\033' + foo
```

```bash
eslint theFile.js --fix
```

**What did you expect to happen?**

I expected no autofix to happen, because the string `'\033'` contains an octal escape sequence, which is a syntax error when it appears in a template literal.

**What actually happened? Please include the actual, raw output from ESLint.**

The problem was automatically fixed, resulting in a syntax error.

```
1:2  error  Parsing error: Octal literal in strict mode
```

(Note: the error message is a bit misleading; this is a parsing error because the resulting string is a template literal, not because it's in strict mode.)

**Comment by MuraliNunna** [comment]
Hello,
I wanted to work on eslint and this seemed like a 'good first issue' to pick up. 

**My findings:**
I dug a bit deeper and found that the parser used by eslint(espree using acorn) is throwing this error in strict mode.

Specifically the error is thrown from here https://github.com/acornjs/acorn/blob/0d20f67b03e0784bdd18eb88e0f76e6a53043404/src/tokenize.js#L631

As for the fix there, this will not occur if you disable the 'strict' rule.

This is the file that i tried to replicate this issue
```js
"use strict";
function testIssue10031() {
    return "\033" + "postfix";
}
```
This threw me the error
```bash
  4:13  error  Parsing error: Octal literal in strict mode
```

If i disable the 'strict' rule, i get the proper rule suggestion for it
```js
/* eslint strict: 0 */
function testIssue10031() {
    return "\033" + "postfix";
}
```
```bash
  2:1   error  Missing JSDoc comment                          require-jsdoc
  2:10  error  'testIssue10031' is defined but never used     no-unused-vars
  3:12  error  Don't use octal: '\033'. Use '\u....' instead  no-octal-escape
  3:19  error  Unexpected string concatenation of literals    no-useless-concat
```

As eslint, i gather reports parse errors as also eslint errors, how should i proceed here? Should this be considered as a bug to be fixed?

**Comment by not-an-aardvark** [comment]
@MuraliNunna Thanks for looking into this! You're correct that ESLint just catches parser errors and reports them as linting errors. However, I think there are a few issues with the test code that you're using, which are preventing it from being a good demonstration of this issue.

* The test code is running in strict mode, due to the `"use strict"` directive at the top. However, using octal escape sequences is a syntax error in strict mode, regardless of whether it's in a template literal, so the `prefer-template` rule never runs in that case.
* The test code is concatenating two string literals (`"\033"` and `"postfix"`). However, the `prefer-template` rule only reports an error when concatenating a string literal with something other than a string literal (e.g. a variable).

Have you tried using the example code and configuration that were provided in the original issue? I think if the source file only contains `'\033' + foo` (with nothing else), and only the `prefer-template` rule is enabled, it will be easier to trigger this bug.

**Comment by malcolmsgroves** [comment]
@MuraliNunna I figured you stopped working on this?

**Comment by MuraliNunna** [comment]
@malcolmsgroves Apologies for the late reply. I wasn't able to look into the issue after my initial comment. I should have at least put out a comment that i was not working on it. Thanks for the fix anyways.
