### ISSUE TITLE
eslint-disable-line not work

### ISSUE THREAD

**Issue by youngpink** [eslint/eslint#10035]
**Tell us about your environment**

* **ESLint Version: 3.19.0**
* **Node Version: 6.9.1**
* **npm Version: 3.10.8**

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": "airbnb",
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".ios.js", ".android.js"]
      }
    }
  },
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "import/no-unresolved": [2, { "ignore": [".png"] }],
    "no-underscore-dangle": [0],
    "react/forbid-prop-types": [0],
    "react/no-unused-prop-types": [2, { "skipShapeProps": true }],
    "import/prefer-default-export": [0],
    "class-methods-use-this": [0],
    "no-use-before-define": "off",
    "consistent-return": [0]
  },
  "env": {
    "jest": true
  }
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
...
         <RowPanel      
            onPress={() => Actions.vehicleSelect({   
              initialVehicle: {
                ...vehicleInfo,
                class: vehicleInfo.class,
              },
            })}
          />  // eslint-disable-line
...
```

```bash
npm run lint
```

**What did you expect to happen?**
no errors
**What actually happened? Please include the actual, raw output from ESLint.**
  266:12  error  Parsing error: Unexpected token >

**Comment by not-an-aardvark** [comment]
The issue is that JSX does not allow line comments, so your `// eslint-disable-line` is actually not a comment and it's being rendered as a regular part of your JSX text.

**Comment by youngpink** [comment]
@not-an-aardvark   thank your explanation, so do you have any idea to fix this?

**Comment by not-an-aardvark** [comment]
You could do something like this:

```js
         <RowPanel      
            onPress={() => Actions.vehicleSelect({   
              initialVehicle: {
                ...vehicleInfo,
                class: vehicleInfo.class,
              },
            }) /* eslint-disable */}
          />
          {/* eslint-enable */}
```

**Comment by youngpink** [comment]
@not-an-aardvark  it works! thank  you so much

**Comment by youngpink** [comment]
@not-an-aardvark  I try it, but not work for me. Actually, 'eslint-disable-line' only  don't work on my laptop. And the error appears out of the line 'class: vehicleInfo.class'. But I must left this line. It seems own to my local environment. I'll try others. Thank you anyway.

**Comment by youngpink** [comment]
I delete node_modules, and run 'npm install', then run 'npm run lint', it success.
