### ISSUE TITLE
broken valid-jsdoc in 4.18.2

### ISSUE THREAD

**Issue by tomfun** [eslint/eslint#10051]
**Tell us about your environment**

* **ESLint Version:**: 4.18.2
* **Node Version:** 8
* **npm Version:** 5.5.1

**What parser (default) are you using?** babel

**Please show your full configuration:**
```json
  "parserOptions": {
    "ecmaVersion": 7,
    "ecmaFeatures": {
      "globalReturn": true,
      "impliedStrict": true,
      "modules": true,
      "experimentalObjectRestSpread": true
    },
    "sourceType": "module"
  },
  "plugins": [
    "import"
  ],
  "parser": ".../node_modules/babel-eslint/lib/index.js",
/// ....

    "valid-jsdoc": [
      1,
      {
        "prefer": {
          "returns": "return"
        },
        "preferType": {
          "string": "String",
          "object": "Object",
          "number": "Number"
        },
        "requireReturn": false,
        "requireParamDescription": false,
        "requireReturnDescription": false
      }
    ],
```
<details>
<summary>Configuration</summary>
[Full config](https://pastebin.com/WeRnHWyz)

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// ...
    /**
     * @return {{DEFAULT_TYPE: String, REGULAR_PRICE: String}}
     */
    static get TYPES() {
        return {
            DEFAULT_TYPE, REGULAR_PRICE
        };
    }

    /**
     * @param {Money} [money]
     * @param {String} [type]
     */
    constructor(money, type = DEFAULT_TYPE) {
        if (money) {
            this.setValue(type, money);
        }
    }
// ...
```

```bash
npx eslint services/PriceCalcService/entities/PriceValues.js
```

**What did you expect to happen?** js doc is valid. It was so when was **4.18.1** version.

**What actually happened? Please include the actual, raw output from ESLint.**
```txt
..../services/PriceCalcService/entities/PriceValues.js
  15:5  error  Missing JSDoc return description                    valid-jsdoc
  25:8  error  Missing JSDoc parameter description for 'money'     valid-jsdoc
  26:8  error  Missing JSDoc parameter description for 'type'      valid-jsdoc
  34:5  error  Missing JSDoc @returns for function                 valid-jsdoc
```
*returns* for constructor is never required! types (as you see) are good.

**Comment by ilyavolodin** [comment]
Pretty sure that valid-jsdoc doesn't know about `constructor`, so it just treats it as a regular function (that's why return is required), however, since you have `"requireReturn": false` in your config, it shouldn't be required.

**Comment by tomfun** [comment]
@ilyavolodin , in the past it was OK, and it understood what is the constructor, so it didn't require `@return`

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
