### ISSUE TITLE
proposal: Add disable-styling option when run init.

### ISSUE THREAD

**Issue by sottar** [eslint/eslint#10068]
### What rule do you want to change?
Add disable styling rules option when run `init` command.

### Background and Details.
I'm using prettier and eslint in my project. But these are usually conflict with styling rules.

I thought it's better that format styling by `prettier` and perform static analysis without styling by `eslint`.  But it's pain to setting it myself.
So I want to create option that to be able to remove static analysis about stylings by `eslint`

for example, add like a `? Disable style rules?` option when run `./node_modules/.bin/eslint --init` command.  And if yes, add invalidate styling rules to `eslintrc`.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
