### ISSUE TITLE
Install breaks on Windows due to "weak" dependency

### ISSUE THREAD

**Issue by Pomax** [eslint/eslint#10083]
It looks like there's a dependency on `weak`, which does not have precompiled binaries and thus means that windows developers who want to use `eslint` must have python and Visual Studio installed, just to lint javascript =(

It would be great if an alternative library could be found to replace whatever's relying on `weak`, so that `eslint` becomes nicely cross-platform again.

**Comment by platinumazure** [comment]
Hi @Pomax, thanks for the issue.

Could you show us the output of `npm ls` and help us find which dependency is depending on `weak`? Thanks!

**Comment by Pomax** [comment]
Good request - apparently, nowhere. I ran into this in the context of a different project where `npm install eslint` caused the problem, I guess I'll go hunt down why their package.json causes compile errors on `weak` whereas just `eslint` in a clean dir does not. Apologies for filing.
