### ISSUE TITLE
.babelrc.js should not be ignored by default

### ISSUE THREAD

**Issue by jaydenseric** [eslint/eslint#10089]
By default ESLint ignores dot files and folders, presumably because they are often generated or temporary.

As an exception, `.babelrc.js` files should not be ignored by default. These commonly used files are manually authored and should be linted.

A lot of people either don't realise their babel configs are not being linted or they can't be bothered to mess around with [`eslintIgnore` glob weirdness](https://github.com/eslint/eslint/issues/9942).

**Tell us about your environment**

* **ESLint Version:** v4.18.2
* **Node Version:** v9.8.0
* **npm Version:** v5.7.1

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. I don't think we should add special exceptions for the config files of specific tools, but it might be reasonable to just removing the dotfiles exception entirely, as you suggested in https://github.com/eslint/eslint/issues/9942. (However, we would need to still have an exception for things like `.git/`, which should presumably never be linted. I'm not sure what the specifics of that exception would look like.)

**Comment by not-an-aardvark** [comment]
Closing in favor of https://github.com/eslint/eslint/issues/10341.
