### ISSUE TITLE
Parsing Error: Unexpected Token {

### ISSUE THREAD

**Issue by chasen-bettinger** [eslint/eslint#10088]
**Tell us about your environment**

* **ESLint Version:** 4.18.2
* **Node Version:** 8.9.2
* **yarn Version:** 1.5.1

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

{
  "env": { "node": true, "browser": true, "es6": true },
  "extends": "airbnb",
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  }
}


```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

function App() {
  
  render() {
    return ( 
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    )
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

I use ESLint in VSCode so I don't think this is applicable? Could be wrong.

**What did you expect to happen?**

There to be no error? I checked the AirBnb style guide meticulously and I thought I written my code for their guidelines but apparently not.

**What actually happened? Please include the actual, raw output from ESLint.**

severity: 'Error' message: 'Parsing error: Unexpected token {' at: '6,12' source: 'eslint' code: 'undefined'

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is happening because your code contains invalid syntax. It's not valid JavaScript to have a method directly inside of a function. When using functions as components in React, the return value of the function itself is used for rendering, so no explicit `render` method is necessary.

Instead, you should replace this:

```js
function App() {
  
  render() {
    return ( 
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    )
  }

}
```

...with this:

```js
function App() {
  return ( 
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Text>Changes you make will automatically reload.</Text>
      <Text>Shake your phone to open the developer menu.</Text>
    </View>
  )
}
```

**Comment by chasen-bettinger** [comment]
@not-an-aardvark Thank you! I didn't understand that beforehand (obviously).
