### ISSUE TITLE
Feature request: option to set non-zero exit code when autofixing

### ISSUE THREAD

**Issue by kvsm** [eslint/eslint#10099]
Scenario: When running eslint in a pre-commit hook against files which are staged in git, I want to automatically fix issues with --fix, but have eslint return a non-zero exit code so that the commit is rejected (because the fixed files need to be restaged).

Proposed solution: Have a command line flag which enables returning non-zero exit code when autofixing issues.

Example: I also use Rubocop for Ruby code, which has the option `--fail-level=autocorrect` for this purpose.

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. I'm personally not sure this is worth adding, for a few reasons:

* This could be simulated outside of the CLI (by using a custom formatter that checks whether any fixes were applied, and checking the output of the formatter in a git commit hook).
* This would a new semantic to the exit code, which is already used to indicate the whether there are any remaining problems after using `--fix`. From a design perspective, it seems like it's not ideal to give the same output (the exit code) two entirely unrelated meanings depending on the presence of a flag.

However, I'm not entirely opposed to this (it seems like it could be a useful convenience feature in some cases), so I'd be fine with adding this if there are other team members in favor of it.

**Comment by platinumazure** [comment]
Could we use a new exit code entirely for this feature?

For example (and taking into account the accepted proposal for separate exit code when there is a configuration error):

* 0 is used for no errors or warnings only. With the new flag, only used if no fixable errors/warnings were ever reported in the run.
* 1 is used for when errors are reported.
* 2 is used for when configuration errors occur or ESLint crashes for other reasons.
* 3 is used for this new case: A fixable error or warning was reported, but currently no errors after fixing. (Only through use of a new flag. Without flag, this scenario would have exit code of 0. If errors remain, use exit code 1 as normal.)

That said, I'm on the fence about whether the added complexity is worthwhile. I think this could be mitigated by adding easily-read top-level information to the lint result object about whether fixes were ever applied or not.

**Comment by kvsm** [comment]
You're right about overloading the exit code, I didn't mean to suggest exit code 1 specifically, edited title to reflect this.

**Comment by TSMMark** [comment]
Interested in this feature, any pointers on how to implement it and submit a PR?

**Comment by platinumazure** [comment]
Hi @TSMMark, thanks for your interest.

At this point, we would want some level of team consensus on a new design. I'm not sure if this requires an RFC as the design/implementation should be pretty simple. A new design would need approval by our technical steering committee (TSC).

Probably the simplest approach would be to create a new issue. I would recommend having a specific proposal on how the exit codes would work and whether the behavior is behind a CLI flag or not, as well as specific information on how this would be beneficial to you. (Some of this could be lifted from previous posts on this issue.) Once we have a concrete proposal, the team can evaluate it and eventually send to the TSC.

Let me know if you have any questions!

**Comment by TSMMark** [comment]
Thanks @platinumazure. For now I was able to use a workaround where we grep the eslint cli process stdout and scan for a regex pattern that indicates that something was fixed. Although more brittle than I'd like it's acceptable for now so I will not be working any more towards this goal in the near future. Thanks again
