### ISSUE TITLE
Autocomplete ")" after "(" gets unnecessarily added, even if preventing to do so could prevent eslint syntax error. 

### ISSUE THREAD

**Issue by lensbart** [eslint/eslint#10097]
**Tell us about your environment**

* **ESLint Version:** 
* **Node Version:**
* **npm Version:**

Atom 1.24.1

**What parser (default, Babel-ESLint, etc.) are you using?** linter-eslint 8.4.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.
