### ISSUE TITLE
Cannot read property slice of undefined

### ISSUE THREAD

**Issue by mividtim** [eslint/eslint#10107]
I get an unhandled exception, "Cannot read property slice of undefined," when using this in certain environments. I added logging statements, starting in eslint, and ending up in index.js in the callsites package, until I found the line which throws the exception:

https://github.com/sindresorhus/callsites/blob/master/index.js#L5

As I cannot post an issue on that Github repo, I'm hoping you will support me in this issue, as you chose the package as a dependency (albeit indirectly).

The `stack` property of a `new Error()` object is undefined at that line of code in these environments. But if I just run `new Error().stack` in a Node REPL on the same computer (with only one version of Node installed on that computer), it returns a string, as expected.

Does anyone have any thoughts as to how this is possible? Strangest to me is that the same exact code-base, with a yarn.lock file and Node, git, and yarn at the same versions, other machines do not have this issue. All machines are running Mac OS, and we cannot find any pattern regarding Mac update versions.

**Comment by mividtim** [comment]
We are locked into using Node v6.5.0 (due to embedding in a custom Electron build) and generally yarn 1.3.2, although some of us are using yarn 1.5.1, both with success. In the environments where this is failing, some are using either version of yarn, so there are no obvious patterns.

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.
