### ISSUE TITLE
Add a rule to avoid unnecessary spread operators

### ISSUE THREAD

**Issue by daedalus28** [eslint/eslint#10129]
I've seen a few cases on projects where developers are using extra spread operators, e.g.:

```js
fn(...[arg1, arg2, ...args])
```

which should autofix to

```js
fn(arg1, arg2, ...args)
```

This seems to follow the eslint philosophy of being generally applicable to all projects. I checked the docs and did not see a rule to do this already.

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.
