### ISSUE TITLE
eslint crashes with "RegExpValidator is not a constructor"

### ISSUE THREAD

**Issue by raphinesse** [eslint/eslint#10128]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.10.0
* **npm Version:** 5.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    sourceType: 'script',
  },
  env: {
    es6: true,
    node: true,
  },
  plugins: ['prettier'],
  extends: ['eslint:recommended', 'prettier'],
  rules: {
    'comma-dangle': ['error', 'always-multiline'],
    'linebreak-style': ['error', 'unix'],
    'no-console': 'off',
    'no-unused-vars': ['error', { argsIgnorePattern: '^_$' }],
    'space-before-function-paren': ['error', 'never'],
    strict: ['error', 'global'],
  },
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
eslint .
```

**What did you expect to happen?**
Normal linting

**What actually happened? Please include the actual, raw output from ESLint.**
```
RegExpValidator is not a constructor
TypeError: RegExpValidator is not a constructor
    at new <anonymous> (PKG_ROOT/node_modules/eslint/lib/rules/no-control-regex.js:14:27)
    at Object.<anonymous> (PKG_ROOT/node_modules/eslint/lib/rules/no-control-regex.js:9:19)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Rules.get (PKG_ROOT/node_modules/eslint/lib/rules.js:118:34)
```

**Comment by raphinesse** [comment]
Error does not occur when using ^4.18. Could be caused by https://github.com/eslint/eslint/commit/8d3814e4ae823e58f40539047bb35bcaf5c76660

**Comment by Aladdin-ADD** [comment]
hi, thanks for the report! However I was not able to reproduce it. Could you  please share the source code in [eslint demo](https://eslint.org/demo)?

**Comment by raphinesse** [comment]
It happens even when I check an empty file. I already tried deleting `node_modules/` and doing a clean install (I use a local install of `eslint`). That did not fix the error either.

**Comment by Aladdin-ADD** [comment]
emm.. interesting! seems the dep `regexpp` is actually resolved to `readline`(npm's issue to me):
https://github.com/raphinesse/cordova-plugin-exclude-files/blob/018fcd2fddaaa067ae2c08acaffd85a196c66dc7/package-lock.json#L1549-L1557

`npm cache clean -f` and reinstall works for me.😄

**Comment by raphinesse** [comment]
This is about the strangest issue I encountered in some time. Another `rm -rf node_modules/ package-lock.json && npm i` just resolved it. I still don't know what was going on, but it does not seem to be an eslint issue. Sorry for troubling you and thanks for the help.
