### ISSUE TITLE
Cannot find module 'regexpp' source from => \node_modules\eslint\lib\rules\no-control-regex.js

### ISSUE THREAD

**Issue by Mohanrau** [eslint/eslint#10122]
**Tell us about your environment**

* **ESLint Version: 4.19.1**
* **Node Version: latest**
* **npm Version: latest**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
npm run dev
```

```bash
eslint --ext .js,.vue src
```

**What did you expect to happen?**
npm run dev

**What actually happened? Please include the actual, raw output from ESLint.**

npm run dev throw error
**Module build failed:   Error: Cannot find module 'regexpp'**

then run  **eslint --ext .js,.vue src**
```
Cannot find module 'regexpp'
Error: Cannot find module 'regexpp'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projects\Nibs\Frontend\node_modules\eslint\lib\rules\no-control-regex.js:8:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by platinumazure** [comment]
We recently added that dependency. Try running `npm install` to get it installed in your project, and let us know if that doesn't solve it.

**Comment by Mohanrau** [comment]
`npm install` not solving the issue already remove node_modules directory and do clean installation.Same error.

**Comment by platinumazure** [comment]
@Mohanrau Issue #10128 seems similar, although it resulted in a different error message... Are you using package-lock or shrinkwrap, and does it potentially have any inconsistencies?

**Comment by Mohanrau** [comment]
@platinumazure thanks man. Issue #10128 helps.

by executing  `rm -rf node_modules/ package-lock.json && npm i` solve the issue
