### ISSUE TITLE
Docs - Missing d at end of capitalized

### ISSUE THREAD

**Issue by jasonfry** [eslint/eslint#10135]
https://eslint.org/docs/rules/capitalized-comments#ignoreconsecutivecomments has two typos with the rule name missing a d at the end of capitalized.

```
/* eslint capitalize-comments: ["error", "always", { "ignoreConsecutiveComments": true }] */
```

**Comment by platinumazure** [comment]
Hi @jasonfry, thanks for the issue! You are right, those should definitely be fixed.

Would you like to submit a PR?
