### ISSUE TITLE
Allow inlining of processors in config file

### ISSUE THREAD

**Issue by hrb90** [eslint/eslint#10145]
**Tell us about your environment**

* **ESLint Version:** 4.19.0
* **Node Version:** 7.6.0
* **npm Version:** 4.1.2

**What parser (default, Babel-ESLint, etc.) are you using?** default

I wanted autofix support in a third-party plugin, so I forked the plugin code and made a patch. However, for simplicity's sake, I removed a feature I'm not using from the original plugin, so I don't want to upstream it as a PR, and if at all possible I'd like to avoid publishing and maintaining an npm package for our narrow use-case. (Especially since I'm hoping to get a real PR open on the original plugin soon.) The plugin code is only 80 lines to define a processor, so I'd like to inline it in my .eslintrc.js file; however, I can't find a good way of doing this in the docs. Do I have any options other than publishing my patched plugin to npm?

**Comment by platinumazure** [comment]
Hi @hrb90, thanks for the issue.

You could use `npm link` to "install" it locally. The npm docs have a little more information.

**Comment by hrb90** [comment]
Thanks for the suggestion! Do you happen to know if there's a way to get that symlink that `npm link` creates inside our git repo? The rest of the team needs to use this plugin too :smile:

**Comment by kaicataldo** [comment]
You could potentially write a script that does this, but it seems easier to me to just install from your branch on GitHub by specifying it in the package.json

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
