### ISSUE TITLE
Remove compatibility hack for plugins that monkeypatch `Linter`

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#10140]
See [here](https://github.com/eslint/eslint/blob/f6901d0bcf6c918ac4e5c6c7c4bddeb2cb715c09/lib/linter.js#L741-L752) and [here](https://github.com/eslint/eslint/blob/f6901d0bcf6c918ac4e5c6c7c4bddeb2cb715c09/lib/linter.js#L798-L814).

**Comment by not-an-aardvark** [comment]
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/4604d91e9e0c546b9bf336ed24dc9a7998a17010/notes/2018/2018-04-12.md#remove-compatibility-hack-for-plugins-that-monkeypatch-linter), the TSC decided to remove the compatibility hacks.
