### ISSUE TITLE
no-use-before-define: add exception for mutually recursive functions

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#1015]
Like these guys:

```js
function a(n) { return n > 0 ? n * b(n - 1) : n; }
function b(n) { return n > 0 ? n + a(n - 1) : n; }
```

**Comment by nzakas** [comment]
Cleaning up issues. I don't think it's worth pursuing this. Our current behavior matches JSHint's and there's been no further movement on this issue, so closing.
