### ISSUE TITLE
Eslint --rule and --fix options together

### ISSUE THREAD

**Issue by tgreen7** [eslint/eslint#10150]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 9.8.0
* **npm Version:** 5.8.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint": "^8.2.2"

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: ['react-app'],
  rules: {
    'no-var': 2,
    'no-console': [1, { allow: ['warn', 'error'] }],
    'no-debugger': 2,
    'no-empty': [2],
    'no-extra-boolean-cast': 2,
    'no-extra-semi': 1,
    'no-inner-declarations': [2, 'functions'],
    'no-undef': 2,
    'no-unneeded-ternary': 1,
    'no-unsafe-negation': 2,
    'no-unused-vars': [1, { ignoreRestSiblings: true }],
    'import/no-unresolved': 2,
    'import/named': 2,
    'no-const-assign': 2,
    'import/default': 2,
    'react/jsx-boolean-value': 0,
    'react/jsx-key': 2,
    'graphql/template-strings': [
      "error",
      {
        env: "apollo",
        schemaJson: require("./server/schema.json")
      }
    ]
  },
  plugins: ["graphql"]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Running eslint using lint-staged. If I have an import order warning I want it to be fixed. However, I don't want the warnings to show up while coding. It would be awesome for them to be fixed just when I commit by using the command belong along with husky and lint-staged.

```bash
eslint --fix --max-warnings=0 --rule 'import/order: 1'
```

**What did you expect to happen?**
import/order warnings to be fixed automatically.

**What actually happened? Please include the actual, raw output from ESLint.**
There is not output and no changes. The import/order warnings are not being checked or fixed. If I add the import/order rule to my eslint config then it works but then I have the warning while coding. I would just like it when committing.

**Comment by platinumazure** [comment]
Hi @tgreen7, thanks for the issue.

There are a few possibilities for where the issue is (ESLint, lint-staged, husky, eslint-plugin-import, etc.). Would it be possible to do one or both of the following to help us narrow the issue down?

1. Run ESLint with the `--debug` CLI option (running through lint-staged/husky), if possible, and provide that output here
1. Create a simpler reproduction case by (e.g.) using a core rule, removing husky and/or lint-staged, etc. so we can see if the problem is really in ESLint

Thanks!

**Comment by tgreen7** [comment]
@platinumazure I ran the command on a single file and it seems to be working, so I guess this is an issue with one of the other packages listed. I will close this ticket and keep looking into it.
