### ISSUE TITLE
space-infix-ops: relaxed version

### ISSUE THREAD

**Issue by madbence** [eslint/eslint#1016]
I think the `space-infix-ops` is too strict, the code is often more readable when spaces are used only around low precedence operators:

```js
// readable, operator precedence is obvious
var foo = bar*baz + qux*woof;

// not so readable
var foo = bar * baz + qux * woof;
```

But I'm not sure how to generalize this behaviour...

**Comment by gyandeeps** [comment]
Any update on how we are managing this as this issue has been opened for a long time now.

**Comment by nzakas** [comment]
Let's just close it - it's been open almost a year without any progress.
