### ISSUE TITLE
Parsing error: Unexpected token * on Unix Environment

### ISSUE THREAD

**Issue by AjayU** [eslint/eslint#10177]
Getting the "Parsing error: Unexpected token *" on UNIX environment when we execute the build of our react app. 

This issue is intermittent and occurs but is frequent. I thought it could be due to the large amount of file parsed for scanning. But the same build works perfectly in windows environment.

The eslint rules file is 

{
	"parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
			"modules": true,
			"blockBindings": true,
			"defaultParams": true,
			"destructuring": true,
			"generators": true
        }
    },
"plugins": [
        "react",
	"import"
    ],
	"extends": ["eslint:recommended", "plugin:react/recommended","plugin:import/errors","plugin:import/warnings"],
	"env":{
		"es6": true,
		"browser": true,
		"node": true
	},
"settings": {
		"import/ignore": [".css$","node_modules/*"],
        "react": {
            "pragma": "React",
            "version": "15.6.0"
        }
    }
}

**Comment by nicoxxie** [comment]
we have been seeing the same issue since yesterday, it was working on a build 15 minutes before.

```
"eslint": "4.19.1",
    "eslint-plugin-babel": "5.0.0",
    "eslint-plugin-filenames": "1.2.0",
    "eslint-plugin-import": "2.10.0",
    "eslint-plugin-jest": "21.15.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.7.0",
    "eslint-watch": "3.1.4"
```

Error out put

**Comment by ljharb** [comment]
There may not have been a package.json update, but a transitive dependency (anything in your dep graph) could have been published. That seems a likely suspect.

**Comment by dammo001** [comment]
I found that the issue was caused by an update in [this dependency](https://github.com/estools/esquery) from 1.0.0 -> 1.0.1

**Comment by platinumazure** [comment]
Hi @dammo001, do you know for sure it's that dependency? I looked at all commits between 1.0.0 and 1.0.1 and did not see an exponentiation operator anywhere, but maybe I'm not looking correctly.

**Comment by dammo001** [comment]
Yeah I'm not 100% sure what about it caused the issue, but when I version locked it to 1.0.0 the problem went away.

**Comment by platinumazure** [comment]
@dammo001 And you definitely haven't locked any other dependencies, just that one? (Don't worry, I'm still digging on the esquery side.)

**Comment by nicoxxie** [comment]
It is passing again without any changes, no more parsing error.

**Comment by platinumazure** [comment]
Hi @dammo001, I have done the following to check esquery and it isn't showing any evidence of `**` operator (error message: Unexpected token *):

1. Grep for `**` in a local clone of the repo (we just get comments beginning with `/**`)
1. Adding eslint and eslint-plugin-node and running eslint-plugin-node's `no-unsupported-features` rule, which should flag for exponentiation operator against the configured `engines: { node: ">=0.6" }` in package.json
1. Checked for esquery dependencies being changed between 1.0.0 and 1.0.1, nothing changed

Unless you're seeing a different error message, I can see no reason why esquery should be the problem in your case.

Are you no longer seeing failures, similar to [this comment](https://github.com/eslint/eslint/issues/10177#issuecomment-378346433)?

@AjayU Are you still seeing errors?

**Comment by dammo001** [comment]
@platinumazure I apologize, after looking into it further, you are totally right. It looks like the real issue was [this](https://github.com/babel/babel/issues/7654) or something close to it.

**Comment by ljharb** [comment]
Seems like this can be closed.
