### ISSUE TITLE
This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by xiaoyueyue165** [eslint/eslint#10176]
**Tell us about your environment**

* **ESLint Version:** 4.18.2
* **Node Version:** 8.93
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "name": "react-blog",
  "version": "1.0.0",
  "scripts": {
    "dev": "webpack-dev-server --open --history-api-fallback",
    "build": "webpack -p",
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint **/*.js",
    "lint-html": "eslint **/*.js -f html -o ./reports/lint-results.html",
    "lint-fix": "eslint --fix **/*.js"
  },
  "dependencies": {
    "antd": "^3.3.1",
    "babel-plugin-import": "^1.6.7",
    "jquery": "^3.3.1",
    "puppeteer": "^1.2.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "bundle-loader": "^0.5.5",
    "cross-env": "^5.1.3",
    "css-loader": "^0.28.9",
    "eslint": "^4.18.2",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.9.0",
    "file-loader": "^1.1.6",
    "history": "^4.7.2",
    "html-webpack-plugin": "^2.30.1",
    "jsx-loader": "^0.13.2",
    "open-browser-webpack-plugin": "0.0.5",
    "react-router": "^4.2.0",
    "style-loader": "^0.19.1",
    "uglifyjs-webpack-plugin": "^1.1.6",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
  },
  "license": "MIT"
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
https://github.com/xiaoyueyue165/react-blog
```

```bash
npm run lint --fix
```

**What did you expect to happen?**
````
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-blog@1.0.0 lint: `eslint **/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-blog@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yanyue\AppData\Roaming\npm-cache\_logs\2018-04-03T09_10_39_948Z-debug.log
````

**What actually happened? Please include the actual, raw output from ESLint.**

I don't know how to do this. I haven't been able to correct my mistake for a long time. I'm getting an error. Why is this? May you ask me questions.

<details>
<summary>debug.log</summary>

```js
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Alike\\Environment\\nodejs\\node.exe',
1 verbose cli   'D:\\Alike\\Environment\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint',
1 verbose cli   '--fix' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle react-blog@1.0.0~prelint: react-blog@1.0.0
6 info lifecycle react-blog@1.0.0~lint: react-blog@1.0.0
7 verbose lifecycle react-blog@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle react-blog@1.0.0~lint: PATH: D:\Alike\Environment\nodejs\node_modules\npm\bin\node-gyp-bin;e:\Front-end\react-blog\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;D:\Alike\TortoiseGit\bin;D:\Alike\Environment\java-jdk-1.70\bin;D:\Alike\Environment\nodejs\;C:\Program Files\TortoiseSVN\bin;D:\Alike\A-PCMaster\Git LFS\Git LFS;D:\Alike\pandoc\;C:\Users\yanyue\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
9 verbose lifecycle react-blog@1.0.0~lint: CWD: e:\Front-end\react-blog
10 silly lifecycle react-blog@1.0.0~lint: Args: [ '/d /s /c', 'eslint **/*.js' ]
11 silly lifecycle react-blog@1.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle react-blog@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: react-blog@1.0.0 lint: `eslint **/*.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Alike\Environment\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Alike\Environment\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-blog@1.0.0
15 verbose cwd e:\Front-end\react-blog
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Alike\\Environment\\nodejs\\node.exe" "D:\\Alike\\Environment\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint" "--fix"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error react-blog@1.0.0 lint: `eslint **/*.js`
22 error Exit status 1
23 error Failed at the react-blog@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</details>

**Comment by platinumazure** [comment]
Can you please include the ESLint output? (Try running ESLint directly from the command line. You may need to use `./node_modules/.bin/eslint` to ensure you are targeting the locally installed ESLint.)

**Comment by xiaoyueyue165** [comment]
I do install it locally and it is not possible to run directly on the cmd command line.

**Comment by mysticatea** [comment]
Please try `.\node_modules\.bin\eslint` or [eslint-cli](https://github.com/eslint/eslint-cli#eslint-cli).

**Comment by GitHub1396** [comment]
Perfect! yarn add eslint-cli solves the issue for me.
Thank you @mysticatea

**Comment by sonaskyla12** [comment]
please help me ...currently i m working on windows
with npm -v =5.3.0 and node -v =v10.4.0 and i m getting this error
'nodemon' is not recognized as an internal and external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! erno 1
npm ERR! mernstack@1.0.0 server : 'nodemon server js'
npm ERR! Exit status 1
npm ERR! failed at the mernstack@1.0.0 server script
npm ERR! this probably not the problem with npm .There is additional logging output above
npm ERR! A complete log of this run can be found in :
C:\User\shubhendu\APPdata\roaming\npm-cache_logs\2018-06-22T03_20_40_649Z-debug.log

**Comment by sonaskyla12** [comment]
and i have tired all the solution describe above

**Comment by sonaskyla12** [comment]
.\node_modules\.bin\eslint
after trying this on my visual studio code 
i m getting an error "command not found"

**Comment by platinumazure** [comment]
@sonaskyla12 Please file a new issue. Thanks!

**Comment by platinumazure** [comment]
Closing as the original issue has been solved.

**Comment by robiadiprawira** [comment]
hey, i have same error like this 

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Halallocal@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Mylocal@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.`

**Comment by ErKiran** [comment]
This problem arises from the npm package which is incompatible with the react package you have.
Try Updating both package or uninstall the package which is causing this problem.

**Comment by robiadiprawira** [comment]
@ErKiran well, i have solved this issue.. 
when uninstall the package which is causing this problem help me out with this issue ... 
great thanks ...

**Comment by not-an-aardvark** [comment]
If you're encountering an error that looks like this, please file a new issue or ask for help in our [Gitter channel](https://gitter.im/eslint/eslint). The error message "This is probably not a problem with npm..." typically occurs anytime ESLint exits with an error, so it's unlikely that the problem you're encountering is related to the original issue here.

**Comment by not-an-aardvark** [comment]
Locking this issue since discussions about fixes for this error message are likely to be misleading to users that come across this issue in the future (see the above comment).
