### ISSUE TITLE
Support for ignoring Jekyll front matter?

### ISSUE THREAD

**Issue by dylanbah** [eslint/eslint#10189]
* **ESLint Version:** 4.19.1
* **Node Version:** 9.4.0
* **npm Version:** 5.8.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

For our project we're using Jekyll front matter to denote that a javascript file should be processed by babel. That is, our Javascript files that we would like to be babelified we start with the following:

    ---
    ---

This works fine for having Jekyll run babel on the file, but eslint complains because it is not valid Javascript. Eslint completely fails to parse the file and instead errors out on the first real line of code with the following error:

    Parsing error: Unexpected token const

Is there any way to have eslint ignore frontmatter? I tried multiple comments as documented here https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments but none seem to resolve the issue as the frontmatter is not valid Javascript.

Any ideas for how to resolve this? I would like to parse the files with eslint despite them having front matter.

**Comment by platinumazure** [comment]
Hi @dylanbah, thanks for the issue.

What you need is a plugin with a processor that will strip out the YAML frontmatter and send only the JS to ESLint. There is a plugin, [eslint-plugin-frontmatter](https://www.npmjs.com/package/eslint-plugin-frontmatter), which seems to do this. However, it is a fairly new plugin and may have bugs.

I've done a quick skim of the plugin's source code and have identified one possible bug and one limitation.

Possible bugs:
* I don't see any line number adjustments for messages, so line numbers for ESLint errors might be off by a few lines.

Known limitations:
* This plugin does not support autofix, so you will basically lose ESLint's autofix capabilities on all of your JS files if you use this plugin.

The ESLint team does not maintain this plugin. It looks like the GitHub repository for this plugin can be found [here](https://github.com/duhaime/eslint-plugin-frontmatter).

Hope this helps!

**Comment by platinumazure** [comment]
Updating this issue again: I've written some PRs to fix at least some of the bugs, so it should work better than it did as of my last comment. Please open an issue in the [eslint-plugin-frontmatter repository](https://github.com/duhaime/eslint-plugin-frontmatter) if you run into any issues.

Closing as the question has been answered.
