### ISSUE TITLE
eslint crashes when encounter a comment starting with "eslint"

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10193]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 9
* **npm Version:** 5

**What parser (default, Babel-ESLint, etc.) are you using?**
default

[eslint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHVubGlrZSBtZSovXHJcbmZvbzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7Im5vLXVudXNlZC12YXJzIjoyfSwiZW52Ijp7fX19)

```js
/*eslint unlike me*/
foo;
```

**What did you expect to happen?**
no error thrown. I think it make more sense just to ignore -- it's just a comment.

**What actually happened? Please include the actual, raw output from ESLint.**
1:1 - Failed to parse JSON from ' unlike me': Unexpected token u in JSON at position 2

**Comment by platinumazure** [comment]
This is working as designed: Block comments starting with "eslint" are assumed to be inline rule configuration comments and everything following that comment must be valid levn (not JSON).

More details can be found [here](https://eslint.org/docs/user-guide/configuring#configuring-rules).

If you think the error message could be improved (e.g., to tell the user that we're trying to interpret it as an inline configuration), I think a PR could be very useful.

**Comment by Aladdin-ADD** [comment]
Thanks for the answer, however it seems a little overkill. it means a user cannot use a comment starting with "eslint", even it's just a plain comment. 😞 
 
It make more sense to only parsing specific format comment. could this be an enhancement?

**Comment by Aladdin-ADD** [comment]
Closing as it seems working as intended. Please feel free to comment here or stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you have any further questions. Thanks!
