### ISSUE TITLE
Use eslint-plugin-markdown for parsing only?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#10197]
Can we use eslint-plugin-markdown for parsing only?

There are still plenty of open questions on how we could support intentional violations in markdown blocks (i.e., all of our "incorrect code" examples). But I'm wondering if we could pull in the plugin and use it with no rules enabled to help catch minor mistakes in documentation examples.

@btmills Does this sound plausible, technically speaking?

Team: Is this worth considering?

**Comment by not-an-aardvark** [comment]
Sounds reasonable to me. We could have an override with a config containing no rules that applies to all `.md` files.

There might be some places where we intentionally use invalid syntax for some reason, but if they exist I suspect they are probably rare and could be manually disabled.

**Comment by btmills** [comment]
@not-an-aardvark’s suggestion of an override for `.md` files sounds like the way to go.

As for disabling, if that comes up, there’s `<—eslint-skip—>` to ignore the code block entirely, don’t even parse it.
