### ISSUE TITLE
eslint --init Command not found

### ISSUE THREAD

**Issue by usulla** [eslint/eslint#10192]
Hi!
I want to set globally the module settings for all projects.
I try: 
`npm install -g eslint`

After I enter:
`eslint --init`

And after that I see:
`eslint: command not found`

Tell me, please, what is my mistake?

**Comment by platinumazure** [comment]
It sounds to me like the global npm bin path is not in your PATH environment variable. You can check this by looking at the result of `npm bin -g` and see if that path shows up in the PATH environment variable.

If you can tell us your OS and shell, we could provide more specific guidelines if you need help checking this.

**Comment by nemyxa** [comment]
@platinumazure, i have same problem, on ubuntu lts, but instead npm i use yarn. I did "yarn global add eslint", and in workspace folder "eslint --init". output is
eslint: command not found

**Comment by LiviuLvu** [comment]
Encountered the same error when trying eslint --save-dev in a local project.

This tutorial about PATH was helpful (mac OS):
https://www.youtube.com/watch?v=3MhWLqOuKRs

Also found helpful instructions in this post:
http://notions.me/post/adding-npm-bin-to-path

Now I added these 2 lines to my /etc/profile:
export PATH=/usr/node_modles/.bin:PATH
export PATH=$PATH:./node_modules/.bin

Works but I do not understand why or which line fixed the issue :)
The [zsh: command not found: eslint error] is fixed and eslint starts.

**Comment by LiviuLvu** [comment]
I did that and int says
```
Cannot find module 'eslint-config-airbnb-base'
Referenced from: /Users/liviu.iancu/Documents/learn-js-patterns/.eslintrc.json
Error: Cannot find module 'eslint-config-airbnb-base'

```
Then I uninstalled the global eslint and it says

**Comment by glntlq** [comment]
I guess you didn't install eslint successfully

**Comment by Shyroby** [comment]
Are you using powershell?

**Comment by nzakas** [comment]
This is definitely an installation issue. The most likely problem is that your `PATH` environment variable does not contain the global npm folder. 

As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
