### ISSUE TITLE
[Help Request] Semicolon placement configuration

### ISSUE THREAD

**Issue by Daniil-Pabolkov** [eslint/eslint#10226]
I have some problem with placement of semicolon in multyline call chain: I want to place semicolon in the new line after call chain. (I don't found resolves of my problem in docs)

For example, lets look for next code:
```javascript
const arr = [];

// Inline style:
arr.map(x => x).filter(x => x).sort((a, b) => (a >= b) * 2 - 1);

// My style:
arr
   .map(x => x)
   .filter(x => x)
   .sort((a, b) => (a >= b) * 2 - 1)
; // << Semicolon placement here (in my sweet dreams)

// ESLint fixer result:
arr
   .map(x => x)
   .filter(x => x)
   .sort((a, b) => (a >= b) * 2 - 1); // << Semicolon placement here, but I didn't want this end
```

* **ESLint Version:** 4.19.0
* **Node Version:** 8.9.1
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint / 8.2.2

Does ESLint have rule for setting this behavior? Otherwise whether can you add it?

**Comment by ilyavolodin** [comment]
`semi-style` only enforces position of semi-columns, as in at the beginning of the string or the end. It doesn't enforce semi-columns to be on a separate line in case of chaining.

**Comment by Daniil-Pabolkov** [comment]
@ilyavolodin Thanks for suggestion.

**Comment by amoshydra** [comment]
@Daniil-Pabolkov
This might be what you are looking for https://github.com/justinanastos/eslint-plugin-justinanastos/blob/master/docs/rules/chained-semi.md
