### ISSUE TITLE
New rule: indent [$100]

### ISSUE THREAD

**Issue by jrajav** [eslint/eslint#1022]
Ref discussion in https://github.com/eslint/eslint/pull/1019. New rule to enforce a certain style of indentation across a whole file. There are various possibilities for options: You can have tabs-only, spaces-only, or either-but-consistent, and you can have smart tabs (spaces allowed for aligning statement continuations) or no.

To continue the discussion in https://github.com/eslint/eslint/pull/1019 I see this as being a little redundant with a line-by-line option - they would have almost the same effect, except that the line-by-line option of no-mixed-spaces-and-tabs would allow you to switch off tabs and spaces for every line in the same file, which would be unreadable if you didn't have the same tabwidth it was written with. It could also be confusing to have two almost identical rules. Still, having both would be better than having none.

**Comment by lo1tuma** [comment]
@nzakas Do you still want to see my implementation when it is ready or should I stop working on this?

**Comment by nzakas** [comment]
Up to you. If you think it's worth continuing because you have a better way of doing it, then I'd be very happy to see it.
