### ISSUE TITLE
Node.js API docs: CLIEngine#getConfigForFile references deprecated linter property

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#10228]
CLIEngine#getConfigForFile references `require("eslint").linter` in an example. Might be better to reference `require("eslint").Linter` instead.

Can be found [here](https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile).

**Comment by santanaG** [comment]
Is there anything else left to evaluate here? I can make the change on the go ahead.

**Comment by platinumazure** [comment]
Hi @santanaG, I don't think so, mostly I wanted to give the team a chance to object. But we've had more than enough time :smile:

I've marked this as "accepted" and look forward to your PR. Thanks!

**Comment by nzakas** [comment]
Fixed by # 10864
