### ISSUE TITLE
Feature request: line padding for array and object literals, like block-padding rule.

### ISSUE THREAD

**Issue by trusktr** [eslint/eslint#10232]
It'd be nice to have padding also for multi-line array and object literals.

For example, if I have this code,

```js
        data: () => ( {
            isMobile: true,
            isDesktop: false,
        } ),
```

I'd like to force it to be

```js
        data: () => ( {

            isMobile: true,
            isDesktop: false,

        } ),
```

and similar with array literals. Basically, the same functionality as `padded-blocks`, but applied to literals.

**Comment by trusktr** [comment]
Similar to inner line padding, it'd also be nice if the `padding-line-between-statements` option would allow to add outer padding for object literals (add them to `block-like` and `multiline-block-like`). For example, 

```js
let a = 5
let b = 6
let o = {
    n: 1
}
let o2 = {
    n: 1
}
```

would become

```js
let a = 5
let b = 6

let o = {
    n: 1
}

let o2 = {
    n: 1
}
```

**Comment by trusktr** [comment]
Also, padding for other parens. F.e.

```js
    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= ( window.innerHeight || document.documentElement.clientHeight ) &&
        rect.right <= ( window.innerWidth || document.documentElement.clientWidth )
    )
```

to become

```js
    return (

        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= ( window.innerHeight || document.documentElement.clientHeight ) &&
        rect.right <= ( window.innerWidth || document.documentElement.clientWidth )

    )
```

**Comment by not-an-aardvark** [comment]
Thanks for the feature request. I'm personally not sure this is worth adding to ESLint core, although I'm not opposed to it if there are other team members in favor of it. In either case, keep in mind that you can also [implement this as a custom rule](https://eslint.org/docs/developer-guide/working-with-rules) regardless of whether the ESLint team decides to accept the proposal.
