### ISSUE TITLE
Include #9908 in 4.x.x branch as bugfix

### ISSUE THREAD

**Issue by betaorbust** [eslint/eslint#10244]
**Tell us about your environment**: N/A

* **ESLint Version:** 4.x.x
* **Node Version:** N/A
* **npm Version:** N/A

**What parser (default, Babel-ESLint, etc.) are you using?** N/A

**Please show your full configuration:** N/A

**Issue**

In #9890, we decided to go with a non-breaking change, to address an issue where `data` was required during rule testing with `messageId`. We went with non-breaking bugfix [mentioned here](https://github.com/eslint/eslint/issues/9890#issuecomment-373841059) but looks like it was mistagged as an enhancement in the actual PR https://github.com/eslint/eslint/pull/9908 and was put into the 5x line.

**Proposed Solution**
If there's another minor or patch release for the 4x line, can it also be applied there?

Thanks!

**Comment by not-an-aardvark** [comment]
Hi again, thanks for creating an issue. I don't think we have any plans right now to do another v4.x release unless a critical bug is found (we're mainly working on v5.x right now), but if we do do another release I'll make sure #9908 is included in it.

**Comment by platinumazure** [comment]
Closing as the question has been answered. (We're hoping to release 5.0.0 this weekend.)
