### ISSUE TITLE
context.getScope() depends on parserOptions.ecmaVersion

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#10247]
> I'm sorry that I don't follow issue templates.

From #10227.

`context.getScope()` method depends on `parserOptions.ecmaVersion`: [lib/linter.js#L615-L616](https://github.com/eslint/eslint/blob/a2953ec0c975f6ac8f44fbe6944a6f3116f445cc/lib/linter.js#L615-L616)

However, `ecmaVersion` doesn't exist always because the parser options are defined by each parser. This means the `context.getScope()` method doesn't work correctly with custom parsers.

I think that we should remove the dependency from `context.getScope()` method and fix it to the current `ecmaVersion >= 6` behavior.

To get the current `ecmaVersion < 6` behavior, use `context.getScope().variableScope`.

**Comment by mysticatea** [comment]
I found that removing the `ecmaVersion` check of `lib/linter.js#L615-L616` has only small effects because the `eslint-scope` package is checking `ecmaVersion` and doesn't create block scopes in ES5.

I think there is only the following effect:

- `context.getScope()` on `CatchClause` node in ES5 returns `catch` scope. (currently it returns the parent scope)

Note `context.getScope()` on `CatchClause > BlockStatement` is no change. It returns `catch` scope currently.

**Comment by mysticatea** [comment]
**TSC Summary**: `context.getScope()` should not depend on `parserOptions.ecmaVersion`. The `context.getScope()` probably does not work correctly with custom parsers that don't have `parserOptions.ecmaVersion` option such as `babel-eslint` and `typescript-eslint-parser`. If we remove that dependency, `context.getScope()` on `CatchClause` will be changed. I believe that other changes are nothing.
**TSC Question**: Should we accept this change -- remove the `parserOptions.ecmaVersion` access from `context.getScope()`?

**Comment by not-an-aardvark** [comment]
This issue was accepted in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/c271eee0c355058b90acb511a6e70a0c4520b121/notes/2018/2018-04-26.md#contextgetscope-depends-on-parseroptionsecmaversion).
