### ISSUE TITLE
Documentation search is broken

### ISSUE THREAD

**Issue by s-pace** [eslint/eslint#10259]
👋 Iam working on DocSearch.

I was using your doc when firstly I have noticed you were using DocSearch 👏 . 

But it looks like the search is broken:
![image](https://user-images.githubusercontent.com/32097720/39195993-53a310ae-47e1-11e8-8068-18baf0db44d3.png)

I have made a quick showcase of the version I have made for you, check it out:

http://eslint-docsearch.surge.sh/

--- 

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '891b0e977d96c762a3821e0c00172ac9',
  indexName: 'eslint',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["version:$VERSION", "tags:$TAGS"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace `$VERSION` with the version you want to search on.
   The list of possible version is hardcoded in the config.
   So as of today you have: `1.0.0`, `2.0.0`, `3.0.0`

- Replace `$TAGS` with the tags you want to search on.
   The list of possible tags is hardcoded in the config.
   So as of today you have: `blog`

  For example if you want to refine the search to the version "1.0.0" and the tags "blog" just specify:
```js
 'facetFilters': ["version:1.0.0", "tags:blog"]
```

- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in [our github repo](https://github.com/algolia/docsearch-configs/blob/master/configs/eslint.json).

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

**Comment by ilyavolodin** [comment]
Thanks for the issue. We are currently not using DocSearch, but instead we are using full Algolia search (which is broken because we haven't been able to get our build to work with newer version of Ruby and Algolia gh-pages plugin). @pixelastic did recommend we switch over to DocSearch, but I haven't had a chance yet to look into it.

Also, this issue belongs in https://github.com/eslint/eslint.github.io repository instead, since that's where we deal with our site.

**Comment by s-pace** [comment]
🙏 for the details @ilyavolodin 

I can do a PR if you want?

**Comment by ilyavolodin** [comment]
@s-pace That would be great (I still can't find time to look into DocSearch, but if it will solve our problem with broken search - it's great). If you will be able to create a PR, it should be created against our website repository (https://github.com/eslint/eslint.github.io). While doing indexing on the schedule vs. build is going to cause some minor issues across the release boundaries, I think it's still better than the situation we are currently in.

**Comment by s-pace** [comment]
no sooner said than done #464
