### ISSUE TITLE
no-unused-vars being thrown when variable is being used

### ISSUE THREAD

**Issue by TheIronG** [eslint/eslint#10276]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.4.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "node": true,
        "commonjs": true,
        "es6": true
	},
	"parserOptions": {
        "ecmaVersion": 2017
    },
    "extends": "eslint:recommended",
    "rules": {
		"no-empty": "off",
		"no-console": "off",
		"prefer-const": "error",
		"no-var": "error",
		"linebreak-style": "off",
		"one-var": [
			"error",
			"never"
		],
        "indent": [
            "error",
			"tab",
			{
				"SwitchCase": 1
			}
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let length = 1;
length += util.sizeOfMCString(data.uuid);
length += util.sizeOfMCString(data.username);

const buffer = Buffer.alloc(length);
let offset = util.writeVarInt(0x02, buffer); // no-unused-vars thrown here
offset = util.writeMCString(data.uuid, buffer, offset); // offset is used here and the line below
offset = util.writeMCString(data.username, buffer, offset);
```

```bash
./node_modules/.bin/eslint .
```

**What did you expect to happen?**
No error to be thrown

**What actually happened? Please include the actual, raw output from ESLint.**
no-unused-vars error is thrown
```
C:\Users\REMOVED\Documents\Programming\_minceraft\src\java\protocol\protocol.js
  59:9  error  'offset' is assigned a value but never used  no-unused-vars
```

I would also like to point out that this snippet (from the same file) does NOT throw the error, which adds to my confusion as they are essentially the same:
```js
let length = 1;
length += util.sizeOfMCString(data);

const buffer = Buffer.alloc(length);
let offset = 0;
offset = util.writeVarInt(0x00, buffer);
util.writeMCString(data, buffer, offset);
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is happening because the assignment to `offset` on the last line is unnecessary, since `offset` doesn't get used after that. The last line could simply be rewritten as:

```js
util.writeMCString(data.username, buffer, offset);
```

**Comment by TheIronG** [comment]
Wow, can't believe I didn't notice that. Thanks, closing as that solved my issue
