### ISSUE TITLE
Disable rule for multiline string

### ISSUE THREAD

**Issue by AuthorProxy** [eslint/eslint#10275]
```  
  // eslint-disable-next-statement max-len
  const someToken = `
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.
    eyJpc3MiOiJwb3J0YWwuaHJrZXRpbmcuY29tIiwiaWF0IjoxNTI0NTg5MDEwLCJleHAiOjE1NTYxMjUwMDksImF1ZCI6InBvcnRhbC5ocmtldGluZy5jb20iLCJzdWIiOiJrb3N0eXVrb3ZAaHJrZXRpbmcucnUiLCJHaXZlbk5hbWUiOiJBbGV4IiwiU3VybmFtZSI6Iktvc3R5dWtvdiIsIkVtYWlsIjoia29zdHl1a292QGhya2V0aW5nLnJ1IiwiUm9sZSI6WyJNYW5hZ2VyIiwiUHJvamVjdCBBZG1pbmlzdHJhdG9yIl19.
    j02OSFLofqQOGglYu2VS3Lh8oApf5jZPa_OIrT3scGQ
  `;
```
Some rule like eslint-disable-next-statement will be useful.  eslint-disable-next-line doesn't work at this case

**Comment by AuthorProxy** [comment]
yes, I could and I use, but this is one statement, one string, and just one sample. A lot of regexes or multiline strings needs to be excluded like this, and this is not comfortable at all. I cannot make most of them oneline because I need `\n` to be preserverd and cannot use `disable-next-line`.

**Comment by MarkKahn** [comment]
+1, just came here to find out if anyone else had requested this.  I run into this all the time and always end up wrapping a single statement with `/* eslint-disable/enable */`, which is ugly:

```js
/* eslint-disable no-unused-vars */
const envVariable = process.env.NODE_ENV
  ? (nm: string): ?string => process.env[nm.replace(/[^_0-9a-z]/gi, '_')]
  : (nm: string): void => {};
/* eslint-enable no-unused-vars */
```

`disable-next-line` is also ugly and distracting

```js
const envVariable = process.env.NODE_ENV
  ? (nm: string): ?string => process.env[nm.replace(/[^_0-9a-z]/gi, '_')]
  // eslint-disable-next-line no-unused-vars
  : (nm: string): void => {};
```

I'd much prefer:

```js
// eslint-disable-next-statement no-unused-vars
const envVariable = process.env.NODE_ENV
  ? (nm: string): ?string => process.env[nm.replace(/[^_0-9a-z]/gi, '_')]
  : (nm: string): void => {};
```

**Comment by kaicataldo** [comment]
@AuthorProxy This is difficult to evaluate without a proper proposal. Do you mind writing something up? If not, it might be time to close this since it looks like discussion has stalled.

**Comment by AuthorProxy** [comment]
No, I just wanted to propose an idea, close if you don't want to implement it

**Comment by kaicataldo** [comment]
Closing this since discussion has stalled. If someone would like to write up a proposal, please feel free to make a new issue. Thanks!
