### ISSUE TITLE
no-useless-escape 

### ISSUE THREAD

**Issue by slim-hmidi** [eslint/eslint#10286]
**Tell us about your environment**

* **ESLint Version:** 4.17.0
* **Node Version:** 8.11.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "env": {
        "node": true
    },
    "extends": "airbnb-base"
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
'[2018-02-01, 2018-04-01]'.replace(/[\[ | \]]/g,'')).split(',')
```

```bash

```

**What did you expect to happen?**
```
No eslint error 
```
**What actually happened? Please include the actual, raw output from ESLint.**

```
Unnecessary escape character: \[  no-useless-escape
```

**Comment by platinumazure** [comment]
Hi @slim-hmidi, thanks for the issue.

The rule is working as designed: `\[` is a useless escape when you're already inside a character class. You could write this in the following way:

```js
'[2018-02-01, 2018-04-01]'.replace(/[[ | \]]/g,'')).split(',')
```

That said, I see a few potential issues with your regex. You appear to be using the pipe character as an alternator token to try to search for only left or right square bracket, but that doesn't work in a character class. In reality, the character class will search for left bracket, space, literal pipe, space (again), and right bracket and replace them with empty string. Maybe you want something like `/[[ \]]/` (if you want space and brackets replaced)?

In any case, the `no-useless-escape` rule is working as designed here.

**Comment by slim-hmidi** [comment]
@platinumazure  thanks, it works well.
