### ISSUE TITLE
"node" environment is missing `URL` global

### ISSUE THREAD

**Issue by ravinggenius** [eslint/eslint#10284]
**Tell us about your environment**

* **ESLint Version:** `4.19.1`
* **Node Version:** `10.0.0`
* **npm Version:** `5.6.0`

**What parser (default, Babel-ESLint, etc.) are you using?** `babel-eslint@8.2.3`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "jest": true,
    "node": true
  },

  "extends": [
    "bespoke",
    "plugin:react/recommended"
  ],

  "parser": "babel-eslint"
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
new URL(import.meta.url).pathname
```

```bash
eslint --ext .mjs --ignore-path .gitignore .
```

**What did you expect to happen?**

`URL` to be a known global when specifying `"node": true`. (SEE https://nodejs.org/api/url.html)

**What actually happened? Please include the actual, raw output from ESLint.**

```
4:17  error  'URL' is not defined                      no-undef
```

---

I'm using `babel-eslint` until `import.meta` is more widely supported.

**Comment by kaicataldo** [comment]
It looks like this was added in [globals v11.5](ttps://github.com/sindresorhus/globals/commit/0a57eb52ff7a1c92f227d2441349e0441252e8bb), which we updated to in ESLint v5. Updating to the latest version of ESLint will fix this. Thanks!

**Comment by medikoo** [comment]
It's controversial, as `URL` as global is not exposed with Node.js v8.

So this change breaks for users of Node.js v8 LTS (linter doesn't report that `URL` is undefined)

IMO this should match LTS behavior

**Comment by platinumazure** [comment]
@medikoo You can use the `no-restricted-globals` rule to cover that case.

**Comment by medikoo** [comment]
> @medikoo You can use the no-restricted-globals rule to cover that case.

Yes, same way I can just turn off this in `globals`.

Issue here is, that default setting doesn't reflect LTS version, eventually two node envs should be set, e.g. `node-lts` and `node-non-lts`
