### ISSUE TITLE
Question: AST - How do I match against a nested array attribute?

### ISSUE THREAD

**Issue by ryami333** [eslint/eslint#10295]
I'm trying to write a selector for a `JSXOpeningElement` which contains a certain prop value, `foo`.

_This_ matches the `JSXAttribute`:
```
JSXOpeningElement > JSXAttribute[name.name=foo]
```

But I actually want something more like the following, because I want to match the `JSXOpeningElement` rather than the `JSXAttribute`:
```
JSXOpeningElement:has(JSXAttribute[name.name=foo])
```

or
```
JSXOpeningElement[attributes[].name.name=foo]
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue. As far as I know, it's not possible to match the parent node with a selector in this case. However, if you're writing a custom rule you could access the parent node by creating a selector that matches the child node, and then accessing `node.parent`.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
