### ISSUE TITLE
Anti human things, disappear

### ISSUE THREAD

**Issue by modifMX** [eslint/eslint#10290]
**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

Anti human things, disappear
 ضد الإنسانية  ما  تختفي 
反人类东西，消失
사람의 물건을 반반하여 사라지다
人を逆にする
สิ่งที่ต่อต้านมนุษย์และหายไป
что - то  против человечества  ,  исчезнуть
az emberiség el valamit,
Quelque chose a disparu contre l'humanité
Nada contra a humanidade desaparecer

**Comment by not-an-aardvark** [comment]
Closing because this doesn't appear to be related to ESLint.
