### ISSUE TITLE
New Feature Proposal - `no-throw-literal` fix

### ISSUE THREAD

**Issue by yinonc** [eslint/eslint#10296]
**The version of ESLint you are using.**
4.19.1
**What rule do you want to change?**
I would like to propose a fix for `no-throw-literal` rule.
**Does this change cause the rule to produce more or fewer warnings?**
When applying fix not for all the test cases, `eslint-plugin/consistent-output` error is coming up, so I had to disable by now the rule for this specific file.
**How will the change be implemented? (New option, new default behavior, etc.)?**
The change will be implemented with `eslint` standard fixer, keeping it simple and readable.

Examples for test changes:
```js
{
            code: "throw 'error';",
            output: "throw new Error('error');",
            errors: [{
                message: "Expected an object to be thrown.",
                type: "ThrowStatement"
            }]
},
{
            code: "throw 0;",
            output: "throw new Error(0);",
            errors: [{
                message: "Expected an object to be thrown.",
                type: "ThrowStatement"
            }]
        }
```

**What does the rule currently do for this code?**
Currently the rule is providing indication when there is a invalid throw statement, and do not have a fix option.
**What will the rule do after it's changed?**
After changing, the rule would have a fix option. By now the fix would be simple and would solve 90% of wrong throw statements (won't fix string templates and string concatenation at first).

https://github.com/eslint/eslint/pull/10300

**Comment by platinumazure** [comment]
Didn't see this issue at first or I would have just left my comment here:

Do runtimes currently wrap non-Error objects in `Error` instances specifically? If not, I'm mildly :-1: to this autofix simply because the user might actually prefer to use a different error type such as RangeError.

**Comment by yinonc** [comment]
Hi thanks for your comment!
In my opinion, a developer which throws a string, clearly doesn't know what he's doing. Anyway he needs to pass the lint, and this would be his fastest and safest way.
For anyone who distinguishes between different kind of error objects, he would probably code his specific needed kind of error.

**Comment by platinumazure** [comment]
Thanks @yinoc. In our autofix code, we try really hard not to change runtime behavior (without good reason) and we try to only suggest fixes that should be non-controversial (given the rule's configuration). In this case, I don't think we can know what type of error the user wants to use.

I'm willing to go with ESLint team consensus if they feel this is a worthwhile change.

**Comment by not-an-aardvark** [comment]
I'm :-1: for autofixing this because it would change runtime behavior.

**Comment by platinumazure** [comment]
@yinonc Thanks for explaining your reasoning, greatly helps.

> Developer that throws a literal is probably **not aware that he's losing the stack trace**, therefor changing to a default error can only help him.

I agree with your claim that the developer is probably not aware of the lack of stack trace (at least, in most cases). However, this is only a rationale for *reporting* the issue, not necessarily for prescribing a particular fix.

> When someone throws a literal, he doesn't know anyway what kind of error he would like to throw.

And (IMO) this is why we shouldn't choose for them. Instead, we should report and not fix, so that the developer has to research and make a choice.

Thanks again for the spirited discussion!

**Comment by ljharb** [comment]
This autofix would break codebases I work in; while it's a best practice to always throw an Error instance, there are times you want a promise that's rejected with a non-Error value, for example.

**Comment by ilyavolodin** [comment]
While this fix will make sense most of the time, our rule for auto-fixes is to not modify runtime behavior, and this would modify it and have a very good potential to break your code (as @ljharb mentioned). So I don't think we can accept this.

**Comment by not-an-aardvark** [comment]
I'm closing this issue because it seems like there is consensus among the ESLint team that we don't want to add an autofixer for this rule. We appreciate the contribution regardless!
