### ISSUE TITLE
eslint --init messes up binaries for projects using yarn

### ISSUE THREAD

**Issue by elyalvarado** [eslint/eslint#10293]
`eslint --init` uses npm which messes up the binaries installed by yarn. This issue will affect any project using yarn.

Even worse, it also runs some packages uninstall scripts, which in the case you're using `husky` will remove the installed git hooks.

An asciinema recording of the steps to reproduce the issue, and its effects, can be found here:

[https://asciinema.org/a/T200B8Qgg7QepzHw5w1TbtuoC](https://asciinema.org/a/T200B8Qgg7QepzHw5w1TbtuoC)

* eslint@4.19.1
* Node version 10.0.0
* npm version 5.6.0
* yarn version 1.6.0

No eslint configuration needed to reproduce this issue.

**Steps to reproduce**

The following steps reproduce the issue in a test project:

```bash
mkdir eslint-init-with-yarn
cd eslint-init-with-yarn
git init .
ls -ltr .git/hooks
yarn init .
yarn add husky eslint --dev
# Check that husky created the hooks
ls -ltr .git/hooks
# Check the binaries added by yarn in the node_modules dir
ls node_modules/.bin
yarn eslint --init
# Answer with predefined AirBNB style guide, no react, using a JSON configuration file

# Check that the hooks disappeared
ls .git/hooks
# Also the binaries
ls node_modules/.bin
```

**What did you expect to happen?**

Previously binaries installed by yarn to keep existing, and the git hooks not being removed.

**What actually happened? Please include the actual, raw output from ESLint.**

The binaries previously installed by yarn were deleted, and the commit hooks created when installing `husky` also were removed (the uninstall script for husky was run).

**Comment by elyalvarado** [comment]
A work around for those affected by this issue is removing your `node_modules` folder and running `yarn install` again

**Comment by kaicataldo** [comment]
Apologies that we lost track of this. Though a specific solution isn't mentioned here, it sounds like you're advocating for Yarn support in ESLint. This has been discussed [before](https://github.com/eslint/eslint/pull/9023), and the team decided at that time not to add this enhancement. If you have a concrete solution/proposal, please feel free to share it here so that we can evaluate.

**Comment by not-an-aardvark** [comment]
Is this still a problem now that https://github.com/eslint/eslint/issues/9918 has been implemented?

**Comment by elyalvarado** [comment]
@not-an-aardvark you're right. This shouldn't be a problem after #9918 , so its safe to close

**Comment by not-an-aardvark** [comment]
Thanks for confirming. Closing this issue.
