### ISSUE TITLE
prefer-default-export weird behavior?

### ISSUE THREAD

**Issue by dmitry-saritasa** [eslint/eslint#10303]
If I have a single index.js file with single line re-exporting import as shown below

```bash
➜ tree  src/lib/mixins 
src/lib/mixins
├── form-validation.js
└── index.js

```

```js
export { default as FormValidationMixin } from './form-validation';
```

then I get eslint error " 1:10  error  Prefer default export  import/prefer-default-export"

however if I add the 2nd line then the error is gone

```js
export { default as FormValidationMixin } from './form-validation';
export { default as FormValidationMixin2 } from './form-validation';
```

**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.7.0
* **npm Version:** 5.4.2

My **.eslintrc.js**
https://gist.github.com/dmitry-saritasa/f63e2fe57405f9a409d86046ee6608c4

extraction from **package.json**
```
    "babel-eslint": "^8.2.1",
    "eslint": "^4.17.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-import-resolver-babel-module": "^4.0.0",
    "eslint-import-resolver-configurable": "^0.1.3",
    "eslint-import-resolver-webpack": "^0.9.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-compat": "^2.2.0",
    "eslint-plugin-eslint-comments": "^2.0.2",
    "eslint-plugin-html": "^4.0.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-vue": "^4.2.2",
```

**Comment by Aladdin-ADD** [comment]
Thanks for the issue, however seems it's related to `eslint-plugin-import` -- not in eslint core. you can file the issue in [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import).

**Comment by dmitry-saritasa** [comment]
Got it thank you!
