### ISSUE TITLE
ESLint run one single rule (indent)

### ISSUE THREAD

**Issue by Ronnyrr** [eslint/eslint#10304]
I want to change the indenting of my project from 4 to 2 spaces using ESLint. Basicly I want to ignore all rules except de indenting. 

Currently I have to following ESLint config. 

    {
        "plugins": [
            "react"
        ],
        "rules": {
            "react/jsx-indent": [
                "error",
                2
            ],
            "react/jsx-indent-props": [
                "error",
                2
            ],
            "indent": [
                "error",
                2
            ]
        }
    }

But when I run this config using `eslint -c ./eslint4-2.json src/*` I get parsing error like: `1:1  error  Parsing error: The keyword 'import' is reserved`. But this is not where I want to look for. 

I also tried the command line `eslint --no-eslintrc src/* --rule 'indent:[2,2]'`, but this gives the same 
Parsing error as above. If I remove the folder setting I get: 

```

    eslint [options] file.js [file.js] [dir]
    
    Basic configuration:
    ....
```

ESLint version: v4.19.1

**Comment by Aladdin-ADD** [comment]
You need specify `ecmaVersion`(default to 5) if you're using es5+. eg:
```js
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "module"
    },
```
refs: [specifying-parser-options](https://eslint.org/docs/user-guide/configuring#specifying-parser-options)

**Comment by Ronnyrr** [comment]
Thanks @Aladdin-ADD, this seems to solve this problem indeed. But it doens't lint all my files correctly. Currently I run `eslint -c eslint4-2.json ./src/* --ext .jsx --ext .js --rule 'indent:[2,2]'`, and my config looks like:

```
{
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "react/jsx-indent": [
            "error",
            2
        ],
        "react/jsx-indent-props": [
            "error",
            2
        ],
        "indent": [
            "error",
            2
        ]
    }
}
```

I got a file structure as seen in the attachment, but it only lints the `App.jsx` and `Root.jsx`. It ignores the files in subfolders. When I run 
`eslint -c eslint4-2.json --debug ./src/**/* --ext .jsx --ext .js` ESLint does reach the files, but passes them:

```
  eslint:linter Linting code for /Users/ronny/Projecten/react-prime/src/app/components/common/Button/index.jsx (pass 1) +3ms
  eslint:linter Generating fixed text for /Users/ronny/Projecten/react-prime/src/app/components/common/Button/index.jsx (pass 1) +22ms
```

I have no clue why the files are passed. Any suggestions or solutions?

![screen shot 2018-05-03 at 14 57 31](https://user-images.githubusercontent.com/4519142/39577717-5b6f4dd6-4ee2-11e8-954a-c6addc58687c.png)

**Comment by Aladdin-ADD** [comment]
I got a little confused. `eslint ./src/* ` vs. `eslint ./src/**/* --debug`.

does running `eslint src/**/*` solve the problem 😄 ?

**Comment by platinumazure** [comment]
@Ronnyrr When you pass this pattern `./src/*`, that will only look for files in that src folder without recursing into subfolders. That's why App.jsx and Root.jsx are linted.

If you're using the `--ext` flag to specify that you want jsx and js files linted, then you could probably just pass `./src` to ESLint and it should do the right thing and lint every js and jsx file in that directory. If there are files that you don't want linted, you could use an [`.eslintignore` file](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories).

Hope this helps!

**Comment by Ronnyrr** [comment]
Thanks for helping out. That was my bad. I also tried running `eslint ./src/**/*`, but that doesn't help either. 

I found that ESLint is throwing other error in those files:

`/Users/ronny/Projecten/tryouts/react-prime/src/app/components/modules/Demo/index.jsx
  23:52  error  Parsing error: Unexpected token ..` 

It breaks on spread operators. Any idea how to solve this?

**Comment by platinumazure** [comment]
@Ronnyrr You need to use `ecmaVersion: 9` (in parserOptions) or `experimentalObjectRestSpread: true` (in parserOptions.ecmaFeatures) in order for espree (default parser) to parse object spreads.

**Comment by Ronnyrr** [comment]
Great! Thanks for helping out. This solve my issue! :)
One last thingy. It skips `styled-components` inside components. For example:

```
const CenteredSection = styled.section`
    display: flex;
    padding: 0 20px;
`;


const Demo = ({ installation: { passed, loading }, ...props }) => (
  <CenteredSection>
    <LogoIcon />
    <Button onClick={props.install}>Click Me</Button>
  </CenteredSection>
);
```

The `Demo` components is now linted to 2 spaces, but the styled components const in the same file is still 4 spaces. 

```
    "plugins": [
        "react",
        "styled-components-config"
    ],
```

I've added and installed the `styled-components` npm packages as you can see above, but it still ignores it. Any idea why?

**Comment by platinumazure** [comment]
Hi @Ronnyrr, sorry for losing track of this.

Unfortunately, I don't know about the styled-compoments and/or react plugins enough to know what rules are needed to fix styled.section templates. However, I can tell you that the `indent` rule, by default, does not care about the inside of template literals at all, so you'd definitely need a separate rule to handle the styled.section templates.

Sorry this isn't much help.

**Comment by Ronnyrr** [comment]
No worries. Thanks for your reply, fixed it with Prettier tho ;)
