### ISSUE TITLE
Fix should also indent comments the same as code

### ISSUE THREAD

**Issue by BridgeAR** [eslint/eslint#10318]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 11-pre
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

```js
indent: error
```
This is only about the fixer of indent.

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
'use strict';

class Foo {
bar() {
  if (true) {
    console.log('foo');
  } else if (false) {
    // This is a comment starting at the line beginning.
    console.log('bar');
  } else {
    // Do something
  }
  return 'hello world';
}
}
```

**What did you expect to happen?**

The expected output is:

```js
'use strict';

class Foo {
  bar() {
    if (true) {
      console.log('foo');
    } else if (false) {
      // This is a comment starting at the line beginning.
      console.log('bar');
    } else {
      // Do something
    }
    return 'hello world';
  }
}
```

But instead it results in:

```js
'use strict';

class Foo {
  bar() {
    if (true) {
      console.log('foo');
    } else if (false) {
    // This is a comment starting at the line beginning.
      console.log('bar');
    } else {
    // Do something
    }
    return 'hello world';
  }
}
```

So if the code lines above and below a comment get indented the same, it should also indent the comments appropriately. That they are ignored this way results in weird indentation.

**Comment by sstern6** [comment]
I believe this is closely related to https://github.com/eslint/eslint/issues/9733.

@not-an-aardvark @platinumazure

**Comment by not-an-aardvark** [comment]
I think the two issues are loosely related in that both of them concern how the `indent` rule treats comments, but it should be possible to solve them independently.

> So if the code lines above and below a comment get indented the same, it should also indent the comments appropriately. That they are ignored this way results in weird indentation.

This seems reasonable to me. I'd be in favor of this enhancement as long as it doesn't add too much complexity.
