### ISSUE TITLE
Missing non existing class parameter 'k'

### ISSUE THREAD

**Issue by Zydnar** [eslint/eslint#10311]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 9.0.0
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint + babel-eslint+ WebStorm

**Please show your full configuration:**
https://pastebin.com/yzCgfgEQ

https://pastebin.com/0mzMg0SE

Eslint with Jetbrains WebStorm and babel-eslint plugin

**What did you expect to happen?**
Error should throw at the "x" function, not at the top of class.

**What actually happened? Please include the actual, raw output from ESLint.**
Error throws in at the beginning of class JSDoc and filling there `@param {Number} k - foo` makes error disappear. Filling out JSDoc for function "x" with same text works too, but error is being shown in wrong place.

**Comment by platinumazure** [comment]
Class properties are not yet Stage 4, so this is something ESLint can't support yet.

Try raising an issue in [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel). They may have a modified version of valid-jsdoc which handles class property documentation correctly.
