### ISSUE TITLE
How to get rid of node_modules when specifying --format ?

### ISSUE THREAD

**Issue by adelura** [eslint/eslint#10338]
Disclaimer: I asked on gitter, but no one answered.

Is there a way to get rid of hardcoded path to formatter?

    $ eslint --format ./node_modules/eslint-formatter

The problem is that as it's not guaranteed that formatted will be in that location. Especially when using tools like [lerna](https://github.com/lerna/lerna).

**Comment by nzakas** [comment]
Sorry for the delay in responding. The `--format` option requires a full path to the formatter file, so there isn't a way to get rid of `./node_modules` in your example.

**Comment by not-an-aardvark** [comment]
A quick correction to what @nzakas mentioned: As of fairly recently (https://github.com/eslint/eslint/pull/9464), we do support loading formatters from `node_modules` under certain circumstances, provided that the formatter name starts with `eslint-formatter-`. In other words, `--format foo` will load a formatter called `eslint-formatter-foo`.

**Comment by adelura** [comment]
Great! thank you very much.
