### ISSUE TITLE
getting error while installing rules for eslint with following command line in the reactnative project folder : npm install --save-dev eslint-config-rallycoding

### ISSUE THREAD

**Issue by Shanie1331** [eslint/eslint#10345]
> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\traverse\node_modules\.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules\@babel\traverse\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\traverse\node_modules\.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules\@babel\traverse\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\template\node_modules\.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules\@babel\template\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\template\node_modules\.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules\@babel\template\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\core\node_modules\.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules\@babel\core\node_modules\.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon
> npm ERR! path D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall unlink
> npm ERR! Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin'
> npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin'
> npm ERR!   cause:
> npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin'
> npm ERR!      errno: -4048,
> npm ERR!      code: 'EPERM',
> npm ERR!      syscall: 'unlink',
> npm ERR!      path: 'D:\\react native\\portfolio\\node_modules\\@babel\\core\\node_modules\\babylon\\bin' },
> npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\react native\\portfolio\\node_modules\\@babel\\core\\node_modules\\babylon\\bin\'',
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'unlink',
> npm ERR!   path: 'D:\\react native\\portfolio\\node_modules\\@babel\\core\\node_modules\\babylon\\bin',
> npm ERR!   parent: '@babel/core' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\shash\AppData\Roaming\npm-cache\_logs\2018-05-12T13_43_29_686Z-debug.log
> 
> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm ERR! Maximum call stack size exceeded
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\shash\AppData\Roaming\npm-cache\_logs\2018-05-12T13_47_04_528Z-debug.log

after removing readonly from the project folder properties i was still getting the following error:

> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules\.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm ERR! Maximum call stack size exceeded
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\shash\AppData\Roaming\npm-cache\_logs\2018-05-12T13_47_04_528Z-debug.log

I checked log also , it is following : 

6031 warn rm not removing D:\react native\portfolio\node_modules\.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
6032 silly isEverInside D:\react native\portfolio\node_modules\.bin\uuid is not inside D:\react native\portfolio\node_modules\uuid
6033 silly isEverInside D:\react native\portfolio\node_modules\request\node_modules\uuid\bin\uuid is not inside D:\react native\portfolio\node_modules\uuid
6034 silly gentlyRm parent.path = D:\react native\portfolio\node_modules\uuid
6035 silly gentlyRm parent.managed = D:\react native\portfolio\node_modules\uuid is in D:\react native\portfolio
6036 silly gentlyRm target.path =  D:\react native\portfolio\node_modules\.bin\uuid
6037 silly gentlyRm target.symlink = ../request/node_modules/uuid/bin/uuid
6038 silly gentlyRm target.managed = D:\react native\portfolio\node_modules\.bin\uuid is in D:\react native\portfolio
6039 silly gentlyRm target.inParent =  false
6040 warn rm not removing D:\react native\portfolio\node_modules\.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid

**Comment by Shanie1331** [comment]
The version of ESLint : v4.19.1
I had created a react app where babel & yarn were already installed I wanted to add eslint with rallycoding also.

1. - first I ran `npm install -g eslint`, and it was sucessful.
2. - then I ran `npm install --save-dev eslint-config-rallycoding` in my project folder to add rules, this was not successfull and has given the following errors:
```

> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\traverse\node_modules.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules@babel\traverse\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\traverse\node_modules.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules@babel\traverse\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\template\node_modules.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules@babel\template\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\template\node_modules.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules@babel\template\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\core\node_modules.bin\babylon.cmd as it wasn't installed by D:\react native\portfolio\node_modules@babel\core\node_modules\babylon
> npm WARN rm not removing D:\react native\portfolio\node_modules@babel\core\node_modules.bin\babylon as it wasn't installed by D:\react native\portfolio\node_modules@babel\core\node_modules\babylon
> npm ERR! path D:\react native\portfolio\node_modules@babel\core\node_modules\babylon\bin
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall unlink
> npm ERR! Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules@babel\core\node_modules\babylon\bin'
> npm ERR! { Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules@babel\core\node_modules\babylon\bin'
> npm ERR! cause:
> npm ERR! { Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules@babel\core\node_modules\babylon\bin'
> npm ERR! errno: -4048,
> npm ERR! code: 'EPERM',
> npm ERR! syscall: 'unlink',
> npm ERR! path: 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin' },
> npm ERR! stack: 'Error: EPERM: operation not permitted, unlink 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin'',
> npm ERR! errno: -4048,
> npm ERR! code: 'EPERM',
> npm ERR! syscall: 'unlink',
> npm ERR! path: 'D:\react native\portfolio\node_modules\@babel\core\node_modules\babylon\bin',
> npm ERR! parent: '' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\shash\AppData\Roaming\npm-cache_logs\2018-05-12T13_43_29_686Z-debug.log
> 
> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm ERR! Maximum call stack size exceeded
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\shash\AppData\Roaming\npm-cache_logs\2018-05-12T13_47_04_528Z-debug.log

```

after removing read only from the project folder properties i was still getting the following error:

```

> D:\react native\portfolio>npm install --save-dev eslint-config-rallycoding
> npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc.cmd as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\jsesc as it wasn't installed by D:\react native\portfolio\node_modules\jsesc
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esparse as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate.cmd as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm WARN rm not removing D:\react native\portfolio\node_modules.bin\esvalidate as it wasn't installed by D:\react native\portfolio\node_modules\esprima
> npm ERR! Maximum call stack size exceeded
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\shash\AppData\Roaming\npm-cache_logs\2018-05-12T13_47_04_528Z-debug.log
> 

```
I checked log also , it is following :

> 6031 warn rm not removing D:\react native\portfolio\node_modules.bin\uuid.cmd as it wasn't installed by D:\react native\portfolio\node_modules\uuid
> 6032 silly isEverInside D:\react native\portfolio\node_modules.bin\uuid is not inside D:\react native\portfolio\node_modules\uuid
> 6033 silly isEverInside D:\react native\portfolio\node_modules\request\node_modules\uuid\bin\uuid is not inside D:\react native\portfolio\node_modules\uuid
> 6034 silly gentlyRm parent.path = D:\react native\portfolio\node_modules\uuid
> 6035 silly gentlyRm parent.managed = D:\react native\portfolio\node_modules\uuid is in D:\react native\portfolio
> 6036 silly gentlyRm target.path = D:\react native\portfolio\node_modules.bin\uuid
> 6037 silly gentlyRm target.symlink = ../request/node_modules/uuid/bin/uuid
> 6038 silly gentlyRm target.managed = D:\react native\portfolio\node_modules.bin\uuid is in D:\react native\portfolio
> 6039 silly gentlyRm target.inParent = false
> 6040 warn rm not removing D:\react native\portfolio\node_modules.bin\uuid as it wasn't installed by D:\react native\portfolio\node_modules\uuid

I expected no errors.

**Comment by kaicataldo** [comment]
Apologies that we lost track of this. Has this been resolved?

**Comment by soft1700** [comment]
i have the exact same problem. any solutions?

**Comment by kaicataldo** [comment]
As this is happening during`npm install`, this seems more like an issue with your development environment than ESLint.

**Comment by Gurdeep0007** [comment]
Old version of eslint is deprecated so you have to use new package name while installation. 

npm install --save-dev eslint-plugin-babel

Please use  above command instead of old one. This will work for you. 

Best of luck

Happy coding :)

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back from the issue author for quite some time. Feel free to create a new issue if this is something you would like to discuss further.
