### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by arunprakashpj** [eslint/eslint#10349]
ESLint Version: 3.19.0
Node Version:8.9.1
npm Version: >=5.0.0

"babel-eslint":  "7.2.2",

The eslint was fine until I upgraded the web pack version from 1.x to 4.x 
 Currently, my web pack version is 4.8.

```
   "@babel/cli": "^7.0.0-beta.46",
    "@babel/core": "^7.0.0-beta.46",
    "@babel/preset-react": "^7.0.0-beta.46",
    "@babel/register": "^7.0.0-beta.46",
    "babel-eslint": "7.2.2",
    "babel-loader": "^7.1.4",
    "sass-loader": "^7.0.1",
    "webpack": "^4.8.1",
```

I am getting the following error when i run eslint .

> ImportDeclaration should appear when the mode is ES6 and in the module context.
AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.

**Comment by ilyavolodin** [comment]
That doesn't sound at all like ESLint error. Not sure where the error is coming from, but maybe from Webpack or babel-eslint?

**Comment by arunprakashpj** [comment]
Increasing the eslint version to 4.x solved the issue
