### ISSUE TITLE
crash on malformed package.json

### ISSUE THREAD

**Issue by jacekkopecky** [eslint/eslint#10364]
If `package.json` is malformed, eslint fails by crashing. This is relevant because then in Atom, every file that is to be checked by eslint is marked as invalid.

**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 9.8.0
* **npm Version:** 6.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

original `package.json` so I can `npm i` eslint:

```json
{
  "name": "test",
  "version": "0.1.0",
  "description": "test eslint",
  "main": "app.js",
  "scripts": {
    "lint": "eslint ."
  },
  "author": "Jacek Kopecky <jacek@jacek.cz>",
  "engines": {
    "node": ">=8.7.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1"
  }
}
```

No `.eslintrc` or anything like that.

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I was editing package.json and introduced a syntax error - the usual extra comma (near the end of the file below).

```json
{
  "name": "test",
  "version": "0.1.0",
  "description": "test eslint",
  "main": "app.js",
  "scripts": {
    "lint": "eslint ."
  },
  "author": "Jacek Kopecky <jacek@jacek.cz>",
  "engines": {
    "node": ">=8.7.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
  }
}
```

Then I want to lint the project:

```bash
eslint .
```

**What did you expect to happen?**

Eslint should either fail gracefully with a warning because it can't parse `package.json`, or it assumes there's nothing in `package.json` of interest to eslint (which is correct) and proceeds to check the directory, which is otherwise empty so eslint succeeds quietly. If eslint fails, its output should clearly blame `package.json` in the normal »this file has a linting error« format.

**What actually happened? Please include the actual, raw output from ESLint.**

Crash.

```
Unexpected token } in JSON at position 275
SyntaxError: Unexpected token } in JSON at position 275
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/ignored-paths.js:176:55)
    at lodash.memoize.optionsObj (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:115:13)
    at memoized (/Users/kopeckyj/tmp/eslint/node_modules/lodash/lodash.js:10551:27)
    at globPatterns.forEach.pattern (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:175:34)
    at Array.forEach (<anonymous>)
    at Object.listFilesToProcess (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/util/glob-util.js:158:18)
    at CLIEngine.executeOnFiles (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/cli-engine.js:518:35)
    at Object.execute (/Users/kopeckyj/tmp/eslint/node_modules/eslint/lib/cli.js:189:111)
    at Object.<anonymous> (/Users/kopeckyj/tmp/eslint/node_modules/eslint/bin/eslint.js:74:28)
```

**Comment by jacekkopecky** [comment]
Hi, I'd love to have a stab at it but I'm too busy with the day job until July easily.

**Comment by g-plane** [comment]
Should the error stack be outputed?

**Comment by not-an-aardvark** [comment]
I think it would be nice to output the error message, but outputting the stack is probably not necessary.

So the output could look something like this:

```
Failed to parse config file at /foo/bar/.eslintrc.json:

SyntaxError: Unexpected token } in JSON at position 275
```

**Comment by g-plane** [comment]
How about removing the stack info before throwing error?

**Comment by not-an-aardvark** [comment]
We already have code in place for pretty-printing error messages by adding a `messageTemplate` property to the thrown error -- if an error has a `messageTemplate`, then a corresponding message from the `templates/` folder is printed rather than a stack trace.

For example, see:

https://github.com/eslint/eslint/blob/a812845dd6da88c2857d06782906aa076c5dd497/lib/config.js#L255-L263
