### ISSUE TITLE
eslint doesn't support parsing json files yet still tries to parse them

### ISSUE THREAD

**Issue by LJNeon** [eslint/eslint#10383]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 10.1.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
ES2018
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "es6": true,
    "node": true
  },
  "extends": "google",
  "rules": {
    "arrow-parens": [2, "as-needed"],
    "comma-dangle": [2, "never"],
    "curly": [2, "multi-or-nest"],
    "keyword-spacing": [2, {
      "after": true,
      "before": false,
      "overrides": {
        "break": {"after": false},
        "case": {"after": false},
        "catch": {"after": false},
        "continue": {"after": false},
        "debugger": {"after": false},
        "default": {"after": false},
        "do": {"after": false},
        "else": {"after": false},
        "extends": {"before": true},
        "finally": {"after": false},
        "for": {"after": false},
        "if": {"after": false},
        "in": {"before": true},
        "instanceof": {"before": true},
        "of": {"before": true},
        "super": {"after": false},
        "switch": {"after": false},
        "this": {"before": true, "after": false},
        "while": {"after": false}
      }
    }],
    "max-len": [2, {
      "code": 120,
      "tabWidth": 2,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true,
      "ignoreUrls": true
    }],
    "no-console": 2,
    "prefer-template": 2,
    "require-jsdoc": 0,
    "sort-keys": [2, "asc", {
      "caseSensitive": false,
      "natural": true
    }],
    "quotes": [2, "double", {
      "avoidEscape": false,
      "allowTemplateLiterals": true
    }]
  },
  "parserOptions": {"ecmaVersion": 2018}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
{
  "any values": "you want, it doesn't matter"
}
```

```bash
eslint src/**
```

**What did you expect to happen?**
it would ignore files it wasn't meant to parse
**What actually happened? Please include the actual, raw output from ESLint.**
./src/credentials.json
  2:10  error  Parsing error: Unexpected token :

**Comment by not-an-aardvark** [comment]
Hi,

I think this is happening because when you type `eslint src/**` on a command line, your shell is expanding `src/**` to a list of filenames before the glob gets passed to ESLint. So ESLint is getting run with arguments like `eslint src/foo.js src/bar.js src/baz.json`, and so it's linting your `.json` file since that file was "explicitly" passed as an argument.

To avoid this, I would recommend quoting the globs on the command line to prevent your shell from expanding them. This will allow ESLint's glob resolution to handle the globs, which should work as expected.

```
eslint "src/**"
```

**Comment by LJNeon** [comment]
Just tried that and it still tries to parse the JSON file

**Comment by not-an-aardvark** [comment]
Hmm, that is odd. Could you run ESLint with the `--debug` flag and paste the output here?

**Comment by LJNeon** [comment]
The first option worked, thanks!
