### ISSUE TITLE
"'Class' is not defined" when using eslint/babel-eslint/babel-preset-flow

### ISSUE THREAD

**Issue by rbong** [eslint/eslint#10395]
**Tell us about your environment**

* **ESLint Version:** `v4.19.1` according to `node_modules/.bin/eslint -v`
* **Node Version:** `v8.10.0` according to `node -v`
* **npm Version:** `5.7.1` according to `npm -v`

**What parser (default, Babel-ESLint, etc.) are you using?**

`babel-eslint`

**Please show your full configuration:**

<details>
<summary>ESLint Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "rules": {
    "no-undef": "error"
  }
}
```

</details>

<details>
<summary>Babel Configuration</summary>

```js
{
  "presets": [
    "flow"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

</details>

</details>

<details>
<summary>Flow Configuration</summary>

```js
[ignore]

[include]

[libs]

[options]
```

</details>

<details>
<summary>package.json</summary>

```js
{
  "name": "class-lint-example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-flow": "^6.23.0",
    "eslint": "^4.19.1",
    "flow": "^0.2.3",
    "flow-bin": "^0.72.0"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// index.js
type ClassType = Class<{}>;

class RealClass {}

const c : ClassType = new RealClass();

export default c;
```

```bash
$ node_modules/.bin/eslint index.js
```

In addition, all of the following commands are successful:

```bash
$ node_modules/.bin/babel index.js
(valid Javascript code)
$ node_modules/.bin/flow index.js
(no errors found)
```
**What did you expect to happen?**

No errors should be triggered by the above code.
`Class<T>` is a [valid flow type](https://flow.org/en/docs/types/utilities/#toc-class).

**What actually happened? Please include the actual, raw output from ESLint.**

The following error is produced.

```bash
$ node_modules/.bin/eslint index.js

/home/rbong/prog/class-lint-example/index.js
  1:18  error  'Class' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

**Additional Details**

Not sure if this belongs here or `babel-eslint` or somewhere else, please let me know.

This is the same as #7945 but that issue was closed and locked because of failing to provide details.

As a workaround you can add the following to your config:

```js
  "globals": {
    "Class": false
  }
```

**Comment by platinumazure** [comment]
I think maybe this should be reported in babel-eslint, but not 100% sure.

I assume this is not really recreatable with the default parser due to experimental syntax, so I'm not sure if there's much we can/should do here in ESLint. :man_shrugging:

**Comment by rbong** [comment]
My bad, `eslint-plugin-flowtype-rules-define-flow-type` needs to be added. It's right on the `babel-eslint` readme. I don't know how I avoided this for the rest of my flow typing.

```
{
  "parser": "babel-eslint",
  "plugins": ["flowtype"],
  "rules": {
    "no-undef": "error",
    "flowtype/define-flow-type": 1
  }
}
```
