### ISSUE TITLE
replace inquirer library in eslint 5a3

### ISSUE THREAD

**Issue by bugzpodder** [eslint/eslint#10404]
In eslint 5 alpha 3, we have upgraded the inquirer library to 5.x from 3.3.0.  This doubled the install size from 19MB to 37MB because inquirer switched from rx-lite (rxjs 4 lite to rxjs 5/6) in the newer builds https://github.com/SBoudrias/Inquirer.js/pull/614

Would people here be open to use a more lightweight alternative such as http://enquirer.io/?

**Comment by platinumazure** [comment]
I'm not opposed, but I'd like to see what other team members think.

I'd be interested in seeing a PR with how it would look, but I also don't want to ask you to do work that we might just decide not to merge. I do think it could help, though (but either way is fine).

**Comment by platinumazure** [comment]
Looking at [this comment](https://github.com/SBoudrias/Inquirer.js/pull/614#issuecomment-368735466), could we also address this in the upstream repo by ensuring they don't put many unnecessary files in their published package? Not sure how feasible that is.

**Comment by g-plane** [comment]
ESLint is running on our/your development computer or CI server, not in browser. So, file size should not be cared.

**Comment by bugzpodder** [comment]
@g-plane We are trying to reduce the install size of create-react-app 2.0 which bundles eslint. 
https://github.com/facebook/create-react-app/issues/3880

**Comment by saberduck** [comment]
I am also interested in this, because we are trying to embed eslint for SonarQube analyzer. Is it safe to remove inquirer from dependencies when eslint is not used interactively on command line but only executed as a standalone process?

**Comment by ilyavolodin** [comment]
I'm also not opposed to this change. However, it has to be thoroughly verified, since we have almost not tests covering CLI interactions.

**Comment by bugzpodder** [comment]
I actually implemented it for eslint and it was fairly straightforward.  But eslint moved out of beta fairly quickly and I was told enquirer was getting a version bump (never happened), and I wasn't sure if create-react-app planned on switching as well.  

I wonder if it's possible to have a CLI package just for initiating new projects.

**Comment by millette** [comment]
Could the config initializer (the part that depends on inquirer) be moved to a secondary package?
