### ISSUE TITLE
checking test coverage

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#10415]
refs: https://github.com/eslint/eslint/pull/10407#issuecomment-392547229
We have disabled `coveralls` somehow. is there some reason doing so?
Do we still want to add something checking test coverage?

**Comment by ilyavolodin** [comment]
Coverage is checked every time we run unit tests in the build. coveralls was more for visual browsing. I'm not sure we really need it.

**Comment by not-an-aardvark** [comment]
From what I understand, we currently make the build fail if coverage falls below a certain threshold (98%), but a build is considered to be fine even if there are uncovered parts and it makes the total coverage go down (e.g. from 98.4% to 98.1%). It would be nice if coveralls could alert us when that happens, since it could indicate that some tests should be added to a PR.

**Comment by ilyavolodin** [comment]
It seems that if we want to do that, we should probably just raise coverage threshold to current coverage number. That would fail the build and indicate that more tests are required.

**Comment by not-an-aardvark** [comment]
I think by "current coverage number" you mean "coverage number at the last git commit". (If we set the coverage threshold to whatever the coverage is when the tests run, then the tests would always pass.) But it seems like it's nontrivial to measure the coverage at the last git commit, and I think that's what coveralls does.

**Comment by ilyavolodin** [comment]
To be honest, I looked at coveralls report maybe a few times just as we wired it in, after that, I never looked at it again. So I'm not sure it was helpful. I'm not opposed to setting it up again, just not sure it's needed.

**Comment by platinumazure** [comment]
It might be worthwhile to see how the typescript-eslint folks are using it. I think they've enabled a few more features than we had done, and they might be getting more utility out of it.

**Comment by aladdin-add** [comment]
we had enabled CodeClimate ~4 years ago (https://github.com/eslint/eslint/issues/4068), but it didn't work somehow.

**Comment by kaicataldo** [comment]
@aladdin-add Is this something you're still championing?

**Comment by aladdin-add** [comment]
Take it for granted we should set it. can we table it in the next TSC meeting?

and toooo sorry for the late response! (ノへ￣、)

**Comment by aladdin-add** [comment]
TSC Summary: This issue proposes to checking test coverage in CI.

TSC Question: Shall we accept it?

**Comment by btmills** [comment]
@aladdin-add you've got the go-ahead to set a code coverage tool back up and get that badge working again! We're fine re-connecting coveralls like we had before, but codecov also came up in the discussion, and we'd also be open to that if you decide it's better for our use case.
