### ISSUE TITLE
no-unused-vars: ignoreRestSiblings not applying within for...of statement.

### ISSUE THREAD

**Issue by alockwood05** [eslint/eslint#10421]
**Tell us about your environment**

* **ESLint Version:** v4.19.1
* **Node Version:** v8.9.4/
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-ESlint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parser": "babel-eslint",
    "plugins": [ "react" ],
    "env": {
        "es6": true,
        "node": true,
        "browser": true,
        "mocha": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "extends": [
      "eslint:recommended",
      "plugin:react/recommended"
    ],
    "globals": {
      "AppSettings": true,
      "Version": true
    },
    "rules": {
        "indent": [ 0, 2 ],
        "quotes":  0 ,
        "curly": [0],
        "linebreak-style": [ 2, "unix" ],
        "semi": [ 2, "always" ],
        "no-console": 0,
        "no-unused-vars": [2, { "vars": "local", "args": "none", "ignoreRestSiblings": true}],
        "react/prop-types": [0],
        "react/no-unescaped-entities": ["error", {"forbid": [">", "}"]}]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
for (let [index, d] of [[0, {data: 'testing'}]]) {
  console.log(d);
}
```

```bash
▶ node_modules/.bin/eslint ESLINT_TEST.js
```

**What did you expect to happen?**
I expected this would have no linting errors, because of the `{"ignoreRestSiblings": true}` option

**What actually happened? Please include the actual, raw output from ESLint.**
```
1:11  error  'index' is assigned a value but never used  no-unused-vars
```

**Comment by platinumazure** [comment]
Hi @alockwood05, thanks for the issue.

This is working as designed because the `ignoreRestSiblings` option only applies to object destructuring with a rest element.

With an object destructure, you have to name the rest element, so you can't avoid the unused variable in those cases.

With an array destructure, you can just use empty array slots. So you could rewrite your example this way:

```js
for (let [, d] of [[0, {data: 'testing'}]]) {
  console.log(d);
}
```

So the rule doesn't actually need to ignore missing elements there.

**Comment by alockwood05** [comment]
good to know!  Thanks :)
