### ISSUE TITLE
commit tag `Revert` not allowed

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10427]
+ `Revert` is not included in the tag list:

> * `Fix` - for a bug fix.
> * `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems.
> * `New` - implemented a new feature.
> * `Breaking` - for a backwards-incompatible enhancement or feature.
> * `Docs` - changes to documentation only.
> * `Build` - changes to build process only.
> * `Upgrade` - for a dependency upgrade.
> * `Chore` - for refactoring, adding tests, etc. (anything that isn't user-facing).

+ commit message check failing when a commit beginning with `Revert` (eg. https://github.com/eslint/eslint/pull/10426)

**Comment by platinumazure** [comment]
We don't want to encourage contributors to use "Revert:"-- that should only be for team members when we need to revert a commit. So, in my opinion, we should not change the docs. But we can definitely enhance the bot.

**Comment by arunikayadav42** [comment]
Can anybody help me get started with this project?I would love to contribute :)

**Comment by platinumazure** [comment]
Hi @arunikayadav42, thanks for reaching out!

It looks like @Aladdin-ADD already created eslint/eslint-github-bot#74 which is pretty close to fixing this.

If you are interested in helping out with other parts of ESLint, you could look for issues with either the ["good first issue"](https://github.com/eslint/eslint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or ["help wanted"](https://github.com/eslint/eslint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+) labels. Hope to see you soon in those!

**Comment by Aladdin-ADD** [comment]
closing, as https://github.com/eslint/eslint-github-bot/pull/74 get merged.
