### ISSUE TITLE
no-unneeded-ternary --fix breaks with yield statement

### ISSUE THREAD

**Issue by biw** [eslint/eslint#10432]
**Tell us about your environment**

* **ESLint Version:** v4.19.1
* **Node Version:** v9.6.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": [
    "airbnb-base",
    "plugin:flowtype/recommended",
    "plugin:react/recommended"
  ],
  "plugins": [
    "flowtype"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 8,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "modules": true,
      "jsx": true,
      "impliedStrict": true
    }
  },
  "globals": {
    "jest": false,
    "expect": false,
    "__DEV__": false
  },
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
    "es6": true
  },
  "rules": {
    "max-len": ["error", 100, {
      "ignoreUrls": true,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true,
      "ignoreRegExpLiterals": true
    }],
    "linebreak-style": ["error", "unix"],
    "quotes": ["error", "single", { "avoidEscape": true }],
    "no-param-reassign": "off",
    "camelcase": "off",
    "no-underscore-dangle": "off",
    "space-before-function-paren": ["error", "always"],
    "func-style": ["error", "expression", { "allowArrowFunctions": true }],
    "func-names": ["error", "as-needed"],
    "import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.js",  "test/*.js"]}],
    "flowtype/delimiter-dangle": 2,
    "flowtype/require-return-type": 2,
    "flowtype/require-parameter-type": 2
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    },
    "import/resolver": {
      "babel-module": {}
    }
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const exampleFunc = function* (in) {
  const result = in ? in : yield 1;
};
```

```bash
 ./node_modules/.bin/eslint --fix
```

**What did you expect to happen?**

ESLint should return:

```js
const exampleFunc = function* (in) {
  const result = in || (yield 1);
};
``` 

**What actually happened? Please include the actual, raw output from ESLint.**

The issue is that the parser returns invalid syntax with the `--fix` command.

ESLint returns:

```js
const exampleFunc = function* (in) {
  const result = in || yield 1;
};
```

which is invalid JavaScript code.

**Comment by platinumazure** [comment]
I can reproduce with the default parser. Marking as accepted.

I think one option would just be to parenthesize the alternate during autofix (unless already parenthesized). It would be ideal to only do so with yield and other keywords, but we do have `no-extra-parens` for handling extra parentheses that aren't needed.

**Comment by biw** [comment]
I would love to help work on a fix. If I could get some mentorship, I would love to take a try at a fix. Would that be possible?

**Comment by platinumazure** [comment]
Hi @biw, I would be happy to help you out. If you have any questions as to go, you may leave comments here and a team member will help; additionally, you are welcome to visit the ESLint team chat on Gitter (https://gitter.im/eslint/eslint) or chat with me directly on that platform.

Welcome aboard and good luck as you get started!
