### ISSUE TITLE
no-var to support const

### ISSUE THREAD

**Issue by slichlyter12** [eslint/eslint#10436]
**What rule do you want to change?**
The ```no-var``` rule
**Does this change cause the rule to produce more or fewer warnings?**
Same number of warnings
**How will the change be implemented? (New option, new default behavior, etc.)?**
New behavior
**Please provide some example code that this change will affect:**

```js
var visitors = 0;
var CONFIG = {};
```
to
```js
let visitors = 0;
const CONFIG = {};
```

**What does the rule currently do for this code?**
It converts all instances of `var` to `let` when applicable.
**What will the rule do after it's changed?**
Convert instances of `var` to `const` when that variable is never changed, otherwise convert to `let` where applicable.

**Comment by gyandeeps** [comment]
Recommended way is to activate `prefer-const` rule and it will auto fix the lets to const.
This was a design decision made when auto fix was added to `no-var` rule.
ref: https://github.com/eslint/eslint/issues/6639
