### ISSUE TITLE
Add experimentalECMAScriptMoudlesExtension: boolean

### ISSUE THREAD

**Issue by achun** [eslint/eslint#10451]
The developer chose to use ".mjs" as the extension, indicating that he is very clear that this is experimental and that he is using experimental features.

We know that ecmaFeatures has the experimentalObjectRestSpread option, to follow...

Proposal: add an option in env

```js
{
  "env": {
      "experimentalECMAScriptMoudlesExtension": true
  }
}
```

**Comment by achun** [comment]
needs info???????

Well, I give up this proposal.

**Comment by Aladdin-ADD** [comment]
not very sure what you were proposing here, just want to point out `experimentalObjectRestSpread` has been deprecated in https://github.com/eslint/eslint/pull/10230.

**Comment by achun** [comment]
@Aladdin-ADD  谢谢,

早知道我直接用中文写了, 我英文太差, 长篇的写肯定写崩了.
的确没看到 #10230 已经把 experimentalObjectRestSpread 废弃.
我说呢, 既然允许 experimental 这种选项存在, 那么要求周知的实验性选项被加入就合理了.
现在不同了, 既然 estree 坚守标准, 那我这个提案应该被拒绝.

**Comment by platinumazure** [comment]
You can run ESLint to search for mjs files:

```
eslint . --ext mjs
```

Or:

```
eslint "**/*.mjs"
```

And you can also run on both extensions if needed:

```
eslint . --ext mjs,js
```

```
eslint "**/*.{js,mjs}"
```

Hope this helps!

**Comment by achun** [comment]
@platinumazure  Thanks first.

I know that way. I need to get support in the configuration.  In some environments, using the command line is an obstacle. Such as VS code.

先感谢你, 命令行的方法我是知道的, 我的需求是在配置中得到支持, 有些时候无法方便的使用命令行, 比如在 vs code 中只能通过配置文件来让 eslint 工作.

另外, 还是那个,,,,, 这本应该是标准啊, 现在却难堪的变成了实验性的,,,,,

**Comment by platinumazure** [comment]
@achun You could use [glob-based configuration](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) to add specific configuration for .mjs files.

**Comment by achun** [comment]
@platinumazure Thanks.

eslint is work for '*.mjs'

The configuration .eslintrc.js

```js
module.exports = {
    "env": {
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            2
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "never"
        ]
    }
};
```
