### ISSUE TITLE
Probably we can deprecate no-catch-shadow rule?

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#10466]
**What rule do you want to change?**

- [no-catch-shadow] rule

**Does this change cause the rule to produce more or fewer warnings?**

- It doesn't change warnings.
- It marks the rule as deprecated (this is a minor change).

**How will the change be implemented? (New option, new default behavior, etc.)?**

- It changes rule's metadata.

**Please provide some example code that this change will affect:**
**What does the rule currently do for this code?**
**What will the rule do after it's changed?**

- N/A

----

- That rule looks like a rule for IE8 that was EOL on 2016/01/13.
- The [no-shadow] rule reports the shadowing of `catch` binding as well. ([online demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tc2hhZG93OiBlcnJvciwgbm8tY2F0Y2gtc2hhZG93OiBlcnJvciAqL1xyXG5cclxudmFyIGVyciA9IDBcclxudHJ5IHtcclxufSBjYXRjaCAoZXJyKSB7XHJcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=))

[no-catch-shadow]: https://eslint.org/docs/rules/no-catch-shadow
[no-shadow]: https://eslint.org/docs/rules/no-shadow

**Comment by not-an-aardvark** [comment]
@mysticatea This issue has 3 :+1:s from team members, so it can be accepted if you are willing to champion it.

**Comment by Mouvedia** [comment]
How do you limit `no-shadow` to `catch` only?
