### ISSUE TITLE
SublimeLinter: ERROR: env: node: No such file or directory

### ISSUE THREAD

**Issue by azamkth** [eslint/eslint#10465]
Initially, it was working perfectly fine when I install. But suddenly I got stuck and getting this error.

**Comment by g-plane** [comment]
Hi @azamkth , these info may help you:
https://github.com/SublimeLinter/SublimeLinter/issues/1218
https://github.com/SublimeLinter/SublimeLinter-eslint/issues/232
https://github.com/SublimeLinter/SublimeLinter/pull/1266

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back for quite some time. Feel free to create a new issue if this is something you would like to discuss further.
