### ISSUE TITLE
Issue on eslinit --init

### ISSUE THREAD

**Issue by JulioVL** [eslint/eslint#10472]
**Tell us about your environment**

* **ESLint Version:**
v4.19.1
* **Node Version:**
v10.3.0
* **npm Version:**
6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
1. Globally Installation: "npm install -g eslint"
2. Set up configuration file: "eslint --init" on project directory
   (a) how would you like to configure ESLint?
         inspect your JavaScript file(s)
   (b) which file(s), path() should be examined?
        ./js/*.js
   (c) What format do you want your config to be in?
        Javascript

**What did you expect to happen?**
I expected for the other questions to appear so I could finish the configuration.

**What actually happened? Please include the actual, raw output from ESLint.**
It doesn't show any other question, nor show me any error message. It freezes there.

Image: https://snag.gy/w4ge1i.jpg

**Comment by Aladdin-ADD** [comment]
have you tried `eslint@5.0.0-rc.0 ` ?
it was fixed in https://github.com/eslint/eslint/pull/10422 .

**Comment by JulioVL** [comment]
Thank you.
Installing that ESLint version solved the problem.

**Comment by ilyavolodin** [comment]
Closing as issue is now resolved.
