### ISSUE TITLE
move rule strict to category: "Best Practices"

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10471]
it should be a best priactice, IMHO. Not sure why it's seperated.

![image](https://user-images.githubusercontent.com/13050025/41297723-5fa131d8-6e92-11e8-809b-284423cdeb22.png)

**Comment by platinumazure** [comment]
I've long advocated that we should have only 3 categories: possible errors, best practices, and stylistic issues. And anything else (ES6, variables, strict, Node.js, etc.) should be a "tag" that could be used for further faceting.
