### ISSUE TITLE
Confusing ecmaVersion

### ISSUE THREAD

**Issue by polizz** [eslint/eslint#10479]
**Tell us about your environment**
macOS High Sierra

* **ESLint Version:**
v4.19.1
* **Node Version:**
8.11.2, v9.3.0
* **npm Version:**
5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```js
{
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2018,
    "env": {
      "es6": true,
      "node": true
    }
  },
  "plugins": ["eslint-plugin-import"],
  "rules": {
  }
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
exports.handler = async () => {
  const { body: allRepos } = await getUrl(teamRepoRoot)

  const repoPulls = await Promise.all(allRepos.map(item =>
    getUrl(item.pulls_url.replace('{/number}', ''))))
```
and
```js
  ({
      ...pr,
      reviews: prSummary[i].body.map(r => r.state),
    })
```

```bash
eslint *.js
```

**What did you expect to happen?**
I want all syntax up to the 2018 ecmaVersion, but when I use it, I lose the globals that I have with 2015. 2017 keeps the globals, but I lose object rest spread. If I add the deprecated ```"experimentalObjectRestSpread": true``` to the 2017 version, I get object rest spread but lose the globals 😕 

**What actually happened? Please include the actual, raw output from ESLint.**
The config above produces:

/doRequest.js
  3:28  error  'Buffer' is not defined  no-undef

/index.js
   8:1   error  'exports' is not defined  no-undef
  11:27  error  'Promise' is not defined  no-undef
  25:27  error  'Promise' is not defined  no-undef
  40:3   error  'console' is not defined  no-undef

✖ 5 problems (5 errors, 0 warnings)

**Comment by ljharb** [comment]
"env" is a top-level key; it's not part of parserOptions.

**Comment by polizz** [comment]
Ah thanks man! You proved what I suspected... I'm going blind or dumb 😖
