### ISSUE TITLE
"ecmaVersion": "2017" gives Parsing error: Unexpected token ( on async method

### ISSUE THREAD

**Issue by tapasweni-pathak** [eslint/eslint#10489]
* **ESLint Version:** v4.10.0
* **Node Version:** v8.10.0
* **npm Version:** 6.0.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": "eslint:recommended",
  "env": {
    "node": true,
    "es6": true,
    "jest": true
  },
  "parserOptions": {
    "ecmaVersion": "2017"
  },
  "plugins": [
    "node"
  ],
  "rules": {
    "arrow-parens": ["error", "always"],
    "no-var": "error",
    "prefer-const": "error",
    "array-bracket-spacing": ["error", "never"],
    "comma-dangle": ["error", "never"],
    "computed-property-spacing": ["error", "never"],
    "eol-last": "error",
    "eqeqeq": ["error", "smart"],
    "indent": ["error", 2, { "SwitchCase": 1 }],
    "no-confusing-arrow": ["error", {"allowParens": false}],
    "no-extend-native": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-spaced-func": "error",
    "no-trailing-spaces": "error",
    "no-unused-vars": "error",
    "no-use-before-define": ["error", "nofunc"],
    "object-curly-spacing": ["error", "always"],
    "prefer-arrow-callback": "error",
    "quotes": ["error", "single", "avoid-escape"],
    "semi": ["error", "always"],
    "space-infix-ops": "error",
    "spaced-comment": ["error", "always"],
    "keyword-spacing": ["error", { before: true, after: true }],
    "template-curly-spacing": ["error", "never"],
    "semi-spacing": "error",
    "strict": "error",
    "no-console": "off",
    "node/no-unsupported-features": ["error", {"version": 8}],
    "node/no-missing-require": "error"
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class DeadLetter {
  constructor(options = {}) {
    if (!options.queueUrl)
      throw new Error('queueUrl is undefined');
    this.options = options;
    this.sqs = new AWS.SQS({
      region: url.parse(options.queueUrl).host.split('.')[1],
      params: { QueueUrl: options.queueUrl }
    });

    this.cfn = new AWS.CloudFormation({
      region: url.parse(options.queueUrl).host.split('.')[1],
    });

    const actions = { purse, writeOut, replay, triage };

    findQueues(this.cfn, options);
    const queues = selectQueue(queues);
    const queue = triageSelection(queue);
    const data = actions[data.action](sqs, data.queue);
  }

  async findQueues(options) {
    return new Promise((resolve) => {
      let res = await this.cfn.describeStacks({ StackName: options.stackName}).promise();

```

```bash
npm run lint
```

this basically runs eslint.

**What did you expect to happen?**
I don't think the ( on async should error. When I change the `"ecmaVersion": "8"`, I get 
`Parsing error: The keyword 'class' is reserved` on the first line which also shouldn't be the case.

**What actually happened? Please include the actual, raw output from ESLint.**

`"ecmaVersion": "2017"`
```
33:1 error Parsing error: Unexpected token (

```
`"ecmaVersion": "8"`
```
  11:1  error  Parsing error: The keyword 'class' is reserved
```
I checked on gitter channel members on this, seems like saying `"ecmaVersion": "8"` should work here, haven't looked a lot on this, is there something in local setup or what else am I missing here?

**Comment by platinumazure** [comment]
I think ecmaVersion is supposed to be a number rather than a string.

Try `8` or `2017` (without quotation marks) instead of `"8"` or `"2017"`. Does that work?

**Comment by tapasweni-pathak** [comment]
Gah, how can I not see this, thanks! May be just picked what was there on project. Can there be a check to say that it should be a number and not a string, instead of giving random eslint failed checks?

**Comment by tapasweni-pathak** [comment]
Gah, how can I not see this, thanks! May be just didn't realize as it was already on the project. Can there be a check to say that it should be a number and not a string, instead of giving random eslint failed checks?

**Comment by tapasweni-pathak** [comment]
Related to proper checks, I want to **stop** using string values, would really help if using string values **fails** all the time strongly.

**Comment by platinumazure** [comment]
Did this solve your issue after all?

Agreed that we should catch this.

**Comment by tapasweni-pathak** [comment]
No. I'm getting different error, error on `this` in class method which works syntactically. I dropped a ping in gitter with some more info.

**Comment by Aladdin-ADD** [comment]
need ecmaVersion: 9/2018, to allow `async/await`.

**Comment by ljharb** [comment]
@Aladdin-ADD async/await was added in ES2017.

**Comment by kaicataldo** [comment]
This seems like a nice thing to validate or to at least throw up a warning message about.

**Comment by tapasweni-pathak** [comment]
I checked with @platinumazure on this on gitter, he reffered to an espree ticket about validating options, I think this https://github.com/eslint/espree/issues/384. I wanted to know if PRing in eslint https://github.com/eslint/eslint/blob/master/conf/config-schema.js#L8-L18 adding to `parserOptions` would be good?

**Comment by tapasweni-pathak** [comment]
I checked with @platinumazure on this on gitter few weeks back, he reffered to an espree ticket about validating options, I think this eslint/espree#384. I wanted to know if PRing in eslint https://github.com/eslint/eslint/blob/master/conf/config-schema.js#L8-L18 adding to parserOptions would be good?

**Comment by tapasweni-pathak** [comment]
I checked with @platinumazure on this on gitter few weeks back, he reffered to an espree ticket about validating this in espree, I think this eslint/espree#384. I wanted to get started with contributing to eslint codebase, was thinking if adding to https://github.com/eslint/eslint/blob/master/conf/config-schema.js#L8-L18 `parserOptions` would work? would be happy to in espree as well.

**Comment by tapasweni-pathak** [comment]
I checked with @platinumazure on this on gitter few weeks back, he reffered to an espree ticket about validating this in espree, I think this eslint/espree#384. I wanted to get started with contributing to eslint codebase, was thinking if adding to https://github.com/eslint/eslint/blob/master/conf/config-schema.js#L8-L18 `parserOptions` would work? would be happy to pr in espree as well.

**Comment by kaicataldo** [comment]
Thanks for looking into this! Let’s take the discussion over to the Espree issue you listed above, as it looks like there are some things we implementation details we need to figure out.

I’m going to go ahead and close this in favor of https://github.com/eslint/espree/issues/384.
