### ISSUE TITLE
shared-node-browser is buggy

### ISSUE THREAD

**Issue by pronebird** [eslint/eslint#10493]
The docs for `shared-node-browser` state:

>shared-node-browser - Globals common to both Node.js and Browser.

Which looks like Electron renderer to me. Yet when trying to use it, it emits a lot of errors like it's none of what docs describe.

Excerpt from config:

```
"env": {
    "es6": true,
    "shared-node-browser": true
  }
```

Emits errors like:

>'process' is not defined
>'HTMLInputElement' is not defined  
>'__dirname' is not defined

and so on..

What are you `shared-node-browser`?

ps: using `eslint@4.19.1`

**Comment by sindresorhus** [comment]
> Globals common to **both** Node.js and Browser.

**Comment by mysticatea** [comment]
This is intentional behavior.

`shared-node-browser` defines the global variables which exist on both Node.js and Browser.

- `process` doesn't exist on `browser`.
- `HTMLInputElement` doesn't exist on `node`.
- `__dirname` doesn't exist on `browser`.
