### ISSUE TITLE
new rule to help people discover ordering bug in args to Promise((reject, resolve) => {..} 

### ISSUE THREAD

**Issue by humphd** [eslint/eslint#10508]
I'm not sure if this is possible, but I know [I'm not alone](https://github.com/search?p=2&q=%22Promise%28%28reject%2C+resolve%29%22&type=Code) in reversing the order of the arguments `resolve, reject` when creating a new `Promise`.  Obviously you could name these functions anything, but what you end-up doing with them matters: `reject` needs to `Promise.reject` and `resolve` needs to `Promise.resolve`.

If there is some way to help people correct this via an eslint rule, that would be great.

[ ] Enforces code style
[ X ] Warns about a potential error
[ X ] Suggests an alternate way of doing something
[ ] Other (please specify:)

For examples, see the [link I provided](https://github.com/search?p=2&q=%22Promise%28%28reject%2C+resolve%29%22&type=Code) where hundreds of people get it backwards.

It's possible that this can't be done via eslint, or that it has been done and I'm missing it.  If so, my apologies.  If it hasn't, I think it's worth considering, since this is very easy to get wrong and still have a "working" program.

**Comment by ilyavolodin** [comment]
The only way this can be done is by relying on naming convention, and that's very error-prone method. I don't think including rules based on the naming convention into the core is a good idea, however, it can be done in a plugin. I would suggest opening an issue here: https://github.com/xjamundx/eslint-plugin-promise

**Comment by ilyavolodin** [comment]
I'm going to close this issue, since you already filed it for a plugin, and I don't think this proposal would meet our requirements for inclusion into the core.
