### ISSUE TITLE
Extra commas after prefer-object-spread --fix

### ISSUE THREAD

**Issue by turadg** [eslint/eslint#10512]
**Tell us about your environment**

* **ESLint Version:** 5.0.0
* **Node Version:** 8.11.3
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-Eslint 8.2.5

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
---
# Use babel as our parser https://github.com/babel/babel-eslint
parser: "babel-eslint"

# by default we follow this styleguide https://github.com/airbnb/javascript
# overrides below in rules
extends:
  - "airbnb"
  - "prettier"
  - "prettier/flowtype"
  - "prettier/react"

plugins:
  # React rules https://github.com/yannickcr/eslint-plugin-react
  - "react"
  # Flowtype rules https://github.com/gajus/eslint-plugin-flowtype
  - "flowtype"
  # Browser compatibility rules https://github.com/amilajack/eslint-plugin-compat
  - "compat"

rules:
  # Stricter than Airbnb
  constructor-super: 2
  prefer-const: 2
  no-class-assign: 2
  no-this-before-super: 2
  quote-props:
    - 2
    - "as-needed"
    -
      unnecessary: false
      numbers: true
  no-eq-null: 2
  new-cap: 0 # TODO alan switch to prefer cap
  arrow-spacing: 2
  block-spacing: 2
  spaced-comment: 2
  prefer-object-spread: 2

…
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
    const actions = Object.assign(
      {
        onChangeInput: this.handleChangeInput,
      },
      this.props.actions
    );
```

```bash
eslint <path> --fix
```

**What did you expect to happen?**
```js
    const actions = {
        onChangeInput: this.handleChangeInput,
        ...this.props.actions,
    };
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
    const actions = {
        onChangeInput: this.handleChangeInput,,
...this.props.actions};
```
Note the extra comma, causes syntax error.

Proper indentation would be nice, but can be fixed with Prettier, if the two commas didn't break the syntax.

**Comment by platinumazure** [comment]
Hi @turadg, thanks for the issue!

I can recreate in [the demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1vYmplY3Qtc3ByZWFkOiBlcnJvciAqL1xyXG5cclxuICAgIGNvbnN0IGFjdGlvbnMgPSBPYmplY3QuYXNzaWduKFxyXG4gICAgICB7XHJcbiAgICAgICAgb25DaGFuZ2VJbnB1dDogdGhpcy5oYW5kbGVDaGFuZ2VJbnB1dCxcclxuICAgICAgfSxcclxuICAgICAgdGhpcy5wcm9wcy5hY3Rpb25zXHJcbiAgICApOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==). This is definitely a bug.

**Comment by mysticatea** [comment]
I'll try to fix it if anyone has not been working on this.
