### ISSUE TITLE
Set `no-trailing-spaces` on by default ?

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#1051]
Will it be good for all to enable rule `no-trailing-spaces` with error by default ?

**Comment by jeffscottward** [comment]
I disagree. I'm a beginner. I don't know how to turn this off.

**Comment by puzrin** [comment]
That's no longer relevant. Since 1.0.0 no rules are enabled by default.

**Comment by IanVS** [comment]
Hi @jeffscottward, hope you're liking ESLint so far.  To learn how to turn rules on and off, please checkout the [configuring rules](http://eslint.org/docs/user-guide/configuring#configuring-rules) section of the user guide.  And if you have any questions on how to use ESLint, feel free to jump in the [gitter chat](https://gitter.im/eslint/eslint).

And yes, if you are using the 1.0.0 release candidate of ESLint (install with `npm install ESLint@next`), the rules are all turned off by default.  You can see the [latest blog post](http://eslint.org/blog/2015/07/eslint-1.0.0-rc-3-released/) for a description of what is changing in `v1.0.0`.
