### ISSUE TITLE
[import/named] not working for index.js in folder which exports object

### ISSUE THREAD

**Issue by jairusd** [eslint/eslint#10518]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
extends: airbnb
env:
  browser: true
  node: true
  es6: true
parser: babel-eslint
plugins:
  - react
rules:
  array-callback-return: 0
  camelcase: 0
  class-methods-use-this: 0
  comma-dangle:
    - 1
    - never
  func-names: 0
  generator-star-spacing:
    - 0
    -
      before: true
      after: false
  guard-for-in: 0
  no-console: off
  no-param-reassign:
    - 1
    -
      props: true
      ignorePropertyModificationsFor:
        - errors
        - columnObject
  no-unused-vars:
    - 1
    -
      args: none
  semi: 0
  react/no-array-index-key: 0
  react/require-default-props: 0 # to be removed
  react/prop-types: 0 # to be removed
  react/forbid-prop-types: 0
  react/no-children-prop: 0
  react/jsx-no-bind: 0
  react/jsx-filename-extension: 0
  react/no-unescaped-entities: 0

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

![image](https://user-images.githubusercontent.com/36670564/41846029-074eb274-78a8-11e8-809c-50da673b47bd.png)

![image](https://user-images.githubusercontent.com/36670564/41846057-17c656de-78a8-11e8-9d23-25a89915f98c.png)

```bash

```
i'm using sublime nad have eslint run in background

**What did you expect to happen?**
expected to detect `globalSelector` to be detected since it does exist from the object I exported from `index.js`

**What actually happened? Please include the actual, raw output from ESLint.**
![image](https://user-images.githubusercontent.com/36670564/41846182-7b2e1a18-78a8-11e8-8f57-91d1d6c65390.png)

As you can see i'm calling `globalSelector` from `index.js` in `reselect` folder and as you can see from `index.js` i'm exporting an object with `globalSelector` in it.

**Comment by not-an-aardvark** [comment]
Hi,

The `import/named` rule is part of [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import), which is not maintained by the ESLint team. I would recommend reporting an issue on that repository instead.

**Comment by jairusd** [comment]
added issue here: https://github.com/benmosher/eslint-plugin-import/issues/1124

**Comment by platinumazure** [comment]
Closing as this is not an issue with core ESLint.
