### ISSUE TITLE
cannot install eslint on latest node, as Node 10.x is missing in "engines" section of package.json

### ISSUE THREAD

**Issue by Jabher** [eslint/eslint#10519]
**Tell us about your environment**

* **ESLint Version:** 5.0.0
* **Node Version:** 10.1.10

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
> yarn

yarn install v1.3.2
warning package.json: No license field
warning ..\..\..\..\..\package.json: No license field
warning No license field
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.2.3: The platform "win32" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error eslint@5.0.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Process finished with exit code 1
```

**What did you expect to happen?**
eslint installed

**What actually happened? Please include the actual, raw output from ESLint.**
installation exited with code 1

**Comment by platinumazure** [comment]
Hi @Jabher, thanks for the issue.

Node 10 is included in the version range `^6.14.0 || ^8.10.0 || >=9.10.0` (the `>=` means major versions higher than 9.10 are allowed too). Are you quite sure that this is an ESLint problem?

If anything, this seems like a bug in yarn.

**Comment by Jabher** [comment]
@platinumazure Sorry, my bad! Was on windows, node 10 was in windows linux subsystem, node.exe was 9.0.0, accidentially ran windows one.

**Comment by imtmh** [comment]
Resolved it after upgrading to the latest node version.

**Comment by anaam-nizami** [comment]
This [comment](https://github.com/facebook/create-react-app/issues/5396#issuecomment-429565435) may help ;)
