### ISSUE TITLE
Semi-spacing additional behavior inside for statement

### ISSUE THREAD

**Issue by roman4e** [eslint/eslint#10522]
This is definitely rare usage but still occur in developer's code.

**What rule do you want to change?**
Add permission to use different spacing style inside 'for' statement.

**Does this change cause the rule to produce more or fewer warnings?**
Yes

**How will the change be implemented? (New option, new default behavior, etc.)?**
New options: forBefore, forAfter

**Please provide some example code that this change will affect:**
```json
{ "semi-spacing": ["error", {"before": false, "after": true, "forBefore": true}] }
```

```js
var a, b, c; someFunction();
for ( let i = 0 ; i < 15 ; i++ ) {
   callForSomething(i);
}
```
OR using overriding for global before and after rules:
```json
{ "semi-spacing": ["error", {"before": false, "after": true, "forBefore": true, "forAfter": false}] }
```

```js
var a, b, c; someFunction();
for ( let i = 0 ;i < 15 ;i++ ) {
   callForSomething(i);
}
```

**What does the rule currently do for this code?**
Produces warnings if I use more spacing inside for.

**What will the rule do after it's changed?**
Produces less warnings.

**Comment by platinumazure** [comment]
Hi @roman4e, thanks for the issue.

I'll support this.
