### ISSUE TITLE
Unable to run ESLint when folder missing (glob error)

### ISSUE THREAD

**Issue by Sawtaytoes** [eslint/eslint#10528]
**Tell us about your environment**

* **ESLint Version: 5.0.0**
* **Node Version: 8.11.2**
* **yarn Version: 1.6.0**

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I've got 2 projects. One has this source code, the other is calling it. The one that has the code is an npm package. The other is the app that has the npm package as a dependency. When running `executeOnFiles` in version 4, it would skip directories that didn't exist. Now, it errors on those directories.

In this instance, `config/` doesn't exist in the app, but it exists in the npm package. Both the npm package and the app run this same block of code using the same commands from package.json.

```js
const { CLIEngine } = require('eslint')

const config = require('config')

const cli = new CLIEngine({
  cache: true,
  fix: config.isLocalDevelopment(),
})

module.exports = () => {
  const { errorCount, results } = (
    cli
    .executeOnFiles([
      '*.js',
      'config/**/*',
      'scripts/**/*',
    ])
  )

  const formatter = cli.getFormatter()

  const formattedResults = formatter(results)

  formattedResults
  && console.info(formattedResults)

  errorCount > 0
  && process.exit()
}
```

**What did you expect to happen?**
It runs like normal and skips any globed folders that don't exist.

**What actually happened? Please include the actual, raw output from ESLint.**
It errors because the directory is missing.

```
Error: No files matching 'config/**/*' were found.
    at resolvedPathsByGlobPattern.reduce (an-npm-package\node_modules\eslint\lib\util\glob-util.js:244:19)
    at Array.reduce (<anonymous>)
    at Object.listFilesToProcess (an-npm-package\node_modules\eslint\lib\util\glob-util.js:242:59)
    at CLIEngine.executeOnFiles (an-npm-package\node_modules\eslint\lib\cli-engine.js:533:35)
    at module.exports (an-npm-package\scripts\tester\eslint.js:20:4)
    at Object.runDeploymentServer [as server] (the-app\scripts\utils\runScript.js:2:34)
    at runScript (the-app\scripts\utils\runScript.js:15:47)
    at Object.<anonymous> (the-app\index.js:14:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. However, this was an intentional change in ESLint v5 -- see the [migration guide](https://eslint.org/docs/user-guide/migrating-to-5.0.0#nonexistent-files).

**Comment by Sawtaytoes** [comment]
Thanks for your quick response! I read through the migration guide, and it looks like the only fix is selectively figuring out which project has this directory and then doing the glob on it.

This is the solution I used in my code:
```js
  const files = (
    [
      '*.js',
      'config/**/*',
      'scripts/**/*',
    ]
    .filter(fs.existsSync)
  )

  const { errorCount, results } = (
    cli
    .executeOnFiles(files)
  )
```
