### ISSUE TITLE
Path is changed when using a path other than CWD for --ignore-path

### ISSUE THREAD

**Issue by jukebox017** [eslint/eslint#10529]
I want to load an .eslintignore file from a directory other than cwd, but still begin linting from root. This is so I can load a shared .eslintignore from node_modules.

Here is my folder structure:
```
not-src/
- .eslintignore
- this-is-linted.js
src/
- ignore/
   - do-not-lint.js
 - not-linted.js
.eslintrc.json
package.json
```

Contents of .eslintignore:
```
src/ignore/
```

**Tell us about your environment**

* **ESLint Version:** 5.0.1
* **Node Version:** 9.11.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "es6": true,
    "node": true
  },
  "extends": "eslint:recommended"
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let x;
```

```bash
eslint . --ignore-path ./not-src/.eslintignore
```

**What did you expect to happen?**
ESLint should load the `.eslintignore` file from the `not-src` directory and lint from the project root.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint only linted files from the `not-src` directory.

```
/[...]/eslint-test/not-src/this-is-linted.js
  1:5  error  'x' is defined but never used  no-unused-vars
```

✖ 1 problem (1 error, 0 warnings)

**Comment by not-an-aardvark** [comment]
This might be related to https://github.com/eslint/eslint/issues/9227.

**Comment by jukebox017** [comment]
@not-an-aardvark Yes it is. This can be closed in favor of that issue.
