### ISSUE TITLE
quote-props Rule highlights false positives

### ISSUE THREAD

**Issue by MatthewCallis** [eslint/eslint#10535]
**Tell us about your environment**

* **ESLint Version:** v4.19.1
* **Node Version:** v8.11.1
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "plugins": [
    "ava",
    "no-inferred-method-name",
    "no-only-tests",
    "xss"
  ],
  "env": {
    "es6": true,
    "browser": true,
    "mocha": true
  },
  "globals": {
    "sinon": false,
    "mocha": true,
    "expect": true
  },
  # Custom Disabled Rules
  rules: {
    camelcase: 0,
    max-len: 0,
    no-param-reassign: 0,
    no-unused-vars: ["error", { "varsIgnorePattern": "^_", "argsIgnorePattern": "^_", "caughtErrors": "none" }],
    no-plusplus: 0, # Meaningless as other rules prevent the errors that could happen.
    # no-restricted-syntax: 0,
    no-alert: 0,
    no-console: 0,
    "react/react-in-jsx-scope": 0,
    "react/prop-types": 0,
    "react/no-unknown-property": 0,
    "jsx-a11y/anchor-is-valid": 0,
    "object-curly-newline": 0,
    "react/jsx-one-expression-per-line": 0,
    "operator-linebreak": 0
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// Works everywhere
const a = {
  '\u309b': { image: '' }, // eslint-disable-line quote-props
  '\u309c': { image: '' }, // eslint-disable-line quote-props
};

// Works in Chrome, Firefox, errors on Safari when fixed with ESLint.
const b = {
  ゛: { image: '' },
  ゜: { image: '' },
};
```

```bash
Ran from Atom Linter Plugin
```

**What did you expect to happen?**
To report items that can exist without quotes and fix them.

**What actually happened? Please include the actual, raw output from ESLint.**
The removed quotes throw an error in Safari. I believe it is related to the configuration as the demo does not do this, but the available options can cause this to fail:

```
"quote-props": ['error', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. This seems like a bug in Safari, so I would recommend reporting an error there instead. `゜` is a character with the "Other_ID_Start" Unicode property as defined [here](https://unicode.org/reports/tr31/#Backward_Compatibility), and the ECMA262 spec indicates [here](https://tc39.github.io/ecma262/#prod-IdentifierStart) that all characters with the "ID_Start" or "Other_ID_Start" properties are allowed to be used at the start of identifiers.

**Comment by ljharb** [comment]
@not-an-aardvark however, if browsers have this issue, then shouldn't eslint not force it to be unquoted? eslint should work on quote intended for older browsers too.

**Comment by not-an-aardvark** [comment]
Is this an "older version of the spec" issue, or is it just accounting for a specific bug in a specific browser? My gut reaction is that we shouldn't make exceptions in rules to accommodate specific browser bugs -- we're targeting ECMA262 with core rules, not specific browser compatibility thresholds.

**Comment by ljharb** [comment]
@not-an-aardvark that's not accurate; there's a number of eslint rules that handle specific browser compat issues: `no-catch-shadow` for <= IE 8, `no-reserved-keys` (the origin of `quote-props`, in fact) had specific handling of issues with specific browsers, etc.

Regardless, the same logic used to remove the `no-debugger` autofix should apply here - if you only cared about ecma262, then no-debugger would have an autofix, because `debugger` has no behavior in the spec. Since the autofix WAS removed, then this is false, and core rules *absolutely* care about platform behavior as well as the spec. Which is it?

**Comment by not-an-aardvark** [comment]
It's true that in the past we've made rules based on browser-specific behavior. That said, browsers nowadays generally follow the spec much more closely than they did in the past (particularly IE8), so I think the spec is often a better target now. I don't think we should jump to change the behavior of rules whenever a browser bug is discovered, although perhaps I could be convinced otherwise if there are specific cases where a browser bug isn't being fixed by the vendor for a long time and is causing significant problems for users.

`debugger` has an implementation-dependent behavior in the spec; this is effectively the opposite of having "no behavior". I would rather not rehash this discussion.

**Comment by ljharb** [comment]
This is an issue in latest Safari, dating all the way back to Safari 5.1 - I'd say that the rule should be erring on the side of safety, not pedantic correctness.

**Comment by platinumazure** [comment]
@ljharb It seems like maybe we could consider an enhancement here (i.e., a new option for whether or not to force quoting on Other_ID_Start, similar to what we have for numbers). I'm disinclined to think this is a bug, based on @not-an-aardvark's reasoning.

Would you mind opening a new issue to request an enhancement? Thanks!

**Comment by MatthewCallis** [comment]
Would y'all recommend I also file a bug with https://github.com/airbnb/javascript in the case this isn't a bug? I would say it is fair to assume that a style guide not recommend and potentially fix a suggestion that would render code in a modern (modern being released, latest supported version) browser.

I have filed a bug with Apple, but have no way to link to it from what I can tell.

**Comment by ljharb** [comment]
@platinumazure thanks; i'll file an issue at some point when i have the time.

@MatthewCallis i'm not sure what could possibly change in the airbnb styleguide here; eslint would have to make a change to address it.

**Comment by platinumazure** [comment]
@ljharb @MatthewCallis 

> i'm not sure what could possibly change in the airbnb styleguide here; eslint would have to make a change to address it.

Yeah, basically there are two options:

1. airbnb would have to create and publish a custom rule that could extend quote-props but allow quoted property keys that start with a character in Other_ID_Start
1. ESLint would need to add an option to the rule, and airbnb would consume

I have a pretty good idea which one @ljharb would prefer, but he'll need to keep the other option in mind in case we decide not to accept an enhancement proposal.

**Comment by not-an-aardvark** [comment]
Is Other_ID_Start the only group for which Safari has this bug, or are there also other groups?

**Comment by ljharb** [comment]
This is still a bug, and it'd be great to reopen it.
