### ISSUE TITLE
Invalid warning about Webpack config after upgrading to 5

### ISSUE THREAD

**Issue by Simek** [eslint/eslint#10530]
Warning content:
`ESLint: 5.0.1.
No files matching the pattern "webpack.config.*" were found.
Please check for typing mistakes in the pattern.`

According to Webpack Production Guide word "config" isn't necessary in Webpack config files naming:
https://webpack.js.org/guides/production/

* **ESLint Version:** 5.0.1
* **Node Version:** 10.5
* **npm Version:** 6.1.0

**Comment by platinumazure** [comment]
That error isn't about how Webpack config files should or shouldn't look. Rather, the error is about a folder or glob you've passed in to ESLint that doesn't match any files. So if it truly isn't necessary for "config" to appear in your glob patterns, just don't use it.

Places where you might be passing folder names or glob patterns to ESLint:

* Command line: "foo" and "bar/*.tests.js" in `eslint --fix foo "bar/*.tests.js"`
* NPM script: See above
* CLIEngine: Arguments passed to `executeOnFiles` method

If you need more help, please answer the questions posed by eslintbot. Thanks!

**Comment by Simek** [comment]
@platinumazure Thank you for quick answer and tips where to find those patterns. It turned out that the above mentioned pattern was passed in the "executeOnFiles" method in file generated by other script.

**Comment by Mattenable** [comment]
@platinumazure I have a similar issue with 5.0.1 where `.eslintignore` contains a line like `coverage/`, which is meant to ignore any test coverage files generated by istanbul. 

Our build script first runs ESLint, then runs tests. On the first run of the build script, the coverage directory does not exist, but after one successful run, it will.

When that directory does not exist, `eslint *` fails, whereas the same command succeeded using ESLint 4.x
