### ISSUE TITLE
Eslint CLIEngine removes empty line between imports incorrectly, but eslint --fix works

### ISSUE THREAD

**Issue by amosyuen** [eslint/eslint#10567]
**Tell us about your environment**

* **ESLint Version:** 5.0.1
* **Node Version:** 8.11.1
- `yarn` version: 1.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```javascript
const path = require("path");

const config = {
  parser: "babel-eslint",
  env: {
    node: true
  },
  plugins: ["import"],
  rules: {
    "import/order": [
      "error",
      {
        groups: [
          ["builtin", "external"],
          "internal",
          "parent",
          ["sibling", "index"]
        ],
        "newlines-between": "always"
      }
    ]
  },
  settings: {
    "import/resolver": {
      node: {
        root: __dirname
      },
      alias: [["appalias", path.resolve(__dirname, "src/app")]]
    }
  }
};

module.exports = config;
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Run eslint CLIEngine on a source file using `import/order` rule that requires newline between import groups.

run-eslint-cli.js
```js
const eslint = require("eslint");

const config = require("./.eslintrc.js");

const CLIEngine = eslint.CLIEngine;

const cli = new CLIEngine({
  ...config,
  useEslintrc: false,
  fix: true
});
const results = cli.executeOnFiles(["./src/example.js"]);
CLIEngine.outputFixes(results);
console.info("Results:\n" + JSON.stringify(results, null, 2));
```

src/example.js (file being formatted)
```javascript
const fs = require("fs");
const main = require("src/main");

const app = require("appalias");

const packageJson = require("../package.json");

const mainSibling = require("./main");
```

**Reproduction repository:**

https://github.com/amosyuen/prettier-eslint-import-empty-line-removal

**What did you expect to happen?**

eslint shouldn't remove the empty line between `const main = require("src/main");` and `const app = require("appalias");`.

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint CLI engine incorrectly removes the empty line between `const main = require("src/main");` and `const app = require("appalias");`. This causes an eslint error.

However, running the eslint cli directly works. `yarn eslint --fix` will correctly add back the empty line.

**Comment by platinumazure** [comment]
Hi @amosyuen, thanks for the issue.

I don't think your CLIEngine and CLI examples are equivalent:

* In the CLIEngine, you are passing in one config file explicitly and specifying `useEslintrc: false`, which means any `.eslintrc.*` files in ancestor directories won't be used.
* In the CLI example, you seem to be calling `eslint --fix`, which will use our normal config detection to find your config.

You should get consistent behavior by doing one of the following:

* Don't pass the config file to CLIEngine and don't set `useEslintrc: false`
* Call the CLI with `--config ./eslintrc.js --no-eslintrc` to match with the original CLIEngine call

Of these, you probably want the first:

```js
const cli = new CLIEngine({
  fix: true
});
const results = cli.executeOnFiles(["./src/example.js"]);
CLIEngine.outputFixes(results);
console.info("Results:\n" + JSON.stringify(results, null, 2));
```

**Comment by platinumazure** [comment]
Addendum: If you have no other config files, you could also just remove the object spread operator:

```js
const cli = new CLIEngine({
  config,
  useEslintrc: false,
  fix: true
});
const results = cli.executeOnFiles(["./src/example.js"]);
CLIEngine.outputFixes(results);
console.info("Results:\n" + JSON.stringify(results, null, 2));
```

**Comment by amosyuen** [comment]
I don't have any eslintrc files in my ancestors, so I would think it shouldn't affect it. But I tested your suggestions and I seem to be getting some interesting results:

| Method | useEslintRC | Result |
|--------------|-------------|--------|
| eslint --fix | true | Fixed |
| eslint --fix | false | Fixed |
| CLIEngine | true | Fixed |
| CLIEngine | false | Broken |

Also if I remove the object spread operator, then I get a parsing error instead:
```
Results:
{
  "results": [
    {
      "filePath": "E:\\prettier-eslint-import-empty-line-removal\\src\\example.js",
      "messages": [
        {
          "ruleId": null,
          "fatal": true,
          "severity": 2,
          "message": "Parsing error: The keyword 'const' is reserved",
          "line": 1,
          "column": 1
        }
      ],
      "errorCount": 1,
      "warningCount": 0,
      "fixableErrorCount": 0,
      "fixableWarningCount": 0,
      "source": "const fs = require(\"fs\");\r\nconst main = require(\"src/main\");\r\nconst app = require(\"appalias\")
;\r\n\r\nconst packageJson = require(\"../package.json\");\r\n\r\nconst mainSibling = require(\"./main\");\r\n"
    }
  ],
  "errorCount": 1,
  "warningCount": 0,
  "fixableErrorCount": 0,
  "fixableWarningCount": 0
}
```

Exact methods of calling are in https://github.com/amosyuen/prettier-eslint-import-empty-line-removal

**Comment by platinumazure** [comment]
In general, unless you have a good reason for doing so, we recommend storing config in .eslintrc.js or other extension (which you're doing), and using the eslintrc resolution via `useEslintrc: true` (CLIEngine) or by NOT specifying `--no-eslintrc` (command line). That way, ESLint will use its normal configuration detection and resolution approach.

In your last post, you didn't specify exactly how you ran ESLint on the command line. So, just to make sure we're talking about the same things, I will 

* CLI:
  * `yarn eslint --fix`: Should use your .eslintrc.js, should use ancestor directory .eslintrc.js files if they exist, should successfully fix code.
  * `yarn eslint --fix --no-eslintrc`: Should ignore your .eslintrc.js, no linting rules should be on and no fixing should occur.
  * `yarn eslint --fix --no-eslintrc --config ./.eslintrc.js`: Should use your .eslintrc.js, should ignore ancestor directory .eslintrc.js files if they exist, should successfully fix code.
* CLIEngine:
  * `{ fix: true }`: Should use your .eslintrc.js, should use ancestor directory .eslintrc.js files if they exist, should successfully fix code.
  * `{ fix: true, useEslintrc: false }`: Should ignore your .eslintrc.js, no linting rules should be on and no fixing should occur.
  * `{ fix: true, useEslintrc: false, config: config }`: Should use your .eslintrc.js, should ignore ancestor directory .eslintrc.js files if they exist, should successfully fix code.
  * `{ fix: true, useEslintrc: false, config: ...config }`: Should result in weird behavior. This will directly inject your config file object into the CLIEngine options object, without ESLint processing the config file in any way. Some things might work, some won't. So you definitely don't want to do this.

When you say you "removed the ... and then got a parsing error", the error in question suggests that the file might not have been parsed with babel-eslint. If you want, you can share exactly how you ran ESLint in this case and I can take a look and see if we have a bug. But that said, you *probably* just want `{ fix: true }` and everything should work as you would expect.

**Comment by amosyuen** [comment]
You didn't list the case I specified that is broken, which is my original attempt to use CLI engine: `{ fix: true, useEslintrc: false, ...config }`.

Using `{ fix: true, useEslintrc: false, config: config }` causes the parsing error I specified above, which seems to indicate to me that config field isn't actually parsed. https://eslint.org/docs/developer-guide/nodejs-api#cliengine doesn't list a `config` field, are you sure that's valid?

**Comment by amosyuen** [comment]
So after some reading around I think I see the problem. Your 4th case for CLIEngine should correspond to the broken case. I didn't realize it because you had an extra `config:` in there, which I think is a typo.

Looking at https://eslint.org/docs/developer-guide/nodejs-api#cliengine, seems like settings isn't a field on the options, so that would explain why my eslint settings aren't used. I'm guessing instead of `config` field, I think you meant to use `configFile` field.

If that's true then seems like the problem is I was assuming the CLIEngine options should support all the same fields as a normal eslintrc file. While the documentation doesn't list all the fields, this seems like an easy and error prone thing for developers to do. Perhaps some extra documentation warning that it doesn't support all the same fields as eslintrc would be nice. Note: this is exactly how `prettier-eslint` uses CLIEngine, which is what lead me to file this bug in the first place.

For reference, the bug at prettier-eslint https://github.com/prettier/prettier-eslint/issues/181

**Comment by amosyuen** [comment]
Another thing that could be done is to log a warning if the config has unsupported keys.

**Comment by platinumazure** [comment]
Apologies, you're right, I meant configFile. So config isn't actually a
valid option. Using object spread means some of the config file options do
get mapped onto CLIEngine options, but as I said that isn't meant to be a
1-to-1 map. So I still don't recommend using object spread in that case.

Agreed that it would be good to validate options and warn on anything
unrecognized or the wrong type.

**Comment by amosyuen** [comment]
Another problem it seems is `configFile` only accepts a path to a file. So it seems there is no way to define in memory the eslint config `settings`.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here and hasn't circled around a specific action item, so I'm closing the issue. 

If you still need help and think a behavior should be changed, please open a new issue. If you just need clarification on something, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!

**Comment by amosyuen** [comment]
Hey, sorry didn't get back to this in a while, but I think the specific problem is eslint supports only a subset of config options directly on the settings or a path to a config file with full settings. The action item is that eslint should support all config options directly on the settings.
