### ISSUE TITLE
consider moving espree to eslint repo

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10575]
it has some pros:

+ some shared config(like eslintrc)
+ easier to do a prerelease test

drawbacks:
+ might need to update our release tools

**Comment by platinumazure** [comment]
Thanks for the issue!

We can achieve a shared configuration using eslint-config-eslint (that's the whole reason we created that package in the first place).

If you have any suggestions for how to make things better in espree (e.g., if we should release eslint-config-eslint or if we need to solve a specific problem around pre-releases), I think we can try to solve those. We just need to know what those problems are :smile:

**Comment by not-an-aardvark** [comment]
I think one helpful thing would be to do another release of `eslint-config-eslint`, it's been awhile since the last one.

**Comment by Aladdin-ADD** [comment]
could be done in https://github.com/eslint/eslint/issues/10523

**Comment by Aladdin-ADD** [comment]
seems like the team has no strong interests in the movement, closing.
