### ISSUE TITLE
`no-use-before-define` with arrow functions and the top-to-bottom/the stepdown rule Clean Code principle.

### ISSUE THREAD

**Issue by EddyVinck** [eslint/eslint#10589]
**What rule do you want to change?**
`no-use-before-define`

The `no-use-before-define` makes it so you cannot follow the[ 'top-to-bottom' principle or 'the stepdown rule'](https://dzone.com/articles/the-stepdown-rule) from the book Clean Code (by Robert C. Martin or Uncle Bob if you will) when declaring arrow functions. You can get around this by sticking with using the `function` keyword, but I (and I assume others) would like to use arrow functions instead because of the different behavior of `this`.

I think this change behavior is important because it's nice to be able to have an abstract function at the top of your file that explains the behavior of the rest of the file. This function can call other functions that abstract uninteresting details.

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
I have a couple suggestions.

1. Add a new option `arrow-function`  that checks for arrow functions after `let` and `const`
2. Added behavior: Check if `lowerLevelFunction` is called inside another function (`higherLevelFunction`) and only throw an error if `higherLevelFunction` is invoked before `lowerLevelFunction` is declared. This would need to be checked multiple levels deep of course, but I'm sure you get the point.

**Please provide some example code that this change will affect:**

**Before:**
```js
// .eslintrc.js
"no-use-before-define": ["error", { 
      "functions": false,
      "classes": true,
      "variables": true }]

// app.js
const higherLevelFunction = () => {
       // stuff

       const abstractedStuff = lowerLevelFunction(); // no error

       // more stuff
};
const lowerLevelFunction = () => {
       // do something
      return something
};
```

**After**
```js
// .eslintrc.js
"no-use-before-define": ["error", { 
      "functions": true,
      "classes": true,
      "variables": true,
      "arrow-functions": false }]

// app.js
const higherLevelFunction = () => {
       // stuff

       const abstractedStuff = lowerLevelFunction(); // no error

       // more stuff
};
const lowerLevelFunction = () => {
       // do something
      return something
};
```
**What does the rule currently do for this code?**
Throw errors about no-use-before-define when it should not happen

**What will the rule do after it's changed?**
Consider arrow functions as an exception or check the order of function calls like I explained earlier.

**Comment by kaicataldo** [comment]
I'm a bit concerned about potential confusion caused by `variables: true` and `arrow-functions: false`. I wonder if it would be clearer for the option to be called something like `arrow-function-declaration`?

**Comment by ljharb** [comment]
"functions" is for declarations; there's no such thing as an arrow function declaration.

If you want to reference arrow functions lexically before they're defined, then you'd need to set "variables" to true.

**Comment by kaicataldo** [comment]
Right, that is the current behavior of the rule. 

`arrow-function-declaration` may not be correct, but I don't think the option should just be called `arrow-function` either, as this proposal would only apply to the above case.

I'm not championing this change, but I am curious what the perceived downsides would be to a configuration option like this. I wouldn't personally use it, but it seems like a reasonable ask.
