### ISSUE TITLE
ESLint 5.1.0 - No files matching the pattern for several repos

### ISSUE THREAD

**Issue by gnobre** [eslint/eslint#10599]
* **ESLint Version: 5.1.0**
* **Node Version: v8.10.0**
* **npm Version: 6.1.0**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "indent": [
            2,
            4,
            {"SwitchCase": 1}
        ],
        "quotes": [
            2,
            "double"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ],
        "dot-notation": 0,
        "camelcase": 0,
        "strict": 0,
        "no-var": 2,
        "prefer-const": 2,
        "prefer-rest-params": 2,
        "no-unreachable": 2,
        "eol-last": 2,
        "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
        "keyword-spacing": [2, {
            "before": true,
            "after": true
        }],
        "no-multiple-empty-lines": [2, {"max": 2, "maxEOF": 1}],
        "no-trailing-spaces": 2,
        "eqeqeq": 2,
        "no-console": 0,
        "no-alert": 1,
        "complexity": [0, 11],
        "space-before-function-paren": 2,
        "comma-spacing": [2, {"before": false, "after": true}]
    },
    "env": {
        "es6": true,
        "node": true,
        "browser": true
    },
    "extends": "eslint:recommended"
}

```

</details>

------------------------
**What did you do?**

```bash
eslint **/*.js
```

**What did you expect to happen?**
ESLint would run fine as previous versions. No code was changed for this repo since the lat time I ran eslint, suddenly stopped working after ESLint update.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint: 5.1.0.
No files matching the pattern "node_modules/complex.js" were found.
Please check for typing mistakes in the pattern.

This happened for complex.js, decimal.js and fraction.js. The correct path for the three of them is, for instance, `node_modules/complex.js/complex.js`. If I move the file to `node_modules/complex.js` eslint works fine but actually running the script breaks as it looks for `node_modules/complex.js/complex.js`.

**Comment by platinumazure** [comment]
Hi @gnobre, thanks for the issue.

Do you mean to lint in node_modules? That's not something we usually recommend.

I think due to the name of the complex.js package, your glob pattern is matching up to the folder name rather than the filename. That said, the glob pattern is probably being handled by your shell, not ESLint. Perhaps you could try quoting the glob pattern? Then ESLint would be handling the glob, and maybe our glob logic would pick up the necessary files.

**Comment by gnobre** [comment]
That was exactly it! I just had to add quotes to the pattern: `eslint '**/*.js'` 

Working like a charm, thank you.

**Comment by not-an-aardvark** [comment]
@vvscode Please create a new issue or join our [Gitter channel](https://gitter.im/eslint/eslint) if you're having trouble. Thanks!
