### ISSUE TITLE
Why node >=9.1.0?

### ISSUE THREAD

**Issue by Mindaugas-Jacionis** [eslint/eslint#10598]
Generic question here:
is there any specific case why `5.x` version is restricted to use `node` `>=v9.1.0`?
Maybe there is some issues that I am not aware of? :)

**Comment by ljharb** [comment]
https://github.com/eslint/eslint/blob/master/package.json#L127 says it supports 6.14, 8.10, or anything after 9.10 - since v9 is EOL, is there any reason you need to use v9 at all?

**Comment by not-an-aardvark** [comment]
The reason we use v9 at all is that v9.10 was not yet EOL at the time that v5.x came out. More discussion on the oddly-specific version ranges can be found in https://github.com/eslint/eslint/issues/10052 (the tl;dr is that they were roughly the latest released versions on each release line at the time that we made the decision).

**Comment by Mindaugas-Jacionis** [comment]
Ohhh, right - I read `>=` wrongly(need to get that morning coffe). :)

Hmmm, still this is odd - I just had an issue with `eslint v5.x` in my gitlab-ci pipeline that uses node `v9.4.0` container, when switched to `4.x` - issue was gone.  Maybe one of the dependencies gets in the way. Will try to look into this later and report my findings.

For us v9 of node is also there for historic reasons. Will probably switch to 10 anytime this week, just was curious to double check with you guys about the case. :)

**Comment by platinumazure** [comment]
Closing as the question seems to have been answered. Please leave a comment if there is more discussion needed, and we can reopen. Thanks!
