### ISSUE TITLE
Feature: Collect Metrics for most common rule setting

### ISSUE THREAD

**Issue by FL0RIANMEYER** [eslint/eslint#10602]
Feedback API to capture metrics at changed settings to capture the most common rules and evaluate best practice coding styles.

- Present Stats on eslint.org
- Rate rules by github usage (.eslintrc) or change Feedbacks
- Group rules by most common use (like [airbnb config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb))

**Comment by ilyavolodin** [comment]
One of the initial rules that was set by @nzakas is that ESLint should not be "phoning back" any information. We could re-evaluate that, but I think argument would need to be very convincing.

**Comment by not-an-aardvark** [comment]
I don't think this is something we should do. People are placing a lot of trust in ESLint by effectively having it read all of their proprietary code. It seems like many users probably wouldn't be comfortable with us exfiltrating any of that data for analytics, especially when we already have a lot of data available to us in public config files.

**Comment by ilyavolodin** [comment]
> Instead, consider that there are thousands upon thousands of popular open source projects which have already published their configuration files. Retrieving and analysing them on a regular basis to obtain the data is likely to be both easier and less controversial.

Yes, this was done before through Google BigData analysis for a degree thesis. Although it's been a while since that report was generated, so it wouldn't be a bad idea to do it again.
