### ISSUE TITLE
eslint --init for react doesn't install plugins

### ISSUE THREAD

**Issue by pankaja92** [eslint/eslint#10604]
**Tell us about your environment**

* **ESLint Version:** v5.1.0
* **Node Version:**  v8.11.3
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
This is what it automatically generated

```
module.exports = {
    "extends": "airbnb"
};

```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash

eslint --init

```

**What did you expect to happen?**
Configure plugins as well 
```
module.exports = {
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-ally",
        "import"
    ]
};
```

**What actually happened? Please include the actual, raw output from ESLint.**
Configured only extends
```
module.exports = {
    "extends": "airbnb"
};
```

This is what I followed running `eslint --init` 

```
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb (https://github.com/airbnb/javascript)
? Do you use React? Yes
? What format do you want your config file to be in? JavaScript
Checking peerDependencies of eslint-config-airbnb@latest
? The style guide "airbnb" requires eslint@^4.19.1. You are currently using eslint@5.1.0.
  Do you want to downgrade? Yes
The config that you've selected requires the following dependencies:

eslint-config-airbnb@latest eslint@^4.19.1 eslint-plugin-import@^2.12.0 eslint-plugin-jsx-a11y@^6.0.3 eslint-plugin-react@^7.9.1
? Would you like to install them now with npm? Yes
Installing eslint-config-airbnb@latest, eslint@^4.19.1, eslint-plugin-import@^2.12.0, eslint-plugin-jsx-a11y@^6.0.3, eslint-plugin-react@^7.9.1
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ eslint-config-airbnb@17.0.0
+ eslint@4.19.1
+ eslint-plugin-jsx-a11y@6.1.0
+ eslint-plugin-import@2.13.0
+ eslint-plugin-react@7.10.0
added 6 packages from 6 contributors, removed 2 packages, updated 10 packages, moved 1 package and audited 14721 packages in 12.911s
found 0 vulnerabilities

Successfully created .eslintrc.js file in /home/pankaja/Documents/Projects/Ideas/weekli/client
```

**Comment by platinumazure** [comment]
Hi @pankaja92, thanks for the issue.

You are correct that the ESLint configuration doesn't show the plugins, but I'm not sure it needs to: the airbnb configuration should include the plugins.

Can you please confirm the following:

1. Does your package.json contain the packages in devDependencies?
1. Does `npm ls | grep eslint` (or equivalent) show the dependencies?
1. Can you run ESLint successfully (`npx eslint` or `./node_modules/.bin/eslint`) even though the configuration doesn't explicitly list the plugins?

If all of the above work, then I think this is working as designed. There should be no need to list the plugins in your .eslintrc.js if they're used by a shared config.

**Comment by Gallagher94** [comment]
I had a similar  warning message, running 
-     - npx install-peerdeps --dev eslint-config-airbnb
solved the peer issue.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
