### ISSUE TITLE
[eslint] Parsing error: Unexpected token *

### ISSUE THREAD

**Issue by we18** [eslint/eslint#10614]
```var f = 10 ** 2;```
eslint] Parsing error: Unexpected token *

How to fix my config?

**Comment by platinumazure** [comment]
Hi @we18, thanks for the issue.

You need to include a `parserOptions` section in your config, if not already present. In that section, you need to set an `ecmaVersion: 2016` property.

In future, please include your existing config (or, if you have no config, state that) when reporting issues that might have to do with configuration. It really helps us identify issues more easily! :smile:
