### ISSUE TITLE
Requiring 2FA for the ESLint GitHub organization

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#10630]
In light of recent events, I think this would be a good time to start requiring 2FA to be enabled for members of the `eslint` organization on GitHub. People in the organization (particularly TSC members) have a lot of access with their GitHub accounts, and it's important for us and for our users that we keep the accounts safe.

Currently, 26 of the 34 members of the organization have 2FA enabled. Of the remaining 8, two are bot accounts (@eslintbot and @jquerybot) and two are TSC members. In order to do this, we would need to enable 2FA for all of the remaining accounts, otherwise those accounts would be removed from the organization when we started requiring 2FA. We would also have to ensure that the bot accounts are still able to function correctly with 2FA enabled, or we could remove them from the organization if their functionality has been superseded by [`eslint-github-bot`](https://github.com/eslint/eslint-github-bot). (I think the @eslintbot account is still used to push commits during releases.)

**Comment by platinumazure** [comment]
What do we even use jquerybot for, anyway? Is it related to the current CLA checks, or a previous implementation? (Or something else?)

**Comment by not-an-aardvark** [comment]
I think it was previously used to add the `CLA: valid` and `CLA: invalid` labels. As far as I know, it's no longer used for anything.

**Comment by not-an-aardvark** [comment]
@jquerybot has been removed from the organization since it's not used for anything anymore.

**Comment by Aladdin-ADD** [comment]
after enabling 2FA, I was asked to input user & password in every push(ノへ￣、):

![image](https://user-images.githubusercontent.com/13050025/44306311-677a9280-a3be-11e8-95d2-70e52fd80ec8.png)

is there a way to skip this?

**Comment by not-an-aardvark** [comment]
Yes, you can create a personal access token for the command line: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by Aladdin-ADD** [comment]
👍 it works! thanks!!

**Comment by lydell** [comment]
You can also use SSH instead of HTTPS.

**Comment by not-an-aardvark** [comment]
There were four TSC members at the meeting in favor of enabling the setting on September 13th, and one additional TSC member added a :+1: to https://github.com/eslint/eslint/issues/10630#issuecomment-417454558, so the resolution is to enable the setting on September 13th.

**Comment by not-an-aardvark** [comment]
I've enabled the setting; all organization members are now required to use 2FA. The one remaining member that did not have 2FA enabled has been temporarily removed from the organization, and invited back (although they will need to enable 2FA in order to accept the invitation).
