### ISSUE TITLE
eslint v6 wish list

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#10644]
In the spirit of [previous wish lists](https://github.com/eslint/eslint/issues/8972), now that v5 has shipped, what big changes do we want to see in v6? We can use this issue for brainstorming and discussing ideas. For the changes we want to tackle for v6, we'll then create issues in the v6.0.0 milestone.

**Comment by not-an-aardvark** [comment]
* I'd like to improve the ergonomics of using custom rules. There are currently a few problems that add a high barrier to entry:
    * Using project-specific rules requires either either creating a separate plugin package, using the `--rulesdir` flag and effectively breaking editor integrations, or using a hack like [`eslint-plugin-rulesdir`](https://github.com/not-an-aardvark/eslint-plugin-rulesdir).
    * Adding custom rules to a shareable config requires all users of the shareable config to manually install a plugin.

    As a result of these problems, we get significantly more pressure to add new core rules and features since it's harder for users to create their own. 
* I'd like to make ESLint's config-loading compatible with package tools like `lerna`, by resolving the issues described in https://github.com/eslint/eslint/issues/10125.
* I'd like to add native support for parallel linting (https://github.com/eslint/eslint/issues/3565).
* I'd like to improve the security of our infrastructure and release operations, to reduce the likelihood of  compromised accounts and malicious publishes in the future.

**Comment by platinumazure** [comment]
I'd like to see if we could eliminate the local vs global installation problem in some way.

* Personally, I would love to see local-only installations (including working with any IDE integrations or other folks that are currently depending on global installations only).
* Ideally, I would like to see eslint-cli become the only globally installed thing and it would just have --init and not much else, and it would install everything needed and then use the local installation from there.
* Despite the above, I'm open to other options-- anything to reduce the pain point for users.

**Comment by kaicataldo** [comment]
I would love to go after parallel linting for this next major version. Feels overdue and could have a huge impact.

**Comment by jorgegonzalez** [comment]
Personally, I would love the JavaScript community to embrace TOML format configuration files more, as it is subjectively superior to both YAML and JSON configurations. ESLint could lead the community in this by supporting `.eslintrc.toml` files.

Some reasons why TOML is better than YAML for configuration files: arp242.net/weblog/yaml_probably_not_so_great_after_all.html

Some arguments against JSON as a configuration language: lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language

**Comment by ilyavolodin** [comment]
Everything that's already been said before, plus I would want to revisited discussion about tags for rule metadata. I think rule findability is a very big pain for users, tags might be able to help with that a bit.

**Comment by ljharb** [comment]
AST-based autofixing

**Comment by MayhemYDG** [comment]
I wish `babel-eslint` would be the default parser.
- I wish ESLint had TypeScript support out of the box, maybe via parser options. I've found `typescript-eslint-parser` to have minor bugs, and not all rules are compatible, though that's not a parser-specific issue.
- `babel-eslint` has support for upcoming syntax features like class properties. Using babel to use new syntax features is a common practice, so it's hard to use ESLint without `babel-eslint`.

**Comment by ljharb** [comment]
Better than babel-eslint, it'd be great if eslint could parse stage 3 features by default.

**Comment by StreetStrider** [comment]
Found this topic through search "plugin resolve". I got an issue which is described in @not-an-aardvark 's first point. Seemes that using custom configs with plugins distributed as a package is not possible, since plugin's resolves are relative to config consumer side and not config package side. So if I use custom config I must to install eslint plugins on the consumer side, breaking config package encapsulation.

I would like it to be possible to do things like
```js
{ parser: require.resolve('babel-eslint'), }
```
with plugins at least in the same manner:
```js
{ plugins: [ require.resolve('eslint-plugin-flowtype') ] }
```
or even better — to make resolving algorithm better, so it would not require any additional efforst from consumer.

**Comment by platinumazure** [comment]
Reopening, as this type of issue has been a source of valuable ideas for the roadmap. I've signed this to myself to avoid auto-closure.

**Comment by StreetStrider** [comment]
@silverwind unfortunately, LoDash' function modules are deprecated.

**Comment by silverwind** [comment]
@StreetStrider where did you get that from? Modules like https://www.npmjs.com/package/lodash.clonedeep are in widespread use and I see nothing about a deprecation.

**Comment by StreetStrider** [comment]
@silverwind yes, soft deprecation. They will not make into next major.

**Comment by sindresorhus** [comment]
> Possible solutions could be to bundle the CLI to a single file similar to how yarn does it.

The [`ncc`](https://github.com/zeit/ncc) package would be useful for that.

**Comment by aladdin-add** [comment]
Hopefully we can drop supporting node 6.x in eslint v6.0.0, so we can start supporting some async function api.

![image](https://user-images.githubusercontent.com/13050025/52561946-d6015000-2e37-11e9-95b4-f42d79517fa5.png)

**Comment by ljharb** [comment]
You can support that API already from plugins/rules/etc in the sense that `async function` is just a promise-returning function; you could use babel if you wanted to use the syntax - the only thing that dropping node 6 gets you is the ability for eslint itself to use the syntax without a build process.

**Comment by not-an-aardvark** [comment]
I think we should probably drop support for v6.x anyway given that it reaches EOL in April, and the major release will probably happen in April or later given how long prereleases have taken in the past.

**Comment by mysticatea** [comment]
Closing as released.
