### ISSUE TITLE
Parsing error: Unexpected token (strange warnings)

### ISSUE THREAD

**Issue by MikhailMelnikovNsk** [eslint/eslint#10681]
Webpack 4.16.2
Typescript 2.9.2
Eslint 5.2.0

![err](https://user-images.githubusercontent.com/40119987/43265260-76886eb4-9112-11e8-8986-56e4492c2107.jpg)

All files with warnings '.ts'

**Comment by MikhailMelnikovNsk** [comment]
1. Eslint **5.2.0**

2. **Updated webpack (3 to 4) and all packages (npm)**.

I use 'webpack' + 'vue' + 'typescript'.

4. The error is somehow related to **typescript**.

Maybe someone has the same problems.

[.babelrc.txt](https://github.com/eslint/eslint/files/2234702/default.babelrc.txt)
[.eslintrc.js.txt](https://github.com/eslint/eslint/files/2234703/default.eslintrc.js.txt)
[tsconfig.json.txt](https://github.com/eslint/eslint/files/2234704/tsconfig.json.txt)

**Comment by kaicataldo** [comment]
@MikhailMelnikovNsk Mind inlining these configs?

**Comment by MikhailMelnikovNsk** [comment]
Explained how could...

Another note: this error (Unexpected token) cannot be disabled by comments.
