### ISSUE TITLE
Is there a way to disable indent checking?

### ISSUE THREAD

**Issue by bigradish** [eslint/eslint#10696]
I use tab for indent, but eslint report this as errors. How to disable it? thanks.

**Comment by platinumazure** [comment]
As a side note, you can run ESLint with the `--print-config` option (along with a filename) and ESLint will print out the entire resolved configuration for that file. This will help confirm if some configuration file has enabled the `indent` rule.

**Comment by bigradish** [comment]
Thank you so much @not-an-aardvark and @platinumazure 
I use eslint in a vue project. Now I use the following rules in the  .eslintrc.js file to remove the indent errors:
```
rules: {
  'no-tabs': 'off',
  'indent': 'off',
}
```

**Comment by not-an-aardvark** [comment]
Great, I'm glad it's working now. Closing this issue since the question seems to be answered, but feel free to join our [Gitter channel](https://gitter.im/eslint/eslint) or open another issue if you have more questions.
