### ISSUE TITLE
Make Sort Keys Fixable, the Return

### ISSUE THREAD

**Issue by bennyhobart** [eslint/eslint#10715]
Hey Everyone,

There was a much-needed discussion around how auto fixing sort-keys will change how the code functions at runtime ([7714](https://github.com/eslint/eslint/issues/7714)).

This is not ideal, but I feel this is the case that `// eslint-disable` is justified. If teams are deciding to warn (or prevent) developers from having unsorted keys, why wouldn't we give them the ability to simply fix it?

I'm happy to tackle this problem if I get a strong signal to make this rule auto-fixable

**Comment by ljharb** [comment]
Note that if sort-keys is made autofixable, the autofix *must not* move anything across a spread boundary - meaning:
```js
const o = {
  d,
  b,
  ...other,
  c,
  a
};
```

can ONLY be safely autofixed to:
```js
const o = {
  b,
  d,
  ...other,
  a,
  c
};
```

which will mean that there could still be a linter warning remaining - one that only a human can satisfy.

**Comment by TheSavior** [comment]
Should sort-keys only care about either side of the spread?

**Comment by Daniel15** [comment]
> Should sort-keys only care about either side of the spread?

This sounds reasonable, at least as an option.

**Comment by not-an-aardvark** [comment]
I'm still opposed to this change for the same reasons as in https://github.com/eslint/eslint/issues/7714 -- changing the order of keys can subtly break code, and I don't think an autofixer for a core rule should do that under any circumstances.

> If teams are deciding to warn (or prevent) developers from having unsorted keys, why wouldn't we give them the ability to simply fix it?

Unfortunately, it's not possible to automatically fix it. It's possible to automatically change the order of the keys, but it's not possible to automatically change the other parts of the code that might inadvertently be depending on the original order of the keys. A user would need both of these to be accomplished in order for the linting problem to be properly "fixed".

**Comment by bennyhobart** [comment]
Pragmatically this is a waste of time for a lot of devs; the average case doesn't break due to autofixing, and comments should document the cases where it does.

Idealisticaly I agree with the eslint team, this opens doors to autofixing `var => let` and other behaviors that can introduce subtle bugs, which definitely shouldn't be apart of the core rules.

I think moving forward there's space for an eslint plugin "sort-keys-autofix" that is the same as this but provides auto fixing functionality, taking into account @ljharb's advice.

Cheers and thanks for this great tool!

**Comment by bennyhobart** [comment]
`Should sort-keys only care about either side of the spread?` is probably better suited to another issue so I'm closing this one

**Comment by ljharb** [comment]
It's worth noting that object key ordering is set in ES2015 and later, so anyone who this autofix would break is going to be broken by every single browser already.

**Comment by not-an-aardvark** [comment]
@ljharb I'm not sure what you mean -- object key ordering is deterministic based on how the properties are ordered in the source code, so it would change when the ordering in the source code is changed.

```js
var foo = { b: 0, a: 0 };

console.log(Object.keys(foo))
// prints ['b', 'a'] as-is, or ['a', 'b'] if the keys were reversed in the `foo` source code
```

**Comment by ljharb** [comment]
ahh yes, you're right - it's insertion order for non-numeric keys.

I still don't think this is a real concern; anyone relying on key ordering will break in *older* browsers too :-)

**Comment by bennyhobart** [comment]
As @ljharb said, I'm pretty sure key ordering was defined in ES6, until then it was based on browser implementation

**Comment by gajus** [comment]
FYI, there is a plugin that implements a fixable version of sort-keys.

https://github.com/leo-buneev/eslint-plugin-sort-keys-fix

This addresses issues described in:

* https://github.com/eslint/eslint/issues/10324
* https://github.com/eslint/eslint/issues/7714

Unfortunately, it is currently unsafe to use with spread operator. I have raised an issue.

https://github.com/leo-buneev/eslint-plugin-sort-keys-fix/issues/3
