### ISSUE TITLE
Internal consistent-docs-url rule crashes if meta.docs isn't present

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#10722]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

According to the internal ESLint config around rules:

```yml
rules:
    rulesdir/consistent-docs-url: "error"
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
module.exports = {
    meta: {}
};
```

```bash
npm run lint
```

**What did you expect to happen?**

Either a lint error about the lack of `meta.docs` (or `meta.docs.url`), or nothing if that is covered by another rule.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint crashes, with an error message from `context.report` that the node location must be passed if the node is not passed.

--------

I believe the problem is in [this area](https://github.com/eslint/eslint/blob/master/tools/internal-rules/consistent-docs-url.js#L48-L57), where we check for the absence of `metaDocsUrl` but don't check that `metaDocs` is non-null before sending it to `context.report`.

**Comment by s4san** [comment]
PR - #10711
