### ISSUE TITLE
eslint-disable-next-line does not work as expected

### ISSUE THREAD

**Issue by npasquet** [eslint/eslint#10725]
**Tell us about your environment**

* **ESLint Version:**
v4.16.0
* **Node Version:**
v10.3.0
* **npm Version:**
v6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
`default`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// .eslintrc.json
{
    "extends": [
        "airbnb-base"
    ],
    "parserOptions": {
        "ecmaVersion": 2017
    }
}

// package.json
{
  "name": "eslint-issues",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "eslint": "4.16.0",
    "eslint-config-airbnb-base": "12.1.0",
    "eslint-plugin-import": "2.8.0"
  },
  "scripts": {
    "lint": "eslint --color index.js"
  },
  "engines": {
    "node": "10.3.0"
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

toto.json is dynamically generated by CI scripts

```js
/* eslint-disable-next-line import/no-unresolved */
const toto = require('./toto');

console.log(toto);
```

```bash
eslint --color index.js
```

**What did you expect to happen?**

Eslint should acknowledge the inline comment and not raise an error

**What actually happened? Please include the actual, raw output from ESLint.**

I'm requiring a file that is generated by e2e testing stage in CI environment so I add `/* eslint-disable-next-line import/no-unresolved */` so the linter stage that precedes it will pass.

```
$ eslint --color index.js

/Users/nicolas/Projects/github-issues/index.js
  1:22  error    Unable to resolve path to module './toto'  import/no-unresolved
  3:1   warning  Unexpected console statement               no-console

✖ 2 problems (1 error, 1 warning)

error Command failed with exit code 1.
```

**Comment by mysticatea** [comment]
`eslint-disable-next-line` in block comments is supported since [v4.18.0](https://eslint.org/blog/2018/02/eslint-v4.18.0-released). Use line comments `// eslint-disable-next-line` or a newer version of ESLint.

**Comment by npasquet** [comment]
@mysticatea Thank you I will use line comments for now.
