### ISSUE TITLE
replacement for requirePaddingNewLinesAfterBlocks

### ISSUE THREAD

**Issue by cup** [eslint/eslint#10731]
The JSCS site was closed, and I am not seeing a good replacement for this rule.
I found this:

http://eslint.org/docs/rules/padding-line-between-statements

but its not clear if or how this could be used to mimic the old rule. Note that
AirBnb defines this rule as well:

http://github.com/airbnb/javascript#whitespace--after-blocks

I found some older issues but they were locked by the bot:

- https://github.com/eslint/eslint/issues/7356
- https://github.com/eslint/eslint/issues/3092

and even an AirBnB issue:

https://github.com/airbnb/javascript/issues/1660

PS: that bot seems too aggressive. 8 months and it locks the issue? Why is
locking even needed as the issues were already closed?

**Comment by kaicataldo** [comment]
Apologies that this was missed until now. Does `padding-line-between-statements with the following config solve your issue?

```
padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: "block", next: "*" }
]
```

**Comment by BBoehm** [comment]
For future visitors, the following rule might help as well (and can be combined with the aforementioned rule):

padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: "block-like", next: "*" }
]
