### ISSUE TITLE
Documentation about Caching is outdated

### ISSUE THREAD

**Issue by ajafff** [eslint/eslint#10739]
**The version of ESLint you are using.** v5.3.0

**The problem you want to solve.**

Since #10571 now also stores the result of failing files, the docs are no longer correct: https://eslint.org/docs/user-guide/command-line-interface#caching

> Note:: As of now, only the results for successfully linted files are stored in the cache. Files which fail linting are not stored in the cache, so they will be linted every time.

**Your take on the correct solution to problem.**

Just remove this paragraph.

**Comment by platinumazure** [comment]
Hi @ajafff, thanks for the issue. This would definitely be a worthwhile change.

Would you like to submit a pull request?

**Comment by ajafff** [comment]
@platinumazure I just opened #10740 to fix this
