### ISSUE TITLE
one-var with --fix is adding multiple empty lines between var declarations on keeping on the same line

### ISSUE THREAD

**Issue by carlos-algms** [eslint/eslint#10741]
**Tell us about your environment**

* **ESLint Version:**
v5.2.0

* **Node Version:**
8.11.3

* **npm Version:**
5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "env": {
    "browser": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 5
  },
  "rules": {
    "indent": ["error", 2],
    "linebreak-style": ["error", "unix"],
    "quotes": ["error", "single"],
    "semi": ["error", "always"],
    "one-var": ["error", "never"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

**Input A** 
```js
var a = 1, b = 2, c = 3;
```
**Output A** 
```js
var a = 1; var b = 2; var c = 3;
```

**Input B** 
```js
var a = 1, 
  b = 2, 
  c = 3;
```
**Output B** 
```js
var a = 1;
 
    
var b = 2;
 
    
var c = 3;
```

```bash
eslint --quiet --fix src/
```

**What did you expect to happen?**
Do not include multiple lines between variables declaration

**Expected output on both cases** 
```js
var a = 1; 
var b = 2;
var c = 3;
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

I'm confused because you have three different blocks of code labeled as `output`. Could you clarify which one is the actual output after running `eslint --fix`? Are the other two samples also related to the issue?

**Comment by carlos-algms** [comment]
@not-an-aardvark sorry, I've updated the description.

**Comment by kaicataldo** [comment]
Actually, it looks like this might be the intended behavior given [these tests](https://github.com/eslint/eslint/blob/master/tests/lib/rules/one-var.js#L880).

**Comment by kaicataldo** [comment]
@eslint/eslint-team Thoughts on this? We now have an open PR, so I'd love for to come to a consensus.

**Comment by Aladdin-ADD** [comment]
Every eslint rule is standalone, and the rule doesn't know the other rules' config. so it's likely that the fixed code causing other warnings(e.g.max-statements-per-line).

that's say, I deem it as a enhencement, rather than a bug.

**Comment by eatorres** [comment]
This does feel like a bug rather than the intended behaviour. --fix shouldn't do more than what the rule intends it to do

**Comment by podkot** [comment]
reopen please, the current behavior is quite annoying when `--fix` is applied on a large legacy codebase

**Comment by aladdin-add** [comment]
well, I'll champion this!

**Comment by carlos-algms** [comment]
> This does feel like a bug rather than the intended behaviour. --fix shouldn't do more than what the rule intends it to do

It is a bug when the fix cause more problems, like including useless empty lines between declarations.
That is not acceptable on any style-guide.
