### ISSUE TITLE
max-depth restarts at each function

### ISSUE THREAD

**Issue by garyking** [eslint/eslint#10746]
**The version of ESLint you are using.** v4.19.1

**The problem you want to solve.** `max-depth` restarts at each function

**Your take on the correct solution to problem.**

In the [docs for max-depth](https://eslint.org/docs/rules/max-depth), in the first example, it claims it is nested 5 deep. But if I use the same example, then the deepest block is actually 3 deep. The counting seems to restart at the `val` function expression.

Therefore, are the docs incorrect, or the rule incorrect, or am I simply missing something?

**Comment by MartinMuzatko** [comment]
Yes! I would also love to have a rule for max indentation, I hoped that max-depth is what I was looking for.
