### ISSUE TITLE
ESLint CLI: using more than 1 option in rule options failed

### ISSUE THREAD

**Issue by dskuratovich** [eslint/eslint#10745]
Hey everyone!
I have just failed an attempt to use ESLint CLI.

I have tried to run this command in Ubuntu:
`npx eslint app/services/consts.js --rule max-len:[2,20,{ignoreComments:true,ignoreStrings:true}]`
As soon as it's finished I got the following:
![image](https://user-images.githubusercontent.com/4585857/43847115-8da4257c-9b38-11e8-97e4-f0450f7ea3e4.png)

And the question isn't it possible to use multiple options in rule or I did something wrong?

Versions:
* ESLint: v4.19.1
* NPM: v6.2.0
* Node: v8.10.0

**Comment by platinumazure** [comment]
Might be that your shell is interpreting some characters before they are sent to ESLint. Can you try quoting the rule argument?

```shell
npx eslint app/services/consts.js --rule "max-len:[2,20,{ignoreComments:true,ignoreStrings:true}]"
```

**Comment by dskuratovich** [comment]
@platinumazure wow! Thanks so much, now that works!
Sorry for this sort of stupid question, you made my day!

**Comment by dskuratovich** [comment]
The issue has been resolved by @platinumazure
