### ISSUE TITLE
sort-keys not working with spread props

### ISSUE THREAD

**Issue by csantos1113** [eslint/eslint#10760]
**Tell us about your environment**

* **ESLint Version:** 5.3.0
* **Node Version:** 9.10.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
None
**Please show your full configuration:**

```js
{
    "parserOptions": {
        "ecmaVersion": 9,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "sort-keys": 2
    },
    "env": {
        "browser": true
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const a = {
  a: 'a',
  x: 'x',
  b: 'b'
};

const b = {
  ...a,
  t: 't',
  d: 'd'
};
```
Fully replicable in **[ESLint Demo](https://eslint.org/demo/#eyJ0ZXh0IjoiY29uc3QgYSA9IHtcbiAgYTogJ2EnLFxuICB4OiAneCcsXG4gIGI6ICdiJ1xufTtcblxuY29uc3QgYiA9IHtcbiAgLi4uYSxcbiAgdDogJ3QnLFxuICBkOiAnZCdcbn07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InNvcnQta2V5cyI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlfX19)**

**What did you expect to happen?**
I'm expecting to see errors in lines:
`b: 'b'` and `d: 'd'`

**What actually happened? Please include the actual, raw output from ESLint.**
I'm not getting the error in line `d: 'd'`

**Comment by peanutenthusiast** [comment]
@keepitrio and I are interested in taking this one!

**Comment by infctr** [comment]
yeah, that kinda renders this rule useless
