### ISSUE TITLE
Please lint IndexedDB API too

### ISSUE THREAD

**Issue by vitaly-zdanevich** [eslint/eslint#10789]
Currently no error for this:

    indexedDB.open('my-db-name', 'this-is-incorrect-param')

But [open()](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open) accept only name of the database and optional integer.

**Comment by ilyavolodin** [comment]
ESLint is a plugable linter. It allows users to create their own rules and plugins to lint framework-specific code. ESLint itself doesn't have rules that are specific to any framework. So if you want to be able to lint IndexedDB APIs, you can create a plugin that would focus specifically on that API. You can find more information about building plugins here: https://eslint.org/docs/developer-guide/working-with-plugins

**Comment by vitaly-zdanevich** [comment]
Yes, but IndexedDB is part of any browser, this is not separate external framework.

**Comment by platinumazure** [comment]
There are more runtimes than just the browser. We have NodeJS, Rhino, Spidermonkey, PhantomJS, etc. We realistically can't support all possible runtimes fully, so we focus on pure ECMAScript. (Yes, I know we have Node-specific rules, but those are historical and we would not let them into ESLint core today.)

Please let us know if you need help making a plugin.

**Comment by g-plane** [comment]
This work can be done well with a type checker like TypeScript.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
