### ISSUE TITLE
'one-var': separateRequires does not work in consecutive mode

### ISSUE THREAD

**Issue by tarol** [eslint/eslint#10784]
**Tell us about your environment**

* **ESLint Version:**5.3.0
* **Node Version:**8.11.3
* **npm Version:**6.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
    jest: true
  },
  parser: 'babel-eslint',
  rules: {
    'one-var': [2, { var: 'consecutive', let: 'consecutive', const: 'consecutive', separateRequires: true }],
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const foo = require("foo");
const bar = "bar";
```

```bash

```

**What did you expect to happen?**
no error
**What actually happened? Please include the actual, raw output from ESLint.**
[eslint] Combine this with the previous 'const' statement. (one-var)

**Comment by ilyavolodin** [comment]
I can reproduce this issue. Seem like a bug to me. It looks like `const: 'consecutive'` takes priority.
