### ISSUE TITLE
very good

### ISSUE THREAD

**Issue by bcliuxing** [eslint/eslint#10786]
I'm using ESLint v1.0.0-rc-2 and I (have some feedback|found a bug). I used this code

(include full code)

and this configuration

(include full configuration)

And got this output:

(include full ESLint output)

I expected this instead:

(describe what you thought should happen or what you'd like to happen)

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue. Please feel free to [create an issue](https://github.com/eslint/eslint/issues/new?template=BUG_REPORT.md) and fill out the questions in the template if you'd like to report a bug.
