### ISSUE TITLE
Can't get eslint to work on Linux (a Devbox.. maybe relevant)

### ISSUE THREAD

**Issue by moteleolu** [eslint/eslint#10791]
**Tell us about your environment**
GNU/Linux 3.19.0-65-generic x86_64

* **ESLint Version:**
eslint@5.4.0 

* **Node Version:**
v4.2.6

* **npm Version:**
3.5.2

<details>
<summary>Configuration</summary>

</details>

I've run this: 
```bash
sudo npm install -g eslint
```
Gotten this: 
<img width="922" alt="screen shot 2018-08-22 at 2 54 34 pm" src="https://user-images.githubusercontent.com/8581299/44493017-55e1f680-a61b-11e8-8fbd-899a5fbdcd75.png">

trying to use  e.g Ran ``` eslint -v ``` and keep getting 
<img width="572" alt="screen shot 2018-08-22 at 4 46 27 pm" src="https://user-images.githubusercontent.com/8581299/44496793-fab80000-a62a-11e8-884a-8f0f759c7488.png">

**Comment by not-an-aardvark** [comment]
Hi,

ESLint v5 only supports Node versions above v6.14.0. I would recommend upgrading the version of Node used on your server, or if that's not possible, downgrade to ESLint v4.19.1 instead.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!

**Comment by moteleolu** [comment]
sorry, should've closed this weeks ago
