### ISSUE TITLE
Add ignoreJsxPlainText to max-len

### ISSUE THREAD

**Issue by merlinpatt** [eslint/eslint#10797]
**What rule do you want to change?**
max-len

**Does this change cause the rule to produce more or fewer warnings?**
If turned on, it will produce fewer warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
Add an option `ignoreJsxPlainText` (or a better key) to the `max-len` configuration. Set it to `true` to ignore any lengthy plain text in between JSX tags

**Please provide some example code that this change will affect:**

```js
<p>
  Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. Nearly-Headless Nick now string them together, and answer me this, which creature would you be unwilling to kiss? 
</p>
```

**What does the rule currently do for this code?**
Currently `max-len` warns that the line exceeds the maximum line length

**What will the rule do after it's changed?**
This will prevent any warnings or errors when JSX plain text is too long

**Comment by bendtherules** [comment]
Very much needed. Will be a JSX sibling to `ignoreStrings`.

**Comment by AdsonCicilioti** [comment]
Omg!

**Comment by wilsonrocks** [comment]
I want this so much I would be prepared to try and implement it myself which would be my first contribution to a public library

**Comment by platinumazure** [comment]
@wilsonrocks Would you mind opening a new issue? (You could copy/paste the markdown from this issue's original post, but you could optionally incorporate the feedback suggested by Kai as well if you wanted.)

Hopefully Kai or someone else on the team might champion the new proposal.

Thanks for your interest!
