### ISSUE TITLE
Consider removing the auto-fix logic for no-debugger

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint#10794]
**What rule do you want to change?**
`no-debugger`

**Does this change cause the rule to produce more or fewer warnings?**
Neither.

**How will the change be implemented? (New option, new default behavior, etc.)?**
I propose completely removing auto-fixing for the `no-debugger` rule. Just treat it as another one of those rules that has no auto-fix.

**Please provide some example code that this change will affect:**

```js
debugger;
```

**What does the rule currently do for this code?**
It warns if you use the `debugger` statement.

**What will the rule do after it's changed?**
It will work exactly the same, it just won't be auto-fixable.

**Why?**

It's annoying when you add a `debugger` statement and save the file, and the `debugger` statement just quietly disappears. It's hard to see why anyone would want that behaviour.

If someone chooses to use the `no-debugger` rule, it's probably because they don't want to _commit_ code with the `debugger` statement. It's not because they want it to be automatically cleaned up when they 'accidentally' type it in.

It would be easy to auto-fix console.logs by deleting them too, but that doesn't happen with `no-console`, because that would be silly. The same is true for `debugger`. Just because it's easy to autofix doesn't mean it should be autofixed. Just leave it marked as a lint error, and let the developer deal with it in their own time.

Existing workarounds:

1. Whenever you insert a debugger statement, disable auto-fixing, save the file, and remember to re-enable it afterwards.
2. Add `// eslint-disable-line` whenever you add a `debugger` statement.
3. Configure your editor to override and disable autofix just for this rule.

These are all high-friction and imo unacceptable workarounds for something that has very little real benefit in the first place.

**Comment by platinumazure** [comment]
Hi @callumlocke, thanks for the issue.

What version of ESLint are you using? I'm asking because we actually removed the autofixer for `no-debugger` in e862dc3a8e500afb54a229a20ce892272bf41860, which was released in ESLint 5.1.0. So if you upgrade to that version, you should have an autofix-free version of the rule :smile:

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
