### ISSUE TITLE
`space-unary-ops` can override `space-in-parens`

### ISSUE THREAD

**Issue by ilovett** [eslint/eslint#10795]
Example is to enforce space before and after `!` and should be valid inside parens even is `space-in-parens` is restricted

The `space-in-parens` should concede to `space-unary-ops` if they exist in

EG: `if ( ! something) ...`

Suggesting an exception something like:

`{ "exceptions": ["!"] }`

or

`{ "exceptions": ["space-unary-ops"] }`

**Comment by platinumazure** [comment]
Hi @ilovett, thanks for the issue.

Could you please provide a specific example (with configuration of both rules, as well as a code sample) which show the issue? As it is, I'm not sure I understand from your report what the problem is. Thanks!
