### ISSUE TITLE
Rule no-magic-numbers doesn't respect statics

### ISSUE THREAD

**Issue by Yserz** [eslint/eslint#10809]
**Tell us about your environment**

* **ESLint Version:** 5.4.0
* **Node Version:** v10.8.0
* **npm Version:** 6.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint 8.2.6

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
env:
  browser: true
  es6: true
  jasmine: true
  node: true

plugins:
  - jasmine
  - prettier
  - react

extends:
  - plugin:jasmine/recommended
  - plugin:react/recommended
  - prettier

parser:
  babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  computed-property-spacing: 2
  constructor-super: 2
  curly: 2
  default-case: 2
  dot-notation: 2
  handle-callback-err: 2
  id-length: 2
  jasmine/new-line-before-expect: 0
  jasmine/no-spec-dupes: [1, branch]
  jasmine/no-suite-dupes: [1, branch]
  no-console: 0
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-inner-declarations: 2
  no-lonely-if: 2
  no-magic-numbers: [2, {ignore: [-1, 0, 1]}]
  no-shadow: 2
  no-unneeded-ternary: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-useless-return: 2
  no-var: 2
  object-shorthand: 2
  one-var: [2, never]
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prefer-spread: 2
  prefer-template: 2
  prettier/prettier: 2
  react/jsx-tag-spacing: [2, {beforeSelfClosing: always}]
  react/prefer-stateless-function: 2
  react/prop-types: 0
  sort-imports: [2]
  sort-keys: [2, asc, {caseSensitive: true, natural: true}]
  sort-vars: 2
  space-infix-ops: 2
  strict: [2, global]
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Adding a static variable for a number triggers the `no-magic-numbers` rule.

```js
class SomeClass extends Component {
  static STATIC_VALUE = 10;
}
```

```bash
eslint -c .eslintrc.yaml --fix
```

**What did you expect to happen?**
The rule `no-magic-numbers` should not be triggered. Instead the static value should be handled as `const` value.

**What actually happened? Please include the actual, raw output from ESLint.**
```
SomeClass.js
  xx:xx  error  No magic number: 10  no-magic-numbers

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

**Comment by kaicataldo** [comment]
Class fields are still experimental syntax and are not supported by ESLint core rules. It doesn't look like a parallel exists in https://github.com/babel/eslint-plugin-babel yet, but that seems like the solution at the moment. We'll be updating the rules in core once this language feature reaches stage 4.

**Comment by Yserz** [comment]
Alright, thanks for the fast response! 👍
