### ISSUE TITLE
Run remote ESLint configurations on CLI like npx does with NPM packages?

### ISSUE THREAD

**Issue by metaa** [eslint/eslint#10804]
Would it be possible (and make sense) to create some logic to allow linting with a configuration found in an npm package that's not installed?

This would be something like [`npx`](https://www.npmjs.com/package/npx) and could look like this:
```console
eslint --use random-eslint-config index.js
```

It would either use the globally installed `random-eslint-config` package or download it like `npx`, lint given files with it and then throw it away afterwards.

With this people could test various configurations and give them a try without having to install them all.

---

If there's something similar I'm missing, though, let me know 😄

**Comment by ilyavolodin** [comment]
I think this is an overkill for a linter. This takes into the realm of dependency management solutions, which, I think, is unnecessary. You can always install the package with NPM and point to it's config file from the CLI.

**Comment by kaicataldo** [comment]
Thanks for the issue. I agree with @ilyavolodin. This would add a ton of overhead (also nervous about security implications). If this is something someone _really_ wanted they could always make some kind of wrapper for ESLint that does this, but I am firmly against adding this to core.

**Comment by metaa** [comment]
Alright guys, thanks for the feedback, really appreciated 😅
