### ISSUE TITLE
camelcase duplicate warning bug

### ISSUE THREAD

**Issue by helixbass** [eslint/eslint#10801]
**Tell us about your environment**

* **ESLint Version:** 5.4.0
* **Node Version:** 8.11.3
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Coffeescript (ran into this while working on [eslint-plugin-coffee](https://github.com/helixbass/eslint-plugin-coffee))

**Please show your full configuration:**

The relevant configuration would be `camelcase: error`. I encountered this while testing the Coffeescript custom parser against the existing ESLint `lib/rules/camelcase.js` rule

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I was running against a copied version of `tests/lib/rules/camelcase.js` where the tested pieces of code were converted to Coffeescript, but these are the corresponding tests in `tests/lib/rules/camelcase.js` that would have been failing:
- `invalid` test `var { category_id } = query;` (where `ignoreDestructuring` is implicitly `false`)
- `invalid` test `function foo({ no_camelcased }) {};` (where `ignoreDestructuring` is implicitly `false`)

**What did you expect to happen?**
For these tests to pass

**What actually happened? Please include the actual, raw output from ESLint.**
They failed due to reporting 2 errors instead of the expected one. I found the bug and will open a fixing PR momentarily

**Comment by ilyavolodin** [comment]
Sounds like a bug. But I can't seem to reproduce it in the online demo: https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgY2FtZWxjYXNlOiBbXCJlcnJvclwiLCB7aWdub3JlRGVzdHJ1Y3R1cmluZzogZmFsc2V9XSovXG5cbnZhciB7IGNhdGVnb3J5X2lkIH0gPSBxdWVyeTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=

**Comment by helixbass** [comment]
@ilyavolodin try:
https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgY2FtZWxjYXNlOiBbXCJlcnJvclwiLCB7aWdub3JlRGVzdHJ1Y3R1cmluZzogZmFsc2V9XSovXG5cbnZhciB7IGNhdGVnb3J5X2lkOiBjYXRlZ29yeV9pZCB9ID0gcXVlcnk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19

With a different parser that doesn't reuse the same `Identifier` object for shorthand `key` and `value`, the demo you shared would also produce duplicate warnings
