### ISSUE TITLE
Add new line between siblings and put each {{}} into separate line

### ISSUE THREAD

**Issue by mkbctrl** [eslint/eslint#10818]
I can see that ESlint is not yet capable of doing the following?

Here is the code linting I like to preserve
```
<div class="car-details-meta d-inline-block">
  <h2 class="font-weight-medium m-b-0 h3">
    {{ deal.final_offer.final_car_model.manufacturer_name }}
    {{ deal.final_offer.final_car_model.name }}
  </h2>

  <h3 class="font-weight-light m-t-0 h5">
    {{ deal.final_offer.final_car_model.name }}
  </h3>
</div>
```

but after linting I end up with:

```
<div class="car-details-meta d-inline-block">
   <h2 class="font-weight-medium m-b-0 h3">{{ deal.final_offer.final_car_model.manufacturer_name }}</h2>
   <h3 class="font-weight-light m-t-0 h5">{{ deal.final_offer.final_car_model.name }}</h3>
</div>
```

Looks like it might be a need for a set of new rules :) The problem to solve is following:

1. move `{{ content }}` to a new line
2. add empty line between sibling HTML tags 

Please correct me if I am wrong and such rules already exists

**Comment by mkbctrl** [comment]
Intersting thing is that it not always work
<img width="664" alt="screen shot 2018-08-30 at 19 34 10" src="https://user-images.githubusercontent.com/10107362/44868759-11de9980-ac8c-11e8-9200-a29dbd37e6c5.png">
in that case the linting were preserved

**Comment by bendtherules** [comment]
Maybe look at package https://github.com/yannickcr/eslint-plugin-react/ and rules:
react/jsx-one-expression-per-line
react/jsx-closing-tag-location

**Comment by mkbctrl** [comment]
@bendtherules do you think it will work with Vue.js?

**Comment by bendtherules** [comment]
Not too sure. Ideally, the rule would just depend on jsx and not anything react specific.
Maybe ask the package maintainers?

**Comment by kaicataldo** [comment]
@mkbctrl We're happy to try to help, but we still don't have enough information to really understand what's going on. If you wouldn't mind following the instructions from the bot, that would be great.
