### ISSUE TITLE
default ignore node_modules inside monorepos

### ISSUE THREAD

**Issue by Janpot** [eslint/eslint#10810]
**The version of ESLint you are using.**

`5.0.0-alpha.2`

**The problem you want to solve.**

I'd like to configure `standard` in the root of my monorepo. By default `eslint` only ignores top level `node_modules`. I see no reason why I'd want to lint _any_ `node_modules` folder by default. The problem can be worked around by providing extra configuration. But most people wouldn't want their inner `node_modules` linted. So I'd like to save those people the hassle of figuring this out and provide it as default.
Relevant issue https://github.com/standard/standard/issues/1182

**Your take on the correct solution to problem.**

I didn't dig through the code yet but I'm assuming there's a default defined for ignoring. I'd like this default changed to `**/node_modules/`

PS.
I don't mind cooking up a PR for this

**Comment by kaicataldo** [comment]
This does seem like a sane default to me, though I'd be hesitant about changing this in a non-major release.

**Comment by Janpot** [comment]
It might be possible that there are people around that structured their monorepo as
```
/node_modules         // packages in here are npm installed
/packages
  /node_modules       // packages in here are user authored
    /package1
      /package.json
    /package2
      /package.json
    /package3
      /package.json
/package.json
```
As to get module resolution between packages in their repo working for free. These would be impacted by a non-major release. I'd argue that this is quite a hacky way to abuse `node_modules` though.

**Comment by sibelius** [comment]
related to these 2 issues
https://github.com/Microsoft/vscode-eslint/issues/503
https://github.com/Microsoft/vscode-eslint/issues/6

and this https://github.com/eslint/eslint/issues/10811

@Janpot do you have a config for .eslintignore that makes this work?

it is failing for me on monorepo as well

**Comment by sibelius** [comment]
it did not work on this monorepo https://github.com/entria/entria-fullstack

**Comment by Janpot** [comment]
@sibelius I only use `eslint` through `semistandard` and following configuration in the top-level package.json works for me
```json
  "semistandard": {
    "ignore": [
      "**/node_modules/**"
    ]
  }
```
Maybe you can dig through the `standard` codebase to find how they pass these optons to `eslint`?

**Comment by kaicataldo** [comment]
@sibelius It doesn't look like there's a .eslintignore file in the top-level root. Is that what you tried?
