### ISSUE TITLE
Indent doesn't work properly inside of template literals

### ISSUE THREAD

**Issue by daviddelusenet** [eslint/eslint#10814]
**Tell us about your environment**

* **ESLint Version: 5.4.0**
* **Node Version: 8.9.3**
* **npm Version: 6.4.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
    es6: true,
  },
  settings: {
    jsx: true,
  },
  plugins: [
    'babel',
    'react',
  ],
  extends: 'airbnb',
  rules: {
    'babel/semi': 1,
    'brace-style': ['error', '1tbs'],
    curly: ['error', 'all'],
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
      peerDependencies: false,
    }],
    indent: ['error', 2, {
      SwitchCase: 1,
    }],
    'jsx-a11y/anchor-is-valid': ['error', {
      components: ['Link'],
      specialLink: ['to'],
    }],
    'keyword-spacing': 0,
    'max-len': ['error', {
      code: 120,
      ignoreTemplateLiterals: true,
      tabWidth: 2,
    }],
    'object-property-newline': ['error', {
      allowAllPropertiesOnSameLine: false,
    }],
    'react/destructuring-assignment': 0,
    'react/jsx-filename-extension': 0,
    'react/jsx-max-props-per-line': ['error', {
      maximum: 3,
    }],
    'react/jsx-sort-default-props': ['error', {
      ignoreCase: false,
    }],
    'react/jsx-sort-props': ['error', {
      callbacksLast: false,
      ignoreCase: false,
      noSortAlphabetically: false,
      reservedFirst: false,
      shorthandFirst: false,
      shorthandLast: false,
    }],
    'react/sort-prop-types': ['error', {
      callbacksLast: false,
      ignoreCase: false,
      requiredFirst: false,
      sortShapeProp: false,
    }],
    'sort-keys': ['warn', 'asc', {
      caseSensitive: true,
      natural: false,
    }],
  },
  globals: {
    Cookiebot: true,
    Modernizr: true,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export default styled.div`
  th, td {
    ${defaultTextStyling({ fontSizes: { root: '12px', xxxlarge: '14px' } })};
    border-bottom: 1px solid ${BLACK};
    text-align: center;
  }
`;
```

```bash
"lint:js": "eslint './src/**/*.js' --config config/.eslintrc.js"
```

**What did you expect to happen?**
I want a setting to make my code to look like this:

```
${defaultTextStyling({
  fontSizes: {
    root: '12px',
    xxxlarge: '14px',
  },
})};
```

Or like this:

```
${defaultTextStyling(
  {
    fontSizes: {
      root: '12px',
      xxxlarge: '14px',
    },
  },
)};
```

**What actually happened? Please include the actual, raw output from ESLint.**

But ESLint wants me to make it look like this:

```
    ${defaultTextStyling({
    fontSizes: {
      root: '12px',
      xxxlarge: '14px',
    },
  })};
```

Which is just plain weird..

**Comment by daviddelusenet** [comment]
Anyone?

**Comment by ilyavolodin** [comment]
Sorry, looks like we lost track of this issue. To the best of my knowledge, indent considers anything inside template literal as a single string, and completely skips any checks inside of it.
Indent code is extremely complicated, and because of that, we rarely touch it. Because this is not a common scenario, chances are, this change request will not be approved. I would suggest creating a stand-alone plugin that would just check for indentation inside template literal.

**Comment by not-an-aardvark** [comment]
> indent considers anything inside template literal as a single string, and completely skips any checks inside of it.

This isn't correct -- the rule does check the indentation of template elements.

This behavior was also discussed in https://github.com/eslint/eslint/pull/7618#issuecomment-262440153, although I forget some of the details of that discussion.

> Because this is not a common scenario, chances are, this change request will not be approved.

I'm not sure how other team members feel about it, but I think it would be reasonable to make a change here if we can figure out a better behavior than the current behavior. Multiline template elements are somewhat common in my experience.

**Comment by ilyavolodin** [comment]
@not-an-aardvark Sorry, I was referring to the indentation inside template literal. Does indent actually checks anything inside template literal? I understand that it will make sure that the template literal itself will be indented correctly in relation to the code around it, but will its content be even checked?

**Comment by not-an-aardvark** [comment]
It doesn't check the "string" contents of the template literal because the indentation spaces there are semantically significant, but it does check the indentation of any nested expressions. For example:

```js
`foo
        bar (this line is not checked)
${
    foo(
        bar,
            baz // this line is checked
    )
}
`
```

**Comment by ilyavolodin** [comment]
Ah, I see. Sorry, didn't realize that was happening.
