### ISSUE TITLE
Why are rules disabled in eslint:recommended?

### ISSUE THREAD

**Issue by danny-andrews** [eslint/eslint#10816]
If you look at https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js, you can see that a whole slew of rules are explicitly disabled. This seems redundant, as the docs state that no rules are enabled by default.

**Comment by ilyavolodin** [comment]
eslint:recommended is a built-in configuration that we provide. It has to be enabled manually, and it only enables some of the rules.

**Comment by not-an-aardvark** [comment]
I think the question in the issue is why it explicitly disables non-recommended rules, rather than providing no configuration for those rules. This could have the effect of overriding another config that enabled the non-recommended rules.

**Comment by danny-andrews** [comment]
@not-an-aardvark This is correct. Thanks for clarifying!

**Comment by platinumazure** [comment]
This is only a problem if someone extends a shareable config or plugin config and then extends eslint:recommended. I assume it's extremely rare in practice, but I also see no reason why eslint:recommended should explicitly change configuration (on/off) of other rules.

That said, to be safe, I think we should regard this as a breaking change and to make this change in a major release.

**Comment by danny-andrews** [comment]
It probably is rare. I encountered it because I wrote a script to determine if there are any core rules that 
I do not have a corresponding rule for. This was leading to surprising results because eslint:recommended defined rules for every core rule.

**Comment by nzakas** [comment]
Background: the default config file is setup that way to use as a template that has every rule in it. I envisioned it as a place where developers could refer if they wanted to see every rule that ESLint had to make it easier to configure.

@platinumazure this issue is still marked as a question, should it be marked as an enhancement?

**Comment by platinumazure** [comment]
@nzakas I'll create an enhancement proposal and then close this issue. Thanks!

Re: place to see ESLint rules: I'm hoping we no longer need to use the eslint:recommended configuration. I think users could get a feeling for all core rules in 2 ways:

1. Non-programmatically: Look at the files in lib/rules or docs/rules (or on the website!)
1. Programmatically: Use the `Linter#getRules` API

Given these options, hopefully we could remove the extra rules from the recommended configuration. (But let's discuss further when I create the enhancement request issue.)

**Comment by danny-andrews** [comment]
@platinumazure Looks good!
