### ISSUE TITLE
Custom parser hook for code path analysis

### ISSUE THREAD

**Issue by helixbass** [eslint/eslint#10823]
**The version of ESLint you are using.**
5.4.0
**The problem you want to solve.**
In working on a custom parser for Coffeescript ([`eslint-plugin-coffee`](https://github.com/helixbass/eslint-plugin-coffee)), I've found the need to modify the code path analysis provided by ESLint's `CodePathAnalyzer` et al in a couple Coffeescript-specific ways (eg `switch` cases implicitly break, `and`/`or`/`?` logical operators, differently structured `for` loops)

Rather than having to monkeypatch ESLint's code path analysis, it'd be preferable to expose an additional custom parser hook (similar to `visitorKeys` or `scopeManager`) to allow customizing code path analysis

**Your take on the correct solution to problem.**
I've opened #10822, which exposes a `CodePathAnalyzer` custom parser hook (which I have successfully working in the Coffeescript custom parser). @not-an-aardvark replied there wondering whether perhaps a more fine-grained API for "extending" the existing code path analysis would be better (rather than having to provide your own completely overriding version of `CodePathAnalyzer`)

My impression (based on the extent to which I've wrapped my head around ESLint's `code-path-analysis/`) is that while providing a more nuanced hook sounds like a nice idea, it'd be an extremely tricky API to design and would presumably add a fair amount more complexity to a section of the ESLint codebase that's already pretty complex

So my instinct is that while @not-an-aardvark is correct that the hook I've proposed involves the custom parser implementer "copy-pasting large portions of ESLint's source code and making patches to it", it's a cleaner approach from the perspective of ESLint itself. I didn't find it that cumbersome to modify and wire up copies of the relevant files from `code-path-analysis/` inside the custom parser implementation

If there's indication that it's worth exploring a more nuanced hook interface though, I could come up with some kind of a diff of what I had to modify for the Coffeescript custom parser's code path analysis as a "case study"

**Comment by ilyavolodin** [comment]
I think it's a good idea to expose `CodePathAnalyzer` from the parser. I'm not sure about the copy&paste approach vs. more complicated API though. To be honest, I don't know CodePathAnalyzer well enough to have an opinion (@mysticatea should probably comment on that issue).
However, from the point of view of ESLint itself, it doesn't really matter to us how passed in Analyzer was created, if it was done by somehow inheriting the code from the default one, or copy & pasting it. As long as it confirms to a specific API, we shouldn't really care. What might be a better solution is to move `CodePathAnalyzer` into it's own packages somehow, and allow for it to be extended.

**Comment by ilyavolodin** [comment]
Fair enough. Do you have a proposal on how to simplify exposed API?

**Comment by helixbass** [comment]
@not-an-aardvark in what sense is the current `CodePathAnalyzer` API "extremely complex"? It seems like it's only expected to handle `enterNode()` and `leaveNode()` (and to forward those calls on to the event generator that it wraps). And to fire the (five?) expected code path event types (`onCodePathStart` etc)

That seems like a pretty clean interface to "expose" (in the sense that the custom parser hook `CodePathAnalyzer` would be expected to satisfy that interface)

Or does your comment pertain to "exposing the `CodePathAnalyzer` API as-is" in the sense of moving it to a separate package (at which point it's "exposed")?

**Comment by not-an-aardvark** [comment]
> in what sense is the current `CodePathAnalyzer` API "extremely complex"?

In addition to the `enterNode` and `leaveNode` methods, an implementation would also be required to:

* Create a `CodePath` interface with the following properties/methods:
    * `id`
    * `upper`
    * `childCodePaths`
    * `initialSegment`
    * `finalSegments`
    * `returnedSegments`
    * `thrownSegments`
    * `currentSegments`
    * `traverseSegments`

...and a `CodePathSegment` interface with the following properties/methods:

    * `id`
    * `nextSegments`
    * `prevSegments`
    * `allNextSegments`
    * `allPrevSegments`
    * `reachable`
    * `isLoopedPrevSegment`

Moreover, all of these methods would need to behave precisely the same way as the built-in methods (except for the parts that are intentionally changed), otherwise users would encounter difficult-to-debug crashes in rules.

> Do you have a proposal on how to simplify exposed API?

I don't have a well-defined proposal, but the very large size of the existing `code-path-analyzer` file in combination with the small size of the desired feature (making a modification to the control flow graph for a particular node type) makes me believe that there must be a smaller API that we could expose to accomplish the same thing.

Off the top of my head, maybe a parser could have a per-node-type hook that gets called before rules access a node, and that has the ability to mutate the control flow graph.

I also think there is room for a much larger refactoring of `code-path-analyzer` to make the implementation simpler and easier to compose with, but that would take awhile and I don't want to unnecessarily block this proposal on it.

**Comment by helixbass** [comment]
@not-an-aardvark ah good point

> I also think there is room for a much larger refactoring of `code-path-analyzer` to make the implementation simpler and easier to compose with, but that would take awhile and I don't want to unnecessarily block this proposal on it

So the monkeypatching version seems to be working, and (at least at this point) it's backwards-compatible with JS (all tests from `tests/fixtures/code-path-analysis/` still pass). I'd be curious if there's insight from the experiences with eg `babel-eslint` what the potential downsides of monkeypatching are, but it seems like if that's not a problematic solution for the time being, it makes it not particularly urgent to get a custom parser hook of some kind exposed (if the sensible path forward as far as exposing an API would be to do some real thinking and possible refactoring of the code path analysis code)

If it's helpful as anyone would start to consider the needs of the API, [this](https://github.com/helixbass/eslint-plugin-coffee/compare/dac8acd...master#diff-fff41ae69b03eb3a8e09140b6c5f8cf6) should be the relevant diff (in Coffeescript) of what I had to modify compared to the original ESLint version (that link doesn't seem to take you straight to the specific file diff, the relevant file diffs are `src/code-path-analysis/code-path-analyzer.coffee` and `src/code-path-analysis/code-path-state.coffee`)
