### ISSUE TITLE
'prefer-const' not recognizing 'delete' on objects

### ISSUE THREAD

**Issue by armaanahluwalia** [eslint/eslint#10844]
Consider the following code
```
const state = {
  foo: "bar"
};
let newState = {
	...state,
};
delete newState["foo"];
```
prefer-const is throwing the error 
```
'newState' is never reassigned. Use 'const' instead. (prefer-const)
```

See [here](https://eslint.org/demo/#eyJ0ZXh0IjoiY29uc3Qgc3RhdGUgPSB7XG4gIGZvbzogXCJiYXJcIlxufTtcbmxldCBuZXdTdGF0ZSA9IHtcblx0Li4uc3RhdGUsXG59O1xuZGVsZXRlIG5ld1N0YXRlW1wiZm9vXCJdOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJleHBlcmltZW50YWxPYmplY3RSZXN0U3ByZWFkIjp0cnVlfX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6MiwicHJlZmVyLWNvbnN0IjoyfSwiZW52Ijp7fX19) for a live example.

**Tell us about your environment**

* **ESLint Version:**
v5.5.0
**What parser (default, Babel-ESLint, etc.) are you using?**
ESLint
**Please show your full configuration:**
See link

**What did you expect to happen?**
prefer-const not to throw an error since the object is being modified.

**Comment by platinumazure** [comment]
As I said, `prefer-const` just follows the rules of the language.

There are probably some good ESLint plugins you could use for immutability enforcement. I suggest searching npm for eslint-plugin and immutable, and you might find some plugins that you could use.

**Comment by armaanahluwalia** [comment]
Totally understood. Thanks for your time.

**Comment by platinumazure** [comment]
Closing since the question has been answered, but please feel free to add any follow-up questions here if needed. Thanks!
