### ISSUE TITLE
allow ternary in valid-v-model

### ISSUE THREAD

**Issue by FunnyB0y** [eslint/eslint#10845]
**The version of ESLint you are using.**
eslint 5.5
eslint-plugin-vue@5.0.0-beta.3
**The problem you want to solve.**
A red line is shown for this 
`v-model="same_title ? data.name : data.display_name"`
**Your take on the correct solution to problem.**
Remove error/warn line

**Comment by g-plane** [comment]
This problem is from https://github.com/vuejs/eslint-plugin-vue , not ESLint itself.
