### ISSUE TITLE
`context.report()` signature improvments

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#1087]
When creating report from rules, it would be convenient:

1. make `node` param not mandatory, if location present. In fact, currently some rules pass 'Progmam' node to fill gap, and that's absulutely useless.
2. allow to pass location in numeric format (offset from file start).

That will simplify code in non-ast-based rules.

**Comment by platinumazure** [comment]
@nzakas Wondering if this issue needs more discussion and/or closing? Autofix introduced a new API for `context.report` to make it object-based (though the positional syntax is still supported).

**Comment by nzakas** [comment]
You're right! Totally forgot about this one. New syntax is implemented.
