### ISSUE TITLE
Remove non-recommended rules from recommended config

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#10873]
**The version of ESLint you are using.**

5.6.0/master

**The problem you want to solve.**

The `eslint:recommended` config contains all ESLint rules. Non-recommended rules are explicitly set to "off", while recommended rules are set to "error".

This impacts users who might wish to extend eslint:recommended after having already extended a different configuration. The rules configured as "off" will override any rules configured as "warn" or "error" in the extended configuration.

In practice, this is pretty rare. However, it also seems that eslint:recommended should not explicitly turn off other rules.

Inspired by #10816.

**Your take on the correct solution to problem.**

Remove the "off" rules from eslint:recommended. This is technically a breaking change, so we should do this within a major release.

**Comment by platinumazure** [comment]
In https://github.com/eslint/eslint/issues/10816#issuecomment-422853644, it was noted that the recommended config was originally set up as a template where all of the core rules could be listed.

Rule discoverability has greatly improved since then:

* The website lists all the core rules and is very searchable
* In a local repo clone, one could look at lib/rules or docs/rules and see all the core rules there
* In a Node API context, one could use CLIEngine#getRules or Linter#getRules to get all core rules (if no plugins are loaded)

So I'm hoping that we no longer need to use the eslint:recommended config as a template for seeing all the core rules.

**Comment by not-an-aardvark** [comment]
I'm willing to champion this issue for the next major release.

**Comment by platinumazure** [comment]
**TSC Summary**:

The `eslint:recommended` config contains all ESLint rules. Non-recommended rules are explicitly set to "off", while recommended rules are set to "error".

This impacts users who might wish to extend eslint:recommended after having already extended a different configuration. The rules configured as "off" will override any rules configured as "warn" or "error" in the extended configuration.

In practice, this is pretty rare. However, it also seems that eslint:recommended should not explicitly turn off other rules.

**TSC Question**:

Should we remove non-recommended rules from the eslint:recommended config in the next major release?

**Comment by btmills** [comment]
This has been accepted for the next major release!

**Comment by platinumazure** [comment]
Working on this.
