### ISSUE TITLE
Rule: Space after line comments

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#1088]
- name: __line-comments-spaces__
- params: \[0, "always"|"never"] ("always" by default)

good:

```javascript
var foo; // abc
var bar; /* a */

var foo(a/* height */) {
}
```

bad:

```javascript
var foo; //abc
var bar; /*a*/

var foo(a/*height*/) {
}
```

Don't know if inverse option needed or not.

**Comment by lo1tuma** [comment]
The rule `spaced-line-comment` can already do this for single line comments.

**Comment by nzakas** [comment]
Should we change to `spaced-comment`?

**Comment by gyandeeps** [comment]
Since `spaced-line-comment` rule already does this for line comments, we can (as per comments above) actually name the rule `spaced-comment` and deprecate `spaced-line-comment` rule.
Do we agree on this?

**Comment by nzakas** [comment]
:+1: we should do this for 1.0

**Comment by gyandeeps** [comment]
Working on this. Will have it ready by this weekend.
