### ISSUE TITLE
Why was this closed? https://github.com/eslint/eslint/issues/9848

### ISSUE THREAD

**Issue by myyellowshoe** [eslint/eslint#10901]
Apologize as this a little out of the ordinary, as it should probably be a comment under the original issue, but its now locked. 

Why was this issue closed when this is still an issue? Little confused. Having issues with this bug currently.
https://github.com/eslint/eslint/issues/9848

Thanks guys!

**Comment by myyellowshoe** [comment]
Ahh gotcha, just wanted to make sure.
 Happy to open a bug report on this 👍

**Comment by nzakas** [comment]
Closing because the question was answered.
