### ISSUE TITLE
eol-last change: ignore embedded environments

### ISSUE THREAD

**Issue by faiwer** [eslint/eslint#10914]
**What rule do you want to change?**

This one: `eol-last`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

Maybe add an extra parameter? Or just ignore embedded JS environments?

**Please provide some example code that this change will affect:**

e.g. `.vue`-files (for vue.js) or any other where JS can be embedded.
```html
<!-- rule's value is "never" -->

<!-- with error -->
<script>
some js-code
</script>

<!-- without error, but ugly -->
<script>
some js-code</script>
```

**What does the rule currently do for this code?**

It throws an error about excessing \n at the end of the `<template/>`-body (opt "never" is set).

**What will the rule do after it's changed?**

e.g. it'll ignore injected JS environments due to they have its close-tags and they aren't real files.

I'm not sure that there is not any better idea, searches led me to issues where people use one of next:
- `eslint-disable` in each `.vue` file
- disable this rule at all
- use intricate system of several eslintrc files for different types of file extensions.

I think that this rule is a great tool, but only for real files, not for embedded parts.

**Comment by nzakas** [comment]
I agree that this behavior is unexpected. Unfortunately, ESLint is designed in such a way that the linter doesn't distinguish between JavaScript embedded within a file (like in `.vue`) and a standalone JavaScript file, and I don't think that's going to change.

It's probably best to disable the rule, but let's see if other team members have a different opinion.
