### ISSUE TITLE
Global assignment not counting as a usage for no-unused-vars rule

### ISSUE THREAD

**Issue by cameron-martin** [eslint/eslint#10921]
**Tell us about your environment**

* **ESLint Version:** 5.5.0
* **Node Version:** v8.11.3
* **npm Version:** yarn 1.7.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "extends": ["eslint:recommended", "plugin:react/recommended", "prettier"],
  "rules": {
    "react/prop-types": "off"
  },
  "env": {
    "browser": true,
    "jquery": true,
    "es6": true
  },
  "globals": {
    "dataLayer": true
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* globals __webpack_public_path__:true */

__webpack_public_path__ = 'SOME_PUBLIC_PATH';
```

```bash
eslint src
```

**What did you expect to happen?**
No errors in the above file.

**What actually happened? Please include the actual, raw output from ESLint.**
I get the error:

    1:12  error  '__webpack_public_path__' is defined but never used  no-unused-vars

**Comment by platinumazure** [comment]
Hi @cameron-martin, thanks for the issue.

[As noted in the docs](https://eslint.org/docs/rules/no-unused-vars#exported), ESLint needs to be informed that a variable is intended to be exported globally. Simply add a comment like this somewhere in your file:

```js
/* exported __webpack_public_path__ */
```

And the rule should stop complaining. (Note that this only works in non-CommonJS, non-ES6 Module environments. If you're in one of those environments, you should export using `module.exports` or an `export` declaration.)

**Comment by cameron-martin** [comment]
Thanks. That does work. However, [according to the docs](https://eslint.org/docs/rules/no-unused-vars#exported) it shouldn't:

> Note that /* exported */ has no effect for any of the following:
> * when `parserOptions.sourceType` is `module`

Although I do not have `parserOptions.sourceType` set, [the default for `babel-eslint` is `module`](https://github.com/babel/babel-eslint#configuration)

**Comment by platinumazure** [comment]
@cameron-martin ESLint is reading from the config, not interrogating the parser to see what the "effective" sourceType is.

I agree that `// eslint-disable-next-line` is probably the right approach here. ESLint can't cover every corner case.

**Comment by cameron-martin** [comment]
Gotcha. In that case I'm closing this. Thanks for your help!
