### ISSUE TITLE
Array.concat used in nested forEach loop causes 'no-loop-function' error

### ISSUE THREAD

**Issue by mymmoonoa** [eslint/eslint#10961]
Hi guys I test ESLint with following code on [ESLint.org official site](https://eslint.org/demo/#eyJ0ZXh0IjoiLy8gd2h5IHRoaXMgaXMgbm90IG9rXG5mdW5jdGlvbiBhKCkge1xuICAgIGxldCBhYiA9IFtdO1xuICAgIGNvbnN0IGNkID0gW1sxXSwgWzJdLCBbM11dO1xuICAgIGZvciAobGV0IGkgPSAwOyBpIDwgMTA7IGkrKykge1xuICAgICAgICBhYiA9IGFiLmNvbmNhdChjZCk7XG4gICAgICAgIGNkLmZvckVhY2goKHN0aCkgPT4ge1xuICAgICAgICAgICAgYWIgPSBhYi5jb25jYXQoc3RoKTtcbiAgICAgICAgfSk7XG4gICAgfVxuICAgIHJldHVybiBhYjtcbn1cbi8vIHRoaXMgaXMgT0tcbmZ1bmN0aW9uIGIoKSB7XG4gICAgbGV0IGFiID0gW107XG4gICAgY29uc3QgY2QgPSBbWzFdLCBbMl0sIFszXV07XG4gICAgLy8gZm9yIChsZXQgaSA9IDA7IGkgPCAxMDsgaSsrKSB7XG4gICAgYWIgPSBhYi5jb25jYXQoY2QpO1xuICAgIGNkLmZvckVhY2goKHN0aCkgPT4ge1xuICAgICAgICBhYiA9IGFiLmNvbmNhdChzdGgpO1xuICAgIH0pO1xuICAgIC8vIH1cbiAgICByZXR1cm4gYWI7XG59XG5hKCk7XG5iKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8tbG9vcC1mdW5jIjoyfSwiZW52Ijp7Im5vZGUiOnRydWV9fX0=) <--- **click here to check!!!**
I can't figure out why I got the 'no-loop-func' error, Any help? Thx.
```
// why this is not ok
function a() {
    let ab = [];
    const cd = [[1], [2], [3]];
    for (let i = 0; i < 10; i++) {
        ab = ab.concat(cd);
        cd.forEach((sth) => {
            ab = ab.concat(sth);
        });
    }
    return ab;
}
// this is OK
function b() {
    let ab = [];
    const cd = [[1], [2], [3]];
    // for (let i = 0; i < 10; i++) {
    ab = ab.concat(cd);
    cd.forEach((sth) => {
        ab = ab.concat(sth);
    });
    // }
    return ab;
}
a();
b();
```
config:
- ESLint v5.6.1
- ES2017
- Rules enables 'no-loop-function''

**Comment by mymmoonoa** [comment]
[add more test code](https://eslint.org/demo/#eyJ0ZXh0IjoiLy8gd2h5IHRoaXMgaXMgbm90IG9rXG5mdW5jdGlvbiBhKCkge1xuICAgIGxldCBhYiA9IFtdO1xuICAgIGNvbnN0IGNkID0gW1sxXSwgWzJdLCBbM11dO1xuICAgIGZvciAobGV0IGkgPSAwOyBpIDwgMTA7IGkrKykge1xuICAgICAgICBhYiA9IGFiLmNvbmNhdChjZCk7XG4gICAgICAgIGNkLmZvckVhY2goKHN0aCkgPT4ge1xuICAgICAgICAgICAgYWIgPSBhYi5jb25jYXQoc3RoKTtcbiAgICAgICAgfSk7XG4gICAgfVxuICAgIHJldHVybiBhYjtcbn1cbi8vIHRoaXMgaXMgT0tcbmZ1bmN0aW9uIGIoKSB7XG4gICAgbGV0IGFiID0gW107XG4gICAgY29uc3QgY2QgPSBbWzFdLCBbMl0sIFszXV07XG4gICAgLy8gZm9yIChsZXQgaSA9IDA7IGkgPCAxMDsgaSsrKSB7XG4gICAgYWIgPSBhYi5jb25jYXQoY2QpO1xuICAgIGNkLmZvckVhY2goKHN0aCkgPT4ge1xuICAgICAgICBhYiA9IGFiLmNvbmNhdChzdGgpO1xuICAgIH0pO1xuICAgIC8vIH1cbiAgICByZXR1cm4gYWI7XG59XG4vLyB0aGlzIGlzIE9LXG5mdW5jdGlvbiBjKCkge1xuICAgIGxldCBhYiA9IFtdO1xuICAgIGNvbnN0IGNkID0gW1sxXSwgWzJdLCBbM11dO1xuICAgIC8vIGZvciAobGV0IGkgPSAwOyBpIDwgMTA7IGkrKykge1xuICAgIGFiID0gYWIuY29uY2F0KGNkKTtcbiAgICBjZC5mb3JFYWNoKCgpID0+IHtcbiAgICAgICAgLy8gZG8gbm90aGluZ1xuICAgIH0pO1xuICAgIC8vIH1cbiAgICByZXR1cm4gYWI7XG59XG5hKCk7XG5iKCk7XG5jKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8tbG9vcC1mdW5jIjoyfSwiZW52Ijp7Im5vZGUiOnRydWV9fX0=)

**Comment by platinumazure** [comment]
Hi @mymmoonoa, thanks for the issue.

The `no-loop-func` rule is warning in your case because you're writing to a variable defined outside of the loop (in this case, `ab`) from within your inner function. JavaScript does weird things with variable reassignments when a function is defined inside a loop. (The reasoning is well-defined, but I confess I don't know how to explain it very well. It has to do with how functions close around a variable *reference*, rather than variable *values*, but I can't explain it beyond that.)

You can work around this by defining the function outside the loop:

```js
function a() {
    let ab = [];

    // Note: This function is outside the loop
    const doConcat = (sth) => {
        ab = ab.concat(sth);
    };

    const cd = [[1], [2], [3]];
    for (let i = 0; i < 10; i++) {
        ab = ab.concat(cd);
        cd.forEach(doConcat);
    }
    return ab;
}
```

Hope this helps!

**Comment by platinumazure** [comment]
Closing as the question has been answered. Please feel free to stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you have any other questions.

**Comment by mymmoonoa** [comment]
Thanks @platinumazure,  your code works fine. 
Still the lint error looks a little wired for it makes me feel like the assignment ```ab = ab.concat(sth)``` turns out be making a implicit function declaration.
