### ISSUE TITLE
"no-undef" doesn't work with variable-name "context"

### ISSUE THREAD

**Issue by mrx8** [eslint/eslint#10984]
**Tell us about your environment**

* **ESLint Version:**
5.7.0
* **Node Version:**
8.12.0
* **npm Version:**
6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "rules": {
        "no-undef": "error"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
console.log(context);
```

```bash
eslint
```

**What did you expect to happen?**
context marked as error "no-undef"

**What actually happened? Please include the actual, raw output from ESLint.**
context is not marked as error "no-undef"

**Comment by mrx8** [comment]
Ah, you are right, I meant "no-undef", sorry for this!
Use for example "context2" and it is marked as error. So it seems that the name "context" is some sort of "reserved value" for eslint which it whitelists.

**Comment by platinumazure** [comment]
@mrx8 `context` may be a global in some environment, so `no-undef` would not treat it as undefined in that case.

Please share the results of running ESLint with the `--print-config` option on the file in question, and it will hopefully show what environments and/or globals have been configured (not visible in the config you provided in the initial post of this issue).

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back for quite some time and it looks as though this question has been answered. Feel free to create a new issue if this is something you would like to discuss further.
