### ISSUE TITLE
Extend no-multi-spaces with allow alignment option

### ISSUE THREAD

**Issue by qbob** [eslint/eslint#11002]
Is it possible to have a rule to allow alignment of = (which introduces multi spaces) without having to turn off no-multi-spaces?

The following would be considered a warning:

```
var a   = 1;

var a    = 1;
var bar = 1;
```

The following would not:

```
var a   = 1;
var bar = 1;
```
Currently no-multi-space complains about what ESLint calls good coding conventions:

```
// Good
var count   = 10,
    name    = "Nicholas",
    found   = false,
    empty;
```

I agree that this is good, but turning off no-multi-spaces completely is a blunt instrument that would hide warnings you want.

**Comment by kaicataldo** [comment]
Have you tried the [`exceptions`](https://eslint.org/docs/rules/no-multi-spaces#exceptions) configuration option? It sounds like you want to use `"exceptions": { "VariableDeclarator": true }` in your config.
