### ISSUE TITLE
Add verbose level cli option for output

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#1101]
related to #1098.

When verbose mode on - show each linted file name even if it has no messages. That will help to understand perfomance/integrity problems, when you setup eslint on new big project:

- mistake in .eslintignore can cause unnesessary traverses
- mistake in .eslintignore can disable evertyhing

This option yallow to check what eslint really does when it finish with no errors.

**Comment by JohnAlbin** [comment]
+1

The docs for minimatch are pretty parse. And the intersection between eslint's traverse() and minimatch are non-obvious IMO.

```
# .eslintignore
path1/*
# the next line won't work because traverse() will never reach this level.
!path1/sub/sub/dont-ignore/*
```

I just spent way too many hours trying to figure out why it wouldn't work and then how to work around it.

A simple `--verbose` would have been super handy.
```
> eslint --verbose .
Ignoring path1/file1.js
Processing path2/file2.js
```

**Comment by nzakas** [comment]
You can already kind of do this:

```js
$ DEBUG=eslint:* eslint .
```

Just have to figure out what subset of messages would be appropriate for this.

**Comment by ralphholzmann** [comment]
Wanted to +1 this.

Just went through the process of creating a mono-repo at our company (taking three independent web repos and putting them in the same parent repo). We spent the time to set up common cascading `.eslintrc`s, as well as merging together our `.eslintignore`s. It would have been great to have a `--verbose` option just to sanity check that all of the files that were being linted when we had 3 separate repos are still being linted now that we're in a single repo.

Something as simple as
```/path/to/file: No errors or warnings```
for each file it lints would suffice.

**Comment by fastotter** [comment]
+1 on ralphholzmann comment above

I was struggling with setting up eslint for the first time, to be sure I was linting all the files I wanted I did the same thing, broke rules in files.

**Comment by IanVS** [comment]
@ralphholzmann and @fastotter, this is an [accepted enhancement](http://eslint.org/docs/developer-guide/contributing/working-on-issues#issue-labels), which means it is pretty low on the priority list for the core team but anyone is welcome to submit a PR.

**Comment by darrenmce** [comment]
have been using `DEBUG=eslint:*` but noticed that in v1.5 a `--debug` flag was added to the cli that does just this

**Comment by IanVS** [comment]
@darrenmce As noted in https://github.com/eslint/eslint/issues/1101#issuecomment-54732556, `--debug` (which now exists), is not the same as `--verbose` (which is what this issue is for).

**Comment by darrenmce** [comment]
@IanVS ah yes, your right. I was off-focus since this issue was the issue that actually helped me solve my `--debug` need (prior to the new flag).

**Comment by afahim** [comment]
I'll take a stab at this during the weekend.

**Comment by kaicataldo** [comment]
Hey @afahim, are you still working on this?

**Comment by afahim** [comment]
@kaicataldo taking another look today. If I can't get it done, its all yours / whoever wants to take it!

**Comment by kaicataldo** [comment]
@afahim Thanks for the update :)

**Comment by nzakas** [comment]
This has been open for over two years and no updates in five months, it looks like there's just not enough interest to pursue this.

**Comment by kirkstrobeck** [comment]
Use 

```
DEBUG=eslint:cli-engine eslint .
```

**Comment by jcrben** [comment]
Seems like `--debug` is a good option here. Somehow `DEBUG=eslint:cli-engine eslint .` didn't do much for me running node 6.10.1 on Mac 10.11.5.
