### ISSUE TITLE
`allowStart/End` option for `prefer-template` rule

### ISSUE THREAD

**Issue by Alhadis** [eslint/eslint#11034]
**What rule do you want to change?**
[`prefer-template`](https://eslint.org/docs/rules/prefer-template)

**Does this change cause the rule to produce more or fewer warnings?**
Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option. Default configuration looking something like this:

~~~js
"prefer-template": [
	"error",
	{
		"allowStart": false,
		"allowEnd": false
	}
]
~~~

**Please provide some example code that this change will affect:**

`{"allowStart": true}`
~~~js
// Valid
var foo = foo + "\n";
var bar = bar() + "\n";

// Invalid: "allowEnd" is `false`
var foo = "\n" + foo;
var bar = "\n" + bar();

// Invalid: Variable component(s) surrounded by concatenation
var foo = "\n" + foo "\n";
var bar = "\n" + bar() + "\n";
~~~

**What does the rule currently do for this code?**
Flags very simple string concatenation as an error.

**What will the rule do after it's changed?**
Allow authors to enforce template literals only when they're really needed.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by nzakas** [comment]
Thanks for the issue. Can you explain exactly what "allowStart" and "allowEnd" are intended to do? It's not clear from your description.

**Comment by Alhadis** [comment]
Sorry. Should've clarified, or at least chosen less vague names for the proposed settings.

`allowStart` allows concatenation if the first operand isn't a string literal, such as:

~~~js
someVariable + "string";
~~~

Conversely, `allowEnd` allows concatenation if the last operand isn't a string literal:

~~~js
"string" + someVariable;
~~~

Does that make sense?

**Comment by Alhadis** [comment]
I should also stress the reasoning behind this option is to eliminate cluttered-looking string literals which are cleaner to express with concatenation:

~~~js
`${foo}\n`;
~~~

I find this clearer to read:

~~~js
foo + "\n";
~~~

Template literals only feel cleaner and more logical if there's concatenation both before and after an expression:

~~~js
`\n${foo}\n`
"\n" + foo + "\n"
~~~

This is purely subjective, of course, but my motive for enforcing `prefer-template` was to eliminate messy constructions like this:

~~~js
"^(" + words.join("|") + ")$|(?=" + moreWords.join("|") + ")"
~~~

I have `prefer-template` in my [shareable ESLint config](https://github.com/Alhadis/Coding-Style/blob/1b34d07fb933d94d8ca7ceb90971057fb9504968/eslint/.eslintrc.json), but I'm finding myself overriding it in projects which use it, as most of the "errors" are forgivably minor concatenations like the first example I posted...

**Comment by nzakas** [comment]
Thanks for clarifying.

To me, this seems like a change that wouldn't benefit a large portion of our users, so I'd be inclined to suggest you create your own rule (possibly using [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer)) to add in the exceptions you're looking for.

**Comment by Alhadis** [comment]
I guess I'll just abolish the rule then. Had no idea how to visualise "first node", "second node", what nodes were available for perusal during captured frames...

Thanks anyway. =)
