### ISSUE TITLE
Check object literals as part of no-useless-rename

### ISSUE THREAD

**Issue by paulmelnikow** [eslint/eslint#11041]
**What rule do you want to change?**

[no-useless-rename](https://eslint.org/docs/rules/no-useless-rename)

**Does this change cause the rule to produce more or fewer warnings?**

More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option + new default behavior

**Please provide some example code that this change will affect:**

```js
const a = 123
const b = {a: a}
```

**What does the rule currently do for this code?**

No warning is generated for this code.

**What will the rule do after it's changed?**

```
  2:12  error  Object literal a unnecessarily renamed  no-useless-rename

✖ 1 problem (1 error, 0 warnings)
```

When `ignoreLiteral` is true, the warning will be suppressed (same as current behavior).

**Are you willing to submit a pull request to implement this change?**

If no one else feels inclined!

**Comment by not-an-aardvark** [comment]
Hi, thanks for the proposal.

I'm a bit confused because I'm not sure I understand the problem with the code above. How would the rule recommend writing it instead?

Also, does the [`object-shorthand`](https://eslint.org/docs/rules/object-shorthand) rule already cover this case?

**Comment by platinumazure** [comment]
Is this covered by `object-shorthand`? I'm confused, maybe I'm missing something.

**Comment by paulmelnikow** [comment]
Ah! So it is. Maybe I can add a cross-reference in the documentation. Thanks!

**Comment by platinumazure** [comment]
A documentation PR to add cross-reference(s) would be wonderful, thanks!
