### ISSUE TITLE
no-alert and others

### ISSUE THREAD

**Issue by kof** [eslint/eslint#1105]
They should be smart enough to recognize that I am not calling window.alert. I have a component named alert and its declared like this ` var alert = require('components/notification/alert')`

**Comment by rlidwka** [comment]
> Shadowing 'alert' means that if you copy-and-paste any of the code, or otherwise exit the shadowed scope, you suddenly have a wild alert statement in your code.

Is there a way to explicitly turn off global `alert`, so `no-undef` rule will treat it as undefined variable?

Because this is much better solution than tracking where `alert` variable is coming from. `no-undef` rule already does that.

**Comment by nzakas** [comment]
You'd need to disable the browser environment to do that. There's no way to undefine a global one it's been defined.
