### ISSUE TITLE
comma dangle: shouldn't show error in arrow function

### ISSUE THREAD

**Issue by videni** [eslint/eslint#11057]
![image](https://user-images.githubusercontent.com/4058341/48055073-b1b72700-e1e9-11e8-8bcc-2644dd8d8e11.png)

**Comment by mysticatea** [comment]
Thank you for the report.

But this is not a bug.

The arrow function is the first argument of the call of `addAuthorizationHeader`.
The rule is configured to require the trailing comma of arguments.

**Comment by videni** [comment]
@mysticatea, I seem, thanks
