### ISSUE TITLE
JUnit reporter XML output missing required classname attribute on testcase element

### ISSUE THREAD

**Issue by micheee** [eslint/eslint#11068]
When producing JUnit XML output, the resulting XML file seems to be missing required attributes.

I found the following [XML Schema Definition](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) that indicates the required fields.

While I don't think it is necessary to support every optional attribute, I think it would make sense to provide those that are mandatory.

I stumbled across this, as I tried to integrate ESlint output in GitLab CI, but GitLab CI will not display the report, as it requires the classname attribute to be present. 

There is also an issue filed [over at GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/50964), but maybe it was more obvious to fix the issue in ESlint.

If you think here’s the right place to fix this, I'd be happy to contribute a Pull Request.

**Tell us about your environment**

* **ESLint Version:** v5.8.0
* **Node Version:** v10.12.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** ø

<details>
<summary>Configuration</summary>

```js
#  cat eslintconfig.json
{
  "plugins": [],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "extends": ["eslint:recommended"]
}
```

```js
#  cat test.js
console.log('foo');
```

**What did you expect to happen?**

Expected the attribute `classname` to be present on element `<testcase />` — I suggest that classname will be set to `basename` of the parents `<testsuite/>` `file` attribute.

```xml
<testsuites>
<testsuite package="org.eslint" time="0" tests="1" errors="1" name="/path/to/test.js">
  <testcase time="0" classname="test" name="org.eslint.no-console">…</testcase>
</testsuite>
</testsuites>
```

**What actually happened? Please include the actual, raw output from ESLint.**

```xml
<!-- ⇒  ./node_modules/.bin/eslint -c eslintconfig.json -f junit test.js -->
<testsuites>
<testsuite package="org.eslint" time="0" tests="1" errors="1" name="/path/to/test.js">
  <testcase time="0" name="org.eslint.no-console">… </testcase>
</testsuite>
</testsuites>
```

**Are you willing to submit a pull request to fix this bug?**

👍

**Comment by platinumazure** [comment]
Hi @micheee, thanks for the issue.

I agree this seems like a bug, but I'm not sure what value we should put in there. Do you have any thoughts?

**Comment by not-an-aardvark** [comment]
How about an empty string?

**Comment by evanlucas** [comment]
We ran into this also. To me, the filename would be useful

**Comment by dosuken123** [comment]
Some example of how other test tools fill `classname`

- PHPUnit: https://gitlab.com/gitlab-org/gitlab-ce/issues/50426#note_98295197
- rspec: https://gitlab.com/snippets/1731728
- Basic: https://gitlab.com/gitlab-org/gitlab-ce/issues/50426#note_98162786
- NUnit: https://gitlab.com/gitlab-org/gitlab-ce/issues/50426#note_96631485
- Karma: https://gitlab.com/gitlab-org/gitlab-ce/issues/50426#note_96400871

**Comment by micheee** [comment]
> We ran into this also. To me, the filename would be useful
 
The Filename — maybe without the extension — would be my proposal as well.

Any other thoughts?

**Comment by platinumazure** [comment]
Thanks everyone for your suggestions!

Re: filename: It looks like the filename is captured in the `name` attribute of the `<testsuite>` element. Would adding the file name as a "classname" (which seems to expect a Java class) really be useful?

And I guess I'm a bit skeptical about looking at other test runners for examples. Not sure if those are really apples-to-apples comparisons.

If empty string will work (i.e., if the attribute being "required" in the XSD means the attribute just needs to be present, but it doesn't have to have a non-empty value), I could get behind that. I could also support a value like "Linter", since that's the name of our (ES6) class that is doing the linting.

@micheee Can you test out whether `classname=""` will work in GitLab CI? Thanks!

**Comment by micheee** [comment]
@platinumazure 

> @micheee Can you test out whether classname="" will work in GitLab CI? Thanks!

Sorry I've been in the mountains for the weekend — I will check this out today an report back.

**Comment by micheee** [comment]
Long story short:

Setting classname to empty string would be valid, but won't help GitLab as it uses `classname` + `name` as its grouping key when displaying the errors.

So I'd propose to change the value of classname to the name attribute of its parent testsuite element, ore more profane: the full path to the file under consideration. 


My example report contains 18 errors of the category `org.eslint.no-extra-boolean-cast` and 1 error of category `org.eslint.no-unused-var` however only 2 total failures are reported in the UI:

![image](https://user-images.githubusercontent.com/422242/48409041-21259d00-e73b-11e8-8eb6-9b5d59e6b20f.png)


--- 

If I however change the classname to the file path (I'd vote for that because filenames like index.js are very likely to show up more than once in any given codebase) the results are shown mostly correct in the UI — multiple errors of the same category per File will only show up once — but I don't think that's something eslint should tackle.

![image](https://user-images.githubusercontent.com/422242/48408549-e1aa8100-e739-11e8-95e2-987f625ad49d.png)

---

Feedback appreciated.

**Comment by cbleslie** [comment]
> mostly correct in the UI — multiple errors of the same category per File will only show up once — 

90% of something, is better than 0% of nothing, hombré. I'll take what I can get!

**Comment by micheee** [comment]
What do you think, I could send a PR containing the required change?

**Comment by platinumazure** [comment]
@micheee What value would you want to use? I don't think we came to consensus on that, did I miss something?

**Comment by micheee** [comment]
@platinumazure Sorry, I did not want to rush things.
The empty string turned out to be not too useful in terms of GitLab’s CI Panel (though valid w.r.t. to the schema).

I am locally playing around with using the filepath, but trimmed relative to the project root and without the filename suffix to have a things a little more readable for humans.

Currently it I imagine something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite package="org.eslint" time="0" tests="1" errors="0" name="/Users/michael/Code/foo/foo-dev/src/frontend/controllers/PageController.js">
    <testcase time="0" name="org.eslint.no-console" classname="src/frontend/controllers/PageController">
      <failure message="Unexpected console statement."><![CDATA[line 41, col 9, Error - Unexpected console statement. (no-console)]]></failure>
    </testcase>
  </testsuite>
</testsuites>

```

Still this decision is kind of arbitrary as obviously the reporting format was invented for Java.

**Comment by iMarv** [comment]
If I am not mistaken by the JUnit schema, `package` should be a property of `testsuites` rather than `testsuite`
