### ISSUE TITLE
Upgrade MockFS for Node.js 11 support

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#11104]
**The problem you want to solve.**

A lot of our tests use [`mock-fs`](https://npmjs.com/package/mock-fs) for mocking out the file system (specifically in `linter.js`). We recently started testing ESLint on Node 11, and `mock-fs` doesn't currently work in Node 11, and [likely never will](https://github.com/tschaub/mock-fs/issues/254#issuecomment-425573723).

**Your take on the correct solution to problem.**

In the short term, it might be best to stop testing in Node 11 to unblock incoming PRs. In the long-term, we probably need to either refactor the tests not to use `mock-fs` and/or find another module to replace it.

**Are you willing to submit a pull request to implement this change?**

Of course.

**Comment by not-an-aardvark** [comment]
FYI, incoming PRs have been unblocked by https://github.com/eslint/eslint/commit/709190f8c5d7559b1e0915e25af60b50a94ba1c7, so the build is currently passing on Node 11. I think it would be better to continue running tests on Node 11 if possible, but I agree that we should probably switch away from `mock-fs` in the long term.

**Comment by nzakas** [comment]
I think this actually breaks the test now, because the Mock file system isn't being set and therefore isn't being tested at all.

**Comment by not-an-aardvark** [comment]
It now tests the real filesystem, but since there (usually) isn't a `package.json` file in the root directory, it is still accurately testing the case where a given file doesn't exist.

**Comment by nzakas** [comment]
Hmm, that seems like a fragile solution to me, especially since a lot of the surrounding tests are using `mock-fs` for this purpose. I'll add a comment in that spot to at least ensure we remember what's going on in that.

**Comment by not-an-aardvark** [comment]
Agreed, it's not ideal. I was going for a quick solution that would prevent the build from breaking for now.

**Comment by nzakas** [comment]
Reopening as we still need to investigate this.

**Comment by ilyavolodin** [comment]
> It now tests the real filesystem, but since there (usually) isn't a package.json file in the root directory, it is still accurately testing the case where a given file doesn't exist.
This is the reason we introduced MockFS, because we ran into cases, where cascading config files in some directory were affecting unit tests for some users. So I wouldn't really want to go back to this solution.

**Comment by not-an-aardvark** [comment]
There are already [other tests](https://github.com/eslint/eslint/blob/0b81fc2d1931372a89df871543fa401e8e5fa100/tests/bin/eslint.js#L125-L153) which assume there is no config file in the root directory, so I'm not too concerned about that particular case. I agree that relying on the user's file structure outside of the project is not ideal in general.

If we don't want the tests to be fragile and break when Node changes things, I think it would be worth changing the source code to not rely on Node's `fs` module, e.g. by using something like dependency injection. There are further approaches we could take to make the tests less fragile (e.g. refactoring to use monadic effects), but I think they're probably not worthwhile at this point.

**Comment by nzakas** [comment]
It looks like MockFS has actually solved this! https://github.com/tschaub/mock-fs/issues/256#event-2116072325

So I think we can revert the test change and upgrade MockFS.
