### ISSUE TITLE
eslint hangs when invoked programmatically 

### ISSUE THREAD

**Issue by simlu** [eslint/eslint#11106]
**Tell us about your environment**

* **ESLint Version:** [5.9.0](https://github.com/blackflux/js-gardener/blob/master/package.json#L51)
* **Node Version:** [8.10](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
* **npm Version:**: 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?** 

babel-eslint

**Please show your full configuration:**
- [eslint.json](https://github.com/blackflux/js-gardener/blob/master/src/conf/eslint.json)
- [.babelrc](https://github.com/blackflux/js-gardener/blob/master/.babelrc)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

We use js-gardener to invoke eslint programmatically. This works perfectly fine most of the time. However sometimes it hangs.

Is there a way to check where this hangs? Unfortunately it doesn't happen very often, so it's hard to place debug code. 

**What did you expect to happen?**

Eslint to work correctly every time and not just most of times.

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint hangs. There is no output.

**Are you willing to submit a pull request to fix this bug?**

Sure, once we can figure out what is going on.

**Comment by platinumazure** [comment]
Hi @simlu, thanks for the issue.

Could you provide some basic instructions on installing and using js-gardener, and some sample configuration (etc.), so it's easier to try to reproduce this issue? Thanks!
