### ISSUE TITLE
no-extra-parens fires a warning after a documented type cast

### ISSUE THREAD

**Issue by roncli** [eslint/eslint#11109]
**What rule do you want to change?**
no-extra-parens

**Does this change cause the rule to produce more or fewer warnings?**
Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**
Default behavior would be preferable, but I have nothing against it being a new option.

**Please provide some example code that this change will affect:**

```js
// @ts-check
/* eslint-disable max-classes-per-file */

/**
 * Class A.
 */
class A {}

/**
 * Class B.
 */
class B extends A {

    /**
     * @returns {string} The class name.
     */
    get name() {
        return "B";
    }
}

/**
 * Function c.
 * @returns {A} Class A.
 */
const c = () => new B();

const d = c();

console.log(/** @type {B} */ (d).name);
```

Here is the same code with the warning:

![image](https://user-images.githubusercontent.com/498929/48828633-182d6080-ed25-11e8-94f2-8c8601a08c80.png)

**What does the rule currently do for this code?**
In this code, I am documenting a type cast from one class to another.  This requires the expression following the documented type cast to be enclosed in parenthesis.  See https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript#casts for details regarding the implementation.

In this case, the variable `d` is assigned to the return from the function `c()` which is documented to return an instance of class `A`.  I then document a type cast of `d` to an instance of class `B` using `/** @type {B} */` just before using it in the `console.log` method.  In order for TypeScript to recognize this documented type cast, I must then enclose `d` in parenthesis.  However, eslint does not recognize this as a valid reason for using parenthesis around `d` and gives the "no-extra-parens" warning.

**What will the rule do after it's changed?**
The rule should recognize that I am documenting a type cast, understand that this type of documentation requires parenthesis around the next expression, and not give the "no-extra-parens" warning.

**Are you willing to submit a pull request to implement this change?**
This is not something I could do in a timely fashion, as I have no knowledge of the eslint code base.

**Comment by nzakas** [comment]
Thanks for the report. Unfortunately, we don't make exceptions for the way other tools require comments/parens/etc. to be situated. There are just too many tools with too many different patterns to support. Your best bet is probably to create your own version of the rule using [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer), which allows you to inherit the core rule and filter out messages you don't want.

**Comment by roncli** [comment]
Thanks, I'll consider that.  Right now I'm just doing a // eslint-disable-line no-extra-parens as a workaround.
