### ISSUE TITLE
Stop reporting warning as errors when using tap reporter

### ISSUE THREAD

**Issue by GabrielCousin** [eslint/eslint#11110]
**The version of ESLint you are using.**
2.7.0

**The problem you want to solve.**
I am a sass-lint user (which relies on eslint-formaters)
When using the tap formatter, all messages are flagged as `not ok` no matter their severity. Messages with severity of 1 should be flagged as `ok` and should contain the warning message. I feel like it's odd to have a failing test result despite all tests are passing but containing some warnings.
However, this seems to be the expected behavior according to tests written in the project.

* Already reported here but closed because of inactivity: https://github.com/eslint/eslint/issues/6916

**Your take on the correct solution to problem.**
The issue is located in this file: https://github.com/eslint/eslint/blob/master/lib/formatters/tap.js#L53
I think it would be a good think for iterate on each message and flag the "message key" as "not ok" if a 
severity of 2 is found.

**Are you willing to submit a pull request to implement this change?**
Definitely, I just wanted to be sure this actual problem was not something "by design"

Thanks!

**Comment by nzakas** [comment]
Thanks for the issue. Can you please update the description to include the actual problem you're seeing? (Referencing another issue means people need to jump around and it's much easier to have all of the information in one issue.)

Thanks!

**Comment by GabrielCousin** [comment]
@nzakas description rephrased, I hope it's easier to read! Sorry about that 👍

**Comment by platinumazure** [comment]
Reopening, reclassifying as formatter issue, and marking as accepted.

I don't think this was something we intentionally designed as such and it's definitely not ideal that warnings and errors can't be distinguished in this formatter.

**Comment by GabrielCousin** [comment]
@platinumazure I’ll submit a PR soon.
