### ISSUE TITLE
Un-deprecate the lines-around-directive rule

### ISSUE THREAD

**Issue by nwoltman** [eslint/eslint#11115]
**The version of ESLint you are using.**

5.9.0

**The problem you want to solve.**

The [`lines-around-directive`](https://eslint.org/docs/rules/lines-around-directive) rule was deprecated in ESLint v4.0.0 with the claim that it will be replaced by the [`padding-line-between-statements`](https://eslint.org/docs/rules/padding-line-between-statements) rule. However, the `padding-line-between-statements` rule is not able to fully replicate the functionality of the `lines-around-directive` rule (as demonstrated in #8884).

**Your take on the correct solution to problem.**

Since the proposal from #8884 was rejected, I'd like to propose that the `lines-around-directive` rule be un-deprecated.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by nzakas** [comment]
Thanks for the issue. We don't have a process for undeprecating rules, so I think the best way forward is to open a new issue as a bug that explains the behavior you're looking for. You can either update the description of this issue to do that or close this one and open a new issue. Thanks!

**Comment by platinumazure** [comment]
As a note-- #8884 was not rejected as such, it's more that it didn't get support from the team. We're happy to re-evaluate (and I'm more inclined to support it or a similar proposal now that I know we have a compatibility issue with a previous rule).

**Comment by nwoltman** [comment]
Opened #11129 as suggested by @nzakas.
