### ISSUE TITLE
Deprecated dependancy

### ISSUE THREAD

**Issue by LJNeon** [eslint/eslint#11119]
**Tell us about your environment**

* **ESLint Version:** 5.9.0
* **Node Version:** 10.13.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
npm install --save-dev eslint
```

**What did you expect to happen?**
It would install with no deprecation warnings.

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
+ eslint@5.9.0
added 114 packages from 71 contributors and audited 183 packages in 8.393s
found 0 vulnerabilities
```

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by nzakas** [comment]
Duplicate of #11052
