### ISSUE TITLE
Eslint cli doesn't accept single quoted parameters

### ISSUE THREAD

**Issue by linvain** [eslint/eslint#11120]
For some reason `"lint": "eslint \"./src/**/*.js\""` works but `"lint": "eslint './src/**/*.js'"` doesn't. It throws an error:
```console
$ yarn lint
yarn run v1.12.3
$ eslint './src/**/*.js'

Oops! Something went wrong! :(

ESLint: 5.9.0.
No files matching the pattern "'./src/**/*.js'" were found.
Please check for typing mistakes in the pattern.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Tell us about your environment**

* **ESLint Version:** 5.9.0
* **Node Version:** 11.2.0
* **npm Version:** 6.4.1
* **yarn Version:** 1.12.3
* **OS:** Windows 10
* **Shell:** Git Bash

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  "extends": "eslint:recommended"
}
```

```json
{
  "private": true,
  "scripts": {
    "start": "webpack-dev-server --mode development --open",
    "build": "webpack --mode production",
    "lint": "eslint './src/**/*.js'"
  },
  "dependencies": {
    "@babel/core": "^7.1.6",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "html-webpack-plugin": "^3.2.0",
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0-alpha.2",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "devDependencies": {
    "eslint": "^5.9.0"
  }
}
```
</details>

**Comment by mysticatea** [comment]
Thank you for this issue.

But I think it's by design, by Windows.
On Windows, single quotes are not part of syntax.

**Comment by nzakas** [comment]
Yes, this is part of the operating system behavior, not ESLint's behavior.
