### ISSUE TITLE
Enforce parser usage from a plugin

### ISSUE THREAD

**Issue by bradzacher** [eslint/eslint#11127]
**The problem you want to solve.**
Right now, if a plugin requires certain config to run correctly, it must have a readme listing out the requirements, and each user must copy out the config (and install any additional dependencies, if required).

For example, `eslint-plugin-typescript` has a hard dependency on `typescript-eslint-parser`, and it *must* be defined in the config as the parser.

If plugins had a way to provide this when it is included, this could ease the friction of configuring, and also make it easier for a plugin to manage its dependencies.

**Your take on the correct solution to problem.**
I would consider adding it to the [`environments`](https://eslint.org/docs/developer-guide/working-with-plugins#environments-in-plugins) export for plugins.

Right now `environments` supports `globals` and `parserOptions`.

**Are you willing to submit a pull request to implement this change?**
👍

**Comment by nzakas** [comment]
> If plugins had a way to provide this when it is included

What is "this" and "it" in this sentence? Are you talking about exporting the parser object from the plugin object? You can kind of already do that. Suppose you plop a file like this in your plugin at `/parser.js`:

```js
module.exports = require("typescript-eslint-parser");
```

You can then do this in a config:

```js
module.exports = {
    parser: "eslint-plugin-typescript/parser"
};
```

You can make it simpler for users at that point by [exporting a config](https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins) from your plugin that includes that entry and updating the documentation to make sure to supply the name of the config in their `extends` field.

Does that solve your problem?

**Comment by bradzacher** [comment]
Sorry, to be clear I mean:
> If plugins had a way to provide the required parser to eslint when the plugin is loaded into eslint.

I.e. this would work
```JS
// eslint-plugin-foo
module.exports = {
  environment: {
    parser: 'mylanguage-parser-eslint',
  },
  rules,
}
```
```CJSON
// .eslintrc
{
  "plugins": [
    "foo"
  ]
}
```

Your solution is a nice alternative that works right now. But it still has the friction of explicitly having to have users include the config
```JS
// eslint-plugin-foo/parser.js
module.exports = require('mylanguage-parser-eslint')

// eslint-plugin-foo
module.exports.rules = rules;
```
```CJSON
// .eslintrc
{
  "parser": "eslint-plugin-foo/parser",
  "plugins": [
    "foo"
  ]
}
```
This does allow us to make the parser a direct dependency though, which is super nice.

Exporting a config would work as well. However not everyone uses or even looks at the "recommended" configs provided by plugins.

**Comment by bradzacher** [comment]
sounds like a reasonable justification!
thanks for explaining.

We'll go with import/exporting the parser to create a direct dependency
