### ISSUE TITLE
object-curly-newline support object extraction in function parameters

### ISSUE THREAD

**Issue by vincentkwok** [eslint/eslint#11131]
`object-curly-newline` blocks object extraction in function parameters. Workaround is to code within the function line. 

**What rule do you want to change?**
object-curly-newline

**Please provide some example code that this change will affect:**

```js
const formatter = ({ msg, param, value, nestedErrors }) => {
  // do something
};

formatter(object);
```

**What does the rule currently do for this code?**

```bash
error  Expected a line break after this opening brace   object-curly-newline
error  Expected a line break before this closing brace  object-curly-newline
```

**Comment by platinumazure** [comment]
Hi @vincentkwok, thanks for the issue.

The `object-curly-newline` rule does support different configuration for ObjectPattern (i.e., object destructuring) vs ObjectExpression (i.e., object literals). You could configure ObjectPattern to not require newlines and ObjectExpression to require newlines:

```json
{
    "rules": {
        "object-curly-newline": ["error", {
            "ObjectExpression": "always",
            "ObjectPattern": { "multiline": true }
        }]
    }
}
```

That said, this will affect other destructuring as well (even outside of function parameters). If you need it specifically for function parameters only, then we can discuss that enhancement (or you could create a custom rule using `eslint-rule-composer` to ignore the errors reported in the function parameter case).
