### ISSUE TITLE
id-length ignore destructured object properties

### ISSUE THREAD

**Issue by andrewmiller1** [eslint/eslint#11142]
**What rule do you want to change?**

id-length

**Does this change cause the rule to produce more or fewer warnings?**

Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

New default behavior

**Please provide some example code that this change will affect:**

```js
import Module from 'module';
const { builtinModules: builtins } = Module;
```

**What does the rule currently do for this code?**

Says builtinModules is too long

**What will the rule do after it's changed?**

Understand builtinModules isn't even being used and is being renamed as a compromise for the sole purpose of following this rule

**Are you willing to submit a pull request to implement this change?**

If someone points out to me where in https://github.com/eslint/eslint/blob/master/lib/rules/id-length.js builtinModules from the above example would be captured then sure

**Comment by andrewmiller1** [comment]
To expand on what's at play in the "compromise" I mentioned in "What will the rule do after it's changed?":

I made a standard for myself to keep variable name lengths under 12 characters. When making use of npm, I commonly run into some variables in packages not following this specific standard.

This puts me in a bind, as I don't want to litter my code with disable rule comments, or, even worse, disable the rule for the whole file.

With destructuring, we get a cool ability to make aliases for each variable of outside code.

I'd like eslint to use destructuring as an opportunity to check to see if the offending item we're grabbing is being used via its name (violation) or rename (valid).

**Comment by platinumazure** [comment]
Hi @andrewmiller1, thanks for the issue.

This seems like a reasonable request to me. I'll support it.
