### ISSUE TITLE
deprecate built-in jsdoc

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11146]
this is to track todos in https://eslint.org/blog/2018/11/jsdoc-end-of-life.

- [x]  deprecate doctrine
- [x]  deprecate `require-jsdoc` and `valid-jsdoc` (https://github.com/eslint/eslint/pull/11145)
- [x]  deprecate `SourceCode#getJSDocComment()`
- [x]  switch to `eslint-plugin-jsdoc` in `eslint-config-eslint` (#11147 )

am I missing something?

**Comment by kaicataldo** [comment]
Thanks - I'll assign myself since I committed to the work, but if you're interested in helping out, that's great!

**Comment by kaicataldo** [comment]
Looks like this is done now that https://github.com/eslint/eslint/pull/12332 is merged!
