### ISSUE TITLE
eslint not working with yarn add

### ISSUE THREAD

**Issue by flyingguitarman** [eslint/eslint#11157]
**Tell us about your environment**

* **ESLint Version:** eslint 5.9.0
* **Node Version:** 9.3.0
* **npm Version:** 6.4.1
* **yarn version** 1.12.3

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

`Daniels-MBP-2 src/functions ‹fbhosting*› » yarn add eslint
yarn add v1.12.3
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
error eslint@5.9.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.3.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**What did you expect to happen?**
I expected yarn to add eslint and it's dependancies to my project.

**What actually happened? Please include the actual, raw output from ESLint.**
it did not install due to node's version being to high.

**Comment by flyingguitarman** [comment]
I do know that i have a package.lock due to my switching from npm to yarn. I'd prefer to use yarn. the concern is the node version should work due to it looking for a node version of ">=9.10.0"

**Comment by Aladdin-ADD** [comment]
have you tried`yarn --ignore-engines`?

**Comment by flyingguitarman** [comment]
looks like that "fixed" it. everything appears to have worked.

thanks!
