### ISSUE TITLE
Make prefer-destructuring fixable

### ISSUE THREAD

**Issue by golopot** [eslint/eslint#11151]
**What rule do you want to change?**
prefer-destructuring

**Does this change cause the rule to produce more or fewer warnings?**
same

**Please provide some example code that this change will affect:**

```js
// This
const z = a.z
// should autofix to this
const { z } = a

```

**Are you willing to submit a pull request to implement this change?**
no

**Comment by kaicataldo** [comment]
This seems like a reasonable enhancement to me, however I do wonder what the autofixing behavior should be for array destructuring when the index > 0. i.e. should it autofix `const foo = bar[2];` to `const [,, foo] = bar;`?

**Comment by ljharb** [comment]
I think it probably shouldn’t autofix in that case - since it’s iterable destructuring, not array destructuring, and there’s no guarantee that an object with a 2 property is either an array or iterable.

**Comment by bendtherules** [comment]
Few cases I could think of :
1. Handling just assignments: `z = a.z`
2. Longer assignment expressions: `blah = z = a.z` (which is different from `blah = {z} = a`)
3. Merging different property names from same object ?? 
```js
// from
let x = a.x;
let y = a.y;
let z = a.z;

// to
let {x, y, z} = a;
```
This would be very very hard to implement correctly, but produce more human-like result.

**Comment by platinumazure** [comment]
What about nested destructuring cases, in addition to the cases above?

My thinking is, this would be a pretty significant implementation and maintenance burden, unless we only cover very simple cases and just don't bother with the rest. I'm currently mildly opposed to this for that reason, but could be persuaded.

**Comment by sindresorhus** [comment]
I would be happy if it only auto-fixed the simple case, like `let x = a.x;` => `let {x} = a;`.

**Comment by ilyavolodin** [comment]
I think supporting auto-fixing for the most basic cases is fine for this rule.
