### ISSUE TITLE
Confliction rule: comma-spacing & space-in-parens

### ISSUE THREAD

**Issue by wilsonIs** [eslint/eslint#11164]
**Tell us about your environment**

* **ESLint Version:*^4.19.1*
* **Node Version:*v8.11.2*
* **npm Version:*5.6.0*

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
"comma-spacing": ["error", {"before": false, "after": true}]
"space-in-parens": ["error", "always"]
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const something = this.doSomething(a,);
```

```bash
eslint --fix
```

**What did you expect to happen?**
do not repeat compiled with hot reload since there is no file change

**What actually happened? Please include the actual, raw output from ESLint.**
since the rules above has a conflict, when it sets to use autofix, webpack repeat complie and never stop

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by g-plane** [comment]
I cannot reproduce this when `space-in-parens` is in `always` mode. However, there is really a conflict when `space-in-parens` is in `never` mode.

**Comment by wilsonIs** [comment]
you are right, my mistake

**Comment by platinumazure** [comment]
@g-plane Sorry to ask, but is this still reproducible? If so, could you show that in a demo? Then we can reopen and accept. Thanks!

**Comment by g-plane** [comment]
@platinumazure https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGNvbW1hLXNwYWNpbmc6IDIgKi9cclxuLyogZXNsaW50IHNwYWNlLWluLXBhcmVuczogWzIsICduZXZlciddICovXHJcbmEoYSwgYiwpIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19
