### ISSUE TITLE
Parsing error: Unexpected token ="

### ISSUE THREAD

**Issue by GerardSuch** [eslint/eslint#11175]
**Tell us about your environment**

* **ESLint Version:** 5.10
* **Node Version:** 10.12.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
<details>
<summary>Configuration</summary>
```js
{
    "env": {
      "browser": true,
      "es6": true,
      "node": true
    },
    "extends": ["prettier"],
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      },
      "ecmaVersion": 2018,
      "sourceType": "module"
    },
    "plugins": ["react", "prettier"],
    "rules": {
      "prettier/prettier": ["error"],
      "indent": ["error", 2],
      "semi": ["error", "never"]
    }
  }
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import React from "react";
import Head from "next/head";
import { onFormSubmit } from "../components/onFormSubmit";
import HtmlTable from "../components/HtmlTable.js";
import Upload from "../components/Upload.js";
import "semantic-ui-css/semantic.min.css";
import "../static/index.css";

export default class Index extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      files: null,
      stocks_present: null,
      stocks_past: null,
      historic: null,
      webpage_status: "getting stocks..."
    };
  }

  static async getInitialProps({ req }) {
    const userAgent = req ? req.headers["user-agent"] : navigator.userAgent;
    const baseUrl = req ? `${req.protocol}://${req.get("Host")}` : "";
    return {
      baseUrl: baseUrl,
      userAgent: userAgent
    };
  }

  Header = () => (
    <Head>
```

![image](https://user-images.githubusercontent.com/4474004/49702887-3ab4ea00-fbfe-11e8-8a4d-235a2113e090.png)

And another error

```js
import React from 'react';
import { Input, Label, Button, Icon } from 'semantic-ui-react'

const div_css = {
    margin: '45px'
}
const label_css = {
    cursor: 'pointer',
    marginRight: '45px'
}

const Upload = props => {
    return (
    <div style={div_css}>
```

![image](https://user-images.githubusercontent.com/4474004/49702882-2ffa5500-fbfe-11e8-8358-fd9bc6670f33.png)

**What did you expect to happen?**
Nothing

**What actually happened? Please include the actual, raw output from ESLint.**
Don't understand the error "Parsing error: Unexpected token =",

![image](https://user-images.githubusercontent.com/4474004/49702889-49030600-fbfe-11e8-888b-1e886462cb72.png)

**Comment by platinumazure** [comment]
Hi @GerardSuch, thanks for the issue.

You're using a class property, which is not (yet) standard JS. So the default parser (which only parses standard JS) correctly complains about your syntax.

You have two options:

* Install babel-eslint and use it as your parser, so that ESLint won't get a parser error
* Use the standard class method syntax:
    ```js
    Header() {
        return (
            // JSX goes here
       )
    }
    ```

As for the other error, I'm not sure how to help because I can't tell which line is line 14 in upload.js. Please clarify.

**Comment by GerardSuch** [comment]
Thanks! I'm looking at it now. Related to the other error, it's the image I've uploaded, it is the "style" word that appears underlined.

**Comment by platinumazure** [comment]
Thanks for clarifying! Unfortunately I can't actually tell what was wrong what the `Upload` example, but I'm glad you figured it out!
