### ISSUE TITLE
esllint not work in vscode

### ISSUE THREAD

**Issue by lilingling3** [eslint/eslint#11188]

**Comment by lilingling3** [comment]
ESLint couldn't find the plugin "eslint-plugin-node". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-node is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-node@latest --save-dev

Path to ESLint package: /Users/lilingling/.nvm/versions/node/v8.6.0/lib/node_modules/eslint

i do this ,but not work

**Comment by Aladdin-ADD** [comment]
ESLint can be globally or locally installed. seems you are using a global-installed eslint, have you tried `npm i eslint-plugin-node -g`?

refs: https://github.com/eslint/eslint#why-cant-eslint-find-my-plugins
