### ISSUE TITLE
'React' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by VanessaChu** [eslint/eslint#11183]
When i run eslint on my code, I get the error:
`'React' is defined but never used  no-unused-vars`
when I remove import 'React' from 'react' I get the error 
`'React' must be in scope when using JSX`

I tried enabling the rules below but still receive the error. 
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/react-in-jsx-scope": 1

Can someone help me check if my configurations are correct, if I'm not overriding anything?

```
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "airbnb",
    "plugin:flowtype/recommended"
  ],
  "plugins": [
    "babel",
    "react",
    "flowtype"
  ],
  "rules": {
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/react-in-jsx-scope": 1,
  
    // Indent with 4 spaces
    "indent": [
      "error",
      4
    ],
    // Indent JSX with 4 spaces
    "react/jsx-indent": [
      "error",
      4
    ],
    // Indent props with 4 spaces
    "react/jsx-indent-props": [
      "error",
      4
    ],
    // TODO: Remove all of these exceptions
    // We have code that violates each one of these rules.
    // We should fix the style then remove the rules when we can.
    "consistent-return": "off",
    "flowtype/no-types-missing-file-annotation": "off",
    "import/extensions": "off",
    "import/no-unresolved": "off",
    "import/no-named-as-default": "off",
    "import/no-named-as-default-member": "off",
    "import/prefer-default-export": "off",
    "react/default-props-match-prop-types": "off",
    "react/forbid-prop-types": "off",
    "react/jsx-closing-tag-location": "off",
    "react/jsx-filename-extension": "off",
    "react/no-string-refs": "off",
    "react/no-unused-prop-types": "off",
    "react/no-unused-state": "off",
    "react/prefer-stateless-function": "off",
    "react/prop-types": "off",
    "react/require-default-props": "off",
    "react/sort-comp": "off",
    "max-len": "off",
    "no-case-declarations": "off",
    "no-console": "off",
    "no-mixed-operators": "off",
    "no-nested-ternary": "off",
    "no-shadow": "off",
    "no-use-before-define": "off",
    "no-underscore-dangle": "off",
    "no-unused-expressions": "off",
    "prefer-promise-reject-errors": "off"
  },
  "env": {
    "jest": true
  },
  "globals": {
    "fetch": false,
    "Response": false,
    "React": true
  }
}

```

I am using these versions in package.json:
devDependencies
```
      "eslint-config-airbnb": "16.1.0",
      "eslint-plugin-babel": "^5.1.0",
      "eslint-plugin-flowtype": "^2.46.1",
      "eslint-plugin-react": "^7.9.1",
```
dependencies

>       "react": "16.0.0",
>       "react-native": "0.50.4",

**Comment by platinumazure** [comment]
Hi @VanessaChu, thanks for the issue.

Your configuration looks good to me. Would you mind trying to run ESLint with the --debug flag to see if another configuration is being picked up unexpectedly?

**Comment by not-an-aardvark** [comment]
You might need to enable the [`react/jsx-uses-react`](https://github.com/yannickcr/eslint-plugin-react/blob/8ef86c53003d78c88416a35e1e627914fcfabdf4/docs/rules/jsx-uses-react.md) rule.

**Comment by VanessaChu** [comment]
@platinumazure after running npm run lint --debug
Lifecycle scripts included:
  test
    jest

available via `npm run-script`:
  build
    npm run copy-src
  copy-src
    (cd build && mkdir -p lib/commonjs/story-builder) && cp -r src/* package.json build/lib/commonjs/story-builder
  clean
    cd build && rm -r lib/commonjs/story-builder
  release
    npm run lint && npm run build && npm run test
  test-watch
    jest --watch
  test-debug
    node --inspect-brk node_modules/.bin/jest --runInBand
  lint
    node node_modules/.bin/eslint src/ test/ --fix

**Comment by VanessaChu** [comment]
@not-an-aardvark  I have already enabled react/jsx-uses-react with "react/jsx-uses-react": 1,

**Comment by platinumazure** [comment]
My apologies, I didn't realize you were running an npm script. Adding just `--debug` to an npm script results in npm's debug logs being visible, rather than ESLint's.

Could you try running the script with `-- --debug` on the end? This ensures the `--debug` parameter is passed to ESLint rather than consumed by npm. Thanks!

**Comment by g-plane** [comment]
@VanessaChu Does your code contain valid JSX?
