### ISSUE TITLE
Error with Eslint with Nexe compiled executable

### ISSUE THREAD

**Issue by jimdou** [eslint/eslint#11190]
Also posted the issue to Nexe https://github.com/nexe/nexe/issues/569

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I have created a CLI application on node js, it has Eslint as a dependency.
I built it using nexe, I get an error when I try to use my function to lint from the executable:

```js
var CLIEngine = require("eslint").CLIEngine;
eslintCli.executeOnFiles(jsFiles).results
```
Note the function still woks when called from the script with node index.js

In both case the error seems linked with the path for rules in node_modules/eslint/lib/rules.js (line 14)

```js
 const ruleReplacements = require("../conf/replacements").rules;
```

**Anything else we need to know?:**
The bug appeared when I added Eslint as a depency, it was working beforehand.

with nexe 2.0.0-rc.34 :
```bash
const ruleReplacements = require("../conf/replacements").rules;
                                                        ^

TypeError: Cannot read property 'rules' of null
    at Object.<anonymous> (executable:39640:57)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:29912:13)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:29862:16)
    at c (executable:220866:3584)
    at b.require (executable:220866:3346)
    at Object.<anonymous> (executable:1365:17)
```

with nexe 3.0.0 using nexe@next:
```bash
Error during CommitAttempt creation.
{ Error: ENOENT: no such file or directory, scandir 'executable/node_modules/eslint/lib/rules'
    at Object.readdirSync (fs.js:783:3)
    at Object.readdirSync (executable:168:50)
    at module.exports (executable/node_modules/eslint/lib/load-rules.js:40:8)
    at Rules.load (executable/node_modules/eslint/lib/rules.js:83:26)
    at new Rules (executable/node_modules/eslint/lib/rules.js:63:14)
    at new Linter (executable/node_modules/eslint/lib/linter.js:887:22)
    at new CLIEngine (executable/node_modules/eslint/lib/cli-engine.js:442:23)
    at createCommitAttempt.then.body (executable/utils/linter.js:266:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path:
   'executable/node_modules/eslint/lib/rules' }
```
   
**What did you expect to happen?**
That the executable can use the eslint module depency when built

**Tell us about your environment**

* **ESLint Version:**
5.9.0

* **Node Version:**
10.14.1

* **npm Version:**
6.4.1

* **Platform(OS/Version):**
 MacOs High Sierra

* **Host Node Version:**
 v10.14.1

* **Nexe version:**
2.0.0-rc.34 and V3.0.0

**Comment by jimdou** [comment]
Also posted the issue to Nexe https://github.com/nexe/nexe/issues/569

**Comment by kaicataldo** [comment]
Given that this works when you run your script directly, it sounds like the file is there when you `npm install`. Since it doesn't work after you build it with Nexe, I wonder if this is a bug with how Nexe calculates what files to include?

**Comment by jimdou** [comment]
https://github.com/nexe/nexe/issues/569#issuecomment-449621078 
I tried using nexe creator's recommendation. I still get the issue, i think this is due to the way the CLI engine calls its scripts

**Comment by jimdou** [comment]
The problem seems to be linked to the way eslint/lib/load-rules works in order to get the eslint/lib/rules/ directory

```js
module.exports = function(relativeRulesDir, cwd) {

    const rulesDir = relativeRulesDir
        ? path.resolve(cwd, relativeRulesDir)
        : path.join(__dirname, "rules");

    // cache will help performance as IO operation are expensive
    if (rulesDirCache[rulesDir]) {
        return rulesDirCache[rulesDir];
    }

    const rules = Object.create(null);

    fs.readdirSync(rulesDir).forEach(file => {
        if (path.extname(file) !== ".js") {
            return;
        }
        rules[file.slice(0, -3)] = path.join(rulesDir, file);
    });
    rulesDirCache[rulesDir] = rules;

    return rules;
};
```
Using nexe 2.0.0-rc.34 
If  i call 
```js
 var linter = new Linter();
```

On the project itself (using node index.js)

<img width="557" alt="screen shot 2018-12-23 at 4 02 36 pm" src="https://user-images.githubusercontent.com/626003/50384942-2d572f80-06d5-11e9-877d-f5efc6970e7d.png">


Using the executable
<img width="488" alt="screen shot 2018-12-23 at 4 01 57 pm" src="https://user-images.githubusercontent.com/626003/50384943-30522000-06d5-11e9-95de-718072460c7b.png">


@calebboyd
