### ISSUE TITLE
[semi] require semicolons doesn't work

### ISSUE THREAD

**Issue by wuliqiangqiang** [eslint/eslint#11209]
```js
module.exports = {
  root: true,
  parserOptions: {
    "sourceType": "module",
  },
  env: {
    "browser": true,
    "commonjs": true,
    "node": true,
    "es6": true
  },
  extends: "eslint:recommended",
  plugins: [
    'html'
  ],
  rules: {
    "no-console": "off",
    "semi": ["error", "always"],
    "curly": "error",
    "no-redeclare":"error",
    "strict": 2,
  }
};
```
it is my .eslintrc.js setting with the webpack4 
```js
{
        enforce: 'pre',
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'eslint-loader',
          options: {
            fix: true,
            formatter: require('eslint-friendly-formatter')
          }
        },
      },
```
it is my webpack's loader eslint-loader setting

just the semi function doesn't work. Becuase it hasn't any tip from the shell about the sime function ,  others function is success

the shell tips:
```shell
ERROR in ./src/pages/test/child_test2/js/child_test2.js
Module Error (from ./node_modules/_eslint-loader@2.1.1@eslint-loader/index.js):

  ✘  http://eslint.org/docs/rules/no-undef  'c' is not defined
  src/pages/test/child_test2/js/child_test2.js:19:3



✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/no-undef

```

the child_test2.js file content
```js
var aa = 1
if (aa) {
  a()
  b()
  c()
}
function a(){
  var v =1
  console.log(v)
}
function b(){
  var vv =1
  console.log(vv)
}
```

**Comment by g-plane** [comment]
ESLint works as intended. Your problem is just that you haven't defined the function `c`.

**Comment by wuliqiangqiang** [comment]
@g-plane but `"semi": ["error", "always"]` doesn't work. no throw any error tip in the shell.just function c no defined

**Comment by ljharb** [comment]
If you fix the no-undef error, do you see a semi error?

**Comment by wuliqiangqiang** [comment]
@ljharb no..

**Comment by mysticatea** [comment]
What does it happen if you remove `fix: true` from your webpack config?

**Comment by wuliqiangqiang** [comment]
@mysticatea hey man. the same result, no any error message or tip.

**Comment by g-plane** [comment]
How about running ESLint directly from CLI?

**Comment by wuliqiangqiang** [comment]
@g-plane thx 
boot the ESLint with the CLI  is work.

so i think it has some problem in the webpack setting .

i close the webpack setting about it 
```
stats: "errors-only",
```
the missing semicolon error tip was show in the shell .
but i find the `fix:true` eslint setting  doesn't work .

in the eslint-loader issue
about it [https://github.com/webpack-contrib/eslint-loader/issues/248](eslint-loader/)

I have been resolved it about this. THX
