### ISSUE TITLE
Feature Request: How output stats can tell us eslint has fixed something or nothing

### ISSUE THREAD

**Issue by wood1986** [eslint/eslint#11219]
**Tell us about your environment**

* **ESLint Version:** 5.11.1
* **Node Version:** 11.6.0
* **npm Version:** 6.5

**What parser (default, Babel-ESLint, etc.) are you using?**
NOT applicable

**Please show your full configuration:**
NOT applicable

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
eslint -c ./.eslintrc.js --fix --ext .js --ext .jsx .
```

**What did you expect to happen?**

```
{
  results,
  errorCount: 0,
  warningCount: 5,
  fixedCount: 2, <<<<<<<<<<<< new stat
  fixableErrorCount: 0,
  fixableWarningCount: 0,
  usedDeprecatedRules
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

I am fixing https://github.com/webpack-contrib/eslint-loader/pull/255#issue-228445668 and https://github.com/webpack-contrib/eslint-loader/pull/260#issue-241268921. I find that there is no way to know if the last run did fix something or nothing.

For example, the first run fixed 10 errors/warnings and saved to disk. It still has some unfixable errors/warnings. And the json output stats looks like

```
{
  results,
  errorCount: 0,
  warningCount: 5,
  fixableErrorCount: 0,
  fixableWarningCount: 0,
  usedDeprecatedRules
}
```

If I did nothing to the sources and then do the second run, the json output stats remains unchanged. Based on the two identical info, it cannot tell us eslint did fix/save/touch the file.

Currently, eslint-loader tries to stop the infinite loop issue with that predicates 
`if (config.fix && (res.results[0].fixableErrorCount > 0 || res.results[0].fixableWarningCount)) {`
See https://github.com/webpack-contrib/eslint-loader/blob/f9d48ea55138c64231890f2c2825e3a454345836/index.js#L73
But it breaks the auto-fix and auto-save. 

After I changed the predicates to `if (config.fix)`, the infinite loop comes again. Then I realize that eslint output stats does not provide enough information about the last run which is how many fixableError and fixableWarning have been fixed in the last run.

With `fixedCount`, it can tell eslint-loader does not need to save/touch the file again. Then the infinite loop issue can be solved by checking the value of `fixedCount`

**Comment by wood1986** [comment]
Here is my PR #11214

**Comment by wood1986** [comment]
#7404

**Comment by wood1986** [comment]
I guess you are talking about using `source` to check if eslint has applied the fix. 

This is not true. If your code has unfixable warning, `source` will always the fixed code.

**Comment by wood1986** [comment]
I can create a repo or video to show you later

**Comment by not-an-aardvark** [comment]
> I guess you are talking about using `source` to check if eslint has applied the fix.

No, I'm talking about using the `output` property to check if eslint has applied the fix.

**Comment by not-an-aardvark** [comment]
If you use a `results` object where fixes have been applied, there will be an `output` property containing the fixed source code instead of the `source` property. You can check whether the `output` property exists in order to figure out whether fixes have been applied.

**Comment by wood1986** [comment]
Thanks for that. Let me try on eslint-loader. If it works, I will close it.
