### ISSUE TITLE
camelCase ignoreDestructuring not ignored when destructuring happens in function parameters

### ISSUE THREAD

**Issue by dcorb** [eslint/eslint#11226]
**Tell us about your environment**

* **ESLint Version:**5.11.1
* **Node Version:**10.9.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  extends: ['airbnb', 'plugin:prettier/recommended', 'prettier/react'],
  plugins: ['prettier', 'react'],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 8,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    camelcase: ['error', { ignoreDestructuring: true }],
    'react/jsx-filename-extension': [0],
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import React from 'react';

const SectionFormattedText = ({ field_formatted_text }) => (
  <div dangerouslySetInnerHTML={{ __html: field_formatted_text.processed }} />
);

export default SectionFormattedText;
```

```bash
eslint --ignore-path .gitignore \"**/*.{js,jsx}\"",
```

**What did you expect to happen?**
camelCased `field_formatted_text` to be ignored

**What actually happened? Please include the actual, raw output from ESLint.**
` 4:43  error    Identifier 'field_formatted_text' is not in camel case  camelcase`

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by RedTn** [comment]
I don't think it necessarily needs to be inside function parameters.
When my code is 
```
const { field_formatted_text } = foo;
const bar = field_formatted_text;
```
My linter complains
```
Identifier 'field_formatted_text' is not in camel case. (at 2:13)
const bar = field_formatted_text;
```

Doesn't complain if
```
myfunc(field_formatted_text);
```

**Comment by platinumazure** [comment]
Hi @dcorb, sorry for letting this slip through the cracks.

I [can't reproduce](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGNhbWVsY2FzZTogW2Vycm9yLCB7IGlnbm9yZURlc3RydWN0dXJpbmc6IHRydWUgfV0gKi9cclxuXHJcbmNvbnN0IFNlY3Rpb25Gb3JtYXR0ZWRUZXh0ID0gKHsgZmllbGRfZm9ybWF0dGVkX3RleHQgfSkgPT4gbnVsbDtcclxuXHJcbmV4cG9ydCBkZWZhdWx0IFNlY3Rpb25Gb3JtYXR0ZWRUZXh0OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) in the ESLint demo. Am I missing something?

**Comment by Rawphs** [comment]
@platinumazure I just stumbled upon this issue and I took the liberty to [fix your demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGNhbWVsY2FzZTogW2Vycm9yLCB7IGlnbm9yZURlc3RydWN0dXJpbmc6IHRydWUgfV0gKi9cblxuY29uc3QgU2VjdGlvbkZvcm1hdHRlZFRleHQgPSAoeyBmaWVsZF9mb3JtYXR0ZWRfdGV4dCB9KSA9PiB7XG5cdHJldHVybiBmaWVsZF9mb3JtYXR0ZWRfdGV4dDtcbn07XG5cbmV4cG9ydCBkZWZhdWx0IFNlY3Rpb25Gb3JtYXR0ZWRUZXh0OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==). I think this is what he meant (I am having the same issue)

**Comment by dcorb** [comment]
Thanks @Rawphs , that's it

**Comment by liunate** [comment]
I found the destructured variable also shows identifier error when it's assigned to another variable.

It's OK when it's assigned to object property value or is fed to function parameter.

See latest eslint v6 [demo] (https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGNhbWVsY2FzZTogW2Vycm9yLCB7IGlnbm9yZURlc3RydWN0dXJpbmc6IHRydWUsIHByb3BlcnRpZXM6IFwibmV2ZXJcIiB9XSAqL1xuXG5jb25zdCBhbm90aGVyRnVuYyA9ICh0ZXN0KT0+IG51bGw7XG5cbmNvbnN0IFNlY3Rpb25Gb3JtYXR0ZWRUZXh0ID0gKHsgZmllbGRfZm9ybWF0dGVkX3RleHQgfSkgPT4ge1xuICBjb25zb2xlLmxvZyhmaWVsZF9mb3JtYXR0ZWRfdGV4dCk7XG4gIFxuICBjb25zdCBhbm90aGVyVmFyID0gYW5vdGhlckZ1bmMoZmllbGRfZm9ybWF0dGVkX3RleHQpO1xuXG4gIGNvbnN0IHVuZGVyc2NvcmVPbk9iamVjdFByb3BlcnR5ID0ge1xuICAgIGFiYzogZmllbGRfZm9ybWF0dGVkX3RleHRcbiAgfTtcbiAgXG4gIGNvbnN0IG15VmFyID0gZmllbGRfZm9ybWF0dGVkX3RleHQgKyAnYWJjJztcblxuICByZXR1cm4gZmllbGRfZm9ybWF0dGVkX3RleHQ7XG59O1xuZXhwb3J0IGRlZmF1bHQgU2VjdGlvbkZvcm1hdHRlZFRleHQ7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNhbWVsY2FzZSI6Mn0sImVudiI6e319fQ==)

**Comment by kaicataldo** [comment]
@liunate Feel free to open up a new issue! We've found that reopening stale issues tend to still not get much attention.
