### ISSUE TITLE
feature request: --fix-hard option

### ISSUE THREAD

**Issue by piotr-s-brainhub** [eslint/eslint#11230]
**The version of ESLint you are using.**

4.19.1

**The problem you want to solve.**
It would be good to have two separate options:
- `--fix` - which I can use when saving a file in my IDE
- `--fix-hard` - which I can use before commit (this could fix e.g. `no-unused-vars`)

**Your take on the correct solution to problem.**

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by piotr-s-brainhub** [comment]
@kaicataldo 

IMO it should be configurable in `.eslintrc` but as default `--fix` could fix all the rules instead of:
- `no-console`
- `no-debugger`
- `accessor-pairs`
- `class-methods-use-this`
- `no-empty-function`
- `no-unused-expressions`
- `no-unused-vars`

On the other hand `--fix-hard` should always fix all the rules.

**Comment by kaicataldo** [comment]
So you're proposing two flags - one that is allows you to configure what rules run autofixers and one where it forces all the rules to run their autofixers. Does the new [--fix-type](https://eslint.org/docs/user-guide/command-line-interface#--fix-type) CLI flag solve your problem?

**Comment by piotr-s-brainhub** [comment]
@kaicataldo 

Thanks, `--fix-type` should be enough.

Btw. do you know why so many rules are not auto-fixed? e.g. `no-unused-vars`
Nobody had enough time to implement that or such rules are not designed to be auto-fixed?

**Comment by piotr-s-brainhub** [comment]
@platinumazure 

thanks for explanation

**Comment by coderaiser** [comment]
@piotr-s-brainhub , you can use [putout](https://github.com/coderaiser/putout) to fix rules that can't be fixed by `eslint`. For example it can:
- remove unused variables
- remove console calls
- remove debugger statements

All rules are configurable and can be turned on or off.
