### ISSUE TITLE
Exception for capitalized-comments if first word matches method parameter

### ISSUE THREAD

**Issue by jamestalmage** [eslint/eslint#11244]
**What rule do you want to change?**
`capitalized-comments`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer, by allowing an exception to the rule if the first word matches a method parameter.

**How will the change be implemented? (New option, new default behavior, etc.)?**
Add an option toggling the behavior. I think it should default to allowing the exception.

**Please provide some example code that this change will affect:**

```js
/*
  bar: some explanation you feel is needed about this param 
*/
function foo(bar) {
  /...
}
```

**What does the rule currently do for this code?**
It would throw an exception, since bar is not capitalized (assuming capitalize is always). 

**What will the rule do after it's changed?**
If `exceptionForMethodParams:true` option is set (which I believe should default to true), then it would allow this usage as an exception to the rule.

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by nzakas** [comment]
Thanks for the suggestion. I'm not in favor of making such a change as we'd get into a bit of comment parsing that seems beyond the intent of this rule. I'd suggest using [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer) to make a version of the rule that filters out this type of error for your projects.

**Comment by kaicataldo** [comment]
I agree with @nzakas. Just to be clear, isn't this already possible using the [`ignorePattern`](https://eslint.org/docs/rules/capitalized-comments#ignorepattern) configuration option?
