### ISSUE TITLE
Update file-entry-cache version to v4.0.0

### ISSUE THREAD

**Issue by cktang88** [eslint/eslint#11257]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**
Update dep

**Your take on the correct solution to problem.**
Update dep

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by RobLoach** [comment]
Getting deprecation notices about this....
```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for test-jstransformer@^1.0.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'jstransformer-svgo'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-01-16T03_49_54_369Z-debug.log
```

Would be great to get file-entry-cache up to date.

**Comment by nzakas** [comment]
Thanks. We are aware of this issue and it has been reported before: https://github.com/eslint/eslint/issues/11052, https://github.com/eslint/eslint/issues/11119

Unfortunately, `circular-json` is not exactly the same, and actually caused issues when we tried to upgrade it last. Please see the discussion on https://github.com/eslint/eslint/issues/11052 for the latest.
