### ISSUE TITLE
implicit-arrow-linebreak autofixer sometimes adds extra characters

### ISSUE THREAD

**Issue by bradennapier** [eslint/eslint#11268]
**Tell us about your environment**

* **ESLint Version:** 5.12.0
* **Node Version:** 10.15.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

`babel-eslint` (but i dont believe it matters)

<br />
<details>
<summary>Configuration</summary>

```json
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "env": {
    "node": true
  },
  "rules": {
    "implicit-arrow-linebreak": "error"
  }
}
```

</details>
<br />

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* [Demo](https://eslint.org/demo/#eyJ0ZXh0Ijoic3RhcnQoKVxuICAudGhlbigoKSA9PiBcbiAgICAvKiBJZiBJIHB1dCBhIGNvbW1lbnQgaGVyZSwgZXNsaW50IC0tZml4IGJyZWFrcyBiYWRseSAqL1xuICAgIHByb2Nlc3MgJiYgdHlwZW9mIHByb2Nlc3Muc2VuZCA9PT0gJ2Z1bmN0aW9uJyAmJiBwcm9jZXNzLnNlbmQoJ3JlYWR5JylcbiAgKVxuICAuY2F0Y2goZXJyID0+IHtcbiAgXHQvKiBjYXRjaCBzZWVtcyB0byBiZSBuZWVkZWQgaGVyZSAqL1xuICBcdGNvbnNvbGUubG9nKCdFcnJvcjogJywgZXJyKTtcbiAgfSlcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnNvbGUiOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZW1wdHkiOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImltcGxpY2l0LWFycm93LWxpbmVicmVhayI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlLCJub2RlIjp0cnVlLCJjb21tb25qcyI6dHJ1ZSwic2hhcmVkLW5vZGUtYnJvd3NlciI6dHJ1ZSwid29ya2VyIjp0cnVlLCJhbWQiOnRydWUsIm1vY2hhIjp0cnVlLCJqYXNtaW5lIjp0cnVlLCJqZXN0Ijp0cnVlLCJwaGFudG9tanMiOnRydWUsImpxdWVyeSI6dHJ1ZSwicXVuaXQiOnRydWUsInByb3RvdHlwZWpzIjp0cnVlLCJzaGVsbGpzIjp0cnVlLCJtZXRlb3IiOnRydWUsIm1vbmdvIjp0cnVlLCJwcm90cmFjdG9yIjp0cnVlLCJhcHBsZXNjcmlwdCI6dHJ1ZSwibmFzaG9ybiI6dHJ1ZSwic2VydmljZXdvcmtlciI6dHJ1ZSwiYXRvbXRlc3QiOnRydWUsImVtYmVydGVzdCI6dHJ1ZSwid2ViZXh0ZW5zaW9ucyI6dHJ1ZSwiZXM2Ijp0cnVlLCJncmVhc2Vtb25rZXkiOnRydWV9fX0=)

```js
start()
  .then(() => 
    /* If I put a comment here, eslint --fix breaks badly */
    process && typeof process.send === 'function' && process.send('ready')
  )
  .catch(err => {
  	/* catch seems to be needed here */
       console.log('Error: ', err)
  })

```

```bash
eslint --fix
```

**What did you expect to happen?**

Code that it "fixes" should not be invalid javascript

**What actually happened? Please include the actual, raw output from ESLint.**

It creates broken code

```javascript
start()
  .then(() => ( 
    /* If I put a comment here, eslint --fix breaks badly */
    process && typeof process.send === 'function' && process.send('ready')
         )
        )
  )
  .catch(err => ( {
  	/* catch seems to be needed here */
       console.log('Error: ', err)
  })
```

> Notice that it broke the catch as it seems to assume its an implicit object return 

**Are you willing to submit a pull request to fix this bug?**

not really, wouldnt know where to start

---

This can get REALLY bad and is especially an issue since its part of `eslint-config-airbnb`, granted this file is crazy, but the bug ends up filling the entire file up with thousands of invalid lines

![image](https://user-images.githubusercontent.com/15365418/51068445-e0c78b80-15d2-11e9-865d-17659d123e3e.png)

**Comment by peanutenthusiast** [comment]
I'll look into this.

**Comment by not-an-aardvark** [comment]
Hi @peanutenthusiast, just checking in to see if you've had a chance to work on this.

**Comment by peanutenthusiast** [comment]
@not-an-aardvark  you can expect a PR by tomorrow afternoon/early evening! thank you for your patience

**Comment by zliy** [comment]
another falling case:

```
hello(response =>
  // comment
  response, param => param)
```
=>
```
hello(response => (
  // comment
  response
)), param => (param)
```
