### ISSUE TITLE
'global' override using comments in file ignored

### ISSUE THREAD

**Issue by idahogurl** [eslint/eslint#11260]
**Tell us about your environment**

* **ESLint Version:** 5.12.0
* **Node Version:** 10.15.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "root": true,
  "extends": "airbnb",
  "globals": {
    "window": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018,
    "ecmaFeatures": {
      "jsx": true,
      "modules": true
    }
  },
  "plugins": ["react"],
  "rules": {
    "brace-style": [
      "error",
      "1tbs",
      {
        "allowSingleLine": false
      }
    ],
    "consistent-return": "off",
    "curly": ["error", "all"],
    "import/extensions": "off",
    "import/no-extraneous-dependencies": "off",
    "import/no-unresolved": "off",
    "import/prefer-default-export": "off",
    "import/no-mutable-exports": "off",
    "max-len": "off",
    "no-await-in-loop": "error",
    "no-compare-neg-zero": "error",
    "no-confusing-arrow": "off",
    "no-mixed-operators": "off",
    "no-multi-assign": "off",
    "no-plusplus": "off",
    "no-use-before-define": ["error", { "functions": false, "classes": true }],
    "nonblock-statement-body-position": "error",
    "operator-linebreak": [
      "error",
      "before",
      {
        "overrides": {
          "+=": "after",
          "=": "after"
        }
      }
    ],
    "prefer-arrow-callback": [
      "error",
      {
        "allowNamedFunctions": true,
        "allowUnboundThis": true
      }
    ],
    "prefer-destructuring": "off",
    "prefer-promise-reject-errors": "error",
    "react/jsx-sort-props": "off",
    "react/sort-comp": "off",
    "react/prop-types": ["error", { "skipUndeclared": true }],
    "react/forbid-prop-types": "off",
    "react/jsx-filename-extension": [
      "error",
      {
        "extensions": [".js", ".jsx"]
      }
    ],
    "react/no-array-index-key": "off",
    "react/no-danger": "off",
    "react/prefer-stateless-function": "off",
    "react/react-in-jsx-scope": "off",
    "react/require-default-props": "off",
    "template-tag-spacing": "error"
  },
  "overrides": [
    {
      "files": ["**/__tests__/**/*.js", "**/__mocks__/**/*.js"],
      "env": {
        "jest": true
      },

      "globals": {
        "page": true,
        "browser": true,
        "context": true,
        "jestPuppeteer": true
      }
    },
    {
      "files": [
        "autotest/**/**/*.js"
      ],
      "rules": {
        "no-underscore-dangle": "off"
      }
    },
    {
      "files": ["server/**"],
      "rules": {
        "no-restricted-syntax": [
          "error",
          "ForInStatement",
          "LabeledStatement",
          "WithStatement"
        ]
      }
    }
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* global history, location */
import Router from 'next/router';
import { encodeQueryParams } from './query-params';

export function replaceHash(name) {
  const hash = name ? name.replace(/^#?/, '#') : '';
  if (location.hash === hash) {
    return;
  }

  const url = `${Router.pathname}?${encodeQueryParams(Router.query)}`;
  const as = `${location.pathname}${location.search}${hash}`;
  history.replaceState({ url, as, options: {} }, null, as);
}

```

```bash
eslint --cache --cache-location ./node_modules/.cache/eslint --ignore-path .gitignore --ext .js --ext .jsx .
```

**What did you expect to happen?**
Comments in file would override the **no-restricted-globals** rule

**What actually happened? Please include the actual, raw output from ESLint.**
error  Unexpected use of ‘location’  no-restricted-globals
error  Unexpected use of ‘history’  no-restricted-globals

**Are you willing to submit a pull request to fix this bug?**
I tried tracking it down but I was unsuccessful.

**Comment by idahogurl** [comment]
So it seems this is a feature request since globals only affects `no-undefs`

**Comment by platinumazure** [comment]
Hi @idahogurl, thanks for the issue.

This can be worked around using `overrides` in configuration (basically, for the specified files, you could override the `no-restricted-globals` rule). That said, there are many shortcomings to this workaround (including the fact that you need to list all the other globals you still want to restrict in that overridden configuration).

I don't feel strongly about adding this feature, but I can see it being a quality of life improvement. It could be added as an option to avoid accidentally breaking other users.

Curious to hear what the rest of the team thinks.

**Comment by idahogurl** [comment]
It's tricky because I set them as global because I want to use them no matter what. I know they work without "window." But then again it's good to get some warning/error so I have to think about it.

**Comment by nzakas** [comment]
The `global` directive is meant to say "I am using these global variables, don't mark them as undefined," (think of it as similar to `import` or `var`) whereas the `no-restricted-globals` rule is meant to say, "I noticed you're using a global that you said you didn't want to use." Unless I'm missing something, I think the current behavior makes sense.
