### ISSUE TITLE
Feature: no-inline-comments: Allow exception inside JSX

### ISSUE THREAD

**Issue by alexilyaev** [eslint/eslint#11270]
**What rule do you want to change?**
`no-inline-comments`
**Does this change cause the rule to produce more or fewer warnings?**
Fewer
**How will the change be implemented? (New option, new default behavior, etc.)?**
Rule options, or change in rule behavior
**Please provide some example code that this change will affect:**
```jsx
function App() {
  return (
    <div>
      {/* Some comment */}
      <h1>Some heading</div>
    </div>
  )
}
```

**What does the rule currently do for this code?**
Right now `no-inline-comments` will warn on any comments inside JSX.
**What will the rule do after it's changed?**
It makes sense to allow comments inside JSX while still disallowing inline comments in regular JS blocks.
**Are you willing to submit a pull request to implement this change?**
Unfortunately not.

**Comment by platinumazure** [comment]
Reopening. I'll champion this.

**Comment by g-plane** [comment]
I'd like to add an option called "ignoreJSX".

**Comment by kaicataldo** [comment]
@platinumazure @g-plane It sounds like we have two different implementation ideas here (assuming @platinumazure was championing something in neighborhood of what I was suggesting). How should we proceed?

**Comment by platinumazure** [comment]
I don't feel strongly either way. I would be okay with an option, but I also note that this rule is pretty much unusable in JSX without the new option and I think we could easily avoid a breaking change in non-JSX code even if we change the default behavior.

**Comment by kaicataldo** [comment]
The current behavior in JSX does feel like a bug to me, and I would be okay with changing the behavior by default for JSX as long as other cases aren't affected. If we make this change, I do think we should note the reasoning for this exception in the docs. It would be even better if we could get this into v6!

**Comment by kaicataldo** [comment]
@eslint/eslint-team Looks like we need one more :+1: or it might be time to close this issue. @platinumazure are you still championing this change?

**Comment by jumpconnector** [comment]
+1 on this. There should be an option to allow exception on comments inside JSX

**Comment by platinumazure** [comment]
@kaicataldo Yes, I'll champion still. I'll poke in the team chat for another :+1: from the team :smile:

**Comment by dorian-marchal** [comment]
> Looks like we need one more :+1:

+1 :+1:

**Comment by platinumazure** [comment]
Thanks @dorian-marchal... We're looking for a :+1: from a member of the ESLint team. (Please review our [consensus process](https://eslint.org/docs/maintainer-guide/issues#consensus) for more context.)

**Comment by mdjermanovic** [comment]
I'm working on this.
