### ISSUE TITLE
Expose a rules dictionary keyed by ruleId to formatters

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [eslint/eslint#11273]
v5.11.1

My custom formatter outputs the SARIF format which is designed to be completely self-contained, and provides an affordance for rule metadata. This property is implemented as a dictionary, keyed by ruleId. All of the metadata fields in ESLint's Rule object are useful in a SARIF log.

A dictionary makes sense as the data structure. I'm not too familiar with ESLint's architecture, so I can't speak to the manner in which the dictionary would be exposed. One thought would be to pass it is a parameter to the formatter, so there is just one instance and custom rules could be included.

Yes.

**Comment by nzakas** [comment]
Thanks for opening the issue. This seems like it could be helpful for a lot of formatters, so I'd be in favor of such a change.

I think the larger question is how to do this correctly. In the past we've discussed adding information into results that are passed in to a formatter, but that ultimately results in a lot of duplication of information. So, it seems like the right approach would be to pass in a second argument to a formatter with this information.

As this would be a core change, it does fall under our [RFC process](https://github.com/eslint/rfcs). If you'd like to try writing up the RFC, please feel free. If not, I can take that on, but it might take me a couple of weeks. (Of course, anyone reading this an interested is free to submit an RFC, it doesn't have to be just you or me.)

Related issues: https://github.com/eslint/eslint/issues/9841

**Comment by EasyRhinoMSFT** [comment]
Agree on the parameter approach. I'll take a crack at the RFC.
Thanks!

**Comment by not-an-aardvark** [comment]
(For anyone coming across this issue later: this feature is being discussed in https://github.com/eslint/rfcs/pull/10.)
