### ISSUE TITLE
html attribute in vue : eslint raises error "defined but never used"

### ISSUE THREAD

**Issue by liteultom** [eslint/eslint#11286]
**Tell us about your environment**

* **Platform: Linux Ubuntu 16.04LTS**
* **VS Code version: 1.29.1**

* **ESLint Version: 1.7.2**
* **Node Version: 8.12.0**
* **npm Version: 6.4.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module'
  },
  env: {
    browser: true
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/essential',
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  globals: {
    'ga': true, // Google Analytics
    'cordova': true,
    '__statics': true
  },
  // add your custom rules here
  'rules': {
    // allow async-await
    'generator-star-spacing': 'off',

    // allow paren-less arrow functions
    'arrow-parens': 0,
    'one-var': 0,

    'import/first': 0,
    'import/named': 2,
    'import/namespace': 2,
    'import/default': 2,
    'import/export': 2,
    'import/extensions': 0,
    'import/no-unresolved': 0,
    'import/no-extraneous-dependencies': 0,

    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Note : it's in a `.vue` file, in the template part
```html
<template slot="top-left" slot-scope="props">
    <div>Hello there</div>
</template>
```

Not sure, it's running inside VSCode

**What did you expect to happen?**
No error
Note : it was note raising any error the last time I opened this project about 2 month ago. the ` slot-scope="props"` is necessary for quasar-framework to know where to put the element, but I  don't use `props` myself

**What actually happened? Please include the actual, raw output from ESLint.**
[eslint-plugin-vue]
[vue/no-unused-vars]
'props' is defined but never used

**Are you willing to submit a pull request to fix this bug?**
Not sure how to fix it

Maybe similar to [https://github.com/eslint/eslint/issues/11280](https://github.com/eslint/eslint/issues/11280)

**Comment by g-plane** [comment]
Hey @liteultom , thanks for the issue.

The reported error is from `eslint-plugin-vue`, not ESLint itself. You can consider open issue in the repository of `eslint-plugin-vue` or `quasar-framework`.

For workaround, you can add a line of HTML comment `<!-- eslint-disable-next-line vue/no-unused-vars -->` above your code or `<!-- eslint-disable-line vue/no-unused-vars -->` with the same line of attribute `slot-scope`.

**Comment by liteultom** [comment]
Thank you for your answer, I will look for the specific `eslint-plugin-vue` repository

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
