### ISSUE TITLE
'no-unused-vars' rule doesn't consider 'arguments' object

### ISSUE THREAD

**Issue by johnd0e** [eslint/eslint#11280]
**Tell us about your environment**

* **ESLint Version:** 5.12.0
* **Node Version:** 8.11.3
* **npm Version:** 6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** `.eslintrc.json`

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "browser": true
    },
    "extends": "eslint:recommended",
        "ecmaVersion": 5
    },
    "rules": {
         "no-console": 0
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
(function(a,b,c){a=0;console.log(arguments)}(1,2,3))
```

```bash
eslint sample.js
```

**What did you expect to happen?** no errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
  1:11  error  'a' is assigned a value but never used         no-unused-vars
  1:13  error  'b' is defined but never used                  no-unused-vars
  1:15  error  'c' is defined but never used                  no-unused-vars
```

**Are you willing to submit a pull request to fix this bug?** No

**Comment by g-plane** [comment]
Hi @johnd0e , thanks for opening this issue.

There is no doubt that you can access the value of `a`, `b` and `c` via `arguments`, but actually, you just visiting the `arguments` object itself, not visiting the arguments directly. So, this may not be a bug. (I don't mind hearing different opinions.)

**Comment by johnd0e** [comment]
I agree that is not just bug, perhaps it's just special case which wasn't handled by now.

I would be great if `eslint` could track `arguments` access as well.
In general we could consider `a`,`b`,`c` as properties of `arguments` object, so I expect similar handling.

Of course one could wish different behavior in this case, so additional configuration's options required I suppose.
