### ISSUE TITLE
Deprecated dependency

### ISSUE THREAD

**Issue by prettydiff** [eslint/eslint#11285]
https://github.com/prettydiff/prettydiff/issues/564

    ares /usr/local/src/prettydiff # npm install eslint -g
    npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
    /usr/bin/eslint -> /usr/lib/node_modules/eslint/bin/eslint.js
    + eslint@5.12.0
    added 116 packages from 70 contributors in 26.613s
    ares /usr/local/src/prettydiff #

**Comment by ljharb** [comment]
Duplicate of #11052.
