### ISSUE TITLE
Cannot read property 'replace' of undefined Use --force to continue

### ISSUE THREAD

**Issue by phani17c** [eslint/eslint#11290]
So I want to add some eslint rules for promises, then I found "eslint-plugin-promise version". And after installing that through npm, I have added "promise" to my plugins array and 
promise/no-callback-in-promise: "error" to my rules object. But I am getting the below error.

Warning: Cannot read property 'replace' of undefined Use --force to continue.

Any help would be appreciated.

* **ESLint Version:** 5.12.0
* **Node Version:** 8.0.0
* **npm Version:** 5.x
* **eslint-plugin-promise version:** "4.0.1"

package.json
`eslint-plugin-promise version: "4.0.1"`

.eslintrc
`
plugins: ["promise"]
rules : {
"promise/no-callback-in-promise": "error"
}
`

Step Js file for cucumber

`this.Given(/^something...$/, function(callback){
...
callback();
}`

As the above code is not a good practice, I want to add a eslint rule which already there in "eslint-plugin-promise" --> promise/no-callback-in-promise: "error"

when I run eslint
this is the error in the terminal

`Warning: Cannot read property 'replace' of undefined Use --force to continue.`

**Comment by phani17c** [comment]
@not-an-aardvark , @eslint[bot] updated my description

**Comment by not-an-aardvark** [comment]
It looks like you still haven't provided enough information to figure out what's going on, as requested by the bot. Could you please provide:

* What you did (the source code you're running ESLint on, and the ESLint configuration file)
* The actual ESLint output complete with numbers (is there a stack trace along with the error?)

**Comment by phani17c** [comment]
@not-an-aardvark I think I went in a wrong direction as this is really related to cucumber but I went for promise. Dont know I might be wrong at this assumption. thanks for your resposne

Closing this!
