### ISSUE TITLE
object-shorthand: autofix breaks first arrow function in default parameter

### ISSUE THREAD

**Issue by MayhemYDG** [eslint/eslint#11305]
**Tell us about your environment**

* **ESLint Version:** 5.12.1
* **Node Version:** 11.7.0
* **npm Version:** 6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`, `@typescript-eslint/parser`, and the default parser.
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    "ecmaVersion": 6
  },
  rules: {
    'object-shorthand': [1, "always", { avoidExplicitReturnArrows: true }]
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var test = {
  key0: function(arg) {},
  key1: (arg) => {},
  key2: (arg = () => {}) => {},
  key3: (arg1 = () => {}, arg2 = () => {}) => {}
}
```

```bash
eslint --fix --ext js,jsx,ts,tsx --max-warnings 0 -f codeframe --cache --color src
```

**What did you expect to happen?**
Autofix should have been:
```js
var test = {
  key0(arg) {},
  key1(arg) {},
  key2(arg = () => {}) {},
  key3(arg1 = () => {}, arg2 = () => {}) {}
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
Autofix gives invalid syntax:
```js
var test = {
  key0(arg) {},
  key1(arg) {},
  key2(arg = () {}) => {},
  key3(arg1 = () {}, arg2 = () => {}) => {}
}
```
Command output:
```
error: Parsing error: Unexpected token ) at src\file.js:4:15:
  2 |   key0(arg) {},
  3 |   key1(arg) {},
> 4 |   key2(arg = () {}) => {},
    |               ^
  5 |   key3(arg1 = () {}, arg2 = () => {}) => {}
  6 | }
  7 |


1 error found.
```

**Are you willing to submit a pull request to fix this bug?**
No, but @platinumazure might have some thoughts about this.

**Comment by platinumazure** [comment]
It looks like the issue is we find and remove the [first arrow token in the object value](https://github.com/eslint/eslint/blob/7ad86dea02feceb7631943a7e1423cc8a113fcfe/lib/rules/object-shorthand.js#L258), which could find an arrow token in a default parameter:

```js
const arrowToken = sourceCode.getTokens(node.value).find(token => token.value === "=>");
```

Instead, I think we should be looking for the last arrow token before the body node. Something like:

```js
// Note: We know we're in an ArrowFunctionExpression already
const arrowToken = sourceCode.getTokenBefore(node.value,body, { filter: token => token.value === "=>" });
```

There might be a bit more to it, but I'm hoping that will do the job for most cases.

**Comment by abubuker** [comment]
Than You
