### ISSUE TITLE
Better crash reporting

### ISSUE THREAD

**Issue by alexzherdev** [eslint/eslint#11304]
**The version of ESLint you are using.**
5.12

**The problem you want to solve.**
When a rule crashes for any reason, it can be difficult for the users to determine which source file caused the crash - especially if they are running ESLint from the command line on a big project. We're [encountering](https://github.com/yannickcr/eslint-plugin-react/issues/1974) [this](https://github.com/yannickcr/eslint-plugin-react/issues/2095) [very](https://github.com/yannickcr/eslint-plugin-react/issues/2108) [often](https://github.com/yannickcr/eslint-plugin-react/issues/1881) after releases in eslint-plugin-react and frequently have to ask for reproduction code.

I'm filing this to double-check if anything can be done in ESLint core to improve on this.

**Your take on the correct solution to problem.**
 It'd be ideal if before the stack trace we could output the source file name and line number that caused the crash, although I imagine at that point it wouldn't be too hard to output the actual code on that line. I'm not sure if this can be achieved within ESLint's architecture, which I'm not familiar with.

**Are you willing to submit a pull request to implement this change?**
Yes, although again I'm not familiar with the ESLint codebase.

**Comment by alexzherdev** [comment]
Just tried that flag - here's what it looks like on ESLint 5.12.1:
```
  eslint:linter Linting code for /Users/.../file.js (pass 1) +0ms
  eslint:linter An error occurred while traversing +2s
  eslint:linter Filename: /Users/.../file.js +0ms
  eslint:linter Parser Options: { ecmaFeatures:
   { globalReturn: false,
     ...
     experimentalObjectRestSpread: true },
  ecmaVersion: 7,
  sourceType: 'module' } +0ms
  eslint:linter Parser Path: /Users/.../node_modules/babel-eslint/lib/index.js +1ms
  eslint:linter Settings: { 'import/resolver':
   { node: { extensions: [Array] },
     webpack: { config: 'webpack.dev.config.js' } },
  'import/extensions': [ '.js', '.mjs', '.jsx' ],
  ...
  propWrapperFunctions: [ 'forbidExtraProps', 'exact', 'Object.freeze' ] } +0ms
Cannot read property 'split' of undefined
MBP15:src admin$
```
On ESLint 4.19 it's just
```
  eslint:linter Linting code for /Users/.../file.js (pass 1) +0ms
Cannot read property 'split' of undefined
MBP15:src admin$
```

So it does output the file name, which is good. I guess we could direct users to use the `--debug` flag, although it'd be nice to output the file name without the flag if we're going to crash, to avoid the back-and-forth.
cc @ljharb

**Comment by not-an-aardvark** [comment]
Isn't all of that information already inferable from the stack trace?

**Comment by ljharb** [comment]
The trace is from where it threw; it tells you nothing about which code it threw on.

**Comment by not-an-aardvark** [comment]
Sorry, I misunderstood (I thought by "the file and line it crashed on" you meant the rule file).

I think it would be reasonable to always include the target filepath that caused the crash in the error message. However, I don't think it's possible to determine the line of the target filepath that caused the crash.

**Comment by ljharb** [comment]
Surely the ast node’s location, for the visitor that crashed, is available?

**Comment by not-an-aardvark** [comment]
We could report the AST node's location, which would help in some cases. But it could often turn out that the crash was a result of some corrupted state from some previous point in the file, which only resulted in an error being thrown at a normal-looking AST node.

For example, if a rule's logic is "given some variable reference, iterate over all places where the variable was assigned", and one of the assignments does something that causes the rule to crash, then the crash might occur in the visitor where the variable is read, even though the actual cause of the crash is in the node where the variable is assigned.

**Comment by ljharb** [comment]
That doesn't matter; the point in the source code at which the crash occurred is invaluable in determine why the rule code crashed.

**Comment by not-an-aardvark** [comment]
Sounds reasonable, I'd be fine with improving the error message to include that info if anyone wants to create a PR. (Since this just modifies an error message for debugging and doesn't have semver impact, I don't think this would need TSC approval.)

It would probably be better to add this information to the error object that gets thrown from `Linter` (rather than adding `console.error` statements), to ensure that the info can be used and doesn't spam the console when running ESLint from an integration.

**Comment by alexzherdev** [comment]
Ok, I'm taking a stab at this. A couple of clarifying questions:
- is it enough to just add the line number of the node's starting location? (we already have the file name in the output)
- do we still want to output this information only when `--debug` is set? I feel like this flag is not widely known, but I also don't fully understand the consequences of outputting it without that flag. Perhaps as long as it's not `--quiet`, it could be fine?

**Comment by ljharb** [comment]
I would prefer to see both the code’s filename and line number *always*, without exception.

**Comment by ljharb** [comment]
It’d be great to reopen this; this impacts the entire plugin ecosystem.

**Comment by not-an-aardvark** [comment]
@alexzherdev Sorry, I missed your questions. Thanks for working on this!

> is it enough to just add the line number of the node's starting location? (we already have the file name in the output)

I agree with @ljharb that outputting both the line number and the filename is worthwhile in the event of a crash, regardless of whether the `--debug` flag is enabled.

> do we still want to output this information only when --debug is set? I feel like this flag is not widely known, but I also don't fully understand the consequences of outputting it without that flag. Perhaps as long as it's not --quiet, it could be fine?

Given that this only applies when something has crashed, I think it's fine to add lots of debugging information regardless of whether a flag like `--quiet` is in use.

---

To reiterate https://github.com/eslint/eslint/issues/11304#issuecomment-456941005, I think this would involve adding information to a thrown error object rather than adding something like `console.error`, so I don't think it should be conditional on whether debug mode is enabled.

**Comment by alexzherdev** [comment]
Sounds good. I understand this is impactful and I’ll try to find time to complete this 👍
I think I had questions around testing this when I first looked into it, but to start I’ll do a PR when I have something to show.
