### ISSUE TITLE
React: Inline If with Logical && Operator

### ISSUE THREAD

**Issue by OZZlE** [eslint/eslint#11313]
https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

**The version of ESLint you are using.**
5.6.0

**The problem you want to solve.**
Passing eslint without ignore and not outputting random numbers.

If I do:

    {item.url.length && (
      <a href={item.url}>
        {item.title}
      </a>
    )}
    {!item.url.length && (
      <span
        style={this.getStyleItemText()}
        onClick={this.onItemClick}
        onKeyDown={this.onItemClick}
        role="button"
        tabIndex={0}
      >
        {item.title}
      </span>
    )}

Result: when false it outputs the length in the dom, in this case 0.
![skarmklipp 2019-01-24 08 55 50](https://user-images.githubusercontent.com/893783/51663050-f4e99080-1fb5-11e9-80da-7f7707539793.png)

If I do:

    {item.url.length && (
      <a href={item.url}>
        {item.title}
      </a>
    ) || ''}
    {!item.url.length && (
      <span
        style={this.getStyleItemText()}
        onClick={this.onItemClick}
        onKeyDown={this.onItemClick}
        role="button"
        tabIndex={0}
      >
        {item.title}
      </span>
    ) || ''}

Result: `error  Unexpected mix of '&&' and '||'  no-mixed-operators`

**Your take on the correct solution to problem.**
Somehow allow mixing of operators in Inline If Logical statements

**Are you willing to submit a pull request to implement this change?**
Not sure if I am able and will have time :/

**Comment by g-plane** [comment]
Hey @OZZlE , thanks for the issue. Which rule and what behavior you'd like to change?

**Comment by OZZlE** [comment]
@g-plane "no-mixed-operators" is the rule: https://eslint.org/docs/rules/no-mixed-operators

to change it so it's allowed in "Inline If with Logical && Operator": https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

**Comment by OZZlE** [comment]
@g-plane I figured out a solution without needing to change eslint at all :) I just used `!!` :)

    {!!item.url.length && (
      <a href={item.url} style={this.getStyleItemText()}>
        {item.title}
      </a>
    )}
    {!item.url.length && (
      <span
        style={this.getStyleItemText()}
        onClick={this.onItemClick}
        onKeyDown={this.onItemClick}
        role="button"
        tabIndex={0}
      >
        {item.title}
      </span>
    )}

**Comment by OZZlE** [comment]
problem was that if `item.url.length` was `0` then it's falsy so the part after the `&&` won't execute and the `{}` gets the `0` so it outputs it. By using `!!` it converts the zero into boolean `false` which won't be outputted
