### ISSUE TITLE
Support regex literal for config properties that accept regex string

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#11318]
**Description**

Would be nice to be able to use regex literals to not have to double-escape certain characters when using JS-based ESLint config.

###### Before

```js
'no-unused-vars': [
	'error',
	{
		argsIgnorePattern: '^_$'
	}
]
```

###### After

```js
'no-unused-vars': [
	'error',
	{
		argsIgnorePattern: /^_$/
	}
]
```

This would apply to all rule options that currently supports a regex string.

It also means it becomes syntax highlighted and when linting the config file itself, some incorrect regex patterns can be detected by linter rules.

**Are you willing to submit a pull request to implement this change?**

No

**Comment by g-plane** [comment]
Can `Ajv` accept regex literal?

**Comment by sindresorhus** [comment]
No, but ESLint can define a custom keyword: https://github.com/epoberezkin/ajv/issues/101#issuecomment-173516325

**Comment by nzakas** [comment]
Thanks for the suggestion. In the current configuration system, we don't have different acceptable types between the different configuration file formats, and I'm not sure we'd want to introduce one here. We could certainly look at doing this if/when https://github.com/eslint/rfcs/pull/9 becomes a reality.

In the meantime, do you have a list of rules and options this would apply to? We have over 200 rules, so it would be helpful to know how many rules and options would be affected.

**Comment by sindresorhus** [comment]
I went through the the documentation for all the rules and these are the ones with regex options:

- https://eslint.org/docs/rules/default-case
- https://eslint.org/docs/rules/dot-notation
- https://eslint.org/docs/rules/no-fallthrough
- https://eslint.org/docs/rules/no-unused-vars
- https://eslint.org/docs/rules/handle-callback-err
- https://eslint.org/docs/rules/capitalized-comments
- https://eslint.org/docs/rules/id-match
- https://eslint.org/docs/rules/line-comment-position
- https://eslint.org/docs/rules/lines-around-comment
- https://eslint.org/docs/rules/max-len

**Comment by not-an-aardvark** [comment]
Another option would be to automatically convert regexes to strings as part of config processing, so that individual rules wouldn't need to make changes. So rules would still only accept strings as options, but the user could provide that string in a JS config by using a regex and having it automatically be converted.

**Comment by sindresorhus** [comment]
@not-an-aardvark @nzakas @g-plane Can you please re-open?
