### ISSUE TITLE
Issue in using custom rules

### ISSUE THREAD

**Issue by jankhunter** [eslint/eslint#11327]
**Tell us about your environment**

* **ESLint Version:** v5.12.1
* **Node Version:** v8.9.0
* **npm Version:** 5.8.0

```bash
eslint filename
```

**What did you expect to happen?**
I have configured the rule properly in eslintrc.js. I have copied the rule file into the root directly where the eslint installed ( /usr/local/lib/node_modules/eslint/lib/rules ). 

I expect the Eslint to work properly with all the custom rules included. Actually it was working fine till the last version. 

**What actually happened? Please include the actual, raw output from ESLint.**
When i run the command, 'eslint filename', i am getting the error as "Definition for rule 'rulename' was not found" for all the custom rules..

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by not-an-aardvark** [comment]
Hi, thanks for reporting an issue. Copying a rule file into `/usr/local/lib/node_modules/eslint/lib/rules` isn't a supported way to use custom rules. I would recommend using the [`--rulesdir`](https://eslint.org/docs/user-guide/command-line-interface#--rulesdir) CLI option instead.
