### ISSUE TITLE
[Feature request] maxLen auto fix

### ISSUE THREAD

**Issue by TheJaredWilcurt** [eslint/eslint#11325]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**
There is a rule to set max length of a line (defaulting to 80 characters). However this rule does not offer an auto-fix option. This is a feature currently in Prettier.

**Your take on the correct solution to problem.**
none

**Are you willing to submit a pull request to implement this change?**
no

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. Could you go into more detail on how this would work? How would the `max-len` rule decide where to insert a linebreak to prevent lines from being too long?

Keep in mind that the user might also have other stylistic rules enabled regarding where linebreaks should appear, including stylistic rules from third-party plugins.

**Comment by not-an-aardvark** [comment]
(Sorry, I inadvertantly hit the "close and comment" button rather than the "comment" button. Just reopened this issue.)

**Comment by g-plane** [comment]
@not-an-aardvark You can use [refined-github](https://github.com/sindresorhus/refined-github) to prevent this. (It will move "Close and comment" button away from "Comment" button.)

**Comment by TheJaredWilcurt** [comment]
I don't have any strong opinions on how the implementation of this should work.

I think it makes since to format objects where each key/value are on their own lines and follow the other formatting rules for quotes and indentation. break up methods and functions to their own lines in a logical manner. Split up variable declarations to one per line. split up arrays to have one item per line (except for objects that would take up multiple lines).

Using the example from [the docs](https://eslint.org/docs/rules/max-len);

```js
var foo = { "bar": "This is a bar.", "baz": { "qux": "This is a qux" }, "difficult": "to read" }; // very long
```

Auto-fix would convert it to this, then apply any other formatting settings fixes (like indentation).

```js
// very long
var foo = {
  "bar": "This is a bar.",
  "baz": {
    "qux": "This is a qux"
  },
  "difficult": "to read"
};
```

Even if it's a rudimentary implementation that still results in there being max-length too long error (like if `foo.baz.qux`'s value was a very long string). That would at least format most of the object/method/function/array for you, and more improvements can be made to the auto-fixer in the future.

**Comment by aladdin-add** [comment]
I'm slightly opposed to add the autofix:
+ it can be very subjective how to do the fix.
+ it might cause conflicts with some core rules: [array-bracket-newline](https://eslint.org/docs/rules/array-bracket-newline), [array-element-newline](https://eslint.org/docs/rules/array-element-newline)

**Comment by TheJaredWilcurt** [comment]
Well same logic still applies. Break it up into new lines, then apply the auto fix for `array-bracket-newline`, `array-element-newline`, indentation, etc. And if at the end there is still a `max-len` that couldn't be auto-fixed, then output the warning/error. It would still fix most `max-len` errors and the ones that are left can be dealt with by hand. Which is better than having to deal with all of them by hand.

**Comment by aladdin-add** [comment]
just to be clear: `array-bracket-newline` has a "always"/"never" option, enforces have/**have no** linebreaks. and the example you given might be fixed with "always" option.

**Comment by TheJaredWilcurt** [comment]
Max line length can be caused by anything, not just arrays. The auto-fix for this should take lowest priority. If users have other rules that may conflict, they should take higher priority. But not everyone has those other rules, and for those scenarios it would be more convenient for ESLint to be able to auto fix this rule as best it can.

**Comment by platinumazure** [comment]
@TheJaredWilcurt I lean towards agreeing with the team that this autofix is probably, in general, unsafe and/or could cause conflicts with other rules. That said, I'm open to persuasion that this could maybe be done safely. Can you offer a more concrete proposal for exactly how you think the autofix should work on this case (i.e., how would line breaks be determined, where would excess text be moved, account for edge cases like comments, etc.)? If there's a reasonably safe way it could be done that won't conflict with other rules, I'll support that proposal.

**Comment by EarthyOrange** [comment]
Wouldn't the following work?
```
const eg = 'long long long';
const eg = 'long'
           + 'long'
           + 'long';
```

**Comment by platinumazure** [comment]
@EarthyOrange Thanks for the idea. Your example would not result in equivalent strings; additionally, this wouldn't work for long strings with no whitespace, so you need something that can handle those types of strings.

Please feel free to work some more on your proposal and then open a new issue when you think you have something concrete (which can handle long strings, comments, URLs, long numbers or words such as digits of pi or DNA base sequences, etc.). That said, I personally think the code would become really complicated and inconvenient to maintain without generating a lot of value for our users.
