### ISSUE TITLE
Line 2:  Parsing error: Unexpected token, expected ";"

### ISSUE THREAD

**Issue by gitvivekgupta** [eslint/eslint#11351]
**Tell us about your environment**

* **Node Version: 11.5.0
* **npm Version: 6.7.0

```js

import React, { Component } from 'react';
import 'FileUpload' from './FileUpload'; **Error is shown in this line**

class App extends Component {
  render() {
    return (
      <div>
        <h2> File upload </h2>
        <FileUpload />
      </div>
    );
  }
}

export default App;

```

**Error**

./src/App.js
  Line 2:  Parsing error: Unexpected token, expected ";"

  1   | import React, { Component } from 'react';
> 2 | import 'FileUpload' from './FileUpload';
      |                     ^
  3  | 
  4  | class App extends Component {
  5  |   render() {

**Comment by aladdin-add** [comment]
do you want `import FileUpload from './FileUpload';`(FileUpload not quoted)?
