### ISSUE TITLE
improve the UX of linting typescript

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11368]
**The version of ESLint you are using.**
n/w

**The problem you want to solve.**
I've seen some devs didn't know how to lint typescript using eslint.
After looking through the docs, I found very little content about it(and some are outdated https://eslint.org/docs/user-guide/configuring#specifying-parser).

**Your take on the correct solution to problem.**
- [x] update outdated docs. (https://github.com/eslint/eslint/pull/11369)
- [ ] add a para: "working with typescript".
- [x] support `eslint --init` typescript repos.

**Are you willing to submit a pull request to implement this change?**
partly.

**Comment by kaicataldo** [comment]
@aladdin-add @g-plane It looks like a PR was merged but it's not clear what the plan is here. Mind filling us in?

**Comment by g-plane** [comment]
@kaicataldo I've update this issue for adding a check list to track on the progress.

**Comment by g-plane** [comment]
Do we need an RFC for supporting TypeScript in configuration initializer?

**Comment by ilyavolodin** [comment]
@g-plane No, I don't think so, config initializer is not really part of the core, so changes there shouldn't require RFC, just an issue with support from the team.

**Comment by kaicataldo** [comment]
I believe this is now complete!
