### ISSUE TITLE
no-unneeded-ternary should have a no-useless-ternary alias for consistency sake

### ISSUE THREAD

**Issue by Mouvedia** [eslint/eslint#11367]
**The version of ESLint you are using.**
5.4.0

**The problem you want to solve.**
missing alias

**Your take on the correct solution to problem.**
add no-useless-ternary as an alias to no-unneeded-ternary

This would be consistent with:

- no-useless-call
- no-useless-catch
- no-useless-concat
- no-useless-escape
- no-useless-return
- no-useless-computed-key
- no-useless-constructor
- no-useless-rename

**Are you willing to submit a pull request to implement this change?**
N/A

PS: while you are at it check #8211

**Comment by kaicataldo** [comment]
@Mouvedia Since `no-unneeded-ternary` isn't deprecated, it sounds like you're suggesting the rule is renamed to `no-useless-ternary` (done in a backwards-compatible way). Mind confirming that that's correct?

**Comment by Mouvedia** [comment]
That's correct.

**Comment by not-an-aardvark** [comment]
Personally, I don't think this inconsistency is enough of an issue to merit renaming rules/dealing with aliases. It's not ideal but I don't think it's causing any big problems either.

**Comment by Mouvedia** [comment]
There are precedents.
e.g. #6586

**Comment by Mouvedia** [comment]
.
