### ISSUE TITLE
Switch browserify to webpack or other bundler

### ISSUE THREAD

**Issue by g-plane** [eslint/eslint#11366]
**The problem you want to solve.**
Browserify isn't under active development. Should we consider switching to webpack or other bundler?

This not only relates browserify only, but also other build tool. For example, we can use `babel-loader` or `rollup-plugin-babel` instead of `babelify`.

**Your take on the correct solution to problem.**
1. Remove browserify from the build steps of ESLint.
2. Add webpack or other bundler.
3. Update the Karma config, and use some preprocessors if necessary.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by ilyavolodin** [comment]
ESLint doesn't currently compile out of the box when using webpack or rollup (as far as I know). It needs some tweaking. Not really sure it's worth the change, since we only support web build for the website, and that works perfectly fine for now. But if you want to investigate - that's fine by me.

**Comment by g-plane** [comment]
webpack has a concept of "mode" now, which simpilifies the configuration.

**Comment by ilyavolodin** [comment]
"mode" is just a bundled set of configuration settings for debugging vs. production, so I'm not sure how this is going to help. What wasn't working, as far as I remember is loading rules from the file system.

**Comment by g-plane** [comment]
We can generate a JavaScript for loading rules when building with bundler.

**Comment by kaicataldo** [comment]
There's been some previous discussion about this (see https://github.com/eslint/eslint/issues/9478), but it looks like discussion stalled. I would be all for switching out browserify in favor Webpack. It sounds like @g-plane is willing to do this work and I'd also be willing!

**Comment by nzakas** [comment]
There is an approved PR for this change: https://github.com/eslint/eslint/pull/11398

Are we comfortable with marking this issue as accepted and merging the PR?

**Comment by aladdin-add** [comment]
Agreed. we had 5+ 👍 from the team members, and seems no objections.
