### ISSUE TITLE
Module not found: Error: Can't resolve 'module' in '\node_modules\eslint\lib\util'

### ISSUE THREAD

**Issue by VasilisNikiforidis** [eslint/eslint#11376]
Hi, I tried importing ESlint into my vue file, in which I try to build a code editor using Monaco Editor, where I want to integrate ESlint. 
I was thinking of importing ESlint to my file and then, with a worker, verify the code a user writes on the editor. I simply tried the following:
`import ESLint from '../../node_modules/eslint'
`
and I keep getting the errors: 
`./node_modules/eslint/lib/rules.js
Module not found: Error: Can't resolve '../conf/replacements' in 'C:\............\node_modules\eslint\lib'`

`./node_modules/eslint/lib/util/module-resolver.js
Module not found: Error: Can't resolve 'module' in 'C:\................\node_modules\eslint\lib\util'`

`./node_modules/eslint/node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in 'C:\...................\node_modules\eslint\node_modules\resolve-from'`

I fixed the 1st one by going into the rules.js and changing const `ruleReplacements = require("./conf/replacements").rules; ` to `const ruleReplacements = require("../conf/replacements.json").rules;`.

But I cannot do anything for the other 2 since the problem is at : 
`const Module = require("module");`
and I cannot find anything named "module" in my eslint folder.

Any suggestions are welcome

**Comment by ilyavolodin** [comment]
ESLint does not officially support web browsers as a platform. However, you can take a look at our makefile to see how we build web-compatible version of ESLint for our demo.

**Comment by mysticatea** [comment]
Maybe you can use https://www.npmjs.com/package/eslint4b and https://www.npmjs.com/package/vue-eslint-editor :smile:

**Comment by VasilisNikiforidis** [comment]
@mysticatea Thanks for the suggestions I will look into eslint4b for sure. The other one though is, by my undestanding, eslint to be used on vue files. What I want is to load eslint into my vue file to use for the code editor I am creating, not to lint the vue file itself.

**Comment by mysticatea** [comment]
> Thanks for the suggestions! I have looked into eslint4b, but I was getting a message `Cannot find module 'babel-eslint'.` (I had babel-eslint as the set parser option in my eslintrc file).

You have to define the parser manually because dynamic loading is not supported in `eslint4b`. `Linter` class has [defineParser](https://eslint.org/docs/developer-guide/nodejs-api#linterdefineparser) method.

> The other one though is, by my undestanding, eslint to be used on vue files. What I want is to load eslint into my vue file to use for the code editor I am creating, not to lint the vue file itself.

https://mysticatea.github.io/vue-eslint-editor/ is an example that uses ESLint and Monaco editor together, so I introduced it for a reference.

>could you point me to the demo files, cause I cannot seem to find them.

https://github.com/eslint/eslint.github.io/tree/master/js/app/demo

**Comment by mysticatea** [comment]
For a reference, this is an example to define a parser and plugin rules: https://github.com/mysticatea/typescript-eslint-demo/blob/c84e882a4590aed863bda9264105914b2706369e/src/lib/eslint.js

**Comment by VasilisNikiforidis** [comment]
@mysticatea Thanks these are a great help, I really appreciate it!

**Comment by nzakas** [comment]
It looks like this question has been answered, so closing. If you need help in the future, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
