### ISSUE TITLE
Incomplete documentation on http://eslint.org/docs/developer-guide/working-with-rules.html

### ISSUE THREAD

**Issue by brandyn1bennett** [eslint/eslint#1137]
The 'context' object that is passed in to all of the rules is missing some documentation about it's functions.  If I console.log(context) I see the following functions without any documentation:

*  getSourceLines
*  getTokens
*  getTokensBefore
*  getTokenBefore
*  getTokensAfter
*  getTokenAfter
*  getFirstTokens
*  getFirstToken
*  getLastTokens
*  getLastToken
*  getAncestors
*  getScope
*  getJSDocComment
*  getFilename

Some these functions are being used in some of the rules, but I can't find any documentation on how to use them and what parameters, if any, they take.

**Comment by nzakas** [comment]
Documentation updated in 4c38981d as part of #1330.
