### ISSUE TITLE
Rule proposal: Use regex Unicode property escapes

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#11382]
**Please describe what the rule should do:**

Enforce using regex [Unicode property escapes](http://2ality.com/2017/07/regexp-unicode-property-escapes.html) instead of classic escapes whenever possible, as Unicode property escapes improve readability.

This rule could be auto-fixable.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[x] Suggests an alternate way of doing something (suggestion)
[ ] Enforces code style (layout)
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

`/^\s+$/u` → `/^\p{White_Space}+$/u`

`/^\d+$/u` → `/^\p{Decimal_Number}+$/u`

**Why should this rule be included in ESLint (instead of a plugin)?**

It's a native JS feature and ESLint already has some other regex-related rules.

**Are you willing to submit a pull request to implement this rule?**

No

**Comment by maxnordlund** [comment]
One thing to keep in mind is that the unicode property escapes may not directly translate to the classic ones. For example, word characters `\w` is the same as `[A-Za-z0-9_]`, but the unicode recommendation for [\w](https://unicode.org/reports/tr18/#word) includes much more.

This is a good resource for this IMHO: https://mathiasbynens.be/notes/es-unicode-property-escapes
