### ISSUE TITLE
eslint comments to enable/disable not respecting order specified in code

### ISSUE THREAD

**Issue by j3tan** [eslint/eslint#1139]
```
/*eslint camelcase: 0*/
var queryParams = {
    first_param: 'foo'
};
queryParams.second_param = 'bar';
/*eslint camelcase: 1*/
```

```
  3:1   warning  Identifier 'first_param' is not in camel case   camelcase
  5:12  warning  Identifier 'second_param' is not in camel case  camelcase
✖ 2 problems
```

It looks like the second `/*eslint*/` comment takes precedence. Default rule is `camelcase: 2`. If I remove the second `/*eslint*/` comment, no errors are thrown.

Use Case: Legacy APIs sometimes use underscores for params.

I've also verified this is the case with other rules as well.

**Comment by calidion** [comment]
seems not working for me.

**Comment by platinumazure** [comment]
@caldion Please open a new issue and follow the instructions in the issue template to provide us with the information we need to help you out. Thanks!

**Comment by calidion** [comment]
@platinumazure 

I have solved by the following code.
```js
/*eslint camelcase: [2, {properties: "never"}]*/
```

it seems the rules are changed.

**Comment by tetreault** [comment]
I had a similar issue. 

Setup: 
gulp-eslint: ^4.0.0
NPM: 5.0.3
Node: v7.2.0

Tossing `/* eslint-disable */` at the top of one of the files had no effect.
