### ISSUE TITLE
Formatter exit code 1 without any message

### ISSUE THREAD

**Issue by mazipan** [eslint/eslint#11393]
**Tell us about your environment**

* **ESLint Version: 5.13.0**
* **Node Version: 10.15.0**
* **npm Version: 6.4.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'airbnb-base',
    'plugin:vue/essential' // TODO: change to 'plugin:vue/recommended'
  ],
  // required to lint *.vue files
  plugins: ['vue'],
  // add your custom rules here
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-underscore-dangle': 0,
    'no-param-reassign': ['warn', { props: false }],
    'no-unused-vars': 0, // TODO: remove this
    'no-underscore-dangle': 0,
    'no-empty': 0,
    'no-trailing-spaces': [2, { 'ignoreComments': true }],
    'comma-dangle': [2, 'always-multiline'],
    'indent': ["error", 2, { "SwitchCase": 1 }],
    'generator-star-spacing': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-dynamic-require': 0,
    'max-len': [
      'warn',
      {
        code: 400,
        ignoreComments: true,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true
      }
    ],
    'prefer-destructuring': [
      'error',
      {
        AssignmentExpression: {
          array: false
        }
      },
      {
        enforceForRenamedProperties: false
      }
    ],
    'vue/html-closing-bracket-newline': [
      'error',
      {
        singleline: 'never',
        multiline: 'never'
      }
    ],
    'vue/component-name-in-template-casing': [
      'error',
      'kebab-case',
      {
        ignores: ['nuxt', 'nuxt-link', 'nuxt-child', 'no-ssr', 'header']
      }
    ]
  },
  settings: {
    'import/resolver': {
      webpack: 'webpack.config.js'
    }
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// i created any function that not passed my eslint rule, like
const add = (a, b) => {
  return a + b // oh I forgot the semicolon
}
```

```bash
./node_modules/.bin/eslint --ext .js,.vue --ignore-path .eslintignore . -f html -o eslint-report.html
```

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint exit with code 1, but never give error message and didn't print out any report in HTML file. 

**Expected**
ESLint keep show the error message and print in HTML file.

**Are you willing to submit a pull request to fix this bug?**
NO

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

To be clear, are you saying that ESLint is not creating an HTML file, and also isn't printing out any output at all when you run it?

What happens if you run ESLint without `-f html`?

**Comment by mazipan** [comment]
Without `-f html`
<img width="914" alt="screen shot 2019-02-15 at 15 46 48" src="https://user-images.githubusercontent.com/7221389/52845155-f6335680-3138-11e9-9382-153ef764b28f.png">

Oh I see @not-an-aardvark, this error coming from [eslint-detailed-reporter](https://github.com/mportuga/eslint-detailed-reporter).

**Comment by mazipan** [comment]
I will close this issue, sorry for not investigate further.
