### ISSUE TITLE
Proposal: change no-redeclare default behavior

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#11405]
**What rule do you want to change?**

- [no-redeclare]

**Does this change cause the rule to produce more or fewer warnings?**

- More Warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**

- It changes the default value of `builtinGlobals` option to `true`.

**Please provide some example code that this change will affect:**

```js
/*eslint-env browser */
/*eslint no-redeclare: error */

var top = 100
```

**What does the rule currently do for this code?**

- [No errors](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQtZW52IGJyb3dzZXIgKi9cclxuLyplc2xpbnQgbm8tcmVkZWNsYXJlOiBlcnJvciAqL1xyXG5cclxudmFyIHRvcCA9IDEwMCIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6eyJicm93c2VyIjpmYWxzZX19fQ==).

**What will the rule do after it's changed?**

- [Warn the `top` variable as a redeclaration](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQtZW52IGJyb3dzZXIgKi9cclxuLyplc2xpbnQgbm8tcmVkZWNsYXJlOiBbZXJyb3IsIHtidWlsdGluR2xvYmFsczogdHJ1ZX1dICovXHJcblxyXG52YXIgdG9wID0gMTAwIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlfX19) because `browser` environment has it.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Context:**

- We cannot redeclare the `top` variable, browsers ignore the `var top` declaration silently. This can cause confusion and I believe that it's worth to warn by default.
- Originate `no-undef` rule had warned redeclarations of globals by default, but it was removed in https://github.com/eslint/eslint/issues/4504. I think that we can re-enable it on `no-redeclare` rule.

[no-redeclare]: https://eslint.org/docs/rules/no-redeclare

**Comment by platinumazure** [comment]
Yes! This is a sensible default. My guess is we had to implement the option with a default disabled state so it wasn't a breaking change, but we should absolutely change this in the next major release.

**Comment by not-an-aardvark** [comment]
This issue was accepted in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/3e40976a2ebb9481405d4c3a358bc3191ecd234a/notes/2019/2019-02-28.md#proposal-change-no-redeclare-default-behavior).
