### ISSUE TITLE
Indent: Method Chain Comments 

### ISSUE THREAD

**Issue by ntatko** [eslint/eslint#11418]
**What rule do you want to change?** 

Indent

**Does this change cause the rule to produce more or fewer warnings?**

Probably no change, although it would change from project to project.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New Option: `commentAllignWith: below` or something like that 

**Please provide some example code that this change will affect:**

My code, after `eslint --fix` has run:
```js
const myFunction = (myUrl) => {
    // This comment spacing makes sense
    fetch(myUrl)
        .then(response => {
        // This is the first comment whose spacing is broken
            if(response.status === 404) {
            // Another strangely spaced comment
                window.location.reload();
            } else {
            // The last strange comment
                preformSuccessfulAction(myUrl);
            }
        })
        .catch(() => {
            console.error("no internet connection");
        });
}
```

**What does the rule currently do for this code?**

The rule `"indent": ["error", 4, {"SwitchCase": 1, "ignoreComments": false}]` produces comments which go from this:
```js
const myFunction = (myUrl) => {
    // This comment spacing makes sense
    fetch(myUrl)
        .then(response => {
            // This is the first comment whose spacing is broken
            if(response.status === 404) {
                // Another strangely spaced comment
                window.location.reload();
            } else {
                // The last strange comment
                preformSuccessfulAction(myUrl);
            }
        })
        .catch(() => {
            console.error("no internet connection");
        });
}
```
to this:
```js
const myFunction = (myUrl) => {
    // This comment spacing makes sense
    fetch(myUrl)
        .then(response => {
        // This is the first comment whose spacing is broken
            if(response.status === 404) {
            // Another strangely spaced comment
                window.location.reload();
            } else {
            // The last strange comment
                preformSuccessfulAction(myUrl);
            }
        })
        .catch(() => {
            console.error("no internet connection");
        });
}
```

**What will the rule do after it's changed?**

It will allow the option of comments to align with the line above or below, should the user specify.

**Are you willing to submit a pull request to implement this change?**

Willing, yes; able, no.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. I can't reproduce this issue -- your original code sample isn't reporting any errors for me in the [demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGluZGVudDogZXJyb3IgKi9cclxuY29uc3QgbXlGdW5jdGlvbiA9IChteVVybCkgPT4ge1xyXG4gICAgLy8gVGhpcyBjb21tZW50IHNwYWNpbmcgbWFrZXMgc2Vuc2VcclxuICAgIGZldGNoKG15VXJsKVxyXG4gICAgICAgIC50aGVuKHJlc3BvbnNlID0+IHtcclxuICAgICAgICAgICAgLy8gVGhpcyBpcyB0aGUgZmlyc3QgY29tbWVudCB3aG9zZSBzcGFjaW5nIGlzIGJyb2tlblxyXG4gICAgICAgICAgICBpZihyZXNwb25zZS5zdGF0dXMgPT09IDQwNCkge1xyXG4gICAgICAgICAgICAgICAgLy8gQW5vdGhlciBzdHJhbmdlbHkgc3BhY2VkIGNvbW1lbnRcclxuICAgICAgICAgICAgICAgIHdpbmRvdy5sb2NhdGlvbi5yZWxvYWQoKTtcclxuICAgICAgICAgICAgfSBlbHNlIHtcclxuICAgICAgICAgICAgICAgIC8vIFRoZSBsYXN0IHN0cmFuZ2UgY29tbWVudFxyXG4gICAgICAgICAgICAgICAgcHJlZm9ybVN1Y2Nlc3NmdWxBY3Rpb24obXlVcmwpO1xyXG4gICAgICAgICAgICB9XHJcbiAgICAgICAgfSlcclxuICAgICAgICAuY2F0Y2goKCkgPT4ge1xyXG4gICAgICAgICAgICBjb25zb2xlLmVycm9yKFwibm8gaW50ZXJuZXQgY29ubmVjdGlvblwiKTtcclxuICAgICAgICB9KTtcclxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==). Are you sure the code samples you provided are correct?

**Comment by platinumazure** [comment]
Hi @ntatko. In addition to not-an-aardvark's comment above, it could also help to know which version of ESLint you are using.
