### ISSUE TITLE
ESLint v5.14.0 now requires Node.js to be compiled with crypto

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#11413]
I came across this on Twitter. It appears that upgrading file-entry-cache means that ESLint now requires Node.js to be compiled with crypto because of how the cache is generated now. More details:

https://github.com/nodejs/node/pull/26182

We should decide if this is something we are okay with going forward. 

I’m guessing there aren’t a lot of folks using Node.js without crypto, so maybe not a big deal, but at a minimum it seems like we should acknowledge this requirement in our docs somewhere.

**Comment by platinumazure** [comment]
@nzakas Do we need to reopen this?

**Comment by nzakas** [comment]
Yes, thanks for catching this! I filed it on mobile which didn't allow me to set an assignee, and it fell off my radar.

**Comment by kaicataldo** [comment]
Related issue from a while back: https://github.com/eslint/eslint/issues/5522

How do we want to proceed with this? Should we maybe bring this up in the next TSC meeting? Given we haven't seen any other issues, it doesn't seem like it's a widespread problem. That being said, if it's something that's easily fixable it could be worth changing to make it easier for Node core's tests.

**Comment by kaicataldo** [comment]
Is this something we still need to look at?

**Comment by nzakas** [comment]
This is really just a sentence addition to the readme saying that ESLint requires crypto.

**Comment by nzakas** [comment]
Submitted #12475
