### ISSUE TITLE
Documentation could indicate usage

### ISSUE THREAD

**Issue by vfonic** [eslint/eslint#11433]
Hi!

I'm using eslint and I'm loving it! Thanks!

However, every time I go to some rule page (this time it was: https://eslint.org/docs/rules/guard-for-in), I can't find enough information to know how to add this rule to my eslint config.

Yes, I'm a total beginner and I'd love to have a tiny little code snippet showing me exactly where and how to add it (remember webpack configs pre v3? #tappingInTheDarkCopyPastingRules)

I think this short code snippet wouldn't bloat the pages in any way, but would be super useful to "not have to think":

```js
rules: {
  // ...
  'guard-for-in': 1,
}
```

Especially since eslint rules' values are not necessarily always a simple true/false. It would be great to specify which values each rule accepts.

Thanks!

**Comment by ilyavolodin** [comment]
Each code example in the documentation has comments up top showing current configuration for the rule. Here's how it looks like in `guard-for-in` rule:

```
/*eslint guard-for-in: "error"*/

for (key in foo) {
    doSomething(key);
}
```
I know it's not the most obvious way of showing how to configure a given rule, but once you know it, it becomes pretty easy to understand.

**Comment by vfonic** [comment]
@ilyavolodin even now, after you explained it, and I've re-read your comment and the documentation page again, I still don't understand how that (`/*eslint guard-for-in: "error"*/`) applies to `.eslintrc.js` or `json` or other eslint config file.

What are all the possible values? Is "error" the only value? I'd assume "warning" would be accepted value, too. What about `1`? Can I put `/*eslint guard-for-in: 1*/` like I did in my eslintrc file? What about passing multiple arguments as an array? `["error", "always", ...]`? I've seen this for other eslint rules.

I don't want to put this on top of every file in my project, I'd like to know how to add this to a project-wide eslint configuration. The example you're showing, shows how this could be used in a single file.

🤷‍♂️ I'm just a fan of a good User/Developer Experience. It's there like you said...but it's also not there. :) I hope I'm still making sense. :)

**Comment by ilyavolodin** [comment]
You are making perfect sense, but we have to balance clarity and work load on contributors. We have 265 rules, and if we had to update each rule's documentation with all possible examples of usage, it would be a very large undertaking. Because of that, we centralized explanation about configuration of the rules in general here: https://eslint.org/docs/user-guide/configuring#configuring-rules and then each rule's documentation lists all of it's available configuration options. Inline configuration as shown in the example translates to .eslintrc.* configuration by just removing comments and `eslint` prefix. So `/*eslint guard-for-in: "error"*/ becomes
```
rules: {
  "guard-for-in": "error"
}
```

It would be nice to automate documentation update with all options somehow, but it's not trivial.

**Comment by platinumazure** [comment]
Hi @vfonic, I agree that the UX for new ESLint users is, in some ways, not ideal.

General information about configuring rules, including configuring the severity level (common to all rules), can be found here: https://eslint.org/docs/user-guide/configuring#configuring-rules

And then each rule has specific options, found on their own documentation pages.

The rule documentation assumes that users have read the configuration docs, and so understand how to configure the rule severity. I think that is possibly reasonable for anyone who has used ESLint for some time, but it could be difficult for people who are using ESLint for the first time but are inheriting a setup (so they have no reason, in their view, to read the general config documentation).

I'd be interested to see if we could make any improvements to the rule docs such as (for example) adding a quick aside reminding readers to view the general config page to understand general rule configuration (including severity). We would want to make this visible to new users, but easily skipped for people who already know the basics.

If you have any specific suggestions for how we could proceed with something like this, we would be grateful for any contributions!

**Comment by vfonic** [comment]
Thanks for quick replies!

@platinumazure I love your idea of adding a sidenote reminding readers about general config page. I think it wouldn't occupy too much space if there's one more sentence of text, with a link to the general config page documentation. Could this be added to the template/layout for the rule pages, so that we don't have to update all the rule pages one by one?

**Comment by platinumazure** [comment]
> Could this be added to the template/layout for the rule pages, so that we don't have to update all the rule pages one by one?

That sounds feasible!
