### ISSUE TITLE
new label "typescript" or something?

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11442]
Some issues (e.g. #11441 ) may be related to "typescript" or something. should we create a label?

**Comment by ilyavolodin** [comment]
In most cases, issues that are related to typescript are not directly related to this repository and should be filed either in [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) or [eslint-plugin-tslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint). But I'm not opposed to adding a new label for rare occasions when we need to do something to enable some typescript functionality.
