### ISSUE TITLE
comments are not indented when code is indented

### ISSUE THREAD

**Issue by govindrai** [eslint/eslint#11447]
**Tell us about your environment**

* **ESLint Version:** 5.14.1
* **Node Version:** 9.2.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: 'airbnb-base',
  parserOptions: {
    ecmaVersion: 8,
    sourceType: 'module',
  },
  env: {
    node: true,
    es6: true,
  },
  rules: {
    'no-case-declarations': 'off', 
    'no-new-func': 'off', 
    'no-multi-assign': 'off', 
    'no-new-object': 'off', 
    'no-ex-assign': 'off', 
    'no-await-in-loop': 'off', 
    'no-nested-ternary': 'off', 
    'import/order': 'off', 
    'no-constant-condition': 'off', 
    'prefer-spread': 'off', 
    'no-void': 'off', 
    'no-eval': 'off', 
    'no-console': 'off', 
    'no-sequences': 'off', 
    'no-mixed-spaces-and-tabs': 'off', 
    'no-tabs': 'off', 
    'no-empty': 'off', 
    'no-lonely-if': 'off', 
    'no-useless-concat': 'off', 
    'no-cond-assign': 'off', 
    'no-mixed-operators': 'off', 
    'no-useless-escape': 'off', 
    'no-buffer-constructor': 'off', 
    'no-bitwise': 'off', 
    'radix': 'off', 
    'new-cap': 'off', 
    'prefer-rest-params': 'off', 
    'array-callback-return': 'off', 
    'block-scoped-var': 'off', 
    'no-redeclare': 'off', 
    'class-methods-use-this': 'off', 
    'no-restricted-properties': 'off', 
    'no-loop-func': 'off', 
    'no-unused-expressions': 'off', 
    'no-underscore-dangle': 'off', 
    'no-var': 'off', 
    'prefer-const': 'off', 
    eqeqeq: 'off', 
    camelcase: 'off', 
    'import/no-unresolved': 'off', 
    'no-continue': 'off',
    'func-names': 'off', 
    'no-unused-vars': 'off', 
    'no-undef': 'off', 
    'no-use-before-define': 'off', 
    'vars-on-top': 'off', 
    'max-len': 'off', //what should our max character length be? 100 is recommended GOOD
    'arrow-parens': 'off', 
    'no-else-return': 'off', 
    'one-var': 'off',
    'on-var-declaration-per-line': 'off', 
    'no-throw-literal': 'off', 
    'array-bracket-spacing': 'off', 
    'object-shorthand': 'off', 
    'arrow-body-style': 'off', 
    'no-confusing-arrow': 'off', 
    'prefer-promise-reject-errors': 'off', 
    'object-curly-newline': 'off', //--> this is a heated one do you want all methods to be on
    'no-param-reassign': 'off', 
    'brace-style': 'off', 
    'prefer-destructuring': 'off', 
    'no-shadow': 'off', 
    'no-plusplus': 'off', 
    'default-case': 'off', 
    'no-restricted-globals': 'off', 
    'no-return-assign': 'off', 
    'consistent-return': 'off', 
    'guard-for-in': 'off', 
    'no-restricted-syntax': 'off', 
    'no-prototype-builtins': 'off', 
    'comma-dangle': ["error", "always-multiline"],
    'spaced-comment': ["error", "always", { "exceptions": ['*'] }] 
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function promises() {
  const chain = Promise.resolve()
      // do this
      .then(console)
      // also do this
      .then(console)
      // do that
      .then(console)
      // also do that
      .then(console);
}
```

```bash
eslint --fix
```

**What did you expect to happen?**
I expected eslint to format my code as below (with the comments lined up with the promise chains).
```js
function promises() {
  const chain = Promise.resolve()
    // do this
    .then(console)
    // also do this
    .then(console)
    // do that
    .then(console)
    // also do that
    .then(console);
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
The comments are not indented and this misalignment happens all over my codebase (which is a ton of lines)
```js
function promises() {
  const chain = Promise.resolve()
  // do this
    .then(console)
  // also do this
    .then(console)
  // do that
    .then(console)
  // also do that
    .then(console);
}
```

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by Manu1400** [comment]
Can you publish your eslint config file ?

**Comment by govindrai** [comment]
It is there under configuration in my question.

**Comment by not-an-aardvark** [comment]
Thanks for the report, I can reproduce this issue.

A small reproducible case is [here](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGluZGVudDogZXJyb3IgKi9cblxuZm9vXG4gICAgLmJhclxuLy8gY29tbWVudFxuICAgIC5iYXoiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19) (the comment on line 5 should be an error, but it is considered valid).

**Comment by Manu1400** [comment]
@govindrai :  I can't reproduce this issue with eslint 5.14.1 and your .eslintrc.js config (on Mac OS).
@not-an-aardvark : It's an other issue ?

**Comment by not-an-aardvark** [comment]
I think this issue and the case [here](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGluZGVudDogZXJyb3IgKi9cblxuZm9vXG4gICAgLmJhclxuLy8gY29tbWVudFxuICAgIC5iYXoiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19) have the same underlying cause, because if line 5 was considered an error then it would also be autofixed appropriately.

**Comment by Benjmhart** [comment]
I'll take a look at this issue over the next week and see if I can reproduce
