### ISSUE TITLE
Add 'native' as well as 'windows' and 'unix' to linebreak-style

### ISSUE THREAD

**Issue by MikeBeaton** [eslint/eslint#11458]
This is a duplicate of request #8596, which already has a closed pull request #8620 which was designed to fix this. I realise this will therefore most likely be closed summarily, but I did just want to try to put the reasons for this change fowards again. I suspect that this may have been rejected by people who *don't* have extensive experience of working on a projects where some developers are on Linux and some on Windows - because the approaches suggested as alternatives to allowing this fix really, truly, don't work well.

I'll try to be as brief as reasonably possible:

 - If you don't specify anything on git then it is easy to end up with a mixed Linux-Windows project which has mixed line endings in its files which (we all agree) is horrible
 - For Linux-Windows projects on git, the standard approach to resolving this is to either set the `git` `core.autocrlf` config variable to `true` at the repository (or global) level or, even better (because it forces the equivalent of this setting on everyone who clones the repo), to have a `.gitattributes` file in the repo root containing the line `* text=auto`
- As we know, this results in all text files in the repo itself having LF line endings, but all text files checked out to Windows machines (only) appearing on Windows to have CRLF line endings, and with such files (and changes to them) checked back in again 'magically' as LF
- Mainly, this just works. We can also safely say there's a reason the git developers did this, and that it's the standard approach to this problem. Which is, mainly, that it just works.
- The advantages of it are:
    - *All* programs on the OS (even older ones, such as Windows `notepad`, for example) are presented with native line endings, which they can read just fine
    - Any new files, created by anything, are essentially by definition correct, produced with native line endings and (correctly) added to the repository with LF line endings (and no warnings)
    - Any files which get modified by build processes (sometimes with changes which might need to be checked in, but sometimes with no changes) are by definition correct
        - What this lets you avoid is an LF file which has been 'modified' by some Windows process to have exactly the same contents but now with CRLF line endings
        - **I am here because `npm run build` in a `create-react-app` project on Windows DOES exactly this - it rewrites `tsconfig.json`, typically with no actual changes, but with Windows CRLF line endings regardless of what it started with** (yes, there is a bug here in what this process does; but such bugs are widespread and almost unavoidable in practice, in a complex build set-up)

Yes, we definitely want to avoid mixed line endings in files. But I am convinced (along with the original proposer) that the most correct way to do this is to allow the standard, clean, safe `core.autocrlf true` (aka `* text auto`) behaviour by `git` and to have an eslint `linebreak-style` `native` variant of the rule which (automatically, nothing else needed) matches that standard, safe approach.

NB, also, using the `git` `core.autocrlf` approach but turning off the `eslint` rule (which seems to be the main suggestion, apart from forcing LF endings onto Windows machines, which is problematic for the types of reasons given) works, of course.... as long as everything was set up right in the first-place, but it removes all verification - which eslint could otherwise provide! and surely that is part of its purpose?! - that everything was indeed set up right.

**Comment by platinumazure** [comment]
I'm :+1: to this idea-- it does seem like a real pain point. That said, not 100% sure yet if this is the best approach for solving.

It will really help to have some code examples of what would be different with this new option (although I suppose those will require some extra comments for context, such as whether the example is for Windows vs Linux vs some other OS). Thus, I've added the "needs info" label. Please look at the bot's link to our Rule Change Request template for a guide of what sort of info we need. Thanks!

**Comment by MikeBeaton** [comment]
HI @platinumazure - thank you! When you say code samples of what would be different, you mean in a project using this, or in the eslint source? (Sorry I'm not clear which!) (I do *think* you mean examples of where projects would be different, and how and why this change would help them, right? I can happily try to do that!)

**Comment by MikeBeaton** [comment]
So, I actually have a `create-react-app` project which I'm working on now. It's being created for our company originally by an external company whose developers use VS Code on macOS, but our developers are going to working on it too, using VS Code on Windows.

When I first cloned the project and built it, I got lots of errors as follows:

![screenshot_1](https://user-images.githubusercontent.com/11946605/53658861-eb58e580-3c51-11e9-86e5-aed50a93f662.jpg)

The project is using the default eslint 'linebreak-style': unix', but because I have my Windows git set up in a fairly standard way, and because we hadn't yet specified anything else, all the text files on Windows are checking out as CRLF. I obviously can't change the 'linebreak-style' to 'windows', that would break the Mac build. (Nor, of course, should I run `eslint --fix`. That would be a *bad* choice in this state, although there is an error message recommending it, and a more junior programmer might be tempted to try that as a fix!)

I can just turn of the warnings by setting `'linebreak-style': 'off'` in `.eslintrc.js` and this works - but I don't *want* to just turn off the warnings, that's the whole point of lint, right? (And it is *certainly* possible, in a mixed Windows Un*x project, that some file will turn up somewhere with mixed line endings, from an erroneous commit by someone. They should be told, and I'd like to know.)

So the only real option (apart from just telling eslint 'hey, don't worry about it') is to switch to a `.gitattributes` file such as the following:

```
# check out all text files as LF always on all OSes
* text eol=lf

# make sure that these files aren't modified
*.png binary
*.ico binary
*.jpg binary
*.jpeg binary
```

Now we're getting somewhere. Although note that once you've specified `* text eol=lf` things already start getting harder, and you now have to start explicitly specifying all your binary files - which you don't have to with `* text auto`, where git automatically does what it thinks is right - which it mostly is. We need to delete everything and clone it again, but now the software will compile on Windows without triggering the eslint warning - because the line endings *are* now LF, even on Windows!

But we have disadvantages to this.

Here's one:

![screenshot_2](https://user-images.githubusercontent.com/11946605/53659650-02003c00-3c54-11e9-8a00-cb202ca81d66.jpg)

Something in the toolchain has inserted some CRLFs into a file which shouldn't have them - and which is otherwise unchanged; as verified by the fact that after running `dos2unix` on the file, the spurious file change message goes away.

Yes, this *is* a bug in something in the react toolchain, but that doesn't really matter (I think). It is the near impossibility of fully avoiding errors like this which is the reason why git provides the `core.autocrlf` setting in the first place.

And note that we have other disadvantages.

I can no longer read my files in 'quick and dirty' tools like Windows `notepad`, even if I want to:

![screenshot_3](https://user-images.githubusercontent.com/11946605/53660135-109b2300-3c55-11e9-8dc0-cbe9e2565cf1.jpg)

I have to be very careful creating new files:

![screenshot_4](https://user-images.githubusercontent.com/11946605/53660250-50faa100-3c55-11e9-83c9-955014b153e6.jpg)

Many Windows programs will (of course) create new files with CRLF in them. So I get a warning when I try to add them to a commit. It will in fact work, but I have to get in the habit of ignoring lots of warnings (*bad*), *and* I will be in a situation where my local files (the ones I added, with CRLF) will no longer be the same as they would be if I deleted and re-cloned the repo (when they would become LF). Otherwise I have to be much more careful, and remember to `dos2unix` all text files which I add (and when - not if - I forget to do this, I have to back out the adds, convert them, and then re-add them). This is a world of pain...

Now, as far as I can see, if I could have set `'linebreak-style': 'native'` in `.eslintrc.js` in the first place (i.e. in combination with the `* text auto` in `.gitattributes`) then none of this would have happened, and everything would be peachy! Windows programs could insert Windows linebreaks in files on Windows without generating spurious change messages. New files could be freely created (with their default Windows linebreaks) and correctly committed with Unix linebreaks (to the repo, and to the Mac developers). And eslint is *checking* that this is all alright.

For example, if we had forgotten to put anything in `.gitattributes` in the first place, and if some Windows developer had their global `core.autocrlf` set to false, then they could easily have ended up committing CRLF files back into an LF repo. Bad. But immediately noticed. But eslint running in the CI and on the Mac developers' machines, and complaining that it was seeing non-native line endings.

There's one disadvantage to this, which is that there are now two substantively different builds hanging around - a build where everything is in CRLF, built on Windows, and a build where everything is in LF, but on macOS (or on some Un\*x system, more generally). But that doesn't matter, right? The only builds I will build on my local machine are development builds, and they work just fine with either line ending. All test, staging and production builds are done on our CI server and... it's our responsibility to set up our CI correctly! But basically, it's going to be (or, in actual fact, it already is) running on a Un\*x docker image, and it's going to build the expected version with LFs, and - because eslint is now playing along! - it's going to be checking, while it builds, that no mixed or Windows line endings have been introduced.

**Comment by MikeBeaton** [comment]
@mysticatea - thumbs down to me means "someone really hasn't tried very hard, hasn't got it, and is wasting our time". Am I mis-reading? I have put a lot of reasoning down on this page (maybe too much, but I added more when I was asked to), and I've tried to be very measured. At least some additional words as feedback would help. Do you ever work on mixed Windows-Un\*x projects, at all? Because if you don't, it's really *not* obvious how painful all this can be, and how much the `core.autocrlf` setting helps to (almost completely) mitigate this. What we're basically asking for is an **eslint setting compatible with that git feature, specifically for use in mixed Windows Un\*x projects**. This is not just a way for people to be lazy and say 'check it, but I don't really care what the result it', it's a way to say 'check it, please, and make sure everything is right and that I do always, consistently, have the right line endings for my environment'.

**Comment by MikeBeaton** [comment]
(I'm more than happy that any revised documentation - were this to occur - should very strongly emphasize that this option is provided specifically for used on mixed projects, in conjunction with the `* text auto` setting in `.gitattributes` - and I'm more than happy to volunteer to revise the documentation if needed to support this.)

**Comment by not-an-aardvark** [comment]
@MikeBeaton Sorry about the miscommunication. In this repo it's common for people to use :-1: to simply express opposition to adding a feature, without the other connotations you suggested. I'm undecided on whether this feature would be worthwhile, but I don't think anyone would read this and think you're wasting peoples' time. (Hopefully @mysticatea will be able to elaborate on his reasoning for opposing this feature request soon.)

**Comment by mysticatea** [comment]
Sorry. :+1: and :-1: from the team is just a sign to support and oppose the feature. (You can find the issue state on https://github.com/mysticatea/eslint-evaluating-issues)

I'm a Windows user and I have often experienced in mix of multiple environment. And I believe it's not good idea if we change code for each environment because it causes trouble.

**Comment by MikeBeaton** [comment]
That's great - thank you for the feedback!

If I'm not wrong, what you're saying is that you think it's not a good idea if the system (git) automatically changes the code on the different environments, because that causes trouble?

I do have to say it's certainly my experience, as in the examples above, and as in one other open source project that I've contributed to significantly, that not letting git do this is what ends up causing trouble - and requiring lots more care and time from developers for something that git can handle perfectly well. (And almost ensuring that non-careful, more junior developers make mistakes which have to be unpicked by someone else.)

But also, if I can paraphase, to the extent that the eslint project refuses this, again (despite having two clearly worded arguments for it and - I understand - an otherwise perfectly acceptable implementation of it already submitted as a PR), them you are basically saying:

"Git got it wrong; all those people who use `core.autocrlf = true` in their git config or `* text auto` in their  `.gitattributes` file are making a mistake; as did the people who originally implemented this very widely used feature of git. We, eslint, don't agree with it, and we are deciding to refuse to add the rule variant which would be necessary (and sufficient) for us to support those (many) people who want use it. If you do use that feature of git you are on your own, as far as line breaks in your js are concerned - just turn off our checking completely, please, and manage it manually or with some other tool."

**Comment by ilyavolodin** [comment]
@MikeBeaton That's not necessarily true. Git has 3 ways of configuring line endings (or maybe even 4, can't remember now). It looks like you are using "checkout as-is, checking as-is" which is fine, but if you want consistent line ending, you should configure it as "checkout as-is, checkin unix" or something like that. That would make sure that all line endings are normalized on checkin, and ESLint rule is going to work correctly independent of the environment.
I'm on the fence on including this option. On one hand, I can understand how it might be helpful, but on the other, I think it leads no only to complexity down the road, but also makes ESLint get into the area of trying to resolve cross-platform incompatibilities, which is very much not the goal of this tool.

**Comment by MikeBeaton** [comment]
Hi @ilyavolodin I'm using checkout as appropriate for the OS, check in as LF (that's `core.autocrlf` = `true` does). Yes, there are some other options, but that particular option is very widely used, and very helpful at avoiding line ending problems. All we're asking for is that eslint checks that the line endings are consistent, and correct for the current platform. Without the suggested new option in eslint, you have to turn off linebreak checking in eslint completely to use `core.autocrlf` `true` in git. I would totally agree that it's not a part of eslint to deal with cross platform incompatibilities, but your `linebreak-style` rule is pretty much already in that area, and is on by default, and incompatible with (not just neutral about) one perfectly good way of dealing with cross platform incompatibilities. One could very well argue that is you don't want to get into resolving cross platform issues then the new, proposed `native` setting is a more appropriate default that the current `unix`!

**Comment by MikeBeaton** [comment]
@platinumazure Was the info above what you needed? Let me know if I can provide anything else.

**Comment by MikeBeaton** [comment]
Hi @ilyavolodin,

Github promote setting `core.autocrlf` to `true` (or it's equivalent `* text auto` in the `.gitattributes` file) [as the 'correct' and 'default' way to handle line-ending problems in cross-platform repositories](https://help.github.com/en/articles/dealing-with-line-endings).

The fact that Github say this doesn't necessarily make them right, and certainly doesn't make this necessarily the 'best' way of dealing with line ending issues.

But I would submit that it *is* (very arguably) a problem, of some sort, if eslint is saying that this approach is so wrong that you have to turn off the eslint linebreak checking entirely if you wish to use it.

**Comment by platinumazure** [comment]
I personally feel that we're getting a bit caught up in the Git/Github discussion. This issue could easily happen with some other source control tool, or just in general.

I think that, outside of the source control context, asking ESLint to just check for consistent line endings matching the software platform (which can be done using [`os.EOL`](https://nodejs.org/api/os.html#os_os_eol) and does not depend on presence/absence of Git at all) is a reasonable request. Additionally, the fact is that ESLint currently cannot handle these cases at all, and some of our responses (both here and in past discussions) has effectively been, "well, sucks for you, don't use the rule here". That's not ideal given that this is a fairly common development experience.

As with all enhancement requests, we need to balance them against maintainability concerns. My hope is that we could make it clear in documentation that ESLint is not going to try to cater to every possible Git (or other source control) setting, but rather allow users to force `\r\n`, force `\n`, or defer to the platform standard, and that's it.

My own evaluation is that we could easily add this without paying a significant maintainability cost-- and furthermore, we should, because it would be beneficial to a fairly common use case and because most of the arguments against have been doing so under the straw man argument that this request is about supporting Git settings, when it is not.

@MikeBeaton What I was asking for was more like code examples where the rule would warn currently but would not warn under the new setting, and vice versa. In this case, since the issue is about linebreaks rather than code syntax, it would probably help to just have 1 code sample and have a matrix of checkout scenarios (e.g., OS platform line setting, line endings on the checked-in code, and other inputs) to show where the rule currently warns, but wouldn't under the new setting. Basically, I'm just asking for a concise demonstration of how the new setting would help developers. :smile:

**Comment by MikeBeaton** [comment]
Say we have a project which is being checked out with the same line endings on all platforms. Then we set the eslint rule to the line ending being used, and it all works.

Say we have a project which (due to the source control being used) is checked out in platform appropriate line endings. Assume there is one or more `.js` file in the project, which has one or more line endings, and on which eslint is running. Then if we use `'linebreak-style': 'unix'` the file(s) in question will pass on Unix, but fail on Windows. Or if we use `'linebreak-style': 'windows'` we will pass on Windows, but fail on Unix. (!) If we omit any `'linebreak-style'` setting, we will pass on Unix but see warnings (or outright build fails depending on how strictly our environment is set up) on Windows, since `'linebreak-style': 'unix'`  is the default). In order to pass on both, we *must* currently disable the rule: `'linebreak-style': 'off'` (or, somehow, have some other process which modifies the eslint config prior to build; or use an eslint plugin).

**Comment by MikeBeaton** [comment]
@platinumazure I really hope that answers what you're asking for?! I don't think there is such a thing as a code sample that shows this, the problem happens with any and all normally configured JS files (at least, ones with any lines in!), in combination with a widely used and otherwise normally very successful approach to cross-platform development (which I'm sure is supported by more than one VCS!).

**Comment by MikeBeaton** [comment]
Hi @platinumazure , @ilyavolodin , @mysticatea and others - thank you for engaging with this!

I looked again at the old discussion #8596.

A key point made there is that not enforcing strictly Unix line endings has broken the builds of several projects in the past - including eslint.

However... if a project has its CI set up correctly then its build will always be on one, consistent OS (nothing to do with any development machine's OS) and that problem goes away, I think? (Even with CI, development builds will still differ, but that may be okay if users know what they are doing and have chosen this - see following.)

I wonder if it would make sense to:
 - Add the `native` option
 - Leave the `unix` option as the default
 - Change the docs to explain that `unix` is the default because using non-Unix line endings can break builds
 - Change the docs to clearly recommend against using the `native` option unless you know what you are doing and have CI set up (so that your builds don't depend on who builds them)

**Comment by MikeBeaton** [comment]
In case it helps anyone else reading this, I've only just realised that @sholladay gives a perfectly usable, short, simple, workaround to achieve the same result at the end of his original post #8596 .

**Comment by MikeBeaton** [comment]
I've just finished [an accepted and merged pull request](https://github.com/facebook/create-react-app/pull/6610) for the issue in `create-react-app` which brought me here (already described above).

I'm mentioning this because I did just want to mention that *they* weren't willing to accept a fix designed to allow for users using non-native linefeeds  - i.e. using what I think it is fair to call the ESLint-recommended approach of Unix linefeeds in all OSes (and, specifically, in Windows) for all mixed-OS development projects - since in their opinion a simpler fix which works for people using native linefeeds would work for "[al]most everyone"...

**Comment by MikeBeaton** [comment]
I am still trying to argue/persuade/suggest that it is unnecessarily prescriptive (I know it is ESLint's *job* to be prescriptive!) to completely rule out supporting a `native` option, and I would still like to note that if 'on' and `unix` is the default setting for the rule (as it is) then anybody coming across this issue will *very* likely arrive at the ESLint documentation and will see the warning - if one is added, as it should be - the the purpose of the `native` setting is to make it easier to use all native tools for *development* on cross-OS projects, and that the user should NOT use it on any serious production project unless release builds are being done on one, consistent environment (preferably using CI - which ensures this).

**Comment by MikeBeaton** [comment]
@platinumazure - This is another try at giving you the matrix you've been asking me for via the `needs info` label, but also at the same time to mock up a first suggestion towards the type of warning text I was talking about just above:

---

**native**

**WARNING:** We now support a `native` option in order to make it easier for you to use all your native development tools in mixed OS projects whilst still having ESLint check for consistent linebreaks (in combination with the native linebreak features of several version control systems). However, we strongly recommend that you DO NOT USE this setting on mixed OS projects unless you have Continuous Integration set up, to ensure that release builds are always done on one consistent OS. Failure to ensure this has resulted in broken public releases for several popular packages, including [Mocha](https://github.com/mochajs/mocha/issues/2799), [Showdown](https://github.com/showdownjs/showdown/issues/244), [npm-lockdown](https://github.com/mozilla/npm-lockdown/issues/42), and [ESLint itself](https://github.com/mozilla/npm-lockdown/issues/42)!

Examples of incorrect code for this rule with the "native" option:

```
var a = 'a', // \n	// fails on Windows
    b = 'b'; // \r\n	// fails on Unix
```
Examples of correct code for this rule with the "native" option:

```
// passes on Windows
var a = 'a', // \r\n
    b = 'b'; // \r\n
```

```
// passes on Unix
var a = 'a', // \n	
    b = 'b'; // \n
```

**Comment by not-an-aardvark** [comment]
Personally, my impression is that an option isn't worth adding to ESLint core if it requires that much caution tape, given that the alternative from https://github.com/eslint/eslint/pull/8620#issuecomment-340805911 still works if someone really wants to do this. I think it's reasonable to require users to jump through a few more hoops for "unsafe" behavior since it reduces the likelihood that someone will use it if they're not sure what they're doing.

While documentation warnings can certainly help to prevent users from doing something unsafe, not everyone who uses the option reads the documentation (e.g. they might copy-paste code from a StackOverflow comment or a github issue comment).

**Comment by MikeBeaton** [comment]
@not-an-aardvark - thank you. I honestly don't believe the change does require that much safety tape. I added it to try to address the concerns being raised.

Can I try proposing a simpler, less warning-laden version? #11497 (Not intended to be merged, only to present the suggestion being made.)

**Comment by MikeBeaton** [comment]
This was the revised version, I've tried to keep the tone very neutral, and not-overladen with warnings, just to simply mention the issue:

---

### Options

This rule has a string option:

* `"unix"` (default) enforces the usage of Unix line endings: `\n` for LF.
* `"windows"` enforces the usage of Windows line endings: `\r\n` for CRLF.
* `"native"` enforces OS-native linefeeds (`\r\n` for CRLF on Windows, `\n` for LF on Unix).


### unix

Examples of **incorrect** code for this rule with the default `"unix"` option:

&lt;no change&gt;

### windows

Examples of **incorrect** code for this rule with the `"windows"` option:

&lt;no change&gt;

### native

Examples of **incorrect** code for this rule with the `"native"` option:

```js
/*eslint linebreak-style: ["error", "native"]*/

var a = 'a', // \n     // fails on Windows
    b = 'b'; // \r\n   // fails on Unix
```

Examples of **correct** code for this rule with the "native" option:

```js
/*eslint linebreak-style: ["error", "native"]*/

// passes on Windows
var a = 'a', // \r\n
    b = 'b'; // \r\n
```

```js
/*eslint linebreak-style: ["error", "native"]*/

// passes on Unix
var a = 'a', // \n
    b = 'b'; // \n
```

## Using this rule with version control systems

Version control systems sometimes have special behavior for linebreaks. For example, the default behavior of [git](https://git-scm.com/) on Windows systems is to convert LF linebreaks to CRLF when checking out files, but to store the linebreaks as LF when committing a change.

To make it easy for developers to contribute to your codebase from different platforms, you should configure your VCS to handle linebreaks appropriately.

If you use git, one option is to add a line to your [`.gitattributes` file](https://git-scm.com/docs/gitattributes) to prevent git from converting linebreaks in `.js` files:

```
*.js text eol=lf
```

That works with the default `"unix"` option for the `linebreak-style` rule.

Another option is to explicitly ask git to use native linebreaks for all users, regardless of their personal settings, by adding the following line to your [`.gitattributes` file](https://git-scm.com/docs/gitattributes):

```
* text=auto
```

This will work with the `"native"` option for the `linebreak-style` rule. When doing this, exercise caution since the build output of your project will inherit the *local* linebreak style of the OS on which the build was made. Many developers consider this to be fine for development work - we leave that choice up to you - but it is not fine for release builds, and may even break the release for users on the wrong OS. If you are using a modern [continuous integration](https://github.com/marketplace/category/continuous-integration) approach this problem will not arise so long as you configure things so that your release builds are always made automatically, on a known image of a known OS.

**Comment by MikeBeaton** [comment]
@mysticatea @g-plane @not-an-aardvark Does the above go any way towards addressing your legitimate concerns, here?

We can note that using the linefeed conversion feature of Git (and I'm sure the same applies to other VCSs) is [widely](https://help.github.com/en/articles/dealing-with-line-endings) [recommended](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/), although it's also, apparently, [widely hated and widely loved](https://stackoverflow.com/a/170968/795690) in something approaching equal measure.

ESLint currently [recommends](https://github.com/eslint/eslint/issues/8596) [against](https://github.com/eslint/eslint/pull/8620) using it, and [recommends strictly sticking to LF](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems).

On the other hand, I've only just completed and had accepted a small pull request to the `create-react-app` project, which fixes a mixed linebreak bug and which is what brought me here... and I mention this in order to note that they refused to countenance a fix for anything other than users using OS-native linebreaks, on the basis that that would be sufficient for "[[al]most everyone](https://github.com/facebook/create-react-app/issues/6566#issuecomment-471213230)".

All the above makes the whole thing look very much like a matter of opinion, with two viable ways of working.

It's true that there was [a genuine reason why using linefeed conversion was frowned upon, and which apparently bit the ESLint project itself](https://github.com/eslint/eslint/pull/8620#issuecomment-302899468), namely broken builds. More specifically CRLF builds breaking things for Un\*x end users. I personally believe this issue is made moot by the modern widespread adoption of CI practices.

It's certainly the case that many, many people, including [major players in the JS ecosystem](https://github.com/facebook/create-react-app), and [your own project for everything except JS files](https://github.com/eslint/eslint/blob/master/.gitattributes)(!!), are using (&/or assuming that people will use) Git linefeed conversion.
