### ISSUE TITLE
`ignoreTopLevelFunctions` option for `max-lines-per-function` 

### ISSUE THREAD

**Issue by yc624** [eslint/eslint#11459]
* **ESLint Version:** v5.8.0
* **Node Version:** v10.11.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**What did you expect to happen?**
It's a very similar request to this "ignoreTopLevelFunctions" option for "max-statement" rule here (https://github.com/eslint/eslint/issues/4309). Please enable the same flag for max-lines-per-function rule. Thank you!

**Comment by peteward44** [comment]
You can use the ```IIFEs: false``` option to ignore top-level functions
