### ISSUE TITLE
lint ts report Cannot read property 'body' of null

### ISSUE THREAD

**Issue by clock157** [eslint/eslint#11464]
**Tell us about your environment**

* **ESLint Version:** 5.15.0
* **Node Version:** 8.11.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
@typescript-eslint/parser
**Please show your full configuration:**
```js
module.exports = {
  extends: [
    'react-app',
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
  ],
  rules: {
    strict: [0],
    'no-sequences': [0],
    'no-mixed-operators': [0],
    'react/react-in-jsx-scope': [0],
    'no-useless-escape': [0],
  },
};

```
<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```ts
// AvatarItem.d.ts
import * as React from 'react';
export interface IAvatarItemProps {
  tips: React.ReactNode;
  src: string;
  style?: React.CSSProperties;
}

export default class AvatarItem extends React.Component<IAvatarItemProps, any> {
  constructor(props: IAvatarItemProps);
}
```

```bash
npx eslint --ext=ts AvatarItem.d.ts
```

**What did you expect to happen?**
lint result

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
Cannot read property 'body' of null
```

I have located the error location where in the `no-useless-constructor.js`, line 169

```js
function checkForConstructor(node) {
            if (node.kind !== "constructor") {
                return;
            }

            const body = node.value.body.body;  // <---- here
            const ctorParams = node.value.params;
            const superClass = node.parent.parent.superClass;
```

Is there have a bug or our wrong code? 

**Are you willing to submit a pull request to fix this bug?**

**Comment by g-plane** [comment]
Hi @clock157 , thanks for this issue.

This is about TypeScript. We recommend you to use [`@typescript-eslint/no-useless-constructor`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md).

**Comment by clock157** [comment]
thanks, @g-plane.

```diff
"rules": {
+       "no-useless-constructor": "off",
+       "@typescript-eslint/no-useless-constructor": "error",
}
```
no error anymore, but, is there any way to auto apply different rules between extension like js and ts

**Comment by platinumazure** [comment]
@clock157 You can use config overrides:

```json
{
    "rules": {
        "no-useless-constructor": "error"
    },
    "overrides": [
        {
            "files": "**/*.ts",
            "rules": {
                "no-useless-constructor": "off",
                "@typescript-eslint/no-useless-constructor": "error"
            }
        }
    ]
}
```

More info: https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns

**Comment by clock157** [comment]
@platinumazure thank you, it works. but `extends` not work in `overrides`, so I copy all rules from source file which I want extends, is there any better way to do this?

**Comment by ljharb** [comment]
this needs to be reopened; it crashes on TS because there's no `body`.

**Comment by platinumazure** [comment]
@ljharb In cases where there are deviations from the ESTree spec (and it's not due to a Stage 3 feature, etc.), we recommend that custom/plugin rules be created. According to ESTree for JS, the constructor function body should not be null. Since TS supports declaration-only constructors with no body, `@typescript-eslint/eslint-plugin` should implement a custom rule here.

**Comment by ljharb** [comment]
@platinumazure could perhaps the TS parser be fixed as well, to ensure that it's non-null?

**Comment by platinumazure** [comment]
@ljharb Maybe, but this discussion should take place on the [typescript-eslint project](https://github.com/typescript-eslint/typescript-eslint). Please file an issue there. Thanks!

**Comment by paulmelnikow** [comment]
I wanted to note to others reading this that the related issue is typescript-eslint/typescript-eslint#420.
