### ISSUE TITLE
Relative paths in ESLint config should be treated as relative to config dir

### ISSUE THREAD

**Issue by andrew-humu** [eslint/eslint#11466]
**The version of ESLint you are using.**

`5.15.0`

**The problem you want to solve.**

ESLint parsers do not get information about the path to the configuration file in which the parserOptions they are receiving was specified.

This manifests in issues like the following:

https://github.com/typescript-eslint/typescript-eslint/issues/251

**Your take on the correct solution to problem.**

The solution that suggests itself to me is to pass context about the configuration file to parsers, so that they can use that information to resolve relative paths.

**Are you willing to submit a pull request to implement this change?**

I'm game to attempt a patch, if my solution sounds reasonable.

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

I'm not sure it makes sense to provide parser with the path to a config file, for a few reasons:

* The parser options could be coming from multiple different files simultaneously (e.g. if someone is using a shareable config with parser options, and also sets their own parser options).
* The parser options might not be coming from a file at all (e.g. if they're configured on the command line)
* From looking at https://github.com/typescript-eslint/typescript-eslint/issues/251, it seems like the goal is to be able to determine the user's project root, but a config file might not be in the user's project root (e.g. if they're using [config cascading](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) or the `--config` flag).

I think it would be better to either figure out the user's project root out-of-band, or have the user provide an absolute path.

**Comment by andrew-humu** [comment]
> * The parser options could be coming from multiple different files simultaneously

Yeah.  I wondered about that, too.  I noticed there is an internal helper called `getConfigVector`, which might be closer to what you'd really need?  But I'm not sure that's a very friendly UI for parser developers.

I can't think of a clean solution to this short of deprecating everything other than `.js` configs, or removing support for config cascade in favour of "extends".
