### ISSUE TITLE
eslint silently ignores .eslintrc.js when function is exported

### ISSUE THREAD

**Issue by matthargett** [eslint/eslint#11475]
**Tell us about your environment**

I'm contributing to the react-navigation-core project on Windows, with Ubuntu 16.04 in WSL.

* **ESLint Version:**

5.14.1 and 5.15.0

* **Node Version:**
nodejs 10.12.0 in Ubuntu/x64 and nodejs 10.8.0 in Windows.

* **npm Version:**

6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// eslint-disable-next-line import/no-commonjs
module.exports = function(x) { return {
  "extends": ["eslint-config-satya164"],

  "plugins": ["react-native-globals"],

  "env": {
    "react-native-globals/all": true,
  },

  "settings": {
    "react": {
      "version": "detect"
    }
  },

  "rules": {
    "import/no-unresolved": "off",
    "react/sort-comp": "off",
    "jest/no-disabled-tests": "off",
  }
};
};
```

relevant part of package.json:
```json
"devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-object-rest-spread": "7.3.4",
    "@babel/plugin-transform-block-scoping": "7.3.4",
    "@babel/plugin-transform-modules-commonjs": "7.2.0",
    "@babel/plugin-transform-flow-strip-types": "7.3.4",
    "@babel/plugin-transform-react-jsx": "7.3.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.49.2",
    "conventional-changelog-cli": "^2.0.5",
    "eslint": "^5.15.0",
    "eslint-config-satya164": "^2.1.0",
    "eslint-plugin-react-native-globals": "^0.1.2",
    "husky": "^1.1.2",
    "jest": "^24.1.0",
    "jest-expo": "^32.0.0",
    "prettier": "^1.13.6",
    "prop-types": "^15.7.2",
    "react": "16.6.3",
    "react-dom": "16.6.3",
    "react-native": "^0.58.6",
    "react-test-renderer": "16.6.3",
    "release-it": "^7.6.1",
    "ts-jest": "^24.0.0",
    "typescript": "^3.3.3333"
  },```



```

```bash
eslint .
```

**What did you expect to happen?**

I expected eslint to pick up the configuration in my .eslintrc.js like babel does for babel.config.js. If I change the export to a straight hash, the configuration works.

**What actually happened? Please include the actual, raw output from ESLint.**

It did not pick up the configuration, and adding console.logs showed that the exported function wasn't executed. The symptom was this output:
```
$ eslint --config ./.eslintrc.js  .

C:\Users\matt\workspace\react-navigation-core\example\App.js
  1:1  error  Parsing error: The keyword 'import' is reserved

C:\Users\matt\workspace\react-navigation-core\example\src\EventsStack.js
  1:1  error  Parsing error: The keyword 'import' is reserved
```

**Are you willing to submit a pull request to fix this bug?**
yes, if the functionality is supposed to be supported. if it's not supposed to be supported, I can contribute a documentation change to explicitly communicate what the supported module export needs to look like.

**Comment by platinumazure** [comment]
Hi @matthargett, thanks for the issue.

With the current ESLint configuration logic, a JS config does need to specifically export an object. So this is currently working as designed.

Related: https://github.com/eslint/rfcs/pull/9, which explores an overhaul of the config file format which would support function exports

**Comment by matthargett** [comment]
Ok. Which repo/directory contains the documentation so I can document the explicitly narrow format?

**Comment by not-an-aardvark** [comment]
The documentation for config files is found in this repo, in the file [`docs/user-guide/configuring.md`](https://github.com/eslint/eslint/blob/b00a5e9d8dc6c5f77eb0e4e0c58dfaf12a771d7b/docs/user-guide/configuring.md).

The format for `.eslintrc.js` files is currently described in the ["Configuration File Formats"](https://github.com/eslint/eslint/blob/b00a5e9d8dc6c5f77eb0e4e0c58dfaf12a771d7b/docs/user-guide/configuring.md#configuration-file-formats) section:

> **JavaScript** - use .eslintrc.js and export an object containing your configuration.

So perhaps an additional note about not allowing functions could be added there. Alternatively, if there's a different change that you think would make it more clear, we'd certainly be happy to take a look at that too.
