### ISSUE TITLE
Validate against invalid rule schema defaults in RuleTester

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#11473]
**The version of ESLint you are using.**

v5.15.0

**The problem you want to solve.**

As of v5.14.0, we allow rule schemas to include the `default` keyword to specify default options. However, it's easy for a rule author to inadvertently use the `default` keyword in a place where the keyword is ignored, resulting in a buggy rule. (Also see: https://github.com/eslint/eslint/pull/11427)

**Your take on the correct solution to problem.**

When we validate rule schemas in `RuleTester`, we should use the new `strictDefaults` option in Ajv to raise an error if a rule schema has an invalid `default` keyword.

This is a breaking change for users who use `RuleTester`, because `RuleTester` would sometimes start reporting additional validation errors. However, rules themselves would still work as before, even if they contain invalid defaults. Additionally, the impact is expected to be very low since we only added support for the `default` keyword recently.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by aladdin-add** [comment]
And, we can enable `validateSchema: true` in rule tester.

https://github.com/eslint/eslint/blob/b00a5e9d8dc6c5f77eb0e4e0c58dfaf12a771d7b/lib/util/ajv.js#L18-L25

**Comment by not-an-aardvark** [comment]
This proposal was accepted in [yesterday's TSC meeting](https://github.com/eslint/tsc-meetings/blob/137fbe2be55499cd75f28a008900803078d22dfd/notes/2019/2019-03-14.md#validate-against-invalid-rule-schema-defaults-in-ruletester).
