### ISSUE TITLE
Proposal: show a warning when a rule is unnecessarily disabled

### ISSUE THREAD

**Issue by lensbart** [eslint/eslint#11493]
Hi,

First of all, thanks for developing and maintaining such a great tool. I really appreciate it!

Here’s a proposal: show a warning for every `eslint-disable` comment that doesn’t actively suppress ESLint errors or warning. The idea would be analogous to how Flow’s `// $FlowFixMe` works. One advantage would be that you would get warned after relaxing rules in `.eslintrc`.

I currently don’t have the capacity to submit a pull request, but wanted to propose the idea anyway.

(ESLint version 5.15.1)

**Comment by not-an-aardvark** [comment]
Hi, have you seen the [`--report-unused-disable-directives`](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives) flag? It seems to do what you're asking.

**Comment by lensbart** [comment]
Thanks. I was looking for a rule in `.eslintrc.js` in order to enable editor integration, but your suggestion lead me to [this issue](https://github.com/eslint/eslint/issues/9382) where the proposal has been decided against.

However, the compromise of only allowing `off/warn` seems reasonable to me.

I’ll close this issue because it’s a duplicate
