### ISSUE TITLE
AST-based auto fixing

### ISSUE THREAD

**Issue by g-plane** [eslint/eslint#11494]
**The version of ESLint you are using.**
5.x

**The problem you want to solve.**
Currently, the auto fixing mechanism is string-based. It works well, but it's not flexible enough.

For example, let's see the fixer of the rule [`prefer-const`](https://github.com/eslint/eslint/blob/e7266c2478aff5d66e7859313feb49e3a129f85e/lib/rules/prefer-const.js#L453):
https://github.com/eslint/eslint/blob/e7266c2478aff5d66e7859313feb49e3a129f85e/lib/rules/prefer-const.js#L453
The current solution of the auto fixing is just replace the first token of the AST node. Nothing bad here, but could be better if we support AST-based auto fixing like this:

```js
fix: shouldFix
    ? fixer => {
        node.kind = "const";
        return fixer.modifyNode(node);
    }
    : null
```

That will make easier for writing auto fixing of rules, and it can increase the readability of the source code of rules, IMHO.

**Your take on the correct solution to problem.**
To achieve that, we must update the logic of the auto fixing mechanism.

1. Use code generator to generate code from AST. There are tools which are able to do that, e.g. `@babel/generator` and `recast`. However, `@babel/generator` seems opinionated because it may change the code style of the whole source file, which may confuse the users. While `recast` only change the code where you have modified the AST.

    For references:

  - [@babel/generator](https://babeljs.io/docs/en/babel-generator)
  - [recast](https://github.com/benjamn/recast)

2. Traditional string-based auto fixing must be kept. As we know, AST is not CST. For some stylistic-related rules, it's impossible to fix problems according to AST.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by aladdin-add** [comment]
https://github.com/Rich-Harris/magic-string is another choice -- seems it has a better perf.

**Comment by platinumazure** [comment]
I think something like this will need an RFC since this would be a pretty significant core change. I've added the "needs design" label to reflect this.

I'm :+1: to the idea but I want to make sure we spend a lot of time designing this and making it good. :smile:

**Comment by ilyavolodin** [comment]
This has been attempted before. You either have to have CST instead of AST to be able to fix stylistic related rules, or you have to have two completely different mechanisms for fixing rules. Which would be confusing to the rule creators. In general, this would be a pretty big change, and I'm not convinced that it's worth it.

**Comment by not-an-aardvark** [comment]
I'm in favor of the idea but I agree qith @platinumazure that more design/probably an RFC will be needed.
