### ISSUE TITLE
eslint adds extra parentheses in certain scenarios, that creates a syntax error when auto fix/fix on save

### ISSUE THREAD

**Issue by jcursoli** [eslint/eslint#11507]
**Tell us about your environment**

* **ESLint Version:** 5.14.0 - 5.15.1
* **Node Version:** v10.14.1 but also reproducable on eslint demo (will provide link)
* **npm Version:** 6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?** Babel-ESLint

**Please show your full configuration:** 

<details>
<summary>Configuration</summary>

```js
{
    "parser": "babel-eslint",
    "extends": ["airbnb", "plugin:jsx-a11y/recommended"],
    "settings": {
        "import/resolver": {
            "node": {
                "extensions": [
                    ".js",
                    ".jsx",
                    ".json",
                    ".less"
                  ],
                "paths": [
                    "./src/web",
                    "./src/common",
                    "node_modules",
                    "./src/web/toolkit/util/helperUtils.js",
                    "./test/common"
                ]
            }
        }
    },
    "env": {
        "node": true,
        "es6": true,
        "mocha": true,
        "browser": true,
        "jquery": true,
        "jest": true
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true,
            "modules": true
        }
    },
    "plugins": ["react", "import", "jsx-a11y"],
    "rules": {
        "eqeqeq": "off",
        "linebreak-style": "off",
        "no-plusplus": "off",
        "class-methods-use-this": "off",
        "no-return-assign": "off",
        "no-underscore-dangle": "off",
        "import/no-named-as-default": "off",
        "import/prefer-default-export": "off",
        "react/destructuring-assignment": "off",
        "no-void": "off",
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "react/jsx-indent": ["error", 4],
        "react/prop-types": [
            2,
            {
                "ignore": [
                    "location",
                    "router",
                    "push",
                    "pop",
                    "children",
                    "params",
                    "routes"
                ]
            }
        ],
        "react/jsx-indent-props": [2, 4],
        "react/jsx-curly-spacing": [
            2,
            {
                "when": "never",
                "children": true
            }
        ],
        "no-param-reassign": [
            "error",
            {
                "props": false
            }
        ],
        "react/jsx-uses-vars": 2,
        "comma-dangle": ["error", "always-multiline"],
        "id-length": [
            2,
            {
                "exceptions": ["e", "i", "t"]
            }
        ],
        "max-len": [1, 80],
        "import/no-duplicates": 2,
        "no-duplicate-imports": 0,
        "react/no-unknown-property": 2,
        "react/jsx-filename-extension": [
            2,
            {
                "extensions": [".js", ".jsx"]
            }
        ],
        "react/sort-comp": [
            2,
            {
                "order": [
                    "static-methods",
                    "props",
                    "context",
                    "lifecycle",
                    "everything-else",
                    "render"
                ]
            }
        ],
        "arrow-parens": 0,
        "import/no-extraneous-dependencies": 0
    },
    "globals": {
        "__DEV__": false,
        "__SERVER__": false,
        "__TEST__": false,
        "__LOCAL_ORIGIN__": false,
        "getText": false,
        "NOOP": false,
        "promise": false
    }
}

```

</details>

**What did you do?**
This snippet of code below breaks when eslint does an auto fix, causing it to add extra parentheses resulting in a syntax error. Below that will be the "fixed version". this is reproducible on the eslint demo site.

```js
import React from 'react';

class HeaderComponent extends React.Component {
    anActionThatDoesSomehting() {
         // a comment
        return surePrepActor.generateSurePrepToken()
            .then((result) => this.logout(result.url + result.token), (error) =>
            // a comment to tell me something
                this.someMethod()
            );
    }

    render() {
        return <header />;
    }
}

const SOME_METHOD_THAT_BREAKS_ESLINT = (state) => ({
    user: state.actors.user,
});

export default HeaderComponent;

```
Broken "fixed" code below (notice the extra parentheses created by eslint)
```js
import React from "react";

class HeaderComponent extends React.Component {
    anActionThatDoesSomehting () {

        // A comment
        return surePrepActor.generateSurePrepToken().
            then((result) => this.logout(result.url + result.token), (error) => (
            // a comment to tell me something
                this.someMethod()
                                        )
                                                                       )
            );
    }
    render() {
        return <header />;
    }
}

const SOME_METHOD_THAT_BREAKS_ESLINT = (state) => ( ({
    "user": state.actors.user
});

export default HeaderComponent;


```

```bash

```

**What did you expect to happen?**
no extra parentheses to be generated creating a parsing error.
here is a link to the demo site, im not sure what rule breaks the code.
[demo](https://eslint.org/demo/#eyJ0ZXh0IjoiaW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JztcblxuY2xhc3MgSGVhZGVyQ29tcG9uZW50IGV4dGVuZHMgUmVhY3QuQ29tcG9uZW50IHtcbiAgICBhbkFjdGlvblRoYXREb2VzU29tZWh0aW5nKCkge1xuICAgICAgICAgLy8gYSBjb21tZW50XG4gICAgICAgIHJldHVybiBzdXJlUHJlcEFjdG9yLmdlbmVyYXRlU3VyZVByZXBUb2tlbigpXG4gICAgICAgICAgICAudGhlbigocmVzdWx0KSA9PiB0aGlzLmxvZ291dChyZXN1bHQudXJsICsgcmVzdWx0LnRva2VuKSwgKGVycm9yKSA9PlxuICAgICAgICAgICAgLy8gYSBjb21tZW50IHRvIHRlbGwgbWUgc29tZXRoaW5nXG4gICAgICAgICAgICAgICAgdGhpcy5zb21lTWV0aG9kKClcbiAgICAgICAgICAgICk7XG4gICAgfVxuXG4gICAgcmVuZGVyKCkge1xuICAgICAgICByZXR1cm4gPGhlYWRlciAvPjtcbiAgICB9XG59XG5cbmNvbnN0IFNPTUVfTUVUSE9EX1RIQVRfQlJFQUtTX0VTTElOVCA9IChzdGF0ZSkgPT4gKHtcbiAgICB1c2VyOiBzdGF0ZS5hY3RvcnMudXNlcixcbn0pO1xuXG5leHBvcnQgZGVmYXVsdCBIZWFkZXJDb21wb25lbnQ7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlLCJpbXBsaWVkU3RyaWN0Ijp0cnVlLCJnbG9iYWxSZXR1cm4iOnRydWV9fSwicnVsZXMiOnsiYWNjZXNzb3ItcGFpcnMiOjIsImFycmF5LWJyYWNrZXQtbmV3bGluZSI6MiwiYXJyYXktYnJhY2tldC1zcGFjaW5nIjoyLCJhcnJheS1jYWxsYmFjay1yZXR1cm4iOjIsImFycmF5LWVsZW1lbnQtbmV3bGluZSI6MiwiYXJyb3ctYm9keS1zdHlsZSI6MiwiYXJyb3ctcGFyZW5zIjoyLCJhcnJvdy1zcGFjaW5nIjoyLCJibG9jay1zY29wZWQtdmFyIjoyLCJibG9jay1zcGFjaW5nIjoyLCJicmFjZS1zdHlsZSI6MiwiY2FsbGJhY2stcmV0dXJuIjoyLCJjYW1lbGNhc2UiOjIsImNhcGl0YWxpemVkLWNvbW1lbnRzIjoyLCJjbGFzcy1tZXRob2RzLXVzZS10aGlzIjoyLCJjb21tYS1kYW5nbGUiOjIsImNvbW1hLXNwYWNpbmciOjIsImNvbW1hLXN0eWxlIjoyLCJjb21wbGV4aXR5IjoyLCJjb21wdXRlZC1wcm9wZXJ0eS1zcGFjaW5nIjoyLCJjb25zaXN0ZW50LXJldHVybiI6MiwiY29uc2lzdGVudC10aGlzIjoyLCJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiY3VybHkiOjIsImRlZmF1bHQtY2FzZSI6MiwiZG90LWxvY2F0aW9uIjoyLCJkb3Qtbm90YXRpb24iOjIsImVvbC1sYXN0IjoyLCJlcWVxZXEiOjIsImZvci1kaXJlY3Rpb24iOjIsImZ1bmMtY2FsbC1zcGFjaW5nIjoyLCJmdW5jLW5hbWUtbWF0Y2hpbmciOjIsImZ1bmMtbmFtZXMiOjIsImZ1bmMtc3R5bGUiOjIsImZ1bmN0aW9uLXBhcmVuLW5ld2xpbmUiOjIsImdlbmVyYXRvci1zdGFyLXNwYWNpbmciOjIsImdldHRlci1yZXR1cm4iOjIsImdsb2JhbC1yZXF1aXJlIjoyLCJndWFyZC1mb3ItaW4iOjIsImhhbmRsZS1jYWxsYmFjay1lcnIiOjIsImlkLWJsYWNrbGlzdCI6MiwiaWQtbGVuZ3RoIjoyLCJpZC1tYXRjaCI6MiwiaW1wbGljaXQtYXJyb3ctbGluZWJyZWFrIjoyLCJpbmRlbnQiOjIsImluZGVudC1sZWdhY3kiOjIsImluaXQtZGVjbGFyYXRpb25zIjoyLCJqc3gtcXVvdGVzIjoyLCJrZXktc3BhY2luZyI6Miwia2V5d29yZC1zcGFjaW5nIjoyLCJsaW5lLWNvbW1lbnQtcG9zaXRpb24iOjIsImxpbmVicmVhay1zdHlsZSI6MiwibGluZXMtYXJvdW5kLWNvbW1lbnQiOjIsImxpbmVzLWFyb3VuZC1kaXJlY3RpdmUiOjIsImxpbmVzLWJldHdlZW4tY2xhc3MtbWVtYmVycyI6MiwibWF4LWNsYXNzZXMtcGVyLWZpbGUiOjIsIm1heC1kZXB0aCI6MiwibWF4LWxlbiI6MiwibWF4LWxpbmVzIjoyLCJtYXgtbGluZXMtcGVyLWZ1bmN0aW9uIjoyLCJtYXgtbmVzdGVkLWNhbGxiYWNrcyI6MiwibWF4LXBhcmFtcyI6MiwibWF4LXN0YXRlbWVudHMiOjIsIm1heC1zdGF0ZW1lbnRzLXBlci1saW5lIjoyLCJtdWx0aWxpbmUtY29tbWVudC1zdHlsZSI6MiwibXVsdGlsaW5lLXRlcm5hcnkiOjIsIm5ldy1jYXAiOjIsIm5ldy1wYXJlbnMiOjIsIm5ld2xpbmUtYWZ0ZXItdmFyIjoyLCJuZXdsaW5lLWJlZm9yZS1yZXR1cm4iOjIsIm5ld2xpbmUtcGVyLWNoYWluZWQtY2FsbCI6Miwibm8tYWxlcnQiOjIsIm5vLWFycmF5LWNvbnN0cnVjdG9yIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1hd2FpdC1pbi1sb29wIjoyLCJuby1iaXR3aXNlIjoyLCJuby1idWZmZXItY29uc3RydWN0b3IiOjIsIm5vLWNhbGxlciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNhdGNoLXNoYWRvdyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uZnVzaW5nLWFycm93IjoyLCJuby1jb25zb2xlIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udGludWUiOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kaXYtcmVnZXgiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1kdXBsaWNhdGUtaW1wb3J0cyI6Miwibm8tZWxzZS1yZXR1cm4iOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LWZ1bmN0aW9uIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lcS1udWxsIjoyLCJuby1ldmFsIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dGVuZC1uYXRpdmUiOjIsIm5vLWV4dHJhLWJpbmQiOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtbGFiZWwiOjIsIm5vLWV4dHJhLXBhcmVucyI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZsb2F0aW5nLWRlY2ltYWwiOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBsaWNpdC1jb2VyY2lvbiI6Miwibm8taW1wbGljaXQtZ2xvYmFscyI6Miwibm8taW1wbGllZC1ldmFsIjoyLCJuby1pbmxpbmUtY29tbWVudHMiOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWludmFsaWQtdGhpcyI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLWl0ZXJhdG9yIjoyLCJuby1sYWJlbC12YXIiOjIsIm5vLWxhYmVscyI6Miwibm8tbG9uZS1ibG9ja3MiOjIsIm5vLWxvbmVseS1pZiI6Miwibm8tbG9vcC1mdW5jIjoyLCJuby1tYWdpYy1udW1iZXJzIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtb3BlcmF0b3JzIjoyLCJuby1taXhlZC1yZXF1aXJlcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1tdWx0aS1hc3NpZ24iOjIsIm5vLW11bHRpLXNwYWNlcyI6Miwibm8tbXVsdGktc3RyIjoyLCJuby1tdWx0aXBsZS1lbXB0eS1saW5lcyI6Miwibm8tbmF0aXZlLXJlYXNzaWduIjoyLCJuby1uZWdhdGVkLWNvbmRpdGlvbiI6Miwibm8tbmVnYXRlZC1pbi1saHMiOjIsIm5vLW5lc3RlZC10ZXJuYXJ5IjoyLCJuby1uZXciOjIsIm5vLW5ldy1mdW5jIjoyLCJuby1uZXctb2JqZWN0IjoyLCJuby1uZXctcmVxdWlyZSI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tbmV3LXdyYXBwZXJzIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1vY3RhbC1lc2NhcGUiOjIsIm5vLXBhcmFtLXJlYXNzaWduIjoyLCJuby1wYXRoLWNvbmNhdCI6Miwibm8tcGx1c3BsdXMiOjIsIm5vLXByb2Nlc3MtZW52IjoyLCJuby1wcm9jZXNzLWV4aXQiOjIsIm5vLXByb3RvIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1yZXN0cmljdGVkLWdsb2JhbHMiOjIsIm5vLXJlc3RyaWN0ZWQtaW1wb3J0cyI6Miwibm8tcmVzdHJpY3RlZC1tb2R1bGVzIjoyLCJuby1yZXN0cmljdGVkLXByb3BlcnRpZXMiOjIsIm5vLXJlc3RyaWN0ZWQtc3ludGF4IjoyLCJuby1yZXR1cm4tYXNzaWduIjoyLCJuby1yZXR1cm4tYXdhaXQiOjIsIm5vLXNjcmlwdC11cmwiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZWxmLWNvbXBhcmUiOjIsIm5vLXNlcXVlbmNlcyI6Miwibm8tc2hhZG93IjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhY2VkLWZ1bmMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXN5bmMiOjIsIm5vLXRhYnMiOjIsIm5vLXRlbXBsYXRlLWN1cmx5LWluLXN0cmluZyI6Miwibm8tdGVybmFyeSI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXRocm93LWxpdGVyYWwiOjIsIm5vLXRyYWlsaW5nLXNwYWNlcyI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZGVmLWluaXQiOjIsIm5vLXVuZGVmaW5lZCI6Miwibm8tdW5kZXJzY29yZS1kYW5nbGUiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bm1vZGlmaWVkLWxvb3AtY29uZGl0aW9uIjoyLCJuby11bm5lZWRlZC10ZXJuYXJ5IjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWV4cHJlc3Npb25zIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlLWJlZm9yZS1kZWZpbmUiOjIsIm5vLXVzZWxlc3MtY2FsbCI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1jb21wdXRlZC1rZXkiOjIsIm5vLXVzZWxlc3MtY29uY2F0IjoyLCJuby11c2VsZXNzLWNvbnN0cnVjdG9yIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8tdXNlbGVzcy1yZW5hbWUiOjIsIm5vLXVzZWxlc3MtcmV0dXJuIjoyLCJuby12YXIiOjIsIm5vLXZvaWQiOjIsIm5vLXdhcm5pbmctY29tbWVudHMiOjIsIm5vLXdoaXRlc3BhY2UtYmVmb3JlLXByb3BlcnR5IjoyLCJuby13aXRoIjoyLCJub25ibG9jay1zdGF0ZW1lbnQtYm9keS1wb3NpdGlvbiI6Miwib2JqZWN0LWN1cmx5LW5ld2xpbmUiOjIsIm9iamVjdC1jdXJseS1zcGFjaW5nIjoyLCJvYmplY3QtcHJvcGVydHktbmV3bGluZSI6Miwib2JqZWN0LXNob3J0aGFuZCI6Miwib25lLXZhciI6Miwib25lLXZhci1kZWNsYXJhdGlvbi1wZXItbGluZSI6Miwib3BlcmF0b3ItYXNzaWdubWVudCI6Miwib3BlcmF0b3ItbGluZWJyZWFrIjoyLCJwYWRkZWQtYmxvY2tzIjoyLCJwYWRkaW5nLWxpbmUtYmV0d2Vlbi1zdGF0ZW1lbnRzIjoyLCJwcmVmZXItYXJyb3ctY2FsbGJhY2siOjIsInByZWZlci1jb25zdCI6MiwicHJlZmVyLWRlc3RydWN0dXJpbmciOjIsInByZWZlci1uYW1lZC1jYXB0dXJlLWdyb3VwIjoyLCJwcmVmZXItbnVtZXJpYy1saXRlcmFscyI6MiwicHJlZmVyLW9iamVjdC1zcHJlYWQiOjIsInByZWZlci1wcm9taXNlLXJlamVjdC1lcnJvcnMiOjIsInByZWZlci1yZWZsZWN0IjoyLCJwcmVmZXItcmVzdC1wYXJhbXMiOjIsInByZWZlci1zcHJlYWQiOjIsInByZWZlci10ZW1wbGF0ZSI6MiwicXVvdGUtcHJvcHMiOjIsInF1b3RlcyI6MiwicmFkaXgiOjIsInJlcXVpcmUtYXRvbWljLXVwZGF0ZXMiOjIsInJlcXVpcmUtYXdhaXQiOjIsInJlcXVpcmUtanNkb2MiOjIsInJlcXVpcmUtdW5pY29kZS1yZWdleHAiOjIsInJlcXVpcmUteWllbGQiOjIsInJlc3Qtc3ByZWFkLXNwYWNpbmciOjIsInNlbWkiOjIsInNlbWktc3BhY2luZyI6Miwic2VtaS1zdHlsZSI6Miwic29ydC1pbXBvcnRzIjoyLCJzb3J0LWtleXMiOjIsInNvcnQtdmFycyI6Miwic3BhY2UtYmVmb3JlLWJsb2NrcyI6Miwic3BhY2UtYmVmb3JlLWZ1bmN0aW9uLXBhcmVuIjoyLCJzcGFjZS1pbi1wYXJlbnMiOjIsInNwYWNlLWluZml4LW9wcyI6Miwic3BhY2UtdW5hcnktb3BzIjoyLCJzcGFjZWQtY29tbWVudCI6Miwic3RyaWN0IjoyLCJzd2l0Y2gtY29sb24tc3BhY2luZyI6Miwic3ltYm9sLWRlc2NyaXB0aW9uIjoyLCJ0ZW1wbGF0ZS1jdXJseS1zcGFjaW5nIjoyLCJ0ZW1wbGF0ZS10YWctc3BhY2luZyI6MiwidW5pY29kZS1ib20iOjIsInVzZS1pc25hbiI6MiwidmFsaWQtanNkb2MiOjIsInZhbGlkLXR5cGVvZiI6MiwidmFycy1vbi10b3AiOjIsIndyYXAtaWlmZSI6Miwid3JhcC1yZWdleCI6MiwieWllbGQtc3Rhci1zcGFjaW5nIjoyLCJ5b2RhIjoyfSwiZW52Ijp7ImJyb3dzZXIiOnRydWUsImNvbW1vbmpzIjpmYWxzZSwiZXM2IjpmYWxzZSwibm9kZSI6ZmFsc2V9fX0=). Also when I remove the comments it does not cause the error. But when i ran "fix" across the whole code base a few files broke that looked similar to this code.
**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by platinumazure** [comment]
It's not clear what rule is causing this, but I'm wondering if this is potentially fixed by PR #11407.

@jcursoli Do you have a way of testing using the branch associated with the PR I linked above?

**Comment by not-an-aardvark** [comment]
Closing on the assumption that this has been fixed by https://github.com/eslint/eslint/pull/11407, since it looks like the same issue. Feel free to comment if it hasn't been fixed in the latest version of ESLint.

**Comment by jcursoli** [comment]
I appreciate it, I verified it has been resolved. 👍
