### ISSUE TITLE
no-implicit-dependencies 

### ISSUE THREAD

**Issue by Yzrsah** [eslint/eslint#11501]
## `no-implicit-dependencies` rule

It would be excellent if we had a rule which worked similarly to the TSLint rule [no-implicit-dependencies](https://palantir.github.io/tslint/rules/no-implicit-dependencies)

It has been implemented as a plugin: [eslint-plugin-implicit-dependencies](https://github.com/lennym/eslint-plugin-implicit-dependencies)

But adding this plugin to all projects presents a challenge. We would like to keep the dependency count low.

The consistent usage in TSLint shows that it's a reasonable rule for ESLint.

**Comment by platinumazure** [comment]
Is this covered in [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node)?

We don't like to have runtime-specific rules in core ESLint, so I would be :-1: to adding this rule. (I'm aware we already have some Node-specific rules-- ideally we would deprecate and move those out of core at some point as well.)

**Comment by g-plane** [comment]
Yes, it seems that it's covered in `eslint-plugin-node`.

**Comment by Yzrsah** [comment]
Thank you
