### ISSUE TITLE
Browser version of 5.15.x does not work in IE 11

### ISSUE THREAD

**Issue by spahnke** [eslint/eslint#11504]
**Tell us about your environment**

* **ESLint Version:** 5.15.x
* **Node Version:** 11.11.0
* **npm Version:** 6.9.0

**What did you do?**

Built ESLint using
```sh
npm run webpack
```
and ran it in IE 11 (more precisely, in a web worker and in conjunction with the Monaco editor but that should not matter). The source code couldn't be parsed because it contains a lot of ES2015+ syntax like `const` and `let` since the recent change to Webpack. The Browserify version in `5.14.x` works in IE 11.

You can get a step further by changing the Webpack config to also transpile files from `node_modules` (including `.mjs` files apparently) like shown below. This makes sure to transpile to ES5 but I got stuck at this stage because IE still throws the error `Incorrect syntax in regular expression`. Since I saw nothing obvious in the source code I gave up at this point.

```js
rules: [
    {
        test: /\.m?js$/u,
        loader: "babel-loader",
        options: {
            presets: ["@babel/preset-env"]
        }
    }
]
```

So the question boils down to: What browsers do you intend to support with the browser variant of ESLint?

**Are you willing to submit a pull request to fix this bug?**
Not at the moment, sorry.

**Comment by not-an-aardvark** [comment]
Thanks for the report, I can reproduce this issue. It seems like `espree` isn't getting compiled to ES5 with the new build setup.

**Comment by spahnke** [comment]
Thanks so much for the fix!

It still doesn't quite work though. As I stated above, as soon as you load the ES5 compatible `eslint.js` in IE 11 you get the error `Incorrect syntax in regular expression`. It is reproducible with the following code. I don't know where this might be coming from as there is nothing super obvious in the code.

```html
<script src="eslint.js"></script>
<script>
	var linter = new eslint();
	console.log(linter.verify("var foo = 1", {
		"parserOptions": {
			"ecmaVersion": 5
		},
		"rules": {
			"semi": "warn"
		}
	}));
</script>
```

![image](https://user-images.githubusercontent.com/25029871/54475669-511da380-47f4-11e9-9a7e-0672226dc10a.png)
![image](https://user-images.githubusercontent.com/25029871/54475672-57138480-47f4-11e9-99e4-4d69fe464ecf.png)

P.S. Pardon the german error messages 😅

**Comment by g-plane** [comment]
Can you paste the whole line? Thanks.

**Comment by spahnke** [comment]
Sure, sorry about that!

```js
var $flags = __webpack_require__(199);

var $RegExp = global.RegExp;
var Base = $RegExp;
var proto = $RegExp.prototype;
var re1 = /a/g;
var re2 = /a/g; // "new" creates a new object, old webkit buggy here

var CORRECT_NEW = new $RegExp(re1) !== re1;

if (__webpack_require__(7) && (!CORRECT_NEW || __webpack_require__(8)(function () {
  re2[__webpack_require__(28)('match')] = false; // RegExp constructor can alter flags and IsRegExp works correct with @@match

  return $RegExp(re1) != re1 || $RegExp(re2) == re2 || $RegExp(re1, 'i') != '/a/i';
}))) {
  $RegExp = function RegExp(p, f) {
    var tiRE = this instanceof $RegExp;
    var piRE = isRegExp(p);
    var fiU = f === undefined;
    return !tiRE && piRE && p.constructor === $RegExp && fiU ? p : inheritIfRequired(CORRECT_NEW ? new Base(piRE && !fiU ? p.source : p, f) : Base((piRE = p instanceof $RegExp) ? p.source : p, piRE && fiU ? $flags.call(p) : f), tiRE ? this : proto, $RegExp);
  };
```

**Comment by g-plane** [comment]
Did you build ESLint yourself?

**Comment by spahnke** [comment]
Yes, I pulled the current master branch and build ESLint by running
```sh
npm run webpack
```

**Comment by g-plane** [comment]
Well, this is a bug from [`core-js`](https://github.com/zloirock/core-js/).

Look at Line 4795 in the picture you gave. There is a comment which is `RegExp constructor can alter flags and IsRegExp works correct with...`, and I found it: https://github.com/zloirock/core-js/search?q=RegExp+constructor+can+alter+flags+and+IsRegExp+works+correct+with&unscoped_q=RegExp+constructor+can+alter+flags+and+IsRegExp+works+correct+with .

It seems that we're using `core-js` v2, but `core-js` v3 is developing now, so I'm not sure if they fixed it.

**Comment by spahnke** [comment]
Hm, according to the changelog this was introduced 4 years ago
>**0.4.2 - 2015.01.10**
>* Object static methods accept primitives
>* RegExp constructor can alter flags (IE9+)
>* Added Array.prototype[Symbol.unscopables]

Why did it work with Browserify in version `5.14.1` though?

**Comment by zloirock** [comment]
It's not a bug from `core-js`, it's a bug it regexp pattern, wrapper just calls internally original `RegExp` constructor with the passed pattern.

**Comment by aladdin-add** [comment]
recently we are using `/u` flag in regex -- it may be related to this. can you see the error stack?

**Comment by spahnke** [comment]
@aladdin-add You are right!

It is the `createGlobalLinebreakMatcher` function in [ast-utils.js](https://github.com/eslint/eslint/blob/1f715a20c145d8ccc38f3310afccd838495d09d4/lib/util/ast-utils.js#L401). The `u`-flag was added in #11422.

![image](https://user-images.githubusercontent.com/25029871/54487173-03a44380-4893-11e9-87de-bc8142daecdf.png)
 
This whole "syntax error" thing threw me off; for some reason I assumed this whole time that the error occurs during the parsing phase of the file 😩🤦‍♂️

**Comment by not-an-aardvark** [comment]
I was under the impression that babel can polyfill the behavior of unicode regexes. Is that not the case?

**Comment by spahnke** [comment]
Hm, it can in principle ([Babel Regex](https://babeljs.io/docs/en/babel-plugin-transform-unicode-regex)). But I think there would be limitations for usages like
```js
return new RegExp(LINEBREAK_MATCHER.source, "gu");
// or
new RegExp(somePatternVariable, someFlagVariable)
```
because it can't really manipulate the content of those variables, right?

**Comment by not-an-aardvark** [comment]
I thought it would polyfill the `RegExp` constructor itself to handle those cases at runtime.

**Comment by zloirock** [comment]
It's too costly for runtime.

**Comment by spahnke** [comment]
Babel apparently uses the *regexpu* package to do the transform which has this exact [limitation](https://www.npmjs.com/package/regexpu#known-limitations). I couldn't find any polyfill of the `RegExp` contructor for the `u`-flag unfortunately.
