### ISSUE TITLE
"'BigInt' is not defined" for build-in BigInt

### ISSUE THREAD

**Issue by Nogias9x** [eslint/eslint#11524]
**My environment**

* **ESLint Version:** 5.15.2 (I just updated from 4.19.1 when I was attempting to void the issue)
* **Node Version:** v10.15.1
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** standard

**Please show your full configuration:**
I'm using standardjs

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let totalPrice = BigInt(0)
totalPrice += BigInt(123)
f (BigInt(totalPrice) === BigInt(0)) console.log('PAID')
```

```bash
standard --fix
```

**What did you expect to happen?**
BigInt should be recognized as build-in object and  there should not be "no-undef" error.

**What actually happened? Please include the actual, raw output from ESLint.**
"'BigInt' is not defined." error is thrown.

**Comment by ljharb** [comment]
BigInt is still stage 3, so even though it's shipping in browsers, eslint won't support it by default.

**Comment by not-an-aardvark** [comment]
To enable the `BigInt` global you can add a comment to your code:

```js
/* global BigInt */
```

To avoid needing to do this, you could ask the `standard` maintainers to enable `BigInt` in their configuration.

**Comment by amejiarosario** [comment]
related to: https://github.com/eslint/eslint/issues/10860

**Comment by leegee** [comment]
Would be convenient to have some kind `stage-3` or `node12` environment -- I can't find such a thing, are there any plans?

**Comment by aladdin-add** [comment]
We don't have a plan to accept new envs, but you can create an eslint plugin to do such a thing.

**Comment by vanduc1102** [comment]
i added 
```
'globals':{
    'BigInt':true
  },
```
to eslint config

**Comment by g-plane** [comment]
Closing now because it seems that this question has been answered. If you have any questions, feel free to ask us on [Gitter](https://gitter.im/eslint/eslint).

**Comment by Kostanos** [comment]
I don't think that the question was answered.
Defining BigInt as a global variable/function it is workaround that proposed here.

eslint should support BigInt by default for node > 10.4 where BigInt was introduced

**Comment by platinumazure** [comment]
Hi @Konstanos, ESLint does not make distinctions between different versions of runtimes in core logic and rules. I would invite you to look at [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) to see if they will be able to provide global support based on Node.js runtime version.

**Comment by vitaly-t** [comment]
The solutions above do not work `123n` format for big numbers.

**Comment by platinumazure** [comment]
@vitaly-t We now have `ecmaVersion: 2020` support in espree, which should allow you to use the literal syntax.
