### ISSUE TITLE
Allow specifying maxWarnings in the config as well as CLI

### ISSUE THREAD

**Issue by alexkrolick** [eslint/eslint#11523]
**The version of ESLint you are using.**

5.x

**The problem you want to solve.**

Scenario: extending a lint config that uses `warn` as the default level, but you want to enforce that the rules be escalated to errors (e.g. to get a non-zero exit code).

**Your take on the correct solution to problem.**

Allow specifiying `maxWarnings` in the checked-in lint config, rather than only as a command line parameter. This would allow the option to be checked in and not be accidentally omitted in a CI pipeline, for example.

**Are you willing to submit a pull request to implement this change?**

Yes

**Related**

- https://github.com/eslint/eslint/issues/7937
- https://github.com/facebook/create-react-app/pull/4916

**Comment by ilyavolodin** [comment]
Configs work per folder, or, with overrides, even per file, there're also shareable configs that come from outside of your working folder. All of the configs are combined together when linting a specific file. Global commands, like `maxWarnings` can't be defined in configs because there's no clear way to figure out how to combine them when they are mentioned in multiple config files.

**Comment by alexkrolick** [comment]
I'm not sure why the resolution priority would be different than something like `env` or even the list of rules. That said, it would be pretty bad practice for a plugin to define this option.

**Comment by ilyavolodin** [comment]
Difference between this and `env` is that `env` can cascade, as in, in one folder, you might have one `env` and in parent folder, you will have another. Resolution is pretty clear in that case. `maxWarnings` is global to the entire run, no matter which folders you selected, so it can't cascade. We also do not limit plugins and shareable configs in what they can and can't define. So there might be issues with that.
I'm not sure I understand your other suggestion, can you elaborate a bit more please?

**Comment by not-an-aardvark** [comment]
I think the other suggestion is the same as https://github.com/eslint/eslint/issues/9484.

**Comment by alexkrolick** [comment]
> As an alternative, what about an env var or separate flags config file to define the defaults for CLI params?

Example 1: you could define an environment variable called ESLINT_MAX_WARNINGS that would be used if the CLI flag was not passed; a team could use an env management option like a .env file to set it.

Example 2: what if flags could only be read from the default config file or the one passed with the --config CLI flag

**Comment by not-an-aardvark** [comment]
I'm confused about problem that this is trying to solve:

> Allow specifiying `maxWarnings` in the checked-in lint config, rather than only as a command line parameter. This would allow the option to be checked in and not be accidentally omitted in a CI pipeline, for example.

Why is it more likely for a CLI flag to be omitted than an environment variable?

**Comment by alexkrolick** [comment]
> Why is it more likely for a CLI flag to be omitted than an environment variable?

There is environment management tooling that can help set up CI/dev environments with the right values, but I agree it's not a great improvement

**Comment by mysticatea** [comment]
Related to https://github.com/eslint/rfcs/pull/18, how about adding `maxWarnings` property to the top-level of the config which is at the project root?

**Comment by not-an-aardvark** [comment]
I don't really see how this is related to https://github.com/eslint/rfcs/pull/18. In the long term, I'm not opposed to adding top-level-config-only features, but it seems like `--ext` and `--rulesdir` would be a higher priority than `--max-warnings`.
