### ISSUE TITLE
Definition for plugin rule not found by verify

### ISSUE THREAD

**Issue by cloewen8** [eslint/eslint#11573]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 11.6.0
* **npm Version:** 6.5.0-next.0

* **eslint-plugin-no-for-each plugin:** version 0.1.14

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
	"plugins": [
		"no-for-each"
	],
	"rules": {
		"no-for-each/no-for-each": "error"
	}
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

index.js:
```js
var CLIEngine = require("eslint").CLIEngine,
    linter = require("eslint").linter;

var cli = new CLIEngine();

var config = cli.getConfigForFile("myfile.js");

console.log(linter.verify("var foo;", config));
```

I was noticing far more errors related to rule definitions not being found when using the verify API. So I created a small package to try and reproduce the error.

In one script, I used verify.
```bash
node index.js
```
In a second script I called eslint normally.
```bash
eslint myfile.js
```
myfile.js:
```js
var foo;
```

Reproduction: https://drive.google.com/file/d/1ONZIkdpU1A-YKvaGaRq9kzYnwOlrA4IJ/view?usp=sharing

**What did you expect to happen?**
I would expect both scripts to not produce any errors, since they are using the exact same input and configuration.

**What actually happened? Please include the actual, raw output from ESLint.**
The first script produced:
```text
[ { ruleId: 'no-for-each/no-for-each',
    severity: 2,
    message:
     "Definition for rule 'no-for-each/no-for-each' was not found",
    line: 1,
    column: 1,
    nodeType: null } ]
```
The second script produced:
```text
```

**Are you willing to submit a pull request to fix this bug?**
Yes, if I can identify the bug, a pull request is desired, and I can determine an adequate fix.

**Comment by platinumazure** [comment]
Hi @cloewen8, thanks for the issue.

This isn't a bug. Linter only starts with awareness of the core ESLint rules, and it must be told about non-core rules via [`Linter#addRules()`](https://eslint.org/docs/developer-guide/nodejs-api#linterdefinerules). For example, you could probably pass in `require("eslint-plugin-myPlugin").rules`.

That said, if you want to take advantage of the plugin loading mechanism, I strongly recommend using CLIEngine instead. In that case, you could use `CLIEngine#addPlugin`(https://eslint.org/docs/developer-guide/nodejs-api#cliengineaddplugin) to define the plugin, and then use `CLIEngine#executeOnText`(https://eslint.org/docs/developer-guide/nodejs-api#cliengineexecuteontext) to lint the text. This is a slightly more convenient interface that abstracts away some of the internal configuration logic.

Hope this helps!
