### ISSUE TITLE
Rule 'prefer-object-spread' return unexpected result

### ISSUE THREAD

**Issue by copycut** [eslint/eslint#11582]
* ESLint Version: 5.16
* Node Version: 10.15.3
* npm Version: 6.9.0
* Babel-eslint: 10.0.1

When --fix is used on project, the result of converting Object.assign don't return the expected value.

## Previously

```js
const user = {name: 'user', id: 0};
return Object.assign({name: 'test'}, user); // {name: 'test', id:0}
```

## After convertion (--fix applied)

```js
const user = {name: 'user', id: 0};
return {name: 'test', ...user}; // {name: 'user', id: 0}
```

## Expected result

```js
const user = {name: 'user', id: 0};
return {...user, name: 'test'}; // {name: 'test', id: 0}
```

**Comment by g-plane** [comment]
Hi @copycut , thanks for this issue.

IMHO, this may not be a bug. When you use `Object.assign`, the properties from `user` will override those in `{name: 'test'}`, while object spread syntax does as well.

**Comment by copycut** [comment]
In fact, that was an error on our base code:
```js
[{a: 1}, {a: 2}, {a: 3}].map(t => Object.assign({a: 'x'}, t)); // [{a: 1}, {a: 2}, {a: 3}]
```
same as 

```js
 [{a: 1}, {a: 2}, {a: 3}].map(t => ({a: 'x', ...t})); // [{a: 1}, {a: 2}, {a: 3}]
```

I have to blame my colleagues before Eslint 😉
