### ISSUE TITLE
`semi` and `no-extra-semi` rules are conflicting with each other in TypeScript interfaces (vue-cli app)

### ISSUE THREAD

**Issue by tzurbaev** [eslint/eslint#11585]
**Tell us about your environment**

* **ESLint Version:** v5.16.0
* **Node Version:** v8.15.1
* **npm Version:** 6.4.1
* **typescript Version:** 3.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/essential',
    '@vue/airbnb',
    '@vue/typescript',
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
  },
  parserOptions: {
    parser: '@typescript-eslint/parser',
  },
};
```

</details>

First of all, I'm not sure if this is correct repository to submit this issue - I'm using eslint in a Vue application with typescript support that was created via `vue-cli`.

Since this bug happens with bundled eslint rules, I decided to submit it here.

The `semi` and `no-extra-semi` rules are seems to be conflicting with each other when eslint tries to run them on TypeScript interfaces.

```typescript
export default interface Customer {
  id: string;
  name: string;
};
```

Running eslint on given interface will trigger both `Missing semicolon (semi)` and `Unnecessary semicolon (no-extra-semi)` errors pointing to the same character (4:2).

Also, if you add `'no-extra-semi': 'off',` to the rules config, eslint will add 10 semicolons and trigger `Missing semicolon (semi)` error.

But if we have some TypeScript class, eslint will run without errors:

```typescript
export default class ExampleClass {
  constructor() {
    console.log('Hello world');
  }
};
```

In this case eslint will remove ending semicolon and will not produce any errors.

I have demo repository that shows this behaviour - https://github.com/tzurbaev/vue-ts-eslint-semi. This is default Vue app that was created via `vue create` command.

**What did you expect to happen?**
Running eslint on the given interface example will remove semicolon just like running on given class example without errors.

**What actually happened? Please include the actual, raw output from ESLint.**
eslint triggers both `semi` and `no-extra-semi` errors pointing to the same position.

```bash
error: Missing semicolon (semi) at src/interfaces/Customer.ts:4:2:
  2 |   id: string;
  3 |   name: string;
> 4 | };
    |  ^
  5 | 


error: Unnecessary semicolon (no-extra-semi) at src/interfaces/Customer.ts:4:2:
  2 |   id: string;
  3 |   name: string;
> 4 | };
    |  ^
  5 | 
```

**Are you willing to submit a pull request to fix this bug?**
Not sure how to fix it (and how to debug what package is actually bugged - eslint itself or Vue's eslint plugin or even something else).

**Comment by jgalp** [comment]
Is anyone working on this or should I pick this up?

**Comment by quinlander** [comment]
Is this a valid issue and is anyone working on it? I am a student at the University of Michigan looking to contribute to an open source project for my upper level software engineering class and would like to tackle this issue along with @jgalp if we can.

**Comment by not-an-aardvark** [comment]
Since this issue concerns TypeScript, I think it would be better to have a fix be part of the [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint) project. We generally don't support bugfixes for custom syntax such as TypeScript in core ESLint rules.

**Comment by tzurbaev** [comment]
I checked typescript-eslint repository and seems that it already has similar [issue](https://github.com/typescript-eslint/typescript-eslint/issues/123) and related [PR](https://github.com/typescript-eslint/typescript-eslint/pull/411) that should fix the bug.

I'll close this for now, thanks everyone.
