### ISSUE TITLE
getErrorResults alters passed `results` parameter

### ISSUE THREAD

**Issue by danielamaia** [eslint/eslint#11589]
**The version of ESLint you are using.**
5.9.0

**The problem you want to solve.**
When using the function `getErrorResults`, it alters the passed parameter `results`, when I'm expecting that the parameter I passed to remain immutable.

**Your take on the correct solution to problem.**
The `results` parameter should remain unchanged, I should get the filtered error results only by the returned array.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by not-an-aardvark** [comment]
Thanks for the report. I can reproduce this issue.

**Comment by mysticatea** [comment]
Closing as the PR merged.
