### ISSUE TITLE
`no-var` fixer breaks on declared vars in @typescript-eslint

### ISSUE THREAD

**Issue by epmatsw** [eslint/eslint#11594]
The fixer for `no-var` just replaces the first token in the VariableDeclaration with `let` or `const`:
https://github.com/eslint/eslint/blob/c021117915d5d23399233f761a237e138f1854af/lib/rules/no-var.js#L308 

This is valid in JS, but in TS that first token can be `declare`, which breaks the fixer.

In the discussion over in https://github.com/typescript-eslint/typescript-eslint/issues/410, @platinumazure suggested that this could be fixed in `eslint` instead:

```js
const varToken = sourceCode.getFirstToken(node, { filter: t => t.value === node.kind });
```

**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 11.12.0
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?** @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parser": "@typescript-eslint/parser",
    "rules": {
        "no-var": 2
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```ts
declare var blah: number;
```

```bash
eslint --ext js,jsx,ts,tsx --fix .
```

**What did you expect to happen?**
It should fix the code into:

```ts
declare let blah: number;
```

**What actually happened? Please include the actual, raw output from ESLint.**
It fixed the code into:

```ts
let var blah: number;
```

**Are you willing to submit a pull request to fix this bug?**
Unfortunately not. However, @platinumazure suggested a fix:

```js
const varToken = sourceCode.getFirstToken(node, { filter: t => t.value === node.kind });
```

**Comment by platinumazure** [comment]
Working on this.

**Comment by epmatsw** [comment]
Dupe of https://github.com/eslint/eslint/issues/11441
