### ISSUE TITLE
Can eslint include JSON files like package.json?

### ISSUE THREAD

**Issue by mcandre** [eslint/eslint#11605]
Could eslint automatically include `*.json` files such as the common `package.json` file?

Would be good to apply consistent styling across JSON files. Not necessarily the same style as for `*.js` scripts, as JSON specifies double quotes for strings, whereas JavaScript may use double or single quotes.

**Comment by platinumazure** [comment]
Hi @mcandre, thanks for the issue.

I don't think this is something we would want to do automatically, as most users wouldn't benefit and we would probably be adding some dependencies (our default parser will not parse most JSON as-is).

The good news is, this is something you can definitely do yourself! You can use [glob-based configuration](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) to create an override section for your JSON files; in that section, you could specify a different parser and/or plugin, and even change rules that need to be changed (such as setting `quotes` to use double quotes even if you require single quotes everywhere else).

As a result, I don't think the proposed change is necessary.
