### ISSUE TITLE
RuleTester should report syntax error of fixed code

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#11615]
**The version of ESLint you are using.**

- master

**The problem you want to solve.**

I found `RuleTester` doesn't report any errors even if autofix makes a syntax error in #11579.

![image](https://user-images.githubusercontent.com/1937871/56079186-d7e19280-5e2b-11e9-83b3-f8dc7e46fb10.png)

I expected above test results to be "A fatal parsing error occurred in autofix: Parsing error: ..." rather than "Output is incorrect".

**Your take on the correct solution to problem.**

`RuleTester` makes failing if autofix made a syntax error.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by kaicataldo** [comment]
This feels like a bug - I wonder if we need to wait for a major release to fix this?

**Comment by mysticatea** [comment]
I'm fine to fix it as a bug.
