### ISSUE TITLE
Google Season of Docs application

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#11622]
Google has started the [Season of Docs](https://developers.google.com/season-of-docs/) program to match up open source projects with technical writers to help improve documentation. In order to apply, we need to figure out:

1. What project(s) we would like to submit a proposal for.
2. Two organizational administrators.
3. Two mentors to work with the technical writer.

Details: https://developers.google.com/season-of-docs/docs/admin-guide

The deadline to apply is **April 23, 2019**.

Of course, we can decide not to do this as well. Earlier discussions seem to indicate that there was a level of interest. Some of the projects we came up with during brainstorming were:

1. Reorganizing the docs top-to-bottom.
2. Writing goal-oriented tutorials for all of ESLint.
3. Coming up with a new format for the rule pages.

(I'm still a under the weather after my procedure, just wanted to kick this off to make sure it doesn't fall under the radar in my absence.)

**Comment by kaicataldo** [comment]
It unfortunately looks like we missed this deadline (though I may also have just missed the discussion in my absence). Next year!
