### ISSUE TITLE
quote-props and object-shorthand autofix props that hold functions incorrectly

### ISSUE THREAD

**Issue by jaller94** [eslint/eslint#11631]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 10.15.3
* **yarn Version:** 1.15.2

**What parser (default, Babel-ESLint, etc.) are you using?**
[babel-eslint](https://github.com/babel/babel-eslint)

**Please show your full configuration:**
[eslint-config-7geese](https://github.com/7Geese/eslint-config-7geese)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Have this code in a file:
```
const foo = {
    'BAR': function(state, action) {
    },
    BAR2: function(state, action) {
    },
};
```

The line with BAR is now invalid.

```bash
eslint src/ --ext .jsx,.js --quiet --report-unused-disable-directives --fix
```

**What did you expect to happen?**
Auto fix the rule `quote-props` and it becomes:
```
const foo = {
    BAR: (state, action) => {
    },
    FOOBAR: function(state, action) {
    },
};
```
or it states that it cannot auto this, because satisfying both rules is kind of hard.

**What actually happened? Please include the actual, raw output from ESLint.**
Auto fixed the rule `quote-props` and changed the meaning fundamentally:
```
const foo = {
    BAR(state, action) {
    },
    FOOBAR: function(state, action) {
    },
};
```

**Are you willing to submit a pull request to fix this bug?**
no, maybe @himynameisdave does. 😋

**Comment by mysticatea** [comment]
Thank you for this report.

However, I could not reproduce it.

```
~\dev\sandbox> cat .\.eslintrc.json
{
  "root": true,
  "extends": "7geese"
}
~\dev\sandbox> cat test.js
const foo = {
    'BAR': function(state, action) {
    },
    BAR2: function(state, action) {
    },
};
~\dev\sandbox> eslint test.js --fix
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

C:\Users\t-nagashima.AD\dev\sandbox\test.js
  1:7   error  'foo' is assigned a value but never used  no-unused-vars
  2:9   error  'state' is defined but never used         no-unused-vars
  2:16  error  'action' is defined but never used        no-unused-vars
  4:10  error  'state' is defined but never used         no-unused-vars
  4:17  error  'action' is defined but never used        no-unused-vars

✖ 5 problems (5 errors, 0 warnings)

~\dev\sandbox> cat test.js
const foo = {
    BAR(state, action) {
    },
    BAR2(state, action) {
    },
};
```
