### ISSUE TITLE
Security vulnerability in js-yaml dependency

### ISSUE THREAD

**Issue by andykais** [eslint/eslint#11632]
**Tell us about your environment**

* **ESLint Version:** 5.16.0 (latest)
* **Node Version:** v11.12.0
* **npm Version:** 6.9.0

`npm audit` will report this vulnerability
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint > js-yaml                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. The security issue with `js-yaml` isn't applicable to ESLint due to how the library is used, but if you want the error to go away you can ensure that `js-yaml@3.13.1` is installed with ESLint. That version is already compatible with ESLint, although you might have an older version specified in your lockfile.

ESLint has also upgraded its `js-yaml` dependency to require the latest version on master, but this change hasn't reached a stable release yet (see eeea89361d48494995446ddb6ee6f049457911ec).

**Comment by andykais** [comment]
thanks. I have edited my package-lock.json file for the time being. I will look out for the next stable release!

**Comment by mk-pmb** [comment]
I'm considering making a stripped-down version of js-yaml that ships just the safe parts, in case the unsafe stuff might get the package marked insecure again some day. Would there be interest on eslint's side?

Is the new stable eslint gonna be released soon? Using package lock or ignoring npm audit would both need major changes to my CI setup. :-(

**Comment by mk-pmb** [comment]
If the stable release will take a while: Could you publish an intermediate version based on the latest stable with just the js-yaml dep updated?

**Comment by not-an-aardvark** [comment]
It's not clear to me that that would be warranted. I'm not sure how your CI setup works, but there's nothing stopping you from using the latest version of `js-yaml` with the latest stable release of ESLint. In fact, if you're doing a fresh install without a lockfile, you should already be getting the patched version of `js-yaml`.

**Comment by mk-pmb** [comment]
> In fact, if you're doing a fresh install without a lockfile, you should already be getting the patched version of `js-yaml`.

You're right, thanks for the reminder. Forcing npm to install from scratch is another possible workaround.

**Comment by ScottA38** [comment]
I am experiencing this issue as well, but I have edited my pakage-lock.json and when I run `npm update eslint --depth 2` or `npm update js-yaml --depth 2` like npm suggests nothing happens.
Further down package-lock js-yaml has it's own entry and when I change the version number for that it resets everything back to v3.13.0 without any explanation.
If a fresh install is the best option for me as well @not-an-aardvark could you explain/link to an explanation? I don't understand what I'd do without deleting package.json
