### ISSUE TITLE
no-throw-literal: confusing error message when throwing object literal

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#11637]
**Tell us about your environment**

* **ESLint Version:** 6.0.0-alpha.0 and 5.16.0 (via demo)
* **Node Version:** 11.13.0
* **npm Version:** I’m using pnpm v3.0.1 instead of npm

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Here](https://eslint.org/demo/#eyJ0ZXh0IjoidGhyb3cgeyBmb286ICdiYXInIH07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8tdGhyb3ctbGl0ZXJhbCI6Mn0sImVudiI6e319fQ==) is an example of the problem where a object literal is thrown:

```js
throw { foo: 'bar' };
``` 

**What did you expect to happen?**

I think the wording of the reported message is very confusing because in my example I did throw an object. I would expect a message like `Unexpected object literal thrown.` or `Expected an error object to be thrown.`.

**What actually happened? Please include the actual, raw output from ESLint.**

The reported problem message is `Expected an object to be thrown.`.

**Are you willing to submit a pull request to fix this bug?**

Yes. However I’m not completely sure if this will be considered as a bug or as a breaking change.

**Comment by platinumazure** [comment]
Hi @lo1tuma, thanks for the issue!

I think this is reasonable to fix as a bugfix. I personally like this message: `Expected an error object to be thrown.` (Using an "Unexpected" message might require that we craft similar language for string literals and other literal values of different types.) Other team members may feel differently, but I think this would be a great starting point for a pull request!
