### ISSUE TITLE
ESLint not linting test.js files in VSCODE

### ISSUE THREAD

**Issue by tsysrws** [eslint/eslint#11641]
I have VSCODE and have started using ESLINT for all of my projects.  ESLINT will run for files with .js and .jsx extensions, but not with test.js extensions.  Is this an issue with a config setup, or is it unique to VSCODE?

VSOCDE version 1.31.0
ESLINT version 5.16.0
.eslintrc.json
`{
  "parser": "babel-eslint",
  "extends": ["airbnb"],
  "env": {
    "browser": true,
    "node": true,
    "jest": true
  },
  "rules": {
    "no-console": 1,
    "comma-dangle": "off",
    "react/jsx-filename-extension": "off"
  },
  "plugins": [
    "import",
    "jest",
    "react",
    "jsx-a11y"
  ]
}`

**Comment by g-plane** [comment]
Hi @tsysrws , thanks for this issue.

Can you try running ESLint in command line? If it works, that issue may be caused by `vscode-eslint` extension, not ESLint itself.

**Comment by tsysrws** [comment]
yes, i can run from command line just file for files with test.js.

**Comment by g-plane** [comment]
So, I think you should open issue in `vscode-eslint` repository and ask for help.
