### ISSUE TITLE
How to close the console?

### ISSUE THREAD

**Issue by moonlitnighta** [eslint/eslint#11644]
I am going crazy, every time I open a new file it will open the console, but I don't want to do this, "debug" setting "false" is completely invalid, can anyone tell me what to do?
![image](https://user-images.githubusercontent.com/22231630/56547257-6fbf4900-65af-11e9-89d8-09ed542754d1.png)
![image](https://user-images.githubusercontent.com/22231630/56547267-764dc080-65af-11e9-9952-4a30119298e0.png)

**Comment by g-plane** [comment]
Hi @moonlitnighta , thanks for this issue.

It seems that you're using Sublime Text, so we advise you to ask for help from the author of `SublimeLinter` or similar packages, since ESLint itself doesn't provide any integrations with editors.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
