### ISSUE TITLE
extends overrides parserOptions

### ISSUE THREAD

**Issue by UziTech** [eslint/eslint#11658]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** v11.11.0
* **npm Version:** v6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```js
{
  "extends": "standard",
  "parserOptions": { "ecmaVersion": 5 }
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function test () {
  const a = 1
  return a
}
test()
```

```bash
eslint .
```

**What did you expect to happen?**

throw the error `Parsing error: The keyword 'const' is reserved` since we are targeting ES5

**What actually happened? Please include the actual, raw output from ESLint.**

No error

**Are you willing to submit a pull request to fix this bug?**

yes

**Comment by not-an-aardvark** [comment]
At first glance I think this might have been addressed by https://github.com/eslint/espree/pull/412. Does the problem go away if you add `sourceType: "script"` to `parserOptions`?

**Comment by aladdin-add** [comment]
it will be fixed by https://github.com/eslint/eslint/pull/11649

**Comment by UziTech** [comment]
Ya `"sourceType": "script"` seems to have fixed it thanks
