### ISSUE TITLE
`no-multi-space` exception for re-export statement 

### ISSUE THREAD

**Issue by CxRes** [eslint/eslint#11651]
**What rule do you want to change?**
`no-multi-space` exception for re-export statement (similar to the import statement)!
```
export {foo}            from 'foo';
export {default as bar} from 'bar';
```

**Does this change cause the rule to produce more or fewer warnings?**
fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
Can be made part of `"exceptions": { "ImportDeclaration": true }` option or 
new option  `"exceptions": { "ExportDeclaration": true }`

**Please provide some example code that this change will affect:**
see above

**What does the rule currently do for this code?**
throws a warning

**What will the rule do after it's changed?**
no warning

**Are you willing to submit a pull request to implement this change?**
Wouldn't know how to :(

**Comment by platinumazure** [comment]
Seems reasonable to me. :+1:

**Comment by CxRes** [comment]
@platinumazure could you please look into this and reopen...thanks!
