### ISSUE TITLE
Iterating on `RegExp.prototype.exec` triggers `no-undef`

### ISSUE THREAD

**Issue by mets11rap** [eslint/eslint#11669]
I am using
Node 10.15 (default parser)
NPM 6.4.1
ESLint 5.6.1

<details>

<summary>Config:</summary>

```json
{
  "extends": "standard",
  "rules": {
    "array-bracket-spacing": "error",
    "no-lonely-if": "warn",
    "arrow-parens": "error",
    "no-var": "error",
    "prefer-const": "error",
    "max-len": [
      "warn",
      {
        "code": 155,
        "tabWidth": 2,
        "ignoreComments": true
      }
    ]
  }
}
```

</details>

I'm working on a module where I find multiple matches in a string, however, I need all the captures which `String.prototype.match` does not accomplish.

I used MDN's official code for a matter such as this:
```js
    while ((docs = jsdocFinder.exec(file)) !== null) {
      console.log(docs)
    }
```

This code is fully functional. Unfortunately, ESLint sees `docs` as undefined and errors me on it. I have tried putting keywords such as `const` and `let` there, but they don't work.

My ESLint script is `eslint ./`

Output:
```
> eslint ./

C:\Users\Arthur\Documents\GitHub\cyclone-engine\build\jsdinterpreter.js
  15:13  error  'docs' is not defined  no-undef
  16:19  error  'docs' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

Unfortunately, I am not adept enough with ESLint's code to create a PR. I apologize.

Please fix this. I'd really appreciate it!

**Comment by g-plane** [comment]
Hi @mets11rap , thanks for this issue.

You should add `var docs` before your `while` loop.

**Comment by ljharb** [comment]
You could also use `.matchAll` - https://npmjs.com/string.prototype.matchall - and bypass the issue entirely.

**Comment by mets11rap** [comment]
@ljharb `matchAll` does not return capture groups.

**Comment by mets11rap** [comment]
@g-plane That would store it as a global variable, however. (It's local even with no keyword right now) Besides, this is still something that should be fixed.

**Comment by platinumazure** [comment]
@mets11rap Why do you say the variable is local even with no keyword, but that it would be global if declared with `var`? That doesn't make sense.

Could you please share your entire file here?

From what you've shown so far, if that is a full program, `no-undef` is behaving correctly here because `docs` is not explicitly declared.

**Comment by mets11rap** [comment]
Nevermind, I'm just being stupid.

**Comment by ljharb** [comment]
@mets11rap `matchAll` absolutely returns capture groups, that's the entire reason I added it to JavaScript.

**Comment by mets11rap** [comment]
> @mets11rap `matchAll` absolutely returns capture groups, that's the entire reason I added it to JavaScript.

Unfortunately, it's not supported by Node.

**Comment by ljharb** [comment]
It should be in node 12, but that’s why i linked you to the official polyfill that works everywhere.
