### ISSUE TITLE
Add top-level option for noInlineConfig or allowInlineConfig

### ISSUE THREAD

**Issue by niftylettuce** [eslint/eslint#11665]
It'd be nice to be able to force override declarations in code that you're linting with a `.eslintrc` config.  For example, the code has `complexity` declarations via comments, e.g. `/* eslint complexity: [2, 17], max-statements: [2, 33] */` but I wish to disable that rule globally with `"complexity": "off"` in my `.eslintrc`.  There's no way to currently do this unless I strip that code from my build, which sometimes is not easily possible without having some extra build step or regexp to strip out `/* eslint` blocks.

**Comment by not-an-aardvark** [comment]
Have you tried the [`no-inline-config`](https://eslint.org/docs/user-guide/command-line-interface#--no-inline-config) CLI flag?

**Comment by niftylettuce** [comment]
That worked.  Thank you @not-an-aardvark  👏 

Could we add this as `noInlineConfig` option as well so I can just add it to my `.eslintrc` as `"noInlineConfig": true`?  Neither `noInlineConfig` nor `allowInlineConfig` are top-level property options.
