### ISSUE TITLE
Document Typo for indent rule

### ISSUE THREAD

**Issue by sdev** [eslint/eslint#11666]
The document for the rule "indent" has typos for some of the examples for `Importdeclaration` option. The quotes are missing. Please see link:  https://eslint.org/docs/rules/indent

ex. `4, { ImportDeclaration: 1 }`   vs.  `4, { "ImportDeclaration": 1 }`

**Comment by sdev** [comment]
@g-plane on this link https://eslint.org/docs/rules/indent, search for term `ImportDeclaration`, you will find some of them are not double quoted, which is inconsistent with others, and also it does not work without the double quote. The rule is not recognized unless it is double quoted.

**Comment by platinumazure** [comment]
Hi @sdev, thanks for explaining.

Quotes are required in JSON configuration files. However, what you see in the rule docs are inline configuration comments. Those accept a loose superset of JSON and don't require quotes. However, a PR would be welcome to bring everything into consistency.

**Comment by AlokTakshak** [comment]
@platinumazure 
I have updated the doc change please tell me how to raise a PR

**Comment by kaicataldo** [comment]
Closing this as It looks the corresponding PR (https://github.com/eslint/eslint/pull/11679) has been merged.
