### ISSUE TITLE
'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead (node/no-deprecated-api)

### ISSUE THREAD

**Issue by qyjs** [eslint/eslint#11660]
I use eslint, now this error, 
How to remove it inside the rules ?
my code:

const URL = require('url')
URL.parse(window.location.href, true)

Wrong as follows:
'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead (node/no-deprecated-api)

my node environment: 
  node: v10.15.3
  npm: 6.4.1

**Comment by saschanaz** [comment]
Use standard URL instead. Just remove `require('url')` and do `new URL("window.location.href")`.

**Comment by kaicataldo** [comment]
This warning is coming from the [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) plugin. If you're having an issue with the rule, I recommend making an issue for that plugin.

**Comment by platinumazure** [comment]
Closing as this question has been answered. Thanks!
