### ISSUE TITLE
Method is not defined?

### ISSUE THREAD

**Issue by isaaclem** [eslint/eslint#11672]
**Tell us about your environment**
```
Environment:
  OS: macOS 10.14.4
  Node: 12.1.0
  Yarn: 1.15.2
  npm: 6.9.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.4 AI-183.5429.30.34.5452501

Packages: (wanted => installed)
  react: ^16.2.0 => 16.8.6
  react-native: 0.53.0 => 0.53.0
```

* **ESLint Version:**"eslint": "^4.19.1",
* **Node Version:**v12.1.0
* **npm Version:**6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint: "7.1.1"
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  'extends': 'airbnb',
  "parserOptions": {
    "ecmaVersion": 2018
  },
  'parser': 'babel-eslint',
  'env': {
    'jest': true,
  },
  'rules': {
    'no-use-before-define': 'off',
    'react/jsx-filename-extension': 'off',
    'react/prop-types': 'off',
    'comma-dangle': 'off',
    'react/destructuring-assignment': 'off',
  },
  'globals': {
    "fetch": false
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class App extends Component { 
  constructor(props) { ... }

  foo = () => { ... } // 'foo' is not defined. eslint(no-undef)

  foo() { ... } //no problem
}

```
**What did you expect to happen?**
Supporting fat arrow function for class properties

**What actually happened? Please include the actual, raw output from ESLint.**
'foo' is not defined. eslint(no-undef)

**Are you willing to submit a pull request to fix this bug?**

**Comment by platinumazure** [comment]
Hi @isaaclem, thanks for the issue.

Class properties are still a Stage 3 feature in ECMAScript, so ESLint (and the default parser) won't support them.

I see you're using babel-eslint already, so I would suggest looking at eslint-plugin-babel to see if that plugin has its own `no-undef` rule that takes class properties into account. If so, you can disable the core rule and use the plugin version.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
