### ISSUE TITLE
Add "fix" severity level

### ISSUE THREAD

**Issue by arvigeus** [eslint/eslint#11674]
ESLint is smart enough to auto fix some of the code. The problem is, in order to do so, the related rule must be marked as `"warn"` or `"error"`, which can pollute the code with unnecessary warnings. For example: `indent` - good rule, but produces too much warnings/errors, that can be solved easily with CI (let's ignore `prettier` for this example).

My proposition is to have additional `"fix"` level that does not produce an error/warning, but is still auto fixed when running with `--fix`.

One possible problem would be if the user configures non-fixable rule as `"fix"` - what would happen then? Maybe then it should not be a severity level, but something else that suppresses the error/warning? Or simply interpret is as `"off"`?

**Comment by kaicataldo** [comment]
@arvigeus Thanks for the issue. Can you explain why errors in the code that can be fixed should not be reported? I personally would want the tool to operate as transparently as possible and alert me to what changes it will make. Given that any fixable errors would no longer be reported after running ESLint with `--fix`, the errors would only show up for any runs before running the autofixer. 

Additionally, not all errors reported by a fixable rule can be fixed. While it's possible that we could create some new API to set the warning level when an error is found but the autofixer is not run, that would require making changes to core as well as updating all the existing fixable rules.

Can you explain why this is a problem for your use case?

**Comment by kaicataldo** [comment]
One more small note: we can definitely discuss this here to get some initial feedback, but our process requires an RFC for changes to core. See more details [here](https://github.com/eslint/rfcs).

**Comment by arvigeus** [comment]
I was hoping to see more people wanting the same feature. Apparently only me. I think this is just aesthetics. Considering the effort needed for implementation, it's not worth it then. I'll close the issue unless anyone else agrees with my idea.

**Comment by TehShrike** [comment]
I'm looking for a solution to this problem as well.

I don't want to see visual warnings in my IDE for things that eslint is going to automatically fix for me as soon as I hit the save button.

I currently solve this by putting my fixable rules in one config file, and the rules that I want to affect my IDE in another config file.  This is pretty jankety.

**Comment by kaicataldo** [comment]
Feel free to open a new issue with a proposal if this is something you'd like to advocate for. My comments above still stand!
