### ISSUE TITLE
 Parsing error: Unexpected character '#'

### ISSUE THREAD

**Issue by orangebook** [eslint/eslint#11677]
**The version of ESLint you are using.**
v5.16.0

**The problem you want to solve.**
support new feature:  public/private class fields
```
class Animal {
  constructor(name) {
    this.name = name;
  }
}

class Cat extends Animal {
  likesBaths = false;
  #canFly = false
  meow() {
    console.log('Meow!');
  }
}
```
**Your take on the correct solution to problem.**
no error lint on env=node

**Are you willing to submit a pull request to implement this change?**
no

**Comment by g-plane** [comment]
Hi @orangebook , thanks for this issue.

Private class fields is still at Stage 3, while ESLint only supports ECMAScript 2019 at present. We recommend you to use `babel-eslint` if you want to parse it.

**Comment by ljharb** [comment]
(public class fields too)

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Comment by flaviolc18** [comment]
any update? private class fields are already available on node 12

**Comment by g-plane** [comment]
ESLint only supports Stage 4.
