### ISSUE TITLE
"indent" rule: add more flexibility for the alignment of chained method calls

### ISSUE THREAD

**Issue by OliverSieweke** [eslint/eslint#11690]
**What rule do you want to change?**

[`indent`](https://eslint.org/docs/rules/indent)

**Does this change cause the rule to produce more or fewer warnings?**

More or fewer depending on code style.

**How will the change be implemented? (New option, new default behavior, etc.)?**

Two new possible values for the `MemberExpression` option:

- `{MemberExpression: "first"}`
- `{MemberExpression: "last"}`

[The current possible values are `"off"` or a number]

**Please provide some example code that this change will affect:**

```js
object.firstCall().secondCall()
.thirdCall()
.fourthCall()
```

**What does the rule currently do for this code?**

With `["error", 2, {MemberExpression: 1}]`, expects:
```js
object.firstCall().secondCall()
  .thirdCall()
  .fourthCall()
```

**What will the rule do after it's changed?**

With `["error", 2, {MemberExpression: "first"}]`, expects:
```js
object.firstCall().secondCall()
      .thirdCall()
      .fourthCall()
```

With `["error", 2, {MemberExpression: "last"}]`, expects:
```js
object.firstCall().secondCall()
                  .thirdCall()
                  .fourthCall()
```

**Are you willing to submit a pull request to implement this change?**

Yes

**Comments**

- The following options already implement an analogous feature and accept `"first"` as value: `VariableDeclarator.var`, `VariableDeclarator.let`, `VariableDeclarator.const`, `FunctionExpression.parameters`, `CallExpression.arguments`, `ArrayExpression`, `ObjectExpression`, `ImportDeclaration`.
- This is the way Webstorm aligns chained method calls for example when the formatting option `Chained method calls > Align when multiline` is activated.

**Comment by platinumazure** [comment]
Nice! I'll support this. :+1:

**Comment by OliverSieweke** [comment]
@platinumazure Great! Not sure how the process goes from here... Are you happy with me starting to work on this or is this still pending and waiting for further team feedback?

**Comment by ilyavolodin** [comment]
@OliverSieweke Our rules require 3 up-votes from the team + one person who will be willing to champion this change. Once that's done, the issue will be moved into accepted state. You can start the work on the change before the accepted state, but there's a chance that an issue will never reach accepted state, and as such, PR will never be merged. So, in a lot of cases, it's safer to wait until issue is accepted before starting the work on the code.

**Comment by OliverSieweke** [comment]
@ilyavolodin I see, thanks for explaining!
