### ISSUE TITLE
newline-after-var produces invalid autofix when variable declaration is followed by a line comment and a block comment

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#11707]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 12.1.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yml
rules:
  newline-after-var: error
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var foo;

//
/*
*/x
```

```bash
eslint --fix
```

**What did you expect to happen?**

I expected ESLint to not produce invalid syntax.

**What actually happened? Please include the actual, raw output from ESLint.**

The rule was autofixed to the following code:

```js
var foo;///*
*/x
```

This is a syntax error because the block comment start marker `/*` is itself commented, so `*/` doesn't close any block comment.

[Demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG5ld2xpbmUtYWZ0ZXItdmFyOiBbZXJyb3IsIG5ldmVyXSAqL1xuXG52YXIgZm9vO1xuXG4vL1xuLypcbioveCIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

This was discovered while running the fuzzer locally.

**Are you willing to submit a pull request to fix this bug?**

Yes, but not sure when I'll have time.

**Comment by mysticatea** [comment]
It's a deprecated rule.

**Comment by not-an-aardvark** [comment]
Oh, so it is. I suppose we should make it so the fuzzer doesn't test deprecated rules.
