### ISSUE TITLE
Require "secure" cookies

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#11715]
**Please describe what the rule should do:**

When setting cookies with js, we should require the "secure" parameter. In 2019, with free SSL with letsencrypt, there really is no reason anymore to not be on SSL/https and eslint should require the secure parameter to improve security.

This is (I believe) also easily auto-fixable by eslint.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[ ] Suggests an alternate way of doing something (suggestion)
[ ] Enforces code style (layout)
[x] Other (please specify:) **Improves security**

**Provide 2-3 code examples that this rule will warn about:**

```js
document.cookie = "username=John Doe";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/";

Should be:
document.cookie = "username=John Doe; secure";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; secure";
document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/; secure";
```

**Why should this rule be included in ESLint (instead of a plugin)?**
This is a core component in making js/the web more secure (even only marginally)

**Are you willing to submit a pull request to implement this rule?**
I have no idea how, but I am happy to test, write documentation or whatever else is needed.

**Comment by aladdin-add** [comment]
hi, thanks for creating the issue! it seems an useful rule, however it would only works for browsers. we don't accept new rules for specific runtime. https://eslint.org/docs/developer-guide/contributing/new-rules#core-rule-guidelines

I would recommended you to add it to an eslint plugin.

**Comment by kkmuffme** [comment]
@aladdin-add thanks, but wouldn't this apply to all places that can set cookies via js?

**Comment by g-plane** [comment]
> but wouldn't this apply to all places that can set cookies via js?

Sorry for being not so clear what you mean.

**Comment by not-an-aardvark** [comment]
To clarify, this would only apply to browsers, since that's where cookies are set in this context. It wouldn't apply to other JS environments such as Node.

**Comment by g-plane** [comment]
Should this be closed? We may not accept this proposal.

**Comment by platinumazure** [comment]
I also think this would be better in a plugin.

**Comment by sindresorhus** [comment]
I agree this would be a better fit for a plugin.

@kkmuffme Open an issue on [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn). I would be happy to host the rule there.

**Comment by kkmuffme** [comment]
@sindresorhus great, I opened an issue: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/299
