### ISSUE TITLE
[6.0.0-alpha.1] `RuleTester` fails tests if `parser` property is a package name

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#11728]
From https://github.com/benmosher/eslint-plugin-import/issues/1362
From https://travis-ci.org/benmosher/eslint-plugin-import/jobs/533124402

**Tell us about your environment**

* **ESLint Version:** 6.0.0-alpha.1
* **Node Version:** 10.15.3
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

n/a

**Please show your full configuration:**

n/a

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Use `RuleTester` with `parser` option with `babel-eslint`. (e.g., [eslint-plugin-import:/tests/src/rules/default.js#L31](https://github.com/benmosher/eslint-plugin-import/blob/c8ac7ffd4ee3e2d1837515cc5da708ed7b2890ee/tests/src/rules/default.js#L31))

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

The test failed with "Parsers provided as strings to RuleTester must be absolute paths."

**Are you willing to submit a pull request to fix this bug?**

Yes.

----

I think that `RuleTester` should allow package names (maybe it loads it relative to CWD).

Also, the Migration Guide must describe this change.

**Comment by not-an-aardvark** [comment]
The current behavior is intentional because it's not clear where packages should be loaded from with `RuleTester`. I suppose the CWD works, but it could be confusing because projects using `RuleTester` might be dependencies of the user's project, so they can't guarantee that their dependencies will be loadable from the CWD. It seems like it would be safer to require an absolute path so that users use `require.resolve` to avoid the ambiguity.

**Comment by platinumazure** [comment]
I think I agree with @not-an-aardvark. We should just document this as a breaking change and require users to specify a full path.

**Comment by mysticatea** [comment]
Thank you for the explanation.

But, my position is different. Because to use file paths for `parser` config is a pretty rare case (probably only we are). For 99.99% of users, `parser` is packages such as `babel-eslint`, `vue-eslint-parser`, `@typescript-eslint/parser`. and etc. Not a file path. Therefore, the `parser` option disallows a package name would be a surprising behavior.

I think that good design is "people can do the most popular use case easily, and can do rare cases with detailed way." I think we should allow a package name and show a understandable error message for rare cases.

**Comment by mysticatea** [comment]
**TSC Summary:**

This is an awareness that came from [the failing CI build of `eslint-plugin-import`](https://travis-ci.org/benmosher/eslint-plugin-import/jobs/533124402). We no longer support a package name in the `parser` option in `RuleTester`. This has been introduced in https://github.com/eslint/rfcs/pull/7 intentionally. But for 99.99% of users, `parser` is packages such as `babel-eslint`, `vue-eslint-parser`, `@typescript-eslint/parser`. and etc. Therefore, disallowing a package name would be a surprising behavior.

Opinions:

- @not-an-aardvark and @platinumazure ... https://github.com/eslint/eslint/issues/11728#issuecomment-493119553
- @mysticatea ... https://github.com/eslint/eslint/issues/11728#issuecomment-493307839

**TSC Question:**

What is the direction we want to go?

1. The `parser` requires an absolute path. Just we add the description of that into the migration guide.
1. The `parser` allows a package name as similar to ESLint 5. We add the change of the place that ESLint loads the package from, into the migration guide. (On ESLint 5, `RuleTester` had loaded packages from the location ESLint was installed.)
1. Others.

**Comment by mysticatea** [comment]
**TSC Resolution:** we won't change the current behavior, the `parser` option requires an absolute path. We will add it to the migration guide.
