### ISSUE TITLE
Site routing for Getting Started/Configuring/CLI returns 404

### ISSUE THREAD

**Issue by JustinHallquist** [eslint/eslint#11732]
**Tell us about your environment**

* **ESLint Version:** N/A
* **Node Version:** N/A
* **npm Version:** N/A

**What parser (default, Babel-ESLint, etc.) are you using?** N/A

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

navigate to https://eslint.org/
select either, `getting started`, `configuring`, or `cli` options from the `user guide` dropdown

this is also reproducible with any link on https://eslint.org/docs/rules/

**What did you expect to happen?**
the page to render 200

**What actually happened? Please include the actual, raw output from ESLint.**
404 is returned

**Are you willing to submit a pull request to fix this bug?**
Yes, depending on urgency

**Comment by platinumazure** [comment]
Hi @JustinHallquist, thanks for the issue.

Is this still a problem? I just tried visiting the Getting Started guide, as well as a rule's documentation page, and I had no problems.

**Comment by JustinHallquist** [comment]
Looks like it's back up. Any idea what caused the issue?

Also, feel free to close

**Comment by SimulatedGREG** [comment]
Looks like it was a GitHub Pages issue. https://www.githubstatus.com/incidents/6vyp7d36str6

**Comment by JustinHallquist** [comment]
Awesome, thanks for pointing that out.

Will close
