### ISSUE TITLE
semi always not work

### ISSUE THREAD

**Issue by andreysuha2** [eslint/eslint#11734]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 10.15.3
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**
.eslintrc
```js
{
    "parser": "babel-eslint",
    "rules": {
        "semi": ["error", "always"]
    }
}
```

webpack.config.js
```js
{
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "eslint-loader"
                    },
                    {
                        loader: "babel-loader"
                    }
                ]
            }
```

linted file

```js
dl.logInProduction(`%cRun in "production" environment`, "font-weight: bold")
dl.notify("Welcome to F5-studio start theme!")
dl.warning("Using jQuery is danger for your brain!")
dl.error("Change git user name, user email, and repo!")
dl.handler(() => {
    console.log("%cThis notifications show you who use DevLogger))", "font-size: 18px;font-weight: bold")
    let test = 2
})
```

**What did you expect to happen?**
See error thet semicolon is required

**What actually happened? Please include the actual, raw output from ESLint.**
I didt see expected error

**Comment by andreysuha2** [comment]
It fix when i change my webpack configuration to

```js
{
                enforce: "pre",
                test: /\.js$/,
                exclude: /node_modules/,
                loader: "eslint-loader"
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: ["babel-loader"]
            }
```

**Comment by platinumazure** [comment]
Hi @andreysuha2, thanks for the issue.

Can you try running ESLint from the command line? Do you see the issue there?

If you see the issue using the ESLint CLI, can you run with the `--debug` flag? It might tell you if there is another configuration file interfering with your configuration. If there is, you could try adding `"root": true` to your configuration file.

**Comment by andreysuha2** [comment]
Hi @platinumazure thenks for try to help me)) I find the problem in my webpack.config.js
