### ISSUE TITLE
module-resolver didn't search local node_modules

### ISSUE THREAD

**Issue by bluelovers** [eslint/eslint#11741]
**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

`module-resolver` didn't search local node_modules

```
[
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\eslint\\lib\\util\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\eslint\\lib\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\eslint\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\node_modules',
  'C:\\Users\\User\\AppData\\node_modules',
  'C:\\Users\\User\\node_modules',
  'C:\\Users\\node_modules',
  'C:\\node_modules',
  'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules',
  'C:\\Users\\User\\.node_modules',
  'C:\\Users\\User\\.node_libraries',
  'C:\\Program Files\\nodejs\\lib\\node'
]
```

but my project is in 

```
G:\Users\The Project\nodejs-yarn\ws-ts-type\packages\package-dts
```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by bluelovers** [comment]
hmm alight 

> eslint@5.16.0

issue is when eslint install on global
and config is install on local

then eslint only search global path

**Comment by platinumazure** [comment]
Hi @bluelovers, thanks for clarifying.

ESLint is working as designed here. Globally installed ESLint only knows how to find globally installed plugins/configs, and locally installed ESLint only knows how to find locally installed plugins/configs. I recommend you install ESLint locally as a devDependency.

See our [FAQs](https://github.com/eslint/eslint/blob/master/README.md#why-cant-eslint-find-my-plugins) for more info.

**Comment by bluelovers** [comment]
hope can have a options allow it

because i don't wanna install eslint in local,
and didn't wanna install conf in global
