### ISSUE TITLE
Update the no-proto rule documentation

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#11743]
**The version of ESLint you are using.**

5.16.0.

**The problem you want to solve.**

The documentation of the `no-proto` rule seems to be outdated as of today. I can point out three issues:

* The documentation only suggests using `getPrototypeOf` method instead of `__proto__`. But `getPrototypeOf` cannot change the prototype of an object, and as such cannot be used to rewrite assignments to the `__proto__` property, which the `no-proto` rule complains about.
* The documentation says that "support for `getPrototypeOf` is not yet universal". Now `getPrototypeOf` (unlike `setPrototypeOf`) is part of ES 5.1 spec and is implemented in browsers as old as IE 9 and Safari 7.
* There are two choices for `getPrototypeOf`: `Object.get​PrototypeOf` and `Reflect​.getPrototypeOf`, where the main difference is browser support. The documentation leaves this ambiguity open to the reader.

**Your take on the correct solution to problem.**

I'd be glad to submit a PR if the team agrees that the rule documentation needs to be updated.

**Are you willing to submit a pull request to implement this change?**

Sure.

**Comment by platinumazure** [comment]
Hi @fasttime, thanks for the issue!

This sounds like a reasonable and useful documentation improvement to me, and I would love to see a pull request!
