### ISSUE TITLE
Improve cache location

### ISSUE THREAD

**Issue by evilebottnawi** [eslint/eslint#11757]
**The version of ESLint you are using.** 

v5.16.0

**The problem you want to solve.**

Many tools have persistent cache will be great store them in one location. Example many webpack plugins (and not only) store cache in `node_modules/.cache`.

Props:
- One location for caches.
- No need adding `.eslintcache` to `.gitignore`.

**Your take on the correct solution to problem.**

Using https://github.com/avajs/find-cache-dir

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by platinumazure** [comment]
Hi @evilebottnawi, thanks for the issue.

Have you looked at the `--cache-location` CLI flag or the `cacheLocation` CLIEngine option?

**Comment by evilebottnawi** [comment]
@platinumazure yes, i known about this CLI flag (use this as workaround right now), but it is require write long line like '--cache-loader=node_modules/.cache/.eslintcache' and it is ugly and uncomfortably.

**Comment by platinumazure** [comment]
I guess I'm not sure of the need for this change, and I think it could confuse other users to make this change. So I'm :-1: on this unless we see broad community support.

As far as the inconvenience goes, there are at least 2 ways to mitigate that:

1. Put the ESLint CLI invocation in an npm script
1. Use CLIEngine and write a Node wrapper script that you can call for linting

**Comment by evilebottnawi** [comment]
@platinumazure Do you seriously consider it convenient?

> Put the ESLint CLI invocation in an npm script

https://github.com/eslint/eslint/issues/11757#issuecomment-495306284

> Use CLIEngine and write a Node wrapper script that you can call for linting

When you need just linting it is very overhead. I don't think it is good idea for little (and not little) projects. Publish this as package require time to maintenance additional package just for run linting.

I can't find any advantage on current cache location, but there are definitely cons:
- additional line in `.gitignore` (almost repos ignore node_modules by default)
- require use `-i .gitignore`
- extra file in root directory

**Comment by platinumazure** [comment]
> yes, i known about this CLI flag (use this as workaround right now), but it is require write long line

The idea is you would write the long line once in an npm script, and then you could lint from the command line using something like `npm run lint`, which is much cleaner. This is a good practice for invoking *any* CLI tool from a Node package environment. Since there is a way to abstract the long command, I don't find the inconvenience argument very persuasive.

**Comment by evilebottnawi** [comment]
> The idea is you would write the long line once in an npm script, and then you could lint from the command line using something like npm run lint, which is much cleaner.

Yes, but it is still require to add additional line in .gitignore but we can avoid this :confused:

**Comment by mistic** [comment]
In my own opinion, while this is a breaking change and could only be released in the next major, I think it is a good move. I found myself less and less willing to have tool specific files ending up on my repo that requires special actions on my side, specially cache files. The only good reason I see to keep it on the repo would be the ability to share the cache which others, through the git, which I think it is not possible as the cache is generated with absolute paths 😃

**Comment by kaicataldo** [comment]
@evilebottnawi Are other projects in the JS tooling ecosystem standardizing around something in this regard?

If you’re interested in pursuing this, would you mind writing up an RFC (following the instructions at https://github.com/eslint/rfcs)?

This does seem like something that would need to happen in a major release.

**Comment by evilebottnawi** [comment]
@kaicataldo yes, many tools use this place for store cache, not sure I can write RFC due English is not my native language, anyway thanks for reply

I agree, it is breaking change

**Comment by kaicataldo** [comment]
@evilebottnawi Thanks! Mind sharing some examples that we can take a look at (if you decide to write an RFC and want to include it there, that's fine too!)

**Comment by evilebottnawi** [comment]
@kaicataldo 

> Mind sharing some examples that we can take a look

Example in code? 

- Webpack@5 use https://github.com/webpack/webpack/blob/next/lib/WebpackOptionsDefaulter.js#L8
- Many of loader/plugins for webpack also use this module.
- As core contributor of `stylelint` i opened issue https://github.com/stylelint/stylelint/issues/4045 too
- Ava use this for cache
- nyc use this module 
- babel use this module 
- storybook use this module 

And many other tools https://www.npmjs.com/browse/depended/find-cache-dir
