### ISSUE TITLE
Array.push is 945x faster than Array.concat

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11753]
there is an [evidence](https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki) shown that `[].push()` is remarkably faster than `[].concat()`.

+ do we want to make the change in eslint codebase?
+ is it worthy to add a new rule that reports the use of `[].concat()`?

**Comment by not-an-aardvark** [comment]
I think this is just happening because `concat` creates a copy of an array while `push` mutates the array. They're useful for different purposes, so I'm not sure it would make sense to have a rule that disallows one or the other.

**Comment by kaicataldo** [comment]
Agreed with @not-an-aardvark, but also wanted to say that if you know of ways we can improve perf in our own codebase than please feel free make a PR or share that info with the community so we can improve it!
