### ISSUE TITLE
Parsing error: Unexpected character   ​Default

### ISSUE THREAD

**Issue by hezedu** [eslint/eslint#11752]
**Tell us about your environment**

* **ESLint Version:** 5.15.3
* **Node Version:** 8.11.3
* **npm Version:** 6.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": ["eslint:recommended", "plugin:vue/recommended", "plugin:vue/strongly-recommended", "plugin:vue/essential"],
    
    "parserOptions": {
        "parser": "babel-eslint",
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "vue"
    ],
    "rules": {
        "indent": [
            0,
            2,
            { "SwitchCase": 1 }
        ],
        "no-extra-semi": "warn",
        "no-unused-vars": "warn",
        "no-trailing-spaces": 0,
        "no-case-declarations": "warn",
        "no-unreachable": "warn",
        "no-multiple-empty-lines": 0,
        "prefer-const": 0,
        "space-infix-ops": "warn",
        "camelcase": 0,
        "no-console": 0,
        "linebreak-style": 0,
        "quotes": 0,
        "semi": 0,

        "vue/require-prop-types": 0,
        "vue/no-reserved-keys": 0,
        "vue/order-in-components": 0,
        "vue/require-default-prop": 0,
        "vue/return-in-computed-property": 0

    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function SimpleEvent(){
  this._isPreventDefault = false;
}

SimpleEvent.prototype.prevent​Default = function(){

}
```

![eslint](https://user-images.githubusercontent.com/8508437/58145651-795ad000-7c85-11e9-9cdf-ed92024054cb.png)

**Comment by aladdin-add** [comment]
Seems the error comes from editor. What if running eslint directly?

**Comment by hezedu** [comment]
https://eslint.org/demo/#eyJ0ZXh0IjoiZnVuY3Rpb24gU2ltcGxlRXZlbnQoKXtcclxuICB0aGlzLl9pc1ByZXZlbnREZWZhdWx0ID0gZmFsc2U7XHJcbn1cclxuXHJcblNpbXBsZUV2ZW50LnByb3RvdHlwZS5wcmV2ZW504oCLRGVmYXVsdCA9IGZ1bmN0aW9uKCkge1xyXG5cclxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnNvbGUiOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=

**Comment by aladdin-add** [comment]
thanks for the demo. the code includes a `\u200b`(zero width space) somehow:
![image](https://user-images.githubusercontent.com/13050025/58190779-d1c6b780-7cef-11e9-8da4-5e31a9e52ebc.png)


it is invisible, so the reported message is really misleading. you can file an issue in acorn repo to improve the message. I would recommended to say something like `unexpected '\u200b'`.

**Comment by hezedu** [comment]
OK, thanks.  `zero width characters`  is More covert than `backspace` I met before.  (All happened  in vsCode)

**Comment by hezedu** [comment]
You are right. np
