### ISSUE TITLE
Why doesn't linter.verify meet expectations?

### ISSUE THREAD

**Issue by moonlitnighta** [eslint/eslint#11763]
I have a project that uses eslint. It works fine and the editor can catch the error correctly. I tried to check the project code in the project (used to learn eslint api) using node Api, but it is not the same as the editor's inspection result. I don't even understand the results of the node api, but they all use the same .eslintrc.js configuration file.

Sample code:
test.js
![image](https://user-images.githubusercontent.com/22231630/58334645-94d6fe00-7e72-11e9-8866-830635e73e2c.png)

vscode Test results:
There are two errors
![image](https://user-images.githubusercontent.com/22231630/58334702-b6d08080-7e72-11e9-94c0-2a6f233b819c.png)

node api:
![image](https://user-images.githubusercontent.com/22231630/58334961-247cac80-7e73-11e9-9bf7-34ced5c38e30.png)

node api Test results:
![image](https://user-images.githubusercontent.com/22231630/58335021-46762f00-7e73-11e9-8367-7fad7422a691.png)

What am I doing wrong?
What should I do if I want to achieve the same effect as the editor?

**Comment by platinumazure** [comment]
Hi @moonlitnighta, thanks for the issue.

I would recommend using [`CLIEngine#executeOnFiles`](https://eslint.org/docs/developer-guide/nodejs-api#cliengineexecuteonfiles) or [`CLIEngine#executeOnText`](https://eslint.org/docs/developer-guide/nodejs-api#cliengineexecuteontext). This will ensure .eslintrc is fully taken into account and it should load plugins. In your case, although you're retrieving the config object for the file being linted, this does not load plugins and so all of the plugin rules are not found.

**Comment by moonlitnighta** [comment]
![image](https://user-images.githubusercontent.com/22231630/58336510-6c510300-7e76-11e9-930b-a77e689fb6b4.png)

@platinumazure thank you very much！！This seems to be consistent with the editor.

**Comment by moonlitnighta** [comment]
@platinumazure 
Hi, cli.executeOnText seems to be very slow. It takes too long to perform a lot of file checking. Can it be optimized?

**Comment by moonlitnighta** [comment]
Wait for more than ten minutes when the file reaches hundreds of...

**Comment by platinumazure** [comment]
Could you try running ESLint with a TIMING=1 environment variable? That will give you the 10 slowest rules, which will at least tell you if the problem is in a core rule or plugin rule.

**Comment by moonlitnighta** [comment]
hi，Where should I get the TIMING report when I use "executeOnText"?

**Comment by platinumazure** [comment]
Sorry, in this case it's for a command line execution of ESLint. In a *nix system it might look like: `TIMING=1 path/to/eslint path/to/file.js`

**Comment by moonlitnighta** [comment]
Thank you, I understand.
