### ISSUE TITLE
"computed-property-spacing" option "operators"

### ISSUE THREAD

**Issue by kasvtv** [eslint/eslint#11772]
**What rule do you want to change?** `computed-property-spacing`

**Does this change cause the rule to produce more or fewer warnings?** by default, no

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option `"operators"` that defines if there needs to be spacing inside the brackets when whatever inside the brackets contains an operator

**Please provide some example code that this change will affect:**
```js
console['log'];
console[ 'lo' + 'g' ];
```

**What does the rule currently do for this code?**
Given `["warn", "never"]`, it wants it to be:
```js
console['log'];
console['lo' + 'g'];
```

**What will the rule do after it's changed?**
Given `["warn", "never", {"operators": "always"}]`, it wants it to be:
```js
console['log'];
console[ 'lo' + 'g' ];
```

**Are you willing to submit a pull request to implement this change?**
In a few months, yes

**Comment by not-an-aardvark** [comment]
Hi, thanks for the proposal.

I'm not sure this option would make sense to add to ESLint core -- it seems like a fairly specific stylistic preference. We wouldn't be able to add individual options for every user's preference, so instead we generally only add an option to a rule if it would be useful for a fairly large percentage of our users, and in other cases we suggest that people [create a custom rule](https://eslint.org/docs/developer-guide/working-with-rules) instead. Personally, I'm not convinced this option would meet the bar for adding to ESLint core, although I wouldn't object to adding it if another team member thinks it's worthwhile.
