### ISSUE TITLE
can we support to maintain coding style consistent within single file instead of workspace?

### ISSUE THREAD

**Issue by lakca** [eslint/eslint#11809]
can we support to(maybe 'easily achieve' is more accurately) keep coding style consistent within every single file instead of workspace?

i think it makes more sense to keep coding style consistent in a single file instead of the whole project. for example, using or not using semicolons after statement is personal style, there is no best practice, the same is true as many other rules.

maybe like these:

```javascript
{
  "parserOptions": {
    "consistent": true // consistent for all unspecified rules.
  },
  "rules": {
    "semi": "consistent" // "consistent" semicolon rule will take effect in scope of every file.
  }
}
```

**Comment by kaicataldo** [comment]
Some questions I have:

1. Can you elaborate on what `parserOptions.consistent` does?
1. How do you propose would ESLint know what to enforce? Would it run the rule with every configuration possible and enforce the one that has the fewest errors? 

A concrete example: Let’s say we have a file that has 49 lines that end with a semicolon and 51 lines that do not. Does that mean if someone were to make a change that increases the number of lines with semicolons to 51 that suddenly it would require semicolons everywhere?

**Comment by lakca** [comment]
Appreciation for your replies.

1. parserOptions.consistent is a global flag for all rules to be kept consistent in every single file.

2. in my mind, the linter should be a lazy processor in the case, i.e. there is no default(possible) rules, a rule will be set down after first occurrence. For example, when the first statement in the file is ended with semicolon, the "semi" rule is set to be 2("error"), afterwards the subsequent ones should obey the rule, or error will be thrown.

**Comment by kaicataldo** [comment]
Thanks for explaining. I don't think this is a good idea to include in core, for a few reasons:

1. I don't think this is a commonly desired behavior. The purpose of ESLint is to enforce code standards across a project. If you don't have specific code standards you want to enforce, why enforce a standard at all?

1. I personally would be really frustrated if every time the first instance of quotes changed the rest of the quotes in the file had to change.

1. From an implementation perspective, this feels like a pretty complex change for what seems like a very niche use case. First of all, rules are not enabled by default, so we would have to figure out how ESLint would know which rules to enforce. Beyond that, we would have to figure out a way for ESLint to calculate what configuration of the enabled rules it would enforce. I think the individual rules would most likely have to be updated to be able to calculate this (as well as all plugin rules).

Some further questions I have:

1. How would configuration for things like exceptions to rules work?

1. How would this work if an end user used an `eslint-disable-*` comment on the first instance where a rule would enforce this? Would it use the next instance?

1. How would auto fixing work with this feature? i.e. if I'm running the auto fixer on save, and I add a space to the beginning of the first indented line, will it automatically update the rest of the file?

One final note: `parserOptions` are options for the parser, so I don't think that putting that configuration option there makes much sense.

**Comment by lakca** [comment]
Yes, you are right, it will be a complex feature, and makes someone annoyed when it applied on all rules . But implementation on auto-fixable rules may be an option.

**Comment by lakca** [comment]
Yes, you are right, it will be a pretty complex feature and may break the original purpose of ESLint , also makes some people annoyed if there is a frequently code change on save, especially when applied on all rules. But maybe configuration on each rule separately is an option.

1. As mentioned above, no default consistency check on all rules will be provided, the option should be configured by user on each rule by intention.

2. No, the ESLint rule has been disabled in the case which just seems like a function scope. i.e. consistency check takes effect only when the rule is enabled.

3. Yes, the rest will be automatically updated, and I know this will be a frustrating behavior. But I don't think auto-save or frequent hand-save is necessary or a good habit, also this will cause some unexpectedness. Instead, almost all modern editors support auto-cache.

**Comment by mysticatea** [comment]
- `parserOptions` is for changing the parser's behavior. Not rules. Each parser decides how it uses the parser options. ESLint doesn't control it.
- I don't think that using several different styles in a workspace is good practice. I oppose adding the feature to ESLint core.

**Comment by ilyavolodin** [comment]
I'm very confused by this issue. ESLint doesn't operate on multiple files at the same time. Each file is processed individually. Given a specific config file (with overrides) you can have files in the same "workspace" follow completely different styles. It's just a matter of crafting that config file.
If you mean that you don't care if somebody uses semi-columns or not, as long as they are doing it consistently within a specific file, then the solution would be to create your own version of `semi` rule that supports `consistent` option (as I do not think something like that would be added to the core rule).
