### ISSUE TITLE
Docs: clarify that `plugins` is not required when `extends` is used

### ISSUE THREAD

**Issue by borekb** [eslint/eslint#11804]
**The version of ESLint you are using.**

5.14.1

**The problem you want to solve.**

I was reading the [docs about using plugins](https://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin) and was under the impression that I have to add the `plugins` property to my config. However, it's not necessary when using `extends` like this:

```js
extends: ['plugin:some-plugin/recommended']
```

Community plugins like [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/859def6212e4d8d850b9c70a3df0fdad58c14d16/README.md) and [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/b257e928d52a0ffff625bf34c89268d6b7e3f00c/readme.md#recommended-config) already suggest using only `extends`, unlike the example in [`docs/user-guide/configuring.md`](https://github.com/eslint/eslint/blob/cb1922bdc07e58de0e55c13fd992dd8faf3292a4/docs/user-guide/configuring.md#using-the-configuration-from-a-plugin).

It might be worth noting that developers are [instructed](https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-plugins.md#configs-in-plugins) to add `plugins` property to their plugins:

> Note: Please note that configuration will not enable any of the plugin's rules by default, and instead should be treated as a standalone config. This means that **you must specify your plugin name in the plugins array** as well as any rules you want to enable that are part of the plugin. [...]

**Your take on the correct solution to problem.**

I think the docs could be a bit clearer and explicit about when the `plugins` property is necessary. I think that there should be two separate examples in the plugins section:

- One with `plugins` and `rules` but no `extends`
- One with `extends` and `rules`

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by platinumazure** [comment]
Is it as simple as that?

What if the plugin exports a configuration, and that configuration does not use "plugins"? Will the plugin rules be loaded properly in that case?

I personally like to specify my plugins in my project config anyway, just to be safe.

**Comment by borekb** [comment]
You're right. I just encountered a plugin that doesn't do it – `eslint-plugin-sonarjs` ([source](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/cd2257a73e84b09d793abbb09051b89e53d055c9/src/index.ts#L49)), in which case I needed to add the `plugins` property myself.

Do you think this is worth noting in the docs, somehow? They are currently not incorrect, I just found it a bit confusing that ESLint docs suggest to add the `plugins` property while some popular community plugins don't have this in their READMEs. I was wondering if I'm misunderstanding ESLint docs or what is going on.
