### ISSUE TITLE
docs: migrating to v5/v6 is missing 

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11819]
https://eslint.org/docs/user-guide/#migrating
![image](https://user-images.githubusercontent.com/13050025/59149044-fa1a1a00-8a42-11e9-96c9-560c246d6700.png)

not sure why it happened -- it is correct in the repo: 
https://github.com/eslint/eslint/tree/master/docs/user-guide#migrating

**Comment by mysticatea** [comment]
https://github.com/eslint/eslint/pull/11729 has fixed it already. But we are on prerelease, the fix has not been applied to the document. You can see the latest version: https://eslint.org/docs/6.0.0/user-guide/
