### ISSUE TITLE
Cannot read config file while using eslint:recommended

### ISSUE THREAD

**Issue by gonardfreeman** [eslint/eslint#11816]
**Tell us about your environment**
MacOS Mojave 10.14.5, VSCode v.1.35, eslint-vscode 1.9.0
* **ESLint Version:**
5.16.0
* **Node Version:**
10.16.0
* **npm Version:**
6.9.0
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint@10.0.1
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
	"extends": "eslint:recommended",
	"parser": "babel-eslint",
	"parserOptions": {
		"ecmaVersion": 6,
		"sourceType": "module",
		"ecmaFeatures": {
			"modules": true,
			"classes": true
		}
	},
	"rules": {
		"semi": "error"
	},
	"env": {
		"es6": true,
		"browser": true,
		"node": true
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
I'm added to `.eslintrc` file `eslint:recommended` and after that extension said that it cannot find eslint.json at node modules `conf` folder of eslint. After I take a look at that folder it appear that file isnt there.

**What did you expect to happen?**
eslint.json file for eslint:recommended in conf folder

**What actually happened? Please include the actual, raw output from ESLint.**
File isnt there
```
[Error - 9:30:46 AM] Cannot read config file: /Users/user/Documents/projects_home/js/blabla/node_modules/eslint/conf/eslint.json Error: ENOENT: no such file or directory, open '/Users/user/Documents/projects_home/js/blabla/node_modules/eslint/conf/eslint.json' Referenced from: /Users/user/Documents/projects_home/js/blabla/.eslintrc
```
**Are you willing to submit a pull request to fix this bug?**
No

**Comment by aladdin-add** [comment]
the weird thing is: `eslint:recommended` is located in `eslint/conf/eslint-recommended`, but seems you are reading from `/eslint/conf/eslint.json`

so, what is in your `/Users/user/Documents/projects_home/js/blabla/.eslintrc`?

**Comment by mysticatea** [comment]
Hi. Sounds like your environment problem. Please try:

- Restart VSCode after you install/update ESLint. Your VSCode may cache old ESLint.
- Remove `node_modules` and re-install ESLint. Npm may fail to install ESLint.
