### ISSUE TITLE
Feat req: Remove unused imports

### ISSUE THREAD

**Issue by corysimmons** [eslint/eslint#11814]
Mostly a request to reopen discussion around: https://github.com/eslint/eslint/issues/7619

VSCode has been doing this with the setting...

```json
"editor.codeActionsOnSave": {
  "source.organizeImports": true
}
```

...for a while, and people love it.

It just stinks that we can't do this with a CLI in a precommit linting step. Typescript org is currently discussing exposing this but it's being bundled with a huge TS architecture change so it likely won't make it in for years.

If this is something ESLint could handle, it'd be amazing.

To prevent it from being too destructive, expose an option to let people opt-in to this behavior.

---

**What rule do you want to change?**

no-unused-vars

**Does this change cause the rule to produce more or fewer warnings?**

same

**How will the change be implemented? (New option, new default behavior, etc.)?**

new option

**Please provide some example code that this change will affect:**

before:
```js
import gql from 'graphql-tag' // err
import { Foo, Bar } from 'MyComponents' // Bar err

export default () => <Foo>hi</Foo>
```

```js
import { Foo } from 'MyComponents'

export default () => <Foo>hi</Foo>
```

**What does the rule currently do for this code?**

it already errs on the unused vars, but doesn't remove them

**What will the rule do after it's changed?**

remove unused imports

**Are you willing to submit a pull request to implement this change?**

doubtful, but possibly with some hand holding?

**Comment by g-plane** [comment]
Hey @corysimmons , thanks for the issue.

ESLint doesn't intend to provide auto fixing for this rule.

Alternatively, there's a third-party ESLint plugin may support this feature: https://github.com/aladdin-add/eslint-plugin-autofix , and you can track on their issue: https://github.com/aladdin-add/eslint-plugin-autofix/issues/33 .

**Comment by kaicataldo** [comment]
For some more context around this discussion, please see https://github.com/eslint/eslint/issues/11668.

**Comment by corysimmons** [comment]
👌 will close and join that discussion
