### ISSUE TITLE
Disable rule at a line from another line

### ISSUE THREAD

**Issue by idrisadetunmbi** [eslint/eslint#11821]
**The version of ESLint you are using.**
Not applicable

**The problem you want to solve.**
Eslint rule can be disabled for a line from a line preceding it or on that very line. This sorts of create a visual noise at those points. It would be nice to be able to disable a rule from another line. A prominent use case would be to disable a rule at a line from the top of the file instead of disabling eslint for the entire file.

**Your take on the correct solution to problem.**
Not applicable

**Are you willing to submit a pull request to implement this change?**
No

**Comment by kaicataldo** [comment]
It’s hard to evaluate this without a full proposal (the “Your take on the correct solution to a problem” section of the template), but having to maintain a series of line locations in another location sounds like a huge burden on the developer workflow to me. Any time a line was added or removed before that line in the file, the comment at the top of the file would have to be updated.

I understand that the problem you’re trying to solve is to not litter files with `eslint-disable-*` comments. Can you share more details about what you think the correct solution is?

**Comment by kaicataldo** [comment]
Also please note that changes to core (such as this) require going through our [RFC](https://github.com/eslint/rfcs) process before we can implement them.
