### ISSUE TITLE
Allow pasting existing config to demo

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#11822]
https://eslint.org/demo/ is a great tool to visually see the effect of rules/rule changes.

It already allows me to download the selected config, but it would be great if I could also paste an existing config to use, so I don't always have to manually check the checkboxes.

**Comment by platinumazure** [comment]
Hi @kkmuffme, thanks for the issue.

As a note, you can use ESLint comments to create a config inline (using the supported comment-based config options). This isn't the same as what you're requesting, but it does allow you to be a little quicker in creating a demo and you can bypass the checkboxes.

**Comment by kaicataldo** [comment]
This is something I’ve been wanting to explore as well, as I think it would be a really useful feature. Do you mind making an issue over at https://github.com/eslint/eslint.github.io and closing the issue here? This repo is for ESLint itself.

**Comment by kkmuffme** [comment]
@kaicataldo thanks. Created the issue https://github.com/eslint/eslint.github.io/issues/574
