### ISSUE TITLE
Unexpected token /

### ISSUE THREAD

**Issue by sergey-shpak** [eslint/eslint#11824]
**Tell us about your environment**

* **ESLint Version: v5.16.0**
* **Node Version: v8.9.4**
* **npm Version: 6.4.1**

**What parser (default, Babel-ESLint, etc.) are you using?
Not specified (default)**

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
module.exports = {
  "extends": "airbnb-base",
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "globals": {
    "h": true,
    "describe": true,
    "it": true
  },
  "rules": {
    "semi": [0],
    "quotes": [2, "single"],
    "implicit-arrow-linebreak": [0],
    "comma-dangle": [0],
    "object-curly-newline": [2, { consistent: true }],
    "import/no-extraneous-dependencies": [1],
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function app(){
  return <div>app</div>
}
```

```bash
./node_modules/.bin/eslint src/app.js
```

**What did you expect to happen?**
No parsing errors
**What actually happened? Please include the actual, raw output from ESLint.**
2:19  error  Parsing error: Unexpected token /

**Comment by sergey-shpak** [comment]
After small investigation 
**eslint@4.19.1 - No parsing error**
**eslint@5.0.0-alpha.0 -  Parsing error: Unexpected token /**
Something wrong happened in the [5.0.0-alpha.0 release](https://github.com/eslint/eslint/releases/tag/v5.0.0-alpha.0)

**Comment by platinumazure** [comment]
Hi @sergey-shpak, thanks for the issue.

Please try removing all node_modules and rerunning npm install. This is likely an issue with npm where some versions of upstream packages like acorn are inconsistent. Your configuration looks correct to me but it looks like the JSX parsing might not be working correctly.

**Comment by mysticatea** [comment]
Sounds like the same issue as https://github.com/eslint/eslint/issues/11018.

npm has a bug around install the packages which have peer dependencies. You seem to have encountered that bug.

**Comment by sergey-shpak** [comment]
@platinumazure @mysticatea thanks,
after playing around the issue and updating other packages which can possibly create acorn inconsistency (eslint-plugin-import and eslint-config-airbnb-base) everything works as expected.
Issue is resolved and can be closed
