### ISSUE TITLE
arrow-body-style autofix with 'in' in a for-loop init

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#11849]
**Tell us about your environment**

* **ESLint Version:** 5.16.0 (same behaviour with 6.0.0-rc.0)
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
    "arrow-body-style": "error",
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
for (let a = b => { return b in c; }; ;);
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

Not a SyntaxError in the fixed code.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
for (let a = b => b in c; ;);
```

The fix changed semantics and produced an error: 

> `SyntaxError: for-in loop variable declaration may not have an initializer.`

This is similar to [#11706](https://github.com/eslint/eslint/issues/11706)

**Are you willing to submit a pull request to fix this bug?**

Yes, when PR [#11848](https://github.com/eslint/eslint/pull/11848) is finished, since it might be a similar fix.

**Note**

The fixed code is SyntaxError in Node/Chrome and Firefox (with a bit different message).

However, it's a valid ForStatement for acorn, babel-eslint and other parsers (e.g. not esprima).

Check: [AST Explorer](https://astexplorer.net/#/gist/f2099b9c9d5e5d2637e94c619ce207b8/816578b963086b257121fa089b00940f9762be27)

Reported [acorn #838](https://github.com/acornjs/acorn/issues/838)

**Comment by mysticatea** [comment]
Thank you for your report.

I confirmed it. I prefer that the rule fixes that code along with wrapping by parentheses.

----

In the spec,

- [RelationalExpression] production requires `[In]` parameter with positive to allow the `in` operator.
- In [IterationStatement] production, the initialization part of `for` statement passes negative to `[In]` argument.
- In [ArrowFunction] production, the bare function body passes the received value to `[In]` argument as is. On the other hand, the block function body doesn't pass `[In]` argument. I guess that it means the`[In]` argument becomes the default value (positive).
- [ParenthesizedExpression] production passes positive to `[In]` argument always.

Therefore, `for (let a = b => b in c; ;);` should be a syntax error.

[ArrowFunction]: https://www.ecma-international.org/ecma-262/9.0/#prod-ArrowFunction
[IterationStatement]: https://www.ecma-international.org/ecma-262/9.0/#prod-IterationStatement
[ParenthesizedExpression]: https://www.ecma-international.org/ecma-262/9.0/#prod-ParenthesizedExpression
[RelationalExpression]: https://www.ecma-international.org/ecma-262/9.0/#prod-RelationalExpression

**Comment by mysticatea** [comment]
By the way, `for (let a = b => [b in c]; ;);` is valid.

**Comment by mdjermanovic** [comment]
>  I prefer that the rule fixes that code along with wrapping by parentheses.

Where should the fix put parentheses, there are several options.

For example, if the code that should be fixed is:

```js
for (let a = (b, c, d) => { return b && c in d; }; ;);
```

parens could be put around the whole function:

```js
for (let a = ((b, c, d) => b && c in d); ;);
```
or around the body:

```js
for (let a = (b, c, d) => (b && c in d); ;);
```
or around the 'in' node':

```js
for (let a = (b, c, d) => b && (c in d); ;);
```

Depending on the precedence, there could be more expressions inside the parens around the 'in' node.

**Comment by mdjermanovic** [comment]
I checked how the fix works for cases like `() => {return {}}`, `() => {return {}.a}` etc. 

The added parentheses are always around the whole body, so that option would be the consistent one:

```js
for (let a = (b, c, d) => (b && c in d); ;);
```

**Comment by mdjermanovic** [comment]
I'll fix this.

**Comment by anikethsaha** [comment]
@mdjermanovic are you working on this? if not I would like to take this

**Comment by mdjermanovic** [comment]
@anikethsaha I'm not working on it at the moment, feel free to take this!
