### ISSUE TITLE
[Feature Request:] add support for config file name => eslint.config.js

### ISSUE THREAD

**Issue by jimblue** [eslint/eslint#11844]
Hi,

Configuration name **`*.config.js`** seems to be the most default/common value for most of majors libraries:

- **webpack.config.js**
- **babel.config.js**
- **stylelint.config.js**
- **postcss.config.js**
- **prettier.config.js**
- **vue.config.js**
- **nuxt.config.js**
- **tailwind.config.js**
- **jest.config.js**

I see only too libraries that doesn't support this format:
- **Eslint**
- **Browserlist** ([Browserlist issues 380](https://github.com/browserslist/browserslist/issues/380))

It could be nice for **Eslint** to offer this option.

Following this convention will definitively help users.
Having a consistent way to configure libraries would be easier and cleaner.

Just my two cents to make our life a little easier 😄 !

Cheers!

**Comment by kaicataldo** [comment]
Some relevant prior discussion: https://github.com/eslint/rfcs/pull/9

@jimblue Please note that we require proposals for changes to core to go through the RFC process outlined [here](https://github.com/eslint/rfcs). The above RFC proposes adding `eslint.config.js` as a recognized file format (though it would also come with changes to how configuration currently works). If you would like to make a separate proposal, please feel free!

One other note is that while Babel supports `babel.config.js`, it also supports `.babelrc` and recommends using both, depending on the user's needs.

**Comment by jimblue** [comment]
@kaicataldo, from Babel team:

> We recommend to use the babel.config.js format. Babel itself is using it. ([ref here](https://babeljs.io/docs/en/configuration#what-s-your-use-case))

It's only two libraries from getting a new standard... could be worst! 😅 
Using `*.config.js` as a convention will definitively help a lot... don't you think?

**Comment by kaicataldo** [comment]
I'm personally [in support](https://github.com/eslint/rfcs/pull/9#discussion_r249959649) of `eslint.config.js`. 

For clarity, that quote is actually taken out of context (and is actually in response to a joke question). The Babel team recommends `.babelrc` if "you have a static configuration that only applies to your simple single package".

**Comment by jimblue** [comment]
Hey :robot: @eslintbot !
Have you read the PR for this issue... It's far from what you call not enough interest...
Could you please re-open this issue, thank you.
A human

**Comment by jimblue** [comment]
In case you miss it: https://github.com/eslint/rfcs/pull/9
