### ISSUE TITLE
Documentation of "no-return-await"

### ISSUE THREAD

**Issue by lll000111** [eslint/eslint#11878]
**The version of ESLint you are using:** 6.0.0 (but this is about the text on https://eslint.org/docs/rules/no-return-await &mdash; 1st paragraph there already)

The documentation of "no-return-await" was written without asynchronous stack traces in mind, which make using `return await promise` over `return promise` a vastly different experience &mdash; if you need to debug a rejected promise: With the `await` the calling function will be included in the stack trace (as of recent V8).

V8 recently introduced **zero-cost async stack traces**. Look for this term on https://v8.dev/blog/fast-async The example there with two functions `foo()/bar()` can be easily slightly modified to have a `return await` to convince yourself, if that is necessary, that what they write also applies when the await-ed promise is at the very end.

I think this changes the reasons given against `return await`, in the current documentation for the rule as well as on StackOverflow (but of course we can't do anything about those) significantly. Anyone who ever had to debug a promise rejected by a sub-function called from different places, where seeing the parameters didn't help knowing where it was called from (such as simply trying to load a file, if there is more than one place in the code that does that), knows that async. stack traces are a godsend, and getting them for free also during production and also on node.js and not just in Chrome dev. tools (with significant overhead) IMHO is reason enough to rethink the advice given thus far.

**Comment by kaicataldo** [comment]
It's not clear to me what exactly you're proposing as a solution to the problem you've described - whether it's a documentation change or behavior change of the `no-return-await` rule. Do you mind clarifying? Following [one of the templates](https://github.com/eslint/eslint/issues/new/choose) we ask for would go a long way in helping evaluate your proposal.

**Comment by lll000111** [comment]
Where do I start?

Did you read what I wrote (or just skim through some keywords because you are too busy to read all)?

Do you understand the documentation for the rule?

Do you understand that the claim that "return await" is useless is plain wrong now? Because it enables stack traces for asynchronous functions?

I must admit that it is *me* who doesn't understand &mdash; what exactly do you not understand? Please help me help you.  The issue seems plain and simple to me.

**Comment by kaicataldo** [comment]
I think you've described the problem in detail (and thank you for that). What I'm trying to suss out is what you think the correct solution would be to fix this problem, since it's not clear to me from the original post. Are you proposing a documentation update?

**Comment by lll000111** [comment]
How about

- stating that on some modern runtimes such as current V8 "return await" is _not_ useless but enables asynchronous stack traces
- pointing to the article I linked (to the section about "zero-cost stack traces"
- that if you want asynchronous stack traces you should _not_ use that rule

**Comment by lll000111** [comment]
Here is the example slightly changed to have "return await". Try function "foo" with or without "await" in a current version of Chrome (node.js v12.4 worked too when I just tried).

```js
(function () {
  async function foo() {
    // return bar();
    return await bar();
  }

  async function bar() {
    await Promise.resolve();
    throw new Error('BEEP BEEP');
  }

foo().catch(error => console.log(error.stack));
})()
```

**Comment by kaicataldo** [comment]
The documentation changes sound good to me (let's see what the rest of the team has to say). Would you be willing to make a PR?

**Comment by lll000111** [comment]
> Would you be willing to make a PR?

Yes

**Comment by lll000111** [comment]
Just to avoid anyone waiting for me (ignore if that's not the case, no hurry):

> let's see what the rest of the team has to say

I'm waiting for that before I write anything.

**Comment by platinumazure** [comment]
I'm :+1: to a documentation change at this point. I think if we want to overhaul the rule based on the notes from the first issue post, we might need an RFC or other detailed design (IMO).

**Comment by ilyavolodin** [comment]
I'm 👍 for documentation change, provided that it mentions that this is purely for debugging, and you might want to consider removing it in your production code. I'm currently 👎 on the rule change (or adding new rule). ESLint rules target run-time or compile-time for the most part, this is debug-time rule, and I'm not sure it's a good idea to add that in.

**Comment by lll000111** [comment]
@ilovejary 

> that it mentions that this is purely for debugging, and you might want to consider removing it in your production code

But that is not true. That is the whole point, this works in production! Debugging was already solved, expensive but dev.tools could already do it.

**Comment by ilyavolodin** [comment]
By purely for debugging I mean for getting information about the error. This does not have any positive effect (only unnoticeable negative effect) to the end consumer.

**Comment by lll000111** [comment]
@ilyavolodin I don't understand your comment. Any programmer, any company, wants to get as much information about production errors as possible. **THAT** is a positive effect for consumers too!

If this very strange thinking is the last word then I'll leave this discussion because it is way too weird to be useful or based on realities of real-world application development. It's "your" repo here so you can do whatever, however silly, that's fine.

**Comment by kaicataldo** [comment]
Closing since the proposal author is no longer interested in pursuing this change.
