### ISSUE TITLE
https://eslint.org/demo/

### ISSUE THREAD

**Issue by 1Jesper1** [eslint/eslint#11873]
https://eslint.org/demo/ broken? 

```
Linter is not a constructor
    at eval (app.jsx:14)
```
` var linter = new Linter()`

**Comment by platinumazure** [comment]
@mysticatea Is this possibly related to file/folder restructuring?

**Comment by mysticatea** [comment]
The cause is that the `Linter` moved to `module.exports.Linter` from `module.exports`. This move because `linter.js` exposes two stuff. We need fix demo.

**Comment by platinumazure** [comment]
@mysticatea Thanks, that makes sense.

I'll work on this.
