### ISSUE TITLE
eslint --print-config no longer works when given a directory

### ISSUE THREAD

**Issue by francoism90** [eslint/eslint#11874]
**Tell us about your environment**

* **ESLint Version:** v6.0.0
* **Node Version:** v11.15.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true
  },
  extends: [
    'standard',
    'plugin:vue/recommended',
    'prettier',
    'prettier/babel',
    'prettier/standard',
    'prettier/vue'
  ],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module'
  },
  plugins: ['babel', 'prettier', 'standard', 'vue'],
  rules: { 'prettier/prettier': 'error' }
};
```

```bash
$ cd /home/user/www/project && yarn run eslint --print-config .
```

**What did you expect to happen?**
Printing config

**What actually happened? Please include the actual, raw output from ESLint.**
Looks in upper path instead of current.

```
Oops! Something went wrong! :(

ESLint: 6.0.0.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /home/user/www and its ancestors.
```

Project path is located at `/home/user/www/project`.

**Are you willing to submit a pull request to fix this bug?**
No, sorry.

**Comment by g-plane** [comment]
Hey @francoism90 , thanks for the issue.

Where does your `.eslintrc.js` locate?

Also, can you install ESLint v5 and try it again to let us know whether it's a bug in v6 or not?

**Comment by francoism90** [comment]
@g-plane Downgrading to Eslint v5 fixes this issue:
```
  "devDependencies": {
    "cross-env": "^5.2",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^5.0.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-promise": "^4.1.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "laravel-mix": "^4.0.16",
    "pug-plain-loader": "^1.0.0",
    "resolve-url-loader": "3.1.0",
    "sass-loader": "^7.1.0",
    "vue": "^2.6.10",
    "vue-template-compiler": "^2.6.10"
  }
```

The configuration file is located at `/home/user/www/project/.eslintrc.js` and I'm running the command in the same location after/prior ESLint upgrade. I tried removing `node_modules`, possible caches, but it seems the upper directory is used.

**Comment by g-plane** [comment]
How about your `package.json`? Does it locate at `/home/user/www` or `/home/user/www/project`?

**Comment by francoism90** [comment]
@g-plane `/home/user/www/project` - everything is the same, except the upgrade to `"eslint": "^6.0.0"`.

**Comment by g-plane** [comment]
It seems that I can't reproduce this on my PC (Windows 10).

**Comment by francoism90** [comment]
@g-plane This is on Linux, path lookup may differ.

**Comment by francoism90** [comment]
For the record, this also happens when upgrading to v6, creating a new `.eslintrc.js` using `yarn run eslint --init` and running finally `yarn run eslint --print-config .`

**Comment by mysticatea** [comment]
I wonder if this is an error message confusing because `eslint-plugin-vue` has not supported ESLint 6 yet.

**Comment by francoism90** [comment]
@mysticatea Unfortunately no:
```
$ cat .eslintrc.js
module.exports = {
  'env': {
    'browser': true,
    'es6': true
  },
  'extends': [
    'standard'
  ],
  'globals': {
    'Atomics': 'readonly',
    'SharedArrayBuffer': 'readonly'
  },
  'parserOptions': {
    'ecmaVersion': 2018,
    'sourceType': 'module'
  },
  'rules': {
  }
}
```

```
$ yarn run eslint --print-config .
yarn run v1.16.0
$ /home/user/www/project/node_modules/.bin/eslint --print-config .

Oops! Something went wrong! :(

ESLint: 6.0.0.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /home/user/www and its ancestors. If it found none, it then looked in your home directory.
```

**Comment by mensfeld** [comment]
I have a similar problem, despite having proper packages in place:

```
Oops! Something went wrong! :(

ESLint: 6.0.0.
ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by malcolmr** [comment]
I can reproduce on Windows here. In my case, running `eslint --init` will generate (e.g.) `.eslintrc.json` in the current directory, but `eslint --print-config .` still prints a similar message.

From the error message (and as shown above), it looks like eslint is starting from the parent of the current working directory.

**Comment by not-an-aardvark** [comment]
Does this issue occur when you actually lint a file, or only when using `--print-config`?

**Comment by not-an-aardvark** [comment]
@mensfeld I think the error you're encountering might have a different cause -- feel free to open a new issue for it or stop by in the [Gitter chat](https://gitter.im/eslint/eslint).

**Comment by not-an-aardvark** [comment]
I can reproduce this issue as it relates to `--print-config`. However, as far as I can tell, linting itself is still working properly. Feel free to let me know if I've misunderstood the problem.

**Comment by not-an-aardvark** [comment]
Actually, it seems like the issue is that `--print-config` only works when provided with a filepath, whereas it would previously also work when provided with a directory. So `eslint --print-config .` doesn't work, but `eslint --print-config someFile.js` does work.

@mysticatea Do you think this is worth fixing? With upcoming changes to `--overrides` and `--ext`, it seems like getting the config for a directory might not make much sense conceptually anymore. On the other hand, we could just convert `--print-config .` to something like `--print-config ./__placeholder__.js` internally and it could still provide some value.

**Comment by mysticatea** [comment]
I see. I think a better message is useful. If a directory path was given with `--print-config`, it shows "please a path to a source code" or something like, as our document says. Because configs can be different for each source code due to `overrides`.

**Comment by malcolmr** [comment]
fwiw, I think `--print-config .` was a fairly simple way to ask for the config that applied to an arbitrary .js file in the current directory, but if it no longer makes sense, a better error message would be nice.

In practice (and looking through github's search), I suspect most usages are coming from people using eslint-config-prettier, due to e.g. https://github.com/prettier/eslint-config-prettier#cli-helper-tool.

**Comment by francoism90** [comment]
@not-an-aardvark This works fine:
```
$ yarn run eslint --fix .
yarn run v1.16.0
Done in 0.29s.
```

I don't know if this helps:
```
$ yarn run eslint --debug --print-config .
[..]
  eslint:cli CLI args: [ '--debug', '--print-config', '.' ] +0ms
  eslint:ignored-paths baseDir = "/home/user/www/project" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +0ms
  eslint:ignored-paths Looking for ignore file in /home/user/www/project +0ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:ignored-paths baseDir = "/home/user/www/project" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +0ms
  eslint:ignored-paths Looking for ignore file in /home/user/www/project +1ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cascading-config-array-factory Load config files for /home/user/www. +0ms
  eslint:cascading-config-array-factory No cache found: /home/user/www. +0ms
  eslint:config-array-factory Config file not found on /home/user/www +0ms
  eslint:cascading-config-array-factory No cache found: /home/user. +1ms
  eslint:cascading-config-array-factory Stop traversing because of considered root. +0ms
  eslint:cascading-config-array-factory Loading the config file of the home directory. +0ms
  eslint:config-array-factory Config file not found on /home/user +0ms
  eslint:cascading-config-array-factory Configuration was determined: ConfigArray [] on /home/user/www +0ms
```

Thanks for taking a look, don't know if this may cause issues, I just use this command for testing the config.

**Comment by mensfeld** [comment]
@not-an-aardvark it seems it's related directly to lack of support of the new es linter from the airbnb package maintainers: https://github.com/airbnb/javascript/issues/2036

**Comment by mysticatea** [comment]
Since v4.1.0, ESLint has supported glob-based configuration. So `--print-config` with a directory path doesn't make sense anymore. Configurations are not per directory.

And [the document](https://eslint.org/docs/user-guide/command-line-interface#--print-config) says requiring a file path and print the configuration for linting the given file. I think that the solution is a better error message when a directory path was given.

**Comment by lydell** [comment]
I think there might be a few usages of `eslint --print-config .` in the wild because of https://github.com/prettier/eslint-config-prettier/#cli-helper-tool

I need to update that section.
