### ISSUE TITLE
bag in version 6.0.0

### ISSUE THREAD

**Issue by maystrenkoYurii** [eslint/eslint#11882]
bag in version 6.0.0 and "eslint-loader": "2.1.2"
![Снимок](https://user-images.githubusercontent.com/23016311/59977450-ccec7080-95d9-11e9-8f96-d5182b157bc4.PNG)
With old version 5.16.0 good work

**Comment by maystrenkoYurii** [comment]
@bot version eslint 6.0.0

**Comment by g-plane** [comment]
Hey @maystrenkoYurii , thanks for the issue.

Can you fill out our issue template and tell what problems you have encountered?

**Comment by maystrenkoYurii** [comment]
@g-plane I think eslint-loader version 2.1.2 causes conflict with eslint version 6.0.0

**Comment by g-plane** [comment]
So I think you'd better open issue at `eslint-loader`'s repo.

**Comment by kaicataldo** [comment]
@maystrenkoYurii It's really difficult to figure out what's going on here without the information requested in our templates, but it does look to me like this is a Webpack/eslint-loader issue based on the information given above.

**Comment by weilinzung** [comment]
`Error: Cannot find module 'eslint/lib/formatters/stylish'`

```
    "eslint": "^6.0.0",
    "eslint-loader": "^2.1.2",
```

**Comment by g-plane** [comment]
It seems that `eslint-loader` is out of maintenance.

**Comment by bsas** [comment]
This issue looks like it is affecting webpack plugins:
https://github.com/webpack-contrib/eslint-loader/issues/238

**Comment by g-plane** [comment]
Maybe this issue can be closed if we confirmed it's an issue from `eslint-loader`.

**Comment by mysticatea** [comment]
Closing as not an issue in ESLint itself. Thank you.
