### ISSUE TITLE
Eslint broke plugin resolution from 5 version

### ISSUE THREAD

**Issue by Delagen** [eslint/eslint#11889]
**Tell us about your environment**

* **ESLint Version:** 6.0
* **Node Version:** 12.4.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
...
"plugins": [
		"node"
	],
...
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I have shared package which contains all the dependencies (plugins) and call eslint parser via CLIEngine

```js
const linter = new CLIEngine(options);
```

```bash
invoked via runner
```

**What did you expect to happen?**
All works as expected

**What actually happened? Please include the actual, raw output from ESLint.**

Failed to load eslint-plugin-node
https://github.com/eslint/eslint/blob/master/lib/cli-engine/config-array-factory.js#L870

Cause it contained in subpackage that calling this code? I think in broke many shared runners.

**Comment by mysticatea** [comment]
Hi. How do you run `eslint`?

As [the migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification) says, we have changed plugin resolution intentionally. Is this not related to your case?

**Comment by Delagen** [comment]
I resolved this via resolvePluginsRelativeTo option of CLIEngine.
But now has error Configured parser 'full path to \@typescript-eslint\parser\dist\p
arser.js' was not found.

**Comment by mysticatea** [comment]
If it's an absolute path and the file existed, it should load successfully. Would you confirm the path is valid and exists?

**Comment by Delagen** [comment]
Yes, path is valid and file exists. Tried to update parser to canary version, but no success

**Comment by mysticatea** [comment]
Would you check the version of your `@typescript-eslint/parser`? `1.11.0` got supported ESLint 6.

**Comment by mysticatea** [comment]
Ah, sorry. You said canary.

Hmm. I'm not sure what it happens. If you provided a repro case, it will be helpful.

**Comment by Delagen** [comment]
https://github.com/Delagen/eslint-resolution-issue

**Comment by mysticatea** [comment]
Ah, I see. Thank you for the repro repo!

This is related to [Linter no longer tries to load missing parsers from the filesystem](https://eslint.org/docs/user-guide/migrating-to-6.0.0#linter-parsers) section. `Linter` class doesn't load parsers automatically. I'd like to recommend to use `CLIEngine` instead of `Linter`.

**Comment by Delagen** [comment]
Thanks. Rewrote code to executeOnText of CLIEngine. 
Any way to remove check rule for existense in disable comments?

**Comment by mysticatea** [comment]
Unfortunately, there are no ways. Since https://github.com/eslint/eslint/pull/11742, ESLint validates directive comments stricter.

**Comment by Delagen** [comment]
I use multi pass eslint with different configs and plugins

**Comment by mysticatea** [comment]
Closing as answered. Thank you.
