### ISSUE TITLE
closing div tag improperly indented when preceded by whitespace

### ISSUE THREAD

**Issue by SHxKM** [eslint/eslint#11892]
**Tell us about your environment**

* **ESLint Version:** `eslint@5.15.31`

* **Node Version:** `v10.10.0`
* **npm Version:** `6.9.0`

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "parserOptions": {
    "parser": "babel-eslint",
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "extends": [
    "@nuxtjs"
  ],
  "rules": {
    "quotes": [
      0,
      "double"
    ],
    "indent": [
      0,
      4
    ],
    "vue/html-indent": [
      0,
      4
    ],
    "no-console": "off",
    "semi": [
      "error",
      "never"
    ],
    "vue/html-closing-bracket-newline": [
      "error",
      {
        "singleline": "never",
        "multiline": "never"
      }
    ]
  }
}
```

NPM packages:

```
├── eslint@5.15.3
├── eslint-config-prettier@4.3.0
├── eslint-config-standard@12.0.0
├── eslint-loader@2.1.2
├── eslint-plugin-es-beautifier@1.0.1
├── eslint-plugin-import@2.16.0
├── eslint-plugin-jest@22.4.1
├── eslint-plugin-node@8.0.1
├── eslint-plugin-prettier@3.0.1
├── eslint-plugin-promise@4.0.1
├── eslint-plugin-standard@4.0.0
├── eslint-plugin-vue@5.2.2
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

In a `.vue` file in VSCode or Pycharm (so it's not platform specific), write the following code (notice the whitespace):

```vue
<template>
  <div>
    <h1>Hello</h1>
    
  </div>
</template>
```

Save the file with `eslint.fixOnSave` equal `true`.

**What did you expect to happen?**

(Notice properly indented closing `div` tag)
```html
<template>
  <div>
    <h1>Hello</h1>
  </div>
</template>
```

**What actually happened? Please include the actual, raw output from ESLint.**

(Notice improperly indented closing `div` tag)

```html
<template>
  <div>
    <h1>Hello</h1>
</div>
</template>
```

**Are you willing to submit a pull request to fix this bug?**

I don't have the required knowledge.

**Comment by g-plane** [comment]
Hey @SHxKM , thanks for the issue.

It seems that it's about `eslint-plugin-vue`, and we recommend you to open issue at its repository.

**Comment by SHxKM** [comment]
@g-plane - done, if this is irrelevant to this repo specifically then feel free to close.
