### ISSUE TITLE
I have a issue with ESLint 6.0.1 (Error: Cannot find module 'eslint/lib/formatters/stylish')

### ISSUE THREAD

**Issue by duongagangiang** [eslint/eslint#11896]
I have a project integrate with ESLint to set rules for my code, a few day ago I used npm to install ESLint v5.16.0, it still actives normally. But today, i use npm install eslint for another project then I see "Error: Cannot find module 'eslint/lib/formatters/stylish". I cannot find formatters module in "eslint/lib/".

**Comment by g-plane** [comment]
Hey @duongagangiang , thanks for the issue.

Are you using `eslint-loader`?

**Comment by duongagangiang** [comment]
Yes, I'm using eslint with some other packages:
"eslint-config-airbnb": "^17.1.0",
"eslint-loader": "^2.1.2",
"eslint-plugin-import": "^2.17.3",
"eslint-plugin-jsx-a11y": "^6.2.1",
"eslint-plugin-react": "^7.13.0",

**Comment by kaicataldo** [comment]
Can you share with us the steps you are taking that leads to this error? Ideally,  it would be really helpful to have a minimal reproduction case (ideally a GitHub repo we could look at). Thanks!

**Comment by g-plane** [comment]
Maybe we can close this issue, and please refer to: https://github.com/webpack-contrib/eslint-loader/issues/271 .

**Comment by duongagangiang** [comment]
Oh, thanks for your answer @g-plane
