### ISSUE TITLE
arrow-body-style autofix errors with sequence expression

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#11917]
**Tell us about your environment**

* **ESLint Version:** 6.0.1 (same with 5.16.0)
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 6,
  },
  rules: {
    "arrow-body-style": "error",
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

First example:

```js
const foo = () => { return bar, baz; };
```

Second example:

```js
const a = 1;
if (true) {
  let foo = () => { return bar, a; };
  console.log(a); // 1
}
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

Not a syntax error or changed semantics.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
const foo = () => bar, baz; // SyntaxError: Missing initializer in const declaration
```

```js
const a = 1;
if (true) {
  let foo = () => bar, a;
  console.log(a); // undefined
}
```

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by g-plane** [comment]
Should we add parens at this case?

**Comment by mysticatea** [comment]
Thank you for your report.

I confirmed it: [online demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyb3ctYm9keS1zdHlsZTogZXJyb3IgKi9cclxuY29uc3QgZm9vID0gKCkgPT4geyByZXR1cm4gYmFyLCBiYXo7IH07XHJcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

I agree that we should parenthesize the body in that case as same as `() => { return { bar, baz }; }` case.
