### ISSUE TITLE
Autofix for `strict` can break code

### ISSUE THREAD

**Issue by erikeckhardt** [eslint/eslint#11927]
**Tell us about your environment**

* **ESLint Version:** eslint@6.0.1 
* **Node Version:** v10.15.3
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>
```js
{
  "env": {
      "jest": true,
      "browser": true,
      "commonjs": true,
      "es6": true,
      "node": true
  },
  "extends": "airbnb-base",
  "globals": {
      "Atomics": "readonly",
      "SharedArrayBuffer": "readonly"
  },
  "parserOptions": {
      "ecmaVersion": 2018
  },
  "rules": {
      "arrow-parens": ["error", "as-needed", {
          "requireForBlockBody": false
      }],
      "comma-dangle": ["error", {
          "arrays": "never",
          "objects": "never",
          "imports": "never",
          "exports": "never",
          "functions": "never"
      }],
      "max-len": "off",
      "implicit-arrow-linebreak": "off",
      "object-curly-newline": ["error", {
        "consistent": true
      }],
    "object-curly-spacing": ["error", "always"],
    "no-mixed-operators": "off",
    "no-param-reassign": [2, {
      "props":  false
    }],
    "no-empty": ["error", {
      "allowEmptyCatch": true
    }],
    "prefer-template": "warn"
  },
  "overrides": [{
    "files": ["*.test.js"],
    "rules": {
      "global-require": "off",
      "no-new": "off"
    }
  }]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I ran eslint with the autofix flag set.

Details: in a unit test using `jest`, on a `Proxy` object that is rejecting property assignment, in non-strict mode `proxy.a` will not throw but does not change the value. But in strict mode, it should throw a `TypeError`. This is the pre `--fix` code.
```js
      proxy.a = {};
      expect(proxy.a).toEqual(original.a);

      expect(() => {
        'use strict';

        proxy.a = {};
      }).toThrow(TypeError);
```

As an external tool in WebStorm, the command was:
```bash
./node_modules/.bin/eslint --fix .
```

**What did you expect to happen?**
To not break any code with option `--fix`.

**What actually happened? Please include the actual, raw output from ESLint.**

I don't think the raw output from ESLint is necessary here, as the cause is simple and easy to understand.

What actually happened is that the option `--fix`  removed the line `'use strict';`, yielding this code:

```js
      proxy.a = {};
      expect(proxy.a).toEqual(original.a);

      expect(() => {
        // `use strict`; has been removed by `--fix` option
        proxy.a = {};
      }).toThrow(TypeError);
```

This caused my unit test to fail because `proxy.a = {};` no longer throws a `TypeError`. Here are the failed Jest unit test results:

```
Error: expect(received).toThrow(expected)

Expected constructor: TypeError

Received function did not throw

    at Object.toThrow (/path/to/unit/test/make-proxy.test.js:36:10)
    at ... and so on and so forth
```
![image](https://user-images.githubusercontent.com/6424367/60411859-9e473a80-9b83-11e9-88e8-e82760939243.png)

When I put `'use strict';` back, a hint reports `Eslint: 'use strict' is unnecessary inside of modules. (strict)`.

(Then, annoyingly, when I suppress `strict` for current line, I get the `lines-around-directive` error. Might want to disable that for eslint disabling hints!)

**Are you willing to submit a pull request to fix this bug?**
Sure, I'm happy to submit a pull request—as soon as I receive some confirmation that you consider it a bug and you suggest the proper behavior.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. In general, I think the autofixer for `strict` tries to avoid changing behavior by only removing `'use strict'` when it's completely redundant (i.e. when the function would already be in strict mode anyway).

I see you're using `eslint-config-airbnb-base`, which [sets the `sourceType: "module"` parser option](https://github.com/airbnb/javascript/blob/a9a83d9150ce2903032d64593243e3490f332b9f/packages/eslint-config-airbnb-base/index.js#L13). This tells ESLint that your code uses ES modules, which are always in strict mode without the need for a directive. So the `strict` rule reports your directives as redundant.

Based on the fact that your code's behavior is changing, my guess is that your code isn't actually using ES modules. So I think the solution would be to add `parserOptions: { sourceType: "script" }` to your configuration, and that will remove the errors from the `strict` rule.

**Comment by erikeckhardt** [comment]
Thanks for explaining. You are undoubtedly right. Closing case.
