### ISSUE TITLE
remove no-useless-escape from eslint:recommended

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11922]
2 similar rules:
+ `no-useless-escape` was categorized to `best practice`, and is recommended.
+ `no-extra-parens` was `possible errors`,  and is not recommended.

this rule need to be removed from `eslint:recommended`, given we had been setting a high bar to add new rules(eg. no-eval).

**Comment by mysticatea** [comment]
I'm not sure why do you compare those two rules. Those look non related.

Why do you think that `no-useless-escape` is not proper for recommended?

**Comment by kaicataldo** [comment]
@aladdin-add Are you still championing this proposal?

**Comment by btmills** [comment]
Since it seems there's still some discussion needed here, we decided in today's TSC meeting not to include this in the v7.0.0 release. @aladdin-add are you still interested in pursuing this change? If so, we'll consider it for v8.0.0.

**Comment by aladdin-add** [comment]
I have seen some devs using something like [this](https://github.com/eslint/eslint-release/commit/8cde736c5cdb4e9fe9cbc593e1d8f956633cfd8b#diff-3fded56634bc95e505ff3b855115fefcL61):
```js
 /^[\w\-]+\/[\w\-]+$/.test(...) //
```
it seems like more a stylistic than a mistake. But I'm open to close the issue, as no users response so far. :)

**Comment by kaicataldo** [comment]
@aladdin-add Feel free to close this if you're not planning on championing this proposal any longer. It's been open for half a year now, so we should probably make a decision either way!
