### ISSUE TITLE
function-paren-newline with multiline-arguments is incorrect when param takes multiple lines

### ISSUE THREAD

**Issue by kcsparks** [eslint/eslint#11920]
**Tell us about your environment**

* **ESLint Version:** 6.0.0
* **Node Version:** 8.16.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
package.json
{
  "dependencies": {
    "eslint": "6.0.0"
  }
}

.eslintrc.json
{
    "env": {
        "browser": true,
        "es6": true
    },
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
      "function-paren-newline": ["error", "multiline-arguments"]
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```
const randomFunction = (a, b) => Promise.resolve(b(a));

randomFunction('hello world', (a) =>
  a.toUpperCase()
)
  .then((a) => console.log(a));
```
A repo with the code can be found at https://github.com/kcsparks/eslint-function-paren-newline-issue

```
./node_modules/eslint/bin/eslint.js test.js
```

**What did you expect to happen?**
The auto fix should have formatted the code like:

```
randomFunction(
  'hello world',
  (a) =>
    a.toUpperCase()
)
  .then((a) => console.log(a));
```

**What actually happened? Please include the actual, raw output from ESLint.**
The autofix creates a linter error and fixes it like so:

```
randomFunction('hello world', (a) =>
    a.toUpperCase())
  .then((a) => console.log(a));
```
Output:
```
/Users/kcs/Documents/testrepos/eslint-function-paren-newline-issue/test.js
  5:1  error  Unexpected newline before '('  function-paren-newline

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Are you willing to submit a pull request to fix this bug?**

**Comment by platinumazure** [comment]
Apologies for the auto-close; the team maintains this project on our own time and we've been really busy lately. I'll reopen this so we can evaluate.

**Comment by kcsparks** [comment]
No problem!
