### ISSUE TITLE
eslintrc aliases or preact lookup when no react is found?

### ISSUE THREAD

**Issue by damianobarbati** [eslint/eslint#11923]
I have a simple application which I build with parcel and I aliased react:
```
    "alias": {
        "react": "preact/compat",
        "react-dom": "preact/compat"
    },
    "dependencies": {
        "preact": "^10.0.0-beta.3",
        "react-jss": "^10.0.0-alpha.21"
    },
```

Everything works fine but I have eslint not working with the warning you can see in the screenshot, which is normal because it is not finding `react` package.
Anyway to specify aliases into `eslintrc`?

I'd rather avoid adding a useless `react` devDependency for this!

<img width="1083" alt="Screenshot 2019-06-30 at 13 33 40" src="https://user-images.githubusercontent.com/2225869/60396005-36b9cc80-9b3c-11e9-92df-c360191432b5.png">

**Comment by g-plane** [comment]
Thanks for your report.

I think this problem is from `eslint-plugin-react`, not ESLint itself, so we advise you to open new issue at its repo.
