### ISSUE TITLE
Provide an option to insert eslint-disable(-next)-line for specific rules

### ISSUE THREAD

**Issue by kevinbarabash** [eslint/eslint#11948]
**The version of ESLint you are using.**
5.8.0

**The problem you want to solve.**
I am adopting new rules in a large legacy codebase.  It's difficult to fix all of the errors immediately so I'd like an easy way of disabling existing violations when a new rule is added.

**Your take on the correct solution to problem.**
I would like an option that automatically inserts `// eslint-disable-line foo` or `// eslint-disable-next-line foo` comments for a specific rule or rules.

**Are you willing to submit a pull request to implement this change?**
I am.

**Comment by kaicataldo** [comment]
Hi, thanks for the issue. Please be aware that we require changes to core to go through the [RFC process](https://github.com/eslint/rfcs). Happy to discuss here if you’re looking for initial feedback.

**Comment by kevinbarabash** [comment]
Sounds good.  I can write up an RFC, but some initial feedback would be good before starting that process.

**Comment by kaicataldo** [comment]
I think the first thing we need to decide on is if this is a good fit for core or if it makes more sense as an 3rd party tool. It seems like something you would only run once when new rules are added.

I would personally advocate against a strategy like this. In my personal experience, this usually leads to the disable comments just existing forever.

Some alternatives I can think of that would be good to compare to this solution:: per-file eslint disable comments at the top of the file, using something like `lint-staged` to only lint files that are touched, and using glob configurations to only enable the new rules for certain files.

Have you tried running the auto fixer yet? A lot of rules support auto fixing now and may cut down significantly on the reported errors.

**Comment by kevinbarabash** [comment]
The rule I was adding was react-native/no-unused-styles.  There is no auto-fixer for this rule, but even if there was our code is using styles in ways that plugin doesn't recognize so I'll have to inspect each manually.  In the past I've added `eslint-disable`s to the top of files, but in this particular case I didn't want to do this because I thought it would lead to new cases of unused styles appearing those files.

Creating a standalone tool is my backup option.  I was thinking of parsing eslint's output to determine where to put the eslint-disable comments.  It would be nice if eslint could output violations it finds as JSON.  That would save the parsing part and would making a third party tool more resilient to changes in the normal output.

**Comment by kaicataldo** [comment]
@kevinbarabash ESLint has the ability to output results using custom formatters. Here's a [list of the built in](https://eslint.org/docs/user-guide/formatters/) ones, but you can also [write your own](https://eslint.org/docs/developer-guide/working-with-custom-formatters)!

**Comment by platinumazure** [comment]
@kevinbarabash Our built-in `json` formatter is probably what you're looking for, as far as formatters go.

**Comment by kevinbarabash** [comment]
That's perfect.  The existing `json` reporter looks like it should do the trick.  Thank you.

**Comment by btucker** [comment]
@kevinbarabash I'm looking for this functionality as well. Did you make any progress?
