### ISSUE TITLE
built-in directive support

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#1194]
I propose eslint detects `ExpressionStatement`s representing directives and triggers the `DirectiveStatement` event instead of `ExpressionStatement`. This will remove the burden from rule developers to implement directive detection, and will ease transition when `DirectiveStatement` becomes a standard node type.

**Comment by nzakas** [comment]
Has `DirectiveStatement` been standardized? Seems like Esprima still doesn't support it?

**Comment by michaelficarra** [comment]
No, it has not, and it is not a particularly good way to solve this problem. Unfortunately, I don't think we'll ever see this properly fixed in the SpiderMonkey AST.

**Comment by nzakas** [comment]
Okay thanks, closing.

**Comment by michaelficarra** [comment]
That's not a reason to close. eslint could still do the detection for us so we don't have to duplicate that logic everywhere. It is not a simple process, and most devs will get it wrong if they try to implement it themselves.

**Comment by nzakas** [comment]
This has been sitting around for months without any progress, which means it's  not a big pain point. I don't see any reason to either do the work or leave this issue open indefinitely.

**Comment by michaelficarra** [comment]
We just maintain our projects differently, then. I don't care whether or not people are complaining daily about an issue. It would undoubtedly improve the project, so it would stay open in one of my repos. Closing it means it's either fixed or would not be accepted as a patch if one was ready right now.

**Comment by nzakas** [comment]
Yup, Im closing it to say I don't want people spending time on it. Since this failed to reach standardization, I don't think it's a good idea.

**Comment by michaelficarra** [comment]
> Since this failed to reach standardization

I'm not sure you're aware what this issue was about. Directives themselves *are* standardised as part of ES5 and must be acknowledged. The mention of `DirectiveStatement` was just an off-hand comment that this may be easier in the future. It doesn't make handling/detecting directives any less of an issue today.
