### ISSUE TITLE
Can't lint files with square brackets in the name

### ISSUE THREAD

**Issue by staab** [eslint/eslint#11940]
**Tell us about your environment**

MacOS 10.14.5 (18F132)
zsh 5.3 (x86_64-apple-darwin18.0)

* **ESLint Version:** v6.0.1
* **Node Version:** v8.15.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
  },
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended",
  ],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly",
  },
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
  },
  "rules": {
    "no-unused-vars": ["error", {args: "none"}],
  },
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

No source, the bug happens even if the file is empty.

```bash
$ cat src/routes/blog/\[slug\].svelte
console.log('x',)
$ npx eslint src/routes/blog/\[slug\].svelte
No files matching 'src/routes/blog/[slug].svelte' were found.
$ npx eslint src/routes/blog/[slug].svelte
No files matching 'src/routes/blog/[slug].svelte' were found.
$ npx eslint src/routes/blog/\\[slug\\].svelte
No files matching 'src/routes/blog/\[slug\].svelte' were found.
```

**What did you expect to happen?**

That eslint would lint the file.

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint was unable to find the file.

**Are you willing to submit a pull request to fix this bug?**

I could give it a shot, but I'm probably not the best person to solve it.

**Comment by mysticatea** [comment]
Thank you for your report.

I confirmed it on a Linux VM.

The cause is the following step in ESLint's file enumerator:

- `\[abc\].js` ... ESLint received it as `[abc].js`.
    1. `isGlob("[abc].js")` is `true` then it be handled as a glob; it matches any of `a.js`, `b.js`, and `c.js`.
- `\\[abc\\].js` ... ESLint received it as `\[abc\].js`.
    1. `isGlob("\\[abc\\].js")` is `false` then it be handled as a filename; it matches `\[abc\].js` rather than `[abc].js` on Linux. Also, it matches `C:\[abc\].js` on Windows (because `\` is the path separator).

Hmm. I'm considering how we should do.

**Comment by mysticatea** [comment]
ESLint cannot distinguish `[abc].js`, `\[abc\].js`, and `"[abc].js"` because ESLint receives all of those as the same string `"[abc].js"`. It's...
