### ISSUE TITLE
[cli]: Have a dedicated option to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [eslint/eslint#11958]
## Present Scenario

Presently, the Issue template (Bug report) asks the user to provide a couple of information concerning his/her local environment. 

## What is intended?

IMO it would be good to have a dedicated option, preferably `eslint --info` which would show up all the required information, and the Issue template could be updated accordingly.

**Comment by jamesgeorge007** [comment]
@aladdin-add I would love to submit a PR :+1:

**Comment by aladdin-add** [comment]
hi, @jamesgeorge007 thanks for reaching out!

We abide by the policy: 

> consensus is reached on issues when there are at least three team members who believe the change is a good idea and no one who believes the change is a bad idea. 

That is to say, it may take some time to accept the issue, but feel free to submit a PR! :)

**Comment by platinumazure** [comment]
The consensus process mostly applies to new rules and rule enhancements, whereas this is a CLI feature, so I think we need the TSC to evaluate it.

I like the idea enough that I've added it to the TSC agenda for our next meeting.

**Comment by not-an-aardvark** [comment]
In [the TSC meeting two weeks ago](https://github.com/eslint/tsc-meetings/blob/0103ba20ecbafb0910cbf2e62f9b7f3731d0ef1d/notes/2019/2019-07-18.md#cli-have-a-dedicated-option-to-show-up-local-environment-information), the TSC accepted this proposal with the implementation details to be figured out in this issue.

**Comment by jamesgeorge007** [comment]
@not-an-aardvark Kindly let me know when should I kickstart :smile:

**Comment by ilyavolodin** [comment]
@jamesgeorge007 I think we need to figure out exactly what type of info we should show first. Do you have suggestions?

**Comment by jamesgeorge007** [comment]
Preferably, what we ask in the issue-template as per now :thinking:

**Comment by jamesgeorge007** [comment]
> Preferably, what we ask in the issue-template as per now

concerning the user's local environment

**Comment by platinumazure** [comment]
Hi @jamesgeorge007, that sounds like a good start. I would suggest adding some logic to cli.js which prints that information to the console. Feel free to open a PR when you can get most/all of the fields to show up; if needed, we can help you get the rest of the way there and/or provide feedback on what's there.

**Comment by g-plane** [comment]
Should we print the configuration file?

**Comment by platinumazure** [comment]
@g-plane We already have `--print-config`. Are you thinking we should do something else? (And, should your proposal be in a new issue?)
