### ISSUE TITLE
no-redeclare errors on double-defined inline /* global variable */

### ISSUE THREAD

**Issue by dominikschreiber** [eslint/eslint#11979]
**Tell us about your environment** Reproduceable on [eslint.org/demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZ2xvYmFsIHdhdCAqL1xuLyogZ2xvYmFsIHdhdCAqLyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby1yZWRlY2xhcmUiOjJ9LCJlbnYiOnt9fX0=)

* **ESLint Version:** v6.0.1
* **Node Version:** unknown for eslint.org/demo, 8.16.0 in real life
* **npm Version:** unknown for eslint.org/demo, 6.4.1 in real life

**What parser (default, Babel-ESLint, etc.) are you using?** unknown for eslint.org/demo, default in real life

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 5,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "no-redeclare": 2
    },
    "env": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* global wat */
/* global wat */
```

https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZ2xvYmFsIHdhdCAqL1xuLyogZ2xvYmFsIHdhdCAqLyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby1yZWRlY2xhcmUiOjJ9LCJlbnYiOnt9fX0=

**What did you expect to happen?**
No code, just comments => no errors.

**What actually happened? Please include the actual, raw output from ESLint.**
2:11 'wat' is already defined (no-redeclare)

This is obviously a minimal example. In real life, globals are defined in the files they are used in (because we don't need them everywhere), so only 1 per file. But running eslint on all js sources (`eslint **/*.js`) throws these no-redeclare errors.

If you don't consider this a bug in no-redeclare, could no-redeclare then work with an option similar to `builtinGlobals:true` that ignores variables defined as global, like `definedGlobals:false`?

**Comment by mysticatea** [comment]
Thank you for your report.

This is intentional behavior since 6.0.0. See [the migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0#no-redeclare-updates).

> ..., so only 1 per file. But running eslint on all js sources (eslint **/*.js) throws these no-redeclare errors.

I'm not sure what your problem is. ESLint verifies each file independently, so `/*globals*/` comments in other files don't effect anyway.

**Comment by dominikschreiber** [comment]
Ah, thank you for that hint. I revisited what the actual problem is, and I think it stems from variables being defined global in the eslintrc and then also defined global on a per-file level. So the problem really is
```js
// .eslintrc.json
{
  // ...
  "globals": {
    "wat": false
  }
}

// my-file.js
/* global wat */
```
My dev eslintrc is stricter than the one for our central builds (because not everyone wants to define globals on a per-file level), so locally (without globals in the eslintrc) eslint is happy, but in our central builds these "'wat' is already defined" errors occur.

**Comment by mysticatea** [comment]
Thank you for the investigation.

...but it's a redeclaration that `no-redeclare` rule should catch. The `builtinGlobals:false` option will ignore the redeclaration of globals.

**Comment by dominikschreiber** [comment]
> ...but it's a redeclaration that `no-redeclare` rule should catch.

I'm sorry, I don't get that point of view. From my understanding `/* global wat */` does not _declare_ a variable (in a control-flow altering way, via `var`/`let`/`const`), it merely _tells_ eslint that `wat` should be considered global (so that `no-undef` et al. don't fail). Going in that direction, I'd say "something can't be more global than being global", therefore it shouldn't harm to inform eslint about variables being global multiple times.

It may be an implementation detail of no-redeclare or eslint that `/* global wat */` gets rewritten to `var wat;` or similar, but from my understanding that should not change the behavior.

**Comment by jsg2021** [comment]
I second @dominikschreiber. The global comment directive should not trip this rule. 😕

**Comment by kaicataldo** [comment]
I do agree that isn't intuitive behavior. So, just to clarify, the edge case here is having the same global defined in both a config file and locally in a file using a `/* global */` comment, correct? For this case, I feel like it would make sense to just merge the globals (accounting for if they're `"writable"` or `"readonly"` and warning when those don't match).
