### ISSUE TITLE
Allow snapshot test

### ISSUE THREAD

**Issue by fa93hws** [eslint/eslint#11988]
**The version of ESLint you are using.**
Not important

**The problem you want to solve.**
Improve development experience with the testing.

**Your take on the correct solution to problem.**
Using snapshot test to provide more conclusive result
![8E2DD8E6-1763-4D32-89EF-07DFC8FEDC00](https://user-images.githubusercontent.com/10626756/61182572-c0a78080-a678-11e9-86b7-bb3e09a052cc.png)

**Are you willing to submit a pull request to implement this change?**
https://github.com/eslint/eslint/pull/11987

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue. Could you elaborate on what problems with developer experience you're encountering, and how the snapshot testing would work specifically (e.g. what APIs would be exposed)? I looked at the PR that you created, but not immediately clear how this works by looking at the PR, particularly since it didn't include documentation.

**Comment by fa93hws** [comment]
> Hi, thanks for creating an issue. Could you elaborate on what problems with developer experience you're encountering, and how the snapshot testing would work specifically (e.g. what APIs would be exposed)? I looked at the PR that you created, but not immediately clear how this works by looking at the PR, particularly since it didn't include documentation.

Hi! Thanks for the reply.
> Could you elaborate on what problems with developer experience you're encountering

It was hard to see what the linting result is by looking at the test. Most of the information provided are indirectly related to what is shown on the IDE.

For example, if the linting is supposed to give linting error on the `para` in `fn(para)` instead of on the `fn` or the whole. The only way to do so is by counting the row and the column, which isn't a good experience.

> what APIs would be exposed

I think exposing a `generateErrorSnapshot` and a `generateFixSnapshot` should be enough.
It's consumer's responsibility to compare the snapshot. They are free to use any snapshot test tool. or write their own to get rid of the character escaping. While the string is provided in the eslint side.
