### ISSUE TITLE
Put .eslintignore in config file

### ISSUE THREAD

**Issue by hangyangws** [eslint/eslint#11995]
Every APP has many config files.
And eslint has two config files: config file and the ignore file.
Why put ignore info into config file as a ignore field,
just like:
```json
{
   "ignore": [
     "build/",
     "tests/",
     "node_modules/"
   ]
}
```

?

**Comment by kaicataldo** [comment]
This is currently being proposed [here](https://github.com/eslint/rfcs/pull/22). Please track that issue.
