### ISSUE TITLE
Typo in no-duplicate-imports Rule Documentation

### ISSUE THREAD

**Issue by olsonek** [eslint/eslint#11999]
I believe there is a typo in the [Rule Details section for no-duplicate-imports](https://eslint.org/docs/rules/no-duplicate-imports#rule-details).

> This _rules_ requires that all imports from a single module exists in a single import statement.

I will make a PR to resolve this issue shortly.

**Comment by platinumazure** [comment]
Hi @olsonek, thanks for the issue.

I agree this is a typo/mistake. Thanks for creating an issue and I look forward to your pull request!
