### ISSUE TITLE
Warn when ESLint directives which expect to be used in block level comments are used in inline comments

### ISSUE THREAD

**Issue by captbaritone** [eslint/eslint#12014]
**The problem you want to solve.**

ESLint requires that `eslint-disable rule-name` and similar directives are placed in block level comments (`/* */`) and not in inline comments (`// `). 

> To temporarily disable rule warnings in your file, use __block comments__ in the following format:

-- [Configuring ESLint](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments)

While the rational is not stated in the docs, I assume this is because disabling a rule is a "big deal" and that should be reflected in the type of comment used.

I think this requirement makes sense, but it can be hard to remember, and when you get it wrong (use an inline comment instead of a block level comment), ESLint just silently ignores your request.

**Your take on the correct solution to problem.**

I propose that we emit an error or warning when we discover an ESLint directive that is in the incorrect type of comment.

There is some precedent for this, as [getDirectiveComments](https://github.com/eslint/eslint/blob/1fb362093a65b99456a11029967d9ee0c31fd697/lib/linter/linter.js#L263) already has a number of different places where it will emit problems.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by kaicataldo** [comment]
This seems like a nice improvement to the developer experience to me, but I’m curious what you mean by 

> ...when you get it wrong (use an inline comment instead of a block level comment), ESLint just silently ignores your request.

Since it’s a disable comment, I would expect that the rules the user intended to disable would start warning.

I believe these are block comments because that allows for more fine grained control over where you can put the comments (i.e. in front of code on a given line).

**Comment by kaicataldo** [comment]
One more thing: changes to core require going through our [RFC process](https://github.com/eslint/rfcs), but we’re happy to discuss here and give feedback!

**Comment by captbaritone** [comment]
> Since it’s a disable comment, I would expect that the rules the user intended to disable would start warning.

Correct. By "silently ignores your request" I just mean that the comment has no effect on ESLint's behavior. In the workflow where a user is trying to ignore a rule which is currently causing an error, they might add `// eslint-disable my-rule` and then be very confused as to why it didn't work.

Good to know about the RFC process. Should I proceed to open PR against that repo, or would it be worth having some discussion here first?

**Comment by captbaritone** [comment]
I went ahead and opened the RFC: https://github.com/eslint/rfcs/pull/34
