### ISSUE TITLE
getConfigHierarchy   baseconfig

### ISSUE THREAD

**Issue by crecreek** [eslint/eslint#12013]
hao can i get specificConfig  without baseconfig?

=====
my programe mixed js and ts, i want to use all  rules to ts,but use js rules to jsfile,  
i find a method  to fix this,   
  overrides: [
    Object.assign(
        {
          files: ['*.js', '*.jsx'],
        },
        require('/somefile/'),
    ),
  ]

but  the keyword ‘extend’  in my required file ,  some error 

Unexpected top-level property "overrides[0].extends". . Please see the 'ESLint' output channel for details.

so i want to use printconfig to get js config,   but  the config is contain baseconfig, and when i printconfig  the engine is read eslintrc,   in loop,

help me ?

**Comment by aladdin-add** [comment]
which version are you using?  can you give some more background?

I'm not sure I've got all your meaning, just a reminder: extends in eslintrc is supported in `eslint>=6.0.0-alpha.2` https://github.com/eslint/eslint/commit/54e6edaa2f881aab530fa14e63d92e5e0e2ca55c

**Comment by crecreek** [comment]
its my config fault, sorry
