### ISSUE TITLE
Remove implied eval check from no-eval

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#1202]
The rule `no-eval` checks for `eval` and implied `eval` occurrences. So I wonder why we need the extra rule `no-implied-eval`.
We could add an option to the `no-eval` rule to only check for implied eval but allow calling `eval()` directly.

Is there any other special reason why there are two separate rules?

**Update:** As discussed, `no-eval` and `no-implied-eval` should be separate rules. To avoid duplication of functionality we should remove the implied eval check from `no-eval`.

**Comment by lo1tuma** [comment]
@nzakas any thoughts about this?

**Comment by nzakas** [comment]
I kind of like having these separate. I found JSLint/JSHint's bundling of the two confusing.

**Comment by lo1tuma** [comment]
If you want to have those separate, we should remove the check for implied eval from `no-eval` because we have a separate rule `no-implied-eval` for it.

**Comment by nzakas** [comment]
Agreed.
