### ISSUE TITLE
Improve `padding-line-between-statements` for `delete` operator

### ISSUE THREAD

**Issue by evilebottnawi** [eslint/eslint#12025]
**What rule do you want to change?**

`padding-line-between-statements`

**Does this change cause the rule to produce more or fewer warnings?**

more

**How will the change be implemented? (New option, new default behavior, etc.)?**

Add `delete` to `STATEMENT_TYPE`. I understand that this is not entirely true because it is a unary expression with `delete` operator, but maybe it will be easy to understand other developers.

**Please provide some example code that this change will affect:**

```js
const obj = getObj();
delete obj.test;
obj.bar();
```

**What does the rule currently do for this code?**

No errors/warnings for code above

**What will the rule do after it's changed?**

Require newline before/after `delete` (depends on how the developer setup the rule)

```js
const obj = getObj();

delete obj.test;

obj.bar();
```

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by platinumazure** [comment]
Hi @evilebottnawi, thanks for the issue.

I support this enhancement.
