### ISSUE TITLE
write an implementation that uses Deno

### ISSUE THREAD

**Issue by catastrop** [eslint/eslint#12029]

**Comment by catastrop** [comment]
write an implementation that uses Deno instead of Nodejs

**Comment by ilyavolodin** [comment]
ESLint was created to only support one environment (that was a concise decision). Even browser runtime is not officially supported, ESLint just happens to work in browser when compiled properly. We currently have no plans to change that rule. If Deno overtakes NodeJS in popularity we can revisit that decision, but for not, I don't think this is going to happen.
