### ISSUE TITLE
eslint does not see plugins when using node.js api (Definition for rule <ruleName> was not found.)

### ISSUE THREAD

**Issue by sharikovvladislav** [eslint/eslint#12030]
**Tell us about your environment**

* **ESLint Version:** 6.1.0
* **Node Version:** v10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** 

<details>
<summary>Configuration</summary>

```js
{
    "extends": [
        "eslint:recommended",
        "plugin:node/recommended"
    ],
    "rules": {
        "node/exports-style": ["error", "module.exports"],
        "node/file-extension-in-import": ["error", "always"],
        "node/prefer-global/buffer": ["error", "always"],
        "node/prefer-global/console": ["error", "always"],
        "node/prefer-global/process": ["error", "always"],
        "node/prefer-global/url-search-params": ["error", "always"],
        "node/prefer-global/url": ["error", "always"],
        "node/prefer-promises/dns": "error",
        "node/prefer-promises/fs": "error"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const CLIEngine = require('eslint').CLIEngine;
const Linter = require('eslint').Linter;
const path = require('path');

const cli = new CLIEngine({
    configPath: path.resolve(process.cwd(), '.eslintrc.json')
});

const linter = new Linter();

const result = linter.verifyAndFix('var foo', cli.getConfigForFile("script.js"));

console.log(result);

```

I just want to lint & fix code `var foo`. I am creating CLIEngine instance (looks like only to get config for some file in future). Also I am creating linter instance. And I use it to lint & fix the code.

I also found this: https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile. Where you don't create instance by `new Linter` but use `require("eslint").linter`. Can you tell my why and what is the difference? Looks like other 12 examples on same page are about cretating the instance...

```bash
node script.js
```

**What did you expect to happen?**

I expect that after linting using node.js API I will get only one error: `'\'foo\' is defined but never used.'`.

**What actually happened? Please include the actual, raw output from ESLint.**
I am getting "Definition for rule <ruleName> was not found." error for every rule defined by `eslint-plugin-node` (problem is with any plugin, not specifically about this one).

I have this in console:

```
 ~/tmp/test-eslint-with-plugins   master ●  node script
{ fixed: false,
  messages:
   [ { ruleId: 'node/no-extraneous-require',
       message:
        'Definition for rule \'node/no-extraneous-require\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/exports-style',
       message: 'Definition for rule \'node/exports-style\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-global/buffer',
       message:
        'Definition for rule \'node/prefer-global/buffer\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-global/console',
       message:
        'Definition for rule \'node/prefer-global/console\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-global/process',
       message:
        'Definition for rule \'node/prefer-global/process\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-global/url-search-params',
       message:
        'Definition for rule \'node/prefer-global/url-search-params\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-global/url',
       message:
        'Definition for rule \'node/prefer-global/url\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-promises/dns',
       message:
        'Definition for rule \'node/prefer-promises/dns\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/prefer-promises/fs',
       message:
        'Definition for rule \'node/prefer-promises/fs\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-deprecated-api',
       message:
        'Definition for rule \'node/no-deprecated-api\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/file-extension-in-import',
       message:
        'Definition for rule \'node/file-extension-in-import\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-missing-require',
       message:
        'Definition for rule \'node/no-missing-require\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-unpublished-bin',
       message:
        'Definition for rule \'node/no-unpublished-bin\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-unpublished-require',
       message:
        'Definition for rule \'node/no-unpublished-require\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-unsupported-features/es-builtins',
       message:
        'Definition for rule \'node/no-unsupported-features/es-builtins\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-unsupported-features/es-syntax',
       message:
        'Definition for rule \'node/no-unsupported-features/es-syntax\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/no-unsupported-features/node-builtins',
       message:
        'Definition for rule \'node/no-unsupported-features/node-builtins\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/process-exit-as-throw',
       message:
        'Definition for rule \'node/process-exit-as-throw\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'node/shebang',
       message: 'Definition for rule \'node/shebang\' was not found.',
       line: 1,
       column: 1,
       endLine: 1,
       endColumn: 2,
       severity: 2,
       nodeType: null },
     { ruleId: 'no-unused-vars',
       severity: 2,
       message: '\'foo\' is defined but never used.',
       line: 1,
       column: 5,
       nodeType: 'Identifier',
       endLine: 1,
       endColumn: 8 } ],
  output: 'var foo' }
 ~/tmp/test-eslint-with-plugins   master ● 
```

If I use `npx eslint script.js` command in terminal, everything is ok. Just for test I added `var x = 5;` to the code to check it. Here is the result:

```
 ~/tmp/test-eslint-with-plugins   master ●  npx eslint script.js

/Users/vladislav.sharikov/tmp/test-eslint-with-plugins/script.js
  10:5  error  'x' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Are you willing to submit a pull request to fix this bug?**

Not yet. I don't understand if it is normal behavior or not. Looks like I am using this correctly, but I still get the error.

The problem is not only about `eslint-plugin-node`. I created some small repo to reproduce this bug and added `eslint-plugin-node` to test if I have the problem. I have rather huge project where I tried to do some stuff with eslint node.js API and I have save with all (not almost all, but **all** plugins).

Here is the repo: https://github.com/sharikovvladislav/eslint-try-api-with-plugins. All code is here. You also can clone the repo, `npm i` and try same what I am trying. You will get the error (probably xD).

I also asked same in gitter and in stackoverflow, but I got no answer. Here is the question: https://stackoverflow.com/questions/57221475/why-my-eslint-script-can-not-resolve-eslint-plugin-dependencies

I am not sure it is a bug. Looks like I misunderstand some small point.... Sorry if so. Can you please explain where is the problem?

Also, can you clarify the difference between creating instance of Linter and using `require("eslint").linter`?

**Comment by sharikovvladislav** [comment]
Any thoughts?

**Comment by jehy** [comment]
It can be a breaking fix from ESLint 6, try version 5. See more here: https://github.com/eslint/eslint/issues/11964

**Comment by sharikovvladislav** [comment]
Tried on eslint@5.16.0. Same problem.

**Comment by sharikovvladislav** [comment]
I debugged a little how eslint command line interface works. Under the hood it uses executeOnFiles method of CLIEngine instance.

I tried same and it worked perfectly.

Well, as I think the question about nodejs api is still opened.

**Comment by g-plane** [comment]
1. `require("eslint").linter` is deprecated, and don't use it. Use `new Linter` instead.
2. We recommend you to use an instance of `CLIEngine` directly. This is a high-level API.

**Comment by mysticatea** [comment]
`Linter` class is designed to work in browsers, so it doesn't depend on any file system. This means that the `Linter` doesn't find/load any plugins, parsers, and shareable configs. You have to prepare those manually by `linter.defineRule` method and something like.

On the other hand, `CLIEngine` class works with file system. It resolves plugins, parsers, and shareable configs, then prepares `Linter` and does lint.

**Comment by sharikovvladislav** [comment]
Thank you for your answers.

@g-plane thats exactly what I do (1 item in the list).
@mysticatea 

<details>
![image](https://user-images.githubusercontent.com/5622526/62102321-447c8200-b2a1-11e9-90a2-c3a344dca0d9.png)
</details>
This is what we can see at docs page of node.js API. You can see something like CLIEngine, Linter and stuff. Seems to me, after looking there it is obvious to use things like I used. I assumed that config object from CLIEngine would be enough.

`defineRule` I thought about it too (just a thought) and assumed it could help, but didn't give a try.

Is it mentioned explicitly in the node.js API docs? If yes, thats just my fault. If not, probably, it should be.

**Comment by mysticatea** [comment]
I agree that our documentation is not perfect. The PRs that improve documentation would be appreciated.

For reference, a previous discussion is here: https://github.com/eslint/eslint/pull/11070
