### ISSUE TITLE
flatTernaryExpressions not working in inline ternarys

### ISSUE THREAD

**Issue by Soaku** [eslint/eslint#12039]
**Tell us about your environment**

* **ESLint Version:** v5.16.0
* **Node Version:** v12.6.0
* **npm Version:** v6.10.1

**What parser (default, Babel-ESLint, etc.) are you using?**  `@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "es6": true,
        "node": true
    },
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint"
    ],
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1,
                "flatTernaryExpressions": true
            }
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": "off",
        "@typescript-eslint/semi": "error",
        "no-var": "error",
        "no-case-declarations": "off",
        "no-unused-vars": "off",
        "no-console": "off",
        "no-empty": "off",
        "no-dupe-class-members": "off",
        "no-constant-condition": "off",
        "no-cond-assign": "off"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

The `flatTernaryExpressions` rule doesn't seem to work properly on ternaries inside function calls.

```js
someFunction(
    variable === "value" ? "Foo"
        : variable === "other value" ? "Bar"
        : "Foobar"
);
```
ESLint doesn't consider the above code as valid and requires the indentation level to be lower.

```
Expected indentation of 16 spaces but found 20. eslint(indent)
```

**Are you willing to submit a pull request to fix this bug?** Not likely.

**Comment by aladdin-add** [comment]
I recommend to use `@typescript-eslint/eslint-plugin/indent`, as you are using typescript.

**Comment by kaicataldo** [comment]
@Soaku Does this issue also occur with the default parser?

**Comment by Soaku** [comment]
@kaicataldo It seems it does, here's a sample project: 
[issue12039.zip](https://github.com/eslint/eslint/files/3456968/issue12039.zip)

@aladdin-add It seems the `@typescript-eslint/indent` has the exact same issue. I disabled `indent` and the error didn't change.
