### ISSUE TITLE
Syntax error while doing "node ./node_modules/.bin/eslint --init" on windows

### ISSUE THREAD

**Issue by dakshj48** [eslint/eslint#12040]
**Tell us about your environment**

* **ESLint Version:** 6.1.0
* **Node Version:** v12.2.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
N/A
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
N/A
```

```bash
node ./node_modules/.bin/eslint --init
```

**What did you expect to happen?**
Run config initialization wizard.

**What actually happened? Please include the actual, raw output from ESLint.**
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by g-plane** [comment]
Hi @dakshj48 , `./node_modules/.bin/eslint` is for Linux or macOS.

You can use `npx eslint --init` or `yarn eslint --init` for cross-platform usage.

**Comment by dakshj48** [comment]
It worked, thanks!
