### ISSUE TITLE
padding-line-between-statements for empty line before return statement

### ISSUE THREAD

**Issue by indapublic** [eslint/eslint#12050]
**Tell us about your environment**

* **ESLint Version:**
5.16.0
* **Node Version:**
v10.16.1
* **npm Version:**
6.9.0
* **yarn Version:**
1.17.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "parser": "babel-eslint",
  "plugins": [
    "react",
    "react-native",
    "sort-imports-es6-autofix"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "airbnb-base",
    "prettier"
  ],
  "rules": {
    "semi": [
      "error",
      "never"
    ],
    "quotes": [
      "error",
      "double"
    ],
    "indent": [
      "error",
      "tab",
      {
        "SwitchCase": 1
      }
    ],
    "no-tabs": [
      "error",
      {
        "allowIndentationTabs": true
      }
    ],
    "import/prefer-default-export": "off",
    "class-methods-use-this": [
      "error",
      {
        "exceptMethods": [
          "componentDidMount",
          "componentWillUnmount",
          "componentDidCatch",
          "render"
        ]
      }
    ],
    "sort-imports-es6-autofix/sort-imports-es6": [
      2,
      {
        "ignoreCase": false,
        "ignoreMemberSort": false,
        "memberSyntaxSortOrder": [
          "none",
          "all",
          "multiple",
          "single"
        ]
      }
    ],
    "eol-last": [
      "error",
      "always"
    ],
    "no-case-declarations": "off",
    "no-return-await": "off",
    "newline-before-return": "error",
    "padding-line-between-statements": [
      "error",
      { "blankLine": "always", "prev": "var", "next": "return" }
    ]
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const combinedForeground = StyleSheet.flatten([
	{
		marginTop: showlogo ? width / 3 : width / 3,
	},
	styles.loginForeground,
])
return (
	<Container>
		<Content scrollEnabled={false} contentContainerStyle={styles.container}>
```

```bash
yarn eslint
```

`newline-before-return` will show errors but `padding-line-between-statements` will pass it.

``` 
12:2  error  Expected newline before return statement  newline-before-return
```

**Comment by platinumazure** [comment]
Hi @indapublic, thanks for the issue.

I think this is working as designed in your case. The `var` statement type only matches variable declarations with the `var` keyword, but your code uses `const`.

If your goal is to emulate `newline-before-return` behavior, you can use `"*"` as a statement type. Otherwise, if you only want the rule to apply for variable declarations, you'll need to have 3 configurations in the rule (for `"var"`, `"let"`, and `"const"`).

Unfortunately, at the moment we don't have support for checking all variable declarations as one statement type.

**Comment by indapublic** [comment]
Understood. Thanks, @platinumazure
