### ISSUE TITLE
no-mixed-operators

### ISSUE THREAD

**Issue by minbelapps** [eslint/eslint#12052]
`allowSamePrecedence` should be turned by default. 

The thig is that `a + b - d`  is the same `a - d + b` - it's the **Associative Operation**, and the brackets in this situation just add not necessary noise.

Usually, some clients have default Eslint configurations and it's not easy to disable Eslint rules in the code as it could require the justification on code review.

The default configuration should bring the biggest value, not the biggest restrictions.

**Comment by ilyavolodin** [comment]
Could you edit your issue to follow our Proposing a Rule Change template please? It provides us with common ground for evaluating all requests. Thanks.
