### ISSUE TITLE
Feature Request: Set custom formatter in .eslintrc

### ISSUE THREAD

**Issue by devinrhode2** [eslint/eslint#12115]
**The version of ESLint you are using.**
6.1.0

**The problem you want to solve.**
Set custom formatter via eslintrc file. (https://eslint.org/docs/user-guide/formatters/#eslint-formatters)

It seems that eslint only supports custom formatters via the command line flag `-f` and via CLIEngine api.

I have dug around for a few hours and it looks like you can only set a custom formatter via cli OR the CLIEngine

Not sure how this would be implemented...

**Comment by kaicataldo** [comment]
Do you mind explaining the problem you’re trying to solve with this proposal? Please note that changes to core are required to go through our RFC process outlined [here](https://github.com/eslint/rfcs).

**Comment by devinrhode2** [comment]
Just a more convenient/accessible way to set a custom formatter. That's all. I had a hard time figuring out how to set loader options via craco for webpack's eslint-loader. Took be a while but I have it all figured out. So feel free to close. (My answer is on SO for anyone googling)

**Comment by kaicataldo** [comment]
Thanks for explaining. If you'd like to write up an RFC, please feel free!

**Comment by kaicataldo** [comment]
Alternatively, if you feel documentation can be at all improved, we'd love a PR :)

**Comment by devinrhode2** [comment]
Idk could probably add something like

"You cannot currently set formatter via eslintrc. If you don't run eslint
via the command line, you'll have to dig into whatever tools you are using
to run eslint to see how to configure a formatter.
You may find the readme for eslint-formatter-friendly a good starting
point: https://github.com/royriojas/eslint-formatter-friendly"

eslint-formatter-friendly readme already outlines how to add the custom
formatter via a variety of tools+methods. My craco config should be added
there to keep everything in one place.

-Devin <http://devinrhode2.github.io>
<http://devinrhode2.github.io/>
