### ISSUE TITLE
indent issue with tagged template literals

### ISSUE THREAD

**Issue by msvab** [eslint/eslint#12122]
**Tell us about your environment**

* **ESLint Version:** 6.2.0
* **Node Version:** 10.16.3
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "es6": true,
    "jest/globals": true
  },
  "plugins": ["jest"],
  "rules": {
    "indent": [
      "error", 2, {
      "SwitchCase": 1,
      "VariableDeclarator": 1,
      "outerIIFEBody": 1,
      "FunctionDeclaration": {
        "parameters": 1,
        "body": 1
      },
      "FunctionExpression": {
        "parameters": 1,
        "body": 1
      },
      "CallExpression": {
        "arguments": 1
      },
      "ArrayExpression": 1,
      "ObjectExpression": 1,
      "ImportDeclaration": 1,
      "flatTernaryExpressions": false,
      "ignoredNodes": [
        "JSXElement", "JSXElement > *", "JSXAttribute", "JSXIdentifier", "JSXNamespacedName", "JSXMemberExpression", "JSXSpreadAttribute", "JSXExpressionContainer", "JSXOpeningElement", "JSXClosingElement", "JSXText", "JSXEmptyExpression", "JSXSpreadChild"
      ],
      "ignoreComments": false
    }]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

describe('Indentation Bug', () => {

  test.each`
    a    | b
    ${1} | ${1}
  `('$a == $b', ({ a, b }) => {
    expect(a).toBe(b); // error  Expected indentation of 2 spaces but found 4  indent
  }); // error  Expected indentation of 0 spaces but found 2  indent
});
```

```bash
eslint .
```

**What did you expect to happen?**
I would expect the code indentation to be valid.

**What actually happened? Please include the actual, raw output from ESLint.**
Following eslint errors are displayed:

```
8:1  error  Expected indentation of 2 spaces but found 4  indent
9:1  error  Expected indentation of 0 spaces but found 2  indent
```

I've created a small repo where you can easily reproduce the issue.
https://github.com/msvab/eslint-tagged-literal-indent-bug

**Are you willing to submit a pull request to fix this bug?**
I can try, but I have zero knowledge on eslint internals.

**Comment by kaicataldo** [comment]
For clarity's sake, can you add comments in the example that show us exactly which lines the errors are being reported on?

**Comment by msvab** [comment]
> For clarity's sake, can you add comments in the example that show us exactly which lines the errors are being reported on?

Done.

**Comment by seetd** [comment]
It might take some time to get familiar with inner workings Eslint but I am interested in taking this up.

**Comment by kaicataldo** [comment]
@seetd Fantastic! Feel free to comment here or visit [our chat](https://gitter.im/eslint/eslint) if you run into any issues or want to talk through anything.

**Comment by seetd** [comment]
Sorry I started looking into the issue but something crop up that I had to attend. Once I get that competed I will come back to this. I thought it will be good to drop a note here in case someone else wants to pick this up before that.

**Comment by kaicataldo** [comment]
Reopening and assigning to myself so it doesn't get auto closed again.

**Comment by CinKon** [comment]
It's still closed though ;)
I'd really like to get this fixed too, as I have to disable the indent rule on test-files otherwise...

**Comment by kaicataldo** [comment]
Whoops, sorry. Reopened now!
