### ISSUE TITLE
enhance "quotes" fixer to take "avoidEscape" into consideration

### ISSUE THREAD

**Issue by wmhilton** [eslint/eslint#12129]
**What rule do you want to change?**
`eslint --fix` rewrote my template strings (containing single quotes) into single quote strings (containing escaped single quotes) despite the fact that the `avoidEscape` setting was true.

I'd like to enhance the fixer function for https://eslint.org/docs/rules/quotes to take the `avoidEscape` setting into account when converting quotes from backtick to single quotes.

**Does this change cause the rule to produce more or fewer warnings?**
exactly the same

**How will the change be implemented? (New option, new default behavior, etc.)?**
I would modify this function to have a second argument, `avoidEscape`:
https://github.com/eslint/eslint/blob/4aeeeedb656ee3519ea82ebf0cb41ca801215046/lib/rules/quotes.js#L48-L69

**Please provide some example code that this change will affect:**

e.g. with these rules:
```json
"quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": false }],
```

and this code

```js
console.log(`'a.txt' exists`)
```

running `eslint --fix` would generate the following:
```js
console.log("'a.txt' exists")
```

**What does the rule currently do for this code?**
currently the fixer generates this:
```js
console.log('\'a.txt\' exists')
```

which is technically correct but not as nice

**What will the rule do after it's changed?**
rule is same, only fixer changes

**Are you willing to submit a pull request to implement this change?**
yup

---
Note: kinda related to https://github.com/eslint/eslint/issues/10627

closes https://github.com/standard/standard/issues/1380

**Comment by mdjermanovic** [comment]
Hi @wmhilton, thank you for the proposal and for the relevant link.

Someone will correct me if I'm wrong, I think that this enhancement would be incompatible with #10627 and that the question should the rule report error should be resolved first.

**Comment by feross** [comment]
@mdjermanovic I don't see how the proposed change in this issue is incompatible with #10627.

If I understand correctly, this issue is proposing that when the rule `"quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": false }]` is in effect, ESLint should prefer correcting `console.log(`'a.txt' exists`)` to `console.log("'a.txt' exists")` rather than `console.log('\'a.txt\' exists').

**Comment by mdjermanovic** [comment]
Makes sense, but the proposed change in #10627 is *no error reported*. That's why this is incompatible.

Or am I reading something wrong, one example is with single quotes the other with double quotes but it's the same situation with different proposals?

**Comment by feross** [comment]
> Makes sense, but the proposed change in #10627 is no error reported

I see. The reason I though this was unrelated is that we specify `"allowTemplateLiterals": false` and also `"avoidEscape": true` so there's no ambiguity about what type of quotes we prefer to be used to avoid escaping.

**Comment by mdjermanovic** [comment]
> 
> I see. The reason I though this was unrelated is that we specify `"allowTemplateLiterals": false` and also `"avoidEscape": true` so there's no ambiguity about what type of quotes we prefer to be used to avoid escaping.

Yes, but the rule shouldn't work differently with the explicit option's value than with the implicit default value (`false`), so it's the same whether you put `"allowTemplateLiterals": false` or omit the option.
