### ISSUE TITLE
Autofix (--fix) violations of `argsIgnorePattern`

### ISSUE THREAD

**Issue by gerardolima** [eslint/eslint#12130]
I just enforced the pattern for unused args and that yielded errors on more than 200 files. Although the changes are trivial, that's a lot of files and each change will be a chance of introducing bugs.

So I wonder if that could be an improvement to the `--fix` option, at least the most common cases such as the patterns that describe a prefix (i.e. ` "argsIgnorePattern": "^_"`).

**Comment by gerardolima** [comment]
This is not a bug report, this is a suggestion for enhancement of the autofixer. The required information follows below:
- The version of ESLint you are using (run eslint -v)
_v6.1.0_
- What you did (the source code and ESLint configuration)

```
--- .eslintrc.json ---
{
  "env": { "es6": true, "node": true },
  "parser": "babel-eslint",
  "extends": ["eslint:recommended", "standard-react"],
  "rules": { "no-unused-vars": [ 2, { "vars": "all", "args": "all", "argsIgnorePattern": "^_", "ignoreRestSiblings": false } ] }
}
```
```
--- myfile.js ---
function aa (abc) {}
module.exports = { aa }
```
```
--- command ---
eslint myfile.js --fix
```
- The actual ESLint output complete with numbers
```
/Users/<path-was-removed>/myfile.js
  1:14  error  'abc' is defined but never used. Allowed unused args must match /^_/u  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```
- What you expected to happen instead
I expected `myfile.js` to be autofixed as the following and no errors to be triggered:
```
--- myfile.js ---
function aa (_abc) {}
module.exports = { aa }
```

**Comment by gerardolima** [comment]
Since `argsIgnorePattern` is a simple prefix (_and I assume here this is the most common case_), this would allow for automatically fixing the name of the parameter.

This is no big deal for one file, but adding this rule on an existing codebase can easily yield the need to manually changing a big number of files.

**Comment by kaicataldo** [comment]
Thank you for filling out the template. I have a much better understanding what you're proposing now.

This seems like a reasonable behavior for the case you've described, however I'm not sure how we would go about actually implementing it since the configuration for this is a `RegExp`. In the case of an leading or trailing underscore like this, the fix is clear, but I don't know how the rule would be able to fix most other configuration options. It feels like you would have to be able to provide your own fixer function, which I don't know if we can support (since configuration files can have other extensions besides `.js`).

Do you have an idea of how this could actually work?

**Comment by gerardolima** [comment]
hey, @kaicataldo, thank you for your response!

I understand that such a general autofix, one that could fix any `RegExp`, would not be feasible. Nevertheless, it seems that an implementation for the simple (and, I expect, most common) cases would already be a great help :)

**Comment by mdjermanovic** [comment]
Perhaps a 3rd party plugin like [eslint-plugin-autofix](https://www.npmjs.com/package/eslint-plugin-autofix) could help.

A recent modification in [this PR](https://github.com/aladdin-add/eslint-plugin/pull/59) looks like your example.

**Comment by gerardolima** [comment]
hey, @mdjermanovic, yes it seems the PR you referred would indeed fix the situation I described; thank you!! Nevertheless, wouldn't that be a nice addiction to be incorporated into eslint?

_As a personal preference_, I try to avoid too many plugins, to reduce the risk exposure regarding different policies of tests/bug-fixes/releases/compatibilities/etc ... and, since eslint is not expected to be bundled into target objects, I believe it wouldn't matter much if some couple of lines were added to its codebase.

What's your opinions, @mdjermanovic and @kaicataldo?

**Comment by mdjermanovic** [comment]
I personally see unused variables as a possible error, and wouldn't like the core rule to auto-fix and hide errors.

3d party plugin could be used just as a utility to fix the existing codebase (if you trust that already existing unused variables are not errors) before enabling the core rule.
