### ISSUE TITLE
Potential plugin paths issue

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1214]
I've not had time to fully test this, but it looks like plugins won't work correctly when the plugin is installed at the same level as ESLint itself. For example, I'd expect a project using ESLint and a plugin to have dependencies in the `package.json` look like:

```
"dependencies": {
    "eslint":"^0.7.4",
    "eslint-plugin-foo": "^0.1.0"
}
```

In that case, if inside of ESLint we do `require('eslint-plugin-foo')`, it will fail because it's not a direct dependency of ESLint in that package (it's a sibling).

I think this means we may need to do a filepath instead of just a package name.

**Comment by ahmedelgabri** [comment]
@nzakas @lo1tuma I have the exact same issue right now. I'm using  [ESLint React plugin](https://github.com/yannickcr/eslint-plugin-react) & my `package.json` has this 

```json
    "eslint": "^0.20.0",
    "eslint-plugin-react": "^2.2.0"
```

When I run `eslint <filepath>` I get this error

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:107:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:98:21)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:179:5)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
```
But if I install the plugin globally it works, but that's not how it should work.

**Comment by ilyavolodin** [comment]
@ahmedelgabri How do you run eslint? Do you also have another instance of eslint installed globally?

**Comment by gyandeeps** [comment]
Can you share the dependencies and devDependencies from your project?

I have seen something like this happen but that depends upon how the hierarchy is laid out. That why if u can share more datils that would be awesome.

**Comment by ahmedelgabri** [comment]
@ilyavolodin I'm using it inside Gulp which runs fine. But I was getting lots of error in Vim when [Syntastic](https://github.com/scrooloose/syntastic) tries to lint the files. debugging the issue I found that Syntastic was running this command on the file `eslint -f compact <file>`.

Which lead me to try to actually run the command in the command line and did actually fail. And yes I have a global instance of eslint installed.

@gyandeeps I don't understand how is this might be related but here you go

```json
  "dependencies": {
    "lodash": "3.5.0",
    "moment": "^2.9.0",
    "moment-range": "^1.0.5",
    "pikaday": "^1.3.2",
    "react": "^0.12.2",
    "tablesort": "^3.0.2"
  },
  "devDependencies": {
    "babel-eslint": "^3.0.1",
    "browser-sync": "^2.5.2",
    "browserify": "^9.0.3",
    "del": "^1.1.1",
    "eslint": "^0.20.0",
    "eslint-plugin-react": "^2.2.0",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-concat": "2.5.2",
    "gulp-eslint": "^0.9.0",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-less": "^3.0.2",
    "gulp-plumber": "^1.0.0",
    "gulp-rename": "^1.2.0",
    "gulp-streamify": "^0.0.5",
    "gulp-uglify": "^1.1.0",
    "gulp-util": "^3.0.4",
    "karma": "^0.12.31",
    "karma-browserify": "^4.1.2",
    "karma-chrome-launcher": "^0.1.7",
    "karma-mocha": "^0.1.10",
    "karma-sinon-expect": "^0.1.4",
    "karma-spec-reporter": "0.0.18",
    "reactify": "^1.1.0",
    "require-dir": "^0.3.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^2.4.0"
  },
```

**Comment by gyandeeps** [comment]
Can you try running it like this:
```sh
./node_modules/.bin/eslint -f compact <file>
```

**Comment by ahmedelgabri** [comment]
Yeah I tried and it works. But shouldn't `eslint` works also if it finds a `.eslintrc` inside the project? without the need to run it like this `./node_modules/.bin/eslint`

**Comment by gyandeeps** [comment]
I think when you run (like you ran it using just eslint), then it ran the global installed eslint and your plugin was not installed at the global level. So it was not able to find the module.

**Comment by ahmedelgabri** [comment]
I completely understand this but if I remove the plugin from `.eslintrc` and run the global command it works with the all the rules from inside my project `.eslintrc` so I was expecting the same kind of behaviour if I'm using a plugin.

**Comment by gyandeeps** [comment]
I understand what you are saying but this thing has more to do with how native `require` works.
Just saying.

**Comment by nzakas** [comment]
You need both the plugin and ESLint to be installed in the same place. If you have ESLint installed globally, then the plugin needs to be installed globally. This is explicitly mentioned in our docs: http://eslint.org/docs/user-guide/configuring#configuring-plugins

Some editor integrations might confuse the matter, but it ultimately comes down to this.

**Comment by ahmedelgabri** [comment]
I was confused by the behaviour of ESLint without plugins cause it worked and it grabbed the rules from the project `.eslintrc` so I thought will do the same when using plugins, but now this behaviour makes sense. thanks @gyandeeps @nzakas

**Comment by carlosmmelo** [comment]
Wow nice to know! was driving me crazy until I read this and installed both globally.

Thanks.
