### ISSUE TITLE
Enhancement: Set default parser ecmaVersion to 6

### ISSUE THREAD

**Issue by mcandre** [eslint/eslint#12148]
Now that JavaScript 6 AKA ECMAScript 2015 is now widely supported across the majority of client and server JavaScript engines, let's go ahead and update the default eslint parser to accept JavaScript 6 syntax. This way, eslint "just works" with modern JS projects.

**Comment by ljharb** [comment]
"majority" isn't the important metric. If *any* supported browsers still require ES5, then those users will silently be able to ship syntax error to their users.

It's best for this to remain an explicit choice for the foreseeable future.

**Comment by ilyavolodin** [comment]
It is very hard to define "widely". There are a lot of people who use ES6 and above. But there're also a lot of people who has to maintain legacy applications. Difference is, if we set the flag to es6 by default it would cause issues that would be hard to debug for people on the older code-bases. If we keep it at 5, the errors are a lot easier to debug.

**Comment by ljharb** [comment]
If anything, I'd say a good change for eslint would be to remove the default entirely - making eslint "out of the box" error with a helpful message, telling you to explicitly configure your target environments (ideally, not specifying something arbitrary like ecmaVersion, but instead specifying browser and/or node versions, a la babel-preset-env). That way, everyone would be strictly forced to explicitly indicate what they supported, and then eslint would help enforce that.

**Comment by kaicataldo** [comment]
That's a really interesting idea. While that requires more up front knowledge from a new user, it does seem like a way to help ensure that we ESLint is never making bad assumptions. It would be more difficult for less experienced developers (the barrier for entry would now involve understanding ECMAScript versioning and how environments implement features), but this could also potentially be shored up with shared presets or some kind of equivalent to Babel's `preset-env`.
