### ISSUE TITLE
RegExp parse errors in regexpp are not tolerated and crash eslint

### ISSUE THREAD

**Issue by Jessidhia** [eslint/eslint#12169]
**Tell us about your environment**

* **ESLint Version:** 6.2.1
* **Node Version:** 12.6.0
* **npm Version:** yarn 1.17.3

**What parser (default, Babel-ESLint, etc.) are you using?**
`@typescript-eslint/parser`, but the crash is in the `regexpp` instance used by the `no-misleading-character-class` rule.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// too big to share, but this in any file should be enough
/* eslint no-misleading-character-class: 1 */
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/{/u
```

It happens on the command line as well but this is particularly bothersome with editor plugins (e.g. vscode integration), as you get plugin crash messages while typing up regexps.

**What did you expect to happen?**
No crash, at worst just an "invalid regexp" lint.

**What actually happened? Please include the actual, raw output from ESLint.**
```
[Error - 1:37:37 PM] SyntaxError: Invalid regular expression: /{/u: Lone quantifier brackets
Occurred while linting .../test.js:9
    at RegExpValidator.raise (.../node_modules/regexpp/index.js:5643:15)
    at RegExpValidator.disjunction (.../node_modules/regexpp/index.js:5747:18)
    at RegExpValidator.pattern (.../node_modules/regexpp/index.js:5681:14)
    at RegExpValidator.validatePattern (.../node_modules/regexpp/index.js:5461:14)
    at RegExpParser.parsePattern (.../node_modules/regexpp/index.js:6889:25)
    at verify (.../node_modules/eslint/lib/rules/no-misleading-character-class.js:134:40)
    at Literal[regex] (.../node_modules/eslint/lib/rules/no-misleading-character-class.js:168:17)
    at listeners.(anonymous function).forEach.listener (.../node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

To be clear, this _is_ indeed a syntax error, it's not a false positive on my input code; rather, it's an unhandled error happening inside the rule when a regexp is invalid.

**Are you willing to submit a pull request to fix this bug?**
Maybe, I don't know how this should be handled.

**Comment by platinumazure** [comment]
Hi @Jessidhia, thanks for the issue.

I think at the very least, we should wrap the regex parse in a try/catch statement and then bail out gracefully if we can.

I'm very curious to know what happens in the default parser. Seems to me this should be a parse error, even before any rules are run.

**Comment by mdjermanovic** [comment]
It is indeed parsing error in the default parser ([demo](https://eslint.org/demo#eyJ0ZXh0IjoiL3svdSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLWF0b21pYy11cGRhdGVzIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==))

I believe this is a bug in `@typescript-eslint/parser`, it shouldn't allow invalid code.

**Comment by mysticatea** [comment]
I agree that this is a problem in `@typescript-eslint/parser` for now. But once [RFC 19](https://github.com/eslint/rfcs/tree/master/designs/2019-recoverable-error-handling) was implemented, it will be a problem in that rule.

**Comment by mysticatea** [comment]
I think that ignoring syntax errors makes sense. Syntax errors are reported by parsers and the purpose of `no-misleading-character-class` rule is to report the character classes that behave unexpectedly due to multiple code unit characters.

**Comment by mdjermanovic** [comment]
The rule will also crash with the default parser on this:

```js
/*eslint no-misleading-character-class: error */

new RegExp("{", "u");
```

so this isn't just an issue with `@typescript-eslint/parser`

The other 3 rules that use `regexpp` (`no-control-regex`, `no-invalid-regexp` and  `prefer-named-capture-group`) already have try/catch.

@Jessidhia would you like to submit a PR for this fix?
