### ISSUE TITLE
Fallback to using `.gitignore` when `.eslintignore` doesn't exist

### ISSUE THREAD

**Issue by phaux** [eslint/eslint#12199]
**The version of ESLint you are using.**
6.2.2

**The problem you want to solve.**

There are a few problems with current behavior. Currently I always end up with multiple `.*ignore` files in the project root. They often have the same content too, it's usually `node_modules` and folders which contain build/coverage artifacts. Specifying `--ignore-path` doesn't help, because then the text editor won't pick it up. This is the main issue which makes this option less useful.

**Your take on the correct solution to problem.**

Take the zero-config approach and try to do the right thing implicitly.

The specific behavior would be as follows:
1. If `--ignore-path` is provided, use the file specified.
2. Else, traverse all the paths normally.
    1. If `.eslintignore` exists in current folder, use it.
    2. Else, if `.gitignore` exists in current folder, use that.

This is also what `npm` does, so people might be already familiar with this, although in `npm`'s case it indeed might count as surprising behavior, because it's usually **not** what you want.

**Are you willing to submit a pull request to implement this change?**

Maybe.

**Comment by kaicataldo** [comment]
Thanks for the proposal. Please note that we require any changes to core to go through the RFC process outlined [here](https://github.com/eslint/rfcs).

Since this is a breaking change, it would have to wait until a major version to be released. My biggest concern with the proposal is that it could cause a lot of pain in the community, since it's possible that files that were being linted before could silently stop being linted when upgrading.

**Comment by platinumazure** [comment]
I agree with @kaicataldo here. Personally, I think it would be better to enhance the editor integrations to support `--ignore-path`. That way, the user's intent is crystal clear.

**Comment by phaux** [comment]
@platinumazure editors usually support `--ingore-path` when you configure them, but they have no chance to figure this out automatically when it's only something you write in console or npm script.

**Comment by kaicataldo** [comment]
As an alternative solution, I wonder if we could add support for configuring this in config files (similar to https://github.com/eslint/rfcs/pull/22)? This would allow for consumers to easily be able to know what ignore file to use.

**Comment by mysticatea** [comment]
I don't think that the fallback makes sense because there is an important difference between `.eslintignore` and `.gitignore` -- `.gitignore` in subdirectories are valid, but `.eslintignore` in subdirectories are ignored silently.

**Comment by phaux** [comment]
> `.gitignore` in subdirectories are valid, but `.eslintignore` in subdirectories are ignored silently.

@mysticatea That's also a thing that could be changed to better align with other tools. [Relevant Prettier issue](https://github.com/prettier/prettier/issues/4081)
