### ISSUE TITLE
computed-property-spacing errors with parens

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12198]
**Tell us about your environment**

* **ESLint Version:** 6.3.0
* **Node Version:** 10.16.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2015,
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgY29tcHV0ZWQtcHJvcGVydHktc3BhY2luZzogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0qL1xuXG5jb25zdCBmb28gPSB7XG4gIFsgKGEpIF06IDFcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS1hdG9taWMtdXBkYXRlcyI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=)

```js
/*eslint computed-property-spacing: ["error", "always"]*/

const foo = {
  [ (a) ]: 1
}
```

```bash
eslint index.js --fix
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
4:5  error  A space is required after '('   computed-property-spacing
4:7  error  A space is required before ')'  computed-property-spacing
```

Fixed to:

```js
/*eslint computed-property-spacing: ["error", "always"]*/

const foo = {
  [ ( a ) ]: 1
}
```

**Are you willing to submit a pull request to fix this bug?**

Yes.

It would be also good to clarify how should the rule handle comments.

**Comment by mysticatea** [comment]
Thank you for your report.

> It would be also good to clarify how should the rule handle comments.

We have a utility function to check spaces: [sourceCode.isSpaceBetweenTokens()](https://github.com/eslint/eslint/blob/master/lib/source-code/source-code.js#L424). It intends to ignore comments on between the tokens.

**Comment by mdjermanovic** [comment]
Meant to ask, should this rule see comments as equal with other tokens regarding the spacing logic.

For example, should this be valid:

```js
/*eslint computed-property-spacing: ["error", "never"]*/

foo = {
  [/**/ a /**/]: 1
}
```

It's currently an error, because there are spaces between the brackets and the `key` node (`a`). But, there are no spaces between the brackets and the comments and I think this should be no error.

Some other spacing rules see comments as equal:

```js
/*eslint space-in-parens: ["error", "never"]*/

foo = (/**/ a /**/) // no error
```
```js
/*eslint object-curly-spacing: ["error", "never"]*/

foo = {/**/ a /**/} // no error
```

While some don't:

```js
/*eslint array-bracket-spacing: ["error", "never"]*/

foo = [/**/ a /**/] // error, autofix will delete comments
```

**Comment by mysticatea** [comment]
> It's currently an error, because there are spaces between the brackets and the key node (a). But, there are no spaces between the brackets and the comments and I think this should be no error.

Sounds good to me.

So maybe the `sourceCode.isSpaceBetweenTokens()` function is not useful because it cannot distinguish the space was placed on which side of the comment  :)

**Comment by mdjermanovic** [comment]
> So maybe the `sourceCode.isSpaceBetweenTokens()` function is not useful because it cannot distinguish the space was placed on which side of the comment :)

It could be useful, the logic can be modified to pick the first token (including comments) after `[` and first before `]`, then use  `sourceCode.isSpaceBetweenTokens()` on those tokens and brackets.

Though, it would be good to see what should be done with #11902 first.
