### ISSUE TITLE
use-isnan options for implicit Strict Equality Comparison

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12207]
**What rule do you want to change?**

`use-isnan`

This rule targets `foo === NaN` ([Strict Equality Comparison](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-strict-equality-comparison))

(also targets `!==`, `==` and `!=`)

Currently, the rule checks only `BinaryExpression` nodes, i.e. only explicit comparisons.

This is a proposal to also check the following:

* [CaseClauseIsSelected](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-runtime-semantics-caseclauseisselected) internally performs Strict Equality Comparison, so `case NaN` will never match and it's a possible error.
* [Array.prototype.indexOf](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-array.prototype.indexof) also uses Strict Equality Comparison, so `foo.indexOf(NaN)` will never match and it's a possible error. The same applies to [Array.prototype.lastIndexOf](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-array.prototype.lastindexof).

**Does this change cause the rule to produce more or fewer warnings?**

More if an option is set to `true`. Defaults are `false`.

**How will the change be implemented? (New option, new default behavior, etc.)?**

2 options, `enforceForSwitchCase` and `enforceForIndexOf`.

**Please provide some example code that this change will affect:**

```js
/*eslint use-isnan: "error"*/

switch (foo) {
    case NaN:
        bar();
        break;
}

foo.indexOf(NaN);
foo.lastIndexOf(NaN);
```

**What does the rule currently do for this code?**

Nothing.

**What will the rule do after it's changed?**

```js
/*eslint use-isnan: ["error", {"enforceForSwitchCase": true}]*/

switch (foo) {
    case NaN: // error
        bar();
        break;
}
```

```js
/*eslint use-isnan: ["error", {"enforceForIndexOf": true}]*/

foo.indexOf(NaN); // error
foo.lastIndexOf(NaN); // error
```

**Are you willing to submit a pull request to implement this change?**

Yes. (there is PR #12106 for `enforceForSwitchCase`)

**Comment by mysticatea** [comment]
Thank you for this issue.

Sounds a good idea.

**Comment by platinumazure** [comment]
I'm definitely :+1: for case clauses.

I'm less sure about `indexOf` just due to lack of strong typing, but I won't oppose that (and I acknowledge that we have precedent with other `Array.prototype` functions).

**Comment by ljharb** [comment]
it’d be better to make a custom rule forbidding indexOf in favor of includes, for that one.

**Comment by mdjermanovic** [comment]
> I'm less sure about `indexOf` just due to lack of strong typing, but I won't oppose that (and I acknowledge that we have precedent with other `Array.prototype` functions).

The initial idea was one option for both, but exactly because of this user should have a way to disable `indexOf` check. I think it's still useful in most cases, but has to be always behind an option (unlike case clauses, which could be default behavior in next major version).

**Comment by mdjermanovic** [comment]
> it’d be better to make a custom rule forbidding indexOf in favor of includes, for that one.

This can be easily done with `no-restricted-properties`. Or probably with `no-restricted-syntax` to disable just `=== -1`,  `>= 0`  etc. for which `includes` is equvalent.

**Comment by g-plane** [comment]
Off topic:
`eslint-plugin-unicorn` has a [rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-includes.md) to advise to use `Array.prototype.indexOf`.

**Comment by mdjermanovic** [comment]
I'm working on this (indexOf).
