### ISSUE TITLE
Eslint needs to update eslint-utils to patched version

### ISSUE THREAD

**Issue by michdsouza** [eslint/eslint#12204]
**Tell us about your environment**

* **ESLint Version:** 5.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**What did you expect to happen?**
Expect eslint to use patched version of eslint-utils

**What actually happened?**

| critical      | Arbitrary Code Execution                                     |   
|---------------|--------------------------------------------------------------|
| Package       | eslint-utils                                                 |
| Patched in    | >=1.4.1                                                      |
| Dependency of | eslintr                                                      |
| Path          | eslint > eslint-utils                                        |
| More info     | https://www.npmjs.com/advisories/1118                        |

**Are you willing to submit a pull request to fix this bug?**
Yes, if I know how.

**Comment by mysticatea** [comment]
Thank you for your report.

But your ESLint is too old. Please use the latest version.

**Comment by michdsouza** [comment]
Thank you for you response! I didn't realize my version was so far behind. This has been resolved for me :)
