### ISSUE TITLE
Combine multiple files

### ISSUE THREAD

**Issue by dkarpeSS** [eslint/eslint#12215]
Hello, I'd like to ask how can I resolve this issue: I have two files(file1,file2), I'm calling from file1 function from file2, without import, etc.Also with variables. Can you please help what rule do I need to use? Something like combining all files to one.

**Comment by dkarpeSS** [comment]
rules:[
"no-unused-vars":[
            "error",
            {
                "vars": "all",
                "args": "after-used",
                "ignoreRestSiblings": false 
            }
        ],
        "no-undef": "error"]
-----------------------------------------
file1.js :
function fileOne(){
 new fileTwo().innerFunction();
};
------------------------------
file2.js:
function fileTwo(){
this.innerFunction(){}
}
-------------------------
Error:
fileTwo is not defined. eslint (no-undef)

**Comment by mysticatea** [comment]
Hi. Thank you for your question.

ESLint verifies each file individually. There are some directive comments to tell ESLint about the existence of other files.

- `/* globals foo */` ... There are global variable `foo` that another file defined.
- `/* exported foo */` ... Global variable `foo` that this file defined is used in other files.

For example:

**file1.js:**

```js
/* globals fileTwo */
/* exported fileOne */

function fileOne(){
    new fileTwo().innerFunction();
}
```

**file2.js:**

```js
/* globals fileOne */
/* exported fileTwo */

function fileTwo(){
    new fileOne().innerFunction();
}
```

**Comment by kaicataldo** [comment]
Closing this as it looks like the question has been answered.
