### ISSUE TITLE
Add semi option to strengthen beforeStatementContinuationChars

### ISSUE THREAD

**Issue by christianbundy** [eslint/eslint#12228]
**What rule do you want to change?**

[semi](https://eslint.org/docs/rules/semi#options)

**Does this change cause the rule to produce more or fewer warnings?**

More.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option that disables the exception for `{ "beforeStatementContinuationChars": "never" }` that currently allows semicolons before statement continuation characters. Currently "never" implements behavior that I'd describe as "never, if it doesn’t make ASI hazard", whereas I'd really like to use "never" in general.

Maybe something like "allow ASI hazard" or something? The default might be `{ "allowAsiHazard": true }` and the behavior I'm looking for would be `{ "allowAsiHazard": false }` or similar. I'm very open to suggestions on how to best implement this.

**Please provide some example code that this change will affect:**

```js
/*eslint semi: ["error", "never", { "beforeStatementContinuationChars": "never"}] */

console.log(42)
;(function() {
    // ...
})()
```

**What does the rule currently do for this code?**

No errors detected.

**What will the rule do after it's changed?**

Detect the error caused by the semicolon before the statement continuation characters.

**Are you willing to submit a pull request to implement this change?**

Yes.

---

Backlink: https://github.com/standard/standard/issues/1402

**Comment by christianbundy** [comment]
FWIW, here's a diff that gives the behavior that I'm looking for:

```diff
diff --git a/lib/rules/semi.js b/lib/rules/semi.js
index a159e19d..39136c27 100644
--- a/lib/rules/semi.js
+++ b/lib/rules/semi.js
@@ -228,7 +228,7 @@ module.exports = {
             if (isOnSameLineWithNextToken(node)) {
                 return false; // One liner.
             }
-            if (beforeStatementContinuationChars === "never" && !maybeAsiHazardAfter(node)) {
+            if (beforeStatementContinuationChars === "never") {
                 return true; // ASI works. This statement doesn't connect to the next.
             }
             if (!maybeAsiHazardBefore(sourceCode.getTokenAfter(node))) {
```

Assuming that the current behavior is desired, I'd love to add an option that disables the `maybeAsiHazardAfter()` check.

**Comment by mysticatea** [comment]
Thank you for your proposal.

But I don't think that this is a job of `semi` rule because removing such a semicolon will break code. In other words, it's not extra semicolons. To autofix that changes semantics is not acceptable at least. So I think that it would be good if it's a separated rule.

About adding the rule into core, I don't have strong opinions.

**Comment by platinumazure** [comment]
I don't understand. What would be the "correct" way of writing code in your example?

Note that this code is semantically different:

```js
console.log(42)
(function() {     // WARNING: Double function call!
    // ...
})()
```

**Comment by mysticatea** [comment]
@platinumazure From the original issue (https://github.com/standard/standard/issues/1402), I guess that it intends to disallow IIFE in that case. Instead, separate it to a declaration and a call expression. Therefore, the new rule will enforce to separate hazardable statements to a declaration and an expression instead of inserting the workaround semicolons.

**Comment by christianbundy** [comment]
> To autofix that changes semantics is not acceptable at least. So I think that it would be good if it's a separated rule.

Yes, you're absolutely right. Sorry I hadn't considered that this was still getting run with `--fix`. I'd be happy to add this as its own rule, do you have any suggestions on what it should be called? I don't want to stray from the usual naming scheme, but I haven't contributed very often to ESLint.

> Therefore, the new rule will enforce to separate hazardable statements to a declaration and an expression instead of inserting the workaround semicolons.

Yep, exactly. I'm currently using [`no-unexpected-multiline`](https://eslint.org/docs/rules/no-unexpected-multiline) to ensure that there aren't any problems. If that rule finds a problem, I'd like for ESLint to guide me toward solutions other than "throw in a semicolon". 

> I don't understand. What would be the "correct" way of writing code in your example?

I think both of these would be fine:

```javascript
console.log(42)
const f = function () {
    // ...
}
f()
```

```javascript
console.log(42)

{
    // Use `let` or `const` to emulate IIFE scope
    // ...
}
```

**Comment by platinumazure** [comment]
I definitely think it is unexpected/not ideal for "beforeStatementContinuationChars": "never" to sometimes allow a semicolon anyway. I don't know if we can safely autofix those cases, but I'm okay with reporting them with no fix.

I would want to look at the rule history and make sure this behavior wasn't intentional before accepting this as a bug fix. Otherwise, this should be a breaking change.

**Comment by christianbundy** [comment]
I think this behavior was intentional, but I'd be interested in fixing it if we can reach consensus that the current `"never"` behavior isn't what we want: #9594

**Comment by platinumazure** [comment]
In my quick reading of #9594 (thanks for the link!), this does sound like a bug to me.

@mysticatea Do you agree this could be a bug? At the very least, the semi rule isn't reporting what it should. (There is no requirement for us to autofix always, or to autofix in all cases when the rule autofixes in a single case. We can have cases that don't fix.)

**Comment by mysticatea** [comment]
No, the current behavior is intentional.

The `"never"` option reports *extra* semicolons because to prevent *extra* semicolons is the purpose of `semi` rule with `never` option. The rule doesn't consider the semicolons as *extra* if those protect code from ASI Hazard because it will change semantics if we delete the semicolons.

As #9594 said, the `beforeStatementContinuationChars` option considers the semicolons which satisfy the following conditions as *extra*:

> - The semicolon (or lacking semicolon) is followed by the tokens which can make ASI hazard (`[`, `(`, `+`, `-`, or `` ` ``).
> - But the semicolon (or lacking semicolon) does not make ASI hazard because the next token does not connect to the previous statement.

**Comment by platinumazure** [comment]
@mysticatea I'm sorry, but I'm still not understanding. Could you please provide an example? When should `"beforeStatementContinuationChars": "never"` report, and when shouldn't it report?

**Comment by mysticatea** [comment]
Sure.

```js
//------------------------------------------------------------------------------
// The rule doesn't report semicolons if it will change semantics after removed.
let foo = bar
;[1, 2, 3].map(f) // This semi has protected code from ASI Hazard.

//------------------------------------------------------------------------------
// The rule does report semicolons if it will not change semantics after removed.
import "module"
;[1, 2, 3].map(f) // This semi is extra.

do { /*do something*/ } while (condition)
;[1, 2, 3].map(f) // This semi is extra.
```

**Comment by mysticatea** [comment]
At the start point, the old `semi` rule with `"never"` option *ignores* the latter cases regardless of the existence of semicolons. Therefore, `beforeStatementContinuationChars` has introduced to enforce a consistent style for the latter cases.

**any:** (this is the previous behavior as-is)

```js
/*eslint semi: [error, never] */

// No errors regardless of semicolons
import "module"
;[1, 2, 3].map(f)
import "module"
[1, 2, 3].map(f)

do { /*...*/ } while (condition)
;[1, 2, 3].map(f)
do { /*...*/ } while (condition)
[1, 2, 3].map(f)

function f() { /*...*/ }
[1, 2, 3].map(f)
function f() { /*...*/ }
;[1, 2, 3].map(f)
```

**always:**

```js
/*eslint semi: [error, never, { beforeStatementContinuationChars: always }] */
import "module"
[1, 2, 3].map(f) // Missing semicolon.

do { /*...*/ } while (condition)
[1, 2, 3].map(f) // Missing semicolon.

function f() { /*...*/ }
[1, 2, 3].map(f) // Missing semicolon.
```

**never:**

```js
/*eslint semi: [error, never, { beforeStatementContinuationChars: never }] */
import "module"
;[1, 2, 3].map(f) // Extra semicolon.

do { /*...*/ } while (condition)
;[1, 2, 3].map(f) // Extra semicolon.

function f() { /*...*/ }
;[1, 2, 3].map(f) // Extra semicolon.
```

**Comment by mysticatea** [comment]
Anyway, the `semi` rule should address only the semicolons which don't have any effect on semantics.

**Comment by mightyiam** [comment]
Thank you for the examples, @mysticatea. If the purpose is to have a set of rules that prohibits any statement-separating semicolons (as opposed to `for` semicolons, for example), should it be a change to the `semi` rule or a new rule or what, please?

**Comment by mysticatea** [comment]
As I said in https://github.com/eslint/eslint/issues/12228#issuecomment-528652769, I prefer a new rule. It would be `no-workaround-semi` or something like.

**Comment by platinumazure** [comment]
I really don't see why `semi` couldn't be enhanced for this case.

Part of my difficulty with this is, I see `semi` as a rule primarily about semicolon tokens, but it seems @mysticatea (and maybe others) see this as a rule about the end of statements. So, because I see this as a rule about semicolon tokens, the current behavior of `"beforeStatementContinuationChars": "never"` is *utterly incomprehensible* to me. I don't see any value in distinguishing between whether the semicolon is part of the previous statement (i.e., is necessary for ASI) vs if the semicolon represents an empty statement, for the purposes of the `semi` rule. I can't imagine many of our users would be keeping track at that level of detail.

I would much rather add a new option value to `semi`'s `"beforeStatementContinuationChars"` and have "never" actually mean *never*-- no semicolons allowed at that location. If we need to add a new option representing the current behavior (no semicolons allowed, but only if the semicolon is unnecessary for ASI purposes), I would much rather do that in this rule (e.g., `"beforeStatementContinuationChars": "warnIfUnnecessarySemi"` or similar). If all of this needs to be done in 7.0.0 due to breaking changes, of course I would be okay with that.

**Comment by mysticatea** [comment]
@platinumazure Sorry, your thought that `semi` rule handles all semicolon tokens is definitely wrong. The `semi` rule handles only the semicolons which (1) separate two statements and (2) doesn't change semantics. 
1. The semicolons which don't separate statements are handled by `no-extra-semi` rule in fact. We have discussed to merge `semi` and `no-extra-semi` in the past, but it has been rejected.
1. If `semi` rule handled the semicolons which change semantics, it's clearly a bug. At least we have fixed those as bugs in the past. The reason that the rule doesn't handle the semicolon in `foo()\n;[]` is the completely same as the reason that the rule doesn't handle the semicolon in `foo(); bar()` one-liner. The semicolon is necessary to keep semantics. It's very clear.

**Comment by christianbundy** [comment]
I'm sure everyone in this thread already knows this, but I wanted to make a note because I hadn't seen it mentioned: there's another exception made for semicolons in `for` statements, which makes sense because those semicolons are a mandatory part of the `for` statement syntax I think we're all on the same page that those semicolons should *not* trigger a report. 

```javascript
for (var i = 0; i < 42; i += 1) {
  //          ^       ^
}
```

I think it's reasonable for the `semi` rule to have an option to say "I don't want any semicolons, except in `for` loops", but clearly these should not be auto-fixed unless they're unnecessary.

**Comment by mysticatea** [comment]
@christianbundy To prevent one-liner, there is `max-statements-per-line` rule already. I think that the lacking parts are only the `no-workaround-semi`-like rule as a family of `no-unexpected-multiline` rule.

**Comment by christianbundy** [comment]
@mysticatea Do you think there would be utility in supporting [both use-cases](https://github.com/eslint/eslint/pull/12240#issuecomment-529250523)? I think there are two distinct camps that would use this rule:

```javascript
// common style for ASI users
// always protect statement with semicolon
;[1, 2, 3].reverse()

// common style for both ASI and semicolon users
// never use semicolon workaround
const nums = [1, 2, 3]
nums.reverse()
```

I'd be happy to implement this in a new rule and combine with `max-statements-per-line` if that's the consensus on the best way to implement this, but I'd love to support both use-cases.

**Comment by christianbundy** [comment]
Also, I'm unsure whether `max-statements-per-line` does what we're discussing, since it also reports semicolon-free code like:

```javascript
if (err) { console.log('foo') } else { console.log('bar') }
```

**Comment by mysticatea** [comment]
"always protect statement with semicolon" has been supported already by `semi` rule with `["never", { beforeStatementContinuationChars: "always" }]`. We don't like the overlap of rules.

**Comment by christianbundy** [comment]
I understand wanting to avoid overlap, thanks for helping orient me through these rules. Here's my current understanding:

- The `semi` option only removes unnecessary semicolons, not semicolons *in general*.
  - The `beforeStatementContinuationChars` option can be used to enforce semicolon workarounds, but can't be used to disallow semicolon workarounds.
- The `max-statements-per-line` rule disallows semicolon-delimited on the same line, but also disallows lots of other common uses.
- Your preference would be to write a new `no-workaround-semi` rule that disallows semicolons before statement continuation characters that the `semi` option ignores.

I don't think `max-statements-per-line` is a viable solution to disable semicolons because it aggressively reports all sorts of other common patterns. Are there any other options you think might work? I strongly agree that any rule warning for necessary semicolons shouldn't auto-fix, but it seems intuitive for me that disallowing semicolons is handled by `semi`.

**Comment by mysticatea** [comment]
Maybe `semi: ["error", "true-never"]` ?

But I'm not sure if it's common style enough to add into ESLint core.

**Comment by mightyiam** [comment]
Just wanna drop by and say good work guys. Keep it up. I would love to see this happening.
