### ISSUE TITLE
Make `max-lines-per-function` play nice with jsx

### ISSUE THREAD

**Issue by amio** [eslint/eslint#12236]
**What rule do you want to change?**

`max-lines-per-function`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option: `skipJSX` (default `false`)

**Please provide some example code that this change will affect:**

```js
/*eslint max-lines-per-function: ["error", {"max": 2, "skipJSX": true}]*/
function Foo () {
  return (
    <div>some long long jsx codes</div>
  )
}

```

**What does the rule currently do for this code?**
Throw error

**What will the rule do after it's changed?**
Play nice with big jsx template which is common and reasonable use case.

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by platinumazure** [comment]
Hi @amio, thanks for the issue.

I'm not sure we need to code a new option for this case. This sort of thing is exactly what ESLint disable comments are for.

```js
/* eslint-disable max-lines-per-function */
function Foo () {
  return (
    <div>some long long jsx codes</div>
  )
}
/* eslint-enable max-lines-per-function */
```

**Comment by amio** [comment]
Thanks @platinumazure , I think disable comments is a patch for it. Since it's a very common use case for project using jsx, we might need an option like `skipComments` or `skipBlankLines` to handle it regularly.

For an react component, a `render` function often containing jsx more than 120 lines, and it's reasonably, while for a regular js function, it would be too loose to set the bar over 60.

It's the blocking issue for our project to adapt this rule, we need exception for jsx, and it's too common to force developers use `/* eslint-disable max-lines-per-function */` every time.

**Comment by platinumazure** [comment]
Is it possible to use configuration overrides to only allow 120-line functions in files that tend to have large JSX templates, such as React components?

For example, if all your JSX functions are in `src/components`, a config could look like this:

```json
{
    "rules": {
        "max-lines-per-function": ["error", { code: 60 }]
    },
    "overrides": [
        {
            "files": ["src/components/**"],
            "rules": {
                "max-lines-per-function": ["error", { code: 120 }]
            }
        }
    ]
}
```

If that's not feasible, then I wonder if we could instead create a more generic exception (e.g., specify a node type such as JSXElement and then all lines in nodes of that type don't count toward the line limit). I don't want to keep adding exceptions for different cases like comments, strings, templates, and JSX when we could just add something that anyone could use in the future.

**Comment by amio** [comment]
That's feasible and good enough, thanks @platinumazure!
