### ISSUE TITLE
space-before-function-paren removes comments when fixing

### ISSUE THREAD

**Issue by zaygraveyard** [eslint/eslint#12259]
**Tell us about your environment**

* **ESLint Version:** v6.3.0
* **Node Version:** NA (using https://eslint.org/demo)
* **npm Version:** NA (using https://eslint.org/demo)

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 10,
        "sourceType": "module",
        "ecmaFeatures": {}
    },
    "rules": {
        "space-before-function-paren": ["error", "never"]
    },
    "env": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Tried to fix the following code

```js
function delay /*:: <T>*/() {}
```

https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgc3BhY2UtYmVmb3JlLWZ1bmN0aW9uLXBhcmVuOiBbJ2Vycm9yJywgJ25ldmVyJ10qL1xuZnVuY3Rpb24gZGVsYXkgLyo6OiA8VD4qLygpIHt9Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==

**What did you expect to happen?**
The space after `delay` to be removed while preserving the comment.

**What actually happened? Please include the actual, raw output from ESLint.**
The space and the comment after `delay` got removed.

**Are you willing to submit a pull request to fix this bug?**
No

**Cause**
https://github.com/eslint/eslint/blob/460c5ad176eaf39ff579cd96b3bcbe0539093f8f/lib/rules/space-before-function-paren.js#L127
The fixing is done by removing everything between the identifier and the opening parenthesis (without taking comments into consideration)

**Comment by mdjermanovic** [comment]
Hi @zaygraveyard, thanks for the report! I can reproduce this bug.

**Comment by mdjermanovic** [comment]
Perhaps we could implement here the logic from `template-tag-spacing`?

[Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgdGVtcGxhdGUtdGFnLXNwYWNpbmc6IFtcImVycm9yXCIsIFwibmV2ZXJcIl0qL1xuXG5mb28gLyogYmxvY2sgY29tbWVudCAqL2BgO1xuXG5mb28gLypjb21tZW50IDEqL1xuLypjb21tZW50IDIqL2BgO1xuXG5mb28gLy8gbGluZSBjb21tZW50IFxuYGA7XG5cblxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

It concatenates all block comments. If there is a line comment, just reports without the autofix.

**Comment by zaygraveyard** [comment]
@mdjermanovic yes, this would indeed fix this issue since it would preserve the comments
