### ISSUE TITLE
`Failed to load plugin` when extends a shared config

### ISSUE THREAD

**Issue by uni-zheng** [eslint/eslint#12257]
**Tell us about your environment**

* **ESLint Version: 6.3.0**
* **Node Version: 10.14.2**
* **npm Version: 6.4.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
none

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: [
    '@foo/eslint-config-a',
  ],
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// test.js
const a = 1;
```

```bash
./node_modules/.bin/eslint test.js
```

**What did you expect to happen?**
work

**What actually happened? Please include the actual, raw output from ESLint.**
```
Oops! Something went wrong! :(

ESLint: 6.3.0.

ESLint couldn't find the plugin "@foo/eslint-plugin-b".

(The package "@foo/eslint-plugin-b" was not found when loaded as a Node module from the directory "/Users/zhengxiang/Documents/Project/Zeyi/test/packages/project-c".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @foo/eslint-plugin-b@latest --save-dev

The plugin "@foo/eslint-plugin-b" was referenced from the config file in ".eslintrc.js » @foo/eslint-config-a".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

```

**Are you willing to submit a pull request to fix this bug?**
sorry, its hard to me

=======

Hi, thanks to provide this tool. It's very helpful for development.

I used Lerna the multiple packages managing tools to built three packages:
* @foo/eslint-config-a
* @foo/eslint-plugin-b
* @foo/project-c

<img width="315" alt="image" src="https://user-images.githubusercontent.com/9986421/64685374-78121500-d4b9-11e9-99f3-0f7ece7d80fe.png">

### @foo/eslint-plugin-b
This package created by generator-eslint.

### @foo/eslint-config-a
This package has a dependence `eslint-plugin-b`, and output a shareable config.
```js
module.exports = {
  plugins: [
    '@foo/eslint-plugin-b'
  ]
};
```

### @foo/project-c
This package has those dependences:
* eslint
* @foo/eslint-config-a

And has a config file and be tested file
```js
// .eslintrc.js
module.exports = {
  extends: [
    '@foo/eslint-config-a',
  ],
};
```

```js
// test.js
const a = 1;
```

When check `test.js` file the program would throw the error:
```
ESLint couldn't find the plugin "@foo/eslint-plugin-b"
```

In `project-c` folder, It's has correct directories.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/9986421/64686086-aba16f00-d4ba-11e9-9825-079a3960a75c.png">

But `ESLint` still throw error.

I provide a case for this issue  https://github.com/uni-zheng/eslint-issue-case

If you have any confusion please let me know and forgive me for my terrible English.
Thinks.

**Comment by FrancoMeriles** [comment]
did you resolve this ?

**Comment by uni-zheng** [comment]
@FrancoMeriles 

Sorry, I forget why I closed it.

This problem is still exist.

I will re-open this issue and maybe someone can share answer

**Comment by kaicataldo** [comment]
I'm not terribly familiar with Lerna, but I think the issue here might be Lerna's bootstrap command isn't flattening `node_modules`. I would expect `node_modules` to look like:

```
- project c
    - node_modules
        - @foo 
            - eslint-config-a
            - eslint-plugin-b
```

In ESLint v6, we changed the config and plugin resolution algorithm to load plugins relative to the project it is used in (you can find more information [here](https://eslint.org/docs/user-guide/migrating-to-6.0.0#plugins-and-shareable-configs-are-no-longer-affected-by-eslints)), and since `@foo/eslint-plugin-b` is nested in `@foo/eslint-config-a/node_modules`, it's unable to resolve the plugin.
