### ISSUE TITLE
function-paren-newline error when there's a multiline comment before first argument or after last

### ISSUE THREAD

**Issue by zaygraveyard** [eslint/eslint#12251]
**Tell us about your environment**

* **ESLint Version:** v6.3.0
* **Node Version:** NA (using https://eslint.org/demo)
* **npm Version:** NA (using https://eslint.org/demo)

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 10,
        "sourceType": "module",
        "ecmaFeatures": {}
    },
    "rules": {
        "function-paren-newline": 2
    },
    "env": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function RelativeLink({
  a,
  b
} /*: {
  +a: string,
  +b: string,
} */) {
  return a + b;
}

RelativeLink('a', 'b')
```

https://eslint.org/demo#eyJ0ZXh0IjoiZnVuY3Rpb24gUmVsYXRpdmVMaW5rKHtcbiAgYSxcbiAgYlxufSAvKjoge1xuICArYTogc3RyaW5nLFxuICArYjogc3RyaW5nLFxufSAqLykge1xuICByZXR1cm4gYSArIGI7XG59XG5cblJlbGF0aXZlTGluaygnYScsICdiJykiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEwLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImZ1bmN0aW9uLXBhcmVuLW5ld2xpbmUiOjJ9LCJlbnYiOnt9fX0=

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
7:5 - Unexpected newline before ')'. (function-paren-newline)
```

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by kaicataldo** [comment]
I agree that this looks like a bug. I think if a multiline comment begins on the same line as an argument and starts/ends on the same line as the opening/closing parenthesis, I don't think it should be considered whitespace.

**Comment by kaicataldo** [comment]
Reopening this so we can evaluate if this is a bug or not.

**Comment by yeonjuan** [comment]
If this is a bug, Is this case a bug too? - [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktYnJhY2tldC1uZXdsaW5lOiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cblxudmFyIGEgPSBbIDEsXG4yLyoqXG4qXG4qL107XG5cbnZhciBhID0gWyAxLFxuMl07XG5cblxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJmdW5jdGlvbi1wYXJlbi1uZXdsaW5lIjoyfSwiZW52Ijp7fX19)
```js
/*eslint array-bracket-newline: ["error", "never"]*/

var a = [ 1,
2/**
*
*/]; // Error - There sould be no line ... 

var a = [ 1,
2];
```

**Comment by arminyahya** [comment]
Can these lines have `{ includeComments: true}` ?

https://github.com/eslint/eslint/blob/4cab165bf4e6e5e9f42a59a37a8ff2548c0af87d/lib/rules/function-paren-newline.js#L109
https://github.com/eslint/eslint/blob/4cab165bf4e6e5e9f42a59a37a8ff2548c0af87d/lib/rules/function-paren-newline.js#L110

**Comment by t-mangoe** [comment]
> Can these lines have `{ includeComments: true}` ?
> 
> https://github.com/eslint/eslint/blob/4cab165bf4e6e5e9f42a59a37a8ff2548c0af87d/lib/rules/function-paren-newline.js#L109
> 
> 
> https://github.com/eslint/eslint/blob/4cab165bf4e6e5e9f42a59a37a8ff2548c0af87d/lib/rules/function-paren-newline.js#L110

I added `{ includeComments: true}` to these two lines, and checked the result.
As a result, the reported error message is not printed. However, in other cases, an unexpected error is printed.
As shown below, if there is a comment after an opening parenthesis, `13:15  error  Expected newline after '('  function-paren-newline` is printed.
```js
function RelativeLink({
    a,
    b
} /*: {
    +a: string,
    +b: string,
} */) {
    return a + b;
}

RelativeLink('a', 'b')

RelativeLink( // any comment  <- Here, error is output.
    'a',
    'b'
);
```
For example, such comments exist in the `no-nonoctal-decimal-escape`rule.
https://github.com/eslint/eslint/blob/c981fb1994cd04914042ced1980aa86b68ba7be9/lib/rules/no-nonoctal-decimal-escape.js#L101-L112

**Comment by arminyahya** [comment]
I'm working on it right now.

**Comment by sam3k** [comment]
Looks like there was an attempt to submit a fix but was abandoned. Should this issue remain opened?

**Comment by mdjermanovic** [comment]
Closing as this rule has been deprecated per https://github.com/eslint/eslint/issues/17522
