### ISSUE TITLE
`no-restricted-imports`: disable comments do not work for individual named imports

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/eslint#12282]
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** 10.16.3
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  rules: {
    'no-restricted-imports': [
      'error',
      {
        name: 'lodash',
        importNames: ['zip'],
      },
    ],
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import {
  zip, // eslint-disable-line no-restricted-imports
  pickBy,
} from 'lodash';
```

```bash
eslint
```

**What did you expect to happen?**
No error

**What actually happened? Please include the actual, raw output from ESLint.**
Error

```
'lodash' import is restricted from being used.
```

To workaround this you must disable the rule for the whole import statement. However this is not ideal because this could accidentally silence errors that we want to hear about, for other named imports:

```js
// eslint-disable-next-line no-restricted-imports
import {
  zip,
  pickBy,
} from 'lodash';
```

**Are you willing to submit a pull request to fix this bug?**

**Comment by g-plane** [comment]
I can reproduce this bug at our [ESLint Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgJ25vLXJlc3RyaWN0ZWQtaW1wb3J0cyc6IFtcbiAgICAgICdlcnJvcicsXG4gICAgICB7XG4gICAgICAgIG5hbWU6ICdsb2Rhc2gnLFxuICAgICAgICBpbXBvcnROYW1lczogWyd6aXAnXSxcbiAgICAgIH0sXG4gICAgXSAqL1xuXG5pbXBvcnQge1xuICB6aXAsIC8vIGVzbGludC1kaXNhYmxlLWxpbmUgbm8tcmVzdHJpY3RlZC1pbXBvcnRzXG4gIHBpY2tCeSxcbn0gZnJvbSAnbG9kYXNoJzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEwLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).

I think the rule should only report the restricted items. For the example from @OliverJAsh , the rule should report `zip` only.

**Comment by eclectrony** [comment]
Just so that I understand this rule more clearly:

If we _didn't_ have the eslint-disable-line comment, should "pickBy" still be allowed to be imported even as "zip" is disallowed, or should "import { zip, pickBy, } from 'lodash';" be disallowed entirely because of the presence of "zip" in the import statement?

**Comment by OliverJAsh** [comment]
The former

**Comment by mdjermanovic** [comment]
It seems that reporting zip identifier node instead of the whole import statement would fix this issue. Would be probably nice to have a different error message in this case.

This change also means that the rule can now report multiple errors for the same import statement.

**Comment by fanich37** [comment]
I'm gonna check it and send a PR till New Year.
