### ISSUE TITLE
Add documentation explaining config merging behavior

### ISSUE THREAD

**Issue by galvarez421** [eslint/eslint#12295]
**The version of ESLint you are using.**
6.3.0

**The problem you want to solve.**
The config merging behavior is not obvious and is hard to discern without looking at the code.

**Your take on the correct solution to problem.**
Following up on https://groups.google.com/forum/#!topic/eslint/XJn64b-RouI, I think it would be helpful for the documentation website to document exactly how configs are merged. There is already some good documentation about how rules are merged in https://eslint.org/docs/user-guide/configuring#extending-configuration-files. I think additional documentation for other parts of the config (`settings`, `parserOptions`, etc.) would also be helpful, especially since the merging behavior appears to be different for different parts of the config (https://github.com/eslint/eslint/blob/v6.4.0/lib/cli-engine/config-array/config-array.js#L238-L273).

**Are you willing to submit a pull request to implement this change?**
Possibly, if the issue is considered valid.

**Comment by kaicataldo** [comment]
PRs to improve documentation are always welcome!
