### ISSUE TITLE
[multiline-comment-style] autofix removes indentation in the comment

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#12312]
**Tell us about your environment**

* **ESLint Version:** 6.4.0
* **Node Version:** 12.10.0
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**

Default.

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbXVsdGlsaW5lLWNvbW1lbnQtc3R5bGU6IFtlcnJvcl0gKi9cblxuLypcbntcbiAgICBcImZvb1wiOiAxLFxuICAgIFwiYmFyXCI6IDJcbn1cbiovXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=).

```js
/*eslint multiline-comment-style: [error] */

/*
{
    "foo": 1,
    "bar": 2
}
*/
```

**What did you expect to happen?**

ESLint fixes it to:

```js
/*eslint multiline-comment-style: [error] */

/*
 * {
 *     "foo": 1,
 *     "bar": 2
 * }
 */
```

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint fixed it to:

```js
/*eslint multiline-comment-style: [error] */

/*
 * {
 * "foo": 1,
 * "bar": 2
 * }
 */
```

The indentation in the comment is broken.

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by kaicataldo** [comment]
Verified and agree that this looks like a bug.
