### ISSUE TITLE
False "indent" positive with TypeScript generics

### ISSUE THREAD

**Issue by MidnightDesign** [eslint/eslint#12318]
**Tell us about your environment**

* **ESLint Version:** 6.4.0
* **Node Version:** 10.16.3
* **npm Version:** Yarn 1.17.3

**What parser (default, Babel-ESLint, etc.) are you using?**
`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:react/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "react/prop-types": 0,
        "@typescript-eslint/no-unused-vars": 1,
        "react/display-name": 0
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```typescript
const foo = <T extends string>(
    str: T
) => (
    `${str} foo`
);

foo('x');
```

```bash
./node_modules/.bin/eslint test.ts
```

**What did you expect to happen?**
No ESLint errors.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

/home/[...]/test.ts
  4:1  error  Expected indentation of 8 spaces but found 4  indent
  5:1  error  Expected indentation of 4 spaces but found 0  indent

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Are you willing to submit a pull request to fix this bug?**
No, I don't know the codebase at all.

Note: This seems to be related to TypeScript generics because the error goes away if you remove the generic type. There are also no problems if the argument isn't on a separate line.

**Comment by kaicataldo** [comment]
Hi, the `indent` rule doesn't know about TypeScript-specific syntax. You'll want to use `@typescript-eslint/indent` from [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) instead.

**Comment by MidnightDesign** [comment]
Thank you so much, I didn't think about that. For anyone stumbling upon this in the future:
```json
"rules": {
    "indent": "off",
    "@typescript-eslint/indent": [
        "error",
        4
    ]
}
```
...or whatever settings you want to use.
