### ISSUE TITLE
Template string crashes eslint

### ISSUE THREAD

**Issue by brunottonurb** [eslint/eslint#12341]
**Tell us about your environment**
Ubuntu 18.04, vscode 1.38.1

* **ESLint Version:**
1.9.1
* **Node Version:**
v10.14.1
* **npm Version:**
6.10.2

**What parser (default, Babel-ESLint, etc.) are you using?**
default (?)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "airbnb",
    "parser": "babel-eslint",
    "env": {
      "browser": true,
      "jest": true
    },
    "rules": {
        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
        "react/no-array-index-key": false,
        "import/prefer-default-export": false
      }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

The following line crashes eslint
```js
const onError = error => ({ output: `Backend Error (${error})` });
```

Using vscode to automatically check linting, the following creates the same issue:
```bash
eslint src/
```

**What did you expect to happen?**
eslint not crashing

**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'range' of null
[...]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! client@0.0.1 lint: `eslint src/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the client@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
[...]
```

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by kaicataldo** [comment]
@brunottonurb Sorry for the lack of response - this appears to have fallen through the cracks. You're using an extremely old version of ESLint. Can you confirm if this is an issue with the latest version or not?

@sdemjanenko Please make a new issue.

**Comment by sdemjanenko** [comment]
I found that running a dedupe in yarn fixes this for me. Shout-out to: https://github.com/babel/babel-eslint/issues/681#issuecomment-516893539
