### ISSUE TITLE
Clarification on behavior of dot directories

### ISSUE THREAD

**Issue by brandonchinn178** [eslint/eslint#12348]
**Tell us about your environment**

* **ESLint Version:** v6.3.0
* **Node Version:** v12.8.1
* **yarn Version:** 1.17.3

**What parser (default, Babel-ESLint, etc.) are you using?**

`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "simple-import-sort", "prettier"],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "indent": ["error", 2],
    "react/display-name": "off",
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "off",
    "simple-import-sort/sort": "error",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/member-delimiter-style": "off",
    "@typescript-eslint/no-unused-vars": ["error", {
      "argsIgnorePattern": "^_$"
    }]
  },
  "globals": {
    "React": "writable"
  },
  "settings": {
    "react": {
        "version": "detect"
    }
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

**What actually happened? Please include the actual, raw output from ESLint.**

```
$ yarn eslint client/.storybook/config.js 

.../client/.storybook/config.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```
**What did you expect to happen?**

`client/.storybook/config.js` should be linted

**Are you willing to submit a pull request to fix this bug?**

Sure?

## More details

I see this comment: https://github.com/eslint/eslint/issues/4828#issuecomment-194535273

> Thanks. So this looks like a bug, we should be linting anything passed on the command line. We should fix that.

But it seems like that's not the case, from this test suite: https://github.com/eslint/eslint/blob/22046939a7f250e6cce40a2acdfd3581a2ce29f5/tests/lib/cli-engine.js#L355-L375

The documentation doesn't seem very helpful. Searching for "dot files" doesn't help me, and [the section on `.eslintignore`](https://eslint.org/docs/user-guide/configuring#eslintignore) only mentions:

> Lines preceded by ! are negated patterns that re-include a pattern that was ignored by an earlier pattern.

Even though I'm not ignoring anything. It's also weird that the message says `File ignored because of a matching ignore pattern` because I don't have a `.eslintignore` file in my project.

The weird part is that `yarn eslint client/.storybook/` works. Can we get some clarification on this issue (and the expected behavior) in the docs and/or in the CLI?

Issues that I've already looked at:
* https://github.com/eslint/eslint/issues/5623
* https://github.com/eslint/eslint/issues/10341
* https://github.com/eslint/eslint/issues/4828
* https://github.com/eslint/tsc-meetings/blob/430455a12366c4614f322734b38521ef12870251/notes/2018/2018-08-02.md#do-not-ignore-files-started-with--by-default
* https://github.com/eslint/eslint/issues/10597

**Comment by mysticatea** [comment]
Thank you for your report.

Indeed, documentation is not enough.

The logic to ignore files has quirks for historical reason. I don't know the reason, but I found some quirks while I implemented https://github.com/eslint/eslint/pull/12274. The following list is it.

- ESLint ignores `/node_modules/*`, `/bower_components/*`, and dotfiles by default.
- If a path is a glob pattern or a directory path rather than a file path, and the path starts with `.` or contains `/.`, then ESLint makes an exception that unignores dotfiles automatically.
- If `--no-ignore` is present, and a path is a file path rather than a glob pattern nor a directory path, then ESLint doesn't ignore the file even if the path matches the default ignore patterns.

----

Anyway, I'd like to recommend to configure to unignore dotfiles you want because ignoring dotfiles is essential behavior.

```
# .eslintignore
!.storybook
```

**Comment by brandonchinn178** [comment]
Yes, I can unignore manually, but I would like to echo what this person said: https://github.com/eslint/eslint/issues/10341#issuecomment-468548031

> It's weird that you use an ignore list to un-ignore things.

I would personally request the following changes:

1. Change the error message to mention whether the ignored file is due to a default, **implicit** ignore pattern
2. Update docs to include the minutiae you listed out
3. (optional) It would be amazing to add a `dotpaths` key to `eslintrc` that specifies dot files/directories that shouldn't be "auto-ignored".

Thanks!

**Comment by mysticatea** [comment]
I have [the same comment](https://github.com/eslint/eslint/issues/10341#issuecomment-399679283). However, ignoring dotfiles is a common behavior.

About 1 and 2, PR is welcome.

About 3, you can do it once https://github.com/eslint/eslint/pull/12274 merged.

**Comment by snhardin** [comment]
Hello! I'd like to take a stab at this. I use ESLint a lot for work and would enjoy the opportunity to give back. Any pointers on where to focus my attention are appreciated.

**Comment by brandonchinn178** [comment]
@snhardin For 2, I would recommend editing [this section](https://github.com/eslint/eslint/blob/master/docs/user-guide/configuring.md#eslintignore) with more details on the implicit ignore patterns eslint automatically applies (see @mysticatea's first comment). Also, the [documentation](https://eslint.org/docs/user-guide/configuring#ignored-file-warnings) says

> File ignored because of your .eslintignore file. Use --no-ignore to override.

But the message shown is different

> File ignored because of a matching ignore pattern. Use "--no-ignore" to override

See https://github.com/eslint/eslint/blob/master/lib/cli-engine/cli-engine.js#L293

For 1, it seems like the [code tries to handle this](https://github.com/eslint/eslint/blob/master/lib/cli-engine/cli-engine.js#L286-L287), but the regex isn't good enough: it only matches `/^\./`, when the problem happens when a dot file/directory (e.g. `client/.storybook/foo.js`) occurs later on in the path. So it would probably mean fixing the regex

**Comment by snhardin** [comment]
Hello everyone. Will be submitting a PR for this soon. Thank you for your patience. 🙂

**Comment by kaicataldo** [comment]
Reopening this because we have an open PR for it.
