### ISSUE TITLE
Eslint does not respect .eslintignore when using file match pattern

### ISSUE THREAD

**Issue by amclin** [eslint/eslint#12344]
When running eslint as a command, it is required that you specify the files to be linted. But if you specify a file pattern, then the ESLint standard ignore behaviors *and* the .eslintignore file in the project folder are completely ignored.

This defeats the entire point of having node_modules ignored by default and having an `.eslintignore` file.

**Tell us about your environment**

* **ESLint Version:** 6.5.0
* **Node Version:** 10.15.3
* **npm Version:** 6.11.2

**What parser (default, Babel-ESLint, etc.) are you using?**
n/a

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

`.eslintignore`:
```
# /node_modules/* and /bower_components/* in the project root are ignored by default

# Ignore built files
build/*
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

`package.json`
```js
...
scripts: {
  "lint:eslint": "eslint **/*.{jsx,js}",
}
```

```bash
npm run lint:eslint
```

**What did you expect to happen?**
Files are linted

**What actually happened? Please include the actual, raw output from ESLint.**
```
Oops! Something went wrong! :(

ESLint: 6.5.0.

No files matching the pattern "node_modules/asn1.js" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-project-boilerplate@1.0.0 lint:eslint: `eslint **/*.{jsx,js}`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-project-boilerplate@1.0.0 lint:eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amclin/.npm/_logs/2019-09-30T19_39_42_699Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-project-boilerplate@1.0.0 lint: `npm run lint:eslint`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-project-boilerplate@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amclin/.npm/_logs/2019-09-30T19_39_42_721Z-debug.log
```

**Are you willing to submit a pull request to fix this bug?**

**Comment by amclin** [comment]
This is contrary to what the documentation says the behavior should be:
https://eslint.org/docs/user-guide/configuring#ignored-file-warnings

**Comment by amclin** [comment]
Using the `--ext` flag to specify filetypes and then declaring the root folder works:
`eslint --ext .js,.jsx ./`

But this is counterintuitive in the Node ecosystem where people expect to be able to pass glob patterns when a command accepts a list of files.

**Comment by mysticatea** [comment]
Because you are using glob patterns without quotes, so your shell resolves the patterns then pass the actual files to eslint. The error message is 'No files matching the pattern "node_modules/asn1.js" were found.' This means that the "node_modules/asn1.js" that shell passed was ignored because the path matches the default ignored pattern.

Please enclose the glob pattern by quotes.

```
eslint "**/*.{jsx,js}"
```

**Comment by kaicataldo** [comment]
Closing this issue since it looks like the question has been answered.
