### ISSUE TITLE
New rule proposal: no-undef-default

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12368]
**Please describe what the rule should do:**

Disallows using global `undefined` as a default value in destructuring patterns.

Optionally, disallows the same for function parameters.

Has autofix for both (with some exceptions for params).

**What category of rule is this? (place an "X" next to just one item)**

[X] Suggests an alternate way of doing something (suggestion)

**Provide 2-3 code examples that this rule will warn about:**

Destructuring:

```js
/* eslint no-undef-default: ["error"]*/

var { a = undefined } = foo;

let { bar: b = undefined } = foo;

const [c = undefined] = foo;

({ d = undefined } = foo);

[e = undefined] = foo;
```

Auto-fixed to:

```js
/* eslint no-undef-default: ["error"]*/

var { a } = foo;

let { bar: b } = foo;

const [c] = foo;

({ d } = foo);

[e] = foo;
```

Function params:

```js
/* eslint no-undef-default: ["error", { enforceForParams: true }]*/

function foo(a, b = undefined, c = undefined) {
}

const bar = (d, e = 1, f = undefined) => {
}
```

Auto-fixed to:

```js
/* eslint no-undef-default: ["error", { enforceForParams: true }]*/

function foo(a, b = undefined, c) { // just warning without autofix for `b`
}

const bar = (d, e = 1, f) => {
}
```

Autofix never removes a param default when it's the first default in the list because it would automatically change function's `length`. Also, it could turn a non-simple param list into a simple param list, I'm not sure could that also change some behavior.

**Why should this rule be included in ESLint (instead of a plugin)?**

It's a best practice to avoid unnecessary use of `undefined`, and it's completely unnecessary in destructuring patterns. Removing `undefined` improves readability and understanding on how destructuring works.

It could be used in functions to control `length`, that's why it's behind an option (default is `false`).

There is already a similar rule, `no-undef-init`.

I'm not sure about the name, should it be `no-undef-default` or `no-undef-defaults`.

**Are you willing to submit a pull request to implement this rule?**

Yes.

**Comment by ilyavolodin** [comment]
Not sure this rises to the level of inclusion into the core. I haven't seen a code like that before. While I think the rule is valid, it seems to me that it only covers an extreme edge case.

**Comment by platinumazure** [comment]
Why do we need a new rule? Why not just add this to no-undef-init?

**Comment by kaicataldo** [comment]
Agreed with @platinumazure. Would it make sense to add this to `no-undef-init` behind a new flag (that could be turned on by default in a future major version)? Feels like both checks (default values in destructured assignments and function parameters) could be behind one flag - maybe `enforceForDefaultValues`?

**Comment by mdjermanovic** [comment]
The idea for the new rule instead of option(s) in `no-undef-init` was because some of the cases that the rule would target, like `({ d = undefined } = foo);` and `[e = undefined] = foo;` are not 'initializing' variables. Also, with the option, it isn't possible to enforce this without the default behavior of `no-indef-init`.

If none of the above isn't a problem, I like the idea for an option in `no-undef-init`, too. Should I open a separate proposal for the option?

**Comment by ljharb** [comment]
Yes, they are - all destructurings are initializing variables.

**Comment by aladdin-add** [comment]
Thanks for your interest in improving ESLint. As of 2020, unfortunately, we have decided to [only accept rules related to new ECMAScript features](https://eslint.org/blog/2020/05/changes-to-rules-policies). We prefer that new rules be implemented in plugins, so I'm closing it.

Since ESLint is pluggable and can load custom rules at runtime, it doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Comment by ljharb** [comment]
What a really unfortunate decision :-/
