### ISSUE TITLE
eslint --changedSince

### ISSUE THREAD

**Issue by benmonro** [eslint/eslint#12363]
**The version of ESLint you are using.**
5.16.0

**The problem you want to solve.**
jest has a CLI flag for `--changedSince` which allows pull requests to only execute tests on files that have changed in that branch.  It would be nice to have something like this in eslint that would allow eslint to figure out the diff of files and only execute against those files.

**Your take on the correct solution to problem.**
`eslint --changedSince=master`

**Are you willing to submit a pull request to implement this change?**
yes

**Comment by kaicataldo** [comment]
Thanks for the issue. We ask that all changes to core go through the RFC process outlined [here](https://github.com/eslint/rfcs).

I would want to see a more complete proposal, but I'm not convinced this should be part of core. This sounds useful, but I think it would better as a 3rd party tool. I understand this isn't exactly the same thing, but here's a similar tool: https://github.com/okonet/lint-staged
