### ISSUE TITLE
no-process-env rule bypassed with require("process")

### ISSUE THREAD

**Issue by ccarcaci** [eslint/eslint#12385]
**Tell us about your environment**

* Node version: v10.15.3
* npm version: v6.11.2
* ESLint version: v6.5.1

* Parser: default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const eenie = require("process").env.EENIE
console.log(eenie)
```

```bash
eslint --fix ./
```

This is the content of my .eslintrc.js:
```
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
  },
  extends: "eslint:recommended",
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly"
  },
  parserOptions: {
    ecmaVersion: 2018
  },
  rules: {
    "no-process-env": "error",
  }
}
```

**What did you expect to happen?**
I am expecting an error or warning to the line that is using ```require("process")```

If I use the code below the rule is correctly applied:
```
const process = require("process")
const eenie = process.env.EENIE
console.log(eenie)
```

Output is:
```
no-process-env-bug/index.js
  2:15  error  Unexpected use of process.env  no-process-env
```

**What actually happened? Please include the actual, raw output from ESLint.**
No warning or error shown

**Are you willing to submit a pull request to fix this bug?**
Yes, but I don't know the code base

A complete gist with the code is here:
https://gist.github.com/ccarcaci/73baf8497ae83a0a101fd7bade25dc18

**Comment by kaicataldo** [comment]
My only concern is that we can’t avoid false negatives here due to the limits of static analysis.. That being said, seems like the majority use case (`require`ing the `process` module and reading the `env` property) would be caught.

**Comment by ccarcaci** [comment]
Thank you very much! :+1:
