### ISSUE TITLE
It doesn't work on vscode when upgrading from eslint5 to eslint6

### ISSUE THREAD

**Issue by zhanyuzhang** [eslint/eslint#12392]
It doesn't work on vscode when upgrading from eslint5 to eslint6.

**Comment by zhanyuzhang** [comment]
@eslintbot  I use [vscode-eslint](https://github.com/microsoft/vscode-eslint) plugin to config eslint on vscode editor. When I install local eslint@5.16.0 , it work perfectly , but it doesn't work when upgrading to eslint@6.4.0 , the `.eslintrc.js`'s content as follow:
```
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
    }
};
```

**Comment by g-plane** [comment]
What problem have you encountered? Also, can you try running ESLint at CLI? If it works at CLI, this problem may be from "vscode-eslint".

**Comment by zhanyuzhang** [comment]
@g-plane It can run at cli.  Only not working on vscode, I have newed an issue on   "vscode-eslint" repo. Thanks.

**Comment by g-plane** [comment]
Closing now, since it's not an issue from ESLint itself.
