### ISSUE TITLE
SVG with "viewBox" in .vue with pug

### ISSUE THREAD

**Issue by eafomi4ev** [eslint/eslint#12405]
I have a vue component. In the component's template I use a pug. When I write svg(viewBox="0 0 500 500"), eslint gives an error "All attributes must be written in lower case". How can I fix this?

"eslint": "^5.16.0",
"eslint-loader": "^3.0.2",
"eslint-plugin-vue": "^5.2.3",

No one answered me in https://gitter.im/eslint/eslint, sorry for asking there

**Comment by g-plane** [comment]
Thanks for this issue.

It seems that this issue is related to [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue), so we advise you to open issue at their repository.
