### ISSUE TITLE
Show release dates or release versions of rules in documentation

### ISSUE THREAD

**Issue by helmbold** [eslint/eslint#12404]
After configuring an eslint rule set there is no simple way to find out whether new useful rules were released and should be added to the own configuration. 

Therefore I suggest to add the date or version number when a certain rule was released the first time in the [overview](https://eslint.org/docs/rules/) and on each detail page (like [for-direction](https://eslint.org/docs/rules/for-direction)).

**Comment by g-plane** [comment]
Thanks for this issue.

First, out release note will introduce new rules when new version of ESLint was released, so you can read it to know about changes of ESLint core rules.
Second, each release of ESLint contains a Git tag. With version control, you can check the history of a rule.

**Comment by ilyavolodin** [comment]
@helmbold If you scroll down on the page that you linked for `for-direction` rule, at the bottom, you will see the section [Version](https://eslint.org/docs/rules/for-direction#version) which contains the version of ESLint when a given rule was added. We don't list that information in the rules index page, but I think the page will become very cluttered if we did.

**Comment by helmbold** [comment]
For me the additional version would be worth it, but I see your point with cluttering this overview. My use case is, that I want to check from time to time if I should add new rules to my existing rule set. It would be annoying to open every single rule page to check this.

Would it be possible to add a filter to [overview](https://eslint.org/docs/rules/) page? Like: "Show only rules from Version [x.y.z] and newer", where "[x.y.z]" would be an text field or select box.

If this is not possible, would it be possible to generate a list with rules and version information? Something like this:

```
for-direction,4.0.0-beta.0
getter-return,4.2.0
no-async-promise-executor,5.3.0
...
```
This file could be updated on every release. It would be simple to generate and simple to process, and it wouldn't clutter anything. This file could be linked on the overview page near the tables listing the rules.
