### ISSUE TITLE
new Configuration option to specify rules directory

### ISSUE THREAD

**Issue by yemb** [eslint/eslint#12403]
**The version of ESLint you are using.**
5.16.0

**The problem you want to solve.**
When i define custom rules at runtime and going to run them, i have to using the `--rulesdir `option to specify the location。
```js
eslint --rulesdir src/lib/rules test.tsx
```
I used to use tslint to lint my code, there is a option `rulesDirectory`, i can specify rules directory by adding this option in the `tslint.json`
The way I expected:
```js
// .eslintrc.js
module.exports = {
  extends: [xxx],
  rules: {xxx},
  ……
  rulesdir: ['./src/lib'] // specify rules directory here
}
```

**Are you willing to submit a pull request to implement this change?**
I'm not capable.

**Comment by kaicataldo** [comment]
Please see https://github.com/eslint/eslint/issues/4366#issuecomment-155902593.
