### ISSUE TITLE
the rule no-multi-spaces has prop ImportDeclaration, but no ExportDeclaration;

### ISSUE THREAD

**Issue by OlegBrony** [eslint/eslint#12415]
I've found a problem about multi spacing. If you want to make imports look like this 
![image](https://user-images.githubusercontent.com/19880334/66719062-aace6680-edf3-11e9-9fda-84cec7fccb99.png)
you can write something like 
```
"no-multi-spaces": [
        "error",
        {
          "exceptions": {
            "ImportDeclaration": true
          }
        }
      ],
```
but it's not working on exporting files;
![image](https://user-images.githubusercontent.com/19880334/66719073-d94c4180-edf3-11e9-8153-249c13defc74.png)

could you please add some property for this?

**Comment by mdjermanovic** [comment]
Hi @OlegBrony, thanks for the issue.

In this case, you can use `ExportNamedDeclaration` as an exception for the rule.

**Comment by OlegBrony** [comment]
okay, it helped. thanks.

**Comment by mdjermanovic** [comment]
You're welcome!

I'm closing this issue as it seems to be resolved. Feel free to open a new issue anytime if you have any further questions.
