### ISSUE TITLE
[func-call-spacing] add exception for single-character functions

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12418]
**What rule do you want to change?**

`func-call-spacing`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option, perhaps enabled by default.

**Please provide some example code that this change will affect:**

```js
$('.selector').toggle ();
```

**What does the rule currently do for this code?**

It complains about the missing space after `$`.

**What will the rule do after it's changed?**

I think a new option should be added for excluding either single-character functions or a provided list of function names from this rule.

The issue is that I usually want a space between my function name and it's call, but I also use jQuery and adding spaces after `$` would be pretty weird, I don't think I've ever seen anybody call it like that.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by kaicataldo** [comment]
If we were to add an option, I think it makes sense to make it a more generic one. Maybe `namedExceptions: string | string[]`? It could acccept a string or an array of strings (potentially also accepting RegExp as strings?).

**Comment by fabiospampinato** [comment]
@kaicataldo it sounds good 👍 Accepting a regex would make it more powerful, allowing people to match all single-character functions, which could potentially be useful for extendable configurations, for project-specific configurations I don't think listing all functions would be too much to ask.
