### ISSUE TITLE
[arrow-body-style] add exception for class arrow methods

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12417]
**What rule do you want to change?**

`arrow-body-style`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option, perhaps enabled by default.

**Please provide some example code that this change will affect:**

```js
class Cls {
  foo = () => {
    return true;
  };
  bar = () => {
    return true;
  };
  baz () {
    return this.whatever;
  }
}
```

**What does the rule currently do for this code?**

It says the arrow methods in `Cls` should spawn one line.

**What will the rule do after it's changed?**

I think a new option should be added for treating arrow functions used as class or object methods differently than other arrow functions. 

Like I want my regular throwaway/callback arrow functions to follow this rule, but if they are methods, especially class methods, I want them to always have a body for alignment purposes, without this exception those methods definitions will become an mess to read.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by mdjermanovic** [comment]
Hi @fabiospampinato,

I think this is a good idea. However, per the team's [policy around experimental features](https://github.com/eslint/eslint#what-about-experimental-features) ESLint's core rules don't support stage 3 features.

We'd be happy to discuss this enhancement if and when the syntax advances to stage 4.

**Comment by fabiospampinato** [comment]
> but if they are methods, especially class methods, I want them to always have a body for alignment purposes

Actually except if they have an empty body, then I want them inline.
