### ISSUE TITLE
[space-in-parens] add some options for handling common exception cases

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12424]
**What rule do you want to change?**

`space-in-parens`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New options.

**Please provide some example code that this change will affect:**

```js
const Foo = ({ isFoo }) => {}

const bar = fn ( { foo: true }, () => {
});
```

**What does the rule currently do for this code?**

It doesn't like the lack of spacing in the first destructuring, and it doesn't like that I'm omitting spaces when "closing" the call to `fn`.

**What will the rule do after it's changed?**

I think a few options should be added to make this rule a bit smarter for common use cases.

I generally want spaces between parenthesis, but not under some scenarios like the ones I wrote above, in particular ending the call to `fn` with `} );` rather than `});` makes it _less_ legible for me, as that space isn't serving any purpose as far as I can tell, just writing the closing parenthesis is cleaner for me.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by mdjermanovic** [comment]
Hi @fabiospampinato, thanks for the enhancement proposal!

There is already the `exceptions` option to disallow spaces in some cases when the main option is `always`: 

```js
/*eslint space-in-parens: ["error", "always", { "exceptions": ["{}"] }]*/

const Foo = ({ isFoo }) => {}

const bar = fn ({ foo: true }, () => {
});
```

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgc3BhY2UtaW4tcGFyZW5zOiBbXCJlcnJvclwiLCBcImFsd2F5c1wiLCB7IFwiZXhjZXB0aW9uc1wiOiBbXCJ7fVwiXSB9XSovXG5cbmNvbnN0IEZvbyA9ICh7IGlzRm9vIH0pID0+IHt9XG5cbmNvbnN0IGJhciA9IGZuICh7IGZvbzogdHJ1ZSB9LCAoKSA9PiB7XG59KTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by fabiospampinato** [comment]
@mdjermanovic That actually doesn't really work for me, you wrote this:

```js
const bar = fn ({ foo: true }, () => {
});
```

While I want this (notice che space before the object destructuring):

```js
const bar = fn ( { foo: true }, () => {
});
```

By enabling that rule I get about 150 extra errors, and I doubt I've been inconsistent 150 times with my own code style.

A few more code snippets that are not handled correctly/as I want to:

```js
mermaid.render ( id, str, () => {} );
$('.foo') // <- this is another exception for me, adding spaces when calling jQuery would look pretty weird to me
```

**Comment by mdjermanovic** [comment]
Thanks!

Could you please provide more details about the proposal? What options would you expect this rule to have and how exactly would the rule be configured to not report errors on these particular examples?

**Comment by fabiospampinato** [comment]
Yes, I'm not exactly sure how this should be resolved though and how the current "exceptions" option really works, but roughly:

- If some functions have a single argument of a particular type I don't want any spaces, so for instance:

  ```
  $('foo'); // OK
  $(123); // not OK
  foo ( 'foo' ); // OK
  foo ('foo'); // not OK
  ```

  - Perhaps there could be an option for adding exceptions for specific functions and for specific arguments passed to that functions, like:
  
  ```
  { "allowed": ["$", "i"] } // This would add an exception for the "$" and "i" functions, no matter how many arguments they receive and of what type
  { "allowed: [{ "function": "$", "max": 1 }] } // This would add an exception for the "$" function, but only if it receives at maximum 1 argument. I don't see why somebody may want this to work for 2 or 3 arguments but it may be good to generalize this anyway
  { "allowed": [{ "function: "$", "max": 1, "types": ["string"] }] } // Like the above, but it works only if strings are passed
  ```

- If in a line I'm just closing curly braces, brackets and/or parenthesis I don't care about spacing.
  - Perhaps an `ignoreClosingLine` could be added, where by "closing line" I mean a line containing only closing tokens.

Btw I have another code style practice I haven't opened an issue for, I prefer to write `foo ([ 1, 2, 3 ])` and `foo ({ foo: 1, bar: 2 })` if I'm passing a single array or object to a function, fixing the issue I reported here would partially address this too.

**Comment by fabiospampinato** [comment]
> If in a line I'm just closing curly braces, brackets and/or parenthesis I don't care about spacing.

Actually I would expect to be able to write something like this too:

```
})).catch ( onError );
```

So perhaps a better definition would be: if the first token in a line is an ending token I don't care about spaces between it and subsequent consecutive ending tokens.

**Comment by kaicataldo** [comment]
I'm 👎 on this proposal as it's a highly complicated, niche style. This seems like a great candidate for implement your own rule using https://github.com/not-an-aardvark/eslint-rule-composer.

**Comment by fabiospampinato** [comment]
@kaicataldo I'm not sure it's that niche of a style. Within the set of people who like spaces between their parenthesis I doubt those that are using jQuery prefer to call it like so: `$( '.foo' )`  (or even `$ ( '.foo' )`), that looks kind of weird to me.

I agree that the configuration might get somewhat complicated, but the alternative for those who need this is just not using the rule at all, perhaps even dropping ESLint entirely if it can't really be used to format their code.

**Comment by kaicataldo** [comment]
Mind sharing some examples of this code style? We do try to support popular styles in our core rules.

I've worked in code bases that require spaces in parens and ones that disallow it but I've never encountered a code base that required different rules based on what function was being called, but maybe I've just happened to miss it.

**Comment by fabiospampinato** [comment]
> I've worked in code bases that require spaces in parens and ones that disallow it but I've never encountered a code base that required different rules based on what function was being called, but maybe I've just happened to miss it.

Were those codebases using jQuery or a similar library? I don't think I've ever seen somebody calling it like this: `$( '.foo' )`, if it happened it must have been a rare occurrence.

To give some more non-jQuery examples:

1. I call functions like this if they only get passed a single object or array, it makes the code quite a bit cleaner for me:

   ```js
   this.setState ({ editing });
   notesNext = notes.concat ([ note ]);
   ```

2. I don't bother writing spaces that serve no legibility purposes in closing lines, in fact adding them makes the thing less legible for me:

   ```js
    await Promise.all ( filePaths.map ( async filePath => {
      const note = await this.ctx.note.read ( filePath );
      if ( !note ) return;
      notes[filePath] = note;
    }));
    // OR
    const {id, plainContent} = useStore ( API.note, note => ({
      id: note.getFilePath (),
      plainContent: note.getPlainContent ()
    }));
   ```

**Comment by kaicataldo** [comment]
> Were those codebases using jQuery or a similar library?

Yes, lots of jQuery :) For what it's worth, jQuery's own docs format use spaces in jQuery selectors.

I'm not against it if other team members feel like the extra complexity is worth it. Can you add more detail about the API you're envisioning and how you think it will work? Seems like there are a few different enhancements listed here, and they'll each need their own option. If it makes it easier, feel free to split it out into multiple issues/proposals.

**Comment by kaicataldo** [comment]
As a starting point, here are the proposals I see (I've added question marks to the ones I'm not sure of):

1) Allow exceptions for destructured parameters (?)
2) Allow exception for groups of parens/brackets on the last line if they are alone on that line
3) Configurable exceptions based on function names and types (the latter is not really enforceable without a type system)
4) Allowing spaces before the parens of a call expression only when the arguments consist of a single object or array (?)

Please also note that the rule already has some configuration options and we'll need to figure out how they would all interact.

**Comment by fabiospampinato** [comment]
> For what it's worth, jQuery's own docs use spaces in jQuery selectors.

Oh that's true! 😨 I can't believe I didn't realize that.

> Allow exceptions for destructured parameters (?)

- For a destructured parameter if that's the only parameter.
- For an array or object literal if that's the only passed parameter.

> Allow exception for groups of parens/brackets on the last line if they are alone on that line

Yes, but more specifically the range between the first ending token and the last consecutive ending token on a line shouldn't contain spaces.

The difference is that this would allow for code like this to be written:

```
})).catch ( onError );
```

Usually though I refactor those code snippets anyway so making the rule this precise wouldn't matter much for me.

> Configurable exceptions based on function names and types (the latter is not really enforceable without a type system)

Yes, as long as only one argument gets passed. An exception based on function names alone would work just fine 99.99% of the times I think.

> Allowing spaces before the parens of a call expression only when the arguments consist of a single object or array(this would actually be the responsibility of space-before-function-paren) (?)

No that would actually be about _disallowing_ spaces _between_ parenthesis if only a single array or object is passed, and that literal should contain spaces between its starting and ending tokens.

It's a little weird but I've gotten used to writing this way and it makes the code a bit clear in my opinion.

I haven't actually mentioned this use case in my original post as that would require exceptions in some rules regarding arrays and objects too, for enforcing spaces in this scenario), I'll open up a separate issue if this one goes through.
