### ISSUE TITLE
[object-curly-spacing] add exception for imports and destructuring

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12422]
**What rule do you want to change?**

`object-curly-spacing`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New options.

**Please provide some example code that this change will affect:**

```js
import {foo, bar} from 'example';

const {key1, key2} = foo ( { opt: true } );
```

**What does the rule currently do for this code?**

It handles object literals, object destructuring and multiple imports the same way.

**What will the rule do after it's changed?**

I think new options should be added for handling those cases separately. 

I personally want spaces inside curly braces in object literals, but not when importing and when destructuring.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by kaicataldo** [comment]
I think this makes sense. If we accept this, I think it makes sense to have it be similar to the configuration for [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline).
