### ISSUE TITLE
[multiline-ternary] doesn't handle newlines properly

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12421]
**Tell us about your environment**

* **ESLint Version:** 6.5.1
* **Node Version:** 10.15.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

`@typescript-eslint/parser`

**Please show your full configuration:**

[Here](https://pastebin.com/Ni7HyKHL) it is, just uncomment the "multiline-ternary" rule.

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const Foo = ({ isFoo }) => (
  <div>
    {!isFoo ? null : (
      <p>Whatever</p>
    )}
  </div>
);
```

```bash
npx eslint src --ext '.ts, .tsx'
```

**What did you expect to happen?**

No error detected.

**What actually happened? Please include the actual, raw output from ESLint.**

I think ESLint is considering a newline inside the last argument as a newline inside the entire ternary operator expression, which kind of makes sense but because of this the ternary operator I wrote doesn't follow the rule according to ESLint.

Writing ternary operators like that is very common inside React components, and putting the first "argument" of the ternary operator in a new line as well would severely hinder legibility for me.

**Are you willing to submit a pull request to fix this bug?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by mdjermanovic** [comment]
Hi @fabiospampinato, thanks for the report!

I think that the option works as intended:

> "always-multiline" enforces newlines between the operands of a ternary expression if the expression spans multiple lines.

**Comment by kaicataldo** [comment]
I agree with @mdjermanovic, but can you include the actual error/output you're seeing so we can confirm it? I just want to make sure we're diagnosing the right issue.

**Comment by fabiospampinato** [comment]
> I think that the option works as intended:

I can see how "always-multiline" could be working as intended, but given that it triggers even if a newline is found inside the last argument it doesn't allow the pattern I wrote above, which is common in the React world.

I think there should be an option for relaxing this behavior and allowing the last argument to be written on multiple lines if its definition at least starts on the same line.

I could disable this rule entirely but I'd also like it to warn me about ternary operators written like this:

```js
foo
  ? 123 : 0

// OR

foo ? 123
    : 0 

// OR

foo ? 123 :
  0
```

Maybe an option for this could be added? I should have probably opened a rule-change issue rather than a bug report 🤔.

> I agree with @mdjermanovic, but can you include the actual error/output you're seeing so we can confirm it? I just want to make sure we're diagnosing the right issue.

I'm getting the following error:

```
Expected newline between test and consequent of ternary expression.eslint(multiline-ternary)
```

**Comment by mdjermanovic** [comment]
I agree that this looks more like a rule-change request.

An interesting thing here is that the rule doesn't require a newline between consequent and alternate as well. That's probably because the paren isn't a part of the alternate in AST, and that might be a bug (most likely in some other 'newline' rules, too).

Off-topic, something like `isFoo && <p>Whatever</p>` can be also used instead of a ternary.

**Comment by fabiospampinato** [comment]
> Off-topic, something like `isFoo && <p>Whatever</p>` can be also used instead of a ternary.

Right 🤔 I don't actually remember why I started using the `!isFoo ? null : ()` pattern, maybe for avoiding potential issues when writing things like `list.length && <p>List...</p>`. That could be the topic for another rule.
