### ISSUE TITLE
[lines-between-class-members] add exception for non-method members

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12420]
**What rule do you want to change?**

`lines-between-class-members`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option, perhaps enabled by default.

**Please provide some example code that this change will affect:**

```js
class Cls {
  myPropFoo = 123;
  myPropBar = 123;
  myPropBaz = 123;
	
  foo = () => {
    return this.myPropFoo;
  };

  bar = () => {
    return this.myPropBar;
  };

  baz = () => {
    return this.myPropBaz;
  };
}
```

**What does the rule currently do for this code?**

It says I need to add a newline between `myPropFoo`, `myPropBar` and `myPropBaz`.

**What will the rule do after it's changed?**

I think a new option should be added for treating non-method members differently, as I want to group them together instead of have them separated by a newline. A newline between non-method members is not useful for legibility as one between methods is for me, in fact it will have the opposite effect.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by mdjermanovic** [comment]
Thanks for the issue!

Per the team's [policy around experimental features](https://github.com/eslint/eslint#what-about-experimental-features) ESLint's core rules don't support stage 3 features.

I agree that the rule should have new options if the syntax advances to stage 4, this should be definitely discussed when that happens.
