### ISSUE TITLE
[func-names] add an exception for IIFEs

### ISSUE THREAD

**Issue by fabiospampinato** [eslint/eslint#12434]
**What rule do you want to change?**

`func-names`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option.

**Please provide some example code that this change will affect:**

```js
(function () {
	// code
})();
```

**What does the rule currently do for this code?**

It complains that the IIFE doesn't have a name.

**What will the rule do after it's changed?**

I think a new option should be added for excluding IIFEs from this rule, as I don't think it makes a lot of sense to name IIFEs.

**Are you willing to submit a pull request to implement this change?**

I'm not too familiar with the AST, but with some pointers perhaps I can help.

**Comment by kaicataldo** [comment]
> I think a new option should be added for excluding IIFEs from this rule, as I don't think it makes a lot of sense to name IIFEs.

Can you expand on this? The purpose of the rule is to enforce named functions for the purposes of debugging. If this isn't desired, could it better to just turn the rule off?

**Comment by fabiospampinato** [comment]
> Can you expand on this? The purpose of the rule is to enforce named functions for the purposes of debugging. If this isn't desired, could it better to just turn the rule off?

These rules are sometimes too simplistic. I like my functions to be named, but naming an IIFE litters the code more than anything in my opinion.

**Comment by kaicataldo** [comment]
Understood. I'm not sure I'm convinced it's worth adding the extra complexity here, since the motivation for the rule is to improve debugging. If that's something you don't care about, it seems like a better option to just disable the rule.

**Comment by fabiospampinato** [comment]
Other than for an improved debugging experience I'm using this rule to keep my code more consistent, I think ESLint should help with that too. If I can't configure it to follow my coding style it may be more of an annoyance than an helpful tool for me.

**Comment by kaicataldo** [comment]
We understand that the core rules won't be sufficient for all use cases, which is why ESLint is pluggable. Let's hear what others have to say, but in the event this doesn't get accepted, you can always create your own rule (using https://github.com/not-an-aardvark/eslint-rule-composer can simplify this quite a bit).

**Comment by fabiospampinato** [comment]
Fair enough. I just don't think I've ever seen somebody naming their IIFEs, it may be not a super popular use case as most people maybe don't use IIFEs at all, but those who do I bet either don't enable this rule or just comply with it to shut the warnings up, if ESLint could handle this it would be great.

**Comment by fabiospampinato** [comment]
A bunch of my issues have been closed for the same reason, one question: if I submit a PR implementing would it still be considered? In case they will be considered should I perhaps jump in the individual issues again in the future in order to discuss potential solutions before attempting to implement them?

**Comment by kaicataldo** [comment]
@fabiospampinato We appreciate your proposals, regardless of whether or not the team reaches consensus on implementing them. You can find our issue acceptance policy [here](https://eslint.org/docs/maintainer-guide/issues).

As for specific feedback on your proposals, I think some of them have been a bit too niche for core rules, making it difficult to reach consensus from the team. Fortunately, ESLint is pluggable, and you can make your own [custom rules](https://eslint.org/docs/developer-guide/working-with-rules) to enforce whatever you’d like!

You can also feel free to create a new issue and see if you can garner support once more.

**Comment by fabiospampinato** [comment]
@kaicataldo Thanks. Did my proposals not reach consensus because the maintainers thought they would bloat ESLint without providing enough value?

I'll consider developing custom plugins for my use case, but I think that would probably require me to spend a few days developing them, at least, and I would then have the burden to backport (or "frontport" I guess? 🤔) any improvements you guys may do on those rules to my version of them, so I'm not sure I'll do it.

**Comment by kaicataldo** [comment]
I can’t speak for any of my colleagues, but the trade-off of maintenance burden is always a consideration.
