### ISSUE TITLE
no-undef rule doesn't work properly with comma operator

### ISSUE THREAD

**Issue by SkeLLLa** [eslint/eslint#12449]
* **ESLint Version:** eslint@6.5.1
* **Node Version:** node@12.12.0
* **npm Version:** npm@6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    env: {
        commonjs: true,
        es6: true,
        node: true,
    },
    extends: ['eslint:recommended'],
    parserOptions: {
        ecmaVersion: 2018,
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const object = {a:1, b:2, c:3, d:4}
const filterProps =
        (({a, b} = object),
        {a, b});
```

```bash
eslint .
```

**What did you expect to happen?**
No `no-undef` error for each parameter (`a` and `b` in example)

**What actually happened? Please include the actual, raw output from ESLint.**
Eslint throws `no-undef` error.

**Comment by ljharb** [comment]
Why would you expect no error? The destructuring (`({a, b} = object)`) is creating `a` and `b` variables without a declaration keyword.

**Comment by mdjermanovic** [comment]
Hi @SkeLLLa, thanks for the issue.

I agree with @ljharb. Code without `no-undef` errors could be something like this:

```js
const object = {a:1, b:2, c:3, d:4}
const {a, b} = object,
    filterProps = {a, b}
```
