### ISSUE TITLE
Allow test on folder or files

### ISSUE THREAD

**Issue by fa93hws** [eslint/eslint#12442]
**The version of ESLint you are using.**
Not related

**The problem you want to solve.**
The `npm run test` is too slow.
If I add a feature and a unit test for it, I would like to see whether my unit test failed or not. However, I can only do a `npm run test` currently which will run all the tests for me.
Chances are that I made some mistake in my implementation and my unit test is able to catch that. But I have to wait another minute for all test cases to run.🤦‍♂️

Another thing is the linting before the test.
Sometime I need a `console.log` for debugging purpose but I have to add a `eslint-disable-next-line` in order to let the test to begin. There are some other cases like that such as I have to add an empty line after some kind of statement which further decrease the efficiency.

**Your take on the correct solution to problem.**
Allow the script to accept an argument, say `--folder`.
Running `npm run test --folder lib/linter" will only trigger the tests in the `tests/lib/linter`.

Allow the script to accept an argument, say `--skipLinting`
Runing `npm run test --skipLinting` will skip the linting in the test

**Are you willing to submit a pull request to implement this change?**
Happy to have a try even though the logic in the Makefile looks a bit crazy.

**Comment by mdjermanovic** [comment]
Maybe this could help: [Running Individual Tests](https://eslint.org/docs/developer-guide/unit-tests#running-individual-tests)

**Comment by fa93hws** [comment]
Oh thanks! Didn't know there is such a thing
