### ISSUE TITLE
White-spaces in ternary operator

### ISSUE THREAD

**Issue by rhalaly** [eslint/eslint#12447]
**Tell us about your environment**

* **ESLint Version:** 6.3.0
* **Node Version:** 10.16.3
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
"multiline-ternary": [
    "error",
    "always-multiline"
],
"operator-linebreak": "error",
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
true
    ?                         trueCode()
    :                          falseCode();
```

```bash
eslint index.js
```

**What did you expect to happen?**
Get an error about the trailing white-spaces in the ternary operator.

**What actually happened? Please include the actual, raw output from ESLint.**
No error

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mdjermanovic** [comment]
Hi @rhalaly, thanks for the issue!

Maybe the [no-multi-spaces](https://eslint.org/docs/rules/no-multi-spaces) rule could help here?

**Comment by rhalaly** [comment]
Thanks! Maybe it is what I've searched for. Closing this issue.
