### ISSUE TITLE
extend eslint:all to include plugins

### ISSUE THREAD

**Issue by mockdeep** [eslint/eslint#12453]
**The version of ESLint you are using.**

6.5.1

**The problem you want to solve.**

This is a followup to https://github.com/eslint/eslint/issues/6240 and https://github.com/eslint/eslint/pull/6248. The `eslint:all` configuration has been working great on our projects. However, some plugins implement a similar `all` configuration and some don't. It's a pain for every plugin maintainer to have to implement a similar rule, and in some cases they are unwilling to implement it. We would like to be able to enable all ESLint rules across all of our plugins by default, then configure them away from the defaults where appropriate. A couple of my previous comments for way more context:

https://github.com/eslint/eslint/issues/6240#issuecomment-221123719
https://github.com/eslint/eslint/issues/6240#issuecomment-223716227

**Your take on the correct solution to problem.**

ESLint should have an option to enable all rules across plugins, not just the built in rules.

**Are you willing to submit a pull request to implement this change?**

I'm happy to implement something like this with guidance. I implemented the `eslint:all` rule, but it looks like plugin rules are loaded separately from builtin rules, so it might be somewhat more complicated to implement.

**Comment by kaicataldo** [comment]
I don't think this is a good idea. We make a concerted effort to make core rules not conflict with each other, but there's absolutely no guarantee that this will happen with 3rd party plugins.

**Comment by platinumazure** [comment]
I wouldn't want to have `eslint:all` itself automatically include core plugins, but I could maybe get behind a dynamic configuration extension that turns on all rules of any named plugin (e.g., `all:plugin:react` might turn on all rules in eslint-plugin-react). This would come with the same caveats we already include for `eslint:all`. (That said, I'm not sure where I land on benefit vs maintenance cost there.)

@kaicataldo Do you think you could get behind something like that?

**Comment by mockdeep** [comment]
> We make a concerted effort to make core rules not conflict with each other, but there's absolutely no guarantee that this will happen with 3rd party plugins.

I mentioned this in the other thread, but I'm not super concerned with this, as it's opt-in behavior and I can disable rules that clash for me. There's already somewhat of a risk with using the `recommended` rule sets that most plugins have, though admittedly this will be more extensive. I've definitely run into conflicts between the React plugin and core rules.

>  I could maybe get behind a dynamic configuration extension that turns on all rules of any named plugin

This seems like a good alternative. Another thought is to have a separate directive like `eslint:all-with-plugins`.

**Comment by platinumazure** [comment]
@kaicataldo @g-plane Could you please clarify your :-1:s? Are you opposed to the whole idea, or just to making `eslint:all` include plugins by default? Do you have any thoughts on the alternatives raised so far?

**Comment by kaicataldo** [comment]
I don't really see the value in this (the benefits don't seem to outweigh the increased confusion/support we might have to offer users), but if other members of the team are for it, I'll defer to consensus.

**Comment by ilyavolodin** [comment]
I also share @kaicataldo opinion. A lot of plugin rules were never designed to be just `on/off`. They requires configuration, and are completely meaningless without it. Most of the bigger plugin packages also provide bundled configs with a plugin, so if anything that `all` config should just go into plugin.

**Comment by platinumazure** [comment]
I've thought about it some more, and I think I'm also slightly opposed on cost/benefit grounds.

I'm wary of more support questions that might come in because someone is using the ESLint core "enable all rules from a plugin", even though 99% of those questions should go to the plugin owner. The benefit of this change does not justify the maintenance/support cost, in my view.

**Comment by mockdeep** [comment]
@kaicataldo @platinumazure have there been support questions about the existing `eslint:all` rule? I wouldn't expect much being that it is the sort of thing somebody would have to go in search of in the first place.

**Comment by kaicataldo** [comment]
I don't think we do, no. My concern is mostly with 3rd party plugins, since there are no guarantees that they won't conflict with core rules or each other. As an example, `eslint-plugin-babel` and `@typescript-eslint/plugin` both contain rules that are intended to replace core rules (you want to turn core rules off and the replacement rule on) to handle non-standard syntax. This means that this feature would be completely incompatible with those plugins.
