### ISSUE TITLE
[no-unused-vars] rule reports an error for... in/of

### ISSUE THREAD

**Issue by tichenchen** [eslint/eslint#12455]
### The version of eslint
6.5.1
### The details of the problem
`for (const item of items ) { console.log(item)}`
no-unused-vars reports an error to the above code block，What's the reason

**Comment by platinumazure** [comment]
Possible duplicate of #12117.

If you're using babel-eslint, please upgrade to latest.

**Comment by g-plane** [comment]
Out of this issue, should we pin an issue to issues list to prevent duplicated issues about this problem (which is related to `no-unused-vars` and "babel-eslint")?

**Comment by tichenchen** [comment]
It's really because of babel-eslint, Thank you. 
I think it's a good idea to have a list of questions.

**Comment by tichenchen** [comment]
> Out of this issue, should we pin an issue to issues list to prevent duplicated issues about this problem (which is related to `no-unused-vars` and "babel-eslint")?

It's really because of babel-eslint, Thank you.
I think it's a good idea to have a list of questions.
