### ISSUE TITLE
Unify strict mode rules

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1246]
Right now we have three rules dealing with strict mode:

- [global-strict](http://eslint.org/docs/rules/global-strict.html)
- [no-extra-strict](http://eslint.org/docs/rules/no-extra-strict.html)
- [strict](http://eslint.org/docs/rules/strict.html)

Working on #1245, it seemed like there was a lot of code that was either duplicated or existed only to avoid stepping on the other rules.

It seems logical to me to combine all three rules into a single `strict` rule, which would have a mode option for "global"/"function"/"never" and warn whenever a strict mode directive occurred in an undesirable location. Thoughts?

**Comment by nzakas** [comment]
Let's do this. We still need to keep the old rules around until 1.0.0, but we can deprecate them.

**Comment by btmills** [comment]
Working on this.

**Comment by btmills** [comment]
I've combined all three rules as described at the top of this issue, the tests pass, there are no breaking changes, and the deprecated code is isolated for easy removal when 1.0 rolls around. To elaborate on the three modes:

- `"never"` forbids any occurrence of a Use Strict Directive.
- `"global"` ensures that global code contains exactly one Use Strict Directive. Use Strict Directives inside functions are considered unnecessary. Multiple Use Strict Directives at any level also trigger warnings.
- `"function"` forbids any occurrence of a Use Strict Directive in global code. It requires exactly one Use Strict Directive in each function declaration or expression whose parent is global code. Use Strict Directives inside nested functions are considered unnecessary. Multiple Use Strict Directives at any level also trigger warnings.

Note that a `"use strict";` statement that occurs outside of the Directive Prologue will be flagged by `no-unused-expressions` and not by this rule.

The available modes do not cover the case where someone may wish to forbid Use Strict Directives in global code while allowing but not requiring them in function code. Since this would involve mixing strict and non-strict code, I'm inclined to say that this case should require explicitly enabling or disabling the rule or disabling it entirely, though I could be convinced either way.

**Comment by nzakas** [comment]
:+1: to everything you said.
