### ISSUE TITLE
SyntaxError: Invalid regular expression flags From 6.6.0 Release

### ISSUE THREAD

**Issue by emilyrohrbough** [eslint/eslint#12493]
**Tell us about your environment**

* **ESLint Version:** 6.6.0
* **Node Version:** lts/carbon
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

My eslint-config extends: https://github.com/cerner/eslint-config-terra/blob/master/eslint.config.js

```js
"eslintConfig": {
    "extends": "terra",
    "settings": {
      "polyfills": [
        "Promise"
      ]
    },
    "rules": {
      "import/no-extraneous-dependencies": "off",
      "import/no-unresolved": "off",
      "camelcase": "off",
      "class-methods-use-this": "off"
    },
},
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
The latest eslitn version was pulled in during a CI build and failed lint tests.

I was able to reproduce by removing my node_modules dir locally and running install again. Running eslitn resulting in errors.

```bash
> eslint --ext .js,.jsx .
```

**What actually happened? Please include the actual, raw output from ESLint.**
[This recent change](https://github.com/eslint/eslint/commit/2d6e345e3c2626b0f2252f22cfaffdf53ea0871a#diff-b9a51d45d62371fc85d5c2198b40cdd6R426
) is causing builds to fail with the following error: 
```bash
> eslint --ext .js,.jsx .

/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/eslint/lib/source-code/source-code.js:426
        return /\s/u.test(text.replace(/\/\*.*?\*\//gus, ""));
                                       ^

SyntaxError: Invalid regular expression flags
    at NativeCompileCache._moduleCompile (/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/eslint/lib/source-code/index.js:4:17)
    at Module._compile (/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

**Comment by mdjermanovic** [comment]
That's the `s` flag added in #12407 

According to this [compat-table](https://kangax.github.io/compat-table/es2016plus/#test-s_(dotAll)_flag_for_regular_expressions) it should be supported in Node >= 8.10

**Comment by mdjermanovic** [comment]
Our Node v8.16.2 build is passing, @emilyrohrbough on which Node version is your build failing?

**Comment by rajakedia1** [comment]
On node v8.9.4 its failing

**Comment by kaicataldo** [comment]
The latest major release line of ESLint [currently supports the following engines](https://github.com/eslint/eslint/blob/4e142ea411dfb692b6e2a69cd5f1204ade4dd58a/package.json#L143): 

```json
{
    "node": "^8.10.0 || ^10.13.0 || >=11.10.1"
}
```

**Comment by platinumazure** [comment]
Can we just make a change to not require this flag? The s flag just means dots represent newlines, right? Could we use something like `[\s\S]` instead of dot and then we could remove the s flag?

**Comment by mysticatea** [comment]
Yes, ESLint supports only Node.js `8.10.0` or later since ESLint `6.0.0`.

You should see the following warning if you installed ESLint with old Node.js:

```
> npm i eslint
npm WARN notsup Unsupported engine for eslint@6.6.0: wanted: {"node":"^8.10.0 || ^10.13.0 || >=11.10.1"} (current: {"node":"8.0.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: eslint@6.6.0
```

**Comment by emilyrohrbough** [comment]
@mdjermanovic & @mysticatea it looks like I am on node 8.9.2 and missed the 8.10 minimum requirement for the upgrade. whoops!! I did just verify my build, and I am not seeing the warning messages in install for the non-supported engines/node verisons:
<details>
<summary> Log Output: </summary>

```bash
➜  chart-summary-component git:(add-menu-sass-side) run clean:install

> chart-summary-component@0.0.0 clean:install /Users/er047227/orion/chart-summary/chart-summary-component
> npm run clean && npm install


> chart-summary-component@0.0.0 clean /Users/er047227/orion/chart-summary/chart-summary-component
> rm -f ./package-lock.json && rm -rf node_modules

npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> fsevents@1.2.9 install /Users/er047227/orion/chart-summary/chart-summary-component/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/er047227/orion/chart-summary/chart-summary-component/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> chart-summary-component@0.0.0 prepare /Users/er047227/orion/chart-summary/chart-summary-component
> npm run build


> chart-summary-component@0.0.0 build /Users/er047227/orion/chart-summary/chart-summary-component
> npm run compile


> chart-summary-component@0.0.0 compile /Users/er047227/orion/chart-summary/chart-summary-component
> npm run compile:clean && npm run compile:build


> chart-summary-component@0.0.0 compile:clean /Users/er047227/orion/chart-summary/chart-summary-component
> rm -rf lib


> chart-summary-component@0.0.0 compile:build /Users/er047227/orion/chart-summary/chart-summary-component
> babel src --out-dir lib --copy-files

Successfully compiled 17 files with Babel.
npm WARN eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-react-hooks@^1.7.0 but none is installed. You must install peer dependencies yourself.

added 779 packages in 22.343s
```
</detials>

**Comment by RoCkAs** [comment]
I get the same output error. Tested with node **8.16.0** and **10.15.3**. If i refactor
`return /\s/u.test(text.replace(/\/\*.*?\*\//gus, ""));`
to
`return /\s/u.test(text.replace(/\/\*.*?\*\//gu, ""));`
or downgrade to **eslint@6.0.1** then everything works as expected.
