### ISSUE TITLE
Problem with rule in file

### ISSUE THREAD

**Issue by dkarpeSS** [eslint/eslint#12499]
I created my own rule, run it from CLI as a --ruledir, it shows me warnings as expected, but when I open the file in which this problem occurs, it writes me a message : Definition for rule 'bla-bla-bla' was not found, but i`d like to indicate in file which word must be changed, how can i add this?

**Comment by g-plane** [comment]
Thanks for this issue.

Custom rules directory is only available at CLI, and editor integration may not support this.

**Comment by kaicataldo** [comment]
For what it's worth, I've successfully used https://www.npmjs.com/package/eslint-plugin-rulesdir to ensure that custom rules are used by integrations that use the Node API (like editor integrations).
