### ISSUE TITLE
Eslint eagerly parses config files, in spite of glob pattern

### ISSUE THREAD

**Issue by abirmingham** [eslint/eslint#12503]
**Tell us about your environment**

```
$ ./node_modules/.bin/eslint --env-info
Environment Info:

Node version: v12.4.0
npm version: v6.9.0
Local ESLint version: v6.6.0 (Currently used)
Global ESLint version: Not found
```

**What parser (default, Babel-ESLint, etc.) are you using?**
`default`

**Please show your full configuration:**
```js
{
    "rules": {
        "react/jsx-key": "error",
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "error"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": ["react", "react-hooks"]
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
./node_modules/.bin/eslint '{src,test,stories}/**/*.+(ts|tsx)'
```

**What did you expect to happen?**
Eslint to audit code in paths matching the glob pattern, i.e. in `src`/`test`/`stories`.

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint throws an exception when parsing a configuration file in unrelated subdirectory `tools`. Looking at the eslint code a bit, it appears that all subdirectories are being eagerly parsed prior to being filtered to match the glob. In my case, `./tools/node_modules/acorn/src/.eslintrc` exists, and when that file is parsed eslint attempts to resolve its `extends` array, which includes the config `standard`. Understandably, `acorn` specifies all of its `eslint` dependencies as `devDependencies`, so they will not be installed transitively. Note that this is `acorn@5.0.3`.

**6.6.0:**
```
ESLint: 6.6.0.

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/data/depot-ui/tools/node_modules/acorn/src/.eslintrc".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I'll include 6.3.0 as well because it includes a stack trace that I manually printed...
**6.3.0:**
```
Error: Failed to load config "standard" to extend from.
Referenced from: /data/depot-ui/tools/node_modules/acorn/src/.eslintrc
    at configMissingError (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:712:23)
    at ConfigArrayFactory._loadExtends (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:617:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.loadInDirectory (/data/depot-ui/node_modules/eslint/lib/cli-engine/config-array-factory.js:400:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/data/depot-ui/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:304:46)

Oops! Something went wrong! :(

ESLint: 6.3.0.

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/data/depot-ui/tools/node_modules/acorn/src/.eslintrc".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by abirmingham** [comment]
**Workaround:**

As a workaround I've added an `.eslintignore` file to ignore the `tools` directory.

**Comment by mysticatea** [comment]
Thank you for your report.

Because, when ESLint handles a glob pattern, it starts to traverse directories at the longest static part then finds the files that are matched the rest part. For example, if `/foo/bar/{a,b,c}/*.js`  is present, it starts at `/foo/bar` then checks all files with `{a,b,c}/*.js` in the directory.

If you separate the glob pattern, it should work as expected.

```
./node_modules/.bin/eslint src test stories --ext ts,tsx
```

**Comment by abirmingham** [comment]
@mysticatea thanks for the quick response!

I just want to make sure that I understand. You're saying that if I provide `/foo/bar/{a,b,c}/*.js`, I should expect `/foo/bar/d/a/*.js` to match?

Or, in my case, I should expect `{src,test,stories}/**/*.+(ts|tsx)` to match `tools/node_modules/acorn/src/.eslintrc`?

**Comment by mysticatea** [comment]
> I just want to make sure that I understand. You're saying that if I provide /foo/bar/{a,b,c}/*.js, I should expect /foo/bar/d/a/*.js to match?

No. But ESLint traverses `/foo/bar/*` to check if there are the files that are matched the rest part of glob. In that time, ESLint loads config files from the traversed directories because config files can change how ESLint finds files.

> Or, in my case, I should expect {src,test,stories}/**/*.+(ts|tsx) to match tools/node_modules/acorn/src/.eslintrc?

ESLint ignores `/node_modules/*` by default, so doesn't traverse `/node_modules/*`.

**Comment by mysticatea** [comment]
> In my case, why should ./tools/node_modules/acorn/.eslintrc change how ESLint find files? And why would this behavior be specific to the glob case?

By [ignorePatterns](https://github.com/eslint/rfcs/blob/master/designs/2019-core-options/README.md#-ignorepatterns) property, config files can add/remove ignored files/directories. By [overrides[].files](https://github.com/eslint/rfcs/blob/master/designs/2019-additional-lint-targets/README.md#detailed-design), config files can add the kind of default target files. Therefore, ESLint must load config files before traversing the directory. Since ESLint 6.0.0, it loads config files before traversing each directory in order to add such kind of functionality without more breaking changes.

> Should it?

This behavior has been introduced in [ESLint 0.10.0](https://eslint.org/blog/2014/11/eslint-0.10.0-released), then it's as-is til now. If you want to change this behavior, please write an RFC. We have [the RFC process](https://github.com/eslint/rfcs#readme) to change core behavior.

**Comment by abirmingham** [comment]
> By ignorePatterns property, config files can add/remove ignored files/directories. By overrides[].files, config files can add the kind of default target files. Therefore, ESLint must load config files before traversing the directory. Since ESLint 6.0.0, it loads config files before traversing each directory in order to add such kind of functionality without more breaking changes.

Forgive me, I may not have phrased my question precisely. I understand that `.eslintrc` affects the way that a directory is parsed by ESLint. What I'm trying to understand is how a subdirectory `.eslintrc` might affect parsing of a parent/ancestor directory. For example, in my case, why would `./tools/node_modules/acorn/.eslintrc` ever need to be parsed in order to handle the glob `{src,test,stories}/**/*.+(ts|tsx)`? As far as I can tell, this "eager parsing" behavior can only lead to errors - I can't seem to think of a case where it would be desired or expected. But maybe there is a case where a subdirectory `.eslintrc` affects the parsing of its ancestor directories? Can you give an example of a case like this?

**Comment by mysticatea** [comment]
No, config files don't affect to ancestor directories. As I described in this part "[But ESLint traverses `/foo/bar/*` to check if there are the files that are matched the rest part of glob.](https://github.com/eslint/eslint/issues/12503#issuecomment-547732581)", the reason for ESLint loads `/foo/bar/d/.eslintrc` is that ESLint traverses `/foo/bar/*` to check if there are the files that are matched the rest part of glob.

**Comment by abirmingham** [comment]
> No, config files don't affect to ancestor directories.

That's good. It does seem there is no need for `/foo/bar/d/.eslintrc` to be parsed in this case.

> ...the reason for ESLint loads `/foo/bar/d/.eslintrc` is that ESLint traverses `/foo/bar/*` to check if there are the files that are matched the rest part of glob.

I am suggesting that this is unnecessary, expensive, and can cause errors like this one. Wouldn't it be strictly better if path expansion occurred prior to traversal?

For example, if `/foo/bar/{a,b,c}/*.js` is passed, then ESLint need not traverse `/foo/bar/d`. Enumerating its descendants might be costly or impossible (in the case of `acorn`), and those descendants will later be discarded anyway when the glob is matched against.

Forgive me, I don't mean to belabor the point. I'm simply confused as to why path expansion delay would ever be desirable.

**Comment by alexburner** [comment]
I'm interested in this too, @mysticatea can you offer any further clarification?
