### ISSUE TITLE
prefer-const not work with mutiple functions

### ISSUE THREAD

**Issue by rupertqin** [eslint/eslint#12514]
## Tell us about your environment

Node version: v10.16.3
npm version: v6.12.0
Local ESLint version: v6.6.0
Global ESLint version: v6.6.0

## What did you expect to happen?
rule of `prefer-const` mess up in multiple function.
the config is:
```
"prefer-const": [
      "warn",
      {
        "destructuring": "all",
        "ignoreReadBeforeAssign": true
      }
    ],
```

file a.js
```
function a (){
  let foo =0;
  foo = 1;
}
function b (){
  let foo =0;
  foo = 1;
}
function c (){
  let foo =0;
  foo = 1;
}
```

will `eslint --fix` output as
```
function a (){
  let foo =0;
  foo = 1;
}
function b (){
  const foo =0;
  foo = 1;
}
function c (){
  const foo =0;
  foo = 1;
}
```
## Are you willing to submit a pull request to fix this bug?
Can't help with resolution.

**Comment by g-plane** [comment]
It seems that I can't reproduce via [online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgXCJwcmVmZXItY29uc3RcIjogW1xuICAgICAgXCJlcnJvclwiLFxuICAgICAge1xuICAgICAgICBcImRlc3RydWN0dXJpbmdcIjogXCJhbGxcIixcbiAgICAgICAgXCJpZ25vcmVSZWFkQmVmb3JlQXNzaWduXCI6IHRydWVcbiAgICAgIH1cbiAgICBdICovXG5cbmZ1bmN0aW9uIGEgKCl7XG4gIGxldCBmb28gPTA7XG4gIGZvbyA9IDE7XG59XG5mdW5jdGlvbiBiICgpe1xuICBsZXQgZm9vID0wO1xuICBmb28gPSAxO1xufVxuZnVuY3Rpb24gYyAoKXtcbiAgbGV0IGZvbyA9MDtcbiAgZm9vID0gMTtcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEwLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).

Can you tell us more detail?

**Comment by rupertqin** [comment]
@g-plane  try this

```
function a() {
  let foo = 0,
    bar = 1;
  foo = 1;
}
function b() {
  let foo = 0,
    bar = 1;
  foo = 1;
}
function c() {
  let foo = 0,
    bar = 1;
  foo = 1;
}
```

**Comment by g-plane** [comment]
Reproduced. [Online demo](https://eslint.org/demo#eyJ0ZXh0IjoiZnVuY3Rpb24gYSgpIHtcbiAgbGV0IGZvbyA9IDAsXG4gICAgYmFyID0gMTtcbiAgZm9vID0gMTtcbn1cbmZ1bmN0aW9uIGIoKSB7XG4gIGxldCBmb28gPSAwLFxuICAgIGJhciA9IDE7XG4gIGZvbyA9IDE7XG59XG5mdW5jdGlvbiBjKCkge1xuICBsZXQgZm9vID0gMCxcbiAgICBiYXIgPSAxO1xuICBmb28gPSAxO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTAsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsicHJlZmVyLWNvbnN0IjoyfSwiZW52Ijp7fX19).

**Comment by yeonjuan** [comment]
May I try this on?

**Comment by g-plane** [comment]
Feel free to do this!

**Comment by kaicataldo** [comment]
@g-plane Can you explain what the bug here is? I'm not sure I understand why the above code being flagged is incorrect.

**Comment by g-plane** [comment]
The bug is about autofix, while problem reports work as intended.

**Comment by kaicataldo** [comment]
Oh, I see - yes, that does look like a bug.
