### ISSUE TITLE
Different lint rules based on last change date

### ISSUE THREAD

**Issue by AlexHayton** [eslint/eslint#12520]
**The version of ESLint you are using.**
6.6.0

**The problem you want to solve.**
I am maintaining a large codebase which has had a very lax set of ESLint rules in the past.  I would like to make the rules much stricter but only on the files we are currently modifying (and hence re-testing) as part of normal maintenance, to reduce the testing overhead of introducing the stricter ruleset.

I would like the ability to use one .eslintrc file for source files with a last commit date later than a certain point, and a different one for general linting (the more lax ruleset).

**Your take on the correct solution to problem.**
As I see it, the simplest solution to this conundrum would be to add a new parameter e.g. `--changedSince` which accepts either a date (YYYY-MM-DD) or a branch name, similar to how `jest --changedSince` works. And it would only lint the files that have changed since that time.

**Are you willing to submit a pull request to implement this change?**
Yes

I'm keen to get a little more feedback on this idea before submitting an RFC. I can see in the replies to https://github.com/eslint/eslint/issues/12363 that this kind of thing wouldn't normally go into core, and could go into another tool instead. So I might make a start by building it that way and then submitting an RFC after exploring the problem space a little further.

**Comment by ilyavolodin** [comment]
There are other tools out there that would do something like this, for example [lint-staged](https://github.com/okonet/lint-staged). I think this is outside of the scope of the responsibilities for ESLint. ESLint accepts a list of files to lint (or a glob), you could always create a script that would check dates of the files, and only pass the ones you want into ESLint. Also, date is very unreliable way of checking for updates.
