### ISSUE TITLE
anyway to ignore parent directory config?

### ISSUE THREAD

**Issue by deadlyicon** [eslint/eslint#12542]
Is there anyway to configure eslint to ignore the configurations in the parent directory / directories? Both `../package.json` and `../.eslingrc.js`.

Thanks!

**Comment by kaicataldo** [comment]
Have you tried the `root: true` option? More information can be found in the documentation [here](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).

**Comment by deadlyicon** [comment]
That a the ` --no-eslintrc` option worked for me. Thank you!
