### ISSUE TITLE
Add merge strategy for 'no-restricted-imports/modules` rule, so we can multiple ones in overrides

### ISSUE THREAD

**Issue by dietergeerts** [eslint/eslint#12549]
**The version of ESLint you are using.** 
v6.4.0

**The problem you want to solve.**
Being able to have the rule `no-restricted-imports/modules` in different overrides with different configs, and have them combined.
Right now, We have config for all files, but some files need others added. The current workaround is to make sure we have a global object to configure the rules for all files, and then use that as base for the overrides that want to add extra rules, but this becomes hard to manage, as we use overrides per use-case, e.g. icon imports, ....

**Your take on the correct solution to problem.**
I think it would be safe if the config is combined by just adding them all together where the rule had been set to error.

**Are you willing to submit a pull request to implement this change?**
I didn't work with the code base yet, and as I have limited time due to sickness, I don't know if I will be able to create a pull-request. If I got help to get me up to speed how and where I can do this in-code, I could give it a try.

**Comment by kaicataldo** [comment]
I don’t think this is a good idea because it makes it impossible to remove paths in configs that inherit from other configs. Please see [this issue ](https://github.com/eslint/eslint/issues/3175) for some relevant discussion.

**Comment by kaicataldo** [comment]
I also want to note that we require changes to core to go through the RFC process outlined [here](https://github.com/eslint/rfcs).

**Comment by dietergeerts** [comment]
> I don’t think this is a good idea because it makes it impossible to remove paths in configs that inherit from other configs.

And now it makes it impossible for multiple extended configs to define their own and have them both applied. There are so many use cases we can come up with for both situations. Imho, it would be a good idea to think about this and find a solution where most use-cases can fit in, no?

Right now, for a lot of projects, there is a lot of config needed to get Eslint fully working with all the rules a project needs. It would be great if this config can easily be shared, but for this to be possible, and thus have smaller re-usable configs that we can compose depending on the needs of the project, we need some kind of merge strategy for config in overrides/extends, either automatic, manual or in between.

To give some background on why we end up with a lot of overrides: Imho, it's always better to whitelist instead of blacklist, and thus, if our project is using e.g. node, but not for all files, we make sure that rules going with node are only applied there, like globals, so we don't make mistakes on those in the other files. I know a lot of peeps just put all together, but I have seen this lead to problems using stuff that must not be used in some files. So our current config exists of almost a clean base config, and +/- 12 overrides, each in it's own file and own scope.
