### ISSUE TITLE
support disabling specific rule fixes

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#12561]
Creating a new issue because the two other issues have been archived without a solution:

* https://github.com/eslint/eslint/issues/7549
* https://github.com/eslint/eslint/issues/5329

(This auto-archiving logic just hides existing issues and discourages community participation in addressing them.)

It was proposed multiple times to add "nofix" configuration.

Ideally, I would like this to be a top-level configuration option, not rule specific, i.e.

```json
{
  "rules": {},
  "noFix": {
  	"react/prefer-read-only-props": true
  }
}

```

This would allow to configure the auto-fix preference without overriding inherited warning/ error levels.

**Comment by g-plane** [comment]
For built-in ESLint rules, you can consider [eslint-plugin-no-autofix](https://github.com/aladdin-add/eslint-plugin/tree/master/packages/no-autofix).

**Comment by gajus** [comment]
Furthermore, having this configuration would allow to allow to add auto-fixing to some of the potentially breaking rules, like https://github.com/eslint/eslint/issues/7714. Currently community has to resolve to patches such as this one https://github.com/leo-buneev/eslint-plugin-sort-keys-fix.

**Comment by platinumazure** [comment]
I like the idea of having a top-level config for this. I wasn't looking forward to trying to integrate this with existing rule config schemas.

I assume the purpose of having an object with true/false values (instead of an array of rule names) is to make it easier to support this in shareable configs and plugin configs, while still allowing end users to override as needed?

**Comment by platinumazure** [comment]
That said, for core change proposals, we require an [RFC](https://github.com/eslint/rfcs) in order to accept a proposal. We can do preliminary discussion in this issue, but could you please create an RFC with a formal proposal when you're ready? Thanks!

**Comment by gajus** [comment]
Sorry, I am not available to write an RFC.
