### ISSUE TITLE
Eslint is still using the cache when an eslint plugin is updated but the .eslintrc file remain the same

### ISSUE THREAD

**Issue by fa93hws** [eslint/eslint#12578]
**Tell us about your environment**
Not related

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**
Not related

**Please show your full configuration:**
Not related

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
`eslint --cache --cache-location .eslintcache`
(took 4~5 minutes)
`eslint --cache --cache-location .eslintcache`
(took few seconds)
yarn install --dev eslint-plugin-react-hooks
(2.2.0 -> 2.3.0)
`eslint --cache --cache-location .eslintcache`
(took few seconds)
`eslint --cache --cache-location .eslintcache`
(took few seconds)

**What did you expect to happen?**
`eslint --cache --cache-location .eslintcache` after version change of any plugins should not using the cache at all.

**What actually happened? Please include the actual, raw output from ESLint.**
It's still using the cache..

**Are you willing to submit a pull request to fix this bug?**
Yes, but maybe after some discussion.
currently there is a workaround to include the hash of the `yarn.lock` or something equivlent to the cache filename.
But I am more towards to have a flag to do something like
"hey, the old cache is not valid any more, let's create a new one and overwrite the old one"

**Comment by jgreen210** [comment]
I ran into stale cache problems when upgrading babel-eslint to fix https://github.com/eslint/eslint/issues/12117. I had to delete the cache to make the babel-eslint upgrade work.

This was with eslint 6.7.1, upgrading babel-eslint from 10.0.1 to 10.0.3. The cache was probably created with eslint 6.5.1, if that matters.

**Comment by kaicataldo** [comment]
Sorry for the delay in response here!

> But I am more towards to have a flag to do something like
"hey, the old cache is not valid any more, let's create a new one and overwrite the old one"

Just so I understand, are you proposing a new CLI flag that would bust the cache and create a new cache file?

**Comment by kaicataldo** [comment]
Also, I don't think this is a bug, since I don't think it's an expectation that ESLint should know about when plugins change. That being said, I do think is worth exploring as an enhancement.

One other thought - when using the cache, could we track the versions of plugins loaded and use that to bust the cache? Not sure what kind of performance implications this would have, since it would be reading from the file system in `node_modules.`

**Comment by platinumazure** [comment]
I would love to see an RFC for this-- I really think this is something we should look at, but as with all core changes, we want to make sure we come up with the best design we can.

If anyone is interested, please feel free to submit an RFC as an issue here: https://github.com/eslint/rfcs. Thanks!

**Comment by jgreen210** [comment]
Parsing package-lock.json, npm-shrinkwrap.json or yarn.lock, extracting list of all packages that matter (eslint itself, plugins, babel-eslint,...) and including fingerprint of all their versions in part of cache path would solve this I think. Cache wouldn't be invalidate too often. 

Requiring some flag for correct operation in some cases would not be what anyone is expecting to happen.
