### ISSUE TITLE
@typescript-eslint/no-unused-vars autofix

### ISSUE THREAD

**Issue by qiuguixin** [eslint/eslint#12589]
Tell us about your environment

**ESLint Version: 5.14.1
Node Version: 8.12.0
npm Version: 6.4.1**

**The problem you want to solve.**
fix vars which defined but never used. 
rules: eslint(@typescript-eslint/no-unused-vars)
can we add a autofix feature to auto fix this problem.
 

**Your take on the correct solution to problem.**
I solved these problems manually.

![image](https://user-images.githubusercontent.com/16093668/69400879-31009580-0d2e-11ea-8049-5cdc018d2f41.png)
can we add a autofix feature to auto fix this problem.

**Comment by kaicataldo** [comment]
`@typescript-eslint/no-unused-vars` is a rule in the [typescript-eslint repository](https://github.com/typescript-eslint/typescript-eslint). Please make an issue there.

**Comment by platinumazure** [comment]
Closing as this is not an ESLint issue. Thanks for contributing!
