### ISSUE TITLE
eqeqeq : documentation is misleading : rule is not autofixable

### ISSUE THREAD

**Issue by aymericbouzy** [eslint/eslint#12583]
**The version of ESLint you are using.**
v5.16.0

**The problem you want to solve.**
Documentation https://eslint.org/docs/rules/eqeqeq says rule eqeqeq is auto-fixable, whereas it isn't (as mentionned in https://github.com/eslint/eslint/issues/4578)

**Your take on the correct solution to problem.**
Update documentation

**Are you willing to submit a pull request to implement this change?**
Yes!

**Comment by ilyavolodin** [comment]
`eqeqeq` does have some autofixing. It's very limited to either `typeof` comparisons or comparisons where both sides contain literal. Here's the link to the comment in the code: https://github.com/eslint/eslint/blob/master/lib/rules/eqeqeq.js#L140

**Comment by aymericbouzy** [comment]
oh I see. Maybe I can update the documentation to specify when the autofixing happens?

**Comment by kaicataldo** [comment]
Contributions clarifying documentation are definitely welcome!

**Comment by aymericbouzy** [comment]
Actually it is already mentioned in the documentation, I simply didn't see it 😳

> The --fix option on the command line automatically fixes some problems reported by this rule. A problem is only fixed if one of the operands is a typeof expression, or if both operands are literals with the same type.

Sorry for that.
