### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by CharlyPoppins** [eslint/eslint#12584]
**Tell us about your environment** 

* **ESLint Version:** v.6.6.0
* **Node Version:** v12.4.0
* **npm Version:** 6.13.0

**What parser (default, Babel-ESLint, etc.) are you using?** @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
    "env": {
        "browser": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
    "plugins": ["@typescript-eslint/eslint-plugin"],
    "rules": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// Somewhere in the file I have got
this.myFunction(if).then(
    (object: MyInterface) => {
            //
    },
    (error: any)  => {
            //
     },
)
// if i change MyInterface to any, there is no nug
```

```bash
node_modules/eslint/bin/eslint.js myFile.ts
```

**What did you expect to happen?**
Give me an handled error return :)

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
TypeError: Cannot read property 'type' of undefined
Occurred while linting **myFile.ts:1
    at isForInRef (node_modules/eslint/lib/rules/no-unused-vars.js:423:24)
    at node_modules/eslint/lib/rules/no-unused-vars.js:460:21
    at Array.some (<anonymous>)
    at isUsedVariable (node_modules/eslint/lib/rules/no-unused-vars.js:459:40)
    at collectUnusedVariables (node_modules/eslint/lib/rules/no-unused-vars.js:570:26)
    at collectUnusedVariables (node_modules/eslint/lib/rules/no-unused-vars.js:577:17)
    at Program:exit (/node_modules/eslint/lib/rules/no-unused-vars.js:589:36)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Are you willing to submit a pull request to fix this bug?**
Did not manage to fix it. Maybe you can give me a lead.

**Comment by kaicataldo** [comment]
The core rules aren't guaranteed to work with TypeScript. You'll want to use the [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin).

**Comment by CharlyPoppins** [comment]
As you can see in my eslint config I'm using @typescript-eslint/eslint-plugin as plugin.
I'll post an issue on their repo, thanks.

**Comment by g-plane** [comment]
You may need to check out: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md .

**Comment by CharlyPoppins** [comment]
I wasn't but I do now. 
Error is still triggered,  I continue my research
