### ISSUE TITLE
Suggestion data

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12606]
**The version of ESLint you are using.**

6.7.1

**The problem you want to solve.**

A couple of things I noticed while working on #12591:

* It isn't documented that a suggestion object should have its own `data` property for interpolation.  This is probably intuitive for most people, but I was still initially expecting the base `data` object from `context.report({ data: {} })` to be used for all messages including suggestions, not just for the main error message.
* Rule tester doesn't support interpolation for suggestions' messages. You can test either `desc` (the final text) or just `messageId`, but not `messageId` + `data`. If you pass `messageId` and `data`, the tester will check just `messageId` and ignore `data`, which is different from how it works with error messages.

**Your take on the correct solution to problem.**

*  It might be nice to clarify suggestion `data` in `working-with-rules.md`.
* Improve rule tester to use suggestion's `data` provided in a test in the same way as it works with error's `data`: interpolate and compare final messages.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by mdjermanovic** [comment]
This seems to have enough votes, but since it's a core enhancement I think it needs to be accepted by a  TSC member?

**Comment by mysticatea** [comment]
To me, this looks like a bug that our tester cannot test suggestions with `messageId` + `data`.

**Comment by ilyavolodin** [comment]
Agree. I think it's just something that we missed in the original feature PR. Don't think it needs to go through TSC, also it's already up-voted by 3 members of TSC, so I think we should be good.

**Comment by mdjermanovic** [comment]
I'm working on the rule tester now. Looks like this issue can be marked as accepted?

There is one problem - the actual version allows `desc` and `messageId` in the same test. Even [the example](https://eslint.org/docs/developer-guide/nodejs-api#testing-suggestions) has both fields. 

This is different from the error tests validation (`message` and `messageId` can't be defined on the same error object), but to disallow the same in the suggestion test objects looks like a breaking change now?


The solution might be to keep the current behavior (allow `desc` + `messageId` and test both if present against the actual result), but disallow `desc` + `data`. That shouldn't be a breaking change because `data` isn't specified in the API and isn't implemented yet.
