### ISSUE TITLE
Missing documentation about custom formatters [$10]

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#1260]
Since #172 ESLint can load custom formatters by path but I can’t find any documentation about that feature.
A "Working with Formatters" page, which explains how to write a custom formatter, would be nice too.

**Comment by Dashed** [comment]
+1. At the moment, there's documentation on loading formatters via CLI. It's unclear if it can be set via config file.

**Comment by nzakas** [comment]
It cannot. Formatters must be specified on the command line.

**Comment by nzakas** [comment]
@dashed there is documentation as part of the CLI docs: http://eslint.org/docs/command-line-interface/#-f,---format

**Comment by royriojas** [comment]
Hi guys, I wrote a wiki page on the matter https://github.com/royriojas/eslint-friendly-formatter/wiki/Writing-a-custom-eslint-formatter until you have proper documentation for the formatters, it might help others to understand how to write their own reporters

**Comment by IanVS** [comment]
@royriojas Since you've created a formatter and even made a writeup, would you be willing to submit a PR to add documentation to the eslint.org site?

**Comment by royriojas** [comment]
sure @IanVS, but where should that be? any guidance on where add it would be nice

**Comment by IanVS** [comment]
My guess would be a new file `working-with-custom-formatters.md` in https://github.com/eslint/eslint/tree/master/docs/developer-guide.

@nzakas @ilyavolodin ?

**Comment by ilyavolodin** [comment]
Yes, that sounds right. I will add it to website menus after it's checked in and release is published.

**Comment by lo1tuma** [comment]
@royriojas There is a bounty for this issue, which is still not claimed: https://www.bountysource.com/issues/4345778-missing-documentation-about-custom-formatters

**Comment by royriojas** [comment]
@lo1tuma thanks, I claimed it!
