### ISSUE TITLE
v6.7.0 broke autofixing for eslint-plugin-react

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#12614]
Tests pass on master in https://github.com/yannickcr/eslint-plugin-react on v6.6, and fail on v6.7.0 or v6.7.1. https://travis-ci.org/yannickcr/eslint-plugin-react/jobs/616996307 is an example of the failures; they're related to whitespace placement, within jsx.

I'm not sure which item in the [changelog](https://github.com/eslint/eslint/blob/master/CHANGELOG.md) might be responsible, but perhaps #12491 (cc @kaicataldo)?

The change doesn't need to be reverted if i have a reliable way in the react plugin to detect the different behavior, but I suspect that's also difficult.

**Comment by mysticatea** [comment]
Thank you for your report.

I confirmed it.
As you mentioned, #12491 has changed the behavior of the `isSpaceBetweenTokens()` method about JSXText tokens that contain only spaces.
