### ISSUE TITLE
--strict mode flag to treat warnings as errors

### ISSUE THREAD

**Issue by osdiab** [eslint/eslint#12618]
**The version of ESLint you are using.**
6.6.0

**The problem you want to solve.**
https://github.com/facebook/create-react-app by default treats warnings as warnings while you're developing, but as errors if the `CI` flag is set to `true`.

To follow the same conventions on my packages that aren't `create-react-app` apps, I would love to be able to flip that flag easily with the `eslint` CLI, but it's not convenient - they do it by [hooking into eslint through webpack and inspecting the warnings array directly](https://github.com/facebook/create-react-app/blob/4582491a8b46be6c98c0934df1fb7ae81c95f6c1/packages/react-scripts/scripts/build.js#L198), but I'd love to be able to do it without having to jump through so many hoops.

Given that a pretty major project is using this, I think it's worth revisiting the decision to not provide this.

This was requested and denied back in 2015: https://github.com/eslint/eslint/issues/2309

**Your take on the correct solution to problem.**

A `--strict` flag (or named otherwise) that makes warnings cause `eslint` to return a non-success status code

**Are you willing to submit a pull request to implement this change?**
I don't really know how ESLint works internally, but I can give it a go

**Comment by osdiab** [comment]
Current workaround is the last comment in that issue.

https://github.com/eslint/eslint/issues/2309#issuecomment-286649686

**Comment by platinumazure** [comment]
Have you tried using `--max-warnings 0`? That's more or less the same thing, isn't it?

**Comment by osdiab** [comment]
@platinumazure ah I didn’t realize that was a thing, thanks for pointing it out to me!
