### ISSUE TITLE
Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by Rotinx** [eslint/eslint#12623]
**Tell us about your environment**

Node version: v10.16.3
npm version: v6.13.1
Local ESLint version: v6.7.1
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint-config-airbnb-base

**Please show your full configuration:**

```js
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: [
    'airbnb-base',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  rules: {
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const test = 's';
```

```bash
./node_modules/.bin/eslint --init (Then it automatically starts I believe via the extension or something.)
```

**What did you expect to happen?**
For eslint to start linting.

**What actually happened? Please include the actual, raw output from ESLint.**
I've been encountering this issue while trying to setup eslint with airbnb. Using this npx package.
https://www.npmjs.com/package/eslint-config-airbnb-base

ESlint output
```bash
Failed to load plugin 'import' declared in 'server\.eslintrc.js » eslint-config-airbnb-base » Z:\Development\JS\Nuxt-Test-App\zuka-ma-shlong\server\node_modules\eslint-config-airbnb-base\rules\imports.js': Cannot find module 'eslint-plugin-import'
```
package.json
```json
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "eslint": "6.1.0",
    "eslint-config-airbnb-base": "14.0.0",
    "eslint-plugin-import": "^2.18.2",
    "express": "^4.17.1"
  }
}
```
.eslintrc.js
```js
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  extends: [
    'airbnb-base',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
  },
  rules: {
  },
};
```
eslint-plugin-import is however installed locally aswell as eslint. 

I've attempted installing the package with yarn which also didn't seem to work either. [Issue link](https://github.com/facebook/create-react-app/issues/6391)

At this point I've ran out of ideas to get this working.

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by aladdin-add** [comment]
what's the output after running `npm ls eslint eslint-config-airbnb-base eslint-plugin-import`?

**Comment by Rotinx** [comment]
![image](https://user-images.githubusercontent.com/39930952/69903656-5f9f0000-1401-11ea-909a-00d4cef9c4f8.png)

**Comment by aladdin-add** [comment]
emm.. not sure what happened -- I was not able to repro it.

>  Local ESLint version: v6.7.1

just noticed the eslint v6.7.1 in OP, but actual insalled eslint v6.1.0. can you retry to make a clean install:
```bash
$ rm -rf node_modules package-lock.json
$ npm i
```

**Comment by Rotinx** [comment]
![image](https://user-images.githubusercontent.com/39930952/69904382-e3111f00-140a-11ea-8208-9b7c184f6e26.png)
![image](https://user-images.githubusercontent.com/39930952/69904385-ea382d00-140a-11ea-8089-0187aca4bf65.png)

Still not working, restarted vs code to make sure. Good catch though I didn't notice that.

**Comment by aladdin-add** [comment]
seems like npm's issue to me -:) can you provide a repo(with package-lock.json) please?

**Comment by Rotinx** [comment]
um thats really werid I just created a new folder and it works fine.

**Comment by Rotinx** [comment]
I'll upload the project that I had issues with.

**Comment by Rotinx** [comment]
https://github.com/Rotinx/broken

**Comment by aladdin-add** [comment]
(o_ _)ﾉ  works fine on my computer.

anyway, glad to see it works!

**Comment by Rotinx** [comment]
so weird I appreciate your help.
