### ISSUE TITLE
Update: rule 'padding-line-between-statements' - add number of lines

### ISSUE THREAD

**Issue by IgorNovozhilov** [eslint/eslint#12634]
[x] Documentation update
 [x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
 [x] Add autofixing to a rule

**What rule do you want to change?**

<https://eslint.org/docs/rules/padding-line-between-statements>

**Does this change cause the rule to produce more or fewer warnings?**

No, the number of warnings will remain the same.

**How will the change be implemented? (New option, new default behavior, etc.)?**

For this rule, the set of possible options for using the `blankLine` parameter
    will be expanded by adding the ability to specify the required number of blank lines.

**Please provide some example code that this change will affect:**

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

"use strict";


class A {}


function b() {}
```

**What does the rule currently do for this code?**

Currently, you cannot specify the required number of blank lines.

**What will the rule do after it's changed?**

The rule will start using the number of blank lines only after setting the `blankLine` parameter to a numeric value.
In this case, the problem will be displayed if the number of blank lines is greater than or less than the specified value.

**What changes did you make? (Give an overview)**

1.  Added ability to specify numeric value in `meta.schema.definitions.paddingType`
2.  Added a new message view with the number of blank lines
3.  Added to `function verifyForAlways` output of new messages depending on `blankLine` parameter
4.  Changed the "rule fixer" so that it could replace blocks in the code with the required number of blank lines
5.  In `function getPaddingLineSequences` added search the current number of blank lines to display in the problem message
6.  Updated tests and documentation

**Is there anything you'd like reviewers to focus on?**

Do I need to cover any other cases with tests?

**Example**
This change will improve the readability of the source code by highlighting the concept blocks.
And it will also automate the process of formatting.

Here is an example of the configuration I plan to use with these updates:

```js
  "rules": {
    "lines-between-class-members": "error",
    "padding-line-between-statements": [
      "error",
      { "blankLine": 1, "prev": "*", "next": ["cjs-import", "cjs-export"] },
      { "blankLine": 1, "prev": ["cjs-import", "cjs-export"], "next": "*" },
      { "blankLine": 2, "prev": "expression", "next": ["cjs-import", "cjs-export"] },
      { "blankLine": 2, "prev": ["cjs-import", "cjs-export"], "next": "expression" },
      { "blankLine": 2, "prev": "*", "next": ["class", "function"] },
      { "blankLine": 2, "prev": ["class", "function"], "next": "*" },
      { "blankLine": 1, "prev": ["directive", "const", "let"], "next": "expression" },
      { "blankLine": 1, "prev": "expression", "next": ["const", "let", "return"] },
      { "blankLine": "never", "prev": "cjs-import", "next": "cjs-import" },
      { "blankLine": "never", "prev": "cjs-export", "next": "cjs-export" }
    ],
    "padded-blocks": [
      "error",
      { "blocks": "never", "classes": "always", "switches": "never" },
      { "allowSingleLineBlocks": true }
    ]
  }
```

Before `eslint . --fix`

```js
'use strict'
const any = require('any')
const { any2 } = require('any2')
const CONST1 = 'CONST1'
const CONST2 = 'CONST1'
/**
 * My class
 */
class Test {
  constructor() {
    this.a = any + any2 + CONST1
  }
  any(a) {
    let anyText = 'any'
    if (a) {
      anyText = 'a' + CONST2
    }
    return anyText
  }
}
/**
 * My function
 */
function test() {
  const t = new Test()
  console.log(t)
  return t
}
console.log('any' + test())
module.exports.Test = Test
module.exports.test = test
```

After `eslint . --fix`

```js
'use strict'

const any = require('any')
const { any2 } = require('any2')

const CONST1 = 'CONST1'
const CONST2 = 'CONST1'


/**
 * My class
 */
class Test {

  constructor() {
    this.a = any + any2 + CONST1
  }

  any(a) {
    let anyText = 'any'
    if (a) {
      anyText = 'a' + CONST2
    }
    return anyText
  }

}


/**
 * My function
 */
function test() {
  const t = new Test()

  console.log(t)

  return t
}


console.log('any' + test())


module.exports.Test = Test
module.exports.test = test
```

**PR:** https://github.com/eslint/eslint/pull/12663

**Comment by kaicataldo** [comment]
I support this change.

**Comment by kaicataldo** [comment]
For posterity, I want to note that this can conflict with [no-multiple-empty-lines](https://eslint.org/docs/rules/no-multiple-empty-lines), though I don't think that's an issue since this isn't the default behavior.

Hopefully some other members of the team can give their opinion on this proposal.

**Comment by yeonjuan** [comment]
> This change will improve the readability of the source code by highlighting the concept blocks.

I agree with this change. 👍

**Comment by mdjermanovic** [comment]
How would the rule treats comments between, e.g.,:

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

"use strict";

/**/

class A {}

/**/

function b() {}
```

**Comment by IgorNovozhilov** [comment]
@mdjermanovic, this behavior remains the same as before. I made sure that all the old tests were running successfully.

"comment" is not an "expression", and when evaluating whether there is an empty line, the comment is appended to the next expression, and the empty line is counted from the comment to the higher expression.

The code after `--fix` will look like this:
```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

"use strict";


/**/

class A {}


/**/

function b() {}
```

**Comment by mdjermanovic** [comment]
Tried how #12663 works, it seems that the logic is to require at least one occurrence of exactly n consecutive blank lines anywhere between two statements?

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";

// Invalid: 1 above, 1 below

class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";



// Invalid: 3 above, 1 below

class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";

// Invalid: 1 above, 3 below



class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";


// Valid: 2 above, 1 below

class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";

// Valid: 1 above, 2 below


class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";



// Valid: 3 above, 2 below


class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";


// Valid: 2 above, 3 below



class A {}
```

```js
/*eslint padding-line-between-statements: ["error", 
    { blankLine: 2, prev: "*", next: "class" }]
*/

"use strict";

// Valid: 1 above this comment, 2 between comments, 1 below the second comment


//

class A {}
```

**Comment by IgorNovozhilov** [comment]
> require at least one occurrence of exactly n consecutive blank lines anywhere between two statements?

@mdjermanovic. Yes. This rule does not define empty lines for comments, it considers comments to be part of one of the expression.
There is a separate rule for comments `lines-around-comment`, but it doesn't work exactly as expected.
A full-fledged unified proposal on this issue has not yet been announced:
https://github.com/eslint/eslint/issues/11129#issuecomment-536327392

> PS: For myself, I wanted to implement the `padding-lines/padded-scope` rule in the future, but without a confirmed offer, so far only in the form of a external plugin

**Comment by mdjermanovic** [comment]
I agree there are certain problems with comments and line padding rules, just have concerns that this enhancement might introduce some new ones.

For instance, someone might complain about why is a code like the following invalid by this rule:

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 1, prev: "*", next: "function" },
    { blankLine: 1, prev: "function", next: "*" },
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

//------------------------------------------------------------------------------
// Functions
//------------------------------------------------------------------------------

function f() {
    // ...
}

function g() {
    // ...
}

//------------------------------------------------------------------------------
// Classes
//------------------------------------------------------------------------------

class A {
    // ...
}


class B {
    // ...
}
```

Also, error highlights `class A` with `"Before this statement there are 1 blank line. Allowed is 2"`  , but the code gets auto-fixed to:

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 1, prev: "*", next: "function" },
    { blankLine: 1, prev: "function", next: "*" },
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

//------------------------------------------------------------------------------
// Functions
//------------------------------------------------------------------------------

function f() {
    // ...
}

function g() {
    // ...
}


//------------------------------------------------------------------------------
// Classes
//------------------------------------------------------------------------------

class A {
    // ...
}


class B {
    // ...
}
``` 

The following would be also invalid (at `class C`):

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

//------------------------------------------------------------------------------
// Some Classes
//------------------------------------------------------------------------------

class A {
    // ...
}


class B {
    // ...
}

//------------------------------------------------------------------------------
// Some Other Classes
//------------------------------------------------------------------------------

class C {
    // ...
}


class D {
    // ...
}
```

Another example:

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

//#region Some Classes

class A {
    // ...
}


class B {
    // ...
}

//#endregion

//#region Some Other Classes

class C {
    // ...
}


class D {
    // ...
}

//#endregion
```

gets auto-fixed to:

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

//#region Some Classes

class A {
    // ...
}


class B {
    // ...
}


//#endregion

//#region Some Other Classes

class C {
    // ...
}


class D {
    // ...
}

//#endregion
```

Thoughts about these examples? Is this a correct behavior at the moment given that the rule doesn't apply to comments, or should this be already treated as a bug (and if so how could we fix it, i.e. what would be the correct behavior).

**Comment by IgorNovozhilov** [comment]
@mdjermanovic
> Also, error highlights class A with "Before this statement there are 1 blank line. Allowed is 2" , but the code gets auto-fixed to:...

> The following would be also invalid (at class C): ...

I think this is normal behavior and separators should also be included in checking empty lines. Such separators do not have a special type and do not stand out among other comments.


> Another example:... gets auto-fixed to:...

I don't see any way to solve this problem other than making a new rule that will count empty lines between comments.
With automatic correction, you can't guess which comments to insert empty lines between, so by default they are inserted before the first one.
However, the developer can manually specify where the indent will be, and the check will be performed correctly:
```js
/* eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
] */

// #region Some Classes

class A {
  // ...
}


class B {
  // ...
}

// #endregion


// #region Some Other Classes

class C {
  // ...
}


class D {
  // ...
}

// #endregion
```

PS: I think that for the new rule `padding-lines`, we can provide not only single-line and multi-line comments, but also delimiter-comment, and set specific rules for them for empty lines.
