### ISSUE TITLE
The radix rule should provide fixers

### ISSUE THREAD

**Issue by stof** [eslint/eslint#12649]
**What rule do you want to change?** `radix`

**Does this change cause the rule to produce more or fewer warnings?** no

**How will the change be implemented? (New option, new default behavior, etc.)?** implementing the fixer

**Please provide some example code that this change will affect:**

```js
/*eslint radix: "error"*/

var num = parseInt("071");

/*eslint radix: ["error", "as-needed"]*/

var num = parseInt("071", 10);
```

**What does the rule currently do for this code?**
it reports problems in both cases, but requires fixing manually

**What will the rule do after it's changed?**
It should at least be able to fix the `Redundant radix` error, as there is only one valid way to perform it (removing the second argument).

For the `missing radix` (when using the default `always` configuration), I think it would also be fine to implement a fix adding a second argument with value `10`, as that's the expected behavior.

**Are you willing to submit a pull request to implement this change?**
I might try, but I have no experience writing rules and fixers for them.

**Comment by platinumazure** [comment]
I would love to see the user experience improve here for sure.

My only question is whether some or all of the messages this rule reports might have multiple possible fixes. If so, those messages should probably use our new Suggestions feature, rather than a single autofix.

**Comment by stof** [comment]
Well, the `Invalid radix` might have multiple ways to fix it, but I don't think any of them could be suggested (as the cause is a bug in the code that probably require a dev to look at it). The case of having no argument at all won't be fixable either.
But I think it is fine to have 2 fixable problems and 2 non-fixable problems in the rule rather than 4 non-fixable problems.

**Comment by kaicataldo** [comment]
> But I think it is fine to have 2 fixable problems and 2 non-fixable problems in the rule rather than 4 non-fixable problems.

There's a lot of precedence for this in the core rules, and I agree!

> It should at least be able to fix the Redundant radix error, as there is only one valid way to perform it (removing the second argument).

:+1:

> For the missing radix (when using the default always configuration), I think it would also be fine to implement a fix adding a second argument with value 10, as that's the expected behavior.

I think this should be added as a `suggestion` rather than an autofix, as it's a reasonable assumption, but not something ESLint can be sure of.

**Comment by mdjermanovic** [comment]
> It should at least be able to fix the Redundant radix error, as there is only one valid way to perform it (removing the second argument).

This fix can potentially change behavior, as `parseInt(x)` is not always the same as `parseInt(x, 10)`. Though I think that in ES5+ env the only difference is when the string starts with `0x` or `0X`, and given that the user has opted-in to disallow `10` it might make sense to do auto-fix. Or it might be safer to report a `suggestion` instead?

> For the missing radix (when using the default always configuration), I think it would also be fine to implement a fix adding a second argument with value 10, as that's the expected behavior.

It's most likely `10` when the argument is variable, but if it is a constant (a string literal), `10` might be the least expected?

**Comment by kaicataldo** [comment]
Given what @mdjermanovic listed above, I think suggestions might be the best course of action for both these cases.

We don’t want to make any assumptions in autofixing, because many users run auto fixing on save or as a pre-commit hook.

**Comment by stof** [comment]
> This fix can potentially change behavior, as `parseInt(x)` is not always the same as `parseInt(x, 10)`. Though I think that in ES5+ env the only difference is when the string starts with `0x` or `0X`, and given that the user has opted-in to disallow `10` it might make sense to do auto-fix. Or it might be safer to report a `suggestion` instead?

Well, for the error about redundant radix, the project has already explicitly opted-in for omitting the `10` radix. And removing the second argument is the only way to get linting green. The only alternative suggestion we could have is adding a `eslint-disable` annotation, which does not make sense as a suggestion IMO.
But I'm fine with making them suggestions.
