### ISSUE TITLE
Optional Chaining and Nullish coalescing Operator arrived at Stage 4

### ISSUE THREAD

**Issue by g-plane** [eslint/eslint#12642]
**The version of ESLint you are using.**
6.7

**The problem you want to solve.**
Support two new ES features: Optional Chaining and Nullish coalescing Operator.

**Your take on the correct solution to problem.**
- [x] **ESTree:** https://github.com/estree/estree/pull/204 and https://github.com/estree/estree/pull/211
- [x] **Acorn:** https://github.com/acornjs/acorn/pull/890 and https://github.com/acornjs/acorn/pull/891
- [x] **eslint-visitor-keys:** https://github.com/eslint/eslint-visitor-keys/pull/12
- [ ] **Espree:** https://github.com/eslint/espree/pull/441 and https://github.com/eslint/espree/pull/446
- [ ] **ESLint:** https://github.com/eslint/eslint/pull/13196 and https://github.com/eslint/eslint/pull/13416

*(Template inspired by Issue 12629)*

**Comment by franktopel** [comment]
When can we hope to get this? optional chaining is a highly desirable feature, and since we dropped Babel we're waiting for Acorn to support this, so webpack can support it as well :)

**Comment by kaicataldo** [comment]
We're currently also waiting for Acorn to support this (our default parser, Espree, wraps Acorn), and that work is currently blocked by https://github.com/estree/estree/pull/204.

**Comment by DaniGuardiola** [comment]
I encountered [this](https://github.com/eslint/eslint/issues/11045) problem and figured this is the right place to mention it :)

As per [this](https://github.com/babel/eslint-plugin-babel/issues/185#issuecomment-547368879) comment: 

> Closing as this is currently unsupported. If optional chaining becomes a Stage 4 ECMAScript proposal, we could reopen this and make any necessary changes to the core rule. Thanks!

**Comment by NemoStein** [comment]
As I understand, we are waiting for Optional Chaining syntax to be added to ESTree to merge this PR.
@mysticatea may correct me if I'm wrong (sorry to bug you)...

**Comment by NemoStein** [comment]
Does [this](https://github.com/eslint/eslint/pull/13196#issuecomment-642491517) means this issue can be closed?

**Comment by kaicataldo** [comment]
Not yet. This will be closed when we integrate these upstream changes into ESLint core.

**Comment by NemoStein** [comment]
Right, makes sense...
Just to be sure, Optional Chaining is included in Acorn by that PR?
There was a lot of back and forth about it and I'm not sure even if Nullish coalescing Operator is in ESLint now... =|

**Comment by kaicataldo** [comment]
> Just to be sure, Optional Chaining is included in Acorn by that PR?

The ESTree spec was just finalized yesterday, so it's going to take a little bit of time to get everything updated downstream. Hopefully we'll be able to get it out in the next release.

> There was a lot of back and forth about it and I'm not sure even if Nullish coalescing Operator is in ESLint now... =|

Nullish coalescing operator was included in the latest release ([v7.2.0](https://eslint.org/blog/2020/06/eslint-v7.2.0-released)).

**Comment by Lonniebiz** [comment]
Should this issue remain open? While Nullish coalescing maybe supported, I have confirmed that **Optional Chaining is not supported in (the latest) eslint 7.6.0**.

**Comment by SebastianSimon** [comment]
@Lonniebiz It works in the online demo. What input code are you using and which warning or error do you see?

**Comment by Lonniebiz** [comment]
Earlier, I tested some code that looked like this:
```
	let obj = {};
	if (obj.data?.length === 0)
	{
		console.log(obj);
	}
```
I got some error griping about `?.` However, now when I try it, it works. Maybe when I changed `eslint.parserOptions.ecmaVersion` from 2018 to 2020 it didn't take effect right away. Not sure, but thanks for the reply, which cause me to try it again and experience it working. Glad to see this one!

**Comment by sevor005** [comment]
Good afternoon! Have you added support for optional chaining to eslint? If not added, which version will support it? Thanks!

**Comment by marktaiwan** [comment]
> Good afternoon! Have you added support for optional chaining to eslint? If not added, which version will support it? Thanks!

Support for optional chaining was added in v7.5.0
https://eslint.org/blog/2020/07/eslint-v7.5.0-released

**Comment by sevor005** [comment]
> > Good afternoon! Have you added support for optional chaining to eslint? If not added, which version will support it? Thanks!
> 
> Support for optional chaining was added in v7.5.0
> https://eslint.org/blog/2020/07/eslint-v7.5.0-released

Thank you very much!
