### ISSUE TITLE
How to handle Definition for rule xx was not found

### ISSUE THREAD

**Issue by YuunYang** [eslint/eslint#12656]
## Configuration:
```json
{
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true
    }
  },
  "rules": {
    "semi": "2"
  }
}
```
## Actual source code causing the issue
```javascript
function getEslintReport(code){
  linter.defineRules({
    "wizard/action-checker": {
    create(context) {
      return {
        "semi": 1
      }
    }},
    "wizard/nightwatch-execute": {
      create(context) {
        return {
          "semi": 1
        }
      }
    }
  });
  const cli = new CLIEngine({
    configPath: path.resolve(process.cwd(), '.eslintrc.json')
  });
  const config = cli.getConfigForFile();
  const res = linter.verify(code, config);
  console.log(res);
}
getEslintReport(`import React, {Component} from 'react';`)
```
## Expection
I want it just return
```shell
 [{ ruleId: 'no-unused-vars',
    severity: 1,
    message: '\'React\' is defined but never used.',
    line: 1,
    column: 8,
    nodeType: 'Identifier',
    endLine: 1,
    endColumn: 13 },
  { ruleId: 'no-unused-vars',
    severity: 1,
    message: '\'Component\' is defined but never used.',
    line: 1,
    column: 16,
    nodeType: 'Identifier',
    endLine: 1,
    endColumn: 25 } ]
```
## Actually happen
It returns many error message like this
```
{ ruleId: 'jsx-a11y/heading-has-content',
    severity: 1,
    message:
     'Definition for rule \'jsx-a11y/heading-has-content\' was not found',
    line: 1,
    column: 1,
    nodeType: null }
```
![image](https://user-images.githubusercontent.com/15278220/70591499-538d1c80-1c11-11ea-9030-c0a48a0d3772.png)
## What I have try
I find a similar problem #12030 , and find your [reply](https://github.com/eslint/eslint/issues/12030#issuecomment-516266124), it helped, but I think it is too complicated, because I have dozens of rules that `Not Defined`, so I need to manually add those one by one? or I need to use another way

**Comment by mysticatea** [comment]
Well, I guess that the `linter` object in your code is not related to the `CLIEngine` instance. ESLint doesn't have the global registry of rules. You need to add rule definitions to your `CLIEngine` instance.

Also, you should use `CLIEngine#executeOnText()` or `CLIEngine#executeOnFiles()` rather than `Linter#verify()`. The `Linter` class is the extracted parts for browsers, so it doesn't support some functionality of ESLint.

```js
const engine = new CLIEngine()

// For files
{
    const { results } = engine.executeOnFiles(["path/to/a-file.js"])
    console.log(results)
}

// For text
{
    const { results } = engine.executeOnText(`import React, {Component} from 'react';`, "path/to/a-file.js")
    console.log(results)
}
```

With the above, `CLIEngine` instance loads config files that are related to `path/to/a-file.js` and lints the file or given code.

**Comment by YuunYang** [comment]
Thanks a lot for your reply of your busy schedule. It really helped me, I'm so lucky to be the user of this project. Thanks again.
