### ISSUE TITLE
.mjs and .cjs files should override sourceType

### ISSUE THREAD

**Issue by LJNeon** [eslint/eslint#12675]
**The version of ESLint you are using.**
6.7.2

**The problem you want to solve.**
`.mjs` and `.cjs` files aren't correctly parsed when the `sourceType` configuration conflicts.

**Your take on the correct solution to problem.**
I understand that there is currently a workaround using [glob-based configuration overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns), but `.mjs` files will always be modules and `.cjs` files will always be scripts, so I believe this override should be the default behavior for those, and `sourceType` should only affect `.js` files.

**Are you willing to submit a pull request to implement this change?**
I lack the knowledge of eslint internals needed to do so.

**Comment by kaicataldo** [comment]
Would you mind creating an [RFC](https://github.com/eslint/rfcs) for this proposal, since it's an enhancement to core? I think this would be a nice enhancement, personally.
