### ISSUE TITLE
Please include the ability to configure indent on conditional expressions

### ISSUE THREAD

**Issue by t-rad679** [eslint/eslint#12674]
**What rule do you want to change?**
indent

**Does this change cause the rule to produce more or fewer warnings?**
more

**How will the change be implemented? (New option, new default behavior, etc.)?**
new option

**Please provide some example code that this change will affect:**

Existing:
```js
        'indent': [
            'error',
            4,
            {
                'CallExpression': {
                    'arguments': 2,
                },
                'FunctionDeclaration': {
                    'body': 1,
                    'parameters': 2,
                },
                'FunctionExpression': {
                    'body': 1,
                    'parameters': 2,
                },
                'MemberExpression': 2,
                'ObjectExpression': 1,
                'SwitchCase': 1,
                'ignoredNodes': [
                    'ConditionalExpression',
                ],
            },
        ],
```

Desired (Example):
```js
        'indent': [
            'error',
            4,
            {
                'CallExpression': {
                    'arguments': 2,
                },
                'FunctionDeclaration': {
                    'body': 1,
                    'parameters': 2,
                },
                'FunctionExpression': {
                    'body': 1,
                    'parameters': 2,
                },
                'MemberExpression': 2,
                'ObjectExpression': 1,
                'SwitchCase': 1,
                'ConditionalExpression: 1,
            },
        ],
```
**What does the rule currently do for this code?**
The only way to configure indent behavior for conditional (ternary) expressions is to ignore them completely

**What will the rule do after it's changed?**
Conditional expressions will be configurable, just as every other kind of expression. At the very least, it should be possible to automatically bring conditional expressions into conformance with the rest of the code base, which it does not currently seem to do.

**Are you willing to submit a pull request to implement this change?**
I have no idea how to do that. Maybe if you can give me enough of a description on how to make it happen, I could give it a shot, but I am not familiar at all with JS, so my code might be less than great.

**Comment by kaicataldo** [comment]
It would be really helpful to us in evaluating your proposal if you include what the rule will actually allow/disallow using code examples. Some specific questions I have:

1) I'm assuming this will only apply to multiline ternary expressions. What's the expected behavior for the following cases?

```js
const a = b 
    ? c 
    : d;

const a = b ? 
    c :
    d;

const a = b ? c :
    d;

const a = b
    ? c :
    d;

const a = (
        b || c
    ) ? d :
    {
        e: true
    };
```

2) How would this new option interact with the existing `flatTernaryExpressions` option?

I personally think a more generic option that configures the indentation of multiline expressions might be more useful (see https://github.com/eslint/eslint/issues/12248).

**Comment by kaicataldo** [comment]
Ah, I found it! Sorry, thought it was an issue. https://github.com/eslint/eslint/pull/12556

Do the proposed changes in that PR satisfy your use case?

**Comment by t-rad679** [comment]
Thank you for your prompt reply!

Yeah, a generalized multiline expression config would be better. I was under the impression that was already happening for most expressions, though. In most cases, it seems to correctly handle my multiline cases...i.e.
```js
for (blah in blahs) {
    const thisStatementIsMultiline =
            someReallyLongStuffThatDeservesItsOwnLine();
}
```

This seems to be handled correctly.

However, in looking through the codebase to make sure I have everything I'm telling you correct, I did run across an odd case:

```js
function isAVuexModule() {
   return (
        _.isPlainObject(options) &&
  _.isPlainObject(options.state) &&
  _.isPlainObject(options.getters) &&
  _.isPlainObject(options.mutations) &&
  _.isPlainObject(options.actions)
    );
}
```

This is unexpected in several ways (I recognize that not all of these are relevant to this PR):

* The opening paren is on a different line than the first element
* The first element is the first continuation line (the second element should be
   first continuation line)
* The first continuation line is only indented 4 spaces (8 expected)
* The subsequent continuation lines are not indented at all
* The closing paren (which should be on the same line as the last element) is
   indented two additional spaces. Even if you wanted your closing paren on the
   next line, this is an incorrect indentation. IIUC, nothing is configured for 2 spaces.

Whatever solution we come to also ought to fix this; so, I agree, doing this just for Conditional Expressions is not the best way to proceed. What I would expect in this scenario is:

```js
function isAVuexModule() {
        return (_.isPlainObject(options) &&
                _.isPlainObject(options.state) &&
                _.isPlainObject(options.getters) &&
                _.isPlainObject(options.mutations) &&
                _.isPlainObject(options.actions));
}
```
(To be clear, the behavior I want is *not* to have the continuations line up with the argument on the first line. It's all about 8 spaces aka double the normal indent)

Now to answer your questions:

1.
```js
// Ideally, one this short would be on one line. If it's broken, it would be
// the following.

// The first 4 should look like this
const a = b ?
        c :
        d;

const a = (b || c) ?
        d :
        {e: true};
// Or, if the inline object is too long for one line
const a = (b || c) ?
        d :
        {
            e : true
        };
```
2.  If used in conjunction with `flatTernaryExpressions`, it depends on a number of things, really. First of all, I find the example very difficult to read as is. I think something like this would be ideal:

```js
var a = foo ?
        bar :
        baz ? qux : boop;
```

With `flatTernaryExpressions` set to `false`, it should look like this:

```js
var a = foo ?
        bar :
                baz ? qux : boop;
```

If `qux : boop` is too long, it should look like this:

```js
var a = foo ?
        bar :
                baz ?
                        qux :
                        boop;
```
Does that help?

**Comment by t-rad679** [comment]
Just looked at that PR you linked. I don't think it addresses the issue, though it is important. Correct me if I'm wrong, but it seems like that PR would allow for the following:
```js
// Format...
foo ?
    bar => {
    function();
    } :
    baz;
// Into...
foo ?
    bar => {
        function();
    } :
    baz;
```
This seems important; the latter seems like the correct behavior. However, what I'm looking for is the following:

```js
// Format...
foo ?
    bar => {
        function();
    } :
    baz;
// Into...
foo ?
        bar => {
            function();
        } :
        baz;
```

**Comment by kaicataldo** [comment]
These seem like two separate issues to me - do you mind creating a separate issue for the latter one?

I don't think we're quite on the same page. The `indent` rule enforces indentation but doesn't add newlines. You can see an example [here](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgYSA9ICggYiAgICAgICAgICAgICAgIClcblxuY29uc3QgYTIgPSAoIGJcbiAgICAgICAgICAgICApXG5cbmNvbnN0IGEzID0gKCBcbiAgYlxuICAgICAgICAgICAgICkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS1hdG9taWMtdXBkYXRlcyI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImluZGVudCI6Mn0sImVudiI6e319fQ==).

It sounds like what you're looking for is the following:

```js
/*eslint indent: ["error", 4, { "ConditionalExpression": 2 }]*/

// Incorrect
foo ?
    bar => {
        function();
    } :
    baz;

// Correct
foo ?
        bar => {
            function();
        } :
        baz;
```

```js
/*eslint indent: ["error", 4, { "ConditionalExpression": 2, "flatTernaryExpressions": false }]*/

// Incorrect
var a =
    foo ? bar :
    baz ? qux :
    boop;


// Correct
var a =
    foo ? bar :
            baz ? qux :
                    boop;
```

```js
/*eslint indent: ["error", 4, { "ConditionalExpression": 2, "flatTernaryExpressions": true }]*/

// Inorrect
var a =
    foo ? bar :
            baz ? qux :
                    boop;

// Correct
var a =
        foo ? bar :
        baz ? qux :
        boop;
```
