### ISSUE TITLE
ESLint hangs on linting complete stage

### ISSUE THREAD

**Issue by lipis** [eslint/eslint#12681]
**Tell us about your environment**

* **ESLint Version:** 6.7.2
* **Node Version:** v10.16.0
* **yarn Version:** 1.21.1

**What parser (default, Babel-ESLint, etc.) are you using?**

`"@typescript-eslint/parser"`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

- https://github.com/wireapp/wire-web-packages/blob/lipis-eslint/packages/eslint-config/eslintrc.json
- https://github.com/wireapp/wire-webapp/blob/lipis-eslint/.eslintrc.json

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
yarn lint:code
```

Which essentially is running

```bash
eslint -c .eslintrc.json --ext .js . --debug
```

**What did you expect to happen?**

Finish the task and show the current errors

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint hangs on the last step

**Are you willing to submit a pull request to fix this bug?**

No :(

**Comment by kaicataldo** [comment]
Is there any other information you can share with us? Do you know what the offending code might be? Maybe the results of running with the `--debug` flag? It's possible this is related to `@typescript-eslint/parser` as well, but it's difficult to know what's going on without more information.

**Comment by lipis** [comment]
Yeap, I forgot the link to our PR!

https://github.com/wireapp/wire-webapp/pull/7933

You can run the `yarn lint:code` to see it in action.
