### ISSUE TITLE
Add constructor option to space-before-function-paren

### ISSUE THREAD

**Issue by clar-cmp** [eslint/eslint#12705]
**What rule do you want to change?** `space-before-function-paren`

**How will the change be implemented? (New option, new default behavior, etc.)?** A new type of function would be added, "constructor," which would only affect the constructor keyword

**Please provide some example code that this change will affect:**

```js
// eslint space-before-function-paren: ["error", { "constructor": "always" }]*/
class Foo {
    constructor () {
        // ...
    }
}

// eslint space-before-function-paren: ["error", { "constructor": "never" }]*/
class Foo {
    constructor() {
        // ...
    }
}

```

(ignore would accept both)

**Are you willing to submit a pull request to implement this change?** (Don't have time, up for grabs)

**Comment by kaicataldo** [comment]
How do you envision this interacting with the pre-existing `named` option?

**Comment by clar-cmp** [comment]
This would replace the `named` option  for the constructor keyword only. We could choose to make the value of `constructor` default to the value of `named` to avoid breaking changes, although I'd personally recommend just leaving it as a breaking change and defaulting to true like all the other values.

**Comment by kaicataldo** [comment]
I wonder if it would make more sense to add a `classMethod` option instead. It seems more likely to me that folks would want to enforce this spacing consistently for all methods rather than just for the `constructor` of a class.

**Comment by clar-cmp** [comment]
Personally, I see `constructor` as a keyword and would like to enforce spaces after keywords, but not after identifiers. That's mostly why I think it should be a separate option.

**Comment by kaicataldo** [comment]
Understood. Please note that you can always make a custom rule even if this doesn't reach consensus. [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) would make it a fairly easy one to create!
