### ISSUE TITLE
forgetting adding await before calling async function

### ISSUE THREAD

**Issue by EhsanSarshar** [eslint/eslint#12712]
**eslint:6.8.0**

**forgetting to add await before a function that return a Promise cause unexpected result**

right way `const data = await db.getDate()`
wrong way `const data = db.getDate()`

**I hope that there be such a plugin that warn the user if he/she forget to add await before promise**

**Comment by kaicataldo** [comment]
This is not enforceable without false negatives without some sort of type system. I would suggest using Flow or TypeScript to catch these kinds of errors.

We would really appreciate it if you would fill out the full template next time, as it helps us evaluate proposals better.
