### ISSUE TITLE
no-constant-condition not able to detect one of constant case

### ISSUE THREAD

**Issue by anilnamde** [eslint/eslint#12763]
I think that below ternary is constant condition and should have been detected by the no-constant-condition eslint rule

```
history.push(`${match.url}/${false && isUser ? 'OVERVIEW' : 'Performance'}`)
```

* ESLint Version: 6.4.0
* Node Version: v10.16.0
* npm Version: 6.11.1

**Comment by mdjermanovic** [comment]
Hi @anilnamde, thanks for the issue!

I can't reproduce this. 

In this [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiaGlzdG9yeS5wdXNoKGAke21hdGNoLnVybH0vJHtmYWxzZSAmJiBpc1VzZXIgPyAnT1ZFUlZJRVcnIDogJ1BlcmZvcm1hbmNlJ31gKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby1jb25zdGFudC1jb25kaXRpb24iOjJ9LCJlbnYiOnt9fX0=) the rule correctly reports `false && isUser` as a constant condition. I also tried locally with ESLint 6.4.0 and it's the same.

Could you please fill out bug template report?
