### ISSUE TITLE
ESLint doesn't respect the .eslintignore and hangs on the last step

### ISSUE THREAD

**Issue by lipis** [eslint/eslint#12769]
**Tell us about your environment**

* Node version: v10.18.0
* npm version: v6.13.4
* Local ESLint version: v6.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**

`babel-eslint` and for `ts`, `tsx` files `@typescript-eslint/parser`

**Please show your full configuration:**

I created a small project to demonstrate the issue.

https://github.com/lipis/eslint-ts-bug

Just clone it, run `yarn` and then `yarn test`.

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

When I run `yarn test` it also parses the `lib` directory, which is ignored inside the `.eslintignore`.. why is that?

```bash
yarn test

# the actual command
# eslint --ignore-path .gitignore --ext .js,.ts,.tsx . --debug
```

**What did you expect to happen?**

To ignore the `lib` directory and finish the task.

**What actually happened? Please include the actual, raw output from ESLint.**

Doesn't ignore the `lib` and hangs in the end.

**Are you willing to submit a pull request to fix this bug?**

No :(

**Comment by lipis** [comment]
Related issue: #12681

**Comment by jchristou** [comment]
The problem is you don't have the lib folder listed in your .gitignore.
You're setting this option:
`--ignore-path .gitignore`
So the old .eslintignore won't be used. See [here](https://eslint.org/docs/user-guide/configuring#using-an-alternate-file)

**Comment by kaicataldo** [comment]
Sorry for the delay! I think @jchristou's answer is correct. @lipis Can you confirm?

**Comment by lipis** [comment]
Does ESLint ignore the files in `.gitignore` by default?

what I did to solve my problem is to add the ignore list inside the `eslint.json` file with the additional patterns that are not part of `.gitignore`

I think the idea would be for ESLint to ignore `.gitignore` by default as well.

**Comment by kaicataldo** [comment]
ESLint only ignores `/node_modules/*` and `/bower_components/*` by default. Feel free to make an [RFC](https://github.com/eslint/rfcs) if you'd like to propose a change!
