### ISSUE TITLE
Eslint (no-unused-vars) can't properly detect unused variable at Vue factory pattern

### ISSUE THREAD

**Issue by rockmandash** [eslint/eslint#12770]
Please see this thread:

https://stackoverflow.com/questions/59682349/eslint-no-unused-vars-cant-properly-detect-unused-variable-at-vue-factory-pat

**Comment by categulario** [comment]
hey @rockmandash I ran into a similar problem. Although in the example you show the behavior is exactly as described here: https://eslint.org/docs/rules/no-unused-vars because the variable is assigned a value but never actually used.

**Comment by rockmandash** [comment]
I think I got it.
