### ISSUE TITLE
Allow config to not emit information for Github Actions

### ISSUE THREAD

**Issue by runspired** [eslint/eslint#12776]
currently eslint is emitting check info for Github Actions, this produces unnecessary noise that greatly hinders code reviews.

Example

<img width="891" alt="image" src="https://user-images.githubusercontent.com/650309/72211401-93992680-347f-11ea-9b80-641a6b4322c9.png">

The entire point of listing, ci lint checks, and auto fix is that this allows reviews to ignore code style aspects, this noise defeats that and makes file diffs difficult to read.

**Comment by g-plane** [comment]
Hello, thanks for this issue.

However, it seems that this message isn't from ESLint. Can you provide more detail? Thanks.

**Comment by runspired** [comment]
@g-plane ill find the docs and an example but roughly it means eslint is emitting info that actions uses to the  display this. Eslint doesn’t have to emit it.

**Comment by g-plane** [comment]
It should be related to the actions you're using, not ESLint itself. ESLint doesn't provide any functionalities with GitHub Actions.

**Comment by runspired** [comment]
Here’s the docs https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-error-message-error

Note this isn’t specific to actions, or even necessarily github.

Here’s an example of how this is integrated in a lint library from one that allows it to be turned off https://github.com/ember-template-lint/ember-template-lint/pull/966

**Comment by g-plane** [comment]
However, according to your information, I don't think there's anything related to ESLint *itself*.

**Comment by ilyavolodin** [comment]
@runspired Just to expand on what @g-plane is saying. ESLint doesn't maintain GitHub action that you are using. I'm not sure who does. ESLint is a CLI tool that is meant to be run on the command line through Node. It sounds like you should turn off whatever GitHub actions is running ESLint in your repository to get rid of the errors that you are seeing.

**Comment by runspired** [comment]
@ilyavolodin I'll work to expand on the explanation and reproduction, but quite literally there is no GitHub action involved here. Simply running `eslint` with config flags via the command line as a step during a workflow causes this.

**Comment by mysticatea** [comment]
Do you use [actions/setup-node] action?

As far as I know, [actions/setup-node] action registers the matcher of ESLint errors automatically. So if you run ESLint after [actions/setup-node] action, GitHub Actions pick up and comment it.

[actions/setup-node]: https://github.com/actions/setup-node
