### ISSUE TITLE
[multline-comment-style] fix breaks code

### ISSUE THREAD

**Issue by hornta** [eslint/eslint#12785]
**Tell us about your environment**

* **ESLint Version:** 6.7.2
* **Node Version:** 12.14.1
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint@10.0.3

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
When autofixing the following code it resulted in non-parseable js code. This is a minimal reproducible example.

```js
/* eslint-enable multiline-comment-style */
/*
  // a line comment
  some.code();
*/
```

**What did you expect to happen?**
I expect it to not yield non-parseable code.

**What actually happened? Please include the actual, raw output from ESLint.**
It yielded non-parseable code

**Comment by yeonjuan** [comment]
Hello, I'm not an eslint member. But, In my opinion, it looks like a bug. reproduced- [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG11bHRpbGluZS1jb21tZW50LXN0eWxlOiBbXCJlcnJvclwiXSAqL1xuLypcbiAgLy8gYSBsaW5lIGNvbW1lbnRcbiAgc29tZS5jb2RlKCk7XG4qL1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnsiYnJvd3NlciI6ZmFsc2V9fX0=)

```
/* eslint multiline-comment-style: ["error"] */
/*
  // a line comment
  some.code();
*/
```
after fix.
```js
/* eslint multiline-comment-style: ["error"] */
/*
 *// a line comment
 *some.code();
 */
```

**Comment by aladdin-add** [comment]
hi, thanks! labelled accepted, based on the repro-demo.

**Comment by jpramassini** [comment]
I'd be interested in jumping on this one if there aren't any other takers.

**Comment by kaicataldo** [comment]
@jpramassini Please feel free! Let us know if you have any questions.

**Comment by karthikkp** [comment]
@jpramassini Still working on this?

**Comment by jpramassini** [comment]
Hey Karthik, sorry for the delay on this. I'm planning on knocking this out this weekend.

**Comment by jpramassini** [comment]
@karthikkp I got the flu so I might be slower in getting to this than I thought. If you want to take a crack at it, go for it.

**Comment by karthikkp** [comment]
@jpramassini Thank you. I am taking up this issue
