### ISSUE TITLE
case sensitive props duplicate-props check problem

### ISSUE THREAD

**Issue by ahmetcaglayan** [eslint/eslint#12781]
![7FD6A8D9-41F3-42CF-945E-D2F700E36C28](https://user-images.githubusercontent.com/13018803/72260476-03e0ad00-3624-11ea-9cb1-bc768267a7ab.jpeg)

inputProps !== InputProps 
// eslint-disable-next-line react/jsx-no-duplicate-props

does not check property names as case sensitive. Material-ui components have such a feature but eslint is angry.

**Comment by yeonjuan** [comment]
@ahmetcaglayan 
Hi, `react/jsx-no-duplicate-props` is a rule in the [eslint-plugin-react repository](https://github.com/yannickcr/eslint-plugin-react). How about reporting an issue there?
