### ISSUE TITLE
no-unused-vars rule with for-in loop

### ISSUE THREAD

**Issue by dangreen** [eslint/eslint#12793]
```
Environment Info:

Node version: v11.15.0
npm version: v6.7.0
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found
```

TravisCI build:
https://travis-ci.com/TrigenSoftware/scripts/builds/144470340

```
/home/travis/build/TrigenSoftware/scripts/packages/scripts/src/eject.js
  41:13  error  'scriptName' is defined but never used  no-unused-vars
```

Code:
https://github.com/TrigenSoftware/scripts/blob/master/packages/scripts/src/eject.js#L41

```js
...
	for (const scriptName in scripts) {

		const cmd = scripts[scriptName];
...
```

`scriptName` is used

**Comment by dangreen** [comment]
eslint@6.1.0 - ok
eslint@6.2.0 - problems

**Comment by kaicataldo** [comment]
Most likely a dupe of https://github.com/eslint/eslint/issues/12117.

**Comment by dangreen** [comment]
Solution: update `babel-eslint` to 10.0.3
