### ISSUE TITLE
[no-proto, no-iterator] overlooks template literal

### ISSUE THREAD

**Issue by yeonjuan** [eslint/eslint#12801]
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v12.13.0
* **npm Version:** v6.12.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Demo - no-proto](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcHJvdG86IFwiZXJyb3JcIiovXG5cbnZhciBhID0gb2JqW1wiX19wcm90b19fXCJdO1xudmFyIGEgPSBvYmpbYF9fcHJvdG9fX2BdOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlfX19)
```js
/*eslint no-proto: "error"*/
var a = obj["__proto__"];
var a = obj[`__proto__`];
```

[Demo - no-iterator](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8taXRlcmF0b3I6IFwiZXJyb3JcIiovXG5mb29bXCJfX2l0ZXJhdG9yX19cIl0gPSBmdW5jdGlvbiAoKSB7fTtcbmZvb1tgX19pdGVyYXRvcl9fYF0gPSBmdW5jdGlvbiAoKSB7fTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6e30sImVudiI6eyJicm93c2VyIjpmYWxzZX19fQ==)
```js
/*eslint no-iterator: "error"*/
foo["__iterator__"] = function () {};
foo[`__iterator__`] = function () {};
```

**What did you expect to happen?**

Both cases are expected two errors each.

**What actually happened? Please include the actual, raw output from ESLint.**

Both rules(no-proto, no-iterator) don't consider template literals.

* no-proto
```js
/*eslint no-proto: "error"*/
var a = obj["__proto__"]; // Error - The '__proto__' property is deprecated
var a = obj[`__proto__`]; // no error.
```

* no-iterator
```js
/*eslint no-iterator: "error"*/
foo["__iterator__"] = function () {}; // Error - Reserved name '__iterator__'/
foo[`__iterator__`] = function () {}; // no error
```
**Are you willing to submit a pull request to fix this bug?**

Yes (it's prepared)

**Comment by aladdin-add** [comment]
confirmed, thanks!
