### ISSUE TITLE
enable Cache by default

### ISSUE THREAD

**Issue by zodiac1214** [eslint/eslint#12802]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**
Enable cache by default

**Your take on the correct solution to problem.**
we should enable cache by default in cli so lint in a monorepo would be a lot faster. I know we could do so with --cache but it is a pain to add that to every single project in a monorepo. 

**Are you willing to submit a pull request to implement this change?**
yes

**Comment by kaicataldo** [comment]
Do you mind writing up an [RFC](https://github.com/eslint/rfcs) for this? We would want to make sure that we think through all the consequences of this change, since it's potentially so wide-reaching.

**Comment by ilyavolodin** [comment]
This would only benefit large projects and might create confusion for smaller ones. Considering the number of ESLint users, I don't think this would be a good idea.

**Comment by zodiac1214** [comment]
> This would only benefit large projects and might create confusion for smaller ones. Considering the number of ESLint users, I don't think this would be a good idea.

Can we at least allow this option in the config file instead of only available as a CLI option?

**Comment by kaicataldo** [comment]
> Can we at least allow this option in the config file instead of only available as a CLI option?

As mentioned above, this would need to go through the RFC process. Please feel free to create a proposal!

**Comment by canova** [comment]
I found an old issue for this and it's closed because apparently caching can lead to wrong results with some plugin rules(at least as of 2018). This is the comment: https://github.com/eslint/eslint/issues/10712#issuecomment-409748549
Do you think this is not the case anymore and worth an RFC?

**Comment by kaicataldo** [comment]
This would still be the case. @mysticatea is referring to the fact that these plugins check things outside the scope of what ESLint is aware of, so ESLint will not be able to bust the cache correctly for those plugins.
