### ISSUE TITLE
Linting inside comments block spaces/tab to single space

### ISSUE THREAD

**Issue by jperocho** [eslint/eslint#12800]
Just a question if eslint has a rule to check for multiple spaces or tabs inside a comment block?

**Environment:**
ESLint: v6.7.2
Node: v12.13.1
npm: 6.12.1

```
 /**
 * Some jsdocs for a function
 * @param   {String}   argument string - string
 * @param   {Object}   property        - property object
 * @returns {Function} callback        - callback
 */
```
Thanks in advance.

**Comment by yeonjuan** [comment]
@jperocho 
Hi, eslint core does not have a rule related to JSDoc alignment.
Maybe you can find some JSDoc linting rules in this plugin repo - [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc). But, I'm not sure whether this plugin has the rules which you want.

**Comment by jperocho** [comment]
Cool thanks for the response. Will check it now
