### ISSUE TITLE
Change default value for enforceForClassMembers in accessor-pairs

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12811]
Rule: [accessor-pairs](https://eslint.org/docs/rules/accessor-pairs)

This is a proposal to change the default value for the option `enforceForClassMembers` to `true` in `v7.0.0`

I believe the expected behavior for this rule would be to check classes by default, so a user may be unaware that it doesn't.

The option was added in `v6.4.0`.

**Comment by btmills** [comment]
In today's TSC meeting, we accepted this as a semver-major change for the v7.0.0 release. It's now ready to implement!
