### ISSUE TITLE
even smarter unused-var detection

### ISSUE THREAD

**Issue by fuweichin** [eslint/eslint#12819]
**What rule do you want to change?**
`no-unused-vars`

**Does this change cause the rule to produce more or fewer warnings?**
More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
In brief, if a *pure data object* (see below), like `Array` `Map`, is constructed and only *initialization statements* (see below) are invoked, then we can mark it as unused.

 *pure data objects::*

ECMAScript built-in Types

+ `Object`
+ `Array`
+ Typed Arrays: `Uint8Array`, `Int32Array`, ...
+ `Map`
+ `Set`

Types defined in DOM

+ Form Objects: `FormData` , `URLSearchParams`

*object initialization statements::*

| Object Type  | Initialization Statements    | Examples                                          |
| ------------ | ---------------------------- | ------------------------------------------------- |
| `Object`     | property assignment          | `object["foo"]="bar";`                            |
| `Array`      | element assignment or push() | `array[0]=1;` or `array.push(1);`                 |
| Typed Arrays | element assignment or set()  | `a.set([0xFF,0xFE],0)` or `a[0]=0xFF;a[1]=0xFE;`  |
| `Map`        | set()                        | `map.set("foo","bar");`                           |
| `Set`        | add()                        | `set.add("foo");`                                 |
| Form Objects | append() or set()            | `params.append("a","1")` or `params.set("a","1")` |
| ...          |                              |                                                   |

**Please provide some example code that this change will affect:**

```js
function test(){
    let a=[];
    a.push(1);
    a.push(2);
    let b=[];
    b.push('1');
    b.push('2');
    return b;
}
test();
```

**What does the rule currently do for this code?**
Current implmentation of the rule doesn't warn 'no-unused-var' on var 'a'

**What will the rule do after it's changed?**
It will give a warning like "'a' is initialized but never used. eslint(no-unused-vars)"

**Are you willing to submit a pull request to implement this change?**
No, I'm currently busy.

**Comment by kaicataldo** [comment]
Some thoughts:

1. I think this would have to go behind a configuration option since it would lead to more errors.
1. I don't think we should include DOM-provided constructors.
1. This wouldn't be able to catch imported values since we can't know what type they are, so this would have a significant set of false negatives.
