### ISSUE TITLE
./node_modules/.bin/eslint --init report an error

### ISSUE THREAD

**Issue by openStar99** [eslint/eslint#12814]
**Tell us about your environment**

* **ESLint Version:**6.8.0
* **Node Version:**8.9.2
* **npm Version:**6.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>
1.run npm install --save-dev eslint;
2.run ./node_modules/.bin/eslint --init report the following error
SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at no-octal-escape (c:\Users\i343419\Desktop\koa2-tutorial\node_modules\eslint\lib\rules\index.js:171:30)
[Error - 2:31:19 PM] ESLint stack trace:
[Error - 2:31:19 PM] \node_modules\eslint\lib\rules\no-octal-escape.js:41
                    /^(?:[^\\]|\\.)*?\\([0-3][0-7]{1,2}|[4-7][0-7]|0(?=[89])|[1-7])/su

```js
module.exports = {
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": [
        "standard"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "rules": {
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**
normal init eslintrc.js file

**What actually happened? Please include the actual, raw output from ESLint.**
report an error and initial process broke

**Are you willing to submit a pull request to fix this bug?**

**Comment by g-plane** [comment]
Hello, can you tell us your steps and choices when running `--init`?

**Comment by openStar99** [comment]
Dear,

Perhaps it will help.


Best regards,
Star




------------------ Original ------------------

**Comment by g-plane** [comment]
It seems that you didn't provide any information.

**Comment by openStar99** [comment]
Dear,
Please refer to the attachment.


Best regards,
Star
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pig Fang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月22日(星期三) 中午12:33
收件人:&nbsp;"eslint/eslint"<eslint@noreply.github.com&gt;;
抄送:&nbsp;"STaR"<291325427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eslint/eslint] ./node_modules/.bin/eslint --init report an error (#12814)




It seems that you didn't provide any information.

**Comment by kaicataldo** [comment]
@openStar99 We are unable to see any attachments in the GitHub UI. Please fill out the template in the original comment.
