### ISSUE TITLE
Change default value for enforceForSwitchCase in use-isnan

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12810]
Rule: [use-isnan](https://eslint.org/docs/rules/use-isnan)

This is a proposal to change the default value for the option `enforceForSwitchCase` to `true` in `v7.0.0`

An option for this is most likely unnecessary, I believe there is no reason to turn it off. Nevertheless, it might be safe to just change the default value for the start.

The option was added in `v6.5.0`.

**Comment by ljharb** [comment]
Flipping the default in v7, and removing the option in v8 if there's no demand for it, seems reasonable (although, doing that would mean it's impossible for a shared config to be compatible with v6, v7, and v8 at the same time)

**Comment by btmills** [comment]
In today's TSC meeting, we accepted this as a semver-major change for the v7.0.0 release. It's now ready to implement!
