### ISSUE TITLE
Change default value for enforceForClassMembers in computed-property-spacing

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12812]
Rule: [computed-property-spacing](https://eslint.org/docs/rules/computed-property-spacing)

This is a proposal to change the default value for the option `enforceForClassMembers` to `true` in `v7.0.0`

The rule currently checks object literals and member expressions by default.

I believe the expected behavior for this rule would be to check computed names in class definitions by default, too.

The option was added in `v6.4.0`.

**Comment by btmills** [comment]
In today's TSC meeting, we accepted this as a semver-major change for the v7.0.0 release. It's now ready to implement!
