### ISSUE TITLE
`func-style` "expression" conflicts with ESM named exports

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#12829]
**What rule do you want to change?**
`func-style`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer or more, depending on how the option is configured.

**How will the change be implemented? (New option, new default behavior, etc.)?**
A new `namedExports` option, which can be set to "expression" or "declaration" or "ignore".

**Please provide some example code that this change will affect:**

```js
/* eslint func-style: [2, "expression"] */
export function foo() {}
```

**What does the rule currently do for this code?**
warns

**What will the rule do after it's changed?**
`/* eslint func-style: [2, "expression", { "namedExports": "declaration"] */` will cause no warning to be issued.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by mdjermanovic** [comment]
Just to clarify the issue, I believe this configuration expects something like:

```js
/* eslint func-style: [2, "expression"] */
export const foo = function () {};
```

What conflict does this cause? Asking because "conflict" is mentioned in the title.

**Comment by ljharb** [comment]
I suppose it isn’t a conflict; it’s just that i don’t see these as the same as function declarations since they’re under a tdz, and so altho i never want declarations, i do want the export function form.

**Comment by mdjermanovic** [comment]
So, the motivation is to allow hoisting only for exported functions because good practice is to define all exports at the end?

```js
foo(); // this wouldn't be possible here with export const foo = function () {};

export function foo() {};
```

**Comment by ljharb** [comment]
Unfortunately that does result in hoisting, but in this case I don't care about it, because i don't want to create an extra variable in my named exports.

**Comment by mdjermanovic** [comment]
> Unfortunately that does result in hoisting, but in this case I don't care about it, because i don't want to create an extra variable in my named exports.

I'm not sure that I understand the part about an extra variable, an example of code you'd like to avoid with this option would be helpful!

**Comment by ljharb** [comment]
i want to avoid `export const =` - i don’t want equals signs in my export statements, but i do want to prohibit declarations everywhere else.

**Comment by mdjermanovic** [comment]
Makes sense to me :+1:

**Comment by ljharb** [comment]
It'd be great if this could be reopened.

**Comment by mdjermanovic** [comment]
I'll champion this.

**Comment by krainboltgreene** [comment]
How can I help with this?

**Comment by mdjermanovic** [comment]
@krainboltgreene this enhancement doesn't have [consensus](https://eslint.org/docs/maintainer-guide/issues#accepting-issues) from the team yet.

If and when this issue gets accepted, a PR will be welcome :)

**Comment by krainboltgreene** [comment]
Ahhh, that makes sense thanks!

**Comment by ljharb** [comment]
@mdjermanovic any update on consensus from the team? this is still an issue for all the packages I'm writing ESM wrappers for.

**Comment by nzakas** [comment]
@mdjermanovic you championed this initially, do you want to move forward? If so, can you explain the exact change?

**Comment by Tanujkanti4441** [comment]
@mdjermanovic a friendly ping, waiting for your suggestion to move this issue forward, Thanks.

**Comment by nzakas** [comment]
@mdjermanovic still looking for your input here

**Comment by mdjermanovic** [comment]
I don't think this rule should ignore named exports by default.

We could add a boolean option to ignore named exports:

```
"func-style": [2, "expression", { "ignoreNamedExports": true }] // `false` by default
```

or an option to override base settings for named exports or ignore them:

```
"func-style": [2, "expression", {
    "overrides": { 
        "namedExports": "declaration" // allowed values are: "expression", "declaration`, "ignore"
    }
}]
```

The latter is similar to the original proposal, I only added `"overrides"` because options that override base settings for certain cases are typically under `"overrides"` in core rules.

Thoughts?

**Comment by ljharb** [comment]
An option sounds perfectly fine, thanks.

**Comment by nzakas** [comment]
@ljharb is that in favor of a boolean option or the `overrides` option?

**Comment by ljharb** [comment]
Either is fine.

**Comment by nzakas** [comment]
@mdjermanovic I think either solution is fine as well, do you have a preference?

**Comment by ljharb** [comment]
i see #18444 was filed; i was planning to file one this week since i was traveling last week, but i'm happy @kecrily beat me to it :-)
