### ISSUE TITLE
How can I use Eslint with Typescript Formater in VSCode?

### ISSUE THREAD

**Issue by alpgul** [eslint/eslint#12838]
**Tell us about your environment**

* **ESLint Version:** "eslint": "^6.8.0",
* **Node Version:** v13.5.0
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "airbnb-base"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "rules": {
        "max-classes-per-file": [
            "error",
            2
        ],
        "no-ternary": "error",
        "no-nested-ternary": "error",
        "max-len": [
            "error",
            {
                "code": 280
            }
        ],
        "no-debugger": 0,
        "linebreak-style": [
            "error",
            "windows"
        ],
        "array-bracket-newline": [
            "error",
            {
                "multiline": true,
                "minItems": 2
            }
        ],
        "array-element-newline": [
            "error",
            {
                "multiline": true,
                "minItems": 3
            }
        ],
        "func-names": [
            "warn",
            "never"
        ],
        "no-console": 0
    }
}
```
```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
        [
          variableCommon.boxPos,
          variableCommon.healtime,
          variableCommon.focusEnt,
          variableCommon.healActive,
          variableCommon.url,
          variableCommon.shipId,
        ] = [
          message.boxPos || variableCommon.boxPos,
          message.healtime || variableCommon.healtime,
          message.focusEnt || variableCommon.focusEnt,
          message.healActive || variableCommon.healActive,
          message.url || variableCommon.url,
          message.shipId || variableCommon.shipId,
        ];
```
**What did you expect to happen?**

> I used with Vscode then I got error. error is  at bellow image. I'm using 'typescript formater extension' and I want to use  'typescript formater extension'  with eslint but i got error. Are there any solution for this?

**What actually happened? Please include the actual, raw output from ESLint.**
![test](https://user-images.githubusercontent.com/5773704/73246370-7e323500-41bf-11ea-8dea-8fbcc542fd7c.gif)
**Expected indentation of 10 spaces but found 12.**

**Comment by kaicataldo** [comment]
I would turn off all style-related rules (`indent`, `semi`, etc.) if you're using another program to format your code. This is true of other popular formatters like Prettier as well.
