### ISSUE TITLE
Deprecate Node-specific core rules

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#12835]
**The version of ESLint you are using.**
`master`

**The problem you want to solve.**

The number of rules in core has grown to the point that we have to set a very high bar for new rules. To improve our ability to maintain core, I think it makes sense to treat the current core Node/CommonJS rules similarly to how we handled the deprecation of [core JSDoc rules](https://eslint.org/blog/2018/11/jsdoc-end-of-life). I believe these are the last runtime/library specific rules that we have in core, and think this also makes sense for the sake of consistency.

**Your take on the correct solution to problem.**

As discussed in our TSC meeting (notes [here](https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-12-19.md#update-no-path-concat-rule-checks-template-literals-fixes-12323)), this proposal is to deprecate all the Node/CommonJS-specific rules in core and to move all of them into [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node), maintained by @mysticatea.

**Are you willing to submit a pull request to implement this change?**
Yes!

**Questions**
1. @mysticatea Are you still okay with this? Just wanted to check because it's been a little while since we last discussed this.

**Comment by mysticatea** [comment]
Thank you for this issue.

> Are you still okay with this? Just wanted to check because it's been a little while since we last discussed this.

Yes!

**Comment by kaicataldo** [comment]
Marking as accepted since this was decided on during a TSC meeting and @mysticatea is still on board.

**Comment by kaicataldo** [comment]
I'll work on this :)

**Comment by kaicataldo** [comment]
# Steps to complete this:
- [ ] Port rules over to `eslint-plugin-node` (https://github.com/mysticatea/eslint-plugin-node/pull/206)
- [ ] Deprecate rules in core
- [ ] Write a blog post similar to https://eslint.org/blog/2018/11/jsdoc-end-of-life

**Comment by ljharb** [comment]
I know it might be late, but this seems like a terrible idea. Having rules in core is paramount for discoverability, especially since shared configs and peer deps are still a huge PITA, until shared configs can bring along plugins as regular deps.
