### ISSUE TITLE
ESLint attempting to load parser for directory inside node_modules

### ISSUE THREAD

**Issue by fmapilis** [eslint/eslint#12854]
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 10.13.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
 Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  env: {
    browser: true,
    es6: true
  },
  extends: ["react-app"],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 2018,
    sourceType: "module"
  }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

See https://github.com/fmapilis/ts_eslint_test for an example

`eslint-config-react-app` has an override for Typescript files:
https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js#L57

Despite the project not having any Typescript files at all, running `yarn lint` / `eslint  "**/**.js"` produces the following error:
```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » eslint-config-react-app#overrides[0]': Cannot find module '@typescript-eslint/parser'
```

However, by removing the `microevent.ts` dependency in the project and running lint again, it does not throw that same error.

```bash
yarn remove microevent.ts
eslint  "**/**.js"
```

Alternatively, when running eslint with a more specific ignore pattern _and_ still having the `microevent.ts` package installed:

```bash
yarn add microevent.ts --save
eslint  "**/**.js" --ignore-pattern "/node_modules/"
```
This also produces no errors.

**What did you expect to happen?**
My assumption was that eslint ignores the top level `node_modules` directory completely.

**What actually happened? Please include the actual, raw output from ESLint.**
It seems that it's still looking at each of the directories inside of `node_modules` and skipping each one. I can see this happen running those same eslint commands with a `--debug` flag. It seems that it's confusing the `/node_modules/microevent.ts/` directory for an actual typescript file and trying to load the appropriate parser (which isn't installed in the project) rather than skipping it.

<details>
<summary>Debug logs</summary>

```
  eslint:ignore-pattern Check { filePath:
   '/Users/fmapilis/GitHub/ts_eslint_test/node_modules/locate-path/',
  dot: false,
  relativePath: 'node_modules/locate-path/',
  result: true } +0ms
  eslint:ignore-pattern Check { filePath:
   '/Users/fmapilis/GitHub/ts_eslint_test/node_modules/lodash/',
  dot: false,
  relativePath: 'node_modules/lodash/',
  result: true } +0ms
  eslint:ignore-pattern Check { filePath:
   '/Users/fmapilis/GitHub/ts_eslint_test/node_modules/loose-envify/',
  dot: false,
  relativePath: 'node_modules/loose-envify/',
  result: true } +0ms
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » eslint-config-react-app#overrides[0]': Cannot find module '@typescript-eslint/parser'
```

The next package after `loose-envify` is the `microevent.ts` package.
</details>

It feels strange to have to add a Typescript as dependency despite a project not using it at all. This package causing this issue is also fairly popular – https://www.npmjs.com/package/microevent.ts and will likely show up as dependecy for others as well.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by kaicataldo** [comment]
Thanks for the detailed issue! I'm not terribly familiar with how config loading works, so I'm digging through the code right now. I agree that this behavior seems unexpected, though, and that it should probably be consistent (either always requiring the config or not), regardless of the contents of an ignored directory.

I'm curious if this occurs only with directories with a name that end with an extension or files as well. Will keep digging!
