### ISSUE TITLE
`yoda` overlooks template literal 

### ISSUE THREAD

**Issue by yeonjuan** [eslint/eslint#12863]
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:**  v12.13.0
* **npm Version:** v6.12.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogXCJlcnJvclwiKi9cblxuaWYgKFwicmVkXCIgPT09IGNvbG9yKSB7XG4gICAgLy8gLi4uXG59XG5cbmlmIChgcmVkYCA9PT0gY29sb3IpIHtcbiAgICAvLyAuLi5cbn1cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlfX19)
```js
/*eslint yoda: "error"*/

if (`red` === color) { // No Error
    // ...
}

```

**What did you expect to happen?**

expect an error.

**What actually happened? Please include the actual, raw output from ESLint.**

no error

**Are you willing to submit a pull request to fix this bug?**

yes

**Comment by mdjermanovic** [comment]
I think this makes sense for template literals without expressions. Someone can always use only backticks (which can be enforced with the `quotes` rule), so `yoda` as it is now wouldn't work for them.

**Comment by nzakas** [comment]
There's consensus on this change, so marking as accepted.
