### ISSUE TITLE
Page not found for no-useless-backreference in documentation

### ISSUE THREAD

**Issue by svltmccc** [eslint/eslint#12860]
https://eslint.org/docs/rules/no-useless-backreference is not found, but https://eslint.org/docs/rules/ has link to **no-useless-backreference.**

Does this rule exist now?

**UPD:** there is the same with **default-case-last**

**Comment by mdjermanovic** [comment]
Hi @svltmccc, thanks for the issue!

Those are new rules that happened to be merged during the actual major `v7.0.0` release cycle, so they're at the moment available only in `v7.0.0-alpha.0`.

You can install and try out this version with: `npm i eslint@next --save-dev`

Any feedback about the pre-release version would be greatly appreciated!

Links:

* https://eslint.org/blog/2020/01/eslint-v7.0.0-alpha.0-released
* https://eslint.org/docs/7.0.0/rules/default-case-last
* https://eslint.org/docs/7.0.0/rules/no-useless-backreference
* https://eslint.org/docs/7.0.0/rules/no-restricted-exports

I also opened an issue in the website repo on should these rules be visible in the https://eslint.org/docs/rules/ list at the moment.
