### ISSUE TITLE
no-extra-parens conflicts with wrap-iife

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#12870]
**Tell us about your environment**

* **ESLint Version:** 7.0.0-alpha.0
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    parserOptions: {
        ecmaVersion: 2015
    },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint wrap-iife: ["error", "inside", { functionPrototypeMethods: true }] */
/* eslint no-extra-parens: ["error"] */

var x = function(){}.call(); // wrap-iife error

var x = (function(){}).call(); // no-extra-parens error
```

[Online Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHdyYXAtaWlmZTogW1wiZXJyb3JcIiwgXCJpbnNpZGVcIiwgeyBmdW5jdGlvblByb3RvdHlwZU1ldGhvZHM6IHRydWUgfV0gKi9cbi8qIGVzbGludCBuby1leHRyYS1wYXJlbnM6IFtcImVycm9yXCJdICovXG5cbnZhciB4ID0gZnVuY3Rpb24oKXt9LmNhbGwoKTsgLy8gd3JhcC1paWZlIGVycm9yXG5cbnZhciB4ID0gKGZ1bmN0aW9uKCl7fSkuY2FsbCgpOyAvLyBuby1leHRyYS1wYXJlbnMgZXJyb3IiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) (demo is v6.8.0, but it's same)

```bash
eslint index.js --fix
```

**What did you expect to happen?**

These are two same lines, except for the parens around the function expression.

`wrap-iife` requires these parens, while `no-extra-parens` disallows them.

I'm not sure what should be expected default behavior for `no-extra-parens`:

> This rule always ignores extra parentheses around the following:
>
> immediately-invoked function expressions (also known as IIFEs) such as var x = (function () {})(); and ((function foo() {return 1;})()) to avoid conflicts with the wrap-iife rule

This isn't quite an IIFE, but it is a conflict with `wrap-iife`.

**What actually happened? Please include the actual, raw output from ESLint.**

Autofix worked 10 times, so the code at the end remained unchanged, with the following errors:

```
  4:9  error  Wrap an immediate function invocation in parentheses  wrap-iife
  6:9  error  Unnecessary parentheses around expression             no-extra-parens
```

If it was set to run an odd number of times, it would basically flip those two lines.

**Are you willing to submit a pull request to fix this bug?**

Yes. I'm not sure should this be default or an option.

**Comment by kaicataldo** [comment]
Since `wrap-iife` doesn't warn on this by default, I don't think this should be the default behavior of `no-extra-parens`. Thoughts on adding a corresponding option to `no-extra-parens` (`enforceForfunctionPrototypeMethods`, maybe?) that defaults to `false`?

**Comment by mdjermanovic** [comment]
> Since `wrap-iife` doesn't warn on this by default, I don't think this should be the default behavior of `no-extra-parens`. Thoughts on adding a corresponding option to `no-extra-parens` (`enforceForFunctionPrototypeMethods`, maybe?) that defaults to `false`?

Agreed! It seems better to add an option.

Only, I think it should be `true` by default, like all other options in this rule. `true` would also retain the current default behavior.

**Comment by kaicataldo** [comment]
> Only, I think it should be true by default, like all other options in this rule. true would also retain the current default behavior.

Ah, right, got my wires crossed. That sounds good to me :+1:

**Comment by mdjermanovic** [comment]
I'm working on this.
