### ISSUE TITLE
new cap: option capIsNewExceptionPattern is not behaving as documented

### ISSUE THREAD

**Issue by l1bbcsg** [eslint/eslint#12874]
Documentation for `capIsNewExceptionPattern` says the following:
> allows any uppercase-started **function names that match** the specified regex pattern to be called without the new operator.

However, the actual behaviour seems to be that entire [call expression is matched](https://github.com/eslint/eslint/blob/439c83342c364ba3ce5168d54e165b1fe3e35630/lib/rules/new-cap.js#L211) against the pattern, not just the function name.

Either `capIsNewExceptionPattern` should match only function name, or the documentation should reflect the actual behaviour.

I believe matching code with regex is fundamentally wrong and the first option is more sane solution. So, the documentation should stay as is, behaviour corrected and example updated, but that might be a breaking change.

Additionally, [the example](https://eslint.org/docs/rules/new-cap#capisnewexceptionpattern) given as "correct code for this rule" is actually producing warnings (see demo), the reason being the regex configured does not match anything in the code at all.

Also other options of this rule may be poorly documented as well, for example `capIsNewExceptions` also states that it matches names, while actually it can match either name or full expression.

**Tell us about your environment**

Node version: v12.10.0
npm version: v6.10.3
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found

Also same result on whatever version is currently deployed as demo.

**Please show your full configuration:**

<details>
<summary>Demo links</summary>

Expected no warnings: https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbmV3LWNhcDogW1wiZXJyb3JcIiwgeyBcImNhcElzTmV3RXhjZXB0aW9uUGF0dGVyblwiOiBcIl5CYXIkXCIgfV0qL1xuXG5mb28uQmFyKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==

Not expected to ignore:
https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbmV3LWNhcDogW1wiZXJyb3JcIiwgeyBcImNhcElzTmV3RXhjZXB0aW9uUGF0dGVyblwiOiBcIl5mb29cXC5CYXIkXCIgfV0qL1xuXG5mb28uQmFyKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==

Documentation example, wrong on several accounts: https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbmV3LWNhcDogW1wiZXJyb3JcIiwgeyBcImNhcElzTmV3RXhjZXB0aW9uUGF0dGVyblwiOiBcIl5QZXJzb25cXC4uXCIgfV0qL1xuXG52YXIgZnJpZW5kID0gcGVyc29uLkFjcXVhaW50YW5jZSgpO1xudmFyIGJlc3RGcmllbmQgPSBwZXJzb24uRnJpZW5kKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==
</details>

**What did you do?**

Configuration:
```
eslint new-cap: ["error", { "capIsNewExceptionPattern": "^Bar$" }]
```

Code:
```js
foo.Bar();
```

**What did you expect to happen?**

No warnings as function named `Bar` should be ignored.

**What actually happened? Please include the actual, raw output from ESLint.**

A warning against function `Bar`.

**Are you willing to submit a pull request to fix this bug?**

Only if it's as trivial as `pattern.test(calleeName)`, but then it's probably trivial for anyone else as well.

**Comment by mdjermanovic** [comment]
Hi @l1bbcsg, thanks for the issue!

This is working as expected (ref #2584), but the documentation should be definitely improved to clarify the options and match the actual behavior (and to fix the mistake you found, `"^Person\.."` should be lowercase). 

PR to fix and improve the documentation is welcome!

The options are designed to allow users to define exceptions by object names, property names or a combination of both. A configuration for the example you provided could be:

```js
/*eslint new-cap: ["error", { "capIsNewExceptionPattern": "\.Bar$" }]*/

foo.Bar(); // no error
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbmV3LWNhcDogW1wiZXJyb3JcIiwgeyBcImNhcElzTmV3RXhjZXB0aW9uUGF0dGVyblwiOiBcIlxcLkJhciRcIiB9XSovXG5cbmZvby5CYXIoKTtcblxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**Comment by naima-shk** [comment]
@mdjermanovic  Can i get this issue please ? :)

**Comment by mdjermanovic** [comment]
Of course, PR is welcome :)

**Comment by jordanmoore753** [comment]
I'm not sure if this issue has already been addressed but just not closed yet, but if not, may I tackle the issue of improving the documentation?

**Comment by mdjermanovic** [comment]
> I'm not sure if this issue has already been addressed but just not closed yet, but if not, may I tackle the issue of improving the documentation?

@jordanmoore753 there is no PR yet, and it doesn't look like anyone is working on this at the moment, so feel free to claim this :)

**Comment by mdjermanovic** [comment]
Reopening since we have a PR for this issue.
