### ISSUE TITLE
[max-lines] - add an option to ignore imports

### ISSUE THREAD

**Issue by avalanche1** [eslint/eslint#12875]
**What rule do you want to change?**
max-lines
**Does this change cause the rule to produce more or fewer warnings?**
less
**How will the change be implemented? (New option, new default behavior, etc.)?**
new option
**Please provide some example code that this change will affect:**

```js
import doStuff from 'stuff'

doStuff()
```

**What does the rule currently do for this code?**
counts import statement as a line
**What will the rule do after it's changed?**
does not count import statement as a line
**Are you willing to submit a pull request to implement this change?**
no

**Comment by kaicataldo** [comment]
Thanks for the proposal. This seems reasonable to me, but let's see what other team members thinks.

**Comment by mdjermanovic** [comment]
I'll champion this.

**Comment by anikethsaha** [comment]
I can work on this if it gets accepted !

**Comment by kaicataldo** [comment]
@mdjermanovic Are you still championing this?

**Comment by mdjermanovic** [comment]
Since this enhancement hasn't reached consensus, and it's about a stylistic rule, I'm closing this issue in line with the recent [changes to our rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies). 

@avalanche1 thanks for the proposal!
