### ISSUE TITLE
Missing links formatting in documentation

### ISSUE THREAD

**Issue by revolter** [eslint/eslint#12894]
**What did you expect to happen?**

> These rules have been deprecated in accordance with the [deprecation policy](/docs/user-guide/rule-deprecation), and replaced by newer rules:

**What actually happened? Please include the actual, raw output from ESLint.**

Links are not formatted in the docs (e.g. https://eslint.org/docs/rules/#deprecated):

> These rules have been deprecated in accordance with the \[deprecation policy](/docs/user-guide/rule-deprecation), and replaced by newer rules:

**Are you willing to submit a pull request to fix this bug?**

Depends.

**Comment by kaicataldo** [comment]
A PR to fix this would be welcome! I believe the code in question can be found [here](https://github.com/eslint/eslint/blob/caeb223c4f7b0b6fe35e5348ae0df4c6446b5bed/conf/category-list.json#L13). When we run a release, all the documentation in this repository is copied over to https://github.com/eslint/website and rendered [in this file](https://github.com/eslint/website/blob/master/docs/rules/index.liquid#L34).

**Comment by revolter** [comment]
And what is the command that generates the documentation? So I / we have an easier starting point 😃

**Comment by kaicataldo** [comment]
Good question! [This](https://github.com/eslint/eslint/blob/master/Makefile.js#L587) is the target script we run when we're generating the site (which occurs when we run a release, not on every commit to `master`).

**Comment by revolter** [comment]
It doesn't generate any HTML file (apart from the fact that the tests fail, and that it can't create its own directories).

**Comment by kaicataldo** [comment]
That's correct - we generate the site from Markdown files copied over into https://github.com/eslint/website (using [this command](https://github.com/eslint/website/blob/master/package.json#L20)).

**Comment by revolter** [comment]
Yeah, too complex for a new contributor. But I can tell you that Markdown doesn't work at all on that page.
