### ISSUE TITLE
prefer-destructuring false-positive if already declared in upper scope

### ISSUE THREAD

**Issue by marcospgp** [eslint/eslint#12902]
I ran into this issue today and saw it had already been posted before a few times:

https://github.com/eslint/eslint/issues/9734
https://github.com/eslint/eslint/issues/10067
https://github.com/eslint/eslint/issues/9108
https://github.com/eslint/eslint/issues/6926

But was closed by a bot without a decision being made. I'd like to vouch for the fix 🙂

**Comment by mdjermanovic** [comment]
@marcospgp could you please fill out the [bug report template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) so we can know what exactly seems to be a bug?

The links you provided look like different bug reports. I believe some of them have been already fixed, while some were not actually a bug.
