### ISSUE TITLE
Investigate supporting ES6/JSX

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1291]
After many requests and some soul-searching, I've come around to believing that ESLint should optionally support JSX. My rationale is based on:

1. The growing popularity of React/JSX
2. The existence of Esprima-FB and estraverse-FB

There is still the issue of escope not supporting es6 scoping rules and relying on estraverse directly, but that may be solvable. 

The way I'm envisioning this working is by allowing you to specify one of four JavaScript modes:

1. ECMAScript 3
2. ECMAScript 5
3. ECMAScript 6
4. JSX

That means ECMAScript 6 support is separate from JSX support. You opt-in to JSX, you get whatever is in Esprima-FB vs. opting in to ES6, which should not support JSX syntax. 

This issue is to gather investigation data to determine how this can be achieved and what blockers might exist.

**Comment by nzakas** [comment]
#1602 adds the ability to set the feature flags for Espree, which allows turning on ES6 features and JSX.

#1640 makes sure traversal of JSX nodes works correctly

**Comment by nzakas** [comment]
Closing as 0.12.0 introduced support for JSX and partial ES6 support.

**Comment by StoneCypher** [comment]
:trophy:
