### ISSUE TITLE
no-multi-spaces does not respect AssignmentExpression

### ISSUE THREAD

**Issue by paulschreiber** [eslint/eslint#12918]
See previous discussion in #12910. 

no-multi-spaces does not respect AssignmentExpression, and reports errors.

**Tell us about your environment**
* **ESLint Version:** 6.8.0
* **Node Version:** 10.16.3
* **npm Version:** 6.13.7

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "no-multi-spaces": ["error", { "exceptions": { "AssignmentExpression": true } }]
        }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function foo() {
    return (
        <aside>
            <NewsList
                header     = {header}
                articles   = {articles}
                footerLink = {footerLink}
            />
        </aside>
    );
}

function bar() {
  var header, articles; footerLink;

  header     = 1;
  articles   = 2;
  footerLink = 3;
}
```

```bash
./node_modules/.bin/eslint -c eslintrc.json test.jsx
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
/Users/paul/test/test.jsx
  5:23  error  Multiple spaces found before '='  no-multi-spaces
  6:25  error  Multiple spaces found before '='  no-multi-spaces

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by kaicataldo** [comment]
JSX attributes are represented by a different Node type than `AssignmentExpression`s  in [ESTree](https://github.com/estree/estree) (the spec ESLint's AST follows). You'll want to add `JSXAttribute` to the exceptions:

```js
/*eslint "no-multi-spaces": [
	"error", { 
    	"exceptions": { 
        	"AssignmentExpression": true,
            "JSXAttribute": true
        } 
    }
]*/

function foo() {
    return (
        <aside>
            <NewsList
                header     = {header}
                articles   = {articles}
                footerLink = {footerLink}
            />
        </aside>
    );
}

function bar() {
  var header, articles; footerLink;

  header     = 1;
  articles   = 2;
  footerLink = 3;
}
```

You see an example of this using our [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgXCJuby1tdWx0aS1zcGFjZXNcIjogW1xuXHRcImVycm9yXCIsIHsgXG4gICAgXHRcImV4Y2VwdGlvbnNcIjogeyBcbiAgICAgICAgXHRcIkFzc2lnbm1lbnRFeHByZXNzaW9uXCI6IHRydWUsXG4gICAgICAgICAgICBcIkpTWEF0dHJpYnV0ZVwiOiB0cnVlXG4gICAgICAgIH0gXG4gICAgfVxuXSovXG5cbmZ1bmN0aW9uIGZvbygpIHtcbiAgICByZXR1cm4gKFxuICAgICAgICA8YXNpZGU+XG4gICAgICAgICAgICA8TmV3c0xpc3RcbiAgICAgICAgICAgICAgICBoZWFkZXIgICAgID0ge2hlYWRlcn1cbiAgICAgICAgICAgICAgICBhcnRpY2xlcyAgID0ge2FydGljbGVzfVxuICAgICAgICAgICAgICAgIGZvb3RlckxpbmsgPSB7Zm9vdGVyTGlua31cbiAgICAgICAgICAgIC8+XG4gICAgICAgIDwvYXNpZGU+XG4gICAgKTtcbn1cblxuZnVuY3Rpb24gYmFyKCkge1xuICB2YXIgaGVhZGVyLCBhcnRpY2xlczsgZm9vdGVyTGluaztcblxuICBoZWFkZXIgICAgID0gMTtcbiAgYXJ0aWNsZXMgICA9IDI7XG4gIGZvb3RlckxpbmsgPSAzO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlfX19).

**Comment by paulschreiber** [comment]
@kaicataldo Should https://eslint.org/docs/rules/no-multi-spaces be updated to list JSXAttribute?

**Comment by kaicataldo** [comment]
I [commented](https://github.com/eslint/eslint/issues/12910#issuecomment-586506411) on the other issue. Let's discuss documentation updates there so that the discussion isn't spread over multiple issues :)
