### ISSUE TITLE
Categorized Changelog

### ISSUE THREAD

**Issue by bmish** [eslint/eslint#12931]
**The version of ESLint you are using.** N/A

**The problem you want to solve.**

The changelog published in [CHANGELOG.md](https://github.com/eslint/eslint/blob/master/CHANGELOG.md) and in the Github [Releases](https://github.com/eslint/eslint/releases) page is not as human-readable as it could be. Developers like myself love to read about the dozens of great changes that go into each release, but the changelog often looks like a wall of text in seemingly-random order, making it hard for us to quickly parse and understand it. For example, I'm often interested to find out what new rules are in a release, but these entries are often scattered throughout the list as opposed to being grouped together.

**Your take on the correct solution to problem.**

Many other packages have adopted categorized changelogs for their releases (typically handled by an automatic changelog generator). Eslint changes are already prefixed by category (`New`, `Docs`, `Chore`, etc), so simply alphabetizing the list would be the easiest way to achieve this. An even better way would be to separate out each category into its own list and then remove the redundant prefixes. This way, the most important change lists (`Breaking`, etc) could come at the beginning while the least important lists (`Chore`, etc) could come at the end.

Before:

```
vX.Y.Z - February 17, 2020

* abcdefg New: add my-new-rule (PR Number) (Author Name)
* abcdefg Fix: fix bug in some rule (PR Number) (Author Name)
* abcdefg Breaking: some breaking change (PR Number) (Author Name)
* abcdefg Fix: fix another bug in some rule (PR Number) (Author Name)
* abcdefg Chore: clean something up (PR Number) (Author Name)
* abcdefg New: and my-other-new-rule (PR Number) (Author Name)
```

After

```
vX.Y.Z - February 17, 2020

Breaking:
* abcdefg some breaking change (PR Number) (Author Name)

New:
* abcdefg add my-new-rule (PR Number) (Author Name)
* abcdefg and my-other-new-rule (PR Number) (Author Name)

Fix:
* abcdefg fix another bug in some rule (PR Number) (Author Name)
* abcdefg fix bug in some rule (PR Number) (Author Name)

Chore:
* abcdefg clean something up (PR Number) (Author Name)
```

Here's a real world [example](https://github.com/ember-cli/eslint-plugin-ember/blob/master/CHANGELOG.md#v780-2020-02-12).

Related issues: #3155

**Are you willing to submit a pull request to implement this change?**

Possibly but I'm not sure offhand where this change would be made?

**Comment by kaicataldo** [comment]
I agree it would be nice to format things in a more human-readable format on the GitHub releases page. We do make an effort to do this in our official change log posts on https://eslint.org. You can see an example [here](https://eslint.org/blog/2019/12/eslint-v6.8.0-released).

**Comment by bmish** [comment]
Should be fixed by https://github.com/eslint/eslint/issues/14231.
