### ISSUE TITLE
Parser in extended configuration isn't resolved relatively to current directory, opposite to plugins

### ISSUE THREAD

**Issue by etki** [eslint/eslint#12949]
I have a monorepo with similar subpackages which i have quite the same config for, so obviously i'd prefer having single eslintrc for them all, where i specify `@typescript-eslint/parser` parser. When it comes to running eslint in `src/<subpackage>` (`cd src/subpackage; yarn eslint 'src/**/*.ts'`), it finds root configuration (whether it's only configuration, extended configuration or implicitly merged configuration) and tries to load `@typescript-eslint/parser` from there, but it is installed only within `src/<subpackage>/node_modules` (which is also actual home for running eslint binary), thus eslint fails. It would be great to perform parser loading in a way that is used plugins according to documentation:

>Note: Plugins are resolved relative to the current working directory of the ESLint process. In other words, ESLint will load the same plugin as a user would obtain by running require('eslint-plugin-pluginname') in a Node REPL from their project root.

**The version of ESLint you are using.**

6.8.0

**Any workarounds?**

Just placing `.eslintrc.yml` with single parser option in subpackage directory makes the day.

**Are you willing to submit a pull request to implement this change?**

Sorry, nope, i'm not a JS/TS developer until it comes absolutely necessary.

**Comment by mysticatea** [comment]
Thank you for this issue.

We are going in the opposite direction -- ESLint loads plugins as well from the directory of each config file that declares the plugin since ESLint 7. This is similar to `require()` in each config file.

Therefore, you have to install the necessary plugins/parsers to beside your config file.
