### ISSUE TITLE
Support querying for nodes using the eslint node selector syntax from an individual node

### ISSUE THREAD

**Issue by suchanlee** [eslint/eslint#12941]
**The version of ESLint you are using.**

6.4.0

**The problem you want to solve.**

Want to be able to query for nodes using the eslint node selector syntax from a particular node, instead of the main visitor body callback, to make it easier to locate nodes that maybe relevant for writing descriptive error messages or fixes. Eslint already has an amazing selector syntax, so it would be great to be able to utilize it here too.

Currently, once you're in the visitor, all the traversal has to be done manually.

**Your take on the correct solution to problem.**

Like how `.querySelector()` exists not only for the `document` but for every element in the DOM, I think that adding a similar method for each node would be nice. Another approach could be to add it to the `context` object, something like `context.queryNodes(rootNode, selector)`.

**Are you willing to submit a pull request to implement this change?**

Sure but could be easier for someone with a more intimate knowledge of ESLint internals

**Comment by kaicataldo** [comment]
I really like this idea! I think it would be better to include it in the context object that's passed to each rule (maybe on `SourceCode`)? Since this is a change to core, we'll probably want to write up an RFC.

**Comment by g-plane** [comment]
Will `SourceCode` be confusing? Personally, I think this proposal is related to AST, not source code which is represented as text.
This is also similar with `document` and `querySelector`: the `querySelector` method acts on document which is parsed from HTML, not HTML itself directly.

**Comment by kaicataldo** [comment]
That's a good point. Regardless of where we decide it should go, I'm in support of adding this functionality to core :+1:

**Comment by mysticatea** [comment]
I wonder how it's different from `const esquery = require("esquery"); esquery(node, "selector")`.
I'm not sure if it should be in ESLint core.

**Comment by kaicataldo** [comment]
That's right. Seems like it would be a useful utility to expose to all rules.
