### ISSUE TITLE
typescript-eslint/no-var returns error for declare var

### ISSUE THREAD

**Issue by noh626** [eslint/eslint#12940]
I am using @typescript-eslint/eslint-plugin and parser @ 2.20.0.

With no-var rule turned on, ESlint keeps failing for 'declare var' statement.

I can't change it to 'declare let'. Is there a way to resolve or ignore this error?

Thanks,

**Comment by g-plane** [comment]
Hi @noh626 , `declare` is a TypeScript syntax. Maybe you can open a new issue at the repository of typescript-eslint and ask for discussion.

**Comment by kaicataldo** [comment]
Closing this issue since it's related to usage of `@typescript-eslint/eslint-plugin`.
