### ISSUE TITLE
[no-setter-return] Add option to ignore `set: () => value`

### ISSUE THREAD

**Issue by Alhadis** [eslint/eslint#12958]
**What rule do you want to change?**  
[`no-setter-return`](https://eslint.org/docs/rules/no-setter-return)

**Does this change cause the rule to produce more or fewer warnings?**  
Fewer warnings if enabled.

**How will the change be implemented? (New option, new default behaviour, etc.)?**  
Adding an object as an optional second parameter which supports the option `ignoreExpressions` (or something similarly-named):

~~~json
{
	"no-setter-return": [
		"error",
		{
			"ignoreExpressions": "always | never | ignore" 
		}
	]
}
~~~

**Please provide some example code that this change will affect:**  
In the setter function below, the return value is purely implicit, and shouldn't be held in the same light as an explicit `return` statement (which *is* indicative of a refactoring or authoring error):

~~~js
let foo;
Object.defineProperty(subject, "foo", {
	get: () => foo,
	set: to => foo = to,
});
~~~

**What does the rule currently do for this code?**  
Raise an error because an assigned value is implicitly returned by an arrow-function expression.

**What will the rule do after it's changed?**  
Allow authors to keep their getter/setter pairs terse and nicely-aligned (as illustrated above).

**Are you willing to submit a pull request to implement this change?**  
Yes.

**Comment by kaicataldo** [comment]
Just to be clear

**Comment by ljharb** [comment]
The rule is precisely to block a return value though - in your case, you're not trying to return anything, so you definitely should be using curly braces.

**Comment by Alhadis** [comment]
> Is there a reason you don’t want to wrap the body of the arrow function expression in braces?

Fewer lines and easier vertical alignment of similarly-named property-setters that are more amenable to multi-cursor editing. But forget it, I can already see where this has headed: _"just make a plugin for it, lol"_

> The rule is precisely to block a return value though 

This:

~~~js
Object.defineProperty({}, "value", {
	set: (to) => {
		return this.value = to + 45;
	},
});
~~~

is entirely different to this:

~~~js
Object.defineProperty({}, "value", {
	set: to => value = to,
});
~~~

… because the author has consciously written a `return` statement, as opposed to omitting braces for conciseness.

> so you definitely should be using curly braces.

Great. Glad I disabled the rule then. 👍 I'll just add a hairy `no-restricted-syntax` selector to target pointless `return` statements in whatever quacks like a setter function instead. Case closed.

**Comment by ljharb** [comment]
It's not different, because observably from the caller (in this case, they'd have to extract it from the property descriptor, ofc), it's the same.

**Comment by Alhadis** [comment]
Different in **the author's _intent_**. Did you not read the part immediately under the second code-block?

**Comment by ljharb** [comment]
Sure. The author's intent is irrelevant though when it would cause an observable difference - especially in this case where that difference *violates* the author's intent. If your intent was not to return a value, you'd need the curly braces - by omitting them, it's impossible to intend anything that doesn't include "return a value" ¯\\\_(ツ)_/¯

**Comment by Alhadis** [comment]
@ljharb No, the intent was keeping code brief when a return value is meaningless, irrespective of whether somebody's siphoned a setter out of a property descriptor or not.

I already regret filing this stupid issue.
