### ISSUE TITLE
Can't find config when Node version > 12.x.x

### ISSUE THREAD

**Issue by RyanChristian4427** [eslint/eslint#12954]
**Tell us about your environment**

* **ESLint Version: v6.8.0 (Currently used)**
* **Node Version: v13.8.0**
* **npm Version: v6.13.7**

**What parser (default, Babel-ESLint, etc.) are you using?**

@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports =  {
    parser:  '@typescript-eslint/parser',
    extends:  [
        'preact',
        'plugin:@typescript-eslint/recommended',
        'prettier/@typescript-eslint',
        'plugin:prettier/recommended'
    ],
    settings: {
        react: {
            pragma: 'h',
            version: 'detect'
        },
    },
    parserOptions:  {
        ecmaVersion:  2018,
        sourceType:  'module',
        ecmaFeatures: {
            jsx: true
        }
    },
    ignorePatterns: ['build/'],
    rules:  {
        'indent': ['warn', 4, { "SwitchCase": 1, "ignoredNodes": ["TemplateLiteral > *"] }],
        'react/jsx-indent': ['warn', 4],
        'react/jsx-indent-props': ['warn', 4],
        'react/no-unknown-property': ['error', { ignore: ['class'] }],
        'react/no-unescaped-entities': ['warn'],
        'react/jsx-no-bind': ['off'],
        'quotes': 'off',
        '@typescript-eslint/quotes': ['warn', 'single'],
        '@typescript-eslint/no-use-before-define': ['off'],
        'arrow-parens': 'warn',
        '@typescript-eslint/ban-ts-ignore': ['warn'],
        '@typescript-eslint/interface-name-prefix': 'off',
        'semi': 'off',
        '@typescript-eslint/semi': ['warn'],
    },
    overrides: [
        {
            files: ["*.js"],
            rules: {
                "@typescript-eslint/explicit-function-return-type": "off",
            }
        }
    ]
};
```

</details>

```bash
eslint src/**/*.{js,ts,tsx} --fix
```

**What did you expect to happen?**
Eslint to run against my application using the preact config

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "preact" to extend from. Please check that the name of the config is correct.

The config "preact" was referenced from the config file in "/x/x/x/.eslintrc.js".
```

I added the eslint-config-preact package to my application to replace the React config, as I do use Preact, and this was fine and worked on my machine. However, once the build server failed, I noticed multiple coworkers had the same issue. Eventually I came to checking versions of Node, and noticed Eslint won't be able to find that config if the version is greater than 12.x.x.

If this isn't an Eslint issue but an issue with the config itself, I can always create an issue there, but I'd assume it's the underlying tool first.

**Comment by aladdin-add** [comment]
have you installed `eslint-config-preact`? plus, adding `--debug` could be helpful to find what's going wrong. :)

**Comment by RyanChristian4427** [comment]
Of course I made sure it was installed, it was only after systems seemingly at random could run the linter did I start to dig into Node and NPM versions. The following is the output of running with the debug flag:

```
eslint:cli CLI args: [ 'src/**/*.{js,ts,tsx}', '--fix', '--debug' ] +0ms
  eslint:cli Running on files +3ms
  eslint:config-array-factory Loading JSON config file: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/package.json +0ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/node_modules/*', '/bower_components/*' ], basePath: '/home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app', patterns: [ '/node_modules/*', '/bower_components/*' ] } +2ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/node_modules/*', '/bower_components/*' ], basePath: '/home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app', loose: false } ] +1ms
  eslint:ignore-pattern   processed: { basePath: '/home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app', patterns: [ '/node_modules/*', '/bower_components/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [ 'src/**/*.{js,ts,tsx}' ] +0ms
  eslint:file-enumerator Glob: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/src/**/*.{js,ts,tsx} +1ms
  eslint:file-enumerator recursive? true +2ms
  eslint:file-enumerator Enter the directory: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/src +0ms
  eslint:cascading-config-array-factory Load config files for /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/src. +0ms
  eslint:cascading-config-array-factory No cache found: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/src. +0ms
  eslint:config-array-factory Config file not found on /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/src +7ms
  eslint:cascading-config-array-factory No cache found: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app. +1ms
  eslint:config-array-factory Loading JS config file: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/.eslintrc.js +0ms
  eslint:config-array-factory Config file found: /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/.eslintrc.js +1ms
  eslint:config-array-factory Loading {extends:"preact"} relative to /home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/.eslintrc.js +0ms

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "preact" to extend from. Please check that the name of the config is correct.

The config "preact" was referenced from the config file in "/home/ubuntu/buildAgent/work/da14275a8c39b99c/packages/web-app/.eslintrc.js".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.

(node:15958) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
```
It works without issue if I set my Node version to 12.x, but if I go up to 13.x, it fails.

**Comment by ljharb** [comment]
Looks like "eslint-config-preact" is using the "exports" field, which is newly respected in node 13.3+, and the "conditional exports" feature, which was added in v13.7.

Adding the "exports" field is a breaking change in almost every case; eslint-config-preact seems to have added it in a minor version (v1.1). See https://unpkg.com/browse/eslint-config-preact@1.1.0/package.json. The "main" and the "require" are the same, so it should work in v13.7+, but because it lacks a "default" as well, it *will not* work in node v13.3 - v13.6.

**Comment by RyanChristian4427** [comment]
Sorry for the delay, thanks. I'll bring this issue over to the config's repo. 

I am able to confirm that it does not work on any v13 that I've tried, including < v13.3 and > 13.7. I went through every minor release just to be sure.

**Comment by marvinhagemeister** [comment]
Just had a look at it and it turns out that conditional exports **must** be declared as relative paths. That's different to the `main` and `module` fields where the leading `./` can be omitted. Made a PR against our preact config to fix that. It's an issue in our package not in eslint, so I think this can be closed :+1:

**Comment by ljharb** [comment]
Indeed, that is true. Only main/bin have the legacy mistake of not requiring `./` for relative paths.

**Comment by RyanChristian4427** [comment]
Sorry, got busy, accidentally let this slip my mind. I'll close this, as it isn't the fault of eslint at all.
