### ISSUE TITLE
Update: rule 'padding-line-between-statements' - add number of lines

### ISSUE THREAD

**Issue by IgorNovozhilov** [eslint/eslint#12979]
[x] Documentation update
 [x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
 [x] Add autofixing to a rule

**What rule do you want to change?**

<https://eslint.org/docs/rules/padding-line-between-statements>

**Does this change cause the rule to produce more or fewer warnings?**

No, the number of warnings will remain the same.

**How will the change be implemented? (New option, new default behavior, etc.)?**

For this rule, the set of possible options for using the `blankLine` parameter
    will be expanded by adding the ability to specify the required number of blank lines.

**Please provide some example code that this change will affect:**

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: 2, prev: "*", next: "class" },
    { blankLine: 2, prev: "class", next: "*" }
]*/

"use strict";


class A {}


function b() {}
```

**What does the rule currently do for this code?**

Currently, you cannot specify the required number of blank lines.

**What will the rule do after it's changed?**

The rule will start using the number of blank lines only after setting the `blankLine` parameter to a numeric value.
In this case, the problem will be displayed if the number of blank lines is greater than or less than the specified value.

**What changes did you make? (Give an overview)**

1.  Added ability to specify numeric value in `meta.schema.definitions.paddingType`
2.  Added a new message view with the number of blank lines
3.  Added to `function verifyForAlways` output of new messages depending on `blankLine` parameter
4.  Changed the "rule fixer" so that it could replace blocks in the code with the required number of blank lines
5.  In `function getPaddingLineSequences` added search the current number of blank lines to display in the problem message
6.  Updated tests and documentation

**Is there anything you'd like reviewers to focus on?**

Do I need to cover any other cases with tests?

**Example**
This change will improve the readability of the source code by highlighting the concept blocks.
And it will also automate the process of formatting.

Here is an example of the configuration I plan to use with these updates:

```js
  "rules": {
    "lines-between-class-members": "error",
    "padding-line-between-statements": [
      "error",
      { "blankLine": 1, "prev": "*", "next": ["cjs-import", "cjs-export"] },
      { "blankLine": 1, "prev": ["cjs-import", "cjs-export"], "next": "*" },
      { "blankLine": 2, "prev": "expression", "next": ["cjs-import", "cjs-export"] },
      { "blankLine": 2, "prev": ["cjs-import", "cjs-export"], "next": "expression" },
      { "blankLine": 2, "prev": "*", "next": ["class", "function"] },
      { "blankLine": 2, "prev": ["class", "function"], "next": "*" },
      { "blankLine": 1, "prev": ["directive", "const", "let"], "next": "expression" },
      { "blankLine": 1, "prev": "expression", "next": ["const", "let", "return"] },
      { "blankLine": "never", "prev": "cjs-import", "next": "cjs-import" },
      { "blankLine": "never", "prev": "cjs-export", "next": "cjs-export" }
    ],
    "padded-blocks": [
      "error",
      { "blocks": "never", "classes": "always", "switches": "never" },
      { "allowSingleLineBlocks": true }
    ]
  }
```

Before `eslint . --fix`

```js
'use strict'
const any = require('any')
const { any2 } = require('any2')
const CONST1 = 'CONST1'
const CONST2 = 'CONST1'
/**
 * My class
 */
class Test {
  constructor() {
    this.a = any + any2 + CONST1
  }
  any(a) {
    let anyText = 'any'
    if (a) {
      anyText = 'a' + CONST2
    }
    return anyText
  }
}
/**
 * My function
 */
function test() {
  const t = new Test()
  console.log(t)
  return t
}
console.log('any' + test())
module.exports.Test = Test
module.exports.test = test
```

After `eslint . --fix`

```js
'use strict'

const any = require('any')
const { any2 } = require('any2')

const CONST1 = 'CONST1'
const CONST2 = 'CONST1'


/**
 * My class
 */
class Test {

  constructor() {
    this.a = any + any2 + CONST1
  }

  any(a) {
    let anyText = 'any'
    if (a) {
      anyText = 'a' + CONST2
    }
    return anyText
  }

}


/**
 * My function
 */
function test() {
  const t = new Test()

  console.log(t)

  return t
}


console.log('any' + test())


module.exports.Test = Test
module.exports.test = test
```

**PR:** https://github.com/eslint/eslint/pull/12663
> issues: https://github.com/eslint/eslint/issues/12634

**Comment by IgorNovozhilov** [comment]
Тема не раскрыта, PR готово, отзыва "все плохо - не мержим" не получено. :seedling:

**Comment by kaicataldo** [comment]
I think this addition makes sense. Let's see what the rest of the team thinks.

**Comment by IgorNovozhilov** [comment]
:disappointed:
