### ISSUE TITLE
Document configuration hierarchy merge principles

### ISSUE THREAD

**Issue by leventov** [eslint/eslint#12974]
**The problem you want to solve.**
In [Configuration Cascading and Hierarchy](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) documentation, I've not been able to find the explanation of how the configurations are inherited.

For example, if I have `plugins: ["my-plugin"]` in `/my/dir/.eslintrc.js` and `plugins: ["my-plugin2"]` in `/my/dir/subdir/.eslintrc.js`, does this mean that both `my-plugin` and `my-plugin2` will be applied on the `subdir/` level, or only `my-plugin2`? The same uncertainty applies to `extends` and `rules`.

**Are you willing to submit a pull request to implement this change?**
No

**Comment by kaicataldo** [comment]
From the [plugins](https://eslint.org/docs/user-guide/configuring#configuring-plugins) section of the docs:
> Plugins are resolved relative to the current working directory of the ESLint process. In other words, ESLint will load the same plugin as a user would obtain by running require('eslint-plugin-pluginname') in a Node REPL from their project root.

And from the [shareable config](https://eslint.org/docs/user-guide/configuring#extending-configuration-files) docs:
> Relative paths and shareable config names in an extends property are resolved from the location of the config file where they appear.

Happy to accept a PR if you have an idea of how we could improve the documentation!
