### ISSUE TITLE
Heap out of memory is thrown when different line endings are configured

### ISSUE THREAD

**Issue by jeroennijhuis** [eslint/eslint#12973]
I am currently developing a Nuxt app (version 2.11.0) and i am using eslint (version 6.8.0). The latter caused my app to crash when serving my app locally. While other developers had not problem when serving the app, I ended up with the exception attached to this report.

[hom-exception.txt](https://github.com/eslint/eslint/files/4265938/hom-exception.txt)

The `--max-old-space-size` configuration in node didn't solve the problem. After a few days we noticed when disabling some eslint config, that it didn't throw any exception. But it reported a huge list of errors, all mentioning an incorrect line ending config (CRLF instead of LF). When fixing all line endings in the repository, eslint ran fine. 

We assume eslint couldn't handle this number of errors and because of an incorrect line ending configuration, we ended up with a Heap out of memory exception. 

It might be better handle the eslint errors differently, avoiding any heap out of memory occurence when there's just to much to fix. It would have saved at least a few days on figuring out the root cause.

**Comment by kaicataldo** [comment]
How is ESLint causing the application to crash? Are you using ESLint as a direct dependency in your application?

Do you have a suggestion as to what we could do differently in this case?
