### ISSUE TITLE
Unable to resolve path to module 'dotenv-webpack'. (import/no-unresolved)

### ISSUE THREAD

**Issue by gonjavi** [eslint/eslint#12990]
This is my webpack config.js

const path = require('path');
const Dotenv = require('dotenv-webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  performance: {
    hints: false,
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader',
        ],
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader',
        ],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: [
          'file-loader',
        ],
      },
    ],
  },
  plugins: [
    new Dotenv()
  ],
};

I am having this eslint problem:
@stickler-ci
stickler-ci
/ stickler-ci

**webpack.config.js#L2
Unable to resolve path to module 'dotenv-webpack'. (import/no-unresolved)**

How to solve it

**Comment by mdjermanovic** [comment]
Hi @gonjavi, thanks for the issue!

> Unable to resolve path to module 'dotenv-webpack'. (import/no-unresolved)

This message is from the `import/no-unresolved` rule (third-party plugin `eslint-plugin-import`).

Can you please create an issue in the `eslint-plugin-import` repository:

https://github.com/benmosher/eslint-plugin-import

**Comment by kaicataldo** [comment]
Closing this issue since this question has been answered.
