### ISSUE TITLE
`padded-blocks`: Add "iife" object option

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#12993]
**What rule do you want to change?**

`padded-blocks`

**Does this change cause the rule to produce more or fewer warnings?**

Either more or fewer warnings or no change, depending on the configuration.

**How will the change be implemented? (New option, new default behavior, etc.)?**

A new property to add to the option object, `iife`.

**Please provide some example code that this change will affect:**

Now these will change to produce **no warnings**:

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "never",
    "iife": "always"
}]*/

(() => {

requirePaddingHere();

})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "never",
    "iife": "always"
}]*/

(async () => {

await requirePaddingHere();

})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "always",
    "iife": "never"
}]*/

(() => {
preventPaddingHere();
})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "always",
    "iife": "never"
}]*/

(async () => {
await preventPaddingHere();
})();
```

Now these will change to produce **new warnings**:

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "always",
    "iife": "never"
}]*/

(function () {

preventPaddingHere();

})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "always",
    "iife": "never"
}]*/

(async function () {

preventPaddingHere();

})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "never",
    "iife": "always"
}]*/

(() => {
requirePaddingHere();
})();
```

```js

/* eslint padded-blocks: ["error", { 
    "blocks": "never",
    "iife": "always"
}]*/

(async () => {
await requirePaddingHere();
})();
```

**What does the rule currently do for this code?**

Reports an error or fails to report an error.

**What will the rule do after it's changed?**

- If the context is an IIFE and the rule's existing (string or `blocks` object) option is set to

    - "always" (the default behavior of requiring padding), AND the proposed `iife` option is set to "never"

        - ...there will be **Fewer warnings** if the IIFE has no padding

        - ...there will be **More warnings** if the IIFE has padding

    - "never" (the non-default of disallowing padding) AND the proposed `iife` option is set to "always"

        - ...there will be **Fewer warnings** if the IIFE has padding

        - ...there will be **More warnings** if the IIFE has no padding

- Under any of these other possibilities, **no changes** will occur.

    - The context is not an IIFE

    - The user does not use the new `iife` option

    - The `iife` option value matches the string or `blocks` object option value

**Are you willing to submit a pull request to implement this change?**

Possibly, yes. :)

**Comment by fab1o** [comment]
I think this would be a better call: https://github.com/eslint/eslint/issues/12997

**Comment by brettz9** [comment]
Apologies, I see my examples didn't have the padding that I would like not to be reported, but were instead showing what was being expected.

That option looks like it would be fine for some, but some of us don't normally want one extra line break around other blocks. I personally don't like the following as I find it unnecessarily sparse:

```js
if (cond) {

  beginHere();

}
```

But with IIFE's I think they are a little too noisy looking not to allow some padding before/after them (despite not even being a complete statement).

For example, in README docs (which some of us also lint through `eslint-plugin-markdown`), this looks to me to be crowded:

```js
(async () => {
await dontRequirePaddingHere();
})();
```

while I do not think this looks too crowded:

```js
if (cond) {
  beginHere();
}
```

**Comment by brettz9** [comment]
I might be ok though with an option which interacted with `indent` such that padding became allowed when `indent` was disabled for such blocks. But I understand the desire for atomic rules in eslint would prevent such a rule.

**Comment by mdjermanovic** [comment]
@brettz9 I think the description in "What will the rule do after it's changed?" still refers to the original examples before the edit?

**Comment by brettz9** [comment]
Ugh, yes, thanks. I really don't know what I was thinking. I've amended to:

>  Not report an error when the `iife` option is added and set to `"always"` (setting it to "never" or omitting it, will behave as before)

**Comment by mdjermanovic** [comment]
> **Does this change cause the rule to produce more or fewer warnings?**
> 
> Fewer warnings if the option is set.

Maybe I don't understand the proposal, but if the value in `iife` overrides the setting that would be used otherwise, then it could also produce more warnings?

```js
/* eslint padded-blocks: ["error", { 
    "blocks": "never",
    "iife": "always"
}]*/

(function () {
dontPreventPaddingHere();
})();
```

**Comment by brettz9** [comment]
Apologies. I've amended to state:

> Fewer warnings if the option is set **to "always".**

As far as:

> then it could also produce more warnings?

Yes, you're right. I've amended and spelled out what should happen under more conditions.

**Comment by mdjermanovic** [comment]
Thanks for all the details!

I support this :+1: 

So, for an IIFE in the code and the object configuration, `"always"`/`"never"` value that applies would be the value set in `"iife"` if it's specified. Otherwise, the value set in `"block"`.

If `"block"` also isn't specified, then the IIFE will be ignored, like all other blocks.

It could be a bit confusing that `"iife"`, which overrides `"block"`, is at the same level in configuration (and would be even more confusing if someone asks to add `"function"`), but there is already a precedent of such configuration in the `padding-lines-between-statements` rule.
