### ISSUE TITLE
Documentation bug: Re: linting `node_modules`

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#13006]
**The version of ESLint you are using.**

6.8.0

**The problem you want to solve.**

Per https://eslint.org/docs/user-guide/command-line-interface , there is an implied need to ignore `node_modules` (which seems no longer to be the case per #1163):

1. Here's one:

> Here's a simple example of a .eslintignore file:
>  node_modules/*

2. Also on https://eslint.org/docs/user-guide/configuring , the need to ignore `node_modules` seems implicit here as well:

> "ignorePatterns": ["temp.js", "node_modules/"],

3. While the following implies the opposite, I think the text could be clarified here a bit too:

> In addition to any patterns in a .eslintignore file, ESLint always ignores files in /node_modules/* and /bower_components/*.
> ...
> \# /node_modules/* and /bower_components/* in the project root are ignored by default

The first line is confusing as it seems to suggest one cannot get linting of `node_modules` or `bower_components` yet it is possible to reenable both of them with `!`.

**Your take on the correct solution to problem.**

1. Remove `node_modules` from the examples unless to point out that one can undo the default (it may be helpful to mention that `!.eslintrc.js` (or `!.*.js`) can be added back too, at least until eslint 7 may change this behavior for `!.eslintrc.js`).
2. For the third case, I think it should instead say in the first line "ESLint always ignores files by default in ..." since I am (thankfully!) able to reapply linting of `node_modules` (or `bower_components`) by adding `!node_modules/**` to an ignore (within an `.eslintignore` file or by a command such as `$(npm bin)/eslint --no-inline-config --ignore-pattern='!node_modules/**' .`). (I truly hope this functionality will never be dropped, btw!)

**Are you willing to submit a pull request to implement this change?**

Not at this time.

**Comment by kaicataldo** [comment]
Agreed that the docs could be improved here.
