### ISSUE TITLE
Acorn is outdated with vulnerability

### ISSUE THREAD

**Issue by idanavr** [eslint/eslint#13012]
**The version of ESLint you are using.**
6.8.0

**The problem you want to solve.**
Regular Expression Denial of Service.
![image](https://user-images.githubusercontent.com/28144178/76141747-e94d1200-606f-11ea-930d-1144b16aa194.png)

**Your take on the correct solution to problem.**
Update the package version of Acorn to 7.1.1 or later.
For now users can use the command:
`npm update acorn --depth 3`

**Are you willing to submit a pull request to implement this change?**
Sure.

**Comment by hugoluchessi** [comment]
Actually is Espree which has an outdated reference to Acorn.

Espree PR https://github.com/eslint/espree/pull/434 to fix that.

We need this PR merged to release a new version to fix it here.

**Comment by kaicataldo** [comment]
Thanks for reporting this. While I think it’s prudent to bump the version of Acorn in Espree’s `package.json`, please note that it seems like this is only an issue if Acorn is used as a runtime dependency in a Node service (rather than just running ESLint itself).

**Comment by jsejcksn** [comment]
I see that #13026 needs a review, but is there anything else blocking it from being merged and shipping a patch update?

**Comment by kaicataldo** [comment]
Nope, it just needs reviews.

**Comment by jsejcksn** [comment]
@kaicataldo I don't have write access, but I approved it. 😏😎

**Comment by Lewiscowles1986** [comment]
The PR has merged, but no release has been put out AFAIK. Please can someone action this so GitHub can STFU reporting security vulnerabilities in devDependencies

**Comment by kaicataldo** [comment]
> The PR has merged, but no release has been put out AFAIK. Please can someone action this so GitHub can STFU reporting security vulnerabilities in devDependencies

In the meantime, you can always upgrade your lockfile. The new Acorn release should be supported in the ranges we have specified in Espree's `package.json`.

**Comment by kaicataldo** [comment]
We are not planning to release this in the 6.x line. As mentioned above, this should be fixable by updating your lockfile. Huzzah for semver ranges 😄
