### ISSUE TITLE
Note if `/* exported */` applies when using `--no-inline-config`

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#13013]
**The version of ESLint you are using.**

v6.8.0

**The problem you want to solve.**

Per the listing at https://eslint.org/docs/user-guide/command-line-interface#inline-configuration-comments :

> All inline config comments are ignored

However,  [`/* exported */`](https://eslint.org/docs/rules/no-unused-vars#exported) is not listed as being among these when using `--no-inline-config`. If it is prevented, it should be documented here, and if not, I think it should be called out as an exception (and why).

I think it would make sense to add it if it is not supported.

**Your take on the correct solution to problem.**

It is unclear.

**Are you willing to submit a pull request to implement this change?**

Not at this time.

**Comment by anikethsaha** [comment]
I think it should be supported and added to the list though it's being used only in specific rules (`no-unused-vars`), i would be better to support it !

**Comment by kaicataldo** [comment]
"Inline config comments" refer to ESLint directives in this case, and this configuration comment is for configuring a specific rule. Since any rule can implement configuration comments (and they're relatively uncommon) and we don't currently have an API to "mark" comments as configuration comments, I think updating the documentation clarifying this behavior is the way to go here.

**Comment by anikethsaha** [comment]
So is `exported` only being used in `no-unused-vars` rule or some other rule as well which is related to vars?
Cause if it's being used there, supporting might help. Else documenting will fit better

Also, by documenting, it should be documented in rule's docs right ? not in CLI !

**Comment by anikethsaha** [comment]
> . Since any rule can implement configuration comments (and they're relatively uncommon) and we don't currently have an API to "mark" comments as configuration comments,

Yes, keeping track of these configs through comment is really hard and unpredictable!
those should be managed by the rule itself !

Shouldnt this `exported` comment if only used by `no-unused-vars` be implemented as option for the rule instead of a comment? I am pretty sure it wouldn't be hard to refactored this and the behavior will be same as well

**Comment by brettz9** [comment]
> [@kaicataldo] "Inline config comments" refer to ESLint directives in this case, and this configuration comment is for configuring a specific rule.

`/*global*/` is in the list at https://eslint.org/docs/user-guide/command-line-interface#no-inline-config too, and I wouldn't think that many rules would be using it besides https://eslint.org/docs/rules/no-undef

Also, more importantly, the rationale given for what this command allows one to do:

> This allows you to set an ESLint config without files modifying it.

...is a very sound one, and by this logic, `exported` should be prohibited too.

Admittedly this is not so serious of an issue because `no-unused-vars` is just preventing projects from accidentally setting variables which may have been intended for use but which were not used (whether due to a misspelled variable name or incomplete code). The rule has not been about prohibiting `var`'s from setting globals in non-modular browser environments (I think we need another rule for that). But allowing comments to override is still taking away authority from the config to decide which variables are considered "used".

> [@anikethsaha] Shouldnt this exported comment if only used by no-unused-vars be implemented as option for the rule instead of a comment?

If you mean to suggest replacing the use of `exported` with an option, I think this has been too long of a convention to be turned into an option only, and in any case, as long as it is supported, the soundest option is not to allow files to dictate how the linting is performed unless a project trusts them.) (Though this would be a separate issue, my feeling is that `root: true` should be overrideable for similar reasons so that control rests fully on the API consumer, though in that case, a project can at least override by `--no-eslintrc`.) 

However, if you mean adding an option to `no-unused-vars` to disable checking of `exported`, then this would at least allow `--no-inline-config` to prevent sites from overriding one's disabling of the exported check, so I would personally be satisfied with that.

**Comment by brettz9** [comment]
> [@anikethsaha] Also, by documenting, it should be documented in rule's docs right ? not in CLI !

If you don't end up allowing `no-inline-config` to handle it, I think it still merits mention in the CLI docs, as consumers such as myself may wonder if it handles such special, eslint-interpreted directives.

**Comment by anikethsaha** [comment]
> However, if you mean adding an option to no-unused-vars to disable checking of exported, then this would at least allow --no-inline-config to prevent sites from overriding one's disabling of the exported check, so I would personally be satisfied with that.

yes

**Comment by anikethsaha** [comment]
@kaicataldo it seems `exported` is implemented like other config commands. (I may be wrong about it )

eg , like [`here`](https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L350)

So , will it make sense to support it for `--no-inline-config` command like other commands ?

**Comment by mdjermanovic** [comment]
> > This allows you to set an ESLint config without files modifying it.
> 
> ...is a very sound one, and by this logic, `exported` should be prohibited too.

There is no alternative for `/* exported */` comments in the config, so files aren't modifying config in this case.

> The rule has not been about prohibiting top-level var (or const/let) declaration's from setting globals in non-modular browser environments (I think we very much need another rule for that--and that definitely should allow any exported to be ignored or otherwise it wouldn't be useful for security auditing).

[no-implicit-globals](https://eslint.org/docs/rules/no-implicit-globals) disallows this.

> However, if you mean adding an option to no-unused-vars to disable checking of exported, then this would at least allow --no-inline-config to prevent sites from overriding one's disabling of the exported check, so I would personally be satisfied with that.

I don't think there is a use case for an option to enforce use of a global variable in the same file where it is declared. Since it's global, it will be used elsewhere.

 `no-unused-vars` just requires additional confirmation (an  `/* exported */` comment) that the variable is supposed to be used from another place, in order to prevent errors.

Disabling this would mean disabling declarations that create variables in the global scope (and only those unused, which are less likely mistakenly global than the used ones), but that should be the responsibility of `no-implicit-globals`.

> So , will it make sense to support it for --no-inline-config command like other comments?

What should the user do in that case, i.e. how can they change the code?

**Comment by brettz9** [comment]
> > > This allows you to set an ESLint config without files modifying it.
> > 
> > 
> > ...is a very sound one, and by this logic, `exported` should be prohibited too.
> 
> There is no alternative for `/* exported */` comments in the config, so files aren't modifying config in this case.

While there is no complete alternative in the config, they are kind of modifying or at least adding to the `varsIgnorePattern` config. While the effect of `exported` is limited to certain environments only, if @anikethsaha 's idea for an option to add exports were applied here (giving control back to the config), then it would be overriding.

> > The rule has not been about prohibiting top-level var (or const/let) declaration's from setting globals in non-modular browser environments (I think we very much need another rule for that--and that definitely should allow any exported to be ignored or otherwise it wouldn't be useful for security auditing).
> 
> [no-implicit-globals](https://eslint.org/docs/rules/no-implicit-globals) disallows this.

Ah, yes, I thought there had been such a rule, thank you for that. (That rule doesn't seem to have a whitelist exceptions option though, so it would seem too aggressive for my security-based interest in allowing a project to audit its dependencies--permitting the dependencies to set known (implicit) globals while forbidding any others.)

> > However, if you mean adding an option to no-unused-vars to disable checking of exported, then this would at least allow --no-inline-config to prevent sites from overriding one's disabling of the exported check, so I would personally be satisfied with that.
> 
> I don't think there is a use case for an option to enforce use of a global variable in the same file where it is declared. Since it's global, it will be used elsewhere.
> ...
> Disabling this would mean disabling declarations that create variables in the global scope (and only those unused, which are less likely mistakenly global than the used ones), but that should be the responsibility of `no-implicit-globals`.

It's not as big of a big use case in the context of "no unused vars" as it is with globals (though with `no-implicit-globals` lacking a whitelist, people may rely on `no-used-vars` to prevent globals). But even regarding unused variables, it still subverts the config's intent. Consider this:

```js
/* exported unusedVar1, unusedVar2, unusedVar3 */
var unusedVar1 = 42;
var unusedVar2 = 43;
var unusedVar3 = 44;
var intendedVar = 52;
```

In the above, a novice developer might have suppressed the errors because they learned they could suppress the warnings by adding them to `exported`. The intent of the rule is to catch this bad practice of having dangling useless variable declarations (and possible mistakes or, in my experience, more frequently, incomplete code). With inline `exported`, the intent can be subverted. So, imo, even in the context of unused variables (rather than just for inadvertent globals), the config, combined with actual usage, should be the authority on what is actually "used", even if, the global is typically the more serious situation. 
 
> > So , will it make sense to support it for --no-inline-config command like other comments?
> 
> What should the user do in that case, i.e. how can they change the code?

The proposed config would be:

```js
/*eslint no-unused-vars: ["error", {"exported": ["intendedVar"]}]*/
```

Then with `--no-inline-config`, linting would expose `unusedVar1`, `unusedVar2`, etc.

Granted, it is not usually at the global level where one cares to control this. But it does allow auditing in a consistent way. And projects that wish to use this approach can be assured that unused variables are indeed not being added except where truly needed for the exports they expect to have.

**Comment by mdjermanovic** [comment]
In favor of `exported` being a directive, it also affects `prefer-const`:

```js
/* eslint prefer-const: ["error"] */

let x = 1; // error

/* exported y */
let y = 1; // ok
```

Also, it's handled by the core. Technically, it sets [variable.eslintUsed = true](https://github.com/eslint/eslint/blob/f1525dc45dfdbbe31e724671270785b41cffc6bd/lib/linter/linter.js#L168).

**Comment by brettz9** [comment]
In such a case, that would seem to argue for a config *setting* to determine the behavior (instead of an option), so both `no-unused-vars` and `prefer-const` could use it, but it could be overridden at the config level.
