### ISSUE TITLE
Support whitelist with `no-implicit-globals`

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#13033]
**What rule do you want to change?**

`no-implicit-globals`

**Does this change cause the rule to produce more or fewer warnings?**

Fewer warnings when new config is set.

**How will the change be implemented? (New option, new default behavior, etc.)?**

A new option.

**Please provide some example code that this change will affect:**

All of the examples which currently report, e.g.,
```js
var foo = 1;
function bar() {}
```
or for non-strict mode:
```js
foo = 1;
```

Also for the following when `lexicalBindings` is `true`.

```js
const foo = 1;
let baz;
class Bar {}
```

**What does the rule currently do for this code?**

Reports them.

**What will the rule do after it's changed?**

Not report them. E.g., when the rules is defined as `/* eslint no-implicit-globals: ['error', {allowed: ['foo', 'baz', 'Bar', 'bar']}] */`

**Are you willing to submit a pull request to implement this change?**

Possibly, yes.

The whitelist is intended to be particularly useful when auditing third-party code, ensuring that it doesn't set any other globals than are expected (while still allowing it to set some expected globals). However, this could be useful for any project which wishes to avoid accidentally setting globals (while still allowing it to set some and not being forced into the style of setting on `window`--which one might wish to forbid separately with `no-restricted-syntax` anyways).

**Comment by mdjermanovic** [comment]
An option for declarations makes sense to me :+1: 

On the other hand, I'm not sure if this should be allowed:

```js
foo = 1;
```

Also, it's a bit unusual to configure something that will apply only to 1 file (the one that declares the allowed name). From that point of view, a comment like `exported` in that particular file might make more sense than the project-level configuration, but I understand that it wouldn't work for the use case you presented.

**Comment by brettz9** [comment]
> On the other hand, I'm not sure if this should be allowed:
> 
> ```js
> foo = 1;
> ```

My use case for allowing it is this:  If a project I am reviewing were to use this approach--bad as I find it to be--I don't want to have to get them to change their styling practices just so I can go about my auditing without undue noise. From all too much experience (!), I know that devs are slow to want to change the way they have things unless there is a demonstrable bug. So if such global assignments are the approach used, I can at least catch the globals they didn't mean to export in this way. I'm hoping to make this into pretty generic tool too, so others can have what they need to catch intrusive dependencies--without the distraction of stylistic or even best practice concerns when that is not the immediate priority.

> Also, it's a bit unusual to configure something that will apply only to 1 file (the one that declares the allowed name). From that point of view, a comment like `exported` in that particular file might make more sense than the project-level configuration, but I understand that it wouldn't work for the use case you presented.

Yeah, understood. OTOH, I'm personally a big fan of `overrides`, even using them frequently for single files. Beyond the security auditing use case, it's a kind of separation-of-concerns issue for me.

**Comment by kaicataldo** [comment]
While this is a valid use-case of the tool, I don't think it's worth complicating core rules for uncommon use cases. ESLint can already be overwhelmingly complex to configure, and we need to be judicious about adding complexity. The current rule only has one option (`lexicalBindings`), which exists because we didn't want to add breaking changes when adding support for lexically scoped declarations. Ideally, this option would eventually go away.

I personally think this is a better case for a custom rule. This should be fairly straightforward to accomplish using [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer).

**Comment by brettz9** [comment]
Thank you for the reference to what looks like a useful tool.

But why is (or should) this be uncommon to check others' code for practices that have the potential to conflict with one's code, if not introduce security bugs? Isn't that an even more compelling use case than linting one's own code?

**Comment by kaicataldo** [comment]
This is actually the first time I've heard of ESLint being used this way, so I don't think it's a common use case. It's definitely cool, though, and I do think it would be better to have a plugin with custom rules. I'm happy to defer to team consensus on this, though :)

**Comment by brettz9** [comment]
Ok, sure, thanks, @kaicataldo .

FWIW, there are some existing tools in the community for security: [eslint-plugin-security](https://github.com/nodesecurity/eslint-plugin-security), [eslint-plugin-xss](https://github.com/Rantanen/eslint-plugin-xss) [eslint-plugin-no-unsanitized](https://github.com/mozilla/eslint-plugin-no-unsanitized), noting that these may not necessarily be usable for untrusted code as much as preventing vulnerabilities in well-meaning code (e.g., unless DOM globals like `window` and `document` are prevented, untrusted code could, at a minimum, add false info into a page even if it could in all cases successfully be prevented from using `innerHTML` and the like (which those plugins don't do)).
