### ISSUE TITLE
`prefer-numeric-literals` overlooks template literal

### ISSUE THREAD

**Issue by yeonjuan** [eslint/eslint#13045]
**Tell us about your environment**

* **ESLint Version:** v7.0.0-alpha.2
* **Node Version:** v11.15.0
* **npm Version:** 6.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

* [online-demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgcHJlZmVyLW51bWVyaWMtbGl0ZXJhbHM6IFwiZXJyb3JcIiovXG5cbnBhcnNlSW50KGAxMTExMTAxMTFgLCAyKSA9PT0gNTAzOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOmZhbHNlLCJub2RlIjpmYWxzZX19fQ==)
```js
/*eslint prefer-numeric-literals: "error"*/

parseInt(`111110111`, 2) === 503;
```

**What did you expect to happen?**

1 error. 

**What actually happened? Please include the actual, raw output from ESLint.**

No error

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by mdjermanovic** [comment]
I agree it's reasonable to treat "static" template literals as string literals in this rule  :+1:

**Comment by kaicataldo** [comment]
I agree that this is a missing case :+1:
