### ISSUE TITLE
Parsing error: Unexpected token import

### ISSUE THREAD

**Issue by Fi1osof** [eslint/eslint#13042]
Origin: https://github.com/microsoft/vscode-eslint/issues/908

`const moduleURL = new URL(import.meta.url);`

This is valid code for .mjs https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/import.meta
But i got eslint error and can not disable this.
  

* **ESLint Version:** 6.8.0
* **Node Version:** 10.19.0
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**
Pure node-js

**Comment by mdjermanovic** [comment]
Hi @Fi1osof, thanks for the issue!

[import.meta proposal](https://github.com/tc39/proposal-import-meta) is currently in stage 3. ESLint's default parser will support this syntax if and when it reaches stage 4.

In the meantime, you can use a parser that supports experimental syntax, like [babel-eslint](https://github.com/babel/babel-eslint).

**Comment by Fi1osof** [comment]
@mdjermanovic thanks!

**Comment by brendankenny** [comment]
`import.meta` moved to stage 4 on April 1st (the [spec proposal](https://github.com/tc39/proposal-import-meta) still lists it as stage 3 but see [tc39/finished-proposals.md](https://github.com/tc39/proposals/blob/master/finished-proposals.md) and https://github.com/tc39/proposals/commit/0c27379ebb525ffebed75584827ce51687af99f8)

Is there extra process for adding support for new syntax or is this something a contributor could help with? Would love to avoid the extra parser dependencies!

cc @mdjermanovic

**Comment by brendankenny** [comment]
Oh, sorry, just found #13133 which has this covered :)

**Comment by mdjermanovic** [comment]
Closing this issue since we are tracking progress in #13133
