### ISSUE TITLE
Enabling globals only for part of a file

### ISSUE THREAD

**Issue by jsejcksn** [eslint/eslint#13057]
@platinumazure [suggested that I open this issue](https://gitter.im/eslint/eslint?at=5e701f1465758a0f97f99a8a). I'm not sure which template it fits, so I'm just beginning discussion.

In the example below `puppeteer` uses `window`, `document` etc in Node without providing them as function parameters, and I don't want ESLint to complain about that, but I also don't want them available outside the puppeteer functions which use them. I tried to fix it using directives:

```js
const results = await page.evaluate(selector => {
  /* global document:readonly */
  const titleNodes = [...document.querySelectorAll(selector)];
  const titles = titleNodes
    .filter(node => node.textContent.includes('. '))
    .map(node => node.textContent.trim());
  return titles;
  /* global document:off */
}, selector);
```

However, those directives don't work as I thought they would. Apparently, they only apply to the entire file, unlike

```js
/* eslint-disable rule */
// targeted code
/* eslint-enable rule */
```

@platinumazure suggested `no-undef` as a workaround, but I want more precision than that.

I'm wondering if this can be solved as a new option related to globals on the `no-undef` rule or something entirely different.

What are your thoughts?

**Comment by kaicataldo** [comment]
I think it makes sense that globals apply at the file/module level since, well, they're globals :)

My suggestion would be to use [no-restricted-globals](https://eslint.org/docs/rules/no-restricted-globals) to disallow these directives and to turn the rule off for the functions where you would like to  reference these globals. This would also allow you to explain in the error message why it's disallowed

**Comment by jsejcksn** [comment]
@kaicataldo What I’m looking for is the inverse effect: I want to _allow_ specific globals for a block of code.

The approach you suggested sounds like it might work, but wouldn’t it require me to discover and explicitly state every other global in the environment(s) containing the globals I want to allow? If I understand it correctly, that doesn’t sound like a maintainable strategy, especially if the environments are updated with new globals over time.

**Comment by kaicataldo** [comment]
It should be possible to use the [globals](https://www.npmjs.com/package/globals) package to configure which global you want to disallow, but I understand that’s not a very intuitive way to do this.

Do you mind explaining why you need this behavior (i.e. Is this for server-side rendering?)? I’d love to have a better understanding of the problem you’re trying to solve.

**Comment by jsejcksn** [comment]
@kaicataldo See the example in my original post. Here’s a link to the related documentation in puppeteer:

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

That method runs the provided callback in an environment with access to some browser globals. However, accessing those globals in other parts of my code would produce an error. That’s why I need access to those globals only within the context of the body of the callback functions.

**Comment by mdjermanovic** [comment]
> That method runs the provided callback in an environment with access to some browser globals. However, accessing those globals in other parts of my code would produce an error. That’s why I need access to those globals only within the context of the body of the callback functions.

It seems that puppeteer converts the callback function to a `string` [here](https://github.com/puppeteer/puppeteer/blob/013a86cf2865d585b94628e0fbc142ade4039a7f/lib/ExecutionContext.js#L88) and then evaluates it. It's observable since you can't access outer variables from the callback.

So, it might be best to define the callback in another file and enable the `browser` environment for that file.

An alternative is to use `this.document` or `globalThis.document` instead of `document`.

**Comment by kaicataldo** [comment]
While I understand the challenges here, @mdjermanovic's suggestions seem like the right course of action to me. I personally don't think we should go down the path of globals not being treated as true globals, due to the amount of complexity and confusing behavior this could introduce.

**Comment by jsejcksn** [comment]
I realize this is a minority scenario, but there are some other libraries out there which work similarly (stringifying code to run in a different environment).

Perhaps at some point in the future, “globals” can be reconsidered (as a product of the current execution environment) and treated similarly to any other configurable setting, like rules.

Thanks @mdjermanovic for your suggestion and for linking me to that line in the puppeteer source.

**Comment by mdjermanovic** [comment]
> Perhaps at some point in the future, “globals” can be reconsidered (as a product of the current execution environment) and treated similarly to any other configurable setting, like rules.

I think this isn't only about globals, stringifying code also breaks lexical scoping. In particular, the callback function shouldn't be treated as a nested scope, e.g.:

```js
const DOT = '. ';

const results = await page.evaluate(selector => {
  const titleNodes = [...document.querySelectorAll(selector)];
  const titles = titleNodes
    .filter(node => node.textContent.includes(DOT)) // this should be no-undef error?
    .map(node => node.textContent.trim());
  return titles;
}, selector);
```

This looks to me more like a case for some new eslint directives, which would treat code between them as basically a separate file (where you can set globals, environments, etc.).

**Comment by jsejcksn** [comment]
@mdjermanovic That's exactly what I'm thinking.

And your example illustrates that well: `DOT` would need to be included as an arg along with `selector`:

```js
const DOT = '. ';

const results = await page.evaluate(selector => {
  ...
}, selector, DOT);
```

**Comment by jsejcksn** [comment]
@eslint I know you don’t really mean that.
