### ISSUE TITLE
Detect if .eslintrc file exists with API / use `baseConfig` only if an .eslintrc file does not exist

### ISSUE THREAD

**Issue by agilgur5** [eslint/eslint#13071]
**The version of ESLint you are using.**

[^6.1.0](https://github.com/jaredpalmer/tsdx/blob/e84e8d654c8462b8db65a3d395e2a4ba79bf1bd2/package.json#L68)

**The problem you want to solve.**

I'd like to be able to detect if a `.eslintrc`, `.eslintrc.js`, `package.json.eslintrc`, etc exists using the ESLint API.

[TSDX](https://github.com/jaredpalmer/tsdx), which wraps `eslint` with a `tsdx lint` command that uses `CLIEngine`, has a [few issues](https://github.com/jaredpalmer/tsdx/issues/514) around users configuring an `eslintrc` file only to be confused that there are additional rules/presets on top of their config added due to our `baseConfig`.
I'd like to be able to switch to a preset/config they can extend instead, but for zero-config users that use `tsdx lint` without an `eslintrc`, they should continue having the same experience with a `baseConfig`.

As far as I can tell, there is no way to do this with `CLIEngine` as `baseConfig` gets merged with their `eslintrc`.

What we could do is add a `baseConfig` if and only if there is no `eslintrc` file detected, but given the number of different file extensions, `package.json.eslint`, and the possibility of those changing over time, that's not so easy. I assume ESLint already has this kind of logic somewhere, it's just not exposed directly to the API.

**Your take on the correct solution to problem.**

I think the ESLint API exposing a function for this purpose would be the easiest solution to this.

Alternatively could modify the behavior of `CLIEngine` with something like `overrideConfig`, but that seems like a worse option?

When I [looked through the API](https://github.com/jaredpalmer/tsdx/issues/514#issuecomment-594186639), I did think of a potentially very hacky solution available now that uses [`CLIEngine#getConfigForFile`](https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile) to detect if an `eslintrc` exists, but that seems like a very suboptimal way of doing something much more direct.

**Are you willing to submit a pull request to implement this change?**

Yes, if you can point me in the right direction. Have done a few upstream changes

**Comment by kaicataldo** [comment]
Since this is a change to core, could you create an RFC following the process outlined [here](https://github.com/eslint/rfcs)? This does seem like a useful thing to expose in the public API, either through some existing method or some kind of addition. One thing to note: we will be [deprecating `CLIEngine` in favor of a new `ESLint` class](https://github.com/eslint/rfcs/pull/40) in the near future, so whatever solution we come up with should have some corollary in the new class.

**Comment by nzakas** [comment]
Another thing to keep in mind is that this config system is being deprecated in favor of a new one, so any change would need to apply equally well to both systems.
