### ISSUE TITLE
[Question] Turn off all rules, specifically from plugins

### ISSUE THREAD

**Issue by himynameisdave** [eslint/eslint#13077]
Probably a bit of a weird use case here, but I am looking to create a separate ESLint configuration for doing pre-commit checks, since in our pre-commit hook we only want to lint a (much) smaller sub-set of core ESLint rules.

I figured out how to get a separate config running for the pre-commit command (which involved moving the ESLint configs into their own directory so as [to avoid any weird cascading/hierarchy](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) issues). Then I just targeted them with the `-c` flag:

**`package.json`**
```json
  "scripts": {
    "lint": "eslint --ext .ts,.js,.jsx,.tsx -c ./lint/.eslintrc.frontend.js .",
    "lint:pre-commit": "eslint --ext .ts,.js,.jsx,.tsx -c ./lint/.eslintrc.precommit.js ."
  }
```

For the paired-down pre-commit config, I borrowed a bit [from the `eslint:all` config](https://github.com/eslint/eslint/blob/master/conf/eslint-all.js#L20-L24), which grabs all the rules and creates an object like `{ [ruleId]: 'off' }` (with a key/value pair for each rule).

It looks a little something like this:

**`.eslintrc.pre-commit.js`**

```js
const allRules = require('../node_modules/eslint/lib/rules');

// These are the only rules we want to flag on pre-commit:
const ERROR_RULES = ['no-undef'];

const rules = Object.entries(allRules).reduce((accRules, [ruleId, rule]) => {
  return {
    ...accRules,
    // Only set specified rules to 'error', all others are 'off'
    [ruleId]: ERROR_RULES.includes(ruleId)
      ? 'error'
      : 'off',
  };
}, {});

module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    tsconfigRootDir: __dirname + '../',
    project: './tsconfig.json',
    ecmaFeatures: {
      'jsx': true,
    },
    sourceType: 'module',
  },
  rules,
};
```

No plugins, it just turns off all the core ESLint rules. Uses the TS parser but not the TS plugin. 👍 

☝️ This got me 90% of the way to where I needed to be, but I've hit a roadblock because throughout our codebase we use disable directive comments to disable rules from specific plugins. Here's an example:

```tsx
// eslint-disable-next-line react/no-array-index-key
<option key={i} value={option}>
```

The problem is that ESLint then goes looking for a definition for `react/no-array-index-key`, but can't find one because I'm not specifying `react` in `plugins`, hence this (and many other) errors:

```
error   Definition for rule 'react/no-array-index-key' was not found
```

**Question:** without manually listing each rule from each plugin we use and setting each one to `'off'`, is there a simple way to either:
1. Ignore disable directive comments when running ESLint?
2. Extend an existing config, but set all the rules values (including those from plugins) to `'off'`, and then go from there?

It would be great if all the plugins (and ESLint itself) exposed a `plugin:off` config that I could base off, but that is unreliable as plugins vary too much in the way they are structured and most configs don't have an `off` setting.

My next steps are going to basically create some hacky script to run ESLint's [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#print-config), import all the rules from that JSON, loop through and turn them off.

Thanks in advance for the help!

**Comment by kaicataldo** [comment]
Does the [`--no-inline-config`](https://eslint.org/docs/user-guide/command-line-interface#no-inline-config) CLI flag solve your issue?

**Comment by himynameisdave** [comment]
@kaicataldo, you're my hero, this would totally solve my issue -- thank you!

![giphub](https://media2.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

**Comment by kaicataldo** [comment]
Yay! Glad we were able to find something that works :)
