### ISSUE TITLE
esquery@1.2.0 Node.js version incompatible with `engines` field in ESLint v5.16.0

### ISSUE THREAD

**Issue by d4nyll** [eslint/eslint#13081]
**Tell us about your environment**

* **ESLint Version:** v5.16.0
* **Node Version:** v6.17.1
* **npm Version:** 3.10.10
* **yarn Version:** v1.22.4

**What did you do?**

Run `yarn add eslint@5.16.0 --dev` on Node.js v6.17.1.

**What did you expect to happen?**

`yarn add` to succeed.

**What actually happened? Please include the actual, raw output from ESLint.**

`yarn add` fails due to dependency on esquery@1.2.0 (esquery@1.1.0 supports Node.js v0.6+)

```
$ nvm use 6.17.1
Now using node v6.17.1 (npm v3.10.10)
$ yarn init -y
yarn init v1.22.4
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.03s.
$ yarn add eslint@5.16.0 --dev
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning eslint > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning eslint > file-entry-cache > flat-cache > write > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] Fetching packages...
error esquery@1.2.0: The engine "node" is incompatible with this module. Expected version ">=8.0". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

`eslint@5.16.0` specifies [support](https://github.com/eslint/eslint/blob/v5.16.0/package.json#L126) for ` "node": "^6.14.0 || ^8.10.0 || >=9.10.0"`

```
  "engines": {
    "node": "^6.14.0 || ^8.10.0 || >=9.10.0"
  }
```

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by cesarguillotel** [comment]
It's the same thing for previous versions like ESLint 4.19.1, esquery version needs to be set to 1.1.0.

**Comment by kaicataldo** [comment]
I do think it’s unfortunate that `esquery` published a semver-minor release with a breaking change. It looks like [this was intentional](https://github.com/estools/esquery/issues/95), with the argument being that the dropped Node versions have been end-of-lifed.

We don’t currently have a policy for releasing old versions of ESLint and, given the workaround listed in the issue above (using a lock file), I’m not sure we should start now. Let’s see what the rest of the team has to say.

**Comment by kaicataldo** [comment]
As mentioned [here](https://github.com/eslint/eslint/pull/13082#issuecomment-604062770), we don't have a policy of releasing patches to old versions of ESLint. Thank you for your interest in improving ESLint.
