### ISSUE TITLE
use astUtils.getStaticPropertyName in no-prototype-builtins

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#13088]
**What rule do you want to change?**

`no-prototype-builtins`

**Does this change cause the rule to produce more or fewer warnings?**

more

**How will the change be implemented? (New option, new default behavior, etc.)?**

new default behavior

**Please provide some example code that this change will affect:**

```js
/*eslint no-prototype-builtins: "error"*/

var hasBarProperty = foo["hasOwnProperty"]("bar");

var isPrototypeOfBar = foo['isPrototypeOf'](bar);

var barIsEnumerable = foo[`propertyIsEnumerable`]("bar");
```

**What does the rule currently do for this code?**

no errors

**What will the rule do after it's changed?**

3 errors

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by kaicataldo** [comment]
I would argue that this is a bug in the current rule.

**Comment by mdjermanovic** [comment]
I'd also agree with treating this issue as a bug.

**Comment by nanbeinanbei** [comment]
when can we get it changed？

**Comment by btmills** [comment]
This is now accepted, and I agree we can treat it as a semver-minor bug fix.

**Comment by mdjermanovic** [comment]
I'm working on this.
