### ISSUE TITLE
Error while installing ESlint (Legacy versions of mkdirp)

### ISSUE THREAD

**Issue by skystar7** [eslint/eslint#13085]
I am getting this error during installation:

npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! Unexpected end of JSON input while parsing near '...","eslint":"^3.10.2",'

npm ERR! A complete log of this run can be found in:
npm ERR!     XXX\npm-cache\_logs\2020-03-24T18_07_58_883Z-debug.log

**Tell us about your environment**

 node --version
v13.11.0

npm --version
6.13.7

Many thanks for your kind help

**Comment by ljharb** [comment]
The first one isn't an error, it's a warning. Warnings should generally be ignored.

The error is that some package.json (yours, or a dep's) has a trailing comma, making it invalid JSON.

**Comment by skystar7** [comment]
This is a clean project, I literally run  npm install -save-dev eslint after npm init

**Comment by ljharb** [comment]
eslint 3.10.2 is very old; i'm not sure what would be referencing that version. Unfortunately the error is coming from "json-parse-better-errors", so it's not telling us what file has the JSON error. What version of eslint are you trying to install? Do you have a private registry, or is this the public one?

**Comment by skystar7** [comment]
npm cache clean --force
Fixed the issue, thank you ljharb for your kind help

**Comment by dipudey** [comment]
how can you solve this error....?
I can't solve this problem.
how can i solve this.

**Comment by skystar7** [comment]
> skystar7,
> how can you solve this error....?
> I can't solve this problem.
> how can i solve this.

by just running npm cache clean --force

**Comment by Yogeshkumar9291** [comment]
Hey

I still got error

**Comment by skystar7** [comment]
> Hey
> 
> I still got error

try running the command as an administrator in the same dir as your project
