### ISSUE TITLE
ignorePatterns is not working for paths with hyphens

### ISSUE THREAD

**Issue by miyasudokoro** [eslint/eslint#13095]
**Tell us about your environment**

Environment Info:

Node version: v12.14.0
npm version: v6.13.4
Local ESLint version: vundefined (Currently used)  <-- this is what it output but it should be 6.8.0
Global ESLint version: Not found

* **ESLint Version:** 6.8.0
* **Node Version:** 12.14.0
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**
no parsers

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "ignorePatterns": [
    "ci-output/",
    "dist/",
    "node_modules/"
  ],
  "extends": [
    "jquery"
  ],
  "plugins": [
    "standard",
    "mocha"
  ],
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
    "amd": true,
    "es2020": true
  },
  "globals": {
    "sinon": "readonly",
    "expect": "readonly",
    "fixtures": "readonly",
    "fail": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },
  "rules": {
    "indent": [
      "error",
      4,
      {
        "SwitchCase": 1
      }
    ],
    "quotes": [
      "error",
      "single",
      {
        "avoidEscape": true,
        "allowTemplateLiterals": true
      }
    ],
    "no-trailing-spaces": [
      "error",
      {
        "ignoreComments": true,
        "skipBlankLines": true
      }
    ],
    "require-jsdoc": [
      "error",
      {
        "require": {
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "ClassDeclaration": true,
          "ArrowFunctionExpression": false,
          "FunctionExpression": false
        }
      }
    ],
    "no-unused-expressions": [
      "error",
      {
        "allowShortCircuit": true
      }
    ],
    "linebreak-style": "off",
    "lines-around-comment": "off",
    "max-len": [ "error", 200 ]
  },
  "overrides": [
    {
      "files": [ "*.spec.js", "*.mocha.js" ],
      "rules": {
        "require-jsdoc": "off",
        "max-len": "off"
      }
    }
  ]
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
eslint -c path/to/eslintrc.js ./**/*.js -f html -o ./ci-output/eslint/index.html
```

**What did you expect to happen?**
It does not lint files in the directory `ci-output`.

**What actually happened? Please include the actual, raw output from ESLint.**
It lints files in the directory `ci-output` even though it is clearly listed in ignorePatterns.

**Are you willing to submit a pull request to fix this bug?**
Sorry, my company policy does not allow it.

**Comment by miyasudokoro** [comment]
I've done a little more experimentation. 

1. It seems to generally not work for directories that have a hyphen in the name.
2. The exact same line `ci-output/` inside an .eslintignore file works to ignore the directory.

**Comment by kaicataldo** [comment]
> Local ESLint version: vundefined (Currently used) <-- this is what it output but it should be 6.8.0

Huh, that seems like a bug. Would you be able to make an issue for that, by any chance?

For the problem at hand, I think this is some interaction between the `-c` CLI argument interacting with the `ignorePattersn` configuration option rather than having to do with hyphens. In my local testing, I'm unable to ignore anything at all using `ignorePatterns` with relative paths and using the `-c` CLI option.

This doesn't work even when I use `path.resolve()` to add the absolute path to the `ignorePatterns` array.

Please note that this behavior should work as expected in the next prerelease, since we have merged https://github.com/eslint/eslint/commit/48b122f450b14dd27afef4c8115c69fca4f02be1.
