### ISSUE TITLE
Parsing error: Unexpected token =

### ISSUE THREAD

**Issue by michaelrehman** [eslint/eslint#13097]
**Tell us about your environment**

* **ESLint Version:** v6.8.0 (global)
* **Node Version:** v13.1.0
* **npm Version:** v6.12.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/**
 * Class used to map characters to arrays.
 */
export class CharacterMapper {

    /** Value representing that a pixel of the character is present. */
    static pixelPresent = 1;
    /** Value representing that a pixel of the character is not present. */
    static pixelNotPresent = 0;
    // ...
} // CharacterMapper
```
The full source code can be seen at [this repository](https://github.com/michaelrehman/canvas_collection) under [`typer/models/CharacterMapper.js`](https://github.com/michaelrehman/canvas_collection/blob/master/typer/models/CharacterMapper.js).

```bash
eslint typer/models/CharacterMapper.js
```

**What did you expect to happen?**
For nothing to be outputted.

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
C:\Absoulte\Path\To\Repo\Canvas_Collection\typer\models\CharacterMapper.js
  7:25  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)
```
The odd thing is that it only ever detects the first `=`.

**Are you willing to submit a pull request to fix this bug?**
No, not really.

**Comment by anikethsaha** [comment]
looks like `acron` cant parse it!

**Comment by kaicataldo** [comment]
Class fields are currently experimental and aren't supported by ESLint core. We'll be adding support once the syntax is finalized. In the meantime, you can use [`babel-eslint`](https://github.com/babel/babel-eslint).
