### ISSUE TITLE
id-length exceptions pattern

### ISSUE THREAD

**Issue by burawi** [eslint/eslint#13094]
**What rule do you want to change?**
Property `exceptions` for rule `id-length`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
Property value support

**Please provide some example code that this change will affect:**

```js
{
  id-length: {
    min: 3,
    max: 16,
    exceptions: ["^BEFORE_"]
  }
}
```

**What does the rule currently do for this code?**
It makes the exception only for identifiers named exactly `^BEFORE_`

**What will the rule do after it's changed?**
It will make the exception for all identifiers matching the pattern. In the example above, it will make the exception for every identifier starting with `BEFORE`

**Are you willing to submit a pull request to implement this change?**
Not for the moment

**Comment by anikethsaha** [comment]
this doesn't need much refactoring. 
I think it can be done but I think it will be safe to implement as a separate option like `exceptionPattern`

**Comment by kaicataldo** [comment]
This seems like a reasonable enhancement to me :+1:

**Comment by yeonjuan** [comment]
I agree with it 👍  and marked as accepted.

**Comment by anikethsaha** [comment]
I would like to work on this if its ok by others!

**Comment by kaicataldo** [comment]
@yeonjuan We still need a champion for this proposal. Would you like to champion it?

**Comment by yeonjuan** [comment]
@kaicataldo sorry for mislabeling,  I'm willing to champion this : )

**Comment by kaicataldo** [comment]
@eslint/eslint-team Looks like we just need one more :+1: from a team member.

**Comment by sodaMelon** [comment]
hi, It seems to have stopped last month. 
Can i continue this?

**Comment by aladdin-add** [comment]
@sodaMelon  sure, please feel free to pick up!
