### ISSUE TITLE
reportUnusedDisableDirectives should probably be a regular rule

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#13104]
`reportUnusedDisableDirectives` is currently a config option but I think it would make more sense if it would just be a regular rule which would allow:

- Allow it to be disabled by line (`/* eslint-disable-line rule report-unused-disable-directives */`)
- Setting it to `error` level (https://github.com/eslint/eslint/issues/12703)
- Autofix can be implemented as usual (https://github.com/eslint/eslint/issues/11815)

Example where it is useful to disable per-line is a imported externally generated file that may or may not be present. `import/no-unresolved` will warn on it when absent but if I add a per-line disable `reportUnusedDisableDirectives` will trigger in situations where the file is present. My only option to resolve this is to disable `reportUnusedDisableDirectives` completely.

(Sorry, for omitting the issue template but none seems to really fit)

**Comment by mdjermanovic** [comment]
@silverwind thanks for the issue!

This feature needs output (reported problems) from all rules. Any ideas on how could we make `reportUnusedDisableDirectives` rule with the current architecture?

If it helps with your use case, `reportUnusedDisableDirectives` is allowed in [overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) sections, so it can be set to `false` for a specific file.

**Comment by silverwind** [comment]
Thanks for the tip, having `reportUnusedDisableDirectives` overrideable per-file certainly helps here.

Regarding implementation, I read that it was tried to be implemented as a rule initially but the architecture did not allow it (https://github.com/eslint/eslint/issues/9382#issuecomment-340196266), so it might be impossible currently.
