### ISSUE TITLE
no-unused-vars feature request arrayIgnorePattern

### ISSUE THREAD

**Issue by cyberixae** [eslint/eslint#13100]
It would be nice if the rule would allow you to name things when unpacking an array.

```javascript
/* eslint no-unused-vars: ["error", { "arrayIgnorePattern": "^_" }] */

const [_a, b, _c] = 'a:b:c'.split(':');
console.log(b);
```

**Comment by anikethsaha** [comment]
I guess the above can be covered using `varsIgnorePattern`

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJ2YXJzSWdub3JlUGF0dGVyblwiOiBcIl5fXCIgfV0qL1xuXG5jb25zdCBbX2EsIGIsIF9jXSA9ICdhOmI6Yycuc3BsaXQoJzonKTtcbmNvbnNvbGUubG9nKGIpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdW51c2VkLXZhcnMiOjJ9LCJlbnYiOnsibm9kZSI6dHJ1ZSwiYnJvd3NlciI6dHJ1ZSwiZXMyMDIwIjp0cnVlfX19)

**Comment by cyberixae** [comment]
Oh, dear! Didn't realize that would work. Somehow confused argsIgnore with varsIgnore.
