### ISSUE TITLE
Feature request: apply suggestions fix via API or CLI

### ISSUE THREAD

**Issue by fisker** [eslint/eslint#13103]
**The version of ESLint you are using.**

`v6.8.0`

**The problem you want to solve.**

We use CLI argument `--fix-dry-run` to run tests on files, make sure `fix` don't crash on fixing files. But seems there is no way to apply suggestions fix via API or CLI (except ruleTester).

**Your take on the correct solution to problem.**

No idea. Maybe apply suggestions fix via API or CLI, or other way to do this test.

**Are you willing to submit a pull request to implement this change?**

Probably not.

**Comment by kaicataldo** [comment]
From the [corresponding RFC](https://github.com/eslint/rfcs/tree/master/designs/2019-suggestions):

> It's very similar to fixes mechanism that already exists in ESLint, but will provide ability to create multiple suggestions per rule, suggestions will not be automatically applied by using --fix flag, and will require user interaction. This feature will only be exposed through the ESLint API, and will not be available on the CLI.

The decision to not apply fixes automatically with suggestions is intentional. If you have a rule that you want to be autofixed, we suggest using the current rule fixing logic instead.
