### ISSUE TITLE
Scheduled release for April 10th, 2020

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#13113]
The scheduled release on Friday, April 10th, 2020 is assigned to:

* (needs volunteers)

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

Resources:

* [Release guidelines](https://eslint.org/docs/maintainer-guide/releases)

**Comment by kaicataldo** [comment]
I ended up having to create this issue manually because `eslint-github-bot` didn't start after the last `eslint-github-bot` release. This is fixed now.

**Comment by btmills** [comment]
This release will not happen as scheduled. We're working on finishing https://github.com/eslint/eslint/pull/12939 before doing the last v7 alpha release.
