### ISSUE TITLE
How to lint a file base on another file?

### ISSUE THREAD

**Issue by fluentwind** [eslint/eslint#13114]
Once i have a.js and b.js.

I want to lint a.js with objectB defined in b.js. I can rean b.js in 'create' callback.
But when objectB is changed, how can i do to trigger a new lint for a.js?
By the way, how to cache the lint result for such situation?

**Comment by kaicataldo** [comment]
This use case is not one we currently support, since ESLint is designed to run on one file at a time. 

You might be able to achieve this by using the Node API and creating a wrapper that builds up the dependency tree, triggering linting a module’s consumers when it has changed. You could also create your own caching logic in this wrapper.

**Comment by fluentwind** [comment]
@kaicataldo I think so. 
I have thought about this and have three situations(solutions) here:
### First: Lint after coding and munually trigger.
For munually running a script to lint, i can create a wrapper in a node script. It's the easiest way to achieve. But it could not be able to originally triggered by eslint, i need to trigger by myself, like run a script 'node my-wrapper.js' every time.
It's not the best method.

### Second: Lint after coding but automatically trigger.
So i think, in another side, if i want to work with webpack, that means i need to do another webpack-plugin to work with this. Since webpack has hot-reload and file watcher, it seems to be able to lint and report automaticaly.
But this method also has the same problem: I cannot lint when i am coding.

### Third: Lint when coding and automatically trigger.
For further use, if i want to work with a IDE like Webstorm. The eslint plugin in webstorm can do real-time lint when i'm coding. But it depends on eslint and one eslintrc file. If i can use original eslint function, it will be the best exprience in coding. Unfortunately eslint could not do that.

### Is there any solutions for the third situation. If not i will try webpack-plugin.

**Comment by kaicataldo** [comment]
There is no built in way to achieve this, unfortunately. If you want to automate it, creating your own watcher/using Webpack seems like the way to go.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
