### ISSUE TITLE
Website suggestion: add 'Migrating from tslint' like 'Migrating from JSCS'

### ISSUE THREAD

**Issue by mikemaccana** [eslint/eslint#13123]
The website has a bunch of awesome guides:

![image](https://user-images.githubusercontent.com/172594/77915170-e7e9c080-728e-11ea-8b5c-2f2c924a9605.png)

it would be useful to have something official for those arriving to eslint from tslint! Similar to https://medium.com/create-code/migrate-angular-8-from-tslint-to-eslint-4b0c44c8ae38

**Comment by kaicataldo** [comment]
Agreed that it would be nice to provide documentation for TSLint users. The ESLint team doesn't maintain the TypeScript integration, but perhaps we could partner with the @typescript-eslint team to either add documentation or add a clear link to documentation they maintain?

**Comment by anikethsaha** [comment]
perhaps this can be helpfull https://github.com/typescript-eslint/typescript-eslint#migrating-from-tslint-to-eslint

**Comment by nzakas** [comment]
We have a migrating from JSCS guide because JSCS merged with ESLint. Given that typescript-eslint is a separate project that is not maintained by this team, I don't think we should add such documentation to our website as it creates an external dependency that can get out-of-date.

**Comment by mikemaccana** [comment]
@nzakas Understood re: external dependency. Maybe the best thing that would avoid that, yet still give people using TypeScript somewhere to get help, is a link (like the JSCS one) to a page that says

> Migrating to eslint from typescript? Check out the [official docs from the `typescript-eslint` team](https://github.com/typescript-eslint/typescript-eslint#migrating-from-tslint-to-eslint). Note that `typescript-eslint`is a separate project, so please send contributions, requests etc regarding TypesScript support there.

or something similar.
