### ISSUE TITLE
[bug] undefined variable `name` does not trigger errors or warnings in JSX.

### ISSUE THREAD

**Issue by JustFly1984** [eslint/eslint#13127]
I'm not sure which rule is failing, but if I had a component which had prop name and used it in JSX, while refactoring and renaming prop to `title`, the leftovers of name prop iN JSX slept unnoticed, and caused errors in production, even with typescript.

**Comment by anikethsaha** [comment]
Can you share your config.
I think this belongs to https://github.com/yannickcr/eslint-plugin-react ?

**Comment by JustFly1984** [comment]
my `.eslintrc.js`

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "standard-react",
    "plugin:cypress/recommended",
    "plugin:jest/recommended",
    "plugin:import/typescript",
    "plugin:jsx-a11y/recommended",
    "plugin:react/recommended",
    "plugin:react-perf/all",
    "plugin:react-redux/recommended",
    "plugin:promise/recommended",
    "stylelint",
    // Prettier always last
    "prettier",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint",
    "prettier/react",
    "prettier/standard",
  ],
  plugins: [
    "chai-expect",
    "import",
    "@typescript-eslint",
    "react",
    "jsx-a11y",
    "react-hooks",
    "react-perf",
    "react-redux",
    "jest",
    "no-inferred-method-name",
    "optimize-regex",
    "promise",
    "cypress",
    "prettier",
    "standard",
    "markdown",
    "json",
    "xss",
    "perf-standard",
    "es",
    "babel",
    "formatjs",
  ],
  settings: {
    react: {
      version: "detect",
    },
    node: {
      allowModules: ["src"],
      resolvePaths: [__dirname],
      tryExtensions: [".ts", ".tsx", ".js", ".jsx", ".json"]
    },
  },
  env: {
    "cypress/globals": true,
    browser: true,
    node: true,
    es6: true,
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: "module", // Allows for the use of imports
  },
  rules: {
    "node/no-missing-import": "off",
    "node/no-missing-require": "off",
    "node/no-unsupported-features/es-syntax": "off",
    "sort-requires/sort-requires": "off",
    "no-console": ["error", { allow: ["warn", "error", "info"] }],
    "no-unused-vars": "off",
    "@typescript-eslint/explicit-function-return-type": [
      "warn",
      { allowExpressions: true },
    ],
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-use-before-define": [
      "error",
      { functions: false, classes: false, typedefs: false },
    ],
    "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    "react-redux/prefer-separate-component-file": "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "optimize-regex/optimize-regex": "warn",
    "es/no-async-iteration": "error",
    "es/no-malformed-template-literals": "error",
    "es/no-regexp-lookbehind-assertions": "error",
    "es/no-regexp-named-capture-groups": "error",
    "es/no-regexp-s-flag": "error",
    "es/no-regexp-unicode-property-escapes": "error",
    "chai-expect/missing-assertion": 2,
    "chai-expect/terminating-properties": 1,
  },
  overrides: [
    // Override some TypeScript rules just for .js files
    {
      files: ["*.js"],
      rules: {
        "semi": ["error", "never"],
        "jsx-quotes": ["error", "prefer-single"],
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/explicit-function-return-type": "off",
      },
    },
  ],
}
```

this is how it looks in vscode:
<img width="880" alt="Screenshot 2020-04-01 14 38 16" src="https://user-images.githubusercontent.com/2255993/78111343-b73c8f00-7426-11ea-82f0-c6ec8fdc7e85.png">

as you can see variable name is not defined, but somehow not highlighted. Had this slipped in to the code base 3 times this year

**Comment by anikethsaha** [comment]
I dont think there is any rule in eslint core which catches that ( not sure though )
it may belong to https://github.com/yannickcr/eslint-plugin-react  as I mentioned. 

Lets hear from other as I am not sure about it. I tried on demo page with possible rules to catch this but couldn't find this.

**Comment by kaicataldo** [comment]
@JustFly1984 Please fill out the requested issue template. It’s difficult for us to triage this issue without having all that information.

**Comment by kaicataldo** [comment]
You can find the template [here](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by JustFly1984** [comment]
1. eslint - latest.
eslint config attached on top.
@typescript-eslint/parser and all the plugins - latest

2. As I explained above - eslint missing an error

example of code with an error:

```
import * as React from 'react'

import Layout from 'src/components/layout/static'

import AuthLogin from 'src/components/auth-login'

import { StaticPage } from 'src/types/common'

export default function LoginPage({ pageContext }: StaticPage): JSX.Element {
  return (
    <Layout pageContext={pageContext}>
      {name}
      <AuthLogin />
    </Layout>
  )
}

```

variable `name` is not defined in the scope of the module, nor imported. 
Navigating to type definition leads to 'lib.dom.d.ts` file

<img width="445" alt="Screenshot 2020-04-10 04 53 17" src="https://user-images.githubusercontent.com/2255993/78944033-36952700-7ae7-11ea-8ae8-80bcb58d5abd.png">

there is for sure clash of global variable `window.name` and JSX context. Can't really think about any proper solution, except warn about using global variables. https://developer.mozilla.org/en-US/docs/Web/API/Window/name

As I recal, before in some project I had some kind of comment on top of the file which clearly lists all global variables used in the file, so no accident global variable do not snitch unnoticed, but can't remember how to enable this functionality again.

**Comment by webOS101** [comment]
Using version numbers like `latest` is not very informative, particularly for people looking at this issue in the future.  New releases of components happen daily so 'latest' at 12:00 may not be the same as 'latest' at 2:00.

**Comment by webOS101** [comment]
I think the solution to your problem is to remove 'browser' from your environment.  Then, you won't be able to access browser globals implicitly like that.

**Comment by JustFly1984** [comment]
@webOS101 can you please elaborate? I guess I had to add `dom.lib` to tsconfig.js to have type support for browser environment, and your advice is to globally disable it doesn't seems like correct solution, cos it will cause type mismatches in other jsx files.

this is the set of everything related to eslint in my package.json:
```json
{
    "@typescript-eslint/eslint-plugin": "2.27.0",
    "@typescript-eslint/parser": "2.27.0",
    "eslint": "6.8.0",
    "eslint-config-prettier": "6.10.1",
    "eslint-config-standard": "14.1.1",
    "eslint-config-standard-react": "9.2.0",
    "eslint-config-stylelint": "12.0.0",
    "eslint-config-typescript": "3.0.0",
    "eslint-import-resolver-typescript": "2.0.0",
    "eslint-plugin-babel": "5.3.0",
    "eslint-plugin-chai-expect": "2.1.0",
    "eslint-plugin-cypress": "2.10.3",
    "eslint-plugin-es": "3.0.0",
    "eslint-plugin-formatjs": "2.1.0",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-jest": "23.8.2",
    "eslint-plugin-json": "2.1.1",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-markdown": "1.0.2",
    "eslint-plugin-no-inferred-method-name": "2.0.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-optimize-regex": "1.1.7",
    "eslint-plugin-perf-standard": "1.0.3",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-react": "7.19.0",
    "eslint-plugin-react-hooks": "3.0.0",
    "eslint-plugin-react-perf": "3.2.3",
    "eslint-plugin-react-redux": "3.0.3",
    "eslint-plugin-standard": "4.0.1",
    "eslint-plugin-xss": "0.1.10",
    "typescript": "3.8.3"
}
```

**Comment by JustFly1984** [comment]
@webOS101 

my `tsconfig.json` for any case:

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "src/*": ["src/*"]
    },
    "types": [
      "chart.js",
      "classnames",
      "cypress",
      "intl",
      "node",
      "node-fetch",
      "qrcode.react",
      "reach__router",
      "react-dom",
      "react-helmet",
      "react-redux",
      "react-toastify",
      "redux-actions",
      "redux-debounced",
      "showdown",
      "uniqid",
      "webpack",
      "webpack-env"
    ],
    "module": "commonjs",
    "target": "esnext",
    "jsx": "react",
    "lib": ["dom", "es2017"],
    "strict": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": false,
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true
  },
  "exclude": ["node_modules", "public", ".cache"]
}
```

**Comment by webOS101** [comment]
Explicitly enable the globals you need (`window` or `document`, for example) and only access the browser through those globals.  I can't speak to the typescript side of things as I just don't know enough about configuring that.

**Comment by ark120202** [comment]
There is a [`no-restricted-globals`](https://eslint.org/docs/rules/no-restricted-globals) rule for that. create-react-app is maintaining a [`confusing-browser-globals`](https://github.com/facebook/create-react-app/tree/master/packages/confusing-browser-globals) package, which is a list of globals you usually want to restrict, including `name` and `event`.

**Comment by webOS101** [comment]
That's a good solution, too. There is also this link I found:  https://github.com/microsoft/TypeScript/issues/14306#issuecomment-552890299

**Comment by mdjermanovic** [comment]
> As I recal, before in some project I had some kind of comment on top of the file which clearly lists all global variables used in the file, so no accident global variable do not snitch unnoticed, but can't remember how to enable this functionality again.
> 
> ```
> /* globals $ fetch */
> ```

You can set `env: { browser: false }` (instead of `true`) in your config and use `/* globals ...*/` comments to enable only browser globals you want to use in that file.

Or, as @webOS101 recommended in [this comment](https://github.com/eslint/eslint/issues/13127#issuecomment-611793349), enable just `window`/`document` and access browser globals only through those, in which case you should also set `env: { browser: false }`.

Either of these solutions would lead to [no-undef](https://eslint.org/docs/rules/no-undef) rule warnings on the `name` reference.

A problem with this might be if `@typescript-eslint/eslint-recommended` config turns `no-undef` off, in which case the solution with `no-restricted-globals` as recommended by @ark120202 in [this comment](https://github.com/eslint/eslint/issues/13127#issuecomment-611793564) looks like the best approach for a typescript project.

**Comment by JustFly1984** [comment]
@ark120202 no-restricted-globals seems like correct way to go in our case with typescript.
