### ISSUE TITLE
BigInt not support yet

### ISSUE THREAD

**Issue by willin** [eslint/eslint#13122]
**The version of ESLint you are using.**

6.8.0

**The problem you want to solve.**

BigInt Support

**Your take on the correct solution to problem.**

```js
console.log(1 === 1n);
// Parsing error: Identifier directly after number
```

```js
console.log(BigInt(1));
// 'BigInt' is not defined.
```

**Comment by anikethsaha** [comment]
Can you share your eslint config ? 
BigInt I think is available from es2020

`parserOptions: { ecmaVersion: 2020 }`

**Comment by willin** [comment]
@anikethsaha  https://github.com/tc39/proposals/blob/master/finished-proposals.md

besides, Optional Chaining is not supported too.

**Comment by anikethsaha** [comment]
> @anikethsaha https://github.com/tc39/proposals/blob/master/finished-proposals.md

yes, 2020 as I mentioned

> besides, Optional Chaining is not supported too.

this is work in progress.

**Comment by willin** [comment]
```yaml
root: true
extends: shiwangme
parserOptions:
  ecmaVersion: 2020
```
when i add  ecmaVersion:

```js
console.log(BigInt(1));
// 'BigInt' is not defined.
console.log(1n === 1);
// ok
```

**Comment by anikethsaha** [comment]
> ```js
> console.log(BigInt(1));
> ```
is 
```js
console.log(1n) //  use this one
```

Or else , try using `babel-eslint` if you want to use `BigInt` , though I am not sure about this whether they support it or not. 


> ```js
> const a = {};
> console.log(a?.b);
> // Parsing error: Unexpected token .
> ```

 its still in work in progress state, check this one https://github.com/eslint/eslint/issues/12642

Hope this helps 👍

**Comment by willin** [comment]
thx
