### ISSUE TITLE
eslint returns with parsing error unexpected token

### ISSUE THREAD

**Issue by hamedminaee** [eslint/eslint#13137]
In my vscode I have eslint enabled and I get the following error:

![image](https://user-images.githubusercontent.com/52859974/78305545-88521600-7517-11ea-816d-3bc7dc2fdcbc.png)

and here is the eslint config:

```
const path = require('path');
module.exports = {
  parser: 'babel-eslint',
  extends: [
    'airbnb',
    'plugin:import/recommended',
    'prettier',
    'plugin:security/recommended',
  ],
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      experimentalObjectRestSpread: true,
    },
  },
  env: {
    browser: true,
    jest: true,
    node: true,
    es6: true,
  },
  rules: {
    'prettier/prettier': 'error',
    'no-use-before-define': 0,
    'valid-jsdoc': 2,
    'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
    'import/no-webpack-loader-syntax': 0,
    'import/no-unresolved': 0,
    // "max-len": [ "error", 120 ],
    'security/detect-object-injection': 0,
    'jsx-a11y/label-has-for': 1,
    'no-nested-ternary': 0,
    "import/extensions": [
      0
    ]
  },
  plugins: ['import', 'prettier', 'security'],
  settings: {
    'import/resolver': {
      node: {
        paths: ['src'],
      },
    },
  },
};
```

and here is eslint libs in my package.json

```
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-redux-saga": "^0.8.0",
    "eslint-plugin-security": "^1.4.0",
```

I am not really sure what that error is at all. Am I missing anything? I appreciate any input

**Comment by nzakas** [comment]
There is no such “private” keyword in JavaScript. If you are trying to use TypeScript, you likely need to configure that for babel-eslint (which is not maintained by this team).

You may want to consult their docs:
https://github.com/babel/babel-eslint/blob/master/README.md

**Comment by anikethsaha** [comment]
use `typescript-eslint`  as this is a typescript code

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
