### ISSUE TITLE
Do not ignore eslintrc below eslintignore path

### ISSUE THREAD

**Issue by ofk** [eslint/eslint#13147]
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v12.16.1
* **npm Version:** using yarn 

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

.eslintignore:
```
/ignoreDir
```

ignoreDir/.eslintrc.json
```
{"extends":["invalid"]}
```

See https://github.com/ofk/eslint-ignore-test for full version.
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
$ node_modules/.bin/eslint ignoreDir/

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "invalid" to extend from. Please check that the name of the config is correct.

The config "invalid" was referenced from the config file in "/eslint-ignore-test/ignoreDir/.eslintrc.json".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**What did you expect to happen?**

I expected no output like `eslint .`.

I encountered this problem when I intentionally disabled eslint in a repository that uses multiple packages, `husky` and `lint-staged` .
In this case, I added `packages/` into `.eslintignore`, but the precommit hook runs `eslint --fix pages/foo/bar.js` .

**Comment by kaicataldo** [comment]
I think this is working as intended. Have you tried using a negative ignore pattern (prefixing with a `!`) for just `.eslintrc` files? Example:

```
ignoreDir
!ignoreDir/path/to/.eslintrc.json
```

**Comment by ofk** [comment]
Hmm. I also made an additional investigation. Let me explain it in more detail.

* eslint loads the child directory's `.eslintrc` recursively.
    * I understand this behavior.
* I want to block this loading. So, I put a directory path in `.eslintignore` .
    * This is `.eslintignore` 's `ignorePath` in [the sample](https://github.com/ofk/eslint-ignore-test). | hope that `ignorePath/.estrintrc.json` is *never* loaded. To make it easier to understand, the sample intentionally broke `.estrintrc` .

**Result**

1.
```
$ node_modules/.bin/eslint .
# no output
```

I expected. Document root specification ignores broken `.eslintrc` in child directory by `.eslintignore` .

2.
```
$ node_modules/.bin/eslint ignoreDir/

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "invalid" to extend from. Please check that the name of the config is correct.

The config "invalid" was referenced from the config file in "/eslint-ignore-test/ignoreDir/.eslintrc.json".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

`.eslintrc` validation performed, but I do not expect this. At first, I wrote that this correct output is empty, but it was a mistake. I expect the following.

```
$ node_modules/.bin/eslint ignoreDir/

Oops! Something went wrong! :(

ESLint: 6.8.0.

You are linting "ignoreDir/", but all of the files matching the glob pattern "ignoreDir/" are ignored.

If you don't want to lint these files, remove the pattern "ignoreDir/" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.
```

This is the same behavior as without `ignoreDir/.eslintrc.json` .

3.
```
$ node_modules/.bin/eslint ignoreDir/test.js

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "invalid" to extend from. Please check that the name of the config is correct.

The config "invalid" was referenced from the config file in "/eslint-ignore-test/ignoreDir/.eslintrc.json".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I don't expect this output. I expect the following.

```
$ node_modules/.bin/eslint ignoreDir/test.js

/eslint-ignore-test/ignoreDir/test.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```

This is the same behavior as without `ignoreDir/.eslintrc.json` .

P.S.

I tried your suggestion, but I didn't get the desired behavior of ignoring `.eslintrc` in child directory.

**Comment by kaicataldo** [comment]
Apologies for just getting around to following up. I misunderstood what you were reporting. I believe this is because ESLint traverses all the configuration files it finds to build up the list of files it needs to lint before it applies ignore patterns. 

This does feel like unexpected behavior from a user standpoint, though, and it would be nice to remove this behavior. Since [`ignorePatterns` in config files are overridden by .eslintignore file entries](https://eslint.org/docs/user-guide/configuring#ignorepatterns-in-config-files), I don't think there would be any danger in doing this, however it seems like it could incur a performance penalty, since it may have to resolve files matched by globs twice (once for the initial traversal of configuration files and a second time for the files to be linted).

All that being said, this might be solved by the [config file simplification RFC](https://github.com/eslint/rfcs/pull/9/files#diff-4fab19e15273179c525fc49a689b73a5R46).
