### ISSUE TITLE
The "indent" rule + "--fix" flag does not fix multi-line conditionals properly

### ISSUE THREAD

**Issue by Zamiell** [eslint/eslint#13154]
**Tell us about your environment**

```
Environment Info:

Node version: v12.13.0
npm version: v6.13.4
Local ESLint version: v6.8.0
Global ESLint version: Not found
```

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

eslintrc.js
```
module.exports = {
  rules: {
    indent: ['error', 2],
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

index.js
```js
if (
    longCondition1
    && longCondition2
    && longCondition3
    && longCondition4
) {
    console.log('all conditions met');
}
```

```bash
npx eslint index.js --fix
```

**What did you expect to happen?**

I expected the following code to get transformed to

index.js.fixed
```js
if (
  longCondition1
  && longCondition2
  && longCondition3
  && longCondition4
) {
  console.log('all conditions met');
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

Instead, it transformed the file into the following:

```js
if (
  longCondition1
    && longCondition2
    && longCondition3
    && longCondition4
) {
  console.log('all conditions met');
}
```

Eslint should be intelligent enough to know that I am using [Airbnb-style multi-line conditionals](https://github.com/airbnb/javascript/issues/1380#issuecomment-296262030) and indent it accordingly.

e.g. each condition is on its own line, open paren and close paren is on its own line, indent matches the number specified in the eslint "ident" rule, etc.

The Airbnb style is one of most popular styles in the world (if not the #1 most popular?), so I don't think this is a particularly outlandish request.

**Are you willing to submit a pull request to fix this bug?**

No.

**Comment by mdjermanovic** [comment]
This is related to #13153.

I don't think this is a bug in the actual version of the `indent` rule since it doesn't enforce indentation for multi-line expressions. New option `MultilineExpression` as proposed in #12248 would cover this.

**Comment by Zamiell** [comment]
Agreed. Will close, thank you mdjermanovic.
