### ISSUE TITLE
bug `no-unused-vars` - is assigned a value but never used

### ISSUE THREAD

**Issue by jonathantribouharet** [eslint/eslint#13172]
Node version: v13.11.0
npm version: v6.13.7
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found
Typescript Version: 3.8.3
VueJS Version: 2.6.11

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/recommended',
    '@vue/typescript/recommended',
  ],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    "indent": ["error", 2],
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/camelcase': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
  },
  settings: {
    polyfills: [
      "promises",
    ]
  }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
    let myArray = [1,2,3,4].filter((x) => x == 0);
    myArray = myArray.filter((x) => x == 1);
```

**What did you expect to happen?**
It should be an error.

**What actually happened? Please include the actual, raw output from ESLint.**
error  'myArray' is assigned a value but never used         no-unused-vars
error  'myArray' is assigned a value but never used         @typescript-eslint/no-unused-vars

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by anikethsaha** [comment]
I am not sure but I think this is intentional.
cause when using this 

```js
 let myArray = [1,2,3,4].filter((x) => x == 0);
    foo= myArray.filter((x) => x == 1);
```

it is lint-free. 

> Also just to note, that you are using both `@typescript-eslint/no-unused-vars` and `no-unused-vars` (from eslint). Its recommended to use `@typescript-eslint/no-unused-vars` and turn off the base rule (`no-unused-vars`) if its a TS project. this rule is extending the base rule (`no-unused-vars`)

**Comment by jonathantribouharet** [comment]
It feels strange, because my example is very trivial but I don't understand the why.
In my real case, I use the array in a loop  so I cannot create a new variable each time a reassign the variable `myArray`.

**Comment by anikethsaha** [comment]
I would chain them if possible. 

```js
let myArray = [1,2,3,4].filter((x) => x == 0).filter((x) => x == 1)
```

**Comment by jonathantribouharet** [comment]
In my real case the two operations are not exactly like this, the 2nd line is in a loop and the condition change.

**Comment by mdjermanovic** [comment]
@jonathantribouharet thanks for the bug report!

> ```js
>     let myArray = [1,2,3,4].filter((x) => x == 0);
>     myArray = myArray.filter((x) => x == 1);
> ```
> 
> 
> What did you expect to happen?
> It should be an error.
> What actually happened? Please include the actual, raw output from ESLint.
> error  'myArray' is assigned a value but never used         no-unused-vars
> error  'myArray' is assigned a value but never used         @typescript-eslint/no-unused-vars

Can you please clarify this issue, it seems that the actual behavior matches the expected behavior?

**Comment by jonathantribouharet** [comment]
@mdjermanovic the issue is I'm actually using the variable `myArray` so why having an error saying the opposite?

The real code look like this:

```
function (items: [OrderItem]) {
  let itemsToProcess = items.filter((x) => x.relationships.item.data != null);
  let results = items.filter((x) => x.relationships.item.data == null);
  results = results.sort((a, b) => b.amountWithVat - a.amountWithVat)

  itemsToProcess = itemsToProcess.filter((item) => {
    const parentId = item.relationships.item.data.id;

    const index = results.findIndex((x) => x.id == parentId);
    if (index >= 0) {
      results.splice(index + 1, 0, item);
      return false;
    }

    return true;
  })


  return results;
}
```

The error is on `itemsToProcess` on line 2.

**Comment by mdjermanovic** [comment]
> @mdjermanovic the issue is I'm actually using the variable `myArray` so why having an error saying the opposite?

`no-unused-vars` by design reports an error if the variable is used only to update itself.

I agree it would be nice to change the error message in this case.

> The real code look like this:
> 
> ```
> function (items: [OrderItem]) {
>   let itemsToProcess = items.filter((x) => x.relationships.item.data != null);
>   let results = items.filter((x) => x.relationships.item.data == null);
>   results = results.sort((a, b) => b.amountWithVat - a.amountWithVat)
> 
>   itemsToProcess = itemsToProcess.filter((item) => {
>     const parentId = item.relationships.item.data.id;
> 
>     const index = results.findIndex((x) => x.id == parentId);
>     if (index >= 0) {
>       results.splice(index + 1, 0, item);
>       return false;
>     }
> 
>     return true;
>   })
> 
>   itemsToProcess.filter((item) => {
>     const parentId = item.relationships.item.data.id;
> 
>     const index = results.findIndex((x) => x.id == parentId);
>     if (index >= 0) {
>       results.splice(index + 1, 0, item);
>       return false;
>     }
> 
>     return true;
>   })
> 
>   return results;
> }
> ```
> 
> The error is on `itemsToProcess` on line 2.

This would be a bug, but I can't reproduce it. Please let me know if I'm missing something.

config: 

```js
module.exports = {
    parser: "@typescript-eslint/parser",
    plugins: ["@typescript-eslint"],
    rules : {
        'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
        '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }]
    },
};
```

code (had to add function's name to make it valid syntax):

```js
function foo(items: [OrderItem]) {
    let itemsToProcess = items.filter((x) => x.relationships.item.data != null);
    let results = items.filter((x) => x.relationships.item.data == null);
    results = results.sort((a, b) => b.amountWithVat - a.amountWithVat)
  
    itemsToProcess = itemsToProcess.filter((item) => {
      const parentId = item.relationships.item.data.id;
  
      const index = results.findIndex((x) => x.id == parentId);
      if (index >= 0) {
        results.splice(index + 1, 0, item);
        return false;
      }
  
      return true;
    })
  
    itemsToProcess.filter((item) => {
      const parentId = item.relationships.item.data.id;
  
      const index = results.findIndex((x) => x.id == parentId);
      if (index >= 0) {
        results.splice(index + 1, 0, item);
        return false;
      }
  
      return true;
    })
  
    return results;
  }
```

output:

```
  1:10  error  'foo' is defined but never used  no-unused-vars
  1:10  error  'foo' is defined but never used  @typescript-eslint/no-unused-vars
```

Neither of the two `no-unused-vars` rules reports errors on `itemsToProcess`.

I also tried with `@typescript-eslint/parser` and the result is same.

Here's also [online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICduby11bnVzZWQtdmFycyc6IFsnZXJyb3InLCB7IGFyZ3NJZ25vcmVQYXR0ZXJuOiAnXl8nIH1dICovICAgXG5cbmZ1bmN0aW9uIGZvbyhpdGVtcykge1xuICAgIGxldCBpdGVtc1RvUHJvY2VzcyA9IGl0ZW1zLmZpbHRlcigoeCkgPT4geC5yZWxhdGlvbnNoaXBzLml0ZW0uZGF0YSAhPSBudWxsKTtcbiAgICBsZXQgcmVzdWx0cyA9IGl0ZW1zLmZpbHRlcigoeCkgPT4geC5yZWxhdGlvbnNoaXBzLml0ZW0uZGF0YSA9PSBudWxsKTtcbiAgICByZXN1bHRzID0gcmVzdWx0cy5zb3J0KChhLCBiKSA9PiBiLmFtb3VudFdpdGhWYXQgLSBhLmFtb3VudFdpdGhWYXQpXG4gIFxuICAgIGl0ZW1zVG9Qcm9jZXNzID0gaXRlbXNUb1Byb2Nlc3MuZmlsdGVyKChpdGVtKSA9PiB7XG4gICAgICBjb25zdCBwYXJlbnRJZCA9IGl0ZW0ucmVsYXRpb25zaGlwcy5pdGVtLmRhdGEuaWQ7XG4gIFxuICAgICAgY29uc3QgaW5kZXggPSByZXN1bHRzLmZpbmRJbmRleCgoeCkgPT4geC5pZCA9PSBwYXJlbnRJZCk7XG4gICAgICBpZiAoaW5kZXggPj0gMCkge1xuICAgICAgICByZXN1bHRzLnNwbGljZShpbmRleCArIDEsIDAsIGl0ZW0pO1xuICAgICAgICByZXR1cm4gZmFsc2U7XG4gICAgICB9XG4gIFxuICAgICAgcmV0dXJuIHRydWU7XG4gICAgfSlcbiAgXG4gICAgaXRlbXNUb1Byb2Nlc3MuZmlsdGVyKChpdGVtKSA9PiB7XG4gICAgICBjb25zdCBwYXJlbnRJZCA9IGl0ZW0ucmVsYXRpb25zaGlwcy5pdGVtLmRhdGEuaWQ7XG4gIFxuICAgICAgY29uc3QgaW5kZXggPSByZXN1bHRzLmZpbmRJbmRleCgoeCkgPT4geC5pZCA9PSBwYXJlbnRJZCk7XG4gICAgICBpZiAoaW5kZXggPj0gMCkge1xuICAgICAgICByZXN1bHRzLnNwbGljZShpbmRleCArIDEsIDAsIGl0ZW0pO1xuICAgICAgICByZXR1cm4gZmFsc2U7XG4gICAgICB9XG4gIFxuICAgICAgcmV0dXJuIHRydWU7XG4gICAgfSlcbiAgXG4gICAgcmV0dXJuIHJlc3VsdHM7XG4gIH0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) with the default parser.

**Comment by jonathantribouharet** [comment]
Ok it makes sense for the rule
For the online demo, I see the problem, in fact the code I sent wasn't good, it is:

```
/* eslint 'no-unused-vars': ['error', { argsIgnorePattern: '^_' }] */   

function foo(items) {
    let itemsToProcess = items.filter((x) => x.relationships.item.data != null);
    let results = items.filter((x) => x.relationships.item.data == null);
    results = results.sort((a, b) => b.amountWithVat - a.amountWithVat)
  
    itemsToProcess = itemsToProcess.filter((item) => {
      const parentId = item.relationships.item.data.id;
  
      const index = results.findIndex((x) => x.id == parentId);
      if (index >= 0) {
        results.splice(index + 1, 0, item);
        return false;
      }
  
      return true;
    })
  
    itemsToProcess = itemsToProcess.filter((item) => {
      const parentId = item.relationships.item.data.id;
  
      const index = results.findIndex((x) => x.id == parentId);
      if (index >= 0) {
        results.splice(index + 1, 0, item);
        return false;
      }
  
      return true;
    })
  
    return results;
  }
```

And the problem is line 20 with `itemsToProcess = itemsToProcess` where I don't use afterwards `itemsToProcess` but the error appear on line 4 at the declaration. So there is no problem with the rule, maybe just indicate the line 20 instead of line 4.

**Comment by mdjermanovic** [comment]
> And the problem is line 20 with `itemsToProcess = itemsToProcess` where I don't use afterwards `itemsToProcess` but the error appear on line 4 at the declaration. So there is no problem with the rule, maybe just indicate the line 20 instead of line 4.

Makes sense :+1: 

I believe this is the same request as #12871, which unfortunately didn't reach [consensus](https://eslint.org/docs/maintainer-guide/issues#accepting-issues) at the time.

I think we could at least change the error message.

**Comment by anikethsaha** [comment]
Yes, it should report at the latest references instead of the declaration if it has references.

**Comment by nzakas** [comment]
Can someone make a concrete proposal so we can decide on it?

**Comment by anikethsaha** [comment]
@nzakas I made a fresh issue with the proposal here https://github.com/eslint/eslint/issues/13181
