### ISSUE TITLE
node_modules is not ignored when running from a child-module

### ISSUE THREAD

**Issue by cambiph** [eslint/eslint#13187]
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v13.12.0
* **npm Version:** v6.14.4

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "google"
    ],
    "ignorePatterns": [
        "../../node_modules/",
        "CODEOWNERS",
        "*.yml",
        "package-lock.json"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

https://github.com/milieuinfo/webcomponent-vl-ui-button/tree/eslint uses vl-ui-util#UIG-292
which has the eslint config. In vl-ui-button  run the following command to start the linting process:
```bash 
npm explore vl-ui-util -- npm run format
```

```bash
eslint ../../. --ext .js --ext .css --ext .html -c .eslintrc.json --no-eslintrc --debug
```

**What did you expect to happen?**
The node_modules folder of vl-ui-button should be ignored.

**What actually happened? Please include the actual, raw output from ESLint.**
The node_modules folder of vl-ui-button is processed. An excerpt of the debug logging:

```
} +0ms
  eslint:file-enumerator Didn't match: semver +0ms
  eslint:file-enumerator Leave the directory: /Users/philippe/Documents/localdev/webcomponent-vl-ui-button/node_modules/@babel/core/node_modules/semver/bin +0ms
  eslint:ignore-pattern Check {
  filePath: '/Users/philippe/Documents/localdev/webcomponent-vl-ui-button/node_modules/@babel/core/node_modules/semver/package.json',
  dot: false,
  relativePath: '../@babel/core/node_modules/semver/package.json',
  result: false
} +0ms
  eslint:file-enumerator Didn't match: package.json +0ms
  eslint:ignore-pattern Check {
  filePath: '/Users/philippe/Documents/localdev/webcomponent-vl-ui-button/node_modules/@babel/core/node_modules/semver/range.bnf',
  dot: false,
  relativePath: '../@babel/core/node_modules/semver/range.bnf',
  result: false
} +0ms
  eslint:file-enumerator Didn't match: range.bnf +0ms
  eslint:ignore-pattern Check {
  filePath: '/Users/philippe/Documents/localdev/webcomponent-vl-ui-button/node_modules/@babel/core/node_modules/semver/semver.js',
  dot: false,
  relativePath: '../@babel/core/node_modules/semver/semver.js',
  result: false
} +0ms 
```

The problem has been fixed a long time ago but it seemls to be back:
https://github.com/eslint/eslint/issues/3788

**Are you willing to submit a pull request to fix this bug?**
If I know where the problem lies, yes.

**Comment by cambiph** [comment]
Bump

**Comment by kaicataldo** [comment]
This should be enabled by default in v7.0.0 (see the [migration guide](https://eslint.org/docs/user-guide/migrating-to-7.0.0#default-ignore-patterns). If you can't upgrade, you should be able to also explicitly ignore these directories by specifying them in your `.eslintignore` file.

**Comment by cambiph** [comment]
Works with v7, thanks for the info!
