### ISSUE TITLE
eslint breaks `.d.ts` files

### ISSUE THREAD

**Issue by dora-gt** [eslint/eslint#13182]
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** v12.16.1
* **npm Version:** 6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
    'prettier',
    'prettier/vue',
    'plugin:prettier/recommended',
    'plugin:nuxt/recommended'
  ],
  plugins: [
    'prettier'
  ],
  // add your custom rules here
  rules: {
  },
  ignorePatterns: ["docs/"]
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

declare module '*/office.gql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const AllOffices: DocumentNode;

  export default defaultDocument;
}
    

declare module '*/p-graphql.gql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const HelloMessage: DocumentNode;
export const HelloValue1: DocumentNode;
export const HelloValue2: DocumentNode;
export const HelloValue3: DocumentNode;
export const Hi: DocumentNode;
export const HelloAndHi: DocumentNode;

  export default defaultDocument;
}
```

```bash
yarn eslint --fix xxx.d.ts
```

**What did you expect to happen?**
```js
declare module '*/office.gql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    export const AllOffices: DocumentNode;

    export default defaultDocument;
}

declare module '*/p-graphql.gql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    export const HelloMessage: DocumentNode;
    export const HelloValue1: DocumentNode;
    export const HelloValue2: DocumentNode;
    export const HelloValue3: DocumentNode;
    export const Hi: DocumentNode;
    export const HelloAndHi: DocumentNode;

    export default defaultDocument;
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
declare module '*/office.gql' {
    import { DocumentNode, DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    export const AllOffices: DocumentNode;

    export default defaultDocument;
}

declare module '*/p-graphql.gql' {
    const defaultDocument: DocumentNode;
    export const HelloMessage: DocumentNode;
    export const HelloValue1: DocumentNode;
    export const HelloValue2: DocumentNode;
    export const HelloValue3: DocumentNode;
    export const Hi: DocumentNode;
    export const HelloAndHi: DocumentNode;

    export default defaultDocument;
}
```

**Comment by anikethsaha** [comment]
eslint's default parser cant parse typescript code. you need to change the parser to [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint)

**Comment by dora-gt** [comment]
It works perfectly with the other `.ts` files. 🤔

**Comment by anikethsaha** [comment]
opps, `@nuxtjs/eslint-config-typescript` does uses `typescript-eslint/parser`.

**Comment by anikethsaha** [comment]
can you just try turning `import/order` off for the file ? not sure about this but I do think that there might be some inconsistency with this rule

**Comment by mdjermanovic** [comment]
@dora-gt thanks for the issue!

This seems to be caused by a third-party rule: [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/no-duplicates.md)

Please create an issue in the `eslint-plugin-import` repository:

https://github.com/benmosher/eslint-plugin-import

**Comment by dora-gt** [comment]
hmmm it didn't work... 😞

**Comment by dora-gt** [comment]
Disabling `import/no-duplicates` worked!
Thank you so much 🙇 I'll report there.
