### ISSUE TITLE
ESLint fails parsing files containing obsolete ES syntax

### ISSUE THREAD

**Issue by DenyVeyten** [eslint/eslint#13186]
**The version of ESLint you are using.**
^6.7.2 (but it should be related to any version)

**The problem you want to solve.**
ESLint fails parsing files containing obsolete ES syntax
For example, E4X - https://developer.mozilla.org/en-US/docs/Archive/Web/E4X

**Your take on the correct solution to the problem.**
Add an ability to ignore lines or code blocks for parser engine

**Are you willing to submit a pull request to implement this change?**
Yes, but it feels too hard for me :)

**Comment by g-plane** [comment]
Hello, this is not a valid feature in ES, so ESLint cannot support it.

**Comment by DenyVeyten** [comment]
Hi, @g-plane, what did you mean by "not a valid feature is ES"? This is about [ECMA-357 standard](https://www.ecma-international.org/publications/files/ECMA-ST-WITHDRAWN/Ecma-357.pdf)
It currently used by [Salesforce B2C Commerce](https://www.salesforce.com/products/commerce-cloud/ecommerce/) and maybe by other platforms powered by old JS engines.
But this is just one example of obsolete ES syntax, there may be more. And if tomorrow some ES syntax become obsolete, ESLint will support one obsolete syntax and does not support another? This is not logically from that point of view.

**Comment by g-plane** [comment]
The standard which ESLint supports is ECMA-262, not ECMA-357.

**Comment by kaicataldo** [comment]
To expand on what @g-plane has said, adding support for this syntax would have to be done with a 3rd party custom parser. ESLint doesn't support this standard, and so we won't adding support in the default parser.

**Comment by DenyVeyten** [comment]
I've got the point, some custom parser should be used as per https://eslint.org/docs/developer-guide/working-with-custom-parsers
Thanks for explanations!

**Comment by kaicataldo** [comment]
No problem!
