### ISSUE TITLE
eslint never finishes

### ISSUE THREAD

**Issue by gregid** [eslint/eslint#13209]
After I added some external files to the project and pushed to gitlab the CI running `eslint .` failed after hour due to time out. The same when I run it on my desktop - `eslint .` causes only blinking cursor and no action no matter how long I leave it to run.
After adding `.eslintignore` to the project exluding newly added folder it successfully finishes it on gitlab CI (running docker container). On the desktop however the problem persists. I tried uninstalling and installing eslint but that didn't help. Is there maybe some eslint cache that could cause the problem?

Environment:

OS: Win10
Node version: v13.5.0
npm version: v6.13.4
Local ESLint version: v6.8.0
Global ESLint version: Not found

**Comment by gregid** [comment]
Update: After leaving it run for few hours It finally completed but it still processes files that are set to ignore in `.eslintignore`.

**Comment by anikethsaha** [comment]
I think there might be something buggy with the ignore pattern you are using. 
and about the not finishing, it might be linting node_modules which are not in the root or in some nested folder.

**Comment by gregid** [comment]
that was also my initial thought but the ignore pattern works with gitlab CI (linux docker). 
I have already tried a few variations but is there any option to dry run eslint - to list all the files that will be checked? This could really help debugging the issue.

**Comment by anikethsaha** [comment]
> that was also my initial thought but the ignore pattern works with gitlab CI (linux docker).

so those files in `.eslintignore` are not linting in gitlab but they are in your local ?

**Comment by gregid** [comment]
yes that's correct

**Comment by anikethsaha** [comment]
Umm 🤔 ...that's weird. 

I do think they are being lint in gitlab as well but it may be fast so it finishes soon. 
I can only think of some bug in the pattern for this case. 
May be someone else can have better input in this.

**Comment by gregid** [comment]
Without the ignore patterns it also failed in gitlab after 1 hour (time out). With the pattern it finishes in under 1 min

**Comment by mdjermanovic** [comment]
If it helps with debugging in this case, you can run eslint on a single file, i.e. `eslint path/to/file.js`.

There should be a "File ignored because of a matching ignore pattern" warning if that file is ignored.

**Comment by gregid** [comment]
@mdjermanovic thanks for pointer it helped me to identify the problem - the pattern was correct but the difference between remote and local repo was additional dist folder created by parcel for a demo app (that bundled these external files).
The issue can be considered closed but I would like to raise a feature request for `--list-only` that would list all the files and their paths that will be linted.

**Comment by mdjermanovic** [comment]
Glad you solved this! Feel free to open an issue for a feature request.
