### ISSUE TITLE
工程启动时，正则匹配eslint错误

### ISSUE THREAD

**Issue by wangwang001** [eslint/eslint#13207]
Syntax Error: F:\vue-next-test\node_modules\eslint\lib\rules\no-octal-escape.js:41
                    /$(?:[^\\]|\\.)*?\\([0-3][0-7]{1,2}|[4-7][0-7]|0(?=[89])|[1-7])/su
                    ^

SyntaxError: Invalid regular expression flags
    at Array.forEach (<anonymous>)

 @ multi (webpack)-dev-server/client?http://192.168.46.245:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by mdjermanovic** [comment]
@wangwang001 thanks for the issue!

There's not enough information, but you're most likely using an old Node version.
