### ISSUE TITLE
Add --list-only option to eslint CLI

### ISSUE THREAD

**Issue by gregid** [eslint/eslint#13212]
Continuation of #13209.
ESLint version: v6.8.0

At the moment if `eslint .` processes files that it shouldn't (e.g. some large external files), the lint may take hours to finish. This makes it really hard to identify what's the culprit.

I propose adding new `--list-only` option to eslint CLI that will print out all the file names (and their paths) that will be linted with current set up. This will make debugging processes that take too long much easier.

**Comment by kaicataldo** [comment]
This sounds useful. I'm generally in support of this, though I'm not convinced of the command line flag name. I wonder if it would also make sense sense to add a corresponding option to the public Node API as well.

Since this is an addition to core, would you like to create an [RFC](https://github.com/eslint/rfcs)?

**Comment by anikethsaha** [comment]
this seems good enhancement. 
currently using `--debug` you can get the list of file which will be linted. 

![image](https://user-images.githubusercontent.com/26347874/80091806-557fc880-857f-11ea-98b5-12675f922c0f.png)

**Comment by gregid** [comment]
Sure I will take a look at starting the RFC. As to the name it was just the first thing that came to mind. How about `--ls-files` similar to git ls-files which does something similar.
As to Node API, I haven't had a need to use it yet but being able to get list of files to be linted may be useful from there as well.
`--debug` gives pretty much all information but it also executes the lint itself, hence the proposal.
