### ISSUE TITLE
Max Warnings Configuration Option

### ISSUE THREAD

**Issue by fishcharlie** [eslint/eslint#13220]
**The version of ESLint you are using.**

6.8.0

**The problem you want to solve.**

Keep configuration all in one place instead of separating between CLI and configuration file, specifically for [`max-warnings`](https://eslint.org/docs/user-guide/command-line-interface#max-warnings).

**Your take on the correct solution to problem.**

Add `maxWarnings` option to configuration file that has same behavior as [`max-warnings` CLI option](https://eslint.org/docs/user-guide/command-line-interface#max-warnings).

**Are you willing to submit a pull request to implement this change?**

Possibly, if someone can help guide me with which files to modify and look into. Haven't looked at all into the code base of this repo, but willing to spend a little bit of time diving in.

**Comment by anikethsaha** [comment]
I do think this should be a part of [RFC](https://github.com/eslint/rfcs) first as this is a change in the core.
cause currently `max-warnings` is being resolved and used in the `cli.js`.
Some options are being passed to `cli-engine.js` from `cli.js` but I think the reverse is not true.

**Comment by drianoaz** [comment]
I thought it was possible to use the CLI settings via file, but I was wrong. Some settings like max-warnings would be really cool to be in the configuration file instead of being lost in package.json.
