### ISSUE TITLE
[Suggestion] Make breaking changes conspicuously

### ISSUE THREAD

**Issue by Mister-Hope** [eslint/eslint#13225]
I dont think the description on the release page looks good.
Can we make a part to place all the breaking changes as other repo? Maybe something like this:

> 
> ## Breaking Changes
> 
> - ........................
> - ........................
> - ........................
> 
> ## Changes
> 
> - ........................
> - ........................
> - ........................

Thanks.

BTW, there isn't a classification like "Suggestion" or "Feature Request", so I choose the bug.

**Comment by kaicataldo** [comment]
> Can we make a part to place all the breaking changes as other repo? 

Can you clarify what you mean by this?

**Comment by Mister-Hope** [comment]
You can have a look at your release page, it can take people an hour time wasted if they are on alpha channel with your team,

Please mark every breaking changes in every version clearly.

**Comment by Mister-Hope** [comment]
https://github.com/eslint/eslint/releases/tag/v7.0.0 Look here, emm the other repo's release page is definitly not like this.

**Comment by anikethsaha** [comment]
maybe [this](https://eslint.org/docs/user-guide/migrating-to-7.0.0) can be helpful 👍

**Comment by Mister-Hope** [comment]
> maybe [this](https://eslint.org/docs/user-guide/migrating-to-7.0.0) can be helpful 👍 

I know this page, but I open this issue a few days ago. It's not a good experience for me following all the alpha versions.

I think people will be more willing to follow the alpha version and report bugs if the breaking changes are all marked up clearly.

**Comment by Ajitesh13** [comment]
Hello, Is this bug confirmed and open to contributions?

**Comment by kaicataldo** [comment]
@Mister-Hope We do list breaking changes in their own category (see https://eslint.org/blog/2020/01/eslint-v7.0.0-alpha.0-released#breaking-changes, for example), which it sounds like is the ask. If I'm wrong about that, can you clarify what you mean?

**Comment by kaicataldo** [comment]
@Ajitesh13 I don't believe there is a bug here, but are always happy to improve our release notes.

**Comment by swetankraj** [comment]
@kaicataldo A suggestion - wouldn't it be nice to format CHANGELOG markdown file (here https://github.com/eslint/eslint/blob/master/CHANGELOG.md) something like this they do in Angular (here https://github.com/angular/angular/blob/master/CHANGELOG.md) decriptive, sections dedicated to releases, bugs and also addressing breaking changes?

**Comment by kaicataldo** [comment]
@swetankraj I'm personally definitely not against that! We should already have the logic that creates these changelogs because that's how we format our release notes. For some context, we treat the release notes on the ESLint website (see https://eslint.org/blog/2020/05/eslint-v7.0.0-released, for example) as our official changelog/release notes.

**Comment by swetankraj** [comment]
@kaicataldo If ESLint's website is serving the purpose, then we shouldn't be worried. But if someone is landing on github shouldn't the format must stay here similar too ? Or a link to offical changlelog/release notes ? Otherwise would it be hard to append those "well structured" release notes in markdown file from website? Just curious. :D

**Comment by kaicataldo** [comment]
I do think it would be an improvement, yes. I’d love to hear opinions from the rest of the team.

**Comment by Mister-Hope** [comment]
> @Mister-Hope We do list breaking changes in their own category (see https://eslint.org/blog/2020/01/eslint-v7.0.0-alpha.0-released#breaking-changes, for example), which it sounds like is the ask. If I'm wrong about that, can you clarify what you mean?

Wow, I did not know that, I believe there are some people like me wound like to watch this repo for release and look at the release page directly

**Comment by Mister-Hope** [comment]
> @kaicataldo A suggestion - wouldn't it be nice to format CHANGELOG markdown file (here https://github.com/eslint/eslint/blob/master/CHANGELOG.md) something like this they do in Angular (here https://github.com/angular/angular/blob/master/CHANGELOG.md) decriptive, sections dedicated to releases, bugs and also addressing breaking changes? 

That's what I mean, format changelog and release description like this

**Comment by jescalan** [comment]
Just want to pitch in here and agree with the sentiment - I was upgrading to `7.0.0` and headed over to the releases to see a changelog there in a nightmarish format with all commits just listed in order. Only found the migration link in the blog in this issue.

I feel like it would be more useful even to remove the commit log from the github releases and replace this with a link to the blog post 😀

**Comment by kaicataldo** [comment]
> I feel like it would be more useful even to remove the commit log from the github releases and replace this with a link to the blog post grinning

Why not both? :smile:

**Comment by StringEpsilon** [comment]
Here a slightly improved version of the current changelog for v7:

https://gist.github.com/StringEpsilon/327709e8cc49b7485d6f5b22960e892f

I basically just took the existing list, moved the commit IDs to the right side, sorted the list alphabetically to get the categories grouped. Then I moved some stuff around and condensed / deleted some duplicated entries (such as "Sponsors: Sync README with website). Finally, I added the headlines and the link to the migration guide. I'm sure the changelog can be condensed even further, but I really don't know what is and isn't relevant.

**Comment by kaicataldo** [comment]
I'm personally for formatting the release notes changelogs, but we'll want to make sure it's automated so that we don't have to manually sort everything during a release.

**Comment by andreymal** [comment]
The current changelog is awful, it's very hard to read. A raw and unsorted commit list is always a bad changelog.

StringEpsilon's suggestion is good (but not ideal).

**Comment by StringEpsilon** [comment]
Just saw that there was a new release. Took a couple minutes to make a slightly beautified changelog for that one as well:

https://gist.github.com/StringEpsilon/ed2b1f90f5dd42c46b981b2baee2961f
