### ISSUE TITLE
Auto-fix typescript's no-unused-var rule using --init

### ISSUE THREAD

**Issue by davc0n** [eslint/eslint#13233]
**The version of ESLint you are using.**
6.8.0

**The problem you want to solve.**
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md

**Your take on the correct solution to problem.**
Using eslint --init, if chosen that typescript is in use, those rules should be added automatically.

**Are you willing to submit a pull request to implement this change?**
No

**Comment by kaicataldo** [comment]
I don't think we should get in the business of picking specific rules to enable in `--init`, but I do think it could make sense to enable `plugin:@typescript-eslint/recommended` (we do the same for the React plugin).

**Comment by anikethsaha** [comment]
`plugin:@typescript-eslint/recommended` will be added if `eslint:recommended` is added.

[implemented-here](https://github.com/eslint/eslint/blob/master/lib/init/config-initializer.js#L327-L329)

adding of `eslint:recommended` depends on `purpose` name from the interactive cli. 
@davc0n can you share your answer which you shared. 


@kaicataldo maybe we should add the typescript-eslint/recommended added irrespective of `eslint:recommended`. WDYT ?

**Comment by kaicataldo** [comment]
It's a bit confusing, but we add `plugin:@typescript-eslint/eslint-recommended`, not `plugin:@typescript-eslint/recommended`. The former is designed to be used with `eslint:recommended`, and adjusts the config for a TypeScript codebase. You can see more details [here](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs).

What I suggested above is doing the following:

```json
{
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ]
}
```

**Comment by anikethsaha** [comment]
I didnt know there are two recommended configs from typescript-eslint 😄 

```
{
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ]
}
```

yes, this is much better. 👍

**Comment by davc0n** [comment]
In the init process I did specify that typescript is in use, so those extends are present in config:
```
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended"
    ],
```

`"plugin:@typescript-eslint/recommended"` includes the following rules ?

```
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": [
            "error"
        ]
```

If so, adding the additional extend when typescript is chosen should be fine. Otherwise, I would simply include those rules, without an explicit question (actually some rules might be asked, but I think this one is not needed since typescript related)

**Comment by kaicataldo** [comment]
@aladdin-add Can you explain why this is marked as accepted?

**Comment by aladdin-add** [comment]
it is as you suggested in https://github.com/eslint/eslint/issues/13233#issuecomment-620731808 ?

or we need 3+ 👍 from the team?

**Comment by kaicataldo** [comment]
Yeah, I don't think we should bypass our standard approval process. I'd like for other members of the team to have the chance to give their input.

**Comment by kaicataldo** [comment]
I'm championing this, but for the sake of making it easier to understand where we stand, can supporting team members please put :+1:s on the [corresponding PR](https://github.com/eslint/eslint/pull/13235) rather than this issue?
