### ISSUE TITLE
Support ES6 default exports in 'rulesdir' 

### ISSUE THREAD

**Issue by ulrichb** [eslint/eslint#13232]
**The version of ESLint you are using:** 6.8.0 (same with current 7.0)

**The problem you want to solve.**

Atm. when using ES6 "default exports" (`exports.default = { /* ... `) in a `--rulesdir` rule / (instead of `module.exports = { ...`), ESLint fails with _"Error while loading rule 'my_rule': rule.create is not a function"_.

See https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export  and https://stackoverflow.com/questions/40294870/ for reference.

**Your take on the correct solution to problem.**

Detect ES6 default exports within `load-rules` ...

https://github.com/eslint/eslint/blob/fdfa364c1b0d88689d02cbe8ae848a3e323209aa/lib/cli-engine/load-rules.js#L41

... by (additionally) checking for `.default` in the `require()` result.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Why can't you just use `module.exports =`?**

Because the `exports.default = ` is a transpiler output.

**Comment by kaicataldo** [comment]
I'm :-1: because this output is not standard Node syntax. `exports.default` in CommonJS is not equivalent to ESM `export default`, and I think we should be putting out efforts towards supporting actual ESM rather than special casing output from a specific compiler.

**Comment by ulrichb** [comment]
I agree that supporting ES6 modules fully (using the async dynamic `import()` function) would be better.

But as this is still [marked as experimental in Node](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_ecmascript_modules) (and available without a flag only since Node 13/14) I'd vote for an solution until we have it.

Two more arguments:

* The `exports.default` isn't some weird proprietary hack, but nowadays _the_ convention for ES6 modules in CommonJS, just [search for "__esModule default"](https://www.google.com/search?q=__esModule+default) or see the [corresponding Babel plugin](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs).

* Mentioning Babel: Just as an example it itself supports this pattern when dynamically importing configuration modules:

  https://github.com/babel/babel/blob/2d8edf7c6f1b077e0c92cbd18a9b3b3f59642e88/packages/babel-core/src/config/files/module-types.js#L48

**Comment by kaicataldo** [comment]
I'm personally not in favor of adding special cases when there is a clear path forward, but let's see what other team members have to say. As a workaround in the meantime, I believe you could add a wrapper module that imports `exports.default` and exports as `module.exports`.
