### ISSUE TITLE
[release]: generating website during prereleases can be improved

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#13231]
**The version of ESLint you are using.**
`master`

**The problem you want to solve.**
There are currently a few issues with our site generation script surrounding the process of releasing prerelease versions.

1. The [`_data/rules.yml` file](https://github.com/eslint/website/blob/master/_data/rules.yml) in the website repo gets updated to include rules that have been added during the prerelease. This means that we end up with broken links on our rules page, because the actual documentation for these rules only exists in `/docs/7.0.0/rules/`.
1. We currently have to manually copy over the previous version of the documentation when we start a new major release cycle. It doesn't look like this was done with this current release cycle, so I believe the documentation in `docs/6.0.0/` is the documentation that was generated during that prerelease cycle and would therefore be out of date.

**Your take on the correct solution to problem.**
1.  Do not regenerate the `_data/rules.yml` file during prereleases (fixed by https://github.com/eslint/eslint/pull/13230).
1. I _think_ this could be fixed by always copying over the current documentation into the corresponding `/docs/{version}/` as well as the top level `/docs/` directory, regardless of whether we're running a prerelease or not. The current system treats these directories as temporary pages (only up to date during the prerelease stage of our major release process), which I think is both confusing and forces us to manual update the files.

**Are you willing to submit a pull request to implement this change?**
Yes!

**Comment by kaicataldo** [comment]
Reopening this to track any work we do to solve #2.

**Comment by aladdin-add** [comment]
closing as outdated.
