### ISSUE TITLE
no-useless-backreference and default-case-last - docs page 404

### ISSUE THREAD

**Issue by devansvd** [eslint/eslint#13249]
URL - [https://eslint.org/docs/rules/no-useless-backreference](https://eslint.org/docs/rules/no-useless-backreference) is missing 404 in the docs ? Is this intentional ?

I can see this inside docs repo - https://github.com/eslint/eslint/blob/master/docs/rules/no-useless-backreference.md

Also, default case last doc 404 - URL - https://eslint.org/docs/rules/default-case-last 

![Screen Shot 2020-05-02 at 22 59 25](https://user-images.githubusercontent.com/11324776/80871210-13fec400-8cc9-11ea-9b9d-d78bab8729dd.png)

**Comment by anikethsaha** [comment]
they are added in `7.0.0-apha.0` check [here](https://eslint.org/docs/7.0.0/rules/no-useless-backreference) , [here](https://eslint.org/docs/7.0.0/rules/default-case-last)

[release note](https://eslint.org/blog/2020/01/eslint-v7.0.0-alpha.0-released#top)

I think it will reflect as default when `7.0.0` is out of alpha. *not sure tho*

**Comment by devansvd** [comment]
Ok got it thanks
