### ISSUE TITLE
Non-rule change request

### ISSUE THREAD

**Issue by 137717unity** [eslint/eslint#13259]
**The version of ESLint you are using.**

**The problem you want to solve.**

**Your take on the correct solution to problem.**

**Are you willing to submit a pull request to implement this change?**

**Comment by anikethsaha** [comment]
@yeonjuan I think this is a spam a account , ref https://github.com/eslint/eslint/pull/13257, https://github.com/eslint/eslint/pull/13258

also, I checked his/her account and other PRs, all same.

I think this issue and other PR can be close with a note if its fine !

**Comment by g-plane** [comment]
@anikethsaha Thanks for figuring out that!

@137717unity Closing since it's not a valid issue. You can ask questions at [Gitter](https://gitter.im/eslint/eslint).
