### ISSUE TITLE
Add `multiline-return` STATEMENT_TYPE to padding-line-between-statements rule

### ISSUE THREAD

**Issue by 185driver** [eslint/eslint#13262]
**What rule do you want to change?**
`padding-line-between-statements`
Specifically, add a `multiline-return` STATEMENT_TYPE to it.

**Does this change cause the rule to produce more or fewer warnings?**
more

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option.

**Please provide some example code that this change will affect:**

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: "*", next: "multiline-return" }
]*/
const movie = 'title';
return {
  that: 'thing',
  you: 'do',
};
```

**What does the rule currently do for this code?**
No `padding-line-between-statements` observer can be set for `multiline-return` statements, specifically. All return statements line lengths are treated the same.

**What will the rule do after it's changed?**
A padding line would be added just before the return statement if used per my sample code above.

**Are you willing to submit a pull request to implement this change?**
Apologies. Not at this time.

**Comment by anikethsaha** [comment]
```js
return {
  that: "thing",
  you: "do"
};
```

is considered as object, so if it is to be included in `multiline-block-like`, then this code will throw an error as well.

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: "*", next: "multiline-block-like" }
]*/

const movie = "title";
const a = {    // <--- error here, needs a line
  ab: "aa"
};
```

IMO, the purpose of the rule is to pad the code in order to group similar kinds of tokens. 

Let's hear from others, as I might be missing something.

**Comment by 185driver** [comment]
@anikethsaha I agree. What I'm proposing above misses the mark and shouldn't be done. On further reflection, I think the feature request I intended could more clearly be described as the addition of a `multiline-return` `STATEMENT_TYPE` to the `padding-line-between-statements`rule:
```
"multiline-return" is multiline `return` statements. This is the same as `return` type, but only if the statement is multiline.
```
This was my actual intent. I'm wondering if I should a) close this and open a new issue, b) edit this issue to match this new approach, or c) leave this issue as it is.

**Comment by anikethsaha** [comment]
if `multiline-return` is concerned, I think it can be doable. 

> This was my actual intent. I'm wondering if I should a) close this and open a new issue, b) edit this issue to match this new approach, or c) leave this issue as it is.

I think you can edit this issue with a detailed approach.

**Comment by 185driver** [comment]
Edited the issue to match my intent. Thank you for the feedback.
