### ISSUE TITLE
Inline comment option to warn instead of disable

### ISSUE THREAD

**Issue by markjackson02** [eslint/eslint#13264]
**The version of ESLint you are using.**
6.8.0

**The problem you want to solve.**
I have reviewed an eslint error and decided it should be a warning. Currently I do not see a way to override a line to set it to warning at the line level. It looks like currently the only options are either 1) override at the config level / file level, or 2) disable the rule completely on the line using `// eslint-disable-line [rule]`

**Your take on the correct solution to problem.**
Add inline comment options for `// eslint-warn [rule]`, `// eslint-warn-line [rule]`, `// eslint-warn-next-line [rule]`

**Are you willing to submit a pull request to implement this change?**
Potentially. Doesn't seem too difficult if most of the code for `eslint-disable` can be leveraged.

**Comment by anikethsaha** [comment]
I think this needs a [RFC](https://github.com/eslint/rfcs) as it belongs to the core 🤔

**Comment by kaicataldo** [comment]
I'm not sure I understand why you would want to do this - can you explain what problem this solves? We would also need to think about the API, because the relationship between `eslint-enable` and `eslint-warn` is not very clear. Also, if someone wanted to enable both rules as errors and rules as warnings, do they have to use two different types of directive comments?

Agreed that this should go through the RFC process, but it's also fine to get some initial feedback here.

**Comment by markjackson02** [comment]
@anikethsaha Thanks. I will plan on opening an RFC. I'll leave this open for conversation until I open the RFC.

@kaicataldo As an example of when I would use this: ESLint generates an error that is normally a quick fix, but the code is complex and I don't want to tackle refactoring it immediately. I don't want ESLint to generate an error for this line and therefore fail CI builds, nor do I want to use `// eslint-disable` and lose sight of the fact that it should be refactored. I reviewed the code and it is permissible for now. Right now, I can only "downgrade" an `error` to `warning` at the file level using overrides in `.eslintrc`. Why not have the same in-line functionality for downgrading `error` to `warning` as we have for downgrading `error`/`warning` to `off` with `// eslint-disable`?

**Comment by kaicataldo** [comment]
Thanks for the explanation. This seems like a valid use-case to me, though I think we'll want to really make sure the API is easy to use and clear. We already have a lot of directives, and it's already difficult for users to keep track of all of them.
