### ISSUE TITLE
[Suggestion] Allow paths to configs in 'package.json' key

### ISSUE THREAD

**Issue by davidbwaters** [eslint/eslint#13273]
Hi, when adding a config using the package.json eslintConfig key, it only allows objects.  It would be nice to have it try to resolve a path when it gets a string value.  It would keep the file cleaner and look consistent other popular project's conventions.

**Comment by anikethsaha** [comment]
Can you share a bit more about the structure and your eslint setup.

**Comment by davidbwaters** [comment]
Actually, this appears to work with eslint from the command line, but the eslint VSCode extension throws an error when the param is not an object, so maybe I should open an issue there.  ESLint 7.0.0 on Windows, NPM 6.14.4.
