### ISSUE TITLE
Don’t stub console.log

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#1328]
The [cli test](https://github.com/eslint/eslint/blob/976aac7a43e1def7140025e56469879224a48282/tests/lib/cli.js#L24-L25) stubs `console.log` and `console.error`. As mocha is using `console.log` in its reporters we probably don’t get some assertion errors printed to the console (see #1325).

I suggest to use `sinon.spy` instead.

**Comment by nzakas** [comment]
Following up on this - changing `console.log` to be spied on instead of stubbed means a lot of noise when testing the CLI. Probably need to think this through some more.

**Comment by glenjamin** [comment]
An option would be to add a layer of indirection for eslint log output that gets stubbed instead.

Alternatively, some mocha reporters always use `process.stdout.write` instead of `console.log`, so setting one of those to be the default might be good enough.
