### ISSUE TITLE
devdeps: leche has been deprecated

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#13287]
**The version of ESLint you are using.**
v7.0.0(latest)

**The problem you want to solve.**
https://github.com/box/leche#deprecated

> Box has migrated to using Jest and no longer uses mocha or leche. We no longer support changes, pull requests, or upgrades to this package.

**Your take on the correct solution to problem.**
do we want to switch to jest, or just find an alternative?

**Are you willing to submit a pull request to implement this change?**
y

**Comment by nzakas** [comment]
Switching to Jest doesn't make sense just to update this small dependency. I'm not sure we need to change anything if our tests are still working, but if we do want to change something, I'd just keep it local to the tests using the dependency.

**Comment by kaicataldo** [comment]
Agreed with @nzakas. We only use `leche` in a [handful of places](https://github.com/eslint/eslint/search?q=leche&unscoped_q=leche), and it looks like we use it for two purposes:

1. Creating mocks
2. Running the same test with multiple inputs/outputs

We should be able to replace it by:

1. Use Sinon for mocking (which we already do in the majority of tests)
2. Use native JS syntax

Example (based on [these tests](https://github.com/eslint/eslint/blob/bc435a93afd6ba4def1b53993ef7cf8220f3f070/tests/lib/source-code/source-code.js#L1794-L1830)):

```js

[
    ["let foo", true],
    ["let  foo", true],
    ["let /**/ foo", true],
    ["let/**/foo", false],
    ["let/*\n*/foo", false]
].forEach(([code, expected]) => {
    describe("when the first given is located before the second", () => {
        it(code, () => {
            const ast = espree.parse(code, DEFAULT_CONFIG),
                sourceCode = new SourceCode(code, ast);


            assert.strictEqual(
                sourceCode.isSpaceBetween(
                    sourceCode.ast.tokens[0],
                    sourceCode.ast.tokens[sourceCode.ast.tokens.length - 1]
                ),
                expected
            );
        });
    });
});
```

**Comment by nzakas** [comment]
To reopen this, we should have a plan for addressing it. If not, we should close it.

**Comment by aladdin-add** [comment]
Anyway, it is discouraged to keep using unmaintained packages. And [@kaicataldo 's comment](https://github.com/eslint/eslint/issues/13287#issuecomment-627941597) seems like a good direction. thoughts?

**Comment by nzakas** [comment]
I originally wrote leche, so I’m not very concerned about continuing to use it. @kaicataldo‘s suggestion is fine too. I just don’t want to leave this open without a plan.

**Comment by kaicataldo** [comment]
@aladdin-add Do you want to work on this? This could also be a good opportunity for a community contribution :)

**Comment by peanutenthusiast** [comment]
going to look into this

**Comment by nzakas** [comment]
Thanks @peanutenthusiast!
