### ISSUE TITLE
Settings object can't have keys that conflict with Object.prototype

### ISSUE THREAD

**Issue by edg2s** [eslint/eslint#13289]
**Tell us about your environment**

* **ESLint Version:** 7.0.0, 6.8.0, probably all others
* **Node Version:** any
* **npm Version:** any

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "settings": {
    "myPlugin": {
      "constructor": "val",
      "hasOwnProperty": "val",
      "isPrototypeOf": "val",
      "propertyIsEnumerable": "val",
      "toLocaleString": "val",
      "toString": "val",
      "valueOf": "val"
    }
  }
}

```

</details>

**What did you expect to happen?**
These settings are available to the plugin.

**What actually happened? Please include the actual, raw output from ESLint.**
All the settings are dropped, due to a crude key check in `mergeWithoutOverwrite`, which checks if the setting already exists using `target[key]!==undefined` instead of `Object.prototype.hasOwnProperty`.

**Are you willing to submit a pull request to fix this bug?**
Yes

This issue arises is https://github.com/gajus/eslint-plugin-jsdoc, where the `tagNamePreference` object expects a key of `constructor` to set the preference for `@constructor` tag in jsdoc. Downstream task is https://github.com/gajus/eslint-plugin-jsdoc/issues/537.

**Comment by anikethsaha** [comment]
I think `Object.prototype.hasOwnProperty` can be an easy win here. 

👍

**Comment by kaicataldo** [comment]
I haven't verified this yet, but if this is the case this definitely seems like something we should fix.

**Comment by edg2s** [comment]
I'm guessing you want to re-open this given the PR is active :)
