### ISSUE TITLE
Upgrade ignore to 5.x?

### ISSUE THREAD

**Issue by kaelzhang** [eslint/eslint#13294]
**The version of ESLint you are using.**

7.0.0

**The problem you want to solve.**

The latest eslint still uses `ignore@^4.0.6`, but the latest version of `ignore@5.1.3` solves many known issues.
- .gitignore(.eslintignore) rules should always check paths that are relative to some directory which is usually the base dir of .gitignore file or the root directory of a repo. ignore <= 5 actually DONT KNOWN whether a pathname should be ignored if it is an absolute path.
- and also improves perf
- fixes some windows issues.

For details, we could check [releases](https://github.com/kaelzhang/node-ignore/releases)

**Are you willing to submit a pull request to implement this change?**

I'd like to help.

I submit this issue in order to discuss the necessarity whether we should do an upgrade which might introduce quite a few changes.

**Comment by kaicataldo** [comment]
Upgrading to latest to take advantage of the things you listed above sounds great. Looking at the [migration docs](https://github.com/kaelzhang/node-ignore#upgrade-4x---5x), is it true that we could avoid it being a breaking change for our users by filtering out the invalid paths?

**Comment by mysticatea** [comment]
Currently, we allow relative paths to the parent (`../*`), so I think we need breaking changes to upgrade.

**Comment by kaelzhang** [comment]
> Currently, we allow relative paths to the parent (`../*`), so I think we need breaking changes to upgrade.

@mysticatea Those relative paths to the parent (../*) is defined in .eslintignore file or command-line arguments

**Comment by kaelzhang** [comment]
> Upgrading to latest to take advantage of the things you listed above sounds great. Looking at the [migration docs](https://github.com/kaelzhang/node-ignore#upgrade-4x---5x), is it true that we could avoid it being a breaking change for our users by filtering out the invalid paths?

I guess it is possible to make a smooth upgrade.

**Comment by metasean** [comment]
fwiw: The [ignore](https://github.com/kaelzhang/node-ignore) package is now up to [release](https://github.com/kaelzhang/node-ignore/releases) v.5.1.5

**Comment by bmish** [comment]
Reopening since should be able to upgrade this in the upcoming eslint v8 release: https://github.com/eslint/eslint/pull/14889
