### ISSUE TITLE
ESLint 7.0.0 showing v.6.8.0 with the 'eslint -v' command

### ISSUE THREAD

**Issue by AnneCHPostma** [eslint/eslint#13300]
**Tell us about your environment**

Node version: v13.11.0
npm version: v6.13.7
Local ESLint version: Not found
Global ESLint version: v6.8.0 (Currently used)

**What parser (default, Babel-ESLint, etc.) are you using?**
n/a

**Please show your full configuration:**
n/a

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Installed ESLint, using:
yarn global add eslint

Then tried to verify the version number, using:
eslint -v

**What did you expect to happen?**
I expected to see v7.0.0 returned

**What actually happened? Please include the actual, raw output from ESLint.**
I got back v.6.8.0

**Are you willing to submit a pull request to fix this bug?**
Sure

**Comment by ljharb** [comment]
What does `which eslint` say?

**Comment by AnneCHPostma** [comment]
> What does `which eslint` say?

I put it in the header and in the message .. how can this not be clear?
ESLint 7.0.0 showing v.6.8.0

**Comment by AnneCHPostma** [comment]
Never mind, it shows the proper version on a clean install on my laptop, so it is probably a glitch (local issue) on my Mac.
