### ISSUE TITLE
Bump: Add --ext mjs to default file extensions

### ISSUE THREAD

**Issue by cookiengineer** [eslint/eslint#13301]
This is the same issue as https://github.com/eslint/eslint/issues/9592 that was closed due to old age (and that the TSC, at the time, decided against its consideration).

1. Now we have 2020, and Browser Modules have shipped in all stable Browser channels, see https://caniuse.com/#feat=es6-module

2. All Browsers (meaning Firefox, Chromium, Edgium, Safari 12+ and all downstream forks, including WebKitGTK / QTWebKit) accept the `.mjs` ESM module file extension by default and expressively check against the `application/javascript` header for that specific file extension when being used as `<script type="module">` and it can be assumed that this is the defacto standard file extension for ESM modules now.

3. Node.js removed the `--experimental` flag in its stable release channel.

4. The IETF is working on an RFC to include `mjs` as the official file extension in the following Draft: https://tools.ietf.org/html/draft-ietf-dispatch-javascript-mjs-05

5. The Python language adapted `mjs` as the file extension for ESM modules: https://bugs.python.org/issue31715

6. Golang adapted `mjs` as the file extension for ESM modules: https://github.com/golang/go/issues/30547

Given the circumstances and the state that ESM modules are in, right now, and that `mjs` as a file extension was already pushed out on stable channels of above mentioned implementations - and considering the IETF effort that is put this into an RFC - I think it is safe to say that `mjs` will be the official file extension soon.

I hope that the file extension `mjs` can now be reconsidered to be included in the default file extensions that are linted by `eslint`.

**Paste the command you used to run ESLint:**
```bash
eslint --ext js,mjs ./*; # mjs should not be necessary
```

**What did you expect to happen?**
```bash
eslint ./*; # should behave the same way as above
```

**Are you willing to submit a pull request to fix this bug?**

Yes, of course.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

if I am not wrong, this might need `sourceType : module` by default then, 🤔 ?

**Comment by cookiengineer** [comment]
@anikethsaha Yep, `mjs` are the extension that forces node and the Browser into using `ESM` import syntax, whereas `js` files cannot use `import` and neither `export`.

**Comment by anikethsaha** [comment]
yes, it needs `ecmaVersion` to `2015` by default as well. (_breaking_)

This might need [RFC](https://github.com/eslint/rfcs) 

let's hear from others.
