### ISSUE TITLE
Enforce 2 (or more) lines not just one [lines-between-class-members]

### ISSUE THREAD

**Issue by seanpmaxwell** [eslint/eslint#13323]
**What rule do you want to change?**

[lines-between-class-members]

**Does this change cause the rule to produce more or fewer warnings?**

Possibly more.

**How will the change be implemented? (New option, new default behavior, etc.)?**

Modification to setting in eslint file.

```JSON
{
  "rules": {
    "lines-between-class-members": [true, 2], <--- This right here, enforces 2 lines
  },
  "rulesDirectory": [
    "node_modules/tslint-lines-between-class-members"
  ]
}
```

**Please provide some example code that this change will affect:**

```js
// Valid
    componentDidMount() {
        this._isMounted = true;
        this.getProjects();
        this.getPendingInvites();
    }

    
    componentWillUnmount() {
        this._isMounted = false;
    }

// Invalid

    componentDidMount() {
        this._isMounted = true;
        this.getProjects();
        this.getPendingInvites();
    }
    
   componentWillUnmount() {
        this._isMounted = false;
    }
```

**What does the rule currently do for this code?**

Can only be used to enforce 1 space between class members.

**What will the rule do after it's changed?**

Be able to enforce more than 1 space. Some people like to use 2 spaces.

**Are you willing to submit a pull request to implement this change?**

No I don't know how this works under the hood.

**Comment by yeonjuan** [comment]
Hi. @seanpmaxwell  
Thanks for the proposal.😁It seems to duplicate with this pr- #12663

**Comment by kaicataldo** [comment]
Can you expand on the configuration API? I don't currently see how it fits into the existing API. What does `true` mean, in this context? How would this be configured with the options object? Is this a no-op when the rule is set to "never"?

**Comment by seanpmaxwell** [comment]
Ideally I would like it to be configured just tslint-lines-between-class-members found here https://github.com/chinchiheather/tslint-lines-between-class-members#readme. So true means the rule is being enforced.

**Comment by IgorNovozhilov** [comment]
I also thought about this when I was working on PR #12663. But since the review of the changes took a long time, I left the idea with the revision for later.

**Comment by seanpmaxwell** [comment]
Would be awesome if implemented. tslint-lines-between-class-members is still growing in npm downloads so def would be useful to a lot of people if implemented.
