### ISSUE TITLE
ajv seems to be major contributor to performance slowdown

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#13324]
**The version of ESLint you are using.**
v7.0.0

**The problem you want to solve.**
ESLint is taking a pretty long time to run even on a single file (1.2s on a single file). After doing some high level performance profiling I found that ajv seems to be taking roughly about 5% of the execution time of the whole linting process (running current master branch on ./lib/linter/linter.js).
![image](https://user-images.githubusercontent.com/1380062/82278003-35adab80-9957-11ea-965a-78981699525c.png)
(ignore total execution time, I let profiler run a bit too long).

**Your take on the correct solution to problem.**
Not entirely sure, but ajv is doing very little other then validating JSON Schema, so it shouldn't be taking longer then indent rule (which is second biggest offender, or rather red-black-tree that indent depends on).

**Are you willing to submit a pull request to implement this change?**
Maybe.

**Comment by kaicataldo** [comment]
Thanks for reporting this! Marking as accepted since we would accept PRs to improve the performance. Ideally, we would be able to look into why `ajv` is taking so long and either make issues or create PRs to improve performance upstream.

**Comment by nzakas** [comment]
Folks, we should either come up with a plan to address this or close it. It looks like some investigation still needs to happen?

**Comment by nzakas** [comment]
Closing, as there is no plan to address this.
