### ISSUE TITLE
Remove deprecated rules from Rules Configuration tool

### ISSUE THREAD

**Issue by pubmikeb** [eslint/eslint#13348]
**The version of ESLint you are using.**
7.1.0

**The problem you want to solve.**
[Rules Configuration tool](https://eslint.org/demo) contains rules, which are deprecated already, e.g. `no-catch-shadow`.

**Your take on the correct solution to problem.**
To cleanup the list of rules and extract all deprecated rules into separate section in https://eslint.org/demo

**Are you willing to submit a pull request to implement this change?**
No

**Comment by anikethsaha** [comment]
Thanks for the issue.

IMO, a `deprecated` note/label next to their name can be done I guess.

**Comment by pubmikeb** [comment]
Where can I find a `deprecated` note/label? For instance, `callback-return` is deprecated, but I don't see  any label next to this rule on https://eslint.org/demo:

![24_085631](https://user-images.githubusercontent.com/17231333/82747734-83357880-9d9c-11ea-8fb7-9693813f9c49.png)

Any way, it would be great to have a separate subsection under Rules to be able enable/disable all deprecated rules at one click.

**Comment by anikethsaha** [comment]
> Where can I find a `deprecated` note/label?

it is not implemented as of now. I meant we can add like that

**Comment by pubmikeb** [comment]
> I meant we can add like that

I think label is good but not enough, ideally is to be able to switch on/off all deprecated rules with one single click.

**Comment by kaicataldo** [comment]
Can we take this discussion to the https://github.com/eslint/website repository? The demo can definitely use some love, and ideally will be entirely redesigned with the rest of the site in the future.

**Comment by pubmikeb** [comment]
@kaicataldo, yeah sure.
The key idea is to allow to get the ESLint config file with a set of supported rules only.
