### ISSUE TITLE
Lint (do not ignore) dot files by default

### ISSUE THREAD

**Issue by mightyiam** [eslint/eslint#13342]
Following up from #10341.

**The version of ESLint you are using.**

v6.8.0

**The problem you want to solve.**

ESLint ignores dot files by default. I don't see a reason for this behavior. One could wrongly assume that ESLint is linting their dot files (of which there may be many) when in fact no linting is occurring. And when one does find this out, it's just a waste of time figuring it out.

**Your take on the correct solution to problem.**

Just lint the dot files by default.

![download](https://user-images.githubusercontent.com/635591/82660353-668e2900-9c54-11ea-80b1-670e10b2f12f.jpeg)

**Are you willing to submit a pull request to implement this change?**

Nah.

**Comment by aladdin-add** [comment]
I'm in favor of the change. Just a reminder: eslint v7.0.0 starts linting `.eslintrc.js` (•_•)

**Comment by kaicataldo** [comment]
As mentioned [here](https://github.com/eslint/eslint/issues/10341#issuecomment-445313707), this is a breaking change in core and such requires an [RFC](https://github.com/eslint/rfcs). We would be happy to evaluate an RFC proposal.

**Comment by mightyiam** [comment]
https://github.com/eslint/rfcs/pull/55
