### ISSUE TITLE
max-len ignoreImports option

### ISSUE THREAD

**Issue by liesislukas** [eslint/eslint#13350]
Imports are OK to be longer then a normal code. It's often more "clean" and easier to read the code when all imports take one line each. Yet some imports's width is bigger than normal and it wraps. It destroys the beauty and that's... 😥😵

**What rule do you want to change?**
max-len

**Does this change cause the rule to produce more or fewer warnings?**
doesn't change with default but opt-in to show fewer warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
new option: ignoreImports

**Please provide some example code that this change will affect:**

```js
import {someVeryLongLoooooooongVariable as _someLocalVariable, anotherLoooooooooongVariable as anotherLocalVariable} from 'some-package';
```

**What does the rule currently do for this code?**
wraps to max-len

**What will the rule do after it's changed?**
with option ignoreImports:true would ignore all import lines

**Are you willing to submit a pull request to implement this change?**
maybe, but I guess it's a super easy to update for someone who is familiar with eslint plugin docs

**Comment by anikethsaha** [comment]
Thanks for the issue. 

may be [ignorePattern](https://eslint.org/docs/rules/max-len#ignorepattern) can be helpful here !

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbWF4LWxlbjogW1wiZXJyb3JcIiwgeyBcImlnbm9yZVBhdHRlcm5cIjogXCJpbXBvcnRcIiB9XSovXG5cbmltcG9ydCB7c29tZVZlcnlMb25nTG9vb29vb29vbmdWYXJpYWJsZSBhcyBfc29tZUxvY2FsVmFyaWFibGUsIGFub3RoZXJMb29vb29vb29vb25nVmFyaWFibGUgYXMgYW5vdGhlckxvY2FsVmFyaWFibGV9IGZyb20gJ3NvbWUtcGFja2FnZSc7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

> _the regex is not so solid, you can create a better regex for your use_

let me know if I am missing something

**Comment by liesislukas** [comment]
that's what i'm using at the moment, yet imports is popular thing to have in code so maybe it would make sense to have a flag to ignore those?

**Comment by anikethsaha** [comment]
> yet imports are a popular thing to have in code so maybe it would make sense to have a flag to ignore those?

Sorry if I am not understanding this, can you give some example/case where `ignorePattern` won't solve your issue ?

**Comment by liesislukas** [comment]
it does, yet we still have ignoreUrls and other pre-defined options

**Comment by anikethsaha** [comment]
`ignoreUrls` may be implemented because ( may be I can be wrong ) regex for URLs are bit complicated so it can be easy to have a general regex that can be used via an option.

yes it can be done via the same option as well.
