### ISSUE TITLE
Plugins not being loaded relative to the configs that reference them

### ISSUE THREAD

**Issue by richardkazuomiller** [eslint/eslint#13364]
ESLint version: 7.1.0
Node version: 12.16.3
npm Version: 6.14.4

---

I have two configuration files. One is in a npm package and the other extends it.

`@my-org/eslint-config/typescript/index.js`: 

```
module.exports = {
  plugins: [
    '@typescript-eslint'
  ],
  // ... other config
};
```

`.eslintrc.js`: 

```
module.exports = {
  extends: [
    "@my-org/eslint-config/typescript"
  ],
  // ...other config
}
```

I get the following error when running ESlint:

```
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/Users/richard.miller/srv/sn-covid19-static".)
```

The documentation says:

```
In v7.0.0, plugins will be loaded relative to the configs that reference them.
```

but it seems that plugins are loaded from whatever directy the root config is in. How do I get the plugin to be loaded from the config that references it?

**Comment by aladdin-add** [comment]
does the [`--resolve-plugins-relative-to`](https://eslint.org/docs/user-guide/command-line-interface#resolve-plugins-relative-to) help?
also, please make sure you have installed `@typescript-eslint/eslint-plugin`. :)

**Comment by richardkazuomiller** [comment]
I'm aware of that option but it's not clear that I need it based on the documentation. I thought v7 resolved plugins relative to the configuration file that references them. `@typescript-eslint/eslint-plugin` is installed in `@my-org/eslint-config` but it only gets loaded if it is installed to the project that extends the configuration

**Comment by brandon-leapyear** [comment]
@richardkazuomiller According to [this section](https://eslint.org/docs/user-guide/configuring#configuring-plugins):

> Plugins in the base configuration (loaded by extends setting) are relative to the derived config file. For example, if ./.eslintrc has extends: ["foo"] and the eslint-config-foo has plugins: ["bar"], ESLint finds the eslint-plugin-bar from ./node_modules/ (rather than ./node_modules/eslint-config-foo/node_modules/) or ancestor directories. Thus every plugin in the config file and base configurations is resolved uniquely.
