### ISSUE TITLE
Support "ignorePath" as top level configuration setting

### ISSUE THREAD

**Issue by medikoo** [eslint/eslint#13361]
Currently the only way to use alternate ignore file is to pass `--ignore-path` into CLI, and that's quite limited as it doesn't ensure that desired _ignore file_ is respected by default in every lint check for given project. 

That affects IDE configurations. e.g.  on my side in most of the projects I want ESLint by default to treat `.gitignore` as _ignore file_, for that I have _lint_ scripts configured as `eslint --ignore-file=.gitignore .`, but that's not picked by VSCode ESLint extension, which anyway doesn't want to lint files that start with a `.` which are otherwise linted by _lint_ scripts.

**Comment by mysticatea** [comment]
Thank you for your request.

You can do like below:

```js
// .eslintrc.js
const fs = require("fs")

module.exports = {
    ignorePatterns: fs.readFileSync(".gitignore", "utf8").split("\n").filter(Boolean),
    // other settings.
}
```

**Comment by medikoo** [comment]
@mysticatea thanks, that indeed works as workaround. Still it'll be nice to be able to achieve without a need of JS file configuration or copying a settings

**Comment by aleclarson** [comment]
+1

**Comment by nzakas** [comment]
To close the loop here: we aren't making any further changes to the configuration system. We are working on a new configuration system (defined in eslint/rfcs#9) and there will be more options for specifying ignore files.
