### ISSUE TITLE
Lines between variable/property/any assignments

### ISSUE THREAD

**Issue by seahindeniz** [eslint/eslint#13378]
**What rule do you want to change?**
padding-line-between-statements

**Does this change cause the rule to produce more or fewer warnings?**
Less and more warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option

**Please provide some example code that this change will affect:**

```jsx
constructor() {
  this.a = 1;
  this.b = 2; // Expect new line after this assignment
  this.method();
}
method(){
  let c = 3;

  if(this.a === 1){
    c = 4; // Expect new line after this assignment
    console.log(c);
  }
}
```

**What does the rule currently do for this code?**
It doesn't have any configuration for variable or property assignments

**What will the rule do after it's changed?**

```jsx
constructor() {
  this.a = 1;
  this.b = 2;

  this.method();
}
method(){
  let c = 3;

  if(this.a === 1){
    c = 4;

    console.log(c);
  }
}
```

**Are you willing to submit a pull request to implement this change?**
Not right now but if it's needed, I can.

**Comment by anikethsaha** [comment]
Thanks for the issue.

IMO, having a `call` expression for statement type in the options might solve this issue.
I couldn't find any `STATEMENT_TYPE` for that or similar. (may I missed something.)

like this.

```js
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: "expression", next: "call" } // call or similar is not available as of now. 
]*/

class Cla {
  constructor() {
    this.a = 1;
    this.b = 2; // Expect new line after this assignment
    this.method();
  }
  method() {
    let c = 3;

    if (this.a === 1) {
      c = 4; // Expect new line after this assignment
      console.log(c);
    }
  }
}
```

**Comment by seahindeniz** [comment]
I think an expression is not an assignment and can be referred to this usage:
```jsx
window.alert; // No call or assign, just expression
```
The `no-unused-expressions` rule will be going to complain about the express usage. So I think the `prev: "expression"` config will not be a good approach here.

Allow me to provide some possible more stricted examples
```jsx
/*eslint padding-line-between-statements: [
    "error",
    { blankLine: "always", prev: ["const", "let", "var"], next: "*"},
    { blankLine: "any",    prev: ["const", "let", "var"], next: ["const", "let", "var"]}
]*/
function() {
  this.a = 1;
  this.b = 2; // A new STATEMENT_TYPE to override the requirement for a blank line after this
  const c = 3;
}
```
```jsx
function() {
  this.a = 1;
  this.b = 2; // Expect new line after this assignment
  return true; // Can also be achieved with { "blankLine": "always", "prev": "*", "next": "return" }
}
```
```jsx
function() {
  this.a = 1;
  this.b = 2; // Expect new line after this assignment
  if(this.a === 1) return;
}
```
```jsx
function() {
  this.a = 1;
  this.b = 2; // Expect new line after this assignment
  if(this.a === 1) {
    this.a = 3; // Expect new line after this assignment
    return;
  }
}
```
```jsx
function() {
  this.a = 1;
  this.b = 2; // Expect new line after this assignment
  console.log(this.a);
}
```

**Comment by kaicataldo** [comment]
Since the API of stylistic rules are now frozen (please see [here](https://eslint.org/blog/2020/05/changes-to-rules-policies) for more details), we won't be able to accept this proposal. Thanks for wanting to help improve the project!

**Comment by seahindeniz** [comment]
Hi @kaicataldo 
As far as I understand, we can't ask for new rules. Which is sad and acceptable due to number of rules. 
But I think the issue is about adding a new statement type, not a different kind of stylistic rule that is going to increase the current number of rules. The rule that is related to this issue already exists :slightly_frowning_face:

**Comment by kaicataldo** [comment]
Thanks for your understanding. This proposal would fall under this category:

> **Stylistic rules are frozen** - we won't be adding any more options to stylistic rules. We've learned that there's no way to satisfy everyone's personal preferences, and most of the rules already have a lot of difficult-to-understand options. Stylistic rules are those related to spacing, conventions, and generally anything that does not highlight an error or a better way to do something.

**Comment by kaicataldo** [comment]
I'm going to go ahead and close this, but we appreciate your willingness to contribute, regardless!
