### ISSUE TITLE
prefer-destructuring maxIndex option

### ISSUE THREAD

**Issue by nickofthyme** [eslint/eslint#13382]
**What rule do you want to change?**
[`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring)

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option to add to second options with `enforceForRenamedProperties`, something like `maxIndex`.

**Please provide some example code that this change will affect:**
When accessing indexes on arrays that are relatively large (>10), there is a point of diminishing return where destructuring the array becomes more and more impractical.

This idea is mentioned in the docs [here](https://eslint.org/docs/rules/prefer-destructuring#when-not-to-use-it) on the extreme side where the index is `100`. But there is no recourse for this scenario other than to ignore or disable the rule. But with this change, people will be able to address this scenario to their liking.

```js
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const previous = data[7];
const current = data[8];
const next = data[9];
```

which fixing this would look something like...

```js
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const [,,,,,, previous, current, next] = data;
```

This to me is nice because of the chained index values but the preceding commas required to access large indices can get unruly and negate readability, on the order of `20` or `50` let alone `100`.

**What does the rule currently do for this code?**
```js
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const previous = data[7]; // <-- errors on prefer-destructuring
const current = data[8]; // <-- errors on prefer-destructuring
const next = data[9]; // <-- errors on prefer-destructuring
```

**What will the rule do after it's changed?**
For a example rule configuration like this

```json
{
  "rules": {
    "prefer-destructuring": ["error", {
      "array": true,
      "object": true
    }, {
      "maxIndex": 8
    }]
  }
}
```

```js
const data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const previous = data[7]; // <-- error becasue 7 <= 8
const current = data[8]; // <-- error becasue 8 <= 8
const next = data[9]; // <-- no error because 9 > 8
```

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by anikethsaha** [comment]
Thanks for the issue, 

Though I have never seen any code which accesses a long index, if it does so,  this seems good enhancement.

**Comment by nickofthyme** [comment]
Yeah, I guess you're right, it may be seldomly seen. I only came across it accessing mock data for jest tests.

**Comment by yeonjuan** [comment]
Hi :) @nickofthyme 
I'll mark it as "evaluating" since it needs the [consensus](https://eslint.org/docs/maintainer-guide/issues#consensus) of the team members.

I do not strongly disagree with this option.
but IMO, directly accessing array by large literal index seems quite a unique case where [eslint-disable comment](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments) can be used.

**Comment by nickofthyme** [comment]
@yeonjuan Thanks for the update. Sounds good, I'm in no hurry 👍.

**Comment by kaicataldo** [comment]
The team has made the difficult decision to freeze stylistic rules (please see https://eslint.org/blog/2020/05/changes-to-rules-policies for more details), and we unfortunately won't be able to accept this proposal.

The good news is that this should be fairly easy to enforce by creating a custom rule using [eslint-rule-composer](https://www.npmjs.com/package/eslint-rule-composer)!

Thanks for contributing to ESLint and for being willing to implement your proposal.

**Comment by yeonjuan** [comment]
@kaicataldo oops. Sorry for mislabeling

**Comment by anikethsaha** [comment]
it is a stylistic rule indeed. in rule's meta it is written as [`ECMAScript 6`](https://github.com/eslint/eslint/blob/master/lib/rules/prefer-destructuring.js#L17)

Shouldnt this be `Stylistic Issues`?

**Comment by nickofthyme** [comment]
No worries, Thanks @anikethsaha, @yeonjuan and @kaicataldo for the consideration. I think I might just start my own custom plugin to expand my personal preferences on top of all the amazing work y'all are doing.

Just for clarity, how do you define a _stylistic rule_?

**Comment by kaicataldo** [comment]
@anikethsaha Can you clarify what you mean? Not sure I understand.

@nickofthyme Thanks for your understanding. ESLint was intended to have a very small core rule set with the idea that folks could make their own rules to enforce whatever they would like to!

Stylistic rules are ones that don't warn about a potential problem. As an example, this rule enforces a preference rather something that might cause incorrect behavior.

**Comment by anikethsaha** [comment]
@kaicataldo [this](https://github.com/eslint/eslint/blob/master/lib/rules/prefer-destructuring.js#L17) should be `Stylistic Issues` right ?

**Comment by kaicataldo** [comment]
I do think we should get rid of the ECMAScript 6 category, but since it exists, I think this is correctly categorized.

**Comment by anikethsaha** [comment]
sorry if I am not understanding, but this rule is a stylistic rule right ? so the category should be same ?

**Comment by kaicataldo** [comment]
We also have the ECMAScript 6 category, and so this could fit in either (it looks like we have other ES2015 syntax-specific rules in the stylistic section). For consistency and ease of understanding, I do think it would be better to get rid of the ECMAScript 6 category and move all those rules into the other, more descriptive categories. If you'd like to make an issue for that, feel free!

**Comment by anikethsaha** [comment]
ahh, I see. 

yea I will make an issue soon.
