### ISSUE TITLE
Respect .gitignore files by default?

### ISSUE THREAD

**Issue by borekb** [eslint/eslint#13389]
#### Current situation

ESLint has several features around ignoring things, e.g.:

- `.eslintignore`
- some built-in rules like ignoring `node_modules` automatically (this changes over time, see e.g. [7.0.0 release notes](https://eslint.org/blog/2020/05/eslint-v7.0.0-released))
- `ignorePatterns` in config files
- `--ignore-path`

Still, it's currently quite hard to configure ignore rules correctly in a larger repo, without the setup being sort of duplicate/fragile. For example, in our monorepo, we have several subfolders, each with its own `.gitignore` file, and to replicate the correct ignoring behavior means duplicating ignore paths in the root `.eslintignore` file.

#### Previous discussions about `.gitignore` support

There have been issues around `.gitignore` support in the past, e.g.:

- Use .gitignore by default if no .eslintignore is found #5848
- Fallback to using `.gitignore` when `.eslintignore` doesn't exist #12199

Some arguments against it were that ESLint should have its own mechanism independent on other systems, that it would add magic behavior, that it's a breaking change or that you can usually find some workaround like building `config.ignorePatterns` in code.

I sort of agree with all of that, or at least see the point, but as a regular user of [ripgrep](https://github.com/BurntSushi/ripgrep) or [fd](https://github.com/sharkdp/fd) I have to say that I see no practical downside of respecting `.gitignore` by default – in fact, it's a beautiful usability feature.

#### Worth an RFC?

I realize these things should go through the RFC process and I'm willing to do it but first I wanted to discuss this in an issue (that is not locked; otherwise, this is quite relevant: #12199). 

What do you think about this? Am I missing some major downsides?

The biggest counter-argument, IMO, is that some files that were linted before would not be linted after this. To that, I'd say:

1. I'm not sure how common is linting e.g. `dist/**.js` files. My guess would be that it's very rare but I acknowledge that it can happen.
2. These kinds of breaking changes are already happening, for example, with v6, someone could be linting `subdir/node_modules` which stopped working in v7.

It's also possible to add this to ESLint in a non-breaking way, behind some new flag like `--ignore-strategy=gitignore` (this is different from `--ignore-path`, even if it supported multiple paths – #9794).

I generally think that the new behavior would be useful for most projects using ESLint (like the vast majority; "99%") without many downsides. What do you think?

**Comment by borekb** [comment]
Similar Prettier proposal: https://github.com/prettier/prettier/issues/4081.

**Comment by kaicataldo** [comment]
You can always feel free to create another RFC, but for some more context, this was recently discussed in [this RFC](https://github.com/eslint/rfcs/pull/9#issuecomment-636955833).

**Comment by borekb** [comment]
@kaicataldo Thank you, I even saw that RFC but missed that it also discusses `.gitignore`. There are probably many other things that that RFC tackles but I'll post my comment there anyway. Thanks again.

**Comment by borekb** [comment]
That RFC actually feels like a great place to discuss this as it aims to replace `.eslintignore`. I'll close this one.

**Comment by borekb** [comment]
As eslint/rfcs#9 will not be dealing with `.gitignore` after all – see [this comment](https://github.com/eslint/rfcs/pull/9#issuecomment-640752373) and commit https://github.com/eslint/rfcs/pull/9/commits/e68e6a016c52df91fd601a8692774704bc7ca870 – I'm reopening this issue.

Nothing really new to add, just that I'd love to see gitignore being honored by default 😄.

**Comment by kaicataldo** [comment]
Please feel free to create an RFC.

**Comment by mysticatea** [comment]
For a workaround for right now, I have released [eslint-gitignore](https://github.com/mysticatea/eslint-gitignore) package as we can convert `.gitignore` files to our `ignorePatterns` option.

For example:

```js
// .eslintrc.js
const { readGitignoreFiles } = require("eslint-gitignore")

module.exports = {
  // Your config.

  ignorePatterns: readGitignoreFiles({ cwd: __dirname })
};
```

---

My thoughts:

- It's worth that we consider this feature because we have heard this request frequently.
- We can implement it by a utility package like `eslint-gitignore` in userland, but if ESLint reads it while traversing directories, it will improve performance. Because `.gitignore` files can be in subdirectories.
- Fallback to `.gitignore` is nice, but:
    - we should be able to override it by our config files (`.eslintignore` / `.eslintrc.*` / `eslint.config.js`). For example, I have often `/test.*` in `.gitignore` to play something, but I want to lint it.
    - we should support `.eslintignore` in subdirectories to be consistent. So both `.gitignore` and `.eslintignore` should behave samely.
    - Should we support other patterns of `.gitignore`? For example, `$GIT_DIR/info/exclude`, `core.excludesFile` setting of git, and `~/.gitignore`? It will bring complex...
- I'm not a fan of new options for this because we have a lot of options.

**Comment by borekb** [comment]
@mysticatea Wow, that is a nice package! I'll give it a go next week.

I agree that ESLint config files should still be able to override gitignore rules, similarly to how `.rgignore` can override `.gitignore` in ripgrep. Generally, I think that a lot of inspiration can be drawn from [how ripgrep ignores files](https://github.com/BurntSushi/ripgrep/blob/a16bfcb3d695d1d1158b20253806945581f80c80/doc/rg.1.txt.tpl#L129-L158) – it has a very good UX, in my opinion.
