### ISSUE TITLE
prefer-destructuring after delcaration

### ISSUE THREAD

**Issue by nickofthyme** [eslint/eslint#13381]
**What rule do you want to change?**
[`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring)

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New behavior

**Please provide some example code that this change will affect:**
When a variable (`color`), is declared prior to redeclaring with a value accessed from a property on an object (`spec`). This has no nice solution, other than refactoring the code to not mutate the `color` variable.

```js
let color;

if (spec.color ) {
  color = spec.color;
} else {
  color = 'blue';
}
```

**What does the rule currently do for this code?**
```js
let color;

if (spec.color ) {
  color = spec.color; // <-- errors on prefer-destructuring
} else {
  color = 'blue';
}
```

> Note: this would not error is the predefined variable and the target object property key were different (e.g. `finalColor = spec.color`).

**What will the rule do after it's changed?**
```js
let color;

if (spec.color ) {
  color = spec.color; // <-- not error on prefer-destructuring for previously defined variable
} else {
  color = 'blue';
}
```

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by yeonjuan** [comment]
@nickofthyme 
Hi :) Maybe [`AssignmentExpression` option](https://eslint.org/docs/rules/prefer-destructuring#options) is helpful to you
* [online-demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1kZXN0cnVjdHVyaW5nOiBbXCJlcnJvclwiLCB7QXNzaWdubWVudEV4cHJlc3Npb246IHsgYXJyYXk6IHRydWUsIG9iamVjdDogZmFsc2UgfX1dICovXG5cbmxldCBjb2xvcjtcbmlmIChzcGVjLmNvbG9yICkge1xuICAgY29sb3IgPSBzcGVjLmNvbG9yOyAvLyA8LS0gbm8gZXJyb3Jcbn0gZWxzZSB7XG4gIGNvbG9yID0gJ2JsdWUnO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)
```js
/* eslint prefer-destructuring: ["error", {AssignmentExpression: { array: true, object: false }}] */

let color;
if (spec.color ) {
   color = spec.color; // <-- no error
} else {
  color = 'blue';
}
```

>  This has no nice solution, other than refactoring the code to not mutate the color variable.

And maybe there is a solution if I understand the situation properly

```js
let color;

if (spec.color ) {
  ({color} = spec);
} else {
  color = 'blue';
}
```

**Comment by yeonjuan** [comment]
I'll mark it as a "question" since it seems already support the proposal. If I miss something, please leave a comment.

**Comment by nickofthyme** [comment]
Hey @yeonjuan, thanks for the comments.

Ideally, I would like to avoid disabling object `AssignmentExpression` just for this case. But if you think this is not an enhancement, that is fine with me.

You are right about the `({ color }) = spec)` I didn't think about that, ugly but it works. 👍

**Comment by kaicataldo** [comment]
FWIW, I think this rule shouldn't exist at all. There are times when member access is clearer than destructuring, and vice versa, and always enforcing one or the other, while consistent, leads to harder-to-read code, in my opinion.
