### ISSUE TITLE
Add `maxWarnings` as a configuration option

### ISSUE THREAD

**Issue by hbergren** [eslint/eslint#13391]
**The version of ESLint you are using.**
`7.1.0`

**The problem you want to solve.**
I want to be able to set `maxWarnings` property in a `.eslintrc.js` file, and not just on the command line.

**Your take on the correct solution to problem.**
`reportUnusedDisableDirectives` can be set in the configuration file or as a command line option. I think `maxWarnings` should be handled the same way.

**Are you willing to submit a pull request to implement this change?**
Yes, given some guidance.

**Comment by kaicataldo** [comment]
I think we should hold off on making any more changes to the existing configuration system until after we finalize and implement https://github.com/eslint/rfcs/pull/9. Once that's done, we'll be able to better evaluate what our needs are.
