### ISSUE TITLE
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser

### ISSUE THREAD

**Issue by smollweide** [eslint/eslint#13393]
**Tell us about your environment**

* **ESLint Version: 7.1.0**
* **Node Version: 12.16.3**
* **npm Version: 6.14.4**

**What parser (default, Babel-ESLint, etc.) are you using?**
@typescript-eslint/parser and babel-eslint

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

it's a monorepo with this structure:

```
- .eslintrc.js
--- packages
----- graphql
------- .eslintrc.js
```

idea is:
* js files are config files => node.js rules
* ts files are clintside code with react
* if serverside package => ts file will be linted with node.js + security rules by adding a `.eslintrc.js`

<details>
<summary>./eslintrc.js</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  rules: {
    ...
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      plugins: ['@typescript-eslint', 'jsx-a11y', 'react'],
      parser: '@typescript-eslint/parser',
      rules: {
        ...
      },
      settings: {
        react: {
          version: '16',
        },
      },
    },
  ],
};
```

</details>

<details>
<summary>./packages/graphql/eslintrc.js</summary>

```js
module.exports = {
  plugins: ['@typescript-eslint', 'security'],
  parser: '@typescript-eslint/parser',
  rules: {
    ...
  },
};

```

</details>

command in root is:
`eslint . --ext .jsx,.js,.ts,.tsx`

issue happens when upgrading from `6.8.0` to `7.1.0`.
Maybe it's not a bug but do you may have a hint what could be the problem?

**What actually happened? Please include the actual, raw output from ESLint.**
```
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/graphql/.eslintrc.js.
The file must be included in at least one of the projects provided
```

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by kaicataldo** [comment]
It seems like this might be an issue with `@typescript-eslint`. Have you tried making an issue in that repository?

**Comment by smollweide** [comment]
Hi @kaicataldo,
thanks for the fast response.
It happens when updating from eslint `6.8.0` to `7.1.0`. `@typescript-eslint` stays in the same version. That's why I created it here. I will test it with the newest @typescript-eslint.

**Comment by smollweide** [comment]
The update of typescript-eslitn didn't solved the issue.
But there is a workaround:

```js
module.exports = {
  parser: 'babel-eslint',
  rules: {
    ...
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      plugins: ['@typescript-eslint', 'jsx-a11y', 'react'],
      parser: '@typescript-eslint/parser',
      rules: {
        ...
      },
      settings: {
        react: {
          version: '16',
        },
      },
    },
    {
      files: ['packages/graph-ql/**/*.ts', 'packages/graph-ql/**/*.tsx'],
      plugins: ['@typescript-eslint', 'security'],
      parser: '@typescript-eslint/parser',
      rules: {
        ...
      },
    },
  ],
};
```
