### ISSUE TITLE
Distinguish between formatting and code-quality rules

### ISSUE THREAD

**Issue by pubmikeb** [eslint/eslint#13397]
**The version of ESLint you are using.**
7.2.0

**The problem you want to solve.**
Following the issue https://github.com/eslint/eslint/issues/13348, currently [Rules Configuration tool](https://eslint.org/demo) contains a long mixed list of rules, which contains both formatting and code-quality rules all together. 

**Your take on the correct solution to problem.**
It's better to separate these rules into two categories:
* formatting rules
* code-quality rules

This will simplify the rules management and housekeeping, and will allow easily to delegate code-quality linting to ESLint and rely on Prettier for formatting tasks.

**Are you willing to submit a pull request to implement this change?**
No.

**Comment by kaicataldo** [comment]
Agreed that the demo could use a lot of love. Could you make this issue in https://github.com/eslint/website, since that's where this code lives?

**Comment by pubmikeb** [comment]
Done: https://github.com/eslint/website/issues/736

**Comment by kaicataldo** [comment]
Thanks! I'll go ahead and close this in favor of the other issue.

> Perhaps, it worths to mention https://github.com/eslint/website for the website related issues in the Issue Creation Wizard?

Great idea!
