### ISSUE TITLE
Search for `.eslintignore` from target files in parent directories

### ISSUE THREAD

**Issue by devsnek** [eslint/eslint#13402]
See https://github.com/eslint/eslint/issues/6727

**The version of ESLint you are using.**

v6.8.0

**The problem you want to solve.**

running `eslint a/b/c/` when the `.eslintignore` file is in `a/b/` does not work correctly because eslint only looks for `.eslintignore` in the cwd.

**Your take on the correct solution to problem.**

The `.eslintignore` file should be looked for recursively upwards from whatever the target file is.

**Are you willing to submit a pull request to implement this change?**

Assuming this doesn't require a deep expert knowledge of eslint internals, yes

**Comment by kaicataldo** [comment]
Have you tried using [`--ignore-path`](https://eslint.org/docs/user-guide/command-line-interface#ignore-path)? If so, do you mind expanding on why this solution isn't adequate for your use case?

**Comment by devsnek** [comment]
@kaicataldo my editor picks up global eslint in cases where a local one isn't available (vim ale). i suppose i could teach ale how to understand eslint's configuration lookup behaviour, but that feels like the wrong abstraction to me.
