### ISSUE TITLE
使用ts的public属性后，报语法错误

### ISSUE THREAD

**Issue by vueProgrammer** [eslint/eslint#13406]
在vue项目中添加ts之后，使用public属性后，报语法错误，其余语法均没有错误
`public $refs!: {
        choose: Choose,
        list: Element
    }`
`Parsing error: Unexpected token

  34 | })
  35 | export default class carList extends newVue {
> 36 |     public $refs!: {
     |            ^
  37 |         choose: Choose,
  38 |         list: Element
  39 |     }eslint`
还望各位大佬帮忙看下，下面是eslint的配置
`module.exports = {
    // "parser": "babel-eslint",
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "168"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        // "allowImportExportEverywhere": false,
        // "codeFrame": true,
        "ecmaFeatures": {
            "legacyDecorators": true
        }
    },
    "plugins": [
        "vue"
    ],
    "rules": {
        "no-new":0
    }
};`

**Comment by aladdin-add** [comment]
eslint 本身不支持 ts/vue 的语法，如果需要，请参照 https://github.com/typescript-eslint/typescript-eslint 或者 vue 的官方文档进行配置。

**Comment by vueProgrammer** [comment]
感谢各位的回答，我已经解决了该问题
