### ISSUE TITLE
Codespell report for "ESLint" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [eslint/eslint#13428]
Also a lint tool would like to be linted someday itself (even if it's just a spell check):

The FOSS server [fossies.org](https://fossies.org) - supporting also "ESLint" - offers among others a feature "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies admin I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the new "ESLint" release 7.3.0:

&nbsp;&nbsp;&nbsp;&nbsp;https://fossies.org/linux/www/eslint/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available).

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/www/eslint/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/www/eslint/codespell_fps.html) and an [misspelling history](https://fossies.org/linux//www/eslint/codespell_hist.html) (log).

Although only few spelling errors or typos were found (some even ambiguous) and  their correction has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

**Comment by kaicataldo** [comment]
@jschleus Thanks! PRs to improve documentation are always welcome :)

**Comment by jschleus** [comment]
@kaicataldo   Unfortunately, in principle I don't make such corrections myself.

Just quoting  "[Source code misspelling reports](https://fossies.org/features.html#codespell)":

> A note: Fossies provides as an information only the source code spelling check reports with the special option to inspect the context of the probably misspelled words in a fast and comfortable way. However Fossies doesn't create for e.g. "diff"-like files usable by the "patch" command or even GitHub pull requests (PRs) since the risk is too high that something would be wrongly corrected (but here you may find some small codespell usage_hints. Whether it's worth the effort to correct the misspelling errors manually is a decision of the respective project.

If  manual corrections are out of the question the file [codespell.eslint-7.3.1.txt](https://fossies.org/linux/www/eslint-7.3.1.tar.gz/codespell.eslint-7.3.1.txt) may be helpful (linked via the word "list" above the full spelling errors table within Fossies maln [ESLint codespell report page](https://fossies.org/linux/www/eslint/codespell.html)). That file listing all the suggested corrections (incl . line numbers) could be adapted to make the suggestions unique and then used by a simple (to be written) script and e.g. "sed" to make all the changes within a cloned source directory.

For more general solutions see e.g. the two small Fossies [codespell usage hints](https://fossies.org/codespell_usage_hints.html).

Otherwise, since there are no really "harmful" misspellings, the issue can just be closed.
