### ISSUE TITLE
Breaking `eslint --init`

### ISSUE THREAD

**Issue by mujib2953** [eslint/eslint#13423]
**Tell us about your environment**
I am using Windows 10. And trying to add **eslint** in my customized react application( Customized means, not used `create-react-app` to create application instead of that add all packages manually )

* **ESLint Version: 7.2.0**
* **Node Version: 8.12.0**
* **npm Version: 6.14.5**

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I just installed **eslint** and **eslint-react-plugin** package to my dev-dependency. 
And then using
`eslint --init` 
command I am expecting eslint will be setup for me in the application as mentioned in documentation.

**What did you expect to happen?**
As per documents after init command **.eslintrc** configuration file will be created.

**What actually happened? Please include the actual, raw output from ESLint.**
Instead of there are errors on the command window, please see the attached the sceen-shot.
![eslint_issue](https://user-images.githubusercontent.com/17664474/85022919-9bc56280-b191-11ea-8105-297a2c9e9e5b.PNG)

**Are you willing to submit a pull request to fix this bug?**
IDK, I could try :)

**Comment by anikethsaha** [comment]
Can you share your node version ?

**Comment by mujib2953** [comment]
I can't update my node version due to project restriction.

**Comment by anikethsaha** [comment]
> Do I need to downgrade eslint?

I cant think of any other workaround other than downgrading, 

lets see if others have any things to suggest.

**Comment by mdjermanovic** [comment]
@mujib2953 thanks for the issue!

Starting from ESLint v7.0.0, [Node.js 8 is no longer supported](https://eslint.org/docs/user-guide/migrating-to-7.0.0#node-js-8-is-no-longer-supported).

Supported Node versions are: 

https://github.com/eslint/eslint/blob/d98152a3d8c72e4f5ac4c6fa10a615b12090c8f7/package.json#L143-L145

**Comment by kaicataldo** [comment]
Closing this issue since the question has been answered.
