### ISSUE TITLE
Indent rule - offsetTernaryExpressions seems not working on ConditionalExpression second branch

### ISSUE THREAD

**Issue by waivital** [eslint/eslint#13425]
**Tell us about your environment**

* **ESLint Version:** v7.2.0
* **Node Version:** v12.18.0
* **npm Version:** v6.14.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "es2020": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 11,
        "sourceType": "module"
    },
    "rules": {
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Demo Link](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgaW5kZW50OiBbXCJlcnJvclwiLCAyLCB7IFwib2Zmc2V0VGVybmFyeUV4cHJlc3Npb25zXCI6IHRydWUgfV0qL1xuXG5jb25zdCB0ZXN0ID0gKGEsIGIpID0+IHtcbiAgY29uc3QgcmVzdWx0ID0gYVxuICAgID8gYSh7XG4gICAgICAgIGE6IDFcbiAgICAgIH0pXG4gICAgOiBiKHtcbiAgICAgICAgYTogMVxuICAgICAgfSlcbiAgcmV0dXJuIHJlc3VsdDtcbn07XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImluZGVudCI6Mn0sImVudiI6e319fQ==)

```js
/*eslint indent: ["error", 2, { "offsetTernaryExpressions": true }]*/

export const test = (a, b) => {
  const result = a
    ? a({
        a: 1
      })
    : b({
        a: 1
      })
  return result;
};
```

```bash
./node_modules/.bin/eslint test.js
```

**What did you expect to happen?**
Expected to not receive any errors

**What actually happened? Please include the actual, raw output from ESLint.**

```
   9:1  error  Expected indentation of 6 spaces but found 8  indent
  10:1  error  Expected indentation of 4 spaces but found 6  indent
```

**Are you willing to submit a pull request to fix this bug?**
I don't have a fix at the moment

**Comment by kaicataldo** [comment]
This does seem like a bug to me.
