### ISSUE TITLE
Baseline option to report only new warnings

### ISSUE THREAD

**Issue by Serchinastico** [eslint/eslint#13437]
**The version of ESLint you are using.**

7.3.1

**The problem you want to solve.**

I want to add new rules to my project, which exists from a long time ago. If I just add the new rule I have to either fix all the violations of the new rule or add a lot of `/* eslint-disable */` directives. This causes a lot of noise for projects with many collaborators and, most probably, undesirable merge conflicts.

**Your take on the correct solution to problem.**

I come from a mobile development background so I'm used to tools like Android Lint. This linting tool has the possibility to create a _baseline_ file that registers where all warnings/errors are (filename + offending line)<sup>[1](https://developer.android.com/studio/write/lint#snapshot)</sup>. The baseline file lives in the root directory of your project and, ideally, it is just created once. The tool then checks for errors and ignores them if they are present in the file.

This is really useful to start using linting tools in old projects, as it lets you start with a broken project with many linting errors while making sure you don't introduce any more to the mix.

**Are you willing to submit a pull request to implement this change?**

Sure thing! It'll take me some time as I'm not used to the codebase but I'd love to see this feature implemented and I'm up to offer some help.

---

1 [Android Lint baseline feature](https://developer.android.com/studio/write/lint#snapshot)

**Comment by anikethsaha** [comment]
Thanks for the issue, 

This is a kind of interesting feature. As it involves changes in the core, maybe [RFC](https://github.com/eslint/rfcs) is required for this. 

Alternatively, maybe ignoring all rules, caching the result, and then adding the rule back may solve your issue?

_not sure about this, never tried this, just a thought_

**Comment by yeonjuan** [comment]
Hi @Serchinastico  Thanks for the suggestion. :) I have a question about it

> This is really useful to start using linting tools in old projects, as it lets you start with a broken project with many linting errors while making sure you don't introduce any more to the mix

If it's the purpose of the suggestion, what about using [the "max-warnings" CLI option](https://eslint.org/docs/user-guide/command-line-interface#max-warnings)?

**Comment by Serchinastico** [comment]
> Hi @Serchinastico Thanks for the suggestion. :) I have a question about it
> 
> > This is really useful to start using linting tools in old projects, as it lets you start with a broken project with many linting errors while making sure you don't introduce any more to the mix
> 
> If it's the purpose of the suggestion, what about using [the "max-warnings" CLI option](https://eslint.org/docs/user-guide/command-line-interface#max-warnings)?

This is actually a great compromise. 

On the one side, you lose control of which warnings you are reporting. This means it might happen that you fix 2 warnings and add 2 different ones. As a consequence, eslint wouldn't fail whilst the baseline approach would have. One the other side, it's dead simple and covers most situations so I think I'll go for that.

Thanks for your prompt response and solution :+1:
