### ISSUE TITLE
Automatically disable current violations

### ISSUE THREAD

**Issue by domyalexMS** [eslint/eslint#13439]
**The version of ESLint you are using.**
7.3.0

**The problem you want to solve.**
We work in a fairly large codebase that has been around for several year; however the current files are still being updated on a regular basis. Whenever we decide to enable a new rules, we can get thousands of violations and so we'd like to be able to automatically disable all current violations, but still trigger errors whenever new code is added.

I understand the current options to override/disable rules per file pattern / folder, etc, as well as per-line or per-block disable comments but this is not what we are after either.

**Your take on the correct solution to problem.**
Ideally we'd like an options along the lines of --autoDisable that automatically injects the disable comments (ie: eslint-disable-next-line <rule>) wherever errors are detected.

**Are you willing to submit a pull request to implement this change?**
Potentially

**Comment by yeonjuan** [comment]
@domyalexMS 

Hi :) Thanks for the suggestion.

IMO, I'm not sure injecting disable comment is a good way to support linting on a large codebase.
And there are [--max-warnings CLI option](https://eslint.org/docs/user-guide/command-line-interface#max-warnings) which useful when start linting on a large codebase.
if it is not fit in, I suggest using [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) on your project.

**Comment by kaicataldo** [comment]
I don't think this is a feature that should be included in core. This seems doable with a 3rd party code modding tool, though. As a rough sketch, I think you could do something like the following:

1. Using ESLint's Node API, lint the codebase.
2. Iterate through the results, checking for line numbers of reported errors.
3. Use a code modding tool like [jscodeshift](https://github.com/facebook/jscodeshift) to insert `eslint-disable-next-line` comments.
