### ISSUE TITLE
Documentation broken for no-multiple-empty-lines

### ISSUE THREAD

**Issue by walliski** [eslint/eslint#13432]
**The version of ESLint you are using.**
7.3.0

**The problem you want to solve.**
Documentation for the [no-multiple-empty-lines](https://github.com/eslint/eslint/blob/master/docs/rules/no-multiple-empty-lines.md) rule is wrong. The examples are identical for breaking and non-breaking code. This was introduced in https://github.com/eslint/eslint/commit/1ee3c42ceeee56b650bcc4206ed783b795f65643, probably due to some auto-formatting.

**Your take on the correct solution to problem.**
Revert parts of the documentation to match the intended behavior of the rule.

**Are you willing to submit a pull request to implement this change?**
Not at this point, no.

Also on another note. Not sure if I am not smart, but could not really figure out which category of issue these kind of changes goes into 🤔

**Comment by anikethsaha** [comment]
Thanks for the report.

Yea I think this is an inconsistency.

**Comment by mdjermanovic** [comment]
@walliski thanks for the issue! 

I'm working on it.

Also, you're right, we should probably have a separate issue template for reporting documentation problems, or maybe not assume that "Non-rule change request" must be a core enhancement request :)

**Comment by mdjermanovic** [comment]
This should be fixed by #13433.

Just a note about `maxEOF` examples: they'll still look identical if the document is viewed on github, because github doesn't render any empty lines at the end of code blocks. They should be okay at https://eslint.org/docs/rules/no-multiple-empty-lines
