### ISSUE TITLE
Support ESM config (.eslintrc.mjs)

### ISSUE THREAD

**Issue by jsejcksn** [eslint/eslint#13440]
Search terms used: [`is:issue is:open mjs OR esm OR "es module" `](https://github.com/eslint/eslint/issues?q=is%3Aissue+is%3Aopen+mjs+OR+esm+OR+%22es+module%22)

cf. #12593, which was auto-closed. All of the issues/RFCs mentioned as blockers in that issue are now closed/merged.

What is the status of ES module support for config files? In the form of

- `.eslintrc.mjs` or
- `.eslintrc.js` where the nearest `package.json` includes `"type": "module"`

**Comment by kaicataldo** [comment]
Now that we have an asynchronous API, I believe that supporting `.mjs` is unblocked from a technical standpoint. For the second bullet point, ESLint does already support `.eslintrc.cjs` files, so this should not be an issue (see [here](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) for more details).

**Comment by kaicataldo** [comment]
Would you like to create an [RFC](https://github.com/eslint/rfcs) for adding support for `.mjs`?

**Comment by jsejcksn** [comment]
@kaicataldo Oh, wow—I thought this was already on the roadmap based on all of the discussion around it. I’ll take a look at the RFC process. Does it require having any knowledge of ESLint’s internal API (not user API)?

**Comment by kaicataldo** [comment]
The RFC template is a section for outlining what kind of changes would be required to implement it, which is really useful both for evaluating trade offs as well as for whoever ends up implementing the accepted RFC.

This is definitely something we want to do, but I do think it makes sense to go through this process to make sure we approach it thoughtfully.

**Comment by jsejcksn** [comment]
@kaicataldo I looked and I don't think I have enough knowledge about ESLint internals to provide implementation details. Is there an RFC for an RFC 😄?

**Comment by kaicataldo** [comment]
Ha! My personal take is that this is something we’re going to have to implement eventually anyway, if you’re willing to wait :)

In the meantime, it should be possible to use a `.eslintrc.cjs` configuration file.

**Comment by jsejcksn** [comment]
Sure—I just didn't see a place to track ESM configs specifically, so I created this issue.

**Comment by Rishabh-malhotraa** [comment]
@kaicataldo I would like to try to solve this issue :)

**Comment by kaicataldo** [comment]
@Rishabh-malhotraa Great! As mentioned above, the next step is create an RFC for this so that we can decide how this should be implemented.

**Comment by nzakas** [comment]
Given that we are moving forward with a different config system, I think any changes should be proposed for the new system rather than continuing to modify the current system. 
https://github.com/eslint/rfcs/pull/9

**Comment by jsejcksn** [comment]
> Given that we are moving forward with a different config system

@nzakas I thought it was just an RFC at this point. Especially in consideration of the statement in [your most recent message](https://github.com/eslint/rfcs/pull/9#issuecomment-653219866), isn’t it prudent to support ESM in the current system?

**Comment by nzakas** [comment]
The RFC was accepted several months ago and will be the new config system for ESLint. There were some outstanding questions that had to be answered so I kept iterating until we got most of them ironed out. It will be formally merged this week with development starting next week. 

I don’t see a scenario where it makes sense to update the eslintrc config system to support ESM. The simple config system actually makes supporting ESM super easy, though I’m not sure I’d want to support the .mjs extension as I think that will be a relic in the next couple years. However, we could support ESM in simple config files relatively easily.

**Comment by ljharb** [comment]
@nzakas i'm not sure why it'd be a relic; it'll be supported by node for the foreseeable future, and is the best way to avoid ambiguity about what `.js` means (which is "not a module", unless you use the `type` field to subvert that).

**Comment by nzakas** [comment]
@ljharb I just don't foresee people using it much after the transition period from CJS to ESM. Right now, it's a stopgap for needing to support both in Node.js packages, but eventually (and probably sooner than we realize), no one is going to be writing CJS, so I'm not sure it's worth adding in support for a stopgap measure that eventually won't be used.

**Comment by ljharb** [comment]
imo that's entirely false :-) people are still writing ES5, and sloppy code, and Scripts, and I think CJS will be around for effectively ever. Obv we don't have to agree here, but the node modules group is expecting a *minimum* of 10 years before it'd even be remotely possible to *consider* deprecating any CJS features.

**Comment by nzakas** [comment]
Here's the nice thing about my approach: if I'm wrong, we can always add support for `.mjs` later. I'm just less inclined to add a feature that may or may not be needed because we already have nearly seven years of backwards compatibility cruft in ESLint that we really can't remove, so I don't want to add more unless we need it.

**Comment by nzakas** [comment]
As a final note here: ESM config will be part of the https://github.com/eslint/rfcs/pull/9 implementation.

**Comment by KilianKilmister** [comment]
@kaicataldo 
> In the meantime, it should be possible to use a `.eslintrc.cjs` configuration file.

Well yes, but only sort of. I just tried to use a dynamit `import( )` statement in my config, but eslint isn't able to use that.
I'm in the process of filing an issue about it with the details.
