### ISSUE TITLE
Config json cloning is a BREAKING CHANGE!

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#13447]
Related: https://github.com/eslint/eslint/pull/13034#discussion_r446611500

**Tell us about your environment**

* **ESLint Version:** 7.3.1
* **Node Version:** v14.4.0
* **npm Version:** 6.14.4

**What parser (default, Babel-ESLint, etc.) are you using?**

[eslint-mdx](https://github.com/mdx-js/eslint-mdx)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: 'plugin:unicorn/recommended',
  rules: {
    'unicorn/filename-case': [
      2,
      {
        cases: {
          kebabCase: true,
          pascalCase: true,
        },
        // ignore UPPER_CASE markdown filenames
        ignore: [/^[A-Z](([\dA-Z]+_)*[\dA-Z]+)?\.mdx?$/],
      },
    ]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```markdown
<!-- README.md -->
```

```bash
eslint README.md
```

**What did you expect to happen?**
no error

**What actually happened? Please include the actual, raw output from ESLint.**
```log
1:2  error  Filename is not in kebab case or pascal case. Rename it to `readme.md` or `Readme.md`  unicorn/filename-case
```

The error occurres because the ESLint config is json cloned since v7.3.0, and this breaks `Regxp` option of [`unicorn/filename-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md#ignore), I don't think this is an invalid usage.

**Comment by anikethsaha** [comment]
You can try regex in string ? in your case, `'/^[A-Z](([\dA-Z]+_)*[\dA-Z]+)?\.mdx?$/'`, though the flags wont work here, there can be work-around in the unicorn plugin to remove the regex instance and go with full string , even string for flags in a array 

like

```js
ignore: [ '^FOOBAR\\.js$', ['^FOOBAR\\.js$', 'i'] ]
```

but yeah , this was a breaking change.

**Comment by aladdin-add** [comment]
what do you think revert the change? we can reconsider introducing it in a major release(eslint v8)

**Comment by anikethsaha** [comment]
I did mention that earlier, https://github.com/eslint/eslint/pull/13034#issuecomment-646804513. 

+1 for that

**Comment by kaicataldo** [comment]
I personally think this change should be reverted (even though I understand it was considered a bug fix, because the intention was always to have ESLint configs be serializable). @eslint/eslint-tsc I know there was other discussion of this while I was on vacation. Would someone like to fill us in on what the final decision was?

**Comment by nzakas** [comment]
The discussion was to wait and see how many bug reports we received before deciding whether to revert or not. We had just one report of the use of `Infinity`, and given that was clearly a bug and could be easily replaced with a valid number to work the same, we decided to add a patch to allow that isolated case. 

This case is more concerning because it involves encouraging end users to use regular expressions in their configs (vs one isolated instance of `Infinity` in one config).

With this new data, I’m in favor of reverting the change.

**Comment by aladdin-add** [comment]
well, seems we have reached a consensus to revert it. will make a PR later!

**Comment by kaicataldo** [comment]
@btmills @mysticatea Would love to hear your opinions as well :)

**Comment by mysticatea** [comment]
:+1: for reverting.

**Comment by btmills** [comment]
Agreed with @nzakas - this is the sort of end-user case we were looking for that would indicate we need to revert. A couple things we could do in addition to reverting:

- Add custom `replacer` functions that log non-fatal warnings when non-serializable values are found in the [cache](https://github.com/eslint/eslint/blob/bf3939bbd9a33d0eb96cebe6a53bf61c855f9ba6/lib/cli-engine/lint-result-cache.js#L32) and [`--print-config`](https://github.com/eslint/eslint/blob/bf3939bbd9a33d0eb96cebe6a53bf61c855f9ba6/lib/cli.js#L266) option.
- Open an issue with [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) to start a discussion around alternatives.

**Comment by ljharb** [comment]
Note that the cloning isn't the issue; it's using JSON to clone that's the issue. A proper deep cloning algorithm would work fine and preserve the fix that cloning originally solved.

**Comment by kaicataldo** [comment]
Marking as accepted since the entire TSC is in favor of reverting.

**Comment by kaicataldo** [comment]
@ljharb Yeah, that was also explored. I believe the reason that implementation was not chosen was due to challenges with potential circular references.

**Comment by ljharb** [comment]
@kaicataldo yeah, that gets tricky, but i'd expect that to be handleable with a WeakMap, and mapping "original object" to "cloned object", prior to iterating over the original object to clone copies into the cloned object, and always looking up a cloned object in the map before creating a new one.

**Comment by anikethsaha** [comment]
similar to https://github.com/eslint/eslint/pull/13034#issuecomment-632339452 ?
