### ISSUE TITLE
Deprecating CLIEngine when it still has needed features?

### ISSUE THREAD

**Issue by bradennapier** [eslint/eslint#13454]
I noticed when building a github action to run eslint on changed files that I could not accomplish what I needed without the `CLIEngine`.

Specifically the `engine.getRules()` feature I am using to get the metadata of a rule so that I can get the docs for the rule that triggered an event.

Is there some other way to get the rules for the run?

I noticed the linter has a getRules() but that doesn't seem to return anything and expects all the rules to be defines via programmatic methods.  In my case I am running programmatically but want it to load all the linting rules and such from the given .eslintrc and .eslintignore like the CLIEngine is doing so basically looking for the equivalent of the `engine.getRules()` which returns a `Map` of rule to metadata and such.

```typescript
const ruleDocs = engine.getRules().get(ruleId)?.meta?.docs;
``` 

> **Note:** I also noticed most of the anchors on https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions do not actually work, just a FYI - many do nothing or go to a 404.

**Comment by kaicataldo** [comment]
The plan is to add a corresponding API to the ESLint class. You can find more details in [this RFC](https://github.com/eslint/rfcs/tree/master/designs/2019-move-to-async-api). From the RFC:

> `getRules()` ... This method returns the map that contains core rules and the rules of the plugin that the previous `executeOnFiles()` method call used. This behavior is surprised and forces us to store the config objects that the previous `executeOnFiles()` method call used. This proposal removes this method and a separated RFC (maybe [RFC47]) will add the successor.

Until that's implemented, I think it makes sense to continue using `CLIEngine`.

**Comment by bradennapier** [comment]
Ok great, good to know!  Thanks for the reply!
