### ISSUE TITLE
getting 'color' PropType is defined but prop is never used in react navigation 

### ISSUE THREAD

**Issue by khaledBou** [eslint/eslint#13468]
**Environment**

"eslint": "^7.3.1",
react-native": "0.61.5",

**Libraries**
"@typescript-eslint/parser": "^3.4.0",
    "babel-eslint": "^10.1.0",

**How i got the error**

I configured eslint with vs code for react native

```js
function ButtomTabs() {
  return (
    <Tab.Navigator
      initialRouteName="Home"
      activeColor={COLORS.ACTIVETAB}
      inactiveColor={COLORS.INACTIVETAB}
      barStyle={{backgroundColor: COLORS.DEFAULT}}
      backBehavior="initialRoute"
      lazy
      shifting={false}
      tabBarOptions={{
        activeTintColor: COLORS.ACTIVETAB,
        inactiveTintColor: COLORS.INACTIVETAB,
      }}>
      <Tab.Screen
        name="Home"
        component={HomeStackScreen}
        options={{
          tabBarLabel: 'Accueil',
          tabBarColor: COLORS.DEFAULT,
          tabBarIcon: ({color}) => <MaterialCommunityIcons name="home" color={color} size={26} />,
        }}
      />
```

```js
ButtomTabs.propTypes = {
  color: PropTypes.string.isRequired,
};
```

**What did you expect to happen?**

Normally i got no eslint error

**What actually happened? Please include the actual, raw output from ESLint.**

I got an error about color props : 

'color' PropType is defined but prop is never usedeslintreact/no-unused-prop-types

**Comment by mdjermanovic** [comment]
Hi @khaledBou, thanks for the issue!

This seems to be related to a third party rule `react/no-unused-prop-types` from `eslint-plugin-react`.

Can you please open issue in the plugin's repository:

https://github.com/yannickcr/eslint-plugin-react

**Comment by khaledBou** [comment]
okay thanks :)

**Comment by mdjermanovic** [comment]
Closing this issue since it isn't related to eslint core rules.
