### ISSUE TITLE
TypeError: createRequire is not a function

### ISSUE THREAD

**Issue by RuanXuSong** [eslint/eslint#13467]
**Tell us about your environment**

* **ESLint Version:7.4.0**
* **Node Version:12.17.0**
* **npm Version:6.14.4**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  rules: {
    complexity: ['warn', { max: 5 }],
    '@typescript-eslint/camelcase': 0,
    '@typescript-eslint/class-name-casing': 0,
    'import/no-extraneous-dependencies': 0,
    '@typescript-eslint/no-explicit-any': 0,
    'import/no-unresolved': 0,
    'import/no-dynamic-require': 0,
    'import/order': 0,
    'global-require': 0,
    'no-shadow': 0,
    'no-param-reassign': 0,
    'symbol-description': 0,
    'no-unused-expressions': 0,
    'class-methods-use-this': 0,
    'no-undef': 0,
    'no-console': 0,
    'dot-notation': 0,
    'prefer-template': 0,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I just added below code in `.eslintrc.js`,and it went wrong.`@umijs/fabric/dist/eslint` is a configuration file containing `eslint`

```js
extends: [require.resolve('@umijs/fabric/dist/eslint')],
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

Whenever I open a file,it will throw an error like this.
```
TypeError: createRequire is not a function
Referenced from: /Users/michael/Work/leishu/project/my-project/.eslintrc.js
    at Object.resolve (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/shared/relative-module-resolver.js:29:20)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/config-array-factory.js:854:39)
    at ConfigArrayFactory._loadExtends (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/config-array-factory.js:763:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/config-array-factory.js:495:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:355:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/michael/Work/leishu/project/my-project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:374:20)
```

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by btmills** [comment]
When you run [`eslint --env-info`](https://eslint.org/docs/user-guide/command-line-interface#env-info), what does it show? The `createRequire()` API has existed in one form or another since [Node 10.12](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.12.0), so I'm wondering if somehow there's an earlier version of Node being used.

**Comment by RuanXuSong** [comment]
> When you run [`eslint --env-info`](https://eslint.org/docs/user-guide/command-line-interface#env-info), what does it show? The `createRequire()` API has existed in one form or another since [Node 10.12](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.12.0), so I'm wondering if somehow there's an earlier version of Node being used.

When I run `eslint --env-info`,as shown below:
```
Environment Info:

Node version: v12.17.0
npm version: v6.14.4
Local ESLint version: Not found
Global ESLint version: Not found
```
Because my eslint is project built-in.Certainly,I find this issue is because of the version of my Visual Studio Code.When I upgrade my Visual Studio Code ,this problem went away.But I don't know why old version of Visual Studio Code causes this  problem.

**Comment by btmills** [comment]
Aha! So you got the error when running ESLint from VSCode, but not from the command line? Here's what I bet was happening:

1. VSCode's ESLint integration probably runs ESLint using the Node.js that's part of Electron.
1. The pre-upgrade version of VSCode probably included an older version of Electron that included an older version of Node.js that didn't have the `createRequire` API.
1. When you updated VSCode, it included upgraded versions of Electron, which included an upgraded version of Node.js, which now includes `createRequire`.

Does that sound plausible? If so, and assuming things are fixed now, then nothing left to do here!

**Comment by RuanXuSong** [comment]
> Aha! So you got the error when running ESLint from VSCode, but not from the command line? Here's what I bet was happening:
> 
> 1. VSCode's ESLint integration probably runs ESLint using the Node.js that's part of Electron.
> 2. The pre-upgrade version of VSCode probably included an older version of Electron that included an older version of Node.js that didn't have the `createRequire` API.
> 3. When you updated VSCode, it included upgraded versions of Electron, which included an upgraded version of Node.js, which now includes `createRequire`.
> 
> Does that sound plausible? If so, and assuming things are fixed now, then nothing left to do here!

Yes,that's it!So there is nothing to do but upgrade VSCode.Thanks anyways~
