### ISSUE TITLE
Unexpected token: illegal catch statement

### ISSUE THREAD

**Issue by skerit** [eslint/eslint#13463]
There's an `(err)` missing in this catch statement:

https://github.com/eslint/eslint/blob/bcafd0f8508e19ab8087a35fac7b97fc4295df3e/bin/eslint.js#L93

Edit: This is apparently accepted behavior since node 10.3

**Comment by anikethsaha** [comment]
Not sure about whats the issue. Are you facing parsing error while running eslint ?

this is [optional catch binding](https://tc39.es/proposal-optional-catch-binding/) feature. 

[ref this](https://github.com/eslint/eslint/issues/13419).

**Comment by skerit** [comment]
Yes, it's the same issue as the one you referred to. An older version of node was throwing that error.
Normally "new syntax" would immediately make me think about the version of node I'm currently running, but seeing a `catch` statement without binding a variable seems like such an anti-pattern it never even crossed my mind.

**Comment by daniloprates** [comment]
I'm having the same issue using eslint with SublimeLinter. Any solution on this?
