### ISSUE TITLE
ESLint: Missing semicolon.(semi) adding multiple semicolons after curly braces

### ISSUE THREAD

**Issue by uzagoranski** [eslint/eslint#13480]
**Tell us about your environment**

* **ESLint Version:** 7.4.0
* **Node Version:** 10.16.3
* **npm Version:** 6.14.5

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module",
        "project": "./tsconfig.json"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "indent": [
            "warn",
            "tab"
        ],
        "quotes": [
            "warn",
            "double"
        ],
        "semi": [
            "warn",
            "always"
        ],
        "arrow-parens": [
            "warn"
        ],
        "object-curly-spacing": [
            "warn",
            "always"
        ],
        "no-trailing-spaces": [
            "warn"
        ],
        "comma-dangle": [
            "warn",
            {
                "arrays": "always-multiline",
                "objects": "always-multiline",
                "imports": "always-multiline",
                "exports": "always-multiline",
                "functions": "always-multiline"
            }
        ],
        "space-before-blocks": [
            "warn"
        ],
        "keyword-spacing": [
            "warn"
        ],
        "array-bracket-spacing": [
            "warn",
            "always"
        ],
        "eol-last": [
            "warn"
        ],
        "space-infix-ops": [
            "warn"
        ],
        "padding-line-between-statements": [
            "warn",
            { "blankLine": "always", "prev": ["const", "let", "var"], "next": "*"},
            { "blankLine": "always", "prev": "import", "next": "*"},
            { "blankLine": "never", "prev": "import", "next": "import"},
            { "blankLine": "any",    "prev": ["const", "let", "var"], "next": ["const", "let", "var"]},
            { "blankLine": "always", "prev": "*", "next": "return"}
        ],
        "no-multiple-empty-lines": [
            "warn",
            { "max": 1 }
        ],
        "no-multi-spaces": [
            "warn"
        ],
        "prefer-template": [
            "warn"
        ],
        "@typescript-eslint/no-empty-function": [
            "error",
            { "allow":  ["constructors"] }
        ],
        "@typescript-eslint/no-extra-semi": 0,
        "@typescript-eslint/no-non-null-assertion": 0,
        "@typescript-eslint/interface-name-prefix": 0
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```
export default interface ICompany {
	id: string;

	name: string;

	adminUsers: string[];

	emails: {
		defaultSendFromEmail: string;
		defaultAdministrativeEmail: string;
		defaultBusinessTripEmail: string;
		defaultAbsenceEmail: string;
	}

	workDays: boolean[];
};;;;;;;;;;;

```

```
eslint --ext .ts,.tsx ./ --fix
```

**What did you expect to happen?**

One semi colon to be added at the end of the file (after last curly brace).

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint rule **semi** expects semicolon after curly brace:
![Screenshot 2020-07-10 at 2 17 40 PM](https://user-images.githubusercontent.com/33725933/87153660-1fb5ca80-c2b8-11ea-90b1-6d2b57bc8487.png)

After executing ESLint fix command, too many semicolons are added at the end of the file:
![Screenshot 2020-07-10 at 2 19 28 PM](https://user-images.githubusercontent.com/33725933/87153829-60154880-c2b8-11ea-97ae-4797eb37405b.png)

If unnecessary semicolons are removed, ESLint suggests adding missing semicolons again, so we encounter infinite loop.

**Are you willing to submit a pull request to fix this bug?**

No

**Comment by anikethsaha** [comment]
Thanks for the repo. 

Can you try turning off the base `semi` and turn on the `typescript-eslint/semi` [like this](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/semi.md#how-to-use)

**Comment by yeonjuan** [comment]
Hi @uzagoranski 

> Can you try turning off the base semi and turn on the typescript-eslint/semi like this
- [@anikethsaha 's comment](https://github.com/eslint/eslint/issues/13480#issuecomment-656651779)

Could you try it? 
ESLint core didn't support the TypeScript syntax, and it can make some incorrect results.

**Comment by uzagoranski** [comment]
@anikethsaha @yeonjuan thank you both! I added `@typescript-eslint/semi` and `@typescript-eslint/member-delimiter-style` and now it works as it should!
