### ISSUE TITLE
no-void should be in "Stylistic Issues" category

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#13498]
This is a proposal to change the category of the `no-void` rule to "Stylistic Issues", because the rule is about preferences, not best practices.

`no-void` is currently categorized as a "Best Practice" rule, which suggests that it is considered a best practice to not use `void`. That wasn't the intention when this rule was introduced (#1017).

This change should avoid some confusion about this rule. In particular, if one assumes that this rule does enforce best practices (based on its current category), it could seem that the rule fails to allow some cases where the use of `void` might not be a bad practice, while it's actually just a stylistic rule.

**Comment by mdjermanovic** [comment]
Marked as accepted per today's TSC meeting.

Marked as breaking based on the discussion in #13398.

**Comment by tanohzana** [comment]
@mdjermanovic  I can help with this ! I just need a week ✌🏽

**Comment by mdjermanovic** [comment]
Hi @tanohzana!

We're also planning to use the rule types instead of categories for our website, as discussed in https://github.com/eslint/eslint/issues/13398. 

That change could also include removing the `category` field from the core rules, so this issue might become obsolete.

Either way, this is a breaking change and we won't be able to merge it before the next major release, so it might be better to wait for the next major release cycle, when we'll certainly know if this change should be implemented or not.

**Comment by mdjermanovic** [comment]
We have decided to remove the `meta.docs.category` property from all core rules (https://github.com/eslint/eslint/issues/13398), so this can be closed.
