### ISSUE TITLE
eslint --fix not working when running by npm

### ISSUE THREAD

**Issue by ChumakovaAnna** [eslint/eslint#13490]
**Tell us about your environment**
Eslint find many problems 
"122 errors and 0 warnings potentially fixable with the `--fix` option." but fixable not work.

* **ESLint Version:** 7.4.0
* **Node Version:** 12.18.2
* **npm Version:** 6.14.5

**What parser (default, Babel-ESLint, etc.) are you using?**
not used

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

  "scripts": {
    "build": "webpack --config webpack.prod.js",
    "coverage": "jest --coverage",
    "doc": "jsdoc -c jsdoc.conf.json",
    "lint": "eslint .",
    "start": "webpack-dev-server --config webpack.dev.js",
    "test": "exit 0"
  },
"devDependencies": {
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.2",
    "@babel/preset-env": "^7.10.2",
    "babel-jest": "^26.0.1",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.6.0",
    "eslint": "^7.4.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jest": "^23.18.0",
    "file-loader": "^6.0.0",
    "html-loader": "^1.1.0",
    "inline-source-map": "^0.6.2",
    "jest": "^26.0.1",
    "jsdoc": "^3.6.4",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "core-js": "3",
    "html-webpack-plugin": "^4.3.0",
    "mini-css-extract-plugin": "^0.9.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "push-dir": "^0.4.1",
    "terser-webpack-plugin": "^3.0.6",
    "webpack-merge": "^4.2.2"
  },
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
npm run lint
npm run lint --fix

<!-- Paste the source code below: -->
https://github.com/ChumakovaAnna/AHJ-hw-2-task-1
The code is training and not working, I know. But Eslint doesn’t fix problems for me and I want to fix it.

```

powershell

```

**What did you expect to happen?**
Problems that can be automatically fixed - fixed

**What actually happened? Please include the actual, raw output from ESLint.**
All problems are re-located, but not fixed. I can’t understand if this is a mistake in me or in Eslint

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by ChumakovaAnna** [comment]
Reinstalled the node_modules folder
Eslint in global not have

**Comment by mdjermanovic** [comment]
Hi @ChumakovaAnna, thanks for the issue!

I think this is related to how [npm run](https://docs.npmjs.com/cli/run-script) works with arguments.

Can you try:

```
npm run lint -- --fix
```

**Comment by ChumakovaAnna** [comment]
Sorry! I am stupid :)
