### ISSUE TITLE
`--cache` stores source code in the cache file on the second run

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#13507]
**Tell us about your environment**

* **ESLint Version:** master (v7.5.0)
* **Node Version:** v12.14.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

Linting ESLint's codebase, just added the following line to `rules` in [`.eslintrc.js`](https://github.com/eslint/eslint/blob/f3a19d2a7ea9505000d14229a450dba133c10d5e/.eslintrc.js#L66):

```js
strict: ["error", "never"],
```

with this change, all files in our codebase will have a linting error (since they all have `"use strict"`) and thus all linting results will have `source` property.

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
npx eslint . --cache

npx eslint . --cache
```

**What did you expect to happen?**

Same cache size after the first and the second run.

**What actually happened? Please include the actual, raw output from ESLint.**

`.eslintcache` file size:

* First run ~380KB
* Second run ~10000KB (contains all source code) 

**Are you willing to submit a pull request to fix this bug?**

Yes.

By the comments in [lint-result-cache.js](https://github.com/eslint/eslint/blob/f3a19d2a7ea9505000d14229a450dba133c10d5e/lib/cli-engine/lint-result-cache.js#L124) it seems the intention was not to store `result.source` in the cache file.

However, getting linting results from the cache [mutates](https://github.com/eslint/eslint/blob/f3a19d2a7ea9505000d14229a450dba133c10d5e/lib/cli-engine/lint-result-cache.js#L90) cache objects that will be later saved on `reconcile`.

**Comment by nzakas** [comment]
@mdjermanovic is still issue still relevant?

**Comment by mdjermanovic** [comment]
Yes, I can still reproduce this with eslintrc, and now with flat config as well. I'm working on the fix.

**Comment by mdjermanovic** [comment]
I'm working on this now. I also noticed that `usedDeprecatedRules` property of lint results can mistakenly be stored in the cache file (though this can only happen when ESLint is used through API).
