### ISSUE TITLE
update documentation re  no-param-reassign

### ISSUE THREAD

**Issue by EdmundsEcho** [eslint/eslint#13506]
Great tool.  I hope this idea might help.

`no-param-reassign` is a solid rule for good reason (it's not intuitive that a function's arguments is recorded as an array, not a key-value).  

However, may I suggest the one time the user can safely ignore this rule: creating an object from an array using reduce.  I use the eslint-rules for three reasons (loosely speaking): 

1. safety that includes consistent, clean design
2. idiomatic to plug-into norms and thus increase speed of understanding
3. performance without sacrificing on safety

My recommendation would be to describe how avoiding a destructuring call on every iteration of the reducing function likely provides a net benefit when building an object from an array using reduce.

This is such an often used function (`reduce`), that I believe it merits this special "calling out".

What do you all think?

\- E

**Comment by mdjermanovic** [comment]
Hi @EdmundsEcho, thanks for the suggestion!

> However, may I suggest the one time the user can safely ignore this rule: creating an object from an array using reduce.

Do you mean mutating the accumulator?

> My recommendation would be to describe how avoiding a destructuring call on every iteration of the reducing function likely provides a net benefit when building an object from an array using reduce.

I think that would be out of scope for this rule's documentation, but an example for `"ignorePropertyModificationsFor": ["accumulator"]` (or `"acc"`) might be nice since it's relatively common. For example, it's in [airbnb config](https://github.com/airbnb/javascript/blob/c5bee75b1b358a3749f1a6d38ee6fad73de28e29/packages/eslint-config-airbnb-base/rules/best-practices.js#L199).

(if I got the suggestion right)

**Comment by EdmundsEcho** [comment]
@mdjermanovic You got it.  It's about mutating the accumulator in the reduction function.  When I do something like:

```javascript
someArray.reduce(acc, arrayItem) => {
   acc[arrayItem.name]: { ... do something };
   return acc; 
}, {})
```
Eslint complains.

FYI: I also have airbnb up and running.  Does the sequence of entries in my config infer a prioritization of some sort?  Do you have an example of a config that uses prettier, react and airbnb?

**Comment by mdjermanovic** [comment]
> PS: I also have airbnb up and running. Does the sequence of entries in my config infer a prioritization of some sort? Do you have an example of a config that uses prettier, react and airbnb?

You can use [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#print-config) to see the configuration that will be used for the particular file.

In no other config re-defines `no-param-reassign` rule, then it should print the options from the `airbnb` config (`props: true, ignorePropertyModificationsFor: ['acc', ...`).

In that case, the rule shouldn't warn on assigning to properties of `acc`, as in [this online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcGFyYW0tcmVhc3NpZ246IFtcImVycm9yXCIsIHsgXG4gICAgcHJvcHM6IHRydWUsXG4gICAgaWdub3JlUHJvcGVydHlNb2RpZmljYXRpb25zRm9yOiBbXCJhY2NcIl1cbn1dKi9cblxuc29tZUFycmF5LnJlZHVjZSgoYWNjLCBhcnJheUl0ZW0pID0+IHtcbiAgIGFjY1thcnJheUl0ZW0ubmFtZV0gPSBhY2NbYXJyYXlJdGVtLnZhbHVlXTtcbiAgIHJldHVybiBhY2M7IFxufSwge30pIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).

I also tried locally with this eslint config:

```json
{  
    "extends": ["airbnb"]  
}
```

and eslint doesn't report `no-param-reassign` errors in the following code:

```js
someArray.reduce((acc, arrayItem) => {
  acc[arrayItem.name] = acc[arrayItem.value];
  return acc;
}, {});
```

**Comment by EdmundsEcho** [comment]
Thank you for letting me know how to verify the rules being enforced.  I was using it to make sure I did not have any rules conflicting one another, but not in a way that had me see the list... thank you.  

Does it make sense to update the eslint docs?

**Comment by mdjermanovic** [comment]
> Does it make sense to update the eslint docs?

I support adding one "valid" example with `reduce`, it could be something like this:

```js
/*eslint no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ["acc"] }]*/

someArray.reduce((acc, arrayItem) => {
   acc[arrayItem.name] = arrayItem.value;
   return acc;
}, {});
```

I  think we shouldn't add more details or recommendations about `reduce` to this particular document, but the example would be nice.

**Comment by EdmundsEcho** [comment]
@mdjermanovic I think your idea is spot-on.  In general, when such a suggestion is made, are the authors of the documentation implying that if you had to break the rule, this would be a *good/acceptable* time to do so.  In other words, implying a positive connotation to when to make an exception?  \- E

**Comment by mdjermanovic** [comment]
> are the authors of the documentation implying that if you had to break the rule, this would be a good/acceptable time to do so

Not necessarily, though a realistic example of an exception that seems to be at least acceptable is usually preferable over one that looks like a bad practice,

**Comment by platinumazure** [comment]
It's also worthwhile to note that this is a pretty good use case for [inline disable comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments). You could use those comments in the cases where `acc` is a real accumulator in a `reduce` function, but not allow mutations of `acc` parameters in other contexts.

That said, I wouldn't oppose improving the docs with a `reduce` example.
