### ISSUE TITLE
Add parser lifecycle hooks

### ISSUE THREAD

**Issue by bradzacher** [eslint/eslint#13525]
I wanted to raise an issue just to see if there's any interest from the core team here before spending the time writing out an entire RFC.

The @typescript-eslint project has a stateful parser<sup>[1]</sup>.
ESLint, however, is designed around stateless parsers.

This causes two issues for us:
- We have a lot of complexity in our parser because we have to handle both the "persistent watch" case (ie. IDEs) and the "one and done" case (ie. CLI runs).
  - For the "persistent watch" case, we need to figure out when to update our internal state when files are added/deleted, but we don't need to worry about this in the "one and done" case.
- (For medium-large+ projects) This causes issues for us and our users caused by OOMs because we can not know when it's safe to cleanup resources.

To help with this, I would propose the addition of two features:
- a new config option to let consumer specify the work they're doing with the ESLint API, eg:
  - pass a flag `workloadType: 'persistent' | 'transient'` (default `transient`) when constructing the `ESLint` class, which can then be passed to the parser to signal the type of work being done.
- a new method (or methods?) for the parser API which lets ESLint signal the state to the parser, eg:
  - "lint run start", before any files are sent for parsing.
    - Potentially passes a list of files included in the lint run.
  - "lint run end", when there are no more files to be parsed.
  - "file complete", when a file that was parsed has finished being linted.

If the core team is at all interested in this, I'll go ahead and write a RFC for this on the weekend.

----

[1] Note that it's only stateful if the user configures it to include type information.

**Comment by kaicataldo** [comment]
I'm in support of an RFC for this :+1:. I'm not convinced about the `workloadType` flag being passed to the parser, but we can find consensus on the API in the RFC.
