### ISSUE TITLE
mac/ctrl+s/ Unable to repair itself

### ISSUE THREAD

**Issue by takhello** [eslint/eslint#13532]
**Tell us about your environment**

* **ESLint Version:**
"eslint": "^5.16.0"
* **VS-code ESLint extension Version:**
2.1.8
* **Node Version:**
v10.15.3
* **npm Version:**
6.4.1
**What parser (default, Babel-ESLint, etc.) are you using?**
ESLint
**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
  "eslint.options": {
        //指定vscode的eslint所处理的文件的后缀
        "extensions": [
            ".js",
            ".vue",
            ".ts",
            ".tsx"
        ]
    },
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true 
    },
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Add a space outside the rule and save

```js
 console.log('1') //Pay attention to the Spaces
```

```bash
// What all not/Auto repair
```

**What did you expect to happen?**

Spaces are automatically removed
**What actually happened? Please include the actual, raw output from ESLint.**
![image](https://user-images.githubusercontent.com/24371818/88530608-312b0080-d034-11ea-810c-20663995654e.png)
![image](https://user-images.githubusercontent.com/24371818/88530691-56b80a00-d034-11ea-888e-26bb6217d264.png)

When I use the lower version，
<img width="215" alt="4B83095F-6A62-42C2-839E-DFEB100878F7" src="https://user-images.githubusercontent.com/24371818/88552329-8d9f1780-d056-11ea-86e4-f0bca403150b.png">
<img width="400" alt="303D4CB7-115B-4C95-A2A6-2CD65DE06282" src="https://user-images.githubusercontent.com/24371818/88552337-90017180-d056-11ea-9ff9-1fb0fdfce69e.png">

**Are you willing to submit a pull request to fix this bug?**
Beyond the ability

**Comment by yeonjuan** [comment]
Hi: ) @takhello 
Can you share your eslint config (.eslintrc{.js,json,yaml..})?

**Comment by takhello** [comment]
expressing thanks，
module.exports = {
    root: true,
    env: {
        node: true
    },
    'extends': [
        'plugin:vue/essential',
        '@vue/standard'
    ],
    rules: {
        'no-console': 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        // allow async-await
        'generator-star-spacing': 'off',
        'no-extend-native': 0,
        'no-callback-literal': 'off',
        // Default first line indentation 4
        // 'vue/script-indent': ['error', 4, {'baseIndent': 1}],
        'indent': ['error', 4, { 'SwitchCase': 1 }],
        'object-curly-spacing': 0,
        'vue/no-reserved-keys': 0,
        // allow async-await
        "generator-star-spacing": "off",
        // allow debugger during development
        "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
        eqeqeq: 0, 
        "no-use-before-define": 0, 
        "no-undef": 0, 
        "prefer-promise-reject-errors": 0,
        "no-extend-native": 0, 
        "no-global-assign": 0, 
        "no-unused-vars": 0, 
        semi: 0, ,
        "no-multiple-empty-lines": 1,
        "one-var": 0,
        "no-tabs": 1,
        "no-redeclare": 1,
        "no-proto": 1,
        "no-inner-declarations": 1,
        "no-unmodified-loop-condition": 0,
        "no-shadow-restricted-names": 0,
        "no-useless-escape": 0, 
        "no-inner-declarations": 0,
        "standard/no-callback-literal": 0,
        "no-unused-expressions": 0,
        "no-eval": 0,
        "standard/computed-property-even-spacing": 1,
        camelcase: 1,
        'comma-dangle': 0,
        'handle-callback-err': 1

    },
    parserOptions: {
        parser: 'babel-eslint'
    },
    overrides: [
        {
            files: [
                '**/__tests__/*.{j,t}s?(x)',
                '**/tests/unit/**/*.spec.{j,t}s?(x)'
            ],
            env: {
                jest: true
            }
        }
    ]
}

**Comment by yeonjuan** [comment]
@takhello 
Thanks, I think the version you mentioned (`2.1.8`) is a version of  VS-code ESLint extension.
Could you give me a version of `eslint`? 
>  eslint --v

And could you explain it more? `// What all not/Auto repair`

**Comment by takhello** [comment]
The version adopted is，
"eslint": "^5.16.0"

**Comment by g-plane** [comment]
It seems that it's a problem of ESLint extension from VS Code, not ESLint itself. To confirm this, can you try running ESLint from CLI?
