### ISSUE TITLE
Please add "extended" config in addition to "recommended"

### ISSUE THREAD

**Issue by pkruk2** [eslint/eslint#13541]
Hello, 

as far as I know eslint provides only eslint:recommended and eslint:all configs. I'd like to have also eslint:recommended-extra or something similar.

There are a lot of interesting rules available, rules which catch possible errors, which are not enabled in eslint:recommended. On the other hand eslint:all produces a lot of formatting-related findings.

Having something in the middle would be nice.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

IMO, It looks great for a custom config and you can even publish that config.

**Comment by kaicataldo** [comment]
As @anikethsaha says, the purpose of having user-defined configurations is to allow users to enforce whatever they would like.

We don't recommend using `eslint:all`, and `eslint:recommended` is purposefully kept to enforcing things that are universally accepted as errors or bad practices, regardless of environment.
