### ISSUE TITLE
'ReturnType' is not defined

### ISSUE THREAD

**Issue by dschinkel** [eslint/eslint#13550]
We we to just ignore this specific case? What about other cases where eslint doesn't recognize some of the TS API such as `'unknown' is not defined` which is another error I get in the same file?

 It's complaining about the TypeScript `ReturnType` object and `unknown` parameter (further down in my code in this file) which are both part of the typescript API.
![y7iek](https://user-images.githubusercontent.com/338798/89603619-2429c080-d82f-11ea-8003-11c4df5c4e09.jpg)

**Comment by ljharb** [comment]
I believe you have to use the typescript eslint plugin's rules and config, which subsumes all the core rules that conflict with typescript.

babel-eslint functions the same way.

**Comment by dschinkel** [comment]
Thanks and Hi again @ljharb.  Sorry can you be more specific, what do you mean by `typescript eslint plugin's rules and config`
