### ISSUE TITLE
eslint --init SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by PossibleLlama** [eslint/eslint#13572]
**Tell us about your environment**

* **ESLint Version:** 7.7.0
* **Node Version:** 8.10.0
* **npm Version:** 6.14.7

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{}
```
None.

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
npm i eslint --save-dev && ./node_modules/.bin/eslint --init
```

**What did you expect to happen?**
Initialise ESLint, probably create config file and add scripts.

**What actually happened? Please include the actual, raw output from ESLint.**
```text
./node_modules/.bin/eslint --init
/home/project/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Are you willing to submit a pull request to fix this bug?**

**Comment by anikethsaha** [comment]
Thanks for the report. 

Please update your node version. May be to `12.x.x` ! We don't support `v8`

**Comment by PossibleLlama** [comment]
Thanks for that. Updating the node version worked.

**Comment by kopkaa** [comment]
> Thanks for the report.
> 
> Please update your node version. May be to `12.x.x` ! We don't support `v8`

Have the same problem, from what node version eslint works ? I have to use node version 6.

**Comment by mdjermanovic** [comment]
Hi @kopkaa!

ESLint v7 supports the following Node versions:

https://github.com/eslint/eslint/blob/4255f360a9e107dd34fb7bf4f4e0e6a8d340abb6/package.json#L144-L146
