### ISSUE TITLE
Custom parser by file extension

### ISSUE THREAD

**Issue by MentalGear** [eslint/eslint#13591]
Feat request: Would it be possible to add custom parser by file extension, instead of in general ?

**Comment by mdjermanovic** [comment]
Could [overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) solve the problem:

```js
module.exports = {
  overrides: [
    {
      files: ["**/*.ts"],
      parser: "@typescript-eslint/parser",
    }
  ]
};
```

**Comment by kaicataldo** [comment]
This is the intended use of overrides! Going to go ahead and close this since this is a feature we already support.
