### ISSUE TITLE
eslint fix return non-success error code when files were modified

### ISSUE THREAD

**Issue by ssbarnea** [eslint/eslint#13601]
Like other code formatters (black), when files are modified a different exit code should be returned.

In order to keep backwards compatibility this feature should be triggered by another command line option and/or a configuration item.

The entire idea is to ease integration in automation workflows and tell user that the tested code was not already conformant. 

A common similar approach is to perform a git dirty check after the run and to return error code. Still this approach is problematic because it does not fix well into npm configs, as it would require shell scripting `eslint ... && git diff-index --quiet --cached HEAD --`.

Due to this is much better to enable `eslint --fix ...` itself to return zero only when everything was fine and files were not modified.

**Comment by ssbarnea** [comment]
It indicates that the original code was not ok. Yes, running again would likely return a success, but only because it will not have to change anything.

You can think about it from a different point of view: the main action of the tool is "linting" (as part of its name). Fixing formatting is an optional service on top, one that would likely be needed only if linting fails. The final outcome is supposed to represent the state of the codebase before the tool run, not after.

Take a look at [--check](https://github.com/psf/black) option from black, this may be another way to implement the desired functionality.

PS. Obviously that exit code should be different between a runtime failure and a reformatting occurred.

**Comment by jasonkarns** [comment]
Strong agree, here. If any files were in need of being modified, then that indicates that the source was _non-compliant_ when invoking eslint. And as a linter, eslint's job should be to report "error" whenever the source is non-compliant to the project's lint and formatting ruleset.

**Comment by jasonkarns** [comment]
There has been prior interest in this feature as indicated by: https://github.com/eslint/eslint/issues/10099
