### ISSUE TITLE
ESLint documentation generation

### ISSUE THREAD

**Issue by jonathanKingston** [eslint/eslint#1363]
The docs suggest this should still work: http://eslint.org/docs/developer-guide/development-environment.html

I tried running:
`npm run docs`

Which should have generated the docs into the jsdoc directory however nothing was produced and make file threw nothing to stdout.

I tried adding in the bindings into package.json to link the run scripts with no immediate avail as other doc files were breaking the generation:
```
Generating documentation
js: "/usr/local/lib/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: cannot create a doclet for the comment "/**     * Gets a number of tokens that precede a given node's tokens in the token stream.     * @param {ASTNode} node The AST node.     * @param {int} [beforeCount=0] The number of tokens before the node to retrieve.     * @returns {[Token]} Array of objects representing tokens.     */": unable to parse the type expression "[Token]": Expected "!", "$", "(", "*", "...", "?", "Function", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter or Unicode uppercase letter but "[" found.
```

I suspect the following tasks should be done:

- [ ] Add tests to make sure the functionality stays, testing both the output and the command both looks the right shape.
- [ ] Spin up a simple web head to run the docs in the browser
- [ ] Get the functionality generating the doc files again into `jsdoc` directory

Eslint version: 0.6.2 installed from master.
Willing to resolve this issue.

**Comment by nzakas** [comment]
Wow, totally lost track of this. Unless anyone wants to take this on, I'd favor closing this issue.

**Comment by gcochard** [comment]
I think it would be a much smaller barrier to entry for new contributors if there were up to date API docs.

It looks like that jsdoc error is due to the `[Token]` syntax, when it should be `Token[]` instead, with `Token` documented earlier. I will investigate getting this working again.

**Comment by nzakas** [comment]
Working on this.

**Comment by nzakas** [comment]
I'm just working on getting JSDoc generated right now. I don't think spinning up a server is necessary when people can open the file in the directory.

**Comment by gcochard** [comment]
Why not just add the api docs to the eslint.org site?

**Comment by nzakas** [comment]
The JSDoc would need a lot more cleanup before that can be done. I'd like to do it eventually, we're just not quite ready for that yet.

**Comment by jonathanKingston** [comment]
:+1: Thanks @nzakas sorry about not responding at all.
