### ISSUE TITLE
Season of Docs: Reorganize/Rewrite Configuration Documentation

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#13632]
The ESLint team is excited to be working with @khawarlatifkhan for Google's Season of Docs 2020! @kaicataldo will be acting as mentor and the main point of contact for this project.

## Workflow

To allow for a comprehensive overhaul, @khawarlatifkhan will be working off of a feature branch of his fork, where he will make PRs that will be reviewed by @kaicataldo (and others, if they are interested). Any changes made to the upstream configuration documentation during this process will be incorporated into this feature branch. Once the documentation overhaul is completed, a PR will be created upstream, at which time feedback from the rest of the team and community can be given through our standard PR review process.

We have decided to specifically focus on the content for this project. Any website asset changes will be scoped to incorporating changes to the documentation (i.e. the table of contents). Once the content overhaul is complete, the ESLint team can look at the design of this page and update it as we see fit.

### Community bonding phase (August 17 - September 13, 2020)

- [x] Discuss proposal and develop game plan for the coming months.
- [x] Get more comfortable with Node, ESLint, Git, GitHub, and Markdown by making small documentation PRs and working with @kaicataldo.

### Doc development phase (September 14, 2020 - November 30, 2020)

- [x] Content audit - comprehensive content audit of the configuration documentation.
- [x] Create Information Architecture (IA) - focus on presenting the knowledge network in a way that is understandable. This will then help in making improvements to the flow of information.
- [x] Links and reference - analyze the IA during this phase to map out links and references between various sections of the documentation. Create a hierarchy of all sections, improving the IA in the process.
- [x] Create final map with the help of insights gained through content audit and IA. This comprehensive map will contain a table of contents, a hierarchy of topics, and a list of links and cross-references between sections of the documentation.
- [x] Present findings and get feedback from the ESLint team.
- [x] Rewrite and edit existing documentation - edit and update based on the information listed above. The focus in this phase will be to ensure that the documentation is accurate, updated, flexible, and reusable. This will be done on a feature branch where individual PRs will be reviewed by @kaicataldo.
- [x] Make PR to upstream and get feedback from the team/community.
- [x] Merge the PR and release!

### Project finalization
- [x] Final project report and tie up loose ends.

**Comment by khawarlatifkhan** [comment]
![Proposed IA v3  ESLint Configuration](https://user-images.githubusercontent.com/66240534/96328267-8e928480-105a-11eb-8eab-1b7c3a9e3533.png)

Based on the findings of a comprehensive content audit and after the identification of some gaps in the current Information Architecture (IA), we've developed a new IA for ESLint Configuration Documentation. Please see the attached graphic.

**Comment by nzakas** [comment]
Looks like we forgot to update the issue. We haven't completed this task and huge thanks to @khawarlatifkhan for all of his work!
