### ISSUE TITLE
Feature request: [no-shadow] It would really help, if the error message would show where the original identifier has been defined

### ISSUE THREAD

**Issue by doberkofler** [eslint/eslint#13646]
**What rule do you want to change?**
no-shadow

**Does this change cause the rule to produce more or fewer warnings?**
The same

**How will the change be implemented? (New option, new default behavior, etc.)?**
Just a change in the error message

**Please provide some example code that this change will affect:**

In my experience, the `no-shadow` rule could greatly benefit from an error message that also describes where the identifier has already been defined and not only where the redefinition has occurred.

```js
var a = 3;
function b() {
    var a = 10;
}
```

**What does the rule currently do for this code?**

The error `3:9 - 'a' is already declared in the upper scope. (no-shadow)` explains that `a` has already be declared somewhere but not exactly where the original declaration has been made.

**What will the rule do after it's changed?**

An improved error like `3:9 - 'a' is already declared in the upper scope 1:5. (no-shadow)` would additionally inform that the original definition is in line 1 column 5 and greatly improved the experience.

**Are you willing to submit a pull request to implement this change?**
Not sure if I have the required skills.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `ESLint`                           | `7.8.0` |
| `node`                             | `14.8.0` |

**Comment by anikethsaha** [comment]
Thanks for the issue


Make sense to me.

**Comment by mdjermanovic** [comment]
Makes sense to me, too. I'll champion this.

**Comment by t-mangoe** [comment]
I have worked on this issue.
I will open pull request, if you like, please check and review my codes.

**Comment by btmills** [comment]
This is a nice improvement :+1: marking as accepted since this has support from three team members including a champion.
