### ISSUE TITLE
Parsing error with hexadecimal literals that have underscores

### ISSUE THREAD

**Issue by ImUrX** [eslint/eslint#13652]
**Tell us about your environment**
Node version: v14.0.0
npm version: v6.14.4
Local ESLint version: v7.8.0
Global ESLint version: v7.8.1 (Currently used)

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
None

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
/* eslint-env node */
module.exports = {
    "env": {
        "es2020": true,
        "browser": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
0x0000_ffff_ffff_0000;
```

```bash
eslint .
```

**What did you expect to happen?**
No error to happen

**What actually happened? Please include the actual, raw output from ESLint.**
C:\Users\uri\Desktop\enchcracker\www\js\index.js
  14:57  error  Parsing error: Identifier directly after number

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by kaicataldo** [comment]
HI there! Numeric separators require settings `parserOptions.ecmaVersion: 2021` (it looks like you have `2020` currently set in your config).

**Comment by ImUrX** [comment]
Wew, you are right, i was trying to figure out if it ended up being in es2020 or es2021 but couldn't remember the name of the proposal. Thanks!
