### ISSUE TITLE
Breaking: define an `exports` field for our public API

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#13654]
**The version of ESLint you are using.**

Latest

**The problem you want to solve.**

Downstream packages rely on ESLint's internal modules, and removing/altering these modules can cause breakages in the ecosystem (example [here](https://github.com/sarbbottam/eslint-find-rules/issues/331)). A lot of thought has gone into what is and isn't our public API (defined [here](https://github.com/eslint/eslint#semantic-versioning-policy)), but it would be great to be able to enforce that downstream packages don't rely on these modules, since treating every module in our codebase as public isn't practical and would make it extremely difficult to refactor or do feature work.

To be clear, I don't think that our current strategy of defining our public API and then treating all other modules as "private" is an uncommon practice, but I do think this small change could prevent some instances of this from happening in the future.

**Your take on the correct solution to problem.**

As suggested [here](https://github.com/eslint/eslint/pull/13613#issuecomment-684975848), I would like to propose that we define an `exports` field to **a)** clearly document what we consider our public API from an importable module standpoint, and **b)** prevent those using more recent versions of Node.js from importing internal modules not intended for public consumption. For older versions of Node.js, `main` (which we have defined) would be used as a fallback. You can find more details in the  [Node.js Package Entry Points docs](https://nodejs.org/api/esm.html#esm_package_entry_points).

**Are you willing to submit a pull request to implement this change?**

Absolutely!

**Comment by ljharb** [comment]
When adding this, you can use `npx ls-exports path .` to verify what exports you're exposing. This can be used to add the field in a nonbreaking way right now as well.

Either way, I'd be happy to review any change around this field for correctness (node 13.0 and 13.1, if supported, require extra consideration in the format, as do a few non-latest minors in 12 and 14); please feel free to ping me.

**Comment by nzakas** [comment]
@kaicataldo Did you mean to link to here?
https://nodejs.org/api/packages.html. The link in the description is to the ESM Docs.

This seems like a simple enough change to prevent any further misunderstandings about what is and isn’t a public API.

**Comment by kaicataldo** [comment]
> @kaicataldo Did you mean to link to here?
https://nodejs.org/api/packages.html. The link in the description is to the ESM Docs.

That's right - looks like the docs were moved.

**Comment by ljharb** [comment]
Note as well that all my complaints about breaking changes in non-majors from renaming internal files would go away if internal things were excluded from "exports" :-) (or at least, change to feature requests to expose them explicitly)

**Comment by nzakas** [comment]
**TSC Summary:** This proposal seeks to add an `exports` field to `package.json` that specifically identifies which files are part of the public API. Despite our consistently saying people should not be accessing files directly in the `eslint` package, people still are, and then complain when we make a change. For new Node.js versions, including `exports` would ensure our internal file structure isn't exposed publicly.

**TSC Question:** Shall we accept this proposal and add it to the public roadmap (for v8.0.0).

**Comment by btmills** [comment]
In the 2020-10-08 TSC meeting, we accepted this as a semver-major change for the v8.0.0 release. I've added it to our public roadmap. The next step is for someone to write an RFC outlining which endpoints we need to expose and hopefully identifying which packages currently import private API that will be affected by this change. As we start working on v8.0.0, we can mention this change in a blog post to give those packages plenty of notice.

**Comment by ljharb** [comment]
@btmills once the choices are made, I’d be happy to volunteer to write the PR to implement it.

**Comment by btmills** [comment]
We’d like to include this in our upcoming v8.0.0 release if possible. The next step is to write an [RFC](https://github.com/eslint/rfcs) specifying which portions of our API we want to expose via `exports`. Is anybody interested in contributing that? The team would be happy to answer questions along the way.

**Comment by ljharb** [comment]
Once the list of entrypoints exists, i will still happily make the PR to define them.

**Comment by bradzacher** [comment]
worth noting that @typescript-eslint does a bunch of deep, direct importing of rules so that we can define extension rules. Which I'd assume this change would break?

We could technically go via the root import - but I thought it was nicer to restrict the footprint of the import. Probably makes no difference though as ESLint should have already been `require`d and initialised by the time our rules are imported.

**Comment by ljharb** [comment]
"each rule" could still be on the list of entrypoints; that seems like a reasonably safe thing to expose to me.

**Comment by nzakas** [comment]
> worth noting that @typescript-eslint does a bunch of deep, direct importing of rules so that we can define extension rules. Which I'd assume this change would break?

Yes. This is exactly what we didn’t want people to do. Rules are explicitly not part of the public API because subtle changes could break people expecting them to stay the same. We can’t guarantee that every rule will continue to work in the way you’re expecting. 

> “ each rule" could still be on the list of entrypoints; that seems like a reasonably safe thing to expose to me.

Not at all safe. Simple example: we may remove a rule in the future. We can’t be painted into a corner because a plugin is relying on ESLint to provide that rule.

We explicitly state on our [public API](https://eslint.org/docs/developer-guide/nodejs-api):

> Use undocumented parts of the API at your own risk. Only those parts that are specifically mentioned in this document are approved for use and will remain stable and reliable. Anything left undocumented is unstable and may change or be removed at any point.

**Comment by bradzacher** [comment]
@nzakas Yes, of course.

To clarify: we are not asking, nor will we ever we asked ESLint core to maintain a stable internal folder structure for private files, nor do we want ESLint core to keep all rules around indefinitely.

We understand the risks and maintain relatively tight version ranges to mitigate them, and if a user encounters a risk we update and handle it accordingly.

We ensure to handle backwards and forwards compatibility as appropriate, as we know it is not part of ESLint's API surface, nor is it ESLint's responsibility.

**Comment by ljharb** [comment]
How could removing a rule ever be non-breaking?

**Comment by nzakas** [comment]
@ljharb fair point. Perhaps a bad example. My overall point remains, though, that we do not guarantee any APIs that aren’t documented and their interfaces or locations may change at any time without warning and outside of a major release.

@bradzacher thanks. 👍 I’d suggest just copying over any rules you want to reference.

**Comment by ljharb** [comment]
Right. But rule names and existence are already guaranteed - so it seems like zero additional maintenance cost to also guarantee the rule file entry points, especially since the likelihood these will change in a non-major is effectively zero.

**Comment by nzakas** [comment]
@ljharb as I’ve already said, it’s not just existence that has to be guaranteed if rules are public — the entire interface needs to be guaranteed, which means everything in meta, whether the rule is fixable, the object returned from `create()`, etc. We have run into such issues before, which is part of why we adopted the stance that anything undocumented is not part of the API. We need the flexibility to be able to change how rules are implemented whenever we want. (Remember, the preferred rule format already changed once from functions to objects.)

**Comment by ljharb** [comment]
Gotcha - so with no official method of rule composition, not exporting the rule objects is removing that capability from the ecosystem. That seems like a high cost to avoid the worst case of having placeholder files sitting around with a “todo, remove on semver-major”, but certainly it’s your call to make.

**Comment by walkerburgin** [comment]
I'm guessing this would also impact https://github.com/microsoft/rushstack/tree/master/stack/eslint-patch? (related to https://github.com/eslint/eslint/issues/3458)

**Comment by walkerburgin** [comment]
@nzakas it looks like `@rushstack/eslint-patch` works by reaching in and importing what I assume are ESLint package internals ([here](https://github.com/microsoft/rushstack/blob/master/stack/eslint-patch/src/modern-module-resolution.ts#L27-L41)) that wouldn't be accessible after this change. I'm not affiliated with Rush, but we use this package so that we can ship a self contained lint configuration to over a thousand packages internally. For what it's worth, we use PNPM as our package manager (and actually used Yarn for years before that), so https://github.com/eslint/eslint/issues/3458 is still relevant for us at least.

In the abstract I definitely support making the API surface area clear and well defined. I'm just noting that I think this would cause issues for us with the way things stand right now, unless I'm misunderstanding something.

**Comment by bradzacher** [comment]
note - this should not have been closed yet.

**Comment by btmills** [comment]
Thanks for catching this @bradzacher, looks like automation got excited. Reopening and re-adding to project boards.
