### ISSUE TITLE
Getting a lot of "Parsing error: Unexpected token"

### ISSUE THREAD

**Issue by joshxyzhimself** [eslint/eslint#13662]
Please see https://github.com/microsoft/vscode/issues/106190

Anyone also encountering this?

**Comment by mdjermanovic** [comment]
Hi @joshxyzhimself!

I believe that upgrading `babel-eslint` to the latest version (which is now [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser)) would solve this problem.

If it doesn't help, can you please run eslint from the command line so we could see the error stack trace, and then fill out the bug report template?

**Comment by joshxyzhimself** [comment]
Oh god that worked!

It also became way way smoother and less laggy now.

Thank you very much @mdjermanovic!!!! :100:
