### ISSUE TITLE
Output more rule durations with TIMING environment variable

### ISSUE THREAD

**Issue by bmish** [eslint/eslint#13671]
**The version of ESLint you are using.**

Latest 7.8.1.

**The problem you want to solve.**

**Context**: The [per-rule performance](https://eslint.org/docs/1.0.0/developer-guide/working-with-rules#per-rule-performance-3) numbers outputted by running `TIMING=1 eslint` are very useful to me, especially because I have a large codebase (thousands of JS files) and hundreds of eslint rules (from eslint core and many plugins) enabled. Running linting takes 5-10 minutes for me, so I use this information to consider which rules I should target for performance optimizations.

**Problem**: This list only shows the top 10 longest-running rules and their durations. Given that I have hundreds of rules enabled, this severely and unnecessarily limits the usefulness of this feature for me.

**Your take on the correct solution to problem.**

Several ideas:

1. Get rid of the limit entirely (remove `.slice(0, 10)`).
2. Increase the limit substantially to at least 100.
3. Make the limit configurable using the existing `TIMING` environment variable by changing it from a boolean to an integer (in a backwards-compatible way).
   * `TIMING=1`: show the first 10 (due to minimum of 10)
   * `TIMING=5`: show the first 10 (due to minimum of 10)
   * `TIMING=10`: show the first 10
   * `TIMING=15`: show the first 15
   * `TIMING=100`: show the first 100
4. Make the limit configurable using a new `TIMING_LIMIT` integer environment variable.

**Are you willing to submit a pull request to implement this change?**

Yes, all of the proposed solutions would be trivial to implement, and I could implement the preferred solution promptly.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

It does make sense to me to have some kind of configurable approach to change the limit. maybe `4` can be suitable. 

_this is needs a [RFC](https://github.com/eslint/rfcs) to implement first. But it can be discussed here before moving to RFC if there is interest about this from others_

**Comment by mdjermanovic** [comment]
I support this! Just not sure about the details.

If we want a backward-compatible change, then `1` and `2` wouldn't fit, and `3` is also questionable.

[Per-rule Performance](https://eslint.org/docs/developer-guide/working-with-rules#per-rule-performance-1) docs says "Setting the TIMING environment variable will trigger the display", but it isn't specific about the value, so it could be argued that any value should enable this feature, even though both examples have `TIMING=1`.

Also, it does work like that at the moment. Any non-empty value is truthy, so `0` or `100` works the same as `1`.

In addition, it might be confusing that `100` means `100` but `1` means `10`, and also `TIMING` might not be the best name for variable that takes a number.

Overall, a new environment variable might be the best choice, along with deprecating `TIMING` at some point?

**Comment by anikethsaha** [comment]
One more solution can be a one to the one time-limit with the `TIMING` env itself. 

That is `TIMING=0` is do not show
`TIMING=1` would be the first rule
`TIMING=7` would be the first 7  rule

and so on. This would be a breaking change I think. 

having `TIMING_LIMIT` and keeping the work of `TIMING` as it is can be a good solution as well. It wouldn't be a breaking change IMO.

**Comment by bmish** [comment]
It sounds like my proposed solutions `3` and `4` are currently favored. I can put together an RFC once we settle on a decision.

My top preference is solution `3` which could be considered the most elegant since it doesn't add any extra environment variables. Note that I would keep the output list to a minimum of 10 rules to avoid causing a breaking change, and because there's not much reason to shorten the list beyond that.

If we went with `4`, I would leave the existing `TIMING` variable alone (not deprecate it), since most people probably don't care about setting a specific limit.

**Comment by mdjermanovic** [comment]
`TIMING=0` in the actual version also shows 10 rules. `TIMING=-1`, `TIMING=true`, `TIMING=false`, `TIMING=foo` all show 10 rules as well.

If we choose the solution `3`, maybe we could `parseInt()`or `Number()` the value, and show 10 rules if it produces anything other than a number greater than 10. Then, the only difference would be if someone already has  `TIMING=11` or above, so we could discuss whether or not that constitutes a breaking change.

**Comment by bmish** [comment]
@mdjermanovic sounds good, I put up a PR #13679 to demonstrate this potential change. I personally don't think this should be considered a breaking change, as I'm not sure why anyone would be using a large integer as the value for this environment variable.

**Comment by anikethsaha** [comment]
IMO, It won't be a breaking change. Cause in the docs, it is not mentioned to use any value other than `1` so even if anyone is using `11` or greater, it will give different output but it was never mentioned by the docs to use so. 

Also, should this go through RFC? though it looks like a non-breaking change but this change is related to the core.

**Comment by mdjermanovic** [comment]
I think this should go through the RFC process. It might be a small change in the code at the end, but it is related to the core and it isn't entirely clear whether it is a non-breaking change.

@bmish feel free to create an RFC :)

**Comment by bmish** [comment]
Opened RFC: https://github.com/eslint/rfcs/pull/66

Note that I am still okay with either solution (reusing the `TIMING` env variable, or adding a new `TIMING_LIMIT` env variable).
