### ISSUE TITLE
Tagged Template Literals Trigger no-undef rule.

### ISSUE THREAD

**Issue by stephenhurleyjpl** [eslint/eslint#13676]
### eslint --env-info
```
Node version: v14.9.0
npm version: v6.14.7
Local ESLint version: v7.8.1 (Currently used)
Global ESLint version: Not found
```

### yarn list | grep eslint

```
├─ @eslint/eslintrc@0.1.3
├─ eslint-config-standard@14.1.1
├─ eslint-import-resolver-node@0.3.4
├─ eslint-module-utils@2.6.0
├─ eslint-plugin-es@3.0.1
│  ├─ eslint-utils@^2.0.0
├─ eslint-plugin-import@2.22.0
│  ├─ eslint-import-resolver-node@^0.3.3
│  ├─ eslint-module-utils@^2.6.0
├─ eslint-plugin-node@11.1.0
│  ├─ eslint-plugin-es@^3.0.0
│  ├─ eslint-utils@^2.0.0
├─ eslint-plugin-promise@4.2.1
├─ eslint-plugin-standard@4.0.1
├─ eslint-scope@4.0.3
├─ eslint-utils@2.1.0
│  └─ eslint-visitor-keys@^1.1.0
├─ eslint-visitor-keys@1.3.0
├─ eslint@7.8.1
│  ├─ @eslint/eslintrc@^0.1.3
│  ├─ eslint-scope@^5.1.0
│  ├─ eslint-scope@5.1.0
│  ├─ eslint-utils@^2.1.0
│  ├─ eslint-visitor-keys@^1.3.0
│  └─ eslint-visitor-keys@^1.3.0
│  ├─ eslint-scope@^4.0.3
```

### .eslintrc

```
{
	"extends": [
		"standard",
		"plugin:import/errors",
		"plugin:import/warnings"
	],
	"parserOptions": {
		"ecmaFeatures": {
			"modules": true
		}
	},
	"rules": {
		"brace-style": ["error", "stroustrup"],
		"indent": ["error", "tab", { "SwitchCase": 1 }],
		"no-tabs": ["off"],
		"operator-linebreak": ["error", "before"],
		"semi": ["error", "always"],
		"space-before-function-paren": ["error", {
			"anonymous": "always",
			"asyncArrow": "always",
			"named": "never"
		}]
	},
	"env": {
		"browser": true
	}
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
glsl``;
```

I am using the VSCode ESLint 2.1.8 extension to run ESLint.

**What did you expect to happen?**

No linting errors.

**What actually happened? Please include the actual, raw output from ESLint.**

`glsl` is squiggled and when hovering over it, the tooltip reports an error:
```
'glsl' is not defined.eslint
no-undef
```

**Are you willing to submit a pull request to fix this bug?**

I'm not familiar with the code enough, but I might be up to the task.

** Other notes **

I figure there are three options:
* I'm just configuring something wrong (most likely).
* no-undef needs to be modified to handle tagged template literals.
* an option to no-undef needs to be added to make tagged template literals exempt.

**Comment by anikethsaha** [comment]
Thanks for the report. 

from the code snippet you shared, it is working as intended. is `glsl` defined in the same scope?

**Comment by stephenhurleyjpl** [comment]
You know what? From you comment, I think I understand. I'm using the glsl as a helper for a VSCode extension (glsl-literal), and I forgot exactly how tagged template literals work. My test code is equivalent to ```glsl(``);```, which is of course undefined (nothing else is in the file). I'll close this, as this was just me not understanding tagged template literals fully. Thanks :)
