### ISSUE TITLE
Feature Request: re-enable global installs 

### ISSUE THREAD

**Issue by wesbos** [eslint/eslint#13685]
Just upgraded from ESLint 6.x to  7.8.1 and I've noticed that it no longer allows for global installs.

I know we should be installing this for every project, and I am, but I _really_ liked the ability to have my code linted if I just created a quick `.js` file anywhere on my computer.

Previously I had it setup that most of my projects would have a local ESLint, but if I wanted to whip up a quick demo (several times a day for me), it would still lint my code. 

So - maybe I'm not finding how to do this with 7, but from [this thread](https://github.com/wesbos/eslint-config-wesbos/issues/53) it seems that feature was removed.

Could we have this added back in? Or is there another way we can get the benefit without having to do the whole install song-and-dance when I'm editing a 20 line .js file? 

Thanks a lot :)

**Comment by anikethsaha** [comment]
Thanks for the issue.

Does [`--config`](https://eslint.org/docs/user-guide/command-line-interface#-c-config) flag for the CLI helps here?

**Comment by wesbos** [comment]
Is it possible to have that dynamically look it up? The way I use it is via the eslint vs code plugin, it looks for a local install and if not it goes for the global install.

**Comment by mdjermanovic** [comment]
> Is it possible to have that dynamically look it up?

Yes, ESLint looks for configuration files in ancestor directories.

Plugins, configs ("extends"), and external parsers will be resolved from the location of the configuration file.

**Comment by wesbos** [comment]
@mdjermanovic thanks for the reply - that is how it worked in 6.0, but with 7.0, it finds the config, but can't find any globally installed plugins or extends. See this thread for a list of people who have it globally installed, with a global .eslint, but get the "couldn't find the config XXX to extend from"

https://github.com/wesbos/eslint-config-wesbos/issues/53

**Comment by mdjermanovic** [comment]
As of 6.0, ESLint doesn't support globally installed plugins and globally installed shareable configs. Please find more details here:

https://eslint.org/docs/user-guide/migrating-to-6.0.0#plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location

In 7.0 we changed only plugin resolution (which can be actually helpful for this use case):

https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-resolution-has-been-updated

It's still possible to have an ESLint config file in an ancestor directory, but plugins, shareable configs and external parsers should be installed from that directory (i.e. in `./node_modules` of that directory).

**Comment by wesbos** [comment]
hmm, so you are saying nothing broke? Because my global plugins and configs works great on 6.0 and it stopped working on 7.0 (same with the whole list of people on that issue).

> It's still possible to have an ESLint config file in an ancestor directory, but plugins, shareable configs and external parsers should be installed from that directory (i.e. in ./node_modules of that directory).

yes, so this means if you have a global eslint and config it is no longer works, right?  Are we able to reinstate that functionality?

**Comment by mdjermanovic** [comment]
> hmm, so you are saying nothing broke? Because my global plugins and configs works great on 6.0 and it stopped working on 7.0 (same with the whole list of people on that issue).

The same error from the original issue `ESLint couldn't find the config "wesbos" to extend from` should appear with ESLint 6 if `eslint-config-wesbos` cannot be resolved from the location of `.eslintrc` (e.g., if `eslint-config-wesbos` was installed globally).

This was an intentional change made in ESLint 6.0.0, per https://github.com/eslint/rfcs/pull/7.

I'm not sure what's the best way to check which version of ESLint was loaded by the vscode eslint plugin, but you can try with `eslint -v` from the command line. Loading globally installed shareable configs isn't supposed to work since ESLint 6.0.0.
 
> > It's still possible to have an ESLint config file in an ancestor directory, but plugins, shareable configs and external parsers should be installed from that directory (i.e. in ./node_modules of that directory).
> 
> yes, so this means if you have a global eslint and config it is no longer works, right? Are we able to reinstate that functionality?

It isn't likely that ESLint will support globally installed configs and plugins, for the reasons described in https://github.com/eslint/rfcs/pull/7.

**Comment by ljharb** [comment]
@wesbos could you not have a package.json and node_modules in .eslintrc, rather than globally installing? As long as individual projects remember to add `"root": true` to their eslintrc, that would govern anything in your home dir *except* individual projects.

**Comment by wesbos** [comment]
@ljharb So if I'm following, I could install it in `~` and then in my `~./eslintrc` I could tell it where to resolve the node_modules and package.json folder?

Then on each project for a "local" install, I just add root: true to the eslintrc?

**Comment by ljharb** [comment]
> I could tell it where to resolve the node_modules and package.json folder?
i wasn't thinking this, i was thinking it'd be `~/package.json` and `~/node_modules`.

Then yes, on any project that has an eslint config, you'd add root: true (which it should have anyways) so that your homedir config didn't interfere.

**Comment by itstheandre** [comment]
Hey there! Just jumping on this issue :)
@ljharb so we can do a normla npm install in the root folder of our computer and, if no eslint is installed locally on a folder , eslint will go up the folder structure until it ultimately finds the .eslintrc ?
this way we don't have a global install, but rather having a `package.json` and `node_modules` in our root folder is this it?

**Comment by ljharb** [comment]
@itstheandre yes (altho that's not a good idea for a number of reasons, it would at least provide for this use case)

**Comment by nzakas** [comment]
Closing as we don’t plan on making a change for this issue.

**Comment by JestDotty** [comment]
I found a solution that's pretty nifty. There's so many threads so I don't know where to post it (primarily because the most active threads were locked, lol) but:

I have a `projects` folder with all my projects in it, and a `.eslintrc.js` file with `root: true`. I just `npm i`'ed my plugins into that folder. Seems to work as expected.

![image](https://user-images.githubusercontent.com/4729968/96387574-15398580-1171-11eb-9270-54f4e791825b.png)
