### ISSUE TITLE
Enhancement of 'no-else-return' rule

### ISSUE THREAD

**Issue by kmdrGroch** [eslint/eslint#13693]
**What rule do you want to change?**
no-else-return

**Does this change cause the rule to produce more or fewer warnings?**
more

**How will the change be implemented? (New option, new default behavior, etc.)?**
adding some options / extension to this rule.

**Please provide some example code that this change will affect:**

```js
if(something) {
   throw new Error();
} else {
  return true;
}
---
if(something) {
   throw new Error();
}
return true;
```
```js
if(something) {
  return 1;
} else if(sthMore) {
  return 2;
}
---
if(something) {
  return 1;
}
if(sthMore) {
  return 2;
}
```
```js
if(something) {
  return 1;
} else {
  throw new Error();
}
---
if(something) {
  return 1;
}
throw new Error();
```

**What does the rule currently do for this code?**
it does sometimes work for the last case. it doesn't change `if else` statements.

**What will the rule do after it's changed?**
adds support for `Errors` - they 'work quite similar to returns'
adds support for `if else`

**Are you willing to submit a pull request to implement this change?**
unfortunatelly don't have time. Could help with some information

**Comment by kmdrGroch** [comment]
Side note: It seems it also does not work in some cases:
```js
  if (semver.satisfies(jestVersion, '<22.0.0')) {
    log.debug('Detected Jest below 22.0.0: %s', jestVersion);
    throw new Error('You need Jest version >= 22.0.0 to use Stryker');
  } else if (semver.satisfies(jestVersion, '<25.0.0')) {
    return injector.injectClass(JestLessThan25TestAdapter);
  } else {
    return injector.injectClass(JestGreaterThan25TestAdapter);
  }
```
shows no error

**Comment by anikethsaha** [comment]
Thanks for the issue. 

> adds support for Errors - they 'work quite similar to returns'

IMO, it is out of scope for this rule, this is to check for `return` statements alone. 

> adds support for if else

Do you mean about [this](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZWxzZS1yZXR1cm46IFtcImVycm9yXCIsIHthbGxvd0Vsc2VJZjogZmFsc2V9XSovXG5cblxuZnVuY3Rpb24gaCgpe1xuaWYoc29tZXRoaW5nKSB7XG4gIHJldHVybiAxO1xufSBlbHNlIGlmKHN0aE1vcmUpIHtcbiAgcmV0dXJuIDI7XG59XG59XG5cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) ?

**Comment by kmdrGroch** [comment]
hmmm it seems it doesn't work in some cases, or with Typescript itself

**Comment by kmdrGroch** [comment]
function h(){
if(something) {
  throw new Error();
} else if(sthMore) {
  return 2;
}
}
it seems to not be working

**Comment by anikethsaha** [comment]
> hmmm it seems it doesn't work in some cases, or with Typescript itself

We dont support typescript in core rules. Please use [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) for config and plugins



> ```js
> function h(){
> if(something) {
>   throw new Error();
> } else if(sthMore) {
>   return 2;
> }
> }
> ```
> 
> it seems to not be working

because this rule is not about `throw` statements. as per the docs

> If an if block contains a return statement, the else block becomes unnecessary. Its contents can be placed outside of the block.

So even if there is an interest to support `throw`, IMO it has to be in a separate new rule.

**Comment by bconnorwhite** [comment]
The inverse of this would be really great. 

Ex:

Error:
```
if(a) {
  return 1;
}
if(b) {
  return 2;
}
return 3;
```
Correct:
```
if(something) {
  return 1;
} else if(sthMore) {
  return 2;
} else {
  return 3;
}
```
