### ISSUE TITLE
Improve no-func-assign docs and add tests

### ISSUE THREAD

**Issue by bendtherules** [eslint/eslint#13705]
**Tell us about your environment**

Eslint demo page with Eslint v7.9.0 - [Demo URL](https://eslint.org/demo#eyJ0ZXh0IjoidmFyIGEgPSBmdW5jdGlvbiBoZWxsbygpIHtcbiAgJ3VzZSBzdHJpY3QnO1xuICBoZWxsbyA9IDEyMztcbn07XG5hKCkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWltcG9ydC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)

* **ESLint Version:** v7.9.0
* **Node Version:** Doesn't matter (web hosted)
* **npm Version:** Doesn't matter (web hosted)

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** - default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "constructor-super": 2,
        "for-direction": 2,
        "getter-return": 2,
        "no-async-promise-executor": 2,
        "no-case-declarations": 2,
        "no-class-assign": 2,
        "no-compare-neg-zero": 2,
        "no-cond-assign": 2,
        "no-const-assign": 2,
        "no-constant-condition": 2,
        "no-control-regex": 2,
        "no-debugger": 2,
        "no-delete-var": 2,
        "no-dupe-args": 2,
        "no-dupe-class-members": 2,
        "no-dupe-else-if": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-empty": 2,
        "no-empty-character-class": 2,
        "no-empty-pattern": 2,
        "no-ex-assign": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-semi": 2,
        "no-fallthrough": 2,
        "no-global-assign": 2,
        "no-import-assign": 2,
        "no-inner-declarations": 2,
        "no-invalid-regexp": 2,
        "no-irregular-whitespace": 2,
        "no-misleading-character-class": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-new-symbol": 2,
        "no-obj-calls": 2,
        "no-octal": 2,
        "no-prototype-builtins": 2,
        "no-redeclare": 2,
        "no-regex-spaces": 2,
        "no-self-assign": 2,
        "no-setter-return": 2,
        "no-shadow-restricted-names": 2,
        "no-sparse-arrays": 2,
        "no-this-before-super": 2,
        "no-undef": 2,
        "no-unexpected-multiline": 2,
        "no-unreachable": 2,
        "no-unsafe-finally": 2,
        "no-unsafe-negation": 2,
        "no-unused-labels": 2,
        "no-unused-vars": 2,
        "no-useless-catch": 2,
        "no-useless-escape": 2,
        "no-with": 2,
        "require-yield": 2,
        "use-isnan": 2,
        "valid-typeof": 2
    },
    "env": {}
}
```

Only actual change from default config is - disabled "no-func-assign"

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var a = function hello() {
  'use strict';
  hello = 123; // should throw error here
};
a()
```

Ran demo web version - [Demo URL](https://eslint.org/demo#eyJ0ZXh0IjoidmFyIGEgPSBmdW5jdGlvbiBoZWxsbygpIHtcbiAgJ3VzZSBzdHJpY3QnO1xuICBoZWxsbyA9IDEyMztcbn07XG5hKCkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWltcG9ydC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)

**What did you expect to happen?**

I have disabled "no-func-assign" rule.  
On the line "hello = 123" within named function expression, this will always throw a runtime JS error saying `TypeError: Assignment to constant variable`. That means, this is a assignment to a (implicitly created) immutable binding for the function name "hello". "no-const-assign" rule should also catch this error, irrespective of "no-func-assign" - because this is a const reassignment.

The [spec says](https://tc39.es/ecma262/#sec-function-definitions-runtime-semantics-evaluation) that for named function expressions, there is a implicitly created extra scope above the function local scope which has immutable binding for funcName = funcObject. So, this means -

A. This code should not be allowed

```
var a = function hello() {
  'use strict';
  hello = 123; // reassign const
};
```

B. but this should be allowed -

```
var a = function hello() {
  'use strict';
  const hello = 123; // creates new const
};
```

**What actually happened? Please include the actual, raw output from ESLint.**

No lint error or warning (lint-free)

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by anikethsaha** [comment]
Thanks for the issue. 

IMO, this is out of the scope of this rule. This rule checks for the `const` variables alone. 
According to the rule's docs

>  Disallow modifying variables that are declared using `const` (no-const-assign)

[no-func-assign](https://eslint.org/docs/rules/no-func-assign) does catches the same. 

Let me know if I am missing something.

**Comment by bendtherules** [comment]
I understand your point about the scope - that it is only supposed to catch const s declared explicitly by the user.

But what about the ones implicitly created by the language? This is one such example. Is there any other rule for that? 

Also no-func-assign might be moved to warning in some configs, because it alone does not cause a error. 
On the other hand, this example always throws a error.

**Comment by bendtherules** [comment]
Ok, i take back my words. 
Seems like in all other implicitly immutable cases (class name, imported var) - it shows a specific error instead of no-const-assign.

Only suggestion in that case is to add more strict words to no-func-assign doc saying that it can throw error also, not just a clean code issue

**Comment by anikethsaha** [comment]
Yeah, I think there can be some more effective docs as an example similar to the one you shared.

**Comment by mdjermanovic** [comment]
> Only suggestion in that case is to add more strict words to no-func-assign doc saying that it can throw error also, not just a clean code issue

Sounds good to me!

Marked as an accepted issue to improve documentation for `no-func-assign`. In particular, to add named function expressions.

The actual document doesn't even mention named function expressions and doesn't have any examples with them. Also, there are no test cases, so it's possible that the original intention was to check only function declarations:

> This rule disallows reassigning function declarations.

Either way, this rule checks function expressions from the start (v0.0.9), this behavior does make sense, so we should update the docs to reflect the actual behavior.

**Comment by mdjermanovic** [comment]
@bendtherules would you like to submit a pull request to improve documentation for `no-func-assign`?

**Comment by bendtherules** [comment]
Yes, i would like to add the pr. But it will probably take some time.
If someone would like to pick it up quickly, i am good with that 👍

**Comment by snitin315** [comment]
@beaugunderson can I send a PR if you haven't already started working on this one?

**Comment by bendtherules** [comment]
Feel free to pick it up. I have not done any work on this. (in case you meant to ask me)

**Comment by bendtherules** [comment]
While the PR adds a example of incorrect code, i think the whole scope is not holistically covered. 

1. The description text should say that in some case, this will actually cause a error and is not just a styling thing.
2. Add tests

Can we reopen this? (can't see button)

**Comment by mdjermanovic** [comment]
We added an example in https://github.com/eslint/eslint/pull/13777, and a test in https://github.com/eslint/eslint/pull/13783.

@bendtherules I agree that the docs and the tests can be further improved, feel free to submit a PR!

**Comment by bendtherules** [comment]
Ahh, i missed the tests pr. Then it looks better, maybe some text can be changed in the description is all. I'll try to raise a pr for this.
