### ISSUE TITLE
also lint <script> code insde html files

### ISSUE THREAD

**Issue by nektro** [eslint/eslint#13700]
**The version of ESLint you are using.**
`v6.8.0`

**The problem you want to solve.**
Javascript code inside of `<script>` tags in `.html` files is not linted.

**Your take on the correct solution to problem.**
Do linting it.

**Are you willing to submit a pull request to implement this change?**
Am unfamiliar with `eslint` internals.

**Comment by mdjermanovic** [comment]
Thanks for the issue!

You can use [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) to lint code inside `<script>` tags.

After installing the plugin and configuring `"plugins": ["html"]`, just add `.html` to the list of extensions when you run eslint.

For example:

```bash
npx eslint . --ext .js,.html
```

**Comment by nektro** [comment]
Thanks! That worked perfectly.

**Comment by btmills** [comment]
Closing since this has a resolution.
