### ISSUE TITLE
Please help us getting ESLint 7 support landed for testing-library & create-react-app

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint/eslint#13702]
Hi team! 👋

I would like to ask if you guys could help us out in getting mysticatea/eslint-utils#7 merged.
I already tried contacting @mysticatea in a lot of different ways, but I haven't heard from him since July 16th when he said he would have a look at it the weekend after.

I know OSS relies on the maintainer of the packages and I'm super grateful for all the packages @mysticatea's maintaining, but this PR is blocking (at least) 7 other packages to be able to get ESLint 7 support without any problems.
The most important ones are [`eslint-plugin-testing-library`](https://github.com/testing-library/eslint-plugin-testing-library/pull/139) & [`eslint-config-react-app`](https://github.com/facebook/create-react-app/pull/8963).
![](https://user-images.githubusercontent.com/6643991/93669328-c1fde580-fa93-11ea-96e1-2fdcbbb5ea57.png)

Since @mysticatea seems to be the only person who can publish the package, we're thinking about publishing a fork if this isn't resolved within a week or two.
If the @eslint team is willing to take over the package and publish it yourself (since it's a generic enough package) that would be awesome, but we're also willing to take ownership of the package if necessary.

Hopefully we can get this sorted out and we can enjoy all the lovely packages.

Thanks for helping us out! 👊

CC all people involved in the depending PRs: @Belco90 @iansu @ianschmitz @kentcdodds @mrmckeb @nickmccurdy

**Comment by mdjermanovic** [comment]
Hi @MichaelDeBoey, thanks for the issue! 

Can you please provide more details about what problems is the actual version of `eslint-utils` causing for other packages? What exactly wouldn't work with `eslint-utils` v2.1.0?

**Comment by mdjermanovic** [comment]
@MichaelDeBoey thanks for your efforts to verify that a number of plugins work well with ESLint 7!

Still, I don't understand why is the set of plugins on the left side a blocker for the configs on the right side:

![image](https://user-images.githubusercontent.com/44349756/93708370-db576e00-fb35-11ea-9abb-374e39292ed8.png)
 
`eslint-plugin-node` and `eslint-plugin-promise` are here just [devDependencies](https://github.com/testing-library/eslint-plugin-testing-library/blob/a934cd78d64b8842535d522b40ce2539e987d518/package.json#L43) of `eslint-plugin-testing-library`?

**Comment by MichaelDeBoey** [comment]
@mdjermanovic After looking closer into your comment, I think we can indeed merge the `eslint-plugin-testing-library` PR (all tests are green) and release it without all other (dev)Dependencies being ESLint 7.x compatible 🙂

That being said: it would be lovely if you guys somehow could notice @mysticatea that there are still a some other packages waiting for mysticatea/eslint-utils#7, looking at the reactions I get on my pings

![](https://user-images.githubusercontent.com/6643991/93712661-8e848f00-fb57-11ea-83b2-27376a6b4b43.png)
![](https://user-images.githubusercontent.com/6643991/93712664-92b0ac80-fb57-11ea-9dd2-a2af29aa1a8c.png)
![](https://user-images.githubusercontent.com/6643991/93712673-9cd2ab00-fb57-11ea-9c6f-6b2a60befe3f.png)

**Comment by nzakas** [comment]
Just a reminder that this repo is for issues related directly to ESLint. It’s not appropriate to file issues here about a project we don’t maintain just because the maintainer also happens to maintain ESLint.
