### ISSUE TITLE
More documentation on conflicting fixes

### ISSUE THREAD

**Issue by RunDevelopment** [eslint/eslint#13721]
The [developer documentation about rules](https://eslint.org/docs/developer-guide/working-with-rules) (`docs/developer-guide/working-with-rules.md`) doesn't contain enough information about rules. This is a followup to eslint/website#791.

The following questions should be answered:

1. Q: When do fixes conflict?
    A: ["Conflicting fixes are fixes that would be applied to the same part of a string. So if two fixes want to modify characters 0 through 5, only one will be applied."](https://github.com/eslint/website/issues/791#issuecomment-700233043)
1. Q: If fixes conflict which one will be applied?
    A: [Fixes are not guaranteed to be applied.](https://github.com/eslint/website/issues/791#issuecomment-700233043) ESLint may choose to apply or not to apply any fix.
1. Q: Can the (rule) developer affect which one of the conflicting fixes is applied?
    A: [No.](https://github.com/eslint/website/issues/791#issuecomment-700233043)

**Are you willing to submit a pull request to implement this change?**
No. I'm not good at writing technical documentation.

**Comment by mdjermanovic** [comment]
Thanks for the issue!

I think `1.` and `3.` would be very useful, but not sure if we should document `2.`

> * Q: When do fixes conflict?
>   A: ["Conflicting fixes are fixes that would be applied to the same part of a string. So if two fixes want to modify characters 0 through 5, only one will be applied."](https://github.com/eslint/website/issues/791#issuecomment-700233043)

I agree that we should specify this. It's an important detail for cases like https://github.com/eslint/eslint/issues/13706 and the `i` flag example you described in https://github.com/eslint/website/issues/791#issuecomment-700278390.

> * Q: If fixes conflict which one will be applied?
>   A: [Fixes are not guaranteed to be applied.](https://github.com/eslint/website/issues/791#issuecomment-700233043) ESLint may choose to apply or not to apply any fix.

Would appreciate more opinions on this. Specifying these details might disallow further optimizations, like the one we made in https://github.com/eslint/eslint/pull/8035. On the other hand, rule developers should be aware of how this works when writing tests with overlapping ranges.

> * Q: Can the (rule) developer affect which one of the conflicting fixes is applied?
>   A: [No.](https://github.com/eslint/website/issues/791#issuecomment-700233043)

Make sense to document this.

**Comment by mdjermanovic** [comment]
Maybe I misunderstood the proposal for `2.`. Does it include details on which of the conflicting fixes will be chosen?

**Comment by RunDevelopment** [comment]
> Does it include details on which of the conflicting fixes will be chosen?

Yes. If two of my rules produce fixes that conflict, then I'd like to know which one is applied. 

I know that right now it's going to be the left-most fix after being sorted by [this function](https://github.com/eslint/eslint/blob/51674a4113a1ca877094606bbf4938ab06cc1aad/lib/linter/source-code-fixer.js#L26) but that very specific implementation detail probably shouldn't make it into the public doc. Explicitly stating that it's undefined behaviour in that context should suffice.

**Comment by mdjermanovic** [comment]
Reopening, as it seems useful to clarify this in the docs.

**Comment by arminyahya** [comment]
About `2.` can we add a few details about how it works?

@mdebruijne

**Comment by Gautam-Arora24** [comment]
Hi! Are we still interested to solve this issue?

**Comment by btmills** [comment]
The additional changes as currently described sound reasonable to me. Like others, I'd prefer to leave 2 as undefined behavior to avoid committing ourselves to a particular implementation.

**Comment by snitin315** [comment]
Marked as accepted since we have 3 👍🏻
