### ISSUE TITLE
Move no-multi-spaces to "stylistic issues" category

### ISSUE THREAD

**Issue by golopot** [eslint/eslint#13742]
This rule is very stylistic in my opinion.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

This does make sense but it would be a breaking change.

Also, please fill the issue template as it helps triaging better.

**Comment by nzakas** [comment]
@golopot can you more fully explain why you think that? One sentence isn't enough for us to properly evaluate your proposal.

**Comment by golopot** [comment]
1. Most of best practices rules involves non-whitespace problems, and fixing the problem changes the meaning of the program.

2. Most of whitespaces rules are in the stylistic issue category. For example, no-trailing-spaces, no-whitespace-before-property, and no-multiple-empty-lines.

3. If it is fixable by prettier. It is a stylistic issue.

**Comment by nzakas** [comment]
I forgot that we are planning on replacing these categories on the website:
https://github.com/eslint/eslint/issues/13398

@anikethsaha are you still planning on addressing that?

**Comment by anikethsaha** [comment]
As per what I recall, as the change mentioned in #13398 is a breaking change so we decided till then we will change only in the docs (in website alone). 

For the website change, I will try if possible in this weekend or next (stuck with online classes). 

And about changes in schema (breaking), should this be handled now or later?

**Comment by nzakas** [comment]
The resolution was to not making any changes to the rule categories at all and just to change how the website list was organized. The category field will eventually go away as we won’t be using it anymore.
