### ISSUE TITLE
when dealing template string came out such error :ESLint: Cannot read property 'value' of null Occurred while linting /path/to/file.js:43. Please see the 'ESLint' output channel for details.

### ISSUE THREAD

**Issue by rmGFW** [eslint/eslint#13750]
**Tell us about your environment**
macOS node -v === v14.2.0
eslint version is ^7.11.0

* **ESLint Version:7.11.0**
* **Node Version:14.2.0**
* **npm Version:6.14.4**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: ['@tencent/eslint-config-tencent'],
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by mdjermanovic** [comment]
Hi @rmGFW,

There is really not enough information, but I'd guess that upgrading `babel-eslint` to the latest version of [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) can fix this problem.

If that doesn't help, can you please fill out the bug report template?

**Comment by rmGFW** [comment]
sorry for omit information

1.eslint -v === 7.11.0
2.my eslint config is 
```js
module.exports = {
  // plugins: ['prettier'],
  // extends: ['prettier', '@tencent/eslint-config-tencent'],
  extends: ['@tencent/eslint-config-tencent'],
  // rules: {
  // 'prettier/prettier': 'error',
  // },
};
```
when I open my project on vim . get such error :ESLint: Cannot read property 'value' of null Occurred while linting /path/to/my/project/file.js:43. Please see the 'ESLint' output channel for details.

when I open my project on vscode .get such error 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/66858140/95801610-64c12100-0d2d-11eb-9d14-d64dcd8be6d5.png">

and if I run `npx eslint --fix path/to/file`
then come out 

Oops! Something went wrong! :(

ESLint: 7.11.0

TypeError: Cannot read property 'value' of null
  Occurred while linting /path/to/my/project/file.js:43
  at checkSpacingBefore (/path/to/my/project/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
at TemplateElement (/path/to/my/project/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
  at/path/to/my/projectnode_modules/eslint/lib/linter/safe-emitter.js:45:58
  at Array.forEach (<anonymous>)
  at Object.emit (/path/to/my/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
  at NodeEventGenerator.applySelector (/path/to/my/project/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
  at NodeEventGenerator.applySelectors (/path/to/my/project/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
  at NodeEventGenerator.enterNode (/path/to/my/project/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
at CodePathAnalyzer.enterNode (/path/to/my/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
  at /path/to/my/project/node_modules/eslint/lib/linter/linter.js:952:32

**Comment by rmGFW** [comment]
> Hi @rmGFW,
> 
> There is really not enough information, but I'd guess that upgrading `babel-eslint` to the latest version of [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) can fix this problem.
> 
> If that doesn't help, can you please fill out the bug report template?

my babel-eslint version is 10.1.0 .
I have update the babel-eslint but still can't fix that problem

I have finish fill out he template .thanks😃

**Comment by mdjermanovic** [comment]
This was a known issue with `babel-eslint` (https://github.com/babel/babel-eslint/issues/799).

> my babel-eslint version is 10.1.0 .
> I have update the babel-eslint but still can't fix that problem

You'll need to switch from `babel-eslint` to `@babel/eslint-parser`(it's a different package, successor of `babel-eslint`).

Please see https://babel.dev/blog/2020/07/13/the-state-of-babel-eslint#the-future for more details.
