### ISSUE TITLE
(spaced-comment) rule

### ISSUE THREAD

**Issue by cybermerlin** [eslint/eslint#13773]
hi. Sorry about this task, but I don't know what the plugin did this mark.
![image](https://user-images.githubusercontent.com/1460479/96566941-da4d6400-12ce-11eb-85fd-b56583e5e4a9.png)
![image](https://user-images.githubusercontent.com/1460479/96567370-5ba4f680-12cf-11eb-92a4-6e690031da11.png)

[eslint demo online](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICdzcGFjZWQtY29tbWVudCc6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHtcbiAgICAgIFwibGluZVwiOiB7IFwiZXhjZXB0aW9uc1wiOiBbXCJUT0RPOiBcIiwgXCIjXCIsIFwiQFwiLCBcInJlZ2lvblwiXSB9LFxuICAgICAgXCJibG9ja1wiOiB7IFwiZXhjZXB0aW9uc1wiOiBbXCJUT0RPOiBcIiwgXCIjXCIsIFwiQFwiLCBcInJlZ2lvblwiXSB9LFxuICAgICAgXCJleGNlcHRpb25zXCI6IFtcIlRPRE86IFwiLCBcIiNcIiwgXCJAXCIsIFwicmVnaW9uXCIsIFwiZW5kcmVnaW9uXCJdXG4gICAgfV1cbiovXG5cbi8vQHRzLWlnbm9yZVxubGV0IGRkID0gYW55O1xuXG4vLyBkZGRkXG5uZXcgU2VydmljZSh7IGF1dGhOYW1lOiAnczMtc2lnbmVyLWF1dGgnLCBvcGVuQVBJOiBzM1VybHNpZ25lciB9KTtcbi8vVE9ETzogYXNkZlxuY29uc29sZS5pbmZvKCdoZWxsbycpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJyZXF1aXJlLWF3YWl0IjoyLCJtdWx0aWxpbmUtdGVybmFyeSI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlfX19)

I use the latest versions of all things (typescript, eslint, eslint-plugin-prettier, vue.2).
My rule:
```
    'spaced-comment': ["error", "always", {
      "line": { "exceptions": ["TODO: ", "#", "@", "region"] },
      "block": { "exceptions": ["TODO: ", "#", "@", "region"] },
      "exceptions": ["TODO: ", "#", "@", "region", "endregion"]
    }],
```
------

**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by cybermerlin** [comment]
on this [page](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICdzcGFjZWQtY29tbWVudCc6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHtcbiAgICAgIFwibGluZVwiOiB7IFwiZXhjZXB0aW9uc1wiOiBbXCJUT0RPOiBcIiwgXCIjXCIsIFwiQFwiLCBcInJlZ2lvblwiXSB9LFxuICAgICAgXCJibG9ja1wiOiB7IFwiZXhjZXB0aW9uc1wiOiBbXCJUT0RPOiBcIiwgXCIjXCIsIFwiQFwiLCBcInJlZ2lvblwiXSB9LFxuICAgICAgXCJleGNlcHRpb25zXCI6IFtcIlRPRE86IFwiLCBcIiNcIiwgXCJAXCIsIFwicmVnaW9uXCIsIFwiZW5kcmVnaW9uXCJdXG4gICAgfV1cbiovXG5cbi8vQHRzLWlnbm9yZVxubGV0IGRkID0gYW55O1xuXG4vLyBkZGRkXG5uZXcgU2VydmljZSh7IGF1dGhOYW1lOiAnczMtc2lnbmVyLWF1dGgnLCBvcGVuQVBJOiBzM1VybHNpZ25lciB9KTtcbi8vVE9ETzogYXNkZlxuY29uc29sZS5pbmZvKCdoZWxsbycpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJyZXF1aXJlLWF3YWl0IjoyLCJtdWx0aWxpbmUtdGVybmFyeSI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlfX19), you can see all

**Comment by mdjermanovic** [comment]
@cybermerlin exceptions define patterns for the whole comment. From the docs (emphasis mine): 

> The "exceptions" value is an array of string patterns which are considered exceptions to the rule. The rule will not warn when the pattern starts from the beginning of the comment and __repeats until the end__ of the line or */ if the comment is a single line comment. Please note that exceptions are ignored if the first argument is "never".

You can define `"TODO:"` and `"@ts-ignore"` as markers, like in [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICdzcGFjZWQtY29tbWVudCc6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHsgICAgICBcbiAgICAgIFwibWFya2Vyc1wiOiBbXCJUT0RPOlwiLCBcIkB0cy1pZ25vcmVcIl1cbiAgICB9XVxuKi9cblxuLy9AdHMtaWdub3JlXG5sZXQgZGQgPSBhbnk7XG5cbi8vIGRkZGRcbm5ldyBTZXJ2aWNlKHsgYXV0aE5hbWU6ICdzMy1zaWduZXItYXV0aCcsIG9wZW5BUEk6IHMzVXJsc2lnbmVyIH0pO1xuLy9UT0RPOiBhc2RmXG5jb25zb2xlLmluZm8oJ2hlbGxvJyk7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InJlcXVpcmUtYXdhaXQiOjIsIm11bHRpbGluZS10ZXJuYXJ5IjoyfSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=).
