### ISSUE TITLE
Add option to semi to require semi colons after arrow function definitions in class body.

### ISSUE THREAD

**Issue by sirmspencer** [eslint/eslint#13781]
**What rule do you want to change?**
semi / no-extra-semi

**Does this change cause the rule to produce more or fewer warnings?**
More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
Please add the option to require use of semi colons after class arrow function definitions in `semi` or require no semi colon in `no-extra-semi`. 

The main thing is that either way, there is no ESLint rule that produces consistency in the code wrt to semi colons after class arrow functions. Here is the ECMAS definition for class body.  I can make sense of this either way wrt arrow functions in the class body. http://www.ecma-international.org/ecma-262/11.0/index.html#prod-ClassBody

**Please provide some example code that this change will affect:**

```js
class Project extends React.Component {

    constructor() {
    } // Require no semi colon in no-extra-semi (current)

    lifeCycle() {
    } // Require no semi colon in no-extra-semi (current)

    withoutSemi() {
    }  // Require no semi colon in no-extra-semi (current)

    withSemiArrow = () => {
    }; // Optional require semi colon in semi (requested)

    withoutSemiArrow = () => {
    } // Optional require semi colon in no-extra-semi (requested)

} // Require no semi colon in no-extra-semi (current)
```

**What does the rule currently do for this code?**
semi add semi colons in many place.  no-extra-semi removes them in many places.

**Are you willing to submit a pull request to implement this change?**
Im not sure I would have the knowledge how.

**Comment by ljharb** [comment]
Class fields are stage 3; when they're stage 4 (or when eslint decides to support things that browsers already ship), I would expect the normal `semi` rule to cover them.

**Comment by sirmspencer** [comment]
> Class fields are stage 3; when they're stage 4 (or when eslint decides to support things that browsers already ship), I would expect the normal `semi` rule to cover them.

If the normal semi rule "should" cover them, then this is a bug report.  The current semi does not add semi colons to my class arrow functions.

**Comment by ljharb** [comment]
At this time, it shouldn't, because eslint doesn't support stage 3 features.

**Comment by mdjermanovic** [comment]
@sirmspencer thanks for the issue!

All core rules will be updated to support this syntax when class fields proposal reaches stage 4, per our [policy about experimental features](https://github.com/eslint/eslint#what-about-experimental-features).

In the meantime you can use [@babel/semi](https://github.com/babel/babel/tree/main/eslint/babel-eslint-plugin#rules) rule from `@babel/eslint-plugin`, instead of the core `semi` rule.

**Comment by sirmspencer** [comment]
> @sirmspencer thanks for the issue!
> 
> All core rules will be updated to support this syntax when class fields proposal reaches stage 4, per our [policy about experimental features](https://github.com/eslint/eslint#what-about-experimental-features).
> 
> In the meantime you can use [@babel/semi](https://github.com/babel/babel/tree/main/eslint/babel-eslint-plugin#rules) rule from `@babel/eslint-plugin`, instead of the core `semi` rule.

Thank you so much. The @babel/eslint-plugin works great for what I need.
