### ISSUE TITLE
Error with os-specific directory separators when using parserOptions.project

### ISSUE THREAD

**Issue by qucumbah** [eslint/eslint#13786]
**Tell us about your environment**

* **ESLint Version:** 7.12.0
* **Node Version:** 14.8.0
* **npm Version:** 6.14.7

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: 'c:/code/game/src/main.ts',
  },
  plugins: [
    '@typescript-eslint',
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'airbnb-typescript',
  ],
  rules: {
    'import/prefer-default-export': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',

    'no-console': 'off',
  },
};
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "game",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "webpack --config webpack.config.js",
    "start": "webpack-dev-server --config webpack.config.js --host 0.0.0.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.4.1",
    "@typescript-eslint/parser": "^4.5.0",
    "copy-webpack-plugin": "^6.2.1",
    "electron": "^10.1.4",
    "eslint": "^7.12.0",
    "eslint-config-airbnb-typescript": "^12.0.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.3",
    "eslint-plugin-react-hooks": "^4.0.8",
    "ts-loader": "^8.0.6",
    "typescript": "^4.0.3",
    "webpack": "^5.2.0",
    "webpack-cli": "3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "pixi.js": "^5.3.3"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// Happens to every .ts file in codebase
```

```bash
npx eslint . --ext .ts
```

**What did you expect to happen?** Linting

**What actually happened? Please include the actual, raw output from ESLint.**
```
C:\Code\game\src\engine.ts
  0:0  error  Parsing error: Debug Failure. Expected c:/code/game/src/main.ts === c:\code\game\src\main.ts

C:\Code\game\src\main.ts
  0:0  error  Parsing error: Debug Failure. Expected c:/code/game/src/main.ts === c:\code\game\src\main.ts

... (same for every .ts file)
```
**Are you willing to submit a pull request to fix this bug?** No

**Comment by mdjermanovic** [comment]
Hi @qucumbah, thanks for the bug report!

Does this happen with ESLint 7.11.0, too?

**Comment by qucumbah** [comment]
Yes

**Comment by mdjermanovic** [comment]
Thanks for that info!

This seems to be directly related to `@typescript-eslint/parser`. I don't think ESLint is doing anything with `parserOptions.project` other than just passing it to the parser.

Can you please open an issue in the typescript-eslint repository:

https://github.com/typescript-eslint/typescript-eslint

I'll leave this issue open for the case that it turns out that it is related to ESLint itself.

**Comment by qucumbah** [comment]
New issue in case you want to track it:
https://github.com/typescript-eslint/typescript-eslint/issues/2705

**Comment by yeonjuan** [comment]
Hi @qucumbah  :)
I will close the issue because it was found to be a wrong configuration problem (https://github.com/typescript-eslint/typescript-eslint/issues/2705#issuecomment-715988066).
Please comment if there is anything we missed.

cc. @mdjermanovic
