### ISSUE TITLE
ES lint is not replacing double quotes with single quotes - possible edge case?

### ISSUE THREAD

**Issue by 123aswin123** [eslint/eslint#13784]
**Tell us about your environment**

* **ESLint Version:**
``` Javascript
"devDependencies": {
    "eslint": "^7.11.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^6.13.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.1.2"
  }
```
* **Node Version:** `v14.13.1`
* **npm Version:** `6.14.8`

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
  env: {
    node: true,
    es6: true,
  },
  extends: ['airbnb-base' , 'plugin:prettier/recommended'],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  rules: {
    // to allow console.log in code
    'no-console': 'off',
  },
};


```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
console.log("Hello World");
```

```bash
npx eslint --fix .
```

**What did you expect to happen?**
The airbnb style guide defaults to single quotes in strings. However when I run `npx eslint --fix .` I expect the double quotes to be replaced by single quotes.

**What actually happened? Please include the actual, raw output from ESLint.**

The double quotes were not replaced to single quotes, but when I did ~`['airbnb-base' , 'plugin:prettier/recommended']`~ `['airbnb-base']`, `npx eslint --fix .`, it fixed my double quotes to single quotes. The `plugin:prettier/recommended` isn't playing well with `airbnb-base`

``` bash
[Info  - 11:00:16 p.m.] ESLint server is starting
[Info  - 11:00:16 p.m.] ESLint server running in node v12.14.1
[Info  - 11:00:16 p.m.] ESLint server is running.
[Info  - 11:00:20 p.m.] ESLint library loaded from:
```

**Are you willing to submit a pull request to fix this bug?**
Yes, with some guidance, noob to the project!

**Comment by mdjermanovic** [comment]
Hi @123aswin123, thanks for the issue!

`plugin:prettier/recommended` config disables all ESLint's layout rules (incl. `quotes`), in order to avoid conflicts with prettier.

If you prefer single quotes, you can re-configure the `prettier/prettier` rule:

```json
{
  "rules": {    
    "prettier/prettier": ["error", { "singleQuote": true }]
  }
}
```

You can also re-enable the `quotes` rule, since it additionally checks template literals (`prettier/prettier` doesn't):

```json
{
  "rules": {    
    "prettier/prettier": ["error", { "singleQuote": true }],
    "quotes": ["error", "single", { "avoidEscape": true }]
  }
}
```

**Comment by 123aswin123** [comment]
Thanks for your clarification.
