### ISSUE TITLE
Enable getting config array from outside of ESLint

### ISSUE THREAD

**Issue by voxpelli** [eslint/eslint#13802]
**The version of ESLint you are using.**

`master`

**The problem you want to solve.**

I want to solve the problem highlighted in #5116:

I want to be able to retrieve all rule collections that are in use and highlight which ones that duplicates/overrides which other ones.

_Reason:_

I want to make a tool that helps me highlight possible duplicated rules between my own defined rules and new rules introduced by new versions of plugins or entirely new plugins. See eg: https://github.com/voxpelli/eslint-config/blob/692e9342bafca7cd6b6d15399d5addd3e671d1bc/eslintrc.json#L10-L17

I eg. want to ensure that with the release of Standard 16, that I remove redundant rules from my rule set, like eg. the addition of `no-var` to Standard 16.

I also want to be notified if eg. Standard and Unicorn starts to have different opinions on things, because then I maybe want to opt in to the Standards way rather than the Unicorn way, but right now it is hard to tell if new version will cause such issues.

**Your take on the correct solution to problem.**

Currently the official API to use to get the config for a file is: `ESLint#calculateConfigForFile()`

The legacy API for doing the same is the one suggested in #5116: `CLIEngine#getConfigForFile()`

What would be needed to solve this: A new method (eg. `ESLint#getConfigArrayForFile()`) replicating `CLIEngine#getConfigForFile()`, but instead returning the raw array from `configArrayFactory.getConfigArrayForFile(absolutePath)` rather than continuing and running additional methods on it:

https://github.com/eslint/eslint/blob/a1a9d14f11b409fba9117a101480153a0085e2a9/lib/cli-engine/cli-engine.js#L951-L954

**Are you willing to submit a pull request to implement this change?**

I can do a PR if the API is of interest.

**Comment by nzakas** [comment]
Sorry this fell through the cracks. We are currently in the process of switching over to a new config system (see #13481), so we aren't going to be adding any new APIs related to the current config system.

I'm not sure I completely understand what you'd like to accomplish with this. Can you walk me through what the algorithm would look like for the new method you're suggesting?
