### ISSUE TITLE
eslint --init should offer to save custom configs

### ISSUE THREAD

**Issue by tscpp** [eslint/eslint#13803]
**The version of ESLint you are using.**
v7.12.1

**The problem you want to solve.**
Copy/paste a config I want for all of my projects.

**Your take on the correct solution to the problem.**
`eslint --init` should offer an option to use a saved configuration.

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by anikethsaha** [comment]
Thanks for the issue. 

Please give some more details about this. Though it does looks like a interesting feature. 


Also, it needs an RFC to implement this. But we can discuss here before.

**Comment by tscpp** [comment]
You could use `eslint --init-save-preset [preset_name]` to save presets (config files).
And use `eslint --init-load-preset [preset_name]` to load presets.

**Comment by nzakas** [comment]
I think this is an interesting idea, I’m just not sure how practical it is. I don’t think we want to add a bunch of new command line flags for something people only do once in a while. I could see something like a config file in your home directory that specifies additional config names to use with --init. 

Would like to hear what others think.

**Comment by anikethsaha** [comment]
I think options like `eslint --init save <ref-name>` and `eslint --init load <ref-name>` and then in a json file, we can map the generate config content with the `ref-name` and use that to retrieve and save.
Another way I think can be to copy-paste the generated file in some global config .

**Comment by tscpp** [comment]
The idea of this issue was not to have to copy/paste. Your idea is quite amazing with the saving and loading of refs.

**Comment by nzakas** [comment]
**TSC Summary:** This proposal seeks to allow a way to save custom configs to be selected as part of `--init`. This would involve a way to specify which configs to include and then display them when `--init` is used. This would require an RFC before implementation.

**TSC Question:** Shall we accept this proposal?

**Comment by btmills** [comment]
@tcppp, thank you for taking time to contribute to ESLint with this suggestion! We talked about it in today's TSC meeting. Because `--init` is often used by developers who are new to ESLint or once at the start of a new project, we try to avoid having too many moving parts. Since this has a copy/paste alternative solution, we decided not to add this feature.
