### ISSUE TITLE
Customize tab length (for max-len rule)

### ISSUE THREAD

**Issue by Luifr** [eslint/eslint#13825]
**What rule do you want to change?**

Identation and/or max-len

**Does this change cause the rule to produce more or fewer warnings?**

fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

new option (probably on ident)

**Please provide some example code that this change will affect:**

If a have a max-len set to 100, the following line would give an error saying the length is 104, but it has only 26 characters (26 tabs, each one counting 4 characters)
I would like to be able to customize this to 2 characters for exemple

```js
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t
```

**What will the rule do after it's changed?**

i will be able to customize how many characters a tab counts toward the lenght of each line (max-len)

**Are you willing to submit a pull request to implement this change?**

yes!

**Comment by mdjermanovic** [comment]
Hi @Luifr, thanks for the issue!

> i will be able to customize how many characters a tab counts toward the lenght of each line (max-len)

I think this option already exists in the [max-len](https://eslint.org/docs/rules/max-len) rule:

> "tabWidth" (default 4) specifies the character width for tab characters

**Comment by Luifr** [comment]
Yes! That was what i was looking for, thank you @mdjermanovic
