### ISSUE TITLE
[one-var] Autofixing this rule drops some exported vars

### ISSUE THREAD

**Issue by scinos** [eslint/eslint#13834]
**Tell us about your environment**

Can be reproduced in [Eslint demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgb25lLXZhcjogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG4vKmVzbGludC1lbnYgZXM2Ki9cblxuZXhwb3J0IGNvbnN0IGZvbz0xLCBiYXI9MjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

Check how 'Fixed code' doesn't export both consts.

**What did you do?**

```js
/*eslint one-var: ["error", "never"]*/
/*eslint-env es6*/

export const foo=1, bar=2;
```

**What did you expect to happen?**
I expect the rule to be autofixed to 

```js
/*eslint one-var: ["error", "never"]*/
/*eslint-env es6*/

export const foo=1; export const bar=2;
```
I.e. both const are exported.

**What actually happened?**

Only the first const is exported:

```js
/*eslint one-var: ["error", "never"]*/
/*eslint-env es6*/

export const foo=1; const bar=2;
```

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by mdjermanovic** [comment]
Hi @scinos, thanks for the bug report!

I can confirm this in [online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgb25lLXZhcjogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG4vKmVzbGludC1lbnYgZXM2Ki9cblxuZXhwb3J0IGNvbnN0IGZvbz0xLCBiYXI9MjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=), PR is welcome.

**Comment by anikethsaha** [comment]
@scinos are you planning to work on this ? 
Else I can submit a PR.

**Comment by scinos** [comment]
I haven't had time lately, and I don't think I will have in the near future.

All yours :)
