### ISSUE TITLE
ESList: cannot find module

### ISSUE THREAD

**Issue by allan2coder** [eslint/eslint#13847]
ESList: cannot find module occur in my vs code
`
ESLint: Cannot find module '/Users/MyApp/node_modules/esquery/esquery.js'. Please verify that the package.json has a valid "main" entry. Please see the 'ESLint' output channel for details.
`
and i found `esquery` in package-lock.json config as following:
```
"eslint": {
      "version": "6.8.0",
      "resolved": "http://nodepackages.hellobike.cn:4873/eslint/-/eslint-6.8.0.tgz",
      "integrity": "sha1-YiYtZylzn5J1cjgkMC+yJ8jJP/s=",
      "dev": true,
      "requires": {
        "@babel/code-frame": "^7.0.0",
        "ajv": "^6.10.0",
        "chalk": "^2.1.0",
        "cross-spawn": "^6.0.5",
        "debug": "^4.0.1",
        "doctrine": "^3.0.0",
        "eslint-scope": "^5.0.0",
        "eslint-utils": "^1.4.3",
        "eslint-visitor-keys": "^1.1.0",
        "espree": "^6.1.2",
        "esquery": "^1.0.1", // here it is
        ...
}
```
![image](https://user-images.githubusercontent.com/14307551/99222653-f5ec5180-281d-11eb-9861-ae99a141c10c.png)

**Comment by mdjermanovic** [comment]
Hi @allan2coder, thanks for the issue!

Can you please check `"main"` and `"version"` fields in `node_modules/esquery/package.json`? Also, is there `node_modules/esquery/esquery.js` file or  `node_modules/esquery/dist/` directory.

**Comment by allan2coder** [comment]
I have checked.
