### ISSUE TITLE
Cannot find module eslint-plugin-react/lib/options

### ISSUE THREAD

**Issue by AntonTaran** [eslint/eslint#13858]
Please help. Eslint cannot find module  eslint-plugin-react/lib/options, but they're no "options" directory

![image](https://user-images.githubusercontent.com/15983496/99402132-ae36fa00-28f1-11eb-949b-a211dada59de.png)

![image](https://user-images.githubusercontent.com/15983496/99398416-0f100380-28ed-11eb-9aba-1d7ef2b2e8ba.png)

![image](https://user-images.githubusercontent.com/15983496/99401749-3668cf80-28f1-11eb-9bc8-1f4a39f8d7ee.png)

![image](https://user-images.githubusercontent.com/15983496/99401791-42549180-28f1-11eb-90af-eb020349c275.png)

**Comment by AntonTaran** [comment]
My issue NOT related to the rules. It just doesn't work because it can't find eslint-plugin-react. It installed but doesn't have directory "options".

Please take a look at the screens above.

Eslint version 7.2.0

Configuration :

{
  "plugins": [
    "@typescript-eslint",
    "babel",
    "react",
    "import",
    "prettier",
    "jest",
    "jsx-a11y",
    "react-hooks",
    "react-i18n",
    "testing-library",
    "jest-dom"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:jsx-a11y/recommended",
    "prettier",
    "prettier/react",
    "prettier/@typescript-eslint",
    "plugin:import/recommended",
    "plugin:import/typescript",
    "plugin:testing-library/recommended",
    "plugin:testing-library/react",
    "plugin:jest-dom/recommended"
  ],
  "parserOptions": {
    "ecmaVersion": 10,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "node": true,
    "es6": true,
    "commonjs": true,
    "jest": true,
    "jest/globals": true,
    "browser": true
  },
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"],
      "babel-eslint": [".js", ".jsx"]
    },
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true,
        "directory": ["."]
      }
    }
  },
  "globals": {
    "__dirname": false,
    "require": false,
    "document": false,
    "$": false,
    "console": false,
    "module": false
  },
  "rules": {
    "no-console": ["warn", { "allow": ["warn", "error"] }],
    "default-case": "warn",
    "default-case-last": "warn",
    "no-alert": "warn",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-implicit-coercion": "warn",
    "no-implied-eval": "error",
    "no-param-reassign": "error",
    "no-with": "error",
    "no-unneeded-ternary": "warn",
    "prefer-arrow-callback": ["warn", { "allowNamedFunctions": true }],
    "prefer-const": "warn",
    "prefer-destructuring": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "no-useless-return": "warn",
    "eqeqeq": "warn",
    "no-restricted-syntax": [
      "warn",
      {
        "selector": ":matches(ImportDefaultSpecifier[local.name='React'])",
        "message": "Use namespace (wildcard) import for React: `import * as React from 'react'`."
      },
      {
        "selector": ":matches(ImportDeclaration[source.value='@client-core/ui'])",
        "message": "'@client-core/ui' is deprecated. Please use '@material-ui' instead."
      },
      {
        "selector": ":matches(ImportDeclaration[source.value='epic-ui-toolkit'])",
        "message": "'epic-ui-toolkit' is deprecated. Please use '@material-ui' instead."
      },
      {
        "selector": ":matches(ImportDeclaration[source.value='moment'])",
        "message": "'moment' is deprecated and will be removed from project. Please use native date or 'date-fns' instead."
      }
    ],

    "react/destructuring-assignment": ["warn", "always"],
    "react/prop-types": "off",
    "react/forbid-prop-types": "off",
    "react/function-component-definition": ["warn", { "namedComponents": "arrow-function" }],
    "react/no-danger": "warn",
    "react/jsx-no-target-blank": "warn",
    "react-hooks/rules-of-hooks": "error",
    "react/display-name": "warn",

    "react-i18n/no-dynamic-translation-keys": [
      "warn",
      {
        "functionNames": ["t", "translate", "localize"]
      }
    ],

    "import/no-useless-path-segments": "warn",
    "import/no-deprecated": "warn",
    "import/no-unresolved": "off", // Fix weird build error in epic-twinmotion
    "import/newline-after-import": "warn",
    "import/order": "warn",
    "import/first": "error",
    "import/extensions": [
      "error",
      "never",
      {
        "json": "always",
        "css": "always",
        "pcss": "always",
        "jpg": "always",
        "png": "always",
        "svg": "always"
      }
    ],
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.stories.js",
          "**/*.stories.tsx",
          "**/*.images.js",
          "**/*.test.js",
          "**/*.test.ts",
          "**/*.test.tsx",
          "**/__tests__/**",
          "**/__storybook__/**"
        ]
      }
    ],

    "@typescript-eslint/no-inferrable-types": [
      "warn",
      { "ignoreParameters": true, "ignoreProperties": true }
    ],
    "@typescript-eslint/ban-types": "warn",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/no-unused-vars": ["error", { "args": "none" }],
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-use-before-define": ["error", { "functions": false, "classes": false }],
    "@typescript-eslint/ban-ts-comment": "warn",
    "@typescript-eslint/no-unused-expressions": [
      "error",
      { "allowShortCircuit": true, "allowTernary": true }
    ],

    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/label-has-for": "off",
    "jsx-a11y/anchor-is-valid": "off",

    "testing-library/await-async-query": "error",
    "testing-library/no-await-sync-query": "error",
    "testing-library/no-debug": "warn",

    "jest-dom/prefer-checked": "error",
    "jest-dom/prefer-enabled-disabled": "error",
    "jest-dom/prefer-required": "error",
    "jest-dom/prefer-to-have-attribute": "error"
  }
}

**Comment by mdjermanovic** [comment]
By the discussion in https://github.com/yannickcr/eslint-plugin-react/issues/2859 it seems that upgrading ESLint to the latest version fixed the problem, so I'm closing this issue here. @AntonTaran if that isn't the case, please let me know so we could reopen the issue.
