### ISSUE TITLE
--debug doesn't show debug info from @eslint/eslintrc

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#13850]
**The version of ESLint you are using.**

7.13.0

**The problem you want to solve.**

`eslint --debug` doesn't show debug info from `@eslint/eslintrc`, ref https://github.com/eslint/eslint/issues/13848.

Namely, `eslintrc:cascading-config-array-factory` and `eslintrc:config-array-factory`.

This info used to be printed when the modules were in `eslint/eslint`.

**Your take on the correct solution to problem.**

Either change these to `eslint:` in `eslint/eslintrc`, or add `eslintrc:*` here:

https://github.com/eslint/eslint/blob/37a06d633d3669f0f43236141dc43465b8bc7ec5/bin/eslint.js#L17

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by nzakas** [comment]
Makes sense. I think the right approach is to update the code in `bin/eslint.js` to include `eslintrc:*`.
