### ISSUE TITLE
Enable Top Level Await

### ISSUE THREAD

**Issue by richardsimko** [eslint/eslint#13870]
Please describe what the rule should do:
Provide a setting or rule that enables top level await in code without an error or warning.

As this is now a part of node 14.x+ I'm asking you to reopen/reconsider #13178 even if it's not a Stage 4 feature yet. At the very least so that eslint is able to parse files with top-level awaits without triggering a parser error.

**Comment by janosh** [comment]
Update: Besides node, top-level `await` has also just been added to the [Chromium engine Blink](https://v8.dev/blog/v8-release-89).
