### ISSUE TITLE
Turn off complexity for switch statement.

### ISSUE THREAD

**Issue by wsakaria-mdsol** [eslint/eslint#13881]
**What rule do you want to change?**
I'd like to see a option within the `complexity` rule whereby things like switch statement are omitted. This is because we have a lot of switch statements, for example, in our redux reducers and also in utlis files for feature tests.

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option. 

`"complexity": ["error", { "max": 5 }, { "ignoredClauses": ["caseClause"] }]`

**Please provide some example code that this change will affect:**
**What does the rule currently do for this code?**
**What will the rule do after it's changed?**

`switch (field) {
   case "1":
      someCode
      break
   case "2":
      someCode
      break
   case "3":
      someCode
      break
   case "4":
      someCode
      break
   default:
      someCode
}`

For example here if my complexity is set to 3 this will throw a error. Whereby this statement is actually considered to be of good/decent quality.

I'd like switch statements to be ignored.

**Are you willing to submit a pull request to implement this change?**

I'll give it a try.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

IMO, I would increase the `max` option or disable the line as limit should be same across the codebase .

Lets see if there is interest from others.

**Comment by mdjermanovic** [comment]
This rule aims to work per the definition of [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) as stated in the [documentation](https://eslint.org/docs/rules/complexity), so I think adding options to change this behavior doesn't make sense.

For a different metric you can make a custom rule or use plugin rules like [sonarjs/cognitive-complexity](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md).

**Comment by wsakaria-mdsol** [comment]
Fair enough, there are other patterns to use, so we can use them and disable in other areas. 

Thanks!
