### ISSUE TITLE
Gitlab Code Quality formatter

### ISSUE THREAD

**Issue by AlexLisenkov** [eslint/eslint#13886]
**The version of ESLint you are using.**
Latest

**The problem you want to solve.**
Feature request for Gitlab Code Quality cli formatter.
https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool

**Are you willing to submit a pull request to implement this change?**
Yes. Will take me some time to do so as it will be my fist change and also need to find some time.

**Comment by nzakas** [comment]
Thanks for the suggestion. We're not adding any more formatters to the core of ESLint, but you can always [create your own](https://eslint.org/docs/developer-guide/working-with-custom-formatters).
