### ISSUE TITLE
"multiline-ternary" assumes "operator-linebreak"  is not set to "before"

### ISSUE THREAD

**Issue by mbalc** [eslint/eslint#13887]
**Tell us about your environment**

* **ESLint Version:     `"eslint": "7.10.0",`**
* **Node Version: `    "node": "14.15.0",`**
* **npm Version: `"npm": "6.14.8",`**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?:
`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended"
  ],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly",
    "IS_DEV": "readonly"
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "react",
    "react-hooks",
    "only-warn"
  ],
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/resolver": {
      "alias": {
        "map": [
          [
            "~",
            "./src/"
          ]
        ],
        "extensions": [
          ".ts",
          ".js",
          ".tsx",
          ".jsx"
        ]
      }
    }
  },
  "ignorePatterns": "functions/lib/index.*",
  "rules": {
    "max-len": [
      "warn",
      {
        "code": 120,
        "ignoreRegExpLiterals": true
      }
    ],
    "indent": [
      "warn",
      2
    ],
    "eqeqeq": [
      "warn",
      "always"
    ],
    "dot-location": [
      "warn",
      "property"
    ],
    "guard-for-in": "warn",
    "no-else-return": "warn",
    "no-undef-init": "warn",
    "global-require": "warn",
    "array-bracket-newline": [
      "warn",
      "consistent"
    ],
    "brace-style": [
      "warn",
      "1tbs",
      {
        "allowSingleLine": true
      }
    ],
    "camelcase": "warn",
    "comma-dangle": [
      "warn",
      "always-multiline"
    ],
    "comma-spacing": [
      "warn",
      {
        "before": false,
        "after": true
      }
    ],
    "comma-style": [
      "warn",
      "last"
    ],
    "computed-property-spacing": [
      "warn",
      "never"
    ],
    "func-call-spacing": [
      "warn",
      "never"
    ],
    "key-spacing": "warn",
    "keyword-spacing": "warn",
    "no-lonely-if": "warn",
    "no-trailing-spaces": "warn",
    "no-whitespace-before-property": "warn",
    "operator-linebreak": [ "warn", "before" ],
    "quotes": [
      "warn",
      "single"
    ],
    "semi": "warn",
    "semi-spacing": "warn",
    "semi-style": "warn",
    "space-before-blocks": "warn",
    "space-before-function-paren": [
      "warn",
      {
        "anonymous": "always",
        "named": "never",
        "asyncArrow": "always"
      }
    ],
    "space-in-parens": ["warn", "never"],
    "object-curly-spacing": [ "warn", "always" ],
    "array-bracket-spacing": [ "warn", "never" ],
    "space-infix-ops": "warn",
    "space-unary-ops": [
      "warn",
      {
        "words": true,
        "nonwords": false
      }
    ],
    "@typescript-eslint/no-unused-vars": ["warn", {
      "argsIgnorePattern": "^_*"
    }],
    "switch-colon-spacing": "warn",
    "arrow-body-style": "warn",
    "arrow-parens": "warn",
    "arrow-spacing": "warn",
    "padded-blocks": [ "warn", "never" ],
    "multiline-ternary": [ "warn", "never" ],
    "no-confusing-arrow": "warn",
    "no-duplicate-imports": "warn",
    "no-var": "warn",
    "prefer-const": "warn",
    "prefer-template": "warn",
    "template-curly-spacing": ["warn", "never"],
    "react-hooks/rules-of-hooks": "warn",
    "react/prop-types": "off",
    "react/jsx-curly-spacing": ["warn", {
      "when": "never",
      "children": { "when": "always" }
    }],
    "react/jsx-tag-spacing": "warn"
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const _ = (config) => ({
  someKey: (config.some_condition
    ? ['thing1']
    : [
      'thing2', 'thing3',
      'thing4', 'thing6', 'thing42',
    ]),
});

```

```bash
./node_modules/.bin/eslint a.js
```
(where 'a.js' is the source code from above)

**What did you expect to happen?**
Accept the code without warnings

**What actually happened? Please include the actual, raw output from ESLint.**
What happened is - I think - the rule `multiline-ternary` assumed that `operator-linebreak` is not set to `before`.

It looks like `multiline-ternary` expects the above snippet to look like this:
```js
const someObject = {
  someKey: (config.some_condition ?
    [thing1] :
    [
      thing2, thing3,
      thing4, thing6, thing42,
    ]),
}
```

However, that violates the rule `operator-linebreak: before` (and gets autofixed by my editor preconfigured to use eslint --fix)

The output for ESLint is:
```

/home/mbalc/[redacted]/a.js
  1:7   warning  '_' is assigned a value but never used                                     @typescript-eslint/no-unused-vars
  2:13  warning  Unexpected newline bet  ween test and consequent of ternary expression       multiline-ternary
  3:7   warning  Unexpected newline between consequent and alternate of ternary expression  multiline-ternary

✖ 3 problems (0 errors, 3 warnings)


```

**Are you willing to submit a pull request to fix this bug?**
No, at least not in the nearest foreseeable future

**Comment by ljharb** [comment]
I very much agree with your above snippet being the correct one, and am very surprised that multiline-ternary doesn’t accept it.

**Comment by mdjermanovic** [comment]
Hi @mbalc, thanks for the issue!

You have `"multiline-ternary": [ "warn", "never" ]` in configuration, so the rule expects no linebreaks around `?` and `:`.

> "never" disallows newlines between the operands of a ternary expression.

```js
/* eslint "multiline-ternary": [ "warn", "never" ] */

// ok
const foo = (config) => ({
  someKey: (config.some_condition ? ['thing1'] : [
      'thing2', 'thing3',
      'thing4', 'thing6', 'thing42',
    ]),
});

// not ok
const _ = (config) => ({
  someKey: (config.some_condition
    ? ['thing1']
    : [
      'thing2', 'thing3',
      'thing4', 'thing6', 'thing42',
    ]),
});

// not ok
const someObject = {
  someKey: (config.some_condition ?
    [thing1] :
    [
      thing2, thing3,
      thing4, thing6, thing42,
    ]),
}
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwibXVsdGlsaW5lLXRlcm5hcnlcIjogWyBcIndhcm5cIiwgXCJuZXZlclwiIF0gKi9cblxuLy8gb2tcbmNvbnN0IGZvbyA9IChjb25maWcpID0+ICh7XG4gIHNvbWVLZXk6IChjb25maWcuc29tZV9jb25kaXRpb24gPyBbJ3RoaW5nMSddIDogW1xuICAgICAgJ3RoaW5nMicsICd0aGluZzMnLFxuICAgICAgJ3RoaW5nNCcsICd0aGluZzYnLCAndGhpbmc0MicsXG4gICAgXSksXG59KTtcblxuLy8gbm90IG9rXG5jb25zdCBfID0gKGNvbmZpZykgPT4gKHtcbiAgc29tZUtleTogKGNvbmZpZy5zb21lX2NvbmRpdGlvblxuICAgID8gWyd0aGluZzEnXVxuICAgIDogW1xuICAgICAgJ3RoaW5nMicsICd0aGluZzMnLFxuICAgICAgJ3RoaW5nNCcsICd0aGluZzYnLCAndGhpbmc0MicsXG4gICAgXSksXG59KTtcblxuLy8gbm90IG9rXG5jb25zdCBzb21lT2JqZWN0ID0ge1xuICBzb21lS2V5OiAoY29uZmlnLnNvbWVfY29uZGl0aW9uID9cbiAgICBbdGhpbmcxXSA6XG4gICAgW1xuICAgICAgdGhpbmcyLCB0aGluZzMsXG4gICAgICB0aGluZzQsIHRoaW5nNiwgdGhpbmc0MixcbiAgICBdKSxcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

If you want formatting from the example, you can configure `multiline-ternary` as `"always"` or `"always-multiline"`:

```js
/* eslint "multiline-ternary": [ "warn", "always-multiline" ] */
/* eslint "operator-linebreak": [ "warn", "before" ] */

// ok
const _ = (config) => ({
  someKey: (config.some_condition
    ? ['thing1']
    : [
      'thing2', 'thing3',
      'thing4', 'thing6', 'thing42',
    ]),
});
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwibXVsdGlsaW5lLXRlcm5hcnlcIjogWyBcIndhcm5cIiwgXCJhbHdheXMtbXVsdGlsaW5lXCIgXSAqL1xuLyogZXNsaW50IFwib3BlcmF0b3ItbGluZWJyZWFrXCI6IFsgXCJ3YXJuXCIsIFwiYmVmb3JlXCIgXSAqL1xuXG4vLyBva1xuY29uc3QgXyA9IChjb25maWcpID0+ICh7XG4gIHNvbWVLZXk6IChjb25maWcuc29tZV9jb25kaXRpb25cbiAgICA/IFsndGhpbmcxJ11cbiAgICA6IFtcbiAgICAgICd0aGluZzInLCAndGhpbmczJyxcbiAgICAgICd0aGluZzQnLCAndGhpbmc2JywgJ3RoaW5nNDInLFxuICAgIF0pLFxufSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by ljharb** [comment]
@mdjermanovic aha, ok so `always-multiline` would be compatible with `operator-linebreak` set to `before` :-) thanks!

**Comment by mbalc** [comment]
okay, I must've gotten a brain lag back then, I was 100% sure then that it is indeed set to `always-multiline` - thanks for the help!

closing as this has been resolved for me
