### ISSUE TITLE
'unexpected token =' in class declaration

### ISSUE THREAD

**Issue by dariuski** [eslint/eslint#13892]
**Tell us about your environment**
* **ESLint Version: 7.14.0**

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class a {
  b = {}
}
```

```js
class a {
  static b = 'c'
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

`Parsing error: unexpected token =`

**Comment by anikethsaha** [comment]
Thanks for the issue. 
 
Class field is still in [stage 3](https://github.com/tc39/proposal-class-fields) and eslint supports stage 4 features. 
You could either wait for it to reach stage 4 or use other parser that supports it like `@babel/eslint-parser`.

**Comment by dariuski** [comment]
Is there any way to disable parsing the block or line using comments until this feature is supproted?

**Comment by mdjermanovic** [comment]
> Is there any way to disable parsing the block or line using comments until this feature is supproted?

No, it isn't possible to ignore part of the code while parsing or to disable parsing errors.

We recommend using [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) for experimental syntax.

I'm closing this issue as it isn't actionable at the moment. ESLint's default parser will support this syntax when it reaches stage 4.
