### ISSUE TITLE
Consider changing default location of `.eslintcache` to `node_modules/.cache`

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#13897]
**The version of ESLint you are using.**

v7.14.0

**The problem you want to solve.**

The default location of `.eslintcache` in the project root is problematic because that directory is generally used to store configuration, not ephemeral files like this cache. By putting it in the project root, you're forcing everyone wo enables that cache to put an entry for it in `.gitignore`.

**Your take on the correct solution to problem.**

 Use [find-cache-dir](https://github.com/avajs/find-cache-dir) to locate the common cache directory and store the file there instead. This is a common pattern used by many other modules like `babel-loader`, `terser-webpack-plugin` and even `eslint-loader`. If there is no `node_modules`, fall back to a temporary directory.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by sztadii** [comment]
Looks like a small change https://github.com/eslint/eslint/blob/master/lib/eslint/eslint.js#L159
If the Eslint team will agree I would love to fix it ( cause it annoyed me in CRA :D )

**Comment by ljharb** [comment]
Alternatively, making an `.eslint` dir, putting the cache and ignore files in there, and then we can just gitignore that folder

**Comment by sztadii** [comment]
That's the thing, nobody wants to extend .gitignore every time when creating a new project.
Nobody will complain if other packages solve that problem in a more elegant way ( keeping it in node_modules/.cache ).
So I think keeping the standard is not a bad idea.

**Comment by NMinhNguyen** [comment]
For what it's worth, this has been raised before and https://github.com/eslint/eslint/issues/11757#issuecomment-496945984 has examples of other popular projects using the `node_modules/.cache` convention.
