### ISSUE TITLE
Recognize eslint-disable and eslint-enable configuration in line comments

### ISSUE THREAD

**Issue by abacabadabacaba** [eslint/eslint#13893]
**The version of ESLint you are using.**

ESLint v7.14.0.

**The problem you want to solve.**

Currently, ESLint recognizes `eslint-disable` and `eslint-enable` directives in block comments, but not inline comments. This is confusing to the users. This was [discussed](/eslint/eslint/issues/6416) a while ago, and was declined because "We've been trying to avoid having multiple ways of doing the same thing".

Back then, `esline-disable-line` and `eslint-disable-next-line` directives were recognized in inline comments but not block comments, but this was later [changed](/eslint/eslint/pull/9745), so the original justification doesn't seem to be valid anymore. Now users expect block comments and line comments to behave in the same way, and that works for `eslint-disable-line` and `eslint-disable-next-line` comments. However, this doesn't work for `eslint-disable` and `eslint-enable`, which is confusing.

**Your take on the correct solution to problem.**

Support `eslint-disable` and `eslint-enable` in line comments. In general, treat block and line comments the same for the purpose of processing configuration.

**Are you willing to submit a pull request to implement this change?**

No.

**Comment by mdjermanovic** [comment]
Hi @abacabadabacaba, thanks for the issue!

I think there's already RFC for this change: https://github.com/eslint/rfcs/pull/34, so I'm closing this issue as a duplicate.

Please let me know if this isn't the same proposal as https://github.com/eslint/rfcs/pull/34 and I'll reopen the issue.
