### ISSUE TITLE
ESLint: 'v-model' directives require no argument.(vue/no-v-model-argument)

### ISSUE THREAD

**Issue by chao921125** [eslint/eslint#13890]
In vue3 project, use v- model:aa How to shut down eslint.
vue3 项目中，使用v-model:aa等指令eslint如何关闭。

**Comment by chao921125** [comment]
Thank you for your reply. Here are my reasons and expectations. 

This is the GitHub address of my project.

[vue3-cli](https://github.com/chao921125/vue3-cli)

Now the temporary solution is to vue.config.js Lintonsave is set to false in the configuration item.

The version of ESLint you are using (run eslint -v)
"eslint": "^7.14.0"

What you did (the source code and ESLint configuration)
module.exports = {
    root: true,
    env: {
      node: true,
      browser: true,
      es6: true,
      es2021: true
    },
    extends: ["plugin:vue/essential", "plugin:prettier/recommended", "eslint:recommended", "@vue/prettier"],
    plugins: ['vue', 'prettier'],
    rules: {
      'prettier/prettier': 'error',
      'generator-star-spacing': 'off',
      "no-console": process.env.NODE_ENV === "production" ? "error" : "off",
      "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
      'space-before-function-paren': 0,
      'no-irregular-whitespace': 0,
      "vue/no-multiple-template-root": 0,
    },
    parserOptions: {
      parser: "babel-eslint",
      sourceType: 'module',
      ecmaVersion: 6
    },
    overrides: [
      {
        files: ["**/__tests__/*.{j,t}s?(x)"],
        env: {
          mocha: true
        }
      }
    ]
  };

The actual ESLint output complete with numbers

What you expected to happen instead
I expect eslint to support some of the new syntax of vue3, such as v- model:aa

**Comment by btmills** [comment]
Hi @chao921125, since you're using `parser: "babel-eslint"`, you'll want to look there for new syntax. It's possible that what you want already works in the newer `@babel/eslint-parser`. Take a look at https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint for more details on that migration.

**Comment by chao921125** [comment]
@btmills  Thanks
