### ISSUE TITLE
Used enum shows as unused

### ISSUE THREAD

**Issue by Christilut** [eslint/eslint#13905]
**Tell us about your environment**

* **ESLint Version:** 7.14.0
* **Node Version:** 12.13.0
* **npm Version:** 6.12.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
```
    "@babel/preset-typescript": "7.12.7",
    "@babel/preset-env": "7.12.7",
    "@typescript-eslint/eslint-plugin": "4.9.0",
    "@typescript-eslint/parser": "4.9.0",
```

**Please show your full configuration:**

```
    "eslint-config-standard": "16.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "5.0.0",
```

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'vue-eslint-parser',
  env: {
    browser: true,
    es6: true
  },
  extends: [
    'plugin:vue/essential',
    "plugin:vue/recommended",
    'standard',
    'plugin:@typescript-eslint/recommended'  // Uses the recommended rules from the @typescript-eslint/eslint-plugin
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly'
  },
  parserOptions: {
    ecmaVersion: 2018,
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
    project: "./tsconfig.json",
    extraFileExtensions: ['.vue']
  },
  plugins: [
    'vue',
    '@typescript-eslint'
  ],
  rules: {
    "semi": ["error", "never"],
    "no-use-before-define": 0,
    "no-new": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-inferrable-types": 0,
    "@typescript-eslint/camelcase": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/no-floating-promises": 2,
    "no-prototype-builtins": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "quotes": ["error", "single", {
      "avoidEscape": true,
      "allowTemplateLiterals": true
    }],
    "no-unused-vars": 1,
    "space-before-function-paren": ["error", {
        "anonymous": "always",
        "named": "never",
        "asyncArrow": "always"
    }],
    "import/no-webpack-loader-syntax": 0,
    "@typescript-eslint/no-var-requires": 0,
    "@typescript-eslint/explicit-module-boundary-types": 0,
    "@typescript-eslint/interface-name-prefix": 0,
    "@typescript-eslint/ban-types": 0,
    "no-async-promise-executor": 0,
    "camelcase": 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```ts
enum CONTEXTMENU_IDS {
  Delete = 'delete',
  OpenFolder = 'OpenFolder',
  Play = 'Play',
  Edit = 'Edit'
}

const foo = CONTEXTMENU_IDS.Delete

console.log(foo)
```

**What did you expect to happen?**
Should not show warnings as the `CONTEXTMENU_IDS` enum is in use.

**What actually happened? Please include the actual, raw output from ESLint.**
![image](https://user-images.githubusercontent.com/3471363/100994404-d4e26b00-3556-11eb-999c-777411b8738b.png)

`'CONTEXTMENU_IDS' is defined but never used. eslint no-unused-vars`

**Comment by yeonjuan** [comment]
Hi :) @Christilut 

ESLint cannot handle ts syntax well. please `off` the base rule and use the extension rule ([`@typescript-eslint/no-unused-vars`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md)).  It seems work

- see [online demo](https://yeonjuan.github.io/typescript-eslint-demo/#e2NvZGU6ImVudW0gQ09OVEVYVE1FTlVfSURTIHtcbiAgRGVsZXRlID0gJ2RlbGV0ZScsXG4gIE9wZW5Gb2xkZXIgPSAnT3BlbkZvbGRlcicsXG4gIFBsYXkgPSAnUGxheScsXG4gIEVkaXQgPSAnRWRpdCdcbn1cblxuY29uc3QgZm9vID0gQ09OVEVYVE1FTlVfSURTLkRlbGV0ZVxuXG5jb25zb2xlLmxvZyhmb28pIixydWxlczp7J25vLXVudXNlZC12YXJzJzonb2ZmJywnQHR5cGVzY3JpcHQtZXNsaW50L25vLXVudXNlZC12YXJzJzonZXJyb3InfSxwYXJzZXJPcHRpb25zOntlY21hRmVhdHVyZXM6e2pzeDpmYWxzZSxnbG9iYWxSZXR1cm46ZmFsc2V9LGVjbWFWZXJzaW9uOjIwMTgscHJvamVjdDpbJy4vdHNjb25maWcuanNvbiddLHNvdXJjZVR5cGU6J3NjcmlwdCd9fQ==)

```json
"rules": {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error"
}
```

**Comment by Christilut** [comment]
Thanks! I always had it the old way but something must've changed. Works perfect now.
