### ISSUE TITLE
conflict between prefer-const and no-use-before-define

### ISSUE THREAD

**Issue by f5lee** [eslint/eslint#13904]
There seems to be no way to write this code in a way that satisfies both of these rules

```js
/* eslint prefer-const: "error", no-use-before-define: "error" */
let foo;
const bar = () => foo;
foo = [bar];

const bar2 = () => foo2;
const foo2 = [bar2];
```

[link to demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogXCJlcnJvclwiLCBuby11c2UtYmVmb3JlLWRlZmluZTogXCJlcnJvclwiICovXG5sZXQgZm9vO1xuY29uc3QgYmFyID0gKCkgPT4gZm9vO1xuZm9vID0gW2Jhcl07XG5cbmNvbnN0IGJhcjIgPSAoKSA9PiBmb28yO1xuY29uc3QgZm9vMiA9IFtiYXIyXTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by mdjermanovic** [comment]
Hi @f5lee, thanks for the issue!

You can use set [ignoreReadBeforeAssign](https://eslint.org/docs/rules/prefer-const#ignorereadbeforeassign) in `prefer-const`:

```js
/* eslint prefer-const: ["error", { ignoreReadBeforeAssign: true }], no-use-before-define: "error" */
let foo;
const bar = () => foo;
foo = [bar];
```

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogW1wiZXJyb3JcIiwgeyBpZ25vcmVSZWFkQmVmb3JlQXNzaWduOiB0cnVlIH1dLCBuby11c2UtYmVmb3JlLWRlZmluZTogXCJlcnJvclwiICovXG5sZXQgZm9vO1xuY29uc3QgYmFyID0gKCkgPT4gZm9vO1xuZm9vID0gW2Jhcl07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

or set `"variables": false` in `no-use-before-define` to allow use in inner functions only:

```js
/* eslint prefer-const: "error", no-use-before-define: ["error", { "variables": false }] */
const bar2 = () => foo2;
const foo2 = [bar2];
```

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogXCJlcnJvclwiLCBuby11c2UtYmVmb3JlLWRlZmluZTogW1wiZXJyb3JcIiwgeyBcInZhcmlhYmxlc1wiOiBmYWxzZSB9XSAqL1xuY29uc3QgYmFyMiA9ICgpID0+IGZvbzI7XG5jb25zdCBmb28yID0gW2JhcjJdOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**Comment by f5lee** [comment]
I don't like either option, they both seem worse than just using eslint-disable for the specific case that's a false warning.

Setting prefer-const ignoreReadBeforeAssign:true will suppress the warning in cases where it should be const:
```js
/* eslint prefer-const: ["error", { ignoreReadBeforeAssign: true }], no-use-before-define: "error" */
let foo;
function f () { return foo; }
foo = 3;
```
[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogW1wiZXJyb3JcIiwgeyBpZ25vcmVSZWFkQmVmb3JlQXNzaWduOiB0cnVlIH1dLCBuby11c2UtYmVmb3JlLWRlZmluZTogXCJlcnJvclwiICovXG5sZXQgZm9vO1xuZnVuY3Rpb24gZiAoKSB7IHJldHVybiBmb287IH1cbmZvbyA9IDM7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

Setting no-use-before-define variables:false will suppress the warning in cases where it's an error:
```js
/* eslint prefer-const: "error", no-use-before-define: ["error", { "variables": false }] */
function f() { return foo; }
f();
const foo = 3;
```
[demo]( https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogXCJlcnJvclwiLCBuby11c2UtYmVmb3JlLWRlZmluZTogW1wiZXJyb3JcIiwgeyBcInZhcmlhYmxlc1wiOiBmYWxzZSB9XSAqL1xuZnVuY3Rpb24gZigpIHsgcmV0dXJuIGZvbzsgfVxuZigpO1xuY29uc3QgZm9vID0gMztcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**Comment by mdjermanovic** [comment]
> I don't like either option, they both seem worse than just using eslint-disable for the specific case that's a false warning

That's fine, assuming you prefer the version with `const` instead of `let`.

`no-use-before-define` cannot track all possible paths to determine whether it's completely safe or not to reference a variable before its declaration, so `variables: true` seems like a good way to avoid TDZ errors, combined with `eslint-disable` in cases where you're sure it's safe.

```js
/* eslint prefer-const: "error", no-use-before-define: "error" */
const bar2 = () => foo2; // eslint-disable-line no-use-before-define -- bar2 isn't called before `const foo2`
const foo2 = [bar2];
```

**Comment by f5lee** [comment]
Sure, eslint can't do a perfect flow control analysis, but maybe it could do a better job than it does now?

I feel like this is not an uncommon case, it seems like it could be handled with simple static analysis, and I'd feel better if a tool like eslint would do it for me.

I mean, it's not really hard to do the analysis manually, but it's also easy to make a mistake in analysis, and much of what eslint does is about catching easy mistakes.

**Comment by mdjermanovic** [comment]
I believe `no-use-before-define` was actually intended to be more like a stylistic/best practice rule.

There is a discussion about catching TDZ error in another rule: https://github.com/eslint/eslint/issues/11903
