### ISSUE TITLE
autofix no-use-before-define

### ISSUE THREAD

**Issue by gomesalexandre** [eslint/eslint#13926]
**What rule do you want to change?**

`no-use-before-define` 

**Does this change cause the rule to produce more or fewer warnings?**

None after autofix

**How will the change be implemented? (New option, new default behavior, etc.)?**

If `--fix` is used, definitions would be moved before first use. 

We would, of course, have to account for dependencies i.e we move all definitions before their respective first use, some of the just-moved classes / variables / functions might again be reported as violations so the most efficient algorithm will have to be used, depending on the style we want to achieve with the autofix.

Some fixing styles would also be possible:

- Do we want to, when possible, move each definition *right* before its first use? 
- Or do we rather want to move all the imports before the very first violation of the rule in the module, and group them together? 

**Please provide some example code that this change will affect:**

[ESLint Live Demo
](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgZm9vID0gZWNob0ZvbygpO1xuY29uc3QgZWNob0ZvbyA9ICgpID0+ICdmb28nO1xuXG5jb25zb2xlLmxvZyh7Zm9vfSkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8tdXNlLWJlZm9yZS1kZWZpbmUiOjJ9LCJlbnYiOnsiYnJvd3NlciI6dHJ1ZSwibm9kZSI6dHJ1ZSwiY29tbW9uanMiOnRydWUsInNoYXJlZC1ub2RlLWJyb3dzZXIiOnRydWUsIndvcmtlciI6dHJ1ZSwiYW1kIjp0cnVlLCJtb2NoYSI6dHJ1ZSwiamFzbWluZSI6dHJ1ZSwiamVzdCI6dHJ1ZSwicGhhbnRvbWpzIjp0cnVlLCJqcXVlcnkiOnRydWUsInF1bml0Ijp0cnVlLCJwcm90b3R5cGVqcyI6dHJ1ZSwic2hlbGxqcyI6dHJ1ZSwibWV0ZW9yIjp0cnVlLCJtb25nbyI6dHJ1ZSwicHJvdHJhY3RvciI6dHJ1ZSwiYXBwbGVzY3JpcHQiOnRydWUsIm5hc2hvcm4iOnRydWUsInNlcnZpY2V3b3JrZXIiOnRydWUsImF0b210ZXN0Ijp0cnVlLCJlbWJlcnRlc3QiOnRydWUsIndlYmV4dGVuc2lvbnMiOnRydWUsImVzNiI6dHJ1ZSwiZXMyMDE3Ijp0cnVlLCJlczIwMjAiOnRydWUsImVzMjAyMSI6dHJ1ZSwiZ3JlYXNlbW9ua2V5Ijp0cnVlfX19)
```js
const foo = echoFoo();
const echoFoo = () => 'foo';

console.log({foo})
```

**What does the rule currently do for this code?**

It linths with no autofix, as no `fix` method is currently present

**What will the rule do after it's changed?**

Allow for autofixing 

**Are you willing to submit a pull request to implement this change?**

If we find value in this fix and want to proceed with it, sure! 👍

**Comment by anikethsaha** [comment]
Thanks for the issue

IMO,  fixing for this might involve movement of too many code. for the above example, currently we would need to swap the position of those lines. But if we have code similar to this

```js
const foo = echoFoo(), bar = 1; // line 1
// other codes
console.log(bar) // line 2
const echoFoo = () => bar + 'foo'; // line 3

console.log({foo})
```

in order to fix the `echoFoo` issue, we would need to put line 1 after line 3 but doing that would create other errors (at line 2). 
So autofixing these would be highly complex with lots of possibilities of further false cases. 

LMK if I am missing anything.

**Comment by nzakas** [comment]
Yeah, this is far too complicated for our autofix capabilities, so I'm afraid we can't move forward with this.
