### ISSUE TITLE
`prefer-const` can ask for a fix that will cause a javascript syntax error

### ISSUE THREAD

**Issue by brizental** [eslint/eslint#13929]
**Tell us about your environment**

Node version: v10.16.3
npm version: v6.14.9
Local ESLint version: v7.12.1 (Currently used)
Global ESLint version: Not found

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "env": {
    "node": true,
    "browser": true,
    "webextensions": true
  },
  "rules": {
    "indent": ["error", 2],
    "quotes": ["error", "double"],
    "no-var": "error",
    "prefer-const": "error",
    "strict": ["error", "global"],
    "notice/notice":[ "error", {
      "mustMatch": "This Source Code Form is subject to the terms of the Mozilla Public",
      "templateFile": "copyright.template.txt"
      }
    ],
    "semi": ["error", "always"],
    "no-debugger":  ["error"],
    "jsdoc/no-types": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns-type": "off"
  },
  "extends": [
    "plugin:jsdoc/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint",
    "json",
    "notice",
    "mocha",
    "jsdoc"
  ],
  "overrides": [
    {
      "files": "tests/**",
      "env": {
        "mocha": true
      },
      "extends": [
        "plugin:mocha/recommended"
      ]
    },
    {
      "files": "*.json",
      "extends": [
        "plugin:json/recommended"
      ],
      "rules": {
        "notice/notice": "off"
      }
    },
    {
      "files": "*.js",
      "extends": [
        "eslint:recommended"
      ]
    },
    {
      "files": "*.ts",
      "extends": [
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended"
      ]
    }
  ]
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let test;
// ...other stuff...
test = "blabla";
```

```bash
eslint . --ext .ts,.js,.json
```

**What did you expect to happen?**

No error.

**What actually happened? Please include the actual, raw output from ESLint.**

`error    'test' is never reassigned. Use 'const' instead  prefer-const`

Note that if I make `test` a `const` that is a Javascript syntax error.

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by mdjermanovic** [comment]
Hi @brizental, thanks for the issue!

This rule reports `let` variables that can be `const` variables, but that doesn't necessarily mean that the only change should be to replace `let` with `const`.

In your example, the fix would be:

```js
const test = "blabla";
// ...other stuff...
```

**Comment by brizental** [comment]
Yes, sure. But what if I want to do something like:

```js
let test;
assert(test === undefined);
test = "blabla";
assert(test === "blabla");
```

(Sorry, couldn't think of a less terrible example).

My point is, that is valid code that one possibly would write and the eslint error is misleading and the fix produces a syntax error. Interestingly, when I do

```js
let test;
if (2 > 1) {
   test = "blabla";
}
```

I don't get the sam error.

Maybe for the first example eslint should have a different rule, such as `unnecessary early variable definition`?

**Comment by mdjermanovic** [comment]
The rule would be pretty limited if it would be reporting only cases where `let` can be just replaced with `const` without any other changes. For example, in the following code it reports `a`, but not `b`:

```js
let a = 1, b = 2;

if (something) {
  b = 3;
}
```

> ```js
> let test;
> assert(test === undefined);
> test = "blabla";
> assert(test === "blabla");
> ```

This can be refactored to `const`, since using an uninitialized variable like this doesn't make sense (all references before the assignment can be replaced with `undefined`), but if someone does want to allow that, they can use [ignoreReadBeforeAssign](https://eslint.org/docs/rules/prefer-const#ignorereadbeforeassign) option.

> ```js
> let test;
> if (2 > 1) {
>    test = "blabla";
> }
> ```

This is different since the assignment is conditional, so there are really two possible values for the rest of the code.

> `error 'test' is never reassigned. Use 'const' instead prefer-const`
> the eslint error is misleading

Maybe we could change the error message?
