### ISSUE TITLE
Ability to specify cache configuration in eslintrc files to optimize cache strategy

### ISSUE THREAD

**Issue by olderor** [eslint/eslint#13938]
**The version of ESLint you are using.**
7.15.0

**The problem you want to solve.**
Currently, the cache can only be specified in command line options, but not through the eslintrc file (at least I was unable to find any documentation on this for the config file, please point me to the right direction if I missed anything).

We would like to configure caching in eslintrc files instead. There are a few reasons behind that:

1. (critical) We have one 'global' eslintrc file enabled for the whole repo with main configuration and a standard set of rules, and 'local' eslintrc files enabled for each package with different rules, overriding, etc. When a developer builds one of the packages, we run the linter, and the results are cached for this specific package. When a developer runs the linter over the whole repo, it cannot use the caching results for the 'local' package, it has to be a new cache file as the command itself is different. This way we lose on performance as the linter doesn't optimize the cache strategy, so **for our case the time to lint doubles** (first to lint one specific package, then lint all packages including the one which is already linted).

2. (less critical) In eslintrc files we can specify which package should be linted with cache, and which package should be linted without cache. That way we can turn off caching for some specific packages that are crusial for us.

**Your take on the correct solution to problem.**
Adding cache configuration to the eslintrc file along with the command line options similar to the other functionality which is available both in eslintrc and cmd options. Ability to override caching configuration for sub-packages (in eslintrc files that extend the global one). Improving cache strategy to switch the cache configuration based on the eslintrc configuration.
P.S. Adding this functionality will not break backwards comp, so it will be a good addition to the linter.

**Are you willing to submit a pull request to implement this change?**
I can probably take it, but maybe it's better to assign it to someone experienced with how the caching works as I don't have this knowledge.

**Comment by mdjermanovic** [comment]
Hi @olderor, thanks for the issue! 

> When a developer builds one of the packages, we run the linter, and the results are cached for this specific package. When a developer runs the linter over the whole repo, it cannot use the caching results for the 'local' package, it has to be a new cache file as the command itself is different.

Can you use the same 'global' cache file in both scenarios? It can be specified with the [--cache-location](https://eslint.org/docs/user-guide/command-line-interface#-cache-location) option.

**Comment by olderor** [comment]
Hi @mdjermanovic ,

Thanks for the suggestion! For some reason, I thought the cache should be specified separately because of different configurations. I switched it to be 'global' cache instead, and the time improved.

Although it seems to me that it's still not optimal for the very first run, probably because we build the packages in parallel, and there is some race condition on writing the cache to this file, so some of the packages aren't getting cached until I run linter over the whole repo separately.
So I believe if you run a few instances of linter that work with the same cache file but check different code with different configurations, some of the cache data can be missed due to this racing. I'm not sure if it's good to have a few instances working with the same cache file, and what can be the consequences of this racing.

**Comment by nzakas** [comment]
I’m :-1: to adding this to config files. Doing so would allow shared configs to also specify this information and transparently change how ESLint does its caching. I think this is best kept as a CLI option only.

**Comment by nzakas** [comment]
Closing, as we won’t be moving forward with this suggestion. Thanks!
