### ISSUE TITLE
[meta] Add developer guidance about how to write messages

### ISSUE THREAD

**Issue by thw0rted** [eslint/eslint#13952]
**The version of ESLint you are using.**

7.15.0, though that's irrelevant.

**The problem you want to solve.**

The developer guide includes technical information about [how to write rules](https://eslint.org/docs/developer-guide/working-with-rules), including how to use templating and how to extract messages from rules into the `meta` section.  As far as I can see, though, there is no guidance about what makes a good message.  This means that it's up to individual rule authors to determine how to format messages, which can lead to inconsistency and a bad user experience.

Is a particular grammatical style encouraged?  Should messages be short enough to fit on one line?  If they don't, should they use newlines? If brevity is important, should the message include a link to a more detailed explanation?  How?  Does it make sense for messages to include any kind of markup?  If so, what kind of markup is commonly supported by formatters?

I opened this issue because of https://github.com/typescript-eslint/typescript-eslint/issues/2895. One set of rules supplied by this plugin emits messages that stand out as very different from most of the other messages -- long messages, including Markdown for formatting and links, with multiple newlines.  This causes the default (`stylish`) formatter to break a commonly-used parser that didn't expect mid-message newlines.  When I filed that issue, I couldn't find any guidelines to say what messages should look like.  If there were published guidance one way or the other, I could either tell the rule authors that they're violating guidelines, or tell the (VSCode) parser that they're not handling an edge case that's officially supported.  As it stands, there are no constraints.

**Your take on the correct solution to problem.**

It's probably not a big enough topic to warrant its own page in the docs, but one of the existing pages should at least include an entry addressing this, ideally with examples of good and bad messages to illustrate each point.

**Are you willing to submit a pull request to implement this change?**

I would be happy to make some suggestions but I don't feel like I've had enough experience with the diverse set of community-created rules to write guidance that would cover the current ecosystem without alienating anyone.  I was hoping somebody who has spent more time with the project would have ideas about this -- with some feedback from the maintainers, I could mold their ideas into a fleshed-out entry on one of the existing documentation pages.

**Comment by nzakas** [comment]
We don’t really have any guidance on how to write messages as we generally assume the people writing the rules have enough knowledge to decide what should be in the message.

if you have suggestions for what the guidance should be, we are open to that.
