### ISSUE TITLE
Cannot fix max-len errors on example for max-len

### ISSUE THREAD

**Issue by skamansam** [eslint/eslint#13951]
**Tell us about your environment**

* Node version: v15.2.1
* npm version: v7.0.8
* Local ESLint version: v7.16.0 (Currently used)
* Global ESLint version: Not found

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
none, but I tried with @babel/eslint-parser with the same result.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// package.json
{
  "name": "eslint-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "eslint": "eslint eslint-test.js",
    "fix": "eslint --fix eslint-test.js"
  },
  "dependencies": {
  },
  "devDependencies": {
    "eslint": "^7.16.0"
  },
  "eslintConfig": {
    "rules": {
      "no-console": [
        "error",
        {
          "allow": [
            "debug"
          ]
        }
      ],
      "max-len": [
        "error",
        {
          "tabWidth": 2,
          "code": 60
        }
      ]
    }
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var foo = { bar: 'This is a bar.', baz: { qux: 'This is a qux' }, difficult: 'to read' }; // very long
```

```bash
./node_modules/.bin/eslint --fix eslint-test.js
```

**What did you expect to happen?**
The file should have been changed to:

```js
var foo = {
  bar: 'This is a bar.',
  baz: {
    qux: 'This is a qux'
  },
  difficult: 'to read'
}; // very long
```

**What actually happened? Please include the actual, raw output from ESLint.**
nothing. the file remained the same, and the command only output the errors:

```bash
#./node_modules/.bin/eslint --fix eslint-test.js 

/home/sam/workspace/eslint-test/eslint-test.js
  1:1  error  This line has a length of 102. Maximum allowed is 60  max-len

✖ 1 problem (1 error, 0 warnings)
```

**Are you willing to submit a pull request to fix this bug?**
I would love to, but I don't have the time currently.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

I guess we can do autofix for `arrays` and `objects` but it would be complex autofix with possible further linting errors.  
IMO, I would leave it to users to fix it.

**Comment by nzakas** [comment]
Unfortunately, `max-len` isn't a rule that we can provide autofix for. It would require far too much logic and there are too many ways people prefer to wrap their code when it gets too long. Prettier is a better option for fixing these types of issues.
