### ISSUE TITLE
eslint rule tester output the failing cases' filename and line number

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#13955]
**The version of ESLint you are using.**
v7.16.0/master

**The problem you want to solve.**
when running rule testing, devs are hard to find the failing cases - as eslint tester did not show failing cases' line number
![image](https://user-images.githubusercontent.com/13050025/103116293-f7bcf680-46a0-11eb-911a-4e569e5f7b55.png)

**Your take on the correct solution to problem.**
output the failing cases' filename and line number.
![image](https://user-images.githubusercontent.com/13050025/103116489-a103ec80-46a1-11eb-8788-7690cdce4f73.png)

**Are you willing to submit a pull request to implement this change?**
maybe. :)

**Comment by mdjermanovic** [comment]
That would be useful, but it seems very complicated. Any ideas on how could RuleTester figure out the file and the line number?

**Comment by aladdin-add** [comment]
I guess mocha can tell the filename, but yes, the line number could be complicated. It helped me a little to print the failing cases' index.

![image](https://user-images.githubusercontent.com/13050025/103133944-6ec9ad80-46e8-11eb-8ef1-03cc0299197a.png)

**Comment by aladdin-add** [comment]
closing, as seems there is no easy ways to get it. v\(￣︶￣*\))
