### ISSUE TITLE
CLIEngine.getConfigForFile() fails after Webpack.

### ISSUE THREAD

**Issue by daidodo** [eslint/eslint#13974]
**Tell us about your environment**

Environment Info:

Node version: v12.16.3
npm version: v6.14.10
Local ESLint version: v7.16.0 (Currently used)
Global ESLint version: v5.4.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

package.json:

```json
  "eslintConfig": {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "tsconfigRootDir": "./",
      "project": [
        "./tsconfig.json"
      ]
    },
    "plugins": [
      "@typescript-eslint",
      "eslint-plugin-tsdoc"
    ],
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/eslint-recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking",
      "prettier/@typescript-eslint"
    ],
    "ignorePatterns": [
      "src/test/suite/examples/**/*.ts",
      "webpack.config.*"
    ],
    "rules": {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-use-before-define": [
        "error",
        {
          "functions": false,
          "classes": false
        }
      ],
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          "varsIgnorePattern": "^_",
          "argsIgnorePattern": "^_",
          "ignoreRestSiblings": true
        }
      ],
      "tsdoc/syntax": "warn"
    }
  }
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I'm writing a [VSCode extension](https://github.com/daidodo/tsimportsorter) and using the following code to get user project ESLint config:

```ts
    const eslint = new CLIEngine({});
    if (eslint.isPathIgnored(filePath)) {  // filePath points to a user project source file
      log.debug('Ignored by ESLint for filePath:', filePath);
      return undefined;
    }
    const config = eslint.getConfigForFile(filePath);
    log.debug('Finish loading ESLint config');
```

The webpack.config.js for the extension:

```ts
const config: Configuration = {
  target: 'node', // vscode extensions run in a Node.js-context 📖 -> https://webpack.js.org/configuration/node/

  entry: './src/extension.ts', // the entry point of this extension, 📖 -> https://webpack.js.org/configuration/entry-context/
  output: {
    // the bundle is stored in the 'out' folder (check package.json), 📖 -> https://webpack.js.org/configuration/output/
    path: path.resolve(__dirname, 'out'),
    filename: 'extension.js',
    libraryTarget: 'commonjs2',
  },
  externals: {
    vscode: 'commonjs vscode', // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed, 📖 -> https://webpack.js.org/configuration/externals/
  },
  resolve: {
    // support reading TypeScript and JavaScript files, 📖 -> https://github.com/TypeStrong/ts-loader
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: 'ts-loader',
      },
    ],
  },
};

export default config;
```

**What did you expect to happen?**
The config is successfully loaded if ESLint is properly installed in the user project, regardless of my extension is webpacked or not.

**What actually happened? Please include the actual, raw output from ESLint.**
If webpacked, the config will fail to load due to wrong path to `eslint-recommended.js`, e.g.:

```log
Cannot read config file: /Volumes/Unix/Desktop/work/private/tsimportsorter/conf/eslint-recommended.js
Error: Cannot find module '/Volumes/Unix/Desktop/work/private/tsimportsorter/conf/eslint-recommended.js'
Require stack:
- /Volumes/Unix/Desktop/work/private/tsimportsorter/project/out/noop.js
Referenced from: /Volumes/Unix/Desktop/work/native/first/.eslintrc.json
```

If not webpacked, the config will be loaded successfully.

**Preliminary Analysis**
The root cause might be the use of `__dirname` inside [lib/cli-engine/cli-engine.js](https://github.com/eslint/eslint/blame/896273f9d75c973ce2c7cc25580ae667a10ec6f9/lib/cli-engine/cli-engine.js#L580):

```js
eslintRecommendedPath: path.resolve(__dirname, "../../conf/eslint-recommended.js"),
eslintAllPath: path.resolve(__dirname, "../../conf/eslint-all.js")
```

Without Webpack, the `__dirname` will be `user_project/node_modules/eslint/lib/cli-engine/` which is all right.
But if webpacked, all sources are in a single file, e.g. `extension_dir/out/extension.js`, so `__dirname` is no longer what we want.

**Are you willing to submit a pull request to fix this bug?**
No, I'm new to ESLint APIs.

**Comment by anikethsaha** [comment]
Thanks for the issue.

`__dirname` is required as it prints the current directory from where the script is being run and as this is being used by the eslint (as cli).

I guess there can be ways to address this using webpack config itself. May be [config.node.__dirname](https://webpack.js.org/configuration/node/#node__dirname) will help here

**Comment by daidodo** [comment]
Thanks for the response!

I've tried `node.__dirname` but couldn't find a way to overcome the issue.

I'm new to the APIs but given the popularity of ESLint, there will be more and more 3p integrations. Since CLIEgine/ESLint are the only public APIs (are they?), it might be necessary to make them generic and independent to execution environments.

**Comment by aladdin-add** [comment]
just a reminder: The CLIEngine class has been deprecated in favor of the ESLint class as of v7.0.0.

refs: https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by daidodo** [comment]
Thanks! I noticed that. 
But it has the sync version of resolving config which is what I need.

**Comment by mdjermanovic** [comment]
We don't support web-packing ESLint.

Can you use the installed ESLint? [vscode-eslint](https://github.com/microsoft/vscode-eslint) extension is working like that:

> The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version.

**Comment by daidodo** [comment]
Webpack is just a tool to pack the code.

My understanding tells me that `__dirname` is used to achieve some kind of dynamic loading. I wonder if that's is really necessary as the recommend rules don't look huge to me.

**Comment by mdjermanovic** [comment]
ESLint internally treats `eslint:recommended` and `eslint:all` like any other configs from [this point](https://github.com/eslint/eslintrc/blob/f1179c587ae09fabb5c3402598363cfcec2494f7/lib/config-array-factory.js#L795) onward, so they have to be separate files. Changing this internal logic would require a significant amount of work for a use case we don't support.

We could maybe consider changing `path.resolve` to `require.resolve`, but I'm not sure if that change alone would help.

> ```ts
>     const eslint = new CLIEngine({});
>     if (eslint.isPathIgnored(filePath)) {  // filePath points to a user project source file
>       log.debug('Ignored by ESLint for filePath:', filePath);
>       return undefined;
>     }
>     const config = eslint.getConfigForFile(filePath);
>     log.debug('Finish loading ESLint config');
> ```

ESLint config files and loading have changed over time, so it's probably better to use the user's local ESLint version than packing one particular version that may or may not work as expected with given configs.

**Comment by daidodo** [comment]
Do you suggest that I check user's `node_modules/` and dynamically import `eslint` and APIs? That doesn't seem natural and stable (Did `npm i` finish?) to me. And if every 3p client needs to do things that way, probably the library should take care of it?

I understand that the rules config and recommendations may change over time. Is it possible that they can be in a separate package or a cloud server (like the config schema), because the APIs should be fairly stable?

**Comment by mdjermanovic** [comment]
> Do you suggest that I check user's node_modules/ and dynamically import eslint and APIs? That doesn't seem natural and robust (Did npm i finish?) to me.

ESLint is designed to be installed in `node_modules/`, and then used as a CLI tool or required as a module: `require("eslint")`. It's a common usage of tools/libraries on Node.js.

I can't tell what's the best practice for VSCode extensions, but there are examples of extensions that use ESLint from `node_modules/`, like [microsoft/vscode-eslint](https://github.com/microsoft/vscode-eslint).

> And if every 3p client needs to do things that way, probably the library should take care of it?

Can you please clarify this?

> I understand that the rules config and recommendations may change over time. Is it possible that they can be in a separate package or a cloud server (like json schema store), because the APIs should be fairly stable?

We haven't considered splitting ESLint into multiple packages. If that seems useful, you can open an issue so we could evaluate benefits over added complexity.

**Comment by nzakas** [comment]
Closing due to age
