### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by lollita** [eslint/eslint#13980]
Linus
* **ESLint Version:**
v7.15.0
* **Node Version:**
15.5.0
* **npm Version:**
7.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const {title, ...options} = notification;
```

```bash

```

**What did you expect to happen?**
nothing
the code work fine.

**What actually happened? Please include the actual, raw output from ESLint.**
error  Parsing error: Unexpected token ..

**Are you willing to submit a pull request to fix this bug?**

**Comment by mdjermanovic** [comment]
Hi @lollita, thanks for the issue!

Can you please share your configuration?

If you're using the default parser, you'll have to set `"ecmaVersion": 2018`, or higher.

```json
{
    "parserOptions": {
        "ecmaVersion": 2018
    }
}
```

[Specifying Parser Options](https://eslint.org/docs/user-guide/configuring#specifying-parser-options)

**Comment by lollita** [comment]
I had "ecmaVersion": 8.
2018 fix it.
ty.
