### ISSUE TITLE
Docs for `no-unused-vars` show `argsIgnorePattern": "^_"` instead of `argsIgnorePattern": "^\_"`

### ISSUE THREAD

**Issue by brunoreis** [eslint/eslint#13999]
`argsIgnorePattern": "^\_"` works
`argsIgnorePattern": "^_"` does not work

https://eslint.org/docs/rules/no-unused-vars

**Comment by brunoreis** [comment]
"^\_" seems to work for the inline blocks only.

**Comment by brunoreis** [comment]
In fact this does not make sense. 
I have no idea why `"argsIgnorePattern": "^_"` is not working here.

**Comment by mdjermanovic** [comment]
Hi @brunoreis!

If something doesn't seem to be working as expected, could you please open a bug report issue with all the details?

**Comment by brunoreis** [comment]
Sure. I had made some confusion between argsIgnorePattern and varsIgnorePattern in an array deconstruction. My bad.
