### ISSUE TITLE
"TypeError: Cannot read property 'type' of undefined" with Flow-typed private array instance property

### ISSUE THREAD

**Issue by adelespinasse** [eslint/eslint#13994]
**Tell us about your environment**
Environment Info:

Node version: v10.19.0
npm version: v6.14.9
Local ESLint version: v7.17.0 (Currently used)
Global ESLint version: Not found

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

I'm not totally sure. Whatever is the default for the "react-app" base configuration, I guess. Previously I was using `"babel-eslint"` and got the same error.

**Please show your full configuration:**

Full reproduction repo is here: https://github.com/adelespinasse/eslinttypeerror
This is a much-scaled-down copy of my actual project repo, which has a long and complex history. I'm not sure how much more could be removed from it and still have the failure.

<details>
<summary>Configuration</summary>

```js
{
  "extends": ["react-app"]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export class Controller {
  #undoStack: Array<number>;
}
```

To run and reproduce the error:

```bash
git clone https://github.com/adelespinasse/eslinttypeerror.git
cd eslinttypeerror
npm install
npm run lint
```

**What did you expect to happen?**

ESLint should run successfully.

**What actually happened? Please include the actual, raw output from ESLint.**

```
> eslinttypeerror@0.1.0 lint /home/aldel/eslinttypeerror
> eslint --ext .js,.jsx .

Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

Oops! Something went wrong! :(

ESLint: 7.17.0

TypeError: Cannot read property 'type' of undefined
Occurred while linting /home/aldel/eslinttypeerror/src/controller.js:4
    at isForInRef (/home/aldel/eslinttypeerror/node_modules/eslint/lib/rules/no-unused-vars.js:449:24)
    at variable.references.some.ref (/home/aldel/eslinttypeerror/node_modules/eslint/lib/rules/no-unused-vars.js:486:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/home/aldel/eslinttypeerror/node_modules/eslint/lib/rules/no-unused-vars.js:485:40)
    at collectUnusedVariables (/home/aldel/eslinttypeerror/node_modules/eslint/lib/rules/no-unused-vars.js:596:26)
    at Program:exit (/home/aldel/eslinttypeerror/node_modules/eslint/lib/rules/no-unused-vars.js:615:36)
    at listeners.(anonymous function).forEach.listener (/home/aldel/eslinttypeerror/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/aldel/eslinttypeerror/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/aldel/eslinttypeerror/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eslinttypeerror@0.1.0 lint: `eslint --ext .js,.jsx .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eslinttypeerror@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aldel/.npm/_logs/2021-01-07T23_17_10_332Z-debug.log
```

**Are you willing to submit a pull request to fix this bug?**

I would have no idea where to start.

**Notes**

This may have something to do with Flow type annotations. If I change the declared type to just `number`, it does not crash. If I remove the `#` from the variable name (i.e., make it public), it does not crash.

**Comment by anikethsaha** [comment]
Thanks for the issue.

Its not an issue with eslint's core. 

can you try adding [`parser: ['@babel/eslint-parser']`](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) .

**Comment by adelespinasse** [comment]
> can you try adding [`parser: ['@babel/eslint-parser']`](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) .

I added `"parser": "@babel/eslint-parser"` (since it's an `.eslintrc` file, not a .js config file) and installed `@babel/eslint-parser`. Now it gives this error:
```
/home/aldel/eslinttypeerror/src/controller.js
  0:0  error  Parsing error: No Babel config file detected for /home/aldel/eslinttypeerror/src/controller.js. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files
```
If I set "requireConfigFile" to false, I get:
```
/home/aldel/eslinttypeerror/src/controller.js
  5:2  error  Parsing error: /home/aldel/eslinttypeerror/src/controller.js: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled (5:3):

  3 |  */
  4 | export class Controller {
> 5 |   #undoStack: Array<number>;
    |   ^
  6 | }
  7 | 

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing
```
That's as far as I took it. I don't even know how to create a Babel configuration file; I haven't needed one before. Presumably `create-react-app` takes care of that under the hood.

**Comment by anikethsaha** [comment]
You need babel config to specify the presets/plugin here in order to parse flow and language features. 

You can refer [this](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4GEIDsZQRJLBRwDeAUHHAMQCuuAJhAMowoIDWAXHAIJQoKAJ4AeXPQC2AI1IA-ANyUAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ces2015%2Creact%2Cstage-2%2Cflow&prettier=false&targets=&version=7.12.12&externalPlugins=) and [here](https://babeljs.io/docs/en/configuration)

Though I agree this should be handled by the `create-react-app` itself. May be opening a PR in their repo can be helpful
