### ISSUE TITLE
required: exit non-zero status code when found error/warn

### ISSUE THREAD

**Issue by axetroy** [eslint/eslint#14013]
I hope there is no any warning/error in my project

I set up a series of CI and hook checks, but eslint has no options. When there is warn/error, exit the process with the specified status code (non-zero)

**Comment by mdjermanovic** [comment]
Hi @axetroy, thanks for the issue!

ESLint already exits with a non-zero code if there are linting errors, please see [Exit Codes](https://eslint.org/docs/user-guide/command-line-interface#exit-codes) in the CLI documentation.

> When linting files, ESLint will exit with one of the following exit codes:
>
> 0: Linting was successful and there are no linting errors. If the --max-warnings flag is set to n, the number of linting warnings is at most n.
> 1: Linting was successful and there is at least one linting error, or there are more linting warnings than allowed by the --max-warnings option.
> 2: Linting was unsuccessful due to a configuration problem or an internal error.

Can you please provide more details about the problem you’re trying to solve?

**Comment by axetroy** [comment]
> Hi @axetroy, thanks for the issue!
> 
> ESLint already exits with a non-zero code if there are linting errors, please see [Exit Codes](https://eslint.org/docs/user-guide/command-line-interface#exit-codes) in the CLI documentation.
> 
> > When linting files, ESLint will exit with one of the following exit codes:
> > 0: Linting was successful and there are no linting errors. If the --max-warnings flag is set to n, the number of linting warnings is at most n.
> > 1: Linting was successful and there is at least one linting error, or there are more linting warnings than allowed by the --max-warnings option.
> > 2: Linting was unsuccessful due to a configuration problem or an internal error.
> 
> Can you please provide more details about the problem you’re trying to solve?

Thank you for your reply, this is my fault, I didn't read the document well.

--max-warnings can already meet my requirements.
