### ISSUE TITLE
Decorator: Unexpected use of 'name'. no-restricted-globals

### ISSUE THREAD

**Issue by Edge00** [eslint/eslint#14020]
### env info
* ESLint Version: 7.14.0
* Node Version: 12.13.1
* npm Version:6.4.10

### parser
@typescript-eslint/parser

<details>
<summary>Configuration</summary>

```js
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
    mocha: true,
  },
  parser: '@typescript-eslint/parser',
  extends: ['airbnb-base', 'plugin:@typescript-eslint/recommended'],
  globals: {
    expect: false,
  },
  rules: {
    'no-use-before-define': 0,
    'max-classes-per-file': [0, 1],
    '@typescript-eslint/member-delimiter-style': [2, { multiline: { delimiter: 'none' } }],
    '@typescript-eslint/no-use-before-define': [2],
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/ban-types': 0,
  },
```
</details>

<details>
<summary>Code</summary>

```js
export default class CiController extends Base {
  @post('/docker-image/record')
  async createDockerImageRecord(@parseRequest({
    body: {
      name: {
        type: 'string',
        required: true,
      },
      tag: {
        type: 'string',
        required: true,
      },
      jobId: {
        type: 'number',
        required: true,
      },
      pId: {
        type: 'number',
        required: true,
      },
      packageLockStr: {
        type: 'string',
        required: true,
      },
    },
  }) paramters: {
    body: {
      name: string
      tag: string
      jobId: number
      pId: number
      packageLockStr: string
    }
  }): IResult<any> {
    const {
      name,
      tag,
      jobId,
      pId,
      packageLockStr,
    } = paramters.body

  }
}
```
</details>

### command
```bash
eslint
```

### result
![image](https://user-images.githubusercontent.com/23715779/105321018-dc8ec980-5c01-11eb-8090-1a2c49b287ec.png)

**What did you expect to happen?**
This is not declaring a variable. Sholdn't trigger this rule

**What actually happened? Please include the actual, raw output from ESLint.**
/Users/qiongen/Desktop/red/fe-platform/src/app/controller/ci.ts
  96:7  error  Unexpected use of 'name'  no-restricted-globals

✖ 1 problem (1 error, 0 warnings)

**Are you willing to submit a pull request to fix this bug?**

**Comment by anikethsaha** [comment]
Thanks for the issue.

`no-restricted-globals` doesnt support `ts` (and `decorators`). You can request for the support in [`typescript-eslint`] (https://github.com/typescript-eslint/typescript-eslint) repo. In the meantime you can disable this rule.

**Comment by mdjermanovic** [comment]
@Edge00 can you try with the latest version of `@typescript-eslint/parser`?

If there's still a problem, then this would be a bug in `@typescript-eslint/scope-manager` that should be reported on https://github.com/typescript-eslint/typescript-eslint repo. This rule should work well with TS code as long as the scope analysis is correct.

**Comment by JanJakes** [comment]
Seeing this with ESLint 7.18.0 and `@typescript-eslint/parser` 4.14.0 (latest version).

**Comment by mdjermanovic** [comment]
I can reproduce this with the latest `@typescript-eslint/parser` 4.14.0. It doesn't happen with 4.13.0.

It looks like the problem has been already fixed by https://github.com/typescript-eslint/typescript-eslint/pull/2943 as it works well with 4.14.1-alpha.2.

The solution at the moment would be to use 4.13.0 or 4.14.1-alpha.2 until the next version (on Monday).

https://github.com/typescript-eslint/typescript-eslint#package-versions

**Comment by Edge00** [comment]
@anikethsaha @mdjermanovic  Thanks for helping. since this is a bug with `typescript-eslint`. i'll close this issue. Thanks again!
