### ISSUE TITLE
How to get an eslint plugin version using CLI ?

### ISSUE THREAD

**Issue by nvuillam** [eslint/eslint#14031]
I need to be able to retrieve the version of an eslint plugin using command line

Is there a way to do that with eslint ? 

Even a command returning all plugins versions would be ok, as I can parse the stdout with a regex

Thanks 

( related to https://github.com/ota-meshi/eslint-plugin-jsonc/issues/30 )

**Comment by anikethsaha** [comment]
Thanks for the repo . 

I don't think it is possible with eslint's CLI. may be the `--debug` may list that (not sure tho). 
you can use `npm list` command. eg. `npm list <plugin-name>` or `npm list --depth=0 | grep "<plugin-name>"`

**Comment by nvuillam** [comment]
Thanks a lot for your reply, `npm list eslint-plugin-jsonc` perfectly did the job :)

https://nvuillam.github.io/mega-linter/descriptors/json_eslint_plugin_jsonc/#eslint-plugin-jsonc-documentation
