### ISSUE TITLE
func-call-spacing

### ISSUE THREAD

**Issue by pistone** [eslint/eslint#14048]
**Tell us about your environment**

* **ESLint Version:** v7.18.0
* **Node Version:** v14.15.1
* **npm Version:** v6.14.8

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
default?

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  'env': {
    'browser': true,
    'es2021': true,
  },
  'extends': [
    'google',
  ],
  'parser': '@typescript-eslint/parser',
  'parserOptions': {
    'ecmaVersion': 12,
    'sourceType': 'module',
  },
  'plugins': [
    '@typescript-eslint',
  ],
  'rules': {
    'func-call-spacing': 2,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const x = new Map<number, (y:number)=>number> ();
console.log(x);
```

```bash
npx eslint temp.ts
```

**What did you expect to happen?**
The space before '(y:number)' looks fine to me.

**What actually happened? Please include the actual, raw output from ESLint.**
 1:26  error  Unexpected whitespace between function name and paren  func-call-spacing

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mdjermanovic** [comment]
Hi @pistone, thanks for the issue!

You can use [@typescript-eslint/func-call-spacing](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/func-call-spacing.md) rule as a replacement for the core `func-call-spacing` rule:

```js
{
  // note you must disable the base rule as it can report incorrect errors
  "func-call-spacing": "off",
  "@typescript-eslint/func-call-spacing": ["error"]
}
```

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code

**Comment by pistone** [comment]
@mdjermanovic Thanks for the suggestion. I tried that:

```js
module.exports = {
  'env': {
    'browser': true,
    'es2021': true,
  },
  'extends': [
    'google',
  ],
  'parser': '@typescript-eslint/parser',
  'parserOptions': {
    'ecmaVersion': 12,
    'sourceType': 'module',
  },
  'plugins': [
    '@typescript-eslint',
  ],
  'rules': {
    'func-call-spacing': "off",
    '@typescript-eslint/func-call-spacing': ["error"],
  },
};
```

But I still got:

```
F:\test\temp.ts
  1:45  error  Unexpected whitespace between function name and paren  @typescript-eslint/func-call-spacing
```

**Comment by pistone** [comment]
Never mind. I was looking at the wrong column. Thanks.
