### ISSUE TITLE
Default ignore results in top-level node_modules directory to be traversed

### ISSUE THREAD

**Issue by twelve17** [eslint/eslint#14047]
Through observing eslint output with `--debug`, it appears that the top level `node_modules` directory is being traversed even though it is going to be ignored altogether.

What I believe is happening is that the default glob of `/**/node_modules/*` is intending to ignore any nested `node_modules` folders, but nevertheless causes eslint to inspect the top-level `node_modules` in the process.

Debug output (edited for brevity):

```
2021-01-27T12:51:14.840Z eslint:cli CLI args: [ '--ext', 'mjs', '.', '--debug' ]
2021-01-27T12:51:14.857Z eslintrc:ignore-pattern   processed: { basePath: '/my/repo', patterns: [ '/**/node_modules/*' ] }
...
2021-01-27T12:51:14.863Z eslint:file-enumerator Enter the directory: /my/repo/node_modules
...
# now it checks every folder in node_modules

2021-01-27T12:51:14.864Z eslintrc:ignore-pattern Check {
  filePath: '/my/repo/node_modules/@babel/',
  dot: false,
  relativePath: 'node_modules/@babel/',
  result: true
}

2021-01-27T12:51:14.864Z eslintrc:ignore-pattern Check {
  filePath: '/my/repo/node_modules/@eslint/',
  dot: false,
  relativePath: 'node_modules/@eslint/',
  result: true
}

# ... and so on
```

If I explicitly add the `node_modules` folder without the preceding `**/` glob, the top level `node_modules` folder is not traversed:

Config change:

```
  ignorePatterns: ['dist', 'example-app', 'node_modules']
```

Run again:

```
# my explicit ignore of node_modules is added to the list, in addition to the default /**/node_modules glob:

2021-01-27T12:59:04.217Z eslintrc:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/my/repo/', loose: false }, IgnorePattern { patterns: [ 'dist', 'example-app', 'node_modules' ], basePath: '/my/repo/', loose: false } ]
```

In the above run, eslint does *not* traverse the top node_modules folder.

To give an illustration of the difference, here are the debug line counts in both use cases:

```
# using default ignores
$ npx eslint --ext mjs . "--debug" 2>&1 | wc -l
    1783

# with extra node_modules ignore
$ npx eslint --ext mjs . "--debug" 2>&1 | wc -l
     187
```

I looked through  https://github.com/eslint/eslint/issues/5739 but wasn't able to come up with a connection.

**Tell us about your environment**

Node version: v14.15.1
npm version: v6.14.8
Local ESLint version: v7.18.0 (Currently used)
Global ESLint version: Not found

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

default

**Please show your full configuration:**

```js

  module.exports = {
    env: {
      browser: false,
      es2021: true
    },
    ignorePatterns: ['dist', 'example-app'],
    parserOptions: {
      ecmaVersion: 12,
      sourceType: 'module',
    }
  };

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
eslint --ext mjs . "--debug"
```

**What did you expect to happen?**

Did not expect eslint to traverse the top level `node_modules` folder.

**What actually happened? Please include the actual, raw output from ESLint.**

eslint traversed the top level `node_modules` folder,  only to ignore all the entries.

**Are you willing to submit a pull request to fix this bug?**

Yes.

**Comment by mdjermanovic** [comment]
Hi @twelve17, thanks for the issue!

ESLint has to check the content of `node_modules` because it is possible to unignore some subdirectories.

The default pattern `/**/node_modules/*` intentionally has `/*` at the end to allow that (please see the first comment in https://github.com/eslint/eslint/commit/8851dddba842d5fe6d10ab91ca6477e1aa5c37d4).

I don't think that shallow-checking the content of `node_modules` affects the performance much, but if you want to prevent ESLint from doing that, you can add the following pattern:

```
/**/node_modules/
```

**Comment by twelve17** [comment]
Hi @mdjermanovic  - Thanks for pointing that out. Sounds like it is expected behaviour, then. I'll close this out.  Cheers!
