### ISSUE TITLE
100% CPU with VSCode open in VSCode

### ISSUE THREAD

**Issue by Timmmm** [eslint/eslint#14056]
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 14.5.0
* **npm Version:** 6.14.9

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

    @typescript-eslint/parser

**Please show your full configuration:**

https://github.com/microsoft/vscode/blob/master/.eslintrc.json

<details>
<summary>Configuration</summary>

It's very long, just go here: https://github.com/microsoft/vscode/blob/master/.eslintrc.json

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

1. Clone VSCode.
2. Open it in VSCode.
3. Open a .ts file. E.g. `viewImpl.ts`.
4. Wait a while.

**What did you expect to happen?**

Nothing.

**What actually happened? Please include the actual, raw output from ESLint.**

100% CPU in the Code Helper process. VSCode's process viewer shows that ESLint is the culprit. Or maybe tsserver. I'm not exactly sure what that is.

![image](https://user-images.githubusercontent.com/376842/106385512-90454580-63c8-11eb-9596-d9d5165cb564.png)

In any case, I expect some CPU usage while I'm editing the file, but not while I just have it open idle.

**Are you willing to submit a pull request to fix this bug?**

No

**Comment by nzakas** [comment]
Thanks for the report. We actually don't maintain the VS Code ESLint plugin. You may want to open an issue on their repo: https://github.com/Microsoft/vscode-eslint
