### ISSUE TITLE
Support/Document `:has()` selectors (per esquery update)

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#14076]
**The version of ESLint you are using.**

7.19.0

**The problem you want to solve.**

`esquery` has just published a new release with the support for custom visitor keys (that may contribute to fixing #13639 ), which brings parser-independent support including for `has:()` selectors.

However, https://github.com/eslint/eslint/blob/master/docs/developer-guide/selectors.md does not indicate support for `:has()`, and per https://github.com/eslint/eslint/issues/13639#issuecomment-774577141 there may be some work to do to be able to support them:

> ESLint selectors are using esquery, but we're also doing some optimizations and calculating specificity in [NodeEventGenerator](https://github.com/eslint/eslint/blob/master/lib/linter/node-event-generator.js), so it's possible that some additional work has to be done before we can say that ESLint fully supports new selectors.

(Note that in addition to `:has()` the "subject" indicator is also supported, but per https://github.com/estools/esquery/pull/61 , that implementation is buggy while the `:has()` one was working enough to be used as a base for the former–though with one issue on relative keys mentioned there.)

**Your take on the correct solution to problem.**

No special take. Ideally would provide support for the selectors and update the docs.

**Are you willing to submit a pull request to implement this change?**

No.

**Comment by mdjermanovic** [comment]
I think this could be very useful for configuring rules such as [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax), but we should probably add a note that it [traverses subtrees](https://github.com/estools/esquery/blob/7c3800a4b2ff5c7b3eb3b2cf742865b7c908981f/esquery.js#L129), so a rule written in a way that uses ESLint's traversal instead of `:has()` may have a much better performance.

**Comment by mdjermanovic** [comment]
I'll champion this.

**Comment by nzakas** [comment]
@mdjermanovic whats the next step here? Do we need an RFC?

**Comment by mdjermanovic** [comment]
> @mdjermanovic whats the next step here?

The proposal is waiting for more opinions from the team.

> Do we need an RFC?

Hm, it looked like a small change so I wasn't thinking about RFC. It's indeed a change in the core, so by our policy it would need an RFC. What do you think?

**Comment by nzakas** [comment]
Okay, be sure to tag in other folks when you’re looking for more opinions. That way we know what is stopping progress.

I’m 👍. I was just concerned about the note about NodeEventGenerator and didn’t know if we needed some investigation as to the changes necessary. If it’s really just a plug and play change with minimal other code necessary, I think we can do it without an RFC.

**Comment by nzakas** [comment]
@btmills can you chime in on this?

**Comment by btmills** [comment]
:+1:, marking as accepted and moving to ready to implement. I don’t see a need for an RFC.

**Comment by snitin315** [comment]
Can I work on this one?

**Comment by mdjermanovic** [comment]
@snitin315 sure, thanks!

**Comment by mdjermanovic** [comment]
> while the :has() one was working enough to be used as a base for the former–though with one issue on relative keys mentioned there

@brettz9 the issue on relative keys is that syntax such as `:has( > Identifier)` isn't supported yet?

**Comment by brettz9** [comment]
Right. A PR in https://github.com/estools/esquery/pull/61 attempted to offer it, but the review comments were never completed.

**Comment by mdjermanovic** [comment]
Is it expected behavior that selectors in the `:has()` list can match the element itself, or only its descendants?

```js
/* eslint no-restricted-syntax: ["error", "Literal:has(Literal)"] */

1 // error
```

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtc3ludGF4OiBbXCJlcnJvclwiLCBcIkxpdGVyYWw6aGFzKExpdGVyYWwpXCJdICovXG5cbjEgLy8gZXJyb3IiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by brettz9** [comment]
Hmmm. The tests don't refer to self-referential elements, and the only other reference I see is in the README comparing it to the CSS pseudo-selector: https://drafts.csswg.org/selectors-4/#has-pseudo . So I'm not sure.

In the latest esquery on `master`/1.4.0, it doesn't error but returns the same `Literal` as itself.

I wouldn't expect this to work myself, but that's just my own sense.

**Comment by mdjermanovic** [comment]
> In the latest esquery on `master`/1.4.0, it doesn't error but returns the same `Literal` as itself.

Sorry, by "error" I meant a linting problem, i.e., the selector in the `no-restricted-syntax` config matches literal `1`.

I filed an issue in esquery repo: https://github.com/estools/esquery/issues/122

**Comment by nzakas** [comment]
Based on implementation issues, we [decided](https://github.com/eslint/eslint/pull/14674#discussion_r715873447) not to move forward with this feature. The selector has performance issues and we would prefer it not be used in rules.
