### ISSUE TITLE
@babel/code-frame v7.12.13 breaks codeframe formatter

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#14087]
**The version of ESLint you are using.**

ESLint v7.19.0

**The problem you want to solve.**

[codeframe formatter](https://eslint.org/docs/user-guide/formatters/#codeframe) uses `@babel/code-frame`.

The latest `@babel/code-frame` v7.12.13 made an intentional change babel/babel#12567 to trim trailing space after `|` if the source code line is empty.

Before:

```
  1 | <LF>
> 2 | foo;<LF>
    | ^<LF>
  3 | <LF>
```

After:

```
  1 |<LF>
> 2 | foo;<LF>
    | ^<LF>
  3 |<LF>
```

We agreed that this would be a breaking change in the `codeframe` formatter, and merged https://github.com/eslint/eslint/pull/14067 for ESLint v7.20.0 release to pin `"@babel/code-frame": "7.12.11"` in order to prevent the change.

However, we probably don't want to stay on `"@babel/code-frame": "7.12.11"` forever.

**Your take on the correct solution to problem.**

Upgrade `@babel/code-frame` dependency in ESLint v8.0.0 as a breaking change in the `codeframe` formatter.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by mdjermanovic** [comment]
This will become obsolete if we remove the `codeframe` formatter per https://github.com/eslint/eslint/issues/14277.

**Comment by btmills** [comment]
Since we decided to remove some formatters, including `codeframe`, in ESLint v8.0.0, we can close this.
