### ISSUE TITLE
[max-statements]: add option to not count lines as statements if they start as filter regexp

### ISSUE THREAD

**Issue by natlibfi-jonollil** [eslint/eslint#14093]
**What rule do you want to change?**
max-statements

**Does this change cause the rule to produce more or fewer warnings?**
Fewer warnings "faulty"

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option: ignorePatterns

**Please provide some example code that this change will affect:**
Option type array of objects. E.g. [{pattern: '/^logger.info/', count : 2, severity: error}, {pattern: '/^logger.info/', count : 2, severity: error}]

pattern: RegExp pattern
count : Count how many times pattern in ignored. Defaults to 0 as unlimited
severity: If number of matches exceeds given count number severity level of ESlint error is thrown. Defaults to warning

```js
const testers = ignorePatterns.map(pattern => new RegExp(pattern));
if (!testers.some(tester => tester.test(line)); {
  // ignore line as statement, but count as used line to tester
} 
```

**What does the rule currently do for this code?**
At the moment rule counts all logging information as statement line.
In our case of using winston logger one function might have 1 HTTP call logging, 2-3 verbose logging, 1 info logging, 2-5 debug logging and even some silly logging. Those alone would take major part of our recommended (default ) 10 statements of function. And without those logging information / levels debugging  work slows down. Same time not everything is important so some control over how many of those can be made in single function is nice to have

**What will the rule do after it's changed?**
I hope it does not count them as statements. And gives some options to rule logging behavior

**Are you willing to submit a pull request to implement this change?**
If i have time

**Comment by mdjermanovic** [comment]
Hi @natlibfi-jonollil, thanks for the issue!

The team has made the difficult decision to [freeze stylistic rules](https://eslint.org/blog/2020/05/changes-to-rules-policies), so we won't be able to accept this proposal. I'm closing this issue per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates).

Thanks for contributing, and you can always make a custom rule or a [plugin](https://eslint.org/docs/developer-guide/working-with-plugins).
