### ISSUE TITLE
Update the list of style guides to choose from

### ISSUE THREAD

**Issue by iamchathu** [eslint/eslint#14101]
**The version of ESLint you are using.**
^7.18.0

**The problem you want to solve.**
In the init wizard there are three pre defined code styles to select. But there is opinionated Javascript Standard config to choose. Please for more informations go though this [issue](https://github.com/standard/standard/issues/78). 

**Your take on the correct solution to problem.**
Since as they claim it not "Standard" standard better not to add to default selection list since many of newbies might ends up thinking it's JS Standard.

**Are you willing to submit a pull request to implement this change?**
Will go though and see if I can contribute on this.

**Comment by ljharb** [comment]
I think that the name "standard" makes it inappropriate to include in eslint's list even as an option.

Those that prefer standard's style generally use `standard` and not eslint. standard isn't a styleguide either - it's just a config. A styleguide is written out with prose.

**Comment by iamchathu** [comment]
Seems this can be removed from the code in [the line](https://github.com/eslint/eslint/blob/9d6063add931f0803cae1676d5df307baf114360/lib/init/config-initializer.js#L533).

**Comment by nzakas** [comment]
Thanks, we’ve had this option for years and it hasn’t caused any problems. We realize some people have a problem with the name of the style, but we do have two other options to choose from, and Airbnb in particular is quite popular. I don’t see a reason to change anything at this point.
