### ISSUE TITLE
`semi` `beforeStatementContinuationChars` without `never`

### ISSUE THREAD

**Issue by Y-Less** [eslint/eslint#14104]
**What rule do you want to change?**

`semi`

**Does this change cause the rule to produce more or fewer warnings?**

More.

**How will the change be implemented? (New option, new default behavior, etc.)?**

Slight tweak to when the option can be used.  Currently `beforeStatementContinuationChars` requires `never`, but you might not care if they're missing or not, as long as they are always used in ambiguous cases.

**Please provide some example code that this change will affect:**

```js
const a = 5
const b = c
(a);
```

**What does the rule currently do for this code?**

With `always`, `const a = 5` will give a warning/error.
With `never`, `(a);` will give a warning/error.
With `beforeStatementContinuationChars` and `never`, `const b = c` will give a warning/error.

**What will the rule do after it's changed?**

If we can enable `beforeStatementContinuationChars` without `never` the first and last lines will be ignored - we don't care if there's a semicolon or not; however, we can still get a diagnostic in the case where ASI doesn't apply.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by Y-Less** [comment]
A clearer explanation might be to add a top-level `any` option, thus the run can be:

```js
"semi": [ "error", "any", { "beforeStatementContinuationChars": "always" } ]
```

**Comment by mdjermanovic** [comment]
Hi @Y-Less, thanks for the issue!

The team has made the difficult decision to [freeze stylistic rules](https://eslint.org/blog/2020/05/changes-to-rules-policies), so we won't be adding new options to the `semi` rule. I'm closing this issue per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates).

> we can still get a diagnostic in the case where ASI doesn't apply

I think this is already covered by the [no-unexpected-multiline](https://eslint.org/docs/rules/no-unexpected-multiline) rule.
