### ISSUE TITLE
no-useless-constructor in typescript 

### ISSUE THREAD

**Issue by Luxcium** [eslint/eslint#14118]
### The rule should be able to discriminate from when using TypeScript *parameter properties*

```typescript
class OctoCat {
  readonly numberOfLegs: number = 8;
  constructor(readonly name: string) {}
}

let gitHubCat = new OctoCat("Cat with the 8 strong legs");
gitHubCat.name;
```

> Notice how we dropped theName altogether and just use the shortened readonly name: string parameter on the constructor to create and initialize the name member. We’ve consolidated the declarations and assignment into one location.
> Parameter properties are declared by prefixing a constructor parameter with an accessibility modifier or readonly, or both. Using private for a parameter property declares and initializes a private member; likewise, the same is done for public, protected, and readonly.
― ***From TypeScript Handbook*** [(Link to parameter properties section!)](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties)

**Tell us about your environment**

* **ESLint Version:**
 ⑆  7.16.0
* **Node Version:**
 ⑆  15.6.0
* **npm Version:**
  ⑆  7.4.0
* **TypeScript Version:**
  ⑆  4.1.3
* **Operating System:** 
⑆  Linux  5.10.13-100.fc32.x86_64 GNU/Linux (Fedora 23)

**What parser (`@typescript-eslint/parser`) are you using?**
 ⑆  @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration (partial)</summary>

```jsonc
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "extends": [
    "plugin:jsonc/auto-config",
    "plugin:jsonc/base",
    "plugin:jsonc/recommended-with-json",
    "plugin:jsonc/recommended-with-json5",
    "plugin:jsonc/recommended-with-jsonc",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint",
    "prettier/babel",
    "prettier/flowtype",
    "prettier/react",
    "prettier/standard",
    "prettier/unicorn",
    "prettier/vue"
  ],
  "env": {
    "browser": true,
    "es2021": true,
    "node": true,
    "jest": true
  },
  "plugins": [
    "@typescript-eslint",
    "eslint-plugin-tsdoc",
    "fp",
    "functional",
    "import",
    "jsdoc",
    "prettier",
    "promise",
    "radar",
    "security",
    "simple-import-sort",
    "sort-keys-fix",
    "unicorn"
  ],
  "rules": {
    "no-useless-constructor": "error", 
 /* [ ... Link below ... ] */
  },
  "overrides": [
    {
      // enable the rule specifically for json files
      "files": [
        "*.json",
        "*.jsonc"
      ],
      "rules": {
        "semi": 0
      }
    }
  ]
}

```
</details>

⑆  Configuration (complete): [github.com/Luxcium/questrade-ts/ ... /.eslintrc](https://github.com/Luxcium/questrade-ts/blob/bfebf8a57bc968be44d68e42bbbd650f033215a0/.eslintrc#L1)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

⑆  [Actual source code causing the issue](https://github.com/Luxcium/questrade-ts/blob/bfebf8a57bc968be44d68e42bbbd650f033215a0/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9)

```typescript
  constructor(protected handlerOptions: ProxyHandlerOptions) {
    // empty comment is to avoid → Unexpected empty constructor.eslint (no-empty-function)
  }

```
<details>
<summary>The command used to run ESLin</summary>

```bash
⑆ yarn linting
yarn run v1.22.10
$ yarn run pretty:fix  # prettier --check --write --config .prettierrc './src/**/*.ts'  || exit 11
$ git add .; prettier --config "./.prettierrc" --loglevel log -c --write "./src/**/*.ts" || exit 11
Checking formatting...
All matched files use Prettier code style!
$ eslint "./src/**/*.ts" --format=stylish --fix || exit 15

https://github.com/Luxcium/questrade-ts/blob/bfebf8a57bc968be44d68e42bbbd650f033215a0/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9
  9:3  error  Useless constructor  no-useless-constructor

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 15.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
⑆ 
```
</details>

**What did you expect to happen?**
⑆  No report of such a problem when using ***TypeScript parameter properties***

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

```bash
$ eslint "./src/**/*.ts" --format=stylish --fix || exit 15

https://github.com/Luxcium/questrade-ts/blob/bfebf8a57bc968be44d68e42bbbd650f033215a0/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9
  9:3  error  Useless constructor  no-useless-constructor

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 15.
```

[![Screenshot_20210216_070625](https://user-images.githubusercontent.com/42672814/108061235-04692580-7026-11eb-9e71-aaacbc27fd95.png)](https://github.com/Luxcium/questrade-ts/blob/bfebf8a57bc968be44d68e42bbbd650f033215a0/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9)

```bash

$ eslint "./src/**/*.ts" --format=stylish --fix || exit 15

https://github.com/Luxcium/questrade-ts/blob/23840b5d8713ae29ce13384acf1e1298c846f72f/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9

  9:3   error  Useless constructor           no-useless-constructor
  9:62  error  Unexpected empty constructor  no-empty-function

✖ 2 problems (2 errors, 0 warnings)

error Command failed with exit code 15.
```

[![Screenshot_20210216_070148](https://user-images.githubusercontent.com/42672814/108060464-e5b65f00-7024-11eb-8aa3-1a0db7eaf7ac.png)](https://github.com/Luxcium/questrade-ts/blob/23840b5d8713ae29ce13384acf1e1298c846f72f/src/resources/side-effects/proxies/core/reflexion-logger-proxy-handler-abstarct-class.ts#L9)

<details>
<summary>VsCode ESLint Output</summary>
```log
[Info  - 07 h 13 min 22 s] ESLint server is starting
[Info  - 07 h 13 min 22 s] ESLint server running in node v12.18.3
[Info  - 07 h 13 min 22 s] ESLint server is running.
[Info  - 07 h 13 min 23 s] ESLint library loaded from: ./node_modules/eslint/lib/api.js
```
</details>

![Screenshot_20210216_071507](https://user-images.githubusercontent.com/42672814/108061732-bb65a100-7026-11eb-8559-856afe9b103a.png)

**Are you willing to submit a pull request to fix this bug?**
⑆  I am unable to produce such a fix

**Comment by ljharb** [comment]
You can already achieve this with the typescript eslint plugin: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md

**Comment by mdjermanovic** [comment]
Hi @Luxcium, thanks for the issue!

The core `no-useless-constructor` rule doesn't support typescript, so you would probably want to use [@typescript-eslint/no-useless-constructor](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md) rule instead:

```js
{
  // note you must disable the base rule as it can report incorrect errors
  "no-useless-constructor": "off",
  "@typescript-eslint/no-useless-constructor": ["error"]
}
```

For the list of `@typescript-eslint/eslint-plugin` rules that should be used as replacements for core rules, please see [TypeScript ESLint FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code).

**Comment by Luxcium** [comment]
Thank you very much!

add @typescript-eslint/eslint-plugin configs

thanks to 
@mdjermanovic
@ljharb
https://github.com/Luxcium/questrade-ts/commit/c6e62720510df12e63b5b97180e71b4c6da52636 closes https://github.com/eslint/eslint/issues/14118
