### ISSUE TITLE
'--fix-list' command line option to display the list of active fixes

### ISSUE THREAD

**Issue by Yzrsah** [eslint/eslint#14111]
**Proposal:**

Command line option: --fix-list

```
Fixing problems:
  --fix                          Automatically fix problems
  --fix-dry-run                  Automatically fix problems without saving the changes to the file system
  --fix-list                     Print the list of fixes that --fix can apply
  --fix-type Array               Specify the types of fixes to apply (problem, suggestion, layout)
```

It would be great if there was a way to find out which fixes are currently active for a given eslint setup.
`--fix-dry-run` does not tell this information because it only tells you there's a fix if it finds a problem.

For example I'm using some eslint config packages that use other eslint configs + plugins and have some inherited hierarchy in `extends`, and I want to see a list of which fixes are active for the setup.

I can go through eslint config packages and their sub dependencies configs + plugins and check every rule to see if there's a fix for something that's active. But it's tedious and a few hours can slip by just going through stuff. If it's for my project I don't mind -- but I loaded someone else's repo and just wanted to check which fixes are active without getting distracted by taking apart their whole eslint config setup.

**Comment by mdjermanovic** [comment]
Hi @Yzrsah, thanks for the issue!

I'm not sure that I understand the request. Would you like to see all fixes that can be applied to the given source code, or a list of all enabled rules?

**Comment by Yzrsah** [comment]
@mdjermanovic Yes, to see all enabled fixes that can be applied to the given source code is exactly it.

But also being able to see the list of all enabled rules would be fabulous too.

**Comment by mdjermanovic** [comment]
> Yes, to see all enabled fixes that can be applied to the given source code is exactly it.

ESLint returns fixes as a part of linting results which are passed to formatters, so an additional option seems redundant.

[json formatter](https://eslint.org/docs/user-guide/formatters/#json) outputs entire linting results, including fixes.

You can run `eslint . -f json` (without `--fix`), and then look for `"fix":{ ... }` fields in the output, or pipe the output to a script that extracts fixes from the given JSON.

You can also write a [custom formatter](https://eslint.org/docs/developer-guide/working-with-custom-formatters) that prints only fixes.

> But also being able to see the list of all enabled rules would be fabulous too.

This can be done with the [--print-config](https://eslint.org/docs/user-guide/command-line-interface#-print-config) option.

**Comment by nzakas** [comment]
Closing as there are other solutions available.
