### ISSUE TITLE
[Typescript] More human-user friendly type errors

### ISSUE THREAD

**Issue by exapsy** [eslint/eslint#14124]
(I apologize if it's not the right place to write Typescript linter eslint request)

**The version of ESLint you are using.**
VSCode ESLint plugin - 2.1.14
package.json: eslint - 7.11

**The problem you want to solve.**
Currently, Typescript type linting is really verbose. You literally have to scroll through a whole page to understand what exactly is the type error. It prints the whole type.

![image](https://user-images.githubusercontent.com/9019120/108591698-b2503900-7372-11eb-9476-b82000f0ff05.png)

This would be equivelant to C++ print the whole class every-time there's a definition of the wrong type.

> Person does not equal Dog? Lets print the whole class definitions. `Class { void Dog::Lick(times: number), void Woof(times: uint16, loudness: int32), void Zoomies(distance: int32) } does not equal in Class { void::Walk(...), void Eat::(...) } ` ... 

you get the point. But the error instead is `Error class Person does not equal or inherit from Dog` or something like that

That's really too much and too unnecessary information 99% of the time and you spend minutes just trying to figure out what's wrong with your type. It's counter-intuitive of what its meant to be. 

It doesn't help the user figure out exactly what's wrong even though the typescript linter knows or may know exactly what's wrong.

**Your take on the correct solution to problem.**

The name and source of the type would be far of a better solution I think. Instead of demonstrating the type exactly, something like `interface "User" does not equal interface "UserData": "UserData" missing "fullname: string" / "UserData" has wrong type "number" for field "fullname"` would be much more helpful for the end user than read a whole list describing each type in a very verbose way without giving helpful information about the exact reason of the error outcome.

**Are you willing to submit a pull request to implement this change?**

No. Just a feature request that I find useful since it has been troubling me for years and I think it could make a perfect addition and improvement for the eslint linter in the future.

**Comment by mdjermanovic** [comment]
Hi @exapsy, thanks for the issue!

ESLint doesn't produce those messages. I believe this is a question for https://github.com/microsoft/TypeScript repository.

I'm closing this issue since it isn't related to ESLint.

**Comment by exapsy** [comment]
Thanks for the response @mdjermanovic ! I see, thanks for the notice. :)

In any case, for anyone who may still look at this issue in the future:

Typescript 4.2+ supports smarter type alias preservation, which is exactly what is demonstrated in this issue! 

If I knew I wouldn't have made the issue at all :P But it was released literally yesterday.

https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#smarter-type-alias-preservation

**Typescript 4.1 Playground**

![image](https://user-images.githubusercontent.com/9019120/108995787-43424f80-76a6-11eb-9322-00106d09507d.png)

**Typescript 4.2 Playground**

![image](https://user-images.githubusercontent.com/9019120/108995760-3aea1480-76a6-11eb-92b0-5b02b527d67e.png)

Won't continue the discussion any further as it's not in topic with this repository. But just in case anyone falls in this issue it's good to know it has been resolved anyways.
