### ISSUE TITLE
[proposal] merge `unicorn/prefer-ternary` into `no-else-return` with new option `preferTernary `

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#14121]
**What rule do you want to change?**

[`no-else-return`](https://eslint.org/docs/rules/no-else-return)

**Does this change cause the rule to produce more or fewer warnings?**

Yes

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option: `preferTernary: true`

**Please provide some example code that this change will affect:**

```js
function a() {
  if (test) {
	return 1;
  } else {
    return 2;
 }
}
```

**What does the rule currently do for this code?**

```js
function a() {
  if (test) {
	return 1;
  }

  return 2;
}
```

**What will the rule do after it's changed?**

```js
function a() {
  return test ? 1 : 2;
}
```

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by mdjermanovic** [comment]
Hi @JounQin, thanks for the issue!

The team has made the difficult decision to [freeze stylistic rules](https://eslint.org/blog/2020/05/changes-to-rules-policies), so we won't be able to accept this proposal.

I'm closing this issue per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates).

**Comment by JounQin** [comment]
@mdjermanovic Thanks for your clarify.
