### ISSUE TITLE
I can't use static properties in class

### ISSUE THREAD

**Issue by lth707** [eslint/eslint#14128]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**
![image](https://user-images.githubusercontent.com/16285977/108824694-fc4c4f80-75fc-11eb-8a06-e1f3fe31427d.png)

**Your take on the correct solution to problem.**

**Are you willing to submit a pull request to implement this change?**

**Comment by g-plane** [comment]
Hello, static properties in class is still in Stage 3, while ESLint only supports Stage 4 syntaxes by default. You can use [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) as an alternative parser.

**Comment by jayshah123** [comment]
https://github.com/babel/babel/issues/12864 is probably related.

**Comment by nzakas** [comment]
Closing, as experimental syntax isn’t yet supported.

**Comment by voxpelli** [comment]
Now this has actually moved to stage 4, just mentioning it here for reference, I understand that a new issue should be opened: https://github.com/tc39/proposals/commit/5435781b2f252945694618f22f5956f17a639d3a
