### ISSUE TITLE
Directories that exactly match a glob, but are eslintignored, throw error

### ISSUE THREAD

**Issue by amiller-gh** [eslint/eslint#14149]
https://github.com/eslint/eslint/issues/12854

**Tell us about your environment**

* **ESLint Version:** 7.21.0
* **Node Version:** 12.18.3
* **npm Version:** 6.14.9
* **Operating System:** MacOS

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
`@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports =  {
  parser:  '@typescript-eslint/parser',  // Specifies the ESLint parser
  ignorePatterns: [
    'node_modules/**',
    '/node_modules/',
    'node_modules',
    '**/node_modules/**',
    'node_modules/microevent.ts/**',
    'dist',
    'types-local',
    'graphql.ts',
    'packages/@universe/aether/cjs/**',
    'packages/@universe/aether/esm/**',
  ],
  extends:  [
    'preact',
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  parserOptions:  {
    ecmaVersion:  2018,  // Allows for the parsing of modern ECMAScript features
    sourceType:  'module',  // Allows for the use of imports
    ecmaFeatures:  {
      jsx:  true,  // Allows for the parsing of JSX
    },
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
  plugins: ['simple-import-sort'],
  rules:  {
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
    'sort-imports': 'off',
    'import/order': 'off',
    semi: [ 'error', 'always' ],
    'jsx-quotes': [ 'error', 'prefer-double' ],
    'react/jsx-curly-brace-presence': [ 'error', { props: "never", children: "never" }],
    'max-len': [ 'error', { code: 180, tabWidth: 2 }],
    'no-multiple-empty-lines': [ 'error', { max: 1 }],
    'no-var': ['error'],
    'space-before-function-paren': [ 'error', 'never' ],
    'no-return-assign': 'off',
    'no-unused-expressions': 'off',
    'brace-style': [ 'error', 'stroustrup', { allowSingleLine: true }],
    'comma-dangle': [ 'error', 'always-multiline' ],
    "array-bracket-spacing": [ "error", "always", {
      singleValue: false,
      objectsInArrays: false,
      arraysInArrays: false,
    }],
    'object-curly-spacing': [ 'error', 'always' ],
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': [ 'error', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],

    // TODO: Fully enable these rules.
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    "react-hooks/rules-of-hooks": "warn",
    "react-hooks/exhaustive-deps": "warn",
    "react/no-deprecated": "warn",
    "react/no-did-mount-set-state": "warn",
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

There is a package names `microevent.ts`. It is depended on by `react-dev-utils` and `@storybook/react`, which is how it got into my repo.

**What did you expect to happen?**
The lint command to work!

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

When installed, and when using a glob pattern to match typescript files `**.*.ts`, the eslint command will always fail with 

```
Oops! Something went wrong! :(

ESLint: 7.20.0

No files matching the pattern "node_modules/microevent.ts" were found.
Please check for typing mistakes in the pattern.

<!-- Paste the source code below: -->
```bash
npm install microevent.ts
eslint **/*.ts **/*.tsx
```

**Steps to reproduce this issue:**
See above.

1. Install microevent.ts
1. Use the glob `**/*.ts`
1. Panic.

**Are you willing to submit a pull request to fix this bug?**
Happily! I have one half baked here https://github.com/eslint/eslint/pull/14148. 

I'm sure there is a better place to put this logic earlier in the code, and I may need help with testing. Guidance would be appreceated.

**Comment by amiller-gh** [comment]
Obviously, the companion PR's tests don't pass :) 

However, it does illustrate where the problem occurs. Would love additional guidance for where this check should actually live in the codebase.

https://github.com/eslint/eslint/pull/14148

And for reference, this issue appears to have been brought up in the past: https://github.com/eslint/eslint/issues/12854

**Comment by mdjermanovic** [comment]
Hi @amiller-gh, thanks for the issue!

> `eslint **/*.ts **/*.tsx`
>
> `No files matching the pattern "node_modules/microevent.ts" were found.`

I think this is expected behavior. ESLint throws an error if some of the given patterns doesn't match any files, because that usually indicates that the pattern was not the intended one and should be corrected.

In this case, you're not using quotes, so your shell probably expands `**/*.ts` to a list of individual paths and ESLint gets `node_modules/microevent.ts` as a CLI argument. As that pattern doesn't match any files, ESLint throws an error.

Can you try with `eslint "**/*.ts" "**/*.tsx"`?

**Comment by amiller-gh** [comment]
🤦  yup that was it. Hopefully this issue can help someone else who runs into this glob quirk!

Thank you for your help and patience :)
