### ISSUE TITLE
eslint --init: Parsing error: Cannot use keyword 'await' outside an async function

### ISSUE THREAD

**Issue by VyrekXD** [eslint/eslint#14156]
**Tell us about your environment**

* **ESLint Version:**
* 7.21.0
* **Node Version:**
* 15
* **npm Version:**
* 7.5.4
* **Operating System:** 
Windows 7

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
n/a

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
npx eslint --init
```

**What did you expect to happen?**
To make my eslint file

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
Oops! Something went wrong! :(

ESLint: 7.21.0

Error: (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\src\index.js:9:1) Parsing error: Cannot use keyword 'await' outside an async function
    at getSourceCodeOfFile (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\lib\init\source-code-utils.js:48:15)
    at C:\Users\user\Desktop\user\Bots\DoughnutSheriff\node_modules\eslint\lib\init\source-code-utils.js:93:28
    at Array.forEach (<anonymous>)
    at getSourceCodeOfFiles (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\lib\init\source-code-utils.js:92:15)
    at configureRules (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\lib\init\config-initializer.js:173:23)
    at processAnswers (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\lib\init\config-initializer.js:319:22)
    at C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\lib\init\config-initializer.js:629:28
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async main (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\node_modules\eslint\bin\eslint.js:137:9)

**Steps to reproduce this issue:**

1. Open a console
2. Use npm i -D eslint 
3. Use npx eslint --init
4. Do this config: To check syntax, find problems, and enforce code style, JavaScript modules (import/export), None of these, no, Node, Inspect my js files, src, JavaScript
5. At the 12 percent it gives the error 

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mdjermanovic** [comment]
Hi @VyrekXD, thanks for the issue!

> Error: (C:\Users\user\Desktop\Vyrek_DEV\Bots\DoughnutSheriff\src\index.js:9:1) Parsing error: Cannot use keyword 'await' outside an async function

ESLint's default parser doesn't support top-level `await`, as it is still a [stage 3](https://github.com/tc39/proposal-top-level-await#ecmascript-proposal-top-level-await) feature.

Per our [policy about experimental features](https://github.com/eslint/eslint#what-about-experimental-features), ESLint's parser will support the top-level `await` syntax if and when it reaches stage 4.

Until then, you can use ESLint with a [different parser](https://eslint.org/docs/user-guide/configuring/plugins#specifying-parser) that supports this syntax, like [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser).

Unfortunately, `eslint --init` doesn't provide an option to install `@babel/eslint-parser`, so the auto-config option ("Inspect my js files") cannot be used with source code files that can't be parsed by the default parser.

**Comment by mdjermanovic** [comment]
I'm closing this issue as it doesn't seem actionable.

A workaround can be to provide a pattern that will match only files without the top-level `await` syntax, and manually update the config with `@babel/eslint-parser` after `--init` finishes and creates an initial configuration file.

**Comment by vitaliytv** [comment]
Status update to Stage-4
https://github.com/tc39/proposal-top-level-await/commit/2762cc57808dd6c965257b5deec636362b4228de
