### ISSUE TITLE
Indent issue with complex template literals

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#14192]
**Tell us about your environment**

* **ESLint Version:** 7.21.0
* **Node Version:** 12.16.3
* **npm Version:** 7.6.1
* **Operating System:** OSX

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** Espree

**Please show your full configuration:** 

<details>
<summary>
Indent config
</summary>

```js
        indent: ['error', 4, {
            SwitchCase: 1,
            VariableDeclarator: 1,
            outerIIFEBody: 1,
            // MemberExpression: null,
            FunctionDeclaration: {
                parameters: 1,
                body: 1
            },
            FunctionExpression: {
                parameters: 1,
                body: 1
            },
            CallExpression: {
                arguments: 1
            },
            ArrayExpression: 1,
            ObjectExpression: 1,
            ImportDeclaration: 1,
            flatTernaryExpressions: false,
            ignoreComments: false
        }],
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
    if (query.astNode.arguments && query.astNode.arguments.length > 0) {
        output.push({
            name: 'inputs',
            type: 'lit-html',
            value: html`
                <section class="inputs">
                    <h3>Inputs:</h3>
                    ${query.astNode.arguments.map((input) => {
                        const inputType = schema.getType(getTypeName(input));
                        return html`
                            <div class="input-list">
                                <dd>${input.name.value}</dd>
                                <dt>
                                    ${!inputType.astNode ? getTypeDisplayName(input) : html`<a href=${`../input/${getTypeName(input)}.html`}>${getTypeDisplayName(input)}</a>`}
                                </dt>
                            </div>`;
                    })}
                </section>`
        });
    }
```

```bash
node ./node_modules/.bin/eslint .
```

**What did you expect to happen?**
No errors

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
  9:1   error  Expected indentation of 8 spaces but found 24         indent
  10:1   error  Expected indentation of 8 spaces but found 24         indent
  17:1   error  Expected indentation of 4 spaces but found 20         indent

**Steps to reproduce this issue:**
Code above will always report errors where it shouldn't.

**Are you willing to submit a pull request to fix this bug?**
No, sorry, I'm not touching indent rule.

**Comment by mdjermanovic** [comment]
Reopening as this hasn't been triaged yet.
