### ISSUE TITLE
[no-sequences] Add option to disable the "in-parentheses" exception

### ISSUE THREAD

**Issue by danielrentz** [eslint/eslint#14197]
Follow-up for bug report #14184

**What rule do you want to change?**
[no-sequences](https://eslint.org/docs/rules/no-sequences)

**Does this change cause the rule to produce more or fewer warnings?**
more warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
- New option that disables (or enables) the exception that sequences are allowed in parentheses.

**Please provide some example code that this change will affect:**

```js
if ((x1 === x2) && (y1, y2)) {
```
Intended was
```js
if ((x1 === x2) && (y1 === y2)) {
```
This real-life bug sneaked in after replacing a comparison function with the comparison operator
```js
- if (isEqual(x1, x2) && isEqual(y1, y2)) {
+ if ((x1 === x2) && (y1, y2)) {
```
It was hard to find because the sequence expression was hidden in a short-circuiting AND operator.

**What does the rule currently do for this code?**
Lets it pass.

**What will the rule do after it's changed?**
Warns for the sequence.

**Are you willing to submit a pull request to implement this change?**
~~No.~~ Yes.

**Comment by aladdin-add** [comment]
@danielrentz no worries, I will champion the change. :)

it may take a while for the issue being reviewed by other team members, and reach consensus.

**Comment by nzakas** [comment]
Makes sense to me. 👍

**Comment by btmills** [comment]
Agreed :+1: and marking as accepted.
