### ISSUE TITLE
delete(item.id) in vue template

### ISSUE THREAD

**Issue by chenguzhen87** [eslint/eslint#14195]
**Tell us about your environment**
version: eslint 6.8.0,prettier 1.19.1

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
"delete(item.id)" is deleted   to "delete tem.id"

**Comment by mdjermanovic** [comment]
Hi @chenguzhen87, thanks for the issue!

Can you please fill out our [bug report template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md)?

**Comment by nzakas** [comment]
Not enough info, so closing.
