### ISSUE TITLE
Using --max-warnings in combination with --quiet should error

### ISSUE THREAD

**Issue by gewoonwoutje** [eslint/eslint#14202]
**The version of ESLint you are using.**
v7.21.0

**The problem you want to solve.**
Using the `--max-warnings` cli option is useless in combination with `--quiet`. 
I'm running this in 

Note the following, first running without `--quiet`, then with.
![image](https://user-images.githubusercontent.com/9407072/110871764-42790280-82cf-11eb-805a-7049261c3b62.png)

**Your take on the correct solution to problem.**

Ideally: The `--quiet` flag should be overriden when the amount of warnings exceeds `max-warnings`, logging the warnings.
Also acceptable: The exit code should be 1 when `max-warnings` is exceeded.

**Are you willing to submit a pull request to implement this change?**
Not really 😇

**Comment by nzakas** [comment]
It looks like there is probably a bug when quiet and max-warnings are used together. In that case, it should still exit with a 1 exit code saying that there were too many warnings.

I think it makes sense to not show warnings in this case.

**Comment by mdjermanovic** [comment]
> It looks like there is probably a bug when quiet and max-warnings are used together. In that case, it should still exit with a 1 exit code saying that there were too many warnings.

I agree that `--max-warnings` indicates that the user wants a non-zero exit code when there are too many warnings, even with `--quiet`. Otherwise, this combination wouldn't make sense, and if a non-zero exit code isn't desired behavior then they can just remove `--max-warnings` from the command.

> I think it makes sense to not show warnings in this case.

I don't have a strong opinion on this. Not showing warnings looks less surprising, but the list of warnings might be valuable in this case.

**Comment by btmills** [comment]
I agree that this is a bug and that `--max-warnings` should trigger a non-zero exit code when the limit is exceeded even if used with `--quiet`.

> I think it makes sense to not show warnings in this case.

I also agree that this is the correct behavior because we should respect `--quiet` and not show warnings even if `--max-warnings` is exceeded.

**Comment by nzakas** [comment]
Okay, so it sounds like we've agreed that the current behavior is a bug.

Current behavior: When using `--quiet` with `--max-warnings`, we are not showing an error even when the number of warnings exceeds the threshold for errors.

Desired behavior: When using `--quiet` with `--max-warnings`, we should show the error that the maximum number of warnings has been reached and not show the actual warnings.

**Comment by mdjermanovic** [comment]
Should we show the number of found warnings in the message?

Current message is: `ESLint found too many warnings (maximum: 100).`

https://github.com/eslint/eslint/blob/ebd70263f6e6fe597613d90f4b8de84710c2f3d6/lib/cli.js#L315-L318

Without `--quiet`, formatter is expected to show the number of warnings.

With `--quiet`, formatter will show either nothing or, if it's a formatter that always show a summary, something like `warnings: 0`.

**Comment by nzakas** [comment]
I don’t think that’s necessary. The max allowable warnings is already shown so I don’t think there’s any need to show the actual number

**Comment by jamietre** [comment]
Hi, just wanted to point out that this is a breaking API change; our build depended on "--quiet" ignoring warnings rather than just not printing them in our build.
