### ISSUE TITLE
No-unreachable-code detected bug

### ISSUE THREAD

**Issue by WickedWizard3588** [eslint/eslint#14206]
Hey,

When I use `return` in the middle of the code, it shows `no-unreachable-code` and throws an error in VSCode. But, when I use `process.exit()` it does not that error. 

Environment Info: 

Node version: v15.10.0
npm version: v7.5.6
Local ESLint version: v7.21.0
Global ESLint version: v7.20.0 (Currently used)

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
default

<details>
<summary>Configuration</summary>
<br>
<pre>
<code>
{
	"extends": "eslint:recommended",
	"env": {
		"node": true,
		"es6": true
	},
	"parserOptions": {
		"ecmaVersion": 2021
	},
	"rules": {
		"brace-style": ["error", "stroustrup", { "allowSingleLine": true }],
		"comma-dangle": ["error", "always-multiline"],
		"comma-spacing": "error",
		"comma-style": "error",
		"curly": ["error", "multi-line", "consistent"],
		"dot-location": ["error", "property"],
		"handle-callback-err": "off",
		"indent": ["off",  "tab"],
		"max-nested-callbacks": ["error", { "max": 4 }],
		"max-statements-per-line": ["error", { "max": 2 }],
		"no-console": "off",
		"no-empty-function": "error",
		"no-floating-decimal": "error",
		"no-inline-comments": "error",
		"no-lonely-if": "error",
		"no-multi-spaces": "error",
		"no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 1, "maxBOF": 0 }],
		"no-shadow": ["error", { "allow": ["err", "resolve", "reject"] }],
		"no-trailing-spaces": ["error"],
		"no-var": "error",
		"object-curly-spacing": ["error", "always"],
		"prefer-const": "error",
		"quotes": ["error", "single"],
		"semi": ["error", "always"],
		"space-before-blocks": "error",
		"space-before-function-paren": ["error", {
			"anonymous": "never",
			"named": "never",
			"asyncArrow": "always"
		}],
		"space-in-parens": "error",
		"space-infix-ops": "error",
		"space-unary-ops": "error",
		"spaced-comment": "error",
		"yoda": "error"
	}
}
</code>
</pre>
</br>
</details>

<details>
<summary>Bugged Code</summary>
<br>
<pre>
<code>
console.log('test');

process.exit();

console.log('test');
</code>
</pre>
</br>
</details>

**What did you expect to happen?**

Expected it to show the underline issue in console and VSCode like for `return`, but doesn't occur.
![image](https://user-images.githubusercontent.com/67627239/110911258-776d6f80-8338-11eb-819c-d3de8927ce32.png)

**Steps to reproduce this issue:**

1. Copy Paste the above code
2. Run `eslint .` to find no errors in console or the VSCode Problems

**Comment by mdjermanovic** [comment]
Hi @WickedWizard3588, thanks for the issue!

The `no-unreachable` rule works as expected in this case, as isn't designed to be aware of platform-specific features like `process.exit()`. Per the [documentation](https://eslint.org/docs/rules/no-unreachable):

> This rule disallows unreachable code after `return`, `throw`, `continue`, and `break` statements.

If you want this rule to also report unreachable code after `process.exit()`, you can install [eslint-plugin-node](https://www.npmjs.com/package/eslint-plugin-node) and additionally enable [node/process-exit-as-throw](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/process-exit-as-throw.md) rule:

```json
{
    "plugins": ["node"],
    "rules": {
        "no-unreachable": "error",
        "node/process-exit-as-throw": "error"
    }
}
```

**Comment by WickedWizard3588** [comment]
Oh ok, so this was meant purposefully then... Thanks for the clarification!!
