### ISSUE TITLE
Update: add options to (dis)allow comma expression in for-loops in no-sequences

### ISSUE THREAD

**Issue by danielrentz** [eslint/eslint#14204]
**What rule do you want to change?**

[no-sequences](https://eslint.org/docs/rules/no-sequences)

This is a follow-up of #14197 (Add option to disable the "in-parentheses" exception).
Consequently, the rule should contain an option to decide whether commas are allowed in for-loop heads.

**Does this change cause the rule to produce more or fewer warnings?**

More.

**How will the change be implemented? (New option, new default behavior, etc.)?**

Currently, comma expressions are always allowed in for-loop `init` and `update` part, but not in `test` part where it does not make any sense.

I have two alternatives in mind:

1. One option for init and update part of the for-loop, e.g. "allowInForLoop". But this is confusing as it obfuscates the fact that comma will still not be allowed in `test` part.
2. Distinct options for `init` and `update` part:
   - `allowForLoopInit` (following "ignoreForLoopInit" from [init-declarations](https://eslint.org/docs/rules/init-declarations))
   - `allowForLoopAfterthoughts` (as in [no-plusplus](https://eslint.org/docs/rules/no-plusplus)) (or `allowForLoopUpdate` which is shorter and better remarkable?)

All options will be `true` by default for compatibility.

**Please provide some example code that this change will affect:**

```js
let i, j;
for (i = 0, j = 0; i < 100; i += 1, j += 2) {
  
}
```

**What does the rule currently do for this code?**

Passes.

**What will the rule do after it's changed?**

Pass or warn according to options.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by mdjermanovic** [comment]
I'm not much in favor of this option, as it's mostly stylistic. Comma in a for-loop init/update doesn't look like a possible error or a bad practice. It's also easy to disallow this with `no-restricted-syntax`, the selector would be: 

`"ForStatement > SequenceExpression.init, ForStatement > SequenceExpression.update"`.

I'm in favor of https://github.com/eslint/eslint/issues/14197 as it can catch possible errors, and it doesn't seem easy to write a selector that would disallow sequence expressions everywhere except in for-loop init/update.

**Comment by danielrentz** [comment]
Sure it does not hide errors like #14197 but is mostly for completeness :)

**Comment by nzakas** [comment]
We aren’t moving forward with this, so closing.
