### ISSUE TITLE
Improve the docs for RuleTester

### ISSUE THREAD

**Issue by AntonNiklasson** [eslint/eslint#14218]
**The problem you want to solve.**

I was initially looking for a way to test a lint rule with specific shared settings on a per-case basis. I realised there are a few key details left out of the documentation for RuleTester. I'm not sure if this is intentional or not, just let me know if it is.

Comparing [the docs for RuleTester](https://eslint.org/docs/developer-guide/nodejs-api#ruletester) to how it's [typed with JSDoc](https://github.com/eslint/eslint/blob/master/lib/rule-tester/rule-tester.js#L62-L88) reveals a few things I would like to have read about in the docs. 

**Your take on the correct solution to problem.**

The documentation should be a bit more in-depth and explain the test cases better.

**Are you willing to submit a pull request to implement this change?**

If this is something that needs to be adressed, I'm available to contribute 🤗

**Comment by mdjermanovic** [comment]
Hi @AntonNiklasson! 

> Comparing [the docs for RuleTester](https://eslint.org/docs/developer-guide/nodejs-api#ruletester) to how it's [typed with JSDoc](https://github.com/eslint/eslint/blob/master/lib/rule-tester/rule-tester.js#L62-L88) reveals a few things I would like to have read about in the docs.

Things like `settings`, `parser`, `globals` and `env`?

That should be covered by "Any additional properties of a test case will be passed directly to the linter as config options." in the docs, but I agree that examples would be nice.

**Comment by AntonNiklasson** [comment]
Ah, you're right. That should cover it. 👍
