### ISSUE TITLE
Backtick bug

### ISSUE THREAD

**Issue by Bayramito** [eslint/eslint#14211]
I think this is a very common bug becouse i alredy googled it and saw a lot of topics about that.

**Steps to produce this bug**

I just type single `backtick` and try to save the file and vscode stops responding. Actually ESLint crashing here is a screenshoot from this case. Also my CPU starts to work at 100% after a couple seconds.

<img width="1107" alt="Ekran Resmi 2021-03-13 11 23 56" src="https://user-images.githubusercontent.com/44513402/111026160-9845cb80-83f1-11eb-9f0a-13fef465f74f.png">

Of couse on purpose this is not a ideal case, i mean saving a js file with a single backtick, but sometimes you are doing it by mistake and you need to reload the vscode to be able to save again.

So once it happens, you need to reload your whole editor. Even you press Cancel at right bottom and remove the backtick still not responding... just like beloew

<img width="1096" alt="Ekran Resmi 2021-03-13 11 24 12" src="https://user-images.githubusercontent.com/44513402/111026269-14401380-83f2-11eb-8946-f4291f16c56d.png">

HERE IS MY SETUP
  **"eslint": "^7.21.0",**
* **Node Version: v14.15.1**
* **npm Version: 6.14.10**
* **Operating System: macOS (Big Sur v11.2.3)** 

```js
    **"@react-native-community/eslint-config": "^0.0.5",**
    **"eslint-config-airbnb": "^18.2.1",**
    **"eslint-config-prettier": "^6.15.0",**
    **"eslint-import-resolver-babel-module": "^5.1.0",**
    **"eslint-plugin-import": "^2.22.1",**
    **"eslint-plugin-jsx-a11y": "^6.4.1",**
    **"eslint-plugin-prettier": "^3.3.1",**
    **"eslint-plugin-react": "^7.22.0",**
    **"eslint-plugin-react-hooks": "^1.7.0",`**
```

**Comment by nzakas** [comment]
This looks to be a problem with the ESLint Visual Studio Code plugin, which is not maintained by the ESLint team. You may want to open an issue here:
https://github.com/microsoft/vscode-eslint
