### ISSUE TITLE
check `node.raw` before checking because it's not standard and may break custom parser

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#14219]
**What rule do you want to change?**

https://github.com/eslint/eslint/search?q=node.raw&type=

**Does this change cause the rule to produce more or fewer warnings?**

Fewer error for custom parser, `raw` of `Literal` is not standard, see https://github.com/estree/estree/issues/14

**How will the change be implemented? (New option, new default behavior, etc.)?**

check `node.raw`, return if not presented

**Please provide some example code that this change will affect:**

Context: https://github.com/mdx-js/eslint-mdx/pull/284#issuecomment-800399534

**What does the rule currently do for this code?**

break if the custom parser does not have `node.raw`

**What will the rule do after it's changed?**

no error

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by wooorm** [comment]
> Fewer error for custom parser, raw of Literal is not standard, see estree/estree#14

Specifically, fewer crashes.

---

My use case for this is that certain languages can compile to JavaScript. Such as markdown/MDX, and others. But those language have different and noncompatible representations of literals.

For example, in markdown, an `alt` attribute can be represented with `![the alt attribute]()`.
A custom parser could represent that attribute as a JSX attribute in estree.
But in those cases, setting a `raw` field on the literal is nonsensical: there are no quotes, escapes don‘t work, character references (`&amp;`) could exist, etc.

A different solution for custom parsers would be to try and create a sensical `.raw` attribute. The problem with this approach though is that it now needs to know what the preferred quote style is.

So, I think a better solution would be for rules that can only work on `.raw` to exit gracefully if that field does not exist.

**Comment by JounQin** [comment]
> Hi @JounQin & @wooorm!
> 
> Per our [AST specification](https://eslint.org/docs/developer-guide/working-with-custom-parsers#the-ast-specification) for parsers, the [`Literal` node](https://eslint.org/docs/developer-guide/working-with-custom-parsers#the-literal-node) must have `raw` property.
> 
> Modifying several core rules wouldn't fix this issue, as plugins and custom rules can also use this property.

Thanks for clarify, if it's in ESLint's specification, then we need to add it. @wooorm

**Comment by wooorm** [comment]
I'd prefer to continue the conversation to see if this could change to a *should* instead of *must*?

**Comment by mdjermanovic** [comment]
I'm not sure if the `raw` property itself is the problem. `node.raw` is a shortcut to get the source code. If the rules would use another way to get the source code, they'll still assume that if `node.type === "Literal" && typeof node.value === "string"` then `node` is a JavaScript string literal.

**Comment by mdjermanovic** [comment]
> For example, in markdown, an `alt` attribute can be represented with `![the alt attribute]()`.
> A custom parser could represent that attribute as a JSX attribute in estree.
> But in those cases, setting a `raw` field on the literal is nonsensical: there are no quotes, escapes don‘t work, character references (`&amp;`) could exist, etc.
> 
> A different solution for custom parsers would be to try and create a sensical `.raw` attribute. The problem with this approach though is that it now needs to know what the preferred quote style is.

`.raw` should represent the source code as-is. A solution for rules that are about the syntax of literals (i.e., rules that work on raw literals, like `quotes` and `no-useless-escape`) could be to write replacement rules that would ignore non-js-syntax literals.

As an example of this approach, `@typescript-eslint/eslint-plugin` provides [extension rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#extension-rules).

**Comment by wooorm** [comment]
> If the rules would use another way to get the source code, they'll still assume that if node.type === "Literal" && typeof node.value === "string" then node is a JavaScript string literal.

Tokens? What other ways are there?

> .raw should represent the source code as-is.

I agree, but in my use case this conflicts with the other requirement of `.raw`, namely that it *must* exist.
There are languages that can be represented as an estree, but setting `.raw` fields would trip ESLint rules up.

Most AST transforms, such as Babel plugins as they change the tree, also don’t set `.raw` fields. Lifting the requirement of `.raw` would allow transforms to come before ESLint. I prefer that over a) crashing ESLint, b) getting false positives, c) turning these rules off and thus missing correct warnings.

> \@typescript-eslint/eslint-plugin

True, but TS is a big example: it’s specced. A lot of work went into adding it here. It may not be suitable for smaller languages to get it specced and integrated into ESLint, nor is it ideal to add every arbitrary language here.

Forking eslint rules and crashing when the original rules are used is also a solution, but it’s not very nice I think.

Having new and different rules for the different syntax though: all for that.

**Comment by JounQin** [comment]
If we don't provide `node.raw`, then it seems as the same as by just disabling the related rules, it doesn't make sense to me IMO.

**Comment by wooorm** [comment]
@JounQin Because the language is a mix between JS and something else. ESLint can lint the JS parts fine. `.raw` is set there.
Turning ESLint rules off means that it doesn’t lint anything.

**Comment by JounQin** [comment]
> @JounQin Because the language is a mix between JS and something else. ESLint can lint the JS parts fine. `.raw` is set there.
> Turning ESLint rules off means that it doesn’t lint anything.

Hah, forgot about that, but I'm +1 for `extension rules` personally. `mdx/no-unused-expressions` for example. 😂

We can't and shouldn't enforce other rules to be compatible with us. It's the risk for custom parsers/plugins.

**Comment by mdjermanovic** [comment]
> > If the rules would use another way to get the source code, they'll still assume that if node.type === "Literal" && typeof node.value === "string" then node is a JavaScript string literal.
> 
> Tokens? What other ways are there?

Tokens, or slicing text from the source code by node's `.range`.

> > .raw should represent the source code as-is.
> 
> I agree, but in my use case this conflicts with the other requirement of `.raw`, namely that it _must_ exist.
> There are languages that can be represented as an estree, but setting `.raw` fields would trip ESLint rules up.

Rules that need `.raw` are mostly rules with a purpose to check how the code was exactly written in JS and enforce some style or best practices about it. Those rules are thus not applicable to languages with a different syntax for literals.

If we treat an absence of `.raw` as a way to tell that it isn't really a JS literal, that would add maintenance to rules that were designed for JS. It could also hide bugs in rules and other parsers.

> ESLint can lint the JS parts fine. `.raw` is set there.
> Turning ESLint rules off means that it doesn’t lint anything.

You'll produce a single AST with JS and non-JS parts, where some `Literal` nodes have `.raw` but some don't?
