### ISSUE TITLE
Consider switching to Conventional Commits

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#14231]
## Background

When ESLint was started, there weren't any standardized conventions for commit messages. I had a custom convention that I had used for other projects, so ESLint used that from day one. Since that time, [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) have become the de facto standard for commit message formatting in the JavaScript community. In fact, we get a lot of pull requests where people assume we are using Conventional Commits.

Because commit messages are used to generate releases and changelogs, tools are necessarily tied to the commit message format being used. As such we have maintained [eslint-release](https://github.com/eslint/eslint-release) to help manage our releases. Similarly, there are a lot of tools that support Conventional Commits.

## Why switch?

The reason for considering the switch is the tooling support for Conventional Commits. Instead of maintaining our own tooling, which is additional overhead for little additional value, we would be able to use some of the tools that the larger ecosystem already relies on and maintains, for example:

* [release-please](https://github.com/googleapis/release-please) is a tool that manages releases by building up a branch of changes and a pull request that displays them. It auto-generates changelogs, bumps version numbers, and would solve one of our biggest problems, which is how to do a major release without stopping the development of minor releases in the meantime.
* [Lerna](https://github.com/lerna/lerna) is a tool that helps manage monorepos based on Conventional Commits. If we ever wanted to explore a monorepo setup, we'd be hard-pressed to create a better tool.

## Why not use the tools and update to our own commit format?

Yes, we could probably request that these tools support our format, or create forks that do...but why? Our format is already pretty close to Conventional Commits, and asking tooling to change for us doesn't seem like a good use of anyone's time. Conventional Commits has already landed as a favorite, so let's go the direction the river is flowing.

## What would be involved?

From our point of view, we'd need to do a gradual transition where we allowed both our current format and Conventional Commits, in order to minimize disruption to in-progress work. I envision the process would look like this:

- [x] Update eslint-release so that is respects both our current format and Conventional Commits
- [x] Update our commit message check on pull requests to validate for Conventional Commits (easy to fix right before merging on existing pull requests)
- [ ] Do a release so all original-format commit messages are published
- [ ] Retire eslint-release
- [ ] Switch to release-please (or another alternative)

**Comment by JounQin** [comment]
I'm suffered from raising issue to ESLint because of message cases like `Fix` vs `fix`.

**Comment by btmills** [comment]
:+1: from me. `eslint-release` was a great automation tool when other options weren't so well-developed. Now that well-supported community-maintained options are available, it would be nice to remove the overhead of our custom tooling. It'd also be nice to get away from running our own Jenkins server.

Would we be able to hook the website build step that we currently run as part of releases into release-please? That's probably the most-customized release step we have.

**Comment by nzakas** [comment]
We can customize what happens when a release is created, so yes. It’ll probably be a bit messy, but I’m sure we can make it work.

**Comment by aladdin-add** [comment]
https://github.com/release-it/release-it seems be more popular than release-please.

**Comment by nzakas** [comment]
The benefit of release-please is that it creates a pull request for the next release and updates the PR when new commits are pushed to master, so a release is just merging the PR. My goal is avoid any need for a command line for most releases.

**Comment by nzakas** [comment]
**TSC Summary:** This issue suggests moving to conventional commits for all ESLint projects, which would allow us to adopt more conventional tooling for managing projects.

**TSC Question:** Shall we accept this proposal?

**Comment by btmills** [comment]
The TSC accepted this change in Thursday's meeting. We'll do this as a phased migration so we don't disrupt releases.

**Comment by JounQin** [comment]
Another alternative is https://github.com/atlassian/changesets, it makes possible to exclude some unexpected commit message into release or custom release content via file content instead of uneditable (impossible on website directly) commit message.

**Comment by nzakas** [comment]
Thanks, I’ll take a look. At first glance that seems a bit more complicated that what we need, but we still have time to evaluate several options.

**Comment by voxpelli** [comment]
As mentioned in #14708, the highlights that are currently posted to eslint.org is quite useful, is there a way to add a highlight section manually when doing a release with `release-please`?

I love automation that removes repeated work, but I'm hesitant about automation that also completely removes the human part of a process, rather I think automation should make it so that more focus can be given to the human part of it all, like writing a thoughtful highlight section 🙂

**Comment by nzakas** [comment]
We haven’t made any final decision on tooling at this point but will revisit once we get v8.0.0 out the door.

**Comment by JounQin** [comment]
[changesets](https://github.com/atlassian/changesets)' CHANGELOGs are based on files, so it's full controlled by human easily. You can always change it before merging the final PR for releasing.

**Comment by voxpelli** [comment]
> [changesets](https://github.com/atlassian/changesets)' CHANGELOGs are based on files, so it's full controlled by human easily. You can always change it before merging the final PR for releasing.

Looks interesting, seems to also have some [good automation](https://github.com/atlassian/changesets/blob/main/docs/automating-changesets.md) – both a [bot for PR:s](https://github.com/apps/changeset-bot) and [an action that creates a release PR](https://github.com/changesets/action)

**Comment by voxpelli** [comment]
@nzakas I think this one can be closed as complete now, right?

**Comment by btmills** [comment]
We're still in the middle of this migration right now, where we're using our own tooling adapted to work with conventional commits. The checklist at the top has a couple more tasks that will allow us to move off of our custom tooling entirely.

**Comment by sam3k** [comment]
Summary as of February 8 2023:

- [x] We've officially switched to conventional commits
- [x] Out bot has been [updated](https://github.com/eslint/eslint-github-bot/pull/158) to check for conventional commits.
- [x] Update eslint-release so that is respects both our current format and Conventional Commits
- [x] Update our commit message check on pull requests to validate for Conventional Commits (easy to fix right before merging on existing pull requests)
- [ ] Release tool alternative
  - [ ] Do a release so all original-format commit messages are published
  - [ ] Switch to release-please (or another alternative) We're currently evaluating other tools for managing releases but this won't be part of the ongoing work on this issue?
  - [ ] Retire eslint-release
  - [ ] We need to finish migrating our tooling to adapt to work with conventional commits

**Comment by nzakas** [comment]
Thanks for the great summary @sam3k! We will be switching some of the other repos to `release-please` to test it out soon.

**Comment by aladdin-add** [comment]
reopened, as it seems the eslint repo has not switched to `release-please`, and it still has some more todos.

**Comment by nzakas** [comment]
I'm not sure if we'll end up switching the `eslint` repo or not as the release process is a lot more involved. It may just stay as-is and when we create a new repo for the rewrite, start there with release-please.

@mdjermanovic what do you think?

**Comment by mdjermanovic** [comment]
> I'm not sure if we'll end up switching the `eslint` repo or not as the release process is a lot more involved. It may just stay as-is and when we create a new repo for the rewrite, start there with release-please.

I agree.

@aladdin-add are all remaining tasks related to the `eslint/eslint` repo? If yes, I think we can close this.

**Comment by aladdin-add** [comment]
> Retire eslint-release

I think it's the last one. But if it's still being used to publish eslint, we may not be able to complete this one.

**Comment by nzakas** [comment]
Yeah, we won't be able to do that until we stop publishing releases from this repo. So, I think we are done with this issue. :tada:
