### ISSUE TITLE
Proposal: Provide a `defineConfig` function

### ISSUE THREAD

**Issue by Shinigami92** [eslint/eslint#14249]
**The version of ESLint you are using.**
`<= 7.22.0`

**The problem you want to solve.**

When building up a `.eslintrc.js` I do not get provided inline help, autosuggestion, documentation or type-safety.
Also if a new major breaking change is introduced by `eslint`, I do not see directly if my config is still working or not by opening the file and trust the compiler.

**Your take on the correct solution to problem.**

[Vite idea to the rescue :ambulance:](https://twitter.com/antfu7/status/1365907188338753536)

Provide a `defineConfig` function that can be `require`/`import`-ed in the configuration file. _It is a bit like json-schema._

The `defineConfig` function itself does nothing at runtime, it's just

```ts
export function defineConfig(config: EslintConfig) {
  return config;
}
```

[TypeScript Playground Example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBUygGc0B5MGBCJYuAbwCg4W5iIBXKXAFQE8wwAPwAuOAHIAthAAmHADbBxcAD4SAdJvEBuZq2DZJmAGppi1JKLgAmAAx24AegBUazeuePdrJ47jvGAF9GRlBIWDgYATwAJQVgAGVgADc0BCi4AF4JCHR0ZTVxAHciJAKJNChoHRCw6HgowTg4xQBhGnQEAHMAHgoqGjpQVCQZOg4kAGskCCKkAG0AXSy4CenZhcWAPhWWxJS0jLV5vaTUqHS+ABp-TX6LYkXdUPB6xBQ0LFxm+KGQEbGBCIVEw8h6MQM0BkPWIMAuSC6Nz27SQnS6Wx2TB8LmcelYzjgABEEMRQfJZpEABZ4DikOC5OAyYAAIw4XS6aDxLAJXLgBIAAqQ8PMZgBaJms9loRYACkpMBgYGIIkcjmAxHkyBg6mgXUcMgg2GIjigv0cYolbI5UAAlLzPFzxBaWVa0OIrMiOt0ekstt5WDj7XAAKKo6DfGDUuDYQYkkbwWl4BnAdLUqBwZk4SZUbCTYg3A0cZmKG7QNjILqKOAARw4EFQxCDQcFwGFtfr6tl8sVytV6s1KB1UD1BqNJrN7Ybdp8fMcjsn6vdYk9qO9815rHEheLSlUEnMCMU5XEmdzOcm4iuG5YWJnd5xcAAgvJyUU6LD4V06DAIKs6QfK2AUUFzoMtt0UYC6wbNhf3JBE4Ewb8ow-CtoxoGBMGQOhMBrKC8EjTB4CKTh5BkOBKUwVJIl-Zk8HVbBMEEMj6zTIoSTwB07zvSiIAQGRg2IBjBCsZkIAgRRMCQK8uJnB9n1fd84Qrb9f0TDMs3POhOJk1gyVmHhgEkMB5EI4AABl0jQUFiBEsSJKQa84GCHxtn9FhAxnAkIVrBAoCTdMZBJPSijYQyEBjOC6Cw1BMGY9AnwSABJJtPLgFthVISQEC7BUlRVNUNS1IcR0NY1TUUY1MoQacfAdABIcQqqXH42i9Xp5nEUESj4YhjyQA4oEvJwCXcWdXKCWpXgiLVPhwPAyHOC4mQYLlOgqsQUIRJY3Lgcr1WXX4dtVW51Aml5wgaaI4AWyo+PVFZHygKBMD4PpFruv1Jou95UAwOaQ0KlAUTRFbsWcAlCUNDg4HQMsqnrWcuXhmBbPE4BJKO8GiShmGy2GYBRi0ucfHxwmrE2rptq5B9IewaHYfTMAiFIdNtJYJmSDQcmlIRTGIZxhm4A5ln7kGRGfGF8hKAeKxCE5qBRdoPnsbp3H0z2omkd+D1DuprHafpssIHeplNZ8Y3btNqwbqeu7iCOvwAmCc63nQCZsAGJBGWATp+uB7oZRjVcujEASBxgf2uhtUHWD8mAuC9oO0V0Z3jvUfstW4dQACtG2OoPYQYb3feASOnJWPyfL8mVxAzlBxBtZ4XGkORFHTqaYDoTJPGL5BS7amVbxYDWxCH2S-AAaRmOZdt+cjKLwUcOEkAmMM9hDRgQjgf2IV1YQsRynQgcUXSlQaxFrp7qmkrjxBA8QxA6ypr-3CsjxuegEOSXj+MExjgDEHCDgeBAiLCvHVBqTVH6XyqING4nV5DdV6mAkIMljpkEjGgOAAAiNY09sHmhoKKOuMAT5YAUPADWh9+SNHohcSgxDAYwEcJmJAopO6ihjJIFe9cL65HyOAhqNDoiCXoaQkhapwCamwOkUUbskAewsKKOOCd2HRAfnAJ+V84FF2CsGcAfliDmEGIA00IDFhcmCIERujAgA)

**Are you willing to submit a pull request to implement this change?**

I think so, but someone needs to help me to find where and how I should add the functionality and TypeScript definitions.

**Alternative approach**

Provide a new package like [`eslint-define-config`](https://github.com/Shinigami92/eslint-define-config)

**Comment by Shinigami92** [comment]
I already jumped ahead and published [![npm version](https://img.shields.io/npm/v/eslint-define-config.svg)](https://www.npmjs.com/package/eslint-define-config) :smile:  

Repo: https://github.com/Shinigami92/eslint-define-config

Anyone who wants to help is welcome, I accept PRs now!

**Comment by nzakas** [comment]
It sounds like what you’re asking for is for ESLint to ship type definitions for config files?

We are in the middle of transitioning to a new config system (see #13481) so we aren’t making any further changes to the existing config system.

We also haven’t shipped type definitions for anything before, and I’m not sure that’s a direction we want to go in.

Given that you’ve already implemented a package that does what you want, it seems like using that package is the best option.
