### ISSUE TITLE
"@typescript-eslint/no-floating-promises" doesn't do the job if operator ! is used

### ISSUE THREAD

**Issue by bonjourjoel** [eslint/eslint#14258]
Hi,

I have installed eslint only for the rules "@typescript-eslint/no-floating-promises", because I believe it is a huge whole in typescript compiler to not report unhandled promises, those not using void nor await in async functions.

Eslint helps me a lot, but whenever i try to test a boolean or a boolean function call, i can write something like:
`if (! this.method(args)) {...`  where `method` returns a `Promise<boolean>`
Eslint doesn't detect that I made a programming error. These errors are difficult to find and defeat the purpose of the rule. I understand it's a C-style construction to test a value that's not a boolean. But myself I never do this, even in C, because it's errors prone, and it's useless/outdated/cowboy style imho.
Those unhandled promises can cause race situations and make bugs reported by users impossible to reproduce. They are a nightmare. I wish eslint could handle these ones, either in the rule "@typescript-eslint/no-floating-promises", or in another, maybe disabled by default if you believe it's not a good rule for everyone.

Thanks for your time.
Regards.

**Comment by mdjermanovic** [comment]
Hi @bonjourjoel, thanks for the issue!

>  I wish eslint could handle these ones, either in the rule "@typescript-eslint/no-floating-promises", or in another, maybe disabled by default if you believe it's not a good rule for everyone.

`@typescript-eslint/no-floating-promises` is a rule from `@typescript-eslint/eslint-plugin`. You can open an issue in the plugin's repository:

https://github.com/typescript-eslint/typescript-eslint

A new rule would certainly require type information, which we don't have in core rules, so it would be also a request for a rule in `@typescript-eslint/eslint-plugin` or another plugin.

**Comment by bonjourjoel** [comment]
thanks i'll do just that!
