### ISSUE TITLE
@typescript-eslin"t"/eslint-plugin? 

### ISSUE THREAD

**Issue by ooo2003003v2** [eslint/eslint#14268]
Hello there I ran eslint "*/.ts" --quiet on my console but it showed an error saying it couldnt find the "@typescript-eslin/eslint-plugin" which is missing a "t" and I have installed  "@typescript-eslint/eslint-plugin": "^2.33.0" in my dev dependencies. Any idea why this happened?

```
 "devDependencies": {
    "@types/node": "^14.14.36",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.34.0",
    "eslint": "^6.7.2",
    "eslint-plugin-jest": "^24.3.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.23.1",
    "jest": "^26.6.3",
    "nodemon": "^2.0.7",
    "prettier": "^1.19.1",
    "ts-jest": "^26.5.4",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.3"
  },
```
![image](https://user-images.githubusercontent.com/55082067/112934980-6e143d80-9155-11eb-8eb0-973f895c0914.png)

**Comment by ljharb** [comment]
You're using eslint 6 (and not even the latest v6), and eslint is up to v7. What happens if you update to the latest eslint 6, or 7?

**Comment by ooo2003003v2** [comment]
> nd
Oh thx. Problem solved after updating everything eslint related.
