### ISSUE TITLE
[Feature] Convert inline-styles into independent styles in React-Native?

### ISSUE THREAD

**Issue by MenaiAla** [eslint/eslint#14272]
### Description

In `react-native`, `eslint` warns us to avoid `inline-style` in our components but it provides one solution by __disabling the rule.__
However, I'd recommend to add an option that let's convert `inline-styles` into independent styles.

### Example

```Javascript
 <Text style={{backgroundColor: 'green'}}>{section.title}</Text>
```

In the above snippet, `eslint` will have the ability to transform that rule into:

```Javascript
<Text style={styles.text}>{section.title}</Text>

const styles = StyleSheet.create({
  text: {
    backgroundColor: 'green'
  },
});
```

**Comment by mdjermanovic** [comment]
Hi @MenaiAla, thanks for the issue! 

> In `react-native`, `eslint` warns us to avoid `inline-style` in our components

ESLint core doesn't have this rule, you are probably getting warnings from a third-party rule.

Can you share the error message (including the name of the rule), so we could locate the plugin?

**Comment by MenaiAla** [comment]
Hi @mdjermanovic , I've made a screenshot of the warning:

<img width="1080" alt="Screen Shot 2021-03-31 at 10 41 30 AM" src="https://user-images.githubusercontent.com/20143684/113125330-65337280-920e-11eb-8b75-009d9178d7b5.png">
