### ISSUE TITLE
Remove some formatters from the core

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#14277]
**The version of ESLint you are using.**

v7.x

**The problem you want to solve.**

We ship a lot of formatters with the core, and some of them require dependencies that aren't necessary elsewhere in ESLint. If we remove these formatters, we reduce the overall size of ESLint by removing these dependencies.

Spawned from https://github.com/eslint/eslint/issues/14098.

**Your take on the correct solution to problem.**

Remove these formatters:

* `codeframe` - depends on `@babel/code-frame`
* `table` - depends on `table`

Note that @fregante has already packaged all of the built-in formatters into separate packages on npm: https://github.com/fregante/eslint-formatters. So we would be able to tell people, for example, to install `eslint-formatter-table` if they are using the table formatter.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by fregante** [comment]
Keep in mind that they after this they will become unmaintained. I'll gladly pass on the mentioned formatter packages to their original writers.

**Comment by nzakas** [comment]
I think that’s fine. Formatters don’t change a lot, so they might not even need maintenance.

**Comment by btmills** [comment]
This change is accepted for ESLint v8.0.0.

**Comment by fregante** [comment]
I'll take it

**Comment by nzakas** [comment]
@fregante Thanks! Keep in mind that it still may be several weeks before v8.0.0 is released so we may leave the PR open until we are ready.
