### ISSUE TITLE
Support multiple parsers for different rules

### ISSUE THREAD

**Issue by Plondrein** [eslint/eslint#14286]
**The version of ESLint you are using.**
7.23.0

**The problem you want to solve.**
I've got Angular project where i want to lint HTML files with two different plugins that provide custom parsers: 

* [angular-eslint](https://github.com/angular-eslint/angular-eslint)
* [html-eslint](https://github.com/yeonjuan/html-eslint)

I'm trying to apply rules from both plugins in single config file, yet without success.  Parsers are overriding each other, I can't manage to set combine them.

The workaround was to run ESLint multiple times with different configs, but IDE doesn't handle such approach well and doesn't show any warnings when i'm working with a particular file.

**Your take on the correct solution to problem.**

Maybe if I could provide multiple parsers and then each rule would specify which parser is required and then it should combine well.

**Are you willing to submit a pull request to implement this change?**

I could do it with some guidance.

**Comment by nzakas** [comment]
Sorry, this isn’t something we can support. There is an explicit constraint that ESLint uses exactly one parser per file, and another that rules cannot dictate how a file is parsed. 

I’m afraid the best solution is to do what you’re doing and run ESLint twice with two separate configs. You might also want to contact the owners of those two packages to see if they might consider converging on the same parser or perhaps duplicating the rules you want to work with their own parser.
