### ISSUE TITLE
Faulty catch block in code, error not handled

### ISSUE THREAD

**Issue by oldCoder29** [eslint/eslint#14283]
file name : eslint/bin/eslint.js
line number 93 : 

        } catch {

            // Ignore template error then fallback to use `error.stack`.
        }

this catch block is faulty,

**Comment by oldCoder29** [comment]
eslint/lib/cli-engine/cli-engine.js:421

} catch {
        fileStats = null;
    }

**Comment by ljharb** [comment]
What is faulty? Optional catch bindings were added in ES2019, and it's perfectly valid to omit the binding now.

**Comment by oldCoder29** [comment]
Yeah, got it. I was using older version of node. Thank you.
