### ISSUE TITLE
Add `--since` CLI option to only lint changed files

### ISSUE THREAD

**Issue by jdanil** [eslint/eslint#14294]
**The version of ESLint you are using.**

7.23.0

**The problem you want to solve.**

Only lint files that have changed since a feature branch was created, or since a particular commit, to save time by avoiding linting unchanged files.

This would be similar to functionality in other tools like jest (https://jestjs.io/docs/cli#--changedsince), lerna (https://github.com/lerna/lerna/tree/main/core/filter-options#--since-ref), and prettier (https://github.com/azz/pretty-quick).

**Your take on the correct solution to problem.**

I would like to propose adding a new `--since` CLI option to eslint, which would take a branch name or commit hash. The branch name or commit hash would be used to determine all the files changed between that commit and the current state. This would run the same as if eslint was run via CLI, with all the changed filenames passed in as arguments.

I've tested this concept out in https://github.com/jdanil/eslint-changeset.

**Are you willing to submit a pull request to implement this change?**

Yes. But my changes would be restricted to supporting git, as I am not familiar with other SCM systems.

**Comment by nzakas** [comment]
This is an interesting idea. I’m unsure if we want to go down the path of building git-specific functionality into ESLint. I’d be interested to hear what others think. @eslint/eslint-tsc

**Comment by jdanil** [comment]
Thanks @nzakas. Just to clarify, I think this could be implemented in a SCM-agnostic way. Both jest and pretty-quick support this feature for both git and mercurial. They perform detect step by checking for a `.git` or `.hg` directory and then use the appropriate SCM commands. I just meant that I'm not familiar with mercurial, so if I were to contribute an initial implementation I probably would only cover git (but other SCMs could be supported).

Am I understanding your concern correctly or are you more worried about including any SCM logic in eslint?

**Comment by nzakas** [comment]
I’m not thrilled with baking in any SCM-specific knowledge. This seems like something a script built on top of ESLint could do in a single line.

**Comment by mdjermanovic** [comment]
I'm not in favor of maintaining any SCM logic in ESLint. It seems more flexible to have this functionality in a separate tool that could provide various options or to make a custom script for a specific use case.

**Comment by btmills** [comment]
Thanks for the suggestion, but I agree about not wanting to build in SCM logic. This feature is a perfect use case for a separate tool like `eslint-changeset`. You should submit it to [aweseome-eslint](https://github.com/dustinspecker/awesome-eslint), @jdanil!

**Comment by jdanil** [comment]
All good. Thanks for considering it.
