### ISSUE TITLE
Override files in parent directory

### ISSUE THREAD

**Issue by adpeyre** [eslint/eslint#14299]
**The version of ESLint you are using.**
Node version: v14.15.5
npm version: v6.14.11
Local ESLint version: v7.20.0 (Currently used)

**The problem you want to solve.**

My file structure:

- ci
  -  package.json (script: `eslint '../assets/**/*.{js,ts}' --config ./config/eslintrc.js`)
  - config
    - eslintrc.js
- assets
  - file.js  

My eslintrc.js: 

``` js
...
  'overrides': [{
    files: ['../assets/file.js'],
    rules: {
      'import/prefer-default-export': 'off',
    }
  }],
...
````

In this situation, I cannot override files because the path is relative to `./ci` directory and `..`is not allowed in pattern files.

Thanks for your help

**Comment by ljharb** [comment]
The config is supposed to be in the root, where most configs go for tooling sensitive to file paths. Why is it in `config/`?

**Comment by adpeyre** [comment]
For a specific project, I need to separate my project dependencies and my quality tools dependencies. So eslint (and stylelint) is in a dedicated package.json.

**Comment by ljharb** [comment]
Unfortunately that's just not the way eslint (and babel, and typescript, etc) all work. The folder the config is in, _is_ the root of the project, as far as those tools are concerned.

**Comment by adpeyre** [comment]
Ok I understand. But eslint works very well with this configuration except overrides.

**Comment by nzakas** [comment]
I’m sorry, we don’t support parent directories in overrides, and we aren’t making any further changes to this config system as we move to a new one (see #13481).
