### ISSUE TITLE
Docs - Add eslint disable to the "ignore code" section

### ISSUE THREAD

**Issue by seanbecker15** [eslint/eslint#14301]
**The version of ESLint you are using.**
N/A

**The problem you want to solve.**
I had to go to stackoverflow to figure out how to ignore the next line.

**Your take on the correct solution to problem.**
Add all of the rules to this page:
https://eslint.org/docs/user-guide/configuring/ignoring-code

**Are you willing to submit a pull request to implement this change?**
Sure, but evidently I don't know eslint well enough to know all of the different commands.

**Comment by nzakas** [comment]
I’m sorry, I’m not sure what it is you’re suggesting be changed.  Can you provide more detail? What is it you think is missing?

**Comment by nzakas** [comment]
Not enough info to proceed, so closing.
