### ISSUE TITLE
eslint 7.5.0 option chain error

### ISSUE THREAD

**Issue by wangi4myself** [eslint/eslint#14307]
"eslint": "^7.23.0",
 "eslint-plugin-prettier": "3.1.1",
 "eslint-plugin-vue": "^5.2.3",

and my .eslintrc.js
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: ['plugin:vue/essential', 'eslint:recommended', '@vue/prettier', '@vue/typescript'],
  plugins: ['vue', 'prettier'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'off' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'prettier/prettier': 'warn',
    eqeqeq: 'off',
    'no-unused-vars': 'off', // 后期再启用
    'vue/no-parsing-error': 'off' // 存在推到bug暂不启用
  },
  parserOptions: {
    ecmaVersion: 2020
  }
};

but npm run lint still error:
![image](https://user-images.githubusercontent.com/26651458/114147005-d54aa280-994a-11eb-9386-68937ad4837d.png)

**Comment by aladdin-add** [comment]
can you fill our lovely bug report template please? we cannot repro this without enough info.

**Comment by nzakas** [comment]
Not enough to proceed, so closing.
