### ISSUE TITLE
`no-redeclare` loose parser tests

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#14315]
**The version of ESLint you are using.**

v7.24.0

**The problem you want to solve.**

We have several tests for the `no-redeclare` rule where `let` and `const` variables are redeclared:

https://github.com/eslint/eslint/blob/555cbf37f6fe17d8ea8bf8f642a49801aab336c7/tests/lib/rules/no-redeclare.js#L208-L216

This is normally a syntax error reported by the parser, so the tests are using fixture parser [tests/tools/loose-parser.js](https://github.com/eslint/eslint/blob/master/tests/tools/loose-parser.js)

The fixture parser requires an internal module from `espree` in order to produce an error-tolerant parser.

https://github.com/eslint/eslint/blob/555cbf37f6fe17d8ea8bf8f642a49801aab336c7/tests/tools/loose-parser.js#L10

The problem is - after we release https://github.com/eslint/espree/pull/469, that module will be no more available as it isn't defined by `exports` in espree's `package.json`. Even if we could bypass this restriction, the module will be ESM so it can't be `require`d.

**Your take on the correct solution to problem.**

Just remove those tests? Core rules are not generally designed to handle code that has syntax errors, at least for now.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by nzakas** [comment]
I agree, let's remove the tests.
