### ISSUE TITLE
There is no way to extend only rules from a shared config

### ISSUE THREAD

**Issue by ChipZhang** [eslint/eslint#14329]
**The version of ESLint you are using.**
v7.24.0

**The problem you want to solve.**
Sometimes, I want to use the rules of a shared config. I only want the rules to be extends. If I use the "extends: [...]" syntax, globals/settings/parserOptions are extended as well, thus "polluting" the final effective config.

**Your take on the correct solution to problem.**
The project may introduce a syntax like

```JavaScript
{
  extends: {
   // extends only rules from `base-config`
    "base-config": {"rules": true, "globals": false, "settings": false, "parserOptions": false...},
    // extends all settings from `another-config`
    "another-config": true
  }
}
```
to explicitly specify which settings in the base shared config will be extended.

**Are you willing to submit a pull request to implement this change?**
No

**Comment by ljharb** [comment]
The parser and parserOptions are an inextricable part of a shared config (as are `settings`, `env`, etc). What's the config you want to inherit the rules from, but not the other relevant settings?

**Comment by ChipZhang** [comment]
> The parser and parserOptions are an inextricable part of a shared config (as are `settings`, `env`, etc). What's the config you want to inherit the rules from, but not the other relevant settings (that the rules are configured to require/assume)?

In fact, I want to manually set settings other than rules (e.g. env/settings/globals/parserOptions) rather than automatically extends the entire base config.

Is there an easy way to do that?

**Comment by ljharb** [comment]
Not that I know of (short of using a JS config and importing the config, and accessing it that way) but I'm suggesting that it's actually a really bad idea to do that. Any of those settings are *essential* to correct operation of the configured rules in the shared config, and it's just not a reliable approach to discard those.

**Comment by nzakas** [comment]
This is by design. Configs are meant to be atomic and we don’t want to change that.
