### ISSUE TITLE
[FEATURE] autofix specific rules in .eslintrc config files

### ISSUE THREAD

**Issue by danny007in** [eslint/eslint#14337]
```json
{
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    }
}
```

Adding new feature like

```json
{
    "rules": {
        "^semi": ["error", "always"],
        "quotes": ["error", "double"]
    }
}
```

at here `"^semi": ["error", "always"],`
only semi rules will fix.

also

```json
{
    "extends": "^eslint:recommended"
}
```

by this `^eslint:recommended` whole eslint:recommended rules auto fix should work.

**Comment by nzakas** [comment]
I’m sorry, I don’t know what you’re asking. If you could please use an issue template, it would help us out a lot.

**Comment by danny007in** [comment]
https://eslint.org/docs/user-guide/command-line-interface#fixing-problems this for cli.

but in config files setting, which allows to auto fix the specific rules.

**Comment by nzakas** [comment]
@danny007in We can’t add that into config files because fixing is a completely different mode that ESLint runs in.
