### ISSUE TITLE
Cannot read property 'expression' of undefined Occurred while linting 

### ISSUE THREAD

**Issue by karthikeyan676** [eslint/eslint#14345]
**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**
* **Operating System:** 

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

**Steps to reproduce this issue:**

1. 
1. 
1. 

**Are you willing to submit a pull request to fix this bug?**

**Comment by nzakas** [comment]
No details, so closing.
