### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ppicom** [eslint/eslint#14357]
**Tell us about your environment**

Environment Info:

Node version: v12.16.2
npm version: v7.10.0
Local ESLint version: v7.24.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.11.14-200.fc33.x86_64

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "es2021": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module",
        "project": "./.eslintrc.json"

    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "plugin:@typescript-eslint/no-floating-promises": "error"
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// tried to lint a big project. Pasting the actual code here is unfeasible
```

```bash
npx eslint ./backend
```

**What did you expect to happen?**

All contents of the backend/ folder to be linted.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

Took very long to run and crashed with the error that gives title to this issue.

**Steps to reproduce this issue:**

1. Have a folder with lots of files of ts code (my guess is that the issue could come from here) 
1. npx eslint <that_folder>
1. The error is shown in the terminal.

**Are you willing to submit a pull request to fix this bug?**
Not in the immediate future

**Comment by aladdin-add** [comment]
this is mostly related to typescript-eslint. not sure what we can do in eslint.
/cc @bradzacher

**Comment by bradzacher** [comment]
> ​"project"​: ​"./.eslintrc.json"​

That's not right at all... Assuming you mistyped it.

---

Likely this is a KP.
It's hard to tell though as "lots of files" and "very long" are pretty vague terms and the Typescript-ESLint versions are not listed.

https://github.com/typescript-eslint/typescript-eslint/issues/1192

**Comment by nzakas** [comment]
Closing as there’s not enough info to proceed.
