### ISSUE TITLE
.eslintrc written in JSON, interpreted as YAML

### ISSUE THREAD

**Issue by jiannicello** [eslint/eslint#1443]
I have the .eslintrc file written as JSON:
{
    "env": {
        "browser": true
    }
}

When I run eslint in same directory as the .eslintrc file I get this error message (on windows 7):

YAMLException: Cannot read config file: <path_to_projectdir>.eslintrc
Error: JS-YAML: end of the stream or a document separator is expected at line 2,
 column 10:
        "env": {
             ^

**Comment by dwelle** [comment]
Just to throw my 2 cents, I had a similar issue and it was, indeed, caused by BOM marker which my editor so kindly inserts in all new files. @jiannicello did you check that?

**Comment by cmaish** [comment]
I hate to do the "me too" thing, but found that eshlintrc files with a BOM were always processed as YAML (at least in 0.17.1 / Windows environment).  If the file was json, this would error consistently for me.

**Comment by nzakas** [comment]
Just so there's no confusion: the `.eslintrc` file is a YAML file. Since YAML is a superset of JSON, JSON syntax works just as well as YAML syntax. 

If you're running into parsing issues, please report an error [here](https://github.com/nodeca/js-yaml/issues)
