### ISSUE TITLE
Missing sample .eslintrc file(s)

### ISSUE THREAD

**Issue by SanderElias** [eslint/eslint#1445]
I just started the other day with ESlint. It took me a little while to get up and running.

it would have been really helpful if there where a few sample .eslintrc files.
Ideally, a couple of them, to make (as far as possible!) eslint behave exactly as a standard jslint and one for jshint.
This would provide a running start.

**Comment by cletusw** [comment]
On a slightly different note, here's an .eslintrc that acts like a CSS Reset, setting all the rules to 0, providing a clean slate for customization: https://gist.github.com/cletusw/e01a85e399ab563b1236

I know you didn't want comments, but I added them anyway.

**Comment by nzakas** [comment]
@cletusw thanks. It's worth noting you can also use the `--reset` option to have zero rules enabled by default.

**Comment by cletusw** [comment]
True. It's nice to see all the options that are available along with their
current state, though.

2015-02-06 12:24 GMT-07:00 Nicholas C. Zakas <notifications@github.com>:

**Comment by IanVS** [comment]
I'd imagine this could be closed now that there is the `--init` flag, since the core of the issue seems to be getting a .eslintrc file for a new project.

**Comment by nzakas** [comment]
Yeah. I think the issue was really about providing examples to get started. With `--init` and shareable configs, we have some good options now.
