### ISSUE TITLE
This is because you're linting node_modules, which you shouldn't be. If you're in a monorepo with nested node_modules dirs, you have to add `**/node_modules` to your `.eslintignore`.

### ISSUE THREAD

**Issue by oimmc** [eslint/eslint#14546]
This is because you're linting node_modules, which you shouldn't be. If you're in a monorepo with nested node_modules dirs, you have to add `**/node_modules` to your `.eslintignore`.

_Originally posted by @ljharb in https://github.com/eslint/eslint/issues/14533#issuecomment-828506394_

Still not available

**Comment by ljharb** [comment]
Seems like a spam/accidental issue?

**Comment by oimmc** [comment]
exclude: /node_modules/

you are right, I find it.

**Comment by ljharb** [comment]
Add it to `.eslintignore`, yes

**Comment by aladdin-add** [comment]
please move to the discussion: https://github.com/eslint/eslint/discussions/14544
