### ISSUE TITLE
eslint --init "Which framework does your project use?"

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#14566]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**

when running `eslint --init`. the choice of question "Which framework does your project use?" defaults to react.
![image](https://user-images.githubusercontent.com/13050025/117014761-b231c980-ad23-11eb-9b08-168a013ace31.png)

I argue it make more sense to defaults to "none"(the 3rd choice)

**Your take on the correct solution to problem.**

**Are you willing to submit a pull request to implement this change?**
y

**Comment by nzakas** [comment]
I don’t think this matters one way or another. Someone will always think that the default is wrong based on their own usage so I’m not sure this is something we should spend any time on.

**Comment by aladdin-add** [comment]
well, I agreed it is not a big deal, although I don't think we should default to any framework. just like the option "jsx" was not enabled by default.
