### ISSUE TITLE
.eslintcache could use relative pathes to give the opportunity of sharing the file in a project.

### ISSUE THREAD

**Issue by Plopsi** [eslint/eslint#14571]
**The version of ESLint you are using.**
7.24.0

**The problem you want to solve.**
.eslintache should use relative pathes for saving informations about the linted file. This would be a nice to have feature, as a necessary or mandatory usecase is rare. It would open the possiblity to 'share' the .eslintcache file, or make use of it in a pipeline.

**Your take on the correct solution to problem.**
N/A

**Are you willing to submit a pull request to implement this change?**
Sorry, no time to read into the eslint-code currently. So sadly no :(

**Comment by nzakas** [comment]
This is an interesting thought, but without a use case there’s no reason to investigate this.

**Comment by Plopsi** [comment]
yeah... you are right, it was overall just a thourght and a I have a not necessary use case - I come back with a PR when I got time :)

later... sadly much later... :/
