### ISSUE TITLE
Feature request: improve how configurations may be extended/loaded from the command line

### ISSUE THREAD

**Issue by jeffrson** [eslint/eslint#14574]
**The version of ESLint you are using.**
7.24.0

**The problem you want to solve.**

I would like to "extend" rules by another set of rules contained in a "shareable configs" (inside a dependent package - https://eslint.org/docs/developer-guide/shareable-configs) from the commandline, like it is possible via package.json:
```
"eslintConfig": {
        "extends": "plugin:@scope/eslint-plugin/require-types"
}
```

This way it would be possible to have a set of standard rules when using eslint via editor (eg. VSCode), and use extended rules only on purpose directly from command line or through a package.json script.

Other ways to achieve this don't seem to work:

* use "-c"- this needs a "real" file, which "@scope\eslint-config\require-types" is not
In case of a single package, "node_modules/@scope/eslint-config/require-types" would work, but not in a workspace. There I would need to include several "..", which is inflexible and doesn't work at all for packages that shall be used inside as well as outside a workspace

* use "--plugin" respects the package ("@scope\eslint-config"), but there appears to be no way for naming the config to be used

**Comment by nzakas** [comment]
Thanks for opening this. It looks like there are two issues here:

1. you cant specify a shared config using the command line
2. there is no way to reference a config inside of a plugin from the command line

These are most likely unintentional oversights but I’d like some more opinions from the team. 

@aladdin-add please only move issues to Triaging if you are actively working with the issue creator to triage.

**Comment by mdjermanovic** [comment]
@jeffrson can you make a new config file, extend the shareable config/plugin config from that file, and then use that new config file in `-c`?

```js
//----------- additional-config.js ------------------

module.exports = {
    extends: ["plugin:@scope/eslint-plugin/require-types"]
};
```

```bash
eslint . -c additional-config.js
```

**Comment by jeffrson** [comment]
AFAICT this does not work when the file "additional-config.js" is distributed via shareable config.

`eslint -c <file>` does not know how to find "additional-config.js" inside the shareable config.

**Comment by mdjermanovic** [comment]
> AFAICT this does not work when the file "additional-config.js" is distributed via shareable config.

Yes, that wouldn't work. The idea was to add a config file to the project, as a workaround. Would that work for you?

**Comment by jeffrson** [comment]
It does work as it seems, but it defeats the purpose of the shared config if every project needs "additional-config.js".

**Comment by mdjermanovic** [comment]
@nzakas 

> * you cant specify a shared config using the command line
> * there is no way to reference a config inside of a plugin from the command line

In regard to the current `eslintrc` config system, this would be a request to add a CLI option that would accept config specifiers such as `plugin:@scope/eslint-plugin/require-types` or `@scope/eslint-config`, and then resolve them in the same way as `extends: [...]` in `eslintrc` files are resolved.

However, I'm not sure how would that option work with the new [flat config system](https://github.com/eslint/eslint/issues/13481). Does it seem that the option would be incompatible with the flat config system (which aims to avoid resolving modules), and therefore basically deprecated from the start?

Does flat config support use case where user wants to apply a config on top of the project's standard config? (with `eslintrc`, that can be achieved by `-c path/to/additional-config.js` without `--no-eslintrc`).

**Comment by nzakas** [comment]
> However, I'm not sure how would that option work with the new flat config system. Does it seem that the option would be incompatible with the flat config system (which aims to avoid resolving modules), and therefore basically deprecated from the start?

That is a good point. 🤔 I need to take another look once I can circle back to flat config.

> Does flat config support use case where user wants to apply a config on top of the project's standard config? (with eslintrc, that can be achieved by -c path/to/additional-config.js without --no-eslintrc).

Not as currently defined. The -c would take the place of the config file on disk, not add to it.

**Comment by nzakas** [comment]
I’ll take this as something to investigate as I’m working on the new config system

**Comment by mdjermanovic** [comment]
For the context, this feature was supported since ESLint v1.2.0 (https://github.com/eslint/eslint/pull/3063) but then removed in ESLint v6.0.0 (https://github.com/eslint/eslint/pull/11388).

Per [this change](https://github.com/eslint/eslint/pull/11388/files#diff-7d7a5060a56e821e7c2d33a27e8fede7b1f4d497956b68e85f3ea649878a269b) it looks like the feature was intentionally removed, though I can't find a mention of it in https://github.com/eslint/rfcs/pull/7.

**Comment by nzakas** [comment]
Just circling back to this again. Because flat config doesn't really have a notion of "extends", we can't move forward with making this change. The `-c` flag completely overrides anything else you have and expects a file. We just can't support `extends` from the command line when that concept doesn't exist in flag config.
