### ISSUE TITLE
[Feature Request]: newline-per-chained-call { consistent: true }

### ISSUE THREAD

**Issue by svenssonaxel** [eslint/eslint#14599]
**What rule do you want to change?**

newline-per-changed-call

**Does this change cause the rule to produce more or fewer warnings?**

`{ consistent: true, ignoreChainWithDepth: 2 }` would produce more than `{ ignoreChainWithDepth: 2 }`.

**How will the change be implemented? (New option, new default behavior, etc.)?**

A new option `{ consistent: true }` that requires that either all or none of the dot operators in a chain has a newline next to it.

**Please provide some example code that this change will affect:**

```js
d3.select("body").selectAll("p");
```

**What does the rule currently do for this code?**

With `{ ignoreChainWithDepth: 2 }`, it is changed to the following:

```js
d3.select("body")
  .selectAll("p");
```

**What will the rule do after it's changed?**

With `{ consistent: true, ignoreChainWithDepth: 2 }` it would be changed to the following:

```js
d3
  .select("body")
  .selectAll("p");
```

**Are you willing to submit a pull request to implement this change?**
Not currently.

**Comment by aladdin-add** [comment]
thanks for the suggestion, however stylistic rules are frozen according to our policy. please see https://github.com/eslint/eslint#stylistic-rule-updates
