### ISSUE TITLE
no-unused-expresssions showing error on optional chaining

### ISSUE THREAD

**Issue by Honatas** [eslint/eslint#14606]
**Tell us about your environment**
* **ESLint Version:** v7.24.0
* **Node Version:** v14.16.0
* **npm Version:** v7.10.0
* **Operating System:** Ubuntu 20.04

**What parser are you using?** @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking"
  ],
  "rules": {
    "array-bracket-spacing": [1, "never"],
    "arrow-spacing": 1,
    "brace-style": [1, "1tbs", {"allowSingleLine": true}],
    "camelcase": 1,
    "comma-dangle": [1, "always-multiline"],
    "comma-spacing": 1,
    "eol-last": 2,
    "indent": [1, 2, {"MemberExpression": 0}],
    "key-spacing": 1,
    "keyword-spacing": [1, {"overrides": {"catch": {"after": false}}}],
    "no-lonely-if": 2,
    "no-multiple-empty-lines": [2, {"max": 2, "maxBOF": 0, "maxEOF": 0}],
    "no-negated-condition": 2,
    "no-trailing-spaces": 1,
    "no-unneeded-ternary": 2,
    "no-unused-expressions": 1,
    "no-whitespace-before-property": 2,
    "one-var-declaration-per-line": 2,
    "semi": [1, "always", {"omitLastInOneLineBlock": true}],
    "semi-spacing": 1,
    "semi-style": 1,
    "space-before-blocks": [1, "always"],
    "space-before-function-paren": [1, "never"],
    "space-in-parens": [1, "never"],
    "space-unary-ops": 1,
    "spaced-comment": 1,
    "@typescript-eslint/explicit-module-boundary-types": 1,
    "@typescript-eslint/no-unsafe-member-access": 1,
    "@typescript-eslint/no-explicit-any": 1
  }
}
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
document.getElementById('my-element-id')?.classList.add('my-class');
```
I've used gulp-eslint to run
```js
const typescript = require('gulp-typescript');
const eslint = require('gulp-eslint');
function lintTs() {
  return typescript.createProject('tsconfig.json').src()
    .pipe(eslint())
    .pipe(eslint.format());
}
```

**What did you expect to happen?**
I've expected no errors

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Steps to reproduce this issue:**
1. Add an optional chaining (a.k.a. null-safe operator) to the code;
2. Add no-unused-expresssions rule to .eslintrc;
3. Run eslint.

**Are you willing to submit a pull request to fix this bug?**
Probably no.

**Comment by aladdin-add** [comment]
have you tried `@typescript-eslint/no-unused-expresssions`?

**Comment by Honatas** [comment]
I haven't, because I didn't knew it exist.

Well, actually I just did and it works as expected. The big problem I see now is that there is no easy way to find the docs on all rules available on @typescript-eslint. The md files are hidden in a deep folder inside the git repo and there is no link to them.

I suggest creating a md file as a rule list with links to all rules, and a link to this md file at the README.md (main page).

**Comment by nzakas** [comment]
The typescript-eslint project isn’t maintained by this team. You should refer to that repo for documentation on that project.
