### ISSUE TITLE
Same code is fixed via `ESLint` cli, but breaks via `RuleTester`

### ISSUE THREAD

**Issue by B2o5T** [eslint/eslint#14619]
I wrote a new rule for `graphql-eslint` that can fix code and via ESLint cli all works perfectly fine, the new rule fixes the code as I expected.

But when I try to test the same code via `RuleTester`, this breaks with unexpected `output`.
I started thinking what the problem might be, it went on for many hours of debugging

And what I found https://github.com/eslint/eslint/blob/master/lib/rule-tester/rule-tester.js#L567

The behavior of `CLIEngine` and `RuleTester` is different when we try to fix code

`CLIEngine` can attempt to fix code many times if it's needed, but `RuleTester` not, because in `CLIEngine` we call `linter.verifyAndFix` and in `RuleTester` we call `SourceCodeFixer.applyFixes`

when I add bottom changes in `rule-tester.js`, everything works fine in RuleTester, the behavior is the same as in cli
```diff
- output = SourceCodeFixer.applyFixes(code, messages).output;
+ const fixedResult = linter.verifyAndFix(code, config, { filename });
+ output = fixedResult.output;
- const errorMessageInFix = linter.verify(output, config, filename).find(m => m.fatal);
+ const errorMessageInFix = (fixedResult.messages || []).find(m => m.fatal);
```

**Tell us about your environment**

* **ESLint Version:** 7.27.0
* **Node Version:** v14.16.0
* **Operating System:** macOS

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by mdjermanovic** [comment]
Hi @B2o5T, thanks for the issue!

[RuleTester](https://eslint.org/docs/developer-guide/nodejs-api#ruletester) runs only one pass of autofixing:

> `output` (string, required if the rule fixes code): Asserts the output that will be produced when using this rule for a single pass of autofixing  

This is by design, please see the discussion in https://github.com/eslint/eslint/issues/11187.
