### ISSUE TITLE
"Configured parser was not found" when using Linter API 

### ISSUE THREAD

**Issue by swatisahay** [eslint/eslint#14636]
I'm attempting to run ESLint from the API to automatically lint some files. First, I get the local configuration  by eslint.calculateConfigForFile(.eslintrc.js), Then, I load the file text and run ESlint.Linter.verify(fileText, configuration, filePath). but  when I check the output messages, this is what I see:
 ruleId: null,
    fatal: true,
    severity: 2,
    message: "Configured parser '\\node_modules\\@typescript-eslint\\parser\\dist\\index.js' was not found.",
    line: 0,
    column: 0
  }
![image](https://user-images.githubusercontent.com/39397953/119716938-8b464f00-be1a-11eb-9f2f-3bab441ac843.png)

However, I know for certain that the parser file exists at this path. Am I doing something wrong, or is this a bug?

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by nzakas** [comment]
No response, so closing.
