### ISSUE TITLE
do not call the fix functions in no-autofix mode

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#14637]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**

eslint will always call the fix functions even in no-autofix mode.

**Your take on the correct solution to problem.**

do not call the fix functions in no-autofix mode. Pros:

* avoid crashing in no-autofix mode if there are bugs in the fixers. e.g., #14633 
* Perf improvement in no-autofix mode.

**Comment by mdjermanovic** [comment]
Running ESLint in no-autofix mode doesn't necessarily mean that fixes are not needed. Autofix mode (`--fix`) is more like "automatically apply fixes". Integrations can use [`LintMessage#fix`](https://eslint.org/docs/developer-guide/nodejs-api#-lintmessage-type) property to manually apply fixes ([vscode-eslint example](https://github.com/microsoft/vscode-eslint/blob/2e046709d5fd3078b995e8c9bb26b0e9e0ff6ff1/server/src/eslintServer.ts#L511)). I think that without an additional flag we can't really know whether or not the `fix` property will be used.

**Comment by aladdin-add** [comment]
good point! but at the very least, it can be skipped in eslint cli. :)

**Comment by nzakas** [comment]
I’m not sure this is worth changing without quantifying what kind of performance change we might get.

@aladdin-add if you’re interested in pursuing this, I’d suggest creating a perf test that shows the difference between what we have now and what you’re suggesting. I’m guessing the actual change is probably pretty small.

**Comment by nzakas** [comment]
Closing because we couldn’t reach consensus on moving forward here.
