### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by bilalmalkoc** [eslint/eslint#14639]
**Tell us about your environment**

* **ESLint Version:** 7.27.0
* **Node Version:** 12.22.1
* **npm Version:** 6.14.12
* **Operating System:**  MacOS 11.2.3 Big Sur with Apple silicon.

**Parser** @babel/eslint-parser
It is happeninng with default parser too.

**Configuration (.eslintrc)**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "browser": true,
    "es2021": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "prettier"
  ],
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "requireConfigFile": false,
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "rules": {
    "no-console": "warn",
    "prettier/prettier": "error"
  },
  "plugins": ["prettier"]
}
```

</details>

Tried on this simple code:

```js
import "./js/admin/accordion-table"

var x = 5;;
```

**Comment by nzakas** [comment]
Can you please fill out the full issue template?
https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

Thanks!

**Comment by nzakas** [comment]
No response, so closing.
