### ISSUE TITLE
Crash with `"arrow-body-style": ["error", "always"]`

### ISSUE THREAD

**Issue by alextewpin** [eslint/eslint#14633]
### Environment Info
Node version: v12.19.0
npm version: v6.14.8
Local ESLint version: v7.27.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.4.0

### Parser
`"@babel/eslint-parser": "7.14.3"`

### Description
ESLint breaks using rule `"arrow-body-style": ["error", "always"]` on a very specific function signature.

In my case it's `const createMarker = (color) => ({ latitude, longitude }, index) => {};`.

Other variations of `arrow-body-style` (`never` or `as-needed`) work fine.

[DEMO](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICBcImFycm93LWJvZHktc3R5bGVcIjogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxuY29uc3QgY3JlYXRlTWFya2VyID0gKGNvbG9yKSA9PiAoeyBsYXRpdHVkZSwgbG9uZ2l0dWRlIH0sIGluZGV4KSA9PiB7fTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by aladdin-add** [comment]
thx! confirmed, it also happened with the default parser.
