### ISSUE TITLE
Add Support for RegExp match indices

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint#14640]
**The version of ESLint you are using.**

7.27.0

**The problem you want to solve.**

Support RegExp match indices officially, as it has reached stage-4.
refs:
https://github.com/tc39/proposals/blob/master/finished-proposals.md
https://github.com/tc39/proposal-regexp-match-indices

**Your take on the correct solution to problem.**

- [x] Ecma262 update: tc39/ecma262#1713
- [x] Acorn update: acornjs/acorn#1039
- [x] `regexpp`update: https://github.com/mysticatea/regexpp/pull/22
- [x] `espree` update: https://github.com/eslint/espree/pull/505
- [ ] `eslint` update: #14653

We probably need to add `d` to the `validFlags ` of the no-invalid-regexp rule.
We probably need to add `d` to the `regex` variable of the no-empty-character-class rule.

**Are you willing to submit a pull request to implement this change?**

I will submit a pull request.

**Comment by ota-meshi** [comment]
Since acorn has been released, I would like to specify a new acorn in the espree dependency and make changes to allow 2022 for ecmaVersion. Is this acceptable?

https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#830-2021-05-31

When I make changes to ecmaVersion to allow 2022, acorn also tries to parse class fileds, but espree doesn't yet support it. Is es2022 syntax support done in v8.0.0?

**Comment by ota-meshi** [comment]
I saw the meeting memo. My understanding is that support for the ES2022 syntax will not be added to ESLint v7.
https://github.com/eslint/tsc-meetings/blob/master/notes/2021/2021-05-20.md#espree-class-fields

**Comment by nzakas** [comment]
Yes, we will be waiting to add ES2022 syntax in ESLint v8.0.0. This PR updates Acorn in Espree: https://github.com/eslint/espree/pull/505

**Comment by aladdin-add** [comment]
update: [regexpp v3.2.0 was released](https://github.com/mysticatea/regexpp/releases/tag/v3.2.0)!

**Comment by ota-meshi** [comment]
Thank you for letting me know!
