### ISSUE TITLE
padding-line-between-statements: multiline-const rules are ignored when using export

### ISSUE THREAD

**Issue by cseas** [eslint/eslint#14655]
**Tell us about your environment**

Node version: v14.16.1
npm version: v7.15.0
Local ESLint version: v7.25.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.5.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: ["./tsconfig.json"],
  },
  plugins: ["@typescript-eslint", "import"],
  extends: [
    // https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  rules: {
    // https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
    "import/order": [
      "warn",
      {
        groups: [["builtin", "external"], "internal", ["parent", "sibling"]],
        pathGroups: [
          { pattern: "src/**", group: "internal", position: "before" },
          { pattern: "client/**", group: "internal" },
        ],
        pathGroupsExcludedImportTypes: ["builtin", "parent", "sibling"],
        "newlines-between": "always",
        alphabetize: { order: "asc", caseInsensitive: false },
      },
    ],
    // https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#examples
    "@typescript-eslint/naming-convention": [
      "error",
      {
        selector: ["variable", "parameter", "property"],
        types: ["boolean"],
        format: ["PascalCase"],
        prefix: ["is", "should", "has", "can", "did", "will", "enable"],
      },
    ],
    // http://eslint.org/docs/rules/padding-line-between-statements
    "padding-line-between-statements": [
      "warn",
      { blankLine: "always", prev: "block-like", next: "return" },
      { blankLine: "always", prev: "multiline-const", next: "multiline-const" },
    ],
  },
  // https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns
  overrides: [
    {
      files: ["**/*.js"],
      rules: {
        // disable type aware linting
        "@typescript-eslint/no-unsafe-member-access": "off",
        "@typescript-eslint/no-unsafe-call": "off",
        "@typescript-eslint/no-unsafe-assignment": "off",
        "@typescript-eslint/restrict-plus-operands": "off",
        "@typescript-eslint/no-unsafe-return": "off",
        // allow require imports
        "@typescript-eslint/no-var-requires": "off",
      },
    },
  ],
  env: {
    browser: true,
    node: true,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export const CUSTOMER = {
  id: "Id",
  name: "Name",
};
export const CONFIG = {
  url: "https://github.com/",
  book: {
    url: "https://en.wikipedia.org/wiki/Book",
    url2: "https://en.wikipedia.org/wiki/Book",
  },
};
```

```bash
eslint . --ext .js,.jsx,.ts,.tsx
```

**What did you expect to happen?**

The below rule should enforce a line padding between all multiline const statements:
`{ blankLine: "always", prev: "multiline-const", next: "multiline-const" },`

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

No ESLint warning is shown for the given code.

**Steps to reproduce this issue:**

1. Write two multiline const statements.
1. Verify that the above rule works and throws a warning if a newline is not present between the statements.
1. Add `export` to the statements. Now the rule will allow having no newline between the two statements.

**Are you willing to submit a pull request to fix this bug?**
I'm not sure how to fix this

An alternative to the above use case is to write a rule for multiline export statements but `multiline-export` is not a valid [STATEMENT_TYPE](https://eslint.org/docs/rules/padding-line-between-statements) for this rule.

**Comment by cseas** [comment]
Code and steps to reproduce the issue is included. Not sure why `repro:needed` label got added.

**Comment by aladdin-add** [comment]
no worries, it only means needs a eslint team member to confirm it.

**Comment by nzakas** [comment]
@cseas can you try with the default ESLint parser to rule out a TypeScript-specific issue?

**Comment by cseas** [comment]
Just tried removing the `"parser"` field from `.eslintrc.js` and could reproduce the error even without a parser specified.

**Comment by mdjermanovic** [comment]
This works as expected. `export const` is of the `"export"` statement type for this rule, so only the configuration for `"export"` applies.

```js
/* eslint padding-line-between-statements: ["error",
	{ blankLine: "always", prev: "export", next: "export" }
]*/

export const CUSTOMER = {
  id: "Id",
  name: "Name",
};
export const CONFIG = { // error, expected blank line before this statement
  url: "https://github.com/",
  book: {
    url: "https://en.wikipedia.org/wiki/Book",
    url2: "https://en.wikipedia.org/wiki/Book",
  },
};
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHBhZGRpbmctbGluZS1iZXR3ZWVuLXN0YXRlbWVudHM6IFtcImVycm9yXCIsXG5cdHsgYmxhbmtMaW5lOiBcImFsd2F5c1wiLCBwcmV2OiBcImV4cG9ydFwiLCBuZXh0OiBcImV4cG9ydFwiIH1cbl0qL1xuXG5leHBvcnQgY29uc3QgQ1VTVE9NRVIgPSB7XG4gIGlkOiBcIklkXCIsXG4gIG5hbWU6IFwiTmFtZVwiLFxufTtcbmV4cG9ydCBjb25zdCBDT05GSUcgPSB7IC8vIGVycm9yLCBleHBlY3RlZCBibGFuayBsaW5lIGJlZm9yZSB0aGlzIHN0YXRlbWVudFxuICB1cmw6IFwiaHR0cHM6Ly9naXRodWIuY29tL1wiLFxuICBib29rOiB7XG4gICAgdXJsOiBcImh0dHBzOi8vZW4ud2lraXBlZGlhLm9yZy93aWtpL0Jvb2tcIixcbiAgICB1cmwyOiBcImh0dHBzOi8vZW4ud2lraXBlZGlhLm9yZy93aWtpL0Jvb2tcIixcbiAgfSxcbn07XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

Configuration entries with `"const"`, `"singleline-const"`, or `"multiline-const"` statement type do not apply to `export const` statements.

**Comment by cseas** [comment]
Would it be possible to make this a feature request to add `"multiline-export"`? 

Right now the `"export"` statement type applies to all exports. This might be undesirable when a file contains a lot of single line exports. Like in the case of `index.js` files that usually re-export things from a module.

**Comment by nzakas** [comment]
@cseas we aren't currently adding new options to rules that just enforce stylistic preferences. You can, of course, create your own version of the rule that will behave the way you would like.
