### ISSUE TITLE
Linter ignores multiline `/* eslint-env */` directives

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#14652]
**Tell us about your environment**

* **ESLint Version:** v7.27.0
* **Node Version:** v12.18.4
* **npm Version:** v6.14.6
* **Operating System:** windows

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  rules: {
    "no-undef": "error"
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* eslint-env browser 
*/

window;

```

```bash
npx eslint index.js
```

**What did you expect to happen?**

no `no-undef` errors, because `browser` environment enables `window` global

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

```
  4:1  error  'window' is not defined  no-undef
```

**Steps to reproduce this issue:**

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50LWVudiBicm93c2VyIFxuKi9cblxud2luZG93OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdW5kZWYiOjJ9LCJlbnYiOnt9fX0=)

**Are you willing to submit a pull request to fix this bug?**

Yes, if it is a bug.

The issue is: linter ignores _multiline_ `/* eslint-env ... */` comments. A single-line comment works well, as in [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50LWVudiBicm93c2VyICovXG5cbndpbmRvdzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXVuZGVmIjoyfSwiZW52Ijp7fX19).

I couldn't find a test case or a discussion that would confirm that this was intentional. It looks like a common bug with `.` in a regular expression that doesn't have the `s` flag.

Also, `noInlineConfig: true` option does report multiline `eslint-env` as a directive:

```js
module.exports = {
  rules: {
    "no-undef": "error"
  },
  noInlineConfig: true
};
```

```js
/* eslint-env browser 
*/

window;

```

```
  1:1  warning  '/*eslint-env*/' has no effect because you have 'noInlineConfig' setting in your config (.eslintrc.js)
  4:1  error    'window' is not defined  
```

**Comment by mdjermanovic** [comment]
@eslint/eslint-tsc Thoughts about this? I think this is a bug, but would like another confirmation. We have PR https://github.com/eslint/eslint/pull/14660 prepared.

**Comment by nzakas** [comment]
Most likely a bug. I’m not sure how much it matters since this feature will be going away, but no objections to fixing it.
