### ISSUE TITLE
--ext doesn't work on the command line

### ISSUE THREAD

**Issue by TheDutchCoder** [eslint/eslint#14650]
**Tell us about your environment**

* **ESLint Version:** 7.27.0
* **Node Version:** 16.0.0
* **npm Version:** 7.15.0
* **Operating System:** Mac OS 11.4

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

NPM Script:
```json
"lint": "eslint -c .eslintrc.js --ext .js,.ts,.vue --fix --quiet \"src/**/*.*\""
```

```js
module.exports = {
  env: {
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:vue/base',
    'plugin:vue/vue3-recommended',
    '@vue/typescript/recommended',
  ],
  ignorePatterns: [
    '**/assets/**/*.*',
  ],
  rules: {
    '@typescript-eslint/ban-ts-ignore': 0,
    '@typescript-eslint/indent': ['error', 2],
    'linebreak-style': [
      'error',
      'unix',
    ],
    'quotes': [
      'error',
      'single', {
        'allowTemplateLiterals': true,
      },
    ],
    'semi': [
      'error',
      'never',
    ],
    'space-before-function-paren': [
      'error',
      'always',
    ],
    'object-curly-spacing': [
      'error',
      'always',
    ],
    'eqeqeq': [
      'error',
      'always',
    ],
    'vue/eqeqeq': [
      'error',
      'always',
    ],
    'eol-last': [
      'error',
      'always',
    ],
    'comma-dangle': [
      'error',
      {
        'arrays': 'always-multiline',
        'objects': 'always-multiline',
        'imports': 'always-multiline',
        'exports': 'always-multiline',
        'functions': 'never',
      },
    ],
  },
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

N/A

```bash
npm run lint
```

**What did you expect to happen?**
`.css` files not to be linted

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
`.css` files got linted, as well as fonts. It basically fully ignores the `--ext .ts,.js,.vue` parameter

**Steps to reproduce this issue:**

1. Create a `src` folder with some font/css files
2. Run `npm lint`with the following script and config (see above): `"lint": "eslint -c .eslintrc.js --ext .js,.ts,.vue --fix --quiet \"src/**/*.*\""`
3. eslint will complain about them

**Are you willing to submit a pull request to fix this bug?**
If I know where/what to fix, sure!

**Comment by mdjermanovic** [comment]
Hi @TheDutchCoder, thanks for the issue!

Per the [documentation for `--ext`](https://eslint.org/docs/user-guide/command-line-interface#-ext), it is only used when the arguments are directories, so it's ignored when used with `src/**/*.*` pattern (which matches all files in `src`, including `.css` files).

Can you try with the following script:

```
"lint": "eslint -c .eslintrc.js --ext .js,.ts,.vue --fix --quiet src"
```

**Comment by nzakas** [comment]
No response, so closing.
