### ISSUE TITLE
Prefer-destructuring: an option to ignore reassignments

### ISSUE THREAD

**Issue by webdif** [eslint/eslint#14668]
An old issue (https://github.com/eslint/eslint/issues/7886) raised the concern of reassignment.
Use destructuring when reassign a variable require parentheses that can be hard to read.
It would be wonderful to prefer destructuring for assignment, but ignore the rule for reassignment.

**What rule do you want to change?**
`prefer-destructuring`

**Does this change cause the rule to produce more or fewer warnings?**
fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option

**Please provide some example code that this change will affect:**

```js
let b = 0;
const obj = { a: 1, b: 2};

// Assignment: we prefer destructuring
const { a } = obj;

// Reassignment: we prefer to avoid hard to read parentheses
b = obj.b;
```

**What does the rule currently do for this code?**
An error in the last line.

**What will the rule do after it's changed?**
The last line will be fine if we can add an option to ignore the rule at reassignment.

**Are you willing to submit a pull request to implement this change?**
I have never contribute yet, so I'm unfamiliar with the code. But I will be happy to try :)

**Comment by mdjermanovic** [comment]
Hi @webdif, thanks for the issue!

That option already exists - you can [configure](https://eslint.org/docs/rules/prefer-destructuring#options) this rule to enforce destructuring only in declarations.

Example:

```js
/* eslint "prefer-destructuring": ["error", {
      "VariableDeclarator": {
        "array": true,
        "object": true
      },
      "AssignmentExpression": {
        "array": false,
        "object": false
      }
}]*/

let b = 0;
const obj = { a: 1, b: 2};

const a = obj.a; // error, because VariableDeclarator.object is set to `true`

b = obj.b; // ok, because AssignmentExpression.object is set to `false`
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwicHJlZmVyLWRlc3RydWN0dXJpbmdcIjogW1wiZXJyb3JcIiwge1xuICAgICAgXCJWYXJpYWJsZURlY2xhcmF0b3JcIjoge1xuICAgICAgICBcImFycmF5XCI6IHRydWUsXG4gICAgICAgIFwib2JqZWN0XCI6IHRydWVcbiAgICAgIH0sXG4gICAgICBcIkFzc2lnbm1lbnRFeHByZXNzaW9uXCI6IHtcbiAgICAgICAgXCJhcnJheVwiOiBmYWxzZSxcbiAgICAgICAgXCJvYmplY3RcIjogZmFsc2VcbiAgICAgIH1cbn1dKi9cblxubGV0IGIgPSAwO1xuY29uc3Qgb2JqID0geyBhOiAxLCBiOiAyfTtcblxuY29uc3QgYSA9IG9iai5hOyAvLyBlcnJvciwgYmVjYXVzZSBWYXJpYWJsZURlY2xhcmF0b3Iub2JqZWN0IGlzIHNldCB0byBgdHJ1ZWBcblxuYiA9IG9iai5iOyAvLyBvaywgYmVjYXVzZSBBc3NpZ25tZW50RXhwcmVzc2lvbi5vYmplY3QgaXMgc2V0IHRvIGBmYWxzZWAiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)
