### ISSUE TITLE
padding-line-between-statements: Add STATEMENT_TYPE for tests

### ISSUE THREAD

**Issue by cseas** [eslint/eslint#14664]
**What rule do you want to change?**
padding-line-between-statements

**Does this change cause the rule to produce more or fewer warnings?**
More

**How will the change be implemented? (New option, new default behavior, etc.)?**
New STATEMENT_TYPE

**Please provide some example code that this change will affect:**

```js
describe("Test Suite", () => {
    it("has a test", () => {
        expect(1).to.equal(1);
    });
    it("has another test", () => { // Error
        expect(2).to.equal(2);
    });
});
```

**What does the rule currently do for this code?**
No way to enforce padding line between test statements right now.

**What will the rule do after it's changed?**
Provide an "it" or "test" statement type to configure line padding rules for tests.

**Are you willing to submit a pull request to implement this change?**
Not sure how to

Reopening since the old related issue #8849 was closed. Maybe more people would like to have this now.
cc: @ebramanti

**Comment by mdjermanovic** [comment]
Hi @cseas, thanks for the issue! 

The team has made the difficult decision to freeze stylistic rules (please find more details in [this blog post](https://eslint.org/blog/2020/05/changes-to-rules-policies)), so we won't be adding any options to the `padding-line-between-statements` rule. You can always make a custom rule or publish a plugin.

I'm closing this issue per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates).

**Comment by cseas** [comment]
Thanks for the quick response! I figured out there is a plugin for this.
For anyone looking for reference, [eslint-plugin-jest-formatting](https://github.com/dangreenisrael/eslint-plugin-jest-formatting) does this.
