### ISSUE TITLE
new-line-per-chained-call ignoreChainWIthDept=1

### ISSUE THREAD

**Issue by bovandersteene** [eslint/eslint#14685]
**Tell us about your environment**

* **ESLint Version:**
7.28.0
* **Node Version:**
14.17.0
* **npm Version:**
7.16.0
* **Operating System:** 
Mac OS

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

I would expect that the `newline-per-chained-call` would take over the ignoreChainWithDept but it seems that it takes over the default depth of 2 chained values.

```js
        "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 1 }],
```
 

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
obj.method().method()
```
 

**What did you expect to happen?**

```js
obj
     .method()
     .method()
```

or 
```js
obj.method()
     .method()
```

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
```js
obj.method().method()
```

**Comment by mdjermanovic** [comment]
Hi @bovandersteene, thanks for the issue!

 `newline-per-chained-call": ["error", { "ignoreChainWithDepth": 1 }]` auto-fixes `obj.method().method()` to:

```js
obj.method()
.method()
```

[Online demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwibmV3bGluZS1wZXItY2hhaW5lZC1jYWxsXCI6IFtcImVycm9yXCIsIHsgXCJpZ25vcmVDaGFpbldpdGhEZXB0aFwiOiAxIH1dICovXG5cbm9iai5tZXRob2QoKS5tZXRob2QoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=) 

You can also enable `indent` for additional formatting, and then the final result will be same as the second one in 'What did you expect to happen' section:

```js
obj.method()
    .method()
```

It looks to me that this works as expected, but maybe I didn't understand the issue.

**Comment by nzakas** [comment]
Looks like there is nothing else to do here, so closing.
