### ISSUE TITLE
Make Dependabot / Renovate pick up the formatted release notes

### ISSUE THREAD

**Issue by voxpelli** [eslint/eslint#14708]
### The version of ESLint you are using:

ESLint 7.27.0 to 7.28.0

### The problem you want to solve:

Neither Dependabot or Renovate are picking up the nice release notes that's posted on eslint.org: https://eslint.org/blog/2021/06/eslint-v7.28.0-released

Instead they both pick up what's in the CHANGELOG and/or GitHub Releases.

A Renovate example: https://github.com/voxpelli/eslint-config/pull/30

![Skärmavbild 2021-06-15 kl  11 47 01](https://user-images.githubusercontent.com/34457/122032329-d3301480-cdcf-11eb-9737-0978e5dfed1b.png)

A randomly found public Dependabot example: https://github.com/dangoslen/changelog-enforcer/pull/128

![Skärmavbild 2021-06-15 kl  11 47 55](https://user-images.githubusercontent.com/34457/122032363-daefb900-cdcf-11eb-8237-68cc4252ee37.png)

### Your take on the correct solution to problem:

I would much prefer to get [the nicely formatted release notes from eslint.org](https://eslint.org/blog/2021/06/eslint-v7.28.0-released) rather than the unformatted one [that's in GitHub releases](https://github.com/eslint/eslint/releases/v7.28.0).

Exactly how to achieve that, I'm not sure.

Would it be possible to format the changes in the CHANGELOG and GitHub Releases as nicely as the one on eslint.org? Since it's written anyway it seems a waste that not everyone are getting it and that all who are reading the release notes through Dependabot / Renovate are not even made aware of the formatted release notes (I for a long while wasn't)

### Are you willing to submit a pull request to implement this change?

Yes, when the correct change has been figured out, if a PR can be made to fix it, then I'm up for it.

**Comment by nzakas** [comment]
When you say “nicely formatted” are you referring to the commits being grouped under the category names? Or are you also referring to the highlights?

Its worth noting that we are planning on moving to a new release tool at some point, so we may not take up any changes to the current tool in the meantime, but still good to get an idea about what folks would like.

**Comment by voxpelli** [comment]
@nzakas Especially the highlights, as the grouping can be somewhat inferred from the release notes today, but both would be neat.

What I mainly look for in minor-level releases are what new features that could be of use to me, and that's pretty much the same purpose that the highlights serve.

Is there an issue tracking the new release tool? If so, I might subscribe and lurk around there 👍

**Comment by aladdin-add** [comment]
related: https://github.com/eslint/eslint/issues/14231

**Comment by nzakas** [comment]
We can definitely explore that. The problem with the highlights is that they are written by hand so tough to automate it everywhere. It’s probably worth doing something that can sync changes between the blog and the GitHub release when we revisit the release process.

**Comment by nzakas** [comment]
Assigning to myself to review as we update the release process.

**Comment by voxpelli** [comment]
Works for Renovate bot now at least: https://github.com/voxpelli/eslint-config/pull/103
