### ISSUE TITLE
Support eslint --watch/-w like tsc --watch

### ISSUE THREAD

**Issue by nojvek** [eslint/eslint#14736]
**The version of ESLint you are using.**
v7.28.0

**The problem you want to solve.**
Run `yarn eslint --watch` to get live feedback as code is fixed. Re-running eslint especially with plugins such as `@typescript/eslint` is very expensive. There is ~10 second overhead on a medium sized project. The feedback cycle is too slow.

**Your take on the correct solution to problem.**
Same api as `tsc --watch` https://www.typescriptlang.org/docs/handbook/compiler-options.html

I run a separate `tsc --watch` terminal window, to get immediate feedback as I fix code. #1 issue of CI failing on PRs is due to eslint. Would be nice to have eslint watcher giving feedback in `<1s` as code is changed.

when invoked, the input files are watched for changes, when they update, eslint re-runs on those files to give live feedback of remaining errors.

**Are you willing to submit a pull request to implement this change?**

I can, if someone gives me a pointer.

**Comment by nzakas** [comment]
Thanks for the suggestion. This has been brought up a few times (https://github.com/eslint/eslint/issues/13000 for one), and the team doesn’t believe this should be something built in to ESLint. There are plenty of other ways to accomplish the same thing, and we don’t feel we could provide a better experience than any of the available options today.
