### ISSUE TITLE
Package-lock.json should be committed

### ISSUE THREAD

**Issue by tiziodcaio** [eslint/eslint#14740]
**The version of ESLint you are using.**
I'm not using now

**The problem you want to solve.**
Package-lock.json should be committed, as sayed [here](https://nodejs.dev/learn/the-package-lock-json-file)

**Your take on the correct solution to problem.**
Remove from .gitignore

**Are you willing to submit a pull request to implement this change?**
If you approve them I will happy to do it!

**Comment by mdjermanovic** [comment]
Hi @tiziodcaio, thanks for the issue!

We're not using package-lock.json for the reasons described here:

https://github.com/eslint/eslint#why-doesnt-eslint-lock-dependency-versions

**Comment by tiziodcaio** [comment]
Ok don't worry if you think that, you can ignore the issue
