### ISSUE TITLE
[Possible Deprecation?] no-eq-null (Seems redundant against eqeqeq)

### ISSUE THREAD

**Issue by gfyoung** [eslint/eslint#14749]
`eqeqeq` allows for the specific and individual configuration of linting equality checks against `null`.

IMO this makes the `no-eq-null` rule (as a standalone) unnecessary.

FYI: I wasn't sure what the right issue category was for this, since this is a proposal (not a problem) to completely deprecate a rule (which is technically a change).  Depending on the response, happy to go through with this via a PR.

**Comment by btmills** [comment]
You’re absolutely right that `eqeqeq` does everything `no-eq-null` does and more. However, `no-eq-null` was [originally added](https://github.com/eslint/eslint/pull/179) for compatibility with JSHint. `no-eq-null` reduces friction migrating to ESLint so users can gradually enable more powerful rules like `eqeqeq` later.

**Comment by gfyoung** [comment]
Thanks @btmills for this context!  In that case, shouldn't this be documented?

**Comment by ljharb** [comment]
@btmills are people still trying to migrate from jshint?

**Comment by btmills** [comment]
> In that case, shouldn't this be documented?

Good point, the [`no-eq-null` docs](https://eslint.org/docs/rules/no-eq-null) could certainly indicate it exists for compatibility but recommend `eq-eq-eq`. Are you willing to submit a documentation PR @gfyoung? We can reopen this if so!

> are people still trying to migrate from jshint?

It still gets a couple million monthly downloads, so I wouldn't want to close off the path without a strong benefit.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/jshint says 400K/week, so about 1-2 million a month, but sure, fair enough. Note tho, that it's not every jshint user, it'd only be the subset of those users that use that specific rule.

**Comment by gfyoung** [comment]
> Are you willing to submit a documentation PR @gfyoung? We can reopen this if so!

@btmills : I can open a PR for this. 👍

**Comment by gfyoung** [comment]
Thanks @btmills.  PR is already open as you saw.
