### ISSUE TITLE
Remove `SourceCode#getComments()`

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#14744]
**The version of ESLint you are using.**

ESLint 7.29.0 with Espree 8.0.0-beta.1

**The problem you want to solve.**

This test is failing:

https://github.com/eslint/eslint/blob/f113cdd872257d72bbd66d95e4eaf13623323b24/tests/lib/source-code/source-code.js#L909-L968

because `sourceCode.getComments(node)` uses `start` and `end` properties of nodes and tokens:

https://github.com/eslint/eslint/blob/f113cdd872257d72bbd66d95e4eaf13623323b24/lib/source-code/source-code.js#L351-L357

and after the change in https://github.com/eslint/espree/pull/461, `Program.start` is no longer `0` but `body[0].start`:

https://github.com/eslint/espree/blob/e08c9d78745fcee03136b57f46d09e11cad70861/lib/espree.js#L171

**Your take on the correct solution to problem.**

Remove `SourceCode#getComments()`?

It was deprecated in ESLint v4.0.0 (https://github.com/eslint/eslint/commit/735d02d570f4a2d3c663f0f4c6a6d4e4223aeb32):

> Please note that the following methods have been deprecated and will be removed in a future version of ESLint:
>
>    * `getComments()` - replaced by `getCommentsBefore()`, `getCommentsAfter()`, and `getCommentsInside()`

In ESLint v7.0.0, `RuleTester` was updated to throw on any access to `start` and `end` properties. Consequently, rules that use `sourceCode.getComments()` should have already noticed errors (e.g., https://github.com/eslint/eslint/issues/13293) and switched to other methods.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by nzakas** [comment]
I'm not opposed to removing it but since we already locked down and announced the changes coming in v8.0.0, it seems like we should wait until v9.0.0 and maybe just add a deprecation warning in v8.0.0?

**Comment by mdjermanovic** [comment]
Then we probably should fix it, since it will be broken with Espree 8.

**Comment by nzakas** [comment]
Agreed, sorry, that's what I meant to imply.

**Comment by mdjermanovic** [comment]
Prepared a quick fix: https://github.com/eslint/eslint/pull/14748

**Comment by mdjermanovic** [comment]
I added this to v9.0.0 project.

> maybe just add a deprecation warning in v8.0.0

That would be throwing an error in RuleTester? It already throws on any access to start/end properties, so that might be good enough, though not all code paths in `SourceCode#getComments()` use start/end .

**Comment by nzakas** [comment]
Throwing an error in RuleTester sounds good.

**Comment by mdjermanovic** [comment]
Prepared https://github.com/eslint/eslint/pull/14769 to throw an error in RuleTester if `SourceCode#getComments()` was called, starting from ESLint v8.0.0.

The remaining task is to completely remove `SourceCode#getComments()` in ESLint v9.0.0.

**Comment by mdjermanovic** [comment]
Reopening since it isn't completed (there's still a task to remove the method in v9.0.0).

**Comment by nzakas** [comment]
Weird. No idea what could have caused it to close. Nice catch.
