### ISSUE TITLE
es6jsx: Ability to use different file extensions (.jsx)

### ISSUE THREAD

**Issue by pselden** [eslint/eslint#1475]
It appears that no rules are being run on .jsx files because of an explicit check on file extensions: https://github.com/eslint/eslint/blob/es6jsx/lib/cli-engine.js#L224.

Is it possible to include either an option to specify what file extension should be traversed or simply also include .jsx files when jsx mode is on?

**Comment by nzakas** [comment]
Closing in favor of #801 (the fix for which has already been merged)
