### ISSUE TITLE
Add ignore list to no-use-before-define

### ISSUE THREAD

**Issue by ManhVuTien** [eslint/eslint#14758]
**What rule do you want to change?**
no-use-before-define
**Does this change cause the rule to produce more or fewer warnings?**
fewer
**How will the change be implemented? (New option, new default behavior, etc.)?**
I want to add some variables that can be ignored when enabling rule
**Please provide some example code that this change will affect:**

```js
const Example = () => {
    const demo = () => {
        test();
    };
    const test = () => {
        console.log('test');
    };
    return <View style={styles.container} />;
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
});

export default Example;
```

**What does the rule currently do for this code?**
 `test` and `styles` error because they were used before it was defined

**What will the rule do after it's changed?**
I want the `styles` will be ignored

**Are you willing to submit a pull request to implement this change?**

**Comment by nzakas** [comment]
We can’t really add an ignores list to this rule because the scope of the variable matters. If you were to ignore “styles”, it would ignore any variable named “styles” regardless of it were a global or local. Your best bet is to use a disable comment on just the variables you want to ignore.

**Comment by ManhVuTien** [comment]
> We can’t really add an ignores list to this rule because the scope of the variable matters. If you were to ignore “styles”, it would ignore any variable named “styles” regardless of it were a global or local. Your best bet is to use a disable comment on just the variables you want to ignore.

In my case I want to ignore all "styles" in project,
