### ISSUE TITLE
Add `ignore-single-line-objects` option to `sort-keys`

### ISSUE THREAD

**Issue by lougreenwood** [eslint/eslint#14751]
**What rule do you want to change?**
`sort-keys`

**Does this change cause the rule to produce more or fewer warnings?**
fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option

**Please provide some example code that this change will affect:**

Applying the `sort-keys` rule to short objects which do not span multiple lines is arguably of less value than when the rule is applied to multiple-line objects.

Because the rule is also not auto-fixable, fixing many single-line object definitions is hard since you have to cut and paste each key/value pair individually (unlike fixing a block, which simply requires moving a key/value pair up or down).

By adding some kind of `ignore-single-line-objects` option to `sort-keys`, we can minimise the burden of adopting the rule for the use cases where it is arguably most valuable.

```js
// No warning
const thing = { b: 'hi', a: 'hello' };

// Has warning
const thingB = {
  b: 'hi',
  a: 'hello'
}
```

**What does the rule currently do for this code?**
It would flag both examples as lint rule violations.

**What will the rule do after it's changed?**
Objects which are only on one line will not violate the `sort-keys` rule.

**Are you willing to submit a pull request to implement this change?**
Sorry, no 😞

**Comment by nzakas** [comment]
Thanks for the suggestion. However, we are no longer adding options to rules that just enforce stylistic preferences.

**Comment by lougreenwood** [comment]
Thanks @nzakas, is there a blog post or something explaining this decision? I'm guessing this is the first steps of an effort to handover codestyle to Prettier?
