### ISSUE TITLE
`no-unreachable`: downgrade from autofix to suggestion

### ISSUE THREAD

**Issue by mmkal** [eslint/eslint#14761]
**What rule do you want to change?**

`no-unreachable`

**Does this change cause the rule to produce more or fewer warnings?**

Neither

**How will the change be implemented? (New option, new default behavior, etc.)?**

Change `fix: ...` to `suggest: [{ fix: ... }]`

**Please provide some example code that this change will affect:**

```js
const functionThatIAmWorkingOn = () => {
  doThing1()
  doThing2()
  
  return // todo: remove - thanks eslint, for not letting me forget to remove it!

  someComplexApplicationLogicThatISpentHoursWritingAndVeryMuchDoNotWantToBeDeleted()
  iAmJustNotQuiteReadyToDebugItThatIsWhyIPutTheReturnStatementAbove()
  seriouslyICouldLoseHoursOfWorkIfICloseMyIDEAndCantControlZItBackIntoExistence()
}
```

**What does the rule currently do for this code?**

It brutally **deletes** my work!

**What will the rule do after it's changed?**

**Suggest** that I delete my work - but most likely instead I will remove the `return` statement which I only added temporarily for debugging.

**Are you willing to submit a pull request to implement this change?**

Maybe, if someone could point me in the right direction. I don't actually see where the `fix` part of [no-unreachable](https://github.com/eslint/eslint/blob/aa87329d919f569404ca573b439934552006572f/lib/rules/no-unreachable.js) is.

**Comment by mdjermanovic** [comment]
Hi @mmkal, thanks for the issue!

The `no-unreachable` does not fix code. That has to be another rule or another tool that deletes code.

**Comment by mmkal** [comment]
Ah, you are right. I just tried suppressing it and vscode is still deleting my precious work!
