### ISSUE TITLE
Allow valid/invalid cases in RuleTester to contain a syntax tree instead of example code

### ISSUE THREAD

**Issue by mozfreddyb** [eslint/eslint#14776]
**The version of ESLint you are using.**
v7.30.0

**The problem you want to solve.**
Background: I am maintaining an eslint plugin that tries to detect DOM-based XSS.
This plugin is very specific to Mozilla and uses our own set of trades-off in terms of false positives and false negatives. We don't claim perfect detection and there are some obvious gaps that one has to accept when dealing with a dynamically typed, multi-paradigm language. However, this plugin has gained adoption outside of Mozilla and other projects are using it as well (Microsoft Edge, Wire IM, Kibana, ..)

Precise use-case: We have some logic that tries to be exhaustive in terms of Expressions we can analyze. In particular, it is complaining for expressions that are not within a list of allowed expressions. This helps maintain the security guarantees we provide in our plugin and acts as a forcing function to adopt new JavaScript Syntax in lock-step with the tooling that is used to check it (here's an example for the [nullish assignment operator](https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/147)).
Currently, we can not write a test for this scenario, becaus we cannot write code containing a "FantasyExpression".
It would be really nice to test this behavior using the `RuleTester` by providing an `ast` instead of a `code` attribute.

**Your take on the correct solution to problem.**
Instead of requiring a `code` sample in RuleTester only require it optionally and allow `ast` instead.

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by mdjermanovic** [comment]
Hi @mozfreddyb, thanks for the issue!

If I correctly understand the request, this use case is already (indirectly) supported. 

You can make a custom parser that returns a fixed AST, and specify it as `parser: "/absolute/path/to/module"` in the test case. We're doing that sometimes to test changes in rules to better work with unexpected syntax coming from third-party parsers.

Example: https://github.com/eslint/eslint/commit/fed20bb039cf9f53adfcf93e467f418c5e958f45

`code` is still required to build the `SourceCode` object, but if your rules use only AST you can just set `code: ""`.

Would that work for you?

We could consider adding the `ast` attribute and wrapping it into `{ parse: () => ast }`, but it doesn't seem much different assuming that the ast object will be stored and loaded from a separate file.

**Comment by mozfreddyb** [comment]
Awesome, that's exactly what I needed! However, it took me a time to get the right sort of AST into my custom parser. Simple examples derived from ast-explorer.net were lacking object properties that eslint required (comments, tokens, errors, ...) and the location data needed to be in a `loc` object instead of direct `start`, `end` keys.

I'd be interested if someone could give a suggestion on how to easiest produce a conformant ast and what you have been using instead of ast-explorer.


As for me, this issue can be closed.
Thank you! :star_struck:

**Comment by mdjermanovic** [comment]
Glad it helped!

I'm using the parser directly, e.g.:

```js
const ts = require("@typescript-eslint/parser");

const code = "foo";
const ast = ts.parse(code, {
    tokens: true,
    comment: true,
    range: true,
    loc: true
});

// then stringify, save to file, etc.
```

astexplorer.net should do the same, but you'll need to enable the options that are not set by default (loc, comment, and tokens): 

![image](https://user-images.githubusercontent.com/44349756/124916417-f165ea80-dff2-11eb-8c9d-e1898048faf1.png)

![image](https://user-images.githubusercontent.com/44349756/124916796-5d485300-dff3-11eb-9834-7e3c290577c5.png)

**Comment by mozfreddyb** [comment]
Thanks! Very helpful. For now, we'll solve this in our plugin without an eslint change, but happy to continue in this if you end up seeing this as useful for eslint itself.

**Comment by nzakas** [comment]
I don’t think we are going to move forward with a change here, as there are better options available.
