### ISSUE TITLE
Selector `Property > .key` can't match key in `const {a = 1} = b;`

### ISSUE THREAD

**Issue by fisker** [eslint/eslint#14799]
**Tell us about your environment**

* **ESLint Version:** v7.30.0
* **Node Version:** v16.4.2
* **npm Version:** v7.9.0
* **Operating System:** win32 10.0.19043

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

The default parser.

The issue template doesn't fit, so I removed these sections.

I was making an eslint plugin, for this code

```js
const {a = 1} = b;
```

I should be able to use `Property > .key` to select the key, but ESLint won't match. 

I think this happens because we use the same reference for `key` and `value.left`, so they both have the `AssignmentPattern` as parent. For this reason, I don't think this is an issue by `espree` or `acorn`.

This happens to assignment too.

```js
({a = 1} = b);
```

**Comment by nzakas** [comment]
> I think this happens because we use the same reference for key and value.left, so they both have the AssignmentPattern as parent.

Where are you seeing this?

And can you provide a minimal repro case so we can see the behavior?

Note the query engine is [esquery](https://github.com/estools/esquery), so it could be an issue there.

**Comment by mdjermanovic** [comment]
> I think this happens because we use the same reference for `key` and `value.left`, so they both have the `AssignmentPattern` as parent. For this reason, I don't think this is an issue by `espree` or `acorn`.

This is a bug in Acorn 7 / Espree 7, nodes in a tree shouldn't have multiple parents. The bug is fixed in Acorn 8 / Espree 8 (relevant test is [here](https://github.com/eslint/espree/blob/bf57077e02dd61f82ab533d6bb0c160e2dfe40b8/tests/lib/parse.js#L229)).

Once we switch to Espree 8.0.0, we could add a test with `Property > .key` selector to confirm that it works well in ESLint.

**Comment by nzakas** [comment]
> Once we switch to Espree 8.0.0, we could add a test with Property > .key selector to confirm that it works well in ESLint.

Can you try by using Espree 8 locally and let us know the result?

**Comment by fisker** [comment]
> This is a bug in Acorn 7 / Espree 7, nodes in a tree shouldn't have multiple parents. The bug is fixed in Acorn 8 / Espree 8 (relevant test is here).

Thank you, I didn't know that.

> Can you try by using Espree 8 locally and let us know the result?

Confirmed, updating to Espree 8 fixes this.

---

Question: ETA for switch to Espree 8.0.0? Do we need workaround in ESLint before that?

**Comment by nzakas** [comment]
@fisker thanks for the followup. The Espree upgrade will happen with the ESLint v8.0.0 release, which we hope we will have a preview release of in a couple weeks.

We can’t upgrade Espree in ESLint v7.x line due to breaking changes.
