### ISSUE TITLE
Add `ignoreDeclarations` option to `max-len`

### ISSUE THREAD

**Issue by 4086606** [eslint/eslint#14797]
**What rule do you want to change?** `max-len`

https://github.com/eslint/eslint/blob/b77b4202bd1d5d1306f6f645e88d7a41a51715db/lib/rules/max-len.js#L66

**Does this change cause the rule to produce more or fewer warnings?** ?Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

Syntax: `["error", { "code": 120, "ignoreDeclarations": true }]`

**Please provide some example code that this change will affect:**

```ts
function editHandler(edit: vscode.TextEditorEdit, content: string, exists: boolean, textDoc: vscode.TextDocument): void {
}
```

**What does the rule currently do for this code?**

Throw an error because the line length for row 1 is 123 characters.

**What will the rule do after it's changed?**

Permit line length of >120 for the function declaration. Also apply to classes, functions, TypeScript interfaces, namespaces... anything followed by `{ ... }`.

**Are you willing to submit a pull request to implement this change?**

As for how I could do this, I haven't the foggiest clue at all.

**Comment by mdjermanovic** [comment]
Hi @4086606, thanks for the issue!

Stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates) so we won't be adding any more options to the `max-len` rule, but you can use the existing [ignorePattern](https://eslint.org/docs/rules/max-len#ignorepattern) option to ignore lines that match the specified regular expression.

> Permit line length of >120 for the function declaration. Also apply to classes, functions, TypeScript interfaces, namespaces... anything followed by `{ ... }`.

You can specify pattern `\{$` (`"\\{$"`) to ignore all lines that end with `{`:

```js
/* eslint max-len: ["error", {
	code: 30,
    ignorePattern: "\\{$"
}] */

// ok
function someLongName(and, many, parameters) {
}

// ok
class AnotherLongName extends SomeBaseClass {
}

// not ok
someFunction(many, many, many, arguments);
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG1heC1sZW46IFtcImVycm9yXCIsIHtcblx0Y29kZTogMzAsXG4gICAgaWdub3JlUGF0dGVybjogXCJcXFxceyRcIlxufV0gKi9cblxuLy8gb2tcbmZ1bmN0aW9uIHNvbWVMb25nTmFtZShhbmQsIG1hbnksIHBhcmFtZXRlcnMpIHtcbn1cblxuLy8gb2tcbmNsYXNzIEFub3RoZXJMb25nTmFtZSBleHRlbmRzIFNvbWVCYXNlQ2xhc3Mge1xufVxuXG4vLyBub3Qgb2tcbnNvbWVGdW5jdGlvbihtYW55LCBtYW55LCBtYW55LCBhcmd1bWVudHMpO1xuXG5cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by 4086606** [comment]
Thanks for the code sample, it's helped immensely!
