### ISSUE TITLE
 @click="delete(item.id)" will be @click="deleteitem.id"  in vue2

### ISSUE THREAD

**Issue by chenguzhen87** [eslint/eslint#14815]
1、ctrl+s in vscode 
![image](https://user-images.githubusercontent.com/28331609/126292946-1174e09f-f014-44c2-8569-03c23c663532.png)

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by nzakas** [comment]
No response so closing.
