### ISSUE TITLE
can't install my project with 7.29.0 in dependencies

### ISSUE THREAD

**Issue by jeffory-orrok** [eslint/eslint#14817]
Trying to install a package with eslint 7.29.0 as a dependency results in an error for the incorrect version of @eslint/eslintrc

> npm install
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @eslint/eslintrc@^0.4.3.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/jeff/.npm/_logs/2021-07-20T13_52_30_066Z-debug.log

Environment:

> node -v ; npm -v
> v14.15.0
> 7.18.1

Sample project and debug log attached
[foo.zip](https://github.com/eslint/eslint/files/6848957/foo.zip)
[debug_log.zip](https://github.com/eslint/eslint/files/6848962/debug_log.zip)

**Comment by nzakas** [comment]
Please reformat your report using [the correct template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) and we will take a look. Thanks.

**Comment by jeffory-orrok** [comment]
Tell us about your environment

ESLint Version: 7.29.0
Node Version: 14.15.0
npm Version: 7.18.1
Operating System: MacOS Big Sur 11.4
What parser (default, @babel/eslint-parser, @typescript-eslint/parser, etc.) are you using? not using a parser

Please show your full configuration:

Configuration not applicable - this is an install issue not a runtime issue

What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.
I tried to install my project's package that has eslint as a dependency
command: cd package; npm install

What did you expect to happen?  The package would be installed

What actually happened? Please copy-paste the actual, raw output from ESLint.

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @eslint/eslintrc@^0.4.3.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/jeff/.npm/_logs/2021-07-20T13_52_30_066Z-debug.log


Steps to reproduce this issue:
cd package
rm -rf node_modules
npm install

Are you willing to submit a pull request to fix this bug? no

**Comment by nzakas** [comment]
Thanks. Can you try updating to the latest ESLint? You’re a minor version behind.

**Comment by nzakas** [comment]
No response, so closing.
