### ISSUE TITLE
Anyway to suppress this warning?

### ISSUE THREAD

**Issue by chelsumz007** [eslint/eslint#14820]
![image](https://user-images.githubusercontent.com/52992133/126465752-58e7115c-5e94-4857-a351-06a1f901a156.png)

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Also, It looks like this warning is not coming from ESLint

**Comment by chelsumz007** [comment]
Not a bug, but a question.. this is a warning message that I'm getting when I run lint for a project that's already running ESLint

**Comment by nzakas** [comment]
This error message is coming from TSLint, not ESLint.
