### ISSUE TITLE
eslint-env browser: Incorrectly warns about valid DOM Core + HTML Interfaces

### ISSUE THREAD

**Issue by iskitz** [eslint/eslint#1483]
| ...                   | ...
|-------------------|--------
|__version__   | 0.9.2
|__config__     | [/\* eslint-env browser \*/](http://eslint.org/docs/configuring/)
|__code__       | [DOMException.NOT_FOUND_ERR](http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-17189187)
|__expected__| No warning
|__observed__| `[no-undef] 'DOMException' is not defined.`

ESLint throws the warning above for code referencing any of these valid [DOM](http://www.w3.org/DOM/DOMTR) interfaces even when the environment is explicitly set to `browser`.

* [DOM 1](http://www.w3.org/TR/REC-DOM-Level-1/): [Core](http://www.w3.org/TR/REC-DOM-Level-1/level-one-core.html#ID-BBACDC08) + [HTML](http://www.w3.org/TR/REC-DOM-Level-1/level-one-html.html)
* [DOM 2](http://www.w3.org/DOM/DOMTR#dom2): [Core](http://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-BBACDC08) + [HTML](http://www.w3.org/TR/DOM-Level-2-HTML/html.html)
* [DOM 3: Core](http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-BBACDC08/)

**Comment by nzakas** [comment]
We have switched to use the globals module (https://github.com/sindresorhus/globals) for managing this. Further issues should be filed there.

**Comment by nzakas** [comment]
Looks like using the globals module covers this issue.
