### ISSUE TITLE
Conflict with prettier

### ISSUE THREAD

**Issue by strrife** [eslint/eslint#14858]
**Tell us about your environment**

* **ESLint Version:** 7.31.0 (was reproducible on 7.29.0 too)
* **Node Version:** v14.17.2
* **npm Version:** 6.14.13

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** babel-eslint@10.1.0

**Please show your full configuration:**

<details>
<summary>package.json</summary>

```js
{
  "scripts": {
    "lint-fix": "eslint --fix problem.js"
  },
  "devDependencies": {
    "eslint": "^7.31.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.3.2",
    "prettier-eslint": "^13.0.0"
  },
  "dependencies": {
    "babel-eslint": "^10.1.0"
  }
}


```

</details>

<details>
<summary>Configuration</summary>

```js
module.exports = {
  plugins: ['prettier'],
  extends: [
    'eslint:recommended',
    "plugin:prettier/recommended"
  ],
  parser: 'babel-eslint'
};

```
</details>

<details>
<summary>.prettierrc</summary>

```json
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "semi": true,
  "printWidth": 120,
  "tabWidth": 2
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I'm trying to run `eslint --fix problem.js` to fix following code:

```js
if (true) {
  const isReproducible = !!1 ?
    ['apple', 'banana', 'orange', 'pineapple', 'apple', 'banana', 'orange', 'pineapple']
    : ['apple', 'banana', 'orange', 'pineapple'];
}


```

**What did you expect to happen?** 

I expected `eslint --fix` to not add syntax errors to the file

**What actually happened? Please include the actual, raw output from ESLint.**

```js
if (true) {
  const isReproducible = 1 ?
    ? ['apple', 'banana', 'orange', 'pineapple', 'apple', 'banana', 'orange', 'pineapple']
    : ['apple', 'banana', 'orange', 'pineapple'];
}
```

<details>
<summary>eslint --fix output</summary>

```

/home/strrife/Projects/eslint-repro/problem.js
  3:5  error  Parsing error: Unexpected token

  1 | if (true) {
  2 |   const isReproducible = 1 ?
> 3 |     ? ['apple', 'banana', 'orange', 'pineapple', 'apple', 'banana', 'orange', 'pineapple']
    |     ^
  4 |     : ['apple', 'banana', 'orange', 'pineapple'];
  5 | }
  6 | 

✖ 1 problem (1 error, 0 warnings)

```

</details>

It looks like the `no-extra-boolean-cast` somehow conflicts with the prettier config. I have experienced similar issues previously when formatting rules were conflicting with prettier. Disablign them made sense, but it is not the case here since prettier would not be fixing `no-extra-boolean-cast`.

Fixing the file manually and running esling --fix again works just fine.

Also, fixing the following piece of code:

```js
const isReproducible = !!1 ?
  ['apple', 'banana', 'orange', 'pineapple', 'apple', 'banana', 'orange', 'pineapple']
  : ['apple', 'banana', 'orange', 'pineapple'];
```

does not create syntax errors.

Thanks, best regards, Alexander

**Comment by nzakas** [comment]
Can you disable prettier and see if you get the same result?

**Comment by fregante** [comment]
Refer to https://prettier.io/docs/en/integrating-with-linters.html
And more specifically: https://github.com/prettier/eslint-config-prettier

In short, you have to add a `prettier` config to eslint to disable conflicting rules in ESLint

**Comment by strrife** [comment]
@nzakas apologies for the delayed feedback, it works fine without prettier. And it works fine with `no-extra-boolean-cast` disabled.

**Comment by nzakas** [comment]
Okay, in that case, this seems like it's most likely a problem with Prettier and not with ESLint. I can't reproduce introducing the syntax error just with ESLint.

**Comment by strrife** [comment]
If I understand correctly, in this context prettier acts just another eslint plugin, and it looks like 2 plugins make changes in the code ignoring each other

**Comment by nzakas** [comment]
Rules don’t know what other rules are doing. We can’t possibly guarantee that every rule created by a third party will work correctly with core ESLint rules. I’d suggest following up with the prettier folks.

**Comment by mdjermanovic** [comment]
This looks like a known bug in `eslint-plugin-prettier`. ESLint prevents conflicts by not applying overlapping fixes, but each individual fix should be complete (should produce valid code after applying) and thus independent of other fixes, which isn't always the case with fixes that `eslint-plugin-prettier` provides: https://github.com/prettier/eslint-plugin-prettier/issues/65#issuecomment-339224115.
