### ISSUE TITLE
Update rules to support ES2022 class fields

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#14857]
**What is the name of the syntax to implement?**

Class fields

**Please provide the TC39 URL for the syntax proposal:**

- [Private methods and getter/setters for JavaScript classes](https://github.com/tc39/proposal-private-methods)
- [Class field declarations for JavaScript](https://github.com/tc39/proposal-class-fields)
- [Static class features](https://github.com/tc39/proposal-static-class-features)

## Implementation Checklist

This issue tracks rules that need to be updated to support ES2022 class fields. Please add to this list if there are any additional rules that need to be updated. I've linked to any comments on the original PR for easier reference. Some rule updates may have been finished in #14591, in which case we can confirm the updates are sufficient and check off the rule here.

- [x] `camelcase` https://github.com/eslint/eslint/pull/14966
	- https://github.com/eslint/eslint/pull/14591#discussion_r676212379
- [x] `class-methods-use-this` https://github.com/eslint/eslint/pull/15018
	- https://github.com/eslint/eslint/pull/14591#discussion_r656613541
	- https://github.com/eslint/eslint/pull/14591#issuecomment-866383434
	- https://github.com/eslint/eslint/pull/14591#issuecomment-877815299
- [x] `complexity` https://github.com/eslint/eslint/pull/14957
	- https://github.com/eslint/eslint/pull/14591#issuecomment-877346829
- [x] `computed-property-spacing`
- [x] `dot-notation` https://github.com/eslint/eslint/pull/14898
	- https://github.com/eslint/eslint/pull/14591#issuecomment-866334741
- [x] `func-name-matching` https://github.com/eslint/eslint/pull/14964
	- https://github.com/eslint/eslint/pull/14591#issuecomment-877324627
- [x] `func-names` https://github.com/eslint/eslint/pull/14908
	- https://github.com/eslint/eslint/pull/14591#issuecomment-875789724
- [x] `id-denylist`: https://github.com/eslint/eslint/pull/14591
- [x] `id-length`: https://github.com/eslint/eslint/pull/14591
- [x] `id-match`: https://github.com/eslint/eslint/pull/14591
- [x] `indent`
- [x] `keyword-spacing` https://github.com/eslint/eslint/pull/14946
	- https://github.com/eslint/eslint/pull/14591#pullrequestreview-701480702
- [x] `lines-between-class-members` https://github.com/eslint/eslint/pull/15045
	- https://github.com/eslint/eslint/pull/14591#issuecomment-875113378
- [x] `no-dupe-class-members` https://github.com/eslint/eslint/pull/15005
	- ~https://github.com/eslint/eslint/pull/14591#issuecomment-866757464~
- [x] `no-eval`
- [x] `no-extra-parens` https://github.com/eslint/eslint/pull/14906
	- https://github.com/eslint/eslint/pull/14591#issuecomment-866388926
- [x] `no-extra-semi`
- [x] `no-invalid-this`
- [x] `no-multi-assign` https://github.com/eslint/eslint/pull/14907
	- https://github.com/eslint/eslint/pull/14591#pullrequestreview-701805427
- [x] `no-self-assign`
- [x] `no-undef-init` https://github.com/eslint/eslint/pull/14994
	- https://github.com/eslint/eslint/pull/14591#discussion_r656622751
	- ~https://github.com/eslint/eslint/pull/14591#issuecomment-875764498~
- [x] `no-underscore-dangle`
- [x] `no-unreachable` https://github.com/eslint/eslint/pull/14920
	- https://github.com/eslint/eslint/pull/14591#pullrequestreview-700195963
	- https://github.com/eslint/eslint/pull/14591#issuecomment-874951639
- [x] `no-useless-computed-key` https://github.com/eslint/eslint/pull/14903
	- https://github.com/eslint/eslint/pull/14591#pullrequestreview-690053478
- [x] `operator-linebreak` https://github.com/eslint/eslint/pull/14915
	- https://github.com/eslint/eslint/pull/14591#issuecomment-874963573
- [x] `prefer-destructuring` https://github.com/eslint/eslint/pull/14897
	- https://github.com/eslint/eslint/pull/14591#issuecomment-874891668
- [x] `prefer-exponentiation-operator`
- [x] `quotes`
- [x] `semi-spacing`
- [x] `semi-style`
- [x] `semi` https://github.com/eslint/eslint/pull/14945
	- https://github.com/eslint/eslint/pull/14591#issuecomment-866328829
	- https://github.com/eslint/eslint/pull/14591#issuecomment-874716539
	- https://github.com/eslint/eslint/pull/14591#issuecomment-876244868
- [x] `space-infix-ops`

**Are you willing to submit a pull request to implement this syntax?**

We can work on these in parallel. To avoid redundant effort, please claim a rule when you start working on it.

**Comment by mdjermanovic** [comment]
Working on `prefer-destructuring`

**Comment by mdjermanovic** [comment]
Checked off rules that already look good: `computed-property-spacing`, `no-eval`, `no-extra-semi`, `no-invalid-this`, `quotes`, `semi-spacing`, `semi-style`, `space-infix-ops`.

**Comment by mdjermanovic** [comment]
Working on `dot-notation`.

**Comment by snitin315** [comment]
working on `keyword-spacing`

**Comment by mdjermanovic** [comment]
Working on `no-useless-computed-key`.

**Comment by mdjermanovic** [comment]
Working on `no-extra-parens`.

**Comment by mdjermanovic** [comment]
Working on `no-multi-assign` (it's a documentation-only issue).

**Comment by mdjermanovic** [comment]
Working on no-func-names (it's a documentation-only issue).

**Comment by mdjermanovic** [comment]
Working on `operator-linebreak`.

**Comment by mdjermanovic** [comment]
Working on `no-unreachable`.

**Comment by nzakas** [comment]
Working on `no-underscore-dangle`

**Comment by nzakas** [comment]
Oops, `no-underscore-dangle` is already fixed. Working on `camelcase`.

**Comment by nzakas** [comment]
Actually, I'm not clear on what changes need to be made on `camelcase`, so I'll leave that to @mdjermanovic.

I'll work on `semi`.

**Comment by nzakas** [comment]
Working on `keyword-spacing`

**Comment by mdjermanovic** [comment]
Working on `complexity`

**Comment by mdjermanovic** [comment]
Working on `func-name-matching`

**Comment by mdjermanovic** [comment]
Working on `camelcase`

**Comment by mdjermanovic** [comment]
Working on `no-dupe-class-members`

**Comment by btmills** [comment]
I could make a case either way for `no-undef-init` applying to class fields with an option or as a separate rule, so I’ll defer to consensus in favor of leaving it for a separate rule.

**Comment by mdjermanovic** [comment]
Working on `no-undef-init`

**Comment by mdjermanovic** [comment]
https://github.com/eslint/eslint/pull/14994 fixes https://github.com/eslint/eslint/pull/14591#discussion_r656622751 as agreed (`no-undef-init` should not apply to class fields), so https://github.com/eslint/eslint/pull/14591#issuecomment-875764498 no longer applies.

**Comment by yeonjuan** [comment]
Working on `class-methods-use-this`

**Comment by mdjermanovic** [comment]
Prepared https://github.com/eslint/eslint/pull/15005 to update documentation for `no-dupe-class-members`.

Regarding https://github.com/eslint/eslint/pull/14591#issuecomment-866757464, we discussed that question in https://github.com/eslint/eslint/pull/14979 and decided to not make any changes for now.

**Comment by mdjermanovic** [comment]
Working on `lines-between-class-members`

**Comment by mdjermanovic** [comment]
All planned tasks are done :tada: 

I made a quick pass through all rules to check if anything should be additionally updated because of the new code path and new scope for class field initializers, and I didn't see any problems.

If anyone finds more rules that need to be updated, please open new issues.
