### ISSUE TITLE
Write "Migrating to v8.0.0" guide

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#14856]
**The version of ESLint you are using.**

v7.31.0

**The problem you want to solve.**

I'd like to know how to migrate to v8.0.0.

**Your take on the correct solution to problem.**

Write a "Migrating to v8.0.0" guide as we've done in the past: https://eslint.org/docs/user-guide/migrating-to-7.0.0

**Are you willing to submit a pull request to implement this change?**

If someone else doesn't get to it first.

**Comment by nzakas** [comment]
Starting work on this.
