### ISSUE TITLE
Feature request/discussion: add color to codeframe formatter

### ISSUE THREAD

**Issue by elektronik2k5** [eslint/eslint#14870]
Hello and thanks for writing and maintaining eslint!

I was wondering whether there's any reason why the `codeframe` formatter output is always monochromatic. Is there any reason we shouldn't enable syntax highlighting?

**The version of ESLint you are using.**
7.31.0

**The problem you want to solve.**
`codeframe` reporter output is monochromatic even in color capable TTYs.

**Your take on the correct solution to problem.**
Enable colors by setting the `highlightCode` option to `true`. I believe that'll handle everything automatically. If we wanna be more pedantic and consistent then we can respect eslint's `--color`/`--no-color` CLI arguments. 

**Are you willing to submit a pull request to implement this change?**
Yes, definitely! :)

Tagging original contributor @vitorbal for historical context.

**Comment by nzakas** [comment]
The codeframe formatter is  [being removed in v8.0.0](https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#removing-the-codeframe-and-table-formatters), so we aren't making any further changes to it.
