### ISSUE TITLE
To add `cache` option to `ci.yml` workflow 

### ISSUE THREAD

**Issue by oscard0m** [eslint/eslint#14875]
**The version of ESLint you are using.**
Not important for this change

**The problem you want to solve.**
To improve `npm install` times for `ci.yml`

**Your take on the correct solution to problem.**
`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

**Are you willing to submit a pull request to implement this change?**
https://github.com/eslint/eslint/pull/14874

**Comment by snitin315** [comment]
There was a similar attempt before in https://github.com/eslint/eslint/pull/14843,  It looks like this won't work as we don't have any lock file present [as described in README](https://github.com/eslint/eslint#why-doesnt-eslint-lock-dependency-versions)

**Comment by oscard0m** [comment]
> There was a similar attempt before in #14843, It looks like this won't work as we don't have any lock file present [as described in README](https://github.com/eslint/eslint#why-doesnt-eslint-lock-dependency-versions)

I guess it can be discussed a different way to cache somehow. `actions/cache` + cachinng `node_modules` is not recommended for instance https://github.com/actions/cache/blob/main/examples.md#node---npm

**Comment by snitin315** [comment]
I did some research and was unable to find a way to cache node.js modules without a `key`. Hence, I am closing this issue for now.
