### ISSUE TITLE
Allow DOMException to be thrown in browser env

### ISSUE THREAD

**Issue by PaperStrike** [eslint/eslint#14880]
**What rule do you want to change?**
[`no-throw-literal`](https://github.com/eslint/eslint/blob/master/docs/rules/no-throw-literal.md)

**Does this change cause the rule to produce more or fewer warnings?**
Fewer warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New default behaviour.

> Any web platform API using promises to represent operations that can be aborted must adhere to the following:
> * ...
> * Convey that the operation got aborted by rejecting the promise with an **"`AbortError`" `DOMException`**.
> * ...
>
> —— [Using `AbortController` and `AbortSignal` objects in APIs | DOM Standard](https://dom.spec.whatwg.org/#abortcontroller-api-integration)

It seems not always to be a good practice to only throw `Error` in browser environment, as it is "encouraged" to write a function like:

```js
const abortableFunc = async ({ signal }) => {
  if (signal.aborted) {
    throw new DOMException('Aborted', 'AbortError');
  }
  // ...
}
```

 I'm not sure whether there are more similar APIs other than `DOMException`.)

**Please provide some example code that this change will affect:**

Currently, ["due to the limits of static analysis"](https://github.com/eslint/eslint/blob/master/docs/rules/no-throw-literal.md#known-limitations), code below passes the vanilla ESLint.

Howerver, with parsers like `@typescript-eslint/parser` that have fully implemented this rule, it gets different results.

```js
throw new DOMException('Aborted', 'AbortError');
```

**What does the rule currently do for this code?**
Fail to pass.

**What will the rule do after it's changed?**
Pass if "browser" of "env" config evaluates to `true`.

**Are you willing to submit a pull request to implement this change?**
No. Thanks in advance.

**Comment by nzakas** [comment]
`no-throw-literal` doesn't prevent you from using `throw DOMException`. If you're getting "DOMException is not defined, then you need to enable the `browser` environment or else manually define the DOMException global.

**Comment by PaperStrike** [comment]
Yes, "due to the limits of static analysis". But unfortunately, with `@typescript/parser`, I'm getting:

![Expected an error object to be thrown when throwing a DOMException](https://user-images.githubusercontent.com/22674396/128436483-6dfddca2-be15-47e1-bf08-32d03d0b7e28.png)

I preferred not to open an issue there in [`typescript-eslint/no-throw-literal`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-throw-literal.md), as it (more precisely, its design) was "taken from" your `no-throw-literal`. This seems more like a design problem, if you change the description about `no-throw-literal`, I think all the other parsers will follow up.

**Comment by nzakas** [comment]
Ah ok. This isn’t a behavior that is found in the core rule as we don’t do any type checking on what is thrown. You’ll need to talk to the typescript-eslint folks about it.
