### ISSUE TITLE
TypeError: __webpack_require__(...).posix is undefined

### ISSUE THREAD

**Issue by nik-swarmagency** [eslint/eslint#14885]
**Tell us about your environment**

* **ESLint Version:**
* eslint
* 7.32.0
* https://www.npmjs.com/package/eslint
* **Node Version:**
* 14.6.1 (lts)
* **npm Version:**
* 6.14.12
* **Operating System:** 
* ubuntu 20.04

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
When using latest react from create-react-app:
import ESLint from 'eslint';
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import ESLint from 'eslint';
```

```bash
npm run start
```

**What did you expect to happen?**
load module into node.js without issues

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
TypeError: __webpack_require__(...).posix is undefined
When using latest react from create-react-app

**Steps to reproduce this issue:**
install react with create-react-app
npm i eslint
import ESLint from 'eslint';

1. 
2. 
3. 

**Are you willing to submit a pull request to fix this bug?**
no idea how to solve this, I assume it's because this module doesn't have support for posix systems?
![image](https://user-images.githubusercontent.com/85505858/128436171-f08c8649-4595-4900-9a80-d21c33278076.png)

**Comment by snitin315** [comment]
Strange, I tried it locally, the warning is coming from `glob-parent` node-module. Updating `glob-parent` in eslint might fix it. I will take a look.

**Comment by snitin315** [comment]
This issue isn't related to ESLint, just add `require(path).posix.dirname` in the react app instead of `import ESLint from 'eslint';` and you will end up with the same error.

You should probably report it to `webpack` or `create-react-app`
