### ISSUE TITLE
Ability to configure cache location and strategy with environment variables

### ISSUE THREAD

**Issue by 2tunnels** [eslint/eslint#14894]
I'm configuring CI in one project that uses ESLint, and I discovered that cache could be configured only with command line arguments. It seems like environment variables are more flexible.
For example, I can use the same commands that people are already using (from `package.json` or `Makefile`) but change some behavior for different environments (CI, local development, deployment, etc.).
Is it possible to add environment variable support?

**Comment by nzakas** [comment]
Please update your issue to use one of our [issue templates](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/) and we will take a look. Thanks.

**Comment by nzakas** [comment]
No response so closing.
