### ISSUE TITLE
Expanding environments

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#14904]
**The version of ESLint you are using.**

7.32.0

**The problem you want to solve.**

It would be convenient to have "cypress" available as `env`  for setting predefined globals. (I'd also like to submit a PR for chai as well if there is openness to it.)

**Your take on the correct solution to problem.**

I think this is a popular enough project to merit its inclusion so things are more elegant and easy for users.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by mdjermanovic** [comment]
The list of built-in environments is frozen (ref https://github.com/sindresorhus/globals/issues/82). Additional environments can be created in plugins.

Also, the new config system will remove the concept of environments: https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification#applying-an-environment

**Comment by brettz9** [comment]
Thought the freezing might have been possible, but as I didn't find mention of it, figured these would be good ones to have. Thanks!
