### ISSUE TITLE
Update: Replace "Unexpected x." error messages with helpful error messages

### ISSUE THREAD

**Issue by paulsmithkc** [eslint/eslint#14914]
I've submitted a few Pull Requests related to fixing rules one by one, trying to keep the changes minimal. But I've encountered some oddly fervent opposition. So I'm promoting this to an issue to try and encourage some productive discussion.

## Background

For context, I work as a computer science professor teaching Freshman/Sophomore level college courses. Some of which involve browser-side JavaScript and Node.js web apps. I want my students to learn better coding habits as they work through coding assignments, and get feedback sooner on how to improve.

Linters (like eslint) give me a way to automate some of that feedback process. Meaning that they can get feedback sooner, and I spend less time marking them up for the same problems over and over. Thus I am trying to integrate eslint into my teaching and grading processes.

When everything is working well, the error messages from eslint will appear in a few different places:

1. Directly in their IDE, using the eslint extension for VS Code.
2. On GitHub, via a GitHub Actions workflow that runs on every push.
3. In a grade summary email, that is initiated via webhook.

## Issues with the current system

However, in order for all of this to be useful. The error messages need to actually explain a) what is wrong b) how to fix it. Without both of these in place, students don't have the opportunity to improve their coding habits.

Currently, a lot of the error messages that eslint emits, and my students see, look like this:
• "Unexpected alert."
• "Unexpected prompt."
• "Unexpected console."
• "Unexpected isNaN."
• etc.

Unfortunately these error messages create several issues:

1. These error messages all effectively say "read the docs"
2. They are misleading, as they seem to indicate a syntax error, or a parse error with one of the tools. Which is not actually the case.
3. They are not easy to Google. There is not enough verbage for them to be directed to the eslint docs and most of the results that come up are not relevant.
4. If you do manage to find the docs. The actual information therein is just 1-2 sentences about what the problem might be.
5. The docs are focused on explaining how to configure the rules, not on how to fix the code. So most of the information isn't relevant.
6. The docs assume that you have configured eslint yourself, or know how to do so. They are not conducive to an absolute beginner.
7. The error message doesn't tell you what is wrong, what caused it, or how to fix it.

These error messages do accomplish the goal of being "un-opinionated." But they are horrible in terms providing actual value and insight. However, the process of installing and configuring a linter is a very opinionated process, and I want those opinions to be communicated in the error messages. I hope that I am not alone in this.

There are several rules were a good one-sentence error message would avoid the trip to read the docs, allow students to easily comprehend and fix the issue, and keep them coding along.

## Pushback

"Just read the docs." seems to be the main pushback to this I'm seeing, but that poses several hurdles for junior developers:
1. They don't know what tool is generating the error. They have determine it is eslint, to know what docs to look in.
2. They don't know what rule caused the error. Since many rules produce the same/similar error messages, this is not easy to determine unless you know where to look, and what to look for. (And the eslint plugin for vscode actually greys out the rule name, making it less obvious.)
3. They assume that red/yellow underlines mean that it is a syntax error. So they often don't look very far.
4. When multiple errors are present on the same line, it is hard to see all of them and determine the root cause. (Note that junior devs have a higher error density, than senior devs.)

## Solutions

So my thoughts on fixing this situation are that I see a few possible ways forward:

1. Update the default error messages to be more helpful (hopefully helping everybody)
2. Implementing options to override the messages with custom opinionated error messages (allowing for more customization for those that want to be more opinionated)
3. Fork eslint and make the changes that I need.
4. Drop eslint and switch to a different JS linter that is less opposed to change.
5. Dropping js linters entirely and revert to grading styling / best practices manually. (Losing out on the quick feedback and equal treatment, that I'm looking for.)

I'm really hoping that options 1 or 2 are viable. To me, this feels to me like a glaring problem, with an easy fix.

I'm more than happy to submit updated wording / code changes to support this. But it feels like everything I submit gets vetod.

## Related Pull Requests

#14762 #14763 #14779

**Comment by nzakas** [comment]
As I’ve explained on various PRs, while I understand your point of view, I fundamentally disagree that these error messages should be changed in the ways you’re suggesting. We’ve used the same basic format for 8 years now, which is to specifically state what was expected and what was not. 

* Rules beginning with no- always have “Unexpected X” and May optionally say “expected Y” if that is known.
* Other rules say “Expected X” and May or may not contain further details.

The error messages are intentionally concise and we always display the rule ID with the intention that people who want more information can google the rule ID, which is a lot more unique than any error message can be.

I don’t want to move to a model where error messages contain the level of detail you want. That clutters the console unnecessarily and makes it the more verbose the message, the less likely people are to correctly interpret it.

As I’ve also mentioned in other PRs, I think some of your suggestions for improving error messages were good, and we merged them, but a lot are just overly verbose and don’t fit out style.

**Comment by lydell** [comment]
`@typescript-eslint/eslint-plugin` has really nice error messages, in my opinion. For example, the [ban-types](https://github.com/typescript-eslint/typescript-eslint/blob/v4.29.0/packages/eslint-plugin/docs/rules/ban-types.md) rule. They could have gone with “Unexpected {} type” but instead have this:

```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
```

Getting that when hovering the over `{}` in my editor is super helpful!

**Comment by nzakas** [comment]
Yep, all plug-ins are allowed to define their own error message format and some have chosen to use longer formats. For the core rules, we prefer to keep messages concise and describing the expectations that were met or unmet.

so the message is about the expectation, and the documentation is about the reasons behind the expectation.

**Comment by aladdin-add** [comment]
you can use the [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) to create custom rules based on the core rules.

**Comment by paulsmithkc** [comment]
@nzakas This doesn't answer my question as to why these aren't even configurable.

> 2. Implementing options to override the messages with custom opinionated error messages (allowing for more customization for those that want to be more opinionated)

If I could at least configure these messages to be different via the config that would suffice. Currently none of these messages can even be overridden.

#14763 got rejected not because it was changing a default error message. But because you simply saw it as "not needed."

**Comment by paulsmithkc** [comment]
@aladdin-add I'd prefer to override the messages for core rules, without recreating all of them.

**Comment by nzakas** [comment]
@paulsmithkc the reason you can’t override messages is because there’s no way for ESLint to know how each rule implements messaging. Individual rules can allow that, such as no-restricted-syntax, but there’s no way for ESLint to just use a separate message for any rule. 

At this point I’m not clear on the problem you’re attempting to solve, as the default messaging and rule ID should suffice for most use cases.

If you really feel that it’s important for your project to have alternate messages from the defaults, the easiest thing would be to create a custom formatter so you can output whatever you want.

**Comment by mdjermanovic** [comment]
I'm not in favor of any verbose error messages that would just replicate the content from the documentation since we already have online documentation which is more detailed than an error message could be.

All core rules and most plugins provide [meta.docs.url](https://github.com/eslint/eslint/blob/660f075386d0b700faf1a1a94cde9d51899738a3/lib/rules/no-undef.js#L33) property. Integrations and formatters can use this property to print the documentation URL or even provide a clickable link.

Here's how it looks in VS Code:

![image](https://user-images.githubusercontent.com/44349756/132959436-1e136d8c-db8a-45e8-ae8d-db79cca07794.png)

When user clicks on `no-undef`, it opens https://eslint.org/docs/rules/no-undef in a browser.

**Comment by nzakas** [comment]
We aren’t going to be moving forward with any large-scale change to how we formulate our rule error messages, so I’m closing this issue.

If there are tweaks we can make to make the messages more helpful, please feel free to send a PR. Thanks.
