### ISSUE TITLE
Requesting underscore demarcation for no-unused-vars

### ISSUE THREAD

**Issue by StoneCypher** [eslint/eslint#1494]
The rule `no-unused-vars` is very useful.  However there are times at which its current structure is at odds with other peoples' APIs.

Consider the case of a page error handler to `express.js`, whose signature is roughly

``` javascript
app.use(function(err, req, res, next) { ... });
```

If you want to write a 404 handler that looks at what the actual `err`or was, and sets things on the `res`ponse, but doesn't care what the `req`uest is (say, maybe you're making an imgur clone,) then you're out of luck: there is no way to write that which won't ring `eslint`'s bell.

Could `eslint` be extended to do what `erlang` does?  Prefixing a name with an underscore in `erlang` suppresses non-use detection.  Then we could just name them `_req` and `_next` and the problem goes away.

**Comment by zckrs** [comment]
Since 2014 the rule `no-unused-vars` have news options.

You can use http://eslint.org/docs/rules/no-unused-vars#argsignorepattern

Example in `package.json`

```
"eslintConfig": {
    "rules": {
      "no-unused-vars": ["error", { "argsIgnorePattern": "next" }]
    }
  }
```

**Comment by StoneCypher** [comment]
cheers, thanks :smile:
