### ISSUE TITLE
Add a configuration to ignore files/folders from .gitignore

### ISSUE THREAD

**Issue by GuyLescalier** [eslint/eslint#14944]
**The version of ESLint you are using.**
7.32.0

**The problem you want to solve.**
Ignore files and folders listed in `.gitignore`

**Your take on the correct solution to problem.**
The possibility to use the `.gitignore` by default has been discussed and discarded for good reasons (https://github.com/eslint/eslint/issues/5848).
It can be done with the CLI but not with VS Code (or other IDE) extension.
Or if it can, maybe it should be added to the documentation (https://eslint.org/docs/user-guide/configuring/ignoring-code#using-an-alternate-file).
Anyway I think it would be interesting to have it as an opition in the configuration.
The option:
- would be inactive by default to avoid breaking change.
- could be combined with `ignorePatterns` to add some more files and folders not in `.gitignore`

`{
    "ignoreFromGitignore": true,
    "ignorePatterns": ["folder_not_in_gitignore"],
}`

**Are you willing to submit a pull request to implement this change?**
I haven't looked at the code yet but I can give it a try.

**Comment by nzakas** [comment]
We are no longer making changes to the eslintrc config file format as we will be switching to a new config file format. The new config file format is more extensible, so you’ll be able to manually add whatever ignore patterns you want. Follow https://github.com/eslint/eslint/issues/13481 to keep up to date.
