### ISSUE TITLE
Clarify Linter vs ESLint in node.js api docs

### ISSUE THREAD

**Issue by Brian-Bartels** [eslint/eslint#14953]
**The version of ESLint you are using.**
latest

**The problem you want to solve.**
improve clarity in docs here https://eslint.org/docs/developer-guide/nodejs-api#-eslintlintfilespatterns

**Your take on the correct solution to problem.**
Just add a few sentences clarify the differences between Linter and ESLint objects as they have a lot of overlap

**Are you willing to submit a pull request to implement this change?**
Yes, but I feel like someone with more domain knowledge would be more successful!

**Comment by nzakas** [comment]
Can you explain what you think is missing or should be clarified?

**Comment by Brian-Bartels** [comment]
A bit from each blurb at the tops of the classes could be bubbled up to the top. Also perhaps a sentence on why having access to the file system is useful. For example. I needed some additional ts configurations that I didn't realize. I was trying to use linter. But when I switched to eslint it worked perfectly. Even just a disclaimer at the top "these classes appear similar but have important differences" let me know what you think

**Comment by nzakas** [comment]
We have this blurb under the [ESLint class header](https://eslint.org/docs/developer-guide/nodejs-api):

> The ESLint class is the primary class to use in Node.js applications.
>
> This class depends on the Node.js fs module and the file system, so you cannot use it in browsers. If you want to lint code on browsers, use the Linter class instead.

Do you think changes should be made there to clarify things?

**Comment by Brian-Bartels** [comment]
I suppose that's exactly my point. Unless you read the header for ESLint, and you just read the header for Linter. You'd miss the fact that they are similar

**Comment by nzakas** [comment]
Here’s the description for Linter:

> The Linter object does the actual evaluation of the JavaScript code. It doesn't do any filesystem operations, it simply parses and reports on the code. In particular, the Linter object does not process configuration objects or files. The Linter is a constructor, and you can create a new instance by passing in the options you want to use.

What would you change? Would adding a sentence like, “Unless you are working in the browser, you probably want to use the ESLint class instead,” address your concern?

**Comment by Brian-Bartels** [comment]
I do think that would help

**Comment by Brian-Bartels** [comment]
Well I think I messed up a few things about the title. But I just signed the CLA and hopefully fixed the title #14995

**Comment by nzakas** [comment]
Looks good
