### ISSUE TITLE
Include more operators in `no-mixed-operators`’s default config (by ESLint 8?)

### ISSUE THREAD

**Issue by fregante** [eslint/eslint#14975]
**What rule do you want to change?**

`no-mixed-operators`:

https://github.com/eslint/eslint/blob/c981fb1994cd04914042ced1980aa86b68ba7be9/lib/rules/no-mixed-operators.js#L25-L40

**Does this change cause the rule to produce more or fewer warnings?**

More

**How will the change be implemented? (New option, new default behavior, etc.)?**

New default

**Please provide some example code that this change will affect:**

```js
a || b === c
a ?? b === c
```

**What does the rule currently do for this code?**

No error, unless configured.

**What will the rule do after it's changed?**

Suggest a fix:

```js
a || (b === c)
a ?? (b === c)
```

**Are you willing to submit a pull request to implement this change?**

Possibly

**Comment by nzakas** [comment]
What is it that you are suggesting? What do you want to change that is different than what the rule is currently doing?

**Comment by fregante** [comment]
My two examples show what I'm suggesting: don't mix `??` and other operators, like `===`

I tried looking into the config but I don't quite understand why they're grouped by type. I was able to achieve what I asked by appending `'??'` to every group, but that doesn't seem right:

```js
		'no-mixed-operators': [
			'error',
			{
				// Customize the defaults to force being explicit about use of null-coalescing operator because its precedence
				// is unintuitive. See: https://eslint.org/docs/rules/no-mixed-operators
				groups: [
					// Conflicts with Prettier: https://github.com/prettier/prettier/issues/3968
					// ["+", "-", "*", "/", "%", "**", "??"],
					['&', '|', '^', '~', '<<', '>>', '>>>', '??'],
					['==', '!=', '===', '!==', '>', '>=', '<', '<=', '??'],
					['&&', '||', '??'],
					['in', 'instanceof', '??'],
				],
			},
		],
```

**Comment by nzakas** [comment]
I can’t say I understand why the operators are grouped the way they are, but it does seem intentional and your config does seem to be the correct way to override the default.

**Comment by nzakas** [comment]
@eslint/eslint-tsc any idea on if this is a bug or otherwise should be changed?

**Comment by btmills** [comment]
I'm not seeing anything that would make me think this is a bug in the rule's default behavior. We could discuss whether we should make this change as an enhancement, but because it'd cause more warnings by default, it'd be semver-major, so I'd lean against doing it. At the very least, it'd have to wait for a major release, and given we're already at v8.0.0-rc.0, that would mean v9.

**Comment by nzakas** [comment]
Sounds good. Given that the behavior seems intentional and there is a workaround, it doesn’t seem like a change is warranted here.

**Comment by fregante** [comment]
> make me think this is a bug in the rule's default behavior

I didn't say it's a bug, it just said it would be helpful to enable more warnings.



> Given that the behavior seems intentional

Intentional how? It just _allows_ more operators being mixed. 🤷‍♂️ It's as "intentional" as the lack of a rule.



> given we're already at v8.0.0-rc.0, that would mean v9.

That's unfortunate, it would be a simple change to bring in v8, hence the issue title.
