### ISSUE TITLE
Fix docs about the config in the root directory

### ISSUE THREAD

**Issue by chinesedfan** [eslint/eslint#14972]
**The version of ESLint you are using.**

7.32.0

**The problem you want to solve.**

Seems from v6, eslint skips the config file in the ~~root~~ home directory. See [codes](https://github.com/eslint/eslintrc/blob/be0f70dacaa3ea1f0f606d240e5f63435b34810e/lib/cascading-config-array-factory.js#L363).
And docs also mention that personal configuration files are deprecated. See [link](https://eslint.org/docs/user-guide/configuring/configuration-files#personal-configuration-files-deprecated).

But there are somewhere makes me confused, like [section 1](https://eslint.org/docs/user-guide/configuring/configuration-files#using-configuration-files) and [section 2](https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy).

> ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem (unless root: true is specified).

> ESLint then searches up the directory structure, merging any .eslintrc files it finds along the way until reaching either a .eslintrc file with root: true or the root directory.

**Your take on the correct solution to problem.**

My point is that those 2 sentences should be updated to reflect the change. Emphasize the ~~root~~ home directory is ignored now. Forgive me if I misunderstood something.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by nzakas** [comment]
The root directory (`/`) isn’t ignored, it’s the user directory (`/~`) that is ignored. So the documentation is correct.

**Comment by chinesedfan** [comment]
@nzakas Thanks for correcting me the difference between the root directory and the home directory. I updated the issue descrption.

But I still have the problem. Should the following 2 places be changed as "the home directory(not included)"? Because eslint will stop at the home directory now. See [eslintrc codes](https://github.com/eslint/eslintrc/blob/be0f70dacaa3ea1f0f606d240e5f63435b34810e/lib/cascading-config-array-factory.js#L363).

> up to **the root directory of the filesystem**

> until reaching either a .eslintrc file with root: true or **the root directory**.

**Comment by chinesedfan** [comment]
Here is my simple test. When the config file is placed at `~/.eslintrc.json`,

```
[zhong@localhost jstest]$ ls ~/.eslintrc.json 
/Users/zhong/.eslintrc.json
[zhong@localhost jstest]$ pwd
/Users/zhong/Desktop/test/jstest
[zhong@localhost jstest]$ DEBUG=eslintrc:* eslint --print-config a.js

  eslintrc:config-array-factory Loading package.json config file: /Users/zhong/Desktop/test/jstest/package.json +9ms
  eslintrc:config-array-factory Loading JSON config file: /Users/zhong/Desktop/test/jstest/package.json +0ms
  eslintrc:config-array-factory Error reading package.json file: /Users/zhong/Desktop/test/jstest/package.json +1ms
  eslintrc:config-array-factory Config file not found on /Users/zhong/Desktop/test/jstest +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong/Desktop/test. +2ms
  eslintrc:config-array-factory Config file not found on /Users/zhong/Desktop/test +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong/Desktop. +0ms
  eslintrc:config-array-factory Config file not found on /Users/zhong/Desktop +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong. +0ms
  eslintrc:cascading-config-array-factory Stop traversing because of considered root. +0ms

{
  "env": {},
  "globals": {},
  "parser": null,
  "parserOptions": {},
  "plugins": [],
  "rules": {},
  "settings": {},
  "ignorePatterns": [
    "a.js"
  ]
}
```

According to logs, you can see that the file is not found and the printed config object is almost empty. But if I moved the file to another place, as well as the subdirectory of the home directory,

```
[zhong@localhost jstest]$ mv ~/.eslintrc.json ~/Desktop/
[zhong@localhost jstest]$ DEBUG=eslintrc:* eslint --print-config a.js

  eslintrc:config-array-factory Config file not found on /Users/zhong/Desktop/test/jstest +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong/Desktop/test. +1ms
  eslintrc:config-array-factory Config file not found on /Users/zhong/Desktop/test +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong/Desktop. +0ms
  eslintrc:config-array-factory Loading JSON config file: /Users/zhong/Desktop/.eslintrc.json +0ms
  eslintrc:config-array-factory Config file found: /Users/zhong/Desktop/.eslintrc.json +3ms
  eslintrc:config-array-factory Loading parser "@babel/eslint-parser" from /Users/zhong/Desktop/.eslintrc.json +0ms
  eslintrc:config-array-factory Loaded: @babel/eslint-parser@7.15.0 (/Users/zhong/.config/yarn/global/node_modules/@babel/eslint-parser/lib/index.cjs) +6ms
  eslintrc:cascading-config-array-factory No cache found: /Users/zhong. +317ms
  eslintrc:cascading-config-array-factory Stop traversing because of considered root. +0ms

{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "globals": {},
  "parser": "/Users/zhong/.config/yarn/global/node_modules/@babel/eslint-parser/lib/index.cjs",
  "parserOptions": {
    "requireConfigFile": false,
    "ecmaVersion": 10,
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [],
  "rules": {
    "for-direction": [
      2
    ],
    "getter-return": [
      2
    ],
    ... ...
```

Now the file is found and loaded. Lots of rules are in the printed config object. Any mistakes?

**Comment by nzakas** [comment]
Ah ok, so you are in a subdirectory of your user directory. Yes, in that case you will stop at the user directory instead of going all the way to the root. Sorry, I misunderstood.

**Comment by Deep1Shikha** [comment]
@nzakas , shall I start working on this? Could you assign it to me?

**Comment by nzakas** [comment]
@Deep1Shikha you are welcome to work on this. Please comment back here if you have any questions.

**Comment by Gautam-Arora24** [comment]
Hello @Deep1Shikha! Are you still working on this issue?
