### ISSUE TITLE
magic comment "eslint-disable-next-line" failed due to code formatting

### ISSUE THREAD

**Issue by doggy8088** [eslint/eslint#14992]
**Tell us about your environment**

```log
Node version: v14.17.5
npm version: v6.14.15
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19043
```

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

`@angular-eslint` & `@typescript-eslint`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json", "e2e/tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "error",
          {
            "prefix": "app",
            "style": "kebab-case",
            "type": "element"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "prefix": "app",
            "style": "camelCase",
            "type": "attribute"
          }
        ],
        "@angular-eslint/no-empty-lifecycle-method": [
          "off"
        ]
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {}
    }
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
@Directive({
  // eslint-disable-next-line @angular-eslint/directive-selector
  selector: 'app-bidirectional-list[formControlName],app-bidirectional-list[formControl]',
  providers: [BI_VALUE_ACCESSOR]
})
// eslint-disable-next-line @angular-eslint/directive-class-suffix
export class BidirectionalListValueAccessor implements ControlValueAccessor {
}
```

```bash
ng lint
```

**What did you expect to happen?**

I expected to pass the lint.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

It actually failed to lint on CI server.

**Steps to reproduce this issue:**

1. Prepare the original source just like above.
2. Run `ng lint` will success.
3. I actually apply Prettier code formatting at Git `pre-commit` hook. The source will be changed after applied prettier code formating.
4. The source code will actually become this:

    ```js
    @Directive({
      // eslint-disable-next-line @angular-eslint/directive-selector
      selector: 
          'app-bidirectional-list[formControlName],app-bidirectional-list[formControl]',
      providers: [BI_VALUE_ACCESSOR]
    })
    // eslint-disable-next-line @angular-eslint/directive-class-suffix
    export class BidirectionalListValueAccessor implements ControlValueAccessor {
    }
    ```

5. The magic comment `// eslint-disable-next-line @angular-eslint/directive-selector` become meaningless. It because the `'app-bidirectional-list[formControlName],app-bidirectional-list[formControl]',` wrapped to another line.

I don't know it's a bug or non-rule change request. Is it possible to let **magic comment** works on this situation?

**Are you willing to submit a pull request to fix this bug?**

I don't know how to fix this issue.

**Comment by mdjermanovic** [comment]
Hi @doggy8088, thanks for the issue!

This works as intended, `eslint-disable-next-line` directive applies only to the next line after the comment.

The solution would be to apply the prettier formatting first, and then add the comment to the right place in the final version:

```js
@Directive({  
  selector:
      // eslint-disable-next-line @angular-eslint/directive-selector
      'app-bidirectional-list[formControlName],app-bidirectional-list[formControl]',
  providers: [BI_VALUE_ACCESSOR]
})
// eslint-disable-next-line @angular-eslint/directive-class-suffix
export class BidirectionalListValueAccessor implements ControlValueAccessor {
}
```
