### ISSUE TITLE
add information about non-capturing regex groups in prefer-named-capture-group docs

### ISSUE THREAD

**Issue by akwodkiewicz** [eslint/eslint#15007]
I wanted to point out that the `prefer-named-capture-group` rule suggest that 2 actions that can be made to fix the error:
- either convert the group to a non-capturing group
- or use a named group

![rule](https://user-images.githubusercontent.com/22861194/131539606-ddff983f-02a5-406d-ba3a-9b04d5dc75e8.png)

However, the [current version of documentation](https://github.com/eslint/eslint/blob/b301069981dc1dcca51df2813dcebdca8c150502/docs/rules/prefer-named-capture-group.md) only explains how to use the named groups. 

While I understand that the rule tries to enforce _named_ groups, it would be wise to instruct about the usage of non-capturing groups `(?:)`. Somebody already must have noticed that case when they created the error message, so why not explaining the second approach further in the docs?

**Comment by mdjermanovic** [comment]
Hi @akwodkiewicz, thanks for the issue!

> However, the [current version of documentation](https://github.com/eslint/eslint/blob/b301069981dc1dcca51df2813dcebdca8c150502/docs/rules/prefer-named-capture-group.md) only explains how to use the named groups.
> 
> While I understand that the rule tries to enforce _named_ groups, it would be wise to instruct about the usage of non-capturing groups `(?:)`. Somebody already must have noticed that case when they created the error message, so why not explaining the second approach further in the docs?

Agreed, this is definitely missing in the docs. PR is welcome!

**Comment by akwodkiewicz** [comment]
I'll try adding something in a while!
