### ISSUE TITLE
add cacheLocation to config 

### ISSUE THREAD

**Issue by jcollum** [eslint/eslint#15020]
**The version of ESLint you are using.**
 7.32.0 

**The problem you want to solve.**
I have this .eslintcache file kicking around my root folder. But it's not a config file, it looks like a temporary file, so it should be in a temp folder. I can override this at the command line but it feels more like a configuration than a command line switch. 

**Your take on the correct solution to problem.**
Add `cacheLocation` as a valid config. Use that value unless the CLI call overrides it. That way I can set my cache location once and it will be valid for all of my calls to eslint CLI without me having to add it to the CLI call. 

**Are you willing to submit a pull request to implement this change?**
Sorry, no, free time is booked up with other projects.

**Comment by nzakas** [comment]
Thanks for the suggestion, however, it's not safe to add this into the config. A shareable config can then override it without making it obvious to you. Cache settings need to remain at the CLI level.

**Comment by jcollum** [comment]
Is there an issue in here for the location of the `.eslintcache` file? I need to add it to a comment in gitignore. The first issue I found was in `create-react-app` repo.

**Comment by jcollum** [comment]
Ah I see, the team wasn't interested in changing it. That's annoying. The root of the project doesn't seem like an appropriate place for a cache file.
