### ISSUE TITLE
Add exception to 'id-length' for array callback functions

### ISSUE THREAD

**Issue by Slapbox** [eslint/eslint#15027]
**What rule do you want to change?**

id-length

**Does this change cause the rule to produce more or fewer warnings?**

Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option to exclude array callback args from the rule.

**Please provide some example code that this change will affect:**

```js
const filteredArray = myArray.filter(t => !t);
```

**What does the rule currently do for this code?**

Rule will currently flag the code for using a single character identifier.

**What will the rule do after it's changed?**

Rule would ignore `t` in the example above and allow the single character identifier. In cases like this, it's likely the developer can easily determine the value of `t` - and adding `t` as an exclusion isn't as satisfactory of a solution as in some other array callback we may wish to use some other letter, or even to nest array callbacks.

**Are you willing to submit a pull request to implement this change?**

No, unfortunately this is beyond my knowledge.

**Comment by mdjermanovic** [comment]
Hi @Slapbox, thanks for the issue!

Per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates), stylistic rules are frozen, so we won't be adding any more options to the `id-length` rule.

You can always make a custom rule based on the code from the core rule.

**Comment by Slapbox** [comment]
@mdjermanovic fair enough!

If possible, I think the issue template for rule change requests should probably mention that prominently.
