### ISSUE TITLE
Support top-level await: status update to Stage-4

### ISSUE THREAD

**Issue by AndreiSoroka** [eslint/eslint#15025]
Status update to Stage-4
https://github.com/tc39/proposal-top-level-await/commit/2762cc57808dd6c965257b5deec636362b4228de

_Originally posted by @vitaliytv in https://github.com/eslint/eslint/issues/14156#issuecomment-853382103_

Any update?

**Comment by AndreiSoroka** [comment]
FYI: @VyrekXD @mdjermanovic @vitaliytv

**Comment by nzakas** [comment]
Duplicate of https://github.com/eslint/eslint/issues/14632

Please be sure to search issues before opening new ones.
