### ISSUE TITLE
remove the old cla checker in all eslint repos

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#15038]
recently we are starting to [use the new cla](https://github.com/eslint/eslint/discussions/14943), but old checker has not been removed in some repos. e.g. https://github.com/eslint/espree/pull/514

![image](https://user-images.githubusercontent.com/13050025/132552287-31d017d9-61d0-4391-a346-e1959a8be691.png)

**Comment by nzakas** [comment]
I think this is all set on the eslint, espree, eslint-visitor-keys, eslintrc, and eslint-scope repos. If you find issues on other repos, please open an issue directly there.
