### ISSUE TITLE
Feature Request: Support plugin references

### ISSUE THREAD

**Issue by wSedlacek** [eslint/eslint#15031]
From what I can tell, plugins defined in config files must be strings.
This makes sense for `yml` and `json` files, however with JavaScript it would be nice to be able to provide a imported reference for the plugin.

This would be useful when using tools like `@nrwl/nx` which analyze the imports into a file to automatically add `dependencies` for node packaging.

Example
```ts
import JsdocPlugin from 'eslint-plugin-jsdoc';

module.exports = {
  plugins: [JsdocPlugin]
}
```
Because TypeScript can trace all the modules being used `eslint-plugin-jsdoc` would be a determined to be a dependency and automatically added to the `dependencies` of the generated `package.json` when `@nrwl/node:package` is run.

**Comment by aladdin-add** [comment]
this is possible in the new coming config system, please subscribe the issue https://github.com/eslint/eslint/issues/13481.

**Comment by wSedlacek** [comment]
Awesome! Thank you!
