### ISSUE TITLE
Switch primary branch to main

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#15042]
We've switched all of the other repos to use `main` as the primary branch, so it's time to move this repo as well. Now that GitHub has automatic branch renaming there are a lot fewer issues to deal with. As best I can tell, these are the steps we need to follow:

- [ ] Update GitHub action workflow files to use "main" instead of "master" (maybe start with listing both to avoid breaking coverage?)
- [ ] Update `Makefile.js` to replace instances of "master" with "main"
- [ ] Update "Working with Rules" documentation to replace instances of "master" with "main"
- [ ] Use GitHub branch rename feature to change "master" to "main"

There don't appear to be any other important [instances of "master"](https://github.com/eslint/eslint/search?q=master) in the codebase. I believe URLs referring to blobs in the repo will automatically redirect once changed through the GitHub feature.

**Comment by ljharb** [comment]
Note that all inks (URLs) can (and probably should) use `HEAD` instead of hardcoding the name of the default branch, and github will redirect it appropriately.

This way, you can also make all the URL changes immediately, and they'll Just Work when you change the default branch of the repo.

**Comment by niteshseram** [comment]
Hi, Can i work on this?

**Comment by nzakas** [comment]
@niteshseram yes, we would love the help! 🙏

**Comment by niteshseram** [comment]
I will make a PR soon

**Comment by mdjermanovic** [comment]
Data Fetches scripts (sponsor data and team data) on Jenkins should be updated, too.

**Comment by nzakas** [comment]
Good call. I updated them to use HEAD.
