### ISSUE TITLE
Rule Change: `no-restricted-imports` support replacement for fixer or suggestion

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#15054]
### What rule do you want to change?

no-restricted-imports

### Does this change cause the rule to produce more or fewer warnings?

No change to warnings

### How do you think the change should be implemented?

A new option

### Example code

```js
{
  "rules": {
    "no-restricted-imports": [
      2,
      {
        "paths": [
          {
            "name": "rxjs/operators",
            // replace module name
            "replacements": ["rxjs"],
            "message": "Please use top level `rxjs` directly instead."
          },
          {
            "name": "use-memo-one",
            "importNames": ["useMemoOne", "useCallbackOne"],
            // replace named exports
            "replacements": {
              "useMemoOne": "useMemo",
              "useCallbackOne": "useCallback"
            },
            "message": "use-memo-one exports `useMemo` and `useCallback` which work nicer with `eslint-plugin-react-hooks`"
          }
        ]
      }
    ]
  }
}
```

### What does the rule currently do for this code?

N/A

### What will the rule do after it's changed?

N/A

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by nzakas** [comment]
There’s not enough information in this issue to evaluate. Please explain what it is you’re requesting and show some example code as requested.

**Comment by JounQin** [comment]
@nzakas 

Does not the comments help?

`// replace module name` and `// replace named exports`

In details, I want rule `no-restricted-imports` to support auto fixer, what means:

```ts
// original
import {} from 'rx/operators'
import { useMemoOne, useCallbackOne } from 'use-memo-one'

// fixed
import {} from 'rxjs'
import { useMemo, useCallback } from 'use-memo-one'
```

**Comment by mdjermanovic** [comment]
> ```js
> {
>     "name": "rxjs/operators",
>     // replace module name
>     "replacements": ["rxjs"],
>     "message": "Please use top level `rxjs` directly instead."
>}
> ```

I'm not sure how common is the scenario where all that needs to be changed in the code is just the import source, and thus how useful this feature would be. On the contrary, I have concerns that this feature could introduce bugs in user codebases or require a very complex configuration with mapping exports from one module to exports from one or more other modules.

**Comment by JounQin** [comment]
`replacements` are chosen by users, if they add them, then they should have confirmed what they want.

In my case, we have a lot of custom components which aim to override a 3rd party library's original style:

```ts
// original
import { Alert, Table, Card } from 'antd'

// after
import { Card } from 'antd'

import { Alert, Table } from 'components'
```

**Comment by mdjermanovic** [comment]
> `replacements` are chosen by users, if they add them, then they should have confirmed what they want.

Yes, but they should be very careful to use this feature only with replacements that provide the exact same functionality, otherwise autofix could introduce numerous bugs in the code.


> ```ts
> // original
> import { Alert, Table, Card } from 'antd'
> 
> // after
> import { Card } from 'antd'
> 
> import { Alert, Table } from 'components'
> ```

This would require a more complex configuration that would define a map (name1, module1) -> (name2, module2)

**Comment by nzakas** [comment]
I agree with @mdjermanovic — this seems like a fragile operation, and auto fixes in the core must never change how the code works. If we can’t guarantee that, then we shouldn’t do it.

**Comment by nzakas** [comment]
Closing as we won’t be moving forward with this.
