### ISSUE TITLE
Change Request: Eslint plugins exported via custom entry-point

### ISSUE THREAD

**Issue by danieldelcore** [eslint/eslint#15069]
### ESLint version

v7.7.0

### What problem do you want to solve?

Support the ability to register eslint plugins exposed via custom entry-points. 

For example, a package which contains source code for the package itself and all supporting tooling related to the package, including an eslint plugin. 

Currently the docs state: 

> Each plugin is an npm module with a name in the format of eslint-plugin-<plugin-name>, such as eslint-plugin-jquery. You can also use scoped packages in the format of @<scope>/eslint-plugin-<plugin-name> such as @jquery/eslint-plugin-jquery or even @<scope>/eslint-plugin such as @jquery/eslint-plugin.

But to support this use case we would need eslint to support the following: `@scope/packageName/eslint-plugin-packageName`

### What do you think is the correct solution?

Eslint could be updated to be entry-point aware when attempting to register plugins.

Potentially by updating this logic (maybe 😬): https://github.com/eslint/eslint/blob/a744dfa1f077afe406014f84135f8d26e9a12a94/lib/init/config-initializer.js#L115

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We aren’t making any changes to how plugins work in the current config system. The [new config system](https://github.com/eslint/eslint/issues/13481) doesn’t have any constraints on how your plugins are packaged.
