### ISSUE TITLE
Rule function-paren-newline incorrectly formats a method with a ordered array as a return type

### ISSUE THREAD

**Issue by simonkarman** [eslint/eslint#15091]
### Environment

Node version: v16.9.1
npm version: 7.21.1
Local ESLint version: 7.32.0
Global ESLint version: none
Operating System: Ubuntu 20.04

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
Rule function-paren-newline incorrectly formats a function with a ordered array as a return type, when that function has its parameters on new lines and the return type has a method in its type. Only happens when the function is an inline function and the return type of that function is specified on the function itself.
</details>

```ts
// works when all on the same line
const method1: (abc: number, def: () => void) => [string, number] = () => ['a', 2];
method1(3, () => {});

// works when function is part of the params
const method2: (
  abc: number,
  def: () => void
) => [string, number] = () => ['a', 2];
method2(3, () => {});

// works when function definition is defined separate from the implementation
const method3: (
  abc: number,
  def: () => void
) => [string, () => void] = () => ['a', () => {}];
method3(3, () => {});

// works when function definition is defined separate from the implementation even if array is on multiple lines
const method4: (
  abc: number,
  def: () => void
) => [
  string,
  () => void
] = () => ['a', () => {}];
method4(3, () => {});

// works when the function parameters are on the same line
const method5 = (abc: number, def: () => void): [
  string,
  () => void,
] => [`a${abc}`, def];
method5(3, () => {});

// doesn't work when the function itself is given a return type, now we need to use a 'disable next line' for the rule
const method6 = (
  abc: number,
  def: () => void,
): [
  string,
  // eslint-disable-next-line function-paren-newline
  () => void
] => [`a${abc}`, def];
method6(3, () => {});
```

### What did you expect to happen?

I expect the following to work even without the disable next line.
```ts
const method6 = (
  abc: number,
  def: () => void,
): [
  string,
  // eslint-disable-next-line function-paren-newline
  () => void
] => [`a${abc}`, def];
method6(3, () => {});
```

Unfortunately it transforms it to:
```ts
const method6 = (
  abc: number,
  def: () => void,
): [
  string,
  (
) => void
] => [`a${abc}`, def];
method6(3, () => {});
```

### What actually happened?

Expected newline before ')'.eslintfunction-paren-newline

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @simonkarman, thanks for the issue!

I think we can improve the `function-paren-newline` rule to better support Typescript code in this particular case.

Can you please provide one example where this rule doesn't work as expected with Typescript, so we could test the rule on that example? In particular:

1. Your configuration for `function-paren-newline`.
2. Code where this rule reports a parenthesis that shouldn't be reported (please don't include eslint-disable comments in the example).

**Comment by mdjermanovic** [comment]
I can reproduce this with ESLint v8.3.0, @typescript-eslint/parser v5.4.0, and the following code:

```ts
/* eslint function-paren-newline: ["error", "multiline"] */

const method6 = (
  abc: number,
  def: () => void,
): [
  string,
  () => void
] => [`a${abc}`, def];
method6(3, () => {});
```

I'll work on this.
