### ISSUE TITLE
Change Request: Implement expect error ( similar to typescript )

### ISSUE THREAD

**Issue by danielhammerl** [eslint/eslint#15108]
### ESLint version

7.32.0

### What problem do you want to solve?

When you add a "eslint-disable-next-line" in your code for a temporary problem and refactor your code afterwards, so the eslint error isnt thrown anymore, you want to remove the "eslint-disable-next-line". If you forget it you may have new eslint errors you dont expect and you dont see them.

### What do you think is the correct solution?

Have the option to add a comment like "eslint-expect-error-next-line" like also done in typescript, to ignore a linting error but also throws a new error if the original error isnt thrown anymore, so it reminds you to remove the comment again.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments

**Comment by mdjermanovic** [comment]
Hi @danielhammerl, thanks for the issue!

> When you add a "eslint-disable-next-line" in your code for a temporary problem and refactor your code afterwards, so the eslint error isnt thrown anymore, you want to remove the "eslint-disable-next-line". If you forget it you may have new eslint errors you dont expect and you dont see them.

I think this use case is already covered by the CLI option [--report-unused-disable-directives](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives) or config option [`"reportUnusedDisableDirectives"`](https://eslint.org/docs/user-guide/configuring/rules#report-unused-eslint-disable-comments).

**Comment by danielhammerl** [comment]
Great thank you, thats exactly what i was looking for

**Comment by ljharb** [comment]
However, this seems like it only produces warnings - is there a way to make it produce *errors*?
