### ISSUE TITLE
global declarations should be inline, not hoisted

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#1512]
In the `es5-shim` I have the following lines:
```js
/*global Date: true */
Date = (function () { return …; }());
/*global Date: false */
```

Thus, `Date` should both be global and writable, but only writable for the lines that appear within the comments. However, I get the following error on `eslint v0.9.2`:
`error    'Date' is read only                                              no-undef`

Does ESLint, unlike JSHint and JSLint, not support turning rules on and off for specific blocks of code within the same scope?

**Comment by IanVS** [comment]
This has been open for a year with no movement.  Is it worth keeping open, or can we close as a `wontfix`?

**Comment by ljharb** [comment]
I'd still like to see it - `global` follows certain rules that only `eslint` seems to not follow.

**Comment by nzakas** [comment]
Closing. will reopen if someone wants to submit a PR.

**Comment by ljharb** [comment]
How will anybody know to submit a PR if it's closed? ◉︵◉

**Comment by georeith** [comment]
Another place I need this is when using tools like PhantomJS. You have functions that will be run in different contexts with different globals. For example:

```js
phantom.create()
    .then(instance => instance.createPage())
    .then(page => page.evaluate(() => {
        /* global React, ReactDOM */
        // globals exist here
    })).then(() => {
        // globals don't exist here
    });
```
