### ISSUE TITLE
Change Request: Add eslint-config-prettier as a style guide during init

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [eslint/eslint#15131]
### ESLint version

v7.32.0

### What problem do you want to solve?

Right now `eslint --init` supports only 4 style guides, google, airbnb, standard and xo. This is a request to add prettier as another style guide as it is a very popular style in the ecosystem.

### What do you think is the correct solution?

`eslint-config-prettier ` could be added as an option during the questions when entering the style guide choice.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. eslint-config-prettier is not a style guide, it only turns rules off that conflict with prettier preferences. You still need to manually use prettier to format your code. As such, this isn’t a good fit to add.

**Comment by SayakMukhopadhyay** [comment]
> You still need to manually use prettier to format your code

Is adding Prettier as a dependency and using `eslint-config-prettier` and `eslint-plugin-prettier` a non use case for ESLint?
