### ISSUE TITLE
Bug: update eslint package, @humanwhocodes/config-array Not Found

### ISSUE THREAD

**Issue by pedropcruz** [eslint/eslint#15141]
### Environment

Node version: 14.18.0
npm version: 6.14.15
Local ESLint version: 
Global ESLint version: 
Operating System: Windows 11

### What parser are you using?

Other

### What did you do?

Basically, I install eslint@nest version, like: `npm i eslint@next --save-dev` and I'm getting this error
![image](https://user-images.githubusercontent.com/6757946/136434079-608dfa81-9aa9-42fd-9c97-af739b811dc7.png)

### What did you expect to happen?

install the package

### What actually happened?

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by drochgenius** [comment]
Facing this issue in our CI as well, trying to install `eslint@latest`

**Comment by pedropcruz** [comment]
I'm getting the same.

![image](https://user-images.githubusercontent.com/6757946/136434896-5607d79b-df68-4b0e-b849-ad672d4d0a40.png)

Is it because the npm service is down?

https://status.npmjs.org/

**Comment by nzakas** [comment]
Yes, there is an ongoing npm outage. This isn’t an issue with ESLint itself.
