### ISSUE TITLE
Bug: using babel-eslint parser throws error

### ISSUE THREAD

**Issue by ais-one** [eslint/eslint#15157]
### Environment

Node version: 14.18.0
npm version: 6.14.15
Local ESLint version:  v8.0.0
Global ESLint version:  Not Found
Operating System: win32 10.0.18363
 
Also "babel-eslint": "^10.1.0",

### What parser are you using?

Other

### What did you do?

1. create a project using npm init
2. install eslint and babel-eslint
3. eslint --init settings: CommonJS, Not using react or vue,  No typescript, run on node, use JS for config file
4. create a simple console.log('hello world') JS file
5. add `parser: 'babel-eslint'` to .eslintrc file
6. run the lint

### What did you expect to happen?

No error when linting

### What actually happened?

get the error below

```
  0:0  error  Parsing error: Must use import to load ES Module: C:\Users\aaron\test\cookbook\js-node\expressjs\node_modules\eslint-scope\lib\definition.js
require() of ES modules is not supported.
require() of C:\Users\aaron\test\cookbook\js-node\expressjs\node_modules\eslint-scope\lib\definition.js from C:\Users\aaron\test\cookbook\js-node\expressjs\node_modules\babel-eslint\lib\require-from-eslint.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename definition.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\aaron\test\cookbook\js-node\expressjs\node_modules\eslint-scope\package.json
```

When I remove the parser: 'babel-eslint'. The linting runs without error...

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snitin315** [comment]
Resolved in https://github.com/babel/babel/pull/13782
