### ISSUE TITLE
Bug: Unable to resolve path to module 'swiper'

### ISSUE THREAD

**Issue by vicasas** [eslint/eslint#15171]
### Environment

Node version: 16.3.0
npm version: 7.15.1
Local ESLint version: 7.32.0
Global ESLint version: 
Operating System: Mac OS

### What parser are you using?

Default (Espree)

### What did you do?

I am creating a web application using Next.js together with React Swiper v7 to create carousels.

<details>
<summary>Configuration</summary>

```json
{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": ["plugin:react/recommended", "plugin:@next/next/recommended", "airbnb", "prettier"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["react", "prettier"],
  "rules": {
    "prettier/prettier": "error",
    "react/react-in-jsx-scope": "off",
    "react/jsx-props-no-spreading": "off",
    "react/forbid-prop-types": "off",
    // defaultProps rule to be deprecated on function components
    // https://github.com/reactjs/rfcs/pull/107
    "react/require-default-props": [
      "error",
      {
        "ignoreFunctionalComponents": true
      }
    ]
  }
}
```
</details>

```js
import { A11y, Autoplay, Navigation, Pagination } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
```

### What did you expect to happen?

I was hoping that when importing the modules using `import {} from` this Eslint would recognize it as a valid path since it exists in my `node_modules` folder but it ends up throwing an error when not being able to resolve the path.

### What actually happened?

What happened was that when importing the Swiper modules it threw the following error.

> Unable to resolve path to module 'swiper/react'.eslintimport/no-unresolved

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @vicasas, thanks for the issue! 

> What happened was that when importing the Swiper modules it threw the following error.
> 
> > Unable to resolve path to module 'swiper/react'.eslintimport/no-unresolved

This error is reported by a plugin rule `import/no-unresolved`. Can you please open an issue in the plugin's repository:

https://github.com/import-js/eslint-plugin-import

**Comment by vicasas** [comment]
follow-up https://github.com/import-js/eslint-plugin-import/issues/2266
