### ISSUE TITLE
Classes strict organization with pattern members

### ISSUE THREAD

**Issue by djmisterjon** [eslint/eslint#15189]
### ESLint version

v8

### What problem do you want to solve?

i would like found a way to organize members declarations inside class with a strict pattern.

Consider a class disordered this way
```js
export class Class {

	// 0
	static sta1;

	// 1
	static get get() {
		return this;
	}

	// 2
	constructor(){
	
	}

	// 3
	static methodName() {
		
	}

	// 0
	pub = null;

	// 0
	#pri = null;

	// 1
	get get() {
		return this;
	}

	// 3
	#meth1() {
		
	}

	// 1
	set set( v ) {
	
	}

	// 3
	meth2() {
		
	}

	// 0
	pro = null;

	// 3
	meth3() {
		
	}

}
```
Do we have a rule to force ordering pattern like this ?

```json
        "classes-pattern-orders-correlation": [
            "warn",
            {
                "ignor-getter": false,
                "pattern-members-orders": [
                    "statics",
                    "properties",
                    "getters-setters",
                    "constructors",
                    "methodes",
                ]
            }
        ],
```

```js
export class Class {

	// 0
	static sta1;

	// 1
	static get get() {
		return this;
	}

	// 3
	static methodName() {
		
	}

	// 0
	pub = null;

	// 0
	pro = null;

	// 0
	#pri = null;

	// 1
	get get() {
		return this;
	}

	// 1
	set set( v ) {
	
	}

	// 2
	constructor(){
	
	}

	// 3
	#meth1() {
		
	}

	// 3
	meth2() {
		
	}

	// 3
	meth3() {
		
	}

}
```

or a near solutions ?

### What do you think is the correct solution?

I am not sure at the moment because given that the order of the properties in classes can be strongly coupled with `this`, so it could maybe a issue !

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

thanks for your suggestions and sorry if there is already a solution, i was not able to find something.

**Comment by nzakas** [comment]
Thanks for the suggestion. There isn’t already a solution, but we aren’t adding any more core rules that just enforce stylistic preferences. You’d need to create a custom rule for this purpose.
