### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rules/no-unused-expressions' is not defined by "exports"

### ISSUE THREAD

**Issue by codingChewie** [eslint/eslint#15195]
### Environment

Node version: v14.17.1
npm version: 6.14.13
Local ESLint version: 8.0.1
Global ESLint version: NA
Operating System: Mojave 10.14.6

### What parser are you using?

Other

### What did you do?

Installed [`eslint-config-react-native-community`](https://github.com/facebook/react-native/tree/main/packages/eslint-config-react-native-community) with the command:

```
yarn add --dev eslint prettier @react-native-community/eslint-config
```

added to _.eslintrc_:

```
{
  "extends": "@react-native-community",
  "rules": {
    "quotes": [2, "single", { "avoidEscape": true }],
    "semi": ["error", "never"]
  }
}
```

added `lint` to`scripts`:

```
"scripts": {
  "start": "expo start",
  "android": "expo start --android",
  "ios": "expo start --ios",
  "web": "expo start --web",
  "eject": "expo eject",
  "lint": "eslint . --ext .js"
},
```

dependencies:

```
"dependencies": {
  "expo": "~42.0.1",
  "expo-status-bar": "~1.0.4",
  "react": "16.13.1",
  "react-dom": "16.13.1",
  "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
  "react-native-web": "~0.13.12"
},
"devDependencies": {
  "@babel/core": "^7.9.0",
  "@react-native-community/eslint-config": "^3.0.1",
  "eslint": "^8.0.1",
  "prettier": "^2.4.1"
},
```

### What did you expect to happen?

Ran the command `yarn lint` and get a linting report back.

### What actually happened?

Terminal threw an error:

```
Oops! Something went wrong! :(

ESLint: 8.0.1

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rules/no-unused-expressions' is not defined by "exports" in /Users/USER/project/node_modules/eslint/package.json
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

In my research I've run across this issue "[eslint-config-react-app is not compatible with ESLint 8](https://github.com/facebook/create-react-app/issues/11549)" from `create-react-app` thought I'm building in React Native with Expo. 

When I search for a similar issue from this repo the closest I was able to find was this issue: "[[eslint-plugin-flowtype] 'no-unused-expressions' rule not defined](https://github.com/eslint/eslint/issues/15192)" but isn't directory related so I thought I'd author a new issue.

Had to revert to an older version of ESLint for linting to work in my expo project: version `7.16.0`

**Comment by nzakas** [comment]
You’ll have to ask the maintainer if that config to update it for ESLint 8. See https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0

**Comment by adamgajzlerowicz** [comment]
Seems that `@react-native-community/eslint-config` for whatever reason depends on `eslint-plugin-flowtype`. 

Adding it as a dev dependency `yarn add --dev eslint-plugin-flowtype@8.0.3` allows eslint update to version 8

**Comment by adamgajzlerowicz** [comment]
Seems that `@react-native-community/eslint-config`  depends on `eslint-plugin-flowtype` package. 

Adding it as a dev dependency with, allows eslint update to version 8
```
yarn add --dev eslint-plugin-flowtype@8.0.3
```
