### ISSUE TITLE
Change Request: If `ecmaVersion: latest` pass `ecmaVersion: 6` to eslint-scope

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint#15256]
### ESLint version

v8.1.0

### What problem do you want to solve?

I want to resolve a problem where a user uses a parser other than `espree` and uses `ecmaVersion: latest` to reject syntax such as import statements as an error.

Currently vue-eslint-parser can accept and parse `ecmaVersion: latest`, but users can't actually use with ESLint because of an error in eslint-scope.

Related to: https://github.com/vuejs/vue-eslint-parser/issues/135, https://github.com/eslint/eslint-scope/issues/78

### What do you think is the correct solution?

I want to change ESLint to pass `ecmaVersion: 6` to `eslint-scope` if the user sets `ecmaVersion: latest`.

https://github.com/eslint/eslint/blob/3630211c46f1ed691445231164e29e5cd6c87dff/lib/linter/linter.js#L629

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
In general, we should pass ecmaVersion 6 to eslint-scope whenever a non-numeric ecmaVersion is found.
