### ISSUE TITLE
Rule Change: no-mixed-spaces-and-tabs 

### ISSUE THREAD

**Issue by djmisterjon** [eslint/eslint#15254]
### What rule do you want to change?

no-mixed-spaces-and-tabs 

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

Options for prefer: "spaces" or prefer: "tabs"

### Example code

```js
transform = {
 		x:0,
 		y:0,
		height:0,
		width:0,
	 	radians:0,
		scaleX:1,
		scaleY:1,
	};
```

### What does the rule currently do for this code?

It not auto fix, need to do it manually replace by tabs when they have mix space ! 

### What will the rule do after it's changed?

Hi guys, did you think you can reconsidering a way to add a **auto-fix**  for the rule `no-mixed-spaces-and-tabs` .
A very old post was close about this , but maybe your team can reconsidering the issue ?
https://github.com/eslint/eslint/issues/6873

The reason is actually i am really happy to finally take of Prettier with all imposed rule syntax to use only Eslint for format my codes.

Everything work very fine with Eslint formater, but **the only one rule** where give me sometime big time waste, it to manually fix all spaces in tabs when sometime i duplicate codes, structures, copy past from another source , or generate code with intellisence or githubCopilote ....

![image](https://user-images.githubusercontent.com/24865815/140252947-7d0c4add-d8e6-40ad-807f-c37674cb4e7a.png)

From what i remember , by using Prettier, it successfully remove those space inside tabs indents without issue!
So is there maybe a way to add this ? 
I really want avoid use Prettier mixed with Eslint because it will impose you some rule , slow compute and break some formatting rules.

Ideas and opinions can change, and I wonder if the subject could be revalued for a native implementation ?
I think what @Wilfred suggest in others post are not so bad and maybe your team can try something ? 

 thanks a lot for all your great work on Eslint, it one of my favorite productivity tools!
 If this will definitively never added, feel free to close and thanks.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by nzakas** [comment]
Thanks for the input. As [stated in the README](https://github.com/eslint/eslint#stylistic-rule-updates), we actually aren't making any further updates to rules that enforce stylistic preferences. If you have a strong preference for such a change, you can always copy the existing rule into a custom rule and make it behave the way you want.
