### ISSUE TITLE
Bug: 'return' can't be read by lint? require-atomic-updates

### ISSUE THREAD

**Issue by ShuiX** [eslint/eslint#15260]
### Environment

Node version: v16.2.0
npm version: v7.13.0
Local ESLint version: 8.1.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 19.6.0 | macOS Catalina 10.15.7

### What parser are you using?

vue-eslint-parser

### What did you do?

<details>

<summary>Configuration</summary>

```
Vue version: 2.6.14
Vue composition API version: 1.3.2
Typescript version: 4.4.4
```

</details>

### The code

```js
async () => {
      if (props.kind === ChannelType.radio) {
        return
      }
      if (showLanguageSelection.value) {
        showLanguageSelection.value = false
        return
      }
      audioAndSubtitleStore.setAudioLangs(await (await createTvDeviceService()).fetchAudioAvailable())
      if (entertainmentMode.value && audioAndSubtitleStore.getAudioLangs?.length > 1) {
        languageType.value = LanguageType.audio
        showLanguageSelection.value = true // require-atomic-updates gets triggered.
      }
    }
```

By adding the ```!showLanguageSelection.value``` to the ```if (entertainmentMode.value && audioAndSubtitleStore.getAudioLangs?.length > 1)``` statement fixes the rule.

### What did you expect to happen?

```return``` in ``` if (showLanguageSelection.value) {
        showLanguageSelection.value = false
        return
      }``` should fix the rule, since ```showLanguageSelection.value = true``` won't get executed.

### What actually happened?

![Bildschirmfoto 2021-11-04 um 10 15 58](https://user-images.githubusercontent.com/37545626/140288116-7d57f37d-aefc-4c7e-80ef-5cb09836e5ad.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @ShuiX, thanks for the issue!

> ```js
> async () => {
>       if (props.kind === ChannelType.radio) {
>         return
>       }
>       if (showLanguageSelection.value) {
>         showLanguageSelection.value = false
>         return
>       }
>       audioAndSubtitleStore.setAudioLangs(await (await createTvDeviceService()).fetchAudioAvailable())
>       if (entertainmentMode.value && audioAndSubtitleStore.getAudioLangs?.length > 1) {
>         languageType.value = LanguageType.audio
>         showLanguageSelection.value = true // require-atomic-updates gets triggered.
>       }
>     }
> ```


The rule works as intended in this case. `showLanguageSelection.value` is read before `await` and then assigned after `await`, so the rule detects that the code after `await` works on the assumption that `showLanguageSelection.value`  hasn't changed, which generally doesn't have to be the case, as in this simplified example:

```js
const showLanguageSelection = { value: false }

const func = async () => {
  if (showLanguageSelection.value) {
    showLanguageSelection.value = false
    return
  }
  await 0
  console.log(showLanguageSelection.value);

  // ... do something assuming that `showLanguageSelection.value` is `false`

  showLanguageSelection.value = true 
}

func() // logs `false`
func() // logs `true` !
```

> By adding the `!showLanguageSelection.value` to the `if (entertainmentMode.value && audioAndSubtitleStore.getAudioLangs?.length > 1)` statement fixes the rule

That is exactly the expected fix because it checks if `showLanguageSelection.value` hasn't changed in the meantime. As `showLanguageSelection.value` is read again after `await` and before the assignment, the rule assumes that the assignment is based on the new value, so it isn't reported.
