### ISSUE TITLE
New Rule: No unnecessary `Promise.resolve/reject()` in async function

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#15280]
### Rule details

The rule should prevent using moot `Promise.reject` and `Promise.resovle` calls in async functions.

### Related ECMAScript feature

Promises and async/await

### What type of rule is this?

Suggests an alternate way of doing something

### Example code

```js
// Before

const main = async foo => {
	if (foo > 4) {
		return Promise.reject(new Error('🤪'));
	}

	return Promise.resolve(result);
};


// After

const main = async foo => {
	if (foo > 4) {
		throw new Error('🤪');
	}

	return result;
};
```

### Why should this rule be in the core instead of a plugin?

It's about promises and async/await which is core to JavaScript.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by nzakas** [comment]
Thanks for the submission. Unfortunately, this rule doesn't meet our [criteria for new rules](https://eslint.org/blog/2020/05/changes-to-rules-policies), so I'm closing this issue. We aren’t adding new rules except for syntax that was introduced in the past year or in the case of errors. Given that this rule just enforces a stylistic preference, it’s not a fit for a core rule. 

Please note that you can always create any rule you want and distribute it in your own plugin for use with ESLint.

**Comment by sindresorhus** [comment]
No problem. Continued in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1609.
