### ISSUE TITLE
Feedback Needed: Passing options to parsers with new config system

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#15284]
## Background

In the new config system, `ecmaVersion` and `sourceType` have moved onto the `languageOptions` object in order to better represent how ESLint uses this information. Previously, these were passed solely on `parserOptions`, and there are a bunch of places where ESLint used those values outside of parsing.

Current config system (eslintrc):

```js
{
    parserOptions: {
        ecmaVersion: 2021,
        sourceType: "module"
    }
}
```

New config system (flat config):

```js
{
    languageOptions: {
        ecmaVersion: 2021,
        sourceType: "module",
        parserOptions: {}
    }
}
```

In this format, `parserOptions` can also be provided for anything that ESLint doesn't support directly.

## Question: How do custom parsers want to receive these values?

Ideally, ESLint could pass `ecmaVersion` and `sourceType` directly into custom parsers (users can override this by manually assigning other values in `parserOptions`). This would mean that custom parsers would always receive:

* `ecmaVersion` - this would be 3, 5, or the year-based ECMAScript version (2015 instead of 6, for example). This would never be "latest", because this value is always normalized to the most recent ECMAScript version that ESLint supports in the core.
* `sourceType` - passed as-is.

Will this work for custom parsers?

## Question: Can custom parsers support `sourceType: commonjs`?

One of the changes we've made is to introduce a third possible value for `sourceType`, which is "commonjs". This lets ESLint know that the file is a CommonJS file and so it will allow top-level `return` statements and add the CommonJS global variables.

For best compatibility, it would be ideal if custom parsers also supported `sourceType: commonjs`, so we could pass `sourceType` through directly.

Are custom parser maintainers willing/able to do this?

cc @ota-meshi @bradzacher @nicolo-ribaudo

**Comment by bradzacher** [comment]
In terms of `ecmaVersion` - typescript-eslint only respects this from within the scope analyser in two ways:
1) it loads up a bunch of global variables from the TS lib defs based on this
2) the standard ways that eslint-scope uses it.
    - In this case it only cares about 2 values, is it `=== 5` or `>= 6`.
    - TBH we're getting to a state of JS where this could probably be deprecated and removed as it's rare (/ never) that someone is writing raw ES5 code by hand (I don't think it happens _at all_ in TS).

We currently do conversions from `latest` to `1e99` which then maps back to "esnext" (which is basically "give me all the TS libdefs").

---

In terms of `sourceType` - this is currently respected only by our scope analyser.
TS has its own definition of what is a script vs a module, which we defer to letting TS figure this out on its own.
Thinking about it - the scope analyser should probably ignore this as well and instead just respect the `sourceType` stored on the `Program`.

For "supporting `sourceType: commonjs`" - similarly it doesn't make much sense for our tooling to respect this either.

---

Most of the `ecmaFeatures` are ignored by typescript-eslint:
- `impliedStrict` is ignored completely
- `jsx` is respected in [certain but very limited and rare circumstances](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionsecmafeaturesjsx)
- `globalReturn` is respected by the scope analyser only (based on code from eslint-scope)

**Comment by nicolo-ribaudo** [comment]
I would love `sourceType: commonjs`. I recently fixed a bug in `@babel/eslint-parser` that was initially related to how we decide when to allow top-level return and when not.

I also like that `ecmaVersion` would be normalized. Babel ignores it (it always enables the last standard by default), but we have to pass it to something (eslint-scope?) and we received a bug report a few months ago because we didn't normalize `latest`.

**Comment by ota-meshi** [comment]
About vue-eslint-parser.
vue-eslint-parser transfers most of the script parsing to another script parser, so it is largely unaffected by changes in parser options.
vue-eslint-parser currently does its own normalization of `ecmaVersion: latest`, but I can remove it if ecmaVersion is normalized by the ESLint engine 😃.
As for parser processing, there is no problem even if there is `sourceType: commonjs`.

**Comment by nzakas** [comment]
@bradzacher 

> For "supporting sourceType: commonjs" - similarly it doesn't make much sense for our tooling to respect this either.

If we pass “commonjs”, could you map that to “script”? I’m mostly worried about parsers failing with an unexpected value.

> We currently do conversions from latest to 1e99 which then maps back to "esnext" (which is basically "give me all the TS libdefs").

If we pass you a normalized ecmaVersion will that be a problem for this?

@nicolo-ribaudo 

> Babel users can set a custom sourceType for specific files in the Babel config -- I don't know how we handle it in integration with ESLint, but it would be nice to allow parser to decide the sourceType (at least when it's not explicitly set in the ESLint config).

Can you point me to an example of this? At the moment, you’ll always receive a sourceType from ESLint. You can, of course, choose to ignore it.

@ota-meshi awesome, thanks!

**Comment by nzakas** [comment]
This was actually already merged with the Linter PR, so closing.
