### ISSUE TITLE
Bug: deprecate lines-around-comment

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#15292]
### What did you expect to happen?

`meta.deprecated` to be set.

### What actually happened?

`meta.deprecated` is not set.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This rule is deprecated in documentation, but not in `meta`.

https://eslint.org/docs/rules/lines-around-comment

**Comment by mdjermanovic** [comment]
Hi @gajus, thanks for finding this!

> This rule is deprecated in documentation, but not in `meta`.
> 
> https://eslint.org/docs/rules/lines-around-comment

`lines-around-comment` isn't deprecated, this is a documentation bug. I prepared https://github.com/eslint/eslint/pull/15293 to fix that.
