### ISSUE TITLE
Bug: `eslint-disable` should accept `//` style comments too

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#15329]
### Environment

-

### What parser are you using?

Default (Espree)

### What did you do?

See [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLy8gZXNsaW50LWRpc2FibGUgbm8tZGVidWdnZXJcbmRlYnVnZ2VyO1xuLy8gZXNsaW50LWVuYWJsZSBuby1kZWJ1Z2dlclxuXG4vKiBlc2xpbnQtZGlzYWJsZSBuby1kZWJ1Z2dlciAqL1xuZGVidWdnZXI7XG4vKiBlc2xpbnQtZW5hYmxlIG5vLWRlYnVnZ2VyICovIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby1kZWJ1Z2dlciI6Mn0sImVudiI6e319fQ==).

### What did you expect to happen?

The rule to be disabled between `//` comments and linting to pass.

### What actually happened?

Linting failed because eslint does not seem to recognize directives defined in `//` comments but does in `/**/` comments.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
We tried this but it caused too many problems so we rolled it back:
https://github.com/eslint/eslint/issues/14960

So, we won’t be making any changes related to this.
