### ISSUE TITLE
Can't able to sign CLA. Links are broken.

### ISSUE THREAD

**Issue by akgupta0777** [eslint/eslint#15367]
I am new to ESLint and want to contribute to the repository. I am required to sign the CLA before contributing.
But the links are just broken and giving Authentication errors.

Here is the image for reference.
Link I used for signing CLA - https://cla.js.foundation/eslint/eslint

![image](https://user-images.githubusercontent.com/51379307/143776877-3bdd4890-adf6-43d4-a281-4167c8cc663d.png)

**Comment by snitin315** [comment]
Hi @akgupta0777, that is the old CLA link.

Please find the latest CLA info here - https://eslint.org/docs/developer-guide/contributing/#signing-the-cla

Also, the CLA bot will provide you with the latest link when you open PR for the first time.

**Comment by snitin315** [comment]
I have opened a PR to update it in `CONTRIBUTING.md`.

**Comment by akgupta0777** [comment]
@snitin315 thanks ❤️
