### ISSUE TITLE
Rule Change: brace-style exception for comments

### ISSUE THREAD

**Issue by emmanuelvlad** [eslint/eslint#15378]
### What rule do you want to change?

brace-style

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
// should PASS, does PASS
if (true) {
  a();
} else {
  b();
}

// should ERROR, does ERROR
if (true) {
  a();
}
else {
  b();
}

// should PASS, does ERROR
if (true) {
  a();
}

// something something
else {
  b();
}
```

### What does the rule currently do for this code?

It will just error if there is a line between the blocks

### What will the rule do after it's changed?

Allow comments between blocks for better code visibility

Ex.
```js
function foo(a, b, c) {
  let tmp;

  // Very useful comment
  // Explaining how this works
  if (a && c) {
    ...
    ...
    ...
  }

  // Documentation...
  // Does this and this
  // ...
  else if (a > 10) {
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
  }

  // Fallback on B
  // More documentation...
  else {
    ...
    tmp = b & a;
    ...
    ...
    ...
  }
}
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

duplicate of #8586

**Comment by nzakas** [comment]
Thanks for the input. As [stated in the README](https://github.com/eslint/eslint#stylistic-rule-updates), we actually aren't making any further updates to rules that enforce stylistic preferences. If you have a strong preference for such a change, you can always copy the existing rule into a custom rule and make it behave the way you want.
