### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by om-mani-padme-hum** [eslint/eslint#15382]
### Environment

Node version: 14.16.1
npm version: 7.20.3
Local ESLint version: v7.24.0
Global ESLint version: v7.24.0
Operating System: Windows

### What parser are you using?

Default (Espree)

### What did you do?

```js
fileName.match(new RegExp(`^${itemNumber}.*\.xml`)); // Results in no-useless-escape for the escaped period
```

### What did you expect to happen?

I want to match a literal period, not any character like the unescaped . would match.  It is not a useless escape

### What actually happened?

error Unnecessary escape character: \.  no-useless-escape

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @om-mani-padme-hum, thanks for the issue!

> ```js
> fileName.match(new RegExp(`^${itemNumber}.*\.xml`)); // Results in no-useless-escape for the escaped period
> ```

This works as intended. `\.` is escaped dot in the template literal, and it evaluates to `.`, so it is a useless escape.

```js
`\.` === `.`; // true
```

In the regex pattern, it will match any character:

```js
const itemNumber = 1;
const fileName = "1fooxml"; // does not end with .xml

fileName.match(new RegExp(`^${itemNumber}.*\.xml`)); // [ '1fooxml', index: 0, input: '1fooxml', groups: undefined ]
```

If you want escaped dot in the pattern, then you need to escape `\` in the template literal:

```js
const itemNumber = 1;
const fileName1 = "1fooxml"; // does not end with .xml
const fileName2 = "1foo.xml"; // does end with .xml

fileName1.match(new RegExp(`^${itemNumber}.*\\.xml`)); // null
fileName2.match(new RegExp(`^${itemNumber}.*\\.xml`)); // ['1foo.xml', index: 0, input: '1foo.xml', groups: undefined]


```

**Comment by om-mani-padme-hum** [comment]
That explains it, sorry to bother you with a non-issue!  Thanks
