### ISSUE TITLE
Bug:  Conflict with VSCode's autoImport

### ISSUE THREAD

**Issue by YangChen00** [eslint/eslint#15398]
### Environment

Node version: v15
npm version:  v6
Local ESLint version: v7.8.1
Global ESLint version: none
Operating System: MacOS

### What parser are you using?

@typescript-eslint/parser

### What did you do?

please see this issues

https://github.com/microsoft/vscode/issues/137930

### What did you expect to happen?

works fine in VSCode without reporting errors

### What actually happened?

![image](https://user-images.githubusercontent.com/94821645/144951977-1e419f62-d818-40d3-b6a6-0e89216bd39d.png)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
it was reported by eslint-plugin-import, which is not maintained by the eslint team.

please read its docs: https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md, and file an issue in that repo if you think it's a bug.
