### ISSUE TITLE
Bug: Basic config reports "Oops! Something went wrong! :("

### ISSUE THREAD

**Issue by wbt** [eslint/eslint#15407]
### Environment

Node version: 16.10.0
npm version: 7.24.0
Local ESLint version: 8.4.1
Global ESLint version: N/A
Operating System: Windows 10 Pro

### What parser are you using?

Default (Espree)

### What did you do?

In an empty folder, I ran `npm init` to completion followed by `npm i eslint --save-dev` (which succeeded) and then `./node_modules/.bin/eslint --init` per basic instructions at https://www.npmjs.com/package/eslint. 

### What did you expect to happen?

An ESlint configuration file to be generated.

### What actually happened?

Log of interaction:
./node_modules/.bin/eslint --init
√ How would you like to use ESLint? · style
√ What type of modules does your project use? · esm
√ Which framework does your project use? · none
√ Does your project use TypeScript? · No / Yes
√ Where does your code run? · browser, node
√ How would you like to define a style for your project? · guide
√ Which style guide do you want to follow? · xo
√ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-xo@latest

Oops! Something went wrong! :(

ESLint: 8.4.1

SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.fetchPeerDependencies (path\to\project\node_modules\eslint\lib\init\npm-utils.js:82:17)
    at getPeerDependencies (path\to\project\node_modules\eslint\lib\init\config-initializer.js:95:27)
    at getModulesList (path\to\project\node_modules\eslint\lib\init\config-initializer.js:132:17)
    at path\to\project\node_modules\eslint\lib\init\config-initializer.js:637:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (path\to\project\node_modules\eslint\bin\eslint.js:127:9)
    
 I got the same results when choosing "JSON" at the last prompt.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is an MVCE with it not working out of the box as documented.

**Comment by aladdin-add** [comment]
**Note:** `--init` assumes you have a `package.json` file already. If you don't, make sure to run `npm init` or `yarn init` beforehand.

**Comment by wbt** [comment]
I do have the package.json already, as `npm init` is the only thing preceding this step in the MVCE.

**Comment by aladdin-add** [comment]
Ops, sorry I misread the error. Looks like there is something wrong in the fetched text from npm. will try to repro it later.

**Comment by aladdin-add** [comment]
it turns out the `npm show --json` output is not a valid json on windows.
OS: windows 11
Node: v17.2.0
npm: v8.2.0

![image](https://user-images.githubusercontent.com/13050025/145447035-0ebd2f24-cbda-4371-a655-45230078388f.png)

**Comment by aladdin-add** [comment]
emm.. I was not able to repro(). can you log the `` in this line to see what's the fetched text?
https://github.com/eslint/eslint/blob/74cf0a040e1a83990d8d7eb57e1f5ce919a11ebe/lib/init/npm-utils.js#L80-L82

**Comment by wbt** [comment]
Yes, this sheds more light on it.  fetchedText is `Sorry, there's a problem with nodist. Couldn't resolve npm version spec 7.24.0` : Couldn't find any matching version'  which seems to clearly relate to my use of [nodist](https://github.com/nullivex/nodist).  When I run `npm show --json eslint-config-xo@latest peerDependencies` directly on the command line, I get the expected:   
>{
       "eslint": ">=7.20.0"
}

When I convert the `cross-spawn` call over to using Node's `child_process.spawnSync` it's the same result.  When I run 'npm -v' from the command line I get 7.24.0 so that version of npm is clearly in use, but somehow not available to spawn.sync. I created the issue linked just above on nodist to see if folks there have any ideas.

**Comment by nzakas** [comment]
Closing, as this isn’t related to a bug in ESLint.
