### ISSUE TITLE
Change Request: Require that rule export defines configuration defaults

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#15428]
### ESLint version

next major

### What problem do you want to solve?

Currently, it is impossible to automate tracking of breaking changes because of changing defaults.

A very simple fix to this would be requiring rule authors to export the default configuration of the plugin in addition to schema.

### What do you think is the correct solution?

A `defaultConfiguration` property mandated in plugin export, e.g.

```js
module.exports = {
  create,
  meta: {
    defaultConfiguration: {
      sortCharacterClasses: true,
    },
    docs: {
      description:
        "Improve regexes by making them shorter, consistent, and safer.",
    },
    fixable: "code",
    messages,
    schema: [
      {
        additionalProperties: false,
        properties: {
          sortCharacterClasses: {
            type: "boolean",
          },
        },
        type: "object",
      },
    ],
    type: "suggestion",
  },
};


```

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by bmish** [comment]
The schema can already include default values for options. I'm also interested in detected breaking changes, but it seems we can do that by checking if the schema changes.

**Comment by gajus** [comment]
Sometimes it does, sometimes it does not. Sometimes schema is `oneOf`, and then there cannot be a default.

This is advocating for adding a simple to interpret default configuration object.

**Comment by bmish** [comment]
Fair point.

Just to play devil's advocate:
* Changes to default option values is only one way in which breaking changes can be in introduced to rules. Obviously, many other code changes can cause breaking changes and we can't detect which actually do. Is it worth the added rule API surface area when this still won't completely solve the problem?
* `defaultConfiguration` could become a maintenance burden? Have to remember to keep it up-to-date, in sync with schema changes, make sure the rule actually respects the default values from it, etc.

**Comment by gajus** [comment]
> defaultConfiguration could become a maintenance burden? Have to remember to keep it up-to-date, in sync with schema changes, make sure the rule actually respects the default values from it, etc.

Tests would break if `defaultConfiguration` was incompatible. This could be automated tests for all rules.

> Changes to default option values is only one way in which breaking changes can be in introduced to rules. Obviously, many other code changes can cause breaking changes and we can't detect which actually do. Is it worth the added rule API surface area when this still won't completely solve the problem?

It won't completely solve the problem, but it takes away from imperative code, closer to declarative rule definition. Declarative rules are easier to interpret, test, categorize, etc. It's the difference between reading someone's code and trying to figure out how defaults are derived (which are sometimes in schema, sometimes in code), and reading a simple export interface.

**Comment by gajus** [comment]
To give context over where this cropped up: I was generating documentation highlighting differences between various ESLint configurations –

https://github.com/gajus/eslint-config-canonical#incompatible-rules

and as I was doing this I realized that the reason some rules are flagged as having different configuration is because `eslint-config-canonical` explicitly provides default values and other config authors do not, i.e. I needed to somehow identify what are the default variables of the rules in order to have a fair comparison.

I looked at the exported schema, but most do not provide default values.

Admittedly, this is an edge case (useful mostly for config maintainers), but it highlighted an opportunity to improve the API.

> We would be automatically preventing the use of older, still functional yet not maintained plugin rules.

This argument applies to any breaking change.

> There are some rules that don’t have logical defaults, like no-restricted-syntax. What would we do for that?

Empty object.

> There will likely be duplication of information from the schema, where defaults can already be set. This seems like an annoyance to rule developers.

We could discourage adding this information to schema.

**Comment by gajus** [comment]
> If a default configuration is present, how will that help track breaking changes?

If any of the values change in the default config, it would signal a breaking change.

> What is responsible for reading that information and determining that it’s breaking? What so the behavior when a breaking change is detected?

I view this as an opportunity to hint rule developers that if there is a commit that changes default settings, then it should be treated as a breaking change. When it is declarative setting, it is easier to detect such change than if it is hidden in schema or implementation of a rule.

That being said, the more I talk about this, the more this feels like a nice to have with a risk of duplicating information. There is no good way to force someone to use `defaultSettings` either, they could still add some to `defaultSettings` and others hidden in implementation, which would make it even worse.

I am leaning towards not further pursuing this suggestion, but if others come up with better arguments, would be open to continue exploring.

Thank you all for contributing your thoughts.

**Comment by bmish** [comment]
@gajus thanks for sharing this suggestion and helping us understand it as well as its pros and cons. I share your interests in detecting breaking changes and looking for opportunities to make rules more declarative. Open to continued explorations in these areas.
