### ISSUE TITLE
Bug: `array-element-newline` does not work properly

### ISSUE THREAD

**Issue by thep0y** [eslint/eslint#15426]
### Environment

Node version: v14.18.1
npm version: v6.14.15
Local ESLint version: v8.4.1
Global ESLint version: Not found
Operating System: win32 10.0.22000

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": [
            "tsconfig.json"
        ]
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "plugins": [
        "eslint-plugin",
        "@typescript-eslint"
    ],
    "rules": {
        "quotes": [
            "error",
            "single"
        ],
        "comma-dangle": [
            "error",
            "never"
        ],
        "no-multiple-empty-lines": [
            "error",
            {
                "max": 2,
                "maxEOF": 0,
                "maxBOF": 0
            }
        ],
        "@typescript-eslint/no-non-null-assertion": "off",
        "array-element-newline": [
            "error",
            "never"
        ]
    }
}
```
</details>

```js
const names = ['HTML', 'Crawler'
]

const values = [
    1, 8]
```

### What did you expect to happen?

Remove line breaks between array elements

### What actually happened?

```
➜  yarn eslint .\src\test.ts
yarn run v1.22.17
warning package.json: No license field
$ ...\test.ts

...\test.ts
  11:7  warning  'names' is assigned a value but never used   @typescript-eslint/no-unused-vars
  14:7  warning  'values' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

Done in 1.83s.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snitin315** [comment]
I believe it is working as expected because it reports **only** if there is a linebreak between the elements of the array. 

```js
/*eslint array-element-newline: ["error", "never"]*/

var a = []; // ok

var c = [
  1, 2, 3, 4 // ok, since no line break between elements
];

var d = [1, 
         2, 3]; // error, linebreak after first element
```
### [See Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktZWxlbWVudC1uZXdsaW5lOiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cblxudmFyIGEgPSBbXTtcblxudmFyIGMgPSBbXG4gIDEsIDIsIDMsIDRcbl07XG5cbnZhciBkID0gWzEsIFxuICAgICAgICAgMiwgM107Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**Comment by snitin315** [comment]
Perhaps, this will be reported by [`array-bracket-newline`](https://eslint.org/docs/rules/array-bracket-newline#never) rule.

```js
const names = ['HTML', 'Crawler'
]

const values = [
    1, 8]
```

### [See Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktYnJhY2tldC1uZXdsaW5lOiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cblxuY29uc3QgbmFtZXMgPSBbJ0hUTUwnLCAnQ3Jhd2xlcidcbl1cblxuY29uc3QgdmFsdWVzID0gW1xuICAgIDEsIDhdIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

**Comment by snitin315** [comment]
I think we should add these cases in the documentation of  [`array-element-newline`](https://eslint.org/docs/rules/array-element-newline), to make it more clear.

**Comment by thep0y** [comment]
> I believe it is working as expected because it reports **only** if there is a linebreak **between the elements** of the array.
> 
> ```js
> /*eslint array-element-newline: ["error", "never"]*/
> 
> var a = []; // ok
> 
> var c = [
>   1, 2, 3, 4 // ok, since no line break between elements
> ];
> 
> var d = [1, 
>          2, 3]; // error, linebreak after first element
> ```
> 
> ### [See Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktZWxlbWVudC1uZXdsaW5lOiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cblxudmFyIGEgPSBbXTtcblxudmFyIGMgPSBbXG4gIDEsIDIsIDMsIDRcbl07XG5cbnZhciBkID0gWzEsIFxuICAgICAgICAgMiwgM107Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)

You are right.
