### ISSUE TITLE
Bug: Error while runing ./node_modules/.bin/eslint \"**/*.js\"

### ISSUE THREAD

**Issue by ouafaGit** [eslint/eslint#15435]
### Environment

Node version: v12.14.1
npm version: 6.13.4
Local ESLint version: ^6.7.2
Global ESLint version: --
Operating System: Windows 10

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>I'm trying to install an existing project, I've run ``yarn install`` and when I run ``yarn run dev`` I get an error while executing the eslint command from my scripts, I've attached the list of scripts from my packages.json and the error message</summary>

```
$ ./node_modules/.bin/eslint "**/*.js"; exit 0

Oops! Something went wrong! :(

ESLint: 6.8.0.

No files matching the pattern "**/*.js;" were found.
Please check for typing mistakes in the pattern.

error Command failed with exit code 2.
```
</details>

```js
"scripts": {
    "dev": "SET NODE_ENV=development & nodemon -r esm ./src/app.js --exec \"yarn lint && node\" ",
    "lint": "./node_modules/.bin/eslint \"**/*.js\"; exit 0",
    "lint-fix": "./node_modules/.bin/eslint --fix \"**/*.js\"; exit 0",
    "test": "jest --runInBand"
  },
```

### What did you expect to happen?

I've expected to have a list of files with issues but the app should still run

### What actually happened?

I get an error and the app crash 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @ouafaGit, thanks for the issue!

> No files matching the pattern "**/*.js;" were found.
> Please check for typing mistakes in the pattern.

This doesn't seem to be a problem with ESLint. Your command runs eslint with `**/*.js;` as a command line argument, and that glob doesn't match anything (note `;` at the end).

**Comment by nzakas** [comment]
Closing due to age
