### ISSUE TITLE
Rule Change: add "block" option for implicit-arrow-linebreak rule

### ISSUE THREAD

**Issue by goodleby** [eslint/eslint#15446]
### What rule do you want to change?

implicit-arrow-linebreak

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
/* eslint implicit-arrow-linebreak: ["error", "beside"] */

(foo) =>
  bar;

(foo) =>
  (bar);

(foo) =>
  bar =>
    baz;

(foo) =>
(
  bar()
);
```

### What does the rule currently do for this code?

It gets converted to this:
```js
/* eslint implicit-arrow-linebreak: ["error", "beside"] */

(foo) => bar;

(foo) => (bar);

(foo) => bar => baz;

(foo) => (
  bar()
);
```

Which is totally fine for the current configuration.

### What will the rule do after it's changed?

It would be nice to have an option to convert it to blocks with `return` statements instead, maybe it could be called `"block", e.g.:

```js
/* eslint implicit-arrow-linebreak: ["error", "block"] */

(foo) => {
   return bar;
}

(foo) => {
   return (bar);
}

(foo) => {
   return bar => baz;
}

(foo) => {
   return (
      bar()
   );
}
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Why do I need that?

Basically, I am using Prettier, and if the line with an arrow function is too long it will simply wrap its body on the newline, e.g.:
```js
const functionWithReallyLongName = () => anotherFunctionWithReallyReallyLongName();

// Gets converted by Prettier to:
const functionWithReallyLongName = () =>
   anotherFunctionWithReallyReallyLongName();
```

And my own preference is to use block instead of implicit new line, so I would like it to be:
```js
const functionWithReallyLongName = () => {
   return anotherFunctionWithReallyReallyLongName();
}
```

### How do we implement that?

I was thinking about something like: 
- If the option `"block"` is chosen and an arrow function has an implicit newline then autofix it to block with `return`. 
- If the arrow function does not have an implicit newline then do not apply this rule.

I am new to ESLint, so I haven't ticked that I can make a PR for that, because I am not even sure that what I have described above is possible. But I will have a deeper look and might be able to make the PR for that later.

### Why ESLint?
Prettier [made it clear](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about) that they don't want to preform "Adding/removing `{}` and `return` where they are optional.". So it's not an option to ask them to fix this, that's why I am looking for ESLint rule to fix that

**Comment by mdjermanovic** [comment]
Hi @goodleby, thanks for the issue!

This looks more like an option for the [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style) rule.

However, per our rules policies (as [stated in the README](https://github.com/eslint/eslint#stylistic-rule-updates)), stylistic rules are frozen, so we won't be adding any more options to either of these two rules. You can always copy an existing rule into a custom rule and make it behave the way you want.

**Comment by lishine** [comment]
@goodleby 
did you find a solution?

**Comment by goodleby** [comment]
> @goodleby did you find a solution?

Nope, didn't find any appropriate plugin for that. I was planning on making a custom one for this specific purpose, but still didn't get around to do that. If I do that, I will post the plugin name here :)

**Comment by lishine** [comment]
Thanks :)
I started doing as well and then put it on a pause because the setup was
not straight forward.
