### ISSUE TITLE
Change Request: Add docker support

### ISSUE THREAD

**Issue by oliv3r** [eslint/eslint#15452]
### ESLint version

all

### What problem do you want to solve?

ESLint currently does not have official docker support. While it is certainly possible to build a custom container, for CI pipelines that introduces unnecessary overhead. Also it makes it impossible to do a 'quick-one-off'. e.g. while it is possible to do `eslint file.js` on a local system, if a user does not want the overhead of installing all the dependencies (npm etc) and would much prefer to use a docker container, they currently have to rely 3rd party containers.

CI systems fall into the same category, where building custom images or using 3rd party images are fine, they make it harder then it should be.

### What do you think is the correct solution?

From usability AND security point of view,  offering an official ESLint Docker container is by far the most ideal solution.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

While in terms of process, #15430 has been already closed, I believe it checks all the marks.

**Comment by nzakas** [comment]
I’m not sure I understand the use case here. Projects generally run ESLint in the same container as their project. In what situation would someone want a container that just runs ESLint and does nothing else?

What other ecosystem tools have official containers like this?

**Comment by oliv3r** [comment]
@nzakas Hey, sure, so for 'who needs this' Anybody that has a code repository containing javascript code, where the deployable is not (but even if it is) necessarily a docker container. I'd even find it odd to include eslint into my <random-js-based-app> container. Sure in a development environment it makes sense, but not in your deployable env. I suppose anything not relying on npm comes into play? Anybody that just wants to (start) writing some javascript and just wants to lint their code. Especially when doing thing with a CI pipeline, where you write individual jobs with individual responsibilities. E.g. doing a linting stage, where no other dependency is needed is not possible without this. E.g. in gitlab-CI talk:
```yaml
lint_job:
  image: "index.registry.io/u/eslint/eslint:latest"
  script:
    - eslint *.js
```

There's [shellcheck](https://github.com/koalaman/shellcheck/blob/master/Dockerfile.multi-arch), [shfmt](https://github.com/mvdan/sh/blob/master/cmd/shfmt/Dockerfile) and [hadolint](https://github.com/hadolint/hadolint/blob/master/docker/Dockerfile) of the top of my head.

But even [clamav](https://github.com/Cisco-Talos/clamav/blob/main/Dockerfile) offers it to be used in a containerized setup

And a shameless self-plug, I have a little javascript project https://gitlab.com/ci-dashboard/pipeshow that doesn't need to offer a docker container per say, but I do want to lint things in a `lint` stage of the pipeline is very much desired.

Does that offer some more insights? :)

**Comment by nzakas** [comment]
Thanks for the details. I’m not sure there’s much of a demand for the use case you’re describing. Because ESLint uses config files in a project to determine how to execute, it seems like crossing over to and from a container would be a stumbling block.

Add on top of that the extra maintenance burden of building, testing, and deploying an official image and I’m just not sure it’s worth the overhead for such a narrow use case.

@eslint/eslint-tsc what do you think?

**Comment by btmills** [comment]
As far as I'm aware, shellcheck, shfmt, and hadolint don't have plugins. Is that correct? So many ESLint users include plugins, which removes the big benefit of having a pre-build Docker image. Users would still need to run an install step inside the container before running `eslint`. They'd have to either maintain a separate dependency manifest just for ESLint and its plugins or accept redundantly installing CI-related dependencies twice - once in the ESLint container and once to run other CI tasks.

**Comment by oliv3r** [comment]
I'm not sure I completely agree with you here. If you look on [docker hub](https://hub.docker.com/search?q=eslint&type=image) we see plenty of users offering eslint containers. I think pipeline components is a common one. I think you guys are looking mostly at the big and heavy users of javascript based repo's, that very heavily rely on npm and the likes, stating that 'well basic users, well we don't care about, they are not significant enough'. Also, this repo is not dealing with that either, right? In the end, the pre-build container is just a 'packaging of' whatever you offer in this repo + whatever you offer on npm, nothing more, nothing less. I do still think it would benefit a significant amount of users.

I won't even try to go over the fact, that plugins for a linter, that's just weird :p I mean, if you have that many ways/needs for a linter, then that's just crazy :)

Yes, you won't cover EVERY use case out there, but you don't have to. I don't think pipeline components for example installs every plugin out there.

So will this be applicable to everybody? Of course not. Heavy JS apps that have special needs/special containers, they won't benefit from this.
Everybody else relying on 3rd party containers (like those from pipeline components for example) will benefit from an upstream official container.

As for the config files, I think that's moot. I think it's quite fair to store a config file. I store .shellcheckrc, .hadolint etc etc config files in my repo too.

As for maintenance + testing, as you can see in my merge request, the container is rather trivial (which is good). So now the question comes on testing the container, that should be covered with a few automated tests no?

So what's the alternative? Well people will likely keep on using 3rd party containers with all of the (security) risks of using a 3rd party repo.

As author of the initial clamav container, I can tell you that the maintainer was first against it, then understood the benefits (though argued they where probably slim) and after a year (yes the MR was open for a year :p) the code was merged with the maintainer now a heavy promoter :)

**Comment by nzakas** [comment]
Given that there are already publicly-available options on Docker Hub, and there’s not much interest from the team in moving forward here, I’d rather suggest folks use an existing solution or build their own Dockerfile that does what they need. Thanks for the suggestion.

**Comment by oliv3r** [comment]
Yeah, sure, no problem. Sad that you don't want to support all your users (especially from a security PoV) and just prefer people roll their own :(

Such is life!
