### ISSUE TITLE
Change Request: Support ESM plugins

### ISSUE THREAD

**Issue by mizdra** [eslint/eslint#15453]
### ESLint version

v8.4.1

### What problem do you want to solve?

I have implemented an eslint-plugin that relies on a 3rd-party npm package. Using a 3rd-party npm package allows me to reuse existing assets and develop an eslint-plugin quickly.

On the other hand, there is an increasing number of pure ESM npm packages on npmjs.com. Dynamic import is the only way to import pure ESM packages from CJS ([ref](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1)). Currently, ESLint only supports eslint-plugin in CJS format and does not allow async plugins, making it virtually impossible to use Pure ESM packages with eslint-plugin (ref: #15394).

```console
> yarn add -D git://github.com/mizdra/eslint-plugin-layout-shift.git#2a97ffba28749d0311f068f2eacd96180686bf40
> yarn run lint:eslint
yarn run v1.22.15
$ eslint .

Oops! Something went wrong! :(

ESLint: 8.4.1

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@mizdra/eslint-plugin-layout-shift/lib/index.js from /Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of index.js in /Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
    at ConfigArrayFactory._loadPlugin (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3342:42)
    at /Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3214:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3210:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3031:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2817:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3772:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3693:18)
    at FileEnumerator._iterateFilesRecursive (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/lib/cli-engine/file-enumerator.js:482:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/lib/cli-engine/file-enumerator.js:297:49)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/lib/cli-engine/cli-engine.js:778:48)
    at ESLint.lintFiles (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/lib/eslint/eslint.js:559:23)
    at Object.execute (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/lib/cli.js:301:36)
    at main (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/bin/eslint.js:132:52)
    at Object.<anonymous> (/Users/mizdra/src/github.com/mizdra/scrapbox-userscript-icon-suggestion/node_modules/eslint/bin/eslint.js:136:2)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What do you think is the correct solution?

I would like to see ESLint support the eslint-plugin for ESM. This will allow us to import Pure ESM packages from eslint-plugin with an import statement.

Internally, we need a mechanism to switch the import method depending on whether eslint-plugin is CJS or ESM. Jest's implementation of switching the import method for `jest.config.js` (in `pkg.type == 'module'`) / `jest.config.cjs` may be helpful ([ref1](https://github.com/facebook/jest/blob/4113c1d6741d802292f424711a0d114a5f332a9a/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L37), [ref2](https://github.com/facebook/jest/blob/3a85065fe5604655e1337ffc1631f9999722c821/packages/jest-util/src/requireOrImportModule.ts#L23-L34)).

Here are the lines that need to be changed:

- https://github.com/eslint/eslintrc/blob/731fa4993e3b37d703cf2ba4f03429f89ae6e0a2/lib/config-array-factory.js#L1040

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

- Does eslint/eslintrc allow asynchronous code in the first place?
  - I didn't understand it. Is this feature difficult to implement for the same reason as #15394?
- This feature is related to #15394
  - #15394 also allows ESM import with eslint-plugin (or rule)
- This feature may also be related to #14139

**Comment by ljharb** [comment]
The quite small number of packages that have gone ESM-only are user-hostile, and should be replaced with more friendly ones.

It's fine if eslint decides to support ESM plugins, but I don't think that's a compelling reason to do so.

**Comment by mizdra** [comment]
Oh, I should certainly make a distinction on that issue. I apologize for that.

**Comment by brettz9** [comment]
> The quite small number of packages that have gone ESM-only are user-hostile, and should be replaced with more friendly ones.

That strikes me as a rather sharp judgment.

As a user of such packages, I don't find them hostile and in fact welcome them pushing us toward being able to enjoy the benefits of ESM-only packages (fewer build requirements, uniform standard syntax, cross-environment support). Yes, some of the benefits I mention can be delivered by hybrid packages, but even if ESM is used in source, many packages don't provide an ESM distribution, forcing one to build one's own.

Voluntary standards, like how metric system legislation was passed in the U.S., does not conduce to transitioning, as people feel no pressure to update.

This is one Bandaid that, imho, needs to be ripped off, and I personally would support our own eventual move to such a package format (in addition to supporting ESM plugins).

**Comment by ljharb** [comment]
It is a sharp judgement - because what to you is a welcome change is to me and many others a unwelcome one. When something isn’t universally welcomed, then *no matter the improvement if the change is forced*, it is wrong to force it.

**Comment by brettz9** [comment]
Yes, it may be unwelcome by some, but it doesn't mean it follows that it is wrong. Browsers force changes all the time, the whole idea of semver allows for breaking changes (which are also typically not welcomed either but are also "forced"). One can debate the merits of forcing in a given case, whether it can at all be avoided, or debate the timescale of forcing, but barring all "forcing" is not consistent with the needs of reality and progress.

**Comment by mizdra** [comment]
Thank you all for your comments. I'm glad you are taking this issue seriously. It seems to me that both sides are right and that people have different opinions and ideas. This is a complex issue.

In my personal opinion, I think the Pure ESM package is user-hostile. In most cases a user can import a package by converting user code to ESM or by dynamically importing the package from CJS, but in some cases, such as https://github.com/eslint/eslint/issues/15453#issue-1088450248, it is not possible. In other words, the Pure ESM package limits the user's choices and causes some problems. The packages should be hybrid in consideration of the user.

On the other hand, I find ESLint's restriction on the module format of the plugin to be user-hostile as well. Users are not allowed to use ESM and dynamic import is not allowed. This also limits the user's choices and causes some problems. The plugins should be hybrid in consideration of the user.

I think this is a compelling reason for ESLint to support ESM plugins. I'd love to hear your thoughts on this.

**Comment by ljharb** [comment]
@brettz9 its always wrong to force things on people, *even when the things are otherwise good*. It is quite consistent with the needs of reality, and progress a) isn’t, when forced, and b) isn’t the same thing as change.

**Comment by brettz9** [comment]
@ljharb I don't want to distract from the issue at hand by going too deep into such a tangent here, but I think it is a good discussion to have elsewhere.

I didn't know if this was quite relevant enough for starting something on https://github.com/eslint/eslint/discussions (being more generic of a topic than ESLint), so I added my response to https://gist.github.com/brettz9/cc0a44fd216c357a8561e5d06a114647  . Feel free to respond there if you like, but I think we ought to curtail the discussion now here.

@mizdra Thanks for your thoughts as well. I'll just briefly say that I agree that the current system here is "hostile" in a sense that id doesn't work for ESM users, but as far as the general argument against ESM-only projects, as I argue at the Gist, one could see imposing burdens on developers who wish to only continue with ESM-only support to be "hostile" to them and to the complexities it adds to future generations of developers having to maintain polyglot projects (if we have to use such language as "hostile" at all). But let's carry on that discussion elsewhere if desired. :-)

**Comment by mizdra** [comment]
It looks good to discuss it on gist! Let's move it there.

On the other hand, it would be good to continue the following discussion in this issue.

- Whether ESLint should support the ESM plugin or not.
- What are the blockers for ESM plugin support?
  - Does eslint/eslintrc allow asynchronous code in the first place? (ref: https://github.com/eslint/eslint/issues/15453#issue-1088450248)

**Comment by mdjermanovic** [comment]
The current eslintrc config system is frozen as we are working on the new flat config system (https://github.com/eslint/eslint/issues/13481).

The new config system will expect config files to load plugins instead of just specifying them by name, so I believe that ESM plugins can "just work". 

For example, if this is an ESM plugin:

```js
//------ eslint-plugin-foo (ESM) ------

export default {
    rules: {
        "my-rule": {
            create(context) {
                // rule implementation ...
            }
        }
    }
}
```

then, it can be used in ESM config files like this:

```js
//------ eslint.config.js (ESM) ------

import foo from "eslint-plugin-foo";

export default [{
    plugins: {
        foo
    },
    rules: {
        "foo/my-rule": "error"
    }
}];
```

and a bit more complicated in CJS config files, like this:

```js
//------ eslint.config.js (CJS) ------

module.exports = async () => [{
    plugins: {
        foo: (await import("eslint-plugin-foo")).default
    },
    rules: {
        "foo/my-rule": "error"
    }
}];
```

**Comment by mizdra** [comment]
Wow! I tried it, and it worked! Thank you.

**Comment by mizdra** [comment]
https://github.com/eslint/eslint/issues/15453#issuecomment-1001200953 reveals that the ESM plugin is already supported.

Therefore, this issue seems to have been resolved. If there are no objections, I'll close it.

On the other hand, adding a description of this technique to the documentation might help a lot of people. I'll open the issue to add the documentation later. If there is anything else I should do, please tell me.

**Comment by mizdra** [comment]
Incidentally, should we open an issue to support loading the ESM plugin by name? According to @mdjermanovic, eslintrc config system is frozen, so maybe it shouldn't be opened?

**Comment by nzakas** [comment]
Yes, the current config system is frozen. It doesn’t make sense to open any further issues for config changes until the new config system is available for testing (you may be requesting something that already works).

As best I can tell from my prototype, ESM should “just work” as expected in the new config system. Hopefully we will have a developer preview available in the next couple of months.

**Comment by mdjermanovic** [comment]
> [#15453 (comment)](https://github.com/eslint/eslint/issues/15453#issuecomment-1001200953) reveals that the ESM plugin is already supported.
> 
> Therefore, this issue seems to have been resolved. If there are no objections, I'll close it.
> 
> On the other hand, adding a description of this technique to the documentation might help a lot of people. If you think it would be a good idea to open the issue to add documentation, please tell me.

To clarify, the current version of ESLint does not support ESM plugins because the current config system does not support them. We think the new config system will support ESM plugins, but the new config system is still a work in progress (#13481), so the earliest version where ESM plugins may be supported is ESLint v9.

**Comment by mizdra** [comment]
Oh. I was using the `plugins` field of `ESLint` class to load plugins ([ref](https://github.com/mizdra/eslint-interactive/pull/104/commits/ff84b144526af11b6b78ed9999228d85fd55d7e0#diff-033ecd338eec0994fe53c0896219baee901e20068b8fbe6259a23d5759584b06R148-R154)), and it was working in ESLint v8. So I thought that this issue was already resolved in v8.

However, the `plugins` field of `ESLint` class and the `plugins` field of eslintrc are not the same thing. The former can load plugins by value in v8, but the latter cannot yet. I'm sorry to have caused confusion.
