### ISSUE TITLE
Change Request: Add `lintText` cache support

### ISSUE THREAD

**Issue by aaronadamsCA** [eslint/eslint#15463]
### ESLint version

8.5.0

### What problem do you want to solve?

IDE linting can be very slow, especially in larger projects. This is because they use [`eslint.lintText`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintlinttextcode-options) which, according to the docs, doesn't use the cache even with `cache: true`:

> The `eslint.lintText()` method doesn't use caches even if you pass the `options.filePath` to the method.

### What do you think is the correct solution?

I think (probably read-only) cache support in `lintText` would make a lot of sense here, and could greatly improve the IDE performance of ESLint. As long as the existing cache invalidation paths work correctly, it seems like a safe enough idea? But I wasn't able to find any prior discussions on the topic.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. I’m guessing there’s a reason we don’t support caching in this case, but it will probably take some digging to figure it out. I’m not opposed to the idea, I’d just want to make sure we know why we aren’t already doing it before we make such a change.

This would end up being a breaking change, though, so we would need to wait for the next major version before releasing it.

**Comment by nzakas** [comment]
@eslint/eslint-tsc any thoughts on this?

**Comment by mdjermanovic** [comment]
> I think (probably read-only) cache support in `lintText` would make a lot of sense here, and could greatly improve the IDE performance of ESLint.

Can you provide more details on your expectations for performance improvements? In particular, in which scenarios would ESLint use cache instead of linting? When opening a file in IDE, its content is possibly the same as the content for which the cache was stored, so that's one case where the cache may be used. However, while you type the content is changing so there's no valid cache available for the new content.

**Comment by aaronadamsCA** [comment]
Sure thing. Looking at our codebase, here are the CLI run times I see for `eslint --cache .`:

1. After deleting the cache file: **60 seconds**.
2. After editing a string in a "leaf node" (a file that isn't imported anywhere else): **20 seconds**.
3. After editing a string much deeper inside our codebase: **30 seconds**.

Naively, then, if `lintText` could read from the same cache that's speeding up runs 2 and 3, I'd think it could potentially gain some of the same performance benefits.

**Comment by nzakas** [comment]
> Naively, then, if lintText could read from the same cache that's speeding up runs 2 and 3, I'd think it could potentially gain some of the same performance benefits.

Would you be willing to put together a perf test to prove this out?

Also, do you expect the main use case to be IDEs? In that case, I’d expect a negligible difference, if any. The speed of the cache is related to skipping the linting of unchanged files, but presumably you always want to lint the text you’re viewing.

**Comment by nzakas** [comment]
Closing due to age.
