### ISSUE TITLE
Bug: run "yarn run eslint --init" returns "Oops! Something went wrong!"

### ISSUE THREAD

**Issue by lvqq** [eslint/eslint#15464]
### Environment

Node version:  v.12.22.8
npm version:  v6.14.15
Local ESLint version:  v8.5.0
Global ESLint version:  N/A
Operating System: macOS

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
</details>

```js
How would you like to use ESLint? · style
✔ What type of modules does your project use? · commonjs
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · node✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · airbnb
✔ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-airbnb-base@latest
The config that you've selected requires the following dependencies:

eslint-config-airbnb-base@latest eslint@^7.32.0 || ^8.2.0 eslint-plugin-import@^2.25.2
✔ Would you like to install them now with npm? · No / Yes
```

After choose js config file, select aribnb and not install right now, eslint throw an error with:
```
Oops! Something went wrong! :(

ESLint: 8.5.0

ESLint couldn't find the config "airbnb-base" to extend from. Please check that the name of the config is correct.

The config "airbnb-base" was referenced from the config file in "".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And if I choose yarm or json config file, it works fine

### What did you expect to happen?

There is no error

### What actually happened?

I get "Oops! Something went wrong!"

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by btmills** [comment]
@lvqq you said in your steps that you chose not to install dependencies yet. Did you install them later? If you haven't installed the airbnb config yet, ESLint wouldn't be able to find it.

**Comment by lvqq** [comment]
@btmills I know. But the `Oops! Something went wrong!` came up after `eslint --init`.  It doesn't seem to matter if dependencies is installed or not later. By the way, I chose yaml or json file and got successful message. Only js file occurred this problem but the file `.eslintrc.js` was created normally. I just want to report the error message I met if it was an real bug.

**Comment by lvqq** [comment]
And I debug in eslint source code. I found `writeJSConfigFile` function would always create an instance of class `CLIEngine`, which would do some config checks like extend was installed or not. But if user chose not to install, then it would throw an error. I think checking whether dependencies have been installed is not needed under this case. I will be glad to fix the minor problem if necessary and you can give me some advise. Thanks~

![image](https://user-images.githubusercontent.com/29809148/147730030-7a92e7bf-f51a-4477-aa2a-46e24472dc51.png)

**Comment by aladdin-add** [comment]
we are working on a new cli `@eslint/create-config`. can you please try it `npm init @eslint/config` to see if it has been fixed?

**Comment by lvqq** [comment]
@aladdin-add I use `npm init @eslint/create-config` and get the same error message. Worsely, it comes up with an `UnhandledPromiseRejectionWarning: Unhandled promise rejection`. Maybe you should add an process's unhandledRejection event listener. I can't find the source code in github. That's all the information I can give you.

**Comment by aladdin-add** [comment]
@lvqq  thanks for the feedback! I think we can just skip the step when users choose not to install the deps, will try to fix it in the new package.

**Comment by aladdin-add** [comment]
closing, as it should have been fixed in https://github.com/eslint/create-config/commit/da0fcbb760c21a75c530d70391211a80c85a7d60.  Please feel free to reopen if it still happens. :)
