### ISSUE TITLE
remove global-install eslint in cli docs

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#15498]
### ESLint version

main

### What problem do you want to solve?

https://github.com/eslint/eslint/blob/main/docs/user-guide/command-line-interface.md#command-line-interface

In general we should not recommend global-usage.

### What do you think is the correct solution?

just remove the first para, and add a link to [getting-started.md#installation-and-usage](https://github.com/eslint/eslint/blob/main/docs/user-guide/getting-started.md#installation-and-usage). thoughts?

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
PR https://github.com/eslint/eslint/pull/15513
