### ISSUE TITLE
ESLint interpreting `.ts` config file as YAML causing YAMLException

### ISSUE THREAD

**Issue by theoavoyne** [eslint/eslint#15499]
### Environment

Node version: `v16.13.0`
npm version: N/A
Local ESLint version: `v8.6.0`
Global ESLint version: None
Operating System: MacOS Monterey

### What parser are you using?

Default (Espree)

### What did you do?

I'm trying to use `@babel/register` in order for ESLint to be able to load config files written in TypeScript.

Here's a minimal example:
```js
// ./.eslintrc.js

require("@babel/register")({
  extensions: [".ts"],
  plugins: ["add-module-exports"],
  presets: [
    [
      "@babel/preset-env",
      { 
        targets: { node: "12.22" },
      },
    ],
    "@babel/preset-typescript",
  ],
});

module.exports = {
  extends: "./my-config.ts",
};
```
```js
// ./my-config.ts

export default {
  extends: "blabla"
};
```

### What did you expect to happen?

I expect ESLint to be able to load the resulting transpiled config.

### What actually happened?

```
YAMLException: Cannot read config file: /Users/blackjelly/code/eslint-test/my-config.ts
Error: end of the stream or a document separator is expected (2:10)

 1 | export default {
 2 |   extends: ["bla"],
--------------^
 3 | };
```

There are actually two problems here.

First, we can see that the code hasn't been transpiled, i.e. the `export default` syntax hasn't been transformed to a `module.exports` one, as we might have expected. So I guess my question is: is there any way to make ESLint work with `@babel/register` in order to do that?

The second problem is that ESLint is trying to parse TS code as if it was YAML. My guess is that ESLint defaults to YAML when encountering an extension it doesn't know (here `.ts`). Is there any way to make it default to JS?

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

The `@babel/register` itself code is not responsible for the above error. The same error occurs when removing it. I added it to this example just so you understand what I'm trying to achieve.

**Comment by aladdin-add** [comment]
related discussion: https://github.com/eslint/eslint/issues/12078

The legacy config eslintrc are frozen, we will not change it. I think it will be just working in [the new coming config](https://github.com/eslint/eslint/issues/13481), while it's still wip.

**Comment by theoavoyne** [comment]
Thank you, @aladdin-add.

Yes indeed, the discussion is related. Though here I’m not expecting ESLint to natively support TS, just to interpret files with`.ts` extensions (which contain just valid JS since they were transpiled) as JS and not YAML.

You’re right, this problem will probably be solved by v9 which will, it seems, give back power to the user in the resolution of config files, which is great BTW 👌

Any idea of how I might tackle this in the meantime?

**Comment by nzakas** [comment]
Closing, as ESLint doesn't natively support TypeScript files.

**Comment by theoavoyne** [comment]
@nzakas I haven't said that I'm expecting ESLint to support TS natively. I'm using `@babel/register` for that purpose, i.e. to transpile TS to JS. So, in the end, ESLint is not supposed to encounter a single line of TS. The only problem is that ESLint doesn't recognise the extension. Again, I know ESLint doesn't support TS natively, and this isn't what I'm requesting. It's just too bad that we can't use a tool like `@babel/register` which was built just to fix problems like that just because ESLint interprets `.ts` extension as `YAML`.
