### ISSUE TITLE
Module parse failed: Identifier directly after number

### ISSUE THREAD

**Issue by JeffML** [eslint/eslint#15511]
### Syntax name

BigInt literals with underscore

### Syntax proposal URL

Best explained with code:

```
let a = 100_000    //works; integer literal with underscore separator
let b = 100000n    //works; big int literal
let c = 100_000n  // fails; big int literal with underscore separator
```
The last line returns: 

> Module parse failed: Identifier directly after number
> File was processed with these loaders:
>  * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
>  * ./node_modules/react-scripts/node_modules/eslint-loader/dist/cjs.js
> You may need an additional loader to handle the result of these loaders.

### Example code

```js
// show above
```

### Implementation Checklist

- [ ] Ecma262 update: 
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [ ] `eslint` update: 

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

I have my eslintrc.js set to 

```
module.exports = {
    "env": {
        "browser": true,
        "commonjs": true,
        "es2020": true,
        "node": true
    },
    "extends": ["eslint:recommended", "plugin:react/recommended"],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2020,
        "sourceType": "module",   
     },
    "plugins": [
        "react"
    ],
    // "rules": {
    //   ""
    // }
};
```

**Comment by aladdin-add** [comment]
Hi, it's not clear to me. If you are reporting a bug, please fill the bug-report template: https://github.com/eslint/eslint/issues/new?assignees=&labels=bug%2Crepro%3Aneeded&template=bug-report.yml&title=Bug%3A+%28fill+in%29
