### ISSUE TITLE
Rule Change: don't prefer const on exports

### ISSUE THREAD

**Issue by jimmywarting** [eslint/eslint#15527]
### What rule do you want to change?

prefer-const

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
when i explicitly use `let` in a `export` declaration:


export let Promise = Bluebird

... Then I want to allow users to have a choice to change it to native promises if they prefer.
```

### What does the rule currently do for this code?

an autofix on `export let Promise = Bluebird` changes it to `export const Promise = Bluebird`
this isn't what i want...

### What will the rule do after it's changed?

I don't want the prefer-const to apply to export syntax, only internal code...

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
Hi @jimmywarting, thanks for the issue!

> ```js
> when i explicitly use `let` in a `export` declaration:
> 
> 
> export let Promise = Bluebird
> 
> ... Then I want to allow users to have a choice to change it to native promises if they prefer.
> ```

How can users change it? Imports are read-only, so if the variable isn't reassigned in the same module where it is declared, then there doesn't seem to be a reason to declare it with `let`.

**Comment by jimmywarting** [comment]
oh, my bad, mixup with how it was compiled to cjs
