### ISSUE TITLE
Change Request: noInlineConfig that only blocks blanket disable directives

### ISSUE THREAD

**Issue by silverlyra** [eslint/eslint#15537]
### ESLint version

v8.2.0

### What problem do you want to solve?

ESLint currently has a `noInlineConfig` option and `--no-inline-config` flag that prevents source files from using any [inline configuration comments](https://eslint.org/docs/user-guide/command-line-interface#inline-configuration-comments).

This only provides a binary choice: either all inline directives are allowed, or none of them are.

### What do you think is the correct solution?

I’d like ESLint to let me disable only the inline directives that I think are problematic for maintainability.

I only want to disallow `eslint-disable` comments that do not include the specific rule(s) they are disabling. Sometimes in our code it is useful to disable a lint error for a particular file or line, but we’ve got a number of comments that are just `// eslint-disable-line`. If any other lint issues apply to that line (now or in the future) beyond the one the author wanted to suppress, those will end up disabled as well.

I only want to allow `disable` comments that disable individual named rule(s), but can’t find a way to do so today.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I apologize if there’s a rule available that already does this; I found it hard to search for without just getting results about using `eslint-disable` to disable rules 😄.

**Comment by nzakas** [comment]
There is a plugin that has what you’re looking for:
https://www.npmjs.com/package/eslint-plugin-eslint-comments

Will that do the trick?

**Comment by silverlyra** [comment]
Ah yes! `eslint-comments/no-unlimited-disable` is exactly what I was looking for. Thank you!
