### ISSUE TITLE
Rule Change: multiline-comment-style allow disabling auto-fix

### ISSUE THREAD

**Issue by binary64** [eslint/eslint#15536]
### What rule do you want to change?

multiline-comment-style

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
// export const one = ""
// export const two = ""
```

### What does the rule currently do for this code?

It currently autofixes it into
```
/**
 * export const one = ""
 * export const two = ""
 */
```
which is the point of the plugin

### What will the rule do after it's changed?

However, I have a more advanced request: I also use the `etc/no-commented-out-code` rule which works great, but its warning gets lost because this plugin autofixes too eagerly for my use-case.

It would be great to either opt-out of the autofixer routine for your plugin only, or have your plugin smartly disable autofix when the above rule is being emitted.

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

I appriciate all the work you guys do.

**Comment by nzakas** [comment]
Thanks for the suggestion. Unfortunately, we can’t implement autofix for this rule because there’s no way to tell what the correct fix. For example, if someone commented out several lines of code, they wouldn’t want that fixed into a multi line comment.

**Comment by binary64** [comment]
Could an all-or-nothing approach work here? `['error', { skipFix: true }]`
