### ISSUE TITLE
Bug: OOM exception with large files in repo

### ISSUE THREAD

**Issue by Nokel81** [eslint/eslint#15542]
### Environment

Node version: 14.18.3 (tested also with 14.17.5)
npm version: v6.14.15
Local ESLint version: 7.32.0 (tested also with 8.3.0)
Global ESLint version: N/A
Operating System: macOS 10.15.7

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  extends: [
    "eslint:recommended",
  ],
}
```
</details>

```js
console.log("foobar");
```

### What did you expect to happen?

Eslint to work correctly

### What actually happened?

I had a bunch of large `.tgz` files and other build artifacts in my repo and I constantly got OOM errors. If I used `NODE_OPTIONS="--max-old-space-size=4096" npm run eslint --ext js,ts,tsx --max-warnings=0 .` then it would take >500s to complete.

I eventually tried cleaning up all of the build artifacts and then when I ran `npm run eslint --ext js,ts,tsx --max-warnings=0 .` it only took ~30s.

What is very strange is that it shouldn't have even been reading the `.tgz` files.

```
<--- Last few GCs --->

[67263:0x108008000]    51657 ms: Scavenge (reduce) 2091.4 (2100.9) -> 2091.2 (2102.2) MB, 3.4 / 0.0 ms  (average mu = 0.223, current mu = 0.122) allocation failure
[67263:0x108008000]    53784 ms: Mark-sweep (reduce) 2092.7 (2099.2) -> 2092.4 (2100.9) MB, 2120.6 / 0.0 ms  (+ 0.0 ms in 15 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2126 ms) (average mu = 0.129, current mu = 0.02

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
This might have to do with how the TypeScript plugin is behaving and not with ESLint itself. @bradzacher thoughts?

**Comment by bradzacher** [comment]
It's hard to tell much of anything without more information.
@Nokel81 - if you can provide a complete repro, then we might be able to look into this. As it stands though the issue report is not complete enough to be reproducible.

**Comment by nzakas** [comment]
No response, so closing.

**Comment by Nokel81** [comment]
Sorry, I'll try to create a smaller reproduction. I know this is still a problem since I ran into it a few days ago.

You can leave this closed until I make a repo.

**Comment by edwin177** [comment]
Also having this issue with versions:

"eslint": "8.8.0",
"@typescript-eslint/parser": "5.18.0",

Will see if I can come up with a simple repro.
