### ISSUE TITLE
Change Request: Enable typechecking

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#15559]
### ESLint version

v8.8.0

### What problem do you want to solve?

Currently, we have loosely-defined JSDoc types, but they're for humans only. No computer reads them, so we have no idea if they're accurate.

### What do you think is the correct solution?

This is a tracking issue, but broadly speaking, for each repository in the organization, it'll probably look something like this:

1. Set up `tsc` to start checking JSDoc type annotations.
2. Gradually add new annotations and improve existing annotations, preferably with help from the community, until `tsc` is happy. This may require some refactors to make the codebase more readily typable.
3. Configure `tsc` in CI to fail the build if it's ever unhappy.
4. Ship first-party type definitions.

We dogfood ESLint's defaults, which means we need to stay with vanilla JS, so we'll use JSDoc annotations instead of TypeScript syntax extensions.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

We added this to the roadmap in the 2022-01-27 TSC meeting. Ideas and advice for the best way to approach this are welcome!

**Comment by nzakas** [comment]
We aren't going to do this until the rewrite, so closing.
