### ISSUE TITLE
Change Request: Support non-JS languages

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#15562]
### ESLint version

v8.8.0

### What problem do you want to solve?

ESLint has many of the foundational components that would allow it to lint non-JS languages, and a couple people have even experimented with doing that, going so far as to , but it's not a first class feature.

### What do you think is the correct solution?

We should enable ESLint to lint and fix non-JS syntaxes. We've already [removed](https://github.com/eslint/rfcs/pull/56) some JS-related [assumptions](https://github.com/eslint/eslint/pull/13305) from the traversal engine.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

We added this to the roadmap in the 2022-01-27 TSC meeting.

**Comment by btmills** [comment]
We've added this to the roadmap, but we don't have a point person on it yet, so I've assigned eslintbot to fend of the stale bot.

**Comment by nzakas** [comment]
Closing in favor of #16999
