### ISSUE TITLE
Change Request: deprecate [no-restricted-imports] in favor of eslint-plugin-node

### ISSUE THREAD

**Issue by c-vetter** [eslint/eslint#15586]
### ESLint version

n/a

### What problem do you want to solve?

[no-restricted-modules](https://eslint.org/docs/rules/no-restricted-modules) has been deprecated in favor of [node/no-restricted-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-restricted-require.md) in ESLint v7.0.0.

### What do you think is the correct solution?

In the same way, for consistency, it would make sense to also deprecate [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports) in favor of [node/no-restricted-import](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-restricted-import.md).

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
no-restricted-modules was deprecated because we wanted to remove all CommonJS-related functionality from the core. That’s a very different situation than no-restricted-imports so consistency isn’t a deciding factor here.

I’m not completely against the idea, but the rest of the team needs to chime in here.

**Comment by mdjermanovic** [comment]
I think `eslint-plugin-node` is primarily intended for the development of Node.js apps/tools, so it doesn't seem right to deprecate a core rule that doesn't relate to any specific environment in favor of a plugin that does relate to a specific runtime environment. Is there an equivalent rule in `eslint-plugin-import`?

**Comment by ljharb** [comment]
There is not, because it already exists in core so there was no point in adding it :-)

I suppose both rules could be added to the import plugin largely as-is, if eslint wants to deprecate them, to ensure that there's a proper place for them to live.

**Comment by mdjermanovic** [comment]
> I suppose both rules could be added to the import plugin largely as-is, if eslint wants to deprecate them, to ensure that there's a proper place for them to live.

@ljharb assuming that one rule is `no-restricted-imports`, what's the other rule that could be added to the import plugin?

**Comment by ljharb** [comment]
no-restricted-modules. I’d probably combine the implementations into a single rule.

**Comment by nzakas** [comment]
I’m still not seeing a good argument to deprecate no-restricted-imports in this thread. We get a lot of requests about this rule, so it’s clearly used a lot. At this point, deprecating the rule seems to only cause pain for users. 👎

**Comment by ljharb** [comment]
I’d certainly prefer it be a core rule :-) I’m just willing to give it a home if that ever changes.

**Comment by nzakas** [comment]
**TSC Summary:** This issue requests that we deprecated `no-restricted-imports` in favor of a plugin rule. This rule doesn't currently exist in another plugin by `eslint-plugin-import` would be willing to take it if we would like to deprecate it. We have previously deprecated `no-restricted-modules` in favor of moving it into `eslint-plugin-node` as we removed CommonJS support in the core.

**TSC Question:** Do we want to deprecate `no-restricted-imports`?

**Comment by btmills** [comment]
We appreciate the suggestion, @c-vetter! After discussing this in the most recent TSC meeting, we're not ready to deprecate this rule in core yet. If, at some point in the future, we start shifting previously core rules to plugins, `no-restricted-imports` and the other ESM-related rules would be natural candidates for that.
