### ISSUE TITLE
Change Request: auto-fix for max-let

### ISSUE THREAD

**Issue by Gentlee** [eslint/eslint#15588]
### ESLint version

8.8.0

### What problem do you want to solve?

Get rid of prettier and use only eslint.

Currently there is not auto-fix for max-len, which is very strange and forces everyone not to use this rule but to use prettier.

### What do you think is the correct solution?

Implement auto-fix for max-len rule the same way as prettier plugin does.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Without auto-fix this rule doesn't make sense and forces everyone to use prettier plugin.

**Comment by nzakas** [comment]
ESLint can’t autofix max-len because we don’t have the ability to know where line breaks make sense. You’ll still need to use prettier for this.
