### ISSUE TITLE
Bug: Environment key "es2022" is unknown with ESLint: 8.8.0

### ISSUE THREAD

**Issue by MrBokeh** [eslint/eslint#15580]
### Environment

Node version: v14.18.3
npm version: 6.14.15
Local ESLint version: v8.8.0
Global ESLint version: v8.8.0
Operating System: Windows 11 Professional

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
"env": {
    "browser": true,
    "es2022": true
  }
```
</details>

```js
npx eslint . --fix
```

### What did you expect to happen?

No error

### What actually happened?

Oops! Something went wrong! :(

ESLint: 8.8.0

Error: .eslintrc.json:
        Environment key "es2022" is unknown

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ljharb** [comment]
That's because ES2022 adds no new globals, and eslint has decided not to make a noop "env" for the years that don't add new globals. You'll need to get lucky and guess the latest year that does add new globals, and put that in your env.

**Comment by MrBokeh** [comment]
Hi @ljharb, do you know how to config ESLint to validate ES2022 code then? It is quite confusing that they announced that they are supporting ES2022 since 8.0 in June last year but not very clear on how to set it up properly if they don't support ES2022 as a global env...

**Comment by ljharb** [comment]
You set parserOptions.ecmaVersion to 2022. “env” is not the primary way to configure that.

**Comment by bricss** [comment]
> You set parserOptions.ecmaVersion to 2022. “env” is not the primary way to configure that.

It must be primary, or at least possible.
Bcos, it's very confusing and it affects **3rd-party** parsers in a very bad way, e.i.: `@babel/eslint-parser` 🥶

Usage of `parserOptions.ecmaVersion` with it will end up in **eslint** to fallback to default ECMAScript **5** spec 😑
And as result many `globals` NOT available, at all 💀

**Comment by ljharb** [comment]
Yes, the current way it works is that you always specify the ecmaVersion, and then also supply the available env keys. It works perfectly fine with Babel’s parser to do this.

**Comment by bricss** [comment]
I just clearly don't see the reason why I cannot simply add `globals.es2022 = true` and that's it 🧐
I oughta be a way to make it work, coz it's quite some confusing API.

**Comment by ljharb** [comment]
I agree it’s confusing that you have to just “know” which years add globals and which don’t - but that’s still the way it works.

**Comment by mdjermanovic** [comment]
Configuration that enables ES2022 syntax and globals is:

```js
{
   "parserOptions": {
      "ecmaVersion": 2022
   },
   "env": {
      "es2021": true
   } 
}
```

There's still no difference between ES2022 and ES2021 globals, so we haven't added `es2022` environment yet.

All available environments are listed here: https://eslint.org/docs/user-guide/configuring/language-options#specifying-environments

Currently available ES environments are: `es6`, `es2017`, `es2020`, and `es2021`.

With the new config system (https://github.com/eslint/eslint/issues/13481), there will be a single setting `languageOptions.ecmaVersion` to enable both syntax and globals (for example, `"languageOptions" :  { "ecmaVersion": 2022 }` enables ES2022 syntax and ES2022 globals). The concept of enviroments will be removed.

That said, I agree it's confusing that `es2022` and other years are missing, and I wouldn't mind adding those environments now. @eslint/eslint-tsc thoughts about this?

**Comment by ljharb** [comment]
(fwiw, I’ve asked about this before - it’s incredibly confusing that every year isn’t present - https://github.com/eslint/eslint/issues/8453#issuecomment-293727708)

**Comment by btmills** [comment]
If someone’s willing to do the work (@bricss, would you be interested?), I wouldn’t be opposed to filling in the gaps between years since they’re effectively aliases to the prior year that does contain changes. It’s reasonable to me that we’d take on the work of understanding the precise differences between each version of the standard in order to offer consumers a friendlier API.

**Comment by ljharb** [comment]
I’d be happy to make that PR; I’ll look into it tonight.

**Comment by ljharb** [comment]
Done: https://github.com/eslint/eslintrc/pull/68

**Comment by nzakas** [comment]
Fine by me. This confusion will go away with the new config system anyway.

**Comment by MrBokeh** [comment]
Thanks guys, you guys are legends!
