### ISSUE TITLE
Add ability to report dependencies for rule error

### ISSUE THREAD

**Issue by barak007** [eslint/eslint#15583]
### ESLint version

v8.8.0

### What problem do you want to solve?

Projects that implements watch mode over eslint will be able to invalidate an error. 

### What do you think is the correct solution?

Add ability to add dependency paths when reporting a lint error then other tools (ide plugins) will be able to look at this field and act (usually invalidate rule error when one of the affecting files changes).

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

This was discussed in #13570 but I feel that we missed the point there. 

Typescript eslint has horrible experience with stalemate errors all around!

**Comment by nzakas** [comment]
I’m sorry, there’s not enough information here to comment on the idea itself. 

> Add ability to add dependency paths when reporting a lint error

What is a “dependency path”? Please give some examples. And are you expecting rule authors to provide this information? Are you expecting ESLint to calculate it? Please provide as much detail as possible.

**Comment by nzakas** [comment]
Thanks, that’s helpful. To make sure I understand correctly: you’re saying that you want to pass this extra data about a dependency with a lint message, but ESLint itself would not use it? Only the process that is running ESLint would use that data?

**Comment by barak007** [comment]
Sorry for the spam but it would be nice to also hear from [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)
I'm sure that they encounter this problem.

**Comment by nzakas** [comment]
This request may be related to https://github.com/eslint/eslint/issues/14198

@btmills

**Comment by barak007** [comment]
@bradzacher maybe you can give an opinion here?

**Comment by nzakas** [comment]
@btmills still looking for thoughts from you on this. 

> This request may be related to https://github.com/eslint/eslint/issues/14198
