### ISSUE TITLE
Change Request: Increase unit test timeout in Makefile.js

### ISSUE THREAD

**Issue by piggynl** [eslint/eslint#15582]
### ESLint version

the `main` branch

### What problem do you want to solve?

Currently some unit tests timeout on slow machines, with the following output.

```
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Specifically, ~30 tests fail on both SiFive Unmatched RISC-V development board and `qemu-riscv64`.

### What do you think is the correct solution?

Increase the timeout from 10s to 60s will solve.

https://github.com/eslint/eslint/blob/355b23d0c4e050be4e53292f552a47c10ec6e00e/Makefile.js#L81-L82

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @piggynl, thanks for the issue! 

> Currently some unit tests timeout on slow machines, with the following output.
> 
> ```
> Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
> ```
> 
> Specifically, ~30 tests fail on both SiFive Unmatched RISC-V development board and `qemu-riscv64`.

Can you provide the complete output (the list of tests and hooks that are failing)?

**Comment by piggynl** [comment]
Hi @mdjermanovic,

The number of failing tests varies between 10 and 40 all the time. Here are some collected outputs:
- (18 failing) http://fars.ee/eOj-
- (25 failing) http://fars.ee/15PI
- (27 failing) http://fars.ee/UVFB
- (28 failing) http://fars.ee/amat

If you want to setup a QEMU environment same as mine, the wiki page [Setup Arch Linux RISC V Development Environment](https://github.com/felixonmars/archriscv-packages/wiki/Setup-Arch-Linux-RISC-V-development-environment) will help. You will need to run `pacman -S git nodejs npm` after the setup, then `git clone` or `node Makefile.js` as usual will be ok.

**Comment by piggynl** [comment]
Certainly, it will be great! Shall I propose a PR on it?

**Comment by mdjermanovic** [comment]
> Certainly, it will be great! Shall I propose a PR on it?

Sounds good to me, it will be easier for the team to evaluate the change on the PR.
