### ISSUE TITLE
Change Request: Update CLA info

### ISSUE THREAD

**Issue by piggynl** [eslint/eslint#15627]
### ESLint version

the `main` branch

### What problem do you want to solve?

The CLA info is confusing now.

Outdated link:

https://github.com/eslint/eslint/blob/b93af98b3c417225a027cabc964c38e779adb945/docs/developer-guide/contributing/pull-requests.md?plain=1#L9

Link points to where ["you can’t sign the CLA"](https://github.com/eslint/eslint/pull/15370#discussion_r758874388):

https://github.com/eslint/eslint/blob/b93af98b3c417225a027cabc964c38e779adb945/docs/developer-guide/contributing/README.md?plain=1#L13

### What do you think is the correct solution?

It will be better if they are rewritten like in #15370.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Thanks for finding this, a PR is welcome!
