### ISSUE TITLE
Change Request: Make sure plugins expose their working data so that developers can extend them. Use case: indent

### ISSUE THREAD

**Issue by mercmobily** [eslint/eslint#15622]
### ESLint version

v8.x.x

### What problem do you want to solve?

ESLing currently doesn't make it easier for plugin developers to extend existing rules.
For example, I want to do something very basic: I want to delete any warning/error for comments starting on column 1.

The goal is to facilitate literate code, so that [the source code](https://github.com/mobily-enterprises/data-loader/blob/main/index.js) becomes a [document](https://mobily-enterprises.github.io/data-loader/literate-code.html). When writing files like this, it makes sense to have the "writing" part unindented.

I just released this plugin that achieve exactly that:

https://github.com/mobily-enterprises/eslint-plugin-literate-comments

The code is very straightforward:

````
const indent = require('../eslint/lib/rules/indent.js')

let createWrapper = function(context) {
  const originalCreateResult = indent.create(context)
  
  const originalProgramExit = originalCreateResult['Program:exit']
  originalCreateResult['Program:exit'] = function() {
    context
    .getSourceCode()
    .getAllComments()
    .filter(comment => comment.loc.start.column === 0)
    .forEach(comment => indent.create.offsets.ignoreToken(comment))

    originalProgramExit()
  }

  return originalCreateResult
}

module.exports = {
  rules: {
      "indent": {
        create: createWrapper,
        meta: indent.meta
      }
  },
  configs: {
    recommended: {

      plugins: ['literate-comments'],

      // Rules copied from 'standard'
      rules: {
        "indent": "off",
        "literate-comments/indent": ["error", 2, {
          "SwitchCase": 1,
          (...)
          "ignoredNodes": ["TemplateLiteral *"]
        }]
      }
    }
  }
}
````

The crucial line is `.forEach(comment => indent.create.offsets.ignoreToken(comment))` -- to make that possible, I have to patch eslint's code like this:

````
#!/bin/bash

# If the file couldn't be found, then skip
# file="./indent.js" # This is for testing purposes
file="../eslint/lib/rules/indent.js"
if [ ! -f "$file" ];then
  >&2 echo "Could not find eslint's original indent.js file, this won't work"
  exit 1
fi

# If the string is not already there, apply the patch
str="module.exports.create.offsets = offsets;"
if ! grep -q "$str" $file; then
  sed -i -- "/const parameterParens = new WeakSet();/a\ \ \ \ \ \ \ \ $str" $file  
else
  echo "Original indent.js already patched. Patching was skipped"
fi
````
Which adds that `module.exports.create.offsets = offsets;` to the right spot.

Having an npm package that, on install, will patch another one is... let's just say... "less than ideal".

### What do you think is the correct solution?

Exposing the `offsets` variable is not straightforward. Other plugins I saw have similar variables lying around.

This would be trivial if ESLint rules were written as Javascript classes, since internal data would be available as `this`. However, I realise that that's not the case.

Without proposing a total revolution, exposing internal variables can be done in several ways -- and none of them is 100% ideal:

* Adding it to the `exports`. Cons: it's something "private" and yet exported. Plugins could export a `data` property which would be an object, with the plugin's internal data -- or, the ones that would make sense to access if you are trying and extend it.

* Add an object to the context that can be used for "general purpose" variables. This would be the ideal solution, but it needs to "fit" the codebase. Plugins would use `context.vars` to store things that each event would share (`context.vars.offsets` for example). While it would be an API change, `contenct.vars` would simply be an empty object for plugins without internal data.

* (Maybe there are other ways, but I can't think of any)

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I am not aware of the direction of the codebase... maybe there is work going on already fixing this issue.

The compromise I have (patching eslint) is not exactly ideal and definitely shouldn't be a pattern.

**Comment by mdjermanovic** [comment]
Hi @mercmobily, thanks for the issue! 

> ESLing currently doesn't make it easier for plugin developers to extend existing rules.

Rule implementations are not a part of the [public API](https://eslint.org/docs/developer-guide/nodejs-api), because we don't intend to maintain backwards compatibility in implementation details. 

For your use case (modifying functionality of a core rule), we recommend a copy-paste approach. You can always copy the code of a core rule into a custom rule and make it behave the way you want.

**Comment by mercmobily** [comment]
Thank you for your response. No worries at all, will leave my code as is!
