### ISSUE TITLE
Bug: Error while loading rule 'react/prefer-stateless-function': Cannot read property 'version' of null Occurred while linting

### ISSUE THREAD

**Issue by tipleavalentin** [eslint/eslint#15646]
### Environment

Node version: 16.14.0
npm version: 8.5.2
Local ESLint version: 8.9.0
Global ESLint version: -
Operating System: Windows 11 2H2...527

### What parser are you using?

@babel/eslint-parser

### What did you do?

console.log('this should get a warning');

### What did you expect to happen?

I am expecting eslint to work, throwing warnings and errors where it should.

### What actually happened?

Eslint load fails.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Error details:
[Info - 16:29:28] ESLint server is starting
[Info - 16:29:28] ESLint server running in node v14.16.0
[Info - 16:29:28] ESLint server is running.
[Info - 16:29:30] ESLint library loaded from: \node_modules\eslint\lib\api.js
[Info - 16:29:31] Error while loading rule 'react/prefer-stateless-function': Cannot read property 'version' of null Occurred while linting AnyJSFile.js

**Comment by tipleavalentin** [comment]
If I remove the rule 'react/prefer-stateless-function' then it moves to "react/no-unused-state" and so on...

**Comment by mdjermanovic** [comment]
Hi @tipleavalentin, thanks for the issue!

> [Info - 16:29:31] Error while loading rule 'react/prefer-stateless-function': Cannot read property 'version' of null Occurred while linting AnyJSFile.js

Can you please run ESLint from the command line and share the output (with the full error stack trace)?

**Comment by tipleavalentin** [comment]
> Hi @tipleavalentin, thanks for the issue!
> 
> > [Info - 16:29:31] Error while loading rule 'react/prefer-stateless-function': Cannot read property 'version' of null Occurred while linting AnyJSFile.js
> 
> Can you please run ESLint from the command line and share the output (with the full error stack trace)?

Hi! 

here it is:
$ npx eslint src_site/pages/HomePage.js

Oops! Something went wrong! :(

ESLint: 8.8.0

TypeError: Error while loading rule 'react/prefer-stateless-function': Cannot read properties of null (reading 'version')
Occurred while linting D:\project\src_site\pages\HomePage.js
    at getReactVersionFromContext (D:\project\node_modules\eslint-plugin-react\lib\util\version.js:92:81)
    at testReactVersion (D:\project\node_modules\eslint-plugin-react\lib\util\version.js:138:28)
    at usedPropTypesInstructions (D:\project\node_modules\eslint-plugin-react\lib\util\usedPropTypes.js:285:36)
    at Function.componentRule (D:\project\node_modules\eslint-plugin-react\lib\util\Components.js:1018:37)
    at createRuleListeners (D:\project\node_modules\eslint\lib\linter\linter.js:915:21)
    at D:\project\node_modules\eslint\lib\linter\linter.js:1097:31
    at Array.forEach (<anonymous>)
    at runRules (D:\project\node_modules\eslint\lib\linter\linter.js:1034:34)
    at Linter._verifyWithoutProcessors (D:\project\node_modules\eslint\lib\linter\linter.js:1382:31)
    at Linter._verifyWithConfigArray (D:\project\node_modules\eslint\lib\linter\linter.js:1722:21)

**Comment by tipleavalentin** [comment]
So it seems to be an issue on eslint-plugin-react, I'll add the issue there. :)

**Comment by tipleavalentin** [comment]
https://github.com/yannickcr/eslint-plugin-react/issues/3219
