### ISSUE TITLE
Rule Change: class-methods-use-this error message

### ISSUE THREAD

**Issue by Goufix** [eslint/eslint#15652]
### What rule do you want to change?

class-methods-use-this

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

Other

### Example code

```js
export class SomeClass {
  private name = "Any name";
 
  methodOne() { 
    return this.name
  }

  private methodTwo() {
    // Does not use 'this' keyword.
  }
}
```

### What does the rule currently do for this code?

It Just shows a not clear message: `Expected 'this' to be used by class method 'deleteMessage'`		

### What will the rule do after it's changed?

I found two possible solutions that could be either done.

- Add a clear error message.
- Implement a quick fix that adds the `static` keyword to the method

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by btmills** [comment]
Thanks for the contribution, @Goufix! Taking your two suggestions individually:

> Add a clear error message.

What about the current error message do you fund unhelpful?

> Implement a quick fix that adds the `static` keyword to the method

Since autofixes can be applied without interaction, they should always be safe. Making an instance method static can be a breaking change. I could see implementing this as an [editor suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) instead so that developers have a chance to think through the impact of such a change before applying it.

**Comment by Goufix** [comment]
> Thanks for the contribution, @Goufix! Taking your two suggestions individually:
> 
> > Add a clear error message.
> 
> What about the current error message do you fund unhelpful?
> 
> > Implement a quick fix that adds the `static` keyword to the method
> 
> Since autofixes can be applied without interaction, they should always be safe. Making an instance method static can be a breaking change. I could see implementing this as an [editor suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) instead so that developers have a chance to think through the impact of such a change before applying it.

`What about the current error message do you fund unhelpful?`
 - I think the message is not clear, it should suggest add the `static` just like the [docs](https://eslint.org/docs/rules/class-methods-use-this)

`I could see implementing this as an [editor suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) instead so that developers have a chance to think through the impact of such a change before applying it.`
LGTM

**Comment by TriMoon** [comment]
@btmills 
> > Add a clear error message.
> 
> What about the current error message do you fund unhelpful?

IMHO its obviously the bolded part in:
>Expected 'this' to be used by class method **'deleteMessage'**
(it should have mentioned the methods name) :wink:

**Comment by btmills** [comment]
Typically, we try to keep messages short enough to fit on a single line in output and reserve longer explanations for the docs. In this case, the docs are careful to mention that converting to a static method is only possible _sometimes_, and it's definitely a breaking change. That'd be a lot of nuance to include in a one-line message, so I'm :-1: to changing the error message. Most editor integrations will link directly to docs, which reduces the friction of getting to that additional context.

For the ESLint team: what do you think of adding a `class-methods-use-this` suggestion to make the method `static`? The downside is that it's a breaking change, so any suggested fix would also require manual changes elsewhere.

**Comment by mdjermanovic** [comment]
> For the ESLint team: what do you think of adding a `class-methods-use-this` suggestion to make the method `static`? The downside is that it's a breaking change, so any suggested fix would also require manual changes elsewhere.

I believe the common expectation for an action that suggests converting a method to a static method would be to automatically update all method calls as well. Since we cannot implement that, I'm not much in favor of a suggestion that just adds `static`. On the other hand, given that we'll add a general warning about suggestions (https://github.com/eslint/website/issues/899), the change is acceptable so I won't be opposed if other team members think that it would be useful.

**Comment by nzakas** [comment]
I agree that this is too much info for the message. I’m unsure about adding a suggestion to add “static” as such a change will have side effects to the caller, and while suggestions may have side effects, I’d prefer those side effects be local to the change.

**Comment by btmills** [comment]
Sounds like we have consensus that `static` as a potential solution should be left in the docs and not in the error message.

I'm also reluctant to have a suggestion that would have significant non-local side effects and don't hear anyone pushing for the suggestion.

@Goufix while we're not making any changes here, thank you for your contribution to improving ESLint for everyone!
