### ISSUE TITLE
Change Request: Built-in SARIF format support

### ISSUE THREAD

**Issue by yongyan-gh** [eslint/eslint#15656]
### ESLint version

v8.10.0

### What problem do you want to solve?

SARIF format is an [OASIS](https://www.oasis-open.org/) [approved](https://www.oasis-open.org/news/announcements/static-analysis-results-interchange-format-sarif-v2-1-0-is-approved-as-an-oasis-s) standard, it is the format used in GitHub advanced security to generate code scanning alerts for the repositories.

Now ESLint doesn't have a built-in SARIF formatter. The SARIF SDK team created a custom SARIF formatter at https://github.com/microsoft/sarif-sdk/tree/main/src/ESLint.Formatter which can be used to convert ESLint JSON output to SARIF format.

The issues in current situation:
- Customers need to install custom formatter separately in order to get SARIF output.
- SARIF formatter version falls behind latest ESLint version.

### What do you think is the correct solution?

We think it's better ESlint has its built-in SARIF format support so that:
- Customers get native SARIF output from ESLint. No custom formatter needed.
- ESLint SARIF output keeps up-to-date if any change.

We are willing to help to add the SARIF formatter in ESLint.

Please let us know what do you think about the solution.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

cc @eddynaka @michaelcfanning

**Comment by aladdin-add** [comment]
In eslint 8.0, we had removed some formatters(https://github.com/eslint/eslint/issues/14277), so I'm not sure we want to do this.

**Comment by nzakas** [comment]
Yes, in general we are moving away from having built-in formatters in the core because most people only use or two, so it doesn't make sense for us to maintain a large library. You can use [a custom formatter](https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif) instead.
