### ISSUE TITLE
Change Request: add a typedef for formatter functions

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#15654]
### ESLint version

v8.10.0

### What problem do you want to solve?

ESLint does not include a type definition for the signature of a formatter function.

A [(custom) formatter](https://eslint.org/docs/developer-guide/working-with-custom-formatters) is a plain function that accepts a list of lint results and an optional second parameter [`context`](https://eslint.org/docs/developer-guide/working-with-custom-formatters#the-context-argument) with properties `cwd` and `rulesMeta`. This would be the expected type of the default export of a formatter module (a [TypeScript example](https://github.com/sindresorhus/eslint-formatter-pretty/blob/decbd28/index.d.ts#L12-L15)).

By contrast, there exists a type [`Formatter`](https://eslint.org/docs/developer-guide/nodejs-api#-formatter-type) which is used for a different purpose: it is the type of a value resolved by `eslint.loadFormatter`. This is an object with a method named `format` that accepts a single argument.

### What do you think is the correct solution?

Adding a type definition for the signature of a formatter function would be useful as a guideline to work with custom formatters and other tools that deal with those formatters, in the same way the type definitions for e.g. `Rule` or `Plugin` help with rules and plugins.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I could submit a PR if desired, but I would probably need some input from the team, for example about naming conventions.

**Comment by btmills** [comment]
This brings us one step closer to #15559, so :+1: from me! Good research on the existing `Formatter` type. The name collision is unfortunate, but it brings up an interesting question: since the existing `Formatter` type is only used internally, could we rename it to e.g. `LoadedFormatter`, freeing up `Formatter` for the publicly-consumable type?

Question for the team: as we're working on typing ESLint's codebase as part of #15559, **are existing internal `@typedef`s stable public API?** If we renamed the existing `@typedef Formatter` below, which is only used internally, to free up the name for the type of format functions for the public API, **would that be a breaking change?**

https://github.com/eslint/eslint/blob/802c85c28283362d48d77876e924fd381a15f573/lib/eslint/eslint.js#L39-L43

**Comment by fasttime** [comment]
Thanks for the feedback @mdjermanovic. I have to say, I also call it `FormatterFunction` in my projects, because I don't know any better name. But @btmills' suggestion seems very reasonable to me. At least it would make things clearer, especially because people seem to think that the type `Formatter` is - what else? - the type of a formatter, despite the documentation making it clear that it's used for something different. I've seen this myself generating [some confusion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58761#discussioncomment-2169486) in discussions, so I guess it's not only my impression. But anyway, adding a type for a formatter with whatever name should already help disambiguating the ideas, so maybe a more conservative naming choice could be actually a good option.

**Comment by mdjermanovic** [comment]
> Perhaps we should both call the new type `FormatterFunction` and rename the existing `Formatter` type to `LoadedFormatter` to avoid any ambiguity?

Good idea :+1:

`Formatter` could be interpreted as either of those, so it seems best to remove that ambiguous name in favor of the two more concrete ones `FormatterFunction` and `LoadedFormatter`.

**Comment by nzakas** [comment]
I’m 👍 for getting more type information into the repo. What are the next steps here?

**Comment by fasttime** [comment]
If the consensus is for renaming `Formatter` to `LoadedFormatter` and calling the new type `FormatterFunction`, that would be fine. I guess this change doesn't need a RFC, right?

**Comment by fasttime** [comment]
@btmills Thanks for accepting this. Sure, I will work on a PR.
