### ISSUE TITLE
Bug: `/* eslint-enable */` wipes out previously disabled rules

### ISSUE THREAD

**Issue by dosisod** [eslint/eslint#15662]
### Environment

Node version: v17.5.0
npm version: v8.5.1
Local ESLint version: v8.10.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.16.10-arch1-1

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "camelcase": 2
    },
    "env": {}
}
```
</details>

[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50LWRpc2FibGUgY2FtZWxjYXNlICovXG5cbmNvbnN0IHhfMSA9IDE7XG5cbi8qIGVzbGludC1kaXNhYmxlICovXG4vLyBzb21lIGNvZGUgSSB3YW50IHRvIGRpc2FibGUuIHRoZSBkaXNhYmxlIGxpbmUgYWJvdmUgaXMgbm90IG5lZWRlZCB0aG91Z2hcbi8qIGVzbGludC1lbmFibGUgKi9cblxuY29uc3QgeF8yID0gMjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNhbWVsY2FzZSI6Mn0sImVudiI6e319fQ==). Copy of code in link below:

```js
/* eslint-disable camelcase */

const x_1 = 1;

/* eslint-disable */
// some code I want to disable. the disable line above is not needed though
/* eslint-enable */

const x_2 = 2;
```

### What did you expect to happen?

I expected that after adding `eslint-enable`, the same rules that where before the `eslint-disable` would still apply. The `camelcase` rule could be anything, I just chose it to illustrate the issue.

### What actually happened?

```
/home/loot/code/js/eslint/index.js
  9:7  error  Identifier 'x_2' is not in camel case  camelcase

✖ 1 problem (1 error, 0 warnings)
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Is this expected behavior? If so, there are no docs (that I could find) that explain this feature.

**Comment by mdjermanovic** [comment]
Hi @dosisod, thanks for the issue!

This works as expected. `/* eslint-disable camelcase */` disables the camelcase rule in the range that starts from that directive and ends with `/* eslint-enable camelcase */`, or `/* eslint-enable */`, or end of file, whichever comes first.

`eslint-enable` directives are not paired with previous `eslint-disable` directives. `/* eslint-enable */` (without rules specified) simply re-enables all rules, starting from that point in the code.

If you want to disable the camelcase rule for the entire file, you can also use a [rule configuration comment](https://eslint.org/docs/user-guide/configuring/rules#using-configuration-comments) `/* eslint camelcase: "off" */`

> If so, there are no docs (that I could find) that explain this feature.

Documentation for `eslint-disable` and `eslint-enable` directives is here: https://eslint.org/docs/user-guide/configuring/rules#using-configuration-comments-1

I agree that this behavior should be explained more precisely. I'm marking this issue as accepted to improve the documentation.

**Comment by snitin315** [comment]
@dosisod are you willing to send a PR to improve our docs for this case?

**Comment by dosisod** [comment]
Yes @snitin315, I would be willing to do that! I'll go ahead and write it up tomorrow.
