### ISSUE TITLE
Bug: excludedFiles in overrides do not apply some regexp pattern

### ISSUE THREAD

**Issue by blephy** [eslint/eslint#15670]
### Environment

Node version: 14.17.6
npm version: 6.14.15
Local ESLint version: 8.10.0
Global ESLint version: none
Operating System: Darwin

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
const commentsRules = require('../rules/comments');
const importRules = require('../rules/import');
const jestRules = require('../rules/jest');
const jsxA11yRules = require('../rules/jsx-a11y');
const reactRules = require('../rules/react');
const typescriptRules = require('../rules/typescript');

module.exports = {
  root: true,
  env: {
    node: true,
    browser: true,
    es2020: true,
  },
  plugins: ['import', 'unused-imports', 'jest', 'jest-formatting', 'testing-library'],
  extends: [
    'eslint:recommended',
    'airbnb',
    'airbnb/hooks',
    'airbnb-typescript',
    'plugin:json/recommended-with-comments',
    'plugin:eslint-comments/recommended',
    'plugin:promise/recommended',
    'plugin:no-unsanitized/DOM',
    'plugin:@typescript-eslint/recommended',
    'prettier',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module',
    extraFileExtensions: ['.json'],
    projectFolderIgnoreList: [
      '**/node_modules/**',
      './.github',
      './.husky',
      './.circleci',
      './stats',
      './docs',
      './documentations',
      './reports',
      './coverage',
      './build',
      './dist',
      './lib',
    ],
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    ...commentsRules,
    ...importRules,
    ...jsxA11yRules,
    ...reactRules,
    ...typescriptRules,
  },
  overrides: [
    {
      files: ['./public/locales/**/*.json'],
      extends: ['plugin:i18n-json/recommended'],
      rules: {
        'i18n-json/valid-message-syntax': [
          'error',
          {
            syntax: require.resolve('../parser/i18n/message-parser.js'),
          },
        ],
        'i18n-json/sorted-keys': [
          'error',
          {
            order: 'asc',
            indentSpaces: 2,
          },
        ],
        'i18n-json/valid-json': 'error',
      },
    },
    {
      files: ['./**/__tests__/**/*.[jt]s?(x)', './**/?(*.)+(spec|test).[jt]s?(x)'],
      excludedFiles: ['./**/Storyshots.(spec|test).[jt]s?(x)'],
      extends: ['plugin:jest/all', 'plugin:jest-formatting/strict', 'plugin:testing-library/react'],
      env: {
        'jest/globals': true,
      },
      rules: {
        ...jestRules,
        // too hard to do in the codebase actually
        'jest/prefer-expect-assertions': 'off',
      },
    },
  ],
};

```
</details>

```js
// ./src/Storyshots.test.ts

import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({});
```

### What did you expect to happen?

Eslint should not check a file included by the `excludedFiles` regexp

### What actually happened?

Eslint is still checking a file when the regexp is including an 'alternative' pattern (parenthesis with pipe)

This does nos work (files are not excluded), but should : 

```ts
// in overrides
excludedFiles: ['./**/Storyshots.(spec|test).[jt]s?(x)'],
```

This does work (files are excluded) : 

```ts
// in overrides
excludedFiles: ['./**/Storyshots.test.[jt]s?(x)', './**/Storyshots.spec.[jt]s?(x)'],
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Seems `(spec|test)` is breaking the regexp pattern in `excludedFiles` in an `overrides`

**Comment by mdjermanovic** [comment]
Hi @blephy, thanks for the issue!

> ```ts
> excludedFiles: ['./**/Storyshots.(spec|test).[jt]s?(x)'],
> ```

I think that `(foo|bar)` without a prefix doesn't have a specific syntactic meaning in globs.

Can you try with either of these and see if that works as expected:

```js
excludedFiles: ['./**/Storyshots.@(spec|test).[jt]s?(x)'],
```

```js
excludedFiles: ['./**/Storyshots.{spec,test}.[jt]s?(x)'],
```

**Comment by blephy** [comment]
Hi @mdjermanovic !

Thanks a lot for your answer. 

You right, both of your regexp are excluding well files :) 

Can you update the eslint documentation about it ? Should be great 👍

**Comment by mdjermanovic** [comment]
> Can you update the eslint documentation about it ? Could be great

I think we don't have any documentation about glob syntax where this explanation could be added. Maybe we could make a document about glob syntax that ESLint supports, or add a link to an external document (for example, to `minimatch`'s README). @eslint/eslint-tsc thoughts?

**Comment by blephy** [comment]
@mdjermanovic this could be better than nothing IMO 👍🏼

**Comment by nzakas** [comment]
If we make mention that glob patterns follow minimatch syntax, I think we can just link to minimatch. Probably here:
https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns

**Comment by tewarig** [comment]
can i work on this issue ?
