### ISSUE TITLE
Change Request: Config base path in flat config

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#15683]
### ESLint version

main

### What problem do you want to solve?

When implementing flat config, I discovered a quirk that wasn't obvious from the RFC. The `files` and `ignores` patterns are calculated relative to where the config file was found. So if the `eslint.config.js` file is found in `~/project`, then `*.js` matches `~/project/foo.js` but not `~/foo.js`. This is the intended behavior and not a problem, as I think it is expected when we search for a config file that the patterns will be relative to where the file was found.

The problem is when someone uses the `ESLint` constructor and passes in an alternate config file (via `configFile` option). In this case, we don't do a search for `eslint.config.js` and instead just load the referenced config file. Right now, that config file also resolves `files` and `ignores` relative to the location of the file, but I believe this is unexpected from a user perspective.

### What do you think is the correct solution?

When someone passes `configFile` to the `ESLint` constructor, I think `files` and `ignores` should be calculated as relative to the current working directory instead of the location of the file. 

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> When someone passes `configFile` to the `ESLint` constructor, I think `files` and `ignores` should be calculated as relative to the current working directory instead of the location of the file.

Makes sense to me, I would expect this behavior.

Current eslintrc works exactly like this with `overrideConfigFile` constructor option (`--config` CLI option). Patterns in `overrides` of those configs are calculated relative to `cwd`, not to the passed config path.

**Comment by nzakas** [comment]
Thanks, that really validates this decision. 👍
