### ISSUE TITLE
Overrides of ignore patterns

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#15687]
From: https://github.com/eslint/eslintrc/pull/20#discussion_r569884691, eslint/eslint#5410

The flat config should provide the way that end-users override the `ignores` setting of shareable configs and ESLint built-ins.

----

In `.eslintignore`, we can use negative patterns.

```gitignore
# .eslintignore
!/node_modules/my-package/
!.eslintrc.js
```

ESLint ignores `/node_modules/*` by default, but we can un-ignore it by such as the above setting.
Similarly, ESLint ignores dotfiles by default, but we can un-ignore it to lint `.eslintrc.js`-like config files.

----

In `.eslintrc.*`, the `ignorePatterns` setting is the same style as `.eslintignore`. Both end-user's configs and shareable configs can have the `ignorePatterns` setting. It let us override the settings of base configs.

```yml
# .eslintrc.yml
ignorePatterns:
  - "!/node_modules/my-package/"
  - "!.eslintrc.js"
```

----

I think we should consider it on the flat config system.

```js
import baseConfig from "my-eslint-config"
export default [
  baseConfig, // when it has `ignores: ["/foo/*"]`
  {
    ignores: [
      "!/node_modules/my-package/", // un-ignore the built-in ignores
      "!/foo/bar"                   // un-ignore the base config's ignores
    ]
  }
]
```

----

Also, I think it's confusing with the following:

```js
import baseConfig from "my-eslint-config"
export default [
  baseConfig, // when it has `ignores: ["/foo/*"]`
  {
    files: ["/**/*.js"],
    ignores: [
      "!/node_modules/my-package/", // 
      "!/foo/bar"                   // what happens?
    ]
  }
]
```

This is a topic that wasn't resolved in "Config File Simplification" RFC.

In https://github.com/eslint/rfcs/pull/9#discussion_r433626412 thread, I had tried to describe that the `ignores` setting has two meaning, then argued that it should be separated.

- If the `files` field exists, the` ignores` field is used for the adoption of the config array element and isn't merged for the ignore check. It's glob patterns as the RFC says. It corresponds to the `files` and `excludedFiles` of legacy configs.
- If the `files` field doesn't exist, the `ignores` field doesn't affect the adoption of the config array element and is merged for the ignore check. It's a list of gitignore-style patterns and supports negative patterns to override base configs.  It corresponds to the `ignorePatterns` of legacy configs and `.eslintignore`.

**Comment by nzakas** [comment]
This was completed with some of the other work, most notably #16415 and #16416.
