### ISSUE TITLE
Fuzz testing

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1568]
I started fuzz testing ESLint using @michaelficarra's [estools/esfuzz](https://github.com/estools/esfuzz) about a week ago, which is how I found crashes in no-multi-spaces, comma-spacing, comma-style, and no-else-return. All of these have now been fixed, and I just tested more than 10,000 unique inputs without any more crashes. Would the rest of you working on ESLint find this useful? I'll submit a PR if there's interest.

**Comment by platinumazure** [comment]
Is there anything in LEVN/type-check that could make this easier than using JSON Schema?

**Comment by nzakas** [comment]
We've already implemented JSON Schema for rules. If you have a suggestion for how to do fuzz testing more efficiently, please let us know.

**Comment by platinumazure** [comment]
So you have- I think I was confused by some of the conversation here which must have taken place before that decision.

I have nothing useful for you now, but I'll keep thinking on it.

**Comment by platinumazure** [comment]
I found this fuzz generator implemented in Ruby, which generates JSON inputs based on a JSON Schema. I didn't see anything in Node.js on it. Maybe it might be worth porting over to Node.js and create an npm package? I'd be interested in seeing it done but I haven't got the time to run a project like that.

**Comment by IanVS** [comment]
I'll have to do something similar for autoconfig, in that I need to create combinations of valid schemas.  It's next up on my plate after I wrap up the documentation updates I'm currently working on.  Thanks for sharing the fuzz generator, that will be a helpful reference I'm sure.

**Comment by gyandeeps** [comment]
Nobody has committed to do this and this issue has been open for a year now. I think we should close this as I dont see it getting done.
Feel free to reopen if interested.
