### ISSUE TITLE
Update eslint.org website - Userguide => Integrations

### ISSUE THREAD

**Issue by db-developer** [eslint/eslint#15690]
### ESLint version

v8.9.0

### What problem do you want to solve?

Userguide => Integrations => Atom
enhancement

### What do you think is the correct solution?

Section Integration - list of Editors.
Feel free to add [fast-eslint-8](https://atom.io/packages/fast-eslint-8) to editor Atom.
fast-eslint-8 currently supports eslint v8.9.0

Thanx for your continuing work on eslint.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Please submit a pull request. We don’t maintain this list ourselves.
