### ISSUE TITLE
Support top-level await syntax

### ISSUE THREAD

**Issue by ddurschlag** [eslint/eslint#15693]
### Syntax name

Top-level await

### Syntax proposal URL

https://github.com/tc39/proposal-top-level-await

Previously suggested in #13663 when this was only stage 3.

### Example code

```js
#!/usr/bin/env node

import {myAsyncThing} from 'myAsyncPackage';

await myAsyncThing();
```

### Implementation Checklist

- [ ] Ecma262 update: 
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [ ] `eslint` update: 

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @ddurschlag, thanks for the issue!

ESLint already supports top-level await syntax. If you're using ESLint with the default parser, you'll have to set `ecmaVersion: 2022` in parser options to enable this syntax.

```json
{
    "parserOptions": {
        "sourceType": "module",
        "ecmaVersion": 2022
    }
}
```
