### ISSUE TITLE
Bug: `comma-style = first` in combo with comments (fe. JsDoc style)

### ISSUE THREAD

**Issue by TriMoon** [eslint/eslint#15708]
### Environment

Node version: v17.7.1
npm version: v8.5.4
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.10.0-9-amd64 (**Debian 10 Live-USB**)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
	"env": {
		"browser": true,
		"es2021": true
	}
	,"extends": [
		"standard"
	]
	,"parser": "@typescript-eslint/parser"
	,"parserOptions": {
		"ecmaVersion": "latest"
		,"sourceType": "module"
	}
	,"plugins": [
		"@typescript-eslint"
	]
	,"rules": {
		"no-tabs": 0
		,"indent": ["error" ,"tab",{
			"SwitchCase": 1
			,"flatTernaryExpressions": false
			,"offsetTernaryExpressions": true
		}]
		,"brace-style": ["error" ,"stroustrup" ,{
			"allowSingleLine": true
		}]
		,"camelcase": ["error" ,{
			"properties": "always"
			,"ignoreGlobals": true
			,"allow": [
				"^UNSAFE_"
			 ]
		}]
		,"comma-spacing": ["error" ,{
			"before": true
			,"after": false
		}]
		,"comma-style": ["error" ,"first"]
		// ,"comma-style": ["error" ,"first", {
		// 	"exceptions": {
		// 		"VariableDeclaration": true
		// 	}
		// }]
		,"eol-last": ["error", "never"]
		,"one-var": ["error" ,"consecutive"]
		,"operator-linebreak": ["error" ,"before" ,{
				"overrides": {
					"=": "after"
				}
			}
		]
		,"space-before-blocks": ["error" ,"never"]
		,"space-before-function-paren": ["error" ,"never"]
	}
}
```
</details>

```js
/**
 * Add an Error object as log entry.
 * @param {logTimestamp} ts
 * see {@link logTimestamp}.
 * @param {Error} err
 * The Error object.
 * @throws {TypeError} Invalid logEntries provided.\
 * See the {@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error Error Object}@MDN.
 * @this Logger
 * The Logger instance.
 * @requires module:rawHTML
 */
function addError(
	ts
	,err
){
	// Parameter sanity checking.
	if (!(err instanceof Error)){
		throw new TypeError('Invalid Error object provided !');
	}

	const
		/** @type {DocumentFragment} */
		fragment = new DocumentFragment()
		,/** @type {String} */
		errorName = err.name
		,/** @type {String|HTMLElement|DocumentFragment} */
		errorMsg = err.message
		,/**
		 * A DOM-Node container.
		 * @typedef
		 * @type			{Object}
		 */
		childNodes = {}
		;

	// rest of code...
}
```

### What did you expect to happen?

Being able to code and lint error-free, **without the need** to instead switch to using the commented out version of the config.
Because the JsDoc comments need to immediately precede the identifiers.

This rule should proceed as intended, while skipping the comments right after the comma (like the JavaScript engines do also).

### What actually happened?

I receive the error: `Bad line breaking before and after ','.` on the lines where i use a first comma.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

- See [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyoqXG4gKiBBZGQgYW4gRXJyb3Igb2JqZWN0IGFzIGxvZyBlbnRyeS5cbiAqIEBwYXJhbSB7bG9nVGltZXN0YW1wfSB0c1xuICogc2VlIHtAbGluayBsb2dUaW1lc3RhbXB9LlxuICogQHBhcmFtIHtFcnJvcn0gZXJyXG4gKiBUaGUgRXJyb3Igb2JqZWN0LlxuICogQHRocm93cyB7VHlwZUVycm9yfSBJbnZhbGlkIGxvZ0VudHJpZXMgcHJvdmlkZWQuXFxcbiAqIFNlZSB0aGUge0BsaW5rIGh0dHBzOi8vZGV2ZWxvcGVyLm1vemlsbGEub3JnL2VuLVVTL2RvY3MvV2ViL0phdmFTY3JpcHQvUmVmZXJlbmNlL0dsb2JhbF9PYmplY3RzL0Vycm9yIEVycm9yIE9iamVjdH1ATUROLlxuICogQHRoaXMgTG9nZ2VyXG4gKiBUaGUgTG9nZ2VyIGluc3RhbmNlLlxuICogQHJlcXVpcmVzIG1vZHVsZTpyYXdIVE1MXG4gKi9cbmZ1bmN0aW9uIGFkZEVycm9yKFxuXHR0c1xuXHQsZXJyXG4pe1xuXHQvLyBQYXJhbWV0ZXIgc2FuaXR5IGNoZWNraW5nLlxuXHRpZiAoIShlcnIgaW5zdGFuY2VvZiBFcnJvcikpe1xuXHRcdHRocm93IG5ldyBUeXBlRXJyb3IoJ0ludmFsaWQgRXJyb3Igb2JqZWN0IHByb3ZpZGVkICEnKTtcblx0fVxuXG5cdGNvbnN0XG5cdFx0LyoqIEB0eXBlIHtEb2N1bWVudEZyYWdtZW50fSAqL1xuXHRcdGZyYWdtZW50ID0gbmV3IERvY3VtZW50RnJhZ21lbnQoKVxuXHRcdCwvKiogQHR5cGUge1N0cmluZ30gKi9cblx0XHRlcnJvck5hbWUgPSBlcnIubmFtZVxuXHRcdCwvKiogQHR5cGUge1N0cmluZ3xIVE1MRWxlbWVudHxEb2N1bWVudEZyYWdtZW50fSAqL1xuXHRcdGVycm9yTXNnID0gZXJyLm1lc3NhZ2Vcblx0XHQsLyoqXG5cdFx0ICogQSBET00tTm9kZSBjb250YWluZXIuXG5cdFx0ICogQHR5cGVkZWZcblx0XHQgKiBAdHlwZVx0XHRcdHtPYmplY3R9XG5cdFx0ICovXG5cdFx0Y2hpbGROb2RlcyA9IHt9XG5cdFx0O1xuXG5cdC8vIHJlc3Qgb2YgY29kZS4uLlxuICBmcmFnbWVudCwgZXJyb3JOYW1lLCBlcnJvck1zZywgY2hpbGROb2Rlcztcbn1cbmFkZEVycm9yKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUtZWxzZS1pZiI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW1wb3J0LWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLWxvc3Mtb2YtcHJlY2lzaW9uIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW5zYWZlLW9wdGlvbmFsLWNoYWluaW5nIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImNvbW1hLXN0eWxlIjoyfSwiZW52Ijp7ImJyb3dzZXIiOnRydWUsImVzMjAyMSI6dHJ1ZX19fQ==)

**Comment by TriMoon** [comment]
PS: Same problem with `operator-linebreak` :disappointed: 
Same config as above and using fe. `||`

**Comment by nzakas** [comment]
These rules don’t support this format. We do our best to support the most common cases, but we can’t guarantee every case. Here, your best bet is to create a custom rule that behaves the way you want.

**Comment by TriMoon** [comment]
@nzakas 
> These rules don’t support this format. We do our best to support the most common cases, but we can’t guarantee every case. Here, your best bet is to create a custom rule that behaves the way you want.

If a product bugs when a user uses the products feature and the makers are not willing to fix their own product then that user will not have any reason to report other bugs and will move to other products at the first viable chance.
_(Closing the issue = not willing to fix)_

eg:
- "These rules don’t support this format."
A user either uses comma first or last right?
So why is that user not allowed to use comments in this case?
- "We do our best to support the most common cases, but we can’t guarantee every case."
How is using comments with coma-first style not a common case? _(Are you kidding?)_
Of-course you cant guarantee every case, that's why users give feedback with buggy behaviour to help you improve it....
- "Here, your best bet is to create a custom rule that behaves the way you want."
Create a custom rule to fix your product's **own supported feature?** _(Are you kidding?)_
You want your users, me in this case, to delve into how your product works so much that I'm able to create a custom rule?
Every user which gets an answer like that will say:
  - These guys have grown too popular being able to afford such a response to their user-base.
  - I guess the time and efforts needed for that are better spend on looking for other products and switch asap.

No need to mention that these kind of responses from product makers stay until **eternity** on the internet, and will keep haunting **them** in future, more as it will haunt the product itself...
_(You just made a scratch on your own CV.)_

I did my part by reporting some bugs in your product, it's of-course up to you  and your team to fix it or not, no one can demand or force anyone to do anything.
But a response like that is just shooting yourself in the face.
Too bad because i saw how `eslint` grew to be a great product from the start by trying to replace "the other products" at that time....
Take care, no hard feelings just stating the facts...
