### ISSUE TITLE
Bug: (fill in) Eslint NPM throwing 5 high severity 

### ISSUE THREAD

**Issue by bearsworth** [eslint/eslint#15714]
### Environment

Node version: v17.7.2
npm version: v8.5.2
Local ESLint version: v8.11.0 (Currently used)

### What parser are you using?

Other

### What did you do?

Using eslint version 8.11.0. After running @eslint/config. Do this setup:

How would you like to use ESLint? · style
✔ What type of modules does your project use? · commonjs
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · node
✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · airbnb
✔ What format do you want your config file to be in? · JSON
Checking peerDependencies of eslint-config-airbnb-base@latest
The config that you've selected requires the following dependencies:

eslint-config-airbnb-base@latest eslint@^7.32.0 || ^8.2.0 eslint-plugin-import@^2.25.2
✔ Would you like to install them now with npm? · No / Yes
Installing eslint-config-airbnb-base@latest, eslint@^7.32.0 || ^8.2.0, eslint-plugin-import@^2.25.2

### What did you expect to happen?

No high severity vulnerabilities.

### What actually happened?

After going through setup, the program installs the eslint import plugin which throws 5 high severity vulnerabilities. Details from the audit:

minimist  *
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix --force`
Will install eslint-plugin-import@2.20.2, which is a breaking change
node_modules/minimist
  json5  1.0.0-beta - 2.2.0
  Depends on vulnerable versions of minimist
  node_modules/json5
    tsconfig-paths  >=3.3.0
    Depends on vulnerable versions of json5
    Depends on vulnerable versions of minimist
    node_modules/tsconfig-paths
      eslint-plugin-import  >=2.21.0
      Depends on vulnerable versions of tsconfig-paths
      node_modules/eslint-plugin-import
        eslint-config-airbnb-base  >=14.2.0
        Depends on vulnerable versions of eslint-plugin-import
        node_modules/eslint-config-airbnb-base

5 high severity vulnerabilities

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
This is coming in from the Airbnb plugin. I’d suggest opening an issue with them, as we just install the latest version.

Please note that security vulnerabilities are relevant when running packages as part of a web server or other network-connected service. As a CLI program, ESLint isn’t affected.
