### ISSUE TITLE
Bug: `no-use-before-define` in combo with `export` keywords.

### ISSUE THREAD

**Issue by TriMoon** [eslint/eslint#15710]
### Environment

Node version: v17.7.2
npm version: v8.5.2
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.10.0-9-amd64 (**Debian 10 Live-USB**)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
	"env": {
		"browser": true
		,"es2021": true
	}
	,"extends": [
		"standard"
	]
	,"parser": "@typescript-eslint/parser"
	,"parserOptions": {
		"ecmaVersion": "latest"
		,"sourceType": "module"
	}
	,"plugins": [
		"@typescript-eslint"
	]
	,"rules": {
		"no-tabs": 0
		,"indent": ["error" ,"tab",{
			"SwitchCase": 1
			,"flatTernaryExpressions": false
			,"offsetTernaryExpressions": true
		}]
		,"brace-style": ["error" ,"stroustrup" ,{
			"allowSingleLine": true
		}]
		,"camelcase": ["error" ,{
			"properties": "always"
			,"ignoreGlobals": true
			,"allow": [
				"^UNSAFE_"
			 ]
		}]
		,"comma-spacing": ["error" ,{
			"before": true
			,"after": false
		}]
		// Manually disable/enable blocks until this bug is fixed...
		,"comma-style": ["error" ,"first"]
		// ,"comma-style": ["error" ,"first", {
		// 	"exceptions": {
		// 		"VariableDeclaration": true
		// 	}
		// }]
		// /Manually disable/enable blocks until this bug is fixed...

		,"eol-last": ["error", "never"]
		,"one-var": ["error" ,"consecutive"]
		,"operator-linebreak": ["error" ,"before" ,{
				"overrides": {
					"=": "after"
				}
			}
		]
		,"space-before-blocks": ["error" ,"never"]
		,"space-before-function-paren": ["error" ,"never"]
	}
}
```
</details>

```js
import { x }	from	'./y.mjs'
export {
	logger as default
	,SomeClass
	,x
}

class SomeClass{
	// code
}

const logger = new SomeClass()
```

### What did you expect to happen?

No complaint from `eslint`.

### What actually happened?

- `logger` was used before it was defined. `eslint(no-use-before-define)`
- `SomeClass` was used before it was defined. `eslint(no-use-before-define)`

See also [demo](https://eslint.org/demo#eyJ0ZXh0IjoiaW1wb3J0IHsgeCB9XHRmcm9tXHQnLi95Lm1qcydcbmV4cG9ydCB7XG5cdGxvZ2dlciBhcyBkZWZhdWx0XG5cdCxTb21lQ2xhc3Ncblx0LHhcbn1cblxuY2xhc3MgU29tZUNsYXNze1xuXHQvLyBjb2RlXG59XG5cbmNvbnN0IGxvZ2dlciA9IG5ldyBTb21lQ2xhc3MoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWVsc2UtaWYiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWltcG9ydC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tbm9ub2N0YWwtZGVjaW1hbC1lc2NhcGUiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZXR0ZXItcmV0dXJuIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtYmFja3JlZmVyZW5jZSI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyLCJuby11c2UtYmVmb3JlLWRlZmluZSI6Mn0sImVudiI6eyJicm93c2VyIjp0cnVlLCJlczIwMjEiOmZhbHNlfX19).

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

What is needed for `eslint` to allow exports at top of modules in combination with `no-use-before-define`?
Because JavaScript processes those keywords before the actual code they represent in modules.
The style works perfectly without errors in `browsers`, but `eslint` forces you to place the export part at end of the file.
Yes i know i could use the `export` keywords on the same line as the definition of them, but it is better for overview to place them at start like shown in code above.

**That's why i propose an `exports` flag in [no-use-before-define#options)](https://eslint.org/docs/rules/no-use-before-define#options) to control the wanted behaviour.**

---
I'll currently use this work-around for my exports at top until this is fixed/added: :disappointed: 
```js
/* eslint-disable no-use-before-define */
export {
	logger as default
	,SomeClass
	,x
}
/* eslint-enable no-use-before-define */
```

**Comment by mdjermanovic** [comment]
Hi @TriMoon, thanks for the issue!

I can reproduce this, but it isn't a bug. This rule is mostly stylistic, so it reports references that appear before declarations even when those references do not cause runtime errors.

> That's why i propose an `exports` flag in [no-use-before-define#options)](https://eslint.org/docs/rules/no-use-before-define#options) to control the wanted behaviour.

An option to always allow references inside `export { ... }` makes sense to me :+1:

**Comment by TriMoon** [comment]
@mdjermanovic 
>An option to always allow references inside export { ... } makes sense to me +1

Thinking about how the language handles the `export` keyword, it might even be better to change that rule to always allow it without a need/ability to change the posibility :wink: 
But in that case `eslint` should ofcourse still bark if the reference is never declared inside the module, eg. unable to export it. :wink:

**Comment by ljharb** [comment]
The whole point of `no-use-before-define` is that you don't reference things before they're defined, whether it's for exporting or anything else.

My stylistic preference is that exports, like returns, should go at the end of the relevant section of code. Putting exports at the end obviates this issue's conflict, and since export statements are hoisted/parsed prior to evaluation, the effect is the same no matter where they're located.

**Comment by TriMoon** [comment]
@ljharb 
That is a perfectly acceptable style, just like a style with them on top of the file, it's all a **style preference** of the coders.

- Pro-argument for using them at top instead of at bottom or even middle:
  1. It provides a better overview of what `imports/exports` a modules uses, without the need to search inside the module-code.

**Comment by ljharb** [comment]
Sure. That stylistic preference would be the same applied to function declarations. If that's a style you prefer, then it doesn't seem like this rule - whose entire purpose is to prevent that style - is for you.

**Comment by TriMoon** [comment]
> Sure. That stylistic preference would be the same applied to function declarations. If that's a style you prefer, then it doesn't seem like this rule - whose entire purpose is to prevent that style - is for you.

uhmmm :eyes: 
Do i smell a +1 vote for a new option to override this rule's barking in this case then?

**Comment by ljharb** [comment]
I don’t think such an option makes sense for this particular rule, but since eslint has a ban on stylistic changes, i don’t see how any such option would qualify for addition.

**Comment by TriMoon** [comment]
ahhh so `eslint` just likes to put its head in ground when it comes to es6+ features? (I doubt that)
There are more issues related to  `import/export` statements as far as i could see, which require stylistic changes/adding to properly support the technological advancements.

It's disappointing to read such a reaction from a (sponsor) contributor...

**Comment by mdjermanovic** [comment]
@TriMoon ljharb is referring to our [policies about stylistic rules](https://github.com/eslint/eslint#stylistic-rule-updates).

@ljharb this rule was originally purely stylistic. As of es6, it can also be used to prevent TDZ errors, and the [documentation](https://eslint.org/docs/rules/no-use-before-define) for this rule does mention TDZ as one of the rationales for using the rule. Since this rule can be used for different purposes, I'm supportive of an option to disable a stylistic-only exports check so that the rule can be configured to only warn about statically determinable TDZ errors.

**Comment by nzakas** [comment]
> I'm supportive of an option to disable a stylistic-only exports check so that the rule can be configured to only warn about statically determinable TDZ errors.

Makes sense to me 👍

**Comment by mdjermanovic** [comment]
@btmills would you agree with adding an option to allow references in `export { }`?

**Comment by btmills** [comment]
TDZ-only makes sense to me :+1:

**Comment by mdjermanovic** [comment]
I'm working on this.

**Comment by TriMoon** [comment]
@mdjermanovic thanks for implementing this :+1: 

I'm just wondering why you choose to default to `false` in https://github.com/eslint/eslint/commit/f6d79209821241c8e03c183b5844a024da0efe8a#diff-c6cfabe41e087014db02d66b884c50157300e6309034ba79d548c2b421468f8eR128
Because the behavior of the language allows it by definition by hoisting them to top of the code :wink: 
(I would prefer it to defaulting to `true` to better reflect es6+ standard parsing)

**Comment by mdjermanovic** [comment]
> I'm just wondering why you choose to default to `false` in [f6d7920#diff-c6cfabe41e087014db02d66b884c50157300e6309034ba79d548c2b421468f8eR128](https://github.com/eslint/eslint/commit/f6d79209821241c8e03c183b5844a024da0efe8a#diff-c6cfabe41e087014db02d66b884c50157300e6309034ba79d548c2b421468f8eR128)
> Because the behavior of the language allows it by definition by hoisting them to top of the code 
> (I would prefer it to defaulting to `true` to better reflect es6+ standard parsing)

This rule is primarily stylistic, so by default any reference that appears before the declaration is disallowed. References to function declarations are also disallowed by default, although they are hoisted.
