### ISSUE TITLE
Rule Change: (eqeqeq)

### ISSUE THREAD

**Issue by tylerlong** [eslint/eslint#15717]
### What rule do you want to change?

eqeqeq

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

```js
"eqeqeq": ["error", "always", {"autoFix": true}]
```

### Example code

```js
const a = 1;
if(a + 1 == 2) {
  console.log('Hello');
}
```

### What does the rule currently do for this code?

It will not auto fix the code for me

### What will the rule do after it's changed?

It should auto fix the code for me because I specified `"autoFix": true`

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

Ref: https://github.com/eslint/eslint/issues/4578

So there was concern regarding auto fix. That is why I suggest an option `autoFix`. By default is it `false` so it won't break anything. 

For those who really want the auto fix they could explicitly specify `"autoFix": true`

**Comment by aladdin-add** [comment]
As stated in the docs: "Avoid any fixes that could change the runtime behavior of code and cause it to stop working."
https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes

you can try [eslint-plugin-autofix](https://npmjs.com/package/eslint-plugin-autofix) if you want.
