### ISSUE TITLE
Bug: array-bracket-spacing fixer unexpectedly removed inline comment

### ISSUE THREAD

**Issue by Krinkle** [eslint/eslint#15732]
### Environment

Affected ESLint versions: 8.12.0, 7.32

### What parser are you using?

Default (Espree)

### What did you do?

See also: [ESLint Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGFycmF5LWJyYWNrZXQtc3BhY2luZzpcImVycm9yXCIgKi9cblxuUVVuaXQudGVzdCggXCJleGFtcGxlXCIsIGFzc2VydCA9PiB7XG4gIGZ1bmN0aW9uIFBvaW50KCB4LCB5ICkge1xuICAgIHRoaXMueCA9IHg7XG4gICAgdGhpcy55ID0geTtcbiAgfVxuICBjb25zdCBuZXN0ZWQgPSB7XG4gICAgICBub3J0aDogWyAvKiAuLi4gKi8gXSxcbiAgICAgIGVhc3Q6IG5ldyBQb2ludCggMTAsIDIwICksXG4gICAgICBzb3V0aDogWy8qIC4uLiAqL10sXG4gICAgICB3ZXN0OiBbIC8qIC4uLiAqLyBdXG4gIH07XG4gIGFzc2VydC5wcm9wQ29udGFpbnMoIG5lc3RlZCwgeyBlYXN0OiB7IHg6IDEwLCB5OiAyMCB9IH0gKTtcbn0pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnsiaW1wbGllZFN0cmljdCI6dHJ1ZX19LCJydWxlcyI6e30sImVudiI6e319fQ==)

<details>
<summary>Configuration</summary>

```
{
  "array-bracket-spacing": "error"
}
```
</details>

```js
const nested = {
  north: [ /* ... */ ],
  east: new Point( 10, 20 ),
  south: [/* ... */],
  west: [ /* ... */ ]
};
```

### What did you expect to happen?

Remove the spaces within the array brackets.

### What actually happened?

The contents of the array (specifically, the comment node) were removed as well.

```js
const nested = {
  north: [],
  east: new Point( 10, 20 ),
  south: [/* ... */],
  west: []
};
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I originally encountered this when using ESLint with eslint-plugin-markdown to lint code examples at <https://api.qunitjs.com/assert/propEqual/#examples>.

**Comment by aladdin-add** [comment]
marked as accepted, given the repro demo. thanks!

**Comment by Gautam-Arora24** [comment]
Can I work on this issue?

**Comment by aladdin-add** [comment]
please feel free.
