### ISSUE TITLE
Bug: (VSCode, WebStorm) Unexpected top-level property "overrides[0].extends"

### ISSUE THREAD

**Issue by chirastefan** [eslint/eslint#15741]
### Environment

Node version:  12.22.11
npm version:  6.14.16
Local ESLint version:  4.19.1
Global ESLint version:  none
Operating System:  OSX

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
const path = require('path');

const TS_OVERRIDES = {
  files: ['**/*.{tsx,ts}'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: path.resolve(__dirname, 'tsconfig.json'),
    tsconfigRootDir: __dirname
  },
  plugins: ['@typescript-eslint'],
  extends: [
    'airbnb-typescript',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'prettier/@typescript-eslint'
  ],
  rules: {},
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.tsx', '.ts']
    },
    'import/resolver': {
      typescript: {
        project: path.resolve(__dirname, 'tsconfig.json')
      }
    }
  }
};

module.exports = {
  root: true,
  env: {
    browser: true,
    jest: true
  },
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 12,
    sourceType: 'module'
  },
  plugins: ['react', 'react-hooks', 'prettier'],
  extends: ['airbnb', 'plugin:react/recommended', 'prettier', 'prettier/react'],
  rules: {
    'react/jsx-filename-extension': [
      1,
      {
        extensions: ['.js', '.jsx', '.ts', '.tsx']
      }
    ],
    'import/no-unresolved': [
      2,
      {
        amd: true
      }
    ],
    'import/no-extraneous-dependencies': 0,
    'react/prop-types': 0,
    'comma-dangle': [1, 'never'],
    'object-curly-spacing': 0,
    'object-curly-newline': 0,
    'react/require-default-props': [
      1,
      {
        ignoreFunctionalComponents: true
      }
    ]
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx'],
        paths: ['node_modules', 'src/']
      }
    }
  },
  overrides: [TS_OVERRIDES]
};
```
</details>

### What did you expect to happen?

run without errors

### What actually happened?

I get this error in WebStorm and when i try to run eslint on the src folder, I get the same error

<img width="1310" alt="Screen Shot 2022-03-30 at 13 26 31" src="https://user-images.githubusercontent.com/16649178/160811309-738a7976-5ce4-4842-a941-9f70397d00b4.png">

![Screen Shot 2022-03-30 at 13 29 32](https://user-images.githubusercontent.com/16649178/160811559-4b55d45e-01be-4f36-a4bc-9ac9d1c5db50.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

strangely enough, it seems to work inside the terminal

**Comment by snitin315** [comment]
> strangely enough, it seems to work inside the terminal

@chirastefan If it's working fine on CLI, then it seems to be a problem with the editor extension itself.

**Comment by mdjermanovic** [comment]
> Local ESLint version: 4.19.1

@chirastefan you are using an old version of ESLint that doesn't support `extends` in `overrides`. Can you try with the latest ESLint v8.12.0?

**Comment by chirastefan** [comment]
I noticed afterward that somehow I managed to downgrade to eslint 4.19.1, now it seems to be fixed, ty

**Comment by mdjermanovic** [comment]
> I noticed afterward that somehow I managed to downgrade to eslint 4.19.1, now it seems to be fixed, ty

Thanks for the info! Closing, as the issue has been resolved.
