### ISSUE TITLE
Bug: All ESLint 8 commands fail if the project path contains URL-encoded characters

### ISSUE THREAD

**Issue by chucknelson** [eslint/eslint#15766]
### Environment

Node version: 14.18.2
npm version: 6.14.15
Local ESLint version:  8.12.0
Global ESLint version: none
Operating System: Darwin 20.6.0 (macOS Big Sur)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Try to run any ESLint command in a project path with a URL encoded character, such as `/my%2Fproject/yarn eslint --env-info`.

### What did you expect to happen?

Command would succeed with the expected output, such as:

```sh
/Users/myuser/my%2Fproject/node_modules/.bin/eslint --debug --env-info
eslint:cli CLI args: [ '--debug', '--env-info' ] +0ms
Environment Info:

Node version: v14.18.2
npm version: v6.14.15
Local ESLint version: v8.12.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.6.0
```

### What actually happened?

# Example

A project with `eslint@8.12.0` installed is in the following path that includes a URL-encoded slash:

`/Users/myuser/my%2Fproject`

Run any ESLint command, such as `--env-info` and it fails with the following:

```sh
/Users/myuser/my%2Fproject/node_modules/.bin/eslint --debug --env-info

Oops! Something went wrong! :(

ESLint: 8.12.0

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///Users/d108059/Development/tmp/my%2Fproject/node_modules/@eslint/eslintrc/dist/eslintrc.cjs'
    at new NodeError (internal/errors.js:322:7)
    at Function.createRequire (internal/modules/cjs/loader.js:1182:13)
    at Object.<anonymous> (/Users/d108059/Development/tmp/my%2Fproject/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2383:26)
    at Module._compile (/Users/d108059/Development/tmp/my%2Fproject/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/Users/d108059/Development/tmp/my%2Fproject/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/d108059/Development/tmp/my%2Fproject/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
error Command failed with exit code 2.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Prior versions of ESLint, such as `7.32.0`, work fine with these paths. For example, this works fine:

```sh
/Users/myuser/my%2Fproject/node_modules/.bin/eslint --debug --env-info
eslint:cli CLI args: [ '--debug', '--env-info' ] +0ms
Environment Info:

Node version: v14.18.2
npm version: v6.14.15
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.6.0
```

**Comment by nzakas** [comment]
This error is coming from `require()`, which means it’s coming from inside Node.js. Here’s the line:

https://github.com/eslint/eslint/blob/bb4c0d530a231a8a14ed70ad61c06e284bbaaef0/lib/cli-engine/cli-engine.js#L33

Do you see this behavior in ESLint v8.0.0?

**Comment by fasttime** [comment]
Looking at the line `/@eslint/eslintrc/dist/eslintrc.cjs:2383:26` hinted by the stack trace, I can find this code:

```js
const require$1 = Module.createRequire((typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('eslintrc.cjs', document.baseURI).href)));
```

You can see the whole file here: https://unpkg.com/@eslint/eslintrc@1.2.1/dist/eslintrc.cjs

The corresponding source code is this harmless-looking line in eslintrc:

```js
const require = createRequire(import.meta.url);
```

which can be found here: https://github.com/eslint/eslintrc/blob/9b719813fc6f023b722168a4f67d895106e875ce/lib/config-array-factory.js#L58

From what I can tell, the generated code is trying to create a file URL from `__filename`, but doing so in a very error-prone way: `'file:' + __filename` rather than using the builtin Node function [`pathToFileURL`](https://nodejs.org/api/url.html#urlpathtofileurlpath). The resulting URL will contain an escaped slash (`%2F`) rather than the proper escape sequence for "%2F" (`%252F`).

This is not a bug in ESLint, but rather an issue with the build tools used in eslintrc, most probably Rollup.

**Comment by nzakas** [comment]
@fasttime wow, thanks for the detailed analysis. We will look deeper into this.

**Comment by mdjermanovic** [comment]
@fasttime thanks for all the details! I prepared a possible fix based on your suggestion.

https://github.com/eslint/eslintrc/pull/77
