### ISSUE TITLE
Bug: eslint --init doesn't handle "code runs in node" option

### ISSUE THREAD

**Issue by timrobinson33** [eslint/eslint#15778]
### Environment

Node version: 14.1.82
npm version: 8.2.0
Local ESLint version: 
Global ESLint version: 8.13.0
Operating System: ubuntu 20.04

### What parser are you using?

Default (Espree)

### What did you do?

run `eslint --init`

leave the default for all answers except "where does your code run" - answer "node" instead of "browser"

### What did you expect to happen?

resulting configuration should include 
`    "env": {        "node": true    }`

### What actually happened?

resulting configuration had
`    "env": {        "browser": true    }`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
it's multi-selectable. you'll need to type space to unselect `browser`, and then select the `node`.

![image](https://user-images.githubusercontent.com/13050025/163113504-652c03b9-29a2-46d5-bbc1-f0e3c0b32193.png)

**Comment by timrobinson33** [comment]
you're right, sorry I didn't see the instructions.
