### ISSUE TITLE
Bug: "TypeError: Cannot read property 'type' of undefined" with `prefer-const` with optional chaining code

### ISSUE THREAD

**Issue by malixsys** [eslint/eslint#15786]
### Environment

Node version: v14.17.6
npm version: 6.14.15
Local ESLint version: eslint@8.13.0 
Global ESLint version: N/A
Operating System: mac osx 11.6.5

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  extends: [
    "plugin:jest-dom/recommended",
    "plugin:testing-library/react",
    "plugin:cypress/recommended",
    "next/core-web-vitals",
    "prettier",
    "prettier/react",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
  ],
  rules: {
    // NOTE Keep these
    "testing-library/await-async-query": "off",
    "testing-library/prefer-screen-queries": "off",

    // TODO remove these when fixed
    "@next/next/no-img-element": "warn",
    "@typescript-eslint/ban-ts-comment": "warn",
    "@typescript-eslint/no-empty-function": "warn",
    "@typescript-eslint/no-empty-interface": "warn",
    "@typescript-eslint/no-explicit-any": "warn",
    "@typescript-eslint/no-unused-vars": "warn",
    "@typescript-eslint/no-var-requires": "warn",
    "jsx-a11y/alt-text": "warn",
    "prefer-const": "warn",
    "testing-library/no-node-access": "warn",
    "testing-library/no-unnecessary-act": "warn",
    "testing-library/no-wait-for-multiple-assertions": "warn",
    "testing-library/prefer-find-by": "warn",
    "testing-library/prefer-presence-queries": "warn",
    "testing-library/render-result-naming-convention": "warn",
    "react-hooks/exhaustive-deps": "warn",

    "import/order": [
      "error",
      {
        groups: [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
        ],
        pathGroups: [
          {
            pattern: "react",
            group: "external",
            position: "before",
          },
          {
            pattern: "@sonder/**",
            group: "internal",
            position: "before",
          },
          {
            pattern: "lib/**",
            group: "internal",
            position: "before",
          },
          {
            pattern: "components/**",
            group: "internal",
            position: "before",
          },
          {
            pattern: "{.,..}/**/*.+(css|sass|less|scss|pcss|styl)",
            group: "index",
            position: "after",
          },
        ],
        pathGroupsExcludedImportTypes: ["react"],
        "newlines-between": "always",
        alphabetize: { order: "asc", caseInsensitive: true },
      },
    ],
  },
  overrides: [
    {
      files: ["*.stories.jsx", "*.stories.tsx"],
      rules: {
        "import/no-anonymous-default-export": "off",
      },
    },
  ],
}
```
</details>

```js
let someVariable = zoom?.prop?.prop2;
```

### What did you expect to happen?

 ```
Warning: 'someVariable' is never reassigned. Use 'const' instead.  prefer-const
```

### What actually happened?

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /<project_path>/path/to/my/Component.jsx:1
Rule: "prefer-const"
    at checkGroup (/<project_path>/node_modules/eslint/lib/rules/prefer-const.js:403:44)
    at Map.forEach (<anonymous>)
    at Program:exit (/<project_path>/node_modules/eslint/lib/rules/prefer-const.js:479:73)
    at ruleErrorHandler (/<project_path>/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /<project_path>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/<project_path>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:349:14)
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

switching to ternary or just one optional chaining produce no error:
```js
let someVariable = zoom ? zoom.prop.prop2 : undefined; // OK
let someVariable = zoom ? zoom.prop?.prop2 : undefined; // OK
```

**Comment by malixsys** [comment]
Also happens with `@typescript-eslint/no-unused-vars` :
```jsx
export function useSomething({ myVar}) {
  const isProp2 = myVar?.prop1?.prop2;
}
```
results in:
```
 2:3  warning  'myVar' is defined but never used  @typescript-eslint/no-unused-vars
```

**Comment by mdjermanovic** [comment]
Hi @malixsys, thanks for the issue!

 

> TypeError: Cannot read property 'type' of undefined
> Occurred while linting /<project_path>/path/to/my/Component.jsx:1
> Rule: "prefer-const"
>     at checkGroup (/<project_path>/node_modules/eslint/lib/rules/prefer-const.js:403:44)
>     at Map.forEach (<anonymous>)
>     at Program:exit (/<project_path>/node_modules/eslint/lib/rules/prefer-const.js:479:73)
>     at ruleErrorHandler (/<project_path>/node_modules/eslint/lib/linter/linter.js:1114:28)
>     at /<project_path>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
>     at Array.forEach (<anonymous>)
>     at Object.emit (/<project_path>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
>     at NodeEventGenerator.applySelector (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
>     at NodeEventGenerator.applySelectors (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
>     at NodeEventGenerator.leaveNode (/<project_path>/node_modules/eslint/lib/linter/node-event-generator.js:349:14)

I can't reproduce this, neither with the default parser (here's [online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogMiAqL1xuXG5sZXQgc29tZVZhcmlhYmxlID0gem9vbT8ucHJvcD8ucHJvcDI7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)) nor with the latest `@typescript-eslint/parser` v5.19.0.

Can you check which version of `@typescript-eslint/parser` you are using, and try with the latest version if you were using an older one?

> Also happens with `@typescript-eslint/no-unused-vars`

This is a plugin rule, you can open an issue on this repository:

https://github.com/typescript-eslint/typescript-eslint
