### ISSUE TITLE
global-strict rule & es6 mode

### ISSUE THREAD

**Issue by lionelB** [eslint/eslint#1578]
Hello,

For now, using es6 branch on a jsx file, eslint output warning about a missing `"use strict"` pragma
when `global-strict:always`
But refering to the this http://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-code
> Module code is always strict code.

I wonder if it shouldn't output warning when export is used ?

**Comment by themouette** [comment]
Any news on this?

**Comment by n1k0** [comment]
:+1:

**Comment by nzakas** [comment]
We don't support es6 modules yet, so this can't be completed until that happens.

**Comment by MoOx** [comment]
I guess it's related to https://github.com/eslint/espree/issues/35 ?

**Comment by nzakas** [comment]
Yup

**Comment by nzakas** [comment]
Closing in favor of #1956
