### ISSUE TITLE
Bug: Option ignoreConstructors of object-shorthand doesn't ignore prototype's constructor property

### ISSUE THREAD

**Issue by marcelschork** [eslint/eslint#15796]
### Environment

Node version: v14.19.0
npm version: 6.14.16
Local ESLint version: 8.12.0 
Global ESLint version: 
Operating System: Windows 10

### What parser are you using?

Default (Espree)

### What did you do?

When creating custom objects within the [SAPUI5](https://sapui5.hana.ondemand.com/) web application framework you need to  inherit the base object via framework inheritance mechanism. To construct the object you need to overwrite the prototype's constructor property. Due to the object-shorthand rule and auto-fixing of lint issues this is always turned in to a method which leads to a javascript error as constructor functions can't be methods.  So the rule should not only ignore uppercase functions names but also the lowercase constructor property when the option ignoreConstructors is set.  
<details>
<summary>Configuration</summary>

``` 
{ 
...
"object-shorthand": ["error", "always", { "ignoreConstructors": true }],
...
}
```
</details>

```js
sap.ui.define(["sap/ui/base/Object"], (SapObject) => {
    "use strict";

    return SapObject.extend("ui5.extendedObject", {
        constructor() {},
    });
});
```

### What did you expect to happen?

```javascript
sap.ui.define(["sap/ui/base/Object"], (SapObject) => {
    "use strict";

    return SapObject.extend("ui5.extendedObject", {
        constructor: function() {},
    });
});
```

### What actually happened?

error  Expected method shorthand                      object-shorthand

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @marcelschork, thanks for the issue!

> So the rule should not only ignore uppercase functions names but also the lowercase constructor property when the option ignoreConstructors is set.

Makes sense to me. It seems reasonable to assume that functions that are value of a property named `constructor` will be used as constructors (i.e., with `new`).

I also think we can treat this as a bug fix because the `ignoreConstructors` option does not disallow the concise method form, so updating the logic to include more constructor-like names can only produce fewer warnings.

I'm in favor of making this change, but would like to hear the opinions of other team members.

**Comment by mdjermanovic** [comment]
@eslint/eslint-tsc thoughts about this?

**Comment by nzakas** [comment]
This seems like a case that ignoreConstructors wasn’t intended to handle. I might be inclined to add a new ignorePrototypeConstructors option or else change the ignoreConstructors option to be a string that can be “all”, “capitalized”, “prototype”, where true is the same as “capitalized”

**Comment by mdjermanovic** [comment]
It would be best to add a generic option that accepts a regex. Properties whose name matches the regex and value is a function would be ignored. This would avoid having built-in assumptions on what names correspond to functions that will be used as constructors (or used in any other way for which the differences between function expressions and methods might be important).

**Comment by mdjermanovic** [comment]
> Do you have a proposal for that new option’s name?

Maybe `functionsIgnorePattern`?

**Comment by nzakas** [comment]
Would “methods” be better than “functions” here?

**Comment by mdjermanovic** [comment]
`methodsIgnorePattern` sounds good to me.

**Comment by mdjermanovic** [comment]
I can work on this.
