### ISSUE TITLE
S2786: 'View' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by ksielyov** [eslint/eslint#15802]
### Environment

Node version: v14.17.5
npm version: v7.21.1
Local ESLint version: v8.14.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.1.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:prettier/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/ban-ts-comment": "off",
        "prettier/prettier": "error"
    },
    "globals": {
        "__DEV__": true
    }
}
```
</details>

```ts
import React from 'react';
// @ts-ignore
import DoubleBounce from 'react-native-loader';
import {View} from 'react-native';

const DoubleBounceLoader: React.FC = () => (
  <View>
    <DoubleBounce size={16} color="#3A3A3A" />
  </View>
);

export default DoubleBounceLoader;
```

### What did you expect to happen?

Working eslint configuration

### What actually happened?

TS2786: 'View' cannot be used as a JSX component.   Its instance type 'View' is not a valid JSX element.     The types returned by 'render()' are incompatible between these types.       Type 'import("/Users/mikhailkiselyov/WebstormProjects/publife/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.         Type '{}' is not assignable to type 'ReactNode'.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
seems the error was from ts, not eslint?

**Comment by mdjermanovic** [comment]
> TS2786: 'View' cannot be used as a JSX component.

This error is coming from TypeScript, not ESLint.

Maybe these recent discussions could be helpful:

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59839

https://stackoverflow.com/questions/71831601/ts2786-component-cannot-be-used-as-a-jsx-component

**Comment by TalhaBlueEast** [comment]
I'm facing the same issue about this error. I add the below code to my **package.json** file.

    "resolutions": {
      "@types/react": "17.0.2",
      "@types/react-dom": "17.0.2",
      "graphql": "^16.5.0"
    },

Then, Run `yarn install` on a terminal.

It works for me.

**Comment by mcjambi** [comment]
i have the same issue, not really an error, but make me confuse!

**Comment by fahad0samara** [comment]
I have the same problem

**Comment by NilsBaumgartner1994** [comment]
Same

**Comment by DianSSIE** [comment]
I had to just make sure the version numbers for:
"@types/react" x.x.x
and
"@types/react-native" y.y.y

match with:
"react": x.x.x
and
"react-native" y.y.y

**Comment by ZackKuhn** [comment]
1. Paste in **package.json** file:
`"resolutions": {
    "@types/react": "17.0.14",
    "@types/react-dom": "17.0.14"
  },` 
2. Run `yarn install` on a terminal.

**Comment by DJ-Icebear** [comment]
For me the issue was I was importing types explicitly when not needed:
I removed two lines from the package.json:
```
 "@types/react": "~18.0.0",
 "@types/react-native": "~0.69.1",
```

**Comment by juancsaenz** [comment]
> I had to just make sure the version numbers for: "@types/react" x.x.x and "@types/react-native" y.y.y
> 
> match with: "react": x.x.x and "react-native" y.y.y

It solved my problem, thank you.

**Comment by GtechHardik** [comment]
for me there was wrong version of type script
so 
npm install --save-dev @types/react  @types/react-dom @types/react-native 

solved the issue

**Comment by BrianIto** [comment]
To add more to this specific topic, **I was having this problem with every React Native Built-In Component** (like View, ScrollView, TouchableOpacity, etc.);

- Updating to matching types versions didn't worked;
- Removing the explicit ``@types`` for ``react, react-native, react-dom`` also didn't worked;

for me what solved was @GtechHardik below suggestion:

> for me there was wrong version of type script so npm install --save-dev @types/react @types/react-dom @types/react-native
> 
> solved the issue

https://github.com/eslint/eslint/issues/15802#issuecomment-1223573458

**Comment by kosbog** [comment]
> for me there was wrong version of type script so npm install --save-dev @types/react @types/react-dom @types/react-native
> 
> solved the issue

Perfect solution! Thanks!
