### ISSUE TITLE
Normalize rule names (notably replace `dupe` with `duplicate` in 4 rule names)

### ISSUE THREAD

**Issue by darkred** [eslint/eslint#15824]
### What rule do you want to change?

`no-dupe-args`, `no-dupe-class-members`, `no-dupe-else-if` and `no-dupe-keys`

### What change to do you want to make?

Rename them for normalization.

### How do you think the change should be implemented?

Other

### Example code

```js
(N/A)
```

### What does the rule currently do for this code?

(N/A)

### What will the rule do after it's changed?

(N/A)

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

Currently there are 6 rules https://eslint.org/docs/rules/ that have the word 'duplicate' in their description.
But, from them, only 2 also have 'duplicate' in their name - all 4 others have 'dupe' instead:
![2022-04-30_013620](https://user-images.githubusercontent.com/723651/166077212-70ca1468-9ff1-4286-99c2-407dbe62c359.jpg)
These are: `no-dupe-args`, `no-dupe-class-members`, `no-dupe-else-if` and `no-dupe-keys`

My suggestion is to make these 4 have 'duplicate' instead. The reason is normalization. 

<table>
<tr>
	<td>Old
	<td>New
<tr>
	<td>no-dupe-args
	<td>no-duplicate-args
<tr>
	<td>no-dupe-class-members
	<td>no-duplicate-class-members
<tr>
	<td>no-dupe-else-if
	<td>no-duplicate-else-if
<tr>
	<td>no-dupe-keys
	<td>no-duplicate-keys
</table>

I understand that this could be considered a breaking change for existing config files, so I'd suggest as an approach to use the existing ones as "aliases"/alternative names.

&nbsp;
Similar cases: 

<table>
<tr>
	<td>Old
	<td>New
<tr>
	<td>no-cond-assign
	<td>no-conditional-assign
<tr>
	<td>- all 5 with '-func-'
	<td>'-function-'
<tr>
	<td>no-obj-calls
	<td>no-object-calls
<tr>
	<td>no-undef/no-undef-init
	<td>no-undefined/no-undefined-init
</table>

&nbsp;
Thank you

**Comment by nzakas** [comment]
Thanks for the suggestion. We don’t rename rules once they are released because it is too disruptive to everyone. Unfortunately when a project has been around for eight years with so many different people working on it, there are going to be inconsistencies. We are now more consistent with new rule names.
