### ISSUE TITLE
Remove `require-jsdoc` and `valid-jsdoc` (and `doctrine`)

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#15820]
### ESLint version

v8.14.0

### What problem do you want to solve?

The `require-jsdoc` and `valid-jsdoc` rules were deprecated [a good while ago](https://eslint.org/blog/2018/11/jsdoc-end-of-life), but despite having [replacements in `eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc/wiki/Comparison-with-deprecated-JSdoc-related-ESLint-rules), a major version change hasn't removed them.

### What do you think is the correct solution?

For the next major version, I think we should remove the rules (and the `doctrine` dependency which is only being used by these rules).

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We can put this on the board for v9.0.0.

**Comment by mdjermanovic** [comment]
We have a policy of not removing rules: https://eslint.org/docs/user-guide/rule-deprecation

**Comment by nzakas** [comment]
I think it's at least having a discussion in this case considering that these rules require a dependency that isn't used anywhere else in ESLint.

**Comment by mdjermanovic** [comment]
I would be in favor of removing rules when the benefit is removing dependencies.

Of these two rules, only `valid-jsdoc` requires `doctrine`, so maybe we could leave `require-jsdoc`?

**Comment by nzakas** [comment]
I’d be on board for that.

**Comment by brettz9** [comment]
Just one disadvantage I might mention is that we have our own `jsdoc/require-jsdoc` in `eslint-plugin-jsdoc`. This doesn't conflict, of course, but if more people start partially transitioning because of dropping `valid-jsdoc`, they might get frustrated and report more to ESLint or to `eslint-plugin-jsdoc` inadequacies/mismatches of expected behavior in `require-jsdoc`.

**Comment by nzakas** [comment]
Leaving open to discuss for v9

**Comment by nzakas** [comment]
We will definitely remove `valid-jsdoc` and `doctrine`. Open question if we should also remove `require-jsdoc`.

We'll also need to update our rule deprecation policy:
https://eslint.org/docs/latest/use/rule-deprecation

**Comment by nzakas** [comment]
@mdjermanovic we need to decide if we want to remove `require-jsdoc` or not. I'm still in favor of removing it because there is a replacement in `eslint-plugin-jsdoc`.

**Comment by mdjermanovic** [comment]
I agree with removing `require-jsdoc` as well, and I agree with updating our rule deprecation policy with the clause that a deprecated rule can be removed if there's a replacement in a plugin.

**Comment by nzakas** [comment]
Thanks, I'll update my PR.
