### ISSUE TITLE
Rule Change: (all) Add support to all rules to custom message

### ISSUE THREAD

**Issue by RodrigoTomeES** [eslint/eslint#15821]
### What rule do you want to change?

all

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
module.exports = {
  rules: {
    'no-console': [
      'error',
      {
        "message": "(Example) Use debug function instead of console.log"
      }
    ]
  },
};
```

### What does the rule currently do for this code?

This rules doesn't support custom messages

### What will the rule do after it's changed?

Add a custom message when throw an error like in others rules

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

Thanks for your work ❤️

**Comment by nzakas** [comment]
Thanks for the suggestion. Unfortunately, this is just not practical. There is no way to centrally implement this, so it would mean modifying nearly 300 rules, and that is not only more work than our small team can commit to, but not worth the opportunity cost to attempt.

Remember, you can always create custom rules that do exactly what you want.

**Comment by RodrigoTomeES** [comment]
Okay thanks @nzakas , Is there any example of a custom rule that extends a native rule?
