### ISSUE TITLE
Change Request: no-restricted-syntax documentation link to AST node names 404s

### ISSUE THREAD

**Issue by NilsMoller** [eslint/eslint#15842]
### ESLint version

v8.14.0

### What problem do you want to solve?

The docs page for [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax) has a GitHub link to the AST node names, which leads to a 404.

### What do you think is the correct solution?

Either remove the link, or have it point to the correct web page.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Thanks for finding this! I prepared PR https://github.com/eslint/eslint/pull/15843 to update the link.
