### ISSUE TITLE
Bug: strip-ansi version vulnerability in ansi-regex

### ISSUE THREAD

**Issue by ccalderon9411** [eslint/eslint#15873]
### Environment

Node version:  16.14.2
npm version: 8.5.0
Local ESLint version: 8.15.0
Global ESLint version: 8.15.0
Operating System: Linux, Windows, MacOS

### What parser are you using?

@babel/eslint-parser

### What did you do?

Generate a new porject and run
npm i eslint

### What did you expect to happen?

Update strip-ansi libary to last versión

### What actually happened?

Veracode test detect ansi-regex vulnerability, the libary that use this is strip-ansi

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
No response, so closing.

**Comment by apupier** [comment]
When running npm audit on my project, I got:
```
ansi-regex  5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/mocha/node_modules/ansi-regex
```

```
├─┬ eslint@8.26.0
│   └─┬ strip-ansi@6.0.1
│           └── ansi-regex@5.0.1
```
It requires to move to strip-ansi 7: https://github.com/chalk/strip-ansi/blob/dd40fa7ced678f14dfb43eb9b62b8e7313fb7011/package.json#L50 as it is not fixed in 6.x https://github.com/chalk/strip-ansi/blob/4eba141b36de8153856fbd9a005398ac2747b154/package.json#L47

> Note that we cannot use strip-ansi v7, because it's an ESM-only package.

Is it still the case?

**Comment by mdjermanovic** [comment]
> ansi-regex  5.0.0
> Severity: high
> Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
> fix available via `npm audit fix`
> node_modules/mocha/node_modules/ansi-regex

According to this link, ansi-regex@5.0.1 we are using via strip-ansi@6.0.1 is not affected.

**Comment by apupier** [comment]
> According to this link, ansi-regex@5.0.1 we are using via strip-ansi@6.0.1 is not affected.

you're right, I misinterpreted it. Sorry for the disturbance
