### ISSUE TITLE
Feature: no-useless-return noFix option

### ISSUE THREAD

**Issue by Zamiell** [eslint/eslint#15872]
### What rule do you want to change?

no-useless-return

### What change to do you want to make?

This is a feature request for a new option for the `no-useless-return` rule called "noFix", or something similar.

### Description

Like many JavaScript/TypeScript developers, I have my IDE configured to automatically run Prettier and run ESLint --fix on save. Most of the time, this is absolutely fantastic, and saves me tremendous amounts of time from having to fix common problems manually.

However, one pain point in this workflow is the `no-useless-return` rule. Consider the following code:

```ts
function foo(bar: number | undefined) {
  // Use the "early return" pattern
  if (bar === undefined) {
    return;
  }

  // Do some work with bar
  console.log(bar);
}
```

Commonly, I will have a code snippet like this, and then I will want to debug it. So, I will comment out the `console.log` line, and save the file, with the intent to uncomment it later.

But now, oops, ESLint has deleted my early return. So when I uncomment the `console.log` code, ESLint has subtly caused a bug in my program without me knowing.

Thus, I want there to be a way to configure this rule such that it will not automatically autofix.

(I would even go so far as to say that it probably shouldn't auto-fix by default, but that ship might have sailed.)

Tangent: Are there other ESLint rules that contain this feature (of an optional "noFix)? I tried searching a bit through the GitHub issues, but it was difficult to find anything.

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by nzakas** [comment]
We don’t support the ability to turn off fixing on a per-rule basis in the core. I generally think it’s a bad idea to automatically run ESLint with fixing enabled on save. I don’t know if it’s possible to configure, but there is the `—fix-type` CLI option that allows you to only fix specific types of problems. I’m not sure if the editor plugin supports it, but if not, it may be worth requesting it.

Otherwise, I’d definitely recommend not running ESLint on save. There are probably other subtle issues you haven’t noticed yet, as well. The use case of commenting out code is bound to mess with rules that change or remove code.

**Comment by Zamiell** [comment]
> We don’t support the ability to turn off fixing on a per-rule basis in the core. 

Too bad.

For now, I [forked the plugin rule](https://github.com/IsaacScript/eslint-plugin-isaacscript/blob/main/docs/rules/no-useless-return-no-fix.md) and stripped out the fix function. But consider this a feature request for adding that to the core, because frankly it seems pretty silly that I have to fork the entire rule simply to turn off the auto-fixer. Perhaps we can convert this issue into that?

> I generally think it’s a bad idea to automatically run ESLint with fixing enabled on save

Why?

>  There are probably other subtle issues you haven’t noticed yet, as well.

I've been doing it for years and it has been working fantastic so far! Except for this small issue, that is. I run a pretty extensive ESLint config, using Airbnb as a base.

**Comment by aladdin-add** [comment]
you can use the plugin [eslint-plugin-no-autofix](https://www.npmjs.com/package/eslint-plugin-no-autofix) to turn off the fixer. :)

**Comment by Zamiell** [comment]
That's nifty, thanks.
