### ISSUE TITLE
Rule: No self comparison

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#159]
This rule checks for comparisons where both sides are the same, such as:

``` js
if (x === x) {}
```

The rule ID should be "no-self-compare" and should be on by default.

**Comment by brettz9** [comment]
I might add that linting is useful not only for one's own code, but also for quickly finding errors in other people's code (or changes they have made to your own code)... If it can cause an error, I don't think it is stupid to have the rule--maybe stupid to make the mistake, but hey, we're all human...
