### ISSUE TITLE
[no-duplicate-imports]: issue while using --fix

### ISSUE THREAD

**Issue by slice-anuj** [eslint/eslint#15916]
### Environment

Node version: v16.13.2
npm version: 8.1.2
Local ESLint version:  8.15.0
Global ESLint version: 8.15.0
Operating System: macOS

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>
if two import is similar then, its merge them both which create a new issue which not identified by eslint.
 

`
import {a} from "./foo";
import {a} from "./foo"
`

if do eslint --fix 

`
import { a,a } from "./foo"; # this create new issue duplicate identifier.
`
</summary>

### What did you expect to happen?

`
import {a} from "./foo";
`

### What actually happened?

`
import {a,a} from "./foo";
`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @slice-anuj, thanks for the issue!

The core rule `no-duplicate-imports` doesn't provide fixes. Can you run eslint without `--fix` to see which rule reports this error?

**Comment by mdjermanovic** [comment]
No response, so closing.
