### ISSUE TITLE
Change Request: Support `eslint-expect` in addition to `eslint-disable`

### ISSUE THREAD

**Issue by Twixes** [eslint/eslint#15913]
### ESLint version

v8.4.0

### What problem do you want to solve?

`eslint-disable` is a crucial part of ESLint – without it, any rule false positives would completely ruin the experience, and it'd extremely cumbersome to fix issues gradually (let's say, with multiple smaller PRs instead of one huge one). _After_ the warning/error (no matter if a false positive or a real acknowledged issue) is gone though, it's easy to forget to remove the `eslint-disable` comments. Them lingering on can cause new issues to be inadvertently ignored in the future.

### What do you think is the correct solution?

The TypeScript project has had this exact issue: blanket disabling of typechecking can be useful for a moment, but you want to enable it back as soon as the issue is fixed – otherwise you risk missing some actually important problems in the future. They solved this by [adding `@ts-expect-error`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments) in addition to `@ts-ignore`.

I propose adding support for `eslint-expect-next-line` and `eslint-expect-line` comments, which would work the same as `eslint-disable-next-line` and `eslint-disable-line`, only they would REQUIRE offending rules to be specified and would result in a linting error if any of those rules no longer mark an error on the relevant line.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @Twixes, thanks for the issue! 

> I propose adding support for `eslint-expect-next-line` and `eslint-expect-line` comments, which would work the same as `eslint-disable-next-line` and `eslint-disable-line`, only they would REQUIRE offending rules to be specified and would result in a linting error if any of those rules no longer mark an error on the relevant line.

I think this can already be achieved by using [eslint-comments/no-unlimited-disable](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unlimited-disable.html) rule to require specifying rules, and CLI option [`--report-unused-disable-directives`](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives) or config option [`"reportUnusedDisableDirectives": true`](https://eslint.org/docs/user-guide/configuring/rules#disabling-inline-comments) to report linting errors on unused disable directives.

**Comment by Twixes** [comment]
Thanks! That does indeed seem to solve the use case really well. TBH I'd still be up for adding this to `eslint` just as an exercise if there's interest from someone else in this exact solution, but I'll close for now.
