### ISSUE TITLE
Bug: The parameters in the path are missing - No files matching the pattern

### ISSUE THREAD

**Issue by arleyGuoLei** [eslint/eslint#15921]
### ESLint version

v7.32.0

### What problem do you want to solve?

```bash
npx eslint "/xxx/render$app$copyright#.tsx"   # bin script, my filename render$app$copyright#.tsx

# ------ result ------

Oops! Something went wrong! :(

ESLint: 7.32.0

No files matching the pattern "/xxx/render#.tsx" were found.
Please check for typing mistakes in the pattern.
```

`$app$copyright` The parameters in the path are missing

**Comment by aladdin-add** [comment]
not sure I got your point; can you explain what's the `$app$copyright`?

**Comment by arleyGuoLei** [comment]
> $app$copyright

The file path contains these two strings，my filename is `render$app$copyright#.tsx`

**Comment by arleyGuoLei** [comment]
sorry, glob string `$` has a mistake, resolve
