### ISSUE TITLE
[new docs site] print style is broken

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#15948]
### Environment

`main` branch and `docs-ui-update` branch.

`npm start` in the `docs` directory.

### What parser are you using?

Default (Espree)

### What did you do?

Ctrl-P in Chrome to print the docs homepage.

### What did you expect to happen?

Document without unnecessary navigation elements.

### What actually happened?

With the current `main` version, there is an unnecessary "Table of Contents" select.

<details>
<summary>main branch</summary>

![image](https://user-images.githubusercontent.com/44349756/171070087-50192438-314c-429c-8486-168bb299b5fe.png)

</details>

With the `docs-ui-update` version, there are even more unnecessary elements.

<details>
<summary>docs-ui-update branch</summary>

![image](https://user-images.githubusercontent.com/44349756/171069885-7e55585f-c1e0-4bcb-ae0a-17882552bb83.png)

</details>

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by amareshsm** [comment]
I would like to work this bug. Can I pick this?

**Comment by snitin315** [comment]
> I would like to work this bug. Can I pick this?

@amareshsm Yes, feel free to send a PR
