### ISSUE TITLE
Change Request: Output rule creation time as well as execution time for TIMING environment variable

### ISSUE THREAD

**Issue by mpsijm** [eslint/eslint#15952]
### ESLint version

v8.7.0

### What problem do you want to solve?

ESLint currently shows the rule execution time when setting the environment variable `TIMING=1`. However, as I found in https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/143/commits/487121afb23e22d67f7665cd4292f8621934c261, these timings do not include the time to _create_ a rule. There is currently not really a simple way (except via chrome://inspect/) to figure out that the time to create a rule is taking exceptionally long.

### What do you think is the correct solution?

I would like the `TIMING` table to include the time to create a rule, either by summing it up to the total or by adding a separate column.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @mpsijm, thanks for the issue!

> I would like the `TIMING` table to include the time to create a rule, 

Makes sense to me. I tried this on our codebase and, for example, `lines-around-comment` spends 2x more time in `create()` than in listeners, so the current timing report is not entirely representative.

> either by summing it up to the total or by adding a separate column.

I think summing, but let's hear more opinions from the team.

**Comment by nzakas** [comment]
I like the idea. Can’t go wrong with more data.
