### ISSUE TITLE
New Rule: sort-exports

### ISSUE THREAD

**Issue by RodrigoTomeES** [eslint/eslint#15954]
### Rule details

Should be the same as sort-imports but for exports

### Related ECMAScript feature

export

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
// Without the rule
export { default as SearchBoxDesktop } from './search-box-desktop';
export { default as InstantSearch } from './instant-search';
export { default as SearchBoxMobile } from './search-box-mobile';
export { default as TypingHits } from './typing-hits';
export { default as SuggestionHits } from './suggestion-hits';

export {
  hasChild,
  pickChilds,
  styleInjector,
  classInjector,
  pickChild,
} from './collections';

// With the rule
export { default as InstantSearch } from './instant-search';
export { default as SearchBoxDesktop } from './search-box-desktop';
export { default as SearchBoxMobile } from './search-box-mobile';
export { default as SuggestionHits } from './suggestion-hits';
export { default as TypingHits } from './typing-hits';

export {
  classInjector,
  hasChild,
  pickChild,
  pickChilds,
  styleInjector,
} from './collections';
```

### Why should this rule be in the core instead of a plugin?

Because if there is a rule for imports why not for exports

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

There is a plugin https://github.com/jrdrg/eslint-plugin-sort-exports which has part of the implementation but does not have the autocorrect option and other options that the native import rule has.

**Comment by mdjermanovic** [comment]
Hi @RodrigoTomeES, thanks for the issue!

Per our [rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies), we will only accept new rules when they relate to new ECMAScript features that reached stage 4 in the preceding 12 months, so this rule doesn't qualify. You can always make a custom rule and publish a plugin.

**Comment by RodrigoTomeES** [comment]
@mdjermanovic hi, thanks for your quick reply. I understand your rules policies but I think the request of sort-export is a petition to achieve parity between the rules. It is strange that there is one for imports and not for exports. From ignorance, wouldn't it be possible to take "the code" of the sort-import code for sort-export but replacing the import keyword with export?

**Comment by mdjermanovic** [comment]
We can't cover all stylistic preferences in the core. You can always make a custom rule or a plugin with additional rules.

> wouldn't it be possible to take "the code" of the sort-import code for sort-export but replacing the import keyword with export?

Depends on desired functionalities of the sort-exports rule, but the code of sort-imports would probably be a good starting point.
