### ISSUE TITLE
Change Request: replace dependency

### ISSUE THREAD

**Issue by Semigradsky** [eslint/eslint#15973]
### ESLint version

latest

### What problem do you want to solve?

It is suggestion: to replace [`json-stable-stringify-without-jsonify`](https://github.com/samn/json-stable-stringify) to [`fast-json-stable-stringify`](https://github.com/epoberezkin/fast-json-stable-stringify).
It is totally the same but slightly faster (without `Array.isArray` and `Object.keys` polyfills in code).

`fast-json-stable-stringify` used by `ts-jest`, `@jest/transform`, ...

### What do you think is the correct solution?

Related discussion: https://github.com/eslint/eslint/discussions/15972

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We don’t normally switch dependencies unless there is some significant gain from doing so. There is a nonzero risk in switching from a known dependency that we’ve used for a while to something new for a small performance gain.

If you can quantify the gain as significant, or there is some other value in switching, please let us know.

**Comment by nzakas** [comment]
Closing as we won’t be making this change.
