### ISSUE TITLE
[new docs site] Remove table of contents from markdown text

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#15997]
On each page with a table of contents under the header, the last couple of items in the table of contents are not styled correctly. This happened within the last few days, so it's likely that there's a recent pull request that caused this problem.

Example:
https://new.eslint.org/docs/head/user-guide/configuring/rules

Screenshot:
![Screenshot 2022-06-13 at 11-09-46 Rules](https://user-images.githubusercontent.com/38546/173417566-37f8b68d-e1f2-4d71-b05d-74f7b8a0e81a.png)

## Notes

The documentation site lives in `/docs` of this repo. You can `cd` into that directly, run `npm install` to install the dependencies and `npm start` to run locally.

**Comment by mdjermanovic** [comment]
> On each page with a table of contents under the header, the last couple of items in the table of contents are not styled correctly.

By the last couple of items that are not styled correctly, did you mean this?

![image](https://user-images.githubusercontent.com/44349756/173431044-82a56863-e9d4-48fb-8e26-0882551a5232.png)

This is table of contents we manually added to this document:

https://github.com/eslint/eslint/blob/1324f10ac58d3685fdb656a4fc9d1e5c9d035e42/docs/src/user-guide/configuring/rules.md?plain=1#L13-L14

For the new site, we should probably just remove it?

**Comment by nzakas** [comment]
Yes that’s it. I didn’t even think we had added that manually. Yes, we should remove it from the markdown text.
