### ISSUE TITLE
[new docs site] Disable ligatures in code examples

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16012]
For example, `</` and `/>` form arrows.

![image](https://user-images.githubusercontent.com/44349756/174188694-30372271-6a7d-4a95-a788-019b951b48ce.png)

https://new.eslint.org/docs/head/rules/jsx-quotes

In the playground, this was fixed by https://github.com/eslint/playground/pull/65

**Comment by snitin315** [comment]
I'll fix it here.

**Comment by harish-sethuraman** [comment]
Just noticed the issue and I had already made a PR sorry 😅 
- https://github.com/eslint/eslint/pull/16019
