### ISSUE TITLE
[new docs site] Broken line numbers in code blocks

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16042]
Something's wrong with the line numbers in _some_ code blocks.

For example https://new.eslint.org/docs/head/rules/function-paren-newline, see `bar` and `baz` lines.

![image](https://user-images.githubusercontent.com/44349756/175111595-846ab83e-25c8-48e0-ae45-a39ce26a3ed4.png)

Note that this isn't caused by the recently added `::: correct` / `::: incorrect` containers because it was the same without them:

https://new.eslint.org/docs/latest/rules/function-paren-newline

**Comment by DeepshikaS** [comment]
The `bar` and `baz` lines should be considered as highlight-line but it is currently being considered as a token, thus it's not coming in a new line. I will look into this.

**Comment by nzakas** [comment]
@DeepshikaS are you still working on this?

**Comment by DeepshikaS** [comment]
> @DeepshikaS are you still working on this?

The default behavior of the 11ty syntax highlighting seems to be causing the issue- https://github.com/falldowngoboone/falldowngoboone-com/issues/116.
I'm trying to find out if there is any other way to solve it.

**Comment by nzakas** [comment]
Another example of this:
https://eslint.org/docs/latest/developer-guide/package-json-conventions#names
