### ISSUE TITLE
Determine where prerelease docs go

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16041]
With the new documentation site, we push to the `latest` branch with each release. This causes the docs to show up at `/docs/latest/` (instead of `/docs/head/`).

When we do a prerelease, where do we want those docs to go? Maybe `/docs/next/` so that `/docs/latest/` preserves the docs for the latest official release?

This will need to be updated in `Makefile.js`.

**Comment by mdjermanovic** [comment]
> Maybe `/docs/next/` so that `/docs/latest/` preserves the docs for the latest official release?

:+1:  for `/docs/next/`

**Comment by btmills** [comment]
:+1: to `/docs/next/` as well. Matches npm tags.

**Comment by nzakas** [comment]
Sounds like we have an agreement on this. If someone feels like picking this up, feel free. Otherwise we can wait for the next major release to address.

**Comment by Gautam-Arora24** [comment]
Would like to work on this.

**Comment by snitin315** [comment]
@Gautam-Arora24 go ahead.

**Comment by nzakas** [comment]
This will involve two steps:

1. Makefile.js needs to be updated to push to the “next” branch during prerelease instead of “latest”.
2. We need to update the docs site to use pathPrefix of “/docs/next/“ when deployed from the “next” branch. We also need the drop down to be updated to include “NEXT” beneath “HEAD”.

**Comment by Gautam-Arora24** [comment]
Thanks for the explanation @nzakas

**Comment by amareshsm** [comment]
@Gautam-Arora24 Are you still working on this? I would like to work on this.

**Comment by Gautam-Arora24** [comment]
@amareshsm You can work on this.

**Comment by amareshsm** [comment]
I will send a PR.
