### ISSUE TITLE
Bug: no-useless-return triggers wrongly in switch

### ISSUE THREAD

**Issue by mkahvi** [eslint/eslint#16055]
### Environment

Node version: v16.15.0
npm version: v8.11.0
Local ESLint version: v8.17.0     
Global ESLint version: Not found  
Operating System: win32 10.0.19043

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
'no-useless-return': ['error'],
```
</details>

```js
function doot(blah) {
  switch (blah) {
    case something:
      return;
    case somethingElse:
      doSomethingReal();
      break;
  }
}
```

### What did you expect to happen?

The return statement to be kept.

### What actually happened?

Return is removed, making the case bleed over to the other one.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mkahvi** [comment]
I know I could've written break in the example, but I was in process of writing much longer code and the return is needed when it's fully done. Pretty sure return isn't any more useless than break there either way.

**Comment by mdjermanovic** [comment]
Hi @mkahvi, thanks for the issue!

> ```js
> function doot(blah) {
>   switch (blah) {
>     case something:
>       return;
>     case somethingElse:
>       doSomethingReal();
>       break;
>   }
> }
> ```

I can't reproduce this error. Here's [your example in ESLint playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVzZWxlc3MtcmV0dXJuOiBbJ2Vycm9yJ10gKi9cblxuZnVuY3Rpb24gZG9vdChibGFoKSB7XG4gIHN3aXRjaCAoYmxhaCkge1xuICAgIGNhc2Ugc29tZXRoaW5nOlxuICAgICAgcmV0dXJuO1xuICAgIGNhc2Ugc29tZXRoaW5nRWxzZTpcbiAgICAgIGRvU29tZXRoaW5nUmVhbCgpO1xuICAgICAgYnJlYWs7XG4gIH1cbn1cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnsiZXM2Ijp0cnVlfX19), and `no-useless-return` doesn't report this `return` statement. I also tried locally with the latest `@babel/eslint-parser` and the result is same.

Is the example exactly the same as the code in which you see this error?

**Comment by mkahvi** [comment]
Alright, I'm guessing it was only issue when writing up the structure before any code, as removing the function call makes it trigger as reported, which I guess technically is right for the error?
```js
function doot(blah) {
  switch (blah) {
    case something:
      return;
    case somethingElse:
      break;
  }
}
```

**Comment by snitin315** [comment]
> Alright, I'm guessing it was only issue when writing up the structure before any code, as removing the function call makes it trigger as reported, which I guess technically is right for the error?

Yes. That seems to be the intended behavior to me.
