### ISSUE TITLE
Bug: calling eslint from yarn hits the roof in memory consumption

### ISSUE THREAD

**Issue by SDAdham** [eslint/eslint#16053]
### Environment

Node version: v14.15.3
npm version: v6.14.9
Local ESLint version: v8.18.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.18.4-1-default

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I have 2 commands:

- `npx eslint -c ./.eslintrc.json projects/<sub-project>/**/*.ts --ext ts`
- `yarn lint` which runs the same command above but without `npx`

### What did you expect to happen?

Both to have an equal usage in memory

### What actually happened?

Running `npx eslint -c ./.eslintrc.json projects/<sub-project>/**/*.ts --ext ts` results with `301-322 MB` memory consumption and a single process in `system monitor` as observed (top-like in unix)

But running `yarn lint` leads to 3 processes where 2 are relatively small in memory consumption but the main one hits the roof with `1.3 GB`.

![image](https://user-images.githubusercontent.com/11182824/175761560-8dfcf90e-638a-4497-b55d-0aae5428327a.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Shouldn't both commands should be identical when any runs? Why the different behavior and the major discrepancy in memory consumption?

**Comment by nzakas** [comment]
Please contact the typescript-eslint team about this. It’s an issue with that plugin, not ESLint itself.
