### ISSUE TITLE
Remove duplicate rule descriptions

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16051]
For the rule documentation page, there are currently two descriptions being shown: one right under the page title and one under the table of contents. Two tasks for each rule:

1. The one under the table of contents is hardcoded into the markdown files and should be removed. These files are all in `docs/src/rules`.
2. The one under the title is pulled from the rule's meta information, so we need to go through and capitalize those descriptions. These files are all in `lib/rules`.

![Screenshot 2022-06-24 at 11-30-13 semi - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/38546/175644805-34f320da-a0e9-4af4-a4c7-59002a43badd.png)

**Comment by amareshsm** [comment]
I would like to work on this. I will send a PR.

**Comment by nzakas** [comment]
Thanks!
