### ISSUE TITLE
Bug: eslint-disable does not work in comment blocks or in slashed comments

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#16065]
### Environment

Node version: v16.14.2
npm version: v8.12.1
Local ESLint version: Not found
Global ESLint version: v8.17.0 (Currently used)
Operating System: linux 4.18.0-348.7.1.el8_5.x86_64

### What parser are you using?

Default (Espree)

### What did you do?

Tried to disable eslint with comment:

```js
/**
 * this is my JS file
 *
 * eslint-disable
 */
```

```js
/**
 * this is my JS file
 *
 * eslint-disable no-console
 */
```

```js
// eslint-disable
```

```js
// eslint-disable no-console
```

### What did you expect to happen?

That eslint-disable actually disables the rule, like when I do:

```js
/* eslint-disable */
```

```js
/* eslint-disable no-console */
```

### What actually happened?

Still got eslint errors

**Comment by mdjermanovic** [comment]
Hi @kkmuffme, thanks for the issue!

This works as intended. [`eslint-disable`](https://eslint.org/docs/latest/user-guide/configuring/rules#disabling-rules) can only be used in block comments (`/**/`), and the comment must start with `eslint-disable`.

> ```js
> /**
>  * this is my JS file
>  *
>  * eslint-disable
>  */
> ```
> 
>   
> ```js
> /**
>  * this is my JS file
>  *
>  * eslint-disable no-console
>  */
> ```

These comments do not start with `eslint-disable`, so ESLint doesn't interpret them as eslint-disable directives.

> ```js
> // eslint-disable
> ```
>   
> ```js
> // eslint-disable no-console
> ```

As mentioned, `eslint-disable` cannot be used in line comments (`//`). This might be allowed in some of the future versions (see https://github.com/eslint/eslint/issues/14575 and https://github.com/eslint/eslint/issues/14960).
