### ISSUE TITLE
Bug: eslint fixer.replaceText on TemplateElement is breaking the syntax

### ISSUE THREAD

**Issue by mozfreddyb** [eslint/eslint#16061]
### Environment

Node version: v18.3.0
npm version: 8.11.0
Local ESLint version: 8.18 
Global ESLint version: None
Operating System: darwin 21.5.0

### What parser are you using?

Default (Espree)

### What did you do?

We are developing a patch for an existing plugin. The new functionality should work with TemplateElemenets.

```js

export default {
  meta: {fixable: "code" },
  create: function(context) {
    return {
      TemplateElement(node) {
        if (node.value.raw.includes("http://")) {
        context.report({
          node,
          message: 'Do not http in tests',

          fix(fixer) {
            let r = node.value.raw.replace("http://", "https://");
            return fixer.replaceText(node, r);
          },
        });
        }
      }
    };
  }
};
```
We also have a reproducer here on [ast-explorer.net](https://astexplorer.net/#/gist/b43387fd73310921b6c10a502b3e69c0/4f6d8a16473a63df66b4b296dfa3250ad4b1aa7a)

### What did you expect to happen?

Input source code like this
```js
let origin = "foo";
a=`http://${origin}/pfad/foof\x25oo`;
```
Should be replaced such that the first TemplateElement is `https` (with the s!):
```js
let origin = "foo";
a=`https://${origin}/pfad/foof\x25oo`;
```

### What actually happened?

eslint is messing up the template string:
```js
let origin = "foo";
a=https://origin}/pfad/foof\x25oo`;
```
Please observe the missing starting backtick and the missing `${`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Depending on the complexity of the underlying issue, I *might* be able to submit a pull request for this.

**Comment by mdjermanovic** [comment]
Hi @mozfreddyb, thanks for the issue!

> ```js
> fix(fixer) {
>  let r = node.value.raw.replace("http://", "https://");
>  return fixer.replaceText(node, r);
>},
> ```

> ```js
> let origin = "foo";
> a=https://origin}/pfad/foof\x25oo`;
> ```

This works as intended.  `fixer.replaceText` replaces the range of `node`, which starts with a backtick and ends with `${`, with text `r` that doesn't include a backtick and `${`.

```
a=`http://${origin}/pfad/foof\x25oo`;
  ^^^^^^^^^^      ^^^^^^^^^^^^^^^^^^
TemplateElement    TemplateElement
```

`TemplateElement#value.raw` represents [TRV](https://tc39.es/ecma262/#sec-static-semantics-trv) (values passed to tag functions as [raw strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#raw_strings)) which doesn't include backticks, `${` and `}`. Unlike `Literal#raw`, this is not raw text from source code. In your example, `node.value.raw` is `http://` string, so at the end `fixer.replaceText(node, r)` replaces `` `http://${ `` with `https://`.

You can use `SourceCode#getText` to get raw TemplateLiteral text from the source code:

```js
fix(fixer) {
  let r = context.getSourceCode().getText(node).replace("http://", "https://");
  return fixer.replaceText(node, r);
}
```

**Comment by mozfreddyb** [comment]
Thank you for the quick feedback! This worked. 🥳
