### ISSUE TITLE
Bug: @types/eslint/-/eslint-8.4.4.tgz - Not found error on npm install

### ISSUE THREAD

**Issue by erdemgonul** [eslint/eslint#16074]
### Environment

Node version: v16.15.1
npm version: v8.11.0
Operating System: MacOS

### What did you do?

After I delete my package-lock.json I can not run **'npm install'** successfully.

### What did you expect to happen?

I expect to install packages successfully

### What actually happened?

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by czuniga9** [comment]
I have the same issue when trying to install laravel-mix (which has a direct dependency to eslint), you can reproduce it with this:

```
mkdir foo && cd foo
npm init # accept all defaults
npm i laravel-mix
```

**Comment by DCampagnola** [comment]
There is a new version in @types/eslint but DefinitelyTyped hasn't updated it in npm.
As said in this FAQ, it should be fixed in minutes.

[My PR is merged; when will the @types npm package be updated?](https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated)

**Comment by erdemgonul** [comment]
We can see the new version in here. There should be another problem here. 
https://www.npmjs.com/package/@types/eslint/v/8.4.4

**Comment by Foozie3Moons** [comment]
Yes, the version is published, but https://registry.yarnpkg.com/@types/eslint/-/eslint-8.4.4.tgz is still 404ing.

**Comment by Victugord** [comment]
Still gives  GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz error (ERR_PNPM_FETCH_404)

**Comment by claytongroth** [comment]
I am also encountering this issue.

**Comment by mdjermanovic** [comment]
Thanks for the issue!

The [@types/eslint](https://www.npmjs.com/package/@types/eslint) package isn't maintained by the ESLint team.

If there are problems with it, please open an issue here:

https://github.com/DefinitelyTyped/DefinitelyTyped
