### ISSUE TITLE
User Guide has broken links

### ISSUE THREAD

**Issue by IncPlusPlus** [eslint/eslint#16072]
### ESLint version

v8.18.0

### What problem do you want to solve?

On the [configuring](https://eslint.org/docs/latest/user-guide/configuring) area of the ESLint docs, the links to other sections are all broken (on the main content of the page, not the navigation sidebar) and bring me to a 404. For example, clicking the Configuration Files directs to the URL https://eslint.org/docs/latest/user-guide/configuration-files when it should be directing to https://eslint.org/docs/latest/user-guide/configuring/configuration-files. It seems that the "/configuring" section of the link is missing.

### What do you think is the correct solution?

I looked at the markdown files in `eslint/tree/main/docs/src/user-guide/configuring`. It seems that the links in [`index.md`](https://github.com/eslint/eslint/blob/main/docs/src/user-guide/configuring/index.md?plain=1#L29) _do_ point to the right relative location (besides the missing .md file extension which I assume is something done intentionally and unrelated to this issue) so I'm not too sure what the problem is.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
I think  removing the `./` in the `./configuration-files#configuration-file-formats` path should fix the issue? Works for me in local. Would you like to send a PR and verify the fix in preview if you have any? 

https://github.com/eslint/eslint/blob/3ae0574fc78c4a2b406625e4792cb2859cb9bcb1/docs/src/user-guide/configuring/index.md?plain=1#L31

**Comment by mdjermanovic** [comment]
This is fixed by https://github.com/eslint/eslint/pull/16046, but the `latest` branch has not been updated yet.

I'll leave this open to doublecheck after tomorrow's release (https://github.com/eslint/eslint/issues/16029) which will update the content under `https://eslint.org/docs/latest/`

**Comment by harish-sethuraman** [comment]
This has been fixed in the main as well :) We can close this issue.

**Comment by mdjermanovic** [comment]
> On the [configuring](https://eslint.org/docs/latest/user-guide/configuring) area of the ESLint docs, the links to other sections are all broken (on the main content of the page, not the navigation sidebar) and bring me to a 404

This is fixed now on the website. @IncPlusPlus thanks for reporting the problem!
