### ISSUE TITLE
Bug: func-style not working in a class

### ISSUE THREAD

**Issue by PierBJX** [eslint/eslint#16091]
### Environment

Node version: 16.15.1
npm version: 8.11.0
Local ESLint version: 8.18.0
Global ESLint version: N/A
Operating System: Windows 10

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "root": true,
  "rules": {
    "func-style": [
      "error",
      "declaration",
      {
        "allowArrowFunctions": true
      }
    ]
  }
}

```
</details>

```js
class myClass {
  test = function (): void {
    console.log('test');
  };
}

const test = function (): void {
  console.log('test');
};
```
[Reproducible link](https://eslint.org/play/#eyJ0ZXh0IjoiY2xhc3MgbXlDbGFzcyB7XG4gIHRlc3QgPSBmdW5jdGlvbiAoKSB7XG4gICAgY29uc29sZS5sb2coJ3Rlc3QnKTtcbiAgfTtcbn1cblxuY29uc3QgdGVzdCA9IGZ1bmN0aW9uICgpIHtcbiAgY29uc29sZS5sb2coJ3Rlc3QnKTtcbn07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJmdW5jLXN0eWxlIjpbImVycm9yIiwiZGVjbGFyYXRpb24iLHsiYWxsb3dBcnJvd0Z1bmN0aW9ucyI6dHJ1ZX1dfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)

### What did you expect to happen?

I expect ESLint to throw this error (`ESLint: Expected a function declaration.(func-style)`) two times: 
- one for the function inside the class 
- one for the function outside the class.

### What actually happened?

There is only one error for the function outside the class.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @PierBJX, thanks for the issue!

> There is only one error for the function outside the class.

This works as intended. The option `"declaration"` enforces the use of function declarations instead of variables initialized to functions. It doesn't disallow the use of function expressions in other contexts such as callbacks or class field initializers.

> ```js
> const test = function (): void {
>   console.log('test');
> };
> ```

This is the case this option is intended to report, and it expects the variable declaration to be replaced with a function declaration:

```js
function test(): void {
   console.log('test');
}
```

> ```js
> class myClass {
>   test = function (): void {
>     console.log('test');
>   };
> }
> ```

Enforcing the use of function _declarations_, in this case, would require declaring another variable in an outer scope:

```js
function test(): void {
   console.log('test');
}

class myClass {
  test = test;
}
```

This is not what this rule was intended to enforce. Note that this rule only enforces `function test` <-> `const test = function` style. It doesn't enforce the use of methods in object literals and classes.

**Comment by PierBJX** [comment]
Thanks for you quick answer @mdjermanovic 

Is there any alternative for that ?
Indeed, we are moving from tslint to eslint and this [rule](https://palantir.github.io/tslint/rules/only-arrow-functions/) was checking func style in both case.

**Comment by mdjermanovic** [comment]
> Is there any alternative for that ?
> Indeed, we are moving from tslint to eslint and this [rule](https://palantir.github.io/tslint/rules/only-arrow-functions/) was checking func style in both case.

There isn't a core rule that specifically enforces this, but you could configure the [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule to disallow the use of function expressions as class field initializers:

```json
{
    "rules": {
        "no-restricted-syntax": ["error", {
            "selector": "PropertyDefinition > FunctionExpression.value",
            "message": "Use method or arrow function instead of the function expression."
        }]
    }
}
```

Here's a [playground example](https://eslint.org/play#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtc3ludGF4OiBbXCJlcnJvclwiLCB7XG4gICAgc2VsZWN0b3I6IFwiUHJvcGVydHlEZWZpbml0aW9uID4gRnVuY3Rpb25FeHByZXNzaW9uLnZhbHVlXCIsXG4gICAgbWVzc2FnZTogXCJVc2UgbWV0aG9kIG9yIGFycm93IGZ1bmN0aW9uIGluc3RlYWQgb2YgdGhlIGZ1bmN0aW9uIGV4cHJlc3Npb24uXCJcbn1dICovXG5cbmNsYXNzIG15Q2xhc3Mge1xuICB0ZXN0ID0gZnVuY3Rpb24gKCkge1xuICAgIGNvbnNvbGUubG9nKCd0ZXN0Jyk7XG4gIH07XG59XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==).

(I wasn't sure if the goal is to enforce the use of methods or arrow functions, but you can change the message accordingly)

**Comment by PierBJX** [comment]
Thank you, it works very well!

Do you think, I could make this rule doing the same job that `func-style`? Like this, I could have the same custom output message?
