### ISSUE TITLE
Bug: comma-spacing is conflicting with array-bracket-spacing

### ISSUE THREAD

**Issue by MiloParigi** [eslint/eslint#16100]
### Environment

Node version: v16.15.1
npm version: v8.11.0
Local ESLint version: v8.18.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.4.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

You can see an ESLint demo [here](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHF1b3RlczogW1wiZXJyb3JcIiwgXCJkb3VibGVcIl0gKi9cbmxldCBhID0gWzEsIDIsIDMsIDQsIF07XG5sZXQgYiA9IFsxLCAyLCAzLCA0LF07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJhcnJheS1icmFja2V0LXNwYWNpbmciOlsid2FybiIsIm5ldmVyIl0sImNvbW1hLXNwYWNpbmciOlsid2FybiIseyJiZWZvcmUiOmZhbHNlLCJhZnRlciI6dHJ1ZX1dfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "browser": true,
        "es2020": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": ["@typescript-eslint"],
    "rules": {
        "comma-spacing": ["warn", { "before": false, "after": true }],
        "array-bracket-spacing": ["warn", "never"],
        "comma-dangle": "off",
    }
}

```
</details>

```js
tsts = [1, 2, 3, 4,];  // A space is required after ','. eslint(comma-spacing)
tsts = [1, 2, 3, 4, ];  // There should be no space before ']'. eslint(array-bracket-spacing)
```

### What did you expect to happen?

I was expecting the `array-bracket-spacing` rule to take over the `comma-spacing` rule and allow the first line as linted

### What actually happened?

- `array-bracket-spacing` requires there to be no space before the close bracket
- `comma-spacing` requires there to be a space after the final comma

Therefore, we have a conflict.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This issue is related to this [issue (#9760)](https://github.com/eslint/eslint/issues/9760) which was closed due to lack of interest.

**Comment by mdjermanovic** [comment]
Hi @MiloParigi, thanks for the issue!

> I was expecting the `array-bracket-spacing` rule to take over the `comma-spacing` rule and allow the first line as linted

I agree. `comma-spacing` already ignores spacing before `)` to avoid conflicts with other rules. It should ignore spacing before `]` and `}` as well. I'm working on this.
