### ISSUE TITLE
Change Request: Allow processors to report syntax errors

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#16104]
### ESLint version

v8.19.0

### What problem do you want to solve?

Originally discussed in https://github.com/eslint/eslint/discussions/16015, the `@graphql-eslint/graphql` processor is encountering a syntax error in the file that is being processed (the "physical" file, if code blocks are "virtual" files). That syntax error results in an exception thrown within the processor that currently crashes the entire lint run. It would be better if processors could report syntax errors like other parsers without crashing the whole process.

### What do you think is the correct solution?

We should mimic [`parse()`'s behavior](https://github.com/eslint/eslint/blob/ae4b449719d496fd611903d596341ec4c1d81c16/lib/linter/linter.js#L844-L851) by wrapping the [`preprocess()` call](https://github.com/eslint/eslint/blob/ae4b449719d496fd611903d596341ec4c1d81c16/lib/linter/linter.js#L1793) in `try`/`catch` and transforming the exception thrown by the processor into a lint error.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

In the [discussion](https://github.com/eslint/eslint/discussions/16015#discussioncomment-3071575), @JounQin asked to take this, but I'm also willing to tackle it as a fallback if necessary.

**Comment by JounQin** [comment]
Thanks for pinning, I'm going to work on a fix soon, then.

**Comment by JounQin** [comment]
@btmills Done in #16105.
