### ISSUE TITLE
Bug: Anchor link missing on headers

### ISSUE THREAD

**Issue by bmish** [eslint/eslint#16128]
### URL(s)

Any page on the new ESLint website. Example: https://eslint.org/docs/latest/developer-guide/working-with-rules

### What did you do?

Hover over section header. For example, the "Rule Basics" section header.

### What did you expect to happen?

An anchor link icon to appear that can be used to directly link to a particular header inside a page. The direct section link https://eslint.org/docs/latest/developer-guide/working-with-rules#rule-basics can only be found in the table of contents now.

### What actually happened?

Nothing.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

From my memory, this feature was present on the old website, but is missing on the new website. It is also a standard convenience feature on GitHub markdown pages and many other documentation sites.

**Comment by harish-sethuraman** [comment]
I believe we were using https://www.npmjs.com/package/anchor-js to add anchors to the heading elements in the archive website. If we want to do the same i'm up for grabs to change it in all docs site :)

**Comment by nzakas** [comment]
@harish-sethuraman yes, please go ahead. 🙏
