### ISSUE TITLE
Option for sort-vars grouping

### ISSUE THREAD

**Issue by solmsted** [eslint/eslint#1612]
The `sort-vars` rule enforces alphabetical ordering of variable definitions per block.  This is a nice feature but it's not always practical especially when there are a large number of variables.  It would be much more useful if alphabetical ordering could be enforced on groups of variables with groups being defined by blank lines.  For example:

```
var x,
    y,
    z,

    a,
    b,
    c;

var u;
var v;
var w;

var i;
var j;
var k;
```

This example would pass because the variable names are in order within each group.

**Comment by jacobrask** [comment]
Please add a comment here if you create such a plugin, so that I and others that are interested will be notified. Thanks.
