### ISSUE TITLE
Bug: documentation site is missing links for versions older than v8.19.0

### ISSUE THREAD

**Issue by monkpit** [eslint/eslint#16124]
### Environment

<img width="528" alt="image" src="https://user-images.githubusercontent.com/5297293/178577175-8735dcd9-6d3a-4021-8991-25870dc61dfd.png">

The documentation site seems to be missing all old versions of eslint.

### What parser are you using?

Other

### What did you do?

Visit the documentation: https://eslint.org/docs/latest/

### What did you expect to happen?

Expected to be able to browse the documentation at v7.32.0 to diagnose some issue I was seeing.

### What actually happened?

The only version that is selectable is v8.19.0

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Thanks for all of your hard work :)

**Comment by nzakas** [comment]
Yeah, we didn’t actually have previous versions of documentation published separately. The goal is to do that going forward, so new versions will be added in the drop down but we don’t have the bandwidth to pull out old docs and get them formatted in the new docs site.

You can still see the raw docs in the repo, though:
https://github.com/eslint/eslint/tree/v7.32.0/docs
