### ISSUE TITLE
Allow exceptions in no-shadow rule

### ISSUE THREAD

**Issue by goloroden** [eslint/eslint#1613]
Basically, the `no-shadow` rule is a great one and makes a lot of sense.

Anyway, there is one scenario where shadowing is (IMHO) perfectly fine, hence I'd love to have the possibility to add exceptions to the `no-shadow` rule.

This scenario is the `err` parameter name, as seen in callbacks:

    doSomething(function (err) {
      doSomethingElse(function (err) {
        // ...
      });
    });

Here, the `no-shadow` rule complains about the second `err` shadowing the first one, but IMHO this is perfectly fine and common in Node.js programming.

What do you think about this?

**Comment by goloroden** [comment]
After having thought about this, I think you are right. It actually is probably not the best idea to have multiple `err` objects, and I like the style that @gcochard pointed out. Hence, regard this issue as irrelevant :-).

Sorry for the inconveniences, but thanks for the great discussion :-)

**Comment by dwelle** [comment]
I still think there should be an opt-in option to disable argument checking.
