### ISSUE TITLE
Change Request: Better documentation for Scopes

### ISSUE THREAD

**Issue by Yash-Singh1** [eslint/eslint#16148]
### ESLint version

N/A

### What problem do you want to solve?

Currently, the documentation just contains a [reference](https://eslint.org/docs/latest/developer-guide/scope-manager-interface) for the `ScopeManager` and `Scope` interfaces. There aren't any basic examples to using it such as `context.report` and `fixer`.

### What do you think is the correct solution?

Add some simple examples to the of using the `ScopeManager` to the `Working with Rules` page.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We are looking at rewriting the docs from scratch going forward. While we don’t have a timeline, you’ll see some improvements. 

In the meantime, if anyone wants to update the current docs for this, please feel free to submit a pull request.
