### ISSUE TITLE
Change Request: (I want to use the configuration in the conf directory externally) 

### ISSUE THREAD

**Issue by NieZhuZhu** [eslint/eslint#16152]
### ESLint version

`>=8`

### What problem do you want to solve?

I want to use the configuration in the conf directory externally

### What do you think is the correct solution?

`package.json` add exports for the conf directory

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
does the `--config` works for you?

**Comment by nzakas** [comment]
We aren’t making any changes to the current config system while we work on the new one.

**Comment by NieZhuZhu** [comment]
> We aren’t making any changes to the current config system while we work on the new one.

When will the new config system be ready 🤣

**Comment by aladdin-add** [comment]
they had been exported. you can already use:
```js
"extends": ["eslint:recommended"],
// or "extends": ["eslint:all"],
```

**Comment by NieZhuZhu** [comment]
> they had been exported. you can already use:
> 
> ```js
> "extends": ["eslint:recommended"],
> // or "extends": ["eslint:all"],
> ```

I am not end-user, I am developer user. Before version 8 I could use it like this
```js
require('eslint/conf/eslint-recommended').rules

```
But now I can only use it like this

```js
require(`${__dirname}/../node_modules/eslint/conf/eslint-recommended`).rules

```
Useful but ugly and not make sense 🙈
