### ISSUE TITLE
`dot-notation` with `allowKeywords` false incorrectly reports `.throws` as a syntax error

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#1616]
In IE 6, 7, and 8, `var a = { throws: 3 }, b = a.throws, throws = 42; [a,b,throws]` does not trigger a syntax error.

However, when using `dot-notation` with `allowKeywords` set to `false`, `assert.throws(…)` is reported as a syntax error by the `dot-notation` rule. This conflicts with jshint, which correctly allows this form in `es3` mode.

**Comment by nzakas** [comment]
If you're offering, I'll gladly accept a pull request to do that :)

**Comment by nzakas** [comment]
@ljharb are you still planning on researching this?

**Comment by ljharb** [comment]
Yes - sorry for the delay. Is it OK to shoot for getting back to you within the next week?

**Comment by nzakas** [comment]
Yup!

**Comment by ljharb** [comment]
Still haven't had a chance to finish researching this :-/ but still planning to work on it.

**Comment by nzakas** [comment]
Thanks for the update.

**Comment by nzakas** [comment]
@ljharb are you still planning on doing this?

**Comment by ljharb** [comment]
I'd definitely still like the feature, but unfortunately I still haven't made the time to do the research.

If anyone else has the time to take it on, that'd be appreciated!

**Comment by gyandeeps** [comment]
I guess nobody is interested to get this enhancement done, which tells me that nobody has is coding in this fashion. Also we are going to hit 1 year mark in few days.
Can we close this?

**Comment by ljharb** [comment]
I am coding in this fashion, in many modules. I simply disable the rule in the meantime.

I don't understand the compulsion to close an issue that is still outstanding. I really do want this change made, and despite not having the time to do it yet, I hope someone will discover it and volunteer to do so. Closed issues are not discoverable.

**Comment by nzakas** [comment]
We close issues that we don't plan on doing. If something has been open for a year, that means it hasn't been a priority and the chances it will become a priority are slim. I'd rather have people focused on the issues we need to get done, and there's no better way to indicate that then to close the ones we don't anticipate being done.

And people do comment on closed issues fairly frequently in ESLint, so it seems like discoverability isn't a big problem. Plus, people frequently open new issues without checking old ones, so we tend to hear the same request multiple times if it ends up important.

**Comment by ljharb** [comment]
Closing for now, then.
