### ISSUE TITLE
Bug: priority of no-lonely-if over no-else-return is wrong

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#16171]
### Environment

[Playground](https://eslint.org/play/#eyJ0ZXh0IjoiZnVuY3Rpb24gZm9vKCkge1xuICAgIGlmIChmb28pIHtcbiAgICAgICAgcmV0dXJuIGZvbztcbiAgICB9IGVsc2Uge1xuICAgICAgICBpZiAoYmFyKSB7XG4gICAgICAgICAgICByZXR1cm4gYmFyO1xuICAgICAgICB9XG4gICAgfVxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tbG9uZWx5LWlmIjpbImVycm9yIl0sIm5vLWVsc2UtcmV0dXJuIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19)

### What parser are you using?

Default (Espree)

### What did you do?

[Playground](https://eslint.org/play/#eyJ0ZXh0IjoiZnVuY3Rpb24gZm9vKCkge1xuICAgIGlmIChmb28pIHtcbiAgICAgICAgcmV0dXJuIGZvbztcbiAgICB9IGVsc2Uge1xuICAgICAgICBpZiAoYmFyKSB7XG4gICAgICAgICAgICByZXR1cm4gYmFyO1xuICAgICAgICB9XG4gICAgfVxufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tbG9uZWx5LWlmIjpbImVycm9yIl0sIm5vLWVsc2UtcmV0dXJuIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19)

### What did you expect to happen?

When eslint auto-fix is enabled, "no-lonely-if" has priority over "no-else-return". However the reverse would be better, as multiple separate "if" are preferred to an "else if" in this case, otherwise the code would already have an else if I guess?

### What actually happened?

Fixed no-lonely-if first

**Comment by mdjermanovic** [comment]
Hi @kkmuffme, thanks for the issue! 

> When eslint auto-fix is enabled, "no-lonely-if" has priority over "no-else-return"

I can't reproduce this. `no-else-return` by design replaces the whole function and thus has precedence over `no-lonely-if`. 

For this code:

```js
function foo() {
    if (foo) {
        return foo;
    } else {
        if (bar) {
            return bar;
        }
    }
}
```

I'm getting the following code after running eslint with `--fix`:

```js
function foo() {
  if (foo) {
      return foo;
  } 
      if (bar) {
          return bar;
      }
  
}

```

Can you provide steps to reproduce this behavior locally, as the order of fixes cannot be determined from the playground?
