### ISSUE TITLE
ES6 Rule Wishlist

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#1617]
There are a lot of new features included in ES6. I know ESLint is working hard to support them. There is no doubt going to be a long list of rules that are likely going to be needed as more features of ES6 are supported. I'd like to propose this as the place where we can discuss feature requests for ES6 rules that maybe aren't quite ready to be made into full-on feature requests. If you'd prefer this on the mailing list (or as separate issues) let me know.

- no `var` (prefer `let` and `const` for everything
- Prefer `setPrototypeOf` to `__proto__`
- Enforce `*` location for generator functions `function* bazooka` or `function *bazooka` 
- Prefer `super` to `Class.prototype.methodName.apply(this, arguments)` or variations
- Avoid `arguments` completely
- Avoid `toMethod` (possibly, it just seems like a a weird edge to me and not normally used)
- Use default parameters (instead of `param1 || 'value'`)
- Avoid UPPER_CASE (i.e. use `const` instead)
- Never use `for` (instead just use `.forEach` and variants, unless you're dealing with iterators.... hmm)
- Only use `=>` for short functions and not for methods (or some variation)
- Prefer shortened object literal syntax for methods `var toaster = { toast() {} };`
- Prefer template strings to string concatenation
- ...

Are these good rules to consider having? Are any of them in the works already? What other ES6 specific ideas are out there?

**Comment by nzakas** [comment]
Some of these make sense as built-in rules for ESLint, others I'm not sure. The ones I definitely would like are:

1. no `var`
1. `setPrototypeOf` over `__proto__`
1. `*` location for generators
1. Prefer `super`
1. Avoid `arguments`
1. Use default parameters
1. Prefer concise object literal syntax
1. Prefer template strings over string concatenation

I can't think of a good reason to avoid `toMethod()`, it's basically just `bind()` for `super`, and I see no issue with using it.

I'd still use `UPPER_CASE` for constants even in ES6. Makes it much easier to see which identifiers are writable in code.

**Comment by xjamundx** [comment]
Great, I'll take a stab at them over the next couple of weeks (and file them as individual PRs per rule)

**Comment by nzakas** [comment]
Not possible at the moment. We do probably need to expose ecmaFeatures to rules so they can turn themselves off when not applicable.

**Comment by xjamundx** [comment]
Yeah or like let the `ecmaFeatures` get defined dynamically by which rules are enabled that need certain features or something. I'll start building some of these out and we'll see what trouble we run into :)

**Comment by nzakas** [comment]
Rules can't define such information, nor would I want them to. We will work on showing the info to rules.

**Comment by xjamundx** [comment]
Yeah what I wanted for now was just the the latest version of https://github.com/eslint/eslint-tester/

**Comment by OliverJAsh** [comment]
Can we add ES6 modules aka `import` to the list?

**Comment by lo1tuma** [comment]
@OliverJAsh this issue is about ES6 related rules, not about ES6 syntax.

We use espree for parsing, if espree supports ES6 modules we will support it too (see https://github.com/eslint/espree/issues/10).

**Comment by xjamundx** [comment]
But @OliverJAsh, @lo1tuma there's already a PR for it https://github.com/eslint/espree/pull/43, so I imagine it will land in the next couple of days :)

**Comment by xjamundx** [comment]
Hey so hanging out in the babel chatroom I found a few more things we should probably consider gently discouraging around fat arrows:

- `() => {}` // will not return `{}`
- `prop => {a: prop}` // is even weirder

suggestion may be to wrap in `()` such as 

- `() => ({})`
- `prop => ({a: prop})`

or possibly add an explicit `return` statement (which i think may confuse people even more)

**Comment by nzakas** [comment]
Hmm, still probably a bit too early to tell about these. I've used `()=>{}` for empty functions in a bunch of places. We don't really know if people will be confused as to what this does yet.

**Comment by xjamundx** [comment]
Yeah let's take a wait and see approach. I imagine patterns of mistakes will become obvious pretty quickly :)

**Comment by xjamundx** [comment]
Any interest in a `require-module-type` : `"amd"`, `"es6"`, `"cjs"` type of plugin?

**Comment by nzakas** [comment]
I'm ambivalent. Seems a bit of a stretch to think that people would accidentally usethe wrong module format.

**Comment by ericelliott** [comment]
> I've used ()=>{} for empty functions in a bunch of places. We don't really know if people will be confused as to what this does yet.

I've done this, too, but I can see how this form is pretty ambiguous from a reader's perspective. :|

**Comment by xjamundx** [comment]
Hey I think it's time to revisit these again. I'll take a stab at "Prefer concise object literal syntax" soon.

**Comment by nzakas** [comment]
:+1: 

I'm also thinking of a "prefer const" rule that flags uses of var and let for variables that never change.

**Comment by Josh-a-e** [comment]
+1

**Comment by AsaAyers** [comment]
> I'm also thinking of a "prefer const" rule that flags uses of var and let for variables that never change.

Having a rule that will error when you assign to a `const` would be nice too. I'm not sure if it's technically a syntax error, but Babel throws an error at compile time if you do this.

**Comment by nzakas** [comment]
Let's close this and just start filing individual issues now.
