### ISSUE TITLE
Eslint 8.21.0 introduced a few new dependencies, can we review these?

### ISSUE THREAD

**Issue by romainmenke** [eslint/eslint#16188]
### ESLint version

8.21.0

### What problem do you want to solve?

Each dependencies is a potential attack vector and slows down npm install, ....

see : 

- https://npm.anvaka.com/#/view/2d/eslint/8.20.0
- https://npm.anvaka.com/#/view/2d/eslint/8.21.0

Were these dependencies sufficiently reviewed?

### What do you think is the correct solution?

Confirm that these dependencies are the right choice for the project or remove them.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Is there a particular package you are concerned about?

**Comment by romainmenke** [comment]
As long as each package is really needed and the maintainer is trusted by you there is no concern. I couldn't find any discussion in a relevant pull request about the added dependencies : https://github.com/eslint/eslint/pull/16149

Just caught my attention to see the number of installed packages go up by a non-trivial amount.

**Comment by nzakas** [comment]
Yeah, that's because we implemented the new config system, which required a bunch of new dependencies. If you have any specific concerns, please feel free to open another issue.
