### ISSUE TITLE
Bug: "RangeError: Maximum call stack size exceeded" in indent rule using colon in tsx

### ISSUE THREAD

**Issue by littleboarx** [eslint/eslint#16192]
### Environment

Node version: v16.16.0
npm version: v8.11.0
Local ESLint version: v8.21.0
Global ESLint version: Not found
Operating System: win32 10.0.18362

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>
        {
            files: ['*.tsx'],
            extends: [
                'eslint:recommended',
                'plugin:@typescript-eslint/recommended',
                'plugin:vue/vue3-recommended',
                'plugin:import/typescript', // this line does the trick
            ],

            parserOptions: {
                parser: '@typescript-eslint/parser',
                ecmaFeatures: {
                    globalReturn: false,
                    impliedStrict: true, 
                    jsx: true, 
                },
            },

            plugins: [
                'vue',
                '@typescript-eslint',
                'import',
            ],

            rules: {
                'indent': [
                    'warn',
                    4,
                ],
            },
        },

```
<!-- Paste your configuration here -->
```
</details>

```js

const Apps = defineComponent({
    name: 'App',
    setup() {
        const a = ref<number>(1)
        return () => <BigDataSelectTsx 
            modelValue={a.value} 
            options={[{ label: '111', value: 1 }]} 
            remote
            onUpdate:modelValue={number => { a.value = number }}
        />
    },
})
```

### What did you expect to happen?

no error

### What actually happened?

RangeError: Maximum call stack size exceeded
Occurred while linting 
Rule: "indent"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
eslint does not officially support ts. you should be using `@typescript-eslint/indent` instead.

**Comment by nzakas** [comment]
It looks like they are using `typescript-eslint` already. The question here is if we can reproduce with the given configuration.

**Comment by nzakas** [comment]
Oops, sorry, I misread your comment. Yes, please use the TypeScript-specific version of indent:
https://typescript-eslint.io/rules/indent
