### ISSUE TITLE
New Rule: no await in Promise.all/race/reject/resolve statements

### ISSUE THREAD

**Issue by hugo-vrijswijk** [eslint/eslint#16205]
### Rule details

Warn when `await` statement is used inside a `Promise.all` (or other Promise method) call. Using `await` inside a `Promise.all` statement is _extremely likely_ to be a user error and can cost a lot of performance because the `awaited` promise will first complete before the rest of the statement is run. 

### Related ECMAScript feature

Promise

### What type of rule is this?

Warns about a potential problem

### Example code

```js
import { setTimeout as sleep } from 'timers/promises';

console.time('setTimeout');
// No warning
await Promise.all([sleep(100), sleep(200)]);
console.timeEnd('setTimeout');

console.time('setTimeout with await');
// Warning
await Promise.all([await sleep(100), sleep(200)]);
console.timeEnd('setTimeout with await');
```

### Why should this rule be in the core instead of a plugin?

Reach. Having this rule inside ESLint core would prevent numerous bugs with a (I think) simple rule, rather than users having to search and install their own plugin _after_ running into this.

### Participation

- [X] I am willing to submit a pull request to implement this rule.

### Additional comments

I ran into this myself on my works code base and was surprised ESLint would not warn for this.

**Comment by nzakas** [comment]
Thanks for the suggestion. This is a bit too generic a proposal to be considered in the core (await can cause problems in many places that have callbacks), but you can always create a custom rule that does exactly what you want.

**Comment by hugo-vrijswijk** [comment]
Yes, I've taken to publishing my own plugin, but I doubt that will reach many bugs by itself 😅: https://www.npmjs.com/package/eslint-plugin-no-await-in-promise

> await can cause problems in many places that have callbacks

Could you explain what you mean by this? My proposed rule would only trigger for code that already uses `await`.
