### ISSUE TITLE
docs: Hardcode eslintVersion.js on release

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16212]
## Problem

Right now, `docs/_data/eslintVersion.js` reads from the root `package.json` to retrieve the version of ESLint. This makes it difficult to copy the docs files into another repo (for translation purposes).

## Solution

Instead of reading the version dynamically, we should instead just hardcode this value whenever we do a release. So in `Makefile.js`, we can add a step where we write the equivalent of `module.exports = "8.22.0";` into `docs/_data/eslintVersion.js`. I think we can make that change around [this line](https://github.com/eslint/eslint/blob/main/Makefile.js#L285). We are already adding the contents of `docs` into the commit, so as long as we update `eslintVersion.js` before that point, everything should work.

**Comment by ljharb** [comment]
what about `require('eslint/package.json').version`, and then making eslint be a dep of the docs?

**Comment by nzakas** [comment]
I’m trying to eliminate the relationship between the docs site and the package.json. The docs site should know what version it represents without any external references.

**Comment by MahendraBishnoi29** [comment]
can you assign it to me :)

**Comment by nzakas** [comment]
@MahendraBishnoi29 absolutely. Thanks for your help!

**Comment by MahendraBishnoi29** [comment]
@nzakas can you guide me how do i do this i'm new to eslint 🙏🏻

**Comment by nzakas** [comment]
@MahendraBishnoi29 there are instructions in the original issue description under "Solution".

**Comment by MahendraBishnoi29** [comment]
i didn't understand what to change there🤔

**Comment by nzakas** [comment]
Ask us some questions. :smile: What can we answer that would help?

**Comment by MahendraBishnoi29** [comment]
as you said we have to make change around [here](https://github.com/eslint/eslint/blob/main/Makefile.js#L285) right? but what changes i have to make here 😬

**Comment by nzakas** [comment]
Sorry, I don’t know how to explain it better than in my original comment above:

> So in Makefile.js, we can add a step where we write the equivalent of module.exports = "8.22.0"; into docs/_data/eslintVersion.js.

**Comment by jugalthakkar** [comment]
I am keen it pick this up as well, please let me know if it is ok with you @MahendraBishnoi29 @nzakas

**Comment by jugalthakkar** [comment]
Do we want to keep the ability to read the version from `env`? Else, we can altogether remove the `eslintVersion.js` file and always have it generated as you have mentioned.

**Comment by nzakas** [comment]
No, we don’t want to read from env. In order to make it easier to just copy the files over directly, we need the version to be static.

**Comment by sararita28** [comment]
I read the file changes and it seems like [jugalthakkar](https://github.com/jugalthakkar) met the latest requirements of [nzakas](https://github.com/nzakas) in the PR. Any other good first issues to work on [nzakas](https://github.com/nzakas)? I would love to contribute.
