### ISSUE TITLE
Rule Change: `object-curly-spacing` to support space in empty braces

### ISSUE THREAD

**Issue by Samuel-Beslogic** [eslint/eslint#16231]
### What rule do you want to change?

object-curly-spacing

### What change to do you want to make?

Generate more warnings

### How do you think the change should be implemented?

A new option

### Example code

```js
// Should pass
export class SomeEmptyClass { }

// Should fail
export class SomeEmptyClass {}
```

### What does the rule currently do for this code?

It is explicitly ignored.
> "always" requires spacing inside of braces (except {})

### What will the rule do after it's changed?

When the option is turned on, Warn for empty braces with no space inside. And autofix.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

This is to allow us to align with VSCode's `javascript.format.insertSpaceAfterOpeningAndBeforeClosingEmptyBraces` which we prefer (but autofixable and enforced by CLI and other editors).
This is likely a revival of #12141, https://github.com/eslint/eslint/issues/7927#issuecomment-327469941 and https://github.com/eslint/eslint/issues/7380#issuecomment-254072380

**Comment by mdjermanovic** [comment]
Hi @Samuel-Beslogic, thanks for the issue! 

Per our rules policies, [stylistic rules are frozen](https://github.com/eslint/eslint#stylistic-rule-updates) so we are not adding new options to the `object-curly-spacing` rule. You can always copy the existing rule into a custom rule and make it behave the way you want.
