### ISSUE TITLE
Bug: (indent rules with parser)

### ISSUE THREAD

**Issue by MrBrN197** [eslint/eslint#16248]
### Environment

Node version: 16.15.0
npm version: 8.10.0
Local ESLint version: 7.32.0
Global ESLint version: N/a
Operating System:  Windows (using WSL)

### What parser are you using?

Other

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "parser": "babel-eslint",
  "rules": {
    "indent": [   // if I remove this rule it works
      "error",
      "tab"
    ]
  }
}
```
</details>

```js
const arr = [];
arr?.forEach(() => `${1}`);
```

### What did you expect to happen?

Not to crash.

### What actually happened?

running `npx eslint file.js` throw this error:

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read properties of null (reading 'range')
Occurred while linting /home/brian//test/demo/test.js:1
    at OffsetStorage.setDesiredOffset (/home/brian//test/demo/node_modules/eslint/lib/rules/indent.js:341:45)
    at /home/brian//test/demo/node_modules/eslint/lib/rules/indent.js:1395:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/home/brian//test/demo/node_modules/eslint/lib/rules/indent.js:1387:34)
    at /home/brian//test/demo/node_modules/eslint/lib/rules/indent.js:1632:55
    at Array.forEach (<anonymous>)
    at Program:exit (/home/brian//test/demo/node_modules/eslint/lib/rules/indent.js:1632:26)
    at /home/brian//test/demo/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/brian//test/demo/node_modules/eslint/lib/linter/safe-emitter.js:45:38)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

this only happens when I have the indent rule + the parser is set the "babel-eslint" + the file I'm testing uses optional and template strings in the way I have it on the example. this specific combination causes the error.

**Comment by mdjermanovic** [comment]
Hi @MrBrN197, thanks for the issue! 

> this only happens when I have the indent rule + the parser is set the "babel-eslint" + the file I'm testing uses optional and template strings in the way I have it on the example. this specific combination causes the error.

This is a known problem in the now-deprecated `babel-eslint` parser. You should use [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) instead.
