### ISSUE TITLE
Bug: Unable to resolve path to module when git+ssh is used

### ISSUE THREAD

**Issue by thanhnguyen** [eslint/eslint#16242]
### Environment

Node version: v12.22.12
npm version: 6.14.16
Local ESLint version: v8.22.0
Global ESLint version: v8.22.0
Operating System: Ubuntu 20 LTS amd64

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>
"depname":"git+ssh://someurl/someproject.git"
</details>

### What did you expect to happen?

eslint should recognize that the dependency is resolvable

### What actually happened?

eslint throws "Unable to resolve path to module"

Verified that yarn was able to download the dependency module and complete the build
Verified that the git+https alternative works without the lint error

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @thanhnguyen, thanks for the issue!
 
> eslint throws "Unable to resolve path to module"

Is this a reported lint error or an error in the execution? Can you please provide the exact output you're getting when you run ESLint on the command line?

**Comment by thanhnguyen** [comment]
sorry this was caused by another issue. thanks
