### ISSUE TITLE
Bug: Error fixing let to const.

### ISSUE THREAD

**Issue by YeWills** [eslint/eslint#16266]
### Environment

Node version:  v16.13.2
npm version: 8.1.2
yarn version: 1.22.19
Local ESLint version: v7.32.0
Global ESLint version: v7.15.0  (Not used)
Operating System:  macOS

### What parser are you using?

Other

### What did you do?

This is my project structure:

package.json:
```json
{
  "name": "test",
  "version": "0.2.75",
  "description": "11",
  "dependencies": {
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^7.16.0",
    "eslint-config-airbnb-base": "13.2.0",
    "eslint-plugin-import": "^2.17.2"
  }
}

```
.eslintrc.js

```js
module.exports = {
  "parser": "babel-eslint",
  "extends": [
    "airbnb-base"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  }
};

```

aa.js
```js
let { itemId, list } = {},
obj = [],
total = 0;
total = 9;
console.log(itemId, list, obj, total);
```
run yarn install project:
```s
yarn
```
Please use yarn to install,  because yarn will force a successful installation when there is a dependency package version conflict.

When I run:
```s
npx eslint --fix aa.js
```
Wrong code modification will occur.

### What did you expect to happen?

When I run:
```s
npx eslint --fix aa.js
```
I want aa.js code becomes
```js
const { itemId, list } = {};
const obj = [];
let total = 0;

total = 9;

console.log(itemId, list, obj, total);
```

### What actually happened?

When I run:
```s
npx eslint --fix aa.js
```
 aa.js code becomes
```js
const { itemId, list } = {};
const obj = [];
const total = 0;

total = 9;

console.log(itemId, list, obj, total);
```
`const total = 0` above Is wrong,  should be let

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

If you change the eslint of the above project to version 5.16.0, there will be no problem and everything will be repaired normally.
Therefore, I think it is the higher version of eslint that causes this problem。

This problem also occurs when I switch to a higher version of eslint and use @ Babel / eslint parser:
The project is as follows:
package.json:
```json
{
  "name": "demo1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/preset-env": "^7.18.10",
    "eslint": "^8.23.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.26.0"
  },
  "dependencies": {
    "@babel/core": "^7.18.13",
    "@babel/eslint-parser": "^7.18.9"
  }
}

```
.eslintrc.js

```js
module.exports = {
  parser: "@babel/eslint-parser",
  extends: "airbnb-base",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    babelOptions: {
      presets: ['@babel/preset-env'].concat([]),
    },
    requireConfigFile: false,
},
};

```

aa.js
```js
let { itemId, list } = {},
obj = [],
total = 0;
total = 9;
console.log(itemId, list, obj, total);
```
run npm install install project:
```s
npm install
```
When I run:
```s
npx eslint --fix aa.js
```
Wrong code modification will occur.

**Comment by YeWills** [comment]
What is more incredible is that if I reduce a variable `list,` the above problem will not exist and eslint will run normally.
将上面的aa.js 改成
```js
let { itemId } = {},
obj = [],
total = 0;
total = 9;
console.log(itemId, list, obj, total);
```
```s
npx eslint --fix aa.js 
```
Everything is normal, aa.js  will become normal:
```js
const { itemId } = {};
const obj = [];
let total = 0;
total = 9;
console.log(itemId, list, obj, total);
```

**Comment by mdjermanovic** [comment]
Hi @YeWills, thanks for the issue!

This is indeed a bug we should fix. I can reproduce it in the latest ESLint v8.23.0 with the default parser, too. Here's a [playground repro](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50ICdwcmVmZXItY29uc3QnOiBbJ2Vycm9yJywge1xuICAgICAgZGVzdHJ1Y3R1cmluZzogJ2FueScsXG4gICAgICBpZ25vcmVSZWFkQmVmb3JlQXNzaWduOiB0cnVlLFxuICAgIH1dXG4gICAgLS0gZnJvbSBhaXJibmItYmFzZSBjb25maWdcbiovXG5cbmxldCB7IGl0ZW1JZCwgbGlzdCB9ID0ge30sXG5vYmogPSBbXSxcbnRvdGFsID0gMDtcbnRvdGFsID0gOTtcbmNvbnNvbGUubG9nKGl0ZW1JZCwgbGlzdCwgb2JqLCB0b3RhbCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby1jb25zdC1hc3NpZ24iOlsiZXJyb3IiXX0sImVudiI6eyJlczYiOnRydWV9fX0=) (click the "Fix" button on the 9:1 error for 'obj').

**Comment by YeWills** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，你的邮件我已经收到。谢谢！

**Comment by Gautam-Arora24** [comment]
Hey! Willing to work on this issue.
