### ISSUE TITLE
Bug: [new config system] globs are ignoring dot files

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16265]
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

```js
// eslint.config.js

module.exports = [];
```

```js
// .foo.js
```

```
npx eslint *.js -f tap
```

### What did you expect to happen?

Per the [RFC](https://github.com/eslint/rfcs/blob/893b49194689fcf0d34743eac75773d098264656/designs/2019-config-simplification/README.md?plain=1#L534), this should include ` .foo.js`?

> 1. **Defaults** - by default, ESLint will ignore `node_modules` and `.git` directories only. This is different from the current behavior where ESLint ignores `node_modules` and all files/directories beginning with a dot (`.`).

In that case, I would expect this output:

```
TAP version 13
1..2
ok 1 - D:\tmp\tmp\.foo.js
ok 2 - D:\tmp\tmp\eslint.config.js
```

### What actually happened?

The `.foo.js` file was not linted:

```
TAP version 13
1..1
ok 1 - D:\tmp\tmp\eslint.config.js
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Confirmed, this is a bug. We should be picking up dot files by default now.

**Comment by nzakas** [comment]
Because this example has a glob without quotes, that means the shell is expanding it and is therefore not including dot files. I don't think there's anything we can do about that.

However, I also see that quoting the glob pattern does not pick up dot files. That is a bug per the RFC:

```
npx eslint "*.js" -f tap
```

This may end up being a case where we should mirror the shell expansion to avoid confusion?

**Comment by mdjermanovic** [comment]
> Because this example has a glob without quotes, that means the shell is expanding it and is therefore not including dot files.

Oh, I was running this in a windows shell and it passed `*.js` to eslint (I double-checked `process.argv`). I'll use quotes from now on to avoid ambiguity.

> This may end up being a case where we should mirror the shell expansion to avoid confusion?

That would mean that dotfiles are effectively ignored by default?

**Comment by mdjermanovic** [comment]
I prepared https://github.com/eslint/eslint/pull/16269 to include dotfiles in glob and directory searches (per the RFC), if we decide that should be the behavior.

**Comment by nzakas** [comment]
> > This may end up being a case where we should mirror the shell expansion to avoid confusion?
> That would mean that dotfiles are effectively ignored by default?

Yeah, that's what I'm wondering. We obviously have control over what gets passed to globby, but, as in your example, it was unclear if the pattern was being passed directly to globby or if it was a shell expansion. I'm just wondering if it would make sense to keep the current behavior because then we at least know the result will be the same regardless of shell expansion or not?

**Comment by mdjermanovic** [comment]
By the current behavior, do you mean current FlatESLint behavior or current eslintrc behavior?

**Comment by nzakas** [comment]
At the moment they are both the same: flat config and eslintrc both ignore dot files right now.

**Comment by nzakas** [comment]
**TSC Summary:** Flat config was originally designed to include dot files by default when using glob patterns on the command line. The current behavior is that it doesn’t include dot files.

**TSC Question:** Should we keep the current behavior? Shell expansion for terminals typically does not include dot files, so we are only able to change for quotes globs passed to ESLint, so would it be too confusing to have a different behavior between the two?

**Comment by mdjermanovic** [comment]
In both eslintrc and the current implementation of flat config, dotfiles are effectively ignored in most cases, but the logic is not the same and there are many differences regarding the cases in which dotfiles are not ignored.

eslintrc:

* If the given pattern is a file path, and `--no-ignore` flag is set. For example, `eslint foo/.bar.js --no-ignore` will lint `foo/.bar.js`.
* If the given pattern is a directory path, and it contains a directory name that starts with a dot. For example, `eslint .foo` will lint `.foo/.bar.js`, and `eslint foo/.bar/baz` will lint `foo/.bar/baz/.qux.js`.
* If the given pattern is a glob, and it contains a directory name that starts with a dot. For example, `eslint .foo/*.js` will lint `.foo/.bar.js`, and `eslint foo/.bar/baz/*.js` will lint `foo/.bar/baz/.qux.js`.
* If the given pattern is a glob, and the last segment starts with a dot. For example, `eslint foo/.*.js` will lint `foo/.bar.js`.
* If the file is unignored. For example, with `!foo/*` in `.eslintignore` or `ignorePatterns`, `eslint foo` will lint `foo/.bar.js`, and `eslint foo/*.js` will lint `foo/.bar.js`

flat config:

* If the given pattern is a file path. For example, `eslint foo/.bar.js` will lint `foo/.bar.js`.
* If the given pattern is a glob, and the last segment starts with a dot. For example, `eslint foo/.*.js` will lint `foo/.bar.js`.
* If the given pattern is a directory, and configuration contains an entry that doesn't end with `*`, its last segment starts with a dot, and it matches the file. For example, with `{ files: ["foo/.*.js"] }` in `eslint.config.js`, `eslint foo` will lint `foo/.bar.js`. This might be unintentional because it doesn't apply to globs, for example `eslint foo/*` will not lint `foo/.bar.js`.

I think the RFC intended to avoid these complex implicit rules by including dotfiles by default and allowing users to configure `ignores` to get the exact behavior they want.

**Comment by mdjermanovic** [comment]
Some notable differences in use cases, as a consequence of the different logic:

* CLI: with eslintrc, unignoring a dotfile in `.eslintignore`/`ignorePatterns` is the way to automatically include it in glob searches. For example, `eslint "foo/*.js"` will include `foo/.bar.js` if there is an entry like `!foo/.bar.js` in `.eslintignore`/`ignorePatterns`. With flat config, including `foo/.bar.js` would require an additional CLI argument, for example `eslint "foo/*.js" foo/.bar.js`.
* IDEs: for a dotfile, by default (i.e. when the file is not unignored), `ESLint#isFileIgnored()` returns `true`, but `FlatESLint#isFileIgnored()` returns `false` which means that the file should be linted.
* lint-staged: with eslintrc, a dotfile, by default (i.e. when the file is not unignored), will not be linted. With flat config, it will be linted.

**Comment by nzakas** [comment]
> I think the RFC intended to avoid these complex implicit rules by including dotfiles by default and allowing users to configure ignores to get the exact behavior they want.

I believe this is true, but I’m still wary of glob patterns behaving different when they are shell expanded vs when they are not. It seems that the best path forward is to try and mimic eslintrc behavior as closely as possible?

**Comment by btmills** [comment]
In the 2022-09-08 TSC meeting, we discussed this and came to the conclusion that users likely expect glob patterns to exclude dot files by default because that's how eslintrc and shell expansions behave. We're intentionally deviating from the RFC so that glob patterns ignore dot files.

---

Speaking for myself now, if differences arise between eslintrc, flat config, and shells, I think it makes sense to match eslintrc unless there's a case to be made that that shell expansions set a better precedent for that particular scenario going forward.

**Comment by nzakas** [comment]
Now that we have rewritten the search functionality, we are actually finding dot files by default. As it is now, it will end up being more difficult to mimic the eslintrc functionality than it will be to ensure the originally intended functionality works. Given that, I think the best path forward now is to include dot files in the glob patterns by default.

**Comment by nzakas** [comment]
Working on this.

**Comment by mvorisek** [comment]
I am on v8.29.0 and js files in `.eslint` dir are still completely ignored.

I found `.eslintignore` file with `!/.eslint` content fixes it, but is there a solution without the .eslintignore` file (config to put into `.eslintrc.js`)?

**Comment by mdjermanovic** [comment]
@mvorisek this issue and the fix are only about the new config system ([`eslint.config.js`](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new)).

In the current config system, dotfiles and dotfolders  are still ignored by default, as described in [Ignoring Code](https://eslint.org/docs/latest/user-guide/configuring/ignoring-code). That will remain unchanged in the current config system, so the solution is to unignore them either in `.eslintignore` file or with `ignorePatterns` config option, just like you did.
