### ISSUE TITLE
ESLint randomly started enforcing new rule which is incorrect and breaking my builds

### ISSUE THREAD

**Issue by tr1s** [eslint/eslint#16278]
### Environment

Node version: `v16.15.1` 
npm version: `8.19.0`
Local ESLint version: `8.23.0`
Global ESLint version: N/A
Operating System: macOS Big Sur / M1 Mac

### What parser are you using?

Default (Espree)

### What did you do?

Configuration

```json
/* .eslintrc.json */

{
  "extends": "next/core-web-vitals"
}
```

My code is viewable [here](https://github.com/tr1s/nightizm).

| File | Vercel Build Error |
|:-------------:|:-------------:|
|![ESLint_ERRORS](https://user-images.githubusercontent.com/19172250/188555165-af40e4a8-35fd-4515-808e-c62d60f3d978.png)|![ESLint-ERRORS-2](https://user-images.githubusercontent.com/19172250/188555424-55e9ceea-55d7-47b8-82c6-3f2be824385b.png)|

I went through my old vercel builds and found where it stopped working—I updated some packages and that was it. I just tried to revert back to all the old package versions where the builds were working fine and I still am getting the errors now.

I'm not sure why ESLint decided to enforce this rule randomly or why it's throwing an error even though it's a real property. I know I can ignore it with next.js configs but I'm instead trying to figure out what's happening here.

I also have an almost identical project with the same setup code and up-to-date packages in which I'm not having this issue. I can't understand why it's only happening on this repo.

If you have any ideas as to what's happening please let me know, thank you.

Posted over at [next.js repo](https://github.com/vercel/next.js/issues/40245) as well.

### What did you expect to happen?

My build should pass.

### What actually happened?

My build failed: `Error: Unknown property 'key' found  react/no-unknown-property`

This is a real property and was working before with no issues, errors, or warnings.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ljharb** [comment]
This is an issue with v7.31.2-6 of eslint-plugin-react. Update to v7.31.7 and the problem should go away.

**Comment by ljharb** [comment]
@tr1s to be clear; this should be closed since it's not an issue with eslint. See https://github.com/jsx-eslint/eslint-plugin-react/issues/3380

**Comment by tr1s** [comment]
@ljharb neither of my projects are using that package, it's probably a peer dependancy though yeah. They're both using: `"eslint": "^8.23.0"` and `"eslint-config-next": "^12.2.5"`

Does that mean I have to wait for next.js to fix it under the hood or?

**Comment by ljharb** [comment]
No, it's a transitive dependency of eslint-config-next. You can either `npm update eslint-plugin-react`, or `npm install eslint-config-next`, or any number of things to update the transitive dependency.

In all of these cases, it's not an issue with eslint or eslint-config-next, so both of these issues should be closed.

**Comment by tr1s** [comment]
@ljharb okay thank you.
