### ISSUE TITLE
Change Request: (fill in)

### ISSUE THREAD

**Issue by thany** [eslint/eslint#16283]
### ESLint version

8.19.1

### What problem do you want to solve?

I was making a HTML formatted overview of linter errors in our codebase, and to my surprise it also includes files without errors:
![image](https://user-images.githubusercontent.com/152227/189113905-18188e4b-f7e3-4cbc-8b18-6fcca4c2f83a.png)

I cannot find a way to skip those from being outputted, other than fiddling them away manually from the output.

### What do you think is the correct solution?

I was hoping a (CLI-)switch could be added to skip files from being outputted to/by the formatter that have no errors.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
ESLint always returns a list of all files it lints whether they have lint errors or not. If you want different output, you'll need to create a custom formatter to do that.
