### ISSUE TITLE
Change Request: Documentation for new configuration files seems to incorrectly specify how severities affect exit code

### ISSUE THREAD

**Issue by haykam821** [eslint/eslint#16290]
### ESLint version

N/A

### What problem do you want to solve?

In [Rule severities](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#rule-severities), the following information is given about the warn severity and how it effects the exit code:

> - `"warn"` (or `1`) - the reported problem should be treated as a warning. When using the ESLint CLI, warnings are reported but do not change the exit code. If only errors are reported, the exit code will be 0.

However, in [Configuring Rules](https://eslint.org/docs/latest/user-guide/configuring/rules), the information is contradicted:

- `"warn"` or `1` - turn the rule on as a warning (doesn’t affect exit code)
- `"error"` or `2` - turn the rule on as an error (exit code is 1 when triggered)

Of course, the latter behavior is what actually happens, so the former documentation should be corrected.

### What do you think is the correct solution?

Either the exit code or the severity could be changed to make the sentence correct and consistent. I think that the best way is to change the severity since the information is listed in the severity bullet point.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @haykam821, thanks for the issue!

PR is welcome. I think this was a typo in the last sentence, it should be "If only warnings are reported, the exit code will be 0."
