### ISSUE TITLE
New Rule: Require public instance fields syntax for class methods

### ISSUE THREAD

**Issue by jez9999** [eslint/eslint#16298]
### Rule details

Public instance fields syntax would be required for class methods instead of public instance methods

### Related ECMAScript feature

Public instance fields & arrow function expressions

### What type of rule is this?

Suggests an alternate way of doing something

### Example code

```js
class Foo {
    constructor() {
        this.bar = 123;
    }
    accessBar() {
        return this.bar;
    }
}
```

### Why should this rule be in the core instead of a plugin?

Almost every developer is confused by the behaviour of `this` when class callbacks are invoked from variable references other than a reference to the class instance.  This rule should advise the rewriting of any public instance method as a public instance field with an arrow function, always binding `this` lexically to the class instance in which it was defined:

```
class Foo {
    constructor() {
        this.bar = 123;
    }
    accessBar = () => {
        return this.bar;
    }
}

let baz = new Foo();
let baz2 = baz.accessBar;
baz2(); // 123
```

### Participation

- [X] I am willing to submit a pull request to implement this rule.

**Comment by mdjermanovic** [comment]
By the thumbs-up on my comment, it seems the team is in agreement not to accept this rule.

**Comment by jez9999** [comment]
Do you know of a plugin that does have this rule?
