### ISSUE TITLE
Bug: flat config with "eslint:all" on a .cjs file recommends function form of "use strict" instead of global form

### ISSUE THREAD

**Issue by jzinn** [eslint/eslint#16304]
### Environment

Node version: `v16.14.0`
npm version: `8.3.1`
Local ESLint version: `v8.23.1`
Global ESLint version: `zsh: command not found: eslint`
Operating System: `Fedora release 36 (Thirty Six)`

### What parser are you using?

Default (Espree)

## package.json

Notice `type` is `module`.

```js
{
  "devDependencies": {
    "eslint": "^8.23.1"
  },
  "license": "ISC",
  "name": "eslint-all-cjs",
  "scripts": {
    "lint": "eslint --fix ."
  },
  "type": "module",
  "version": "1.0.0"
}
```

## eslint.config.js

Using the new flat config file format.  The default `languageOptions` `sourceType` should be `commonjs` for `.cjs` files.

```js
export default ["eslint:all"];
```

## index.cjs

A `.cjs` file that ESLint should consider to be a `commonjs` file.

```js
module.exports = function identity (value) {

    return value;

};
```

### What did you expect to happen?

Expected: a message to use the global form of `"use strict"`.

Why: the docs for rule `strict` say:
> This rule has a string option:
> * "safe" (default) corresponds either of the following options:
>   * "global" if ESLint considers a file to be a CommonJS module
>   * "function" otherwise

The file ends with `.cjs`, so ESLint should recommend "global".

### What actually happened?

A message to use the function form:
```
/path/to/eslint-all-cjs/index.cjs
  1:18  error  Use the function form of 'use strict'  strict

✖ 1 problem (1 error, 0 warnings)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jzinn** [comment]
The docs for `strict` mention two ways to make "safe" equal "global".

The first is to set the environment to `node` or `commonjs`.  I'm not sure how to do this with the new flat configuration files.

The second is to set `globalReturn` like this:
```js
export default [
    "eslint:all",
    {
        "languageOptions": {
            "parserOptions": {
                "ecmaFeatures": {
                    "globalReturn": true
                }
            }
        }
    }
];
```

Setting `globalReturn` works, so I guess this issue is invalid.

It would be nice if this were a little easier to set up like by specifying the `node` environment if that's still possible.

Just configuring the rule might be best:

```js
export default [
    "eslint:all",
    {
        rules: {
            strict: ["error", "global"]
        }
    }
];
```

**Comment by mdjermanovic** [comment]
Hi @jzinn, thanks for the issue! 

> > This rule has a string option:
> > 
> > * "safe" (default) corresponds either of the following options:
> >   
> >   * "global" if ESLint considers a file to be a CommonJS module
> >   * "function" otherwise
> 
> The file ends with `.cjs`, so ESLint should recommend "global".

You're right, this is a bug.

The new config system works correctly in this case, as it automatically sets [`sourceType: "commonjs"`](https://github.com/eslint/eslint/blob/6ba269ed673f965d081287b769c12beeb5f98887/lib/config/default-config.js#L66) for `.cjs` files.

The problem is in the `strict` rule since its logic around CommonJS is based on `parserOptions.ecmaFeatures.globalReturn` field, which is in the new config format dropped in favor of `languageOptions.sourceType = "commonjs"`.

I prepared PR https://github.com/eslint/eslint/pull/16308 that should fix this problem.

**Comment by oalrbabaa** [comment]
> ### Environment
> 
> 
> 
> Node version: `v16.14.0`
> 
> npm version: `8.3.1`
> 
> Local ESLint version: `v8.23.1`
> 
> Global ESLint version: `zsh: command not found: eslint`
> 
> Operating System: `Fedora release 36 (Thirty Six)`
> 
> 
> 
> 
> 
> ### What parser are you using?
> 
> 
> 
> Default (Espree)
> 
> 
> 
> ### What did you do?
> 
> 
> 
> ## package.json
> 
> 
> 
> Notice `type` is `module`.
> 
> 
> 
> ```js
> 
> {
> 
>   "devDependencies": {
> 
>     "eslint": "^8.23.1"
> 
>   },
> 
>   "license": "ISC",
> 
>   "name": "eslint-all-cjs",
> 
>   "scripts": {
> 
>     "lint": "eslint --fix ."
> 
>   },
> 
>   "type": "module",
> 
>   "version": "1.0.0"
> 
> }
> 
> ```
> 
> 
> 
> ## eslint.config.js
> 
> 
> 
> Using the new flat config file format.  The default `languageOptions` `sourceType` should be `commonjs` for `.cjs` files.
> 
> 
> 
> ```js
> 
> export default ["eslint:all"];
> 
> ```
> 
> 
> 
> ## index.cjs
> 
> 
> 
> A `.cjs` file that ESLint should consider to be a `commonjs` file.
> 
> 
> 
> ```js
> 
> module.exports = function identity (value) {
> 
> 
> 
>     return value;
> 
> 
> 
> };
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> ### What did you expect to happen?
> 
> 
> 
> Expected: a message to use the global form of `"use strict"`.
> 
> 
> 
> Why: the docs for rule `strict` say:
> 
> > This rule has a string option:
> 
> > * "safe" (default) corresponds either of the following options:
> 
> >   * "global" if ESLint considers a file to be a CommonJS module
> 
> >   * "function" otherwise
> 
> 
> 
> The file ends with `.cjs`, so ESLint should recommend "global".
> 
> 
> 
> ### What actually happened?
> 
> 
> 
> A message to use the function form:
> 
> ```
> 
> /path/to/eslint-all-cjs/index.cjs
> 
>   1:18  error  Use the function form of 'use strict'  strict
> 
> 
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> ```
> 
> 
> 
> ### Participation
> 
> 
> 
> - [ ] I am willing to submit a pull request for this issue.
> 
> 
> 
> ### Additional comments
> 
> 
> 
> _No response_
