### ISSUE TITLE
New Rule: `no-empty-static-block`

### ISSUE THREAD

**Issue by sosukesuzuki** [eslint/eslint#16318]
### Rule details

Restricts empty static blocks

### Related ECMAScript feature

https://github.com/tc39/proposal-class-static-block

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
class Foo {
  static {
  }
}
```

### Why should this rule be in the core instead of a plugin?

Static blocks is a core feature of ECMAScript

### Participation

- [X] I am willing to submit a pull request to implement this rule.

### Additional comments

https://github.com/eslint/eslint/issues/15016

> ~~no-empty (or no-empty-function?)~~ neither, possibly a new rule.

**Comment by mdjermanovic** [comment]
I support this :+1:

**Comment by B2o5T** [comment]
@mdjermanovic what about current policies regarding stylistic rules of ESLint? why to give an exception to this rule?

**Comment by mdjermanovic** [comment]
@B2o5T we can accept rules related to new ECMAScript features that reached stage 4 in the preceding 12 months.

**Comment by snitin315** [comment]
I'm 👍🏻 for supporting this rule as well.

**Comment by nzakas** [comment]
Is there a reason this needs to be a new rule instead of updating no-empty to include static blocks? I just don’t want to get into a situation where we keep adding new separate rules for each kind of block statement that gets introduced.

**Comment by mdjermanovic** [comment]
> Is there a reason this needs to be a new rule instead of updating no-empty to include static blocks? I just don’t want to get into a situation where we keep adding new separate rules for each kind of block statement that gets introduced.

This was discussed in https://github.com/eslint/eslint/issues/15016 where the question was whether this belongs to `no-empty` or `no-empty-functions`, and the conclusion was that if we want to warn about empty static blocks then that should be a new rule.
