### ISSUE TITLE
new rule: space before (certain) keywords

### ISSUE THREAD

**Issue by dwelle** [eslint/eslint#1631]
There's a rule for `space-after-keywords`, but it seems to me it enforces just one half of the same styleguide, because it doesn't require space before keywords like `else`, `catch`, and `finally`.

```
if ( a ) {} else{}; // space after `else` is enforced
if ( a ) {}else {}; // while space before `else` is not enforced
```

Therefore, we probably should have a rule like `space-before-keywords`.

**Comment by nzakas** [comment]
You're right, though might be better to have a single rule do both.

**Comment by dwelle** [comment]
agreed

**Comment by michaelficarra** [comment]
Just `space-keywords`.

**Comment by gcochard** [comment]
Config for this should look something like:

```json
"space-keywords" : [2, "before/after/both"]
```

**Comment by lo1tuma** [comment]
Seems like this is only related to keywords after a block statement. I think a rule like `space-after-blocks` (similar to `space-before-blocks`) would make more sense and should be easier to implement.

**Comment by lo1tuma** [comment]
@gcochard The config should also accept `"always"` and `"never"` for each option.

**Comment by michaelficarra** [comment]
While the `try` body is represented by a `BlockStatement` in the SpiderMonkey AST, it is not a block (or a statement). I would avoid applying block rules to all instances of curly braces in the JS syntax.

**Comment by nzakas** [comment]
@lo1tuma I'm not sold. Having `space-keywords` with a configuration like:

```js
space-keywords: [2, {
   after: ["if"],
   before: ["catch"]
}
```

Seems like it would both make sense from a user perspective and be pretty easy to implement.

**Comment by lo1tuma** [comment]
@nzakas Your suggested configuration doesn’t work because you have to specify `"always"` or `"never"` for each keyword. So it would look like this:

```js
"space-keywords": [2, {
    "after": {
        "if": "always",
        "else": "never"
    },
    "before": {
        "if": "never",
        "else": "always"
    }
}
```

I don’t like such complicated configurations.

@michaelficarra: Thanks, good to know. Maybe `brace-style` would be the correct rule.

**Comment by nzakas** [comment]
I don't think always/never is necessary. The ones you list should have spaces and the ones you don't shouldn't.

**Comment by lo1tuma** [comment]
We have an edge case with the function keyword where the default should be "don’t care" instead of "always" or "never".

**Comment by nzakas** [comment]
Yeah, function is weird. I'm wondering if that should be handled by space-function-name instead, to encapsulate all spacing related to function.

**Comment by atomantic** [comment]
+1 on this

**Comment by nzakas** [comment]
Thanks, +1s don't actually change anything. This issue is marked as accepted, which means it will get done when someone claims it.

**Comment by ilyavolodin** [comment]
If we want to remove `space-after-keywords` and replace it with `space-keywords` this issue should be marked as required for 1.0.0, since we want to avoid removing existing rules after 1.0.0

**Comment by nzakas** [comment]
Or we just add `space-before-keywords`. We need to be careful about adding more things into the 1.0.0 milestone or we might never get there.

I'd say if someone wants to drive this starting now, fine, but if it sits, then it will be post 1.0.0

**Comment by mmrko** [comment]
+1

**Comment by IanVS** [comment]
@mmrko, would you like to make an attempt at a solution?  If the rule is important to you, the best way to get it implemented is to jump in and try it out.  :)

**Comment by mmrko** [comment]
Okay, let me take a stab at this :)

**Comment by mmrko** [comment]
Related PR: https://github.com/eslint/eslint/pull/3576
