### ISSUE TITLE
Change Request: Make table of contents sticky

### ISSUE THREAD

**Issue by chenxsan** [eslint/eslint#16312]
### ESLint version

N/A

### What problem do you want to solve?

I found it's sort of inconvenient to navigate on those long pages although there was a table of contents in the sidebar. You have to scroll back top to use the table of contents if you want to jump to another section on the page.

### What do you think is the correct solution?

It would be great if we can make the table of contents sticky for desktop users.

E.g.,

<img width="1388" alt="" src="https://user-images.githubusercontent.com/1091472/190398433-2e629349-c6c7-491a-af67-dc6e8da38a92.png">

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
If we want to make it sticky it will anyways come below the AD that is placed above the TOC and we might anyways need to scroll to the bottom of the page when the TOC is too long?

**Comment by kecrily** [comment]
I think he means put the toc in the sidebar (like in his picture)

**Comment by chenxsan** [comment]
> If we want to make it sticky it will anyways come below the AD that is placed above the TOC and we might anyways need to scroll to the bottom of the page when the TOC is too long?

It's likely to happen when TOC is much higher than the viewport, but we can handle those cases with a scrollbar, e.g.:

![](https://user-images.githubusercontent.com/1091472/190430779-59f51dc1-dac0-4fb1-a52d-39c9e6b85b14.png)

**Comment by harish-sethuraman** [comment]
That would mean we will have one scroll for the content and one scroll for TOC as well?

**Comment by chenxsan** [comment]
> That would mean we will have one scroll for the content and one scroll for TOC as well?

Right.

**Comment by snitin315** [comment]
I feel this change makes sense. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) seems to have a similar implementation.

**Comment by snitin315** [comment]
@chenxsan Are you still interested in working on this?

**Comment by chenxsan** [comment]
> @chenxsan Are you still interested in working on this?

Let me try.
