### ISSUE TITLE
eslint linting submodule node_modules no matter what ignore pattern I use

### ISSUE THREAD

**Issue by sacummings91** [eslint/eslint#16320]
### Environment

Node version: 16.13.2
npm version: 8.1.2
Local ESLint version: 8.23.1
Global ESLint version: 8.23.1
Operating System: macOS Catalina 10.15.7

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
  env: { node: true },
  rules: {
    "@typescript-eslint/no-unused-vars": [
      "error",
      { argsIgnorePattern: "_", varsIgnorePattern: "_" },
    ],
  },
};
```
</details>

```js
node_modules/
node_modules/*
./node_modules/**
**/node_modules/**
```
I have tried many flavors of these in  .eslintrc.js and .eslintignore and none of them seem to work.  Tried using --ignore-Patten flag too. No matter what I keep getting an error coming out of my node_modules `node_modules/@cubejs-client/core/index.d.ts`

### What did you expect to happen?

Linter not to check node modules

### What actually happened?

linter lints node modules

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sacummings91** [comment]
Ok I managed to narrow this down to a typescript upgrade causing the issue. Upgrading from `4.7.4` -> `4.8.3` causes this issue. Running `eslint 'src/**/*.{ts,tsx}'`

**Comment by mdjermanovic** [comment]
Hi @sacummings91, thanks for the issue!
 

> ### What actually happened?
> linter lints node modules

> Running `eslint 'src/**/*.{ts,tsx}'`

Can you provide the exact output you're getting when you run eslint?

**Comment by sacummings91** [comment]
Sure thing, it looks like this. It seems to have a problem with their types:
```
node_modules/@cubejs-client/core/index.d.ts:818:31 - error TS2344: Type 'First' does not satisfy the constraint 'DeeplyReadonly<Query>'.

818       ? SingleQueryRecordType<First> | QueryArrayRecordType<Rest & DeeplyReadonly<Query[]>>
                                  ~~~~~

  node_modules/@cubejs-client/core/index.d.ts:817:31
    817     T extends readonly [infer First, ...infer Rest]
                                      ~~~~~
    This type parameter might need an `extends DeeplyReadonly<Query>` constraint.


Found 1 error in node_modules/@cubejs-client/core/index.d.ts:818

**Comment by mdjermanovic** [comment]
Thanks for the info!

> node_modules/@cubejs-client/core/index.d.ts:818:31 - error TS2344: Type 'First' does not satisfy the constraint 'DeeplyReadonly<Query>'.
> 
> 818       ? SingleQueryRecordType<First> | QueryArrayRecordType<Rest & DeeplyReadonly<Query[]>>
>                                   ~~~~~
> 
>   node_modules/@cubejs-client/core/index.d.ts:817:31
>     817     T extends readonly [infer First, ...infer Rest]
>                                       ~~~~~
>     This type parameter might need an `extends DeeplyReadonly<Query>` constraint.
> 
> 
> Found 1 error in node_modules/@cubejs-client/core/index.d.ts:818

Is this the complete output? This looks like an error coming from running `tsc`, not `eslint`.

**Comment by mdjermanovic** [comment]
No response, so closing.
