### ISSUE TITLE
Change Request: Allow manually opting into flat config without an `eslint.config.js`

### ISSUE THREAD

**Issue by TomerAberbach** [eslint/eslint#16349]
### ESLint version

v8.24.0

### What problem do you want to solve?

Right now you have to create an `eslint.config.js` file to use flat config. It would be nice if flat configs could be passed on the command line using the `-c` or `--config` argument. The [docs](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#configuration-file-resolution) currently make it sound like it should work, but it doesn't.

### What do you think is the correct solution?

I can think of two options:
1. A CLI argument like `--use-flat-config` that would make ESLint treat the config as a flat config
2. Assume a config is a flat config if it's ESM because the legacy config files can't be ESM

I think I prefer option 1 because option 2 doesn't support CJS flat configs, which I think are allowed?

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by TomerAberbach** [comment]
I realized the CLI options are differentiated based on whether flat config is being used so maybe this could be configured by an environment variable instead

**Comment by nzakas** [comment]
Thanks for the feedback. The docs are confusing -- they were written with the end state of flat config in mind.

I'm not opposed to adding an environment variable (it was discussed before). Let's see what the rest of the team thinks.

**Comment by mdjermanovic** [comment]
I'm not opposed to adding an environment variable either.

Do we want it to also include an option to opt-out of flat config even if `eslint.config.js` is present?

* `ESLINT_USE_FLAT_CONFIG=true` - forces flat config mode regardless of the presence of `eslint.config.js` (`--config` would be loaded as a flat config file; it would error if there is no `eslint.config.js` and `--config` was not specified).
* `ESLINT_USE_FLAT_CONFIG=false` - forces eslintrc mode regardless of the presence of `eslint.config.js`.
* Not defined or any other value - works the same as now, presence of `eslint.config.js` determines the mode.

**Comment by nzakas** [comment]
> Do we want it to also include an option to opt-out of flat config even if eslint.config.js is present?

That seems like a good idea. It would certainly make compatibility testing a lot easier.

I like the proposal so marking as accepted. 

@TomerAberbach would you like to submit a PR for this?

**Comment by TomerAberbach** [comment]
> > Do we want it to also include an option to opt-out of flat config even if eslint.config.js is present?
> 
> That seems like a good idea. It would certainly make compatibility testing a lot easier.
> 
> I like the proposal so marking as accepted.
> 
> @TomerAberbach would you like to submit a PR for this?

Yup! See #16356 😃
