### ISSUE TITLE
Change Request: Define a `browser` entry point

### ISSUE THREAD

**Issue by MariaSolOs** [eslint/eslint#16345]
### ESLint version

8.24.0

### What problem do you want to solve?

In order to support [VS Code ESLint](https://github.com/microsoft/vscode-eslint) in the [browser](https://code.visualstudio.com/api/extension-guides/web-extensions) it would be great for ESLint to provide a [`browser` entry point](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser) in `package.json`.

### What do you think is the correct solution?

Enable support for this dependency to run in a `browser` runtime.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
I'm sorry, we don't officially support a version of ESLint to run in the browser. The API was not designed with the browser in mind and going back to do that work would be a major undertaking. You can Webpack/Rollup the `Linter` class and that will work in the browser.

**Comment by MariaSolOs** [comment]
> I'm sorry, we don't officially support a version of ESLint to run in the browser. The API was not designed with the browser in mind and going back to do that work would be a major undertaking. You can Webpack/Rollup the `Linter` class and that will work in the browser.

@nzakas I understand. Thank you for indicating the workaround!
