### ISSUE TITLE
Bug: [new config system] `baseConfig` option is unused in `FlatESLint`

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16341]
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: v8.23.1 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044 

### What parser are you using?

Default (Espree)

### What did you do?

```js
const { FlatESLint } = require("eslint/use-at-your-own-risk");
const path = require("path");

const eslint = new FlatESLint({
    overrideConfigFile: true, // just to skip loading eslint.config.js
    baseConfig: {
        rules: {
            "id-denylist": ["error", "foo"]
        }
    }
});

(async () => {
    const result = (await eslint.lintText("let foo;", { filePath: path.join(process.cwd(), "a.js") }))[0];

    console.log(result.messages);
})();
```

### What did you expect to happen?

To log a lint message for `id-denylist`.

### What actually happened?

Logs `[]`

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

`FlatESLint` accepts `baseConfig` option, but does nothing with it.

**Comment by nzakas** [comment]
I'm wondering if we actually need `baseConfig` for anything? It's unclear to me what the intended use case is.

**Comment by mdjermanovic** [comment]
The use case is to provide a way for integrations to set default config: https://github.com/eslint/eslint/issues/2143 (issue wasn't marked as accepted, but PR https://github.com/eslint/eslint/pull/2197 was merged). In the config array, `baseConfig` is inserted before configs from config files, so user configs can override it, as opposed to `overrideConfig` which is inserted at the end and therefore overrides user configs.

**Comment by nzakas** [comment]
Ah got it.

**Comment by mdjermanovic** [comment]
I'll work on this.
