### ISSUE TITLE
Change Request: Add Visual Studio support to editor integrations

### ISSUE THREAD

**Issue by MariaSolOs** [eslint/eslint#16372]
### ESLint version

8.24.0

### What problem do you want to solve?

There's no mention of Visual Studio in the editor integrations page, despite the latest version of the IDE having a [new linting experience](https://learn.microsoft.com/en-us/visualstudio/javascript/linting-javascript?view=vs-2022).

### What do you think is the correct solution?

Add Visual Studio to this list, possibly linking to the respective documentation page.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We don’t actively maintain that page and just leave it up so anyone can edit to it. Please feel free to submit a PR with the changes you’d like.

**Comment by MariaSolOs** [comment]
#16381 Ta-da!
