### ISSUE TITLE
indentation on .catch

### ISSUE THREAD

**Issue by 1muen** [eslint/eslint#16385]
### Environment

[eslint playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgaW5kZW50OiBcImVycm9yXCIqL1xuaWYgKHRydWUpIHtcbiAgICBzdG9yZShcIlwiLFxuICAgICAgICBcIlwiLFxuICAgICAgICBcImFcIikudGhlbigoKSA9PiB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcInRoZW5cIilcbiAgICAgICAgfSkuY2F0Y2goKGUpID0+IHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKChlKS5tZXNzYWdlKTtcbiAgICAgICAgfSk7XG59XG5cbi8vIGVzbGludCBkb2VzIHRoaXM6XG5pZiAodHJ1ZSkge1xuICAgIHN0b3JlKFwiXCIsXG4gICAgICAgIFwiXCIsXG4gICAgICAgIFwiYVwiKS50aGVuKCgpID0+IHtcbiAgICAgICAgY29uc29sZS5sb2coXCJ0aGVuXCIpXG4gICAgfSkuY2F0Y2goKGUpID0+IHtcbiAgICAgICAgY29uc29sZS5sb2coKGUpLm1lc3NhZ2UpO1xuICAgIH0pO1xufVxuXG4vLyBpZiB0aGVuIGlzIG1pc3NpbmcgZXNsaW50IG1ha2VzIGl0IGxvb2sgbGlrZSB0aGlzLCB0aGUgY2F0Y2ggZnVuY3Rpb24gaXMgbm90IGVhc3kgb3IgY2xlYXIgdG8gc3BvdCwgc2luY2UgdGhlIGNvbnNvbGUubG9nIGlzIG5vdCBpbmRlbmRlZDpcbmlmICh0cnVlKSB7XG4gICAgc3RvcmUoXCJcIixcbiAgICAgICAgdGFlc3Rhc2V0LFxuICAgICAgICBhdGVzdGV0YXNzZXRhZXN0KS5jYXRjaCgoZSkgPT4ge1xuICAgICAgICBjb25zb2xlLmxvZygoZSkubWVzc2FnZSk7XG4gICAgfSk7XG59XG5cblxuLy8gVGhpcyBpbmRlbnRhdGlvbiB3b3JrczpcbnN0b3JlKCkudGhlbigoKSA9PiB7XG4gICAgY29uc29sZS5sb2coXCJcIik7XG59KS5jYXRjaCgoZSkgPT4ge1xuICAgIGxvZ2dlci5lcnJvcigoZSkubWVzc2FnZSk7XG59KTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZ2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNsYXNzLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb21wYXJlLW5lZy16ZXJvIjpbImVycm9yIl0sIm5vLWNvbmQtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdGFudC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tY29udHJvbC1yZWdleCI6WyJlcnJvciJdLCJuby1kZWJ1Z2dlciI6WyJlcnJvciJdLCJuby1kZWxldGUtdmFyIjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLXNlbWkiOlsiZXJyb3IiXSwibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2VsZXNzLWJhY2tyZWZlcmVuY2UiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1jYXRjaCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWVzY2FwZSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sInJlcXVpcmUteWllbGQiOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)

### What parser are you using?

Default (Espree)

### What did you do?

```
/*eslint indent: "error"*/
if (true) {
    store("",
        "",
        "a").then(() => {
            console.log("then")
        }).catch((e) => {
            console.log((e).message);
        });
}

// This indentation works:
store().then(() => {
    console.log("");
}).catch((e) => {
    logger.error((e).message);
});
```

### What did you expect to happen?

No complaints on the intendation by default VS Code formatter
The ideal indentation should be like the comment below this one.

### What actually happened?

It complained and offered a fix for the intendation:

```
// if then is missing eslint makes it look like this, the catch function is not easy or clear to spot, since the console.log is not indended:
if (true) {
    store("",
        taestaset,
        atestetassetaest).catch((e) => {
        console.log((e).message);
    });
}
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snitin315** [comment]
I feel the ideal indentation should be as following:

```js
/*eslint indent: "error"*/
if (true) {
    store(
        "",
        "",
        "a"
    ).then(() => {
        console.log("then")
    }).catch((e) => {
        console.log((e).message);
    });
}
```

[ESLint Demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgaW5kZW50OiBcImVycm9yXCIqL1xuXG5pZiAodHJ1ZSkge1xuICAgIHN0b3JlKFxuICAgICAgICBcIlwiLFxuICAgICAgICBcIlwiLFxuICAgICAgICBcImFcIlxuICAgICkudGhlbigoKSA9PiB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcInRoZW5cIilcbiAgICAgICAgfSkuY2F0Y2goKGUpID0+IHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKChlKS5tZXNzYWdlKTtcbiAgICAgICAgfSk7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6eyJlczYiOnRydWV9fX0=)

**Comment by peanutenthusiast** [comment]
Hi, if this issue still needs to be addressed, I'm happy to work on it.

**Comment by snitin315** [comment]
@peanutenthusiast yes, feel free to work on this. Let us know if you need any help.

**Comment by nzakas** [comment]
Hi folks, I just wanted to let everyone know that the ESLint team has decided to deprecate all formatting rules, including indent, and recommend people use source code formatters like [Prettier](https://prettier.io) or [dprint](https://dprint.dev) instead. As a result, we are closing all outstanding issues related to these rules. For more information, please see https://github.com/eslint/eslint/issues/17522. Thanks.
