### ISSUE TITLE
Can autofix on save be opt in.

### ISSUE THREAD

**Issue by Rohitbels** [eslint/eslint#16380]
### ESLint version

8.24.0

### What problem do you want to solve?

- So by default if rule is fixable the rule is fixed if auto save fix is enabled.
- Can add a meta option to make the rule be fixed only if explicitly clicked on the quick fix pop up and not 
auto save.
- The current workflow can remain with no change just we add a extra optional meta option like

`autoSaveFix: true // defaultValue`

### What do you think is the correct solution?

Add Autosave in meta options.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @Rohitbels, thanks for the issue!

ESLint provides fixes but is not aware of the context in which the fixes are applied (on save, on the quick fix pop-up click, on the fix all pop-up click, etc.), and those contexts can be different in different environments so I don't think this should be an option in the ESLint configuration but rather in environment configurations.

For example, [VS Code ESLint extension](https://github.com/microsoft/vscode-eslint) has option `eslint.codeActionsOnSave.rules`:

> - `eslint.codeActionsOnSave.rules` (since 2.2.0) - controls the rules which are taken into consideration during code action on save execution.

**Comment by nzakas** [comment]
Yeah, this needs to be handled in the editor, not in ESLint.
