### ISSUE TITLE
Bug: `no-restricted-properties` misses destructuring object returned from function call

### ISSUE THREAD

**Issue by merrywhether** [eslint/eslint#16412]
### Environment

Node version: v16.14.2
npm version: v8.5.0
Local ESLint version: v8.24.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.6.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

After targeting a property in `no-restricted-properties`, immediately destructuring an object returned from a function call and accessing the restricted property:

```js
const { bad } = foo();
```

[ESLint demo example](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtcHJvcGVydGllczogW1wiZXJyb3JcIiwgeyBwcm9wZXJ0eTogXCJiYWRcIiB9XSAqL1xuLyogZXNsaW50LWRpc2FibGUgbm8tdW51c2VkLXZhcnMgKi9cblxuZnVuY3Rpb24gZm9vKCkge1xuICByZXR1cm4geyBnb29kOiB0cnVlLCBiYWQ6IGZhbHNlIH07XG59XG5cbi8vIHBhc3NcbmZ1bmN0aW9uIHRlc3QxUGFzcygpIHtcbiAgZm9vKCkuYmFkOyAgXG59XG5cbi8vIHBhc3NcbmZ1bmN0aW9uIHRlc3QyKCkge1xuICBjb25zdCBpbnRlciA9IGZvbygpO1xuICBpbnRlci5iYWQ7XG59XG5cbi8vIHBhc3NcbmZ1bmN0aW9uIHRlc3QzKCkge1xuICBjb25zdCBpbnRlciA9IGZvbygpO1xuICBjb25zdCB7IGJhZCB9ID0gaW50ZXI7XG59XG5cbi8vIGZhaWxcbmZ1bmN0aW9uIHRlc3Q0KCkge1xuICBjb25zdCB7IGJhZCB9ID0gZm9vKCk7XG59XG5cbi8vIGZhaWxcbmZ1bmN0aW9uIHRlc3Q1KCkge1xuICBjb25zdCB7IGJhZDogYWxpYXMgfSA9IGZvbygpO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbImVycm9yIl0sIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1lbXB0eS1wYXR0ZXJuIjpbImVycm9yIl0sIm5vLWV4LWFzc2lnbiI6WyJlcnJvciJdLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOlsiZXJyb3IiXSwibm8tZXh0cmEtc2VtaSI6WyJlcnJvciJdLCJuby1mYWxsdGhyb3VnaCI6WyJlcnJvciJdLCJuby1mdW5jLWFzc2lnbiI6WyJlcnJvciJdLCJuby1nbG9iYWwtYXNzaWduIjpbImVycm9yIl0sIm5vLWltcG9ydC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW5uZXItZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWludmFsaWQtcmVnZXhwIjpbImVycm9yIl0sIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjpbImVycm9yIl0sIm5vLWxvc3Mtb2YtcHJlY2lzaW9uIjpbImVycm9yIl0sIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6WyJlcnJvciJdLCJuby1uZXctc3ltYm9sIjpbImVycm9yIl0sIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjpbImVycm9yIl0sIm5vLW9iai1jYWxscyI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOlsiZXJyb3IiXSwibm8tcmVkZWNsYXJlIjpbImVycm9yIl0sIm5vLXJlZ2V4LXNwYWNlcyI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOlsiZXJyb3IiXSwibm8tdW5kZWYiOlsiZXJyb3IiXSwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOlsiZXJyb3IiXSwibm8tdW5yZWFjaGFibGUiOlsiZXJyb3IiXSwibm8tdW5zYWZlLWZpbmFsbHkiOlsiZXJyb3IiXSwibm8tdW5zYWZlLW5lZ2F0aW9uIjpbImVycm9yIl0sIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6WyJlcnJvciJdLCJuby11bnVzZWQtbGFiZWxzIjpbImVycm9yIl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtYmFja3JlZmVyZW5jZSI6WyJlcnJvciJdLCJuby11c2VsZXNzLWNhdGNoIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtZXNjYXBlIjpbImVycm9yIl0sIm5vLXdpdGgiOlsiZXJyb3IiXSwicmVxdWlyZS15aWVsZCI6WyJlcnJvciJdLCJ1c2UtaXNuYW4iOlsiZXJyb3IiXSwidmFsaWQtdHlwZW9mIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19)

### What did you expect to happen?

Accessing restricted property via immediately destructuring object returned from function call is marked as lint error.

### What actually happened?

Accessing restricted property via immediately destructuring object returned from function call is not recognized as error.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

AIUI the issue arises from [checking the RHS type in an assignment](https://github.com/eslint/eslint/blob/main/lib/rules/no-restricted-properties.js#L151). In the case where all instances of a property are restricted (no paired `object` argument) the RHS type check is unnecessary. Given the tight coupling with `object`, a "simple" solution might be treating this object as anonymous/unnamable and defaulting it to `undefined` (or empty string or some other sentinel that would always fail the ensuing object-name-related Map accesses):

```js
function checkDestructuringAssignment(node) {
    if (node.left.type === "ObjectPattern") {
        const objectName = node.right.type === "Identifier" ? node.right.name : undefined;
            node.left.properties.forEach(property => {
                checkPropertyAccess(node.left, objectName, astUtils.getStaticPropertyName(property));
            });
        }
    } 
}
```

(I fully admit there might be reasons why this doesn't work)

It would also be possible to extend the API with the ability to constrain the functions whose returned objects' properties can't be accessed (similar to `object`), but this does increase complexity as you have to handle `CallExpression`, `AsyncExpression`, and probably lots more. So maybe that's better left to future need-based implementation?

([useful reference PR](https://github.com/eslint/eslint/pull/7151/files) for me or whoever winds up tackling this)

**Comment by mdjermanovic** [comment]
Hi @merrywhether, thanks for the issue!

I think this is a bug. The following property accesses are basically the same, yet only the first is reported:

```js
/* eslint no-restricted-properties: ["error", { property: "bad" }] */

bad = foo().bad; // error

({ bad } = foo()); // no error

``` 

I couldn't find any mention of this in https://github.com/eslint/eslint/pull/7151, or a test case that would confirm intent to allow access to restricted properties when the destructuring source is not given as an identifier, so this is most likely an oversight in the implementation.

**Comment by mdjermanovic** [comment]
The rule should probably check all object patterns. In each of the following examples, `bad` property of an object is accessed:

```js
/* eslint no-restricted-properties: ["error", { property: "bad" }] */

const { bad } = foo(); // should be error?

const { bar: { bad } } = foo; // // should be error?

const { bar: { bad } = {} } = foo; // // should be error?

const [{ bad }] = foo; // // should be error?

({ bad } = foo()); // // should be error?

({ bar: { bad } } = foo); // // should be error?

({ bar: { bad } = {} } = foo); // // should be error?

[{ bad }] = foo; // // should be error?

({ bad }) => {}; // // should be error?

({ bad } = {}) => {}; // // should be error?

({ bad: bar }) => {}; // // should be error?

({ bar: { bad } = {} }) => {}; // // should be error?

```

Currently, neither of the above examples is reported. Since this would introduce many new cases in which the rule warns, I'd like more opinions from the team.

**Comment by snitin315** [comment]
@mdjermanovic I feel the same that it should check all object patterns. So all the above examples should be reported 👍🏻

**Comment by thewizarodofoz** [comment]
Hey good people, wanted to check whether anyone is working on this.
I have no experience in implementing rules, but I could give it a go if no one is available.

**Comment by Tanujkanti4441** [comment]
> The rule should probably check all object patterns. In each of the following examples, `bad` property of an object is accessed:
> 
> ```js
> /* eslint no-restricted-properties: ["error", { property: "bad" }] */
> 
> const { bad } = foo(); // should be error?
> 
> const { bar: { bad } } = foo; // // should be error?
> 
> const { bar: { bad } = {} } = foo; // // should be error?
> 
> const [{ bad }] = foo; // // should be error?
> 
> ({ bad } = foo()); // // should be error?
> 
> ({ bar: { bad } } = foo); // // should be error?
> 
> ({ bar: { bad } = {} } = foo); // // should be error?
> 
> [{ bad }] = foo; // // should be error?
> 
> ({ bad }) => {}; // // should be error?
> 
> ({ bad } = {}) => {}; // // should be error?
> 
> ({ bad: bar }) => {}; // // should be error?
> 
> ({ bar: { bad } = {} }) => {}; // // should be error?
> ```

@mdjermanovic, in these cases rule should report just the `bad` property ? or also the object's name that property is inside , if object is specified in the rules option ?

if yes for the reporting objects as well then the for object pattern in function arguments, will it work like this ?

```js
/* eslint no-restricted-properties: ["error", {object: "restrictedObject", property: "bad" }] */

const foo = ({ bad } = {}, ) => {}; // // should be error

foo(restrictedObject);  



```

**Comment by arka1002** [comment]
I’m going to do this, give me two weeks.

**Comment by Tanujkanti4441** [comment]
> I’m going to do this, give me two weeks.

Ok! assigning you.
