### ISSUE TITLE
Bug: [new config system] Files outside `cwd` were not found

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16413]
### Environment

Node version: v16.14.0
npm version: v8.3.1
Local ESLint version: `main` branch
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

```
my-app/
├── a.js
├── eslint.config.js
└── foo/
```

```js
// eslint.config.js
module.exports = [];

```

Command:

```
cd foo && eslint "../*.js" -f tap
```

### What did you expect to happen?

```
TAP version 13
1..2
ok 1 - D:\tmp\my-app\a.js
ok 2 - D:\tmp\my-app\eslint.config.js
```

This was the actual result before https://github.com/eslint/eslint/pull/16369. This is also the actual result when eslintrc config is used.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.25.0

No files matching the pattern "../*.js" were found.
Please check for typing mistakes in the pattern.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Working on this.
