### ISSUE TITLE
Suggestion: Add documentation regarding eslint-ignore comments

### ISSUE THREAD

**Issue by maritaria** [eslint/eslint#16426]
### What problem do you want to solve?

Give a comprehensive explanation of directive comments (e.g. `// eslint-disable-next-line`).

I wanted to know how to add a justification to an eslint directive, the only reference to directives (which I didn't know that's what they are called anyway) is for the `--no-ignore-lines` argument ([link](https://eslint.org/docs/latest/user-guide/command-line-interface#--no-inline-config)).

To answer my question I ended up going through the eslint source code to find [the parsing code of directive statments](https://github.com/eslint/eslint/blob/504fe59b0e0f4f5a2afb6a69aaed5cb4ca631012/lib/linter/linter.js#L343-L354).
Turns out you need a `(space)--(space)` separator to add a justification to a directive.
Silly me had only tried a single `-`, enclosing the comment with `"` and similar.

### What do you think is the correct solution?

Have a page dedicated to ignore comments, the following should be covered:

1. The available directives (including code example for each)
2. The differences between directive behaviours
3. How to add justification to directives (example for each directive type)
4. Link to the `--no-ignore-lines` argument that can disable them again
5. Links to any configuration settings that may affect behaviour of directives
6. List of rules that lint directives (if any)

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Should there be a rule/setting to require all directives to have justifications then that would be good to mention that as well.

**Comment by mdjermanovic** [comment]
Hi @maritaria! I've transferred the issue to eslint/eslint since the docs are in this repository.

> The justification thing could be added as a separate item so it is shown in the nav as well.

Makes sense to me, PR is welcome!
