### ISSUE TITLE
Bug: Autofix for `prefer-object-spread` should preserve surrounding whitespace

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#16424]
### Environment

Node version: v18.9.0
npm version: 8.19.1
Local ESLint version: v8.25.0
Global ESLint version: v8.25.0
Operating System: macOS

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```yaml
rules:
  prefer-object-spread: [2]
```
</details>

```js
console.info(Object.assign({
  foo: true,
  bar: true,
  baz: true,
}, {qux: true}));
```

### What did you expect to happen?

Autofix to fix this to:

```js
console.info({
  foo: true,
  bar: true,
  baz: true,
  qux: true,
});
```

### What actually happened?

Autfix removed the whitespace at start and end of the object, resulting in this ugly code:

```js
console.info({foo: true,
  bar: true,
  baz: true, qux: true});
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Would not really classify this as "bug", but more an enhancement to the autofix formatting.

**Comment by mdjermanovic** [comment]
This works as intended. It would be too complex to consider every formatting detail in each rule. `--fix` is multipass. After `prefer-object-spread` fixes a problem that is its responsibility, formatting rules can fix the formatting in subsequent passes. In this case, those rules are: `object-curly-newline`, `object-property-newline`, and `indent`. Here's a [playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc29sZS5pbmZvKE9iamVjdC5hc3NpZ24oe1xuICBmb286IHRydWUsXG4gIGJhcjogdHJ1ZSxcbiAgYmF6OiB0cnVlLFxufSwge3F1eDogdHJ1ZX0pKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InByZWZlci1vYmplY3Qtc3ByZWFkIjpbImVycm9yIl0sIm9iamVjdC1wcm9wZXJ0eS1uZXdsaW5lIjpbImVycm9yIl0sIm9iamVjdC1jdXJseS1uZXdsaW5lIjpbImVycm9yIix7Im11bHRpbGluZSI6dHJ1ZX1dLCJpbmRlbnQiOlsiZXJyb3IiLDJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==) with all four rules enabled. After all fixes are applied, the code looks as expected.

**Comment by silverwind** [comment]
Thanks, I see I have `object-curly-newline` and `object-property-newline` disabled in my config, so that's why the formatting result is not as expected.

**Comment by silverwind** [comment]
Afraid I can not do `object-curly-newline: ["error",{"multiline":true}]` as it is too prohibitive because forbids single-line object literals entirely.

Best I can do is `"consistent": true`, but this [leaves the leading whitespace unfixed](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc29sZS5pbmZvKE9iamVjdC5hc3NpZ24oe1xuICBmb286IHRydWUsXG4gIGJhcjogdHJ1ZSxcbiAgYmF6OiB0cnVlLFxufSwge3F1eDogdHJ1ZX0pKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InByZWZlci1vYmplY3Qtc3ByZWFkIjpbImVycm9yIl0sIm9iamVjdC1wcm9wZXJ0eS1uZXdsaW5lIjpbImVycm9yIix7ImFsbG93QWxsUHJvcGVydGllc09uU2FtZUxpbmUiOnRydWUsImFsbG93TXVsdGlwbGVQcm9wZXJ0aWVzUGVyTGluZSI6ZmFsc2V9XSwib2JqZWN0LWN1cmx5LW5ld2xpbmUiOlsiZXJyb3IiLHsiY29uc2lzdGVudCI6dHJ1ZX1dLCJpbmRlbnQiOlsiZXJyb3IiLDJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==).

**Comment by mdjermanovic** [comment]
> Afraid I can not do `object-curly-newline: ["error",{"multiline":true}]` as it is too prohibitive because forbids single-line object literals entirely.

It allows single-line object literals. Maybe you're getting an error from `object-property-newline`? In that case, you could set `{ "allowAllPropertiesOnSameLine": true }`. Here's [playground](https://eslint.org/play/#eyJ0ZXh0IjoidmFyIG9iaiA9IHsgYToxLCBiIDoyIH07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJwcmVmZXItb2JqZWN0LXNwcmVhZCI6WyJlcnJvciJdLCJvYmplY3QtcHJvcGVydHktbmV3bGluZSI6WyJlcnJvciIseyJhbGxvd0FsbFByb3BlcnRpZXNPblNhbWVMaW5lIjp0cnVlfV0sIm9iamVjdC1jdXJseS1uZXdsaW5lIjpbImVycm9yIix7Im11bHRpbGluZSI6dHJ1ZX1dLCJpbmRlbnQiOlsiZXJyb3IiLDJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==) with both rules and a single-line object literal.

**Comment by silverwind** [comment]
It's a separate issue, but the problem I'm facing is with `object-property-newline` only and code like [this](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3Qgb2JqID0ge2ZvbzogdHJ1ZSwgcmVuZGVyOiBpdGVtID0+IHtcbiAgcmV0dXJuIGl0ZW07XG59fTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im9iamVjdC1wcm9wZXJ0eS1uZXdsaW5lIjpbImVycm9yIix7ImFsbG93QWxsUHJvcGVydGllc09uU2FtZUxpbmUiOnRydWUsImFsbG93TXVsdGlwbGVQcm9wZXJ0aWVzUGVyTGluZSI6ZmFsc2V9XSwiaW5kZW50IjpbImVycm9yIiwyXX0sImVudiI6eyJlczYiOnRydWV9fX0=) which for some reason is not acceptable to the rule, even thought all properties "start" on the same line.

```js
const obj = {foo: true, render: item => { // Object properties must go on a new line if they aren't all on the same line
  return item;
}};
```

I guess I will take the lesser evil and not enable the rule but to live with the problem that `prefer-object-spread` autofixes suboptimally.
