### ISSUE TITLE
Change Request: Option to require justifications on eslint-disable directives

### ISSUE THREAD

**Issue by maritaria** [eslint/eslint#16431]
### ESLint version

v8.0.0

### What problem do you want to solve?

> This description assumes usage of ESLint in a team or on a project to help multiple programmers work on the same codebase and conform to some style.

ESLint currently either allows usage of disable directives (the default) or bans them all together (via the `noInlineConfig` setting or `--no-inline-config` cli-switch).
Banning them altogether is often too heavy handed, there are always cases where stepping outside of the common style is desirable.
On the other hand, having disables can lead to problems where the original reason to side-step a rule is lost.
The justification mechanism is a helpful tool in this regard, as we can note on rules directly the reason why they are ignored.

However, this is cannot be easily reinforced using ESLint alone.

## [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks#Custom-Configuration)

A very reasonable case where you want this re-inforced is for React projects where eslint-plugin-react-hooks, specifically the `exhaustive-deps` rule, is used.

In short, React has "hooks" which allow you to run functions automatically when their dependencies (i.e. variables used within) are changed. The mentioned rule checks that all variables used in a function are also mentioned in the dependency list of the hook (such that react correctly re-runs the function only when the depended values change).
This rule also has an autofix implemented to easily update the dependencies when they are not correct.

There are cases, for reasons I'll leave out for brevity but rest assured the choice is sound, where you want to omit one or more dependencies or depend on different things than the included variables.
In that case you often see `/* eslint-disable-next-line react-hooks/exhaustive-deps */` show up in the code, but without a justification.

So the problem here boils down to:

1. The rule (exhaustive-deps) is needed because it prevents many bugs and provides convenience in updating the deps list.
2. Disallowing `eslint-disable` is not suitable, as there are cases where you do need to ignore some deps on purpose
3. The resulting code-base is likely to have disabled dep-checks without a guarantee that the reason is documented at all.

### What do you think is the correct solution?

Either a rule or configuration option to control requirements on eslint-disable directives.
If it were to be a rule then it could be part of rule presets for teams.

Open questions:

1. Configurable for directives (e.g. able to only require for `eslint-disable-next-line` and `eslint-disable-line` directives)
2. Configurable for rules (e.g. only require justifications for a given list of rule names, or for all but a given whitelist)
3. Configurable justification content requirements (e.g. min length, max length, multi-line)

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> Either a rule or configuration option to control requirements on eslint-disable directives.

There's already a plugin rule that requires descriptions in eslint directives.

https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html

Would that solve the problem? We also use this rule in eslint codebase.

https://github.com/eslint/eslint/blob/1692840a2f763737a4891419dc304db4ebedab5d/packages/eslint-config-eslint/default.yml#L80

**Comment by snitin315** [comment]
No response hence closing.
