### ISSUE TITLE
Change Request: Consider exporting ./conf/globals.js ?

### ISSUE THREAD

**Issue by fritx** [eslint/eslint#16439]
### ESLint version

v8.0.0

### What problem do you want to solve?

I was trying to import/require from 'eslint/conf/globals':
https://github.com/eslint/eslint/blob/main/conf/globals.js

but getting an error:

```js
let { es5, es2023 } = require('eslint/conf/globals')
```

```plain
Oops! Something went wrong! :(

ESLint: 8.25.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Cannot read config file: /Users/fritx/d/eslint-config-fritx/es5-loose.js
Error: Package subpath './conf/globals' is not defined by "exports" in /Users/fritx/d/eslint-config-fritx/node_modules/eslint/package.json

Referenced from: /Users/fritx/d/silent/blog/.eslintrc.js
```

### What do you think is the correct solution?

Possible Solution is: Adding to the `exports` field in package.json
https://github.com/eslint/eslint/blob/main/package.json#L10-L14

```diff
"exports": {
    "./package.json": "./package.json",
+   "./globals": "./conf/globals.js",
    ".": "./lib/api.js",
    "./use-at-your-own-risk": "./lib/unsupported-api.js"
  },
```

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by fritx** [comment]
Sorry I just found a workaround: https://github.com/sindresorhus/globals/blob/main/globals.json

**Comment by mdjermanovic** [comment]
Hi @fritx, thanks for the issue! 

> Sorry I just found a workaround: https://github.com/sindresorhus/globals/blob/main/globals.json

Yes, [globals](https://www.npmjs.com/package/globals) package provides the same (and more).

`./conf/globals.js` is intended for internal use only.
