### ISSUE TITLE
Rule Change: padding-line-between-statements await keyword

### ISSUE THREAD

**Issue by RettentoRectangle** [eslint/eslint#16444]
### What rule do you want to change?

padding-line-between-statements

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
// Wrong code.
async function example () {
  const a = 5;
  await doSomeAsyncStuff1()

  await doSomeAsyncStuff2()
  await doSomeAsyncStuff3()

  await doSomeAsyncStuff4()
  doSomeNotAsync()
}

// Good code.
async function example () {
  const a = 5;

  await doSomeAsyncStuff1()
  await doSomeAsyncStuff2()
  await doSomeAsyncStuff3()
  await doSomeAsyncStuff4()

  doSomeNotAsync()
}
```

### What does the rule currently do for this code?

Nothing.

### What will the rule do after it's changed?

Apply padding line option for await keyword.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
Hi @RettentoRectangle, thanks for the issue!

Per our rules policies, [stylistic rules are frozen](https://github.com/eslint/eslint#stylistic-rule-updates), so we are not adding new options to the `padding-line-between-statements` rule. You can always copy the existing rule into a custom rule and make it behave the way you want.
