### ISSUE TITLE
New Rule: convert typeof xxx === 'undefined' to xxx === undefined

### ISSUE THREAD

**Issue by mvorisek** [eslint/eslint#16445]
### Rule details

convert typeof xxx === 'undefined' to xxx === undefined

### Related ECMAScript feature

ES5 §15.1.1

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
if (typeof xxx === 'undefined') {
    ...
}
```

should be fixed into

```
if (xxx === undefined) {
    ...
}
```

### Why should this rule be in the core instead of a plugin?

these rules, and recommended/normally enabled:

- https://eslint.org/docs/latest/rules/no-undefined
- https://eslint.org/docs/latest/rules/no-shadow-restricted-names
- https://eslint.org/docs/latest/rules/no-global-assign

takes care of `undefined` name is not shadowed

thus we can/should enforce the shorter style and unify the usage across the linted code

also `xxx === undefined` is constent with null checking - `xxx === null`

**Comment by mdjermanovic** [comment]
Hi @mvorisek, thanks for the issue!

As stated in [Changes to our rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies/), we don't accept new core rules that are suggestions or preferences unrelated to new ECMAScript features. There is already an accepted proposal to include this rule in  `eslint-plugin-unicorn`:

https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1492
