### ISSUE TITLE
Bug: UI inconsistency in site header

### ISSUE THREAD

**Issue by chenxsan** [eslint/eslint#16452]
### Environment

Node version: n/a
npm version: n/a
Local ESLint version: n/a
Global ESLint version: n/a
Operating System: n/a

### What parser are you using?

Other

### What did you do?

Per https://github.com/eslint/eslint/pull/16403#issuecomment-1287467273

The desktop version of eslint site has this border above its site header spanning the full width of the viewport:

<img width="2246" alt="" src="https://user-images.githubusercontent.com/1091472/197308373-3fbffba5-56ba-4483-82ed-10f21887e7fb.png">

<img width="2267" alt="" src="https://user-images.githubusercontent.com/1091472/197308356-9e39b99d-c759-4c02-9489-46eeb9310e6e.png">

<img width="2263" alt="" src="https://user-images.githubusercontent.com/1091472/197308406-76e49c8b-1193-4b5e-b491-c735cdf75e37.png">

But pages under the `docs` are exception:

<img width="2246" alt="" src="https://user-images.githubusercontent.com/1091472/197308457-3bef86d7-f540-4bf4-9cd1-52740b087144.png">

### What did you expect to happen?

I would expect the `docs` one to keep consistent with others.

E.g.,

<img width="2550" alt="" src="https://user-images.githubusercontent.com/1091472/197324906-b76a16c0-4995-48ef-a5c4-38945b364e9f.png">

### What actually happened?

Pages under `docs` don't share a consistent UI with others.

<img width="2544" alt="" src="https://user-images.githubusercontent.com/1091472/197324996-5c99903b-357d-4fe9-ba13-f6a4b33ffaaa.png">

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Sorry for breaking the mobile site with https://github.com/eslint/eslint/pull/16403, I should be more careful when editing those traditional css rules :)

**Comment by mnosov622** [comment]
Hello !

I would love to work on this issue. Could you please assign it to, me ?
