### ISSUE TITLE
Docs: Better example for shared setting

### ISSUE THREAD

**Issue by bpmutter** [eslint/eslint#16507]
### ESLint version

v8.x

### What problem do you want to solve?

Currently the example for shared settings in the docs doesn't show how the shared setting could be applied to rules. 

This is the current example:

```js
{
        settings: {
            sharedData: "Hello"
        }
}
``` 

### What do you think is the correct solution?

expand the example so that readers can see how the shared setting is applied to rules. 

apply the example to both configuration file pages: 

- https://eslint.org/docs/latest/user-guide/configuring/configuration-files
- https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by ReprogramAkash** [comment]
I would like to work on this!

**Comment by fasttime** [comment]
@ReprogramAkash are you still interested in working on this issue?
