### ISSUE TITLE
Rule Change: overlapping "no-new-symbol" and "no-new-native-nonconstructor"

### ISSUE THREAD

**Issue by danielrentz** [eslint/eslint#16513]
### What rule do you want to change?

no-new-symbol, no-new-native-nonconstructor

### What change to do you want to make?

Generate fewer warnings

### How do you think the change should be implemented?

Other

### Example code

```js
const s = new Symbol();
```

### What does the rule currently do for this code?

Both rules "no-new-symbol" and "no-new-native-nonconstructor" trigger.

### What will the rule do after it's changed?

- "no-new-symbol" should be deprecated.
- "no-new-native-nonconstructor" should become recommended (as "no-new-symbol" was).

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by snitin315** [comment]
Hi @danielrentz, Thanks for creating this issue. This was discussed in the PR and we decided not to deprecate the `no-new-symbol` as mentioned in https://github.com/eslint/eslint/pull/16368#pullrequestreview-1169545681

**Comment by snitin315** [comment]
I would suggest you disable the `"no-new-symbol"` rule in favor of the `no-new-native-nonconstructor` rule

**Comment by danielrentz** [comment]
Thanks for the pointer, missed that
