### ISSUE TITLE
Rule Change: Add fixer/suggestions for no-template-curly-in-string

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#16515]
### What rule do you want to change?

no-template-curly-in-string

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

Other

### Example code

```js
"${foo}"
```

### What does the rule currently do for this code?

Reports the string literal but does not fix or offer a suggestion.

### What will the rule do after it's changed?

Automatically fix it or offer a suggestion.
The problem with a potential fixer is that it can introduce parse errors as any expression could be inside, e.g.:
```javascript
"${a +}"
"${// Comment }"
```

There are some cases where it is easy to know that the fix is valid, eg:
```javascript
"${}" // Empty or just containing whitespace
"${value}" // Any variable reference
```

Because of that I would propose fixing in the "easy" cases and providing a suggestion otherwise.
But also provide an option like `enableFixer` which would then fix instead of providing a suggestion.

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

In the original PR #6767 it was talked about adding a fixer but it was decided to add a potential fixer later.

**Comment by mdjermanovic** [comment]
> Automatically fix it or offer a suggestion.

Auto-fixes should never change code behavior so this would always be a suggestion, but suggestions should also produce syntactically valid code. This was discussed in https://github.com/eslint/eslint/pull/15574 and we decided not to implement this change due to parsing-related complexity.

**Comment by DMartens** [comment]
I did not see that PR but the part of the safe fixes still stands:
It is always safe to fix "${}" to `${}`.
This would allow adding dynamic portions to static strings by just adding ${}.
This is especially helpful if it is not only swapping the quotes but also escaping to existing backticks.

**Comment by mdjermanovic** [comment]
Empty `${}` is a syntax error. Suggestions are allowed to change code behavior but should never produce parsing errors. We would have to parse the whole file again to make sure that the new code is syntactically valid.
