### ISSUE TITLE
Change Request: Specifying files and ignores for eslint:recommended/eslint:all

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16537]
### ESLint version

HEAD

### What problem do you want to solve?

With flat config, we currently cannot apply `eslint:recommended` or `eslint:all` to a subsection of files. In eslintrc, we can do this:

```js
module.exports = {
    overrides: [
        {
            files: ["src/foo/*.js"],
            extends: ["eslint:recommended"]
        }
    ]
};
```

### Option 1: Core plugin

One option is that we could expose a "core plugin" at `eslint/plugin` that contains the rules, parsers, and special configs that ship with ESLint. That would end up looking like this:

```js
import corePlugin from "eslint/plugin";

export default [
    {
        files: ["src/foo/*.js"],
        ...corePlugin.configs.recommended
    }
];
```

So both `eslint:recommended` and `eslint:all` would be exposed through `configs`, just like this was a standalone plugin.

**Pros:**

* Represents `eslint:recommended` and `eslint:all` as objects instead of strings.
* Brings these special configs into alignment with configs exposed in plugins, so there's just one way to include configs from outside of your project.
* We can eliminate the special `"eslint:recommended"` and `"eslint:all"` treatment (if we want).

**Cons:**

* Creates a dependency relationship between shareable configs/plugins and ESLint, where they will need to have at least a `peerDependencies` reference to ESLint, if not `dependencies` to ensure everything works correctly.

### Option 2: Function configs

Another option is we could allow function configs that receive a `context` object with a reference to the special configs, such as:

```js
export default function (context) {
    [
        {
            files: ["src/foo/*.js"],
            ...context.getConfig("eslint:recommended")
        }
    ];
}
```

So both `eslint:recommended` and `eslint:all` would be exposed through `context.getConfig()` (or some other function).

**Pros:**

* Represents `eslint:recommended` and `eslint:all` as objects instead of strings.
* Solves the problem of option 1 by ensuring that shared configs don't need a direct dependency relationship to ESLint.
* `ConfigArray` already supports function configs, it's just disabled right now.

**Cons:**

* Introducing function configs complicates sharing configs. Whereas right now we can assume that a shared config is either an object (you can use with the spread operator) or an array of objects (you can use `map()` to apply to different `files` and `ignores`), function configs hide their internals, and because they expect that `context` object, will be hard to manipulate and customize.

### Option 3: External package

Yet another option is we could publish a separate package with just the special configs. If we end up externalizing all JavaScript-related functionality (as suggested in #16482), then a step in that direction would be to publish a `@eslint/js` package, which would make it a natural location for these special configs. This is what it would look like:

```js
import js from "@eslint/js";

export default [
    {
        files: ["src/foo/*.js"],
        ...js.configs.recommended
    }
];
```

**Pros:**

* Represents `eslint:recommended` and `eslint:all` as objects instead of strings.
* Solves the problem of option 1 by ensuring that shared configs don't need a direct dependency relationship to ESLint.
* By publishing an out-of-band `@eslint/js` package, we would be free to update these configs as necessary and also start down the path of removing JS-specific functionality from the core.

**Cons:**

* Introduces another package to manage and release.
* Possible synchronicity issues between the `eslint` package and the `@eslint/js` package, although this could likely be mitigated by also moving rules into `@eslint/js` at some point.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

There may be other options I haven't listed out, so feel free to suggest them.

This appears to be the one case that eslintrc supports and flat config doesn't, so figuring this out is important to get us past the beta stage.

I don't want to consider adding `extends` to flat config to solve this as it would introduce additional complexity into the config system that we were hoping to avoid with flat config.

**Comment by mdjermanovic** [comment]
Given all pros and cons, I think the best option is 2.

> * Introducing function configs complicates sharing configs. Whereas right now we can assume that a shared config is either an object (you can use with the spread operator) or an array of objects (you can use `map()` to apply to different `files` and `ignores`), function configs hide their internals, and because they expect that `context` object, will be hard to manipulate and customize.

Assuming that a shared config will document what it exports (an object, array, or function), if it's a function, config file that uses the shared config can call it with the `context` object and then customize the return value the same as it would customize an exported object/array?

**Comment by snitin315** [comment]
> Assuming that a shared config will document what it exports (an object, array, or function), if it's a function, config file that uses the shared config can call it with the context object and then customize the return value the same as it would customize an exported object/array?

Ideally, yes they should document this. However, this will increase the learning curve for both users and plugin authors and could be problematic for users depending upon older versions of plugins who haven't updated their docs yet.

**Comment by aladdin-add** [comment]
I'm wondering if we could take option 4:  exporting the configs in the ESLint package itself, e.g. `require("eslint").configs.recommended`.

pros: same as option 1.

it was mentioned in the rfc, the reasons for not being adopted is ["the config needs to specify a particular version of ESLint as its dependency".](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification#why-are-eslintrecommended-and-eslintall-strings-instead-of-objects). but imo, it seems not a very big deal - the shared configs can specify eslint as peer deps, and give a range instead of an exact version, e.g. `"eslint": "~8.0.0"`

**Comment by nzakas** [comment]
@aladdin-add that's really just option 1 with a different syntax. :)

@mdjermanovic

> Assuming that a shared config will document what it exports (an object, array, or function), if it's a function, config file that uses the shared config can call it with the context object and then customize the return value the same as it would customize an exported object/array?

This forces any config that is consuming the function config to also define a function config, which seems like a lot of unnecessary boilerplate to me. This is why option 2 is my least favorite of the three I thought of.

Option 3 is my current favorite assuming we want to go the route of splitting out JS-specific functionality in the future.

**Comment by nzakas** [comment]
**TSC Summary:** The one capability flat config doesn't currently have that eslintrc does is the ability to implement `extends: "eslint:recommended"`. This is the last compatibility piece for flat config to address before we move on to the next phase. This issue presents three options for how to move forward.

**TSC Question:** How do we want to support this use case in flat config?

**Comment by btmills** [comment]
In the 2022-12-29 TSC meeting, we decided to publish the `recommended` and `all` configs in a new package named `@eslint/js`. Initially, this package will live in the `eslint` repository. Eventually, it will contain all JS-specific logic.

**Comment by CallMeLaNN** [comment]
Just want to share I was wondering why it does work with `eslint:recommended` but doesn't work with other plugin's configs as a new way to replace `.eslintrc` `extends`.

Good to know that the special string and the example will be removed and updated to avoid this confusion:

```js
import jsdoc from "eslint-plugin-jsdoc";

export default [
  "eslint:recommendded",
  jsdoc.configs.recommended, // Example from the doc but other plugins that internally using `extends` doesn't work.
  "plugin:other-plugin/recommended", // So I tried this because the array seems to accept string like `extends` but I was wrong.
  // It was an idea also to c&p from the old `extends` to here
  {
    // ...
  }
]
```

The `FlatCompat` is really helpful in this case. I learned the difference by logging the compat output and managed to make it work either by using `FlatCompat` or rearrange those config objects.

BTW The new flat config is really nice and easier to configure.
