### ISSUE TITLE
CLIEngine needs a method to run the selected reporter

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#1653]
So every consumer don't have to reimplement that.

See: https://github.com/sindresorhus/grunt-eslint/pull/41#issuecomment-66827746

**Comment by nzakas** [comment]
I'm not sure if it should run the reporter or just retrieve it so you can run it yourself. I'm leaving towards the latter.

**Comment by sindresorhus** [comment]
I'm fine with the latter as long as it's a simple method call.

**Comment by nzakas** [comment]
Working on this.

All formatters work by calling `formatter(report)`, where `report` is what's returned from `executeOnFiles()` or `executeOnText()`.
