### ISSUE TITLE
Rule Change: prefer-named-capture-group: add suggestion fixer

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#16530]
### What rule do you want to change?

prefer-named-capture-group

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
function toTextContentTitle(contentTitle: string): string {
  return contentTitle.replace(/`([^`]*)`/gi, '$1');
}
```

### What does the rule currently do for this code?

It reports a complaint on the regular expression: `/`([^`]*)`/gi`

```plaintext
Capture group '([^`]*)' should be converted to a named or non-capturing group.
```

### What will the rule do after it's changed?

In addition, it'd be nice to also provide a suggestion fixer that uses some arbitrary names for the suggestion group. Maybe: `temp1`, `temp2`, etc.?

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

Named capture groups are pretty new and many developers (myself included!) don't know the syntax on demand. Even if they do, it's just nice to have a suggestion when there's a non-trivial complaint to fix.

**Comment by mdjermanovic** [comment]
Makes sense to me, but would like more opinions from the team as this would be the first core rule suggestion that requires additional user action (renaming `temp1` to a meaningful name) after it's applied.

Alternatively, we could provide an example of the syntax in the error message.

**Comment by snitin315** [comment]
I'm in favor of providing a suggestion fix 👍🏻 

@mdjermanovic I suppose it won't be the first one, we recently added similar suggestions for the `no-empty` rule in https://github.com/eslint/eslint/pull/16470 that would also require additional action (modifying`/* empty */` comment) after it's applied.
