### ISSUE TITLE
Invoking a core rule from a custom rule?

### ISSUE THREAD

**Issue by natecavanaugh** [eslint/eslint#1654]
Hi there,
I tried posting the following to the mailing list, but it seems to have never gone though, so I thought I'd try here.
I'm wondering if it's possible to invoke one rule from another rule, or somehow reuse the code from one rule to another.
What I'm trying to do is suppress a certain rule under certain conditions (as an example, I want the no-undef rule to run most of the time, but for certain files/filetypes, I want to ignore only that one rule).
My idea was to create a custom rule, and do my checking in there. However, I would like to avoid duplicating all of the code in that rule.
Is there some way to invoke it from my custom rule, or, is there a way to conditionally suppress that rule in certain situations?

Thanks in advance :)

**Comment by nzakas** [comment]
Rules aren't allowed to interact with other rules. The best you can do is require an existing rule and use that to somehow modify what your rule does.
