### ISSUE TITLE
Rule Change: (fill in)

### ISSUE THREAD

**Issue by edisonLzy** [eslint/eslint#16571]
### What rule do you want to change?

padding-line-between-statements

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
export const a = '1';
export const b = '2';
export class A {
};
```

### What does the rule currently do for this code?

```js
export const a = '1';
export const b = '2';
export class A {
};
```

### What will the rule do after it's changed?

```js
export const a = '1';
export const b = '2';

export class A {
};
```
- give a options like `multiline-export` 🤔️ ?

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
Hi @edisonLzy, thanks for the issue!

Per our rules policies, [stylistic rules are frozen](https://github.com/eslint/eslint#stylistic-rule-updates) so we are not adding new options to the `padding-line-between-statements` rule. You can always copy the existing rule into a custom rule and make it behave the way you want.
