### ISSUE TITLE
Change Request: [flat config] re-read the eslint.config.js file if it has been changed

### ISSUE THREAD

**Issue by alexander-doroshko** [eslint/eslint#16576]
### ESLint version

8.28.0

### What problem do you want to solve?

Hi from JetBrains! WebStorm [ESLint integration](https://www.jetbrains.com/help/webstorm/eslint.html) has a wrapper Node.js process that lives for a long time and calls `ESLint.lintText()` as needed. ESLint config files might be edited between `ESLint.lintText()` calls.

In the 'flat config' mode, the `eslint.config.js` files are never re-read from disk. The reason is that they are loaded using [import()](https://github.com/eslint/eslint/blob/886a0386897f96d2da95eba8c52bd893fcbf7e86/lib/eslint/flat-eslint.js#L277-L284), which caches the result forever.

So, the problem is that the ESLint results that WebStorm users see do not match the current configuration (`eslint.config.js` files).

Cleaning [require.cache](https://nodejs.org/api/modules.html#requirecache) doesn't help. It looks like there's [no way to drop the internal cache](https://nodejs.org/api/esm.html#no-requirecache) of import(). 

### What do you think is the correct solution?

It would be great if the [loadFlatConfigFile()](https://github.com/eslint/eslint/blob/886a0386897f96d2da95eba8c52bd893fcbf7e86/lib/eslint/flat-eslint.js#L277-L284) function returned up-to-date result each time even if the config file has been edited between loadFlatConfigFile() invocations. Thank you!

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @alexander-doroshko, thanks for the issue!

> In the 'flat config' mode, the `eslint.config.js` files are never re-read from disk. The reason is that they are loaded using [import()](https://github.com/eslint/eslint/blob/886a0386897f96d2da95eba8c52bd893fcbf7e86/lib/eslint/flat-eslint.js#L277-L284), which caches the result forever.
>
> It would be great if the [loadFlatConfigFile()](https://github.com/eslint/eslint/blob/886a0386897f96d2da95eba8c52bd893fcbf7e86/lib/eslint/flat-eslint.js#L277-L284) function returned up-to-date result each time even if the config file has been edited between loadFlatConfigFile() invocations. Thank you!

Any ideas on how we could do this? I'm not sure if there's already built-in support for this use case in Node.js.

Maybe we could check if the config file's `mtime` has changed, and then add a query to force reloading.

**Comment by alexander-doroshko** [comment]
The first idea that came to my mind is based on [this article](https://ar.al/2021/02/22/cache-busting-in-node.js-dynamic-esm-imports/#cache-invalidation-in-esm-with-dynamic-imports). Maybe it will work if you change
```
import("file:///path/to/eslint.config.js")
```
to
```
import("file:///path/to/eslint.config.js?mod=12345")
```
where 12345 is the file modification stamp?

**Comment by alexander-doroshko** [comment]
I don't know how probable it is that `eslint.config.js` imports/requires other files that might also be edited since they have been loaded. The trick with `?mod=12345` will probably work only for the `eslint.config.js` file itself.

**Comment by mdjermanovic** [comment]
> The first idea that came to my mind is based on [this article](https://ar.al/2021/02/22/cache-busting-in-node.js-dynamic-esm-imports/#cache-invalidation-in-esm-with-dynamic-imports). Maybe it will work if you change
> 
> ```
> import("file:///path/to/eslint.config.js")
> ```
> 
> to
> 
> ```
> import("file:///path/to/eslint.config.js?mod=12345")
> ```
> 
> where 12345 is the file modification stamp?

I think this would work. And if we always append the file modification stamp, then we don't need to keep the previous one and check if it has changed. [`fileURL`](https://github.com/eslint/eslint/blob/886a0386897f96d2da95eba8c52bd893fcbf7e86/lib/eslint/flat-eslint.js#L280) we're passing to `import()` is an URL object, so we could do something like `fileURL.searchParams.append("mod", "12345")`.

> I don't know how probable it is that `eslint.config.js` imports/requires other files that might also have been edited since they have been loaded. The trick with `?mod=12345` will probably work only for the `eslint.config.js` file itself.

That case most likely wouldn't be covered, but if we manage to reload `eslint.config.js`, that would at least match the current functionality of eslintrc . In eslintrc, we're using [`import-fresh`](https://github.com/eslint/eslintrc/blob/2a2bef144e9b5ef0fbf780abae0890e0c1f9d23a/lib/config-array-factory.js#L43) to [load JS config files](https://github.com/eslint/eslintrc/blob/2a2bef144e9b5ef0fbf780abae0890e0c1f9d23a/lib/config-array-factory.js#L234-L243). It removes the config module (`.eslintrc.js`) from the require cache, but doesn't remove modules that are required from it so they're not reloaded.

**Comment by alexander-doroshko** [comment]
Thanks, being on par with eslintrc sounds reasonable.
Complete reloading probably requires running it in a separate [context](https://nodejs.org/api/vm.html).

**Comment by alexander-doroshko** [comment]
Hi, I see the `Feedback Needed` tag, do you need any info from me to proceed with the request? Thank you.

**Comment by alexander-doroshko** [comment]
Oops, sorry, I pressed the wrong button, and bots have updated the labels. Sorry about that. I'm afraid I don't have permissions to restore the correct issue state.

**Comment by mdjermanovic** [comment]
I'm in favor of appending a query with file modification stamp in order to force reloading `eslint.config.js`.

@nzakas what do you think?

**Comment by nzakas** [comment]
Appending a time stamp query string seems like an easy way to do this. 👍 

@alexander-doroshko by the way, we would love to have your feedback on this discussion:
https://github.com/eslint/eslint/discussions/16557

We are rethinking our API and would love feedback from integrators on what the current API isn’t doing for you. (Kind of like in this thread.)

**Comment by mdjermanovic** [comment]
PR https://github.com/eslint/eslint/pull/16608. Unfortunatelly, this approach doesn't seem to work when the config file is a CJS module.

https://github.com/nodejs/node/issues/29812

https://github.com/nodejs/modules/issues/417

**Comment by nzakas** [comment]
I'm assuming the issue is that Node.js always caches a CommonJS config file when using `import()`?

**Comment by mdjermanovic** [comment]
Yes, per comments from the issues I linked, when `import`-ing a CJS module Node.js gets file path from the URL and then passes it to the `require` infrastructure, which then loads and caches the module per the file path. Query strings are lost in the process.

I'll try the solution @fasttime suggested in https://github.com/eslint/eslint/pull/16608#issuecomment-1337022476, just had to contemplate whether we should reload CJS configs always, like in the eslintrc config system, or only if they've changed. I think we should do the latter, so that the behavior is the same as with ESM configs.
