### ISSUE TITLE
Bug: invalid type does not throw a linter error

### ISSUE THREAD

**Issue by JakeIV** [eslint/eslint#16577]
### Environment

Node version: v16.18.0
npm version: v8.19.2
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22621

### What parser are you using?

@typescript-eslint/parser

### What did you do?

https://github.com/gdscports/react-snake/pull/51/commits/b64d9a1667001016fab8795eebd05fbd5fd5a28c
Line 17 string is incorrect, it should be a KeyboardEvent

### What did you expect to happen?

a lint error should be thrown

### What actually happened?

it passed the linter

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @JakeIV, thanks for the issue! 

This is a question for Typescript or [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint). Core ESLint does not check types.
