### ISSUE TITLE
docs: Clear button in Searchbar flickers and disappears

### ISSUE THREAD

**Issue by shanpriyan** [eslint/eslint#16584]
### ESLint version

v8.21.0

### What problem do you want to solve?

1. Clear button appears only if the search query length is greater than 2 
2. Once the `no results found` modal appears if we enter text into search input, the clear button starts flickering and disappears. 

https://user-images.githubusercontent.com/42532987/204036388-a78e1747-145e-4f41-9299-e2def9b5a76d.mp4

### What do you think is the correct solution?

1. Clear button shouldn't disappear if a search query is present
2. Clear button shouldn't flicker if we type after the `no results found` modal appears

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I'm willing to send a fix to https://github.com/eslint/eslint.org (blog page) too.

Also, It would be better if we add debouncing.

**Comment by harish-sethuraman** [comment]
Can you send a fix for this in https://github.com/eslint/eslint.org as well?

**Comment by shanpriyan** [comment]
> Can you send a fix for this in https://github.com/eslint/eslint.org as well?

Sure 🚀
