### ISSUE TITLE
docs: Title Case for all headings

### ISSUE THREAD

**Issue by bpmutter** [eslint/eslint#16609]
### ESLint version

latest

### What problem do you want to solve?

inconsistent heading capitalization in the docs

### What do you think is the correct solution?

per convo w Nicholas, Title Case for all headings

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
@bpmutter Is this issue still relevant or can we close it?

**Comment by amareshsm** [comment]
It is not required so closing this Issue. Ref - https://github.com/eslint/eslint/pull/17053#issuecomment-1633384277
