### ISSUE TITLE
Bug: default formatter gives incorrect advice with option `--stdin`

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#16613]
### Environment

Node version: v18.12.1
npm version: v8.19.2
Local ESLint version: v8.29.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.1.0

### What parser are you using?

Default (Espree)

### What did you do?

The output of the default "stylish" formatter always mentions the `--fix` option when there are fixable problems. But the `--fix` option cannot be used together with `--stdin`, which makes the output misleading in some cases.

For example, if I run this command in a zsh terminal

```sh
echo '/* eslint semi: 1 */ foo' | npx eslint --stdin
```

I get

```
<text>
  1:25  warning  Missing semicolon  semi

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

But if I add the `--fix` option as suggested and run

```sh
echo '/* eslint semi: 1 */ foo' | npx eslint --stdin --fix
```

then I get an error

```
The --fix option is not available for piped-in code; use --fix-dry-run instead.
```

### What did you expect to happen?

The output should not mention `--fix`, because it is not applicable. It could mention `--fix-dry-run` instead, or nothing at all, e.g.

```
<text>
  1:25  warning  Missing semicolon  semi

✖ 1 problem (0 errors, 1 warning)
```

### What actually happened?

See above.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

While digging into this issue I realized that there is another situation where the `--fix` text may not be appropriate. This is the case when the stylish formatter is called from user code, rather than from the ESLint CLI. It's up to discussion if and how this case should be handled.

So the questions are:

* What to print when ESLint is launched from the CLI with the `--stdin` option.
* What to print when the formatter is called outside the CLI through the Node API.

As for the technical part regarding the implementation, I can think of several different approaches.

1. The stylish formatter could check if the current process is executing the ESLint CLI, and if so, check if the option `--stdin` has not been used. Only in that case, the `--fix` part would be added to the output.
2. The CLI could pass a hint to the formatter in form of a new property in the [`resultsMeta`](https://github.com/eslint/eslint/blob/main/lib/eslint/eslint.js#L629) options, to signalize whether the `--fix` part should be included in the output or not.
3. Like (2), but using an [environment variable](https://eslint.org/docs/latest/developer-guide/working-with-custom-formatters#using-environment-variables) to provide the hint.
4. Create a new formatter similar to the stylish formatter, but without the part about the `--fix` option. The common base class or prototype of the new formatter and the stylish formatter could be even exposed to users who wish to customize the output even more.

**Comment by nzakas** [comment]
This seems like an edge case that I'm honestly not sure is worth addressing.

Formatters are intentionally prevented from knowing the environment in which they are being executed so they can be executed anywhere. For instance, to generate the documentation page: https://eslint.org/docs/latest/user-guide/formatters/

In any case, I think having the message about `--fix` is important to have in the default output even if it won't work with `--stdin`. The `--stdin` use case is definitely a tiny percentage of overall use, so I don't think it's worth optimizing for that.

**Comment by fasttime** [comment]
I was actually more concerned about the situation of a tool that uses the ESLint API to generate results but does not expose a `--fix` option on the command line, because it doesn't fix files at all or uses a different mechanism to provide autofix. Currently, such a tool *cannot* use the default formatter, or it must otherwise accept that the output could be misleading sometimes.
I was not ready to call this a bug, because nothing suggests that the default formatter should be used outside the ESLint CLI. If this is the case, or if the edge cases are negligible, then this issue can be closed.

**Comment by mdjermanovic** [comment]
I think that passing additional context to formatters or determining it inside the formatter would be too complex a solution for this case. Maybe we could consider just rewording the text to be more specific, e.g.,  `` 0 errors and 1 warning potentially fixable with the `--fix` ESLint CLI option. ``, or perhaps more generic, e.g., `` 0 errors and 1 warning potentially automatically fixable. ``, so that either way it's not misleading?

**Comment by fasttime** [comment]
@mdjermanovic Maybe so. In that case, ``the `--fix` ESLint CLI option`` works probably better. Otherwise, I'd expect questions like "How to fix potentially automatically fixable errors and warnings?" to pop up here and on StackOverflow.

**Comment by nzakas** [comment]
If we want to add "ESLint CLI" into the text, I'm fine with that, but I do not want to remove `--fix` from the message, as I think that will introduce confusion where there wasn't any previously.

I'm also fine with not making a change here, as I think this is an extreme edge case that we shouldn't spend much time on either way.
