### ISSUE TITLE
max-len options: allowUrlComments

### ISSUE THREAD

**Issue by malandrew** [eslint/eslint#1661]
jscs has one nice exception option for the line-length rule, which is to allow long URLs to break the max line length rule. This is preferable to using a URL shorteners.

**Comment by nzakas** [comment]
Can you give an example or point us to some docs about the JSCS rule?

**Comment by Nate-Wilkins** [comment]
@malandrew http://tinyurl.com/ :+1:

**Comment by adamnbowen** [comment]
I was able to find an example in their documentation, though it specifically references URLs in comments, not actual code: http://jscs.info/rules.html#maximumlinelength
> allowUrlComments: (default: false) allows comments with long urls to break the rule

Here is a link to the code governing that rule: https://github.com/jscs-dev/node-jscs/blob/4c31d9ee8039d87aa6db346b5efe7d5679551d21/lib/rules/maximum-line-length.js#L97-L103

@malandrew Are you asking for a rule that mimics this one in JSCS, or are you asking for one that allows URLS anywhere in your code (such as a config variable) to override the line length issue?

**Comment by mathieumg** [comment]
I would love this rule as well. Unlike #2221, I don't need to ignore length for all comments, just single-line URLs, like `// URL`.

**Comment by nzakas** [comment]
We're still a missing a true description of what's being requested here. Without that, we can't move forward.

**Comment by mathieumg** [comment]
Valid:

```
// Some comment referring to content in a URL (MDN for example):
// http://www.a-very.com/long/long/long/long/long/long/long/long/long/long/long/long/url
```

```
// http://www.a-very.com/long/long/long/long/long/long/long/long/long/long/long/long/url
```

Invalid:

```
// Some comment referring to content in a URL (MDN for example): http://www.a-very.com/long/long/long/long/long/long/long/long/long/long/long/long/url
```

```
// A very long long long long long long long long long long long long long comment that is not an URL.
```

Obviously, a line is considered "long" when it's length exceeds `max-len`. I imagine the URL would be "ignored" using a RegEx but for the sake of flexibility a more general "ignore" option could allow for an array for RegEx objects describing which pattern to ignore I imagine. Is that what you were looking for or do you need more precision in certain areas?

**Comment by nzakas** [comment]
So the URL must be alone on a comment line to be allowed? What about for block comments?

**Comment by adamnbowen** [comment]
I think a sane default would be to have:


1. For single line comments, only ignore the length of the URL if it is right after the comment mark (allowing for white space in between)









​2. For a block level comment, either the URL on its own line, or after only a * symbol, with perhaps white space in between.

​

​That probably covers most common use cases.





​



Adam Bowen


Head of Software Engineering
Ochre
4240 Duncan Ave #200
Saint Louis, MO 63110

847-644-8847






On Saturday, May 16, 2015 at 10:50 AM, Nicholas C. Zakas <notifications@github.com>, wrote:

So the URL must be alone on a comment line to be allowed? What about for block comments?

**Comment by mathieumg** [comment]
@adamnbowen At least GitHub indicates it was an email reply. :smile: 

@nzakas What @adamnbowen said follows suit with what I had in mind, I just didn't think about block comments. So in addition to my examples above:

Valid:

```javascript
/*
 * Text.
 * LONG_URL.
 */
```

```javascript
/*
 * LONG_URL.
 */
```

```javascript
/*
 Text.
 LONG_URL.
*/
```

```javascript
/*
 LONG_URL.
*/
```

Invalid:

```javascript
/*
 * Text: LONG_URL.
 */
```

```javascript
/*
 * LONG_TEXT.
 */
```

I guess there could be an argument made about which character, if any, is at the beginning of an intermediary comment block line, but I imagine it could be easily wildcard-ed into an eventual RegEx.

So a long URL should be ignored if and only if:

- We're in a line comment: the line starts with `//`, possibly whitespace thereafter, and then the URL, alone.
- We're in a block comment: the line possibly starts with combinations of whitespace and a single character (nothing, ` `, ` *`, `* `, ` * `, etc.), and then the URL alone.

**Comment by nzakas** [comment]
Sounds good. Should we just allow this by default or should it be an option?

**Comment by mathieumg** [comment]
I think it should be opt-in since it allows to circumvent a rule, technically speaking. I don't really mind honestly, if most people want it as a default it would be fine too.

**Comment by nzakas** [comment]
OK, let's make it opt-in

**Comment by rlidwka** [comment]
I think it should be the default, because I know of no reason why somebody would want to explicitly split URLs.

**Comment by TomFrost** [comment]
I'd like to expand the scope of this just slightly -- if someone is following standard JSDoc convention, they might have a `@see url-here` within a block comment.  Example:

```javascript
/**
 * Escapes a string so that it can be treated as a string literal within a
 * regular expression.
 * @param {string} str The string to be escaped
 * @returns {string} the RegExp-escaped string.
 * @see https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions
 * @private
 */
```

That URL breaks the max-len in my eslint, and save for using tinyurl, there's nothing I can do about it.

**Comment by nzakas** [comment]
@TomFrost how is that expanding the scope? Your case would already be covered.

**Comment by TomFrost** [comment]
@nzakas This quote is what had me concerned:

>We're in a block comment: the line possibly starts with combinations of whitespace and a single character (nothing, , *, *, *, etc.), and then the URL alone.

To me, that says that the URL will be ignored if there's a `*` followed by the URL alone. In my case, there's ` * @see ` before the URL. Apologies if I misunderstood.

**Comment by nzakas** [comment]
Ah, I see what you mean. 

It might just be best if URLs are always treated the same wherever they appear. I suspect we will run into more edge cases if we don't do so.

So, let's just say if a comment line ends with a URL, in either a line or block comment, it is omitted from the check with this option.

**Comment by TomFrost** [comment]
That sounds perfect

**Comment by mathieumg** [comment]
> So, let's just say if a comment line ends with a URL, in either a line or block comment, it is omitted from the check with this option.

But then a line with any amount characters followed by a long URL would still be valid and I believe it should be discouraged to at least minimize the impact of something already "too long".

**Comment by adamnbowen** [comment]
@mathieumg If you check the JSCS code I linked above, a solution like theirs (tweaked for our use case) would handle that—we could just remove the URL from the line count: https://github.com/jscs-dev/node-jscs/blob/4c31d9ee8039d87aa6db346b5efe7d5679551d21/lib/rules/maximum-line-length.js#L97-L103

So I think @nzakas has the right solution.

**Comment by mathieumg** [comment]
@adamnbowen Wouldn't that still allow a line with `max - 1` characters followed by a long URL?

**Comment by adamnbowen** [comment]
@mathieumg Yes, but as he pointed out, there isn't going to be a rule guaranteed to work for every use case—We just had @TomFrost point out that the proposed rule didn't play nicely with JSDoc, and I'm sure there are numerous other documentation conventions that we'd have to support.

Rather than have 7 complicated rules for detecting `* `, `* @word`, `* word:`, `*@word (Type)`, etc., it seems reasonable to just ignore the URL length if it is at the end of a line.

**Comment by rlidwka** [comment]
> Rather than have 7 complicated rules for detecting *, * @word, * word:, * @word (Type), etc., it seems reasonable to just ignore the URL length if it is at the end of a line.

What if there is a single punctuation character at the end of the URL? For example, URL is enclosed in quotes?

Imho, ignoring URL length makes most sense here.

**Comment by mathieumg** [comment]
> Imho, ignoring URL entirely makes most sense here.

Agreed, already better than ignoring the line altogether.

**Comment by nzakas** [comment]
To reiterate, this is the approach:

> So, let's just say if a comment line ends with a URL, in either a line or block comment, it is omitted from the check with this option.

Let's implement this and try it out. If it needs to be adjusted, we will adjust, but let's argue with code.
