### ISSUE TITLE
Docs: Add documentation for "argsIgnorePattern" to rule "no-unused-vars"

### ISSUE THREAD

**Issue by L3XAWeasel** [eslint/eslint#16616]
### ESLint version

v8.29.0

### What problem do you want to solve?

Currently on https://eslint.org/docs/latest/rules/no-unused-vars the documentation for the  "argsIgnorePattern" option on the respective rule is missing, even though the options exists.

### What do you think is the correct solution?

Add the documentation in the "style" of the present documentation of "varsgnorePattern" of the "no-unsed-vars" rule.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Technically this also affects the respective typescript rule (@typescript-eslint/no-unused-vars) which links the eslint documentation.

**Comment by mdjermanovic** [comment]
Hi @L3XAWeasel, thanks for the issue!

Isn't the option documented here:

https://eslint.org/docs/latest/rules/no-unused-vars#argsignorepattern

**Comment by nzakas** [comment]
It seems like this was addressed in the merged PR, so closing.
