### ISSUE TITLE
Bug: `no-use-before-define` cannot be disabled in subconfig once enabled globally

### ISSUE THREAD

**Issue by mvorisek** [eslint/eslint#16621]
### Environment

Node version: v16.1.0
npm version: v7.11.2
Local ESLint version: v8.29.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### How to reproduce?

checkout https://github.com/mvorisek/Fomantic-UI/tree/c197bd75d9a0299e58c3516375c57ab697fd310f

run eslint like in CI:
```
yarn
yarn add -D eslint-config-airbnb-base eslint-plugin-unicorn
npm run lint
```

### What did you expect to happen?

no error

for `tasks/` dir there is a https://github.com/mvorisek/Fomantic-UI/blob/c197bd75d9a0299e58c3516375c57ab697fd310f/tasks/.eslintrc.js#L4 subconfig which disables the `no-use-before-define` rule

in the same subconfig there is also "override" for `globals` and it works, thus the subconfig is read by eslint

### What actually happened?

https://github.com/mvorisek/Fomantic-UI/actions/runs/3629685378/jobs/6122180883#step:5:11

```
/home/runner/work/Fomantic-UI/Fomantic-UI/tasks/admin/components/init.js
Error:    96:17  error  'addRemote' was used before it was defined   no-use-before-define
Error:    98:17  error  'initRepo' was used before it was defined    no-use-before-define
Error:   108:17  error  'addRemote' was used before it was defined   no-use-before-define
Error:   126:17  error  'pullFiles' was used before it was defined   no-use-before-define
Error:   133:17  error  'resetFiles' was used before it was defined  no-use-before-define
Error:   140:17  error  'nextRepo' was used before it was defined    no-use-before-define

/home/runner/work/Fomantic-UI/Fomantic-UI/tasks/admin/components/update.js
Error:   104:25  error  'commitFiles' was used before it was defined    no-use-before-define
Error:   122:25  error  'pushFiles' was used before it was defined      no-use-before-define
...
```

**Comment by mvorisek** [comment]
`-c .eslintrc.js` removal fixes the problem

https://github.com/mvorisek/Fomantic-UI/blob/c197bd75d9a0299e58c3516375c57ab697fd310f/tasks/.eslintrc.js#L7 is however honored in both cases, I would expect:

- this to be fixed
- or subconfig completely ignored (/w possibly a warning)

**Comment by yeonjuan** [comment]
> however honored in both case

@mvorisek It depends on your linted files path. so it's intended behaviors

```
.eslintrc.js
/tasks
   | - some.js   // `no-undef` allows to use `files` as a global variable.
   | - .eslintrc.js  // { globals: { files: true } } 
/others
   | - some.js  //  `no-undef` disallows to use `files`as a global variable.
```
