### ISSUE TITLE
 Standardize auto-labeling 

### ISSUE THREAD

**Issue by amareshsm** [eslint/eslint#16620]
### What problem do you want to solve?

Auto labeling Pull Request - Currently, we are using the ESLint bot to add labels based on the commit message. 

### What do you think is the correct solution?

In some cases the bot is not required we can use [labeler](https://github.com/actions/labeler) to automatically label new pull requests based on the paths of files being changed.

Eg: 
1. Adding a `documentation` label if any file changes in the docs folder.
2. Adding a `rule` label if any file changes in the rule folder.

We can check where else we can use the labeler. For the remaining cases, we can use the ESLint bot itself.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Thoughts?

**Comment by nzakas** [comment]
I'm okay with this. Are there any other labels we can add in this way?

**Comment by snitin315** [comment]
I'm ok with this change too. I believe the following labels can be added:
- `documentation`: changes in `docs/**`
- `rule`: changes in `lib/rules/*.js`
-  `cli`: changes in `lib/cli.js` `lib/cli-engine`
-  `core`: changes in `lib/{linter,eslint,configs}`
- `formatter`: changes in `lib/cli-engine/formatters`

**Comment by harish-sethuraman** [comment]
I think we didn't want this for documentation?

https://github.com/eslint/eslint/pull/16615#discussion_r1041850113

**Comment by nzakas** [comment]
@amareshsm are you still interested in pushing this forward?

**Comment by amareshsm** [comment]
> @amareshsm are you still interested in pushing this forward?

I missed this one thanks for bumping up. I will look into this soon.
