### ISSUE TITLE
Create some shared eslint configurations under monorepo, but it fails when extends

### ISSUE THREAD

**Issue by Mr-GaoYu** [eslint/eslint#16630]
### Environment

Node version: v16.7.1
pnpm version: 7.17.1
Local ESLint version: 8.29.0
Global ESLint version: 8.29.0
rush version：5.86.0

github ：https://github.com/Mr-GaoYu/anadi-rush-core.git

### What parser are you using?

@babel/eslint-parser

### What did you do?

maker/eslint

![image](https://user-images.githubusercontent.com/67352005/206340208-893cd160-34d0-4925-a5c2-c4bfc3514f29.png)
![image](https://user-images.githubusercontent.com/67352005/206340280-b84f115b-49ed-48f6-8e36-cbd88cf0365b.png)

mspbots/login

![image](https://user-images.githubusercontent.com/67352005/206340358-0f76da5f-a3d1-45ff-b77f-cfb19d6bdc07.png)
![image](https://user-images.githubusercontent.com/67352005/206340391-858a4d99-6e04-4a6f-bc81-3199e1fbcee9.png)

vscode  setting.json 
![image](https://user-images.githubusercontent.com/67352005/206340462-161dd76f-af35-48e8-a0c2-b3fdbad6e0eb.png)

### What did you expect to happen?

I created a file and entered the alert, but the vscode plugin eslint didn't give me any hints

### What actually happened?

![image](https://user-images.githubusercontent.com/67352005/206340717-f6cc8cc0-07b9-4075-962e-ed7abb2d8576.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by yeonjuan** [comment]
Hi @Mr-GaoYu It seems not a ESLint's bug so I'll close this issue.
Since I tested it, figured out that It's because of your `exports` field in `maker/eslint/package.json`. removing `exports: {}` will fix this issue.
