### ISSUE TITLE
Rule Change: make no-return-await suggestable

### ISSUE THREAD

**Issue by dbartholomae** [eslint/eslint#16632]
### What rule do you want to change?

no-return-await

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
async function foo {
  return await Promise.resolve("bar")
}
```

### What does the rule currently do for this code?

// Error, but don't change:
async function foo {
  return await Promise.resolve("bar")
}

### What will the rule do after it's changed?

// Fix it
async function foo {
  return Promise.resolve("bar")
}

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

Hi! There have been discussions about whether `no-return-await` [should be a core rule](https://github.com/eslint/eslint/issues/14542). These are resolved - and, consequently, I would argue that the rule should be auto-fixable.

**Comment by yeonjuan** [comment]
Hi @dbartholomae This proposal has been made in the past (https://github.com/eslint/eslint/issues/7593)
And it was not accepted due to the removing `await` can change the behavior of code

**Comment by mdjermanovic** [comment]
I agree with @yeonjuan, per https://github.com/eslint/eslint/issues/7593#issuecomment-260419426 this doesn't seem safe for autofixing. 

Perhaps we could consider implementing this as [suggestions](https://eslint.org/docs/latest/developer-guide/working-with-rules#providing-suggestions)?

**Comment by dbartholomae** [comment]
Thanks, I didn't find that issue when searching.

**Comment by dbartholomae** [comment]
Happy to close this, unless it makes sense to discuss implementing this as a suggestion here

**Comment by nzakas** [comment]
I'd be fine with implementing a suggestion. Just so everyone is aware: suggestions have no effect on the command line, they are just displayed inside of editors like Visual Studio Code as potential fixes. If that's what you're interested in, then we can move forward.

**Comment by dbartholomae** [comment]
Is it possible to auto-fix suggestions via `eslint --fix --fix-type suggestion`? I'm looking for a way to autofix this in a large codebase, so suggestions without a way to auto fix wouldn't help me and then I would implement a [codemod](https://github.com/facebook/jscodeshift) instead.

**Comment by dbartholomae** [comment]
If there is interest in some way to auto-fix suggestions, that would also be something that I would be willing to contribute - or set up as a separate open-source repo that uses eslint machine-readable output.

**Comment by dbartholomae** [comment]
Thanks! I haven't tried it yet, but it seems that [eslint-interactive](https://github.com/mizdra/eslint-interactive) already allows to auto-fix suggestions. I'll check it, and if it works, I would love to contribute a suggestion for this rule :)

**Comment by dbartholomae** [comment]
Looks good! If you are interested, I'm happy to provide a PR on this. Thanks for all the support and the patience with my questions!

**Comment by mdjermanovic** [comment]
Yes, PR is welcome!

**Comment by dbartholomae** [comment]
I've opened #16637 to fix this.
