### ISSUE TITLE
ESLint doesn't support globbing?

### ISSUE THREAD

**Issue by briandipalma** [eslint/eslint#1663]
eslint doesn't seem able to be run on all files in a directory to any depth, is this a limitation of optionator? As it stands I'll have to add all the directories I want linted by hand to the npm script. That's a lot of directories, `**` support would be great.

**Comment by nzakas** [comment]
We don't currently support globbing, though you can do `eslint .` to run on all subdirectories. Does that do what you want?

**Comment by briandipalma** [comment]
According to [this SO issue](http://stackoverflow.com/questions/1690809/what-expands-to-all-files-in-current-directory-recursively) you need an option to be set in bash for `**` to expand all files in subdirectories. I guess that's the issue I'm having, as it stands that means I can't rely on `npm script` to run ESLint over large nested codebases. I was hoping to avoid Gulp for these sort of tasks but it looks like I'd be best using it.

Sorry about the noise of this issue, I incorrectly thought optionator expanded the arguments from npm scripts but the issue seems to be in bash. I think an option in `.eslintrc` to specify a `minimatch` glob for the files to lint would be handy though. Will I leave this open as a feature request or close it?

**Comment by nzakas** [comment]
You can use `eslint .` in the root directory of a project and it will recurse through all subdirectories for you. If that's your use case, then we've already got you covered.

I'm not sure it's worth adding globbing support to the command line. Most people use ESLint through a build system like Grunt that does its own globbing. 

Can you let me know if `eslint .` solves the problem you have?

**Comment by briandipalma** [comment]
Nope `eslint .` only lints files in the current directory. I guess it's no big deal a few Gulp tasks aren't a major issue.

**Comment by lo1tuma** [comment]
@briandipalma that’s not true, `eslint .` lints all files in the current directory AND recursively all subdirectories.

**Comment by briandipalma** [comment]
@lo1tuma I must have messed something up in my bash setup yesterday because it didn't work for me, today it does. Thanks for disagreeing with me, prompted me to test again! Hopefully Windows works the same.

**Comment by nihey** [comment]
`eslint .` lints all `.js` files recursively. But I have a project full of `.jsx` files, and my `.eslintrc` has:
```
  "ecmaFeatures": {
    "jsx": true,
  },
```
In this case, `eslint .` doesn't seem to be looking for any of the `.jsx`.

This is not a critical issue to me, as there are ways to work around it. But what do you think? Should it look for the `.jsx` files?

**Comment by ilyavolodin** [comment]
You have to tell ESLint that you want to lint `.jsx` files by specifying [`--ext` CLI option](http://eslint.org/docs/user-guide/command-line-interface#ext).

**Comment by nihey** [comment]
Nice catch, using `eslint . --ext .jsx` seems good enough.

**Comment by anodynos** [comment]
Worth noting for anyone looking that in `package.json` this solved the eslint not globbing problem in bash / linux : 
```
"scripts": {
    "lint": "eslint './src/**/*.js' './specs/**/*.js'",
 ....
  }
```
All you need is single quotes around the path eg `'./some/path/with/glob/**/*.js'`.

**Comment by platinumazure** [comment]
I think we do support globbing now, incidentally. If you want to avoid the shell expanding your globs, you can quote them with double quotes and that should do it in most shells.

**Comment by FieryCod** [comment]
Is there a way to lint files recursively on Windows like I do on Linux using `eslint .`?
