### ISSUE TITLE
Change Request: Provide a session object to parsers

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#16656]
### ESLint version

v8.29.0

### What problem do you want to solve?

Forking from https://github.com/eslint/eslint/discussions/16557#discussioncomment-4219483: custom parsers sometimes would want to make decisions based on the way ESLint is being run. For example, [`@typescript-eslint/parser`](https://typescript-eslint.io)'s [type-aware linting mode](https://typescript-eslint.io/docs/linting/typed-linting):

* Has to use not-always-correct inferences to know whether to use an _immutable_ TypeScript program (faster but can't react to file changes) or a _builder_ TypeScript program (slower but can react to file changes).
* Can't create file watchers on disk because we don't know when the lint program is done.
    * Given file A importing from file B, we can't inform file A when file B's exported types are changed. This results in frequent user pain: https://typescript-eslint.io/linting/troubleshooting#changes-to-one-file-are-not-reflected-when-linting-other-files-in-my-ide

One piece of information that would really help us out on the parser side would be to know ESLint's runtime mode:

* "One and done" runs: which can have a reusable (_immutable_ program) cache, and doesn't need to attach file watchers
* "One and done, with fixers": which have a _mostly_ reusable cache, except for file fixes, which we generally assume not to change cross-file types
* "Continuous" runs: the "wild west" (_builder_ program), and should attach file watchers

From knowing the usage mode, parsers can then make more informed decision on aspects such as file/program caching. https://github.com/typescript-eslint/typescript-eslint/pull/6178 shows an example of typescript-eslint using this information to determine whether it's in a "single run" mode _without_ `--fix`. That "single run" mode helps with performance (https://github.com/typescript-eslint/typescript-eslint/pull/3512 -> https://github.com/typescript-eslint/typescript-eslint/issues/3528) but has issues when `--fix` is enabled (https://github.com/typescript-eslint/typescript-eslint/issues/6176 -> https://github.com/typescript-eslint/typescript-eslint/issues/6184).

### What do you think is the correct solution?

I'd like to suggest we provide a `session` object to parsers that at first contains just two pieces of information:

```ts
interface LintSession {
  mode?: "persistent" | "single";
  options: ESLintOptions;
}
```

The expectation for this session object is that consumers may provide a `mode` _if_ they know it:

- [`CLIEngine`](https://eslint.org/docs/latest/developer-guide/architecture/#the-cliengine-object) would always provide `mode: 'single'`
- [`Linter`](https://eslint.org/docs/latest/developer-guide/architecture/#the-linter-object) would receive an optional mode from whoever is constructing & using it

Parsers would then receive the session in their [`parseForESLint`](https://eslint.org/docs/latest/developer-guide/working-with-custom-parsers) as a third parameter.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This feels meaty enough to become an RFC. But the RFC README.md seems to suggest posting an issue first. 🙂 

Other fields could eventually be added to session (I'd really love to have file watching handles, to make addressing the issues with watching even more straightforward to resolve). But in the hope of getting this merged in sooner, I'm leaving them out of this proposal for now.

By _✔️  I am willing to submit a pull request for this change._ I mean - I would experience _great_ personal & professional joy in implementing this. Please let me do this thing! 😁 

I'd chatted with @bradzacher and @ljharb briefly about this before filing but haven't gone through much bikeshedding on the contents or naming of that session object.

**Comment by nzakas** [comment]
You got it right, we prefer an issue be opened first so we can track the idea through inception to RFC to implementation. :+1:

Because I mentioned this on the rewrite discussion, I'm obviously in favor of this direction, but I'm not sure it makes sense to try and do this with the current ESLint. My idea was more in the realm of a complete rewrite where we'd have more API flexibility. I definitely do not want to tack this onto `parseESLint()` or anything that I hope will go away at some point in the future.

You are free to put together an RFC and change my mind, though. :smile: Sometimes the details make it clear that my assumptions are incorrect, I just wanted to be up-front with my current thinking around the idea of sessions.

**Comment by ljharb** [comment]
this has an RFC: https://github.com/eslint/rfcs/pull/102

**Comment by ljharb** [comment]
bump
