### ISSUE TITLE
Path to v1.0.0

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1666]
This is a tracking issue to make progress towards v1.0.0. These are the top things to accomplish:

1. Complete `indent` rule (#1022)
1. Add ES6 scoping (via escope, #1642)
1. See if any rules should be combined (the various strict rules, comma spacing/styling, etc.)
1. See if any rules need to change

Once v1.0.0 goes out the door, all existing rules will be locked and can't be removed or changed in a backwards-incompatible way, so those last two are very important.

**Comment by jesstelford** [comment]
> Want to back this issue? Place a bounty on it! We accept bounties via Bountysource.

Do you accept Bitcoin tips as bounties (no 10% withdraw fee)?

**Comment by nzakas** [comment]
Bounties are handled through BountySource. We accept whatever they accept.

**Comment by nzakas** [comment]
We will wait until the work on defining the ES6 AST is completed in the estree project.

**Comment by elwayman02** [comment]
What's the status of this?

**Comment by nzakas** [comment]
This issue is no longer being used (oops). Please see the 1.0.0 milestone for progress.

**Comment by jesstelford** [comment]
[Milestone 1.0.0](https://github.com/eslint/eslint/milestones/v1.0.0) (link for those who had trouble finding it like I did)
