### ISSUE TITLE
Change Request: docs: add example code for eslint.lintText

### ISSUE THREAD

**Issue by milahu** [eslint/eslint#16666]
### ESLint version

8.29.0

### What problem do you want to solve?

no example code for eslint.lintText at

https://eslint.org/docs/latest/developer-guide/nodejs-api#eslint-class

### What do you think is the correct solution?

add example code, something like

```js
const { ESLint } = require("eslint");

let text = `
console.log("hello")
`

(async function main() {
  // 1. Create an instance with the `fix` option and some config.
  const eslint = new ESLint({
    fix: true,
    useEslintrc: false,
    overrideConfig: {
      "extends": [
        "eslint:recommended",
      ],
      "parserOptions": {
        "sourceType": "module",
        "ecmaVersion": "latest",
      },
      "env": {
        "es2022": true,
      },
    },
  });

  // 2. Lint text. Store fixed text in results[0].output.
  const results = await eslint.lintText(text, {filePath: "/script.js"});

  // 3. Format the messages.
  const formatter = await eslint.loadFormatter("stylish");
  const messages = formatter.format(results);

  // 4. Print the messages.
  console.log(messages);

  // 5 Print the new text.
  const newText = results[0].output;
  console.log(newText);
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});
```

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sorry we missed this! We can definitely add an example there. Is that something you'd like to submit a pull request for?

**Comment by milahu** [comment]
> Is that something you'd like to submit a pull request for?

nope, sorry

**Comment by siva-kannan3** [comment]
@nzakas , I have created and tested a basic example. Here is the screenshot. Would love to give a PR for the same.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/60533560/210673981-f40e0d6c-1318-4ebc-b915-abf727f18d38.png">
