### ISSUE TITLE
eslint stopped working with npm scripts

### ISSUE THREAD

**Issue by habsfanongit** [eslint/eslint#16667]
Project structure

![5ueLO](https://user-images.githubusercontent.com/21362322/207930427-252b52de-9890-47ea-8bcf-27fe218f2b07.png)
### Environment

Node version: v18.12.0
npm version: v9.2.0
Local ESLint version: v8.29.0 (Currently used)
Global ESLint version: v8.29.0
Operating System: linux 5.10.102.1-microsoft-standard-WSL2

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>

<summary>Configuration</summary>

```
module.exports = {
  env: {
    browser: true,
    es2021: true
  },
  extends: "standard-with-typescript",
  overrides: [
  ],
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
    project: ["./tsconfig.json"],
    tsconfigRootDir: __dirname
  },
  ignorePatterns: ["!.*", "dist", "node_modules", "./.eslintrc.js", "./src/config/"],
  rules: {
    "@typescript-eslint/no-var-requires": 0,
    "@typescript-eslint/no-base-to-string": 0,
    "@typescript-eslint/restrict-template-expressions": 0,
    "@typescript-eslint/consistent-type-assertions": 0,
    "@typescript-eslint/strict-boolean-expressions": 0,
    "@javascript-eslint/no-path-concat": 0,
    "@typescript-eslint/semi": [2, "always"],
    "@typescript-eslint/quotes": [2, "double"],
    semi: [2, "always"],
    quotes: [2, "double", { avoidEscape: true, allowTemplateLiterals: true }]
  }
};
```

</details>

executing npm run lint doesnt report any errors but executing eslint -c ./.eslintrc.js ./src/**/*.ts directly from the terminal works as expected.

npm script
```
 "lint": "eslint -c ./.eslintrc.js ./src/**/*.ts",
```
</details>

```js
import express from "express"
```
based on the .eslintrc.js configurations, linting should fail due to lack of required semi

### What did you expect to happen?

Running npm run lint should run eslint using the specified configuration.

### What actually happened?

No errors reported while running npm run lint but running globally installed eslint seems to work as expected.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @habsfanongit, thanks for the issue!

Can you try with quotes around the glob? That would make sure that the glob is passed directly to ESLint, not expanded by your shell.

```diff
- "lint": "eslint -c ./.eslintrc.js ./src/**/*.ts",
+ "lint": "eslint -c ./.eslintrc.js \"./src/**/*.ts\"",
```

**Comment by habsfanongit** [comment]
@mdjermanovic,  thank you. that resolved it for me.
