### ISSUE TITLE
Bug: `key-spacing` change has broken alignment of single-line and multi-line keys when mixed

### ISSUE THREAD

**Issue by pdl** [eslint/eslint#16674]
### Environment

Node version: v16.13.2
npm version: v8.3.2
Local ESLint version: Not found
Global ESLint version: Not found
Operating System: linux 4.15.0-194-generic

NB: `$ yarn -s eslint --version` returns `v8.29.0`.

### What parser are you using?

(Initially noticed with an environment which I think uses) vue-eslint-parser (but reproduced as below).

### What did you do?

In ESLint demo, paste the following, or use [this link](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IGtleS1zcGFjaW5nOiBbIFwiZXJyb3JcIiwge1wic2luZ2xlTGluZVwiIDogeyBcImJlZm9yZUNvbG9uXCI6IGZhbHNlLCBcImFmdGVyQ29sb25cIjogdHJ1ZSB9LCBcIm11bHRpTGluZVwiIDogeyBcImJlZm9yZUNvbG9uXCI6IGZhbHNlLCBcImFmdGVyQ29sb25cIjogdHJ1ZSB9LCBcImFsaWduXCIgOiB7IFwiYmVmb3JlQ29sb25cIjogdHJ1ZSwgXCJhZnRlckNvbG9uXCI6IHRydWUsIFwib25cIjogXCJjb2xvblwiIH0gfV0gKi9cblxuLy8gSSB1c2UgdGhlIHJ1bGVzIGFib3ZlIHRvIGxpbmUgdXAgbXkgY29sb25zXG5cbi8vIExpbmluZyB0aGVzZSB1cCB1c2VkIHRvIGJlIG9rXG5jb25zdCBhID0ge1xuICBpdGVtICAgICAgIDogMTIzLFxuICBsb25nZXJJdGVtIDogKFxuICAgIDEgKyAxXG4gICksXG59O1xuXG4vLyBUaGlzIGlzIHN0aWxsIGZpbmVcbmNvbnN0IGIgPSB7XG4gIGl0ZW0gICAgICAgOiAxMjMsXG4gIGxvbmdlckl0ZW0gOiA0NTYsXG59O1xuXG4vLyBObywgSSBzcGVjaWZpY2FsbHkgZG9uJ3Qgd2FudCB0aGlzIHN0eWxlLCBpdCB1c2VkIHRvIGJlIGFuIGVycm9yLCBJIHdhbnQgbXkgY29sb25zIHRvIGFsaWduXG5jb25zdCBjID0ge1xuICBpdGVtOiAxMjMsXG4gIGxvbmdlckl0ZW06IChcbiAgICAxICsgMVxuICApLFxufTtcblxuLy8gdGhlc2UgbGluZXMganVzdCB0byBnZXQgcmlkIG9mIG91dHB1dCBhYm91dCBhLCBiLCBjIGJlaW5nIHVudXNlZFxuYS5pdGVtKys7XG5iLml0ZW0rKztcbmMuaXRlbSsrOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbImVycm9yIl0sIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1lbXB0eS1wYXR0ZXJuIjpbImVycm9yIl0sIm5vLWV4LWFzc2lnbiI6WyJlcnJvciJdLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOlsiZXJyb3IiXSwibm8tZXh0cmEtc2VtaSI6WyJlcnJvciJdLCJuby1mYWxsdGhyb3VnaCI6WyJlcnJvciJdLCJuby1mdW5jLWFzc2lnbiI6WyJlcnJvciJdLCJuby1nbG9iYWwtYXNzaWduIjpbImVycm9yIl0sIm5vLWltcG9ydC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW5uZXItZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWludmFsaWQtcmVnZXhwIjpbImVycm9yIl0sIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjpbImVycm9yIl0sIm5vLWxvc3Mtb2YtcHJlY2lzaW9uIjpbImVycm9yIl0sIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6WyJlcnJvciJdLCJuby1uZXctc3ltYm9sIjpbImVycm9yIl0sIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjpbImVycm9yIl0sIm5vLW9iai1jYWxscyI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOlsiZXJyb3IiXSwibm8tcmVkZWNsYXJlIjpbImVycm9yIl0sIm5vLXJlZ2V4LXNwYWNlcyI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOlsiZXJyb3IiXSwibm8tdW5kZWYiOlsiZXJyb3IiXSwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOlsiZXJyb3IiXSwibm8tdW5yZWFjaGFibGUiOlsiZXJyb3IiXSwibm8tdW5zYWZlLWZpbmFsbHkiOlsiZXJyb3IiXSwibm8tdW5zYWZlLW5lZ2F0aW9uIjpbImVycm9yIl0sIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6WyJlcnJvciJdLCJuby11bnVzZWQtbGFiZWxzIjpbImVycm9yIl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtYmFja3JlZmVyZW5jZSI6WyJlcnJvciJdLCJuby11c2VsZXNzLWNhdGNoIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtZXNjYXBlIjpbImVycm9yIl0sIm5vLXdpdGgiOlsiZXJyb3IiXSwicmVxdWlyZS15aWVsZCI6WyJlcnJvciJdLCJ1c2UtaXNuYW4iOlsiZXJyb3IiXSwidmFsaWQtdHlwZW9mIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19):

```js
/* eslint key-spacing: [ "error", {"singleLine" : { "beforeColon": false, "afterColon": true }, "multiLine" : { "beforeColon": false, "afterColon": true }, "align" : { "beforeColon": true, "afterColon": true, "on": "colon" } }] */

// I use the rules above to line up my colons

// Lining these up used to be ok
const a = {
  item       : 123,
  longerItem : (
    1 + 1
  ),
};

// This is still fine
const b = {
  item       : 123,
  longerItem : 456,
};

// No, I specifically don't want this style, it used to be an error, I want my colons to align
const c = {
  item: 123,
  longerItem: (
    1 + 1
  ),
};

// these lines just to get rid of output about a, b, c being unused
a.item++;
b.item++;
c.item++;
```

### What did you expect to happen?

The first two `const` assignments to `a` and `b` should have no error and `c` should raise an error, fixable to become like `a`.

### What actually happened?

Errors are reported in case `a`, not `c`. ESLint will attempt to 'correct' to `c`.

```
Error
7:7
Extra space after key 'item'.  ([key-spacing](https://eslint.org/docs/rules/key-spacing))

Error
8:13
Extra space after key 'longerItem'.  ([key-spacing](https://eslint.org/docs/rules/key-spacing))
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I assume it was broken by #16532.

**Comment by pdl** [comment]
@fasttime could you confirm whether this was an intentional outcome of your change?

**Comment by mdjermanovic** [comment]
Looks like a bug to me. Marked accepted.

> ```js
> // No, I specifically don't want this style, it used to be an error, I want my colons to align
> const c = {
>   item: 123,
>   longerItem: (
>     1 + 1
>   ),
> };
> ```

This is because the parentheses are not considered to be part of `Property#value`, so it starts on a separate line.  We can fix this by getting the first token after `:` and then using its line instead of the property value's line.

**Comment by mdjermanovic** [comment]
PR is welcome!
