### ISSUE TITLE
Change Request: Rename internal CLIEngine to ESLintEngine or similar?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#16670]
### ESLint version

8.29.0

### What problem do you want to solve?

[As of 8.0.0, `CLIEngine` is no longer exposed to users](https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#remove-cliengine). It -and its name- are now an internal-only implementation detail.

The name is a bit misleading, though: `CLIEngine` isn't necessarily run by the CLI! It's created by the `ESLint` class...

https://github.com/eslint/eslint/blob/173e82040895ad53b2d9940bfb3fb67a0478f00b/lib/eslint/eslint.js#L430

...which is the primary class suggested by the [Node.js API](https://eslint.org/docs/latest/developer-guide/nodejs-api#eslint-class).

### What do you think is the correct solution?

How about... `ESLintEngine`? 

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This isn't the most critical issue, but the naming of `CLIEngine` confuses me every time I write an RFC for ESLint (https://github.com/eslint/rfcs/pull/78, https://github.com/eslint/eslint/issues/16656). I imagine it might confuse other occasional contributors as well.

**Comment by mdjermanovic** [comment]
The `CLIEngine` class will be removed so I think it's not worth renaming it now. Using `CLIEngine` from the `ESLint` class was just an intermediate step, the plan was to implement all functionalities directly in the `ESLint` class. The plan has changed a bit since we started working on `FlatESLint` which will become `ESLint` in a future major version, and at that point we'll remove `CLIEngine`.

**Comment by JoshuaKGoldberg** [comment]
> future major version

Are there any timelines around 9.0 or later? Understanding this is all temporary, my perspective is that it would still be beneficial to do this refactoring in the meantime. But if you close this issue I won't complain. 😄

**Comment by nzakas** [comment]
ESLint v9 will come out sometime in 2023. The timing is TBD and depends largely on development of flat config.

It doesn't make sense to start renaming classes that will be deprecated and removed at this point -- that's just change for change's sake and given all the other changes around these classes I don't think there's much value to be had.

FWIW, in the rewrite, we'll have all new classes with names that actually make sense. :)
