### ISSUE TITLE
Add widely used Preset configurations

### ISSUE THREAD

**Issue by jesstelford** [eslint/eslint#1669]
Similar to [jscs' Presets](https://github.com/jscs-dev/node-jscs/tree/master/presets), it would be useful for new users to get started quickly on a project if they can copy+paste a Preset.

This is particularly useful for new devs joining an existing team which has existing rules to follow, allowing them to pick their linting tool (eslint of course) and still be in line with everyone else's code quality.

**Comment by nzakas** [comment]
I'm weary about getting into this game. Shipping with presets immediately puts us into debates over what is widely used and what is not. I'd rather rely on the community to create and share configs instead of bundling them.

**Comment by jesstelford** [comment]
Fair point. Would it be worthwhile setting up a sister-repo or a wiki page for folks to share on?

As an example, here's a rudimentary [AirBnB Javascript styleguide](https://github.com/airbnb/javascript) implementation for ESLint:

```json
{
	"env": {
		"node": true
	},
	"rules": {
		"no-new-object": 1,
		"no-reserved-keys": 1,
		"no-array-constructor": 1,
		"quotes": [1, "single"],
		"max-len": [1, 80, 2], // 2 spaces per tab, max 80 chars per line
		"no-inner-declarations": [1, "both"],
		"no-shadow-restricted-names": 1,
		"one-var": 0,
		"vars-on-top": 1,
		"eqeqeq": 1,
		"curly": [1, "multi"],
		"no-mixed-spaces-and-tabs": 1,
		"space-before-blocks": [1, "always"],
		"space-infix-ops": 1,
		"eol-last": 1,
		"comma-style": [1, "last"],
		"no-comma-dangle": 1,
		"semi": [1, "always"],
		"radix": 1,
		"camelcase": 1,
		"new-cap": 1,
		"consistent-this": [1, "_this"],
		"func-names": 1
	}
}
```

**Comment by Dashed** [comment]
Maybe a `recipes` (or similar) folder under `docs` folder?

**Comment by nzakas** [comment]
I don't want to manage these configs in the repo. We have an integrations page where we list links to other projects, I'd just add a section for configs there and link out to other repos.

**Comment by nzakas** [comment]
We do have an integrations page on the site: http://eslint.org/docs/integrations/

I'd suggest starting a presets section and then anyone can link to their presets.

**Comment by mansona** [comment]
Hey Folks, 

I think this has suddenly become more important because of the deprecation of JSCS which encouraged the use of presets. Is there any possibility of re-opening this and seeing if we can start a discussion of the best way forward? 

Cheers, 
- Chris

**Comment by ilyavolodin** [comment]
@mansona We have sharable configs in ESLint that work the same way as presets. Search npm for `eslint-config-` and you will see a lot of them.

**Comment by kevinSuttle** [comment]
100% serious: there's an easy way to find out what the most commonly used are now. 
https://twitter.com/fatih/status/758355980442828800
https://cloud.google.com/bigquery/public-data/github

**Comment by Ivanca** [comment]
@nzakas link is broken, now it is: http://eslint.org/docs/user-guide/integrations
