### ISSUE TITLE
Change Request: Add rule performance dashboard

### ISSUE THREAD

**Issue by mnkiefer** [eslint/eslint#16690]
### ESLint version

v8.12.0

### What problem do you want to solve?

Analysing rule performance currently requires additional scripting to collect/extract more *granular* timing data (lint time per file per rule):

1. Running ESLint per rule, per file and then collecting the file/rule time data output:

  ```bash
  TIMING=1 DEBUG=eslint:cli-engine eslint --no-eslintrc --rule ... file
  ```

2. Doing a single ESLint run on all files and then extracting the file/rule time data output:

  ```bash
  TIMING=ALL DEBUG=eslint:cli-engine eslint ... files
  ```

In addition, one needs to create an overview for an effective presentation of the results.

### What do you think is the correct solution?

It would be more *convenient and shareable* to have: 

   1. the **timing data exposed** to the formatters (when `TIMING` is used)
   2. a **built-in formatter** for that data [optional]

To demonstrate this, here is a sample implementation where (1) ESLint added the timing data (`lintOrder`, `lintTime`, `lintTimePerRule` to the `LintResult` object) and (2) the formatter `html-charts` has been applied, which embeds the already established `html` formatter into a dashboard along with two charts on rule performance:

<img width="1401" alt="timing" src="https://user-images.githubusercontent.com/8320933/209118876-c1d3f20c-9132-417b-b3ca-64e68758c701.png">

* The overview shows the overall rule performance per run (i.e. the `TIMING` output), as well as the individual lint time per file per rule (from the exposed timing), which can help to detect more intricate performance issues that may be overlooked otherwise (based on rule reports only). The analysis has been carried out on a set of 28 `*.js` files containing valid/invalid [recommended rules](https://eslint.org/docs/latest/rules/) examples provided by ESLint.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. We do already have an issue open to expose timing data via the ESLint API:
https://github.com/eslint/eslint/issues/16521

We could probably expand that proposal to include timing data being passed to formatters.

In general we've been trying to avoid adding new formatters to the core, but this one is specialized enough that it might make sense.

We would need an RFC to move forward with this, and some feedback from the rest of the team would be appreciated.

**Comment by bmish** [comment]
Another related issue is https://github.com/eslint/eslint/issues/14597#issuecomment-1003863524 where I was imagining a way to output various rule metrics (violations, disable directives, performance stats, etc). So perhaps any solution should be more general than just performance data only.

**Comment by mnkiefer** [comment]
@nzakas: I would love to contribute, please let me know how I can help to move this forward.

**Comment by nzakas** [comment]
@mnkiefer as noted in my previous comment, the next step would be to create an RFC explaining how this feature would work.

**Comment by nzakas** [comment]
We have an RFC opened for this, so we'll leave this issue open.

**Comment by mnkiefer** [comment]
@nzakas: With the [RFC merged](https://github.com/eslint/rfcs/pull/108) and [**ESLint v9.0.0 alpha** coming soon](https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/#when-to-expect-eslint-v9.0.0), would this be a good time to introduce this feature? If so, I would love to help/contribute here too. 👍

**Comment by bmish** [comment]
Since it's not a breaking change, either before or after could work. But note that we have a lot of breaking change PRs for ESLint v9 open right now which may cause more merge conflicts than usual.

**Comment by nzakas** [comment]
It would probably be best to hold off until after we've shipped the first alpha of v9.0.0, which will have most of the huge breaking changes. Hopefully that will be before the end of December.

**Comment by bmish** [comment]
That's fair. Perhaps re-target the PR to the main ESLint repo to start getting reviewers so that it will be lined up for then?

**Comment by mnkiefer** [comment]
> That's fair. Perhaps re-target the PR to the main ESLint repo to start getting reviewers so that it will be lined up for then?

Ok, I've re-targeted the PR [here](https://github.com/eslint/eslint/pull/17850) 👍

**Comment by nzakas** [comment]
https://github.com/eslint/eslint/pull/17850 actually completed the work for this issue, so closing.
