### ISSUE TITLE
Docs: escape key would focus input

### ISSUE THREAD

**Issue by chenxsan** [eslint/eslint#16699]
### Environment

N/A

### What parser are you using?

Other

### What did you do?

I just happened to press the `ESC` key by incident when browsing docs page https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new#configuring-shared-settings, and found it would scroll page to top and focus the search box. Which doesn't seem to be intentional.

Another problem is when you're focused in the search box, pressing `ESC` won't blur the focus from search box.

### What did you expect to happen?

1. When you browse web page, pressing `ESC` should do nothing when no input was focus
2. When you press `ESC` within search box, the search box should lose focus

### What actually happened?

See what did you do part.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Just curious, why not make use of [DocSearch](https://docsearch.algolia.com/docs/DocSearch-v3) library for the docs site? It already handled all those cases for us, and we can customize styles when needed.

**Comment by shanpriyan** [comment]
The issue is reproducible, I would like to take this up.

**Comment by harish-sethuraman** [comment]
> Another problem is when you're focused in the search box, pressing ESC won't blur the focus from search box.

I guess this is expected right? I see the same behaviour with reactjs.org docs, webpack docs?

**Comment by chenxsan** [comment]
> > Another problem is when you're focused in the search box, pressing ESC won't blur the focus from search box.
> 
> I guess this is expected right? I see the same behaviour with reactjs.org docs, webpack docs?

Not same with webpack doc as far as I know. If you can't blur the search box with `esc` on webpack doc, you might have some browser extensions intervening. Try inPrivate mode without any extensions.
