### ISSUE TITLE
Change Request: Replace and discourage use of JSON schema oneOf

### ISSUE THREAD

**Issue by remcohaszing** [eslint/eslint#16691]
### ESLint version

v8.29.0

### What problem do you want to solve?

The `oneOf` property in JSON schemas can cause performance issues. It needs to validate a value against multiple sub schemas in the `oneOf` array, often all of them. Then it makes sure that exactly one of those matches.

For example, given the following schema:

```json
{
  "oneOf": [
    { "type": "number" },
    { "type": "string" },
    { "type": "object" },
  ]
}
```

and the following value:

```js
42
```

- The validator first checks if it’s a number. It is, so now there is one match.
- The validator next checks if it’s a string. It is, so now there is still one match.
- The validator next checks if it’s an object. It is, so now there is still one match.

At this point there is only one match, so the value is valid.

This is a simple example, as are most use cases, but it adds up. With complex / nested schemas this issue can grow exponentially.

### What do you think is the correct solution?

Legitimate use cases of `oneOf` are rare. As far as I recall, I haven’t encountered one yet. Most of the times, the author intended to use `anyOf`.

With `anyOf`, the validator can return if a single match is found. Think of it as `array.some(fn)` instead of `array.filter(fn).length === 1`

This applies to all ESLint rules in the ecosystem. So I suggest to also discourage usage in the documentation.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I managed to reduce validation time from minutes to milliseconds in an unrelated project by replacing `oneOf` with `anyOf`.

**Comment by mdjermanovic** [comment]
> So I suggest to also discourage usage in the documentation.

Makes sense to me. That would be a note in the [Options Schemas](https://eslint.org/docs/latest/developer-guide/working-with-rules#options-schemas) section?

**Comment by ljharb** [comment]
(i think you mean `array.filter(fn).length === 1`)

**Comment by remcohaszing** [comment]
Yes, that's the section I had in mind.

**Comment by mdjermanovic** [comment]
Accepted, PR is welcome!

**Comment by bmish** [comment]
Can I ask how this results in a "minutes to milliseconds" difference in running time? It doesn't seem like validating a few extra objects for a rule's config should cause a difference of minutes, when even running hundreds of rules on a large codebase rarely takes more than a few minutes.

`oneOf` can be useful when there are multiple formats for providing a configuration to a rule but the rule only wants to allow the user to use one of them at a time. Sometimes, the reason there are multiple formats is for backwards compatible, i.e. supporting both an old format and a new format.

I see popular ESLint plugins using it including:

* eslint-plugin-import
* eslint-plugin-jest
* eslint-plugin-jsx-a11y
* eslint-plugin-mocha
* eslint-plugin-react
* eslint-plugin-unicorn
* eslint-plugin-vue
* and many others

And the suggested change from `oneOf` to `anyOf` reduces the completeness/accuracy of a schema, and I'm not a fan of encouraging reduced completeness in schemas, especially when the performance difference for most should be negligible.

Furthermore, I'm not sure ESLint wants to be in the business of telling rule authors how to optimize every little part of their schemas...

That said, a more general feature related to this that I would love to see is an automated warning when a rule takes abnormally long to run that that could trigger when running rule tests.

**Comment by ljharb** [comment]
@bmish eslint-plugin-react and eslint-plugin-import will no longer be using it in the next versions, since there wasn't any semantic reason to do so. eslint-plugin-jsx-a11y uses it in one place, where it's still appropriate to use it - where it's describing all potential object properties versus describing a single object property (where oneOf is useless vs anyOf).

**Comment by remcohaszing** [comment]
> Can I ask how this results in a "minutes to milliseconds" difference in running time? It doesn't seem like validating a few extra objects for a rule's config should cause a difference of minutes, when even running hundreds of rules on a large codebase rarely takes more than a few minutes.

This was about JSON schema validation in an unrelated project. It was validation for a resource against a JSON schema in an OpenAPI document which looks something like this:

```json
{
  "components": {
    "schemas": {
      "Literal": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "value": "string"
        }
      },
      "Parent": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "children": {
            "$ref": "$/components/schemas/Node"
          }
        }
      },
      "Node": {
        "oneOf": [
          { "$ref": "#/components/schemas/Literal" },
          { "$ref": "#/components/schemas/Parent" },
        ]
      }
    }
  }
}
```

Now imagine an object like this:

```json
{
  "children: [
    { "value": "bar" },
    {
      "children": [
        { "value": "foo" }
      ]
    }
  ]
}
```

Now this becomed significantly worse if for example the `"Parent"` and `"Literal"` would get a `"type"` property, and would be split into more specific schemas that may have different properties. The `oneOf` array could quickly grow into over 10 entries. At which point you’ll notice a significant slowdown.

I think the impact in ESLint is minimal, but it’s still a small performance win. I believe it’s mostly important to teach JSON schema authors to prefer `anyOf` over `oneOf` in general.

**Comment by bmish** [comment]
Thank you for clarifying.

It sounds like the "minutes to milliseconds" benchmark is not relevant to ESLint then.

My position remains that we should prefer schema correctness/completeness, leaving it up to rule authors to choose what is semantically correct for their rules, and that we should **not** make recommendations in ESLint guidelines nor make changes to ESLint core rule schemas based on a negligible performance impact or edge case.

So I am opposed to this change.

**Comment by remcohaszing** [comment]
> And the suggested change from `oneOf` to `anyOf` reduces the completeness/accuracy of a schema, and I'm not a fan of encouraging reduced completeness in schemas, especially when the performance difference for most should be negligible.

I don’t understand how this means reduced completeness.

The following schema means a value may be a boolean, a number, or a string

```json
{
  "anyOf": [
    { "type": "boolean" },
    { "type": "number" },
    { "type": "string" }
  ]
}
```

The following schema also means a value may be a boolean, a number, or a string, but it may also explicitly not be more than one of those types at the same time.

```json
{
  "oneOf": [
    { "type": "boolean" },
    { "type": "number" },
    { "type": "string" }
  ]
}
```

**Comment by remcohaszing** [comment]
> leaving it up to rule authors to choose what is semantically correct for their rules, and that we should **not** make recommendations in ESLint guidelines nor make changes to ESLint core rule schemas based on a negligible performance impact or edge case.

I could see that maybe the ESLint documentation is not the place to document this, but the JSON schema website that’s already linked.

**Comment by bmish** [comment]
Switching from "oneOf" to "anyOf" can result in a "less complete" schema because it might not fully capture the constraints or requirements anymore. Only allowing "one of" a set of options is a valid constraint that a rule author or anyone writing a JSON schema may want to enforce.

One of my primary goals when using JSON schema is to enforce as many constraints as possible to ensure users provide valid data, and to do as much validation as possible with the schema itself so I don't have to write custom code to do the validation.

**Comment by ljharb** [comment]
@bmish it's not a valid constraint on a single object property tho, because that constraint is already implicit and unavoidable.

**Comment by mdjermanovic** [comment]
Removing "accepted" as it seems that we don't have a consensus on this change.

**Comment by mdjermanovic** [comment]
In my opinion, when the schemas are already disjunctive (i.e., any input cannot possibly match multiple schemas), there's no reason to use `oneOf` as it's redundant and just enforces the validator to test the input against all schemas.

**Comment by bmish** [comment]
That's fair, although I do think a user might still choose `oneOf` if it makes their intent clearer, even if there's no functional difference.

**Comment by remcohaszing** [comment]
I don’t think either `oneOf` or `anyOf` is more clear on intent. Also both fully capture the constraints and requirements equally. I think the main opposing argument is a change of habit.

The term `oneOf` is a bit ambiguous when translated to plain English. It’s better described as _“exactly one of”_.

The only case where `anyOf` and `oneOf` make a difference, is when there is an overlap between sub schemas.

For example, the following schema matches only decimal numbers. If `anyOf` was used, all numbers would be allowed.

```json
{
  "oneOf": [
    { "type": "integer" },
    { "type": "number" }
  ]
}
```

The following schema allows an object with the one of properties `a` or `c`, with an additional property `b`, but not an object with only property `b` or an empty object.

```json
{
  "oneOf": [
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "a": {},
        "b": {}
      }
    }
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "b": {},
        "c": {}
      }
    },
  ]
}
```

I was also thinking about similarities to TypeScript types. TypeScript unions are equivalent to JSON schema `anyOf`. TypeScript does not have anything comparable to `oneOf`.

> Regardless, not sure ESLint should be in the business of teaching users how to optimize their schemas.

I agree with this now.

**Comment by mdjermanovic** [comment]
> That's fair, although I do think a user might still choose `oneOf` if it makes their intent clearer, even if there's no functional difference.

I consider `anyOf` as the default choice when multiple schemas are needed, and `oneOf` as a rarely needed additional constraint that implies that the schemas do overlap and that there's a specific reason why input must not match more than one, so for me personally the intent is clearer with `anyOf` when there's no functional difference between `anyOf` and `oneOf`.

I'd also argue that ESLint should provide notes about performance where it seems critical because, from the perspective of consumers (rule authors), ESLint processes schemas and performs validations. 

Either way, since there seems to be a consensus around the opinion that in this case the performance impact is negligible, it looks like we can close this issue and the PR https://github.com/eslint/eslint/pull/16692?

**Comment by nzakas** [comment]
I’m not sure how deep we want to get into prescribing schemas for rules. I think that should be left to JSON schema documentation mostly.

However, if we are going to claim that there is a nontrivial performance difference *for ESLint*, then I’d prefer to see some benchmarks before we make a final decision. I’m not interested in performance issues in theory, I want to see them in practice.

Has anyone benchmarked ESLint rule schemas in this way?
