### ISSUE TITLE
Change Request: Replace search.js function with DocSearch library

### ISSUE THREAD

**Issue by chenxsan** [eslint/eslint#16703]
### ESLint version

N/A

### What problem do you want to solve?

I just caught [two bugs](https://github.com/eslint/eslint/issues/16699) in the search box, then I was wondering why ESLint site would use a handcrafted search box instead of the one [DocSearch](https://docsearch.algolia.com/docs/DocSearch-v3) library provides which is used by a lot of open-source documentation sites like webpack, vue, etc.

The code would be much simpler in `search.js` then, e.g.,

```
docsearch({
    container: '.search__input-wrapper',
    appId: 'L633P0C2IR',
    indexName: 'eslint',
    apiKey: 'bb6bbd2940351f3afc18844a6b06a6e8',
})
```
We can eliminate almost all other code in [`search.js`](https://github.com/eslint/eslint/blob/main/docs/src/assets/js/search.js).

Less maintenance cost in the long term, and better accessibility like the shortcut indicator (current no one can tell from the page that you can use ctrl+k), and of course it's easy to customize the styles so the search box would look almost same as before:

<img width="444" alt="" src="https://user-images.githubusercontent.com/1091472/209458552-c7109b71-65ee-429f-a831-1231d5d0d1df.png">

The only difference is how to represent the search result, here's how DocSearch shows them:

<img width="726" alt="" src="https://user-images.githubusercontent.com/1091472/209458680-4e741b70-811a-421d-88f8-78a100f03eb1.png">

Which looks pretty good to me :)

### What do you think is the correct solution?

Replace the handcrafted search box with DocSearch library.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I've drafted a branch locally though it's for demonstration purpose only, let me know if you want to take a look at the preview.

**Comment by amareshsm** [comment]
I'm ok with this change.

**Comment by harish-sethuraman** [comment]
@eslint/eslint-tsc thoughts?

**Comment by kecrily** [comment]
We seem to have technical sponsorship from Algolia, but don't know why we don't use it? Was it used on the old site and is no longer used on the new site?

**Comment by nzakas** [comment]
We didn’t like the UI for DocSearch. It doesn’t fit in with the rest of the site and it’s very difficult to use with screen readers and keyboards. I’d much rather fix the bugs in our own search than use DocSearch.

**Comment by chenxsan** [comment]
> We didn’t like the UI for DocSearch. It doesn’t fit in with the rest of the site and it’s very difficult to use with screen readers and keyboards. I’d much rather fix the bugs in our own search than use DocSearch.

Yeah, I was wondering it could be of the UI concern for not using it.

Regarding `it’s very difficult to use with screen readers and keyboards.`, I'm not familiar with screen readers (I'll see how to test), but DocSearch has pretty good keyboards support as far as I know:

![](https://user-images.githubusercontent.com/1091472/209590368-1861abf1-8777-4e29-91d4-753670f13da5.png)

You can try it on https://deploy-preview-16714--docs-eslint.netlify.app/.

Any way, feel free to close this issue if you still feel the same after trying the demo.

**Comment by chenxsan** [comment]
All right, seems I misunderstood it when you said `it’s very difficult to use with screen readers and keyboards`. That `keyboards` here would mean keyboards used by screen readers' users.

It's my first time testing on a screen reader, I have to say, really impressive by ESLint's own search :)

Although I'm not a real screen reader user here, but DocSearch has pretty good support as well for screen readers and keyboards in my test using [VoiceOver on mac](https://support.apple.com/zh-cn/guide/voiceover/welcome/mac), though I did find some other accessibility problems which I'll file over their repository.

I'm closing this now, but feel free to ping me if you change your mind.
