### ISSUE TITLE
rule suggestion: space-after-semi

### ISSUE THREAD

**Issue by remitbri** [eslint/eslint#1671]
What about a rule for enforcing (or not) a space after a semicolon, as long as it's not at the end of a line? Just to separate blocks, as in 

```js
for (i = 0; i < l; i++) {
  x++;
}
foo++; bar = some_function(baz);
```

instead of 

```js
for (i = 0;i < l;i++) {
  x++;
}
foo++;bar = some_function(baz);
```

**Comment by nzakas** [comment]
I'm open to it, patches welcome.

**Comment by doberkofler** [comment]
+1

**Comment by lo1tuma** [comment]
Maybe we can combine this with `no-space-before-semi` and call it `semi-spacing` similar to `comma-spacing`.

**Comment by lo1tuma** [comment]
I wonder if this rule should also apply for the following example:

```js
var logFoo = function(){console.log("foo");};
```

**Comment by nzakas** [comment]
Yeah, this one is a bit trickier than it seems on the surface. I think the primary use case is in a `for` loop, but maybe there are others?

**Comment by lo1tuma** [comment]
There are other examples from @remitbri in the issue description (e. g.  `a = b;c = d;`).
Personally I think we should enforce it everywhere.

What do you think about combining this rule with `no-space-before-semi`?

**Comment by nzakas** [comment]
I was just about to say I'd like to see a proposal regarding how that would work, but I see you submitted a PR. :)

So the `after` option would apply only if the semicolon is not at the end of line?

**Comment by lo1tuma** [comment]
@nzakas exactly, see [76046c88dd](https://github.com/eslint/eslint/blob/76046c88ddea9a7c411b241462d4267770c53c51/lib/rules/semi-spacing.js#L110). That was even requested in the issue description.
