### ISSUE TITLE
Bug: syntax error in `prefer-arrow-callback` autofix

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#16718]
### Environment

Node version: v19.3.0
npm version: v9.2.0
Local ESLint version: v8.30.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.1.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parserOptions": {
        "ecmaVersion": "latest"
    },
    "rules": {
        "prefer-arrow-callback": [
            "error"
        ]
    }
}
```
</details>

```js
test(
  function ()
  { }
);
```

### What did you expect to happen?

Autofix should fix the code like this:

```js
test(
  () =>
  { }
);
```

### What actually happened?

Autofix produces unparseable code:

```js
test(
  ()
  => { }
);
```

[**DEMO LINK**](https://eslint.org/play/#eyJ0ZXh0IjoidGVzdChcbiAgZnVuY3Rpb24gKClcbiAgeyB9XG4pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsicHJlZmVyLWFycm93LWNhbGxiYWNrIjpbImVycm9yIl19LCJlbnYiOnt9fX0=)

The problem occurs when the function body starts on a new line, like in the Allman style.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Accepted, PR is welcome!

**Comment by fasttime** [comment]
Thanks for accepting this, @mdjermanovic. I'll work on a fix.
