### ISSUE TITLE
Bug: suggestions are broken on processored code if `suggest` array contain more that 2 items

### ISSUE THREAD

**Issue by B2o5T** [eslint/eslint#16716]
### Environment

Node version: 16.18.1
npm version: 
Local ESLint version: 8.30.0
Global ESLint version: 
Operating System: 

### What parser are you using?

Other

### What did you do?

`suggest` array contains 2 items

https://user-images.githubusercontent.com/7361780/209718712-417b52b5-5e16-402b-a133-c9a151a75d4f.mov

`suggest` array contains 1 item

https://user-images.githubusercontent.com/7361780/209718742-5104ae35-8d33-4634-a53f-f66ebef8cd27.mov

This behaviour only happens on processed code (in my case `*.js/*.ts` since I'm the maintainer of [`graphql-eslint`](https://github.com/B2o5T/graphql-eslint) package.
There is no this problem when I apply suggestions on `*.graphql` files directly

I verified another rule that does not do `fixer.replaceText` but `fixer.remove` and received exact same behaviour, suggestions are broken if I add 2nd item.

### What did you expect to happen?

should not break code if there are more than 2 items in suggest array on processed code

### What actually happened?

Suggestions works on `*.js` files only if there is 1 item in the `suggest` array
Suggestions works well on `*.graphql` files if there are 2 items in suggest

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by B2o5T** [comment]
after debugging I found that this happens due to mutating `message.suggestions[i].range` array items in `processor.postprocess()` method

https://github.com/B2o5T/graphql-eslint/blob/1883cc4af49370b4778a158290fcd3763a5d8d41/packages/plugin/src/processor.ts#L107-L110

Anyway I think this should be fixed inside ESLint to avoid confusing different behaviour of mutation 1 suggestion vs multiple suggestions

**Comment by mdjermanovic** [comment]
Hi @B2o5T, thanks for the issue!

To clarify, the problem is that multiple suggestions can have the same instance of array as `fix.range`, and you're suggesting that ESLint makes sure that each `fix.range` is a separate instance?

**Comment by B2o5T** [comment]
Exactly

**Comment by mdjermanovic** [comment]
I think we can update [`report-translator`](https://github.com/eslint/eslint/blob/main/lib/linter/report-translator.js) to always create a new [`EditInfo`](https://eslint.org/docs/latest/developer-guide/nodejs-api#-editinfo-type) object with a new `range` array, in order to make sure that each `fix` and each `fix.range` are separate instances. Let's hear the opinions of other team members about this change.

**Comment by Rec0iL99** [comment]
Waiting for feedback from @eslint/eslint-team. Don't close.

**Comment by B2o5T** [comment]
@nzakas Thanks! I'll do my first contribution once I'll have some time 😉

**Comment by nzakas** [comment]
@B2o5T thanks! Let us know if you have any questions.

**Comment by mdjermanovic** [comment]
@B2o5T are you still working on this? If not, I could take it.

**Comment by B2o5T** [comment]
@mdjermanovic feel free
