### ISSUE TITLE
Change Request: add ability to shard eslint

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#16726]
### ESLint version

Feature suggestion.

### What problem do you want to solve?

Speed up ESLint execution by splitting the workload across multiple CPUs or multiple machines using sharding.

### What do you think is the correct solution?

Copy the existing sharding behavior of libraries such as:

* Jest [`--shard <workerIndex>/<workerCount>`](https://jestjs.io/docs/next/cli#--shard)
* Vitest [`--shard <workerIndex>/<workerCount>`](https://vitest.dev/guide/cli.html)
* Playwright [`--shard <workerIndex>/<workerCount>`](https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines)

Basic principle of sharding: divide all matching files by the number of `workerCount` and only run linting against the files in the matching `workerIndex`.

Example:

Assuming these files

```
a.js
b.js
c.js
d.js
e.js
f.js
```

Then:

* `eslint --shard 1/3` would only lint `a.js` and `b.js`
* `eslint --shard 2/3` would only lint `c.js` and `d.js`
* `eslint --shard 3/3` would only lint `e.js` and `f.js`

This enables splitting ESLint workload either across multiple CPUs or multiple machines.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by gajus** [comment]
Surprised I don't see prior discussion around this. Sorry if it was discussed using another term.

**Comment by fasttime** [comment]
There is a similar issue: #3565

**Comment by gajus** [comment]
I am aware of that proposal. However, adding a `--shard` option is a lot simpler proposal.

**Comment by nzakas** [comment]
"Copy what Jest does" isn't really a proposal we can evaluate. We've already been exploring linting files in parallel for a while, but likely won't revisit that until we do the larger rewrite.

If there's something specific about what Jest does that is different than what was already proposed in the RFC, please describe those differences on this issue.

**Comment by gajus** [comment]
Sharding and parallel linting are separate problems.

Sharding could be a precursor to parallel linting.

**Comment by gajus** [comment]
@nzakas alternatively... if there was a way to pass a long list of files to ESLint, that would work too (sharding could be implemented in user land). However, my attempts to do that failed because of various limits. Maybe you have an idea how it is currently possible to pass a list of thousands of files to ESLint explicitly?

**Comment by bmish** [comment]
Relatedly, I've had some success speeding up ESLint in a large codebase by running it on several large directories separately and in parallel instead of just running `eslint .` on everything:

```json
{
  "scripts": {
    "lint:js": "npm-run-all --aggregate-output --continue-on-error --parallel \"lint:js:*\"",
    "lint:js:dir1": "eslint --cache dir1/",
    "lint:js:dir2": "eslint --cache dir2/",
    "lint:js:dir3": "eslint --cache dir3/",
    "lint:js:other": "eslint --cache --ignore-pattern dir1/ --ignore-pattern dir2/ --ignore-pattern dir3/ .",
  }
}
```

**Comment by gajus** [comment]
That's basically sharding, but limited by predefined patterns. This suggestion is a generic solution.

**Comment by gajus** [comment]
Re-opening as I see a lot of value in having this.

**Comment by nzakas** [comment]
Thanks for explaining. Just so I understand, if you pass `--shard 1/3` to Jest right now, it just takes the total number of files, divides it by three, and only runs on that first third? So it's basically filtering out matches to the glob pattern?

Does Jest also do any parallelization or is it just sharding?

I'm not opposed to this, but I think it does come down to what we want ESLint to do at a high level. We've been bitten by adding a bunch of one-off enhancements before, only to find that they don't all make sense when added together. So, I'd want to have a good story about parallel linting vs. sharding vs. anything else before making a final decision on this.

And this would require an RFC to move forward. I think there are some edge cases (caching, fixing, maybe more) that would need some thought.

**Comment by gajus** [comment]
> Thanks for explaining. Just so I understand, if you pass --shard 1/3 to Jest right now, it just takes the total number of files, divides it by three, and only runs on that first third? So it's basically filtering out matches to the glob pattern?

Correct.

> Does Jest also do any parallelization or is it just sharding?

Jest runs parallelization on top of shard.

Parallelization is configured using `--maxWorkers` (defaults to the number of CPUs).

```bash
# runs all matching tests using 4 workers
jest --maxWorkers 4
# runs a third of matching tests
jest --shard 1/3
# runs a third of matching tests using 4 workers
jest --shard 1/3 --maxWorkers 4
```

For what it is worth, the same pattern is followed by Jest, Playwright, and Vitest.

Sharing can be implemented without parallelization and vice-versa. However, sharding is easier to implement and will produce better speed gains on large projects than parallelization (because there is only so much you can parallelize using cores on a single machine).

It is also worth noting that sharding can already be achieved using [`jest-runner-eslint`](https://www.npmjs.com/package/jest-runner-eslint) in the exact same way as described above. The downside is that it attaches use of ESLint to Jest. In our case, we migrated away from Jest, so it is no longer an option.

> I think there are some edge cases (caching, fixing, maybe more) that would need some thought.

I would not optimize sharding to be executed concurrently on the same machine. It can be, but I would not expect operations like cache to function. In my eyes, sharding is primarily designed to distribute workloads horizontally.

**Comment by nzakas** [comment]
Thanks, that additional info is super helpful.

**Comment by Rec0iL99** [comment]
Waiting for an RFC. Don't close.

**Comment by Rec0iL99** [comment]
Hi @gajus, do you plan on making an RFC for this? We would need an RFC to move forward.

**Comment by nzakas** [comment]
@mdjermanovic would like your feedback on this idea.

**Comment by gajus** [comment]
> Hi @gajus, do you plan on making an RFC for this? We would need an RFC to move forward.

I am not familiar with ESLint RFC process, but if someone links me to the steps that describe it, will give it a shot!

**Comment by nzakas** [comment]
@gajus https://github.com/eslint/rfcs should get you started.

**Comment by sam3k** [comment]
We've decided in the 2023-03-23 TSC meeting to accept a RFC for `--shard` so we can determine whether or not to move forward. Notes from this meeting will be published in this [PR](https://github.com/eslint/tsc-meetings/pull/419/files).

**Comment by gajus** [comment]
Sorry, won't get to this. Been pushing back on my TODO daily, but other priorities are getting in the way.

**Comment by Rec0iL99** [comment]
> Sorry, won't get to this. Been pushing back on my TODO daily, but other priorities are getting in the way.

@gajus in that case, I'll close the issue. Feel free to re-open when you find the time to work on this. Thanks.

**Comment by nzakas** [comment]
RFC was opened: https://github.com/eslint/rfcs/pull/112

@balavishnuvj please be sure to comment on closed issues before opening PRs so we can keep up.

**Comment by Rec0iL99** [comment]
Not stale. RFC is open.

**Comment by nzakas** [comment]
We have an RFC open for this, so not closing.

**Comment by nzakas** [comment]
RFC is open but hasn't been updated in a while. We likely will need someone to take over the RFC for this to progress.

**Comment by Rec0iL99** [comment]
@nzakas should we close the RFC since there has been no response for a while now?

refer https://github.com/eslint/rfcs/pull/112#issuecomment-1753221879

**Comment by nzakas** [comment]
Yeah, just closed it, thanks for the heads up.

If anyone else is interested, we'd need an RFC to move forward with this.

**Comment by nzakas** [comment]
Because there has been no movement on this in a while, I'm closing. If anyone is interested in resurrecting this proposal, please leave a comment and we'll reopen.
