### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by lucasbriandbr** [eslint/eslint#16738]
### Environment

Node version: `v19.3.0`
npm version: `9.2.0`
Local ESLint version: `v7.32.0 (Currently used)`
Global ESLint version: `Not found`
Operating System: `win32 10.0.22000`

### What parser are you using?

@typescript-eslint/parser

### What did you do?

`npm audit fix` in `./web/` in `https://github.com/lucasbriandbr/bibliotheque`

### What did you expect to happen?

Fix the errors

### What actually happened?

```
up to date, audited 742 packages in 7s

108 packages are looking for funding
  run `npm fund` for details

# npm audit report

json5  <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/eslint-config-next/node_modules/json5
node_modules/eslint-plugin-import/node_modules/json5
  tsconfig-paths  3.5.0 - 3.9.0 || 3.11.0 - 3.14.1
  Depends on vulnerable versions of json5
  node_modules/eslint-config-next/node_modules/tsconfig-paths
  node_modules/eslint-plugin-import/node_modules/tsconfig-paths
    eslint-import-resolver-typescript  2.6.0-beta - 2.7.1
    Depends on vulnerable versions of tsconfig-paths
    node_modules/eslint-config-next/node_modules/eslint-import-resolver-typescript

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
  ```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I tried so hard before asking but i'm not an expert, i raised a limit. Thanks for your help <3

**Comment by mdjermanovic** [comment]
Hi @lucasbriandbr, thanks for the issue!

ESLint does not have the `json5` package as a dependency or transitive dependency. If you have concerns about `json5`, you can open issues in repositories for the packages listed in the audit report: `eslint-config-next` and `eslint-plugin-import`.
