### ISSUE TITLE
Allow setting file extensions in .eslintrc

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#1674]
At the moment you can only specify file extensions as a cli argument. I think it would be a good idea to be able to configure this in `.eslintrc` files, so I can enable additional file extensions only for some subdirectories.

**Comment by nzakas** [comment]
I'm not sure how this could be done efficiently. It would greatly complicate traversal of directories, which right now is very simple. I'd rather encourage people to use a build system for such fine grained control over what is listed.

**Comment by nzakas** [comment]
s/listed/linted/

**Comment by lo1tuma** [comment]
I haven’t thought about the implementation details but I think you are right and it’s probably not worth the effort.
