### ISSUE TITLE
Change Request: max-len autofix

### ISSUE THREAD

**Issue by caribou-code** [eslint/eslint#16746]
### ESLint version

8.x

### What problem do you want to solve?

It's likely that a high percentage of engineers care about line length, and therefore the rule `max-len`. However, because it doesn't support `--fix` but could potentially affect every line of code, it's too cumbersome for developers to manually reformat their code to adhere to this rule.

A common solution is to combine Prettier with ESLint, and use their `printWidth` rule, but there are significant drawbacks to that approach:
- Requires installing `prettier`, `eslint-plugin-prettier`, `eslint-config-prettier`
- Requires configuring `.eslintrc` with the above config in a very specific order
- Adds performance overhead at ESLint runtime
- Many Prettier rules are incompatible with ESLint and overriding the wrong ones (such as using `arrow-body-style`) can result in broken code output (in other words this setup is too fragile)

Adding the above overhead to a project to get autofix for 1 formatting rule seems overkill. I've seen this feature request in ESLint a few times over the last 4 years. Can it please be considered? If Prettier can do it, there must be a way for ESLint to do it.

### What do you think is the correct solution?

ESLint should autofix max-len

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @caribou-code, thanks for the issue!

Stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates), so we're not adding new features to the `max-len` rule. Also, as described in previous discussions about this feature - https://github.com/eslint/eslint/issues/11325, https://github.com/eslint/eslint/issues/13951, and https://github.com/eslint/eslint/issues/14527 - it isn't likely that this rule can be fixable. If someone wants to give it a try, it's always possible to make a custom rule based on the core rule and publish a plugin.
