### ISSUE TITLE
Change Request: Give advice on when to use disable comments

### ISSUE THREAD

**Issue by jfmengels** [eslint/eslint#16754]
### ESLint version

v8.31.0

### What problem do you want to solve?

The ESLint docs have a large section on [how to use comments to disable ESLint errors](https://eslint.org/docs/latest/user-guide/configuring/rules#disabling-rules) like `// eslint-disable rule-name`.

For all the "how" that this section provides, it doesn't explain in which situations or for what reasons to use disable comments.

Without this guidance, disable comments are being used and often abused, as I imagine you have seen in practice yourselves. For instance, someone disagreeing with an important rule that has been added and adding a disable comment. Or someone not understanding an issue and ignoring it because that's the easy way out. Or someone adding a disable comment to fix the issue later but never ending up doing it.

### What do you think is the correct solution?

I think that it is important to teach or guide users into using the tool properly. As maintainers of the tool, I believe that you are best placed to explain how to use the feature properly.

Giving some advice in [this section](https://eslint.org/docs/latest/user-guide/configuring/rules#disabling-rules), ideally at the beginning (before explaining how) sounds like the proper solution in my opinion.

As to what advice to write, I don't know. I am myself against this feature in general, as [I have previously written](https://jfmengels.net/disable-comments/), and as such have not enabled this feature in my own [linter](https://elm-review.com/).

As I don't know what to write, I am not willing to submit a pull request. I don't think I am best suited to answer this question.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
This is a good idea. We're in the middle of a big docs project right now, so it's a good time to note that this content is missing and should be added.

@bpmutter

**Comment by bpmutter** [comment]
i think it'd be reasonable to give a couple of scenarios where one might want to disable comments. and then point reader to the sections about disabling inline comments. 

@nzakas, what are some scenarios where you think users _should_ disable comments? and what are the scenarios for when it's generally not advised?

**Comment by bmish** [comment]
I previously put together a list of reasons [here](https://github.com/square/eslint-plugin-square#usage):

> Sometimes, you may not want to fix certain violations, for reasons such as:
>
> - Some code is too risky to change
> - A rule may have too many violations and fixing is too tedious / manual
> - A rule may have false positives and flag legitimate code
> - A rule may not apply / make sense in all circumstances
> - Some parts of the codebase may follow different conventions
> - You may want to follow-up later to address a specific rule in its own PR

Not a comprehensive list but could be helpful.

**Comment by nzakas** [comment]
I generally say that disable comments are appropriate when any of these is true:

a. the convention in this location is an exception to the overall project's conventions
b. you want the rule active but there isn't an option to disable the rule for that particular line or instance of code

We tend to say that the core rules are meant to cover 90% of the cases, but there are always edge cases, and it's not worth it for us to keep adding exceptions to serve a smaller and smaller portion of the user base. So we'll recommend using a disable comment if it seems unlikely that a new option would help the community at large.

I think @bmish's list are some examples that can be provided along those lines. That said, I believe a caveat would be if you start using a lot of disable comments then you should see if the rule can be updated to support your use case or else create a custom rule that does exactly what you want. If a codebase is littered with disable comments, that's not a good thing.

**Comment by criticalAY** [comment]
Hey! can I work on this issue I suggest the following along with some brief explanation for each
1. **Use with Caution**

2. **Document the Reason**

3. **Temporary Solutions**

4. **Code Reviews and Pair Programming**

5. **Configurations**

6. **Selective Rule Disabling**

7. **Rule Exemptions**

**Comment by nzakas** [comment]
@criticalAY Can you give a brief overview of what you'd cover in each section?

**Comment by criticalAY** [comment]
> @criticalAY Can you give a brief overview of what you'd cover in each section?
Yes, here it is

```
1. **Use with Caution**: Emphasize that disabling ESLint rules should be restricted and only in situations with a clear and valid reason for doing so. Disabling rules should not be the default solution to resolve linting errors.

2. **Document the Reason**:  Developers should provide a comment explaining the reason for disabling a particular rule. This documentation should clarify why the rule is being disabled and why it is necessary in that specific situation.

3. **Temporary Solutions**: If a disabled comment is added as a temporary measure to address a pressing issue, developers should also create a follow-up task or ticket to address the underlying problem adequately. This ensures that the disabled comment is revisited and resolved at a later stage.

4. **Code Reviews and Pair Programming**: Encourage team members to review each other's code regularly. Code reviews can help identify the reasons behind disabling comments and ensure that they are used appropriately.

5. **Configurations**: Whenever possible, prefer using ESLint configuration settings over disabled comments. Configuration files allow for consistent and project-wide rule handling.

6. **Selective Rule Disabling**: If multiple rules need to be disabled, consider using block-level or file-level disable comments instead of disabling individual rules inline. This can help prevent the proliferation of disable comments throughout the codebase.

7. **Rule Exemptions**: In cases where a specific rule consistently causes issues that are difficult to resolve, consider creating an exemption for that rule in the project's ESLint configuration with appropriate justifications.
```

**Comment by criticalAY** [comment]
@nzakas this is detailed enough to guide the developers through ig

**Comment by bmish** [comment]
Some of these sections seem too subjective. I disagree with a few, for example:

> 5. **Configurations**: Whenever possible, prefer using ESLint configuration settings over disabled comments. Configuration files allow for consistent and project-wide rule handling.

Disable comments can be appropriate in various situations. I don't see why there should be a blanket suggestion about avoiding them.

> 6. **Selective Rule Disabling**: If multiple rules need to be disabled, consider using block-level or file-level disable comments instead of disabling individual rules inline. This can help prevent the proliferation of disable comments throughout the codebase.

Again, I think disable comments can be appropriate. In fact, individual disable comments can be nice, especially when combined with `--report-unused-disable-comments`, because when the violation is solved, we know the disable comment will be deleted too, as opposed to ending up with obsolete file-level disable comments.

**Comment by criticalAY** [comment]
Then I can make amendments in 5 & 6 or just remove 5 and make little changes in 6 ?

**Comment by nzakas** [comment]
I think overall the message we want to give people is that config files are the best way to configure ESLint, but there are reasons why you may not be able to do that. For example:

1. If you don't have access to the filesystem to create a config file.
2. If you don't have access to the existing config file.
3. If your specific use case isn't supported by a rule's configuration.

So I think section 5 is fine so long as we are saying that the config file is the preferred way for long-term, maintainable ESLint settings. We don't want to say avoid inline configuration, just that they shouldn't be the first option.

I agree with removing 6 -- in general, I think we want to encourage people to use disable comments as close to the code they're related to as possible, to ensure the proper context is understood.

For section 7 - "exemption" isn't a term we use in ESLint. Can you explain what that means and what this section would be suggesting?

**Comment by criticalAY** [comment]
Section 7 basically deals with the situation where a specific type of method or code is reusing the disable comments.
So can I go ahead with removing section 6 and maybe amending the changes or removing it whatever you would suggestion for section 7 @nzakas

**Comment by nzakas** [comment]
Sounds good 👍

**Comment by criticalAY** [comment]
ok then I will go ahead
