### ISSUE TITLE
Change Request: Configure Parsers documentation

### ISSUE THREAD

**Issue by bpmutter** [eslint/eslint#16762]
### ESLint version

latest

### What problem do you want to solve?

Right now, the documentation for using custom parser in configuration doesn't make clear that a parser isn't part of a plugin, it's a separate entity. 

### What do you think is the correct solution?

take content about parsers from page `use/configure/plugins` about parsers and make a new page `use/configure/parsers`.

the fact that this wasn't in the initial IA update RFC was an oversight. addressing here.

Also, as part of this change, change the page "Configure Plugins & Parsers" to be titled "Configure Plugins"
### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
@amareshsm thanks for marking this as accepted. Please remember to move issues into the "Ready to Implement" column in the Triage board as well.
