### ISSUE TITLE
Rule Change: no-multiple-empty-lines to have option for preventing autofix

### ISSUE THREAD

**Issue by TheNotary** [eslint/eslint#16770]
### What rule do you want to change?

no-multiple-empty-lines

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
const myAppIdOrSomething = "0001";
const myReadableCodeLabelName = "Projection (with special hashing): ";
const firstNumber = 5;
const secondNumber = 7;




const rep1 = foreignCode().getProvisioner();
const understatement = foreignCode().getProvisioner(false);
rep1.queryOpener(myAppIdOrSomething);
let can2 = understatement.clampVerification(rep1);
can2.special = "a1hsj2jhwjkaaaaaaa";   // only use a string that hashes to an even digit
const can3 = rep1.generateTicket()
can2 = understatement.clampVerification(rep1, true);
can3.reduce(can2)
const output = rep1.hash();




console.log(`${myReadableCodeLabelName} (${firstNumber}, ${secondNumber}): ${output}`)
```

### What does the rule currently do for this code?

The --fix command will tighten the code up, which during the development of this code isn't a good idea because it makes it harder to see where the line is between readable and non-readable code is.  

### What will the rule do after it's changed?

The rule change will allow users to supress the `--fix` operation, but still allow the warnings about it the issue and fail CI if the code goes unaddressed.  That way you can keep working out the code without the whitespace jumping all over the place after saving and hopefully you eventually decide how the code can be arranged in a readable way.  

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

I tried to configure vscode to not fix this rule, but the only way I've found to prevent eslint from fixing a specific error is by completely disabling the rule.  

err, actually I just go this to work, but it's hacky... I'm checking to see if I'm running via vs code by check for key env variables, and disabling the rule completely if it's vscode running eslint.  

(`.esconfigrc.js`)
```
const isRunningFromVsCode = process.env.ELECTRON_NO_ASAR === '1';

module.exports = {
  .
  .
  .
  rules: {
    'no-multiple-empty-lines': isRunningFromVsCode ? 'off' : 'error'
  }
};

```

**Comment by nzakas** [comment]
We don't have any way to opt-out a single rule from autofixing, so you'll need to use a strategy like you've already mentioned. 

In general, we recommend not using autofix on save in your editor as it can be difficult to locate changes that were made. It's better to use autofix on precommit.

**Comment by TheNotary** [comment]
Ok thanks for the suggestion!
