### ISSUE TITLE
Rule Change: key-spacing align indentation

### ISSUE THREAD

**Issue by murillo128** [eslint/eslint#16772]
### What rule do you want to change?

key-spacing

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
var obj = {
    "one" : 1,
    "seven" : 7
}
var obj = {
    "thirteen" : 1,
    "seven" : 7
}
```

### What does the rule currently do for this code?

Currently, different objects area aligned to the max width of the keys contained in the object
```
var obj1 = {
    "one"   : 1,
    "seven" : 7
}
var obj2 = {
    "thirteen" : 1,
    "seven"    : 7
}
```

### What will the rule do after it's changed?

With the proposed change, it would be possible to specify an indent value, so similar objects are aligned equally.

In the following example, the values would be indented to the next colum multiple of 4: 
```
var obj1 = {
    "one"    : 1,
    "seven"  : 7
}
var obj2 = {
    "twelve" : 1,
    "seven"  : 7
}
```

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

The change is easy to implement, just need to change this line

https://github.com/eslint/eslint/blob/main/lib/rules/key-spacing.js#L583

by:

```
 let targetWidth = Math.ceil(Math.max(...widths) / indent) * indent,
```

**Comment by mdjermanovic** [comment]
Hi @murillo128, thanks for the issue!

Per our rules policies, [stylistic rules are frozen](https://github.com/eslint/eslint#stylistic-rule-updates), so we are not adding new options to the `key-spacing` rule. You can always copy the existing rule into a custom rule and make it behave the way you want.
