### ISSUE TITLE
Allow snake case (and more) as an exception to the dot-notation rule

### ISSUE THREAD

**Issue by tschaub** [eslint/eslint#1679]
In cases where data is being sent to an external API and the developer does not have control over variable names, snake_case properties often need to be used.  In order to use the `dot-notation` and `camelcase` rules together, it would be useful to add `allowSnakeCase` support to the `dot-notation` rule.

This would allow the following configuration:
```js
{
    "rules": {
        "camelcase": 2
        "dot-notation": [2, {"allowSnakeCase": true}]
    }
}
```

And the resulting behavior:
```js
var data = {};
data.foo_bar = 42; // warning from camelcase

var data = {};
data["fooBar"] = 42; // warning from dot-notation

var data = {};
data["foo_bar"] = 42; // no warning
```

I'm willing to work on this if it sounds good.  Here's a branch with changes to support `allowSnakeCase`: https://github.com/tschaub/eslint/compare/eslint:master...tschaub:bracketed_snakes.  I'm happy to submit a pull request or rework this if it is an acceptable change.

See also #1550.  Using bracket notation for snake cased properties is an alternative to adding comments to have `eslint` ignore chunks of code.

**Comment by nzakas** [comment]
Sorry, I'm having a little trouble understanding the problem this is meant to solve. Can you describe the problem without referencing your proposed solution?

**Comment by tschaub** [comment]
I'd like to be able to use both the `dot-notation` and `camelcase` rules to enforce that dot notation is used (with one exception) and that variables and property names are camel case.  However, I find it fairly common to need to prepare data to be sent to an external service where I don't have control over the service (so I don't control member names in the JSON it expects, for example).  So I'd like to have an exception that allows bracket notation for snake case property names.

Currently, I'm working with code that prepares data to be sent to an analytics service.  There are a number of members in the JSON payload that are conditionally included, so the JavaScript object cannot be constructed with a simple object literal.  For example:
```js
// we're collecting some analytics about a "scene" object
var data = {
  'scene_id': scene.get('id')
};

if (scene.get('modified')) {
  /*eslint-disable dot-notation */
  data['age_seconds'] = (Date.now() - new Date(scene.get('modified'))) / 1000;
  /*eslint-enable dot-notation */
}
// etc.

// here, data is serialized and sent to an external service
analytics.track('some event', data);
```

This usage is common enough in the code I'm working with, that I'd prefer to have an option for the `dot-notation` rule rather than disabling it as above.

**Comment by nzakas** [comment]
Okay, let me restate to see if I understand. You want to use snake case strings as properties but `dot-notation` warns that these should not use strings. So if you dying use strings, `camelcase` will warn that the property isn't in camel case. Is that correct?

**Comment by tschaub** [comment]
Yes.  I think you've got it.  However, I wouldn't say that my primary motivation is to use snake case strings.  My motivation is to occasionally assign to properties with snake case names (in cases where data is going to be serialized for an external service that I don't control).

At the same time, I'd like to enforce both the `dot-notation` and `camelcase` rules elsewhere.  Without any changes to `eslint`, I've got two alternatives given the configuration below.
```js
{
  "rules": {
    "camelcase": 2,
    "dot-notation": 2
  }
}
```

**Alternative 1**
```js
/*eslint-disable camelcase */
data.foo_bar = 42;
/*eslint-enable camelcase */
```

**Alternative 2**
```js
/*eslint-disable dot-notation */
data['foo_bar'] = 42;
/*eslint-enable dot-notation */
```

This proposal is about adding an option that allows selective use of snake case properties without disabling the linter in a comment.

**Comment by nzakas** [comment]
Okay, I think I'd actually generalize this out a bit more. I don't think this desire is unique to using snake case. It might be best to solve this in a general way where you can provide a pattern that should be exempt from the `dot-notation` check. That way we could support snake case and any other special cases that might pop up in the future rather than needing to identify and name exceptions.

**Comment by tschaub** [comment]
@nzakas sounds good.  Let me know if something like this would work: https://github.com/tschaub/eslint/compare/eslint:master...tschaub:allow_pattern

Example usage:

```js
  "rules": {
    // allow bracket notation with snake_case properties
    "dot-notation": [2, {"allowPattern": "^[a-z]+(_[a-z]+)+$"}]
  }
```

**Comment by nzakas** [comment]
Yeah, that looks like a good start.

**Comment by tschaub** [comment]
@nzakas should I open a PR to continue discussion there (still seeing the "question" label here)?

**Comment by nzakas** [comment]
Just updated the labels. Feel free to open a PR.
