### ISSUE TITLE
Change Request: (fill in)

### ISSUE THREAD

**Issue by mhenke** [eslint/eslint#16805]
### ESLint version

v8.0

### What problem do you want to solve?

Creating a style guide based on my specific eslint settings. This would help document of the settings and style of our code for other people like management, team members, and not familiar with the customization.

### What do you think is the correct solution?

I would eslint  formatter option to be able to print a style guide md or html file (s) based on the configuration of my eslint file.

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the idea, but this is outside the scope of ESLint. ESLint isn't primarily a style guide enforcer, so we don't want to add anything that is specific to that use case. Generating style guide documentation would be better served by a separate utility.
