### ISSUE TITLE
Bug: Plugin "import" was conflicted between ".eslintrc.json eslint-config-next" and ".eslintrc.json eslint-config-airbnb when using pnpm

### ISSUE THREAD

**Issue by niconatalie** [eslint/eslint#16821]
### Environment

Node version: `v17.9.1`
npm version: `8.11.0` / pnpm version : `7.17.1`
Local ESLint version: `v8.30.0`
Global ESLint version: `v8.30.0`
Operating System: `Ubuntu 18.04.6 LTS`

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I am using `pnpm` and here is the dev dependencies and the minimal `eslintrc.json`.

<details>
<summary>Configuration</summary>

```
{
  "devDependencies": {
    "@next/eslint-plugin-next": "12.2.5",
    "eslint": "^8.30.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "17.0.0",
    "eslint-config-next": "12.2.5",
    "eslint-config-prettier": "^8.3.0",
    "eslint-formatter-gha": "1.4.1",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.6.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-storybook": "^0.6.7",
    "typescript": "4.9.4"
  }
}
```
</details>

```js
{
  "root" : true,
  "extends": [
    "airbnb",
    "airbnb-typescript",
    "next"
  ],
  "plugins": ["react", "@typescript-eslint", "prettier"]
}
```

### What did you expect to happen?

It should run lint correctly

### What actually happened?

Running `npm run lint` causing this error
```
npm run lint

> myappp@0.0.1 lint
> next lint

Plugin "import" was conflicted between ".eslintrc.json » eslint-config-next" and ".eslintrc.json » eslint-config-airbnb » /home/johndoe/Documents/monorepo/node_modules/.pnpm/eslint-config-airbnb-base@15.0.0_2lbwmhbr7bncddqbzzpg77o75m/node_modules/eslint-config-airbnb-base/index.js » /home/johndoe/Documents/monorepo/node_modules/.pnpm/eslint-config-airbnb-base@15.0.0_2lbwmhbr7bncddqbzzpg77o75m/node_modules/eslint-config-airbnb-base/rules/imports.js".
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by yeonjuan** [comment]
Hi @niconatalie , Could you try this solution? https://stackoverflow.com/a/71579750/15972211

> ## The problem:
eslint-plugin-react version in your project's dependency is "different" from the one in eslint-config-react-app package's dependency, hence "conflicting".

> ## he solution:
...

**Comment by niconatalie** [comment]
Thanks for your reply @yeonjuan!

We are using `pnpm`, so the `dedupe` command is not available for us, but I try to use [pnpm-deduplicate](https://www.npmjs.com/package/pnpm-deduplicate) and running `pnpm-deduplicate --list`

It doesn't show anything related to eslint are duplicated.

I checked manually for the conflicted plugin (`import` in this case) in the `pnpm-lock.yaml` file, it consistent using the same version `2.26.0`

**Comment by yeonjuan** [comment]
@niconatalie  Could you share some projects that can reproduce it? For example: github repo.
I tried reproducing it with the config you provided, but it seems not enough.

**Comment by sam3k** [comment]
@niconatalie could you share a reproducible example in a Github repo so we can try it?

**Comment by niconatalie** [comment]
sorry for late reply. I will prepare it soon

**Comment by snitin315** [comment]
Closing as not enough information was provided. Feel free to create a new issue with minimal reproduction steps.
