### ISSUE TITLE
Change Request: Bundle before publishing

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16820]
### ESLint version

HEAD

### What problem do you want to solve?

Currently, when we publish a new version of ESLint, we publish all of the source files as they are in source control. This means that when ESLint starts up, we need to read every file from disk, which contributes to slow startup time. We have also ended up lazy-loading core rules and formatters to address this in a small way, but we are still paying the cost for a lot of disk I/O even though we know most of the files will have to be loaded to run ESLint.

### What do you think is the correct solution?

Bundle (using Rollup, esbuild, etc.) some or all of our files before publishing.

The easiest thing to do would be to bundle `api.js`, which contains most of the code. We could also bundle up `cli.js`, but that would duplicate some of the code in `api.js`.

Undoubtedly this would require more thought and research to come up with a final solution, but I just wanted to get the conversation started.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

A side effect of producing one or more bundles that don't lazy-load dependencies is that it makes life a lot easier to create a (Rust/Deno wrapper binary](https://github.com/bartlomieju/eslint_binary). This works by loading a V8 snapshot of ESLint into Deno. There's a workaround now to eliminate a lot of the lazy loading and create a single-file bundle, but if we can do most of that work in core, then it will make moving eslint-binary forward a lot easier.

cc @bartlomieju

**Comment by bartlomieju** [comment]
Thanks for bringing this up! I can do some benches over the weekend to see if there's noticable performance improvement for startup time when using bundled code.

As you mentioned, some lazy-loading would have to be removed in order to produce a bundle - so far I found two things that would need to be changed:
1. `lib/rules/index.js` would have to use a regular `Map` instead of `LazyLoadingRuleMap`
2. Built-in formatter should be eagerly loaded, only 3rd-party formatters should be loaded via dynamic import

These 2 changes make it possible to generate a bundle with a simple `esbuild` command like so:
```
./node_modules/.bin/esbuild ./bin/eslint.js --bundle --format=iife --platform=node --outfile=bundle.js
```

I think there might be more APIs that do lazy loading, but so far I haven't spotted them.

> The easiest thing to do would be to bundle api.js, which contains most of the code. We could also bundle up cli.js, but that would duplicate some of the code in api.js.

IMO the most popular way to use ESLint is via CLI, so in my mind bundling `cli.js` is more beneficial in this case.

**Comment by nzakas** [comment]
If we bundle cli.js only, then we will either need to ship the unbundled source to give API access or create a second bundle for api.js. And I’d we remove all lazy loading, then we will need a api.js bundle to avoid perf hits through the API

**Comment by bartlomieju** [comment]
> If we bundle cli.js only, then we will either need to ship the unbundled source to give API access or create a second bundle for api.js. And I’d we remove all lazy loading, then we will need a api.js bundle to avoid perf hits through the API

Actually a very good point. I guess it makes more sense to bundle `api.js` after all. Eg in `eslint_binary` it would be better to use `api.js` and rewrite the CLI in Rust (and I guess I would do similar thing if we decide to embed `eslint` in `deno`).

I'll do some tests over the weekend and get back with some numbers and modified commands to generate the bundle.

While we're at it, is it reasonable to start any work on making lazy loading optional (or removed completely) for the built-in rules and formatters?

**Comment by nzakas** [comment]
I think it would be too disruptive to have an opt-out for lazy loading. We generally try to just have one way of doing things to avoid complexity. I’d like to see if we can get agreement on bundling and then do that with the change away from lazy loading.

@eslint/eslint-tsc still need feedback on this.

**Comment by bartlomieju** [comment]
Getting back with benchmark results I can see about 16ms (or 10%) faster execution using bundled ESLint CLI compared to version installed from npm:

```
hyperfine -i "env ESLINT_USE_FLAT_CONFIG=true node ./eslint/bundled_cli.js -c test/config.js test/foo.js" "env ESLINT_USE_FLAT_CONFIG=true ./node_modules/.bin/eslint -c test/config.js test/foo.js"
Benchmark 1: env ESLINT_USE_FLAT_CONFIG=true node ./eslint/bundled_cli.js -c test/config.js test/foo.js
  Time (mean ± σ):     163.8 ms ±   1.5 ms    [User: 152.2 ms, System: 14.7 ms]
  Range (min … max):   162.0 ms … 166.4 ms    17 runs

  Warning: Ignoring non-zero exit code.

Benchmark 2: env ESLINT_USE_FLAT_CONFIG=true ./node_modules/.bin/eslint -c test/config.js test/foo.js
  Time (mean ± σ):     179.8 ms ±   1.6 ms    [User: 181.1 ms, System: 24.1 ms]
  Range (min … max):   177.7 ms … 183.5 ms    16 runs

  Warning: Ignoring non-zero exit code.

Summary
  'env ESLINT_USE_FLAT_CONFIG=true node ./eslint/bundled_cli.js -c test/config.js test/foo.js' ran
    1.10 ± 0.01 times faster than 'env ESLINT_USE_FLAT_CONFIG=true ./node_modules/.bin/eslint -c test/config.js test/foo.js'
```

This is using the same bundle from `eslint_binary` project, here's contents of `bundled_cli.js`:
```js
require("./eslint_bundle.js");
globalThis.initEslint(global, process, __filename, __dirname);
globalThis.runEslintMainFn();
```

**Comment by nzakas** [comment]
So that is using the bundle that includes not just `api.js`, but all of the ESLint code and all of the npm packages bundled into one file?

**Comment by bartlomieju** [comment]
> So that is using the bundle that includes not just `api.js`, but all of the ESLint code and all of the npm packages bundled into one file?

That's correct - including all the built-in rules and formatters. I haven't had time yet to check the results for just `api.js` bundle.

**Comment by nzakas** [comment]
Gotcha. So I think what might be a good intermediate step is if we bundle `api.js` without external dependencies. That will enable us to make the switch away from lazy-loading. We could then add a second dev-only build step that bundles everything, including external dependencies, for use in the Rust CLI.

**Comment by nzakas** [comment]
**TSC Summary:** This issue proposes that we bundle part or all of our JavaScript files upon publishing of each version. Doing so would 1) speed up startup time by reducing file system access and 2) make it easier to create a Rust CLI wrapper around ESLint. My suggestion is to bundle `api.js` without external dependencies and publish that during the release while also adding a process to bundle the entire CLI, including external dependencies, into one file to ease the Rust CLI development.

**TSC Question:** Do we want to accept this proposal?

**Comment by btmills** [comment]
We approved this proposal in the [2023-02-09 TSC meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2023/2023-02-09.md#change-request-bundle-before-publishing)! @bartlomieju would you be interested in setting up a bundle step for `api.js` during releases?

**Comment by bartlomieju** [comment]
Hey @btmills I was supposed to look into that the past weekend, however due to incoming Deno v1.31 release I was short on time. I should be able to pick it up in the coming days.

**Comment by nzakas** [comment]
@bartlomieju no problem at all!

Some tidbits that may be of interest related to this:

* Actual execution of the CLI starts with `bin/eslint.js` and [flows through](https://github.com/eslint/eslint/blob/main/bin/eslint.js#L135) to `lib/cli.js`
* `lib/cli.js` in turn [references](https://github.com/eslint/eslint/blob/df809fdedc5fc92df4be8340e28baedbde605b4f/lib/cli.js#L21-L22) the `ESLint` and `FlatESLint` classes directly from the filesystem. We should be able to replace these with `api.js`

Let us know if you run into any issues.

**Comment by nzakas** [comment]
This turned out to be more work than anticipated, so not moving forward.
