### ISSUE TITLE
docs: broken links

### ISSUE THREAD

**Issue by Zamiell** [eslint/eslint#16833]
The following URL is broken multiple times:

https://eslint.org/docs/use/rule-deprecation

e.g. on the rules page: https://eslint.org/docs/latest/rules/

**Comment by mdjermanovic** [comment]
Transferred to the eslint/eslint repo.

There are two links on https://eslint.org/docs/latest/rules/:

![image](https://user-images.githubusercontent.com/44349756/215265735-6953ef73-78cd-4494-accd-e5ab7f2459ed.png)

![image](https://user-images.githubusercontent.com/44349756/215265799-ca848e39-26c8-467b-85ae-91a04f4caa5f.png)

**Comment by Zamiell** [comment]
Yup, what @mdjermanovic said is the issue that I found, thanks.

**Comment by Zamiell** [comment]
also, another small issue is that the comma should not be part of the link

**Comment by Zamiell** [comment]
> To solve this problem forever, we may need a link checker.

Relevant: https://github.com/facebook/docusaurus/issues/3321#issuecomment-787215626
