### ISSUE TITLE
docs: one example of `no-multiple-empty-lines` rule has double line numbers

### ISSUE THREAD

**Issue by jonz94** [eslint/eslint#16841]
### ESLint version

v8.33.0

### What problem do you want to solve?

Currently, the second example for https://eslint.org/docs/latest/rules/no-multiple-empty-lines#maxeof has double line numbers

<img width="910" alt="Screenshot 2023-01-30 at 18 58 00" src="https://user-images.githubusercontent.com/16042676/215460851-08901945-afad-4924-a973-1b7c8f29c6a0.png">

### What do you think is the correct solution?

I currently have 2 ideas:

### 1. Simply remove the line numbers in the example code

This do make the example on the docs site looks nice:

| Before | After |
| --- | --- |
| ![](https://user-images.githubusercontent.com/16042676/215276670-d75da4f0-4ff3-40e8-a0fa-78dc1940862f.png) | ![](https://user-images.githubusercontent.com/16042676/215462111-7adf3619-1a7f-4077-b5ee-7bfaae6aa449.png) |

but the example on the GitHub markdown preview would be a little bit awkward without these line numbers:

| Before | After |
| --- | --- |
| ![](https://user-images.githubusercontent.com/16042676/215463186-ad6f11cf-0c25-4efe-bb97-3190389f660e.png) | ![](https://user-images.githubusercontent.com/16042676/215463215-72f063d1-81c7-45bb-9f49-ac456e6c516f.png) |

### 2. Add a feature to disable line numbers for specific code block on the docs site

The line numbers feature on docs site is originally modified from `vitepress`, Ref: https://github.com/eslint/eslint/blob/13552c4e8d98c3b38b7dbff9c74dc82ca2aad385/docs/src/_plugins/md-syntax-highlighter.js#L55-L61
Then, I notice `vitepress` do have a way to enable/disable line numbers for individual code block (related PR: https://github.com/vuejs/vitepress/pull/1733)

So if we can implement this feature, we can use the following syntax:

```
```js:no-line-numbers
```

to disable line numbers for specific code block.

This also means we can also turn off line numbers for non-code content (e.g. shell commands, command output, etc.) afterward.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks, we will need to take a closer look at this. @eslint/website-team

**Comment by snitin315** [comment]
> 1. Simply remove the line numbers in the example code

I am inclined towards the first option as it is much simpler and easy to implement.

> but the example on the GitHub markdown preview would be a little bit awkward without these line numbers:

I feel it should be ok as those docs are not intended to be seen on GitHub.

> 2. Add a feature to disable line numbers for specific code blocks on the docs site

This would be relatively more effort, and we don't have many instances of such cases (I believe this is the only one).

**Comment by kecrily** [comment]
> > 1. Simply remove the line numbers in the example code
> 
> I am inclined towards the first option as it is much simpler and easy to implement.
> 
> > but the example on the GitHub markdown preview would be a little bit awkward without these line numbers:
> 
> I feel it should be ok as those docs are not intended to be seen on GitHub.

I also support the first option, and I don't think the lack of line numbers is an obstacle to reading. Because we don't specify the line number of a specific code in the documentation.

**Comment by harish-sethuraman** [comment]
Yep we can use the first option itself. Feel free to send a PR

**Comment by jonz94** [comment]
Thanks for the feedback and suggestions! I will send a PR using the first option.
