### ISSUE TITLE
Bug: `no-extra-parens` autofix changes assignment semantics

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#16850]
### Environment

Node version: v18.13.0
npm version: v8.19.3
Local ESLint version: v8.33.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.2.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "parserOptions": {
        "ecmaVersion": 2015
    },
    "rules": {
        "no-extra-parens": [
            "error"
        ]
    }
}
```
</details>

```js
let foo, bar;
(foo) = function () { };
(bar) = class { };
console.log(foo.name + bar.name);
```

### What did you expect to happen?

ESLint should not remove the parentheses in `(foo)` and `(bar)` automatically. The parentheses are required to prevent the class or function from having its `name` property set to the name of the variable.

### What actually happened?

The parentheses around `foo` and `bar` are removed by the autofix. The resulting code prints `foobar` instead of an empty string like the original code.

[**DEMO LINK**](https://eslint.org/play/#eyJ0ZXh0IjoibGV0IGZvbywgYmFyO1xuKGZvbykgPSBmdW5jdGlvbiAoKSB7IH07XG4oYmFyKSA9IGNsYXNzIHsgfTtcbmNvbnNvbGUubG9nKGZvby5uYW1lICsgYmFyLm5hbWUpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoyMDE1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLWV4dHJhLXBhcmVucyI6WyJlcnJvciJdfSwiZW52Ijp7fX19)

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

My suggestion is to disable the autofix for parentheses around a single identifier on the left side of an assignment when the right side contains an anonymous class or anonymous function. This would avoid unexpected changes in program behavior in some edge cases.

I can't decide if keeping the warning in the first place would be good or not.

**Comment by mdjermanovic** [comment]
Confirmed. Per [assignment operators runtime semantics evaluation](https://tc39.es/ecma262/#sec-assignment-operators-runtime-semantics-evaluation), function name will be assigned only if [`IsIdentifierRef`](https://tc39.es/ecma262/#sec-static-semantics-isidentifierref) returns `true` for the left-hand side expression, which isn't the case for parenthesized expressions.

Since these parentheses are semantically significant, I think the `no-extra-parens` rule should just not report them.

**Comment by fasttime** [comment]
Thanks for accepting this @mdjermanovic. Following the spec link you provided, I was able trace the norm about the naming of anonymous functions in assignments all the way back to [ES6](https://262.ecma-international.org/6.0/#sec-assignment-operators-runtime-semantics-evaluation), but not to [ES5](https://262.ecma-international.org/5.1/#sec-11.13.1) (in fact, ES5 does not even define a `name` property on functions). Now I'm wondering, since the parentheses are only significant in ES6 or later, if the rule should still report them when `ecmaVersion` is 3 or 5.

**Comment by mdjermanovic** [comment]
> Now I'm wondering, since the parentheses are only significant in ES6 or later, if the rule should still report them when `ecmaVersion` is 3 or 5.

I think the rule shouldn't report them regardless of `ecmaVersion`. Even if code is written to be able to work in < es6, it's usually likely that it will be used in >= es6 as well.

**Comment by fasttime** [comment]
> I think the rule shouldn't report them regardless of `ecmaVersion`.

Fine, thanks. I'd be happy to work on a fix. As per discussion, the rule shall not report a problem in this case.
