### ISSUE TITLE
Failure to ignore file when name or pattern has leading "./"

### ISSUE THREAD

**Issue by montlebalm** [eslint/eslint#1685]
I've noticed an issue where files I intended to ignore are being included. This only happens when my file path or ignore pattern has the "current directory" prefix (`./`). Here are the conditions under which it can be reproduced:

1. Ignore pattern has `./` prefix and file name does not. For example, an `.eslintignore` of `./source.js`, will lint the file targeted by `eslint source.js`.

1. Ignore pattern does not have `./` prefix and file name does. For example, an `.eslintignore` of `source.js`, will lint the file targeted by `eslint ./source.js`.

Everything works if both the pattern and file name have the prefix or if neither do.

The problem occurs during the comparison between ignore patterns and file names in [lib/ignored-files.js](https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js#L113). Ideally, this "current directory" prefix shouldn't matter, since the logical file paths are the same. It would be nice if eslint were less strict about this detail.

I'm happy to work on this. I have a working fix, but I need to review and write tests.

**Comment by nzakas** [comment]
Sounds good. Please take a moment to read over our contribution guidelines: http://eslint.org/docs/developer-guide/contributing.html

Also, take a look at our CLA: http://eslint.org
