### ISSUE TITLE
Change Request: Keep providing context.parserPath for flat eslint

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#16878]
### ESLint version

8.33.0

### What problem do you want to solve?

Currently eslint provides `context.parserPath` to rules.
But this property which is required for rules from eslint-plugin-import is no longer available when using the flat config.
According to #13481 it should be available, as it is still in phase 2 (" Ensure context.parserPath still works in Linter for FlatConfigArray (for now)") and not in phase 5 where will be removed.
It seems that currently the linter just [passes an explicit undefined](https://github.com/eslint/eslint/blob/f0a988384ea1a262150e70d83abd8a5e50c46fa7/lib/linter/linter.js#L1700) for the parserPath for flat configs.

### What do you think is the correct solution?

Keep passing `context.parserPath` until it is removed or provide an alternative.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> Keep passing `context.parserPath`

I don't think eslint can provide `context.parserPath` in the flat config mode, because eslint doesn't know the path. In the flat config system, eslint doesn't load parsers. Users provide parsers as objects.

> or provide an alternative.

Rules can already switch to `context.languageOptions.parser`.

**Comment by DMartens** [comment]
Thanks for the clarification.
Then I will file an issue at eslint-plugin-import.
The reason I filed it here is that it was intended to be still supported (see #13481) and so other plugins would also benefit from it.

**Comment by CallMeLaNN** [comment]
@DMartens you probably want to see this [Feature Request Support new ESLint flat config](https://github.com/import-js/eslint-plugin-import/issues/2556)

**Comment by DMartens** [comment]
@CallMeLaNN thanks for the link but that issue is primarily about providing configs for the flat config.
This PR enables to use the the parser of the current linted file without the workaround you posted about manually setting the parsers.
