### ISSUE TITLE
Change Request: [flat config] add defineConfig utility like vitejs

### ISSUE THREAD

**Issue by liuweiGL** [eslint/eslint#16874]
### ESLint version

v8.33.0

### What problem do you want to solve?

Make the config friendly to typescript like vitejs https://vitejs.dev/config/#config-intellisense

### What do you think is the correct solution?

Add `defineConfig` utility

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment]
Hi @liuweiGL, thanks for opening the issue. This looks like a duplicate of #14249. I'm going to leave this open for someone from the core team to review and confirm my assumption. Thanks for using ESLint.
