### ISSUE TITLE
Bug: [flat config] Caching is not supported when parser is an object

### ISSUE THREAD

**Issue by liuweiGL** [eslint/eslint#16875]
### Environment

```txt
Node version: v18.14.0
npm version: v9.3.1
Local ESLint version: v8.33.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045
```

### What parser are you using?

@babel/eslint-parser

### What did you do?

eslint.config.js
```js
import babelParser from '@babel/eslint-parser'

export default [
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      parser: babelParser
    }
  }
]

```

### What did you expect to happen?

Print the config detail

### What actually happened?

```txt
PS C:\Users\liuwei\Desktop\gitlab\eastcoal-pc> pnpm eslint --print-config eslint.config.js

Oops! Something went wrong! :(

ESLint: 8.33.0

Error: Caching is not supported when parser is an object.
    at Object.value (C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\eslint@8.33.0\node_modules\eslint\lib\config\flat-config-array.js:188:27)
    at JSON.stringify (<anonymous>)
    at Object.execute (C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\eslint@8.33.0\node_modules\eslint\lib\cli.js:387:27)
    at async main (C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\eslint@8.33.0\node_modules\eslint\bin\eslint.js:135:24)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

https://eslint.org/blog/2022/08/new-config-system-part-2/#custom-parsers-and-parser-options-are-mostly-the-same

**Comment by Rec0iL99** [comment]
Hi @liuweiGL, thanks for opening this issue.
I was able to reproduce this on my machine. 

I ran with the default ESLint `languageOptions` and it gave me the desired output.
```js
// eslint.config.js

module.exports = [
  {
    files: ['**/*.js', '**/*.mjs'],
    rules: {
        "semi": "error",
        "no-unused-vars": "error"
    },
  }
]
```

```bash
npx eslint --print-config eslint.config.js

// output
{
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parser": "@/espree",
    "parserOptions": {},
    "globals": {}
  },
  "plugins": [
    "@"
  ],
  "rules": {
    "semi": [
      2
    ],
    "no-unused-vars": [
      2
    ]
  }
}
```

But with language options with the babel parser I got an error.

```js
const babelParser =  require('@babel/eslint-parser')

module.exports = [
  {
    files: ['**/*.js', '**/*.mjs'],
    rules: {
        "semi": "error",
        "no-unused-vars": "error"
    },
    languageOptions: {
        parser: babelParser
      }
  }
]
```

```bash
npx eslint --print-config eslint.config.js                                                                                        

// output
Oops! Something went wrong! :(

ESLint: 8.33.0

Error: Caching is not supported when parser is an object.
    at Object.value (/Users/joelmathew/WebProjects/experimenting-with-eslint/node_modules/eslint/lib/config/flat-config-array.js:188:27)
    at JSON.stringify (<anonymous>)
    at Object.execute (/Users/joelmathew/WebProjects/experimenting-with-eslint/node_modules/eslint/lib/cli.js:387:27)
    at async main (/Users/joelmathew/WebProjects/experimenting-with-eslint/node_modules/eslint/bin/eslint.js:135:24)
```

This error might have something to do with the @babel/eslint-parser, I'm not quite sure. Let's wait for someone from the core team to help us out here.

**Comment by liuweiGL** [comment]
Eslint seems to only support string parser
https://github.com/eslint/eslint/blob/3bd380d3ea7e88ade4905ec0b240c866ab79a69d/lib/config/flat-config-array.js#L147-L161
https://github.com/eslint/eslint/blob/3bd380d3ea7e88ade4905ec0b240c866ab79a69d/lib/config/flat-config-array.js#L184-L195

**Comment by nzakas** [comment]
Yes, this is a known limitation of the flat config format right now. We just need to decide how to implement caching for objects.

The most obvious choice is to ask parsers to implement some form of naming, perhaps like this:

```js
parser = {
   meta: {
       name: "foo",
       version: "1.1.1",
   }
};
```

**Comment by nzakas** [comment]
**TSC Summary:** We haven't yet implemented caching for object parsers or processors. To do this, we need a way to identify these objects uniquely. The proposal is to ask parsers to implement some identifying properties, such as:

```js
parser = {
   meta: {
       name: "foo",
       version: "1.1.1",
   }
};
```

**TSC Question:** How do we want to identify object parsers and processors for caching?

**Comment by exodus4d** [comment]
I came across the same issue with [eslint-plugin-jsonc](https://ota-meshi.github.io/eslint-plugin-jsonc/). I could work around the issue with a [runtime plugin](https://eslint.org/blog/2022/08/new-config-system-part-2/#from---rulesdir-to-runtime-plugins). 
The initial problem:

```javascript
// Prior (non flat config) -----------------------------------
module.exports = {
  extends: ["plugin:jsonc/recommended-with-jsonc"],
  parser: "@babel/eslint-parser",
  overrides: [
    {
      files: ["*.json", "*.json5", "*.jsonc"],
      parser: "jsonc-eslint-parser",
    },
  ],
};

// Flat config ------------------------------------------------
import jsonc from "eslint-plugin-jsonc";

export default [{
  files:   ["**/*.json", "**/*.jsonc", "**/*.json5"],
  plugins: {
    jsonc
  },
  languageOptions: {
     parser: 'jsonc/jsonc-eslint-parser' // <- Error because jsonc.parsers['jsonc-eslint-parser'] does not exists
  },
  rules: {...}
}];
```
The initial idea to bypass the `parser`[ as object](https://eslint.org/blog/2022/08/new-config-system-part-2/#custom-parsers-and-parser-options-are-mostly-the-same) failed because of this issue:
```js
  languageOptions: {
     parser: await import('jsonc-eslint-parser') // <- Error must be string. Object not implemented yet
  }
```
To work aroud this, I defined a runtime plugin of the same name `'jsonc'` and made the `parser` available under the `'parsers'` prop: `[Plugin_Name].parsers.[Parser_Name]`. No need to change `languageOptions.parser` to an object any more:
```js
import {default as jsonc, parseForESLint, configs} from "eslint-plugin-jsonc";

const parsers = {
  'jsonc-eslint-parser': {
    parseForESLint
  }
}

export default [{
  files:   ["**/*.json", "**/*.jsonc", "**/*.json5"],
  plugins: {
    jsonc: { ...jsonc, parsers}
    /* same as
    jsonc: {
      parsers: {
        'jsonc-eslint-parser': {
          parseForESLint
        }
      }
    } */
  },
  languageOptions: {
     parser: 'jsonc/jsonc-eslint-parser'
  },
  rules: {...}
}];
```
Not sure if this is a valid approach, but it seems to work so far.

**Comment by btmills** [comment]
Great that you found a workaround! We discussed the [`meta` cache key proposal](https://github.com/eslint/eslint/issues/16875#issuecomment-1423250263) in the 2023-02-09 TSC meeting, and all were in favor, so there will be a built-in solution to this once that's implemented.

**Comment by nzakas** [comment]
Working on this.
