### ISSUE TITLE
ES6 - Unexpected reserved keyword

### ISSUE THREAD

**Issue by qmmr** [eslint/eslint#1688]
I've tried linting person.js file written in ES6 syntax (class, import) but it errors with
`Unexpected reserved word`

```js
// person.js
import foo from './foo';

class Person {
	constructor(name) {
		this._name = name;
	}

	greet(greeting = 'Hello') {
		return `${this._name} says: ${greeting}!`;
	}
}

export default Person;
```

I was looking for a rule for this but I cannot find anything. Are there any plans to support this ES6 keywords?

**Comment by nzakas** [comment]
ESLint doesn't support module syntax yet. You can see the full list of ES6 features we support here: http://eslint.org/docs/configuring/

**Comment by vslinko** [comment]
Excuse me, @nzakas
Do you have any plans to support that feature?

**Comment by nzakas** [comment]
When Espree supports it, so will we. There's a PR open to support modules: https://github.com/eslint/espree/pull/43

**Comment by qmmr** [comment]
What about classes?

**Comment by nzakas** [comment]
Same answer. When the parser supports it, so will we.
