### ISSUE TITLE
New Rule: class-style

### ISSUE THREAD

**Issue by gurgunday** [eslint/eslint#16883]
### Rule details

Check how a class is created (expression vs. declaration)

### Related ECMAScript feature

Classes

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
// Force classes to be created using class declaration
class Class1 {

}

// Or class expressions
const Class2 = class {

}
```

### Why should this rule be in the core instead of a plugin?

Just like `func-style`, `class-style` can help force a specific style of coding and make things more consistent in a codebase.

### Participation

- [X] I am willing to submit a pull request to implement this rule.

**Comment by Rec0iL99** [comment]
Thanks for the suggestion @gurgunday. According to the following [comment](https://github.com/eslint/eslint/issues/15503#issuecomment-1010522197), we aren't adding any more rules that just enforce a stylistic preference. You can create a custom rule to achieve your specific goal. Thanks for using ESLint.

**Comment by gurgunday** [comment]
> Thanks for the suggestion @gurgunday. According to the following [comment](https://github.com/eslint/eslint/issues/15503#issuecomment-1010522197), we aren't adding any more rules that just enforce a stylistic preference. You can create a custom rule to achieve your specific goal. Thanks for using ESLint.

Hey @Rec0iL99, thanks for the timely response. Just a quick question, does that mean stylistic rules in the core will be deprecated in the future?

**Comment by Rec0iL99** [comment]
Not quite sure if stylistic rules will be deprecated in the future, but this [policy change](https://github.com/eslint/eslint#stylistic-rule-updates) and [blog post](https://eslint.org/blog/2020/05/changes-to-rules-policies/) should help you understand why the decision was made.
