### ISSUE TITLE
Bug: attemptFix function did not apply fix.text in my eslint-plugin

### ISSUE THREAD

**Issue by CaptainLiao** [eslint/eslint#16894]
### Environment

Node version: v14.16.1
npm version: 6.14.12
Local ESLint version: 8.2.0
Operating System:  windows 10

### What parser are you using?

Default (Espree)

### What did you do?

I create a plugin that will replace location.assign by navigateTo.

### What did you expect to happen?

````
// before
location.assign(123)

// run eslint --fix
const { navigateTo } from '@/lib/navigate'
navigateTo(123)
````

### What actually happened?

but, i got this:
````
// before
location.assign(123)

// run eslint --fix
const { navigateTo } from '@/lib/navigate'
location.assign(123)
````

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

see repro [eslint-plugin-huoli](https://github.com/CaptainLiao/eslint-plugin-huoli).

run `npm run test`. u can see the error.

**Comment by Rec0iL99** [comment]
Hi @CaptainLiao, thanks for the issue, I was able to reproduce the issue. 

Steps I followed:

``` bash
-- yarn install

-- yarn test                                                                                                                                          
yarn run v1.22.19
$ jest --verbose
 FAIL  test/eslint-rules.test.js
  huoli/no-location-jump
    valid
      ✓ winLoca = window.location; (35 ms)
    invalid
      ✓ var a = 1; location.href = 123; (10 ms)
      ✕ location.assign(123); (8 ms)

  ● huoli/no-location-jump › invalid › location.assign(123);

    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      "import { navigateTo } from '@/lib/navigate'·
    navigateTo(123);"
    Received:
      "import { navigateTo } from '@/lib/navigate'·
    location.assign(123);"
    
    Message:
      Output is incorrect.

    Difference:

    - Expected
    + Received

      import { navigateTo } from '@/lib/navigate'
    - navigateTo(123);
    + location.assign(123);

      at testInvalidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:949:28)
      at Object.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:983:29)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        0.693 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by CaptainLiao** [comment]
@Rec0iL99 that's right, test fail because of the bug.

**Comment by mdjermanovic** [comment]
This works as intended because the rule reports two separate problems with fixes that insert text at the same position, which is considered conflicting, so only one is applied. Generally, each fix should produce a complete, valid code, because fixes can be applied individually in IDEs, and even the `--fix` CLI option doesn't guarantee that all fixes will be applied since fixes can be conflicting. In this case, I think the rule should report only one lint problem (not two), with a fix that adds the import and changes the reported expression at the same time.
