### ISSUE TITLE
Bug: esquery 1.4.1 release seems to break eslint

### ISSUE THREAD

**Issue by scheibo** [eslint/eslint#16896]
### Environment

Node version: 19.0.1
npm version: 9.4.2
Local ESLint version: 8.34.0
Global ESLint version: n/a
Operating System:  macOS

### What parser are you using?

@typescript-eslint/parser

### What did you do?

esquery seems to have released a "patch" release 20 minutes ago which causes eslint to now break.

### What did you expect to happen?

It to work.

### What actually happened?

> smogon@2.2.4 lint
> eslint --cache *.ts

Oops! Something went wrong! :(

ESLint: 8.34.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting /home/runner/work/smogon/smogon/smogon/index.test.ts:1
    at Array.<anonymous> (/home/runner/work/smogon/smogon/node_modules/esquery/dist/esquery.min.js:1:29469)
    at /home/runner/work/smogon/smogon/node_modules/esquery/dist/esquery.min.js:1:29985
    at /home/runner/work/smogon/smogon/node_modules/esquery/dist/esquery.min.js:1:30512
    at b.matches (/home/runner/work/smogon/smogon/node_modules/esquery/dist/esquery.min.js:1:34848)
    at NodeEventGenerator.applySelector (/home/runner/work/smogon/smogon/node_modules/eslint/lib/linter/node-event-generator.js:296:21)
    at NodeEventGenerator.applySelectors (/home/runner/work/smogon/smogon/node_modules/eslint/lib/linter/node-event-generator.js:324:22)
    at NodeEventGenerator.enterNode (/home/runner/work/smogon/smogon/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/smogon/smogon/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:[79](https://github.com/pkmn/smogon/actions/runs/4189907220/jobs/7262767884#step:6:80)5:23)
    at /home/runner/work/smogon/smogon/node_modules/eslint/lib/linter/linter.js:1153:32
    at Array.forEach (<anonymous>)

### Participation

- [ ] I am willing to submit a pull request for this issue.

I mean, I'll open a PR to pin to 1.4.0, but I'm pretty sure anyone can do that.

**Comment by jackie-gan** [comment]
I have encounter the same problem, It seems that esquery@1.4.1 cause this problem, Currently I lock the version 1.4.0 first, Waiting a better solution :)

**Comment by jfeingold35** [comment]
We're encountering the same problem. Can confirm that `esquery@1.4.1` is the problem-child here.

**Comment by aarongoldenthal** [comment]
I get the error, but only with certain lint rules. Specifically only with [`sonarjs/no-one-iteration-loop`](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/src/rules/no-one-iteration-loop.ts), when run from the CLI or testing directly with the `ESLint` class (same error as above).

I can run all of my other rule configs for `eslint`, `eslint-plugin-jest`, `eslint-plugin-jsdoc`, `eslint-plugin-n`, `eslint-plugin-playwright`, `eslint-plugin-promise`, `eslint-plugin-sonarjs`, and `eslint-plugin-unicorn` without issues.

**Comment by jfeingold35** [comment]
I'm seeing it when we run typescript rules specifically.

**Comment by derodero24** [comment]
As a stopgap measure, edit package-lock.json as follows and `npm i` again to fix it.

```diff
...
- "esquery": "^1.4.1",
+ "esquery": "^1.4.0",
...
"node_modules/esquery": {
-    "version": "1.4.1",
-    "resolved": "https://registry.npmjs.org/esquery/-/esquery-1.4.1.tgz",
-    "integrity": "sha512-3ZggxvMv5EEY1ssUVyHSVt0oPreyBfbUi1XikJVfjFiBeBDLdrb0IWoDiEwqT/2sUQi0TGaWtFhOGDD8RTpXgQ==",
+    "version": "1.4.0",
+    "resolved": "https://registry.npmjs.org/esquery/-/esquery-1.4.0.tgz",
+    "integrity": "sha512-cCDispWt5vHHtwMY2YrAQ4ibFkAL8RbH5YGBnZBc90MolvvfkkQcJro/aZiAQUlQ3qgrYS6D6v8Gc5G5CQsc9w==",
      "dev": true,
      "dependencies": {
        "estraverse": "^5.1.0"
      },
      "engines": {
        "node": ">=0.10"
      }
    },
...
```

**Comment by Rec0iL99** [comment]
Could someone maybe create a small reproducible example for the team to have a better look?

**Comment by aladdin-add** [comment]
@Rec0iL99 As eslint does not have a package-lock.json, I've re-triggered the eslint's ci to repro: https://github.com/eslint/eslint/actions/runs/4177992099.

**Comment by derodero24** [comment]
@Rec0iL99 
Here's an example repo.
https://github.com/derodero24/eslint-issue-16896

**Comment by jaliph** [comment]
This is affecting Standard also, eventually all packages using eslint will be affected due to this.

**Comment by seminarian** [comment]
Im using yarn. Added this to the package.json as temp fix:
```
  "resolutions": {
    "esquery": "1.4.0"
  },
```

source: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by nzakas** [comment]
Reopening because while we have solved our CI problem, this is still affecting end users. We should try to root cause this.

**Comment by jfeingold35** [comment]
@nzakas , seems to have fixed the issue on our end.

**Comment by mdjermanovic** [comment]
Our tests are passing with the latest esquery v1.4.2: https://github.com/eslint/eslint/pull/16901

**Comment by nzakas** [comment]
Confirmed that when esquery v1.4.2 was released, anyone installing or reinstalling ESLint will work correctly.

If you come to this issue due to a broken local ESLint install, please try uninstalling and reinstalling the `eslint` package to update your dependencies.

**Comment by Slapbox** [comment]
Simply reinstalling ESLint didn't do it for us. For now we pinned the version to `1.4.2`.

**Comment by aladdin-add** [comment]
@Slapbox it's as you had installed the old esquery v1.4.1, and it has been saved in the lockfile. Please update/regenerate your lockfile and retry.
