### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by DervishD** [eslint/eslint#16904]
### Environment

Node version: v19.5.0
npm version: 9.3.1
Local ESLint version:  8.34.0
Global ESLint version: 8:34.0
Operating System: Windows 10 Home 22H2

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "worker": true,
        "serviceworker": true,
        "es6": true,
        "es2021": true
    },
    "extends": "eslint:all",
    "rules": {
        "array-bracket-newline": ["error", "consistent"],
        "array-element-newline": ["error", "consistent"],
        "arrow-parens": ["error", "as-needed"],
        "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
        "capitalized-comments": ["error", "always", { "ignoreConsecutiveComments": true }],
        "curly": ["error", "multi-line"],
        "default-case": "off",
        "dot-location": ["error", "property"],
        "function-call-argument-newline": ["error", "consistent"],
        "function-paren-newline": ["error", "multiline-arguments"],
        "guard-for-in": "off",
        "id-length": ["error", { "exceptions": ["i"] }],
        "indent": ["error", 4, { "MemberExpression": 0 }],
        "line-comment-position": "off",
        "max-classes-per-file": ["error", 2],
        "max-len": ["error", { "code": 120 }],
        "max-lines": ["error", { "max": 500, "skipBlankLines": true, "skipComments": true }],
        "max-lines-per-function": ["error", { "max": 50 , "skipBlankLines": true, "skipComments": true }],
        "max-statements": ["error", { "max": 20 }, {"ignoreTopLevelFunctions": true }],
        "max-statements-per-line": "off",
        "multiline-comment-style": ["error", "separate-lines"],
        "multiline-ternary": ["error", "always-multiline"],
        "newline-per-chained-call": "off",
        "no-extra-parens": ["error", "all", { "conditionalAssign": false }],
        "no-inline-comments": "off",
        "no-magic-numbers": ["error", { "ignoreArrayIndexes": true }],
        "no-multi-spaces": ["error", { "ignoreEOLComments": true }],
        "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
        "no-ternary": "off",
        "no-unused-expressions": ["error", { "allowShortCircuit": true }],
        "object-property-newline": ["error", { "allowAllPropertiesOnSameLine": true }],
        "one-var": "off",
        "padded-blocks": ["error", "never"],
        "quotes": ["error", "single"],
        "sort-keys": "off",
        "strict": ["error", "global"]
    }
}
```
</details>

```js
// In file z.js
const version = '1.0';  //  'version' is assigned a value but never used (no-unused-vars) error on this line.

// In file ww.js
importScripts('z.js');
// The console.log() statement below works perfectly, it is properly accessing the imported variable.
console.log(version); // 'version' is not defined (no-undef) error on this line.

// If, instead, the code is like this, it does not produce any warning:
// In file z.js
// globalThis.version = '1.0';
// In file ww.js
// importScripts('z.js');
// console.log(globalThis.version);

// Using a /* global */ comment fixes the error, too, but it is cumbersome to maintain, I prefer to use globalThis instead.
```

### What did you expect to happen?

Not having an error for that legal use of a `const` variable which will reside in the global scope anyway.

### What actually happened?

The `no-undef` error is produced when the variable is used, and `no-unused-vars` error happens when it is declared.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I'm aware that maybe this is not the best code style in the world, and that for this particular usage the `globalThis` solution is better, but I think this is a false positive.

¡Thanks!

**Comment by mdjermanovic** [comment]
Hi @DervishD, thanks for the issue!

ESLint doesn't track use of global variables across scripts.

> ```js
> // In file z.js
> const version = '1.0';  //  'version' is assigned a value but never used (no-unused-vars) error on this line.
> ```

This is the intended default behavior of the `no-unused-vars` rule. You can set [`"vars": "local"`](https://eslint.org/docs/latest/rules/no-unused-vars#vars-local) to allow global variables to be unused (here's a [Playground Demo](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgdmVyc2lvbiA9ICcxLjAnOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdW51c2VkLXZhcnMiOlsiZXJyb3IiLHsidmFycyI6ImxvY2FsIn1dfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)), or use [`/* exported */`](https://eslint.org/docs/latest/rules/no-unused-vars#exported) comments to mark variables that are intended to be used from other scripts (here's a [Playground Demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXhwb3J0ZWQgdmVyc2lvbiAqL1xuY29uc3QgdmVyc2lvbiA9ICcxLjAnOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdW51c2VkLXZhcnMiOlsiZXJyb3IiXX0sImVudiI6eyJlczYiOnRydWV9fX0=)).

> ```js
> // In file ww.js
> importScripts('z.js');
> // The console.log() statement below works perfectly, it is properly accessing the imported variable.
> console.log(version); // 'version' is not defined (no-undef) error on this line.
> ```

You can [specify globals](https://eslint.org/docs/latest/use/configure/language-options#specifying-globals) in your ESLint configuration file, or use `/* global */` comments.

**Comment by DervishD** [comment]
Thanks a lot @mdjermanovic!

I already knew about the alternatives you proposed in your reply, and in the end using `globalThis` is marginally better for my use case.

The important thing here is that this is the intended behaviour because I was giving for granted that ESlint was, in fact, tracking variables across scripts! No big deal, really, and it's OK 😄 

Thanks for the prompt reply!
