### ISSUE TITLE
Change Request: [RuleTester] error if multiple suggestion fixers have the same message

### ISSUE THREAD

**Issue by bradzacher** [eslint/eslint#16908]
### ESLint version

latest

### What problem do you want to solve?

Currently it's possible to accidentally create a rule that emits two suggestion fixers with the same message. This is a problem because IDEs will show a list of applicable fixers using the suggestion message; so if two have the exact same message then it means there will be two items in the list with exactly the same label - which is obviously confusing to the user.

### What do you think is the correct solution?

I propose that `RuleTester` be updated so that it enforces that for any given error, the hydrated `desc` of all suggestion fixers must be a unique string, enforcing that there are no duplicates.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

```js
// ❌ BAD
context.report({
  node,
  messageId: 'topLevel',
  suggest: [
    {
      fix: fixerOne,
      messageId: 'suggestionOne',
      data: { placeholder1: 'value1' },
    },
    {
      fix: fixerTwo,
      messageId: 'suggestionOne', // ❌ oops
      data: { placeholder1: 'value1' },
    },
  ],
});
```
```js
// ✅ GOOD
context.report({
  node,
  messageId: 'topLevel',
  suggest: [
    {
      fix: fixerOne,
      messageId: 'suggestionOne',
      data: { placeholder1: 'value1' },
    },
    {
      fix: fixerTwo,
      messageId: 'suggestionTwo', // ✅
      data: { placeholder1: 'value1' },
    },
  ],
});
```

**Comment by mdjermanovic** [comment]
> This is a problem because IDEs will show a list of applicable fixers using the suggestion message; so if two have the exact same message then it means there will be two items in the list with exactly the same label - which is obviously confusing to the user.

I agree with this and I support the proposed change 👍 

Since this is a new constraint that can cause existing plugin tests to fail, I think it should be treated as a breaking change.

**Comment by nzakas** [comment]
Seems reasonable to me. I'll add this to the v9 board so we can track it with the other breaking changes.

**Comment by JoshuaKGoldberg** [comment]
#17532 is ready for review. Marking as draft for now as it's a breaking change.
