### ISSUE TITLE
Bug: Glob pattern in excludedFiles not working.

### ISSUE THREAD

**Issue by infacto** [eslint/eslint#16909]
### Environment

Node version: 14.21.2
npm version: 6.14.17
Local ESLint version: 8.34.0
Global ESLint version: -
Operating System: Win 10

### What parser are you using?

@typescript-eslint/parser

### What did you do?

**override/excludedFiles**

```
my-path/!(aa|bb).json
```

**result**

```
✗ my-path/aa.json
✗ my-path/bb.json
✓ my-path/cc.json
✓ my-path/dd.json
✓ my-path/ee.json
```

Means for the inverted logic of "exclude": Only aa.json and bb.json. All other files are excluded.

### What did you expect to happen?

To use glob pattern in `excludedFiles`.

### What actually happened?

It seems it's not working. The files are still checked.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

See [glob tester online](https://www.digitalocean.com/community/tools/glob?comments=true&glob=my-path%2F%21%28aa%7Cbb%29.json&matches=false&tests=my-path%2Faa.json&tests=my-path%2Fbb.json&tests=my-path%2Fcc.json&tests=my-path%2Fdd.json&tests=my-path%2Fee.json).

Btw. missing docs for `excludedFiles`. It only appears in a [config example](https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work) and in [blog](https://eslint.org/blog/2022/08/new-config-system-part-1/#main).

**Comment by Rec0iL99** [comment]
Hi @infacto, thanks for opening the issue. I'm not familiar with glob patterns. I tried researching about glob patterns and found this issue #15670 which is quite similar. Glob patterns in overrides use [minimatch](https://github.com/isaacs/minimatch) syntax.

This [comment](https://github.com/eslint/eslint/issues/15670#issuecomment-1058021360) helped me find where you might be facing the issue.

> I think that (foo|bar) without a prefix doesn't have a specific syntactic meaning in globs.

Can you try this pattern:

```
my-path/!@(aa|bb).json
```

This is what I tried:

```js
const { minimatch } = require('minimatch')

// true
minimatch('cc.json', '!@(aa|bb).json')

// false
minimatch('aa.json', '!@(aa|bb).json')

// false
minimatch('bb.json', '!@(aa|bb).json')

// Adding `my-path/` doesn't seem to be working for me
// false
minimatch('my-path/cc.json','my-path/!@(aa|bb).json')

// false
minimatch('my-path/aa.json','my-path/!@(aa|bb).json')
```

I might be completely wrong here.

**Comment by Rec0iL99** [comment]
@infacto if possible please provide a reproducible example for the team to have a better look. Thanks.

**Comment by infacto** [comment]
@Rec0iL99 Thanks, I think it's a bit more complicated ... 

My example: https://github.com/infacto/my-eslint-playground

1. I use VSCode 1.75.1 Win 10 with ESLint plugin (dbaeumer.vscode-eslint).
2. You need to restart VSCode after eslint config file changed (in most cases).
3. You don't need VSCode to reproduce the issue, but in addition it shows a weird behavior related to this issue.

My initial issue may not be correct. Because it seems that `src/assets/!(aa|bb).ts` works. It has an affect to the selected files or vice versa. But let me explain:

Run 

```
npm run lint
```

Result:

```
.\src\assets\aa.ts
  1:7  error  Type boolean trivially inferred from a boolean literal, remove type annotation  @typescript-eslint/no-inferrable-types       

.\src\assets\bb.ts
  1:7  error  Type boolean trivially inferred from a boolean literal, remove type annotation  @typescript-eslint/no-inferrable-types       

.\src\assets\cc.ts
  1:11  error  Parsing error: Unexpected token :

.\src\assets\dd.ts
  1:11  error  Parsing error: Unexpected token :

.\src\assets\ee.ts
  1:11  error  Parsing error: Unexpected token :

✖ 5 problems (5 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

The errors for `aa.ts` and `bb.ts` are correct by the rules. And we see that the glob pattern works correctly.
But the file are still included or handled by the linter. In this case, it seems that they are parsed as JavaScript files. Because the parsing error about `:` token is about the type annotation of TypeScript `: boolean`.

In VSCode the excluded files `cc.ts`, `dd.ts` and `ee.ts` throws weird errors and remains on file close. It seems the error remains, because they are excluded. But why initial show errors if excluded? Sometimes it works. No error shown for these files. I haven't figured out how to reproduce the bug yet. Anyway... Maybe an issue of the extention and not eslint. Lets stick on the CLI first.

I would say, the glob pattern works and I have to rename the issue title. But the excluded files (cc, dd, ee) are still handled. It seems they are passed as JavaScript instead. I could work with the global (root) `ignorePatterns`. But what if you want to lint this files in another override?

Maybe this is not really a bug in this way. Because the command `eslint ./src --ext .ts` includes all files. And the override just picks the `aa` and `bb` file to be handled as TypeScript. The other files not matching the overrides are handled as JavaScript by default. As I write more and more, I guess you'll tell me that this is working as intended. ^^ I this is maybe correct. But how would the config look like? I guess I have to use `ignorePatterns` until I add a more specific overrides. Do you see an issue? I'm afraid it's my fault, isn't it? But without this issue report I would never have found out. Sorry anyway in this case. But can you explain it or confirm if this is a bug? Thanks.
