### ISSUE TITLE
Use new strict rule for ESLint codebase

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1691]
Now that #1687 is merged, using the strict rule without a mode option is deprecated. The existing code has 158 errors under the new "global" mode and 272 with "function" mode. The strict rule is turned off in tests/.eslintrc -  should that change with the new rule?

1. [ ] Pick a mode: "global" or "function"?
1. [ ] Decide whether strict should still be off in tests.
1. [ ] Fix lint errors.

**Comment by nzakas** [comment]
I think "global" is right for the repo. We do have some older files that have it in the function.

For tests - I'm not sure. It would probably be good to have all tests in strict mode, though for rule tests it hardly matters.
