### ISSUE TITLE
Change Request: curly all

### ISSUE THREAD

**Issue by carlocorradini** [eslint/eslint#16926]
### ESLint version

v8.33.0

### What problem do you want to solve?

**curly** rule is used to enforce consistent brace style for all control statements.

In the [docs](https://eslint.org/docs/latest/rules/curly) is written that to enable it for _all_ simply configure it as `curly: "error"`

However, I've tried and it does not work for _all_ unless explicitly specified in the rule configuration: `"curly": ["error", "all"]`

### What do you think is the correct solution?

The correct solution to enable _all_ is the one specified in the docs `curly: "error"` 

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment]
Hi @carlocorradini, thanks for opening the issue. Can you provide a minimal reproducible example for us to test? I tried the `curly` rule on my end without specifying the `all` option which is default by nature and it works for me.

**Comment by carlocorradini** [comment]
Test repository: https://github.com/carlocorradini/type-graphql/tree/maintainability

If I set `curly: "error"` some errors are not reported as when using `"curly": ["error", "all"]`

Is this a possible conflixt with TyepScript or ?

Thanks

**Comment by mdjermanovic** [comment]
This could be because some of the configurations you are extending from enable this rule with other options, and then `curly: "error"` in your config file just changes the severity while keeping the options.

https://eslint.org/docs/latest/use/configure/configuration-files#extending-configuration-files

Example from this section:

> * change an inherited rule's severity without changing its options:
>     * Base config: `"eqeqeq": ["error", "allow-null"]`
>     * Derived config: `"eqeqeq": "warn"`
>     * Resulting actual config: `"eqeqeq": ["warn", "allow-null"]`
