### ISSUE TITLE
Remove deprecated strict mode rules

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1692]
- [ ] Remove `global-strict` source, test, and documentation files.
- [ ] Remove `no-extra-strict` source, test, and documentation files.
- [ ] Remove support for using `strict` without a mode option in source, tests, and documentation.
- [ ] Remove `global-strict` and `no-extra-strict` settings in `conf/eslint.json`.
- [ ] Change the default setting for `strict` in `conf/eslint.json`.

**Comment by nzakas** [comment]
Special note to anyone watching: we won't do this until v1.0.0

**Comment by solmsted** [comment]
Please consider adding an option that enforces the deprecated mode of `strict` combined with `no-extra-strict`.  I use function mode for client-side modules that may be concatenated together and global mode for modules that only run in node.js.  Many modules run both client-side and in node.js so projects contain source files using both modes.  I would like to enforce strict mode everywhere and prevent unnecessary extra use strict directives without enforcing either function or global mode.

**Comment by nzakas** [comment]
The new `strict` already did this, that's why we are removing these rules.

**Comment by btmills** [comment]
@solmsted It sounds like you want some files in global strict mode and some in function strict mode, depending on whether they're intended to run on the client or the server. Is that right? If that's the case, you might find success using [configuration comments](http://eslint.org/docs/configuring/#configuring-rules) at the top of each file to select the appropriate mode.

**Comment by solmsted** [comment]
@nzakas The new `strict` doesn't do this.  It enforces either function mode, global mode, or never.  I guess I'd like another mode called `always` that would allow both function mode and global mode.

@btmills I'd considered using configuration comments.  I use them for some other rules but they are less useful for ensuring strict mode.  The rule is basically checking whether or not a developer remembered to type 'use strict'; at the top of the file.  If they have  to add configuration comments to the top of the file to enable the rule, what's checking that they remembered to do that?

I can work around this issue in my projects if needed.  The old functionality just fit my use case much better.

**Comment by nzakas** [comment]
Sorry, I misunderstood what you were looking for. I think we can probably add an "always" option that allows for either. Fwiw, I tend to put client JS in its own directory with an eslintrc file that overrides any node-specific settings.

**Comment by nzakas** [comment]
Closing in favor of #1898.
