### ISSUE TITLE
Change Request: Custom Rule tutorial

### ISSUE THREAD

**Issue by bpmutter** [eslint/eslint#16940]
### ESLint version

latest

### What problem do you want to solve?

It's challenging to figure out how to get started creating a custom rule.

### What do you think is the correct solution?

Add tutorial to guide user through rule creation. 

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by sam3k** [comment]
I'd be happy to go over your tutorial myself if you submit one :)

**Comment by sam3k** [comment]
Seems related to https://github.com/eslint/eslint/issues/16854
