### ISSUE TITLE
Change Request: Correct and unify `LintMessage` type

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#16968]
### ESLint version

v8.35.0

### What problem do you want to solve?

For the [processor docs update](https://github.com/eslint/eslint/pull/16838#discussion_r1107942761), we need to know why the `LintMessage` JSDoc typedef differs from real lint messages I captured at runtime. The short version is "because it doesn't reflect the implementation." I'll update the typedef or implementation, whichever is appropriate, to make sure they match.

### What do you think is the correct solution?

After examining the implementation, I'm confident in at least three changes to the `LintMessage` type:

```diff
 /**
  * @typedef {Object} LintMessage
  * @property {number|undefined} column The 1-based column number.
  * @property {number} [endColumn] The 1-based column number of the end location.
  * @property {number} [endLine] The 1-based line number of the end location.
- * @property {boolean} fatal If `true` then this is a fatal error.
+ * @property {boolean} [fatal] If `true` then this is a fatal error.
  * @property {{range:[number,number], text:string}} [fix] Information for autofix.
  * @property {number|undefined} line The 1-based line number.
  * @property {string} message The error message.
+ * @property {string} [messageId] The ID of the message in the rule's meta.
+ * @property {(string|null)} [nodeType] Type of node
  * @property {string|null} ruleId The ID of the rule which makes this message.
  * @property {0|1|2} severity The severity of this message.
  * @property {Array<{desc?: string, messageId?: string, fix: {range: [number, number], text: string}}>} [suggestions] Information for suggestions.
  */
```

1. Many places that create `LintMessage`s don't set `fatal`, so I made it optional. This would be a breaking change if we made types part of our exports, but in this case I believe it's not because it's updating JSDoc documentation to reflect the reality of the implementation.
2. Added an optional `messageId` property that's set by reports from rules.
3. Added an optional, nullable `nodeType` property.
    - Reports from rules set it to a value.
    - `applyDirectives()` [explicitly sets it to `null`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/apply-disable-directives.js#L265) for unused disable directives.
    - `Linter`'s `createLintingProblem()` [explicitly sets it to `null`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L286).

In addition, there are a couple types we can unify:

1. There are a [handful](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/apply-disable-directives.js#L199) of [places](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/config-comment-parser.js#L64) that [currently](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L367) [reference](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L778) an [undefined](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L997) [`Problem`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L1912) type that really means `LintMessage`, and I'll update those.
2. The [`ReportInfo`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/report-translator.js#L32-L47) type duplicates `LintMessage`, and I'll update that to reference `LintMessage` instead.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I have two open questions:

1. Should I make `nodeType` non-nullable and update the places in the implementation that explicitly set it to `null` to omit it instead? A few places already omit it for e.g. parse errors or ignored file messages, so API consumers already have to check that it might not be set.
3. `line` and `column` are currently required but possibly `undefined`.
    - Ignored file messages [currently omit `line` and `column`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/eslint/eslint-helpers.js#L608-L614).
    - `Linter` explicitly sets them to `0` for two configuration errors ([configured parser not found](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L1323-L1325) and [no configuration found for file](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L1799-L1801)).
    - `Linter`'s [`createLintingProblem()`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L270) has a [`DEFAULT_ERROR_LOC`](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L51) that defaults to line 1 column 0, but the default is only used for [missing rule definition messages](https://github.com/eslint/eslint/blob/caf08ce0cc74917f7c0eec92d25fd784dc33ac4d/lib/linter/linter.js#L1056).

    Should I either:
    1. Keep `line` and `column` required but possibly `undefined` and update ignored file messages to explicitly set them to `0`, following precedent elsewhere?
    1. Or make `line` and `column` optional and remove fallback 0/0 or 1/0 values from configuration issues?

    The second option is how I'd design the API from scratch because I wouldn't report a location unless we had a real location. But it might be a breaking change. Even though the type is specified as possibly `undefined`, in practice, some API consumers might only see messages that have real or fallback locations if they don't encounter ignored file messages. The second option would slightly increase the prevalence of location-less messages.

**Comment by fasttime** [comment]
I recall from a previous discussion that [changes in JSDoc should not be treated as breaking](https://github.com/eslint/eslint/issues/15654#issuecomment-1055249921), so there should be no problem in redeclaring `line` and `column` as optional. As for removing the different fallbacks, that's a change that could affect existing implementations. The same is true for omitting `nodeType` where it is being set to `null`. I'd like to know what the rest of the team thinks about this.

**Comment by nzakas** [comment]
Thanks for flagging this! I think updating the type definition so it reflects reality is the right way to go. Because we don't export types, this is non-breaking.

To answer your questions:

> Should I make `nodeType` non-nullable and update the places in the implementation that explicitly set it to null to omit it instead?

I think this is okay because it appears we [normalize `nodeType`](https://github.com/eslint/eslint/blob/dd58cd4afa6ced9016c091fc99a702c97a3e44f0/lib/linter/report-translator.js#L251) before we expose it externally.

> Keep line and column required but possibly undefined and update ignored file messages to explicitly set them to 0, following precedent elsewhere?

I also think this option is preferable to limit the amount of changes we are introducing into the codebase. I agree that if we were doing type checking from the start, we'd probably want the other option, but since we aren't, I'll favor the less invasive change.

@mdjermanovic what do you think?
