### ISSUE TITLE
Bug: ESLint Plugin Webpack eslint-config-prettier issue

### ISSUE THREAD

**Issue by bobbytreed** [eslint/eslint#16966]
### Environment

Node version: v18.14.2
npm version: v9.5.0
Local ESLint version: v8.35.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22621

### What parser are you using?

Default (Espree)

### What did you do?

I'm sure I'm doing something very dumb, but I can't spend any more time troubleshooting.

```typescript
 const eslint = new ESLint({
      useEslintrc: false,
      overrideConfigFile: lintConfigPath,
      cwd: rootDir
  });
  
  const results = await eslint.lintText(code);        
```
eslintrc
```json
{
    "plugins": [                    
    ],
    "root": true,
    "extends": [
        "eslint:recommended",        
        "./node_modules/eslint-config-prettier/index.js"
    ],
    "env": {
        "commonjs": true,
        "es2020": true,
        "node": true,
        "jest": true
    },
    "parserOptions": {
        "ecmaVersion": 11
    },
    "ignorePatterns": [
        ".vscode",
        ".devcontainer",
        "dist"
    ],
    "rules": {
        "semi": [
            "warn",
            "always"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "no-console": [
            0
        ],
        "no-return-await": [
            "warn"
        ]
    }    
}
```

The issue is that when ESLint attempts to load eslint-config-prettier, it resolves a full path from the eslintrc.json tries to use webpack to import that config file.

```js
_loadExtendedShareableConfig(extendName, ctx) {
        const { cwd, resolver } = internalSlotsMap$1.get(this);
        const relativeTo = ctx.filePath || path__default["default"].join(cwd, "__placeholder__.js");
        let request;

        if (isFilePath(extendName)) {
            request = extendName;
        } else if (extendName.startsWith(".")) {
            request = `./${extendName}`; // For backward compatibility. A ton of tests depended on this behavior.
        } else {
            request = normalizePackageName(
                extendName,
                "eslint-config"
            );
        }

        let filePath;

        try {
            filePath = resolver.resolve(request, relativeTo);
        } catch (error) {
            /* istanbul ignore else */
            if (error && error.code === "MODULE_NOT_FOUND") {
                throw configInvalidError(extendName, ctx.filePath, "extend-config-missing");
            }
            throw error;
        }

        writeDebugLogForLoading(request, relativeTo, filePath);
        return this._loadConfigData({
            ...ctx,
            filePath,
            name: `${ctx.name} » ${request}`
        });
    }
```

This ends up in a loadJSConfigFile

```js
function loadJSConfigFile(filePath) {
    debug$2(`Loading JS config file: ${filePath}`);
    try {
        return importFresh__default["default"](filePath);
    } catch (e) {
        debug$2(`Error reading JavaScript file: ${filePath}`);
        e.message = `Cannot read config file: ${filePath}\nError: ${e.message}`;
        throw e;
    }
}
```

import_fresh looks for the full path of the eslint-config-prettier file in 'd:\\Source\\DocIndexLinter\\src\\LanguageServer\\Client\\node_modules\\eslint-config-prettier\\index.js'
but __webpack_require__.c contains 
![image](https://user-images.githubusercontent.com/10874547/223258104-3516ec50-6fab-4c1a-8811-c7a2ee3585e0.png)

So it doesn't find it and I get the error 

![image](https://user-images.githubusercontent.com/10874547/223258713-346468f5-7cfe-4f8b-b72c-a474460175d4.png)

I know that there are tons of ways to configure WebPack resolutions and eslint plugin rules, but I cannot find and parse together the requisite documentation to understand what I'm doing wrong.  It feels like maybe something that webpack is doing, in that it should discern that the absolute path is acceptable to look up the config file, and if need be, I'll open an issue there, but I'm assuming it's something very simple that I'm missing.

### What did you expect to happen?

I assumed that the de facto require statement at the eslintrc.json file would find the plugin in the node_modules folder (where it is located) and discern the correct methodology for importing it.

### What actually happened?

Already described above.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
> The issue is that when ESLint attempts to load eslint-config-prettier, it resolves a full path from the eslintrc.json tries to use webpack to import that config file.

Are you trying to bundle eslint using webpack? 
atm, it's not officially supported, but we did a similar thing in our playground. you can check out here to see how it works: https://github.com/eslint/eslint.org/tree/main/src/playground

**Comment by bobbytreed** [comment]
I suppose that's fair, though the bundling did in fact work.  It was the plugins and extended config attributes that broke.

![image](https://user-images.githubusercontent.com/10874547/226350070-a02c8169-7979-43bf-89d8-b60e31897809.png)

**Comment by nzakas** [comment]
This is more related to Webpack than it is to ESLint, so closing.

**Comment by ck740** [comment]
Update
