### ISSUE TITLE
Change Request: Documentation-specific License

### ISSUE THREAD

**Issue by sam3k** [eslint/eslint#16980]
### ESLint version

v8.0.0

### What problem do you want to solve?

Currently we don't have a documentation-specific license, so it defaults to all rights reserved. As discussed in the `tsc-meeting` in 2023-03-09, we are going to license the docs under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

### What do you think is the correct solution?

Add a notice in:

- [ ] The docs README
- [ ] The footer of the docs site

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
The license in both places, should look like this:

> © OpenJS Foundation and ESLint contributors, [www.openjsf.org](https://www.openjsf.org/). Content licensed under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/).

This is ready to be implemented.

**Comment by sam3k** [comment]
@nzakas if this is just adding the notice in the two docs I'd be happy to help submitting a PR. (May have to work on it next week as this week is a bit tight for me).

**Comment by nzakas** [comment]
@sam3k yup, that's all there is to it. Feel free!

**Comment by sam3k** [comment]
PR: https://github.com/eslint/eslint/pull/17010 👍
