### ISSUE TITLE
Change Request: Update guard-for-in docs to use Object.hasOwn

### ISSUE THREAD

**Issue by alope107** [eslint/eslint#16981]
### ESLint version

v8.36.0

### What problem do you want to solve?

The docs for [guard-for-in](https://eslint.org/docs/latest/rules/guard-for-in) currently only show how to guard a for-in loop using `Object.prototype.hasOwnProperty` or `{}.hasOwnProperty`. However, as of ES2022, it is best practice to use `Object.hasOwn` instead (see [prefer-object-has-own](https://eslint.org/docs/latest/rules/prefer-object-has-own)).

### What do you think is the correct solution?

To show best practices, I propose adding the following as the first example in the examples of correct code:

```
for (key in foo) {
  if (Object.hasOwn(foo, key)) {
    doSomething(key);
  }
}
```

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I'm happy to make a PR for this small change if it's desired 🙂

**Comment by mdjermanovic** [comment]
Makes sense to me, PR is welcome!
