### ISSUE TITLE
Invalid option '--ext' - perhaps you meant '-c'?

### ISSUE THREAD

**Issue by pedrolgon** [eslint/eslint#16991]
### Environment

Node version: v16.17.1
npm version: 8.15.0
Local ESLint version: ^8.36.0
Global ESLint version: N/A
Operating System: Windows 10 Enterprise

### What parser are you using?

@babel/eslint-parser

### What did you do?

I have configure in the package.json one script in order to check the code.

package.json

 "scripts": {
    "check:lint": "esw -c eslint.config.js ./src ./test --debug",
    "fix:lint": "esw -c eslint.config.js ./src ./test --fix",
    "test": "npm run unit:test",
    "unit:test": "jest --passWithNoTests --coverage"
  },
"devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^8.36.0",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.5.0"
  },
  "dependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@babel/preset-env": "^7.20.2",
    "eslint-watch": "^8.0.0",
    "esw": "^0.15.0"
  }

when I execute the npm run check:lint I get the error 

Invalid option '--ext' - perhaps you meant '-c'?

### What did you expect to happen?

esw -c eslint.config.js ./src ./test --debug

### What actually happened?

> esw -c eslint.config.js ./src ./test --debug

2023-03-15T19:20:43.414Z eslint:cli CLI args: [ '--config', 'eslint.config.js', '--debug', '--ext', '.js', '--config-lookup', '--ignore', '--inline-config', '--error-on-unmatched-pattern', './src', './test' ]
2023-03-15T19:20:43.416Z eslint:cli Using flat config? true
2023-03-15T19:20:43.420Z eslint:cli Error parsing CLI options: Invalid option '--ext' - perhaps you meant '-c'?
Invalid option '--ext' - perhaps you meant '-c'?

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I need to execute eslint with esw not with npx

**Comment by mdjermanovic** [comment]
Hi @pedrolgon, thanks for the issue!

ESLint works as intended, because the `--ext` CLI option cannot be used with the new config system (`eslint.config.js`).

The problem here seems to be that `eslint-watch` runs `eslint` with `--ext .js` by default. The best course of action would be to report this problem to the eslint-watch repo:

https://github.com/rizowski/eslint-watch
