### ISSUE TITLE
Change Request: Switch from Karma to WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [eslint/eslint#17009]
### ESLint version

latest

### What problem do you want to solve?

It seems that Karma is not much maintained anymore as browser test framework and I wonder if the Eslint team would be interested switching to WebdriverIO. I've been working on supporting unit and component based browser tests in WebdriverIO within the recent month and would love to battle test it against mature projects like Eslint. And since we all are part of the OpenJS Foundation family I thought this project would be a good fit.

I am happy to do everything need to switch the harness. I feel like the setup would become much easier and it would be also very easy to run tests across different browser if this is desired.

### What do you think is the correct solution?

Run browser tests with WebdriverIO.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Feel free to disregard if you are happy with the current setup.

**Comment by Rec0iL99** [comment]
Hi @christian-bromann, thanks for the issue. 

**Some relevant info for the dev team:**
- The last [commit](https://github.com/karma-runner/karma/commit/50f963551fbccf669c8d42499d0406ded2ec6176) to the `karma` project was 7 months ago.

- I checked their [Twitter](https://twitter.com/JsKarma), [google group](https://groups.google.com/g/karma-users) and [gitter](https://app.gitter.im/#/room/#karma-runner_karma:gitter.im), and they all looked inactive to me.

- A [critical vulnerability issue](https://github.com/karma-runner/karma/issues/3823) might show that the maintainers aren't currently watching the project.

**Comment by christian-bromann** [comment]
@nzakas @mdjermanovic any comments?

**Comment by aladdin-add** [comment]
yes, I think it's good to have. Let's see what other team members think.

**Comment by mdjermanovic** [comment]
Since the Karma project seems inactive, I support this proposal 👍

**Comment by christian-bromann** [comment]
I raised a PR in #17126, there is still a bit work required as I had two skip to test but the rest works as before. Any initial feedback would be appreciated.
