### ISSUE TITLE
Suggestion: add a quick-link that allows you to open a rule in the playground

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#17018]
### What problem do you want to solve?

It'd be nice to have a quick way to jump from a rule's docs page to trying the rule out in the playground. For example, on https://eslint.org/docs/latest/rules/require-unicode-regexp, it'd be nice to have a quick way to jump to [a playground enabling the rule](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHJlcXVpcmUtdW5pY29kZS1yZWdleHA6IGVycm9yICovXG5SZWdFeHAoXCJoaVwiLCBmYWxzZSkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InJlcXVpcmUtdW5pY29kZS1yZWdleHAiOlsiZXJyb3IiXX0sImVudiI6eyJlczYiOnRydWV9fX0=).

### What do you think is the correct solution?

How about a _Try this rule in the playground ↗_ link in each rule page linking to the playground with the rule enabled in the config?

For reference, we added this to typescript-eslint.io in https://github.com/typescript-eslint/typescript-eslint/issues/6085 -> https://github.com/typescript-eslint/typescript-eslint/pull/6317.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I would love to implement this if accepted! 😄

**Comment by nzakas** [comment]
I like the idea. In order to move forward we would first need a design to evaluate. We actually did start out with a button "Open in Playground" on code samples, which is still commented out in the code:
https://github.com/eslint/eslint/blob/a8d0a57cbc29a917258df41d3254ecd29bcf61ab/docs/src/assets/js/main.js#L195

The problem was that it didn't distinguish between rule code samples and others, so we just removed it. If we want to revive that we'd need to solve that problem.

Because you can use inline comments to configure options, all we really need to do is encode the text in a code sample to a playground URL.

(Moved this to the `eslint` repo, because this has to do with the documentation site and not the primary website.)

**Comment by JoshuaKGoldberg** [comment]
> design to evaluate

How about floating to the right of the h1 on desktop, and below the rule categories on mobile? 

<table>
<thead>
<tr>
<th>Desktop</th>
<th>Mobile</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<img width="799" alt="Screenshot of the constructor-super page on desktop with 'Try this rule in the playground ↗' right aligned next to the main h1 title" src="https://user-images.githubusercontent.com/3335181/227720914-6458c3f3-ee11-42a2-8df5-882fe856d6a5.png">
</td>
<td>
<img width="530" alt="Screenshot of the constructor-super page on mobile with 'Try this rule in the playground ↗' below rule categories" src="https://user-images.githubusercontent.com/3335181/227721028-12f4118d-5315-4187-8b98-f3c24b940d21.png">
</td>
</tr>
</tbody>
</table>

I am not a designer 😄

**Comment by nzakas** [comment]
I just wonder if the "Open in Playground" on the examples is a better approach than a link at the top?

**Comment by JoshuaKGoldberg** [comment]
Ah, +1 to having the "Open in Playground" on the examples. I think I'd misinterpreted your comment on why it was removed.

> distinguish between rule code samples and others

Do you have examples of what you mean by each? As in, what would a code block that you _wouldn't_ want opened in the playground look like?

**Comment by nzakas** [comment]
> Do you have examples of what you mean by each? As in, what would a code block that you wouldn't want opened in the playground look like?

Literally any code block on any page other than rule pages. :)

**Comment by harish-sethuraman** [comment]
Are we going to add these `Open in Playground` button to all codeblocks? or only on some(first) codeblocks? I feel like it would be good if we add this near the rule's heading 😅 .

**Comment by amareshsm** [comment]
> > Do you have examples of what you mean by each? As in, what would a code block that you wouldn't want opened in the playground look like?
> 
> Literally any code block on any page other than rule pages. :)

If we are going to add `open in playground` link to code samples then do we need a mini playground ?https://github.com/eslint/eslint/issues/16227#issuecomment-1228719221

**Comment by sam3k** [comment]
This is a really nice addition to the already great `rules` docs!

**Comment by JoshuaKGoldberg** [comment]
> Literally any code block on any page other than rule pages. :)

Oh, great, my interpretation then is that all code blocks on rule pages are good to go for this. Can do!

> If we are going to add `open in playground` link to code samples then do we need a mini playground ?[#16227 (comment)](https://github.com/eslint/eslint/issues/16227#issuecomment-1228719221)

I'd suggest including both. A mini playground on the page isn't the same full experience as a shareable playground. Both are nice conveniences with overlapping but different sets of purposes IMO.

**Comment by nzakas** [comment]
> Are we going to add these Open in Playground button to all codeblocks? or only on some(first) codeblocks? I feel like it would be good if we add this near the rule's heading 😅 .

@harish-sethuraman Sorry, I'm not sure what this means. Are you saying add a codeblock near the heading?

I don't think adding a button near the heading like @JoshuaKGoldberg suggested makes much sense, either design-wise (there's not enough room) or usability wise (not enough context).

> If we are going to add open in playground link to code samples then do we need a mini playground ?https://github.com/eslint/eslint/issues/16227#issuecomment-1228719221

@amareshsm Definitely not. This would just link out to the current playground. At some point it would be great to have a mini playground; this button was seen as a stepping stone in that direction. The idea was to create a [web component](https://github.com/eslint/eslint/issues/15561) that anyone could use, but we just haven't been able to prioritize that work.

**Comment by sam3k** [comment]
Maybe this is something that can discuss in the next TSC meeting? Adding the label.

**Comment by nzakas** [comment]
@sam3k This discussion hasn't stalled out, so it's too early to add to the TSC meeting.

Also, when flagging something for the TSC meeting, please provide the **TSC Summary** summarizing the issue and explaining where conversation stalled, and also the **TSC Question**, which is what the TSC should decide. See: https://eslint.org/docs/latest/maintain/manage-issues#when-to-send-to-tsc

**Comment by sam3k** [comment]
That makes sense. Will do moving forward.

**Comment by mdjermanovic** [comment]
I agree it would be best to have an "Open in Playground" link on all correct and incorrect examples in rule docs. With that, I don't think we need an extra link at the top.

Those code blocks are already wrapped in [`::: incorrect`](https://github.com/eslint/eslint/blob/d85efad655deacc0dc3fdbbace33307094c3b91b/docs/src/rules/accessor-pairs.md?plain=1#L59) and [`::: correct`](https://github.com/eslint/eslint/blob/d85efad655deacc0dc3fdbbace33307094c3b91b/docs/src/rules/accessor-pairs.md?plain=1#L83) containers, which render as `<div class="incorrect">` and `<div class="correct">` so perhaps we could use that to locate them on the page. Or maybe add the links in build time.

**Comment by mdjermanovic** [comment]
> Because you can use inline comments to configure options, all we really need to do is encode the text in a code sample to a playground URL.

We might still need some metadata. For instance, examples for `no-restricted-imports` need `sourceType: "module"`, while this example for `no-implicit-globals` needs `sourceType: "script"` (it wouldn't be _incorrect_ with `sourceType: "module"`):

https://github.com/eslint/eslint/blob/d85efad655deacc0dc3fdbbace33307094c3b91b/docs/src/rules/no-implicit-globals.md?plain=1#L45-L57

**Comment by Rec0iL99** [comment]
Folks, looks like the discussion stalled a bit. How do we move forward here?

cc @eslint/eslint-team

**Comment by amareshsm** [comment]
Since most people like the idea and I also think the same it would be great if we have a link to open a rule in the playground. We can try it out and see. @mdjermanovic thoughts?

**Comment by mdjermanovic** [comment]
> Since most people like the idea and I also think the same it would be great if we have a link to open a rule in the playground. We can try it out and see. @mdjermanovic thoughts?

I'm in favor of adding an "Open in Playground" button to code blocks that represent correct and incorrect examples for rules.

**Comment by amareshsm** [comment]
Conclusion: we can add an "open in playground" button to correct/incorrect code examples. @JoshuaKGoldberg would you like to start working on this?

**Comment by JoshuaKGoldberg** [comment]
Yes, I'd love to - thanks!

Very cool to see the open discussion in the thread here. If & when this lands, I'll try to bring it up with the other folks at typescript-eslint to see if we want to follow suit.

**Comment by mdjermanovic** [comment]
Implemented in https://github.com/eslint/eslint/pull/17306
