### ISSUE TITLE
Bug: array-bracket-newline schema not updated?

### ISSUE THREAD

**Issue by whatwhywhenandwho** [eslint/eslint#17017]
### Environment

eslint . --config ./setup/lint/configurations/eslint.configuration.js --no-eslintrc --ext=ts,js,json

### What parser are you using?

Other

### What did you do?

If you look at `array-bracket-newline.js`, it's mentioning `ArrayExpression` and `ArrayPattern` in the code, but not the `schema`. Shouldn't it be updated to something like we can see in `array-element-newline.js`?

### What did you expect to happen?

The code should work as implemented.

### What actually happened?

The code didn't work as implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by whatwhywhenandwho** [comment]
@mdjermanovic If you look at [array-bracket-newline](https://github.com/eslint/eslint/blob/main/lib/rules/array-bracket-newline.js), you'll see that it's referring to `ArrayExpression` and `ArrayPattern` in the code, exactly the same way as [array-element-newline](https://github.com/eslint/eslint/blob/main/lib/rules/array-element-newline.js) does. However, if you look at `meta.schema`, you'll see that `ArrayExpression` and `ArrayPattern` aren't defined in [array-bracket-newline](https://github.com/eslint/eslint/blob/main/lib/rules/array-bracket-newline.js). Hence passing them as an option fails. Long story short: it seems that the functionality is implemented, but isn't allowed as input 🙂

This is what we're trying to do:

	'array-bracket-newline': [
		'error',
		{
			'ArrayExpression': 'always'
		}
	]

Or are we missing something?

**Comment by mdjermanovic** [comment]
Thanks for providing more info!

`array-bracket-newline` works for both array expressions and array patterns (that's what you can see in the source code), but unlike `array-element-newline` this rule wasn't designed to provide a way to configure the behavior separately for array expressions and array patterns. Since the core stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates), we are not adding new options to this rule, but you can always copy the core rule into a custom rule and make it behave the way you want.

**Comment by whatwhywhenandwho** [comment]
@mdjermanovic I didn't look into how I could do this yet, but based on your professional estimation, are we talking pretty much just about updating meta to allow the nuanced options?

Also, is a backward compatible PR on this repository an option?

**Comment by whatwhywhenandwho** [comment]
In case someone's wondering, I forked and fixed this, it took 15 minutes. I'm gonna push it in case I get a response here that PRs are welcome.

**Comment by mdjermanovic** [comment]
> are we talking pretty much just about updating `meta` to allow the nuanced options?

Updating `meta.schema` only changes the validation of options. You'll also need to update the code that determines how the rule should behave based on the options.

> Also, is a backward compatible PR on this repository an option?

Per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates), we're not accepting new options for this rule.
