### ISSUE TITLE
missing globals: phantom, jquery, prototypejs, shelljs

### ISSUE THREAD

**Issue by valorkin** [eslint/eslint#1704]
I am using eslint from master branch
And I really missing an option to include `phantom`, `jquery`, `prototypejs`, `shelljs`
as environment settings

resolved in:
https://github.com/eslint/eslint/pull/1697
and
https://github.com/sindresorhus/globals/pull/18 - merged

**Comment by nzakas** [comment]
Why is it `phantom` instead of `phantomjs` to match the others?

**Comment by lo1tuma** [comment]
@nzakas we also have `node` instead of `nodejs`.

**Comment by nzakas** [comment]
Yeah, I copied that from JSHint. :) I don't think we can change it at this point, though we could certainly add `nodejs` as an alias.

**Comment by remitbri** [comment]
Shouldn't conf/eslint.json be updated to included the new globals in the environment setting?

**Comment by nzakas** [comment]
No. Environments are not handled in that for.
