### ISSUE TITLE
Bug: Issue with eslint 8.38.0 not showing lints in WebStorm

### ISSUE THREAD

**Issue by dimassibassem** [eslint/eslint#17077]
### Environment

Node version: v18.13.0
npm version: v8.19.3
Local ESLint version: v8.38.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22000

### What parser are you using?

Default (Espree)

### What did you do?

I have been using WebStorm for my JavaScript projects and have recently updated eslint to version 8.38.0. However, I am facing issues with eslint not showing any lints in WebStorm.

The issue I am facing is that WebStorm is not recognizing eslint 8.38.0 and is not displaying any lints in the editor. I have tried reinstalling eslint and even tried clearing the cache, but the issue persists.

This issue is preventing me from using the latest version of eslint with WebStorm, and I would appreciate any help in resolving this issue.

### What did you expect to happen?

WebStorm should recognize and use eslint version 8.38.0.

### What actually happened?

WebStorm is not showing any eslint lints in the editor.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @dimassibassem, thanks for the issue. Can you please try downgrading to a version other than `8.38.0` and check if everything works as expected? Please report back with your findings.

I think opening an issue at [WebStorm's issue tracker](https://youtrack.jetbrains.com/issues) should help you better since the ESLint team does not maintain the WebStorm integration.

**Comment by dimassibassem** [comment]
Hi @Rec0iL99, yeah I try 8.36.0 and it works properly.
Okay than thank you for your time, I will report that issue to webstorm

**Comment by Rec0iL99** [comment]
Thanks @dimassibassem, please mention the issue tracker number here for us to track and maybe make sure it's not a problem with ESLint.

**Comment by aladdin-add** [comment]
Have you tried to run the eslint cli? If it's working fine, then it's mostly an issue of the integration.

**Comment by nzakas** [comment]
v8.38.0 is a fairly small release, and I don't see anything that could potentially be a problem for an integration. Definitely let us know if there's a WebStorm issue we can watch.

**Comment by nzakas** [comment]
Marking as a patch candidate in case some change is needed. If we don't hear back by the end of the today then we'll move on.

**Comment by nzakas** [comment]
No other reports on this, so removing as a patch candidate. 

If no followup within the next seven days, we can close this.

**Comment by aladdin-add** [comment]
> If no followup within the next seven days, we can close this.

well, I'm closing it. :)
