### ISSUE TITLE
New Rule: enforce if conditions to be boolean

### ISSUE THREAD

**Issue by fansanelli** [eslint/eslint#17083]
### Rule details

To check that every if condition is boolean (or a function returning boolean)

### Related ECMAScript feature

if...else

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
let a = 1;
if (a) do something...

should become:

let a = 1;
if (a !== 0) do something...
```

### Why should this rule be in the core instead of a plugin?

Because testing an object, an array or a number may be confusing and lead unwanted behaviours.
This improves readability mostly, but may also avoid potential bugs, as done in other languages like Java.
The same rule could be extended to while conditions too.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by mdjermanovic** [comment]
Hi @fansanelli, thanks for the issue!

> To check that every if condition is boolean (or a function returning boolean)

Core rules don't have type information to be able to enforce this preference, so this rule doesn't seem feasible.

**Comment by fansanelli** [comment]
I opened in typescript plugin: https://github.com/typescript-eslint/typescript-eslint/issues/6898
sorry the noise
Cheers
