### ISSUE TITLE
Bug: `.eslintrc.js` is ignored again

### ISSUE THREAD

**Issue by tomalec** [eslint/eslint#17090]
### Environment

Node version: v16.19.0
npm version: 8.19.3
Local ESLint version: 8.38.0
Global ESLint version: 8.38.0
Operating System: Ubuntu 22

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
  env: {
    browser: true,
    es2021: true
  },
  extends:"standard-with-typescript",
  overrides: [
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module'
  },
  rules: {
  }
}

```
</details>

I try to make ESLint check its own config (`.eslintrc.js`) as well.
```
eslint .eslintrc.js
```
Therefore as you can see above, in the default config, I changed `extends:"standard-with-typescript",` to a non-compliant format.

### What did you expect to happen?

According to [the docs](https://github.com/eslint/eslint/blob/1fea2797801a82a2718814c83dad641dab092bcc/docs/src/use/configure/ignore.md):

>  dot-files (**except for `.eslintrc.*`**) as well as dot-folders and their contents are ignored.

### What actually happened?

`eslint .eslintrc.js` shows no message and does not check the file

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/js-jcaye9?file=.eslintrc.js%3AL6&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

It seems either a regression was introduced in https://github.com/eslint/eslint/pull/16678/files#diff-a32a0887ed9d1d707bbb3b845b7df7fd40e673c47e7b60a3ebd896b68d3b8839L95 or the docs are not up to date.

**Comment by aladdin-add** [comment]
if it was passed a file which has been ignored, it will output a warning like this:
```bash
/home/projects/node-5szqnh/.foo.js
  0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

✖ 1 problem (0 errors, 1 warning)
```

can you try `eslint --debug` or `eslint --print-config`, and share the output?

**Comment by tomalec** [comment]
Thank you for the quick answer!

Sorry, my bad, today `eslint .eslintrc.js` & `eslint **/*.js` work as expected :confused: I was sure I tried it this way yesterday.

However, `eslint ./*.js` does not. I thought both `./*.js` and `**/*.js` should match the `.eslintrc.js` from the CWD.
