### ISSUE TITLE
Change Request: Support nested comment syntax for `eslint-disable-line`

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#17109]
### ESLint version

v8.38.0

### What problem do you want to solve?

ESLint currently does not recognize a `eslint-disable-line` comment when it is "nested" inside another comment. See [playground example](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgZm9vID0gMTsgLy8gY29tbWVudCAvLyBlc2xpbnQtZGlzYWJsZS1saW5lIG5vLXVudXNlZC12YXJzIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJvYmplY3QtcHJvcGVydHktbmV3bGluZSI6WyJlcnJvciIseyJhbGxvd0FsbFByb3BlcnRpZXNPblNhbWVMaW5lIjp0cnVlLCJhbGxvd011bHRpcGxlUHJvcGVydGllc1BlckxpbmUiOmZhbHNlfV0sImluZGVudCI6WyJlcnJvciIsMl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19). It would be useful so adding a new eslint directive always is a 1-line change while preserving original comments in the code.

```js
const foo = 1; // comment // eslint-disable-line no-unused-vars
```

### What do you think is the correct solution?

When parsing comments, check for the `//` sequence, and if present cut the comment string via from the last occurence of `//` inside it before parsing it for eslint directives.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
it has supported something like

```js
const foo = 1; // eslint-disable-line no-unused-vars -- some desc...
```

https://eslint.org/docs/latest/use/configure/rules#configuration-comment-descriptions, it's what you are looking for?

**Comment by silverwind** [comment]
My goal is to add a eslint directive with the least amount of changes necessary and without disturbing existing comments. Take this example:

```js
const a = 1; // foo
const b = 2; // bar
const e = 3; // baz
```

With current mechanism, the alignment of comments is disturbed:

```js
const a = 1; // foo
const b = 2; // eslint-disable-line no-unused-vars -- bar
const e = 3; // baz
```

With my proposed mechanism, adding a comment is a simple "insert" action:

```js
const a = 1; // foo
const b = 2; // bar // eslint-disable-line no-unused-vars
const e = 3; // baz
```

**Comment by aladdin-add** [comment]
well, I think this kind of change needs a rfc: https://github.com/eslint/rfcs.

**Comment by silverwind** [comment]
Guess I could do that later.

**Comment by silverwind** [comment]
Actually, I don't think I care enough about this to pursue further.
