### ISSUE TITLE
Bug: ESLint Not Activating in Visual Studio 2022

### ISSUE THREAD

**Issue by Sothecom** [eslint/eslint#17119]
### Environment

Node version: v18.8.0
npm version: v8.18.0
Local ESLint version: v8.39.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Other

### What did you do?

I am using Visual Studio 2022

I installed ESLint using npm install eslint in the Package Manager Console

I enabled it the tools options for the solution and also verified it is enabled for the Angular project I am working on.

### What did you expect to happen?

When I open the Solution, I expect the Activating language client indicator complete.

Then is within the code a commit a violation e.g. leave off comma, I expect to see the violation indicated

### What actually happened?

The Activating language client indicator does not appear to progress past some unknown initial step in the process.
The process text shown is Activating language client: ESLint language extension.

No linting issues are highlighted.

### Link to Minimal Reproducible Example

https://github.com/Sothecom/app/blob/master/src/static/MicrosoftTeams-image.png

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @Sothecom, thanks for the issue!

This seems to be an issue with the Visual Studio's integration, not ESLint itself. Please report the problem to the Visual Studio support team.
