### ISSUE TITLE
Rule Change: make `spaced-comment` language agnostic, add new option `commentSymbol`

### ISSUE THREAD

**Issue by B2o5T** [eslint/eslint#17145]
### What rule do you want to change?

spaced-comment

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

ESLint's `spaced-comment` works well with `graphql-eslint` but has some issues while auto-fixing code.

GraphQL comments can be declared with `#` rather than `//` or `/*` in JavaScript

Follow code is never fixed

```graphql
fragment Test on User { #foo
  name ##bar
} ###baz
```

due to this line https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/spaced-comment.js#L284

where `2` stays for the length of comments symbols

### What does the rule currently do for this code?

ESLint try to autofix until reach max autofix limit.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/7361780/235930226-80291630-77ce-4917-8fc2-a93edfe4c54e.png">

### What will the rule do after it's changed?

calculate `magic number` https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/spaced-comment.js#L284
based on the new option `commentSymbol` and generate a new error message.

Currently, ESLint reports an error message:
```sh
Expected space or tab after '//' in comment.
```
But it will report with `{ commentSymbol: '#' }`
```sh
Expected space or tab after '#' in comment.
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

https://github.com/B2o5T/graphql-eslint/issues/1191#issuecomment-1531878179

**Comment by mdjermanovic** [comment]
Hi @B2o5T, thanks for the issue!

Core rules only support JavaScript syntax. For other languages, you can always make a custom rule.

**Comment by sharmilajesupaul** [comment]
> Core rules only support JavaScript syntax. For other languages, you can always make a custom rule.

@mdjermanovic would you take a PR to limit this rule to acting on JS comment characters then?

Right now it's recognizing `#` as a comment character in graphql files and breaks adds the space in the incorrect location.

**Comment by B2o5T** [comment]
@sharmilajesupaul you should not run this rule for your `graphql` files in this case

**Comment by sharmilajesupaul** [comment]
@B2o5T alright,  i guess that's an ok workaround for now
