### ISSUE TITLE
Change Request: Support async postprocessors (and maybe preprocessors) so you can ignore old code based on git

### ISSUE THREAD

**Issue by emattias** [eslint/eslint#17146]
### ESLint version

v8.34

### What problem do you want to solve?

I want to be able to, as performant as possible, ignore certain rules on lines that are done before a certain commit. We have found that this is our preferred method of adopting a new lint rule in a big code base.

We do this with an async `resultProcessors` in stylelint and saw a big difference between being able to run it async vs sync.

### What do you think is the correct solution?

Support async processors so you can can in a postprocessor loop through all messages and in parallel run the git check for all of them instead of having to do them all synchronously with `execSync` or similar.

### Additional comments

Here's an example of what we want to use it for. 

If you could have async postprocessors we could switch out all `execSync` with `await exec` and have one `await Promise.all` for all messages and all they would run in parallel which can make a big difference when a rule has alot of errors (which is when this ignoring based on the lines change date is more likely to be needed):

```js
const { execSync } = require('child_process');

const limitCommitSha = '666379f508cd727a4fcc4ae7e734875643181cdd';
const stdout = execSync(`git show -s --format=%ci ${limitCommitSha}`, {
  encoding: 'utf8',
});
const limitDate = stdout.trim();

const processors = {
  postprocess(_messages, filePath) {
    let messages = [].concat(..._messages);

    return messages.reduce((acc, message) => {
      const { line, ruleId } = message;
      if (ruleId === '@typescript-eslint/no-restricted-imports') {
        const isInIndex = !!execSync(`git ls-files "${filePath}"`, {
          encoding: 'utf8',
        }).trim();

        if (!isInIndex) {
          return messages;
        }

        let includeMessage = true;
        const stdout = execSync(
          `git blame -L ${line},${line} "${filePath}" -p --since="${limitDate}"`,
          {
            encoding: 'utf8',
          }
        );
        let lineSplitted = stdout.split('\n');
        let [lineCommitSha] = stdout.split(' ');

        const lineIsUncommited =
          lineCommitSha === '0000000000000000000000000000000000000000';

        if (lineIsUncommited) {
          includeMessage = true;
        } else {
          const isBoundaryCommit = lineSplitted.find(
            (line) => line === 'boundary'
          );
          const isLimitCommitOrBefore =
            isBoundaryCommit || limitCommitSha === lineCommitSha;

          if (isLimitCommitOrBefore) {
            includeMessage = false;
          }
        }

        if (includeMessage) {
          acc.push(message);
        }
      } else {
        acc.push(message);
      }

      return acc;
    }, []);
  },
};

module.exports = {
  processors: {
    '.ts': processors,
    '.js': processors,
  },
};
```

**Comment by sam3k** [comment]
Hi @emattias, for those of us not too familiar with `stylelint` `resultProcessors` can you point us to some documentation?

Given that this might be a big rewrite, would you:

1. Submit an RFC if the team ask for one?
2. Be willing to champion/submit a PR to implement async processors if request accepted?
3. Do you think this change could be backwards compatible?

**Comment by sam3k** [comment]
Closing issue as I haven't heard from author.
