### ISSUE TITLE
Bug: queue-microtask was not installed in my workspace

### ISSUE THREAD

**Issue by BerendKemper** [eslint/eslint#17147]
### Environment

Node version: v18.2.0
npm version: 9.6.5
Local ESLint version: 8.39.0
Operating System: Windows

### What parser are you using?

Default (Espree)

### What did you do?

ESLint was no longer formatting code or checking for errors. 

I went into the OUTPUT from VS code.
The error logged that `queue-microtask` was not found. 
A certain file called `./node_modules\run-parallel\index.js` requires `queue-microtask`.

```
Require stack:
- .\node_modules\run-parallel\index.js
- .\node_modules\@nodelib\fs.scandir\out\providers\async.js
- .\node_modules\@nodelib\fs.scandir\out\index.js
- .\node_modules\@nodelib\fs.walk\out\readers\async.js
- .\node_modules\@nodelib\fs.walk\out\providers\async.js
- .\node_modules\@nodelib\fs.walk\out\index.js
- .\node_modules\eslint\lib\eslint\eslint-helpers.js
- .\node_modules\eslint\lib\eslint\flat-eslint.js
- .\node_modules\eslint\lib\eslint\index.js
- .\node_modules\eslint\lib\api.js
- ~\.vscode\extensions\dbaeumer.vscode-eslint-2.4.0\server\out\eslintServer.js
```

`[Error - 5:41:35 PM] Error: Cannot find module 'queue-microtask'` Typically node js error when a module is required but was not installed. The Error prevents ESLint to run it's service.

I figured i needed to run `npm i queue-microtask` in order to solve this issue. 
After that ESLint worked again.

### What did you expect to happen?

I expected that ESLint would work.

### What actually happened?

ESLint was no longer formatting code or checking for errors.

### Link to Minimal Reproducible Example

https://github.com/Massarius

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The GitHub repository is private.

**Comment by nzakas** [comment]
This error is coming from the Visual Studio Code extension, not ESLint itself.
