### ISSUE TITLE
Add fix to resolve this issue automatically

### ISSUE THREAD

**Issue by fernandocm121** [eslint/eslint#17177]
### What rule do you want to change?

max-statements-per-line

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

Currently when we have two statements in a row, there is no fix to solve the problem automatically.
The resolution in this case would be to break a line.

An example would be this:
### Example code

```js
const a = true
function teste () {
  if(a) { return }
}
```

### What does the rule currently do for this code?

Just alert the error

### What will the rule do after it's changed?

will allow automatic resolution of the problem, with the line break

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by Rec0iL99** [comment]
Hi, @fernandocm121, thanks for the suggestion. We currently aren't adding any new options to stylistic rules due to the [policy change](https://github.com/eslint/eslint#stylistic-rule-updates). You can always copy the existing core rule into a custom rule and add options.
