### ISSUE TITLE
Bug: `YAMLException: end of the stream or a document separator is expected` when using `eslint.config.mjs` flat-config

### ISSUE THREAD

**Issue by pubmikeb** [eslint/eslint#17180]
### Environment

Node version: `20.1.0`
npm version: `9.6.6`
Local ESLint version: `8.40.0`

### What parser are you using?

Default (Espree)

### What did you do?

I've migrated to the flat-config.
Everything was OK, until I switched from `eslint.config.js` to `eslint.config.mjs` and added:

```bash
-c C:\IdeaProjects\%PATH%\devops\eslint.config.mjs src/**
```

as it's described in [Configuration File Resolution](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file-resolution) and https://github.com/eslint/eslint/issues/17178.

The `eslint.config.mjs` configuration:

```js
export default [{
	files: ["**/*.*js", "**/*.*ts"],
	rules: {
		"accessor-pairs": "error"
	}
}];
```

### What did you expect to happen?

The linting will be accomplished exactly, as it used to be when using `eslint.config.js`.

### What actually happened?

I got:

```bash
YAMLException: end of the stream or a document separator is expected (2:7)

 1 | export default [{
 2 | →files: ["**/*.*js", "**/*.*ts"],
-----------^
 3 | →rules: {
 4 | →→"accessor-pairs": "error",

YAMLException: Cannot read config file: C:\IdeaProjects\%PATH%\devops\eslint.config.mjs
Error: end of the stream or a document separator is expected (2:7)

 1 | export default [{
 2 | →files: ["**/*.*js", "**/*.*ts"],
-----------^
 3 | →rules: {
 4 | →→"accessor-pairs": "error",
    at generateError (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:187:9)
    at readDocument (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1645:5)
    at loadDocuments (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1714:19)
    at loadLegacyConfigFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2544:21)
    at loadConfigFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2659:20)
    at ConfigArrayFactory._loadConfigData (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2963:42)
    at ConfigArrayFactory.loadFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2829:40)
    at createCLIConfigArray (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3637:35)
```

When I run linting from the IDE's terminal, I get:

```bash
PS C:\IdeaProjects\%PATH%> eslint -c C:\IdeaProjects\%PATH%\eslint.config.mjs src/**

Oops! Something went wrong! :(

ESLint: 8.40.0

YAMLException: Cannot read config file: C:\IdeaProjects\%PATH%\eslint.config.mjs       
Error: end of the stream or a document separator is expected (2:7)

 1 | export default [{
 2 | →files: ["**/*.*js", "**/*.*ts"],
-----------^
 3 | →rules: {
 4 | →→"accessor-pairs": "error",
    at generateError (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:187:9)    
    at readDocument (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1645:5) 
    at loadDocuments (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (C:\IdeaProjects\%PATH%\node_modules\js-yaml\lib\loader.js:1714:19)
    at loadLegacyConfigFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2544:21)
    at loadConfigFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2659:20)
    at ConfigArrayFactory._loadConfigData (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2963:42)
    at ConfigArrayFactory.loadFile (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2829:40)
    at createCLIConfigArray (C:\IdeaProjects\%PATH%\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3637:35)
```

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgdGVzdCA9IGZ1bmN0aW9uIHRlc3QoKSB7XG5cdGNvbnNvbGUubG9nKFwiSGVsbG8gd29ybGQhXCIpO1xufTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjIwMjIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbImVycm9yIl0sIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1lbXB0eS1wYXR0ZXJuIjpbImVycm9yIl0sIm5vLWV4LWFzc2lnbiI6WyJlcnJvciJdLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOlsiZXJyb3IiXSwibm8tZXh0cmEtc2VtaSI6WyJlcnJvciJdLCJuby1mYWxsdGhyb3VnaCI6WyJlcnJvciJdLCJuby1mdW5jLWFzc2lnbiI6WyJlcnJvciJdLCJuby1nbG9iYWwtYXNzaWduIjpbImVycm9yIl0sIm5vLWltcG9ydC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW5uZXItZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWludmFsaWQtcmVnZXhwIjpbImVycm9yIl0sIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjpbImVycm9yIl0sIm5vLWxvc3Mtb2YtcHJlY2lzaW9uIjpbImVycm9yIl0sIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6WyJlcnJvciJdLCJuby1uZXctc3ltYm9sIjpbImVycm9yIl0sIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjpbImVycm9yIl0sIm5vLW9iai1jYWxscyI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOlsiZXJyb3IiXSwibm8tcmVkZWNsYXJlIjpbImVycm9yIl0sIm5vLXJlZ2V4LXNwYWNlcyI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOlsiZXJyb3IiXSwibm8tdW5kZWYiOlsiZXJyb3IiXSwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOlsiZXJyb3IiXSwibm8tdW5yZWFjaGFibGUiOlsiZXJyb3IiXSwibm8tdW5zYWZlLWZpbmFsbHkiOlsiZXJyb3IiXSwibm8tdW5zYWZlLW5lZ2F0aW9uIjpbImVycm9yIl0sIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6WyJlcnJvciJdLCJuby11bnVzZWQtbGFiZWxzIjpbImVycm9yIl0sIm5vLXVudXNlZC12YXJzIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtYmFja3JlZmVyZW5jZSI6WyJlcnJvciJdLCJuby11c2VsZXNzLWNhdGNoIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtZXNjYXBlIjpbImVycm9yIl0sIm5vLXdpdGgiOlsiZXJyb3IiXSwicmVxdWlyZS15aWVsZCI6WyJlcnJvciJdLCJ1c2UtaXNuYW4iOlsiZXJyb3IiXSwidmFsaWQtdHlwZW9mIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlLCJlczIwMjEiOnRydWV9fX0=

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @pubmikeb, thanks for the issue. Did you set the `ESLINT_USE_FLAT_CONFIG ` environment variable to `true`? This is required.

**Comment by Rec0iL99** [comment]
@pubmikeb can you please provide a small reproducible example for me to try out? Thanks.

**Comment by Rec0iL99** [comment]
@pubmikeb, thanks for the example and detailed info. I couldn't reproduce the errors you got and these were the steps I followed. 

I first ran the `linting_default` script and ESLint worked as expected.

```bash
> npm run linting_default

> linting_default
> eslint src/**


/Users/joelmathew/Desktop/ESLINT-17180/src/app.mjs
  1:7   error  'boo' is assigned a value but never used         no-unused-vars
  1:29  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  3:2   error  Unexpected var, use let or const instead         no-var
  3:6   error  'test' is assigned a value but never used        no-unused-vars
  3:19  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  4:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  5:2   error  Unexpected console statement                     no-console
  5:2   error  'console' is not defined                         no-undef
  5:30  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  6:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  7:3   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 12 problems (12 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
```

For running the `linting_JS` script I first changed the absolute path to the relative path of `eslint.config.js`. I removed the `root/eslint.config.js` like you mentioned.

```json
"linting_JS": "eslint -c devops/eslint.config.js src/**",
```

I then added `ESLINT_USE_FLAT_CONFIG=true` in my environment as the [docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file-resolution) mention.

```bash
export ESLINT_USE_FLAT_CONFIG=true
```

**Result:**

```bash
> npm run linting_JS                                                                                                                                                                                                         

> linting_JS
> eslint -c devops/eslint.config.js src/**


/Users/joelmathew/Desktop/ESLINT-17180/src/app.mjs
  1:7   error  'boo' is assigned a value but never used         no-unused-vars
  1:29  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  3:2   error  Unexpected var, use let or const instead         no-var
  3:6   error  'test' is assigned a value but never used        no-unused-vars
  3:19  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  4:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  5:2   error  Unexpected console statement                     no-console
  5:2   error  'console' is not defined                         no-undef
  5:30  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  6:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  7:3   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 12 problems (12 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
```

I followed the same steps for the `linting_MJS` script.

**Result:**

```bash
> npm run linting_MJS                                                                                                                                                                                                       

> linting_MJS
> eslint -c devops/eslint.config.mjs src/**


/Users/joelmathew/Desktop/ESLINT-17180/src/app.mjs
  1:7   error  'boo' is assigned a value but never used         no-unused-vars
  1:29  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  3:2   error  Unexpected var, use let or const instead         no-var
  3:6   error  'test' is assigned a value but never used        no-unused-vars
  3:19  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  4:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  5:2   error  Unexpected console statement                     no-console
  5:2   error  'console' is not defined                         no-undef
  5:30  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  6:1   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  7:3   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 12 problems (12 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
```

ESLint is working as expected. I think you might have not set the environment variable `ESLINT_USE_FLAT_CONFIG` properly.

**Comment by Rec0iL99** [comment]
@pubmikeb I don't think the `ESLINT_USE_FLAT_CONFIG ` will be required once we fully migrate to flat config. You can track the progress of flag config implementation here #13481.
