### ISSUE TITLE
es6 arrow function support

### ISSUE THREAD

**Issue by dmnd** [eslint/eslint#1720]
Are arrow functions supported? I saw some issues from late last year that seemed to indicate they should work, but:

```
$ echo 'var fn = x => 1;' > test.js

$ eslint test.js 

test.js
  1:13  error  Unexpected token >

✖ 1 problem
```

I'm running from master (for as much ES6 support as I can get) and have all option enabled. Arrow functions aren't an option, so I'm guessing they're not supported yet. But I thought it was worth checking.

**Comment by nzakas** [comment]
No, please refer to the documentation to see which ES6 pieces are currently supported: http://eslint.org/docs/configuring

When the parser support is there, we'll support it too.

**Comment by dmnd** [comment]
Cool. Thanks for your work on this!

For anyone else reading this, heslint/espree/issues/10 is how you can track which ES6 features are in the parser.
