### ISSUE TITLE
Bug: Documentation licensed under non-OSS compatible license

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#17225]
## Background

We had a request to apply a license to our documentation, and even though this project is MIT licensed, I mistakenly thought that applied only to code and not to documentation. In fact, the MIT license specifically says that it also applies to the documentation (always read your licenses, folks!).

https://github.com/eslint/eslint/discussions/17175 mentions that the CC license we applied is incompatible with open source licenses, which is true (verified by OpenJS legal). Some software scanners will flag this and mark the repo as not open source (technically incorrect, but scanners err on the side of false positives to be safe). Others can't contribute when there is a question about licensing.

So this was my mistake, and we should fix it ASAP.

## Potential Solution

Because the MIT license actually does cover the documentation, the easiest path forward is to revert back to that and just make it clear by replacing all references to the CC license with references to the MIT license.

The steps would be:

1. Find all documentation-related commits since https://github.com/eslint/eslint/pull/17010 was merged.
2. Revert those documentation commits.
3. Revert https://github.com/eslint/eslint/pull/17010.
4. Ask people to resubmit the documentation from the removed commits.

It's kind of a pain, but it's the technically correct approach to this problem.

**Comment by nzakas** [comment]
@mdjermanovic interested to hear your thoughts on this.

**Comment by mdjermanovic** [comment]
If that's the technically correct approach to the problem, then we should do it.

We should probably also not merge any other documentation-related PRs until we finish step 3.

**Comment by mdjermanovic** [comment]
> 1. Find all documentation-related commits since [feat: docs license #17010](https://github.com/eslint/eslint/pull/17010) was merged.

Commits that had changes in the `docs/` folder:

* https://github.com/eslint/eslint/commit/7a2a0bed1bcded9461e8432aa09d754431d8725b (bot commit)
* https://github.com/eslint/eslint/commit/880a4317b949e575a4a6c5e8baaba1eea7674cc6 (https://github.com/eslint/eslint/pull/17184)
* https://github.com/eslint/eslint/commit/94da96cbf0fb2bb6694fa2e757eb1b3e74c40db7 (https://github.com/eslint/eslint/pull/17076)
* https://github.com/eslint/eslint/commit/7f183e020579380fa57473caaf9ed154470c25b3 (https://github.com/eslint/eslint/pull/17157)
* https://github.com/eslint/eslint/commit/69a19c83e44ec7e75d17886529c6dee151d2c960 (bot commit)
* https://github.com/eslint/eslint/commit/e52b98bf25d882da4efd5559ce5974b6697cf701 (https://github.com/eslint/eslint/pull/17107)
* https://github.com/eslint/eslint/commit/1468f5b640cfa6fdd8a5ec895337f692def2780b (https://github.com/eslint/eslint/pull/17111)
* https://github.com/eslint/eslint/commit/0df4d4f658c214e51310a986c03d44d34ceae3ec (https://github.com/eslint/eslint/pull/17106)
* https://github.com/eslint/eslint/commit/52018f21c19b3e461cae32843cddd17ed42f19cd (https://github.com/eslint/eslint/pull/17108)
* https://github.com/eslint/eslint/commit/559ff4e4bc54a8b6e6b54825d83c532d724204b3 (https://github.com/eslint/eslint/pull/17105)
* https://github.com/eslint/eslint/commit/af5fe64c398c9bd4206c3c6c1ade81768b291031 (https://github.com/eslint/eslint/pull/17115)
* https://github.com/eslint/eslint/commit/4a352a957ba9e721bec9f6f403b419a22b0ec423 (https://github.com/eslint/eslint/pull/17114)
* https://github.com/eslint/eslint/commit/560e812d85d1805a59989f295c3a417609033f11 (bot commit)
* https://github.com/eslint/eslint/commit/6987dc59e46f4e345d0d6c20c1f2c6846bbd7acc (https://github.com/eslint/eslint/pull/17097)
* https://github.com/eslint/eslint/commit/3f7af9f408625dbc486af914706d34c4b483b5ba (https://github.com/eslint/eslint/pull/17086)
* https://github.com/eslint/eslint/commit/d8e9887c2c384d24d586d08ee9ae2ada79bd234c (https://github.com/eslint/eslint/pull/16906)
* https://github.com/eslint/eslint/commit/1fea2797801a82a2718814c83dad641dab092bcc (https://github.com/eslint/eslint/pull/17084)
* https://github.com/eslint/eslint/commit/970ef1c868235a58297682513842f1256cdfbd03 (direct commit)
* https://github.com/eslint/eslint/commit/198e5fca2327583bde284acd39e8107accbdcfad (bot commit)
* https://github.com/eslint/eslint/commit/7162d34df9a66c817c3bd4aafd3a03d226b58dd5 (https://github.com/eslint/eslint/pull/17068)
* https://github.com/eslint/eslint/commit/a1d561d18ed653b56bddbfb1bab1ebe957293563 (https://github.com/eslint/eslint/pull/17059)
* https://github.com/eslint/eslint/commit/c83531c1a6026675f36aa9e33fef14458043974a (https://github.com/eslint/eslint/pull/17061)
* https://github.com/eslint/eslint/commit/a3aa6f5f146534ed7999ebf8930c524a4871ec0b (https://github.com/eslint/eslint/pull/17051)
* https://github.com/eslint/eslint/commit/da8d52a9d4edd9b2016cd4a15cd78f1ddadf20c7 (https://github.com/eslint/eslint/pull/17020)
* https://github.com/eslint/eslint/commit/518130ae79a16d7bf4d752c211ae88152cc5a6f0 (https://github.com/eslint/eslint/pull/16687)
* https://github.com/eslint/eslint/commit/4c46fb3d861ca12e86f868af19778ce988238da7 (bot commit)
* https://github.com/eslint/eslint/commit/75339df99418df4d7e05a77e42ed7e22eabcc9e0 (https://github.com/eslint/eslint/pull/17029)
* https://github.com/eslint/eslint/commit/ec2d8307850dd039e118c001416606e1e0342bc8 (https://github.com/eslint/eslint/pull/17012)
* https://github.com/eslint/eslint/commit/e39f28d8578a00f4da8d4ddad559547950128a0d (https://github.com/eslint/eslint/pull/16979)
* https://github.com/eslint/eslint/commit/ad9dd6a933fd098a0d99c6a9aa059850535c23ee (https://github.com/eslint/eslint/pull/17005)
* https://github.com/eslint/eslint/commit/10022b1f4bda1ad89193512ecf18c2ee61db8202 (https://github.com/eslint/eslint/pull/16992)

**Comment by mdjermanovic** [comment]
Step 2: https://github.com/eslint/eslint/pull/17227

**Comment by nzakas** [comment]
> We should probably also not merge any other documentation-related PRs until we finish step 3.

Definitely. Ideally, we put the new license notice in place and ask people on existing PRs to rebase on top of main so the lineage is clear.

**Comment by aladdin-add** [comment]
step 3: https://github.com/eslint/eslint/pull/17231

**Comment by nzakas** [comment]
**TSC Summary:** This issue outlines the steps needed to fix our documentation license issue.

**TSC Question:** What is the plan for making these changes? Should it be done before, with, or after the release?

**Comment by mdjermanovic** [comment]
In the [2023-06-01 TSC Meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2023/2023-06-01.md), we decided to make these changes after the release (after we close the release issue https://github.com/eslint/eslint/issues/17210).

@ollie-iterators timing matters because merging https://github.com/eslint/eslint/pull/17227 makes docs being out-of-sync with the code and releases update the latest version of the docs at https://eslint.org/docs/latest with the content from the `main` branch. Now we have time to get the docs changes back into the `main` branch (step 4) before the next release.

**Comment by mdjermanovic** [comment]
Steps 1-3 are finished now.

> Definitely. Ideally, we put the new license notice in place and ask people on existing PRs to rebase on top of main so the lineage is clear.

@nzakas Should we put the new license notice now, before we ask people to resubmit the documentation from the removed commits and before we ask people to rebase existing PRs?

**Comment by nzakas** [comment]
Yes, let’s get the new license notice in before merging anything else.

**Comment by mdjermanovic** [comment]
Checklist for Step 4 is in https://github.com/eslint/eslint/issues/17225#issuecomment-1565613696

**Comment by mdjermanovic** [comment]
`docs/src/extend/custom-rules.md` had changes from multiple authors. Ordered by commit date, ascending:

1. https://github.com/eslint/eslint/commit/10022b1f4bda1ad89193512ecf18c2ee61db8202 (https://github.com/eslint/eslint/pull/17004) @nzakas
2. https://github.com/eslint/eslint/commit/a1d561d18ed653b56bddbfb1bab1ebe957293563 (https://github.com/eslint/eslint/pull/17059) @nzakas 
3. https://github.com/eslint/eslint/commit/d8e9887c2c384d24d586d08ee9ae2ada79bd234c (https://github.com/eslint/eslint/pull/16906) @bpmutter
4. https://github.com/eslint/eslint/commit/3f7af9f408625dbc486af914706d34c4b483b5ba (https://github.com/eslint/eslint/pull/17086) @nzakas 
5. https://github.com/eslint/eslint/commit/6987dc59e46f4e345d0d6c20c1f2c6846bbd7acc (https://github.com/eslint/eslint/pull/17097) @mdjermanovic 
6. https://github.com/eslint/eslint/commit/af5fe64c398c9bd4206c3c6c1ade81768b291031 (https://github.com/eslint/eslint/pull/17115) contributor
7. https://github.com/eslint/eslint/commit/52018f21c19b3e461cae32843cddd17ed42f19cd (https://github.com/eslint/eslint/pull/17108) @snitin315
8. https://github.com/eslint/eslint/commit/0df4d4f658c214e51310a986c03d44d34ceae3ec (https://github.com/eslint/eslint/pull/17106) @snitin315 
9. https://github.com/eslint/eslint/commit/1468f5b640cfa6fdd8a5ec895337f692def2780b (https://github.com/eslint/eslint/pull/17111) @snitin315 
10. https://github.com/eslint/eslint/commit/e52b98bf25d882da4efd5559ce5974b6697cf701 (https://github.com/eslint/eslint/pull/17107) @snitin315 

It might be easiest to resubmit the changes in the same order:

1 & 2 (@nzakas)  -> 3 (@bpmutter) -> 4 (@nzakas) -> 5 (@mdjermanovic) -> 7 & 8 & 9 & 10 (@snitin315) 

I think 6 can be done afterwards.

Thoughts?

**Comment by nzakas** [comment]
Sounds good to me.

**Comment by nzakas** [comment]
My changes: https://github.com/eslint/eslint/pull/17262

**Comment by mdjermanovic** [comment]
> My changes: #17262

Merged.

@bpmutter could you please now resubmit https://github.com/eslint/eslint/commit/d8e9887c2c384d24d586d08ee9ae2ada79bd234c (https://github.com/eslint/eslint/pull/16906)? An easy way is to copy & paste the whole content of those three files.

**Comment by mdjermanovic** [comment]
@nzakas your turn again: https://github.com/eslint/eslint/commit/3f7af9f408625dbc486af914706d34c4b483b5ba

**Comment by nzakas** [comment]
Done: https://github.com/eslint/eslint/pull/17280

**Comment by mdjermanovic** [comment]
> Done: #17280

Merged. Next step: https://github.com/eslint/eslint/pull/17281

**Comment by mdjermanovic** [comment]
> > Done: #17280
> 
> Merged. Next step: #17281

Merged as well.

@snitin315 you can now prepare a PR for these:



> * [52018f2](https://github.com/eslint/eslint/commit/52018f21c19b3e461cae32843cddd17ed42f19cd) ([feat: add `filename` to the rule context #17108](https://github.com/eslint/eslint/pull/17108)) @snitin315
> * [0df4d4f](https://github.com/eslint/eslint/commit/0df4d4f658c214e51310a986c03d44d34ceae3ec) ([feat: add `cwd` to rule context #17106](https://github.com/eslint/eslint/pull/17106)) @snitin315
> * [1468f5b](https://github.com/eslint/eslint/commit/1468f5b640cfa6fdd8a5ec895337f692def2780b) ([feat: add `physicalFilename` property to the rule context #17111](https://github.com/eslint/eslint/pull/17111)) @snitin315
> * [e52b98b](https://github.com/eslint/eslint/commit/e52b98bf25d882da4efd5559ce5974b6697cf701) ([feat: add `sourceCode` property to the rule context #17107](https://github.com/eslint/eslint/pull/17107)) @snitin315

**Comment by aladdin-add** [comment]
closing as fixed.
