### ISSUE TITLE
Docs: List of available language options are outdated

### ISSUE THREAD

**Issue by FredKSchott** [eslint/eslint#1722]
See: https://github.com/eslint/eslint/blob/022f604264dc351dba23fb3e9f4f9bf6a7ca5730/docs/configuring/README.md#specifying-language-options

This could be updated but maintaining this list is probably unsustainable, at least while new language support is under active development.

**Comment by nzakas** [comment]
What is outdated about it?

**Comment by FredKSchott** [comment]
oh duh, it's just in a different order than I'm used to. Whoops :)

**Comment by nzakas** [comment]
Alphabetical? :)
