### ISSUE TITLE
Bug: EMFILE: too many open files using Flat Config with very large projects

### ISSUE THREAD

**Issue by stevenpetryk** [eslint/eslint#17249]
### Environment

Node version: 20.2.0 (affects 16 and 18 as well)
npm version: 9.6.6
Local ESLint version: 8.42.0
Global ESLint version: N/A
Operating System: macOS 13.4

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = ["eslint:recommended"]
```
</details>

I created 10,000 empty JS files.

### What did you expect to happen?

I expected ESLint to not encounter any errors.

### What actually happened?

ESLint encountered an error:

```
Oops! Something went wrong! :(

ESLint: 8.42.0

Error: EMFILE: too many open files, open '/Users/steven/src/eslint-emfile-repro/src/file-4074.js'
```

### Link to Minimal Reproducible Example

https://github.com/stevenpetryk/eslint-emfile-repro
In that repo, run `npm install`, `npm run setup` (to create 10,000 empty files), and `npm run lint`.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

This issue is caused by [this unrestricted call tp Promise.all](https://github.com/eslint/eslint/blob/v8.42.0/lib/eslint/flat-eslint.js#L843-L942), which causes thousands of simultaneous `read` calls, opening too many file pointers simultaneously. 

A simple fix (we've patched this at Discord for our 10,500 file project) is to use something like [`p-limit`](https://www.npmjs.com/package/p-limit) to restrict the number of reads that are executed simultaneously, to a number like 1,000 (or maybe even 500).

<details>
<summary>± See the patch</summary>

```patch
diff --git a/node_modules/eslint/lib/eslint/flat-eslint.js b/node_modules/eslint/lib/eslint/flat-eslint.js
index f615ae1..e59862d 100644
--- a/node_modules/eslint/lib/eslint/flat-eslint.js
+++ b/node_modules/eslint/lib/eslint/flat-eslint.js
@@ -12,6 +12,7 @@
 // Note: Node.js 12 does not support fs/promises.
 const fs = require("fs").promises;
 const path = require("path");
+const pLimit = require("p-limit");
 const findUp = require("find-up");
 const { version } = require("../../package.json");
 const { Linter } = require("../linter");
@@ -840,6 +841,9 @@ class FlatESLint {

         debug(`${filePaths.length} files found in: ${Date.now() - startTime}ms`);

+        // Only read 1000 files at a time
+        const limit = pLimit(1000);
+
         /*
          * Because we need to process multiple files, including reading from disk,
          * it is most efficient to start by reading each file via promises so that
@@ -910,7 +914,7 @@ class FlatESLint {
                     fixer = message => shouldMessageBeFixed(message, config, fixTypesSet) && originalFix(message);
                 }

-                return fs.readFile(filePath, "utf8")
+                return limit(() => fs.readFile(filePath, "utf8")
                     .then(text => {

                         // do the linting
@@ -936,7 +940,7 @@ class FlatESLint {
                         }

                         return result;
-                    });
+                    }));

             })
         );
```

</details>

If this is an acceptable approach I'm happy to open a PR for it. `p-limit` is already a transitive dependency of eslint anyway, so it wouldn't tangibly require a new dependency.

<details>
<summary>eslint -> p-limit dependency graph (from the repro repo)</summary>

```
❯ npm why p-limit
p-limit@3.1.0 dev
node_modules/p-limit
  p-limit@"^3.0.2" from p-locate@5.0.0
  node_modules/p-locate
    p-locate@"^5.0.0" from locate-path@6.0.0
    node_modules/locate-path
      locate-path@"^6.0.0" from find-up@5.0.0
      node_modules/find-up
        find-up@"^5.0.0" from eslint@8.42.0
        node_modules/eslint
          dev eslint@"^8.42.0" from the root project
          peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
          node_modules/@eslint-community/eslint-utils
            @eslint-community/eslint-utils@"^4.2.0" from eslint@8.42.0
```

</details>

**Comment by Rec0iL99** [comment]
Hi @stevenpetryk, thanks for the issue. I wasn't able to reproduce the error. 

These are the steps I followed:

```bash
>> npm install
added 96 packages, and audited 97 packages in 1s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>> npm run setup

// 10,000 files were created, I manually checked
> eslint-emfile-repro@1.0.0 setup
> for ((i=0; i<10000; i++)); do touch src/file-$(printf "%04d" $i).js; done

>> npm run lint

> eslint-emfile-repro@1.0.0 lint
> eslint src

(node:54729) Warning: The 'eslint:recommended' string configuration is deprecated and will be replaced by the @eslint/js package's 'recommended' config.
(Use `node --trace-warnings ...` to show where the warning was created)
```

Am I missing something?

**Comment by stevenpetryk** [comment]
It could be that you just need to create more files (if your system is configured/capable of having more open file pointers). Perhaps try... 100,000?

**Comment by stevenpetryk** [comment]
The salient issue is that this code attempts to open an unbounded number of file pointers, which may not _always_ fail depending on system activity, configuration, and capability, but has the chance to for large projects. As for me I'm on an M1 Max with no large processes running, so it feels like this issue is likely to happen for folks.

I'll ask colleagues to reproduce as well.

**Comment by stevenpetryk** [comment]
You can run `ulimit -a` to see the number of file descriptors your system is limited to, and then generate that many files (maybe x2) to see if you can repro.

**Comment by stevenpetryk** [comment]
I actually figured out that some of our dev tooling is setting this limit to 4096, and that the default macOS limit it 2^16. Going to close this.

**Comment by Rec0iL99** [comment]
> It could be that you just need to create more files (if your system is configured/capable of having more open file pointers). Perhaps try... 100,000?

I got to repro at 100,000 files 

Results: 

```bash
> npm run lint

> eslint-emfile-repro@1.0.0 lint
> eslint src

(node:61904) Warning: The 'eslint:recommended' string configuration is deprecated and will be replaced by the @eslint/js package's 'recommended' config.
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 8.42.0

Error: EMFILE: too many open files, open '/Users/joelmathew/Desktop/eslint-emfile-repro/src/file-64924.js'
```

**Comment by Rec0iL99** [comment]
@eslint/eslint-team what do you think?
