### ISSUE TITLE
Bug: Eslint --fix removing optional chaining

### ISSUE THREAD

**Issue by Xavier59** [eslint/eslint#17240]
### Environment

Node version: v16.17.0
npm version: 8.15.0
Local ESLint version: v8.42.0
Global ESLint version: v8.42.0
Operating System: Windows 11

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
    env: {
        node: true,
        commonjs: true,
    },
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/strict",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
    ],
    root: true,
    overrides: [],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        ecmaVersion: "latest",
        tsconfigRootDir: __dirname,
        project: ["./tsconfig.json"],
    },
    plugins: ["@typescript-eslint"],
    rules: {
        "@typescript-eslint/no-throw-literal": "off",
        "no-prototype-builtins": "off",
        "@typescript-eslint/restrict-template-expressions": "off",
        eqeqeq: ["error", "always", { null: "ignore" }],
        "@typescript-eslint/consistent-type-definitions": ["error", "type"],
        "@typescript-eslint/array-type": [
            "error",
            {
                default: "array",
                readonly: "array",
            },
        ],
    },
};
```
</details>

I have the following code.

```typescript
const foobar1: Record<string, { bar: string }> = { foo: { bar: "bye !" } }
let myFoo1 = "fo";

console.log(foobar1[myFoo1]?.bar ?? "hello !");

myFoo1 += "o";

console.log(foobar1[myFoo1]?.bar ?? "hello !");
```

I ran `eslint --fix \"**/*.ts\"`

### What did you expect to happen?

Code stays as is and output:

```
hello
bye
```

### What actually happened?

Code was changed to:

```typescript
const foobar: Record<string, { bar: string }> = { foo: { bar: "bye !" } }
let myFoo = "fo";

console.log(foobar[myFoo].bar ?? "hello !");

myFoo += "o";

console.log(foobar[myFoo].bar ?? "hello !");
```

And it now produces the following output:

```
Cannot read properties of undefined (reading 'bar') 
```

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/fr/play?#code/MYewdgzgLgBAZiEAjAhgJwIwC4YCUCmoaAJgDzRoCWYA5gDQwDeMqaOF1NMAvgHwwBeJvEQ5mrHACIkAT3wwAhJJ48AUABt8sALYyAYogyCYkhJIDcq1aEghNAOnUgaACgTJ0GANq6DIDAC6APz2rDBBQSYAFvjqToqSAJSWqr6GMADUQpIgFlY2EHb4js5uiKzeaf7BoejhkZIxcSAJyfng0CIeaABMOAREZBy0DOLo7FBUtDz8QszuYizjJrLySircGlowVT3GprkpBUUlru6sPT76iD0BtWj10bHxSm2p1yB7WSaH7bYOTjO5XQl12dzCESezVa5iAA

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @Xavier59, thanks for the issue!

This autofix is produced by the `@typescript-eslint/no-unnecessary-condition` rule, which is a typescript-eslint plugin rule. If you think that this rule works incorrectly, please report an issue to the typescript-eslint repository:

https://github.com/typescript-eslint/typescript-eslint

I'm closing this issue since the mentioned rule is not maintained in core.
