### ISSUE TITLE
Bug: undefined problem

### ISSUE THREAD

**Issue by cx5397** [eslint/eslint#17253]
### Environment

chrome console

### What parser are you using?

vue-eslint-parser

### What did you do?

An undeclared value of a variable is undefined, and a value declared itself undefined. There is a difference between the two, but it is impossible to judge. Can you add an eslint rule to prohibit the assignment of undefined to the variable, so that undefined means that the variable is declared without assignment. 
let a={};
console.log(b)//will report an error; 
console.log(a.b)//output undefined is unreasonable, 
should also report an error, a.b is not declared like b

### What did you expect to happen?

make eslint rule to undefined

### What actually happened?

Uncaught ReferenceError: b is not defined
    at <anonymous>:1:13

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

thanks

**Comment by sam3k** [comment]
Hi @cx5397, could you provide a reproducible demo?

**Comment by cx5397** [comment]
stop user to set a variable's value undefined
