### ISSUE TITLE
Bug: The milestone for eslint 6.0 is still open

### ISSUE THREAD

**Issue by ollie-iterators** [eslint/eslint#17271]
### Environment

N/A

### What parser are you using?

Default (Espree)

### What did you do?

I looked at the milestones and saw that there was a milestone for version 6.0.0.

Here is the link: https://github.com/eslint/eslint/milestone/19

### What did you expect to happen?

I expected for the milestone for 6.0.0 to be closed.

### What actually happened?

The milestone is not closed.

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint/milestone/19

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
Thanks, I've closed it.
