### ISSUE TITLE
New Rule: no-padded-objects

### ISSUE THREAD

**Issue by AndreCunha1** [eslint/eslint#17304]
### Rule details

Controls whether multiline objects (and arrays) entries should be padded by newlines

### Related ECMAScript feature

Standard built-in objects (Object and Array)

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code

```js
/* eslint no-padded-objects: ["error"] */

// error
var qux = {
  foo: 'foo',
  bar: 'bar'

};

// error
var foo = [

  'bar',
  'baz'
];

// OK
var qux = {
  foo: 'foo',
  bar: 'bar'
};

// OK
var foo = [
  'bar',
  'baz'
];
```

### Why should this rule be in the core instead of a plugin?

The proposed rule is very general and similar in purpose to pre-existing rules such as:

- [padded-blocks](https://eslint.org/docs/latest/rules/padded-blocks)
- [padding-line-between-statements](https://eslint.org/docs/latest/rules/padding-line-between-statements)
- [no-multiple-empty-lines](https://eslint.org/docs/latest/rules/no-multiple-empty-lines)

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

Instead of a new rule, perhaps the following rule could be extended:

- [padding-line-between-statements](https://eslint.org/docs/latest/rules/padding-line-between-statements): extend `STATEMENT_TYPE` with more options such as `object-entry` and `array-entry` that would match entries inside object and array declarations. This way, this existing rule could freely control this with its already existing `"blankLine": LINEBREAK_TYPE` options (i.e. "any", "never", and "always")

**Related abandoned issues with same or similar request:** https://github.com/eslint/eslint/issues/5603 and https://github.com/eslint/eslint/issues/9048
(those are from 2016 and 2017 respectively, so it might be fair to revisit this idea)

**Comment by aladdin-add** [comment]
Per our [rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies), we can only accept new rules if they relate to new ECMAScript features that reached stage 4 in the preceding 12 months, so this proposal doesn't qualify. You can always make a custom rule and publish a plugin.
