### ISSUE TITLE
Supporting TypeScript for NodeJS API for `@eslint/js`

### ISSUE THREAD

**Issue by as1605** [eslint/eslint#17300]
### ESLint version

8.43.0

### What problem do you want to solve?

When importing rules from `@eslint/js` in a typescript project using the NodeJS API, there are no type declarations

### What do you think is the correct solution?

Defining types in an `index.d.ts` file, and exporting it from `package.json`

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Here's a diff patch I created. Currently kept rules as any but can convert the JSDoc to typescript definitions there too
```diff
diff --git a/node_modules/@eslint/js/package.json b/node_modules/@eslint/js/package.json
index 3af35a6..5e9a722 100644
--- a/node_modules/@eslint/js/package.json
+++ b/node_modules/@eslint/js/package.json
@@ -3,6 +3,7 @@
   "version": "8.43.0",
   "description": "ESLint JavaScript language implementation",
   "main": "./src/index.js",
+  "types": "./src/index.d.ts",
   "scripts": {},
   "files": [
     "LICENSE",
diff --git a/node_modules/@eslint/js/src/index.d.ts b/node_modules/@eslint/js/src/index.d.ts
new file mode 100644
index 0000000..4e16f0d
--- /dev/null
+++ b/node_modules/@eslint/js/src/index.d.ts
@@ -0,0 +1,4 @@
+export namespace configs {
+    const all: { rules: any };
+    const recommended: { rules: any };
+}
```

**Comment by Rec0iL99** [comment]
Hi, @as1605, thanks for the issue. You can use the type declarations from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/eslint__js).
