### ISSUE TITLE
Bug: Incorrect autofix ```reportUnusedDisableDirectives```.

### ISSUE THREAD

**Issue by dvun0g** [eslint/eslint#17309]
### Environment

Node version: 16.16.0
npm version: 8.11.0
Local ESLint version: 8.43.0
Global ESLint version: none
Operating System: darwin 22.4.0, MacOS m1, macOS Ventura 13.3.1 (a)

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
	"extends": "airbnb",
	"reportUnusedDisableDirectives": true,
	"ignorePatterns": ["node_modules"]
}
```
</details>

<details>
<summary>JS code</summary>

```
// eslint-disable-next-line
/* eslint-disable-next-line */

// eslint-disable-line
/* eslint-disable-line */

// eslint no-alert: "off"
/* eslint no-alert: "off" */

/* eslint-disable no-alert, no-console */
/* eslint-enable no-alert, no-console */

/* eslint-disable
    no-alert,
    no-console
*/
/* eslint-enable
    no-alert,
    no-console
*/

/* eslint-disable */
/* eslint-enable */
```
</details>

### What did you expect to happen?

All completely deleted disable comments, including ```eslint-enable``` and ```eslint rule: "off"```.

### What actually happened?

Disable comments have not been deleted ```eslint-enable``` and ```eslint rule: "off"```.

<details>
<summary>JS code after autofix</summary>

```
// eslint no-alert: "off"
/* eslint no-alert: "off" */

/* eslint-enable no-alert, no-console */

/* eslint-enable
    no-alert,
    no-console
*/

/* eslint-enable */
```

</details>

### Link to Minimal Reproducible Example

https://github.com/dvun0g/issue-eslint-reportUnusedDisableDirectives-autofix

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Using the ```reportUnusedDisableDirectives: true``` in the eslint configuration, I ran into the problem of incomplete deletion of disable comments. Auto fix does not support deleting comments of this kind ```eslint-enable```, ```eslint rule: "off"```.

I described this problem in the repository on github: https://github.com/dvun0g/issue-eslint-reportUnusedDisableDirectives-autofix. To repeat the problem, it is enough to run: ```npm run lint:fix``` or ```npm run lint -- --fix``` and and make sure that not all comments will be deleted from the file ```source/index.js```.

**Comment by Rec0iL99** [comment]
Hi @dvun0g, thanks for the issue. The [`reportUnusedDisableDirectives`](https://eslint.org/docs/latest/use/configure/rules#report-unused-eslint-disable-comments) config setting only works for `eslint-disable` comments and auto-fix will not remove `eslint-enable` comments. This is not a bug and `reportUnusedDisableDirectives` setting is working as expected.
