### ISSUE TITLE
eslint's npm package should not depend on ^ versions allowing to take package updates

### ISSUE THREAD

**Issue by davidknise** [eslint/eslint#17317]
### Environment

Node version: 
npm version: 
Local ESLint version: 
Global ESLint version: 
Operating System: 

### What parser are you using?

Default (Espree)

### What did you do?

We were running eslint v7.32.0

All of the npm package's versions are prefixed with a "^", which means when users install this package from npm.js org, they receive live version updates.

For about an hour today, fresh installs of eslint failed with "Cannot find module 'word-wrap'".

Looking at the stack trace, it traced back to a call inside the "optionator" dependency package.

Eslint specifies in its package.json "optionator" version "^0.9.1".

Going to npm, you can see v0.9.2 was pushed at the same correlating time to the error.
https://www.npmjs.com/package/optionator?activeTab=versions

An hour later, the issue went away, which correlates with optionator v0.9.3.

The commit message is "fix require of word-wrap"
https://github.com/gkz/optionator/commit/8cd002667162894795308b1780d4207a7cbf13e7

By using "^" dependencies, eslint opens itself to being broken by external dependencies. In addition, this could be security concern to install unvetted code.

### What did you expect to happen?

ESLint installs exact versions of dependencies preventing live dependency updates from breaking the tool.

### What actually happened?

An update to optionator was pushed that broke fresh installs of eslint for an hour today.

### Link to Minimal Reproducible Example

https://github.com/gkz/optionator

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ivari** [comment]
I'd like to point out that this specific example was caused by many dependencies switching to a fork of `word-wrap`, `@aashutoshrathi/word-wrap`, which caused conflicts within npm package handling itself resulting in indeterministic package resolution.

Pinning `eslint` dependencies would have not avoided the issue.
