### ISSUE TITLE
Support remote configuration

### ISSUE THREAD

**Issue by jasonkuhrt** [eslint/eslint#1731]
It would be an interesting feature if configuration of `eslint` could be achieved through remote means. For instance at littleBits we would create a style-guide repo that has an `eslint` config and then all projects that we make would refer to that via, at worst, just the Github raw URI. This would have the benefit of 

1. making sure everyone on our team used the same rules and 
2. when those rules changed every project would not have to be updated in any way. 

I see a third bonus feature here that would allow people to start sharing configs easier. For instance instead of a team saying "we will use the thoughtBot JS style" they would just literally reference their `eslint` config.

The biggest issue I currently see is that the eslint tool has to download the rules periodically and expose some commands so users/tools can force refresh (e.g. an editor plugin could force a request on project open or something).

**Comment by nzakas** [comment]
This is interesting but I think ultimately too problematic. This places a lot of responsibility on ESLint that I think is outside the scope of the tool. This functionality would be more appropriate for an add-on tool to manage configs than it would be as part of ESLint itself.

**Comment by jasonkuhrt** [comment]
@nzakas That's probably fair. It will also be hard to get right on the first go-around.
