### ISSUE TITLE
Bug: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/eslint' is not defined by "exports" in node_modules/eslint/package.json

### ISSUE THREAD

**Issue by shubhamp-sf** [eslint/eslint#17321]
### Environment

Node version: 18.16.0
npm version: 9.5.1
Local ESLint version: 8.43.0
Global ESLint version: 8.43.0
Operating System:  macOS Ventura (Version 13.4.1)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I tried running `lb-eslint` command available in [@loopback/build](https://www.npmjs.com/package/@loopback/build) package (raised [an issue](https://github.com/loopbackio/loopback-next/issues/9703) there too) which depends on `eslint`. But running it from a package (**in a mono-repo being managed via npm workspaces**) throws `ERR_PACKAGE_PATH_NOT_EXPORTED` error.

### What did you expect to happen?

I expect `lb-eslint` command to run without errors and do what it is supposed to do.

### What actually happened?

Throws error:

```sh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/eslint' is not defined by "exports" in /Users/shubham.prajapat/repos/my-mono-repo/node_modules/eslint/package.json

```

Full Logs: 
```sh
loopback:build /Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/packages/cache/.eslintrc.js found +0ms
  loopback:build /Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/packages/cache/.eslintignore found +1ms
  loopback:build Trying to resolve CLI module 'eslint' from /Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/packages/cache +0ms
  loopback:build CLI module 'eslint' is not found in dependencies +0ms
node:internal/modules/cjs/loader:571
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/eslint' is not defined by "exports" in /Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/node_modules/eslint/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at resolveCLI (/Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/node_modules/@loopback/build/bin/utils.js:76:18)
    at Object.runCLI (/Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/node_modules/@loopback/build/bin/utils.js:128:9)
    at run (/Users/shubham.prajapat/repos/sourcefuse/loopback4-microservice-catalog/node_modules/@loopback/build/bin/run-eslint.js:45:16) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.16.0
```

### Link to Minimal Reproducible Example

https://codesandbox.io/p/github/shubhamp-sf/eslint-17321-reproduction/main

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Adding this line in eslint's package.json solves the error for me, but I find no way to patch this change for other team mates without having it in actual eslint package.
```diff
  "name": "eslint",
  ...
  "exports": {
    "./package.json": "./package.json",
+  "./bin/eslint": "./bin/eslint.js",
    ".": "./lib/api.js",
    "./use-at-your-own-risk": "./lib/unsupported-api.js"
  },
```

**Comment by Rec0iL99** [comment]
Hi @shubhamp-sf, thanks for the issue. It looks like that project is using an outdated [method](https://github.com/loopbackio/loopback-next/blob/master/packages/build/bin/run-eslint.js#L45) for using ESLint. A code change commit to the file was back in [2019](https://github.com/loopbackio/loopback-next/commit/a6abe8606495dd16108e0b79135199c758ddb941#diff-0c3ab21bcee3def44dc219ac216c8bc5a39115780f2a811f1a8a0d758bb15c49) and we have changed a lot since then.

I think you should wait for the maintainers to patch a fix.

cc @nzakas @mdjermanovic

**Comment by mdjermanovic** [comment]
We didn't add this subpath to `exports` because `bin/eslint.js` module is not intended to be `require()`-d from other packages. Since the subpath is not defined by `exports`, `require.resolve('eslint/bin/eslint')` fails.

I agree with @Rec0iL99, it seems that the `@loopback/build` package should use some other method to build the path for its use case.

**Comment by nzakas** [comment]
Agree with @mdjermanovic and @Rec0iL99. Please contact the Loopback team with this problem.
