### ISSUE TITLE
Change Request: Update `prefer-destructuring` rule documentation

### ISSUE THREAD

**Issue by marcospgp** [eslint/eslint#17327]
### ESLint version

Latest

### What problem do you want to solve?

Documentation was not updated after https://github.com/eslint/eslint/issues/11584 was closed

Information is important as confusion causes disabling rule and missing out on benefits

### What do you think is the correct solution?

Include info in documentation about how destructuring with assignment to object such as `[this.myVar] = myArray` is possible

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Thanks for the issue, a PR is welcome!

**Comment by mdjermanovic** [comment]
PR https://github.com/eslint/eslint/pull/17330
