### ISSUE TITLE
Bug: `FlatESLint#getRulesMetaForResults` throws on unknown rules

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#17343]
### Environment

Node version: v16.14.0
npm version: 8.3.1
Local ESLint version: `main` branch
Global ESLint version: 
Operating System: windows

### What parser are you using?

Default (Espree)

### What did you do?

While working on https://github.com/eslint/espree/pull/577, where we switched from `eslint-plugin-node` to `eslint-plugin-n`, I noticed that vscode-eslint extension (set to use FlatESLint) crashes, and therefore doesn't show any lint messages, when I open a file that has directives with now-unknown `node/*` rules. For example, `// eslint-disable-next-line node/no-unsupported-features/es-syntax`:

```
[Error - 11:54:29 PM] TypeError: Could not find the rule "node/no-unsupported-features/es-syntax".
    at FlatESLint.getRulesMetaForResults (C:\milos\espree\node_modules\eslint\lib\eslint\flat-eslint.js:720:27)

```

This doesn't happen when vscode-eslint is using the `ESLint` class.

To reproduce this difference in behavior, I wrote a script that runs `lintText` and then `getRulesMetaForResults`, as IDE integrations do.

<details>
<summary>Configuration</summary>

```
No config file needed
```
</details>

```js
const { LegacyESLint, FlatESLint } = require("eslint/use-at-your-own-risk");
const assert = require("assert");

(async () => {
    const text = "/* eslint-disable foo */";

    const legacyESLint = new LegacyESLint({ useEslintrc: false });
    const legacyResults = await legacyESLint.lintText(text);
    assert.strictEqual(legacyResults[0].messages.length, 1);
    assert.strictEqual(legacyResults[0].messages[0].ruleId, "foo");
    legacyESLint.getRulesMetaForResults(legacyResults); // does not throw

    const flatESLint = new FlatESLint({ overrideConfigFile: true });
    const flatResults = await flatESLint.lintText(text);
    assert.strictEqual(flatResults[0].messages.length, 1);
    assert.strictEqual(flatResults[0].messages[0].ruleId, "foo");
    try {
        flatESLint.getRulesMetaForResults(flatResults);
    } catch(e) {
        console.log("Throws!");
        console.log(e);
    }
})();

```

### What did you expect to happen?

`FlatESLint#getRulesMetaForResults` to have the same behavior as `ESLint#getRulesMetaForResults`: not throw on unknown rules.

### What actually happened?

```
Throws!
TypeError: Could not find the rule "foo".
    at FlatESLint.getRulesMetaForResults (C:\milos\eslint\lib\eslint\flat-eslint.js:720:27)
    at C:\milos\eslint\test.js:18:20
```

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint/tree/getrulesmeta-issue-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

It's debatable whether lint messages that report unknown rules should really have those rules set as `ruleId`, but that looks like a bigger change.

**Comment by mdjermanovic** [comment]
This can also be reproduced by running `eslint -f json-with-metadata` on a file that contains directives with unknown rules.

**Comment by nzakas** [comment]
That's interesting. I'm a bit on the fence as to what the desired behavior is -- in theory, you'd want to be informed if you're using a rule that doesn't exist.

It looks like this issue really stems from the fact that when a rule ID doesn't exist, we generate a lint message where `ruleId` is the missing rule ID, which will obviously not be found.

Given that it's disruptive to the VS Code plugin, it seems best to quietly fail to include the rule result for the missing ID.
