### ISSUE TITLE
Change Request: Export a LegacyESLint object

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#17340]
### ESLint version

HEAD

### What problem do you want to solve?

The plan for rolling out flat config is for flat config to become the default in v9.0.0 with eslintrc still supported in a deprecated mode. That means both the current `ESLint` and `FlatESLint` classes will still be used, however, they both won't be accessible via the API. The intent was for `ESLint` in v9.0.0 to be `FlatESLint`, with the current `ESLint` hidden.

Based on how people are starting to integrate with `FlatESLint`, I don't think we can make this drastic of a change without significant problems for the ecosystem.

### What do you think is the correct solution?

I'd like to propose that we start exporting a `LegacyESLint` class from the `/use-at-your-own-risk` entrypoint that is a duplicate of the current `ESLint` class. I'd like to do this before ESLint v9.0.0 to help prepare people. The idea is for the `ESLint` class to always be the "blessed" version that is officially supported while providing both `FlatESLint` and `LegacyESLint` through v9.0.0.

So in v8.x, we would have:

* `ESLint` (equivalent of `LegacyESLint`) as the officially supported API
* `FlatESLint` for flat config in `/use-at-your-own-risk`
* `LegacyESLint` for eslintrc in `/use-at-your-own-risk`

Then, in v9.x, we would swap the official API and have:

* `ESLint` (equivalent of `FlatESLint`) as the officially supported API
* `FlatESLint` for flat config in `/use-at-your-own-risk`
* `LegacyESLint` for eslintrc in `/use-at-your-own-risk`

And in v10.0.0, we would remove both `FlatESLint` and `LegacyESLint`.

I think this approach would allow the ecosystem to make a more gradual transition away from eslintrc functionality.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

If approved, I think we should prioritize getting this work done to aid in the transition to flat config.

**Comment by mdjermanovic** [comment]
I agree with the plan.

**Comment by nzakas** [comment]
I'll get to work on this.
