### ISSUE TITLE
Rule Change: sort-keys

### ISSUE THREAD

**Issue by jozefchutka** [eslint/eslint#17347]
### What rule do you want to change?

sort-keys

### What change to do you want to make?

More parameters

### How do you think the change should be implemented?

A new option / parameter

### Example code

sort-keys could be helpful with resolving "property order polymorphism"
https://devblogs.microsoft.com/typescript/introducing-deopt-explorer/#example-property-order-polymorphism

However, its not always that you want to sort alphabetically. Imagine these objects:

```js
{kind:"b", aProp:1}
{kind:"a", aProp:1, bProp:2}
```

would be sorted as:

```js
{aProp:1, kind:"a"}
{aProp:1, bProp:2, kind:"a"}
```

which would create more maps in V8 than necessary:

1. `{aProp:1}`
2. nr1 extended by `{kind:"a"}`
3. nr1 extended by `{bProp:2, kind:"a"}`

If `sort-keys` could be somehow parametrised, lets say enforcing such common keys/properties as `kind`, `type`, ... to come first, the linted order would be:

```js
{kind:"b", aProp:1}
{kind:"a", aProp:1, bProp:2}
```

and V8 Maps:

1. `{kind:"b", aProp:1}`
2. nr1 extended by `{bProp:2}`

### What does the rule currently do for this code?

sorting alphabetically without additional rules:

```js
{aProp:1, kind:"a"}
{aProp:1, bProp:2, kind:"a"}
```

### What will the rule do after it's changed?

```js
{kind:"b", aProp:1}
{kind:"a", aProp:1, bProp:2}
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by aladdin-add** [comment]
Thanks for the input. As [stated in the README](https://github.com/eslint/eslint#stylistic-rule-updates), we actually aren't making any further updates to rules that enforce stylistic preferences. If you have a strong preference for such a change, you can always copy the existing rule into a custom rule and make it behave the way you want.
