### ISSUE TITLE
Change Request: eslint options to resolve extends config and parser paths

### ISSUE THREAD

**Issue by navateja-alagam** [eslint/eslint#17344]
### ESLint version

v8.43.0

### What problem do you want to solve?

I have a use-case to resolve the third party packages of extend configs, plugins, parser etc. used in `.eslintrc.json` file from a different resolution path than the cwd's 'node_modules'.

our .eslintrc.json config looks something like below:
```
 plugins: [
        '@sfdc-internal/lwc-core',
        'eslint-comments',
    ],
    extends: [
        '@salesforce/eslint-config-lwc/recommended',
        '@locker/eslint-config-locker/base',
    ],

    parser: "@babel/eslint-parser",
```

I found an option for plugins i.e., via resolvePluginsRelativeTo from the [list of eslint options ](https://eslint.org/docs/latest/integrate/nodejs-api#parameters)available for vscode-eslint. But don't see a way to modify the resolve path for the config from extends and parser configurations from above.

cmd:  `eslint ./test.js --resolve-plugins-relative-to <some_other_path_where_plugins_can_be_resolved>`

### What do you think is the correct solution?

With option `--resolve-plugins-relative-to`, I'm able to resolve the plugins config to point to the other path I mentioned in settings.json however looking for an option to modify 'extends & parser' configs too.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @navateja-alagam, thanks for the issue!

> I have a use-case to resolve the third party packages of extend configs, plugins, parser etc. used in `.eslintrc.json` file from a different resolution path than the cwd's 'node_modules'.
>
> With option `--resolve-plugins-relative-to`, I'm able to resolve the plugins config to point to the other path I mentioned in settings.json however looking for an option to modify 'extends & parser' configs too.

The `eslintrc` config system is frozen, so we are not adding any new features that relate to it. If it helps, both `extends` and `parser` accept absolute paths, so in a `.eslintrc.js` config file you could resolve the paths as you'd like and then set absolute paths in `extends` and `parser` config fields.

In the [new config system](https://eslint.org/docs/latest/use/configure/configuration-files-new), plugins, configs and parsers are passed in as objects, so you can resolve and load them however you like.

**Comment by navateja-alagam** [comment]
Thanks @mdjermanovic! Sounds good.
