### ISSUE TITLE
Rule Change: Please add "quotes" as an exception option to rule "space-in-parens"

### ISSUE THREAD

**Issue by brybrant** [eslint/eslint#17350]
### What rule do you want to change?

space-in-parens

### What change to do you want to make?

Generate more warnings

### How do you think the change should be implemented?

A new option

### Example code

```js
/*eslint space-in-parens: ["error", "always", { "exceptions": ["quotes"] }]*/

document.getElementById('example'); // good

document.getElementById( 'example' ); // bad
```

### What does the rule currently do for this code?

Nothing

### What will the rule do after it's changed?

Disallow or require space inside of parenthesis except when the first and/or last item is wrapped in quotes (set by the "quotes" rule).

Maybe also template literals

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

In my opinion, having spaces either side of quotes inside of parenthesis looks like too much space

**Comment by mdjermanovic** [comment]
Hi @brybrant, thanks for the issue! 

Per our rules policies, [stylistic rules are frozen](https://github.com/eslint/eslint#stylistic-rule-updates) so we are not adding new options to the `space-in-parens` rule. You can always copy the existing rule into a custom rule and make it behave the way you want.
