### ISSUE TITLE
Change Request: Allow for plugins with config that supports RC and Flat style configs

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#17355]
### ESLint version

v8.42.0

### What problem do you want to solve?

There does not seem to be any way for a plugin to bundle a config which can bundle the old RC style of `plugins`: e.g., `plugins: ['jsdoc']` for older ESLint at the same time as its new Flat Config style, e.g., `plugins: {jsdoc: jsdoc}`.

### What do you think is the correct solution?

Perhaps ESLint could use a `for..in` loop over the array and ignore numeric indexes (so as to safely ignore the string content of an array like `['jsdoc']`) while checking for array's non-numeric object properties (like `jsdoc: jsdoc`).

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

This is particularly important, I think, in our case since the docs at https://eslint.org/docs/latest/use/configure/configuration-files-new#using-configurations-included-in-plugins are currently actually using our plugin as an example, and the example doesn't work (as reported to us already by a user).

**Comment by fasttime** [comment]
Hi @brettz9, eslintrc config and flat config are not mutually interchangeable. The `plugins` option format is just one of the differences that make the two configs incompatible.

To support both config styles in the same plugin, an option is to provide different named configs: this is what we are doing in `eslint-config-eslint`, where we expose [separate configs](https://github.com/eslint/eslint/blob/5ca9b4d29f747e9cf5c9055e85c93b3b605d57fc/packages/eslint-config-eslint/package.json#L8-L10) as subpath exports. in a plugin, the configs must be exported under the `configs` key, but the idea is basically the same.

As for [the example](https://github.com/eslint/eslint/blob/1866e1df6175e4ba0ae4a0d88dc3c956bb310035/docs/src/use/configure/configuration-files-new.md?plain=1#L469-L486) with `eslint-plugin-jsdoc`, that looks like a bug in the documentation. We should fix that and show a working example.

**Comment by nzakas** [comment]
Yeah, this is already technically supported, just use different names for the flat and eslintrc configs in your plugin.

The example in the docs wasn't mean to be canonical, it was just an example assuming a future world where plugins are all exporting flat configs. No problem if we want to change that to something else.

**Comment by fasttime** [comment]
@brettz9 Do you have any plans to add a flat config to `eslint-plugin-jsdoc`? If so, we could just switch the config name in the documentation and get a working example.

**Comment by brettz9** [comment]
I had been hoping for a polyformat compatible solution, even if it weren't going to handle all compatibility issues, and one which might speed adoption, but if not, I get it.

Am out of the country atm, but maybe in a week or two I can get to it.

**Comment by nzakas** [comment]
Yeah, there's not going to be a single format that works in both cases, there are just too many differences.

**Comment by brettz9** [comment]
Have been having some health issues, but should hopefully be able to take a look in the next couple days....

**Comment by brettz9** [comment]
We've just released a Flat-config-compatible release. The config is available as `jsdoc.configs['flat/recommended']` (I decided not to require a separate import, keeping the configs in one place.)

Hope someone else can prepare the docs PR, however, as still dealing with fatigue.

**Comment by fasttime** [comment]
Thanks for the update @brettz9, hope you get well soon. I will fix the docs with the new config name.
