### ISSUE TITLE
comma-spacing emits a false positive when combined with template strings

### ISSUE THREAD

**Issue by hgwood** [eslint/eslint#1736]
Given the code ``var a; console.log(`${a}`, "a");``, eslint emits the error `There should be no space before ',' (comma-spacing)`.

The false positive is specifically emitted when the template string ends with a closing brace *and* is immediately followed by a comma: ``console.log(`a`, "a");``, ``console.log(`a`);
``, ``var a; console.log(`${a}`);`` emit no error.

**Comment by lo1tuma** [comment]
Looks like a bug.

The rule checks the position of the token before a `","` puctuator. In this case the token before the comma is the closing brace so the rule warns because there is another character between `}` and `,`. 

I'm not if this is something we should fix in espree or in eslint.

**Comment by nzakas** [comment]
That does look like it could be a parser issue. I think the token should be a "Template" instead of "Punctuator".

**Comment by nzakas** [comment]
Opened https://github.com/eslint/espree/issues/44.

**Comment by nzakas** [comment]
Still broken in Espree 1.8.0 :(
