### ISSUE TITLE
Change Request: Discard disabled rule entries in config

### ISSUE THREAD

**Issue by matwilko** [eslint/eslint#17361]
### ESLint version

8.44.0

### What problem do you want to solve?

When [merging config array elements](https://github.com/eslint/eslint/blob/b79b6fb64473969b426d086b484d2e29594a5e9a/lib/config/flat-config-schema.js#L339), ESLint will keep a record of every rule configured, whether or not it ends up enabled or disabled after the merge.

This has a few knock-on consequences:
- the rule has to be enumerated through by various parts of the system, including the rule validator and the linter and the merge function itself - while this doesn't cause the rule to be loaded, and the individual impact is minimal, across many files, this can start to add up
- it needlessly uses up memory with many effectively no-op entries in configs that keep arrays in memory
- it makes the output of `--print-config` harder to read, and especially confusing when a rule ends up merged as disabled, but with configuration (e.g. `[0, {someConfig: ...}, 'strict']`). If the disabled rules were stripped out, only the rules actually enabled for a file would be shown to the user.

### What do you think is the correct solution?

I'd propose refactoring `rulesSchema.merge` so that it only returns rules that are enabled after the merge has taken place, with any disabled rules simply being discarded.

Afaict, this shouldn't have any behavioural consequences for the rest of the system, as other areas already implement checks for `if (ruleOptions[0] === 0) { return/continue/etc; }`. Those checks would become redundant, and could be removed if/when there is confidence in the change. It would also slightly simplify any future development that needs to interact with the `config.rules` object, as there's fewer cases to consider.

This would cause a user-visible change though, as noted, the `--print-config` CLI option would no longer show disabled rules in the resolved config for a file.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We keep the disabled rules around so we can easily report when specific rules have been disabled. The use case you mention `--print-config`, being especially important to help folks understand what configuration was actually loaded. There's a different between `semi: off` and not including `semi`, which is that the former was intentionally included along the way and the latter might be a mistake.
