### ISSUE TITLE
Change Request: Convert classes to use private fields/methods

### ISSUE THREAD

**Issue by matwilko** [eslint/eslint#17387]
### ESLint version

8.45.0

### What problem do you want to solve?

Classes throughout the ESLint codebase that keep private per-instance state currently use a common pattern of declaring an `internalSlotsMap` and getting/setting/destructuring in various places.

It's also common for "internal" methods to be marked with a leading underscore, but unlike the internal slots, these are technically available to consumers of the class (if they like living dangerously!)

I understand that these were probably the best patterns available at the time, but since JS has improved since then, I think there's an opportunity to take advantage of the private class features that became available in NodeJS 12.0+.

I think moving to use these features will improve readability and maintainability - eliminating the extra concept of having to deal with the slots map and reducing to simple property access throughout the class is much simpler to understand and harder to get wrong (e.g. updating the map can be a bit hazardous if care isn't taken to avoid overwriting existing state accidentally)

### What do you think is the correct solution?

I'd propose converting all the properties currently stored in each `internalSlotsMap` into corresponding `#propertyName` fields on the classes, and converting any `_method`s to `#method`.

This will require refactoring some parts of these files that rely on having access to the internal slots map from outside the class, but that probably only requires some small refactors.

As far as I can tell, changing `_method`s shouldn't cause any problems internally to ESLint, as `no-underscore-dangle` already seems to ban access to these methods internally.

I'd propose doing this in stages, perhaps moving one property out of the slot map at a time to make PRs easier to review when updating all the references and/or doing necessary refactors. The slot map can then be removed in each class in a final PR when it is empty.

Method conversions would probably follow the same pattern, though depending on the number of call-sites could probably be updated several at a time.

One big question is whether to treat converting the methods as a breaking change. Since the methods are already considered "private" and aren't part of the public API, consumers shouldn't be relying on them existing but converting them to private methods would immediately break those consumers. I'm not sure how ESLint would want to treat those kinds of changes, or whether they'd need to wait for ESLint 9.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
I support this proposal.

> One big question is whether to treat converting the methods as a breaking change. Since the methods are already considered "private" and aren't part of the public API, consumers shouldn't be relying on them existing but converting them to private methods would immediately break those consumers. I'm not sure how ESLint would want to treat those kinds of changes, or whether they'd need to wait for ESLint 9.

Per [node.green](https://node.green/#ES2022-features-private-class-methods), private methods are not available in Node 12, so this would have to wait for ESLint 9 anyways. I also remember that in Node 12 some basic things with private fields didn't quite work as they should per the final specification (although node.green only lists combinations with optional chaining as problematic), so it might be better to plan all changes for ESLint 9.

Which classes would we like to change?

**Comment by matwilko** [comment]
Dang, that's unfortunate - I was relying on MDN, which reports full support from Node v12.0 😞

In that case, the method conversion would certainly need to wait for ESLint v9 - will ESLint be dropping older Node versions at the time? (a quick look shows that Node 16 will reach EOL in mid-September)

Given the property changes wouldn't require any visible, behavioural or breaking changes, I think it would be valuable to get going on them in the meantime, since they're going to get the most benefit from the conversion. The changes for the properties are also likely to be a bit more involved than the method conversions, so having a bit of runway before ESLint 9 is probably a good idea.

It might be the case that there's a few usages dotted around that need a slight refactor if they use optional chaining, but I think that's a bridge to cross if we come to it 😄

Looking around, I can't find any docs or articles that indicate that _basic_ usage of private fields in Node v12 is problematic. That's partially why I suggested migrating one property at a time, to make sure there aren't any weird issues caused by the changes - I'm happy to take things slow and make sure the changes have time to "soak in" before applying more.

As for suggestions on classes to change, a quick scan through the codebase for `WeakMap` or `_propName` usage highlights:
- [`ESLint`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/eslint/eslint.js#L96)
- [`CLIEngine`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/cli-engine/cli-engine.js#L137)
- [`Linter`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/linter/linter.js#L1163)
- [`FileEnumerator`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/cli-engine/file-enumerator.js#L103)
- [`FlatESLint`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/eslint/flat-eslint.js#L96)
- [`OffsetStorage`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/rules/indent.js#L246)
- [`Rules`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/linter/rules.js#L38)
- [`Traverser`](https://github.com/eslint/eslint/blob/42faa17b1c93f801b14bea2840d1d528e25c7211/lib/shared/traverser.js#L59)

**Comment by nzakas** [comment]
While I'm not opposed to the idea, I'm not sure how valuable this would be. I'd much rather spend time on completing existing tasks than spending a bunch of time refactoring internal-only classes.

Also note that when using private fields, you lose the ability to wrap classes in a proxies:
https://lea.verou.me/2023/04/private-fields-considered-harmful/

If people are excited about this, I'd say go ahead, I'd just ask that we consider the opportunity cost vs. working on already open issues.

Other note: `ESLint`, 'FileEnumerator`, and `CLIEngine` are deprecated and will be removed, so we should not touch those.

**Comment by mdjermanovic** [comment]
I agree with @nzakas that there's no value in refactoring the classes that are planned to be removed, like `ESLint`, `CLIEngine`, and `FileEnumerator`.

**Comment by nzakas** [comment]
@matwilko I'm not sure that the benefits you mention will materialize. Realistically, newcomers don't contribute to the core, they contribute to rules, and dealing with dozens of small PRs to refactor classes that are mostly internal-only will create additional maintenance burden. I just think that we'd rather direct that energy towards issues listed as "Ready to Implement", where we are getting some user-facing value for the work.

And we are planning a big rewrite of the core, so a lot of the existing classes will end up being thrown away.

So, as I said, I'm not sure this is a good use of time but if others on the team want to pursue this I'll go along with the consensus.

**Comment by matwilko** [comment]
> I'm not sure that the benefits you mention will materialize.

Sure, I know it's speculation, but it kind of has to be 😄

> Realistically, newcomers don't contribute to the core

Sure, I can see that's the current state of affairs. I'd suggest that perhaps part of the reason it might be difficult to get new contributors to work on the core is that a lot of the work lined up is large in scope or needs pre-existing intimate knowledge of the codebase to get started on. Not to mention there are 0 issues in "good first issue" or "help wanted" :smile:

All I was suggesting was that having a few low-risk, mostly low-effort issues covering stuff in core _might_ encourage a few people to start contributing to core. Having to touch lots of parts of core functionality in a low-risk way means they gain familiarity with the code and work their way up to helping out with bigger things 😄

> And we are planning a big rewrite of the core, so a lot of the existing classes will end up being thrown away.

I know there's a rewrite planned, and I believe in your conviction to execute it, but rewrites also tend to take years and in many cases outright fail for various reasons. Keeping the existing codebase actively moving forward means that _if_ the rewrite falters for whatever reason, there's still a perfectly viable and actively maintained codebase to carry on with :smile:

**Comment by nzakas** [comment]
@fasttime yup, that was what @mdjermanovic [mentioned](https://github.com/eslint/eslint/issues/17387#issuecomment-1641140712). I'm not sure it's worth the effort even then, but again, will go along with consensus.

**Comment by Rec0iL99** [comment]
@eslint/eslint-team this issue has been marked stale quite a number of times now. What are the next steps here?

**Comment by JoshuaKGoldberg** [comment]
FWIW this would be helpful to me as a previous PR author and new member of the committer team. I found the unusual strategy for privates to be confusing. +1 to the previously stated points that it makes it harder to read & understand the codebase.

It sounds like the main blocker was waiting for v9, and the bot just isn't aware of that, right?

**Comment by Rec0iL99** [comment]
> It sounds like the main blocker was waiting for v9, and the bot just isn't aware of that, right?

Yes. I think we have the consensus from the team to move this forward, right?

**Comment by nzakas** [comment]
No, as I stated previously, I think this is an unnecessary refactoring that doesn't yield much value. Spending time to refactor the already-too-complicated logic in ESLint vs. using that time on fixes and new features doesn't seem like a good tradeoff to me.

Especially where we want to be starting the core rewrite in the near future, I'd rather leave well enough alone and just focus on using newer practices during the rewrite. (And on any new features we implement in ESLint going forward.)
