### ISSUE TITLE
Bug: --no-ignore not working for /* eslint-disable */

### ISSUE THREAD

**Issue by singersbalm** [eslint/eslint#17396]
### Environment

Node version: v20.4.0
npm version: v9.7.2
Local ESLint version: v8.45.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.2.0

### What parser are you using?

Default (Espree)

### What did you do?

eslint --fix --no-ignore .

```js
/* eslint-disable */
/* tslint:disable */
```

### What did you expect to happen?

it should process the file

### What actually happened?

it skipped the file

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
`--no-ignore` relates to [ignoring files](https://eslint.org/docs/latest/use/configure/ignore). If you want eslint to ignore `/* eslint-disable */` directives, you can use [`--no-inline-config`](https://eslint.org/docs/latest/use/command-line-interface#--no-inline-config).
