### ISSUE TITLE
When using --reset, camelcase rule is not reset

### ISSUE THREAD

**Issue by mourner** [eslint/eslint#1740]
Having `camelcase: 2` in `package.json`, running:

```
eslint --reset js
```

Outputs all `camelcase` errors for some reason. All other rules are not affected. If I add an additional rule using `--rule`, it will be output alongside `camelcase`.

**Comment by nzakas** [comment]
`--reset` turns off ESLint defaults. It does not turn off what you have in a configuration file.

**Comment by mourner** [comment]
Ah, I see — thought it resets everything. My use case was running ESLint on a big untidy codebase with lots of errors, tackling errors one at at time by running e.g. `eslint --reset --rule "somerule: 2"`.

**Comment by lo1tuma** [comment]
@mourner this is possible by running `eslint - - reset - - no-eslintrc`.

**Comment by mourner** [comment]
@lo1tuma oh, right! Thanks!
