### ISSUE TITLE
Bug: (Alias path causing error "Unsafe call of an `any` typed value." Vite MERN )

### ISSUE THREAD

**Issue by lolikana** [eslint/eslint#17416]
### Environment

Node version: 18.13.0
npm version: 8.19.3
Local ESLint version: 8.45.0
Global ESLint version: 
Operating System: macOS

### What parser are you using?

@typescript-eslint/parser

### What did you expect to happen?

I am expecting an import without error when using alias path "@hooks/use-title" like the screenshot using relative path "./../hooks/use-title"

![Screenshot 2023-07-25 at 11 35 23](https://github.com/eslint/eslint/assets/91938540/83080b70-2d93-40cf-a980-6df76df60612)

### What actually happened?

When using alias path, error: `Unsafe call of an "any" typed value.eslint(@typescript-eslint/no-unsafe-call)` 

![Screenshot 2023-07-25 at 11 34 10](https://github.com/eslint/eslint/assets/91938540/86b54c6d-e77e-46c9-98c7-fde8fe5dce1b)

![Screenshot 2023-07-25 at 11 34 20](https://github.com/eslint/eslint/assets/91938540/c4dca04e-67ea-4e23-abf3-b1c28b1494f5) 

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/awesome-banach-z9pqxx

### What did I try? 

- Open with another computer : not working
- Add to VSCode settings.json :
```
	"eslint.workingDirectories": [ { "mode": "auto" } ],
```

- Add to .eslintrc.cjs settings: 
```
  settings: {
    'import/resolver': {
      typescript: {
        project: ['tsconfig.json', 'client/tsconfig.json', 'server/tsconfig.json']
      },
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx']
      }
    }
  }
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

If you are not seeing the error in `client/src/pages/Homepage.tsx`, open another file like `client/src/App.tsx` then go back to Homepage.tsx. 
I feel like the problem is using eslint for both, client and server folder. 

_No response_

**Comment by aladdin-add** [comment]
It is a ts integration issue and you should approach the ts-eslint team for help: https://github.com/typescript-eslint/typescript-eslint

**Comment by lolikana** [comment]
I see, thank you! I will ask over there
