### ISSUE TITLE
Ignore paths without the need to create an ignore file

### ISSUE THREAD

**Issue by mourner** [eslint/eslint#1742]
ESLint command line conveniently allows you to specify which files to ignore in a `.eslintignore` file or a different file specified in command line. However, there's no clear way to ignore a path without having to create such a file. Or at least it's not documented in [the docs](http://eslint.org/docs/configuring/).

What I'd love to see:

- be able to set ignore paths explicitly in `package.json`
- be able to set ignore paths directly in the command line, e.g. `eslint js --ignore js/lib`

**Comment by nzakas** [comment]
We can't put ignore files in configuration files due to the life cycle of ESLint, but a command line option might be possible.

**Comment by mourner** [comment]
Command line option would be enough for my use cases. E.g. run eslint on any repo quickly, whether it adopts eslint or not. Thanks!

**Comment by pmcelhaney** [comment]
Working on this. My first eslint contribution so I'll have a PR as soon as I get familiar with the unit tests and such.
