### ISSUE TITLE
Change Request[Rule Tester]: Do not create empty test suites

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#17455]
### ESLint version

8.46.0

### What problem do you want to solve?

The [RuleTester](https://github.com/eslint/eslint/blob/631648ee0b51a8951ce576ccd4430e09c9c8bcae/lib/rule-tester/rule-tester.js#L1025) currently always creates test suites for valid and invalid test cases even if there are no test cases.
This is problematic for [vitest](https://github.com/vitest-dev/vitest/issues/3820) as it marks the empty test suite as failing.
Personally I like to use multiple calls to split up the cases.
For example usually I have a call for only preconditions which the rule does not match (so only valid test cases) and one for the rule fixer testing edge cases (so only invalid test cases).

### What do you think is the correct solution?

Wrap the `valid` and `invalid` describe in a simple if checking whether there are test cases:
```javascript
if (test.valid.length > 0) {
	describe('valid', () => { ... })
}
// same for invalid
```

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sorry, there's not enough information here to understand what it is you're asking. Please provide an example of what you're doing now and explain what problems you're running into.

**Comment by DMartens** [comment]
[Vitest](https://vitest.dev/) is a test runner like mocha or jest.
It requires test suites (here defined by the `RuleTester.describe` calls) to have at least one test case (here defined by `RuleTester.it`) inside them (see the [referenced issue](https://github.com/vitest-dev/vitest/issues/3820)).
As the test cases can get unwieldly when there are many, I like to separate the test cases by context.
This uses the same principle as using nested test suites inside a test suite to further organize the test cases.

For example this would fail the file as an error is generated for the empty invalid test suite when run with vitest:
```javascript
const ruleTester = new RuleTester();
ruleTester.run('Preconditions', rule, {
	valid: [{ code: '' }],
    invalid: [],
});

// More ruleTester.run calls
```

So a solution would be not create empty test suites for `valid` or `invalid` by not calling `RuleTester.describe` if there are no test cases for them.

**Comment by nzakas** [comment]
Thanks, that's very helpful. This seems like a good suggestion. Would you be interested in submitting a PR for this change? (Note it would need to be made both in `RuleTester` and `FlatRuleTester`.)

**Comment by DMartens** [comment]
Sure I'll submit a PR tomorrow.
