### ISSUE TITLE
Separate warnings and issues in summary

### ISSUE THREAD

**Issue by goloroden** [eslint/eslint#1746]
When you run ESLint and it detects some warnings and some errors, it just tells us:

> ✖ 46 problems

IMHO it would be more helpful if we had something such as:

> ✖ 46 problems (2 errors, 44 warnings)

Or, with the first line in red, and the second one in yellow:

> ✖ 2 errors
> ✖ 44 warnings

What do you think?

**Comment by nzakas** [comment]
I think we can do the first option.

**Comment by btmills** [comment]
Working on this.
