### ISSUE TITLE
Missing types for `@eslint/js`

### ISSUE THREAD

**Issue by DamianGlowala** [eslint/eslint#17479]
### ESLint version

8.47.0

### What problem do you want to solve?

```
import js from '@eslint/js'
```
Could not find a declaration file for module '@eslint/js'.

### What do you think is the correct solution?

Add types for the module.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We don't publish types with our packages at this point.

**Comment by DamianGlowala** [comment]
Out of curiosity, is this on the flat config's GA roadmap?

Fortunately these configs can be used as strings (ESLint all & recommended), which I wasn't aware of at the time of creating this issue, therefore my concern has already been solved. 

Thanks for replying!
