### ISSUE TITLE
Rule Change: (function-call-argument-newline) add minArguments option

### ISSUE THREAD

**Issue by schblondie** [eslint/eslint#17476]
### What rule do you want to change?

function-call-argument-newline

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
/*eslint function-call-argument-newline: ["error", { "minArguments": 3 }]*/
bar("one", "two");
foo("one", "two", "three");
"string".slice(0, 3);
```

### What does the rule currently do for this code?

As minArguments option does not exist, code would look like:
```
bar(
    "one",
    "two"
);
foo(
    "one",
    "two",
    "three"
);
"string".slice(
    0,
    3
)
```

### What will the rule do after it's changed?

```
bar("one", "two")
foo(
    "one",
    "two",
    "three"
);
"string".slice(0, 3)
```

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by Rec0iL99** [comment]
Hi @schblondie, thanks for the issue. We currently aren't adding any new options to core stylistic rules due to the [policy change](https://github.com/eslint/eslint/#stylistic-rule-updates). You can always copy the core rule into a custom rule and add options.
