### ISSUE TITLE
[Flat Config] Drop support for string configurations `"eslint:recommended"` and `"eslint:all"`

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#17488]
### ESLint version

v8.47.0

### What problem do you want to solve?

As of v8.35.0 (https://github.com/eslint/eslint/commit/c8c0c715a2964cc1859b99f9d4f542675094d1d5), ESLint emits deprecation warnings when string configurations `"eslint:recommended"` or `"eslint:all"` are used.

### What do you think is the correct solution?

Drop support for these configurations in ESLint v9.0.0.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I don't think we already have a tracking issue for this task.

**Comment by EvebJoan** [comment]
Please can anyone rewrite this code to make it work? Thank you if anyone can
It's for a palindrome checker

<!DOCTYPE HTML>
<html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link rel="stylesheet" href="styles.css"> <title>Palindrome checker</title> <style> @import ur('https://fonts.googleapis.com/css2?
family=Kode+Mono:wght@400.700&display=swap")
< style> <style>
@import url ('https ://fonts.googleapis.com/css2?
family=Dancing+Script:wght@400.700&family=Kode +Mono:wght@400..700&family=Lobster&display=swa p')
</style>
<head> <body> <main>
<h1 class="title">Is it a palindrome?<h1> <h2 class="subtitle">Palindrome checker</h2> < main> ‹div id="result"<
<input id="text-input" placeholder="Write your text here"> <button id="check-btn"><b>Find out</b> </ button>
<div> id="palindrome-def"> <p id="definition">
<span role="img" aria-label="light-bulb">&#128161:</span> A <dfn> <u>palindrome</ u></dfn> is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.
< div> «script src="script.js"></script> < body> <html>

**Comment by EvebJoan** [comment]
Please can anyone rewrite this code to make it work? Thank you if anyone can

```

<!DOCTYPE HTML>
<html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link rel="stylesheet" href="styles.css"> <title>Palindrome checker</title> <style> @import ur('https://fonts.googleapis.com/css2?
family=Kode+Mono:wght@400.700&display=swap")
< style> <style>
@import url ('https ://fonts.googleapis.com/css2?
family=Dancing+Script:wght@400.700&family=Kode +Mono:wght@400..700&family=Lobster&display=swa p')
</style>
<head> <body> <main>
<h1 class="title">Is it a palindrome?<h1> <h2 class="subtitle">Palindrome checker</h2> < main> ‹div id="result"<
<input id="text-input" placeholder="Write your text here"> <button id="check-btn"><b>Find out</b> </ button>
<div> id="palindrome-def"> <p id="definition">
<span role="img" aria-label="light-bulb">&#128161:</span> A <dfn> <u>palindrome</ u></dfn> is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.
< div> «script src="script.js"></script> < body> <html> 
```
