### ISSUE TITLE
Rule Change: Add "never" option to "curly" rule.

### ISSUE THREAD

**Issue by nickshanks** [eslint/eslint#17487]
### What rule do you want to change?

curly

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
if (foo) {
  bar(dependency1 = 5);
  return baz(dependency2);
}
```

### What does the rule currently do for this code?

Leaves it alone.

### What will the rule do after it's changed?

Automatically convert blocks for if/else/do/while/etc. to functions with a unique generated name, and call them:

```js
function _autofunc_if_foo(dependency1, dependency2) {
  bar(dependency1);
  return baz(dependency2);
}

if (foo) return _autofunc_if_foo(dependency1 = 5, dependency2);
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

Suggest using an inner/nested `function` as shown for full backwards compatibility, and defining that function immediatly above the `if`/etc. so that it can be converted to an arrow function by other rules, if desired.

Do not apply transform to any block that writes to non-global variables declared outside of it's scope. So, "almost-never" might be a more accurate name :-/

**Comment by mdjermanovic** [comment]
@nickshanks thanks for the issue, but per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates) stylistic rules are frozen so we're not adding new options to the `curly` rule. You can always copy the core rule into a custom rule and modify it.

**Comment by nickshanks** [comment]
Sorry, I hadn't seen that 2020 blog post before. Maybe you should move 260 of those 280 rules out into plug-ins and then cut them loose for the community to maintain!  Especially ones that just cover stylistic choices.
