### ISSUE TITLE
Bug: (string does not fix via cli)

### ISSUE THREAD

**Issue by mohsenomidi** [eslint/eslint#17491]
### Environment

Node version: v18.12.1
npm version: 8.19.2
Local ESLint version: v8.47.0
Global ESLint version: v8.47.0
Operating System: Ubuntu 22.04

### What parser are you using?

@babel/eslint-parser

### What did you do?

from command line i need to format and fix my js code with `-stdin` and `--fix-dry-run` options
command like below:

```echo "export const gridSpacing = 3; export const drawerWidth = 260; export const appDrawerWidth = 320;" | npx eslint --stdin --fix-dry-run ```

### What did you expect to happen?

generate the fixed and formatted code based on the configuration to stdout or file 

### What actually happened?

if the code had error print errors only not formatted and fixed 
but if you directly give the file by command line it rewrite the fixed and formatted version :

``` npx eslint --fix file.js``` 

### Link to Minimal Reproducible Example

echo "export const gridSpacing = 3; export const drawerWidth = 260; export const appDrawerWidth = 320;" | npx eslint --stdin --fix-dry-run 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @mohsenomidi, thanks for the issue!

> ### Link to Minimal Reproducible Example
> echo "export const gridSpacing = 3; export const drawerWidth = 260; export const appDrawerWidth = 320;" | npx eslint --stdin --fix-dry-run

There isn't enough information to reproduce the problem because the configuration is unknown so we don't know which rules are enabled and therefore what fixes should be applied and what the expected output should be. Can you please provide a link to a minimal reproducible example?

> ### What did you expect to happen?
> generate the fixed and formatted code based on the configuration to stdout or file

Note that using `--fix-dry-run` does not mean that the fixed code will be printed to stdout. Lint results are passed to the formatter, the same as without `--fix-dry-run`, and the default formatter does not show the fixed code. If you want to see the fixed code, you can use `--format json` and then look for the `"output"` value, or make a custom formatter that prints only the `output`.

https://eslint.org/docs/latest/use/command-line-interface#--fix-dry-run

**Comment by mohsenomidi** [comment]
@mdjermanovic Thanks for your fast reply.

Sorry for the lack of information. 

My Configuration file is: 
```
{
    "root": true,
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": ["prettier", "plugin:react/jsx-runtime", "plugin:jsx-a11y/recommended", "plugin:react-hooks/recommended"],
    "settings": {
        "import/resolver": {
            "node": {
                "moduleDirectory": ["node_modules", "src/"]
            }
        }
    },
    "parser": "@babel/eslint-parser",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "impliedStrict": true
        },
        "ecmaVersion": 12
    },
    "plugins": ["prettier", "react", "react-hooks","unused-imports"],
    "rules": {
        "unused-imports/no-unused-imports": 2,
        "react/jsx-filename-extension": 0,
        "no-param-reassign": 0,
        "react/prop-types": 0,
        "react/require-default-props": 0,
        "react/no-array-index-key": 0,
        "react/jsx-props-no-spreading": 0,
        "react/forbid-prop-types": 0,
        "import/order": 0,
        "no-console": 0,
        "jsx-a11y/anchor-is-valid": 0,
        "prefer-destructuring": 0,
        "no-shadow": 0,
        "react/jsx-uses-vars": "error",
        "react/jsx-uses-react": "error",
        "react-hooks/exhaustive-deps":0,
        "prettier/prettier": [
            2,
            {
                "bracketSpacing": true,
                "printWidth": 140,
                "singleQuote": true,
                "trailingComma": "none",
                "tabWidth": 4,
                "useTabs": false,
                "endOfLine": "auto"
            }
        ]
    }
}

```

and once I execute the command ` npx eslint --fix file.js`, eslint automatically fix and format my js file. but I need to format the contents of my js file as text string buffer. and after that write it to file. 
because my js files auto generated. and if I passed the file vi cli I have 4 phase of file operation

1. generate the not formatted and not fixed file content
2. write it to file
3. format by ` npx eslint --fix file.js`
4. eslint rewrite it again 

if I can do the step 2, 3 in 1 step I only have 1 operation and disk operation does not involved in that phase and I only have in memory operation, it is speed up the file operation and prevent the multiple disk write. 

Regards

**Comment by mdjermanovic** [comment]
When I run:

```
echo "export const gridSpacing = 3; export const drawerWidth = 260; export const appDrawerWidth = 320;" | npx eslint --stdin --fix-dry-run -f json
```

The output is:

```
[{"filePath":"<text>","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"output":"export const gridSpacing = 3;\nexport const drawerWidth = 260;\nexport const appDrawerWidth = 320;\n","usedDeprecatedRules":[]}]
```

Which seems correct to me - the autofixed code is: `"output":"export const gridSpacing = 3;\nexport const drawerWidth = 260;\nexport const appDrawerWidth = 320;\n"`.

But please provide a repro repo so we could know what the exact problem you're encountering is.

**Comment by mohsenomidi** [comment]
Thanks for your reply, I checked again, the problem is related to the path of execution of eslit by my generator, it is out of the configuration directory and cause the problem. 
Now I changed the path and works fine.

Thanks for your guidance 😀🙏
