### ISSUE TITLE
Rule Change: no-console could be fixable

### ISSUE THREAD

**Issue by edi9999** [eslint/eslint#17493]
### What rule do you want to change?

no-console

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

I debug a lot with console.log, and have to remove them all afterwards.

Some console.log I write are multiline, like this : 

```js
console.log(
	JSON.stringify({
		msg: "inspect-sectObj",
		inspect: util.inspect(sectObj, { showHidden: true, depth: 2 }),
	})
);
```

### What does the rule currently do for this code?

It will simply report the error

### What will the rule do after it's changed?

It could fix the error, removing the console.log alltogether

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

I know this has not been implemented on purpose, probably people don't want all their console.logs dropped by eslint by default, I would also like to be able to make this rule fix only on certain conditions.

**Comment by edi9999** [comment]
For the moment I will continue removing my console.log manually, it is just annoying when you do it twice a day for 5 minutes.

**Comment by mdjermanovic** [comment]
Hi @edi9999, thanks for the proposal!

We can't implement this as autofix, because autofixes should never change the runtime behavior of code. This is the policy for core rules and general advice for plugins (though, you can find an equivalent but autofixable no-console rule in [eslint-plugin-autofix](https://www.npmjs.com/package/eslint-plugin-autofix)).

We could only consider implementing this in the core `no-console` rule as [suggestions](https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions), if that seems useful to you?

**Comment by edi9999** [comment]
Interesting, how can I access the suggestions ?

Is there a way to access them from the command line ? If yes, I would be interested in first having an example output in the command line, then I could write the code for the suggestion of the console.log rule.

**Comment by mdjermanovic** [comment]
Suggestions can be applied through editors that support this feature.

For example, in VS Code:

![image](https://github.com/eslint/eslint/assets/44349756/2ef6172c-ea9b-4cbc-90c6-f4a2355cb13c)

(`` Remove the `\`...  `` and `` Replace the `\`... `` are two suggestions; when user selects a suggestion, editor applies the fix).

There's no built-in support for applying suggestions from the command line.

**Comment by Dimava** [comment]
Removing console with autofix should be a standalone plugin
And it already exists as https://www.npmjs.com/package/eslint-plugin-fulldo-remove-console

**Comment by edi9999** [comment]
So you mean you wouldn't be open to add the "suggestion" to console.logs ?

I'm using neovim as my editor so I'm not sure whether I can use suggestions at all, that's why I asked whether I could do something from the command line.

**Comment by mdjermanovic** [comment]
The ESLint team would be open to evaluating adding suggestions to the `no-console` rule.

> I'm using neovim as my editor so I'm not sure whether I can use suggestions at all, that's why I asked whether I could do something from the command line.

Not sure either, but you could try with a code example where suggestions are expected to appear:

```js
/* eslint no-useless-escape: "error" */

"\a";
```

The expected suggestions are as in [this demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVzZWxlc3MtZXNjYXBlOiBcImVycm9yXCIgKi9cblxuXCJcXGFcIjsiLCJvcHRpb25zIjp7ImVudiI6eyJlczYiOnRydWV9LCJydWxlcyI6e30sInBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fSwiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIn19fQ==).

**Comment by nzakas** [comment]
Marking as expected.
