### ISSUE TITLE
Change Request: add a no-extend flag to the CLI

### ISSUE THREAD

**Issue by moniuch** [eslint/eslint#17495]
### ESLint version

v8.27.0

### What problem do you want to solve?

FYI: 8.27 is the version I'm having in my project, but from the CLI docs I see that my request could be valid for the latest version as well.

Having a few apps that extend from the main .eslintrc.json at the project root, I find it difficult to run eslint targeting one specific rule, using this syntax `--rule "{...}"`. Whenever I run eslint with the `--rule` flag, I'm getting all issues found for all the rules pulled in by various `extends`.

### What do you think is the correct solution?

Could we maybe have `--no-extend` CLI flag that would basically run a bare eslint and allow to ignore any extends (whether in the root of the config or in the overrides part). That way I would be sure I am really targeting my code with a specific rule of my chouce.

I tried `--no-eslintrc` but it still did all the extension and pulled in all the configs

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment]
Hi @moniuch, thanks for the issue. Quite a similar proposal to #13079. I'm guessing we would need a RFC to move forward if approved.

**Comment by moniuch** [comment]
@Rec0iL99 Hi, yes indeed, sorry I didn't really do a decent search, I was in a flow :) The motivation, I believe, is very clear. Luckily, we have eslint-nibble (a godsend!), but I think the core of eslint should allow for a better control than it this respect. Sometimes you work on a project that you inherit and need really good review/overview tooling.

I think for a lot of new users the current behavior might also be a bit confusing or disappointing.

**Comment by mdjermanovic** [comment]
> Could we maybe have `--no-extend` CLI flag that would basically run a bare eslint and allow to ignore any extends (whether in the root of the config or in the overrides part). That way I would be sure I am really targeting my code with a specific rule of my chouce.

The eslintrc config system is frozen, and in the [new config system](https://eslint.org/docs/latest/use/configure/configuration-files-new) there's no `extends` so we can't accept this change.

> I tried `--no-eslintrc` but it still did all the extension and pulled in all the configs

This isn't the expected behavior. Can you please open a bug report with all the details?

**Comment by mdjermanovic** [comment]
Looks like there are no actionable items here.

@moniuch If the `--no-eslintrc` option doesn't seem to work as expected, or you have a suggestion related to the [new config system](https://eslint.org/docs/latest/use/configure/configuration-files-new), please open a new issue.
