### ISSUE TITLE
Ability to have a CI friendly cache

### ISSUE THREAD

**Issue by kwasimensah** [eslint/eslint#17514]
### ESLint version

v8.46.0

### What problem do you want to solve?

I'm writing a build tool and was looking into speeding up eslint across builds. Digging into that I found https://github.com/eslint/rfcs/pull/106 which seems to have been closed as stale.

I can take a stab at resurrecting it. What I think would also be helpful is to add a layer of indirection for caching in the ESLint API so that people willing to write their own integrations ala https://eslint.org/docs/latest/integrate/integration-tutorial could change the caching strategy without needing agreement on how to spell this for general eslint users.

### What do you think is the correct solution?

Add a layer of indirection for caching in the ESLint API so that people willing to write their own integrations ala https://eslint.org/docs/latest/integrate/integration-tutorial could change the caching strategy without needing agreement on how to spell this for general eslint users.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sure, if you're willing to put together an RFC, we can consider it.

Let's continue the conversation back over on https://github.com/eslint/eslint/issues/16493 so we can keep all relevant information together.

**Comment by Rec0iL99** [comment]
@kwasimensah friendly ping. We have reopened #16493.
