### ISSUE TITLE
Change Request: Remove deprecated context pass-through SourceCode methods

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#17520]
### ESLint version

HEAD

### What problem do you want to solve?

We have a bunch of deprecated methods on `context` that pass through to `SourceCode`:

* `getComments()`
* * `getSource`
* `getAllComments`
* `getNodeByRangeIndex`
* `getComments`
* `getCommentsBefore`
* `getCommentsAfter`
* `getCommentsInside`
* `getJSDocComment`
* `getFirstToken`
* `getFirstTokens`
* `getLastToken`
* `getLastTokens`
* `getTokenAfter`
* `getTokenBefore`
* `getTokenByRangeStart`
* `getTokens`
* `getTokensAfter`
* `getTokensBefore`
* `getTokensBetween`

### What do you think is the correct solution?

I think it's time to remove these methods to clean up the codebase.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Sounds good to me.

We could add deprecation warnings in RuleTester in v8.x, and then remove these methods in v9.0.0?

**Comment by mdjermanovic** [comment]
RuleTester already wraps `create(context)` here:

https://github.com/eslint/eslint/blob/926a28684282aeec37680bbc52a66973b8055f54/lib/rule-tester/rule-tester.js#L561-L571

Perhaps we could insert an object with methods that shadow deprecated ones:

```js
        linter.defineRule(ruleName, Object.assign({}, rule, {

            // Create a wrapper rule that freezes the `context` properties.
            create(context) {
                freezeDeeply(context.options);
                freezeDeeply(context.settings);
                freezeDeeply(context.parserOptions);

                const newContext = Object.freeze(
                    Object.create(
                        context,
                        Object.fromEntries(Object.keys(DEPRECATED_SOURCECODE_PASSTHROUGHS).map(name => [
                            name,
                            {
                                value(...args) {

                                    // emit deprecation warning here

                                    // call the original method                                   
                                    return context[name].call(this, ...args);
                                },
                                enumerable: true
                            }
                        ]))
                    )
                );

                return (typeof rule === "function" ? rule : rule.create)(newContext);
            }
        }));
```

**Comment by nzakas** [comment]
Oh nice! I didn't realize we were doing that already (yet another part of the codebase I'm not familiar with). Then we can definitely do that.

**Comment by nzakas** [comment]
In looking at this, I discovered that the tests for `flat-rule-tester.js` don't include tests for legacy rule format or missing schemas, and I can't recall if this is intentional. Any idea @bmish?

**Comment by mdjermanovic** [comment]
It's intentional per https://github.com/eslint/eslint/pull/16063#issuecomment-1193192107.

I think these warnings can also be implemented just in `rule-tester.js`.

**Comment by nzakas** [comment]
In that case, the PR is ready! :tada:

**Comment by JoshuaKGoldberg** [comment]
Looks like #17527 closed this out?

**Comment by mdjermanovic** [comment]
> Looks like #17527 closed this out?

The remaining task is to remove these methods in v9.

**Comment by nzakas** [comment]
Working on this.

**Comment by sam3k** [comment]
2023-11-30 tsc-meeting note: This one will be ready along with the language plugins issue because it's all in the same PR
