### ISSUE TITLE
Bug: typescript consistent-type-imports crashed on duplicate import

### ISSUE THREAD

**Issue by Failfail2603** [eslint/eslint#17557]
### Environment

Node version: 20.4.0
npm version: 9.8.0
Local ESLint version: ^8.48.0
Global ESLint version: ^8.48.0
Operating System: Linux https://github.com/coder/code-server

### What parser are you using?

@typescript-eslint/parser

### What did you do?

We are writing webcomponents with Lit 2.0. If I do the following imports in one file, eslint crashes.
<details>
<summary>Configuration</summary>

```
env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  'no-confusing-void-expression': 'off'
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/no-confusing-void-expression': 'off'
  '@typescript-eslint/lines-between-class-members': 'off'
  '@typescript-eslint/class-literal-property-style': 'off'
  '@typescript-eslint/no-unnecessary-condition': 'error'
  'no-useless-constructor': 'off'
  '@typescript-eslint/no-useless-constructor': 'off'
  '@typescript-eslint/no-misused-promises': 'off'
  '@typescript-eslint/no-unused-vars': 'warn'
  '@typescript-eslint/restrict-template-expressions':
    - 'error'
    - allowAny: false
      allowBoolean: true
      allowNullish: true
      allowNumber: true
      allowRegExp: true
  '@typescript-eslint/prefer-nullish-coalescing':
    - error
    - ignoreMixedLogicalExpressions: true
      ignorePrimitives:
        string: true
        boolean: true
  '@typescript-eslint/return-await':
    - 'error'
    - 'in-try-catch'
  no-async-promise-executor: 'off'
  promise/param-names: 'off'
  max-statements: 'off'
  no-unused-vars: 'off'
  complexity:
    - warn
    - 10
  max-lines:
    - error
    - max: 500
      skipBlankLines: true
      skipComments: true
  max-lines-per-function:
    - error
    - max: 150
  max-depth:
    - error
    - max: 4

```
</details>

```js
import '@myComponents/design/components/x-flex';
import { XFlex } from '@myComponents/design/components/x-flex';
```
The following function in consistent-type-import.js is the problem. If node.specifiers[0].type is replaced by node.specifiers[0]?.type eslint doesnt crash anymore.

```js
function classifySpecifier(node) {
            const defaultSpecifier = node.specifiers[0].type === utils_1.AST_NODE_TYPES.ImportDefaultSpecifier
                ? node.specifiers[0]
                : null;
            const namespaceSpecifier = node.specifiers.find((specifier) => specifier.type === utils_1.AST_NODE_TYPES.ImportNamespaceSpecifier) ?? null;
            const namedSpecifiers = node.specifiers.filter((specifier) => specifier.type === utils_1.AST_NODE_TYPES.ImportSpecifier);
            return {
                defaultSpecifier,
                namespaceSpecifier,
                namedSpecifiers,
            };
        }
```

### What did you expect to happen?

Eslint should mark this as an duplicate import and should suggest to remove the anonymous. Problem here is, that with some bundlers these imports do different thing. Altough in my case this is not a problem.

### What actually happened?

Eslint crashed with the following error:

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting /home/coder/repositories/rootdir/projectdir/src/client/components/my-component.ts:1
Rule: "@typescript-eslint/consistent-type-imports"
    at classifySpecifier (/home/coder/repositories/rootdir/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports.js:303:57)
    at fixInlineTypeImportDeclaration (/home/coder/repositories/rootdir/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports.js:428:73)
    at fixInlineTypeImportDeclaration.next (<anonymous>)
    at fixToTypeImportDeclaration (/home/coder/repositories/rootdir/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports.js:465:28)
    at fixToTypeImportDeclaration.next (<anonymous>)
    at Object.fix (/home/coder/repositories/rootdir/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports.js:214:52)
    at fix.next (<anonymous>)
    at Function.from (<anonymous>)
    at normalizeFixes (/home/coder/repositories/projectdir/node_modules/eslint/lib/linter/report-translator.js:198:33)
    at /home/coder/repositories/rootdir/node_modules/eslint/lib/linter/report-translator.js:365:49

### Link to Minimal Reproducible Example

/

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I cant show you the actual source-code or the repo, because they are owned by the company i work for. In the first place I want to know if its a problem on my side or an actual bug in eslint.

**Comment by mdjermanovic** [comment]
Hi @Failfail2603, thanks for the issue!

`@typescript-eslint/consistent-type-imports` rule is not maintained in the core, please open an issue in the plugin's repository:

https://github.com/typescript-eslint/typescript-eslint
