### ISSUE TITLE
New Rule: disallow useless assignments

### ISSUE THREAD

**Issue by boris-petrov** [eslint/eslint#17559]
### Rule details

It should disallow useless assignments which might indicate a bug.

### Related ECMAScript feature

Assignment

### What type of rule is this?

Warns about a potential problem

### Example code

```js
function x(arg) {
  const value = arg;
  arg = 8;
  return value;
}
```

### Why should this rule be in the core instead of a plugin?

Because it is very useful. Such an assignment is needless and most likely indicates that there is some behavior that the author wanted but didn't correctly do. There is a [Sonar](https://rules.sonarsource.com/javascript/RSPEC-1854/) rule for the same thing.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

[Related discussion](https://github.com/eslint/eslint/issues/17539).

**Comment by merkuriy** [comment]
This will be helpful.

References:
- https://en.wikipedia.org/wiki/Dead_store
- https://www.npmjs.com/package/eslint-plugin-no-useless-assign
- https://sonarsource.atlassian.net/browse/RSPEC-1854
- https://rules.sonarsource.com/javascript/RSPEC-1854/
- https://rules.sonarsource.com/typescript/RSPEC-1854/
- Common Weakness Enumeration: [CWE-563](http://cwe.mitre.org/data/definitions/563.html) - Assignment to Variable without Use ('Unused Variable')

- [MSC13-C.](https://wiki.sei.cmu.edu/confluence/x/39UxBQ) - Detect and remove unused values

- [MSC56-J.](https://wiki.sei.cmu.edu/confluence/x/9DZGBQ) - Detect and remove superfluous code and values

**Comment by boris-petrov** [comment]
Thanks for accepting the rule!

I definitely won't be able to create the rule, not any time soon. Hopefully someone else can tackle it!

**Comment by mdjermanovic** [comment]
I'm also in favor of this proposal.

**Comment by nzakas** [comment]
For anyone interested in taking this one, a few tips:

1. This rule cannot be effectively implemented just using AST nodes, you'll need to use information from scopes (retrievable via `sourceCode.getScope(node)`.
2. The trick here is to identify that after an assignment (i.e., `foo = 1`) the variable is either a) never read or b) isn't read before that variable is overwritten with another value.

**Comment by ota-meshi** [comment]
Can I work on creating this rule as my next task?

**Comment by nzakas** [comment]
@ota-meshi absolutely! I'd recommend that you **not** look at the existing Sonar rule to make sure you're not copying anything from there. But otherwise, go for it!
