### ISSUE TITLE
New Rule: (trailing-line-comment-align) align trailling comment for Object value and declarations

### ISSUE THREAD

**Issue by axetroy** [eslint/eslint#17553]
### Rule details

trailling comment declarations

### Related ECMAScript feature

no

### What type of rule is this?

Suggests an alternate way of doing something

#### 1. Align trailling comment for object values

```js
var myObj = {
  key1 : 1, // uses multiLine

  key2 : 2,     // uses align (when defined)
  key3 : 32222, // uses align (when defined)

  key4 : 4  // uses multiLine
}
```

#### 2. Align trailling comment for declarations

```js
var name = "Tom" // comment align
var age  = 18    // commant align
```

### Why should this rule be in the core instead of a plugin?

I don't known what the rules(`key-spacing` or `indent` or `comment`) should be related

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by mdjermanovic** [comment]
Hi @axetroy, thanks for the issue!

Per our [rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies/), we can only accept new core rules when they relate to new ECMAScript features that reached stage 4 in the preceding 12 months, so this rule doesn't qualify. Furthermore, we're about to deprecate all whitespace-related rules (https://github.com/eslint/eslint/issues/17522) so we're definitely not adding another one. You can always make a custom rule and publish a plugin.
