### ISSUE TITLE
Bug: `context.sourceCode` undefined when run through npm

### ISSUE THREAD

**Issue by starlingjon** [eslint/eslint#17581]
### Environment

Node version: v18.13.0
npm version: v9.8.1
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.5.0

### What parser are you using?

@babel/eslint-parser

### What did you do?

- created a custom plugin/rule that uses `context.sourceCode`
- updated my `.eslintrc.js` to use this new plugin/rule
- added an npm script "lint" which runs `eslint .`

### What did you expect to happen?

result of running `npm lint` where the "lint" script is `"eslint ."` should be identical to running `eslint .`

### What actually happened?

no output, just an error when I tried to access `.lines` of undefined.

modifying the rule to log `context.sourceCode` to the console logged `undefined` for each file linted

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-edqcts?file=customrule%2Fcustomrule.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

stackblitz link doesn't behave the same as my machine, there `context.sourceCode` is undefined even when run directly with `eslint .` whereas on my machine I do still get the source code as expected

I left a comment in the code there explaining this as well.

Perhaps this suggests that the issue is not specific to npm scripts?

**Comment by mdjermanovic** [comment]
Hi @starlingjon, thanks for the issue!

> Local ESLint version: v7.32.0 (Currently used)

`context.sourceCode` was added in ESLint v8.40.0 (https://github.com/eslint/eslint/commit/e52b98bf25d882da4efd5559ce5974b6697cf701). If you want your plugin to support older versions of ESLint, you can use `context.getSourceCode()` .

> result of running `npm lint` where the "lint" script is `"eslint ."` should be identical to running `eslint .`

If you are getting different results with different commands, maybe they are running different versions of ESLint. You can use the [`--version`](https://eslint.org/docs/latest/use/command-line-interface#-v---version) CLI option to check which version of ESLint is run. Either way, `context.sourceCode` being `undefined` is expected in ESLint v7.32.0.
