### ISSUE TITLE
Change Request: Add a configuration option to treat warnings as errors

### ISSUE THREAD

**Issue by colons** [eslint/eslint#17594]
### ESLint version

v8.49.0

### What problem do you want to solve?

ESLint has a `--max-warnings` parameter, which, because it sets a cap on a number that will vary depending on which files are included, [should not be available as a configuration option](https://github.com/eslint/eslint/issues/16804#issuecomment-1453380014). This parameter is, as well as a way to set a cap, the only way to treat _all_ warnings as errors (`--max-warnings=0`).

Some projects have recommended rule sets that include warnings, and there's currently no way to adopt a project-wide policy of treating all such warnings as errors without manually altering each rule, and checking for new ones whenever that rule set is updated.

### What do you think is the correct solution?

For cases where `--max-warnings` is a number greater than zero, I absolutely agree that it doesn't make sense for it to be configured globally. For the case where it's zero because you just want to not allow warnings at all, though, I don't think the restriction makes sense any more.

Perhaps there should be a `treatWarningsAsErrors` boolean configuration option, since that would cover my use case here without introducing inconsistent failures in the way previous discussions on this matter have been trying to avoid.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

This has been raised twice before (#13391 and #16804), but with the assumed expectation of allowing non-zero caps on warning counts. Here, I'm specifically asking _only_ for a configurable equivalent of `--max-warnings=0`.

**Comment by nzakas** [comment]
Thanks for the suggestion, and thanks for doing your research on previous discussions around this topic.

Fundamentally, we just can't allow things in config that quietly alter other parts of the config. One of our core design principles of config is that changes need to be made explicitly. That's why `max-warnings` is only available at the CLI level -- it is explicit that for this run, you want to treat warnings differently.

**Comment by colons** [comment]
i saw this mention of 'altering other parts of the config' in the other issues, but i don't understand what it refers to. do you mean that individual rules won't be able to set their own warning level any more, since it's being overridden? the only thing i want to change is what exit code eslint uses when there are warnings present; the presentation could otherwise be identical. are there any other config variables that directly control exit code?

would it be more palatable if the config variable was called `nonZeroExitCodeOnWarning` or something?
