### ISSUE TITLE
TypeError: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by franckl** [eslint/eslint#1759]
I am using Eslint in webstorm (an IDE) and I get this error.
Eslint works on the js files that contain my node/express code but not on my client side js file

Any idea what is causing this issue or how I could debug it ? 

```
/usr/local/lib/node_modules/eslint/lib/eslint.js:693
            location = node.loc.start;
                           ^
TypeError: Cannot read property 'loc' of undefined
    at EventEmitter.module.exports.api.report (/usr/local/lib/node_modules/eslint/lib/eslint.js:693:28)
    at RuleContext.report (/usr/local/lib/node_modules/eslint/lib/rule-context.js:93:16)
    at /usr/local/lib/node_modules/eslint/lib/rules/no-shadow.js:38:25
    at Array.forEach (native)
    at checkShadowsInScope (/usr/local/lib/node_modules/eslint/lib/rules/no-shadow.js:36:19)
    at EventEmitter.checkForShadows (/usr/local/lib/node_modules/eslint/lib/rules/no-shadow.js:54:13)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:646:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:639:24)

Process finished with exit code 8
```

**Comment by nzakas** [comment]
It's the `no-shadow` rule. Can you share the code?

**Comment by franckl** [comment]
Sure, please see here http://pastebin.com/PzTq5Mx5

**Comment by btmills** [comment]
Here's a repro:

```js
// test.js
var arguments;

function bar() { }

```

```sh
$ eslint --reset --no-eslintrc --rule "no-shadow: 2" test.js

/Users/brandon/code/eslint/eslint/lib/eslint.js:704
            location = node.loc.start;
                           ^
TypeError: Cannot read property 'loc' of undefinedTypeError: Cannot read property 'loc' of undefined
    at EventEmitter.module.exports.api.report (~/code/eslint/eslint/lib/eslint.js:704:28)
    at RuleContext.report (~/code/eslint/eslint/lib/rule-context.js:96:16)
    at ~/code/eslint/eslint/lib/rules/no-shadow.js:38:25
    at Array.forEach (native)
    at checkShadowsInScope (~/code/eslint/eslint/lib/rules/no-shadow.js:36:19)
    at EventEmitter.checkForShadows (~/code/eslint/eslint/lib/rules/no-shadow.js:54:13)
    at EventEmitter.emit (events.js:95:17)
    at Controller.controller.traverse.enter (~/code/eslint/eslint/lib/eslint.js:657:25)
    at Controller.__execute (~/code/eslint/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (~/code/eslint/eslint/node_modules/estraverse/estraverse.js:495:28)
```

The offending section of `lib/rules/no-shadow.js`:

```js
29 /**
30  * Checks if the given variables are shadowed in the given scope.
31  * @param {Array} variables The variables to look for
32  * @param {Object} scope The scope to be checked.
33  * @returns {void}
34  */
35 function checkShadowsInScope(variables, scope) {
36     variables.forEach(function (variable) {
37         if (isContainedInScopeVars(variable, scope.variables)) {
38             context.report(variable.identifiers[0], "{{a}} is already declared in the upper scope.", {a: variable.name});
39         }
40     });
41 }
```

The `arguments` variable introduced by the function scope shadows the outer `arguments` variable. It tries to warn using the location of the inner (implicit) `arguments` variable's declaration, but there's no corresponding `VariableDeclarator` node in the AST.

**Comment by michaelficarra** [comment]
Seems like you should just except variables named `arguments` from this rule.

**Comment by gcochard** [comment]
Arguably, it's a better idea to not name any variables `arguments`, as using this code in a different environment will introduce subtle errors that the author may not have expected.

For example: using a variable named `arguments` is a syntax error in strict mode.

Additionally, this does actually shadow in the node environment when not in strict mode due to [the way node wraps javascript files](https://github.com/joyent/node/blob/v0.10.36/src/node.js#L910-L913).

Perhaps this rule should use the `context.settings.environments` object to determine (with relatively strong confidence) whether `arguments` is *actually* being shadowed.

Side note: Is the `context.settings` object exposed to the rule?

**Comment by nzakas** [comment]
Regardless of what people name their variables, the rule shouldn't crash. That's really the bottom line in this situation.

@gcochard please see the docs: http://eslint.org/docs/developer-guide/working-with-rules.html#the-context-object

**Comment by gcochard** [comment]
Definitely should not crash. I think I got distracted by the subtle issues inherent in naming a variable `arguments`. Does using `context.settings.environments` make sense and seem in scope for this rule?

**Comment by nzakas** [comment]
It doesn't make a lot of sense to me, as there is no `context.settings.environments`. I don't want to solve anything Node.js-related for this. We already have a tracking issue for Node.js scope (#892), and it's far more complicated than reading which environment is being used.

**Comment by michaelficarra** [comment]
@gcochard:

```
$ node
> (function(){ var arguments; console.dir(arguments); }(0, 1, 2))
{ '0': 0, '1': 1, '2': 2 }
```

This is not shadowing. It is a re-declaration. The only place you can *create* an `arguments` variable is in the global scope, to which you don't have lexical access in node.

**Comment by ilovejary** [comment]
How about making sure the test only runs when ```node``` is defined?

```
/**
 * Checks if the given variables are shadowed in the given scope.
 * @param {Array} variables The variables to look for
 * @param {Object} scope The scope to be checked.
 * @returns {void}
 */
function checkShadowsInScope(variables, scope) {
    variables.filter(function (variable) {
        return (typeof variable.identifiers[0] !== "undefined");
    }).forEach(function (variable) {
        if (isContainedInScopeVars(variable, scope.variables)) {
            context.report(variable.identifiers[0], "{{a}} is already declared in the upper scope.", {a: variable.name});
        }
    });
}
```

**Comment by nzakas** [comment]
Working on this.
