### ISSUE TITLE
Change Request: Drop Node v12/v14/v16/v17/v19 support

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#17595]
### ESLint version

8.49.0

### What problem do you want to solve?

ESLint v8 supports `"node": "^12.22.0 || ^14.17.0 || >=16.0.0"`.

Node 12, 14, 16, 17, 19 are EOL.

* Node 12 EOL: 2022-04-30
* Node 14 EOL: 2023-04-30
* Node 16 EOL: 2023-09-11 (https://nodejs.org/en/blog/announcements/nodejs16-eol)
* Node 17 EOL: 2022-06-01
* Node 19 EOL: 2023-06-01

### What do you think is the correct solution?

In v9, we'd drop support for EOL versions and keep only Node 18, Node 20, and above.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

At the moment, I don't have a concrete proposal for minor versions of Node 18 and Node 20 we'd like to support. Any suggestions?

**Comment by nzakas** [comment]
Most recent versions at the moment: v18.18.0 and v20.7.0.

**Comment by LewisIsWorking** [comment]
Quite frustrating how soon node 19 will be EOL, especially given not everything supports node 20 yet.

**Comment by kibertoad** [comment]
@mdjermanovic Are there any features in semver minor of 18.x that ESLint could benefit from?

**Comment by nzakas** [comment]
@kibertoad that's what we need to find out. Would you be interested in researching what has been added in the various semver minor releases and commenting back here?

**Comment by kibertoad** [comment]
I'd be happy to

**Comment by ota-meshi** [comment]
I think with Node v18 we can remove `graphemer` and use `Intl.Segmenter` instead.

**Comment by nzakas** [comment]
@kibertoad do you still intend to  do this?

**Comment by kibertoad** [comment]
@nzakas yes. please give me time until Monday (eod)

**Comment by nzakas** [comment]
@kibertoad sounds good. Thanks!

**Comment by kibertoad** [comment]
One day late, but I've finally started the research today.

**Comment by kibertoad** [comment]
* CLI Test runner (18.1.0) - in case you are considering switching to `node:test`
* node:test mocking (18.11.0)
* parseArgs module (18.3.0) - **might be interesting**.
* Experimental ESM Loader Hooks API (18.6.0) - probably not relevant
* Runtime userland snapshots (18.8.0) - not sure if relevant
* Watch mode (18.11.0) - not sure if relevant
* buffer.isUtf8 for utf8 validation (18.14.0) - **might be interesting**
* buffer: add isAscii method (18.15.0) - **might be interesting**
* implement URL.canParse (18.17.0)
* add recursive option to readdir and opendir (18.17.0)
* esm: add --import flag (18.18.0)

**Comment by ljharb** [comment]
probably best to start with v20.9.0 then, since there’s no long term support for any v20 releases before then

**Comment by mdjermanovic** [comment]
> Since we opened this, v20 has gone LTS, so I'd suggest we set our minimum v18 version at v18.18.0.
> 
> For v20, I'd suggest we set our minimum to be v20.7.0, unless anything super useful has been released since then.

Sounds good to me. 

In the meantime, Node.js 21 has been released. The latest version is v21.1.0, so perhaps we could set the requirements to:

```
^18.18.0 || ^20.7.0 || >=21.1.0
```

Thoughts?

**Comment by nzakas** [comment]
Works for me.

**Comment by ljharb** [comment]
(again, tho, i'd start with 20.9.0 and not 20.7.0 since 20.9 is LTS and 20.7 is not)

**Comment by nzakas** [comment]
I'm fine with that. @mdjermanovic ?

**Comment by mdjermanovic** [comment]
Makes sense to me. I updated https://github.com/eslint/eslint/pull/17725 with `^20.9.0`.

**Comment by sam3k** [comment]
Per 2023-11-30 tsc-meeting decision, this issue has been set to `ready to merge`.
