### ISSUE TITLE
Change Request: eslint-disable-next-line rule name should not be literal

### ISSUE THREAD

**Issue by mkroman** [eslint/eslint#17598]
### ESLint version

v8.49.0

### What problem do you want to solve?

The `eslint-disable-next-line` magic comment feature treats the rule name as literal characters and doesn't handle quoted strings, whereas the `eslint` magic comment processes quoted strings.

This creates an discrepancy between the two commands.

To provide a user story:

I wanted to disable a rule for a single line of code, and searching initially led me to the [**Configure Rules**](https://web.archive.org/web/20230922165926/https://eslint.org/docs/latest/use/configure/rules#rules-from-plugins) page where there was the following quote:

> You can also use this format with configuration comments, such as:
>
> ```
> /* eslint "plugin1/rule1": "error" */
> ```

This led me to believe that rules for third-party plugins (i.e. namespaced packages) required quotation marks, so that's what I did. Then I noticed the rule was applied globally..

That's when I found out about the `eslint-disable-next-line` comment, and I tried changing the comment from:

```js
/* eslint "@typescript-eslint/no-explicit-any": "off" */
```

to:

```js
/* eslint-disable-next-line "@typescript-eslint/no-explicit-any" */
```

and I was met by the following error:

```
/…/src/index.ts
…
  59:3   error  Definition for rule '"@typescript-eslint/no-explicit-any"' was not found            "@typescript-eslint/no-explicit-any"
```

### What do you think is the correct solution?

The `eslint-disable-next-line` magic comment should add support for stringy syntax, such that the following comments all have the same effect:

* `/* eslint-disable-next-line @typescript-eslint/no-explicit-any */`
* `/* eslint-disable-next-line "@typescript-eslint/no-explicit-any" */`
* `/* eslint-disable-next-line '@typescript-eslint/no-explicit-any' */`

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks, this is definitely a bug. (FWIW, it's helpful to file using "Report a Problem" template when something appears to be a bug.)

We should allow the same format for rule names in all of the configuration comments.

**Comment by nzakas** [comment]
It looks like this can be fixed by stripping the quotes in this function:
https://github.com/eslint/eslint/blob/main/lib/linter/config-comment-parser.js#L136

@mkroman would you like to submit a pull request for this fix?

**Comment by ota-meshi** [comment]
May I work on this issue?

**Comment by mkroman** [comment]
> It looks like this can be fixed by stripping the quotes in this function: https://github.com/eslint/eslint/blob/main/lib/linter/config-comment-parser.js#L136
> 
> @mkroman would you like to submit a pull request for this fix?

Thanks, but I'd rather if someone else with more experience did this.

@ota-meshi would be fine by me.

**Comment by mdjermanovic** [comment]
We should also update the code that removes unused disabled directives. When removing only some rules but not the whole comment, It should account for possible quotes around rule names.

**Comment by ota-meshi** [comment]
@mdjermanovic  Thank you for your comment. I think I added test cases to check them.

**Comment by nzakas** [comment]
Thanks @ota-meshi!
