### ISSUE TITLE
Warning: Object.keys called on non-object

### ISSUE THREAD

**Issue by bierik** [eslint/eslint#1760]
Hi there.

I got the following error when i was trying to lint with the grunt-eslint plugin.

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeConfigs (/Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/util.js:35:12)
    at /Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/util.js:60:25
    at Array.forEach (native)
    at mergeConfigs (/Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/util.js:35:25)
    at /Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/util.js:60:25
    at Array.forEach (native)
    at Object.mergeConfigs (/Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/util.js:35:25)
    at Config.getConfig (/Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/config.js:282:19)
    at processFile (/Users/kbieri/bricoler/simplelayout/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:131:31)
```

According to https://github.com/sindresorhus/grunt-eslint/issues/47 it's not an issue in the plugin.

Thanks for help.

**Comment by bierik** [comment]
Sorry guys I used a rule in a wrong way for escaping quotes.

**Comment by nzakas** [comment]
That's okay, can you share which rule? Even if you misconfigure, ESLint shouldn't throw an error.

**Comment by ot-brett-jones** [comment]
I got this error because of invalid json. I forgot to provide a value for the last line "no-mixed-spaces-and-tabs". Here is what I had in my .eslintrc. 

```javascript
{
  "env": {
    "browser": true,
    "node": true
  },
  "globals": {
    "angular": true
  },
  "rules": {
      "no-use-before-define": "nofunc",
      "strict": false,
      "eol-last": false,
      "no-underscore-dangle": false,
      "quotes": [1, 'double'],
      "no-space-before-semi": [1],
      "no-dangle-comma": [0],
      "indent": 4,
      "no-mixed-spaces-and-tabs"
  }
}
```

**Comment by nzakas** [comment]
Oh very interesting! We should at least be able to tell you that's the problem when it happens.

**Comment by glenjamin** [comment]
picking this up

**Comment by glenjamin** [comment]
This occurred because the file shown above is valid YAML, and the value of that rule key becomes null.

```js
yaml.safeLoad(require('fs').readFileSync('bust.json','utf8'))
{ env: { browser: true, node: true },
  globals: { angular: true },
  rules:
   { 'no-use-before-define': 'nofunc',
     strict: false,
     'eol-last': false,
     'no-underscore-dangle': false,
     quotes: [ 1, 'double' ],
     'no-space-before-semi': [ 1 ],
     'no-dangle-comma': [ 0 ],
     indent: 4,
     'no-mixed-spaces-and-tabs': null } }
```

**Comment by glenjamin** [comment]
I've pushed a PR that treats a `null` value as if the key wasn't there.

I could probably make it error on `null`, but that would likely be a larger change as currently there isn't any schema checking of config files before merging them together - and knowing this is an error relies on knowing valid values for this particular key.

**Comment by nzakas** [comment]
I don't think we should quietly fail in this case because the error might never be found. I'd just throw an error saying "Invalid configuration for rule-name". That at least warns that there's a problem to fix.

**Comment by glenjamin** [comment]
@michaelficarra At the moment there's no validation on rules at all, there's already https://github.com/eslint/eslint/issues/967 which dicusses why this is quite an involved change.

@nzakas would the better fix to add some basic config validation on each config file, that runs before merging, and that disallows `null` as a rule config value?

**Comment by nzakas** [comment]
That's a much larger effort, which is why it hasn't been done yet (see #967). The easiest path forward here is to throw an error.

**Comment by glenjamin** [comment]
Have pushed another draft - the logic has to live in `config.js` rather than `mergeConfig` in `util.js` as there isn't enough context to detect the error otherwise. Unless we say that `null` is never a valid value in a config file anywhere.
