### ISSUE TITLE
Support rest spread

### ISSUE THREAD

**Issue by pstoica** [eslint/eslint#1761]
JSX currently supports using spread for object properties like here: https://github.com/sebmarkbage/ecmascript-rest-spread

I noticed eslint supports spread properties in JSX tags, but not anywhere else. Is this something that can be supported? I know it's only proposed for ES7, but it might be good to lint considering it's available to use.

**Comment by nzakas** [comment]
This is purely dependent on the parser. When the parser supports it, so will we.

**Comment by aesopwolf** [comment]
@nzakas it looks like espree supports this now. is there something eslint has to do, or should it just happen automatically?
