### ISSUE TITLE
Bug: [flat config] ESLint continues linting files after an error occurs

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#17621]
### Environment

Node version: v20.7.0
npm version: v10.1.0
Local ESLint version: v8.50.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

I updated the `no-undef` rule to throw an error on the first file it gets. Then I ran `npx eslint .` 

### What did you expect to happen?

ESLint to print the error and then finish right after.

### What actually happened?

ESLint prints the error, but after that it takes 20 seconds for the command prompt to appear again because ESLint keeps linting other files after the error is thrown. This seems unnecessary as it will not change the outcome.

### Link to Minimal Reproducible Example

```
git fetch origin
git checkout origin/issue17621-repro
npx eslint .
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

I believe this happens because all tasks have already been added to the queue. If we want to fix this behavior, the change would probably be in this part of the code:

https://github.com/eslint/eslint/blob/dd79abc0c1857b1d765acc312c0d6518e40d31c9/lib/eslint/flat-eslint.js#L785-L879

**Comment by fasttime** [comment]
I am able to reproduce this issue. Marking as accepted as there is agreement that this is a bug in the comments to #17560.

**Comment by arka1002** [comment]
Hi, I just had a question - the `throw` which is coming from no-undef.js, that isnt failing the `Promise.all` ? 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#promise.all_fail-fast_behavior

**Comment by mdjermanovic** [comment]
> Hi, I just had a question - the `throw` which is coming from no-undef.js, that isnt failing the `Promise.all` ?
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#promise.all_fail-fast_behavior

It does fail, but it doesn't abort pending promises.

```js
console.time("track");

Promise.all([
    Promise.reject(),
    new Promise(resolve =>
        setTimeout(() => {
            resolve();
            console.timeLog("track", "settled second Promise");
        }, 10000)
    )
]).catch(() => {
    console.timeLog("track", "failed Promise.all");
});

process.on("exit", () => {
    console.timeLog("track", "exit");
});

/*

track: 0.496ms failed Promise.all
track: 10.006s settled second Promise
track: 10.007s exit

*/

```

**Comment by snitin315** [comment]
I'll look into it.
