### ISSUE TITLE
Bug: Eslint throws jsx-a11y/label-has-associated-control when the input is labeled correctly

### ISSUE THREAD

**Issue by radekbys** [eslint/eslint#17634]
### Environment

Node version: v18.18.0
npm version: 10.1.0
Local ESLint version: 
    "eslint": "^8.50.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0"
Global ESLint version:  none
Operating System: Fedora 38

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "name": "meme-generator",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "PORT=2000 react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^8.50.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0"
  }
}

```
</details>

```js
import React, { useState } from 'react';
import './Meme.css';

function Meme() {
  const [firstName, setFirstName] = useState('');

  console.log(firstName);

  const handleChange = (event) => {
    event.preventDefault();
    const newVal = event.target.value;
    setFirstName(newVal);
  };

  return (
    <div className="meme-box">

      <form>
        <label>
          input
          <input
            type="text"
            placeholder="placeholder"
            onChange={handleChange}
          />
        </label>
      </form>

    </div>
  );
}

export default Meme;
```

### What did you expect to happen?

I expected the code to execute without issue. Input is placed within a label

### What actually happened?

[eslint] 
src/components/meme/Meme.jsx
  Line 37:9:  A form label must be associated with a control  jsx-a11y/label-has-associated-control

Search for the keywords to learn more about each error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-uvxfak

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

seems to work correctly in stackblitz

**Comment by nzakas** [comment]
This is coming from `eslint-plugin-jsx-a11y`. Please open an issue on that plugin.
