### ISSUE TITLE
Add support for Meteor environment.

### ISSUE THREAD

**Issue by johanbrook** [eslint/eslint#1763]
Eslint should support the [Meteor](http://meteor.com/) JS framework! Meteor exposes *many* globals, which is tedious to ignore for every new Meteor project. This should warrant adding a `meteor` environment to Eslint.

I added support for Meteor globals in version 6.1.0 of the [globals](https://github.com/sindresorhus/globals) module (dependency of Eslint). 

Supporting Meteor would thus be a matter of upgrading the `globals` dependency to 6.1.0 and referring to them in the [environments.js](https://github.com/eslint/eslint/blob/master/conf/environments.js) file.

I'm happy to file a PR after upgrading the dependency and running tests.

**Comment by nzakas** [comment]
Sounds good. Please be sure to read our contribution guidelines: http://eslint.org/docs/developer-guide/contributing.html

**Comment by johanbrook** [comment]
Sure. PR submitted: https://github.com/eslint/eslint/pull/1764.
