### ISSUE TITLE
Bug: prefer-template doesn't handle ternary operator

### ISSUE THREAD

**Issue by jramsley** [eslint/eslint#17659]
### Environment

Node version: v20.2.0
npm version: v9.6.6
Local ESLint version: v7.31.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.6.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Going through my company's codebase, we have some conditional concatonated strings that use ternary operators.  I am switching everything over to using string templates instead and using `prefer-template` to auto-fix. 
 It caused one string to no longer parse properly, which `fix` shouldn't do.  The string had a ternary operator in it.</summary>

```
{
    "env": {
        "es6": true
    },
    "rules": {
        "prefer-template": [
            "error"
        ]
    },
    "parserOptions": {
        "ecmaFeatures": {},
        "ecmaVersion": "latest",
        "sourceType": "script"
    }
}
```
</details>

original
```js
const str = 'First ' + CONDITIONAL ? 'true' : 'false';
```

fixed
```js
const str = `First ${  CONDITIONAL}` ? 'true' : 'false';
```

eslint playground:
https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3Qgc3RyID0gJ0ZpcnN0ICcgKyBDT05ESVRJT05BTCA/ICd0cnVlJyA6ICdmYWxzZSc7Iiwib3B0aW9ucyI6eyJlbnYiOnsiZXM2Ijp0cnVlfSwicnVsZXMiOnsicHJlZmVyLXRlbXBsYXRlIjpbImVycm9yIl19LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCJ9fX0=

### What did you expect to happen?

I would expect the string to convert to
```js
const str = `First ${ CONDITIONAL ? 'true' : 'false' }`;
```

### What actually happened?

```js
const str = `First ${  CONDITIONAL}` ? 'true' : 'false';
```

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3Qgc3RyID0gJ0ZpcnN0ICcgKyBDT05ESVRJT05BTCA/ICd0cnVlJyA6ICdmYWxzZSc7Iiwib3B0aW9ucyI6eyJlbnYiOnsiZXM2Ijp0cnVlfSwicnVsZXMiOnsicHJlZmVyLXRlbXBsYXRlIjpbImVycm9yIl19LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCJ9fX0=

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Easy enough to work around, but effectively mutates the string.

**Comment by mdjermanovic** [comment]
Hi @jramsley, thanks for the issue!

> ### What did you expect to happen?
> I would expect the string to convert to
> 
> ```js
> const str = `First ${ CONDITIONAL ? 'true' : 'false' }`;
> ```
> 
> ### What actually happened?
> ```js
> const str = `First ${  CONDITIONAL}` ? 'true' : 'false';
> ```

This works as intended because the actual result is equivalent to the original code.

`const str = 'First ' + CONDITIONAL ? 'true' : 'false';` is the same as `const str = ('First ' + CONDITIONAL) ? 'true' : 'false';`

```js
const CONDITIONAL = false;

const str = 'First ' + CONDITIONAL ? 'true' : 'false'; // 'First' + false is truthy, so this evaluates to 'true'

console.log(str); // `true`
```
