### ISSUE TITLE
Change Request: expect-error comment similar to ts-expect-error

### ISSUE THREAD

**Issue by nicogreenarry** [eslint/eslint#17670]
### ESLint version

v8.28.0

### What problem do you want to solve?

This was requested [in this issue](https://github.com/eslint/eslint/issues/15709) and the issue was closed, but I have a use case not mentioned in that issue.

There are times I want to disable a rule for a line, but want to be notified if someone breaks the rule in another way. For example, suppose I'm excluding a dependency from a react hook:
```
useEffect(() => {
  console.log(allColumns, state.hiddenColumns)
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [state.hiddenColumns])
```

`eslint-disable-next-line` works fine here, except that if anyone adds code to this useEffect block, they could add a new dependency, and forget to add it to the dependency array. Eslint will no longer help, since I've told eslint to disable that rule here.

What I really want is a way of telling eslint, "Ignore this rule if it's specifically `allColumns` that's excluded from the dependencies array, but complain otherwise. E.g. I want to write something like this:
```
  // eslint-expect-error-next-line: React Hook useEffect has a missing dependency: 'allColumns'. Either include it or remove the dependency array.
}, [state.hiddenColumns])
```

That line would do two things:
1. It would suppress the normal eslint exception occurring on the dependency array line, as long as my expect-error message matches the actual error
2. It would receive an eslint exception if the eslint exception on the following line is something different. (Edit: Or if the next line didn't actually have any eslint exception.)

FYI @loynoir 

### What do you think is the correct solution?

Described above

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. I'm on the fence about this. I can see why it would be useful, but I also think the added complexity to support what is an edge case may not be worth the tradeoff. I'd like to hear what other team members think.

**Comment by fasttime** [comment]
I don't have strong opinion about this, but if that rule was a built-in rule, a better solution would have been to add an option to specify a list of dependencies to be flagged or excluded from flagging, e.g.

```js
useEffect(() => {
  console.log(allColumns, state.hiddenColumns)
  // eslint "react-hooks/exhaustive-deps": ["error", { "exceptions": ["allColumns"] }]
}, [state.hiddenColumns])
```

The advantage being that one could reuse that configuration across multiple files.

**Comment by mdjermanovic** [comment]
I see this as two functionally distinct requests:

1. A new type of directive that errors if the expected lint problem is not found.
2. Ability to target specific messages.

As for 1), I think that's already covered by reporting unused disable directives CLI/config option, as explained in https://github.com/eslint/eslint/issues/15709.

As for 2), that could be an additional feature in `eslint-disable` directives?

```js
  // eslint-disable-next-line react-hooks/exhaustive-deps: React Hook useEffect ...
}, [state.hiddenColumns])
```

My opinion is also neutral. I agree with @nzakas that this looks like an edge case, and with @fasttime that it might be better to address this in the rule by providing an option for exceptions.

**Comment by nicogreenarry** [comment]
It occurs to me that I could work around this issue by doing the following, with the `exhaustive-deps` rule specifically. Suppose I have this code:
```
useEffect(() => {
  // Code that uses variables a, b, c, d

  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [a, b])
```

So I only want my callback to run when `a` or `b` update. But I'm worried that if this code later changes to also include variable `e`, then we'll forget to add `e` to the dependencies array, even if it should be included.

The solution: Stop disabling the lint rule, and use a helper `ref` variable for the variables that shouldn't trigger the callback again. E.g.:
```
// Some optional comment explaining why these variables are excluded from the dependencies array
const helperRef = useRef({c, d})
useEffect(() => {
  // Code that uses variables a, b, helperRef.current.c, helperRef.current.d
}, [a, b])
```

eslint doesn't expect refs to be in the dependencies array (indeed, it would make no sense to list them there), and that makes it clear to the reader that the variables are very deliberately excluded.

So I no longer need this particular change. Thanks for considering it, y'all!

**Comment by gBasil** [comment]
This would be a useful feature when doing things like scaffolding a project, where you want to quickly define something, but implement the logic later. I think this issue should be reopened.
