### ISSUE TITLE
Change Request: Consider also moving slightly-more-than-formatting rules out of core

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#17681]
### ESLint version

8.52.0

### What problem do you want to solve?

(Moving https://github.com/eslint/eslint/issues/17522#issuecomment-1775868616 here) Following up on rules such as `curly` and `padding-line-between-statements` (https://github.com/eslint-stylistic/eslint-stylistic/issues/26 -> https://github.com/eslint-stylistic/eslint-stylistic/issues/26#issuecomment-1773890620): there are some core rules that aren't quite covered by some or all formatters, but are still within the realm of what eslint-stylistic would cover. Could we also move those rules out of core, with the intent to move them to eslint-stylistic?

### What do you think is the correct solution?

Rules such as `curly` that are at or just above the formatting level suffer from many of the maintainability drawbacks mentioned in #17522.  The eslint-stylistic project is intentionally named _stylistic_ rather than _formatting_ so that it can encompass more than just formatting rules. See https://github.com/eslint-stylistic/eslint-stylistic/issues/26.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Sorry for raising this so late after the initial discussion!

**Comment by nzakas** [comment]
We already decided to keep `curly` and deprecate `padding-line-between-statements`.

What other rules are you referring to?

**Comment by JoshuaKGoldberg** [comment]
> We already decided to keep `curly`

I'm proposing that be reconsidered. Going through the blog post and rules list, the list I'm proposing for this issue is:

* `curly`
* `multiline-comment-style`
* `line-comment-position`

To be honest, I was busy over the last month and wasn't able to find time to think deeply and comment in #17522. I wish I had posted this issue as a comment >2 weeks ago.

**Comment by nzakas** [comment]
The decision on `curly` has already been made, and we discussed why we want to keep it on #17522, so we're not revisiting that.

I don't have a strong opinion about the other two, so I'd be fine with deprecating them. Do Prettier and/or dprint handle those?

**Comment by nzakas** [comment]
@MrHBS @meerhimmel I already answered about `curly` and `no-unexpected-multiline` on the [original issue](https://github.com/eslint/eslint/issues/17522#issuecomment-1741018139). We are not revisiting those decisions.

**Comment by nzakas** [comment]
@antfu do you have a list of additional rules that you think would make more sense to be in eslint-stylistic than the core?

**Comment by antfu** [comment]
For ESLint Stylistic we don't have a strong opinion on what rules to include, we generally take what ESLint/ts-eslint deprecated, as long as they fit in the category of "Stylistic".

Personally, I agree with Josh at https://github.com/eslint/eslint/issues/17681#issuecomment-1783731342

**Comment by Samuel-Therrien-Beslogic** [comment]
Crosslinking https://github.com/typescript-eslint/typescript-eslint/issues/8102 and https://github.com/eslint-stylistic/eslint-stylistic/issues/238 as it is stuck in this weird limbo of "Stylistic, but still in core, so no one touches it"

**Comment by Rec0iL99** [comment]
Ping @eslint/eslint-team. What are the next steps here?

**Comment by nzakas** [comment]
Where we're at here is deciding whether we want to deprecate these two rules:

* `multiline-comment-style`
* `line-comment-position`

I'm fine with that, as they are just enforcing preferences. @mdjermanovic @fasttime what do you think?

**Comment by fasttime** [comment]
> Where we're at here is deciding whether we want to deprecate these two rules:
> 
>     * `multiline-comment-style`
> 
>     * `line-comment-position`

I think it makes sense to move these rules to `@stylistic` to ensure that they are properly maintained. So I'm in favor of deprecating them at this point.

**Comment by nzakas** [comment]
**TSC Summary:** This issue seeks to deprecate two additional rules, `multiline-comment-style` and `line-comment-position`, and allow `@stylistic` to take over maintenance in the plugin.

**TSC Question:** Shall we do so?

**Comment by sam3k** [comment]
Per 2024-04-04 TSC meeting, we've decided to deprecate these two rules and coordinate with `eslint-stylistic` to incorporate and maintain them going forward.
