### ISSUE TITLE
CLIEngine: quiet option

### ISSUE THREAD

**Issue by matz3** [eslint/eslint#1768]
As [grunt-eslint](https://github.com/sindresorhus/grunt-eslint) was switching from cli to CLIEngine, the "quiet" option does not work anymore.
Any chance to move this feature into CLIEngine to be able to use it from there?

reference https://github.com/sindresorhus/grunt-eslint/issues/48

**Comment by nzakas** [comment]
Quiet only has to do with output and CLIEngine is designed specifically to not output anything. So, it's not possible to add this functionality to CLIEngine.

**Comment by matz3** [comment]
Thanks for your fast feedback!
