### ISSUE TITLE
Change Request: Also find `eslintConfig` in `package.yaml` manifest (support `pnpm`)

### ISSUE THREAD

**Issue by danielbayley** [eslint/eslint#17686]
### ESLint version

v8.52.0

### What problem do you want to solve?

Since `pnpm` supports `package.yaml` (see: https://github.com/pnpm/pnpm/pull/1799), it would be useful if an `eslintConfig` property would also be respected from this alternative manifest format. `json5` is also a possibility.

### What do you think is the correct solution?

Since this project already supports reading config from YAML files, this should be an easy win…

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
`eslintConfig` is part of the old eslintrc configuration system that we are deprecating. All configuration will need to be in `eslint.config.js` going forward, so we can't make that compatible with `package.yaml`.

**Comment by danielbayley** [comment]
> `eslintConfig` is part of the old eslintrc configuration system that we are deprecating. All configuration will need to be in `eslint.config.js` going forward, so we can't make that compatible with `package.yaml`.

@nzakas What about situations where the only configuration needed is:
~~~ yaml
eslintConfig:
  extends: "@scoped/preset"
~~~
?

Seems far from ideal to be _forced_ to have yet another root config file containing barely 2 lines of code…

**Comment by Rec0iL99** [comment]
One of the main goals we wanted to achieve with the new config system is to have one place where the ESLint config can be for a project, instead of having multiple ways to do the same thing.

You can read our blog series on this to understand why the new config system was needed.

https://eslint.org/blog/2022/08/new-config-system-part-1
