### ISSUE TITLE
`space-unary-ops` massive false positive

### ISSUE THREAD

**Issue by zloirock** [eslint/eslint#17684]
### Environment

Node version: 21.1.0
npm version: 10.2.0
Local ESLint version: 8.52.0
Global ESLint version: -
Operating System: macOS 14.1

### What parser are you using?

Default (Espree)

### What did you do?

After forced updating of `core-js` dev dependencies, I see:

![image](https://github.com/eslint/eslint/assets/2213682/71fb9ff3-5e35-4630-a555-5dc898ebf4c1)

In all cases, it the `new` keyword case.

The rule settings are default, `space-unary-ops: 'error'`. Changing options does not change anything.

`eslint` or plugins versions are not changed, updated only `acorn` to `8.11.0` and `@eslint-community/regexpp` to `4.10.0`.

Codebase: https://github.com/zloirock/core-js
ESLint config: https://github.com/zloirock/core-js/blob/master/tests/eslint/eslint.config.js
Dependencies: https://github.com/zloirock/core-js/blob/master/tests/eslint/package.json

**Comment by mdjermanovic** [comment]
This is probably a problem in the recently released Acorn v8.11.0.

Waiting for resolution of https://github.com/acornjs/acorn/issues/1252

**Comment by mdjermanovic** [comment]
The fix has been released in Acorn v8.11.1.

@zloirock, @Twipped can you reinstall dependencies and check if the problem is resolved?

**Comment by zloirock** [comment]
Yes, it seems it's fixed, thanks -)
