### ISSUE TITLE
Change Request: Fix fixable/suggestions info for deprecated and removed rules on Rules Reference page

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#17709]
### ESLint version

v8.53.0

### What problem do you want to solve?

On our [Rules Reference](https://eslint.org/docs/latest/rules/) page, it looks like all deprecated and removed rules were fixable and had suggestions:

![image](https://github.com/eslint/eslint/assets/44349756/ae10220a-0974-4690-9347-7e0e798203fa)

### What do you think is the correct solution?

Either remove 🔧 💡 icons or provide the correct info. For deprecated rules, it can be pulled from meta as they're still here, but for removed rules we would need to add it manually.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by kecrily** [comment]
I think it would be nice to just remove the emoji from the removed section.

**Comment by mdjermanovic** [comment]
> I think it would be nice to just remove the emoji from the removed section.

Makes sense to me for the removed section.

As for the deprecated section, we should either remove the emojis or provide the correct info.

**Comment by nzakas** [comment]
For removed rules, it makes sense to just not show the emoji.

For deprecated rules, we should make sure the information is correct because it's still useful to know if those rules have fixes and suggestions.
