### ISSUE TITLE
Add support for TypeScript or Merge with typescript-eslint as one project or monorepo

### ISSUE THREAD

**Issue by Barzi-Ahmed** [eslint/eslint#17719]
### ESLint version

N/A

### What problem do you want to solve?

We want to reduce our dependencies and vendors, dealing with two different projects and vendors ESLint and typescript-eslint for the same goal is an unnecessary added inefficiency and dependency risk. 

### What do you think is the correct solution?

I'd like ESLint to provide TypeScript support officially and as a first party, or it can merge with typescript-eslint together to become one strong project. This will improve collaboration and make development resourceful more efficient. 

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by kecrily** [comment]
Did you know that typescript-eslint was originally a fork of typescript-eslint-parser maintained by ESLint?

This is mentioned in typescript-eslint's README.md:

> typescript-eslint inherits from the original TypeScript ESLint Parser license, as the majority of the work began there. It is licensed under a permissive BSD 2-clause license.

---

In addition, according to the [ESLint Language Plugins RFC](https://github.com/eslint/rfcs/pull/99), ESLint will eventually become a language-independent, more generalized linter. You can follow its progress at https://github.com/eslint/eslint/issues/16999.

---

Based on these two points, I don't think ESLint will ever merge with typescript-eslint.
