### ISSUE TITLE
DeprecationWarning: Punycode

### ISSUE THREAD

**Issue by jasperkelder** [eslint/eslint#17720]
### ESLint version

8.53.0

### What problem do you want to solve?

One of eslint's dependencies is using a deprecated module, we're currently getting the following warning -> DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

└─┬ eslint@8.53.0
  └─┬ ajv@6.12.6
    └─┬ uri-js@4.4.1
      └── punycode@2.3.0

### What do you think is the correct solution?

Make sure the deprecated module gets replaced in the dependency tree.

**Comment by Rec0iL99** [comment]
Hi @jasperkelder, thanks for the issue. I don't think this is something to be solved in ESLint. ESLint directly depends on `ajv` and there is an [open issue](https://github.com/ajv-validator/ajv/issues/2343) addressing this there.

**Comment by domdomegg** [comment]
I've opened a PR to fix this in uri-js, the package ajv depends on here: https://github.com/garycourt/uri-js/pull/95

**Comment by newinfinity12** [comment]
> I've opened a PR to fix this in uri-js, the package ajv depends on here: [garycourt/uri-js#95](https://github.com/garycourt/uri-js/pull/95)
@domdomegg 
still not fixed. would also like to note that eslint uses ajv v6.12.6 instead of the latest v8.12.0 from a year ago

**Comment by Rec0iL99** [comment]
> would also like to note that eslint uses ajv v6.12.6 instead of the latest v8.12.0 from a year ago

@newinfinity12 perhaps this https://github.com/eslint/eslint/issues/13888#issuecomment-872591875 will help you understand why ESLint still uses `Ajv 6`.

**Comment by newinfinity12** [comment]
> > would also like to note that eslint uses ajv v6.12.6 instead of the latest v8.12.0 from a year ago
> 
> @newinfinity12 perhaps this [#13888 (comment)](https://github.com/eslint/eslint/issues/13888#issuecomment-872591875) will help you understand why ESLint still uses `Ajv 6`.

@Rec0iL99
great resource however that does not change the fact that eslint is indirectly using a deprecated dependency.

Based on the threads created in Ajv and URI.js the blame/fix keeps getting pushed around to different repos. Ajv has not been updated in over a year and URI.js in over 3 years. So based on this info it looks like eslint should switch to a different repo to avoid the deprecation warning altogether

**Comment by domdomegg** [comment]
> > I've opened a PR to fix this in uri-js, the package ajv depends on here: [garycourt/uri-js#95](https://github.com/garycourt/uri-js/pull/95)
> 
> @domdomegg still not fixed. would also like to note that eslint uses ajv v6.12.6 instead of the latest v8.12.0 from a year ago

@newinfinity12 the way node resolves dependencies will mean that updating uri-js as a minor or patch version will still fix it, even though eslint uses ajv 6

**Comment by newinfinity12** [comment]
> > > I've opened a PR to fix this in uri-js, the package ajv depends on here: [garycourt/uri-js#95](https://github.com/garycourt/uri-js/pull/95)
> > 
> > 
> > @domdomegg still not fixed. would also like to note that eslint uses ajv v6.12.6 instead of the latest v8.12.0 from a year ago
> 
> @newinfinity12 the way node resolves dependencies will mean that updating uri-js as a minor or patch version will still fix it, even though eslint uses ajv 6

@domdomegg
The only issue as I mentioned mentioned here https://github.com/eslint/eslint/issues/17720#issuecomment-1892188205 is that uri-js has not been updated in over 3 years so it will likely not be updated. So what would be the solution? Wait indefinitely until the maintainer of uri-js decides to update it?

**Comment by iwasrobbed** [comment]
@Rec0iL99 eslint will require an update to fix this whenever ajv eventually fixes it, so either way this issue should remain open here (especially given how far behind on major/minor versions eslint is for ajv).

**Comment by andreinwald** [comment]
Hi there,
I created a replacement for library uri-js as temporal solution.
- Based on Node.js and browser URL api
- 99% compatible with original URI.js library
- Solves "The punycode module is deprecated" warning in Node
- Tested with libraries: ESLint, Webpack, Ajv (runned all ESLint tests)

https://github.com/andreinwald/uri-js-replace

You can add to package.json of your project:
```json
"overrides": {
    "uri-js": "npm:uri-js-replace"
 }

**Comment by alap-apexon** [comment]
> Hi there, I created a replacement for library uri-js as temporal solution.
> 
> * Based on Node.js and browser URL api
> * 99% compatible with original URI.js library
> * Solves "The punycode module is deprecated" warning in Node
> * Tested with libraries: ESLint, Webpack, Ajv (runned all ESLint tests)
> 
> https://github.com/andreinwald/uri-js-replace
> 
> You can add to package.json of your project:
> 
> ```json
> "overrides": {
>     "uri-js": "npm:uri-js-replace"
>  }
> ```

Did not work for me. 
My node version is 22.1.0

**Comment by alapanerao** [comment]
> Hi there, I created a replacement for library uri-js as temporal solution.
> 
> * Based on Node.js and browser URL api
> * 99% compatible with original URI.js library
> * Solves "The punycode module is deprecated" warning in Node
> * Tested with libraries: ESLint, Webpack, Ajv (runned all ESLint tests)
> 
> https://github.com/andreinwald/uri-js-replace
> 
> You can add to package.json of your project:
> 
> ```json
> "overrides": {
>     "uri-js": "npm:uri-js-replace"
>  }
> ```

Did not work for me.
My node version is 22.1.0
