### ISSUE TITLE
Rule Change: no-unused-vars: add ignore by type option

### ISSUE THREAD

**Issue by erosman** [eslint/eslint#17757]
### What rule do you want to change?

no-unused-vars

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
// side effect module
class Something {

  static {
    this.set();
  }

  static set() {
    // do something
  }
}
```

### What does the rule currently do for this code?

ESLint generates an error

### What will the rule do after it's changed?

As posted to [varsIgnorePattern to ignore unused class names](https://github.com/eslint/eslint/discussions/17743), it would be beneficial to have an ignore by type option.

For example:
```
no-unused-vars: ["error", { "ignoreType": ["class"] }]
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
Hi @erosman, thanks for the issue!

Can you provide more details about the motivation for this change, in particular what are side effect modules and why the code needs to be wrapped in a class?

**Comment by erosman** [comment]
> [Import a module for its side effects only](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only)
> 
> Import an entire module for side effects only, without importing anything. This runs the module's global code, but doesn't actually import any values. 
> ```js
> import "/modules/my-module.js";
> ```
> This is often used for [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill), which mutate the global variables.

On occasions, there are codes snippets that run verbatim without any interaction. Using ESM, they can be imported without any `export`.

For example, I use a module to implement i18n in HTML documents in all my extensions. Once it is imported, it runs its course without any further interaction. 

In order to implement an auto-run code in a module, the code may be:

- without any functions
- with function and invoker or IIFE (Immediately Invoked Function Expression)
- with class and initialiser
- with class but without initialiser

Here are some very basic examples:

1. **mod.js** without any functions

```js
document.title = 'New Title';
```

2. **mod.js** with function and invoker

```js
function run() {
  document.title = 'New Title';
}
run();
```

3. **mod.js** with class and initialiser

```js
class Mod {
  run() {
    document.title = 'New Title';
  }
}

Mod.run();
```

4. **mod.js** with class but without initialiser

```js
class Mod {
  static {
    document.title = 'New Title';
  }
}
```


While there are differing opinions among developers on the mortis of each method, I favour `class` without initialisers which provides total encapsulation, in addition to not having to create a new instance of the `class` (on top of the original).

The last module format generates an error in ESLint.

> 'Mod' is defined but never used.  ([no-unused-vars](https://eslint.org/docs/rules/no-unused-vars))

The purpose of this post is to add an option to ignore such classes.

**Comment by kecrily** [comment]
I think just using configuration comments is enough for this case. `ignoreType` may cause unplanned ignoring problems.

**Comment by erosman** [comment]
> I think just using configuration comments is enough for this case. ignoreType may cause unplanned ignoring problems.

That is true.

I have also used inline "eslint-disable-next-line no-unused-vars" which seems to be fine.
Therefore, I am going to close this request.

---

### Just for clarification purposes

> However, this just seems like a stylistic preference to me since I don't see any benefit to wrapping the code in classes instead of writing top-level code in modules

True, however ...

IMHO, the best OOP are the ones that are fully self-sufficient.

You will find 8 examples of such OOP (_inline and not a side-effect module_), in [options.js](https://github.com/foxyproxy/browser-extension/blob/main/src/content/options.js) which are completely encapsulated and self-sufficient. They do their job without requiring any interaction from the other parts of the code.
_(There are also side-effect examples in the same repo)._
