### ISSUE TITLE
New Rule: enforceSafeSpreadOrder

### ISSUE THREAD

**Issue by randomhash** [eslint/eslint#17769]
### Rule details

Rule must prevent propery injection through the payloads

### Related ECMAScript feature

Object spread

### What type of rule is this?

Enforces a formatting/stylistic preference

### Example code
Bad:
```js
const params = {tenantId: id, ...searchOptions}
const params = {...options, tenantId: id, ...searchOptions}
await func({tenantId: id, ...searchOptions, ...options})
```
In this case, tenantId may be rewritten by the searchOptions and compromise application security
To avoid such unintended situations we would want to warn developers about danger and try to rearrange the actual order of the spread
Good:
```js
const params = {...searchOptions, tenantId: id}
const params = {...options, ...searchOptions, tenantId: id}
await func({...searchOptions, ...options, tenantId: id})
```

Problems around this may not be impactful in the short run, as for example searchOptions are validated, but security vulnerabilities are commonly a combination of few small ones.
```


### Why should this rule be in the core instead of a plugin?

I believe that this rule will improve security posture of the codebases that are using eslint

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

_No response_

**Comment by mdjermanovic** [comment]
Hi @randomhash, thanks for the issue!

There are many valid use cases where spread appears after other properties, so I'm not in favor of adding a core rule that generally disallows this.

If you have a specific property name that should never be possibly overwritten this way, you can configure the [`no-restricted-syntax`](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule to disallow that. For example, this is a selector for `tenantId` property name:


```
ObjectExpression > Property[key.name='tenantId'] ~ SpreadElement
```

Here's a [playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtc3ludGF4OiBbXCJlcnJvclwiLCBcbiAgICB7XG4gICAgICAgIHNlbGVjdG9yOiBcIk9iamVjdEV4cHJlc3Npb24gPiBQcm9wZXJ0eVtrZXkubmFtZT0ndGVuYW50SWQnXSB+IFNwcmVhZEVsZW1lbnRcIixcbiAgICAgICAgbWVzc2FnZTogXCJEYW5nZXIsIHRoaXMgY2FuIG92ZXJ3cml0ZSAndGVuYW50SWQnLiBSZWFycmFuZ2UgdGhlIG9yZGVyLlwiXG4gICAgfVxuXSovXG5cbi8vIEJhZFxuY29uc3QgcGFyYW1zMSA9IHt0ZW5hbnRJZDogaWQsIC4uLnNlYXJjaE9wdGlvbnN9XG5jb25zdCBwYXJhbXMyID0gey4uLm9wdGlvbnMsIHRlbmFudElkOiBpZCwgLi4uc2VhcmNoT3B0aW9uc31cbmF3YWl0IGZ1bmMoe3RlbmFudElkOiBpZCwgLi4uc2VhcmNoT3B0aW9ucywgLi4ub3B0aW9uc30pXG5cbi8vIEdvb2RcbmNvbnN0IHBhcmFtczMgPSB7Li4uc2VhcmNoT3B0aW9ucywgdGVuYW50SWQ6IGlkfVxuY29uc3QgcGFyYW1zNCA9IHsuLi5vcHRpb25zLCAuLi5zZWFyY2hPcHRpb25zLCB0ZW5hbnRJZDogaWR9XG5hd2FpdCBmdW5jKHsuLi5zZWFyY2hPcHRpb25zLCAuLi5vcHRpb25zLCB0ZW5hbnRJZDogaWR9KSIsIm9wdGlvbnMiOnsiZW52Ijp7ImVzNiI6dHJ1ZX0sInBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fSwiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIn0sInJ1bGVzIjp7fX19) with this selector and the examples you provided.
