### ISSUE TITLE
Inconsistent documentation for `ecmaVersion`

### ISSUE THREAD

**Issue by donalmurtagh** [eslint/eslint#17771]
### Environment

N/A

### What parser are you using?

Default (Espree)

### What did you do?

In the documentation for the new flat config [an example](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuring-the-javascript-version) configures the JavaScript as `languageOptions.ecmaVersion`.

However, [an example in the migration guide](https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options), the path to this property is `languageOptions.parserOptions.ecmaVersion`.

### What did you expect to happen?

The path to this property should be the same throughout the docs

### What actually happened?

The path to this property is not the same throughout the docs

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @donalmurtagh, thanks for the issue. 

> In the documentation for the new flat config [an example](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuring-the-javascript-version) configures the JavaScript as languageOptions.ecmaVersion.

> However, [an example in the migration guide](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuring-the-javascript-version), the path to this property is languageOptions.parserOptions.ecmaVersion.

Both of these example links are pointing to the same docs link. Can you please correct it?

**Comment by donalmurtagh** [comment]
@Rec0iL99 sorry about that, I've updated the links

**Comment by Rec0iL99** [comment]
I don't think there is a mistake in the docs. The migration guide indicates that the `parserOptions` key has been moved into the `languageOptions` key in the new config system. So, it is showing a difference between how a `parserOptions` key in `eslintrc` would look like in flat config. You can pass any required options via the `parserOptions` key for the parser to know when parsing code. Therefore, I think specifying `ecmaVersion` under `languageOptions.parserOptions` is not a mistake. To specify the JavaScript version ESLint should use during linting, you need to set it in `languageOptions.ecmaVersion` (the default is `ecmaVersion: "latest"`).

cc @mdjermanovic

**Comment by nzakas** [comment]
@donalmurtagh You're correct, the migration guide example is a mistake. When using the default parser, `ecmaVersion` and `sourceType` belong under `languageOptions` rather than `parserOptions`.

Would you be willing to submit a PR to correct that?
