### ISSUE TITLE
Bug: max-len ignore commentaries after string in case "ignoreStrings": true

### ISSUE THREAD

**Issue by victorcarvalhosp** [eslint/eslint#17798]
### Environment

Node version: v18.17.0
npm version: 9.6.7
Local ESLint version: 8.54.0
Global ESLint version: 8.54.0
Operating System: Mac OS

### What parser are you using?

Default (Espree)

### What did you do?

I have this configured on eslintrc.json file:

"max-len": [
          "error",
          {
            "code": 120,
            "ignoreComments": false,
            "ignoreStrings": true,
            "ignoreTrailingComments": false,
            "ignoreTemplateLiterals": true,
            "ignoreUrls": true,
            "ignoreRegExpLiterals": true
          }
        ],

And the rules works fine, except on this scenario:

`const myString = 'This is my string' // And this is a very long commentary that should trigger the lint rule as it has more than 120 characters lorem ipsum lorem ipsum lorem ipsum`

In case I move the commentary a line above or under the string, then the rule applies as expected:
`// And this is a very long commentary that should trigger the lint rule as it has more than 120 characters lorem ipsum lorem ipsum lorem ipsum
const myString = 'This is my string'`

or if I deactivate the "ignoreStrings" rule, then it works as expected too. But I expect both rules to work at the same time.

### What did you expect to happen?

Both commentaries should throw a proper max-len lint error when `"ignoreStrings": true`

### What actually happened?

Just if I moved the commentary to a separated line the lint error is thrown.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHF1b3RlczogW1wiZXJyb3JcIiwgXCJkb3VibGVcIl0gKi9cbmNvbnN0IGEgPSBcImJcIjsgLy8gVGhpcyBpcyBhIHZlcnkgbG9uZyBjb21tZW50YXJ5IHRoYXQgc2hvdWxkIHRocm93IGEgZXNsaW50IGFsZXJ0IGFzIGl0IGhhcyBtb3JlIHRoYW4gMTIwIGNoYXJhY3RlcnMgbG9yZW0gaXBzdW0gbG9yZW0gaXBzdW0iLCJvcHRpb25zIjp7ImVudiI6eyJlczYiOnRydWV9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCJ9LCJydWxlcyI6eyJtYXgtbGVuIjpbImVycm9yIix7ImNvZGUiOjEyMCwiaWdub3JlQ29tbWVudHMiOmZhbHNlLCJpZ25vcmVTdHJpbmdzIjp0cnVlLCJpZ25vcmVUcmFpbGluZ0NvbW1lbnRzIjpmYWxzZSwiaWdub3JlVGVtcGxhdGVMaXRlcmFscyI6dHJ1ZSwiaWdub3JlVXJscyI6dHJ1ZSwiaWdub3JlUmVnRXhwTGl0ZXJhbHMiOnRydWV9XX19fQ==

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @victorcarvalhosp, thanks for the issue. We aren't making any further changes to the [`max-len`](https://eslint.org/docs/latest/rules/max-len) rule since it has been [deprecated](https://eslint.org/blog/2023/10/deprecating-formatting-rules/) in v8.53.0.

**Comment by Rec0iL99** [comment]
You can find the corresponding rule in the [@stylistic/eslint-plugin-js](https://eslint.style/packages/js) plugin. Please open an issue there.
