### ISSUE TITLE
Change Request: Warn when `.eslintignore` detected with flat config

### ISSUE THREAD

**Issue by bmish** [eslint/eslint#17831]
### ESLint version

v8.55.0

### What problem do you want to solve?

After migrating my repository from `.eslintrc.js` to flat config `eslint.config.js`, I was confused by some additional linting errors that showed up. I then realized these linting errors were in files that were supposed to be ignored by `.eslintignore`. After doing some digging through ESLint github issues/PRs, I found out `.eslintignore` no longer works with flat config.

### What do you think is the correct solution?

1. Document that `.eslintignore` no longer works in the migration guide: https://eslint.org/docs/latest/use/configure/migration-guide
2. Most importantly, add an error or warning when `.eslintignore` is detected with flat config, similar to how we often show a warning when the user provides an option that has been removed/deprecated.

If we don't have automated detection for this, then inevitably a large percentage of users performing this migration will meet this same confusion, and some will forget to cleanup/delete their old `.eslintignore` file. Having an `.eslintignore` present with flat config is a recipe for confusion. I can imagine some users even trying to keep `.eslintignore` and `ignores` in `eslint.config.js` in sync because they aren't sure which they are supposed to use.

Ideally, we could throw an error to disallow this mistake entirely, especially since flat config isn't considered stable yet until ESLint v9. Otherwise, we can print a warning to the console. The error/warning message would describe the replacement for this file or link to documentation on it.

Concerns:
1. Is there any situation in which the user would need to ignore the presence of `.eslintignore`?

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Are there any other old files we should warn about to ease the migration? Should we warn when both `.eslintrc.js` and `eslint.config.js` are present?

### Related

* https://github.com/eslint/eslint/issues/17822
* https://github.com/eslint/eslint/pull/16434
* https://github.com/eslint/eslint/pull/16355

**Comment by ajiho** [comment]
I encountered the same problem and, like you, searched for issues/PRs and found the answer

**Comment by SiNONiMiTY** [comment]
Encountered this one too, should be documented. Good thing this PR exists.

**Comment by bmish** [comment]
While waiting to see if this issue will get accepted, I opened up a draft PR to begin proving out the implementation for an error in this scenario (will close the PR if the issue is not accepted):

* https://github.com/eslint/eslint/pull/17862

**Comment by bmish** [comment]
@eslint/eslint-tsc thoughts about a warning or error for this? An error would be a breaking change but I believe a warning would not be.

**Comment by nzakas** [comment]
We should definitely update the migration guide, no doubt about that.

I'm a little hesitant to always search for `.eslintignore` just to warn if it's found -- that's an extra filesystem call, and I generally don't like doing those unless we absolutely have to for performance reasons.

That said, I don't feel super strongly, so happy to go along with what the rest of the team thinks is the correct approach.

**Comment by aladdin-add** [comment]
I feel like it better be just a warning, not an error. users may just forget to remove it, and it does not stop eslint's functionality.

**Comment by sdavids** [comment]
This page should be updated too: https://eslint.org/docs/latest/use/configure/ignore

**Comment by nzakas** [comment]
@sdavids those are the docs for the old config system, so they should not be updated. The new ones are up in a PR: https://github.com/eslint/eslint/pull/17840

**Comment by nzakas** [comment]
After thinking about this for a bit, I'm slightly in favor of detecting the ignore file when in flat config mode.

I agree with @aladdin-add, I think this should be a warning and not error because it doesn't prevent ESLint from working, you just might not get the behavior you're expecting. (Same as when a file is passed on the CLI but is ignored, we warn for that.)

**Comment by nzakas** [comment]
Oh, and as a note: we are in development for v9 right now and aren't doing any further releases of v8, so all of the considerations about breaking vs. non-breaking are moot because this change will go out with v9 regardless.

**Comment by nzakas** [comment]
> Document that `.eslintignore` no longer works in the migration guide: https://eslint.org/docs/latest/use/configure/migration-guide

We already do this: https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files

> Are there any other old files we should warn about to ease the migration? Should we warn when both .eslintrc.js and eslint.config.js are present?

No. As I already mentioned, each of these is a filesystem call and I want to keep them to a minimum.

**Comment by snitin315** [comment]
I believe we can throw a warning here, it should not have a significant impact on performance.
