### ISSUE TITLE
Change Request: Replace `graphemer` with `Intl.Segmenter`

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint#17835]
### ESLint version

v8.55.0

### What problem do you want to solve?

Related to https://github.com/eslint/eslint/pull/17725#issuecomment-1834576019

If we use the new Node.js we can use `Intl.Segmenter` instead of `graphemer`.
`Intl.Segmenter` can be used to reduce ESLint's dependency packages.

### What do you think is the correct solution?

Replace `graphemer` with `Intl.Segmenter`.

before:

```js
    if (!splitter) {
        splitter = new Graphemer();
    }

    return splitter.countGraphemes(value);
```

after:

```js
    if (!segmenter) {
        segmenter = new Intl.Segmenter();
    }

    return [...segmenter.segment(value)].length;
```

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I tested the compatibility of `graphemer` and `Intl.Segmenter`. The test case in the `graphemer` repository did not change the result even if I replaced it with `Intl.Segmenter`.
However, "अनुच्छेद" in the README has a different result.

`graphemer`: `'अ', 'नु', 'च्', 'छे', 'द'`
`Intl.Segmenter`: `'अ', 'नु', 'च्छे', 'द'`

~~(It is not known whether this is a bug or intentional.)~~ See https://github.com/eslint/eslint/issues/17835#issuecomment-1849748312

The results will change, but I think it will be accepted by users as a minor breaking change if included in ESLint v9.

---

Repositories used for testing:
https://github.com/ota-meshi/graphemer/tree/compat-intl-segmenter
Commit:
https://github.com/ota-meshi/graphemer/commit/de301e6079e7e4d179a7ed88113e8e406033e77b

**Comment by ota-meshi** [comment]
> graphemer: 'अ', 'नु', 'च्', 'छे', 'द'
> Intl.Segmenter: 'अ', 'नु', 'च्छे', 'द'

Probably related to https://github.com/orling/grapheme-splitter/issues/22

**Comment by ota-meshi** [comment]
`graphemer` seems to be unicode v15.0 compliant and uses GraphemeBreakTest v15.0 for testing.
However, if I replace this with GraphemeBreakTest v15.1, `graphemer` will fail the test. The test also passes in GraphemeBreakTest v15.1 when using `Intl.Segmenter`.

https://github.com/flmnt/graphemer/blob/master/tests/GraphemeBreakTest.txt
https://www.unicode.org/Public/15.0.0/ucd/auxiliary/GraphemeBreakTest.txt
https://www.unicode.org/Public/15.1.0/ucd/auxiliary/GraphemeBreakTest.txt

**Comment by mdjermanovic** [comment]
> ```js
>  if (!segmenter) {
>         segmenter = new Intl.Segmenter();
>     }
> ```

Per [MDN - Intl.Segmenter() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter), it expects a `locales` argument. Per [locales argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument) docs, if it's omitted, the implementation's default locale will be used.

Does that mean that we could have different behavior in different environments? For example, linting passes locally but then fails on CI because the default locale is different?

**Comment by ota-meshi** [comment]
Hmm. There may be differences depending on locale.
I've read the following links but still can't find a concrete example.

https://github.com/tc39/proposal-intl-segmenter/blob/master/README.md#why-should-we-pass-a-locale-and-options-bag-for-grapheme-boundaries-isnt-there-just-one-way-to-do-it
https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries:~:text=tailored%20grapheme%20clusters%20for%20specific%20locales

**Comment by nzakas** [comment]
@ota-meshi are you still interesting in working on this? Are you still doing research?

**Comment by ota-meshi** [comment]
I haven't looked into it much since then. Perhaps the language in which the problem seems to be a language that is unfamiliar to me so I am having trouble understanding it 😓

**Comment by ota-meshi** [comment]
What do you think is the best way to resolve the issue of non-compliance with Unicode v15.1?
Would you like to close this issue by reporting it on `graphemer` repository?

**Comment by kecrily** [comment]
Can we specify `en-US` as the default language?

**Comment by ota-meshi** [comment]
That idea sounds good to me! At least I don't think the behavior will change depending on the environment.

**Comment by nzakas** [comment]
I think we're at the point where we either need someone to prototype this or we should close this issue. Any volunteers?

**Comment by fasttime** [comment]
I went ahead and prepared a draft: #18110.

One problem that hasn't been discussed yet is that `Intl.Segmenter` is not implemented in Firefox yet (though it could be soon, the corresponding issue is marked as fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1423593). This means that if a rule using `Intl.Segmenter` were opened in the Playground in Firefox, it would crash. So if we decide to go for this change, we should at least wait until `Intl.Segmenter` is supported in all major browsers.

**Comment by nzakas** [comment]
> One problem that hasn't been discussed yet is that `Intl.Segmenter` is not implemented in Firefox

Ooh, great catch! I agree, we should definitely hold off until Firefox supports this.

**Comment by nzakas** [comment]
Blocked by Firefox implementing Intl.Segmenter, so not stale.

**Comment by fasttime** [comment]
`Intl.Segmenter` is unflagged in Firefox 125, so we could consider using it instead of `graphemer` now. Anyway, there is also an alternative proposal to replace `graphemer` with a different package: #18359.

**Comment by nzakas** [comment]
I'd definitely prefer using `Intl.Segmenter`.
