### ISSUE TITLE
How to apply a legacy config to specific files

### ISSUE THREAD

**Issue by bmish** [eslint/eslint#17844]
For example, applying a test config like `mocha/recommended` or `jest/recommended` only to test files seems like a fairly common practice. But I haven't seen any official documentation on this.

I found one way to do it here:

```js
module.exports = [
    // Apply mocha config only to tests.
    ...compat.extends("plugin:mocha/recommended").map(config => ({ ...config, files: ["tests/**/*.js"] })),
];
```

Another similar example:

https://github.com/psychobolt/vite-storybook-boilerplate/blob/1356effb9bdd6f8d09a8c5557e4a8aa411904c68/packages/commons/eslint.config.ts#L20-L23

It may be worth documenting an example like this in the README.

**Comment by nzakas** [comment]
Transferred it over. I'm thinking we probably need a new page that is basically a guide to mixing and matching configs that you don't own. I'll take a look once I finish transferring all the documents over to flat config.
