### ISSUE TITLE
Bug: no-restricted-import exclusion pattern does not work

### ISSUE THREAD

**Issue by ShravanSunder** [eslint/eslint#17860]
### Environment

Node version: 20
npm version: 8 (using yarn v3)
Local ESLint version: 8.45.0
Global ESLint version: 
Operating System: mac os

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
rules: {
        "no-restricted-imports": [
          "error",
          {
            patterns: [
              {
                group: [
                  "!~modules/quick-view/*",
                  "~features/view/*",
                  "~features/edit/*",
                  "~features/list/*",
                  "~features/import/*",
                  "~modules/*",

                  /**
                   * NOTES: If there new modules, we need to restrict them
                   */
                ],
                message:
                  "You cannot import features into modules. Make sure you import from the same feature or from shared, or from the same modules",
              },
            ],
          },
        ],
      },
```
</details>

```js
rules: {
        "no-restricted-imports": [
          "error",
          {
            patterns: [
              {
                group: [
                  "!~modules/quick-view/*",
                  "~features/view/*",
                  "~features/edit/*",
                  "~features/list/*",
                  "~features/import/*",
                  "~modules/*",

                  /**
                   * NOTES: If there new modules, we need to restrict them
                   */
                ],
                message:
                  "You cannot import features into modules. Make sure you import from the same feature or from shared, or from the same modules",
              },
            ],
          },
        ],
      },

The exclusion patter (no matter what the order) does not take precedence over the inclusion pattern.  This is despite what the docs say:  https://eslint.org/docs/latest/rules/no-restricted-imports
```

### What did you expect to happen?

I would expect the example to be correct.  The exclusion pattern to take precedece over inclusion pattern.  
```
When using the object form, you can also specify an array of gitignore-style patterns:

"no-restricted-imports": ["error", {
    "paths": ["import1", "import2"],
    "patterns": ["import1/private/*", "import2/*", "!import2/good"]
}]

```

### What actually happened?

'~modules/quick-view/some-module' import is restricted from being used by a pattern. You cannot import features into modules. Make sure you import from the same feature or from shared, or from the same module seslint[no-restricted-imports](https://eslint.org/docs/latest/rules/no-restricted-imports)
module "/Users/shravan.sunder/dev/bills/bills-spa/src/spa/src/modules/quick-view/some-module"

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @ShravanSunder, thanks for the issue!

Can you please update the "What did you do" section to include an example, and also please provide a Link to Minimal Reproducible Example. It can be a link to [ESLint Playground](https://eslint.org/play/) with the example code and configuration.

Note that `patterns` in the no-restricted-imports rule work per the [.gitignore specification](https://git-scm.com/docs/gitignore), and that per the specification there's no precedence but the order of patterns matters:

> An optional prefix "!" which negates the pattern; any matching file excluded by a _previous_ pattern will become included again.

**Comment by Tanujkanti4441** [comment]
hi @ShravanSunder,
> Note that patterns in the no-restricted-imports rule work per the [.gitignore specification](https://git-scm.com/docs/gitignore), and that per the specification there's no precedence but the order of patterns matters:

you can share if this statement is solving your issue or not.
if not please share the code example (not just eslint configuration) that is reporting the issue.

**Comment by ShravanSunder** [comment]
## Reproduction
@mdjermanovic i'm not sure how to use [ESLint Playground](https://eslint.org/play/) to reproduce import rules.  It doesn't seem to support that?  

## Git ignore
@Tanujkanti4441 It doesn't look like it solved the issue.  

I've used this configuration as specified by gitignore.  Just to make sure i also tried reversing the order of modules and the negation.
```
rules: {
        "no-restricted-imports": [
          "error",
          {
            patterns: [
              {
                group: [
                  "~modules/*",
                  "!~modules/quick-view/*",
                  "~features/view/*",
                  "~features/edit/*",
                  "~features/list/*",
                  "~features/import/*",
                  /**
                   * NOTES: If there new modules, we need to restrict them
                   */
                ],
                message:
                  "You cannot import features into modules. Make sure you import from the same feature or from shared, or from the same modules",
              },
            ],
          },
        ],
      },
```
And just tried to import a file

```
import {someModule} from "~modules/quick-view/someModule";
```

It has a linting error, when it should not, so it does not work.  

## Tests for this rule
Additionally, there are not tests that use wildcards with disallow with this rule. https://github.com/eslint/eslint/blob/main/tests/lib/rules/no-restricted-imports.js
for example
```
{
            code: "import withPatterns from \"foo/bar\";",
            options: [{ patterns: [{ group: ["foo/*", "!foo/bar"], message: "foo is forbidden, use bar instead" }] }]
        },
```
where you check for `!foo/bar/*`

**Comment by Tanujkanti4441** [comment]
Here are the reproductions in playground

[negation before](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcmVzdHJpY3RlZC1pbXBvcnRzOiBbXCJlcnJvclwiLCB7IHBhdHRlcm5zOiBbe1xuICAgIGdyb3VwOiBbXCIhfm1vZHVsZXMvcXVpY2stdmlldy8qXCIsIFwifm1vZHVsZXMvKlwiLFwifmZlYXR1cmVzL3ZpZXcvKlwiLFwifmZlYXR1cmVzL2VkaXQvKlwiLFwifmZlYXR1cmVzL2xpc3QvKlwiLFwifmZlYXR1cmVzL2ltcG9ydC8qXCIsXSxcbiAgICBtZXNzYWdlOiBcIllvdSBjYW5ub3QgaW1wb3J0IGZlYXR1cmVzIGludG8gbW9kdWxlcy4gTWFrZSBzdXJlIHlvdSBpbXBvcnQgZnJvbSB0aGUgc2FtZSBmZWF0dXJlIG9yIGZyb20gc2hhcmVkLCBvciBmcm9tIHRoZSBzYW1lIG1vZHVsZXMuXCJcbn1dfV0qL1xuXG5pbXBvcnQgeyBzb21lTW9kdWxlIH0gZnJvbSBcIn5tb2R1bGVzL3F1aWNrLXZpZXcvc29tZU1vZHVsZVwiOyIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=)

[negation after](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tcmVzdHJpY3RlZC1pbXBvcnRzOiBbXCJlcnJvclwiLCB7IHBhdHRlcm5zOiBbe1xuICAgIGdyb3VwOiBbXCJ+bW9kdWxlcy8qXCIsXCIhfm1vZHVsZXMvcXVpY2stdmlldy8qXCIsXCJ+ZmVhdHVyZXMvdmlldy8qXCIsXCJ+ZmVhdHVyZXMvZWRpdC8qXCIsXCJ+ZmVhdHVyZXMvbGlzdC8qXCIsXCJ+ZmVhdHVyZXMvaW1wb3J0LypcIixdLFxuICAgIG1lc3NhZ2U6IFwiWW91IGNhbm5vdCBpbXBvcnQgZmVhdHVyZXMgaW50byBtb2R1bGVzLiBNYWtlIHN1cmUgeW91IGltcG9ydCBmcm9tIHRoZSBzYW1lIGZlYXR1cmUgb3IgZnJvbSBzaGFyZWQsIG9yIGZyb20gdGhlIHNhbWUgbW9kdWxlcy5cIlxufV19XSovXG5cbmltcG9ydCB7IHNvbWVNb2R1bGUgfSBmcm9tIFwifm1vZHVsZXMvcXVpY2stdmlldy9zb21lTW9kdWxlXCI7Iiwib3B0aW9ucyI6eyJlbnYiOnt9LCJydWxlcyI6e30sInBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fSwiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIn19fQ==)

**Comment by ShravanSunder** [comment]
@Tanujkanti4441 thanks for the help 🙇🏾 

So from my understanding:

### 1. Directory pattern:  (!~modules/quick-view):
This pattern tells Git to re-include the directory named quick-view inside the modules directory.
It does not explicitly specify the contents of the quick-view directory.
Git interprets this as an instruction to consider the quick-view directory itself for tracking, but this does not automatically include all files within it.


### 2. Glob Pattern (!~modules/quick-view/*):

This pattern is more specific. It's telling Git to re-include all files (* wildcard) inside the quick-view directory.
The key here is that it only applies to the files directly inside quick-view, not to the directory itself or to any subdirectories or files within those subdirectories.

### logic

So 1 might work because it excludes everything in the directory?  Where as 2 would only exclude files.   I'm not sure the full reasons, but looks like this works. 🤔   I will do some more testing

**Comment by Tanujkanti4441** [comment]
> I will do some more testing

let us know about them too and also if you still think this behavior is a bug.

**Comment by ShravanSunder** [comment]
@Tanujkanti4441 it looks like it works.

i think based on the docs for this rule, its just very hard to understand.

**Comment by snitin315** [comment]
@ShravanSunder Would you like to send a PR to improve the docs for this rule? or share what additional info can be added to the doc?
