### ISSUE TITLE
Change Request: Rewriting of output paths

### ISSUE THREAD

**Issue by MarttiR** [eslint/eslint#17918]
### ESLint version

v8.54.0

### What problem do you want to solve?

When running inside a Docker container, eslint shows paths based on its working directory:

```
/app/next/components/media--image.tsx
  25:20  error  Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator  @typescript-eslint/prefer-nullish-coalescing
```

This path doesn't match any path on the host machine. Terminals won't make it clickable either, so developers can't quickly open the relevant files in their IDE.

### What do you think is the correct solution?

I'd like there to be a configurable mechanism for rewriting the paths in the output, for example by a regexp substitution.

Something like this in the config:
```
"rewritePaths": {
  "/^\/app/": "./",
  "/^\/app/someotherpath/": "../../wherever",
}
```

This would make DX a lot better for teams who have their development environment containerized.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

There is a previous discussion on this issue: https://github.com/eslint/eslint/discussions/15115

**Comment by nzakas** [comment]
Can you explain a little bit more about your setup? When you say you're running inside a Docker container, how are you running ESLint? (Inside VS Code, on the command line, etc.?)

More details about your workflow would help us better understand what is happening.

Also, are there other related tools (Prettier, Jest, etc.) that seem to be handling filenames in the way you expect? If you could share that list it would help.

**Comment by rellafella** [comment]
I am experiencing a similar annoyance.
I have my project running inside a docker container (in this case configured using ddev), when I run my eslint task from the inbuilt terminal in vscode I get the filepath as an absolute path for the docker container's file system. It would be good to be able to rewrite the path so that I can click on the output and jump straight to that file.
![CleanShot 2024-01-25 at 5  35 31](https://github.com/eslint/eslint/assets/36829732/b5063787-b58c-49f6-90ce-9cb1f5a49382)

**Comment by kecrily** [comment]
I'm sure this can be done with a [custom formatter](https://eslint.org/docs/latest/extend/custom-formatters).

**Comment by MarttiR** [comment]
Sorry for the late reply.

> I am experiencing a similar annoyance. I have my project running inside a docker container (in this case configured using ddev), when I run my eslint task from the inbuilt terminal in vscode I get the filepath as an absolute path for the docker container's file system. It would be good to be able to rewrite the path so that I can click on the output and jump straight to that file. ![CleanShot 2024-01-25 at 5  35 31](https://private-user-images.githubusercontent.com/36829732/299566479-b5063787-b58c-49f6-90ce-9cb1f5a49382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzUzODgsIm5iZiI6MTcwNjc3NTA4OCwicGF0aCI6Ii8zNjgyOTczMi8yOTk1NjY0NzktYjUwNjM3ODctYjU4Yy00OWY2LTkwY2UtOWNiMWY1YTQ5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMWZmNWMyNjIxZmQwN2U1NDMwMWRkOTlhNWEzZWJmY2YwYWNhMGE1YmYxZTkxYTc2MTAxMzA0YTdjMTU5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lJJEKNLUGqT-Y9xK_PAVFnwn2pakXxBZLznl5ji-Og)

This is exactly my use case as well.

> Can you explain a little bit more about your setup? When you say you're running inside a Docker container, how are you running ESLint? (Inside VS Code, on the command line, etc.?)

It's a [Lando](https://lando.dev/) setup. `eslint` is run using `lando npm run eslint <paths...>`, which runs `npm run eslint` inside the development container.

VSCode linting is of course the primary feedback loop, but as a fallback we also use a pre-commit hook, and that is currently outputting paths that are non-clickable.

> I'm sure this can be done with a [custom formatter](https://eslint.org/docs/latest/extend/custom-formatters).

I'm sure of that as well, but I would rather customize the setup as little as possible.
