### ISSUE TITLE
Comment configuration of rule doesn't work

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#1792]
Thanks for bringing in the `indent` rule. :+1: 

It works perfectly fine in all scenarios except when I activate the rule like this 
`/* eslint indent: [2, 4, {indentSwitchCase: true}] */`
And this is when I declare this rule on top of the file. Then it doesn't work.

It also breaks my inline eslint config.

**Comment by nzakas** [comment]
What does "it doesn't work" mean? Do you get errors you don't expect? Does ESLint crash? Please be specific and include sample code plus the console output.

**Comment by gyandeeps** [comment]
I used the rule like this in my file:
```
/* eslint quotes:0, indent: [2, 2, {indentSwitchCase: true}] */
```

It doesnt work. Even it throws "quotes" error tho i have it turned off.

But if I use the rule like this in my file:
```
/* eslint quotes:0, indent: [2, 2, {"indentSwitchCase": true}] */
```

Then it works fine.

I think we need to fix the documentation of the rule to have double quotes around the option.

**Comment by nzakas** [comment]
Okay, so it's not about the rule, it's about configuring inline with comments. 

It looks like quotes are required, but we're swallowing errors if it fails to parse. We should probably throw an error in this case.

**Comment by gyandeeps** [comment]
I saw the unit test for indent rule. They all use args like this 
`indent: [2, 2, {indentSwitchCase: true}]`
and they all pass.  Because i would expect the unit test to fail.
Is there a bug in testing framework?

**Comment by nzakas** [comment]
No. The unit tests are not using comments to change configuration.
