### ISSUE TITLE
Docs: Incorrect example for "Reporting unused disable directives"

### ISSUE THREAD

**Issue by martypdx** [eslint/eslint#17959]
### Docs page(s)

https://eslint.org/docs/latest/use/configure/configuration-files-new#reporting-unused-disable-directives

### What documentation issue do you want to solve?

Current example is `reportUnusedDisableDirectives: "error"`

Should be boolean value like in the blog post example

### What do you think is the correct solution?

`reportUnusedDisableDirectives: true`

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

1. This causes eslint to fail to load in vscode with generic "TypeError: Expected a Boolean." so consequence is severe for copying this example.
2. The button link at the bottom of the page to edit gives `404`. I would have done a PR to just fix. Is the file on a different branch?

**Comment by mdjermanovic** [comment]
Hi @martypdx, thanks for the issue!

Which version of ESLint are you using? `reportUnusedDisableDirectives: "error"` should work with the latest v8.56.0.

**Comment by fasttime** [comment]
Hi @martypdx! The documentation page you are reading is correct with respect to the latest version of ESLint, currently v8.56.0. In previous versions, the only valid settings for the `reportUnusedDisableDirectives` option were `true` (now superseded by `"warn"`) or `false` (`"off"`). So there was no direct equivalent of the current `"error"` setting, and the `TypeError` you are getting for using an invalid setting was expected.

I think the previous documentation is no longer available on the ESLint website, but you can still view it on GitHub: https://github.com/eslint/eslint/blob/v8.55.0/docs/src/use/configure/configuration-files-new.md#reporting-unused-disable-directives.

The only real bug I see in your report is that the edit button at the bottom of the page points to a dead link. Can you post that as a new issue?
