### ISSUE TITLE
"Exit code is now error count" breaking CI code

### ISSUE THREAD

**Issue by doberkofler** [eslint/eslint#1795]
Version 0.14.0 of eslint has changed the exit code to be equal to the number of errors and breaks quite a few tests in my CI environment.
I did not find any issue on this and would like to understand why this change has been introduced and suggest to rather differentiate between errors and warning as this is something that I currently do with a separate parsing step and might come useful to others as well.

Exit codes:
0 - success
1 - error (like before and therefore not changing existing uses of eslint)
2 - warning

**Comment by michaelficarra** [comment]
* This is the commit: https://github.com/eslint/eslint/commit/ff35ae1936709bd837ad51a0ee175c996e580b9b
* When there's only warnings, eslint should have a 0 exit code as it does now, not 2 as you suggest.
* (any multiple of) 256 errors will have a 0 exit code. That seems like a bug.

**Comment by doberkofler** [comment]
* I've looked at the commit but there is no information on why the change has been made.
* Why would you think that having a separate exit code for only warnings would be wrong ?
* You are right. I missed the module 256 problem, so it should anyway be changed.

**Comment by michaelficarra** [comment]
It would be wrong because warnings shouldn't fail a build.

**Comment by doberkofler** [comment]
I guess you are right and only treating 0 as success is the most generic way of using an exit code although in my (buildbot based) CI environment, we differentiate between errors (interrupting a build) and warnings that are reported but do allow the build to continue.

**Comment by nzakas** [comment]
Sorry for the confusion around this. I was cleaning up the CLI interface and thought it would be more useful to return the error count rather than just 1. Most CI systems treat any value greater than 0 the same.

However, this is clearly a bug due to the 255 limit that will cause the exit code to cycle around. I'll get that fixed.
