### ISSUE TITLE
Docs: list wrong number of code path events

### ISSUE THREAD

**Issue by Richardinho** [eslint/eslint#17968]
### Docs page(s)

https://eslint.org/docs/latest/extend/custom-rules#accessing-code-paths

### What documentation issue do you want to solve?

section reads:
> ESLint analyzes code paths while traversing AST. You can access code path objects with five events related to code paths. 
However, there are 7 events, according to this page https://eslint.org/docs/latest/extend/code-path-analysis

### What do you think is the correct solution?

Change first page to give the correct number of events.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> ESLint analyzes code paths while traversing AST. You can access code path objects with five events related to code paths.
> However, there are 7 events, according to this page https://eslint.org/docs/latest/extend/code-path-analysis

> Change first page to give the correct number of events.

Thanks for finding this, a PR to fix the docs is welcome 👍
