### ISSUE TITLE
Change Request: Add a shareable config like recommended for modern ES consumers

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#17975]
### ESLint version

8.56.0 / 9.0.0-alpha.0

### What problem do you want to solve?

Per https://github.com/eslint/eslint/issues/17974#issuecomment-1881743962, `eslint:recommended` / `@eslint/js`'s `recommended` is able to be used by consumers in environments at least as far back as ES3. While that's useful & necessary for those users, it's inconvenient for the majority of users as it prevents enabling rules or rule options that only work in newer ECMAScript versions in the recommended config.

A few points blocked on this:

* #17974
* I would guess rules that require newer syntax -`no-var`, `prefer-rest-params`, `prefer-spread`- are as well
* Edit: Setting `dot-notation`'s `allowKeywords` to `false` by default (thanks https://github.com/eslint/eslint/issues/17974#issuecomment-1881951718 <- @fasttime) 

Most users of ESLint extend from the recommended preset and then only customize as issues come up. So not enabling some features in recommended means most users won't benefit from them.

### What do you think is the correct solution?

I think I can see two options for satisfying the request to enable these newer syntax oriented options or rules in a built-in shareable config:

* _(Not a breaking change)_ Creating a separate config like `eslint:esnext` / `eslint:recommended-esnext` for the newer language targets, keeping `eslint:recommended` the same 
* _(Breaking change)_ Creating an older config like `eslint:legacy` / `eslint:recommended-legacy` for the older language targets, changing `eslint:recommended`

I would personally suggest and prefer the latter as a breaking change in v10, so that most users get the benefits of the more fully featured recommended config.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

The [typescript-eslint `eslint-recommended` preset](https://typescript-eslint.io/linting/configs#eslint-recommended) is a somewhat useful reference, as some of the rules it enables are oriented around encouraging more modern constructs (the aforementioned blocked rules).

**Comment by nzakas** [comment]
I'm having trouble understanding why this is necessary. It seems like you've outlined a couple of rule options that could be tweaked, but otherwise, I'm not sure I see the benefit of having to maintain a second config. 

I guess I'm having a hard time grasping the problem that you're trying to solve. What is the pain users are experiencing right now with the current recommended config?

I'm also not sure where the idea that the recommended config needs to target ES3 came from...that's certainly not something we have documented as a requirement anywhere.

So, I need a lot more context to understand why we'd want two configs instead of figuring out the best settings for one.

**Comment by JoshuaKGoldberg** [comment]
> What is the pain users are experiencing right now with the current recommended config?

The current recommended config does not enable some more-strict-than-default rule options. I believe those rule options are useful and most projects using the recommended config would benefit from them being enabled by default. 

My understanding from https://github.com/eslint/eslint/issues/17974#issuecomment-1881743962 is that legacy ES3 support was the main blocker from enabling those options by default. But if that's not the case, then great! I can file issues about enabling them separately if so.

**Comment by nzakas** [comment]
Let's just use this issue to discuss what changes you'd like to make and we can go from there.

I'm not sure where the ES3 comment comes from -- the goal with `eslint:recommended` was always to provide a good baseline for folks regardless of the environment in which they're running JavaScript, but I don't think that necessarily means lowest possible denominator. And certainly as we set the default to "latest" in flat config, we can revisit some of what's in `eslint:recommended`.

**Comment by JoshuaKGoldberg** [comment]
I don't think there's anything else left to do here? Since #17974 was accepted and merged, it seems the recommended config is cleared to not adhere to ES3/5.

**Comment by nzakas** [comment]
Agreed. Let's close this in favor of more rule-specific changes.
