### ISSUE TITLE
Docs: eslint 9.0.0-alpha.0 mentioned removed methods from `context`, but they are still present

### ISSUE THREAD

**Issue by thepassle** [eslint/eslint#17972]
### Docs page(s)

The release page for `eslint@9.0.0-alpha.0` mentions that a lot context methods have been *removed*, but when trying out the release, it seems like the methods are still there. Is this an oversight? Are they still to be removed?

https://eslint.org/blog/2023/12/eslint-v9.0.0-alpha.0-released/#removed-deprecated-methods-on-context-and-sourcecode

I checked and verified locally that the methods are still there by creating an empty repo, running `npm run -D eslint@9.0.0-alpha.0`, adding a `eslint.config.js` with the following contents:
```js
export default [
  {
    files: ["*.js"],
    rules: {
      "security/no-innerhtml": "error",
    },
    plugins: {
      security: {
        rules: {
          "no-innerhtml": {
            meta: {
              type: "suggestion",
              docs: {
                description: "Don't use innerHTML",
                category: "Security",
                recommended: true,
                url: "../../docs/rules/no-innerhtml.md",
              },
              messages: {
                linkAttrs: "Don't use innerHTML",
              },
              fixable: null,
              schema: [],
            },
            create(context) {
              // throw new Error(context);
              console.log(2222, context.getSourceCode());
              return {
                Identifier(node) {
                  if (node.name === "innerHTML") {
                    if (node.parent?.parent?.type === "AssignmentExpression") {
                      console.log(context.getSourceCode());
                    }
                  }
                },
              };
            },
          },
        },
      },
    },
  },
];

```

and creating an `index.js` with:
```js
document.innerHTML = 'foo';
```

### What documentation issue do you want to solve?

-

### What do you think is the correct solution?

-

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
It seems that `context.getSourceCode()` is deprecated, not removed. This is mentioned in [this earlier blog post](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) and also indicated in the [documentation](https://eslint.org/docs/next/extend/custom-rules#the-context-object). Maybe the difference is not immediately clear, or did you spot any inconsistent information in particular?

**Comment by nzakas** [comment]
The removed methods were listed in the migration guide:
https://eslint.org/docs/next/use/migrate-to-9.0.0#-removed-multiple-context-methods

All others have remained. `getSourceCode()` is deprecated and not removed.
