### ISSUE TITLE
Docs: Add a Glossary page

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#17987]
### Docs page(s)

https://eslint.org/docs/latest/glossary

### What documentation issue do you want to solve?

There are a lot of terms around linting / ESLint that many users have trouble with:

* The difference between rule _"fixes"_ and _"suggestions"_ (https://github.com/eslint/eslint.org/issues/479)
* The specific terms used to describe types of rules: _"formatting"_, _"logical"_, and _"style"_ (https://github.com/eslint/eslint.org/issues/419)
* Terms relevant to linting or popular lint rules that many developers have trouble with: _"callback"_, _"expression"_, _"executor"_, _"identifier"_, _"scope"_, etc.
* Terms specific to linting (or contexts for existing terms): _"formatter"_, _"override"_, _"node"_, _"parser"_, _"plugin"_, _"report"_, _"rule"_, _"violation"_, ...really everything in the AST - and AST itself.

Many of those terms are explained within https://eslint.org/docs/latest/use right now, and especially within https://eslint.org/docs/latest/use/core-concepts. But those docs are written in long-form and meant to be consumed as a large entity. It's hard to find answers to a single _"what does '...' mean?"_ question within them.

### What do you think is the correct solution?

I'd love a dedicated _Glossary_ page in the site that succinctly describes what each of these terms mean & links to the docs that introduce each of them. That way, if someone asks what a term means, we can give them a more precise answer than a general docs page.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Other examples in the wild of "glossary" vs "use" splits in docs:
* https://codecademy.com/docs is an example of a general-purpose coding glossary
* https://react.dev has a split between "learn" and "reference"

**Comment by nzakas** [comment]
@JoshuaKGoldberg do you intend to work on this?

**Comment by JoshuaKGoldberg** [comment]
Hi, yes! Sorry for the delay - will clean & push up what I have this week.
