### ISSUE TITLE
Docs: options section in `no-restricted-import` rule

### ISSUE THREAD

**Issue by Tanujkanti4441** [eslint/eslint#18002]
### Docs page(s)

https://eslint.org/docs/latest/rules/no-restricted-imports

### What documentation issue do you want to solve?

`no-restricted-imports` rule has lots of options and all are explained with a one line description in a row with no particular heading, i think this make it a little bit complex to understand at first and also  PR #16196 and issue #15261 may add new feature or option and will need to be arranged properly in the docs.

### What do you think is the correct solution?

every option can have it's own dedicated section with correct/incorrect examples.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sounds like a good idea. Go for it! :+1:
