### ISSUE TITLE
Bug: AST is `undefined` on Windows when more than one file with upper-case char in filename

### ISSUE THREAD

**Issue by nbolton** [eslint/eslint#18003]
### Environment

Node version: v18.19.0
npm version: 10.2.3
Local ESLint version: v8.46.0
Global ESLint version: n/a
Operating System: Windows 10

### What parser are you using?

@typescript-eslint/parser

### What did you do?

This bug doesn't seem to be relevant to ESLint config or source file. It's a transient hard to reproduce issue related to the Windows filesystem. I have access to multiple Windows computers, and it only happens on one of them.

This might be relvant: It's an Nx project.

Files matched under `tsconfig.lib.json`:
```
"include": ["src/**/*.ts"]
```

I narrowed the problem down to `node_modules\@typescript-eslint\typescript-estree\dist\create-program\getWatchProgramsForProjects.js`:
```
        if (fileList.has(filePath)) {
            log('Found existing program for file. %s', filePath);
            updatedProgram ??= existingWatch.getProgram().getProgram();
            // sets parent pointers in source files
            updatedProgram.getTypeChecker();
            return [updatedProgram];
        }
```

For some reason, `updatedProgram` doesn't contain the source file that is being linted:
```
updatedProgram.getSourceFiles().map(file=>file.fileName).join(", ")
```

The filename is missing from this list.

### What did you expect to happen?

On Windows, an AST for all file names included in `tsconfig.json` should be found. 

### What actually happened?

When it comes to filenames with upper-case chars only the first one is included. Filenames with lower-case and numbers load the AST fine. This results in the following error, despite this file definitely being included in the file list:

```
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/libs\config\src\BuildConfig.ts` usinng `parserOptions.project`:
- <tsconfigRootDir>/libs\config\tsconfig.lib.json
- <tsconfigRootDir>/libs\config\tsconfig.spec.json
However, none of those TSConfigs include this file. Either:
- Change ESLint's list of included files to not include this file
- Change one of those TSConfigs to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-tellling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```
![image](https://github.com/eslint/eslint/assets/313427/743b1cbb-fb14-4059-8b0e-8983c6ee4929)

Watch has 0 elements:
`updatedProgram.getSourceFiles().filter(file => file.fileName.includes("buildconfig.ts"))`

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
This is actually an issue with [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) rather than ESLint itself. Please open an issue there.

**Comment by nbolton** [comment]
> Please open an issue there.

No problem, on it.
