### ISSUE TITLE
Docs: Breaking Changes for v9 is missing an entry for eslint-env / environments

### ISSUE THREAD

**Issue by Standard8** [eslint/eslint#18012]
### Docs page(s)

https://eslint.org/docs/next/use/migrate-to-9.0.0

### What documentation issue do you want to solve?

The document doesn't mentioned that `/* eslint-env <name> */` has now been removed, nor does it mention that environments are will not available from plugins in the same way (it is mentioned in the plugin migration guide, but no-where else as far as I can see).

As this is a breaking change, I think it should be documented. It might be nice to also reference the decision where it was made to drop support for it.

### What do you think is the correct solution?

Add documentation for the change.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by snitin315** [comment]
This is mentioned in the [configuration migration guide](https://eslint.org/docs/next/use/configure/migration-guide#eslint-env-configuration-comments), that is linked under the [New default config format](https://eslint.org/docs/next/use/migrate-to-9.0.0#-new-default-config-format-eslintconfigjs) section in migration guide.

**Comment by nzakas** [comment]
Closing, as the documentation already exists.
