### ISSUE TITLE
Bug: eslint still validates file with eslint-disable on the top

### ISSUE THREAD

**Issue by jeengbe** [eslint/eslint#18022]
### Environment

Node version: n/a
npm version: n/a
Local ESLint version: 8.48.0
Global ESLint version: n/a
Operating System: n/a

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
  "rules": {
    "@typescript-eslint/prefer-nullish-coalescing": "error"
  }
}
```

```json
{
  "compilerOptions": {
    "strict": true
  }
}
```

</details>

```ts
/* eslint-disable */
declare const x: any;

x || true;
```

### What did you expect to happen?

This issue is not about https://github.com/typescript-eslint/typescript-eslint/issues/8261, instead, the crash is used to show that the file is still processed even though it has an `/* eslint-disable */` in the first row.

While I assume that the directive works by simply suppressing errors generated in the succeeding lines, it would be useful to test for it in the top of a file to ignore the file altogether. Perhaps, a new directive (such as `/* eslint-disable-file */` is more appropriate), but a file that indicates it shouldn't be processed should be skipped altogether.

Code generators like tsoa or swagger-typescript-api emit these comments at the top of automatically generated files, so linting would also become a bit faster since fully ignored files are skipped completely.

### What actually happened?

The code crashes (related to https://github.com/typescript-eslint/typescript-eslint/issues/8261), which shows that eslint still processes an "ignored" file. Ignored in that the file itself declares to be ignored. The process doesn't crash if the file is formally ignored with .eslintignore

### Link to Minimal Reproducible Example

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=PQKgBApgzgNglgOwC4FoAmcoEMBGMJgjACwAUGhAMYxYBOBlA9glEmAB4BcYWCAngG4yZdmAA%2BYsEloBXCAKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WlqYSNkAC1pkA9gEMkyMswDm6KL2jjokcGAC%2BILUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @jeengbe, thanks for the issue!

This works as designed. `eslint-disable` directives aren't intended to ignore files, but only to suppress rule errors. A file with `/* eslint-disable */` is still parsed and parsing errors still appear. Rules are still run, and although rule errors don't appear in the "normal" output, formatters and API consumers can still find them in the [lint result](https://eslint.org/docs/latest/integrate/nodejs-api#-lintresult-type) as `suppressedMessages` if that's needed for their use case.

> Code generators like tsoa or swagger-typescript-api emit these comments at the top of automatically generated files, so linting would also become a bit faster since fully ignored files are skipped completely.

ESLint currently doesn't support comments for ignoring files, and `eslint-disable` comments aren't intended for that purpose. If you think that adding support for a new type of comments that would ignore the file would be useful, please open a feature request.
