### ISSUE TITLE
Change Request: Add "fix" severity level

### ISSUE THREAD

**Issue by brandongit2** [eslint/eslint#18030]
### ESLint version

8.56.0

### What problem do you want to solve?

This is a bump of issue #11674.

The old issue was posted in 2019 and locked for age. I'm reposting it to gauge interest now that it's 2024 and ESLint has become much more popular.

I'm aware that core rules relating to code style have been deprecated, which reduces an immediate need for a feature like this. But [ESLint Stylistic](https://eslint.style/) is a thriving project and I personally would prefer to use it over Prettier. The main thing keeping me from switching over fully is this issue. To have my editor blaring at me with formatting squigglies until I save the file is pretty distracting!

Is this something people want now? If I submit a PR (I'd be glad to), is it a feature project maintainers are willing to accommodate in the project?

### What do you think is the correct solution?

Add an additional "fix" rule severity level that does not produce errors/warnings, but is still auto-fixed when running with `--fix`.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment]
Hi @brandongit2, thanks for the issue. I think https://github.com/eslint/eslint/issues/11674#issuecomment-496630820 is still relevant here. I believe it is in the philosophy of ESLint as a tool to be as transparent as possible to the end user.

**Comment by Rec0iL99** [comment]
> To have my editor blaring at me with formatting squigglies until I save the file is pretty distracting!

I think something to address this is currently being added to `vscode-eslint` (https://github.com/microsoft/vscode-eslint/pull/1705)

**Comment by brandongit2** [comment]
Wow, that's actually a good find. It looks like that PR is a little stagnant but I'll keep an eye on it. Closing this issue for now then, thanks!
