### ISSUE TITLE
Docs: Custom rule documentation should consistently document upcoming changes

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#18069]
### Docs page(s)

https://eslint.org/docs/latest/extend/custom-rules#the-context-object

### What documentation issue do you want to solve?

The current documentation mentions some upcoming version 9 (e.g. documents that `getCwd` is deprecated and `cwd` is available) but does neither mention `context.languageOptions` or that `parserPath` and the root `parserOptions` are [removed / deprecated](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context-properties%3A-parseroptions-and-parserpath-being-removed).

### What do you think is the correct solution?

- Add docs for `languageOptions`
- Mark `parserPath` as removed
- Mark the root `parserOptions` as deprecated with a notice for accessing it via `languageOptions.parserOptions`.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I checked the [next branch](https://eslint.org/docs/next/extend/custom-rules#the-context-object) but it does not mention it either

**Comment by nzakas** [comment]
Great idea. It's difficult for us to keep track of where everything needs to be kept up to date. Please feel free to send a PR.
