### ISSUE TITLE
"generator-star" rule should support "middle" position

### ISSUE THREAD

**Issue by feross** [eslint/eslint#1808]
Should be possible to enforce a "middle" start position:

```js
function * bazooka () {

}
```

cc @xjamundx

**Comment by xjamundx** [comment]
Would this be acceptable as well?
- `function *      bazooka () {}`
- `function     *   bazooka () {}`

Would you be able to specify `["middle", 1]` with `1` being the number of spaces?

**Comment by nzakas** [comment]
`no-multi-spaces` will pick up excess spaces, so I'd say just make sure there's whitespace on either side.

**Comment by xjamundx** [comment]
I'll work on this in a bit yeah. Around 1 week.

**Comment by nzakas** [comment]
Thanks!
