### ISSUE TITLE
Bug: Types used in JSDoc blocks of @eslint/js are missing

### ISSUE THREAD

**Issue by colireg** [eslint/eslint#18100]
### Environment

Node version: v21.2.0
npm version: v10.2.3
Local ESLint version: v8.56.0 (Currently used)
Global ESLint version: Not found
Operating System: NixOS 23.11 (Tapir)

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

`packages.json`:
```json
{
  "main": "index.js",
  "type": "module",
  "scripts": {
    "lint": "npx eslint && npx tsc -p jsconfig.json"
  },
  "devDependencies": {
    "@eslint/js": "^8.56.0",
    "eslint": "^8.56.0",
    "typescript": "^5.3.3"
  }
}
```
`index.js`:
```js
import "@eslint/js";
```
`jsconfig.json`:
```json
{
  "compilerOptions": {
    "checkJs": true
  },
  "exclude": ["node_modules"]
}
```

</details>

Running `npx tsc -p jsconfig.json` complains about missing types used by `@eslint/js`

### What did you expect to happen?

No missing type errors caused by `@eslint/js`

### What actually happened?

```bash
❯ npx tsc -p jsconfig.json
node_modules/@eslint/js/src/configs/eslint-recommended.js:11:19 - error TS2307: Cannot find module '../lib/shared/types' or its corresponding type declarations.

11 /** @type {import("../lib/shared/types").ConfigData} */
                     ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@eslint/js/src/configs/eslint-recommended.js:11


```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/eslintjs-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snitin315** [comment]
The path below is indeed incorrect and needs to be updated.

https://github.com/eslint/eslint/blob/15c143f96ef164943fd3d39b5ad79d9a4a40de8f/packages/js/src/configs/eslint-recommended.js#L11

Good catch, this seems like it was missed in https://github.com/eslint/eslint/pull/16844

@colireg Would you like to send a PR?

**Comment by mdjermanovic** [comment]
Since this is a separate package, it probably shouldn't be using a relative path to a module that isn't in the package?

**Comment by colireg** [comment]
> @colireg Would you like to send a PR?

I tried to look into it for a while, but since this is a separate package, fixing this issue is far trickier than I initially thought. I'm not very experienced with npm package publishing, but I'm pretty sure simply updating the path in the comment wouldn't fix it. I tried to add `eslint` as a dependency for `@eslint/js` and import types directly from it, but it led to another type error:
```bash
../../../git/eslint/lib/shared/types.js:77:15 - error TS2304: Cannot find name 'ScopeManager'.

77  * @property {ScopeManager} [scopeManager] The scope manager of the AST.
                 ~~~~~~~~~~~~


Found 1 error in ../../../git/eslint/lib/shared/types.js:77
```
I tried to look for `ScopeManager` definition in the code base to no avail. Removing the line 77 seems to fix the issue, but I don't think that's a solution. Guess at this point I can't do anything useful except removing the JSDoc comment alltogether ;)

**Comment by snitin315** [comment]
>Since this is a separate package, it probably shouldn't be using a relative path to a module that isn't in the package?

Yes, we may need to copy this type in this package.

**Comment by fasttime** [comment]
Probably it's fine to remove the line with the type import:

https://github.com/eslint/eslint/blob/baff28ce8f167f564471f1d70d6e9c4b0cb1a508/packages/js/src/configs/eslint-recommended.js#L11

tsc can infer the type automatically:

![image](https://github.com/eslint/eslint/assets/6367844/1f29f022-7920-42a5-bd02-8ee669abdcb8)

The other config file in that directory, [src/configs/eslint-all.js](https://github.com/eslint/eslint/blob/b4e0503a56beea1222be266cc6b186d89410d1f2/packages/js/src/configs/eslint-all.js), has no type import either.

**Comment by voxpelli** [comment]
Did a deep dive into what `jsconfig.json` implies, when it was added etc here: https://github.com/voxpelli/types-in-js/discussions/25 And added a direct discouragement to use it here: https://github.com/voxpelli/types-in-js

Will follow up with PR:s to the TS/VSCode documentations to highlight what `jsconfig.json` is actually doing.

Meanwhile, suggestion:

- For ESLint: Compile JSDoc into `d.ts` and publish those, this is the preferred way and will solve this problem even for `jsconfig.json` users
- For @colireg and other `jsconfig.json` users: Use a `tsconfig.json` instead, it's much more widely understood.

**Comment by nzakas** [comment]
@voxpelli thanks for that deep analysis. :heart:

Yes, we don't type check anything in the ESLint codebase at this point. The JSDoc is primarily for documentation purposes and for VS Code Intellisense. I'm sure there are a lot of incorrect or missing types throughout the codebase, but we're definitely not going to stop and address them all. And the effort to them generate types and publish them on top of what is not a clean type-checked codebase isn't worth the incremental value here.

@snitin315 you marked this as accepted, but I'd like to suggest we close this as won't fix. Given my comment and @voxpelli's. What do you think?

**Comment by mdjermanovic** [comment]
I think it would be fine to just remove that line, as @fasttime suggested.

**Comment by snitin315** [comment]
Yes, we can just remove this line.

**Comment by nzakas** [comment]
Okay, let's just remove the line.
