### ISSUE TITLE
Include rule?

### ISSUE THREAD

**Issue by mightyiam** [eslint/eslint#1810]
Would a PR for [an include rule](https://httpd.apache.org/docs/2.4/mod/core.html#include) be welcomed, please?

**Comment by nzakas** [comment]
You haven't really explained what you're proposing, so there's no way we can answer.

**Comment by mightyiam** [comment]
If I provide a pull request that adds a rule which is an include, similar to [what Apache HTTPD has](https://httpd.apache.org/docs/2.4/mod/core.html#include), would it be welcomed? Are you open to such a feature?

The include rule/option will allow specifying additional config files, just like with Apache HTTPD's include.

**Comment by nzakas** [comment]
See: https://github.com/eslint/eslint/issues/1637

Please be sure to fully explain what you are suggesting in the future, it save us a lot of time.
