### ISSUE TITLE
Configuration: Overriding default rules

### ISSUE THREAD

**Issue by DavidHughes** [eslint/eslint#1811]
Hi,

I was wondering if there was a way to override the default rules to lower the severity from 2 to 1? I know you can override each rule individually but this will make the config file much larger than it should be.

I was unable to find anything in the docs regarding this use case.

Thanks

**Comment by michaelficarra** [comment]
You can `--reset` to disable them entirely.

**Comment by DavidHughes** [comment]
Perfect, must have missed that option, was looking in the configuration section rather than CLI.
