### ISSUE TITLE
Issue with the latest ESLint release - reduce method undefined

### ISSUE THREAD

**Issue by Gillespie59** [eslint/eslint#1813]
Hi

For my angular-eslint-plugin, I have just updated my dependencies, in order use the latest version of eslint. Now when I try to execute ESLint (via gulp-eslint) on my own project, I have this error : 

![image](https://cloud.githubusercontent.com/assets/555768/6111698/2c26f748-b08b-11e4-8671-99e3e4d415a9.png)

here is my devDependencies : 
```
"devDependencies": {
    "chai": "^1.10.0",
    "eslint": "0.14.1",
    "eslint-tester": "0.6.0",
    "gulp": "^3.8.10",
    "gulp-eslint": "0.4.1",
    "gulp-istanbul": "0.6.0",
    "gulp-mocha": "^2.0.0",
    "istanbul": "^0.3.5",
    "mocha": "2.1.0",
    "shelljs": "^0.3.0",
    "shelljs-nodecli": "^0.1.1"
  }
```

Have you already seen this error ? 

Thanks

Manu

**Comment by Gillespie59** [comment]
it looks like options.globals is an object ? Is it normal ?

**Comment by nzakas** [comment]
options.globals is an array passed from CLIEngine. This is most likely an error in the ESLint gulp plugin.
