### ISSUE TITLE
Rule Change: id-denylist

### ISSUE THREAD

**Issue by malthe** [eslint/eslint#18140]
### What rule do you want to change?

id-denylist

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
const x = "don't use this";

if (some_cond) {
    /* eslint id-denylist: ["error", "x"] */

    // This would be an error:    
    console.log(x);
}

// This would not:  
console.log(x);
```

### What does the rule currently do for this code?

The rule is not aware of its relative location in the source code.

If it appears anywhere in a specific file, the rule will apply everywhere in that file. In addition, if multiple rules are defined, the last one wins (any previous rules are silently ignored).

### What will the rule do after it's changed?

1. The rule will be block-scoped.
2. The rule will affect statements appearing _after_ the rule only (within the scope).

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

The rule can be used for a different purpose than perhaps first envisioned, namely to prevent the use of variables within some block, the use of which would be an error.

For example, an arrow function might want to use _some_ variables from the parent scope, but it would be a hard to understand bug if it were to accidentally use some other subset. There's no syntax to capture just some variables, but we can use a linting rule to the same effect.

**Comment by Tanujkanti4441** [comment]
Actually it does report the usage of restricted id expect function calls as stated in docs also
>It will not catch disallowed identifiers that are:
>    function calls (so you can still use functions you do not have control over)

so it is also not reporting the arguments inside the callExpression

**Comment by Tanujkanti4441** [comment]
@eslint/eslint-team, `id-denylist` rule leaves the function calls from being reported but is it intended to leave the arguments also in the function call?

**Comment by fasttime** [comment]
> @eslint/eslint-team, `id-denylist` rule leaves the function calls from being reported but is it intended to leave the arguments also in the function call?

I'm not sure it's intended. The rule excludes identifiers that are direct children of a `CallExpression` node:

https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/id-denylist.js#L172-L178

But if it's changed to also check call arguments, all tests will still pass.

```diff
             }
 
             return (
-                parent.type !== "CallExpression" &&
+                (parent.type !== "CallExpression" || node !== parent.callee) &&
                 parent.type !== "NewExpression" &&
                 !isRenamedImport(node) &&
                 !isPropertyNameInDestructuring(node) &&
```

**Comment by fasttime** [comment]
> ### What does the rule currently do for this code?
> 
> The rule is not aware of its relative location in the source code.
> 
> If it appears anywhere in a specific file, the rule will apply everywhere in that file.

This is not a limitation of that particular rule. `/* eslint */` configuration comments always apply to the whole file, regardless of their position in the code ([docs](https://eslint.org/docs/latest/use/configure/rules#using-configuration-comments)).

**Comment by mdjermanovic** [comment]
Yes, `/* eslint */` configuration comments always apply to the whole file, so this is not something that could work differently for a particular rule.

Also, while this rule reports references as well, its purpose is to disallow introducing new variables with restricted names, so I don't think whether it should report arguments or not is particularly important as long as it reports declarations.

**Comment by malthe** [comment]
@fasttime I see (with regards to configuration comments), but what's the logic behind them not being block-aware?

I can't imagine a situation where you'd want to place a configuration comment within a block, wanting to have that configuration apply to the entire file. That seems just objectively like a bad idea.

In that light, perhaps configuration comments _should_ apply to:

- The block where they're defined
- From that point and onwards

(That's of course out of scope here, but it would certainly make sense I think.)

@mdjermanovic it would seem that either this particular rule should report assignments only, or it should also report usage.

And with regards to functions, perhaps it should report usage for functions that are defined in that module only, allowing a function that's imported (as the docs mention, "that you have no control over").

**Comment by fasttime** [comment]
> @fasttime I see (with regards to configuration comments), but what's the logic behind them not being block-aware?
> 
> I can't imagine a situation where you'd want to place a configuration comment within a block, wanting to have that configuration apply to the entire file. That seems just objectively like a bad idea.

A problem is that it's not possible to define the severity (`"error"` or `"warn"`) or the options for a rule just for a part of a file. The configuration of each rule must be known before the syntax tree is traversed, for this reason `/* eslint */` configuration comments are evaluated in advance. I'm not informed about the rationale for this design, but ESLint doesn't allow changing rule configuration in the middle of a file, and I agree that placing an `/* eslint */` configuration comment inside a conditional block seems like a bad idea.

> In that light, perhaps configuration comments _should_ apply to:
> 
>     * The block where they're defined
> 
>     * From that point and onwards

Some configuration comments do apply from their location onward. For example `/* eslint-enable */` and `/* eslint-disable */` comments ([docs](https://eslint.org/docs/latest/use/configure/rules#using-configuration-comments-1)) can be used to enable or disable reporting for parts of a file:

```js
/*eslint no-console: "warn" */

/* eslint-disable no-console */

console.log("this will not warn");

/* eslint-enable no-console */

console.log("this will warn");
```
