### ISSUE TITLE
Repo: remove internal multiline-comment-style fork/wrapper

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18169]
Following https://github.com/eslint/eslint/pull/18005/files#r1493021982 -> #18122: the ESLint repo internally uses a [`tools/internal-rules/multiline-comment-style.js`](https://github.com/eslint/eslint/blob/9a4ae3b68a1afd9483d331997635727fb19a1a99/tools/internal-rules/multiline-comment-style.js). It's an [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer)-powered custom wrapper around the built-in [`multiline-comment-style`](https://eslint.org/docs/latest/rules/multiline-comment-style) rule. 

https://github.com/eslint/eslint/blob/9a4ae3b68a1afd9483d331997635727fb19a1a99/tools/internal-rules/multiline-comment-style.js#L2

The composed rule is meant to allow `//-` style comment blocks like the following:

```js
//--------
// Example
//--------
```

The `multiline-comment-style` rule doesn't allow those styles of comments. And per #18122 there's no plan to add in an option, since stylistic rules are feature-frozen (https://eslint.org/blog/2020/05/changes-to-rules-policies).

Personally, I don't find value in the `//-` comment blocks and find them to get in my way when writing files. I find that their contents are easily inferable from the code around them, so to me take up space for essentially nothing added. ESLint is the only project I work on that uses them. Proposal: can we get rid of these comments _and_ the composed rule?

**Comment by nzakas** [comment]
No. This is the project's coding style.
