### ISSUE TITLE
Also check for backslash in path for Windows compatibility

### ISSUE THREAD

**Issue by jscissr** [eslint/eslint#1818]
When using a tool like [standard](https://github.com/feross/standard) on Windows 7, the following error occurs:
`Could not find formatter 'C:\Users\Jan\AppData\Roaming\npm\node_modules\standard\lib\eslint-reporter.js'.`
This is because standard passes a path with backslashes to eslint, as the formatter param; and eslint only looks for forward slashes.

I'm working on a pull request.

**Comment by nzakas** [comment]
What is standard doing that is causing this error? It's not clear from your description.

**Comment by jscissr** [comment]
Something like this:
`eslint --config C:\Users\Jan\AppData\Roaming\npm\node_modules\standard\rc\.eslintrc --format C:\Users\Jan\AppData\Roaming\npm\node_modules\standard\lib\eslint-reporter.js test.js`

**Comment by jscissr** [comment]
btw, new pull request at #1820

**Comment by jscissr** [comment]
Now I made and squashed a new commit.

**Comment by feross** [comment]
Any chance you could do a release so `standard` can pick up this change?

**Comment by nzakas** [comment]
We are doing releases every 1-2 weeks as things come together. We only do one-off releases to fix critical bugs. Next release will likely be this weekend.

**Comment by feross** [comment]
Thanks for explaining.
