### ISSUE TITLE
Docs: Option to use system preference for light/dark theme

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18190]
### Docs page(s)

_all of them_

### What documentation issue do you want to solve?

The ESLint docs currently default to the browser's [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) setting for light/dark mode by default. And they have a Light/Dark selector to let the user specify an override.

But, there's no way to remove the override: i.e. go back to the default behavior of using the browser/system preference. This feels like a bug / missing feature to me: what if the user wants go back to the system preference?

I've hit this where I've needed to change the page temporarily, but subsequently wanted to go back to synced with the browser/system preferences.

### What do you think is the correct solution?

A few UI options come to mind, in order of what I think is most intuitive & usable first:

* Adding a third button like _System_ to the existing Light/Dark selector
* Adding a _dismiss_/_x_ button to clear the current state
* Have pressing the button again dismiss the current state

The current selector, for reference: ![Screenshot of the ESLint docs Light/Dark buttons, with light mode selected](https://github.com/eslint/eslint/assets/3335181/8cb3b56f-39c0-497b-a5ae-d9e53f1ed4dc)

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Sibling issue to #18189.

**Comment by kecrily** [comment]
I like the third button. It does seem more common too.

**Comment by Rec0iL99** [comment]
ping @eslint/eslint-team

**Comment by Tanujkanti4441** [comment]
i think we can just click on the `light/dark` button to match it with the system preference.

**Comment by nzakas** [comment]
I'd like to see some examples of how other sites are doing this before coming to a conclusion here. @JoshuaKGoldberg can you compile a few sites that have implemented something along the lines of what you're describing so we can evaluate?

**Comment by JoshuaKGoldberg** [comment]
A few popular sites that have options on all pages, rather than in profile settings...

<table>
<thead>
<tr>
<th>Site</th>
<th>Style</th>
<th>Visual</th>
</thead>
<tbody>
<tr>
<th>
<a href="https://docs.astro.build">Astro</a>
</th>
<td>Dropdown</td>
<td>
<img alt="Screenshot of Astro's Auto button with a computer glyph." src="https://github.com/eslint/eslint/assets/3335181/8be18526-2c59-4a90-8b56-ea80db0ac688" />
<img alt="Screenshot of Astro's unstyled browser select: Dark, Light, Auto" src="https://github.com/eslint/eslint/assets/3335181/b9ed6698-60e0-4476-9ff9-961139a7c041" />
</td>
</tr>
<tr>
<th>
<a href="https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API">MDN</a>
</th>
<td>Dropdown</td>
<td>
<img alt="Screenshot of MDN's Theme dropdown. Options: (half circle) OS Default, (sun glyph) Light, (crescent moon glyph) Dark" src="https://github.com/eslint/eslint/assets/3335181/0f0485f4-8c86-434f-968f-d2dad42b4486" />
</td>
</tr>
<tr>
<th>
<a href="https://docs.netlify.com">Netlify</a>
</th>
<td>Dropdown</td>
<td>
<img alt="Screenshot of Netlify's System button with a half-filled circle glyph." src="https://github.com/eslint/eslint/assets/3335181/76665a97-191c-45fe-9b28-ab753ba4a18f" />
<img alt="Screenshot of Netlify's unstyled browser select: System, Light, Dark" src="https://github.com/eslint/eslint/assets/3335181/75e87dc0-7d66-4c24-8a4a-4809637614de" />
</td>
</tr>
<tr>
<th>
<a href="https://nextjs.org/docs">Next.js</a>
</th>
<td>Buttons</td>
<td>
<img alt="Screenshot of Next.js's moon, sun, and computer buttons." src="https://github.com/eslint/eslint/assets/3335181/2f4e796a-462d-4ded-8581-a27dd3c29cc7" />
</td>
</tr>
<tr>
<th>
<a href="https://docs.solidjs.com/">Solid (Beta)</a>
</th>
<td>Dropdown</td>
<td>
<img alt="Screenshot of Solid's (sun glyph) Light, (crescent moon glyph) Dark, and (computer glyph) System buttons in a dropdown below a sun glyph button." src="https://github.com/eslint/eslint/assets/3335181/24d4be51-a941-4b6a-b7fb-b52dcf07a551" />
</td>
</tr>
<tr>
<th>
<a href="https://typescriptlang.org/docs">TypeScript</a>
</th>
<td>Dropdown</td>
<td>
<img alt="Screenshot of TypeScript's 'Site Colours:' label and 'System' dropdown button." src="https://github.com/eslint/eslint/assets/3335181/5f38cb52-d2a2-4590-81fb-c44dc4550d5f" />
<img alt="Screenshot of TypeScript's unstyled browser select: System, Always Light, Always Dark" src="https://github.com/eslint/eslint/assets/3335181/a1d3231a-f9a2-4749-ba73-7843b108da99" />
</td>
</tr>
<tr>
<th>
<a href="https://vercel.com/docs">Vercel</a>
</th>
<td>Buttons</td>
<td>
<img alt="Screenshot of Vercel's moon, sun, and computer buttons under a 'Preferences' label." src="https://github.com/eslint/eslint/assets/3335181/e5245e2c-0ead-4057-9bc3-d0ae847861cb" />
</td>
</tr>
</tbody>
</table>

**Comment by nzakas** [comment]
Nice, thanks! Given those, I think adding a third button with a monitor that says "System" probably makes the most sense for us. 

I'm also not opposed to making the "Light", "Dark", and "System" as `aria-label`s that are visually hidden to save space.

**Comment by harish-sethuraman** [comment]
One thing I can notice in all of these sites are. These options are dropdown since we have three values and they aren't button group as we have them in the site. Having so many buttons really feels quite off tbh (for mobile specifically). Shall we go about implementing it as a dropdown rather than having it as button group? 

This is how it looks on the side of blogs page when 
<img width="334" alt="Screenshot 2024-06-21 at 10 45 29 AM" src="https://github.com/eslint/eslint/assets/32865581/ed7c9eec-41b8-4a96-87a5-8b3b85d7d8a1">

**Comment by nzakas** [comment]
I prefer the buttons, personally.
