### ISSUE TITLE
Bug: Flat config doesn't work when `files` refers to a sibling directory.

### ISSUE THREAD

**Issue by danfuzz** [eslint/eslint#18197]
### Environment

Node version: 21.4.0
npm version: 10.2.4
Local ESLint version: N/A
Global ESLint version: 8.57.0
Operating System: macOS

### What parser are you using?

Default (Espree)

### What did you do?

I set up a small project to demonstrate a problem where ESLint does not seem to understand when a flat config file refers to files in a sibling directory to where the config file is: [config-problem.tgz](https://github.com/eslint/eslint/files/14577103/config-problem.tgz)

If you untar this, you'll find this file structure:

```
config-problem/
  lint-setup/
    eslint.config.mjs
  src/
    a-module/
      oh-no.js
      package.json
```

This is meant to be a minimal example of where one wants all linter stuff — including eventually a `node_modules` directory with ESLint plugins (which is specifically what is motivating this example) — to be entirely separate from the `src` directory being operated on.

For ease of reference, this is what's in the config file:

```js
export default [
  {
    files: ['../src/**/*.js'],
    rules: {
      'semi': 'error'
    }
  }
];
```

### What did you expect to happen?

```
$ cd config-problem
$ npx eslint --config=lint-setup/eslint.config.mjs src
[... finds problems in `src` ...]
$ cd lint-setup
$ npx eslint ../src
[... finds problems in `../src` ...]
$
```

### What actually happened?

In the first case, it seems to think the config file is YAML:

```
$ cd config-problem
$ npx eslint --config=lint-setup/eslint.config.mjs src

Oops! Something went wrong! :(

ESLint: 8.57.0

YAMLException: Cannot read config file: /Users/danfuzz/tmp/config-problem/lint-setup/eslint.config.mjs
Error: end of the stream or a document separator is expected (3:10)
[... more error text ...]
$
```

In the second case, it thinks that all files in `src` are ignored:

```
$ cd config-problem/lint-setup
$ npx eslint ../src

Oops! Something went wrong! :(

ESLint: 8.57.0

You are linting "../src", but all of the files matching the glob pattern "../src" are ignored.

If you don't want to lint these files, remove the pattern "../src" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.

$
```

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint/files/14577103/config-problem.tgz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @danfuzz, thanks for the issue!

This works as intended.

1. In ESLint v8.x, eslintrc config mode is default mode. If you don't have a flat config file in the current working directory or its parent directories, you'll need to set environment variable `ESLINT_USE_FLAT_CONFIG=true`. Otherwise, a file passed as `--config` would be treated as an eslintrc config file. In ESLint v9.x, flat config mode will be default so there will be no need for the environment variable.
2.  Files outside of the config base path, which is the directory where the config file is, or the current working directory in case you're using the `--config` option, are considered ignored. File paths in the config file are considered to be relative to the config base path.

In your example, you can update the pattern from `../src/**/*.js` to `src/**/*.js`:

```js

// lint-setup/eslint.config.mjs
export default [
  {
    files: ['src/**/*.js'],
    rules: {
      'semi': 'error'
    }
  }
];
```

and run ESLint this way:

```sh
$ cd config-problem
$ ESLINT_USE_FLAT_CONFIG=true npx eslint --config=lint-setup/eslint.config.mjs src
```

**Comment by danfuzz** [comment]
@mdjermanovic What is the new recommended way to keep ESLint files in a separate directory from source?

Would you all consider honoring a `files` which explicitly uses `../` instead of complaining that it's de facto ignored? Or (equivalently I guess?) would you all consider having a way to drop the "secret" rule that defines anything outside of the tree rooted at the config file to be ignored?
