### ISSUE TITLE
Change Request: Lazy import and initialize Linter

### ISSUE THREAD

**Issue by dmichon-msft** [eslint/eslint#18202]
### ESLint version

9.0.0-beta.2

### What problem do you want to solve?

When there is a misconfiguration in the eslint config, or the eslint cache is fully up-to-date, the `Linter` class is imported and instantiated but never actually used. We can save CPU cycles in these scenarios at no extra cost in the typical case by deferring the import until first use.

### What do you think is the correct solution?

I'd like to change the `linter` field on the `privateMembers` entry for the ESLint object to be a getter, which lazily imports and instantiates the `Linter` object. Subsequently, the getter only needs to be invoked immediately prior to invocation of the `verifyText` function, since it is the only logic that actually uses the `linter` field value.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. In this case, we're happy with how the code currently works. While this may save some cycles in the odd case where the config file has an error or a full cache with no changes, those are edge cases and the added complexity to lazily load `Linter` isn't worth it.
