### ISSUE TITLE
Rule Change: User-defined replacements as autofix for no-restricted-syntax

### ISSUE THREAD

**Issue by smartinio** [eslint/eslint#18210]
### What rule do you want to change?

no-restricted-syntax

### What change do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
// let's say double bangs is banned in a repo with a message to use Boolean() instead
const isFoo = !!foo;

// users should be able to specify a replacement pattern to autofix it to:
const isFoo = Boolean(foo);
```

### What does the rule currently do for this code?

It can error but not autofix.

### What will the rule do after it's changed?

It will try to autofix if the user specified a valid replacement.

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

I've already implemented this. PR up soon.

**Comment by mdjermanovic** [comment]
This is an interesting idea, but since it's fairly easy to write a custom rule, and the new config system allows defining custom rules directly in configuration files, I'm not in favor of adding more features to the `no-restricted-syntax` rule as it's only provided as a convenience for simple cases.

For example, this a configuration with a custom rule that autofixes `!!foo` to `Boolean(foo)`:

```js
// eslint.config.js
export default [{
    plugins: {
        custom: {
            rules: {
                "no-double-bangs": {
                    meta: {
                        fixable: "code"
                    },
                    create(context) {
                        return {
                            "UnaryExpression[operator='!'][argument.operator='!']"(node) {
                                context.report({
                                    node,
                                    message: "Double bangs are not allowed. Use Boolean.",
                                    fix: fixer => fixer.replaceText(node, `Boolean(${context.sourceCode.getText(node.argument.argument)})`)
                                });
                            }
                        }
                    }
                }
            }
        }
    },
    rules: {
        "custom/no-double-bangs": "error"
    }
}];
```

I also think that regular expressions are not a good way to parse and modify JavaScript code.

@eslint/eslint-team thoughts about this?

**Comment by smartinio** [comment]
@mdjermanovic Makes sense. Didn't realize it's that easy to do custom rules nowadays. Can close this.

**Comment by smartinio** [comment]
Although we're not able to migrate to the new config right now though, as several of the plugins we use aren't compatible with the new interface it seems, I still think @mdjermanovic example is more robust than my regex implementation. Closing this and my PR in favor of the new config.
