### ISSUE TITLE
Scope and variable re-declaration problem

### ISSUE THREAD

**Issue by uxer** [eslint/eslint#1821]
When I say:

    for (var x in y) {
        var z = something;
        
        // ...
    }

    var z = somethingElse;

... ESLint says, that `z` is already defined. If I then do this:

    for (var x in y) {
        var z = something;
        
        // ...
    }

    z = somethingElse;

... it says, that `z` is defined out of scope. So essentially, I have to do this:

    var z;

    for (var x in y) {
        z = something;
        
        // ...
    }

    z = somethingElse;

Is this right?

**Comment by nzakas** [comment]
Correct.

**Comment by uxer** [comment]
This JSFiddle somehow disagrees: http://jsfiddle.net/7vxm7xta/1/.

Can you please explain how this makes sense? Because there is no such thing as a `for` loop scope in JavaScript. All variables are hoisted to the top of the scope. So saying `var` inside a `for` loop is the same as saying it outside.

**Comment by nzakas** [comment]
JSFiddle isn't doing static analysis for your code, ESLint is. 

In the first code snippet, you're redeclaring `z`, so you get a `no-redeclare` warning.

In the second code snippet, you're declaring `z` inside the loop and using it outside, so you're triggering `block-scoped-var`.

I'd suggest reading up on the rules and what they look for: http://eslint.org/docs/rules/

If you have further questions, please use the mailing list eslint@googlegroups.com.
