### ISSUE TITLE
Breaking: Eslint fails using Nodejs@0.12.0

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#1823]
If I run the same config using **NodeJs@0.10.36** it works fine but if I run it using **NodeJs@0.12.0** it fails with this error message.

I think this is because I have some custom-rules which I use, but it works in 0.10.36

```.sh
C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:62
            base[key] = custom[key];
                      ^
TypeError: Cannot assign to read only property 'before' of 2
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:62:23
    at Array.forEach (native)
    at mergeConfigs (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:35:25)
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:60:25
    at Array.forEach (native)
    at mergeConfigs (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:35:25)
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:60:25
    at Array.forEach (native)
    at Object.mergeConfigs (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util.js:35:25)
    at Config.getConfig (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\config.js:292:23)
```

here is the config file:

```.json
		"deprecated-functions": 1,
		"camelcase": 0,
		"mp-camelcase": 1,
		"no-comma-dangle": 2,
		"no-cond-assign": 2,
		"no-console": 1,
		"no-constant-condition": 1,
		"no-debugger": 2,
		"no-dupe-keys": 1,
		"no-empty": 1,
		"no-ex-assign": 2,
		"no-extra-boolean-cast": 1,
		"no-extra-parens": 1,
		"no-extra-semi": 1,
		"no-inner-declarations": 1,
		"no-reserved-keys": 2,
		"no-unreachable": 1,
		"use-isnan": 2,
		"valid-jsdoc": 2,
		"valid-typeof": 2,
		"complexity": [1, 4],
		"curly": [2, "all"],
		"dot-notation": 1,
		"eqeqeq": 2,
		"guard-for-in": 2,
		"no-alert": 2,
		"no-eval": 2,
		"no-extend-native": 2,
		"no-floating-decimal": 1,
		"no-implied-eval": 2,
		"no-lone-blocks": 1,
		"no-loop-func": 2,
		"no-multi-spaces": 1,
		"no-multi-str": 1,
		"no-native-reassign": 2,
		"no-return-assign": 1,
		"no-script-url": 2,
		"no-self-compare": 1,
		"no-sequences": 2,
		"no-unused-expressions": 1,
		"no-warning-comments": 1,
		"radix": 2,
		"no-shadow": 1,
		"no-undef": 2,
		"no-undef-init": 1,
		"no-unused-vars": 1,
		"no-use-before-define": 1,
		"comma-spacing": {"before":false, "after":true},
		"eol-last": 0,
		"new-cap": 1,
		"no-array-constructor": 2,
		"no-lonely-if": 2,
		"no-mixed-spaces-and-tabs": 1,
		"no-nested-ternary": 2,
		"no-new-object": 2,
		"no-space-before-semi": 1,
		"no-spaced-func": 1,
		"no-trailing-spaces": 1,
		"quotes": [1, "double", "avoid-escape"],
		"semi": [2, "always"],
		"space-infix-ops": 1,
		"space-return-throw-case": 1,
		"space-unary-ops": 1,
		"strict": 0
```

Now if I remove everything from my setup file as in all the rules then I get this error:

```.sh
C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\eslint.js:599
                        throw ex;
                              ^
TypeError: Error while loading rule 'new-cap': Cannot assign to read only property 'newIsCap' of newIsCap
    at module.exports (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\rules\new-cap.js:54:59)
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\eslint.js:585:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\eslint.js:576:16)
    at processFile (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\cli-engine.js:172:27)
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\cli-engine.js:278:26
    at walk (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util\traverse.js:81:9)
    at C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)
    at traverse (C:\Users\GS025879\Documents\webstrom\launcher\node_modules\eslint\lib\util\traverse.js:101:11)
```

FYI: All of the scenarios works perfectly on **NodeJS 0.10.36**

**Comment by nzakas** [comment]
We have our tests running on Node 0.12 automatically and haven't seen any issues. So either it's the custom code you have or there's a bug in Node 0.12 that only your code is hitting. Either way, you will need to do some more investigating.

**Comment by gyandeeps** [comment]
That could be case with scenario 1 (which I highly doubt) but in scenario 2, I dont use any custom rules but it still fails.

Now all of the above scenarios just work fine in **NodeJs@0.10.36**

**Comment by gyandeeps** [comment]
After a lot of research I have found something:

I had the `new-cap` defined with a wrong syntax inside my file. I had `new-cap:[1, "newIsCap"]`.
So since the `RuleContext` object decalres all the properties as read-only, I think **NodeJs@0.12.0" is very strict about it if you play with it but **NodeJs@0.10.36** did not had any problems and it would skip through it.

The correct way for the rule is `new-cap:[1, {"newIsCap": true}]`.

Something similar was happening for scenario one also.

Sorry for trouble @nzakas  but I am curious as to what has changed from node versions on the part of how `Object.defineProperties` works.

**Comment by nzakas** [comment]
I don't know, I'd suggest filing an issue with Node.js itself to discuss.

**Comment by amatiasq** [comment]
Same issue here, it worked when I removed `eslintConfig` from package.json

**Comment by gyandeeps** [comment]
can you paste the output here. what version of eslint and the parser you are using? and config file too

**Comment by amatiasq** [comment]
Output

    amatiasq:~/frontend (master)$ eslint common/app-bootstrap.js
    /usr/local/lib/node_modules/eslint/lib/util.js:50
                base[key] = mergeConfigs(base[key] || {}, custom[key]);
                          ^
    TypeError: Cannot assign to read only property 'env' of .eslintrc
        at /usr/local/lib/node_modules/eslint/lib/util.js:50:23
        at Array.forEach (native)
        at Object.mergeConfigs (/usr/local/lib/node_modules/eslint/lib/util.js:25:25)
        at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:163:23)
        at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:293:22)
        at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:178:27)
        at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:299:26
        at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
        at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9
        at Array.forEach (native)

Config file:

    env:
      browser: true

    globals:
      define: true

    rules:
      indent: 2
      brace-style: [2, "1tbs"]
      camelcase: 1
      comma-style: [2, "last"]
      comma-dangle: "always-multiline"
      curly: [1, "multi"]
      default-case: 2
      func-style: [2, "declaration"]
      guard-for-in: 2
      indent: [2, 2]
      no-console: 0
      no-floating-decimal: 2
      no-nested-ternary: 2
      no-undefined: 2
      no-use-before-define: [2, "nofunc"]
      quotes: [2, "single", "avoid-escape"]
      radix: 2
      space-after-function-name: [2, "never"]
      space-after-keywords: [2, "always"]
      space-before-blocks: 2
      spaced-line-comment: [2, "always", { exceptions: ["-"]}]
      strict: [2, "function"]
      valid-jsdoc: [2, { prefer: { "return": "returns"}}]
      wrap-iife: 2

Version:

    amatiasq:~/frontend (master)$ eslint --version
    v0.20.0

I don't know what you mean with "the parser", YAML?

**Comment by nzakas** [comment]
@amatiasq can you please file a new issue, as this is not the same as the originally reported issue here.
