### ISSUE TITLE
Change Request: (Consider moving .eslintcache to node_modules/.cache)

### ISSUE THREAD

**Issue by recallwei** [eslint/eslint#18245]
### ESLint version

v8.0.0

### What problem do you want to solve?

Now, I should add .eslintcache to .gitignore manually.
Also, this file should not be in the project root dir.

### What do you think is the correct solution?

Like Prettier, Store in node_modules/.cache seems a great solution.

![image](https://github.com/streetsidesoftware/cspell/assets/62941121/fdb4024a-1472-4a07-a501-272fad7e5261)

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
I'm 👍 to this. However, we cannot accept it in v9(it's in rc). I think we can change it in v10.

Would like to hear from other team members.

**Comment by nzakas** [comment]
I don't think there's a good reason to change the location of the cache file. Some users actually do check in `.eslintcache` to their repository for CI purposes, so I don't think it's safe to either assume that most people don't want that or to put it into a location that is always gitignored by default.

**Comment by JoshuaKGoldberg** [comment]
> Some users actually do check in `.eslintcache` to their repository for CI purposes

🤔 is that... advisable? My impression was that the slice of users who'd want to do such a thing is pretty small. This is all anecdotal and I'd want to know if I'm wrong anywhere:

* Most repositories that include artifacts don't check them in, based on the reasoning that they can clutter changes (e.g. `tsconfig.tsbuildinfo`)
* Most repositories that have performance issues get it from cross-file linting such as `eslint-plugin-import` or typescript-eslint type-checked rules. Given that caching doesn't work well with cross-file lint rules (e.g. https://github.com/typescript-eslint/typescript-eslint/issues/4694), that swathe of repositories likely shouldn't be using it at all
    * This, in particular, I would like to be corrected on if I'm wrong 🙂 

I believe the ecosystem norm is to put artifacts in `node_modules/.cache` or some similar location. If that's right, then my instinct would be that the _default_ for caching should be the ecosystem norm, with an opt-in option to move to a new location like `.eslint-cache`.

**Comment by nzakas** [comment]
> 🤔 is that... advisable?

Folks do this to speed up their CI. There's even an RFC aimed at making this easier:
https://github.com/eslint/rfcs/pull/114

**Comment by recallwei** [comment]
Most of the projects do not use cache and CI. Is it possible to add some custom config to specify the location of the cache file?

**Comment by nzakas** [comment]
@recallwei I don't think you can make any assertion about what most projects do, and even if you could, that doesn't mean we don't consider those use cases.

There is already a `--cache-location` flag that you can use to place the cache file into `node_modules` if you want.

**Comment by fasttime** [comment]
So, if the directory where `eslint` runs does not contain a `package.json` file or a `node_modules` directory, what should happen?

**Comment by nzakas** [comment]
Closing as we're not going to move forward with this. Aside from the reasons already mentioned, other runtimes may not use `node_modules` directories, so we'd still need a different location.
