### ISSUE TITLE
Change Request: `--inspect-config` CLI option

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#18255]
### ESLint version

HEAD

### What problem do you want to solve?

The new [config inspector](https://github.com/eslint/config-inspector) is currently launched via `npx @eslint/config-inspector`, but people likely won't realize it exists if they've just downloaded the CLI.

### What do you think is the correct solution?

Add an `--inspect-config` command line option that launches the config inspector in the same way `--init` launches the config initializer. That way, the command will show up in the help screen and users are more likely to find it.

This would just be for flat config.

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
**TSC Summary:** This issue seeks to add a `--inspect-config` CLI option that will launch the config inspector (similar to `--init` does with `@eslint/create-config`).

**TSC Question:** Shall we accept this proposal?

**Comment by sam3k** [comment]
Per 2024-04-04 TSC meeting, we have agreed to accept this proposal.
