### ISSUE TITLE
Change Request: explicitly handle `undefined` being passed as a config value

### ISSUE THREAD

**Issue by G-Rath** [eslint/eslint#18259]
### ESLint version

next

### What problem do you want to solve?

Currently flat config does not have any special handling for `undefined` being passed in causing an "accessed property on undefined" error:

```
Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading 'ignores')
    at FlatConfigArray.get ignores [as ignores] ([redacted]/node_modules/@humanwhocodes/config-array/api.js:648:15)
    at FlatConfigArray.isDirectoryIgnored ([redacted]/node_modules/@humanwhocodes/config-array/api.js:1012:10)
    at FlatConfigArray.getConfig ([redacted]/node_modules/@humanwhocodes/config-array/api.js:806:12)
    at FlatConfigArray.isFileIgnored ([redacted]/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at [redacted]/node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
    at entryFilter ([redacted]/node_modules/eslint/lib/eslint/eslint-helpers.js:299:28)
    at Object.isAppliedFilter ([redacted]/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
    at AsyncReader._handleEntry ([redacted]/node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
    at [redacted]/node_modules/@nodelib/fs.walk/out/readers/async.js:65:22
```

This is confusing because `undefined` is commonly expected if you try to use a config that doesn't exist but the error message looks more like a potential bug in ESLint:

```js
const jestPlugin = require('eslint-plugin-jest');

module.exports = [
  {
    // enable jest rules on test files
    files: ['test/**'],
    ...jestPlugin.configs['flat/recommended'],
  },
  // explodes, as we're removing this in our next major!
  jestPlugin.configs['flat/snapshots'],
];
```

This is a real-world example of where I hit this as I was testing for `eslint-plugin-jest`'s upcoming major in which we're removing the `flat/snapshots` config.

### What do you think is the correct solution?

I'd like ESLint to explicitly check for `undefined` and raise an error along the lines of "you've passed `undefined` as a config - this usually happens when you're trying to reference a config that doesn't exist"

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Born from https://github.com/eslint/eslint/issues/18094 & https://github.com/eslint/eslint/issues/18094#issuecomment-2029300794

**Comment by mdjermanovic** [comment]
It makes sense to me to improve error reporting in this case, as referencing a config name that doesn't exist in a plugin might be a common mistake.

@eslint/eslint-team thoughts?

**Comment by nzakas** [comment]
@G-Rath can you please update your description with a specific example that results in the error?

**Comment by G-Rath** [comment]
@nzakas done (I was in the middle of doing that when you posted 😅)

**Comment by nzakas** [comment]
Thanks. 

Yeah, I agree we should have a nicer error message in this case.
