### ISSUE TITLE
Docs: no-restricted-imports doesn't explain paths vs. patterns

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18253]
### Docs page(s)

https://eslint.org/docs/latest/rules/no-restricted-imports

### What documentation issue do you want to solve?

The docs page for `no-restricted-imports` mentions the `paths` and `patterns` objects, but never explicitly says what the difference is or why you'd want to use them. I found this to be confusing. Without poring over the rule's source I don't think it's inferable what the differences between the two are.

### What do you think is the correct solution?

Could we clearly explain somewhere under _Rule Details_ or _Options_...

* The difference between `paths` and `patterns`
* What the explicit format is for the objects in their arrays

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This issue inspired by talking over the rule with @matthewp. [[Discord link](https://discord.com/channels/830184174198718474/845430950191038464/1222267521936261292)]

**Comment by nzakas** [comment]
I'd say go for it. 

FWIW, you don't need to open issues to suggest docs changes, you can go ahead and submit a PR with the proposed changes to save some time.

**Comment by JoshuaKGoldberg** [comment]
I'm not likely to be able to send this one soon. If anybody else wants to that'd be great too. 😁
