### ISSUE TITLE
error eslint@9.0.0: "node" 20.8.0 is incompatible with this module

### ISSUE THREAD

**Issue by cope** [eslint/eslint#18288]
### Environment

Node version: 20.8.0
npm version: 10.1.0
Local ESLint version: 8.57.0
Global ESLint version: -
Operating System: Windows 10

### What parser are you using?

Default (Espree)

### What did you do?

yarn latest

error eslint@9.0.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || ^20.9.0 || >=21.1.0". Got "20.8.0"

### What did you expect to happen?

I expected eslint to upgrade to v9

### What actually happened?

error eslint@9.0.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || ^20.9.0 || >=21.1.0". Got "20.8.0"

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Pewtro** [comment]
That is working as intended. v9 requires 20.9 or newer for node v20.x, as per https://github.com/eslint/eslint/issues/17595 and https://github.com/eslint/eslint/pull/17725. Note that latest LTS version of node is 20.12.1.
