### ISSUE TITLE
Bug: `package.json` `eslintConfig` no longer functions

### ISSUE THREAD

**Issue by ryanblock** [eslint/eslint#18296]
### Environment

Node version: v20.10.0
npm version: 10.2.3
Local ESLint version: 9.0.0
Global ESLint version: n/a
Operating System: macOS 14.4.1 (23E224)

### What parser are you using?

Default (Espree)

### What did you do?

I read the [v9 migration doc](https://eslint.org/docs/latest/use/migrate-to-9.0.0) and [flat config rollout plans](https://eslint.org/blog/2023/10/flat-config-rollout-plans/); nothing mentioned keeping eslint config in the `package.json` `eslintConfig` property.

When upgrading to v9 with `package.json` `eslintConfig` populated in a project, the following error is thrown:

```
Oops! Something went wrong! :(

ESLint: 9.0.0

Error: Could not find config file.
    at locateConfigFileToUse (/Users/ryan/git/architect/architect/node_modules/eslint/lib/eslint/eslint.js:349:21)
    at async calculateConfigArray (/Users/ryan/git/architect/architect/node_modules/eslint/lib/eslint/eslint.js:384:49)
    at async ESLint.lintFiles (/Users/ryan/git/architect/architect/node_modules/eslint/lib/eslint/eslint.js:814:25)
    at async Object.execute (/Users/ryan/git/architect/architect/node_modules/eslint/lib/cli.js:461:23)
    at async main (/Users/ryan/git/architect/architect/node_modules/eslint/bin/eslint.js:165:22)
```

This is, as far as I can tell, an unexpected and undocumented breaking change. We have dozens of repos that rely on `eslintConfig.extends` to point to our shared eslint configuration.

### What did you expect to happen?

Based on the [v9 migration doc](https://eslint.org/docs/latest/use/migrate-to-9.0.0), [flat config rollout plans](https://eslint.org/blog/2023/10/flat-config-rollout-plans/), [announcement post](https://eslint.org/blog/2024/04/eslint-v9.0.0-released), and other documentation, we expected package.json-based configuration to continue working as it had until v9, as no indication was provided that that configuration venue would entirely cease to work.

### What actually happened?

See above for error.

### Link to Minimal Reproducible Example

https://github.com/ryanblock/eslint-v9-package.json-config

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

Nothing, except general appreciation for the immense amount of hard work that goes into this project! 💕

**Comment by Rec0iL99** [comment]
Hi @ryanblock, thanks for the issue. The `.eslintrc` config system is now deprecated and the flat config system is the new default config system in ESLint from `v9.0.0`. The `eslintConfig` field in `package.json` is no longer supported in the flat config system. 

If you want to continue using `eslintConfig` (`.eslintrc` config system) in `package.json`, then you must set the environment variable `ESLINT_USE_FLAT_CONFIG` to `false`.

The decision to remove support for `eslintConfig` field was mentioned in this [blog](https://eslint.org/blog/2022/08/new-config-system-part-2/#the-new-config-file%3A-eslint.config.js) post

**Comment by Rec0iL99** [comment]
Sure, 

ping @eslint/eslint-team

**Comment by aladdin-add** [comment]
It's more of a documentation improvement. PRs are welcome! 👍

**Comment by nzakas** [comment]
Yeah, we did apparently skip over mentioning `package.json`. We should definitely add that to the migration guide.

**Comment by nzakas** [comment]
Working on this.
