### ISSUE TITLE
Change Request: Support `.config` directory

### ISSUE THREAD

**Issue by Splines** [eslint/eslint#18294]
### ESLint version

v9.0.0-alpha.0

### What problem do you want to solve?

Currently the configuration files for ESLint have to be placed in the root of the project (as described in the docs [here](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file)).

Due to a lack of standards for where tools store their configuration, the number of top-level configuration files in projects is increasing day by day. See [.config dir proposal](https://github.com/pi0/config-dir) for more context.

### What do you think is the correct solution?

I propose supporting `.config/eslint.js`, `.config/eslint.mjs` and `.config/eslint.cjs` as alternative places to check and load the configuration if the top-level `eslint.config.js/mjs/cjs`does not exist to unblock adopting this new convention across the ecosystem.

While it can take a while to onboard more tools with this new convention, it will be an egg-and-chicken problem to adopt a new convention like this unless more mainstream tools onboard to support it.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

See what tools already support this convention [here](https://github.com/pi0/config-dir/discussions/6).

**Comment by Rec0iL99** [comment]
Hi @Splines, you can put your config file in the `.config/` dir instead of the root, and explicitly provide the path of the config file using the `--config` CLI option.

`npx eslint --config .config/eslint.config.mjs .`

**Comment by Splines** [comment]
Thanks, I forgot about this CLI option which is exactly what I needed. It'd still be awesome to have the `.config/` dir in the default detection path of ESLint ;)

For users of the VSCode ESLint plugin that see this: you might want to put this in your `.vscode/settings.json` for your workspace:
```json
"eslint.options": {
    "overrideConfigFile": ".config/eslint.mjs"
}
```

See the docs for the [`overrideConfigFile` param](https://eslint.org/docs/latest/integrate/nodejs-api#parameters).
