### ISSUE TITLE
Please consider bringing back `Linter#getRules()` or providing an alternative method.

### ISSUE THREAD

**Issue by virtuallyunknown** [eslint/eslint#18322]
### ESLint version

v9.0.0

### What problem do you want to solve?

Greetings!

A few months ago I have created a project which helps me combine and configure rules from different eslint related libraries such as [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn), [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) and others, along with the rules which come from eslint itself.

Basically I import all rules that come from these libraries, and have built a UI on top of it which lets me configure each one of them, and finally I can export all of this into my own custom configuration. I have a significant amount of time building this.

![image](https://github.com/eslint/eslint/assets/24871108/3aeb3a4c-0932-4ffe-8c12-cc564193714f)

![image](https://github.com/eslint/eslint/assets/24871108/47ba948a-4e4e-4b3d-ad55-ce51cb4a269b)

As of version 9.0.0, the functionality which ESLint provided to read and import it's own rule list is now deprecated.

> [Additionally, methods `Linter#defineRule()`, `Linter#defineRules()`, `Linter#defineParser()`, and `Linter#getRules()` are no longer available.](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-linter-now-expects-flat-config-format)

As you can probably tell by now, the `Linter#getRules()` is critical for my project, as I need to access all rule metadata (I think this is the correct term) such as it's schema, description, deprecated status and so on, which the `getRules` method previously exposed and [that I'm currently using](https://github.com/virtuallyunknown/dev-deps/blob/master/packages/eslint-server/src/libs.ts#L15).

I have found a now closed issue #18103 and one of the reasons provided there by @nzakas was that:

> Fundamentally, there's no need to access the raw rule objects, so we didn't include a replacement.

but as you can see, I rely on this functionality for my project. As a matter of fact, without it I am not sure I can even migrate my project to ESLint version 9.0.0, which I was super excited about.

Another person in the comments mentions about the [`rules_meta.json`](https://github.com/eslint/eslint/blob/main/docs/src/_data/rules_meta.json) file, but I don't think this is included with ESLint when installed via npm. 

### What do you think is the correct solution?

Please provide a way to access eslint rules and their metadata programmatically, essentially the same or similar functionality like `Linter#getRules()`.

Thanks!

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

My project: 

- https://github.com/virtuallyunknown/dev-deps

My ESLint configuration:

- https://www.npmjs.com/package/@virtuallyunknown/eslint-config?activeTab=code

**Comment by mdjermanovic** [comment]
Can you load rules from `eslint/use-at-your-own-risk`?

https://github.com/eslint/eslint/blob/16b6a8b469d2e0ba6d904b9e858711590568b246/package.json#L10-L14

https://github.com/eslint/eslint/blob/16b6a8b469d2e0ba6d904b9e858711590568b246/lib/unsupported-api.js#L23

**Comment by virtuallyunknown** [comment]
Thanks for the response @mdjermanovic 

Indeed, it appears that I can, and since opening the issue I also found another way to do it.

```ts
// using eslint 9.0.0

import eslintUnsafe from 'eslint/use-at-your-own-risk';
console.log(eslintUnsafe.builtinRules);

// LazyLoadingRuleMap(290) [Map] { ... }

import eslintBase from 'eslint';
console.log(new eslintBase.Linter({ configType: 'eslintrc' }).getRules());

// Map(290) { ... }
```

The `builtinRules` property is showing me a deprecation warning in the editor, while `Linter({ configType: 'eslintrc' })` is giving me a typescript error that `Type '"eslintrc"' is not assignable to type '"flat"'.ts(2322)`.

Both of these methods successfully output all of ESLint's rules as far as runtime behavior is concerned, however when I see that something is deprecated I assume it's

1. Going to be removed at some future point in time.
2. Become incompatible with current version (9.0.0 or higher) if it already isn't.

I am not in a rush to migrate to 9.0.0 but you can see where my uncertainty lies, so I would appreciate an advice on how to deal with this problem.

Cheers!

**Comment by mdjermanovic** [comment]
We're exporting `builtinRules` through `use-at-your-own-risk` because rules can change at any time. For example, we could rename `messageId`s or change the set of listeners returned by `create()`, which might then break custom rules that load and wrap builtin rules to modify their functionality. Therefore, we wouldn't like to guarantee each rule's API and therefore be forced to wait for the next major release before we can make any changes of this kind. Please see the discussions in https://github.com/eslint/rfcs/pull/80 for more details about this reasoning.

> 1. Going to be removed at some future point in time.
> 2. Become incompatible with current version (9.0.0 or higher) if it already isn't.

I think it's unlikely that we'll remove the `builtinRules` export or change what it is (a Map to the rules) in the foreseeable future, but the rules themselves can change.

@eslint/eslint-team  any thoughts about supporting these use cases (tools that need the list of rules and their metadata)?

**Comment by fasttime** [comment]
The type definitions are incomplete:`configType` has type `"flat"`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0cebe5d5bcaad4a8f18e525b1cd098583b252585/types/eslint/index.d.ts#L844C55-L844C74

This explains why TypeScript is complaining about `"eslintrc"` not being assignable to type `"flat"` (i.e. the type of `configType`). This is an issue in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) and should be reported there.

ESLint doesn't validate the value of `configType`, but it's documented that [it can be `"eslintrc"`](https://github.com/eslint/eslint/blob/b7cf3bd29f25a0bab4102a51029bf47c50f406b5/docs/src/use/migrate-to-9.0.0.md?plain=1#L697).

**Comment by virtuallyunknown** [comment]
Thanks for the in-depth explanations folks, I appreciate it once again. Knowing these methods of accessing the rule metadata won't get suddenly removed, I can now safely proceed with my migration to eslint 9.0.0.

And perhaps I should have been more clear about this (I didn't want to make the post unnecessary long), but for the purposes of my project, I only care about rule meta, so even if the `create()` methods/functions change it doesn't affect anything for me. Furthermore, I expect the rule meta to change between different eslint versions, and the UI I've created is showing me the exact changes.

One last question if you don't mind, should I use `builtinRules` from the `use-at-your-own-risk` import or `Linter({ configType: 'eslintrc' })` from the normal import as they appear functionally identical.

In a few hrs I will also look into opening an issue on `DefinitelyTyped` about the problem @fasttime mentioned.

Cheers!

**Comment by mdjermanovic** [comment]
`new Linter({ configType: 'eslintrc' })` will work in ESLint v9, but will stop working in ESLint v10 when we remove all support for eslintrc configs and functionalities.

**Comment by virtuallyunknown** [comment]
All right, then I suppose the `use-at-your-own-risk` import is the better option for me, so I will stick with that.

**Comment by nzakas** [comment]
In the future, all rules will be removed from the core and moved into `@eslint/js`, so I don't think it's worth making any changes at this point.

**Comment by aladdin-add** [comment]
closing as it's not something we want to add.
