### ISSUE TITLE
Change Request: Provide a Nodejs API for outputing custom lintFiles progress logs

### ISSUE THREAD

**Issue by ShuLaoda** [eslint/eslint#18325]
### ESLint version

7.32.0

### What problem do you want to solve?

Well, I use the Node.js APIs of ESLint to implement the lint command for my CLI, which is a very nice way. 
For example: `umi lint` or `next lint`. The former executes commands, while the latter uses Node.js API `lintFiles`.

However, both of the above methods have a common issue — when the project is large and complex, users have to wait for a long time after running the lint command in the terminal before LintResults logs can be output. While the former can output logs by defining the command parameter `--debug`, many of the contents are unnecessary, and the format of the log content cannot be customized.

I hope to be able to customize the output of the current file name or operation progress when processing each file in the lintFiles function.

### What do you think is the correct solution?

I can hack ESLint code or match all files before executing the lintFiles function. However, this is unnecessary and unsafe. So, I had to ask ESLint to make some changes and provide more useful Node.js APIs.

Before raising this issue, I did a lot of thinking and had several feasible suggestions and ideas:

- Add a new ESLint options parameter, which can be called `outputLIntInfo: (fileInfo: FileEntry) => void`. 
```
eslint/lib/cli-engine/cli-engine.js

class CLIEngine {
        ...

       executeOnFiles(patterns) {
              ...

              for (const { config, filePath, ignored } of fileEnumerator.iterateFiles(patterns)) {
                    outputLIntInfo({ config, filePath, ignored });
              ...
       }
       ...
}
```
However, the above method can only output the file information currently being processed, but cannot output the processing progress. Unless like this: 
```
eslint/lib/cli-engine/cli-engine.js

class CLIEngine {
        ...

       executeOnFiles(patterns) {
              ...

              [...fileEnumerator.iterateFiles(patterns)].forEach(({ config, filePath, ignored }, index) => {
                     outputLIntInfo({ config, filePath, ignored, current: index, total: files.length });
              ...
       }
       ...
}
```
Of course, the above approach also has drawbacks, as it will take up more memory.
- In addition, a method can also be provided that allows users to match patterns to obtain all file paths before using lintFIles.
```
      const eslint = new ESLint(eslintConfig);
      ...
      const files = eslint.matchPatterns(patterns), total = files.length;

      for(let [cur, filename] of files) {
            console.log(`Linting: ${filename}  ${cur}/${total}`);
            await eslint.lintFiles(filename);
      ...
}
```
Of course, the above code also has disadvantages. It will break the original ESLint code logic and does not look standardized and reasonable.

I hope you ESLint team can give me some advice and help me solve this issue!

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
You can currently get a lot of info using the `--debug` flag on the command line or by setting `DEBUG=eslint:*` as an environment variable. Will either of those solve your problem?

**Comment by ShuLaoda** [comment]
> You can currently get a lot of info using the `--debug` flag on the command line or by setting `DEBUG=eslint:*` as an environment variable. Will either of those solve your problem?

I mentioned this, but it doesn't solve my problem because a lot of debug information is unnecessary and cannot be customized.

What I want is to be able to output real-time information about the file currently being processed when I use the ESLint Node.js API `lintFiles`. Because when the project files processed by `lintFiles` are too large, the terminal will pause for a long time without any output.

Like the installation progress bar of NPM, output the processing progress bar or the information of the file being processed of `lintFiles`.

**Comment by ShuLaoda** [comment]
Okay, I understand what you mean. This is indeed the most suitable way to solve this problem.
This question was originally answered 9 years ago. #2152
