### ISSUE TITLE
Support for ES2025 RegExp duplicate named capturing groups

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint#18330]
### Syntax name

Duplicate named capturing groups

### Syntax proposal URL

https://github.com/tc39/proposal-duplicate-named-capturing-groups

### Example code

```js
str.match(/(?<year>[0-9]{4})-[0-9]{2}|[0-9]{2}-(?<year>[0-9]{4})/)
```

### Implementation Checklist

- [ ] Ecma262 update: https://github.com/tc39/ecma262/pull/2721
- [X] ESTree update: That's not necessary.
- [x] Acorn update: https://github.com/acornjs/acorn/commit/9d041c4c950b687df86f87842f458ad72bd7b482
- [X] `eslint-visitor-keys` update: That's not necessary.
- [x] `espree` update: https://github.com/eslint/espree/pull/608
- [X] `eslint-scope` update: That's not necessary.
- [x] `regexpp` update: https://github.com/eslint-community/regexpp/pull/195
- [ ] `eslint`
  - [x] update espree: https://github.com/eslint/eslint/pull/18596
  - [ ] update regexpp: #18630

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Marked as "blocked" until the dependencies are updated to support this syntax.

**Comment by ota-meshi** [comment]
Acorn has been released so I've made some status updates.

**Comment by mdjermanovic** [comment]
Espree has been released and `ecmaVersion: 2025` has been added in ESLint.
