### ISSUE TITLE
requireReturnDescription for valid-jsdoc

### ISSUE THREAD

**Issue by briandipalma** [eslint/eslint#1833]
I was wondering if adding a `requireReturnDescription` option to the valid-jsdoc rule would be acceptable? The major reason for documentation enforcement is to specify types in the code. While I like having good descriptions in the documentation I can see that other people might find it a large burden in a legacy codebase.

I might be able to do this over the weekend if it's acceptable

**Comment by nzakas** [comment]
Fine by me
