### ISSUE TITLE
Rule Change: Add suggestion fixer to no-case-declarations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18349]
### What rule do you want to change?

no-case-declarations

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
/*eslint no-case-declarations: "error"*/

switch (foo) {
  case 1:
    let x = 1;
    break;
}
```

### What does the rule currently do for this code?

No fixers or suggestions, per #15851.

### What will the rule do after it's changed?

Add a suggestion to wrap the `case 1`'s consequent in `{}`:

```js
/*eslint no-case-declarations: "error"*/

switch (foo) {
  case 1: {
    let x = 1;
    break;
  }
}
```

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

The discussion in

**Comment by mdjermanovic** [comment]
> Add a suggestion to wrap the `case 1`'s consequent in `{}`:

Makes sense to me 👍 

This is exactly what the [doccumentation for this rule](https://eslint.org/docs/latest/rules/no-case-declarations) is suggesting - examples of incorrect code are fixed by adding `{}` in examples of correct code.

@eslint/eslint-team thoughts?

> ### Additional comments
> The discussion in

Looks like something is missing here? :)

**Comment by aladdin-add** [comment]
👍

**Comment by nzakas** [comment]
Makes sense. Go for it @JoshuaKGoldberg. 👍

**Comment by JoshuaKGoldberg** [comment]
> Looks like something is missing here? :)

Blurgh, just noticed this. It's a very annoying GitHub bug (https://twitter.com/JoshuaKGoldberg/status/1765397127675498870).

There was some discussion somewhere and I ... don't remember where. Blugh.
