### ISSUE TITLE
Different `let` keywords are caught as an "Unexpected token" with or without the flag

### ISSUE THREAD

**Issue by AntouanK** [eslint/eslint#1834]
Different `let` keywords are caught as an "Unexpected token" with or without the flag `blockBindings`
See the video ( source code is [here](https://github.com/AntouanK/immutabix/blob/master/src/immutabix.js) ) : 
![out](https://cloud.githubusercontent.com/assets/4569111/6187349/3e429384-b37d-11e4-93b9-e06594a7b13c.gif)

**Comment by nzakas** [comment]
Can you show the source code that's causing the issue?

**Comment by AntouanK** [comment]
I added it. You can see the link at the end of my description.

**Comment by nzakas** [comment]
Ah yeah, looks like a dupe of #1805 (`const` and `let` act the same way).
