### ISSUE TITLE
Docs: Possibly missing info in `language-options.md` last example

### ISSUE THREAD

**Issue by germanfrelo** [eslint/eslint#18348]
### Docs page(s)

https://eslint.org/docs/latest/use/configure/language-options#predefined-global-variables

### What documentation issue do you want to solve?

In the last section of https://eslint.org/docs/latest/use/configure/language-options#predefined-global-variables (Predefined global variables), it says:

> For example, here is how you can add `console`, amongst other browser globals, into your configuration.

But the code example doesn't have any `console`:

```js
// eslint.config.js
import globals from "globals";

export default [
    {
        languageOptions: {
            globals: {
                ...globals.browser
            }
        }
    }
];
```

### What do you think is the correct solution?

I suppose adding the `console` or another global example.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Hi @germanfrelo, in that code example, `console` is one of the global identifiers defined in `globals.browser`. Other examples with globals identified by their names are already shown in the [preceding section](https://eslint.org/docs/latest/use/configure/language-options#using-configuration-files).

**Comment by germanfrelo** [comment]
Ah ok!
