### ISSUE TITLE
Bug: using `--ext` throws an invalid option error

### ISSUE THREAD

**Issue by SamSalvatico** [eslint/eslint#18399]
### Environment

Node version: v20.11.1
npm version: v10.5.2
Local ESLint version: v9.1.1
Global ESLint version: Not found
Operating System: darwin 23.4.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
"scripts": {
    "lint": "eslint . --ext .ts"
}
```
</details>

### What did you expect to happen?

`--ext` works as expected or remove it from docs

### What actually happened?

Moving to `v9.1.1` I am getting the following error
```
package@0.0.1 lint:fix
> eslint . --ext .ts --fix

Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

I opened the URL, but `--ext` is extensively used in docs

### Link to Minimal Reproducible Example

https://eslint.org/play/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
it's working as expected. `--ext` is eslintrc-mode-only, and has been documented: https://eslint.org/docs/latest/use/command-line-interface#--ext

**Comment by aladdin-add** [comment]
In flat configs, you can use `{files: ["**/*.ts"], ...config}`, and it just works.

**Comment by SamSalvatico** [comment]
Thank you!

**Comment by SamSalvatico** [comment]
> it's working as expected. `--ext` is eslintrc-mode-only, and has been documented: https://eslint.org/docs/latest/use/command-line-interface#--ext

One note: the examples under the disclaimer are not working, if no additional configurations are set

```
npx eslint . --ext .ts
```
<img width="440" alt="image" src="https://github.com/eslint/eslint/assets/40636569/f12c76b3-c848-4b47-9309-ad0a224bd743">
