### ISSUE TITLE
Change Request: use env npm_execpath in alias init

### ISSUE THREAD

**Issue by RodrigoDornelles** [eslint/eslint#18396]
### ESLint version

v8.56.0

### What problem do you want to solve?

compatibility with other runtimes such as **bun** and **deno**.

### What do you think is the correct solution?

in file `bin/eslint.js`

replace 
```javascript
const spawn = require("cross-spawn");

spawn.sync("npm", ["init", "@eslint/config"], { encoding: "utf8", stdio: "inherit" });
```
to
```javascript
const spawn = require("cross-spawn");
const npm = process.env.npm_execpath || "npm";

spawn.sync(npm, ["init", "@eslint/config"], { encoding: "utf8", stdio: "inherit" });
```

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

I created a PR, but it was rejected because it needed an RFC as per the comment. https://github.com/eslint/eslint/pull/18178#issuecomment-2032740972 

need create an RFC documenting it in the [eslint/rfcs](https://github.com/eslint/rfcs) repository, after that maybe re-opening my contribution;

related: https://github.com/oven-sh/bun/issues/6728

**Comment by nzakas** [comment]
Happy have an RFC submitted for this. :+1:

**Comment by Rec0iL99** [comment]
Not stale. Waiting for an RFC.

**Comment by nzakas** [comment]
This is the second stale notice we've got. If we don't have any RFC for the next one, then it's time to close this issue.

**Comment by nzakas** [comment]
no RFC, so closing.
