### ISSUE TITLE
Bug: object-shorthand loses type parameters when auto-fixing

### ISSUE THREAD

**Issue by aldeed** [eslint/eslint#18429]
### Environment

Node version: v18.19.0
npm version: v10.7.0
Local ESLint version: v8.57.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.4.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "object-shorthand": [
      "error",
      "always",
      { avoidExplicitReturnArrows: true },
    ],
  },
};
```
</details>

Run auto-fix on this:

```js
const testObj = {
  myMethod: <T>(obj: T): T => {
    return obj;
  },
};
```

### What did you expect to happen?

```ts
const testObj = {
  myMethod<T>(obj: T): T {
    return obj;
  },
};
```

### What actually happened?

```ts
const testObj = {
  myMethod(obj: T): T {
    return obj;
  },
};
```

### Link to Minimal Reproducible Example

https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=MYewdgzgLgBFCm0DyAjAVjAvDA3gKBhgFsBPAWXigAsQATALhgB4AVAPgAoR1GWBKXlja4ChGACdKAV3FgY3NAG5RAXwA0eFcqA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQPYCMArRAYwBcBaZAC12jOoEMA7AE3TAG1xsdFpodSABoevSI3gB3RgE9Uo3hCxKcjAG64AlqwCiADwAO8LSS1kASojKxozAIIDcU1BjJxEY7AF8vAXR5fbyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

First reported [here](https://github.com/typescript-eslint/typescript-eslint/issues/9008).

**Comment by nzakas** [comment]
Thanks for the report. I think we can tweak the rule to fix this.
