### ISSUE TITLE
Use strict error during validation of all files

### ISSUE THREAD

**Issue by lmaze** [eslint/eslint#1844]
I just installed eslint (v0.14.1) with a fresh installation of node (v0.12.0 x64 windows version).
Everything seems okay but when I run eslint on a file, I get the same error each time :
**1:0  error  Use the function form of "use strict"  global-strict**

The file I am trying to validate is very simple. I tried with the same example as the one on the website :
```javascript
"use strict";
function foo() {
    return function() {
        return;
    };
}
foo();
```

I tried many things but no change works.

My validation rules are very simple too :
```javascript
{
    "env": {
        "browser": true
    },
    "rules": {
        "strict": [2, "global"],
        "eol-last": 0
    }
}
```

I tested with the latest node in version 0.10.36 too and the error is still present.

I'm not a beginner in node and I really want to use eslint for our projects but in this situation it is impossible.
I think it really looks like a bug.

**Comment by nzakas** [comment]
Right now we have overlapping rules for strict mode for backwards compatibility.  See: http://eslint.org/docs/rules/#strict-mode

Try adding this to your config:

```
global-strict: 0
```

**Comment by lmaze** [comment]
Works best with this adjustment :)

I thought that the "global-strict" and "no-extra-strict" rules were automatically disabled when using the new "strict" rule.

Thank you so much for your quick response and for this great project !

**Comment by nzakas** [comment]
Sorry about the confusion...we kept the old rules with their old settings so as not to disrupt any existing users. For 1.0.0, we will remove the old ones and turn the new one on by default.
