### ISSUE TITLE
Rule Change: Suggestion fixer for `prefer-destructuring`

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [eslint/eslint#18460]
### What rule do you want to change?

prefer-destructuring

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
const selectedCost = costs[index_ - 1]
```
![image](https://github.com/eslint/eslint/assets/84519004/e284b656-d31f-4df3-b3e8-18fbb0fa52d7)

### What does the rule currently do for this code?

Warn but doesn't offer fixes

### What will the rule do after it's changed?

Offer a suggestion to manually fix:
```js
const {[index_ - 1]: selectedCost} = costs
```

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

My original use-case was actually for `@typescript-eslint/prefer-destructuring`. If I understand correctly, if this is added for ESLint, typescript-eslint should follow with their support.

From:
```ts
export abstract class Question {
  readonly id?: number
  readonly text: string

  constructor(data: {
    readonly id?: number,
    readonly text: string,
  }) {
    this.id = data.id
    this.text = data.text
  }
}
```
To:
```ts
export abstract class Question {
  readonly id?: number
  readonly text: string

  constructor(data: {
    readonly id?: number,
    readonly text: string,
  }) {
    ({ id: this.id, text: this.text } = data)
  }
}
```

The parenthesis requirement make the `enforceForRenamedProperties` option hard for me to enable as I feel like other team members will also get confused as to why the syntax is incorrect until realizing that parenthesis are required w/o assignement keywords.

**Comment by aladdin-add** [comment]
the plugin is not maintained by eslint team. please file it in https://github.com/typescript-eslint/typescript-eslint.

**Comment by Samuel-Therrien-Beslogic** [comment]
@aladdin-add I did mean `prefer-destructuring` and accidentally left in `@typescript-eslint`. Could you please reopen?

**Comment by Tanujkanti4441** [comment]
Hi @Samuel-Therrien-Beslogic, 

>const selectedCost = costs[index_ - 1] 
>fixes to
>const {[index_ - 1]: selectedCost} = costs

this example is a bit confusing, while `const selectedCost = costs[index_ - 1];` accesses an array element directly, the fix `const {[index_ - 1]: selectedCost} = costs;` suggests object destructuring, which is not applicable to arrays
can you please add some code example you want to have suggestions for with appropriate fixes?

**Comment by kirkwaiblinger** [comment]
@Tanujkanti4441 

> which is not applicable to arrays

although it's confusing code (IMO), the suggestion in the issue does appear to work as described. Object destructuring with computed keys evidently works just fine on an array; the indices are just properties.

**Comment by Tanujkanti4441** [comment]
> @Tanujkanti4441
> 
> > which is not applicable to arrays
> 
> although it's confusing code (IMO), the suggestion in the issue does appear to work as described. Object destructuring with computed keys evidently works just fine on an array; the indices are just properties.

@kirkwaiblinger, sorry for replying late, and thanks for correcting me, i wasn't aware of this.

but right now rule doesn't report on retrieving the array element with index assign to a variable, so it can't have a suggestion.
[playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1kZXN0cnVjdHVyaW5nOiBcImVycm9yXCIgKi9cblxuY29uc3QgZm9vID0gY29zdHNbMF07XG5cbmNvbnN0IHNlbGVjdGVkQ29zdCA9IGNvc3RzW2luZGV4XyAtIDFdIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==) 

Even it reports such cases when `enforceForRenamedProperties` is `true` but, in that case it assume the code as it is assessing or renaming an object property.
[playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IFwicHJlZmVyLWRlc3RydWN0dXJpbmdcIjogW1wiZXJyb3JcIiwgeyBcIm9iamVjdFwiOiB0cnVlIH0sIHsgXCJlbmZvcmNlRm9yUmVuYW1lZFByb3BlcnRpZXNcIjogdHJ1ZSB9XSAqL1xuY29uc3QgZm9vID0gY29zdHNbMF07XG5cbmNvbnN0IHNlbGVjdGVkQ29zdCA9IGNvc3RzW2luZGV4XyAtIDFdIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==)

and i am not sure about adding suggestions for:

```js
{
    this.id = data.id,
    this.text = data.text
 }
 
fixes to 

({ id: this.id, text: this.text } = data)
```
curious to know what other says @eslint/eslint-team.

**Comment by JoshuaKGoldberg** [comment]
> and i am not sure about adding suggestions for:

IMO if the rule is giving a report about some code, that's an indication the user explicilty wants the rule to help them get to change their code. In this case the intent seems to be to use the `({ ... } = ...)` oddity. +1 from me on giving a suggestion fixer in that case.

**Comment by nzakas** [comment]
In general, if it's easy to offer suggestions, we go ahead and do it. We don't guarantee any rule will have suggestions, and there is a slightly performance penalty for providing them. 

So overall, is it easy to add this suggestion? If so, go ahead. If not, then we'll skip it.

**Comment by Samuel-Therrien-Beslogic** [comment]
> this example is a bit confusing, while `const selectedCost = costs[index_ - 1];` accesses an array element directly, the fix `const {[index_ - 1]: selectedCost} = costs;` suggests object destructuring, which is not applicable to arrays can you please add some code example you want to have suggestions for with appropriate fixes?

Tbf the real-world examples I fell on could be restructured automatically thanks to type-information (so it was more based on objects and arrays, I gave you that example as a simple reproducer that pure ESLint could pick up).

For more context, I was getting support on how to fix my `From:` example picked up by `@typescript-eslint/prefer-destructuring`. After receiving an answer I asked whether this could be provider as a suggestion fixer, as otherwise it's a bit harder justifying turning on this rule if I expect other devs to not immediately realize an extra set of parenthesis is needed, even with other devs who do like the destructuring syntax:
> I do indeed wish there was an autofix for this (even if an unsafe manual suggestion). If I turn it on as-is in our preset I feel I'm not the only one who's gonna get confused.
> 
> I'll add it to our extra strict preset until more of my team members are used to the destructuring syntax.
> 
> Thanks for the help.

To which @bradzacher answered
> Feel free to file an issue on the upstream eslint repo asking for a suggestion fixer!
> Most rules pre-date suggestion fixers so they weren't built with suggestions.

So here I am doing the request here so that `@typescript-eslint/prefer-destructuring` extends the suggestion fixer to cover cases with type information.

I *personally* wouldn't care if ESLint didn't have suggestion fixer for `prefer-destructuring` but @typescript-eslint did (currently neither do)

**Comment by kirkwaiblinger** [comment]
@Samuel-Therrien-Beslogic Would you kindly link the issue/conversation that you're referring to with Brad Zacher? Just trying to follow the paper trail. 

*** 

Also, note that typescript-eslint has just received a report which likely would have been averted if the rule had suggestions:  https://github.com/typescript-eslint/typescript-eslint/issues/9561.

**Comment by kirkwaiblinger** [comment]
FYI - I'd be happy to submit a PR for this if the issue gets marked accepted.

**Comment by nzakas** [comment]
@eslint/eslint-tsc looking for feedback on this request.

**Comment by Samuel-Therrien-Beslogic** [comment]
> @Samuel-Therrien-Beslogic Would you kindly link the issue/conversation that you're referring to with Brad Zacher? Just trying to follow the paper trail.

Sure thing! (I really should've posted it in the first place, I try to have a habit of linking for that exact purpose, added to my previous post as well)
https://discord.com/channels/1026804805894672454/1240457693786013757

**Comment by mdjermanovic** [comment]
This looks like a useful feature, but since this rule falls under stylistic rules, which are generally frozen for new features, and these suggestions don't look quite easy to implement (in particular, when a sequence of assignments should be merged into one destructuring assignment), my opinion is neutral.

**Comment by kirkwaiblinger** [comment]
Is there a list or indication somewhere of what constitutes a stylistic rule? I am struggling to find any docs or issues that indicate prefer-destructuring is feature frozen or deprecated. 
I have looked: 
- https://eslint.org/docs/latest/rules/prefer-destructuring
- https://eslint.org/blog/2020/05/changes-to-rules-policies/#what-are-the-changes
- https://github.com/eslint/eslint/issues/17681
- https://github.com/eslint/eslint/issues/17522

I see plenty of other rules discussed in those, but not `prefer-destructuring`.

**Comment by kirkwaiblinger** [comment]
Had a stab at this, turned out to be quite easy (at least to get a working prototoype) https://github.com/eslint/eslint/commit/355ff175791efaa266aba1005f8d340d6f794581

**Comment by fasttime** [comment]
I'm fine with adding suggestions to `prefer-destructuring` as discussed here.

I closed change requests about adding suggestions or autofix to a rule before on the grounds that the rule was stylistic, so don't ask me to explain what was different about those requests.

> Is there a list or indication somewhere of what constitutes a stylistic rule? I am struggling to find any docs or issues that indicate prefer-destructuring is feature frozen or deprecated.

Actually I thought it would be good to explicitly mark rules that welcome contributions in the docs (not frozen, stylistic, formatting-related, deprecated or else).

**Comment by nzakas** [comment]
> Actually I thought it would be good to explicitly mark rules that welcome contributions in the docs (not frozen, stylistic, formatting-related, deprecated or else).

I agree. We should mark this clearly on the website so there is no confusion, and we should be better at enforcing the "frozen" status. Does anyone want to take that as an action item? I opened an issue:
https://github.com/eslint/eslint/issues/18694

**Comment by kirkwaiblinger** [comment]
That in mind, shall we close out this issue or proceed with a PR along the lines of https://github.com/eslint/eslint/commit/355ff175791efaa266aba1005f8d340d6f794581? Just lmk 🙂

**Comment by nzakas** [comment]
On the grounds of following our own rules around frozen rules, I'm closing this.
