### ISSUE TITLE
Ignore reserved keyword

### ISSUE THREAD

**Issue by wprater** [eslint/eslint#1848]
is there a way I can ignore these errors, or set them to warning?  Im writing ES6 module format and the sublimetext linter using ESLint stops at the first error so I wont see the other linting issues.

**Comment by gyandeeps** [comment]
You might want to log the issue here: https://github.com/roadhump/SublimeLinter-eslint

**Comment by nzakas** [comment]
Sorry, there's nothing we can do until the parser fully supports ES6. Until that point, any ES6 syntax we don't support will end up throwing an error. We're trying really hard to get ES6 stuff done, but there's a lot of discussion around the proper AST structure and we want to be sure we're not just hacking something together that will need to change in the future.
