### ISSUE TITLE
Change Request: deprecate nodeType in context.report

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#18485]
### ESLint version

v9.3.0

### What problem do you want to solve?

The Rule Tester currently does not allow validating whether a node is passed in the `context.report` call as the `type` matcher seems to be the only error matcher which uses a [truthy check](https://github.com/eslint/eslint/blob/389744be255717c507fafc158746e579ac08d77e/lib/rule-tester/rule-tester.js#L1082).
As such setting the `type` to `null` in the error matcher does not check anything.
In other words it currently is not possible to test the following scenario:
```javascript
// Report requires either a node or loc
context.report({ loc: { ... } }); // Resulting message has nodeType: null
```

### What do you think is the correct solution?

Use `hasOwnProperty(error, "type")` (or better `Object.hasOwn`) instead of the truthy check.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

There should probably be an extra error message if no node is passed in the report and `type !== null`.

**Comment by mdjermanovic** [comment]
Just to summarize, you're proposing that `type: null` in error test objects should assert that `nodeType` is `null` in the actual error (lint message)?

**Comment by DMartens** [comment]
Yes that is what I meant. I updated the issue to clarify this.

**Comment by nzakas** [comment]
I'm not sure how useful this would be. The `nodeType` property was kind of a leftover from the early days where you could only pass `node` as an argument and no location data. I'd rather deprecate `nodeType` and say that it shouldn't used for any particular purpose.

**Comment by fasttime** [comment]
> I'm not sure how useful this would be. The `nodeType` property was kind of a leftover from the early days where you could only pass `node` as an argument and no location data. I'd rather deprecate `nodeType` and say that it shouldn't used for any particular purpose.

I agree to deprecate `nodeType`. If we do that, we should probably also deprecate the `type` property on test objects, as that will be checked against a deprecated property.

**Comment by DMartens** [comment]
If the `nodeType` is deprecated, then there is no need for a `node` in the report as only the nodes `loc` is used if no other `loc` is specified.
In other words in that case, it would be clearer if only the `loc` is specified:
```javascript
context.report({ node, loc }) // Node would be completely ignored
// should  either be
context.report({ loc }) // Use a custom loc
// or
context.report({ loc: node.loc }) // Meant to use the node.loc
```

My primary motivation to test the `nodeType` is that other developers may use the reported node in meta rules, e.g. via [eslint-rule-extender](https://github.com/kaicataldo/eslint-rule-extender).

**Comment by nzakas** [comment]
@DMartens Yeah, we kept accepting `node` as an argument for backwards compatibility to older versions of ESLint.

**Comment by Rec0iL99** [comment]
ping @eslint/eslint-team

**Comment by nzakas** [comment]
@mdjermanovic looks like the decision here is whether or not to deprecate `nodeType`. I and @fasttime are in favor.

**Comment by mdjermanovic** [comment]
I agree to deprecate and eventually remove `LintMessage#nodeType` because info about the type of the AST node where the problem is detected doesn't seem to make much sense in lint messages.

**Comment by nzakas** [comment]
> If the `nodeType` is deprecated, then there is no need for a `node` in the report as only the nodes `loc` is used if no other `loc` is specified.

Yes, So originally, messages had to have a `node` specified because I thought every message would apply directly to a node. Only later did we discover that it's more useful to specify the location as separate from any particular node in case you want to adjust the start/end position. And then there was a memory issue where keeping `node` in the message was keeping the AST of every linted file in memory and crashing Node.js. In order to preserve some of that data we switched to `nodeType`, but alas, that's still not useful.

We've agreed to deprecate `nodeType`. We should mention this in the docs.
