### ISSUE TITLE
Bug: ignores key is not ignoring the specified files/directory

### ISSUE THREAD

**Issue by keshav-bohr** [eslint/eslint#18491]
### Environment

Node version: v21.7.3
npm version: v10.5.0
Local ESLint version: v9.3.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.5.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


export default [
  {languageOptions: { globals: globals.browser }, ignores: ["dist/**/*", "src/db/**/*"]},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```
</details>

```js
'use strict';
const {
  Model
} = require('sequelize');
const { Sequelize } = require('.');
module.exports = (sequelize, DataTypes) => {
  class role extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      role.hasMany(models.User,{foreignKey:'roleId'})
    }
  }
  role.init({
    role: DataTypes.STRING,
    scopes: DataTypes.JSON,
    },
  {
    sequelize,
    modelName: 'role',
    tableName: 'roles'
  });
  return role;
};
```

### What did you expect to happen?

I was expecting that the directory should be ignored using the pattern that is defined in the `eslint.config.mjs` file. But it is not happening. It is including the files there. 

I renamed the file to `eslint.config.js`, it resolved the lint errors but gave a different error

### What actually happened?

The files are not excluding from the lint checks.

When the config was renamed to `eslint.config.js`, it gave `SyntaxError: Cannot use import statement outside a module` this error

### Link to Minimal Reproducible Example

https://github.com/Carnera-Tech/candidateportal-BE

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @keshav-bohr, thanks for the issue!

If you want ESLint to completely ignore certain files/directories, `ignores` should be the only key in the configuration object.

```js
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


export default [
  {ignores: ["dist/**/*", "src/db/**/*"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores

When `ignores` is used in a configuration object that has other keys, it only means that that configuration object doesn't apply to files/directories matched by ignores.

https://eslint.org/docs/latest/use/configure/configuration-files#excluding-files-with-ignores
