### ISSUE TITLE
Change Request: Supporting custom rule usage for ESModule projects

### ISSUE THREAD

**Issue by projectoneburmistrovdm** [eslint/eslint#18512]
### ESLint version

v8.57.0

### What problem do you want to solve?

Using custom rules is only available for CommonJS projects because _load-rules.js_ uses _require()_ to load rule files.

My project is built on [Vite](https://github.com/vitejs). [CommonJS syntax is deprecated in Vite and will be removed in the next major version](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated)

My project environment:
**ViteJS** version: 5.0.10
**ESLint** version: 8.57.0
**vite-plugin-eslint** Version: 1.8.1
**Node** version: 20.13.1
**NPM** version: 10.5.2

With the option "type": "module" in my project's package.json I got the following error using a custom rule:

Error [ERR_REQUIRE_ESM]: require() of ES Module _PATH_TO_RULE_ from _PROJECT_PATH_/node_modules/eslint/lib/cli-engine/load-rules.js not supported.
_RULE_FILENAME_ is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename digimap-lazyload.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in _PROJECT_PATH_/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

### What do you think is the correct solution?

Allow to use _.cjs_ extension for rule files

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Please provide a reproducible case in [StackBlitz](https://stackblitz.com) and we can take a look.

**Comment by projectoneburmistrovdm** [comment]
https://stackblitz.com/~/github.com/projectoneburmistrovdm/eslint-issue-18512

Removing _"type": "module"_ from _package.json_ helps. But this solve is incompatible with many other tools.
Please, let me prepare a pull request. I have a solution

**Comment by mdjermanovic** [comment]
As @nzakas noted, we aren't making any further changes to eslintrc config system or any options related to it, including `--rulesdir`.

If you still need to use eslintrc and `--rulesdir`, you can add the following `package.json` file to `src/eslint-rules` directory, and loading rules will work.

`src/eslint-rules/package.json`:

```json
{
    "type": "commonjs"
}
```
