### ISSUE TITLE
Bug: Out of Memory Error with 203 files

### ISSUE THREAD

**Issue by kentcdodds** [eslint/eslint#18520]
### Environment

Node version: 20.13.1
npm version: 10.8.0
Local ESLint version: 9.3.0
Global ESLint version: N/A
Operating System: macOS

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```js
import defaultConfig from '@epic-web/config/eslint'

/** @type {import("eslint").Linter.Config} */
export default [
	...defaultConfig,
	{
		rules: {
			// we leave unused vars around for the exercises
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': 'off',
		},
	},
]
```

`@epic-web/config/eslint` looks like this:

```js
import globals from 'globals'

export default [
	{
		ignores: [
			'**/.cache/**',
			'**/node_modules/**',
			'**/build/**',
			'**/public/build/**',
			'**/playwright-report/**',
			'**/server-build/**',
			'**/dist/**',
		],
	},

	// all files
	{
		plugins: {
			'react-hooks': (await import('eslint-plugin-react-hooks')).default,
			react: (await import('eslint-plugin-react')).default,
			import: (await import('eslint-plugin-import-x')).default,
		},
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node,
			},
		},
		rules: {
			'react-hooks/rules-of-hooks': 'error',
			'react-hooks/exhaustive-deps': 'warn',
			'import/no-duplicates': ['warn', { 'prefer-inline': true }],
			'import/order': [
				'warn',
				{
					alphabetize: { order: 'asc', caseInsensitive: true },
					pathGroups: [{ pattern: '#*/**', group: 'internal' }],
					groups: [
						'builtin',
						'external',
						'internal',
						'parent',
						'sibling',
						'index',
					],
				},
			],
		},
	},

	// JS and JSX files
	{
		files: ['**/*.js?(x)'],
		rules: {
			// most of these rules are useful for JS but not TS because TS handles these better
			// if it weren't for https://github.com/import-js/eslint-plugin-import/issues/2132
			// we could enable this :(
			// 'import/no-unresolved': 'error',
			'no-unused-vars': [
				'warn',
				{
					args: 'after-used',
					argsIgnorePattern: '^_',
					ignoreRestSiblings: true,
					varsIgnorePattern: '^ignored',
				},
			],
		},
	},

	// TS and TSX files
	{
		files: ['**/*.ts?(x)'],
		languageOptions: {
			parser: await import('@typescript-eslint/parser'),
			parserOptions: {
				project: true,
			},
		},
		plugins: {
			'@typescript-eslint': (await import('@typescript-eslint/eslint-plugin'))
				.default,
		},
		rules: {
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{
					args: 'after-used',
					argsIgnorePattern: '^_',
					ignoreRestSiblings: true,
					varsIgnorePattern: '^ignored',
				},
			],
			'import/consistent-type-specifier-style': ['warn', 'prefer-inline'],
			'@typescript-eslint/consistent-type-imports': [
				'warn',
				{
					prefer: 'type-imports',
					disallowTypeAnnotations: true,
					fixStyle: 'inline-type-imports',
				},
			],
		},
	},

	// JSX/TSX files
	{
		files: ['**/*.tsx', '**/*.jsx'],
		languageOptions: {
			parserOptions: {
				jsx: true,
			},
		},
		rules: {
			'react/jsx-key': 'warn',
		},
	},
]
```
</details>

This doesn't happen with only one file. I've experienced in a few projects.

### What did you expect to happen?

I expected linting to pass without issue.

### What actually happened?

I get an out of memory (OOM) error.

The project that's currently having the problem is: https://github.com/epicweb-dev/react-performance ([here's a failed job run](https://github.com/epicweb-dev/react-performance/actions/runs/9258390959/job/25468367755#step:6:10)). I experience this locally as well as in CI.

I'm even having trouble when running this with `bun -r bun run lint` (which runs with bun instead of Node.js and should have much more memory to work with).

### Link to Minimal Reproducible Example

https://github.com/epicweb-dev/react-performance

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

When I run with `--debug` I get this line:

```
  eslint:eslint 203 files found in: 48ms +48ms
```

That seems accurate for this project. But it certainly doesn't seem like so many files that ESLint should have a problem.

Unfortunately I don't have time just now to make a truly minimal reproduction to narrow down the issue and I don't have time to contribute a fix. I understand if this means the issue is closed. But I thought it would be useful (relatively early) feedback on ESLint v9.

**Comment by nzakas** [comment]
This is actually an issue with [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) rather than ESLint itself. This plugin is known to have memory issues because it reads the entire project into memory to do its analysis. Please open an issue there.

**Comment by fenying** [comment]
Hi, @nzakas 

In my project, which contains 412 `.ts` files, eslint v8.57.1 costs no more than 1GiB memory. However, with eslint v9.13.0, it costs more than 4GiB memory.

Is that really a problem due to typescript-eslint plugin? I am using typescript-eslint@8.11.0.
