### ISSUE TITLE
Bug: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vikdet** [eslint/eslint#18525]
### Environment

Node version: 20.10.0
npm version: 10.2.4
Local ESLint version: 9.3.0
Global ESLint version: -
Operating System: Mac Os

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
I have the following project structure:
--REPOS
  --dart 
     --repo-1
     --repo-2
     ........
     --repo-400       
   --ts
     --repo-1
     --repo-2
     ........
     --repo-220     
--src/...
eslint.config.js
```
</details>

```js
const tseslint = require('typescript-eslint');
const commonConfig = require('@wrike/eslint-config/node');
const common = require('@wrike/eslint-config/common');

module.exports = tseslint.config(
  {
    ignores: ['REPOS/'],
  },
  ...commonConfig,
  {
    files: common.files,
    rules: {
      '@typescript-eslint/no-use-before-define': ['error', { functions: false }],
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          checksVoidReturn: false,
        },
      ],
    },
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: __dirname,
      },
    },
  },
);
```

I run eslint . --fix and it fails

### What did you expect to happen?

I expect eslint will ignore all content inside REPOS/ folder.

### What actually happened?

It looks like it tries to analyse REPOS/ folder and fails with 

<--- Last few GCs --->

[72317:0x160008000]   143421 ms: Mark-Compact (reduce) 4070.4 (4142.9) -> 4070.3 (4143.6) MB, 1605.96 / 0.00 ms  (+ 56.1 ms in 15 steps since start of marking, biggest step 5.8 ms, walltime since start of marking 1684 ms) (average mu = 0.648, current mu =[72317:0x160008000]   144843 ms: Mark-Compact (reduce) 4071.6 (4143.9) -> 4071.2 (4144.6) MB, 1416.00 / 0.00 ms  (average mu = 0.450, current mu = 0.004) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x10278553c node::Abort() [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 2: 0x10278573c node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 3: 0x10290a6c4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 4: 0x102adedb8 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 5: 0x102add894 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 6: 0x102ad40ac v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 7: 0x102ad490c v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 8: 0x102ab997c v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
 9: 0x102ea1444 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]
10: 0x103200c44 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/Users/vitalii.bevzik/.nvm/versions/node/v20.11.0/bin/node]

### Link to Minimal Reproducible Example

I don't have public link

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

When I run eslint REPOS/ it works

Oops! Something went wrong! :(

ESLint: 9.3.0

You are linting "REPOS/", but all of the files matching the glob pattern "REPOS/" are ignored.

If you don't want to lint these files, remove the pattern "REPOS/" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.

**Comment by nzakas** [comment]
This is actually an issue with [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) rather than ESLint itself. Please open an issue there.

**Comment by vikdet** [comment]
Ok, thanks
