### ISSUE TITLE
Getting "Missing semicolon" when using a for-of loop

### ISSUE THREAD

**Issue by andersekdahl** [eslint/eslint#1852]
Hi,
The following code:
```
'use strict';

let definition = {};
let store = {};

for (let prop of definition) {
  store[prop] = prop;
}
```
Produces the error "Missing semicolon (semi)".

My guess by looking at the semi-rule is that it needs to check for `ForOfStatement` and not just `ForStatement` and `ForInStatement`.

I'm using version 0.14.1.

My .eslintrc contains this:
```
{
  "ecmaFeatures": {
    "blockBindings": true,
    "forOf": true,
    "jsx": true,
    "arrowFunctions": true,
    "blockBindings": true,
    "defaultParams": true
  },
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "semi": 2,
    "quotes": [2, "single"],
    "eol-last": 0,
    "new-cap": 0,
    "indent": [2, 2],
    "brace-style": [2, "1tbs"],
    "comma-spacing": 2,
    "key-spacing": [2, {
      "beforeColon": false,
      "afterColon": true
    }],
    "no-multiple-empty-lines": [1, {
      "max": 2
    }],
    "space-after-function-name": [2, "never"],
    "space-after-keywords": [2, "always", {
      "checkFunctionKeyword": true
    }],
    "space-before-blocks": [2, "always"],
    "space-in-brackets": [2, "never"],
    "space-in-parens": [2, "never"],
    "spaced-line-comment": [2, "always"],
    "no-var": 2,
    "max-len": [2, 120, 2]
  }
}
```

**Comment by nzakas** [comment]
Just to cover our bases, can you paste the full error message in? I'd like to see the line and column numbers.

**Comment by andersekdahl** [comment]
I'm not on the computer where I have it all set up, so I can't give it to
you right now. But I did manage to resolve it by modifying the semi rule to
make a check for "ForOfStatement" in the same way it does with
"ForInStatement", which made the reported error go away.

On Fri, Feb 20, 2015 at 4:56 PM, Nicholas C. Zakas <notifications@github.com

**Comment by andersekdahl** [comment]
Got it setup here, the file only contains:

```
'use strict';

for (let thing of {}) {
  console.log(thing);
}
```

And the error is:
```
3:14  error  Missing semicolon  semi
```

**Comment by nzakas** [comment]
Thanks. Looking at this now.
