### ISSUE TITLE
Providing non-default extensions via CLI.

### ISSUE THREAD

**Issue by tswaters** [eslint/eslint#18521]
### Environment

Node version:  v18.17.1
npm version:  v9.9.2
Local ESLint version:  9.3.0
Global ESLint version:  n/a
Operating System:  Linux

### What parser are you using?

Default (Espree)

### What did you do?

Tried to update to version 9 of eslint and run my lint command --

```
eslint --ext js,jsx .
```

Raises this error,

> Invalid option '--ext' - perhaps you meant '-c'? You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details

That page doesn't say anything about how to use different extensions when using "config.js" mode, here's what it does say:

<details><summary>Details</summary>
<p>

 --ext

eslintrc Mode Only. This option allows you to specify which file extensions ESLint uses when searching for target files in the directories you specify.

    Argument Type: String. File extension.
    Multiple Arguments: Yes
    Default Value: .js and the files that match the overrides entries of your configuration.

--ext is only used when the patterns to lint are directories. If you use glob patterns or file names, then --ext is ignored. For example, npx eslint "lib/*" --ext .js matches all files within the lib/ directory, regardless of extension.
--ext example

```
# Use only .ts extension
npx eslint . --ext .ts

# Use both .js and .ts
npx eslint . --ext .js --ext .ts

# Also use both .js and .ts
npx eslint . --ext .js,.ts
```

</p>
</details> 

There is no mention of "--ext" or "extension" in the v9.0.0 changelog... seems like a miss?

If I search for "extension" or "ext" in the docs, it comes up with only the CLI reference.

The only other case I've found to these changes are in a blog entry, part.2 of the new config:

https://eslint.org/blog/2022/08/new-config-system-part-2/#setting-logical-defaults-for-linting

Which says,

> ESLint searches for .js, .mjs, and .cjs files - With eslintrc, ESLint only ever searched for .js files when you passed a directory name on the command line, and you would need to use the --ext flag to define more. With flat config, all three of the most common JavaScript filename extensions are automatically searched.

Which is...fine.  It doesn't describe how to extend the defaults.  Is this no longer possible?

I've got about a million projects that use ".jsx" extensions for all their files that can't be linted anymore?

### What did you expect to happen?

Any of the following:

* --ext is still supported in the cli when using eslint.config.js

* there is a documented way to lint non-standard extensions such as "jsx" or "tsx"

* this is listed _somewhere_ in the release notes with a migration strategy for those that use jsx or tsx

### What actually happened?

An error gets raised

It goes to a page that doesn't describe the problem.

Release docs don't mention this change at all

The documentation doesn't describe how to lint jsx or tsx files.

### Link to Minimal Reproducible Example

https://github.com/tswaters/vite-project

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The attached "minimal repo" is the boiler plate for a `npm create vite`  -- this includes a bunch of boilerplate, and notably an "App.jsx"

I've removed the existing eslintconfig it generates, and ran `npx eslint --init` and picked standard options... here's a copy-paste from my terminal window:

<details><summary>Details</summary>

```
$ npx eslint --init
You can also run this command directly using 'npm init @eslint/config@latest'.
Need to install the following packages:
@eslint/create-config@1.1.2
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@eslint/create-config@1.1.2',
npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.9.2' }
npm WARN EBADENGINE }
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · react
✔ The React plugin doesn't officially support ESLint v9 yet. What would you like to do? · 9.x
✔ Does your project use TypeScript? · javascript
✔ Where does your code run? · browser
The config that you've selected requires the following dependencies:

eslint@9.x, globals, @eslint/js, eslint-plugin-react, @eslint/compat
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
☕️Installing...
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: vite-project@0.0.0
npm WARN Found: eslint@9.3.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm WARN   node_modules/@eslint-community/eslint-utils
npm WARN     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.3.0
npm WARN   2 more (eslint-plugin-react-refresh, the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.2
npm WARN node_modules/eslint-plugin-react
npm WARN   dev eslint-plugin-react@"^7.34.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: vite-project@0.0.0
npm WARN Found: eslint@9.3.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm WARN   node_modules/@eslint-community/eslint-utils
npm WARN     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.3.0
npm WARN   2 more (eslint-plugin-react-refresh, the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0" from eslint-plugin-react-hooks@4.6.2
npm WARN node_modules/eslint-plugin-react-hooks
npm WARN   dev eslint-plugin-react-hooks@"^4.6.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-react@7.34.2
npm WARN Found: eslint@9.3.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"9.x" from the root project
npm WARN   2 more (@eslint-community/eslint-utils, eslint-plugin-react-refresh)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.2
npm WARN node_modules/eslint-plugin-react
npm WARN   dev eslint-plugin-react@"^7.34.2" from the root project
npm WARN 
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.2
npm WARN   node_modules/eslint-plugin-react
npm WARN     dev eslint-plugin-react@"^7.34.2" from the root project

added 2 packages, changed 1 package, and audited 272 packages in 2s

103 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

</details> 

Afterwards, I added a dummy commit into App.jsx that should raise a lint error.  
```diff
diff --git a/src/App.jsx b/src/App.jsx
index b8b8473..c2b6256 100644
--- a/src/App.jsx
+++ b/src/App.jsx
@@ -6,6 +6,8 @@ import './App.css'
 function App() {
   const [count, setCount] = useState(0)
 
+a = x
+
   return (
     <>
       <div>

```

It doesn't get caught:

```
$ npm run lint

> vite-project@0.0.0 lint
> eslint . --report-unused-disable-directives --max-warnings 0

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
```

**Comment by mdjermanovic** [comment]
To lint files with non-standard extensions, your config file should have at least one `files` pattern that matches those files.

In your example, as per [this note](https://github.com/jsx-eslint/eslint-plugin-react/blob/417e1ca292788c75618dc994b084c3a57c483fce/README.md?plain=1#L233-L255) from eslint-plugin-react docs, eslint config file would be:

```js
// eslint.config.js
import globals from "globals";
import pluginJs from "@eslint/js";
import pluginReactConfig from "eslint-plugin-react/configs/recommended.js";
import { fixupConfigRules } from "@eslint/compat";

export default [
  pluginJs.configs.recommended,
  { 
    files: ["**/*.jsx"], // <- this enables linting .jsx files
    ...fixupConfigRules(pluginReactConfig)[0],
    languageOptions: {
      ...pluginReactConfig.languageOptions,
      globals: {
        ...globals.browser,
      },
    },
  }
];
```

**Comment by mdjermanovic** [comment]
> * there is a documented way to lint non-standard extensions such as "jsx" or "tsx"

@fasttime this will be covered by the PR for https://github.com/eslint/eslint/issues/18475?

> * this is listed _somewhere_ in the release notes with a migration strategy for those that use jsx or tsx

In the [Migrate to v9.x](https://eslint.org/docs/latest/use/migrate-to-9.0.0) guide, [New default config format (`eslint.config.js`)](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-new-default-config-format-eslintconfigjs) section links to [Configuration Migration Guide](https://eslint.org/docs/latest/use/configure/migration-guide), which has a section for this:

https://eslint.org/docs/latest/use/configure/migration-guide#--ext

Perhaps we could also add a link to https://eslint.org/docs/latest/use/configure/migration-guide#--ext in https://eslint.org/docs/latest/use/command-line-interface#--ext?

**Comment by fasttime** [comment]
> > * there is a documented way to lint non-standard extensions such as "jsx" or "tsx"
> 
> @fasttime this will be covered by the PR for #18475?

Yeah, I was thinking to add a paragraph to the [configuration files docs](https://eslint.org/docs/latest/use/configure/configuration-files) to explain how to include files with non-standard or no extension.

**Comment by fasttime** [comment]
Maybe we could also add a note to the [documentation of the `--ext` flag](https://eslint.org/docs/latest/use/command-line-interface#--ext) with a link to the migration instructions at https://eslint.org/docs/latest/use/configure/migration-guide#--ext.

**Comment by mdjermanovic** [comment]
PR to add a link in `--ext` CLI section: https://github.com/eslint/eslint/pull/18537

**Comment by jameswilddev** [comment]
I'm a little surprised that `.jsx` isn't supported by default when the "react" framework is selected during ESLint init given that large elements of JS community such as [Vite explicitly require it](https://github.com/vitejs/vite/issues/13715).  I can see this being a great source of friction for users setting up projects which wasn't present in previous versions.

**Comment by jameswilddev** [comment]
> ```js
> import { fixupConfigRules } from "@eslint/compat";
> ```

I'm afraid this doesn't work as far as I can tell - seems to still be skipping over `.jsx` files.

**Comment by jameswilddev** [comment]
In fact, discussions is full of people who simply can't get this working:

- https://github.com/eslint/eslint/discussions/18453
- https://github.com/eslint/eslint/discussions/18366
- https://github.com/eslint/eslint/discussions/18321

Between this and a multitude of other issues with ESLint 9 I'm going to recommend to the team that all projects stay on ESLint 8 for the foreseeable future.
