### ISSUE TITLE
Change Request: (For React-Redux users)

### ISSUE THREAD

**Issue by ravenkim** [eslint/eslint#18551]
### ESLint version

8.57.0

### What problem do you want to solve?

When i use react redux i have two problem 
```
    useEffect(() => {
        dispatch(routerAction.locationChange(route))
    }, [route])
```

problem 1 
Void function return value is used 

in `routerAction.locationChange(route)`

but actually 

```
 locationChange: (state, action) => {
        state.location = action.payload
    },
```

In this code I do not need return 

so I want this fixed

problem 2
ESLint: React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array.(react-hooks/exhaustive-deps)

It can solve by put 'dispatch' inside [] but it is not needed

Redux's dispatch function is designed to have a constant reference throughout the app's life cycle. That is, even if a component is rerendered, the reference of the dispatch does not change. Therefore, you can prevent the hook from being unnecessarily re-executed without having to include the dispatch in the useEffect or useCallback dependency array.

So if (dependency is dispatch) {no warning plz}
i hope there is extra rules for react users

### What do you think is the correct solution?

no warning for theses two problem

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
the plugin was not maintained by eslint team, please ask the react team for help!
