### ISSUE TITLE
Bug: attempting to init version 8 installs version 9

### ISSUE THREAD

**Issue by jameswilddev** [eslint/eslint#18578]
### Environment

Node version: v20.14.0
npm version: 10.7.0
Local ESLint version: (see below)
Global ESLint version: none
Operating System: Windows 11

### What parser are you using?

Default (Espree)

### What did you do?

```bash
 npx eslint@8 --init
```

### What did you expect to happen?

ESLint 8 to be installed.

### What actually happened?

From the first prompt it is apparent that the ESLint 9 initialization process has started instead of the requested 8:

```
? How would you like to use ESLint? ...
  To check syntax only
> To check syntax and find problems
```

(the option to enforce code style was removed in V9, so this is V9).

If you follow the prompts through to the end, ESLint 9 is indeed installed rather than 8.  I have confirmed this happens on a clean OS install so this isn't a cache issue or similar.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-nhxth9?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I need to install version 8 rather than 9 to work around the following blockers:

- The VS Code ESLint extension only supports version 8 (a preview version for 9 is available but no production-ready release).
- I've yet to get linting of `.jsx` files to work - there's been a few suggested config edits but they did not work when tested.
- ESLint Stylistic [only supports 8 at this time](https://eslint.style/guide/faq#what-s-the-requirements-for-eslint-stylistic).
- Some kind of dependency conflict occurs when installing 9 with TypeScript enabled.

**Comment by nzakas** [comment]
`--init` always runs the version of `@eslint/create-config` that is cached on your machine. If you want to run a specific version, you need to do so like this:

```shell
npx @eslint/create-config@1.0.0
```

I'm pretty sure 1.0.0 will install ESLint 8, but if not, just drop down to 0.x

**Comment by jameswilddev** [comment]
To anyone who finds this issue in future:

```
❯ npx @eslint/create-config@1.0.0
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-06-10T15_47_01_349Z-debug-0.log
```

Unfortunately, the posted solution doesn't work on a fresh machine for me.  You're probably going to have to manually install the dependencies manually given support for 8.x has been dropped before 9.x is ready.

**Comment by nzakas** [comment]
@jameswilddev That error is coming from npm itself. Not sure if you're behind a proxy or something else, but that has nothing to do with the package.

**Comment by hinst** [comment]
The solution does not work either way. Create-config v1 installs ESLint version 9

**Comment by awixor** [comment]
`npx @eslint/create-config@1.0.0` does not work.
I even tried [0.4.6](https://www.npmjs.com/package/@eslint/create-config/v/0.4.6) but still installs v9, the only diff is that it creats old config, which means I had to downgrade eslint version to `8.57.0`

**Comment by Peredery** [comment]
> `npx @eslint/create-config@1.0.0` does not work. I even tried [0.4.6](https://www.npmjs.com/package/@eslint/create-config/v/0.4.6) but still installs v9, the only diff is that it creats old config, which means I had to downgrade eslint version to `8.57.0`

0.1.1 will help
