### ISSUE TITLE
Bug: TypeError: Key "rules": Key "no-useless-assignment": Could not find "no-useless-assignment" in plugin "@".

### ISSUE THREAD

**Issue by agustaf9** [eslint/eslint#18581]
### Environment

Node version: v18.8.0
npm version: v8.18.0
Local ESLint version: v8.57.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22631

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
npm install eslint --save-dev
npm install eslint-config-eslint --save-dev
<!-- Paste your configuration here -->
import eslintConfigESLint from "eslint-config-eslint";

export default [
    ...eslintConfigESLint
];
</details>

```ts
const test = async () => {
    for(let i = 0; i < 10; i++) {
      await fetch('https://jsonplaceholder.typicode.com/todos/1')
    }
  }
```

### What did you expect to happen?

My Files to be linted

### What actually happened?

When running `npx eslint .`
```
Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError: Key "rules": Key "no-useless-assignment": Could not find "no-useless-assignment" in plugin "@".
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-tp3l6j?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
the rule was introduced in v9.0.0-alpha.1, but you were using v8.57.0. please upgrade your eslint and retry.
