### ISSUE TITLE
Bug: 'fi' ligature on eslint website

### ISSUE THREAD

**Issue by awwsmm** [eslint/eslint#18584]
### Environment

Chrome Version 122.0.6261.69

### What parser are you using?

Other

### What did you do?

Visited the eslint website https://eslint.org/

### What did you expect to happen?

To see properly-rendered code in examples and blog posts.

### What actually happened?

`fi` in code snippets exists as a ligature, even in cases where this doesn't make sense, like

https://eslint.org/

> npm init @eslint/config@latest

and in `files` here

https://eslint.org/blog/2022/08/new-config-system-part-1/

> ...config would use an AND operator to merge files and...

### Link to Minimal Reproducible Example

https://eslint.org/

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is a problem with the eslint website, not with eslint itself.

**Comment by snitin315** [comment]
Thanks for creating the issue. This is already being tracked via https://github.com/eslint/eslint.org/issues/577. So, closing as duplicate.
