### ISSUE TITLE
Bug: Error highlight doesn't work on vscode

### ISSUE THREAD

**Issue by Ahmed-Dghaies** [eslint/eslint#18602]
### Environment

Node version: 16.14.0
npm version: 8.3.1
Local ESLint version: 3.0.8
Global ESLint version: 3.0.8
Operating System: MacOs Monterey

### What parser are you using?

Default (Espree)

### What did you do?

Errors are not highlighted anymore and code suggestions doesn't work as expected also

### What did you expect to happen?

Syntax errors should be highlighed

### What actually happened?

no error were highlighted

### Link to Minimal Reproducible Example

no repo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
We don't maintain the VS Code ESLint extension, please open an issue here:

https://github.com/Microsoft/vscode-eslint
