### ISSUE TITLE
Bug: in eslint version 3.0.8 doesn't work errors and wars highlights in vs code

### ISSUE THREAD

**Issue by Egor-Dubovik** [eslint/eslint#18600]
### Environment

Node version: 20.11.1
npm version: 10.8.0
Local ESLint version: 3.0.8
Operating System: Windows

### What parser are you using?

Default (Espree)

### What did you do?

Update eslint to version 3.0.8 and get this bug. In previous version 2.4.4 highlights worked correctly

### What did you expect to happen?

In v3.0.8 highlights worked correctly

### What actually happened?

Don't see highlights but in terminal get errors and wars

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @Egor-Dubovik, thanks for the issue!
 
> Update eslint to version 3.0.8 and get this bug. In previous version 2.4.4 highlights worked correctly

By these version numbers, I assume you're referring to [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

We don't maintain the VS Code extension. You'll need to open an issue here:

https://github.com/Microsoft/vscode-eslint
