### ISSUE TITLE
Docs: Add Algolia logo under search box

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#18620]
### Docs page(s)

https://eslint.org/docs/latest/

### What documentation issue do you want to solve?

Because we're using Algolia DocSearch, we're required to show their logo.

### What do you think is the correct solution?

Place the "Powered by Algolia" text *under* the search box. I think we can use the simpler style on https://dev.to:

![Screenshot 2024-06-21 at 09-36-06 DEV Community](https://github.com/eslint/eslint/assets/38546/4dfb7fa5-122b-4875-a5e6-9db87131c1dd)

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Note: This will also need to be done on eslint.org/blog

**Comment by Tanujkanti4441** [comment]
Sounds good! the search bar's width is short in desktop and mobile size so we can place the text "Powered by Algolia" above the bar something like this:
![Screenshot 2024-06-22 103747](https://github.com/eslint/eslint/assets/86398394/8d2df015-cd23-4f78-a3f8-878716092c5a)

and for tablet size it could be as you suggested:
![Screenshot 2024-06-22 104055](https://github.com/eslint/eslint/assets/86398394/e2580e16-bbf2-487a-8005-8c140bc0f9e8)

**Comment by harish-sethuraman** [comment]
For desktop we can do it below like a sublabel that would be better?

**Comment by Tanujkanti4441** [comment]
That is also looking good.

![Screenshot 2024-06-22 125037](https://github.com/eslint/eslint/assets/86398394/6a3e4f8c-a783-4749-82ea-977c73f74e05)

**Comment by amareshsm** [comment]
> That is also looking good.
> 
> ![Screenshot 2024-06-22 125037](https://private-user-images.githubusercontent.com/86398394/341949861-6a3e4f8c-a783-4749-82ea-977c73f74e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDU1NjcsIm5iZiI6MTcxOTA0NTI2NywicGF0aCI6Ii84NjM5ODM5NC8zNDE5NDk4NjEtNmEzZTRmOGMtYTc4My00NzQ5LTgyZWEtOTc3YzczZjc0ZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA4MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTMyMGZiMDI4Y2ZmMzdkNDc3OGFiNDA4MmUxODU3NTJjOWM3M2RjOTA3MGFlZGVjNTY4ZTg0OWU1NmQxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDxv3zWwB0QIb1mshmq0i0CQFtlKt9Ig6mzVtfMDf3w)

+1 If everyone agrees with this approach, we can display the powered-by label below the input field on all devices.

 I am willing to work on this and will submit a PR.

**Comment by nzakas** [comment]
@Tanujkanti4441 looks good to me!
