### ISSUE TITLE
Bug: Can't reproduce `root: true` behaviour in node API

### ISSUE THREAD

**Issue by sahariko** [eslint/eslint#18639]
### Environment

Node version: v18.12.1
npm version: v8.19.2
Local ESLint version: Not found
Global ESLint version: Not found
Operating System: darwin 22.6.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

When working in a repo that includes [several cascading ESLint configs](https://eslint.org/docs/v8.x/use/configure/configuration-files#cascading-and-hierarchy), you can use the `root: true` configuration option, and that would work great when using ESLint's CLI.

But it seems like [ESLint's node API](https://eslint.org/docs/v8.x/integrate/nodejs-api#-new-eslintoptions) doesn't offer a compatible configuration option.

### What did you expect to happen?

Node API should support the same capabilities as the CLI.

### What actually happened?

Couldn't make it run.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-dppjdj?file=src%2Fmain.ts&terminal=dev

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
@sahariko I have no idea because you didn't provide a reproduction case.

I will say, however, that the CLI uses the Node.js API, so it's more likely that there's a bug in your setup rather than a bug in the API.

**Comment by sahariko** [comment]
> @sahariko I have no idea because you didn't provide a reproduction case.
> 
> I will say, however, that the CLI uses the Node.js API, so it's more likely that there's a bug in your setup rather than a bug in the API.

Gotcha, I'll double-check and see about creating a reproduction (not so straight-forward since it's a complex proprietary project).
