### ISSUE TITLE
es6 environment

### ISSUE THREAD

**Issue by aeosynth** [eslint/eslint#1864]
i'd like an `es6` environment option which enables all of the es6 rules, similar to jshint's [esnext](http://jshint.com/docs/options/#esnext) rule. to be future proof, this could take an argument specifying the exact ecmascript version.

**Comment by nzakas** [comment]
It's too early to know if this is a good idea or not. We only have two es6 specific rules, and like the rest of our rules, there's no guarantee that those or any future rules make sense as defaults.

We are adding the ability to create custom environments in plugins. When that's ready, you'll be able to make your own.

**Comment by aeosynth** [comment]
sorry, i meant the 'language options', of which there are 19? pertaining to es6.

**Comment by nzakas** [comment]
Ah okay. Yes, we will most likely do this once we support all of ES6.

**Comment by glenjamin** [comment]
I'd also like some way to mark either files or extensions as being in "es6" mode, rather than the all-or-nothing approach available currently.

**Comment by nzakas** [comment]
Once we have an es6 environment, you'll be able to use `/*eslint-env */` in a file to use it. We don't plan on supporting configuration based on file extension.

**Comment by glenjamin** [comment]
Do you plan to provide a way to say which es6 features?

My main use-case is when using Babel for react files, I'd like to get the linting to use the same set of features as whatever my transform supports ideally.

**Comment by nzakas** [comment]
@glenjamin please see http://eslint.org/docs/configuring/#specifying-language-options. Also, please send any follow-up questions to the mailing list so we can keep this issue on track.
