### ISSUE TITLE
Rule Change: Auto-fixer for no-unused-expression ternaries

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18654]
### What rule do you want to change?

no-unused-expression

### What change do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
a ? b : c;
```

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLWV4cHJlc3Npb25zOiBcImVycm9yXCIqL1xuXG5hID8gYiA6IGM7Iiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==

### What does the rule currently do for this code?

Reports the unused expression, and doesn't include a fixer.

### What will the rule do after it's changed?

Include a fixer to rewrite the code as:

```js
if (a) {
  b;
} else {
  c;
}
```

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
Would this apply only if the fixed code doesn't have further `no-unused-expressions` errors?

For example, `a ? b() : c()` but not `a ? b : c`.

**Comment by JoshuaKGoldberg** [comment]
For simplicity's sake, I'd think it'd be cleaner to not have the fixer logic care about whether the fix result has additional errors. `a ? b : c` is really _three_ rule violations rolled into one. Fixing the first (`a`) reveals the next two (`b` and `c`). All three of those violations would need to be fixed by users - so having a fixer for as many as possible is helpful IMO.

Getting even more deep, starting with something like `a ? b : c ? d : e`:
1. A first round of fixing would bring it to: `if (a) { b; } else { c ? d : e }`
2. Second round: `if (a) { b; } else if (c) { d; } else { e; }`

**Comment by mdjermanovic** [comment]
> `a ? b : c` is really _three_ rule violations rolled into one.

In this particular example, I think it's more likely that this is only one error in the code: missing usage of the value to which the ternary evaluates (e.g., the code should have been `x = a ? b : c` or `f(a ? b : c)`),  in which case the autofix to if-else would get the code even farther from the original intent.

I think it would be safer not to assume the intent and offer a suggestion instead of autofixing the code, and only when the suggestion would not have further `no-unused-expressions` problems (e.g, `a ? b() : c()` as that looks like a possible intent to use a ternary instead of if-else).

**Comment by mdjermanovic** [comment]
@eslint/eslint-team thoughts about this?

**Comment by JoshuaKGoldberg** [comment]
I'm happy with that proposal!

**Comment by nzakas** [comment]
I agree with @mdjermanovic -- if we do anything, adding suggestions is a safer choice than autofixing.

I do question, though, how helpful such suggestions will actually be. As already pointed out, this is one of those situations where the intent is really difficult to discern from the code causing the violation. For me, suggestions only make sense when there's a high probability of being a correct choice. In this case, I think it's unlikely that `a ? b : c` is actually mean to be `if (a) { b } else { c }`, which means it's more likely that it's along the lines of what @mdjermanovic, either `let val = a ? b : c` or `f(a ? b : c)`, and both of those suggestions would require adding an identifier that can't possibly be known by the rule.

So overall, I just don't see the value in having suggestions for this rule. At least, I don't see it in the discussion so far.

**Comment by JoshuaKGoldberg** [comment]
The context behind my posting it is that I'd overhauled the ESLint config for a large existing project to newly enable `no-unused-expression`. They had a lot of code like this:

```js
firstLogicalCondition && secondLogicalCondition
  ? trueBranchLogic()
  : falseBranchLogic();
```

...and more complicated variants of that.

It was a real pain to manually go through all every violation and fix them up. Even a suggestion fixer would have saved me many many minutes.

**Comment by nzakas** [comment]
That's interesting. I guess I'm having trouble understanding how an incorrect suggestion or incomplete suggestion would have helped your experience. Can you explain more? Maybe give an example of what you refactored to and what your expectation would have been about the suggestion you'd receive?

**Comment by JoshuaKGoldberg** [comment]
Here's a commit showing changes that _would_ have applied in https://github.com/vitejs/vite/pull/17624/ had I not reverted them and disabled the rule in the ESLint config: https://github.com/JoshuaKGoldberg/vite/commit/2af1a13c456deb0ce0fb9e0030312635de7f93fd

We can see there that many of them were on the lines of https://github.com/JoshuaKGoldberg/vite/commit/2af1a13c456deb0ce0fb9e0030312635de7f93fd#diff-ab75c34fa418085884af97e74c9166830b9f0a3456f9d3336e0c075d6ae9b05aR287:

```diff
-        isDebug &&
+        if (isDebug) {
          console.log(
            `[@vitejs/plugin-legacy] modern polyfills:`,
            modernPolyfills,
          )
+        }
```

Nothing a human can't do. But when the project has dozens of very straightforward `&&` -> `if` conversions like that, it'd be much faster to enable the rule with an auto-fixer, or failing that suggestion prompts.

Is that what you're looking for?

**Comment by nzakas** [comment]
Hmm okay. As already discussed, we aren't doing an autofixer for this rule, so I don't think the user experience you're looking for is achievable with this rule. I'd say in this case, you're better off using something like Babel or another AST mutation tool to just go through and make changes the way you want them to be made. That's really a much better approach to large, one-time codebase changes.

Your example here isn't using a ternary, so I think it's more likely that suggesting switching to an `if` statement makes sense, especially when the right side is a call expression (if the right side is not a call expression, then I think it's less likely that the intent was an `if` statement and more likely it was meant to be an assignment).
