### ISSUE TITLE
Bug: fetch and others  are showing no-undef 

### ISSUE THREAD

**Issue by AlvesJorge** [eslint/eslint#18675]
### Environment

Node version: 20.12.2
npm version: 10.5.0
Local ESLint version: 9.6.0
Global ESLint version: 9.6.0
Operating System: MacOS Sonoma 14.5 (darwin 23.5.0)

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
import globals from "globals";
import pluginJs from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";

export default [
  stylistic.configs["recommended-flat"],
  pluginJs.configs.recommended,
  { "files": ["**/*.{js,mjs,cjs}"] },
  {
    "plugins": {
      "@stylistic": stylistic
    },
    "languageOptions": {
      "globals": {
        ...globals.node,
        ...globals.jest
      }
    },
    "rules": {
      "@stylistic/indent": ["error", 2, { "SwitchCase": 1 }],
      "@stylistic/linebreak-style": ["error", "unix"],
      "@stylistic/quotes": ["error", "double"],
      "@stylistic/quote-props": "off",
      "@stylistic/comma-dangle": "off",
      "@stylistic/semi": ["error", "always"],
      "@stylistic/arrow-parens": ["error", "always"],
      "@stylistic/brace-style": ["error", "1tbs", { "allowSingleLine": true }],
      "@stylistic/function-call-argument-newline": ["error", "never"],
    },
  },
];

```
</details>

You can also check out the example [linked here](https://github.com/eslint/eslint/issues/15941#issuecomment-1140532099) where the user links a [ESLint Playground](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goJ2h0dHBzOi8vbm9kZWpzLm9yZy9hcGkvZG9jdW1lbnRhdGlvbi5qc29uJyk7XG5cbmlmIChyZXMub2spIHtcbiAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCk7XG4gIGNvbnNvbGUubG9nKGRhdGEpO1xufVxuXG5zb21lX3VuZGVmX3ZhcjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXVuZGVmIjoyfSwiZW52Ijp7Im5vZGUiOnRydWV9fX0=)and reports how `fetch` is not throwing any errors on the version at the time, and the OOP reports how upgrading at the time fixed the issue.

You can see that now in that playground `fetch` is throwing `no-undef`. Same is happening locally to me with the config and environment I mention above, and not just for `fetch` but also for `AbortSignal` and probably for other classically browser variables.

### What did you expect to happen?

Fetch is part of the global variables in Node since Node 18.

### What actually happened?

Fetch should be part of the node variables.

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goJ2h0dHBzOi8vbm9kZWpzLm9yZy9hcGkvZG9jdW1lbnRhdGlvbi5qc29uJyk7XG5cbmlmIChyZXMub2spIHtcbiAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCk7XG4gIGNvbnNvbGUubG9nKGRhdGEpO1xufVxuXG5zb21lX3VuZGVmX3ZhcjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXVuZGVmIjoyfSwiZW52Ijp7Im5vZGUiOnRydWV9fX0=

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AlvesJorge** [comment]
Apologies for the misleading demo!
Locally my globals version is as follows:
```
├─┬ eslint@9.6.0
│ └─┬ @eslint/eslintrc@3.1.0
│   └── globals@14.0.0
```

**Comment by fasttime** [comment]
> Locally my globals version is as follows:
> 
> ```
> ├─┬ eslint@9.6.0
> │ └─┬ @eslint/eslintrc@3.1.0
> │   └── globals@14.0.0
> ```
> 
> This is the version that `"eslint": "^9.4.0"` resolves to. Would this globals version not include `fetch`? Shouldn't the latest eslint major version require the most recent major version of `globals` ? :)

`@eslint/eslintrc` is used to provide legacy features in ESLint (I think that `@eslint/eslintrc` leverages `globals` to support [environments](https://eslint.org/docs/latest/use/configure/language-options-deprecated#specifying-environments)) in the legacy configuration system.

By default, ESLint 9 will only recognize globals that are part of the JavaScript specification. This does not include globals defined by web APIs and other technologies such as `fetch`. These globals have to be specified explicitly via a configuration file or a config comment like `/* global fetch */`. This is covered in detail by the [related documentation](https://eslint.org/docs/latest/use/configure/language-options#specifying-globals).
