### ISSUE TITLE
Rule Change: Implement auto-fix for "no-duplicate-imports"

### ISSUE THREAD

**Issue by fdc-viktor-luft** [eslint/eslint#18690]
### What rule do you want to change?

no-duplicate-imports

### What change do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
import { computed } from "vue";
import { ref } from "vue";
```

### What does the rule currently do for this code?

Shows an error for the whole second line.

### What will the rule do after it's changed?

The same but merges both lines with the autofix to:

```ts
import { computed, ref } from "vue";
```

### Participation

- [X] I am willing to submit a pull request to implement this change.

### Additional comments

This is the only reason why I'm still using the `eslint-plugin-import` with the `import/no-duplicates` rule.

**Comment by mdjermanovic** [comment]
Hi @fdc-viktor-luft, thanks for the issue!

This was already discussed in https://github.com/eslint/eslint/issues/14919 and the conclusion was that this rule shouldn't be autofixable.
