### ISSUE TITLE
Change Request: Update release infrastructure to support previous versions

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#18691]
### ESLint version

v9.7.0

### What problem do you want to solve?

Our ESLint release infrastructure currently does not fully support publishing new versions of the previous major line (v8.x at the moment). We made minimal changes to be able to release v8.57.0 while in the v9 prerelease phase, but not everything would work well now that we have released v9.0.0 final.   

### What do you think is the correct solution?

Update the following. I'll use v8 and v9 as a reference for simplicity, the changes would apply to any future versions of course.

- `eslint-release` https://github.com/eslint/eslint-release/pull/62
  - [x] Should correctly calculate the changelog and consequently the version that's going to be released. The current logic is based on the assumption that all version tags point to the history of the branch it's working on. This logic worked for v8.57.0 by chance rather than by design when we were still in the v9 prerelease phase but needs to be updated now.
  - [x] Should not publish a new v8.x to npm with the `latest` tag when v9.0.0 final is already released. It should be either a new tag (e.g., `maintenance` as proposed in https://github.com/eslint/eslint/issues/18621#issuecomment-2214549271) or no tag.
  - [x] Should ensure that the GitHub release for a new v8.x is not marked as `Latest` when v9.0.0 final is already released.
- `Makefile.js` https://github.com/eslint/eslint/pull/18870 and https://github.com/eslint/eslint/pull/18871
  - [x] Should update the right branch for the docs site - a new version of v8.x should update the `v8.x` branch, not the `latest` branch when v9.0.0 final is already released. 
  - [x] Should update `docs/src/_data/versions.json` on the `main` branch.
  - [x] Should also update `CHANGELOG.md` on the `main` branch.
- Jenkins jobs
  - `eslint Release`
    - [x] Rename `v8.x` to `v8.x-dev` in `RELEASE_BRANCH` list.
    - [x] Add `maintenance` to `RELEASE_TYPE` list.
  - `eslint-js Release`
    - [x] Rename `v8.x` to `v8.x-dev` in `RELEASE_BRANCH` list.
    - [x] Add `maintenance.patch` and `maintenance.minor` to `RELEASE_TYPE` list.
    - [x] Update script to handle new release types.

(this is an initial list, they may be more tasks)

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Seems like we should also discuss branches.

While we were in the v9 prerelease phase, we used the `v8.x` branch for development. The corresponding docs site branch was `latest`, because v8 was still the latest.

When we released the final v9.0.0, `v8.x` branch became the branch for v8 docs, and now all changes to this branch are live on https://eslint.org/docs/v8.x/. Now, if we'd like to add to v8.x line some bug fix or a feature that includes a docs update, that docs update shouldn't be live until we release a new version, so it looks like we need a new branch for v8 development (e.g., `v8.x-maintenance` )?

**Comment by nzakas** [comment]
Good point. Maybe just `v8.x-dev` or `v8.x-head` to keep it shorter?

**Comment by mdjermanovic** [comment]
`v8.x-dev` sounds good to me.

**Comment by nzakas** [comment]
@mdjermanovic is anything else blocking this work? We're continuing to get people complaining about https://github.com/eslint/eslint/issues/18723 (i.e., https://github.com/eslint/rewrite/issues/116), so I think it would be good if we get an updated v8.x release out soonish.

**Comment by mdjermanovic** [comment]
I'll start working on this now.

**Comment by mdjermanovic** [comment]
I created `v8.x-dev` branch and updated the Branch name pattern to `v*.x-dev` in the Branch protection rule.

**Comment by mdjermanovic** [comment]
All tasks are done, so closing.
