### ISSUE TITLE
Change Request: Support alternate AST location information for language plugins

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#18695]
### ESLint version

HEAD

### What problem do you want to solve?

Right now, language plugins require that each node in the AST have:

1. `loc`
2. `range`

This information is used primarily for reporting the location of problems inside of files and for applying fixes to the source text.

However, there is a large ecosystem of existing AST utilities that already exist and represent location information in different ways. For example:

* [unist](https://github.com/syntax-tree/unist) represents both range and line/columns as [`position`](https://github.com/syntax-tree/unist?tab=readme-ov-file#position)
* [postcss](https://github.com/postcss/postcss) represents both range and line/column numbers as [`source`](https://postcss.org/api/#source)

In order for language plugins to use these ASTs presently, we'd need to either ask the packages to modify their output or we'd need to manually go through each AST to add the necessary properties. Both of these are nontrivial approaches to solving this problem.

### What do you think is the correct solution?

Define two additional methods on the `SourceCode` interface:

1. `getRange(nodeOrToken)` - returns the range of a node or token
2. `getLoc(nodeOrToken)` - returns a `loc` value for a node or token

Then, update the core to use this methods instead of directly accessing `.loc` and `.range`.

Doing so would allow us to use any AST that provides line/column and offset information in language plugins.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Makes sense to me 👍

**Comment by mdjermanovic** [comment]
@nzakas is there any work left on this or can we close it now?

**Comment by nzakas** [comment]
Oops, yes, this is complete.
