### ISSUE TITLE
Docs: Incorrect alignment of Searchinput's clear icon

### ISSUE THREAD

**Issue by snitin315** [eslint/eslint#18702]
### Docs page(s)

All

### What documentation issue do you want to solve?

Searchinput's clear icon alignment is off.

<img width="375" alt="Screenshot 2024-07-19 at 3 38 10 PM" src="https://github.com/user-attachments/assets/1489292d-1ae9-447e-8c4a-a4085b96ce6b">

### What do you think is the correct solution?

The clear icon should be in middle of the input.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Go for it. :+1:

**Comment by amareshsm** [comment]
This issue was already addressed in https://github.com/eslint/eslint/pull/18682.
