### ISSUE TITLE
Bug: Inconsistent behavior for `ignores: ["/"]`

### ISSUE THREAD

**Issue by latin-1** [eslint/eslint#18706]
### Environment

Node version: v22.5.1
npm version: v10.8.2
Local ESLint version: v9.7.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 6.9.9-zen1-1-zen

### What parser are you using?

Default (Espree)

### What did you do?

<details open>
<summary>Configuration</summary>

```
export default [
  { ignores: ["/"] },
  { rules: { "no-console": "error" } },
];
```
</details>

```js
// file.js
console.log();
```

```js
// subdir/file.js
console.log();
```

### What did you expect to happen?

Either both or none of the two files are ignored.

### What actually happened?

Only `file.js` is ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/eslint-ignores-root-dir?file=eslint.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

https://github.com/eslint/rewrite/blob/20ba992f0eac1af2d6e29b30a5b6612d4f552210/packages/config-array/src/config-array.js#L1038

`isDirectoryIgnored` does not check whether `directoryPath` is an empty string before splitting.

- For input `""`, it checks `"/"`
- For input `"foo"`, it checks `"foo/"`
- For input `"foo/bar"`, it checks `"foo/"` and `"foo/bar/"`

**Comment by mdjermanovic** [comment]
Thanks for the issue! I can also reproduce this.

> Either both or none of the two files are ignored.

Paths in `ignores` should be relative, so `/` should have no effect, and thus none of the two files should be ignored.



> https://github.com/eslint/rewrite/blob/20ba992f0eac1af2d6e29b30a5b6612d4f552210/packages/config-array/src/config-array.js#L1038
> 
> `isDirectoryIgnored` does not check whether `directoryPath` is an empty string before splitting.
> 
> * For input `""`, it checks `"/"`
> * For input `"foo"`, it checks `"foo/"`
> * For input `"foo/bar"`, it checks `"foo/"` and `"foo/bar/"`

Indeed, this is likely the culprit. I'm working on the fix.
