### ISSUE TITLE
Bug: Clean search bar button displaying

### ISSUE THREAD

**Issue by PatrykKuniczak** [eslint/eslint#18717]
### Environment

Operating System: Windows 11
Chrome: 126.0.6478.185

### What parser are you using?

Default (Espree)

### What did you do?

I was using it properly

### What did you expect to happen?

Display on the center vertically

### What actually happened?

Didn't displayed properly

![image](https://github.com/user-attachments/assets/bef5c5e3-3371-4b3f-bbc2-dfae7c803e8a)

### Link to Minimal Reproducible Example

https://eslint.org/docs/latest/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Tanujkanti4441** [comment]
Hi @PatrykKuniczak, thanks for the issue, but this bug is fixed in PR #18682, you can see the change on HEAD branch

![Screenshot 2024-07-26 140033](https://github.com/user-attachments/assets/4ea6c21c-b57b-4c96-8586-69450dea654a)

and will also be shown in the next version.

**Comment by PatrykKuniczak** [comment]
@Tanujkanti4441 OO, i was searching, but i didn't found it. Thanks for quick response 😄
