### ISSUE TITLE
Change Request: Defer scope analysis until it's needed

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18714]
### ESLint version

9.7.0

### What problem do you want to solve?

Right now, ESLint will always create a scope manager and run its `.analyze()` for all files being parsed for linting. This is fine for most projects that enable many rules, as a lot of recommended rulesets -including ESLint core's and typescript-eslint's- enable rules that use scope analysis.

But: if the user's config doesn't enable any of those rules, the scope analysis work is done for nothing. That's extra time that slows down the lint run.

For more context, see:

* https://github.com/typescript-eslint/typescript-eslint/issues/9575
* https://github.com/typescript-eslint/typescript-eslint/issues/9575#issuecomment-2248255834

### What do you think is the correct solution?

Can we, say, change the `scopeManager` property as used inside ESLint to be a computed getter wherever it's accessed?

```diff
const parseResult = parse(...);

- const scopeManager = new ScopeManager(...);
+ let scopeManager;

return {
  // ...
- scopeManager,
+  get scopeManager() {
+    return (scopeManager ??= new ScopeManager(...));
+ }
} 
```

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I ran a performance comparison on a sample repository that doesn't enable any rules using scope analysis: https://github.com/JoshuaKGoldberg/repros/compare/eslint-deferred-scope-analysis. 

> | Lint Form       | Baseline | Deferred | Improvement |
> | --------------- | -------- | -------- | ----------- |
> | **Traditional** | 738.5 ms | 681.0 ms | **~7.7%**   |
> | **Typed**       | 2.006 s  | 1.322 s  | **~34%**    |
> 
> These results show noticeable improvements for projects that:
> 
> 1. Don't utilize scope analysis in any enabled lint rules
> 2. Use a parser such as `@typescript-eslint/parser` with longer scope analysis times

https://github.com/JoshuaKGoldberg/repros/compare/eslint-deferred-scope-analysis/patches includes the code changes that were needed for that comparison.

This should not be a breaking API change, as the API area of retrieving the scope manager still looks the same. This just proposes swapping a traditional property for a getter behind-the-scenes.

**Comment by nzakas** [comment]
While this is interesting, I feel like the amount of work necessary to implement this change won't result in any tangible benefit to end users. Because several rules in `eslint:recommended` make use of scopes, the likelihood that anyone will end up with a configuration that doesn't have any scope-dependent rules is pretty small.

Couple that with the complexity of trying to defer scope analysis until mid-traversal, and I just don't see this being worth the time or effort.

@eslint/eslint-team does anyone else have a different opinion?

**Comment by mdjermanovic** [comment]
I think it's a very rare case that an eslint configuration doesn't enable any rules that need scope analysis (`no-undef`, `no-unused-vars`...) so I agree with @nzakas that this doesn't seem worth the complexity of implementation.
