### ISSUE TITLE
Change Request: Add support for `reportUnusedDisableDirectivesSeverity` in legacy config file

### ISSUE THREAD

**Issue by StyleShit** [eslint/eslint#18710]
### ESLint version

v8.57.0

### What problem do you want to solve?

There is an option to pass `--report-unused-disable-directives-severity` from the CLI, but I don't see a way to use it in the config file.

Is it intentional? Because I can configure `reportUnusedDisableDirectives: true` in my config file and it works fine, so I would've assumed that `reportUnusedDisableDirectivesSeverity` should also be supported.

### What do you think is the correct solution?

Support using `reportUnusedDisableDirectivesSeverity` in the config file.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
This is already supported in the new config system: in your `eslint.config.js` file, you can set `linterOptions.reportUnusedDisableDirectives` to a severity level (e.g., `reportUnusedDisableDirectives: "error"`).

https://eslint.org/docs/latest/use/configure/configuration-files#reporting-unused-disable-directives

The old eslintrc config system is deprecated so we didn't make any changes for .eslintrc config files.
