### ISSUE TITLE
Not Compatible with the Latest version of eslint-config-airbnb

### ISSUE THREAD

**Issue by awaidqureshi** [eslint/eslint#18727]
### Environment

Node version: v20.12.0
npm version: 10.5.0
Local ESLint version: 9.8.0
Global ESLint version: 9.8.0
Operating System: Windows 10

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>
{
  "eslint": "^9.8.0",
  "eslint-config-airbnb": "^19.0.4"
}
```
<!-- Paste your configuration here -->
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

I expected npm install to complete successfully without any dependency conflicts.

### What actually happened?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: smart-react@1.0.33
npm ERR! Found: eslint@9.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.8.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.32.0 || ^8.2.0" from eslint-config-airbnb@19.0.4
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^19.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The eslint-config-airbnb version 19.0.4 does not seem to be compatible with eslint@9.x. This version conflict is blocking my ability to install dependencies and proceed with the project.

I would appreciate any guidance on how to resolve this issue or if there's a plan to update eslint-config-airbnb to support the latest eslint version.

**Comment by Tanujkanti4441** [comment]
Hi @awaidqureshi, thanks for the issue.

I can reproduce this error on installing `eslint-config-airbnb`, since right now airbnb plugin has following peerDeendencies

```json
"peerDependencies": {
    "eslint": "^7.32.0 || ^8.2.0"
  }
```

so only these versions of eslint will be compatible with `eslint-config-airbnb` plugin.
you can raise an issue in their [repository](https://github.com/airbnb/javascript) about this.

**Comment by awaidqureshi** [comment]
Thanks
