### ISSUE TITLE
Docs: (Incorrect yarn command for creating ESLint config in documentation)

### ISSUE THREAD

**Issue by topeogunleye** [eslint/eslint#18734]
### Docs page(s)

[Getting Started with ESLint](https://eslint.org/docs/latest/getting-started)

### What documentation issue do you want to solve?

The current documentation on the "Getting Started with ESLint" page lists the command `yarn create @eslint/config@latest` for creating an ESLint configuration. This command causes an error due to incorrect syntax when using the `@latest` tag.

### What do you think is the correct solution?

The correct command should be `yarn create @eslint/config` without the `@latest` tag. This prevents errors and ensures smooth execution of the command.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

| Command | Output |
|---------|--------|
| `yarn create @eslint/config@latest` |  ![image](https://github.com/user-attachments/assets/f4afaf56-4296-4dad-9484-fe963bc1968b)|
| `yarn create @eslint/config` | ![image](https://github.com/user-attachments/assets/f3d682bb-1852-43ec-9097-4d70f1c8ee7b)  |

Making this change will help users avoid unnecessary errors when setting up ESLint with yarn.

**Comment by amareshsm** [comment]
👍 Feel free to send a PR.

**Comment by topeogunleye** [comment]
> 👍 Feel free to send a PR.


Hi @amareshsm,

Thank you for your response. I'll go ahead and create the pull request.
