### ISSUE TITLE
Different linting behavior with `lintText` and `lintFiles` when using `{ fix: true, fixTypes: ["layout"] }` as options

### ISSUE THREAD

**Issue by dbaeumer** [eslint/eslint#18732]
### Environment

Node version: v20.13.1
npm version: v10.8.1
Local ESLint version: v9.8.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 6.6.36.3-microsoft-standard-WSL2

### What parser are you using?

Default (Espree)

### What did you do?

- clone https://github.com/dbaeumer/eslint-bug.git. The example is based on @VictorAugustoqwe example filed against the ESLint VS Code extension (see: https://github.com/microsoft/vscode-eslint/issues/1860). 
- cd eslint-bug
- npm install
- node ./repro.js

This lints the file fixError.js both with lintText and with lintFiles. Interestingly they produce different results. 

*lintText*
- errorCount is 0
- fixed the upper case comment rule 

*lintFiles*
- errorCount is 1
- upper case comment rule is not fixed.

### What did you expect to happen?

Both functions produce the same result.

### What actually happened?

See above

### Link to Minimal Reproducible Example

https://github.com/dbaeumer/eslint-bug.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Thanks. Indeed, it looks like `lintText()` isn't apply the `fixTypes` option and so is just applying all of the fixes.

We'd just need to copy the logic over from `lintFiles()`.
