### ISSUE TITLE
Change Request: Node 20.x Version Support

### ISSUE THREAD

**Issue by preflight** [eslint/eslint#18745]
### ESLint version

v8.57.0 / v9.8.0

### What problem do you want to solve?

I work for a large company where Node.js must be installed through a distributed package. New packages are released infrequently, so currently we are using Node 20.7 and likely won't get a new release until Node 22 is LTS.

Since ESLint 9 [requires](https://github.com/eslint/eslint/blob/main/package.json#L177) Node 20.9.0, we are unable to upgrade from ESLint 8.

Based on this [change request](https://github.com/eslint/eslint/issues/17595), it appears that Node 20.9 was chosen based on the latest 20.x version at that time and not based on any compatibility issues with earlier 20.x versions. The [logic cited](https://github.com/eslint/eslint/issues/17595#issuecomment-1789289743) for that decision is already outdated; new 20.x versions have been released, so 20.9 is no longer LTS.

### What do you think is the correct solution?

Please consider changing the `engines` requirement for Node.js to use major versions except where there are actual feature-compatibility requirements.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Sorry, I'm not clear on what it is that you're asking for. Are you asking for a change in a current release? Or asking that in the future we do something different?
