### ISSUE TITLE
Change Request: Enable Publish Attestation

### ISSUE THREAD

**Issue by elliot-huffman** [eslint/eslint#18764]
### ESLint version

9.8.0

### What problem do you want to solve?

ESLint currently doesn't publish attestation of the published package.
This increases risk of a supply chain attack.

### What do you think is the correct solution?

Enable NPM publish provenance to support attestation.
This is not a breaking change and is ignored by NPM clients that do not support the extra metadata added to the package.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

NPM Docs on provenance (attestation):
https://docs.npmjs.com/generating-provenance-statements

I would have made a PR to enable this functionality, but I do not see any direct `npm publish` command.
If someone can point me to the GitHub Actions workflow that does the NPM publish command, I can make the PR to reduce DevOps workload.

**Comment by aladdin-add** [comment]
> Set up automation with a supported CI/CD provider to publish your packages to the npm registry. The following providers are supported:
> 
> GitHub Actions. For more information, see "[Publishing packages with provenance via GitHub Actions](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions)."
> GitLab CI/CD. For more information, see "[Publishing packages with provenance via GitLab CI/CD](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-gitlab-cicd)."

per the npm docs, it's not possible as we are not using github actions to publish eslint. so closing.

**Comment by elliot-huffman** [comment]
I am willing to do all of the work to convert your entire DevOps pipeline compute stack to just GH Actions.
GH offers ~50K free action runner minutes every month for open source projects.

That should help simplify and centralize the project's compute. 
As well as unlock attestation capabilities for the release package.
