### ISSUE TITLE
Why do you recommand global install of eslint ?

### ISSUE THREAD

**Issue by MoOx** [eslint/eslint#1877]
Currently when you install eslint you get the -g warning

```console
$ npm i eslint
npm WARN prefer global eslint@0.15.0 should be installed with -g
```

In theory it can be convenient, but it's clearly not a good advice, especially when you work with different team on different projects. You are very likely to never have the latest version on each projects. Since a upgrade need some times (and eventually some code changes), it's clearly not an option to use a global install, and a local install is always better (btw, it's more convenient in practice to offer one command (npm i) that install all deps, without having to introduce a global dependency - like we avoid global var in javascript :D)

Would you be open to remove the `preferGlobal` option of the package.json ?

**Comment by nzakas** [comment]
It's there because traditionally CLIs have had been marked as `preferGlobal` to differentiate from modules that were only libraries. At least, that was the convention when ESLint was started and one that is still followed by other CLIs such as JSHint.

I personally don't care all that much. If it's not helpful, I'm fine with removing it.

**Comment by MoOx** [comment]
On top of that when you use npm scripts (which more and more people do), the node_modules bin are automatically added to path. So using `npm run something-that-call-a-local-bin` is working directly.

For my concern, I append `./node_modules/bin` in my path, so I automatically get local npm bin available (some people it can cause security issues (by overriding common bin like rm or something), but that only the case if you have it BEFORE other paths).

**Comment by nzakas** [comment]
Yup. The question is, is this confusing enough that you want it changed? Will it confuse others if we change it?

**Comment by MoOx** [comment]
It's more the sort of npm warning that annoys me. Not a big deal.

**Comment by nzakas** [comment]
I'll remove it.

**Comment by MoOx** [comment]
Great !
