### ISSUE TITLE
Bug: VSCode and ESLint CLI report differs

### ISSUE THREAD

**Issue by dalisoft** [eslint/eslint#18774]
### Environment

Node version: v22.6.0
npm version: 10.8.2
Local ESLint version: v9.9.0
Global ESLint version: -
Operating System: macOS Sonoma 14.6.1 (ARM)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

[Configuration](https://github.com/dalisoft/airlight/blob/master/eslint.config.mjs)

### What did you expect to happen?

Expecting same no issues report at VSCode

### What actually happened?

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4545dc39-2b7d-4939-9693-f1e6482dd152">

VSCode reports more issues but with CLI no issues

### Link to Minimal Reproducible Example

https://github.com/dalisoft/airlight/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
You'll need to report this at https://github.com/Microsoft/vscode-eslint
