### ISSUE TITLE
Change Request: Make flat config global ignore work with `name` key

### ISSUE THREAD

**Issue by stefanseeger** [eslint/eslint#18780]
### ESLint version

8.57.0

### What problem do you want to solve?

According tp the [Spec](https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores) a global ignore is when

`If ignores is used without any other keys in the configuration object, then the patterns act as global ignores.`

At the same  time we are having the `name` key to describe the rule.

It took me half a day to find out that my global ignore did not work because I used it with a name key

```json
{
  name: "global ignores",
  ignores: ["**/coverage/*", "**/build/*"]
}
```

The same error is existing in this project [eslint.config.js](https://github.com/eslint/eslint/blob/bf96855d7c181648cb0a0e8faf77d707ddd4725f/eslint.config.js#L81)

Also there is a [test fixture](https://github.com/eslint/eslint/blob/bf96855d7c181648cb0a0e8faf77d707ddd4725f/tests/fixtures/eslint.config-with-ignores3.js#L4) which is unused

I prepared a [Stackblitz](https://stackblitz.com/edit/node-twqdwr?file=eslint.config.mjs)
Run ``npm lint`` with and without the name and you can see that it leads to different results.

### What do you think is the correct solution?

Make it possible to have the `name` key together with the `ignores` and still handle it as global ignore

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for the issue @stefanseeger. Take note that the documentation for flat config in ESLint v8.x is at https://eslint.org/docs/v8.x/use/configure/configuration-files-new. The `name` property for config objects is not mentioned there yet.

A request to add support for the `name` property in global `ignores` configs in version 8 is being tracked at #18723.
