### ISSUE TITLE
Signature for token-related methods

### ISSUE THREAD

**Issue by jrvidal** [eslint/eslint#1878]
The documentation about token-related methods of the `context` object (`getTokens`, etc.) seems a little bit confusing to me. They work just fine when passing a `Token` as argument instead of an `ASTNode`. However that this usage is correct is not obvious from either the [docs](http://eslint.org/docs/developer-guide/working-with-rules.html) or the [JSDocs](https://github.com/eslint/eslint/blob/d49a4210ad711cc15c8f6cdb32a218e4b2ed9134/lib/token-store.js#L69-74).

Should we make this behaviour explicit?

**Comment by nzakas** [comment]
Yeah, all those methods actually work fine with any object that has location information. It's acceptable to pass in either a token or a node.

**Comment by btmills** [comment]
Since ba856e7 only touches the docs, should we also update the [JSDocs](https://github.com/eslint/eslint/blob/d49a4210ad711cc15c8f6cdb32a218e4b2ed9134/lib/token-store.js#L69-74) to use union types `{(ASTNode|Token)}`? I can put a PR together for that if needed.

**Comment by nzakas** [comment]
Sure!
