### ISSUE TITLE
no-unreachable.js - add if(false)

### ISSUE THREAD

**Issue by ptitgraig** [eslint/eslint#1879]
Hello.
This issue should be tagged as a question.

Do you think the following case would fit in the no-unreachable rule ? Could this case be added ?
`if (false) { // to stuff }`

**Comment by lo1tuma** [comment]
[no-constant-condition](http://eslint.org/docs/rules/no-constant-condition.html) would consider your example as a warning.

**Comment by ptitgraig** [comment]
Right. I missed that one. 
Thanks a lot.
