### ISSUE TITLE
Rule suggestion : Arguments name should be unique

### ISSUE THREAD

**Issue by ptitgraig** [eslint/eslint#1880]
Hello.

I'd like to get yout input about this rule from SonarQube. Would that be interesting to get this rule in ESLint ?

> Arguments name should be unique.
Function arguments should all have different names to prevent any ambiguity. Indeed, if arguments have the same name, the last duplicated argument hides all previous arguments with the same name (those previous arguments remain available through arguments[i], so they're not completely inaccessible. This hiding makes no sense, clearly reduces understandability and maintanability, and obviously can be error prone. Furthermore, in JavaScript strict mode, declaring arguments with the same name produces an error. 

Thanks.

**Comment by nzakas** [comment]
Sure, I'd call it `no-dupe-args` to go along with some of the other rules we have.

**Comment by michaelficarra** [comment]
If you enable strict node, this will be an early syntax error. The code would never even run. Is that not good enough?

**Comment by nzakas** [comment]
We already have rules for other strict mode things like duplicate keys (ES5) and `no-with`, so I think it makes sense to add this.

**Comment by xjamundx** [comment]
Should be super easy to add. I'll do it in a few days...
