### ISSUE TITLE
missing rule: disallow keywords

### ISSUE THREAD

**Issue by feross** [eslint/eslint#1881]
`jscs` has an option to disallow usage of certain keywords:

```json
{
  "disallowKeywords": ["with"]
}
```

http://catatron.com/node-jscs/rules/disallow-keywords/

**Comment by nzakas** [comment]
I don't see a good use case for such a general rule. What would it be used for outside of the `with` statement? (We already have `no-with`)

**Comment by feross** [comment]
Fair point. I agree – `with` is the primary target of such a rule. Closing.

**Comment by Raynos** [comment]
@nzakas A good use case for this is to ban `try` and `catch`. 

We disallow the `try` and `catch` keywords for the same performance issues as the performance issues with `with`.

**Comment by nzakas** [comment]
@Raynos - then you're not banning keywords, you're banning language features. I'd recommend you write a custom rule to do so.
