### ISSUE TITLE
Change Request: PR Template Checkboxes

### ISSUE THREAD

**Issue by Jay-Karia** [eslint/eslint#18810]
### ESLint version

v9.9.1

### What problem do you want to solve?

The PR template has the section "What is the purpose of this pull request? (put an "X" next to an item)" with multiple checkboxes.
The checkbox/s should be "ticked" after putting "x" ` [x] ... `, on preview it does not show tick!

### What do you think is the correct solution?

The template should be updated to add extra "-" before checkbox: ` - [ ] ... ` in order to see tick/s in the preview.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
it is intentional, to avoid it being rendered to a task.
