### ISSUE TITLE
missing rule: require spaces in for statement

### ISSUE THREAD

**Issue by feross** [eslint/eslint#1883]
http://jscs.info/rules.html#requireSpacesInForStatement

**Comment by nzakas** [comment]
Please do not open any more issues without proper descriptions. We are not going to simply copy every rule from JSCS.

**Comment by feross** [comment]
Apologies. I was under the impression from your comment here (https://github.com/eslint/eslint/issues/1621#issuecomment-68618426) that you want `eslint` to get to a point where people can drop `jscs` and just use `eslint`. In `standard`, there are only a few rules that we're still using `jscs` for, so the goal is very close.

I updated the description to be more specific, so if that's your only objection, can we re-open this?

**Comment by lo1tuma** [comment]
Seems like a duplicate of #1671.

**Comment by feross** [comment]
@lo1tuma yep, correct.
