### ISSUE TITLE
Feature request: ESLint Newsletter

### ISSUE THREAD

**Issue by Jay-Karia** [eslint/eslint#18833]
### ESLint version

N/A

### What problem do you want to solve?

To get updated with eslint and get latest news and updates in the inbox.

### What do you think is the correct solution?

Add a newsletter where users can submit their email and subscribe to it.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
I like the idea, but I don't know if anyone has time to do this. If someone would like to volunteer to put together a newsletter, we can definitely set it up.
