### ISSUE TITLE
Change Request: Change in settings file.

### ISSUE THREAD

**Issue by luas10c** [eslint/eslint#18844]
### ESLint version

9.9.1

### What problem do you want to solve?

Currently eslint has a configuration like this:

```js
import prettier from 'eslint-plugin-prettier'

const config = [
  ...
  {
    plugins: {
      prettier
    },
    rules: {
      'prettier/prettier': 'error'
    }
  }
  ...
]

export default config
```

### What do you think is the correct solution?

This makes the configuration file a bit more complex since it could follow the same path as other libs like jest that currently also support ESM.

Here is an example of how the jest configuration file works.
```js
/** @type{import('jest').Config} */
const config = {
  ...
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc/jest']
  }
  ...
}

export default config
```

The @swc/jest package is imported internally and there is no need to create complexity to import.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

In addition to standardizing this, it would make it easier to import plugins, parsers, and configurations.

**Comment by mdjermanovic** [comment]
> ```js
> /** @type{import('jest').Config} */
> const config = {
>   ...
>   transform: {
>     '^.+\\.(t|j)sx?$': ['@swc/jest']
>   }
>   ...
> }
> 
> export default config
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> The @swc/jest package is imported internally and there is no need to create complexity to import.

One of the main design goals for the new config system was to avoid importing declared plugins, configs and parsers internally as this caused a lot of problems for shareable configs in the old config system (https://github.com/eslint/eslint/issues/3458).

For more details, please see the RFC and the blog posts:

* https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification
* https://eslint.org/blog/2022/08/new-config-system-part-1/
* https://eslint.org/blog/2022/08/new-config-system-part-2/
