### ISSUE TITLE
Rule Change: add suggestions to `no-empty-pattern` rule

### ISSUE THREAD

**Issue by Tanujkanti4441** [eslint/eslint#18843]
### What rule do you want to change?

[no-empty-pattern](https://eslint.org/docs/latest/rules/no-empty-pattern)

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

Other

### Example code

```js
var {} = foo;
var [] = foo;
```

### What does the rule currently do for this code?

provide no suggestions.

### What will the rule do after it's changed?

rule will provide suggestions to remove the code.

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by mdjermanovic** [comment]
I'm not sure if a suggestion to remove the code in these cases would be very helpful because when there's an empty destructuring pattern, I think it's much more likely that a variable reference is missing in it or that the wrong syntax was used.

@eslint/eslint-team thoughts?

**Comment by nzakas** [comment]
I agree with @mdjermanovic. The most likely reason this occurred is that they were refactoring and just forgot to include a variable name. I don't think suggesting to remove the line makes sense.

**Comment by JoshuaKGoldberg** [comment]
Oh! I have a dissent here 🙂. I think there are two directions of refactoring that could be relevant here: _decreasing_ the number of destructured variables vs. _increasing_ them. It's pretty common when cleaning up code to remove unused identifiers/references. Having a suggestion to remove the line would be handy.

Additionally, consider the case of a function that used to take in options but no longer does ([playground link](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZW1wdHktcGF0dGVybjogXCJlcnJvclwiKi9cblxuZnVuY3Rpb24gZXhhbXBsZSh7fSkge1xuICAvLyAuLi5cbn0iLCJvcHRpb25zIjp7InJ1bGVzIjp7fSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19 "playground link of function example")):

```js
// previously: function example({ value }) {
function example({}) {
  // ...
}
```

I've come across this a lot when working with JSX components, such as in Solid and React. Switching components from taking in props to not is a pretty common refactor. It'd be handy to have a suggestion for specifically _function_ parameters to remove the `{}`.

**Comment by fasttime** [comment]
> Additionally, consider the case of a function that used to take in options but no longer does ([playground link](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tZW1wdHktcGF0dGVybjogXCJlcnJvclwiKi9cblxuZnVuY3Rpb24gZXhhbXBsZSh7fSkge1xuICAvLyAuLi5cbn0iLCJvcHRpb25zIjp7InJ1bGVzIjp7fSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)):
> 
> ```js
> // previously: function example({ value }) {
> function example({}) {
>   // ...
> }
> ```
> 
> I've come across this a lot when working with JSX components, such as in Solid and React. Switching components from taking in props to not is a pretty common refactor. It'd be handy to have a suggestion for specifically _function_ parameters to remove the `{}`.

This suggestions is covered by `no-unused-vars` in #18352. See for example:

https://github.com/eslint/eslint/blob/aeb06d8a19d837e73e5bd7a3eb4e4ab7285234b9/tests/lib/rules/no-unused-vars.js#L2101-L2105

It's on my to do list of things to review.

**Comment by JoshuaKGoldberg** [comment]
> This suggestions is covered by no-unused-vars in https://github.com/eslint/eslint/pull/18352. See for example:

That would cover removing `{ value }` in `function example({ value }) { }`, but not the `{}` in `function example({}) {}`, right? If so: I think that's in the same area of refactors, but separately useful and different.

**Comment by fasttime** [comment]
> That would cover removing `{ value }` in `function example({ value }) { }`, but not the `{}` in `function example({}) {}`, right?

Correct. There is no unused variable to report for `no-unused-vars` in `function example({}) {}` (assuming that `example` is called), hence no suggestion.
