### ISSUE TITLE
Rule Change: Support Yoda conditions for null and undefined

### ISSUE THREAD

**Issue by hsvikum** [eslint/eslint#18853]
### What rule do you want to change?

yoda

### What change do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new default behavior

### Example code

```
let x = 1;
if (x === undefined) {
  console.log('unset');
}

if (x === null) {
  console.log('unset');
}
```

### What does the rule currently do for this code?

```
let x = 1;
if (x === undefined) {
  console.log('unset');
}

if (x === null) {
  console.log('unset');
}
```

### What will the rule do after it's changed?

```
let x = 1;
if (undefined === x) {
  console.log('unset');
}

if (null === x) {
  console.log('unset');
}
```

### Participation

- [x] I am willing to submit a pull request to implement this change.

**Comment by Tanujkanti4441** [comment]
Hi @hsvikum, thanks for the issue. 

But `yoda` rule is already fixable.

you can see here => [playground](https://eslint.org/play/#eyJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsic291cmNlVHlwZSI6Im1vZHVsZSJ9fSwidGV4dCI6Ii8qZXNsaW50IHlvZGE6IFtcImVycm9yXCIsIFwiYWx3YXlzXCJdKi9cblxuaWYgKGNvbG9yID09IFwiYmx1ZVwiKSB7XG4gICAgLy8gLi4uXG59XG5cbmlmIChjb2xvciA9PSBgYmx1ZWApIHtcbiAgICAvLyAuLi5cbn0ifQ==)

and also rule already supports `null` condition. [playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgeW9kYTogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0qL1xuXG5pZiAoeCA9PT0gbnVsbCkge1xuICBjb25zb2xlLmxvZygndW5zZXQnKTtcbn0iLCJvcHRpb25zIjp7InJ1bGVzIjp7fSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)

but it does not support `undefined` condition right now, it think rule should support this.

@eslint/eslint-team, should we go for this>

**Comment by mdjermanovic** [comment]
Stylistic rules are frozen for new features so we shouldn't make any changes unless this is considered a bug.

Per the [documentation](https://eslint.org/docs/latest/rules/yoda), this rule only checks comparisons with literals. `undefined` is technically not a literal, so this doesn't seem like a bug to me.

**Comment by hsvikum** [comment]
Thank you for the reply @mdjermanovic @mdjermanovic . I confirmed that the `null` is working. Sorry for the confusion caused.

@mdjermanovic in that case should it make sense to make the `undefined` behave the same as `null` for consistency. 
I assume null is also not a literal value. 

What do you think.

**Comment by hsvikum** [comment]
Reopening as I marked the issue completed by mistake.

**Comment by hsvikum** [comment]
Marked as completed by mistake. @mdjermanovic @Tanujkanti4441 feel free to reopen the issue.

**Comment by mdjermanovic** [comment]
`null` is a literal, `undefined` is an identifier.

**Comment by mdjermanovic** [comment]
> Marked as completed by mistake

Reopening.

**Comment by hsvikum** [comment]
@mdjermanovic the reasoning behind your comment make sense to me now.

**Comment by nzakas** [comment]
It seems there's consensus that this isn't a bug, so closing.
