### ISSUE TITLE
Bug: Eslint is outputting ruleId and nodeType as null when using custom formatter

### ISSUE THREAD

**Issue by haylch** [eslint/eslint#18856]
### Environment

Node version: v20.17.0
npm version: v10.8.2
Local ESLint version: Not found
Global ESLint version: v9.9.1
Operating System: linux 5.15.0-119-generic

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
eslint.config.js:

module.exports = {
        rules: {
			"no-unused-vars": "warn",
			"no-undef": "error"
        }
};

custom_formatter.js:

module.exports = function(results, context) {
    var summary = {issues: []};
    results.forEach(function(result) {
        result.messages.forEach(function(msg) {
		console.log(msg)
        });
    });
    //console.log(summary)
    return JSON.stringify(summary);
}

package,json:

{
  "name": "test-javascript-project",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```
</details>

```js
<!-- Paste your code here -->
app.js

const http = require('http');
const port = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  const msg = 'Hello Node!\n'
  res.end(msg);

  var a = 0;
  var a = 1;
});

server.listen(port, () => {
  console.log(`Server running on http://localhost:${port}/`);
});
```

### What did you expect to happen?

eslint should not output ruleId and nodeType as null in the msg object in custom_formatter.js

### What actually happened?

When I run the following command
eslint --config eslint.config.js --format ./custom_formatter.js --output-file eslint-report.json ./src

The console.log(msg) in custom_formatter.js will print the following output:
{
  ruleId: null,
  nodeType: null,
  fatal: true,
  severity: 2,
  message: "Parsing error: Identifier 'a' has already been declared",
  line: 11,
  column: 9
}

### Link to Minimal Reproducible Example

N.A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
This works as intended. In case the lint message was not produced by a rule (e.g., if it's a parsing error, like in your example), `ruleId` is set to `null`. Similar for `nodeType` - if the message is not related to a particular AST node, `nodeType` is set to `null`. I'll submit a PR to update the custom formatters docs with these details.
