### ISSUE TITLE
Docs: Documentation Redesign

### ISSUE THREAD

**Issue by Jay-Karia** [eslint/eslint#18868]
### Docs page(s)

https://eslint.org

### What documentation issue do you want to solve?

Current docs lack the clean and modern UI.
It would be better to redesign / rewrite the docs

My personal development experience using 11ty (current site generator) is slow, and the time taken for hot reload is significantly high.
This has a great impact when adding new changes

### What do you think is the correct solution?

We can rewrite the docs in another static site generator ([Nextra](https://nextra.site/)).
Uses Next.js as a core framework.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

I am open for discussion about this, please let me know your thoughts.

**Comment by Tanujkanti4441** [comment]
I am not sure about this change, rewriting code with other site generator means we have to write the logic again.

Also 11ty official site provides following data about build.



![Image](https://github.com/user-attachments/assets/a37529fd-4100-4ce4-acfe-6e2c810e6a53)

so clearly nextjs will take longer to built than 11ty.

curious to know what other says, @eslint/eslint-team.

**Comment by nzakas** [comment]
No, we are not redesigning or rewriting the docs site.

**Comment by Jay-Karia** [comment]
It literally takes over a minute for a hot reload !! 😶
![Image](https://github.com/user-attachments/assets/12ef743b-1894-4c36-9ba6-6967d8f266df)
