### ISSUE TITLE
Rule Change: Allow certain whitespace characters when using no-irregular-whitespace

### ISSUE THREAD

**Issue by Svish** [eslint/eslint#18862]
### What rule do you want to change?

no-irregular-whitespace

### What change do you want to make?

Generate fewer warnings

### How do you think the change should be implemented?

A new option

### Example code

const percent = 20;
const text = `${percent} %`;

### What does the rule currently do for this code?

The rule currently disallows the non-breaking whitespace character, `\u00A0`, which is very handy to use in formatting strings and such to prevent certain strings from breaking incorrectly, for example between a number and its unit as shown in the example code.

### What will the rule do after it's changed?

It would be great if I could add an option array called `allowedCharacters` (or something along those lines), where you can add whitespace characters this rule disallows that you explicitly want to allow.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by Svish** [comment]
Many of the whitespace characters the rule currently disallows I would also like to disallow, but when I just want to disallow _most_ of them, but not all, then I cannot currently use this rule. So having an option to allow a small subset, and have the rule disallow the rest, would be great. 👍

**Comment by mdjermanovic** [comment]
An option to allow certain characters was discussed in https://github.com/eslint/eslint/issues/11781, but it wasn't accepted.

Can you use the existing option [`skipTemplates`](https://eslint.org/docs/latest/rules/no-irregular-whitespace#skiptemplates) for your use case? Here's a [Playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8taXJyZWd1bGFyLXdoaXRlc3BhY2U6IFtcImVycm9yXCIsIHsgXCJza2lwVGVtcGxhdGVzXCI6IHRydWUgfV0qL1xuXG5jb25zdCBwZXJjZW50ID0gMjA7XG5jb25zdCB0ZXh0ID0gYCR7cGVyY2VudH3CoCVgO1xuIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==) with the code example from the original post.

**Comment by Svish** [comment]
> An option to allow certain characters was discussed in [#11781](https://github.com/eslint/eslint/issues/11781), but it wasn't accepted.
> 
> Can you use the existing option [`skipTemplates`](https://eslint.org/docs/latest/rules/no-irregular-whitespace#skiptemplates) for your use case? Here's a [Playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8taXJyZWd1bGFyLXdoaXRlc3BhY2U6IFtcImVycm9yXCIsIHsgXCJza2lwVGVtcGxhdGVzXCI6IHRydWUgfV0qL1xuXG5jb25zdCBwZXJjZW50ID0gMjA7XG5jb25zdCB0ZXh0ID0gYCR7cGVyY2VudH3CoCVgO1xuIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==) with the code example from the original post.

I saw that option, but wouldn't that allow _all_ whitespace characters in template strings? Not just the non-breaking space character?

**Comment by mdjermanovic** [comment]
Yes, that would allow all characters in template literals.

**Comment by Svish** [comment]
Yeah, I don't want that, I just want to allow a very small subset and disallow all the others.

**Comment by mdjermanovic** [comment]
Sorry for the delay. I believe the primary purpose of this rule is to disallow all irregular whitespace in code outside comments and literals (string, template, regex, JSX), so I don't think there should be an option to allow some of those characters everywhere. However, I wouldn't be opposed to adding an option that allows only some of those characters in comments and literals while still disallowing the others everywhere. We would just have to think about how this option would correlate with existing options that allow all characters (`skipStrings`, `skipComments`, `skipRegExps`, `skipTemplates`, and `skipJSXText`).

@eslint/eslint-team thoughts?

**Comment by Svish** [comment]
Yeah,sorry, I'm only talking about string literals, template strings, and such.

Irregular whitespace in the code in general, would be very weird. So weird in fact that I assumed that strings and such already was the main focus of this rule.

Maybe for example skipStrings and so on could allow an array of characters to skip for those. So `skipStrings: true` would skip all checking of strings, but `skipStrings: [...]` would only skip the characters listed in thr array, and still fail on others.

**Comment by nzakas** [comment]
The intent of this rule is to prevent the unknowing use of irregular white space in a file, primarily because they are invisible and wouldn't otherwise be noticeable.

I'm not sure I understand the use case here. Is there a reason you don't just use the escape sequence directly in the template? I'd think you'd want to clearly indicate the use of `\u00A0`, and the best way to do that is to use the escape sequence. Otherwise, someone else might come along and not realize there's a special character there instead of a regular space.

**Comment by sam3k** [comment]
Per TSC meeting on 10.03.24, we've decided that this is too much of an edge case for us to provide support at this time. Therefore, we will be closing this issue.
