### ISSUE TITLE
eslint v8.57.1 release

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#18874]
What changes will we include in the v8.57.1 release?

* Changes related to the `name` field in config objects. PR:  https://github.com/eslint/eslint/pull/18875
  * Show config names in error messages: https://github.com/eslint/eslint/commit/3e9fcea3808af83bda1e610aa2d33fb92135b5de (fix in config array: https://github.com/humanwhocodes/config-array/commit/58f8c9f8c06cbc6c67dfefe71b719bc6a940b7b3).
  * Ignore `name` field for global ignores.
    * https://github.com/eslint/eslint/commit/a129acba0bd2d44480b56fd96c3d5444e850ba5b (fix in config array: https://github.com/humanwhocodes/config-array/commit/286f48970f2b2c35c3fae14c5081d29ac23d11cc)    
    * https://github.com/eslint/eslint/commit/19f9a8926bd7888ab4a813ae323ad3c332fd5d5c (just the `@humanwhocodes/config-array` update part, to include additional fix in config-array: https://github.com/humanwhocodes/config-array/commit/3dabb4db2072a86d9b567205626ba0ed537bea2f)
* `--no-ignore` should not apply to non-global ignores: https://github.com/eslint/eslint/commit/09675e153169d4d0f4a85a95007dcd17d34d70c7 PR: https://github.com/eslint/eslint/pull/18875

Most of the above changes are just `@humanwhocodes/config-array` dependency updates, so we could bundle all in one commit.

Note: do not add "release" label to this issue because eslint bot uses it for scheduled releases.

**Comment by mdjermanovic** [comment]
@eslint/eslint-team are there any other critical bug fixes we should include?

Some candidates:

1. Provide helpful error message for nullish configs https://github.com/eslint/eslint/commit/03068f13c0e3e6b34b8ca63628cfc79dd256feac.
2. EMFILE errors: https://github.com/eslint/eslint/commit/0d8cf6350ce3dc417d6e23922e6d4ad03952aaaa and https://github.com/eslint/eslint/commit/37eba48d6f2d3c99c5ecf2fc3967e428a6051dbb
3. Do not crash on error in fs.walk filter: https://github.com/eslint/eslint/commit/594eb0e5c2b14a418d686c33d2d40fb439888b70
4. Skip processor code blocks that match only universal patterns: https://github.com/eslint/eslint/commit/f6534d14033e04f6c7c88a1f0c44a8077148ec6b

Note: We can't use `@eslint/config-array` because it supports only `"node": "^18.18.0 || ^20.9.0 || >=21.1.0"` whereas eslint v8 supports `"node": "^12.22.0 || ^14.17.0 || >=16.0.0"`.

**Comment by nzakas** [comment]
Those all look like good candidates for me. Are all the necessary changes already in the latest `@humanwhocodes/config-array`?

**Comment by mdjermanovic** [comment]
> Those all look like good candidates for me. Are all the necessary changes already in the latest `@humanwhocodes/config-array`?

Yes, sorry, I see that https://github.com/eslint/eslint/issues/18874#issuecomment-2337433674 wasn't clear. Those are candidates I believe we can port while keep using `@humanwhocodes/config-array`. There were other bug fixes, but for them we'd need `@eslint/config-array`.

**Comment by mdjermanovic** [comment]
> 2\. EMFILE errors: [0d8cf63](https://github.com/eslint/eslint/commit/0d8cf6350ce3dc417d6e23922e6d4ad03952aaaa) and [37eba48](https://github.com/eslint/eslint/commit/37eba48d6f2d3c99c5ecf2fc3967e428a6051dbb)

Actually, we can't backport this because `@humanwhocodes/retry` requires `"node": ">=18.18"`.

**Comment by fasttime** [comment]
I think it should be possible to backport these fixes as well:
* #18364
* #18552
* #18736

Thoughts on including those in the maintenance release? I could work on them.

**Comment by mdjermanovic** [comment]
> I think it should be possible to backport these fixes as well:
> 
> * [fix: do not throw when defining a global named __defineSetter__ #18364](https://github.com/eslint/eslint/pull/18364)
> * [fix: Don't lint same file multiple times #18552](https://github.com/eslint/eslint/pull/18552)
> * [fix: add logic to handle fixTypes in the lintText() #18736](https://github.com/eslint/eslint/pull/18736)
> 
> Thoughts on including those in the maintenance release? I could work on them.

Sounds good to me. @nzakas what do you think?

**Comment by nzakas** [comment]
Those all seem like good things to include. :+1:

**Comment by fasttime** [comment]
I opened PRs for v8.x: #18898, #18899, #18900.

**Comment by mdjermanovic** [comment]
ESLint v8.57.1 has been released:

https://eslint.org/blog/2024/09/eslint-v8.57.1-released/

We'll wait a few days to see if there is a need for a follow-up release.
