### ISSUE TITLE
Bug: no-unused-vars crashes in Flow libdefs with class declarations

### ISSUE THREAD

**Issue by reosarevok** [eslint/eslint#18876]
### Environment

Node version: v20.13.0
npm version: v10.5.2
Local ESLint version: v9.10.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 5.15.0-119-generic

### What parser are you using?

Other

### What did you do?

See minimal example at https://github.com/reosarevok/eslint-no-unused-vars-bug

### What did you expect to happen?

Trying eslint 9 (while upgrading from 8) on our flow-typed codebase (using `hermes-eslint`), I was expecting no new issues.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 9.10.0

TypeError: Cannot read properties of undefined (reading 'some')
Occurred while linting /home/reosarevok/musicbrainz-server/flow-typed/npm/jed_v1.x.x.js:1
Rule: "no-unused-vars"
    at collectUnusedVariables (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/rules/no-unused-vars.js:751:71)
    at collectUnusedVariables (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/rules/no-unused-vars.js:829:17)
    at Program:exit (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/rules/no-unused-vars.js:841:36)
    at ruleErrorHandler (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/linter.js:1083:48)
    at /home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/home/reosarevok/musicbrainz-server/node_modules/eslint/lib/linter/node-event-generator.js:348:14)

```

The issue was apparently added with https://github.com/eslint/eslint/commit/1c173dc1f3d36a28cb2543e93675c2fbdb6fa9f1 - changing https://github.com/eslint/eslint/pull/18170/files#diff-b8867bf68ff637ad5f72d604e0e920ffced618515a50a2047958904f837f83deR622 to `def.node.body.body?.some` gets rid of the issue, but it might have other consequences.

### Link to Minimal Reproducible Example

https://github.com/reosarevok/eslint-no-unused-vars-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Thanks for the issue @reosarevok. ESLint core rules are designed and testes to work with JavaScript code. It appears that the source code causing the error contains a `declare` keyword that is not valid JavaScript (maybe Flow?):

```js
  declare class Jed {
}
```

in https://github.com/reosarevok/eslint-no-unused-vars-bug/blob/c0aed2b259541e61d0940d5a878226532de14cc2/testflowdef.js.

And in fact the generated AST contains a `DeclareClass` node that is not found in ESTree: https://astexplorer.net/#/gist/8b8a49c3dca579e0aedab1024edb3b03/e867b08835ccf87470a76c9cdad2f3694ecf2f2c. 

Even if the `no-unused-vars` were patched not to crash in this case, there is no guarantee that it would work as expected with code that is not JavaScript, because ESLint built-in rules don't support nonstandard syntax. In these cases, we recommend forking the build-in rule to [create a custom rule](https://eslint.org/docs/latest/extend/custom-rule-tutorial), if nothing like that exists in another publicly available plugin.

**Comment by Tanujkanti4441** [comment]
@reosarevok, have you tried the `typescript-eslint` where this keyword belongs to, it seems working with typescript-eslint
here you can see => [stackblitz](https://stackblitz.com/edit/stackblitz-starters-khednv?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js,eslint.config.mjs&title=node.new%20Starter)

**Comment by reosarevok** [comment]
It's not typescript, it's flow - but if it works with a different parser then it suggests maybe this should be reported to `hermes-eslint` instead :)

**Comment by nzakas** [comment]
> It's not Typescript, it's Flow - but if it works with a different parser then it suggests maybe this should be reported to `hermes-eslint` instead :)

This is a good idea. To me, it looks like they have a custom scope manager that is treating the `declare class` like a normal class (which is expected to have `.body` as an array) when it should probably be identified differently. I'd say open an issue there, and we'll leave this open to see what the response is.

**Comment by reosarevok** [comment]
No reactions so far from hermes 🤷‍♂. We are just disabling the rule on the affected files for now, in any case.

**Comment by nzakas** [comment]
Okay, thanks for the update. Closing here as there's nothing for us to do.
