### ISSUE TITLE
Remove deprecated rule no-space-before-semi

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#1889]
The rule no-space-before-semi is deprecated and should be removed with ESLint 1.0.0.

**Comment by nzakas** [comment]
I think we should consolidate all these "remove rule" issues into one. What do you think?

**Comment by btmills** [comment]
:+1: It's easy to remove them all with a single commit, and they'll clutter the [v1.0.0](https://github.com/eslint/eslint/milestones/v1.0.0) milestone.

**Comment by lo1tuma** [comment]
Agreed :+1:

**Comment by nzakas** [comment]
Cool, can one of you do that, please? :)

**Comment by btmills** [comment]
Done: #1898

**Comment by nzakas** [comment]
Thanks. Closing in favor of #1898.
