### ISSUE TITLE
External: Mark @types/eslint as a stub types package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18928]
Following #18845 -> https://github.com/eslint/eslint/issues/18845#issuecomment-2325259204 -> #18854 -> https://github.com/eslint/rewrite/pull/106#discussion_r1769036084: now that ESLint publishes its own `.d.ts` TypeScript types, there are two packages consumers can pull ESLint from:

* [`eslint`](https://www.npmjs.com/package/eslint) itself: which is now the correct place
* [`@types/eslint`](https://www.npmjs.com/package/@types/eslint), as published by https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/eslint: which is now slightly outdated

Once a package publishes its own types, it's common practice for the DefinitelyTyped side to mark the the old `@types/` package as a "stub" (no-longer-necessary) package. From https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#removing-a-package:

> When a package [bundles](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) its own types, types should be removed from Definitely Typed to avoid confusion.
> 
> You can remove it by running `pnpm run not-needed <typingsPackageName> <asOfVersion> [<libraryName>]`.
> 
> - `<typingsPackageName>`: This is the name of the directory to delete.
> - `<asOfVersion>`: A stub will be published to `@types/<typingsPackageName>` with this version. Should be higher than any currently published version and should be a version of `<libraryName>` on npm.
> - `<libraryName>`: Name of npm package that replaces the Definitely Typed types. Usually this is identical to `<typingsPackageName>`, in which case you can omit it.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70012 is a good example of another package that was migrated to TypeScript. [`@types/react-datepicker`](https://www.npmjs.com/package/@types/react-datepicker) now has no `.d.ts` files in it. The package instead has an npm deprecation:

> This is a stub types definition. react-datepicker provides its own type definitions, so you do not need this installed.

Is there anything blocking an enterprising individual from sending a similar PR to DefinitelyTyped to deprecate `@types/eslint`?

**Comment by snitin315** [comment]
>Is there anything blocking an enterprising individual from sending a similar PR to DefinitelyTyped to deprecate @types/eslint?


I don't think so, I'll raise a PR in DefiniteltTyped for this.

**Comment by snitin315** [comment]
@JoshuaKGoldberg I've raised a PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735

**Comment by karlhorky** [comment]
Since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735 has been merged, what are the next steps here?

Does there need to be user migration guide written somewhere? (eg. a new ESLint official blog post or release notes?) Would be useful to have a recommended set of steps to follow.

Is migration just as easy as this?

1. Remove `@types/eslint` using your package manager of choice
2. Upgrade `eslint` to at least version `???` (not sure which version is required)

Or will there be breaking types changes as well?

**Comment by karlhorky** [comment]
@snitin315 now that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70735 has been merged, I guess the docs should be updated to not point at DefinitelyTyped anymore (broken link) - I opened a PR here:

- https://github.com/eslint/eslint/pull/19049

(maybe also other pages aside from the migration guide, didn't check those yet)

**Comment by snitin315** [comment]
I am marking this as resolved.

**Comment by kovsu** [comment]
`rgh-linkify-features`
