### ISSUE TITLE
Bug: eslint package's type-level dependencies aren't marked as dependencies

### ISSUE THREAD

**Issue by ashvinsrivatsa** [eslint/eslint#18936]
### Environment

Node version: v22.6.0
npm version: v10.8.3
Local ESLint version: v9.11.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

Consider a package initialized as follows:

```bash
npm init --yes
npm install eslint typescript
echo '{"compilerOptions":{"target":"es2016","module":"commonjs"}}' > tsconfig.json
echo 'import { ESLint } from "eslint"' > index.ts
npx tsc
```

### What did you expect to happen?

TypeScript compilation should succeed.

### What actually happened?

Compilation fails:

```
node_modules/eslint/lib/types/index.d.ts:28:25 - error TS2307: Cannot find module 'estree' or its corresponding type declarations.

28 import * as ESTree from "estree";
                           ~~~~~~~~

node_modules/eslint/lib/types/index.d.ts:29:26 - error TS2307: Cannot find module '@eslint/core' or its corresponding type declarations.

29 import { Language } from "@eslint/core";
                            ~~~~~~~~~~~~~~

node_modules/eslint/lib/types/index.d.ts:30:29 - error TS2307: Cannot find module 'json-schema' or its corresponding type declarations.

30 import { JSONSchema4 } from "json-schema";
                               ~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/eslint/lib/types/index.d.ts:28
```

ESLint has `devDependencies` on `@types/estree`, `@eslint/core`, and `@types/json-schema`, but not `dependencies`, so npm does not install those packages.

### Link to Minimal Reproducible Example

https://github.com/ashvinsrivatsa/eslint-woes

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I noticed this upon upgrade to eslint@9.11 because the `@eslint/core` compilation error was newly visible in one of my projects. The other two missing dependencies were masked by me having installed those packages as top-level dependencies.

Workarounds:
* Set `"skipLibCheck": true` in tsconfig.json. (Strongly dispreferred.)
* Manually install the missing packages as top-level dependencies of your own package.

**Comment by snitin315** [comment]
We need to mention `@types/estree`, `@eslint/core`, & `@types/json-schema` as optional peer dependencies and mention to install them [in the docs](https://eslint.org/docs/latest/use/configure/configuration-files#typescript-configuration-files) when using ESLint Node API.
