### ISSUE TITLE
Bug: ESLint is not working for angular 18 projects

### ISSUE THREAD

**Issue by b-mi** [eslint/eslint#18946]
### Environment

Node version:
20.11.1
npm version:
10.2.4

Local ESLint version:
Global ESLint version:
actual versions installed by npm

├── @typescript-eslint/eslint-plugin@8.7.0
├── @typescript-eslint/parser@8.7.0
├── angular-eslint@18.3.1
├── eslint@9.11.1

Operating System:
Windows 10

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

Various errors like this after trying many many configurations recommended from varius sources, because **ng add @angular-eslint/schematics** is not enough.

H:\Data\webclient\epc>npx eslint . --config eslint.config.js --fix

Oops! Something went wrong! :(

ESLint: 9.11.1

TypeError: Key "rules": Key "@angular-eslint/directive-selector": Could not find "directive-selector" in plugin "@angular-eslint".
    at throwRuleNotFoundError (H:\Data\webclient\epc\node_modules\eslint\lib\config\rule-validator.js:66:11)
    at RuleValidator.validate (H:\Data\webclient\epc\node_modules\eslint\lib\config\rule-validator.js:147:17)
    at new Config (H:\Data\webclient\epc\node_modules\eslint\lib\config\config.js:240:27)
    at [finalizeConfig] (H:\Data\webclient\epc\node_modules\eslint\lib\config\flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (H:\Data\webclient\epc\node_modules\@eslint\config-array\dist\cjs\index.cjs:1102:55)
    at FlatConfigArray.getConfig (H:\Data\webclient\epc\node_modules\@eslint\config-array\dist\cjs\index.cjs:1120:15)
    at H:\Data\webclient\epc\node_modules\eslint\lib\eslint\eslint-helpers.js:354:54
    at H:\Data\webclient\epc\node_modules\eslint\lib\eslint\eslint-helpers.js:296:32
    at Object.isAppliedFilter (H:\Data\webclient\epc\node_modules\@nodelib\fs.walk\out\readers\common.js:12:31)
    at AsyncReader._handleEntry (H:\Data\webclient\epc\node_modules\@nodelib\fs.walk\out\readers\async.js:86:20)

H:\Data\webclient\epc>
```
<!-- Paste your configuration here -->
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

The installation ng add @angular-eslint/schematics is enough install ESLint and ESLint work.

### What actually happened?

Various errors like this after trying many many configurations recommended from varius sources, because **ng add @angular-eslint/schematics** is not enough. Unable to find working solution because of various versions of configuration.

### Link to Minimal Reproducible Example

try it with data above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Please provide a minimal reproducible example of the error you are getting so we can take a look.

**Comment by b-mi** [comment]
It depended on the version, this combination is functional.

 "dependencies": {
    "@angular-eslint/eslint-plugin": "^18.3.1",
    "@angular/animations": "^18.2.4",
    "@angular/cdk": "^18.2.4",
    "@angular/common": "^18.2.4",
    "@angular/compiler": "^18.2.4",
    "@angular/core": "^18.2.4",
    "@angular/forms": "^18.2.4",
    "@angular/material": "^18.2.4",
    "@angular/platform-browser": "^18.2.4",
    "@angular/platform-browser-dynamic": "^18.2.4",
    "@angular/router": "^18.2.4",
    "@angular/service-worker": "^18.2.4",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.4",
    "@angular/cli": "^18.2.4",
    "@angular/compiler-cli": "^18.2.4",
    "@types/jasmine": "~5.1.0",
    "angular-eslint": "18.3.1",
    "eslint": "^9.9.1",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.5.4",
    "typescript-eslint": "8.2.0"
  }
