### ISSUE TITLE
New Rule: Warn on non-scoped dependencies

### ISSUE THREAD

**Issue by mcandre** [eslint/eslint#18953]
### Rule details

Warn when runtime, dev, or transitive dependencies are not scoped

### Related ECMAScript feature

N/A

### What type of rule is this?

Warns about a potential problem

### Example code

NPM/Yarn packages with non-scoped names are vulnerable to spoofing.

Propose that eslint support a rule to warn for non-scoped dependencies.

I recognize that eslint primarily checks for ECMAScript syntax problems. However, eslint has wide adoption and would be a natural place to apply checks for common Node.js/altJS security concerns.

https://docs.npmjs.com/cli/v9/using-npm/scope

### Why should this rule be in the core instead of a plugin?

A plugin would also be fine. Anyone is invited to prototype such a plugin.

If the plugin shall not be installed by default in eslint, then would be helpful for eslint to link to the plugin near documentation about installing eslint, so that users are naturally guided to adopt secure practices for managing ECMAScript applications.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by aladdin-add** [comment]
Per our [rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies), we can only accept new rules if they relate to new ECMAScript features that reached stage 4 in the preceding 12 months, so this proposal doesn't qualify. You can always make a custom rule and publish a plugin.
