### ISSUE TITLE
Bug: ESLint can crash when a source directory is deleted while it runs

### ISSUE THREAD

**Issue by Knagis** [eslint/eslint#18955]
### Environment

Node version: v20.12.2
npm version: v10.8.1
Local ESLint version: v9.4.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22000

### What parser are you using?

@typescript-eslint/parser

### What did you do?

We have lot of parallel tasks happening on CI, one of those being eslint and another - a build that uses `proper-lockfile` package to create a lock directory. If the lock is released at the same time as `eslint` walks the directory gathering the source files, eslint will crash. See #18952 for details where the crash originates (just that the PR was made just before the fswalk dependency was changed).

### What did you expect to happen?

A directory vanishing while the fs walk is done shouldn't crash the process - seem logical that the walk process will ignore such case.

### What actually happened?

```
Oops! Something went wrong! :(
ESLint: 9.4.0
Error: ENOENT: no such file or directory, scandir '/builds/path/to/the/directory.lock'
```

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I was able to reproduce the issue by doing

```
while (true) {
    mkdir("src/foo.lock");
    sleep(100ms);
    rmdir("src/foo.lock");
    sleep(100ms);
}
```

with this running in background, the eslint process in my big monorepo crashed around every 4th time.

**Comment by nzakas** [comment]
> A directory vanishing while the fs walk is done shouldn't crash the process - seem logical that the walk process will ignore such case.

Hmm, I'm not sure I understand the logic here. From my point of view, crashing is the only logical thing to do. Don't you want to know that a directory you were trying to lint is no longer there?

Can you point to a directory traversal in another tool that doesn't crash in this situation?

Also, we will need a repro case to see this behavior in action.

**Comment by Knagis** [comment]
>Don't you want to know that a directory you were trying to lint is no longer there?

Deleted directory won't have any files in it to be linted. It is just a race condition if the walker managed to read the parent quickly enough and then take long enough to read the contents before reaching the particular entry.

>Can you point to a directory traversal in another tool that doesn't crash in this situation?

there is one in this tool that doesn't crash (specifically ignores ENOENT):  https://github.com/eslint/eslint/blob/main/lib/cli-engine/file-enumerator.js#L147

`glob` seems to be checking for the error as well: https://github.com/isaacs/node-glob/blob/main/src/processor.ts#L138

`fast-glob` also performs the same check: https://github.com/mrmlnc/fast-glob/blob/master/src/providers/filters/error.ts#L18

**Comment by nzakas** [comment]
Thanks, that's helpful. Can you put together a small repro case so we can see this error in action?

**Comment by Knagis** [comment]
@nzakas the issue looked to be mostly fixed, however, i just got this stacktrace.
eslint 9.30.1, @humanfs/node 0.16.6

```
Error: ENOENT: no such file or directory, scandir 'D:\js-clients\tsconfig.src.json.lock'
at async Object.readdir (node:internal/fs/promises:958:18)
at async NodeHfsImpl.list (file:///D:/js-clients/node_modules/@humanfs/node/src/node-hfs.js:304:19)
at async NodeHfs.<anonymous> (file:///D:/js-clients/node_modules/@humanfs/core/src/hfs.js:560:21)
at async NodeHfs.<anonymous> (file:///D:/js-clients/node_modules/@humanfs/core/src/hfs.js:604:6)
at async NodeHfs.walk (file:///D:/js-clients/node_modules/@humanfs/core/src/hfs.js:614:3)
at async globSearch (D:\js-clients\node_modules\eslint\lib\eslint\eslint-helpers.js:331:20)
at async Promise.allSettled (index 0)
at async globMultiSearch (D:\js-clients\node_modules\eslint\lib\eslint\eslint-helpers.js:422:18)
at async findFiles (D:\js-clients\node_modules\eslint\lib\eslint\eslint-helpers.js:593:24)
at async ESLint.lintFiles (D:\js-clients\node_modules\eslint\lib\eslint\eslint.js:734:21)
```
