### ISSUE TITLE
Change Request: Investigate using Node.js compile cache

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#18968]
### ESLint version

HEAD

### What problem do you want to solve?

ESLint can take a long time to start up because it loads in so many files from disk.

### What do you think is the correct solution?

Use the new [Node.js Compile Cache API](https://nodejs.org/en/blog/release/v22.8.0#new-js-api-for-compile-cache) to enable on-disk caching for ESLint in Node.js v22+. This will cache the compiled JavaScript that was loaded prior to the API call so that subsequent runs of ESLint will load those files from the cache instead of reading from disk and re-evaluating.

TypeScript recently [implemented this](https://github.com/microsoft/TypeScript/pull/59720).

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
it was using`v8-compile-cache` to do it in https://github.com/eslint/eslint/commit/cc3885b028e29ebc575c900f43af81cb0dabffb6, but later removed somehow.

sounds good to bring it back. :)
