### ISSUE TITLE
Add func-style exception for single-expression arrow functions

### ISSUE THREAD

**Issue by matthewwithanm** [eslint/eslint#1897]
With the addition of arrow functions, I think it would be great to have an exception for the declaration func-style rule. Namely, you should be able to enforce declaration style for all functions *other than single-expression (implicit return) arrow functions.*

It would look something like this:

`"func-style": [2, "declaration", {"allowSimpleArrowFunctionExpression": true}],`

and would behave identically to the normal rule, but allow the following:

`const isOdd = (n) => n % 2 == 1;`

This is a purely stylistic option that I imagine would be used primarily for exempting map/filter/reduce predicates.

**Comment by nzakas** [comment]
At first glance, this seems like a far too specific exception that doesn't fit with the purpose of the rule. I could see an argument to exempt arrow functions from this rule and then create a new rule that has options for how you want to format it.

**Comment by matthewwithanm** [comment]
Yeah, separate rules for arrow functions probably would be the smartest approach.

**Comment by nzakas** [comment]
How would you envision such a rule working?

**Comment by matthewwithanm** [comment]
Honestly, I think the exemption is the important part. That way you could prefer function declarations but carve out an exception for disposable, lightweight functions like those predicates.

**Comment by gyandeeps** [comment]
did we land somewhere?

**Comment by nzakas** [comment]
I think we can create an option `allowArrowFunctions` to exempt arrow functions from this check.

**Comment by robcolburn** [comment]
Is there a release planned for this? `master` doc currently incorrect :(

**Comment by mathieumg** [comment]
@robcolburn Seems released now in 1.7.
