### ISSUE TITLE
Missing support for identification of missing await keyword

### ISSUE THREAD

**Issue by b-mi** [eslint/eslint#18981]
### Environment

Node version:
20.11.1
npm version:
Local ESLint version:
latest
Global ESLint version:
Operating System:
Win 10

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Missing support for searching for the missing **await** keyword causes us faulty results. Not in theoretical and simple applications, but in real and complex applications, where failure to use the await key word results in an erroneous result due to an unexpected change in the order of execution of the function.

### What did you expect to happen?

I expect that ESLint will warn about the missing await keyword for async methods.

### What actually happened?

ESLint does not  warn about the missing await keyword for async methods, even with "@typescript-eslint/no-floating-promises": ["error"]

### Link to Minimal Reproducible Example

no stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Hi @b-mi! In this repo, we only maintain ESLint built-in rules and core functionality. The rule `@typescript-eslint/no-floating-promises` is maintained by [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), so I would suggest you post your issue there. Thanks.
