### ISSUE TITLE
Change Request: --l, --lang or --language option

### ISSUE THREAD

**Issue by ghost** [eslint/eslint#18995]
### ESLint version

9.12.0

### What problem do you want to solve?

I would like to use @eslint/json and @eslint/markdown together with ESLint, and @eslint/css and @eslint/php in the future.

But I would like to keep the scripts in package.json focused on each file type/extension.

### What do you think is the correct solution?

To add an option to restrict the languages being linted.

Something like this:

before
```
"scripts": {
    "lint:css": "stylelint '**/*.css' --cache",
    "lint:javascript": "eslint ./ --cache",
    "lint:json": "eslint ./ --cache",
    "lint:md": "markdownlint-cli2 '**/*.md'",
    "lint:php": "vendor/bin/phpstan analyse -c phpstan.neon",
},
```

after
```
"scripts": {
    "lint:css": "eslint --language 'css' ./ --cache",
    "lint:javascript": "eslint --lang 'javascript' ./ --cache",
    "lint:json": "eslint --lang 'json' ./ --cache",
    "lint:md": "eslint --l 'markdown' ./ --cache",
    "lint:php": "eslint --language 'php' ./ --cache",
},
```

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by lavarnyi** [comment]
I don't see this option available in https://eslint.org/docs/latest/use/command-line-interface

**Comment by mdjermanovic** [comment]
I'm closing this issue because the user account seems to have been deleted (https://github.com/ghost).
