### ISSUE TITLE
Change Request: --l, --lang or --language option

### ISSUE THREAD

**Issue by ghost** [eslint/eslint#18999]
I would like to use @eslint/json and @eslint/markdown together with ESLint, and @eslint/css and @eslint/php in the future.

But I would like to keep the scripts in package.json focused on each file type/extension.

To add an option to restrict the languages being linted.

Something like this:

before

```
"scripts": {
    "lint:css": "stylelint '**/*.css' --cache",
    "lint:javascript": "eslint ./ --cache",
    "lint:json": "eslint ./ --cache",
    "lint:md": "markdownlint-cli2 '**/*.md'",
    "lint:php": "vendor/bin/phpstan analyse -c phpstan.neon",
},
```

after

```
"scripts": {
    "lint:css": "eslint --language 'css' ./ --cache",
    "lint:javascript": "eslint --lang 'javascript' ./ --cache",
    "lint:json": "eslint --lang 'json' ./ --cache",
    "lint:md": "eslint --l 'markdown' ./ --cache",
    "lint:php": "eslint --language 'php' ./ --cache",
},
```

Participation

I am NOT willing to submit a pull request for this change.

I don't see this option available in https://eslint.org/docs/latest/use/command-line-interface

**Comment by mdjermanovic** [comment]
You submitted a request for a new feature in the core. We carefully evaluate new features and usually need more context about the problem the new feature would solve, such as what are the use cases for it, whether the problem can be solved using existing features, and what the advantages of the new feature would be over existing features. Then, if the team is in favor of accepting the proposed feature, we require the request to go through the [RFC process](https://github.com/eslint/rfcs).

In https://github.com/eslint/eslint/issues/18995, the problem you want to solve is described as "I would like to keep the scripts in package.json focused on each file type/extension". I was going to ask isn't that problem already solved by accepting globs, and what would be the benefits of `eslint --language 'markdown'` over `eslint '**/*.md'` for example, then noticed the account was deleted and closed the issue assuming further communication with the author is not possible. If you are willing to elaborate more about the problem you're trying to solve and the advantages the new feature would have over existing ones, we would be happy to discuss it.

**Comment by mdjermanovic** [comment]
Closing this as there hasn't been any follow up. While we wish we could investigate every open issue, we do need to prioritize. Thanks for understanding.
