### ISSUE TITLE
Change Request: Include types for `@eslint/js` in the package

### ISSUE THREAD

**Issue by bnichell** [eslint/eslint#18998]
### ESLint version

v9.12.0

### What problem do you want to solve?

```js
import js from '@eslint/js';
```

results in TypeScript error (TS7016): `Could not find a declaration file for module '@eslint/js'.`

### What do you think is the correct solution?

Include types that are currently provided via [`@types/eslint__js`](https://www.npmjs.com/package/@types/eslint__js).

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

The enhancement has been requested and rejected before in #17479.
In the meantime, the types from [`@types/eslint`](https://www.npmjs.com/package/@types/eslint) have been [included in the package](https://github.com/eslint/eslint/pull/18854).
For this reason, I am opening a new request.

**Comment by fasttime** [comment]
Thanks for the issue @bnichell.

> ```js
> import js from '@eslint/js';
> ```
>
> results in TypeScript error (TS7016): `Could not find a declaration file for module '@eslint/js'.`

For clarity, the above error does not occur if you install [`@types/eslint__js`](https://www.npmjs.com/package/@types/eslint__js) as a dependency is your project?

**Comment by bnichell** [comment]
> For clarity, the above error does not occur if you install [`@types/eslint__js`](https://www.npmjs.com/package/@types/eslint__js) as a dependency in your project?

Yes, that is correct.

**Comment by fasttime** [comment]
I support this proposal. We already ship types with `eslint`, with all packages in the `eslint/rewrite` repo, and with `eslint-visitor-keys`, `@eslint/json` and `@eslint/markdown`. I think we are ready to include types also in `@eslint/js` now. Would like a second opinion before marking as accepted.

**Comment by mdjermanovic** [comment]
> I support this proposal. We already ship types with `eslint`, with all packages in the `eslint/rewrite` repo, and with `eslint-visitor-keys`, `@eslint/json` and `@eslint/markdown`. I think we are ready to include types also in `@eslint/js` now.

I agree. Marking as accepted.

**Comment by snitin315** [comment]
I'll work on this.

**Comment by aryaemami59** [comment]
@snitin315 @fasttime Actually do you mind if I work on this?

**Comment by snitin315** [comment]
@aryaemami59 I've already started working on it.
