### ISSUE TITLE
Support Import Attributes

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#19014]
### Syntax name

Import Attributes

### Syntax proposal URL

https://github.com/tc39/proposal-import-attributes

### Example code

```js
import json from "./foo.json" with { type: "json" };
import("foo.json", { with: { type: "json" } });
```

### Implementation Checklist

- [ ] Ecma262 update: https://github.com/tc39/ecma262/pull/3057
- [x] ESTree update: https://github.com/estree/estree/pull/317
- [x] Acorn update: https://github.com/acornjs/acorn/pull/1325
- [x] `eslint-visitor-keys` update: https://github.com/eslint/js/pull/639
- [x] `espree` update: https://github.com/eslint/js/pull/639
- [x] `eslint-scope` update: (tests only) https://github.com/eslint/js/pull/639
- [ ] `eslint` update:
  - [ ] Update eslint/js dependencies https://github.com/eslint/eslint/pull/19076
  - [ ] Update core rules and add tests https://github.com/eslint/eslint/pull/19076

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Currently blocked on ESTree and Acorn updates. Here's an issue to track implementation in the Acorn repo: https://github.com/acornjs/acorn/issues/1289

**Comment by ota-meshi** [comment]
It looks like a new Acorn has been released that supports import attributes and RegExp modifiers.

**Comment by mdjermanovic** [comment]
As for the core rules, I think that naming convention rules (`id-denylist`, `id-length`, `id-match`, `camelcase`, and `no-underscore-dangle`) should be updated to ignore import attribute keys, both in static and dynamic imports.

`no-duplicate-imports` will report importing same module with different attributes (or with and without attributes). I'm not sure if there's a valid use case for importing the same module multiple times with different attributes, so I don't think any changes are needed in this rule, at least not at this moment.

Other than those, I don't see any other rules that might need an update.

@eslint/eslint-team thoughts?

**Comment by JoshuaKGoldberg** [comment]
👍 from me.

**Comment by nicolo-ribaudo** [comment]
Hey, was support for this reverted? I'm on 9.15, but ESLint is still failing on the `with` token.
