### ISSUE TITLE
Change Request: Provide an API to normalize language options

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#19037]
### ESLint version

v9.13.0

### What problem do you want to solve?

Currently there is a hard-coded mechanism in the `Linter` class to normalize certain language options for the JavaScript language like `ecmaVersion`:

https://github.com/eslint/eslint/blob/381c32b6975fa3208c62ca2b1052eb87182ed731/lib/linter/linter.js#L1646-L1668

For custom languages, there is no such provision. I think we need a documented a way for all languages to transform/normalize their options before they are passed to the parser or to a rule.

### What do you think is the correct solution?

Two possible solutions have been suggested in https://github.com/eslint/eslint/pull/19003#discussion_r1796807702:

1. We could consider allowing languages to provide a `normalizeLanguageOptions()` method. This method could be called either by the `Linter` for each a file, or in the `Config` constructor after `languageOptions` are validated and before the `Config` object is finalized. It would throw an error if the options cannot be normalized.
2. We could return a value from `validateLanguageOptions()`. This means changing the method's signature without adding a new method. As noted in the comment, the naming would be weird in this case.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

Any other way to normalize language options that were not considered?

**Comment by nzakas** [comment]
I like the idea of `normalizeLanguageOptions()` as separate from `validateLanguageOptions()`.

@mdjermanovic what do you think?

**Comment by mdjermanovic** [comment]
I can imagine that validating & normalizing in the same code could be practical for implementations. That would be a single method that either throws an error (when given language options are invalid), or returns normalized language options (when given language options are valid).

But given that we already have `validateLanguageOptions()` that is expected to either throw or complete without returning a value, adding support for `normalizeLanguageOptions()` that would be expected to always return a value seems like the cleanest solution.

**Comment by nzakas** [comment]
Marking as accepted. I'll work on this.

**Comment by nzakas** [comment]
Update to the `Language` type:
https://github.com/eslint/rewrite/pull/131
