### ISSUE TITLE
Bug: Weird yaml error message for .mjs config file, referencing #16707

### ISSUE THREAD

**Issue by scolastico** [eslint/eslint#19058]
### Environment

Node version: 18.18.0
pnpm version: 9.6.0
Local ESLint version: 9.13.0
Global ESLint version: n/a
Operating System: linux-6.1.0-26-amd64

### What parser are you using?

Default (Espree)

### What did you do?

There is an issue when running ESLint in the `base` directory of my project. The setup involves two directories, `base` and `sdk`, both using the same `eslint.config.mjs` file for configuration and version. When running the ESLint command in the `sdk` directory, it works as expected. However, running the same command in the `base` directory results in a `YAMLException` error, which suggests ESLint is incorrectly trying to interpret the `eslint.config.mjs` file as a YAML configuration.

**Steps to Reproduce:**
1. Create the following directory structure:
   ```
   /workspace/
   ├── board-bound/
       ├── base/
       │   └── eslint.config.mjs
       └── sdk/
           └── eslint.config.mjs
   ```
2. Use the following content for `eslint.config.mjs`:
   ```javascript
   import globals from "globals";
   import pluginJs from "@eslint/js";
   import tseslint from "typescript-eslint";

   export default [
     {files: ["**/*.{js,mjs,cjs,ts}"]},
     {languageOptions: { globals: globals.node }},
     pluginJs.configs.recommended,
     ...tseslint.configs.recommended,
     {rules: {"no-console": "error"}},
   ];
   ```
3. Run the following command in the `sdk` directory:
   ```bash
   npx eslint -c eslint.config.mjs src
   ```
   The command executes successfully.

4. Run the same command in the `base` directory:
   ```bash
   npx eslint -c eslint.config.mjs src
   ```
   This produces the following error:
   ```
   YAMLException: Cannot read config file: /mnt/data/workspace/board-bound/base/eslint.config.mjs
   Error: end of the stream or a document separator is expected (6:9)

    3 | import tseslint from "typescript-eslint";
    4 | 
    5 | export default [
    6 |   {files: ["**/*.{js,mjs,cjs,ts}"]},
   -------------^
    7 |   {languageOptions: { globals: globals.node }},
    8 |   pluginJs.configs.recommended,
   ```

**Notes:**
- This issue occurs specifically in the `base` directory, even though both directories use the same `eslint.config.mjs` file.
- It seems ESLint may be misinterpreting the file format in the `base` directory, even though it works fine in `sdk`.

### What did you expect to happen?

ESLint should correctly read and apply the configuration from `eslint.config.mjs` in both the `base` and `sdk` directories without errors.

### What actually happened?

In the `base` directory, ESLint throws a `YAMLException` and attempts to read the `.mjs` configuration file as YAML, resulting in an error.

### Link to Minimal Reproducible Example

https://github.com/board-bound/base

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by scolastico** [comment]
Oh and here the full content of the config file:

```js
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.node }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {rules: {"no-console": "error"}},
];
```

**Comment by mdjermanovic** [comment]
> YAMLException: Cannot read config file: /mnt/data/workspace/board-bound/base/eslint.config.mjs
> Error: end of the stream or a document separator is expected (6:9)
> 
>  3 | import tseslint from "typescript-eslint";
>  4 | 
>  5 | export default [
>  6 |   {files: ["**/*.{js,mjs,cjs,ts}"]},
> -------------^
>  7 |   {languageOptions: { globals: globals.node }},
>  8 |   pluginJs.configs.recommended,

Can you please share the complete output you're getting, including the ESLint version, stack trace, and warnings?

**Comment by scolastico** [comment]
```log
┌─[jb][desk][±][main U:7 ✗][/mnt/data/workspace/board-bound/base]
└─▪ pnpm lint

> @board-bound/base@IN-DEV lint /mnt/data/workspace/board-bound/base
> eslint -c ./eslint.config.mjs src

YAMLException: Cannot read config file: /mnt/data/workspace/board-bound/base/eslint.config.mjs
Error: end of the stream or a document separator is expected (6:9)

 3 | import tseslint from "typescript-eslint";
 4 | 
 5 | export default [
 6 |   {files: ["**/*.{js,mjs,cjs,ts}"]},
-------------^
 7 |   {languageOptions: { globals: globals.n ...
 8 |   pluginJs.configs.recommended,
    at generateError (/usr/share/nodejs/js-yaml/lib/loader.js:183:10)
    at throwError (/usr/share/nodejs/js-yaml/lib/loader.js:187:9)
    at readDocument (/usr/share/nodejs/js-yaml/lib/loader.js:1645:5)
    at loadDocuments (/usr/share/nodejs/js-yaml/lib/loader.js:1688:5)
    at Object.load (/usr/share/nodejs/js-yaml/lib/loader.js:1714:19)
    at loadLegacyConfigFile (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:171:21)
    at loadConfigFile (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:264:20)
    at ConfigArrayFactory._loadConfigData (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:415:13)
    at ConfigArrayFactory.loadFile (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:383:18)
    at createCLIConfigArray (/usr/share/nodejs/eslint/lib/cli-engine/cascading-config-array-factory.js:140:35)
```

**Comment by scolastico** [comment]
I, uhm, just noticed this does not seem to be bug of eslint, rather from `pnpm` as i just noticed this, even tho both folders have this in theyr 'package.json`:

![Image](https://github.com/user-attachments/assets/950996fd-4660-4fd9-bd5c-89d8d2f08490)


```log
┌─[jb][desk][±][main U:7 ✗][/mnt/data/workspace/board-bound/base]
└─▪ pnpm eslint --version
v6.4.0
┌─[jb][desk][±][main U:8 ✗][/mnt/data/workspace/board-bound/base]
└─▪ cd ../sdk
┌─[jb][desk][±][main U:6 ✗][/mnt/data/workspace/board-bound/sdk]
└─▪ pnpm eslint --version
v9.13.0
```
