### ISSUE TITLE
Docs: type ``Linter`` is suggested to be used, but it's not exported

### ISSUE THREAD

**Issue by ferferga** [eslint/eslint#19059]
### Docs page(s)

https://eslint.org/docs/latest/use/configure/configuration-files#typescript-configuration-files

### What documentation issue do you want to solve?

In that page it's stated that we should do ``import type { Linter } from "eslint"``.
However, that type is declared internally, but not exported.

### What do you think is the correct solution?

Export the type

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by snitin315** [comment]
`Linter` is exported ([Reference](https://github.com/eslint/eslint/blob/3d44b3c4751e4c44c32b879b65a723faee9c1c29/lib/types/index.d.ts#L853)). Please make sure you're using [ESLint v9.10.0](https://github.com/eslint/eslint/releases/tag/v9.10.0) or later

**Comment by ferferga** [comment]
@snitin315 Please check this reproduction where ESLint v9.13.0 is being used: https://stackblitz.com/edit/vitejs-vite-9abzaz?file=packages%2Fconfigs%2Feslint.config.ts

If you hover over ``Linter.Config[]``:

![Image](https://github.com/user-attachments/assets/0a9db87c-4dea-4750-849d-c9305056ca24)

If you hover over the import statement:

![Image](https://github.com/user-attachments/assets/369176f7-2f25-4082-bbf0-d2fdf201eee9)

**Comment by snitin315** [comment]
@ferferga It doesn't seem to be happening everywhere, sharing screenshots for `main/eslint.config.ts`. Perhaps there is an issue with your TS configuration?

![Image](https://github.com/user-attachments/assets/045fb1f8-cdfc-4efd-84a3-1e5c42f28249)

![Image](https://github.com/user-attachments/assets/cecaac0b-c4d2-450f-93cd-56ce781955de)

**Comment by ferferga** [comment]
@snitin315 Good catch! I recall trying exactly what you did in the simplest setup possible, but with no avail, though it's very possible it was pre-v9.10 (I've been with this for a while, just posting here now). In the playground I used the most similar setup to my current one to demonstrate the bug, but haven't checked exactly what you did, sorry.

I don't think this is an issue of my config (as you can see, I share the same config across all the packages in that monorepo), but rather a bug with TypeScript itself. Just do the following and the error will be gone:

1. Rename ``packages/configs/eslint`` to ``packages/configs/eslint-new``
2. Update the exports as well in ``packages/configs/package.json``

That will fix the bug, I shall open this instead on TypeScript repo. Thank you very much for helping me in the triaging anyway!
