### ISSUE TITLE
Rule Change: (no-restricted-imports) Allow multiple messages for different imports from the same package.

### ISSUE THREAD

**Issue by ajhenry** [eslint/eslint#19079]
### What rule do you want to change?

no-restricted-imports

### What change do you want to make?

Generate more warnings

### How do you think the change should be implemented?

A new option

### Example code

import { deprecatedA } from "@org/module" // no-restricted-imports: `deprecatedA` is deprecated in favor of `newA`
import { deprecatedB } from "@org/module" // no-restricted-imports: `deprecatedB` is deprecated in favor of `newB`

### What does the rule currently do for this code?

Right now, you can only specify one message for the `no-restricted-imports` rule for an entire package. For legacy packages where everything is in a barrel export, this can present problems. Additionally, if you specify multiple paths that reference the package, only the last one in the message _will be reported_.

Take the following rules for example:

```js
'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: '@org/module',
          importNames: ['A'],
          message: 'Please use the A from @org/other-library instead',
        },
        {
          name: '@org/module',
          importNames: ['B'],
          message: 'Completely different error message for a different import from the same module as above',
        },
      ]
    }
]
```

Only `import { B } from '@org/module'` will be reported.

### What will the rule do after it's changed?

Maybe `importNames` could be a list of objects with a message attached to them?

```js
'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: '@org/module',
          importNames: [
              { module: 'A', message: 'Please use the A from @org/other-library instead' }
              { module: 'B', message: 'Completely different error message for a different import from the same module as above' }
          ],
        },
      ]
    }
]
```

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

Is there a workout for this?

**Comment by mdjermanovic** [comment]
Hi @ajhenry, thanks for the issue!

Which version of ESLint are you using? In v9, the configuration you provided should report both `A` and `B`. Here's a [Playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgJ25vLXJlc3RyaWN0ZWQtaW1wb3J0cyc6IFtcbiAgICAnZXJyb3InLFxuICAgIHtcbiAgICAgIHBhdGhzOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1lOiAnQG9yZy9tb2R1bGUnLFxuICAgICAgICAgIGltcG9ydE5hbWVzOiBbJ0EnXSxcbiAgICAgICAgICBtZXNzYWdlOiAnUGxlYXNlIHVzZSB0aGUgQSBmcm9tIEBvcmcvb3RoZXItbGlicmFyeSBpbnN0ZWFkJyxcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICdAb3JnL21vZHVsZScsXG4gICAgICAgICAgaW1wb3J0TmFtZXM6IFsnQiddLFxuICAgICAgICAgIG1lc3NhZ2U6ICdDb21wbGV0ZWx5IGRpZmZlcmVudCBlcnJvciBtZXNzYWdlIGZvciBhIGRpZmZlcmVudCBpbXBvcnQgZnJvbSB0aGUgc2FtZSBtb2R1bGUgYXMgYWJvdmUnLFxuICAgICAgICB9LFxuICAgICAgXVxuICAgIH1cbl0qL1xuXG5pbXBvcnQgeyBBIH0gZnJvbSAnQG9yZy9tb2R1bGUnXG5pbXBvcnQgeyBCIH0gZnJvbSAnQG9yZy9tb2R1bGUnIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==).

**Comment by ajhenry** [comment]
@mdjermanovic Ah there it is, I'm on `8.57.0`. Appreciate the help!
