### ISSUE TITLE
Bug: Cannot serialize key "parse" in parser when using FlatCompat with next.js config

### ISSUE THREAD

**Issue by kirill-konshin** [eslint/eslint#19080]
### Environment

Node version: v23.0.0
npm version: v10.9.0
Local ESLint version: v9.13.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 24.0.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Configuration:

```js
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import js from '@eslint/js';
import ts from 'typescript-eslint';
import { FlatCompat } from '@eslint/eslintrc';
import { fixupConfigRules } from '@eslint/compat';
import prettierConfigRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';

const flatCompat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const config = [
  js.configs.recommended,
  ...ts.configs.recommended,
  ...fixupConfigRules([...flatCompat.extends('next')]),
  prettierConfigRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    ignores: [ ... ],
  },
];

export default config;
```
</details>

Dependencies:

```json
{
  "devDependencies": {
    "@eslint/compat": "^1.2.2",
    "@eslint/eslintrc": "^3.1.0",
    "@eslint/js": "^9.13.0",
    "@next/eslint-plugin-next": "^15.0.2",
    "eslint": "^9.13.0",
    "eslint-config-next": "^15.0.2",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-react-hooks": "^5.0.0",
    "globals": "^15.11.0",
    "next": "^15.0.2",
    "prettier": "^3.3.3",
    "typescript": "^5.6.3",
    "typescript-eslint": "^8.12.2"
  }
}
```

https://stackblitz.com/edit/stackblitz-starters-vlmm17

Create terminal run `npm run lint`.

**ATTENTION! TO REPRODUCE THE ISSUE THERE MUST BE A CACHE FROM ESLINT 8.**

```bash
$ DEBUG=eslint:eslint eslint --cache --cache-location node_modules/.cache/eslint --fix .
```

Issue reproduces only in this case!

### What did you expect to happen?

Normal linting.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Cannot serialize key "parse" in parser: Function values are not supported.
    at languageOptionsToJSON (/x/node_modules/eslint/lib/config/config.js:111:23)
    at languageOptionsToJSON (/x/node_modules/eslint/lib/config/config.js:105:35)
    at Config.toJSON (/x/node_modules/eslint/lib/config/config.js:275:30)
    at stringify (/x/node_modules/json-stable-stringify-without-jsonify/index.js:25:25)
    at module.exports (/x/node_modules/json-stable-stringify-without-jsonify/index.js:68:7)
    at hashOfConfigFor (/x/node_modules/eslint/lib/cli-engine/lint-result-cache.js:50:75)
    at LintResultCache.getCachedLintResults (/x/node_modules/eslint/lib/cli-engine/lint-result-cache.js:116:30)
    at /x/node_modules/eslint/lib/eslint/eslint.js:783:41
    at async Promise.all (index 0)
    at async ESLint.lintFiles (/x/node_modules/eslint/lib/eslint/eslint.js:759:25)
```

I traced it down to `absoluteFilePath => eslintrcConfig.criteria.test(absoluteFilePath)` function of `FlatCompat`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-vlmm17

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Thanks for the report, I can reproduce this.

I tried a couple of things and determined that `eslint-config-next` is supplying a custom parser as `languageOptions.parser` for JavaScript files. Unfortunately, this parser does not include the appropriate [meta information](https://eslint.org/docs/latest/extend/custom-parsers#meta-data-in-custom-parsers) for ESLint to be able to serialize the config (caching requires serializing the config, which is why there is only an error when using `--cache`). 

I suggest you [open an issue](https://github.com/vercel/next.js/issues/new/choose) to ask them to add the meta information to this file:
https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/parser.js

Once the meta information is included, ESLint will be able to serialize the value.

**Comment by kirill-konshin** [comment]
My point was that eslint should probably delete the cache of v8 if v9 is running. This would solve the problem.

Besides, the function in question is `absoluteFilePath => eslintrcConfig.criteria.test(absoluteFilePath)`, it is added by FlatCompat...

**Comment by subashcs** [comment]
This was the workaround that worked for me:

`
// eslint.config.mjs
import { FlatCompat } from "@eslint/eslintrc"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

/** @type {import('eslint').Linter.Config[]} */
const configs = [
  ...compat.extends("next/core-web-vitals"),
  ...compat.extends("next/typescript"),
  
]

export default configs
`

**Comment by yeasin2002** [comment]
@subashcs Thank, It worked.
