### ISSUE TITLE
Starting with eslint 9.14.0 I am getting messages like “Processing pending tasks: 1 pending, 0 working."

### ISSUE THREAD

**Issue by s-nakajima** [eslint/eslint#19099]
### Environment

Node version: v20.18.0
npm version: yarn 1.22.22 (npm 10.8.2)
Local ESLint version: eslint 9.14.0
Global ESLint version:
Operating System: Ubuntu 24.04

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
[package.json]
"eslint": ">=8.23.1",
"eslint-plugin-jsdoc": ">=39.3.6",
"eslint-plugin-prettier": ">=4.2.1",
```
</details>

```js
[.eslintrc.js]
module.exports = {
  "languageOptions": {
    "parserOptions": {
      "ecmaVersion": "latest",
      "sourceType": "module"
    },
    "globals": {
      "MyGlobal": "readonly",
      "AnotherGlobal": "writable"
    },
  },
  "ignores": ["**/webpack.config.js", "**/dist/*.js", "**/_*"],
  "plugins": {
    "jsdoc": require('eslint-plugin-jsdoc'),
    "prettier": require('eslint-plugin-prettier')
  },
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "printWidth": 100,
        "bracketSpacing": false
      }
    ],
    "max-len": ["error", {"code": 100}],
    "max-classes-per-file": ["error", 2],
    "max-lines": "error",
    "max-lines-per-function": ["error", {"max": 80}],
    "max-depth": "error",
    "max-nested-callbacks": "error",
    "max-params": "error",
    "no-eval": "warn",
    "no-var": "warn",
    "no-unused-vars": "off"
  }
}
```

### What did you expect to happen?

Starting with eslint 9.14.0 I am getting messages like `Processing pending tasks: 1 pending, 0 working.`.
I do not want the running message to appear as it did until 9.13.0.

Is it intended that the message be displayed?

I added the `--quiet` option just to be sure, but it does not improve the situation.
How can I make the message not appear?

Please let me know.

### What actually happened?

I am posting the results of the run for your reference.

````
NODE_PATH=./vendor/node_modules eslint --config ./tests/.eslintrc.js ./plugins/
Processing pending tasks: 1 pending, 0 working.
Processed pending tasks: 0 pending, 1 working.
Processing pending tasks: 1 pending, 1 working.
Processed pending tasks: 0 pending, 2 working.
Processing pending tasks: 1 pending, 2 working.
Processed pending tasks: 0 pending, 3 working.
Function called successfully without retry.
Processing pending tasks: 0 pending, 2 working.
Processed pending tasks: 0 pending, 2 working.
Function called successfully without retry.
Processing pending tasks: 0 pending, 1 working.
Processed pending tasks: 0 pending, 1 working.
Function called successfully without retry.
Processing pending tasks: 0 pending, 0 working.
Processed pending tasks: 0 pending, 0 working.
````

Thank you in advance for your confirmation.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
seems it was from @humanwhocodes/retry v0.3.1:

https://github.com/humanwhocodes/retry/blob/330552f6545197d902d19b143e94bd09cd6e6852/src/retrier.js#L25

did you set up the `DEBUG` env?

**Comment by s-nakajima** [comment]
Oooh. I see that the DEBUG environment variable is now affected.
Indeed, I have the environment variable DEBUG set.

When I run the program with DEBUG empty, the message no longer appears.
````
DEBUG= NODE_PATH=. /vendor/node_modules eslint --config . /tests/.eslintrc.js . /plugins/
````

Thank you.
