### ISSUE TITLE
Change Request: Add `meta` and `rules` properties to ESLint JavaScript Plugin (`@eslint/js`) export

### ISSUE THREAD

**Issue by rakleed** [eslint/eslint#19091]
### ESLint version

9.14.0

### What problem do you want to solve?

I don't see the config name in [config-inspector](https://github.com/eslint/config-inspector), which makes it harder to find the right config right away when there are a lot of them:

<details><summary>Screenshot ↓</summary>

![Image](https://github.com/user-attachments/assets/ff007cd3-3126-49b8-877d-d0cc73a5a9f3)

</details>

Also, as you write in the [documentation](https://eslint.org/docs/latest/extend/plugins#meta-data-in-plugins:~:text=For%20easier%20debugging%20and%20more%20effective%20caching%20of%20plugins%2C%20it%E2%80%99s%20recommended%20to%20provide%20a%20name%20and%20version%20in%20a%20meta%20object%20at%20the%20root%20of%20your%20plugin%2C%20like%20this%3A), it is necessary for easier debugging and more effective caching of plugins.

### What do you think is the correct solution?

Add `meta` and `rules` properties to the [ESLint JavaScript Plugin](https://github.com/eslint/eslint/tree/main/packages/js) [export](https://github.com/eslint/eslint/blob/main/packages/js/src/index.js) as described in https://eslint.org/docs/latest/extend/plugins.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for the suggestion @rakleed. I assume from your screenshot that you are viewing the `recommended` configuration from `@eslint/js` in the config inspector. The _anonymous_ label in the image indicates that that config has no name associated to it. This is not related to the fact that `@eslint/plugin` has no `meta` or `rules` properties exported.

In those cases, the best you can do is adding a name to the config object that includes the imported rules, for example:

```js
import js from "@eslint/js";

export default [

    // apply recommended rules to JS files
    {
        name: "@eslint/js/recommended"
        files: ["**/*.js"],
        rules: js.configs.recommended.rules
    },
    // other configs here ...
];
```

We could update the code examples in the plugin's [readme](https://github.com/eslint/eslint/tree/main/packages/js#usage) file to show users how to set a name on their configs.

As for why that config has no predefined `name` property, it's indicated in a comment in the source code:

https://github.com/eslint/eslint/blob/05ef92dd15949014c0735125c89b7bd70dec58c8/packages/js/src/configs/eslint-recommended.js#L11-L17

**Comment by fasttime** [comment]
I'm working on a pull request to add `meta` information to the `@eslint/plugin` and improve the code examples by adding a `name` property to the config objects.

**Comment by rakleed** [comment]
@fasttime 

> As for why that config has no predefined `name` property, it's indicated in a comment in the source code:
> 
> https://github.com/eslint/eslint/blob/05ef92dd15949014c0735125c89b7bd70dec58c8/packages/js/src/configs/eslint-recommended.js#L11-L17

Will this issue be solved when you move the JS rules into a separate plugin? Since third-party plugins, which also still support version 8 and the old config format, support displaying the name:

- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/8b7c5fcf5c9743db4afde0bb9c90cc51782d47ef/index.js#L50C15-L57
- https://github.com/Rel1cx/eslint-react/blob/7aa09796122b414475d9844ed9dcbaabe8582cc2/packages/plugins/eslint-plugin/src/index.ts#L29-L41
- https://github.com/eslint-community/eslint-plugin-promise/blob/3fae2417bb59ae82a56d3f82d8e28a09eba26421/index.js#L46-L56

And is there a separate issue to track when `@eslint/js` becomes a separate plugin? I couldn't find it in https://github.com/eslint/eslint, https://github.com/eslint/js or https://github.com/eslint/rewrite.

**Comment by fasttime** [comment]
> Will this issue be solved when you move the JS rules into a separate plugin?

When eslintrc support is removed, we'll be able to add a `name` property to the configs in this plugin. Eslintrc support will be removed in a major release because it's a breaking change. This is unrelated to extracting JS rules from the core.

> Since third-party plugins, which also still support version 8 and the old config format, support displaying the name:
> 
> * https://github.com/sindresorhus/eslint-plugin-unicorn/blob/8b7c5fcf5c9743db4afde0bb9c90cc51782d47ef/index.js#L50C15-L57
> 
> * https://github.com/Rel1cx/eslint-react/blob/7aa09796122b414475d9844ed9dcbaabe8582cc2/packages/plugins/eslint-plugin/src/index.ts#L29-L41
> 
> * https://github.com/eslint-community/eslint-plugin-promise/blob/3fae2417bb59ae82a56d3f82d8e28a09eba26421/index.js#L46-L56

A config's `name` property is only allowed for flat configs, and many plugins include different configs for eslintrc and flat mode. The example code for `eslint-plugin-unicorn` shows that legacy configs are created without have a `name` property (`flatConfigName`).

> And is there a separate issue to track when `@eslint/js` becomes a separate plugin? I couldn't find it in https://github.com/eslint/eslint, https://github.com/eslint/js or https://github.com/eslint/rewrite.

It's #19013.
