### ISSUE TITLE
Bug: Updating to `9.14.0` results in `failed to unmarshal rdjson` error

### ISSUE THREAD

**Issue by dsotirakis** [eslint/eslint#19101]
### Environment

Node version: 20
npm version: 9
Local ESLint version: 9.14.0
Global ESLint version: 9.14.0
Operating System: Ubuntu

### What parser are you using?

Default (Espree)

### What did you do?

```js
{
  {
  "description": "node dependencies for eslint linting",
  "private": true,
  "dependencies": {
    "eslint": "9.14.0", # updated from 9.13.0
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-prettier": "5.2.1",
    "eslint-plugin-yml": "1.15.0",
    "prettier": "3.3.3"
  }
}
```

### What did you expect to happen?

Expected everything to run normally after dependabot bumped the eslint version.

### What actually happened?

I got the following error:

```
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): invalid value Processing
```

I am not sure if this is `eslint`'s fault or `reviewdog`'s but I wanted to raise it with you first so if `eslint` latest update broke reviewdog we can make sure to fix it in the next release!

(We're also using `reviewdog/action-eslint@9a6606695f1ef9709cce821919ca3b2a6d5e6bb5 # v1.32.0` in GitHub Actions, if that helps).

If you think this doesn't have to do with `eslint` but it's a reviewdog problem instead, please let me know so I can create a new issue there if needed.

### Link to Minimal Reproducible Example

(sorry, no meaningful example, please let me know if you need something specific)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The failure happens both locally and on CI.

**Comment by mdjermanovic** [comment]
> reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): invalid value Processing

I suspect this might be caused by the debug output of `@humanwhocodes/retry`:

https://github.com/humanwhocodes/retry/blob/90317d3f133d45583296ef740fb8f8e2997c3903/src/retrier.js#L385

Can you check if `DEBUG` environment variable is set?

**Comment by dsotirakis** [comment]
@mdjermanovic yes it indeed was enabled! Thanks for looking into this!
How would you suggest that we move forward with this? (apart from disabling the debug flag for now in our end)

**Comment by mdjermanovic** [comment]
There was another issue where this output was unexpected: https://github.com/eslint/eslint/issues/19099.

@nzakas what do you think about updating `@humanwhocodes/retry` to check for a specific value in `DEBUG` env variable, or perhaps to use the `debug` package?

**Comment by snitin315** [comment]
Yeah, even `DEBUG=false npx eslint .` prints these logs which I believe is misleading. [Here `process?.env.DEBUG`](https://github.com/humanwhocodes/retry/blob/330552f6545197d902d19b143e94bd09cd6e6852/src/retrier.js#L25) will be true for any value expect empty string `DEBUG=""`.

![Image](https://github.com/user-attachments/assets/bf27ba3f-6cdb-4429-989f-c1970754a697)

**Comment by nzakas** [comment]
https://github.com/humanwhocodes/retry/pull/41
