### ISSUE TITLE
Docs: Missing fields in LintMessage type

### ISSUE THREAD

**Issue by DMartens** [eslint/eslint#19119]
### Docs page(s)

The [LintMessage Type](https://eslint.org/docs/latest/integrate/nodejs-api#-lintmessage-type) of the Node.js API reference

### What documentation issue do you want to solve?

The root type is missing the optional `messageId` property and the suggestion type is missing the optional `messageId` and `data` properties.

### What do you think is the correct solution?

Add the property `messageId: string: The message id of the lint error.  This property is undefined if the rule does not use message ids.`
and modify the type of suggestions `({ desc: string, fix: EditInfo, messageId?: string, data?: object })`

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for the report @DMartens. I can see the same fields are also missing from the [`SuppressedLintMessage` type](https://github.com/eslint/eslint/blob/v9.14.0/docs/src/integrate/nodejs-api.md?plain=1#L441-L462) on the same page and `messageId` is missing from the list of information returned by [`Linter.verify()`](https://github.com/eslint/eslint/blob/v9.14.0/docs/src/integrate/nodejs-api.md?plain=1#L657-L667). A PR to update the documentation is welcome.
