### ISSUE TITLE
Rule Change: Add fixer to no-useless-concat for strings on the same line

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#19113]
### What rule do you want to change?

no-useless-concat

### What change do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

'some' + 'string'

### What does the rule currently do for this code?

Report a lint complaint on the `+` with no fixer.

https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdXNlbGVzcy1jb25jYXQ6IFwiZXJyb3JcIiovXG5cbidzb21lJyArICdzdHJpbmcnXG4iLCJvcHRpb25zIjp7InJ1bGVzIjp7fSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19

### What will the rule do after it's changed?

For straightforward cases where the solution would be to just remove the `+`, it'd be nice to add a fixer to remove the `' + '`:

```diff
- 'some' + 'string'
+ 'somestring'
```

In other words, I'm proposing a fixer be added _if_ the start of the string (`'s`) is on the same line as the end of the string (`g'`).

This could alternately be done as a suggestion fixer. The rule does delve a little bit into stylistic territory. But for cases where the string is all on one line already, I struggle to think of a preferable alternative.

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

It's unclear to me whether this is a frozen rule per https://eslint.org/blog/2020/05/changes-to-rules-policies/#:~:text=Stylistic%20rules%20are%20frozen%20%2D%20we,difficult%2Dto%2Dunderstand%20options. It's not explicitly mentioned anywhere as frozen that I can find, but it does show up in the list on https://github.com/eslint/eslint/issues/18694#issuecomment-2355493603 - albeit without the ❄.

I came across while working on #17814. Running `npx prettier --write .`, then `npm run lint`, yields many complaints. For example, in `tests/lib/rules/sort-imports.js`, the change from Prettier is:

```diff
    valid: [
-        "import a from 'foo.js';\n" +
-                "import b from 'bar.js';\n" +
-                "import c from 'baz.js';\n",
+        "import a from 'foo.js';\n" + "import b from 'bar.js';\n" + "import c from 'baz.js';\n",
```

It'd be _really_ nice to have an automatic fixer for all of these cases.

[no-useless-concat-reports.txt](https://github.com/user-attachments/files/17655773/no-useless-concat-reports.txt)

**Comment by fasttime** [comment]
Thanks for the useful information. I've posted [a comment](https://github.com/eslint/eslint/issues/18694#issuecomment-2484827976) in issue #18694 to clarify if the `no-useless-concat` should be considered frozen or not.

**Comment by mdjermanovic** [comment]
We've now agreed to consider `no-useless-concat` as frozen, so we're not adding new features (incl. autofix/suggestions) to it.
