### ISSUE TITLE
nested comments in html

### ISSUE THREAD

**Issue by PGTBoos** [eslint/eslint#19124]
### Syntax name

  -->

### Syntax proposal URL

Essentially I would like ESLint to support nested comments  in HTML

It often happens during development you would like to hide some code and that code had a comment too, or worse multiple comments. And while some may prefer a syntax without any comments at all.
Such is not a rule to not write comments. 
In fact I find comments in code generally really usefully, as to explain what code does towards new developers of a team, or to team members,  or to quickly get you started again after 2 years in some area.

so I wish i could use nested comments.

### Example code

```js
<!---  some 
   <!--text -->  
-->
```

### Implementation Checklist

- [ ] Ecma262 update: 
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [x] `eslint` update: 

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
ESLint itself doesn't support HTML. You're probably using a custom ESLint parser to parse HTML, so I'd suggest opening an issue with them.
