### ISSUE TITLE
Docs: Mark all `eslint-recommended` rules from typescript-eslint as ‘handled by TypeScript’

### ISSUE THREAD

**Issue by kripod** [eslint/eslint#19138]
### Docs page(s)

- https://eslint.org/docs/latest/rules/no-class-assign
- https://eslint.org/docs/latest/rules/no-new-native-nonconstructor

### What documentation issue do you want to solve?

As seen in the [`eslint-recommended` config of typescript-eslint](https://typescript-eslint.io/users/configs#eslint-recommended), both [`no-class-assign`](https://github.com/typescript-eslint/typescript-eslint/blob/12ce800be7779aa1a1ea0329a59fb8ee14795634/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L25) and [`no-new-native-nonconstructor`](https://github.com/typescript-eslint/typescript-eslint/blob/12ce800be7779aa1a1ea0329a59fb8ee14795634/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts#L34) rules are turned off due to being handled by TypeScript.

### What do you think is the correct solution?

Docs pages should be updated accordingly, amending `handled_by_typescript: true` to the rule pages affected [as seen here](https://github.com/eslint/eslint/blob/6f37b0747a14dfa9a9e3bdebc5caed1f39b6b0e2/docs/src/rules/no-invalid-this.md#L4).

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

The reverse applies to `no-invalid-this` which isn’t part of typescript-eslint’s `eslint-recommended` config yet, see https://github.com/typescript-eslint/typescript-eslint/issues/10345.

**Comment by nzakas** [comment]
Sounds good. Feel free to send a PR.
