### ISSUE TITLE
Bug: Disabling of `no-redeclare` `builtinGlobals` not consistently required

### ISSUE THREAD

**Issue by adamlui** [eslint/eslint#19141]
### Environment

Node version: v22.9.0
npm version: v10.9.0
Local ESLint version: v9.14.0
Global ESLint version: none
Operating System: Win10

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```js
import js from '@eslint/js'
import globals from 'globals'
import json from '@eslint/json'
import markdown from '@eslint/markdown'
import * as regexp from 'eslint-plugin-regexp'
import eslintPluginYml from 'eslint-plugin-yml'

export default [
    { ignores: ['**/*.min.js'] },
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 'latest', sourceType: 'script',
            globals: {
                ...globals.browser, ...globals.greasemonkey, ...globals.node,
                chatgpt: 'readonly', chrome: 'readonly', CryptoJS: 'readonly'
            }
        },
        plugins: { regexp },
        rules: {
            ...js.configs.recommended.rules, ...regexp.configs['flat/recommended'].rules,
            'indent': 'off', 'no-unexpected-multiline': 'off', 'key-spacing': 'off', // allow whitespace anywhere
            'quotes': ['error', 'single', { 'allowTemplateLiterals': true }], // enforce single quotes except backticks to avoid escaping quotes
            'comma-dangle': ['error', 'never'], // enforce no trailing commas in arrays or objects
            'no-async-promise-executor': 'off', // allow promise executor functions to be async (to accomodate await lines)
            'no-constant-condition': 'off', // allow constant conditions
            'no-empty': 'off', // allow empty blocks
            'no-inner-declarations': 'off', // allow function declarations anywhere
            'no-useless-escape': 'off', // allow all escape chars cause ESLint sucks at detecting truly useless ones
            'no-unused-vars': ['error', { 'caughtErrors': 'none' }], // allow unused named args in catch blocks
            'no-redeclare': ['error', { 'builtinGlobals': false }] // allow redeclaration of `chatgpt` in chatgpt.js
                // ...due to languageOptions.globals declaration for starter refs
        }
    },
    { files: ['**/*.mjs', '**/lib*/*.js'], languageOptions: { sourceType: 'module' }},
    { files: ['**/*.json'], ignores: ['**/package-lock.json'], language: 'json/json', ...json.configs.recommended },
    {
        files: ['**/*.md'], language: 'markdown/commonmark', plugins: { markdown },
        rules: {
            ...markdown.configs.recommended[0].rules,
            'markdown/heading-increment': 'off', // allow headings to skip levels
            'markdown/fenced-code-language': 'off', // allow code blocks w/ no language specified
            'markdown/no-missing-label-refs': 'off' // allow missing label references
        }
    },
    { files: ['**/*.yaml, **/*.yml'], ...eslintPluginYml.configs['flat/standard'][1] }
]
```
</details>

```js
// © 2023–2024 KudoAI & contributors under the MIT license.
// Source: https://github.com/KudoAI/chatgpt.js
// User guide: https://chatgptjs.org/userguide
// Latest minified release: https://cdn.jsdelivr.net/npm/@kudoai/chatgpt.js/chatgpt.min.js

// Init feedback props
localStorage.alertQueue = JSON.stringify([]);
localStorage.notifyProps = JSON.stringify({ queue: { topRight: [], bottomRight: [], bottomLeft: [], topLeft: [] }});

// Define chatgpt API
const chatgpt = {
    openAIaccessToken: {}, endpoints: {
    assets: 'https://cdn.jsdelivr.net/gh/KudoAI/chatgpt.js',
    openAI: {
        session: 'https://chatgpt.com/api/auth/session',
        chats: 'https://chatgpt.com/backend-api/conversations',
        chat: 'https://chatgpt.com/backend-api/conversation',
        share_create: 'https://chatgpt.com/backend-api/share/create',
        share: 'https://chatgpt.com/backend-api/share',
        instructions: 'https://chatgpt.com/backend-api/user_system_messages'
    }},
...
```

### What did you expect to happen?

https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/extension/lib/chatgpt.js is auto-synced from
https://github.com/KudoAI/chatgpt.js/blob/main/chatgpt.js

Without the config line 31-32 in https://github.com/KudoAI/chatgpt.js/blob/main/eslint.config.mjs...

```js
'no-redeclare': ['error', { 'builtinGlobals': false }] // allow redeclaration of `chatgpt` in chatgpt.js
    // ...due to languageOptions.globals declaration for starter refs
```

KudoAI/chatgpt.js errors w/ 

```
e:\kudoai\chatgpt.js\chatgpt.js
  11:7  error  'chatgpt' is already defined as a built-in global variable  no-redeclare
```

...but KudoAI/chatgpt.js-chrome-starter's same chatgpt.js, without the config line, passes linting

The config files are virtually identical except that one disabling line:
https://github.com/KudoAI/chatgpt.js/blob/main/eslint.config.mjs
https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/eslint.config.mjs

...so one would expect the line to not be required in both files

### What actually happened?

```js
'no-redeclare': ['error', { 'builtinGlobals': false }] // allow redeclaration of `chatgpt` in chatgpt.js
    // ...due to languageOptions.globals declaration for starter refs
```

...is only required in https://github.com/KudoAI/chatgpt.js/blob/main/eslint.config.mjs but not https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/eslint.config.mjs to pass lint

### Link to Minimal Reproducible Example

https://github.com/KudoAI/chatgpt.js

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
> https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/extension/lib/chatgpt.js is auto-synced from https://github.com/KudoAI/chatgpt.js/blob/main/chatgpt.js
> 
> Without the config line 31-32 in https://github.com/KudoAI/chatgpt.js/blob/main/eslint.config.mjs...
> 
> 'no-redeclare': ['error', { 'builtinGlobals': false }] // allow redeclaration of `chatgpt` in chatgpt.js
>     // ...due to languageOptions.globals declaration for starter refs
> KudoAI/chatgpt.js errors w/
> 
> ```
> e:\kudoai\chatgpt.js\chatgpt.js
>   11:7  error  'chatgpt' is already defined as a built-in global variable  no-redeclare
> ```
> 
> ...but KudoAI/chatgpt.js-chrome-starter's same chatgpt.js, without the config line, passes linting
> 
> The config files are virtually identical except that one disabling line: https://github.com/KudoAI/chatgpt.js/blob/main/eslint.config.mjs https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/eslint.config.mjs
> 
> ...so one would expect the line to not be required in both files

The difference is that https://github.com/KudoAI/chatgpt.js/blob/main/chatgpt.js is linted with [`sourceType: "script"`](https://github.com/KudoAI/chatgpt.js/blob/319d3118f064d8a653039703e66505771159da7e/eslint.config.mjs#L13) as it doesn't match [`['**/*.mjs', '**/lib*/*.js']`](https://github.com/KudoAI/chatgpt.js/blob/319d3118f064d8a653039703e66505771159da7e/eslint.config.mjs#L35C14-L35C42), whereas https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/main/extension/lib/chatgpt.js is linted with [`sourceType: "module"`](https://github.com/KudoAI/chatgpt.js-chrome-starter/blob/a1d4889160161da23b8261745bd701af2328b567/eslint.config.mjs#L29).

In the former case, `const chatgpt` in the top-level of a script declares a variable in the global scope, so it redeclares presumably already defined global variable `chatgpt`. In the latter case, `const chatgpt` in the top-level of a module declares a variable in the module scope so it doesn't redeclare the global variable.

**Comment by adamlui** [comment]
The only place it's already defined is in the config's

```js
...
            globals: {
                ...globals.browser, ...globals.greasemonkey, ...globals.node,
                chatgpt: 'readonly', chrome: 'readonly', CryptoJS: 'readonly'
            }
...
```

...and the chatgpt.js file, which is the source of this initial `chatgpt` declaration for starter templates in the repo to import/ref. So the config's global is for these templates to reference `chatgpt` & pass lint.

But since chatgpt.js is the source of declaration for others to ref, even as `[sourceType: "script"]`, it's expected to not be a re-declaration, so what is the best way to avoid the error without disabling the redeclarations `builtinGlobals` option?

**Comment by mdjermanovic** [comment]
> But since chatgpt.js is the source of declaration for others to ref, even as `[sourceType: "script"]`, it's expected to not be a re-declaration, so what is the best way to avoid the error without disabling the redeclarations `builtinGlobals` option?

I think the common practice is to set the configured global variable to `"off"` for the file that does declare it. That means that the variable is not already declared elsewhere.
