### ISSUE TITLE
Bug: sourceType option is added to languageOptions.parserOptions

### ISSUE THREAD

**Issue by vladshcherbin** [eslint/eslint#19144]
### Environment

Node version: 22.10.0
pnpm version: 9.12.3
ESLint version: 9.15.0
Operating System: macOS 15.0.1

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
</details>

```js
import { loadESLint } from 'eslint'

const ESLint = await loadESLint()
const eslint = new ESLint()
const config = await eslint.calculateConfigForFile('*.js')

console.log(config.languageOptions.sourceType)
console.log(config.languageOptions.parserOptions)

// module
// { sourceType: 'module' }
```

### What did you expect to happen?

According to docs, there is no such option as `sourceType` in [languageOptions.parserOptions](https://eslint.org/docs/latest/use/configure/language-options#specifying-parser-options)

### What actually happened?

`sourceType` options was added to `languageOptions.parserOptions`

### Link to Minimal Reproducible Example

https://github.com/vladshcherbin/eslint-9-15/tree/parser-options

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

![Image](https://github.com/user-attachments/assets/285715be-469f-445e-9a28-ba86dcf70ea9)

**Comment by mdjermanovic** [comment]
Same as https://github.com/eslint/eslint/issues/19143. `ESLint#calculateConfigForFile()` returns the final normalized config for the file. When the default parser is used, `languageOptions.sourceType` is copied to `languageOptions.parserOptions.sourceType`.

https://github.com/eslint/eslint/blob/6f37b0747a14dfa9a9e3bdebc5caed1f39b6b0e2/lib/languages/js/index.js#L130-L156

**Comment by vladshcherbin** [comment]
Thanks for clarification 🙌
