### ISSUE TITLE
Granular "quiet" options

### ISSUE THREAD

**Issue by okeydoke** [eslint/eslint#1914]
Ideally I'd like to show warnings but not warnings for files that where ignored
The only option I've seen to deal with ignoring warnings is the `quiet` option which suppresses all warnings. Is it possible to add more granularity? like `quiet-ignored`?

**Comment by nzakas** [comment]
I'm not sure if it's easily possible off the top of my head. Are you using ESLint through a build tool that can configure what is passed in?

**Comment by okeydoke** [comment]
Ah yeah I'm using `grunt-eslint` which I guess passes in an array of files, not sure how to pass in an array of directories to take advantage of `--no-eslintignore` ?

**Comment by nzakas** [comment]
Let us know!

**Comment by gyandeeps** [comment]
@okeydoke is this still an issue? I am going to close this issue now but if you feel this is an issue with eslint then please feel free to open this issue back again.
