### ISSUE TITLE
Bug: Unknown options: extensions - 'extensions' has been removed.

### ISSUE THREAD

**Issue by kunalyadav684** [eslint/eslint#19151]
### Environment

Node version: 18.20.5
npm version: 10.8.2
Local ESLint version: 9.14.0
Global ESLint version: 9.14.0
Operating System: Windows

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
Getting this error with Gatsby v5.9.0
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
package.json
{
  "name": "ingka_meeting_places",
  "private": true,
  "description": "Ingka Meeting Places",
  "version": "1.0.0",
  "author": "Consid <info@consid.se>",
  "dependencies": {
    "@contentful/rich-text-plain-text-renderer": "^16.0.2",
    "@contentful/rich-text-types": "^16.0.2",
    "@elastic/app-search-javascript": "^8.5.1",
    "@elastic/react-search-ui": "^1.19.1",
    "@elastic/react-search-ui-views": "^1.19.1",
    "@elastic/search-ui": "^1.19.1",
    "@elastic/search-ui-app-search-connector": "^1.19.1",
    "@hcaptcha/react-hcaptcha": "^1.8.1",
    "@types/ua-parser-js": "^0.7.39",
    "ajv": "^8.17.1",
    "dompurify": "^3.1.7",
    "eslint-define-config": "^2.1.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "gatsby": "^5.9.0",
    "gatsby-plugin-google-tagmanager": "^5.9.0",
    "gatsby-plugin-image": "^3.9.0",
    "gatsby-plugin-postcss": "^6.9.0",
    "gatsby-plugin-react-svg": "^3.3.0",
    "gatsby-plugin-robots-txt": "^1.8.0",
    "gatsby-plugin-sass": "^6.9.0",
    "gatsby-plugin-sharp": "^5.9.0",
    "gatsby-plugin-sitemap": "^6.9.0",
    "gatsby-source-contentful": "^8.9.1",
    "gatsby-source-filesystem": "^5.9.0",
    "gatsby-transformer-inline-svg": "^1.2.0",
    "gatsby-transformer-sharp": "^5.9.0",
    "luxon": "^3.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-responsive-masonry": "2.2.0",
    "react-unity-webgl": "^9.5.2",
    "tailwind-scrollbar-hide": "^1.1.7",
    "tailwindcss-animation-delay": "^1.0.7",
    "ua-parser-js": "^1.0.37"
  },
  "devDependencies": {
    "@eslint/compat": "^1.2.3",
    "@eslint/eslintrc": "^3.1.0",
    "@eslint/js": "^9.14.0",
    "@testing-library/jest-dom": "^6.6.2",
    "@testing-library/react": "^16.0.1",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^29.2.2",
    "@types/luxon": "^3.2.0",
    "@types/node": "^22.9.0",
    "@types/react": "^18.0.28",
    "@types/react-responsive-masonry": "^2.1.0",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^8.13.0",
    "@typescript-eslint/parser": "^8.14.0",
    "autoprefixer": "^10.4.13",
    "babel-jest": "^29.2.2",
    "babel-preset-gatsby": "^3.9.0",
    "dotenv": "^16.0.3",
    "eslint": "^9.14.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-react": "^7.37.1",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-simple-import-sort": "^12.1.1",
    "gatsby-plugin-asset-path": "^3.0.4",
    "globals": "^15.12.0",
    "husky": "^9.1.6",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.2.2",
    "jest-environment-jsdom": "^29.2.2",
    "jest-fetch-mock": "^3.0.3",
    "lint-staged": "^13.1.2",
    "postcss": "^8.4.23",
    "prettier": "^2.8.4",
    "prettier-plugin-tailwindcss": "^0.2.3",
    "react-test-renderer": "^18.2.0",
    "sass": "^1.80.4",
    "tailwindcss": "^3.2.7",
    "ts-node": "^10.9.1",
    "typescript": "^5.6.3"
  },
  "overrides": {
    "gatsby-plugin-react-svg": {
      "svg-react-loader": {
        "loader-utils": "^1.4.2"
      }
    },
    "xml2js": "0.5.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "0BSD",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "develop:clean": "gatsby clean && gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md,css}\"",
    "start": "gatsby develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "test": "jest",
    "test:coverage": "jest --coverage",
    "prepare": "husky install",
    "check-types": "tsc --noEmit"
  },
  "repository": {
    "type": "git",
    "url": "https://dev.azure.com/IngkaCentresCMSPlatform/IngkaCentresCMSPlatform/_git/Web"
  },
  "browserslist": [
    "> 1%",
    "ios > 15",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "lint-staged": {
    "./src/**/*.{js,jsx,ts,tsx}": "eslint --ext .js,.jsx,.ts,.tsx --cache --fix",
    "*.{js,jsx,ts,tsx,json,md,css}": "prettier --write"
  }
}

</details>

```js
<!-- Paste your code here -->
```
eslint.config.mjs
import simpleImportSort from "eslint-plugin-simple-import-sort";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import typescriptEslint from "@typescript-eslint/eslint-plugin";
import { fixupPluginRules } from "@eslint/compat";
import globals from "globals";
import tsParser from "@typescript-eslint/parser";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default [{
    ignores: ["static/visioweb", "static/ikea-product-feed"],
}, ...compat.extends(
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:react/jsx-runtime",
    "prettier",
), {
    plugins: {
        "simple-import-sort": simpleImportSort,
        react,
        "react-hooks": fixupPluginRules(reactHooks),
        "@typescript-eslint": typescriptEslint,
    },

    languageOptions: {
        globals: {
            ...globals.browser,
            ...globals.node,
        },

        parser: tsParser,
        ecmaVersion: "latest",
        sourceType: "module",

        parserOptions: {
            ecmaFeatures: {
                jsx: true,
            },
        },
    },

    rules: {
        "simple-import-sort/imports": "warn",
        "no-console": "error",

        "no-restricted-imports": ["error", {
            patterns: ["@material-ui/*/*/*"],
        }],

        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "warn",
        "react/jsx-uses-react": "error",
        "react/jsx-uses-vars": "error",
        indent: "off",
        "linebreak-style": ["warn", "windows"],
        quotes: ["error", "single"],
        semi: ["warn", "always"],
        "react/prop-types": 0,
    },
}];

### What did you expect to happen?

The code should get compiled without any errors

### What actually happened?

The code should get compiled but I am getting this error instead

![Image](https://github.com/user-attachments/assets/cc3616fc-54d0-4d4b-bb2d-7bc6ec986b26)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/getting-started-gatsby-ljgubj?file=package.json,eslint.config.mjs,package-lock.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Note everything works fine for eslint V8.38.0 but getting this error after I upgraded version to v9.14.0, and migrated .eslintrc.json to eslint.config.mjs file. Is v9.x.x still not compatible with gatsby ?

**Comment by northbabyboy** [comment]
I also have the same issue

**Comment by nzakas** [comment]
`extensions` was never an ESLint option, that must be a Gatsby option. We only have an `--ext` option, which was [removed](https://eslint.org/docs/latest/use/configure/migration-guide#--ext). I'd recommend you open an issue with Gatsby.

**Comment by shendiid** [comment]
> `extensions` was never an ESLint option, that must be a Gatsby option. We only have an `--ext` option, which was [removed](https://eslint.org/docs/latest/use/configure/migration-guide#--ext). I'd recommend you open an issue with Gatsby.

I also have the same issue
