### ISSUE TITLE
A rule for line-endings?

### ISSUE THREAD

**Issue by vkbansal** [eslint/eslint#1915]
Is there a rule for specifying line-endings as `\n` or `\r\n` ?

**Comment by nzakas** [comment]
No. All rules are listed here: http://eslint.org/docs/rules.

If you'd like to request a rule, please read over: http://eslint.org/docs/developer-guide/contributing.html#new-rules

**Comment by lo1tuma** [comment]
We already have an issue for this: #1255.

**Comment by nzakas** [comment]
Closing as duplicate.
