### ISSUE TITLE
Template strings causing 'Unexpected token ILLEGAL'

### ISSUE THREAD

**Issue by chrisveness** [eslint/eslint#1917]
Should ES6 template strings be ok for eslint now? ([twitter suggests so](https://twitter.com/geteslint/status/558782273944694784)).

With a test.js file containing nothing but the following:

    let str = `ES6 template string`;

`$ eslint test.js` gives an error

    1:11  error  Unexpected token ILLEGAL
    
 I'm using eslint v0.15.1 on Linux Mint.

**Comment by nzakas** [comment]
Have you enabled template strings? http://eslint.org/docs/configuring/#specifying-language-options

**Comment by chrisveness** [comment]
Doh! I was googling all over for template strings, but I forgot all about the ecmaFeatures section (which I'm already using, of course).

Apologies for dumbness.
