### ISSUE TITLE
Change Request: default formatter option through `eslint.config.js`

### ISSUE THREAD

**Issue by SukkaW** [eslint/eslint#19192]
### ESLint version

9.15.0

### What problem do you want to solve?

Currently, it is only possible to specify a custom eslint formatter through CLI:

```sh
# This uses eslint built-in html formatter
eslint --format=html .

# This uses `eslint-formatter-sukka`:
eslint --format=sukka .
```

But this requires installing the custom formatter (`eslint-formatter-sukka` in this case) to every project (we don't want to *shamefully* hoist transitive dependencies, right?). 

### What do you think is the correct solution?

Add a new option to `eslint.config.js` to configure a default formatter, conceptually should look like this:

```js
// eslint.config.js
import customFormatter from 'eslint-formatter-sukka'

export default [
  {
    formatter: customFormatter
  },
];
```

Note that the `--format` cli flag should be preserved and should take priority.

### Participation

- [x] I am willing to submit a pull request for this change.

### Additional comments

This enables shipping the default custom formatter within eslint config presets.

It seems that we only need to modify the `ESLint#loadFormatter` method (which is then used by `cli.js`) to implement this feature.

https://github.com/eslint/eslint/blob/9eefc8f813b5c31f49fbbd9a36f439b365bea180/lib/eslint/eslint.js#L966

**Comment by nzakas** [comment]
The formatter is a feature of the CLI only, and as such, it can't be added into a config file.
