### ISSUE TITLE
Change Request: expand ignores default pattern with the folder 'dist'

### ISSUE THREAD

**Issue by Tamas-hi** [eslint/eslint#19193]
### ESLint version

9.15.0

### What problem do you want to solve?

As the documentation says, currently only _node_modules_ and  the _.git_ folder are ignored by default.

![Image](https://github.com/user-attachments/assets/5c3184c8-0383-4fcf-bb57-8a5552146ca9)

I was wondering if it makes sense to exclude the 'dist' folder as well by default. Is there a reason why anyone would like to lint the content there? 

For me, it falls in the same category as _node_modules_.

### What do you think is the correct solution?

Excluding dist so that there is no need for configuration from the user side.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
I'm not in favor of this proposal. `node_modules` is the standard name for folders where Node.js looks for installed packages, while `dist` is a convention so it may not have the same meaning in all projects.

@eslint/eslint-team thoughts?

**Comment by JoshuaKGoldberg** [comment]
Agreed, this is repo-specific. Some projects might use `dist/` directly. 👎 from me.

**Comment by nzakas** [comment]
Agreed, I don't think this is generic enough to include by default.
