### ISSUE TITLE
Docs: `Stylistic Rule Updates` section in README is outdated

### ISSUE THREAD

**Issue by rakleed** [eslint/eslint#19196]
### Docs page(s)

https://github.com/eslint/eslint/blob/main/README.md#stylistic-rule-updates

### What documentation issue do you want to solve?

[Formatting rules were deprecated in v8.53.0](https://eslint.org/blog/2023/10/deprecating-formatting-rules/), so the `Stylistic Rule Updates` section in README is outdated.

### What do you think is the correct solution?

Remove the `Stylistic Rule Updates` section in README.

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Formatting rules are deprecated, but there are still non-deprecated stylistic rules in the core (https://github.com/eslint/eslint/issues/18694#issuecomment-2355493603) and this section applies to them.
