### ISSUE TITLE
add exception to no-octal-escape for \0

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#1923]
`\0` is commonly used instead of `\x00` or `\u0000`. I think this particular escape sequence should be an exception to this rule.

**Comment by ilyavolodin** [comment]
By `\0` you mean NULL string right? In that case, that feels like the bug in the original rule, since it's called no-**octal**-escape.

**Comment by michaelficarra** [comment]
`0` is simultaneously in every base. Just like how it is unitless.

**Comment by nzakas** [comment]
I'm not sure I understand why this should be an exception. It is an octal literal, and if this rule is saying not to use octal literals, why is this one special?

**Comment by michaelficarra** [comment]
Because zero is special.

**Comment by nzakas** [comment]
@michaelficarra Help me out here. I'm giving you the opportunity to explain why you think this should an exception. Saying it's special doesn't add anything to your original description. If you really think this should be an exception, please take the time to explain why.

**Comment by michaelficarra** [comment]
In the grammar, `EscapeSequence` is defined as

```
EscapeSequence ::
  CharacterEscapeSequence
  0 [lookahead ∉ DecimalDigit]
  HexEscapeSequence
  UnicodeEscapeSequence
```

Section B.1.2 gives an optional extension (allowed only outside strict mode), replacing `0 [lookahead ∉ DecimalDigit]` with `OctalEscapeSequence` in the above grammar. If we disallow `OctalEscapeSequence`, we should re-allow `0 [lookahead ∉ DecimalDigit]`.

**Comment by nzakas** [comment]
Ah interesting. So what you're saying is that `\0` isn't actually an octal so it shouldn't be flagged. I agree.

**Comment by nzakas** [comment]
Working on this.
