### ISSUE TITLE
Bug: Ignored files still report Parsing Errors

### ISSUE THREAD

**Issue by mamaniv** [eslint/eslint#19247]
### Environment

Node version: 22.11.0
npm version: 10.9.0
Local ESLint version: 9.17.0
Global ESLint version: 9.17.0
Operating System: windows

### What parser are you using?

Default (Espree)

### What did you do?

As a minimal reproducer, I created a very simple node app that has only one directory: `ignore` and in it only 2 files:

/ignore/global-return.js
```
return;
```

ignore/unused-var.js
```
var unusedVar = 1;
```

Using the following `eslint.config.js`
```
'use strict';

module.exports = {
  files: ['**/*.js'],
  ignores: ['node_modules', 'ignore/**/*.js'],
  languageOptions: {
    parserOptions: {
      ecmaFeatures: {
        globalReturn: true,
      }
    },
    'ecmaVersion': 2024,
    'sourceType': 'commonjs'
  },
  rules: {
    'no-unused-vars': 'error'
  }
};
```

### What did you expect to happen?

details below

### What actually happened?

I run eslint:
```
PS C:\Dev\webapps\simple-lint> eslint ./

C:\Dev\webapps\simple-lint\ignore\global-return.js
  1:1  error  Parsing error: 'return' outside of function

✖ 1 problem (1 error, 0 warnings)
```

I expected that the `ignore` directory will be entirely ignore, but I still get an error for "return outside of function".

I can see that the ignore configuration is correct, because if I remove it, I get the following error:
```
PS C:\Dev\webapps\simple-lint> eslint ./

C:\Dev\webapps\simple-lint\ignore\unused-var.js
  1:5  error  'unusedVar' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

As you can see, the "return outside of function" surprisingly disappeared, but instead I get this unusedVar error (as expected).

### Link to Minimal Reproducible Example

Can't reproduce in the playground. See minimal reproducible example above

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

It looks like the ignore configuration works on all rules, except for parsing errors.

Is there anything wrong with my configuration or is it a bug?

**Comment by aladdin-add** [comment]
1. it should export a config array in the `eslint.config.js`.
2. In your eslint.config.js file, if an ignores key is used without any other keys in the configuration object, then the patterns act as global ignores.

the example you provided can be:

```js

'use strict';

module.exports = [
 {  ignores: ['node_modules', 'ignore/**/*.js'] },
 {
  files: ['**/*.js'],
  languageOptions: {
    parserOptions: {
      ecmaFeatures: {
        globalReturn: true,
      }
    },
    'ecmaVersion': 2024,
    'sourceType': 'commonjs'
  },
  rules: {
    'no-unused-vars': 'error'
  }
 }
];
```

**Comment by mamaniv** [comment]
It works perfectly with the global ignore. Thanks!

**Comment by mamaniv** [comment]
It works perfectly with a separated config for ignores.

Thanks!
