### ISSUE TITLE
Change Request:  Support a "staged files" mode (`--staged-files`?) that suppresses "File ignored because of a matching ignore pattern" warnings.

### ISSUE THREAD

**Issue by broofa** [eslint/eslint#19253]
### ESLint version

All of them

### What problem do you want to solve?

One of the most common use cases for`eslint` is to check files as part of `git` pre-commit hooks.  There are various tools for this: `husky`, `lint-staged`, and `lefthook`, to name a few.

These tools all work by enumerating the complete list of git-staged files as command-line arguments.  It's not uncommon for this list to include files that match an ignore pattern in eslint.  This is normal, and the expectation in this case is that eslint will simply ignore any files that match it's configured `ignore` patterns. 

Unfortunately that is not `eslint`'s current behavior.  Instead, it logs "File ignored because of a matching ignore pattern..." warnings which are (in this case) annoying and distinctly unhelpful.  Moreover, there is no simple way of "fixing" or suppressing these warnings other than to pre-filter the list of files in some way.  (Alas, this is not practicable with the tools mentioned.)

And, yes, I'm aware this issue has been raised many times before.  See also

- https://github.com/eslint/eslint/issues/17436
- https://github.com/eslint/eslint/issues/16602
- https://github.com/eslint/eslint/issues/15010
- https://github.com/eslint/eslint/issues/12249
- https://github.com/eslint/eslint/issues/9977
- https://github.com/eslint/rfcs/pull/38#discussion_r334270836

My hope is that by proposing a "staged files mode", this use case can be properly addressed

### What do you think is the correct solution?

Proposal:  Support a "--staged-files" option.  With this option enabled, `eslint` should apply the `ignores` filter to the list of CLI arguments (file paths) rather than logging warnings when a path matches one of the `ignores` patterns.

Additionally, if all CLI arguments end up being ignored, eslint should silently exit with exit code = 0.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by aladdin-add** [comment]
It seems you're looking for `--no-warn-ignored`:  https://eslint.org/docs/latest/use/command-line-interface#--no-warn-ignored ?

note: it was introduced in v8.51.0, and flat-mode-only.

**Comment by broofa** [comment]
Ooh, cool!  Didn't know that was a thing. Yeah, it looks like that solves the problem.  (Now to port to our config to flat-mode 🤦 )
