### ISSUE TITLE
Bug: lintText avoids having to look for the configuration file

### ISSUE THREAD

**Issue by Aarebecca** [eslint/eslint#19261]
### Environment

Node version: v20.13.1
npm version: v10.8.2
Local ESLint version: v9.17.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 24.1.0

### What parser are you using?

@babel/eslint-parser

### What did you do?

I developed a code inspection tool based on ESLint and configured a set of built-in eslint configuration items. It is expected not to rely on the external `eslint.config.mjs` configuration file.

However, when calling lintText, it seems to strictly require the existence of a configuration file in the working directory; otherwise, it will throw an exception.

The following is a simple example:

```js
import { ESLint } from 'eslint';

const eslint = new ESLint({
  baseConfig: [
    // base config here
  ],
  overrideConfig: [
    // override config here
  ],
  overrideConfigFile: null,
});

eslint.lintText('const foo = 1;');
```

I have reviewed the source code of ESLint. Wouldn't a better logic be to add a configuration item (such as useConfigFile: boolean) to ESLint.Options? When the value is true, skip looking for the configuration file and generate the actually used configuration items based on baseConfig and overrideConfig.

https://github.com/eslint/eslint/blob/bbb9b46c20662019e98df85dedde9b68719afa1f/lib/eslint/eslint.js#L914

The assertion (`assertConfigurationExists`) for the existence of the configuration file in `loadConfigArrayForFile` is unnecessary because the absence of the `configFilePath` is judged in `calculateConfigArray`.

https://github.com/eslint/eslint/blob/bbb9b46c20662019e98df85dedde9b68719afa1f/lib/config/config-loader.js#L341

https://github.com/eslint/eslint/blob/bbb9b46c20662019e98df85dedde9b68719afa1f/lib/config/config-loader.js#L509-L522

### What did you expect to happen?

It is expected that there can be no external eslint configuration file.

### What actually happened?

When the `eslint.lintText` method is called, it prompts `Could not find config file.`

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/lk5ttz

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
This works as intended. `overrideConfigFile: null` (default) means that ESLint will look for a configuration file.

If you want ESLint to skip looking for the configuration file, set `overrideConfigFile: true`.

> ```js
> import { ESLint } from 'eslint';
> 
> const eslint = new ESLint({
>   baseConfig: [
>     // base config here
>   ],
>   overrideConfig: [
>     // override config here
>   ],
>   overrideConfigFile: true, // <--
> });
> 
> eslint.lintText('const foo = 1;');
> ```

Now I see that the `overrideConfigFile` option isn't correctly described in the docs, and I'll prepare a PR to update the docs.
