### ISSUE TITLE
Bug: in check mode (not --fix) still logs that it's applying fixes

### ISSUE THREAD

**Issue by ORESoftware** [eslint/eslint#19284]
### Environment

Node version: v20.12.0
npm version: 10.8.0
Local ESLint version: v9.17.0
Global ESLint version: Not installed globally
Operating System: macOS 14.4.1 (x86_64)

The problem is that:

```
pnpm eslint . --debug
```

yields this:

```

  eslint:languages:js Scope analysis: /Users/alex.mills/codes/dd/dancing-dragons-next/tests/twilio/twilio-via-messaging-service.ts +0ms
  eslint:languages:js Scope analysis successful: /Users/alex.mills/codes/dd/dancing-dragons-next/tests/twilio/twilio-via-messaging-service.ts +0ms
  eslint:linter Generating fixed text for /Users/alex.mills/codes/dd/dancing-dragons-next/tests/twilio/twilio-via-messaging-service.ts (pass 1) +11ms
  eslint:source-code-fixer Applying fixes +15ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
  eslint:eslint Lint /Users/alex.mills/codes/dd/dancing-dragons-next/tests/twilio/twilio.ts +11ms
```

1. I don't want fixes applied (the log lines/text are misleading at best)
2. I want the fix recommendations logged for each file as we go

is there a flag for this ^^?

### What parser are you using?

Default (Espree)

### What did you do?

```
pnpm eslint . --debug
```

### What did you expect to happen?

n/a

### What actually happened?

n/a

### Link to Minimal Reproducible Example

https://github.com/oresoftware/dd-next

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

repo is private I cannot share

**Comment by ORESoftware** [comment]
aka, what is this?

```
  eslint:source-code-fixer Applying fixes +15ms
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
```

in other words

```
  eslint:source-code-fixer Applying fixes +15ms  # this should not be logged
  eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms  # this should not be logged for every instance since the --fix flag is not there, this is a global thing for all files, not individual files
```

furthermore - I want to see recommendations on how to fix each instance of a problem in the debug logs

**Comment by mdjermanovic** [comment]
Hi @ORESoftware, thanks for the issue! 

> eslint:source-code-fixer Applying fixes +15ms
> eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms

This works as intended. Linting enters the code path that applies fixes and exits right away.

> I want to see recommendations on how to fix each instance of a problem in the debug logs

Debug logs are for debugging purposes, and including fixes in them doesn't seem important for debugging. You can see recommendations on how to fix each instance of a problem ([`EditInfo`](https://eslint.org/docs/latest/integrate/nodejs-api#-editinfo-type) objects as the `fix` property of lint messages) by using the built-in [`json` formatter](https://eslint.org/docs/latest/use/formatters/#json).
