### ISSUE TITLE
Often skips single vs double quote check

### ISSUE THREAD

**Issue by mcandre** [eslint/eslint#1928]
I want to enforce single quotes for strings across all my JavaScript (*.js) files, but for some reason this linter is ignoring `lib/regenboog.js`.

Code:

https://github.com/mcandre/regenboog/tree/ac12033014bc08e08988ecedb461263b8005f4a4

Configuration:

```
{
  "env": {
    "node": true,
    "browser": true,
    "mocha": true,
    "jquery": true
  },
  "rules": {
    "global-strict": true,
    "no-mixed-requires": true,
    "no-unused-vars": true,
    "quotes": "single"
  }
}
```

Trace:

```
$ grunt eslint
Running "exec:eslint" (exec) task

Done, without errors.
```

**Comment by gcochard** [comment]
Try updating your rules block with the syntax example [in the docs](http://eslint.org/docs/configuring/#configuring-rules).

**Comment by nzakas** [comment]
More precisely, you are incorrectly configuring the rule. You need do this:

```js
"quotes": [2, "single"]
```
