### ISSUE TITLE
Use TryStatement handler property

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1930]
`TryStatement.handlers` became the singular `TryStatement.handler` in estree/estree#1. `no-empty` at least uses the plural `handlers`, which caused babel/babel-eslint#26. [Esprima is transitioning gradually](https://github.com/jquery/esprima/issues/1031) by supporting both `handlers` and `handler` for a time. Perhaps ESLint should check `handler` and `handlers` but deprecate the latter and remove it in [v1.0](https://github.com/eslint/eslint/milestones/v1.0.0)?

**Comment by nzakas** [comment]
Yeah, we should update Espree with `handler` and then start checking both.

**Comment by emmenko** [comment]
Found the same problem. @btmills thanks for the PR :+1:
