### ISSUE TITLE
no-unused-vars and unused parameters

### ISSUE THREAD

**Issue by spicydonuts** [eslint/eslint#1939]
Many callback-based patterns provide parameters that are not always used: browser events, node callbacks, etc.

I want to note the existance of these parameters while also indicating they will not be used, rather than completely omitting them.  Consider:

```js
input.addEventListener('keyUp', function (e) {
  console.log('key-pressed');
});
```

`e` is not used, so this is a warning.  I could remove `e`, but that hides its existance rather than indicating that I am intentionally not using it.

Here's how I do this right now:

```js
input.addEventListener('keyUp', function (_e) {
  console.log('key-pressed');
});
```

It's also common to simply name it `_` when only one parameter is unused.  This is also helpful when you want to use some parameters but not one of the ones in between:

```js
function (a, _, c) {
}
```

I don't want to completely turn off `no-unused-vars` because skipping a parameter in business logic is usually an error.

Thoughts?

**Comment by spicydonuts** [comment]
The underscore is used elsewhere for this purpose in languages where function arity has to match like Erlang and Clojure[Script].

**Comment by gyandeeps** [comment]
Did you try using different option as specified in docs.
http://eslint.org/docs/rules/no-unused-vars.html#options

**Comment by nzakas** [comment]
In this case, I'd suggest you manually disable the rule around your code:

```js
/*eslint-disable no-unused-vars*/
input.addEventListener('keyUp', function (e) {
/*eslint-enable no-unused-vars*/
  console.log('key-pressed');
});
```

**Comment by spicydonuts** [comment]
Yes, `after-used` is close but not the same.  It wouldn't work in my last snipped above, and it isn't explicit ignoring.  This is a syntax that is already used to convey "I'm not using this, but this is what it is (error, event, etc)".

**Comment by spicydonuts** [comment]
I also tried to use both `after-used` and `never`:
```yaml
  no-unused-vars:
    - 2
    - vars: all
    - args: after-used
```
```yaml
  no-unused-vars:
    - 2
    - vars: all
    - args: never
```

Neither of these removed the warning.  I ended up turning the whole thing off:

```yaml
  no-unused-vars: 0
```

**Comment by spicydonuts** [comment]
Regarding the temporary rule disabling -- those comments are way way too verbose, and I never want to encourage "just disable the rule if it's bugging you".  I'd rather turn the whole thing off.  The only exception to that for me might be some one-time hack to interop with a weird library, but I can't think of any examples of something that odd.

**Comment by spicydonuts** [comment]
If something like this was implemented it would also be an error to use a parameter that begins with an underscore:

```js
function (_err, data) {
  if (_err) throw _err; // <-- lint warning
  // ...
}
```

**Comment by spicydonuts** [comment]
This is the line that it complains about even with `args: none`:

```js
app.post('/menu', body(), function* (_) {
```

Maybe it's having issues because it's a generator function.  I also mis-typed above and said `never` instead of `none`.  I was actually using `none` as the docs indicate.

**Comment by spicydonuts** [comment]
I've confirmed that `args: none|after-used` works fine in the same file for non-generator functions.  Not sure if that bug is `eslint` domain or `babel-eslint`.

I guess this thread has both a bug and feature proposal.

**Comment by nzakas** [comment]
Try using the default parser with the `generators` flag on: http://eslint.org/docs/configuring/#specifying-language-options

If there's still an issue, then it's a bug in ESLint.

We aren't going to make changes related to a naming convention, as there is too much gray area there. It's best to use a custom rule for that.

**Comment by JedWatson** [comment]
I've been reading related issues and my PR (#2007) might help with this; you could ignore `e` as an unused argument, rather than *all* unused arguments.

It works if you hit this rule regularly on certain conventions (`e` is definitely one of those for me) and any other exceptional arguments could be wrapped in `/*eslint-disable no-unused-vars*/` if there are any.

Interested if you think that would be an improvement; perhaps my PR should allow distinct `ignore` values for `vars` and `args`.

**Comment by spicydonuts** [comment]
I don't think global ignores are a good idea.  The only place that makes sense is the `global` object.  Function parameters will always be specific.  That said, global patterns might make sense, like `/_.*/` (not sure if `_` needs to be escaped.  Or if you don't like that version you could use `/ignore.*/`, etc.

**Comment by nzakas** [comment]
We are adding a way for you to mark a variable as used in a custom rule. See #1911 for discussion.

**Comment by spicydonuts** [comment]
Does this mean you'd have to call that function all the time?

```js
e => {
  markVariableAsUsed(e);
  otherThings();
}
```

**Comment by nzakas** [comment]
Can you be more specific?

The method allows custom rules to augment how `no-unused-vars` determines which variables have been used.

**Comment by spicydonuts** [comment]
Oh, maybe I misunderstood.  How would you make a rule that ignores variables starting with `foo` that are parameters?

**Comment by nzakas** [comment]
Please take a look at our docs regarding how to create rules:
http://eslint.org/docs/developer-guide/working-with-rules.html

You'd create a new rule, find the variables you're interested in, then called `markVariableAsUsed()` on it.

We'll add some documentation around it when it's ready. Please follow #1911 for updates.
