### ISSUE TITLE
exception in no-empty.js when in a finally block with no catch clauses

### ISSUE THREAD

**Issue by blazarus** [eslint/eslint#1941]
When the no-empty rule encounters code like this:
```
try {
    ...
} finally {
   ...
}
```
It fails with the exception `Cannot read property 'length' of undefined`. It looks like the culprit is this code in no-empty.js:
```
if (/Function|CatchClause/.test(parentType) ||
        (isFinallyBlock && !parent.handlers.length)) {
            return;
}
```
which assumes that if this node is a finally block with no associated catch clauses, `parent.handlers` is an empty array, when it appears to actually be undefined.

**Comment by blazarus** [comment]
I only see this issue when using babel-eslint as the parser, so it seems like the issue is something there. Closing this issue.

**Comment by btmills** [comment]
Yep: babel/babel-eslint#26
