### ISSUE TITLE
destructuring missing in ecmaFeatures documentation

### ISSUE THREAD

**Issue by zaggino** [eslint/eslint#1942]
`ecmaFeatures: { destructuring: true }` is not mentioned in
https://github.com/eslint/eslint/tree/master/docs/configuring
but used here
https://github.com/eslint/eslint/blob/master/tests/lib/rules/block-scoped-var.js#L34-L35

**Comment by kentor** [comment]
Destructuring defaults are coming right? Looks like it was added to espree recently? Currently using destructuring defaults throw an error:
```javascript
throw new Error('Unknown node type ' + nodeType + '.')
```

**Comment by nzakas** [comment]
It should work. Make sure your using the latest version 0.16.1. If you are, please for a new issue and include sample code, your config, and the console output.
