### ISSUE TITLE
How to enable ES6 modules and what it means

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1944]
We are getting close to supporting ES6 modules, and as such, we need to figure out how to do so and what opting-in to modules means.

First, possible ways to opt-in to modules:

1. `ecmaFeatures` flag
1. Add a new `sourceType` config value that is "module" or "script" (default)
1. Create a "module" environment

The second issue is to determine what opting in to modules means. The options are:

1. Opt in to modules means only allowing import/export and toggling strict mode, but all other ES6 features require explicit opt-in.
1. Opt in to modules means opting in to all ES6 features.

What do you think?

**Comment by xjamundx** [comment]
A few use cases:

1. **Full ES6 Project** `environment: es6` (or equivalent) to turn on everything
1. **Mixed ES5/ES6 project** Maybe some `.es6` and some `.js` files. May want a common non-ES6 module format for consistency. `environment: es6` (or equivalent) is still probably fine though.
2. **IO.js users** CJS modules + a few other things. `ecmaFeatures: {}` should be acceptable.
3. What other use cases are likely?

I think in a few months time more and more people are going to be in the first camp, so that should be the primary way to enable things. 

Not sure if a specific way to handle modules outside of `ecmaFeatures` is really needed....*shrugs*

**Comment by calebboyd** [comment]
One and one look like good options to me, and they are in tune with how the other language features operate. Also, as suggested, a single es6 flag would be pretty handy.

**Comment by nzakas** [comment]
We will have an ES6 environment, but you can use ES6 without using ES6 modules. 

This issue is about how to support modules, so let's keep on that topic.

**Comment by juandopazo** [comment]
Is a flag really necessary? Could opting-in be done by using `import` or `export`?

I think ideally ESLint should check that the when module A imports from module B, the imports in A match the exports in B.

**Comment by nzakas** [comment]
@juandopazo unfortunately that won't work. Modules are strict mode by default, and that changes how the parser works and how we calculate errors. So you need to say up front that you're using a module in order for anything to be accurate (this is true for loading modules in browsers as well, it will need to be explicitly stated on the `<script>` element that it's a module).

**Comment by juandopazo** [comment]
@nzakas Import/export statements are top level only. Can that be used to do some lightweight checking without running the whole parser?

**Comment by xjamundx** [comment]
@nzakas that explains the need to have a special `sourceType`. I was thinking it could be handled (in espree) more like `use strict`, but I see now that won't work. I'm fine with a `sourceType` option explicitly enabling `module` mode (just the strict stuff). Unclear if we need a separate `ecmaFeatures` option for modules if that's the case.

**Comment by nzakas** [comment]
@juandopazo no. A naive `indexOf()` search would be inaccurate due to comments and strings containing those words, and there's no guarantee that `import` or `export` will end up at the top of a file. So even if we only parsed up until `import` or `export` was found, we still could end up parsing almost the entire file before we find them. In short, there's no error-proof way to do any sort of automatic determination as to whether or not a file is an ES6 module or not.

@xjamundx I'm leaning against adding `sourceType` to ESLint at the moment. The more I look at it, the more it seems like it's overkill for a single use case. Maybe it makes sense to have an `es6` environment and then allow people to toggle `modules` in `ecmaFeatures` as opposed to having a `module` environment. The downside to that is that environments can be toggled with comments inside of files while `ecmaFeatures` cannot.

**Comment by caridy** [comment]
> I think ideally ESLint should check that the when module A imports from module B, the imports in A match the exports in B.

This is not possible because the module specifier can be anything (`string` value), and ESLint will not know how to resolve it to verify that the exported definition exists. This can only be done during the runtime, or thru a build process that knows how to resolve files for bundling or folding.

**Comment by juandopazo** [comment]
@caridy why can't we hook a resolver into ESLint?

**Comment by nzakas** [comment]
@juandopazo this is outside the scope of ESLint. We deal only with one file at a time so we don't have any other knowledge to rely on.

Note that this issue is about how to opt-in to module support for ESLint, so let's keep the discussion on that topic.

**Comment by juandopazo** [comment]
I don't want to derail the thread, but I find it sad that we're dismissing the option because it's relatively uncomfortable to solve. Modules are static. We should be able to leverage that.

**Comment by nzakas** [comment]
@juandopazo if you want to go off and investigate how to do this efficiently and report back with results, I'll be happy to review it. Send a PR when you're ready and we can review it.

**Comment by nzakas** [comment]
Okay, so here's my current thinking on how to support modules:

1. You can enable just `import` and `export` via `ecmaFeatures.modules` (this will also put the parser into strict mode).
1. We'll have an `es6` environment that enables all ES6 `ecmaFeatures` *except* `modules`.

Thoughts?

**Comment by xjamundx** [comment]
1. :+1: 
2. I think this is the most flexible for the most use cases, however I do think some people may get confused having to set 2 flags for es6 and modules.

Overall I'm definitely :+1 to something :)

**Comment by caridy** [comment]
:+1:

**Comment by doberkofler** [comment]
I'm good with this solution but do yet not understand why it is important to enable all es6 features except modules?

**Comment by pesho** [comment]
> We'll have an es6 environment that enables all ES6 ecmaFeatures except modules.

I don't get it. Why require a separate flag for modules? They are part of ES6 just like the others. IMO `environment: es6` should enable all ES6 features, including modules. If you only want a subset, cherry-pick it via `ecmaFeatures`.

> We will have an ES6 environment, but you can use ES6 without using ES6 modules.

Yes, and you can also use ES6 without generators, or without arrow functions, or without template strings. What makes modules special here?

**Comment by xjamundx** [comment]
@pesho I think what makes modules special is the fact that they have different rules than other ES6 things. You can opt-in to generators without changing the way the rest of the codebase works, because modules are implicitly strict. I imagine the io.js team for example will want most/all of ES6, but will continue to use CJS modules. They might be very against the `"use strict"` requirement of module mode. I assume this separation is in deference to people that don't want to apply that......time will tell if it's a good default, and maybe something will change, but for now it's probably the most flexible combination.

**Comment by pesho** [comment]
@xjamundx why would iojs be against "use strict"? Their core modules _are_ using "use strict" ([example](https://github.com/iojs/io.js/blob/v1.x/lib/fs.js)).

It doesn't seem right if `environment: es6` didn't enable _all_ of ES6. If there are valid reasons to want ES6-minus-modules (I'm not convinced so far), this would be better served by a separate environment, e.g. `environment: es6WithoutModules`.

**Comment by nzakas** [comment]
@doberkofler @pesho as @xjamundx mentioned, ES6 modules are *not* just new syntax, they actually change the way the parser works. This is why you can't use modules natively anywhere right now. Neither browsers nor Node have decided how to let you opt in to using modules.

However, both browsers and Node (io.js) allow other ES6 syntax because it doesn't change how the parser works.

In any event, you can always add enable module support directly in ESLint. So it's not like you can't use them, we are just asking you to explicitly opt-in to avoid unnecessary errors.

**Comment by fczuardi** [comment]
The commit that closes this bug adds an environment that "enable all ECMAScript 6 features except for modules." and the title of this bug is "How to enable ES6 modules and what it means".

So, I am a little confused about how to enable ES6 modules in the config... are there ecmaFeatures attributes for import / export? If I use the "es6" environment, that says explicitly in the README that doesnt enable modules feature, will eslint treat the import keyword as an error?

**Comment by nzakas** [comment]
You need to use `ecmaFeatures.modules` to enable modules. Without it, `import` and `export` are syntax errors. So if you want modules plus all ES6 features, then you'd use the `es6' environment plus `ecmaFeatures.modules`.

**Comment by fczuardi** [comment]
great! thanks!
