### ISSUE TITLE
Rule suggestion : disallow the use of continue statement

### ISSUE THREAD

**Issue by ptitgraig** [eslint/eslint#1945]
Hello.

I'd like your input about a rule suggestion I've seen in SonarQube JavaScript plugin.
The rule aims at be disallow the use of continue statement.

Explaination below :
>The use of the "continue" branching statement increase the essential complexity of the source code and so prevent any refactoring of this source code to replace all well structured control structures with a single statements.

Regards

**Comment by ilyavolodin** [comment]
This is also mentioned in #667 as a rule 25.
