### ISSUE TITLE
eslint 0.15.1 is backwards incompatible with 0.15.0

### ISSUE THREAD

**Issue by sam-github** [eslint/eslint#1953]
`no-comma-dangle` appears to have changed to `comma-dangle`, though I don't see that in the release notes.

Perhaps its time to adopt semver?

**Comment by lo1tuma** [comment]
That is not true, the change was not made in eslint 0.15.1, it is only on current master and will land in the next version of eslint.
Additionally we didn’t remove `no-comma-dangle`, we just marked it as deprecated. It will be removed in eslint version 1.0.
