### ISSUE TITLE
Investigate using npmlog for logging and crash reports

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1961]
npm has a nice logger that caches log messages so you can output a crash report when an error occurs. It would be nice to have similar functionality in ESLint since people tend to report crashes without any additional information.

Here's how npm does it:
https://github.com/npm/npm/blob/master/lib/utils/error-handler.js

**Comment by alberto** [comment]
Superseded by https://github.com/eslint/eslint/issues/5221
