### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1988]
Current master is at 3bf1511f37.

I'm noticing 8 failures across core, `no-undef`, and `no-unused-vars`. Haven't investigated the cause yet.

**Comment by btmills** [comment]
Sorry, false alarm. Needed to `npm i` to get the new `escope` version after pulling latest changes.

**Comment by nzakas** [comment]
No worries, I've done the same thing a lot of times. :)
