### ISSUE TITLE
Cache rule added information for eslint.org

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#2003]
When generating eslint.org, we go through and check each rule to see when it was added to ESLint, and then we append that info to the documentation. This process takes a really long time (minutes, not seconds), to get data that essentially doesn't change.

Instead of regenerating this data with each release, we should cache the information in a file and look it up from there first, only hitting git if it's not already in the file, and then adding it to the file.

**Comment by lo1tuma** [comment]
This is probably a problem with shelljs and the [`execSync` hack](https://github.com/arturadib/shelljs/blob/b542e4d021f45a8121bf14491515a4c1452425af/src/exec.js#L8-L12).
Related: https://github.com/arturadib/shelljs/issues/167

**Comment by nzakas** [comment]
Even so, there's still no reason to recheck when each rule was added.

**Comment by ilyavolodin** [comment]
Closing this for #2475 as that one is more generic
