### ISSUE TITLE
Document exception types for no-multi-spaces

### ISSUE THREAD

**Issue by gabrielecirulli** [eslint/eslint#2006]
I'm having a lot of trouble getting eslint to accept this sort of code:

```javascript
var _     = require("lodash");
var React = require("react");
var _s    = require("underscore.string");
```

In our codebase we try to align declarations where it makes sense. My idea would be to make `eslint` ignore this situation while still keeping the benefits of `no-multi-spaces`, but I can't figure out what I'm supposed to ignore. The only example and documentation I can find is for `Property`, but that's for objects.

As far as I can tell this goes into parser territory and you should just look at the parent of the current expression (as the code does), but I can't really infer what that would be without a deep knowledge of the parser, which I don't have.

Here's my suggestion: can there be documentation of the most common types of things you might want to ignore?

Alternatively, why not make `no-multi-spaces` output the type of the parent node every time, so that if you want to add it to an exception you can do so directly?

**Comment by gabrielecirulli** [comment]
Well, I hacked eslint just now to print the parent type and it turned out to be `VariableDeclarator`. It turns out the idea could have been useful after all :smile: 

If anyone's interested, I can just submit a pull request to do something like this.

**Comment by ilyavolodin** [comment]
Instead of hacking ESLint code, you can use this: http://esprima.org/demo/parse.html

**Comment by nzakas** [comment]
@gabrielecirulli what is it you're asking for with this issue?

**Comment by gabrielecirulli** [comment]
@ilyavolodin thanks, but it was much easier to see when eslint was outputting the type of the node.

@nzakas simply for eslint to also print the type of parent node that it's encountering when it complains about no-multi-spaces, since that would be the keyword to use when you want to add an exception for that specific node.

**Comment by nzakas** [comment]
Can you give an example message you'd like to see?

**Comment by gyandeeps** [comment]
closing this as we have not received any feedback.
Feel free to reopen.
