### ISSUE TITLE
Has spread operator parsing been removed?

### ISSUE THREAD

**Issue by yazdog8** [eslint/eslint#2008]
In version 0.15.0 spread: true was enabled as a configurable parameter. We're now running 0.16.0 and we're getting this error with the following function.

"error  Unexpected token .."

The function is:
```
$scope.$on('$locationChangeSuccess', function(...args) {
                let [,toState, fromState] = args;

                if (toState.includes(wdsConfig.states.browse) && fromState.includes(wdsConfig.states.browse)) {
                    setStateParams();
                    submitSearch();
                }
            });
```

This was working with the 0.15.0 version and now the spread option doesn't seem to be in your documentation on the configuring page:

http://eslint.org/docs/configuring/

On the espree github page, the spread: true is there in the documentation:

https://github.com/eslint/espree

Am I missing something? Has this changed or been removed? As far as I can tell I'm using the spread properly in this instance.

**Comment by nzakas** [comment]
That's not the spread operator, it's `defaultParams`. Do you have that enabled?

**Comment by yazdog8** [comment]
Yes, we do.

**Comment by nzakas** [comment]
Can you share your config file?

**Comment by yazdog8** [comment]
Would be happy to.

{
    "ecmaFeatures": {
        "arrowFunctions": true,
        "blockBindings": true,
        "classes": true,
        "defaultParams": true,
        "destructuring": true,
        "forOf": true,
        "generators": true,
        "objectLiteralComputedProperties": true,
        "objectLiteralDuplicateProperties": true,
        "objectLiteralShorthandMethods": true,
        "objectLiteralShorthandProperties": true,
        "spread": true,
        "superInFunctions": true,
        "templateStrings": true
    },
    "rules":{
        "strict": 2,
        "no-dupe-keys": 1,
        "no-empty": 2,
        "no-empty-class": 2,
        "no-extend-native": 2,
        "no-trailing-spaces" : 0,
        "no-eval": 2,
        "eqeqeq": 2,
        "no-else-return": 2,
        "no-caller": 2,
        "block-scoped-var": 0,
        "no-lone-blocks": 2,
        "no-script-url": 2,
        "no-self-compare": 2,
        "no-unused-vars": 1,
        "no-undef-init": 1,
        "brace-style": ["2", "1tbs"],
        "camelcase": 2,
        "no-nested-ternary": 1,
        "no-space-before-semi": 1,
        "new-parens": 2,
        "quotes": 0,
        "no-underscore-dangle": 2,
        "eol-last": 0,
        "no-mixed-spaces-and-tabs": 0,
        "semi": [2, "always"],
        "key-spacing":0,
        "comma-spacing":0,
        "no-multi-spaces":0,
        "no-shadow":0
    },
    "globals": {
        "jQuery": false,
        "$": true,
        "angular": true,
        "_": true,
        "kendo": true,
        "moment": true,
        "countdown": true,
        "cytoscape": true
    },
    "env":{
        "browser": true
    }
}

**Comment by nzakas** [comment]
Oops, I mistyped. You should enable `restParams`, which is missing from your config.

**Comment by yazdog8** [comment]
That fixed it! Thanks!

**Comment by nzakas** [comment]
I also added `spread` into the docs so it will end up on the site with the next release.
