### ISSUE TITLE
`Unexpected token` on Object destructuring assignment

### ISSUE THREAD

**Issue by pascalduez** [eslint/eslint#2010]
```js
let { foo, bar } = baz();
```
```
20:23  error  Unexpected token =
```

**Comment by ivanoats** [comment]
I get this error too:
`const { isDragging } = this.getDragState(ItemTypes.CARD);`

**Comment by nzakas** [comment]
Do you have `destructuring` enabled in your config file?

**Comment by ivanoats** [comment]
oops, that fixed it, thanks!

**Comment by pascalduez** [comment]
Dang! How can I have missed that rule... Sorry.

But now with that enabled I get the same Error as is babel/babel-eslint#47 
Which is happening when you export an unnamed function.

`export function () { ... }`

**Comment by pascalduez** [comment]
Okay so it's the same issue as in #1985
