### ISSUE TITLE
Rule to sort properties in object literal

### ISSUE THREAD

**Issue by jacobrask** [eslint/eslint#2017]
Similar to `sort-vars`, how about a rule to always sort object properties alphabetically when defining an object literal?

It would be really useful for things like options objects. I realize that the property order can matter in iteration, but it's nothing you should rely on anyway. With the new ES6 data structures, I think the use case for object literals is shrinking to be a lot about options objects, including in native APIs.

You could argue that it will cause a huge number of warnings in existing code and thus not be useful at all. I'm not completely sure, I just know that I often use vim's `sort` command, but it doesn't work well if a property value spans several lines.

Warnings:

    var obj = {
      c: "foo",
      a: "bar",
      b: {
        e: 1,
        d: 2,
      }
    };

OK:

    var obj = {
      a: "bar",
      b: {
        d: 2,
        e: 1,
      },
      c: "foo",
    };

**Comment by nzakas** [comment]
As with all rule suggestions, the important question is if this is necessary as part of the core or if it is better as a plugin? And is this a rule you would use personally?

Right now we are focused very heavily on ES6 support, so new rules are very low purity.

**Comment by jacobrask** [comment]
I see. I will look into writing a plugin and we could evaluate the usefulness of the feature.

**Comment by jacobrask** [comment]
[eslint-plugin-sorting](https://github.com/jacobrask/eslint-plugin-sorting)

Thanks for making it dead easy to write plugins to ESLint.

**Comment by nzakas** [comment]
Sure thing! Part of why we did that was so people didn't need to wait around for us to implement every rule they want. :) Nice work!

**Comment by gajus** [comment]
@jacobrask Thank you for making the plugin.

@nzakas I am struggling to see how is this different from http://eslint.org/docs/rules/sort-vars. Feels like it should be part of the core.

**Comment by gajus** [comment]
@nzakas Now that https://github.com/jacobrask/eslint-plugin-sorting has somewhat matured, is it worth it to consider adding it to the core?

**Comment by mherodev** [comment]
Just went hunting for this -- seems like core material.

**Comment by Gopikrishna19** [comment]
http://eslint.org/docs/rules/sort-keys from eslint 3.3.0 on :)
