### ISSUE TITLE
Documentation lacking for plugin rules configuration

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2022]
Currently, documentation doesn't include anything about configuring rules that came from plugins, only how to include plugins themselves. Documentation for including plugins states that you can either use plugin name or prefix with plugin name. So "eslint-plugin-test" and just "test" will do the same. Since no documentation is provided for setting plugin's rules, one can easily assume that the same rules apply for "rules" part of configuration, however, that's not true. Only plugin name (without prefix) can be used. So the following rules section will not do anything:

```json
"rules": {
  "eslint-plugin-test/somerule": 2
}
```
P.S. Was this intentional? Not missing documentation, but functionality? This feels like an oversight. cc @lo1tuma

**Comment by xjamundx** [comment]
That's something I previously found confusing as well. I bet we can do something about to improve it :)

**Comment by lo1tuma** [comment]
Yes, this functionality was intentional, see https://github.com/eslint/eslint/issues/1106.

> ### Configuring rules
>
> In order to configure plugin rules, use the plugin name (minus the "eslint-plugin-") plus the rule ID separated with a slash (such as jquery/dollar-sign).

I agree that it can be confusing, so we should definitely document this.

**Comment by nzakas** [comment]
:+1:

**Comment by nzakas** [comment]
Working on this.
