### ISSUE TITLE
Per-Directory .eslintrc

### ISSUE THREAD

**Issue by krnlde** [eslint/eslint#2026]
Hey guys,
I'm having trouble with eslint when linting server side es6 together with client side es5 using only one `.eslintrc` for both. The ruleset has to be different per directory. I tried creating multiple `.eslintrc`s within those dirs with the effect of having applied the default [ruleset](/eslint/eslint/blob/master/conf/eslint.json) instead of the expected files.

Am I missing something or is this simply the wrong way to use eslint?

**Comment by krnlde** [comment]
According to #963 it should work.

**Comment by nzakas** [comment]
You can use a different `.eslintrc` per directory, however, the configurations cascade. So a subdirectory configuration will be combined with the configuration found in its parent directory's `.eslintrc`. See: http://eslint.org/docs/configuring/#configuration-cascading-and-hierarchy

If you're still having trouble, please contact eslint@googlegroups.com

**Comment by krnlde** [comment]
Thanks @nzakas That's what I tried. But for some reason eslint didn't pull those files. I reinstalled eslint (I was using v0.15) and now it behaves like described :) Again, thanks for your assistance.

**Comment by ryb73** [comment]
Updated version of @nzakas's link for anyone interested: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
