### ISSUE TITLE
no-new description text is inaccurate/confusing

### ISSUE THREAD

**Issue by UltCombo** [eslint/eslint#2044]
Quoting the [no-new description](http://eslint.org/docs/rules/no-new.html):

> Calling constructors with the `new` keyword, without assigning the resulting object to a variable does is equivalent to simply calling the constructor without the `new` keyword. Thus, the constructor can be avoided and the function can be called directly.

This is simply untrue, more-so considering 3rd party APIs that you don't know the implementation thereof.

Consider:

```js
function Thing() {
	if (this instanceof Thing) { /*do the awesome*/ }
	else throw new Error('Called without `new`');
}

Thing();
```

Or, a slightly less contrived example:

```js
//
// 3rd party lib implementation
//
function Thing() {
	this.initDefaults();
}
Thing.prototype.initDefaults = function() {/**/};

//
// Invalid API consumption without `new`:
//
Thing(); // throws because the `this` binding inside of the constructor
         // resolves to the global object and not an instance of Thing.
```

**Comment by nzakas** [comment]
Yeah, I get what the author was trying to say, but is definitely a bit misleading.

**Comment by UltCombo** [comment]
Nice fix, thanks. :smile:
