### ISSUE TITLE
complexity rule doesn't understand ES6 class function names

### ISSUE THREAD

**Issue by lencioni** [eslint/eslint#2049]
In an ES6 class that fails the `complexity` rule, e.g.:

```js
class MyClass {
  foo() {
    ...
  }
}
```

I get the message:

> Function 'anonymous' has a complexity of N (complexity)

It would be better if this message (and likely others) included the function's name instead of "anonymous".

**Comment by nzakas** [comment]
Yeah, I think this is one of those rules that hasn't been touched in a long time.

**Comment by nzakas** [comment]
Working on this.
