### ISSUE TITLE
yoda range fails on 'this' reference

### ISSUE THREAD

**Issue by chrisveness** [eslint/eslint#2063]
Using a rule

    "yoda": [ 2, "never", { "exceptRange": true } ]

and given the code

    if (1<=this.prop && this.prop<=10) console.log('ok');

ESLint (v0.17.0) fails with *Expected literal to be on the right side of <=* (it should pass).

I suspect this might be in `lib/rules/yoda.js: function same(a, b)`: for the above example, `a.type` comes through with `ThisExpression` which is not covered in the switch expression.

**Comment by nzakas** [comment]
Yup, will take a look.

**Comment by btmills** [comment]
Easy fix: #2073

**Comment by chrisveness** [comment]
I wondered if it might be so simple as this, but wasn't confident enough to offer a PR!
