### ISSUE TITLE
Consider saving exact Espree version as dependency

### ISSUE THREAD

**Issue by davidtheclark** [eslint/eslint#2070]
Maybe there's a good reason to use the caret -- but I just had a little bit of annoyance caused by that caret that would have been prevented with an exact dependency, so I thought I'd file an issue for your considerations.

I tried updating to from ESLint 0.16.2 to 0.17.0; and a number of bugs (already filed) meant that this update broke my build, so I had to revert back to 0.16.2. However, at least one of these bugs was a problem with Espree, not ESLint, introduced with Espree v0.12.0. Because ESLint's dependency used the caret, even reverting back to 0.16.2 didn't get this bug out of my hair: the newer (buggy) Espree was still installed. So I had to install and save Espree 0.11 in my own setup. Now, when these bugs are fixed I will have to remember to remove Espree from my dependencies before I update ESLint.

Does this make sense? It's a little convoluted, but that's kind of the point: this kind of issue could be done away with by saving the exact Espree version. Just something to consider. Thanks.

**Comment by nzakas** [comment]
Thanks, need to think this through because it cuts both ways (you can get bug fixes to Espree without waiting for an ESLint upgrade).

As far as I can tell, the only Espree regression had to do with JSX + template literals. Was there something else that broke for you?

**Comment by davidtheclark** [comment]
Yep, I'm pretty sure the bug I was encountering was this one: https://github.com/eslint/eslint/issues/2045 And that's all I'm aware of.

You're right about the benefit of the caret for updating Espree independently.

**Comment by nzakas** [comment]
I think we are going to stick with what we have for now. We will keep an eye out for more issues like you mention.
