### ISSUE TITLE
inline disable es6 & modules

### ISSUE THREAD

**Issue by t128** [eslint/eslint#2072]
hi,

is there an inline config for disabling all es6 features (including modules)?

i tried:
```
/* eslint ecmaFeatures: [] */
/* eslint ecmaFeatures: {} */
/* eslint-ecmaFeatures modules: false */
/* eslint-env es6: false */
/* eslint es6: false */
/* eslint modules: false */
/* eslint-disable es6 */
/* eslint-disable modules */
```

**Comment by nzakas** [comment]
You can do `/*eslint-env es6:false*/` if you're using the `es6` environment, but if you are manually enabling `ecmaFeatures` in your config file, that won't work.

**Comment by t128** [comment]
so, when i have 100 es6 files one es5. i have to enable es6 in that 100 files instead of just being able to disable it in that one?

**Comment by nzakas** [comment]
As I said, you can disable ES6 support using `/*eslint-env es6:false*/` provided that you are also enabling it using the `es6` environment.

**Comment by t128** [comment]
ok, but how to disable modules (as it is not enabled with env: es6, so i **have** to enable it with ecmaFeatures)?

**Comment by nzakas** [comment]
We don't have a way of doing that currently. It's a bit dicey because it changes how the parser works. Can you move the one ES5 file into a different directory?

**Comment by t128** [comment]
actually is that one file already in an other director? Are the configs i do in the parent eslintrc file inherited by an eslintrc file in a child directory?
that way i could easily disable it in that one directory, but keep the other configs.

**Comment by nzakas** [comment]
Yup, configs cascade. See: http://eslint.org/docs/configuring/#configuration-cascading-and-hierarchy

**Comment by t128** [comment]
Am 16.03.2015 um 23:31 schrieb Nicholas C. Zakas:
> Yup, configs cascade. See: http://eslint.org/docs/configuring/#configuration-cascading-and-hierarchy
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/eslint/eslint/issues/2072#issuecomment-81967690
> 

wow, thank you
