### ISSUE TITLE
new-cap rule could accept "Error" as an exception

### ISSUE THREAD

**Issue by mickaeltr** [eslint/eslint#2098]
Hello,

Currently, the "new-cap" rule has a property "capIsNewExceptions" which defaults to the following value: 
["Object", "Function", "Number", "String", "Boolean", "Date", "Array", "Symbol", "RegExp"]

What do you think about adding "Error" to this list?

Cheers

**Comment by michaelficarra** [comment]
:+1:

**Comment by nzakas** [comment]
Sounds good.
