### ISSUE TITLE
Illegal import declaration

### ISSUE THREAD

**Issue by razagill** [eslint/eslint#2112]
Just updated to 0.17.1 and still getting the error: `Illegal import declaration` on the following line.
```javascript
import request from 'superagent';
```

And here is my .eslintrc

```javascript
{
  "ecmaFeatures": {
    "jsx": true
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "rules": {
    "strict": 0,
    "no-underscore-dangle": 0,
    "quotes": [
      2,
      "single"
    ]
  }
}
```

**Comment by nzakas** [comment]
You need to enable modules via `ecmaFeatures: { modules: true }`

**Comment by razagill** [comment]
Damn, totally forgot. Thanks!

**Comment by stofte** [comment]
Came here from Google, so in case it helps anyone else, I'll add that my problem was the parser `esprima-fb`, when using `babel-eslint` the error went away.

**Comment by joezimjs** [comment]
```json
{
    "parser": "babel-eslint",
    "env": {
        "browser": true,
        "node": true,
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true
    },
    "rules": {
    }
}
```

That's what I have and I still keep seeing "Illegal import declaration" and "Illegal export declaration" for all of my files. I just installed everything yesterday, so it should be up-to-date. I've tried several different ways of doing ES2015 imports and exports (e.g. named vs default exports, etc.), but I'm still getting the errors.

**Comment by IanVS** [comment]
Have you tried using the default parser?  (Remove the `"parser": "babel-eslint",` line).

**Comment by joezimjs** [comment]
Yea I tried the default parser. I found the issue. I was using gulp-eslint, which doesn't directly support the parser option in the configuration unless pulling the configuration from a file. Apparently this is because the eslint API doesn't accept a parser: https://github.com/adametry/gulp-eslint/issues/39

**Comment by IanVS** [comment]
There is an accepted issue (https://github.com/eslint/eslint/issues/3127) to add parser selection to the CLI (and therefore CLIEngine).  If this is important to you, please consider submitting a pull request.

**Comment by jedwards1211** [comment]
I'm getting these errors on `.js` files, and when I rename the `.js` files to `.jsx` the errors go away.  Should it matter?

**Comment by yairEO** [comment]
I'm also here because of the GULP plugin. I really need this to work, please somebody do a PR or something, I have no sufficient knowledge with NPM packages to help here

**Comment by platinumazure** [comment]
@yairEO We've fixed #3127 already-- do you know what else might be needed to make this work for Gulp? Is there an issue on gulp-eslint which tracks remaining work here?

**Comment by yairEO** [comment]
@platinumazure - I just opened a new issue, hope this will be solved. not sure how though..

https://github.com/adametry/gulp-eslint/issues/110

**Comment by IanVS** [comment]
In the last two weeks, there have been nearly 650 people visiting this issue, which makes it one of the top most-viewed pages in this repo.  I'm curious, could someone explain why this issue is so popular?

**Comment by joezimjs** [comment]
@IanVS I think the big issue is that the documentation doesn't make it clear that the babel-eslint parser is required when using ES2015 modules. Though, I haven't upgraded to Babel 6 yet, so it may also need some changes after that?

**Comment by nzakas** [comment]
@joezimjs you don't need to use babel-eslint, as I stated in the first comment: https://github.com/eslint/eslint/issues/2112#issuecomment-83633766

**Comment by joezimjs** [comment]
It never worked for me without babel-eslint

**Comment by nzakas** [comment]
ESLint natively supports all of ES6, you don't need babel-eslint for any of it. Just make sure you remember the correct `ecmaFeatures`. If you still get an error, then chances are your using a syntax that only Babel supports (and is therefore not standard ES6).

**Comment by brettz9** [comment]
I found I was getting the error (even with `"ecmaFeatures": {"modules": true}`) within a closure:

```js
(function () {
    import * as math from 'math';
    alert('2π = ' + math.sum(math.pi, math.pi));
})();
```

...but not when the import was outside of the closure.

**Comment by ilyavolodin** [comment]
@brettz9 imports are only valid in the top level scope. Babel allows you to do them in the inner scopes, but that's incorrect and doesn't adhere to the es6 spec.

**Comment by brettz9** [comment]
Thanks, @ilyavolodin  . Hopefully this may identify issues for others here, as I wasn't otherwise sure that this placement issue would fall under "a syntax that only Babel supports".

**Comment by hzoo** [comment]
Babel only allows it with parser option: `allowImportExportEverywhere` set to true

**Comment by orangewise** [comment]
this works for me:

```
"parserOptions": {
     "ecmaVersion": 6,
     "sourceType": "module"
}
```

**Comment by DelvarWorld** [comment]
The above doesn't work with babel 6: `Unknown option: .babelrc.ecmaFeatures.`. Still investigating

**Comment by ilyavolodin** [comment]
@DelvarWorld Those are configuration for ESLint, not babel, so they should go into your .eslintrc file.

**Comment by zhanfenghai** [comment]
@IanVS i got the same problem ,i have see the the answers upstairs，but not work
![image](https://cloud.githubusercontent.com/assets/18130809/18429369/7be5a57e-7905-11e6-9712-5d050ae7c9cb.png)

**Comment by snnsnn** [comment]
After adding `"ecmaFeatures": {
      "jsx": true,
      "modules": true
    }` you may need to restart your editor. It fixed my problem..

**Comment by Hancoson** [comment]
![image](https://cloud.githubusercontent.com/assets/5474666/24190252/12e697ae-0f23-11e7-8868-6c5f3d936f0b.png)
What's the problem,please?

**Comment by vitorbal** [comment]
@Hancoson can you open a new ticket or come by our [ESLint Gitter](https://gitter.im/eslint/eslint)? Thanks!

**Comment by Hancoson** [comment]
@vitorbal  Good! Thank you

**Comment by pornel** [comment]
If anyone with Sublime Linter is seeing this error:

It's caused by configuration of Sublime Linter: files with `.jsx` file extension are handled by jsxhint, rather than eslint. This can be fixed in user config of sublime linter by changing `syntax_map` to map `jsx` to `javascript` (and restart the editor).

**Comment by titouandk** [comment]
I had that error, because my eslint config file was named `.eslintrc.json` instead of `.eslintrc`
