### ISSUE TITLE
ES6 arrow function and no-wrap-func

### ISSUE THREAD

**Issue by t128** [eslint/eslint#2113]
hi

```js
opts.ease = opts.ease || a => a * a * a
```
results in:
```
 error  Unexpected token =>
```

so i tried:
```js
opts.ease = opts.ease || (a => a * a * a)
```
this results in:
```
error  Wrapping non-IIFE function literals in parens is unnecessary  no-wrap-func
```

i think, we need an exception for arrow functions in the *no-wrap-func* rule, especially the rule is enabled by default.

**Comment by nzakas** [comment]
Will need to double-check that the parser is doing the right thing here, as well.

**Comment by michaelficarra** [comment]
It appears to be.

**Comment by nzakas** [comment]
Working on this.
