### ISSUE TITLE
Disable plugin with comments

### ISSUE THREAD

**Issue by Znarkus** [eslint/eslint#2118]
Hi!

I want to disable a plugin or disable the plugin rules with a comment. I'm using the an angular plugin, but it shouldn't be enabled for some cli files. Is this possible? :)

Suggestions:

- `/*eslint-plugins node*/`
- `/*eslint-disable-plugin angular */`

**Comment by nzakas** [comment]
No. You need to disable the plugin rules directly:

```js
/* eslint-disable angular/rule1, angular/rule2 */
```

**Comment by jrencz** [comment]
The syntax might be

```js
/* eslint-disable angular/* */
```
