### ISSUE TITLE
no-lone-blocks: the description doesn't match ES6 reality

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint#2119]
From http://eslint.org/docs/rules/no-lone-blocks.html:
"In JavaScript, standalone code blocks delimited by curly braces do not create a new scope and have no use."

That's not true for `const`/`let`/`function` in ES6. Now that ESLint supports ES6, the description should be fixed. Also, does it make sense to keep it on by default in ES6 mode since the rationale now doesn't apply?

**Comment by nzakas** [comment]
Yeah, the docs should be fixed. We should probably also change the rule so that it only warns if there's no block binding inside the curlies.

You can still have useless lone blocks in ES6, it would just be a block without a block binding, so I'd still keep it on provided we make that adjustment.

**Comment by mzgol** [comment]
> You can still have useless lone blocks in ES6, it would just be a block without a block binding, so I'd still keep it on provided we make that adjustment.

Yes, in that case the rule would still be useful even in ES6.

**Comment by jrvidal** [comment]
Working on this
