### ISSUE TITLE
ES6 catch destruct and this assignment

### ISSUE THREAD

**Issue by jupl** [eslint/eslint#2125]
Given the following snippet, an error is noted on line 6 with the message `Do not assign to the exception parameter.` due to `no-ex-assign`. If destructuring on `catch` is not used, no error occurs.

```js
function x(next) {
  try {
    y();
  }
  catch({stack}) {
    this.something = 4; // ESLint error
    next = 4;
  }
  return next;
}
```

**Comment by nzakas** [comment]
Working on this.
