### ISSUE TITLE
should.js no-unused-expressions

### ISSUE THREAD

**Issue by willin** [eslint/eslint#2129]
iojs 1.6.1
eslint 0.17.1
should 5.2.0

**Comment by michaelficarra** [comment]
This is one of the worst bug reports I've ever seen. Unfortunately, I know what you're trying to say and it's invalid and duplicate.

**Comment by nzakas** [comment]
@willin Please read over our contribution guide to see how to for a proper issue: http://eslint.org/docs/developer-guide/contributing.html

I believe this is a duplicate of #2102
