### ISSUE TITLE
Unexpected token < error in jsx

### ISSUE THREAD

**Issue by flipjs** [eslint/eslint#2138]
```
	render: function() {
		return (
			<div className="jumbotron">
			</div>
		)
	}
```

From the code above, Im getting an error "unexpected token <" on div tag in my jsx file. Sorry if this has been asked before. I tried searching but can't find the solution. Is this something that I have to add in my eslint config or something? Im using v0.17.1 . Thanks.

**Comment by BenoitZugmeyer** [comment]
Did you set `"jsx": true` in `"ecmaFeatures"`?
See: http://eslint.org/docs/user-guide/configuring#specifying-language-options

**Comment by flipjs** [comment]
```
{
	"settings": {
		"ecmascript": 6,
		"jsx": true
	}
}
```

I just did, but I still get the same error. Code above is all I have in my .eslintrc. Do I need to add some more in my .eslintrc?

**Comment by flipjs** [comment]
```
{
	"ecmaFeatures": {
		"jsx": true
	}
}
```

I got it now. I used the above code. Thanks!

**Comment by sidazhou** [comment]
+1

**Comment by anthonybrown** [comment]
👍
