### ISSUE TITLE
Allow to modify base configuration

### ISSUE THREAD

**Issue by meoguru** [eslint/eslint#2143]
I'm implementing a library which help developers to quickly set up a project. ESLint configuration will be pre-defined by the library and can be overrided by the developer also.

For example, the library want to set following configuration by default:

```js
{
  "parser": "babel-eslint",
  "rules": [
    "quotes": [ 2, "single" ],
    "strict": [ 2, "never" ]
  ]
}
```

And the developer has the option to override it (through `.eslintrc`, `package.json`, etc.):

```js
{
  "parser": "espree",
  "rules": [
    "strict": [ 2, "global" ]
  ]
}
```

The above example is taken from a real use case, in which the whole project is supposed to be written in ES6/7, while some directories have files which are written in ES5 and down.

I digged through ESLint code and realize that at the moment there is no way to solve that use case. I propose a solution as:

* Adding a new option called `baseConfig`.
* After initialize `configHelper.baseConfig`, merge it with `baseConfig` option.

Please refer to this pull request #2141 for more detail. Thank you.

**Comment by nzakas** [comment]
This sounds a lot like #1637. Can you confirm?

**Comment by meoguru** [comment]
I think #1637 is somewhat different.

#1637 is about having a base configuration for the whole project. Each `.eslintrc` file will extend from that base configuration directly instead of: base configuration → `.eslintrc` in parent directories → `.eslintrc` in the current directory.

My issue and solution are only about having a customized base configuration. You can think of it as another `.eslintrc` file at the top of the directory tree.

**Comment by nzakas** [comment]
You would be able to achieve that with `--reset` and `extends` in the `.eslintrc` file.

**Comment by meoguru** [comment]
There are 2 points here.

Firstly, I'm writing a library and it have no control over developer's `.eslintrc` file. Custom configuration has to be loaded before any `.eslintrc` file, that's why I called it custom *base* configuration. Going with `--reset` or equivalent, `options.reset`, doesn't work because `options.reset` configuration is loaded after `.eslintrc` files.

Second, `options.reset` resets default configuration of ESLint (the one in `conf/eslint.json`). I can do something like:

```js
var eslintDefaultConf = require('gulp-eslint/node_modules/eslint/conf/eslint.json');
var options = { reset: clone(eslintDefaultConf) };
options.reset.rules = { ... };
```

But it's a bit hacky with that `require()` call.

**Comment by nzakas** [comment]
I'm sorry, I'm having a hard time understanding what it is you're trying to accomplish. Can you describe what it is you're doing without referencing a particular solution?

**Comment by meoguru** [comment]
For example:

**What I want**: To change `strict` rule of ESLint to `[ 2, "global" ]` (just that rule, other ones from `conf/eslint.json` must be retained).

**What I cannot do**: To change rules using any `.eslintrc` file, because I'm just writing a package which provide default ESLint support to other applications.

**Comment by meoguru** [comment]
I think the first comment of mine explained it well, you can just ignore the proposed solution.

**Comment by nzakas** [comment]
If the first comment explained well, I wouldn't be asking for more details. :) I think what you're saying is you want to use `CLIEngine` to make a new tool, is that correct?

> What I want: To change strict rule of ESLint to [ 2, "global" ] (just that rule, other ones from conf/eslint.json must be retained).

Is there a reason you can't do this?

```js
var CLIEngine = require("eslint").CLIEngine;

var cli = new CLIEngine({
    envs: ["browser", "mocha"],
    useEslintrc: true,
    rules: {
        global: [ 2, "global" ]
    }
});
```

(Example taken from our [Node.js API docs](http://eslint.org/docs/developer-guide/nodejs-api))

**Comment by meoguru** [comment]
Oh sorry I thought it was clear enough.

In your example, the `strict: [2, "global"]` rule will override any `strict` rule in `.eslintrc` files, right?

**Comment by nzakas** [comment]
Yes.

**Comment by meoguru** [comment]
Hmm, is there any way to make it be set before `.eslintrc` files?

**Comment by nzakas** [comment]
Not right now. The command line options always take precedence over everything else.

**Comment by meoguru** [comment]
Is any chance for this feature to be supported?

**Comment by nzakas** [comment]
I'm still not entirely sure what you're asking for. Are you asking for:

1. A way to use a different config in place of eslint.json as the base?
1. A way to use a different config in addition to eslint.json as the base? So your config just overrides what's in eslint.json?
1. Something else?

**Comment by meoguru** [comment]
3. A way to use a different config in addition to `eslint.json` as the base. But my config will be overrided by what's in `.eslintrc`.

**Comment by nzakas** [comment]
Okay, I really don't want to do something like that, as it complicates the already complicated hierarchy we have.

I would be willing to do #1. In that case, it would be up to you to read eslint.json and then merge in the differences you want.

**Comment by meoguru** [comment]
Hmm, I think #1 is fine. Is exporting `eslint.json` ok? Or else we have to do something like:

```js
var eslintDefaultConf = require('gulp-eslint/node_modules/eslint/conf/eslint.json');
```

**Comment by nzakas** [comment]
Yeah, I think exporting the defaultConfig is fine.

**Comment by meoguru** [comment]
Hmm, I found it. `eslint.json` is already exported under `eslint.linter.defaults()`.

And about replacing `eslint.json`, which option name is ok? We had `options.configFile` for command-line specific config. So it should be something like `options.baseConfigFile`?

**Comment by meoguru** [comment]
We should take care when this new option and `reset` option is passed at the same time as well. What about having a new CLI option named `default`. The whole picture will be like this:

* `default = false`: same as `reset = true`.
* `default = true`: load `conf/eslint.json`.
* `default = <some file path>`: load that file instead of `conf/eslint.json`.
* `reset` option will override `default` option when both appearing at the same time. `reset` will be deprecated.
* `baseConfig` will be refactored to `defaultConfig`.

How do you think?

**Comment by nzakas** [comment]
I think I would deprecate the `reset` option and a `baseConfig` option. 

* When `--reset` is passed to the CLI, `baseConfig` would be set to an empty object.
* If `--reset` is not passed, then `baseConfig` is set to eslint.json.
* Otherwise, you can set `baseConfig` to whatever you want.

In the short-term, the `reset` option, if true, would just set `baseConfig` to an empty object.

We could remove `reset` in a future version.

**Comment by meoguru** [comment]
Yes my idea is exactly the same without the `baseConfig`/`defaultConfig` name.

**Comment by nzakas** [comment]
I'd prefer to use `baseConfig`, as I think it more accurately describes its purpose.

**Comment by meoguru** [comment]
Ok. I'm working on a pull request.

**Comment by meoguru** [comment]
Please review the later commit above (the first one has a mistake of mine, ignore it).
