### ISSUE TITLE
npm run profile is broken

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#2150]
A `git bisect` determined that 4f4a7ea (PR #1781, "New: Allow parser to be configured (fixes #1624)") broke `npm run profile`.

`master` looks like this:

![screenshot 2015-03-27 01 29 24](https://cloud.githubusercontent.com/assets/1709537/6863036/db22f842-d420-11e4-805d-88217ce3e755.png)

When it should look more like `4f4a7ea~1`:

![screenshot 2015-03-27 01 31 08](https://cloud.githubusercontent.com/assets/1709537/6863048/0e6f8fda-d421-11e4-9f04-3f966abae8ca.png)

**Comment by nzakas** [comment]
This probably has to do with the browserified version it generates. I had to make a change to out browserify task when I asked pluggable parsers. Probably a similar issue here.
