### ISSUE TITLE
option to list files being processed

### ISSUE THREAD

**Issue by glenjamin** [eslint/eslint#2152]
I had a few issues this morning trying to get my .eslintignore file to do what I wanted (it turned out what I needed was `**/node_modules/*` in the end).

It would have been helpful to have a `--list-files` option or similar which uses the internal file matching / directory walking code, and either spits out filenames as it goes, or even skips linting entirely and just shows which files would match.

Can probably contribute this myself if you're happy with the concept.

**Comment by nzakas** [comment]
You can already get this info by running in debug mode:

```
$ DEBUG=eslint:* eslint lib/
```

**Comment by EmSyndio** [comment]
@nzakas the debug option is nowhere close to what you would expect with a --list-files option.
--list-file would be very useful to debug what files are being parsed or missed. 
The output of debug eslint:* is very very verbose and it is not clear at all what filter would really simply pull the list.

a filter on eslint:cli-engine leads some result but many dupes, eslint:linter generates a bunch of extra data.

Plus a --list-file option would simply list files that are going to be processed, without processing them. The simple output of the glob function.

I think this is worth working on.
