### ISSUE TITLE
Flow Type Annotations

### ISSUE THREAD

**Issue by balupton** [eslint/eslint#2157]
There is https://github.com/eslint/eslint/issues/1486 which was closed as it was not possible at the time.

It is now possible with the babel-eslint parser as babel supports flow type.

So how do we make this happen?

**Comment by nzakas** [comment]
We aren't going to natively support Flow type annotations in the foreseeable future. You can still use `babel-eslint` or `esprima-fb` as a parser for ESLint, and it will parse the files okay. You can also then create your own rules that look at the type annotations and do whatever you want.
