### ISSUE TITLE
New rule proposal: no-const-reassign

### ISSUE THREAD

**Issue by jbrumwell** [eslint/eslint#2158]
Variables that are declared as constants but are later reassigned, are no longer constant, and should be declared with let or var.

This rule is aimed at eliminating errors and silent defects in code by ensuring that constants are not assigned more then once.

**Comment by nzakas** [comment]
It's worth noting that constant reassignment will throw an error in both strict and non-strict mode in ES6, so it's not possible for the code to silently fail.

Even so, seems like a good rule provided it's not too expensive.

**Comment by jbrumwell** [comment]
That isn't exactly correct, we can see the support for strict and non-strict mode here;

http://kangax.github.io/compat-table/es6/#const_redefining_a_const_is_an_error
http://kangax.github.io/compat-table/es6/#const_redefining_a_const_(strict_mode)

**Comment by nzakas** [comment]
You're saying that current ES6 implementations have bugs in this regard. I'm saying ES6 specifies this behavior so it will eventually be correct everywhere.
