### ISSUE TITLE
disable check for unused variable

### ISSUE THREAD

**Issue by sfabriece** [eslint/eslint#2173]
How can i disable a check for one unused variable while still checking all the other?

**Comment by nzakas** [comment]
You can use an inline comment to disable rules in specific areas. See http://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by servel333** [comment]
For clarity and a specific example for others:

      var some_unused_variable; // eslint-disable-line no-unused-vars

**Comment by jacklovepdf** [comment]
any other good idea?

**Comment by platinumazure** [comment]
@jacklovepdf We now have a [`varsIgnorePattern` option](https://eslint.org/docs/rules/no-unused-vars#varsignorepattern) available for this use case (best suited for ignoring specific unused variable names or patterns across all your files).

It's always worth checking the rule documentation to see if there are good options. Our rules documentation can be found here: https://eslint.org/docs/rules
