### ISSUE TITLE
How to specify the --rulesdir option without command line?

### ISSUE THREAD

**Issue by hatelove85911** [eslint/eslint#2180]
I'm using vim editing javascript code. so I have sytastic plugin installed and configured eslint as the checker for javascript code.
Below is the project structure:
```
xxx_project
     |-- .eslintrc
     |-- .eslintrules
                 |-- rule1.js
                 |-- rule2.js
                 |-- ...
     |-- web
            |-- a.js
            |-- b.js
            |-- ...
```
Everytime I use vim to check js file, eslint will find the .eslintrc configuration file under the project root folder. eslint will throw errors for those custom rules, because eslint can't find the definition of them. But in fact the custom rules' definition is under "xxx_project/.eslintrules" directory.  

Is there any way to tell eslint which rulesdir to use when not using command line?

**Comment by gyandeeps** [comment]
Yes there is a way.
Can you share the code where you are calling `eslint` code to fire up?

**Comment by ilyavolodin** [comment]
The only way to run custom rules without command line arguments is to package them as a plugin. If you do not want to post them on NPM (say your rules are private and you don't want to share them), you can install them through NPM by pointing it to your [local folder](https://docs.npmjs.com/cli/install). You will need to create package.json file and follow the same requirements as the rest of the plugins. Here's a link to [documentation](http://eslint.org/docs/developer-guide/working-with-plugins).

**Comment by nzakas** [comment]
`--rulesdir` is being deprecated in favor of plugins.
