### ISSUE TITLE
Inconsistent use of " for object keys in tests

### ISSUE THREAD

**Issue by JedWatson** [eslint/eslint#2184]
I was reviewing the tests for `spaces-in-brackets` and noticed inconsistencies with the use of quoted keys in objects when describing tests.

e.g.

```js
        // never - arraysInArrays
        { code: "var arr = [ [1, 2], 2, 3, 4];", args: [2, "never", {"arraysInArrays": true}] },

        // never - arraysInArrays, singleValue
        { code: "var arr = [ [1, 2], [ [ [ 1 ] ] ], 3, 4];", args: [2, "never", {"arraysInArrays": true, singleValue: true}] },

        // never - arraysInArrays, objectsInArrays
        { code: "var arr = [ [1, 2], 2, 3, {'foo': 'bar'} ];", args: [2, "never", {"arraysInArrays": true, objectsInArrays: true}] },
```

note `"arraysInArrays"` vs. `objectsInArrays: true`

This may have slipped in with a PR, I just wanted to confirm what the intended style here should be. I'm planning to add some tests to that file and can fix the inconsistencies if desired.

**Comment by nzakas** [comment]
The preferred style is to only use quotes when necessary.
