### ISSUE TITLE
Provide `no-empty` option that allows empty `catch` blocks.

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#2187]
I want to disallow empty blocks in general with the `no-empty` rule, but I do not want to disallow empty "catch" blocks.

I'd like an option that restores the pre-`0.18.0` behavior of ignoring empty `catch` blocks.

Filing per discussion on https://github.com/eslint/eslint/issues/1841#issuecomment-87721836

**Comment by nzakas** [comment]
We aren't going to restore the previous behavior. You can still allow empty `catch` blocks, you just need to add a comment inside. We made this change because it's easy to miss empty `catch` blocks that weren't intended to be empty. 

Happy to discuss other augmentations of the rule that might help you out.

**Comment by ljharb** [comment]
So `var data; try { data = JSON.parse(json); } catch (e) {}`, which is a very common pattern I've seen, necessitates a comment in that block? would `/**/` work, or does the comment have to have content?

**Comment by nzakas** [comment]
> necessitates a comment in that block?

Yes.

> would `/**/` work, or does the comment have to have content?

With #2193 that comment will work.

**Comment by ljharb** [comment]
Thanks, #2193 makes this much easier for me. However, I'd still like an option that does ignore empty `catch` blocks, so I'd love this to remain open.

**Comment by doberkofler** [comment]
@ljharb I generally understand your point with a breaking change and in the original #1841 discussion I actually opted for a separate (no-empty-catch) rule altogether. @nzakas convinced me, that keeping this a single rule makes more sense and I still think he was right. I would keep the behavior as it is now and am fine with relaxing the the need for a specific comment to any comment.

**Comment by nzakas** [comment]
@ljharb thanks for your input. We've already made the other change you requested, so I'm considering the matter closed. I know you disagree with the decision, however, I've already explained the rationale. We have a lot of other issues to focus on now.
