### ISSUE TITLE
`no-empty` rule should allow empty blocks with any single comment

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#2188]
If a single comment "// empty" is sufficient in the eyes of the `eslint` maintainers to mean "this empty block is intentional", then shouldn't *any* comment in an empty catch block be sufficient?

A specific example of this is here: https://github.com/es-shims/es5-shim/blob/1e3abcb09f9914f6fe408ddffb7471e5b98e053c/es5-sham.js#L109-L113

To me, that comment is far more explicit than "empty" and imo it should pass the rule.

(Related to #1841, #2187)

**Comment by nzakas** [comment]
Yeah, that's a very good point. I agree. An empty block with one or more comments is a clear indicator that the emptiness is intentional.

**Comment by ljharb** [comment]
Thanks!
