### ISSUE TITLE
rule idea: prefer-exports

### ISSUE THREAD

**Issue by calvinmetcalf** [eslint/eslint#2198]
A rule the doesn't allow you to do module.exports = object literal in node, instead of individually exporting each of the things, in other words it would ban this:

```js
module.exports = {
  foo: 'bar',
  bar: 'baz'
}
``` 

instead of 

```js
exports.foo = 'bar';
exports.bar = 'baz'
```

would not ban

```js
module.exports = new Foo();
```

The main reason for me personally wanting it is that I have one co worker that always does the top style while I have another that does not so would like to get a style check for consistently.

The top one has the disadvantage that in case of a circular dependency will break. Another reason would be how in ES6 modules those 2 styles mean very different things so unintentionally mixing would be a problem.

I can open a pull.

**Comment by nzakas** [comment]
I think this is more complicated than it seems. It's one thing to say enforce `module.exports` instead of `exports`, but to start distinguishing by the right hand value gets tricky. If you want something that specific, I'd say you're better off with a custom rule.

**Comment by gyandeeps** [comment]
As there has been no progress on this discussion, I am going to close it as the suggestion was made to  create a custom rule.
Feel free to reopen this issue if needed for further discussions.

**Comment by xjamundx** [comment]
The problem with the other approach is that you'd be effectively banning anything like this:
```
module.exports = {
   name: 'jamund',
   age: 32
};
```

You could go further down and say no no we're only banning `module.exports` that export an `object` that only has `functions` or `intentifiers` as keys, which is probably the intent of this rule.

I get that there's a need for consistency here. Personally on my team I'd love to enforce this style:

```js
function a() {}
function b() {}

// really clear single place for exports
module.exports {
   a: a,
   b: b
};
```

Also worth thinking about is the slightly different ex6 export semantics. Fun stuff, maybe we'll revisit in a few months if other things die down :)
