### ISSUE TITLE
no-unused-vars on default parameters

### ISSUE THREAD

**Issue by kentcdodds** [eslint/eslint#2201]
This may be related to the eslint-babel parser. Given [this code](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=true&spec=false&code=const%20foo%20%3D%20'hello!'%3B%0A%0Afunction%20bar(foobar%20%3D%20foo)%20%7B%0A%20%20console.log(foobar)%3B%0A%7D)

```javascript
// example.js
const foo = "hello!";

function bar(foobar = foo) {
  foobar.replace(/!$/, " world!");
}

bar();
```

and this .eslintrc

```json
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}
```

I get this error:

```
~/Desktop
⛄  $ eslint example.js 

example.js
  1:6  error  foo is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

However, `foo` is being used as the default parameter.

**Comment by gyandeeps** [comment]
Have you tried with the default parser (`espree`)?

**Comment by nzakas** [comment]
Can you try with the default parser and see if you get the same results?

**Comment by gyandeeps** [comment]
@nzakas I tried it, It gives the same results.

**Comment by nzakas** [comment]
Thanks. Will probably wait until the escope upgrade to address.
