### ISSUE TITLE
no-spaced-func counts comments as spaces

### ISSUE THREAD

**Issue by necolas** [eslint/eslint#2211]
I was not expecting [padded-blocks](http://eslint.org/docs/rules/padded-blocks) to result in errors when a comment is the first or last line of a block. Assuming this is a bug but it could also be intentional.

Rule:

```
"padded-blocks": [2, "never"],
```

Code:

```
function fn(a, b) {
  /**
   * comment
   */
  return function () {
    return a + b;
  };
}
```

Error:

```
error  Block must not be padded by blank lines  padded-blocks
```

**Comment by necolas** [comment]
Also noticed that other rules have similar results when comments are involved (e.g., no-spaced-func: 2):

```
describe/*.only*/('foo', function () {});
```

```
error  Unexpected space between function name and paren  no-spaced-func
```

**Comment by lo1tuma** [comment]
`padded-blocks` shouldn’t count comments as empty lines, there is a [test-case for this scenario](https://github.com/eslint/eslint/blob/89b1ee3a06370197e060fe6688b40d1b587ee1af/tests/lib/rules/padded-blocks.js#L37).

Can you provide more information? Do you use the default parser `espree` or a different parser?

**Comment by necolas** [comment]
ah, yeah i'm using babel-eslint

**Comment by necolas** [comment]
Disabling the babel-eslint parser makes the `padded-blocks` error go away, but `no-spaced-func` still produces errors.

**Comment by nzakas** [comment]
Let's focus on the `no-spaced-func` issue. We're probably mistakenly treating comments as spaces because we're just checking the location of the two tokens (and the comment doesn't appear in the token list).

**Comment by lo1tuma** [comment]
@nzakas I guess there are more rules affected by this bug, see https://github.com/eslint/eslint/search?utf8=%E2%9C%93&q=isSpaced.

**Comment by nzakas** [comment]
Ack! Okay, we probably need to externalize that into a common utility so we can fix it once.

**Comment by nzakas** [comment]
I'm wonder how much would break if we add comments into the token list. Might need to investigate that as a better long-term solution.

**Comment by btmills** [comment]
> I'm wonder how much would break if we add comments into the token list.

I've investigated doing something along these lines (inspired by what millermedeiros/rocambole does with tokens), but merging tokens and comments was a big enough perf hit (~30% iirc) that I didn't pursue it much further. I got far enough to know we'd probably need to augment the tokens API with methods that skipped comments, so that style rules would get comments and semantic rules wouldn't.

**Comment by nzakas** [comment]
It seems like there should be a fairly inexpensive way to do this. I'm assuming you were doing some array splicing, but I'm not sure that's necessary. In token store, we're already iterating over each token to setup the lookups. What if we just, in that same loop, checked to see if a comment comes next and add `leadingComments` and `trailingComments` as we do for nodes?

**Comment by nzakas** [comment]
Working on this.

**Comment by necolas** [comment]
Thanks Nicholas
