### ISSUE TITLE
Auto apply rules to code 

### ISSUE THREAD

**Issue by Globegitter** [eslint/eslint#2212]
I was thinking that the other day and also just read https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8 

I was wondering if that is anything on the Roadmap for eslint? It would be really great if there was an option that eslint just automatically fixes all the errors, or well I suppose the style rules since that is probably more feasible than actually fixing code errors.

**Comment by Globegitter** [comment]
Ah just seeing #2203. Yeah definitely in favour of that!

**Comment by nzakas** [comment]
Yeah, this is a pretty tricky problem to solve, and we're not sure if we're going to address it yet. Stay tuned to #2203 as we finalized the roadmap for 2.0.0
