### ISSUE TITLE
Add ability to ignore arbitrary tokens

### ISSUE THREAD

**Issue by TGOlson** [eslint/eslint#2213]
I'd love to be able to ignore arbitrary tokens, particularly in the case of macro support. I understand that full linting of macros or any invalid JavaScript would be a massive undertaking, but it would be great to be able to configure a rule where the identifier includes an invalid token. 

For example, I want to write a macro above my functions that includes a couple illegal tokens:

```js
@ (Str) -> Str
function someStringThing(/*...*/) {}
```

It would be great to at the very least be able to tell eslint to ignore this line (without the wrapping it in the 'ignore' comments), or be able to define a custom rule of my own. Currently that is not possible because eslint displays an `Unexpected token ILLEGAL` message which overrides everything.

**Comment by ilyavolodin** [comment]
This is an issue for espree not eslint. However, eslint already supports something like that. It has support for code processors. You can write your own custom processor that will eliminate unwanted code before linting it. See here for more details: http://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins

**Comment by nzakas** [comment]
Yeah, you're much better off with a code processor for this case.

**Comment by TGOlson** [comment]
Awesome, thanks for the heads up - processors are exactly what I was looking for.

Are either of you aware of any limitation with processors and IDEs? My preprocessor works great when I run from the command line, but when live linting in an IDE eslint seems to ignore my processor. Any ideas?

**Comment by nzakas** [comment]
Sorry, we aren't aware of how IDEs interact with ESLint. You'd have to contact either the IDE or the IDE plugin author.

**Comment by TGOlson** [comment]
Makes sense, and thank you for the help and the awesome linter. It does everything I need it to and more.
