### ISSUE TITLE
Different parsers for different folders in my project

### ISSUE THREAD

**Issue by Globegitter** [eslint/eslint#2217]
Taking this PR https://github.com/balderdashy/enpeem/pull/4 as an example, I am adding [Babel](https://github.com/balderdashy/enpeem/pull/4) to the test-side of the project, so I can write my tests using the latest ES6/7 syntax, but I don't want this in the app/production code itself because it degrades performance quite a bit.

So for eslint to recognize the ES6/7 syntax properly I am using [babel-eslint](https://github.com/babel/bhttps://github.com/babel/babel-eslint) as a parser, which is great to have, but I would only want that to parse the code in my `tests` folder and everything else use the default eslint parser, so it recognizes if I accidently write ES6/7 code in the app itself.

Furthermore I am running eslint via [mocha-esling](https://github.com/BadgeLabs/mocha-eslint), so may there could be some api to set the parser. So I could have babel-eslint in the `.eslintrc` file, it would use that as a default, but using the api I can overwrite the parser when it comes to the test-folders.

Does that make sense? Something worth considering?

**Comment by gyandeeps** [comment]
I think this is futuristic idea and its belongs here: https://github.com/eslint/eslint/issues/2203

**Comment by ilyavolodin** [comment]
I might not be understanding what you are looking for correctly, but what is stopping you from creating another .eslintrc file under `tests` folder and setting parser to babel-eslint there? Your root .eslintrc config will not specify parser, so it will be parsed using espree.

**Comment by Globegitter** [comment]
Ahhh @ilyavolodin that sounds like it would exactly do what I need. So would the .eslintrc in my `tests` folder need to have an exact copy of the rules? Or would it take the root folder rules and then just override any differences in the subfolder?

**Comment by ilyavolodin** [comment]
For now, you will have to duplicate your config. There's a ticket opened for being able to inherit configs here: #1637

**Comment by nzakas** [comment]
If your rules are specified in a top-level config, then you can just specify the parser difference in `.eslintrc` in your `tests` directory and the rules will cascade. See: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by Globegitter** [comment]
Oh that is pretty sweet and should close this issue. I will update as soon as I get to it. Thanks!

**Comment by nzakas** [comment]
Closing as this is already supported.

**Comment by ORESoftware** [comment]
:+1:
