### ISSUE TITLE
Add support for Spread operators

### ISSUE THREAD

**Issue by tracker1** [eslint/eslint#2220]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

Example: (line 41)

```
  promise.close = (...args)=>promise.then((conn)=>conn.close(...args));
```

Currently (0.18.0) shows the following error...

```
src/index.js
  41:20  error  Unexpected token
```

**Comment by gyandeeps** [comment]
What config did use?
Here the link which would help you to activate `es6` features: http://eslint.org/docs/user-guide/configuring

**Comment by nzakas** [comment]
You need to enable `spread` and `restParams` for that to work.

**Comment by tracker1** [comment]
@nzakas thanks, I was looking on the rules page, not the configuring page... didn't see anything related.
