### ISSUE TITLE
Add space-in-curly-braces rule [$15]

### ISSUE THREAD

**Issue by JedWatson** [eslint/eslint#2225]
As discussed in #1576, replacing `space-in-brackets` with individual `space-in-square-brackets` and `space-in-curly-braces` rules makes sense, adds flexibility and will reduce confusion going forward.

This issue is for tracking the addition of the `space-in-curly-braces` rule (which may need a better name, e.g. `space-in-object-notation`) and discussing the options it will support (e.g. ignoring nested objects, arrays, etc) as per the original `space-in-brackets` rule.

@nzakas once I've got feedback and direction from you on how you'd like this done, I'm happy to work on a PR implementing it.

**Comment by lo1tuma** [comment]
Should this rule only apply to object literals or also to destructuring object patterns and JSX expressions?

**Comment by nzakas** [comment]
yeah, maybe space-in-object-literal is better. It should apply to restructured objects but not JSX.

**Comment by nzakas** [comment]
Better: `object-literal-spacing`?

**Comment by nzakas** [comment]
So `object-literal-spacing` may not be right because import statements have something that look like an object literal aren't really. Maybe `curly-braces-spacing` is better even though it doesn't deal with blocks.

**Comment by xjamundx** [comment]
I may be able to take a look at this in the next week.

**Comment by nzakas** [comment]
Awesome!

**Comment by xjamundx** [comment]
I started working on this. I'll probably have a few questions, but for now it's good. Hopefully will have a candidate PR by tomorrow...

**Comment by xjamundx** [comment]
Thinking out loud there are several use cases we may want to include in our testing as part of this rule:

- **Object literals** `var x = { a: "b" };`
- **Destructuring** `var { x, y, z } = a;`
- **Nested Objects** `var x = { a: { b: "c" } }`
- **Import/Export Specifiers** `export {tar}` and `import {tar} from "roof"`

Here are some curly braces we want to make sure are not included:

- **Template Strings** <code>var a = \`I am ${age} years old\`;</code>
- **Block Statements** including `if (x) {}` and `x => {x}`

The only option in the current rule that apply to curly braces is the `objectsInObjects` which is either `true` or `false` and determines if a space is needed around the closing brace of an object inside of another object such as:

-  true (space at the end is required) `var x = { a: { b: "c" } }`
- false (space at the end is forbidden) `var x = { a: { b: "c" }}`

**Comment by nzakas** [comment]
:+1:

**Comment by xjamundx** [comment]
Just about done, wrapping up some issues with destructuring edge cases like defaults and nesting...

**Comment by nzakas** [comment]
@xjamundx there was a bounty on this issue that you can claim

**Comment by xjamundx** [comment]
Thanks can you give to charity?

**Comment by nzakas** [comment]
You should claim the Bounty and donate to whatever you want. :)
