### ISSUE TITLE
Add spaces-in-square-brackets rule [$15]

### ISSUE THREAD

**Issue by JedWatson** [eslint/eslint#2226]
As discussed in #1576, replacing space-in-brackets with individual `space-in-square-brackets` and `space-in-curly-braces` rules makes sense, adds flexibility and will reduce confusion going forward.

This issue is for tracking the addition of the `space-in-square-brackets` rule (which may need a better name, e.g. `space-in-array-notation`) and discussing the options it will support (e.g. ignoring nested objects, arrays, etc) as per the original `space-in-brackets` rule.

@nzakas once I've got feedback and direction from you on how you'd like this done, I'm happy to work on a PR implementing it.

**Comment by lo1tuma** [comment]
Do we also want to distinguish between spaces in array literals and spaces in bracket notation (e.g. `a[0]`)?

**Comment by nzakas** [comment]
That's a good point. Maybe we should further split this out into space-in-array and space-in-computed-property?

**Comment by nzakas** [comment]
Better: `array-literal-spacing` and `computed-property-spacing`?

**Comment by btmills** [comment]
:+1: to `*-spacing` names; that pattern is more consistent with other rules (e.g. `comma-spacing`, `key-spacing`, and others).

Would `computed-property-spacing` apply to `a[b]` as well as `({ [a]: b })`, or are computed property keys a third case?

Since this only entails adding new rules, I don't think it's breaking. The breaking change would be removing the deprecated rule these replace as part of #1898, wouldn't it?

**Comment by nzakas** [comment]
Yes, I'd say the `computed-property-spacing` should apply in both cases.

The breaking part is that this rule replaces an existing one.

**Comment by xjamundx** [comment]
I'll take this on sometime this week.

**Comment by nzakas** [comment]
Thanks! Just to be clear: there are two rules to close this issue.

**Comment by nzakas** [comment]
Rule names should be `array-bracket-spacing` and `computed-property-spacing`

**Comment by RReverser** [comment]
I'm having currently conflicts between `space-in-brackets: [2, "never"]` and `object-curly-spacing: [2, "always"]` rules. Is it part of this issue and thus will be auto-fixed (i.e. `space-in-brackets` will be deprecated in favor of separate rules or smth.) or should I submit another one?

**Comment by xjamundx** [comment]
Yes `space-in-brackets` will be deprecated. I'm starting working on `array-bracket-spacing` today!

**Comment by xjamundx** [comment]
Similarly to `curly-braces-spacing` do we automatically apply the whitespace rules for `array-bracket-spacing` to destructuring syntax?

**Comment by RReverser** [comment]
Thanks!

> Similarly to curly-braces-spacing do we automatically apply the whitespace rules for array-bracket-spacing to destructuring syntax such as var [a,b] = x

Yes, it would feel pretty logical.

**Comment by nzakas** [comment]
Yes, definitely apply to array destructuring

**Comment by nzakas** [comment]
@xjamundx there was a bounty on this issue that you can claim
