### ISSUE TITLE
wrong rule in test configurations

### ISSUE THREAD

**Issue by remitbri** [eslint/eslint#2227]
In `eslint/tests/fixtures/configurations/env-node-override.json`, the rule is `"no-global-strict": 1`.
I think it should be `"global-strict": [1, "never"]`.

**Comment by nzakas** [comment]
All rules have a default setting. In this case, the default is "never", so it's the same as providing " never" explicitly.

**Comment by remitbri** [comment]
Sure, but the name of the function changed.

**Comment by nzakas** [comment]
Oh sorry, I completely missed that. Probably not a big deal since no tests are failing, but we can clean that up.

**Comment by remitbri** [comment]
Hmm, silly me: it's not `global strict` either, rather something like `"strict": [2, "never"]`. But I'm not sure whether `env-node-override.json` is used at all: any value has no incidence on tests (it seems)…

**Comment by ilyavolodin** [comment]
This file is not used anywhere, as far as I can tell. In general the whole `fixtures` directory needs a good cleanup.
