### ISSUE TITLE
ES7 decorators throws error which can't be disabled..

### ISSUE THREAD

**Issue by bytasv** [eslint/eslint#2228]
Hello

Babel 5 came out and now allows us to use decorators - http://babeljs.io/blog/2015/03/31/5.0.0/#stage-1:-decorators

I'm really happy with this release and I implemented it in some places BUT now with linter I'm getting error:
```
error  Unexpected character '@'
```

Which can't not be removed even by using `// eslint-disable-line` on that line..

Here's the code:
```es6
class Cat extends Animal {

  @isSiamese // eslint-disable-line
  @hasParam('tail') // eslint-disable-line
  woof() {
    // ...
  }
}
```

What are my options in this case that does not include **disabling linter** or **removing decorators**

**Comment by nzakas** [comment]
We don't support ES7 syntax. If you are using babel-eslint as your parser, please for an issue there.
