### ISSUE TITLE
Eslint api.verify does not use plugin processors

### ISSUE THREAD

**Issue by TGOlson** [eslint/eslint#2231]
It looks like `eslint.verify` does not run plugin processors. From a little inspection, it seems the only way to access that feature is via `cliEngineInstance.executeOnFiles(/*...*/)` (where `cliEngineInstance = new CLIEngine(/*...*/)` ). 

 Is it possible to have `eslint.verify` invoke the plugin processor feature? Maybe by leveraging the `CLIEngine` itself?

**Comment by nzakas** [comment]
No, the `eslint` object doesn't know anything about the filesystem, so it cannot use processors. See http://eslint.org/docs/developer-guide/architecture for an overview of the architecture.

Processors are strictly a `CLIEngine` feature.
