### ISSUE TITLE
Feature Request: support strong mode

### ISSUE THREAD

**Issue by jonathanong** [eslint/eslint#2240]
as an optional flag like `'use strict'`. would be cool if strong mode catches on.

https://developers.google.com/v8/experiments#strong

i'm sure half of these rules are already implemented as individual rules. the way i see it working is:

- "strong" rules override all other rules when and only when in `strong mode`
- `strong mode` is an acceptable substitute for `use strict` (per definition)

can't think of anything else

**Comment by nzakas** [comment]
I'm sorry, your description isn't specific enough. What do you by "support strong mode?"

**Comment by jonathanong** [comment]
implement every rule (many of which are already implemented) and support the `strong mode` macro similar to `use strict`.

**Comment by nzakas** [comment]
What does "every rule" mean? What does support "strong mode" macro mean? We really need a lot more specific information in order to evaluate what you're requesting. If you've done the research, please provide as much detail as possible.

**Comment by jonathanong** [comment]
strong mode is a superset of strict mode: https://docs.google.com/a/fuiszmedia.com/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/view

it lists all the rules.

**Comment by nzakas** [comment]
It sounds like you're asking me to do research on strong mode and make some changes to ESLint for it. I'm sorry, I don't have the time nor inclination to do such research. Unless you are willing to explain exactly what you're requesting from us, including which rules you're looking for, then I'm going to close this issue.

**Comment by jonathanong** [comment]
i can write down the all the specific rules (list which have been implemented, reference relevant issues already opened), but first the concept has to be accepted. there's like 50 rules on that list - i'm not going to spend the time to break them down unless you give direction or say okay. i don't know what you don't know about strong mode or strict mode, so i have no idea what to answer. 

implementation steps are:

1. add "strong mode" support to the roadmap
2. list all the rules and their relevant eslint rules
3. implement all the rules as separate eslint rules
4. when `strong mode` is detected in any block, automatically enable those rules for that block (not sure if this is already implemented in strict mode).

**Comment by nzakas** [comment]
What I've been saying is that you aren't providing enough information for me to make any decision. "Support strong mode" doesn't mean anything to me, which is why I've been repeatedly asking for more information. Refusing to give more information until I commit to something I don't understand is counterproductive.

From what I've gathered from skimming over the links, strong mode is an experimental extension to JavaScript. As such, we won't be making any changes for it.

I haven't reviewed the rules in strong mode, but if any are of interest to you, please file separate issues describing each one you'd like to see in ESLint. We are always happy to review possible rules.

**Comment by jonathanong** [comment]
> From what I've gathered from skimming over the links, strong mode is an experimental extension to JavaScript. As such, we won't be making any changes for it.

yup, all i wanted to know. make sense. i guess the "experimental" part is what greatly differentiates it from `use strict`. 

i will open up separate issues for each rule as i come across them.
