### ISSUE TITLE
Deprecation notice for rules or functions or API

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#2243]
As we are approaching towards `1.0.0`, I think it would be a good idea to printing deprecation warnings on the `cmd` prompt. So that people know they are using old rules, or deprecated API or deprecated functions inside certain modules.
This will help people specially for rules to update their config files, so that on the day when `0.1.1` gets released the tool doesn't bomb out.

I know `Gulp` does it by using the module [deprecate](https://github.com/brianc/node-deprecate)

**Comment by nzakas** [comment]
I'm not sure this is a good idea. People may be relying on the output from ESLint for automation, and inserting random deprecation notices into the output might have unintended consequences.

**Comment by gyandeeps** [comment]
More like before printing the actual output of the report. This way people would know which rules are expiring and it will become easy for them to update their config file.

**Comment by nzakas** [comment]
Still, anytime you change what is output, you run the risk of interrupting automation. For instance, if someone is using JSON or XML formatter, then you introduce invalid syntax.

So I'm :-1: on this suggestion unless there's a way to add such warnings without potentially breaking something.

We've also been pretty explicit about what we are deprecating and what is going to change in 1.0.0, so hopefully there won't be any big surprises for anyone.

**Comment by gyandeeps** [comment]
Alright. Thanks.
