### ISSUE TITLE
[Demo] This snippet make Firefox very slow & crash Safari 

### ISSUE THREAD

**Issue by MoOx** [eslint/eslint#2247]
I was about to try something in the demo to reproduce a indentation bug (I think but that's not the point of this issue).

When I paste this code into Firefox I can barely move my cursor (partial freeze) & Safari just reload the page and say it has to reload it because of a crash.

I guess it's not the expected behavior for the demo :)

```js
switch(chunk.type) {
case "test":
  console.log(`# ${ chunk.name }`)
  break

case "assert":
  asserted++
  console.log(chunk)
  if(chunk.ok) {
    ok++
  }
  else {
    notOk++
  }
```

**Comment by ilyavolodin** [comment]
Did you past the whole code snippet that you used? I just tried it in Chrome, Firefox and Safari and I get an instance "Unexpected token ILLEGAL" message due to usage of template strings. Demo doesn't support ES6 currently. Also, this ticket should probably be filed in website's repository instead.

**Comment by MoOx** [comment]
Well that weird. I think I pasted a wrong modified version of what was crashing ff & safari. I can't reproduce anymore. Sorry for bothering you. :/
