### ISSUE TITLE
Set quote-props to ignore {func() {}} case

### ISSUE THREAD

**Issue by edygar** [eslint/eslint#2251]
Is there a option to make `{"quote-props": "always" }` ignore the case `{ funcDefinition() { } }` (ES6 function definition)?

**Comment by nzakas** [comment]
No there isn't. We should probably just make it ignore by default.

**Comment by nzakas** [comment]
Working on this.

**Comment by edygar** [comment]
Thank you, sorry the delay for answer. But you just got me thinking, maybe, there should be a concise methods rule too, so one could forbide this and impose the extended way.

Anyway, thank you!

**Comment by fakewaffle** [comment]
Would that also fix these conflicts?

![Image](https://www.dropbox.com/s/jtrei7ooidzan03/Screenshot%202015-06-04%2021.30.42.png?dl=1)
![Image](https://www.dropbox.com/s/9x75zbqq1r59h5p/Screenshot%202015-06-04%2021.31.25.png?dl=1)
