### ISSUE TITLE
Add --no-eslintignore to CLIEngine

### ISSUE THREAD

**Issue by globexdesigns** [eslint/eslint#2255]
Would it be possible to add the --no-eslintignore option to the CLIEngine list of options?

**Comment by nzakas** [comment]
You mean `--no-ignore`. This is already supported via the `ignore` property. See http://eslint.org/docs/developer-guide/nodejs-api

**Comment by globexdesigns** [comment]
@nzakas No, I'm looking for the `--no-eslintignore` option. The one that prevents warning from appearing for files mentioned in the .eslintignore file.

See "Ignored File Warnings" at the bottom of: http://eslint.org/docs/user-guide/configuring.html

**Comment by nzakas** [comment]
`--no-eslintignore` didn't exist. That's a mistake in the docs: https://github.com/eslint/eslint/commit/b481e3c92aa9b180f032d455fdf11460dbf166d1

There's only `--no-ignore`.
