### ISSUE TITLE
no-undef and  no-underscore-dangle uses single quotes

### ISSUE THREAD

**Issue by message** [eslint/eslint#2258]
It's minor, but it would be nice to stick with one quotation style. Since most rules uses double quotes, i think `no-undef` and `no-underscore-dangle` should be changed.

```
   1:0   error  Use the global form of "use strict"           strict
  20:12  error  "args" used outside of binding context        block-scoped-var
  20:12  error  'args' is not defined                         no-undef
  26:1   error  Unnecessary semicolon                         no-extra-semi
  38:18  error  Unexpected dangling '_' in '__container__'    no-underscore-dangle
```

**Comment by nzakas** [comment]
There are probably more, too, since so many different people write rules. We can try to clean these up.

**Comment by message** [comment]
We can use eslint itself to define quotation style

**Comment by nzakas** [comment]
No, we can't. These quotes occur inside of strings.
