### ISSUE TITLE
Add option to tolerate non-top-level `import`s in ES6 mode

### ISSUE THREAD

**Issue by cvrebert** [eslint/eslint#2259]
The ES6 spec only allows `import`s at the top-level of a module (i.e. not nested inside another block, such as a function body, `try`, etc.). However, when using ES6 in a transpiled-to-ES5 context, it's useful to loosen this constraint and just treat `import`s as a regular statement that's allowed anywhere, since the ES5 module systems it's transpiled to don't have any such constraint.
In particular, this is useful for optional imports (e.g. try to import `foo`, else try to import `bar`, else see if there's a global hanging on `window` and grab that).
Therefore, I'd like to request the addition of an option that would allow `import`s anywhere.

Esprima harmony, Acorn, Babel, and JSCS all already have options to allow this:
* https://github.com/jquery/esprima/commit/b1dd29e985b353648a6e0fa8b9f852cd2db228ac
* https://github.com/marijnh/acorn/issues/174
* https://babeljs.io/docs/usage/loose/#es6-template-literals (see the `es6.modules` option)
* https://github.com/jscs-dev/node-jscs/issues/952

**Comment by michaelficarra** [comment]
This would be an espree option.

**Comment by cvrebert** [comment]
Espree already shares Esprima's "tolerant" mode which makes supporting this possible. However:
* it's not clear how to pass the `{tolerant: true}` option to espree via eslint
* it would be preferable to have eslint/espree only be tolerant/loose regarding `import`/`export` declarations, and not regarding various other syntactical oddities

**Comment by nzakas** [comment]
Since you're transpiling, is there a reason you don't use babel-eslint as the parser? I'm assuming you're using Babel for transpiling?

**Comment by cvrebert** [comment]
> I'm assuming you're using Babel for transpiling?

Indeed.

> is there a reason you don't use babel-eslint as the parser?

Mainly that `babel-eslint` didn't yet exist when I setup my project. And I'm not using any of Babel's post-ES6 extensions.
However, now that I try it, switching to it merely changes the error message:

With vanilla eslint configured for ES6:
>  11:9  error  Illegal import declaration

With babel-eslint:
>  11:8  error  'import' and 'export' may only appear at the top level

**Comment by nzakas** [comment]
That's interesting, I'd expect all of Babel's tools to work the same way. 

In any event, this would be an Espree issue because the error comes from the parser, not ESLint itself.

**Comment by necolas** [comment]
(FWIW, babel-eslint has some bugs (namely around comment handling) that are currently preventing us from using it too.)

**Comment by cvrebert** [comment]
Filed successor Espree bug: https://github.com/eslint/espree/issues/124
