### ISSUE TITLE
Wrap Markdown paragraphs at 80 columns to improve patch readability?

### ISSUE THREAD

**Issue by NateEag** [eslint/eslint#2268]
While submitting some PRs last night, I noticed that many of the documentation Markdown files are written with each paragraph as a single long line.

In GitHub's UI, patches to those long lines have the internal differences highlighted, so they're still pretty readable.

In vanilla git, the diff is not very readable.

Would a PR wrapping all regular Markdown paragraphs at 80 columns be accepted?

**Comment by nzakas** [comment]
It would be accelerable, but honestly, I don't think it's a good use of time. It would be hard to enforce this on all PRs, and it's hard enough to get people to write documentation as it is, I really don't even to start imposing such conventions on them.

**Comment by NateEag** [comment]
Okay, fair enough. I won't worry about it, then.

Thanks for all your work on ESLint. It's an excellent tool.
