### ISSUE TITLE
Turn off 'unexpected token' for certain files?

### ISSUE THREAD

**Issue by Globegitter** [eslint/eslint#2275]
I am just trying to see how eslint does on: https://github.com/ember-cli/ember-cli and turns out these files https://github.com/ember-cli/ember-cli/blob/master/blueprints/util-test/files/tests/unit/utils/__name__-test.js are a problem, since eslint is of course not expecting to see the `<%=` token. But these are template files that, I believe at runtime, get the variables inserted.

I managed to just ignore these files completely via the `.eslintignore` which is a nice workaround but I was wondering if it would be possible to still get the style rules checked for these files or if that is against how eslint currently works?

**Comment by ilyavolodin** [comment]
You could write a processor to replace those template variables with something meaningful before linting. Take a look at documentation here: http://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins

**Comment by nzakas** [comment]
Yeah, a processor is your only option. The parser can't know to skip arbitrary strings.
