### ISSUE TITLE
Allow ~.eslintrc to be ignored

### ISSUE THREAD

**Issue by jwoudenberg** [eslint/eslint#2279]
I have a `.eslintrc` in my home directory as a default linter for small experiments, and different `.eslintrc` files in a number of projects. Those projects run eslint as part of a git commit hook.

My problem is that when I lint my project files, I inherit additional rules from my personal `.eslintrc` (which is technically in a parent directory). This means that code which is proper by the standards of the project is still causing lint tasks in the projects to fail.

I've searched the documentation for some option to disable my persional `~/.eslintrc`, or designate a certain `.eslintrc` as the root one (which would mean eslint should start cascading from that file). So far I haven't been able to find anything. Have I overlooked something?

**Comment by nzakas** [comment]
We should automatically ignore ~/.eslintrc if there's a local .eslintrc:
https://github.com/eslint/eslint/blob/master/lib/config.js#L159

Can you double check that this isn't happening?

**Comment by jwoudenberg** [comment]
I double checked. `found` is true at that point. The problem is that my projects directory is in a subdirectory of my home: `~/projects/foo`. So even when my personal `.eslintrc` is not used as a fallback option, it still gets found here:
https://github.com/eslint/eslint/blob/master/lib/config.js#L349

**Comment by nzakas** [comment]
Okay thanks, that's definitely a bug then.
