### ISSUE TITLE
`block-scoped-var` shows an error while using es6 classes

### ISSUE THREAD

**Issue by eTorAken** [eslint/eslint#2280]
I'm trying to `eslint` a file written in es6:
```js
class Share {
  // some code
}

export default Share;
```

And I got this error: `warning  "Share" used outside of binding context  block-scoped-var` at the line corresponding to `export default Share;`.

Is this a bug, or did I forget something? I'm using `v0.18.0`

**Comment by nzakas** [comment]
Looks like a bug.

**Comment by nzakas** [comment]
Working on this.

**Comment by sijovijayan** [comment]
Hi,
I got a wanning when i used the following code to export multiple classes with first class as default.

    148:21  warning  "default" used outside of binding context  block-scoped-var

When i using the following code.

    export { Editable as default, EditableMyTeam };

My project is reactjs based project, I'm using Eslint with babel. How to fix it ?

**Comment by mysticatea** [comment]
@sajinshrestha I could not reproduce that in [the online demo](http://eslint.org/demo/). 

![image](https://cloud.githubusercontent.com/assets/1937871/10804163/6cb3ef36-7e09-11e5-88c2-ab8d5d4bc6a8.png)
