### ISSUE TITLE
Switch column numbers to be 1-based

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#2284]
Since ESLint has started, we've used 0-based column numbers in our error reporting. This was not an intentional design decision, but rather a side effect of using what Esprima (and now Espree) returned as location position.

Other tools such as JSHint and JSLint are 1-based, and some editors (such as Sublime) expect error messages to come out as 1-based instead of 0-based.

As we are very close to a 1.0.0 release, this is the right time to stop and think if the 0-based columns we've been using are a bug or a feature. I'm leaning more heavily towards "bug" right now, and we could fix this for 1.0.0.

What do others think? Ping @btmills @ilyavolodin @lo1tuma @xjamundx

**Comment by ilyavolodin** [comment]
On one hand I think we should be consistent with other linters out there. On the other, we should think very long and hard about making this change. There are a lot of integrations already out there. Some of them are built-in to the editors directly (like WebStorm). So they can only update when the editor updates, which can take a long time. Until then, users will see incorrect reports.

**Comment by gyandeeps** [comment]
Would this change impact the modules which dependent on`eslint`?

**Comment by michaelficarra** [comment]
Shouldn't this decision be made by the formatter? 0-based column numbers can be used internally and exposed through the API, and a formatter can choose to display them to a CLI user as 1-based.

**Comment by ilyavolodin** [comment]
@michaelficarra I would guess most of the integrations don't use formatters, since they just use API directly and formatter is not required for that.
@gyandeeps Yes, most likely this change would affect anything that depends on ESLint and bypasses formatter.

**Comment by nzakas** [comment]
@michaelficarra It wouldn't make sense to update every formatter to do this. If 1-based is the right choice, then we shouldn't put the responsibility on formatters to always add 1.

@ilyavolodin Yes, this would be breaking, which is why it would be good to do at 1.0.0. It could break a lot of things, which is why we need to forecast it ahead of time.

**Comment by ilyavolodin** [comment]
@nzakas I understand. What I'm questioning is if it's a good idea to make such a disruptive change for no apparent gain other then consistency.

**Comment by nzakas** [comment]
The gain is that it's a lot less confusing (I'll admit, when I have an error at the 9 column, I tend to do a double take as well). Consistency is important, especially as people switch to ESLint from other tools.

And the disruption is minimal. In the worst case, error reporting is off by one column until people upgrade.

**Comment by xjamundx** [comment]
I think we should get this right before 1.0!

**Comment by ilyavolodin** [comment]
I don't feel strongly either way. Mostly just playing devil's advocate.

**Comment by albertosantini** [comment]
Before developing Build Next plugin (for SublimeText), I asked in the forum about 0-based column numbers in the error reporting: as @nzakas [said](https://groups.google.com/forum/#!searchin/eslint/santini/eslint/OqYkSPyyeRc/1OZOvJ54UK8J), it was Esprima heritage and no option was available.

So I added a preference to the plugin to deal with the issue.

Also in Vim, for instance, you need to adjust the [column programmatically](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/javascript/eslint.vim#L47).

I gave a look at another tools, as gcc and clang: they are 1-based and I didn't find any discussion about column numbers in the error reporting.

My point is the tools expect 1-based column and I vote for a breaking change.
My second option would be adding a setting to control the behaviour: the default might be also 0-based.

**Comment by albertosantini** [comment]
New kid on the block, Visual Studio Code, is 1-based column number.

https://code.visualstudio.com/Docs/tasks

**Comment by nzakas** [comment]
Working on this.
