### ISSUE TITLE
strict: [2, "global"] has no effect without env.node: true

### ISSUE THREAD

**Issue by chriscalo** [eslint/eslint#2296]
I'm on version 0.18.0 and it seems `strict: [2, "global"]` does nothing unless you also have `env.node: true`.

With the following `.eslintrc` file I kept getting the message **Use the function form of "use strict".**

    rules:
      strict: [2, "global"]

If I changed it to `"never"` or `"function"` I got the expected error messages, but I could never get `"global"` to work.

If I then set it to a node environment, everything works as expected.

    env:
      node: true

    rules:
      strict: [2, "global"]

Now if I have a file that is missing `"use strict";` at the top I get the expected error message of **Use the global form of "use strict".** And if I remove the `strict` rule, it also doesn't enforce that a `"use strict";` statement be present. This is perfect. Except for having to turn on the `node` environment.

The docs for the [strict rule](http://eslint.org/docs/rules/strict) make no mention of this and it would have saved me a ton of time if that were mentioned. Two proposals:

1. If this behavior is correct, explain that `node: true` is required in the "global" mode section of the [strict rule docs](http://eslint.org/docs/rules/strict).

2. Or if it's not correct, fix the behavior such that `strict: [2, "global"]` works without `node: true`.

Thoughts?

**Comment by btmills** [comment]
What rule is producing the error message, `strict` or `global-strict`?

Try adding `"global-strict": 0` to your `.eslintrc`.

**Comment by chriscalo** [comment]
@btmills, that indeed fixes the problem for me. Thanks.

My suggestion would be to explain the interdependencies of these rules. Something to the effect of "If you want to use `strict: [2, "global"]`, you should also set `global-strict: 0`.

**Comment by nzakas** [comment]
There aren't interdependencies, just an overlap. global-strict is already marked as deprecated in the docs and will be removed in 1.0.0 (soon!).

**Comment by aliaksandr-pasynkau** [comment]
ESLint has version 0.19.0 
rule strict: [2, "global"] isn't work! 
adding global-strict: 0 option into in the file .eslintrc didn't give any effect
