### ISSUE TITLE
Documentation: word missing in output

### ISSUE THREAD

**Issue by spadgos** [eslint/eslint#2297]
On [Working with rules](http://eslint.org/docs/developer-guide/working-with-rules) under the `context.report()` heading, the source reads:

    context.report(node, "`{{identifier}}` is unexpected!", { identifier: node.name });

But the output shows:

![selection_006](https://cloud.githubusercontent.com/assets/426222/7111744/77ed9aa4-e206-11e4-9504-35df11cfce4c.png)

**Comment by michaelficarra** [comment]
Probably better to open this bug on https://github.com/eslint/eslint.github.io

**Comment by spadgos** [comment]
[Reported there](https://github.com/eslint/eslint.github.io/issues/61), closing here.

**Comment by nzakas** [comment]
That page is managed in this repo: https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules.md

**Comment by michaelficarra** [comment]
@nzakas But is the rendering of that markdown page as HTML managed here? Because that's where the problem is.

**Comment by nzakas** [comment]
We don't render to HTML, we publish as markdown and Jekyll automatically does it. There is nothing else to change besides the markdown, which is managed here.

**Comment by michaelficarra** [comment]
The linked markdown document has no errors, though.

**Comment by nzakas** [comment]
I'm not sure what you're arguing about. The file gets copied over as-is to the website. If you think there's another way to fix this issue other than editing the markdown, please share.

**Comment by michaelficarra** [comment]
Why do you think the markdown needs to change? You either need to reconfigure or upgrade Jekyll, apparently. It is dropping the `{{identifier}}` portion of the Markdown document. None of that is handled in this repo.

Just to be absolutely clear here:

* the markdown document in this repo is *not* broken
* nothing in this repo needs to change
* something in the eslint/eslint.github.io repo needs to change to handle markdown like this properly
