### ISSUE TITLE
--init to setup .eslintrc file

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#2302]
I was using Karma the other day and became enamored with its `init` command. Basically, running `karma init` walks you through a questionnaire that helps create an initial configuration file. The more I thought about it, the more I think we need something like that for ESLint in 1.0.0.

So here's what I'm thinking:

```
$ eslint --init
```

This will *not* do any linting, but rather will start up a questionnaire about the user's settings. It needs to be short enough that people will want to do it, but long enough so the most important pieces are set. Here's what I think should be in the questions:

1. What style of indentation do you use? Tabs or Spaces
  * If spaces, how many spaces?
1. What quotes do you use for strings? Double or Single
1. What line endings do you use? Windows or Unix
1. Do you require semicolons? Yes or No
1. Which of these libraries are you using? React, Angular
  * If any are chosen, automatically install `eslint-plugin-react` or `eslint-plugin-angular` based on selection.
1. Are you using ECMAScript 6 features? Yes or No
  * If yes, enable `es6` environment.
1. Where will your code run? Browser, Node.js
  * Set appropriate environment
1. What format do you want your config file to be in? JSON or YAML

We can use https://github.com/SBoudrias/Inquirer.js to make this easy, and once complete, output a `.eslintrc` file with these filled in.

This would probably be implemented as a new object (let's say, `Initializer`?).

**Comment by ilyavolodin** [comment]
I thank that's fine. But I would remove libraries from the questioner. Don't think it's a good idea to get into a business of maintaining list of all available plugins for libraries. New libraries will continue to pop up all the time, and then you get into arguments as to why my library isn't listed even though there's a plugin for it.

**Comment by nzakas** [comment]
I'm selfishly trying to limit the number of times people open issues because they are using React but don't have the plugin installed - this happens way too frequently and we need to do something about it. While I agree that I don't want to maintain a list of libraries, I don't have a better solution, and limiting to React and Angular sets the bar pretty high. If you do, I'm happy to consider it instead.

For the location of the file, I think it should always be the current working directory. It doesn't matter where ESLint is installed, only where it's run from.

**Comment by ilyavolodin** [comment]
Yes, React is an issue. I don't think init will solve it, but if you think it would, I would suggest having two questions:
```
Will you use JSX
```
and if user answers yet, then
```
Will you use React
```
While Angular is popular now, it might not be popular in 3 month. And React is the one that's causing trouble currently.

**Comment by nzakas** [comment]
Fair point.

**Comment by Globegitter** [comment]
I like the idea. Are you planning to set some defaults to get quicker through it, or new users don't have to think too much? Especially for the last question I could see that some people have not heard of YAML before and have something pre-selected would certainly make it easier for me.

**Comment by ilyavolodin** [comment]
ESLint already comes with some defaults (in terms of rules). They are listed here: https://github.com/eslint/eslint/blob/master/conf/eslint.json

**Comment by nzakas** [comment]
We will definitely have logic defaults for each question so people won't get stuck.

**Comment by popenkomaksim** [comment]
My point of view, that questionnaire should be as simple as question of what existing config to choose, for example, airbnb has one https://github.com/airbnb/javascript/blob/master/linters/.eslintrc

There are many well known code styles to manage:
[Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)
[Google JavaScript Style Guide](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)
[Idiomatic.js](https://github.com/rwaldron/idiomatic.js)
[Crock's Code Conventions For JavaScript](http://javascript.crockford.com/code.html)
[jQuery Core Style Guide](http://contribute.jquery.org/style-guide/js/)
ESLint default preset
...

But these code styles are good draft for projects code style.


@addyosmani has good article "[JavaScript Style Guides And Beautifiers](http://addyosmani.com/blog/javascript-style-guides-and-beautifiers/)"
By the way even [GitHub JavaScript Style Guide](https://github.com/styleguide/javascript) exist.

As for me, rules like ES6, global variables, JSX and etc. should be manage manually in config.

**Comment by ilyavolodin** [comment]
@popenkomaksim We discussed it a few times. Bottom line, we really want to avoid putting ourself into position of having to be gatekeepers for different styleguides.
We are going to implement an ability to package .eslintrc files into plugins (and publish it on npm), and an easy way for you to import them into your project. That should be good enough for styleguide support, and we don't have to be filtering them.

**Comment by interactionist** [comment]
I wrote my own .eslintrc boilerplate based on http://eslint.org/docs/rules and just started implementing a interactive command line user interface (inquirer) to it so that you can easily set it up. I was just tired to manually configure it.

```bash $ eslint-initializer```

I think that's what you are up to as well, @nzakas?

**Comment by nzakas** [comment]
Yes, `--init` is already released, so you can use it today.

**Comment by AsaAyers** [comment]
It seems that `--init` exists, but it isn't listed under `--help`. v0.23.0

```
eslint [options] file.js [file.js] [dir]

Options:
  -h, --help                  Show help
  -c, --config path::String   Use configuration from this file
  --rulesdir [path::String]   Use additional rules from this directory
  -f, --format String         Use a specific output format - default: stylish
  -v, --version               Outputs the version number
  --reset                     Set all default rules to off - default: false
  --no-eslintrc               Disable use of configuration from .eslintrc
  --env [String]              Specify environments
  --ext [String]              Specify JavaScript file extensions - default: .js
  --plugin [String]           Specify plugins
  --global [String]           Define global variables
  --rule Object               Specify rules
  --ignore-path path::String  Specify path of ignore file
  --no-ignore                 Disable use of .eslintignore
  --ignore-pattern String     Pattern of files to ignore (in addition to those in .eslintignore)
  --no-color                  Disable color in piped output
  -o, --output-file path::String  Specify file to write report to
  --quiet                     Report errors only - default: false
  --stdin                     Lint code provided on <STDIN> - default: false
  --stdin-filename String     Specify filename to process STDIN as
```

**Comment by nordisk** [comment]
+1

**Comment by btmills** [comment]
@AsaAyers thanks for the report; I created #2817 to track that.

**Comment by raould** [comment]
Pretty please some day make it possible to use this w/out having cursor keys available, i.e. in a "*shell*" buffer in Emacs. It would probably mean offering it as multiple choice instead/optionally. :-)
