### ISSUE TITLE
no-irregular-whitespace not catching \u2028

### ISSUE THREAD

**Issue by cletusw** [eslint/eslint#2316]
The [docs](http://eslint.org/docs/rules/no-irregular-whitespace.html) list [`\u2028` (Line Separator)](http://www.fileformat.info/info/unicode/char/2028/index.htm) as one of the characters that the `no-irregular-whitespace` rule will catch. In my experience, this is not the case:

![screen shot 2015-04-14 at 5 31 41 pm](https://cloud.githubusercontent.com/assets/862638/7149555/2921a188-e2cc-11e4-9f60-66094e1812c0.png)

Allowing this character caused an uglify step in a build of mine to fail. Would be nice if ESLint could catch  it. If not, the docs need to be updated.

I'm on a Mac, in case that helps.

**Comment by nzakas** [comment]
If the docs say it should, then it should. Probably just a bug.

**Comment by ilyavolodin** [comment]
Last two errors reported are coming from espree, not eslint.

**Comment by nzakas** [comment]
That's true, however, there is no error for 2028.js, which is the one that has this character. The other results are not important for this issue.

**Comment by cletusw** [comment]
True, 2028 is the only one I really care about. However, it looks like 2029 is not being caught either. The others are there to show that it's at least catching some of the ones listed, so the whole rule is not broken. Just a few (potentially more than these two) characters.
