### ISSUE TITLE
Add global-require rule (Node.js)

### ISSUE THREAD

**Issue by Alaneor** [eslint/eslint#2318]
This rule would only allow the use of `require()` calls in the top-level scope of a module and would only allow use of module's exported functions **after** they have been declared.

#### Clarity

Declaring module's dependencies at the beginning of a module improves readability and provides insight to other developers about what modules are required. Declaring these dependencies inline within other parts of the code may make them harder to spot and could lead to poorly-maintainable code in the long term.

#### Performance

`require` is synchronous and so it blocks the process while the module is loaded. If we declare our dependencies in the top-level scope, we increase the likelihood of these dependencies being loaded at application startup. On the other hand, if we require them within a function, that function might be called much later in an application lifecycle, possibly even after that application has started serving requests - and now our `require` could block the whole process for several milliseconds, or even seconds if the server has a bad day. This is explained in greater detail [here](https://github.com/alanjames1987/Node.js-Best-Practices#never-require-modules-inside-of-functions).

### Examples

The following examples are considered warnings/errors:

```js
// Use of module function before dependency declaration
var formatted = require("util").format("Ultimate answer: %s", 42)

// Indirect dependency declaration
var util
util = require('util')

function myFunc () {
    // require() statements should be in the module's top-level scope
    var util = require('util')
}

// Use of require() in a function call? (facepalm)
myFunc(require('util').inspect)

var result = require('myfunc')()
```

The following examples are considered okay:

```js
var util = require('util')

var inspect = require('util').inspect

var util = require('util')
function myFunc () {
    var inspect = util.inspect
}
```

### Rule classification

Personally I feel this rule is a "best practice" rule - however, use cases exist where inline `require` calls are inevitable, so perhaps "coding style" classification is a better fit.

### Default behaviour

This rule should be off by default.

### Configuration options

We could have two modes for this rule.

- `always`: A strict variant, with behaviour as described above. Only top-level `require` calls are allowed and dependencies must be declared before they are used.
- `declare-first`: A more permissive variant, which allows `require` calls at any place in the code, but will still warn about code that immediately uses a required module, i.e.:

    ```js
    function myFunc () {
      // Bad
      console.log(require('util').inspect(obj))
      // Good
      var util = require('util')
      var insp = require('util').inspect
      console.log(util.inspect(obj))
    }
    ```

> This rule has been partially implemented (test cases, docs) in #2314.

**Comment by nzakas** [comment]
Thanks for the submission, at first glance, this rule looks like it's doing too much. I could see an argument that a rule banning require outside of the global score should exist, but the rest of the functionality seems only tangentially related to that point and bundling all of them into a single rule is confusing. If you want a rule that does everything you're asking, then it's best written as a plugin. Otherwise, we really need to figure out of there are multiple useful rules you're proposing.

**Comment by xjamundx** [comment]
I'm with @nzakas in that a rule that checks for `require` outside of the global scope might be a good idea, essentially enforcing `import` rules. @Alaneor do you think that would be at least a good starting point? I still think the name is probably accurate, despite the limited feature set.

**Comment by Alaneor** [comment]
Hi guys!

Yup - I think that limiting the scope of this proposal to only check for `require`s in the global scope is a very good start.

Perhaps the rest is not really needed (or I will consider a separate proposal).

How do we proceed next? I am unsure if I can be of much assistance in the implementation phase, though I did write some tests in a [different PR](2314) for this. Perhaps I can reuse some parts of that code and at the very least provide tests and documentation for this rule.

**Comment by nzakas** [comment]
Ok, let's go with `global-require` as the rule name. You can either take a stab at it, or we can leave it open for implementation. New rules are very low priority right now for the core team, so I'd suggest talking a stab at it or out could be a while.

**Comment by xjamundx** [comment]
I'll take a stab at this...

**Comment by xjamundx** [comment]
Currently I'm disallowing them to be children of a block, but I found a few other cases we might like to include. What are your thoughts?


- `code: "var x = (x => require(x))('weird')",`
- `code: "switch(x) { case '1': require('1'); break; }",`

**Comment by xjamundx** [comment]
I'll push up my partial implementation just for discussion (early...)

**Comment by xjamundx** [comment]
Any consideration of built-in exception for AMD-style `require([], function)`?

I use this in webpack all the time, because it uses async semantics. Maybe we can check for require() with a single argument?

**Comment by nzakas** [comment]
Block scope and function scope. I don't know that it makes sense to have an exception for AMD.

**Comment by xjamundx** [comment]
@Alaneor were you hoping that your rule would stop this case:

```
if (process.env.NODE_ENV === 'development') { require('debug'); }
```

I guess people can easily just declare these as exceptions if they want...

**Comment by Alaneor** [comment]
@xjamundx Yes, `if`ing a `require` statement might seem like a nice thing, but then it forces you into checking for the module's presence every time you want to use it. Consider:

```js
var debug

if (process.env.NODE_ENV === 'development')
  debug = require('debug')

// But this would crash on production (undefined is not a function)! So we would
// need another check here
debug('some debug message')
```

So I am against allowing conditional `require` statements.

As for the AMD-style `require`, I have no opinion on that matter as I have never worked with it. I'll defer to your good judgement. :)

Thanks!

**Comment by xjamundx** [comment]
@Alaneor I'm assuming this should be allowed:

`var logger = DEBUG ? require('dev-logger') : require('logger');`

**Comment by xjamundx** [comment]
But I'm banning switch statements, because of complexity. Hope that's alright :)

**Comment by xjamundx** [comment]
Take a look at the PR I'm thinking it's probably ready to go...

**Comment by xjamundx** [comment]
Sorry I've slept on this. Let me check out the feedback...
