### ISSUE TITLE
no-mixed-require: Missing module name for iojs

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#2320]
For iojs `v8` modules is missing from the list.
My recommendation would be to not hard code module names but calculate them at run time using:
`require("repl")._builtinLibs.concat('repl').sort()`

If we all agree I can work on this.

**Comment by nzakas** [comment]
We don't calculate them at runtime because there's no guarantee the version of node that's running ESLint is the same as the one that the linted code would be used on. Feel free to add the missing modules to the list.
