### ISSUE TITLE
no-unused-args: ignore parameters with name matching a regex

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint#2321]
In AngularJS when using dependency injection the order of parameters is not important, therefore it makes sense if all of them are used so that to not leave an unused dependency in parameter list. However, sometimes one has to define a function with unused first parameter, e.g. if a function is passed two arguments but we need only the second one.

How about adding an option that'd behave more or less as `{"args": "all"}` but that'd ignore parameter names that match a certain regex/start with something. This would allow to write:
```js
function onClick(_ev, data) {
    send(data);
}
```
and have it not fail on ESLint because `_ev` starts with `_` but would still allow to use ESLint to find unused parameters where they're not left on purpose.

**Comment by nzakas** [comment]
You can already write that today using the rule. Can you provide an example that isn't possible today that you'd life to support?

**Comment by mzgol** [comment]
I'd like the following:
```js
function onClick(_ev, data) { // no warning about an unused _ev
    console.log(data);
}

function job(name, title, source) { // warning about unused title
    jobs[name] = source;
};
```

**Comment by nzakas** [comment]
Ah I see...so you're saying that you want to be able to annotate parameters to say, "don't check this one"? Is a naming convention the best way to do that? What about using a comment?

**Comment by mzgol** [comment]
> Ah I see...so you're saying that you want to be able to annotate parameters to say, "don't check this one"?

Exactly.

> Is a naming convention the best way to do that? What about using a comment?

You mean to wrap it in proper `/* eslint-enable ... */` & `/* eslint-disable */`? I guess that would work but it's a little more tedious; also, this doesn't allow to disable checking for specific parameters but for the whole function. In cases like that I usually have to define a first unused parameter but I do care if I don't introduce new excessive ones after that one.

**Comment by mzgol** [comment]
@nzakas any thoughts about my ideas?

**Comment by nzakas** [comment]
I suppose I can see it. What would you expect the options to look like?

**Comment by mzgol** [comment]
I see a couple of options. Either a specific comment:
```js
function f(a /* unused */, b) {
    return b;
}
```
configured normally:
```js
"no-unused-vars": [2, {"vars": "all", "args": "all"}]
```
or (my preferred but the previous one would be ok as well):
```js
function f(_a, b) {
    return b;
}
```
configured like:
```js
"no-unused-vars": [2, {"vars": "all", "args": {"all-except-prefixes": ["_"]}}]
```
or:
```js
"no-unused-vars": [2, {"vars": "all", "args": {"all-except-regex": ["/^_/"]}}]
```

**Comment by andy-hanson** [comment]
mzgol's idea would be great. 99% of the time I intend to use every parameter, so having to type an underscore for ignored parameters is fine.

**Comment by gyandeeps** [comment]
@nzakas I think we have all the info to make a decision and add the appropriate labels here.

**Comment by nzakas** [comment]
I think we need a better option name for using regular exclusions, but otherwise, looks good.

**Comment by mzgol** [comment]
Is this supposed to work with ESLint 1.2.1? The following config:
```json
{
    "root": true,
    "rules": {
        "no-unused-vars": [2, {"args": "all", "argsIgnorePattern": "^_"}]
    }
}
```
still prints an error for the file:
```js
function foo(_a) { } foo();
```
Error:
```
a.js
  1:14  error  _a is defined but never used  no-unused-vars
```

**Comment by gyandeeps** [comment]
@mzgol Can you file a separate issue with appropriate details. Thanks

**Comment by gyandeeps** [comment]
Correction: This issue has been fixed but not yet released

**Comment by mzgol** [comment]
@gyandeeps Sorry, I got confused by https://github.com/eslint/eslint/commits/master showing `1.2.1` as a newer commit than 91fc1c588db38292ad9e107d5369732b9e272c61 so I erroneously assumed it includes it. That's what happens when you flatten a tree. :)
