### ISSUE TITLE
Can't detect recursion

### ISSUE THREAD

**Issue by Newlifer** [eslint/eslint#2335]
Maybe this linter isn't for this, but it says that the code below is fine. But sure this is not true.

```
function foo (fn) {
	"use strict";
	fn(foo);
}


foo(foo);
```

**Comment by nzakas** [comment]
I'm sorry, this isn't enough information. What do you think is wrong with the code? What rules do you have enabled? What are you expecting ESLint to do with this code?

**Comment by ilyavolodin** [comment]
The title should be changed to `Can't detect infinite loop/recursion`. And I'm really not sure if the linter should be doing this.

**Comment by nzakas** [comment]
@Newlifer is that what you mean?

**Comment by Newlifer** [comment]
Yes, sure. I meant this. Sorry for this inaccurate wording.

**Comment by nzakas** [comment]
Thanks.  Unfortunately, this is really a runtime check and would be too difficult to figure out via static analysis.
