### ISSUE TITLE
Enable/disable 'global return' via comments?

### ISSUE THREAD

**Issue by jprichardson** [eslint/eslint#2339]
In reference to: https://github.com/eslint/eslint/issues/1158 is it possible to enable/disable `globalReturn` via comments? Something like:

```js
// skip test for windows
// eslint-disable global-return */
if (os.platform().indexOf('win') === 0) return
// eslint-enable global-return */
```

I didn't see anything in the documentation and tried a few permutations of `global-return`. Thanks.

**Comment by nzakas** [comment]
It's not possible at the moment.

**Comment by gyandeeps** [comment]
@nzakas should we close this?

**Comment by ilyavolodin** [comment]
Related to #2134

**Comment by nzakas** [comment]
This isn't possible because it's a parser switch that we can't change mid-code.
