### ISSUE TITLE
using es6 default parameters throws no-undef

### ISSUE THREAD

**Issue by Nyalab** [eslint/eslint#2345]
Hello,

I have an issue with ES6 default parameters + no-undef (already discussed a bit on https://github.com/babel/babel-eslint/issues/70)

```shell
~/d/o/admin-client ❯❯❯ eslint -v
v0.19.0
```

```js
function getPaletteClassName(color = '', tint = '', variation = '') {
  return color.charAt(0) + tint.charAt(0) + variation.charAt(0)
}
```

```shell
~/d/o/admin-client ❯❯❯ eslint web_modules/pages/styleguide/index.js

web_modules/pages/styleguide/index.js
  30:45   error  "color" is not defined            no-undef
  30:57   error  "props" is not defined            no-undef
  30:73   error  "color" is not defined            no-undef
```

Thanks in advance for your time & help!

**Comment by nzakas** [comment]
Can you try with the default parser and see if you get the same issues?

**Comment by xjamundx** [comment]
Using ESLint `0.21.0` I cannot reproduce this issue:
`eslint --reset --env es6 --rule '{"no-undef": 2, "strict": 0}' test.js`

test.js contains the following:
```js
function getPaletteClassName(color = '', tint = '', variation = '') {
    return color.charAt(0) + tint.charAt(0) + variation.charAt(0)
}
```

**Comment by yourcelf** [comment]
This is cropping up for me with eslint ``0.21.0``.

.eslintrc:

    {
      "ecmaFeatures": {
        "jsx": true
      },
      "env": {
        "browser": true,
        "node": true,
        "es6": true
      },
      "rules": {
        "no-unused-vars": [2, {"vars": "all", "args": "none"}],
        "no-var": true,
        "no-underscore-dangle": false,
        "quotes": false
      }
    }

script file:

    "use strict";

    module.exports = function(path, soureName="js/timeline-editor.min.js") {
      let scripts = document.getElementsByTagName("script");
      for (let i = 0; i < scripts.length; i++) {
        if (scripts[i].src.indexOf(sourceName) !== -1) {
          return scripts[i].src.replace(sourceName, "") + path;
        }
      }
    };

eslint output:

    6:31  error  "sourceName" is not defined  no-undef
    7:36  error  "sourceName" is not defined  no-undef

**Comment by yourcelf** [comment]
Nevermind. I clearly had a typo -- ``soureName`` -- and eslint correctly caught it.  Sorry for the noise.
