### ISSUE TITLE
Add explicit exceptions to `no-extend-native` and `no-native-reassign`

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#2355]
I can certainly disable these rules when desired, but I'd prefer to enable the rule, and supply explicit exceptions. A specific example: in https://github.com/es-shims/RegExp.prototype.flags , I'd like to allow `no-extend-native` of `RegExp.prototype` only.

Is this something you'd be open to adding?

**Comment by doberkofler** [comment]
I had the same problem and did disable the rule for each individual exception. The ability to specify explicit exception would be a helpful addition.

**Comment by nzakas** [comment]
Possibly, do you have an idea about how it should be implemented? What would you expect to specify as exceptions?

**Comment by doberkofler** [comment]
I imagined that the rule could offer an array of object names that are allowed to have their prototypes modified.

**Comment by ljharb** [comment]
Exactly that - like `capIsNewExceptions`, an array of values that are allowed. So `[2, { "exceptions": ["RegExp.prototype"] }]` would allow my `RegExp#flags` polyfill to modify `RegExp.prototype`.

**Comment by doberkofler** [comment]
What about only using the object name? `[2, {"exceptions": ["RegExp", "Array"]}]`

**Comment by ljharb** [comment]
That would be fine too, since it appears the rule only covers `.prototype` modifications.

**Comment by nzakas** [comment]
Yeah, I think just the constructor name makes the most sense.

**Comment by ljharb** [comment]
Thanks!
