### ISSUE TITLE
no-constant-condition: generators?

### ISSUE THREAD

**Issue by bathos** [eslint/eslint#2375]
A common pattern in infinitely yielding generators that's emerged is to use loops with while (true). It feels a little weird to me still, but if it's an emerging standard pattern (and I don't know of a better one, personally), perhaps there ought to be an option to allow constant conditions "only in generators."

Do other people think this would be useful? And is it even viable? (I don't know whether eslint knows whether the context is a generator body or not.)

**Comment by nzakas** [comment]
I don't think this makes sense as a built-in exception. If you're doing that, then it's best to manually disable the rule in the generator using a comment.

**Comment by bathos** [comment]
Okay. I don't feel strongly about this, I've just seen it a lot lately and figured it would be useful to people. Thanks.

**Comment by jbblanchet** [comment]
+1. I agree with @bathos, this is something I'm using more and more (at this particular moment with [redux-saga](https://github.com/yelouafi/redux-saga/)) and I do think it would be useful as a generic exception.

**Comment by Andarist** [comment]
@jbblanchet you can use `for (;;)` instead of `while (true)`

**Comment by jbblanchet** [comment]
@Andarist thanks for taking the time to answer me.

There are plenty of workarounds, but I've never believed to hacking around linters. I prefer deactivating the rule.

This is not a major pain point for me. I've simply deactivated the rule in an .eslintrc file in the directory where my generators are located. But I do think that `while(true)`, when used in iterators and generators, is a valid pattern that is starting to show up in more and more places, mostly because generators support is growing.

**Comment by benjamingr** [comment]
I think now that generators are mainstream and async functions are becoming mainstream this should be revisited. Users are also complaining about this in the context of fibers: http://stackoverflow.com/questions/37466508/are-there-any-objective-reasons-to-favour-for-over-while-for-an-infinite-loo

**Comment by ilyavolodin** [comment]
@benjamingr This has already been fixed with the last release.

**Comment by benjamingr** [comment]
Thanks! In generators? I think the problem with that question is that OP is using fibers. Not sure if that's an issue as I expect node fibers to go away when async await lands which was ~ a week ago (so Node 7)

**Comment by ilyavolodin** [comment]
https://github.com/eslint/eslint/pull/6202 It's a flag that doesn't care if you are doing generators or fibers or something else. It will just allow you to do `while(true)`.

**Comment by jordonbiondo** [comment]
I disagree that using a comment to disable the rule when in a generator is the best approach. IMO users should be able to enable the most strict ruleset possible and not get warned about a `while(true)` loop that contains `yield` inside a generator function.

Would it be possible to add a rule that allows constant conditions for loops if the loop is inside a generator and the body contains `yield`? I'd be happy to look into this if it would be possible and accepted if done correctly.

**Comment by platinumazure** [comment]
@eslint/eslint-tsc [Here](https://github.com/eslint/eslint/issues/2375#issuecomment-255137510) is a reasonably concrete proposal for how `no-constant-condition` could possibly ignore generators safely. Is this something we can consider, or still no?

**Comment by Turbo87** [comment]
@platinumazure has there been some progress on this? the proposal seems reasonable.

**Comment by platinumazure** [comment]
@Turbo87 Seems we've lost track of this since the issue is closed. Would you mind opening a new issue using that proposal, and ping me so I can :+1: it? (I'd suggest also adding some notes about generators and async being more mainstream, and do we want to augment the proposal to include async functions?)

**Comment by Andarist** [comment]
hm, yeah - `async` should be included too, its easy to imagine a polling task

**Comment by Turbo87** [comment]
@platinumazure done (https://github.com/eslint/eslint/issues/8566)
