### ISSUE TITLE
Node.js API modifies global defaults

### ISSUE THREAD

**Issue by also** [eslint/eslint#2380]
In ESlint v0.20.0, using `CLIEngine` modifies the `linter.defaults()` object or the passed-in `baseConfig` option directly before it is cloned.

```javascript
var eslint = require('eslint');
var CLIEngine = eslint.CLIEngine;
var linter = eslint.linter;
 
var baseConfig = {format: 'stylish'};
 
console.log(baseConfig.format);
new CLIEngine({baseConfig: baseConfig}).getConfigForFile('.');
console.log(baseConfig.format);
 
console.log();
 
console.log(linter.defaults().format);
new CLIEngine({format: 'compact'}).getConfigForFile('.');
console.log(linter.defaults().format);
```

The `getConfigForFile` call causes `format` to be reset. This logs

```
stylish
undefined

undefined
compact
```

This line from the current master appears to be responsible: https://github.com/eslint/eslint/blob/88b5ffa14fe11b0cc55ca60bf42d508a32d5c231/lib/config.js#L268

**Comment by nzakas** [comment]
Oh gross, sorry about that. We will get this fixed.

**Comment by nzakas** [comment]
Working on this.
