### ISSUE TITLE
new rule: disallow conditional expressions whose consequent and alternate are both Boolean literals

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#2391]
* `x ? true : false` is better written as `x` or `!!x` depending on whether x is already a Boolean
* `x ? false : true` is better written as `!x`
* `x ? true : true` is better written as `x, true`
* `x ? false : false` is better written as `x, false`

I have no idea what this rule should be called.

**Comment by ilyavolodin** [comment]
That's a fairly popular mistake to make. So I think it would be a good idea to create a rule for it.

**Comment by hzoo** [comment]
Maybe `simplify-conditional-logic`, `simple-conditionals`, `no-boolean-literal-conditionals`?

**Comment by nzakas** [comment]
Good idea. I'd call it `no-unneeded-ternary`?

**Comment by michaelficarra** [comment]
I don't like calling conditional expressions ternaries because there very well may be more ternary operators in the language in the future.

**Comment by gyandeeps** [comment]
how about `no-boolean-conditional` ?

**Comment by michaelficarra** [comment]
Sounds good to me.

**Comment by nzakas** [comment]
Hmmm, we already have `no-nested-ternary` and `no-ternary`, it would be strange to have such a disparity across for names for the same thing.
