### ISSUE TITLE
Question: Is there a good resource for comparing ESLint rules to other linters?

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#2395]
I've looked and looked, but have been unable to find an authoritative comparison of the rules between JSLint, JSHint, JSCS, and ESLint.  The closest I've come is https://jslinterrors.com/, which seems very useful but appears to be created to serve a different purpose of explaining the errors (and it does not include JSCS or even the last few versions of ESLint).  

It seems that at one time ESLint maintained a [compatibility spreadsheet](https://docs.google.com/spreadsheet/lv?key=0Ap5QGaRT4AJ_dGV6VXBlMEw3NHhVRl9vQ0lIX2FnVlE&usp=sharing).  Is there a more up-to-date version of this sheet?  It would be great to see something at-a-glance to tell what the overlap is between various linting tools.  I'm considering tackling that as a project for myself, but am opening this issue in case the work has already been done (or at least to find the best starting point).

**Comment by nzakas** [comment]
We don't maintain such a list, as rules are added, updated, and changed across projects too frequently. I know a few people have made attempts at this, but it's a maintenance nightmare so they often fall out of sync quickly.

**Comment by IanVS** [comment]
OK, thanks!
