### ISSUE TITLE
`no-unused-vars` incorrectly triggering for destructuring assignment with defaults

### ISSUE THREAD

**Issue by remko** [eslint/eslint#2405]
The following code
    
    const x = 1;
    const {y = x} = {};

triggers a warning of an unused `x`, although it's being used as a default for a destructuring assignment.

**Comment by nzakas** [comment]
What version of ESLint are you using? Are you using the default parser? Can you paste the actual console output into this issue?

**Comment by remko** [comment]
Eslint version 0.20.0, default parser.

Actual console output:

    test.js
      1:6  error  x is defined but never used  no-unused-vars

    ✖ 1 problem (1 error, 0 warnings)

**Comment by jsg2021** [comment]
This happens with the babel parser too.

**Comment by nzakas** [comment]
Thanks, will take a look.

**Comment by bucaran** [comment]
:+1: Thanks

**Comment by jrvidal** [comment]
The output of Escope for the code above does not list the second `x` instance as a reference to `x`. It looks like a bug on their end.

**Comment by nzakas** [comment]
Can you file an escope issue?

**Comment by nzakas** [comment]
escope issue: https://github.com/estools/escope/issues/64

**Comment by mysticatea** [comment]
I implemented this: https://github.com/estools/escope/pull/65
I will send a PR to upgrade after released it :)

**Comment by nzakas** [comment]
Awesome!

**Comment by ilyavolodin** [comment]
Closing as this issue has been fixed with latest escope upgrade.
