### ISSUE TITLE
Comment before comma trigger comma-spacing error

### ISSUE THREAD

**Issue by tiansh** [eslint/eslint#2408]
Use default setting on http://eslint.org/demo/

Codes:

```javascript
var myfunc = function (x, y, z) {
  "use strict";
  /* ... */
  return [x, y, z];
};
myfunc(404, true/* bla bla bla */, "hello");
```

Result:

> 6:33 - There should be no space before ','.

i'm new here, not sure if this is a feature or bug. maybe related to #1457

**Comment by gyandeeps** [comment]
I don't think this is related to 1457, since that was different.
But the code right now for comma-spacing doesn't account for the scenario you described, which is having a comment.

**Comment by nzakas** [comment]
Related to #2211.

**Comment by gcochard** [comment]
Is this also related to #1659?

**Comment by nzakas** [comment]
Slightly, but not directly.

**Comment by silverwind** [comment]
Also been hit by this with code such as this:

```js
[
  [0x61, 0x7A] /*a-z*/,
  [0x41, 0x5A] /*A-Z*/,
  0x2E /*'.'*/, 0x2B /*'+'*/, 0x2D /*'-'*/
]
```

Removing the space before the comment doesn't seem to help. I think `context.getTokensBetween` needs to be updated to include comments.
