### ISSUE TITLE
Running eslint as an npm script results in ELIFECYCLE error.

### ISSUE THREAD

**Issue by mikehaas763** [eslint/eslint#2409]
I'm using eslint 0.19.0 installed in a local package. 
I am on node v0.12.2 and npm v2.7.5

I have an npm script in my package.json set up just like the snippet below. When I run `./node_modules/.bin/eslint app` eslint runs exactly as I would expect it to. When I run `npm run eslint` eslint seems to run fine but I then get a nasty error at the bottom of the output. I've pasted the npm-debug.log file below. Any idea why this is happening and how I can fix it?

```json
"scripts": {
    "eslint": "eslint app"
}
```

>0 info it worked if it ends with ok
>1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'eslint' ]
>2 info using npm@2.8.4
>3 info using node@v0.12.2
>4 verbose node symlink /usr/local/bin/node
>5 verbose run-script [ 'preeslint', 'eslint', 'posteslint' ]
>6 info preeslint ccapp@1.0.0
>7 info eslint ccapp@1.0.0
>8 verbose unsafe-perm in lifecycle true
>9 info ccapp@1.0.0 Failed to exec eslint script
>10 verbose stack Error: ccapp@1.0.0 eslint: `eslint app/`
>10 verbose stack Exit status 1
>10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
>10 verbose stack     at EventEmitter.emit (events.js:110:17)
>10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
>10 verbose stack     at ChildProcess.emit (events.js:110:17)
>10 verbose stack     at maybeClose (child_process.js:1015:16)
>10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
>11 verbose pkgid ccapp@1.0.0
>12 verbose cwd /Users/mhaas2/projects/prototypes/ccapp
>13 error Darwin 14.3.0
>14 error argv "node" "/usr/local/bin/npm" "run" "eslint"
>15 error node v0.12.2
>16 error npm  v2.8.4
>17 error code ELIFECYCLE
>18 error ccapp@1.0.0 eslint: `eslint app/`
>18 error Exit status 1
>19 error Failed at the ccapp@1.0.0 eslint script 'eslint app/'.
>19 error This is most likely a problem with the ccapp package,
>19 error not with npm itself.
>19 error Tell the author that this fails on your system:
>19 error     eslint app/
>19 error You can get their info via:
>19 error     npm owner ls ccapp
>19 error There is likely additional logging output above.
>20 verbose exit [ 1, true ]

**Comment by gyandeeps** [comment]
Do you have any eslint errors for the JavaScript files?

What you have pasted here is the text from your `npm-debug` file. Look at the ouput on your console/cmd for truly whats going on.
I tried your scenario and what happens is that when eslint run ends with a exit code of 1 (that means you have eslint error(s) in your code) and then when npm tackles that error code then it throws an error because internal task returned an exit code 1.

It will for sure run fine if you don't have any eslint errors.
So to answer your questions, Yes its behaving as expected.

**Comment by nzakas** [comment]
To echo what @gyandeeps said, npm always outputs a bunch of debug info when a command returns a non-zero exit code. If you have linting errors, eslint returns 1 as the exit code. You can verify by running the same ESLint command in your console directly and also try running another task through npm that returns a 1 as the exit code.

**Comment by mikehaas763** [comment]
@gyandeeps @nzakas I did have some eslint errors. I didn't realize that `npm run` logged all that debug info based on the return code of the script it's running. I learn something new every day. Thanks!

**Comment by mmahalwy** [comment]
@mikehaas763, @nzakas is there a way to let the exit codes surface but without failing npm? So, I'd like to run the script via something else (git) and not have it break everything because it errors out.

**Comment by michaelficarra** [comment]
`eslint ...; exit 0`?

**Comment by mmahalwy** [comment]
@michaelficarra BO$$

**Comment by piecioshka** [comment]
:+1: 

Thanks @michaelficarra !

**Comment by andyfleming** [comment]
@michaelficarra :beers:

**Comment by catalin-testenv** [comment]
Thanks @michaelficarra !

**Comment by jeremenichelli** [comment]
Though that solves the npm error log, it's not recommendable since you might want to concat commands like linting and then bundling with browserify, and the second one will occur even if you have code to fix. To be honest it also bothers me the error logging in the console and I don't know a way to silent that, but forcing a `0` exiting code it's not a good idea.

**Comment by jalooc** [comment]
@jeremenichelli I fully agree with you, there should be a method of silencing the eslint output based on e.g. environmental variable.*

*In my particular case I would like to be able to run eslint through a package.json script without throwing npm errors AND to be able to use the same script as a git [pre-commit](https://www.npmjs.com/package/pre-commit) script to actually output corresponding value from eslint.

**Comment by jerexyz** [comment]
thanks @michaelficarra

**Comment by anhkhoi** [comment]
thanks @michaelficarra

**Comment by mingelz** [comment]
thanks @michaelficarra

**Comment by arkka** [comment]
What a hack, thanks @michaelficarra

**Comment by gggauravgandhi** [comment]
@michaelficarra
Thanks a lot, solved ugly error splitting.

**Comment by nao215** [comment]
Awesome!!! @michaelficarra 
I wanna give you sushi 🍣
