### ISSUE TITLE
Enforce File Names Conventions

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#2412]
One thing I've noticed in my code-base is that it's hard to get people to stay consistent on file naming conventions. For example we've tried to use `snake-case`, but often people end up using `camelCase` and occasionally `snake_case`. Would it be outside of the scope of eslint to provide a rule that would enforce file naming conventions?

Its might look something like this:

```js
{ "file-name-style": [2, "camel"] } // "snake", "kebab" 
```

**Comment by lo1tuma** [comment]
I’m not convinced that eslint is the right tool for this use-case. While rules can access the filename (if available), such a rule would be limited to only lint filenames of javascript files.

Anyway, there is already a plugin for this [eslint-plugin-filenames](https://github.com/selaux/eslint-plugin-filenames). A more generic tool (which can lint all kinds of files) is [fs-lint](https://www.npmjs.com/package/fs-lint).

**Comment by xjamundx** [comment]
I know I always have weird use cases. I'll just use the plugin, thanks for the pointer!
