### ISSUE TITLE
Skip cascading or from reading the package.json  as config

### ISSUE THREAD

**Issue by lucasmotta** [eslint/eslint#2416]
Whenever I run `eslint`, it tries to read the `.eslintrc` and the `package.json` inside directories.
The problem in my case is that one of my package.json file has some `lodash` template tags, which breaks the JS-YAML parser:

```
/Users/lucas/test-project/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:60
            throw e;
                  ^
YAMLException: Cannot read config file: /Users/lucas/test-project/template/package.json
Error: JS-YAML: missed comma between flow collection entries at line 15, column 26:
        "gulp-util": "^3.0.4"<% if(js) { %>,
```

So is there any way of stopping the "cascading and hierarchy"? I already have a `.eslintrc` at the root of my project and I want that to be the only config file to be checked.

**Comment by michaelficarra** [comment]
Why do you have non-JSON in your package.json file? If you're generating the file, name the source something else.

**Comment by nzakas** [comment]
There's no way to stop this behavior. You need to have package.json or .eslintrc as syntactically valid in order for ESLint to use them. If you're using a template to generate package.json, then you should be sure the template has a different name.

**Comment by lucasmotta** [comment]
@michaelficarra yeah will do that - thanks anyway :)
