### ISSUE TITLE
.config/.eslint

### ISSUE THREAD

**Issue by shannonmoeller** [eslint/eslint#2426]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `findup-sync`, `travis-ci` and `zuul` repos.

**Comment by gyandeeps** [comment]
Can you briefly explain what are you proposing here?

**Comment by nzakas** [comment]
You can already use package.json to specify your ESLint config, if you prefer: http://eslint.org/docs/user-guide/configuring

**Comment by shannonmoeller** [comment]
@gyandeeps I'm recommending that `.config/` directory be added to the list of default locations to check for an `.eslintrc` file. The idea here is to foster the use of [http://standards.freedesktop.org/basedir-spec/latest/index.html](http://standards.freedesktop.org/basedir-spec/latest/index.html) where `$HOME` is a module's root directory to [declutter](http://unix.stackexchange.com/a/38871) module repos.

I understand that the path can be configured in package.json, but that's replacing file noise with config noise and requires additional effort in every project. This is one request of many made to some of the top best-practice CLI utilities out there in the node.js community.

**Comment by nzakas** [comment]
I'm sorry, I don't see any benefit to making such a change. We rely on `.eslintrc ` files to be in the same directory as the code it refers to. It would be confusing to have the top level config in a separate directory, and would definitely be impossible to get everyone to add a `.config` to all levels of their project.

Aesthetics aren't nearly as important as functionality that many people are dependent on and used to, so I'm afraid there is no chance we will make any such change.
