### ISSUE TITLE
Complexity reporter

### ISSUE THREAD

**Issue by romeovs** [eslint/eslint#2429]
Is there a way to get the cyclomatic complexity that eslint calculates in a report?

And are there plans to add more code quality measures to eslint?
It would be very nice if eslint could also serve as a code quality tool.

**Comment by michaelficarra** [comment]
Why would eslint do this? You should use a separate tool for distinct tasks. escomplex is already very good at this.

**Comment by romeovs** [comment]
escomplex isn't nearly as pluggable as eslint. I haven't got it to work with my es6 codebase (although that might be my failure). I view code quality as a part of the linting task.  And since eslint is already generating some metrics, why not be able to view them?

**Comment by michaelficarra** [comment]
eslint is not generating any metrics that I know of. And even if escomplex didn't exist, I would still not want all of that implemented in eslint. Proper modularisation would put it in its own project.

**Comment by romeovs** [comment]
what does it use for the cyclomatic complexity rule then? But your answer is clear. I will look for other tools to do code quality.

**Comment by michaelficarra** [comment]
Which rule reports on cyclomatic complexity?

**Comment by romeovs** [comment]
[the cyclomatic complexity rule](https://github.com/eslint/eslint/blob/c9139375f872d1b696bab0046b0d62081b71c898/lib/rules/complexity.js) limits the maximum cyclomatic complexity.

**Comment by michaelficarra** [comment]
This is being calculated in the rule, though. I thought you meant it was something that the eslint engine provided to rules, like scope information.

**Comment by nzakas** [comment]
ESLint isn't designed to produce code metrics, only to identify problems. We don't have any affordances for creating the type of report you're looking for.

**Comment by romeovs** [comment]
okay. It was just a thought! I love `eslint` for the rest 😊
