### ISSUE TITLE
New rule suggestion: no-variable-names

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint#2431]
Now that a lot of people are transpiling their code, it'd be useful to be able to blacklist the use of specific variable names.

For example, if a project relies on rest parameters it might be useful to blacklist the `arguments` variable name from even being used so that the following code prints a linting error:
```js
function f() {
    for (let i = 0; i < arguments.length; i++) {
        console.log(arguments[i]);
    }
}
```

Another example is `require`. If someone transpiles their code via Babel, they might want to use ES6 modules everywhere so the following code:
```js
const koa = require('koa');
```
throws as one is expected to write:
```js
import koa from 'koa';
```

This could be handled by a config:
```js
{
    "rules": {
        "no-variable-names": [2, ["arguments", "require"]]
    }
}
```

**Comment by nzakas** [comment]
This is similar to some other suggestions we've received, and I'll repeat here the problem we run into: variables are used in a number of ways, and the semantics of those uses aren't always clear. They can be used:

1. In a variable declaration
2. As an assignment target (`x = 0`)
3. As an assignment value  (`x = y`)
4. As a function argument
5. As a function name
6. As a class name
7. In a function call (`x()`)
8. In a method call (`x.y()`)

So if we ban identifier names, where do we ban them? Everywhere? 

From experience, banning everywhere tends to lead to a trickle of requirements to make an exception in "just this one spot", and then the rule turns to chaos.

For `arguments`, it might be okay to just block it outright. But `require` is dicey... You wouldn't want to allow that identifier ever?

So I'd ask you to consider, what are you really trying to achieve?

**Comment by mzgol** [comment]
> So if we ban identifier names, where do we ban them? Everywhere?

I was thinking about everywhere

> For arguments, it might be okay to just block it outright.

Yep, if nothing else, this one would be useful. But any rule to block identifiers globally could accept an identifier list as a parameter and support all names, no just `arguments`.

> But require is dicey... You wouldn't want to allow that identifier ever?

I see your point; using `require` as a variable name would be right but it's hard to distinguish it from a Node call statically (if not impossible outright) so I'd rather just ban the entire identifier name everywhere in the project than allow someone to accidentally use it & break the style guide.

**Comment by rlidwka** [comment]
I see two separate rules here:

1. prefer rest over `arguments`
2. blacklist a certain global variable (e.g. `require`), i.e. remove that variable from the list of globals

Those are two separate things and shouldn't be mixed to one rule

**Comment by nzakas** [comment]
@rlidwka can you file a separate issue for that first one?

The second one is very different from what @mzgol is requesting.

Again, my concern with "ban identifier" is that there will likely be a long tail of exceptions requested because identifiers are used in so many places. Is there a way we can narrow the field? 

For instance, the `no-underscore-dangle` rule has many of the same problems, and we are still getting requests for exceptions in various cases.

**Comment by rlidwka** [comment]
> @rlidwka can you file a separate issue for that first one?

I'm very not interested in "rest vs arguments" rule, because it's purely a style issue.

Second one however is more important. As far as I see, @mzgol has a global variable named "require" (set with node environment presumably) and doesn't want anybody to use that one. But code like that:

```js
function something() {
  var require = 123;
  return require;
}
```

... is a fair game, right? It's not a reserved identifier or anything.

**Comment by nzakas** [comment]
I'm not sure what you're asking.

**Comment by xjamundx** [comment]
@rlidwka `require` isn't part of the language spec AFAIK, it's just injected into the modules at run-time. Pretty sure you can shadow/override it to your hearts content....

**Comment by xjamundx** [comment]
I'd love to see this developed first as a plugin where maybe some of the kinks could be worked out. Internally we've played around with things like this to enforce for example names of things like `err` and `callback` and ban `error` and `cb`. It works alright, but there are a bunch of edge cases.

**Comment by nzakas** [comment]
Agreed - where there isn't enough clarity, it's best to pursue as a plugin. We can't become the backlog for every rule everyone wants - this is exactly why we created plugins. :)
