### ISSUE TITLE
Space-in-brackets fails on import without binding

### ISSUE THREAD

**Issue by joshq00** [eslint/eslint#2437]
space-in-brackets throws an error when an import declaration does not define a variable.

Setting:
`"space-in-brackets": [2, "always"]`

Code:
`import 'xyz';`

```
eslint\lib\rules\space-in-brackets.js:236
            if (firstSpecifier.type === "ImportSpecifier" && lastSpecifier.typ
                              ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ImportDeclaration (eslint\lib\rules\space-in-brackets.js:236:31)
```

Quick assumption at a fix: adding the following to `space-in-brackets#ImportDeclaration`
```js
if ( node.specifiers.length === 0 ) {
    return;
}
```

From [mozilla-import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import):
> Import an entire module for side effects only, without importing any bindings.
>
> ```js
> import "my-module.js";
> ```

**Comment by nzakas** [comment]
Yeah, we've run into this in a few places. Easy fix.

**Comment by gyandeeps** [comment]
Duplicate https://github.com/eslint/eslint/issues/2378
This has been fixed but not yet released https://github.com/eslint/eslint/pull/2385
I think we can close this issue.

**Comment by nzakas** [comment]
Ah, nice catch @gyandeeps . Feel free to close things you find as duplicates.
