### ISSUE TITLE
Angular2 Linting

### ISSUE THREAD

**Issue by peteringram0** [eslint/eslint#2446]
Hi Guys, 

Im trying out ESlint against Angualr2 (Typescript) and running into some issues i hope someone will be able to point me in the right direction on.

.eslintrc file
`{
	"env": {
		"es6": true
	},
	"ecmaFeatures": {
		"modules": true
	}
}`

Stuff ESLint does not seem to like with this config:
`import {Component, View, bootstrap} from 'angular2/angular2';`
`@Component({});`
`@View`
`name: string;`

https://angular.io/docs/js/latest/quickstart.html

**Comment by ilyavolodin** [comment]
@peteringram0  I assume that you are trying to lint uncompiled typescript, right? ESLint is build for JavaScript. Typescript syntax is quite different from JavaScript, so espree will not be able to parse it. You should try TSLint instead.
We have no plans to support TypeScript.

**Comment by tjoskar** [comment]
Hi,

If one use the babel-plugin (https://github.com/babel/babel-eslint) which enables all es6 and es7 features, you should be able to use eslint with typescript. 

Eslint feels more stable than tslint and I'm already using eslint on several js-projects and it should be nice to use it on typescript aswell but I can't get it to work. 

If I creates two files: `test.js` and `test.ts` and runs `eslint .` eslint will only parse `test.js`. I can however run `eslint *.ts` (or `eslint test.ts`) and its parse `test.ts` aswell but I want to parse all `ts` files per default (to be able to use eslint in difrent editors). How do I change this behavior?

**Comment by ilyavolodin** [comment]
@tjoskar when you run eslint, you should specify command line option `--ext` for eslint to be able to lint *.ts files. More information [here](http://eslint.org/docs/user-guide/command-line-interface#ext)

**Comment by tjoskar** [comment]
@ilyavolodin, Thanks!

**Comment by pixelshaded** [comment]
I'm having some trouble with babel-eslint. If I add a class or enum to the ts file I get parsing errors aka unexpected token.

**Comment by ilyavolodin** [comment]
@pixelshaded It's probably an issue for `babel-eslint`. We don't natively support TypeScript in ESLint.

**Comment by pixelshaded** [comment]
one of the ecmaFeatures is jsx. Doesn't jsx use strong typing like this?

**Comment by ilyavolodin** [comment]
Not as far as I know. JSX doesn't use strong typing to the best of my knowledge.

**Comment by lo1tuma** [comment]
@ilyavolodin is right. You can read the jsx specification [here](https://facebook.github.io/jsx/).
