### ISSUE TITLE
operator-linebreak doesn't apply to string concatenation

### ISSUE THREAD

**Issue by glenjamin** [eslint/eslint#2450]
Adding strings together is the most common case where I find myself breaking operators across multiple lines.

As far as I can tell this rule doesn't do anything on string concat - although I might have overlooked a setting or another rule.

I'm unsure whether a better approach is a new rule which covers concat, or simply expanding this one.

**Comment by nzakas** [comment]
Can you please put together some sample code, run it through ESLint, and share both the code and the output? It helps to talk specifics.

**Comment by glenjamin** [comment]
Hrm, can't reproduce now - that's what I get for rushing a report.

Sorry for the noise, I must have had an invalid eslint config when I was trying it before!
