### ISSUE TITLE
Speed up site generation

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#2475]
The site generation script is now taking minutes to run, which is really frustrating. This needs to be sped up for my sanity.

I believe the biggest time-consuming piece is still the part where we determine the first version that a rule appeared in. This info should be cached so we don't need to re-run it each time, as the version rules first appeared in doesn't ever change.

**Comment by ilyavolodin** [comment]
Dupe of #2003 I'll close #2003

**Comment by ilyavolodin** [comment]
Just measured it. You are correct. Each file takes 200ms on average to retrieve first version.
