### ISSUE TITLE
Custom Rules - context question

### ISSUE THREAD

**Issue by davidamir10** [eslint/eslint#2485]
Hi,

I would like to create a custom rule that validates correct call function usage.
So, I could create a rule that checks nodes of type CallExpression and verify that it is calling it correctly.
But, in my use case it can be that a certain object is created, and then method of that object is called:
var x = new Person();
x.getName();

I need a context that will help me to infer this relation.
Is there a way to collect the information during ESLint parser execution (like a visitor)? could you suggest another way?

Thanks in advance,
Amir

**Comment by nzakas** [comment]
You would need to create that context yourself by looking at the AST.

**Comment by davidamir10** [comment]
Hi Nicholas,

Thanks for your answer.
if I understand you correctly, you suggest to collect the context during rule execution?
the problem is that I might need the AST based context in various custom rules, so I prefer to collect it in a "central" point before my custom rules are called. this is why I thought that another parameter in the API would be a solution.
what do you think?

Regards,
Amir

**Comment by nzakas** [comment]
You'll need to do that yourself.

**Comment by ilyavolodin** [comment]
@davidamir10 We discussed ability for rules to share information before, and decided against it. ESLint was created to have each rule to be a stand-alone construct. So I don't think we will provide a centralized point of collecting context. You probably want to do that in each rule as a shared library.
