### ISSUE TITLE
Error: Cannot assign to read only property 'env' of .eslintrc

### ISSUE THREAD

**Issue by amatiasq** [eslint/eslint#2488]
I was having the same error as #1823:

    amatiasq:~/frontend (master)$ eslint common/app-bootstrap.js
    /usr/local/lib/node_modules/eslint/lib/util.js:50
                base[key] = mergeConfigs(base[key] || {}, custom[key]);
                          ^
    TypeError: Cannot assign to read only property 'env' of .eslintrc
        at /usr/local/lib/node_modules/eslint/lib/util.js:50:23
        at Array.forEach (native)
        at Object.mergeConfigs (/usr/local/lib/node_modules/eslint/lib/util.js:25:25)
        at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:163:23)
        at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:293:22)
        at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:178:27)
        at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:299:26
        at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
        at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9
        at Array.forEach (native)

I started trying random stuff until it worked when I removed `eslintConfig` from package.json

Config file:

    env:
      browser: true

    globals:
      define: true

    rules:
      indent: 2
      brace-style: [2, "1tbs"]
      camelcase: 1
      comma-style: [2, "last"]
      comma-dangle: "always-multiline"
      curly: [1, "multi"]
      default-case: 2
      func-style: [2, "declaration"]
      guard-for-in: 2
      indent: [2, 2]
      no-console: 0
      no-floating-decimal: 2
      no-nested-ternary: 2
      no-undefined: 2
      no-use-before-define: [2, "nofunc"]
      quotes: [2, "single", "avoid-escape"]
      radix: 2
      space-after-function-name: [2, "never"]
      space-after-keywords: [2, "always"]
      space-before-blocks: 2
      spaced-line-comment: [2, "always", { exceptions: ["-"]}]
      strict: [2, "function"]
      valid-jsdoc: [2, { prefer: { "return": "returns"}}]
      wrap-iife: 2

Version:

    amatiasq:~/frontend (master)$ eslint --version
    v0.20.0

**Comment by gyandeeps** [comment]
Are you saying that when you had all of your config inside package.json then it give errors  but after you created its own config file (like you shown above) it works fine?

**Comment by amatiasq** [comment]
No, I'm saying I have a .eslintrc file on my project's root folder and I had a `eslintConfig` entry on my package.json file with value `".eslintrc"` (I know it's not necessary but my idea was to move the config file to other location so I needed `eslintConfig`) and every time I executed eslint it failed with the error shown above until I removed

    "eslintConfig": ".eslintrc",

From my package.json file.

**Comment by gyandeeps** [comment]
It used to work on old version and now it throws error?

**Comment by amatiasq** [comment]
No, it's the first time I use ESLint.

**Comment by gyandeeps** [comment]
Why I ask is because you referenced an issue which talked about nodejs 0.12.2 version vs old version.

**Comment by amatiasq** [comment]
I referenced the issue because it's the only one with the same error as I had but @nzakas say's it's different. I pasted the version with the bug on the issue description.

**Comment by gyandeeps** [comment]
It is different. That issue was logged by me. Yours is different.

**Comment by gyandeeps** [comment]
You should specify the actual config inside package.json file and not the name of the file for config.

**Comment by amatiasq** [comment]
Then that's the reason, thanks @gyandeeps
