### ISSUE TITLE
`--init` generates incorrect indent "tabs" rule

### ISSUE THREAD

**Issue by remko** [eslint/eslint#2493]
It seems that with ESLint 0.21.0, the tabs indent rule got broken.
With the default `eslint --init` (which generates an indent: tabs), the following:

    function x() {
    <TAB>var y = 3;
    }

gives an:
   
    2:4 error Expected indentation of 4 characters  (indent)

**Comment by remko** [comment]
Figured out the problem, `eslint --init` generates

    {
        "rules": {
            "indent": [ 2, "tabs" ]
        }
    }

That should be `tab` instead of `tabs` it seems.
Changed the title accordingly.

**Comment by ilyavolodin** [comment]
Thanks. We'll fix it. We have a pull request in progress to validate incorrect config settings.

**Comment by nzakas** [comment]
Working on this.
