### ISSUE TITLE
eslint --rule 'rule-name: true' should not fail silently

### ISSUE THREAD

**Issue by mozfreddyb** [eslint/eslint#2498]
I wasted an hour or so running eslint and trying to set the rule preference to a boolean instead of the required 0/1/2 value.

e.g. `eslint --rule 'brace-style: true'` instead of `eslint --rule 'brace-style: 2'`.

I propose that eslint warns or fails when getting a boolean instead of a number.

**Comment by gyandeeps** [comment]
We are working on an enhancement which is going to validate the rules and its configurations also.

**Comment by mozfreddyb** [comment]
It seems like the source line 531 in https://github.com/eslint/eslint/blob/be3702cfd8c02d6118668b7fde3084826efff66c/lib/eslint.js#L519-533 could be improved with a console.log(…) call.

**Comment by nzakas** [comment]
Already being covered by #2179.
