### ISSUE TITLE
Name question: no-empty-class

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#2508]
Before ES6 came along `no-empty-class` may not have been okay, but now it's kind of a confusing name. What would the thoughts be on a rename to `no-empty-regex-class` or something?

**Comment by michaelficarra** [comment]
`no-empty-character-class`

**Comment by nzakas** [comment]
+1 to @michaelficarra 's suggestion. As with other changes, we'd need to create a new copy of the rule and deprecate the old one before removing in 1.0.0.

**Comment by xjamundx** [comment]
working on it...
