### ISSUE TITLE
Support multiple configs in one shareable module

### ISSUE THREAD

**Issue by goloroden** [eslint/eslint#2511]
Right now, ESLint assumes that a shareable module exports a single set of configuration settings. What I would like to do is to export multiple ones (e.g., I have two sets, one for the client, one for the server, that I would like to manage in a single repo).

So supporting something like this would be awesome:

### `index.js`

```javascript
module.exports = {
  server: { /* server config goes here */ },
  client: { /* client config goes here */ }
};
```

### In your `.eslintrc` file:

```json
"extends": "eslint-config-myconfig/server"
```

Is something like this possible?

**Comment by gcochard** [comment]
I think having multiple exports might be something that could be handled, but then how do you reference them in the extends, something like `extends: 'myconfig.server'`?

Alternatively, you could create two configs, then just add both to your package and in both `.eslintrc` files.

**Comment by ilyavolodin** [comment]
I'm not sure I see a big advantage of implementing something like that. What's stopping you from publishing two separate NPM modules?

**Comment by nzakas** [comment]
This is technically possible, and I considered trying it for the initial implementation, but ultimately decided not to for the sake of simplicity. I'm not sure it's necessary, and as such, I'd rather focus on the things that are.

**Comment by goloroden** [comment]
@ilyavolodin Nothing is stopping me, except that I actually have *four* configurations:

- Server (ES5)
- Server (ES6)
- Client (ES5)
- Client (ES6)

And it is *way* more comfortable to maintain one single repo and module than four that I have to keep up-to-date and in-sync.

Not to mention having to write four readme files, four .gitignore files, and so on…

**Comment by nzakas** [comment]
@goloroden it's been four days since this feature was released, so I think it's too soon to make statements saying it's not enough for many teams. 

We will look at enhancements when we have more feedback.

**Comment by goloroden** [comment]
I didn't say that it's not enough for many teams, I said that *I think* that is it's not enough for many teams ;-)

**Comment by jonathanKingston** [comment]
Another possibility is using variables passed into the package perhaps. I was considering asking the same as it seems excessive to publish at least two of the same setup.

Without looking how does the native node rules get defaulted different?

**Comment by feross** [comment]
I don't need this feature, and it might be unnecessary. But it might make sense to just use the node.js `require` semantics for the `extends` key. Basically, if I wanted to ship two configs in a single module, I would just make another file in the root that could be referred to with:

```
{
    "extends": "eslint-config-myconfig/server"
}
```

With `require`, that would load `node_modules/eslint-config-myconfig/server.js` or `node_modules/eslint-config-myconfig/server/index.js`

**Comment by nzakas** [comment]
@feross interesting, this might already work. If the `extends` string isn't a path, we just pass it directly to `require`, and since `require` has this behavior already... Seems like it should just work.

Anyone want to give it a try and let us know? (I'm on mobile until end of this week)

**Comment by feross** [comment]
Yep, it works. Glad I could be helpful  :smile:

**Comment by goloroden** [comment]
Wow, I didn't know that this works with `require`, but this way you solved my issue and I learned something new.

Two birds, one stone :-)
