### ISSUE TITLE
Nested API calls breaks shareable configs

### ISSUE THREAD

**Issue by jonathanKingston** [eslint/eslint#2529]
# Explanation

After running with the latest master which uses: #2489  I still suffer from not being able to load my module when using the API.

```
Build failed.
File: app.js
Cannot find module 'eslint-config-ember'
Referenced from: /home/jonathan/testingprojects/testingeslintherrors/.eslintrc
Error: Cannot find module 'eslint-config-ember'
Referenced from: /home/jonathan/testingprojects/testingeslintherrors/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
```

So the package `broccoli-lint-eslint` is using `CLIEngine` which has been consumed by `eslint-config-eslint` in a sample Ember app.

The config I am using is:
```
{
  "extends": "ember"
}
```

ember-cli-eslint@beta and eslint-config-ember@0.0.3 are installed on the ember app.

# Issue

Node is running `require` relative to `broccoli-lint-eslint` directory rather than relative to the .eslintrc.

# Solution

Hacking the ESLint lib/config.js code to do the following got his working for me.
```
function loadConfig(filePath, includePath) {
...
            var relative = includePath || '';

            var packagedConfig = require(relative + '/node_modules/' +  filePath);
...
            try {
                config = util.mergeConfigs(loadConfig(parentPath, path.dirname(filePath)), config);
```

**Comment by nzakas** [comment]
Can you show the directory structure of your project? I'm having a hard time understanding the dependency relationships from your description.

FWIW, we intend `extends` to run in the current working directory, not relative to the config file.

**Comment by jonathanKingston** [comment]
```
~/projectName/
~/projectName/node_modules/eslint-config-eslint/
~/projectName/node_modules/ember-cli-eslint/
~/projectName/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/
~/projectName/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint
```

I'm then in ~/projectName/ running `npm test` which triggers the test to be run in the `broccoli-lint-eslint` project.

Installing `eslint-config-eslint` in the `broccoli-lint-eslint` fixes this also however obviously defeats the point of the shared configs.


So you are suggesting `process.cwd()` would be perhaps better as a prefix to the files?
Wouldn't that then break the inheritance if anyone ever wanted to chain multiple together, my project then would need to install the whole tree of dependencies manually.
I'm not sure if you wanted multiple levels of extension however the current code allows for it.

**Comment by ilyavolodin** [comment]
It looks like `broccali-lint-eslint` might be switching working directory to itself. Either that, or your `npm test` does.

**Comment by jonathanKingston** [comment]
@ilyavolodin it is believable certainly I will take a further look.

**Comment by gyandeeps** [comment]
Based on how native `require` works and looking at your project structure, it should pick your config file.

**Comment by jonathanKingston** [comment]
I use the following code which ends up running per file:
```
var result = this.cli.executeOnFiles([this.eslintrc + '/' + relativePath]);
```
So this resolves to paths like:
```
tests/helpers/resolver.js
tests/helpers/start-app.js
tests/test-helper.js
```

Which this uses the correct .eslintrc file for the base of the project.

**Comment by gyandeeps** [comment]
This is how the `require` lookup would work in your case to look for `eslint-config-eslint` module:

```
~/projectName/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint/lib/node_modules
~/projectName/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules
~/projectName/node_modules/ember-cli-eslint/node_modules
~/projectName/node_modules
...
```

**Comment by jonathanKingston** [comment]
Yeah I thought as much.
I'll reinstall it might be because I am using `npm link` all through the stack etc. Which if it is executing up through the stack may not follow that path.

**Comment by jonathanKingston** [comment]
I **think** this is ok, so closing however it may return as I'm not certain this is bug free.
As mentioned I think everything being `npm link`'ed was the cause.
Thanks for all your help.
