### ISSUE TITLE
rule suggestion: newline before comment

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#2534]
We have this rule in the PayPal UIE style guide and I couldn't find a way to enable it with ESLint.

I think JSCS has something similar:
http://jscs.info/rule/requirePaddingNewLinesBeforeLineComments.html

I'd be happy implementing it.

**Comment by gyandeeps** [comment]
I like the idea. :+1:

**Comment by lo1tuma** [comment]
Looks like a duplicate of #1344.

**Comment by gyandeeps** [comment]
yup.
