### ISSUE TITLE
Is there a way to disable a global?

### ISSUE THREAD

**Issue by apechimp** [eslint/eslint#2536]
If I have a .eslintrc like

```json
{
  "globals": {
    "foo": false
  }
}
```

Is there a way to make it so I can do something like the following?

```javascript
var foo = 'bar';
```

I realize I can set `/* globals foo: true */`, but that make `foo` writable which isn't what I want: I want to be able to shadow it.

**Comment by nzakas** [comment]
There's no way to delete a global definition once it has been introduced. You can flip between read only or not, but there's no other modification possible.

Your example isn't shadowing, it's overwriting.

**Comment by apechimp** [comment]
Ahh! Indeed: it's overwriting. Thanks for your help!
