### ISSUE TITLE
New rule suggestion: no-up-requires

### ISSUE THREAD

**Issue by denis-sokolov** [eslint/eslint#2539]
I would like to add a new rule to eslint - `no-up-requires`.
It would disallow moving up the directory tree in static `require` calls.

The following would be invalid when the rule is enabled:
```javascript
require('../foo');
require('./../bar');
require('../../bar');
```

The use case is - it is sometimes customary to mirror the project module dependency tree using the filesystem. That makes the project structure considerably easier to understand, it almost guarantees a lack of an intricate web of dependencies inside a project.

The error thus would prevent a semantic error by a developer. It would also prevent developers from the temptation of using the up selector "just this once".

Having this error in the list will not only allow projects with this structure to enforce it, but perhaps having it in the list of rules can cause new developers to consider such a possibility for their projects.

The rule is very strict, and definitely should be off by default (this choice is irrelevant with 1.0.0 using `--reset`).

**Comment by nzakas** [comment]
Thanks for the suggestion. The first question to answer is if it makes sense for this did to be in ESLint itself, or if it is better as a plugin. Thoughts? @ilyavolodin @lo1tuma @btmills @xjamundx

**Comment by gyandeeps** [comment]
Whenever I think of how the project should be organised, its becomes very personal and scenario based.
So for me this should more likely be a plugin.

**Comment by denis-sokolov** [comment]
That is reasonable.
I suppose it would be beneficial to come up with a stricter definition whether a rule belongs in the core or in a plugin. Ultimately every rule is useful to somebody and almost every rule is not useful to somebody.

**Comment by ilyavolodin** [comment]
I could see a value of creating a generic `require-path-constraints` rule that would take options that would specify if you are allowed to go up or down directory structure and if you do, how far. While everyone has their own preference in how they layout project, this rule would allow them to configure constraints based on their preferences. Something like this, I think:
```json
"require-path-constraints": [2, { "up": "never", "down": 2 }] //can't go up, can go down up to 2 levels deep
```
should be able to provide value while not limiting users.
I do not see a whole lot of value in creating a bunch of separate rules for the same task.

P.S. @denis-sokolov Problem is that every rule request is different. We have to play it by the ear, and not limit ourselves to strict guidelines in this case.

**Comment by mathieumg** [comment]
I think the suggestion by @ilyavolodin makes a lot of sense. I'd welcome this rule, as a plugin or as part of ESLint itself.

**Comment by nzakas** [comment]
@denis-sokolov we do have some general guidelines: http://eslint.org/docs/developer-guide/working-with-rules#rule-acceptance-criteria

However, as @ilyavolodin points out, these aren't hard-and-fast.

**Comment by ilyavolodin** [comment]
Closing this in favor of #2555 that make this idea an option of a larger rule.
