### ISSUE TITLE
New rule suggestion: no-deep-file-requires

### ISSUE THREAD

**Issue by denis-sokolov** [eslint/eslint#2541]
I would like to add a new rule to eslint - `no-deep-file-requires`.
It would disallow moving deep the directory tree in static `require` calls.

The following would be invalid when the rule is enabled:
```javascript
require('./foo/bar');
require('./foo/bar.js');
require('./foo/bar/quux');
require('../foo/bar');
```

The following would still be valid when the rule is enabled:
```javascript
require('./foo');
require('../foo');
require('foo/bar/quux');
```

The use case is - it is sometimes customary to mirror the project module dependency tree using the filesystem. That makes the project structure considerably easier to understand, it almost guarantees a lack of an intricate web of dependencies inside a project. Any sub-dependencies that need to be exposed, can be exposed through the owner of the directory, `index.js`.

The error thus would prevent a semantic error by a developer. It would also prevent developers from the temptation of diving deep into sub-dependencies "just this once".

Having this error in the list will not only allow projects with this structure to enforce it, but perhaps having it in the list of rules can cause new developers to consider such a possibility for their projects.

The rule is very strict, and definitely should be off by default (this choice is irrelevant with 1.0.0 using `--reset`).

**Comment by nzakas** [comment]
I'm not sure I understand the point of this rule. You want to disallow subdirectory access? At first glance, this seems like a personal preference that is probably better off as a plugin rule.

**Comment by gyandeeps** [comment]
To me its conceptually similar to https://github.com/eslint/eslint/issues/2539

**Comment by denis-sokolov** [comment]
@nzakas, I want to enforce encapsulation.
A parent module can only access the interface of the subdirectory, `foo/index.js`. Whatever is deeper is implementation details of `foo`.
This way I treat every subdirectory in my project as a dependency that I did not bother to publish and that I can publish at any moment as a stand-alone.

If you like the idea of a combined rule between this and #2539, we can close this and discuss in #2539 further.

**Comment by nzakas** [comment]
Yeah, let's talk on #2539 if there are some generic constraints for require.
