### ISSUE TITLE
Feature Request: set "extends" option via CLI

### ISSUE THREAD

**Issue by shinnn** [eslint/eslint#2543]
I'd like to set the value of [`extends`](http://eslint.org/docs/user-guide/configuring#extending-configuration-files) option from CLI like below:

```
eslint --extends (eslint-config-)myrules *.js
```

If the CLI have this option, we don't need to create `.eslintrc` only for extending a configuration file.

**Comment by nzakas** [comment]
I don't think adding `--extends ` to the CLI makes sense, because there's no config that could extend anything.

It might make sense to let `-c` accept a shareable config, though.

**Comment by shinnn** [comment]
> because there's no config that could extend anything.

I agree about it.

> It might make sense to let `-c` accept a shareable config, though.

Better idea :+1: It would be more helpful.

**Comment by nzakas** [comment]
Okay, we can take a look at that.

**Comment by xjamundx** [comment]
Also with regard to the `default` options. We'll want to be able to turn them on from the command line easily.

**Comment by nzakas** [comment]
@xjamundx `-c "eslint:default" would do that

**Comment by shinnn** [comment]
I implemented the feature mentioned in https://github.com/eslint/eslint/issues/2543#issuecomment-102441119:

> let `-c` accept a shareable config

I'll submit a pull request soon.

**Comment by shinnn** [comment]
Completed. #3063
