### ISSUE TITLE
es6 class declarations trigger "no-shadow"

### ISSUE THREAD

**Issue by jsg2021** [eslint/eslint#2546]
I have a file with just `class Foo {}` and it triggers the error.  I've tried both default and babel parsers.

eslint@0.21.1

**Comment by gyandeeps** [comment]
same as https://github.com/eslint/eslint/issues/2545
I am going to close this and @jsg2021 you can track the issue there.

**Comment by jsg2021** [comment]
thanks, sorry for the dupe
