### ISSUE TITLE
Missing release notes on eslint v0.21.1 release tag

### ISSUE THREAD

**Issue by gcochard** [eslint/eslint#2549]
https://github.com/eslint/eslint/releases/tag/v0.21.1 has no content yet.

**Comment by gyandeeps** [comment]
Will get that updated.

**Comment by nzakas** [comment]
Fixed. This still has to be done manually, so I sometimes forget. Reminder that all this information is already in CHANGELOG.md, which is automatically updated for each release: https://github.com/eslint/eslint/commits/master/CHANGELOG.md

**Comment by gcochard** [comment]
Thanks. I think there is an API to update release tag info, would a PR be welcome to integrate that with the auto changeling update?

**Comment by nzakas** [comment]
Yes, most definitely.

**Comment by gcochard** [comment]
Sounds good. I will create a new issue when it is ready to go.
