### ISSUE TITLE
no-shadow errors are thrown twice in ES6 class definitions

### ISSUE THREAD

**Issue by taion** [eslint/eslint#2552]
As mentioned in #2547, against both 0.21.0 and 0.21.1 + #2547, I get

```
jjia@jjia-mbp:~/tmp$ cat .eslintrc
{"env": {"es6": true}, "rules": {"strict": 0}}
jjia@jjia-mbp:~/tmp$ cat test.js
class A { constructor() { var A; this.dummy = A; }; }
jjia@jjia-mbp:~/tmp$ eslint test.js

test.js
  1:30  error  A is already declared in the upper scope  no-shadow
  1:30  error  A is already declared in the upper scope  no-shadow

✖ 2 problems (2 errors, 0 warnings)
```

I expect to only see this error once.

**Comment by woodb** [comment]
:+1: Glad I'm not the only one that was seeing this, thanks for creating the issue @taion

**Comment by michaelficarra** [comment]
Well you're shadowing two bindings created from a single construct, so this makes sense. You could argue it's not necessary to warn about both shadowings, but then this would be an enhancement, not a bug.

**Comment by taion** [comment]
I just filed this as requested per https://github.com/eslint/eslint/pull/2547#issuecomment-102644231. I do think it's fairly unintuitive and confusing to see this error twice, though.

**Comment by nzakas** [comment]
@michaelficarra which two bindings are you referring to?

**Comment by michaelficarra** [comment]
@nzakas see https://github.com/estools/escope/pull/65#issuecomment-103055176

**Comment by nzakas** [comment]
Oh wow, had no idea that was the case. Thanks for explaining.

Even so, this behavior is confusing, so we should fix it.

**Comment by taion** [comment]
Is that also the root cause of #2545, then? Would be good to take out the special-casing logic there if this can be resolved, if so.

**Comment by nzakas** [comment]
Looks like it may be.
