### ISSUE TITLE
no-shadow ignores function and class names that shadow outer vars

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#2556]
```js
(function a() {
  function a(){}
})()
```

This should have a `no-shadow` error, but does not. Same goes for 

```js
(function a() {
  class a{}
})()
```

```js
(function a() {
  (function a{});
})()
```

```js
(function a() {
  (class a{});
})()
```

This behaviour is undocumented and was introduced in [an upgrade of escope](https://github.com/eslint/eslint/commit/a0717687110bdfe544bb8ee6482347d588623116#diff-bb960ca8871dafb0bbd3959858e00231R42).

**Comment by nzakas** [comment]
Are you saying this may be an escope bug?

**Comment by michaelficarra** [comment]
No. These are [explicitly ignored](https://github.com/eslint/eslint/blob/3fec4186a80d1345f6d1e7dfb11c84664ba663da/lib/rules/no-shadow.js#L42-L43) for some reason. The comment does not explain why. The "upgrade of escope" commit also changed unrelated things like this.

**Comment by nzakas** [comment]
They aren't unrelated - escope changed how things worked, so our code had to change accordingly based on the tests we already had.

**Comment by mysticatea** [comment]
Working on this.
