### ISSUE TITLE
Add env: Service Workers

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/eslint#2557]
Browsers are beginning to add service workers, which have a new scope: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope

Could this be added as an env?

**Comment by btmills** [comment]
This looks like a duplicated of #2442, which you'll be happy to know will be fixed in #2537.

**Comment by ilyavolodin** [comment]
Pull request for this is already waiting approval. Closing in favor of #2442

**Comment by lo1tuma** [comment]
AFAIK the ServiceWorker is something different that the web worker.

**Comment by nzakas** [comment]
You are correct.

**Comment by ilyavolodin** [comment]
@OliverJAsh We rely on [globals package](https://github.com/sindresorhus/globals) to provide list of global variables available in different environments. They do not currently have ServiceWorkers. You will need to file a ticket with them in order for us to add it to ESLint.

**Comment by OliverJAsh** [comment]
Tracking https://github.com/sindresorhus/globals/issues/31.
