### ISSUE TITLE
Elision + space-in-brackets

### ISSUE THREAD

**Issue by bathos** [eslint/eslint#2559]
With space-in-brackets set to "always", the following is considered an error:

    let [ , var2 ] = someArr;

Instead, eslint wants `[, var2 ]`. My hunch is that this is not intended behavior -- as far as I can tell, it's inconsistent with the rule settings. Initial elision was an obscure case when it only occurred in array literals, but it's pretty common in binding patterns for destructured assignment.

**Comment by xjamundx** [comment]
+1 for teaching me what an `Elision` is. I've never heard the term before.

FYI the `space-in-brackets` rule is being split into 2 rules with #2226 and #2225.

It might be useful to bring this particular issue as part of the discussion there as they will probably tweak the rules a little bit during the split!

**Comment by nzakas** [comment]
This rule is going away, so we aren't doing any more work on it. See #2226
