### ISSUE TITLE
New formatter

### ISSUE THREAD

**Issue by rizowski** [eslint/eslint#2560]
Would you guys be up to having a new formatter that only prints out the file name count of errors / warnings and leave out the details?

Use case:
I have built [eslint-watch](https://www.npmjs.com/package/eslint-watch) so I can quickly watch a directory without needing to pull in dependencies of webpack or grunt. I have a bunch of files that need to be linted over time and cannot be addressed all at once. It would be nice to have a formatter that will just print out the name of the file and the count of errors/warnings in the file so I at least get the list of files that need addressing for a full directory lint.

I can have a pull request up in a day or so.

**Comment by xjamundx** [comment]
Is there any precedence for this in other linters of what something like this should look like?

**Comment by rizowski** [comment]
It would just be a simple output of something like this:
```
./some/path/to/file.js (35)Errors | (0)Warnings
./some/path/to/this-file.js (4)Errors | (0)Warnings
./some/path/to/js-file.js (0)Errors | (12)Warnings
./some/path/to/and-file.js (2)Errors | (3)Warnings
```
As for precedence, it is just a formatter. However the webpack eslint plugin does lint all files on load, so I could see the benefit of having a formatter that doesn't spit out all the details on a file.

**Comment by nzakas** [comment]
I'd suggest making that as a custom formatter. You can pass any npm/JS name to `-f` and it will work.
