### ISSUE TITLE
Some way to specify rules per file path pattern

### ISSUE THREAD

**Issue by mprokopowicz** [eslint/eslint#2565]
I've following project structure:

```
- root/
--- component/
------ component.js
------ component.test.js
```

component.js is some front-end script, component.test.js is a mocha test.
I need different globals in component and component.test and a few different rules (Like disabling no-unused-expressions in test, because of mochas ```expect(rejectedSpy).to.have.not.been.called;```

For now, I end up with putting all this exceptions in comments at the beginning of test file:
```
/*eslint-env mocha */
/* eslint strict: [2, "global"], no-unused-expressions: [0]*/
```
but it would be great to have one place for this.

**Comment by lo1tuma** [comment]
This is not supported yet, but was already mentioned in the [ESLint 2.0 wishlist](https://github.com/eslint/eslint/issues/2203#issuecomment-88654556).
