### ISSUE TITLE
Plugins ignored when using eslint in node.js

### ISSUE THREAD

**Issue by omerts** [eslint/eslint#2569]
Hello,

I am using eslint in a node.js app, specifically using the verify method. In the config object I pass as a parameter, I am using the 'react' plugin. 
When running my app I get the following error:
```
Error: Definition for rule 'react/jsx-boolean-value' was not found.
```
(I have eslint-plugin-react installed)

**Comment by lo1tuma** [comment]
`verify` doesn’t load plugins. You have to use the `CLIEngine` for this. Have a look at the [documentation](http://eslint.org/docs/developer-guide/nodejs-api#addplugin()) for more details.
