### ISSUE TITLE
Typo in shareable-configs

### ISSUE THREAD

**Issue by ted-piotrowski** [eslint/eslint#2571]
Example

```
module.exports = {

    globals: {
        MyGlobal: true
    },

    rules: {
        semi: [2, "always}"]
    }

};
```

has an extra } at the end of always

**Comment by lo1tuma** [comment]
You are talking about the [example in the documentation](http://eslint.org/docs/developer-guide/shareable-configs#creating-a-shareable-config), right?

**Comment by ted-piotrowski** [comment]
Yes, that's correct.
