### ISSUE TITLE
Bug in newline-after-var

### ISSUE THREAD

**Issue by goloroden** [eslint/eslint#2573]
The following code snippet

    /*eslint-disable no-process-env*/
    var logLevels = process.env.LOG_LEVELS;
    /*eslint-enable no-process-env*/

results in an error of the `newline-after-var` rule. Basically, the rule is right, but I think that this is a valid exception to the rule.

**Comment by gyandeeps** [comment]
I intent of this rule was to have a new line after var which doesn't allow even a comment after that. But i see where you are coming from, I faced the same issue few days back but I ended up actually giving a newline.

**Comment by goloroden** [comment]
You're basically right, but especially if you have this single line as a single block (which contains only the two comments and this line), then an additional new line looks really strange.

**Comment by gyandeeps** [comment]
You can always turn off the rule in-line.

**Comment by goloroden** [comment]
Not sure what you mean by "in-line". Can you elaborate, please?

**Comment by gyandeeps** [comment]
Sorry, multi-tasking...

Here is what you can do:

```js
/*eslint-disable no-process-env*/
var logLevels = process.env.LOG_LEVELS; // eslint-disable-line newline-after-var
/*eslint-enable no-process-env*/
```

or

```js
/*eslint-disable no-process-env, newline-after-var*/
var logLevels = process.env.LOG_LEVELS;
/*eslint-enable no-process-env, newline-after-var*/
```

**Comment by goloroden** [comment]
Ah, okay, thanks :-)

**Comment by gyandeeps** [comment]
I am going to close this issue as I think we are good.
feel free to reopen if you have concerns.

**Comment by lo1tuma** [comment]
```js
var logLevels = process.env.LOG_LEVELS; // eslint-disable-line no-process-env
```
This would be even more easier.

**Comment by gyandeeps** [comment]
@lo1tuma :+1:  :100: 
This is the best solution.

**Comment by goloroden** [comment]
@lo1tuma Good idea, thanks :-)
