### ISSUE TITLE
no-unused-vars does not account for destructing assignment

### ISSUE THREAD

**Issue by sunjay** [eslint/eslint#2576]
> after-used - only **arguments** after the first used argument must be used

http://eslint.org/docs/rules/no-unused-vars.html

The use of arguments here does not account for destructing assignment. Only functions.

Here's an example of what should be valid:

    for (const [arg1, arg2] of args) {
        console.log(arg2);
    }

In this case, there should be no error for arg1 even though it isn't used.

**Comment by michaelficarra** [comment]
No, you can use elision in this position, unlike function parameters.

**Comment by sunjay** [comment]
Cool! I did not know about that feature. Thanks!

For anyone who lands on this

    for (const [, arg2] of args) {
        console.log(arg2);
    }

is a valid way of handling the problem.
