### ISSUE TITLE
ES6 'no-unused-vars' ignore unused import declarations

### ISSUE THREAD

**Issue by pixeldrew** [eslint/eslint#2577]
Would like to add an option to the 'no-unused-vars' rule to ignore unused imports.

For instance:
```js
import plugin from 'plugin'; // defined as a UMD object with a jquery dependency and exports jQuery.fn.plugin 
import $ from 'jquery';

$(ele).plugin();
```
I see this as useful as there are many libraries that add to global objects that are required before the original global object is imported.

**Comment by michaelficarra** [comment]
:-1:. Use `import 'plugin'`.

**Comment by nzakas** [comment]
Agree with @michaelficarra, there's already a way to support that case with regular syntax, so there's no need for a rule exception.

**Comment by pixeldrew** [comment]
ah, good to know. Thanks

**Comment by ffxsam** [comment]
Bringing this issue back from the dead.

We need to have a rule that ignores unused imports, because of this:

```
import React from 'react';
```

I'm not using `React` in the code anywhere, but _not_ importing it causes major breakage.

**Comment by ilyavolodin** [comment]
@ffxsam Use `eslint-plugin-react`, it will mark `React` as used.

**Comment by ffxsam** [comment]
I am using `eslint-plugin-react`.

**Comment by ilyavolodin** [comment]
I know we added an API at some point specifically because React creates a lot of unused variables, and `eslint-plugin-react` uses that API to mark them as used. Chances are, you didn't configure that plugin correctly. I would suggest opening an issue there, somebody should be able to guide you through the setup.

**Comment by ffxsam** [comment]
That's a good idea.. maybe there's some setting that I missed. Thanks!
