### ISSUE TITLE
Teach `capIsNewExceptions` to grok "Foo.Bar"

### ISSUE THREAD

**Issue by wincent** [eslint/eslint#2584]
I'm currently using the following config to prevent eslint from complaining about the "immutable" module's factory methods:

```
"rules" : {
  "new-cap": [2, {
    // for Immutable
    "capIsNewExceptions": ["List", "OrderedSet", "Range"]
  }]
}
```

These are methods which you call like this:

```
import Immutable from 'immutable';
let myList = Immutable.List();
```

The trouble is, if I want to use something like `Immutable.Map`, then I need to add `Map` to the list of exceptions too, which means that calls to the *native* `Map` constructor with a missing `new` keyword will no longer get caught.

It would be really nice if I could use a config like:

```
"rules" : {
  "new-cap": [2, {
    "capIsNewExceptions": ["Immutable.List", "Immutable.OrderedSet", "Immutable.Range"]
  }]
}
```

instead.

For now, the workaround is to create aliases for the Immutable factories, like:

```
import {
  List as ImmutableList,
  Map as ImmutableMap,
  OrderedSet as ImmutableOrderedSet,
  Range as ImmutableRange,
} from 'immutable';
```

And then use the longhand names (`ImmutableList` etc) in the `capIsNewExceptions` list. This is a bit verbose and heavy, but it's the workaround I'm going with for now.

**Comment by LinusU** [comment]
Is there a reason why you aren't typing `let myList = new Immutable.List();`? Babel allows you to instantiate classes without `new` but the ECMAScript 6 standard says to throw a `TypeError`.

**Comment by LinusU** [comment]
> If F’s [[FunctionKind]] internal slot is "classConstructor", throw a TypeError exception.

[Sect. 9.2.2 in the spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-function-objects-call-thisargument-argumentslist)

**Comment by wincent** [comment]
Yep, I'm aware of that. These aren't class constructors; they're factory
functions, like `Symbol`. See the very similar
https://github.com/eslint/eslint/issues/2023#issuecomment-80255655 for some
more context.

**Comment by LinusU** [comment]
Hmm, interesting. I've never seen factory functions that are just the name with capital first char before. I wonder what the reasoning behind `Symbol` where...

**Comment by gyandeeps** [comment]
@eslint/eslint-team Any suggestion/input guys as this has been open for a while now.

**Comment by nzakas** [comment]
Totally missed this. Does someone want to champion this change?

**Comment by mysticatea** [comment]
I want.

**Comment by BYK** [comment]
I support this change too. That said what happens when someone uses `Immutable["Map"]`? Do we catch them or not?

**Comment by mysticatea** [comment]
I thought this does not need to catch computed properties because there are not keywords which starts with upper case. But my plan will compare the source code text (excludes spaces and comments), so `Immutable["Map"]` is caught with `"capIsNewExceptions": ["Immutable[\"Map\"]"]`.

I will work on this.
