### ISSUE TITLE
Add spaced-line-comment option to ignore triple-slash introducing XML doc comments

### ISSUE THREAD

**Issue by cwrea** [eslint/eslint#2588]
Microsoft's Visual Studio has supported the concept of "XML Documentation Comments" [since the advent of C#](https://msdn.microsoft.com/en-us/magazine/cc302121.aspx) in 2002. Microsoft later added support for [JavaScript XML doc comments](https://msdn.microsoft.com/en-us/library/bb514138.aspx) to Visual Studio 2008. XML doc comments for JavaScript are:

> [...] comments that you add to a script to provide information about code elements such as functions, fields, and variables. **In Visual Studio, these text descriptions are displayed with IntelliSense when you reference the script function.** *[emphasis mine]*

```javascript
example.getArea = function(radius) {
    /// <summary>Determines the area of a circle with the specified radius.</summary>
    /// <param name="radius" type="Number">The radius of the circle.</param>
    /// <returns type="Number">The area.</returns>
    var area = Math.PI * radius * radius;
    return area;
};
```
Such comments don't merely feed into HTML doc gen but rather enhance the on-the-fly coding assistance displayed in Visual Studio's editor, and so XML doc comments have been used by many dev teams who use Visual Studio. (The jQuery team even used to publish [vsdoc annotated releases](http://www.learningjquery.com/2009/07/setting-up-visual-studio-intellisense-for-jquery) for the benefit of Visual Studio users.)

Unfortunately, the **triple-slash sequence** that introduces an XML doc comment causes **false positives** in ESLint's `spaced-line-comment` rule. As far as I can tell, the current way to specify `exceptions` isn't flexible enough to allow for arbitrary text after a triple-slash comment has started. It would be nice to be able to configure `spaced-line-comment` to know that within an XML doc comment (denoted by a triple-slash), anything goes, but to otherwise scrutinize regular two-slash line comments.

(I acknowledge there exist [non-Microsoft alternatives](http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/) that don't trigger false positives since they use multi-line or two-slash comment styles. Still, triple-slash XML doc comments have been around for a while and persist in large JavaScript code bases, particularly within the enterprise.)

**Comment by ilyavolodin** [comment]
Could you provide configuration for this rule as well as console output of the error for the code above. Have you tried setting `spaced-line-comment: [2, never]`?

**Comment by gcochard** [comment]
I suppose there could be some value in allowing an exception to this rule to allow arbitrary text *after* a pattern.

Currently, it only allows the exception to be repeated to the end of the line. Maybe if it sees a space after an exception block, all is good? That way there could be an exception for `/` and then this use-case would work.

Adding another value to the `[always, never]` enum like `leading-exception` would keep this backwards-compatible.

**Comment by nzakas** [comment]
From what I can tell, there is no false positive here. It's a true positive because the third slash doesn't have a space before it. The third slash is part of the comment value, not a syntax hint.

I dont like the idea of an "anything goes" option, as that could bite people accidentally. This is still a line comment, so the question is if it makes sense to consider the third slash as part of the current marker, and if so, what that option looks like.

**Comment by cwrea** [comment]
Thank you all for your responses.

@ilyavolodin: Using `never` doesn't permit the behavior I'd like, which is to force a space after line comment markers. My eyes bleed when I see `//description` instead of `// description`. Yet, `always` complains about the triple-slash because it treats the first two slashes as introducing the comment, and the next as comment value, as @nzakas has pointed out, when really the three taken together introduce a special *kind* of comment, not as far as the language spec itself is concerned, but as far as third-party tooling is concerned.

@nzakas: Sorry for my poor choice of words. I meant "false positive" not in the strict sense that the rule isn't working exactly as designed (it certainly is) but rather that in this specific context of XML doc comments, the rule is warning of things I don't *want* to be considered violations, and addressing those violations would negate those comments' primary purpose.

You're right of course that from a pure JavaScript perspective, the third slash is technically part of the comment and not the marker introducing the comment. However, if you are suggesting an approach that optionally permits a third slash in the line comment marker, that certainly would meet the goal while not requiring a more elabore `exceptions` configuration or permitting of arbitrary text in the special case.

**Comment by nzakas** [comment]
I think we need to think about this more generically as, "what type of special comments are out there?" Off the top of my head:

```
/// XML comment

//@ conditional comment

 //# source map comment
```

Any others?

**Comment by cwrea** [comment]
@nzakas Good point. FWIW, I know that [Doxygen](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html), which originated for C++ ca. 1997, now also supports multiple languages. While it doesn't yet JavaScript, it is conceivable that Doxygen or something inspired by its comment format *could* be adapted for use in JavaScript. Anyway, with respect to single-line special comments, Doxygen has:

    /// doc comments
    //! ditto

... and it can get more complicated:

    ///< member doc comments
    //!< ditto

While I don't suggest these be added specifically as exceptions, I mention them as examples so that if an option were to be added to specify additional single-line comment markers, it would need to be mindful of more than just *one* extra character. Perhaps something like, e.g.:

    "spaced-line-comment": [ 1, "always", { "exceptions": [ "=", "-" ] },
        { "treatedAsMarkers": [ "///", "//@", "//#", "//!", "//!<" ] }
    }

? TTYL.

**Comment by nzakas** [comment]
I'd like to avoid overcomplicating the rule, so I'm looking for an option that doesn't require a lot of configuration.

**Comment by cwrea** [comment]
Acknowledged. I'll interpret your *"doesn't require a lot of configuration"* as meaning either no added configuration, or the least possible, i.e. a boolean. From there, I propose any of:

- No configuration required, tight: The rule could accept the *specific* special single-line comment markers discovered already as equivalent to a single-line comment marker. Adding other variants would require extension.

- No configuration required, loose: The rule could accept *any* special single-line comment marker, "special" defined as `//` followed immediately by *one or two* non-alphanumeric, printable ASCII characters (~32). Permits known variants plus likely potentials either not yet discovered or not yet invented. Increases the likelihood of unintended comment junk going undetected ... but the world won't end. More complex variants (3+ extra chars, or use of non-ASCII glyphs) would require extension.

- Four more distinct possibilities based on the above behaviors but involving an optional boolean to either enable/disable the behavior being off/on by default.

The loose behavior with a boolean required to *enable* wouldn't inflict change on existing rule users, and might perhaps be the most agenda-free, generalizable choice w.r.t. [the philosophy](http://eslint.org/docs/about/#philosophy), but I'm new here and accept I may be completely wrong on any of this :)

**Comment by nzakas** [comment]
Come to think of it, defining specific markers is probably the best way to go. I've been seeing some code that would not be happy with generic options. Maybe something like:

```
markers: ["/", "@", "!<"]
```

Thoughts?

**Comment by gcochard** [comment]
`markers` sounds like a decent option given what they are doing.

Config should look like this:

```json
"spaced-line-comment": [ 1, "always", {
        "exceptions": ["=", "-"],
        "treatedAsMarkers": ["///", "//@", "//#", "//!", "//!<"]
}]
```

**Comment by nzakas** [comment]
Not quite, see my comment for what I think it should look like. No point in making people specify `//` all the time.

**Comment by gcochard** [comment]
@nzakas Copypasta error :disappointed:. Corrected below.

```json
"spaced-line-comment": [ 1, "always", {
        "exceptions": ["=", "-"],
        "markers": ["/", "@", "#", "!", "!<"]
}]
```

**Comment by nzakas** [comment]
:+1:

**Comment by gcochard** [comment]
I'll take this and have it patched today :smile:

**Comment by gcochard** [comment]
@nzakas just need the `accepted` label before I start.

**Comment by nzakas** [comment]
Oops forgot. Thanks for the reminder.

**Comment by gcochard** [comment]
No prob.

**Comment by cwrea** [comment]
Works great! Thank you all.

**Comment by dancvogel** [comment]
I'm using:  
```
"spaced-comment": [2, "always", {"exceptions": ["-"], "markers": ["/"]}], 
```
But it still says both of these lines are errors:
```
///-----------------------------------------------------------------------------------------
///
```

**Comment by gcochard** [comment]
@dancvogel please open a new issue to report this.
