### ISSUE TITLE
Automatically validate rule options

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#2595]
Pulling this back into an issue from #2179.

Now that we have the validator from #2523 and schemas from #2580, we can enable automatic validation. How should eslint-tester verify the tests?

**Comment by nzakas** [comment]
What do you think eslint-tester's job is in this regard? What are we trying to accomplish?

**Comment by btmills** [comment]
Since we pulled validation out of `validate`, anything that accepts options is responsible for validating them. Because eslint-tester calls `validate` directly, eslint-tester will somehow need to call (either directly or indirectly) the `validateRuleOptions` method of `config-validator`. In #2179, adding a private API to eslint was discouraged, so I passed a reference to the validation function as part of the eslint-tester. Unfortunately the latter required modifying every single test file.

**Comment by ilyavolodin** [comment]
Would it be an option to separate out validator into it's own package? I'm not really sure it's a great idea, but that would simplify everything quite a bit.

**Comment by btmills** [comment]
The validate also needs to be able to pull in the rules to get the schemas, so that would still require us to either add an API or `require("eslint/lib/rules")`, which seems even more hackish.

**Comment by ilyavolodin** [comment]
You are correct. In that case, I don't see any other way then to expose verify on eslint object. I think that's better approach then injecting it into eslint-tester every time. I also don't think it's such a bad thing to expose it. It could be useful for plugins and maybe runners to verify custom rules.

**Comment by nzakas** [comment]
Why not export config validator from the ESLint package?

**Comment by ilyavolodin** [comment]
Ah, that's probably a cleaner way. Then eslint-tester can just import it, and it still should allow third-party tools to validate rules, if necessary.
