### ISSUE TITLE
func-names included as stylistic but can issues for code correctness

### ISSUE THREAD

**Issue by ORESoftware** [eslint/eslint#2598]
In the ESLint docs, in the rules section it mentions "func-names":

func-names - require function expressions to have a name (off by default)

as a stylistic concern.

However, eliminating anonymous functions in JS can be very useful for code correctness as far as debugging goes. So I think putting "func-names" in the stylistic concerns section is more than style problem :)

**Comment by ilyavolodin** [comment]
I agree. I think it might fit better under `Best Practices`.

**Comment by xjamundx** [comment]
Agreed as well.

**Comment by lo1tuma** [comment]
I'm not convinced. Can you explain why named functions are better for debugging? We had a similar discussion about this in #938 which recommends to NOT name all functions for better debugging.

**Comment by ilyavolodin** [comment]
@lo1tuma In both cases, named and unnamed, it's done for debugging convenience, no for styling. Naming functions allows stack traces to point you directly to the function that caused an issue. Based on discussion in #938 not naming function attacked to objects does the same. Hence - best practices.

**Comment by lo1tuma** [comment]
> In both cases, named and unnamed, it's done for debugging convenience, no for styling.

So what is the best practice then? `func-names` can only enforce one of those cases which contradicts with the other.

**Comment by ilyavolodin** [comment]
If you do name functions assigned to object properties, your stack trace is only going to contain function name, not object name. If you don't name any functions, your stack trace is going to be full of "Anonymous function" statements. Turning it on should be best practice, but maybe we should consider adding an option for object properties.

**Comment by nzakas** [comment]
The issue here is that there isn't general agreement as to whether the name helps debugging or not. I, for one, don't find it very useful and so consider it a stylistic choice for code readability.

**Comment by ORESoftware** [comment]
you know what would be pretty cool. if we could generate unique ids for function names that had a certain format. likes names starting with $$$. then the ide could/would hide them. but you could search for them in your IDE and they would appear in stack traces. that would be cool. so in your codebase, the functions would appear to be anonymous, because the IDE would hide them.

**Comment by ORESoftware** [comment]
that's actually a crap idea hahaha

**Comment by ORESoftware** [comment]
function $$$hidden(){}

the "$$$hidden" would show up in plain text everywhere

**Comment by nzakas** [comment]
@ORESoftware please keep your comments related to the issue.

**Comment by ORESoftware** [comment]
$$$

**Comment by nzakas** [comment]
Okay, to close this out - the categories are just logical groupings so we don't just have a giant list of rules. That's too say, I don't consider this distinction important enough to spend more time on.
