### ISSUE TITLE
Is there any way to disable all default rules by setting .eslintrc ? 

### ISSUE THREAD

**Issue by elrrrrrrr** [eslint/eslint#2609]
Is there any way to disable all default rules by setting .eslintrc .
```json
{
    "defualt": "off"
}
```
which like 
```shell
elinst --reset
```

**Comment by ilyavolodin** [comment]
We currently do not support this. However, starting with 1.0.0 release, reset will become default behavior (as in, you are not going to get any default rules).

**Comment by JikkuJose** [comment]
Is there any update for this? Is there a setting I can do to disable all rules?

**Comment by not-an-aardvark** [comment]
As of the 1.0.0 release, all rules are disabled by default.
