### ISSUE TITLE
no-redeclare is misperforming

### ISSUE THREAD

**Issue by ORESoftware** [eslint/eslint#2617]
var eventData = validator.validateEvent(event);
    var options = createOptionsData(getIngestURL(eventData), event);

this throws a no-redeclare problem for the var 'eventData'. However, eventData is not being redeclared - it is merely being passed to the getIngestURL function.

Is this a known ESLint issue?

**Comment by gyandeeps** [comment]
Can you share:
* version of eslint being used?
* What kind of parser?
* Screenshot of the actual output.

**Comment by ORESoftware** [comment]
$ eslint -v
v0.21.2

{
  //comments are OK in .eslintrc files
  //http://eslint.org/docs/user-guide/configuring

  "parser": "espree",  
  "ecmaFeatures": {
    "blockBindings": true,
    "forOf": true,
    "jsx": true,
    "classes":true
  },
  "rules": {
    "semi": [2, "always"],
    "quotes": [1, "single"],
    "curly": [2, "all"],
    "strict":2,
    "no-console":1,
    "no-new":1,
    "brace-style": [1, "Stroustrup", { "allowSingleLine": true }],
    "key-spacing": [0, {"beforeColon": false, "afterColon": false}],
    "comma-spacing": [0, {"before": false, "after": true}],
    "no-unused-vars": 1,
    "func-names":1, //no anonymous functions allowed
    "no-lonely-if":2,
    "no-cond-assign":2,
    "no-native-reassign":2,
    "no-dupe-keys":2,
    "no-duplicate-case":2,
    "no-empty":1,
    "no-func-assign":2,
    "new-cap":1,
    "no-trailing-spaces": [0, { "skipBlankLines": true }],
    "no-multiple-spaces":0,
    "valid-typeof":2,
    "block-scoped-var":2,
    "consistent-return":2,
    "default-case":2,
    "no-proto":1,
    "no-redeclare":2,
    "no-return-assign":2,
    "no-self-compare":2,
    "no-sequences":2,
    "no-throw-literal":2,
    "no-unused-expressions":2,
    "radix":2,
    "wrap-iife":2,
    "yoda": [2, "never", { "exceptRange": true }],
    "no-caller":2,
    "no-empty-label":2,
    "no-extend-native":2,
    "no-extra-bind":2,
    "no-fallthrough":2,
    "no-floating-decimal":2,
    "no-lone-blocks":2,
    "no-loop-func":2,
    "no-multi-str":1,
    "no-new-func":1,
    "no-new-wrappers":1,
    "no-catch-shadow":2,
    "no-delete-var":2,
    "no-use-before-define":0,
    "handle-callback-err": [2, "^.*(e|E)rr" ],
    "no-new-require":2,
    "no-path-concat":2,
    "no-restricted-modules": [2, "cluster"],
    "no-sync":2,
    "no-extra-semi":2
  },
  "env": {
    "es6":true,
    "browser": false,
    "node": true,
    "mocha": true,
    "amd":false
  },
  "globals": {
    "colors": true,
    "nconf": true
  }
}

**Comment by ilyavolodin** [comment]
I can't reproduce this in online demo, it might be somehow related to `es6` environment.

**Comment by gyandeeps** [comment]
I mean the actual error message out on the console.

FYI, i just ran the code on the online demo and it didn't complain.

**Comment by ORESoftware** [comment]
it seemed to work - I just misread what line it was complaining about. you can close for now.
