### ISSUE TITLE
Sub-option to allow console.warn and friends in no-console

### ISSUE THREAD

**Issue by hgl** [eslint/eslint#2621]
`console.warn` and `console.error` are pretty useful to help users report errors even in production code.

I wonder if it makes sense to add a sub-option to only report error on using `console.log`, which is mainly used for development debugging?

**Comment by ilyavolodin** [comment]
The rule was create to guard any output to console in production code, as it's considered a bad practice. There is no real difference between `console.warn` and `console.log` from my perspective. I think if you want to output to console, you should just disable this rule.

**Comment by gyandeeps** [comment]
Agree with @ilyavolodin .
If its an exception just once then you can actually disable the rule for that particular line

```js
console.error("hi") // eslint-disable-line no-console
```

**Comment by hgl** [comment]
The problem is that my project uses `console.warn` and `console.error` in production code, but I do want to check for `console.log` in case I forget to remove them after debugging.

Having to to use comment *every time* I use `console.warn` and `console.error` doesn't sound very optimal.

It's pretty common for a browser extension to dump indexDB error to the console to help users report bugs for example.

**Comment by xjamundx** [comment]
My thought would be to create a custom rule for your project to do this. I don't think it would be something that we'd want to have globally, but it would be really easy to add this exception for your project. Do you want some help setting it up?

**Comment by hgl** [comment]
> Do you want some help setting it up?

That would be great. Thanks. Does the doc cover it?

**Comment by xjamundx** [comment]
Take a look at the [existing no-console rule](https://github.com/eslint/eslint/blob/master/lib/rules/no-console.js#L18).

You can add the following in order to make it only warn on `console.log` statements you need to update the `if` statement on line 18 to look like this:
```js
if (node.object.name === "console" && node.property.name === "log") {
```

1. Save that modified file into a `rules/` directory inside your project as `no-console-log.js`.
2. Open up your `.eslintrc` file and then add `no-console-log: 2` to the `rules` section to enable the rule.
3. When you run eslint make sure to use the `--rulesdir` flag to specify that it should look in the `rules/` directory

More info here:
http://eslint.org/docs/user-guide/command-line-interface#--rulesdir

More advanced docs:
https://gist.github.com/jareware/7179093

Good luck!

**Comment by ilyavolodin** [comment]
We have a whole section in the documentation dedicated to rule creation here: http://eslint.org/docs/developer-guide/working-with-rules
Let us know if you run into some problems.

**Comment by xjamundx** [comment]
@hgl feel free to join the chat room at https://gitter.im/eslint/eslint if you get stuck

**Comment by hgl** [comment]
Thanks guys. And thank you @xjamundx for taking the time writing the step by step instructions.

I will try it out.

**Comment by Globegitter** [comment]
I agree with @hgl that there should be options that you can `allow` warn and/or `err`. We allow `console.warn` in our production code and also other third-party libraries such as ReactJS or pixi.js do that. So I do think there is enough of a real-world use-case to reconsider.

But of course I also do respect the choice of the main contributors if that is set in stone.

**Comment by joeybaker** [comment]
For what it's worth, I published a plugin that just checks for `console.log`, using @xjamundx's advice above. https://github.com/joeybaker/eslint-plugin-no-console-log

**Comment by IanVS** [comment]
:+1: Thanks for reporting back!

**Comment by Diokuz** [comment]
+1 for no-console-log

**Comment by allenmanning** [comment]
+1 for configuring which ones fail

**Comment by freddyrangel** [comment]
Custom rule creation is great! But it does seem awfully opinionated to say that using `console.log` is so bad that it's should not be a configuration option. I love the flexility of ESLint: this seems like it should be another option.
