### ISSUE TITLE
Add configuration to no-unreachable

### ISSUE THREAD

**Issue by tomprogers** [eslint/eslint#2637]
Some people subscribe to the notion that you should always `break` in your `case` statements, even if the `case` `return`s. Like so:

```javascript
switch(x) {
    case 'one':
        return 1;
        break; // this line is unreachable, but some insist on it
    
    default:
        return undefined;
        break; // sometimes people even insist on breaking in the final case
}
```

It the code you get when you take the `no-fallthrough` rule to the furthest extreme.

It would make life easier if we could configure the `no-unreachable` rule to accept this kind of thing. Perhaps there is a broader, generalized form of this, like being able to permit unreachable exits. I'm not aware of other practices like this, though.

**Comment by lo1tuma** [comment]
Is there any reason why you don't disable this rule?

**Comment by tomprogers** [comment]
We still want to alert devs to things like this:

```javascript
function expensiveMethod(input) {
    var start = performance.now();
    // ... interesting algorithm
    var end = performance.now();
    return output;
    var end = performance.now(); // sometimes this happens, which is funny
    // usually it's just this: metrics or whatever after *all* the "work"
    console.log('expensiveMethod: ' + parseInt(end - start) + ' ms');
}
```

And just to be clear: "devs" in this case is me. ;)

**Comment by nzakas** [comment]
I'd suggest disabling the rule manually in that case:

```
break;  // eslint-disable no-unreachable
```

I'm sorry, but I can't rationalize adding an exception that allows unreachable code to this rule. :)

**Comment by ripter** [comment]
I just ran into this problem as well. The suggested work around does not work. I'm still getting the error even after I added the comment.

    break; // eslint-disable no-unreachable

**Comment by nzakas** [comment]
Try this instead:

```js
        /* eslint-disable no-unreachable */
        break;
        /* eslint-enable */
```

**Comment by ripter** [comment]
That worked. Thanks.
