### ISSUE TITLE
Yoda: optionally only apply to equality operator

### ISSUE THREAD

**Issue by denis-sokolov** [eslint/eslint#2638]
The premise of the Yoda rule is to prevent accidental assignment instead of comparison due to similarity of `=`, `==`, and `===`. This premise is confirmed in the [issue that initiated the yoda rule in eslint](https://github.com/eslint/eslint/issues/504), [in Wikipedia](http://en.wikipedia.org/wiki/Yoda_conditions), [on Stackoverflow](http://web.archive.org/web/20100715190839/http://stackoverflow.com/questions/2349378/new-programming-jargon-you-coined#answer-2430307) and in [older sources](http://thomas.tuerke.net/on/design/?with=1146181680#msg1146181680). That purpose is fully unrelated to any operators other than the equality operator. I hereby propose making `yoda` rule only apply to equality operator.

The rule as it stands, has caused [questionable exceptions](https://github.com/eslint/eslint/issues/1561) already. Here's another possible one: whether somebody wants yoda always or never is unrelated to the preference towards ordering comparison operators. Somebody might like to always use the smaller-than operator to place the values in the order they lie on the imaginary number axis. Somebody might like to use `yoda: always` to prevent the assignment bug, but dislike the weird look of `2 > a`.

In addition, while the equality operator is commutative, and fixing the warning requires to trivially switch the operands, comparison operators are not commutative, and one also needs to replace the operator. This additional step can be missed resulting in another bug.

Overall, I think it's beneficial for eslint to strive to minimize false positives whenever possible and keep the scope of the rules to a minimum. `yoda` rule is about the equality operator and it should only apply to the equality operator.

I will welcome your input.

**Comment by nzakas** [comment]
The yoda rule is not just about equality, though your interpretation is that it should be. We never intended it to be just about equality, so we aren't going to make such a chance.

The best I can offer is an option that lets you restrict the Yoda rule to equality if you so choose.

Keep in mind, we have a ton of users, so we try not to change existing rules unless there are obvious bugs or missing options, and we rarely will change the default behavior of rules. The good news is that we have plugins, so you can always write your own rules even if we don't accept your changes.

**Comment by denis-sokolov** [comment]
If you don't mind, what is the value behind extending the yoda rule for non-equality? Enforcing `2 == a` avoids the `a = 2` bug. What does enforcing `2 > a` achieve? Is there anyone else on the internet that uses the yoda rule for non-equality?

This change would be backwards-compatible, as it would not introduce new warnings, but decrease the number of previously existing warnings. I thought that this is exactly the time to fix rules up before the release of 1.0.0, when all rules will be off by default, no?

But yes, if that's out of the question, the option would be really necessary.
You [worry about the expanded scope](https://github.com/eslint/eslint/issues/2555#issuecomment-107100914) of the rules, that's good. Well, in case of the yoda rule, in my personal case, it is definitely overreaching. I want to forbid `2 == a` in my code, but allow `2 < a`. In my personal opinion, those are two absolutely unrelated pieces of code. Yet currently the yoda rule piles them together.

Please let me know, whether changing the rule is still considered, and if not, whether I can implement an option for it.

**Comment by michaelficarra** [comment]
I agree with @denis-sokolov here. I would only want the yoda rule to work on equality comparisons, and I think that is a better default.

**Comment by nzakas** [comment]
@denis-sokolov I've already said I'd accept an option and why I don't like changing rule defaults. That's all in going to say on the topic. 

You have to realize, for every person who shares your opinion, there's another who wants it the way it is and would be upset with a change in default behavior. That's the burden of having a popular tool, we have to balance everyone's needs and expectations.

So, propose an option name and let's go from there.

**Comment by denis-sokolov** [comment]
Perhaps `onlyEquality` as the option name? With the option enabled the yoda rule would only care about `==` and `===`, but would not care about `!=`, `!==`, `<`, `>`, `<=`, and `>=`.


The following is a continuation of a discussion. Feel free to ignore it if you can't afford further debate.

Of course, every change [breaks someone's workflow](http://xkcd.com/1172/). I am trying to make eslint's default rule more consistent with expectations of masses of new developers that expect it to only apply to equality, as proved by my links before. I can't imagine hoards of upset developers claiming "oh no, this tool now reports one fewer warning for my code, this is an outrage!" Especially given that it's easy to provide a reverse option and that the tool is pre-1.0.0 on purpose, where the 1.0.0 change will be massively backwards incompatible and require defining all rules from scratch.

**Comment by nzakas** [comment]
The option sounds okay. If you'd like to submit a PR, we will happily except.

I'm not interested in debate - the option is as far as this will go.
