### ISSUE TITLE
Auto publishing release notes throws an error

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2640]
```
Publishing changes to github release

c:\git\github\eslint\node_modules\gh-got\node_modules\got\index.js:82
                throw new GotError('options.body must be a ReadableStream, string or Buffer'
                      ^
GotError: options.body must be a ReadableStream, string or Buffer
    at got (c:\git\github\eslint\node_modules\gh-got\node_modules\got\index.js:82:9)
    at ghGot (c:\git\github\eslint\node_modules\gh-got\index.js:37:9)
    at release (c:\git\github\eslint\Makefile.js:138:5)
    at Function.target.minor (c:\git\github\eslint\Makefile.js:755:5)
    at Object.global.target.(anonymous function) [as minor] (c:\git\github\eslint\node_modules\shelljs\make.js:28:26)
    at c:\git\github\eslint\node_modules\shelljs\make.js:38:27
    at Array.forEach (native)
    at null._onTimeout (c:\git\github\eslint\node_modules\shelljs\make.js:36:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by gcochard** [comment]
Ack, I didn't realize `got` and by extension `gh-got` didn't automatically stringify the `POST` body. I will have this fixed in a few minutes.

**Comment by ilyavolodin** [comment]
Sill issues with autopublish. Now it hangs right after generating changelog.

**Comment by ilyavolodin** [comment]
Hmm... might've been something else. I couldn't do release even after I commented out all of the code.

**Comment by gcochard** [comment]
Hmm, same symptoms after commenting out the changelog code?

**Comment by gcochard** [comment]
@ilyavolodin have you had a chance to test this out since June 14?

**Comment by ilyavolodin** [comment]
Sorry, I haven't had a chance to verify it:-( Last time I removed it, the issue wasn't caused by auto publish, I think I never figured out what was the issue though, since I removed the repository and recloned it again, which cleared the error. So it might be safe to put back in.

**Comment by BYK** [comment]
Is this still relevant? I see this portion of the code commented out in `Makefile.js`

**Comment by BYK** [comment]
Ping :)

**Comment by ilyavolodin** [comment]
I think we should put the code back in, and try it again. I don't have time to test this out (sorry, I know it's been a long time, and it wouldn't take too long to test, but just can't find time:-( )

**Comment by nzakas** [comment]
I'll try to take a look next week.

**Comment by gyandeeps** [comment]
Is this still an issue? Since I dont see any code in makefile for this do we still want to pursue this?

**Comment by ilyavolodin** [comment]
@nzakas Pushed a new PR just a few days ago that removed this code. I think ideally we would want this in, but we have no real way to verify that the code works (other then during releases).

**Comment by nzakas** [comment]
Yeah. I'm planning on looking at this again, it shouldn't be too hard. Just didn't want that extra code hanging around confusing things.

**Comment by btmills** [comment]
I think this can be closed here now that eslint uses eslint-release. Does it need to be migrated to the eslint/eslint-release issue tracker?

**Comment by ilyavolodin** [comment]
Agree. Up to @nzakas if he want's a new issue in `eslint-release` for this. I think it would be nice to automate this step.
