### ISSUE TITLE
Deprecate `no-wrap-func`

### ISSUE THREAD

**Issue by jrvidal** [eslint/eslint#2644]
We should deprecate `no-wrap-func` after #2578, and disable it by default. We could activate instead `no-extra-parens` as `[2, "functions"]` to substitute it.

**Comment by nzakas** [comment]
We don't change which rules are enabled by default because it messes up people's configs. We should track removing it in #1898.

In the meantime, we should add notes to the docs saying the rule is deprecated.

**Comment by btmills** [comment]
`no-wrap-func` has been added to the deprecated rules list in #1898.
