### ISSUE TITLE
Rule names across different ESLint versions

### ISSUE THREAD

**Issue by jcbp** [eslint/eslint#2661]
We are running ESLint from both a grunt task and a Brackets Editor plugin for the same project. There are other contributors to the same project who also run ESLint from Webstorm. We mantain a single .eslintrc file for all cases.
Since the ESLint version that plugins and grunt use may differ from each other, we faced in several situations ESLint failing due to different rule names for each ESLint version. Even if the whole team uses the same ESLint version, we must be careful to keep the rule names updated to that version.
Have you considered backward compatibility for rule names?
Do you know of any workaround for mitigating these issues?
Thanks in advance.

**Comment by hzoo** [comment]
Rules that are changed should already have a notice that they are being deprecated and it doesn't happen that often? You can include ESLint as a root dependency so that grunt and others will use that version. Also, a lot of plugins use a global ESLint anyway which can be updated.

**Comment by ilyavolodin** [comment]
@jcbp We are planning on retiring all of the deprecated rules before 1.0.0 and after the first major release, we will be very cautious about removing existing rules. You can also setup editor integrations to use the same version as command line tool. At the very least you can definitely do that for WebStorm.

**Comment by jcbp** [comment]
Thanks for replying.
We were using a very old version in the Grunt integration and this is why we had a lot of conflicts. Now we have all the plugins and command line working with the same version and these works fine.
I look forward to the first major release.
Thanks again.
