### ISSUE TITLE
eslintrc getting skipped when $HOME is $PWD

### ISSUE THREAD

**Issue by zertosh** [eslint/eslint#2662]
I'm having issues with our CI building our apps in the `$HOME` dir. If I have:

```
your-project
├── .eslintrc
├── lib
│ └── source.js
└─┬ tests
  ├── .eslintrc
  └── test.js
```

And `your-project` also happens to be `$HOME`. When linting `tests/test.js`, eslint will [skip](https://github.com/eslint/eslint/blob/665f87d01943e45f3aa9639ea3e921f7cd402b00/lib/config.js#L203-L206) `your-project/.eslintrc` (since it found `your-project/tests/.eslintrc`).

It makes sense to skip `$HOME/.eslintrc` if another `.eslintrc` was found. However, I wonder if it also makes sense to add an exception so as not to skip it if `$HOME` `===` `$PWD`.

**Comment by ilyavolodin** [comment]
Hmm.. that's strange, as far as I remember the code, it should find `.eslintrc` in the same directory first, and if it did, then it's just not going to look for the file in `$HOME`, but it shouldn't remove the one it found already.

**Comment by zertosh** [comment]
If you're testing `your-project/tests/test.js`, it finds `your-project/tests/.eslintrc` just fine, but it skips `your-project/.eslintrc` if `your-project` is also `$HOME`.

**Comment by nzakas** [comment]
I'm not sure if adding this exception is a good idea - an exception to an exception is always a bit dicey. 

Do you have just one .eslintrc file in your project? If so, you might just want to pass it with `-c` on the command line

**Comment by zertosh** [comment]
At any given depth there are usually two `.eslintrc`: the root one, and another one that has a few browser or node specifics. So `-c` doesn't work for us.

This change would certainly make my life easier, but I understand the rabbit hole that is exceptions-to-exceptions. I'm not sure if there are any good workarounds (besides changing `$HOME` before running eslint), but if the matter is final, feel free to close this issue.

**Comment by nzakas** [comment]
Not final, trying to weigh making a not-terribly-obvious change against other possibilities.

Is it possible for you to check out to a non-`$HOME` directory?

**Comment by zertosh** [comment]
That's not a feasible change in our build infra. I'm not sure what jenkins or travis sets for `$HOME`, but I imagine that setting the checkout directory as `$HOME` for the purposes of building is not impossibly rare in other automated setups.

We run eslint from a script for local dev'ing and as part of the pre-deploy build verification. The workaround we're using kinda-looks like this:

```js
var spawn = require('child_process').spawn;
var env = assign({}, process.env);
// eslint will ignore the `.eslintrc` in the HOME directory
// if it finds any other `.eslintrc`. when the CWD is the HOME
// directory we move one level up so that it actually reads the config.
if (env.HOME === process.cwd()) {
  env.HOME = path.join(env.HOME, '..');
}
console.log('Linting ' + files.length + ' files...');
var args = ['--rulesdir', ESLINT_RULES, '--quiet'].concat(files);
var opts = {stdio: 'inherit', env: env};
spawn(ESLINT_PATH, args, opts)
  .on('close', process.exit);
```

**Comment by ilyavolodin** [comment]
One suggestion that I have, is to use `extend` in your test directory config pointing to a higher level config. If you run it locally, nothing will happen, (or rather the same file will be applied twice, with no result differences), but on your build machine, this would implicitly specify that the file in the upper directory should also be used.
Just add the following:
```json
{
    "extends": "../.eslintrc"
}
```

**Comment by zertosh** [comment]
@ilyavolodin Ugh of course! It worked! Thank you!
