### ISSUE TITLE
no-irregular-whitespace should not be checked in template literals

### ISSUE THREAD

**Issue by Nyalab** [eslint/eslint#2665]
This rule works well for string surrounded by quotes but not for template literals

**Comment by ilyavolodin** [comment]
Can you provide sample code, version of eslint your are using and which parser do you use?

**Comment by gyandeeps** [comment]
is this still a problem @Nyalab ? if yes, please provide us with sample code, version of eslint your are using, which parser do you use and console output please.
Otherwise lets close this issue.

**Comment by gyandeeps** [comment]
Closing because of no communication.
Feel free to reopen.

**Comment by Nyalab** [comment]
ok sorry, i was into paternity holiday, i cannot reproduce this error right now, i guess it should have been fixed previously
