### ISSUE TITLE
`no-process-exit` should be ignored in CLI's

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#2666]
I want to use this option, but in CLI's it *does* make sense to use `process.exit()`.

Would be nice if ESLint could detect the hashbang `#!/usr/bin/env node` and disable the rule there or add some kind of mode for doing that (preferable the first).

Example: https://github.com/sindresorhus/trash/blob/e75f1489f626a729eaec00a2088cd5df76a91420/cli.js#L32

**Comment by ilyavolodin** [comment]
Hmm.. That might be tough. If I'm not mistaken, we remove hashbang from the file before running validate on it. I don't remember this for sure, but I think @michaelficarra made that change a while back.

**Comment by michaelficarra** [comment]
I like this proposal. Also, I don't see why we couldn't change the rule configuration for files that have the shebang stripped.

**Comment by nzakas** [comment]
I think I'm missing something here, why don't you just disable the rule in that file?

I don't foresee treating she-banged files differently, as I don't like implicit switches for things.

**Comment by sindresorhus** [comment]
This is not about it not being possible to work around with an inline comment, it's more about making the check smarter and more developer friendly. I don't want to have a disable comment in all my CLI's, so without this I'm just going to disable the rule.

**Comment by nzakas** [comment]
As I mentioned, I'm not comfortable with automatically changing which rules are enabled based on the presence of shebangs. In 1.0.0, even environments won't automatically enable/disable rules. So, I'm afraid you will be left to manually disable this rule where you need it.

**Comment by sindresorhus** [comment]
In case anyone else wants this, we made a custom rule: https://github.com/sindresorhus/eslint-plugin-xo/blob/master/docs/rules/no-process-exit.md

**Comment by jokeyrhyme** [comment]
FYI...

Upstream Node.js now recommends that we set [`process.exitCode`](https://nodejs.org/api/process.html#process_process_exitcode) and allow the process to terminate gracefully, instead of using [`process.exit()`](https://nodejs.org/api/process.html#process_process_exit_code)
