### ISSUE TITLE
`lines-around-comment` exception for first line in a block

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#2667]
## Config

```json
{
  "lines-around-comment": [2, {"beforeLineComment": true}]
}
````

## Result

```js
function fn() {
	// results in an error
	var foo = true;
}
```

## Wanted

I want to be able to have a comment on the first line in a block without it being an error.

```js
function fn() {
	// does not result in an error
	var foo = true;
}
```

-

Same goes for `beforeBlockComment`.

**Comment by mathieumg** [comment]
I didn't install 0.22.x yet, but when reading the changelog I thought about this case. Especially with `padded-blocks` set to `never`, in which case you're damned if you do, damned if you don't. I'd welcome a way to have block-starting comments be valid. :+1:

**Comment by xjamundx** [comment]
I also want a way to require a newline after a file-level block-level comment.

```js
/**
 * This file describes helpers that do whatever...
 */

'use strict';
```

But without requiring newlines below other block-level comments.

**Comment by xjamundx** [comment]
@sindresorhus Can you suggest what that exception might look like in the configuration?

**Comment by sindresorhus** [comment]
Not sure, maybe something like:

```json
{
  "lines-around-comment": [2, {"beforeLineComment": true, "firstInBlock": false}]
}
```

**Comment by mathieumg** [comment]
For the first case:

```js
{
  "lines-around-comment": [2, {"beforeLineComment": true, "allowBlockStart": true}]
}
```

For the second case:

```js
{
  "lines-around-comment": [2, {"afterLineComment": true, "allowFileStart": true}]
}
```

Not sure they're the best names though.

**Comment by nzakas** [comment]
Let's keep this focused on one enhancement - @xjamundx can you for a separate issue for your request?

**Comment by ilyavolodin** [comment]
Just to clarify @sindresorhus do you want first in block, or first in function? In ES6 block includes a lot of different things, like loops, function and just randomly sprinkled braces. Should this option cover all of those?

**Comment by sindresorhus** [comment]
Yes, blocks.

**Comment by ilyavolodin** [comment]
Ok, then I think `allowBlockStart` is a pretty good name for an option to do this.

**Comment by gyandeeps** [comment]
**Need feedback:** what should happen under this scenario

```js
// "lines-around-comment": [2, {
//     "beforeLineComment": true,
//     "afterLineComment": true,
//     "allowBlockStart": true
// }]
while (true) {
    // This should be followed by a blank line
}
```

**Comment by mathieumg** [comment]
I think it should not error then. A common use case will be:

```js
try { 
  // ...
} catch(e) {
  // Empty.
} 
```

**Comment by nzakas** [comment]
I think we would need an `allowBlockEnd` for that case. Explicit > implicit

**Comment by gyandeeps** [comment]
@nzakas Should that be a different issue or this one only?

**Comment by nzakas** [comment]
I think it's small enough to have in this one.

**Comment by mathieumg** [comment]
@nzakas Would it still work with `allowBlockEnd` set to `true` even when `afterLineComment` is set to `false`?

I want to allow:

```js
{
  // Comment at the beginning of a block, so no line necessary before.
  console.log("Dummy code.");

  // Some comment that must be preceded by a line but not followed by one.
}
```

```js
{
  // Comment-only block.
}
```

But disallow:

```js
{
  
  // Block starts with an empty line, not good.
  console.log("Dummy code.");

  // Block ends with an empty line, not good.

}
```

Just to be clear, my config would be:

```js
"padded-blocks": [2, "never"],
"lines-around-comment": [2, {
  "beforeLineComment": true,
  "afterLineComment": false,
  "allowBlockStart": true,
  "allowBlockEnd": true,
}],
```

**Comment by gyandeeps** [comment]
@mathieumg remember this rule only provides checks for option which are set to `true`. Igf you have something set to `false` the we just don't check for that option.

> When set to false the option is simply ignored.

**Comment by mathieumg** [comment]
@gyandeeps All the same, I don't have configs with rules set to `false`, I just wanted to be super explicit with regards to the fact that this option wasn't enabled. I updated my previous post to remove explicit `false` options, my question still stands.

**Comment by gyandeeps** [comment]
For your disallow example, its the job of `padded-block` to tell whether you need empty lines for not. It has nothing to do with this rule I think.

**Comment by btmills** [comment]
Combining `padded-blocks` and `lines-around-comment` as shown should (if I'm not missing anything) achieve the desired results, right?

**Comment by gyandeeps** [comment]
I think so.

**Comment by mathieumg** [comment]
I just wanted to validate all that and avoid any clash. Specifically, that the comment-only block scenario is possible without `afterLineComment` having to be enabled.

**Comment by gyandeeps** [comment]
@mathieumg I have the PR ready. You can scan through the test cases and make some recommendation there. That would help me to look for bugs.
Thanks
