### ISSUE TITLE
Allow use of `eslint` in package.json

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#2670]
Currently you can specify `"eslintConfig": {}` in package.json with ESLint config.

It would look a lot nicer it was named `"eslint": {}`. ESLint could just try reading both.

I know this is minor, but anything to make package.json less verbose and nicer looking.

**Comment by gyandeeps** [comment]
I like the proposal.

**Comment by nzakas** [comment]
:-1: I don't like having two ways of doing things, especially when the only reason for the change is to save typing 6 characters one time. We already match `jshintConfig` and `jscsConfig`, it seems that the convention has pretty much been set.

**Comment by gyandeeps** [comment]
If its matches the styles used by other modules then I think it makes sense.

**Comment by sindresorhus** [comment]
I don't like having two ways of doing things either, but you could always just document the `eslint` case, and have the old one as legacy. I know this is a long shot, but I'm looking for ways to make "annoying config I have to put into every package.json" look nicer and less verbose. I see no good reason the `Config` is there other than "the other project did it" fallacy.

**Comment by nzakas** [comment]
I'm sorry, I don't find this line of reasoning to be convincing. "Look nicer" is far too subjective a reason to introduce redundancy. We will never be able to remove `eslintConfig`, as it's in use in too many places, so we would forever be stuck with two ways of doing the same thing.
