### ISSUE TITLE
key-spacing sees separate alignment groups despite no blank lines

### ISSUE THREAD

**Issue by heldinz** [eslint/eslint#2674]
I'm using the latest version of eslint (currently v0.22.1). The ability to signify different groupings for the key-spacing rule via newlines is great. However, it is biting me when long values within my object definition wrap, or when I have a value that is also an object.

As I have key-spacing configured to align on value, in these cases, I expect my definition to align the outer values with each other, and the inner values with each other, like this:

```javascript
{
    title:       'My title',
    description: 'My description',
    options:     {
        optionOne:   'First option',
        optionTwo:   'Second option',
        optionThree: 'Third option'
    },
    isDefault:   true
}
```

This is exactly how my IDE formats such an object. However, key-spacing then complains that there is extra space before the value for 'isDefault'. It is treating the 'isDefault' property as part of a group separate from the rest. I see the same behaviour when I wrap and then indent a long value.

I expect a new group to start only when there is a *blank* line between the properties, not just a new line. Is this reasonable?

**Comment by gyandeeps** [comment]
Can you please share the eslint output and the exact code you run on?

**Comment by heldinz** [comment]
Ok. I'm working on a React project right now and I'm getting this issue in my `propTypes` definitions, e.g.

```javascript
'use strict';

var React          = require('react'),
    ReactPropTypes = React.PropTypes;

var ESLintTest = React.createClass({

    propTypes: {
        headline: ReactPropTypes.string.isRequired,
        details:  ReactPropTypes.string.isRequired,
        url:      ReactPropTypes.string.isRequired,

        moreInfo: ReactPropTypes.string,
        path:     ReactPropTypes.arrayOf(ReactPropTypes.shape({
            title: ReactPropTypes.string,
            url:   ReactPropTypes.string
        })),
        target:   ReactPropTypes.string
    },

    render: function () {

    }

});

module.exports = ESLintTest;
```

My `key-spacing` rule is defined as:
```javascript
"key-spacing": [ 1, { "align": "value" } ]
```

And the output I get is:
```
18:18  warning  Extra space before value for key "target"  key-spacing
```

**Comment by btmills** [comment]
As of #2447, properties are only considered part of the same group if they start on consecutive lines. The reasoning behind the request was that properties with "stuff" filling lines between them are already broken up visually, and it's the visual groups we wanted to align.

**Comment by heldinz** [comment]
Thanks for clarifying the expected behaviour, @btmills. Shame it conflicts with IntelliJ's handling, which I personally prefer, but I can understand the reasoning.

**Comment by btmills** [comment]
Should there be an option that would match IntelliJ's behavior? `one-group: true` perhaps? @eslint/eslint-committers

**Comment by heldinz** [comment]
That would certainly work for me. Or perhaps some sort of "strictness" option regarding grouping? Something like `"allow-newlines-in-group": true` ?

**Comment by btmills** [comment]
Looks like this and #2668 have ended up pointing the same direction, so let's merge this into that one. I tried to summarize this thread there, but feel free to jump in if I left something out.

Closing in favor of #2668.
