### ISSUE TITLE
Default option for lines-around-comment rule is misconfigured in code

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#2677]
Docs say "By default an empty line is required above a block comment" that means option `beforeBlockComment` is `true`. But based on the code its not true. https://github.com/eslint/eslint/blob/master/lib/rules/lines-around-comment.js#L58-L62

**Comment by nzakas** [comment]
Question is: is the documentation wrong? Or is the rule wrong?

**Comment by gyandeeps** [comment]
@xjamundx Any idea what part is wrong code or docs?

**Comment by xjamundx** [comment]
I *think* the code is wrong.
