### ISSUE TITLE
Update globals and possible new environments

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#2682]
This is the issue for https://github.com/eslint/eslint/pull/2675 which updates the `globals` package and possibly would add two new environments. Dependency diff: https://github.com/sindresorhus/globals/compare/v6.1.0...7.1.0

Do we want to add `mongo` (https://github.com/sindresorhus/globals/pull/27) and `applescript` (https://github.com/sindresorhus/globals/pull/29) environments, or should I leave these out of the PR?

**Comment by ilyavolodin** [comment]
@nzakas Are you OK with adding those two environments? In my mind they are fine to add. I'm not really sure how much value you can have by linting mongo scripts, but applescript seems reasonable.

**Comment by nzakas** [comment]
If you're OK with it, then I'm OK with it.

**Comment by silverwind** [comment]
Personally, I have no need for them. I'm only interested in the variables update. So I'd be fine not adding them at this point.
