### ISSUE TITLE
Allow a custom parser object (rather than module)

### ISSUE THREAD

**Issue by gfxmonk** [eslint/eslint#2694]
When using a custom parser, it can be convenient to pass in an object with a .parse() method rather than a module name. Splitting a custom parser out into a module that `eslint` can require is an unnecessary step, and passing it directly allows custom parsers to be used in a context where `require()` isn't available (i.e. a browser).

I'm working on this.

**Comment by nzakas** [comment]
Let's talk about this some more. What is the use case you are trying to support?

**Comment by gfxmonk** [comment]
So my use case is that I'm writing an eslint-compatible parser for StratifiedJS. It's built into the StratifiedJS distribution (which already has compiler backends for JS, minified JS, dependency bundling, etc). So it isn't convenient or useful to distribute it separately on NPM, as a separate module.

With this change I could just provide an inline object (from my wrapper which calls into `eslint`), but currently I need to split the compiler out to a separate module, find its full path on disk, then pass that to `eslint`. It's [not difficult](https://github.com/onilabs/stratifiedjs/blob/f356028aa34f4997916123c7b7f281b01e57a690/modules/compile/lint.sjs#L149), but it does seem a little roundabout, doesn't it?

Other benefits (not directly related to my use case, but which seem neat):

 - It's just a more straightforward API: "here is my parser", vs "here is a well-known name by which you can find my parser". This also means you can pass a dynamically-constructed parser - e.g. if you have a parser with configurable settings, you could pass `parser: createParser(settings)`.

 - Going via `require()` can be occasionally pathological. Because while _my module_ might be able to `require('foo')`, there's no guarantee that _eslint_ can also require a module of the same name. Particularly when `npm link` is involved (I've had a lot of issues with `karma` plugins for similar reasons).

 - You can now use custom compilers in the browser. I don't personally need this, but it seems like a good thing.

**Comment by gfxmonk** [comment]
(also, it makes writing tests for #2698 much easier ;))

**Comment by nzakas** [comment]
Given that you have already solved this with one line of code, why do you feel a change should be made?

With regards to your solution: passing a parser object on config is a nonstarter. Configs must be completely serializable. 

I'd really much rather focus on a way to not modify the parser and instead pass the parser output, such as #1025

**Comment by gfxmonk** [comment]
I mostly just thought it was a good idea, particularly as it sidesteps the whole `require()` infrastructure which is not always present (i.e. in a browser).

It's not really about how much effort the workaround is - imagine if the current state was reversed, so that you _had_ to pass in an object and couldn't pass in a module name. The workaround if you wanted to use a string would then be entirely trivial (just wrap your string in `require()`). Sometimes module names are the most convenient way to reference something, but in other cases passing an object directly can avoid unnecessary complexity for the user.

Anyway, it just seemed like a good idea to me. But if you're not sold, that's OK - if you'd rather close this issue I'll just rewrite my tests for #2698.

**Comment by gfxmonk** [comment]
Ahh, I missed your point that "configs must be completely serializable". That's a good point.

**Comment by nzakas** [comment]
FWIW, we don't formally support ESLint in the browser, we only have a demo to let people try it before installing.

I'm not sold on the need for this, especially if we can get #1025 done, so closing.
