### ISSUE TITLE
space-unary-ops rule hardcodes a list of unary expression keywords

### ISSUE THREAD

**Issue by gfxmonk** [eslint/eslint#2696]
I believe this is unnecessary, and it causes errors with custom parsers which allow additional keywords (e.g. StratifiedJS).

I'm working on this.

**Comment by gyandeeps** [comment]
Can please share an example of what is the problem and why we need to solve it (if its a problem)?

**Comment by gfxmonk** [comment]
For example, the StratifiedJS parser supports a superset of JS which includes a `spawn` keyword, e.g.:

    spawn someLongRunningFunction();

This rule explicitly whitelists unary keywords which may be followed by whitespace. Since it doesn't include the StratifiedJS `spawn` keyword, it erroneously reports:

    Unexpected space after unary operator "spawn"

Obviously, the code wouldn't compile if I tried to write:

    spawnsomeLongRunningFunction();

So this rule needs to allow a space after the `spawn` keyword when parsing StratifiedJS. I could add the `spawn` operator to this whitelist, but it's StratifiedJS specific, and I think it makes more sense (and is easier) to distinguish "words" from "symbols" by simply checking whether they're alphabetic or not, rather than using a list of known words.

**Comment by ilyavolodin** [comment]
I'm not sure I'm sold on this. With this change, `blah` now all of a sudden becomes valid unary operator. I do understand why you want to have this change, I'm just not sure it's the right thing to do... Another possible path would be to have a list of allowed unary operators and add an extra option to the rule, that would allow you to supply your own list to be merged with defaults. I can see how this could be also useful for people using `babel-eslint` and `async`, `await` operators.
I think I need @nzakas input on this issue.

**Comment by gfxmonk** [comment]
> `blah` now all of a sudden becomes valid unary operator

Only if it's generated by the parser. This rule's job is not to recognise JS keywords, it is only to make sure you don't place spaces between unary ops that are made of punctuation. The current code assumes anything other than `["delete", "new", "typeof", "void"]` is punctuation.

In other words, if the parser parses `blah 1` as a valid expression, then yes - `blah` really _is_ a valid unary operator.

**Comment by gfxmonk** [comment]
On further inspection, I notice that it's unnecessary to have the `isWordExpression` check at all, since unary _words_ can be distinguished from unary punctuation by simply checking whether their type is `Keyword`. Please let me know if you can think of are any possible cases where this check could ever be incorrect, I can't come up with any.

**Comment by michaelficarra** [comment]
I'm okay with this. :+1:

**Comment by nzakas** [comment]
I think this is OK, both from custom parser and future syntax points of view. The difference between a word and non-word is well-defined, so there's no reason we can't treat unknown words correctly. It's up to the parser to tell us the operator is valid, we just have to categorize.

**Comment by AdriVanHoudt** [comment]
I am updating Lab to 0.23 and suddenly I get an unexpected lint error I assume due to this issue, see https://github.com/hapijs/lab/pull/381, the docs for the rule still state that there ae defaults, see http://eslint.org/docs/rules/space-unary-ops
Might be useful to update the docs according to this change

**Comment by AdriVanHoudt** [comment]
On further notice, I don't see a reason why `this.count++;` gives an error. It has something to do with the `++` but I don't see why it should error apart from being a bad config somewhere or a bug

**Comment by michaelficarra** [comment]
@AdriVanHoudt this has been fixed already.

**Comment by AdriVanHoudt** [comment]
in what version? or when will the fix land?

**Comment by michaelficarra** [comment]
master

**Comment by AdriVanHoudt** [comment]
is there an eta on next release?

**Comment by michaelficarra** [comment]
I don't think releases are scheduled like that. They're fairly frequent, though.

**Comment by AdriVanHoudt** [comment]
I know, I thought maybe there was some form of timeline. Well I hope that there is patch or new version release soon then! Thanks for the info!

**Comment by nzakas** [comment]
Likely this weekend. We try to do releases every two weeks.
