### ISSUE TITLE
eslint mangles error messages thrown by parser which don't start with "line \d+:"

### ISSUE THREAD

**Issue by gfxmonk** [eslint/eslint#2698]
Custom parsers may throw error messages which don't start with e.g. "line 123:". The [current code][0] just strips off everything before the first colon in the error message, which leads to a mangled message if it didn't actually start with "line XX:".

[0]: https://github.com/eslint/eslint/blob/c8a56e2b7c3f27331f93c607947e8c18caa16c18/lib/eslint.js#L468

I'm working on this, but the tests depend on #2694 being merged so I'll wait until that's closed before actually submitting my PR.

**Comment by gyandeeps** [comment]
Can you share an example?

**Comment by gfxmonk** [comment]
For example, the StratifiedJS parser can throw errors with messages like:

    unexpected token: `{`

Because the code trims off everything before the first colon, eslint strips of the first part and just reports a confusing error message of:

    `{`

My change will just replace `/^line \d+:/i` with the empty string, rather than removing everything before the first colon. If the above pattern doesn't match, nothing will be removed.

**Comment by nzakas** [comment]
I think it's an OK change to make, but we do need tests to validate the change.

**Comment by gfxmonk** [comment]
Cool, yeah it comes with tests. You can see my implementation [here](https://github.com/gfxmonk/eslint/commit/9d878ea37faee2e1521e729cd88ebfaf7aeb2a50), but as I mentioned the tests depend on #2694 so it can't be merged just yet.
