### ISSUE TITLE
allow `extends` to be an array

### ISSUE THREAD

**Issue by fakewaffle** [eslint/eslint#2699]
Currently, [extends](http://eslint.org/docs/user-guide/configuring#extending-configuration-files) only allows one file but it should allow an array:

**Sample `.eslintrc` file:**
```json
"extends" : [
	"./node_modules/coding-conventions/.eslintrc-defaults",
	"./node_modules/coding-conventions/.eslintrc-jsx",
	"./node_modules/coding-conventions/.eslintrc-es6"
]
```

**Comment by ilyavolodin** [comment]
How do we resolve conflicts in that case?

**Comment by fakewaffle** [comment]
`.eslintrc-es6` would override `.eslintrc-jsx`, which would override `.eslintrc-defaults`.

`.eslintrc` would override all the extends.

**Comment by gcochard** [comment]
In other words: they override in-order, with the last array element taking highest precedence.

**Comment by nzakas** [comment]
I was actually thinking about this, as well. I like the idea.

**Comment by fakewaffle** [comment]
I submitted a pull request. Let me know your thoughts. :)
