### ISSUE TITLE
Expand ~ to the current user's home directory for cli options.

### ISSUE THREAD

**Issue by tupton** [eslint/eslint#2701]
So something like `eslint --config="~/.eslintrc" --ignore-dir="~/eslintignore" --rulesdir="~/.config/eslint/rules" --output="~/output"` works as expected and uses files in the user's home directory.

**Comment by nzakas** [comment]
Are you saying this doesn't currently work?

**Comment by tupton** [comment]
```
❯ git pull origin master
From https://github.com/tupton/eslint
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
❯ ./bin/eslint.js --version
v0.22.1
❯ ./bin/eslint.js --config=~/.eslintrc lib/
/Users/tupton/code/eslint/lib/config.js:76
                throw e;
                      ^
Error: Cannot read config file: /Users/tupton/code/eslint/~/.eslintrc
Error: ENOENT, no such file or directory '/Users/tupton/code/eslint/~/.eslintrc'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at loadConfig (/Users/tupton/code/eslint/lib/config.js:72:57)
    at new Config (/Users/tupton/code/eslint/lib/config.js:323:34)
    at CLIEngine.executeOnFiles (/Users/tupton/code/eslint/lib/cli-engine.js:303:28)
    at Object.cli.execute (/Users/tupton/code/eslint/lib/cli.js:179:95)
    at Object.<anonymous> (/Users/tupton/code/eslint/bin/eslint.js:32:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by nzakas** [comment]
What happens if you do this?

```
$ eslint --config ~/.eslintrc lib
```

**Comment by michaelficarra** [comment]
@nzakas The shell will expand that. @tupton wants to have the option to pass `~` literally to eslint and have eslint do the expansion.

**Comment by tupton** [comment]
That works, presumably because my shell expanded "~" in that particular case.

It still stands that this doesn't work if you provide a path that starts with "~" when using eslint programmatically.

**Comment by tupton** [comment]
Is this not a common thing to do? Is it expected that you shouldn't pass paths starting with "~" to most tools?

If we really want to keep the current behavior, can we document the fact that you need to pass paths as either relative to cwd or absolute from the root directory? And maybe document the fact that paths beginning with "~" are treated literally and not expanded?

**Comment by michaelficarra** [comment]
@tupton I don't know of a single GNU util (or any other program) that will expand a literal `~` for you. They all let you work with a directory named `~`. Expanding it would be a surprising feature.

```
$ mkdir "~"
$ touch "~/file"
$ cd "~/.."
$ rm "~/file"
$ rmdir "~"
```

**Comment by tupton** [comment]
Fair enough. I think it can be expected that users who have paths beginning with "~" have to perform this expansion before giving the directory to eslint, whether by their shell or otherwise. Thanks for taking the time to look at this.
