### ISSUE TITLE
Consider the default behavior of `no-use-before-define` rule

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2704]
Hello.

On JavaScript, a fact of function declarations are hoisted is well known.
I had been implementing (#2612), the `no-shadow` rule will treat functions as hoisted by default.
But now, the default behavior of the `no-use-before-define` rule is not so.  To use functions before each declaration, it requires `"nofunc"` option.

I want to discuss before `v1.0.0` - wouldn't we change or not the default behavior of the `no-use-before-define` rule to "function declarations are hoisted"?
I thought it's better to help understanding of users when rules are providing each default behavior under consistent principle.

Thank you for read.

**Comment by michaelficarra** [comment]
Agreed, this seems best. I also dislike the double negation with the option name.

**Comment by nzakas** [comment]
This is a bit of a different case than `no-shadow`. `no-use-before-define` is about treating things as if they aren't hoisted. `no-shadow` is about avoiding naming collisions. I'm not sure there's any relationship between these two rules.

**Comment by ilyavolodin** [comment]
This rule was create to help developers who are not very familiar with JavaScript and hoisting. Basically, in any other language, the code where the function shows up after it was used would not even compile. Some people prefer to stick with that limitation, to avoid confusion. And yes, I do understand that in JavaScript it's a perfectly valid construct.

**Comment by mysticatea** [comment]
Thank you.

I thought `no-unused-vars`, `no-undef`, `no-shadow`, and `no-use-before-define` have a common purpose, developers use references correctly. Those rules are the way for it. But, the definition of "correctly" looked different each rule to me.

- `no-undef` - all variables as hoisted.
- `no-unused-vars` - all variables as hoisted.
- `no-shadow` - functions as hoisted by default.
- `no-use-before-define` - all variables as not hoisted by default.

Those was listed, I felt: if `no-undef` and `no-unused-vars` have an same option as `no-shadow`'s, it may be a substitute for `no-use-before-define` and better...? Umm, I have no confidence.

However this doesn't give us new features, so I don't mind if you close this issue.

**Comment by gyandeeps** [comment]
closing based on the above post.

**Comment by michaelficarra** [comment]
The default configuration for these rules should not have this kind of inconsistency. We should do something about it.
