### ISSUE TITLE
space-unary-ops should enforce yield spacing

### ISSUE THREAD

**Issue by michaelficarra** [eslint/eslint#2707]
I would expect `space-unary-ops` (with the default options) to report `yield(0)` and `yield+0`. I would probably expect it to report `yield*0` and the like as well.

**Comment by nzakas** [comment]
Is yield considered an operator?

**Comment by michaelficarra** [comment]
Yield is an operator anywhere within a generator. Elsewhere, it's simply an identifier. But if you ever see a YieldExpression, yes, it's an operator.

**Comment by gyandeeps** [comment]
are we fixing this? if yes, is it a bug or enhancement?

**Comment by michaelficarra** [comment]
I would classify it as a bug.
