### ISSUE TITLE
Rule Proposal: no-const-assign

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2719]
Variables that declared with `const` cannot re-assign.
Under strict mode, it raise a runtime error. Otherwise just ignored (on V8).

The following patterns are considered warnings:

```js
const a = 0;
a = 1;
```

I'm happy to work if it was accepted.

**Comment by nzakas** [comment]
I thought we had an issue covering this already, but apparently not. I like it.

**Comment by michaelficarra** [comment]
I would like to see this rule apply to other constant bindings such as the function name binding created by `(function a(){ a = 0; });`, `class A { f(){ A = 0; }`, and `(class A { f(){ A = 0; } });`.

**Comment by nzakas** [comment]
Those would be covered by no-func-assign and no-class-assign, I believe.

**Comment by michaelficarra** [comment]
@nzakas No, that's not what `no-func-assign` does, and `no-class-assign` is currently proposed to catch assignments to writable bindings. I am proposing this rule catches writes to all const bindings and nothing more.

**Comment by nzakas** [comment]
I'd prefer to have this rule just deal with `const` declarations. We can update `no-func-assign` to work with function expression names, and `no-class-assign` can handle the rest. That seems like a much more logical grouping for end-user understanding.
