### ISSUE TITLE
Rule Proposal: no-this-before-super

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2721]
If the class declaration has `extends`, we cannot use `this` before `super()` calling in its constructor.
See Also: https://github.com/babel/babel/issues/1131

The following patterns are considered warnings:

```js
class A extends B {
  constructor() {
    this.c = 0;
    super();
  }
}
```

The following patterns are not considered warnings:

```js
class A extends B {
  constructor() {
    let c = () => { this.d = 0; };
    super();
  }
}
```

```js
class A extends null {
  constructor() {
    this.c = 0;
  }
}
```

```js
class A {
  constructor() {
    this.c = 0;
  }
}
```

I'm happy to work if it was accepted.

....this name is too long....

**Comment by ilyavolodin** [comment]
Seems reasonable. But yes, we need new name. `no-this-before-super` might work, but it's not very descriptive.

**Comment by michaelficarra** [comment]
This is not something that can be statically detected. What do you do about this?

```js
class A extends B {
  constructor() {
    if (Math.random() < 0.5) this;
    super();
  }
}
```

Or this?

```js
class A extends B {
  constructor() {
    if (false) this;
    super();
  }
}
```

:-1:

**Comment by sindresorhus** [comment]
@michaelficarra The check could still be a "best effort". With that logic nothing is statically detectable as `eval` might be used.

**Comment by michaelficarra** [comment]
@sindresorhus No, lots of things may be statically determined in the presence of `eval`. I gave the two examples because, even if you took the pessimistic approach and warned about the first example, that approach would be too pessimistic for cases like the second example. If you took the optimistic approach and *did not* warn about the second example, that approach would be too optimistic for cases like the first example.

**Comment by ilyavolodin** [comment]
@michaelficarra It is impossible to determine 100% correctly, but we can do the same thing as `babel`. In some cases something is better then nothing.

**Comment by nzakas** [comment]
Let's go for best effort here, I think this can be useful even without catching 100% of the cases. I like `no-this-before-super`.

**Comment by mysticatea** [comment]
Thank you for many opinions.
I will implement this rule with using execution paths analyzing such as #2762.

**Comment by nzakas** [comment]
@mysticatea please see my note on your PR - we really can't afford to have party analysis in multiple rules. Let's just keep this simple and look for `this` before `super` as a starting point. We can always make it better later.
