### ISSUE TITLE
Can't have nested .eslintrc in home directory

### ISSUE THREAD

**Issue by willlma** [eslint/eslint#2724]
When I have one .eslintrc file at `~/.eslintrc`, everything works as expected. But when I add one to `~/project/extension` and try to lint `~/project/extension/index.js`, the former is ignored and only the first error in the file is reported (although there are many). Moving the former into `~/project` solves the problem, but I'd like to be able to use a generic `.eslintrc` for every `js` file on my computer.

**Comment by ilyavolodin** [comment]
This is working as designed. `.eslintrc` file in your home directory will only be picked up if no other files are found in the repository. If you would like to have one global file, then you should use `extends` functionality.

**Comment by gcochard** [comment]
See #2279, this is the correct behavior.

You can create a subdirectory for your projects that should all share the same config, and put a `.eslintrc` in there.

**Comment by willlma** [comment]
Thanks, @ilyavolodin. Is this mentioned in the docs? Would be great to have a warning in `DEBUG=eslint:*` command. Spent too many hours figuring out why it wasn't working as I was transitioning from JSHint, which does allow for this behaviour.

**Comment by nzakas** [comment]
Yes, this is explicitly mentioned in the docs: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by willlma** [comment]
@nzakas I see no mention of the fact that you can't place a `.eslintrc` file in the home directory.
>The configuration cascade works by using the closest `.eslintrc` file to the file being linted as the highest priority, then any configuration files in the parent directory, **and so on**.

Those last words seem to imply that it would work.

**Comment by nzakas** [comment]
If you keep reading, you'll come across this:

Project-level configuration:

1. .eslintrc file in same directory as linted file
1. package.json file in same directory as linted file
1. Continue searching for .eslintrc and package.json files in ancestor directories (parent has highest precedence, then grandparent, etc.), up to and including the root directory.
1.** In the absence of any configuration from (i) and (ii), fall back to ~/.eslintrc - personal default configuration**

We can probably call it out more, though.
