### ISSUE TITLE
ES7 Function Bind Syntax

### ISSUE THREAD

**Issue by cbas** [eslint/eslint#2728]
I get an error when using ES7 function bind. This experimental feature is currently supported by Babel (as of 5.4.0).

foobar.js:
```js
const foo = {}
function bar () {}
foo::bar()
```

```bash
$ eslint foobar.js --env es6

foobar.js
  3:5  error  Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```

```bash
$ eslint --version
v0.22.1
```

Is this supported yet by Eslint? I'm not sure where to start looking.

References:
- https://github.com/zenparsing/es-function-bind
- https://github.com/babel/babel/pull/1518

**Comment by nzakas** [comment]
ESLint doesn't support experimental features natively. You'd need to use babel-eslint for that.

**Comment by cbas** [comment]
Aha, thank you very much for the tip! :+1:
