### ISSUE TITLE
Performance linting

### ISSUE THREAD

**Issue by Raynos** [eslint/eslint#2729]
There are various performance oriented rules that one can think of that may or may not be out of scope for eslint.

This issue is to discuss whether eslint should ship with linting rules aimed at writing performant javascript.

Some examples:

 - disallow `.bind()` as its a de-optimization
 - disallow `.map()`; `.forEach()` and friends as for loops are more performant.
 - support a blacklist of modules (i.e. cannot `npm i x` and use it because its blacklisted as not performant).

Would these feature requests fall within the scope of eslint or should they be a seperate package ?

> ESLint does both traditional linting (looking for problematic patterns)

I personally believe slow code is a problematic pattern and that adding these rules to core has value.

I'd be willing to contribute a set of rules like that and contribute to documentation to mark them as performance sensitive.

I'd also be willing to add a feature to eslint to be able to lint "performance sensitive code" and "test / utility code" differently. Personally I use a lot of "slow" ES5 features in tests or one off scripts just so that I can finish my tests and move on.

cc @nzakas @ilyavolodin

**Comment by xjamundx** [comment]
These rules are totally needed and at least for starters would be great as a seperate plugin.

**Comment by ilyavolodin** [comment]
Agree with @xjamundx those are really nice rules to have, but I do think it's probably a good idea to start them out as a plugin. Reason being that while they are useful for everyone, one a small subset of people will probably turn them on.

**Comment by xjamundx** [comment]
My true dream for all of this stuff is for them to be part of a babel transform that just converts the slow stuff into fast stuff :)

**Comment by mathieumg** [comment]
> My true dream for all of this stuff is for them to be part of a babel transform that just converts the slow stuff into fast stuff :)

But then it doesn't educate the developer. That's the reason behind the "autofix" feature in the ESLint 2.0 wishlist: warn (slap on the wrist), autofix!

**Comment by Raynos** [comment]
@ilyavolodin @xjamundx @nzakas 

I think performance linting is a non-trivial critical problem and many people would benefit from it.

If we all agree it's a good idea; would it be ok to to write the plugin under the `eslint` github organization. This would force discussion and code review, as well as complying with the `eslint` style guides and contribution model.

It would still be an optional plugin but everyone working on eslint that cares about performance would contribute to it.

I would like to get @nzakas opinion on this though; if he believes it's not in scope of eslint I will create these as a personal set of plugins.

**Comment by ilyavolodin** [comment]
@Raynos Don't get me wrong, I completely agree that people would benefit from it:-) But performance is neglected in a lot of cases... The most popular front-end framework right now is Angular, so I think it makes my case for me:-) If @nzakas agrees to ESLint org repository for it, I think that would ideal solution.

**Comment by lo1tuma** [comment]
* How do you know that all of your suggested built-ins (`.bind`, `.map` etc) are slow in all js engines?
* Are you sure that those built-ins are slow in future releases of any js engine (e.g. v8)? Maybe they become faster than the workaround.

I think you should better spend the time to optimize at algorithm-level.

**Comment by nzakas** [comment]
I'd hesitate to create any performance-specific rules as part of ESLint core because performance is not constant. `bind()` is slow *right now*, but that doesn't mean it always will be. For `map()`, the performance difference vs. a loop is inconsequential for any reasonable size array.

So, I agree with the suggestion that this is better as a plugin.

**Comment by Raynos** [comment]
@nzakas thanks. I'll create a plugin for it.
