### ISSUE TITLE
Rule suggestion: Create an option for allow-short-circuit-evaluation

### ISSUE THREAD

**Issue by KevinGrandon** [eslint/eslint#2733]
Please see the comments below by jwarkentin about creating an `allow-short-circuit-evaluation` option.

---

Please see https://github.com/eslint/eslint/issues/2684#issuecomment-110255859

We would like to differentiate no-op statements against unused statements. The no-useless-expressions rule would be a subset of the no-unused-expressions rule, and would error on things like:

```
a;
a + b;
"Hello World!";
```

**Comment by mathieumg** [comment]
:+1:

**Comment by lo1tuma** [comment]
What about `foo.a + foo.b;`?

Properties can have getters with side-effects so you will never know if this pattern is a useless expression.

**Comment by nzakas** [comment]
We don't create rules that are subsets of existing rules - that creates too much confusion. The only potential option would be to add an option to the existing rule, but as @lo1tuma points out, I'm not sure what you're looking for is truly possible to determine through static analysis.

**Comment by michaelficarra** [comment]
@nzakas This is exactly as analysable as `no-unused-expressions`. I believe this rule proposes allowing anything that could determine whether one of the currently accepted effectful expressions is reached. For example, this would be allowed under this proposal, but not under `no-unused-expressions`:

```js
a ? b() : c && new d;
```

**Comment by jwarkentin** [comment]
Through static analysis it is difficult or impossible to catch every case, but it would catch almost all cases if the rule simply allowed function calls and assignments in an expression and warned on anything else.

So, the following would all be valid:
```js
cb && cb();
options || (options = {});
a ? b() : c;
```

I wouldn't worry about getters and setters since they are not as commonly used and it's difficult to know if they exist. Let's just handle the common use cases.

The example by @michaelficarra raises and interesting question as to whether the `new` keyword should also be considered as a condition that causes side-effects and thus does not warn. While it does call the constructor function, I think constructor functions are uniquely different from regular function calls in that most of them probably don't have side effects as they only operate on the constructed object, making them meaningless without an assignment. That is not always the case though. I would be happy regardless of how the rule handled those. I really just think we need a rule for the common use cases.

**Comment by jwarkentin** [comment]
FYI, there was a pull request a while back that changed the behavior. You could work off of this pull request to add a flag if that's the preferred route to do it. See https://github.com/eslint/eslint/pull/2417

**Comment by nzakas** [comment]
`new` needs to be considered the same as a function call.

@jwarkentin please propose a new option for this rule and explain specifically what it would do as compared to what the rule currently does.

**Comment by jwarkentin** [comment]
I don't know if you prefer more verbose names or shorter names for options, but here are some possible option names: `allow-short-circuit-evaluation`, `allow-short-circuit`, `short-circuit-evaluation`, `short-circuit` or just `sce`.

Basically, the option would allow short circuit evaluation as described [here](http://en.wikipedia.org/wiki/Short-circuit_evaluation). That is, it would not warn if any expression or nested expression contains a function call, an assignment or a `new` operator which obviously calls a function.

That is the extent of what can reasonably be determined by static analysis to have side effects and I am positive that it would satisfy the community.

**Comment by ev0rtex** [comment]
If it would help I'd be happy to take some time and modify the code I submitted in #2417 (referenced above by @jwarkentin) to put the functionality behind an option. I have seen a decent number of issues here concerning this behavior. Short-circuit evaluation is a common practice in JS and it's my two cents that it should be allowable without having to litter code with comments.

**Comment by nzakas** [comment]
I'm not sure if @KevinGrandon wanted this focused strictly on short circuit operations or not, it's unclear from the original description.

**Comment by KevinGrandon** [comment]
I am happy with a `allow-short-circuit` option as that would solve the use cases for myself, and many others it seems.

**Comment by mathieumg** [comment]
Same here, an option to whitelist the `a && a()` pattern and I'd be good to go.

**Comment by gyandeeps** [comment]
Any updates here?

**Comment by ev0rtex** [comment]
@gyandeeps I have some code almost ready to go. I've been distracted on a lot of other projects but I'll try and get a PR put together ASAP. I just need to implement some more tests and make sure it's working correctly.

**Comment by yuvalsaraf** [comment]
Would love to see that! :+1:

**Comment by gyandeeps** [comment]
@nzakas I guess we need label updates but not sure?
@ev0rtex Are you still working on this (just checking)?

**Comment by ev0rtex** [comment]
@gyandeeps I have completed it actually. I will get a PR up ASAP. Sorry it took me so long.

**Comment by gyandeeps** [comment]
np. I was just checking.

**Comment by ev0rtex** [comment]
@gyandeeps, @nzakas: Let me know if anything further is needed for my PR. I tried to be pretty exhaustive on the rule tests and documentation so that it's clear what the new options allow and disallow.
