### ISSUE TITLE
no-unused-vars suggestion: ignore vars with a leading underscore

### ISSUE THREAD

**Issue by gfxmonk** [eslint/eslint#2738]
I like the no-unused-vars rule, but it often triggers when I have no real choice. For example, callbacks which take multiple arguments but don't use them all:

    ['foo','bar'].map(function(elem, idx) { return idx; });

Obviously this is a pretty useless example, but there are plenty of cases where you need to bind one variable in order to use a later one. Destructuring assignments are another case:

    var [ content, lineno, column ] = info;
    // I only need `lineno` and `column`

In these cases, I'd like to use a leading underscore to indicate to eslint that I _know_ I'm not using this variable, and that that's OK. So I'd write:

    ['foo','bar'].map(function(_elem, idx) { return idx; });

This would miss errors where you forget to use a variable which starts with an underscore, but I think the tradeoff is worth it. Using an underscore for unused variables is a fairly well-known idiom, and ignoring unused variables which begin with an underscore is established in other languages which warn about unused variables (e.g. Haskell, OCaml).

I'd like to make this the default behaviour, but it could also be hidden behind a configuration option for the `no-unused-vars` rule if you want to be conservative.

**Comment by michaelficarra** [comment]
See previous issues about this. The function parameter case is already an exception in this rule. For array binding patterns, you can use holes.

**Comment by nzakas** [comment]
See #2321. Duplicate request.
