### ISSUE TITLE
New version of Sinon is breaking all builds

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2742]
New version of Sinon (v1.15.1) was released and is missing a folder. We should pin Sinon to version 1.14.1 till this is fixed.

**Comment by gyandeeps** [comment]
If we do this then we need to make sure revert this commit later when sinonJs fixes the issue.

**Comment by ilyavolodin** [comment]
Yes, we've already done this with a few other packages before.

**Comment by gyandeeps** [comment]
Sounds good.
