### ISSUE TITLE
Unpin io.js and sinon dependancies

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2745]
We are currently setting Travis to run only io.js v2.1.0 and sinon is pinned to version 1.14.1 due to bugs in the following versions. Once the fix for Sinon is released, we should unpin both dependencies.

Status:
- [x] iojs - New version has been released
- [x] SinonJs - Tracking https://github.com/cjohansen/Sinon.JS/issues/761 - 1.15.3 has fixed this issue

**Comment by gyandeeps** [comment]
Update:
- [x] iojs - New version has been released
- [ ] SinonJs - Tracking https://github.com/cjohansen/Sinon.JS/issues/761

**Comment by ilyavolodin** [comment]
We should probably upgrade `object-assign` at the same time to version 3.0.0

**Comment by gyandeeps** [comment]
I think we should update `estraverse` because as of now `espree` supports `super` but our version of estraverse doesn't. thoughts @michaelficarra ?

**Comment by btmills** [comment]
Supposedly sinon@1.15.3 has fixed the issue.

**Comment by nzakas** [comment]
Upgrades should be done separately so we can revert just one if necessary.

**Comment by btmills** [comment]
Upgrading to sinon@1.15.3, we get deprecation warnings in the test output:

![](https://www.dropbox.com/s/yq7aop2m1keekr3/Screenshot%202015-06-11%2014.01.09.png?dl=1)

**Comment by nzakas** [comment]
Wtf? Mock is a key utility in Sinon. Is there any docs on its removal?

**Comment by btmills** [comment]
> Wtf? Mock is a key utility in Sinon. Is there any docs on its removal?

Looks like that conversation is occurring in cjohansen/Sinon.JS#745.

**Comment by btmills** [comment]
#2756 took care of the iojs portion of this. Do we want to include `object-assign` and `estraverse` as part of this issue too? I'm guessing we'll hold off on upgrading `sinon` for now.

**Comment by nzakas** [comment]
I'd open a separate issue for misc upgrades not related to breakage

**Comment by ilyavolodin** [comment]
I think we might want to hold of with Sinon upgrade then. Mock is too important to have a warning printed out every time.

**Comment by gyandeeps** [comment]
FYI, https://github.com/eslint/eslint/pull/2762 would update `estraverse` based on the need.

**Comment by nzakas** [comment]
I think it's fine to pin Sinon. It's a testing utility, so we don't lose much by not upgrading.
