### ISSUE TITLE
no-use-before-define: noclass option (similar to nofunc) would be handy

### ISSUE THREAD

**Issue by tomaskulich** [eslint/eslint#2750]

**Comment by michaelficarra** [comment]
I think we should just extend `nofunc` to be an exception for all declarations. This would include function, generator, class, export function, export generator, and export class declarations.

**Comment by tomaskulich** [comment]
That's definitely OK by me, if there is a consensus on this, I can do it like this.

**Comment by RReverser** [comment]
Does it include function/class/generator expressions being assigned somewhere?

**Comment by michaelficarra** [comment]
@RReverser can you be more specific?

**Comment by RReverser** [comment]
`someVar = class {}`, `someObj.method = function () { ... }` and so.

**Comment by tomaskulich** [comment]
someInstance = new someVar();    
     someVar = class {};

will cause warning. The behavior is the same for functions and was not the subject to my PR. However, personally I'd like if 
    
    someVar = class {};

was the same (from the perspective of this rule) as
    
    class someVar{}

**Comment by nzakas** [comment]
Let's make sure we are all taking about the same thing here.

@tomaskulich please provide:

1. The source code you're concerned with
2. The actual ESLint output
3. What you'd like the output to be

**Comment by mysticatea** [comment]
```js
let a = new A();
class A { }
```

This code will raise a runtime error. `ClassDeclaration`s are NOT hoisted. It's not similar to `FunctionDeclaration`s. It's similar to `let`/`const` declarations.

See Also: http://www.2ality.com/2015/02/es6-classes-final.html#class_declarations_are_not_hoisted

We must be careful about it.

**Comment by RReverser** [comment]
@mysticatea Sure, we are not talking about hoisting here.

**Comment by tomaskulich** [comment]
@nzakas 

This whole issue is related to no-use-before-define rule. 

As the title of the issue (noclass option (similar to nofunc) would be handy) implies: I'm proposing here a new functionality (new option) for the rule. Therefore typical bug-reporting (I write this, I expect that, I got else) is not applicable here. I'm sure that if you recall what no-use-before-define rule and its nofunc option does, the point of having 'noclass' option is obvious.

@mysticatea 
Thanks for the hoisting remark, you're right, about classes being different than functions

@all
After some reading I realized, my original PR solves only quite small subset of the original problem and should be rejected in favor of doing more complex change:

Rule no-use-before-define should do some reasoning about scopes, not only compare the lines of code, where the declaration / usage happens. Generally, when the variable was defined in a parent scope, even if the definition comes after (in terms of lines of code) the usage, it should be considered OK (possibly warning, this can be configurable; however, I'd make OK the default behavior). Note that this solves #2747 in a better way than just adding 'nofunc' or 'noclass' options.

The behavior of the proposed solution would be such as

      // error
      f();  
      var f = function(){}

, 

      // ok, x is defined in parent scope (possible warning)
      f(){return x;}
      var x = 0;

,

      // warning (unless nofunc is ON)
      f();
      function f(){};

, 

     // error (classes are not hoisted)
     a = new A();
     class A{}

,
    
    // ok (possible warning), A is defined in the parent scope
    var f = function(){var a = new A();}
    class A{}; // alternatively, var A = class{};

**Comment by nzakas** [comment]
@tomaskulich I ask the same info for bug reporting and enhancements to existing rules because sometimes it's not obvious what people suggest. Sometimes we even already have an option that addresses the concern, and going through these steps helps uncover it. Submitting an issue with just a title and no description makes it very hard for us to help you. Saying you won't answer my questions because you don't think they apply also isn't helpful.

So I'm going to give you another chance, please answer my questions so I can better understand what it is you're asking for.

**Comment by tomaskulich** [comment]
@nzakas

originally, my problem was such as:

    var f = function(){var a = new A();}
    class A{}; 

which resolves in no-use-before-define warning (A was used before it was defined), no matter how you configure the rule.

As I see it now, adding noclass option is actually a bad idea and this issue should be closed in favor of most complex change in no-use-before-define rule. Turning off no-use-before-define rule for specific variables (function, classes) can help you to get rid of the symptoms sometimes but it does not solve the main issue here: no-use-before-define does not really "understand" the code. Note that the following code is perfectly valid and it would be nice if I could configure the no-use-before-define rule to accept it (while still warning me, when my my code is wrong)

    function f(){
        return a;
    } 
    var a = "hello";

**Comment by nzakas** [comment]
Closing per last comment
