### ISSUE TITLE
"this" is an "Unary word operator" since 0.23.0

### ISSUE THREAD

**Issue by theodoreb** [eslint/eslint#2764]
Got this error updating to 0.23.0:

```
Unary word operator "this" must be followed by whitespace  space-unary-ops
```

for this line:
```js
this.indents--;
```

Guessing it's related to #2696.

**Comment by gyandeeps** [comment]
@theodoreb can you share your rule config?

**Comment by theodoreb** [comment]
Sure, http://cgit.drupalcode.org/drupal/tree/.eslintrc

**Comment by btmills** [comment]
So far, the only examples I've found that trigger this are postfix increment or decrement operators. Of the following, only the first and last lines will warn. In both cases, the message is `Unary word operator "this" must be followed by whitespace`.

```js
this.indents--;
this.prop = 42;
this.foo();
bar(this.prop);
!this.bar;
++this.prop;
this.prop++;
```
