### ISSUE TITLE
Eslint Maximum Warnings

### ISSUE THREAD

**Issue by guyellis** [eslint/eslint#2769]
Is there a way to cause eslint to error if there are more than N warnings?

In istanbul you can run it with the check-coverage command and put a threshold on the minimum coverage: https://github.com/gotwarlost/istanbul#the-command-line

Use case: You have (say) 150 warnings. Because there are so many warnings team members start ignoring them and they start getting worse. You might decrease the warnings in a commit to 140 and then another team member increases them to 155. If you can lock in the maximum warnings before eslint returns an error then you can lock in commits that reduce the number of warnings.

e.g. `eslint --max-warnings 150`

**Comment by gyandeeps** [comment]
As of now this functionality is not present.

**Comment by nzakas** [comment]
I'm not sure I understand this use case. Warnings by definition do not change the exit code. You're asking that if there's are a certain number, the exit code should change?

**Comment by guyellis** [comment]
@nzakas Yes. It is driven by a command option. In my example above the exit code would change if there were more than 150 warnings.

This type of feature is used by `istanbul` to "prevent" developers from reducing code coverage on a commit. So for eslint it would be used to prevent developers from increasing the number of warnings in a project.

**Comment by nzakas** [comment]
Got it, sounds useful. It will be low priority for the core team, but open to anyone who wants to submit a PR.

**Comment by platinumazure** [comment]
I'm willing to look into writing a PR, but I'd like to ask if there should be a config equivalent for this (to allow config files in subdirectories to tighten rules).

If we did that, we would probably have to have restrictions that "higher-precedence" config files can only tighten the warning count relative to the more general files. I'm already getting a headache just thinking about that, so maybe not; but I just wanted to throw the idea out there.

**Comment by guyellis** [comment]
@platinumazure my opinion is that there would not be a config equivalent and that it would be a global flag/condition against total warnings.

In normal usage a developer would reduce the number of warnings and then change the --max-warnings value in the package.json to "lock in" their changes. In an extremely rare use case a developer might reduce the warnings in a subdirectory and increase them in another location. Let's say, for example, they decreased warnings by 10 in /foo and increase them by 10 in /bar. In this situation there would be no change to the global --max-warnings flags. If there were a config equivalent then they could "lock in" the reduction in /foo by changing the max-warnings in the config file in that directory and increase it in the /bar directory (if there was a config file there). The "locking in" by subdirectory does not seem very useful.

**Comment by nzakas** [comment]
Agreed. This would be purely a command line option.

**Comment by guyellis** [comment]
Another comment about this feature from what I've seen working on large real world apps:

Everyone seems to want to use a linting tool and often it's added after the project is under-way or the settings are tweaked mid-project. This can result in a number or warnings being generated by the project. A quick glance at the warnings determines that there's nothing to really worry about (e.g. space after comma) but we'd like to keep that setting in place and tidy up the code later. That later is often a long time coming. In the meantime nobody is monitoring or noticing that the warnings are slowly increasing.

By locking in the max warnings we are immediately adding value to the project by preventing more "bad" code from being added and giving us a better chance of reducing those warnings when we have some breathing room.

**Comment by nzakas** [comment]
@guyellis we've already agreed to do it :)

**Comment by guyellis** [comment]
@nzakas sorry - got carried away with my enthusiasms for it :)

**Comment by platinumazure** [comment]
@guyellis @nzakas Fair enough-- just had to float it out there.

**Comment by IanVS** [comment]
@guyellis I can't resist a shameless plug for my own [ESLint-Nibble](https://github.com/IanVS/eslint-nibble), which is useful when you have a large number of errors and/or warnings from adding ESLint to an existing project, and want to tackle them slowly over time.

Oh, and I like this proposal for "locking down" warning count.  I'll look forward to seeing what @platinumazure cooks up.  :)

**Comment by guyellis** [comment]
@IanVS Very nice! I'll definitely be using that before adding eslint to the next unlinted project I get pulled into. Thanks!

**Comment by platinumazure** [comment]
Been busy at work but I'm about to start taking a crack at this. Thanks for your patience, folks!

**Comment by mmrko** [comment]
:+1:
