### ISSUE TITLE
`spaced-comment` warns on "don't minify" comment blocks

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#2777]
Typically, the first comment block in a file starts with `/*!` to indicate to a minifier like uglify that it should not strip the comment block (a "prelude").

Could we add an option to the `spaced-comment` rule that allows this pattern?

**Comment by gyandeeps** [comment]
You can use `exceptions` option.
http://eslint.org/docs/rules/spaced-comment

**Comment by ljharb** [comment]
aha, thanks! Sorry I missed that in my reading :-)

However, I tried adding `["!"]` as the exceptions list, and I get "Expected exception block, space or tab after /* in comment". The comment block is https://github.com/es-shims/es7-shim/blob/master/es7-shim.js#L1-L5

**Comment by gyandeeps** [comment]
after further looking into this, I dont think there is an clean way to get rid of the error.
Should we just ignore multi-line block comments for this rule?

CC: @eslint/eslint-committers

**Comment by ljharb** [comment]
Personally I wouldn't want to allow:
```js
/*blah
 *blah
 */
```
but that might be pretty specific. If this only covered single-line comments I still think it'd be useful.

**Comment by gyandeeps** [comment]
To solve your case, you have to do what you just specified above. as of now.

**Comment by ljharb** [comment]
Then for now I'll have to leave the rule disabled :-( thanks for the quick replies

**Comment by gyandeeps** [comment]
Found the problem. As of now if you use a `marker` then you have to specify a `space` to `tab` after it.
But we can start allowing `\n` then this scenario would work out.
Here is the code: https://github.com/eslint/eslint/blob/master/lib/rules/spaced-comment.js#L49

**Comment by ljharb** [comment]
I didn't use a marker though, I created an exception.

At any rate, I'd assume any syntactically valid whitespace would be allowed, so definitely that would include a newline, and possibly other chars (still getting confirmation on that tho)

**Comment by ljharb** [comment]
Valid whitespace is http://people.mozilla.org/~jorendorff/es6-draft.html#sec-white-space, so I'd think we'd want to include all of those?

**Comment by gcochard** [comment]
I think this is an edge case introduced when the logic for single line comments was added to multi-line comments. We should definitely allow any whitespace between lines, and we should also split milti-line comments on newline and treat each line individually.

As for this issue, @ljharb do you have any whitespace after the `!`? I believe the rule looks for exceptions and then EOL, with nothing in between.

**Comment by ljharb** [comment]
As you can see on https://github.com/es-shims/es7-shim/blob/master/es7-shim.js#L1-L5, no, no trailing whitespace, just EOL.

**Comment by feross** [comment]
I just ran into this issue with this comment block:

```js
/**
 * This is a block comment
 */
```

Neither `"exceptions": ["*"]` or `"markers": ["*"]` does the trick. But removing the newline works:

```js
/** This is a block comment */
```

Newline should be treated as whitespace in this case.

**Comment by gyandeeps** [comment]
thats what i proposed above and i agree.

**Comment by gyandeeps** [comment]
@ljharb Once the fix is done you should be able to use `markers: ["!"]` for your scenario.
@feross your scenario is more like #2766 . So it will be resolved when that issue gets resolved.
