### ISSUE TITLE
A rule to enforce a minimum identifier name length

### ISSUE THREAD

**Issue by BYK** [eslint/eslint#2784]
I propose adding a rule that checks any identifier names against a predefined minimum length (2 by default).

**The use case for the rule**: People tend to use variable names such as `e` or `x` which makes the code harder to read and less maintainable. Proposal is to add a rule that has the following properties:
 - Have a minimum length for property and variable names
 - Have a predefined, sane ignore list: `i`, `j`, `$` and `_` for now
 - Have the ability to add exceptions per expression type

This is a purely stylistic rule and I think is generic enough to be included.

I think the rule should be off by default since it may throw some people off who tend to use `x`, `y`, `a`, `b`, `e` as variable names extensively in their code.

A sample implementation which we started to use at Disqus can be found here: https://gist.github.com/BYK/837ca4e7c12d1ee1693c

I'll create a pull request if this looks good.

**Comment by nzakas** [comment]
Sounds good. I'm assuming this isn't just variables but any identifiers?

Can you propose what the rule configuration should look like?

**Comment by ilyavolodin** [comment]
I would suggest making a more generic rule called `name-length` that would apply to variables and functions and would have config options of `{min: int, max: int, exclusions: string[]}`

**Comment by BYK** [comment]
Yeah, agree that the name is close to terrible.

A sample config for the shared Gist would be like this:

    no-short-var-names: [2, 3, ['x', 'y', 'i', 'j'], ['CatchClause']]

I kept using arrays but at this point, if we also add `max` it may make more sense to use an options object instead. What do you think?

**Comment by BYK** [comment]
Edited the description to be more generic re: identifier names

**Comment by nzakas** [comment]
name-length or id-length? Technically, these are identifiers, so id would seem like a better name?

Agreed that having an options object makes the most sense.

**Comment by BYK** [comment]
>name-length or id-length? Technically, these are identifiers, so id would seem like a better name?

wfm

I'll submit a PR shortly based on these discussions. Thanks a lot for the swift feedback!

**Comment by sindresorhus** [comment]
I think it would make sense to have an option to exclude one line arrow functions as a single-character variable name makes sense there:

```js
[].map(x => x * x);
```

**Comment by nzakas** [comment]
Let's start with just named exceptions for now. If we need to add something for arrow functions specifically, then we need to start thinking about more generalizable syntax exceptions, and I'm just not convinced that's a good idea right now.

We can always add later if necessary.

**Comment by BYK** [comment]
We can probably use `_` or `__` instead of `x` or add `x` to exception list as @nzakas suggested.

Good point though. Since I am still living in the ES5 world, I forgot about arrow functions :)
