### ISSUE TITLE
"one-var": { "initialized": "never" } does not prevent initialized var declarations from being joined with uninitialized var declarations

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2786]
I expect to get an error when using this rule:

```
{
  "one-var": [2, { "initialized": "never" }]
}
```

and this code:

```js
var i, j, digits = [0]
console.log(i, j, digits)
```

Specifically, I expect this error: `Split initialized 'var' declarations into multiple statements.`

I do get an error if I do:

```js
var digits = [0], digits2 = [0]
console.log(digits, digits2)
```

I expect `"one-var": { "initialized": "never" }` to prevent initialized var declarations from being joined with any other var declarations (initialized or uninitialized).

**Comment by nzakas** [comment]
@IanVS Can you confirm?

**Comment by dcousens** [comment]
Thanks for filing this @feross.
Can confirm this bug.

**Comment by IanVS** [comment]
Yes, currently the rule only checks within each type. I agree with @feross that this is unexpected.  If @nzakas accepts, I will work on a PR.

**Comment by IanVS** [comment]
Had nothing better to do, so I made a quick fix.  If this is accepted, I'll submit it as a pull request.

**Comment by nzakas** [comment]
Accepted!
