### ISSUE TITLE
Adding the option of `generator-star-spacing`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2787]
From: https://github.com/eslint/eslint/issues/2628#issuecomment-110195576

I think options for the same purpose should have the same format.
But an option of [generator-star-spacing](http://eslint.org/docs/rules/generator-star-spacing) is different to other `*-spacing` rules.

I propose to changing the format of the option to an object such as `{before: true, after: false}`.

Thank you.

**Comment by nzakas** [comment]
We can't change the options, but we could add this as an additional way of specifying the options.

**Comment by mysticatea** [comment]
OK, I want to add this for consistency.

**Comment by nzakas** [comment]
Sounds good.
