### ISSUE TITLE
Dangling underscores from APIs

### ISSUE THREAD

**Issue by rflnogueira** [eslint/eslint#2797]
The no-dangling-underscore option is a great feature, but... 

sometimes when processing an API response, you don't really have control over the property names. 

For example when the API has a _id as fieldname.

Any suggestions on how to manage this?

**Comment by michaelficarra** [comment]
Write a function `function getId(x) { return x._id; }` and then disable this rule in that function using inline comments.

**Comment by rflnogueira** [comment]
Oh the inline comment rules, I had totally forgotten these. Thanks for the advice.
