### ISSUE TITLE
Feature Request: `context.getDeclaredVariables(node)`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2801]
From: #2732

Hello.

I thought we need a function that searches the variables by a declaring node.

Now, for ES2015 Destructuring Assignments, we cannot get variables from a declaring node by a simple way.

For Example:

```js
let {a: [x, y, ...z], b: w = function(c, d) { let d; }} = foo;
//--------
return {
    "VariableDeclaration": function(node) {
        if (node.kind === "let") {
            // what does this node declare?
        }
    }
};
```

So, when I wrote `no-const-assign` rule, I needed to traverse all variables.

----

This proposal is to add `getDeclaredVariables(node)` method to `RuleContext`.

This method provides an ability to search variables that are declared by a node.
"are declared by a node" means the node is same as `variable.defs[].node` or `variable.defs[].parent`.
The order of this method is `O(1)`.

Usage:

```js
return {
    "VariableDeclaration": function(node) {
        if (node.kind === "let") {
            var variables = context.getDeclaredVariables(node);
            console.log(variables); // [x, y, z, w]
        }
    }
};
```

----

Thank you.

**Comment by nzakas** [comment]
So this would return an array of strings? Are you certain no additional information would be necessary for this to be useful?

Also, which nodes would be supported? Just `VariableDeclaration`?

**Comment by mysticatea** [comment]
This method returns an array of `escope.Variable` objects.

Details of mapping between nodes and variables.

- `VariableDeclaration` - variables of its all declarators. (we can use destructuring)
- `VariableDeclarator` - variables. (we can use destructuring)
- `FunctionDeclaration`/`FunctionExpression` - its function name and parameters. (we can use destructuring)
- `ArrowFunctionExpression` - its parameters. (we can use destructuring)
- `ClassDeclaration`/`ClassExpression` - its class name.
- `CatchClause` - a variable of its exception. (we can use destructuring)
- `ImportDeclaration` - variables of  its all specifiers.
- `ImportSpecifier`/`ImportDefaultSpecifier`/`ImportNamespaceSpecifier` - a variable.
- others - always an empty array.

An experimental implementation: https://github.com/mysticatea/escope/commit/8a805b9c42b466f8c354b9037a764307e4476fe2

**Comment by nzakas** [comment]
Thanks, this sounds good!

**Comment by michaelficarra** [comment]
Why would a function declare its parameters? @mysticatea I recommend adding some equivalent to the spec's VarDeclaredNames and LexicallyDeclaredNames. This worked really well for us in the [Shift early error checker](https://github.com/shapesecurity/shift-parser-js/blob/es6/src/early-errors.js).

**Comment by mysticatea** [comment]
@michaelficarra 
> Why would a function declare its parameters?

1. On ESTree, [the function node has parameters directly](https://github.com/estree/estree/blob/master/spec.md#functions), so the declaring node of parameters is its function node.
2. `escope.Variable.defs[].node` of parameters is its function node. So we get ability reference bidirectionally. 
  [node] --- getDeclaredVariables ---> [variable]
  [node] <--- defs.node --- [variable]

**Comment by mysticatea** [comment]
@michaelficarra Do you think we get parameters?  We should traverse all variables in scope?

**Comment by michaelficarra** [comment]
In that case, then you probably actually want to implement `BoundNames`. See https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns-static-semantics-boundnames

You need to just flatMap BoundNames over the function parameters to collect the declared names.

**Comment by mysticatea** [comment]
@michaelficarra Sorry, I don't think so.  If variable names are gotten, we still must traverse all variables in the scope.  And if API targets the `Pattern` nodes, at same time, we should think the `AssignmentExpression` nodes. But `BoundNames` seems to not treat the `MemberExpression` nodes, so `[obj.foo] = bar;` is not treated.

The `Variable` objects have nodes that declares self, and we had been using those information to make rules.  So I think this API that gets variables from nodes that declares those is understandable and useful to us.

**Comment by mysticatea** [comment]
I'm just waiting for the EScope's release or ideas of alternative ways.
