### ISSUE TITLE
ES6 feature error or my mistake? 

### ISSUE THREAD

**Issue by SudoPlz** [eslint/eslint#2806]
I get this error ` 3:5  error  Unexpected token =`

in this file:

    'use strict';
    var React = require('react');
    var {PageHeader} = require('react-bootstrap');

If I do this the problem goes away: 

     var ReactBootstrap = require('react-bootstrap');
     var PageHeader = ReactBootstrap.PageHeader;

Its very annoying.. Is it a bug or is it my mistake? (I really want to use this feature)

Thank you.

My .eslintrc is this: 

    {
          // http://eslint.org/docs/rules/

          "ecmaFeatures": {
            "arrowFunctions": true,
            "blockBindings": true,
            "blockBindings": true,                     // enable let and const (aka block bindings)
            "defaultParams": true,                     // enable default function parameters
            "generators": true,                        // enable generators
            "objectLiteralComputedProperties": true,   // enable computed object literal property names
            "objectLiteralDuplicateProperties": true,  // enable duplicate object literal properties in strict mode
            "objectLiteralShorthandMethods": true,     // enable object literal shorthand methods
            "objectLiteralShorthandProperties": true,  // enable object literal shorthand properties
            "jsx": true                                // enable JSX
          },

          "env": {
            "browser": true,     // browser global variables.
            "node": true,        // Node.js global variables and Node.js-specific rules.
            "mocha": true,       // adds all of the Mocha testing global variables.
          },

          "plugins": [
             "react"
          ],

          "rules": {
            ////////// Possible Errors ////////////    "no-callback-return": 2,

            

            ////////// Best Practices //////////

            "curly": 2,                 // specify curly brace conventions for all control statements

            ////////// Variables //////////

       
            "no-undef": 2,                    // disallow use of undeclared variables unless mentioned in a /*global 

           
            ////////// Stylistic Issues //////////

          
            "new-cap": [1, { "capIsNew": false }],                   // require a capital letter for constructors
          
            "quotes": [2, "single", "avoid-escape"],                    // specify whether double or single quotes should be used
          
            ////////// ECMAScript 6 //////////

            "no-var": 0,          // require let or const instead of var (off by default)
            "generator-star": 0,  // enforce the position of the * in generator functions (off by default)

            //////////  JSX  ///////////

            "react/display-name": 1,
            "react/jsx-boolean-value": 1,
            "react/jsx-no-undef": 1,
            "react/jsx-quotes": 1,
            "react/jsx-sort-prop-types": 1,
            "react/jsx-sort-props": 0,
            "react/jsx-uses-react": 1,
            "react/jsx-uses-vars": 1,
            "react/no-did-mount-set-state": 1,
            "react/no-did-update-set-state": 1,
            "react/no-multi-comp": 1,
            "react/no-unknown-property": 1,
            "react/prop-types": 1,
            "react/react-in-jsx-scope": 1,
            "react/self-closing-comp": 1,
            "react/sort-comp": 1,
            "react/wrap-multilines": 1

          }
        }

**Comment by hzoo** [comment]
I think you are trying to use imports or destructuring?

`var {PageHeader} = require('react-bootstrap');`

add `"destructuring": true` to your `.eslintrc` in ecmaFeatures

**Comment by SudoPlz** [comment]
Thank you, that did it...!!!
