### ISSUE TITLE
Relax regex for checking fall through comment

### ISSUE THREAD

**Issue by moll** [eslint/eslint#2811]
Hey,

It'd be a little more convenient for us pedantics if the fall through regex were a little more relaxed. To support capitalization and imperative speech.

I propose:
https://github.com/eslint/eslint/blob/master/lib/rules/no-fallthrough.js:
```javascript
var FALLTHROUGH_COMMENT = /falls?\sthrough/i;
```

**Comment by nzakas** [comment]
Can you explain more? What code are you trying to lint and what is the problem you're seeing?

**Comment by moll** [comment]
Code with a comment, written as said above, with capitalization and imperative speech. :)
```
// Fall through.
```

**Comment by nzakas** [comment]
I'm sorry, I'm still not completely clear on the change your requesting. Are you just wanting to make the check case-insensitive?

FYI, it would be really helpful if you could follow our guidelines for filing new issues: http://eslint.org/docs/developer-guide/contributing#filing-issues. This helps prevent a lot of back-and-forth.

**Comment by moll** [comment]
The one-liner above there is actually the patch to copy and paste. Sorry if didn't make that too clear. I just didn't go through the whole PR saga as I find it's too heavyweight for a one-line change. :-)

The regexp proposal adds case-insensitivity _and_ makes the "s" optional. Hope that makes it clear.

**Comment by nzakas** [comment]
Ah, I see. Makes sense. As I mentioned, it's really helpful to get as much info as possible up front. We aren't going to copy-paste in a suggestion without understanding the problem it solves and what code will properly test the change.

**Comment by greg5green** [comment]
I'm taking a look at this tonight and will should have a PR up pretty soon.

**Comment by moll** [comment]
Thanks!
