### ISSUE TITLE
Automatically find eslintignore

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/eslint#2824]
Currently:

```
 eslint --ignore-path /Users/OliverJAsh/Development/frontend/static/src/.eslintignore static/src/**/*.js
```

Desired:

```
 eslint --ignore-path static/src/**/*.js
```

Where ESLint will automatically traverse the file tree and spot my `.eslintignore`.

**Comment by nzakas** [comment]
I'm sorry, this is beyond how ignore files are supposed to with in ESLint. If suggest using a bash command to do the search and pass that in as --ignore-path.
