### ISSUE TITLE
handle regexp for variable names

### ISSUE THREAD

**Issue by mlarcher** [eslint/eslint#2829]
Right now we have a Require Camelcase rule  that makes sur variable/property names are camel case.
Would it be possible to provide a regex to match those names against ?

**Comment by gyandeeps** [comment]
I am not sure I understand what you are asking for here?
Can you explain more by providing an example and laying down what do you expect to happen.

**Comment by mlarcher** [comment]
I'm thinking of something I saw in scss-lint and found to be quite handy.
Imagine that instead of having 
```
camelcase: 1
```
we had
```
namesMatch: [a-z]+([A-Z]+[a-z]+)*(_allowedSuffix)*
```

**Comment by ilyavolodin** [comment]
That would be a completely different rule at that point? Because who is stopping you from giving it the following regEx
```json
camelcase: [1, /[a-z_]+/]
```
at that point the rule doesn't have anything to do with camel case anymore.

**Comment by mlarcher** [comment]
Indeed, it would need to be a new rule that has the same kind of responsability, but is broader.
Something like `namesMatch: camelCase` or `namesMatch: /[a-z_]+/`

**Comment by nzakas** [comment]
What would this apply to? All identifiers? Property names?

**Comment by mlarcher** [comment]
I'm thinking all identifiers, as is the case for camelCase, but if there is a way to have some flexibility on that too it could be nice.

**Comment by nzakas** [comment]
@mlarcher sounds like an interesting idea, would you be willing to prototype what you want?

**Comment by mlarcher** [comment]
@nzakas It sounds interesting, but I'm not sure I can gather enough time to dive into it. 
I'll make a PR if I can.

**Comment by mlarcher** [comment]
Just so you know, I'm working on the PR. I have the core feature working, I'm now working on unit tests.

**Comment by mlarcher** [comment]
I have submitter a PR for the regexp-match rule. @nzakas please let me know if something needs fixing.
