### ISSUE TITLE
Extending upon options.js

### ISSUE THREAD

**Issue by rizowski** [eslint/eslint#2831]
Hello,

**Problem:**
options.js does not allow for adding additional command line options.

**Proposal:**
I was wondering if you guys would be up to making options.js a little more modular. Reason I ask is because currently for my project ([ESLint-Watch](https://www.npmjs.com/package/eslint-watch)) I haven't been able to figure out a better way to pull in your options object to add my own command line arguments other than copying what you guys have and pasting it into my project. This creates a lot of upkeep on my end.

**Why:**
If you look [here](https://github.com/rizowski/eslint-watch/blob/master/src/options.js#L108-L112) you can see I copied the options object directly from eslint. ESLint-Watch is only a wrapper of ESLint. I would like the ability to keep the ESLint commands the same and just add my commands on top of that list.

**Proposed Solution:**
The way I would do this is by exporting the `{ prepend: '', options:[]}` object that is passed into optionator, so that way I can have access to it.

Overall the code shouldn't change except via references if that. I am just requesting to make options.js a little more modular.

**Comment by nzakas** [comment]
Hmm, this was really not designed to be accessed outside of ESLint, and I'm not sure it's a good idea to do so. 

If you're just adding more options, why not just look for the `-h` flag and output your options then run `eslint -h` and output the result?

**Comment by rizowski** [comment]
I am not really worried about printing the commands. Although I do kind of have what you are describing in place. My [ArgParser](https://github.com/rizowski/eslint-watch/blob/master/src/arg-parser.js) is for pulling out ESLint-Watch commands before passing them to ESLint. 

`esw -ext .js -w --no-ignore`

The problem that I am presented with is like something above. If the command strings are passed into optionator and if I have not defined them, it will throw and try to suggest an option it thought you meant to type. The only option I have added that is different than ESLint is my watch command (-w).

Does that make sense as to what my problem is?

**Comment by rizowski** [comment]
If it was split out, I could pull the options from eslint, update them with what I want (ex. I have new formatters so I set the default to the ones I have created. Then add the watch option) and then let ESLint handle everything from there.

**Comment by nzakas** [comment]
I understand. My problem is that the architecture is setup specifically so that CLI details are not exposed, as we don't want people manipulating those details. Options are also very implementation dependent, which means we would be stuck with our current option parser or else need to keep the same format exported all the time even after we change. I don't see that as a viable path.

I think the best I can offer is to export the option names as an array on CLIEngine. At least with that, you should be able to filter whatever you have coming in based on that list. Thoughts on that?

Aside: you shouldn't be using /lib/cli in your project, that interface is deprecated for public use. CLIEngine is the official way of interacting.

**Comment by rizowski** [comment]
Fair point. I don't think having the option names coming from the CLIEngine will give me enough. Would this just be the options the ESLint supports or the ones that have been entered?

I will convert it over to CLIEngine, is `/lib/cli` going away?

**Comment by nzakas** [comment]
I'm thinking just the options we actually handle. I don't have a really clean solution, as this isn't a use case I designed for. I might be missing something, but why not execute ESLint as a binary from Node? You could strip out the options you care about and pass the rest through.

lib/cli is not intended for use outside of the project. CLIEngine is the thing designed for external use. lib/cli may change, go away, etc., as we need going forward.

**Comment by rizowski** [comment]
I do currently take in the args and parse them out to pass them to ESLint later. I was only using lib/cli so I could pass along the parsed arg string array.  So...

1. input comes in 
  - `esw -ext .js -w`
2. ESLint-Watch/cli takes in input and takes out `-w`, tacks on default path and new formatter 
  - `esw ./ -ext .js -f simple-detail`
3. The new args to go to ESLint lib/cli as a string array 
  - `['./', '-ext','.js', '-f', 'simple-detail']`
4. ESLint parses and executes from lib/cli
5. ESLint-Watch starts watching file directory after initial lint is ran.

I believe the last time I looked the CLIEngine wouldn't take parameters how I was needing them to. So having the options for opinionator accessible I could easily change the default formatter and adding my own command.

If the CLIEngine could return the options list from opinionator that would be great, but the names of the commands wouldn't help too much from what I can tell. What was your thinking for using the names?

**Comment by nzakas** [comment]
What I'm suggesting is that you run ESLint as an executable rather than accessing the API. So strip off whatever params you're interested in then use child_process or some such thing to execute .bin/ESLint.

I'm sorry, I don't see exposing the actual optionator configuration as a viable option here.

**Comment by rizowski** [comment]
Alright. Thanks for your consideration on the matter.
