### ISSUE TITLE
Specify ES3-only env?

### ISSUE THREAD

**Issue by pdehaan** [eslint/eslint#2835]
Currently in one of our projects, we have `//jshint es3: true, es5: false, esnext: false`.
We're switching from JSHint to ESLint (yay!) but I think that the `es3:true` and `//jshint validthis: true` are the remaining two things we're stumped on.

Is it possible to set `es3:true` for an ESLint `env`?

**Comment by hzoo** [comment]
Don't think so at the moment - http://eslint.org/docs/user-guide/configuring#specifying-environments

> An environment defines both global variables that are predefined as well as which rules should be on or off by default.

I guess a request could be for an env for es3 that sets all relevant rules to account for es3 (like `"dot-notation": [2, {"allowKeywords": false}],`)?

For now you should just check the rules you are using and see if there are options for es3?

**Comment by nzakas** [comment]
We don't have an option for ES3 only mode, as there just aren't enough use cases remaining for this. The only tangible differences between ES3 and ES5 are:

1. ES5 can use keywords as properties, ES3 cannot.
1. The getter/setter syntax for object literals

We do have affordances for the first item through dot-notation and no-reserved-keys/quote-props.

The second one we don't have, but would be really simple to create a rule for. I'm not sure there's enough demand to make it a core rule, but you could certainly make it a custom rule.

@hzoo in 1.0, environments will no longer turn on rules, so we aren't adding any more environments that do that.

**Comment by hzoo** [comment]
Oh ok - is there an issue to change the docs to reflect that? - `as well as which rules should be on or off by default.`

And I guess its only es6 that does something special by turning on emcafeatures?

**Comment by nzakas** [comment]
The tracking issue is https://github.com/eslint/eslint/issues/2100

ES6 and Node change ecmaFeatures

**Comment by gyandeeps** [comment]
based on the above convo I  think this can be closed.
if anyone feels otherwise, feel free to reopen.
