### ISSUE TITLE
Command line parser, ecmaFeatures, and plugins options do not get merged

### ISSUE THREAD

**Issue by cecchi** [eslint/eslint#2844]
Currently a config gets partially ignored when using the command line API (I ran into this using grunt-eslint but I assume it is the same using the command line directly). The `parser`, `ecmaFeatures`, and `plugins` configuration options do not get merged into the final config.

For example:
```
{
    'parser' : 'babel-eslint',
    'envs'   : [
        'browser',
        'es6'
    ],
    'plugins' : [
        'react'
    ],
    'ecmaFeatures' : {
        'modules' : true,
        'jsx'     : true
    }
}
```

The "envs" will survive, but the rest will be overridden.

**Comment by nzakas** [comment]
I'm not quite sure what you're describing. It would be helpful if you could rephrase as:

1. What you did
2. What happened
3. What you expected to happen

**Comment by cecchi** [comment]
My mistake -- I expected the `CLIEngine` constructor to receive an object of the same format as the configuration (i.e. support all of the configuration options). Looking at the documentation again, that is not the case.
