### ISSUE TITLE
"env" vs "envs"

### ISSUE THREAD

**Issue by cecchi** [eslint/eslint#2846]
See: https://github.com/sindresorhus/grunt-eslint/issues/71

In short, when using the CLIEngine API you must use `envs` instead of `env`. You also must use an array in place of an object literal. We should consider accepting both formats (same goes for `globals` vs `global`, I believe).

**Comment by nzakas** [comment]
This is intentional. You cannot turn off environments via the command line, you can only turn them on. Accepting an object would give a false impression that it's possible to toggle environments off on the command line.

This is consistent with the options for rules and globals as well.
