### ISSUE TITLE
Feature: no-else-return in each, forEach and etc

### ISSUE THREAD

**Issue by evilebottnawi** [eslint/eslint#2850]
If i return false in each, forEach and etc - cycle stopping, you need not be returned true

**Comment by lo1tuma** [comment]
I don’t understand what you are requesting. Can you give a more detailed explanation with example code? Please also take a moment to read our [contributing guidelines](http://eslint.org/docs/developer-guide/contributing.html) especially the part about [new rules](http://eslint.org/docs/developer-guide/contributing.html#new-rules).

**Comment by evilebottnawi** [comment]
@lo1tuma sorry my mistake
