### ISSUE TITLE
Automate documentation creation

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2860]
I would like to streamline documentation create a bit. Now that we have schemas, I would like to create a built task that would export schemas and append available options at the end of each rule documentation.I also think we can take it even further, in order to help people search google for errors they get as a result of linting, I think we should include all possible error messages into exportable object that would also be appended to rule documentation. We also can remove "README.md" all together, and generated it from exported object. I will create a WIP pull request with proposed changes for a few rules.
##

**Comment by lo1tuma** [comment]
Some error messages are created dynamically, so I don't think it is possible to automatically document every possible error message.

**Comment by ilyavolodin** [comment]
Most of the error messages are created by substitution, that's why I used `{0}` in my example. If the messages is completely generated (I think there might be one or two rules that do that), then oh well... It's better to have most of the messages then none.

**Comment by nzakas** [comment]
I think this might end up being a bit too pie-in-the-sky, but feel free to explore. :)

**Comment by IanVS** [comment]
> append available options at the end of each rule documentation.

It seems to me like option documentation is important enough that it should be fairly early in the rule docs.  Imagine needing to scroll to the very bottom of [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing) to find the options.

**Comment by ilyavolodin** [comment]
Agree. But without knowing how the document is structured, it's hard to insert auto-created pieces in the middle.

**Comment by IanVS** [comment]
Could we manually put a placeholder in all the rule docs?  Perhaps stub out the header "### Rule Options" or similar?

**Comment by mysticatea** [comment]
Or I think to generate TOC automatically is good for large rules.

**Comment by IanVS** [comment]
I agree, looks like it was discussed in https://github.com/eslint/eslint/issues/1073, but I don't see it live on the site.

**Comment by ilyavolodin** [comment]
It is live. Or at least anchors on all headers are. If you mouse over any header, you should see a link icon pop up.

**Comment by IanVS** [comment]
You're right, I wasn't clear.  The anchors are there, but there are no TOC.

**Comment by nzakas** [comment]
I don't think there are enough sections on rule docs to have a TOC... Most have three, four sections at most. I'm not a big fan of boilerplate like that.

**Comment by IanVS** [comment]
This is getting off topic, but how about some of the larger pages like [Configuring ESLint](http://eslint.org/docs/user-guide/configuring)?

**Comment by nzakas** [comment]
I think the larger pages should be broken up into smaller ones

**Comment by kaicataldo** [comment]
Is this still being worked on?

**Comment by ilyavolodin** [comment]
Second part is done (Index.md). The rest of it is controversial enough to hold off for now.
