### ISSUE TITLE
Missing parent property for nodes retrieved by getNodeByRangeIndex

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#2863]
AST nodes retrieved by `getNodeByRangeIndex` don’t have a `parent` property to access the parent node.

In my use-case I want to access the parent node of an identifier node from an escope reference.

**Comment by nzakas** [comment]
That's a known limitation. The parent property is added during traversal - if you skip ahead, it hasn't been set yet. Same way getAncestors doesn't work outside of the traversal.

Not sure there's a good solution to this.

**Comment by mysticatea** [comment]
Maybe, at `"*:exit"` (e.g. `"FunctionDeclaration:exit": function(node) { ...`), children of its node have `.parent` property.

**Comment by lo1tuma** [comment]
@mysticatea I'm not sure how this could solve my problem. Escope references can appear in almost **any** child node starting from the node where the variable was declared.

@nzakas In `getNodeByRangeIndex` we are doing an extra traversal, wouldn't it make sense to apply the same logic there by attaching the parent node and leading and trailing comments? Another approach would be to create something similar as the `TokenStore` for AST nodes and store the nodes (indexed by range index) during the first traversal, so we could avoid the extra traversal in `getNodeByRangeIndex` completely.

**Comment by btmills** [comment]
@lo1tuma is it just the parent node that you need? If so, untested, but:

```diff
diff --git a/lib/eslint.js b/lib/eslint.js
index 28f6d03..3487995 100755
--- a/lib/eslint.js
+++ b/lib/eslint.js
@@ -940,9 +940,9 @@ module.exports = (function() {
         var result = null;

         estraverse.traverse(controller.root, {
-            enter: function (node) {
+            enter: function (node, parent) {
                 if (node.range[0] <= index && index < node.range[1]) {
-                    result = node;
+                    result = assign({ parent: parent }, node);
                 } else {
                     this.skip();
                 }
```

**Comment by nzakas** [comment]
Seems like that should work.

**Comment by lo1tuma** [comment]
@btmills Yes, that would work for me.

**Comment by btmills** [comment]
I'll do a PR with tests for that tonight.
