### ISSUE TITLE
"yoda" should ignore comparisons where both sides are constant

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2867]
With this code:

```js
console.log(1 < 2)
```

And this rule:

```json
{
  "yoda": [2, "never"]
}
```

I get this error:

```
t.js:1:12: Expected literal to be on the right side of <.
```

I think the solution to this is for the `yoda` rule to ignore situations where both sides of a comparison are constant. `yoda` is supposed to check for situations where a literal value of a condition is first and a variable comes second, not when both sides are constants.

**Comment by michaelficarra** [comment]
Why would we make a special exception for a case that should never exist in your code anyway? Why are you writing things like this?

**Comment by feross** [comment]
You should make a special case because the rule is behaving differently than the documentation. If you want to make a separate rule `no-constant-expressions` that prevents `1 < 2` as well as non-comparison constant expressions like `1 + 2`, then go for it. But it shouldn't be part of `yoda`.

**Comment by michaelficarra** [comment]
Not if we define yoda as "a comparison with a literal must always have a literal on the left".

**Comment by feross** [comment]
Too bad that's not how the documentation defines it:

> Yoda conditions are so named because the literal value of the condition comes first while the variable comes second

**Comment by michaelficarra** [comment]
Then maybe the proper solution is to correct the documentation. My definition would still follow the spirit of the initial rule proposal.

**Comment by feross** [comment]
Nice try, but that's not a real solution. If someone writes `1 < 2`, they're not expecting to get the message:

```
Expected literal to be on the right side of <
```

This message is just wrong – there is a literal on the right side of `2` in this code.

`yoda` is the wrong rule for preventing the use of constant comparisons. It should be removed from `yoda` and if people miss the old behavior we can add a new rule like `collapse-constant-expressions` that forces `1 < 2` to be written as `false`, and `1 + 2` to be written as `3`.

**Comment by nzakas** [comment]
Agree with @feross , we should just skip expressions like this in the Yoda rule.

**Comment by dcousens** [comment]
Thanks @nzakas and @feross for this.

**Comment by feross** [comment]
Don't forget @cjihrig who sent the PR that fixed the issue! :+1:

**Comment by rstacruz** [comment]
just want to say it's an interesting debate between @feross and @michaelficarra here, props on you guys for keeping things civil and the arguments logical :)

**Comment by dcousens** [comment]
@michaelficarra
 
> My definition would still follow the spirit of the initial rule proposal.

I'd argue that was a mistake in the initial proposal then,  yoda conditions IMHO almost always referred to a non-constant expression,  where the risk was mistaken assignment.
