### ISSUE TITLE
Add env preset for ember & qunit

### ISSUE THREAD

**Issue by ismay** [eslint/eslint#2870]
I'm using ember-cli-eslint in an ember application. Ember uses qunit for testing (and has some ember specific globals). This requires me to add a lot of globals to my `.eslintrc`.

It would be great if an `env` preset could be added for qunit (and/or ember), to make using eslint in this setting a little easier.

**Comment by gyandeeps** [comment]
Yes, i think we can add `qunit`. As we depend on https://github.com/sindresorhus/globals module for globals.

**Comment by ismay** [comment]
Cool, and if the `Ember.Test0` methods are added to https://github.com/sindresorhus/globals, I assume they can be added as well?

**Comment by ilyavolodin** [comment]
We still need to do a code change once it's added to globals package. We don't take everything from globals. It's a minor change, though.

**Comment by nzakas** [comment]
I'll add qunit.
