### ISSUE TITLE
Config Autocreation

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#2875]
There was some good discussion in the [2.0.0 wish list issue](https://github.com/eslint/eslint/issues/2203) about generating a config file which most closely matches an existing codebase.  Now that validation has landed in [0.23.0](http://eslint.org/blog/2015/06/eslint-0.23.0-released/#configuration-validation), is this more achievable?  I would be willing to take a crack at something (maybe at least a separate project as a prototype/investigation) if nobody else has started or has time.  I think it would be a really useful thing to have, and would ease the introduction of ESLint for existing projects.

**Comment by nzakas** [comment]
Nothing on the 2.0.0 wish list is ready to be worked on right now. There are a lot of breaking changes in 1.0.0 that need to be in place before we can even consider moving forward with anything on the wish list. I'd much rather have your help on 1.0.0 tasks. :)

Closing, as we aren't going to track wish list items individually.
