### ISSUE TITLE
Bug: computed-property-spacing with ES6 rest operator

### ISSUE THREAD

**Issue by zallek** [eslint/eslint#2889]
`let { center, ...otherProps } = this.props;`
fires the error `There should be no space before '}'  computed-property-spacing`

setup:
`"computed-property-spacing":  [2, "never"],`

eslint version: 0.24.0

**Comment by lo1tuma** [comment]
The rest operator works only for array destructuring. The [object rest operator](https://github.com/sebmarkbage/ecmascript-rest-spread) is a proposal for ES7 which is not supported by ESLint.

**Comment by zallek** [comment]
Ok Thx. Though, sad to know as we use it all over our production code :( and this feature might have been useful.
