### ISSUE TITLE
`lines-around-comment` causes crash with some constructs

### ISSUE THREAD

**Issue by mathieumg** [eslint/eslint#2892]
In the `lines-around-comment` rule, the following will make ESLint crash:

```js
var a,
// line
b;
```

using

```js
{
  "allowBlockStart": true,
  "beforeLineComment": true
}
```

or

```js
{
  "allowBlockStart": true,
  "beforeLineComment": true
}
```

**Comment by gyandeeps** [comment]
Can you share the eslint version and the actual output of eslint.
So that we all can understand what is going wrong.

**Comment by mathieumg** [comment]
See #2893, I added tests that would crash under the current version. I didn't mention the ESLint version because `allowBlockStart` and `allowBlockEnd` are new from 0.24, but yeah, I'm on 0.24.
