### ISSUE TITLE
no-implied-eval doesn't work on template strings or with concatinated strings

### ISSUE THREAD

**Issue by bgw** [eslint/eslint#2898]
For example, `no-implied-eval` could catch:

```js
setInterval(`helper(${foo}, ${bar})`, 50);
// or
setInterval("helper(" + foo + ", " + bar + ")", 50);
```

The first case is easy, as it just needs to check for a TemplateLiteral. The second part is probably a bit more controversial, but basically any concatenation with a literal string implies a string result.

I'm willing to fix this if people want it. (I already have a patch ready)

**Comment by nzakas** [comment]
Sounds like a bug , happy to accept a PR. Please take a moment to read over our contribution guidelines: http://eslint.org/docs/developer-guide/contributing
