### ISSUE TITLE
Custom Environments

### ISSUE THREAD

**Issue by malandrew** [eslint/eslint#2899]
Upon investigating the [default options](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L71) when calling eslint programmatically, it doesn't look like there is support for defining custom environments. 

This would be a nice feature if you want to define your own environments optimized for different conditions, like `/*eslint-env perf*/` or `/*eslint-env readability*/`, on a file per file basis.

**Comment by ilyavolodin** [comment]
We do not currently have support for custom environments at all. It has been discussed multiple time, and a few implementation were tested, but it always turns out to be harder then it looks.

**Comment by nzakas** [comment]
In 1.0.0, environments will no longer toggle rules, so environments can only be used to define globals. I'm guessing what you want is handled better by shareable configs.

**Comment by gyandeeps** [comment]
@malandrew did you get your question answered?

**Comment by nzakas** [comment]
We aren't planning on doing custom environments, so closing.
