### ISSUE TITLE
Missing rules in v24

### ISSUE THREAD

**Issue by benoneal** [eslint/eslint#2900]
```Definition for rule 'array-bracket-spacing' was not found.```
```Definition for rule 'arrays-bracket-spacing' was not found. // docs say both with and without 's'``` 
```Definition for rule 'constructor-super' was not found.```
```Definition for rule 'no-this-before-super' was not found.```

**Comment by btmills** [comment]
The typo in the `array-bracket-spacing` docs was fixed in #2888. Can you run `eslint -v` and paste the output here?

**Comment by benoneal** [comment]
```
$ eslint -v
v0.24.0
```
Regardless of whether the docs had a typo or not, the error throws with either spelling.

**Comment by btmills** [comment]
Thanks. From a terminal session, can you paste the exact command you're using to invoke ESLint along with the output it generates?

**Comment by xjamundx** [comment]
Possibly related. I've been moving, so my brain is a bit spacy at the moemnt.

` eslint --rule '{"object-curly-spacing": [2, "always"]}'  test.js`

```
/usr/local/lib/node_modules/eslint/lib/eslint.js:646
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'Object-curly-spacing' was not found.
```

```
eslint --version
v0.24.0
```

**Comment by benoneal** [comment]
The docs still use "arrays-bracket-spacing" http://eslint.org/docs/rules/array-bracket-spacing.html in the example in the options section. 

Here's my terminal output: 
```
$ gulp lint
[13:21:43] Using gulpfile ~/Code/hui/gulpfile.js
[13:21:43] Starting 'lint'...
/Users/ben.oneal/Code/hui/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:650
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'array-bracket-spacing' was not found.
```
and here's the line I'm using in my ```.eslintrc``` file: 
```
"array-bracket-spacing": [1, "never"],
```

**Comment by btmills** [comment]
Aha! From the line ending `node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:650`, it looks like gulp-eslint is using its own version of eslint, which appears to be v0.23.0, before the new rules were released. gulp-eslint as of 0.15.0 uses eslint `^0.24.0`, so try upgrading gulp-eslint?

**Comment by benoneal** [comment]
Ah ok. I updated that and it appears to work now. Thanks.
