### ISSUE TITLE
`no-multi-spaces` exception type for ES6 import...from?

### ISSUE THREAD

**Issue by sebastienbarre** [eslint/eslint#2901]
I was wondering if there is a documented exception type that can be used in `no-multi-spaces` for ES6 `import...from` declarations. 

More specifically, I would like to allow this:
```
import ColorsPage    from './pages/ColorsPage.react.js';
import DataTablePage from './pages/DataTablePage.react.js';
import FluxPage      from './pages/FluxPage.react.js';
```
but right now I'm getting, unsurprisingly:
```
error  Multiple spaces found before 'from'  no-multi-spaces
```

Thanks

**Comment by mathieumg** [comment]
What if you try with:

```js
no-multi-spaces: [2, { exceptions: { "ImportDeclaration": true } }]
```

**Comment by sebastienbarre** [comment]
Well that was easy, many thanks! 
Out of curiosity, where did you find it? I googled to find a comprehensive list, to no avail.

**Comment by mathieumg** [comment]
Honestly, that was a shot in the dark. :stuck_out_tongue_closed_eyes: 

I just fixed a bug related to `import`/`export` statements here yesterday, so I knew the expression name. I had to look a bit, but https://github.com/eslint/espree/blob/master/lib/ast-node-types.js seems like a good start.

**Comment by MaffooBristol** [comment]
Great stuff.

Documented here: http://eslint.org/docs/rules/no-multi-spaces

I'm personally a fan of the rather lax `"no-multi-spaces": [2, {exceptions: {"ImportDeclaration": true, "VariableDeclarator": true, "Property": true}}]`
