### ISSUE TITLE
"object-curly-spacing" options don't appear to do anything

### ISSUE THREAD

**Issue by benoneal** [eslint/eslint#2902]
Using v0.24 with this rule in my .eslintrc file
```
"object-curly-spacing": [1, "always", {
      "objectsInObjects": false,
      "arraysInObjects": false
}]
```
And getting this error: 
```warning  A space is required before '}'  object-curly-spacing```
Regardless of whether or not the options are set to ```true``` or ```false```

**Comment by ilyavolodin** [comment]
This is working as intended (at least without seeing your code). You set the first option to "always" that means always require space around curly braces. The other options just add exceptions to when you have nested object or an array inside an object.

**Comment by benoneal** [comment]
Sorry, it's not working as I expect. Here's the code it complains about: 
```
        { series: [
          { date: 1, calculatedValue: 4 },
          { date: 2, calculatedValue: 6 },
          { date: 3, calculatedValue: 11 },
          { date: 4, calculatedValue: 2 },
          { date: 5, calculatedValue: 4 },
          { date: 6, calculatedValue: 23 }
        ]} // this is the line it complains about, regardless if options are set to 'true' or 'false'
```

**Comment by benoneal** [comment]
The problem was that I was using gulp-eslint, which used v23 of eslint. Updating to the latest version of gulp-eslint fixed this issue.
