### ISSUE TITLE
Forgive `used before it was defined` for functions.

### ISSUE THREAD

**Issue by bucaran** [eslint/eslint#2909]
I don't rely on `var` hosting anymore, but I do kind of like declaring functions after I use them sometimes, specially small functions inside other functions, yet I still get this lint error, is there an option to disable this?

Thanks.

**Comment by btmills** [comment]
Sounds like you want the [`"nofunc"` option](http://eslint.org/docs/rules/no-use-before-define)?

**Comment by bucaran** [comment]
Awesome!
