### ISSUE TITLE
rule no-with not reporting error.

### ISSUE THREAD

**Issue by snlacks** [eslint/eslint#2925]
Testing with eslint in a fork of [credential](https://github.com/snlacks/credential/tree/IssueID%2327-QA-Improvements) (here's the [master](https://github.com/ericelliott/credential/))

There's a with statement in one [file](https://github.com/ericelliott/credential/blob/master/constantTimeCompare.js) but it's not showing the error when I run the test. Thanks!

**Comment by michaelficarra** [comment]
Cannot reproduce. You must be running/configuring eslint incorrectly.

**Comment by snlacks** [comment]
Thanks for taking a look.

**Comment by ilyavolodin** [comment]
@snlacks Can you try running eslint in debug mode: `DEBUG=eslint:* eslint` it sounds like your config file is not being picked up for some reason. Can you post output of debug mode here?

**Comment by snlacks** [comment]
Sure, the debug file is getting picked for some other setting changes I've set.


    eslint:cli Running on files +0ms
    eslint:cli-engine Processing credential.js +6ms
    eslint:cli-engine Linting credential.js +2ms
    eslint:config Constructing config for C:\Users\Steven\repos\credential\credential.js +1ms
    eslint:config Using .eslintrc and package.json files +0ms
    eslint:config Loading C:\Users\Steven\repos\credential\.eslintrc +2ms
    eslint:config Using C:\Users\Steven\repos\credential\.eslintrc +74ms
    eslint:config Loading C:\Users\Steven\repos\credential\package.json +0ms
    eslint:config Merging command line environment settings +15ms
    eslint:cli-engine Processing test\credential-test.js +831ms
    eslint:cli-engine Linting test\credential-test.js +2ms
    eslint:config Constructing config for C:\Users\Steven\repos\credential\test\credential-test.js +0ms
    eslint:config Using .eslintrc and package.json files +2ms
    eslint:config Loading C:\Users\Steven\repos\credential\.eslintrc +1ms
    eslint:config Using C:\Users\Steven\repos\credential\.eslintrc +8ms
    eslint:config Loading C:\Users\Steven\repos\credential\package.json +1ms
    eslint:config Merging command line environment settings +4ms
...

        "no-with": [2],

...

Thank you for all of your help.

**Comment by gyandeeps** [comment]
What kind of parser are you using?

**Comment by nzakas** [comment]
Do you have a `.eslintrc` file in a parent directory?

**Comment by snlacks** [comment]
Parser

    "parser": "babel-eslint",

Parent directory:
No, only siblings.

**Comment by ilyavolodin** [comment]
Can you try it with default parser and see if the same issue occurs? It might be related to `babel-eslint`

**Comment by snlacks** [comment]
It was my error. There's nothing wrong with the option or eslint, it's an embarrassingly stupid mistake. Thanks for the help, I hope I didn't waste too much of anyone's time. Very sorry. Thanks.

(I owe you what the mistake was, despite the embarassment: Testing the wrong file, that I purposely changed earlier when I was using jshint and getting rid of the with-statement was outside of the scope of the issue.)
