### ISSUE TITLE
no-unused-vars with spread operator

### ISSUE THREAD

**Issue by JohnyDays** [eslint/eslint#2929]
```javascript
function nonsenseExample (values) {
  return {...values}
}
```
The above example triggers a lint error: ```values is defined but never used```
My code is more complex, but this is the minimal reproducible example for the error.
I am using babel, here is the converted code
``` javascript
function nonsenseExample(values) {
  return _extends({}, values);
}
```
Awesome tool! It's really saving me time and frustration.

**Comment by lo1tuma** [comment]
The [object spread operator](https://github.com/sebmarkbage/ecmascript-rest-spread) is an experimental ES7 feature which is not supported by ESLint. Please file an issue for babel-eslint.

**Comment by JohnyDays** [comment]
Still, in the compiled code there is no spread operator. Doesn't eslint operate on the compiled code?

**Comment by btmills** [comment]
babel-eslint is parser plugin, so it returns an AST. I've no idea if it guarantees that the AST will match what Babel would output, but I doubt it. Either way, you'll need to file an issue there.

**Comment by JohnyDays** [comment]
I will, thanks!
