### ISSUE TITLE
How to force spacing between function name and parens?

### ISSUE THREAD

**Issue by geuis** [eslint/eslint#2933]
I have `"space-before-function-paren": [2, "always"]` set.

Notice in the following example the line `return $resource(endpoint, {}, {`

eslint is enforcing the space in `return function (endpoint, data)`, but not in `return $resource()`. 

Is there another property that addresses this?

    app.service('testApiService', ['$resource',
      function ($resource) {
        return function (endpoint, data) {
          return $resource(endpoint, {}, {
            get: {
              method: 'GET',
              transformRequest: [],
              transformResponse: function (response, headers, statusCode) {
                return response;
              }
            }
          });
        });
      };
    ]);

**Comment by lo1tuma** [comment]
`space-before-function-paren` works only for function declarations or function expressions, not for function calls.
I guess you want something linke [`no-spaced-func`](http://eslint.org/docs/rules/no-spaced-func), but to enforce to opposite, always having a space befor the opening paren of a function call. Is this correct?

**Comment by xjamundx** [comment]
You're looking for something like this?

```js
alert ('hi');
console.log ('message')
```

**Comment by geuis** [comment]
Ok, I'm just having a dumb moment. Thanks @xjamundx. You're right, that's not what I want. Been linting dozens of files today and for some reason that particular combo of function declarations and calls looked weird.

**Comment by xjamundx** [comment]
No problem @geuis  :)
