### ISSUE TITLE
Option to ignore max-len based on a regexp

### ISSUE THREAD

**Issue by bgw** [eslint/eslint#2934]
There's outstanding suggestions to make exceptions for comments (#2221) and URI comments (#1661), but I personally think a better solution is to allow arbitrary regexps, at the cost of being less robust for those above cases. This would allow other types of exceptions, such as for really long require lines.

If we were to implement this, one issue I see is we currently use `context.toSourceLines()`. Should we restrict regexps to a single line, or should we also allow multiline matches (probably with an associated performance hit)?

I'd be happy to make a PR if accepted.

**Comment by nzakas** [comment]
Can you explain a use case other than URLs and comments?

Keep in mind, URL regexes are long and complicated, so I don't think we can ask people to manually configure that.

**Comment by bgw** [comment]
The reason why we want it at Facebook is because our old linting system had a way to ignore really long require statements. Because we have some long module names, and because we wrap at 80 columns, if you had a long module name, you'd end up with:

```js
// TODO: Implement enterprise fizzbuzz adapter
var FooBarAbstractIntrospectingFactoryConstructorInterfaceDerivative = require('FooBarAbstractIntrospectingFactoryConstructorInterfaceDerivative');
```

I agree URL regexes are difficult. We could take an object as an argument to `max-len`, which could have keys for special cases like comments and URLs:

```yaml
rules:
  # ignore urls and require statements, but not normal (non-URL) comments
  max-len: [2, 80, 4, {urls: true, comments: false, regexp: '^\s*var\s.+=\s*require\s*\('}]
```

**Comment by mathieumg** [comment]
I think @bgw's suggested configuration is very sensible! Flexible (allows for more advanced use cases) and easy to configure for the common scenarios.

**Comment by dozoisch** [comment]
:+1: love that last config option. Especially useful for import/requires!

**Comment by lo1tuma** [comment]
1. I think a regexp would be very error-prone for this rule. Consider the following example:  

    ```js 
    var code = `var foo = "bar";
    var bar = require(
    `;
    ```
2. Why should this be limited to a single pattern?

**Comment by dozoisch** [comment]
To some extent you can have more than one pattern in a regex `/(pattern1)|(pattern2)/` and I mean at some point, these rules are there to help you pick code style issues. I think the current proposed solution cover most uses cases.

**Comment by bgw** [comment]
@Io1tuma, Are you referring to the fact that the match would match multiple lines? That regexp was assuming matches were constrained to a single line, based on our use of context.toSourceLines().

If you're referring to the unclosed parenthesis, that'd be caught by a parse error.

That said, I agree regexps can't match everything. The advantage of using them here is that we could support arbitrary use-cases, rather than constraining ourselves to some short list of special-cases. Plus, if a regexp matches something it shouldn't, only that one line gets ignored, which isn't the end of the world. IMHO, it's better for the linter not to report something than to report things it shouldn't.

Another syntax to consider would be to accept an arbitrary number of additional positional arguments, and use a string prefix to mark regexp rules, eg:

```yaml
rules:
  # ...
  max-len: [2, 80, 4, 'ignore-urls', 'ignore-regexp:^\s*var\s.+=\s*require\s*\(']
```

**Comment by bgw** [comment]
Oh, another problem, I just noticed: If this is YAML or JSON, those regexps actually need to be double-escaped, which really mucks up the syntax. (whoops!)

**Comment by lo1tuma** [comment]
@bgw No, my point is that the regexp would also match the content of string literal (or in my example above a template literal).

**Comment by bgw** [comment]
@Io1tuma, I see. I'll stand by my second point in that case:

> if a regexp matches something it shouldn't, only that one line gets ignored, which isn't the end of the world. IMHO, it's better for the linter not to report something than to report things it shouldn't.

**Comment by nzakas** [comment]
OK, seems reasonable as an addition to the two other opt-outs. Id suggest the following:

```
"max-len": [ 2, 80, 4, {
   ignorePattern: " foo"
}]
```

@bgw would you be willing to submit a PR for this?

**Comment by bgw** [comment]
@nzakas, Sure. I'll start working on it sometime today. Do we want to handle multi-line regexp, or stick to single-line matches only?

**Comment by nzakas** [comment]
I'd start with single line for now.
