### ISSUE TITLE
Enhancement: Allow exceptions to space-after-keywords rule

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#2936]
As mentioned in https://github.com/eslint/eslint/pull/2935, it is not possible to set `space-after-keywords` to `"never"` if also setting `space-before-blocks` to "`always`", because of pesky `else` statements.

```js
// space-after-keywords never requires:
} else{

// space-before-blocks always requires:
} else {
```

Perhaps one way to allow these rules to be used together in this way, is to allow exceptions to the `space-after-keywords` rule like `[2, "never", { "exceptions": ["else"] }]`, similar to the `spaced-comment` rule.

The reason I noticed this is the [Waterline](https://github.com/balderdashy/waterline) project which I am introducing ESLint into, which does not use spaces after keywords but does use spaces before blocks.

**Comment by lo1tuma** [comment]
Duplicate of #1338

**Comment by IanVS** [comment]
Yep, sorry
