### ISSUE TITLE
Rule Proposal: prefer-reflect

### ISSUE THREAD

**Issue by keithamus** [eslint/eslint#2939]
The ES6 Reflect API comes with a handful of methods which somewhat deprecate methods on old constructors:

 - [`Reflect.apply`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.apply) effectively deprecates [`Function.prototype.apply`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-function.prototype.apply) and [`Function.prototype.call`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-function.prototype.call)
 - [`Reflect.deleteProperty`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.deleteproperty) effectively deprecates the [`delete` keyword](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-delete-operator-runtime-semantics-evaluation)
 - [`Reflect.getOwnPropertyDescriptor`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.getownpropertydescriptor) effectively deprecates [`Object.getOwnPropertyDescriptor`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.getownpropertydescriptor)
 - [`Reflect.getPrototypeOf`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.getprototypeof) effectively deprecates [`Object.getPrototypeOf`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.getprototypeof)
 - [`Reflect.setPrototypeOf`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.setprototypeof) effectively deprecates [`Object.setPrototypeOf`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.setprototypeof)
 - [`Reflect.preventExtensions`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-reflect.preventextensions)  effectively deprecates [`Object.preventExtensions`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.preventextensions)

For each of these methods, using Reflect makes semantic sense: (considering other objects, such as Functions or RegExps could be passed to these, going into Object.* to interact with non-Objects is weird). Some, like `Reflect.apply` are more defensive than using `Function.prototype.apply` as a function could easily define its own apply method to do unexpected things.

I propose a rule called `prefer-reflect` which, when it sees one of these "effectively deprecated" methods, encourages the developer to move to the Reflect method. For example:

```js
Array.prototype.slice.call(arrayLike, 0); // eslint: "Reflect.apply" is preferred over "Function.prototype.call"
```

```js
Object.preventExtensions(new RegExp()); // eslint: "Reflect.preventExtensions" is preferred over "Object.preventExtensions"
```

```js
var foo = { bar: 1 };
delete foo.bar; // eslint: "Reflect.deleteProperty" is preferred over "delete" keyword
```

Provided I get the go-ahead I'm, of course, happy to work on a PR implementing this.

**Comment by xjamundx** [comment]
Interesting stuff. I don't think many of us have thought much about `Reflect.

As far as the first example.  I was thinking of another rule to suggest avoiding `apply` in favor of spread.
- `foo(...args)`

Would you agree? This would likely conflict pretty hard with your suggestion here, though maybe that's alright.

**Comment by nzakas** [comment]
I like the suggestion. I agree with @xjamundx regarding apply, I think Reflect is preferred only if `this` is not the same as the object on which the function resides. We can probably do the opposite check for @xjamundx's suggested rule and these two can coexist.

**Comment by ilyavolodin** [comment]
Do we want this to be part of the core package? I will admit, I'm not up to date on ES6, but I read all of the issues that are filed for eslint, and until today, I haven't even heard of `Reflect`. So it might not be all that suitable for general consumption. (Or it might just be my personal level of education:-)

**Comment by keithamus** [comment]
Agree with @xjamundx and @nzakas' points. Love the idea of a prefer-spread rule. I think both can coexist happily. I've updated my example above to better show where `Reflect.apply` would be needed where prefer-spread would not work.

As for @ilyavolodin's concerns about if this should be in core:

 - `Reflect` is part of JS core, and so it seems to fit that eslint would cover all of JS core. 
 - One could argue that if rules based around things that aren't part of the ECMA spec, such as [valid-jsdoc](http://eslint.org/docs/rules/valid-jsdoc) or [no-console](http://eslint.org/docs/rules/no-console) (not part of the spec, just popularly used in browsers and node.js), then certainly there is room for official parts of the spec, such as Reflect.
 - While `Reflect` may not be one of the sexiest features of ES6, it is still important, and as mentioned above could be considered a best practice to use for better defensive code, and more semantically relevant code. I think it would not be ideal to brush away an opportunity to enforce best practices because they aren't well heard of. It could be said that best practices around, say, IIFEs weren't prevalent before JS[HL]int, but it benefitted everyone to settle on a (few) good convention(s).

**Comment by ilyavolodin** [comment]
@keithamus I'm definitely not arguing about the need for those rules. I'm just not 100% sure whether they should be in the core or a separate plugin. I don't think the case of them being part of the official spec plays much role. If we do add them to the core, and less then 1% of users end up enabling them, that's probably a good use-case of packaging them as plugin instead of bloating core. That's the question I have. Maybe this would be a good time to start thinking about official plugins that are part of the eslint organization?

**Comment by keithamus** [comment]
The situation seems, right now, that eslint plugins are for frameworks (like react) more than esoteric features that are core JS. This makes sense to me at least; eslint is for writing ecmascript, eslint-plugin-`*` is for writing valid `*`. I'd make the humble suggestion that should eslint go down the route of "official plugins" then it should try hard to maintain this level of separation, and instead pull out plugins like eslint-plugin-browser, eslint-plugin-node, eslint-plugin-jsdoc - as these, to me, are more "optional" on a per-project basis.

**Comment by nzakas** [comment]
I think this is fine as a core rule. Rules are evaluated on a case by case basis. As long as the rule isn't library specific and represents a solid recommendation or distilled best practice, then it can be in the core. Reflect was created specifically to encourage this exact use case, so I'm happy to help with that encouragement.

**Comment by keithamus** [comment]
:tada: I'll get working on a PR over the weekend :smile:

**Comment by keithamus** [comment]
Got a bit busy over the weekend, plan to put together a PR this week.

**Comment by nzakas** [comment]
Thanks!
