### ISSUE TITLE
.eslintignore patterns with opening slashes don't work

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint#2940]
For example if I want to ignore the `dist` folder, specifically the one at the root of my project (but not ignore other things that happen to be called `dist` elsewhere in my project), I can use this in `.gitignore`:

```
/dist/
```

But this kind of pattern doesn't work in `.eslintignore`. The opening slash stops it working at all, and nothing gets ignored.

**Comment by gyandeeps** [comment]
Possible duplicate of https://github.com/eslint/eslint/issues/1862

**Comment by callumlocke** [comment]
Yes it is
