### ISSUE TITLE
new rule: prefer-spread

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#2946]
In ES6 there is the wonderful spread operator `...` that makes it easy to apply an array to a function.

In JS you may have previously typed `console.log.apply(console, [1,2,3])` or `foo.apply(foo, x)`.

With spread you can instead say `console.log(...[1,2,3])` or `foo(...x)`.

In my opinion it's a much nicer syntax and generally should be preferred over the other when in an ES6 environment.

**Caveats**

You can't easily imitate this with spread:
`foo.apply(bar, x)`

So the rule would limit itself to occasions where the `context` is the same as the function being applied to. For that case it was suggested that `Reflect.apply` should be used instead (See: #2939)

**Comment by mysticatea** [comment]
I like this!

> `foo.apply(foo, x)`

`foo.apply(undefined, x)`?

**Comment by mysticatea** [comment]
I will try to make this.
