### ISSUE TITLE
Should no-redeclare also check functions?

### ISSUE THREAD

**Issue by dominicbarnes** [eslint/eslint#2953]
I just got burned by a stupid mistake, but I think it should've been caught by `no-redeclare`.

Given the following code:

```
var a = true;
function a() {}
```

If I turn on `no-redeclare: 2`, this is **not** treated as an error, but I think it should.

To be clear, this was a stupid mistake on my part. I added a `var` to the top of a file that was named the same as a function declared much further down in my code. Nonetheless, I think `no-redeclare` should take hoisted functions into account as well.

**Comment by gyandeeps** [comment]
I know there have been conversations around this. Have you tried using `no-shadow` rule.
Related discussions happened here: #2895

**Comment by dominicbarnes** [comment]
This is not an issue `no-shadow` will catch, since this all happened in the "global scope" (not _truly_ global, but it wasn't in a nested function of my module)

**Comment by gyandeeps** [comment]
What are `env` are you using in your eslint config?

**Comment by dominicbarnes** [comment]
In this particular case, I'm using `browser` (plus all ES6 features)

**Comment by nzakas** [comment]
Yeah, most likely a bug even though the docs would indicate otherwise. We should fix this and update the docs to be more accurate.

**Comment by mysticatea** [comment]
I tried:

```
> eslint -v
v0.24.0
> echo "var a = true; function a() {}" | eslint --stdin --env browser --env es6 --rule "no-redeclare:2" --reset --no-eslintrc

<text>
  1:24  error  a is already defined  no-redeclare

✖ 1 problem (1 error, 0 warnings)
```

If you have turned `ecmaFeatures: {modules: true}` on, yes, the `no-redeclare` rule had been missing global declarations. And it was fixed on `master` branch now.

Related: #2903

**Comment by dominicbarnes** [comment]
I can verify that `master` has fixed this issue. Should I close this issue?

**Comment by gyandeeps** [comment]
If you have verified this then you can close.

**Comment by dominicbarnes** [comment]
Actually, could we add tests for `no-redeclare` that include checking named/hoisted functions? (just noticed all the examples there are either `var` or `class`)
