### ISSUE TITLE
Destructuring issue: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by resistdesign** [eslint/eslint#2954]
When linting the following code:
```js
var p = {m: 'M'};

var {m} = p;
```
I get the following error:
```
TypeError: Cannot call method 'toLowerCase' of undefined
    at /Users/*******/node_modules/eslint/lib/rules/sort-vars.js:24:57
```

**Comment by resistdesign** [comment]
`destructuring` is enabled in the config.

**Comment by Aourin** [comment]
I have been looking at this quite a bit.

In the VariableDeclaration function the names are assigned to memo.id.name and decl.id.name;

It looks like when a something id decalred like
```
const sounds = {dog: 'woof'};
const {dog} = sounds;
```
The destructured object comes in as an "ObjectPattern". The memo.id itself is an array of "Property" objects with a key object and a value object. The name property resides within the key and value objects. It doesn't resolve those correctly. I am unsure of the complete intended portion of this code so I haven't found a good solution to this.

**Comment by nzakas** [comment]
We probably just need to skip destructured declarations.
