### ISSUE TITLE
Add "Who Uses ESLint" section to the website

### ISSUE THREAD

**Issue by jesstelford** [eslint/eslint#2956]
JSHint has a section listing [who uses it](http://jshint.com/about/), as does jscs [right on their home page](http://jscs.info/), but I can't find any equivalent list for ESLint.

To start the list off, here are some big-name companies who use it:

* [PayPal](https://www.paypal-engineering.com/2014/12/12/maintaining-javascript-code-quality-with-eslint/)
* [Uber](https://github.com/uber/lint-trap)
* [Big Binary](http://how-we-work.bigbinary.com/conventionandstyle/using-eslint.html)
* Domain.com.au (source: I work at Domain)

**Comment by lo1tuma** [comment]
We already have a section in our README.md. There is also an issue to integrate this for eslint.org, see https://github.com/eslint/eslint.github.io/issues/33

**Comment by jesstelford** [comment]
Whoops, didn't realize it was a separate repo. Thanks :)
