### ISSUE TITLE
"strict": [2, "global"] warns about "use strict"; on top of file

### ISSUE THREAD

**Issue by hasenstein** [eslint/eslint#2957]
I have `'use strict';` on top of each file in my iojs.js (ES6) project. When I tell eslint to check for "strict" with option "global" (in preparation for eslint 1.0 where I have to specify an option) it starts complaining about the strict mode line I have on top of each file. But that's exactly what "global" is supposed to mean, isn't it?

**Comment by mysticatea** [comment]
Maybe, duplicate of #2785

**Comment by hasenstein** [comment]
Looks like it.
