### ISSUE TITLE
is there som way to exclude certain checks by file pattern

### ISSUE THREAD

**Issue by AllanHoejgaardJensen** [eslint/eslint#2958]
Recently we have started using eslint and are very happy with it, and we have a question for you. 

We have a number of unit test files named "<some-script>_test.js" or "some-other-script>-test.js" and these tests get quite a lot of stuff injected and thus the number of parameters gets much higher than the target for the test, thus is why we looked for for some way of excluding e.g. the "max-params" http://eslint.org/docs/rules/max-params for files postfixed with _test.js and -test.js. 

So far we were not succesful in finding a way to do that, is there a way - or is this in fact a request for new functionality?

Thank you for your time.

**Comment by lo1tuma** [comment]
This is not possible with ESLint right now. It was proposed on the [ESLint 2.0 wishlist](https://github.com/eslint/eslint/issues/2203), so we will discuss this feature again after ESLint 1.0 is released.

There is also [a thread](https://groups.google.com/forum/#!topic/eslint/0irFhzhXZkg) on our mailing list about this topic.

**Comment by AllanHoejgaardJensen** [comment]
thank you very much
