### ISSUE TITLE
New exception: space-in-parens exception for the function keyword

### ISSUE THREAD

**Issue by empyrical** [eslint/eslint#2969]
Example of what I mean:

```js
// What I'd like to be acceptable (also with "{}" exception enabled)
someFunction(function ( callback ) {
  callback();
});

(function () {
  doSomething();
})();

// Currently forced to do
someFunction( function ( callback ) {
  callback();
});

( function () {
  doSomething();
})();
```

**Comment by nzakas** [comment]
So it's not the function keyword, it's whenever you have a function expression? What about this?

```
SomeFunction(function() {}, a, b, c);
````

 What would be your expectation there?

**Comment by empyrical** [comment]
I'd say that'd be what I'd expect, because for example this is how I'd like to use setTimeout

```js
setTimeout(function() {
  doSomething();
}, 1500 );
```

**Comment by nzakas** [comment]
I'm having a hard time figuring out how to describe this generically in such a way that it makes sense in this rule. What is special about a function that it's an exception? 

We generally don't incorporate such specific exceptions because that becomes a never-ending maintenance issue. 

@eslint/eslint-team thoughts on this?

**Comment by empyrical** [comment]
I guess the best way to put it would be: an anonymous non-arrow function expression in between parenthesis. It would also mean an ES7 `async function` should get linted like this too. It's not a *huge* deal, `doSomething(function() {` just looks better to me than `doSomething( function() {`

This is how the jQuery project (the styleguide I like using) seems to use its anonymous functions too:

* https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/src/wrap.js#L24

**Comment by nzakas** [comment]
The jQuery style guide actually shows that spaces should always be used: https://contribute.jquery.org/style-guide/js/#good-examples

See the last two examples.

**Comment by empyrical** [comment]
I noticed that - but after I did a grep of their source code, it seems they use `( function` only 3 times - and `(function` 76 times (on current `master`). Maybe this inconsistency would be worth bringing up as an issue on their tracker?

I've never made an eslint plugin before - but if this exception is inappropriate for eslint, would it be possible to do it as a plugin?

**Comment by nzakas** [comment]
It's probably worth pointing that out to them. Regardless, they are very consistent in that opening spacing is always the same as closing spacing. Example:

https://github.com/jquery/jquery/blob/a644101ed04d0beacea864ce805e0c4f86ba1cd1/test/data/core/dynamic_ready.html#L14

You can do whatever you want in a custom rule/plugin.

**Comment by empyrical** [comment]
Alright, thanks man! I'll see what I can do with the plugin api. If the jQuery folks have anything to say about this oddity, I'll ping back here
