### ISSUE TITLE
0.24.1 changelog?

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#2976]
I don't see a changelog entry for 0.24.1 on master - I do see it on https://github.com/eslint/eslint/commit/b4423e309e74956adb05eb543ffb653086e4fe0e however.

**Comment by nzakas** [comment]
It's in the 0.x branch and here: https://github.com/eslint/eslint/releases/tag/v0.24.1

**Comment by ljharb** [comment]
Thanks - I'll use that for now. Presumably it still would be merged into the master branch though, since the changelog is kind of across all branches at once?

**Comment by nzakas** [comment]
I wasn't planning on it, but probably a good idea.

**Comment by ljharb** [comment]
Thanks!
