### ISSUE TITLE
Strict mode paradox in ES6 constructor

### ISSUE THREAD

**Issue by dar5hak** [eslint/eslint#2977]
Here's some ES6 code (I'm using Node 0.10 with ESLint 0.24.0 via gulp-eslint):
```javascript
class Bub extends EventEmitter{
  constructor(config) {
    'use strict';
    this.BASE_URL = 'https://api.telegram.org/bot' + config.token;
    this.TIMEOUT = config.timeout || 864000;
    this.offset = null;
  }
}
```

And here's my `.eslintrc`:
```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "rules": {
    "strict": [2, "function"]
  }
}
```

At the third line, ESLint throws a `no-extra-strict` error. If I remove the statement, it asks me to use the function form of 'use strict'. Is this a bug? Or am I doing something wrong?

**Comment by michaelficarra** [comment]
Class bodies are already strict mode code, so whatever rule that's telling you that you need a use strict directive is broken.

**Comment by dar5hak** [comment]
It's the new `strict` rule that's telling me to use strict mode.

**Comment by michaelficarra** [comment]
Yes, it seems the [current strict rule](https://github.com/eslint/eslint/blob/2ce95aaae22c818030eab1485f45656aa3c4bef6/lib/rules/strict.js) doesn't mention classes anywhere at all.

**Comment by nzakas** [comment]
@dar5hak can you provide the complete output from ESLint in both cases you describe?

**Comment by dar5hak** [comment]
@nzakas Sure. 
I took out the code into a separate file:
```javascript
var EventEmitter = require('events').EventEmitter;

class Bub extends EventEmitter{
  constructor(config) {
    'use strict';
    this.BASE_URL = 'https://api.telegram.org/bot' + config.token;
    this.TIMEOUT = config.timeout || 864000;
    this.offset = null;
  }
}
```

Here's the output without the statement:
```
test.js
  3:6   warning  Bub is defined but never used   no-unused-vars
  4:13  error    Missing "use strict" statement  strict

✖ 2 problems (1 error, 1 warning)
```
And here's the output with the statement:
```
test.js
  3:6  warning  Bub is defined but never used  no-unused-vars
  5:4  error    Unnecessary 'use strict'       no-extra-strict

✖ 2 problems (1 error, 1 warning)
```
(PS: Happy birthday!)

**Comment by mysticatea** [comment]
`ClassDeclaration` and `ClassExpression` are always strict mode automatically, by [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code). so the `"use strict"` directive is unnecessary. It's correct.

But `4:13  error    Missing "use strict" statement  strict` is strange...

**Comment by nzakas** [comment]
@dar5hak thanks. :)

So this looks like a bug in the `strict` rule. You should disable `no-extra-strict` as that is deprecated and not needed if you're using `strict`.

**Comment by mysticatea** [comment]
I will try to fix this.

I will make two PR, for `master` and for `0.x`.

And I will add a message for a reason of unnecessary: such as `module codes are strict mode always` and `class bodies are strict mode always`.

**Comment by ilyavolodin** [comment]
@mysticatea No need to do two PRs, do one PR into master, and we will cherry-pick that commit into 0.x branch whenever we will do a release.

**Comment by mysticatea** [comment]
Hm, this rule at 0.x has a deprecated mode which is nothing at master. So I guess two PRs are needed.

**Comment by ilyavolodin** [comment]
Oh, right, I forgot about deprecated mode, sorry. In that case, yes, we would probably need 2 PRs.

**Comment by nzakas** [comment]
I'd just fix this on master. I'm doing the first RC today, and I'd rather not complicate things with continuing to do 0.x releases.
