### ISSUE TITLE
Specify config file per source file?

### ISSUE THREAD

**Issue by mkscrg** [eslint/eslint#2979]
Is there a way to set the ESLint config file _per source file_?

I'm migrating a project to ES6 (as well as from JSHint to ESLint). I'd like to setup two ESLint configs so we can migrate gradually and maintain our existing code along the way. I'm thinking of a pragma like

```js
/* eslint-config es5-lint.json */
```

that we would add to our ES5/CommonJS modules, then gradually remove the pragmas and "default" to our ES6 setup.

**Comment by nzakas** [comment]
There's no way to do this currently, and we can't support your suggestion because the config fit the file must be known before the file is parsed.

There's a proposal to allow config specified by a glob pattern post-1.0.0.
