### ISSUE TITLE
Checker definition probably flawed.

### ISSUE THREAD

**Issue by bgvianyc** [eslint/eslint#2985]
I'm using eslint with eslint-plugin-react being called from emacs flycheck. I created an init file in the react project directory enabling react and jsx checking. However when the checker is run on a react jsx file, here is the errors thrown:

> Suspicious state from syntax checker javascript-eslint: Checker javascript-eslint returned non-zero exit code 8, but no errors from output: 
/usr/local/lib/node_modules/eslint/lib/util.js:33
            property.forEach(function (plugin) {
                     ^
TypeError: Object react has no method 'forEach'
    at /usr/local/lib/node_modules/eslint/lib/util.js:33:22
    at Array.forEach (native)
    at Object.mergeConfigs (/usr/local/lib/node_modules/eslint/lib/util.js:25:25)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:370:19)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:226:12)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:322:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)

wondering why? What is the cause of the issue?

**Comment by ilyavolodin** [comment]
Can you provide the following:
Version of ESLint you are using, source of the file where the error occurs, copy of your config file.
On top of that, can you try running ESLint directly on the file in question bypassing flycheck and if it fails, can you provide output of the error here as well?

**Comment by bgvianyc** [comment]
v0.24.0

.eslintrc =
-------------------
{
    "rules": {
        "indent": [
            2,
            "tab"
        ],
        "quotes": [
            2,
            "double"
        ],
        "linebreak-style": [
            2,
            "unix"
        ],
        "semi": [
            2,
            "always"
        ]
    },
    "env": {
        "browser": true
    },
    "ecmaFeatures": {
        "jsx": true
    },
    "plugins": [
        "react"
    ]
}
-------------------------
bg$ DocumentItem.jsx 

/usr/local/lib/node_modules/eslint/lib/util.js:33
            property.forEach(function (plugin) {
                     ^
TypeError: Object react has no method 'forEach'
    at /usr/local/lib/node_modules/eslint/lib/util.js:33:22
    at Array.forEach (native)
    at Object.mergeConfigs (/usr/local/lib/node_modules/eslint/lib/util.js:25:25)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:370:19)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:226:12)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:322:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9
----------------------------------------------- DocumentItem.jsx------------------------------
var React = require('react');
var Link = require('react-router').Link;

var DocumentItem = React.createClass({
  render: function() {
    return (
      <li>
        <Link to={this.props.route} params={this.props}>
          {this.props.text}
        </Link>
      </li>
    );
  }
});

module.exports = DocumentItem;

**Comment by gyandeeps** [comment]
I see this error is coming from utils file and from `mergeConfig` function. This function was completely changed in `0.24.1` release. Have you tried with `0.24.1`?

Also is this the only config file getting used or you have more config files?

**Comment by ilyavolodin** [comment]
Thanks for the information. Would it be possible for you to upgrade to v0.24.1 and test this again? We updated the code that's failing in v0.24.1 I'm not sure if it will solve your problem, but would like to test before digging deeper.

**Comment by bgvianyc** [comment]
That did it. Works fine now.

**Comment by creamidea** [comment]
I have met the same problem and I was working on **Windows 10**. 
I solved this problem by downing one file: **libxml2.dll** (from [here]( http://xmlsoft.org/sources/win32/))
Next, I put the **libxml2.dll** into **emacs-bin** and then it worked.
Good luck :)
