### ISSUE TITLE
"spaced-comment" rule doesn't support jsdoc-style comments on Windows

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2987]
This is a bizarre one. With this config:

```
{
  "spaced-comment": [2, "always"]
}
```

and this code:

```js
/**
 * Totally not an example function
 * @return {Boolean}
 */
function isFireflyAwesome () {
  return true
}

console.log(isFireflyAwesome())
```

There are no errors on OS X or Ubuntu. But Windows gives this error:

```
t.js:1:0 Expected space or tab after /* in comment.
```

Tested on Windows 7 Professional SP1, 64 bit.

**Comment by gyandeeps** [comment]
Same as https://github.com/eslint/eslint/issues/2884
It has been fixed but hasn't been released.

**Comment by feross** [comment]
So this was merged into `master` but not `0.x`?

**Comment by gyandeeps** [comment]
I think since the PR was marked as `update` thats why it was not merged.

**Comment by feross** [comment]
What does it mean for a PR to be marked `update`?

**Comment by ilyavolodin** [comment]
It means that it's adding new functionality that's backwards compatible. Right now, we are doing releases on 0.x branch only for bug fixes, that's why it was not cherry-picked into 0.x branch for 0.24.1 release.
