### ISSUE TITLE
Add unix-style formatter

### ISSUE THREAD

**Issue by oshi-shinobu** [eslint/eslint#2991]
A formatter which uses more traditional ~~grep~~ unix-style output such as this:

directory/file.js:6:2: Strings must use singlequote. [Error/quotes]

should in my opinion be included in the base eslint distribution - all major linters already support this format (pyflakes, rubocop, perlcritic, not to mention jshint) because it's a standard which can be understood by tools and editors such as Emacs and it's also very easy to parse when using grep/sed/awk.

**Comment by nzakas** [comment]
JSHint calls this s UNIX style reporter. :+1:

**Comment by oshi-shinobu** [comment]
I think people who see "grep" and know about grep's output would immediately understand the style of the formatter.

grep is a very common and specific program that gives this kind of output and a text-processing tool while UNIX is a whole operating system which can run all kinds of programs so that's why I picked grep, but I am not opposed to renaming it if it's the consensus.

**Comment by nzakas** [comment]
@eslint/eslint-team thoughts on this?

**Comment by ilyavolodin** [comment]
Sorry, I'm not familiar with this topic, so no opinion. Both sounds like the should be meaningful to people who would be interested in them.

**Comment by gcochard** [comment]
FWIW npm uses [`porcelain` and `parseable`](https://docs.npmjs.com/all#shorthands-and-other-cli-niceties) as the option name for passing output to other unix utilities. As someone who has used `grep`, I did not recognize the meaning so I vote for `unix` or an unambiguous name such as `parseable` or `porcelain`.

**Comment by michaelficarra** [comment]
@gcochard Those are both better names than the previous suggestions.

**Comment by oshi-shinobu** [comment]
parseable is OK but it's a bit ambiguous as there are many parseable formats, whereas calling this style UNIX at least has some precedents.

I am going ahead with "unix", then, thanks for the feedback!
