### ISSUE TITLE
lint-disable instead of eslint-disable

### ISSUE THREAD

**Issue by denis-sokolov** [eslint/eslint#2993]
Consider adding and promoting the use of `/* lint-disable */` instead of `/* eslint-disable */`.
Of course, the support for the old name should stay, but not be under the spotlight anymore.

The information that the author wants to allow using `console` or `eval` in this particular piece of code is semantically valuable regardless of the particular brand of the linting tool used.

Generalizing the comment name might allow for a wider variety of linting tools, while keeping the directive branded puts potential pressure on other engine authors to interpret eslint-specific directives, similarly to Webkit CSS prefixes issue.
It would also allow for more pleasant sharing of code. Sharing a snippet with an `eslint`-branded comment implies the person receiving it cares about eslint. A non-branded directive would instead be treated as a nice note in the code even if not used directly.

I recognize that the proposal is unlikely to be accepted, but I thought this concern should be addressed before the 1.0.0 release.

**Comment by nzakas** [comment]
I'm sorry, I don't see the value in making such a change. Not all linters would even be able to use the same format or implement disabling in the same way. Linters are not like browsers, there is no standard implementation for which standard interfaces would make sense.
