### ISSUE TITLE
Inline object not being caught by brace-style

### ISSUE THREAD

**Issue by geuis** [eslint/eslint#2997]
I have a sample line of code here:

    return reply.view('home/home', {mainOffer: o, offers: [o, o, o], error: err});

My rule is:

    "brace-style": [2, "1tbs", { "allowSingleLine": false }]

Shouldn't the inline object be caught as an error?

**Comment by nzakas** [comment]
Brace style does not apply to object literals, only to code blocks.

**Comment by geuis** [comment]
@gyandeeps Ok. Is there an alternate rule or rules that will apply?

**Comment by mysticatea** [comment]
http://eslint.org/docs/rules/object-curly-spacing

**Comment by nzakas** [comment]
We don't have a rule that specifies anything other than spacing (as @mysticatea points out).

If you'd like to propose a new rule, please see the guidelines: http://eslint.org/docs/developer-guide/contributing#new-rules

**Comment by gyandeeps** [comment]
Closing because of no response.
Feel free to reopen.
