### ISSUE TITLE
Error: Definition for rule 'callback-return' was not found.

### ISSUE THREAD

**Issue by SgtPooki** [eslint/eslint#3009]
When using the ```.eslintrc``` file included in this repo, after removing the extends, I get the following error.

```
node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:646
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'callback-return' was not found.
```

This error is only resolved after removing the callback-return rule. I was going to submit a PR of removing it from ```.eslintrc``` but it seems like the rule was added about 19 days ago, so maybe something was missed?

**Comment by ilyavolodin** [comment]
What version of ESLint are you running? Since the rule was only added recently, you have to run latest master (unreleased) version.

**Comment by SgtPooki** [comment]
That makes sense. I was running 0.24.1, pulled down fresh from npm. My bad :)
