### ISSUE TITLE
spaced-comment exception for eslint directives

### ISSUE THREAD

**Issue by malandrew** [eslint/eslint#3017]
Having played around with the `exceptions` and `markers` options of the `spaced-comment` rule, there doesn't seem to be a way to require a space after the comment delimiter, except when you use an eslint directive like `/*eslint-disable complexity*/`.

I tried putting strings like `"eslint"`, `"eslint-disable"` and `"eslint-enable"` in the markers array and that didn't seem to work. Seems like this rule does not allow you to configure things so a space is always required except with certain directives like eslint directives.

**Comment by nzakas** [comment]
Can you give some example code, what the output from ESLint is currently, and what you'd like it to be?

**Comment by IanVS** [comment]
Is there a reason you don't want to require a space there? `/* eslint-disable complexity */`

**Comment by xjamundx** [comment]
```js
/*global define:true, s:true, fpti:true, PAYPAL:true */
/*eslint no-undefined:0 */
```

Will show 

```
public/js/widgets/analytics.js
    1:1  error    Expected space or tab after /* in comment  spaced-comment
    2:1  error    Expected space or tab after /* in comment  spaced-comment
```

Seems like a bug

**Comment by xjamundx** [comment]
The examples here don't show a space:
http://eslint.org/docs/user-guide/configuring#specifying-globals

I didn't even realize a space was allowed.

**Comment by IanVS** [comment]
@malandrew, is there still an issue here, or can this be closed?  Perhaps a note in the docs would prevent confusion.

**Comment by IanVS** [comment]
@xjamundx Why is this a bug? Or did you change your mind in your second comment?

**Comment by nzakas** [comment]
I don't believe there's a bug here - this is expected behavior, unless I'm missing something.

**Comment by mysticatea** [comment]
Since #3167 (I refactored the rule), `markers` option works as expected :)

**Comment by malandrew** [comment]
Since @mysticatea said that the refactored rule allows you to set something like `/*eslint` as a marker, this issue can be closed. I haven't tried it yet though. I'll reopen this if necessary or file a new issue if appropriate.

**Comment by xjamundx** [comment]
I guess I'm still confused. Can we add a section to the docs about directives? Currently the section on "configuring comments" says it has to be in the following format (no space):
http://eslint.org/docs/user-guide/configuring#configuring-rules

Obviously I can go and try out each permutation, but I swear at some old point back in the day I remember trying `// global jquery` or whatever and it not working

**Comment by nzakas** [comment]
What permutations? Just follow your normal code conventions as enforced by this rule. Am I missing something?

**Comment by xjamundx** [comment]
Maybe something like this:

### Directives

Directives, also known as configuration comments, can be found in two types: file-level directives and line-level directives. These allow you to change rules, environments or other configuration for one file or just one part of a file. You can choose to use either line or block comments for your directives.

The following block-level directives exist:
- `global` - Add to the list of known global variables
- `exported` - Create exceptions for creating new global variables
- `eslint` - Enable or disable rules
- `eslint-env` - Change the environment

There are also several line-level directives that exist:
- `eslint-disable-line`
- `eslint-disable`
- `eslint-enable`

Here are some examples of how they can be used:
`/*global jquery,_*/`
`/* exported MYPROJ */`
`//eslint quotes: [2, "double"], curly: 2`
`// eslint-env node, mocha */`

**Comment by cvrebert** [comment]
@xjamundx That would be a great addition to the docs. I agree that the current docs appear to imply that spaces aren't allowed in `/*global` etc.
