### ISSUE TITLE
Should `let` or `const` be considered in "newline-after-var"

### ISSUE THREAD

**Issue by whitneyit** [eslint/eslint#3020]
Since [global-strict](http://eslint.org/docs/rules/global-strict) and [no-extra-strict](http://eslint.org/docs/rules/no-extra-strict) were deprecated in favour of [strict](http://eslint.org/docs/rules/strict); how does that play in with [newline-after-var](http://eslint.org/docs/rules/newline-after-var)?

Should a new rule be created to handle `let`, `const`, as well as `var`? Or should a separate ES6 rule be introduced?

I have a requirement for this at the moment and don't mind pitching in for the PR so long as I know the direction to go :smile:

**Comment by gyandeeps** [comment]
`newline-after-var` rule already supports `let` and `const`.

can you share the code and eslint output where you see this rule doesnt work.?
Also what version of eslint and parser are you using?

**Comment by whitneyit** [comment]
I was unaware that it also handled both of those terms.

Perhaps the documentation of the rule could be updated to show that it works for `let` and `const` as well since there is no mention of those keywords in the [docs](https://github.com/eslint/eslint/blob/44dca275a65b9e77a42057105e2a5aa06faf62fa/docs/rules/newline-after-var.md).

Also, is the rule name worth deprecating to show the support for `let` and `const`?

**Comment by gyandeeps** [comment]
I think "Variable Declarations" means `var`, `let` and 'const`. At least for me. 
But I guess we can say it out in docs.

**Comment by whitneyit** [comment]
How about we update some of the examples to also show usage of `let` and `const`?

**Comment by gyandeeps** [comment]
sounds good to me.

**Comment by whitneyit** [comment]
Ok. I'll work on a PR

**Comment by gyandeeps** [comment]
Since you are going to work on it, its good to say it our loud saying variable declaration means `var`, `let` and `const`.

**Comment by whitneyit** [comment]
Will do :smile:
