### ISSUE TITLE
mocha-phantomjs install creating issues with peerdependency

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#3021]
As of the latest release of `mocha-phantomjs`, they locked down their `phantomjs` peerDependency version to `1.9.7-15` (https://github.com/nathanboktae/mocha-phantomjs/commit/219bc30afa7bb629549fdff89d989e737fa67303). But we in our package explicitly require `phantomjs`, so we end up installing the latest (`1.9.17`), and then we get an install error.

here is the error:

```sh
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Gyandeep\WebstormProjects\eslint\npm-debug.log
```

Question: Why do we have `phantomjs` as a devDependency?

**Comment by IanVS** [comment]
> Question: Why do we have phantomjs as a devDependency? 

Looks like `phantomjs` was added along with `mocha-phantomjs` in https://github.com/eslint/eslint/commit/6a373bd10e0e250abf93e50e161bd5d66047e5b2.

At that time, it was necessary to install both.  It wasn't until [a few months later](https://github.com/nathanboktae/mocha-phantomjs/commit/fd6cbad1d67c1d0da06b62ec9eacbce8936d1e5a) that `mocha-phantomjs` added `phantomjs` as a peer dependency.

**Comment by gyandeeps** [comment]
Thanks. I wasn't sure as to where its getting used.
