### ISSUE TITLE
no-extra-parens and react

### ISSUE THREAD

**Issue by nkt** [eslint/eslint#3034]
"no-extra-parens" throws error on this code:
```js
return (
  <div>
    Hello
  </div>
);
```
How I can fix this?
v1.0.0-rc-1

**Comment by gyandeeps** [comment]
Can you share the exact output please?

**Comment by nkt** [comment]
```
❯ cat test.js 
const React = require('react');

function test() {
  return (
    <div>Hello</div>
  );
}

test();

❯ node_modules/.bin/eslint test.js 

test.js
  4:10  error  Gratuitous parentheses around expression  no-extra-parens

✖ 1 problem (1 error, 0 warnings)
```

**Comment by michaelficarra** [comment]
They are unnecessary. Use `return <...>` or

```js
return 0,
  <...>
```

or just disable the rule.

**Comment by nkt** [comment]
I couldn't disable this rule, cause `no-wrap-func` have been replaced by this rule.

**Comment by michaelficarra** [comment]
Then you have my other recommendations. This rule is behaving as designed.

**Comment by nkt** [comment]
If it is, I suggest to add `"return": false` option for this rule, that would ignore described case.

**Comment by michaelficarra** [comment]
What is wrong with using the style I recommend? We shouldn't have exceptions for a use case that is entirely optional.

**Comment by nzakas** [comment]
@nkt your only real option is to disable the rule. You can do so in your config or by using comments: http://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by mysticatea** [comment]
@nkt The `no-extra-parens` rule has an option `"functions"`. I guess you can use the option.

**Comment by drewed** [comment]
@michaelficarra Actually, the parenthesis are required for multi-line JSX statements, otherwise the transpiler fails.  So while @nkt's example could be solved by expressing the JSX in a single line, other examples will hit this issue.  For example:

```javascript
class App extends Component {
    /* ... */
    render() {
        return (
            <div>
                <Header
                    {...this.state.i18n}
                    flux={this.props.flux} />
                <hr />
                {
                    React.Children
                        .map(this.props.children, this.renderChild)
                }
                <hr />
                <Footer />
            </div>
        );
    }
}
```

Technically, this example could also be expressed as a single line too but it would become significantly less readable.  I also realize that React syntax would be a special case but it would be helpful if eslint, which purports to natively support JSX, didn't through false positives for required syntax.

**Comment by btmills** [comment]
> Actually, the parenthesis are required for multi-line JSX statements

@drewed Where are you seeing that? Your example works fine [with](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20App%20extends%20Component%20%7B%0A%20%20%20%20%2F*%20...%20*%2F%0A%20%20%20%20render()%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CHeader%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B...this.state.i18n%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20flux%3D%7Bthis.props.flux%7D%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chr%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20React.Children%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(this.props.children%2C%20this.renderChild)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chr%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CFooter%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D) or [without](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20App%20extends%20Component%20%7B%0A%20%20%20%20%2F*%20...%20*%2F%0A%20%20%20%20render()%20%7B%0A%20%20%20%20%20%20%20%20return%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CHeader%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B...this.state.i18n%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20flux%3D%7Bthis.props.flux%7D%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Chr%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20React.Children%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(this.props.children%2C%20this.renderChild)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Chr%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CFooter%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%3B%0A%20%20%20%20%7D%0A%7D) parens, and the [JSX spec](https://facebook.github.io/jsx/) generally allows whitespace:

> JSX uses the same punctuators and braces as ECMAScript. WhiteSpace, LineTerminators and Comments are generally allowed between any punctuators.

Could this be a bug in the transpiler you're using?

**Comment by nkt** [comment]
@btmills you're right. JSX allows this. But eslint is a tool for code linting, so in this case `extra-parens` makes code more readable, that's why I've suggested to add exception for jsx code, or just for `return` statements.
Now I have to use `"no-extra-parens": [2, "functions"]` config, and eslint doesn't help me make code more readable in other cases, like `const a = (b + c);`, where I can drop parens safely.

**Comment by drewed** [comment]
@btmills I'm certainly no expert in JSX.  I dug through most of the examples on facebook (most of which use the parenthesized multi-line syntax) and tried one out on react's jsfiddle (https://jsfiddle.net/reactjs/69z2wepo/) Running the multi-line JSX without the parens caused the code to break.  So, yes, you're probably right that it's a bug in the JSX in-browser transpiler.

**Comment by mysticatea** [comment]
Actually, this issue is not related with JSX. Such as [this](https://github.com/eslint/eslint/blob/master/lib/rules/no-shadow.js#L51-L58) is warned by `extra-parens`.
Also, I want to use parens in expressions which are a mix of `&&` and `||` even if it's extra, so I prefer `[2, "functions"]`.

**Comment by michaelficarra** [comment]
@drewed I cannot reproduce what you have claimed. I think people just don't typically know that you can't have a line terminator between `return` and its expression.

**Comment by drewed** [comment]
@michaelficarra You're right.  I wasn't aware of that restriction on the return statement so when I removed the wrapping parenthesis from the multi-line JSX it left the first line of the expression on a different line from the return statement and the JSX transpiler on JS Fiddle didn't give me any output.  Not because the JSX was illegal but because the JS syntax was bad.  If I remove the parenthesis and the newline then it's fine.  Thanks for the enlightenment.

Perhaps the reason Facebook's docs and tutorials feature the extra parenthesis is to allow the JSX multi-line markup to be more readable but as you stated above, they aren't required.  So, in terms of syntax, the parenthesis aren't required but in terms of style, Facebook, at least, encourages them.  It would be nice to be able to configure the rule to support that style but "nice-to-have" is a far lower priority.

**Comment by honzabrecka** [comment]
I think that those extra parenthesis around JSX makes code more readable, so it should cause error.

**Comment by petetnt** [comment]
:+1: for adding an option to allow wrapping these kinds of parens: they aren't required, but Facebook itself does use them for all the multiline examples. ESLint is not opinionated, so why not allow such behavior if needed (without destroying other functionality related to `no-extra-params`)? It's not like that it's a bad practice in the first place, but unneeded at worst (and improves the readability and lessens the probability of errors due to line breaks after returns and such at best).

**Comment by dsernst** [comment]
@michaelficarra: The `0, ` trick does not work in this case:

```
var routes = 0,
  <Route name='app' path='/' handler={Master}>
    <DefaultRoute handler={ConfigScreen} />
    <Route name='play' handler={PlayScreen} />
  </Route>
```

The interpreter breaks with: `Parse Error: Line 61: Unexpected token < while parsing`

**Comment by michaelficarra** [comment]
Looks like a bug in your parser.

**Comment by dsernst** [comment]
Alright, the parser is `esprima-fb@15001.1001.0-dev-harmony-fb`.

**Comment by frantic1048** [comment]
@michaelficarra Could you please explain what the `0,` trick means ? I've tried to search doc about that but I found nothing.

**Comment by dsernst** [comment]
@frantic1048: It's a way to start the body of the `return` value on the next line. 

See this example:
<img width="331" alt="screen shot 2015-10-27 at 11 22 40 pm" src="https://cloud.githubusercontent.com/assets/6340841/10781104/a5be9d70-7d01-11e5-8a64-47b834ee979c.png">

The value before the comma gets ignored, and only what comes after the comma is returned. 

In this case, we're also abusing the fact that ending a line on a comma will cause the `return` statement to continue interpreting onto the next line, so that we don't need to wrap our multiline expression in parentheses.

**Comment by frantic1048** [comment]
@dsernst I think I got it.

The return statment follow by a whole expression combined with comma, just like `return (0, result);`.
And though comma operator's feature, `return` statment finally returns the last `result` back ?

It's really a trick lol
Thanks a lot!

**Comment by dnutels** [comment]
Oh my...

Suggesting to use some contraption like 

```
var routes = 0,
  <Route name='app' path='/' handler={Root}>
```

in an issue thread for **style and code checker** is THE definition of irony.

**Comment by gyandeeps** [comment]
Please follow https://github.com/eslint/eslint/issues/4229 for further discussions.

**Comment by dnutels** [comment]
@gyandeeps 

Considering that both issues are closed it seems to be futile anyway.

**Comment by gyandeeps** [comment]
#4229 is still open for a potential enhancement.

**Comment by fernandopasik** [comment]
Using return has been attended but seems that when saving jsx into a variable still throws error with no-extra-parents.
```
var routes = ( //eslint-disable-line no-extra-parens
  <Route name='app' path='/' handler={Root}>
    <DefaultRoute handler={ConfigScreen} />
    <Route name='play' handler={PlayScreen} />
  </Route>
)
```

**Comment by michaelficarra** [comment]
@fernandopasik Just remove the parentheses.

**Comment by fernandopasik** [comment]
I'm using as good practice to wrap multiline jsx with parenthesis and enforcing it through a react plugin rule **react/wrap-multilines**.

**Comment by pelotom** [comment]
Yeah, it seems like there is still a fundamental conflict between `react/wrap-multilines` and `no-extra-parens`...

**Comment by thefringeninja** [comment]
:+1: @fernandopasik the extra parentheses are idiomatic jsx.

You can sort of get there with `{ "returnAssign": false }` but that won't work in all cases e.g., defining a jsx snippet inside of an array.

**Comment by fernandopasik** [comment]
Right now if you include the react plugin there is no problem using `no-extra-parens` with the return statement. This example does not present a linting error even without configuring the option that you mention @thefringeninja (Mi config right now has the rule as `'no-extra-parens': 'error'`)

```
return (
    <Route name='app' path='/' handler={Root}>
        <DefaultRoute handler={ConfigScreen} />
        <Route name='play' handler={PlayScreen} />
    </Route>
);
```

But when you have just a var assignment like in my previous [example](https://github.com/eslint/eslint/issues/3034#issuecomment-225389242) that's where it throws an error and I don't see an exception in the rule that can be to avoid that.

**Comment by jackwilsdon** [comment]
It looks like this was fixed in #7926, you can now do the following;

```JSON
{
  "rules": {
    "no-extra-parens": [ "warn", { "ignoreJSX": "none|all|multi-line|single-line" } ]
  }
}
```

In the case of this issue, it sounds like you want `multi-line`;
> allows extra parentheses around no/all/multi-line/single-line JSX components.

**Comment by plonko** [comment]
Anyone got any ideas how to _enforce_ extra parens within eslint? 😄 

Sick of seeing this:
``` 
render() {
    return <div>
        <span>stuff</span>
    </div>
}
```

Unless you're a monster it should be:
```
render() {
    return (
        <div>
            <span>stuff</span>
        </div>
    )
}
```

**Comment by btmills** [comment]
@plonko the React plugin has [a rule to do that](https://github.com/yannickcr/eslint-plugin-react/blob/aeed629c15a0e000f34a4480769b9394d40795e2/docs/rules/jsx-wrap-multilines.md)!
