### ISSUE TITLE
Reorganize landing page for rules

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#3037]
We are getting more and more rules that only apply to ES6. We should reorganize our readme.md file to reflect that. Also, we have a "Strict rules" group, but as of 1.0.0 we will only have one rule under it.

**Comment by nzakas** [comment]
We should group all rules that flag strict mode violations together as well.

**Comment by nzakas** [comment]
@ilyavolodin we've done some grouping already, do you think this is still necessary?

**Comment by ilyavolodin** [comment]
I think this can be closed for now. I still would like to do some reorganization, but I think we should wait until after metadata is added.
