### ISSUE TITLE
Support for applying rules based off extension.

### ISSUE THREAD

**Issue by ariporad** [eslint/eslint#3041]
Hi!

Awesome project.

I was wondering if you would consider adding an option to apply rules based off extension.

Here's my two use cases:
1. I have the majority of my code as ES6 (in .es6 files), that get's transpiled by babel. But a few files, (ex. my Gruntfile), plain old .js files, and not transpiled. I'd like to be able to apply es6 related things for only .es6 files.
2. All my tests are .test.es6, all my code is .es6. It'd be nice to apply things like the mocha options based off extension.

It this possible now/would you consider it?

Thanks!

**Comment by ilyavolodin** [comment]
This is already on the roadmap for version 2.0.0
