### ISSUE TITLE
Add issue template to repo

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3048]
I've setup a bot that can respond to new issues automatically, we just need a template for it to respond with.

Working on this.

**Comment by michaelficarra** [comment]
Why does it respond with the entire guide instead of just linking to it? The bot as it is right now is very spammy.

**Comment by nzakas** [comment]
Because having the information front-and-center usually works better than asking people to click a link and read. We will try it out and gather feedback to see what we need to adjust.
