### ISSUE TITLE
no-use-before-define: marks some calls as errors when they might not be errored

### ISSUE THREAD

**Issue by SamuelBolduc** [eslint/eslint#3050]
A picture is worth a thousand words:

![screen shot 2015-07-17 at 3 38 11 pm](https://cloud.githubusercontent.com/assets/4836669/8755593/21b298b8-2c9a-11e5-8346-d71db9b0ee95.png)

In this code snippet, the calls to my functions are marked as errors, but this code is perfectly fine, since all the functions defined below are evaluated before they are actually called inside `module.exports`.

Maybe an option to avoid this could be added?

**Comment by IanVS** [comment]
What is your rule configuration?  Have you tried setting `"nofunc"`, as explained in the [rule docs](http://eslint.org/docs/rules/no-use-before-define)?

**Comment by btmills** [comment]
My initial reaction is that something like this would require more static analysis than we want to put into ESLint, but I'd welcome a way to do this that proves that wrong. Ideas, anyone?

**Comment by nzakas** [comment]
The point of this rule is to flag whenever you use (aka reference) an identifier that has not yet been defined. In this case, the rule is correct, you are referencing those identifiers before they are defined. This isn't making any guarantees about whether or not a runtime error will occur, as the point of this rule is only to say that declarations should come before references in the file.

**Comment by SamuelBolduc** [comment]
You are right, this is probably bad practice anyways to declare my functions below. Also, @btmills is right about the analysis required to make such a rule.

In the end, I changed my function declarations from `const myfunc = (foo, bar) => {};` to the more conventional `function myfunc(foo, bar) {}`.

I personally don't need this rule modification anymore, and will just make sure I write my code accordingly from now on.
