### ISSUE TITLE
no-use-before-define.js: ignore hoisted named function expressions

### ISSUE THREAD

**Issue by andrewdeandrade** [eslint/eslint#306]
When you declare a function via a named function expression, e.g. `function myFunc() {};`, JavaScript hoists that function so it is available before evaluation within the context in which is was declared. Currently the no-use-before-define.js rules throws a warning for this common use case.

**Comment by wildeyes** [comment]
Is there a rule like no-use-before-define that ignores hoisted variables / functions?

**Comment by platinumazure** [comment]
@wildeyes Have you looked at [`no-undef`](http://eslint.org/docs/rules/no-undef)? That will detect variables that are not defined at the time of use and will factor in hoisting.

**Comment by wildeyes** [comment]
no-use-before-define has an option called `nofunc` - exactly what I needed.
