### ISSUE TITLE
eslint-global-vs-local

### ISSUE THREAD

**Issue by iamstarkov** [eslint/eslint#3293]
global eslint cannot see local packages. And it kinda wrong: other tools like mocha, karma, grunt and gulp, user local versions of itself if it exists.

You can see the problem. You can run `eslint index.js` and `npm run eslint` in this repo

_index.js:_

    var some = '';

which violate airbnb codestyle. _.eslintrc:_

    { "extends": "eslint-config-airbnb" }

_package.json scripts field:_

      "scripts": {
        "eslint": "eslint index.js"
      },

local copy of eslint runned from npm-scripts works well. global one throw an error. from my perspective of other tools, its wrong.

```
➜  eslint-global-vs-local git:(master) ✗ eslint index.js
/usr/local/lib/node_modules/eslint/lib/config.js:141
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /Users/matmuchrapna/projects/eslint-global-vs-local/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:104:48)
    at /usr/local/lib/node_modules/eslint/lib/config.js:135:46
    at Array.reduceRight (native)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:119:36)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:243:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:371:22)
```
You can play around with these files in this repo https://github.com/iamstarkov/eslint-global-vs-local

**Comment by xjamundx** [comment]
dup of #1238

**Comment by iamstarkov** [comment]
Yeah, I considering to change this behaviour. I dont think its hard to fix, because a lot of tools, already implemented it. And this is backward compatible change, so we dont need to wait until 2.0 to happen

**Comment by xjamundx** [comment]
FWIW I think the "correct" approach is to install it locally, though it's a harder sell for most people. For example, non-node.js projects would not likely ever do that.

**Comment by iamstarkov** [comment]
it’s correct, but global eslint which use local node_modules as environment, is just slight improvement. because, yes, as you say its better to have it locally, but then eslint command will not work =(.

**Comment by iamstarkov** [comment]
Right now, I have a problem, that I have local and global eslint, and `eslint` is shorter than `npm run eslint` to type and I think that eslint is smart enough (as other tools) to switch cli to local one in node_modules. So, I’m not considering break things, but use local things, if they are available.

**Comment by IanVS** [comment]
You can also install eslint-config-airbnb globally if you want to use your global eslint. It's maybe not ideal but it should work.

What other tools are smart enough to add themselves to the $PATH inside of a node project? That would be a neat trick I'd like to know how to do.

**Comment by iamstarkov** [comment]
> You can also install eslint-config-airbnb globally if you want to use your global eslint. It's maybe not ideal but it should work.

I can, but then local eslint-config-airbnb will nothing in common with global one. its not what I want. I only want to have `eslint` shortcut to local copy of eslint.

As far as I know, karma do this

**Comment by IanVS** [comment]
Yes, that's why I said it's not ideal.

Looks like Karma has a separate cli tool to resolve the version: https://karma-runner.github.io/0.13/intro/installation.html

**Comment by ilyavolodin** [comment]
This has been discussed before. The reason other tools like Grunt work when installed globally with local packages, because they split their distribution into multiple pieces. Grunt has GruntCLI and Grunt as separate packages. You only install GruntCLI globally, and then you use Grunt as a local package. We do not want to maintain two separate packages.
I'm not aware of any way of making it work with just one package.

**Comment by nzakas** [comment]
@iamstarkov you can solve your problem with a bash alias. Uninstall the global ESLint and then put this in your .bashrc file:

```
alias eslint='npm run eslint'
```

For now, we don't plan on making changes to support this use case.
