### ISSUE TITLE
Regression in 1.2.0: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Dignifiedquire** [eslint/eslint#3440]
After upgrading from `1.1.0 ` to `1.2.0` I get this error consistently:

```
/path/to/my/project/node_modules/eslint/lib/rules/no-duplicate-case.js:24
            if (!~["loc", "start", "end", "range"].indexOf(prop)) {
                                                   ^
RangeError: Maximum call stack size exceeded
```

Environment:

```
❯ node -v
v0.10.38
❯ npm -v
2.12.0
```

parser: `babel-eslint@4.0.10`
plugins: `esling-plugin-react@3.2.3`

**Comment by Dignifiedquire** [comment]
Sorry for the noise, updating `babel-eslint` to `4.0.10` solves the issue

**Comment by Dignifiedquire** [comment]
Oh god, I'm just too tired, running linting in the wrong folder. This issue is still at hand, and only goes away after downgrading to `1.1.0`

**Comment by BYK** [comment]
Can you please sharea code sample that we can test on?

**Comment by demiazz** [comment]
@BYK I have this problem too, and try reproduce them on simple code, like this:

```javascript
switch (true) {
  case value === anotherValue:
    doSomething();
}
```

Error raised on expression in case. If use simple value or variable - all works good.

**Comment by lcjnil** [comment]
I got into same trouble with these code: https://github.com/lcjnil/react-redux-scaffold/blob/1b7e9ec1da3d8f066145db98f8afc9195a28966f/src/reducers/todos.js

**Comment by ShpuntiK** [comment]
Has the same error with this code:

```
switch (type) {
	case types.Test:
		Component = First;
		break;
	default:
		Component = Second;
}
```

eslint 1.2.0
nodejs 0.12.7
babel-eslint 4.0.10
eslint-plugin-react 3.2.3

**Comment by BYK** [comment]
I'm pretty sure this is related to `babel-eslint` because I cannot reproduce locally with the provided examples.

**Comment by BYK** [comment]
I can reproduce with `babel-eslint@4.0.10`. Investigating...

**Comment by ShpuntiK** [comment]
@BYK yes, you're right. Without `babel-eslint` the error doesn't occur.

**Comment by BYK** [comment]
@gyandeeps - Adding `_paths` to the "ignore list" (on line 24) as suggested by someone else fixes the problem. What do you think? I can add that or ignore property names starting with `_`.

**Comment by gyandeeps** [comment]
What I am hearing so far is that the issue comes up when we use `babel-eslint`, have we logged an issue with that repo?
@BYK I think we need more info because of my above comment ^^.

**Comment by hzoo** [comment]
all the nodes have that property added https://github.com/babel/babel/blob/722e706a8c77cbeca182f67f68e4aff567060fef/doc/node-props.md#_paths

**Comment by BYK** [comment]
This looks like our fault for not detecting cyclic references in that hash
function. I'll try to fix that.

**Comment by kentaromiura** [comment]
My bad, when sending the PR I did not test it with babel-eslint.

@BYK from the link posted by @hzoo just filteting "_paths" should fix the problem as it seems to be the only property on the AST node that can cause a cyclic reference, also the other properties should not cause the node to be unique (and create a different hash).

May I also suggest, if you want to support babel-eslint, to add it to Travis?

**Comment by hzoo** [comment]
I did some work to try to get eslint tests running with babel-eslint https://github.com/babel/babel-eslint/pull/116. Haven't really integrated it well yet though.

**Comment by nzakas** [comment]
I think we should change the logic - it's really being overly optimistic about what properties will be available on each object. The addition of an unforeseen property shouldn't cause a crash no matter what, because we'll never know when new properties might be added.

**Comment by kentaromiura** [comment]
@nzakas a safe alternative would be to use a serialization library that handles circular references like https://github.com/WebReflection/circular-json but that would kill performances.

Another is to handle every possible node type, that would be far more complicated to update as new syntax/node types gets introduced.

**Comment by nzakas** [comment]
Or we simplify the logic and use the source text instead of the AST for comparison purposes.
