### ISSUE TITLE
Branching Proposal

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3468]
We've always basically worked on a one-branch system, where everything happens on master. That was okay while we were small, but now that we're large with many contributors and more frequent releases, this is getting a bit hard to manage. I've found myself asking reviewers not to merge things so we can do a patch release, and that sort of manual intervention will only slow us down in the future. So I'd like to propose a new branching model that (I hope) will make things better going forward.

The basic idea is:

1. The `master` branch is the development branch. We can merge anything at any point in time without fear (yay!).
1. A second branch, called `stable`, is used for creating new releases.

How this works in practice:

1. When it's time for the next release, I'll create the `stable` branch and release from there. 
1. If we decide that we need a patch release, the appropriate fixes will be cherry-picked from `master` into `stable`, and a new release will be cut from there.
1. When it's time for a minor or major release, `master` will be merged into `stable` and a new release will be cut from there.

Downsides/Questions:

1. `CHANGELOG.md` will only ever be up-to-date in the `stable` branch. Can we live with that? If not, what are the alternatives?
   * Same with `package.json`.
1. Are there other approaches that would suit us better?

Thoughts?

**Comment by gyandeeps** [comment]
I like the proposal.
But we have to be ready to face scenarios where even cherry-picking kinda produces errors because of dependencies inside the code (which I think is fair).
Since we have changelog present on every release tag and also on our website so its not a big concern for me.

**Comment by nzakas** [comment]
That's part of why we squash commits on PR, it reduces the likelihood of this type of error. Also, all the tests are run prior to any release, so hopefully that would catch any such issues.

In any case, we wouldn't blindly pick all fixes to move over, just critical ones that can't wait for the next release.

**Comment by xjamundx** [comment]
sounds reasonable!

**Comment by BYK** [comment]
Sounds reasonable to me too. That said I'm wondering why can't we just spin off a brand from the release tag and do hot fix releases on that.

**Comment by nzakas** [comment]
@BYK that's effectively what this does.

**Comment by nzakas** [comment]
@ljharb do you have any feedback on this proposal? You've had some good insights related to releases and such in the past.

**Comment by BYK** [comment]
@nzakas - Yeah but it doesn't require maintaining a persistent `stable` branch. It can even be done locally actually, right?

My main objection is, I don't really see a benefit from maintaining a `stable` branch as long as we have version tags pushed to GitHub.

**Comment by ljharb** [comment]
Here are the primary things I find important:
 - any release *must* point to a properly git-tagged version
 - the CHANGELOG on the default branch (ie master) should be up to date.
 - follow semver.

I don't think there's any need for a `stable` branch. Example: if master would be v3.0, and master~5 was v2.5.0, and you want to release a v2.5.1, here's how I'd do it: `git checkout v2.5.0 && git cherry-pick someCommitSHA && npm version patch && npm publish`. You don't need a 2.x branch at all - you just cherrypick commits *directly* on top of the version tag you want to iterate from, from `master`.

**Comment by nzakas** [comment]
Ah, my git fu is weak. In that scenario, how does the new tag and updated changelog get back onto master?

**Comment by ljharb** [comment]
Since the commits came from master, you wouldn't need to get those back onto master, and the new tag would remain divorced from master (which is OK). You'd then `git checkout master && git checkout v2.5.1 CHANGELOG.md && git commit -am 'v2.5.1 changelog' && git push` and the changelog would be up to date in `master` also.

**Comment by nzakas** [comment]
Ah fancy! I wonder if our changelog generation would get confused with the detached version (it looks at the last tag and gets all commits since then).

**Comment by ljharb** [comment]
Yeah, that's true - the commits from `v2.5.0..v2.5.1` should be just fine tho, and actually, since the same commits are in master and cherry picked, `git diff v2.5.1..master` should still skip over the duplicated commits - so i think you'd be ok

**Comment by nzakas** [comment]
Cool, we'll go with that then. Thanks for the feedback!
