### ISSUE TITLE
Move some eslint methods to SourceCode

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3516]
Now that `SourceCode` is merged, I'd like to move more of the AST-specific functionality to it. The `eslint` object right now has a mix of methods such as `getComments()` that apply only to the AST and really should never have been on the object.

My goal is to move these methods to `SourceCode` and then have the methods on `eslint` just delegate to `SourceCode`. We can't really remove those methods since others might be relying on them, but we can certainly refactor so that the code doesn't live inside of the `eslint` object.

**Comment by gyandeeps** [comment]
Right now they are actually getting delegated from `ast-utils` module.

**Comment by nzakas** [comment]
Oh okay, somehow I missed that. I think they should all be together in `SourceCode`, and there are other methods on `eslint` that should not be there as well:

* getSource()
* getNodeByRangeIndex()
* getSourceLines()
* getAllComments()

**Comment by gyandeeps** [comment]
I idea of `ast-utils` was to have common methods which rely on ast but dont need `context`.

**Comment by nzakas** [comment]
Yup, I remember. I don't think that changes anything.

**Comment by gyandeeps** [comment]
What about `findJSDocComment`? Right now ist in `ast-utils`.

**Comment by nzakas** [comment]
That too. It occurred to me over the weekend that the role of `ast-utils` is really better encapsulated in `SourceCode`. That way, there's just one object to deal with regardless of what you're trying to do. And then we can start encouraging people to do `context.getSourceCode()` and work on that so we can keep the number of methods on `context` where it is right now (already getting a bit too big).

I'll do a first pass with a couple methods and send a PR to show you.

**Comment by gyandeeps** [comment]
Sounds good.

**Comment by nzakas** [comment]
By the way, I think the `is*()` methods will still be on ast-utils.
