### ISSUE TITLE
Proposal: Code Path Analysis! [$50]

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#3530]
Currently ESLint does not compute code paths, so has some known issues (e.g. #2795). This proposal adds API to use code path analysis from rules.

This computes code paths in ESLint's main traversing. This fires events for start/progress/finish code path. And this adds argument of node enter/leave events.

```js
module.exports = function(context) {
    return {
        //----------------------------------------------------------------------
        // New events.
        //----------------------------------------------------------------------

        /**
         * Called on started new code path.
         * It's fired on `Program`, `FunctionDeclaration`, `FunctionExpression`,
         * or `ArrowFunctionExpression`.
         *
         * @param {CodePath} codePath - The new code path.
         * @param {ASTNode} node - The first node of the code path.
         * @returns {void}
         */
        "onCodePath": function(codePath, node) {
        },

        /**
         * Called on completed a code path.
         * This is fired on `Program:exit`, `FunctionDeclaration:exit`, 
         * `FunctionExpression:exit`, or `ArrowFunctionExpression:exit`.
         *
         * @param {CodePath} codePath - The completed code path.
         * @param {ASTNode} node - The same node as `CodePath` callback.
         * @returns {void}
         */
        "onCodePath:exit": function(codePath, node) {
        },

        /**
         * Called on started new code path segment.
         * This is fired on a code path was forked/merged.
         *
         * @param {CodePathSegment} seg - The new code path segment.
         * @param {ASTNode} node - the first node of the code path segment.
         * @returns {void}
         */
        "onCodePathSegment": function(seg, node) {
        },

        /**
         * Called on completed a code path segment.
         * This is fired on a code path was forked/merged, before `onCodePathSegment` 
         * event.
         *
         * @param {CodePathSegment} seg - The a completed code path segment.
         * @param {ASTNode} node - the last node of the code path segment.
         * @returns {void}
         */
        "onCodePathSegment:exit": function(seg, node) {
        },

        //----------------------------------------------------------------------
        // Getting the current code path.
        //----------------------------------------------------------------------

        "ExpressionStatement": function(node) {
            var codePath = context.getCodePath();
            var seg = codePath.currentSegs[0];
        }
    };
};
```

```ts
interface CodePath {
    id: string;
    currentSegs: CodePathSegment[]; // the current segments.

    initialSeg: CodePathSegment; // the first segment.
    finalSegs: CodePathSegment[]; // a mix of returned and thrown segments.
    returnedSegs: CodePathSegment[]; // returned segments. this includes the last segment if it's reachable.
    thrownSegs: CodePathSegment[]; // thrown segments.
}

interface CodePathSegment {
    id: string;
    reachable: boolean;
    nextSegs: CodePathSegment[];
    prevSegs: CodePathSegment[];
}
```

----

For example:

**Souce Code**

```js
if (a) {
    foo();
} else {
    bar();
}
```

**Code Path**

![image](https://cloud.githubusercontent.com/assets/1937871/9492220/866262b0-4c30-11e5-9619-fc9c71ba9b72.png)

**Event's Order**

```
onCodePath
  onCodePathSeg
  | Program 
  |   IfStatement 
  |     Identifier 
  |     Identifier:exit 
  onCodePathSeg:exit
  onCodePathSeg
  |     BlockStatement 
  |       ExpressionStatement 
  |         CallExpression 
  |           Identifier 
  |           Identifier:exit 
  |         CallExpression:exit 
  |       ExpressionStatement:exit 
  |     BlockStatement:exit 
  onCodePathSeg:exit
  onCodePathSeg
  |     BlockStatement 
  |       ExpressionStatement 
  |         CallExpression 
  |           Identifier 
  |           Identifier:exit 
  |         CallExpression:exit 
  |       ExpressionStatement:exit 
  |     BlockStatement:exit 
  onCodePathSeg:exit
  onCodePathSeg
  |   IfStatement:exit 
  | Program:exit 
  onCodePathSeg:exit
onCodePath:exit
```

----

I'm making a prototype of this, and I modified some rules with using this.
I will send a WIP PR later.
I'm predicting deterioration of performance is about 4% (with `npm run perf` command).

----

EDIT: Renamed new events to like `onCodePath`.
EDIT: Removed the second argument from  AST node events. It was replaced with `context.getCodePath()`.
EDIT: Tweaked interfaces of `CodePath` and `CodePathSegment`.

**Comment by ilyavolodin** [comment]
That's pretty cool! Would performance hit be across the board, or only on the rules that will use code path analysis? As in, if I don't have any of the rules that require code path analysis on, would I see any perf difference?

**Comment by nzakas** [comment]
Interesting! Some questions I have about this approach:

1. How would we use these events? I'm not clear on why it's useful to know when a code path is starting, in progress, or ending vs. `context.getCodePath(node)` and return the path you're currently on.
1. Does this interfere at all with plans for query strings?

**Comment by mysticatea** [comment]
@ilyavolodin Across the board. As similar to scope analysis, this makes code path objects one time and those are used by all rules in common.

@nzakas 1) [An example `no-this-before-super`](https://gist.github.com/mysticatea/8fb522983df4f9edef1b#file-no-this-before-super-js-L40-L41).

Basically, I store additional info for the rule into the current path segment while traversing AST nodes. And when the path forked/merged, I distribute/aggregate the info.

I thought `context.getCodePath()` style. [An example](https://gist.github.com/mysticatea/d816be5e0e0b73063905#file-no-this-before-super-2-js-L41).
This style needs to detect forked/merged manually. But it's easy. This style is no problem.

2) I'm sorry, I cannot understand this sentence...

**Comment by ilyavolodin** [comment]
@mysticatea We have an approved feature in v2.0 timeline to add support for selectors something like `VariableDeclaration>Identifier`. Would this interfere with that feature at all? Or would it make it easier to implement?

**Comment by mysticatea** [comment]
@ilyavolodin Thank you for the explanation.

The structure of the current prototype is:

![image](https://cloud.githubusercontent.com/assets/1937871/9538077/68d8bb8a-4d7b-11e5-8e86-3d95801a889f.png)

I think we can insert "selector event generator"  before/after "code path analyzer".

**Comment by nzakas** [comment]
We can probably make querying easier by changing these code path pieces to `onCodePath`, `onCodePathSegment`, and so on, so anything beginning with `on` we know is not part of the AST?

**Comment by mysticatea** [comment]
@nzakas Is your intent below?

```js
module.exports = function(context) {
    return {
        "onCodePath": function(codePath, node) {},
        "onCodePath:exit": function(codePath, node) {},
        "onCodePathSeg": function(seg, node) {},
        "onCodePathSeg:exit": function(seg, node) {}
    };
};
```

This sounds good.
(I was a bit thinking starting with dollar, like `$CodePath`)

**Comment by nzakas** [comment]
Yes, that's what I was thinking.

**Comment by nzakas** [comment]
Because it seems like these events are very useful based on your example.

**Comment by mysticatea** [comment]
Agreed!

**Comment by nzakas** [comment]
I'll take a look at the pull request soon!

**Comment by mysticatea** [comment]
Ugh, my commits are spammy!
