### ISSUE TITLE
Docs: Show examples of formatter output

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#3560]
Now with the HTML formatter added in #3508, we are up to 9 built-in formatters.  Does it make sense to add a page with some description of each and maybe even example screenshots of what each formatter looks like?  I know that's one thing I looked around for when I first started using ESLint.

**Comment by nzakas** [comment]
Sounds good. Are you volunteering? :)

**Comment by IanVS** [comment]
Indeed.

**Comment by jonathanKingston** [comment]
:+1: was just looking for the same.

The main reason I was looking was:
- to quickly check the TAP output I wrote ages ago to see how it matches with the new progression there
- to see the format output by the new-ish JSON format (standardising this seems pretty important here)

**Comment by IanVS** [comment]
OK, I have a little time, I'll work on this tonight.  Do you have any particular examples you'd like to see, or will any old messages do?

**Comment by nzakas** [comment]
It probably makes sense to generate a results file with a good mix of warnings and then run that through the actual formatters when we publish the docs rather than having then static.

**Comment by IanVS** [comment]
Whatever happened to starting simple?  ;)

Alright, I'll give it a shot.

**Comment by nzakas** [comment]
This is the simple approach. Some upfront cost eliminate a ton of potential customers down the road. Plus, you'd be doing this manually anyway, I'm just saying to automate it so no one ever has to do it again.

**Comment by IanVS** [comment]
Yeah, it makes sense for sure.  I'm just whining.  :)

**Comment by IanVS** [comment]
I don't want to just take the output text and put it in a code block, because it won't look like terminal output and the formatting will be lost (e.g. stylish).  But I can't seem to find a way to redirect stdout to an image.  The html formatter could use phantom.js, but the rest are stumping me.  Any suggestions?

**Comment by nzakas** [comment]
I think you're creating unnecessary pain for yourself by not using text blocks. I think plain text output is fine, and the HTML you can just copy directly into a file.
