### ISSUE TITLE
JSX References are not recognized

### ISSUE THREAD

**Issue by mik01aj** [eslint/eslint#3622]
Using eslint `v1.3.1`, when I check this file:

```
var Component = require('Component');
module.exports = <Component foo="bar" />;
```

I get the following output:

```
$ ./node_modules/.bin/eslint -c .eslintrc a.jsx

a.jsx
  1:1  warning  Use the global form of "use strict"    strict
  1:5  error    "Component" is defined but never used  no-unused-vars

✖ 2 problems (1 error, 1 warning)
```

Where "defined but never used" is obviously wrong.

Here's my [.eslintrc](https://gist.github.com/mik01aj/3f2fc998f883b7c9ebae).

Possibly somehow related to https://github.com/babel/babel-eslint/issues/136.

**Comment by ilyavolodin** [comment]
Can you try the same exact code with the following command:
```sh
./node_modules/.bin/eslint --ext .jsx -c .eslintrc a.jsx
```

**Comment by nzakas** [comment]
You need to use `eslint-plugin-react` to pick up JSX references to identifiers.

**Comment by mik01aj** [comment]
Then it is a documentation issue. [The guide to configuring](http://eslint.org/docs/user-guide/configuring) doesn't say that I need any additional plugin for JSX to work correctly.

**Comment by ilyavolodin** [comment]
That's because this error is not a JSX error, this is React error. We do not support React out of the box, that's what `eslint-plugin-react` is for.

**Comment by mik01aj** [comment]
Thanks. This means that a link to the plugin on the docs page is not required, but it would still be helpful :)

Btw, `eslint-plugin-react` is awesome, thanks.

**Comment by lo1tuma** [comment]
@mik01aj There is a link in the `README.md`, see: https://github.com/eslint/eslint/blob/264ce6ddfc73a731cf3eba45046ae66cb3f15a7b/README.md#does-eslint-support-jsx

**Comment by mik01aj** [comment]
Ah, you're right! I'm sorry for all the hassle with this ticket.

**Comment by newswim** [comment]
I'm using the .yml config and had to add this line (surrounded with **'s):

```yml
extends: ['eslint:recommended', **'plugin:react/recommended'**]
```
