### ISSUE TITLE
eslint acts differently in local vs global install

### ISSUE THREAD

**Issue by endlist** [eslint/eslint#3624]
Running v0.24.1 through `./node_modules/.bin/eslint -c .eslintrc src`, it can't find the eslint:recommended module to extend, I get this error:

`Error: Cannot find module 'eslint-config-eslint:recommended'`

If I remove the extends, eslint will run, but the output includes errors for rules we haven't enabled on the project.  

```
src/CaseController.js
  6:22  warning  input is defined but never used   no-unused-vars
  7:35  warning  reject is defined but never used  no-unused-vars

src/consul.js
  54:40  error    resolve is already declared in the upper scope    no-shadow
  54:49  error    reject is already declared in the upper scope     no-shadow
  54:49  warning  reject is defined but never used                  no-unused-vars
  70:17  error    Expected '===' and instead saw '=='               eqeqeq
  70:17  error    Infix operators must be spaced                    space-infix-ops
  73:10  error    Don't use process.exit(); throw an error instead  no-process-exit

✖ 8 problems (5 errors, 3 warnings)
```

We have not set rules for any of the lines reporting errors.

Using the global install (i.e. `eslint -c .eslintrc src` instead), the eslint:recommended module is found and the report outputs only warnings expected by the rules we've set up in `.eslintrc` as expected:

```
src/CaseController.js
  6:23  warning  input is defined but never used   no-unused-vars
  7:36  warning  reject is defined but never used  no-unused-vars

src/consul.js
  54:50  warning  reject is defined but never used  no-unused-vars

✖ 3 problems (0 errors, 3 warnings)
```

**Comment by IanVS** [comment]
I'm guessing you have version `1.x` installed globally.  `eslint:recommended` was added in version `1.0.0`.  Also, prior to `1.x`, there were a "default" set of rules which were enabled, which is why you are seeing rules you didn't configure.  

Seems to be behaving normally to me.

**Comment by ilyavolodin** [comment]
@endlist Can you run the following command and post it's output here:
```sh
./node_modules/.bin/eslint -v
```

**Comment by endlist** [comment]
@IanVS was right, somehow the local install was only v0.24.1 but global was 1.1.0, thanks, closing
