### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#3643]
https://github.com/blog/2051-protected-branches-and-required-status-checks

Hooray! :fireworks: By protecting the master branch, we can now:

- Prevent force pushes to master
- Require all PRs to pass CI before merging

@nzakas you're the one with permissions for this.

**Comment by BYK** [comment]
:tada:

**Comment by nzakas** [comment]
Awesome. It's not rolled out yet, but will definitely do it once available!

**Comment by nzakas** [comment]
Done!
