### ISSUE TITLE
Problem with no-extra-parens 

### ISSUE THREAD

**Issue by popomore** [eslint/eslint#3653]
I use mocha for test, and always write the following code for asserting function exception.

```js
it('should throw', function() {
  (function() {
    testFunctionCall();
  }).should.throw('error message');
});
```

I configured `no-extra-parens` with `2`, and got the error (eslint version is 1.3.1).

```
4:3  error  Gratuitous parentheses around expression  no-extra-parens
```

Is there any best practice for this?

**Comment by btmills** [comment]
I just verified this on the demo. The rule already handles IIFEs, but this time the `FunctionExpression` is the `object` of a `MemberExpression`. Note that removing the parens causes a syntax error, so they really are required.

**Comment by mysticatea** [comment]
I will try to fix this.

**Comment by popomore** [comment]
Thx @mysticatea
