### ISSUE TITLE
Docs: Change "considered warnings" to "considered problems" in rule docs 

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#3676]
Split from discussion in https://github.com/eslint/eslint/pull/3574#issuecomment-137300189.

Now that the rule doc examples are configured as errors, it could be confusing to say they are "considered warnings", when the intent is only to say that they will be caught by the linter.  New wording will be:

`The following patterns are considered problems:`

and 

`The following patterns adhere to this rule:`

**Comment by nzakas** [comment]
"Adhere" is a bad word. It's hard to understand what it means in general, and it's uncommon enough that non-native English speakers will struggle with it.

I'd just stick with "The following patterns are not considered problems"
