### ISSUE TITLE
Enable `ecmaFeatures: modules` in config comment

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#3698]
For linting of the rule documentation examples, some rules are required to use `ecmaFeatures: modules`, and other rule examples are necessary to be in non-strict mode, and therefore have `modules` disabled. (see https://github.com/eslint/eslint/issues/2271#issuecomment-138689974).

One possible solution for this might be to use configuration globs once https://github.com/eslint/eslint/issues/3611 is implemented, but this would mean listing out the rules which do/don't require `modules` within the `.eslintrc`.  It would be more explicit and maintainable to be able to enable `modules` from within the example itself, with `/*eslint-ecmaFeatures modules:true*/` or similar.

My understanding is that this is difficult, because of the way that modules change the parsing of the file, but I believe this challenge was tackled and overcome by @mysticatea in https://github.com/eslint/eslint/pull/3314, and he has indicated that it may be possible to implement something similar for `modules`.

So: 

* Is this something which can be done?
* If it is possible, would it be it generally useful?

**Comment by mysticatea** [comment]
My idea is adding new environment `modules` into https://github.com/eslint/eslint/blob/master/conf/environments.js

```js
{
    ...,
    modules: {
        ecmaFeatures: {modules: true}
    }
}
```

Then we can use `/* eslint-env es6, modules */`.

I'm happy if I can do it.

**Comment by nzakas** [comment]
I think having a modules environment would be confusing because we already have ecmaFeatures.modules.

I'm kind of adverse to adding yet another type of configuration comment, but maybe what we need is a `eslint-config` comment that lets you include an entire config, then we can deprecate there others. Thoughts?

**Comment by btmills** [comment]
> maybe what we need is a eslint-config comment that lets you include an entire config, then we can deprecate there others. Thoughts?

So we could include full configs directly in the config comment? A couple examples to clarify my understanding:

```js
/* eslint-config { "env": { "mocha": true } } */
/* eslint-config { "rules": { "eqeqeq": [2, "allow-null"] } } */
/* eslint-config {
    "extends": "eslint:recommended",
    "env": {
        "browser": true
    },
    "rules": {
        "no-alert": 2
    }
} */

**Comment by nzakas** [comment]
Yup, that's what I'm thinking. Also YAML.

**Comment by mysticatea** [comment]
Sounds good to me.

**Comment by IanVS** [comment]
Is this accepted?

**Comment by gyandeeps** [comment]
do we still need this as we are removing docs code validation (https://github.com/eslint/eslint/issues/4104) ?

**Comment by nzakas** [comment]
We aren't removing validation, just the online error messages. 

This is a pretty low priority.

**Comment by adjohnson916** [comment]
I'd love to see this.

**Comment by kaicataldo** [comment]
@IanVS Doesn't look like there's been any movement on this in months. Is it time to close this?

**Comment by nzakas** [comment]
Yeah, time to close this. Almost a year open is a good indicator that we are not likely to make this change.
