### ISSUE TITLE
negated patterns in .eslintignore not working

### ISSUE THREAD

**Issue by sentience** [eslint/eslint#3707]
The project tree looks like this:

```
/home/user/my-project
├── .eslintignore
└┬─ lib
 └┬─ client
  └┬─ modules
   └┬─ some-module
    └── index.js
```

.eslintignore:

```
lib/
!lib/client/modules
```

File index.js is linted (as expected) if I run either of these commands in my project dir:

```
eslint lib/client/modules/some-module/index.js
eslint lib/client/modules
```

However, these commands do not lint index.js:

```
eslint lib/client
eslint .
```

**Comment by nzakas** [comment]
This is a limitation of the implementation. We are overhauling ignore files in 2.0.0, so we won't be making further changes until that is complete: #2365
