### ISSUE TITLE
Implement auto fix functionality for camelcase rule

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#3730]
Implement auto fix functionality for camelcase rule

**Comment by nzakas** [comment]
This one worries me a bit. Are we sure this is 100% safe to do?

**Comment by gyandeeps** [comment]
Based on the use cases inside the unit test, looks safe to me but I dont think we can guarantee full proof because of th usage of the variable or whatever it is.

**Comment by ilyavolodin** [comment]
I think I agree. `var Document_Fragment = 3` for example will be fixed in a way that will make `no-redeclare` error out.

**Comment by nzakas** [comment]
Yeah, let's not do this one - messing with identifiers is bound to get us into trouble.

**Comment by tsheaff** [comment]
I agree that this could potentially lead to errors, but getting started using --fix for my codebase, which for historical reasons has highly inconsistent use of camelCase and snake_case, would be a huge time saver, even if it broke some other rules (eg no-redeclare as mentioned), would definitely save us a lot of time and manual and even-more-error-prone work.

Is there some compromise here, to automate this "dangerously" with an understanding of the risks? Perhaps an extra CLI flag?

**Comment by not-an-aardvark** [comment]
This was discussed in https://github.com/eslint/eslint/issues/7873, but the team didn't end up coming to a consensus on whether unsafe autofixes should be allowed.

**Comment by tsheaff** [comment]
Thanks for this context @not-an-aardvark .  I'll add my thoughts to #7873
