### ISSUE TITLE
Provide a way to run Espree in tolerant mode

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#3815]
As requested in #3128 we should try to expose a way to run Espree in tolerant mode, so that when recoverable parsing errors are found, the will be tolerated.

**Comment by nzakas** [comment]
In all likelihood, we should just run in tolerant mode by default.

**Comment by ilyavolodin** [comment]
@nzakas Does this apply for Espree 3.0 at all? If not, this issue should be closed.

**Comment by nzakas** [comment]
Yup, still applies.

**Comment by alberto** [comment]
@nzakas I tried to have a look at this, but it seems `espree` throws a fatal error even in `tolerant` mode.

I get: `Parsing error: Argument name clash`

**Comment by nzakas** [comment]
Yeah, 3.0.0 currently doesn't have tolerant mode. I'm planning on adding it. If you want to take a look, try using proxyquire to stub out a response from Espree that has an `errors` an array and validate that `tolerant ` is set to true when `parse()` is called.

**Comment by kaicataldo** [comment]
Is this still a priority for the team? Curious if it should be in a milestone.

**Comment by nzakas** [comment]
Better to close for now. At some point I'll get around to add this to Espree, but no sense in tracking that here.
