### ISSUE TITLE
.eslintrc is ignored when cwd is the home directory

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#3846]
Given the following directory structure:

```
/app
├── lib
│   ├── foo.js
│   ├── .eslintrc
├── .eslintrc
```

where `/app` is the home directory of the current user AND the current working directory of the eslint process.

When I run `DEBUG=eslint:* eslint /app/lib/foo.js`, I get the following output:

```
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /app/lib/foo.js +29ms
  eslint:cli-engine Linting /app/lib/foo.js +2ms
  eslint:config Constructing config for /app/lib/foo.js +0ms
  eslint:config Using .eslintrc and package.json files +1ms
  eslint:config Loading /app/lib/.eslintrc +1ms
  eslint:config Using /app/lib/.eslintrc +91ms
  eslint:config Loading /app/package.json +0ms
  eslint:config Merging command line environment settings +7ms
  eslint:cli-engine Load plugin react +18ms
  eslint:cli-engine Linting complete in: 126ms +2ms
```

As you can see, `/app/lib/.eslintrc` is used but not `/app/.eslintrc`. This is because `.eslintrc` files in the home directory [are always ignored](https://github.com/eslint/eslint/blob/9f11ba4313a05aaeae71dac054723ff8477b369b/lib/config.js#L304-L307) when retrieving the local config for a given file. The [documentation](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) says that this should only happen in the absence of ANY configuration.

------

When I remove `/app/lib/.eslintrc` then I get the following output:

```
DEBUG=eslint:* ./node_modules/.bin/eslint /app/lib/foo.js
  eslint:cli Running on files +0ms
  eslint:cli-engine Processing /app/lib/foo.js +35ms
  eslint:cli-engine Linting /app/lib/foo.js +2ms
  eslint:config Constructing config for /app/lib/foo.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /app/package.json +1ms
  eslint:config Using personal config +10ms
  eslint:config Merging command line environment settings +97ms
  eslint:cli-engine Load plugin react +18ms
  eslint:cli-engine Linting complete in: 136ms +2ms
```

Now the personal config was used because no other `.eslintrc` was found, which is not correct because there is a config file in the current working directory.

-----

My current workaround is to rename the `/app/.eslintrc` file to `/app/eslint-config` and load it explicitly via the `-c` CLI flag:

```
$ eslint -c eslint-config /app/lib/foo.js
```

**Comment by gyandeeps** [comment]
Questions:
* What version of eslint are you using?
* Do you have `root: true` in any `.eslintrc` file?

**Comment by lo1tuma** [comment]
ESLint versin: `1.4.3`
`root` is not set at all for my examples above, but I’ve tried it and it doesn’t have any impact.

**Comment by lo1tuma** [comment]
FWIW: the workaround mentioned above doesn’t work if you have multiple `.eslintrc` files. Putting the content of the `/app/.eslintrc` file into the  `package.json` works.

**Comment by nzakas** [comment]
Sounds like we need an exception if the cwd is the home directory?

**Comment by lo1tuma** [comment]
Yes, I think an exception is needed to fix this.
