### ISSUE TITLE
Using power-assert in our tests.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#3853]

**Comment by platinumazure** [comment]
Just out of curiosity, why?

**Comment by mysticatea** [comment]
I like `power-assert`'s philosophy.
And this modification doesn't break behaviors of ESLint and RuleTester.

`power-assert` is simple and powerful.
The API which users must learn is only one: `assert(expression);`.

Conventional `assert(expression)` shows useless information (only `true` or `false`), so most assertion libraries have many APIs to show useful debug information. So we must learn those.
On the other hand, `assert(expression)` of `power-assert` shows useful debug information. One API (stable absolutely) and many information.

**Comment by nzakas** [comment]
@mysticatea do you still plan on doing this?

**Comment by mysticatea** [comment]
I'm still interested in this, but I have low priority.
Please feel free to close this... sorry.

**Comment by nzakas** [comment]
OK, thanks.
