### ISSUE TITLE
Curly braces around inner `if`

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#3856]
I'm linting this code:

	if (true) {
		if (false)
			console.log(1)
	} else if (true)
		console.log(2)

With this package.json:

	{
		"eslintConfig": {
			"rules": {
				"curly": [ 1, "multi" ]
			}
		}
	}

And I get this output:

	$ node_modules/eslint/bin/eslint.js file.js 

	/home/andy/mason3/ESLINT/file.js
	  1:1  warning  Unnecessary { after 'if' condition  curly

	✖ 1 problem (0 errors, 1 warning)

Without the curly braces, running the code will log '2'.
With them, it will not log anything.

I've tested this with eslint 1.5.0.

**Comment by gyandeeps** [comment]
I dont think I completely understand what you are reporting here, if there is a bug can you please mention what is the current output and what do you expect the output to be?

**Comment by michaelficarra** [comment]
@gyandeeps You can't remove the curlies without changing the program due to how dangling else is parsed. The `curly` rule should have an exception for this case.

**Comment by mysticatea** [comment]
I will try to fix this.
