### ISSUE TITLE
Proposal: combine semi, no-extra-semi

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3885]
I've been looking at these rules for auto-fixing, and came to the conclusion that it might be best to combine them. In the case of `semi`, we need to know what kind of spacing rules should be applied when a semicolon is inserted in order to avoid triggering a warning from `semi-spacing`. Since rules don't know about each other, we can't do that right now.

If we combined the rules, though, all the necessary information would be in one place and that would make auto-fixing much easier.

Thoughts?

**Comment by ilyavolodin** [comment]
I'm not sure I like combining rules to fix our internal shortcomings. While I think it's fine to combine semi and no-extra-semi, I'm not sold on semi-spacing. That rule is aimed at quite a different thing in my mind.

**Comment by nzakas** [comment]
We've done this before when we had three rules related to strict mode, and also with the two comment spacing rules. I think this also nicely encapsulates everything related to semicolons in one rule, which I'd argue makes it easier on users who, right now, need to search through and fund three rules.

I'm open to other ideas. The goal here is to find a way to allow auto-fixing for all three rules. Do you have an alternative?

**Comment by lo1tuma** [comment]
I agree with @ilyavolodin. If autofixing is the only reason to combine these rules then you also need to include the `max-len` rule,because adding whitespace could conflict with this rule.

**Comment by nzakas** [comment]
`max-len` is a special case that I'm not too worried about right now. I have some theories on how to address that, just need to try prototyping to see if it works.

I'm not sure autofixing is the only reason to combine the rules, but it's definitely one reason. I'm of the mind lately that having so many separate rules related to the same thing is doing us more harm than good. With almost 200 rules, it's really hard for people to find what they want. The most obvious solution is to reduce the number of rules, and combining rules that are related to one another is an obvious way to do that.

As I mentioned, I'm open to other alternatives.

**Comment by lo1tuma** [comment]
The problem I see with these particular rules is that one could be interested in disallowing extra semicolons but doesn’t even care about spacing. If you combine them you can only enforce or disallow whitespace on certain locations but you can’t avoid the whitespace check completely.

**Comment by ilyavolodin** [comment]
@nzakas I think my alternative proposal would be to combine `semi` and `no-extra-semi` but keep `semi-spacing` separate. I know it doesn't solve your problem with autofixing, but I'm just not 100% sure about combining whitespace rule with general code syntax rule.
In general, I think if we want to be able to get the full power of autofixing out, we need to do one of the following things:
* Exposed configuration to all rules (bad idea, since it will couple rule's code)
* Do autofixing in multiple passes (have `semi` insert semicolons first then have `semi-spacing` add/remove spacing)
* Do a hybrid of multipass autofixing and what we are doing now (queue up fixes, but have other rules verify and change queued fixes, no idea how to implement this).

**Comment by mysticatea** [comment]
I guess there are problems similar to this in:

- no-var and prefer-const
- prefer-allow-callback and arrow-spacing.
- no-multi-spaces and key-spacing with align.
- brace-style and indent.
- etc...

So I think doing in multi passes is good idea.

**Comment by nzakas** [comment]
In general, I don't see a path towards nonwhitespace auto-fixing in the near future. Too hairy, so let's focus on solving do it whitespace fixes right now.

@ilyavolodin I don't think you realize the complexity of doing two passes. The only way to do that is to reparse the code and run ESLint again, which will basically double the time it takes. We have zero optimizations that can be made because any autofix can trigger any other warning, so we can't even disable some rules on a second pass. 

So, I really don't see a second pass as a rational option to this problem.

One solution is to only do whitespace rules and remove semi, eqeqeq from auto-fixing.

**Comment by alberto** [comment]
An alternative would be to be able to read the configuration of other rules.

**Comment by nzakas** [comment]
Yeah, I've been thinking about that. The hairy part of that is that we'd be creating a relationship between rules that doesn't exist right now. Maybe that's OK if it's just configuration data, but it's a tenuous situation. For instance, what if you don't have `semi-spacing` enabled but `semi` relies on it for spacing information? What happens then?

**Comment by ilyavolodin** [comment]
I think this might lead to a lot of complex cross-relationships. I'm not sure that's a good idea. Maybe if instead of exposing rule configuration, we create some global object that can maintain currently enabled style for all of the rules that individual rules can query?

**Comment by alberto** [comment]
@nzakas It would create less of a relationship than merging the rules. :) If you don't have `semi-spacing` enabled, you can use a default. In this case, the rule defaults seems the obvious choice: `{"before": false, "after": true}`.

**Comment by nzakas** [comment]
@ilyavolodin that's essentially the same thing. :) We'd still be talking `context.getRuleConfig("semi")`, or some such thing. The underlying implementation doesn't really matter, we'd still be stuck with having rules need to specify which other rule's config to read. 

@alberto Combining rules solves the problem because there are no cross-rule dependencies

**Comment by alberto** [comment]
@nzakas yes, I was talking about a more general solution, not just for `semi`, without multipass.

**Comment by SpadeAceman** [comment]
> With almost 200 rules, it's really hard for people to find what they want. The most obvious solution is to reduce the number of rules, and combining rules that are related to one another is an obvious way to do that.

:+1: I'm definitely in favor of combining related rules when it makes sense, particularly if those rules step on one another's toes in fundamental ways.

Rules depending on the configuration of other rules could get dicey fairly quickly.

> For instance, what if you don't have `semi-spacing` enabled but `semi` relies on it for spacing information? What happens then?

We *could* have `semi` to default to something on its own, if `semi-spacing` isn't active – not impossible, but these kinds of latent cross-rule side-effects could escalate in a bad way. Not only would people need to understand how to use the almost 200 rules currently available, but they'd also need to be aware of the side-effects resulting from using certain rules together. :scream:

**Comment by nzakas** [comment]
Forgot about this - should we still combine `semi` and `no-extra-semi` for 2.0.0. Thoughts?

**Comment by mysticatea** [comment]
I'm OK to combine.

**Comment by ilyavolodin** [comment]
I see no problem combining those two. However, `no-extra-semi` is currently auto fixable, and `semi` is not. We will have to either support fixing both, or none.

**Comment by nzakas** [comment]
Don't you mean `semi` is fixable but `no-extra-semi` is not?

**Comment by ilyavolodin** [comment]
Actually, both seems to be fixable, it's just `semi` documentation doesn't mention is (but Readme.md does).

**Comment by nzakas** [comment]
Working on this.

**Comment by nzakas** [comment]
Eh, once I got in here, I found that this is a bit complicated. There's a pretty difference between enforcing or disallowing semicolons and flagging unnecessary semicolons, so I don't think merging the rules actually makes sense. So, closing.
