### ISSUE TITLE
Implement auto fix functionality for prefer-const rule

### ISSUE THREAD

**Issue by Swatinem** [eslint/eslint#3899]
It would be nice if eslint could just replace my `var` or `let`s with `const`s. There might be some special handling regarding `one-var` rule though, so I don’t think it might be that straight forward.

**Comment by ilyavolodin** [comment]
We are in early stages of testing autofixing for now. And we are only focusing on whitespace rules for now. We might get to other rules later.

**Comment by nzakas** [comment]
We won't be able to do this with auto-fixing. Changes like this could affect many other rules, so it's an unsafe fix.
