### ISSUE TITLE
`no-mixed-requires` uses boolean option [$10]

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#3922]
[no-mixed-requires](http://eslint.org/docs/rules/no-mixed-requires) is the only rule with a boolean option.  Its schema is:

```js
module.exports.schema = [
    {
        "type": "boolean"
    }
];
```

Normally, when there is a need for a boolean, we wrap it in an object.  Therefore, I propose a breaking change for `2.0.0` to change the schema to:

```js
module.exports.schema = [
    {
        "type": "object",
        "properties": {
            "grouping": {
                "type": "boolean"
            }
        },
        "additionalProperties": false
    }
];
```

In the meantime before `2.0.0`, we could deprecate the old method and encourage the object style.  The schema would then be :

```js
module.exports.schema = [
    {
        "oneOf": [
            {
                "type": "boolean"
            },
            {
                "type": "object",
                "properties": {
                    "grouping": {
                        "type": "boolean"
                    }
                },
                "additionalProperties": false
            }
        ]
    }
];
```

**Comment by nzakas** [comment]
Good idea, though I'd rather support both Boolean and object going forward. I don't think it's worth breaking things.

**Comment by IanVS** [comment]
OK, I thought in the past you had said you didn't like configurations like `[2, true]` because of the ambiguity of what `true` represents in this case.  It's not clear that this turns on the grouping option:

```json
rules: {
    "no-mixed-requires": [2, true]
}
```

That thinking, combined with the fact that it's the only such rule using this format, were what led me to suggest a breaking change.

**Comment by nzakas** [comment]
Yup, I have said that, and you'll note I didn't object to this change. However, I don't think it's important enough to warrant forcing everyone to update their configs. Breaking changes are always a last resort, and if there's ever a way to be backwards compatible, we need to take that option.

**Comment by IanVS** [comment]
OK, I misunderstood what you meant by supporting boolean moving forward. You mean just in this one case, not starting to support for all rules.

This makes sense, thanks.

**Comment by nzakas** [comment]
Yes, sorry I wasn't clear. We definitely don't want to introduce new rules that do this.
