### ISSUE TITLE
Add load performance check inside perf function

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#3994]
Current perf function inside Makefile calculates the runtime performance of eslint. I want to add load performance of eslint to it so that it would help us determine the impact whenever new dependencies gets added to the project.

We recently improved our load performance: https://github.com/eslint/eslint/pull/3931

We can use [load-perf](https://github.com/gyandeeps/load-perf) module by consuming its nodejs api.

What do you think @eslint/eslint-team ?

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
:+1:

**Comment by nzakas** [comment]
:+1:
