### ISSUE TITLE
`space-in-parens` warns multiline with a comment.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#3996]
When there is a comment after an opening parenthesis, this rule warns spacing which is between the parenthesis and the comment.
This behavior is different from other spacing rules (`block-spacing`, `object-curly-spacing`, `computed-property-spacing`, `array-bracket-spacing`)
Is this intended behavior?

```js
/* eslint space-in-parens: 2 */
foobar( // some comment
    param,
    args,
    variables
);
```

v1.5.1

![image](https://cloud.githubusercontent.com/assets/1937871/10214022/055945cc-684f-11e5-8d5d-51febcc4dc28.png)

**Comment by nzakas** [comment]
I think that's a bug.

**Comment by mysticatea** [comment]
Oh... this rule is text-based, not token-based.

**Comment by nzakas** [comment]
It is OK to rewrite with tokens.

**Comment by alberto** [comment]
@mysticatea are you working on this?

**Comment by mysticatea** [comment]
No, sorry, I have not made enough time yet for this....

**Comment by alberto** [comment]
Ok, then I will.

**Comment by jareware** [comment]
Just ran into this as well, great that it's being addressed. :+1:

**Comment by mysticatea** [comment]
@alberto Thank you very much!
