### ISSUE TITLE
Remove JSX code fences

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4020]
The `jsx-quotes` rule documentation has code fences in it using `jsx`. This is an invalid code fence and needs to be changed as it breaks the Jekyll site generation. Maybe it should be `html` instead?

@lo1tuma

**Comment by michaelficarra** [comment]
If Jekyll doesn't support it, don't highlight it. It's certainly not HTML.

**Comment by lo1tuma** [comment]
I agree with @michaelficarra

**Comment by alberto** [comment]
jekyll doesn't support it out of the box. I couldn't even find a jsx lexer.
even if there was one, I don't think you can make it work on github pages

**Comment by btmills** [comment]
[Linguist detects JSX](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1580). I'd say keep it.

**Comment by nzakas** [comment]
I think I'm not being clear: this broke the site, keeping it is not an option. I had to manually go in and remove it to get the site to generate. 

The actual examples using it contained only HTML. I actually don't care if it's tagged as HTML or not, but it can't be tagged as JSX without breaking site generation.

**Comment by btmills** [comment]
Working on this. Going with HTML so we at least have some highlighting unless someone objects.
