### ISSUE TITLE
Rule Proposal: `prefer-rest-params`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#4108]
There is rest parameters in ES2015 features.
We can use that instead of the `arguments` variable.
The `arguments` does not have methods of `Array.prototype`, so it's inconvenience a bit.

So I propose a rule that suggests a use of rest parameters instead of the implicit `arguments` variable.

This rule considers the following patterns are problem.

```js
function foo() {
    console.log(arguments);
}

function foo(action) {
    var args = [].slice.call(arguments, 1);
    action.apply(null, args);
}
```

This rule considers the following patterns are not problem.

```js
function foo(...args) {
    console.log(args);
}

function foo(action, ...args) {
    action.apply(null, args); // or `action(...args)`, related with the `prefer-spread` rule.
}

// Note: the implicit arguments can be overwritten.
function foo(arguments) {
    console.log(arguments); // This is the first argument.
}
function foo() {
    var arguments = 0;
    console.log(arguments); // This is a local variable.
}
```

----

I guessed this rule merely checks whether or not the variable of `arguments` has any references.
It's similar to https://github.com/eslint/eslint/pull/4107/files#diff-7b84fea30db343f87eb7fda7ecaac74eR173

**Comment by nzakas** [comment]
Sounds good!

**Comment by alberto** [comment]
@mysticatea are you working on this?

**Comment by mysticatea** [comment]
I'm working on this.
