### ISSUE TITLE
Avoid magic numbers in rule options

### ISSUE THREAD

**Issue by remitbri** [eslint/eslint#4182]
if 
 - the configuration files are js files
 - "no-magic-numbers" is set to 2
 - ESlint version is 1.7.1

then the configuration of some rules flag an error (_"No magic number: …"_). So far, in my case:
 - complexity
 - max-depth
 - max-len
 - max-params
 - max-statements
 - max-nested-callbacks

The reason is these rules expect numbers in their configuration, e.g.
 `"max-nested-callbacks" : [2, 3]`
"3" is the problem, "2" is not since it's in the default list of the "no-magic-numbers" rule.

This is surely nitpicking, but wouldn't it be the occasion to have a proper variable name, eg
`"max-nested-callbacks" : [2, {“maximum" : 3}]`
`"complexity"  : [2, {"maximum" : 5}]`
etc ?

**Comment by hzoo** [comment]
If i'm not mistaken are you saying you are running `no-magic-number` on your `.eslintrc`? I think it would be much easier to either add exceptions to the the list of defaults, add a `/*eslint-disable no-magic-number */` comment for the config, or not run eslint/that rule on your config file since it should already has validation.

I don't think we would want to change the rule format just for this particular rule?

**Comment by remitbri** [comment]
Changing the rule format just for this particular rule is a bit much, I agree, that's why I mentioned nitpicking ;) But at the same time, it would add some consistency in the setting/configuration of rules.
Eg, we already have `"no-multiple-empty-lines" : [0, {"max" : 2}]`, which imho is a good thing, and is more clear than `"no-multiple-empty-lines" : [0, 2]`.

To sum up : if a rule needs to be configured to more than just being set to 0/1/2, then it should be to [0/1/2, {variable : value}]. The `no-magic-number` is just a pretext :)

**Comment by nzakas** [comment]
We do that now. These are all old rules, made before we made that change. I'm not opposed to adding a second way for these rules to be configured, but unless you're volunteering to do so, is unlikely this would get done anytime soon.

**Comment by remitbri** [comment]
@nzakas On top of your head, which rule underwent the same change/dual configuration? So that I can have a look and understand how it's done.

**Comment by hzoo** [comment]
Oh ok, :+1: to add the extra options to be more consistent. I'm not sure any rules were changed to have multiple configs - more that new rules use the config you suggested? You'll probably just have to compare the different kinds unless someone can find one like you are asking.

**Comment by nzakas** [comment]
Yeah, I can't recall off the top of my head any rules we did this for. In general, we don't go back and update stable rules unless someone has a problem or we need to add a new option. At that point, we re-evaluate if we see things that don't make sense.

**Comment by IanVS** [comment]
For dual configuration (where it is possible to use either a string or an object, for example), you can look at `one-var`.  There are a few rules which do this, you can search the rules folder for `oneOf`, which is how it is handled in the schema.

**Comment by IanVS** [comment]
@remitbri is this something you'd like to work on?

**Comment by remitbri** [comment]
Theoretically, yes. Practically/honestly: I don't quite have the time yet. 
If I finally find it, I'll ask first if anyone's already on the issue.

**Comment by bsbeeks** [comment]
Thought I'd take a stab at this one. See :point_up:
