### ISSUE TITLE
node is mandatory inside context.report

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#4220]
Based on the current documentation of [context.report()](http://eslint.org/docs/developer-guide/working-with-rules#contextreport), `node` is optional but if you don't supply it, it will throw an error.

Reference of code where the error comes from: https://github.com/eslint/eslint/blob/master/lib/eslint.js#L849

 Stackoverflow ref: http://stackoverflow.com/questions/33233372/custom-rule-checking-source-code/33250106

I am not sure if the docs need a fix or the code?

**Comment by ilyavolodin** [comment]
I'd say docs should be updated. We need either node or location information.

**Comment by gyandeeps** [comment]
@ilyavolodin If i read your second statement that tells me `node` is optional.
with that being said, we need code update, right?

**Comment by nzakas** [comment]
`node` is optional if `loc` is provided.

**Comment by nzakas** [comment]
We should probably throw an error if one of the two isn't provided.

**Comment by platinumazure** [comment]
How does this play with RuleTester node type assertions? Do we get the node from the location?

**Comment by ilyavolodin** [comment]
We do not. If node is not provided, we can't verify node type in RuleTester

**Comment by nzakas** [comment]
We check node type due to legacy reasons, but it's not very useful IMHO.

**Comment by platinumazure** [comment]
Anyone on this?

**Comment by ilyavolodin** [comment]
Nope. I think it's open for implementation

**Comment by platinumazure** [comment]
Just to make sure, the goal is to require either node or loc, throw if neither is provided, and ensure the docs say the same?

**Comment by ilyavolodin** [comment]
That's my understanding - yes.

**Comment by nzakas** [comment]
Yup!

**Comment by platinumazure** [comment]
Okay-- I'll take a crack at it this weekend.
