### ISSUE TITLE
Parse error on defaulting arrow functions 

### ISSUE THREAD

**Issue by AccaliaDeElementia** [eslint/eslint#4223]
Using the example code below: 

```
'use strict';

function example1 (fn) {
	fn = fn || function () {};
}

function example2 (fn) {
	const noop = () => undefined;
	fn = fn || noop;
}

function example3 (fn) {
	fn = fn || (() => undefined);
}

function brokenExample (fn) {
	fn = fn || () => undefined;
}
```

ESlint generates a parse error on line 17 (inside the `brokenExample` function) as seen below. Node version 0.12 and 4.1 are prefectly happy with the syntax however, see console output below

```
accalia_de_elementia@devbox:~/workspace $ eslint -v                                                                                                                                          
v1.7.1
accalia_de_elementia@devbox:~/workspace $ eslint example.js 

/home/ubuntu/workspace/example.js
  17:15  error  Parsing error: Unexpected token )

✖ 1 problem (1 error, 0 warnings)

accalia_de_elementia@devbox:~/workspace $ node -v
v0.12.7
accalia_de_elementia@devbox:~/workspace $ node --harmony example.js && echo ok!
ok!
accalia_de_elementia@devbox:~/workspace $ nvm use 4
Now using node v4.1.2
accalia_de_elementia@devbox:~/workspace $ node -v
v4.1.2
accalia_de_elementia@devbox:~/workspace $ node example.js && echo ok!
ok!
accalia_de_elementia@devbox:~/workspace $ 
```

---
Updated, wrapping the anonymous function in parens causes ESlint to stop generating the parse error as well.

**Comment by mysticatea** [comment]
It's according to the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-expressions

`ArrowFunction` is an `AssignmentExpression`, so it cannot become a operand of `LogicalORExpression`. Parentheses are needed.
On the other hand, `FunctionExpression` is an `PrimaryExpression`, so it can become a operand of `LogicalORExpression`.

Related: https://code.google.com/p/v8/issues/detail?id=4211
