### ISSUE TITLE
`eslint.verify` does not prepare config if SourceCode is used

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4230]
When a `SourceCode` object is passed into `eslint.verify`, `prepareConfig` is not executed, causing an error like:

```
/home/ian/Local_code/eslint/eslint/lib/eslint.js:721
                    throw ex;
                    ^

TypeError: Error while loading rule 'accessor-pairs': Object prototype may only be an Object or null: undefined
    at Function.create (native)
    at new RuleContext (/home/ian/Local_code/eslint/eslint/lib/rule-context.js:101:23)
    at /home/ian/Local_code/eslint/eslint/lib/eslint.js:707:40
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/home/ian/Local_code/eslint/eslint/lib/eslint.js:686:16)
```

I believe the lines https://github.com/eslint/eslint/blob/master/lib/eslint.js#L660-L661 should be moved outside of the if block they are currently in.

**Comment by IanVS** [comment]
I can submit a PR if accepted.

**Comment by nzakas** [comment]
Can you explain the use case where you found this? I'm assuming that passing `SourceCode` isn't universally broken and there's something special about your case.

**Comment by IanVS** [comment]
I am verifying SourceCode as part of the autoconfig functionality, and providing only rules in the config.  As is,  ESLint does not add an empty ecmaFeatures object unless raw text is passed in.  I believe it to be universally broken, but perhaps the feature is not used much, which is why we have not seen reports up to now.

**Comment by nzakas** [comment]
Thanks!

**Comment by IanVS** [comment]
This is based on the docs and will give the error I mentioned above:

```js
var linter = require("eslint").linter;

var messages = linter.verify("var foo;", {
    rules: { semi: 2 }
});

var code = linter.getSourceCode();

var codeMessages = linter.verify(code, {
    rules: { semi: 2 }
});
```
