### ISSUE TITLE
Unable to extend local module from default/main file

### ISSUE THREAD

**Issue by pdehaan** [eslint/eslint#4263]
I created a dummy eslint-config-* file (https://github.com/pdehaan/eslint-config-extends-test) which extends **eslint-config-node-style-guide** and attempts to bundle the node-style-guide dependency so it doesn't need to be installed with each other repo.

As you can see, the _index.json_ file is the `main` file in the package.json file, and it extends the ./_base.js file:
```js
{
  "extends": "./_base.js",
  "rules": {
    "quotes": [2, "double"]
  }
}
```

When I try and use this custom config in one of my projects, I get the following error:

> "Error: Cannot find module 'eslint-config-_base.js'"

Where my package.json includes the following:
```js
  "devDependencies": {
    "eslint": "^1.7.3",
    "eslint-config-extends-test": "pdehaan/eslint-config-extends-test"
  }
```

and my project's .eslintrc file uses my custom config:
```js
{
  "extends": "extends-test"
}
```

---

Full error stack from npm:
```
➜  eslint-config-extends-test_client  npm test

> eslint-config-extends-test_client@1.0.0 test /Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client
> eslint .


/Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:213
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-_base.js'
Referenced from: extends-test
Referenced from: /Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/.eslintrc
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at readConfigFromFile (/Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:176:22)
    at /Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:191:36)
    at /Users/pdehaan/dev/tmp/del/eslint-config-extends-test_client/node_modules/eslint/lib/config.js:207:46
npm ERR! Test failed.  See above for more details.
```

**Comment by pdehaan** [comment]
The workaround is a bit weird, and not immediately obvious (to me, but I'm a bit dim)...

Instead of using something like "index.json", convert to "index.js" (in your custom config) and then `module.exports` the JSON config object. Then you need to pass a fully qualified path to the _base.js config file, using `path.join(__dirname, '_base.js')`, as seen in the following snippet:

```js
var pathJoin = require('path').join;

module.exports = {
  "extends": pathJoin(__dirname, "_base.js"),
  "rules": {
    "quotes": [2, "double"]
  }
};
```

**Comment by pdehaan** [comment]
Basically we want to share a custom ESLint config between 10-20 repos where the custom config extends **eslint-config-node-style-guide**, but we don't want to have to install the **eslint-config-node-style-guide** module as a dependency in each of those projects. Ideally we'd just be able to bundle the eslint-config-node-style-guide dependency in our custom config and only need to install **eslint** and **eslint-config-extends-test**.

**Comment by nzakas** [comment]
What version are you using?

**Comment by pdehaan** [comment]
@nzakas eslint@1.7.3

**Comment by pdehaan** [comment]
Another, possibly prettier, solution/workaround may be something like `require.resolve()` (instead of `path.join()` and `__dirname`):
```js
module.exports = {
  "extends": require.resolve('eslint-config-node-style-guide'),
  "rules": {
    "quotes": [2, "double"]
  }
};
```

**Comment by gyandeeps** [comment]
Results of the investigation:
If you directly reference a file inside the projects `.eslintrc` file then it works fine.
```js
{
    "extends": "./config.js"
}
```

Now in case where you extend to a package and then inside that package you further extend to a file, then it cause the above error.

So your project `.eslintrc`:
```js
{
    "extends": "ideal"
}
```

and inside ideal's js file
```js
module.exports = {
    "extends": "./config1.js",
    "rules": []
};
```

this where you will get an error with`config1` in reference.

**Comment by nzakas** [comment]
@pdehaan why don't you just:

```js
var base = require("eslint-config-node-style-guide");

// make whatever changes you want
base.rules.semi = 0;

module.exports = base;
```

**Comment by pdehaan** [comment]
@nzakas I thought of that, but using JSON/YAML syntax felt a bit more consistent.
https://github.com/gulpjs/eslint-config-gulp/pull/6#issuecomment-150493224

Plus didn't know if it'd get awkward if I wanted to push new `extends` or whatever, where `extends` can be `undefined`, a string, or an array  and I'd be adding too much logic.

**Comment by nzakas** [comment]
We can make a (breaking) change to update where extends is calculated from, but I'd still encourage you to use the method I described. That lets you be in complete control of his rules are change and merged, and also makes debugging easier.

**Comment by t128** [comment]
@nzakas i think it's not "nice" to put data (your rules) into some other modules

+1 for a fix of this bug

**Comment by nzakas** [comment]
@t128 you can always clone the object and modify that if you want to be "nice".

**Comment by pdehaan** [comment]
@nzakas Actually, your solution works with simple modules such as **eslint-config-node-style-guide** which is basically a single JSON file of rules.
But I just tried converting one of our other projects and it broke since **eslint-config-airbnb** uses a complex web of nested extends and rules files.

In my **eslint-config-blah** custom rules module, I extend **airbnb/base** using the following:
```js
var base = require('eslint-config-airbnb/base');

base.extends.unshift('eslint:recommended');

base.rules['comma-dangle'] = [2, 'never'];
base.rules['indent'] = [2, 2, {'SwitchCase': 1}];
base.rules['no-console'] = 1;
base.rules['no-use-before-define'] = [2, 'nofunc'];

module.exports = base;
```

Which seems to correctly output the following config:
```js
{ extends:
   [ 'eslint:recommended',
     'eslint-config-airbnb/legacy',
     'eslint-config-airbnb/rules/es6' ],
  parser: 'babel-eslint',
  rules:
   { 'comma-dangle': [ 2, 'never' ],
     indent: [ 2, 2, [Object] ],
     'no-console': 1,
     'no-use-before-define': [ 2, 'nofunc' ] } }
```

But when I try and run my `$ gulp lint` task, I get the following error because it can no longer resolve those **eslint-config-airbnb** references since they were specified as a dependency in my **eslint-config-blah** module, and not declared as a dependency of my main project:
```
Error: Cannot find module 'eslint-config-airbnb/rules/es6'
Referenced from: idea-town
Referenced from: /Users/pdehaan/dev/github/idea-town/.eslintrc
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at readConfigFromFile (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:176:22)
    at /Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:191:36)
    at /Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:191:36)
    at getLocalConfig (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:321:23)
    at Config.getConfig (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:416:22)
    at processText (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:197:27)
    at CLIEngine.executeOnText (/Users/pdehaan/dev/github/idea-town/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:678:26)
```

So it looks like if my custom ESLint config extends **eslint-config-airbnb** style guide, I'll need to include that dependency in each of my projects as well, and can't hide that as an implementation detail in my module.

**Comment by nzakas** [comment]
@pdehaan that's actually a different issue. This issue is about file paths, what you're talking about is module resolution.

**Comment by iamstarkov** [comment]
i can see, that issue has been accepted, so can i expect in near future eslint support for self-contained presets like in babel now?

**Comment by platinumazure** [comment]
Issue being accepted means ESLint team agrees it should be implemented, but
it doesn't guarantee that anyone is on it right that second. Sometimes an
issue will be accepted but the core team might not have the resources to do
it themselves; in that case, they will accept pull requests from interested
contributors.

Are you interested in writing a pull request for this?

**Comment by iamstarkov** [comment]
@platinumazure I am. Is there any intro into eslint inner architecture to get started?

**Comment by ilyavolodin** [comment]
@iamstarkov Yes, intro is located [here](http://eslint.org/docs/developer-guide/architecture)

**Comment by iamstarkov** [comment]
yay, will take a look

**Comment by nzakas** [comment]
I'm refactoring how this works right now.

**Comment by iamstarkov** [comment]
@nzakas should I wait for a while, then?

**Comment by nzakas** [comment]
Yes. I actually found myself right in the middle of this issue today, and it looks like extending a file was always intended to work relative to the config file. There's even a comment saying that's how it works, so this is definitely a bug rather than a breaking change/enhancement.

I'll see if I can fix it while I'm in here.

**Comment by nzakas** [comment]
Just tested with my current work and it seems that this bug will be fixed by it.

**Comment by iamstarkov** [comment]
@nzakas thanks for fixes. is it going to be published soon?

**Comment by nzakas** [comment]
This Friday. We do releases every other week

**Comment by iamstarkov** [comment]
@nzakas thank you for release!

**Comment by chapinkapa** [comment]
I am still getting this error.

```
Error: Cannot read config package: eslint-config-require.resolve('eslint-config-airbnb')
Error: Cannot find module 'eslint-config-require.resolve('eslint-config-airbnb')'
Referenced from: /Users/alexander/private/interview/survey/.eslintrc
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadPackage (/usr/local/var/nvm/versions/node/v4.2.1/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/var/nvm/versions/node/v4.2.1/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/var/nvm/versions/node/v4.2.1/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/var/nvm/versions/node/v4.2.1/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/var/nvm/versions/node/v4.2.1/lib/node_modules/eslint/lib/config/config-file.js:309:28)
```

**Comment by chpio** [comment]
@chapinkapa 
> that's actually a different issue. This issue is about file paths, what you're talking about is module resolution.

**Comment by chapinkapa** [comment]
I have tried with an absolute path to the module also. It throws the same issue.

**Comment by nzakas** [comment]
Please open a new issue and describe your problem.

**Comment by EvanCarroll** [comment]
Same problem as @chapinkapa .. The airbnb docs say to do just that..

```text
$ cat .eslintrc
{
        extends: "airbnb/base"
}
```

Yet, when I run it I'm getting

```text
ecarroll@ecarroll-x200s:~/code/samp-frontend$ eslint lib/foo/app.js                    
/usr/local/lib/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-airbnb/base
Error: Cannot find module 'eslint-config-airbnb/base'
Referenced from: /home/ecarroll/code/samp-frontend/.eslintrc.json
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:309:28)

```

**Comment by chapinkapa** [comment]
@EvanCarroll I can't remember how I got this to work. Looks like I am just extending "airbnb".

Here is an example of how I got it working:
https://github.com/chapinkapa/discussion/blob/master/.eslintrc

**Comment by EvanCarroll** [comment]
I can get it to work. I just have to do this..

```javascript
{                                                         
  "extends": "./node_modules/eslint-config-airbnb/base.js"
}                                                         
```

There is something *seriously* wrong with module name resolution and I want to know how it works for anyone...

**Comment by saltire** [comment]
Note on module resolution: if you have eslint installed globally, you need to have the eslint config module (and its peer dependencies) installed globally as well.
If you have the eslint config installed to the local folder, make sure you are running the locally installed eslint binary.
