### ISSUE TITLE
`Quotes` rule has no default

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4270]
Currently, it is possible to set the rule to `2` (error), and it will do nothing unless a quote type is also provided.  As it says in the docs:  

> The first option is "double", "single" or "backtick" for double-quotes, single-quotes or backticks respectively. There is no default.

I think generally we try to provide some kind of default for all rules, and while I really don't care which type is chosen for a default, it seems like there should at least be one.  So, that raises two questions:

1. Should a default style be added?
2. If so, what style should it be?

**Comment by michaelficarra** [comment]
We should just change the schema to not allow that particular configuration. A default would not make sense for this rule.

**Comment by ilyavolodin** [comment]
@michaelficarra Default would make this rule opinionated, but I think it does make sense. Having a rule that does absolutely nothing it you forgot to specify an option is pretty strange. In all honesty default for this rule should probably be autoconfig (as in, count all types of quotes, take larges number as a default and report the rest).
Maybe modifying schema to require a parameter is not a bad option either.

**Comment by michaelficarra** [comment]
> Having a rule that does absolutely nothing it you forgot to specify an option is pretty strange.

Of course, which is why I suggested it fail immediately.

**Comment by IanVS** [comment]
Is it worth making this rule the only one which cannot be set with only a severity, only to avoid choosing a default?  There are other rules like `indent` which could be considered being opinionated in their default, why should this one be treated any differently?

**Comment by nzakas** [comment]
Does the schema check the file or just the finished options? If the former, then there's no way to update the schema to make this work because you can change just the severity of the rule at any point and inherit the options from another file.

If we can't do it schema wise, let's just set to double by default. We have a 50/50 chance that it's correct, and people can always change it if they want.

**Comment by IanVS** [comment]
I was wrong, it is already defaulting to double quotes.  The docs just need to be updated to reflect this.
