### ISSUE TITLE
error PropTypes must be placed after render …?

### ISSUE THREAD

**Issue by maketroli** [eslint/eslint#4272]
All I can say is: WHAT?

How this error is asking me to put PropTypes after the render method ?

Look at the error

    src/components/ChatForm/index.js
       7:3   error  PropTypes must be placed after render                       react/sort-comp
      44:16  error  'onAddMessage' is missing in props validation for ChatForm  react/prop-types

**first PropTypes in the line 7**

      static PropTypes = {
        'onAddMessage' : React.PropTypes.func.isRequired,
      }

I put `.func` because `onAddMessage` is a function...

**then in the line 44**

      _addMessage () {
        this.props.onAddMessage(input.value); // LINE 44
      }

**Comment by gyandeeps** [comment]
I would recommend to open this issue here: https://github.com/yannickcr/eslint-plugin-react
