### ISSUE TITLE
`max-nested-callbacks` has no default

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4297]
We have said in the past that all rules should have sensible defaults.  Currently, setting `"max-nested-callbacks": 2` does nothing at all.  I'm not sure what the right default number would be, but probably something relatively high.  Maybe `5`?

**Comment by michaelficarra** [comment]
The default is Infinity then, no?

**Comment by IanVS** [comment]
Yes, I suppose you could think of it that way.  I'm not sure I would consider that "sensible", though.

**Comment by nzakas** [comment]
I'd go with 10. Double digits are scary to start without being too restrictive (and unlikely to create debates about the number being too low).
