### ISSUE TITLE
Master unittests are failing on Windows

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#4315]
Latest master unit tests are failing on Windows 8, with the following error:
```
  1) globUtil resolveFileGlobPatterns() should convert a directory name with a leading slash into a glob pattern:

      AssertionError: expected [ '/lib' ] to deeply equal [ '/lib/**/*.js' ]
      + expected - actual

       [
      -  "/lib"
      +  "/lib/**/*.js"
       ]

      at Context.<anonymous> (c:\Users\Ilya\Documents\github\eslint\tests\lib\util\glob-util.js:78:20)
```
CC @IanVS

**Comment by platinumazure** [comment]
Between path issues and line ending issues, I'm wondering if we should try
to get a Windows CI environment up.

That said, I've checked Travis and they're still a ways away from Windows
support...

**Comment by IanVS** [comment]
Ah, I was worried about this.  I think it has more to do with the test than the code under test.  I'll try a fix, but I'm not sure how to test it.

@platinumazure, we tried Appveyor for a while, but it timed out a lot and was generally unstable.

**Comment by IanVS** [comment]
I guess this is a question.  Should `\lib` resolve to `/lib/**/*.js` on Windows?  (It isn't)

On Linux, `/lib` does indeed resolve, but perhaps this is unintentional?  I'll take out the test for now until it can be decided.

**Comment by ilyavolodin** [comment]
I think it should. Passing in `\lib` means lint all of `*.js` files under it. So in my mind it should resolve to `/lib/**/*.js`

**Comment by IanVS** [comment]
I think the issue is that our code attempts to determine if the pattern is a folder on the local machine, and only resolves to a glob if it is found.  Perhaps shell.test treats `/lib` and `\lib` differently? Needs more investigation...

**Comment by ilyavolodin** [comment]
Should we open a new issue for this, just so we could track it?

**Comment by IanVS** [comment]
I opened https://github.com/eslint/eslint/issues/4319 to track this and get feedback.
