### ISSUE TITLE
"Unnecessary { after 'else'" error appears on wrong line

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#4362]
This is the code I'm linting:

	if (0)
		console.log(0)
	else if (1) {
		// Above curly brace is necessary.
		console.log(1)
		console.log(1)
	} else {
		// Above curly brace is unnecessary.
		if (2)
			console.log(2)
		else
			console.log(3)
	}

And here's my package.json:

	{
		"scripts": {
			"lint": "eslint src test"
		},
		"devDependencies": {
			"eslint": "1.9.0"
		},
		"eslintConfig": {
			"rules": {
				"curly": [1, "multi"]
			}
		}
	}

I get the following error:

	/home/andy/eslint-bug/src/foo.js
	  3:6  warning  Unnecessary { after 'else'  curly

	✖ 1 problem (0 errors, 1 warning)

which is the correct error but has the wrong line number.
The error should be for the *last* else, on line 7.

**Comment by nzakas** [comment]
This isn't an issue with the wrong line number showing in the message. The first `else` is incorrectly being flagged. It's probably confused because there's an `if` right after it (which is one statement) and then a curly.

**Comment by mysticatea** [comment]
I'm working on this.
