### ISSUE TITLE
nodejs api formatter not working for warnings

### ISSUE THREAD

**Issue by rails4sandeep** [eslint/eslint#4382]
version: 1.7.3 

When using the nodejs API of eslint, I am getting error `formatter is not a function` for the console log statement

```javascript

            formatter = formatter || cli.getFormatter('stylish');
            report = cli.executeOnFiles([ p ]);

          if (report && report.warningCount > 0) {
            console.log(chalk.yellow('code has lint warnings'));
            console.log(formatter(report.results));
          }
```

Does the formatter only work with errors and not warnings?

**Comment by ilyavolodin** [comment]
Can you provide more details? From the looks of the code above, `formatter` might already have some value, but it's not a valid formatter function.

**Comment by rails4sandeep** [comment]
```javascript
var formatter = CLIEngine.getFormatter();

formatter: function(format){
cli.getFormatter(format);
}
```

**Comment by IanVS** [comment]
What are you trying to accomplish?  Maybe something like this?

```js
var cli = new CLIEngine({});
var formatter = cli.getFormatter;
```

**Comment by rails4sandeep** [comment]
That fixed my issue. Thanks a lot.
earlier this is what i had

```javascript
var cli;
var formatter;
cli = new CLIEngine(options);
formatter = cli.getFormatter();
```
It started working once I changed this to

```javascript
var cli = new CLIEngine({});
var formatter;
cli = new CLIEngine(options);
formatter = cli.getFormatter();
```
Thanks for the help.

**Comment by IanVS** [comment]
As a suggestion, there's no need to set `cli` twice, you could simplify this to:

```js
var cli = new CLIEngine(options);
var formatter = cli.getFormatter();
```

**Comment by rails4sandeep** [comment]
if i do this

```javascript
var formatter;
cli = new CLIEngine(options);
formatter = cli.getFormatter();
```
and then try to use `console.log(formatter(report.results));` i am getting an error `formatter is not a function`

**Comment by IanVS** [comment]
It's difficult to tell what you are trying to accomplish.  It would be very helpful if you gave a complete, minimal reproducible snippet and explained your use case.
