### ISSUE TITLE
Document that ~/.eslintrc will be skipped if there’s a project-specific config

### ISSUE THREAD

**Issue by natesilva** [eslint/eslint#4393]
After a some confusion and a `--debug` session, I figured out that `~/.eslintrc` is ignored in the configuration hierarchy if there is a project-specific. `.eslintrc` or `package.json` config.

That makes sense, but is not documented and is confusing (see #2724). The docs should call this out.

**Comment by nzakas** [comment]
Where are you looking? We cover how configuration works pretty extensively here: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by natesilva** [comment]
Yes, that’s what I’m looking at. That page doesn’t mention that `~/.eslintrc` (in your home directory) will be ignored in some cases. In addition, one of the examples is confusing.

With this:

```
/
└── home
    ├── .eslintrc
    └── user
        ├── .eslintrc
        └── projectA
            ├── .eslintrc
            └── lib
                ├── .eslintrc
                └── main.js
```

The following configs will be used when linting `main.js`:

1. `/home/user/projectA/lib/.eslintrc`
2. `/home/user/projectA/.eslintrc`
3. ~~`/home/user/.eslintrc`~~ (this will **not** be used; this fact is not documented anywhere)
4. `/home/.eslintrc`

The confusion is that an `.eslintrc` in your home directory will be used only if there is no more-specific config. Any *other* `.eslintrc`s in the directory hierarchy will be used.

**Confusing example:** In the documentation, the example beginning “For example, consider projectA…” implies that the reason `/home/user/.eslintrc` is not used is because `"root": true` is set. But this is not the case. `/home/user/.eslintrc` would not be used in any case — because it is in the home directory and an `.eslintrc` in your home directory is ignored if there is a more-specific config.

**Use case:** I had a `~/.eslintrc`. In my project, I added a small number of extra settings in `~/code/project/.eslintrc`, expecting the rules from both files to be applied.

Note, I’m not complaining about this feature. It’s useful, but the docs should explain it.

**Comment by nzakas** [comment]
Hmm, yeah, I can see how that is confusing. Do you want to submit a pull request to fix it?

**Comment by natesilva** [comment]
I did but I would need to review and sign a contributor agreement, which I don’t have time for right now. Hence this bug report.

**Comment by nzakas** [comment]
Working on this.

**Comment by nzakas** [comment]
This was actually fixed in this commit: https://github.com/eslint/eslint/commit/b4dfd3a6afed2a9c40409a21ff3a75dd71a5600f

Typo in the commit message left it off of this issue.

**Comment by natesilva** [comment]
Thank you!
