### ISSUE TITLE
"curly": "multi" doesn't work on for loop

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#4436]
This is the code I'm linting:

	// This correctly warns.
	if (true) {
		console.log(true)
	}

	// This doesn't warn.
	for (var key in {}) {
		console.log(key)
	}

And here's my package.json:

	{
		"scripts": {
			"lint": "eslint src test"
		},
		"devDependencies": {
			"eslint": "1.9.0"
		},
		"eslintConfig": {
			"rules": {
				"curly": [1, "multi"]
			}
		}
	}

I get the following output:

	/home/andy/git/ESLINT/src/foo.js
	  1:1  warning  Unnecessary { after 'if' condition  curly

	✖ 1 problem (0 errors, 1 warning)

It appears that the "multi" rule for curly braces works for `if` statements but not for `for` loops.

**Comment by nzakas** [comment]
Confirmed in demo, looks like a bug.

**Comment by kaicataldo** [comment]
I'd like to take a crack at this one, though might be a little delayed due to upcoming holidays.

**Comment by nzakas** [comment]
Okay, we may need to get it fixed before the holidays, so just comment back here when you start.

**Comment by gyandeeps** [comment]
This never handled `ForInStatement`. So I am not sure if we should flag this as a bug or an enhancement.

**Comment by nzakas** [comment]
It's a bug. There's no logical reason we shouldn't cover for-in. It's an accident, for sure.

**Comment by kaicataldo** [comment]
I'll take a look at this tonight, as long as no one else has claimed it :)
