### ISSUE TITLE
Treat package.json just like .eslintrc files

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4451]
When we first added `package.json` support, we made the decision that if there was a `package.json` and an `.eslintrc` file in the same directory, that we would use them both and combine the configuration. While it seemed like a good idea at the time, this setup has created some complexity in the calculation of configs that doesn't useful or worthwhile. It's unlikely that people are ever going to use both `package.json` and `.eslintrc`, and it would simplify the code to treat them the same.

I'd like to propose that `package.json` be treated just like `.eslintrc` (and all of the versions with extensions, `.eslintrc.js`, etc.) in that if present, it will be the only config file used. It would have highest priority to mimic the current behavior and hopefully cause as few issues as possible.

**Comment by gyandeeps** [comment]
Sounds good to me. :+1:

**Comment by ilyavolodin** [comment]
Agree.

**Comment by ilyavolodin** [comment]
Small correction to the proposal above. `package.json` should only be used as a top level config file if it contains `eslintConfig` property, otherwise it should be discounted from the list of order of config files.

**Comment by ilyavolodin** [comment]
The idea of this change is to simplify the code and make it work the same way for all configuration files, however, correction that I added above actually ends up making code more complicated then it is now. Now `file-finder` actually has to be able to parse `package.json` file and verify that it has `eslintConfig` property before bailing out and saying that the file that should be used for configuration. I've been looking at this for a little while, and I'm not sure this change is worth making.

**Comment by nzakas** [comment]
Hmmm good point. I'll take a closer look when I can.

**Comment by nzakas** [comment]
Ah, how about this: if we make package.json the lowest priority, then we don't need to modify file Finder. Just use `ConfigFile.load()` and see if the return value is null. Since it will only be checked if no other standard config files are found, it should be fairly straightforward.

**Comment by ilyavolodin** [comment]
That would work, but I'm not sure if it makes sense from the user's perspective

**Comment by nzakas** [comment]
Because?

**Comment by ilyavolodin** [comment]
I don't know, personally for me, package.json seems like a top level configuration that should override everything else. But that's only my personal feeling, don't know if it applies to anyone else.

**Comment by nzakas** [comment]
The goal here is really to eliminate the special case of merging .eslintrc files with package.json files in the same directory. Whichever is higher priority really doesn't matter unless you have two files already, in which case you'll need to combine the configs into one file.

**Comment by ilyavolodin** [comment]
Agree. I opened a PR with `package.json` at lowest priority. Even though it's still a bit confusing to me personally, but I think there's no default expected behavior for package.json config section, so people will be able to learn about priority from the documentation.

**Comment by platinumazure** [comment]
Do we know that a lot of people used merged configs? Speaking at least for myself, I know I would find that (i.e., having half my config in package.json and the other half in .eslintrc) confusing as hell.

**Comment by ilyavolodin** [comment]
@platinumazure We do not know, but we assume that not a lot of people do. That's why we are removing it.
