### ISSUE TITLE
Write JS, JSON, YAML files from --init

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4476]
Since we now have config files with extensions, we should update `--init` to output a file with an extension.

The last question should now also allow you to select JavaScript as an option, and the file should have an appropriate extension based on the type selected.

**Comment by ilyavolodin** [comment]
Should we still have an option for just `.eslintrc`?

**Comment by nzakas** [comment]
Nah, I don't see a need for it at this point.

**Comment by nzakas** [comment]
Working on this.
