### ISSUE TITLE
Drop support for Node < 4

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4483]
We've supported Node.js versions 0.10 and up for a while now. We didn't want to move off of it until the Node.js ecosystem solidified. This would mark the second time we've end-of-lifed support for an older version of Node.js, the previous being when we dropped 0.8 (#734).

We'd like to start using Node.js 4 so we can start writing ES6 and enable as many ES6 rules as possible on our code base (dogfooding rules yields a lot of problems).

The question is: should we do this sooner or later? It seems like a lot of people have been moving to Node.js 4 (or 5) and 0.10 and 0.12 installations are disappearing as a result. We don't want to leave people out in the cold, but we also don't want to wait forever.

**Comment by BYK** [comment]
Strong +1 for sooner since Node 4 is marked and marketed as LTS and already getting updated in that nature. Node 4 is almost fully backwards compatible too. There's also a Node 5 already. So I don't see a lot of reasons to not going forward with Node 4+ only.

**Comment by mourner** [comment]
> Node 4 is almost fully backwards compatible too.

No, it is breaking in many ways if you consider native modules. Moving everything over is a lot of effort and will take time, especially if you're working for a company with hundreds of modules, many of which rely on C++ bindings (I work for https://github.com/mapbox/).

@nzakas are there any obstacles that prevent you from going further with Node 4+ while keeping compatibility with Node 0.10, at least for a while? It doesn't seem like it would need a lot of overhead for ESLint case specifically. Travis takes care of catching all regressions.

**Comment by cjihrig** [comment]
Are you planning any type of long term support? 0.10 will be in maintenance support until Oct. 2016. 0.12 will be in active LTS until April 2016, followed by a maintenance period. I don't think this is necessarily important for ESLint given the nature of the application (no security patches, etc.), but I thought I'd bring it up.

For what it's worth, the hapi ecosystem has already made semver major version bumps to drop support for older versions.

**Comment by nzakas** [comment]
@mourner We'd like to start writing ES6 code in ESLint, which we can't do using Node.js < 4 (the team is against preprocessing). Writing ES6 code would allow us to test our ES6 rules on our own code, which we do with as many rules as possible to find bugs. The cost of continuing to support Node.js < 4 is that we cannot do that. 

@cjihrig no, we don't do LTS versions. While that would be nice, we simply don't have enough resources to be able to maintain more than one version of ESLint. We will always have just one version that we are supporting and that won't necessarily be tied to the official Node.js LTS strategy.

We'd like to make this change sometime in 2016, so what we're looking for is how this will impact ESLint users. If the majority are upgrading to Node.js 4 soon, then we can make a change sooner; if not, then we won't.

**Comment by mzgol** [comment]
IMO it makes sense to support Node.js LTS versions while they are in the Active state as then new apps may still use it. I'd expect the Maintenance state of Node LTS to be meant for apps already deployed that are no longer developed but have to have security fixes applied.

Therefore, I think it's ok to drop 0.10 support now and 0.12 support in May 2016 when it moves into Maintenance mode.

**Comment by jonkoops** [comment]
I would agree with @mourner and @mzgol here. Ideally packages would maintain compatiblity with LTS versions of Node. From my knowledge a lot of folks are still stuck on 0.12 because of breaking changes in native extensions, so supporting it until it's EOL makes sense.

**Comment by lo1tuma** [comment]
I vote for dropping node < 4 support sooner than later.
If somebody wants to use eslint with a node version < 4 he could just use the latest version which is compatible (this is similar to how [jsdom deals with node versions < 4](https://github.com/tmpvar/jsdom/blob/56323fc29e79fb567253d96a77886e41a7a37e03/README.md#install)). ESLint is almost always a devDependency, so it is not critical for production, therefore I don’t see a need to maintain compatibility with current LTS versions of node.

**Comment by BYK** [comment]
+1 to @lo1tuma but also +1 to @mzgol for the graceful approach. Still, my heart is closer to ES6.

**Comment by mourner** [comment]
> (the team is against preprocessing)

@nzakas can you elaborate more on this? This is potentially a painless set-it-and-forget-it step, where you only care about ES5 when `npm prepublish` script generates transpiled files to push to NPM.

**Comment by nzakas** [comment]
@mourner No, I'd prefer not to start a debate about preprocessing vs. not. We'd like to use native ES6 or else stick with ES5.

The issue at hand is about when it makes sense to drop support for different Node.js versions. As I said, I don't see us sticking to Node.js's LTS strategy. As @lo1tuma showed, jsdom already did something similar and is, arguably, a much more important part of people's applications than ESLint. Directing people to use an older (stable) version of ESLint might be one way to go.

Realistically, we're talking about sweeping up to Node.js 4 and staying there for a while, and then sweeping up to whatever Node.js version introduces native modules. So, we'll not constantly be forcing people to upgrade.

**Comment by mzgol** [comment]
I'm not sure if jsdom is the best example. It breaks compat with older versions pretty quickly, mostly for two reasons:

1. It uses ES6 features that are necessary to implement new DOM APIs reliably and as close to the spec as possible (e.g. Symbols).
2. jsdom's current maintainer cares mostly about current v8

Also, note that Node.js 4 (and even 5) doesn't give you full ES6, some quite important parts are missing. Spread is supported only from Node 5 and rest will only be in Node 6 which means for now you can't use arrow functions accepting indeterminate number of parameters (as arrows don't have the `arguments` binding).

IMO the biggest problem with dropping Node 0.12 is not that developers might need it intentionally but that a lot of packages support Node Active LTS releases (so 0.12+ for a few more months) and test on all supported Nodes on Travis which includes running ESLint on those Nodes (I have a couple of those). Updating to an ESLint version that drops Node 0.12 would require splitting the testing logic so that ESLint is not run on Node 0.12; that increases the CI maintenance burden for ESLint users.

Is it too much to wait until April/May 2016 when Node 0.12 goes into maintenance phase? I expect packages to start dropping support for it more often then.

**Comment by impinball** [comment]
Dropping support for these would require that I create a workaround script just to change versions so I can run this. I have to support 0.10 and 0.12 for one of my projects.

**Comment by mysticatea** [comment]
@nzakas We have [a online demo](http://eslint.org/demo/), but using ES2015 means dropping support for some browsers (e.g. IE). Is it OK?

**Comment by DavidBruant** [comment]
> We don't want to leave people out in the cold

One option I haven't seen mentioned here would be to provide eslint as a Docker container. This way, people could use the latest eslint version (based on whatever version of Node you want) without having to worry about the Node version installed on their machine.

This option adds a dependency to Docker for those who are not using recent versions of Node, but allows the eslint team to be as aggressive in dropping support as they want.

In this situation, people left in the cold are those who both cannot use latest versions of Node, nor install Docker. I believe this is a enough small population to be a workable solution (but of course, this is not my call).

**Comment by feross** [comment]
I don't mind dropping node < 4. But as @mzgol points out, the eslint team should be aware that lots of people still test their code on node 0.10 and 0.12 using Travis (or other CI) and they'll be forced to drop support for these node versions if their tests start failing. Or, they can just lock the eslint version.

**Comment by nzakas** [comment]
@mzgol wouldn't locking in on the last working version solve all the problems you mention? They could upgrade as soon as they moved off older Node.js versions.

According to https://github.com/nodejs/LTS/, 0.10 needs to be supported with critical big fixes until October of next year, and 0.12 with critical bug fixes until April 2017... If we follow LTS, won't we need to also follow the maintenance mode timeline? Or is the expectation that if we follow LTS, that it's just for the timeframe prior to maintenance only?

@mysticatea that's a very good point. We might need to look into transpiling for the demo.

@impinball can you share your upgrade plans?

**Comment by impinball** [comment]
I'm probably going to write a short shell script to temporarily switch nvm versions for ESLint exclusively.

**Comment by mourner** [comment]
I agree with @feross and @mzgol, and would suggest to wait at least until May 2016 before dropping 0.12 (which will be in active LTS until that time). You can drop 0.10 now though.

![](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)

**Comment by impinball** [comment]
@mourner +1

**Comment by mzgol** [comment]
@nzakas 
> According to https://github.com/nodejs/LTS/, 0.10 needs to be supported with critical big fixes until October of next year, and 0.12 with critical bug fixes until April 2017... If we follow LTS, won't we need to also follow the maintenance mode timeline? Or is the expectation that if we follow LTS, that it's just for the timeframe prior to maintenance only?

I'm not sure if there is any official recommendation but let me repeat what strategy seems sensible to me:

> I'd expect the Maintenance state of Node LTS to be meant for apps already deployed that are no longer developed but have to have security fixes applied.

If an app is not developed anymore but only has critical fixes applied then I expect it doesn't need future ESLint versions working as it's not supposed to apply regular dependency updates. If it's still developed it should move from an LTS in Maintenance state to an Active LTS ASAP. That's how I see it.

@rvagg Do I understand it correctly?

**Comment by cjihrig** [comment]
I think it's also worth pointing out that there is a 6 month overlap where there are two active LTS versions. At the moment, that is 0.12 and 4.2.x (Argon). The purpose of that overlap is to give LTS users an upgrade period. Since Argon is available, and pinning to an older version of ESLint is a perfectly fine option, dropping 0.12 support should be fine.

**Comment by rvagg** [comment]
It might be worth prodding at the Hapi strategy for dealing with this. I quite like the approach being promoted there: https://github.com/hapijs/hapi/issues/2765 — forward progress but throwing a bone to folks stuck on old versions. You could probably even get someone who is more invested in older versions of Node to put up their hand to maintain an LTS ESLint branch. Also, npm are doing a similar LTS thing to deal with the new core release schedule with v2 being maintained as LTS and v3+ moving on.

**Comment by lo1tuma** [comment]
I’ve never seen a developer tool which has a LTS version. Why not running ESLint with a different node version (or `babel-node`) than your production code, like @impinball suggested?

**Comment by mzgol** [comment]
@rvagg npm 3 supports Node >= 0.8 so it's a little different... Also, npm 2 is included in Node 4 so the obligation to keep the old version of npm working & patched is higher.

**Comment by nzakas** [comment]
@rvagg I'm really interested in avoiding needing to maintain two versions. The team just isn't big enough to be able to absorb that level of overhead, even if someone stepped forward to volunteer.

@mzgol you make some good points. I can definitely buy that support during the maintenance period can be handled via version pinning as people transition off older versions.

@DavidBruant The Docker approach is super interesting, but we have no Docker expertise on the team, so we would be unprepared to maintain such a solution.

I'm okay with waiting until May to drop 0.12 support. Since dropping 0.10 doesn't buy us all that much, I'd probably wait until then to drop it as well.

How does that sound to everyone? @eslint/eslint-team

**Comment by ilyavolodin** [comment]
I'm impartial either way, but it sounds like supporting 0.12 till May might be a good idea and would lessen the stress on consumers. So I'm for that.

**Comment by alberto** [comment]
I'm in favor of dropping it sooner than later, since there are alternatives for people running on old node versions (staying on eslint 1.x, or running it through nvm or docker).

For people mantaining packages for multiple node versions, do they really need to run eslint for all of them?

**Comment by mzgol** [comment]
@alberto 
> For people mantaining packages for multiple node versions, do they really need to run eslint for all of them?

Theoretically they don't. But it's not always that simple; sometimes ESLint is invoked deep in the test pipeline, sometimes as a Grunt task etc. In these cases you'd often have to create extra logic inside your code to exclude running ESLint on older Nodes. It's not (usually) terribly hard but it is still additional work done purely for ESLint.

**Comment by rvagg** [comment]
My personal position is that I'd rather see packages drop support for <= 0.12 entirely at this stage. They are _old_ (0.12 not so much in terms of years but definitely in terms of distance from where Node is now) and difficult to maintain and I'm happy for the upgrade pressure to be applied to the community. 

However, having said that, I'm concerned about the same logic being applied to v4.x into the future, toward the end of the 30 months that it's going to be supported. We're trying hard to make it a legitimate long-term choice and I have no doubt that it _will_ be different to the way Node was supported in the past. But due to the way that JavaScript marches forward, I'm sure that it's going to feel old to OSS package maintainers pretty quickly. After v6.x turns LTS, it'll be easy to justify dropping v4.x support, with conversations like this one happening all over again. Whatever you do decide, just keep in mind that we sincerely intend v4.x to have the full LTS+maintenance lifespan, that many of us supporting it work for companies that intend to use it for much of that lifespan or support other companies that will be using it for that long. A LTS support strategy for a package like ESLint could consist simply of being open to fixing bugs and making releases off a specific old branch given pull requests from users who still care, perhaps this could even be stated as the LTS approach.

And to be clear: v0.10 is supported till October 2016, it's in "maintenance" the entire time which lowers the threshold for the types of fixes we'll merge. v0.12 is supported till the end of 2016, we're calling it "LTS" till the end of this year and "maintenance" for all of 2016, but in practice it's likely to be maintained in a very similar fashion to v0.10. I'd expect there to be a large number of active users of both for that entire time (and beyond, but that's on them if they do that).

**Comment by xjamundx** [comment]
A couple of quick things:

- PayPal will probably be on 0.10 until Feb. or so. (then move to node 4)
- ES6 features in node 4 are still fairly limited (no destructuring, rest/spread, default params, etc. let doesn't even work properly). Those are my go-to features. What features are we planning to really adopt? (Generators/Promises might be interesting, but would result in a pretty huge API change)
- Not knowing too much about the rest of the enterprise node community (who are often using eslint) and may be slow to upgrade node versions, maybe we should get feedback from someone like @dshaw who may have a better sense of the upgrade paths of other big orgs.

I'm hesitant to move forward with a change like this, because my co-workers and I are still on an old node version and I suspect many other large orgs are as well.

I'd love to revisit this in 4-6 months and see where things are, but right now this feels a bit like the "Let's drop support for IE" discussions I have at work wherein product always comes back and says, yeah yeah that's fine that's it's only a few %, but IE8/9 still made us $100k last months!

**Comment by lo1tuma** [comment]
> but right now this feels a bit like the "Let's drop support for IE" discussions

IMHO this is a completely different discussion, as ESLint is a developer tool which doesn’t face any enduser of production which has ESLint in its pipeline. Also I don’t see a reason why the node versions for production and for executing ESLint have to be the same, just use `nvm exec 5 ./node_modules/.bin/eslint`.

**Comment by xjamundx** [comment]
@lo1tuma that's not realistic where I work, I don't have much control over my CI environment or my production environment. I'm currently working hard to get the whole company to move to `eslint` and I'm worried something like this will get everyone to be a bit skittish about such a move. It will probably still happen, but it will take a lot more work if we also have to modify all of our CI environments...

**Comment by nzakas** [comment]
@rvagg this is why I'm not proposing anything other than his we drop < 4, I'd like to see what the expectations, upgrade cycles, and community sentiment around both are prior to establishing a formal policy. 

@xjamundx stuff like Maps and Weakmaps will help a lot and could speed us up. Promises are also a big one. There's plenty in Node.js 4 that could have a tangible effect on us.

What would make people skittish? And do you have a timeframe for upgrading at PayPal?

@lo1tuma in some ways, this is more problematic than IE8 because we are in the middle of people's release process. It's not like people can just switch to another browser if they get stuck.

**Comment by mzgol** [comment]
@rvagg 
> After v6.x turns LTS, it'll be easy to justify dropping v4.x support, with conversations like this one happening all over again. Whatever you do decide, just keep in mind that we sincerely intend v4.x to have the full LTS+maintenance lifespan, that many of us supporting it work for companies that intend to use it for much of that lifespan or support other companies that will be using it for that long. 

Is there any difference between an Active LTS and one in Maintenance phase from the perspective of package authors then? Node.js 4 will have similarly old v8 when Node 6 gets released as Node 0.12 (its v8 went stable on 2014-10-07) has now. Supporting it through Maintenance phase as well would mean having to work on v8 that's 3 years old (and up to 4 Node versions), that seems a lot considering the speed JavaScript develops currently.

> And to be clear: v0.10 is supported till October 2016, it's in "maintenance" the entire time which lowers the threshold for the types of fixes we'll merge. v0.12 is supported till the end of 2016, we're calling it "LTS" till the end of this year and "maintenance" for all of 2016

Is the table at https://github.com/nodejs/LTS inaccurate then? The messaging around 0.10/0.12 treatment has been very unclear to me even though I tried to follow the decisions made. The page still says 0.12 goes "maintenance" on 2016-04-01 so way later than you said.

**Comment by rvagg** [comment]
> The page still says 0.12 goes "maintenance" on 2016-04-01 so way later than you said.

You're correct, sorry. 0.12 has been really hard to manage and it's effectively close to maintenance now. We'll still be caring for it (I've been poking at a potential memory leak in the last couple of days with 0.12 actually) but we'd prefer that people find an upgrade path asap. The end-of-2016 thing for 0.12 is strictly about losing OpenSSL support then, we can't be responsible for it if OpenSSL aren't even going to be updating the version that's bundled with it.

**Comment by jonkoops** [comment]
An LTS version of Node v0.12 [has just been released](https://nodejs.org/en/blog/release/v0.12.8/), it will as LTS until the end of 2015 and in maintenance until end of 2016.

**Comment by mzgol** [comment]
@rvagg You wrote in the blog post that 0.12 active state ends at the end of 2015, as you wrote here before. Could you correct it?

**Comment by rvagg** [comment]
![LTS](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)

i.e. 0.12 is "Active LTS" until the end of this year and then "Maintenance" until the end of 2016. These are really both forms of LTS but with different thresholds for what makes it in.

**Comment by mourner** [comment]
> 0.12 is "Active LTS" until the end of this year

But it ends on Apr 2016 on the chart (not Dec 2015 to be called "end of the year"), right?

**Comment by rvagg** [comment]
ugh, ok, sorry my bad, you're right

**Comment by alberto** [comment]
do we have a decision on this, now that we are approaching eslint 2.0?

**Comment by nzakas** [comment]
Yeah, we will hold off until 3.0.0 and plan to do that around April 2016 to coincide with the end of active LTS for 0.12.

**Comment by ilyavolodin** [comment]
I have no idea how realistic this statistic is, and what the sample size is, but just saw it, and figured it's better than nothing: https://semaphoreci.com/blog/2015/12/15/nodejs-version-usage-in-commercial-projects-2015-edition.html doesn't paint pretty picture for dropping support for older versions.

**Comment by lo1tuma** [comment]
@ilyavolodin As ESLint is a developer tool, the node version people use in production doesn‘t really matter.

**Comment by nzakas** [comment]
@lo1tuma not entirely true. People aren't going to use a different node version during development than they do in production.

Still, I suspect by next April this will have changed significantly.

**Comment by lo1tuma** [comment]
@nzakas Yes, but they could. They don’t even have to use a different node version for everything, only for eslint.

Anyway, next April sounds good to me.

**Comment by alberto** [comment]
We are already in April, so nodejs@0.12 is officially in maintenance mode (and nodejs@6 will release in a few weeks), but it looks like eslint@3.0.0 is still far from now. What do we want to do?

Also, we talked about dropping node < 4, but, shouldn't it really be node < 4.2.0, since that is the first LTS version?

**Comment by mgol** [comment]
> Also, we talked about dropping node < 4, but, shouldn't it really be node < 4.2.0, since that is the first LTS version?

For any `n` only the latest `n.x.y` release is supported by upstream and I don't think it makes sense to support versions not supported by upstream so that would be achieved by definition. ESLint is already tested [on latest version for each major](https://github.com/eslint/eslint/blob/e0543720bd8154b847d80b6bc56ac62b3e983b36/.travis.yml#L6) so that seems to be the current policy.

**Comment by nzakas** [comment]
We will drop support for older Node versions when 3.0.0 is released (whenever that happens to be). If nothing important comes up as a breaking change in the next couple months, then we can discuss doing a 3.0.0 purely to drop older Node support. 

And yeah, the policy should likely be we support the latest LTS version and higher.

**Comment by Mouvedia** [comment]
Id advise against dropping support for 0.12 in the medium-term.
Just add a one year shift to your maintenance deadlines and you should be good.

**Comment by isiahmeadows** [comment]
@Mouvedia You don't necessarily have to use the same Node version to run ESLint that you run your project with.

**Comment by nzakas** [comment]
@Mouvedia you'll need to continue using an older ESLint version if you need to use an older Node version.

**Comment by mourner** [comment]
> I agree with @feross and @mzgol, and would suggest to wait at least until May 2016 before dropping 0.12 (which will be in active LTS until that time)

The comment above was mine, but now that it's May 2016, I fully support the breaking switch to Node 4+. :)

**Comment by markelog** [comment]
Just fyi, tried to do this in JSCS (one month of support left, so yeah), and lots of people were upset.
To note: i'm not advocating to keep supporting older versions

**Comment by SimenB** [comment]
I couldn't find any module for it, so I quickly created a cli for checking node version.

https://github.com/SimenB/node-version-check

Pretty easy to integrate in current lint script.

**Comment by mysticatea** [comment]
I also thought the same thing, but @SimenB's seems better. :D

https://www.npmjs.com/package/if-node-version

**Comment by SimenB** [comment]
Discoverability of npm modules strikes again 😄

**Comment by Mouvedia** [comment]
@SimenB https://www.npmjs.com/search?q=node+version

**Comment by SimenB** [comment]
I googled it, @mysticatea's module probably wasn't indexed yet (or my google-fu failed me). Anyways, 2 options available, one generic, one specific, no need to spam this thread anymore 😄

**Comment by isiahmeadows** [comment]
If you're using Travis, I use this to address the ESLint version needing to be changed temporarily:

```yaml
before_script:
  - nvm install stable
  - eslint .
  - nvm use $TRAVIS_NODE_VERSION
```

**Comment by SimenB** [comment]
My thinking is that linting doesn't really have to run on more than one version, it's the tests that has to. Consumers won't run linting on the code, but they will run the code, so it's good to have the tests run on many versions. But just skipping eslint on older versions is no real issue.

**Comment by isiahmeadows** [comment]
@SimenB That's why I change the version temporarily. I'll lint on all builds because if it won't lint, I don't trust it to waste time running, but I only need the latest stable to run it.

**Comment by jonkoops** [comment]
Note that when support is dropped for older versions of Node we should add the correct Node version to package.json.

I.e.
```json
"engines": {
  "node": ">=4.4.0"
}
```

**Comment by mysticatea** [comment]
@jonkoops [package.json#L118-L120](https://github.com/eslint/eslint/blob/f8ab8f1283966ac03312ab1c7d215c210e93f3b1/package.json#L118-L120)

**Comment by jonkoops** [comment]
@mysticatea Nice!

**Comment by balupton** [comment]
to add onto @isiahmeadows suggestion in https://github.com/eslint/eslint/issues/4483#issuecomment-230939656

here is another option that only runs the linting on the latest LTS node version:

``` yaml
before_script:
  - if test "$(nvm current)" == "$(nvm version-remote --lts)"; then eslint .; else echo "linting skipped"; fi
```

**Comment by tornado1979** [comment]
Hello i just updated eslint on my repos from ver v2.13.0 to v4.1.1 and i get the error 

[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: ........./node_modules/eslint-config-airbnb/index.js
Referenced from: ........../.eslintrc
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: ........../node_modules/eslint-config-airbnb/index.js
Referenced from: ........../.eslintrc
    at validateConfigSchema (........../node_modules/eslint/lib/config/config-validator.js:187:15)
    at Object.validate (........../node_modules/eslint/lib/config/config-validator.js:200:5)
    at loadFromDisk (........../node_modules/eslint/lib/config/config-file.js:549:19)
    at load (........../node_modules/eslint/lib/config/config-file.js:592:20)
    at ........../node_modules/eslint/lib/config/config-file.js:421:36
    at Array.reduceRight (native)
    at applyExtends (........../node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (........../node_modules/eslint/lib/config/config-file.js:556:22)
    at load (........../node_modules/eslint/lib/config/config-file.js:592:20)
    at ........../node_modules/eslint/lib/config/config-file.js:421:36

i use an older ver of nodejs but > 4.

piece of package.json :

...
"devDependencies": {
    "babel-eslint": "6.1.2",
    "babel-plugin-webpack-alias": "2.1.1",
    "chai": "3.5.0",
    "chai-enzyme": "0.4.2",
    "concurrently": "2.2.0",
    "enzyme": "2.4.1",
    "esdoc": "0.4.8",
    "esdoc-es7-plugin": "0.0.3",
    "esdoc-plugin-enhanced-navigation": "0.0.7",
    "eslint": "4.1.1",
    "eslint-config-airbnb": "9.0.1",
    "eslint-loader": "1.5.0",
    "eslint-plugin-import": "1.14.0",
    "eslint-plugin-json": "1.2.0",
    "eslint-plugin-jsx-a11y": "1.5.5",
    "eslint-plugin-react": "5.2.2",
    "happypack": "2.2.1",
    "mocha": "2.5.3",
    "node-libs-browser": "1.0.0",
    "protractor": "1.8.0",
    "react-addons-test-utils": "15.3.1",
    "sinon": "1.17.5",
    "sinon-chai": "2.8.0",
    "stylint": "1.5.6",
    "stylint-loader": "1.0.0",
    "watchy": "0.6.6"
  },
....
  "engines": {
    "node": "4.2.6"
  }

**Should i commit all the other eslint packages also? Does node v4.2.6 works ok with eslint v4.1.1 ?**

Thanks in advanced.
