### ISSUE TITLE
Update rules format to allow for metadata

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#4494]
We would like to add metadata to all of the rules in the repository to allow for automation of documentation creation and other tasks. Current proposal for rule format would be to convert `module.exports` from a function to an object with the following signature:
```js
module.exports = {
    meta: {
        docs: {
            description: "",
            category: "",
            recommended: false
        },
        fixable: "whitespace",
        schema: []
    },
    create: function(context) {
    }
};
```

This issue is to discuss the new format before converting all of the existing rules. You can see example of the new format in this PR: #4179

**Comment by alberto** [comment]
Why not use [jekyll's front matter](http://jekyllrb.com/docs/frontmatter/)?

**Comment by ilyavolodin** [comment]
@alberto We are talking about rules them self, not documentation for rules. And rule documentation is not the only place we would want to use metadata in. For example, we can use metadata to provide more information to our online demo, or to auto-generate index page for rules, or to provide more information about the rule on the command line, etc.

**Comment by nzakas** [comment]
For additional information: we will still support the original style of rules so as not to break existing plugins, this proposal will be in addition to the current rule format.

One addition that might make sense: what if `fixable` could be more descriptive. For instance, if the value could be "whitespace" or "syntax", we would have the ability to run fixes in waves, the first fix being syntax and the second being whitespace, to avoid creating new whitespace issues. Thoughts on that?

**Comment by ilyavolodin** [comment]
Sure that sounds good. Do we want to define a map somewhere with allowed values, or just deal with strings?

**Comment by nzakas** [comment]
I think strings are OK.

**Comment by ilyavolodin** [comment]
Sounds good. I'll modify original post.
