### ISSUE TITLE
Create downstream automated tests

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4500]
We recently introduced a change that broke `eslint-plugin-react` inadvertently. It would be good to have some automation around popular downstream projects to catch these problems faster. We can start with `eslint-plugin-react` and then add more projects if this is successful.

Some things we need to figure out:

- [ ] **When to run the tests?** How do we know we've not intentionally introduced a breaking change? Should this be run via Travis all the time or only just before we do a release to catch any last-minute issues?
- [ ] **How do we do such a test?** Perhaps look at what Esprima has implemented - I'm not sure how to do this off the top of my head.
- [ ] **Which projects do we test?** At what point do we consider a project "important" enough to add?

**Comment by ilyavolodin** [comment]
I think we can try it on commit, but I think better way would be run it only on a master. That might mean that we will have master with broken builds, but that's not the end of the world (just need to make sure we don't do a release with a broken master). `eslint-plugin-react` is by far the most popular plugin out there, but angular, standard and babel are pretty popular too.

**Comment by nzakas** [comment]
Running on commit will work so long as we don't have breaking changes. When we do have breaking changes, it will break. Any thoughts on how to deal with that?

**Comment by ilyavolodin** [comment]
Do we want to lock down specific version of plugins? Because otherwise, commits might break due to the changes in plugin, and not in our code. Also, no idea how to deal with breaking changes. I don't think Travis allows for downstream builds (as in run this build after the main build, but don't block the main build if this one files?)

**Comment by nzakas** [comment]
We'd need to include the downstream tests in our build. 

Locking down the versions could make sense, but then we'd have to manually update all the time.

**Comment by platinumazure** [comment]
[This article by Ariya Hidayat][1] was brought up in chat, but I'm going to leave it here in case it happens to be of any use for others.

  [1]: http://ariya.ofilabs.com/2015/11/continuous-tests-of-downstream-projects.html

**Comment by nzakas** [comment]
We actually have this in the form of a regression build now, so closing.
