### ISSUE TITLE
Confusing wording for location of no-fallthrough

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#4516]
Here's the code I'm linting:

	function f() {
		switch (0) {
			case 1:
				console.log(2)
				break
			case 3:
				console.log(4)
			case 5:
				console.log(6)
		}
	}

And here's my package.json:

	{
		"scripts": {
			"lint": "eslint src"
		},
		"devDependencies": {
			"eslint": "1.10.0"
		},
		"eslintConfig": {
			"rules": {
				"no-fallthrough": 1
			}
		}
	}

I get the following output:

	/home/andy/git/ESLINT/src/foo.js
	  6:3  warning  Expected a "break" statement before "case"  no-fallthrough

	✖ 1 problem (0 errors, 1 warning)

There is a `break` before the `case` on line **6**. The missing break is before line **8**.

This could be fixed by changing the message to someting like `Expected a "break" statement at the end of this "case"`.

**Comment by alberto** [comment]
Should we fix the message or error line reported?

**Comment by mysticatea** [comment]
I also felt odd the message while #4251.
I think changing the location is fine, because it's near to actual mistaken location.

```
  8:3  warning  Expected a "break" statement before "case"  no-fallthrough
```
