### ISSUE TITLE
Upgrade: js-yaml has invalid dependency

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#4553]
js-yaml latest version depends on [inherit](https://github.com/dfilatov/inherit), which doesn't declare a license in package.json, so build is failing.

**Comment by gyandeeps** [comment]
Can we fix this by sending a PR to `inherit` repo to update the license attribute inside package.json file?
As `inherit` already has an MIT license.
https://github.com/dfilatov/inherit/blob/master/LICENSE.md

**Comment by nzakas** [comment]
+1 for sending a PR to inherit

**Comment by alberto** [comment]
Yeah, I have submitted a PR. I just thought we would like to fix this in the meantime.

**Comment by nzakas** [comment]
I'd prefer not to. That will mean we have to manually unpin later, and it won't help anyone for whom is already a problem.

**Comment by nzakas** [comment]
I merged because I realized this was breaking all builds
