### ISSUE TITLE
"curly": "multi" doesn't work on for-of loop

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#4571]
This is the code I'm linting:

	// This correctly warns.
	for (var key in {}) {
	    console.log(key)
	}

	// This doesn't warn.
	for (var key of []) {
	    console.log(key)
	}

And here's my package.json:

	{
		"scripts": {
			"lint": "eslint src test"
		},
		"devDependencies": {
			"eslint": "1.10.2"
		},
		"eslintConfig": {
			"ecmaFeatures": {
				"forOf": true
			},
			"rules": {
				"curly": [1, "multi"]
			}
		}
	}

I get the following output:

	/home/andy/git/ESLINT/src/foo.js
	  2:1  warning  Unnecessary { after 'for-in'  curly

	✖ 1 problem (0 errors, 1 warning)

See also #4436.

**Comment by kaicataldo** [comment]
I can take this - I added in the for-in loop in #4436.
