### ISSUE TITLE
"brace-style": "1tbs" should warn for brace-less `else` expression on wrong line

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#4591]
This is the code I'm linting:

	// This correctly warns.
	if (true) {
		console.log(1)
		console.log(2)
	}
	else {
		console.log(3)
	}

	// This does not warn.
	if (true) {
		console.log(1)
		console.log(2)
	}
	else
		console.log(3)

And here's my package.json:

	{
		"scripts": {
			"lint": "eslint src test"
		},
		"devDependencies": {
			"eslint": "1.10.3"
		},
		"eslintConfig": {
			"rules": {
				"brace-style": 1
			}
		}
	}

I get the following output:

	/home/andy/git/ESLINT/src/foo.js
	  6:6  warning  Closing curly brace does not appear on the same line as the subsequent block  brace-style

	✖ 1 problem (0 errors, 1 warning)

It makes sense to me that the following style should be preferred for consistency with 1tbs:

	if (true) {
		console.log(1)
		console.log(2)
	} else
		console.log(3)

**Comment by nzakas** [comment]
This rule does not enforce the use of braces. Use `curly` for that: http://eslint.org/docs/rules/curly.html

**Comment by andy-hanson** [comment]
The final sample in the issue is what I want code to look like. **I don't want to enforce the use of braces.** When there are braces, I want the closing curly brace to appear on the same line as the subsequent statement.
