### ISSUE TITLE
no-extra-parens missing YieldExpression

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#4608]
While working on #4229, I came across this:

```js
function *test() {
  yield 1;
  yield (2);
  yield       // 4:8 - Missing semicolon. (semi)
    3;
  yield (
    4
  );
  return (5); // 9:10 - Gratuitous parentheses around expression. (no-extra-parens)
}

for (let val of test()) {
  console.log(val); // 1 2 (blank) 4
}
```

I ran the above code in the demo with only `no-extra-parens` and `semi` enabled and pasted the errors inline. I included `semi` and the `return` as sanity checks.

I would expect a warning about excess parens on `yield (2);`, but there was none. Looking at the source, `no-extra-parens` doesn't check `YieldExpression`s, so hopefully the fix is as simple as adding that check.

Working on this.

**Comment by michaelficarra** [comment]
Looks like the addition of YieldExpression support (#1992) only added support for YieldExpressions within other expressions, but not the other way around.
