### ISSUE TITLE
Path Analysis output makes debug mode hard to read

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#4631]
Path Analysis is adding a tone of output for every code path to the debug log. On Windows machine the amount of buffer is limited, mine is set to 1000 lines and linting just one file (Makefile.js from our repository) overflows the buffer and doesn't let me see the information in the begging of the output. Path Analysis output should probably be piped into a different log.

**Comment by nzakas** [comment]
Any proposal for how that should work? How would we get debug info for code path analysis?

Is it possible to just reduce the debug messages rather than trying to filter?

**Comment by ilyavolodin** [comment]
I'm not really all that familiar with the `debug` and what could be done with it. As far as I understand it, we  name debug log for each file. What I was thinking was to name Path Analysis debug log something completely different from the rest of the ESLint, that way if somebody wants debug log specifically for Path Analysis, they can run `DEBUG=eslint:code-analysis` to get it. Not really 100% sure how to implement it properly, but we added `--debug` flag to be able to ask users to look through the logs, and logs for Path Analysis will be unlikely candidate for resolving issue.

**Comment by nzakas** [comment]
Which is why I ask, can we just reduce the amount of debug messages it creates? 

Trying to filter is going to be a big pain, but if the debug messages aren't that useful, we should eliminate some.

**Comment by mysticatea** [comment]
On, sorry for this.
I think I can remove those debug messages except DOT outputs.
