### ISSUE TITLE
Some arrow functions parsed as a condition.

### ISSUE THREAD

**Issue by calebmer** [eslint/eslint#4632]
In the following snippet:

```js
const callAllObservers = method => value => store.map(observer => observer ? observer[method](value) : null)
```

[`no-arrow-condition`](http://eslint.org/docs/rules/no-arrow-condition.html) throws an error. I'm pretty sure it's looking at `observer => observer ?` and interpreting it as *if* `observer` is less than or equal to `observer` then… when really I'm just checking if `observer` (the only argument of the arrow function) is a falsey value.

**Comment by ilyavolodin** [comment]
`observer ? observer[method(value) : null` is a condition. It's checking for null value.

**Comment by calebmer** [comment]
I know, but the `no-arrow-condition` rule thinks that `observer => observer` is the condition.

**Comment by mysticatea** [comment]
I think this is duplicate of #4417.

**Comment by calebmer** [comment]
@mysticatea I think so as well. This seems to be a pretty common pattern.
