### ISSUE TITLE
ESLint (2.0.0-alpha-1) should not rewrite the given config object.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#4682]
Here: https://github.com/eslint/eslint/blob/v2.0.0-alpha-1/lib/eslint.js#L405

`config.parserOptions.ecmaFeatures` is shallow copied, so L414 overwrites original config.
I encountered incorrect warnings caused by this.

**Comment by gyandeeps** [comment]
huh but config.merge function is supposed to do a deep copy. Are we sure line L405 is the true cause of the issue?

**Comment by mysticatea** [comment]
I believe.

This `deep merge` is not `deep copy`.
When the destination property does not exist, `deep merge` is assigning merely.

https://github.com/eslint/eslint/blob/v2.0.0-alpha-1/lib/config/config-ops.js#L174

**Comment by mysticatea** [comment]
We can reproduce in this repo's branch: https://github.com/mysticatea/npm-run-all/tree/try-eslint-2a1

1. clone
2. checkout try-eslint-2a1
3. npm i
4. npm run lint

There is a mix of ES6 and ES5 in this repo, so I use two kind of eslint config.

- `extends: ["mysticatea", "mysticatea/modules", "mysticatea/node"]
- `extends: ["mysticatea/es5", "mysticatea/node"]

`mysticatea/node` has `parserOptions.ecmaFeatures.globalReturn: true` but it's rewritten with `false` in the former, then eslint shows wrong warnings (mainly `no-implicit-globals`) in the latter.

----

Hmm, should I fix `ConfigOps.merge`?

**Comment by gyandeeps** [comment]
if its an issue then we should fix it.

**Comment by mysticatea** [comment]
Oh, `RuleTester` freezes config object, so several plugin's tests are failed.

![image](https://cloud.githubusercontent.com/assets/1937871/11764906/fc52c0e0-a186-11e5-9485-d34af0a6ca9a.png)
