### ISSUE TITLE
How-To: Performance Tuning

### ISSUE THREAD

**Issue by robcolburn** [eslint/eslint#4724]
Last week, a teammate extended our lint command to tell eslint to also evaluate our `json` files. Since that time, I've felt better that our code is better tested and less likely to have less surprises out in production.  However, some time later, I noticed the performance of our lint command slowed down dramatically.

```bash
$ time(./node_modules/.bin/eslint --quiet .)
real	0m6.303s
user	0m6.710s
sys	0m0.226s
$ time(./node_modules/.bin/eslint --ext .js --ext .json .)
real	0m31.911s
user	0m32.362s
sys	0m0.297s
```

I'd really like to trim that down, so I started looking for culprits…

1. What files are eslint actually evaluating? Maybe other things we can trim down. I couldn't find a way to determine this easily in eslint. *Feature Request:* A way to just get a list of files that ESLint is actually evaluating.
1. Based on the debug output, is there a soar-spot?  I'm not the cleverest at the shell scripting, so I tried and failed a couple tricks I know to filter the output to just "heavy" things. I'm sure there's something about piping/streams I'm not getting. In retrospect, I should have just dumped to a file and filtered from there.

  ```sh
  $ ./node_modules/.bin/eslint --ext .js --ext .json --debug . | grep "[0-9][0-9]ms"
  $ ./node_modules/.bin/eslint --ext .js --ext .json --debug . | grep  --line-buffered "[0-9][0-9]ms"
  ```
1. Maybe there are actually a lot json's we added to the lint job. This turned out to be somewhat true.  There were around 50 in our tests directory, dropping those dropped 10s.

Further tweaking found the main culprit to be `npm-shrinkwrap.json`, in my case was consuming 12s.

So, I'm looking at swapping out eslint's json linting for something more… naive fast.

**Comment by ilyavolodin** [comment]
ESLint doesn't not lint json files. You should be getting a syntax error for every json file that is being linted by ESLint. Right now, we output a bit too much into debug log, there is an issue #4631 to fix this. But you should still be able to grep for "Linting " which would get you the list of files that are being linted. There are also a few formatters out there that would output you the list of files that were linted by a command.

**Comment by robcolburn** [comment]
@ilyavolodin,
> ESLint doesn't not lint json files
Ah, you're right! We apparently have [`eslint-plugin-json`](https://www.npmjs.com/package/eslint-plugin-json) in our package.

>  But you should still be able to grep for "Linting " 
My problem here was that piping to grep didn't seem to have any affect on the screen output.  Not sure what bash thing I did wrong there

**Comment by ilyavolodin** [comment]
@robcolburn I just looked at `eslint-plugin-json` and what it does, is actually calling JSHint on json files. I'm not sure why would somebody want to do that, but basically what is happening is each JSON file is being parsed by Espree to create AST (which will fail in most cases). After that it will run JSHint on the content of the file and output errors is if they were ESLint's. So it's basically doing twice the work for each json file.

I think the issue with piping might be because debug logs are going into std.error? I'm not sure.

**Comment by nzakas** [comment]
You need to use `--stdin` flag to pipe code to ESLint.

**Comment by robcolburn** [comment]
@ilyavolodin Thanks so much for digging in, I really appreciated. Our team converted to straight `jshint` for JSON linting (2.9.x turns out to be really performant at that to boot).

@nzakas,
In this case, I wanted to grep ESLint's debug output (not change ESLint's input).  So, it turns out most of the internet was sending on the almost-the-right trail, redirecting stderr `eslint --debug . 2> log.txt`.  However, it turns out the stderr of ESLint isn't exactly the same as the terminal output.  My goal with grep'ing was to filter out fast things to reduce the noise, that is results with single digit perf `\+[0-9]ms`.  It turns out the micro-benchmarks are not included in stderr.  

Terminal
```
  eslint:config Merging command line environment settings +0ms
  eslint:cli-engine Processing /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js +162ms
  eslint:cli-engine Linting /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js +0ms
  eslint:config Constructing config for /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js +0ms
```

stderr
```
Fri, 18 Dec 2015 20:21:02 GMT eslint:config Merging command line environment settings
Fri, 18 Dec 2015 20:21:02 GMT eslint:cli-engine Processing /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js
Fri, 18 Dec 2015 20:21:02 GMT eslint:cli-engine Linting /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js
Fri, 18 Dec 2015 20:21:02 GMT eslint:config Constructing config for /Users/robertcolburn/Sites/generetic/components/PageTitle/PageTitle.js
```

**Comment by ilyavolodin** [comment]
@robcolburn I could also suggest looking at [jsonlint](https://github.com/zaach/jsonlint). That's what we are using in ESLint for linting json files.
