### ISSUE TITLE
Custom environments in plugins

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4782]
We discussed having custom environments a while back, but we got stuck due to the relationship between rules and environments. (Environments used to be able to enable/disable rules.) Since environments now just apply globals and parser options, I'd like to revisit allowing custom environments from plugins. This would relieve some of the pressure we get to provide an environment for every possible library.

## Defining

The idea is to export an `environments` property from plugins, just like we export `rules`:

```js
// your plugin
module.exports = {
    rules: {},
    environments: {
        custom: {
            globals: { "$": true }
            parserOptions: { ecmaVersion: 6 }
        }
    }
};
```

## Using

You'd use the same convention to load environments from plugins as you do for loading rules from plugins:

In config files:

```yaml
plugins:
  - myplugin
env:
  es6: true
  myplugin/custom: true
```

In comments:

```js
/* eslint-env myplugin/custom, es6*/
```

**Comment by ilyavolodin** [comment]
For references, here's a PR that was doing it originally: #2024 If I get time, I'll take a look at possibly rebasing it doing some minor modifications to account for updated code.

**Comment by nzakas** [comment]
Working on this.
