### ISSUE TITLE
Document expected error line and column properties

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#4810]
@mjomble pointed out in [#4807 (comment)](https://github.com/eslint/eslint/pull/4807#discussion_r48448802) that http://eslint.org/docs/developer-guide/working-with-rules#invalid-code doesn't mention the optional `line` and `column` properties on the expected error object. We should document their existence and mention cases where they might be necessary.

**Comment by platinumazure** [comment]
Indeed-- those properties have been very useful to me, but I stumbled upon them only by reading the RuleTester source. :+1: from me.

**Comment by nzakas** [comment]
It's also missing mention of `parserOptions`, so that should be added as well.

**Comment by ilyavolodin** [comment]
We also don't mention `parser` and `settings` either. Problem is, for the life of me, I can't find the code that's supposed to handle `parserOptions`, `parser` and `settings` in rule-tester. I know they work, but I can't figure out how!

**Comment by nzakas** [comment]
They are. RuleTester just basically passes that stuff through, IIRC
