### ISSUE TITLE
Run plugin on a file without an extension

### ISSUE THREAD

**Issue by radek-holy** [eslint/eslint#4829]
Hello, I have recently found `eslint-plugin-json`. I'd like to run it on some JSON files that do not have a file extension. If I run `eslint --plugin json --debug .jslintrc` with ESLint 1.10.3, I get
```
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +40ms
  eslint:cli-engine Processing /tmp/test/.jslintrc +3ms
  eslint:cli-engine Linting /tmp/test/.jslintrc +0ms
  eslint:config Constructing config for /tmp/test/.jslintrc +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /tmp/test/.eslintrc.json +1ms
  eslint:config-file Loading JSON config file: /tmp/test/.eslintrc.json +1ms
  eslint:config-file Loading /tmp/test/node_modules/eslint/conf/eslint.json +55ms
  eslint:config-file Loading JSON config file: /tmp/test/node_modules/eslint/conf/eslint.json +0ms
  eslint:config-ops Apply environment settings to config +149ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:config Using /tmp/test/.eslintrc.json +1ms
  eslint:config Loading /tmp/test/package.json +0ms
  eslint:config-file Loading package.json config file: /tmp/test/package.json +0ms
  eslint:config Merging command line environment settings +1ms
  eslint:config Merging command line plugins +0ms
  eslint:cli-engine Load plugin json +77ms
  eslint:cli-engine Linting complete in: 296ms +5ms

/tmp/test/.jslintrc
  2:14  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```
IIUIC, ESLint runs JavaScript checks on the file and thus it fails. This is understandable since there is no way to tell it what is the language of the file. Would it be possible to support my use case? For me, it would be enough to e.g. tell ESLint that it should handle all the given files as if they had a `.json` file extension. But I don't insist on any particular implementation. Surely, there are more systematic ways to support files without proper file extensions.

**Comment by nzakas** [comment]
This isn't possible right now. To make it possible, we'd have to dramatically change how processors work, and unfortunately, we don't have enough people to prioritize this work. 

If you or anyone else wants to investigate, propose, and submit a PR, we can consider it.

**Comment by gronke** [comment]
@radek-holy could you please also post the content of your `/tmp/test/.jslintrc` file. As the log shows eslint tries to access `/tmp/test/.eslintrc.json`, what might look a bit confusing with the given test filename, but over all it looks like you have an error in line 2 of `/tmp/test/.jslintrc`.

**Comment by radek-holy** [comment]
@gronke, I'm not sure I understand you. Anyway. I don't have the file any more but I can reproduce it with following `.jslintrc`:
```json
{
  "continue": true,
  "nomen": true,
  "eqeq": true,
  "plusplus": true,
  "stupid": true,
  "todo": true,
  "vars": true,
  "white": true
}
```

**Comment by platinumazure** [comment]
@nzakas Does the discussion in #5155 seem like something that would help this issue out? Or, put another way, is #5155 the beginning of the "[dramatic] change [to] how processors work" that would be needed to allow this?

**Comment by ilyavolodin** [comment]
I don't think #5155 alone is going to help here. We would need glob support for something like this.

**Comment by nzakas** [comment]
No movement on this, so closing. We'll likely revisit a lot about how plugins work in the future, though, so stay tuned.

**Comment by neilbmclaughlin** [comment]
I was also looking to run eslint using eslint-plugin-json on a file without an extension and, through trail and error, came up with this:

`cat .bithoundrc | node node_modules/eslint/bin/eslint.js --stdin --stdin-filename=temp.json`

The use of the stdin-filename forces the file to be parsed as json rather than js. Just recording this here for anyone who is looking to do the same.
