### ISSUE TITLE
`func-style` has no default

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4834]
As part of https://github.com/eslint/eslint/issues/4809, I'm checking that we have sane defaults in our rules.  [func-style](http://eslint.org/docs/rules/func-style) has no default.

In `eslint:recommended`, we use `[0, "declaration"]`.  Any objections to making this the official default?

**Comment by alberto** [comment]
Current default is `expression`. Should we change it?

**Comment by IanVS** [comment]
Ah, I didn't look close enough.  It looks at first glance from https://github.com/eslint/eslint/blob/ad445184ba8e83cd871dd35c25a14bdfa774111b/lib/rules/func-style.js#L14 that there is no default, but it's handled a few lines down.  I'll make a PR for the docs.
