### ISSUE TITLE
`operator-assignment` has no default

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4835]
[operator-assignment](http://eslint.org/docs/rules/operator-assignment) does nothing if an option is not supplied.  The config in `eslint:recommended` is `[0, "always"]`, so I propose to make this an official default for the rule.

(see https://github.com/eslint/eslint/issues/4809.)

**Comment by alberto** [comment]
That's not true, the rule already defaults to always. See https://github.com/eslint/eslint/blob/master/tests/lib/rules/operator-assignment.js#L79 for an example.

**Comment by alberto** [comment]
I have created PR #4866 to add it to the docs.

**Comment by IanVS** [comment]
Ah you're right, I see now it is setting a default here: https://github.com/eslint/eslint/blob/ad445184ba8e83cd871dd35c25a14bdfa774111b/lib/rules/operator-assignment.js#L109
