### ISSUE TITLE
Rule Proposal: `no-new-symbol`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#4862]
`new Symbol()` always throws a `TypeError`, but people might guess `Symbol` is a constructor.
So this rule reports all `new Symbol()`s.

http://www.ecma-international.org/ecma-262/6.0/#sec-symbol-description
> If NewTarget is not `undefined`, throw a `TypeError` exception.

----

The following patterns are considered problems:

```js
/*eslint no-new-symbol: 2*/
/*eslint-env es6*/

const foo = new Symbol("foo");  /*error `new Symbol()` always throws a TypeError.*/
```

The following patterns are not considered problems:

```js
/*eslint no-new-symbol: 2*/
/*eslint-env es6*/

const foo = Symbol("foo");

// Ignores shadowed Symbol.
function bar(Symbol) {
    const baz = new Symbol("baz");
}
```

**Comment by nzakas** [comment]
Good idea, this is very confusing

**Comment by alberto** [comment]
I'm not familiar with `escope`. Is it enough to check that the Symbol in `references` doesn't come from the global scope?

**Comment by mysticatea** [comment]
I guess the logic is:

```js
var variable = globalScope.set.get("Symbol");
if (variable && variable.defs.length === 0) {
    variable.references.filter(isCalleeOfNew).forEach(report);
}
```

- `variable.defs` is not empty if there is a declaration like `function Symbol() { }` in the source code.
- `variable.references` contains all references to this variable.
- Tests need `{env: {es6: true}}` to define `Symbol` variable.
