### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4888]
In preparing to do the release, I found a large number of test failures. This appears to be related to the ignore file changes (https://github.com/eslint/eslint/pull/3948). The full log is at https://gist.github.com/nzakas/4ef85b9c8b0de95e4976. There's 81 failures in total that need to be resolved before we can do a release.

**Comment by alberto** [comment]
Do they fail by running `npm test`? They are all green on my machine. Did you remember to `npm install`? That bites me from time to time.

**Comment by gyandeeps** [comment]
Its happening on windows machines and it due to this: https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L556

**Comment by alberto** [comment]
Just read on gitter it may be a windows-only issue. That explains why it wasn't caught by CI. I'm running on OSX.
