### ISSUE TITLE
Add AppVeyor

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#4894]
Second shot at adding AppVeyor to eslint project. 
Based on the observation so far these are some of the things which are very annoying about 
`AppVeyor` vs `Travis`:

* Its sequential ie it will run one build at one time. 
  * One build means running on node 4 is one build so if we have more node version then that many build per PR.
* Its very slow as it takes around of 30 mins for 1 PR which include 3 builds.
* If you want to restart the build then you have to restart the whole build for the PR and not just for a particular version of node build. 

**Proposal:**

* We should setup build for just PR and not branches (except for `master` branch)
* We should only run build on NodeJs `4.x` for now.
  * We have see a quick response then we can keep adding more node versions in the future.
* Increase `mocha` timeout to 10000 from 4000 for AppVeyor as its very slow.

**Comment by rpatil26** [comment]
@gyandeeps So AppVeyor is sequential by design or because of our configuration?

Given that it's also slow, is it still worth going?

**Comment by nzakas** [comment]
Sounds like a good approach. We really just need a Windows spot check for path/line ending differences, so just one Node environment should be enough.

**Comment by ilyavolodin** [comment]
@rpatil26 AppVeyor is not sequential, it's just for free OSS plan it only supports one single simultaneous build. Problem is, we've had our share of issues that are only happen in Windows environment, and while most of the ESLint team is using Windows, a lot of PRs are coming from people using OSX/Linux, so we need a way to verify anything that deals with file system.

**Comment by rpatil26** [comment]
Thank you @ilyavolodin for the informative details. I jumped in without the context. :smile:
