### ISSUE TITLE
eslint-config-eslint has duplicate keys.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#4909]
https://travis-ci.org/mysticatea/eslint-plugin-node/jobs/101463149#L202

`js-yaml@3.5.0` seemed to come to check duplicate: https://github.com/nodeca/js-yaml/commit/9ea29ec6aa5e48d3dff3eacf7582818643a0ab0c

**Comment by alberto** [comment]
Not sure I understand the issue, but please be aware we cannot upgrade `js-yaml` because of #4553 :(

**Comment by mysticatea** [comment]
Oh, pinned.

I will do:

- Remove duplicate keys.
- Pinned `js-yaml` of `eslint-config-eslint`: https://github.com/eslint/eslint/blob/master/packages/eslint-config-eslint/package.json#L23

**Comment by alberto** [comment]
I asked again for a new release of inherit:
https://github.com/dfilatov/inherit/issues/25
