### ISSUE TITLE
Hashbang needs to be re-added for autofix

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#4916]
We are currently stripping away hashbangs to allow for linting, however, if the file needs to be fixed, we will not add hashbang back into the file, which will result in the invalid Node.js entry point. See #4878 for more details.

**Comment by lo1tuma** [comment]
The hashbang is only transformed to a comment before parsing the code. The sourcecode text isn’t modified.
At least I can’t produce any broken code when letting eslint automatically fix a file which includes a hashbang.

**Comment by nzakas** [comment]
Yeah, keep in mind that we are not regenerating the source code, we are just inserting into what we read. What's in the AST has no effect on the output of the fixer. 

I think we need a solid case where the current functionality is producing a bug in order to move forward here.

**Comment by platinumazure** [comment]
If nothing else, I'm curious how we handle the range of all elements being affected since a comment involves adding at least two characters (and since hashbangs go at the beginning of a file, this means *all* AST nodes are affected).

**Comment by lo1tuma** [comment]
@platinumazure Looks like the characters [`#!` are replaced with `//`](https://github.com/eslint/eslint/blob/master/lib/eslint.js#L683). So the range information shouldn’t be affected.

**Comment by ilyavolodin** [comment]
I admit that I didn't verify if this is actually an issue before opening a ticket. But I remember that we were doing something with hashbang to allow for the file to be parsed. So if this is not a problem, then this issue can be closed.

**Comment by nzakas** [comment]
Yeah, the approach @lo1tuma mentioned keeps everything pretty tight, so I think we are set. If you run into a bug, please feel free to reopen.

**Comment by platinumazure** [comment]
My only concern is whether or we not have a functional test which attempts to auto-fix code with a shebang, such that the test would fail if someone screwed up the ranges in that hashbang replace code. I'll investigate that tonight if nobody else beats me to it.

**Comment by mysticatea** [comment]
btw, I have a fixable rule for shebang: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/shebang.md
A nd this is working fine :)
