### ISSUE TITLE
Remove default rule configuration for plugins

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4952]
In updating plugins to support environments, I found that we're still supporting `rulesConfig` in plugins. I thought we had removed this feature in 1.0.0, but apparently not.

In carrying through the spirit of not forcing anything on anyone, I think it would be best to remove `rulesConfig` support and replace it with named configurations in plugins (#3659). That way, a plugin can still export rule configuration, but instead of forcing it on users, users can opt-in (just as they do with `eslint:recommended`).

Thoughts?

**Comment by platinumazure** [comment]
Just to make sure I have this right:

* Exporting `rulesConfig` in plugins will be discouraged (possibly deprecated);
* Said export will be ignored by ESLint; and
* Plugin developers are encouraged to create ESLint configuration packages (`eslint-config-*`) to represent one or more recommended configurations?

If I'm understanding correctly, I'm :+1:.

**Comment by nzakas** [comment]
All accept the last one. #3659 lets you define configs directly in the plugin rather than having a separate package.

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
I think that's reasonable if we provide another way of configuring plugins (like mentioned above ability to create configs within plugins).

**Comment by platinumazure** [comment]
@nzakas Thanks, I wasn't aware of that and will check it out.

**Comment by captbaritone** [comment]
:+1: We were recently frustrated by the disparity between the core rules being off by default, and plugins still having rules that were on by default. 

cc @afahim

**Comment by afahim** [comment]
This would be wonderful. +1

**Comment by platinumazure** [comment]
@nzakas Looks like the issue you mentioned is still open with no real indication of progress (including but not limited to a PR). Is that something you're hoping to get in for 2.0.0? I'm not sure it's a good idea to remove this functionality in 2.0.0 without having a replacement available, or is this targeted for 3.0?

**Comment by nzakas** [comment]
We will do both for 2.0.0. I already have this removed.
