### ISSUE TITLE
`sourceCode.getNodeByRangeIndex` performance issue

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#4989]
From https://gitter.im/eslint/eslint?at=569c4f4d3165a6af1a3c588c

`sourceCode.getNodeByRangeIndex` has an unintentional performance issue.

`result` is assigned always a new instance at [L263](https://github.com/eslint/eslint/blob/be9be2fe66aa3e8f36e717e23ebc0a1d43e18f22/lib/util/source-code.js#L263), so the condition at [L269](https://github.com/eslint/eslint/blob/be9be2fe66aa3e8f36e717e23ebc0a1d43e18f22/lib/util/source-code.js#L269) never gets `true`. So even if the matched node was found, this continues traversing until the last.

Currently:

```
// sourceCode.getNodeByRangeIndex(6)
Program ( var answer = 6 * 7; )
    found, dive into...
    VariableDeclaration ( var answer = 6 * 7; )
        found, dive into...
        VariableDeclarator ( answer = 6 * 7 )
            found, dive into...
            Identifier ( answer )
                found, dive into...
            Identifier :exit            // FOUND! I expect to break here but not.
            BinaryExpression ( 6 * 7 )
                Skip!
            BinaryExpression :exit
        VariableDeclarator :exit
    VariableDeclaration :exit
Program :exit
```

Expected:

```
// sourceCode.getNodeByRangeIndex(6)
Program ( var answer = 6 * 7; )
    found, dive into...
    VariableDeclaration ( var answer = 6 * 7; )
        found, dive into...
        VariableDeclarator ( answer = 6 * 7 )
            found, dive into...
            Identifier ( answer )
                found, dive into...
            Identifier :exit
            Break!
```

**Comment by lo1tuma** [comment]
Wouldn’t it be better to remove the additional traversal in `getNodeByRangeIndex` and build a `NodeStore` similar to what we have with the `TokenStore` where we can access nodes directly by range index or location information?

**Comment by ilyavolodin** [comment]
@lo1tuma I'm not sure it's worth it. This is going to eat a lot of memory, and I don't see us using it too often.

**Comment by lo1tuma** [comment]
@ilyavolodin Why do you think it would consume a lot of memory? We already have the AST in memory, the `NodeStore` would store only references to objects that already exist.

**Comment by ilyavolodin** [comment]
@lo1tuma On a large file, we are going to have a lot of AST Nodes, just the hash of index is going to take up memory space, even if content is going to be a reference, it's still not worth the trouble in my mind. I just can't think of a lot of places where we would need to get node by index.
