### ISSUE TITLE
Question: Dealing with incomplete ES 2015 support

### ISSUE THREAD

**Issue by Alaneor** [eslint/eslint#5011]
In ESLint 1.x, we had fine-grained control of which ES 2015 features to enable or disable in the parser. With ESLint 2.x, this seems to have been removed and we can either enable or disable everything (via `parserOptions.ecmaVersion: 6`).

However, even the newest and greatest Node.js version 5.4.1 does not have complete support for ES 2015. Being able to turn off these unsupported features proved to be quite useful since every time I accidentally used some new syntax not yet supported, ESLint would warn me about it right away.

With ESLint 2, there is no such feedback. So, I wonder:

**Is there a way to deal with this in ESLint 2.x?** My current solution is to simply run tests - Node.js will throw the "Unexpected token" error at me and I will know something's wrong. However, not everyone writes unit tests... 😱

Thanks for help!

**Comment by michaelficarra** [comment]
http://eslint.org/docs/rules/no-restricted-syntax

**Comment by ilyavolodin** [comment]
You can also use https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md

**Comment by Alaneor** [comment]
Thanks for all the suggestions. Ultimately I went with the `no-restricted-syntax` rule. For the future reader, here is what I ended up with for Node.js v5.

```js
{
  'no-restricted-syntax': [
    2,
    // Rest parameters (not to be confused with rest arguments)
    'RestElement',
    // Default function parameters
    'AssignmentPattern',
    // Destructuring assignment
    'ObjectPattern',
    // Experimental object/rest spread
    'ExperimentalRestProperty'
  ]
}
```

However, some new regex flags cannot be checked for using this rule.
