### ISSUE TITLE
Remove deprecated rules and update documentation

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5032]
Before we release 2.0 we should remove any deprecated rules that are still around. The only two rules I found are:
- [x] space-before-keywords - replaced by keyword-spacing
- [x] space-after-keywords - replaced by keyword-spacing
- [x] no-arrow-condition - replaced by no-confusing-arrow, no-constant-condition
- [x] space-return-throw-case - replaced by keyword-spacing

We should also updated documentation to reflect removed rules. For example, I just noticed that we removed `space-before-keywords` and `space-after-keywords`, but they do not show up under `Removed` rules in http://eslint.org/docs/rules/

**Comment by gyandeeps** [comment]
And `space-return-throw-case` also.

**Comment by mysticatea** [comment]
And `no-arrow-condition` was replaced with `no-constant-condition` and `no-confusing-arrow`.
http://eslint.org/docs/2.0.0/user-guide/migrating-to-2.0.0#removed-rules

**Comment by ilyavolodin** [comment]
This issue is not complete. Deprecated rules should be noted in `replacements.json` file and `readme.md` should be updated to reflect that the rules have been removed.

**Comment by ilyavolodin** [comment]
Also each .md files for removed rules should be updated with replacement notice.

**Comment by gyandeeps** [comment]
Its already noted in https://github.com/eslint/eslint/blob/master/conf/replacements.json

Yup, forgot to update .md files. Should we just remove .md files?

**Comment by nzakas** [comment]
No, we keep the documentation for old rules so search engine results don't break.

**Comment by gyandeeps** [comment]
Just checked all of the rule's .md file has the replacement notice also.

What is missing?

**Comment by ilyavolodin** [comment]
Oh, in that case, nevermind. I didn't see those changes in your PR, so that's why I assumed that it wasn't made.
