### ISSUE TITLE
no-empty-label errors on labelled if statement

### ISSUE THREAD

**Issue by Qix-** [eslint/eslint#5042]
Labels apply to statements, not loops specifically. This is defined in §12.12 in the [Ecmascript 3](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) and [Ecmascript 5](http://www.ecma-international.org/ecma-262/5.1/#sec-12.12) standards, as well as §13.13 in the [Ecmascript 2015 (6.0) standard](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-labelled-statements).

Grammar (ES3/5):
```
LabelledStatement :
    Identifier : Statement
```
<sup>ES6 (ES2015) grammar not shown since it spans multiple rules</sup>

This means labels also apply to if statements.

```js
someLabel:
if (true) {
	console.log('first');
	break someLabel;
	console.log('second');
}
```

outputs:

```console
$ node iflabel.js
first
```

ESLint seems to treating labelled if statements as invalid. In fact, it appears other block statements are being considered as invalid as well.

```js
var obj = {foo: 'bar', qux: 'qix'};

someLabel:
with (obj) {
	console.log(qux);
	break someLabel;
	console.log(foo);
}
```

outputs:

```console
$ node withlabel.js
qix
```

and even normal blocks:

```js
someLabel: {
	console.log('first');
	break someLabel;
	console.log('second');
}
```

outputs:

```console
$ node blocklabel.js
first
````

However, with the following `.eslintrc`

```json
{
  "rules": {
    "no-empty-label": 2
  }
}
```

ESLint errors out with:

```
3:1  error  Unexpected label "someLabel"  no-empty-label
```

Which is incorrect.

**Comment by ilyavolodin** [comment]
Could you clarify what do you expect to happen in the case of if and block labels?

**Comment by Qix-** [comment]
Well it shouldn't error out. It's a valid label; it's not unexpected.

**Comment by platinumazure** [comment]
Reading the documentation, it seems that the rule is designed to enforce that labels are only used on loops. Perhaps you should turn the rule off in your codebase?

Or are there patterns you need to enforce with this rule?

**Comment by mysticatea** [comment]
Hmmm, interesting, but I'm not sure it's according to the spec.

http://tc39.github.io/ecma262/#prod-BreakableStatement

The spec seems to say `BreakableStatement` is a loop or a switch.

**Comment by michaelficarra** [comment]
@mysticatea It's allowed. BreakableStatement only restricted *unlabeled* break statements.

**Comment by mysticatea** [comment]
@michaelficarra I got it. Thank you!

So I think good to support blocks in this rule.
Also I'm glad the rule warns a label if it's not used in the block. (it may be in other rule)

**Comment by Qix-** [comment]
> Reading the documentation, it seems that the rule is designed to enforce that labels are only used on loops. Perhaps you should turn the rule off in your codebase?

That still doesn't make sense, though. If the rule is designed only to affect loop labels, then why is it erroring out on non-loop block statements?

**Comment by nzakas** [comment]
The rule warns whenever a label is used on something other than a loop. Keep in mind, this is not a parser error, its just a rule restricting where you can use a label. If you want to use labels on more than loops, you can disable the rule.

**Comment by Qix-** [comment]
Isn't `no-empty-label` kind of a misnomer, then?

**Comment by mysticatea** [comment]
Related: #5052, #5059

**Comment by nzakas** [comment]
@Qix- potentially. Labels are primarily designed for use with loops, so you could argue that using them without loops doesn't make sense. 

@eslint/eslint-team anyone have thoughts on this?

**Comment by Qix-** [comment]
Labels were designed for blocks. Period. The spec has been there for ages and there has been no discussion on the standards committee (from what I've seen) to remove such functionality. 

The only language that really supports labels (and the use of `break <label>`) that _doesn't_ support breaking out of non-loops is the C family. JavaScript and Java are the only two I know of that support breaking out of blocks using labels. Most other languages don't support breaking out of for loops using labels to begin with.

So if your argument is that "labels [were] primarily designed for use with loops", then you must only be referring to C/C++. No other major language other than the three mentioned before supports breaking out of loop structures using labels to begin with.

The fact of the matter is this has been in the spec for almost two decades. Disregarding the spec and instead going by "what makes sense" isn't what I would want in a linter. Linters are there to be _correct_ first, opinionated later.

This rule should definitely be renamed, or adapted to allow labels on block structures.

**Comment by nzakas** [comment]
In your view, what is it that this rule should warn about?

**Comment by Qix-** [comment]
Labels on things that make no sense.

```js
someLabel: var i = 100;
```

**Comment by mysticatea** [comment]
IMO, if this rule's behavior is changed to warn only non-block statements, the rule almost comes to overlap with #5052.
Maybe this is a good timing to rename this rule?

**Comment by Qix-** [comment]
@mysticatea agreed on that point. If #5052 is added then this should be changed to something along the lines of `no-non-loop-labels`. #5052 would fix this problem.

**Comment by nzakas** [comment]
@mysticatea doesn't it already overlap?

**Comment by mysticatea** [comment]
Yes a bit.
But now, no-empty-lavel prevents us using labels on non loops, and no-unused-labels prevents us using unused labels on loops.
On the other hand, if the behavior of no-empty-label is changed, when we use the two rules, no-empty-label prevents nothing. (Exactly a case: `A: break A`; but it seems to be an unused expression)

**Comment by michaelficarra** [comment]
@mysticatea A useless statement, not an unused expression.

**Comment by mysticatea** [comment]
@michaelficarra Oh, yeah!

**Comment by nzakas** [comment]
@mysticatea does that mean no-empty-label can be removed? Or is it still doing something unique?

**Comment by mysticatea** [comment]
Current `no-empty-label` is doing unique, it prevents labels on non loop. IMO, labels on non loop is not enough well-known, so this is a worth. But the name `no-empty-label` is a bit of confusing.

I'm thinking we have 4 approaches.

1. Keeping as is. The name `no-empty-label` is a bit of confusing, but it's working fine.
2. Renaming `no-empty-label` to `no-non-loop-label`. Hmm, double negation.
3. Deleting the `no-empty-label` rule, then adding an option to allow labels on loops to the `no-labels` rule (`{"allowLoop": true}`, default is `false`). This looks good to me.
4. Just deleting the `no-empty-label` rule. Labels on non loop blocks are not danger, so I'm OK.

**Comment by Qix-** [comment]
Why not `loop-labels`? I know it breaks the general convention of the rule names, but it might be more clear to break dogma in this case.

3 sounds great. I'm all for that.

> Labels on non loop blocks are not danger, so I'm OK.

They're not dangerous but the problem is that most javascript developers don't even know you can do it. I've used it literally _once_ in production (hence this issue being opened) where it removed the need for a second loop in a mathematical algorithm, greatly improving performance. Usually you're doing something wrong if you're using labels in such a way.

**Comment by nzakas** [comment]
I think 3 sounds good, too
