### ISSUE TITLE
Rule Proposal: `template-curly-spacing`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#5049]
This is a rule for a stylistic issue.

We can write expressions in template strings with `${` and `}`.

```js
`hello, ${people.name}!`
```

This rule enforce usage of spacing inside of the `${` and `}`.

This rule have an option:

- `"always"` - It expects one or more spaces between the expression and the `${` and `}`.
- `"never"` (by default) - It expects no space between the expression and the `${` and `}`.

The following patterns are considered problems:

```js
/*eslint template-curly-spacing: 2*/

`hello, ${ people.name }!`  /*error Unexpected space(s) after '${'.*/
                            /*error Unexpected space(s) before '}'.*/
```

The following patterns are considered problems with `"always"`:

```js
/*eslint template-curly-spacing: [2, "always"]*/

`hello, ${people.name}!`  /*error Expected space(s) after '${'.*/
                          /*error Expected space(s) before '}'.*/
```

The following patterns are not considered problems:

```js
/*eslint template-curly-spacing: 2*/

`hello, ${people.name}!`
`hello, ${
    people.name
}!`
```

The following patterns are not considered problems with `"always"`:

```js
/*eslint template-curly-spacing: [2, "always"]*/

`hello, ${ people.name }!`
`hello, ${
    people.name
}!`
```

Related Rules:

- [array-bracket-spacing](http://eslint.org/docs/rules/array-bracket-spacing)
- [block-spacing](http://eslint.org/docs/rules/block-spacing)
- [computed-property-spacing](http://eslint.org/docs/rules/computed-property-spacing)
- [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing)
- [space-in-parens](http://eslint.org/docs/rules/space-in-parens)

**Comment by nzakas** [comment]
:+1:

**Comment by mysticatea** [comment]
I'm working on this.
