### ISSUE TITLE
Add label for issue state

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5053]
It would be nice if we had labels to indicate if an issue is assigned to someone, so we can easily filter those who are not. Ideally @eslintbot could also take care of the work of adding and removing the labels when issues are created and/or PRs are submitted.

**Comment by gyandeeps** [comment]
FYI, issue can be assigned to people who have write/part of the organisation. So that means it can be only assigned to us and not public members. With that we wont be able to benefit a lot with this enhancement.

**Comment by alberto** [comment]
I don't mean assigning the issue to someone, but adding a label to indicate someone is working on it. Precisely because assigning issues is just for the org.

**Comment by gyandeeps** [comment]
Ah i see.
I guess that would be very difficult job for our best friend(@eslintbot) to evaluate that.

**Comment by alberto** [comment]
I was thinking a label could be added/removed to the issue when a PR referencing it in the title was submitted.

**Comment by nzakas** [comment]
It's possible to add a label when a PR is opened and has the correct commit summary format. The problem I see is that the label can easily end up out of sync with reality if you want it to mean "someone is working on this". For instance, suppose someone puts the wrong issue number in the PR. The wrong issue would have the label. Then thecPR is updated with the correct issue, so the correct issue gets the label while the wrong one still has a label (because how would we know to remove it?)

So, I'm concerned that the false positive aspect of this idea could lead to people ignoring issues incorrectly.

**Comment by alberto** [comment]
That was my main concern, but I think that rarely happens and we can fix it by hand.

Anyway, even if it is not automatic, do you see value in having this?

**Comment by zandaqo** [comment]
Wouldn't "help wanted" tag suffice for this? It was my understanding that label "help wanted" meant that no one was working on the issue, though later I discovered that it is added by default to most issues. Maybe it should be reserved for issues that have no related PR or ongoing work?

**Comment by nzakas** [comment]
@alberto I don't see much value in it, myself. There will be problems both applying manually and automatically, so ultimately it will be hard to rely on the label without manually verifying. 

@zandaqo "help wanted" is for issues that will not get done unless there's a contribution from a someone who's not on the team.

**Comment by alberto** [comment]
Currently, not having the label means I have to manually verify each issue to see if it's already in progress (many times, since I usually forget), but maybe it's just me and my bad memory. :)

**Comment by nzakas** [comment]
You would still need to do that because you couldn't rely on a label being accurate. Or, if you did rely on the label, you'd miss things that needed attention.

**Comment by alberto** [comment]
I think if we tag it manually there is not a problem with inaccuracy. just for PRs that get abandoned, and those are few and easy to track. it's also easy to filter and sort the least recently updated issues.

Then, there is the burden of tagging, but that would be shared among the team, and done just once.

**Comment by nzakas** [comment]
I'm very skeptical that this has value, but we can give it a try. Please describe the exact process as you imagine it.

**Comment by platinumazure** [comment]
I think what we really need is for GitHub to implement first class support for issues being listed as having PRs which ref or fix them. Trying to use labels as a workaround is fraught with problems.

**Comment by nzakas** [comment]
@platinumazure yes, that would be ideal. However, GitHub doesn't seem too responsive to such feedback (I've been trying: https://github.com/dear-github/dear-github), so we might as well try something.

**Comment by alberto** [comment]
Nevermind, if no one else in the team sees this as something valuable, then it's not worth adding it.
