### ISSUE TITLE
Ignore all JSON files

### ISSUE THREAD

**Issue by finico** [eslint/eslint#5076]
in this topic [Ignoring json](https://groups.google.com/forum/#!topic/eslint/UGoM2h4O9Dg) Nicholas Zakas says
> All JSON files are ignored by default...

but in my case
```
$ ./node_modules/.bin/eslint ./**
/<path_to_project>/package.json
  2:9  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

my `.eslintignore` is empty
```
$ ./node_modules/.bin/eslint -v
v1.10.3
```

**Comment by michaelficarra** [comment]
You're explicitly passing JSON files. JSON files are ignored by traversals done by eslint only. Pass the directory itself instead of globbing.

**Comment by finico** [comment]
Oh, sure..
@michaelficarra thanks
