### ISSUE TITLE
Help wanted: Non-code contributions to ESLint

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5083]
As ESLint has grown in popularity (we now easily have over 1 million downloads every month), it's taking more and more effort to manage the project. While it's probably obvious that we appreciate code contributions, there are a lot of non-code contributions that could greatly help the project.

**Note:** These are unpaid, volunteer positions. We're hoping that giving back to the community on a project that is widely used will be good experience for everyone involved.

## Community Management

There are a lot of aspects to community management that we can use help with:

* Running the [ESLint Twitter account](https://twitter.com/geteslint)
  * Responding to requests for help directed at the account
  * Routinely running Twitter searches for "eslint" and to see if anyone is having trouble and hasn't pinged us
  * Retweeting new and interesting ESLint integrations, presentations, and articles.
* Monitoring the [ESLint chatroom](https://gitter.im/eslint/eslint) both to answer questions and moderate the chatroom
* Triaging issues as they come in to ensure they have enough information and trying to determine if they are bugs or enhancement requests.
* Moderating discussions on issues and pull requests to ensure they remain positive and there aren't violations of the code of conduct.
* Nudging core team members when issues or pull requests are waiting for their response.
* Writing up release summaries for each reach minor or major release (changelogs are autogenerated, but we hand-edit the blog posts to include highlights from each release)

All of this could be done by one community manager or a team of people.

## Design Help

One of the things that makes ESLint users happy is our website and documentation. We've been using the same design since ESLint began, and we'd like to do some updates:

* An updated logo - we like the current one, but would like to evolve it. We also like the color scheme (purple!). We'd just like an update to the logo and typography that would be good for stickers, tshirts, and more. (https://github.com/eslint/eslint/issues/5085)
* An updated website design - in particular, we'd like to redesign the homepage (eslint.org) to be more informative about what ESLint does and how to get started. (see https://github.com/eslint/eslint.github.io/issues/185)
* Better information architecture - our website doesn't have a lot of organization, and we'd like to make it easier to find the information people need. (see https://github.com/eslint/eslint.github.io/issues/186)

This could also be one person or any number of people. 

## Other Ideas?

If these don't appeal to you or aren't within your means but you'd still like to help out in some way, let us know what you'd be interested in doing. We really can use all the help we can get. :)

**Comment by montogeek** [comment]
I can help in the chat room answering questions :)

**Comment by frantic1048** [comment]
May I could help with the logo and typography >_<

**Comment by nzakas** [comment]
@montogeek great, thanks! All you have to do is hang out there. :)

@frantic1048 awesome, we'd love some help. I opened a separate issue for the logo redesign here: https://github.com/eslint/eslint/issues/5085. Feel free to submit something on the issue whenever you have time.

**Comment by SamuelEnglard** [comment]
I can help with website, do you want to open a separate issue for that?

**Comment by montogeek** [comment]
A note about the website: please add more examples, just a single line showing how it should be defined is good.

**Comment by omerbalyali** [comment]
I can help with branding and website right off the bat. Check out my portfolio: http://www.omerbalyali.com

**Comment by nzakas** [comment]
An issue to start talking about website design: https://github.com/eslint/eslint.github.io/issues/185

Feel free to ask more questions there.

**Comment by pedrottimark** [comment]
Glad to provide some suggestions and constructive critique on proposed improvements to information architecture for interior pages of the Web site.

**Comment by nzakas** [comment]
@pedrottimark thanks so much. I opened a separate issue for that here: https://github.com/eslint/eslint.github.io/issues/186 Any suggestions greatly appreciated.

**Comment by ilyavolodin** [comment]
@nzakas We might want to modify governance model to include non-code contributors.

**Comment by nzakas** [comment]
@ilyavolodin feel free to propose something

**Comment by sotayamashita** [comment]
I can help ESLint chatroom in Japanese and English !!

**Comment by mysticatea** [comment]
Ooh, よろしくです @sotayamashita :)

**Comment by sotayamashita** [comment]
@mysticatea よろしくです :smile: (Nice to meet you !!)

**Comment by tsaiDavid** [comment]
Wouldn't mind helping with the Twitter at all!

**Comment by nzakas** [comment]
Thanks @sotayamashita. There's nothing very official to do, but if you hang out in the chatroom and help to answer questions, that will help!

@tsaiDavid that would be great! would you mind sending a note to the mailing list so we can discuss some of the details?

**Comment by tsaiDavid** [comment]
@nzakas - totally, added a note to the group (Google Group) - you can reach out to me via email too if that makes sense: **david@whataniceguy.com**

**Comment by faceleg** [comment]
I can do my best to help triage issues. You might want to talk to @sheerun about how the bower team is handling this, we went through / are going through similar organisational changes.

**Comment by platinumazure** [comment]
@nzakas Let me know if I can help with triaging issues.

**Comment by nzakas** [comment]
@faceleg @platinumazure thanks, let me see if I can set you up.

**Comment by nzakas** [comment]
@faceleg @platinumazure I haven't forgotten about you. It's just that GitHub doesn't have an "issues only" permission for repos, so I'm trying to figure out how to make this work. Thanks for your patience.

**Comment by faceleg** [comment]
:)

**Comment by nzakas** [comment]
Okay @platinumazure and @faceleg. I'm taking a stab at writing up how we're triaging issues currently:
https://github.com/eslint/eslint.github.io/blob/maintainerguide/docs/maintainer-guide/issues.md

I'll add you both to the repo, just please don't push directly to the repo or merge pull requests.

**Comment by faceleg** [comment]
I was coming here to ask for exactly that, thanks! 

Don't worry, I will remain strictly comment-only.

**Comment by platinumazure** [comment]
Thanks! Incidentally, I couldn't toggle any labels on an issue I was triaging-- I wonder if it's a prospective thing only? Anyway, I also promise not to push to the repo or merge pull requests.

**Comment by nzakas** [comment]
@platinumazure you should have received an invite from GitHub. You need to accept the invite before changes take effect.

**Comment by platinumazure** [comment]
My mistake, I've accepted the invitation and I believe all is well. Thanks!

**Comment by nzakas** [comment]
Closing for now. Thanks to everyone who volunteered.
