### ISSUE TITLE
Problems with config file extends/plugins resolution and home directory

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5164]
With 2.0.0-rc.0, the `extends` and `plugins` fields of config files are resolved relative to the config file itself. This can cause issues when, for example, the home directory config file is used (`~/.eslintrc`). In that case, the resolution for `extends` and `plugins` would begin in the home directory rather than in the project directory, meaning that the shareable config or plugin won't be found. As a concrete example:

1. The project is in `~/projects/foo`
1. The project has no local `.eslintrc` file
1. There is a `~/.eslintrc` file that references `eslint-config-bar`
1. The `eslint-config-bar` package is installed in `~/projects/foo/node_modules/eslint-config-bar`

In this example, ESLint will not find `eslint-config-bar` because the search for that module will begin in `~/node_modules` because that's relative to the config file.

## Possible Solutions

1. If the config file path is a descendant of the CWD, use the config file path.
1. If the CWD is a descendant of the config file path, use the CWD.
1. If the config file path and CWD are not in the same hierarchy, just use the default behavior of `require`.

**Comment by ilyavolodin** [comment]
Just for a record, here's another example that will not work with this change:

1. Project is located in `~/projects/foo`
2. `.eslintrc` file is located in the project root folder and uses plugin `blah`
3. Subdirectory `~/projects/foo/bar` is the one that has `package.json` and `node_modules` folder, with plugin `eslint-plugin-blah` installed in it.
4. ESLint is run from `~/projects/foo/bar`

This would've worked with old behavior, but it would not find plugin with the new behavior.

**Comment by ilyavolodin** [comment]
And, again, for the record. This also means that even if you have ESLint installed globally, you should install plugins and configs locally, relative to the location of the `.eslintrc` file. This is a major breaking change from previous behavior (not necessarily a bad one, just major change).

**Comment by nzakas** [comment]
Global/local differences discussed here: https://github.com/eslint/eslint/issues/5160

**Comment by ilyavolodin** [comment]
Yes, just wanted all of the changes noted in one place.

**Comment by albertosantini** [comment]
I vote for solution 3: using `require`.

I read again the following docs:
- [Configuration Cascading and Hierarchy](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)
- [Shareable Configs](http://eslint.org/docs/developer-guide/shareable-configs)

I recap the complete configuration hierarchy:

1) Inline configuration
2) Command line options
3) Project-level configuration
3.4) In the absence of any configuration from (3.1) thru (3.3), fall back to a personal default configuration in `~/.eslintrc`.
4) NEW - If the config file path and CWD are not in the same hierarchy, just use the default behavior of require.
5) NEW - Global-level configuration (local config extending global plugins/configs), like point 4 (use case #5160).

`require` should resolve both issues, #5160 and #5164 and it should not be a breaking change.

**Comment by nzakas** [comment]
Starting work on this.

**Comment by nzakas** [comment]
Okay, so after digging around in the code a bit, it seems like the best solution is this:

If the config file path is a descendant of the *project path*, then resolve relative to the config file. Otherwise, resolve relative to `__dirname` (which is basically what `require()` does).

The project path is the project that has ESLint installed. For instance:

```
~/projects/my-project
```

That is different than the CWD, because the CWD can change from run to run but the project path won't. I can calculate the project path by looking up the directory structure from `__dirname`.

I believe this will also solve #5160, but need to try it out.
