### ISSUE TITLE
(eslint:recommended) which rules are new or have been updated in v2

### ISSUE THREAD

**Issue by darkred** [eslint/eslint#5232]
In the [announcement post for the v2 release](http://eslint.org//blog/2016/02/eslint-v2.0.0-released) it says that:

> 
> **eslint:recommended Updated**
> 
> We've updated the rules we recommend as a starting point. If you're extending `eslint:recommended`, then you should double-check your code after upgrading as there are new recommended rules (all of the added rules help identify errors, no stylistic rules were added)

But in the [rules page](http://eslint.org/docs/rules/) it doesn't show which of the recommended rules in v2 are new or have been updated _(there's only this paragraph in: [Migrating to v2.0.0](http://eslint.org/docs/user-guide/migrating-to-2.0.0#default-changes-when-using-eslintrecommended))_

So, could you please update the rules page with this extra info?

**Comment by mysticatea** [comment]
Thank you for this issue.

As far as I remember, rules which were added to `eslint:recommended` are below:

- [array-callback-return](http://eslint.org/docs/rules/array-callback-return)
- [constructor-super](http://eslint.org/docs/rules/constructor-super)
- [no-case-declarations](http://eslint.org/docs/rules/no-case-declarations)
- [no-class-assign](http://eslint.org/docs/rules/no-class-assign)
- [no-const-assign](http://eslint.org/docs/rules/no-const-assign)
- [no-dupe-class-members](http://eslint.org/docs/rules/no-dupe-class-members)
- [no-empty-pattern](http://eslint.org/docs/rules/no-empty-pattern)
- [no-new-symbol](http://eslint.org/docs/rules/no-new-symbol)
- [no-self-assign](http://eslint.org/docs/rules/no-self-assign)
- [no-this-before-super](http://eslint.org/docs/rules/no-this-before-super)
- [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline)
- [no-unused-labels](http://eslint.org/docs/rules/no-unused-labels)

I will double check and make PR.

**Comment by mysticatea** [comment]
Oops, `eslint:recommended` has not included `array-callback-return`.
