### ISSUE TITLE
Typo error in consistent-this.md options

### ISSUE THREAD

**Issue by nfroidure** [eslint/eslint#5240]
https://github.com/eslint/eslint/blob/master/docs/rules/consistent-this.md#options

**Comment by albertosantini** [comment]
Thanks for the feedback.

Where is the typo?

**Comment by albertosantini** [comment]
I see. Thanks for the PR.

(Next time add `working on it`) :)

**Comment by nfroidure** [comment]
@albertosantini ok, thanks for working on eslint, best linter ever ;)
