### ISSUE TITLE
ESLint@2 only working with npm@3?

### ISSUE THREAD

**Issue by Turbo87** [eslint/eslint#5241]
It appears to me that ESLint@2 is only working with npm@3 now. Is that correct?

I was trying to run [mocha-eslint](https://github.com/BadgeLabs/mocha-eslint) with ESLint@2 and npm@2, but it complained that it `Cannot find module 'espree' from '/Users/tbn/Code/mocha-eslint/node_modules'`. If I use npm@3 instead it works fine.

I've stepped through the code and it looks like ESLint@2 expects `espree` (or any other parser/package) to be installed next to `eslint` in the main `node_modules` folder, while ESLint@1 was apparently okay with `espree` being nested in `node_modules/eslint/node_modules/espree`.

Has this been changed on purpose or should it be considered a bug?

In my limited knowledge the fix should be relatively easy by first looking for the package in the main `node_modules` and if that fails fallback to looking in `node_modules/eslint/node_modules` instead.

**Comment by BYK** [comment]
I had no problem using ESLint@2.0.0 with NPM@2 but I didn't do a clean install. This is with Node v4. It would be great if you can also provide your Node version.

**Comment by BYK** [comment]
I've also verified I have `node_modules/eslint/node_modules/espree` and not `node_modules/espree`. Does this help?

**Comment by Turbo87** [comment]
@BYK you can try it with https://github.com/Turbo87/mocha-eslint/tree/30b2f3e987cc44fa641969058fa5ab3be6498f6d:

- `nvm use 4` (results in `node v4.2.4 (npm v2.14.12)` for me)
  - `rm -rf node_modules && npm install && npm test` -> fails

- `nvm use 5` (results in `node v5.4.1 (npm v3.3.12)` for me)
  - `rm -rf node_modules && npm install && npm test` -> success

**Comment by BYK** [comment]
@Turbo87 - I can verify that I hit the same problem when I followed your example. Using Node v4.3.0 and NPM v2.11.0

**Comment by Turbo87** [comment]
good to know, thanks for the fast reply and taking the time to reproduce this!

**Comment by BYK** [comment]
Okay, I think I now understand the issue. Since `espree` is the default parser, you shouldn't be setting the `parser` value since ESLint expects the parser to be installed in the project folder, not inside `eslint` folder. Does that make sense?

@nzakas - can you verify me?

**Comment by Turbo87** [comment]
@BYK removing `"parser": "espree"` from `.eslintrc` indeed seems to solve the problem. Is there a reason for still doing the lookup if the parser is set to `espree`?

**Comment by ilyavolodin** [comment]
That's an interesting bug. @Turbo87 we don't make a special case for `espree` it's just a default, so it doesn't have a separate code-path for `espree` and handles it as any other parser.

**Comment by nzakas** [comment]
This is due to the change in how parser path is calculated. When `oarser` is provided, its path is calculated differently in 2.0.0 than in 1.x. We should probably just remove `parser` if it's set to "Espree" so the default case is used.

**Comment by Turbo87** [comment]
@nzakas that is what I was suggesting, yes. It might prevent people from using different `espree` versions though than the one installed for `eslint`, but I don't think that would be a big issue.

**Comment by kaicataldo** [comment]
I can make a PR for this, if you'd like. Is the default parser set in a config file somewhere that we can check against, or should we be checking if `parser === 'espree'` manually?

**Comment by platinumazure** [comment]
I'm not sure I agree with ignoring the `espree` parser specified manually. It could be that someone has monkey-patched it and needs custom behavior (or has pinned it as a dependency).

I think it would be much better to generate a warning when the parser couldn't be found, and if the parser is espree, we could note that the configuration setting should be removed unless the user is trying to use a specific version of espree that they are managing themselves.

**Comment by kaicataldo** [comment]
Totally aware more discussion might be needed, but thought I'd take a stab at fixing this :)

**Comment by nzakas** [comment]
@platinumazure that situation doesn't apply. In 1.x, you could not load anything other than the bundled Espree. This change would ensure the 1.x behavior without errors.

**Comment by Turbo87** [comment]
@kaicataldo did you open a PR for that fix commit yet?

**Comment by kaicataldo** [comment]
Yep! https://github.com/eslint/eslint/pull/5247

**Comment by Turbo87** [comment]
@kaicataldo ah awesome, was missing the crosslink to here ;)
