### ISSUE TITLE
2.0 no-new-symbol rule redundant?

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#5250]
I'm confused why `no-new-symbol` is a rule when http://eslint.org/docs/rules/no-new-wrappers should already be covering `Symbol`?

**Comment by michaelficarra** [comment]
I may want to allow `new Boolean`, but `new Symbol` is an error, plain and simple. They deserve to be separate.

**Comment by ljharb** [comment]
That seems like it'd be an option to `no-new-wrappers` - the name of which means "the entire rule is to forbid using `new` with primitives' wrapper constructors".

While I'm not sure why anyone would want to allow `new Boolean` rather than `Object(true)` or similar, it doesn't make any sense to me to make an entirely separate rule for what "no new wrappers" clearly should subsume.

**Comment by mysticatea** [comment]
Yeah, I had considered about adding `new Symbol` to `no-new-wrappers`. But I thought `Symbol` is not a wrapper because the wrapper object of symbols doesn't exist, so I made a new rule.

**Comment by ljharb** [comment]
@mysticatea absolutely it exists. `Object(Symbol())` is a wrapped Symbol object.

**Comment by mysticatea** [comment]
Is `foo instanceof Symbol` true?

**Comment by ljharb** [comment]
@mysticatea `Object(Symbol()) instanceof Symbol` is absolutely true. It is an axiom that will never be violated that `Object(primitive) instanceof PrimitiveWrapper` will always be true, even when `new PrimitiveWrapper()` throws.

**Comment by mysticatea** [comment]
On I had not known it. Hmm.

**Comment by SpadeAceman** [comment]
The point made by @michaelficarra remains valid – `new Symbol` [throws](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), which means `no-new-symbol` covers a true coding error. Whereas `no-new-wrapper` attempts to flag a likely error of *intent*, which otherwise won't throw when executed. Both rules make sense to have separately. (`Object(PrimitiveWrapper())` isn't flagged or handled by either rule.)

**Comment by nzakas** [comment]
`Object`, `Number`, and `Boolean` are wrappers and return an object when used with `new`. `Symbol` is not a wrapper object and throws an error if used with `new`. So the former is valid but not preferred syntax while the latter is invalid. Two different considerations, so two different rules.
