### ISSUE TITLE
Unable to extend modules from global node_modules

### ISSUE THREAD

**Issue by sudaraka** [eslint/eslint#5255]
`extends: '@scope/myrules'` was not attempting to load
`@scope/eslint-config-myrules` module that installed/linked in the global
`node_modules`.

ESLint version 2.0

Issue started around v2.0.0-beta.3

P.S. I'm working on a fix.

**Comment by albertosantini** [comment]
Did you read this issue https://github.com/eslint/eslint/issues/5160?

**Comment by sudaraka** [comment]
@albertosantini yes I saw that issue, but if I'm not mistaken your issue is with globally installed eslint and config, correct?, and has your issue been solved in the released v2?

In my case I have eslint installed in my project `/home/me/work/myproject/node_modules` and my base config is in `/home/me/opt/npm/lib/node_modules`. And in this setup it still fails to find the config module.

I had similar issues with other node modules before and my solution was to set NODE_PATH environment variable so they can find the global node_modules directory.

I have fixed my issue by making `resolve.sync` lookup NODE_PATH in addition to relative path (https://github.com/sudaraka/eslint/commit/643e8030b6903f49b2aaebf7d8704691b6851b6a), but I will wait for your reply before submitting the PR.

**Comment by albertosantini** [comment]
Correct. I suggested that reading only to give a minimal of context.

Your use case, if I understood correctly, is the following one:
- eslint tool installed in the project 
- eslint config installed in the project
- eslint config extension installed globally (so called shareable config)

Really I don't know if it is intentional not to mix the installations, local eslint tool and global shareable configs.

Waiting an illuminating reply from another member. :)

**Comment by sudaraka** [comment]
@albertosantini your are correct about my setup.

What I have in global is the base rules for all my projects and keep adjusting it from time to time. Therefore I need that module to be global so changing one place applies to all projects without publishing and updating each time.

I understand my setup can be an edge case, I will submit the PR anyway as it doesn't disrupt anything (hopefully).

**Comment by sindresorhus** [comment]
You should not be using `NODE_PATH`... It's a big anti-pattern.

From the Node.js [docs](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) about it:

> **You are highly encouraged to place your dependencies locally in node_modules folders.**

Just add the config as a local dependency.

> Therefore I need that module to be global so changing one place applies to all projects without publishing and updating each time.

That's not how Node.js or npm works anymore. Stop trying to work around it and force your tools to do the same. Use `npm link`, git dependency, a tool, https://docs.npmjs.com/files/package.json#local-paths, etc, instead.

**Comment by ilyavolodin** [comment]
@sudaraka Currently if eslint is installed locally, all of the configs/plugins should also be installed locally, including the ones you are extending from. If you, for some reason want to extend globally installed config, you will need to provide full path when extending. This is working as designed.
We will be taking a look at the whole global vs. local installation in v3.0.0 timeframe as it's been causing a lot of confusion.

**Comment by sudaraka** [comment]
Ok, thanks everyone for the information.

For now I'm settling for symlinking global node_modules to `$HOME/node_modules`. Hopefully we'll get a better solution in the future.
