### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by WhyEvenTry** [eslint/eslint#5260]
**What version are you using?**
eslint 2.0.0 (for node.js 5.6 code using ES 2015)

**What did you do?**
Create a test file with this code:

```
'use strict';

/**
 * @returns {Promise.<string|Buffer>}
 */
function test () {

}
```

The eslintrc is the same as the one I attached to this issue: https://github.com/eslint/eslint/issues/5237 (linked in the first comment)

**What happened?**

The JSDoc syntax `@returns {Promise.<type1|type2>}` causes an error:

```
C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:111
            currentType = type.expression.name;
                                         ^

TypeError: Cannot read property 'name' of undefined
    at getCurrentExpectedTypes (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:111:42)
    at C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:153:35
    at Array.forEach (native)
    at validateTagType (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:150:18)
    at C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:272:21
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\rules\valid-jsdoc.js:208:24)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.leaveNode (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:51:22)

```

I checked the file causing the error, line 111: https://github.com/eslint/eslint/blob/master/lib/rules/valid-jsdoc.js#L110

When I add a `console.log` statement I can see that it is not safe to assume that `type.expression` exists, this is what `type` looks like when the error occurs:

```
{                                       
    "type": "UnionType",
    "elements": [
        {
            "type": "NameExpression",
            "name": "string"
        },
        {
            "type": "NameExpression",
            "name": "Buffer"
        }
    ]
}
```

Independent of if that is the correct syntax for documenting promises - and at least WebStorm interprets this exact syntax correctly and offers the correct auto-completion results for `then(...)` chains on this promise, with methods for the two types on the result - it should not throw.

**Comment by ilyavolodin** [comment]
Thanks for a nice bug report. @mysticatea @nzakas Could you take a look at this? I think rule shouldn't error out, even if the format is slightly incorrect (and I don't know if it is or not).

**Comment by nzakas** [comment]
The format is correct, we're just making an incorrect assumption that the format always has `name`. Definitely a bug.

**Comment by gyandeeps** [comment]
@WhyEvenTry Can you please share the configuration for the rule?
I used it from the file you linked, I am not able to reproduce the error with that config.

**Comment by WhyEvenTry** [comment]
```
module.exports = {
    "root": true,
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 6
    },
    "env": {
        "es6": true,
        "node": true
    },
    "rules": {
        "valid-jsdoc": [2, {
            "requireParamDescription": false,
            "requireReturnDescription": false,
            "prefer": {"return": "returns"},
            "requireReturn": false,
            "preferType": {
                "String": "string",
                "Number": "number",
                "Boolean": "boolean",
                "object": "Object"
            }
        }]
    }
};
```

**Comment by BYK** [comment]
I was able to reproduce this with the provided configuration. Working on a fix...

**Comment by BYK** [comment]
This is taking a bit longer than I expected so anyone willing to give it a try, don't wait for me :)

**Comment by nickyout** [comment]
Running against this as well, using what [Google's Closure compiler page](https://developers.google.com/closure/compiler/docs/js-for-compiler#types) calls the 'Record Type' notation (`{{width: number, height: number}}`). 

I'm not sure what page is the most dictating source on JSDoc, but since [usejsdoc's page on @type](http://usejsdoc.org/tags-type.html) also refers to Google's page and I have yet to find a better page on this topic, I would say Google's page is a reasonable set of notations to be able to swallow.

Looks like an interesting challenge.
