### ISSUE TITLE
2.0 env es6: imperfect detection of calling super

### ISSUE THREAD

**Issue by ta2edchimp** [eslint/eslint#5261]
Correct callings of `super()` in a constructor are not correctly detected.  
Affects rules:

* `constructor-super`
* `no-this-before-super``

**What version are you using?**

```
$ eslint --version
v2.0.0
```

**What did you do?**

I created a class, extending from another class. Within the constructor, called `super()` and accessed properties via `this`. So far no problems.  
When creating new blocks (for example, using a `for ... of` loop) within the constructor, the previously correctly detected call of `super()` is somehow rendered obsolete, triggering the rules mentioned above.

`test.js`:

```JavaScript
/* eslint-env es6 */
/* eslint constructor-super: 2 */
/* eslint no-this-before-super: 2 */
class A {
  constructor () {
    this.foo = 'foo';
  }
}

class B extends A {
  constructor () {
    super();
    // This works: `super` is called before accessing `this`
    this.foo = 'FOO';
  }
}

class C extends A {
  constructor () {
    super();
    // This works: `super` is called before accessing `this`
    this.foo = [];

    const arr = [];
    for (const item of arr) {
      this.foo.push(item); // Does not work
    }
    this.bar = 'bar';      // Does not work
  }
}
```

**What happened?**

Running `eslint test.js` outputs the following:

```
test.js
  19:3  error  Lacked a call of 'super()' in some code paths  constructor-super
  26:7  error  'this' is not allowed before 'super()'         no-this-before-super
  28:5  error  'this' is not allowed before 'super()'         no-this-before-super

✖ 3 problems (3 errors, 0 warnings)
```

**What did you expect to happen?**

The calls of `super()` in class B's and class C's constructors should be detected correctly and the three errors concerning class C's constructor method should not have been yielded.

**Further observations**

When removing the access to `this` within the `for ... of` loop's block and after it, the false triggering of the `no-this-before-super` error yields vanish, the `constructor-super` rule still yields an error.

```JavaScript
    // ...
    for (const item of arr) {
      // New block by using for...of loop still
      // erroneously triggers constructor-super rule
    }
    // ...
```

Even when removing only the code within the `for ... of` loop, the previously correct detection of `super()` becomes forgotten and `no-this-before-super` yields an error:

```JavaScript
    // ...
    for (const item of arr) {
      // New block by using for...of loop still
      // erroneously triggers constructor-super rule
    }
    this.bar = 'bar';  // Will trigger no-this-before-super
    // ...
```

**Comment by ilyavolodin** [comment]
Thanks for the report. @mysticatea could you take a look? Sounds like a bug to me. (I know I keep mentioning you on all of those issues, but that's what you get for creating all of those fancy rules:-)

**Comment by mysticatea** [comment]
Thank you for this issue.

I confirmed this, I will fix.
I'm sorry for a number of my bugs! :astonished:
