### ISSUE TITLE
Augment eslintbot to annotate PRs with why Travis or AppVeyor failed?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#5268]
We could probably save some time on reviewing pull requests if we could get a label or comment after Travis or AppVeyor completes, with information about what went wrong. For example, failed unit tests, commit message problems (including needing an issue), lint errors.

I don't know if this sort of thing is remotely feasible. Thoughts?

**Comment by ilyavolodin** [comment]
That would be pretty nice. I'm not sure it's possible right now, since that means bot has to have access to Travis/AppVeyor. I think Travis does expose an API, but I'm not sure about AppVeyor at all.

**Comment by platinumazure** [comment]
What if we handled it similarly to coveralls? I think in that case we have the script post to coveralls (abstracted by a node module), no? If we augmented the build script to support posting to a web hook, maybe that could then post a comment or label on the PR?

**Comment by BYK** [comment]
:+1: - I think for commit messages we can move the commit message check to the bot itself.

**Comment by nzakas** [comment]
@ilyavolodin I'm working on an enhancement to check commit message on the PR. Should have it working this week.

@platinumazure its not possible to get the error message from Travis in any sort of useful way.

**Comment by platinumazure** [comment]
@nzakas Dang. What about writing a script (presumably as a function in
Makefile.JS) and configuring it as an after-script in .travis.yml which
would send that info somehow?

**Comment by nzakas** [comment]
@platinumazure I don't think that's very useful, honestly. All we need to do is say, "Please check the automated tests".

**Comment by platinumazure** [comment]
Fair enough. At least we agree that the commit message is something we
shouldn't have to waste time diagnosing.

**Comment by ilyavolodin** [comment]
Yes, commit message check with the link to the documentation should take care of most of the issues.
