### ISSUE TITLE
Inner grouping parens

### ISSUE THREAD

**Issue by demrks** [eslint/eslint#5270]
1) I think there should be a rule to disallow spaces inside of **inner** grouping parentheses:

``` js
if ( !("foo" in obj) ) { }
```

The rule `space-in-parens` is only for the _"outer"_ parentheses, but there is currently no rule to enforce or disallow spaces for _inner grouping_ ones. Probably something like `space-in-inner-parens` or a new exception?

2) There should probably also be a new exception for `space-in-parens` to disallow spaces before a `function` inside parens:

``` js
foo(function() { });
```

Since [idiomatic.js](https://github.com/rwaldron/idiomatic.js/) handles it that way, I guess it's pretty _common_. 

I'm using eslint 2.0.0.

**Comment by alberto** [comment]
There is an `exceptions` option that deals with some of the exceptions shown `idiomatic.js`, but not all. This one is not covered.

**Comment by alberto** [comment]
For reference, here are the exceptions in `idiomatic.js` (pasting since I can't directly link to the section):

```
// 2.C.1.1
// Functions with callbacks
foo(function() {
  // Note there is no extra space between the first paren
  // of the executing function call and the word "function"
});

// Function accepting an array, no space
foo([ "alpha", "beta" ]);

// 2.C.1.2
// Function accepting an object, no space
foo({
  a: "alpha",
  b: "beta"
});

// Single argument string literal, no space
foo("bar");

// Inner grouping parens, no space
if ( !("foo" in obj) ) {

}
```

**Comment by demrks** [comment]
Most of them are already covered though, except the _inner grouping parens_ and the _functions with callbacks_.

**Comment by nzakas** [comment]
If we do anything, it would have to be a modification of `space-in-parens`.

**Comment by demrks** [comment]
Probably something like `"exceptions": ["function"]` for the _functions with callbacks_ exception. Not sure about _inner grouping parens_ though.

**Comment by alberto** [comment]
This case isn't covered either:
```
foo("bar");
```

**Comment by demrks** [comment]
@alberto True, but it's probably too specific. At least I don't know of any other styleguide that enforces space in parens, but only if it's not a single string. Since I'm using idiomatic.js myself, I'd love to see it implemented thought.

This is related to https://github.com/eslint/eslint/issues/1142, but as far as I know, it is not limited to arrays. So the following patterns are not considered problems:

```
function foo("string") {}

function foo( "string1", "string2" ) {}

arr["string"]

arr[ 2, "string" ]
```

**Comment by nzakas** [comment]
I don't think there's an easy way to support all of these variations without hardcoding idiomatic-specific knowledge into the rule. You may need to create a custom rule for this.

**Comment by demrks** [comment]
@nzakas Yes, I already thought that the _single argument string literal_ won't be covered by eslint. Is there a way to create a custom rule for this at all without having to built a customized `space-in-parens` rule? Since I can't built custom exceptions for the existing `space-in-parens`, I can't just do something like this:

"rules": {
    "space-in-parens": [2, "always", { "exceptions": ["{}", "[]", "()", "empty"] }],
    "custom-single-argument-string-literal": 2
}

As far as I know, `space-in-parens` will always output an error whenever I write `foo("string")` regardless of what I do in my custom `custom-single-argument-string-literal` rule.

**Comment by alberto** [comment]
No you'll have to disable `space-in-parens` and use your own rule. Just copy and modify it as needed.

**Comment by demrks** [comment]
@alberto Ok thanks, but why is this issue closed? Is the `functions with callbacks` exception or the `inner grouping parens` exception not going to happen/in discussion either? 

I was thinking that @nzakas was only referring to `custom-single-argument-string-literal` exception with his comment?

**Comment by alberto** [comment]
Sorry, I thought you were intending to create a custom rule for all the cases.

**Comment by nzakas** [comment]
Inner parens is feasible to add. I'm not 100% sure about the callback, as that seems really specific to idiomatic. And would it be just functions or also any single argument?

**Comment by demrks** [comment]
Just functions, so only if the word 'function' comes right after a paren.

**Comment by nzakas** [comment]
Yeah, that's way too specific for a core rule.

**Comment by nzakas** [comment]
Let's implement the inner parens option, as that's important for implementing the Idiomatic.js style guide.

**Comment by gibson042** [comment]
Is this intended to match _inner_ parentheses, or _expression_ parentheses (cf. https://github.com/eslint/eslint/issues/4689#issuecomment-210123742 )? The former seems to be ambiguous:
* `foo(function areTheseInner(){})`
* `orThese((a, b)=>(b, a))`
* `{ orThese: function(){} }`
* `[ (howAboutThese) ]`
* `function areDefaultsInner( maybe=(foo), maybeNot=bar() ){}`

**Comment by demrks** [comment]
@gibson042 As far as I can tell, this is how your examples are supposed to be written in idiomatic.js. 

> foo(function areTheseInner(){})

`foo(function areTheseInner( no ) {});`

> orThese((a, b)=>(b, a))

`orThese( (a, b) => (b, a) )` _(I guess, but not sure since there's no example in the style guide)_

> { orThese: function(){} }

`{ orThese: function( withSpace ) {} }`

> [ (howAboutThese) ]

`[( howAboutThese  )]`

> function areDefaultsInner( maybe=(foo), maybeNot=bar() ){}

_No example in the style guide either_

**Comment by nzakas** [comment]
I believe the goal here is for inner parenthesized expressions.

**Comment by gibson042** [comment]
In that case, I believe this functionality is best considered as an "inner" or "nested" option of a rule covering spaces inside parenthesized expressions.

**Comment by kaicataldo** [comment]
I'm closing this issues because it doesn't look like there is enough interest to implement this. While we wish we could accommodate all requests, we have limited resources and do need to prioritize.
