### ISSUE TITLE
Rule no-unused-vars: destructuring assignment in function args

### ISSUE THREAD

**Issue by holymonson** [eslint/eslint#5273]
Example:
```js
func(([argA, argB]) => {
    console.log(argB)
})

const array = [1, 2, 3]
func(array)
```

This code is valid in ES6, but `argA` is treated as `no-unused-vars`. Could it be handled like `args: "after-used"` to leave those before-used argument not be checked?

**Comment by mysticatea** [comment]
Thank you for this issue.

I guess this is the same as #4620.
You can omit unused elements in an array pattern:

```js
const func = ([, argB]) => {
    console.log(argB)
}

const func = ([/*argA*/, argB]) => {
    console.log(argB)
}
```

**Comment by holymonson** [comment]
Thanks @mysticatea , omitting unused params works well. And as @nzakas in #4620 said, it could not count as a bug. I will close this issue and feel free to reopen if needed.
