### ISSUE TITLE
Unexpected error when running commit checker.

### ISSUE THREAD

**Issue by afahim** [eslint/eslint#5298]
**What version are you using?**

2.1.0

**What did you do?**

Added a commit, then checked out a new branch (for renaming purposes). Rebased from upstream. Ran `npm run check-commit`

**What happened?**

Got an error saying  `More than one commit found, please squash.`

**What did you expect to happen?**

Since I only added one commit, I didn't expect to see this message. My local master wasn't up to date. Reading the `checkGitCommit` function, I realized thats where the disparity was,. Solution was to delete my local master, so that this check ran instead

https://github.com/eslint/eslint/blob/ec803b268ade7b9093ac127083ca69c2ad7a2b47/Makefile.js#L871

I think this check assumes local master is up to date, which isn't always true imo (since one can rebase later, etc). Instead I think the check should run against `upstream/master`.

**Comment by BYK** [comment]
>Instead I think the check should run against upstream/master.

I think `upstream` is the name you've given to the original ESLint repo. This wouldn't work for the project maintainers since we have it under `origin`. This wouldn't necessarily work for everyone who may add the original repo under a different name.

A better way might be to check if the branch is up to date with the latest master or try to find the common ancestor. @eslint/eslint-team thoughts?

**Comment by afahim** [comment]
I see your point. Yes I was just looking at at from a contributor's point of view; I believe upstream is a commonly given name.

**Comment by BYK** [comment]
@afahim I agree that `upstream` is a common name, I use it myself too. But sometimes I use the original repo as `origin` and name my own fork as `byk` for instance. My point is, this is a very fragile solution and it may lead to more confusion than it is trying to fix. That said I still see some value in this work if guided correctly, hence the mention to the team :)

**Comment by mysticatea** [comment]
Ah actually I have been seeing the same error always.
I fork branches from `eslint/master`. This `eslint` is the organization name, GitHub added it to the remote list by default.

**Comment by nzakas** [comment]
This script is run as part of our automated tests and is really designed primarily for that, so we need to make sure it works for that case. It might just be better to either add a different check to run locally or just don't recommend people run it anymore.

**Comment by alberto** [comment]
I'm not sure what's the problem. I've run that script with an outdated local master many times and didn't run into problems.

**Comment by nzakas** [comment]
It seems like this isn't an issue anymore, so closing. If someone on the team feels differently, please reopen.

**Comment by i-ron-y** [comment]
Just a heads up: I've just had the misfortune to encounter this very same problem while I was committing for my latest pull request.

**Comment by not-an-aardvark** [comment]
We don't actually require commits to be squashed anymore, so maybe we should just remove that check.
