### ISSUE TITLE
Add version tips about `preferType` option of the `validate-jsdoc` rule

### ISSUE THREAD

**Issue by chinesedfan** [eslint/eslint#5307]
This option was first introduced in release `v2.0.0-beta.2`. But the [document](http://eslint.org/docs/rules/valid-jsdoc) does not mention about it.

BTW, should the title be highlighted?
```
// https://github.com/eslint/eslint/blob/master/docs%2Frules%2Fvalid-jsdoc.md
-### preferType
+### `preferType`
```

**Comment by nzakas** [comment]
We don't generally include versions when options are added. We should update the heading so that it's code formatted.

**Comment by chinesedfan** [comment]
Well, seems that users can check release notes to find out whether an option is valid. I have fixed the heading.
