### ISSUE TITLE
GitHub Issue Templates

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#5313]
Looks like GitHub issue templates are a real thing now! Maybe we can use them in conjunction with the bot to ensure higher quality issues? I'm happy to make a PR if this gets approved and what should be included gets decided on, but also understand it probably makes more sense for a core team member to do this.

Example: https://github.com/samccone/issue-template

**Comment by nzakas** [comment]
Yes yes yes yes yes.

The interesting part here is how do we distinguish between a bug and a change request? Is there a way to have a template that works for both?

**Comment by ilyavolodin** [comment]
I think we should have one big template for both, bug first, feature second.

**Comment by platinumazure** [comment]
We could have a template for both, but I think we need to send feature requests to GitHub to provide more granular control. E.g., user is first presented with radio buttons "Issue type:", Bug vs Enhancement Request, and get two different templates based off of that.

And it would be nice to be able to configure this as a repo setting rather than requiring yet another file in the Git repository. But we have to start somewhere, I guess :grin:

**Comment by kaicataldo** [comment]
Are there any fields specific to either of those types of issues? If they have similar fields, might make sense to have a **Type of Issue** field, otherwise @ilyavolodin seems like the best solution given the current limitations of the feature

**Comment by ilyavolodin** [comment]
@kaicataldo Unfortunately github doesn't yet allow custom fields, so we have to stick with the same form for all of the issues. Hopefully they can add that in at some point, but at least having some sort of template is a step in the right direction.

**Comment by kaicataldo** [comment]
Yeah, you're right, can't have multiple templates. All I meant above was that if they're essentially the same template for both types of issues, then an easy way to differentiate could be something like:
```md
Type of Issue (please fill in Bug or Change Request):
// Rest of fields go down here
```
If they're vastly different in requirements, makes sense to just have two sections in one big template, like you said. :+1:

**Comment by wyze** [comment]
You can do something similar to react-router here: https://github.com/reactjs/react-router/issues/new

They embed instructions as HTML comments in the markdown, so it appears when writing, but not in preview/submission.

**Comment by kaicataldo** [comment]
I think that's pretty cool! My only concern is that making people read a lot of stuff might make people less likely to report things because it seems like a hassle. I can make a PR for this - thoughts on what should be included?

**Comment by nzakas** [comment]
I think the most common issue type is bug reports, probably closely followed by rule changes and new rules. So maybe we should try optimizing for bug reports first, something like:

```
<!-- 
This template is for bug reports. If you are here for another reason, please see below:

1. To propose a new rule, see http://eslint.org/docs/developer-guide/contributing/new-rules for instructions
2. To request a change, see http://eslint.org/docs/developer-guide/contributing/changes
3. If you have a question, please stop by the chatroom: https://gitter.im/eslint/eslint

If you're reporting a bug, please continue on. Note that bug reports without all questions answered will be closed without comment.
-->

**What version of ESLint are you using?**

**What parser are you using? (Espree, Babel-ESLint, etc.)**

**What did you do? Include configuration information and source code.**

**What happened? Include the actual output from ESLint.**

**What did you expect to happen?**
```

**Comment by kaicataldo** [comment]
Great - I'll take a look at this this weekend!

**Comment by albertosantini** [comment]
Also with respect to https://github.com/eslint/eslint/issues/5342 I would describe the label meanings in the CONTRIBUTING docs. (I know nobody read CONTRIBUTING docs).

http://eslint.org/docs/developer-guide/contributing/
https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md

Maybe we add a brief paragraph to the footer of the template, explaining the issue workflow, the main labels and link to the CONTRIBUTINGS docs.

**Comment by kaicataldo** [comment]
@albertosantini The template is for creating new issues, and I don't know the person creating the issue is the one making labels, etc. I wonder if it might make sense to put that in a pull request template (which we haven't discussed here yet).

**Comment by albertosantini** [comment]
@kaicataldo The aim of the suggestion was a try to lower the effort to manage the issue.

For instance, adding the label `needs info` is a good surrogate for a comment "asking more info". Quite often the user ignores the label, because they don't know what are the next steps (or because they are `users`).

So I suggested that kind of sentence or link in the template, avoiding to add the usual comments, saving time for the community helpers, and waiting for a user action: a comment, in that example, with the missing info.

Just my two cents.

**Comment by IanVS** [comment]
@albertosantini Our bot adds a [comment](https://github.com/eslint/eslint/issues/5355#issuecomment-186856149) whenever we add the `needs info` label.  If there are other labels which aren't obvious, maybe we could consider a similar approach.  I could see having one for `accepted` along the lines of "This issue has been marked accepted, and is free for anyone to submit a pull request (link to pull request contributing guide).  We do not prioritize by '+1'-type comments, so any left here will be deleted."

**Comment by albertosantini** [comment]
@IanVS Thanks for the details. Fair enough. Sorry for the noise.

**Comment by IanVS** [comment]
No need to apologize, I was apologizing for my own diversion.
