### ISSUE TITLE
--init ouput to Javascript format doesn't respect user style for quotes

### ISSUE THREAD

**Issue by jraller** [eslint/eslint#5325]
Answering single for quote style and outputting using the JavaScript format results in a `.eslintrc.js` file that uses double quotes. It properly builds the correct rule for single quotes, but uses double quotes throughout the file.

**Comment by ilyavolodin** [comment]
Ah. nice catch!:-) Didn't think about that at all.

**Comment by jraller** [comment]
Maybe while fixing that also look at tabs versus spaces?

**Comment by ilyavolodin** [comment]
Agree. That would be something else to fix. `init` command was added before we had support for `.js` files, that why it wasn't trying to conform to the style you selected.

**Comment by nzakas** [comment]
This happens because we just JSON serialize the config and output it into a JS file.

**Comment by nzakas** [comment]
@jraller do you want to submit a pull request to fix this?

**Comment by jraller** [comment]
I followed the logic from `config-initializer.js` to `config-file.js` which is using https://github.com/substack/json-stable-stringify which correctly only uses double quotes as single quotes aren't valid for JSON.

I'm uncomfortable with the idea of post processing the result with a replace for fear of altering a double quote character that might be escaped as an option for a rule, so the best that could be achieved without significant risk to the code would be to pass the option for tabs versus spaces so that that choice would be reflected by the stringify call. Having the config file respond to only one options feels more problematic than having it always use spaces and double quotes.

Thank you both for looking at this.
