### ISSUE TITLE
npm run perf goes crazy

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5330]
I just pull the master branch and tried to run `npm run perf`. It goes crazy outputing thousands of lint errors to the console (20,451 to be exact) and then throws an error "Performance test failed". 

I haven't kept a good eye on the change to `npm run perf`, but it's definitely not supposed to be outputting lint messages to the console.

**Comment by btmills** [comment]
Working on this. I've narrowed down the break to b32ddad494c9d766aa71144dcccecd040246b040. Working on a fix now.
