### ISSUE TITLE
Specify results of `no-unused-var` with different `args` options

### ISSUE THREAD

**Issue by chinesedfan** [eslint/eslint#5334]
The document provides [3 samples](https://github.com/eslint/eslint/blob/master/docs%2Frules%2Fno-unused-vars.md#args), but what are their results?

**Comment by nzakas** [comment]
I believe those are all valid, but we should be saying that somewhere.

**Comment by chinesedfan** [comment]
Codes in the 3 samples are the same. I think only the last one is valid.
