### ISSUE TITLE
FATAL Parsing Error when using keyword "let"

### ISSUE THREAD

**Issue by inetphantom** [eslint/eslint#5335]
The keyword let is used to define a variable with block scope ([More information on mdn](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let))

I got following code(which works with Chrome, I double checked that): 

`return function foo(){
    if (true){
        let it = "be";
        console.log(it);
        debugger;
    }
}`

I am getting:
> Parsing error: The keyword 'let' is reserved at line X col Y

Same error on the line with a for-loop:

`for (let i = 0; i < items.length; i++){
    /* smoe code*/
}`

I am using eslint v2.1.0, inside Atom Texteditor. on console I am getting 
> 184:8  error  Parsing error: The keyword 'let' is reserved

**Comment by inetphantom** [comment]
The Error only exist, when es6 is not set to true. But never the less the feedback to the user is not good. It should be something like 
> "The keyword 'let' is reserved but not supportet by your environement"

**Comment by nzakas** [comment]
You need to either set the es6 environment to true or set `ecmaVersion` to 6. See http://eslint.org/docs/user-guide/configuring#specifying-parser-options
