### ISSUE TITLE
Pass filename as an argument to `parse`

### ISSUE THREAD

**Issue by nmote** [eslint/eslint#5344]
I have been experimenting with type-aware lint rules. The prototype I have combines [Flow](https://github.com/facebook/flow) with `babel-eslint` to annotate the AST with type information.

However, for Flow to be able to provide complete type information it needs the path to the current file so that it can properly resolve imports/requires. To that end I would like to pass the file name as an argument to `parse`.

I understand that this is a radical departure from the current idea of what a frontend for ESLint is, but the change required to support this idea is very small and will not interfere with existing code. I'm happy to put up a pull request if it is likely to be accepted.

**Comment by ilyavolodin** [comment]
I seem to remember that we already have something like that. We had a request a while back to pass filenames to rules, so we added a function to the rule [`context`](http://eslint.org/docs/developer-guide/working-with-rules#the-context-object). So it should be available inside parse in one form or the other.

**Comment by nmote** [comment]
I don't think the `context` object is available to the `parse` function. It's called [here](https://github.com/eslint/eslint/blob/40fec5812417e608d97f89f5028d551a0ef1a4e9/lib/eslint.js#L577) with only the program text and the `parserOptions` object.

**Comment by ilyavolodin** [comment]
Oh, sorry, for some reason I though you were talking about `validate` method, not `parse`. I'm not 100% sure we want to pass filename to parser, but I'll let others decide.

**Comment by nmote** [comment]
In #5040 @nzakas suggests "better support TypeScript and Flow." This would be a great start. CC @jeffmo.

**Comment by nzakas** [comment]
@nmote can you explain how you see this working? Keep in mind, we'd need something that won't interfere with how other parsers work.

**Comment by nmote** [comment]
I think the clearest thing would be for me to just put up a PR and we can discuss there. What I have is just a third argument passed to `parse` with the filename. Since current parsers only use the first two arguments it would not interfere with existing parsers. I'm certainly open to other ideas on how to accomplish this but this idea seems simplest.

**Comment by hzoo** [comment]
So either `parse(code: string, options: Object, filename: string)` or `parse(code: string, options: Object)` where you can use `options.filename`?

**Comment by nmote** [comment]
Both of those would be fine with me, although perhaps `options` would need to be renamed if we go with the latter.

**Comment by nzakas** [comment]
I thinking something in the options object makes the most sense. My fear of adding another parameter is that we could run into collisions should a parser randomly decide they want to add a third parameter.

My only fear about `filename` in the options object is whether or not that could potentially clash with another parser's options. We might need something a bit more specific.

**Comment by nmote** [comment]
Sounds good to me. Suggestions for a specific option name? `currentFilename`?

I'll put together a PR.

**Comment by nmote** [comment]
`pathToFile`? `pathToCurrentFile`?

**Comment by ilyavolodin** [comment]
@nmote Do you just need filename, or do you need a full path to a file?

**Comment by nmote** [comment]
Well, we at least need a relative path. Sorry for not being clearer throughout. With that in mind I think `pathToFile` probably makes more sense.

**Comment by ilyavolodin** [comment]
That's why I asked. Yes, or `filePath` would be another options. Although all of them sort of imply that the variable only contains directory that the file is in, not the file name itself.

**Comment by nzakas** [comment]
`filePath` seems like a good compromise.

**Comment by nzakas** [comment]
@nmote do you still plan to put together a PR for this?

**Comment by nmote** [comment]
I do, sorry for the delay: I've been busy with other things. It's near the top of my list and I'll do it this week.

**Comment by gyandeeps** [comment]
@nmote I think you have done the work but didn't open a pull request. Do you want to open a pull request?

**Comment by hzoo** [comment]
I can finish this up using that commit if @nmote doesn't (actually seems to be helpful for babel-eslint errors in general when figuring out how to run eslint tests)

**Comment by nzakas** [comment]
There was a pull request that we closed because it was abandoned. @hzoo I'd say go for it.

**Comment by gyandeeps** [comment]
@hzoo (just checking) r u working on this?

**Comment by azhang496** [comment]
i can take this on if @hzoo isn't working on it!

how do i go about writing tests? i haven't made a core contribution yet so i'm not sure how to get started

**Comment by ilyavolodin** [comment]
@azhang496 Unit tests are located here: https://github.com/eslint/eslint/blob/master/tests/lib/eslint.js You will probably need to create fake parser through Sinon and verify that filename is passed into parse method.

**Comment by hzoo** [comment]
@azhang496 If you'd like to, go ahead!
