### ISSUE TITLE
eslint unable to find babel parser, even though it's installed and referenced correctly

### ISSUE THREAD

**Issue by axefrog** [eslint/eslint#5354]
**Note:** please read the followup comment further below for subsequent context.

In my project root I have .eslintrc specifying "babel-eslint" for the parser. Under normal circumstances everything works fine, but as soon as I stick a node_modules folder in a project subdirectory, eslint fails to find the babel parser when looking at any js file at, or descended from, the folder where the additional node_modules folder exists. For context, I use these as a way of emulating [Ryan Florence's folder structure](https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346) as cleanly as possible, and it's a perfectly valid thing to do, even if not that common. If eslint is finding the nearest node_modules folder to the js file being inspected and failing to locate the specified parser there, it should be falling back through the folder tree the exact same way that `require()` works. I would go a step further though, and argue that it should in fact be starting its search for the parser no deeper than the location of the eslintrc file, which is clearly not the case right now.

For illustrative purposes, here's the type of folder structure I'm referring to:

```text
/.eslintrc
/node_modules
    /babel-eslint
/app
    /index.js
    /admin
        /node_modules (for admin-specific shared components)
        /index.js
```

In the above scenario, eslint processes `/app/index.js` successfully, but for `/app/admin/index.js`, it fails to find the parser.

I'm using Atom's linter, though I've also had trouble with this when running eslint from the command line.

**Comment by axefrog** [comment]
Just as a quick followup, in Atom at least, it seems to be able to continue successfully linting a file if it's already open, even after I add a node_modules folder, but if I open it after adding the node_modules folder, the problem presents itself.

**Comment by ilyavolodin** [comment]
@axefrog If ESLint is installed globally, all of the dependencies (parser, plugins, configs) should also be installed globally, and visa versa for local installation. As far as I remember Atom is using local installation of ESLint (unless you changed that in the options). You have to verify that if Atom is running ESLint locally, `babel-eslint` is also installed locally.

**Comment by axefrog** [comment]
@ilyavolodin but if it's not installed globally, you can't use it on the command line... are you saying that if you want to use it locally it must be via a separate tool such as gulp or an IDE integration?

**Comment by ilyavolodin** [comment]
No, you can still run it through full path, i.e. `node node_modules/eslint/bin/eslint.js`. But when you run it like that, it will be searching for locally installed plugins/parser. So in your case it's working fine. It looks like your Atom might be setup to run global installation of ESLint, and you don't have `babel-eslint` installed globally.

**Comment by mysticatea** [comment]
May [eslint-plugin-node](https://www.npmjs.com/package/eslint-cli) help you?

**Comment by ilyavolodin** [comment]
It seems like ESLint is behaving as described in the documentation for this case. Closing. Feel free to reopen if you do not agree.
