### ISSUE TITLE
Add VS Code to list of supported editors

### ISSUE THREAD

**Issue by chrisdias** [eslint/eslint#5360]
Can we add [VS Code](https://code.visualstudio.com) to the list of supported editors on the [integrations](http://eslint.org/docs/user-guide/integrations#editors) page in the docs?

The ESLint Extension can be found in the [marketplace](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

I don't see the page in `docs/user-guide` to make a P/R.  If there is one, please let me know and I'll be happy to do the edit.  

Thanks!

**Comment by ilyavolodin** [comment]
@chrisdias Page is located in the website repository here: https://github.com/eslint/eslint.github.io/blob/master/docs/user-guide/integrations.md If you want to send a PR, I'll merge it.
Closing, as this is website issue.

**Comment by chrisdias** [comment]
awesome, thanks.  PR created!
