### ISSUE TITLE
The "no-irregular-whitespace" rule prevents proper typography in comments outside English.

### ISSUE THREAD

**Issue by tdd** [eslint/eslint#5368]
Hey there,

So I moved to Standard, and am advocating it. It finally got me to jump ship on semicolons, and I use this despite the "space before function decl/expr opening parens" rule, which I find fugly.

So thanks a ton for this cool tool!

**But…**  The `no-irregular-whitespace` rule is messing with my comments. I'm a trainer among other things, and many of my codebases are for teaching purposes, with my audience being mostly French. In French, double punctuation marks (`;`, `:`, `!` and `?`) take a non-breakable space before them. French quotes (`«` and `»`) also use such spaces inside them.

But because of this rule, I can't use such spaces in my comment texts. So either I collapse these spaces, which looks and feels very weird to any French reader, or I use regular spaces, with the virtual guarantee that at least some of these will get wrapped at the beginning of lines in annotated code, looking terrible.

Isn't there a way to relax this rule for comment text? I can't find this relaxing mode in ESLint, but perhaps you know of a way?  I get the rule **inside code** (and btw, it's relaxed within String literals), but inside **comments**? Who gives a damn?

A PR is ready; just creating this issue so I can ref it in there, as per your guidelines.

**Comment by nzakas** [comment]
If you want to add an option like "skipComments" to the rule, that would be fine.

**Comment by tdd** [comment]
Hey @nzakas had not remembered options were available. I'm going for a `skipComments` option defaulting to `true` (this seems sensible to me), si that alright?

**Comment by tdd** [comment]
There, added it in my PR (#5367)
