### ISSUE TITLE
Improve error message when missing errors field in `rule-tester`

### ISSUE THREAD

**Issue by jfmengels** [eslint/eslint#5369]
In version 1.10.3 (and probably earlier), when I forget to specify the `errors` field in an invalid case when using `rule-tester`, I get the error `'Cannot read property 'length' of undefined'`. I think it would be nice to give a more explicit error message.

```js
ruleTester.run("no-eval", require("../../fixtures/testers/rule-tester/no-eval"), {
    valid: [
        "Eval(foo)"
    ],
    invalid: [
        { code: "eval(foo)" } // Missing `errors` field
    ]
});
```

I'm willing to submit a PR [(actually already prepared one, to update when accepted)](https://github.com/jfmengels/eslint/tree/throw-when-no-errors).

**Comment by gyandeeps** [comment]
Yes, It happened to me also this morning. I think it would be good to have an appropriate message.

**Comment by alberto** [comment]
+1

**Comment by ilyavolodin** [comment]
Sounds good to me! Accepted
