### ISSUE TITLE
`RangeError: Invalid string length` with --format=json and a really long source line

### ISSUE THREAD

**Issue by ahal** [eslint/eslint#5380]
Failure:
```
$ eslint --plugin html --ext "[.js,.jsm,.jsx,.xml,.html]" --format json /path/to/mozilla-central/devtools/client/inspector/markup/test
/home/ahal/.npm-global/lib/node_modules/eslint/lib/formatters/json.js:13
    return JSON.stringify(results);
                ^

RangeError: Invalid string length
    at Object.stringify (native)
    at module.exports (/home/ahal/.npm-global/lib/node_modules/eslint/lib/formatters/json.js:13:17)
    at printResults (/home/ahal/.npm-global/lib/node_modules/eslint/lib/cli.js:82:14)
    at Object.cli.execute (/home/ahal/.npm-global/lib/node_modules/eslint/lib/cli.js:173:17)
    at Object.<anonymous> (/home/ahal/.npm-global/lib/node_modules/eslint/bin/eslint.js:60:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

I can consistently reproduce this running eslint on all the files in this directory:
https://dxr.mozilla.org/mozilla-central/source/devtools/client/inspector/markup/test

STR:
```
$ hg clone https://hg.mozilla.org/mozilla-central/
$ ./mach eslint --setup
$ eslint --plugin html --ext "[.js,.jsm,.jsx,.xml,.html]" --format json /path/to/mozilla-central/devtools/client/inspector/markup/test
```
Note: the path needs to be absolute to bypass the include/exclude directives in .eslintrc.

I did a bit of digging and the result set isn't terribly large (104 errors) so I found it strange that memory problems would be the issue. It turns out, that JSON.stringify falls over at this *really* long line:
https://dxr.mozilla.org/mozilla-central/source/devtools/client/inspector/markup/test/browser_markup_copy_image_data.js#12

which appears in the eslint output under the 'source' attribute. Though, if I lint only that specific file, it works fine. I realize this is likely a v8 bug, but might warrant a workaround in eslint to cover this case.

**Comment by nzakas** [comment]
This is happening because we include the line text whenever there's a lint problem on it. If there are multiple problems on that line, that probably blows out the size of the raw result. 

About the only workaround I can think of would be to truncate the line if it's greater than some arbitrary length, and I'm unsure if we should do that. 

Another option is for you to create a custom formatter that omits the `source` field from each message.

**Comment by platinumazure** [comment]
Hmm. Is there really a strong need to serialize the line, anyway? Some other formatters (stylish, compact) don't bother.

Then again, it would be a breaking change to remove it unconditionally, so let me raise one more thought: Could we support formatter-specific CLI or CLIEngine options? These would be ignored by default by all formatters, but the JSON one could have an option for omitting serializing the line; in this particular case, it could be implemented as a replacer function for the `JSON.stringify` call.

**Comment by nzakas** [comment]
> Could we support formatter-specific CLI or CLIEngine options?

No, we don't want to complicate formatters by passing additional options into them. We added the JSON formatter so people could pipe that to whatever tools they wanted. See https://github.com/eslint/eslint/issues/2989

**Comment by platinumazure** [comment]
In that case, should we consider adding a new formatter (maybe "simple-json" or "minimal-json") which omits some values in serialization? That would seem to be a good way to help @ahal out.

**Comment by nzakas** [comment]
Most of our formatters already don't output the source text. Adding another formatter just for this purpose is a bit much, especially when it's easy to create a custom formatter that does exactly what you want.

**Comment by platinumazure** [comment]
It sounds like we're deciding not to fix this in core. Should we close this as wontfix?

@ahal If you would like help writing a custom formatter, please feel free to reach out in our Gitter chat, and we'll do our best to help.

**Comment by rtfpessoa** [comment]
I am getting lots of errors like this.

```
No content to map due to end-of-input
 at [Source: java.io.StringReader@cd1e646; line: 1, column: 1]
```

```
Invalid string length
RangeError: Invalid string length
    at Object.stringify (native)
    at module.exports (/usr/lib/node_modules/eslint/lib/formatters/json.js:12:17)
    at printResults (/usr/lib/node_modules/eslint/lib/cli.js:84:14)
    at Object.cli.execute (/usr/lib/node_modules/eslint/lib/cli.js:192:17)
    at Object.<anonymous> (/usr/lib/node_modules/eslint/bin/eslint.js:77:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Is there any way for me to avoid this?
