### ISSUE TITLE
Rule proposal: let-on-top

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#5383]
Equivalent of http://eslint.org/docs/rules/vars-on-top that requires to have `let` declared at the top of the block.

At the moment, there is no way to enforce a consistent use of `let` keyword. It can be either inline, e.g.,

```js
it('does not affect element with a single children when that children is contained in an array', () => {
    let subject = React.createElement('div', null, [
        React.createElement('p')
    ]);
    let outcome = React.createElement('div', null, [
        React.createElement('p')
    ]);
    subject = wrap(subject);
    outcome = wrap(outcome);

    expect(linkClass(subject)).to.deep.equal(outcome);
});
```

or at the top of the block, e.g.

```js
it('does not affect element with a single children when that children is contained in an array', () => {
    let outcome,
        subject;

    subject = React.createElement('div', null, [
        React.createElement('p')
    ]);
    outcome = React.createElement('div', null, [
        React.createElement('p')
    ]);
    subject = wrap(subject);
    outcome = wrap(outcome);

    expect(linkClass(subject)).to.deep.equal(outcome);
});
```

This rule would require to have all `let` declarations at the top of whatever block.

**Comment by gajus** [comment]
A more appropriate rule might be `no-inline-let`.

**Comment by BYK** [comment]
How about `variable-declarations-on-top` to rule them all (`var`, `let`, `const`) and deprecate the `var`-specific one?

**Comment by gajus** [comment]
> How about variable-declarations-on-top to rule them all (var, let, const) and deprecate the var-specific one?

`*-on-top` makes no sense with `const`, e.g. you cannot rewrite this code to have `const` at the top:

```js
it('generates <noscript> element', () => {
    let Component;

    const shallowRenderer = TestUtils.createRenderer();

    Component = class extends React.Component {
        render () {
            return null;
        }
    };

    Component = extendReactClass(Component);

    shallowRenderer.render(<Component />);

    const component = shallowRenderer.getRenderOutput();

    expect(component.type).to.equal('noscript');
});
```

**Comment by gajus** [comment]
`*-on-top` makes little sense for `let` too, because you do not know where `let` is supposed to be. This is partially what https://github.com/eslint/eslint/issues/5284 rule is trying to address. Therefore, only the inverse (`no-inline-let`) is what can be validated.

**Comment by gajus** [comment]
> *-on-top makes little sense for let too, because you do not know where let is supposed to be. This is partially what #5284 rule is trying to address. Therefore, only the inverse (no-inline-let) is what can be validated.

I am wrong.

`no-inline-let` is too generic. It does not say where `let` needs to be defined. In fact, [`init-declarations`](http://eslint.org/docs/rules/init-declarations) already does exactly what `no-inline-let` proposes to do.

Therefore, @BYK is right. This should be `let-on-top`.

**Comment by mysticatea** [comment]
Hmm, I'm not sure moving `let` declarations to the top of a block is a good practice.
`let` declarations have many different points from `var` declarations.
Could you explain why it's good?

**Comment by gajus** [comment]
> Hmm, I'm not sure moving let declarations to the top of a block is a good practice.
> let declarations have many different points from var declarations.

Not top of the closure. Top of the block.

> Could you explain why it's good?

It gives visibility of all variables used in the closure.

**Comment by nzakas** [comment]
I think this would be best as a custom rule. If this approach makes it into a popular style guide, we can reevaluate at that time.

**Comment by ffxsam** [comment]
Surprised this was closed. Why have `vars-on-top` but no `lets-on-top`? It makes sense that if ESlint allows us to prevent people from using `var` altogether, that there be a substitute for `vars-on-top` that works with `let`.

I agree with @gajus on the point about putting all `let`s at the top of the scope. Better legibility.

On the point about not being able to put `const`s at the top in all scenarios, that's when I use `let` instead, e.g.:

```
it('generates <noscript> element', () => {
    let Component, component;

    const shallowRenderer = TestUtils.createRenderer();

    Component = class extends React.Component {
        render () {
            return null;
        }
    };

    Component = extendReactClass(Component);

    shallowRenderer.render(<Component />);

    component = shallowRenderer.getRenderOutput();

    expect(component.type).to.equal('noscript');
});
```

So for the sake of hoisting, I use `let` instead of `const`.

**Comment by ffxsam** [comment]
Actually on second thought, `vars-at-top` should be modified to include `let` and possibly `const`. The reasoning behind my suggestion is that `newline-after-var` applies to all three variable types, and it uses the term "var" in the rule name. So why shouldn't `vars-at-top`, for the sake of consistency, do the same?
