### ISSUE TITLE
`no-unused-expression` throws when used with `do` expressions (es-stage-0)

### ISSUE THREAD

**Issue by davej** [eslint/eslint#5387]
For Example:

```js
const simpleDoExpression = (
  [1, 2, 3].map(() =>
    do {
      const obj = { foo: 'bar' };
      obj['foo'];
    }
  )
);
```

More info on `do` here: https://ponyfoo.com/articles/proposal-statements-as-expressions-using-do

**Comment by davej** [comment]
Perhaps this isn't within the scope of `eslint` and should be fixed in `eslint-plugin-babel` instead? Feel free to close this issue if appropriate.

Ref: https://github.com/babel/eslint-plugin-babel/issues/13

**Comment by ilyavolodin** [comment]
Thanks for the issue. This feature is at stage 0, so ESLint does not support it. Issue in `eslint-plugin-babel` should cover that. Closing as we do not support this.
