### ISSUE TITLE
[proposal] referencing dot-ignore file from within .eslintrc file, not just via cli

### ISSUE THREAD

**Issue by lucendio** [eslint/eslint#5400]
Hi,

I am using ``eslint@2.2.0``. I think its very likely to use existing ignore files like ``.gitignore``, but I and my team team are using eslint with webstorm and additionally on a git-before-commit-hook. At the same time I would like to have all eslint configurations in one place - for obvious reasons ;)
So I am proposing an ``ignore-path`` option available in the rc file, which might get overwritten by all other possibilities to set this option (CLI, .``eslintignore``, inline, etc.)

NOTE: if such thing was proposed before, please leave a link to the conversation and close the issue. Thanks.

**Comment by nzakas** [comment]
This has been requested a few times, but we have some technical issues that prevent us from doing so. Here's the last issue: https://github.com/eslint/eslint/issues/5038
