### ISSUE TITLE
Selector support

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5407]
This is an issue to discuss selector support for ESLint. This feature has been proposed pretty much as soon as ESLint was created, but we never had time to implement it. There has been attempts to bring in already created tools like `ESQuery` and `CSSAuron` that support selectors, but all of them would require additional traversal of AST, which we want to avoid.
The main question is what type of selectors should we support and in what format should they be. I think format should follow CSS selectors as close as possible. In terms of what to support, here's the list of selectors that I would like to support initially:
- `FunctionDeclaration Identifier` - node with type "Identifier" should be one of the children of node with type "FunctionDeclaration"
- `FunctionDeclaration[expression="false"]` - node with type "FunctionDeclaration" and "expression" attribute with value "false"
- `FunctionDeclaration>Identifier` - node with type "Identifier" and direct parent "FunctionDeclaration"
- `FunctionDeclaration[expression="false"][generator="false"]` - multiple attributes match
- `[name=\"test\"]` - any node with attribute "name" and value "test"
- `Identifier[name]` - node with type "Identifier" and existing "name" attribute
- `FunctionDeclaration[body.type="BlockStatement"]` - nested attributes support
- `FunctionDeclration>Identifier, FunctionExpression>Identifier` - support for multiple selectors

I really don't want to get into complex selectors in the initial implementation, like sudoclasses `:nth-child` or `~` (adjacent sibling) and so on. It's going to be tough to implement those without affecting performance too much, and I don't want to get bugged down into edge cases.

@mysticatea Asked for support of selector that would be able to specify `Identifier` node inside of `AssignmentExpression.left`. I'm not sure how that can be written with CSS selector syntax, as CSS doesn't have anything like that. Maybe something like `AssignmentExpression.left>Identifier` or `AssignmentExpression>[left]>Identifier`.

Would love to hear some thoughts from @michaelficarra on this.

**Comment by platinumazure** [comment]
If we keep track of parents (we do, right?), I can't imagine it would be that hard to implement these as extra event triggers. Then we basically already support them.

Example: We've entered Identifier and it is a left child of BinaryExpression which is init of VariableDeclaration. We emit "BinaryExpression>Identifier" (direct parent, only one of these), and traverse up the parent tree to emit "BinaryExpression Identifier" and "VariableDeclaration Identifier". Depending on how much we track, even attributes and nested attributes could be supported. The problem arises when there are simply too many permutations, but we could go through all rules' keys and look for patterns to determine what we need to "enable" in the traversal (e.g., if a rule uses descendant selector but no rule uses attribute tests, then no need to track and emit attributes at all, but we must track all parents and emit those).

Pros: No extra traversal; not a lot of architecture change needed, just extra lines in traversal enter/exit.

Cons: Won't be able to support wildcard options, no multiple selectors (unless we pre-process those as multiple simple selectors for event purposes?), and attributes (especially nested attributes) will be difficult.

**Comment by ilyavolodin** [comment]
That would be n ** (n * m) selectors (or is it n ** n ** m?) where n is number of nodes, and m - number of attributes. That's definitely not the way to go. I know how I want to implement this without affecting performance or existing architecture. That shouldn't be a problem.

**Comment by platinumazure** [comment]
Attributes make things messy, sure, but exponential? I had projected
quadratic on tree height for parents and descendants, and quadratic on tree
height times linear on attribute count for non-nested attributes. My
thinking was that my approach would allow for gradual implementation of
selector types.

What sort of selectors are people actually demanding? Like, with actual use
cases?

**Comment by ilyavolodin** [comment]
@platinumazure `BinaryExpression Identifier` doesn't mean grandparent, it means any `Identifier` tag with `BinaryExpression` as one of the parents. Even if it's 20 levels removed. More then that, you can have as many qualifiers as you want in the selector, so it might look like `Program BinaryExpression Identifier`, so that means exponential and not quadratic. Once you add attributes into the fold, it becomes a complete mess.
In any case, none of the selector engines that I'm aware of would fire event for every permutation. You can always get the list of subscribers and match only the selectors that were required.
All of the examples I listed above would be useful based on our current rules. I'm sure sibling selectors (`~`, `+`, etc.) will be also very useful as well, but I don't want to deal with them right now, since they would require tracking a lot more information as we traverse AST.

**Comment by nzakas** [comment]
> Asked for support of selector that would be able to specify Identifier node inside of AssignmentExpression.left

For that, you could use some sort of function. CSS selectors do support functions (like `nth-child()`), so that's your escape hatch whenever something doesn't quite fit.

If you want to go incrementally, I'd say the descendant selector and the child selector (`>`) alone give us a pretty big improvement in writing rules. We can always add more capabilities as we go.

My only question is: does this mean you're writing something new rather than using something existing?

**Comment by ilyavolodin** [comment]
@nzakas Yes, writing something new. I could try to reuse selector parser from some existing library, but I think the rest of it would just not fit our existing structure. In general, I think other then selector parser, the amount of code required for this is minimal (50-100 lines of code, if that). I'll give it a try and create a WIP PR for this once I get it working. I'll probably drop `AssignmentExpression.left` for now, as  `left` is not a node, and it would be more complicated to match that selector then the rest of what I described above.
One other question that I have, should I make `AssignmentExpression` be also treated as selector or should it be left in node-event-generator and filtered out of selector-event-generator? The only problem that I see with that approach is it would be a bit harder to handle selectors with comma (like `AssignmentExpression, FunctionDeclaration`).

**Comment by nzakas** [comment]
Not sure I understand what you're asking, can you explain some more?

**Comment by ilyavolodin** [comment]
Right now we have `node-event-generator` that handles standard nodes. I could remove it all together and replace it with `selector-event-generator` where simple nodes will become just one use-case of selectors. However, there might be slight performance hit for selectors (they need to be at least parsed), so originally I was thinking of saying if event has any characters that don't match `[A-Za-z:]` then it's a selector and send it to `selector-event-generator`, otherwise it's a standard node and should be processed by `node-event-generator`. However, in that case, it becomes a bit harder to deal with selector like `AssignmentExpression, FunctionDeclaration`, because it needs to be parsed into two separate events and appended to EventEmitter. Since we can only process selectors on the first event from EventEmitter, if you have a selector like `Program, FunctionDeclaration`, it might be too late to add a handler for `Program` node to EventEmitter at that time.

**Comment by nzakas** [comment]
I mentioned this way back when we first started talking about selectors: I think you can just hook into existing events. For a selector like `FunctionDeclaration Identifier`, you can tell the node is an `Identifier`, so you just listen for that event and then filter for nodes whose parents is `FunctionDeclaration`. For most selectors, you should be able to find the target pretty easily. For generic ones, we can add a `*` event that fires for every node type. So this implementation becomes a filter on `node-event-generator`.

**Comment by ilyavolodin** [comment]
Opened WIP PR here: #5441

**Comment by fvdm** [comment]
Shouldn't this be closed or moved to another milestone as v3.0.0 was released today?
