### ISSUE TITLE
module babel-eslint not found when installed global

### ISSUE THREAD

**Issue by Givemeyourgits** [eslint/eslint#5409]
**What version of ESLint are you using?**
2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
Babel-ESLint version 5.0.0

**What did you do? Please include the actual source code causing the issue.**
export default class MyClass { }

**What did you expect to happen?**
Nothing

**What actually happened? Please include the actual, raw output from ESLint.**
Cannot find module babel-eslint

When the modules (eslint & babel-eslint) are installed globally, I get this error.  When I install them locally, everything seems to work fine.

**Comment by nzakas** [comment]
Can you share the directory of the file you're linting and the full path to your config file?

**Comment by Givemeyourgits** [comment]
Files I am linting are here:
```
C:\Users\cspence\exercism\ecmascript
```

I put .eslintrc here (only because I haven't figured out a way to get it to work globally with Sublime Text, the arg parameter for SublimeLinter 3 doesn't seem to pick it up if I specify it.  If I use eslint & babel-eslint globally, it will throw error it cannot find babel-eslint.

```
C:\Users\cspence\exercism\.eslintrc
```

**Comment by nzakas** [comment]
Ah, another Windows user. Welcome. :)

So this is partly a problem with being on Windows. The globally-installed packages aren't in the lookup path from your project, so while you can run `eslint` on the command line after installing globally, the lookup happens from your project's directory and works back up to `C:\`. 

On Windows, the globally installed packages are installed in `C:\Users\cspence\AppData\Roaming\npm`, which isn't somewhere that `require()` can find the package.

If you install the parser locally (in `C:\Users\cspence\exercism\ecmascript\node_modules`), then it should work.

**Comment by Givemeyourgits** [comment]
Is there an easy hack to put it somewhere require() can reach on Windows?

**Comment by ilyavolodin** [comment]
@Givemeyourgits If you put it anywhere in the path of your project, npm should be able to pick it up. So if your project is in `C:\Users\cspence\exercism\ecmascript` putting it in `C:\Users\cspence\exercism\node_modules` or higher should work.

**Comment by Givemeyourgits** [comment]
I was trying to set it so it would be global so all Sublime Text can pick it up no matter what project/folder I am working on.  Same with .eslintrc

**Comment by ilyavolodin** [comment]
What you could try (not 100% sure it would work without testing it), is put your `.eslintrc` file in `C:\Users\cspence`. In that case, all of the projects that don't have their own configuration file will look there. After that, you should be able to setup `babel-eslint` in each individual project as part of your package dependencies. If you don't want to do that, you can put `babel-eslint` in `C:\Users\cspence\node_modules`.

**Comment by Givemeyourgits** [comment]
I think that will work as I already did it with eslintrc but was hoping there was a cleaner way.

Thanks for your help!

**Comment by davewallace** [comment]
@nzakas I've followed this article and double checked, but I too cannot find the binary for `babel-eslint`. I'm also on Windows, and I have local & global babel-eslint installed.

In the directory, `C:\Users\danjah\AppData\Roaming\nvm\v6.1.0` I see other packages there, eg; `eslint` and `grunt` which I have also just installed locally, for example: 
![image](https://cloud.githubusercontent.com/assets/1988022/15697052/865d32f2-280a-11e6-84f4-d53e487ae533.png)

As you can see here: 
![image](https://cloud.githubusercontent.com/assets/1988022/15697058/a2b35d28-280a-11e6-9890-b133d334b95b.png) there is a babel-eslint dependency present in the above location's `node_modules` directory.

Running `babel-eslint` on CLI returns:
> sh.exe": babel-eslint: command not found
