### ISSUE TITLE
Timline for publishing a new version?

### ISSUE THREAD

**Issue by TheAlphaNerd** [eslint/eslint#5415]
The test suite for v2.2.0 is broken. As such it is causing failure on the node.js smoke testing suite citgm.

I was curious what the timeline is to publishing a new version with an unbroken test suite

**Comment by ilyavolodin** [comment]
We usually do releases every other Friday, so the next release is tentatively scheduled for next Friday. We might reevaluate timeline, if we get more issues in the current version.

**Comment by TheAlphaNerd** [comment]
@ilyavolodin thanks for the heads up. I currently have CITGM testing off of master. I'll roll back to an official release once there is an update

**Comment by ilyavolodin** [comment]
Sounds good. I'll close this issue then. Once we release an update this should be resolved.
