### ISSUE TITLE
Add support for rule options normalization

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5418]
Right now, every rule that accepts options has a bit of code that checks for `context.options[0]` and tries to extract user options. I think that can be improved by applying options on top of the schema and getting back an object with defaults already pre-filled (we would need to update all schemas to have default options). This will eliminate a bunch of code and make rule creation a bit easier. It would also allow us to document rules better, due to the existence of default options in the schema. Here's an example of transformation that I'm thinking about:
**Schema:**
```js
[
    {
        "enum": ["always", "never"],
        "default": "never"
    },
    {
        "type": "object",
        "properties": {
            "singleValue": {
                "type": "boolean",
                "default": false
            },
            "objectsInArrays": {
                "type": "boolean",
                "default": false
            },
            "arraysInArrays": {
                "type": "boolean",
                "default": false
            }
        },
        "additionalProperties": false
    }
]
```
**User config:**
```js
array-bracket-spacing: 2
```
**Result:**
```js
context.options = {
    singleValue: false,
    objectsInArray: false,
    arraysInArrays: false,
    always: false,
    never: true
}
```

I did a very basic (and incomplete) implementation of this here: https://github.com/eslint/eslint/pull/2861/files#diff-fa79c1006638179cf4232bd250ee5fcdR40

**Comment by nzakas** [comment]
That would be really nice! Is there any perf hit for this?

**Comment by ilyavolodin** [comment]
Hmm... I don't think there should be, but I have no supporting arguments for that statement. @btmills are you aware of any existing libraries that are capable of doing this? Seems like something that should be pretty standard for JSON schema. We could then check performance and see if it slows things down. Otherwise we would need to create our own converter, which is not very complicated, but should cover a lot of different configurations.

**Comment by btmills** [comment]
It looks like there's a [Python library](http://python-jsonschema.readthedocs.org/en/latest/faq/) and maybe a [JavaScript option](https://github.com/chute/json-schema-defaults) to extract defaults. [is-my-json-valid](https://github.com/mafintosh/is-my-json-valid), which is what we use to validate, doesn't merge in defaults.

I think the way you have it specced makes it harder since it's not a parallel structure. Purely following the JSOn format from your schema, the defaults would be

```json
[
    "never",
    {
        "singleValue": false,
        "objectsInArrays": false,
        "arraysInArrays": false
    }
]
```

Do you have a way to convert between the parallel structure and the options object?

**Comment by alberto** [comment]
How would that work for rules with optional properties, like `padded-blocks`?

**Comment by ilyavolodin** [comment]
@alberto Optional properties (or `one-of` constructs) will just not be populated, ideally.

@btmills Even if we could get the structure that you posted above, that would be a good start. We can always collapse it to a single level.

**Comment by SpadeAceman** [comment]
@ilyavolodin Why would you want to collapse the structure example from @btmills to a single level? His proposed default structure makes more intuitive sense to me than the "Result" example in your initial post.

**Comment by ilyavolodin** [comment]
Because it's much easier to operate on objects then on arrays. With arrays you need to know the order of things, with object, all you need are names.

**Comment by platinumazure** [comment]
@ilyavolodin You're not wrong, but that really should be retrofitted to the existing JSON schemas in that case.

**Comment by ilyavolodin** [comment]
@platinumazure Schema is there to control user input, what I'm talking about is just a helper that can use that schema to normalize output of the options.

@btmills I just looked at the link to JS library, and that's not what I had in mind. Defaults are just part of the equation, user input is another part that should override defaults. Do you know if there's a library that can take json object, schema and output back normalized object? Using my example above:

```js
array-bracket-spacing: [2, "always", { "objectsInArrays": false }]
```

should return something like:
```js
[
    "always",
    {
        "singleValue": false,
        "objectsInArrays": true,
        "arraysInArrays": false
    }
]
```

**Comment by SpadeAceman** [comment]
@ilyavolodin Aha, I see what you're aiming for now. Would the schema allow you to specify internal-use names for the positional parameters? If so, then perhaps you could do something like this:

```Javascript
context.options = {
    _when: "never", // internal name for first positional parameter
    singleValue: false,
    objectsInArray: false,
    arraysInArrays: false
}
```

Alternatively, you could combine the positional indexes onto the normalized object, and provide the values that way. While this would still tie you to the positions of the values, you'd at least have only a single object to work from:

```Javascript
context.options = {
    1: "never", // or 0, depending on if you want 0- or 1-based indexing internally
    singleValue: false,
    objectsInArray: false,
    arraysInArrays: false
}
```

**Comment by ilyavolodin** [comment]
@SpadeAceman Sure, last example would be fine by me. Still makes it a lot easier to work with options then dealing with normal array and then manually applying defaults on top.

**Comment by nzakas** [comment]
Just a note: if you are going to hack in numeric properties, be aware that some rules expect an array and may use other array methods or properties, so it might not be straightforward to just swap in a regular object.

**Comment by nzakas** [comment]
@ilyavolodin do you still want to do this?

**Comment by ilyavolodin** [comment]
Ideally - yes. I'm not sure when, though. I think this would be helpful and allow us to remove a lot of code from our rules.

**Comment by nzakas** [comment]
@ilyavolodin do you see this as a possibility in the next 90 days? If not, I think we should close.

**Comment by ilyavolodin** [comment]
No, sorry. I don't think I would be able to get to it in the near future. If I'll have more time at some point, I'll just open a new issue.
