### ISSUE TITLE
Rules in Plugins docs incorrectly references environment

### ISSUE THREAD

**Issue by jmm** [eslint/eslint#5421]
[This part](https://github.com/eslint/eslint/blob/8ca6bedac12155891d5dca556498ce12a035eccb/docs/developer-guide/working-with-plugins.md#rules-in-plugins) is a mistake:

> then you would set the environment in your configuration to be `"myplugin/dollar-sign"`.

Should read something like:

> then in your configuration you'd refer to the rule by the name `myplugin/dollar-sign`. Example: `rules: {"myplugin/dollar-sign": 2}`.

**Comment by platinumazure** [comment]
It's definitely confusing, especially with an "Environments" section below it. Leaving the decision on final wording to a core team member.

**Comment by nzakas** [comment]
I think the suggested wording is good.

**Comment by platinumazure** [comment]
@jmm Would you like to submit a pull request with your suggested wording?

**Comment by jmm** [comment]
Thanks all. #5467. Added a set of quotes: `rules => "rules"`.
