### ISSUE TITLE
Plugin names without the eslint-plugin prefix

### ISSUE THREAD

**Issue by TheSavior** [eslint/eslint#5442]
**What version of ESLint are you using?**
1.9.0

**The problem you want to solve**
Our company has a javascript package that we have used for a long time to programmatically define linter configurations. We want to turn this into an eslint plugin but don't want to have to rename this entire project.

**Your take on the correct solution to problem.**
In lots of packages that have plugins, they prefer loading packages with their given prefix but fall back to the specified package name without the prefix if it doesn't exist with the prefix. 

What I'd like to be able to do is change this section: https://github.com/eslint/eslint/blob/master/lib/config/plugins.js#L116 to first check if the module exists with `PLUGIN_NAME_PREFIX`, if it does not, check without `PLUGIN_NAME_PREFIX`, and if it still  doesn't exist then, throw.

A reasonable concern would be that if the prefix isn't required, then people will stop providing the prefix and then plugins will become harder to find. IMO, this isn't a likely situation since it is pretty well drilled into the community that plugin names begin with `eslint-plugin`. Also, since the documentation still recommends adding the keywords, I don't think that will be a problem. I see this as being a use case for a very small sub percentage of users who can't easily do it the recommended way.

**Comment by ilyavolodin** [comment]
We support plugins without prefixes as named packages. Would that solve your problem? I'm not sure it's a good idea to allow for plugins without prefix, while within a company it could be clearly explained, for an external user, even one of those package might create confusion (especially if we don't have it advertised in the documentation).

**Comment by TheSavior** [comment]
Perhaps. Can you link to something about "named packages"? I haven't seen anything about that in the docs.

**Comment by ilyavolodin** [comment]
Hmm.. I just checked documentation, and apparently, I was wrong. Scoped packages are also supposed to be prefixed. And yes, I was talking about scoped packages, not named, sorry for the confusion.

**Comment by nzakas** [comment]
I'm sorry, we can't make such a change right now. The ecosystem is built around prefixed packages for easier discoverability (many don't add the correct keywords to their package, so we can't rely on that). We might allow this in the future if we can solve the discoverability problem in another way, but we can't do it right now.

**Comment by TheSavior** [comment]
I know this is long closed, but it is still a pain point for us as we move to eslint from jscs. We have our eslint and jscs configuration both in a package called `wealthfront-javascript`. If we write our own rules, we can use `rulesdir`. However, in many of your comments on other threads @nzakas, you have commented that you want to replace `rulesdir` with plugins. 

Once we make the switch to eslint, if `rulesdir` is deprecated, or we want to do anything else with plugins then we have to rename our package from `wealthfront-javascript` to `eslint-plugin-wealthfront-javascript`. That will cause so much pain, especially since `wealthfront-javascript` is open source and used outside of our company. It will require all downstream projects to change dependencies, just because eslint only want to support plugins that are prefixed with `eslint-plugin`. :-(

Any recommendations on how we can support this use case?

**Comment by ilyavolodin** [comment]
@TheSavior We don't have any plans to remove `rulesdir` currently. We think that plugins provide greater control and more options than `rulesdir`, but `rulesdir` has it's own uses, and should be available for the foreseeable future.

**Comment by TheSavior** [comment]
I've run into a problem with rulesdir in my 30 minutes of playing with it before writing that last comment that makes it a no go.

Since rulesdir is only a cli flag and can't be set in the eslintrc, for which there are many issues requesting that feature which @nzakas has closed, editor integrations for our team will be broken without manual configuration. They won't be able to work just by following the config files. I'd have to help every member of my team specially configure their editor plugin to also pass that flag.

That pretty much makes rulesdir a no go and I'm back to the beginning. :-/

**Comment by TheSavior** [comment]
It looks like Facebook found a work around by using package.json to create an npm module from a local folder: https://github.com/facebook/react/pull/4034/files

I can make that work.
