### ISSUE TITLE
Docs: WIP Guidelines for rule pages

### ISSUE THREAD

**Issue by pedrottimark** [eslint/eslint#5446]
This issue will accumulate the **reusable patterns** that emerge while the rules pages are edited to improve consistency. The result will become a **template and guidelines** (in a format yet to be determined) for future editing, especially new options and rules.

Goals: https://github.com/eslint/eslint.github.io/issues/186#issuecomment-176457525, https://github.com/eslint/eslint.github.io/issues/186#issuecomment-176457525, https://github.com/eslint/eslint/pull/5375#issuecomment-187488216

Pull requests will have often discussion about specific occurrences which sometimes cause us to add generalized conclusions to this issue. This issue can also have questions, concerns, suggestions.

**Comment by pedrottimark** [comment]
If a rule page has a **level-2 Options** heading, then for each option which has examples there is a **level-3** heading.

The heading text is either:
* string value (for example, always, never)
* object key (for example, after, before, hoist)

For faster scanning, there is **no** additional punctuation (quotes) or formatting (code style indicated by backticks). The example sentences and eslint comments in the code specify the required syntax.

If there are separate examples for values of an object property, then there are **level-4** headings. A **colon** separates key from value, for example:
hoist: functions
hoist: all
hoist: never

**Comment by pedrottimark** [comment]
Most rules (and options) have **examples** of code so people can achieve the following **goals**:
*   *Given* incorrect or inconsistent code, *find a rule* (and its options) to prevent it.
*   *Given* a rule (and its options) in the configuration, *write correct code*.

So people can recognize quickly how rules and options relate to their code, most examples consist of **incorrect** code followed by **correct** code.

Examples of some options (for example, `allow`, `exceptions`, `ignore`) omit incorrect code because it is the same as (or a part of) the incorrect code in a preceding example.

Adapt the following patterns for sentences to precede the code fence for an example.

*   under Rule Details for a rule with no options
    Examples of **incorrect** code for this rule:
    Examples of **correct** code for this rule:

*   under the level-3 heading for the default vanilla option
    Examples of **incorrect** code for the default `"vanilla"` option:
    Examples of **correct** code for the default `"vanilla"` option:

*   under the level-3 heading for the chocolate option
    Examples of **incorrect** code for the `"chocolate"` option:
    Examples of **correct** code for the `"chocolate"` option:

*   under the level-3 heading for options which are object literal keys
    in sentence and eslint comment in code use object-curly-spacing always and quote-props always
    however, the rule name itself is unquoted in the eslint comment
    after
    Examples of **incorrect** code for the default `{ "before": false, "after": true }` options:
    Examples of **correct** code for the default `{ "before": false, "after": true }` option:
    before
    Examples of **incorrect** code for the `{ "before": true, "after": false }` options:
    Examples of **correct** code for the `{ "before": true, "after": false }` option:

*   only correct code for an option which is an exception for another option
    Examples of **correct** code for the `"never", { "ignoreForLoopInit": true }` options:

*   sentence includes significant conditions
    but use comments in code for more minor distinctions
    Examples of **correct** code for this rule with es6 environment:
    Examples of **correct** code for this rule with es6 environment and strict mode:
    Examples of **correct** code with null elements for the default `{ "before": false, "after": true }` option:

**Comment by pedrottimark** [comment]
If a rule has options, then heading level 2 **Options** follows the Rule Details section.

Look at the schema or meta.schema array in module.exports in the rule file: lib/rules/*.js

For each “slot” in the array, include a sentence like one of the following to introduce a bulleted list. The brackets contain example rules for your further study. Do not include them, of course.
* This rule has a string option:
* This rule has a number or string option: [indent]
* This rule has an object option: [camelcase]
* This rule has either a string option: [one-var, padded-blocks, space-before-function-paren]
* Or an object option: [one-var, padded-blocks, space-before-function-paren]
* This rule has either an object option: [generator-star-spacing]
* Or a string option: [generator-star-spacing]
* This rule has string options: [consistent-this]
* This rule has another string option: [quotes]
* This rule has an object option for exceptions: [operator-linebreak]
* This rule has an object option for an exception: [brace-style]
* This rule has an object option for exceptions to the `"always"` option: [object-curly-spacing]
* This rule has an object option for exceptions to the `"never"` option: [object-curly-spacing, yoda]
* This rule has an object option for an exception to the `"declarations"` option: [func-style]

Here are recommended VERBS to use in list items. Try to limit each item to one sentence which begins with the option in code style (enclosed in backticks) and does **not** end with a period
* … disallows …
* … requires …
* … allows … [yoda]
* … allows (but does not require) … [comma-dangle]

list item for string option
* `"option"` (default) VERB …
* `"option"` VERB …

list item for string options
* designated alias names for `this` (default `"that"`) [consistent-this]

list item for number option
* a positive integer (default `4`) enforces … [indent]

list item for object option
* `"SwitchCase"` has an integer value (default `0`) to enforce … [indent]
* `"exceptRange": true` (default `false`) allows … [yoda]
* `"before": true` (default) enforces … [generator-star-spacing]
* `"after": false` (default) disallows … [generator-star-spacing]
* `"exceptions"` has an array of strings … [spaced-comment]
* `"exceptions"` has properties whose names correspond to node types in the abstract syntax tree (AST) of JavaScript code: [comma-style]

useful phrases in list items
* *except* when [eqeqeq]

Here is a question we will answer as we go: how much description to repeat following a heading level 3 for an option preceding its example code? Initial opinion by Mark is usually none.

**Comment by scriptdaemon** [comment]
To remain consistent with the discussions for the process of deprecating rules (and simply for sanity's sake), docs for maintained rules (i.e. non-deprecated rules) should not list any deprecated rules in their "Related Rules" sections.

**Comment by scriptdaemon** [comment]
Where options have been deprecated, examples should no longer reference the deprecated option, nor should the option be listed among the available options. However, a note with the following format should be placed at the bottom of its respective option summary:

**Deprecated:** The object property `maximum` is deprecated; please use the object property `max` instead.

**Comment by pedrottimark** [comment]
- [ ] no-empty-character-class: delete Related Rules no-empty-class
- [ ] space-before-function-paren: delete Related Rules space-after-keywords space-return-throw-case
- [ ] object-curly-spacing: under Related Rules delete space-in-brackets
- [ ] under Removed space-in-brackets add computed-property-spacing to replaced by
- [ ] spaced-comment: delete Related Rules spaced-line-comment

**Comment by pedrottimark** [comment]
The `strict` rule has a rare example of a **removed** option (the original default, lack of any option ;)

If we find any more, we can compare them and decide on a pattern.

**Comment by aubergine10** [comment]
FYI: I've started work on ES6 rules.

For removed, deprecated, changed options, we could use blockquotes to highlight the changes, eg:

> From ESLint 1.2.3 the `"whatever"` option is deprecated/removed/etc.....

**Comment by aubergine10** [comment]
@pedrottimark do you have an example doc showing the full headings, in particular the following h2 headings:

* Environments
* Known Limitations
* Compatibility

Also, IMO it would be better to rename the "When Not To Use It" heading to "Recommendations" so we can also give guidance on when to use it if desired. For example, the `arrow-body-style` rule I might say:

> #### Recommendations
> 
> * If you use arrow functions, use this rule.
> * For _concise_ and _expressive_ code, use the `"as-needed"` pattern
> * For _consistent_ code. use the `"never"` pattern

We could potentially have a list of keywords associated with the meta goals of linting, and then in the recommendations section suggest options to use for different goals. Off the top of my head, I can think of the following meta reasons:

* maintainability - to facilitate best practice
* consistency - to reduce learning curves
* expressiveness - to aid reasoning
* brevity - to ensure concise code
* stylistic - _a mixture of the above + personal preference_

There are likely others. The meta terms could also be used when evaluating new rules or changes to existing rules, and as an aid to decision making could be mentioned in the contributing guidelines.

**Comment by pedrottimark** [comment]
Here are 11 examples of rules whose docs contain **h2** headings you asked about.

I put * at the left of 2 with unexpected order and r at the left of 1 with unexpected capitalization

```
  Rule Details, Compatibility, Further Reading no-octal
* Rule Details, Environments, Options, Further Reading no-invalid-regexp
  Rule Details, Known Limitations, When Not To Use It, Further Reading, Related Rules no-regex-spaces
  Rule Details, Options, Compatibility, Further Reading one-var
  Rule Details, Options, Compatibility, When Not To Use It, Related Rules object-curly-newline
  Rule Details, Options, Environments, When Not To Use It, Compatibility, Further Reading no-undef
* Rule Details, Options, Further Reading, Compatibility: func-names
  Rule Details, Options, Known Limitations, When Not To Use It, Further Reading, Related Rules callback-return
  Rule Details, Options, When Not To Use It, Compatibility, Related Rules object-property-newline
r Rule Details, Options, When Not To Use It, Further reading, Related Rules, Compatibility max-lines
  Rule Details, When Not To Use It, Compatibility, Further Reading no-floating-decimal
```

**Comment by aubergine10** [comment]
With regards to this scenario:

> under Rule Details for a rule with no options
> * Examples of **incorrect** code for this rule:
> * Examples of **correct** code for this rule:

I think we should also match those strings if used under a level-2 **Examples** heading - IMO the code samples should always live under **Examples** heading, even if the rule has no options - this keeps document structure consistent.

**Comment by aubergine10** [comment]
Key notes from `es6` rule docs initial sweep:

* Struggling with one branch per PR approach - can't figure out how to prevent PRs from merging.
* Issues with code example blocks (not covered by initial sweep):
  * ensure each starts with the inline options comment
  * ensure blank line between comment and code example
  * ensure 'correct' vs. 'incorrect' examples clearly convey difference - https://github.com/eslint/eslint/issues/6455#issuecomment-226908530
  * some examples are too terse for newbies to comprehend - #6455
  * colorization and iconification of examples is limited to at most 3 code blocks per heading (or colour?)
    * could maybe merge and add extra comments, see https://github.com/eslint/eslint/pull/6453#issuecomment-226914326 for example
    * alternatively eradicate the restriction (as it would likely cause issues further down the line if we start hosting docs for 3rd party rule plugins)
* Still a lot of inconsistency with opening sections
  * Many docs don't explain the rationale behind the rule
  * Options sections still need lots of cleanup - IMO more discussion needed on the format of the options section as I feel it's still too cumbersome in many scenarios
* Inconsistency of h2 Examples heading, particularly for rules with no options
  * I'd like to ensure every doc includes that heading, even if no options
* With `es6` rules, the h2 When Not To Use This Rule section should always include "If using ES3/5"
  * I'd like to discuss renaming that heading to "Recommendations"
    * Would allow us to say when the rule _should_ be used, in addition to when it _should not_ be used
    * Also allow suggesting which options to use for various project goals

Overall, I'm chomping at the bit to get cracking with more updates to the docs. Real blocker issues from my end are:

* Auto-merging PRs - how to prevent it and ensure separate PR per branch?
  * This could become critical for some of the larger updates planned where a PR might be limited to a specific file with lots of changes that need to be carefully examined
  * If I have to wait for current PR to be merged before submitting next PR, it's going to add lots of latency to workflow
* Scope-creep during the PR review phase; eats up time
  * Better commit comments, stating clearly what is in and out of scope for the PR could help?

**Comment by aubergine10** [comment]
Another thing to consider - would it be worth having an optional h2.FAQ section on rule docs?

For example, with some es6 stuff, people can get `AssertionError: A fatal parsing error occurred: Parsing error: Assigning to rvalue` - to fix they have to add `parserOptions: { ecmaVersion: 6 }` to their tests ([example](https://github.com/eslint/eslint/blob/master/tests/lib/rules/arrow-body-style.js#L22)). An FAQ section could cover such externalities.

**Comment by aubergine10** [comment]
Currently updating some docs _outside_ `es6` category, list will probably grow as I find more (task focus: correct headings and captions in examples section):

* http://eslint.org/docs/rules/padded-blocks
* http://eslint.org/docs/rules/space-before-blocks

**Comment by aubergine10** [comment]
Noticed a fairly common anti-pattern - options section being spread throughout the examples. `space-in-parens` rule is a good example:

* Options section describes `never` and `always`
* Then mid way through lots of examples, the `exceptions` option is introduced
* Then near the bottom the `empty` exception is introduced.

A quick glance of the Options section could leave a reader thinking there were only `always` and `never` options, that the rule didn't meet their specific needs.

I've moved all the options information in to a single h2 Options section and used headings throughout examples to highlight where each option is being discussed.

**Comment by kaicataldo** [comment]
Closing because it doesn't look like there's enough interest to finish implementing this.
