### ISSUE TITLE
`--ext` has no effect on glob patterns

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#5452]
**What version of ESLint are you using?**

2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

Espree

**What did you do? Please include the actual source code causing the issue.**

I made a project structure like:

```
├── node_modules
├── non-js
│   └── readme.txt
```

Where `readme.txt` is a plaintext, non JavaScript file.

I executed `eslint non-js/* --ext .js`.  

**What did you expect to happen?**

I wasn't exactly sure what should happen, since this pattern is obviously a glob which means "match everything".  @ilyavolodin believes only `.js` extensions should be matched.  I couldn't find any tests which establish behavior one way or the other, and the documentation does not address this either.  

**What actually happened? Please include the actual, raw output from ESLint.**

`non-js/readme.txt` is attempted to be linted, and I get a parsing error.

So, my question is: "Is this behaving as expected?  And if so, should we make this more clear in the tests and documentation (perhaps with a warning if `--ext` is used together with a glob)? "

**Comment by nzakas** [comment]
I think only .js should be matched, that seems like the most intuitive expectation.

**Comment by IanVS** [comment]
I agree it might be more intuitive (or maybe not, because `*` should mean everything), but only returning `.js` files would be taking away power from the globs, and it could be breaking.  If I wanted to get all `.js` files within `non-js`, I could have just used `eslint non-js` or `eslint non-js/*.js`.  I wonder if it's useful to keep the current behavior but document it more clearly.  Also, this would be a non-trivial change to make.

**Comment by platinumazure** [comment]
Given that we seem to be going in a direction of relying more on globs, I'm wondering if we should remove the `--ext` option altogether? (As a breaking change in a major version release, of course.)

**Comment by IanVS** [comment]
I don't think we want to directly remove the ability to specify a folder, so I think the `--ext` option is still useful.  Why do you think it should be removed?

**Comment by platinumazure** [comment]
My thought was that we would remove the command line parameter and use
glob-based configuration. If configuration is at root level and not under a
glob, then we could infer `**/*.js`.

On reflection, I'm not liking that as much. Maybe we should find a way to
combine ext and globs so that `--ext .js` + folder "./stuff" turns into
"**/*.js" internally (and so on for multiple extensions)?

**Comment by IanVS** [comment]
I'm sorry, but I still don't understand your suggestion.  We use `--ext` to convert directories to globs already in:  https://github.com/eslint/eslint/blob/master/lib/util/glob-util.js#L42-L48.

**Comment by platinumazure** [comment]
Thanks @IanVS. Forget I said anything.

**Comment by nzakas** [comment]
@IanVS `*` means everything, but I'd argue also using `--ext` signals an intent to not use everything. 

I don't mind just documenting this for now, though. It's probably not causing a lot of heartache at the moment.
