### ISSUE TITLE
Replace getLast() (lib/util.js) with lodash.last()

### ISSUE THREAD

**Issue by captbaritone** [eslint/eslint#5456]
`getLast()` is the only function in `lib/util.js` and it is essentially identical to `lodash.last()`.

The only difference is that `lodash.last()` returns `undefined` for empty arrays instead of `null`. This minute difference does not seem to cause any tests to fail.

It would allow us to remove the `lib/util.js` and `tests/lib/util.js` files altogether. It would also allow us to remove the duplicate implementation that lives in `lib/rules/comma-dangle.js`.

Finally, it would provide a nice opportunity to clean up the docs in `docs/developer-guide/code-path-analysis.md` which erroneously point to this function living in `lib/ast-utils.js`.

**Comment by gyandeeps** [comment]
souds good to me. 
@eslint/eslint-team thoughts?

**Comment by IanVS** [comment]
:+1:  I'm all for removing code when we can!

**Comment by ilyavolodin** [comment]
Sounds good to me.
