### ISSUE TITLE
Feature request: extend eslint-disable comment syntax to support disabling a plugin

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#5481]
I suggest to extend ESLint [`/* eslint-disable */`](http://eslint.org/docs/user-guide/configuring#configuring-rules) syntax to support disabling an entire plugin, e.g.

```js
/* eslint-disable react/* */
```

This is useful in cases where certain code style or requirements apply to must but not all files (e.g. https://github.com/gajus/eslint-plugin-flowtype/issues/5) and listing all plugin rules is simply impractical.

There is an existing question about the existence of the feature (https://github.com/eslint/eslint/issues/2118). This issue is to propose addition of the same feature.

**Comment by platinumazure** [comment]
How much flexibility would you need?

If it's truly about plugins, would something like `/* eslint-disable-plugin-rules react */` work? (Put aside how verbose it is for now-- I'm just trying to see if you actually need wildcards.)

**Comment by gajus** [comment]
`/* eslint-disable-plugin-rules react */` (or a variation of that) would work. No, wildcard is not necessary.

**Comment by gajus** [comment]
In fact, I think you are right – `/* eslint-disable-plugin name[,... name]  */` is a lot more expressive.

**Comment by platinumazure** [comment]
@gajus Yeah, I could definitely get behind `eslint-disable-plugin` and `eslint-enable-plugin`.

**Comment by nzakas** [comment]
Sorry, this really isn't possible right now. We specifically do not distinguish between rules from plugins and core rules because "disabling a plugin" has many different meanings to different people. Configuration merging/overriding/etc. is already really complicated, so I'd rather not add more complexity to it at this point.

**Comment by gajus** [comment]
... This can be implemented in 5 lines of code.
