### ISSUE TITLE
Rule proposal: unicode-bom (byte order mark, U+FEFF)

### ISSUE THREAD

**Issue by ath88** [eslint/eslint#5502]
**When does this rule warn?**
When there is a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) in a file checked by ESLint. This has happened to me after inheriting some code. My editor (atom) doesn't show the mark, but I see it on `git diff`. 

**Is this rule preventing an error or is it stylistic?**
Stylistic

**Why is this rule a candidate for inclusion instead of creating a custom rule?**
I believe this rule is related to whitespace rules, which are in the ESLint core already. 

**Are you willing to create the rule yourself?**
Yes, though I am not sure how to, yet.

**Comment by platinumazure** [comment]
Sometimes the BOM is desirable. Maybe this would be better specified as a `bom` rule which takes in options "always" or "never", with "never" being equivalent to the original proposal?

**Comment by ath88** [comment]
@platinumazure That could be better. I don't know the cases where BOM is desirable. Maybe you would enlighten me? :)

**Comment by platinumazure** [comment]
@ath88 The BOM is useful when files are stored in UTF-16 or other formats with characters wider than 8 bits; in that case, the BOM is required in order to help big-endian and little-endian architectures determine which way the text was encoded. Most of the time, though, I would say it is unnecessary (and until we offered first-class BOM support with ESLint 2.0, the `no-irregular-whitespace` rule actually flagged it).

I would be willing to concede that the "never" option might be the more sensible default. I just want the flexibility :smile:

And good news: I have found that we do track files having BOM or not on the `SourceCode` object, so I would highly encourage you to volunteer to create the rule. It will be a great experience and I can help you out.

ESLint core team: I would be willing to champion this rule, if my voice counts for anything there.

**Comment by ilyavolodin** [comment]
I thought that we already covered BOM somewhere. There was a request for it a few month back. #4935 I assume you want the reverse behavior?

**Comment by platinumazure** [comment]
@ilyavolodin I don't think that was for a rule. That was for tracking it in `SourceCode`, no? It has the side-effect of making `no-irregular-whitespace` usable for files that are stored with BOM, though.

**Comment by ath88** [comment]
@platinumazure It is true that BOM is useful when files are stored in UTF-16. I guess its because I don't see why anyone would use UTF-16 over UTF-8. :)

But, if `no-irregular-whitespace` does flag BOM, then this rule might be superfluous?

I will volunteer, if the rule is deemed worthy. :)

**Comment by platinumazure** [comment]
@ath88 `no-irregular-whitespace` flags all occurrences of the BOM, whether at the beginning of the file or not.

With the recent change to detect if a file has BOM and strip it away from text before parsing (referenced by @ilyavolodin), `no-irregular-whitespace` should only flag BOM if it's in the middle of the file. It should no longer flag it at the beginning of the file.

I think this rule makes sense, separate from `no-irregular-whitespace`. `no-irregular-whitespace` is meant to flag unusual whitespace that can mess with concatenation scripts or throw browsers off, which the BOM can do in the middle of a file. But at the beginning of a file, most build tools are smart enough to handle BOM being present or absent. Then it becomes a stylistic/consistency concern whether or not to use the BOM, hence why this new rule makes a lot of sense.

**Comment by ath88** [comment]
I see. The suggestion will then be; the `no-bom`-rule should only flag BOMs in the beginning of the file. As mentioned, I will volunteer, if the rule is worthy.

**Comment by mysticatea** [comment]
I wrote #4935 for #4878 "Allow utf-8 bom with no-irregular-whitespace" :)

I like `unicode-bom` rule which has an option `"never"/"always"` and fixable.

**Comment by nzakas** [comment]
Sounds like @mysticatea is championing this rule.

**Comment by alberto** [comment]
So, @ath88, do you want to implement this?

**Comment by ath88** [comment]
@alberto Oh, yes! I will try to submit a PR this week. :)

**Comment by platinumazure** [comment]
To confirm, we'll be implementing `unicode-bom` with always/never, not `no-bom` with no option, correct?

If so, can someone please change the title of this issue accordingly? Thanks!
