### ISSUE TITLE
Docs: Missing examples in rule pages

### ISSUE THREAD

**Issue by pedrottimark** [eslint/eslint#5529]
This issue will accumulate rule pages in which **examples** of code are **missing** as requested in https://github.com/eslint/eslint/pull/5375#issuecomment-187454308

and according to guidelines in https://github.com/eslint/eslint/issues/5446#issuecomment-191306528 for which the exceptions are repeated here:

Examples of some options (for example, `allow`, `exceptions`, `ignore`) can omit **incorrect** code because it is the same as (or a part of) the incorrect code in a preceding example.

Examples of a few options (for example, `builtInGlobals` or `{ "hoist": "all" }` in no-shadow) can omit **correct** code because they are “reverse exceptions” which add to the what is incorrect by default for the rule.

**Comment by pedrottimark** [comment]
From #5375 Variables:

- [ ] no-delete-var: **correct** code for this rule
- [ ] no-shadow: **correct** code for this rule

**Comment by pedrottimark** [comment]
From #5470 Best Practices part 1:

- [ ] eqeqeq: **correct** code for this rule

**Comment by pedrottimark** [comment]
From #5506 Best Practices part 2:

- [ ] no-extend-native: **correct** code for this rule

**Comment by pedrottimark** [comment]
From #5544 Best Practices part 3:

- [ ] no-native-reassign: **correct** code for this rule [if there is any that makes sense]
- [ ] no-native-reassign: additional **correct** code for this rule with a sample `"exceptions"` option
- [ ] no-script-url: **correct** code for this rule [if there is any that makes sense]

**Comment by pedrottimark** [comment]
From #5596 Best Practices part 4:

- [ ] no-self-compare: **correct** code for this rule
- [ ] no-void: **correct** code for this rule
- [ ] no-with: **correct** code for this rule
- [ ] strict: **incorrect** and **correct** for this rule with the default `"safe"` option

**Comment by scriptdaemon** [comment]
I'd like to add to this issue tracking for missing examples for arrow functions to relevant rules. There was a commit in the past that added arrow functions to a large number of rules, but not all rule docs were updated with examples: https://github.com/eslint/eslint/commit/accca0b7d21d96e33fe542b87bf79ac17d541f08 (@pedrottimark If you feel this should be a separate issue, I can move it).

For now, I'm listing here all rules updated in the aforementioned commit. We can check off the rules that have already had examples added and the rules that we add them to during our restructuring (and add more rules to the list that check arrow functions that were not added in that commit).

- [ ] block-scoped-var
- [ ] brace-style
- [ ] comma-spacing
- [ ] complexity
- [ ] consistent-return
- [ ] func-style
- [ ] handle-callback-err
- [ ] max-depth
- [ ] max-nested-callbacks
- [ ] max-params
- [ ] max-statements
- [ ] no-constant-condition
- [ ] no-empty
- [ ] no-extra-bind
- [ ] no-extra-strict
- [ ] no-loop-func
- [ ] no-shadow-restricted-names
- [ ] no-unused-expressions
- [ ] no-wrap-func
- [ ] one-var
- [ ] strict
- [ ] valid-jsdoc
- [ ] vars-on-top

**Comment by kaicataldo** [comment]
Looks like work on this has stalled...Thoughts on what we should do with the @pedrottimark's unfinished work? I haven't looked through all the issues, but maybe we could make new issues that make the work friendly for new contributors and put the `help wanted` label on them.

**Comment by scriptdaemon** [comment]
@kaicataldo I had thought to do what's listed myself, but didn't yet as I wasn't sure if there would be more added.

I suppose I can do what's in the thread as it is so this can be closed, and if anything else comes up they can be handled individually?

**Comment by kaicataldo** [comment]
@scriptdaemon Sorry, this fell off my radar. Are you working on this? If not, I think it's time to close this as there doesn't seem to be enough interest to drive it forward.

**Comment by scriptdaemon** [comment]
Feel free to close. I hope to start contributing again, but I don't know when that will be so I won't make any promises.
