### ISSUE TITLE
Migration docs from JSHint to ESLint

### ISSUE THREAD

**Issue by mduvall** [eslint/eslint#554]
Migrating and cross-referencing the rules between different linting tool was less than fun, flipping between documentation pages a lot and such. Was thinking it may be useful to provide a utility (maybe outside of this main repository) that converts `.jshintrc` to a usable `.eslintrc`. Thoughts?

**Comment by valorkin** [comment]
@nzakas I wrote this just for fun and my usage https://github.com/valorkin/eslint-rules-mapper
here is jshint to eslint rules map:
https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js

**Comment by nzakas** [comment]
Wow that is awesome. Please be sure to file issues for any missing rules so others can chip in.

**Comment by valorkin** [comment]
@nzakas except `indent` nothing interesting,

relaxing options:
* [supernew](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L507)
* [laxbreak](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L514)
* [validthis](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L541)
* [noyield](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L571)
* [lastsemic](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L589)
* not sure about [expr](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L625)
* [elision](https://github.com/valorkin/eslint-rules-mapper/blob/master/lib/jshint/jshintRulesMap.js#L643)

and environment presets:
- mootools
- couch
- qunit
- yui
- wsh
- worker
- nonstandard
- dojo
- typed

**Comment by kentcdodds** [comment]
I would be interested in this. I have a very large project on jshint. I don't have time to migrate and figure out the nuances. A tool like this would be very helpful and encourage me to make the switch.

**Comment by valorkin** [comment]
@kentcdodds https://github.com/valorkin/eslint-rules-mapper
it is already working, check it, not really user friendly but working:)
