### ISSUE TITLE
`--no-ignore` should not un-ignore node_modules

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#5547]
**What version of ESLint are you using?**
Master

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
Espree

**What did you do? Please include the actual source code causing the issue.**
Ran eslint with `--no-ignore` flag

**What did you expect to happen?**
Ignore settings from `.eslintignore` to be disregarded, as indicated in docs.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint linted all files within `node_modules`.

Despite having [tests](https://github.com/eslint/eslint/blob/d727f17f4efc888ed0e59259a4e4cac01a42f0d9/tests/lib/ignored-paths.js#L375-L383) to assert that `--no-ignore` will cause `node_modules` to be linted, I think this is not the behavior we expect or want.  

The --no-ignore docs say:
> --no-ignore
> Disables excluding of files from .eslintignore and --ignore-path files.

They don't say anything about also disabling default ignores.

After https://github.com/eslint/eslint/issues/5410 is fixed, it will be possible to lint within node_modules by using a negation pattern.  (e.g. `!/node_modules/package-to-lint/`), at which time I think it would make sense to keep `--no-ignore` from linting `/node_modules/` and `/bower_components/`.

Does the team agree?

**Comment by ilyavolodin** [comment]
Agree.

**Comment by alberto** [comment]
Wouldn't this be a breaking change?

**Comment by IanVS** [comment]
Personally I see it as a bug fix, since the current behavior is not as
documented or expected.

**Comment by alberto** [comment]
I just realized that if `--no-ignore` ignores `.eslintignore` files, it won't be possible to uningnore anything at the same time :sweat_smile:

**Comment by platinumazure** [comment]
@alberto Is that really so, given one could specify ignore patterns in the CLI using `--ignore-pattern`?

**Comment by nzakas** [comment]
`--no-ignore` is mostly used for testing purposes (at least, that's why it was added, IIRC). I agree, this seems like a bug that was leftover after the ignore file refactoring.

**Comment by alberto** [comment]
@platinumazure not very intuitive, but :+1: given the context.

**Comment by IanVS** [comment]
Unfortunately it looks like https://github.com/eslint/eslint/pull/5648 did not fully fix this issue.  It addressed it inside of `ignored-paths.js`, but we also do some checking for `options.ignore` in `cli-engine.js` in [isPathIgnored()](https://github.com/eslint/eslint/blob/866743150898bf109efa3cb320a18b444f9683d4/lib/cli-engine.js#L695) and [executeOnText()](https://github.com/eslint/eslint/blob/866743150898bf109efa3cb320a18b444f9683d4/lib/cli-engine.js#L658).

Testing manually on the cli reveals that `--no-ignore` still causes `node_modules` to be linted as before.

**Comment by nzakas** [comment]
So this would only affect people using the API?

**Comment by IanVS** [comment]
The fix only was made in `ignored-paths`, which caused its own tests to pass.  The API and CLI are still broken.

**Comment by alberto** [comment]
Ooops, sorry. I would swear I had also manually tested it... :(

**Comment by IanVS** [comment]
Working on this.
