### ISSUE TITLE
ESLint: Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by budarin** [eslint/eslint#5552]
Created new simple project with one file:

        import React from 'react';
        import { render } from 'react-dom';
        import { Router, browserHistory } from 'react-router';
        
        render((
            <Router history={browserHistory} routes={routes}>
            </Router>
        ), document.getElementById('root'));

created simple .eslintrc with the help eslint --init:

        {
            "env": {
                "es6": true,
                "node": true,
                "browser": true
            },
            "extends": "eslint:recommended",
            "ecmaFeatures": {
                "jsx": true,
                "experimentalObjectRestSpread": true
            },
            "plugins": [
                "react"
            ],
            "rules": {
                "no-console": 0,
                "indent": [
                    2,
                    4
                ],
                "quotes": [
                    2,
                    "single"
                ],
                "semi": [
                    2,
                    "always"
                ]
            }
        }

enabled esLint settings in IDEA and got the error:

Error:(1, 1) ESLint: Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by ilyavolodin** [comment]
You need to add `sourceType: "module"` to your config. There is no way for us to identify automatically what's a script and what's a module, so you have to provide that information in config file. For more details look in the [documentation](http://eslint.org/docs/user-guide/configuring#specifying-parser-options)

**Comment by budarin** [comment]
thanks

**Comment by ilyavolodin** [comment]
You need to include `eslint-plugin-react`. ESLint doesn't support React on it's own, you need plugin to handle that.

**Comment by budarin** [comment]
it's installed by eslint --init command and included in .eslintrc
   "plugins": [
            "react"
        ],

**Comment by ilyavolodin** [comment]
You'll need to enable appropriate rules from `eslint-plugin-react` package. Not sure which ones, you'll have to look at the repository for instructions. Also we have gitter channel for questions like that here: https://gitter.im/eslint/eslint

**Comment by budarin** [comment]
thanks
