### ISSUE TITLE
Parse error for function call to await()

### ISSUE THREAD

**Issue by jlagerblad** [eslint/eslint#5564]
**What version of ESLint are you using?**
2.4.0 and 2.2.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```JavaScript
{
    "extends": "eslint:recommended",

    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },

    "parserOptions": {
        "sourceType": "module"
    },

    "globals": {
        "$": false,
        "cs": false,
        "DEBUG": false,
        "LOG_DEBUG": false,
        "LOG_INFO": false,
        "LOG_WARN": false,
        "LOG_ERROR": false,
        "TIMING": false
    },

    "ecmaFeatures": {
        "modules": true
    },

    "rules": {
        "eol-last": [2],
        "global-strict": [0],
        "key-spacing": [0],
        "new-cap": [0],
        "no-alert": [0],
        "no-console": [2],
        "no-sequences": [0],
        "no-trailing-spaces": [2],
        "no-underscore-dangle": [0],
        "no-unused-vars": [2, { "args": "none" }],
        "no-use-before-define": [2, "nofunc"],
        "quotes": [0, "single", "avoid-escape"]
    }
}
```
**What did you do? Please include the actual source code causing the issue.**
I ran: eslint -f unix ./src
On a file with this content, there is a parse error (It used to work with eslint 1.x)
```JavaScript
/**
 *
 */

var queue = globals.queue;

export default function(){
    queue().await();
}
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
/Users/jonas/work/csd-js-modules/data-layer/src/api/test.js:8:13: Parsing error: Unexpected token await [Error]

2 problems

**Comment by faceleg** [comment]
Confirmed using setup described above: https://gist.github.com/faceleg/29f16af0b146a59d6b99

**Comment by BYK** [comment]
`await` is a reserved word so I'm not sure if this is actually a bug.

**Comment by BYK** [comment]
@nzakas, @michaelficarra - the following code works in my Node REPL (both in normal and strict modes) so I think this is a bug with Espree.

**Comment by michaelficarra** [comment]
Yep.

**Comment by mysticatea** [comment]
`espree` v3.1.2 released. :smile:
