### ISSUE TITLE
prefer-const not working consistently

### ISSUE THREAD

**Issue by karolyi** [eslint/eslint#5568]
**What version of ESLint are you using?**
2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
{
  "ecmaFeatures": {
    "modules": true
  },
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "babel-eslint",
  "rules": {
    "semi": [2, "never"],
    "quotes": [2, "single"],
    "strict": [2, "never"],
    "max-len": [2, {"code": 80, "tabWidth": 4, "ignoreUrls": true}]
  },
  "globals": {
    "riot": true
  },
  "plugins": [
    "riot"
  ],
  "extends": ["eslint:recommended", "airbnb/base"]
}
```

**What did you do? Please include the actual source code causing the issue.**
I might be missing something, but I think this rule is still not working right.

since `const` has a different behavior in browsers and nodejs, I get different results with using for cycles.

browser (latest chrome):
![image](https://cloud.githubusercontent.com/assets/987055/13743353/8d3d2b16-e9e1-11e5-92d0-8f86a1c398ac.png)

nodejs (v5.7.1):
![image](https://cloud.githubusercontent.com/assets/987055/13743375/aa471384-e9e1-11e5-9385-f41cb31a04de.png)

yet eslint with `prefer-const` still wants to enforce the usage of const in the for cycle declaration with `error: 'key' is never reassigned, use 'const' instead`

setting the eslint directive `/* eslint-env node */` directive doesn't help.

can we get this fixed please?

**What did you expect to happen?**
`prefer-const` not getting enforced either when sensing a for cycle or node environment

**What actually happened? Please include the actual, raw output from ESLint.**
see above.

**Comment by ilyavolodin** [comment]
This is correct behavior based on the spec. Browsers/node have bugs in their implementation of the `const` (before, they didn't work at all). Closing as there is nothing to fix here.

**Comment by mysticatea** [comment]
@karolyi Node.js v5 has not supported ES6 `const` variables yet in sloppy mode. Please use strict mode.
