### ISSUE TITLE
Adding custom rules to one CLIEngine instance affects other CLIEngine instances

### ISSUE THREAD

**Issue by nickiaconis** [eslint/eslint#5577]
## What version of ESLint are you using?

eslint@2.3.0

## What parser (default, Babel-ESLint, etc.) are you using?

Default parser.

## Please show your full configuration:

```javascript
// ./.eslintrc
{
  "extends": "nightmare-mode/node",
  "rules": {
    "arrow-parens": [2, "always"],
    "no-console": 0,
    "prefer-arrow-callback": 0,
    "prefer-reflect": 0,
    "prefer-template": 0,
    "no-restricted-syntax": [2, "WithStatement"],
    "no-empty-label": 0,
    "no-labels": 2,
    "space-after-keywords": 0,
    "space-before-keywords": 0,
    "space-return-throw-case": 0,
    "keyword-spacing": 2,
    "newline-before-return": 0,
    "newline-per-chained-call": 0,
    "no-magic-numbers": 0,
    "arrow-spacing": 0
  }
}
```

```javascript
// ./test/.eslintrc
{
  "env": {
    "mocha": true
  }
}
```

```javascript
// ./test/fixture/.eslintrc
{
  "extends": "nightmare-mode/node"
}
```

```javascript
// ./conf/eslint.json
{
  "extends": "nightmare-mode/node",
  "rules": {
    "no-console": 0,
    "quotes": [1, "double"]
  }
}
```

```javascript
// ./conf/rules/no-alert.js
module.exports = function noAlerts(context) {
  return {
    CallExpression: function callExpression(node) {
      if (node.callee.name === 'alert') {
        context.report(node, 'testing custom rules.');
      }
    }
  };
};
```

## What did you do? Please include the actual source code causing the issue.

[Source code that creates the CLIEngine instance(s)](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/lib/index.js#L86).

[Test code that triggers the instance creation mentioned above](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/test/test.js).

## What did you expect to happen?

I expected the [test on line 59](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/test/test.js#59) to pass.

## What actually happened? Please include the actual, raw output from ESLint.

The [assertion on line 24](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/test/test.js#L24) fails because the CLIEngine instance created for the [test on line 59](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/test/test.js#59) is still using the custom rules from the CLIEngine instance created for the [test on lines 31-42](https://github.com/nickiaconis/broccoli-eslinter/blob/4fa11bc24a6f9a59325cc83c7678839257e00223/test/test.js#L31-L42).

**Raw test output:**
> niaconis@niaconis-mn1 /Users/niaconis/macspace/broccoli-eslinter (input-tree)
> » npm run babelify && npm run babelify-tests && node-inspector & node_modules/mocha/bin/mocha build/test/test.js -d --debug-brk; freeport 8080
> [1] 51463
> Debugger listening on port 5858
>
> > broccoli-lint-eslint@2.0.0 prebabelify /Users/niaconis/macspace/broccoli-eslinter
> > rimraf build
>
>
> > broccoli-lint-eslint@2.0.0 babelify /Users/niaconis/macspace/broccoli-eslinter
> > babel lib --out-dir build
>
> lib/index.js -> build/index.js
>
> > broccoli-lint-eslint@2.0.0 babelify-tests /Users/niaconis/macspace/broccoli-eslinter
> > babel test --ignore fixture --out-dir build/test
>
> test/helpers/run-eslint.js -> build/test/helpers/run-eslint.js
> test/test.js -> build/test/test.js
> Node Inspector v0.12.7
> Visit http://127.0.0.1:8080/?port=5858 to start debugging.
>
>
>   EslintValidationFilter
>     ✓ should report errors (5539ms)
>     ✓ should accept rule paths (255ms)
>     ✓ should accept config file path (323ms)
>     1) should accept a tree/node as the input
>
>
>   3 passing (2h)
>   1 failing
>
>   1) EslintValidationFilter should accept a tree/node as the input:
>      AssertionError: No custom rules defined: expected 'test/fixture/1.js: line 1, col 1, Error - testing custom rules. (no-alert)\ntest/fixture/1.js: line 1, col 1, Error - \'alert\' is not defined. (no-undef)\n\n2 problems\ntest/fixture/2.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)\ntest/fixture/2.js: line 1, col 5, Error - Identifier \'broccoli_conf\' is not in camel case. (camelcase)\ntest/fixture/2.js: line 1, col 5, Error - \'broccoli_conf\' is defined but never used (no-unused-vars)\n\n3 problems\ntest/fixture/3.js: line 4, col 3, Error - Unexpected console statement. (no-console)\n\n1 problem' to not contain 'testing custom rules'
>       at assertLinting (build/test/test.js:26:65)
>       at lib$rsvp$$internal$$tryCatch (node_modules/rsvp/dist/rsvp.js:1036:16)
>       at lib$rsvp$$internal$$invokeCallback (node_modules/rsvp/dist/rsvp.js:1048:17)
>       at lib$rsvp$$internal$$publish (node_modules/rsvp/dist/rsvp.js:1019:11)
>       at lib$rsvp$asap$$flush (node_modules/rsvp/dist/rsvp.js:1198:9)

**Raw eslint output:**
> test/fixture/1.js: line 1, col 1, Error - testing custom rules. (no-alert)
> test/fixture/1.js: line 1, col 1, Error - \'alert\' is not defined. (no-undef)
>
> 2 problems
> test/fixture/2.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)
> test/fixture/2.js: line 1, col 5, Error - Identifier \'broccoli_conf\' is not in camel case. (camelcase)
> test/fixture/2.js: line 1, col 5, Error - \'broccoli_conf\' is defined but never used (no-unused-vars)
>
> 3 problems
> test/fixture/3.js: line 4, col 3, Error - Unexpected console statement. (no-console)
>
> 1 problem

## Have you been able to work around this?
*I added this section.*

Yes, I have. You can see the changes involved in [this commit](https://github.com/nickiaconis/broccoli-eslinter/commit/b2b7faf618651a675253dda094aa068e5d499178). As I understand it, this is not an ideal solution because the [`testReset` function](https://github.com/eslint/eslint/blob/master/lib/rules.js#L91-L98) is marked as "Use for tests only."

**Comment by ilyavolodin** [comment]
This sounds like another instance of ByRef modification of config object. I thought we already deepClone configs every time, but apparently not. @gyandeeps you did the modification to deepCloning last time, do you want to take a look?

**Comment by gyandeeps** [comment]
@nickiaconis Have you tried it with a simple example of invoking the CLIEngine directly and creating 2 instances of it then try to run it in on some files?
For above example I dont want to understand all the broccoli jazz going in the use case. A simplified use case would be really helpful.
Thanks

**Comment by nickiaconis** [comment]
@gyandeeps I've reworked the [tests](https://github.com/nickiaconis/broccoli-eslinter/blob/1ffa438617ae12e28a2abe6da343561579a0cc9f/test/test.js) so they no longer use broccoli. Instead [the CLIEngine instances](https://github.com/nickiaconis/broccoli-eslinter/blob/1ffa438617ae12e28a2abe6da343561579a0cc9f/test/test.js#L11-L25) are created directly in that file. You can see on TravisCI that the [test is still failing](https://travis-ci.org/nickiaconis/broccoli-eslinter/builds/116183308) for the same reason I gave in my initial message.

**Comment by gyandeeps** [comment]
So there are no things going on here:

1. We load all the built in rules on the first go [here](https://github.com/eslint/eslint/blob/master/lib/rules.js#L106) and then use that collection across all the instances of CLIEngine. Now if one of the CLIEngines uses a cutsom rule directory it loads rules from that to that collection (in your case you overwrote the standard rule, which is not encouraged). **All in all, a central store of rules is used across all instances of CLIEngine.**

1. Since you are using `no-alert` for your custom rule you basically end up overwriting the original rule's definition.

@eslint/eslint-team Its an interesting scenario here, any thoughts?

**Comment by platinumazure** [comment]
That is interesting. Since custom rules are not prefixed like plugin rules are, maybe we should throw at config load time if a custom rule is named exactly the same as a core rule?

**Comment by nickiaconis** [comment]
The rule name is a bit of a :bike: :house: bike shed here. The custom rule could be named anything. The fact that an instance of CLIEngine that _didn't load any custom rules_ is having custom rules applied to it is the issue, and I believe it is faulty/a bug.

**Comment by nickiaconis** [comment]
Since we were getting off track because of the rule name, [I renamed it](https://github.com/nickiaconis/broccoli-eslinter/commit/94e62d2eacd88cdaa8112c2c785bbf164d1d913c). You can see by the [latest Travis build](https://travis-ci.org/nickiaconis/broccoli-eslinter/builds/116447849), even when not clobbering a built-in rule, the issue remains.

**Comment by gyandeeps** [comment]
In your first test, it will throw an error something like this
`Definition for rule 'custom-no-alert' was not found`
because the first test has not loaded this rule. Your second test adds those rules to that central object as mentioned in [[1] on my above comment](https://github.com/eslint/eslint/issues/5577#issuecomment-197398475).

Again you can discard my point 2 but the main thing is what i have described in point 1.

**Comment by nickiaconis** [comment]
Yes, I came to the same conclusion as your point 1 by looking at the code, but I am inclined to believe it shouldn't work this way.

Will rewrite the tests again to mitigate missing rule issue...

**Comment by nickiaconis** [comment]
Oh... it's finally clicked. If I load a custom rule with a non-overlapping name and only use a config that activates that rule with the instances for which I expect that rule to be used, the other instances will not have a config that activates that rule, and it won't matter that it's been loaded.

So the naming of the rule _does_ actually play a large role here. Sorry it took me to long to come around to that conclusion. I was simply confused, in part by this test suite I've inherited.

Should we discuss the custom rule/core rule overlap case?

**Comment by nzakas** [comment]
> Should we discuss the custom rule/core rule overlap case?

That's pretty different from what is already being discussed in this issue. I'd suggest opening a new issue if you want to talk more about that topic.

**Comment by nickiaconis** [comment]
It seemed to be the direction the conversation was headed here.

**Comment by alberto** [comment]
Is this a bug then or should it be closed?

**Comment by nzakas** [comment]
Unless someone wants to volunteer to look into this, we should close it.

**Comment by kaicataldo** [comment]
Closing this because we haven't made any progress in months. Thanks for contributing!
