### ISSUE TITLE
prefer-const should somehow figure out mixed destructuring

### ISSUE THREAD

**Issue by djMax** [eslint/eslint#5594]
eslint 2.4.0
babel-eslint 5.0.0
airbnb/base

I have a situation where I want to use destructuring, but one of the variables will be const and one will not. eslint's prefer-const rule basically makes this impossible and I don't see a way to configure around it.

```
function testData() {
  return {a:1,b:2};
}
let {a,b} = testData();
a=6;
```

If I use let, prefer-const fires. If I use const, no-const-assign will fire. It seems like the "reasonable" thing here would be an option that tells prefer-const to ignore destructuring? It would be nice if it only ignored "mixed" cases like this, but not sure how feasible that is.

**Comment by BYK** [comment]
Or you can just put `// eslint-disable-line prefer-const` at the and of that line? :)

**Comment by djMax** [comment]
Yes, but it's hard to restore my sense of self worth after that. :)

**Comment by BYK** [comment]
How is it different than the rule itself ignoring that line automatically? :)

**Comment by djMax** [comment]
Because I want to be able to control the const/let usage globally without littering the code with disabling-comments. I think this is a conceptual issue with the rule and destructuring that should have at least some rhyme or reason to it.

**Comment by BYK** [comment]
@mysticatea is your latest PR address this? Also @eslint/eslint-team what do you think?

**Comment by ilyavolodin** [comment]
I think excluding destructuring from this rule might be a good idea.

**Comment by nzakas** [comment]
In think an option is the best way to go. Destructuring is pretty common in ES6 code, so we lose a lot of we skip it by default. So maybe `checkDestructuring` with a default value of true?

**Comment by alberto** [comment]
@nzakas do you mean an additional option with the current behaviour?

**Comment by mysticatea** [comment]
I remembered a previous discussion: #3223

I'd like to keep the behavior as is, by default.
Then I can add an option to ignore mixed cases. The rule uses `context.getDeclaredVariables(node)` since #5591, so it can check whether mixed or not easily.

**Comment by nzakas** [comment]
@alberto yes. Add a new option that defaults to the current behavior, but you can toggle it off.

**Comment by alberto** [comment]
I was thinking along the line of what @mysticatea explained above, ignoring if at least one of the variables can't be a const.

**Comment by nzakas** [comment]
Do as you wish, I just want the default behavior to remain the same.

**Comment by djMax** [comment]
I'm in the "do as you wish" category too, but I'd argue that IF we can know that it's a mixed assignment, defaulting to asking the developer to do something impossible seems wrong. i.e. if you have a mixed case, you CANNOT simply do what the error says and switch one of them to const. So either it shouldn't error or at least change the error message to something like 'do not use destructuring when some variables are const and some are not.' Which of course makes it clear why the default should probably be to let them go. :)

**Comment by nzakas** [comment]
@djMax but you can change it, you'd just need to break up the assignment. The message currently says:

> 'b' is never reassigned, use 'const' instead.

So you can change your code so `b` uses `const`:

```js
function testData() {
  return {a:1,b:2};
}

const result = testData(),
    {b} = result;

let {a} = result;
a=6;
```

And with the new option, you'll be able to suppress that behavior if you want. I think this is a good solution.

**Comment by djMax** [comment]
Yeah, not a big deal. It's just basically hiding a little info by using the same error message. But I'm fine with it.

**Comment by mysticatea** [comment]
Oh, I hadn't noticed the following pattern.

```js
let a, b;

({a, b} = foo());
a = 0;
```

In this case, I cannot use `context.getDeclaredVariables(node)` to find "mixed" or not.
I'm thinking...
