### ISSUE TITLE
Feature: Expose `extends` resolution

### ISSUE THREAD

**Issue by kentcdodds** [eslint/eslint#5600]
@ilyavolodin recommended that I file an issue here to discuss whether we can expose how ESLint resolves `extends`. More on that conversation [here](https://github.com/kentcdodds/eslint-find-new-rules/pull/4/files/da460030371d0599cd0162ad1d47c3b694484855#r56394388)

The TL;DR: @ta2edchimp and I are working on a tool that allows you to check whether your configuration is explicitly configuring all available rules (currently only supports built-in rules, but eventually will [support plugin rules](https://github.com/kentcdodds/eslint-find-new-rules/issues/3) too).

Right now, this tool will check all the keys and makes sure that you're not missing any that exists in the [rules](https://github.com/eslint/eslint/tree/22046939a7f250e6cce40a2acdfd3581a2ce29f5/lib/rules) directory. But to really accomplish the goal, we need to be able to determine _all_ configured rules and that requires resolving any configurations that you're extending and adding those rules to the list of explicitly configured rules before doing [the diff](https://github.com/kentcdodds/eslint-find-new-rules/blob/1af8dc1b8d5faf83cf50f44d2d9c2d7aedc2ba1f/index.js#L13).

So, with that context:

Could we get ESLint to expose [its mechanism](https://github.com/eslint/eslint/blob/22046939a7f250e6cce40a2acdfd3581a2ce29f5/lib/config/config-file.js#L329-L367) for resolving `extends`? Part of the requirement for us is that it cannot resolve all the way down to the ESLint defaults.

If this is acceptable, I think that @ta2edchimp or I would be willing to do an implementation with a little guidance. :-)

**Comment by platinumazure** [comment]
Have you looked at the CLIEngine docs? I think the [`getConfigForFile()`](http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile) method could be pretty useful for getting the final config including all extensions.

**Comment by ta2edchimp** [comment]
Thanks for your response! We've already been hinted towards `getConfigForFile()`, but – as I understand it – that would only give us the configuration object for a given file (that is, by looking up the „responsible“ eslint config via `.eslintrc` or `package.json` based on the given files location).

What we want to achieve, is to get the compiled config object, starting from a given configuration file, aggregating all applicable rules, by applying the configuration inherited by its `extends` property.
To be precise: we'd need sth. like the [`getConfig()`](https://github.com/eslint/eslint/blob/master/lib/config.js#L200-L270) exposed via api.

**Comment by ilyavolodin** [comment]
@ta2edchimp @kentcdodds Could you guys provide an example of output that you are looking for? Right now I'm not sure I fully understand what do you expect to get as a result.

**Comment by kentcdodds** [comment]
Sure thing.

Given the following configs:

*index.js*

```javascript
module.exports = {
  rules: {
    'comma-dangle': 0
  }
}
```

*other.js*

```javascript
module.exports = {
  extends: './index',
  rules: {
    'no-cond-assign': 2
  }
}
```

I would expect to get:

```javascript
const config = getConfig('./other.js')

const configDeepEquals = {
  'no-cond-assign': 2,
  'comma-dangle': 0
}
```

**Comment by kentcdodds** [comment]
Excuse me, if you're looking at this via email, please see my update :point_up_2:

**Comment by ilyavolodin** [comment]
@kentcdodds `getConfigForFile` will do that right now. I know you mentioned about not wanted to merge in `eslint:recommended` could you provide an example of what you want to happen if you extend from `eslint:recommended` and some other shareable config?

**Comment by kentcdodds** [comment]
If someone explicitly extends from `eslint:recommended` then I think we're :+1: I think I was confused and thought this happened by default.

**Comment by kentcdodds** [comment]
Just tried it out, this is exactly what we need. Thanks a bunch!

**Comment by platinumazure** [comment]
FYI, the reason why `getConfigForFile()` is the way to go (and why we can't just expose a `getConfig()` is because configurations do change as you traverse directories (e.g., a new `.eslintrc` file could be found in a subdirectory, which does change the effective config). So you might want to bear that in mind as you design your tool-- it is possible that different files in a subdirectory could reference different configs, and thus it becomes important to check again for rules being included or not.

**Comment by kentcdodds** [comment]
Yeah, thanks for the tip. I'm thinking that we'll create a file in a temporary directory or something so we're not impacted by `.eslintrc`... Thinking.... :-)

**Comment by sarbbottam** [comment]
Completely out of this discussion, please excuse me for that.

Hi @platinumazure,
 
>> e.g., a new .eslintrc file could be found in a subdirectory, which does change the effective config

Does this mean, I could have different lint criteria for `src/` and `test/`, if I have disfferent `.eslintrc`s in `src/` and `test/` 

Am I reading this correct?

Thanks!

**Comment by kentcdodds** [comment]
> Does this mean, I could have different lint criteria for src/ and test/, if I have disfferent .eslintrcs in src/ and test/
> 
> Am I reading this correct?

Yes! You totally can, and it's quite handy :-)
