### ISSUE TITLE
Rule proposal: no-padded-objects

### ISSUE THREAD

**Issue by codekirei** [eslint/eslint#5603]
**When does this rule warn? Please describe and show example code:**

This potential rule is similar in spirit to [padded-blocks](http://eslint.org/docs/rules/padded-blocks) and [no-multi-spaces](http://eslint.org/docs/rules/no-multi-spaces), though is also closely related to [array-bracket-spacing](http://eslint.org/docs/rules/array-bracket-spacing) and [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing). Because it is fairly broad and touches a lot of contexts, I'm not sure if this concept merits a new standalone rule or would be better implemented as additional configurable params to an existing rule or rules. Very open to direction here.

The main idea is extending the spacing-enforcement provided to blocks by `padded-blocks` to arrays and objects. I proposed the name `no-padded-objects`, a negative context &mdash; opposed to `padded-blocks`' positive context &mdash; because padding inside multiline objects is usually unintentional/erroneous, while padding inside blocks may well be intentional. I'm not at all attached to the name, though :smile:.

*The following patterns are considered problems:*
```js
/* eslint no-padded-objects: 2 */

var foo = [

  'bar',
  'baz'
];

var qux = {
  foo: 'foo',
  bar: 'bar'

};
```

*The following patterns are not considered problems:*
```js
/* eslint no-padded-objects: 2 */

var foo = [
  'bar',
  'baz'
];

var qux = {
  foo: 'foo',
  bar: 'bar'
};
```

It may also be useful to allow warning on extra linebreaks inside objects and arrays &mdash; this clearly doesn't line up with the `padded` concept of the name though.

Example of an in-between problem case:
```js
var foo = [
  'bar',

  'baz'
];
```

**Is this rule preventing an error or is it stylistic?**

Stylistic.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**

This rule is very general and is similar in scope to pre-existing rules such as the aforementioned `padded-blocks` and `no-multi-spaces`.

**Are you willing to create the rule yourself?**

Potentially. I haven't contributed to ESLint before, so I'm not super familiar with the codebase &mdash; but I would definitely be willing to give it a go.

**Comment by adamkdean** [comment]
We are in need of this rule presently, and would value it highly, should it be implement.

**Comment by zxqfox** [comment]
Something similar to [requirePaddingNewLinesInObjects](http://jscs.info/rule/requirePaddingNewLinesInObjects), [disallowPaddingNewLinesInObjects](http://jscs.info/rule/disallowPaddingNewLinesInObjects) but with options of [requirePaddingNewlinesInBlocks](http://jscs.info/rule/requirePaddingNewlinesInBlocks).

**Comment by kaicataldo** [comment]
Closing this because we haven't made any progress in months. Thanks for contributing!
