### ISSUE TITLE
JSX Spread Attributes Throwing Unexpected Token Error 

### ISSUE THREAD

**Issue by KieranP** [eslint/eslint#5608]
**What version of ESLint are you using?**

v2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default  (as far as I know)

**Please show your full configuration:**

`{
  "parserOptions": {
    "ecmaVersion": 5,
    "sourceType": "script",
    "ecmaFeatures": {
      "jsx": true
    }
  }
}`

**What did you do? Please include the actual source code causing the issue.**

`<ApplicationPresenter {...this.props} />`

**What did you expect to happen?**

The file should validate fine, as the "...this.props" spread operator is documented functionality:

https://facebook.github.io/react/docs/transferring-props.html

https://facebook.github.io/react/docs/jsx-spread.html

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint throws a parsing error: "Unexpected token ."

**Comment by hzoo** [comment]
You prob need `experimentalObjectRestSpread` - http://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by ilyavolodin** [comment]
And you also need `ecmaVersion: 6`, since if you are using object spread which is experimental feature, chances are, you are using other es6 features.

**Comment by nzakas** [comment]
Just verified you need `ecmaVersion: 6` in your config.

**Comment by kaicataldo** [comment]
Closing as the question has been answered
