### ISSUE TITLE
[no-unused-vars] destructuring like args

### ISSUE THREAD

**Issue by galambalazs** [eslint/eslint#5616]
Similarly to how `args` are handled, unused variables inside destructuring should be controllable too.

So instead of this:

```javascript
var [/*activeUsers*/, inactiveUsers] = partition(users, isUserActive);
```
One may safely write this:

```javascript
var [_activeUsers, inactiveUsers] = partition(users, isUserActive);
```

I see two solutions:

**1:** *Treat destructuring like arguments.*

 Make the same settings apply to them as   `args `. So if one has `{ "argsIgnorePattern": "^_" }` it applies to destructuring and _variables will be ignored. If one has `{"args": "after-used"}` then it applies to destructuring and only the last variable inside a destructuring has enforced usage.

**2:** *Add a separate option that works exactly like `args`.*

Something like `destr`,  `destrIgnorePattern`

**Comment by alberto** [comment]
`after-used` doesn't make much sense here. And since variables can be omited I'm not sure what `ignorePattern` brings either

**Comment by galambalazs** [comment]
It's about readability. Being explicit about what gets used and what gets left behind after destructuring.

In this example it looks straightforward because the partition gives your two mutually exclusive lists. 
````
var [ , inactiveUsers] = partition(users, isUserActive);
````

But there are more cases where destructuring has multiple elements with varying purposes.
````
var [ , , something] = fromSomeApi(users);
var [, protocol, , fullpath] = parsedURL; // this is from an MDN example
````
This is prone to a lot of programming errors where editing code can result in you removing the one small comma without you noticing and the matching breaks. Or simply understanding what you left behind. Revisiting the code and knowing how to get more data from the assignment if need be.

There are cases where you control the code and most of the time an { object } based destructuring makes more sense, but there are times where the destructuring is applied to outputs you don't control.

Starting with _ for ignored variables in pattern matching is considered a best practices in languages which had this for a long time (Erlang, Prolog).

````
var [ _name, _age, something] = fromSomeApi(users);
var [_all, protocol, _fullhost, fullpath] = urlParsedByRegex; // this is from an MDN example
````

**Comment by galambalazs** [comment]
To be clear: the developer should have a *choice* between the two styles above (explicitly ignored or omitted variables).

Currently ESLint does *not* give you the *choice*. If you enable unused vars (which is helpful) it doesn't allow you to use the explicitly ignored form.

**Comment by alberto** [comment]
Yes, I meant I don't see much benefit over your first example with commented out variables. There is no real difference between a comment and an unused variable. Let's wait and see what others think.

**Comment by mysticatea** [comment]
I may not understand this issue, but couldn't you use [varsIgnorePattern] option?

![image](https://cloud.githubusercontent.com/assets/1937871/13930916/45cdebcc-efe4-11e5-8d63-03423a27d989.png)

[varsIgnorePattern]: http://eslint.org/docs/rules/no-unused-vars#varsignorepattern

**Comment by galambalazs** [comment]
oh but you do understand :)
cheers
