### ISSUE TITLE
Global installation ignores local installation of  eslint-config-*

### ISSUE THREAD

**Issue by mohsen1** [eslint/eslint#5626]
**What version of ESLint are you using?**
> 2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
> None

**Please show your full configuration:**
> It is the result of `eslint --init`.
```
module.exports = {
    "extends": "google"
};
```

**What did you do? Please include the actual source code causing the issue.**
```
npm i -g eslint
eslint --init # selected Google as default
eslint .
```

**What did you expect to happen?**
Validates my project using Google default

**What actually happened? Please include the actual, raw output from ESLint.**

Error was thrown:
```
 eslint .
Cannot find module 'eslint-config-google' from '/usr/local/lib/node_modules'
Referenced from: /Users/mohsen/Projects/____/.eslintrc.js
Error: Cannot find module 'eslint-config-google' from '/usr/local/lib/node_modules'
Referenced from: /Users/mohsen/Projects/___/.eslintrc.js
 ....
```

Using the local installation works:
```
node_modules/.bin/eslint .
```
I have eslint-config-google installed locally

**Comment by ilyavolodin** [comment]
This is correct behavior. Please take a look at documentation here: http://eslint.org/docs/user-guide/configuring#configuring-plugins more specifically a note at the bottom.

**Comment by mohsen1** [comment]
Current behavior is not very intuitive. Having to install many eslint config packages globally isn't the cleanest way of using `eslint` global executable. Each repository should be responsible for owning their configuration packages. This is specially important when you have multiple repository on your machine depending to different versions of a eslint config package. 

Maybe consider changing this behavior and adding local config package installation a higher precedence?

**Comment by mysticatea** [comment]
[eslint-cli] may help you.

[eslint-cli]: https://www.npmjs.com/package/eslint-cli

**Comment by mohsen1** [comment]
I had this issue again today. I don't think it's the "correct" behavior. Most CLI applications take local configuration first and if that doesn't exists use global configuration.  Take for example `. gitattributes` of Git. 

Imagine this scenario:

You clone a repo and install its dependencies. Now if you run `eslint` to check for lint errors, it's going to complain about lack of global installation of a specific configuration package.

If you install that configuration package it works. But now you have a new problem. If I clone another repo that uses a different version of the same configuration I might get lint errors that are result of differences in version of global installation of that configuration package and the configuration package that was uses in this repo.
