### ISSUE TITLE
Build: Enable cache for CI integrations

### ISSUE THREAD

**Issue by BYK** [eslint/eslint#5641]
The CI integrations we use both offer caching:

- https://www.appveyor.com/docs/build-cache
- https://docs.travis-ci.com/user/caching/

This would save some time on CI build times and I don't see a reason to not do this.

If accepted, I'm willing to submit a PR.

**Comment by ilyavolodin** [comment]
Sounds like a worthwhile enhancement. Especially for appVeyor that takes forever to build. My only concern is what should be a good cache invalidation period.

**Comment by nzakas** [comment]
What is the problem we're trying to solve with this? I haven't experienced CI build times as being overly long. Has that been a problem?

**Comment by ilyavolodin** [comment]
AppVeyor takes a while to build, mostly due to one build at a time rule. But the faster the builds the faster it would take to get AppVeyor approval. Travis is pretty speedy as is, but better speeds never hurt:-)

**Comment by nzakas** [comment]
I'm not against caching, I'm just a bit concerned about potential side effects of caching. Right now, I understand exactly what the VMs are doing...with caching on, I'm no longer sure. I just really don't want to get into a situation where we're asking the question, "what happens if we run the test on a clean VM?"

So, that's my only concern. I'd still like to understand the situation where a faster CI is helpful, because in my experience we don't merge PRs typically until the next day, so going from two minutes to one minute on CI doesn't seem like it would matter that much.

**Comment by captbaritone** [comment]
From the top of the Travis.ci link (emphasis mine):

> The features described here are currently _only available for private repositories_ on travis-ci.com and our new container-based infrastructure.

**Comment by nzakas** [comment]
@captbaritone it's the "and" in that sentence that would allow us to use it. :)

**Comment by BYK** [comment]
>So, that's my only concern. I'd still like to understand the situation where a faster CI is helpful, because in my experience we don't merge PRs typically until the next day, so going from two minutes to one minute on CI doesn't seem like it would matter that much.

Faster feedback loop for contributers and preventing potential timeouts on AppVeyor. I never run tests on a "clean" slate anyways and our `package.json` should enforce any old dependencies to be upgraded to the latest minimum version we support anyways so I really don't see much downside. It is almost "stupid not doing this".

If we had shinkwrap though, we wouldn't even think about not enabling if you ask me.

**Comment by hzoo** [comment]
Maybe we can clear cache before a release in case?

**Comment by ilyavolodin** [comment]
I wonder if we can have master branch builds without cache, but PR builds with? Master builds are not time sensitive, but faster feedback for PR submissions is always a nice thing to have.

**Comment by hzoo** [comment]
Yeah :stuck_out_tongue: I think that sounds good if possible

**Comment by BYK** [comment]
In TravisCI, `master` cache is the cache used for all PRs against master and any new branches that doesn't have a cache yet so this doesn't look doable: https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches

That said Travis provides a command-line tool and a web interface to clear cache when necessary. We may chose to invalidate the cache when we see a `Upgrade` or `Build` commit or just with every new release.

**Comment by ilyavolodin** [comment]
@BYK Hmm... that adds a lot of unneeded complexity.

**Comment by BYK** [comment]
@ilyavolodin - that is complexity if we want that functionality. In all honesty, I'm in favor of turning this on and see if any issues arise and if we like the benefits. If we think it is not worth it, we can revert it. What do you think?

**Comment by nzakas** [comment]
@byk my concern is that we won't notice that there's a problem. Incorrectly invalidated caches are one of the hardest problems to identify and debug. 

> I never run tests on a "clean" slate anyways

This is exactly the problem. If we're not doing it, and then the CI environment isn't doing it, who is doing it? :)

At the moment, I'm :-1: on this suggestion. It seems like only a small benefit with a lot of potential complexity and a bunch of unknown unknowns.

**Comment by BYK** [comment]
Alright, not gonna force :)
