### ISSUE TITLE
Ignore node_modules and bower_component folders in subfolders

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5646]
**What version of ESLint are you using?**
2.4.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
Any
**What did you do? Please include the actual source code causing the issue.**
In this project, 
```
cd packages/eslint-config-eslint
npm install
cd ../..
eslint packages
```
**What did you expect to happen?**
eslint should ignore `packages/eslint-config-eslint/node_modules/*` and return no errors

**What actually happened? Please include the actual, raw output from ESLint.**
eslint did run inside `node_modules` and reports lots of errors.

**Comment by nzakas** [comment]
This isn't a bug, it's intentional. We only exclude the top-level `node_modules` and `bower_components` by default.

**Comment by alberto** [comment]
So, could it be an enhancement or did you already decide against this before?

**Comment by nzakas** [comment]
We decided against it before because we wanted to ignore as few directories as possible by default. See https://github.com/eslint/eslint/issues/1163#issuecomment-58378266

**Comment by alberto** [comment]
Thanks for the link. I tried searching for the conversation but I got a lot of results. Closing this, then.
