### ISSUE TITLE
AppVeyor build fails due to rate limit on PhantomJS downloads

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5666]
AppVeyor build has been failing a lot recently due BitBucket rate limiting downloads of PhantomJS binaries. It looks like this is a know issue and there's a ticket to track this here: https://github.com/ariya/phantomjs/issues/13953#issuecomment-200862297
It looks like solution to this problem should be coming in sometime in the future by switching from bitBucket to a CDN, but for now maybe we should use the workaround to have AppVeyor be a bit more happy? Adding env variables `PHANTOMJS_CDNURL=http://cnpmjs.org/downloads` should fix this issue.

**Comment by scriptdaemon** [comment]
Travis also failed a few times in my PR, so it's not just AppVeyor.

**Comment by ilyavolodin** [comment]
Travis fails rarely, AppVeyor fails every other build due to this issue. Not sure why. If we do this, we might as well do it for both.

**Comment by alberto** [comment]
Looks like travis doesn't like that CDN very much. See my PR for details.
