### ISSUE TITLE
Inconsistent option name: max vs. maximum

### ISSUE THREAD

**Issue by teppeis** [eslint/eslint#5685]
The new [max-statements-per-line](http://eslint.org/docs/rules/max-statements-per-line) has `max` option, but other existing rules (including `max-statements`) have `maximum`.

- http://eslint.org/docs/rules/max-statements
- http://eslint.org/docs/rules/max-depth
- http://eslint.org/docs/rules/max-nested-callbacks
- http://eslint.org/docs/rules/complexity
- http://eslint.org/docs/rules/max-params

Is this intentional?

**Comment by teppeis** [comment]
This is something weird for me...

```json
{
  "rules": {
    "max-statements": [2, {"maximum": 10}],
    "max-statements-per-line": [2, {"max": 1}]
  }
}
```

**Comment by mysticatea** [comment]
Thank you for this issue.

Yeah, I feel inconsistent, too.

@eslint/eslint-team May we add `maximum` option to `max-statements-per-line` rule and deprecate `max` option?

**Comment by kaicataldo** [comment]
I'm a fan of making this consistent, too 👍 This would technically be a breaking change though, so we'd have to make both options work for now, right? I can make this change when we've decided.

**Comment by scriptdaemon** [comment]
There are also other rules that use `max` to consider (e.g. `no-multiple-empty-lines` and `id-length`).

**Comment by ilyavolodin** [comment]
So 3 with `max` and 5 with `maximum`. Even though `maximum` appears in more places, I would rather have `max` as the default. `Max` is self-explanatory and less typing.

**Comment by kaicataldo** [comment]
Cool, sounds good. I can start working on this!

**Comment by ilyavolodin** [comment]
@kaicataldo Wait for @nzakas to accept it first. I'm pretty sure we want to fix this, but I don't know which way we are going to go.

**Comment by kaicataldo** [comment]
@ilyavolodin Was just editing my previous comment when I saw yours. Thanks, still learning the ropes :smile:

**Comment by nzakas** [comment]
Yeah, we should fix this for sure. Assuming we stick with `max` everywhere, that would mean that we'd need to:

1. Ensure rules that accept `maximum` also accept `max` (update the rule schema so it accepts both).
1. Change the rule docs to use `max` while adding a note that the option name `maximum` is deprecated and will be remove at some point in the future.

**Comment by kaicataldo** [comment]
Cool, I'll try to get to this this week then.

**Comment by vitorbal** [comment]
hey, @kaicataldo any chance you would be willing to share this issue? Would love to help out, it looks like a good starting point to get my feet wet with contributing :)

**Comment by kaicataldo** [comment]
@vitorbal Go for it, more contributors are always welcome!

**Comment by vitorbal** [comment]
Thanks! FYI: #5743
