### ISSUE TITLE
The default value of CLIEngine's `options.cwd` is decided when ESLint is loaded.

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#5694]
From https://github.com/mysticatea/eslint-plugin-node/issues/28

- [`getRelativePath` function of Atom's `linter-eslint` changes the current directory](https://github.com/AtomLinter/linter-eslint/blob/977fe57693e23b4bd664673496f4d6509518bbfb/src/worker-helpers.js#L103) and returns a relative path from the new current directory. And it executes linting of the file.
- At the time, `eslint.CLIEngine` uses the default value of `options.cwd`. It should be `process.cwd()`.
  But actually, [the default value of `options.cwd` had been decided when ESLint was loaded](https://github.com/eslint/eslint/blob/21bd44190d10d2655f28262e22cab4761de9a952/conf/cli-options.js#L32).

I think the default value of `options.cwd` should be decided in runtime.
  
----

**What version of ESLint are you using?**

- v2.0.0 - v2.5.1.

**What parser (default, Babel-ESLint, etc.) are you using?**

- default.

**Please show your full configuration:**

- https://github.com/mysticatea/cpx/blob/master/.eslintrc

**What did you do? Please include the actual source code causing the issue.**

- I linted [cpx.js](https://github.com/mysticatea/cpx/blob/master/src/lib/cpx.js) with using Atom's `linter-eslint`.

**What did you expect to happen?**

- No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

- I got false positive.
  ![image](https://cloud.githubusercontent.com/assets/1937871/14065902/e71f2ed2-f476-11e5-8f8f-129774595bc7.png)

**Comment by BYK** [comment]
LGTM
