### ISSUE TITLE
Cannot init, fresh install, Windows 10

### ISSUE THREAD

**Issue by smoltron** [eslint/eslint#5703]
I have a fresh global install of eslint in Windows 10.
From git bash:

```
$ eslint --init
Object #<Object> has no method 'resume'
$ which eslint
/c/Users/xxx/AppData/Roaming/npm/eslint
```

**What version of ESLint are you using?**
2.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Not applicable, cannot init

**Please show your full configuration:**
Not applicable, cannot init

**What did you do? Please include the actual source code causing the issue.**
eslint --init

**What did you expect to happen?**
.eslintrc created

**What actually happened? Please include the actual, raw output from ESLint.**
crash

**Comment by nzakas** [comment]
Please try upgrading to 2.5.3.

**Comment by smoltron** [comment]
No effect:
```
$ eslint --version
v2.5.3
$ eslint --init
Object #<Object> has no method 'resume'
```

**Comment by nzakas** [comment]
Hmm, that's strange. What version of Node.js are you using? And is there a stack trace output when you see this? If so, can you please include the full stack trace here.

**Comment by ilyavolodin** [comment]
I verified that on my local machine everything is working correctly, with Windows 10, Node 4, NPM 2

**Comment by smoltron** [comment]
Sorry, this was my fault. There was an old node version in the portion of my path that was used only by Git Bash. Somehow Git Bash has appended /Users/USER/bin to the path. This is not in my environment and other programs do not see it. The bin directory contained this old node, which I had forgotten.
I am sorry about the extra work.

**Comment by ilyavolodin** [comment]
Looks like this issue is resolved. Closing.
