### ISSUE TITLE
node_modules is not ignored

### ISSUE THREAD

**Issue by web2style** [eslint/eslint#5707]
**What version of ESLint are you using?**

`"eslint": "^2.5.1"`

**What parser (default, Babel-ESLint, etc.) are you using?**

`"babel-eslint": "^6.0.0"`

**Please show your full configuration:**

```
{
  "parser"  : "babel-eslint",
  "env"     : {
    "browser" : true
  },
  "globals" : {
    "__DEV__"      : false,
    "__PROD__"     : false,
    "__DEBUG__"    : false,
    "__DEBUG_NEW_WINDOW__" : false,
    "__BASENAME__" : false
  },
  "rules": {
    "semi": [2, "always", {"omitLastInOneLineBlock": true}],
    "comma-dangle": [2, "always-multiline"],
    "jsx-quotes": [2, "prefer-double"],
    "space-before-function-paren": [2, "never"],
    "block-spacing": [2, "never"]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

Run `eslint . ./`.

**What did you expect to happen?**

Ignore `node_modules` and lint files in other directories.

**What actually happened? Please include the actual, raw output from ESLint.**

It doesn't ignore `node_modules` and throws the following errors for every .js file in my project:

```
  1:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  1:1  error  Rule 'space-before-keywords' was removed and replaced by: keyword-spacing    space-before-keywords
  1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
```

I don't have such rules anywhere except `node_modules`. Checked with "Find text in files" in Total Commander to make sure.

**Comment by nzakas** [comment]
Can you try upgrading to 2.5.3?

**Comment by nzakas** [comment]
@IanVS maybe related to #5547?

**Comment by IanVS** [comment]
Maybe, but it doesn't seem like he's using `--no-ignore`.  I'm thinking it's more related to the `eslint . ./` command.  

@web2style Can you try `eslint .` instead?  Is there a reason you are using that syntax?  Were you successfully using that command previously? 

I'll have to take a closer look at this later tonight to try and figure out what it's actually doing.

**Comment by web2style** [comment]
Thank you, @nzakas. Upgrading to 2.5.3 solved the issue.
