### ISSUE TITLE
Inside a switch statement, newline-before-return conflicts with lines-around-comment

### ISSUE THREAD

**Issue by scottohara** [eslint/eslint#5718]
#### Background info
`lines-around-comment: ["error", {beforeLineComment: true, allowBlockStart: true}]` requires a blank line before any single-line comments, *except* where the comment is the first line of the block:

```
{
  // This comment is OK (not preceded by a newline, but first in block)

  // This comment is also OK (preceded by a newline)
  let a = 1;
  // This comment is NOT OK (not preceded by a newline)
}
```

`newline-before-return: "error"` requires a blank line before any return statements, *except* where the return is the only statement in a statement group.

```
function foo() {
  return 1;   // OK, return is the only statement
}

function bar() {
  const a = 1;

  return a;  // OK, return is preceded by a newline
}

function baz() {
  const a = 1;
  return a;   // NOT OK, return is not preceded by a new line
}
```

#### Problem
Inside a `SwitchCase`, there doesn't seem to be a way to get both of these rules to play nicely with each other.  The problem appears to be that `SwitchCase` is considered by `newline-before-return` to be a "statement group", yet it is not a block.

Because `SwitchCase` is not a block, `allowBlockStart` doesn't come into play, so `lines-around-comment` will expect a newline before all comments (including the first comment in each `SwitchCase`).

However `newline-before-return` will complain about this newline before a comment if the only statement in the `SwitchCase` is a return.

See examples below.

**What version of ESLint are you using?**
2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

```
/* eslint
     newline-before-return: 2
     lines-around-comment: [2, {beforeLineComment: true, allowBlockStart: true}]
*/
```

**What did you do? Please include the actual source code causing the issue.**
(for each of these examples, refer to the corresponding output below.  Only code in the default `SwitchCase` differs between each example.)
#### Example 1
```
function test(value) {
	switch (value) {
		case "foo":

			// do something (newline above required by lines-around-comment)
			break;

		case "bar":

			// do something else (newline above required by lines-around-comment)
			break;

		default:

			// bail out (newline above required by lines-around-comment)
			return -1;
	}

	// do some more stuff (newline above required by lines-around-comment)
	return 1;
}

test("foo");
```

#### Example 2
```
function test(value) {
	switch (value) {
		case "foo":

			// do something (newline above required by lines-around-comment)
			break;

		case "bar":

			// do something else (newline above required by lines-around-comment)
			break;

		default:
			// bail out (newline above prevented by newline-before-return)
			return -1;
	}

	// do some more stuff (newline above required by lines-around-comment)
	return 1;
}

test("foo");
```

#### Example 3
```
function test(value) {
	switch (value) {
		case "foo":

			// do something (newline above required by lines-around-comment)
			break;

		case "bar":

			// do something else (newline above required by lines-around-comment)
			break;

		default:
			return -1;
	}

	// do some more stuff (newline above required by lines-around-comment)
	return 1;
}

test("foo");
```
**What actually happened? Please include the actual, raw output from ESLint.**
#### Example 1
In the first example, `newline-before-return` complains about an unexpected newline in the default `SwitchCase`. This is because the return is the only statement in the group:

```
$ eslint foo.js

foo.js
  20:4  error  Unexpected newline before return statement  newline-before-return

✖ 1 problem (1 error, 0 warnings)
```

#### Example 2
In the second example, taking out the unexpected newline fixes the `newline-before-return` error; but triggers a `lines-around-comment` error instead.  This is because a `SwitchCase` is not a block, so `allowBlockStart` doesn't come into play:

```
$ eslint foo.js

/Users/scotto/GitHub/loot/foo.js
  18:4  error  Expected line before comment  lines-around-comment

✖ 1 problem (1 error, 0 warnings)
```

#### Example 3
The only way to get it to work is to remove the comment entirely. With no comment at all in the `SwitchCase`, the code passes.

**What did you expect to happen?**
I think the `allowBlockStart: true` option of `lines-around-comment` should also work for `SwitchCase`  OR there should be a new options such as `allowSwitchCase(Start|End)` to support this.

This would allow the above code to be written as:

```
/* eslint
     newline-before-return: 2
     lines-around-comment: [2, {beforeLineComment: true, allowSwitchCaseStart: true}]
*/
function test(value) {
	switch (value) {
		case "foo":
			// do something
			break;

		case "bar":
			// do something else
			break;

		default:
			// bail out
			return -1;
	}

	// do some more stuff (newline above required by lines-around-comment)
	return 1;
}

test("foo");
```

**Comment by scottohara** [comment]
A workaround is to move the comments to above the case labels, eg.

```
function test(value) {
    switch (value) {
        // do something (this is OK here, because allowBlockStart)
        case "foo":
            break;

        // do something else (newline above)
        case "bar":
            break;

        // bail out (newline above)
        default:
            return -1;
    }

    // do some more stuff (newline above)
    return 1;
}

test("foo");
```

**Comment by btmills** [comment]
Wow, thank you for the thorough report @scottohara!

> I think the `allowBlockStart: true` option of `lines-around-comment` should also work for `SwitchCase` OR there should be a new options such as `allowSwitchCase(Start|End)` to support this.

I agree with your first option because I think that a `case`, while not technically a `BlockStatement`, can be treated like one for the purposes of `allowBlockStart`. @eslint/eslint-team what do you think?

**Comment by platinumazure** [comment]
Since we already seem to do this in padded-blocks, I would be okay with it in this rule.

**Comment by nzakas** [comment]
Sounds good to me.

@scottohara do you want to submit a PR?

**Comment by scottohara** [comment]
Will do.  Might take a day or two to find some time, but I can certainly take this on.
