### ISSUE TITLE
eslintignore ! not working.  (exclude)

### ISSUE THREAD

**Issue by rstudner** [eslint/eslint#5728]
Using eslint 2.5.1

my .eslintignore file is:
```
node_modules
app/assets/javascripts
!app/assets/javascripts/pickAnyFolder
```

This doesn't work.  It ignores pickAnyFolder.  I can't seem to use the ! syntax at all with 'conflicting rules'.

Is this a known issue (I can't seem to find it)

so I have to do:
```
node_modules
app/assets/javascripts/folder1
...
app/assets/javascripts/foldern
```

basically... and then just not include a specific directory in the ignore.  Pain!

**Comment by ilyavolodin** [comment]
@rstudner v2.5.1 had some known issues with npm bundling, could you try this same thing with v2.5.3 please?

**Comment by rstudner** [comment]
Didn't make any positive difference.  The ! appears to not be working.

BTW, I'll try from the command line -- i'm currently using RubyMine to 'visualize' the results and possibly this is affecting things

(though again, if I don't try to rely on !, everything works 100%)

**Comment by alberto** [comment]
You can't unignore something in an ignored folder.

Instead, you can do
```
app/assets/javascripts/**
!app/assets/javascripts/pickAnyFolder
```

**Comment by rstudner** [comment]
alberto - I tried that syntax as well, has no different effect for me at least

**Comment by rstudner** [comment]
```
node_modules
app/assets/javascripts/**
!app/assets/javascripts/visibility_dashboard
spec
```

It won't run on any files under visibility_dashboard with the above.

**Comment by alberto** [comment]
Confirmed on 2.5.3

**Comment by alberto** [comment]
I'll have a look at this

**Comment by IanVS** [comment]
I think the double globstar (`**`) is not what you want here.  Instead, it should be:

```
app/assets/javascripts/*
!app/assets/javascripts/pickAnyFolder
```

With that syntax, everything works as expected when I test (meaning, everything is ignored except for `pickAnyFolder`).

**Comment by rstudner** [comment]
I believe a "great odin's raven" works out nicely here.

That works for me as well thanks :)

Now, the key, is that how it is *supposed* to work hah.

**Comment by IanVS** [comment]
Yes, our `.eslintignore` file is supposed to work the same way as a `.gitignore` file.  And using a trailing `**` doesn't work in a `.gitignore` file either.

**Comment by alberto** [comment]
@IanVS According to the [git docs](https://git-scm.com/docs/gitignore) it should, but I tested on my machine (git 2.6.2) and it didn't work either. Maybe the docs are wrong?

**Comment by zirho** [comment]
To exclude nested folder, something like this works.

public/js/*
!public/js/webpack
public/js/webpack/*
!public/js/webpack/src
