### ISSUE TITLE
Change order in `eslint --init` environment options 

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5742]
This is a minor thing, but I think it's worth fixing anyways. :)

When running `eslint --init`, the question about environment shows `browser` option as selected by default, but I think it is a bit confusing that it is not the first option of the list (which is the one that gets the focus).
![eslint-init-enviroment](https://cloud.githubusercontent.com/assets/72561/14167058/d9f77cec-f718-11e5-8919-9e367c9a5b61.png)

**Comment by alberto** [comment]
If I label it as a (usability) bug, can I sneak this in? 😇

**Comment by platinumazure** [comment]
I can get behind this. As it is, it's not clear whether pushing enter would preserve the selected choice (Browser), or change your choice and select that (Node). By moving Browser up, that ambiguity is removed.

**Comment by nzakas** [comment]
Go for it
