### ISSUE TITLE
performance: improve config caching

### ISSUE THREAD

**Issue by isaacl** [eslint/eslint#5748]
**What version of ESLint are you using?**
2.53.

Eslint currently caches config for each src directory, which leads to lots of redundant config parsing. This is the most expensive step on our repository when --cache is active since airbnb config takes ~50ms to parse.

One alternative would be to split out the logic for determining config files from the actual loading of them, cache this for a given directory, and separately cache the config result from a given list of the input files.

**Comment by gyandeeps** [comment]
@eslint/eslint-team thoughts on this?
CC @royriojas

**Comment by royriojas** [comment]
@isaacl not sure I get the issue is the performance better without the `--cache` flag? can you provide a reduced test case of what you're describing? Are you using different configs per directory?

**Comment by nzakas** [comment]
> Eslint currently caches config for each src directory, which leads to lots of redundant config parsing. This is the most expensive step on our repository when --cache is active since airbnb config takes ~50ms to parse.

@isaacl can you provide some data showing this?

**Comment by IanVS** [comment]
It's been two months since the last activity here.  I think we can close for now, and re-open if more information is provided.
