### ISSUE TITLE
Bad link to "Code Path Analysis" page

### ISSUE THREAD

**Issue by ehom** [eslint/eslint#5777]
This page contains the bad link:
http://eslint.org/docs/developer-guide/working-with-rules#accessing-code-paths

"details here" text is currently linked to:
http://eslint.org/docs/developer-guide/code-path-analysis

It was just missing the ".html"
http://eslint.org/docs/developer-guide/code-path-analysis.html

Very good documentation. Thank you.

====

**Comment by kaicataldo** [comment]
Hey there, thanks for the issue. We have a fix in the pipeline, so this should no longer be an issue very soon!

Issue here: https://github.com/eslint/eslint.github.io/pull/232

**Comment by kaicataldo** [comment]
I'm actually going to close this and move the issue over to the website repo. Thanks again.

**Comment by kaicataldo** [comment]
Issue opened here, if you're interested: https://github.com/eslint/eslint.github.io/issues/233

**Comment by ehom** [comment]
Oh, Okay.

Thanks!

Erwin
