### ISSUE TITLE
The `no-magic-numbers` rule should ignore indexOf === -1 

### ISSUE THREAD

**Issue by d4rkr00t** [eslint/eslint#5783]
**What version are you using?**
`2.6.0`

**What did you do?**
```js
/*eslint no-magic-numbers: ["error"]*/

var data = ['foo', 'bar', 'baz'];
var key = 'bar';
var hasKey = data.indexOf(key) !== -1;
```

**What happened?**
`error  No magic number: -1 no-magic-numbers`

**What did you expect to happen?**
Consider `indexOf(something) === -1;` as ok, because it's a common pattern for checking whether `something` is in array.

**Comment by ilyavolodin** [comment]
Is there a reason why you don't want to whitelist -1:

```js
no-magic-numbers: ["error", { "ignore": [-1, 0, 1] }]
```

**Comment by d4rkr00t** [comment]
Yes, because then, in any other case -1 will be considered as ok. But I want it only for indexOf.

**Comment by d4rkr00t** [comment]
Here is a pull request https://github.com/eslint/eslint/pull/5784 you can take a look at.

**Comment by lo1tuma** [comment]
I don’t think a commonly used pattern makes the number less magic. The meaning of this number is still implicit.

**Comment by ilyavolodin** [comment]
I agree with @lo1tuma on this. I think the best bet is to either whitelist `-1`, or better yet, whitelist `0` as it is self-explanatory and use:
```js
data.indexOf(key) >= 0;
```

**Comment by d4rkr00t** [comment]
`-1` is documented output for the indexOf method which makes it less magic. At least, you can read documentation and find out what `-1` means.

But may be you're right and I should try to whitelist `[-1, 0, 1]` because it will help with another issue with sort method :).

Closing this.

**Comment by michaelficarra** [comment]
@d4rkr00t Instead of whitelisting `-1` everywhere, you might want to define a constant `const INDEXOF_NOT_FOUND = -1;` and compare against that.

**Comment by d4rkr00t** [comment]
Hi @michaelficarra , thanks, but I added ```[-1, 0, 1]``` to whitelist and this's works fine for me.
