### ISSUE TITLE
Gratuitous parentheses in arrow function with object reference

### ISSUE THREAD

**Issue by tuhoojabotti** [eslint/eslint#5789]
**What version of ESLint are you using?** 2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
```js
  "eslintConfig": {
    "extends": "eslint:recommended",
    "parserOptions": { "ecmaVersion": 6 },
    "env": {
      "node": true,
      "es6": true
    },
    "rules": {
      "no-extra-parens": 2
    }
  }
```

**What did you do? Please include the actual source code causing the issue.**
`let test = a => ({ a: 1, b: 2, c: 3 }[a]);`

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
Gratuitous parentheses around expression (no-extra-parens)

**Comment by tuhoojabotti** [comment]
Similar to #2702

**Comment by platinumazure** [comment]
Confirmed in online demo. Seems like a bug.

As I mentioned in the other issue, I think the special check for `ObjectExpression` needs to be expanded to also check `MemberExpression` with its `object` node having a type of `ObjectExpression`.

**Comment by btmills** [comment]
`() => ({}.a.b)` would be two nested `MemberExpressions`, so we'd have to do some sort of recursion. Would it be better, instead of checking node types that we know begin with `{`, to just check for a `{` token immediately following the `(`? Checking tokens seems like it might be a more direct solution.

**Comment by platinumazure** [comment]
@btmills True- this is a tokenizing problem rather than a parsing problem.
Checking the token makes sense.

**Comment by michaelficarra** [comment]
See [my comment](https://github.com/eslint/eslint/issues/2702#issuecomment-109335937) in #2702. That's still correct. The first token of the expression must not be `{` or `function`. #2772 was not at all the proper fix.

**Comment by alberto** [comment]
@michaelficarra can you provide an example with an incorrect use of `function` within the arrow expression?

**Comment by michaelficarra** [comment]
@alberto I misspoke. It is just `{`. See https://tc39.github.io/ecma262/#prod-ConciseBody.

**Comment by btmills** [comment]
Working on this
