### ISSUE TITLE
Global vs Local version mismatch message

### ISSUE THREAD

**Issue by adamweeks** [eslint/eslint#5794]
**What version are you using?**
v2.7.0

**Request**
When running eslint on a project that contains a local version of eslint, if the global version does not match, print a status message that the versions mismatch. This is similar to the gulp version mismatch message when running gulp:

> [17:15:23] Warning: gulp version mismatch:
> [17:15:23] Global gulp is 3.9.1
> [17:15:23] Local gulp is 3.8.6

This would be a good "workaround" for #3993

**Comment by kentcdodds** [comment]
May consider doing the same for plugins as well

**Comment by platinumazure** [comment]
How would you propose to do this, exactly?

**Comment by adamweeks** [comment]
This is how gulp handles it. https://github.com/gulpjs/gulp/blob/098e1825469ecb0b72c74e81db600678b625fea0/bin/gulp.js#L99

If this seems worthwhile, I don't mind looking into and creating a PR. Didn't want to work on it if it was out of scope.

**Comment by nzakas** [comment]
I'm generally not a fan of dirtying the output of ESLint, especially when people rely on the output in CLI and other tools, as it's hard to know what people might be depending on.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
