### ISSUE TITLE
Glob arg behaves differently if ran from npm script

### ISSUE THREAD

**Issue by filipesilva** [eslint/eslint#5796]
**What version of ESLint are you using?**
2.6.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```js
{
    "rules": {
        "semi": [
            2,
            "always"
        ]
    }
}
```
**What did you do? Please include the actual source code causing the issue.**
```sh
filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ eslint -v
v2.6.0

filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ ls -la
total 15
drwxr-xr-x 1 filipe.silva filipe.silva  0 Apr  6 00:18 ./
drwxr-xr-x 1 filipe.silva filipe.silva  0 Apr  4 12:36 ../
-rw-r--r-- 1 filipe.silva filipe.silva 89 Apr  4 12:37 .eslintrc.json
-rw-r--r-- 1 filipe.silva filipe.silva 61 Apr  6 00:18 package.json
-rw-r--r-- 1 filipe.silva filipe.silva 11 Apr  4 12:38 test.js

filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ cat .eslintrc.json
{
    "rules": {
        "semi": [
            2,
            "always"
        ]
    }
}

filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ cat package.json
{
  "scripts": {
    "lint": "eslint './**/*.js'"
  }
}

filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ cat test.js
var a = 1

filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ eslint './**/*.js'

E:\sandbox\eslint-test\test.js
  1:10  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)


filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ npm run lint

> @ lint E:\sandbox\eslint-test
> eslint './**/*.js'


filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$
```
**What did you expect to happen?**
I expected eslint to show the same result when running directly or from an npm script while using a glob pattern enclosed in single quotation marks.
**What actually happened? Please include the actual, raw output from ESLint.**
eslint did not detect the missing semicolon when ran from the npm script. However, I also tried `eslint .` directly and from the npm script, and both worked gave the expected result.

I suspect there might be an issue with path resolution when using globs, perhaps it's being resolved relative to script bin instead of the directly from where it was called.

**Comment by gyandeeps** [comment]
Can you try it by not using `'` around the glob pattern.
Something like this
```js
{
  "scripts": {
    "lint": "eslint ./**/*.js"
  }
}
```

Also in your case you can simple say `eslint .`

**Comment by ilyavolodin** [comment]
@gyandeeps globs behave differently when quoted, see https://github.com/eslint/eslint/issues/5780#issuecomment-205891984 for discussion

**Comment by gyandeeps** [comment]
ah gotcha.

**Comment by filipesilva** [comment]
@gyandeeps I did try with `eslint .` and can confirm it works correctly via CLI and via npm script. I think the issue is specific to globs, which are necessary for some more complicated patterns.

**Comment by alberto** [comment]
I can't reproduce this on a mac. Can you also try with `**/*.js`?

**Comment by filipesilva** [comment]
Trying with `'**/*.js'` gives me the same result:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ npm run lint

> @ lint E:\sandbox\eslint-test
> eslint '**/*.js'


filipe.silva@DESKTOP-7ND6T3R MINGW64 /e/sandbox/eslint-test
$ eslint '**/*.js'

E:\sandbox\eslint-test\test.js
  1:10  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```

**Comment by filipesilva** [comment]
I don't know if this helps, but on other projects when we usually have trouble with paths on windows only, the culprit seems to be usage of `process.end.PWD` which exists on mac/linux, but not on windows.

http://stackoverflow.com/questions/30991319/whats-the-difference-between-process-cwd-vs-process-env-pwd

**Comment by filipesilva** [comment]
I was also having a very similar issue with `tslint`, and after some debugging it seems `glob` itself isn't returning the expected files: https://github.com/palantir/tslint/issues/1091#issuecomment-206094290

**Comment by filipesilva** [comment]
I reproduced this issue on the `glob` repo, with a simpler example: https://github.com/isaacs/node-glob/issues/257

**Comment by alberto** [comment]
Thanks @filipesilva. Keep us updated.

**Comment by filipesilva** [comment]
Will do, thanks for all the help so far!

**Comment by mysticatea** [comment]
As far as I know, `cmd.exe` does not strip single quotes, and npm-scripts are executed by `cmd.exe` on Windows.

```
$ cmd
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

> echo console.log(process.argv[2]) > test.js
> node test.js 'foo'
'foo'
> exit
$ node test.js 'foo'
foo
```

**Comment by mysticatea** [comment]
So I think we have to strip single quotes before we give it to glob.

**Comment by mysticatea** [comment]
A side note: `cmd.exe` does not concatenate args in single quotes.

```
> cat test.js
console.log(process.argv[2])

> node test.js "foo bar"
foo bar
> node test.js 'foo bar'
'foo
```

**Comment by filipesilva** [comment]
@mysticatea that's it! I tested using the example in https://github.com/isaacs/node-glob/issues/257, and got the intended behavior.

I added ```console.log(`------${process.argv[2]}------`);``` and this is what I got with single quotes:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/glob-test
$ npm run glob

> @ glob E:\sandbox\glob-test
> glob-cli-test '**/*.ts'

------'**/*.ts'------
[]

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/glob-test
$ ./node_modules/.bin/glob-cli-test '**/*.ts'
------**/*.ts------
[ 'file.ts' ]
```

And here is with double quotes:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/glob-test
$ npm run glob

> @ glob E:\sandbox\glob-test
> glob-cli-test "**/*.ts"

------**/*.ts------
[ 'file.ts' ]

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/glob-test
$ ./node_modules/.bin/glob-cli-test "**/*.ts"
------**/*.ts------
[ 'file.ts' ]
```

So yeah. In windows it seems args in npm scripts have to use double quotes instead of single quotes, both because of their conversion to strings and because of the concatenation issue you highlighted.

**Comment by alberto** [comment]
Thanks @mysticatea @filipesilva. We should update the docs then. I think it is safe to recommend using double quotes also in unix for better compatibility, since [the only difference](http://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html) is with a few special characters.

**Comment by HouCoder** [comment]
I had the same problem on my mac, and I fixed this problem by double quoting the argument.
