### ISSUE TITLE
New rule proposal—no-arrow-class-methods

### ISSUE THREAD

**Issue by calebmer** [eslint/eslint#5812]
In ES7 you can use the [class fields and static properties](https://github.com/jeffmo/es-class-fields-and-static-properties) feature to do the following:

```js
class Hello {
  world = () => console.log('world')
}
```

This can be a convenient pattern, however it has some downsides. To see such downsides clearly, refer to how babel transforms this code (to ES6):

```js
class Hello {
  constructor() {
    this.world = () => console.log('world');
  }
}
```

Note that a new function is being created every time the `Hello` class is constructed. This can have performance drawbacks when compared to the more general pattern of setting the prototype of a method.

This brings me to my new rule proposal, `no-arrow-class-methods`, this rule would warn when a developer used arrow functions with a class properties.

One caveat to note of this rule is that React developers often use this pattern of arrow functions with class properties as it allows them to use `this` without having to bind the method when passing a method around as a prop. Whether this is a feature of the spec or a side effect of Babel's compilation process is unclear to me. In the spirit of eslint's framework agnosticism this should not be a problem, but it is still worth noting.

**Comment by alberto** [comment]
Sorry, but we don't support experimental features.

**Comment by adamterlson** [comment]
> This can have performance drawbacks when compared to the more general pattern of setting the prototype of a method.

By this logic, you should also not allow any assignment in the constructor either:

```
// Disallowed
class Hello {
    constructor() {
        this.world = function () { console.log('world'); };
    }
}
````
Also, this shouldn't be allowed either:
````
// Disallowed
class Hello {
    constructor() {
        this.world = this.world.bind(this);
    }
    world() {
        console.log('world');
    }
}
````

I am very curious to hear what your use case is that this microoptimization has meaningful performance implications.
