### ISSUE TITLE
newline-before-return throws exception if `return` is first token in file

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#5816]
**What version of ESLint are you using?**

2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

(Note: This is a config based off of the shell command I wrote below.)

```json
{
    "env": {
        "node": true
    },
    "rules": {
        "newline-before-return": 2
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```shell
$ echo "return;" | eslint --stdin --env node --no-eslintrc --rule "newline-before-return: 2"
```

**What did you expect to happen?**

No error (newline-before-return is written to detect that the statement is the first statement in its block and will forbid newlines in that case).

**What actually happened? Please include the actual, raw output from ESLint.**

```shell
Cannot read property 'loc' of undefined
TypeError: Cannot read property 'loc' of undefined
    at hasNewlineBefore (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\rules\newline-before-return.js:105:45)
    at EventEmitter.ReturnStatement (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\rules\newline-before-return.js:134:38)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:609:23)
    at CommentEventGenerator.enterNode (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\util\comment-event-generator.js:99:23)
    at Controller.traverser.traverse.enter (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:887:36)
    at Controller.__execute (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\kpartington\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:501:28)
```

---

The issue appears to be that in `hasNewlineBefore()` method, there is no defensive check around the existence of a token before the return statement. Presumably if there is no token before, then the "line number of the previous token" should be 1 (in a 1-based index).

**Comment by gyandeeps** [comment]
Seems like a bug in `espree` as this is invalid code. It should throw parsing error.
Just tried it on https://astexplorer.net/

**Comment by platinumazure** [comment]
@gyandeeps Not true-- global return is allowed in Node modules and in some other contexts. `espree` has a globalReturn option which the `node` env enables. astexplorer must not be equipped to handle that.

**Comment by gyandeeps** [comment]
k. thanks for explaining

**Comment by platinumazure** [comment]
I'm willing to fix this if the issue is accepted.

**Comment by kaicataldo** [comment]
I wrote this rule and didn't consider this possibility. For my own edification, mind sharing what some example cases of global returns are? Thanks!

If it is only valid in a Node environment, maybe we can only use the suggested fix when the `node` environment option is turned on?

**Comment by platinumazure** [comment]
@kaicataldo The problem is that the rule throws an exception, which causes the linting process to terminate. This means other rules cannot function. Surely we can agree that that is something worth avoiding at all costs?

This happens because the rule code simply assumes there will always be a token before `return`. That's not always true. I don't see why the rule needs to be aware of whether it's in a Node environment or not-- it just needs to know that there might not always be a previous token.

What triggers this possibility is actually `{ parserOptions: { ecmaFeatures: { globalReturn: true } } }`. This is automatically enabled by the node environment, but it's not the only way it can be turned on.

**Comment by kaicataldo** [comment]
Yes, of course it should be fixed - just trying to fully understand the issue at hand. Just for my own education, mind sharing an example or two where this is valid code? Not questioning that it is, but want to understand fully and learn from my mistake :)

**Comment by platinumazure** [comment]
@kaicataldo Please feel free to look at at PR #5818. I didn't make any sweeping changes and all the other test cases should still work as they had been.

As for a valid example, well... I accidentally found this when trying to run ESLint on a Node.JS repository where some test files had literally been prevented from executing by adding a `return;` statement at the beginning of the file. So something like this...

```js
/* File header comments */

// Can't run these tests now due to some issue
return;

describe("some description", function () {
    // tests
});
```

**Comment by kaicataldo** [comment]
Got it - thanks for the explanation, @platinumazure! Totally agree that this needs to be fixed :+1:

**Comment by kaicataldo** [comment]
Was able to reproduce locally.
