### ISSUE TITLE
ESLint -> Lint

### ISSUE THREAD

**Issue by ianlovell** [eslint/eslint#5828]
Is there any reason this project can't be generalised to lint all file types? e.g. SCSS/CSS, .NET files, package files etc? Is this something that's been considered?

**Comment by ilyavolodin** [comment]
This project heavily relies on AST for JavaScript - ESTree. And depends on a lot of tools that are very specific to ESTree (estravers, escope, etc). As such, it would never work for other file types. Now the core could possibly be generalized and made reusable. But then it would be a different project all together.

**Comment by alberto** [comment]
Closing since the question has been answered
