### ISSUE TITLE
--fix doesn't appear to completely indent

### ISSUE THREAD

**Issue by skarfacegc** [eslint/eslint#5847]
**What version of ESLint are you using?**
v2.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
`
{
  "extends": "google"
}
`
**What did you do? Please include the actual source code causing the issue.**
`node_modules/.bin/eslint --fix foo.js`

**What did you expect to happen?**
re-indent foo.js from 4 spaces to 2 spaces

**What actually happened? Please include the actual, raw output from ESLint.**

Original file
```
var foo = function () {
    if(true){
        console.log('true');
        if(1===1){
            console.log('really true')
        }
        else {
            console.log('you broke math');
        }
    } else {
        console.log('you broke booleans');
    }
}
```

After 1 run  (some indentation happened)  no warnings about 4 spaces

```
var foo = function() {
  if (true) {
      console.log('true');
      if (1 === 1) {
          console.log('really true');
        }
      else {
          console.log('you broke math');
        }
    } else {
      console.log('you broke booleans');
    }
};
```

after 2 runs
```
var foo = function() {
  if (true) {
    console.log('true');
    if (1 === 1) {
        console.log('really true');
      }
    else {
        console.log('you broke math');
      }
  } else {
    console.log('you broke booleans');
  }
};
```

after 3 runs (everything seems to be correctly indented)

```

var foo = function() {
  if (true) {
    console.log('true');
    if (1 === 1) {
      console.log('really true');
    }
    else {
      console.log('you broke math');
    }
  } else {
    console.log('you broke booleans');
  }
};
```

Same set of warnings on each run
```
foo.js
  1:5   error  'foo' is defined but never used                                               no-unused-vars
  2:3   error  Unexpected constant condition                                                 no-constant-condition
  4:5   error  Unexpected constant condition                                                 no-constant-condition
  4:9   error  Comparing to itself is potentially pointless                                  no-self-compare
  7:10  error  Closing curly brace does not appear on the same line as the subsequent block  brace-style

✖ 5 problems (5 errors, 0 warnings)
```

**Comment by ilyavolodin** [comment]
I think this might be a known issue. Indent rule works by offsets from the previous lines, so on the first run it fixes issue with first level indentation, on the second it finds and fixes second level indentations, etc. @gyandeeps @BYK could you confirm and close if we already have a duplicate for this issue?

**Comment by skarfacegc** [comment]
Is this related to #5329 ?  I wasn't entirely sure.

**Comment by skarfacegc** [comment]
It never notified me of spacing issues at all.  Just the 5 errors above repeated.  So it fixed one level, but failed to warn on the others that were out of spec.

**Comment by ilyavolodin** [comment]
@skarfacegc ESLint doesn't warn you about issues that it fixed (or thinks that it fixed), if you run ESLint without `--fix` flag, it should give you full report.

**Comment by skarfacegc** [comment]
It does, but eslint isn't fixing the issue or giving me any way to tell when --fix has fixed it after multiple runs.

**Comment by BYK** [comment]
Hey, sorry for coming to the discussion late. @ilyavolodin is right in his first comment. Since the current implementation uses relative offsets, it can mess up when auto fixing.

I did make some progress about the rewrite but having a hard time setting aside dedicated time for that.

**Comment by kaicataldo** [comment]
Closing this because we haven't made any progress in months. Thanks for contributing!
