### ISSUE TITLE
Use .gitignore by default if no .eslintignore is found

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#5848]
This is a proposal intended to reduce the friction for the adoption of eslint into a project.  Most times, files which are not version controlled are also not linted (`node_modules` being a common example, but also compiled code and dynamically generated files as well).  Currently, every project must either create an `.eslintignore` file to specify those files, or if they are using a `.gitignore`, they can add a command line flag like `--ignore-pattern .gitignore`.  But in both cases they must take an action to prevent non-controlled files from being linted.

In the [Gitter chat room earlier today](https://gitter.im/eslint/eslint?at=570e58d25cd40114649ae8b5), @gabmontes suggested that we could default to using a `.gitignore` file if no `.eslintignore` file is found (and of course no `--ignore-path` or `--ignore-pattern` was provided).  

I believe this is a sane default.  It is easily overridden, but will be sufficient for the vast majority of users.  It will help avoid config file clutter, and lower the learning curve for getting started with ESLint.  

I'd be willing to implement this if it is accepted, although I'm guessing this could be seen as a breaking change and may need be held until a major version bump.

**Comment by nzakas** [comment]
I'm not sure this is a good idea. In general, I think it's a bad practice to unexpectedly use files that aren't earmarked for ESLint use. In this case specifically, we can't anticipate the problems if we start reading `.gitignore` by default when `.eslintignore` isn't there. To me, it violates the principle of least surprise ("why would a change to .gitignore affect ESLint???").

You can already pass `.gitignore` on the command line using `--ignore-path`, so I don't see a clear win as compared to the considerable confusion this would seem to introduce.

**Comment by zxqfox** [comment]
@nzakas Guess, In common cases for usual project we need to lint source code before committing. And in most cases I'm agree with @gabmontes because `.gitignore` is a super set of `.anylinterignore`.

But yeah, it's not so clean as could be. Maybe `--verbose`/`-v` flag could help with that.

**Comment by nzakas** [comment]
@zxqfox we made `--ignore-path .gitignore` work correctly so that people had the option to use their `.gitignore` file for this purpose. I think that's the correct recommendation for solving this problem rather than changing the default behavior.

**Comment by alberto** [comment]
Also adding a `.eslintignore` file would make a sudden behaviour change.

**Comment by zxqfox** [comment]
Ah, forget about tricky solution: symlinking .eslintignore to .gitignore usually works just fine.

**Comment by mudetroit** [comment]
I think the question is whether the behavior would be desirable to a new user or not. The reason I say that is that the experienced user will know about the behavior and isn't likely to be surprised by it.

As pointed out be @gabmontes,  and referenced by @IanVS, generally speaking the items mentioned in a .gitignore will be files that you will rarely, if ever want linted. I will admit I fall in the camp that thinks a tool should start working without any configuration.I think as long as you output that you were using it in the header.

Where you currently print
```
> client@0.0.1 lint /some/path                                             
> eslint "./"
```
you instead output
```
> client@0.0.1 lint /some/path                                             
> eslint "./"
> Using .gitignore to define ignored files
```

This shouldn't trip up things parsing the output, unless they are really poorly written, Clues in the user what you are doing. And gets them started with as little work as possible.

**Comment by nzakas** [comment]
I'm sorry, I don't believe invisible defaults make sense and I'm very much against unnecessary extra console output because it has the potential to break tooling that relies on a particular format (for JSON, for example, it would be really bad).

Given that there's already a way to use gitignore if you really want to, we aren't going to move forward with this. Thanks for the discussion, everyone.

**Comment by IanVS** [comment]
Sounds good, thanks for talking it out.
