### ISSUE TITLE
Would you accept an autofix for comma-dangle?

### ISSUE THREAD

**Issue by adriantoine** [eslint/eslint#5854]
Hi,

Sorry I'm not following the issue template but I'm not really reporting an issue, it's more a question related to https://github.com/eslint/eslint/issues/5131.

I have made a change to allow `comma-dangle` to be fixable: https://github.com/adriantoine/eslint/commit/7c0b794498b43920f30f461c292241ad5f6a57c6 it is ready (except that I don't have any issue to reference in the commit message), however I've been reading Github issues and especially this one: https://github.com/eslint/eslint/issues/5131 as well as this comment: https://github.com/eslint/eslint/issues/5329#issuecomment-187796641, in the first one you're saying that you're careful with new autofixes because it could create conflicts and in the second one there's an actual example where `comma-dangle` autofix could be conflicting.

My question is: would you accept a PR to autofix `comma-dangle` (code is above) considering that I used it on my own codebase and it worked perfectly and saved me a lot of time (and it could save a lot of time to other people as well)?

**Comment by alberto** [comment]
Sorry, we can't because it could cause conflicts with other rules. See https://github.com/eslint/eslint/issues/4418 and https://github.com/eslint/eslint/issues/3805 for previous discussion on the topic.
