### ISSUE TITLE
Automatic conversion of .jscsrc files to .eslintrc files

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5857]
For people coming over from JSCS, it would be nice to have a way to automatically convert their `.jscsrc` files into equivalent `.eslintrc` files. 

What I have in mind is adding an additional option to `--init` that is "Convert JSCS configuration file":

* We could use [Polyjuice](https://github.com/brenolf/polyjuice) to do this, and contribute back to Polyjuice to help make it more feature-complete.
* We'd need to figure out what to do about style presets from JSCS. Some of them already have ESLint shareable config equivalents, but I'm guessing a lot of them do not. We might need to do this manually.

Another option would be to instruct people on how to do the conversion themselves using Polyjuice or some other tool, though it seems like the better user experience would be to have this capability as part of ESLint.

Thoughts?

**Comment by ilyavolodin** [comment]
I think using polyjuice inside `--init` is a better for end users, so I would vote for that approach.

**Comment by mgol** [comment]
It might be worthwhile to be able to merge existing `.jscsrc` AND `.eslintrc` into a final `.eslintrc` as some people are already using ESLint in conjunction with JSCS. I know I have for some time, in times when JSCS had way more style-related rules than ESLint.

**Comment by nzakas** [comment]
That's an interesting point. The trouble we always run into when re-writing existing config files is that we end up losing all of the comments, so I'm not sure people would welcome that. We could definitely detect if there's an existing `.eslintrc` file and do something else (like output to the console instead of the file).

**Comment by mgol** [comment]
Hmm, right, I didn't think about comments. The main problem is what to do with converted rules that overlap with the already specified ones. If we had a way to resolve that, omitting the ones that are already present in the console output would help - people would just copy the output and append to the file.

But maybe it's impossible to resolve those conflicts properly.

**Comment by nzakas** [comment]
I think, unfortunately, we may have to rely on people handling those conflicts manually.

**Comment by alberto** [comment]
Is there any benefit to do it in core vs a separate tool?

**Comment by ndarville** [comment]
`eslint/jscs-migrate`? Would also make issue management easier, especially when you can add a bunch of specific disclaimers in `CONTRIBUTING` and `ISSUE_TEMPLATE`.

**Comment by platinumazure** [comment]
I like @ndarville's idea. To me this is similar to how we have eslint-transforms for transforming old-style rules to new-style rules: We *could* have put that in ESLint, but we wanted to avoid scope creep there and instead created a separate small project. I believe the same thing should happen for this use case.

**Comment by nzakas** [comment]
We are trying to make conversion as easy as possible for JSCS users. Asking them to download a second tool is another barrier that we were hoping to eliminate.

**Comment by platinumazure** [comment]
Hmm. Well, maybe it would be possible to have the logic in another package and ESLint can prod-depend on it. I'm just looking out for ESLint's health, I guess.

**Comment by nzakas** [comment]
@platinumazure the proposal is to use Polyjuice. (see original description)

**Comment by nzakas** [comment]
After thinking about this some more, I wonder if we can get away with just having people use Polyjuice directly. It would mean we don't have to add anything specifically to ESLint, avoiding another dependency. We would just have to make sure that the documentation called out this step.

Thoughts? @markelog

**Comment by markelog** [comment]
Yeah! I think that works

**Comment by nzakas** [comment]
Okay, closing this and will roll the work into https://github.com/eslint/eslint/issues/5859 (which I'm starting).
