### ISSUE TITLE
Rule metadata: Moving "fixable" field from docs to top level could be a breaking change for plugin authors

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#5862]
Per discussion on [the Gitter chat](https://gitter.im/eslint/eslint?at=57100ab75ed5a4fd3fe31e57), the change to move the "fixable" field in rules metadata from the "docs" section to the top level is potentially a breaking change if plugin authors have already started migrating their rules to use metadata (but with "fixable" located in "docs").

We may need to support both locations for 2.x, and remove support for the "fixable in docs" scenario with 3.0.

cc: @ilyavolodin, @nzakas

**Comment by nzakas** [comment]
I disagree. This is the first release that we'll be publicizing the new rule format. Prior to this, it was an internal-only concern, so this change is nonbreaking and not really anything that has to be considered.

**Comment by platinumazure** [comment]
@nzakas Does that apply even if plugin authors (perhaps imprudently) consumed the new format? If so, I'll close this.

**Comment by nzakas** [comment]
Yes. If you're using something that wasn't documented, you can't be upset when it breaks. Doing so is a "void your warranty" situation. Plus, I can't imagine anyone (other than @ilyavolodin ) who would have done such a thing.

**Comment by ilyavolodin** [comment]
I'm crazy that way:-) But then I created metadata, so it's unlikely that anyone else would know much about it. My only concern with this situation is that plugin author might specify peerDependancy of eslint@2.0.0 which already had metadata support, but `fixable` field was still inside `docs`. In that case, even if `fixable` would be specified, ESLint would not allow autofix for this rule. But that should be very rare case, and very easily fixable, so I would be OK with not doing anything about this.

**Comment by platinumazure** [comment]
Fine by me. I wonder if we could/should do a documentation change which advises that plugins who want to use this rule metadata should require ^2.8.0 (or whatever version) in docs?

Actually, I could generalize that into a different issue (there is similar lack of clarity on what version of ESLint should be in peer dependencies for things like auto-fix). I'll open an issue along those lines. Thanks!
