### ISSUE TITLE
"Get Started" instructions recommend global installation

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#5874]
We currently recommend installing ESLint globally right before we point new users to the `--init` feature in both the [README](https://github.com/eslint/eslint#installation) and our [Getting Started page](http://eslint.org/docs/user-guide/getting-started). This doesn't seem right, as `--init` is geared towards a local ESLint setup (it installs all the plugins locally). If the users follow these instructions they'll end up in the same position as the issue creator in #5833. 

While we're working out a fix for that situation in #5833, I wonder if we should also clarify in the docs that we actually do recommend using a local over a global installation of ESLint. This issue might belong in the [eslint.github.io repo](https://github.com/eslint/eslint.github.io), but I see this is in the README for this repo too.

**Comment by alberto** [comment]
Agree. However, then we would also have to replace calls to `eslint` in all commands to `./node_modules/eslint/bin/eslint.js`, unless we also recommend to install globally `eslint-cli`

**Comment by kaicataldo** [comment]
I wasn't aware of `eslint-cli` - can we incorporate that into our docs somehow? Or are there downsides to recommending the usage of it?

If we decided we wanted to recommend its use, the docs could say something like:

## Installation

We recommend that you install ESLint locally per project and to use the globally installable ESLint CLI tool to run ESLint from the command line:

    npm install eslint
    npm install -g eslint-cli

## Usage

If it's your first time using ESLint, you should set up a config file using `--init`:

     eslint --init

After that, you can run ESLint on any JavaScript file:

    eslint test.js test2.js

**Comment by mysticatea** [comment]
May I move `eslint-cli` to the `eslint` organization.
People can use it at ease since they feel it's official on that, I think.
Of course, I will continue to maintain it. :)

**Comment by nzakas** [comment]
I don't want to include `eslint-cli` in the instructions. People complained about double installations for things like Gulp and Grunt, and I don't want to add that here.

Really, the only issue we have right now is with absolute beginners who aren't used to using npm. If we want to include some longer text about the difference between local vs. global installs, that's fine, I just wouldn't want to introduce `eslint-cli` into the discussion at this point.

**Comment by kaicataldo** [comment]
Alright. I'll put together a PR for the docs change. Is moving `eslint-cli` into the organization off the table for now as well?
