### ISSUE TITLE
Add `Chore` to allowed commit tags

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5880]
As proposed in the [chatroom](https://gitter.im/eslint/eslint?at=571265572c97111664328234), we could add a tag for internal tasks that don't have observable effect on user experience, such as refactoring, adding tests, removing unused code or general cleanup.

[Here](https://github.com/eslint/eslint/pull/5853) [are](https://github.com/eslint/eslint/pull/5849) a couple of PRs that would qualify for this.

@eslint/eslint-team opinions?

**Comment by kaicataldo** [comment]
I'm for the addition of this label. Would be nice to an easy way to identify tech debt-ish issues

**Comment by platinumazure** [comment]
Would we also add a corresponding issue label (perhaps also "chore", to keep it simple)?

**Comment by ilyavolodin** [comment]
We need to update Maintainer guide, bot and build script if we are adding a new label.

**Comment by mikesherov** [comment]
:+1: @ilyavolodin @alberto, I'd like to work on this, as it'd be a nice first issue for me, where I can get familiar with some of the team's tooling.

Is that ok?

**Comment by ilyavolodin** [comment]
@mikesherov Sounds good. Just need to wait a little bit for @nzakas to mark this as `approved`, but since he is the one who proposed it, I don't see a problem with it. Also, bot is currently not open sourced, so @nzakas will have to make that change. Everything else is up for grabs

**Comment by ilyavolodin** [comment]
Oh and forgot about release script. I think there might need to be some modifications there to aggregate base log entries based on the new label (although I don't remember if the list of labels is supplied there or it's just aggregating everything that it finds, without caring what it is).

**Comment by alberto** [comment]
@mikesherov 👍  welcome to the team!

I looked at `eslint-release` and it doesn't look like any changes are needed.

Someone else with permissions will have to create the label, too.

**Comment by mikesherov** [comment]
@nzakas any chance I can get access to the repo for the eslint bot?

**Comment by nzakas** [comment]
The things that need to be updated are:

1. Bot message - https://github.com/eslint/eslint/blob/master/templates/pr-create.md.ejs
2. Bot message test - https://github.com/eslint/eslint/blob/master/tests/templates/pr-create.md.ejs.js
3. Documentation - https://github.com/eslint/eslint.github.io/blob/master/docs/developer-guide/contributing/pull-requests.md and https://github.com/eslint/eslint.github.io/blob/master/docs/developer-guide/contributing/working-on-issues.md
4. Blog post template - https://github.com/eslint/eslint/blob/master/templates/blogpost.md.ejs

**Comment by nzakas** [comment]
I created the label. Not sure why you couldn't @alberto, I need to double check the permissions setup.

**Comment by platinumazure** [comment]
@nzakas Also we need to update Makefile.js so that `npm run check-commit` will accept the new label, or has that been done already?

**Comment by nzakas** [comment]
@platinumazure oops, forgot about that. Added.

**Comment by alberto** [comment]
@mikesherov are you working on this?

**Comment by mikesherov** [comment]
Yup. I'll do it tonight. Thanks for the ping

**Comment by alberto** [comment]
Cool. I just asked because we are already using the new tag, so it would be nice to have this soon.

**Comment by mikesherov** [comment]
PR coming soon

**Comment by mikesherov** [comment]
https://github.com/eslint/eslint/pull/5929 @alberto @nzakas review?

**Comment by mikesherov** [comment]
@nzakas looks like you already took care of the Documentation.
