### ISSUE TITLE
eslint.org should support HTTPS

### ISSUE THREAD

**Issue by bhubbard** [eslint/eslint#5883]
http://eslint.org should support and probably default to HTTPS. This can easily be done with a service such as CloudFlare or Let's Encrypt.

**Comment by ilyavolodin** [comment]
Our site is hosted on Github and Github pages doesn't support HTTPS currently, so not much we can do about this, without switching hosting. Closing as this is not something we are planning on doing.

P.S. While I know that the flavor of the month is making everything https, I really don't see a point in slowing down the site without a single form just to satisfy search engines.

**Comment by bhubbard** [comment]
So to clarify, its a flavor of the month thats gonna stick around, and just continue to grow. 

You can use CloudFlare to support HTTPS on github pages, and more than likely it will actually improve performance as it will provide support for SPDY/HTTP2.

**Comment by michaelficarra** [comment]
@ilyavolodin A MITM would be happy to change the installation instructions or user guide to deceive a user and convince them to execute code of his choosing. TLS is important *everywhere*. The only case I could imagine it wouldn't be is if you're going to pipe it directly to /dev/null, but then why would one do that?

**Comment by BYK** [comment]
I've also been using another solution, Kloudsec, on my GitHub hosted pages which seems to be working pretty nicely. It also uses Let's Encrypt so we don't need to deal with certificates. 

Needs a DNS record change to get started though.

**Comment by awendland** [comment]
Just FYI (in case anyone stumbles on this): Kloudsec has since shutdown
