### ISSUE TITLE
Add the opposite of eslintignore ("files" field)

### ISSUE THREAD

**Issue by MoOx** [eslint/eslint#5893]
From what I am reading in the docs (http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) there is currently only a wait to ignore files, but nothing like [npm files](https://docs.npmjs.com/files/package.json#files) to include the files you want from the config file.
Another example is the AVA test runner that offers a "files" field so we can choose what to test https://github.com/sindresorhus/ava#configuration

Currently I have a project with multiples node_modules folder, in multiples folders (https://github.com/MoOx/phenomic) and when I lint with the proper ignore pattern (currently, my gitignore file), it takes around 20s.
By providing only the accurate places, I cut the time to 5s.

But the command is pretty long 

```console
$ eslint src __tests__ scripts npm docs/scripts docs/src docs/web_modules boilerplate/scripts boilerplate/src boilerplate/web_modules  
```

What do you think about adding a "files" field in the configuration object to put all entries here, like npm and AVA (and probably others)?

(I took a quick look for opened issue, but can't find anything about that, sorry if I miss something.)

**Comment by ilyavolodin** [comment]
The reason it's slow currently is that ignore patterns do not affect globing. So while files under your node_modules directory is not going to be linted, they are still being walked though when we are opening globs. There's already an open issue tracking this: #5679
Once that is fixed, I really don't see the need for both include and exclude patterns, when you specify exclude pattern, everything that doesn't match it is by definition included.

**Comment by MoOx** [comment]
Oh, that's interesting. So I am tracking this issue. Thanks for the explanation. Should I close this one then?

**Comment by ilyavolodin** [comment]
I think it's safe to close, since #5679 is already tracking the same problem.
