### ISSUE TITLE
Improve the UX of using an npm installed formatter

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#5900]
This is currently what you have to write to use a custom npm installed formatter with ESLint:

```
$ eslint --format=node_modules/eslint-formatter-unicorn file.js
```

That's not very user-friendly.

I propose the following:

1. Make [`getFormatter()`](http://eslint.org/docs/developer-guide/nodejs-api#getformatter) try to [require the formatter from cwd](https://github.com/sindresorhus/req-cwd) first. That way you could just do:

```
$ eslint --format=eslint-formatter-unicorn file.js
```

2. Make it possible to omit the `eslint-formatter` prefix. This matches the convention for shareable configs. This combined with `1.` would mean you could just do:

```
$ eslint --format=unicorn file.js
```

Much nicer! ✨
## 

I would also document the recommendation of using the `eslintformatter` keyword in package.json, like you do with shareable configs. This would make it easier for users to find third-party formatters.

**Comment by platinumazure** [comment]
@sindresorhus To be clear, you are looking for this enhancement in CLIEngine and the CLI interface, if possible?

**Comment by sindresorhus** [comment]
@platinumazure Yes, more specifically, in `CLIEngine.getFormatter`.

**Comment by ilyavolodin** [comment]
I was wondering if we should instead add formatters to be distributed through plugins? Formatters are the only thing we currently have that we don't have a recommended way of shearing.

**Comment by nzakas** [comment]
I fear this is more complicated than it looks. That said, @sindresorhus if you want to volunteer to investigate feasibility, we can consider it.

**Comment by sindresorhus** [comment]
I've already looked into it, and doesn't seem that hard to me, unless I'm missing something.

I would just use [`resolve-from`](https://github.com/sindresorhus/resolve-from) [here](https://github.com/eslint/eslint/blob/38feead95f8d84f6a2f89beec56f5ac133efe479/lib/cli-engine.js#L481) and prepend `eslint-formatter` if missing.

Untested patch:

```diff
@@ -1,3 +1,5 @@
+var resolveFrom = require("resolve-from");
+
 CLIEngine.getFormatter = function(format) {
 
     var formatterPath;
@@ -11,13 +13,20 @@
         // replace \ with / for Windows compatibility
         format = format.replace(/\\/g, "/");
 
+        var cwd = this.options ? this.options.cwd : process.cwd();
+
         // if there's a slash, then it's a file
         if (format.indexOf("/") > -1) {
-            var cwd = this.options ? this.options.cwd : process.cwd();
 
             formatterPath = path.resolve(cwd, format);
         } else {
-            formatterPath = "./formatters/" + format;
+            var npmFormat = /^eslint-formatter-/.test(format) ? format : "eslint-formatter-" + format;
+
+            formatterPath = resolveFrom(cwd, npmFormat);
+
+            if (!formatterPath) {
+                formatterPath = "./formatters/" + format;
+            }
         }
 
         try {
```

**Comment by nzakas** [comment]
I'd prefer not to add a second way to resolve modules (we already have a utility for that), but otherwise looks okay.

The next would be to submit a pull request for the change. We'd need tests as well as documentation in order to merge.

**Comment by joefraley** [comment]
Is it currently possible to specify a formatter via the .eslintrc file? That's what i ultimately want.

**Comment by sindresorhus** [comment]
@joefraley Use the support channels for support questions:

- https://groups.google.com/group/eslint
- https://gitter.im/eslint/eslint

**Comment by kaicataldo** [comment]
As per our discussion in today's TSC meeting, this issue has been added to the Core Roadmap.

**Comment by testower** [comment]
I forgot to mention, but I'm working on this one. It's in review.

**Comment by not-an-aardvark** [comment]
This was added in https://github.com/eslint/eslint/pull/9464.
