### ISSUE TITLE
Chore: Create integration test for auto-fixing

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5909]
JSCS had a very nice test to check auto-fixing. It had two config files and it would take the whole source code of itself and autofix it to second config, then autofix it to first and compare results. @mikesherov @hzoo @markelog @mdevils @zxqfox correct me if I'm wrong in my description above.

I think it would be really nice to add similar test to ESLint. We just added multi-pass autofixing, and it would be nice to verify that it's working correctly.

**Comment by mikesherov** [comment]
Yup this is accurate.

**Comment by not-an-aardvark** [comment]
I'll work on this.
