### ISSUE TITLE
Port JSCS require|disallowMultipleVarDecl rules

### ISSUE THREAD

**Issue by zxqfox** [eslint/eslint#5910]
[requireMultipleVarDecl](http://jscs.info/rule/requireMultipleVarDecl), [disallowMultipleVarDecl](http://jscs.info/rule/disallowMultipleVarDecl) → http://eslint.org/docs/rules/one-var (?)

`onevar` doesn't cover atm these cases:
- `{requireMultipleVarDecl: true}`
- `{requireMultipleVarDecl: {allExcept:["require"]}}`
- `{disallowMultipleVarDecl: {allExcept:["require"]}}`
- `{disallowMultipleVarDecl: {allExcept:["undefined"]}}` (if it's not the same as `{var: {uninitialized: "always"}}`)

Current `one-var` options: `{ var | let | const | uninitialized | initialized: "always"|"never" }`.

**Comment by vitorbal** [comment]
would this be related to #4680?

**Comment by zxqfox** [comment]
Yeah, looks like it's a pure duplicate. ;-(
