### ISSUE TITLE
Update rule descriptions

### ISSUE THREAD

**Issue by scriptdaemon** [eslint/eslint#5912]
This is just a small tracking issue for the few rules that specifically refer to a kwyrod (`var` and `function`) in their descriptions even though the rules apply to the broader concept (`let` and/or `const` and arrow functions). As the metadata is added to the rules, these can be updated then, and the remaining descriptions can be updated when the metadata updates are complete. The rules that only apply to specific keywords do not need to be updated.

The descriptions to be updated are in https://github.com/eslint/eslint/pull/5890. Specifically:

 - [x] `func-call-spacing`: require or disallow spacing between function identifiers and their invocations
 - [x] `init-declarations`: require or disallow initialization in variable declarations
 - [x] `max-params`: enforce a maximum number of parameters in function definitions
 - [x] `max-statements`: enforce a maximum number of statements allowed in function blocks
 - [x] `new-cap`: require constructor names to begin with a capital letter
 - [x] `newline-after-var`: require or disallow an empty line after variable declarations
 - [x] `no-implicit-globals`: disallow variable and `function` declarations in the global scope
 - [x] `no-inner-declarations`: disallow variable or `function` declarations in nested blocks (recommended)
 - [x] `no-mixed-requires`: disallow `require` calls to be mixed with regular variable declarations
 - [x] `no-redeclare`: disallow variable redeclaration (recommended)
 - [x] `no-shadow`: disallow variable declarations from shadowing variables declared in the outer scope
 - [x] `no-spaced-func`: disallow spacing between function identifiers and their applications
 - [x] `one-var-declaration-per-line`: require or disallow newlines around variable declarations
 - [x] `sort-keys`: require object keys to be sorted
 - [x] `space-infix-ops`: require spacing around infix operators

**Comment by nzakas** [comment]
@scriptdaemon @pedrottimark what do you want to do with this issue?

**Comment by pedrottimark** [comment]
@nzakas Thank you for reminding us of this. What do you think of the following way forward:

1. Keep this issue as **evaluating** until the build process uses the `meta.docs.description` property. My bad to forget to add the questionable descriptions that I have found while editing 😳
2. During the first week **after** the first ESLint version with improved build process, we invite the rest of the team to comment on the list of potential changes as it exists at that time.
3. At the beginning of the second week, a reviewer marks the issue as **accepted** with the changes that have agreement, and then @scriptdaemon or I submit a **Chore** pull request to close this issue.

**Comment by nzakas** [comment]
Sounds like a plan. :+1:
