### ISSUE TITLE
Rule "array-bracket-spacing" doesn't work properly

### ISSUE THREAD

**Issue by dfilatov** [eslint/eslint#5930]
**What version of ESLint are you using?**
2.8.0

**Please show your full configuration:**
```json
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "rules": {
    "no-multi-spaces": "error",
    "no-trailing-spaces": "error",
    "curly": [
      "error",
      "all"
    ],
    "no-multiple-empty-lines": [
      "error",
      {
        "max": 1
      }
    ],
    "no-mixed-spaces-and-tabs": "error",
    "key-spacing": [
      "error",
      {
        "beforeColon": true,
        "afterColon": true
      }
    ],
    "array-bracket-spacing": [
      "error",
      "never"
    ],
    "space-before-function-paren": [
      "error",
      "never"
    ]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
myArray[ i ] = 4;
```

**What did you expect to happen?**
I expect that the code above will raise an error since "array-bracket-spacing" is actually "never".

**What actually happened? Please include the actual, raw output from ESLint.**
Nothing. Output is clean.

**Comment by erikdesjardins** [comment]
`array-bracket-spacing` only applies to array literals and array destructuring, [as documented](http://eslint.org/docs/rules/array-bracket-spacing).

The rule you're looking for is [computed-property-spacing](http://eslint.org/docs/rules/computed-property-spacing).

**Comment by dfilatov** [comment]
@erikdesjardins  Thank you for explanation
