### ISSUE TITLE
Explain the purpose of the comments used to separate code blocks

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#5931]
Whenever I look at the ESLint code, what strikes me is the use of seemingly purposeless comments to separate blocks of code, e.g.

```js
//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

// ...

//------------------------------------------------------------------------------
// Helpers
//------------------------------------------------------------------------------

// ...

//------------------------------------------------------------------------------
// Public Interface
//------------------------------------------------------------------------------
```

The reason I see this as "purposeless" is because most (if not all) of it can be enforced using code linting (esp. if the codebase is written in ES6).

I'd like to hear what a proponent of this convention has to say about its benefits.

**Comment by platinumazure** [comment]
Those are standards drawn up by the project lead, @nzakas, so I suspect we'll have to hear from the man himself.

**Comment by nzakas** [comment]
It creates sections in the file that have dedicated purposes, so you know `require` statements come first, then private stuff, then public stuff. It also really helps with making the file a bit more approachable for people who are unfamiliar with the code base.

**Comment by gajus** [comment]
> It creates sections in the file that have dedicated purposes, so you know require statements come first, then private stuff, then public stuff. It also really helps with making the file a bit more approachable for people who are unfamiliar with the code base.

The thing is, that this how you would structure the code anyway.

> so you know require statements come first

If your require statements are not at a top, chances are, you are already doing something wrong.

This can be enforced using a combination of:

* http://eslint.org/docs/rules/global-require
* http://eslint.org/docs/rules/init-declarations
* http://eslint.org/docs/rules/vars-on-top

> then private stuff, then public stuff

Everything that is exported is public, everything thats not exported is private. There is no other way.

**Comment by nzakas** [comment]
@gajus I'm sorry, this isn't a discussion I'm interested in having. We have our conventions and I explained the rationale. You can feel free to disagree and do things differently in your projects. Our conventions are set.
