### ISSUE TITLE
Add auto-fixing to newline-after-var

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#5959]
Similar to #5958.

**Comment by vitorbal** [comment]
@kaicataldo maybe I could give this one a shot? If you're not already on it :)

**Comment by kaicataldo** [comment]
@vitorbal I think @markelog was going to take a look at this - if not, it's all yours!

**Comment by markelog** [comment]
Mine! :)

Hope that's okay

**Comment by vitorbal** [comment]
Of course! All yours :)

**Comment by cristian-sima** [comment]
Any update on this auto-fix? 

It is so frustrating to add them manually :) 

I think as long as you detect them, there should not be very difficult to add a `\n` at the end of the var block

**Comment by markelog** [comment]
It is on my list, I even started it at one point, but there is a lot of to be done here, so i'm a will kick this up again in few weeks hopefully

**Comment by platinumazure** [comment]
@markelog Is it worth unassigning yourself in case someone else wants to jump in on this? (Or, better, is there anything other team members can take off your plate?)

**Comment by markelog** [comment]
Am still planning do it, but if someone ready to start working on it right now, then yeah, re-assign away :)
