### ISSUE TITLE
prefer-template option, allowing multiline concatenation

### ISSUE THREAD

**Issue by le0nik** [eslint/eslint#5961]
Hi.

I think it would be useful to allow string concatenation, if user spreads the string across multiple lines(either because the string is too long to fit into a single line, or for readability purposes).

For example this code will throw:

```js
/*eslint "prefer-template": "error" */
const name = "John";
const longStr = 'Hi, ' +
    name +
    '. I am a long string, ' +
    'that\'s going to be spread across multiple lines.';
```

I propose an option, like `allowMultiline`, so that this code doesn't throw:

```js

/*eslint "prefer-template": ["error", { "allowMultiline": true }]*/
const name = "John";
const longStr = 'Hi, ' +
    name +
    '. I am a long string, ' +
    'that\'s going to be spread across multiple lines.';
```

**Comment by alberto** [comment]
Template literals can span multiple lines, so I am not sure why you would want such option. Can you elaborate?

**Comment by platinumazure** [comment]
@alberto The string literal is across multiple lines, but the string itself has no newline characters. In template literals, if newlines are supplied, do those get ignored or are they treated as `"\n"` characters?

**Comment by alberto** [comment]
@platinumazure thanks, my brain automatically inserted linebreaks :D

**Comment by le0nik** [comment]
```js
var template = `This is a
multiline template`;
```

equals to `This is a\nmultiline template`

whereas

```js
var template = 'This is a ' +
'multiline template';
```

equals to `This is a multiline template`.

Demo [here](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Cstage-0&code=%2F%2F%20Template%20literal%20string%0Aconst%20templateLiteralStr%20%3D%20%60This%20is%20a%0Amultiline%20template%60%3B%0A%0A%2F%2F%20Template%20literal%20string%0Aconst%20concatStr%20%3D%20'This%20is%20a%20'%20%2B%0A'multiline%20template'%3B).

**Comment by mysticatea** [comment]
I think now this rule is expecting the following code.
We can include any spaces and line breaks between `${` and `}`.

```js
/*eslint "prefer-template": "error" */
const name = "John";
const longStr = `Hi, ${
    name
    }. I am a long string, ` +
    'that\'s going to be spread across multiple lines.';
```

Or

```js
/*eslint "prefer-template": "error" */
const name = "John";
const longStr = `Hi, ${name}. I am a long string, ` +
    'that\'s going to be spread across multiple lines.';
```

**Comment by EnoahNetzach** [comment]
The problem could arise when used with _max-len_ rule, if in the string itself I don't have a `\n` character:

```es6
/* eslint prefer-template: "error" */
/* eslint max-len: ["error", 80] */
const limit = 80
const string = `This string is longer than the (absurdly low) limit of ${limit} chars, but shouldn't span on multiple lines`
```

or, in general, if I have some `\n` chars, but I want to indent it consistently:

```es6
/* eslint prefer-template: "error" */
const name = 'John'
if (check) {
    const string = `This line spans multiple lines, but when I go to a new line
all my efforts to maintain a nice-looking indentation are gone.
By the way, hi, ${name}!`
}
```

**Comment by mysticatea** [comment]
@EnoahNetzach You can use concatenations.

```js
/* eslint prefer-template: "error" */
/* eslint-env es6 */

const name = 'John'
if (check) {
    const string = `This line spans multiple lines, but when I go` +
        `to a new line all my efforts to maintain a nice-looking` +
        `indentation are gone. By the way, hi, ${name}!`
}
```

`prefer-template`  is not warning concatenations between literals.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
