### ISSUE TITLE
Move all docs into eslint repo

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5964]
Right now we have a very weird mix of some docs that live in `eslint.github.io` and some that live in `eslint`. I find this pretty confusing (though it's highly likely I'm the one to blame for this!). For instance, there are files here:

https://github.com/eslint/eslint.github.io/tree/master/docs/user-guide

That are not here:

https://github.com/eslint/eslint/tree/master/docs/user-guide

I'd like to propose that everything in the `docs` directory on `eslint.github.io` be maintained in the `eslint` repo from now on. That will help us ensure that all documentation changes can happen in one place without any arbitrary distinction (which we appear to have right now).

This would still allow us to update things like the demo, homepage, blog, etc., directly in `eslint.github.io`. I'm talking only about moving those files that are currently in `docs`.

**Comment by nzakas** [comment]
Note: we may need to update `Makefile.js` as part of this. We should double-check that.

**Comment by alberto** [comment]
Also rules doc? How would we ensure a new or updated rule has the corresponding doc?

**Comment by platinumazure** [comment]
:+1: from me, I always thought the distinction was weird.

**Comment by nzakas** [comment]
@alberto what are you referring to? Rule docs are already in the `eslint` repo.

**Comment by BYK** [comment]
:+1:

**Comment by alberto** [comment]
Sorry, I read it backwards. I thought you wanted to move the docs from here to there.

**Comment by nzakas** [comment]
@alberto ah okay. Cool.

So I think, in general, this should just be copying all files that don't currently exist in this repo to this repo:

1. Copy the files over (only the ones that don't exist in the `eslint` repo) from:
  * `docs/developer-guide`
  * `docs/user-guide`
  * `docs/maintainer-guide`
2. Remove the Jekyll front matter from each file
3. Do not copy over `docs/user-guide/rules.md`, as that is just a Jekyll redirect.
4. Update `Makefile.js` to ensure all the files get copied over. I think they all should right now except for `docs/maintainer-guide`, so that might be the only change necessary.

**Comment by platinumazure** [comment]
I'm interested in working on this, if nobody has laid a claim already.

Should we also write a PR in eslint.github.io which removes the redundant files? (Perhaps after the ESLint repo's pull request is merged, since copy/overwrite of files during release should be safe)

**Comment by nzakas** [comment]
> Should we also write a PR in eslint.github.io which removes the redundant files? 

There aren't any redundant files. The eslint.github.io repo is the live site, so that's what shows up on eslint.org. when we do a release, those files are overwritten with the ones from this repo. We need copies in both places.

**Comment by nzakas** [comment]
Working on this.
