### ISSUE TITLE
`lines-around-comment` reports multiple errors for comments on same line

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5965]
Using 2.8.0.

This is actually covered by a test, but I am not sure it is the correct behaviour, since they are basically reporting the same failure (I found this while adding autofix for the rule):

```
        {
            code: "bar()\n/* first block comment */ /* second block comment */\nvar a = 1;",
            options: [{ afterBlockComment: true, beforeBlockComment: true }],
            errors: [
                { message: beforeMessage, type: "Block", line: 2 },
                { message: afterMessage, type: "Block", line: 2 },
                { message: beforeMessage, type: "Block", line: 2 },
                { message: afterMessage, type: "Block", line: 2 }
            ]
        },
```

I would only expect the first 2 errors, for the first comment.

Note this code is valid (i.e comments don't need to be on different lines from each other) :
```
        {
            code: "bar()\n\n/* first block comment */ /* second block comment */\n\nvar a = 1;",
            options: [{ afterBlockComment: true, beforeBlockComment: true }]
        },
```

**Comment by platinumazure** [comment]
Marking "bug"/"evaluating" for now. I'm not sure what the expected behavior should be here, honestly.

**Comment by alberto** [comment]
@xjamundx I'd like to know your opinion on this, since you created the rule

**Comment by xjamundx** [comment]
I agree with the premise that it shouldn't give 4 errors, much easier to code it up that way though. Not sure it's worth prioritizing a fix, but if someone wants to do it, I think I'd agree.

**Comment by alberto** [comment]
Ok, thanks. I'll do it. I need it to properly autofix this.
