### ISSUE TITLE
RuleTester should throw if test has output but rule is new-style and lacks meta.fixable property

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#5970]
As discussed in the [chat](https://gitter.im/eslint/eslint?at=571fcbb64da16e7d13d90814), it's pretty easy to forget to add `meta.fixable` to a new-style rule and then the unit tests simply won't run auto-fix.

It might be worthwhile to add an assertion to RuleTester. If the test has `output` property and the rule has `meta` but does not have `meta.fixable` set to code or whitespace, an assertion failure should be thrown here so that the developer knows that `meta.fixable` needs to be set on the rule.

**Comment by platinumazure** [comment]
Not sure if this should be "core" or "infrastructure", so leaving that label off for now.

**Comment by vitorbal** [comment]
I'd like to work on this one if it gets accepted :)

**Comment by nzakas** [comment]
The rule should throw if it uses `fix` and doesn't have `fixable` set. If that isn't happening, then that's a bug we should fix. That would, in turn, throw an error during testing.

**Comment by ilyavolodin** [comment]
It's not throwing in the current implementation. It will just not run fix on the rule that doesn't have `meta.fixable` set.

**Comment by nzakas** [comment]
@ilyavolodin then we should throw in that case. I think we talked about this way back, so easy to forget.

**Comment by ilyavolodin** [comment]
I think throwing is fine. We just need to make sure the code is done in such a way that it would only through for rules in new format.

**Comment by vitorbal** [comment]
@nzakas @ilyavolodin please let me know if this is what you had in mind: #6043
