### ISSUE TITLE
CLIEngine.getFormatter swallows exceptions from formatters.

### ISSUE THREAD

**Issue by gustavnikolaj** [eslint/eslint#5977]
**What version are you using?**
2.8.0

**What did you do?**
I had [a problem](https://travis-ci.org/assetgraph/assetgraph/jobs/126035656#L926) in a project where a specific set of packages meant that chalk would be installed in a broken way. I'm trying to reproduce this in a more minimal setting, to report it as an error to npm, as it is only happening with this specific combination of packages and npm 3.

The problem was, that the broken install of chalk (used in the stylish formatter) could not find its dependency has-ansi.

**What happened?**

Running eslint reported that the formatter could not be found, and exited with status 1.

```
$ eslint .
Could not find formatter 'stylish'.
```

**What did you expect to happen?**

That running eslint would have shown me the error and not have told me that the stylish formatter was missing.

```
$ eslint .

Cannot find module 'has-ansi'
Error: Cannot find module 'has-ansi'
...
    at Object.<anonymous> (/projectRoot/node_modules/chalk/index.js:5:15)
...

```

**Comment by nzakas** [comment]
Hmm, yeah, that's not good. We should fix that.
