### ISSUE TITLE
Proposed Rule: check number of parameters between function invocation and definition

### ISSUE THREAD

**Issue by fengthedroid** [eslint/eslint#5984]
As node 6 supports [default parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters), I wonder if it makes sense that we can have an eslint rule as: 
Unless the function signature explicitly expressing that a parameter can be defaulted to undefined or some other value, it shouldn't allow function invocation to have either less or more parameters than the function signature designated.

We have experienced that sometimes the function signature changed but some invocations wasn't updated hence bugs were introduced. With this rule the bugs can be prevented.

Example of the bug:
Originally:
`function foo(a, b) { return a + b};
foo(1, 2) //returns 3`

Then some guy changed the definition of the function to:
`function foo(sign, a, b) {return (a+b)*sign}`
but forgot to update the invocation
`foo(1,2) //now returns NaN`

So the rule will warn after the guy changed the function signature from 2 parameters to 3.

**Comment by alberto** [comment]
We can't do that kind of static analysis in eslint, considering the function could be defined in a different file
