### ISSUE TITLE
Error: cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by olalonde** [eslint/eslint#5997]
**What version of ESLint are you using?**

2.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint ^6.0.4

**Please show your full configuration:**

```
{
  "extends": "airbnb/base",
  "parser": "babel-eslint",
  "rules": {
    "no-param-reassign": [2, {"props": false}],
    "semi": [2, "never"],
    "camelcase": 0,
    "consistent-return": 0,
  }
}
```

package.json:

```
{
  "name": "merkletree",
  "version": "1.0.0",
  "description": "Merkle Tree data structure in Javascript",
  "main": "lib/index.js",
  "scripts": {
    "start:dev": "babel-node src/server",
    "lint": "eslint src/ test/",
    "build": "babel ./src --out-dir ./lib --copy-files",
    "test": "babel-tape-runner test/*.js"
  },
  "author": "Olivier Lalonde <olalonde@gmail.com>",
  "license": "MIT",
  "devDependencies": {
    "babel-cli": "^6.7.7",
    "babel-eslint": "^6.0.4",
    "babel-plugin-transform-es2015-destructuring": "^6.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.6.5",
    "babel-preset-es2015-node6": "^0.1.3",
    "babel-tape-runner": "^2.0.1",
    "blue-tape": "^0.2.0",
    "eslint": "^2.8.0",
    "eslint-config-airbnb": "^8.0.0",
    "eslint-plugin-import": "^1.6.1"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```
npm run lint
```

**What did you expect to happen?**

For eslint to not throw an error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
$ npm run lint                       master ✗

> merkletree@1.0.0 lint /Users/olalonde/code/blockai/merkletree
> eslint src/ test/

module.js:440
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/olalonde/code/blockai/merkletree/node_modules/.bin/eslint:32:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/olalonde/.nvm/versions/node/v6.0.0/bin/node" "/Users/olalonde/.nvm/versions/node/v6.0.0/bin/npm" "run" "lint"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! merkletree@1.0.0 lint: `eslint src/ test/`
npm ERR! Exit status 1
npm ERR!
```

**Comment by nzakas** [comment]
It looks like you're using `babel-eslint` as your parser. Can you try using the default parser instead? You can just delete the `parser` from your config file to switch to the default parser. Make sure you configure the [parser options](http://eslint.org/docs/user-guide/configuring#specifying-parser-options) as well.

**Comment by olalonde** [comment]
For some reason, I'm unable to reproduce the bug now.

> It looks like you're using babel-eslint as your parser. Can you try using the default parser instead?

Wouldn't the default parser fail to parse es6 code?

**Comment by pedrottimark** [comment]
@olalonde The default parser supports ES6, ES7, JSX, and even experimentalObjectRestSpread. You only require babel-eslint if code has not-yet-standardized features proposed for future versions of ECMAScript.

You do need to configure the parserOptions in your ESLint configuration, as mentioned in https://github.com/eslint/eslint/issues/5997#issuecomment-215830901

http://eslint.org/docs/user-guide/configuring#specifying-parser-options

**Comment by olalonde** [comment]
Ok thanks!
