### ISSUE TITLE
Distributable codemod for updating rules to new format

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6010]
The awesome @vitorbal wrote up a jscodeshift codemod that helped us convert all of our rules into the new format. We'll announce the new format in the next release, and as part of that, it would be great to have a codemod that we could share with plugin authors to help them easily convert their rules.

What I'm thinking is:

1. The codemod itself
2. Some instructions on how to install jscodeshift
3. Some instructions on how to use the codemod with jscodeshift on their machine

Open questions:

* Do we want to create a separate ESLint org repo for codemods? (Might we have more of them in the future?) I'm thinking yes, but would like to hear other thoughts.

**Comment by ilyavolodin** [comment]
I think separate repo is a good idea. Repositories are free, so no need to save on them, and it's easier to organize information that way. We might also have additional tooling in the future (I'm thinking, for example, scripts to create quick documentation based on metadata for plugins).

**Comment by kaicataldo** [comment]
I think a separate repo makes sense here, especially if we might have more in the future. That way all the  codemods and relevant documentation can live in one place.

**Comment by sindresorhus** [comment]
You might want to check out https://github.com/jfmengels/lib-upgrader

-

// @jfmengels

**Comment by jfmengels** [comment]
Explaining what @sindresorhus thought of: what the AVA team did, is write all the codemods in a [separate project](https://github.com/jamestalmage/ava-codemods), and add a cli to it. I started exporting the whole CLI creation logic to https://github.com/jfmengels/lib-upgrader, so that any team can easily create a CLI for their codemods (and avoid having users install `jscodeshift` and launch every script manually). I haven't finished it (well, it's working, but had some feedback to make it much better, in breaking ways), but would be happy to prioritize it if you guys are interested in this.

I would definitely advise a separate repo. It's a lot of stuff that you do not necessarily want in ESLint, no need to cumber the project for what users may or may not run, and then only once.

**Comment by vitorbal** [comment]
FWIW, [here](https://gist.github.com/vitorbal/18f75cb8643e51c3540b344a67c4ddb3)'s the original codemod that I used to migrate the core rules.

Here are some of the current open issues to address before the original codemod could be considered stable enough, in my opinion:
- There's currently a bug where the transform moves the schema definition above a variable declaration that was needed by the schema definition. I'll work on that first this week.
- The transform doesn't know how to tell if a rule should have the `fixable` property or not. I suppose all we have to do is check for the `fix` function inside `context.report`, but how to differentiate between "whitespace" or "code" type of fixable?
- The `docs` key is filled via a rule mapping object in the original codemod. For the version we will share with plugin authors, would an empty object be acceptable as a "placeholder" `docs` property?

**Comment by nzakas** [comment]
@sindresorhus @jfmengels thanks for the pointer, we will be sure to check it out. 

@vitorbal I think we can default "fixable" to "code" and then tell people to double-check. There's no functional difference between the two now, so guessing wrong isn't that big of a deal. 

For "docs", you can just leave that as an empty object. It's not required for the rule to work.

**Comment by vitorbal** [comment]
@nzakas @ilyavolodin I created a placeholder repository and opened a pull request to get some feedback on what I got so far: https://github.com/vitorbal/eslint-transforms/pull/1
Let me know what you think!

**Comment by vitorbal** [comment]
@nzakas @ilyavolodin closing this since we got the initial version up and running in https://github.com/eslint/eslint-transforms
