### ISSUE TITLE
Replace calls to deprecated rule-context methods

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6029]
There are a number of deprecated methods in `rule-context` we still use internally that we should replace with the new ones.

I'll do it.

**Comment by alberto** [comment]
@eslint/eslint-team Do we intend to remove these methods in some future release? If so, is the doc notice about deprecation enough? Should we add some kind of warning [here](https://github.com/eslint/eslint/blob/master/lib/rule-context.js#L153) for people using them or would that cause more harm than good?

**Comment by nzakas** [comment]
I'm not a fan of outputting messages to the console because it affects the output for all users. We can probably do a formal deprecation blog post.
