### ISSUE TITLE
New rule: newline-before-var

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#6031]
Add new rule: newline-before-var (similar to http://eslint.org/docs/rules/newline-after-var)

Warns when there is no new line before a variable declaration. Exceptions: (1) beginning of scope, (2) precedes another variable declaration.

> When the rules will warn. Include a description as well as sample code.

Will warn:

```js
foo();
const bar = 'BAR';
```

Will not warn:

```js
foo();

const bar = 'BAR';
const bar = 'BAR';
```

```js
{
    const bar = 'BAR';
    const bar = 'BAR';
}
```

> Whether the rule prevents an error or is stylistic.

Stylistic.

> Why the rule should be in the core instead of creating a custom rule.

It is an extension of an existing rule.

> Are you willing to create the rule yourself?

No.

**Comment by kaicataldo** [comment]
Closing this because we haven't made progress in more than 21 days. Thanks for contributing!
