### ISSUE TITLE
Inconsistent typography and terminology in `indent` documentation

### ISSUE THREAD

**Issue by Trott** [eslint/eslint#6045]
**What version of ESLint are you using?**

master branch

**What parser (default, Babel-ESLint, etc.) are you using?**

n/a

**Please show your full configuration:**

n/a

**What did you do? Please include the actual source code causing the issue.**

Markdown documentation is not consistent about putting configuration options like `SwitchCase` in backticks. It is also a bit loose in that it uses that term to mean `case` clauses in `switch` statements. I'm not sure the typical user will understand that terminology use. (Perhaps it comes from the AST?)

**What did you expect to happen?**

I expected the markdown to be consistent in its usage of typography and precise in its usage of terminology. (Sorry if that sounds persnickity. Not meant that way. Just trying to not put `n/a` for everything.)

**What actually happened? Please include the actual, raw output from ESLint.**

The terminology and typography is imprecise and/or inconsistent.

**Comment by kaicataldo** [comment]
Thanks - linking to this comment for posterity: https://github.com/eslint/eslint/pull/6044#issuecomment-216397657
