### ISSUE TITLE
arrow body style 

### ISSUE THREAD

**Issue by willin** [eslint/eslint#6047]
**What version of ESLint are you using?**

**What parser (default, Babel-ESLint, etc.) are you using?**

```json
  "devDependencies": {
    "babel-eslint": "^5.0.0",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-plugin-react": "^4.2.2"
  }
```

**Please show your full configuration:**

```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "parser": "babel-eslint",
  "rules": {
    "quotes": [2, "single"],
    "semi": 2,
    "max-len": [1, 150, 2],
    "arrow-body-style": [1, "as-needed"],
    "comma-dangle": [2, "never"],
    "object-curly-spacing": 0,
    "no-console": 1,
    "no-param-reassign": [1, { "props": false }],
    "consistent-return": 1
  },
  "extends": "airbnb/base"
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
exports.reply = () => {
     test: 'blablabla'
};
```

> ESLint Error Fatal Parsing error

**What did you expect to happen?**

no err, no warn

**What actually happened? Please include the actual, raw output from ESLint.**

```js
exports.reply = () => {
  return {
       test: 'blablabla'
  };
};
```

> ESLint Warning arrow-body-style

```js
exports.reply = () => {
     test: 'blablabla'
};
```

> ESLint Error Fatal Parsing error

**Comment by mysticatea** [comment]
Thank you for this issue.

This is an intentional behavior.
You can fix the code:

```js
exports.reply = () => ({
     test: 'blablabla'
});
```

**Comment by willin** [comment]
@mysticatea 

as far as i can understand:

```
exports.reply = () => {
  return {
       test: 'blablabla'
  };
};
```

any other better way?

**Comment by michaelficarra** [comment]
@willin: @mysticatea already showed you the better way.

**Comment by willin** [comment]
sorry...
