### ISSUE TITLE
Rule Proposal: comment-capitalizing

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6055]
From [requireCapitalizedComments](http://jscs.info/rule/requireCapitalizedComments) and [disallowCapitalizedComments](http://jscs.info/rule/disallowCapitalizedComments).

This rule will enforce which the first character is an upper case or a lower case.

``` js
{
    "comment-capitalizing": ["error", "always" or "never"],
    // or
    "comment-capitalizing": [
        "error",
        {
            "capitalize": "always" or "never",
            "markers": ["*"],
            "ignorePattern": "^\s*(?:eslint|jshint|jslint|istanbul|global|exported|jscs|falls?\s?through)",
            "ignoreInlineComments": false,
            "overrides": {
                "block": null,  // e.g. "always", {capitalize: "always", markers: ["!"]}, ...
                "line": null
            }
        }
    ]
}
```
- `"always"` (default) - Requires the first alphabetical character of a comment to be uppercase, unless it is part of a multi-line textblock.
- `"never"` - Requires the first alphabetical character of a comment to be lowercase.
- `markers` (default is `["*"]`) - If the head of comments matched to markers, this rule cut the matched part off, then checks the comment capitalizing. (this is similar to [the markers option of spaced-comment rule](http://eslint.org/docs/rules/spaced-comment#markers))
- `ignorePattern` (default is `"^\s*(?:eslint|jshint|jslint|istanbul|global|exported|jscs|falls?\s?through)"`) - If the comment content (except the part that `markers` option has matched) matches the given regexp pattern, this rule ignore the comment.
- `ignoreInlineComments` (default is `false`) - If this is `true`, this rule will be applied to only comments which are at the head of each line. (from `requireCapitalizedComments`'s `inlined` option)
- `overrides` - People can override setting for each line or block comment.

**Comment by akuznetsov-gridgain** [comment]
+1 From me. Also it is possible to add to this rule a check for "." at the end of comment?

**Comment by platinumazure** [comment]
@akuznetsov-gridgain I would suggest creating a separate issue for your request. (In your issue, please note if there is a JSCS equivalent or not, so we know whether or not we should treat the new issue as JSCS compatibility related or not.)

Also, I'd like to try implementing this (goal is to do so by this weekend). Assigning to myself for now.

**Comment by platinumazure** [comment]
@mysticatea Any idea how to handle non-ASCII characters? What about non-letters, should those trigger the rule under any circumstances or not?

**Comment by platinumazure** [comment]
@eslint/eslint-tsc I don't know if we still want to expedited-accept JSCS issues or if we should go through the same process as usual. I have a couple of open questions about non-ASCII and non-letter characters, but this otherwise seems like an actionable proposal and I think this should be accepted.

**Comment by alberto** [comment]
I think default `ignoreWords` should always be applied. I don't think this should even be an option like in https://github.com/eslint/eslint/issues/6077

**Comment by nzakas** [comment]
@platinumazure we should try to follow the regular process here, do you can champion it.

**Comment by mysticatea** [comment]
@platinumazure In Japanese, we don't have upper/lower cases. This rule simply should ignore Japanese letter. (though I'm not sure about other languages). I think `text[0] === text[0].toLocaleUpperCase()` is good. This check would become `true` if the `text` starts with an uppercase letter or a case-less letter.

**Comment by mysticatea** [comment]
Ah... This rule should skip [markers](http://eslint.org/docs/rules/spaced-comment#markers). It may need `markers` option, or simply it would skip symbol letter at the head of comments.

**Comment by platinumazure** [comment]
Okay, by my count of :+1:'s on my champion comment, I think this is ready to roll. I'll try to get this out within the next week or so. (I'm moving house on Friday, though, so my life will be chaotic for the next few days.)

**Comment by platinumazure** [comment]
Started working on this. It'll be another day or two before I have a branch up, but I've already got some questions:

* [ ] onlyHeader/inline option: I looked at the JSCS page and I'm wondering if inline actually means a block comment embedded in a line of code? (For example, `function doFoo(a, /* bar */ b) {}`) Can anyone provide some insight here?
* [ ] ignoreWords: Should the default ignoreWords be always ignored by default, or should it be possible to remove those defaults by specifying an array without them? (And if the latter, do we really want to allow that for "eslint" in particular, since it could mean all inline config comments would be reported?)
* [ ] What about JSDoc comments? Should those be factored in here, ignored entirely, or should we add an option to include/exclude them from this rule? (Should the valid-jsdoc rule be separately enhanced to validate initial capitalization of various parts of JSDoc comments? To me that seems like the best approach for JSDoc. Either way, I still need to know what to do with JSDoc comments in this rule.)

**Comment by nzakas** [comment]
Inline - yes, that's what it means.

IgnoreWords - I think we should always ignore the four defaults and not allow them to be unignored (so they shouldn't be part of configuration, only internal).

JSDoc comments are treated the same as any other.

**Comment by nzakas** [comment]
@markelog can you double check what I said?

@platinumazure I think the JSCS unit tests are a good resource when questions come up: https://github.com/jscs-dev/node-jscs/blob/master/test/specs/rules/require-capitalized-comments.js

**Comment by platinumazure** [comment]
@nzakas I'd like to propose a modification to @mysticatea's proposal in that case:

* onlyHeader option to be renamed to ignoreInlineComments, with the values still being boolean, default false, and having the same meaning as the proposal.

**Comment by mysticatea** [comment]
@platinumazure I'm sorry for my slow response. I have missed notification.

I edited the first post by some suggestions.

- `markers` option was added.
- `onlyHeader` option was renamed to `ignoreInlineComments`. And I'm sorry, I have misunderstood original `inlined` option. This option restricts the rule to apply only comments which are at the head of each line. (https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-capitalized-comments.js#L208-L217)
- `ignoreWords` was changed to `ignorePattern`. This option is same as #6077's for consistency.

**Comment by markelog** [comment]
> Inline - yes, that's what it means.

Yeah, it is even mentioned in the valid/invalid rule examples.

On the side note, right now, I would just implement JSCS options and consider implementing others if there would be sufficient enough amount of users to want them

**Comment by platinumazure** [comment]
Started work on this. Documentation is pretty much done (well, unless we want more examples of different combinations of options). Rule logic seems to be done, now I'm just writing test cases and squashing bugs. I'll get a branch up this weekend once I've made some more progress.

@eslint/eslint-tsc Strong opinions on whether to include `markers` at this point, based on @markelog's comment [here](https://github.com/eslint/eslint/issues/6055#issuecomment-240784690)?

**Comment by platinumazure** [comment]
I've been beavering away at this for the last couple of days, and I think I'll have a PR (re)opened tomorrow.

Decisions I've made unilaterally (subject to discussion in the PR):

* Not adding markers (unnecessary for JSCS compatibility)
* Ensuring comments that begin with URLs don't get reported

Still left:

* Implement "textblock" support
  * "Textblock" is the term JSCS used for consecutive comments, be they line or block. The rule will not report the second or later comment in a "textblock" as long as the first comment follows the rule.
  * To me, this is kind of weird default behavior (users can use block comments for multiple lines usually), especially with consecutive block comments, so I'm going to put this behind an option.

The "textblock" bit should be the last thing I need to do before it's ready for review.

**Comment by platinumazure** [comment]
New PR is open: #7415.
