### ISSUE TITLE
Rule Proposal: jquery-dollar

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6057]
From [requireDollarBeforejQueryAssignment].

This rule will enforce variable names start with `$` if the variable is initialized with a jQuery object.
I think this rule should be in [eslint-plugin-jquery].

```js
{
    "jquery-dollar": ["error", {"ignoreProperties": false}]
}
```

- `ignoreProperties` (default is `false`) - If this is `true`, this rule will ignore property names.

[requireDollarBeforejQueryAssignment]: http://jscs.info/rule/requireDollarBeforejQueryAssignment
[eslint-plugin-jquery]: https://github.com/dgraham/eslint-plugin-jquery

**Comment by platinumazure** [comment]
I agree that this should probably be in a plugin.

Here's an interesting question for @nzakas: How does this proposal for JSCS Compatibility mesh with our goals of being library-agnostic? Should we really put this rule into core? Or does the library-agnostic rule trump JSCS Compatibility (as long as we work to get the JSCS rule in the right plugin)?

**Comment by nzakas** [comment]
I think our goal is to ensure compatibility with JSCS while still following our own guidelines. So in this case, I agree that this rule should be in a plugin. We can always point to the plugin as part of the JSCS compat documentation.

**Comment by doberkofler** [comment]
+1

**Comment by nzakas** [comment]
That said, we should be sure to find a plugin home for this rule before we close this issue.

**Comment by lo1tuma** [comment]
There is already a plugin for this: [eslint-plugin-dollar-sign](https://github.com/erikdesjardins/eslint-plugin-dollar-sign).

**Comment by zxqfox** [comment]
I'm wondered why `eslint-plugin-jquery` is for "Disallow jQuery functions with native equivalents". It should be called `eslint-plugin-no-jquery` 😕

**Comment by nzakas** [comment]
Thanks @lo1tuma!

@zxqfox I was wondering the same thing.

**Comment by kaicataldo** [comment]
How do we want to proceed with this, since the plugin already exists? Do want to just close this or do we need to track it elsewhere so we remember to point users to the plugin?

**Comment by nzakas** [comment]
We should track it somewhere. Maybe just add an entry on @mysticatea's spreadsheet?

**Comment by mysticatea** [comment]
I updated [my spreadsheet](https://docs.google.com/spreadsheets/d/1-XoW_kb4nU1-Zh_5tvjdgQaeAT9RmKX-H5QZfOizHyY/edit?usp=sharing).

**Comment by nzakas** [comment]
Ok, closing as there's no work to do here.
