### ISSUE TITLE
Proposal: new "clang" report formatter

### ISSUE THREAD

**Issue by aparajita** [eslint/eslint#6064]
I'd like to propose that you include my clang-style formatter with the eslint distro. I'll be happy to maintain it.

https://github.com/cappuccino/eslint-clang-formatter

**Comment by ilyavolodin** [comment]
I think this is a cross between our standard stylish formatter and JSCS formatter that will be ported to ESLint.

**Comment by aparajita** [comment]
Yes, sort of, but that was why I created it. The stylish formatter provides no context info and the JSCS formatter is way too verbose. Also, my formatter allows the colors to be customized.

**Comment by nzakas** [comment]
Hmm, I'm not sure there's a lot of value in including this in the core if you already have it as a separate package. I think it would be best if you maintain this as a separate package. Once we do #5900, it will be even easier for people to use.

**Comment by aparajita** [comment]
Once #5900 is done, then it would make sense to keep it separate. But the main reason I asked to include it in the main distro is discoverability. Currently you mention that third party formatters are possible, but don't provide any links or even suggestions how to find them. I propose to have a curated list of third party formatters [here](http://eslint.org/docs/user-guide/formatters/).

**Comment by nzakas** [comment]
Discoverability is a problem for configs and plugins as well. We don't have a good solution for that yet. I don't think just adding a list to the formatters page makes much sense, so I'd rather hold off until we have a chance to look at discoverability across the board.

**Comment by aparajita** [comment]
Fair enough, then I'll close this.
