### ISSUE TITLE
Rule Proposal: sort-keys

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6076]
From [validateOrderInObjectKeys].

This rule will enforce the order of object properties by their names.

```js
{
    "sort-keys": [
        "error",
        "asc" or "desc",
        {
            "insensitive": false,
            "natural": false
        }
    ]
}
```

- `"asc"` (default) - Requires sorting in ascending order.
- `"desc"` - Requires sorting in descending order.
- `insensitive"` (default is `false`) - If this is `true`, this rule compares keys in case-insensitive.
- `natural"` (default is `false`) - If this is `true`, this rule compares keys in natural order.

[validateOrderInObjectKeys]: http://jscs.info/rule/validateOrderInObjectKeys

**Comment by jedwards1211** [comment]
Note that some major libraries (e.g. React's transition group) rely on the de-facto preservation of object property ordering.

**Comment by platinumazure** [comment]
@jedwards1211 Of course, those folks don't need to turn on this rule. :smile:

**Comment by jacobrask** [comment]
For reference, see this plugin https://github.com/jacobrask/eslint-plugin-sorting

**Comment by ilyavolodin** [comment]
I'll support it, :+1:

**Comment by btmills** [comment]
The proposed options make sense to me. :+1:

**Comment by nzakas** [comment]
Per TSC meeting (7/21/16), marking as accepted.

**Comment by mysticatea** [comment]
I will work on this.
