### ISSUE TITLE
Rule Enhancement Proposal: space-infix-ops with never and overrides

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6081]
From:
- [disallowSpaceAfterBinaryOperators](http://jscs.info/rule/disallowSpaceAfterBinaryOperators)
- [requireSpaceAfterBinaryOperators](http://jscs.info/rule/requireSpaceAfterBinaryOperators) 
- [disallowSpaceBeforeBinaryOperators](http://jscs.info/rule/disallowSpaceBeforeBinaryOperators)
- [requireSpaceBeforeBinaryOperators](http://jscs.info/rule/requireSpaceBeforeBinaryOperators)
- [disallowSpacesInConditionalExpression](http://jscs.info/rule/disallowSpacesInConditionalExpression)
- [requireSpacesInConditionalExpression](http://jscs.info/rule/requireSpacesInConditionalExpression)

This proposal is to add some options to [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops).

``` js
{
    "space-infix-ops": ["error", "always" or "never"],
    // or
    "space-infix-ops": ["error", {
        "after": "always" or "never",
        "before": "always" or "never",
        "int32Hint": false,
        "overrides": {
            "*": null, "/": null, "%": null, "+": null, "-": null, "<<": null, 
            ">>": null, ">>>": null, "<": null, "<=": null, ">": null, ">=": null, 
            "in": null, "instanceof": null, "==": null, "!=": null, "===": null, "!==": null,
            "&": null, "^": null, "|": null, "&&": null, "||": null, "=": null,
            "+=": null, "-=": null, "*=": null, "/=": null, "%=": null, "<<=": null,
            ">>=": null, ">>>=": null, "&=": null, "^=": null, "|=": null, "?": null,
            ":": null, ",": null, "**": null, "**=": null
        }
    }]
}
```
- `"always"` (default) - Requires spacing around infix operators. This is the current behavior.
- `"never"` - Disallow spacing around infix operators.
- `after` (default is `"always"`) - Setting of spacing after operators.
- `before` (default is `"always"`) - Setting of spacing before operators.
- `overrides` - People can override settings for each operator. For example
  
  ``` js
  {
      "space-infix-ops": ["error", {
          "after": "always",
          "before": "always",
          "overrides": {
              "**": "never" // or {"before": "never", "after": "never"}
          }
      }]
  }
  ```

**Comment by ilyavolodin** [comment]
Is this something we want to add? Can somebody provide an example of why you would want space before infix operator but not after? I do like `overrides` though.

**Comment by mysticatea** [comment]
I don't mind to remove the `before/after` option, though, my coworker prefers `condition? value : anotherValue`-like style.

**Comment by platinumazure** [comment]
Well, if we want to be JSCS-compatible, I don't know if we have much choice but to support before and after. @ilyavolodin Does our "JSCS-compatible" goal allow us to avoid adding options we don't think we need, even if it means the original JSCS rules are not fully implemented in ESLint?

**Comment by ilyavolodin** [comment]
@platinumazure We already skipped a few rules that were jQuery specific, that were implemented in JSCS. So I think we should evaluate all options before blindly accepting a feature.

**Comment by platinumazure** [comment]
Awesome- I didn't realize we had precedent.

In that case, my vote is to avoid before/after until we have people
demanding it.

**Comment by platinumazure** [comment]
I think a PR (with accepted proposal) is already in the works here: #7591. Should we label the PR or other issue as JSCS-compat?

**Comment by kaicataldo** [comment]
@platinumazure Seems reasonable to me

**Comment by kaicataldo** [comment]
What is the status of this?

**Comment by not-an-aardvark** [comment]
I think the most recent discussion about it is in https://github.com/eslint/eslint/issues/7489.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
