### ISSUE TITLE
Rollup: whitespace rules

### ISSUE THREAD

**Issue by doberkofler** [eslint/eslint#610]
A rule to guarantee consistent whitespaces like (or even better) than the white rule in JSLint would be most appreciated.
I'm pretty much ok with the way how JSLint works but a more configurable and better documented rule or set of rules could be a nice improvement over JSLint and attract more people.

**Comment by nzakas** [comment]
I believe we've covered all cases in this issue now. We do have some outstanding bugs in the indentation rule, but otherwise I think we can call this "done".
