### ISSUE TITLE
Confusing error message when extending non-existing plugin config

### ISSUE THREAD

**Issue by ganimomer** [eslint/eslint#6115]
**What version of ESLint are you using?**
2.9.0
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

``` js
{
  "parser": "babel-eslint",
  "plugins": ["lodash"],
  "extends": ["plugin:lodash/recommend", "eslint-config-airbnb"],
  "rules": {
    "indent": [2, 2, {"SwitchCase": 1}],
    "no-console": [0],
    "func-names": [0],
    "semi": [2, "never"],
    "no-extra-semi": [2],
    "space-before-function-paren": [2, "always"],
    "no-else-return": [0],
    "space-infix-ops": [0],
    "react/prefer-es6-class": [0],
    "react/prefer-stateless-function": [0]
  },
  "globals": {
    "Bugsnag": true,
    "FS": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
This was originally an issue for the Lodash plugin, wix/eslint-plugin-lodash#76.
The user ran ESLint with the config, extending from `lodash/recommend` instead of `lodash/recommended`.
**What did you expect to happen?**
An error similar to the one when extending a non-existing module.
For instance:

``` bash
Error: Cannot find config 'plugin:lodash/recommened' from '...'
Referenced from: <config file>
    <call stack>
```

**What actually happened? Please include the actual, raw output from ESLint.**

```
 TypeError: Cannot convert undefined or null to object
Referenced from: /root/RelateRocket/webapp/.eslintrc
    at Function.keys (native)
   ...
```

**Comment by kaicataldo** [comment]
Thanks for the issue. Agreed - if we can improve this error message, we should.
