### ISSUE TITLE
Rule to warn/error when spreading an object literal into an array?

### ISSUE THREAD

**Issue by DelvarWorld** [eslint/eslint#6122]
**What version are you using?**

    $ eslint --version
        v2.9.0

    $ cat ./.eslintrc

        {
            "parserOptions": {
                "sourceType": "module",
            },
            "plugins": [
                "import"
            ],
            "rules": {}
        }

**What did you do?**

    echo 'const a = []; const b = [...a, ...{}];' | eslint --stdin

**What happened?**

Spreading an object literal into an array did not warn / error.

**What did you expect to happen?**

I accidentally typed the above into my app and it compiled (Babel) and ran fine. Tracking down the source of the error took some line by line investigation. Is this something eslint could warn about?

I couldn't find any rules that seemed relevant to this case.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
