### ISSUE TITLE
Global ESLint does not resolve local dependencies of a module defined in extends

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#6123]
**What version of ESLint are you using?**

v2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

N/A

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue.**
**What did you expect to happen?**
**What actually happened? Please include the actual, raw output from ESLint.**

#### Using module path with local install
```sh
npm install eslint
npm install eslint-config-canonical
echo '{ "extends": "./node_modules/eslint-config-canonical/eslintrc.json" }' > .eslintrc
node ./node_modules/.bin/eslint ./src
```

Works as expected (produces linting report for files contained in `./src`).

#### Using module name with local install

```sh
npm install eslint
npm install eslint-config-canonical
echo '{ "extends": "eslint-config-canonical" }' > .eslintrc
node ./node_modules/.bin/eslint ./src
```

Works as expected (produces linting report for files contained in `./src`).

#### Using module path with global install

```sh
npm install eslint
npm install eslint-config-canonical
echo '{ "extends": "eslint-config-canonical" }' > .eslintrc
/Users/gajus/.nvm/versions/node/v6.1.0/bin/eslint ./src
```

Cannot find dependency of `eslint-config-canonical`:

```
Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-no-use-extend-native". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-no-use-extend-native is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-no-use-extend-native@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Expected result:

Lint code using `eslint-config-canonical` and its dependencies.

#### Using module name with global install

```sh
npm install eslint
npm install eslint-config-canonical
echo '{ "extends": "eslint-config-canonical" }' > .eslintrc
/Users/gajus/.nvm/versions/node/v6.1.0/bin/eslint ./src
```

Complain that module "eslint-config-canonical" is not found:

```
Cannot find module 'eslint-config-canonical'
Referenced from: /Users/gajus/Documents/dev/applaudience/forward-proxy/.eslintrc
Error: Cannot find module 'eslint-config-canonical'
Referenced from: /Users/gajus/Documents/dev/applaudience/forward-proxy/.eslintrc
    at Object.ModuleResolver.resolve (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config/config-file.js:473:33)
    at load (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config/config-file.js:490:24)
    at /Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config/config-file.js:525:22)
    at loadConfig (/Users/gajus/.nvm/versions/node/v6.1.0/lib/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/gajus/.nvm/versio%
```

Expected result:

Lint code using `eslint-config-canonical` and its dependencies.

**Comment by gajus** [comment]
The problem is that with certain setups (e.g. IDE integration, https://github.com/roadhump/SublimeLinter-eslint) it is not possible to use local ESLint instance. It appears that the only workable solution at the moment is to have `eslint-config-canonical` installed globally.

**Comment by gajus** [comment]
A possible workaround would be to make global ESLint detect local install and use that to lint the files, i.e. if you run `eslint ./my-project/src/` and there is `./my-project/node_modules/.bin/eslint`, then global ESLint can dedicate linting to the local ESLint program.

**Comment by gajus** [comment]
> The problem is that with certain setups (e.g. IDE integration, https://github.com/roadhump/SublimeLinter-eslint)

Turns out I am wrong regarding this specific IDE plugin. It is possible to use local ESLint, https://github.com/roadhump/SublimeLinter-eslint#linter-installation.

Regardless, the proposal to fix the issue by delegating linting to a local ESLint instance when found remains.

**Comment by kaicataldo** [comment]
For what it's worth, it does look like you can use a local installation of the SublimeLinter-eslint plugin: https://github.com/roadhump/SublimeLinter-eslint#linter-installation

**Comment by kaicataldo** [comment]
Ha, you beat me to it.

**Comment by kaicataldo** [comment]
Also possibly of interest to you: https://github.com/mysticatea/eslint-cli

**Comment by gajus** [comment]
This is more or less the implementation I was suggesting.

Has there been a proposal to merge this into ESLint core?

**Comment by kaicataldo** [comment]
There has been discussion, but I'm not sure if consensus was met or not. I know one of the cons mentioned is that we are then burdening the user with multiple installations (the global cli helper and the local ESLint installation + plugins).

**Comment by gajus** [comment]
> There has been discussion, but I'm not sure if consensus was met or not. I know one of the cons mentioned is that we are then burdening the user with multiple installations (the global cli helper and the local ESLint installation + plugins).

In this respect, as a user, I want to be able to have ESLint installed globally when I am doing whatever small coding. However, I want to have local ESLint and ESLint version specific configuration for each project. This is esp. relevant when rules are deprecated and removed from ESLint. Local ESLint will continue to work until/ unless upgraded.

**Comment by kaicataldo** [comment]
Ah, re-read this and realized I misunderstood your question. I'm not aware of any discussions to actually add this functionality into core (for some reason I read that as moving it into the org - not the same thing!).

**Comment by nzakas** [comment]
We aren't going to merge `eslint-cli` into the core. We've made attempts before but could never come to an agreement on how to do it without causing massive confusion.

Changing dependency lookup paths is tricky, so we still recommend that you either use everything installed locally or everything installed globally.

**Comment by kaicataldo** [comment]
Appreciate you filling us in, @nzakas. I'm going to go ahead and close this. Thanks for the issue, @gajus.
