### ISSUE TITLE
`--ignore-pattern` can't uningnore files

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6127]
I think `--ignore-pattern` should be able to unignore files ignored in `.eslintignore`. Not sure if this is a bug or an enhancement.

**What version of ESLint are you using?**
2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
.eslintrc.yml
```
root: true

env:
    node: true

extends:
    "./packages/eslint-config-eslint/default.yml"
```
.eslintignore
```
/bin/**
/build/**
/conf/**
/coverage/**
/docs/**
/jsdoc/**
/templates/**
/tests/bench/**
/tests/fixtures/**
/tests/performance/**
/tmp/**
test.js
```

**What did you do? Please include the actual source code causing the issue.**
```
eslint test.js --ignore-pattern '!test.js'
```
**What did you expect to happen?**
I expected `test.js` to get linted

**What actually happened? Please include the actual, raw output from ESLint.**
```
/Users/alberto/projects/oss/eslint/test.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)
```

**Comment by mysticatea** [comment]
Sounds good to me.
I'm also not sure it's which a bug or an enhancement.

**Comment by alberto** [comment]
@eslint/eslint-team more opinions?

**Comment by mikesherov** [comment]
Thanks for contributing. Double negatives are harder to reason about than positive assertions. Do we have an `--include-pattern` option? Would that make more sense? I'd also imagine that'd be much easier to implement than the negative negative match.

**Comment by nzakas** [comment]
@mikesherov `ignore-pattern` lets you specify a pattern as if it were in `.eslintignore`, so the "ignore" is not a verb, it's a noun. 

I do think anything we support in `.eslintignore` should be possible using `--ignore-pattern` 👍

**Comment by nzakas** [comment]
Oh, and this looks more like a bug to me since inclusions work in the file.

**Comment by mikesherov** [comment]
I'll relent considering that this is a bug, but I don't buy the "it's a noun not a verb so double negative isn't a problem" argument.

Mike Sherov

**Comment by alberto** [comment]
> Do we have an `--include-pattern` option? Would that make more sense? I'd also imagine that'd be much easier to implement than the negative negative match.
Actually it would be harder, since we would have to negate it to pass it to `node-ignore`.
