### ISSUE TITLE
Build failing due to phantomjs download

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6128]
Build fails frequently due to inability to properly download phantomjs. I'll try to explain the situation.

We use [mocha-phantomjs](https://github.com/nathanboktae/mocha-phantomjs) to run [some tests](https://github.com/eslint/eslint/blob/master/tests/tests.htm) and ensure `eslint` runs in the browser. `mocha-phantomjs` depends on [phantomjs@1.9.7-15](https://github.com/nathanboktae/mocha-phantomjs/blob/master/package.json#L39) which downloads phantomjs binaries from bitbucket. bitbucket throttles downloads and fails intermitently.

There is an ongoing thread on [phantomjs](https://github.com/ariya/phantomjs/issues/13953) to use a CDN, but it is taking some time to get resolved. There are some [proposed workarounds](https://github.com/ariya/phantomjs/issues/13953#issuecomment-200862297):

> Use PHANTOMJS_CDNURL to point to http://cnpmjs.org/downloads

We have tried this a couple of times, but it is not reliable.
> Propose a feature to https://github.com/Medium/phantomjs to grab the binaries from other mirrors

https://github.com/Medium/phantomjs/releases/tag/v2.1.7 grab the binariess from github, but we can't use it because of `mocha-phantomjs`

> Create your own mirrors (perhaps even internally) and use PHANTOMJS_CDNURL to point there

We'd prefer not to have to do this.

Other issues to keep track of:
[Bump phantomjs package to latest patch version](https://github.com/nathanboktae/mocha-phantomjs/pull/231)

[Backport GitHub release changes to phantomjs 1.9.7](https://github.com/Medium/phantomjs/pull/538)

Some alternatives:
- Disable phantomjs tests temporarily.

- Run those tests separately and avoid them breaking the build.

- Cache downloads in travis and appveyor.

- [Manually download and install phantomjs](https://github.com/nathanboktae/mocha-phantomjs-core/blob/9c39524f526964cfabcf0a714f333735dd166e06/.travis.yml#L12)

**Comment by ilyavolodin** [comment]
Manual download sounds pretty interesting. Maybe we can do that and get it from CDN?

**Comment by alberto** [comment]
@ilyavolodin which CDN?

**Comment by alberto** [comment]
> Disable phantomjs tests temporarily.
Run those tests separately and avoid them breaking the build.

Just realized this doesn't make sense, since this would mean `phantomjs-prebuilt` would still be required and it would fail at download time. We'd have to remove the dependency entirely.

**Comment by ilyavolodin** [comment]
http://cnpmjs.org/downloads?

**Comment by alberto** [comment]
How would that be different from setting PHANTOMJS_CDNURL?

**Comment by markelog** [comment]
You could use that env variable to point anywhere you like, so there is lots of options where those files could be uploaded.

But i'd say this should be tmp solutions, better one is to use a real thing
