### ISSUE TITLE
Feature Request: `info` severity level

### ISSUE THREAD

**Issue by ben-page** [eslint/eslint#6139]
I love that ESLint supports multiple severity levels. This is a huge advantage over many other linters. I'd love to see this developed a little further. I think adding an additional `info` severity level would be a good improvement. Basically this would be a less severe than 'warn' . It would be used to notify about common issues that you don't want enforced and treated as a failure.

So the levels would look like this:
* `error`: should be fixed immediately (pseudo compile-time error)
* `warn`: may be ignored during prototyping, but should be fixed or disabled before committing
* `info`: notify the developer, but don't want to enforce
* `off`

There's secondary benefit to `info` as well. If a rule does not totally conform to your standards (for me `curly` is an example), setting the rule to `info` would allow you reap some benefit from the rule without having to update all of your code.

**Comment by ilyavolodin** [comment]
Currently the only difference between warn and error is that any error will return non-zero exit code and break your CI/build. Warn will not. Everything else is just difference in presentation. Since exit code can only be 0 or non-zero, I don't see what `info` level would add.

**Comment by ben-page** [comment]
The difference is only in how people interact with the output. Basically, a file containing `info` messages would "pass" and files with `warn` messages would fail. It's especially helpful when using ESLint in an editor. `error` and `warn` messages should be intrusive to encourage them to be fixed, `info` messages should not be intrusive. This is how the built-in inspections in most IDEs work.

**Comment by platinumazure** [comment]
This is an interesting idea. Currently, it is possible to flag warnings as errors using `--max-warnings=0` on the command line. That would allow for CI to be stricter than command line tools. In that case, an "info" level would not be promoted to an error.

That said, I think most API consumers of ESLint happily consume warnings and errors and can present them non-fatally if desired (e.g., in editor plugins). So I'm not sure I see the need for this per se.

**Comment by ben-page** [comment]
I really think there is a need for more granularity when enforcing rules in an organization. There are some rules in ESLint that could provide useful information to the programmer, but an organization may not want to enforce across the board.

Basically, I want to be able to tell my people to fix `error` messages immediately, to clean up all `warn` message before committing, and to take a look at `info` messages (but they can be safely ignored).

**Comment by ilyavolodin** [comment]
@eslint/eslint-team what do you think? I, personally, wouldn't use this. But then I never even set the rules to warn.

**Comment by ben-page** [comment]
From a user interface (command line or GUI), the only difference between `warn` and `info` is how they are presented. `warn` messages are more important and should be present in a more intrusive way than `info`. One could make the argument that even more granularity could be beneficial. For example, WebStorm Inspections can be Typo, Info, Weak Warning, Warning, and Error.

For the record, I don't think it's a good idea to change the numeric severity values. `0` should stay `off` and `1` is `warn` and `2` is `error`. But it would be useful to specify at least one additional string value. Internally ESLint could treat these values the same as it does `warn`. But the value would be displayed on the command line and to API consumers for display purposes.

**Comment by BYK** [comment]
We are using `warn` for the `info` described here and I'm not sure one more level would add that much value. So I'm -0.5 for this.

**Comment by IanVS** [comment]
I also don't personally see enough benefit to warrant the additional complexity.  @ben-page can you give an example of how you'd expect the various formatters to output the results of different types?  Maybe a more concrete example would help me understand your reasoning.

**Comment by markelog** [comment]
If we would want to do this, i would implement the whole RFC5424 syslog levels maybe even with ability to define your own levels, but i really don't see the point so -1.

**Comment by kaicataldo** [comment]
I'm not seeing the benefit of `info` when `warn` can be used to do essentially the same thing. I'm with @IanVS - maybe a concrete example would help me out here.

**Comment by ben-page** [comment]
I'll try to be even more specific example than I already have. I'm talking specifically about using ESLint for code analysis in an IDE. Typically (WebStorm, Netbeans, Visual Studio) errors are highlighted or squiggly-underlined in red, warnings in orange/yellow, suggestions in green, and info in blue. Additionally, colored lines are drawn near or over the scroll bar representing each message's location in the code. There is usually an icon at the top or bottom of the scroll bar that shows the most severe error. In order for that icon to go green, all errors and warnings have to be resolved. But suggestions and info messages do not.

Here's a practical example of how I would use it:

- `error` Things that are always considered an error (`eqeqeq`, `no-undef`) or you always want enforced without exception (`semi`, `linebreak-style`). So that needs to be fixed immediately and should never be disabled.
- `warn` Things that are usually a sign of problem, but you occasionally might ignore either when initially writing code (`prefer-const`, `no-empty`). Or things that aren't errors, but are usually bad practice (`no-shadow`, `guard-for-in`).
- `info` Things that could be useful to the programmer to know, but you don't consider an error (`default-case`, `require-jsdoc`, `one-var`)

So files with `error` and `warn` messages would be considered to fail the code analysis. But, for example. a file that would pass even though ESLint displayed a `default-case` message (because it's an `info`).

It seems like many of you are currently using `warn` the way that I intend to `info` to be used. So maybe the real difference above is actually the distinction between `error` and `warn`. My goal is provide more feedback to my programmers. They should know that `error` messages are never OK and `warn` messages should addressed before committing code. `info` messages are suggestions to make their code more readable or maintainable.

Eventually, I like to see ESLint plugins that take advantage of this granularity to provide feedback on many of the common pitfalls JavaScript programmers fall into (not chaining Promises, closures in a loop, etc). This is difficult with only two levels. And every IDE I've tested as three or more.

For anyone that hasn't used an IDE that does code analysis, I'm include a few screenshots that I found online.
![image](https://cloud.githubusercontent.com/assets/744035/15197008/c572b2fe-1794-11e6-849c-d63dcb6e28d3.png)
![image](https://cloud.githubusercontent.com/assets/744035/15197944/fb72db4a-1799-11e6-9851-3e922361c65c.png)
![image](https://cloud.githubusercontent.com/assets/744035/15197981/2ac8c8be-179a-11e6-905f-5b9c9c458cf3.png)

**Comment by nzakas** [comment]
@ben-page I'm sorry, there's a pretty strong consensus against doing this. As many have mentioned, what you are proposing is functionally equivalent to the "warn" use case, so it doesn't add much to ESLint.

Thanks for the suggestion.

**Comment by platinumazure** [comment]
@ben-page For the specific use case you outlined, you could use two separate configurations (one for normal development, one for CI specifically). The CI configuration would extend the main configuration but set more rules to "error" level as needed. Your "info" rules are represented by rules set to "warn" in both configurations; your "fix before check-in" rules are represented by rules set to "warn" in the main configuration and "error" in the CI configuration. You can use npm scripts to encapsulate all that, as well.

**Comment by ben-page** [comment]
That's a shame. I was hoping to use ESLint (via plugins) as a platform for
even more detailed inspections, such as spell checking and allowing NPM
modules to set warnings about common usage mistakes. Having multiple
warning levels is vital for that.

**Comment by ben-page** [comment]
@platinumazure, thank you. That's a very good idea.

**Comment by kasperpeulen** [comment]
Just saying, that I would also really love an extra level. All the argument against this seem with the idea that eslint is mostly used on the command line. But if you use it in an editor, it is very common and useful to have more levels of severity.
