### ISSUE TITLE
Proposal to change rule id-match to define different regexes for different type of declaration

### ISSUE THREAD

**Issue by geekyme** [eslint/eslint#6147]
**What version of ESLint are you using?**
latest. 2.9.0

**What rule do you want to change?**
id-match. The options should allow us to configure which regex rule to apply to which kind of declaration. Example, camelCase for `function`, PascalCase for `class`, and snake_case for variables and object properties. 

**What code should be flagged as incorrect with this change?**
Each declaration that doesn't match the specified regex should be flagged as incorrect.

**What happens when the rule is applied to this code now?**
At present `id-match` will force declarations to only belong to one type. Therefore, it is impossible to have eslint fully passing with a codebase that uses snake_case for all objects and variable declarations but camelCase and PascalCase for functions and classes respectively.

**Comment by ilyavolodin** [comment]
Hmm... Seems like a valid case, but it will bring in a lot of complexity and I'm not sure how widely used this pattern is. Would like to hear from others.

**Comment by geekyme** [comment]
This is quite common when writing new code bases that interacts with legacy code styles in large organizations. Would really like this otherwise I have trouble enforcing the code style / need to rewrite all variables to camelCase in order to have some enforcement.

**Comment by ilyavolodin** [comment]
@geekyme I'm not doubting the need for this type of options. But we are talking about including this into the core. Even if it will not be included, you always have an option to create your own rule that does exactly what you need.
The bar for inclusion into core is set very high, so we need clear justification to add new options/rule as well as somebody on the team who is willing to champion requested change.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
