### ISSUE TITLE
no-anon-event-handler

### ISSUE THREAD

**Issue by erdysson** [eslint/eslint#6151]
**When does this rule warn? Please describe and show example code:**
This rule will warn when an event is handled by an anonymous event handler such as:
`element.addEventListener("click", function() { ... /* event handler context here */ ... }`

**Is this rule preventing an error or is it stylistic?**
This rule will prevent possible errors like memory leak and continuous event handler bindings and it will be possible to alarm the unbinding event handler when no longer it is necessary

**Why is this rule a candidate for inclusion instead of creating a custom rule?**
This situation is a very common mistake among the less experienced and even for the experienced, but distracted developers
**Are you willing to create the rule yourself?**
Yes, I want to work and create this rule myself.

**Comment by BYK** [comment]
I think this is redundant since we already have http://eslint.org/docs/rules/func-names
