### ISSUE TITLE
`max-statements-per-line` max option has no minimum

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6171]
max should be >= 0

Not sure if this would qualify as a bug.

**Comment by alberto** [comment]
I had forgotten I proposed this for other similar rules: https://github.com/eslint/eslint/issues/4941 XD

**Comment by mysticatea** [comment]
Actually, `>=1`?

**Comment by alberto** [comment]
I set it to 0 to go in line with the other rules, just to be safe.

**Comment by mysticatea** [comment]
Fair enough.
