### ISSUE TITLE
Formatting in docs inconsistent

### ISSUE THREAD

**Issue by AnthonyAstige** [eslint/eslint#6181]
I've been reading over just about every rule at http://eslint.org/docs/rules/, and noticed inconsistent formatting between the individual rule pages.

For example I like how http://eslint.org/docs/rules/block-scoped-var looks with green and red highlighted blocks for good and bad.

Where as http://eslint.org/docs/rules/wrap-regex (and others) don't follow this.

Feels like the code for those pages is written by hand, and may benefit from abstraction.

**Comment by gyandeeps** [comment]
@AnthonyAstige Its a work in progress. We are moving all the old rules to that new look in installments.
I am going to close this issue for now since we are actively working on this.
Thanks
