### ISSUE TITLE
Way to enforce strict mode on ES6 modules when not implicit due to transpiling issue?

### ISSUE THREAD

**Issue by AnthonyAstige** [eslint/eslint#6184]
In my `.eslint.js` I have something like 

```
module.exports = {
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module',
        ecmaFeatures: {
            impliedStrict: false
        }
    },
    rules: {
        strict: ['error', 'global'],
        ...
    }
    ...
};
```

When I place `'use strict';` on the top of my JavaScript files ESLint gives me the error:

> 'use strict' is unnecessary inside of modules. (strict)

I was hoping this error wouldn't appear since I'm disabling the `impliedStrict` [parser option](http://eslint.org/docs/user-guide/configuring#specifying-parser-options).

However `impliedStrict` is defined as

> impliedStrict - enable global strict mode (if ecmaVersion is 5 or greater)

And I'm inside a module there, so perhaps this is a request to extend the definition of `impliedStrict` to include modules, or provide another ecmaFeatures named something like `impliedStrictModules`?

**Background**

Meteor 1.3's ecmascript module enables ES2015 support but it doesn't include implicit strict mode.

* [ESLint for Meteor 1.3 “modules” and strict mode](https://forums.meteor.com/t/eslint-for-meteor-1-3-modules-and-strict-mode/23105)
* [[1.3] Full ES2015 module support is claimed, but strict mode not on](https://github.com/meteor/meteor/issues/7050)

If this gets resolved in Meteor, I won't have a need for this rule.  However I don't think Meteor would fix this until a Major release because breaking changes.  I'm guessing other frameworks may have this issue as well if they chose not to enable strict mode in their babel parsing options.

**Comment by nzakas** [comment]
I'm sorry, ES6 modules are always parsed in strict mode, and theres no easy way to change that. `impliedStrict` only enables global strict mode, it cannot disable it.

**Comment by AnthonyAstige** [comment]
Perhaps an option could be added to the `strict` rule instead (which is where the lint error comes from).  This would make sense if this is a common enough problem across multiple frameworks.

If it's an uncommon problem, maybe only to Meteor's module implementation, then maybe an ESLint plugin with a new rule would be better.

**Comment by michaelficarra** [comment]
:-1: We do not need eslint to accommodate for a transitory bug in meteor. Hopefully for you, they will realise this is a bug and not a breaking change.

**Comment by AnthonyAstige** [comment]
@michaelficarra Yeah Meteor's implementation regarding module strict mode is counter to ES2015 spec afaict. I think this issue has been with Meteor since September 2015 ([Meteor 1.2 release](http://info.meteor.com/blog/announcing-meteor-1.2)) though, and I suspect enabling it now could break a lot of people's code. So there is a reason for them to wait for a 2.0 release, which could be a while. That said, this doesn't feel like a core ESLint responsibility to address this, so perhaps an ESLint plugin from the Meteor community instead is an appropriate interim solution.

**Comment by ilyavolodin** [comment]
I agree. Meteor plugin could just clone `strict` rule and modify it to work specifically for meteor's needs. Closing as it doesn't look like we need to address anything here.

**Comment by AnthonyAstige** [comment]
Feature request opened on eslint-plugin-meteor at [Enforce strict mode on ES6 modules when not implicit due to transpiling issue](https://github.com/dferber90/eslint-plugin-meteor/issues/208)
