### ISSUE TITLE
Rule Proposal: Disallow deprecated `__defineGetter__` and `__defineSetter__`

### ISSUE THREAD

**Issue by Trott** [eslint/eslint#6185]
**When does this rule warn? Please describe and show example code:**

This rule will warn when code uses or accesses `Object.prototype.__defineGetter__()` or `Object.prototype.__defineSetter__()`. Both are deprecated. 

* Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__
* Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineSetter__

Good:
```javascript
Object.defineProperty(obj, 'key', {
  __proto__: null
  value: 'static' 
});
```

Bad:
```javascript
o.__defineGetter__('sayHello', function() { return 'hello'; });
o.__defineSetter__('value', function(val) { this.anotherValue = val; });
```

**Is this rule preventing an error or is it stylistic?**

A little of both? Stylistic: `__defineGetter__` and `__defineSetter__` are deprecated in the ES spec and better alternatives exist. However, they are also not defined in IE so using them could be an error there.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**

Flagging deprecated functionality that is not present in all browsers would seem to be a widely-usable and desirable rule.

**Are you willing to create the rule yourself?**

Sure, here's a first pass implementation: https://github.com/Trott/io.js/blob/1d9e3faa5dbd7f5a07532c7bac1ed501ef8bb158/tools/eslint-rules/no-definegetter-definesetter.js

**Comment by michaelficarra** [comment]
:+1: I think this rule should warn about usage of all [B.2.2](https://tc39.github.io/ecma262/#sec-additional-properties-of-the-object.prototype-object) properties.

**Comment by Trott** [comment]
Added sample good and bad code.

**Comment by nzakas** [comment]
Some thoughts:

1. We have a rule baking that would allow flagging any properties by name: https://github.com/eslint/eslint/pull/5872. You could use that for this purpose. 
2. I think on its own, this rule proposal is too specific for core. 
3. A rule that flags all deprecated syntax, as @michaelficarra proposes, would be more appropriate for core, but we would likely run into people asking for all kinds of options to customize which properties were flagged. 

Given that, I'm of the mind that this is better as a plugin.

**Comment by mysticatea** [comment]
Sounds good since we have [no-proto](http://eslint.org/docs/rules/no-proto), so if `__defineGetter__`, `__defineSetter__`, `__lookupGetter__`, and `__lookupSetter__` are covered, we get covering all legacy methods of Object. Maybe `no-legacy-getter-setter`.

But #5872 is a solution as well.

**Comment by nzakas** [comment]
Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
