### ISSUE TITLE
export default from './file' throws Parsing error: Unexpected token './file'

### ISSUE THREAD

**Issue by diegohaz** [eslint/eslint#6187]
**What version of ESLint are you using?**
^2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```json
{
  "parser"  : "babel-eslint",
  "extends" : [
    "standard",
    "standard-react"
  ],
  "env"     : {
    "browser" : true
  },
  "globals" : {
    "__DEV__"      : false,
    "__PROD__"     : false,
    "__DEBUG__"    : false,
    "__COVERAGE__" : false,
    "__BASENAME__" : false
  },
  "rules": {
    "semi" : [2, "never"],
    "max-len": [2, 120, 2]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
export default from './file'
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
1:21  error  Parsing error: Unexpected token './file'
```

**Comment by nzakas** [comment]
It looks like you're using `babel-eslint` as your parser. Can you try using the default parser instead? You can just delete the `parser` from your config file to switch to the default parser. Make sure you configure the [parser options](http://eslint.org/docs/user-guide/configuring#specifying-parser-options) as well.

**Comment by michaelficarra** [comment]
It *is* a syntax error. You need curlies:

```js
export {default} from './file'
```

**Comment by platinumazure** [comment]
I think `export ... from` is still experimental and not part of the ECMAScript standard. If that's the case, then our default parser "espree" will not support that, and you need to use a different parser.

@michaelficarra Can you confirm that `export ... from` is experimental?

I see you're using `babel-eslint`, so your best option is to open an issue on that repository. At any rate, this is not an ESLint issue. Thanks!

**Comment by diegohaz** [comment]
Thank you for the answers. I see. @michaelficarra's solution works with `babel-eslint`, but I switched to this form (I think it's supported by eslint default parser, right?):
```js
import BroadcastCreateForm from './BroadcastCreateForm'
export default BroadcastCreateForm
```

**Comment by platinumazure** [comment]
@diegohaz Yes, `export ... from` is experimental and not supported in espree (default parser), but it's supported in babel-eslint.

**Comment by michaelficarra** [comment]
No, the export-from syntax I listed is valid ES2015 (meaning espree *should* parse it). The originally posted syntax is not, nor is the syntax in @diegohaz's follow-up comment.
