### ISSUE TITLE
Rule Proposal: no-useless-spread

### ISSUE THREAD

**Issue by Mouvedia** [eslint/eslint#6193]
**When does this rule warn? Please describe and show example code:**
It warns when the iterable object is inlined.

```js
// equivalent to foo(1)
foo(...[1])
// equivalent to [1]
[...[1]]
```
**Is this rule preventing an error or is it stylistic?**<del>
It is an error in the sense that's it's useless to use the spread operator in that case.</del>
Stylistic.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**
There are other rules of the same type (no-useless-) that are already part of core.

**Are you willing to create the rule yourself?**
I have done the rule and the corresponding test.

**Comment by nzakas** [comment]
Thanks for the rule submission. Can you please update your proposal to follow the guidelines in our docs? http://eslint.org/docs/developer-guide/contributing/new-rules#proposing-a-rule

(You can also click the "Create an issue" link in that section to pre-fill an issue.)

**Comment by Mouvedia** [comment]
@nzakas I have updated [the proposal](https://github.com/eslint/eslint/issues/6193#issue-154945704) using your template.

**Comment by nzakas** [comment]
Thanks! At first glance, this seems like it would be better as a plugin. (We don't accept a lot of new rules into the core because we already have so many. ) 

@eslint/eslint-team thoughts?

**Comment by mikesherov** [comment]
Belongs as plugin IMO, too much of an edge case for core.

**Comment by ilyavolodin** [comment]
Agree. I think this is better off as a plugin. I don't see people hitting this rule too often, might be just an occasional typo.

**Comment by alberto** [comment]
Agree. It doesn't cause an unexpected error, and I don't believe this would be very common

**Comment by Mouvedia** [comment]
Using a plugin entails me to have a name in the form `@pluginName/ruleName`. It's not appropriate in my case since the plugin is the rule.

IMHO if [no-useless-computed-key](http://eslint.org/docs/rules/no-useless-computed-key) is warranted I don't see why this one is not. It's the same use case more or less.

**Comment by Mouvedia** [comment]
Using a plugin entails me to have a name in the form `pluginName/ruleName`. It's not appropriate in my case since the plugin would have *one* rule.

IMHO if [no-useless-computed-key](http://eslint.org/docs/rules/no-useless-computed-key) is warranted I don't see why this one is not. It's the same use case more or less.
The only main difference in #5402, is that he considers it stylistic; would that make a difference?

@eslint/eslint-team As an alternative we could have a new all encompassing `no-useless` object rule which would cover all of these rules:

- computed-key
- spread-operator
- [assign](https://github.com/erikdesjardins/eslint-plugin-no-useless-assign)
- escape
- concat
- call
- constructor

**Comment by nzakas** [comment]
@Mouvedia we already have over 200 rules, so we aren't adding new rules unless we believe that they are very important. (More details: http://eslint.org/blog/2016/03/updated-rule-policy)

This one is clearly important to you, and that's why we let people write their own rules: so you don't have to convince us. You can either distribute your rule in a plugin or use `--rulesdir` to load your rule at runtime. (http://eslint.org/docs/user-guide/command-line-interface#specifying-rules-and-plugins)

Closing, as the team doesn't believe this is a candidate for a core rule.

**Comment by Mouvedia** [comment]
@nzakas thanks for the `--ruledir` trick.
