### ISSUE TITLE
no-extra-parens confilct with no-confusing-arrow

### ISSUE THREAD

**Issue by tomfun** [eslint/eslint#6196]
ESLint - v2.9.0 (and 2.10.1 - see below)  
parser - default  
this code:

``` javascript
          set(val) {
            let result = val;
            if (_.isArray(val)) {
              result = _.map(val, (str) => /*THERE*/(_.isString(str) ? str.replace(/\(|\)|\-|\s/g, '') : str));
            }
            this.setDataValue(fieldName, JSON.stringify(result));
          }
```

 -- give "no-extra-parens" error.

and this:

``` javascript
          set(val) {
            let result = val;
            if (_.isArray(val)) {
              result = _.map(val, /*THERE*/(str) => _.isString(str) ? str.replace(/\(|\)|\-|\s/g, '') : str);
            }
            this.setDataValue(fieldName, JSON.stringify(result));
          }
```

 -- give "no-confusing-arrow" error

``` json
    "no-confusing-arrow": [
      2,
      {
        "allowParens": true
      }
    ],
    "no-extra-parens": [
      2,
      "all",
      {
        "conditionalAssign": true,
        "nestedBinaryExpressions": false
      }
    ],
```

 -- part of configuration

I already have tried update ESlint to 2.10.1, and change configuration to:  

```
    "no-extra-parens": [
      2,
      "all",
      {
        "conditionalAssign": false,
        "nestedBinaryExpressions": false,
        "returnAssign": false
      }
    ],
```

It did not help.  
I expect, that "no extra parens" error would not appear in that case.

**Comment by nzakas** [comment]
Can you please use our issue template? https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by tomfun** [comment]
Tried to update issue, Is that good enough?

**Comment by nzakas** [comment]
That's better, in the future, please use the issue template. 

I don't see a way to satisfy both rules right now. @eslint/eslint-team thoughts?

**Comment by platinumazure** [comment]
I would say we should enhance `no-extra-parens` to support allowing "extra" parens around a complex single-expression arrow function body. (`no-confusing-arrow` is being flagged here because the arrow could be a mistaken `>=` token which then makes sense in a conditional expression, so I assume the intent of `no-confusing-arrow` is to require parentheses to disambiguate.)

**Comment by alberto** [comment]
Isn't this solved by https://github.com/eslint/eslint/issues/5332 ?

**Comment by nzakas** [comment]
Good point. @tomfun can you try upgrading to the latest version and using the new option: http://eslint.org/docs/rules/no-confusing-arrow#options

**Comment by tomfun** [comment]
@nzakas I updated eslint, it doesn't help.
![http://joxi.ru/D2P6EPesdNpnGr](http://joxi.ru/D2P6EPesdNpnGr.jpg)
Of course I used old configuration:

>     "no-confusing-arrow": [
>       2,
>       {
>         "allowParens": true
>       }
>     ],
>     "no-extra-parens": [
>       2,
>       "all",
>       {
>         "conditionalAssign": true,
>         "nestedBinaryExpressions": false
>       }
>     ],

**Comment by tomfun** [comment]
@platinumazure It is all I want: add option to *no-extra-parens*  
@nzakas So will you change label from *question* to something like extra feature?

**Comment by nzakas** [comment]
@platinumazure can you provide more details about what you are proposing? What qualifies as "complex"?

**Comment by tomfun** [comment]
```json
"no-extra-parens": [
  2,
  "all",
  {
    "conditionalAssign": true,
    "nestedBinaryExpressions": false,
    "confusingArrow": true
  }
],
```
**confusingArrow**  
And maybe add *conflict* details or *when-not-to-use-it* to [docs](http://eslint.org/docs/rules/no-extra-parens)

**Comment by MethodGrab** [comment]
I'm also experiencing this problem:

**What version of ESLint are you using?**
v3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```js
/* eslint-env es6 */
/* eslint no-confusing-arrow: [ "error", { allowParens: true } ], "no-extra-parens": [ "error", "all", { conditionalAssign : false, returnAssign : false, nestedBinaryExpressions : false } ] */
```

**What did you do? Please include the actual source code causing the issue.**
Consider the following examples:

```js
/* eslint-env es6 */
/* eslint no-confusing-arrow: [ "error", { allowParens: true } ], "no-extra-parens": [ "error", "all", { conditionalAssign : false, returnAssign : false, nestedBinaryExpressions : false } ] */

// this correctly warns about `no-extra-parens`
var a1 = ( 1 );

// this correctly warns about `no-confusing-arrow`
var b1 = x => x ? 1 : 2;

// Expected: this should be valid (as per http://eslint.org/docs/rules/no-confusing-arrow#options)
// Actual: it warns about `no-extra-parens`
var c1 = x => ( x ? 1 : 2 );

/* eslint-disable no-extra-parens */
// this now works fine, no warnings
var c2 = x => ( x ? 1 : 2 );
/* eslint-enable no-extra-parens */
```

**What did you expect to happen?**
The above test file should output **2** errors, for lines 5 & 8.
`var c1 = x => ( x ? 1 : 2 );` should be valid with both `no-confusing-arrow` & `no-extra-parens` enabled.

**What actually happened? Please include the actual, raw output from ESLint.**
`var c1 = x => ( x ? 1 : 2 );` triggered the `no-extra-parens` warning message.

```
~/dev/test-cases/eslint-conflict-6196/test.js
   5:10  error  Gratuitous parentheses around expression                       no-extra-parens
   8:10  error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow
  12:15  error  Gratuitous parentheses around expression                       no-extra-parens

✖ 3 problems (3 errors, 0 warnings)
```

**Comment by kaicataldo** [comment]
@eslint/eslint-team Do we want to support this change? It's been a while since the last comment, but seems like we should at least discuss

**Comment by delijah** [comment]
I am also having troubles with those conflicting rules!

**Comment by evilebottnawi** [comment]
@kaicataldo I am too having troubles with those conflicting rules! I love parenthesis around function argument and use ternary.
```js
defer((config) => (config.exist ? 'exist : 'not-exist'))
```

**Comment by kaicataldo** [comment]
I'm closing this issues because it looks like consensus couldn't be reached. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never reach consensus, and as a team have decided to close such issues. This doesn't mean the idea isn't interesting or valuable, only that it's not something the team can commit to at the moment.

**Comment by edoroshenko** [comment]
It's not wise to leave the problem without resolution. It could be solved later, priority could be decreased, but it should be solved eventually.
For now we had (as well as whoever has) to get rid of one of those rules. It's sad.

**Comment by evilebottnawi** [comment]
@edoroshenko i can try resolve this issue today, have some time for this :smile:

**Comment by edoroshenko** [comment]
@evilebottnawi would be awesome :)

**Comment by sleeparrow** [comment]
PSA for people who stumble on this issue in the future - it was fixed. This may be the configuration you are looking for:

```
"no-confusing-arrow": ["error", {"allowParens": true}],
"no-extra-parens": ["error", "all", {"enforceForArrowConditionals": false}],
```
