### ISSUE TITLE
Whats the difference between "build" and "chore" (git commit guidelines)

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#6221]
http://eslint.org/docs/developer-guide/contributing/pull-requests#step2

> * Build - changes to build process only.
> * Chore - for refactoring, adding tests, etc. (anything that isn’t user-facing).

It seems like Chore covers Build most of the time, e.g. aren't tests part of the build process?

**Comment by nzakas** [comment]
Build has to do with strictly with the build process - creating a new build task, updating the release script. Basically, "Build" is for changes to `Makefile.js`.

Everything else is a chore.

**Comment by nzakas** [comment]
By the way, can you please ask questions like this in the chatroom? It saves us time from triaging issues. Thanks
