### ISSUE TITLE
no-multiple-empty-lines fixer

### ISSUE THREAD

**Issue by RRMoelker** [eslint/eslint#6225]
The no-multiple-empty-lines rule does not yet have a fixer for auto removing extra lines. I would like to have a fixer to remove these lines where applicable.

I already made the code to solve this issue. I'll link the PR a.s.a.p.

**Comment by nzakas** [comment]
Sounds good!

**Comment by ThomasCrvsr** [comment]
Hello ! I just had few problems today regarding the last version of eslint and found that it's related to this PR.

Should we also cover the case where the `.match()` call returns null ? 
https://github.com/eslint/eslint/blob/5122f738dc6bdc85c602758b2fa3560c1ac5dceb/lib/rules/no-multiple-empty-lines.js#L81

This would avoid error when executing this line :
https://github.com/eslint/eslint/blob/5122f738dc6bdc85c602758b2fa3560c1ac5dceb/lib/rules/no-multiple-empty-lines.js#L101

What do you think about this ? :)

**Comment by vitorbal** [comment]
hey @ThomasCrvsr, thanks for reaching out! Indeed that's what we are doing now to prevent the problems you mention: https://github.com/eslint/eslint/issues/6449
We are planning to do a patch-release today and this fix should be included, let us know if you still have any problems after that!

**Comment by ThomasCrvsr** [comment]
@vitorbal Thanks your answer !
