### ISSUE TITLE
Option for not indenting the body of closure that wrap entire file

### ISSUE THREAD

**Issue by wojdyr** [eslint/eslint#6259]
This is a follow up of https://github.com/eslint/eslint/issues/632#issuecomment-221071694
I'm opening a new issue for this as requested.

Consider adding an option for not indenting the top-level function.

[jquery guide](https://contribute.jquery.org/style-guide/js/):

> If the entire file is wrapped in a closure, the function body is not indented.

[google guide](https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting):

> Similar to C++ namespaces, do not indent under goog.scope declarations. Instead, continue from the 0 column.

with such an example:
```
goog.provide('my.module.SomeType');

goog.require('goog.dom');
goog.require('goog.ui.Button');

goog.scope(function() {
var Button = goog.ui.Button;
var dom = goog.dom;

// Alias new types after the constructor declaration.
my.module.SomeType = function() { ... };
var SomeType = my.module.SomeType;

// Declare methods on the prototype as usual:
SomeType.prototype.findButton = function() {
  // Button as aliased above.
  this.button = new Button(dom.getElement('my-button'));
};
...
});  // goog.scope
```

I'm not following these guides, but I also like to not indent the top-level namespace-function in my petty projects.

**Comment by platinumazure** [comment]
Can you clarify the enhancement request you're making here?

Do we want an `indent` option which simply ignores the first level of indentation throughout the file, requiring the first "indentation level" to have no extent and then revert to normal indentation thereafter?

**Comment by wojdyr** [comment]
Yes.
Even better if the first level of indentation was ignored only when inside a function, i.e. like this
```
if (foo) {
    // normal indent
}
function () {
// no indent
}();
```

**Comment by davidshepherd7** [comment]
I'm interested in implementing this, although I don't know much about eslint so who knows if I'll succeed. I thought a good first step would be to write the documentation for what I'm aiming to implement. Anyone got any feedback on this?



### IndentOuterfunction

Examples of **incorrect** code for this rule with the options `2, { "IndentOuterfunction": false }`:

```js
/*eslint indent: ["error", 2, { "IndentOuterfunction": false }]*/

(function() {

  function foo(x) {
    return x + 1;
  }

})();

function() {

  function foo(x) {
    return x + 1;
  }

}();

if(y) {
console.log('foo');
}
```

Examples of **correct** code for this rule with the options `2, {"IndentOuterfunction": false}`:

```js
/*eslint indent: ["error", 2, { "IndentOuterfunction": false }]*/

(function() {

function foo(x) {
  return x + 1;
}

})();

function() {

function foo(x) {
  return x + 1;
}

}();

if(y) {
   console.log('foo');
}
```

`

**Comment by ilyavolodin** [comment]
@BYK @gyandeeps could you take a look at this proposal and see if you agree?

**Comment by gyandeeps** [comment]
I think we had this as one of the action items on #632 issue, but we didn't do it because they was no one asking for it.
I think we can do this now.

**Comment by ilyavolodin** [comment]
@gyandeeps Keep in mind that this is also part of both jQuery and Google styleguide. And since JSCS is now retired and we committed to bringing all JSCS features to ESLint, we would want to do this.

**Comment by nzakas** [comment]
I commented on the PR, but will paste here: the other options are all node types, and this is not. Also, we are really talking about indenting the IIFE body, not the IIFE itself, so we need to work on this naming a bit. And last, the other options are numeric, so this one should probably be as well.

**Comment by platinumazure** [comment]
@nzakas Are we sure about that? Do we know of use cases where someone may want an indent level, which is different from the normal file indent level? (Or similarly, where an IIFE might get a tab but everything else gets spaces?) Honestly, until we see some of those use cases, I would prefer a boolean, if it were up to me.

**Comment by davidshepherd7** [comment]
I'm happy to make it numeric for consistency, especially since future options are likely to be numeric. It's not any more difficult to do so YAGNI doesn't really apply IMO.

For the name: how about `OuterIIFEBody`? (Dropped the `Indent` for consistency with other numeric options.)

**Comment by BYK** [comment]
>I'm happy to make it numeric for consistency, especially since future options are likely to be numeric. 

This won't be the case actually.

>And last, the other options are numeric, so this one should probably be as well. 

Can I use this to move the options to non-numeric (in a bw-compatible way)? We had have a very bad pattern and we keep building on it just for the sake of consistency. I can't work on coding ESLint nowadays much but I'd love to fix this.

**Comment by davidshepherd7** [comment]
> Can I use this to move the options to non-numeric (in a bw-compatible way)? We had have a very bad pattern and we keep building on it just for the sake of consistency.

Ok, I'm open to either numeric or non-numeric. I don't really have enough context to have a strong opinion. I just need you guys to tell me which one to implement.

**Comment by nzakas** [comment]
@platinumazure that's not the right question to ask. We can never know all possible use cases, and btw always aim for maximum flexibility given that. 

@byk as I said before, we can't just start adding options that are configured differently without a complete proposal and discussion. So we can either stop work on this rule until you put that together, or we can keep making incremental improvements in a way that makes sense for the rule right now. I think the latter makes the most sense.

@davidshepherd7 I'd prefer that we don't have an initial uppercase letter so it's clear this is not an AST node type. 

Other thoughts?

**Comment by BYK** [comment]
>@byk as I said before, we can't just start adding options that are configured differently without a complete proposal and discussion. So we can either stop work on this rule until you put that together, or we can keep making incremental improvements in a way that makes sense for the rule right now. I think the latter makes the most sense.

Alright, never mind me. Don't wanna stop people from working on something.

**Comment by davidshepherd7** [comment]
Is there anything else that needs to be done to merge the pull request?

**Comment by ilyavolodin** [comment]
No, I think it's ready to merge. Sorry it just fell through the cracks a little bit.
