### ISSUE TITLE
--no-ignore should not prevent --ignore-pattern

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6260]
According to the doc the purpose of `--no-ignore` is to "Disables excluding of files from `.eslintignore` and `--ignore-path` files. However it also prevents any usage of `--ignore-pattern`.

**What version of ESLint are you using?**
2.10.2

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
N/A

**What did you do? Please include the actual source code causing the issue.**
`/bin/eslint.js test.js --no-ignore --ignore-pattern 'test.js'`

**What did you expect to happen?**
`test.js` is still ignored

**What actually happened? Please include the actual, raw output from ESLint.**
`test.js` was linted

**Comment by nzakas** [comment]
I think the documentation just needs to be updated. `--no-ignore` is meant to turn off all ignore features outside of the defaults.

**Comment by platinumazure** [comment]
@nzakas If that's how we want `--no-ignore` to behave, then I think we should also have an option that suppresses ignore files so that users can still specify ignore patterns. I still think that's a valid use case (ignore file exists, user wants to invoke with no ignore file, user wants to provide patterns); do you?

**Comment by alberto** [comment]
@nzakas What would be the reasoning for also ignoring `--ignore-path`, since both would be command line options?

**Comment by nzakas** [comment]
@alberto sorry, I'm not sure what you're asking.

@platinumazure I don't think so. Again, as I said in my comment, `--no-ignore` is meant to turn off all ignore features. I'm not sure why you'd want to have an ignore file but not use it and then specify an ignore pattern on the command line. Given that we've received zero requests to change that behavior, I'd venture to say this isn't a common use case.

So, I'm still of the mind that the documentation is just incorrect and should be updated.

**Comment by platinumazure** [comment]
@nzakas Okay. I do think the use case I have outlined is valid, but I don't feel strongly enough about it to consider your interpretation wrong. If someone requests an enhancement to allow patterns but suppress ignore files, we can revisit then.

**Comment by alberto** [comment]
Sorry, I'll try to explain myself better.

What you are saying is that `--no-ignore` invalidates `--ignore-pattern`, so I wouldn't ever make sense using both at the same time.

I was thinking it could be somewhat useful to not invalidate it (and it's a trivial change to do so). So, for example someone with an `.eslintignore` file which ignores some parts of his project, could run with `--no-ignore`to see the status of things in the ignored folders, but also use `--ignore-pattern` to skip the known really problematic ones. Something like `eslint --no-ignore --ignore-pattern "hereBeDragons/*"`. Not a big deal, since it can also be achieved editing the ignore file or using a different one, so if you don't think it adds enough value, we can update the docs instead, as you said.
