### ISSUE TITLE
Add formatter for VSO (aka TFS, VSTS)

### ISSUE THREAD

**Issue by mattbrooks2010** [eslint/eslint#6262]
## FEATURE REQUEST
Add a new formatter to support VSO / TFS integration.

## PROPOSED SOLUTION
The solution would be to emit [VSO logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md), which are similar to [TeamCity service messages](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-servMsgsServiceMessages).

## STATUS
Forked and in progress. Pull request pending.

## ESLINT VERSION
eslint@2.10.2

**Comment by platinumazure** [comment]
We have a Visual Studio formatter already, is this different?

**Comment by mattbrooks2010** [comment]
Yes it is. The existing Visual Studio formatter is actually an MSBuild formatter.

**Comment by nzakas** [comment]
We aren't really adding any more formatters to the core at this point. It would be better to publish your formatter as a separate package under the name `eslint-formatter-vso` (or whatever you think is appropriate) so you can take advantage of this when it's complete: https://github.com/eslint/eslint/issues/5900

**Comment by mattbrooks2010** [comment]
Thanks for the info. The proposed solution in #5900 makes sense. However, my motivation for doing this is due to the way Sass Lint currently works. It (surprisingly) uses ESLint formatters directly:

Documentation — https://github.com/sasstools/sass-lint/blob/develop/docs/options/formatter.md
Implementation — https://github.com/sasstools/sass-lint/blob/develop/index.js#L248

So I think I'm blocked. Would you have me raise this issue in https://github.com/sasstools/sass-lint?

**Comment by nzakas** [comment]
Oh wow - that's pretty sneaky. Can you open an issue with them and post the link back here? I can comment on it.

**Comment by ilyavolodin** [comment]
Didn't realize that `sass-lint` was using our formatters whole-sale. I would say that they should implement support for loading formatters from outside of ESLint core. It would be very backwards to add formatters to ESLint just so you could use them in sass-lint.

**Comment by mattbrooks2010** [comment]
The issue of `sass-lint` loading the ESLint Core formatters is being investigated with the Sass Tools team.

My requirement for the VSO formatter extends to JavaScript code. It would be useful to be able to leverage the formatter for this purpose but at the moment I cannot see a way of achieving that. 

Are you able to provide any indication of the anticipated timeline for #5900 or perhaps any other suggestions?

**Comment by nzakas** [comment]
@mattbrooks2010 the timeline is basically "when someone decides to do it." Everyone is working in their free time, so there's not really a set schedule.

**Comment by mattbrooks2010** [comment]
OK thanks for the clarity. I will proceed with a separate package `eslint-formatter-vso` or similar, as you have suggested.

**Comment by bdukes** [comment]
@mattbrooks2010 I've gone ahead and published this at https://www.npmjs.com/package/eslint-formatter-vso

**Comment by mattbrooks2010** [comment]
FYI @cgwrench
