### ISSUE TITLE
Cascading configuration does not work as documented for globalReturn with Babel-ESLint parser

### ISSUE THREAD

**Issue by nfriedly** [eslint/eslint#6265]
**What version of ESLint are you using?**
2.10.2 

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

public/js/.eslintrc:

```js
{
  "env": {
    "browser": true,
    "jquery": true,
    "node": false
  },
  "parserOptions": {
    "ecmaFeatures": {
      "globalReturn": false
    }
  }
}
```

root .eslintrc

```js
{
  "rules": {
    "no-console": 0,
    "func-names": 0,
    "vars-on-top": 0,
    "no-else-return": 0,
    "consistent-return": 0,
    "no-process-exit": 0
  },
  "globals": {
    "useResultsTable_template": false,
    "useResultsTableTemplate" : true
  },
  "env": {
    "node": true
  },
  "extends": "eslint-config-airbnb-es5",
}
```

**What did you do? Please include the actual source code causing the issue.**

I have a node.js app that also includes some front-end JS in the `public/js/` folder. I have a few functions for my front-end js that are defined in one file and used in another. Each has an appropriate `/* exported */` comment. Here's one example:

```js
/**
 * Returns the next hour as Date
 * @return {Date} the next hour
 */
/* exported nextHour */
function nextHour() {
  var oneHour = new Date();
  oneHour.setHours(oneHour.getHours() + 1);
  return oneHour;
}
```

Complete code is at https://github.com/watson-developer-cloud/visual-recognition-nodejs/tree/eslint-exported

**What did you expect to happen?**

I expect the `public/js/.eslintrc` file to override the `node` and `globalReturn` settings from the root `.eslintrc` file but inherit other settings per [the documentation](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy):

> The configuration cascade works by using the closest .eslintrc file to the file being linted as the highest priority, then any configuration files in the parent directory, and so on.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLInt does not appear to be letting the closest .eslintrc file override the parent ones for the  `node` and/or `globalReturn` settings. Instead it is ignoring my ` /* exported...` comments as if the environment were still `node`.

ESLint reports the following:

```
/Users/nfriedly/visual-recognition-nodejs/public/js/demo.js
  24:10  error  'nextHour' is defined but never used  no-unused-vars
  37:10  error  'resize' is defined but never used    no-unused-vars

/Users/nfriedly/visual-recognition-nodejs/public/js/use.js
  26:10  error  'setupUse' is defined but never used  no-unused-vars

✖ 3 problems (3 errors, 0 warnings)

```

I have a couple of workarounds - either (ab)use `// eslint-disable-line no-unused-vars` or else just give up and use browserify or something on my front end code.. but I still thought it would be worth reporting this bug so that it hopefully won't bite anyone else.

**Comment by ilyavolodin** [comment]
@nfriedly You forgot to mention that you are using `babel-eslint` in both stackoverflow question as well as mailing list post. `babel-eslint` parses everything as module, there is no other mode. JS module has global return by definition, so no matter what you are going to do in the configuration you will not be able to use `exported` functionality with babel-eslint. I'm pretty sure environment override has been fixed at some point not too long ago, so you can try to remove babel-eslint and just use default parser, and everything should work just fine.

**Comment by nfriedly** [comment]
I didn't realize it myself until I filed the bug and looked it up... and
then I didn't realize that it changes the config behavior. I'll try it
without that

**Comment by nfriedly** [comment]
Yes, switching to the default parser does indeed make the cascading behavior work as expected. I had no idea that could be overridden.

**Comment by ilyavolodin** [comment]
In that case, I'm not sure anything can be done about this. `babel-eslint` parses everything as a module, that's just how it works (I'm not even sure if babel is capable of script parsing). And everything seems to be behaving correctly with ESLint itself.
Closing as the issue seems to be resolved and no work needs to be done.
