### ISSUE TITLE
error when linting valid async function with generator-star-spacing rule enabled

### ISSUE THREAD

**Issue by doronpr** [eslint/eslint#6274]
Getting `TypeError: Cannot read property 'value' of undefined` error when linting valid *async function* with `generator-star-spacing` rule enabled.

**What version of ESLint are you using?**
`2.11.0`
(works in `2.10.*` [this](https://github.com/doronpr/eslint/commit/9fce04e76dcbae96445e9f6868947aba07d0d662#diff-0893bcac2ba523393aaab76d47c7da39R66) is the commit that created the issue).
**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`
**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue.**
See minimum reproduce repository example:
https://github.com/doronpr/min-reproduce-eslint-generator-star-spacing

**What did you expect to happen?**
lint should pass.

**What actually happened? Please include the actual, raw output from ESLint.**
The following internal error is thrown
```
TypeError: Cannot read property 'value' of undefined
    at getStarToken (~/src/min/node_modules/eslint/lib/rules/generator-star-spacing.js:69:25)
    at EventEmitter.checkFunction (~/src/min/node_modules/eslint/lib/rules/generator-star-spacing.js:124:29)
```

**Comment by mysticatea** [comment]
Thank you for this issue.

Unfortunately, ESLint core rules don't support experimental features (async function is still stage 3).
Please use [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel#readme) instead.

**Comment by mysticatea** [comment]
Out of mere curiosity, why does `babel-eslint` create AST with `node.generator == true` for async functions?

**Comment by doronpr** [comment]
@mysticatea Thanks. I'm not sure why `node.generator == true` for async functions. I opened an [issue](https://github.com/babel/babel-eslint/issues/316) with `babel-eslint` to inquire as this would definitely fix the issue.

**Comment by mysticatea** [comment]
Thank you, @doronpr !

**Comment by hzoo** [comment]
The reason why transformations like `node.generator = true` for async or various other transforms is because encountering a unexpected node caused issues with certain rules (at least at the time it was done). Whether it's true or false at least one rule is broken.

Looking back at the history, it was a change made very early on. Not sure what can be done other than certain rules being able to account for unknown/unexpected node types. https://github.com/babel/babel-eslint/issues/22

**Comment by mysticatea** [comment]
@hzoo Thank you for the explanation. True, it's great if there is a way to override parts of core rules/core behavior. I also have made [such a rule](https://github.com/mysticatea/eslint-plugin-node/commit/bdd2c27ee48853df388562e1d897d2c120b5e5d4) before, and I'm going to make such rules in future... (e.g. https://github.com/mysticatea/eslint-plugin-node/issues/4)

----

BTW, for this issue, we can use [babel/generator-star-spacing](https://github.com/babel/eslint-plugin-babel#readme) rule.

**Comment by hzoo** [comment]
Yeah its basically just returning/bailing https://github.com/babel/eslint-plugin-babel/blob/5c20dd610e8ffef752f8df44157f76d7722c3e13/rules/generator-star-spacing.js#L63

It would be interesting to figure out a clean way to allow hooking into certain parts of rules/visitors/branch statements.

**Comment by crossjs** [comment]
set `generator-star-spacing: 0` before `babel/generator-star-spacing: 1`,
it works out for me.

**Comment by feross** [comment]
This issue is thorny. It's creating problems in `standard` since the user can specify their own parser. That makes it impossible for us to know what to put in our config:


```
generator-star-spacing: 2
```

Or:

```
babel/generator-star-spacing: 2
```

Since we obviously can't put both.

Does anyone have ideas for how to improve this situation?

**Comment by platinumazure** [comment]
@feross Don't forget you could have your configuration be a JavaScript file where the config object is computed at runtime and the result is assigned to `module.exports`. Would that solve your use case, or am I missing something?

**Comment by hzoo** [comment]
Kind of like https://github.com/eslint/eslint/issues/5211, another option is for the original eslint rule to account for async functions or for the logic to work such that having the presence of `async function` won't make the rule error. Could look at how someone implemented the rule in the babel plugin https://github.com/babel/eslint-plugin-babel/blob/master/rules/generator-star-spacing.js#L63.

I don't think this would be the same as https://github.com/eslint/eslint/issues/6693 since the rule itself is modified not the default parser or anything

**Comment by hzoo** [comment]
Well now that it's stage 4, we can remove that change in babel-eslint once it's enabled in eslint. Someone can ping me/babel-eslint repo when it happens if I don't see it myself. https://github.com/babel/babel-eslint/issues/350

**Comment by IhostVlad** [comment]
Yes, generator-star-spacing is buggy and causes failure with async/await functions
Can be fixed by turn generator-star-spacing off in local esling config file

**Comment by platinumazure** [comment]
@IhostVlad We should now support async generator functions (in latest ESLint). If you are experiencing problems, please open a new issue following our bug report template. Thanks!
