### ISSUE TITLE
`max-statements-per-line` error should indicate how many statements it found

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#6287]
**What version are you using?**
2.11.0

**What did you do?**
Set `max-statements-per-line` to $N, and lint a line that had > $N statements on it.

**What happened?**
Got "This line has too many statements. Maximum allowed is $N"

**What did you expect to happen?**
When N is 1, I'd expect "This line has 2 statements. Maximum allowed is 1"

**Comment by platinumazure** [comment]
I think this could really help with debugging, both for end users and for us if someone reports a bug with the rule. I'm :+1: on this.

**Comment by ljharb** [comment]
I'm looking into implementing this, and running into difficulty because the current code reports as soon as it finds the "max + 1"th statement on the line - ie, it doesn't count all statements in the entire line before erroring out.

**Comment by kaicataldo** [comment]
@ljharb Thanks for looking into this! Are you still working on this?

**Comment by ljharb** [comment]
I've still got a branch in-progress, but I fear it's beyond my skill atm. I can keep giving it a shot tho!

**Comment by nzakas** [comment]
I count three 👍s so we still need a champion here.

**Comment by btmills** [comment]
I'll champion, marking as accepted. @ljharb can you push that in-progress branch somewhere? I might have an idea for how to report after all have been counted rather than just max + 1...

**Comment by ljharb** [comment]
@btmills done! https://github.com/ljharb/eslint/tree/ljharb/max_statements_per_line_message

**Comment by btmills** [comment]
@ljharb thanks! Just left a comment on that wip commit with an idea :party:

**Comment by ljharb** [comment]
Thanks, that did it. PR incoming.
