### ISSUE TITLE
`no-control-regex` error should indicate which unexpected chars were found

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#6293]
**What version are you using?**
2.11.1

**What did you do?**
enabled `no-control-regex` and ran it on https://github.com/es-shims/String.prototype.trim/blob/e89adeefcbd6fb59563e62d230b8036d65a8bf69/implementation.js#L7-L8

**What happened?**
Got "Unexpected control character in regular expression"

**What did you expect to happen?**
I'd like to know which control character was unexpected, so I can quickly fix it.

**Comment by vitorbal** [comment]
Hi @ljharb, thanks for the issue! What you are proposing is an improvement to the error message, correct? I totally agree this would be helpful. How about showing the column position of the character as well?

**Comment by ljharb** [comment]
Yes, an improvement to the error message. Column position would be great too but imo the more important thing is the character itself.

**Comment by pedrottimark** [comment]
@ljharb Since the problem is a control character, are you thinking of the character (which might be invisible) or its code, or both? If the code, in hexadecimal or decimal, or both?

**Comment by ljharb** [comment]
@pedrottimark the escaped form, ie, `\x03` or whatever - in other words, the literal thing i typed into the code that caused the warning.

**Comment by nzakas** [comment]
@eslint/eslint-team is anyone willing to champion this change?

**Comment by ljharb** [comment]
I'm still attempting to implement it, if that helps it stay open. I was blocked on https://github.com/eslint/eslint/pull/6752 being merged, so it's only been 6 days since then :-)

**Comment by ljharb** [comment]
I have the pull request ready, but since this issue isn't yet marked as accepted, it seems like I shouldn't file it yet.

**Comment by mikesherov** [comment]
:+1: on this change.

**Comment by platinumazure** [comment]
I'll champion.

**Comment by ilyavolodin** [comment]
Sounds good to me. :+1:

**Comment by platinumazure** [comment]
Open question: Do we have consensus that we'll just tweak the error message for now, no location tweaks? (Location info would require reporting one violation per character instead of per literal.)

I'm :-1: (but not strongly) to location info, because I think the characters showing up in the lint message is already a huge win for 99% of use cases. If users want line/column info and create an issue to that effect, we can reconsider then. That's just my thought on the matter, others may disagree.

**Comment by ilyavolodin** [comment]
@eslint/eslint-team Can we get one more :+1: here to mark this as accepted? We have a PR that already has been code reviewed and just waiting for this issue to be accepted.

**Comment by btmills** [comment]
Makes sense to me :+1:
