### ISSUE TITLE
'NewComponent' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by jesusreal** [eslint/eslint#6303]
**What version are you using?**
2.11.1
**What did you do?**
Using React.js, I imported a component to my index.js file. I only use this component as part of the return from the render method. Code can be checked here: https://github.com/jesusreal/eslint-playground-repo/blob/master/src/index.js.
Initially I thought it was a babel-eslint issue, but I replaced it with parserOptions property and I had the same issue. It is also not a problem with any plugin. I googled it and I was reading many github issues related to this rule but I didn't found any issue where they had the same problem as me.
**What happened?**
I got the following error   4:8  error  'NewComponent' is defined but never used  no-unused-vars
**What did you expect to happen?**
I expected not to get any error, as per the docs, the variable is being read.

**Comment by alberto** [comment]
You should use https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md from `eslint-plugin-react`

**Comment by jesusreal** [comment]
Adding the following rule solved my issue:
`"react/jsx-uses-vars": [2]
`

Thanks a lot @alberto

**Comment by yangshun352607664** [comment]
'Iconfont' is defined but never used   ,what should I do ? please help me .Thanks

**Comment by veenapb** [comment]
@jesusreal where should i add that rule?

**Comment by didilinkin** [comment]
@veenapb **../src/.eslintrc.js**
