### ISSUE TITLE
Docs: About page mentions rule severity numbers and probably shouldn't

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6309]
From the "About" page:

> Every rule:
>
>* Is standalone
>* Can be able to be turned off or on (nothing can be deemed “too important to turn off”)
>* Can be set to be a warning or error individually
>* Is turned on by providing a non-zero number and off by providing zero

The last bullet point is problematic for a few reasons:

1. It mentions the numeric severities, which are still allowed but semi-deprecated in favor of strings
1. In my opinion, it's way too specific about implementation/usage details for a high-level About page
1. In my opinion, it is redundant given the point above ("Can be set to a warning or error individually")

I would advocate removing the last bullet point entirely, but I would also accept modifying it to mention numeric and string severity levels.

(Originally filed at eslint/eslint.github.io#261)

**Comment by platinumazure** [comment]
@nzakas Could you please share your thoughts on this point:

> I would advocate removing the last bullet point entirely, but I would also accept modifying it to mention numeric and string severity levels.

Should the bullet point be removed or modified?

I'm happy to take this on once I know the correct approach :smile:

**Comment by nzakas** [comment]
I think removing it is fine
