### ISSUE TITLE
Add auto-fixing to padded-blocks

### ISSUE THREAD

**Issue by glebmachine** [eslint/eslint#6320]
Please, add auto-fixing for **padded-blocks** option

**Comment by kaicataldo** [comment]
This seems like a reasonable request to me, though I'm sure where we stand regarding auto-fixing newlines (see https://github.com/eslint/eslint/issues/5958#issuecomment-222345636). Thoughts @eslint/eslint-team?

I'd be happy to take this on if we decide it's a good idea.

**Comment by alberto** [comment]
Actually I have a branch where I was trying to implement this, and it lead me to that comment and other concerns raised in #6298. Even if we decide those are not a problem, it's not trivial to remove linebreaks, because they might not be `\n`.

**Comment by glebmachine** [comment]
"line breaks (better: newlines) can be one of Carriage Return (CR, \r, on older Macs), Line Feed (LF, \n, on Unices incl. Linux) or CR followed by LF (\r\n, on WinDOS).

Therefore, the most efficient RegExp literal to match all variants is

/\r?\n|\r/"

Source stackoverflow: http://stackoverflow.com/a/10805292

**Comment by kaicataldo** [comment]
Whoops, my first response should have read "not sure where we stand..."

**Comment by glebmachine** [comment]
Btw, it was great, to have fix for this)

**Comment by kaicataldo** [comment]
@alberto Yeah, that makes sense. Any reasons you can think of why the regex solution might not work for removing newlines? Still doesn't solve the problem of adding the right type newline, but that gets back to the discussion happening in the other issue I pointed to earlier.

**Comment by glebmachine** [comment]
Guys, here the snippet to detect proper line engings in node:
```js
typeof process != 'undefined' && 'win32' === process.platform ? '\r\n' : '\n'
```

**Comment by nzakas** [comment]
@glebmachine that isn't accurate. Windows users can use Linux line endings and Linux users can use Windows line endings. You can't make assumptions about this based on the platform.

Removing line breaks can be done with a regex, it's the insertion that is the problem here.

**Comment by glebmachine** [comment]
@nzakas In this uncommon case you can check file for used line endings.

**Comment by alberto** [comment]
@kaicataldo @nzakas re: removing linebreaks. Unless I am missing something here, it can't be done directly with a regex. To create a fixer you have to provide a range to remove, and you can't get the exact range of the linebreak without resorting to something like what's done in #6226.

**Comment by mikesherov** [comment]
Could always look how JSCS 2.0 (pre-CST) does this fix.

**Comment by lukeapage** [comment]
Re: inserting newline, just take the first matching newline in the file or a sensible os default.
Then allow the newline to be fixed by the line break rule in the next iteration for the case where you get it wrong.
Thats my memory of how jscs v2 works (could be wrong)

**Comment by mikesherov** [comment]
@lukeapage yes, basically.

**Comment by kaicataldo** [comment]
@lukeapage @mikesherov Makes sense to me!

**Comment by alberto** [comment]
If we decide inserting the wrong linebreak is not a problem to us (even if `linebreak-style` is disabled!) then yeah, no problem inserting `\n`.

**Comment by kaicataldo** [comment]
As I understand it, it would match the type of the first line break it finds. There is of course the edge case where there might not be any newlines, but that I think that would be pretty rare...

**Comment by glebmachine** [comment]
Cheers!!
