### ISSUE TITLE
--print-config outputs empty config if called not from config file directory

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6329]
**What version of ESLint are you using?**

2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

`e:\DOC\prg\js\node\.eslintrc.json`
```JSON
{
  "root": true,
  
  "extends": [
    "eslint:recommended",
    "airbnb-base"
  ],
  
  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "script"
  },
  
  "env": {
    "browser": false,
    "es6": true,
    "node": true
  },
  
  "rules": {
    "eqeqeq": "error",
    "no-console": "off",
    "no-extra-parens": ["error", "all"],
    "quotes": ["error", "single"],
    "spaced-comment": ["error", "always", { "exceptions": ["/", "*"] }],
    "strict": ["error", "global"]
  }
}
```
**What did you do? Please include the actual source code causing the issue.**

I have a simple test script in the subdirectory relative to the config directory:

`e:\DOC\prg\js\node\-test\test.js`:
```js
'use strict';



console.log(1);

```
eslint output (to be sure eslint really uses all the rules frome the additional configs):
```
e:\DOC\prg\js\node\-test>eslint test.js

E:\DOC\prg\js\node\-test\test.js
  4:2  error  More than 2 blank lines not allowed  no-multiple-empty-lines

✖ 1 problem (1 error, 0 warnings)
```
I want to see all the config set via `eslint --print-config test.js`.

**What did you expect to happen?**

All the rules from `.eslintrc.json` + `eslint:recommended` +  `airbnb-base` should be shown.

**What actually happened? Please include the actual, raw output from ESLint.**

The output is:
```JSON
{
  "globals": {},
  "env": {},
  "rules": {},
  "parserOptions": {}
}
```
However, if I place `test.js` in the same directory with `.eslintrc.json`, the output is a big proper rule set.

**Comment by vsemozhetbyt** [comment]
The test case may be simplified: call `eslint --print-config .` from config file directory and from a subdirectory — the first output is the real set, the second one is empty.

**Comment by vsemozhetbyt** [comment]
Debug outputs from the config file directory:

![1](https://cloud.githubusercontent.com/assets/10393198/15837355/9c05c5ac-2c41-11e6-81cb-71bc0cc0e09a.png)

Debug outputs from a subdirectory:

![2](https://cloud.githubusercontent.com/assets/10393198/15837372/abcd200c-2c41-11e6-9450-ba09b111b037.png)

**Comment by platinumazure** [comment]
I'm really confused about showing the linting messages when the issue seems to be about `--print-config`. Am I missing something?

* Is this about `--print-config` specifically?
* Do you believe the wrong configuration is being loaded/used for your use case?

**Comment by vsemozhetbyt** [comment]
I've put the linting messages as a proving that without `--print-config` eslint uses all the triple rule set even being called frome a subdirectory. However, just adding `--print-config` to call from the same subdirectory somehow cleans rule set for printing.

**Comment by vsemozhetbyt** [comment]
I've added a note before the linting message. Is it clear now? Sorry, my English is clumsy(

**Comment by ilyavolodin** [comment]
Verified. Interesting. I though `--print-config` was running after configuration resolution process. If that would be the case, this should be happening.

**Comment by alberto** [comment]
I am working on this

**Comment by nzakas** [comment]
I'm a bit confused here - what are we saying is the bug? 

I'm pretty sure `--print-config` requires that you pass a file and not a pattern, so `eslint --print-config .` won't work while `eslint --print-config foo.js` will.

**Comment by vsemozhetbyt** [comment]
Does `.` not mean 'current directory' for eslint? Whatever the case, you can replace `.` by any path — the bug is still here: calling from config file directory and calling  from any subdirectory have different outputs.

**Comment by platinumazure** [comment]
@nzakas I think the problem is if you have `foo.js` and `subfolder/bar.js`, `--print-config` simply doesn't work when you pass in `subfolder/bar.js` (or any path where the file is not in the same folder as the config file).

**Comment by alberto** [comment]
@nzakas Here is a failing test case using a file, running from `lib`:
`../bin/eslint.js  --print-config ./cli.js`

**Comment by vsemozhetbyt** [comment]
@platinumazure the bug depends not from path and not from relation between path and config file, but from relation between CWD and  config file. If you call eslint for `subfolder/bar.js` from the same folder with config file, it is OK.

**Comment by ilyavolodin** [comment]
@nzakas That's what I assumed as well. However, that's not what is happening. `eslint --print-config .` is working in the case that you have `.eslintrc` in the current directory, which is strange and not what I expected. But the tests that I posted are done on the file, not on the pattern. So it seems that there might be two bugs here. First one, `--print-config` on a file in the subdirectory returns an empty object. Second one, `--print-config` seems to work on patterns, when it shouldn't.
