### ISSUE TITLE
no-param-reassign: function type exceptions

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6339]
**What version of ESLint are you using?**

2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

I'm generally OK with `airbnb-base`  concerning this rule:

`'no-param-reassign': [2, { 'props': true }], `

**What did you do?..**

However, it would be useful to have exceptions for the whole function types. In my code I've bumped into these cases in which eslint was too strict as for me.

1) `Proxy` traps.

The `target` argument for many traps is intended to be modified. See as example: [Validation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Validation)

eslint output: `error  Assignment to property of function parameter 'obj'  no-param-reassign`

2) Node.js stream listeners.

Expanded example from [Read File Stream Line-by-Line](https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line):
```js
const readline = require('readline');
const fs = require('fs');

const rl = readline.createInterface({
  input: fs.createReadStream('sample.txt')
});

let lineNumber = 0;
rl.on('line', line => {
  if (++lineNumber === 1) line = line.replace(bomRegExp, '');

  line = line.trim();

  if (line) {
    // Do something with the line data.
  }
});
```
eslint output: `Assignment to function parameter 'line' no-param-reassign`

In such cases creation an intermediate variable could be overcomplication. May be some additions to the rule like `proxyTraps: false, eventListeners: false` would be helpful.

**Comment by platinumazure** [comment]
We generally don't like to make library-specific exceptions in core rules, and writing logic to support certain types of function calls/callback arguments could be very tricky.

If this doesn't get any traction, please note that you can use inline ESLint configuration comments to suppress the rule for a single violation:

```js
rl.on('line', line => {
  if (++lineNumber === 1) line = line.replace(bomRegExp, ''); // eslint-disable-line no-param-reassign

  line = line.trim();

  if (line) {
    // Do something with the line data.
  }
});
```

**Comment by vsemozhetbyt** [comment]
@platinumazure Thank you. It seems that arguments for event listeners are subject for mutation in many cases and context. HTML elements as the event targets is an example as well.

**Comment by ilyavolodin** [comment]
@vsemozhetbyt It seems that what you want goes completely against the idea behind `no-param-reassign` rule. Why do you want to keep it on in the codebase that requires overriding parameters? Also, couldn't you assign `line` to a temporary variable inside your event handler and modify that variable instead?

**Comment by vsemozhetbyt** [comment]
@vsemozhetbyt I just think that some function types have a predestination that makes some arguments an intended object for mutation (as in Proxy trap case) or just a very versatile data (as for listener case). And if in such cases we must almost always add  temporary variables just for linter  — well, may be something wrong is about it. However, it is just an idea, and if it is completely against some reliable principles, I am sorry for the false alarm.

**Comment by dacz** [comment]
`reduce` is a function that would be nice to allow modifying `accumulator` (with the rule on).

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
