### ISSUE TITLE
Wrong output indentation in all messages if one massage has a long multiline quote

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6340]
**What version of ESLint are you using?**

2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```JSON
{
  "root": true,

  "extends": [
    "eslint:recommended",
    "airbnb-base"
  ],

  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "script"
  },

  "env": {
    "browser": false,
    "es6": true,
    "node": true
  },

  "rules": {
    "arrow-parens": [2, "as-needed"],
    "eqeqeq": 2,
    "key-spacing": [2, { "beforeColon": false, "afterColon": true, "mode": "minimum" }],
    "no-console": 0,
    "no-eq-null": 2,
    "no-extra-parens": [2, "all"],
    "no-multi-spaces": 0,
    "no-unused-vars": 2,
    "no-use-before-define": [2, { "functions": false }],
    "quotes": [2, "single"],
    "spaced-comment": [2, "always", { "exceptions": ["/", "*"] }],
    "strict": [2, "global"],
    "unicode-bom": [2, "always"]
  }
}
```
**What did you do? Please include the actual source code causing the issue.**

```js
const http = require('http');

http.request({
  // Param
  // Param
  // Param
}).on('response', response => {
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
  // Do something with response.
}).on('error', error => {
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
  // Do something with error.
}).end();
```

**What did you expect to happen?**

An output with readable indentation and alignment.

**What actually happened? Please include the actual, raw output from ESLint.**

![1](https://cloud.githubusercontent.com/assets/10393198/15879737/60a45e62-2d2f-11e6-87f5-6a897f8ad640.png)

Compare with the output after the last error fixed:

![2](https://cloud.githubusercontent.com/assets/10393198/15879757/7c9c4ee0-2d2f-11e6-9596-abbe1e7ffba5.png)

**Comment by platinumazure** [comment]
This is a formatter-specific issue. Other formatters may work better for you.

Please see the [formatter CLI option docs](http://eslint.org/docs/user-guide/command-line-interface#f---format) for more options.

**Comment by vsemozhetbyt** [comment]
@platinumazure Thank you. However, it seems to be a rather generic problem to be considered for default formatter. When it appears, it is more easier to correct the error causing quote then to change the formatter. However, the quote in the end of a message queue has an impact on all the queue and should be located and addressed first — and this is somewhat inconvenient.

**Comment by ilyavolodin** [comment]
It looks like a bug that we should fix. However, I don't think we should fix formatter itself, but instead we should modify `newline-per-chained-call` to not dump that much information into the error message.

**Comment by mysticatea** [comment]
I will work on this.

Just curious about this is intentional behavior?

```js
/*eslint newline-per-chained-call:2*/

const http = require('http');

http.request({
}).on('response', response => {  // NO ERROR at this `.on`.
}).on('error', error => {        // error at this `.on`
}).end();                        // error at `.end`
```

Why is the first `.on` not warned?
Or, actually those all are false positive?

**Comment by mysticatea** [comment]
Ah OK.
Default allows 2 chained and disallows 3rd and later.
