### ISSUE TITLE
how to set different ecma version for files in separate folder

### ISSUE THREAD

**Issue by barbalex** [eslint/eslint#6350]
**What version of ESLint are you using?**
2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
in top project folder:

    {
      "extends": "airbnb",
      "env": {
        "node": true
      },
      "rules": {
        "react/jsx-no-bind": 0,
        "comma-dangle": 0,
        "no-use-before-define": 0,
        "consistent-return": 0,
        "semi": [2, "never"],
        "quotes": [2, "single"],
        "strict": 0,
        "max-len": ["error", 120, 2, {"ignoreUrls": true}],
        "no-underscore-dangle": ["error", { "allow": ["_id", "_rev", "_attachments"] }],
        "no-param-reassign": ["error", { "props": false }]
      }
    }

I read here: https://github.com/eslint/eslint/issues/5651 that the way to do this is adding another `.eslintrc`-file in the folder. So I added this on in the views folder:

    {
      "parserOptions": {
        "ecmaVersion": 5
      }
    }

**What did you do? Please include the actual source code causing the issue.**

linted the following code in sublime text 3 using sublime-linter-contrib-eslint:

    module.exports = function (doc) {
      'use strict'
      var standardtaxonomie
      if (
        doc.Typ &&
        doc.Typ === 'Objekt' &&
        doc.Gruppe &&
        doc.Gruppe === 'Flora' &&
        doc.Taxonomien
      ) {
        standardtaxonomie = findStandardTaxonomyInDoc(doc)
        if (standardtaxonomie) {
          emit(standardtaxonomie.Eigenschaften['Taxonomie ID'], null)
        }
      }
      function findStandardTaxonomyInDoc(dc) {
        var stdTaxonomie = null
        dc.Taxonomien.forEach(function (taxonomy) {
          if (taxonomy.Standardtaxonomie) {
            stdTaxonomie = taxonomy
          }
        })
        return stdTaxonomie
      }
    }

**What did you expect to happen?**

eslint using ecma script 5 rules

**What actually happened? Please include the actual, raw output from ESLint.**

    5 problems 
    SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
    SublimeLinter: ERROR: eslint cannot locate 'eslint' 
    SublimeLinter: WARNING: eslint deactivated, cannot locate local or global binary 
    SublimeLinter: ERROR: eslint cannot locate 'eslint' 
    SublimeLinter: eslint: floraById.js ['C:\\Users\\alex\\ae_views\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
    SublimeLinter: eslint output:
    C:\Users\alex\ae_views\views\floraById.js: line 1, col 18, Warning - Missing function expression name. (func-names)
    C:\Users\alex\ae_views\views\floraById.js: line 3, col 3, Error - Unexpected var, use let or const instead. (no-var)
    C:\Users\alex\ae_views\views\floraById.js: line 17, col 5, Error - Unexpected var, use let or const instead. (no-var)
    C:\Users\alex\ae_views\views\floraById.js: line 18, col 27, Warning - Missing function expression name. (func-names)
    C:\Users\alex\ae_views\views\floraById.js: line 18, col 27, Error - Unexpected function expression. (prefer-arrow-callback)

So eslint used ecma script 6 rules.

Oops. hm. Your template made me look into the console. Why the sublime linter errors? Eslint always worked so far.

It it possible that it needs to be installed globally if it is to use `.eslintrc.json`-files in different folders?

So I did:

    npm i -g eslint

Then reopened my file in sublime-text.

And: YESSS, it works!

So I could close this issue right away. But I am leaving this to you, because of this:

Maybe you could explain somewhere in the docs how to achieve this?

**Comment by barbalex** [comment]
well, I don't know why, but after finishing above issue eslint outputs ecma script 6 errors again:

    SublimeLinter: eslint: floraById.js ['C:\\Users\\alex\\ae_views\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
    SublimeLinter: eslint output:
    C:\Users\alex\ae_views\views\floraById.js: line 1, col 18, Warning - Missing function expression name. (func-names)
    C:\Users\alex\ae_views\views\floraById.js: line 3, col 3, Error - Unexpected var, use let or const instead. (no-var)
    C:\Users\alex\ae_views\views\floraById.js: line 17, col 5, Error - Unexpected var, use let or const instead. (no-var)
    C:\Users\alex\ae_views\views\floraById.js: line 18, col 27, Warning - Missing function expression name. (func-names)
    C:\Users\alex\ae_views\views\floraById.js: line 18, col 27, Error - Unexpected function expression. (prefer-arrow-callback)

Now without the errors from before. But still ecma script 6. How can I get eslint to use ecma script 5 rules?

**Comment by platinumazure** [comment]
Just to be sure, could you try running eslint from the command line and showing us the output you get from that? (Also try `eslint --debug`, which gives a lot more output but sometimes gives us a better clue as to what's going on.) Thanks!

**Comment by mysticatea** [comment]
`parserOptions` setting does not turn any rules off. It just changes the behavior of parser.
You need to turn some rules off manually.

**Comment by barbalex** [comment]
Do I understand you correct: in order to lint ecma script 5 I need to turn off all the eslint 6 rules separately inside the `.eslintrc.json`-file? I can't do this by setting parserOptions?

**Comment by mysticatea** [comment]
Yes.
We can change the parser of ESLint by setting. And the content of `parserOptions` is different for each parser. A parser may not have `ecmaVersion` option.

**Comment by barbalex** [comment]
Hm. Okay, will turn off any rule that turns up and only makes sense vor es6 separately.

@platinumazure : Not sure if this is still important but here comes the requested output:

    > eslint --debug ./views/faunaById.js

      eslint:cli Running on files +0ms
      eslint:ignored-paths Looking for ignore file in C:\Users\alex\ae_views +33ms
      eslint:ignored-paths Could not find ignore file in cwd +2ms
      eslint:glob-util Creating list of files to process. +1ms
      eslint:cli-engine Processing C:\Users\alex\ae_views\views\faunaById.js +5ms
      eslint:cli-engine Linting C:\Users\alex\ae_views\views\faunaById.js +1ms
      eslint:config Constructing config for C:\Users\alex\ae_views\views\faunaById.js +1ms
      eslint:config Using .eslintrc and package.json files +4ms
      eslint:config Loading C:\Users\alex\ae_views\views\.eslintrc.json +5ms
      eslint:config-file Loading JSON config file: C:\Users\alex\ae_views\views\.eslintrc.json +1ms
      eslint:config Using C:\Users\alex\ae_views\views\.eslintrc.json +2ms
      eslint:config Loading C:\Users\alex\ae_views\.eslintrc.json +3ms
      eslint:config-file Loading JSON config file: C:\Users\alex\ae_views\.eslintrc.json +1ms
      eslint:config-file Loading airbnb +16ms
      eslint:config-file Attempting to resolve eslint-config-airbnb +1ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb\index.js +2ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb\rules\react-a11y.js +2ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb\rules\react-a11y.js +1ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb\rules\react.js +54ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb\rules\react.js +1ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\strict.js +14ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\strict.js +2ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\index.js +2ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\index.js +4ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\es6.js +2ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\es6.js +3ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\legacy.js +64ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\legacy.js +2ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\variables.js +3ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\variables.js +3ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\style.js +8ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\style.js +1ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\node.js +81ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\node.js +1ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\legacy.js +7ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\legacy.js +2ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\errors.js +5ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\errors.js +2ms
      eslint:config-file Loading C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\best-practices.js +19ms
      eslint:config-file Loading JS config file: C:\Users\alex\ae_views\node_modules\eslint-config-airbnb-base\rules\best-practices.js +1ms
      eslint:config Using C:\Users\alex\ae_views\.eslintrc.json +40ms
      eslint:config Merging command line environment settings +2ms
      eslint:config-ops Apply environment settings to config +1ms
      eslint:config-ops Creating config for environment node +1ms
      eslint:config-ops Creating config for environment browser +4ms
      eslint:config-ops Creating config for environment es6 +1ms
      eslint:cli-engine Linting complete in: 445ms +65ms

    C:\Users\alex\ae_views\views\faunaById.js
       1:18  warning  Missing function expression name          func-names
       3:3   error    Unexpected var, use let or const instead  no-var
      17:5   error    Unexpected var, use let or const instead  no-var
      18:27  warning  Missing function expression name          func-names
      18:27  error    Unexpected function expression            prefer-arrow-callback

    ✖ 5 problems (3 errors, 2 warnings)

    npm ERR! Test failed.  See above for more details.

**Comment by barbalex** [comment]
turning all the specific es6 rules off in the `.eslintrc.json`-file in the folder works. Closing
