### ISSUE TITLE
Update: Added "allowAfterSuper" property to rule "no-underscore-dangle"

### ISSUE THREAD

**Issue by peteward44** [eslint/eslint#6355]
This is to accompany PR #6354.

Request to add a new property for the no-underscore-dangle rule which can allow use of underscores with the ES2015 super keyword.

**Comment by platinumazure** [comment]
Makes sense to me. @eslint/eslint-team Should we accept this enhancement?

**Comment by mikesherov** [comment]
Honestly, I would just make allowAfterThis automatically work for super too. Just personal pref, but fine with either way.

👍

**Comment by mysticatea** [comment]
`{allowAfterThis: true}` means that it's `private` member.
`{allowAfterThis: true, allowAfterSuper: true}` means that it's `protected` member.
So I'd like to keep separating those.

:+1:

**Comment by nzakas** [comment]
I'll give a 👍 . Do we have a champion for this?

**Comment by nzakas** [comment]
I will champion this, which means we still need one more 👍 to accept this change.

**Comment by ilyavolodin** [comment]
:+1:

**Comment by peteward44** [comment]
I've had to close the previous PR and open a new one, #6662. Sorry about that. It's now rebased
