### ISSUE TITLE
Can we simplify our process.exit logic in bin/eslint.js?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6368]
I found myself in bin/eslint.js recently and found this snippet:

```js
// https://github.com/eslint/eslint/issues/4691
// In Node.js >= 0.12, you can use a cleaner way
if ("exitCode" in process) {
    process.exitCode = exitCode;
} else {
    /*
     * Wait for the stdout buffer to drain.
     * See https://github.com/eslint/eslint/issues/317
     */
    process.on("exit", function() {
        process.exit(exitCode);
    });
}
```

The "In Node.js >= 0.12" bit is what caught my attention. I believe we have dropped support for 0.10 already; if not, we're probably about to with the 3.0.0 release. Should that release include whatever simplification can be done in this section of code?

**Comment by alberto** [comment]
We still support 0.10, but it can be done as part of the 3.0.0 release

**Comment by platinumazure** [comment]
@alberto @nzakas Wow, you jumped on that quick. Thank you and nice work!
