### ISSUE TITLE
rest-spread-spacing typos?

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6370]
Is it OK that in the `docs/rules/rest-spread-spacing.md` and in the `tests/lib/rules/rest-spread-spacing.js` there are both `rest-spread-spacing` and `spread-spacing` keywords?

https://github.com/eslint/eslint/commit/82433ae0a2bafd07dc1966829903d63fcc1720c7

(Sorry, I am a newbie here so I dare not make a PR rashly)

**Comment by platinumazure** [comment]
Nope, it's not good, thanks for calling it out!

That said, I thought I saw a PR on this today- let me dig it up...

**Comment by platinumazure** [comment]
PR available at https://github.com/eslint/eslint/pull/6365. Hopefully that will get merged soon.

I'm going to close this as we have a solution in the works. Thanks so much for the issue and please let us know if you see any other problems!

**Comment by vsemozhetbyt** [comment]
Sorry for not searching first :)

**Comment by platinumazure** [comment]
No worries- thanks again for your help!
