### ISSUE TITLE
Create custom rule to verify a core rule has required `meta` properties

### ISSUE THREAD

**Issue by vitorbal** [eslint/eslint#6383]
This came out of a conversation with @pedrottimark, @ilyavolodin and @nzakas.
We would like to create a custom rule, internal to the eslint codebase, to make sure our core rules have all the required `meta` properties in the new rule format.

I'm willing to work on this.

**Comment by platinumazure** [comment]
:+1: from me- was going to propose this myself but you beat me to it!

**Comment by mysticatea** [comment]
:+1: 

But I have a concern: integrations for editors.
We can specify plugins in .eslintrc, but cannot specify `--rulesdir` in .eslintrc.
So I need to write a setting by `.vscode/setting.json` file.

May the setting file be added into this repo or .gitignore?

**Comment by ilyavolodin** [comment]
@mysticatea We can just make it into a plugin.

**Comment by mysticatea** [comment]
@ilyavolodin sounds good to me 😄

**Comment by platinumazure** [comment]
So are we thinking we should just make a plugin for this? If so, should that be its own repository or should we put it in "packages" like we do for eslint-config-eslint?

**Comment by ilyavolodin** [comment]
It should probably be it's own repository, since it's not really going to be all that useful to anyone outside of the ESLint team and plugin developers.

**Comment by nzakas** [comment]
I'd prefer just keeping it in the repo. It's not useful to anyone but us, there's no reason to have the overhead of a plugin for this.

**Comment by ilyavolodin** [comment]
@nzakas It might be useful for plugin creators. I'm also pretty sure that we can come up with a few additional rules to add to that plugin. I remember that I thought at least a few times that we should have a rule to cover specific convention in our repository (I just can't remember what were those rules at this point:-)

**Comment by nzakas** [comment]
@ilyavolodin I'd really prefer not to have another repo or package to manage at this point. This rule is just for us and it's just one rule, so let's keep it simple for now. If we get requests to share it or we start adding a ton of new rules, we can revisit if it makes sense to have a separate repo or plugin. 

It never hurts to start with the smallest thing that solves the problem.

**Comment by ilyavolodin** [comment]
Sounds fine to me. We can start small and move it into plugin if we need to later. (I just personally always disliked our custom rules, and prefer plugins, even if it's for a single rule).

**Comment by vitorbal** [comment]
Just managed to open a PR for this: #6608
