### ISSUE TITLE
no-extra-semi does not handle empty if blocks

### ISSUE THREAD

**Issue by fb55** [eslint/eslint#6386]
**What version of ESLint are you using?**

`2.12.0`

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

`{"extends": "eslint:recommended"}
`

**What did you do? Please include the actual source code causing the issue.**

```js
if(arr[0] === "1");
else if(arr[0] === "2"){
	...
}
```

**What did you expect to happen?**

Nothing.

**What actually happened? Please include the actual, raw output from ESLint.**

```
  31:48  error  Unnecessary semicolon  no-extra-semi
```

Also, when using `--fix`, the semicolon is removed, which leads to invalid code.

**Comment by michaelficarra** [comment]
This rule simply warns on all empty statements. You can use an empty block (`{}`) or some effect-free expression (`0`) instead.

**Comment by fb55** [comment]
That's right, but `--fix` still produces invalid code, which IMHO should never happen.

**Comment by michaelficarra** [comment]
You're right, that is an issue.

**Comment by mysticatea** [comment]
No, that rule has exceptions by the parent node type: https://github.com/eslint/eslint/blob/cd1b0574f1af79d189259f4e1a255230d24b37ee/lib/rules/no-extra-semi.js#L69
But the exception list does not include IfStatement.
Maybe it should include IfStatement.
