### ISSUE TITLE
Docs: wrong example code for "exceptions" option in id-length rule

### ISSUE THREAD

**Issue by cristian-sima** [eslint/eslint#6397]
[http://eslint.org/docs/rules/id-length#exceptions](http://eslint.org/docs/rules/id-length#exceptions)

It is taking about exceptions, but there is a max property

**Comment by vitorbal** [comment]
Hi @cristian-sima, thank you for the issue!
Indeed it seems like the documentation example is wrong and the option being passed should have been  `{ "exceptions": "x" }` instead.
Would you be willing to open a Pull Request to fix it?

**Comment by pedrottimark** [comment]
@cristian-sima Good eyes. Welcome to ESLint! Yes, it is a copy-and-paste error.

* In the `schema` property of the rule in https://github.com/eslint/eslint/blob/master/lib/rules/id-length.js#L31, there is an `exceptions` options whose value is an **array of strings**.
* There is an example of the options configuration in https://github.com/eslint/eslint/blob/master/tests/lib/rules/id-length.js#L42

Therefore, the option needs to be `{ "exceptions": ["x"] }` in the paragraph and the eslint comment.

@cristian-sima Here are the Contributing Guidelines: http://eslint.org/docs/developer-guide/contributing/
Note especially the Docs tag and length limit (irony here :) for the commit message in http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changesa-namestep2a

**Comment by vitorbal** [comment]
ping @cristian-sima just checking if you would be willing to work on this one. No problem at all if you can't, just let us know :)

**Comment by GramParallelo** [comment]
I'm looking to contribute my first PR to gain some experience.  From what I see this issue seems possible for me to do and tagged beginner.  May I try? ( if so, can I get a little helping hand? :-) ) Thanks!

**Comment by platinumazure** [comment]
Hi @GramParallelo, thanks for stepping up! It looks like @kaicataldo might be working on this- hopefully he can clarify whether he is or not.

If you're looking for a good first pull request area, try filtering the issues to include the "beginner" label. If you can't see one, feel free to visit us in our [chat room](https://gitter.im/eslint/eslint).

**Comment by kaicataldo** [comment]
I'm not working on this - just labeled it as I thought it would be a great issue for a newcomer to the project to start with :) Thanks for contributing, @GramParallelo!

**Comment by vitorbal** [comment]
@GramParallelo [this comment](https://github.com/eslint/eslint/issues/6397#issuecomment-225586322) should help you get started, let us know if you need any help!
