### ISSUE TITLE
Better wording for the error reported by the rule "no-else-return"

### ISSUE THREAD

**Issue by othomann** [eslint/eslint#6411]
**What version are you using?**
Latest.

**What did you do?**
When enabling the rule "no-else-return", the error message states:
"Unexpected 'else' after 'return'."

**What did you expect to happen?**
I would suggest to replace "Unexpected" with "Unnecessary" as the code is perfectly legit, but it is not necessary to have an else. So the new message would be:
"Unnecessary 'else' after 'return'."

**Comment by vitorbal** [comment]
Hi @othomann, thanks for your issue! I think the wording you suggested would make things clearer. Would you be willing to work on a PR for this?

**Comment by othomann** [comment]
Sure, I'll provide a PR for this today.

**Comment by othomann** [comment]
I think the PR is ready now. Let me know if you need anything else.

**Comment by ilyavolodin** [comment]
Sounds reasonable to me. @pedrottimark could you take a look?

**Comment by pedrottimark** [comment]
👍  The current rule doc votes in favor of the change:
* 2 occurrences of unnecessary
* 0 occurrences of unexpected
