### ISSUE TITLE
Add a fixer for object-shorthand

### ISSUE THREAD

**Issue by NickHeiner** [eslint/eslint#6412]
I would like to add a fixer for the `object-shorthand` property. I'll work on a PR for this now. Please let me know if you have any objections to this so I don't waste my time! Thanks.

**Comment by platinumazure** [comment]
Hi @NickHeiner, your best bet is to wait until the issue is labeled "accepted" before starting a PR.

It might not hurt to show a few examples of what the fixer output would look like.

@eslint/eslint-team Thoughts on this proposal to add auto-fix to `object-shorthand` rule?

**Comment by nzakas** [comment]
I can't think of any reason not to. :+1:

**Comment by ilyavolodin** [comment]
This will probably be the most complex fixer that we have. I'm :+1: to try, just need to be careful.

**Comment by NickHeiner** [comment]
Ok, I'm trying it now. Thanks!

**Comment by alberto** [comment]
https://github.com/eslint/eslint/pull/5439 might make this more difficult.

**Comment by TheSavior** [comment]
I've been using the codemod for object-shorthand here: https://github.com/cpojer/js-codemod/blob/master/transforms/object-shorthand.js

There might be some learnings that could be made from that code.

**Comment by mikesherov** [comment]
👍
