### ISSUE TITLE
Add support for consistent quotes by checking the first used mark in the file.

### ISSUE THREAD

**Issue by kylepaulsen** [eslint/eslint#6420]
**What version of ESLint are you using?**
2.12.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default

I want a configuration option like jscs has (when validateQuoteMarks is true): http://jscs.info/rule/validateQuoteMarks

The option could be something like:
"quotes": ["error", "consistent"]

I would be willing to do the work for this.

**Comment by ilyavolodin** [comment]
Not a very strong :-1: from me, but never the less. We don't have rules that do autoconfiguration. Style rules exist to provide tools to maintain **consistent** style throughout your code base. I understand that code grows over time, and preferences might change, but that's why we added autofixing. It doesn't take long to just run autofix command once to get your codebase to a single style.

**Comment by kylepaulsen** [comment]
It would just be nice to have some rules adapt depending on the project you are working on. Not all projects have a eslint config file (and not all project owners want to add one). Also I use linters on new files that haven't even been saved yet - so they don't even have a project directory with a linter file.

Also I just found out eslint doesn't have code to auto detect indentation either. If auto configuration is something you want to stay away from, maybe I should use a different linter...

**Comment by ilyavolodin** [comment]
ESLint doesn't have rules turned on by default. So even if we were to add autoconfiguration to some of the rules, you would still have to create config file to enable them. And if you are already creating configuration file it would probably make sense to select a single style (at least from my perspective it makes sense).
If you use linter on files that haven't been created yet, and don't have project directory, you can always create config file in your user directory, and ESLint will fall back to it every time it doesn't find local configuration file.

**Comment by kylepaulsen** [comment]
Yes, this is what I want - a global config file. I just also want it to be flexible so I don't have to do anything to work on something that uses double quotes only or single quotes only.... or spaces only or tabs only. Things like that. I am super lazy and dont want have to touch configuration, I just see no reason why these things can be automated. But that's just my opinion.

**Comment by platinumazure** [comment]
Then you have your answer- create a configuration file in your home directory, and it will apply to any project that doesn't already have its own configuration.

Alternatively, you can use `eslint --init` and have it create a configuration from existing files and it will generate a configuration favoring the most consistent code.

If you don't want to enforce a quotes style in your codebase, you don't have to use the rule.

**Comment by kylepaulsen** [comment]
Closing this issue... I just ended up forking. Maybe I'm not good at describing my scenario.
