### ISSUE TITLE
(docs) space-before-blocks: typo in config examples

### ISSUE THREAD

**Issue by aubergine10** [eslint/eslint#6440]
`classes` option key not quoted, PR incoming...

http://eslint.org/docs/rules/space-before-blocks

**Comment by aubergine10** [comment]
https://github.com/eslint/eslint/pull/6441

**Comment by aubergine10** [comment]
This issue can be closed - wasn't sure if I should close it myself (eg. does a core contributor need to change labels first)?

**Comment by ilyavolodin** [comment]
Nope, you can close your own issue at any point. But I'll close this one.
