### ISSUE TITLE
Are there any solutions to execute eslint check before git commit?

### ISSUE THREAD

**Issue by alcat2008** [eslint/eslint#6446]
I'm just wondering if there are any solutions to execute eslint check before git commit.
Thank for your patience.

**Comment by aubergine10** [comment]
These any use?

* https://coderwall.com/p/zq8jlq/eslint-pre-commit-hook
* https://github.com/brigade/overcommit

**Comment by aubergine10** [comment]
@alcat2008 did the links above cover your requirements? Can this ticket be closed?

**Comment by alcat2008** [comment]
@aubergine10 thanks a lot.
