### ISSUE TITLE
arrow-body-style: rename bloaty requireReturnForObjectLiteral option

### ISSUE THREAD

**Issue by aubergine10** [eslint/eslint#6447]
Rule: http://eslint.org/docs/rules/arrow-body-style

**Note: The old option would be deprecated, not removed, so as to avoid breaking change**

The `"requireReturnForObjectLiteral"` option is unnecessarily longwinded, can it be renamed to `"allowLiteralForm"`?

This would be clarified by updates to the docs (which I'm currently working on). The old option name could be retained, but deprecated, for backwards compatibility.

For reasoning about the arrow function body, I feel its easier to consider three forms (content from WIP doc update):

> ## Details
>
> Arrow functions have three syntactic forms for their function bodies:
> 
> * **Block form:** `() => { ... }`
>   * Like a normal function, statements in the function body are wrapped in curly braces.
> * **Expression form:** `() => ...`
>   * If the function body is not wrapped in braces, and contains a single expression, the result of that expression will be implicitly returned (the `return` keyword is not required)
> * **Literal form:** `() => ({ key: val, ... })`
>   * To return an object literal, it _must_ be wrapped in parentheses (otherwise the compiler assumes you're using block form)
>   * Technically, this is a variant of the expression form, but for reasoning purposes it's easier to think of it as a separate form.
> 
> The `arrow-body-style` rule allows you to define which forms are acceptable for your scripts.

The options documentation then becomes (taken from WIP doc update):

> ## Options
> 
> ```javascript
> arrow-body-style: [ "level", "pattern", { "option": value } ]
> ```
> 
> * **level**:
>   * **`"off"`** _(default)_ - disable the rule
>   * `"warn"` - the rule generates warnings
>   * `"error"` - the rule generates errors (exit code `1`)
> * **pattern**:
>   * **`"as-needed"`** _(default)_ - prevent unnecessary use of braces (if the body is a simple expression, enforce *expression form*)
>   * `"always"` - mandate *block form*
>   * `"never"` - mandate *expression form*
> * **option**, extra setting for `"as-needed"` pattern:
>   * `"allowLiteralForm"` - if **`true`** _(default)_, allow **literal form**
> 
> > Earlier versions of this rule had a `"requireReturnForObjectLiteral"` option which, if `false`, would allow the **literal form**. That option is now deprecated, use the `"allowLiteralForm"` option instead.

**Comment by platinumazure** [comment]
Lately, we've been pretty :-1: on breaking changes without extremely good reasons. I'm personally not convinced this is an extremely good reason. We'll see what the rest of the team thinks.

**Comment by platinumazure** [comment]
"Breaking" label can be removed if proposal is to support both options until a major release (where the old label would be dropped).

**Comment by aubergine10** [comment]
The old option should be deprecated, not removed. Is it worth me doing a PR with suggested code changes that handle both old and new option?

**Comment by platinumazure** [comment]
Strictly for demonstrative purposes, no, I just misunderstood your
proposal. Maybe just edit your first post to make it clear that you want to
deprecate the first option? Thanks!

**Comment by nzakas** [comment]
We just released this option after a very long discussion around the name, so I'm not really in favor of opening up the discussion again. At some point, we have to consider what we have as "good enough" and move on to other things. 

I don't see a compelling reason to revisit the option name. 👎

**Comment by aubergine10** [comment]
Considering the name that was eventually chosen, which makes it sound like the code should be `() => (return {foo: 'bar'})` or similar, I can see why there was lots of debate 😛
