### ISSUE TITLE
Add a fixer for prefer-const

### ISSUE THREAD

**Issue by NickHeiner** [eslint/eslint#6448]
I would like to add a fixer for the `prefer-const` rule. It seems like this should be pretty easy to do; the tricky part is figuring out that a variable should be `const` instead of `let`, but that's already implemented. I'll start on a PR after getting confirmation that the team would be amenable to this.

**Comment by platinumazure** [comment]
Hi @NickHeiner, thanks for the issue.

I vaguely remember we had some trouble (having to do with fixing across scopes) last time we tried this, but maybe this is possible now? I dunno. Pinging @mysticatea and @ilyavolodin in case they have thoughts.

**Comment by nzakas** [comment]
See https://github.com/eslint/eslint/pull/5310. We should be able to do it now so long as the declaration is `let` and is initialized.

**Comment by NickHeiner** [comment]
So, should I not do this if #5310 already exists?

**Comment by NickHeiner** [comment]
Also, as an aside, is there a notion of fixers that only work in some circumstances? Or should it really be that if a rule if fixable, then it is fixable 100% of the time?

**Comment by nzakas** [comment]
#5310 wasn't merged, so we need something new. 

Rules may fix only some problems, it is not required that they fix all problems they find (and in fact, we explicitly do not guarantee fixes to be applied).

**Comment by NickHeiner** [comment]
Ok, I'll start on a PR for this.
