### ISSUE TITLE
Regression from 2.13.0 release - relative requires in extend

### ISSUE THREAD

**Issue by hzoo** [eslint/eslint#6450]
Ref https://github.com/eslint/eslint/pull/6359 I think, @mysticatea 

**What version of ESLint are you using?**

2.13.0 (just released)

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```js
{
  "extends": "./node_modules/eslint-preset-behance/.eslintrc"
}
```

**What did you do? Please include the actual source code causing the issue.**

run `eslint app_folder/`

Updated to 2.13.0 in CI

**What did you expect to happen?**

No issues

**What actually happened? Please include the actual, raw output from ESLint.**

```
Cannot read config file: app/node_modules/node_modules/eslint-preset-behance/.eslintrc
Error: ENOENT: no such file or directory, open 'app/node_modules/node_modules/eslint-preset-behance/.eslintrc'
```

It's checking `node_modules/node_modules` for some reason

Workaround I guess is that we don't have to use `./node_modules/`

**Comment by Mardak** [comment]
This seems to also result in going up one too many parent directories: `{ "extends": "../../../test/.eslintrc" }`

Results in:
```
Cannot read config file: /Users/test/.eslintrc
Referenced from: /Users/Mardak/foo/bar/baz/test/.eslintrc
```
Before it would extend `/Users/Mardak/foo/test/.eslintrc`

**Comment by paglias** [comment]
Same here. It broke all our builds

**Comment by ilyavolodin** [comment]
Issue was introduced by #6359 fix.

**Comment by hzoo** [comment]
for the change: `path.join(relativeTo || path.dirname(filePath), parentPath)`

`relativeTo`: `app/node_modules`

`path.dirname(filePath)`: `app`

`path.join(path.dirname(filePath), parentPath))`:
`app/node_modules/eslint-preset-behance/.eslintrc`

`path.join(relativeTo || path.dirname(filePath), parentPath))`:
`app/node_modules/node_modules/eslint-preset-behance/.eslintrc`

**Comment by apazzolini** [comment]
This is an issue for me as well - this error appears to be related to using eslint as a non-global package and running it with `./node_modules/.bin/eslint`

**Comment by nzakas** [comment]
Let's see what @mysticatea thinks. He should be around soonish and then we can decide whether there's an easy fix or not.

**Comment by mysticatea** [comment]
I apologize for this.
I will investigate this.
I think `relativeTo` should be the directory that .eslintrc exists.

**Comment by ilyavolodin** [comment]
@mysticatea That's what `relativeTo` should be, but it doesn't look like it is in this case, for some reason. Might be a deeper bug in `relativeTo` itself (which would affect a lot of other things).

**Comment by mysticatea** [comment]
Mmm, weird, we also have relative path in our setting and it's working: https://github.com/eslint/eslint/blob/414206cdec53f4967f56ee23ac0c1eb45b31846a/.eslintrc.yml

**Comment by mysticatea** [comment]
That `relativeTo` seems to be https://github.com/eslint/eslint/blob/414206cdec53f4967f56ee23ac0c1eb45b31846a/lib/config/config-file.js#L328

**Comment by mysticatea** [comment]
```
load( C:\Users\starc\Documents\GitHub\eslint\.eslintrc.yml undefined undefined )
    resolvedPath: { filePath: 'C:\\Users\\starc\\Documents\\GitHub\\eslint\\.eslintrc.yml' }
    dirname: C:\Users\starc\Documents\GitHub\eslint
    basedir: C:\Users\starc\Documents\GitHub\eslint\node_modules
    lookupPath: C:\Users\starc\Documents\GitHub\eslint\node_modules\node_modules
```

`getBaseDir` seems wrong, but if I fixed `getBaseDir`, I get failures of some tests...

**Comment by mysticatea** [comment]
Fixed: https://github.com/eslint/eslint/commit/4c80417ac2975afa521379e4d8c2496da7e98a1e#diff-3ca2712fe1d95b19637e57eb1a8b3a5bR318

But I'm not sure this is a correct way or not...

**Comment by nzakas** [comment]
I don't think special-casing `node_modules` is the right approach.

**Comment by ljharb** [comment]
Is there a deadline at which point the change that broke this will be reverted, absent a fix?

**Comment by ilyavolodin** [comment]
@ljharb We are usually try to release patches on the following Monday after the release that created an issue.

@mysticatea Another problem related to this change. You can't run global eslint at all anymore:
```sh
$ eslint .
Cannot read config file: C:\Users\ilya\AppData\Roaming\npm\node_modules\packages\eslint-config-eslint\default.yml
Error: ENOENT: no such file or directory, open 'C:\Users\ilya\AppData\Roaming\npm\node_modules\packages\eslint-config-eslint\default.yml'
Referenced from: c:\Users\ilya\Documents\github\eslint\.eslintrc.yml
Error: Cannot read config file: C:\Users\ilya\AppData\Roaming\npm\node_modules\packages\eslint-config-eslint\default.yml
Error: ENOENT: no such file or directory, open 'C:\Users\ilya\AppData\Roaming\npm\node_modules\packages\eslint-config-eslint\default.yml'
Referenced from: c:\Users\ilya\Documents\github\eslint\.eslintrc.yml
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at readFile (C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:71:15)
    at loadYAMLConfigFile (C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:102:30)
    at loadConfigFile (C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:219:22)
    at load (C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:500:18)
    at C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (C:\Users\ilya\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:363:28)
```

**Comment by nzakas** [comment]
I think I figured it out. See https://github.com/eslint/eslint/pull/6468

**Comment by travi** [comment]
I'm not sure this fully resolved the problem. I'm still seeing this error in a [CI build](https://travis-ci.org/travi/admin.travi.org-components/jobs/138631752) that shows that it is pulling in the latest version, including this patch.

I started seeing this at the end of last week and have tracked it down to my use of grunt-eslint, which depends on `"eslint": "^2.0.0"`. Therefore, my project does not directly define the eslint version to use since the grunt plugin depends on `^2.0.0`

The piece that might be different in my case is that my `extends` definition is relative to the rule file rather than `node_modules`: https://github.com/travi/eslint-config-travi/blob/master/rules/tests/react.js#L2

**Comment by ljharb** [comment]
(This fix did resolve my issue from #6458, fwiw, thanks!!!)

**Comment by nzakas** [comment]
@travi please open a new issue and provide your details.

**Comment by travi** [comment]
sure thing: #6489. thank you for the help
