### ISSUE TITLE
Proposal: Technical Steering Committee

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6452]
## Background

When I started transitioning ESLint to allow others to start getting more involved, I based the governance model off of the old [YUI model](https://github.com/yui/yui3/wiki/Contributor-Model). While I think that was a good start, and allowed us to scale to the point we're at today, I think we need to change things up now that the team has gotten larger and my availability has lessened due to my health. As such, I'd like to propose a model that is based on the [Node.js governance model](https://nodejs.org/en/about/governance/).

## The tl;dr Overview

* The project lead (currently just me) and reviewer (currently 5 people) levels of the current governance model will be collapsed into a single Technical Steering Committee (TSC). 
* The TSC will have final authority over ESLint and will operate in a [consensus-seeking](https://en.wikipedia.org/wiki/Consensus-seeking_decision-making) manner.
* The TSC will have bi-weekly, open meetings where decisions are made.

## Why the change?

As ESLint has gained in popularity, the number of new issues being filed and the number of overall issues to manage has grown considerably. It's hard for any one person to be a gatekeeper or moderator to keep things moving. The result has been issues and pull requests being left open longer, sometimes without followup, and the focus always ends up on the incoming issues.

There are also gray areas where it's unclear who can make decisions on what. Originally, I wanted to approve everything. Then, as the team got bigger, I completely delegated approval of bugs, new rules, and rule options to everyone on the team but still maintained complete control over the core and its roadmap. Again, that was okay when our user base was small, but now that it's grown, there's far too much for me to keep track of. Also, it's unclear what "core" means and there's no documented way that the project makes decisions on anything other than bugs and rules.

I want ESLint to run in an open way and to know that its progress will not be sacrificed if I leave the project (which I don't plan to do, but who knows what my health has in store for me in the future) or otherwise need to disappear for a while.

## Practical Details

On a day-to-day basis, nothing is really going to change. The changes are more about what happens outside of the day-to-day maintenance of the project.

* We'll eliminate the "project lead" and "reviewer" levels in the governance model, and replace them with a single TSC level. The TSC member selection criteria will be the same as for reviewers right now plus we'll want to be sure that whomever joins the TSC is committed to attending meetings and participating on a regular basis.
* The initial TSC will be made up of the current reviewers (@mysticatea, @gyandeeps, @btmills, @alberto, @ilyavolodin) and me. Everyone has confirmed that they are willing to regularly attend meetings going forward.
* I'll draft a TSC charter explaining how things will work. In general, it will be modeled after the Node.js approach.
  * Bugs, documentation changes, and new rules/rule options will still be handled as they are today, and the TSC will intervene only when progress has stalled or when requested.
  * Anything else will need TSC approval to proceed, which can be accomplished either by discussion on the issue or by bringing it up explicitly in a meeting. 
  * The TSC will operate in a consensus-seeking manner.
* The TSC will have regular bi-weekly meetings by chat (day and time TBD).
  * These meetings will be open, anyone can attend.
  * Anyone can add an agenda item for an upcoming meeting (process TBD).
  * Notes and transcript of meeting will be posted publicly afterwards.
  * Issues can be labeled "tsc agenda" to automatically be added to the TSC agenda for the next meeting (this should be done only when TSC approval is necessary or desired for the proposal to move forward).

This is just a rough overview, I'll write up a more detailed explanation to formally add to the docs.

## Questions and Considerations

**Why not have the whole team involved?**

At this point, we have 18 people with commit access and 2 people on the issues team. Getting everyone to agree on something isn't practical and getting everyone to attend a single meeting is even more difficult. As such, I think it makes sense to adopt a model where a small subset of the team is able to move the project forward. We need to find a way to keep the project moving forward, and the best way to do that is to have a small group who can make decisions.

**Are committers still as important with this model?**

Yes! We still want everyone to participate the same as they've been doing. We want to avoid unilateral decision making and make sure everyone who's interested in a particular topic has a chance to speak their mind. Committers are invited to attending TSC meetings if they want to discuss something, or just to hang out and see what we're talking about. The majority of the day-to-day work is still firmly in the hands of the committers and that won't change. In short, we are not removing any privileges of committers, we are only adding responsibilities for the former reviewers.

**Why not meet every week?**

Because everyone is working on ESLint in their free time, I want to be as respectful of people's time as possible. In initial discussions with reviewers, it seemed like meeting every week was a bit too much to ask while meeting once a month would mean longer meetings. Hopefully every two weeks will be a nice middle ground where we can be effective and not overly-taxing on people's time.

**Comment by platinumazure** [comment]
:+1: from me. Just one question, are we planning to change the release schedule at all? The proposed meeting schedule means there will be one TSC meeting per minor release. (This does sound reasonable to me- just showing the math.) If we wanted two meetings per release, hypothetically, that would mean releasing half as often.

**Comment by alberto** [comment]
👍  I think this will benefit the health of the project, so thank you for bringing this up. I am happy to help were I can.

**Comment by kaicataldo** [comment]
:+1: I think this is a positive step for the project, helping the team keep up with the growing number of issues we have. Concrete example: I'm excited to start in on a lot of the JSCS compatibility tasks (writing new rules, etc.), but many of them are still being evaluated. Appreciate the discussion and working going into this effort :)

**Comment by nzakas** [comment]
@platinumazure release schedule will be unchanged. There is no direct relationship between TSC meetings and releases.

**Comment by nzakas** [comment]
@eslint/eslint-team please comment or react if you haven't already. I want to make sure everyone is on board.

**Comment by vitorbal** [comment]
Sounds great, thanks for putting this forward, @nzakas!
For me personally, I would love to spectate some of the meetings whenever I have a chance. Is the invitation also open for the 2 of us in the issues team? :-)

**Comment by nzakas** [comment]
@vitorbal yes, the meeting is open to everyone, regardless of whether they are a team member.

**Comment by markelog** [comment]
Cool that there will be meetings now!

@nzakas Did you thought about agenda document? Should it be a special github repo or google doc... something else? Or you planning to only use issues? Do you want to log those meetings? If so who/where/etc?

Did i ask too many questions? :)

**Comment by hzoo** [comment]
There's stuff like https://github.com/reactjs/core-notes, https://github.com/emberjs/core-notes

**Comment by nzakas** [comment]
@markelog great questions. My initial thinking is that we will have a repo called `tsc-meetings`  where we will post the agenda (as an issue so anyone can comment) and then commit the transcript and meeting notes into the repo for record keeping. That way, we can also have a public Gitter room in which to have the meeting. 

I'm still investigating the best way to log the meetings. My initial thinking is to use the Gitter IRC bridge with a local client like Pidgin that supports logging.

**Comment by ilyavolodin** [comment]
@nzakas IRC bridge would work, but also this might work as well: https://gist.github.com/melvincarvalho/b7a7087e0f7146113fb6

**Comment by mikesherov** [comment]
jquery foundation has an IRC logger. Wonder if it makes sense to get them involved.

**Comment by nzakas** [comment]
@mikesherov do you have any info about how that works?

**Comment by mikesherov** [comment]
:+1: from me as long as meetings are open (which they are). 

@dmethvin any thoughts on if we can use jQuery's irc bot to log on places other than freenode.

**Comment by dmethvin** [comment]
I'm not sure, maybe @aulvi knows?

**Comment by nzakas** [comment]
It looks like we'd need a separate login for the jQuery logger to use (based on https://irc.gitter.im/).

We can always do local logging in the meantime, and Gitter retains two weeks of logs in the interface by default as well.

**Comment by nzakas** [comment]
Gitter actually has online archives! https://gitter.im/eslint/eslint/archives/all
