### ISSUE TITLE
Auto-fixing "padded-blocks" "never" eats up original indentation

### ISSUE THREAD

**Issue by Mardak** [eslint/eslint#6454]
**What version of ESLint are you using?**
2.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
`{ "rules": { "padded-blocks": ["error", "never"] } }`

**What did you do? Please include the actual source code causing the issue.**
```js
{

  0
}
```

**What did you expect to happen?**
```js
{
  0
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
{
0
}
```

Introduced by #6393 for #6320.

**Comment by nzakas** [comment]
Oops, thanks for the report.
