### ISSUE TITLE
v2.13.0 breaks requiring of relative files by changing the PWD

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#6458]
**What version of ESLint are you using?**
v2.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```json
{
  "extends": "./index.js",
  "rules": {
    "comma-dangle": 0
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
`eslint .`

**What did you expect to happen?**
Linting.

**What actually happened? Please include the actual, raw output from ESLint.**
replaced the project root path (ie the current directory) with `$PWD`
```
Cannot read config file: $PWD/node_modules/index.js
Error: Cannot find module '$PWD/node_modules/index.js'
Referenced from: $PWD/.eslintrc
Error: Cannot read config file: $PWD/node_modules/index.js
Error: Cannot find module '$PWD/node_modules/index.js'
Referenced from: $PWD/.eslintrc
    at Function.Module._resolveFilename (module.js:440:15)
    at module.exports ($PWD/node_modules/resolve-from/index.js:14:16)
    at module.exports ($PWD/node_modules/require-uncached/index.js:11:17)
    at loadJSConfigFile ($PWD/node_modules/eslint/lib/config/config-file.js:161:16)
    at loadConfigFile ($PWD/node_modules/eslint/lib/config/config-file.js:200:22)
```

Note that this works fine after `npm install eslint@2.12` but fails after `npm install eslint@2.13`

**Comment by ljharb** [comment]
The eslint config in question is https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/.eslintrc, if that's helpful.

**Comment by ilyavolodin** [comment]
I think this is related to https://github.com/eslint/eslint/issues/6450

**Comment by ljharb** [comment]
Sounds like it's probably a duplicate of #6450 :-)

**Comment by mysticatea** [comment]
I think so, too.
I close this issue, then reopen if it's wrong.
