### ISSUE TITLE
Cache is deleted when linting text

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#6459]
**What version of ESLint are you using?**
Master

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
N/A

**What did you do? Please include the actual source code causing the issue.**

Given a directory with a file and an `.eslintcache`:
```
> tree -a
.
├── .eslintcache
└── foo.js
```

Running eslint on text with `--stdin` causes the `.eslintcache` file to be deleted:

```
> echo "var foo=42;" | eslint --stdin
> tree -a
.
└── foo.js
```

**What did you expect to happen?**

Since the cache is only used when executing on files, I would not expect the `.eslintcache` file to be deleted.  This causes problems when using eslint in a text editor like Atom, because it means as soon as a file is opened (and therefore linted), the cache file is deleted (see https://github.com/AtomLinter/linter-eslint/issues/587).  

I believe this is because the code which deletes the cache is too high in the CLIEngine execution [right after instantiation](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L460).  It could likely be moved into `executeOnFiles` as an `else` to [this check](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L641).

**Comment by nzakas** [comment]
Yeah, seems like a bug.

**Comment by kaicataldo** [comment]
I'd like to take a look at this one if no one has objections - want to familiarize myself more with the core code

**Comment by IanVS** [comment]
Sure, this should be pretty straight-forward, I think.

**Comment by kaicataldo** [comment]
Finally got around to looking at this and am finding myself confused - what is the desired behavior? According to http://eslint.org/blog/2015/09/eslint-v1.4.0-released, it seems like it's working as intended - the cache is deleted when ESLint is run without the `--cache` flag. If that isn't the intended behavior, what is? Thanks in advance!

**Comment by platinumazure** [comment]
Since the cache only has meaning when ESLint is run on files, maybe there's no need to wipe the cache when `--stdin` option is passed to CLI. At least, that's my take on it.

**Comment by IanVS** [comment]
Yes, that's right. Deletion should move inside executeOnFiles.

**Comment by nzakas** [comment]
What about when `--stdin-filename` is used? Any difference there?

**Comment by kaicataldo** [comment]
Okay, got it - thanks!

**Comment by IanVS** [comment]
I would say no, that should not make a difference.  When `--stdin-filename` is used, we still call `executeOnText`, which bypasses all of the cache application logic.  There's no chance in _using_ a cache when linting straight text, so I argue that it also should not be _deleting_ the cache either.

**Comment by IanVS** [comment]
To give a little more explanation, I run eslint in my editor (Atom), which lints using `--stdin` and `--stdin-filename`.  Linting there is quick, because it only runs on one file-worth of text at a time.  When I'm ready to commit changes, I run an npm script which lints the entire codebase with `--cache`.  I would like the cache to persist between my `npm run lint` executions, because without it linting can take quite a while.

**Comment by kaicataldo** [comment]
Opened a PR - thanks for letting me take this on :) Most of my work has been in rules so far, and I'm eager to get to know the core code better!
