### ISSUE TITLE
Chore: Remove dead code in excuteOnFiles

### ISSUE THREAD

**Issue by ahutchings** [eslint/eslint#6467]
The "processed" identifier is not read from anywhere within executeOnFiles. All tests pass after removing it.

I've submitted #6466 to address this.

**Comment by ilyavolodin** [comment]
I was just looking at that code the other day, and also noticed that `processed` is no longer in use. I think that might've been a result of some refactoring, and it also might be the reason for https://github.com/eslint/eslint/issues/6302
If we are merging in https://github.com/eslint/eslint/pull/6305 I think it should be safe to remove this code now.
