### ISSUE TITLE
Rule addition:: newline before & after logical constructs(if-else, switch blocks)

### ISSUE THREAD

**Issue by sagiavinash** [eslint/eslint#6473]
logical constructs need to be as clear as possible as they can easily get messy.
so a newline between these conditions let logical constructs stand out in the codebase.

1. newline between leading code & logical construct
2. newline between logical construct & trailing 

```
/* if-else constructs */

// code leading the conditional block
*** newline needed ***
if (isConditionMet) { // logical construct start
  // do something...
} // logical construct end
*** newline needed ***
// code trailing the conditional block
```

```
/* switch blocks */

// code leading the conditional block
*** newline needed ***
switch (value) { // logical construct start
  // some code
} // logical construct end
*** newline needed ***
// code trailing the conditional block
```

This rule is a plain javascript rule and doesn't depend on any other rule. Please consider this request.

**Comment by aubergine10** [comment]
This could potentially be an option on `brace-style` rule? http://eslint.org/docs/rules/brace-style

**Comment by aubergine10** [comment]
Looks like the `space-before-blocks` rule might already do what you want @sagiavinash ? 

http://eslint.org/docs/rules/space-before-blocks

**Comment by sagiavinash** [comment]
@aubergine10 

1. brace-style -> is about position of braces within a logical construct

2. lines-around-comment - this is the desired behaviour but it applies only to comments. we want it for logical constructs like if-else and switch constructs

there are enough rules on how to write code withing a logical construct but none regarding before and after. :(

**Comment by aubergine10** [comment]
Would you want something similar with `class` blocks? Also, what about loops - `while`, `for`, etc?

**Comment by sagiavinash** [comment]
@aubergine10 ya makes sense for them too
but this rule should apply only when there is leading or traling code.
imagine if we have nested loops we wouldnt want space above and below the the inner loop.

**Comment by ilyavolodin** [comment]
I'm thinking this might be added to `padded-blocks` as an `outside` option. Configuration might become complicated but would look something like this:
```js
"padded-block": ["error", { "inside": { "blocks": "always", "switches": "always", "classes": "always" }, "outside": { "blocks": "never", "switches": "always", "classes": "always" }}]
```

**Comment by sagiavinash** [comment]
@ilyavolodin using an existing rule is a low hanging fruit, but has it ever been that a rule has been extended this way to add nesting to the existing json config.

**Comment by nzakas** [comment]
Already being discussed on https://github.com/eslint/eslint/issues/3092. Please continue the conversation there.
