### ISSUE TITLE
Docs: Error in Pull Requests guide?

### ISSUE THREAD

**Issue by aubergine10** [eslint/eslint#6474]
These sections in PR guide:

* [Rebase on to upstream](http://eslint.org/docs/developer-guide/contributing/pull-requests#step-3-rebase-onto-upstreama-namestep3a)
* [Rebasing](http://eslint.org/docs/developer-guide/contributing/pull-requests#rebasing)

> `git fetch upstream`

Gives me this error:

```
$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ilyavolodin** [comment]
Looks like we are missing a step with `git remote add upstream git@github.com:eslint/eslint.git`

**Comment by nzakas** [comment]
That's part of the development environment guide, which is referenced at the top of the page. http://eslint.org/docs/developer-guide/development-environment#step-3-add-the-upstream-source

I was trying not to duplicate information.

**Comment by kaicataldo** [comment]
Makes sense - maybe we could put a little note with a link to the dev environment guide. Something alone the lines of:
> If you haven't added the upstream source already, follow [these instructions](http://eslint.org/docs/developer-guide/development-environment#step-3-add-the-upstream-source) before proceeding.

**Comment by nzakas** [comment]
Fine by me, I just don't want the same instructions in multiple places.

**Comment by kaicataldo** [comment]
I actually wonder if we can just make it clearer that the instructions expect the user to have gone through the dev environment setup steps prior to going through the [Working with Code](http://eslint.org/docs/developer-guide/contributing/pull-requests#working-with-code) section, rather than adding another reference/path to get to that information (which can be confusing). I know it's already there, but maybe we can make it stand more visually or something.

**Comment by aubergine10** [comment]
There is also a recurring issue that people updating docs often miss the exception (regarding new issues only required for code commits) in the bullet list at top of page. [example from earlier today](https://github.com/eslint/eslint/pull/6485#issue-161304693) (I also made this mistake first time I did a doc update PR)

In addition, there seems to be something missing in that guide relating to ensuring that PRs only contain a specific group of commits, eg. from specific branch. That's main issue I'm currently struggling with - if I do a PR it seems to include anything from any existing non-merged PRs in the new PR. (This is most likely due to me being clueless about github and just pasting in commands from the guide monkey style).

**Comment by kaicataldo** [comment]
@aubergine10 Hm, yeah, sounds like maybe you're using a different flow. To keep this issue on topic, want to drop by the [ESLint Gitter chatroom](https://gitter.im/eslint/eslint) to talk about the issues you're having when you make PR's?

As for the issue of making these docs clearer, I think the bigger issue might be that a lot of newcomers might not even find this page at all. We could probably do a better job of simplifying/making the important information easier to find. 

Related issue: https://github.com/eslint/eslint/issues/6380
Excerpt from the issue:
> On eslint I felt a little overwhelmed. Especially because I was just looking for rules. (I am coming from jscs and was trying to see how progress is going)

> On eslint there is the big get started that grabs your vision but trying to find where the rules or how to contribute takes time to find it. Then there is news stuff and below that there are links to about and rules. But they take a while to find.

**Comment by aubergine10** [comment]
@kaicataldo I'm on gitter, give me a mention or PM when you're online.

For me, personally, the issue with the contrib guides is that there seems to be two distinct flows merged in to one - changes to docs, and changes to code. They are both very different IMO, yet eslint treats them mostly as the same workflow (with exception of not needing a new issue for doc-only PRs). As I'm mostly focussing on docs, I knew I had to do a PR so went straight to the PR guide. I mostly ignored the development stuff (like setting up a dev environment) because in my mind _I'm not doing development_, I'm merely editing a bunch of markdown files. From a documentation perspective, the whole process feels overcomplicated and cumbersome, but that's probably a separate discussion.

**Comment by kaicataldo** [comment]
I personally don't feel like the workflow is different between code and docs contributions (having done a fair number of both now). Both require forking the repo, setting up the remote upstream, running the tests (this lints markdown files too), and using branches and pull requests to make contributions. The only differences that stand out to me are that an issue isn't required for docs changes, that tests aren't written for the markdown files, and that the contributor is editing markdown files rather than JavaScript.

**Comment by nzakas** [comment]
Yeah, we are getting way too far off topic now. Let's keep this issue discussing what changes we can do to make sure things are clear with respect to rebasing.

**Comment by aubergine10** [comment]
There's two things that can happen when you do a `git fetch upstream` which could be handled with a note under the [first use](http://eslint.org/docs/developer-guide/contributing/pull-requests#step-3-rebase-onto-upstreama-namestep3a) of the command, like so:

```
git fetch upstream
git rebase upstream/master
```

> If you get an `'upstream'` error, follow [these instructions](http://eslint.org/docs/developer-guide/development-environment#step-3-add-the-upstream-source). If you get an `SSH Key Audit` error, follow [these instructions](https://help.github.com/articles/error-we-re-doing-an-ssh-key-audit/).

**Comment by mysticatea** [comment]
Sorry, though I'm not read all of this thread.

I'm wondering why is the guide using `upstream` as a remote?
Cloned repository has a remote which is named same as the organization of the original repo automatically.
So we can use the following commands without extra setup:

    $ git fetch eslint
    $ git rebase eslint/master

The `eslint` is the name of ESLint's organization.

**Comment by nzakas** [comment]
@mysticatea hmmm, are you sure? I don't think remotes are setup that way. See https://help.github.com/articles/syncing-a-fork/

**Comment by platinumazure** [comment]
@mysticatea Most users, especially users who do not have contributor access to ESLint, have to fork the repository on GitHub first and then clone their fork onto their local machine. Thus, they have to use `git remote add` to add the ESLint remote repository and do not clone the ESLint repository directly.

From what I've seen, it's a fairly common convention to use `origin` as the name of your clone remote, and `upstream` as the name of the remote for the original source code that was used as the base for the GitHub fork.

**Comment by aubergine10** [comment]
Here's what I currently have after doing `git remote add upstream git@github.com:eslint/eslint.git`:

```
$ git remote -v
eslint    https://github.com/eslint/eslint.git (fetch)
eslint    https://github.com/eslint/eslint.git (push)
origin    https://github.com/aubergine10/eslint.git (fetch)
origin    https://github.com/aubergine10/eslint.git (push)
upstream    git@github.com:eslint/eslint.git (fetch)
upstream    git@github.com:eslint/eslint.git (push)
```

Not sure whether the `eslint` remotes were already there prior to adding the upstream tho.

**Comment by ilyavolodin** [comment]
Hmm.. interesting. This must be a new thing. It never used to setup upstream automatically for me, when I was working on the fork. So maybe @mysticatea is correct, and we don't even need to guide users to setup upstream?

**Comment by nzakas** [comment]
Can someone confirm this behavior?

**Comment by kaicataldo** [comment]
This didn't happen for me when I set up my fork - I only use the command line (no GUI's), if that makes any difference. I only had `origin` and added `upstream` (since that's how I'm used to working on GitHub projects).

**Comment by nzakas** [comment]
Ah, I'm betting that the GUIs do something for that. It's probably best just to make a simple change. I'll put together a PR.

**Comment by mysticatea** [comment]
Wow. I'm sorry, I had not realized it's GUI's work. Yeah, I always use "open in Desktop" button in website to clone. Then I work in Git Shell.
I confirmed CLI clone don't add `eslint` as a remote.
