### ISSUE TITLE
quote-props: may need tech review

### ISSUE THREAD

**Issue by aubergine10** [eslint/eslint#6477]
I'm currently revising the documentation of `quote-props` rule and suspect a code review may be required, particularly in respect to ES6. It might be that the rule already handles the scenarios listed below but the docs don't mention it (if this is the case, please let me know and I'll ensure these topics are covered in the docs).

**Template literals (backticks)**

With the advent of template literals in ES6, the risk of developers accidentally using backticks instead of single or double quotes has increased. Backticks are not a valid way of quoting property names in object literal definitions.

> Well, unless they are wrapped in square brackets:
> ```js
> var bar = "qux";
> 
> var foo = {
>   [`${bar}`]: true
> }
> 
> document.write( foo.qux );
```

Does the rule check for scenarios like this?

**Unicode identifiers**

See: https://mathiasbynens.be/notes/javascript-identifiers-es6

```js
var wat = {
    ಠ_ಠ: true, // OK

    😜: false, // error
    "😜": true, // OK
}
```

Does the rule check emoji are quoted? lol

**Comment by nzakas** [comment]
@aubergine10 is there a reason you don't run ESLint on those examples and see what happens? :)

**Comment by aubergine10** [comment]
Yup, ended up linting them last night but forgot to close issue, sry.
