### ISSUE TITLE
[request] using browser-compat-data

### ISSUE THREAD

**Issue by lv7777** [eslint/eslint#6483]
1. The version of ESLint you are using.

eslint 2.13.0

2.    The problem you want to solve.

I want to embedding https://github.com/mdn/browser-compat-data

I think this feature provide two effect.

* more clarity to internal.

I don't know with regard to eslint.(I serched internal of eslint to find where file was exsist  that defined webextensions global values,but i cant find.)
but, I think divide file to `browser-compat-data.json` can be more clarity.

* currently, eslint has "webextensions" config option on "env" key,  this feature can indicate more specific.

e.g.
```javascript
"env":{
"webextensions":true
}
```
 to
````javascript
"environment":{
"webextensions":["chrome","firefox","edge"]
}
//or
"environment":{
"chromeextension":true,
"webextension":true
}

```

___


1.    The version of ESLint you are using.

eslint 2.13.0

2.    The problem you want to solve.

I want to embedding https://github.com/mdn/browser-compat-data

これを行うことによって２つの効果が見込めます

* 内部でわかりやすくなる

私はeslintの内部がどうなっているのかわかりません(eslintの内部を調べましたがどこに設定をdefineしたファイルがあるのか、grepしても分かりませんでした。)
しかし、こういう風にファイルを分割して他から読み込むことでわかりやすくなると思います。

* 現在、environmentに"webextensions"というvalueがあるが、それをもっと詳細に分割できる。
例、
```javascript
"env":{
"webextensions":true
}
```
 to
````javascript
"environment":{
"webextensions":["chrome","firefox","edge"]
}
//or
"environment":{
"chromeextension":true,
"webextension":true
}

```

**Comment by mysticatea** [comment]
Thank you for this issue!

In fact, ESLint is importing the values of environments from an external package -- [globals]
This request is a thing about specific platforms, so I think it's proper as a plugin rather than we add it to core.

> 実は、ESLint は外部パッケージ ([globals]) から env の定義をインポートしています。
> このリクエストは特定のプラットフォームに関するものなので、私はコアに追加するよりも、プラグインを作る方が適切であると思います。

[globals]: https://www.npmjs.com/package/globals

**Comment by lv7777** [comment]
>  実は、ESLint は外部パッケージ (globals) から env の定義をインポートしています。

なるほど。だとするとgrobalesのほうに投げたほうがよかったですかね？

> 特定のプラットフォーム

ここでいうプラットフォームっていうのはブラウザのことですよね？
ブラウザなら一般的に周知されているし特定というほどではない気がします。
envの"node"も一応プラットフォームに関することですし。

**Comment by mysticatea** [comment]
> ここでいうプラットフォームっていうのはブラウザのことですよね？

Nope. This request is more specific for each product. Granted, ESLint has env's values for specific products. But unfortunately, we don't want to add more things for specific products into core. Instead, we are recommending making a plugin. (e.g., we didn't accept a Node-specific rule before: #6146) 
Plugins are the system to make diversity as preventing the increase of core's responsibility and maintenance cost.

> なるほど。だとするとgrobalesのほうに投げたほうがよかったですかね？

Similarly, [globals] package seems to be not accepting new environment values. (please see README of the package)


[globals]: https://www.npmjs.com/package/globals

**Comment by lv7777** [comment]
> we didn't accept a Node-specific rule before: #6146

I saw that and understand concept of the repo and consent your plan.
So I closing the issue and investigate how to produce eslint plagin.

thanks.

**Comment by lv7777** [comment]
closed.
more info see https://twitter.com/levena_evenas/status/744906541476655104
