### ISSUE TITLE
Feature request: Include rule option defaults in rule's metadata

### ISSUE THREAD

**Issue by SimenB** [eslint/eslint#6495]
**What version are you using?**
2.13.1

**What did you do?**
Tried to figure out default for rules without parsing the code (impossible) or the docs (difficult, but I don't think it's impossible)

**What happened?**
I failed 😆 

**What did you expect to happen?**
I would like some declarative way of defining rules defaults. Both to make it easier to implement a rule (as all of the `(context.options || {}).someOption || false` will hopefully disappear), and for my use case, which is bundle information about all rules included in a shared config, at least in the repo.

This is probably requested before, but I was unable to find an issue for it when searching

**Comment by ilyavolodin** [comment]
This is a duplicate of https://github.com/eslint/eslint/issues/5418 JSON Schema, that we use to declare rule's options already have support for `defaults`. We are just not using it properly.

**Comment by SimenB** [comment]
Indeed it is! Any particular reason why it's still `evaluating` after 4 months?

**Comment by ilyavolodin** [comment]
@SimenB Because we are not sure how to implement it properly, and what the output format should be. And it also fell off everyone's radar.
