### ISSUE TITLE
inquirer version problem

### ISSUE THREAD

**Issue by Poplava** [eslint/eslint#6503]
```
+-- eslint@2.13.1
| `-- inquirer@0.12.0 
`-- inquirer@1.0.2 
```

I use ```inquirer``` in my dev environment. And when I install deps by running ```npm i``` I got a problem with dependencies. ```npm``` installed only ```inquirer@0.12.0``` and my script is breaking. To make my script working I must run ```npm i inquirer@1.0.2``` to solve this deps conflict.

It is not a big problem, but it will be good to solve it.

I propose to update ```eslint```'s ```inquirer``` dep to ```inquirer@1.0.2```

**Comment by Poplava** [comment]
But it needs some code changes. Because ```inquirer``` is using promises instead of callbacks since v1.

**Comment by alberto** [comment]
If you `npm install --save inquirer@1.0.2` it should install both.

**Comment by Poplava** [comment]
I have those in `package.json`:

```
  "devDependencies": {
    ...
    "inquirer": "^1.0.2",
    ...
  },
  "dependencies": {
    ...
    "eslint": "^2.13.0",
    ...
  }
```

But `npm` decides to install only 0.12 version required by `eslint` (it seems because `eslint` is prod dependency).

`npm install --save inquirer@1.0.2` helps once. But when you install from scratch - this issue happen again.

**Comment by nzakas** [comment]
I'm not opposed to upgrading Inquirer, but that will likely only help for a while until a new version is released. It seems like you should contact npm about this use case.

**Comment by alberto** [comment]
Closing since this looks like an npm issue.

**Comment by xdamman** [comment]
I have the same issue. Has anyone solved this?
