### ISSUE TITLE
Rule Proposal: Enforce a maximum number of line per file

### ISSUE THREAD

**Issue by hwclass** [eslint/eslint#6507]
Hi all,

This is just a rule idea. Some developers can expect to see their codebase with small code files seperated into small pieces. It also encourages decoupling.

This rule is just stylistic.

This could be a rule for some idealistic reasons. During some large scale application development, for some reasons like seperation of concerns and etc., you might hope to see a code file which is not exceeding the line number, for example: 50. 

I would create this rule as well.

My configuration:
Version: 6.0.4
Parser: Babel-ESLint

Thanks.

**Comment by mysticatea** [comment]
Thank you for this issue.

[max-lines](http://eslint.org/docs/rules/max-lines)?

**Comment by hwclass** [comment]
Cool, thanks @mysticatea. My search criteria failed. 👍 

We can close the proposal.
