### ISSUE TITLE
rule extension: camelcase ignore prefix/suffix/patterns before validating

### ISSUE THREAD

**Issue by pabigot** [eslint/eslint#6524]
I'd like to provide optional settings that relax the constraints on `camelcase` to support the use of non-conforming identifiers in cases where style requires them.

The driver for me is projects where variables and properties that hold physical measurements must indicate the units of measure in a suffix with an underscore separator.  For example `ambientTemperature_cCel` or `centerFrequency_kHz` should be allowed as properties or variables. When this was [discussed](https://github.com/jscs-dev/node-jscs/issues/2029) prior to acceptance in [JSCS](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers) other use cases were NPM script config values (`process.env.npm_package_config_MY_ENVIRONMENT_VARIABLE`) and the Google style for [optional parameters](https://google.github.io/styleguide/javascriptguide.xml?showone=Naming#Naming) `opt_varName` and `var_args`.

My proposal is to extend the `camelcase` object option with three properties, the value of each of which is each is an array of String or ESTree [RegExpLiteral](https://github.com/estree/estree/blob/master/spec.md#regexpliteral) objects:

* `allowedPrefixes` identifies text which, if it appears at the start of an identifier, is stripped off before checking the rest of the identifier against the camelcase expectations;
* `allowedSuffixes` does the same for text that appears at the end of the identifier;
* `exceptions` are full identifiers or patterns where violations of camelcase are ignored

For example, the Google style options could be supported by:

* ~~`"allowedPrefixes": [{"regex": {"pattern": "^opt_"}}]`~~
* ~~`"allowedPrefixes": [{"regex": {"pattern": "opt_"}}]`~~
* `"allowedPrefixes": ["opt_"]`
* `"exceptions": ["var_args"]`

An example to support identifiers holding frequency measurements with various multipliers would be:

* `"allowedSuffixes": [{"regex": {"pattern": "_[kMG]?Hz"}}]`

which would allow `baseBand_MHz`, `channelStep_kHz`, `offset_Hz` and others.

Before I proceed with this, are there strong feelings against adding this feature, or an alternative interface that would be preferred?

**Comment by platinumazure** [comment]
@eslint/eslint-team Thoughts on this proposal? Seems decently well flushed out to me, we would just need a champion and three :+1: votes.

**Comment by mikesherov** [comment]
👍

**Comment by ilyavolodin** [comment]
Seems reasonable to me. :+1:

**Comment by aubergine10** [comment]
If using regex, why have separate options for prefix vs. suffix? The regex can state whether it applies to start or end of string...?

**Comment by pabigot** [comment]
@aubergine10 Thanks for raising that.  I mis-wrote the example regex to include an anchor that should not have been there.  I've corrected the original description.

One reason  is to make the three cases consistent: all three take strings or regexps.  For example I might want a suffix string `_Cel` and a suffix regexp `_[kMG]?Hz`.  In both cases the fact it's a suffix is more relevant than that it's expressed as a string or regexp, and this is indicated by putting it in the `allowedSuffixes` property.  The regex is simplified by skipping the explicit anchor: a match is recognized when it occurs at the start (prefix) or end (suffix) of the identifier.

A key point for prefix and suffix is that whatever doesn't match the identified affix remains subject to the original test.  For example with a suffix exclusion `_Cel` I'd want `insideTemp_Cel` to be allowed but `outside_temp_Cel` to produce a diagnostic.

If the difference between prefix and suffix were removed for regex affixes in favor of explicit anchors with something like:

    allowedAffixes: [{regex: {pattern: '^opt_'}}, {regex: {pattern: 'req_'}}]

the absence of an anchor in the second "affix" results in confusion: `foo_req_bar` matches internally, so what part of the other pieces must be checked against the camelcase requirements?  (Using capture groups just becomes ugly really quickly.)

With `exceptions` the interpretation is different: if the identifier as a whole is (exactly) the string or matches (anywhere) the regex, it's passed without further checking of any sub-identifier.  In that case the anchors would need to be explicit to be relevant: for example using this to accept any identifier that begins with `ignore` regardless of case and presence of underscores:

    exceptions: [{regex: {pattern: "^ignore", flags: "i"}}]

**Comment by nzakas** [comment]
Is there a reason the same thing can't be accomplished already using `id-match`? http://eslint.org/docs/rules/id-match

**Comment by pabigot** [comment]
@nzakas It might be technically possible.  The complexity of trying to specify the conditions correctly would become horrifying.  I suspect the example rules for Google given above (which are fairly simple) would become something like:

    'id-match': ['error', '^var_arg|((opt_)?([a-z]+([A-Z][a-z]+)*))$']

The id-match proposed regex for camelcase doesn't match what the camelcase rule does, so to get it right it'd have to be extended to support the exception for constants like `WATER_FREEZES_degF`.

In one project I have 18 distinct suffix strings to match measurement units for various physical properties.  Updating an array to add a new one is easy, while maintaining them in a single regex would be error-prone.

IMO id-match is not a viable solution to this need.

**Comment by nzakas** [comment]
My larger point is that this proposal is about using the camelcase rule to enforce something that is not camelcase. I think we should be discussing how to modify `id-match` instead.

**Comment by pabigot** [comment]
I see this as refining what camelcase applies to without changing the general concept of what style should be used for identifiers exclusive of encoded metadata.  I'd want to see a proposal for how `id-match` could be modified (without completely breaking its existing uses) before assessing whether such modifications would meet the use cases I've described.

Again I note that `id-match`'s proposed camelcase pattern does not in fact match what `camelcase` does.  This suggests that a purely regex-based solution is unlikely to be optimal.

I'd be open to infrastructure that, given an identifier, returns the sub-identifier to which style rules apply---allowing it to augment `camelcase` or `id-match` or whatever---but am not convinced the added complexity is warranted.

**Comment by nzakas** [comment]
@pabigot part of the problem with the `camelcase` rule is that it's very one-dimensional and takes us a bit away from our "we don't recommend styles" mantra. Part of the thinking behind `id-match` was to start to get away from hammering camelcase and think more about generic solutions regardless of the casing preferences of our users. 

> Again I note that id-match's proposed camelcase pattern does not in fact match what camelcase does. This suggests that a purely regex-based solution is unlikely to be optimal.

`camelcase` uses regular expressions as well, there's nothing about your use case that precludes regular expressions nor does it preclude adding more options to `id-match` to make mixing and matching styles easier.

That said, it's just my opinion. I'd like to hear from the team members who gave a :+1:.

**Comment by pabigot** [comment]
My proposed solution is [available in my fork](https://github.com/pabigot/eslint/compare/master...issue/6524?expand=1).

It's not suitable for a pull request because it's in three commits, and I don't know whether you'd prefer them squashed or to have issues for each one.

Also I haven't updated the documentation since if it's not something that will be merged there's no point.

Let me know whether this is of interest, and if so how you want me to deal with the multiple commits.  If it's not something suited for eslint merging I'll create a plugin for use in projects where this feature is required.

**Comment by pabigot** [comment]
@nzakas @platinumazure It doesn't look like this is getting much traction.  I've gone ahead and implemented what I need in [eslint-plugin-pabigot](https://github.com/pabigot/eslint-plugin-pabigot).  That path was much easier, as I could support both the `camelcase` and `id-match` base styles without having to worry about backwards compatibility.

**Comment by markelog** [comment]
Since this options are used in Google/Grunt code styles and was present in JSCS is there any ideas how we can achieve parity? Or we already have? If so can we add such examples in the docs?

**Comment by Kryten0807** [comment]
I'd like to see an `exceptions` argument on the camelcase rule. I have legacy code which is pulling data from a database in which the column names contain underscores. I'd like to be able to implement this on a per-module basis.

For example, I have a module with code that works with customer objects containing fields like `first_name`, `last_name` - I'd like to make exceptions for those fields, while still flagging any other instances of variable names that violate the rule.

Ideally, I'd like to refactor the database & the legacy code to remove these underscores, but that's not practical.
