### ISSUE TITLE
can not parse double colon in es7

### ISSUE THREAD

**Issue by shengxinjing** [eslint/eslint#6527]
**What version of ESLint are you using?**
2.13.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

eslint-config-airbnb

**What did you do? Please include the actual source code causing the issue.**

I use :: operator like this ::this.resolve in es7 . I guess it has the same effect as this.resolve.bind(this).

eslint gives the error message is  "Parsing error: Unexpected token : " . this happens in http://eslint.org/demo/

![image](https://cloud.githubusercontent.com/assets/1905176/16334172/051beb22-3a32-11e6-92c6-56a8a4591d7b.png)

**What did you expect to happen?**
can parse double colon well
**What actually happened? Please include the actual, raw output from ESLint.**
no error message and parse the file

**Comment by vitorbal** [comment]
hi @shengxinjing, eslint doesn't support the double-colon syntax yet.
You might want to use the [babel-eslint](https://github.com/babel/babel-eslint) custom parser for that. If you have any other questions feel free to drop by the [Gitter chatroom](https://gitter.im/eslint/eslint) and we'll be happy to help out!

**Comment by ilyavolodin** [comment]
`Function Bind Syntax` is a stage 0 proposal at this point, and is not part of ES7 specification. ESLint doesn't support anything below stage 4 on it's own. As @vitorbal mentioned, if you want to use experimental features, you need to use `babel-eslint`.
