### ISSUE TITLE
No undefined import rule?

### ISSUE THREAD

**Issue by olalonde** [eslint/eslint#6541]
I couldn't find if there was a rule to prevent importing undefined identifiers. e.g.:

a.js
```javascript
export const a = 1;
```

b.js
```javascript
import { oopsDoesNotExist } from './a'
```

Should return an error in `b.js` because oopsDoesNotExist will be undefined.

Is there such a rule? Otherwise, that would be a feature request.

**Comment by btmills** [comment]
`eslint-plugin-import`'s [`named` rule](https://github.com/benmosher/eslint-plugin-import/blob/a7d627ede2e4b4b7edce116b92b73703af886de5/docs/rules/named.md) should cover this for you!

**Comment by Aprillion** [comment]
I got `TypeError: Cannot read property 'contextTypes' of undefined` reported by Jest+Enzyme and figured out the root cause is mismatch in export/import, so big thanks for connecting my "undefined import" google search with this eslint plugin 🥇
