### ISSUE TITLE
no-es2015-of

### ISSUE THREAD

**Issue by stevegibbings** [eslint/eslint#6544]
I encountered this during a code review with a colleague who assumed we were including the babel-polyfill in our project. Chrome@50.0.2661.102 does not log a js error and fails silently. It's intended to be in Chrome@51.

We (@immediate_media) use eslint to inforce standards and protect us from making easily encountered errors. I feel it would be very useful to support coding standard and browser support decisions of es2015 features like for..of. Perhaps anything that is not transpile-able?

**When does this rule warn? Please describe and show example code:**

Fails if for..of used

for (const item of my_array)

**Is this rule preventing an error or is it stylistic?**

potential for a silent error if not polyfilled

**Why is this rule a candidate for inclusion instead of creating a custom rule?**

for..of isn't transpiled by babel and I would think this would be useful to others.

**Are you willing to create the rule yourself?**

Absolutely happy to have a go!

**Comment by mysticatea** [comment]
Thank you for this issue.

I guess you can use [no-restricted-syntax] rule for this.

    "no-restricted-syntax": ["error", "ForOfStatement"]

[no-restricted-syntax]: http://eslint.org/docs/rules/no-restricted-syntax

**Comment by stevegibbings** [comment]
Thanks. doh! I hadn't appreciated that rule was there. Sorry my bad. I think we should close this issue?

**Comment by mysticatea** [comment]
Yes, I'll close this issue as this has been solved. :smile: 
We are not accepting rules to disallow specific syntax currently since it's overlapped with `no-restricted-syntax` rule.
