### ISSUE TITLE
no-extra-parens with assigning a ternary conditional

### ISSUE THREAD

**Issue by kewisch** [eslint/eslint#6546]
**What version of ESLint are you using?** 2.13.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** `'no-extra-parens' : [2, 'all']`

**What did you expect to happen?**
I would like to be able to write this:
```
let foo = (bar ? baz : quux);
```
but still benefit from the remaining features of no-extra-parens. In other words, I would like to allow parens around ternary conditionals when assigned to a variable. I've also tried with all the exceptions mentioned in the docs.

**What actually happened? Please include the actual, raw output from ESLint.**
`ESLint: Gratuitous parentheses around expression. (no-extra-parens)`

This is similar to #6513 but for assignments and ternary conditionals. If it can be handled in that issue feel free to duplicate.

**Comment by michaelficarra** [comment]
Exceptions to core rules are only added if the style is common. I have never seen this style. Are you claiming that this is common? If so, can you provide evidence?

**Comment by kewisch** [comment]
I am not sure what qualifies as evidence. Using the regex `= \([^?]+\?[^:]+:[^)]+\)`, it is used somewhat often in Firefox and the Mozilla Platform (2.2k hits) as well as in Thunderbird and Lightning, but these are all Mozilla projects (since that is where I come from). livegrep.com only shows 52 results in the github top 10k, so you may be right that this is better fit as an extension.

I'm closing this out, if you would still like to consider this please reopen.
