### ISSUE TITLE
Conflicting wrap-iife and no-extra-parens for IIFE

### ISSUE THREAD

**Issue by FarSeeing** [eslint/eslint#655]
If you have both `wrap-iife` and `no-extra-parens` rules turned on, then the following code:

``` javascript
var foo = (function() {
})();
```

 will throw an error `Gratuitous parentheses around expression  no-extra-parens` but the code 

``` javascript
var foo = function() {
}();
```

will throw an error `Wrap an immediate function invocation in parentheses  wrap-iife`.

**Comment by mcharytoniuk** [comment]
I think there is an issue with arrow functions and gratuitous expressions and JSX. The following code gives `no-extra-parens` error and it's and IIFE wrap:

```JavaScript
import React from "react";

export default React.createClass({
    "render": function () {
        return <span>
            {(() => {
                if (something) {
                    return <div />;
                }
            })()}
        </span>;
    }
});
```

**Comment by andy-hanson** [comment]
I have the "arrowFunctions" ecmaFeature turned on, and the "no-extra-parens" rule turned on.
`(a => a)(1)` is considered to have gratuitous parentheses. But without them it is a different expression.

**Comment by michaelficarra** [comment]
Yeah, that's a bug. Can you open a new issue for it?

**Comment by andy-hanson** [comment]
#2367
