### ISSUE TITLE
Link to rules broken in docs

### ISSUE THREAD

**Issue by adambuczynski** [eslint/eslint#6553]
Minor issue, the link to the rules page is broken from this page: http://eslint.org/docs/user-guide/configuring#using-eslintrecommended

It links to http://eslint.org/docs/docs/rules/ which is 404 due to the double occurrence of /docs.

**Comment by platinumazure** [comment]
Confirmed.

**Comment by alberto** [comment]
Thanks @adambuczynski for reporting!

**Comment by platinumazure** [comment]
Fixed by #6561 (commit message was just off a little).

**Comment by alberto** [comment]
oops. Thanks @platinumazure
