### ISSUE TITLE
Inconsistent rules casing

### ISSUE THREAD

**Issue by adambuczynski** [eslint/eslint#6555]
I've found that there are some inconsistent rule names/options in terms of casing.
Most rules and options seem to follow `camelCase`, but there are several that are in `PascalCase`, for example:

- `SwitchCase`
- `VariableDeclarator`

Which are both options for `indent`. Could these be renamed (or aliases created) to camel case for consistency?

- `switchCase`
- `variableDeclarator`

You'd expect consistency at least in a linter, wouldn't you ;)

**Comment by ilyavolodin** [comment]
The reason why those are PascalCase, is because they are actual AST node types. All node types are in PascalCase, and aliasing them will most likely create much more confusion than it will solve.

**Comment by adambuczynski** [comment]
@ilyavolodin right, I see, wasn't aware of that. Thanks for clarifying.

However, that might be a case in point, as people who are unaware of the underlying mechanics of the linter don't see a difference between the two and assume it's an inconsistency.

How would moving to CST affect this?

**Comment by ilyavolodin** [comment]
@adambuczynski I understand, I'm just not sure we can do much about it. We specifically note in documentation if the option accepts AST Node types, but you are correct, most of the users wouldn't know what that is.

Sorry, I don't really know much about CST, but I think they keep the same names of nodes as AST, just add more of them.

Closing, as the question has been answer.
