### ISSUE TITLE
Refactor inline config comment processing out of lib/eslint.js

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6592]
I've mentioned this in a couple of different issues (#6435, #6190), but I think we should consider moving inline configuration comment processing out of lib/eslint.js. This will make consideration of those other issues a little easier.

The main purpose of this issue (at time of posting) is to lay out a proposal and hopefully get an idea of when it will land on the roadmap. I'm aware that we have other items on the roadmap that may have higher priority. This issue is just so that when we decide we want to do it, we have some concrete notes and discussion that will help. (That said, I'm also interested in implementing if it might make it happen sooner.)

**Proposal:**
1. Create new ReportFilter module which will take responsibility for filtering lint reports (determined by config comments).
2. Extract lib/eslint.js' `disableReporting` into a ReportFilter API which would create an unbounded report disable range for each specified rule. (No real change in functionality)
3. Extract lib/eslint.js' `enableReporting` into a ReportFilter API which would add an end range to the latest-in-file report disable range last created for each specified rule. (No real change in functionality)
4. Extract lib/eslint.js' `isDisabledByReportingConfig` into a ReportFilter API which would check the rule ID and location against disable ranges for the file and return a boolean. (No real change in functionality)
5. Add unit tests for the same.

Goal is to try to do this in such a way that we can also track uses of those disable ranges and have the code be transparent and maintainable, while reducing the complexity and responsibilities of lib/eslint.js.

**Comment by nzakas** [comment]
Can you explain what you mean by "inline configuration comment processing"? It's not clear to me what you're proposing should be moved.

**Comment by platinumazure** [comment]
Hi @nzakas, I'm still working on a full proposal but here is the high-level version of what I want to move:

1. Logic in `api.report` which checks if a node being reported is within a disable range (considering both range and rule ID)
1. Comment traversal (after parsing, before linting) which determines what the disable ranges are for the above

Basically, all of those would be replaced with a module that has APIs kind of like the following:

* `addDisableRange(start, end, ruleId)`: Add a disable range, optionally with a particular rule id.
* `isReportingEnabled(start, end, ruleId)`: Check if a report with given ruleId should be reported or ignored (i.e., is the location of the report within a disable range).

To be clear, this is the processing for `eslint-disable`, `eslint-enable`, `eslint-disable-line`, and `eslint-disable-next-line`. It would probably not include `eslint` comments (i.e., inline rule re-configuration) since that's handled as a per-file config change before linting.

Does that make sense?

**Comment by nzakas** [comment]
Ah, gotcha. Sounds interesting. Looking forward to the full proposal.

**Comment by platinumazure** [comment]
Added a proposal to my first post.

**Comment by nzakas** [comment]
Proposal looks good to me. Also looks like we have a majority of TSC members giving a :+1:, so feel free to start work.

**Comment by platinumazure** [comment]
Just leaving a note here that I want to get to this pretty soon, but that I'm going to try to knock out a few JSCS compat issues first.

**Comment by platinumazure** [comment]
**TSC Summary**: This issue is accepted, but I wanted to see if this merited being included on the core roadmap project.

**TSC Question**: Should this issue be added to the core roadmap project?

**Comment by kaicataldo** [comment]
As per the discussion during today's TSC meeting, this issue has been added to the Core Roadmap.

**Comment by not-an-aardvark** [comment]
Is this still something we're planning to do?

**Comment by platinumazure** [comment]
It's somewhere on my to-do list... It might not be as big a deal anymore if
we create a Linter class in its own file, so if nothing else I'll evaluate
that PR and see if this might still be needed.
