### ISSUE TITLE
Configuration Cascading and Hierarchy not work correctly

### ISSUE THREAD

**Issue by daizhan** [eslint/eslint#6602]
**What version of ESLint are you using?**
eslint v3.0.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default parser

**Please show your full configuration:**
`~/.eslintrc.json`
```json
{
    "extends": "eslint:recommended",
    "rules": {
    }   
}
```
`~/nodejs/requires_opt/package.json`
```json
{
    "name": "requirejs_opt",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": { 
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": { 
        "requirejs": "^2.2.0"
    },
    "eslintConfig": { 
        "globals": { 
            "require": true
        } 
    } 
}
```

**What did you do? Please include the actual source code causing the issue.**
```javascript
// ~/nodejs/requires_opt/src/main.js
require.config({
    baseUrl: "./"
});

require(["index", "buy"], function(index, buy){
    console.log("test");
});

baidu();
````
```shell
cd ~/nodejs/requires_opt/src
eslint main.js
```
 
**What did you expect to happen?**
error 'require is not defined' should remove, but nothing to output.

**What actually happened? Please include the actual, raw output from ESLint.**
nothing to output. 
but if I remove `eslintConfig` from the `~/nodejs/requires_opt/package.json`，eslint is work.
![4ab1 tmp](https://cloud.githubusercontent.com/assets/5318547/16580677/1fbcda3c-42d8-11e6-8af9-a80b5ad2dc8a.png)

and buy the way,  eslint seem only look`.eslintignore` in the current working directory, can make it cascade like .eslintrc?

**Comment by gyandeeps** [comment]
Can you please run eslint with `--debug` flag and then share the output?
So in your case it will be `eslint --debug main.js`

**Comment by daizhan** [comment]
debug result 
![11c2 tmp](https://cloud.githubusercontent.com/assets/5318547/16605828/1f3c742c-4365-11e6-959c-bb3e7f6c58cc.png)

**Comment by mysticatea** [comment]
Thank you for this issue.

Since 2.0.0, ESLint does not merge `.eslintrc.*` file and the setting in `package.json`.
See also http://eslint.org/docs/user-guide/migrating-to-2.0.0#configuration-cascading-changes

**Comment by platinumazure** [comment]
@mysticatea Is this answered/should we close?

**Comment by mysticatea** [comment]
Closing as this is answered.
Please feel free to reopen if your problem is not solved.

**Comment by daizhan** [comment]
@mysticatea  it not work yet even if I replace `eslintConfig` in `package.json` with `.eslintrc.json` .
but it's ok if I run it in my home directory with any case. 
![b58a tmp](https://cloud.githubusercontent.com/assets/5318547/16641011/4416f90a-442f-11e6-985c-15d8b2b43872.png)

**Comment by mysticatea** [comment]
The `.eslintrc` file of home directory is used only if there is no project setting.
This allows that the team members and CI tools use a consistent setting of ESLint for the project.

**Comment by daizhan** [comment]
I got it. @mysticatea  thank you very much.
