### ISSUE TITLE
Version 3.0.1 Requires Node >= 4 While 3.0.0 Doesn't

### ISSUE THREAD

**Issue by DavidTPate** [eslint/eslint#6603]
**What version of ESLint are you using?** 3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** Not relevant.

**What did you do? Please include the actual source code causing the issue.** Tried to run `eslint`

**What did you expect to happen?** `eslint` would run

**What actually happened? Please include the actual, raw output from ESLint.** `eslint` errored when attempting to run due to `arrow function` in sub-dependency.

It looks like with version `3.0.1` of `eslint` and updated version of `strip-bom` was included which now has an arrow function in it. This causes `eslint` to not be able to be run on versions of node older than `v4`.

[Here's](https://travis-ci.org/DavidTPate/isuri/jobs/142535018) an example build which had the following stack trace:

(For other examples here's [Restify](https://travis-ci.org/restify/node-restify/builds/142533226) and [Request](https://travis-ci.org/request/request/builds/142532741) experiencing the same issue)

```
/home/travis/build/DavidTPate/isuri/node_modules/eslint/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/DavidTPate/isuri/node_modules/eslint/lib/config/config-file.js:23:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by gyandeeps** [comment]
This is working as expected because we only support node >= 4.0 starting eslint 3.0
We will slowly introduce ES6 into eslint code base.

**Comment by DavidTPate** [comment]
Well that's no good. Unfortunately `v3.0.0` worked perfectly fine with `Node < 4` so I'm sure a bunch of people like myself merged it only to have it break with `v3.0.1`. I do see it in the "Migration to v3.0.0" guide, but obviously didn't read it.

**Comment by platinumazure** [comment]
@nzakas Can/should we enforce this using the `"engines"` section in package.json?

**Comment by nzakas** [comment]
It's already there: https://github.com/eslint/eslint/blob/master/package.json#L116
