### ISSUE TITLE
An option for comma-dangle so that it works on function calls too

### ISSUE THREAD

**Issue by sassanh** [eslint/eslint#6610]
**When does this rule warn? Please describe and show example code:**
It should warn for this:

    func(
        a,
        b
    )

Adding a comma after b should solve it.

**Is this rule preventing an error or is it stylistic?**
stylistic

**Why is this rule a candidate for inclusion instead of creating a custom rule?**
well, it's just a simple option for comma-dangle rule.

**Are you willing to create the rule yourself?**

no

**Comment by platinumazure** [comment]
Just out of curiosity, do you need `babel-eslint` in order for that to parse correctly? I don't remember dangling commas in function calls being in the language spec (yet).

**Comment by sassanh** [comment]
Yes, I'm using babel-eslint.
The philosophy behind it is a line of code alone should always seem incomplete when it's part of a wrapped line of code and by copying it you should get syntax error from compiler. I follow this rule and I'd be happy if eslint could warn me about it.

**Comment by platinumazure** [comment]
Well, I had to ask. We might decide not to add it since it reflects syntax that's not (technically) valid/standard-compliant JavaScript. In that case, you would want to work with the eslint-plugin-babel group to add a modified comma-dangle rule which accounts for this.

Let's see what other team members say. I'm personally neutral.

**Comment by sassanh** [comment]
I see, I understand if you don't want to add a rule that is not valid in standard JS.

**Comment by ilyavolodin** [comment]
I think you should file an issue for `eslint-plugin-babel` to support this (if they don't already), since trailing commas for functions is still a Stage 3 proposal. And ESLint doesn't support anything below Stage 4.

Closing, as this is not a valid JS till at least ES2017 (or later)

**Comment by sassanh** [comment]
@ilyavolodin I see, will do.

**Comment by sassanh** [comment]
For someone who googles and comes to this page: this is already done in `eslint-plugin-babel`, the rule name is `babel/func-params-comma-dangle`.
