### ISSUE TITLE
Output fixed source for text editor tools and extensions

### ISSUE THREAD

**Issue by mrapogee** [eslint/eslint#6612]
**What version are you using?**
v2.13.1

Currently --fix changes are outputted directly to the files. I created a emacs command called eslint-fix that saves the file, executes --fix on it, then reloads the file from the source. Saving the file is an unexpected side effect. it would be terrific if we could input the buffer, get the fixed buffer, then replace it without saving anything.

Thanks!

**Comment by platinumazure** [comment]
Hi @mrapogee, thanks for the issue!

It is true that invoking `eslint --fix` will write the file back to the file system. You might be interested in using our [CLIEngine API](http://eslint.org/docs/developer-guide/nodejs-api#cliengine) (Node.js), which allows you to have finer control. Perhaps you could write a Node.js script which uses CLIEngine, and then emacs can invoke that script using the node binary?

Here's what you would probably want to do in your Node script:

1. Create a CLIEngine instance that uses mostly default options (to emulate the actual CLI)
1. Use [`executeOnFiles()`](http://eslint.org/docs/developer-guide/nodejs-api#executeonfiles) to run the linter on the current file. This will not apply fixes to disk.
1. Iterate through the results object you get back and find the `output` property of the result object for the file you just linted.
1. That output needs to go back to your emacs script-- possibly the simplest approach is just to print `output` to stdout if the emacs script is able to read stdout when spawning a process.

Then your emacs script can reload the local buffer with that information, all without persisting to disk.

Will that work?

**Comment by mrapogee** [comment]
Thanks @platinumazure 

That looks like it will work, I can use `executeOnText()` to get the exact behaviour I'd need.

**Comment by platinumazure** [comment]
Awesome! I'll go ahead and close this issue for now. Feel free to reach out again (or stop by our [Gitter chat](https://gitter.im/eslint/eslint)) if you need anything else. Thanks!

**Comment by platinumazure** [comment]
Oh, also-- good luck and do consider making your emacs integration open source so others can benefit :smile:

**Comment by aaronjensen** [comment]
@mrapogee did you end up doing this? I'm looking to do the same.

**Comment by mrapogee** [comment]
@aaronjensen Yup. I don't really have time to create a project, but here's a gist: https://gist.github.com/mrapogee/4c64a5c85064f9d907d8c9a5b4c8b045

**Comment by aaronjensen** [comment]
FYI, eslint_d.js now supports this out of the box: https://github.com/mantoni/eslint_d.js#automatic-fixing
