### ISSUE TITLE
MockFS error when testing on Node 6

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6621]
In our automated tests, there is a failure in Node 6 due to MockFS doing something. Example:
https://travis-ci.org/eslint/eslint/jobs/142938850

We should get this figured out so we are properly testing on Node 6.

**Comment by alberto** [comment]
This started failing yesterday, coinciding with the [release of node@6.3.0](https://nodejs.org/en/blog/release/v6.3.0/).

**Comment by kaicataldo** [comment]
Might be relevant: https://github.com/tschaub/mock-fs/issues/137

**Comment by tschaub** [comment]
Just started on fixes.  The v6 support in mock-fs was incomplete (missing `binding.realpath()`) and 6.3 will require a few additional changes.  Should have a new release out soon.
