### ISSUE TITLE
Need to handle Node <4 users better (show better error message, possibly lock down version)

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6623]
**The version of ESLint you are using.**

3.x

**The problem you want to solve.**

Provide better error messages when users running an unsupported Node engine version are using ESLint.

**Your take on the correct solution to problem.**

Two basic options:

1. Detect Node engine version and throw an exception for unsupported versions (using package.json to avoid hardcoding, and ideally using a pre-existing package)
1. Attempt to catch certain exceptions (anything indicating an ES6 syntax error basically) in `bin/eslint.js` and display a nicer message to the user

Not sure which is the better option (or if there is a superior third option). Let's discuss!

**Comment by alberto** [comment]
I'm not sure we should do anything here. It's clearly documented in the [migration guide](http://eslint.org/docs/user-guide/migrating-to-3.0.0) and npm already shows a warning.

**Comment by nzakas** [comment]
@platinumazure what is the problem users are having right now?

**Comment by platinumazure** [comment]
@nzakas The problem that users have is that if we use ES6 syntax, or a dependency of ours uses ES6 syntax, an unhelpful SyntaxError is raised as soon as a module is required or imported in, and it just points out the alleged syntax error in the module. The error message is confusing and unhelpful.

The error message does not do either of these two things which might make it useful:

1. Making a reference to ES6 not being supported by the Node engine
1. Making a reference to ESLint not supporting the Node engine the user is running

As a result, we've gotten a few issues and chats about "why is ESLint now throwing SyntaxErrors".

This is compounded by our first actual ES6 usage being in v3.0.1, so that even when we say "we stopped supporting Node <4 in ESLint 3.0", we sometimes get the response "but it worked in v3.0.0". That's more of an annoyance than anything else, though.

The problem I would like to solve is, if we truly can't support Node <4 due to ES6 usage, that we try to show a better error message telling them they need to install a newer version of Node (or, optionally, that they should use ESLint v2.x if they can't upgrade their Node runtime).

**Comment by nzakas** [comment]
@platinumazure people already see a warning when they install ESLint on Node < 4,  so I'm curious why you think we need a second warning? We had one instance of confusion, but we get plentyof one-off issues from people who are confused about various things, so I'm not sure why this is different.

**Comment by platinumazure** [comment]
I guess it's because npm produces a lot of output most of the time and I don't even notice warnings sometimes. I don't think it's reasonable to assume users will watch those carefully since npm is so lenient about version mismatching.

I do concede, though, that it would be *far* better if we could find some small, easily installed package that could do this for us, instead of actually implementing the logic ourselves, because I agree that the cost/benefit ratio doesn't look good otherwise.

**Comment by epoberezkin** [comment]
Node 0.10-0.12 is still used quite a lot. So if I want to test the package in travis with these node versions and also use eslint I have to install two node versions and manually switch them that would result in longer execution time and more complex setup. Would you maybe consider providing an optional build step that would make eslint supported by 0.10-0.12? It probably should be another issue...

**Comment by mysticatea** [comment]
@epoberezkin I think that linting is not required in all node versions in CI, so you can consider a use of [if-node-version](https://www.npmjs.com/package/if-node-version)-like tool.

**Comment by ljharb** [comment]
You can also configure that in your [.travis.yml](https://github.com/ljharb/is-callable/blob/master/.travis.yml#L55).

**Comment by alberto** [comment]
Should we do anything here or close this?

**Comment by gyandeeps** [comment]
I am going to say close because i haven't seen any issue which require this change/effort.
