### ISSUE TITLE
AssertionError: Error message should be

### ISSUE THREAD

**Issue by sandy11apr** [eslint/eslint#6626]
**What version of ESLint are you using?** 
"eslint": "^2.13.1"

**What parser (default, Babel-ESLint, etc.) are you using?**
    "babel-core": "^6.10.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-register": "^6.9.0",

**Please show your full configuration:**
{
  "name": "eslint-plugin-linter",
  "version": "1.0.0",
  "description": "Es Linter for proj code",
  "keywords": [
    "eslint",
    "eslintplugin",
    "eslint-plugin"
  ],
  "author": "xyz",
  "main": "lib/index.js",
  "scripts": {
     "test": "mocha ./tests/lib/rules/**/*.js --compilers js:babel-register"
  },
  "dependencies": {
    "requireindex": "~1.1.0"
  },
  "devDependencies": {
    "babel-core": "^6.10.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.0",
    "babel-register": "^6.9.0",
    "eslint": "^2.13.1",
    "eslint-config-google": "^0.6.0",
    "eslint-plugin-jasmine": "^1.8.1",
    "eslint-plugin-mocha": "^3.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "license": "ISC"

**What did you do? Please include the actual source code causing the issue.**
I am trying to add rules for match the class name UpperCamelCase

    create: function(context) {
        
        function upperCamelCase(node) {
            let UpperCamelCase = /(^[A-Z][a-z0-9]+[A-Z]$)|(^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)+$)|(^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)+[A-Z]$)/,
              nodeName = node.id.name;

            if (!UpperCamelCase.test(nodeName)) {
                console.log(nodeName)
                context.report(node, "class {{name}} does not match the naming convention.",{
                    name: nodeName
                })
            }
        }
        return {
            ClassDeclaration: upperCamelCase
        };
    }
};

Example : 
let rule = require("../../../lib/rules/match-uppercamelcase"),

  RuleTester = require("eslint").RuleTester;
 let ruleTester = new RuleTester();
    ruleTester.run("match-uppercamelcase", rule, {

    valid: [
        {
            code: "class HelloComponent {}",
            filename: "hello.component.js",
            parserOptions: { ecmaVersion: 6 }
        },
        {
            code: "class HeroListComponent {}",
            filename: "hero-list.component.js",
            parserOptions: { ecmaVersion: 6 }
        },
      
        // give me some code that won't trigger a warning
    ],
    invalid: [
        {
            code: "class helloComponent {}",
            parserOptions: { ecmaVersion: 6 },
            errors: [
                { message: "class 'helloComponent' does not match the naming convention." }
            ]
        }
    ]
});
**What did you expect to happen?**
Invalid test case should pass but getting below error please explain me how to add invalid test case to make it pass. also if you can suggest rejex for UpperCamelCase. Thanks 

**What actually happened? Please include the actual, raw output from ESLint.**

but getting error message 
 2 passing (30ms)
  1 failing

  1) match-uppercamelcase invalid class helloComponent {}:

      AssertionError: Error message should be class 'helloComponent' does not match the naming convention.
      + expected - actual

      -class helloComponent does not match the naming convention.
      +class 'helloComponent' does not match the naming convention.

      at testInvalidTemplate (C:\linter\node_modules\eslint\lib\testers\rule-tester.js:407:36)
      at Context.<anonymous> (C:\linter\node_modules\eslint\lib\testers\rule-tester.js:455:25)
      at callFn (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:422:10)
      at C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:528:12
      at next (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:342:14)
      at C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:352:7
      at next (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (C:\FDDD\FDDD_LOCAL\npm\node_modules\mocha\lib\runner.js:320:5)
@nzakas @platinumazure @DrewML

**Comment by platinumazure** [comment]
If you read the expected/actual results of your assertion, you'll see that your expected message has single quotes around the identifier name, but the `context.report()` call does not.

Assuming you want the quotes, you should report the error like this:

```json
                context.report(node, "class '{{name}}' does not match the naming convention.",{
                    name: nodeName
                })
```

**Comment by platinumazure** [comment]
As for a camelcase regex, it can definitely be simpler. Maybe start with this? (You can tweak later, if needed.)

```js
/^[A-Z][A-Za-z0-9]*$/
```

**Comment by sandy11apr** [comment]
@platinumazure Great Thanks it work . Can you please suggest me UpperCamelCase and mandatory special char in Regex 
using this now for UpperCamelCase 
 /(^[A-Z][a-z0-9]+[A-Z]$)|(^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)+$)|(^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)+[A-Z]$)/,

and uppercase + underscore mandate rejex ??

**Comment by platinumazure** [comment]
Hi @sandy11apr, please see my comment [above](https://github.com/eslint/eslint/issues/6626#issuecomment-231270580) for a first suggestion.

Can you explain what you mean by "uppercase + underscore mandate rejex"? Do you mean you need a regular expression for CONSTANT_VAR_NAMES?

If so:

```js
/^[A-Z_]+$/
```

Incidentally, you might find it helpful to read about [regular expression syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) and/or [test regular expressions online](https://regex101.com/).

Have your ESLint-specific issues been addressed, or do you still need help writing your rule or its tests?

**Comment by sandy11apr** [comment]
Yes I need Rejex for this CONSTANT_VAR_NAMES but /^[A-Z_]+$/ this will allow me to enter CONSTANTVARNAMES which should not...

Thanks for your help - I am Writing more eslint rules for Angular 2 - and following style guide (https://angular.io/docs/ts/latest/guide/style-guide.html)
for that if any thing is required i will reach you.. if you can suggest something for angualr 2 syntax eslint custom rules will be appropriated. Thanks again.

**Comment by platinumazure** [comment]
Fair warning: Regular expressions cannot (by themselves) detect words that should be split, such as in your CONSTANTVARNAMES example. What you might be able to do is use a regular expression to get the individual words (split on underscore or on camel case transition) and then validate each word against a words dictionary, but that will come with its own set of problems. Unfortunately, some problems can't be solved by a linter and need to be caught in code review. Good luck!

Closing this issue for now. Please reopen if you need me to clarify anything further, or feel free to open a new issue if you run into a new problem related to ESLint. You can also ask questions in our [Gitter chat](https://gitter.im/eslint/eslint).
