### ISSUE TITLE
Minor inconsistencies in CLI docs

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6627]
(Skipping bug report template since this is docs only)

I was reading through the [CLI docs](http://eslint.org/docs/user-guide/command-line-interface#h---help) and saw some minor inconsistencies between `-h` and `-v` (which I would expect to be pretty similar and simple):

* Both options mention that other CLI options are ignored. One option says "flags", the other "options". I like "options" better because to me "flags" represent booleans, but I can do either.
* Only `-v` has an example. A lot of other options have examples even for ridiculously trivial case, so I can add one for `-h`.

If accepted, I can knock this out pretty quickly.

**Comment by gyandeeps** [comment]
Example for `-h` will be huge since it prints all the cli options. Personally I dont think we need an example for that.

**Comment by platinumazure** [comment]
Ah, I meant just the command line, similar to what is used for `-v`.

I'm also okay with removing the example for `-v`. It's the inconsistency
between the two that bothers me.

**Comment by nzakas** [comment]
Agree that example for `-h` is overkill (especially since the output is already included at the top). Feel free to adjust the language to be more consistent.
