### ISSUE TITLE
ESLint using config file from the directory above

### ISSUE THREAD

**Issue by Muniek** [eslint/eslint#6630]
**What version of ESLint are you using?**
3.0.1, 2.9.0
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**
None or as empty as possible:

`
{
  "parser"  : "babel-eslint",
  "env"     : {
    "browser" : true
  },
  "globals" : {
    "Action"       : false,
    "__DEV__"      : false,
    "__PROD__"     : false,
    "__DEBUG__"    : false,
    "__BASENAME__" : false
  },
  "rules": {
  }
}`
**What did you do? Please include the actual source code causing the issue.**
1. I copied .eslintrc the the upper dir (mv .eslintrc ..). This eslintrc had some rules that I didn't intend to use anymore (obsolete). 
2. I removed or cleaned-up the eslintrc in the projects dir. 
3. I run either `./node_modules/.bin/eslint .` or npm run lint (which is running: `eslint .`)
(I do not have global eslint installed (or anything else than npm).)
**What did you expect to happen?**
I expected eslint to go lint the files without any rules.
**What actually happened? Please include the actual, raw output from ESLint.**
ESLint used the eslintrc from upper directory. Basically if you have such structure:
~/projects/project1
and you put a file .eslintrc in ~/projects, then if you run eslint in ~/projects/project1 , then it'll use the file from upper dir. It is also valid if you have also additional projects there:
~/projects/project2
~/projects/project3

They'd be all affected by this "common" file.

**Comment by platinumazure** [comment]
Hi @Muniek, this behavior is expected- ESLint does not claim to know your project root automatically.

You have a couple of options here:

1. If you still have an eslintrc file in the project root, add `"root": true` to it. This tells ESLint not to use ancestor directories.
2. If you don't want to use an eslintrc file at all, use the CLI flag `--no-eslintrc` or the CLIEngine option `useEslintrc: false`.

Let me know if I'm misunderstanding your problem.

**Comment by Muniek** [comment]
Thanks for quick answer @platinumazure .
I understand that ESLint doesn't need to know the project root - but why would it look for the configuration file above the file I am calling eslint from?

Case:
cd ~/projects/project1 
./node_modules/.bin/eslint . (or npm run lint which will do the same)

Why would eslint go to the upper directory looking for .eslintrc files? Also, it goes only one directory up. So if .eslintrc is in ~/ then it's not being used. What is the use of this behaviour?

My expectation would be, that when I am in ~/projects/project1, and call eslint, then first eslint is looking for config file in ~/projects/project1 , and using this config for all the nested files (and dirs). If there is any .eslintrc "deeper", then it would be applied to files "under" it - it's how e.g. gitignore files work. You would not expect .gitignore file in ~/projects to affects your git command in ~/projects/project1. I understand that git commands are tighter connected with the repository itself, but still the current eslint behaviour is highly misleading.

**Comment by platinumazure** [comment]
Well, that's why we recommend `"root": true` in project configuration files as a best practice.

**Comment by Muniek** [comment]
Alright, I understand. I am still slightly confused and believe it would be better to have it as opt-out option, but I get the technical constrains if ESLint doesn't know where is the project root.

Thank you for your time and help @platinumazure .

**Comment by platinumazure** [comment]
Glad to help @Muniek. Incidentally, if you haven't had a chance to read the ESLint documentation, you might find it pretty helpful, especially [this section](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) on Configuration Cascading and Hierarchy. Hopefully that will help everything to make more sense.

Closing this issue for now-- please reopen if I haven't answered all your questions, or feel free to stop by our [chat room](https://gitter.im/eslint/eslint) if you need help with anything else.
