### ISSUE TITLE
Make valid-jsdoc fixable (the parts that are possible)

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6633]
As I just painfully went through and updated our JSDoc comments by hand, it seems like there are a least a couple of things in `valid-jsdoc` that we can make fixable:

1. Replacing `prefer` tags
1. Replacing `preferType` types

This might be a bit tricky as I'm not sure how much location information we get from Doctrine, but worth looking at to avoid future pain.

**Comment by gyandeeps** [comment]
How we consume it inside eslint correctly, we dont have any location info for comments.

**Comment by gyandeeps** [comment]
How we currently use we dont have line numbers at all. if we activate `lineNumbers` option for `doctrine` then also we only get the line number but info on column.

**Comment by ilyavolodin** [comment]
Can we enhance Doctrine to return all location information. Since it's part of our org, it seems like that would be something doable. In general I'm :+1: if it's possible to do.

**Comment by nzakas** [comment]
There's not enough info from Doctrine for this, and it's past 21 days, so closing.
