### ISSUE TITLE
Enhancement Proposal: auto fixing of no-var

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6639]
This proposal is it makes [no-var](http://eslint.org/docs/rules/no-var) rule fixable:

- It modifies most `var` declarations to `let` declarations.
- It does not modify a `var` declaration if the declaration has redeclaration(s) ~~in the same scope~~ because `let` declarations are not allowed redeclaration.
- (It does not modify any `var` declarations to `const` declarations. If it can become a `const` declaration, `prefer-const` rule will modify it in the next step.)

```js
var a;            // => let a;
var b = 1;        // => let b = 1;
var {c, d} = obj; // => let {c, d} = obj;
var e = 1;        // not changed since this is redeclared.
var e = 1;        // 
var f = 1;        // not changed since this is redeclared.
if (a) {
    var f = 2;    // 
}
```

This would help us to apply this rule to our codebase.

**Comment by mysticatea** [comment]
- It does not modify a `var` declaration if the variable is used from outside of the scope.

```js
if (a) {
    var g = 1;
}
foo(g);
```

**Comment by ilyavolodin** [comment]
:+1:

**Comment by nzakas** [comment]
This would be awesome! 👍

**Comment by mysticatea** [comment]
Thank you.
I will work on this.
