### ISSUE TITLE
proposal: extract CLI and settings handling into separate module(s)

### ISSUE THREAD

**Issue by jokeyrhyme** [eslint/eslint#6651]
ESLint has very comprehensive and reliable CLI and settings handling features, just to name a few of my favourites:
- can use .eslintrc or .eslintrc.json or .eslintrc.yaml
- .eslintrc can "extend" from multiple installed shared configurations
- certain settings can be overridden from the command line

If we extracted these out into a separate library, other Node.js libraries could more easily provide convenient and flexible CLI surfaces, e.g. https://github.com/wooorm/retext

Is this something that you would be interested in seeing a PR for?

**Comment by ilyavolodin** [comment]
I think it's part of our long-long-term vision, but I'm not really sure we are ready for something like that right now. Also in some cases it will be problematic to separate items you listed above, since, for example, code that deals with configuration (extensions, cascading, extending, etc.) rely on our code that traverses directories.

**Comment by wooorm** [comment]
@jokeyrhyme For this particular case I suggest using [`unified-engine`](https://github.com/wooorm/unified-engine) or [`unified-args`](https://github.com/wooorm/unified-args), which are specifically designed for retext! :)

**Comment by jokeyrhyme** [comment]
@wooorm oh, thanks for the tip! I'll go check those out. :)

**Comment by jokeyrhyme** [comment]
I have other projects where it would still be ideal for me to avoid duplicating all the CLI and .rc.json behaviour, so I'll see if unified-args does the trick. As unified-args is a little unified-specific, it may still be the case that a more general baseline is still something useful to extract from ESLint (or unified-args, for that matter).

**Comment by nzakas** [comment]
Agree with @ilyavolodin -- while we have talked about it as a potential way to go in the future, we are definitely not the point where it makes sense to consider such a change.

**Comment by alberto** [comment]
Closing since it's out of scope
