### ISSUE TITLE
ignore-path .gitignore not working as expected

### ISSUE THREAD

**Issue by gauntface** [eslint/eslint#6654]
**What version of ESLint are you using?**

    $ eslint -v
    v3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

    babel-eslint

**Please show your full configuration:**

    {
      "parser": "babel-eslint",
      "extends": "google"
    }

**What did you expect to happen?**
**What actually happened? Please include the actual, raw output from ESLint.**

Eslint is looking at node_modules for code, which makes the file regex I passed in, but I had hoped this could be over by using gitignore.

    eslint --ignore-path ./.gitignore ./**/*.js

Running the above code I would expect all javascript files to be run through eslint apart from any paths that would be excluded via the gitignore file:

    node_modules/
    dist/
    npm-debug.log
    docs/
    tagged-release/
    wires

Instead, I see a huge output of the following for every node_module js file:

     0:0  warning  File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override

Am I using the ignore-path flag incorrectly?

**Comment by alberto** [comment]
You should use quotes around the argument to avoid shell expansion

`eslint --ignore-path ./.gitignore './**/*.js'`

or just

`eslint --ignore-path ./.gitignore '.'`

**Comment by gauntface** [comment]
That is awesome - thank you sooo much.
