### ISSUE TITLE
chore: combine multiple RegEx replaces with one

### ISSUE THREAD

**Issue by thefourtheye** [eslint/eslint#6669]
**What version of ESLint are you using?**

latest master

**What parser (default, Babel-ESLint, etc.) are you using?**

N/A

**Please show your full configuration:**

N/A

**What did you do? Please include the actual source code causing the issue.**

N/A

**What did you expect to happen?**

N/A

**What actually happened? Please include the actual, raw output from ESLint.**

N/A

---

I would like to propose a small improvement in the way boolean configuration values are
processed. As it is, there are two RegEx based replacements happening to clean up whitespaces
around `:`, and `,`, [here](https://github.com/eslint/eslint/blob/master/lib/eslint.js#L46-L50)

```js
    // Collapse whitespace around : to make parsing easier
    string = string.replace(/\s*:\s*/g, ":");

    // Collapse whitespace around ,
    string = string.replace(/\s*,\s*/g, ",");
```

That can actually be simplified into a single RegEx based `replace`, like this

```js
    string = string.replace(/\s*([:,])\s*/g, "$1");
```

**Comment by thefourtheye** [comment]
The proposed fix is in #6661

**Comment by platinumazure** [comment]
Thanks for writing an issue! I'd love to see the proposed PR land. :+1:

**Comment by ilyavolodin** [comment]
Since this is a very minor issue, marking as accepted.
