### ISSUE TITLE
Formatter cannot escape ASCII control characters in XML report.

### ISSUE THREAD

**Issue by Gerhut** [eslint/eslint#6673]
**What version of ESLint are you using?**

3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

Google

**What did you do? Please include the actual source code causing the issue.**

    console.log({'\b':'\\b'});

    $ eslint index.js --format checkstyle --output-file checkstyle.xml

open checkstyle.xml in google chrome

**What did you expect to happen?**

A valid checkstyle formatted XML report file.

**What actually happened? Please include the actual, raw output from ESLint.**

This page contains the following errors:

error on line 1 at column 212: invalid character in attribute value
Below is a rendering of the page up to the first error.

**Comment by nzakas** [comment]
Confirmed
