### ISSUE TITLE
NodeJS 0.12 doesn't work - dependency conflict

### ISSUE THREAD

**Issue by Kflash** [eslint/eslint#6679]
**What version of ESLint are you using?** 3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?** I expected nodeJS 0.12 to work with latest ESLint version..

**What actually happened? Please include the actual, raw output from ESLint.**

Well. ESLint uses strip-bom as dependency. Latest version 3.0.0. And there is an conflict with NodeJS 0.12. The source is in ES6 and not ES5.

Reference:
https://github.com/sindresorhus/strip-bom/issues/7#issuecomment-232689179

**Comment by jeromecovington** [comment]
Not sure if this helps, but is is possible for you to pin `eslint@3.0.0`? That version doesn't use `strip-bom` at all. https://github.com/eslint/eslint/blob/v3.0.0/package.json

**Comment by molee1905** [comment]
http://eslint.org/blog/2016/07/eslint-v3.0.0-released#requires-nodejs-4-or-higher

>ESLint v3.0.0 now requires Node.js 4 or higher. Going forward, our plan is always to support the LTS version of Node.js and periodically end-of-life support for older Node.js versions. As both Node.js v0.10 and v0.12 will be out of maintenance mode at the end of 2016, we hope that this change won’t affect too many users.

>If you still need ESLint to run on Node.js < 4, then we recommend staying with ESLint v2.13.1 until you are ready to upgrade your Node.js version.

**Comment by ilyavolodin** [comment]
As @molee1905 mentioned, starting with ESLint version 3, we dropped support for versions of Node earlier then LTS (4.0).

Closing as this is expected behavior. If you want to use earlier version of Node, please pin ESLint to version prior to 3.0
