### ISSUE TITLE
`key-spacing`: `multiLine.align.mode` is overridden, `multiLine.mode` with `align` causes an error

### ISSUE THREAD

**Issue by whizark** [eslint/eslint#6691]
**What version of ESLint are you using?**
ESLint 3.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

case1.js
```javascript
module.exports = {
    "rules"   : {
        "key-spacing"                  : [
            "error",
            {
                "multiLine" : {
                    "beforeColon": false,
                    "afterColon" : true,
                    "mode"       : "strict",
                    "align"      : {
                        "beforeColon": false,
                        "afterColon" : true,
                        "on"         : "colon",
                        "mode"       : "minimum"
                    }
                }
            }
        ]
    }
};
```

case2.js
```javascript
module.exports = {
    "rules": {
        "key-spacing": [
            "error",
            {
                "multiLine": {
                    "beforeColon": false,
                    "afterColon" : true,
                    "mode"       : "strict"
                },
                "align"    : {
                    "beforeColon": false,
                    "afterColon" : true,
                    "on"         : "colon",
                    "mode"       : "minimum"
                }
            }
        ]
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

test.js
```javascript
var a = {
    foo   : 1,
    align1: {
        foo:    2
    },
    align2: {
        foo:    3
    },
    bar: 4
};
```

**What did you expect to happen?**

Case 1
```shell
  5:5   warning  Unexpected a line break before this close brace  object-curly-newline
  6:13  warning  Unexpected a line break after this open brace    object-curly-newline
```

Case2
```shell
  1:1   error    Unexpected var, use let or const instead         no-var
  1:5   error    'a' is defined but never used                    no-unused-vars
  3:13  warning  Unexpected a line break after this open brace    object-curly-newline
  5:5   warning  Unexpected a line break before this close brace  object-curly-newline
  6:13  warning  Unexpected a line break after this open brace    object-curly-newline
  8:5   warning  Unexpected a line break before this close brace  object-curly-newline
```

**What actually happened? Please include the actual, raw output from ESLint.**

Case 1
```shell
  4:17  error    Extra space before value for key 'foo'           key-spacing
  5:5   warning  Unexpected a line break before this close brace  object-curly-newline
  6:13  warning  Unexpected a line break after this open brace    object-curly-newline
  7:17  error    Extra space before value for key 'foo'           key-spacing
```
Because of https://github.com/eslint/eslint/blob/67c3cc2fa655e9e92e01d7a88e9a9d60cd4a4ce9/lib/rules/key-spacing.js#L139

Case2
```shell
/path/to/config/case2.js:
        Configuration for rule "key-spacing" is invalid:
        Value "[object Object]" no schemas match.

Error: /path/to/config/case2.js:
        Configuration for rule "key-spacing" is invalid:
        Value "[object Object]" no schemas match.
```

Because of https://github.com/eslint/eslint/blob/67c3cc2fa655e9e92e01d7a88e9a9d60cd4a4ce9/lib/rules/key-spacing.js#L271-L321 (`multiLine.mode` isn't allowed with `align` option)

Are they designed as they are?

**Comment by btmills** [comment]
The object `align` option applies to properties that are in a group and can be aligned. Try the `case1.js` config on this:

```js
var a = {
    foo   :    1,
    align1:    {
        foo: 2
    },
    align2: {
        foo: 3
    },
    bar: 4
};
```

Since `foo` and `align1` are the only properties on adjacent lines in the same object literal, they're the only ones where `align` applies. All of the other properties are individual and will follow the rules for a `multiLine` object literal. Assuming that modified example passes, I think we're good on that part.

As for the schema error, that is a bug. `key-spacing` has a pretty complex schema, so `mode` was probably omitted by mistake.

**Comment by whizark** [comment]
@btmills Thank you for you explanation.  I had a slight misunderstanding about *align*... :flushed: 
I tried to lint the first code in [align and multiLine](https://github.com/eslint/eslint/blob/67c3cc2fa655e9e92e01d7a88e9a9d60cd4a4ce9/docs/rules/key-spacing.md#align-and-multiline) with `case1.js` config and the code actually passed, so I also tried to lint another code based on the code above.

```javascript
var myObj = {
  key1: 1, // uses multiLine

  key2:    2, // uses align (when defined)
  key3:    3, // uses align (when defined)

  key4: 4 // uses multiLine
}
```

The result is:
```shell
  4:12  error  Extra space before value for key 'key2'  key-spacing
  5:12  error  Extra space before value for key 'key3'  key-spacing
```
I'm a little confused because `multiLine.align.mode`  in `case1.js` seems to be overridden with `multiLine.mode`. Is this also a bug? Or we cannot use both `multiLine.mode` and `multiLine.align.mode` in the same time?

**Comment by btmills** [comment]
@whizark is right - `align` isn't respecting its own `mode` at all, and is instead using `multiLine`'s `mode` value.

Two steps to fixing this:

1. Change the schema to allow `mode.align`. Right now just `multiLine.align.mode` is permitted.
2. Change the code so that `mode` uses `align`'s setting, if present, when properties are part of a group.

**Comment by azhang496** [comment]
i'll work on this!

**Comment by btmills** [comment]
Great, @azhang496 - let us know if you need any help!

**Comment by azhang496** [comment]
sorry for the delay - @btmills is it necessary to change the schema? seems like this can be fixed just by changing this https://github.com/eslint/eslint/blob/67c3cc2fa655e9e92e01d7a88e9a9d60cd4a4ce9/lib/rules/key-spacing.js#L139 to `mode: toOptions.multiline.align.mode`

**Comment by btmills** [comment]
@azhang496 I'm on my phone, so I can't check to be sure, but if the scheme is left unchanged, won't the case 2 config (setting a mode under align) still throw a validation error?

**Comment by azhang496** [comment]
@btmills i can do both! i didn't realize the goal was to fix both cases, since just fixing case 1 would give the option to have different modes for `multiline` and `align`

**Comment by azhang496** [comment]
@btmills made a PR if you'd like to check it out
