### ISSUE TITLE
eslint should parse all stage 3 proposals

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#6693]
Per the discussion [here](https://github.com/eslint/eslint/issues/4352#issuecomment-232404631);

> Something being in stage 3 means, that barring some massive surprise performance issue discovered by browsers, that it almost certainly will ship. Browsers begin implementing in stage 3, since it's a stage 4 requirement that 2 browsers support something first. What this policy means is that eslint will be unable to lint code that works in half of the browsers - that doesn't seem ideal.

> ES2016 was ratified in June, so it's complete. However, the "yearly spec" is irrelevant - only what's on Github matters, which is all the things that are stage 4 (which luckily doesn't yet include any syntax changes).

In other words, I think that stage 3 - not just stage 4, and *certainly* not just when the yearly spec is ratified (which is not a meaningful milestone for implementations; stage 4 is when it's final) - should be when `eslint`'s default parser adds support for any syntax changes.

Specifically: ([proposal list](https://github.com/tc39/proposals))
 - [ ] trailing commas in function signatures
 - [ ] async functions / await keyword

**Comment by platinumazure** [comment]
Seems like this is something our TSC should discuss.

Worth noting that this is really about espree, the default parser for ESLint.

**Comment by ljharb** [comment]
Thanks, would you prefer I file it there? My hope was that it'd be an eslint policy, in the case that eslint ever switches its default parser.

**Comment by alberto** [comment]
I think we can discuss it here. I'm also removing the `tsc agenda` label for now. We can add it later if we can't reach consesus here.

@ljharb this doesn't seem accurate:
> What this policy means is that eslint will be unable to lint code that works in half of the browsers - that doesn't seem ideal.

As you said it's not until stage 4 that at least two browsers have implemented it. I understand there can be a span when 2 browsers have implemented it but the proposal hasn't moved yet into stage 4. But adding stage 3 support could also mean we add it before any browser has implemented it.

**Comment by ljharb** [comment]
@alberto Stage 4 requires a TC39 meeting; which means that it can be shipping in 2+ browsers for many months before that happens.

I agree, adding support in stage 3 means it would be before any browser has implemented it - but that's kind of the point :-) ideally a linter can help locate problems before it's too late for browsers to adapt to them.

**Comment by alberto** [comment]
> Stage 4 requires a TC39 meeting; which means that it can be shipping in 2+ browsers for many months before that happens.

That looks like a bug in the TC39 scheduler 😜

**Comment by nzakas** [comment]
@ljharb the big problem here is the overhead. Because Acorn (which Espree relies on) doesn't support anything lower than stage 4, that would mean we'd have to write the logic ourselves in Espree rather than wait for Acorn (which negates a lot of the value we get from using Acorn).

The other problem is that with stage 3, there is no way to know which ECMAScript version these features belong to. I don't think it's safe to assume that something that is stage 3 will definitely end up in the upcoming ECMAScript release, which would mean we'd have to create feature flags for each one, and that's what we tried to get away from.

So, there are a lot of logistical issues as to why I think this is a bad idea. I don't see any reason to rush to get stage 3 features supported in core when there are perfectly valid solutions like `babel-eslint` available.

**Comment by ljharb** [comment]
That's a fair concern - absolutely something in stage 3 may not make it into any given year of publication (async/await didn't make it into ES2016 and who knows if it'll get into ES2017). However, I think the thing that should be gotten away from is the concept of a "version" mattering - per-feature parser options imo are the right path forward, since "hitting stage 4" is the moment when a feature is finalized.

What that decision means is that eslint-config-airbnb will have to switch back to babel-eslint for effectively ever, since we encourage using features at stage 3, and we want to enable trailing function argument commas :-/

**Comment by nzakas** [comment]
@ljharb unfortunately, we've already found that having multiple independent feature flags for new features is a big pain for everyone (ESLint developers and users alike) and I don't see us going back to that model. 

As always, if you'd be willing to invest some time in researching and prototyping some other options, we're happy to evaluate such work.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
