### ISSUE TITLE
object-curly-spacing "never" fails when "exporting from"

### ISSUE THREAD

**Issue by mattkrick** [eslint/eslint#6695]
**What version of ESLint are you using?**
3.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
"object-curly-spacing": [2, "never"]
```

**What did you do? Please include the actual source code causing the issue.**
```
export Step1 from './Step1';
```
**What did you expect to happen?**
no error

**What actually happened? Please include the actual, raw output from ESLint.**
`There should be no space after 'export'`.
Also, when using `--fix` it corrects it to:

```
exportStep1from './Step1';
```

**Comment by alberto** [comment]
That syntax is still experimental and not supported directly by `eslint`. You should open an issue in `babel-eslint`
