### ISSUE TITLE
Rule arrow-body-style with "as-needed" kinda forces long lines of code

### ISSUE THREAD

**Issue by FredyC** [eslint/eslint#6697]
**What version are you using?**
eslint: 2.9.0
eslint-plugin-babel: 3.2.0

**What did you do?**
```js
const saveTree = (treeModel) => {
	return treesRef.child(treeModel.getId()).set(serializeTree(treeModel));
};
```

**What happened?**
_Unexpected block statement surrounding arrow body. (arrow-body-style), Line 1, Column 1_

Rule is configured as: `"arrow-body-style": [1, "as-needed"]`

**What did you expect to happen?**
Essentially I want to keep explicit return here, because it's harder to understand it at the first glance without it. Following is without the issue.
```js
const saveTree = (treeModel) => (
	treesRef.child(treeModel.getId()).set(serializeTree(treeModel));
);
```
Changing is to one-liner makes it also without issues, but in my opinion it's already too long to be readable.
```js
const saveTree = (treeModel) => treesRef.child(treeModel.getId()).set(serializeTree(treeModel));
```

Would be nice if this rule can have a option to be ignored when specified number of characters for the line inside the block is exceeded.

**Comment by alberto** [comment]
You can break the body in multiple lines like
```
const saveTree = (treeModel) => treesRef.
     child(treeModel.getId()).set(serializeTree(treeModel));

```

**Comment by FredyC** [comment]
Thanks, but I don't like that much either.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by zimme** [comment]
I would love to have an option, e.g. `"single-line"`, to allow this.
```
// Would trigger warning/error
something.map(value => { return value.id });

// Would not trigger warning/error
something.map(value => {
  return value.id
});
```
This way I can deny unnecessary arrow-body on single line callback
functions but structure longer code in a more readable way

**Comment by not-an-aardvark** [comment]
@zimme You can already check for that with [`brace-style`](http://eslint.org/docs/rules/brace-style).

```js
/* eslint brace-style: "error" */

something.map(value => { return value.id; }); // error reported

something.map(value => { // no error reported
  return value.id;
});
```

**Comment by zimme** [comment]
@not-an-aardvark, but if I'm not mistaken. That doesn't check for that unnecessary return?
```
// Error
something.map(value => { return value.id; });

// Should be
something.map(value => value.id);

// No error
something.map(value => {
  return value.id;
});

**Comment by not-an-aardvark** [comment]
I'm not sure I understand; could you clarify what you mean by "unnecessary return"?

**Comment by zimme** [comment]
Ok, tested that rule out just now and it allows and deny's what I was expecting, it just warns about `Statement inside of curly braces should start on next line` which is fine. :+1:
