### ISSUE TITLE
Rule proposal: no-null

### ISSUE THREAD

**Issue by nene** [eslint/eslint#6701]
A rule to warn when `null` literal is used anywhere in the code.

**Motivation for avoiding null**

Because of historic accident JavaScript has two null-ish values: `undefined` and `null`. The language itself uses `undefined` for any uninitialized variable and it's also the default return value of functions. Therefore one can argue that `undefined` is the natural null-value to use in JavaScript while `null` is the odd one.

The only places where one actually needs to use `null` is some API-s that require `null`. For example render() methods of React components must return `null` to render an empty component. In my experience there aren't many such API-s though. One can explicitly disable the rule for the places where one really needs to use `null`.

This rule should fall in **Best practices** category.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**

- There already exists a companion rule `no-undefined` which enforces an opposite practice: never using `undefined`. Though the docs of `no-undefined` explain that the main reason for it's existence is to avoid problems with declaring a custom variable named `undefined` - but really, wouldn't it be better to have a rule for ensuring one never declares a variable named `undefined`? Anyway, ESLint should not pick sides, so it should support both pro-undefined and against-undefined camps.
- There is `no-restricted-syntax` rule to allow one to easily disallow the use of any JavaScript syntax node. Unfortunately this doesn't help with literals which all have node type `Literal`. I don't see much reason for banning other literals besides `null` though. So I think it doesn't make sense to add `no-restricted-literal` rule for which the only actual use would be to ban `null`.
- It would be a trivial rule that would hardly require any maintenance. Creating a plugin for such a trivial thing feels a bit on the silly side.

**Are you willing to create the rule yourself?**

Yeah, already done.

**PS.** Perhaps somebody knows of a publicly available style guide that forbids `null`? Unfortunately I don't know any besides the one I created for my own company.

**Comment by platinumazure** [comment]
Hi @nene, thanks for this detailed proposal.

I like the idea of having such a rule available, but I don't know if this proposal meets the (admittedly high) [guidelines for inclusion](http://eslint.org/docs/developer-guide/contributing/new-rules#accepting-a-rule) which state, among other things, "any new rules must be deemed of high importance to be considered for inclusion in ESLint."

I can't vote for rules since I'm not on the core development team, but if I could, I would give it a :+1:.

**Comment by nzakas** [comment]
To me this seems like a very personal preference, so I'm :-1: on inclusion in the core. This would be better as a custom rule.

**Comment by nzakas** [comment]
Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

You can still create a custom rule that does exactly what you want if you still want this functionality.

**Comment by nene** [comment]
No problem... I'll probably have some fun creating a custom rule then.

**Comment by nene** [comment]
Published a custom rule for this: https://github.com/nene/eslint-plugin-no-null

**Comment by ajhyndman** [comment]
I think it's a shame that this didn't make it into core.

I would love to be able to write in a programming language where the majority of code I read didn't have two quirk-filled null-ish values that need to be hacked around all the time (with rules like `"eqeqeq": ["error", "always", {"null": "ignore"}]`).
