### ISSUE TITLE
Should we remove indent's autofix?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6702]
There are a lot of issues around indent's auto-fix, including but not limited to the following:

* Comments lose their alignment with nearby code
* Behavior is completely incorrect if fixing towards or away from a tab-based setup
* Sometimes the reasoning for an indent level is unclear or possibly incorrect (at least we get questions on that sort of thing a lot); auto-fix makes that problem worse because it can cause unwanted changes.

We have precedent of removing auto-fix when it's known to occasionally create undesirable results (eqeqeq).

Should we remove auto-fix from the rule until we have a better idea of how to proceed with it?

**Comment by ilyavolodin** [comment]
I would 👍  this, but I think it would be considered a breaking change, and we can't do that until 4.0.

**Comment by platinumazure** [comment]
@ilyavolodin I can definitely see the argument, but I think the eqeqeq one was treated as a patch. Personally I think it merits at least a minor since it's a fundamental change in behavior, though.

**Comment by nzakas** [comment]
I'm :-1:. Indenting is one of the biggest pains for developers, so I'd rather invest the time to fixing autofix rather than removing it entirely. Like the comments indenting, for example, is probably pretty easy.

Let's see if we can get to some consensus on this issue before discussing at the TSC meeting. The TSC meeting is supposed to be for problems that we aren't able to resolve on issues, and since this issue is so new, I'd suggest we try to hash it out here rather than placing it on the agenda right now.

**Comment by platinumazure** [comment]
Adding "tsc agenda" label. This can be discussed at the same time as the other indent issue listed in the linked tsc-meetings issue.

Questions I think should be considered:
* If we don't come up with a plan for fixing or rewriting indent, should we turn off auto-fix?
* Even if we do come up with a plan, should we turn off auto-fix just due to possibility of confusion/large number of potentially incorrect fixes?
* If we want to turn off auto-fix, can that be done as a patch or minor or must it be breaking?
  * When considering this question, please consider how eqeqeq was handled and whether that precedent is appropriate.

**Comment by lukeapage** [comment]
I for one get daily benefit from the existing autofix. Autofix should not mean unseen - when following good coding practices code is still reviewed, hopefully before check in and before merging. So autofix not fixing comments is a pain as i have some manual work to do, but less than if i couldnt autofix.

It seems to me the fear of bad autofixing comes more from fear of issues being raised than net benefit? Or maybe im missing something (everyone using autofix & one of the most popular rules and hasnt complained via an issue it should be disabled - thats got to be alot of people?)

In another issue i seem to recall a suggestion to disable/enable individual rules - that could help if someone finds indent partial fixing counter-productive.

**Comment by platinumazure** [comment]
@lukeapage Auto-fix works wonderfully (for the most part) if you are in a space indent environment. If you are in a tab indent environment, it is horrendous. So it's not just fear from issues being raised-- I do have personal experience.

It is possible to disable/enable individual rules from linting, but when `--fix` is specified on the command line, all linted rules that are fixable will try to auto-fix. If there was a way to disable auto-fix for a single rule, that would work well for my own use case.

**Comment by nzakas** [comment]
@platinumazure if there's a problem with tabs, then let's spend some time finding solutions. It sounds like you have code that relies in tabs, so do you have any thoughts on how to fix it?

FWIW, you can always disable a rule on the command line when you fix:

    eslint --rule 'indent:0' --fix .

**Comment by kaicataldo** [comment]
I know this issue is for autofixing in particular, but we have a very large number of issues with bug reports of the `indent` rule. Is there a larger discussion going on about how we we want to approach fixing this? Seems like it needs some attention and maybe a plan of attack (though I understand JSCS compatibility currently takes precedence).

**Comment by nzakas** [comment]
@kaicataldo yes, @ilyavolodin is going to review the open issues and put together an overview.

**Comment by alberto** [comment]
Closing per discussion in last TSC, there are plans to try to improve the situation with the `indent` rule.
