### ISSUE TITLE
spaced-comment auto generated docs artefacts

### ISSUE THREAD

**Issue by wKich** [eslint/eslint#6705]
In the rule description on http://eslint.org/docs/rules/spaced-comment#always has git-conflict artefacts, something like this
```
<<<<<<< 63d55b12081116b89031a18743c01652a9e9244c
/* eslint spaced-comment: ["error", "always", { "block": "balanced": true }] */
=======
/* eslint spaced-comment: ["error", "always", { "block": { "balanced": true } }] */
>>>>>>> Autogenerated new docs and demo at Mon Jul 18 2016 10:56:32
/* This is a comment with whitespace at the beginning but not the end*/
```

**Comment by vitorbal** [comment]
Thanks, @wKich! probably it went unnoticed during a merge.

**Comment by vitorbal** [comment]
@nzakas might have something to do with the merge conflicts you mentioned during the patch release yesterday.

**Comment by nzakas** [comment]
Yeah. This has to be fixed on `eslint.github.io` directly as it has to do with what is published, not what is stored in this repo.

**Comment by nzakas** [comment]
I'll fix this.
