### ISSUE TITLE
What about checking commit message style with commitplease?

### ISSUE THREAD

**Issue by all3fox** [eslint/eslint#6706]
ESLint follows this [commit message style][1]. If I am not mistaken, it is checked by [the following code from Makefile.js][2] when the developer manually runs `npm run check-commit` [as instructed at step 5][3]. If the check fails, the developer has to go back and slightly rewrite some local git history, rinse and repeat.

Would you like this commit message style check to happen automatically when you type `git commit`? That is what the npm module [commitplease][4] does. If the commit message style check fails, the commit aborts and you do not have to rewrite any history. Just read the failure reason and try to `git commit` again with a new message. This is a shorter cycle!

Secondly, you have had problems (#3706 and #6109) with in-house scripts that check commit messages before. If you use commitplease, you outsource those problems to us. And we do not have many :)

Finally, if you would like to give commitplease a go, here is the real issue that needs discussing. [Your style guide][1] is very close to [jQuery commit message style](https://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines). The only big difference is that you require the first line of the commit message to end with a reference to the issue, while jQuery style does not.

Would you consider loosening that requirement and moving the issue reference to the bottom of the commit message? What problems do you think that will cause? I am happy to solve any of those if you are willing to give commitplease a go.

Commitplease is:
 1. used by jQuery Core, jQuery UI, jQuery Mobile, Globalize and QUnit
 1. considered by angular (angular/angular.js#14888 and angular/angular#9953)

[1]: http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changesa-namestep2a
[2]: https://github.com/eslint/eslint/blob/565e584c3ad879aa9aee34b888a973665a4b7ada/Makefile.js#L887-L948
[3]: http://eslint.org/docs/developer-guide/contributing/pull-requests#step-5-double-check-your-submissiona-namestep5a
[4]: https://github.com/jzaefferer/commitplease

**Comment by vitorbal** [comment]
Hi @all3fox, thanks for reaching out!

With regards to changing our commit message format to the one from jQuery, I believe there are a couple more open questions to talk about:

- In our commit message style, the "Tag" prefix is used to determine what kind of version bump will the next release be. For instance, if there is a commit with tag "Breaking" then the next release will be a major release. I couldn't find any reference to this in the jQuery commit style guide, but correct me if I'm wrong :)
- We automate the release process using our [eslint-release](https://github.com/eslint/eslint-release) tool. If we change the commit message format we would have to update the check there too.

What about the commit history up to this point? Is there any way to change it to the new format or would we have to live with the old format in past commits?

With all that said, I think if commitplease could support our commit format, it would be nice to validate the commit message in a shorter cycle like you mentioned.

Let's wait for more opinions from the rest of the team before anythying else!

**Comment by all3fox** [comment]
@vitorbal thank you for such a prompt and meaningful response!

> In our commit message style, the "Tag" prefix is used to determine what kind of version bump will the next release be.

In jQuery, this "Tag" is called a "Component" and is primarily used to determine the location of the change (like "Docs", "Tests" or "Core"). It looks to me like you use it for both things: "Build", "Chore" and "Docs" primarily for location and "Breaking", "New", etc for version bump.

However, from the commitplease viewpoint the meaning of this prefix is not important (and you can have any prefixes you like). What is important is that there is a set of allowed prefixes that must be in message.

> We automate the release process using our eslint-release tool.

Thank you, I will take a look at that too if you decide to try commitplease.

> What about the commit history up to this point?

It just remains as is, I am not sure it is a good idea to rewrite it.

> With all that said, I think if commitplease could support our commit format...

Currently, any valid ESLint commit message is a valid jQuery commit message. But ESLint has a single additional requirement (reference to the issue at the end of first line) that will not be checked, ie will not be enforced, if you use jQuery presets in commitplease.

It certainly can be implemented as a separate style. However, for the sake of avoiding yet another commit message style, I am encouraging a discussion.

**Comment by platinumazure** [comment]
@all3fox How many distinct commit message styles do you have to support right now?

I'm wondering if it would be possible to create a commit style format which might look something like this:

{tag}: {summary} (fixes {issue})

Which represents the ESLint summary style. Presumably jQuery style would just be {tag}: {summary}.

If you do something like that, you would only need to handle a few tokens ({tag}, {issue}, and generic handling for {summary}), but would be able to allow consumers to choose their style in configuration.

Is that something you guys would be willing to allow? (And does your answer change if you can get a volunteer to help implement?)

**Comment by all3fox** [comment]
> How many distinct commit message styles do you have to support right now?

[jQuery style][1] and [Angular style][2]

> you would only need to handle a few tokens ({tag}, {issue}, and generic handling for {summary})

Well, yes and no. I am not very advanced myself, but you are beginning to describe a "context free grammar" for a commit message. [We have thought][3] about it a bit already. The tricky part in your thinking is here: "but would be able to allow consumers to choose their style in configuration", i.e. how complicated a parser are you willing to write for that grammar?

For example, would you allow new tags (say, `{ticket references}` and `{long summary}`)? If yes, reporting custom error messages "Your commit message is bad because ..." becomes tricky/impossible. You could only say "the commit message did not match the following grammar" or make the user provide a custom error message for each new tag.

Secondly, suppose you decide to drop the requirement of having `{issue}` at the end of the first line. Instead, you impose another requirement that `{issue}` must simply be present somewhere in the commit message. In fact, it immediately turns the whole set of possible commit message into a not context free language, i.e. you can no longer describe it with simple tags and parse it with a context-free parser.

However, if you are not limiting yourself to these `{tag}, {summary}, etc` formal building blocks of a context-free grammar, enforcing the hypothetical requirement above can be hard-coded directly in commitplease.

To recap:
 1. There is no formal grammar for commit message styles
 1. If we adopt a context-free grammar (usually used to describe syntax of progamming languages), we will:
    1. Loose flexibility (two examples with error reporting and `{issue}` position above)
    1. Have a much more complicated parser that cannot be easily hacked/tweaked
 1. If we stay without a formal grammar:
    1. The end user has to limit themselves to the [available settings][4]. If they really want something special, they need to hack the parser itself.
    1. The parser is reasonably small, gives precise error messages and can accomodate any crazy rule a commit message style might have :)

Please tell me if you disagree or have questions.

[1]: http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit
[3]: https://github.com/jzaefferer/commitplease/issues/44#issuecomment-227616022
[4]: https://github.com/jzaefferer/commitplease#setup

**Comment by platinumazure** [comment]
Thanks for the thorough reply.

I don't believe I was advocating for a context-free grammar-- I was really advocating for a regular language parser, where tokens (e.g., `{tag}` in my examples) would essentially be parsed by a regex (tokenized I guess?), then the value is run through some simple predicates.

I did look at the Angular.js commit guidelines and I admit that perhaps, in order to describe their commit message grammar, a CFG would be easier. So I will need to rethink my suggested approach. In any case, you deserve a fully thought out proposal, so I will take the time to work on that and then perhaps create an issue in the commitplease repo. I agree that it would not be ideal to create another preset style, but at the same time I doubt we will be dropping our issue fix requirement either.

**Comment by nzakas** [comment]
We actually check the commit message format in only one place right now, which is by our bot on pull requests. The `check-commit` task is no longer run automatically because we can always fix the commit message in the PR directly. Plus, as we can now squash commits in PRs, we don't need to check every commit, just the first one.

So, I don't see a lot of value in switching to something else. I'm very much of the mind that we shouldn't be spending time fixing things that aren't broken, and this part of our process works just fine right now.

**Comment by jzaefferer** [comment]
> So, I don't see a lot of value in switching to something else.

I still see some value for you in improving onboarding new contributors. The earlier a tool yells at me when I made a mistake, the better. The bot can only act after submitting a PR. Commitplease gets involved right when committing.

If you agree with that, @all3fox could take care of adding whatever extra validation is needed to make this work. So there's little effort involved for the eslint team.

**Comment by nzakas** [comment]
@jzaefferer as I said, this really isn't a big concern for us and we don't have a lot of problems with people improperly formatting commit messages. Even so, we've found that having the bot catch it on the pull request tends to be very effective at helping people fix the commit message format. And last, we rarely ask people to update commit messages, we just fix them when we merge the PR. So, I'm pretty unconvinced that there's value here, but I'll leave this open to see if any other team members feel differently.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint @all3fox @jzaefferer 
Unfortunately, it looks like this issue didn't gain enough support from the team, so I'm closing it.
