### ISSUE TITLE
wrong error about react

### ISSUE THREAD

**Issue by laoqiren** [eslint/eslint#6708]
eslint version : v3.1.1
os： windows7
I import a react component ,just like this:
import` HeaderComponent from './header.js';

and then ,I render it like this:
ReactDOM.render(<FooterComponent introContent = {introContent}/>,$('#footer')[0]);

but the eslint makes the error: 'the HeaderComponent is defined but never been used, so I think this is a bug , wish that you can resolve this problem. Thanks.

**Comment by platinumazure** [comment]
Closing as a duplicate of #6707.
