### ISSUE TITLE
no-case-declarations examples are very similar and hard to distinguish

### ISSUE THREAD

**Issue by philiiiiiipp** [eslint/eslint#6716]
Hey, 

looking at http://eslint.org/docs/rules/no-case-declarations#rule-details I cannot really see the difference between correct and incorrect code. Either I am missing something or the declarations should be removed there.

**Comment by platinumazure** [comment]
@philiiiiiipp Thanks for reporting this-- at a quick glance I have to agree that there's a problem. Just wondering, why did you close this?

**Comment by platinumazure** [comment]
Never mind, I see it-- it's the braces. The point is that `case` declarations don't in themselves introduce a new block scope, so you need braces to create a new block scope.

That's extremely subtle and I think it could be improved. I'm going to reopen the issue, if that's okay.

**Comment by nzakas** [comment]
@platinumazure how would you improve the examples?

**Comment by platinumazure** [comment]
@nzakas A couple of things come to mind:

1. Have some declarations outside of the switch, to show those are okay
1. Add comments to point out the new block scope being introduced with braces
1. Use var in case statements and explain that that is valid due to function-scope hoisting

Okay if I try to show what I mean with a PR?

**Comment by philiiiiiipp** [comment]
1. The option of making the declarations outside seems obvious, but is probably nevertheless good to have in a complete example.
2. A comment about the braces would have solved some confusion for me in an instant.
3. You would then violate the [vars-on-top](http://eslint.org/docs/rules/vars-on-top) rule though.

I am not sure if I find it any better or worse to use only one case, since multiple cases are the more likely real world example.

**Comment by nzakas** [comment]
@platinumazure sounds good, feel free to open a PR (documentation improvements are always welcome).

I also think that the introduction could be expanded to include an example or two -- right now it's pretty bare.

@philiiiiiipp we don't have to worry about violating other rules because we don't know which ones a user will have enabled.

**Comment by rangelke** [comment]
I can try to pick this up, as I would like to start contributing to eslint, this sounds like a good introduction to the eslint-project. If no-one is busy with it of course.

As for the change in documentation. Would you prefer 1 single example and explaining with comments, which is good an bad?
Or would you prefer multiple example for (1) var in case being always valid, (2) declarations outside the switch being always valid and (3) and example as the current one, but with added comments when the braces are introduced?

**Comment by not-an-aardvark** [comment]
@rangelke Thanks for contributing!

There's no hard and fast rule for how to arrange the examples. Personally, I think the second option (a different example for each of the cases) sounds like it would be clearer, but anything that clearly indicates what the rule is doing would be fine.

**Comment by rangelke** [comment]
Alright. I'll take this on me then! I have to setup the project first though!

**Comment by vitorbal** [comment]
@rangelke Thanks! You can always drop by our [gitter chat](https://gitter.im/eslint/eslint) if you need help setting anything up.
