### ISSUE TITLE
ESLint long-term vision

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#6733]
After every major release we try to discuss features and enhancements that we want to focus on for the next major milestone. What I would like to know is what does the team thinks should be a long-term vision for ESLint? Any specific features you think are missing and should be considered? They don't have to be reachable in the near future, that's more of question about final state of ESLint as a project.
For example, I can think of three different things that I would want ESLint to eventually be able to do:
1. Support variable type/value tracking. - Currently Escope provides us with scope tracking, but I think type/value tracking can enable us to provide much more interesting rules.
2. Support cross-file linting. One of the most popular plugin currently is `eslint-plugin-import` that checks for correct import statements, and verifies that files exists and export proper object. Having ability to lint the whole project and find unused variables/function would provide a lot of value, I think.
3. I would like ESLint to eventually become not just a linter, but an engine that can provide editors with suggestions for improving the code as you type. In the same way Visual Studio and WebStorm show lighting bulb icon next to the code that can be improved, and provide different options to improve it (like, simplifying statements, extracting code into a function, refactoring, etc.).

---

**Note:** This issue is locked so the team can discuss amongst themselves what their ideas are. We are sharing here for transparency with the community.

**Comment by mysticatea** [comment]
> Support variable type/value tracking

The thing I was going to write has been already written. :laughing:
Variable type/value tracking is the feature I really want.
I will investigate it if I get enough time.

BTW, ["Control Flow Analysis for Types" of TypeScript 2.0 β](https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/#user-content-control-flow-analysis-for-types) is excellent.

**Comment by nzakas** [comment]
Agree with 1 & 2 completely. 

For 1, my feeling is that we will likely have to fork escope in order to accomplish this unless it can be made a lot more pluggable than it is today. I also need something that can adjust to Flow/TypeScript syntax so that references are correctly understood by ESLint.

For 2, this has been on my mind a lot. Figuring out an efficient way to do multi-file linting is an interesting challenge and definitely one we need to tackle. 

Can you describe what you mean by 3? This seems a bit out of scope, but I'm not 100% clear about what you have in mind. 

---
Some additional ideas I have:

1. I'd like ESLint to become AST-format agnostic. At some point, we will reach the end of for ESTree and will have to switch to something else. I'd like ESLint to be able to easily switch AST formats without a complete rewrite. 
2. I'd also like to see if we can extract the non-JS-specific parts of ESLint into a toolkit for writing ESLint-like tools for other languages.

**Comment by ilyavolodin** [comment]
For number 3, what I mean is a much more robust autofixing, basically. Right now, autofixing basically changes your code to match selected style. However, once we add autofixing to simple rules, we will end up with complex cases that we can't fix automatically, because there's more then one possible way to fix a rule. For example, `init-declarations` rule will not be a candidate for autofixing, because we might change the meaning of the code, by fixing it. However, we could provide suggestions on how to fix it (in a lot of cases, we might provide more then one suggestion for the same code). In that case, editors can provide interface similar to Visual Studio and WebStorm to let user know that there code can be improved and list our suggestions to them.

![image](https://cloud.githubusercontent.com/assets/1380062/17071158/d37c8970-502d-11e6-9d89-91b1572db85a.png)

![image](https://cloud.githubusercontent.com/assets/1380062/17071273/60f87b74-502e-11e6-85ef-fcbe10bfab01.png)

All of the new editors that are showing up currently (Atom, VSC, Brackets, etc.) are nice, but they are lacking support for automatic refactoring and cleanup like that, we could provide it if we extend the scope of autofixing.

**Comment by platinumazure** [comment]
@ilyavolodin So maybe you're saying, what if we had definite/canonical fixes (which all rule fixes are currently assumed to be) and suggestions/possible fixes (which are not automatically applied by `--fix` but could be handled by editors via context menus)? If I'm understanding correctly, I'm intrigued by the concept.

**Comment by ilyavolodin** [comment]
@platinumazure Correct. Autofixing will stay as is for rules that can be autofixed. For rules that are too complicated to be automatically fixed we provide a set of suggestions that require user input. This would be API-only feature, and not part of the CLI, since asking user on the command prompt about suggestion would probably not be a great UX. This can be extended later to provide ability to create rules that would not report errors, but only provide suggestions. So, for example, extracting repeated code into a separate function, or refactoring ternary statements into `if...else`, and back.

**Comment by gyandeeps** [comment]
very interesting ideas @ilyavolodin :+1:

**Comment by platinumazure** [comment]
I would like to throw analytics in the ring. No idea how it would be done, but here are some statistics I would be interested in collecting:

* Usage frequency of shareable configurations
* Usage frequency of particular configurations of rules (e.g., how often is indent used with tabs, etc.)

And I'm sure there are plenty more possibilities. Of course, I would want that to be strictly opt-in and transparent for users.

**Comment by ilyavolodin** [comment]
@platinumazure I suggested it at some point, but @nzakas feels pretty strongly against "phoning home".

**Comment by platinumazure** [comment]
@ilyavolodin For very good reasons, I'm sure! What about if statistics were collected locally, maybe stored in the lint cache directory or something, and then a `eslint --send-usage-report` could send statistics "home", completely out-of-band from linting? (And of course, collection of statistics locally would only be done if a user opts in.)

An approach similar to how coveralls operates might work here, as well.

**Comment by ilyavolodin** [comment]
@platinumazure I'm not sure how many users will do that manually. I see no incentive for them to do it. More than that, I don't think it's all that necessary, since we can do those analysis off-band on github projects: https://github.com/blog/2201-making-open-source-data-more-available (I was planning to look into this at some point).

**Comment by platinumazure** [comment]
Good points, hadn't thought of Github analytics. I would have just thumbs-up'd your comment but it seems that feature is disabled when an issue is locked to contributors, so apologies for the extra notification.

**Comment by alberto** [comment]
Closing as this is a meta issue
