### ISSUE TITLE
Proposal: 'eslint:all' preset should not include deprecated rules

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6734]
**The version of ESLint you are using:**

- 3.1.1

**The problem you want to solve:**

We have several accepted issues we will deprecate rules. (#6080, #6586)
We generate `eslint:all` preset from rule files automatically, and this would include deprecated rules.

I think `eslint:all` preset should not include deprecated rules.

**Your take on the correct solution to problem:**

1. It adds `deprecated` information into the `meta` property of rules.
2. `eslint:all` checks the `meta.deprecated` property.

```js
var enabledRules = ruleFiles.reduce(function(result, filename) {
    const ruleId = path.basename(filename, ".js");
    if (path.extname(filename) === ".js" && !rules.get(ruleId).meta.deprecated) {
        result[ruleId] = "error";
    }
    return result;
}, {});
```

**Comment by ilyavolodin** [comment]
Agree!

**Comment by platinumazure** [comment]
Agreed: If we have deprecated a rule, the vast majority of the time we already have a preferred replacement available, so rule coverage is not lost. Regarding burden of user having to potentially configure for new rule, that burden is already accepted by the user for completely new rules by using `eslint:all`. So I definitely think we should make this change.

**Comment by nzakas** [comment]
Agree. We should document this.

**Comment by alberto** [comment]
Is it ok to exclude it from `eslint:all` even if it is enabled in `eslint:recommended`? I guess yes...

**Comment by ilyavolodin** [comment]
Yes, because we said right from the start that `eslint:all` will not be subject to semantic versioning, while `eslint:recommended` is. So we will remove deprecated rules from `eslint:recommended` with a next major release, but we can remove them from `eslint:all` at any time.
