### ISSUE TITLE
`no-unused-vars` message does not end with a period

### ISSUE THREAD

**Issue by wavebeem** [eslint/eslint#6738]
**What version of ESLint are you using?**

2.10.2

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

```javascript
const options = {
  // TODO: Actually set the envs correctly
  envs: ['browser', 'mocha', 'node', 'es6'],
  useEslintrc: false,
  extends: 'eslint:recommended',
  ignorePattern: [
    'node_modules',
    'bower_components',
    'build',
    'tmp',
    'dist'
  ],
  // Eventually let's enable it to fix problems automatically! :D
  // fix: true,
  rules: {
    semi: WARN,
    strict: [WARN, 'safe'],
    'no-undef': ERROR,
    'wrap-iife': WARN,
    'no-trailing-spaces': WARN,
    'comma-style': [WARN, 'last'],
    'new-parens': WARN,
    'no-inline-comments': WARN,
    'no-sequences': ERROR,
    'no-alert': WARN,
    'no-caller': WARN,
    'no-lone-blocks': WARN,
    'object-curly-spacing': [WARN, 'never'],
    'space-infix-ops': WARN,
    'space-unary-ops': [WARN, {words: true, nonwords: false}],
    'spaced-comment': [WARN, 'always'],
    'no-unused-vars': [WARN, {argsIgnorePattern: '^_'}]
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

I linted code and got back a message without a period.

```javascript
const cli = new eslint.CLIEngine(eslintOptions);

function lint(req, res) {
  if ('paths' in req.body) {
    const report = cli.executeOnFiles(req.body.paths);
    if (eslintOptions.fix) {
      eslint.CLIEngine.outputFixes(report);
    }
    res.json(report);
  } else {
    res.status(S.BAD_REQUEST).json({
      error: 'Missing parameter "path"'
    });
  }
}
```

**What did you expect to happen?**

I expected the message from the `no-unused-vars` rule to include a period at the end, like the other messages from ESLint.

**What actually happened? Please include the actual, raw output from ESLint.**

https://gist.github.com/wavebeem/98136a4d2823a43716e76651571473a6

**Comment by platinumazure** [comment]
Just to avoid potential confusion for people who use the most common formatter, "stylish", it's worth noting that that formatter explicitly strips periods off the end of messages. My opinion is that we should still end lint messages with periods in general, because most or all other formatters carry those through.

@wavebeem Thanks very much for the issue and for submitting a pull request to address!

**Comment by wavebeem** [comment]
@platinumazure Oh, that's a good thing to call out! I was wondering why this wasn't noticed sooner, and that makes sense. I found this while making a tool that wraps ESLint, so I might have to copy that approach of trimming final periods!

**Comment by nzakas** [comment]
@wavebeem do you want to submit a PR for this?

**Comment by ilyavolodin** [comment]
@nzakas #6739

**Comment by wavebeem** [comment]
@nzakas I already have, but it needs some work still (https://github.com/eslint/eslint/pull/6739)
