### ISSUE TITLE
Make `max-lines` report the actual number of lines

### ISSUE THREAD

**Issue by jrencz** [eslint/eslint#6766]
**What version of ESLint are you using?**
3.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
n/a

**What did you do? Please include the actual source code causing the issue.**
I enabled the max-lines rule

**What did you expect to happen?**
Rule should tell me how many lines each too long file has

**What actually happened? Please include the actual, raw output from ESLint.**
Rule only told me that the file is too long and what was the max allowed number of lines

**Comment by platinumazure** [comment]
Seems reasonable to me. :+1:

**Comment by mysticatea** [comment]
I think helpful that the rule warns those violated lines rather than the top of files?

**Comment by vitorbal** [comment]
I believe this increases developer experience, and it's a pretty simple change, so I'm willing to champion this rule. We need 2 more 👍's and we can mark this as accepted.

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
:+1:
