### ISSUE TITLE
`object-curly-newline` non-gramatical error when line break is not expected

### ISSUE THREAD

**Issue by jrencz** [eslint/eslint#6769]
**What version of ESLint are you using?**
3.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
n/a

**What did you do? Please include the actual source code causing the issue.**
I enabled the `object-curly-newline` rule

**What did you expect to happen?**
I got `47:15  error  Unexpected a line break after this open brace    object-curly-newline`

**What actually happened? Please include the actual, raw output from ESLint.**
`47:15  error  Unexpected line break after this open brace    object-curly-newline` (without `'a'`)

**Comment by alberto** [comment]
Thanks for reporting, but this is fixed in master
