### ISSUE TITLE
ES7 Decorator errors with no-undef

### ISSUE THREAD

**Issue by rwwagner90** [eslint/eslint#6775]
**What version of ESLint are you using?**
2.13.1
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**
This just pertains to the no-undef rule
**What did you do? Please include the actual source code causing the issue.**
`@alias('fieldName') foo` is the part causing the issue, and the whole file is:

```js
import Ember from 'ember';
import layout from './template';
import computed, {alias} from 'ember-computed-decorators';
const {Component} = Ember;

export default Component.extend({
  layout,
  tagName: 'div',
  classNameBindings: [ ':contact-item', ':icon', 'textarea:message' ],
  @computed('fieldName')
  idAndName(fieldName) {
    return `cd-${fieldName}`;
  },
  @alias('fieldName') foo,
  textarea: false
});
```
**What did you expect to happen?**
No errors
**What actually happened? Please include the actual, raw output from ESLint.**
`error  'foo' is not defined  no-undef`

Decorators do work for functions though, as `@computed` throws no errors.

**Comment by dbashford** [comment]
[Related error in eslint-babel](https://github.com/babel/babel-eslint/issues/204) which was closed without fix indicating that there may be no fix.

**Comment by ilyavolodin** [comment]
ESLint doesn't support decorators, so this is purely the domain of `babel-eslint`. @dbashford posted a link to the issue in `babel-eslint` that seems to suggest this is correct behavior.

Closing, as decorators are still stage 1 proposal, and it's going to be a very long while before ESLint will support them.

**Comment by mattmarcum** [comment]
@ilyavolodin decorators are finally stage 2 now!  What stage do they have to be to get official eslint support?

**Comment by hzoo** [comment]
ESLint doesn't support async/await yet by default either - I would follow https://github.com/eslint/eslint/issues/6693

**Comment by platinumazure** [comment]
@mattmarcum Stage 4, plus however long it takes Acorn and espree to support it. Sorry, but you'll still need babel-eslint a little while longer.
