### ISSUE TITLE
Build: Update markdownlint dependency to 0.2.0

### ISSUE THREAD

**Issue by DavidAnson** [eslint/eslint#6781]
Changes:

* 0.2.0 - Add MD042/MD043, enhance MD002/MD003/MD004/MD007/MD011/MD025/MD041, dependencies.

PR to follow

**Comment by nzakas** [comment]
@DavidAnson can you explain why this upgrade is useful for us?

**Comment by DavidAnson** [comment]
@nzakas Sure!

There are two new rules:
* MD042 no-empty-links - No empty links
* MD043 required-headers - Required header structure

The first is automatically applied and makes sure no links are empty or just "#", both of which are common placeholder/editing mistakes. The second is not in effect, but could be used to ensure that all rule documentation had a common header structure like "Introduction, Details, Examples". It supports optional headers as well, so an "Exceptions" header might only appear on some pages (but always in the same place).

There are also a couple of bug fixes and improvements to other rules to make them more flexible. None of this breaks on current ESLint files, but the changes may help improve the life of a future developer one day.

Finally, the updated dependency (the package has only one) is for `markdown-it`, the underlying Markdown parser, and includes better support for the CommonMark specification. Again, nothing breaks today, but future issues should be less likely.

Hope this helps!

**Comment by nzakas** [comment]
That helps, thanks! We just like to have rationale for upgrading other than "it's nice to upgrade." :)
