### ISSUE TITLE
Posible error when setting a variable in an arrow function.

### ISSUE THREAD

**Issue by iDuran90** [eslint/eslint#6787]
**What version of ESLint are you using?**
2.5.3

**What parser (default, Babel-ESLint, etc.) are you using?**
gulp-babel

**Please show your full configuration:**
`'no-unused-vars': [2, { 'vars': 'local', 'args': 'after-used' }]`

**What did you do? Please include the actual source code causing the issue.**
`let myVar;`
`const myObject = {};`
`myObject.myFunction = () => {
  myVar = true;
};`

**What did you expect to happen?**
No errors.

**What actually happened? Please include the actual, raw output from ESLint.**
1:5  error 'myVar' is defined but never used  no-unused-vars

**Comment by alberto** [comment]
It's considered unused if you never read its value

**Comment by iDuran90** [comment]
Oh, ok, Thanks.
