### ISSUE TITLE
Remove output in browser console 

### ISSUE THREAD

**Issue by tokenvolt** [eslint/eslint#6790]
Is there a way to remove output of eslint from browser console?

**Comment by platinumazure** [comment]
Are you using the online demo, or a webpack'd or browserify'd version of the Node package?

**Comment by tokenvolt** [comment]
I'm using eslint with webpack through eslint-loader. It outputs the errors and warnings to the terminal and also to the browser.

**Comment by mysticatea** [comment]
@tokenvolt So, is this `eslint-loader`'s issue?

**Comment by tokenvolt** [comment]
I'm not sure what is exactly responsible for this, so I created an issue. Should I look into eslint-loader then?

**Comment by mysticatea** [comment]
I'm not familiar with webpack and eslint-loader, but I guess eslint-loader runs eslint in browsers and outputs the result to browser's console.

FWIW, [Our online demo](http://eslint.org/demo/) does not output the result to browser's console.

**Comment by alberto** [comment]
@tokenvolt yes, they can probably help you better there, thanks

**Comment by JikkuJose** [comment]
@tokenvolt did you find a solution for this?

**Comment by tokenvolt** [comment]
@JikkuJose nope, but I think it's not a eslint issue as @mysticatea stated above.
