### ISSUE TITLE
Entire site is giving 404s

### ISSUE THREAD

**Issue by cristian-sima** [eslint/eslint#6791]
So:
 
1. Go to [this link](http://eslint.org/docs/rules/)
2. Choose any of the rules
3. Click

It does not work :-1:

**Comment by marvinhagemeister** [comment]
Seems like the whole documentation under `eslint.org/docs/` returns a 404.

**Comment by nzakas** [comment]
Confirmed. Something happened in the course of the release that broke our documentation. Looking into it now.

**Comment by nzakas** [comment]
The site is fully functional as of 6 hours ago.
