### ISSUE TITLE
Errors on 'no-empty-label' when there is no rule with that name.

### ISSUE THREAD

**Issue by ripter** [eslint/eslint#6811]
**What version of ESLint are you using?**
eslint v3.2.0
node v6.3.0
npm 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
No config needed to show issue. 

**What did you do? Please include the actual source code causing the issue.**
```
$ ./node_modules/.bin/eslint src/
```

**What did you expect to happen?**
```
 2:10  error  'hello' is defined but never used                                            no-unused-vars
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
/dev/src/index.js
  2:1   error  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  2:1   error  Rule 'space-before-keywords' was removed and replaced by: keyword-spacing    space-before-keywords
  2:1   error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  2:1   error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  2:10  error  'hello' is defined but never used                                            no-unused-vars
```

**Comment by platinumazure** [comment]
We do need your configuration: Somehow the `no-empty-label` rule is being enabled in your configuration. We do not enable any rules by default in ESLint (since 1.0.0). Please show your configuration.

**Comment by ripter** [comment]
I have no .eslint file. I removed it trying to debug the issue. Here is the output of ll
```
$ ll
total 32
-rw-r--r--    1 chrisrichards  staff   544B Jul 31 12:58 Makefile
-rw-r--r--    1 chrisrichards  staff    21B Jul  8 23:37 README.md
drwxr-xr-x  128 chrisrichards  staff   4.3K Jul 31 13:15 node_modules
-rw-r--r--    1 chrisrichards  staff   465B Jul 31 13:08 package.json
drwxr-xr-x    4 chrisrichards  staff   136B Jul  8 23:53 public
drwxr-xr-x    3 chrisrichards  staff   102B Jul  8 23:49 src
-rw-r--r--    1 chrisrichards  staff   337B Jul 31 12:59 webpack.config.js
```

**Comment by platinumazure** [comment]
You might be using an .eslintrc file from a parent directory or your user
home directory. Please run ESLint with the `--debug` flag and include the
output here (and you can read that output to determine what configuration
file(s) is/are being used).

**Comment by ripter** [comment]
Ah, that was it. I didn't know eslint would go out of my root directory searching for a config. There was a bad .eslintrc file in my root dev folder. I removed it and everything is working as expected. Thank you!

**Comment by gyandeeps** [comment]
you can use `root: true` inside a config file that way eslint will stop looking upwards from that config.
