### ISSUE TITLE
Nested dependency circular-json is failing our license check

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6816]
For the master branch, Travis checks are now failing because the license checker is saying that `circular-json` doesn't have a correct license. It's likely that one of our dependencies just started including it. We need to figure out which one and probably just set a stricter version to work around this. 

Longer-term, we can probably send a pull request to `circular-json` to get the license information put into `package.json`.

**Comment by nzakas** [comment]
Looks like it's a transitive dependency:

`file-entry-catch` -> `flat-cache` -> `circular-json`

CC: @royriojas

**Comment by platinumazure** [comment]
Just for record on this issue: circular-json has accepted my PR to add a license to their package.json, so hopefully we can proceed without having pinned dependencies in the future.

**Comment by royriojas** [comment]
hi @nzakas, 

Sorry for that, I was working on another PR #6780 and just published the new version that includes `circular-json` as a way to handle cycles. I fail to notice the license though, sorry I should have checked that before.

Hopefully it seems it is now fixed.
