### ISSUE TITLE
Arrow function returning an object incorrectly marked

### ISSUE THREAD

**Issue by udnaan** [eslint/eslint#6833]
eslint: 3.2.2

consider this code for example:

    let comp;
    this.setState(state => {comps: state.comps.push(comp)});

it's a one liner arrow function, returning an object. 

Eslint returns the following issues:
  2:25  error  'comps:' is defined but never used  no-unused-labels
  2:54  error  Missing semicolon                   semi

I expect it to take it for what it is, an arrow function without curly braces returning an object. 
Eslint parses it as an arrow function with curly braces and function body. 

my eslint config: https://gist.github.com/udnaan/4968046ad01a7fd2c5b0df95e3dd8559

**Comment by gyandeeps** [comment]
Eslint is correctly parsing it according to the specs.

If you want to return an object, you have 2 options:

1. `this.setState(state => ({comps: state.comps.push(comp)}));`
1. `this.setState(state => { return {comps: state.comps.push(comp)}});`

**Comment by udnaan** [comment]
Can you point to the specs which are in question?

**Comment by platinumazure** [comment]
http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions

<pre>
ConciseBody: [lookahead is not `{`] AssignmentExpression |
    { FunctionBody }
</pre>

**Comment by udnaan** [comment]
Closing the issue. Thanks!
