### ISSUE TITLE
no-useless-escape strange behaviour

### ISSUE THREAD

**Issue by cristian-sima** [eslint/eslint#6842]
I have 3 functions:

```js
const replaceCharInString = ({word, oldChar, newChar} : {
  word: string,
  oldChar: string,
  newChar: string
}) : string =>
  word.replace(`/${oldChar}/g`, newChar);

export const formatNumber = (word : string) : string =>
  replaceCharInString({
    word,
    oldChar: "\.",
    newChar: ",",
  });

export const normalizeNumber = (word : string) : string =>
  replaceCharInString({
    word,
    oldChar: ",",
    newChar: ".",
  });
```

In this case I really need `\.` otherwise the `replaceCharInSting` will replace **all the characters**, but I want just the dots.

**Comment by michaelficarra** [comment]
That's not how string escapes work. `"\." === "."`. This rule is working as intended.

**Comment by cristian-sima** [comment]
Yes it it, but in this case I really need `\`

**Comment by platinumazure** [comment]
@cristian-sima You want to use "\\." here. As a string literal, that gives you a 2-character string with backslash and then period. As @michaelficarra noted, "\." is a one-character string with period.

**Comment by cristian-sima** [comment]
Thank you
