### ISSUE TITLE
Type error in an internal-rule

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6848]
I just found that our a CI build was failed by TypeError of `internal-no-invalid-meta` rule.
I have not investigated it yet.

https://travis-ci.org/eslint/eslint/jobs/149564000#L559

**Comment by vitorbal** [comment]
@mysticatea i'll investigate. Looks like the rule does not follow the new rule format and does not provide a meta property.

**Comment by vitorbal** [comment]
Thanks for opening the issue, @mysticatea! I notified the author of the PR that he needs to update his rule to the new format.

But I'm also going to work on a better handling of the case where a rule is on old format, so it shows a lint message instead of throwing!
