### ISSUE TITLE
Provide a way to check for conditionals on process.env.NODE_ENV

### ISSUE THREAD

**Issue by mcasimir** [eslint/eslint#6855]
### Request:

I'd like to have a way to prevent `if (process.env.NODE_ENV === 'production')` while allowing other environment variables to be used freely.

The closest rule i've found is `http://eslint.org/docs/rules/no-process-env` but it serves for another purpose.

### Motivation:

Many cloud providers as well as mainstream technologies like docker and kubernetes allows to use environment variables to inject dependencies (ie: MONGODB_URL).

Differently from what is stated in http://eslint.org/docs/rules/no-process-env that's perfectly ligit and correct since only the environment is knowing the right values.

What is dangerous, no matter if done using `process.env` or `config.json`, is environment aware code (eg. `if env === dev`) since it breaks dev/prod parity and makes deployments unsafe.

Thus it would be nice to have at least a way to check and prevent the use of `NODE_ENV`.

#### About http://eslint.org/docs/rules/no-process-env

Please consider to mitigate this sentence in the doc:

> Instead, one of the best practices is to define all those parameters in a single configuration/settings file which could be accessed throughout the project.

Since that's not a best practice but a common practice, perhaps born long ago when it was unpractical to replicate a production environment on developers machines and misunderstood long enough to end up in the docs of a code quality tool.

It is ok to host global config in files and not in environment variables (that can be a best practice) but it should not hold environment configuration.

Nowadays using containerization and virtualization technologies doing so is almost just a source of issues (a dominant part of the code that won't be covered by tests and potentially breaks in production).

ESLint version: v3.2.0

**Comment by platinumazure** [comment]
This sounds like a good candidate for a custom rule. Or you could visit the [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) repository and see if this might be a suitable rule for that plugin. But I don't think this is a good candidate for core.

Labeling as a new rule request for now.

**Comment by mcasimir** [comment]
@platinumazure thanks for considering it. I was actually thinking more about an extension of `no-process-env` that allows to restrict the warning/error to some specific variables.

**Comment by platinumazure** [comment]
Sure! And I was just trying to say I consider such an enhancement unlikely
to be accepted, since one of our requirements for new features and
enhancements is whether the missing functionality is critical to users of
core ESLint in aggregate, which I'm personally not persuaded is the case.
But maybe the rest of the team will feel differently.

I'll try to get a few more folks to look at this today.

**Comment by mcasimir** [comment]
Cool. I'll follow here and figure out a way around in case it would be rejected. Thanks!

**Comment by mysticatea** [comment]
If we move `no-process-env` rule to [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node), I can accept it :stuck_out_tongue_winking_eye: .

I know containers prefer environment variables.
But I'm hard to think I use the environment variables from a whole program.
A config file would refer the environment variables and others would refer the config file.

```js
/*eslint-disable no-process-env*/
exports.foo = process.env.FOO
exports.bar = Number(process.env.BAR) || 100
```

In this case, `no-process-env` rule works fine to prevent a use of environment variables outside of the config file.

**Comment by mcasimir** [comment]
@mysticatea I use env vars it in a way that is very similar to what you wrote, except i like to split in by modules and not to create a whole config so each modules holds their own configuration and are easier to drop or replace. 

Speaking about containers kubernetes config maps or gitRepo volumes makes also reasonably handy to inject a whole config file and avoid env vars at whole. 

Still the problem remains: it has to be independent from `NODE_ENV`. So welcome `config.js/json` but no `dev.json`, `staging.json`, `miantenance.json` and so on and so forth.

Those files are loaded based on `NODE_ENV` value and sadly some libraries simplifies the process and would hide the `require` part. As a result of recommending that as a best practice I've seen project with 20 environment files, most of them was legacy config used by old teams that no one can understand anymore and clean. 

Even worse those files contains a mix of application settings (that would need a full rebuild anyway) and environment specific setup (`MONGO_DB_URL`). 

It makes any release thrilling. Thus my will to discourage that practice, at least where i work :).

I'm fully aware that an eslint rule wont solve the problem, but at least will be a starting point.

I understand the way i stated it is a very specific node js rule so i'm fine to start bugging in `eslint-plugin-node` issue list or just to create one on my own.

I'd just like to continue here if you instead consider an improvement to have more flexibility in `no-process-env`.

Thanks

**Comment by nzakas** [comment]
I agree with @platinumazure, I think this is best as a custom rule and not part of core.

**Comment by alberto** [comment]
Agree, closing
