### ISSUE TITLE
Eslint cannot be run in Visual Studio 2015

### ISSUE THREAD

**Issue by tsnig** [eslint/eslint#6858]
I need to integrate eslint running into Visual Studio 2015 (version 14.0.25425.01 Update 3). I want to have errors listed in an "Error List" window with files names and lines where it happened.

I am using the following package.json configuration:
```
    "babel-eslint": "^6.1.2",
    "eslint": "^3.2.2",
    "eslint-config-airbnb-base": "^5.0.1",
    "eslint-config-angular": "^0.5.0",
    "eslint-config-default": "^0.2.1",
    "eslint-config-defaults": "^9.0.0",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-angular": "^1.3.1",
    "eslint-plugin-import": "^1.12.0
```
Eslint configuration is the next one:
 ```
 "extends": ["airbnb-base", "angular"],
  "parser": "babel-eslint",
  "env": {
    "amd": true,
    "jasmine": true,
    "browser": true,
    "jquery": true,
    "node": true,
    "es6": true,
    "commonjs": true,
    "worker": true
  },
  "globals": {
    "inject": false
  },
  "rules": {
    "eol-last": "off",
    "linebreak-style": [ 2, "windows" ],
    "comma-dangle": [ "error", "never" ],
    "spaced-comment": "off",
    "max-len": [2, 140, 2, {
        "ignoreUrls": true,
        "ignoreComments": false
      }
    ],
    "no-underscore-dangle": [2, { "allowAfterThis": true }
    ],
    "no-use-before-define": "off",
    "no-param-reassign": ["error", { "props": false }],

    "angular/no-service-method": "off"
  }

```
This configuration successfully works in Visual Code and through command line utility. But in VS no errors are displayed at all. The only configuration that worked was "extends": [ "defaults/configurations/airbnb/es6"]. When I tried to add angular config to "extends" field, it stopped to display any error. 
The another option that I tried was to copy all rules in one configuration file, however, the rules still did not work (ex. "strict": 2, "no-alert": 1).

I would appreciate if someone explains how integrate eslint into VS or how to run it except like through command line.

**Comment by ilyavolodin** [comment]
I know this is probably not the answer you are looking for, but there are better ways to integrate ESLint with Visual Studio. You can install [.NET Core Tooling Preview 2](https://www.microsoft.com/net/core#windows) which comes with built-in integration with ESLint. If that's not an option, you can also install [Web Analyzer](https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d) extension, which brings integration with ESLint, TSLint, CSSLint and so on.
If none of those are possible, I would suggest getting ESLint to run on the command line first, with the configuration you want, and only after that trying to integrate it with Visual Studio.

**Comment by tsnig** [comment]
@ilyavolodin , I have .Net Core Tooling and Web Analyzer installed, but it does not help. When I click on Run Web Code Analysis, nothing happens.
My configuration is run in the command line successfully, but I would like to have integration with VS for easier development.

**Comment by ilyavolodin** [comment]
@tsnig Sorry, I haven't worked with Visual Studio in a while, but my guess would be global vs. local installation of ESLint. As far as I remember, Web Analyzer runs global installation of ESLint, it's possible that .Net Core Tooling does as well. In that case, you need all of your plugins/configs installed globally too.

**Comment by tsnig** [comment]
Installing eslint, eslint plugins and configuration globally helped. In addition, it is required to add eslint as external tool (Tools -> External Tools) to have Visual Studio take you to the line where the error occurred
