### ISSUE TITLE
Allow disabling environments with inline comments

### ISSUE THREAD

**Issue by facboy** [eslint/eslint#6861]
**What version of ESLint are you using?**

3.2.2

It would be nice if we could disable environments using inline comments and/or the command-line, eg

```
/* eslint-env node, !mocha */
```

could be used to enable node and disable mocha.

**Comment by platinumazure** [comment]
I'm not sure there's much we can do here. To help explain why, let me give some background on the order we do things in ESLint.

For each file:

1. Read configuration files to determine configuration for that file (we may cache these results to avoid repeating this step for files in the same directory but we do have to determine the configuration for each file)
1. Read the file contents and parse
1. Iterate through online configuration comments

So it's pretty clear we have to parse the file before we can process comments.

Now, considering all that, what if the environment changes the ecmaVersion, like the `es6` environment does? We run into a circular dependency: We have to parse first before reading configuration comments, but then the configuration comments tell us we need to parse again using non-ES6.

You can remove environments in configuration files. Unfortunately, we don't support removing them via inline comments.

**Comment by facboy** [comment]
I guess this means it is virtually impossible to disable an environment on a per-file basis, without resorting to a completely separate eslint run with a different config file?

For completeness sake, what about on the command-line?  Not that this would help with the above.

**Comment by vitorbal** [comment]
@facboy it's also not possible to disable an environment via the CLI, but if you want to guarantee that the set of enabled environments matches exactly what is specified via the CLI `--env` flag, you could combine it with the `--reset` and `--no-eslintrc` flags.

**Comment by vitorbal** [comment]
Closing, as the questions seem to be resolved. Please reopen if there is more to discuss!
