### ISSUE TITLE
`npm test` does infinite looping

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#6870]
Currently, the test of ESLint seems to be broken on Windows.

https://ci.appveyor.com/project/nzakas/eslint/build/3834

It seems to start infinite looping (it's consuming CPU 1 Core 100%) after it printed "Validating JavaScript files".
This has reproduced on my local machine.

I'm not sure what is happening...

**Comment by mysticatea** [comment]
- Windows 7
- both PowerShell (GitHub Shell) and cmd.exe
- both Node 4.4.7 and Node 6.3.1
- npm 3.9.0

**Comment by ilyavolodin** [comment]
I can confirm. It's also goes into infinite loop on my machine. Could this be related somehow to #6850 that's the only thing that changed recently. But then I'm not really sure why it's failing on Windows only.

**Comment by gyandeeps** [comment]
Confirmed: If I remove this commit https://github.com/eslint/eslint/commit/f8ab8f1283966ac03312ab1c7d215c210e93f3b1 then the lint works fine. This is currently the top most commit.

**Comment by gyandeeps** [comment]
Found the issue. Will send a PR with the fix.
Reason is that we hitting the limit on how many files can be passed though cli into eslint. Will explain more once i have the PR out.

**Comment by gyandeeps** [comment]
Fun facts:

- I did this `console.log(process.argv.join("").length)`
- I could make the console work for 7860
- as soon as i add one more character, it would hangup

**Comment by mysticatea** [comment]
@gyandeeps Cool. Thank you so much!
