### ISSUE TITLE
Add --fix option for no-mixed-spaces-and-tabs

### ISSUE THREAD

**Issue by Wilfred** [eslint/eslint#6873]
It would be really useful to add a `--fix` option for the no-mixed-spaces-and-tabs rule.

**Comment by platinumazure** [comment]
How would you propose fixing in this case?

* Under what conditions should tabs be favored, rather than spaces?
* How would you know the number of characters that should be inserted or removed?

**Comment by Wilfred** [comment]
Perhaps an option `prefer: "spaces"` or `prefer: "tabs"` to decide which character to replace with?

Likewise, `"tab-width"` in spaces could be an option. Assuming the user wants to replace tabs with spaces, the value of `"tab-width"` is less important because the indent rule can fix the code once it's all spaces.

**Comment by Wilfred** [comment]
Alternatively, if the indent rule could replace tabs (see #6875), this would be redundant.

**Comment by nzakas** [comment]
Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by IBwWG** [comment]
For those who find this issue who were hoping eslint would just enforce the `indent` rule rather strictly, a workaround (caution, back up first!) would be to strip all leading tabs and spaces first:

```sh
find . -name '*.js' -print0 | xargs -0 sed -i 's/^[ \t]*//g'
```

...and then run eslint with `--fix` to get all of your leading whitespace the way your `indent` rule defines it.

However, you'd better be sure you don't have anything fancy like mixed tabs and spaces to align properties, etc.  This is really best used on simple/small codebases.

**Comment by ratbeard** [comment]
This one worked for me on osx

`find src -name '*.js' ! -type d -exec bash -c 'expand -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;`
