### ISSUE TITLE
ESLint CLI gives no information about exceptions thrown on plugin load

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6874]
**What version of ESLint are you using?**
2.13.1 (with eslint-plugin-react 6.0.0)

**What parser (default, Babel-ESLint, etc.) are you using?**
Default (this shouldn't matter)

**Please show your full configuration:**

``` json
{
    "plugins": ["react"]
}
```

**What did you do? Please include the actual source code causing the issue.**

``` shell
$ eslint --debug someFile.js
```

**What did you expect to happen?**
Plugin loads successfully, or if it fails to load, the exception thrown should show up in `eslint --debug`.

**What actually happened? Please include the actual, raw output from ESLint.**

``` text
eslint:cli Running on files +0ms
eslint:ignored-paths Looking for ignore file in /path/to/root +88ms
eslint:ignored-paths Could not find ignore file in cwd +3ms
eslint:glob-util Creating list of files to process. +0ms
eslint:cli-engine Processing /path/to/js/file +23ms
eslint:cli-engine Linting /path/to/js/file +2ms
eslint:config Constructing config for /path/to/js/file +1ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Loading /.eslintrc +3ms
eslint:config-file Loading config file: /.eslintrc +1ms
eslint:plugins Failed to load plugin eslint-plugin-react. Proceeding without it. +212ms
```

With no indication of why the plugin failed to load. In this case, it wasn't due to the plugin not being available, but rather the `require()` failed due to something wrong with the plugin's main file.

**Comment by platinumazure** [comment]
In addition, I'm wondering if we want to try to detect if the plugin existed (but threw) vs the plugin didn't exist, and modify the pretty message template accordingly.

**Comment by pmcelhaney** [comment]
Is it only 2.x or does it happen on 3.x as well?

**Comment by platinumazure** [comment]
@pmcelhaney Good question, I'll try to repro with latest and see what happens.

Unfortunately the issue can be obscured by the fact that a plugin could fix itself (this only happens when a plugin exists locally but throws when it is require'd by ESLint). So I suppose the best thing I could do is to create a temporary repo representing a bad plugin that could be `npm link`'d to reproduce the issue. I'll see if I can get that done in the next couple of days.

**Comment by platinumazure** [comment]
I've been pretty busy with some other issues (both code I'm writing and issues I'm trying to shepherd through), so this has unfortunately fallen by the wayside. I'm hoping to confirm on ESLint 3.x this week and set up a fake plugin repo to prove the issue.

If we can keep this open a little while longer, I'd be most grateful. :smile:

**Comment by platinumazure** [comment]
**TSC Summary**: This issue is accepted, but I wanted to see if this merited being included on the core roadmap project.

**TSC Question**: Should this issue be added to the core roadmap project?

**Comment by kaicataldo** [comment]
As per the discussion during today's TSC meeting, this issue has been added to the Core Roadmap.

**Comment by platinumazure** [comment]
@kaicataldo has suggested also solving issue #7668 in this one. So the goal would be for the basic UX to change around plugin errors (i.e., user can tell via pretty exception message whether the plugin didn't exist or it threw an exception); and `eslint --debug` should also give some more information in this same scenario.

**Comment by kaicataldo** [comment]
Here's another one: https://github.com/eslint/eslint/issues/6976
