### ISSUE TITLE
indent adds a wrong amount of space when tabs are present

### ISSUE THREAD

**Issue by Wilfred** [eslint/eslint#6875]
Given the following file foo.js, which is tab indented:

```js
function foo() {
	if (true) {
		console.log('foo');
	}
}
```

Running `eslint --no-eslintrc --fix --rule 'indent: "warn"' foo.js` changes foo.js to:

```js
function foo() {
	                                        if (true) {
		                                        console.log('foo');
	}
}
```

This has inserted 40 spaces on lines 2 and 3. This isn't idempotent, running the same command again gives:

```js
function foo() {
	                                                                                if (true) {
		                                                                                console.log('foo');
	}
}
```

I'm using v3.2.2 with the default parser.

I was expecting eslint to replace the tabs with spaces. Failing that, I would have expected eslint to choose a size of tab so it can calculate the indent consistently, so `--fix` is idempotent for this rule.

**Comment by gyandeeps** [comment]
This is a known issue. I know long time back @platinumazure worked on something similar. Can't remember all the details.

**Comment by platinumazure** [comment]
The original issue was #4274. I had the beginnings of a fix but ran into a number of subtle issues with the rule that made me give up (especially when I learned that folks were considering rewriting the rule, but I can't find that issue right now).

Please follow #4274 for progress on this issue. I'm going to close this as a duplicate. Thanks for the report!
