### ISSUE TITLE
eslintrc at odds with npm link (and other node resolution friendly usages)

### ISSUE THREAD

**Issue by stefanpenner** [eslint/eslint#6877]
posted as per: https://github.com/eslint/eslint/pull/6865#issuecomment-238923390

eslintrc at odds with npm link (and other node resolution friendly usages)

#### Given 2 modules:

* Module `B`: the extraction of generic build tool code (the invoker of eslint)
* Module `A`: the application which which configures eslint + depends on the generic build tool code module

#### Working scenario:
1. `A` depends on `B`
2. `B` is a descendent of `A` on the file system
3. when `B` "resolves" A's configuration it will walk up the file system and eventually find it

```
~/projects/A/
~/projects/A/node_modules/B
```

#### Failing scenario 1:
1. `A` depends on `B`
2. `B` is in an ancestor directories node_module of `A` on the file system
3. when `B` "resolves" A's configuration it will walk up the file system and not find A, rather it may find something else

```
~/projects/A/
~/projects/node_modules/B
```

#### Failing scenario 2  (npm link):
1. `A` depends on `B`
2. `B` npm link'd to `A` on the file system
3. when `B` "resolves" A's configuration it will walk up the file system and not find A, rather it may find something else

```
~/projects/A/
~/projects/node_modules/B -> ~/src/B
```

----

In node references to other code, and modules is always related to the including modules position on disk. Not relative to the invoker, or `cwd`. But fs/system calls are relative to cwd().

```js
// foo/bar/baz.js
require('some-module'); // is a resolve relative to the current file
```

**Comment by nzakas** [comment]
Sorry, what I meant was to put these comments into issue #3458, which is what the pull request was attempting to address. It helps to keep all of the information together.

**Comment by stefanpenner** [comment]
https://github.com/eslint/eslint/issues/3458#issuecomment-239823560
