### ISSUE TITLE
Duplicate statement in docs for lines-around-comment rule

### ISSUE THREAD

**Issue by richardkall** [eslint/eslint#6879]
On http://eslint.org/docs/rules/lines-around-comment: 

> This rule does not apply to comments that appear on the same line as code and **does not require empty lines at the beginning or end of a file**. **Empty lines are also not required at the beginning or end of a file**.

Highlighted the duplicated part.

**Comment by platinumazure** [comment]
Closing, as your PR has been merged even though it doesn't link to this issue. Thanks for the contribution, it's greatly appreciated!
