### ISSUE TITLE
Optimize page title of rule docs

### ISSUE THREAD

**Issue by vitorbal** [eslint/eslint#6888]
I would like to modify the page title of the rule docs so that the name of the rule is the first thing in it.
This is a small optimization, but it's very convenient when the browser tab headers are very small, i.e see screenshots in https://github.com/eslint/eslint.github.io/issues/268.

Here's how it would look like for the `template-curly-spacing` rule, for example:
<img width="460" alt="screenshot 2016-08-11 22 15 10" src="https://cloud.githubusercontent.com/assets/626038/17603906/84c1dcf4-6013-11e6-919b-b0a78c80a552.png">

I need to modify the frontmatter that is generated for the rule docs in the `gensite` task, hence why I'm opening an issue here as well, besides [the one in eslint/eslint.github.io](https://github.com/eslint/eslint.github.io/issues/268).

**Comment by ilyavolodin** [comment]
Sounds good to me.

**Comment by kaicataldo** [comment]
Awesome!
