### ISSUE TITLE
Feature request: eslint-disable-block or eslint-disable-next

### ISSUE THREAD

**Issue by finom** [eslint/eslint#6903]
This is one almost real part of my code:
```js
function unbindNode(object, key, node, eventOptions) {
    if(typeof this === 'object' && whatever) {
        eventOptions = node;
        node = key;
        key = object;
        object = this;
    } else {
        checkObjectType(object, 'unbindNode');
    }
...
```

``no-param-reassign`` shows errors "Assignment to function parameter...". It's OK but I need to use ``eslint-disable-line`` for every line of the ``if`` block. I have almost the same code in tens of files and I really don't want to disable the rule globally.

I hope this proposition makes sense. At least istanbul has very similar feature ``/* istanbul ignore next */``

**Comment by platinumazure** [comment]
You can use `/* eslint-disable rule-name */` and `/* eslint-enable rule-name */` within the block. Note that those have to be block comments, not line comments.

Yes, that's two comments instead of one, but better than one per line.

**Comment by finom** [comment]
@platinumazure   I don't like it because it's not obvious where disabled rule is turned on back. Maybe this is my personal preference. But thank you for temporary (I hope so) solution.

**Comment by platinumazure** [comment]
Well, I like this idea personally, but we already support a number of these configuration comments (and the code handling said configuration comments is in need of refactoring), so we'll have to see what the rest of the team thinks.

**Comment by nzakas** [comment]
We also have `/* eslint disable-next-line */` already. 

I'm definitely not sold on adding another disable comment.

**Comment by ilyavolodin** [comment]
Agree. We already have multiple ways of doing the same thing. I don't think that adding yet another way is going to help, especially since it's not clear how it should handle edge cases:

```js
//eslint-disable-block
var a = 10; // what should happen in this case?
```

**Comment by alberto** [comment]
Closing this as out of scope.

**Comment by dandv** [comment]
My voice may be in the minority, but I would also like the ability to disable a rule per function. A common use case is decorating an object with extra properties. ESLint will complain with `no-param-reassign` about each assignment of the form

```js
function decorateObject(object) {
    ...
    object.extraProperty1 = ...  // eslint-disable-line no-param-reassign
    object.extraProperty2 = ...  // eslint-disable-line no-param-reassign
}
```

I'd rather not add

**Comment by smeijer** [comment]
Would be very useful for reduce statements:

```js
// eslint-disable-block no-param-reassign
arr.reduce((l, r) => {
  l[r] = index[r];
  return l;
}, {});
```

It would also be fine if `next-line` was effecting the params defined on the next line. This snippet doesn't work, but it would be awesome if it did:

```js
// eslint-disable-next-line no-param-reassign
arr.reduce((l, r) => {
  l[r] = index[r];
  return l;
}, {});
```

So in the snippet above, there should not be displayed any reassign errors for `l` and `r` in the scope of `reduce`.

**Comment by yamsellem** [comment]
@dandv @smeijer you can already disable a function block with eslint with a block comment.

```javascript
function decorateObject(object) { /* eslint-disable no-param-reassign */
    ...
    object.someSummaryProp = ...  
    object.extraProperty1 = ...  
    object.extraProperty2 = ... 
}
```

```javascript
arr.reduce((l, r) => { /* eslint-disable */
  l[r] = index[r];
  return l;
}, {});
```
