### ISSUE TITLE
Add option to camelCase rule to ban the use of camelCase in variable names

### ISSUE THREAD

**Issue by samgensburg** [eslint/eslint#6913]
I am currently working on my second major project requiring the use of snake_case (or whatever else you would like to call it) for defined variable names. Unfortunately, eslint has no option to verify that variables are named appropriately in this naming scheme! I would like to add one. Given that eslint reasonably bans conflicting rules, this would need to be an additional option for the camelCase rule.

**What version of ESLint are you using?**
v3.1.1

**What rule do you want to change?**
camelCase

**What code should be flagged as incorrect with this change?**
`var myVariable;`
`function definedFunction()`
`class NewClass`

**What happens when the rule is applied to this code now?**
This is the current goal usage of the rule.

I would like

**Comment by platinumazure** [comment]
Have you looked at the [`id-match`](http://eslint.org/docs/rules/id-match)? Think that will give you the flexibility you need.

**Comment by kaicataldo** [comment]
@samgensburg friendly ping to see if @platinumazure's comment answered your question

**Comment by alberto** [comment]
Closing for now.
