### ISSUE TITLE
user no-unused-vars except function

### ISSUE THREAD

**Issue by Dn9x** [eslint/eslint#6917]
my code:
```main.js
var name = 'TM';
function show() {
    console.log('this is test');
}
```

```main.html
//something
<button onClick="show()">Test</button>
//something
```

it have error:
error  'name' is defined but never used  no-unused-vars
error  'show' is defined but never used  no-unused-vars

i only want to ignore function. how to do??

**Comment by ljharb** [comment]
In the latter case, "show()" is being used as a string (and you wouldn't want to invoke it). You want `onClick={show}`.

In the former case, it does seem like you should be getting an error about `name`.

**Comment by Dn9x** [comment]
@ljharb thank you reply me.
i find this: https://github.com/eslint/eslint/issues/5086#issuecomment-178115336
i can use like this:
```
function show() { // eslint-disable-line 
    //dosomething
}
```
but, if i need write like `onClick="show()"` and config in global, how to do??

**Comment by ljharb** [comment]
If you're asking how to write an oldschool inline event handler in JSX, that's not what you want to do. You want `onClick={show}` and to make sure `show` is available in scope.

Either way I don't think this applies to eslint.

**Comment by Dn9x** [comment]
@ljharb oh, i am sorry, i dont write clear. this demo is not single page.
i dont have use react, i have two file,
``` main.js
function show() {
    console.log('this is test');
}
```
and 
```main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>test</title>
</head>
<body>
    <button onClic="show()">test</button>
    <script type="text/javascript" src="main.js"></script>
</body>
</html>
```
i can use  inline comments disable it. but my project already finish 90%, i have a lot of js files. so i want config in global.

**Comment by vitorbal** [comment]
Hmm, I'm not really sure this is an important use case that would justify a new option to the `no-unused-vars` option. I would say your best bet would be to use the "eslint-disable" comments as you already described.
Let's see if someone else from the team disagrees.

**Comment by ilyavolodin** [comment]
This is the reason `no-unused-vars` supports `exported` comment. If you have functions/variables that are unused in the current file but used elsewhere, they should be marked as exported. For more information, see documentation: http://eslint.org/docs/rules/no-unused-vars#exported

**Comment by platinumazure** [comment]
I think you want to use the `/* exported */` comment here. That tells ESLint that your function is intended to be exported to global scope and used by a different file.

```js
/* exported show */

function show() {
    // ...
}
```

**Comment by Dn9x** [comment]
@platinumazure @ilyavolodin @vitorbal @ljharb very thanks.
I think best way is i use `// eslint-disable-line `.  because i dont need use CommonJS or ECMAScript modules. 
very thanks.
