### ISSUE TITLE
Indent with RequireJS code convention.

### ISSUE THREAD

**Issue by mattcollier** [eslint/eslint#6918]
**What version of ESLint are you using?** 3.3.1

**What parser (default, Babel-ESLint, etc.) are you using?** AtomLinter/linter-eslint

**Please show your full configuration:**
```
{
  "env": {
    "es6": true
  },
  "rules": {
    "comma-dangle": ["error", "never"],
    "eol-last": "error",
    "keyword-spacing": ["error", {"overrides": {
      "catch": {"after": false},
      "do": {"after": false},
      "for": {"after": false},
      "if": {"after": false},
      "switch": {"after": false},
      "while": {"after": false}
      }}],
    "indent": ["error", 2, {"SwitchCase": 1}],
    "linebreak-style": ["error", "unix"],
    "max-len": ["error", 80],
    "no-irregular-whitespace": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multiple-empty-lines": ["error", {"max": 1}],
    "no-spaced-func": "error",
    "no-trailing-spaces": "error",
    "object-curly-spacing": ["error", "never"],
    "semi": ["error", "always"],
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", "never"],
    "space-infix-ops": "error",
    "space-in-parens": ["error", "never"],
    "spaced-comment": ["error", "always"]
  }
}
```
**What did you do? Please include the actual source code causing the issue.**

Making the switch from JSCS to ESLint.  We have a code convention where we use RequireJS where we structure the code like this:

```
define([
  'angular',
  'lodash'
], function(angular, _) {
// no indent
'use strict';

var foo = 0;
var bar = 'hello';
// end no indent
});
```

ESLint expects the lines NOT being indented to be indented.

**What did you expect to happen?**

JSCS was somehow able to ignore this issue, but we did not have any special rules that I'm aware of.  The JSCS config is here: https://github.com/digitalbazaar/bedrock/blob/master/.jscsrc

Is there an ESLint setting I can use to get ESLint to cooperate with this code convention?

**Comment by nzakas** [comment]
We have an open issue to implement a solution for this: https://github.com/eslint/eslint/issues/6690
