### ISSUE TITLE
eol-last: Add "none" option to enforce no line break at end of file

### ISSUE THREAD

**Issue by kdex** [eslint/eslint#6938]
**What version of ESLint are you using?**
3.2.2
**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint 6.1.2
**Please show your full configuration:**
<details>
<summary>.eslintrc</summary>
```json
{
	"env": {
		"browser": true,
		"es6": true,
		"node": true
	},
	"extends": [
		"eslint:recommended",
		"plugin:react/recommended"
	],
	"installedESLint": true,
	"parser": "babel-eslint",
	"parserOptions": {
		"ecmaFeatures": {
			"experimentalObjectRestSpread": true,
			"jsx": true
		},
		"sourceType": "module"
	},
	"plugins": [
		"filenames",
		"react"
	],
	"rules": {
		"accessor-pairs": [
			"error"
		],
		"array-bracket-spacing": [
			"error",
			"never"
		],
		"array-callback-return": [
			"error"
		],
		"block-scoped-var": [
			"error"
		],
		"brace-style": [
			"warn",
			"stroustrup"
		],
		"camelcase": [
			"error", {
				"properties": "always"
			}
		],
		"comma-dangle": [
			"warn",
			"never"
		],
		"comma-style": [
			"warn",
			"last"
		],
		"comma-spacing": [
			"warn", {
				"before": false,
				"after": true
			}
		],
		"complexity": [
			"warn"
		],
		"consistent-return": [
			"error"
		],
		"consistent-this": [
			"error"
		],
		"curly": [
			"error"
		],
		"default-case": [
			"error"
		],
		"dot-notation": [
			"error"
		],
		"dot-location": [
			"error",
			"property"
		],
		"eqeqeq": [
			"error"
		],
		"filenames/match-regex": [
			"error",
			"^[a-zA-Z.]+$"
		],
		"guard-for-in": [
			"error"
		],
		"indent": [
			"warn",
			"tab", {
				"SwitchCase": 1
			}
		],
		"jsx-quotes": [
			"warn",
			"prefer-double"
		],
		"key-spacing": [
			"error", {
				"beforeColon": false,
				"afterColon": true,
				"mode": "strict"
			}
		],
		"keyword-spacing": [
			"warn", {
				"before": true,
				"after": true
			}
		],
		"linebreak-style": [
			"error",
			"unix"
		],
		"max-statements-per-line": [
			"warn", {
				"max": 1
			}
		],
		"new-parens": [
			"warn"
		],
		"no-caller": [
			"error"
		],
		"no-case-declarations": [
			"error"
		],
		"no-cond-assign": [
			"error"
		],
		"no-console": [
			"off"
		],
		"no-dupe-args": [
			"error"
		],
		"no-dupe-keys": [
			"error"
		],
		"no-duplicate-case": [
			"error"
		],
		"no-empty": [
			"warn"
		],
		"no-empty-character-class": [
			"error"
		],
		"no-empty-function": [
			"warn"
		],
		"no-empty-pattern": [
			"error"
		],
		"no-eval": [
			"error"
		],
		"no-ex-assign": [
			"error"
		],
		"no-extend-native": [
			"error"
		],
		"no-extra-bind": [
			"error"
		],
		"no-extra-boolean-cast": [
			"warn"
		],
		"no-extra-semi": [
			"error"
		],
		"no-fallthrough": [
			"error"
		],
		"no-floating-decimal": [
			"error"
		],
		"no-func-assign": [
			"error"
		],
		"no-inline-comments": [
			"warn"
		],
		"no-invalid-regexp": [
			"error"
		],
		"no-implicit-coercion": [
			"warn"
		],
		"no-implicit-globals": [
			"error"
		],
		"no-implied-eval": [
			"error"
		],
		"no-iterator": [
			"error"
		],
		"no-labels": [
			"error"
		],
		"no-lone-blocks": [
			"warn"
		],
		"no-multiple-empty-lines": [
			"warn", {
				"max": 0,
				"maxBOF": 0,
				"maxEOF": 0
			}
		],
		"no-negated-in-lhs": [
			"error"
		],
		"no-multi-spaces": [
			"error"
		],
		"no-multi-str": [
			"error"
		],
		"no-native-reassign": [
			"error"
		],
		"no-new-func": [
			"error"
		],
		"no-new-wrappers": [
			"error"
		],
		"no-obj-calls": [
			"error"
		],
		"no-octal": [
			"error"
		],
		"no-octal-escape": [
			"error"
		],
		"no-param-reassign": [
			"warn"
		],
		"no-proto": [
			"error"
		],
		"no-redeclare": [
			"error", {
				"builtinGlobals": true
			}
		],
		"no-regex-spaces": [
			"error"
		],
		"no-return-assign": [
			"error"
		],
		"no-script-url": [
			"error"
		],
		"no-self-assign": [
			"error"
		],
		"no-self-compare": [
			"error"
		],
		"no-sequences": [
			"warn"
		],
		"no-sparse-arrays": [
			"error"
		],
		"no-this-before-super": [
			"error"
		],
		"no-throw-literal": [
			"error"
		],
		"no-trailing-spaces": [
			"warn"
		],
		"no-underscore-dangle": [
			"warn", {
				"allow": ["_rawDBType"]
			}
		],
		"no-unneeded-ternary": [
			"warn"
		],
		"no-delete-var": [
			"error"
		],
		"no-unexpected-multiline": [
			"error"
		],
		"no-unmodified-loop-condition": [
			"error"
		],
		"no-unreachable": [
			"error"
		],
		"no-unused-expressions": [
			"error"
		],
		"no-useless-call": [
			"error"
		],
		"no-useless-concat": [
			"error"
		],
		"no-useless-escape": [
			"error"
		],
		"no-void": [
			"error"
		],
		"no-warning-comments": [
			"warn", {
				"terms": [
					"todo",
					"fixme",
					"fix",
					"bugfix",
					"warn"
				],
				"location": "anywhere"
			}
		],
		"no-with": [
			"error"
		],
		"no-var": [
			"error"
		],
		"object-curly-spacing": [
			"error",
			"always"
		],
		"object-property-newline": [
			"error"
		],
		"object-shorthand": [
			"error"
		],
		"prefer-arrow-callback": [
			"warn"
		],
		"prefer-const": [
			"warn"
		],
		"prefer-reflect": [
			"warn"
		],
		"prefer-rest-params": [
			"warn"
		],
		"prefer-spread": [
			"warn"
		],
		"prefer-template": [
			"warn"
		],
		"quotes": [
			"warn",
			"double", {
				"allowTemplateLiterals": true
			}
		],
		"radix": [
			"error",
			"as-needed"
		],
		"react/display-name": [
			"off"
		],
		"require-jsdoc": [
			"warn", {
				"require": {
					"FunctionDeclaration": true,
					"MethodDefinition": true,
					"ClassDeclaration": true
				}
			}
		],
		"semi": [
			"error",
			"always"
		],
		"space-in-parens": [
			"warn",
			"never"
		],
		"space-infix-ops": [
			"warn"
		],
		"space-unary-ops": [
			"warn"
		],
		"strict": [
			"error",
			"never"
		],
		"template-curly-spacing": [
			"error",
			"never"
		],
		"use-isnan": [
			"error"
		],
		"valid-jsdoc": [
			"error", {
				"prefer": {
					"return": "return"
				},
				"requireReturn": false,
				"requireParamDescription": true,
				"requireReturnDescription": false,
				"requireReturnType": true,
				"preferType": {
					"String": "string",
					"Number": "number",
					"Object": "object",
					"Symbol": "symbol",
					"Function": "function",
					"Boolean": "boolean"
				}
			}
		],
		"yield-star-spacing": [
			"error",
			"after"
		],
		"yoda": [
			"error",
			"never"
		]
	}
}
```
</details>
**What did you do? Please include the actual source code causing the issue.**
I am trying to lint a file that ends in a single newline character, making contributors aware that they should configure their editors' saving configuration properly, as many of them append an invisible newline on file saves.
**What did you expect to happen?**
If the file ends in a single newline character, this should be a linting error.
**What actually happened? Please include the actual, raw output from ESLint.**
ESLint doesn't output any linting error, but it should.

**Comment by vitorbal** [comment]
Could you check f the problem still happens if you use the default parser? I couldn't reproduce what you describe with the following test file and config:

```javascript
var foo = 5;
var bar = 3;


```

```json
{
    "root": true,
    "rules": {
        "no-multiple-empty-lines": [
            "warn", {
                "max": 0,
                "maxBOF": 0,
                "maxEOF": 0
            }
        ]
    }
}
```

Result:
```shell
$ node_modules/.bin/eslint --version
v3.3.1
$ node_modules/.bin/eslint src/test.js

/Users/vitorbalocco/Workspace/eslint_bug_tester/src/test.js
  4:2  warning  Too many blank lines at the end of file. Max of 0 allowed  no-multiple-empty-lines

✖ 1 problem (0 errors, 1 warning)
```

If you could provide a reduced version of your file where the problem is reproducible, that also probably helps us track down the issue. Thanks!

**Comment by kdex** [comment]
@vitorbal You've deleted your comment just now; does that mean you were able to reproduce the issue or should I still follow your suggestions?

**Comment by vitorbal** [comment]
@kdex Sorry, I got a bit confused trying to reproduce your issue :-)

I don't think `no-multiple-empty-lines` does what you want as it validates only the number of **consecutive** empty lines.

That means that this is correct:
```javascript
/*eslint no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 0 }]*/\n
\n
var foo = 5;\n
var bar = 3;\n

```

Whereas this isn't:
```javascript
/*eslint no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 0 }]*/\n
\n
var foo = 5;
var bar = 3;\n
\n

```
The closest thing I can find for what you want is the `eol-last` rule, but it only works for enforcing that last trailing newline.

**Comment by kdex** [comment]
@vitorbal I would have expected that setting `max` to `0` in `no-multiple-empty-lines` would also take care of the last empty line, judging from the semantics that the rule's name implies. I.e. I'd expect that the following should have failed, with `0` suggesting that empty lines are globally forbidden, regardless of whether they're the last EOL in a file or not:

```js
/*eslint no-multiple-empty-lines: ["error", { "max": 0, "maxEOF": 0 }]*/\n
var foo = 5;\n
var bar = 3;\n
```

As you have already mentioned, `eol-last` can't be used to enforce that it the last EOL omitted, but rather to encforce that it's there.

Thinking about it, there are two places where one might want to implement this behavior:

- Making `max: 0` a special case in `no-multiple-empty-lines` 
- Adding `"always"`/`"never"` semantics to `eol-last`

**Comment by pmcelhaney** [comment]
Since the current options for `eol-last` are "windows" and "unix" it might make sense to add a "none" option.

**Comment by kaicataldo** [comment]
@kdex Kind of confused here - am I misunderstanding that you want to disallow any newlines at the ends of files? 

Using this .eslintrc
```json
{
  "rules": {
    "no-multiple-empty-lines": ["error", { "max": 0, "maxEOF": 0 }]
  }
}
```
the following produces an error:
```js
var foo = 1;\n
var bar = 2;\n
```
while this does not:
```js
var foo = 1;\n
var bar = 2;
```

Apologies if I'm misunderstanding what the problem is, but if so, could you clarify?

**Comment by kdex** [comment]
@kaicataldo Yes, that's exactly what I'm trying to do, but what you're suggesting is not what actually happens in ESLint.

The settings you've suggested will produce an error for

```js
var foo = 1;\nvar bar = 2;\n\n
```
but not for
```js
var foo = 1;\nvar bar = 2;\n
```
and also not for what I actually want:
```js
var foo = 1;\nvar bar = 2;
```

Please have a look at [this test case](https://github.com/kdex/eslint-issue-6938).

**Comment by alberto** [comment]
`\n` is considered a line terminator so there isn't really an empty line at the end of the file in your case. So, what you are requesting is for the last line not to be terminated, which I'm not sure is a good idea, given many editor force that. Check [this](https://github.com/eslint/eslint/issues/4228#issuecomment-150569111) for reference.

**Comment by kdex** [comment]
@alberto Thanks for the reference! For most editors I've tried (nano/pico, Atom, Kate, vim), this is really a matter of preference. No one *forces* you to use a final `\n`. :smile: 

In fact, [EditorConfig](http://editorconfig.org/) files even let you specify a boolean parameter `insert_final_newline` to ask editors not to insert these characters project-wide. It would be neat if ESLint could ensure this is actually followed.

**Comment by alberto** [comment]
Sorry, I didn't mean they force it, but rather that they insert it by default.

As I said, this rule is about empty lines and there are no empty lines in this case. What you want is a rule that ensures there is no line terminator at the end of the file. It doesn't fit cleanly in this rule in its current form, so I think that should be a separate rule, and I don't think that's common enough to be in core, so you may want to write this as a custom rule.

**Comment by platinumazure** [comment]
@alberto Couldn't OP use eol-last?

**Comment by kdex** [comment]
@platinumazure `eol-last` currently doesn't support `always`/`never` semantics, meaning that it can only be used to ensure that a final `\n` *exists*—not to check whether is *does not exist*.

**Comment by platinumazure** [comment]
I think that's a better rule to enhance than no-multiple-empty-lines. That's what I was getting at.

**Comment by alberto** [comment]
@platinumazure @pmcelhaney yes, I forgot we had `eol-last`. That's definitely a better place for this.

**Comment by kaicataldo** [comment]
@kdex You're right - thanks for clarifying!

**Comment by platinumazure** [comment]
Okay, let's get this moving. I proposed adding a "none" option to `eol-last`. I will champion. Can we get three endorsements?

**Comment by kaicataldo** [comment]
What about `"always"` and `"never"` (defaulting to `"always"`) for consistency with our other rules?

**Comment by platinumazure** [comment]
@kaicataldo In this case, because there's actually 2 modes of enforcement: "unix" or "windows". Either of those is synonymous with "always" and furthermore defines what the linebreaks should specifically look like. So in this case, "none" feels like a better fit to me, although I could live with "never".

But I don't think switching to "always" would help, unless we reconfigured the schema:

```json
{
    "no-multiple-empty-lines": ["error", "always", { "style": "unix" }]
}
```

Which seems unnecessary to me (when done strictly to match other rules' schemas). I think it's okay to have two styles of schema (always/never, vs type1/type2/none), but if you feel strongly about it, let's work to build consensus.

**Comment by kaicataldo** [comment]
Makes sense - I'm fine with what you proposed. I think you're right that it does seem to add unnecessary complexity.

**Comment by platinumazure** [comment]
@kaicataldo Thanks-- just for my understanding, you're okay with unix/windows/none, or do you want unix/windows/never?

**Comment by kaicataldo** [comment]
I think "none" makes more sense in that context, and yeah, :+1: for me

**Comment by platinumazure** [comment]
@kdex I've changed the title of the issue to reflect where the discussion seems to be going-- hope that's okay. Thanks!

**Comment by kdex** [comment]
@platinumazure Ah, good point. Thank you!

**Comment by vitorbal** [comment]
(y) from me as well!

**Comment by nzakas** [comment]
:+1:
