### ISSUE TITLE
Question: Access line number from `context`?

### ISSUE THREAD

**Issue by amilajack** [eslint/eslint#6943]
Is it possible for a plugin to have access to the current line number from the `context`?

**Comment by platinumazure** [comment]
If you're processing a particular `node` in your rule, you should be able to get its line number using `node.loc.start.line`. You can play around on http://astexplorer.net (make sure to use the "Espree" parser) to see how location information is represented in the parse tree.

**Comment by amilajack** [comment]
@platinumazure I cant find 'node' in the ast explorer. What do I need to do to make it show up?

**Comment by platinumazure** [comment]
Ah, sorry, I assumed you were writing a rule as well.

You can write any example code you want in ASTExplorer. Then just click on some part of the code, and the display on the right should change to reflect what node type you've clicked on. (For example, click the "if" in an if statement.) There should be a "loc" object. (So `node`, in ASTExplorer, is the full object you're looking at.)

If you can describe the exact problem you're trying to solve, we can try to give better insight. (This sounds like a possible [XY problem](http://xyproblem.info/) as it is.)

**Comment by amilajack** [comment]
I'm trying to write a plugin for flow that collects errors from flow and reports them in eslint

**Comment by mysticatea** [comment]
![astexplorer-loc](https://cloud.githubusercontent.com/assets/1937871/17831798/3534bfea-672e-11e6-9e48-d93610dd2e2b.gif)

**Comment by amilajack** [comment]
@mysticatea Thanks!
