### ISSUE TITLE
Add a --fix option for no-extra-parens

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#6944]
I'm using Node v6.4.0 and ESLint v3.3.1.

I think it would be useful to have an autofix option for the `no-extra-parens` rule. I think the fixer would be fairly simple; it would just remove the offending parens from the source code.

Presumably, the fixer would follow the same options as the rule itself to determine whether parentheses are gratuitous. For example:

```js
/* eslint no-extra-parens: "error" */

var foo = (bar && baz) || qux;

// gets fixed to:

var foo = bar && baz || qux;
```

```js
/* eslint no-extra-parens: ["error", "all", { "nestedBinaryExpressions": false }] */

// does not get fixed, because these parens are not errors with nestedBinaryExpressions: false
var foo = (bar && baz) || qux;
```

---

One special case for `no-extra-parens` is when a parenthesized expression is immediately preceded by a keyword:

```js
//  In this case, the fixer should insert a space in addition to removing the parens:
function foo () {
  return(0);
}

// gets fixed to:

function foo () {
  return 0;
}


// However, the fixer probably should not insert a space if a space is already present:
function foo () {
  return (0);
}

// gets fixed to:

function foo () {
  return 0;
}
```

---

If this issue gets accepted, I would be happy to send a PR for it.

edit: Added a special case that I noticed

**Comment by platinumazure** [comment]
Sounds reasonable to me. I'll endorse this (:+1:).

**Comment by mysticatea** [comment]
:+1:

**Comment by gyandeeps** [comment]
:+1:

**Comment by ilyavolodin** [comment]
👍  I'll champion this.
