### ISSUE TITLE
Question: `init` step for plugins?

### ISSUE THREAD

**Issue by amilajack** [eslint/eslint#6949]
Is there a way for plugins to run an initialization process before being? Also is there a way of accessing values returned from the init process inside of the create fn?

**Comment by ilyavolodin** [comment]
Plugin is just a JavaScript file that exports an object of specified type. You can create an initialization function and use that to export an object, that's up to you. For more information see our plugin documentation here: http://eslint.org/docs/developer-guide/working-with-plugins
