### ISSUE TITLE
Add a custom rule to enforce conventions in rule metadata

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#6954]
Forking this from [discussion on #6915](https://github.com/eslint/eslint/pull/6915#issuecomment-240090220).

**The problem you want to solve.**

Most of our rule descriptions begin with lowercase letters. #6915 corrected two that didn't. Right now, we have no automatic verification of conventions there.

**Your take on the correct solution to the problem.**

> @ilyavolodin We should think about adding a custom rule for this.

> @vitorbal sounds good, maybe the custom rule could also enforce that the description starts with one of "enforce", "require", "disallow", etc.?
When we make it so the title of each rule page also comes from the meta.description we will benefit even more from this consistency.

**Comment by vitorbal** [comment]
I'm willing to work on this if it get's accepted. Except if you'd like to take a stab at it, @btmills!

**Comment by btmills** [comment]
@vitorbal all yours!

**Comment by platinumazure** [comment]
Dang, we haven't had any movement here in a while.

I'm in favor, but I'm not sure if this requires TSC consensus. @btmills What are our next steps here?

**Comment by btmills** [comment]
Since this isn't so much a core feature as it is an internal chore, I can't think of anything that would require TSC here. Next step be consensus and acceptance. I'll add my :+1:. @vitorbal since you're willing to implement, are you also championing? It looks like @ilyavolodin :+1:'d my original comment, so assuming that counts as another (ref https://github.com/eslint/eslint/issues/6424#issuecomment-243941055), that would give us 3 including a champion.

**Comment by vitorbal** [comment]
Sure, I'll champion!

**Comment by vitorbal** [comment]
PR is up here: #7155
