### ISSUE TITLE
Rename "AirBnB" => "Airbnb" config initializer choice

### ISSUE THREAD

**Issue by hshoff** [eslint/eslint#6968]
1. The version of ESLint you are using.

`3.3.1`

2. The problem you want to solve.

I was trying out the config initializer tool and noticed the below typo:
![screen shot 2016-08-24 at 11 33 42 am](https://cloud.githubusercontent.com/assets/339208/17943046/a9016f6e-69ee-11e6-97ec-c8853e38d308.png)

3. Your take on the correct solution to problem.

Rename `AirBnB` choice name to our preferred spelling of `Airbnb`

PR coming.

**Comment by ilyavolodin** [comment]
Sounds good to me. Accepting since it's a minor change, and we should follow correct spelling.
