### ISSUE TITLE
Core rule messages should use our template syntax and avoid concatenation

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6977]
Goal is to make sure all rule messages that need runtime data use the `{{ variable }}` format and the `data:` key, rather than string concatenation or ES6 template literals.

**Comment by platinumazure** [comment]
Note; Discussion came up in chat about whether we should consider just using ES6 templates instead. At this point I just want to get all the rules into our "current"/"old" style before we consider a huge change like that (which would be breaking unless we supported the current form, anyway).

**Comment by kaicataldo** [comment]
I like the idea of doing this task as a prerequisite to https://github.com/eslint/eslint/issues/6407#issuecomment-241223919. We can use ES6 template literals everywhere else.

**Comment by platinumazure** [comment]
Working on this. I might just do the ES6 templates everywhere else in
lib/rules so that someone can use prefer-template to help make sure I
didn't miss any.

**Comment by kaicataldo** [comment]
Great. I can work on the converting to template literals in other directories besides `lib/rules`.

**Comment by platinumazure** [comment]
PR up at #6989.

**Comment by gyandeeps** [comment]
Just curious, why are we just not going directly to template strings? (sorry if I missed the discussion)

**Comment by platinumazure** [comment]
@gyandeeps At this point, for no real reason besides following our own guidelines for how to write rules.

There's also issue #6740-- one benefit I could see from that issue is being able to show possible rule messages (with format placeholder) in CLI docs. That said, if there is a way to take a template string and render it as a string without interpolation, I wouldn't be opposed to using that format.

**Comment by mysticatea** [comment]
I prefer #6740 than ES templates because it's easier to support i18n 😇
