### ISSUE TITLE
Does the "Architecture" documentation need some tweaks?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6982]
Here's the intro to the [architecture document](http://eslint.org/docs/developer-guide/architecture) as of the date this issue was created:

> At a high level, there are a few key parts to ESLint:
> 
> * bin/eslint.js - this is the file that actually gets executed with the command line utility. It’s a dumb wrapper that does nothing more than bootstrap ESLint, passing the command line arguments to cli. This is intentionally small so as not to require heavy testing.
> * lib/cli.js - this is the heart of the ESLint CLI. It takes an array of arguments and then uses eslint to execute the commands. By keeping this as a separate utility, it allows others to effectively call ESLint from within another Node.js program as if it were done on the command line. The main call is cli.execute(). This is also the part that does all the file reading, directory traversing, input, and output.
> * lib/eslint.js - this is the core eslint object that does code verifying based on configuration options. This file does no file I/O and does not interact with the console at all. For other Node.js programs that have JavaScript text to verify, they would be able to use this interface directly.

This is inconsistent with later section headers, which are:
* The `cli` object
* The `CLIEngine` object
* The `eslint` object

I'm wondering if the intro should include CLIEngine, and/or if the cli object should be removed from either the intro or the later sections. I know that we generally encourage folks to use CLIEngine when developing against ESLint, but we also have the [Node.js](http://eslint.org/docs/developer-guide/nodejs-api) API docs for that.

Maybe there's nothing to do here, but I wanted to ask. At the very least, the [commit history for the file](https://github.com/eslint/eslint/commits/master/docs/developer-guide/architecture.md) shows that the content has not been modified significantly for over a year.

Please feel free to close if we definitely don't want/need to do anything here.

**Comment by nzakas** [comment]
If you want to make a change, just a submit a PR. This is just docs, if you think there's a way to improve it, go ahead and do it, you don't have to ask for permission.

**Comment by platinumazure** [comment]
@nzakas Thanks, noted. At the time I submitted the issue, I didn't really have a clear plan for what the best change was, so I was hoping for some discussion and an issue seemed like the best way to gather that discussion. In future I might just pick "an" approach and send a PR.

**Comment by nzakas** [comment]
I think submitting a PR is best. Let's not overwhelm people with long abstract discussions about documentation. In fact, I'd say let's close this and just submit a PR with your suggestions.

**Comment by platinumazure** [comment]
Sounds good. Closing.
