### ISSUE TITLE
Rule message substitution will get confused with triple braces

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6988]
Currently, it is impossible to perform rule substitution for no-regex-spaces because the message displays a number in curly braces (representing a regex quantifier).

The correct message: `"Spaces are hard to count. Use {{{count}}}."`

However, the regex for rule message substitution looks for `\{\{\s*(.+?)\s*\}\}`, which will result in the substitution code looking for a `"{count}"` key.

I'd like to replace `(.+?)` with `([^}]+?)`. This will force the regex to match `{{count}}` and extract `"count"` as the key.

**Comment by nzakas** [comment]
Go for it. You can accept bugs that you've verified.
