### ISSUE TITLE
Add a --fix option for new-parens

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#6994]
I'm using Node v6.4.0 and ESLint v3.4.0.

It would be useful to have an autofix option for the `new-parens` rule. The fixer would simply add `()` to all places where the rule reports an error.

```js
var x = new Foo;
var y = new foo.Bar;
var z = (new Foo).bar;

// gets corrected to:

var x = new Foo();
var y = new foo.Bar();
var z = (new Foo()).bar;
```

I would be willing to add this if the issue is accepted.

**Comment by platinumazure** [comment]
Thanks for the issue!

This seems reasonable to me. I'll champion this enhancement.

**Comment by mysticatea** [comment]
👍 

And I'd like to suggest one more case.

- `new (Foo)` → `new (Foo)()` (it will add parentheses to outside of parentheses which enclose callee.)

**Comment by not-an-aardvark** [comment]
@mysticatea: I agree with that, but it seems like `new-parens` does not currently report `new (Foo)` as an issue. I suppose that's a separate bug.

**Comment by mysticatea** [comment]
Oh, it's a bug!

Currently, `new-parens` rule seems to check whether there are 2 or more parentheses in a `NewExpression` node. It does not check whether the parentheses is for arguments or not.

I will open an issue.

**Comment by nzakas** [comment]
👍

**Comment by vitorbal** [comment]
:+1:
