### ISSUE TITLE
Add a --fix option for prefer-arrow-callback

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7002]
I'm using Node v6.4.0 and ESLint v3.4.0.

It would be useful to have an autofix option for the `prefer-arrow-callback` rule. The fixer would attempt to convert regular callback functions to arrow functions.

* If the function does not use `this`, `super`, `arguments`, or `new.target`, and it is not explicitly bound, it can be replaced naively:

```js
/* eslint prefer-arrow-callback: ["error"] */

[1, 2, 3].map(function(a, b, c) {
  return a * 2;
});

// gets fixed to:

[1, 2, 3].map((a, b, c) => {
  return a * 2;
});
```

* If the function is explicitly bound with `.bind(this)`, and it does not use `super`, `arguments`, or `new.target`, the binding can be removed and the function can be replaced:

```js
/* eslint prefer-arrow-callback: ["error"] */

[1, 2, 3].map(function(a, b, c) {
  return a * 2;
}.bind(this));

// gets fixed to:

[1, 2, 3].map((a, b, c) => {
  return a * 2;
});

// ---

[1, 2, 3].map(function(a, b, c) {
  return a * this.foo;
}.bind(this));

// gets fixed to:

[1, 2, 3].map((a, b, c) => {
  return a * this.foo;
});

```

* If the option `{allowUnboundThis: false}` is used, and the function includes `this` without being explicitly bound, the problem should not get fixed, since there is no way to be sure of the correct `this` value:

```js
/* eslint prefer-arrow-callback: ["error", {allowUnboundThis: false}] */
[1, 2, 3].map(function(a, b, c) {
  return a * this.foo;
});

// (Reports an error, but is not autofixed)
```

* If the function uses `super`, `arguments`, or `new.target`, the rule does not report any problems, so nothing gets fixed.

```js
/* eslint prefer-arrow-callback: ["error"] */

[1, 2, 3].map(function(a, b, c) {
  return arguments[0] * 5;
});

// (no errors are reported, so no fixes are performed)
```

* To avoid SyntaxErrors, the fixer should not fix anything unless ES6 parsing is enabled. 

---

Other things to consider:

* If the `{allowNamedFunctions: false}` option is used and a function has a name, should the function still be changed when autofixing? (This doesn't break recursive functions, since those are ignored by `prefer-arrow-callback` anyway.) I think the fixer should still fix these functions; if people want to allow named functions, then they should set `{allowNamedFunctions: true}`.

---

I would be willing to add this if the issue is accepted.

**Comment by platinumazure** [comment]
I can see how this would be useful, but this would be a massive fix (in terms of characters of source code affected per fix). However, the fix plan seems pretty sensible. I'll endorse (:+1:).

**Comment by not-an-aardvark** [comment]
> but this would be a massive fix (in terms of characters of source code affected per fix)

Note that this is only a massive fix if `.bind(this)` is used; otherwise, the fix would just replace `function (a, b, c)` with `(a, b, c) =>` and leave the rest of the function untouched.

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
:+1:

**Comment by mysticatea** [comment]
I will champion this.
We needs one more :+1: from the team.

**Comment by platinumazure** [comment]
Not fair @mysticatea, you endorsed and championed and I double-counted you. :stuck_out_tongue_winking_eye: One more :+1: from the team as @mysticatea said.

**Comment by vitorbal** [comment]
I'll :+1: this!
