### ISSUE TITLE
Docs: class-methods-use-this and "ECMAScript 6" section

### ISSUE THREAD

**Issue by lukeapage** [eslint/eslint#7005]
The new "class-methods-use-this" is under best practices and not "ECMAScript 6" in the docs, which seems inconsistent.

But I've found it strange you even separate the "ECMAScript 6" rules. Will you have a section for 2016 and 2017? You might consider moving all the rules under the various "best practices" "stylistic" etc. sections.

**Comment by platinumazure** [comment]
I agree, but we'll see what the rest of the team thinks.

Personally I'd love to see a primary category (possible errors, best practices, style) and then have "tags" for things like ES2015, ES2016, variables, Node-specific which could be applied on rules in all categories.

**Comment by mysticatea** [comment]
Actually, some ES6 rules are on outside of `ECMAScript 6` section.

- `no-dupe-keys` (until ES5, duplicated property names are syntax error)
- `no-template-curly-in-string`
- `class-methods-use-this`
- `no-case-declarations`
- `no-empty-pattern`

I also would love the "tags" idea.

**Comment by kaicataldo** [comment]
I still think this is a worthwhile idea, but it's time to close this issue since we haven't had any activity in so long. If anyone is interested in this and has a proposal for how we could implement tags, please feel free to make an issue!
