### ISSUE TITLE
Help to switch from jscs and jshint to eslint in mediawiki please?

### ISSUE THREAD

**Issue by paladox** [eslint/eslint#7011]
**What version of ESLint are you using?**
the latest

**What parser (default, Babel-ESLint, etc.) are you using?**
grunt-eslint

**Please show your full configuration:**
None yet need help to switch please?

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

Hi could I have some help to switch mediawiki to eslint please.

I have uploaded the patch here https://gerrit.wikimedia.org/r/#/c/307286/1 but it fails.

I carnt seem to get all the jscs configs switched and some of the jshint configs too.

It fails https://integration.wikimedia.org/ci/job/mediawiki-core-npm-node-4-jessie/117/console

Plus the config names are confussing which makes it harder to switch, wondering could we also have backcompat config names for jscs switching, will make it easy to switch please?

Task: https://phabricator.wikimedia.org/T118941

**Comment by platinumazure** [comment]
@paladox Have you looked at [polyjuice](https://github.com/brenolf/polyjuice/) by any chance? It should help generate ESLint configurations from JSCS/JSHint. It's not perfect but it will get you 90% of the way there.

Once you're sure that your ESLint config matches your JSHint/JSCS configuration, you can run ESLint with the `--fix` option from the command line (or there should be an equivalent option in Grunt), and that should help fix most of the remaining lint errors.

By the way, ESLint is not yet fully compatible with JSCS/JSHint, so you may wish to look at your rule configuration and see if there are ESLint equivalents or not. If any of your JSCS rules do not have an ESLint equivalent, we recommend not upgrading at this time. You can track our progress using the [JSCS Compatibility Milestone](https://github.com/eslint/eslint/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22JSCS+Compatibility%22). We're working on documentation to aid in the switch from JSCS to ESLint, but that's not quite ready either.

If you have any further questions, feel free to stop in our [Gitter chat room](https://gitter.im/eslint/eslint).

**Comment by paladox** [comment]
@platinumazure hi, yes I used that to convert it but with jscs it didn't do a very good job only converting one or two configs. jshint did better but I doint know what was converted and what wasent due to different names in the configs between eslint and jscs.

**Comment by nzakas** [comment]
@paladox you're a bit early to try to automatically convert configs. We are working on it, we just aren't finished yet. We did start a migration guide that we are adding to as we complete more work that might be of use: http://eslint.org/docs/user-guide/migrating-from-jscs

Unfortunately, we can't support JSCS rule names, but we are doing our best to make migrating to ESLint easier.

**Comment by paladox** [comment]
Oh ok thanks.

**Comment by kaicataldo** [comment]
Going to close this, since it looks like the question has been answered. Please feel free to stop by the [Gitter chat](https://gitter.im/eslint/eslint) with questions if you need help!

**Comment by paladox** [comment]
Ok thanks.
