### ISSUE TITLE
Add a --fix option for wrap-regex

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7013]
I'm using Node v6.4.0 and ESLint v3.4.0.

It would be useful to have an autofix option for the `wrap-regex` rule. The fixer would simply wrap all regular expression literals with parentheses, if they aren't parenthesized already.

```js
var hasFoo = /foo/.test(myStr);

// gets fixed to:

var hasFoo = (/foo/).test(myStr);
```

We would need to ensure that adding parentheses doesn't cause the regex to be interpreted as a function parameter (like with `no-unexpected-multiline`). However, I don't think this is an issue, because in scenarios like this, the regex is parsed as a division operator anyway:

```js
var unrelated = 'foo' // <-- no semicolon
/regex/.test('bar');

// This is a SyntaxError even before parentheses are added,
// because `/` is parsed as a division operator.
```
---

I would be willing to add this if the issue is accepted.

**Comment by platinumazure** [comment]
Seems reasonable to me. :+1:

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
:+1:

**Comment by mysticatea** [comment]
I will go to a champion.
Then, there are 3 :+1:s from the team.
