### ISSUE TITLE
no-unused-require

### ISSUE THREAD

**Issue by dfcreative** [eslint/eslint#7018]
Hi!

We are trying to setup [eslint for audiojs](https://github.com/audiojs/contributing/issues/19), allowing really loose code requirements, and we need to force _no unused `require`_, because each _require_ call blows browserify bundle. But `no-unused-vars` is too strict for us and it is anyways resolved by any minifier, but may annoy during development.

Is there `no-unused-require` rule/plugin, and if there is no such, is there a sense to add this rule?

Thanks.

**Comment by platinumazure** [comment]
You can look at https://github.com/cvisco/eslint-plugin-requirejs. I'm not sure if they've implemented such a rule yet- I know there has been discussion on it in the past.

**Comment by dfcreative** [comment]
@platinumazure thank you for the reference! I forgot to specify - `require` for nodejs/commonjs/browserify.

**Comment by platinumazure** [comment]
In that case, I would suggest searching for "eslint plugin commonjs" and
similar terms on GitHub and NPM. Hopefully there's something out there for
you.

**Comment by platinumazure** [comment]
Oh, wait, I might have misunderstood. Are you trying to avoid `require()` calls altogether? If so, try using `no-restricted-globals`, you should be able to specify `require` on that list.

**Comment by dfcreative** [comment]
You got it right the fisrt time, I just guess there is no unused only global vars checker, at least I did not find one.

**Comment by vitorbal** [comment]
I quickly tried to find a "plugin-eslint-commonjs" or the like but couldn't.
I think your best bet would be to write a custom rule. You can pretty much base it out of the `collectUnusedVariables` function that is implemented in the `unused-vars` rule and run a check only for `require()` calls. 

Please drop by the [gitter chatroom](https://gitter.im/eslint/eslint) if you have any questions, we would be happy to help out!

**Comment by vitorbal** [comment]
Closing this, as I believe my previous comment is an acceptable solution. Please re-open if anyone disagrees!
