### ISSUE TITLE
eslintbot should not double-comment "LGTM" on PRs

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#7046]
Essentially, after eslintbot has commented "LGTM" on a PR, if I rebase and re-force-push, it comments "LGTM" again. This doesn't really seem to serve a purpose except to trigger redundant email notifications.

It would be nice if eslintbot deduped - essentially, if the comment it's about to make is identical to the latest comment it's left, it refrained from commenting.

Thoughts?

**Comment by nzakas** [comment]
This is working as designed. We need the bot to run each time a PR is updated to make sure no problems have been introduced. We used to only run it the first time, but we ran into situations where a PR was okay and then a problem was introduced, and of course, vice versa. 

I know it's a bit annoying, but it's a small price to pay to verify the PR and to know that the bot actually ran again (if there's no comment, we know there's a problem with the bot).

**Comment by ljharb** [comment]
I totally get that the bot should run every time - it just seems unnecessary to post a comment when the status hasn't changed. It could, for example, update its previous LGTM with the new sha that it's marking, or any number of other things that wouldn't generate an email.

**Comment by ljharb** [comment]
Another alternative is that you could use a required Github status check instead of a comment bot, which would enforce things more strongly, with an always-visible status, without any comment noise whatsoever (in the case of a LGTM).

**Comment by platinumazure** [comment]
I'd be interested to see if it could be implemented as a status check, but am not strongly opposed to the current behavior.

**Comment by kaicataldo** [comment]
I'd support looking into making it a status check that marks as good or marks as not good and comments on the cause of the failure.

**Comment by nzakas** [comment]
Changing to a status check would require a rewrite of the bot (which is used on all of our repos, not just this one). Right now it's very generic in that it just outputs stuff in relation to a PR. Making such a change is a bunch of work and I just don't see enough value to prioritize this over other things we have on our plate.

**Comment by kaicataldo** [comment]
Sounds like no one is really opposed to this but, given other priorities, it probably wouldn't happen in the near future.

**Comment by not-an-aardvark** [comment]
Another short-term option would be to just run `npm run check-commit` in CI. eslintbot would keep doing what it normally does for incorrect commit messages (it would leave a comment explaining how to fix them), but there would be no need to comment "LGTM" for correct commit messages because the build would fail if the commit message was incorrect.

**Comment by nzakas** [comment]
@not-an-aardvark we moved away from that because it blurs the line between a CI test failure (most likely a unit test or linting) vs. a commit format issue (that might be able to be fixed upon merging).

**Comment by ljharb** [comment]
Can test and lint failures not possibly be fixed on merging?

**Comment by nzakas** [comment]
@ljharb that would require merging the code and then someone manually fixing it, which doesn't scale. With commit message formatting, we can just change it right in the UI.

**Comment by ljharb** [comment]
ah, i was assuming you were talking about merging from the command line, where you can change all those things.

**Comment by nzakas** [comment]
After discussing with the team, we do recognize that there's a bit of annoyance with the multiple "LGTM"s on pull requests. However, the amount of work it would take to do something more optimal is pretty high (it would require rewriting the bot), and given that this is a minor annoyance and our current solution is flexible enough to use in all of our repos, we aren't going to investigate this any further. We'd rather focus our attention on improving ESLint itself.
