### ISSUE TITLE
Implement autofix for no-implicit-coercion

### ISSUE THREAD

**Issue by TheSavior** [eslint/eslint#7056]
**What version of ESLint are you using?**
3.0.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
Seems unnecessary

**What did you do? Please include the actual source code causing the issue.**
I tried to use the --fix command with 

```
"no-implicit-coercion": 2
```

**What did you expect to happen?**
I expected it to fix my source

**What actually happened? Please include the actual, raw output from ESLint.**
It gave me explicit recommendations on what to write in my code, but didn't make the actual changes.

**Comment by platinumazure** [comment]
Just for the convenience of anyone perusing the issue, could you show the messages you receive so we can see exactly what fixes you have in mind?

**Comment by TheSavior** [comment]
Yeah, I plan on digging into this. I updated the current tests with example fixes:

https://github.com/TheSavior/eslint/blob/fix-conversion/tests/lib/rules/no-implicit-coercion.js#L80

**Comment by TheSavior** [comment]
Essentially, this rule right now reports exactly what to replace each node with. I recommend that when using the fix option, it just does that exact change.

**Comment by kaicataldo** [comment]
:+1: from me. Given that we already calculate the replacement for the error message, should be pretty straight forward!

**Comment by vitorbal** [comment]
👍 from me as well

**Comment by ilyavolodin** [comment]
👍  Just need somebody to champion this now.

**Comment by platinumazure** [comment]
I'll champion.
