### ISSUE TITLE
Bad file extenstions matching.

### ISSUE THREAD

**Issue by smmoosavi** [eslint/eslint#7059]
```
./node_modules/.bin/eslint src/** --ext .js

/myproject/src/index.ejs
  1:2  error  Parsing error: Unexpected token !

✖ 1 problem (1 error, 0 warnings)

```
**What version of ESLint are you using?**

v3.4.0

**What did you expect to happen?**

`--ext .js` should not match `index.ejs` file.

**What actually happened? Please include the actual, raw output from ESLint.**

file `index.ejs` was matched and caused error.

**Comment by platinumazure** [comment]
When you use a glob pattern (instead of a directory), the `--ext` CLI flag is basically ignored.

You have two options here:

* Your glob pattern could be more specific: `src/**/*.js`
* You can use a path and `--ext`: `./node_modules/.bin/eslint src --ext .js`

**Comment by smmoosavi** [comment]
Thank.
your suggestion solved the problem.
