### ISSUE TITLE
Documentation bug: missing Reflect.apply() argument in examples

### ISSUE THREAD

**Issue by mgedmin** [eslint/eslint#7069]
**What version of ESLint are you using?**

Not applicable.

**What parser (default, Babel-ESLint, etc.) are you using?**

Not applicable.

**Please show your full configuration:**

Not applicable.

**What did you do? Please include the actual source code causing the issue.**

Read the page at http://eslint.org/docs/rules/prefer-reflect

**What did you expect to happen?**

I expected the documentation examples of correct code to be correct, i.e. the first argument of Reflect.apply() to be a function.

**What actually happened? Please include the actual, raw output from ESLint.**

The first argument of Reflect.apply() is `null` or `undefined` in some of the examples:

![ekrano nuotrauka is 2016-09-07 12-45-02](https://cloud.githubusercontent.com/assets/159967/18307389/ec7dc6ba-74f8-11e6-8ebe-e7126d9f9d7b.png)

See also #7068.

**Comment by sstern6** [comment]
@vitorbal I can have a PR open for this today, should we simply remove the bad examples or replace the bad examples with new `correct` ones?

Thanks

**Comment by vitorbal** [comment]
@sstern6 I think we should replace them with correct ones!

**Comment by sstern6** [comment]
@vitorbal will have it up for review this afternoon.

Thanks

**Comment by sstern6** [comment]
@vitorbal PR open and ready for review.  Let me know if you need anything else.

Thanks
