### ISSUE TITLE
Add an autofixer for no-floating-decimal

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7070]
I'm using Node v6.5.0 and ESLint v3.4.0.

It would be useful to have an autofix option for the [`no-floating-decimal`](http://eslint.org/docs/rules/no-floating-decimal) rule. This would add a `0` before or after the decimal point in order to fix errors.

```js
var foo = .5;
var bar = 2.;
var baz = -.7;

// gets fixed to:

var foo = 0.5;
var bar = 2.0;
var baz = -0.7;
```

I would be willing to add this if the issue is accepted.

**Comment by platinumazure** [comment]
:+1:, sounds good to me.

**Comment by mysticatea** [comment]
:+1:

**Comment by ilyavolodin** [comment]
👍
