### ISSUE TITLE
Docs: Explain why `{}.hasOwnProperty.call` is recommended 

### ISSUE THREAD

**Issue by dallonf** [eslint/eslint#7071]
A coworker just cleaned up a bunch of lint errors in the project, and left this headscratcher in the codebase:

```js
for(let key in obj) {
      if ({}.hasOwnProperty.call(obj, key)) {
          // ...
      }
}
```

When asked what was going on here and why not just use `obj.hasOwnProperty(key)` or even `Object.prototype.hasOwnProperty.call(obj, key)`, he pointed to the docs for [guard-for-in](http://eslint.org/docs/rules/guard-for-in), which, sure enough, recommends this pattern as a solution.

I dug through the history of the docs page, assuming to maybe find it as part of a commit that expanded the detection capabilities of the rule (and the docs would demonstrate just how crazy you could write the call and still satisfy the rule), but it turns out it is in fact recommended as a "best practice": https://github.com/eslint/eslint/commit/551335eedf62261299af7aafdfc896b3aef8de67

I'd recommend the docs page for this rule be amended to explain exactly why this sort of gymnastics is demonstrated over a simpler approach. Is it meant to avoid an edge case where `hasOwnProperty` is defined and thus overridden higher in the prototype chain?

**Comment by not-an-aardvark** [comment]
To answer your question, `Object.prototype.hasOwnProperty.call` is generally used for two reasons:

1. `hasOwnProperty` is defined on the object as something else, as you mentioned:

  ```js
  var someObject = {foo: 'bar', hasOwnProperty: 5};
  someObject.hasOwnProperty('foo') // throws a TypeError
  ```

1. The object in question is being used as a map and doesn't inherit from `Object.prototype`, so it doesn't have `hasOwnProperty`:

  ```js
  var someObject = Object.create(null);
  someObject.hasOwnProperty('foo'); // throws a TypeError
  ```

See also: [`no-prototype-builtins`](http://eslint.org/docs/rules/no-prototype-builtins)

**Comment by mysticatea** [comment]
In addition, considering "[querystring](https://nodejs.org/api/querystring.html)" package in Node.js 6.

```js
const qs = require("querystring")
const obj = qs.parse("a=1&b=2")

obj.hasOwnProperty("a")  // → TypeError: obj.hasOwnProperty is not a function
```

Like this, library might return an object which is created by `Object.create(null)`.

**Comment by vitorbal** [comment]
I think `no-prototype-builtins` could be mentioned in the "Related Rules" section of `guard-for-in`, to clarify this a bit. @dallonf would you be willing to cook up a PR for that?

**Comment by ljharb** [comment]
(fwiw, this is why the Airbnb style guide and virtually every "best practice" i've seen discourages use of `for..in` - `Object.keys(obj).forEach` does not have this problem)

**Comment by dallonf** [comment]
Thanks for the explanation! I'll see if I can cook up a PR.
