### ISSUE TITLE
Docs: Reflect.getOwnPropertyNames does not exist

### ISSUE THREAD

**Issue by dwhieb** [eslint/eslint#7075]
In the [documentation](https://github.com/eslint/eslint/blob/master/docs/rules/prefer-reflect.md#reflectgetownpropertynames) and [source code](https://github.com/eslint/eslint/blob/master/docs/rules/prefer-reflect.md#reflectgetownpropertynames) for the `prefer-reflect` rule, the user is instructed to use `Reflect.getOwnPropertyNames` in place of `Object.getOwnPropertyNames`. However, `Reflect.getOwnPropertyNames` doesn't actually exist. The closest corresponding Reflect method is `Reflect.ownKeys`, although this isn't quite the same because it also includes Symbol properties.

**Comment by dwhieb** [comment]
Btw, I'm happy to make a PR for this if you'd like it addressed.

**Comment by ilyavolodin** [comment]
That's correct. Spec doesn't include `getOwnPropertyNames` (http://www.ecma-international.org/ecma-262/6.0/#sec-reflect-object). Thanks for finding this, @dwhieb

**Comment by ilyavolodin** [comment]
@ljharb Those two deal with arguments passed into `Reflect.apply`, so I don't think they are related to this issue.

**Comment by ljharb** [comment]
Oops, you're right. I was thinking of #7119.

**Comment by dwhieb** [comment]
Yeah, I'm working on getting #7119 in shape for merging to address this issue.

**Comment by dwhieb** [comment]
The PR should be all set:
#7119 

As I noted in the comments there, I had some troubles getting my CLA recognized and the commit summary validated, but I think both are okay. The CLA is signed, but one of my commits had GitHub's anonymized email, so the check didn't like it. The other commits have my actual email. The commit summary also couldn't be validated, but as far as I can tell it's formatted correctly. Let me know if there's anything else I can do.

**Comment by platinumazure** [comment]
If you can fetch the entire remote branch (including the first commit), you could squash the commits and force-push back to github. Presumably the squashed commit should have the right author info. Let me know if that doesn't work or if you need help (also feel free to stop by our Gitter chat, https://gitter.im/eslint/eslint).

**Comment by kaicataldo** [comment]
I'm closing this because the team has decided to deprecate the `prefer-reflect` rule (see discussion here: #7226). @dwhieb Thanks for creating the issue and being willing to do the work!
