### ISSUE TITLE
`class-methods-use-this`: "exceptMethods" array option

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#7085]
**What version are you using?**
3.4.0

**What did you do?**
Enabled `class-methods-use-this` and ran it on this code:
```js
import React from 'react';

class Foo extends React.Component {
  componentDidMount() {
    doSomethingHereWithLogging();
  }
}
```

**What happened?**
`Expected 'this' to be used by class method 'componentDidMount'`

**What did you expect to happen?**
What I would *like* to happen is to be able to specify "componentDidMount", and all the other React lifecycle methods, as exceptions to this rule. In other words, the typical reasoning for a class method is that it needs access to `this` - but in the case of React components, the lifecycle methods provide context-based hooks that don't necessarily require `this`. A generic "exceptMethods" array would allow me to manually specify component lifecycle methods, and exempt them from this rule, without losing its general utility.

**Comment by platinumazure** [comment]
What happens if you make that method static? Does React fail to work with it in that case?

**Comment by ljharb** [comment]
Correct - React requires it to be an instance method.

This will likely come up with other frameworks as well, which is why I think a generic escape hatch is a good idea.

**Comment by platinumazure** [comment]
Agreed-- to me the spirit of the rule is, when you're designing a class and you fully control the contract, you should use static unless the class method actually uses `this`. When you have to conform to a different contract, the rule is not as useful here.

If you can provide a suggested schema and example of correct/incorrect code, just so we have a proper proposal, I can endorse that.

**Comment by ljharb** [comment]
Essentially: `"class-methods-use-this": [2, { "exceptMethods": ["componentDidMount"] }]`, where "exceptMethods" defaulted to `[]` and was always concatenated to `["constructor"]` (ie, the default behavior).

Good code with the option:
```js
class Foo extends React.Component {
  componentDidMount() {
    doSomethingHereWithLogging();
  }
}
```

Bad code without the option, or with an empty array:
```js
class Foo extends React.Component {
  componentDidMount() { // warning here
    doSomethingHereWithLogging();
  }
}

class Bar extends React.Component {
  componentDidMount() { // warning here
    doSomethingHereWithLogging();
  }

  foo() { // warning here
    return 3;
  }
}
```

Bad code with the option:
```js
class Foo extends React.Component {
  componentDidMount() {
    doSomethingHereWithLogging();
  }

  foo() { // warning here
    return 3;
  }
}
```

**Comment by platinumazure** [comment]
:+1: from me.

**Comment by ljharb** [comment]
I've put up #7120, even though this is not yet accepted, since it seemed simple enough.

**Comment by btmills** [comment]
:hand: I'll champion, this is a good idea. One more :+1: from the team?

**Comment by gyandeeps** [comment]
I already gave it on the issue.
But here it is again 👍

**Comment by platinumazure** [comment]
@btmills @gyandeeps I count only two :+1:'s and champion (btmills champion, gyandeeps and platinumazure :+1:). Am I missing someone? Or should this not be accepted yet?

**Comment by btmills** [comment]
Could be I misunderstood the rules. Is it champion plus 3 :+1:, or can the champion count as one of the three :+1:?

**Comment by platinumazure** [comment]
My understanding is champion plus 3 :+1:s, maybe I have it wrong.

**Comment by platinumazure** [comment]
Never mind, found a buried :+1: by @vitorbal. We're good here, I'll review the PR now.

**Comment by vitorbal** [comment]
Sorry, if i have read this earlier I would've reiterated myself! But yeah, :+1: from me as well :)

**Comment by niksajanjic** [comment]
Hi, why are docs updated to support exceptions array for this rule:

http://eslint.org/docs/rules/class-methods-use-this

When latest release of eslint 3.5.0 doesn't yet support it. I see it's been merged 2 days ago and latest version was released 6 days ago so it's obvious it isn't supported, but then again that adds confusion so I just spent some time figuring out why it doesn't work assuming it is my fault.

**Comment by gyandeeps** [comment]
The docs doesnt show the exception array option. what am i missing?
I jus tried the link which you pasted

**Comment by gyandeeps** [comment]
I think now you just edited the link on your post:
this is the original link: http://eslint.org/docs/rules/class-methods-use-this

Thats what people should be looking at.

**Comment by niksajanjic** [comment]
Sorry, I pasted wrong link, but then again the link I edited afterwards isn't part of official eslint documentation so it is my fault. Sorry.

**Comment by mathieumg** [comment]
This might be handy as a starting point for React users leveraging this rule:

```js
"exceptMethods": [
  "componentDidMount",
  "componentDidUpdate",
  "componentWillMount",
  "componentWillReceiveProps",
  "componentWillUnmount",
  "componentWillUpdate",
  "render",
  "shouldComponentUpdate",
]
```

Depending on your codebase (if you use stateless components, if you don't have side-effects in your components, etc.) you probably only need a few of these, if any.

**Comment by ljharb** [comment]
There's a few more for React, that eslint- config-airbnb defines.

**Comment by mathieumg** [comment]
> There's a few more for React, that eslint- config-airbnb defines.

For reference, https://github.com/airbnb/javascript/blob/8468ed842314a5d66816927ba6c35f018035cffc/packages/eslint-config-airbnb/rules/react.js#L22-L33

I don't use external configurations, that's why posted my snippet. :) That being said, I forgot about context (not on the React lifecycle page since it's still technically not officially supported) and I use class properties that's why I didn't include `getInitialState` and `getDefaultProps`, I actually thought about it but figured it was only for the `createClass` approach, which is obviously not true, I've just grown so accustomed to class properties already. Thanks for pointing these out!
