### ISSUE TITLE
Question: Errors after timestamp

### ISSUE THREAD

**Issue by okcoker** [eslint/eslint#7106]
A lot of times throughout the evolution of an app, you'll want to change rules or introduce new plugins/rules etc. In order to encourage usage of the newly imposed rules, whether solo or on a team, it is sometimes impractical to fix all of the new warnings/errors that have appeared at once. I was thinking it might be useful to have some sort of functionality to throw an error for certain rules if it appears after X point in time. Maybe even force a warning on rules that are an error after X time in order to encourage clean up.

Is that dumb or nah?

**Comment by platinumazure** [comment]
I don't see this happening in core, but you can definitely write a Node app that uses our CLIEngine API to run the linter (after processing configuration files and everything), iterates through the lint messages to change some of them to warnings as needed, and then invoking your formatter of choice to spit out the results.

**Comment by ilyavolodin** [comment]
I agree. I don't think this should be in the core. I think you can probably do it by creating a custom formatter, instead of a whole new Node application. The only thing I don't remember is if you can change exit code from inside formatter (I don't think you can).

**Comment by okcoker** [comment]
Thanks guys. If all the tools are available to create this functionality then that would be a start. Changing the exit code would be important 😏

**Comment by platinumazure** [comment]
@okcoker I'm not sure about creating a new formatter due to the exit code issue, but CLIEngine definitely lets you have finer control over the whole process. Please stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need help with anything.

**Comment by okcoker** [comment]
@platinumazure Nope, we're good here. Thanks for listening.
