### ISSUE TITLE
`no-restricted-properties` is in the wrong category

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#7112]
https://github.com/eslint/eslint/blob/master/lib/rules/no-restricted-properties.js#L18 is in http://eslint.org/docs/rules/#nodejs-and-commonjs and I'm not sure why - this is a generic rule and has nothing to do with node and commonJS. It seems like "best practices" or "stylistic" is a better category for it?

**Comment by kaicataldo** [comment]
I agree! My vote is for "Best Practices":
>These rules relate to better ways of doing things to help you avoid problems

**Comment by kaicataldo** [comment]
Removing the bug label so it's clear this is a docs change. Sorry for the confusion!
