### ISSUE TITLE
Quotes rule docs has examples reversed for allowTemplateLiterals.

### ISSUE THREAD

**Issue by nruhe** [eslint/eslint#7115]
See [here](https://github.com/eslint/eslint/blob/master/docs/rules/quotes.md#allowtemplateliterals).

Double quotes example is listed for single quotes, and visa versa.

**Comment by kaicataldo** [comment]
Great catch! Thanks for the issue report :)

**Comment by zoeingram** [comment]
Hi, this is my first PR. I'll have it up in a day! Will let you know if I have any questions. Thank you :)

**Comment by platinumazure** [comment]
@zoeingram Welcome to ESLint! Good luck with your PR and feel free to post here or stop by our [chat room](https://gitter.im/eslint/eslint) if you have questions or need help. Thanks in advance for your contribution!

**Comment by zoeingram** [comment]
@platinumazure Thank you!  [PR is up](https://github.com/eslint/eslint/pull/7135) and ready for review :)
