### ISSUE TITLE
Prevent confusing if-statement usage

### ISSUE THREAD

**Issue by feross** [eslint/eslint#7116]
Is there a way to configure eslint to prevent confusing if-statements like the following?

``` js
if (condition) {
  // stuff
} if (anotherUnrelatedCondition) {
  // more
} 
```

This is confusing because at first glance it looks like the second `if` is an `else if`, but it's not.

I couldn't find a rule to enforce this. It seems that this could potentially be part of the [`keyword-spacing`](http://eslint.org/docs/rules/keyword-spacing) rule. Perhaps an option to require _newlines_, not just a space, before certain keywords.

But I'm not sure this is the right approach. Thoughts?

**Comment by btmills** [comment]
@feross how about `max-statements-per-line`?

```js
/* eslint max-statements-per-line: ["error", { "max": 1 }] */

if (condition) {
  // stuff
} if (anotherUnrelatedCondition) {
  // more
}
```

Just tried that in the demo and got a warning on the second `if`.

**Comment by platinumazure** [comment]
I'd be in support of a new rule. Conceptually it seems like the opposite of `no-lonely-if`, which checks for an else that has only an if in the block and requires the use of `else if`. This hypothetical new rule would say, if you're an if statement and not part of an else, it must be on a new line.

A more general rule that could cover this would be requiring a newline (not necessarily a blank line) before all control statements (where an else is considered part of the if control statement).

Just putting my two cents out-- I'm happy to go with team consensus whatever that might be.

**Comment by kaicataldo** [comment]
@feross does @btmills's suggestion work for your use case?

**Comment by feross** [comment]
Unfortunately, it doesn't work for us. It prevents things like:

```js
if (err) { t.fail(str) } else { t.pass(str) }
``

which is too restrictive.

**Comment by kaicataldo** [comment]
Looks like this proposal might be relevant: https://github.com/eslint/eslint/issues/5982#issuecomment-248302460

**Comment by vitorbal** [comment]
@feross could you let us know if the proposal in #5982 solves your needs? Since that issue is part of the JSCS milestone, it should get some attention from the team in the very near-future. Thanks!

**Comment by feross** [comment]
@vitorbal Looks similar, but I think that issue is about a rule that assumes that we want to enforce two newlines, like this:

```js
// Two newlines -- Allowed
if (condition) {
}

if (condition) {

}
```

```js
// One newline -- Disallowed
if (condition) {
}
if (condition) {

}
```

We are happy to allow BOTH of the above cases. We just want to disallow the following:

```js
// No newline -- Disallowed
if (condition) {

} if (condition) {

}
```

**Comment by vitorbal** [comment]
Thanks for clarifying, I think I understand your idea fully now. In that case padded-blocks would not work since that rule is supposed to deal with blank lines, not newlines per se.

Perhaps another solution would be a new option for `max-statements-per-line` that would allow `if-else` statements in the same line?

**Comment by dcousens** [comment]
Maybe `no-if-stalker`

**Comment by not-an-aardvark** [comment]
I think the [`newline-between-statements`](https://github.com/eslint/eslint/pull/8099) rule will solve this issue.

**Comment by not-an-aardvark** [comment]
Closing because this should now be solved by `padding-line-between-statements`.
