### ISSUE TITLE
Traverse into type annotations

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7129]
Currently, we are not traversing into type annotations for either Flow or TypeScript. This is because the nodes on which these properties exist (`Identifier`, `FunctionDeclaration`, etc.) are already defined with a set number of children inside of `escope`, and so it doesn't search for unknown properties. 

Now that we are doing more with type annotations, and the location of type annotation information is more or less [standardized for ESTree](https://github.com/estree/estree/blob/master/extensions/type-annotations.md). I think we should add traversing of these properties. This would basically be:
- `Identifier.typeAnnotation`
- `FunctionDeclaration.returnType`
- `FunctionExpression.returnType`
- `ArrowFunctionExpression.returnType`
- `MethodDefinition.returnType`

We can modify how `escope` traverses to include these extra properties.

**Breaking:** This is a breaking change because changing the traversal depth could have unintended side effects on core or custom rules.

**Comment by btmills** [comment]
In the 2016-09-15 TSC meeting, we decided to add traversals for [type annotations](https://github.com/estree/estree/blob/master/extensions/type-annotations.md) and [decorators](https://github.com/estree/estree/blob/master/experimental/decorators.md) in v4.0.

**Comment by nzakas** [comment]
Details: We can modify how escope traverses ASTs by modifying the `estraverse.VisitorKeys` object. `escope` uses that to determine where it should traverse for known nodes. This should be done in the `traverser.js` file like we used to do it in `eslint.js`: https://github.com/mysticatea/eslint/blob/6c3d7e424a75b0d70b6b84edc8f2b25aab1c315c/lib/eslint.js#L30-L38

**Comment by JamesHenry** [comment]
Is the idea that once the extra traversal is added, relevant core rules can be updated to take the type annotation nodes into account? Or will that still be the job of plugins?

**Comment by not-an-aardvark** [comment]
Should this issue be handled in eslint, or in eslint-scope?

**Comment by ilyavolodin** [comment]
If I understand this correctly, it should be handled in ESLint by passing `VisitorKeys` to `eslint-scope` (or rather `estraverse` which will later pass it to `eslint-scope`).

**Comment by kaicataldo** [comment]
I can work on this - I'd like to learn more about how this works!

**Comment by nzakas** [comment]
Yeah, the idea is to modify estraverse.VisitorKeys directly. That is depended upon by esrecurse, estraverse, and escope, so the change is made everywhere simultaneously. We used to do this in lib/eslint.js, so if you look through the git history, you should find an example.

**Comment by corbinu** [comment]
Would just like to comment that https://github.com/eslint/eslint-scope/pull/25 would solve this issue. It seems the feeling is that it would be better to pull the traverser into eslint rather than eslint-scope though.

https://github.com/corbinu/eslint-scope/blob/08121aed951b061456efc93f65f07a02135c94ad/lib/traverser.js

**Comment by soda0289** [comment]
@nzakas @kaicataldo Not sure if any work has been done on this but I was able to get escope to add references for type annotations. 
https://github.com/eslint/eslint-scope/pull/26 (This solution is made for typescript but can be improved to support Flow Type)

It is not as simple as updating the Visitor Keys. I think updating Visitor Keys will allow for estraverse to enter type annotations, which will allow rules to be made for them. I need to test this again to confirm.

Esrecurse will try and find a handler function in the Visitor class and if found will not traverse it's children.
https://github.com/estools/esrecurse/blob/master/esrecurse.js#L121-L123 

I was thinking of doing the same for decorators as this will solve some long standing issues with typescript-eslint-parser and the no-unused-vars eslint rule.

**Comment by ilyavolodin** [comment]
@kaicataldo Any chance you can take a look at this before Friday?

**Comment by kaicataldo** [comment]
I'm planning to look at it tomorrow! Sorry for the delay, was hoping to get to it sooner.

**Comment by kaicataldo** [comment]
That being said, I won't be at all offended if someone gets this done before I do - I know we need to get this out ASAP.

**Comment by kaicataldo** [comment]
Working on this now - will have aPR up in a little bit

**Comment by kaicataldo** [comment]
PR up!
