### ISSUE TITLE
`eol-last`: Issues should be reported in last column, not the first

### ISSUE THREAD

**Issue by kdex** [eslint/eslint#7136]
Currently, `eol-last` always reports linting issues [in column 1](https://github.com/eslint/eslint/blob/master/lib/rules/eol-last.js#L42).

Earlier today, @kaicataldo and I had a [discussion about this](https://github.com/eslint/eslint/pull/6952#issuecomment-246533858) and thought that semantically, it would make more sense to report issues at: *last line, last column* (as opposed to: *last line, first column*), since the last EOL in a file is also the last character of a line.

One might argue that the last EOL is a newline, so we could theoretically also report the issue in column `0`, but in line `lines + 1`. For users, the latter approach might be unexpected and have bad editor integration.

What do you think?

**Comment by vitorbal** [comment]
I think lines + 1 could create unexpected behavior as you mentioned, so "last line, last column" sounds good to me.
Not sure if this should be considered an enhancement or a bug fix, though.

**Comment by platinumazure** [comment]
:+1: for last line, last column. My vote is bug fix, because report count won't change and reports are currently wrong.

**Comment by vitorbal** [comment]
@platinumazure good point, agreed!
