### ISSUE TITLE
Updated process for evaluating rule proposals

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7156]
Right now, we have a process where we need one champion and three :+1:s to accept new rule proposals or new rule option proposals. However, with our issues getting a lot more traffic, it's becoming harder to easily see when one of these proposals has reached the necessary consensus. People add :+1: comments in addition to questions, and so we spend a lot of time scrolling up to find other :+1:s. As such, I'd like to propose a few simple changes to how we manage these issues and pull requests:

1. If you are championing the change, in addition to the comment, assign the issue to yourself.
2. If you are :+1:ing the change, leave that :+1: on the *original issue description* rather than a comment. (You can leave a comment as well, but make sure to leave a reaction on the original issue description).

If we do this, then all of the information we need is right up at the top.

Thoughts? @eslint/eslint-team

**Comment by mikesherov** [comment]
:+1:

**Comment by michaelficarra** [comment]
Sounds good.

**Comment by nzakas** [comment]
Okay, looks like we're all in agreement. If anyone wants to volunteer to update the maintainer guide docs for this, I'd appreciate it.

**Comment by kaicataldo** [comment]
I can make a PR for this when I get back this weekend

**Comment by nzakas** [comment]
Thanks @kaicataldo!
