### ISSUE TITLE
Proposal: Require reviews for all pull requests

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7157]
Today, GitHub released its pull request reviews feature (see https://help.github.com/articles/about-pull-request-reviews/). This gives an explicit signal as to whether a reviewer believes the PR should be merged.

I'd like to propose that we start requiring reviews for all pull requests and that we [protect the master branch](https://help.github.com/articles/about-required-reviews-for-pull-requests/) from merging a pull request if there's no review. This will ensure we don't accidentally merge something that hasn't gone through a thorough review.

Thoughts?

**Comment by vitorbal** [comment]
Totally agree. This should also make it easier to go through open PR's and find the ones that are ready to be merged or not.

**Comment by ilyavolodin** [comment]
My only concern is critical fixes. There were a few times when release broke something major and I had to push critical fix and merge it right in. However, that's probably less then 1% of our PRs, so I'm not sure we should focus on edge-case here.

**Comment by nzakas** [comment]
Okay, looks like everyone is in favor of this, so I'm enabling the check on pull requests.

To summarize: make sure when you review a PR that you submit an official review that indicates comment, approved, or changes are required. PRs won't be able to be merged until there are approvals.

**Comment by nzakas** [comment]
Oops, for some reason I didn't see the comments until I refreshed the page.

@ilyavolodin for critical fixes, we probably want to get another set of eyes on it. 

...however, TSC members can merge without waiting for an approval if absolutely necessary. This is the default GitHub setting (admins can merge without approval).
