### ISSUE TITLE
V8 “Strong Mode” expiremental rules

### ISSUE THREAD

**Issue by calebmer** [eslint/eslint#7163]
Is there any interest in adding “strong mode” rules to eslint? For context, [Strong Mode is a V8](https://github.com/v8/v8/wiki/Experiments%20with%20Strengthening%20JavaScript#strong-mode) expirement to allow for better and more predictable JavaScript optimizations and has been implemented in the most recent version of V8. Such rules could be gleaned from the [Strong Mode Proposal](https://docs.google.com/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/view).

I realize not all rules can be implemented in eslint, and this may be a better suited problem for userland with plugins/configs. Just wanted to make sure this is on the eslint teams radar :+1:

**Comment by mysticatea** [comment]
Thank you for this issue.

As far as I know, V8 has removed the supports of strong mode already.

If there are general best practices, whether it's in strong mode or not, I think good if it's in core rules.

**Comment by nzakas** [comment]
Duplicate of https://github.com/eslint/eslint/issues/2240.

If you'd like to propose a single rule, we can evaluate it, but there's no way for us to evaluate "add strong mode rules."

**Comment by calebmer** [comment]
Sounds good 👍
