### ISSUE TITLE
'self' is already declared in the upper scope 

### ISSUE THREAD

**Issue by liuyanjie** [eslint/eslint#7208]
ESLint Version: 3.5.0
Node Version: 4.4.4
npm Version: 2.15.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Default Parser

**Please show your full configuration:**

This is the source code.

```js
/** eslint no-shadow: ["error", { "builtinGlobals": true, "builtinGlobals": true }] */
const self = this;
```
> tips: 'self' is already declared in the upper scope

https://github.com/eslint/eslint/blob/master/lib/rules/no-shadow.js#L160

```js
// shadowed.identifiers is 0
// (options.builtinGlobals && "writeable" in shadowed) is true
// shadowed.writeable is false, "writeable" in shadowed is true
// options.builtinGlobals is true ??? Cause
(shadowed.identifiers.length > 0 || (options.builtinGlobals && "writeable" in shadowed)
```

**Comment by ljharb** [comment]
`self` is a browser global. If your file is a script (not a module) and you have the browser env enabled, then you're shadowing it.

**Comment by liuyanjie** [comment]
Think you. This answer solved my problem.
