### ISSUE TITLE
Proposal: add a mechanism for rules to suppress others

### ISSUE THREAD

**Issue by jamestalmage** [eslint/eslint#7216]
Inspired by #3480

> The trouble we'll run into is how this overlaps with `no-extra-parens`. Even if we add such an option, if you're also using `no-extra-parens`, it will flag those parentheses as unnecessary. We've already run into trouble with this on a couple of other rules that use parentheses as the exception to the rule. Since rules can't know about each other's settings, this puts us in a tricky situation.
>   -- https://github.com/eslint/eslint/issues/3480#issuecomment-134322191
## 

> Qix, we don't have a mechanize to "check to see if this rule is enabled", and we don't want to couple rules among themselves, that would lead to unsustainable code. So, in short, no - rules cannot know anything about other rules.
>  -- https://github.com/eslint/eslint/issues/3480#issuecomment-190222864

It seems to me that some way for one rule to suppress another would be beneficial. 

Instead of adding a bunch of exceptions to `no-extra-parens`, what if context had a `suppressRule` method.

``` js
// no-nested-ternary rule:

if (isNestedTernary(node)) {
  if (isParenthesised(node)) {
    // we allow nested ternary if it is parenthesised
    // request exemption to the `no-extra-parens` rule for this special case 
    context.suppressRuleAtNode({
      node,
      rule: 'no-extra-parens'
    });
  } else {
     context.report(/* ... */)
  }
}
```

I think you could have a number of suppression methods:
- `suppressRuleAtNode` - as used above - suppresses only on that particular node.
-  `suppressRuleWithinNode` - suppresses for children of the node
- `suppressRuleForLine`
- `suppressRuleForLocationRange`

The issue with closing #3480 as won't fix in favor of someone implementing a third party rule, is that it necessitates the creation of **two** additional rules (alternates for both `no-nested-ternary`, and for `no-extra-parens`). Even if someone actually does that, it doesn't solve the React use case mentioned [here](https://github.com/eslint/eslint/issues/3480#issuecomment-189960121). 

Also, I feel that this pushes the responsibility for mitigating collisions to the right place in the code. External plugins will be able to manage their own collisions with the core rules without requiring users to completely disable useful rules.

 [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn) has a number of rules that essentially mirror core rules but add a few exceptions. If this proposal were implemented, many of those rules could be greatly simplified - eliminating the code copy-pasted from ESLint core, and only applying suppression where desired.

**Comment by platinumazure** [comment]
I'm not comfortable with this, because there will be a great temptation to use that functionality even in cases where the rules could be designed more intelligently to avoid those collisions in the first place. Maybe that would be okay in plugins, but I don't think we would want that temptation available for core rules.

Just my take on it-- perhaps others on the team can be convinced.

**Comment by jamestalmage** [comment]
> I'm not comfortable with this, because there will be a great temptation to use that functionality even in cases where the rules could be designed more intelligently to avoid those collisions in the first place.

It's not possible to anticipate all the valid exceptions to a rule, and trying to make rules "more intelligent" to accommodate all possible usage patterns inevitably leads to bloat. In the case of #3480 you have a rule where pretty much everybody agreed it was a good exception, but that it wasn't worth bloating the `no-extra-parens` rule to accommodate. Also, doing so correctly would have meant asking the system about the config for the `no-nested-ternary` rule (something that isn't supported, and with good reason).

>  Maybe that would be okay in plugins, but I don't think we would want that temptation available for core rules.

I'm not sure why you wouldn't use the feature in core once it was available, but whatever. I'd be happy if it was available to my plugins regardless. If you are suggesting that plugins not be allowed to disable core rules, then I definitely disagree (not worth doing in that case).

**Comment by platinumazure** [comment]
I was focusing more on the maintainability of the ESLint core repository in my previous comment. If we hypothetically implemented such a feature against my reservations, I wouldn't care what plugins did with it, including disabling core rules. Sorry if I wasn't clear.

**Comment by sindresorhus** [comment]
This feature would be very value for plugin developers.

-

> but I don't think we would want that temptation available for core rules.

Then create a guideline that core rules should not use it. You control ESLint. You can choose not to use it.

**Comment by ilyavolodin** [comment]
Technical issue with this proposal is that it assumes that plugin rule will run first, before the core rule that it's suppressing. Problem is, we don't really control order of execution of the rules. There is never a guarantee on which rule will execute first. While I do not oppose exposing something that would make it easier for third-party rules to change the behavior of built-in rules, I don't think this proposal is going to work.

**Comment by platinumazure** [comment]
If disable logic were refactored (see #6592), we could probably piggyback on that for actually handling the rule suppressions. But that doesn't solve the issue of rule order.

I wonder if metadata could be used to indicate rule "dependencies", and then we could create a DAG and do a topological sort before iterating through rules' event handlers? Right now, we probably just iterate through the rules alphabetically or something equally arbitrary.

**Comment by nzakas** [comment]
:-1: The whole architecture is built on the idea that rules cannot and should not affect each other. We absolutely do not want rules depending on other rules, or rules being able to manipulate how other rules act. Rules are made to be completely independent, allowing us to easy mix and max, add and remove, and change the order in which they are applied whenever we want. 

Part of what has made ESLint easy for people to work with is that we have these strict boundaries around what parts of code are allowed to do which things. I'm very much against any change to that.

**Comment by jamestalmage** [comment]
> The whole architecture is built on the idea that rules cannot and should not affect each other

That is an admirable design goal, but think my proposal solves real world problems while breaking encapsulation in the most minimal way. 

ESLint, by its very nature and the size of its ecosystem, was bound to create these types of conflicts. A rigid stance that insists users "ask the rule author to make an exception for you" is simply not realistic. Should the `no-nested-parens` author really need to consider the JSX exception [as described here](https://github.com/eslint/eslint/issues/3480#issuecomment-189960121)? I don't think so. The exception to that rule should be maintained by whomever maintains the JSX related rules library. The only other alternative is for the JSX people to copy the `no-nested-parens` rule and modify it. But in addition to violating DRY, that necessitates users knowing about and installing the alternative rule, and manually disabling the original one.

I would ask you to reconsider the original proposal in detail. The proposed API was (I believe), a solution to the problem that addresses your concerns in the best way possible. The only allowed "manipulation of another rule" is that of suppression, and the proposed API for doing so is intentionally very restrictive; You must explicitly specify the node or line where a specific rule should be suppressed. Additionally, all you need to know about the rule to suppress is it's name (not how it is configured, if it will actually generate an error, or even if it is installed).

The only confusion I can foresee is when a user expects a rule to be violated, but is unaware it is being suppressed by another rule. I think this is easily mitigated by including suppressed rules in the report (`rule foo suppressed by rule bar at file:line:column`). Personally, I would like to see such reports hidden behind a `--verbose` or `--debug` flags to reduce noise, but I can see the argument for always showing it to reduce false bug reports.

In all sincerity, I believe this would make rules *easier* to maintain. As a maintainer of a few rules myself, I have encountered requests to hard code exceptions that seemed reasonable, but I wasn't entirely comfortable adopting the possible side effects and ongoing maintenance. The proposed API could allow powerful composition of what I will call "base rules", and rules that invoke exceptions to those rules by suppressing them. Indeed, a read through of [the docs](http://eslint.org/docs/rules/) for the first dozen rules reveals that (by far) the most common use of a config option is to allow for an exception to the rule.

**Comment by jamestalmage** [comment]
@ilyavolodin I am trying to understand the following:

> Technical issue with this proposal is that it assumes that plugin rule will run first, before the core rule that it's suppressing. Problem is, we don't really control order of execution of the rules. There is never a guarantee on which rule will execute first.

By my thinking, it wouldn't matter which went first. You would keep a separate list of "suppressions" (i.e. what rule was being suppressed at what node). Rules would be completely unaware they were being suppressed, and you wouldn't necessarily need to know they were before they ran. Before passing the list of violations on to the reporter, you would simply merge the list of violations and suppressions (deleting the violation, or marking it as suppressed whenever you found a matching suppression).

**Comment by nzakas** [comment]
I'm sorry, there's no support for this within the team and this issue is very far past our evaluation period for new features. While I understand your desires here, allowing rules to affect other rules runs counter to how rules were designed and introduces a level of opacity in rule relationships that I'm personally not comfortable with. 

Thanks for the suggestion and apologies for not resolving this sooner.
