### ISSUE TITLE
indent MemberExpression not working

### ISSUE THREAD

**Issue by marneborn** [eslint/eslint#7233]
**Tell us about your environment**

* **ESLint Version:**
2.13.1
* **Node Version:**
v6.5.0
* **npm Version:**
3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
none

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**
Created tmp.js with this example from [doc](http://eslint.org/docs/rules/indent#memberexpression)
```javascript
/*eslint indent: ["error", 2, { "MemberExpression": 1 }]*/

var foo = [];

foo
.bar
.baz();
```

Then ran:
```
node_modules/eslint/bin/eslint.js tmp.js
```

**What did you expect to happen?**
Error about lack of spaces before indents
**What actually happened? Please include the actual, raw output from ESLint.**

```
/Users/mikael/Work/lint/.eslintrc:
	Configuration for rule "indent" is invalid:
	Value "data["1"].MemberExpression" has additional properties.

Error: /Users/mikael/Work/lint/.eslintrc:
	Configuration for rule "indent" is invalid:
	Value "data["1"].MemberExpression" has additional properties.

    at validateRuleOptions (/Users/mikael/Work/lint/node_modules/eslint/lib/config/config-validator.js:119:15)
    at /Users/mikael/Work/lint/node_modules/eslint/lib/config/config-validator.js:166:13
    at Array.forEach (native)
    at Object.validate (/Users/mikael/Work/lint/node_modules/eslint/lib/config/config-validator.js:165:35)
    at Object.load (/Users/mikael/Work/lint/node_modules/eslint/lib/config/config-file.js:523:19)
    at loadConfig (/Users/mikael/Work/lint/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/mikael/Work/lint/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/mikael/Work/lint/node_modules/eslint/lib/config.js:227:22)
    at processText (/Users/mikael/Work/lint/node_modules/eslint/lib/cli-engine.js:223:27)
    at processFile (/Users/mikael/Work/lint/node_modules/eslint/lib/cli-engine.js:298:18)
```

Maybe because MemberExpression isn't defined in the schema for indent?

**Comment by not-an-aardvark** [comment]
The `MemberExpression` option was introduced in ESLint v3.2.1, and you're using ESLint v2.13.1.

Could you try upgrading to the latest version of ESLint, and see if the problem still happens?

**Comment by JonathanWolfe** [comment]
I'm on  `@latest` and see the same issue.

* **ESLint Version:** 3.6.1
* **Node Version:** 6.1.0
* **npm Version:** 3.8.6

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
```json
{
	"env": {
		"browser": true,
		"jquery": true
	},
	"extends": "airbnb-base",
	"globals": {
		"Polymer": true
	},
	"plugins": [ "html" ],
	"rules": {
		"array-bracket-spacing": [ "warn", "always" ],
		"computed-property-spacing": [ "warn", "always" ],
		"global-require": "off",
		"import/no-extraneous-dependencies": [ "error", { "devDependencies": true } ],
		"indent": [ "warn", "tab", { "SwitchCase": 1, "MemberExpression": 1 } ],
		"max-len": "off",
		"new-cap": [ "warn", { "capIsNewExceptionPattern": "Polymer" } ],
		"newline-before-return": "warn",
		"no-console": "off",
		"no-multiple-empty-lines": [ "warn", { "max": 1, "maxBOF": 0, "maxEOF": 1 } ],
		"no-param-reassign": "off",
		"no-tabs": "off",
		"padded-blocks": "off",
		"prefer-arrow-callback": "off",
		"radix": "off",
		"space-in-parens": [ "warn", "always" ],
		"id-length": [ "error", { "min": 2 } ],
		"lines-around-comment": [ "warn", { "afterBlockComment": true, "beforeLineComment": true, "allowBlockStart": true, "allowBlockEnd": true, "allowObjectStart": true, "allowObjectEnd": true, "allowArrayStart": true, "allowArrayEnd": true } ],
		"max-statements-per-line": [ "warn", { "max": 1 } ],
		"newline-after-var": [ "warn", "always" ],
		"newline-per-chained-call": [ "warn", { "ignoreChainWithDepth": 2 } ]
	}
}
```

**What did you do? Please include the actual source code causing the issue.**
```js
const folder = filePath
.split( /[\\|\/]/ )
.slice( 0, -1 )
.join( '/' );
```

**What did you expect to happen?**
A warning message about the missing indentation.

**What actually happened? Please include the actual, raw output from ESLint.**
No lint errors. Says everything is okay.

**Comment by not-an-aardvark** [comment]
I think this is intended behavior: the [docs](http://eslint.org/docs/rules/indent#memberexpression) mention that "Any indentation is permitted in variable declarations and assignments".

**Comment by vitorbal** [comment]
@JonathanWolfe as @not-an-aardvark mentioned, in your case the behavior is intended. If you disagree with that behavior, please open a new issue.

**Comment by vitorbal** [comment]
friendly ping @marneborn, were you able to verify if your issue is solved after upgrading your version of ESLint?

**Comment by marneborn** [comment]
Yes, the problem was with eslint 2.5, works in 3.1.

-mikael
