### ISSUE TITLE
Eslint for the browser

### ISSUE THREAD

**Issue by ShirH** [eslint/eslint#7238]
is there a version of eslint for use in web browser and ecma script 5?
Thanks,
Shir

**Comment by platinumazure** [comment]
Nothing officially supported. ESLint is primarily a Node app that uses the filesystem to do linting. Technically we've built a web version for our online demo, but it's not suitable for production use in browsers.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Comment by ShirH** [comment]
Hi, I'm trying to browserify the ESlint (latest version) and the problem that ES lint contain fs module and when I try to use it I got error, any idea how to overcome this ?
