### ISSUE TITLE
warning: flattenChildren(...)

### ISSUE THREAD

**Issue by valinaga** [eslint/eslint#7256]
I fresh install ignite and create new app. 
I run the app in ios.
Then click on the Component Example Screen i got this warning:

ExceptionsManager.js:78 Warning: flattenChildren(...): Encountered two children with the same key, `1:$Full Button`. Child keys must be unique; when two children share a key, only the first child will be used.
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by AllComponentsScreen)
    in RCTView (created by View)
    in View (created by AllComponentsScreen)
    in AllComponentsScreen (created by DefaultRenderer)
    in RCTView (created by View)
    in View (created by DefaultRenderer)
    in DefaultRenderer (created by SceneView)
    in SceneView (created by NavigationCard)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by NavigationCard)
    in NavigationCard (created by Container)
    in Container (created by NavigationComponent)
    in NavigationComponent (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in NavigationAnimatedView (created by NavigationComponent)
    in NavigationComponent (created by DefaultRenderer)
    in DefaultRenderer (created by NavigationDrawer)
    in RCTView (created by View)
    in View (created by Drawer)
    in RCTView (created by View)
    in View (created by Drawer)
    in Drawer (created by NavigationDrawer)
    in NavigationDrawer (created by Connect(NavigationDrawer))
    in Connect(NavigationDrawer) (created by DefaultRenderer)
    in RCTView (created by View)
    in View (created by DefaultRenderer)
    in DefaultRenderer (created by SceneView)
    in SceneView (created by NavigationCard)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by NavigationCard)
    in NavigationCard (created by Container)
    in Container (created by NavigationComponent)
    in NavigationComponent (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in NavigationAnimatedView (created by NavigationComponent)
    in NavigationComponent (created by DefaultRenderer)
    in DefaultRenderer (created by NavigationRootContainer)
    in NavigationRootContainer (created by Router)
    in Router (created by NavigationRouter)
    in NavigationRouter (created by RootContainer)
    in RCTView (created by View)
    in View (created by RootContainer)
    in RootContainer (created by Connect(RootContainer))
    in Connect(RootContainer) (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by mysticatea** [comment]
Thank you for this issue.

That warning seems to not related to ESLint.
I'm not sure what is it. I'm sorry.
