### ISSUE TITLE
no-implicit-coercion autofixer can change logic

### ISSUE THREAD

**Issue by meeber** [eslint/eslint#7272]
**Tell us about your environment**

* **ESLint Version:** 3.6.1
* **Node Version:** 6.7.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yaml
rules:
  no-implicit-coercion: error
```

**What did you do? Please include the actual source code causing the issue.**

Ran `eslint --fix` on:

```js
const catNoises = ["meow", "hiss", "purr"];

if (!~catNoises.indexOf("purr")) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

**What did you expect to happen?**

Expected ESLint to autofix the code to:

```js
const catNoises = ["meow", "hiss", "purr"];

if (catNoises.indexOf("purr") === -1) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

Or just report the problem without trying to autofix it.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint autofixed the code to:

```js
const catNoises = ["meow", "hiss", "purr"];

if (!catNoises.indexOf("purr") !== -1) {
  console.log("no purr");
} else {
  console.log("yes purr");
}
```

This autofix changes the logic of the code significantly.

**Comment by platinumazure** [comment]
I agree, in this case the tree structure has changed significantly: UnaryExpression > UnaryExpression becomes BinaryExpression > (UnaryExpression, Literal). Acceptable fix would be to surround the new BinaryExpression in parentheses, but I think it would be best not to fix if the expression is preceded by a unary operator.

**Comment by platinumazure** [comment]
Pinging @TheSavior: Any chance you could take a look at this?

**Comment by TheSavior** [comment]
Does this problem exist *only* when prefixed with a unary operator?

**Comment by not-an-aardvark** [comment]
No, it applies in cases like this as well:

```js
var foo = ~bar.indexOf(baz); // foo will be a number

// gets fixed to:

var foo = bar.indexOf(baz) !== -1; // foo will be a boolean
```

So I think the solution is to only fix the `~`/`indexOf` case if the expression is always going to be evaluated as a boolean (e.g. in an `if` or `while` test).

**Comment by meeber** [comment]
@not-an-aardvark makes a good point, although his example contains a concerning lack of animal noises.

On a similar note:

```js
if (~catNoises.indexOf("purr") === 0) { ... }

// gets fixed to:

if (catNoises.indexOf("purr") !== -1 === 0) { ... }
```

**Comment by TheSavior** [comment]
So it seems like it is only an issue of `~`. 

What if we always wrap the resulting indexOf check in parens if it is inserted into a larger expression?

**Comment by not-an-aardvark** [comment]
That would still cause some issues, because the fixer changes its type to a boolean instead of a number.

```js
var negativeFour = ~[foo, bar, baz, qux].indexOf(qux);
assert.strictEqual(negativeFour, -4); // assertion passes

// gets fixed to:

var negativeFour = [foo, bar, baz, qux].indexOf(qux) !== -1;
assert.strictEqual(negativeFour, -4); // assertion fails, `negativeFour` is now `true`
```

**Comment by TheSavior** [comment]
So perhaps the approach is that we just shouldn't autofix `~`

**Comment by meeber** [comment]
I think the following two statements are by far the most common use of `~` with `indexOf` and can both be safely autofixed:

```js
if (~a.indexOf(b))     // if (a.indexOf(b) !== -1)
if (!~a.indexOf(b))    // if (a.indexOf(b) === -1)
```

But any other variation seems risky to autofix, as the user might be doing something whacky that'll break as a result of autofixing. Is it reasonable to only autofix the above two cases, but warn on any other case? Or is the complexity and lack of consistency not worth the small value that autofixing provides? Seems like a toss-up to me. I know I wouldn't be heartbroken if it always warned instead of autofixed.

**Comment by nzakas** [comment]
Lets just not auto fix `~`.  Our policy is not to auto fix unless it can be done safely, and in this case we obviously can't. (Trying to detect methods that return numbers is a step beyond what we should be doing.)
