### ISSUE TITLE
Problem reading `\u{}` formatted unicode

### ISSUE THREAD

**Issue by SirSeim** [eslint/eslint#7278]
**Tell us about your environment**

* **ESLint Version:** v3.6.1
* **Node Version:** v4.5.0
* **npm Version:** 2.15.9

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
Within `package.json`

```
"scripts": {
    "test": "eslint *.js"
  },
  "devDependencies": {
    "eslint": "^3.6.1"
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "node": true
    },
    "extends": "eslint:recommended",
    "rules": {
      "no-extra-parens": 2,
      "curly": 2,
      "eqeqeq": 2,
      "no-eval": 2,
      "no-global-assign": 2,
      "no-lone-blocks": 2,
      "no-multi-spaces": 2,
      "no-return-assign": 2,
      "brace-style": [2, "1tbs", { "allowSingleLine": true }],
      "camelcase": [2, { "properties": "always" }],
      "func-style": [2, "expression"],
      "max-len": [2, 128],
      "no-tabs": 2,
      "operator-linebreak": [2, "after"],
      "no-console": 1,
      "no-unused-vars": 0,
      "semi": [2, "always"]
    }
  }
```

**What did you do? Please include the actual source code causing the issue.**

```js
var obj = {
    item: "\u{1f4a9}, \u{1f338}"
};
```

**What did you expect to happen?** No Errors

**What actually happened? Please include the actual, raw output from ESLint.**

```
/path/to/file/exercises.js
  2:11  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

More interestingly, doing
```js
var obj = {
    item: "\u1f4a9, \u1f338"
};
```
does not cause any problems. The use of the curly braces method of entering unicode causes ESLint to freak out.

**Comment by not-an-aardvark** [comment]
I think this is happening because curly braces with unicode are an ES6 feature, and ESLint only parses ES5 by default. You can enable ES6 parsing by adding `env: {es6: true}` to your config.

**Comment by SirSeim** [comment]
@not-an-aardvark, you are awesome!
