### ISSUE TITLE
no-unused-vars occurs even when variable is used in operator assignment

### ISSUE THREAD

**Issue by mlesk** [eslint/eslint#7286]
Environment 
-----------------------
ESLint Version: 3.6.1
Node Version: 4.1.0
npm Version: 3.10.8

parser : babel-eslint: 7.0.0

```
{
    "extends": [
      "airbnb-base",
      "plugin:flowtype/recommended"
    ],

     ////////// Parsing  //////////
    "parserOptions": {
      "parser": "babel-eslint",
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
          "jsx": true
      }
    },

    "plugins": [
      "flowtype"
    ],

    "rules": {
      ////////// Imports //////////
      "import/no-unresolved": [
        1,
        {
          "commonjs": true
        }
      ],
      "import/named": 1,
      "import/namespace": 1,
      "import/default": 1,
      "import/export": 1,
      "import/no-amd": 1,
      "import/no-duplicates": 1,
      "import/no-extraneous-dependencies": 1,
      "import/no-named-as-default": 1,
      "import/no-named-as-default-member": 1,

      ////////// Flow Type ////////////////
      "flowtype/generic-spacing": [1, "always"],

      ////////// Stylistic Issues //////////
      "semi": [1, "always"], // require or disallow use of semicolons instead of ASI
      "semi-spacing": [1, {"before": false, "after": true}], // enforce spacing before and after semicolons
      "no-extra-semi": 2
    }
}
```

Problem
---------------
use of variable with operator assignment results in a no-unused-vars warning

```js
let counter = 1;
function increment() {
  counter += 1;
}
increment();
```
I did not expect to receive a warning since the variable counter is used, but I received a no-unused-vars warning. 

'counter' is defined but never used.(no-unused-vars) 

If I switch it to 

```js
let counter = 1;
function increment() {
  counter = counter + 1;
}
increment();
```
I receive the error:

Assignment can be replaced with operator assignment. (operator-assignment)

**Comment by platinumazure** [comment]
As the lint error notes, `counter` is never actually used. You could remove the variable and all references to it and consuming code wouldn't know the difference.

What are you intending to do with `counter`? Finish implementing your program and the error should go away.

**Comment by mlesk** [comment]
You are correct. Thanks.

**Comment by adrianoresende** [comment]
But and this code? Result warning
```
let logoAnimateName = this.$el.querySelector('#headerLogo').style.animationName
...
logoAnimateName = 'fade-to-bottom'
```
What is solution?

**Comment by not-an-aardvark** [comment]
I think you meant to do this:

```js
const logoAnimateName = this.$el.querySelector('#headerLogo').style
style.animationName = 'fade-to-bottom'
```

As written, your code will not actually change the style, so the `logoAnimateName` variable isn't doing anything.
