### ISSUE TITLE
Automatic fix for yoda causes parsing error

### ISSUE THREAD

**Issue by Hirse** [eslint/eslint#7326]
**Tell us about your environment**

* **ESLint Version:** 3.7.1
* **Node Version:** 6.7.0
* **npm Version:** 3.7.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
eslint --fix --no-eslintrc --rule 'yoda: 2' test.js
```

**What did you do? Please include the actual source code causing the issue.**

```js
while (0 === (a)) {}

while (0 === (a = b)) {}
```

**What did you expect to happen?**

```js
while ((a) === 0) {}

while ((a = b) === 0) {}
```

**What actually happened? Please include the actual, raw output from ESLint.**

```js
while (a === (0) {}

while (a = b === (0) {}
```

**Comment by platinumazure** [comment]
Hi @Hirse, thanks so much for submitting this issue. This is an unfortunate bug and I hope we'll be able to resolve this soon!

Ping @not-an-aardvark-- I might have a chance to look at this today, but if you find time and want to look at this, let me know.

**Comment by not-an-aardvark** [comment]
Oops. I'll look at if now if you're not already looking at it.

**Comment by platinumazure** [comment]
Had to run a few errands, please feel free to investigate. Thanks!

**Comment by not-an-aardvark** [comment]
See #7326 for a fix.
