### ISSUE TITLE
`prefer-template` fixer should remove quotes that are uselessly escaped

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7330]
**What rule do you want to change?**

`prefer-template`

**Does this change cause the rule to produce more or fewer warnings?**

The same amount

**How will the change be implemented? (New option, new default behavior, etc.)?**

The change will modify the default behavior of the fixer for `prefer-template`.

**Please provide some example code that this change will affect:**

```js
const escapedQuote = "\"foo\"" + bar
```

**What does the rule currently do for this code?**

It fixes the code to:

```js
const escapedQuote = `\"foo\"${bar}`
```

**What will the rule do after it's changed?**

It should fix the code to:

```js
const escapedQuote = `"foo"${bar}`
```

This would be consistent with the `quotes` autofixer; it should clean up after itself and escape quotes that are no longer necessary.

**Comment by ilyavolodin** [comment]
Should this be handled by `prefer-template` or by `quotes` rule?

**Comment by not-an-aardvark** [comment]
I think it would be better handled by `prefer-template` (or if anything, `no-useless-escape`). `quotes` is only related in that it also handles escaping when it does fixes, but it doesn't actually check for uselessly-escaped quotes.
