### ISSUE TITLE
Proposal: Add exception option to `no-extra-parens` to allow parens around React components

### ISSUE THREAD

**Issue by Alaneor** [eslint/eslint#7350]
The rule `no-extra-parens` currently flags parens around React components spanning multiple lines:

```js
const component = (
  <div>
    <h1>Hello world</h1>
  </div>
)
```

However, [some believe](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md) that wrapping multiline React components is the preferred way to write them to increase readability.

### Proposal

Introduce a new exception option to this rule, `reactComponents` (or just `react` for brevity) which, when set to `false`, would not flag React components wrapped in parens as issues.

**ESLint**: 3.7.1
**Parser**: [babel-eslint](https://github.com/babel/babel-eslint)
**`no-extra-parens`** configuration:
```js
{ 'no-extra-parens': [1, 'all', {
    nestedBinaryExpressions: false
  }]
}
```

**Comment by platinumazure** [comment]
Hi @Alaneor, thanks for the issue!

We definitely can't make library-specific exceptions. We could possibly make an exception option for JSX or for multi-line expressions in general.

I'm fairly sure this is a duplicate of another issue, but I'm on a mobile device and can't search as easily. Just noting that this issue may be closed as a duplicate.

**Comment by Alaneor** [comment]
@platinumazure Thanks for the info! Of course the main issue is with the JSX syntax so naming the configuration option `jsxComponents` is totally fine with me.

I believe that having a `multiline` configuration option will work just as well for my use case and might actually be more helpful for the broader community since there might be more situations where such exception will be desired.

**Comment by platinumazure** [comment]
Here's the duplicate issue: #4229

That originally was closed with a JSX-specific commit, but I think we reverted it because we wanted to be more generic. Personally I like michaelficarra's idea of just allowing the parentheses in the case where `[no LineTerminator here]` appears in the spec (which includes return statements). So basically, if return is followed by open paren and then newline, then no-extra-parens wouldn't report.

I'm not sure what the status of this is since that issue is closed, so I'm going to leave this open until we know for sure if we want to reopen #4229.

**Comment by platinumazure** [comment]
Oh, wow, I'm dumb. Okay, the parentheses should be unnecessary because this isn't a return/throw/yield statement, so you should be able to just do this:

```js
const component =
  <div>
    <h1>Hello world</h1>
  </div>
```

**Comment by Alaneor** [comment]
@platinumazure Yup, that would work - writing the component like that does not cause `no-extra-parens` to complain.

The problem is, that our team's coding style guides prefer wrapping multiline JSX components in parens, for clarity. That, however, causes a conflict with the `no-extra-parens` rule. And that's why I would like to have a new option in `no-extra-parens` to allow JSX components wrapped in parens.

**Comment by platinumazure** [comment]
Referencing [your earlier post](https://github.com/eslint/eslint/issues/7350#issuecomment-253579666), just want to re-confirm that a `multiline` option would also work for you?

**Comment by Alaneor** [comment]
@platinumazure Yup, I believe it would be of help here. Although I must say I am not quite certain I would enjoy seeing code like this:

```js
if ((
  condition1 &&
  condition2
)) { /* ... */ }
```

I wonder if there's any use case for allowing parens around multiline, non-jsx expressions?

Perhaps it would really be better to add the `jsx` option as described [in the issue you linked](https://github.com/eslint/eslint/issues/4229#issuecomment-156748164)?

**Comment by ljharb** [comment]
This would be great, as it's blocking Airbnb's config from enabling `no-extra-parens` - precisely because our guide requires that multiline JSX be paren-wrapped.

However, it also *allows* single-line JSX to be paren-wrapped, which means `multiline` wouldn't suffice for our use case (@platinumazure)

**Comment by Alaneor** [comment]
Is there anything I can do to help this issue move forward? Looks like adding an exception for multiline `jsx` components would be a welcome addition by the community. Thanks!

**Comment by ljharb** [comment]
I'd like one option for multiline jsx, and *another* option for single-line jsx. Both should allow values "always", "never", or "ignore", so that parens can be required, forbidden, or permitted in each case.

**Comment by platinumazure** [comment]
I think I can get behind JSX options (including multi-line vs single-line). Can someone draft a proposal (see [Rule Change guidelines](http://eslint.org/docs/developer-guide/contributing/rule-changes)) and ping me when that's done so I can try to get the team to review?

**Comment by Alaneor** [comment]
I submitted the proposal as requested. See #7444 and let's continue the discussion there.
