### ISSUE TITLE
Unused var React JSX

### ISSUE THREAD

**Issue by f0rr0** [eslint/eslint#7355]
Why is `Main` unused?

<img width="619" alt="screen shot 2016-10-14 at 1 07 12 am" src="https://cloud.githubusercontent.com/assets/8574219/19364139/997f60ee-91aa-11e6-9027-0624d3cd999d.png">

`.eslintrc` :

```json5
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "rules": {
    "comma-dangle": 0,
    "import/extensions": 0,
    "new-cap": 0
  }
}
```

**Comment by kaicataldo** [comment]
Hey there, thanks for the issue. I believe you need to use https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md to have vars used in JSX marked correctly as used.

**Comment by f0rr0** [comment]
@kaicataldo right on, thanks!
