### ISSUE TITLE
Breaking: remove `source` property from individual eslint.verify messages

### ISSUE THREAD

**Issue by vitorbal** [eslint/eslint#7358]
This is a follow-up of #7098.

We should **remove the `source` property from individual linting error messages** that `eslint.verify()` outputs, in order to avoid duplicate information in the results.

For more information, please see [this comment](https://github.com/eslint/eslint/issues/7098#issuecomment-251242459).

This is a **breaking change**, and as agreed, we plan on introducing it only for 5.0.0. Justification:

> [...] as we're planning on having 4.0.0 before the end of the year, it's probably best to keep the source property for each individual message until 5.0.0, to give people time to adjust their formatters.

**Comment by vitorbal** [comment]
@nzakas marking this as accepted as we've already agreed on it in #7098. Hope that's okay!

**Comment by nzakas** [comment]
Yup!

**Comment by bdkjones** [comment]
I can adapt to this change, but I'm a little curious about why it was made. In what context is ESLint run by something that's unaware of the file that's being linted? In other words, why is it necessary to return the full text of the file in the linting result if the thing that called ESLint already knows the file and could, if desired, read it and then find the line(s) it wants to display for each error (if it wanted to display more than just the line where the error occurred)?

If there are such contexts, wouldn't the `filePath` property on the returned object provide a way to retrieve the entire contents of the linted file, should a formatter desire that?

The new approach is more memory-intensive and slightly less performant, as I now have to manually find and retrieve the line to display for each error once ESLint is done running.
