### ISSUE TITLE
Docs: Links to jslinterrors.com now go to an ads site

### ISSUE THREAD

**Issue by curiousdannii** [eslint/eslint#7368]
For example http://eslint.org/docs/rules/one-var links to http://jslinterrors.com/combine-this-with-the-previous-var-statement/

See: https://github.com/jamesallardice/jslint-error-explanations/issues/39

There [looks to be 17 pages with links to jslinterrors.com](https://github.com/eslint/eslint/search?utf8=%E2%9C%93&q=jslinterrors). I would've submitted a pull request removing the links, but I didn't know if there is somewhere else those pages can still be viewed? Perhaps they can be commented out until the domain is fixed or an alternative found?

See also https://github.com/eslint/eslint/pull/7342 where one of these links was just removed.

**Comment by kaicataldo** [comment]
Thanks for looking at this! Commented on the PR
