### ISSUE TITLE
The 'curly' rule fixer break 'brace-style' rule

### ISSUE THREAD

**Issue by onemen** [eslint/eslint#7374]
**Tell us about your environment**

* **ESLint Version:**
3.8.0
* **Node Version:**
6.8.1
* **npm Version:**
3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```
"brace-style": [2, "1tbs", {"allowSingleLine": true}],
"curly": [2, "all"],
```

**What did you do? Please include the actual source code causing the issue.**
```
if (foo)
  bar();
```

**What did you expect to happen?**
```
if (foo) {
  bar();
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
code 'fixed' to:
if (foo)
  {bar();}
```
Errors on line 2:
Opening curly brace does not appear on the same line as controlling statement
Statement inside of curly braces should be on next line
Closing curly brace should be on the same line as opening curly brace or on the line after the previous block

**Comment by not-an-aardvark** [comment]
Thanks for the report.

I don't think this is a bug; fixing an issue in one rule will occasionally cause a new problem to be reported for another rule.

This particular case will be solved when https://github.com/eslint/eslint/pull/7347 is merged, because then `brace-style` will be autofixable.

**Comment by onemen** [comment]
OK.
I will test tomorrow if #7347 will fix all the errors after 'curly' rule fixer

**Comment by not-an-aardvark** [comment]
I'm going to close this issue since I don't think this is a bug, but please feel free to continue the discussion.
