### ISSUE TITLE
[Rule Change] max-params: explicit constructor() value

### ISSUE THREAD

**Issue by apfelbox** [eslint/eslint#7392]
I would like to add an option to `max-params` to tread constructors differently.
### The version of ESLint you are using.

3.4.0
### The problem you want to solve.

Currently we can define a maximum number of parameters for a function with the `max-params` rule. It would be nice to define a option to the rule, to handle `constructor()` parameters differently than parameters to regular methods and functions.
### Your take on the correct solution to problem.

Add two options to the `max-params` rule :
`constructor` and `regular-function` (naming arbitrary). If only a single number is given (in the current 3.4.0 definition), both options use that as value.

**Comment by not-an-aardvark** [comment]
Thanks for the rule suggestion.

Out of interest, why do you want to have a different maximum for constructor functions versus other functions?

Also, by `constructor` functions, do you mean any function called `constructor` (e.g. in a class body)? Or do you mean any function that is instantiated?

**Comment by platinumazure** [comment]
Do we want to distinguish between functions and methods, as well?

**Comment by apfelbox** [comment]
@not-an-aardvark because a class `constructor` is normally only responsible for setting the dependencies of the class, not doing any actual work. So one could argue that a method with too many parameters does too much (SRP etc), but a core responsibility of the `constructor` is to receive and set the obligatory dependencies.

So one could be fine with a lot (like 4-6) constructor arguments, but not with a regular method with this many arguments.

(I know that too many dependencies in a class are a code smell - please don't let us have this discussion here 😉 )

I only use ES6 `class`es, so I can only speak about this use case. Not sure what to do with any other instantiated function.

**Comment by kaicataldo** [comment]
Closing this as discussion has stalled and it doesn't appear there is enough interest, either from the team or from the community, to continue the discussion at this time. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. Please feel free to open a new issue with a proposal to continue this discussion if this is something you would like to continue advocating for.
