### ISSUE TITLE
To-do list for 4.0.0

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7407]
There are a lot of issues where we have discussed changing behavior in the next major version, but we haven't really kept track of these. This issue is intended to be a place to put breaking changes that we are evaluating, so that we don't forget make those changes when the release happens.

---

Accepted changes:
- Core:
  - Fix scoped plugin names (https://github.com/eslint/eslint/issues/6362)
  - Calculate leading/trailing comments (https://github.com/eslint/eslint/issues/6724)
  - Fix `ignore-path` relative paths (https://github.com/eslint/eslint/issues/6759)
  - Traverse into type annotations (https://github.com/eslint/eslint/issues/7129)
- `eslint:recommended` changes:
  - (none yet)
- Other rule changes:
  - (none yet)

**Comment by not-an-aardvark** [comment]
Here are a few changes I think we should make:

* Rules to add to `eslint:recommended`:
  * [`array-callback-return`](http://eslint.org/docs/rules/array-callback-return)
  * [`no-useless-escape`](http://eslint.org/docs/rules/no-useless-escape)
  * [`no-template-curly-in-string`](http://eslint.org/docs/rules/no-template-curly-in-string)
  * [`no-unsafe-negation`](http://eslint.org/docs/rules/no-unsafe-negation)
  * [`no-shadow`](http://eslint.org/docs/rules/no-shadow)? (I think this is a good rule in general, but I'm worried about [#2645](https://github.com/eslint/eslint/issues/2645).)
  * [`no-loop-func`](http://eslint.org/docs/rules/no-loop-func)?
  * Remove [`no-negated-in-lhs`](http://eslint.org/docs/rules/no-negated-in-lhs) (deprecated)
  * Remove [`no-native-reassign`](http://eslint.org/docs/rules/no-native-reassign) (deprecated)
* Changes to rule defaults:
  * For [`indent`](http://eslint.org/docs/rules/indent), set `{MemberExpression: 1}` by default.
  * For [`valid-typeof`](http://eslint.org/docs/rules/valid-typeof), set `{requireStringLiterals: true}` by default.
  * For [`no-extra-parens`](http://eslint.org/docs/rules/no-extra-parens), set `{nestedBinaryExpressions: false}` by default (to avoid conflicting with [`no-mixed-operators`](http://eslint.org/docs/rules/no-mixed-operators))
  * For [`space-before-function-paren`](http://eslint.org/docs/rules/space-before-function-paren), set `{asyncArrow: "always"}` by default (it is currently `"ignore"` for backwards-compatibility, but it's inconsistent with the other options).
* Other:
  * Hopefully get the [`indent`](http://eslint.org/docs/rules/indent) rewrite in (meta-issue: https://github.com/eslint/eslint/issues/7274). The `indent` rewrite currently checks a lot of indentation cases that the current rule ignores. I think this is a good thing (ideally, no cases would be ignored by default), but it's possible it will cause a lot of builds to fail. We should make sure to put it in 4.0.0 if it's not already in by then.

**Comment by kaicataldo** [comment]
I'm hoping that the [comment attachment changes](https://github.com/eslint/eslint/issues/6724) also get in

**Comment by not-an-aardvark** [comment]
As discussed in https://github.com/eslint/eslint/pull/7689, we should consider reporting an error for for `ObjectExpression` and `ArrayExpression` errors/rejection reasons in `no-throw-literal` and `no-reject-literal`

**Comment by platinumazure** [comment]
Possible addition: Refactor public-facing APIs to use ES6 classes, where feasible (this can't be done outside of semver-major, for sure).

**Comment by JamesHenry** [comment]
@nzakas Will we able to get `eslint/eslint-scope` into v4 do you think?

**Comment by wtgtybhertgeghgtwtg** [comment]
Would it be possible to have https://github.com/eslint/eslint/issues/7718 considerd for `eslint@4.0.0`, as well?

**Comment by JamesHenry** [comment]
@wtgtybhertgeghgtwtg Only accepted issues are eligible for consideration, and that issue is currently not. I have requested a bit more info from you on the thread. Thanks!

**Comment by nzakas** [comment]
Yeah, we should work to get eslint-scope into 4.0.0. We should probably open an issue on babel-eslint to let them know of the change ahead of time.

**Comment by not-an-aardvark** [comment]
I'm going to close this issue in favor of using the [v4.0.0 project](https://github.com/eslint/eslint/projects/3) for tracking instead. The changes that have been suggested are all already on the tracking project in some form.
