### ISSUE TITLE
Implement formatter with rel paths, colors and path:line:column lines

### ISSUE THREAD

**Issue by a-x-** [eslint/eslint#7412]
```
tmp2.js:1:1: Do not use 'new' for side effects. [Error/no-new]
tmp2.js:1:5: 'FooBar' is not defined. [Error/no-undef]
tmp2.js:1:11: Missing semicolon. [Error/semi]
```

* relative paths (to project root)
* :line:column like eslint `unix` formatter
* colored output like jscs and eslint default formatter (stylish)

**Comment by platinumazure** [comment]
I don't think we're accepting new formatters anymore (except for the JSCS one in progress elsewhere), but you can certainly build your own that does what you want. Please stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you run into any trouble.

**Comment by vitorbal** [comment]
FWIW, the JSCS formatter (I'm the one working on it) will have relative paths, colored output and (maybe) path:line:column in the output. Here's the issue if you want to track the progress on that one: https://github.com/eslint/eslint/issues/5860

**Comment by a-x-** [comment]
@vitorbal, ok, cool.

it's not clear for me by #5860 issue description

**Comment by vitorbal** [comment]
@a-x- unless, something unexpected comes up, it will be in there :)
Closing this, as it looks like there's nothing left to discuss. Thanks for reaching out!
