### ISSUE TITLE
eslint-config-eslint needs a major version release

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#7414]
**TSC Summary**: Our internal ESLint configuration, package "eslint-config-eslint", hasn't been updated on npm for nine months. This means that other ESLint repos which use it aren't getting the benefits of recent changes to that configuration.

Since changing a config is probably a breaking change for consumers (we consider it as such with `eslint:recommended`, after all), I believe we should publish a major version.

**TSC Question**: Should we publish a new major version for eslint-config-eslint?

**Comment by ilyavolodin** [comment]
I would like to expand the question to: Should we consider doing a release of `eslint-config-eslint` any time we do major release for ESLint?

**Comment by platinumazure** [comment]
That's a good point.

The good news is, by publishing a major version of the config, other
organization repos can consume at their own pace. For example, supposing
the config is now only useful for ES6 repos, that means generator-eslint
would have to wait. However, by not publishing a configuration at all,
repos which might be ready to consume it are stuck with the older version.

Maybe the config needs to be forked for ES6 vs non-ES6 configuration? Not
sure.

**Comment by alberto** [comment]
**TSC Resolution**: Verify that configuration is stable and after that release a new major version of eslint-config-eslint. It should follow it's own release cycle.

**Comment by kaicataldo** [comment]
@eslint/eslint-team How does everyone feel about this now? It's been a few months since the TSC discussion.

**Comment by not-an-aardvark** [comment]
Fine by me. We might want to decide what we're doing about `comma-dangle` (https://github.com/eslint/eslint/issues/7725) first though.

**Comment by not-an-aardvark** [comment]
Now that https://github.com/eslint/eslint/issues/7725 is closed and we've added all the rules in https://github.com/eslint/eslint/issues/6407, I think we're ready to do this (unless anyone has other rules that they'd like to add).

**Comment by danny-andrews** [comment]
> The big problem right now is that the ESLint repo is using ES6 while none of the others are, so it's unclear if eslint-config-eslint would be of use to them.

Just wanted to mention that some people outside the eslint organization find eslint-config-eslint to be a great base config to work off of, and get use out of the es6 rules. ;)

**Comment by ilyavolodin** [comment]
I think we should be good to schedule a new major release now that we enabled a bunch of rules in ESLint core. Just need to verify that all of the other projects will not pull new major version.

**Comment by not-an-aardvark** [comment]
All of the following projects use `eslint-config-eslint^3.0.0`, so they shouldn't be broken:

* espree
* generator-eslint
* eslint-transforms
* eslint-release
* typescript-eslint-parser
* eslint-plugin-markdown

So I think we should be good to run the release.

**Comment by ilyavolodin** [comment]
I think we can schedule a release for this at the same time we do next release for ESLint.

**Comment by ilyavolodin** [comment]
I created a new Jenkins build for eslint-config-eslint releases. And released version 4.0.0 just now. This issue is now done.
