### ISSUE TITLE
Broken link to new rule proposal template on eslint.org

### ISSUE THREAD

**Issue by kemitchell** [eslint/eslint#7419]
**Tell us about your environment**

This issue concerns eslint.org only.

**What parser (default, Babel-ESLint, etc.) are you using?**

N/A

**Please show your full configuration:**

N/A

**What did you do? Please include the actual source code causing the issue.**

- Browsed to http://eslint.org/docs/developer-guide/contributing/new-rules
- Clicked the link "rule proposal template"

**What did you expect to happen?**

- Load <https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md>

**What actually happened? Please include the actual, raw output from ESLint.**

- Loaded <https://github.com/eslint/eslint/blob/master/templates/rule-proposal> (no `.md` extension. 404.)

**Additional Observations**

457be1baa11e475b9419fc95679a49253c5a2cfa added the link in Markdown. The Markdown link URL is correct. Perhaps the site generation system is stripping out the extension, figuring it's another page that will be rendered to HTML and served on a path without extension?

**Comment by not-an-aardvark** [comment]
I can reproduce, thanks for the report. I think there was an issue awhile ago where .md extensions were getting stripped from URLs -- I'll see if I can find the relevant link.
