### ISSUE TITLE
A typo in no-unexpected-multiline rule documentation

### ISSUE THREAD

**Issue by gamtiq** [eslint/eslint#7442]
It seems there is a typo in [no-unexpected-multiline rule documentation](https://github.com/eslint/eslint/blob/master/docs/rules/no-unexpected-multiline.md):
> a newline *character character* always ends a statement

**Comment by platinumazure** [comment]
Hi @gamtiq, thanks for the issue! I've confirmed that the documentation does indeed have a typo.

Would you like to submit a pull request to fix it?

**Comment by gamtiq** [comment]
Hello @platinumazure,
I will make a pull request to fix the typo.
