### ISSUE TITLE
Parsing error: Unexpected token ...

### ISSUE THREAD

**Issue by rshmiraf** [eslint/eslint#7446]
**Tell us about your environment**

* **ESLint Version: v3.8.1**
* **Node Version: v6.8.1**
* **npm Version: v4.0.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint eslint-plugin-react, babel-eslint globally
atom: 1.11.2 with language-babel 2.45.0

**Please show your full configuration:**

```
module.exports = {
    "env": {
        "browser": true,
        "jquery": true,
        "node": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true,
            "modules": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "indent": [1,4],
        "linebreak-style": [1,"unix"],
        "quotes": [1,"double"],
        "semi": [1,"always"],
        "jsx-quotes": 1,

        "react/display-name": 0,
        "react/forbid-prop-types": 0,
        "react/jsx-boolean-value": 1,
        "react/jsx-closing-bracket-location": 1,
        "react/jsx-curly-spacing": 1,
        "react/jsx-handler-names": 1,
        "react/jsx-indent-props": 1,
        "react/jsx-indent": 1,
        "react/jsx-key": 1,
        "react/jsx-max-props-per-line": 0,
        "react/jsx-no-bind": 0,
        "react/jsx-no-duplicate-props": 1,
        "react/jsx-no-literals": 0,
        "react/jsx-no-undef": 1,
        "react/jsx-pascal-case": 1,
        "react/jsx-sort-prop-types": 0,
        "react/jsx-sort-props": 0,
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "react/no-danger": 1,
        "react/no-deprecated": 1,
        "react/no-did-mount-set-state": 1,
        "react/no-did-update-set-state": 1,
        "react/no-direct-mutation-state": 1,
        "react/no-is-mounted": 1,
        "react/no-multi-comp": 0,
        "react/no-set-state": 0,
        "react/no-string-refs": 0,
        "react/no-unknown-property": 1,
        "react/prefer-es6-class": 1,
        "react/prop-types": 0,
        "react/react-in-jsx-scope": 1,
        "react/require-extension": 1,
        "react/self-closing-comp": 1,
        "react/sort-comp": 1,
        "react/wrap-multilines": 1,
    }
};

```

**What did you do? Please include the actual source code causing the issue.**

![screen shot 2016-10-24 at 22 59 47](https://cloud.githubusercontent.com/assets/14861637/19663888/5fbecec0-9a3e-11e6-8f4d-a9235095f49f.png)

**What did you expect to happen?**
Why its error? This code work well :)

**Comment by platinumazure** [comment]
Object spread is not part of ES6. Our parser, espree, supports it as an experimental feature, but you must enable it as an ecmaFeature "experimentalObjectRestSpread": true.

See our [parser options](http://eslint.org/docs/user-guide/configuring#specifying-parser-options) documentation for more information.

**Comment by rshmiraf** [comment]
Thanks a lot platinumazure. Thats resolved my problem.

Last question is that problem. I'm using this short option:

> state={}

to set default empty object. This method its not bad but making a problem with a tabs.

![screen shot 2016-10-24 at 23 24 27](https://cloud.githubusercontent.com/assets/14861637/19664539/2c65907e-9a41-11e6-9acd-0a6f8105a83c.png)

**Comment by not-an-aardvark** [comment]
To fix this, you can use `"indent": [1, 4, {"SwitchCase": 1}]` to change the indentation setting for switch cases.

**Comment by rshmiraf** [comment]
Great! Thanks you not-an-aardvark :)
