### ISSUE TITLE
spread operator in React component children crashes no-use-before-define rule

### ISSUE THREAD

**Issue by viventus** [eslint/eslint#7451]
**Tell us about your environment**
- **ESLint Version:3.6.0**
- **Node Version:6.5.0**
- **npm Version:3.10.6**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint
**Please show your full configuration:**

```
{
  "parser": "babel-eslint",
  "extends": "airbnb",

  "env": {
    "browser": true
  },
  "plugins": [
    "flowtype"
  ],
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  },
  "rules": {
    "indent": [2, 4, {"SwitchCase": 1}],
    "linebreak-style": [2, "unix"],
    "react/jsx-indent": [2, 4],
    "react/jsx-indent-props": [2, 4],
    "react/sort-comp": [2, {
      "order": [
        "flow",
        "/^_.+$/",
        "static-methods",
        "lifecycle",
        "everything-else",
        "render"
      ],
      "groups": {
        "flow": [
          "props",
          "state",
          "defaultProps"
        ]
      }
    }],
    "flowtype/require-parameter-type": 0,
    "flowtype/define-flow-type": 1,
    "flowtype/use-flow-type": 1,
    "flowtype/valid-syntax": 1,
    "flowtype/union-intersection-spacing": [
      2,
      "always"
    ],
    "max-len": [0, 140, 2],

    "react/jsx-no-target-blank": "off",
    "func-names": "off",
    "global-require": "off",
    "import/no-named-as-default": "off",
    "radix": "off",
    "no-prototype-builtins": "off",
    "react/prop-types": "off",
    "no-param-reassign": "off",
    "consistent-return": "off",
    "react/no-danger": "off",
    "react/no-unused-prop-types": "off",
    "react/prefer-stateless-function": "off",
    "react/jsx-no-bind": "off",
    "react/jsx-filename-extension": "off",
    "react/forbid-prop-types": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/href-no-hash": "off",
    "jsx-a11y/label-has-for": "off",
    "class-methods-use-this": "off",
    "label-has-for": "off",
    "comma-dangle": "off",
    "import/no-extraneous-dependencies": "off",
    "import/no-unresolved": "off",
    "import/extensions": "off",
    "import/prefer-default-export": "off",
    "arrow-parens": "off",
    "arrow-body-style": "off",
    "camelcase": "off",
    "no-duplicate-imports": "off",
    "no-underscore-dangle": "off",
    "no-case-declarations": "off",
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }]
  }
}

```

**What did you do? Please include the actual source code causing the issue.**

``` js

const foo = {};
return <div>{...foo}</div>;

```

**What did you expect to happen?**

Nothing. It was an invalid jsx file.

**What actually happened? Please include the actual, raw output from ESLint.**

Cannot read property '1' of undefined
TypeError: Cannot read property '1' of undefined
    at /node_modules/eslint/lib/rules/no-use-before-define.js:202:83
    at Array.forEach (native)
    at findVariablesInScope (/node_modules/eslint/lib/rules/no-use-before-define.js:190:30)
    at findVariables (/node_modules/eslint/lib/rules/no-use-before-define.js:226:13)
    at EventEmitter.ruleDefinition.ArrowFunctionExpression:exit (/node_modules/eslint/lib/rules/no-use-before-define.js:249:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:628:23)
    at CommentEventGenerator.leaveNode (/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.leave (/node_modules/eslint/lib/eslint.js:901:36)

**Comment by vitorbal** [comment]
Thank you for the report.

> What did you expect to happen?
> 
> Nothing. It was an invalid jsx file.

I'm not sure I understand. If the file had invalid JSX, as you mentioned, shouldn't it report a syntax error?

@mysticatea @hzoo any clue if this could be related to different names for the AST nodes between babel-eslint and the default parser?

**Comment by not-an-aardvark** [comment]
Even if the JSX is invalid, I think the rule shouldn't throw a TypeError under any circumstances. (Also, if the rule is getting run at all, the file must have been successfully parsed.)

**Comment by mysticatea** [comment]
Thank you for the issue.

But I could not reproduce it with both `espree` and `babel-eslint` of [astexplorer.net](http://astexplorer.net/#/bgGvGB0QdA).
In both cases, it notified a parsing error expectedly.

```js
/* eslint no-use-before-define: error */

const foo = {};
const div = <div {...foo}>{...foo}</div>
```

```
$ eslint test.js --no-eslintrc --no-ignore --parser-options "ecmaVersion:2015,ecmaFeatures:{jsx:true,experimentalObjectRestSpread:true}"

C:\Users\t-nagashima.AD\Documents\GitHub\eslint\test.js
  4:28  error  Parsing error: Unexpected token ..

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kaicataldo** [comment]
Closing this issue since we haven't heard anything back for quite some time. Feel free to create a new issue if this is something you would like to discuss further.

**Comment by villesau** [comment]
This same is now happening with flow & flows new spread type syntax. Babel transpiles, but eslint fails into same error.

**Comment by villesau** [comment]
Now when i parsed an AST using babylon (not the flow parser), GenericTypeAccotation looks like this:
```
{
                            'type': 'GenericTypeAnnotation',
                            'start': 55,
                            'end': 56,
                            'loc': {'start': {'line': 3, 'column': 21}, 'end': {'line': 3, 'column': 22}},
                            'typeParameters': null,
                            'id': {
                                'type': 'Identifier',
                                'start': 55,
                                'end': 56,
                                'loc': {
                                    'start': {'line': 3, 'column': 21},
                                    'end': {'line': 3, 'column': 22},
                                    'identifierName': 'A'
                                },
                                'name': 'A'
                            }
                        }
```
