### ISSUE TITLE
Eslint no-var --fix command just changes var to let

### ISSUE THREAD

**Issue by revisionfour** [eslint/eslint#7458]
Running the --fix command with the eslint no-var rule only changes var to let. It does not seem to intelligently check to see if a variable is reassigned or not, properly determining whether to use let or const.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

I think this is intended behavior for `no-var`. To ensure that `const` is used rather than `let` where possible, you should use the [`prefer-const`](http://eslint.org/docs/rules/prefer-const) rule.

**Comment by revisionfour** [comment]
I think its a little misleading by the title of the rule in the link.
http://eslint.org/docs/rules/no-var

Its very unclear what the --fix command is going to do and it just changes var to let.

The [prefer-const](http://eslint.org/docs/rules/prefer-const) rule is also not totally clear what the --fix command is going to do. I don't think this will do what I want either because in the example it suggest to use the no-var rule at the bottom.

no-var --fix command should change var to either let or const, not just let. Or at least there should be settings to adjust for both. The --fix on prefer-const is not going to change var decorations, it appears it just changes let to const?

If the rules are written as described, how would one change var to either let or const intelligently or are you saying you do a no-var --fix, then a prefer-const --fix or can I add both rules and get the result Im trying to get?

**Comment by not-an-aardvark** [comment]
> no-var --fix command should change var to either let or const, not just let. Or at least there should be settings to adjust for both.

The idea is that there is a separation of concerns. `no-var` only deals with `var`, and it ensures that there are no `var` statements in the code, but it doesn't have an explicit preference for `let` versus `const` (aside from the fact that it always autofixes to `let`). The assumption is that if the user does have a preference to use `const` rather than `let`, they can just enable `prefer-const` as well.

> If the rules are written as described, how would one change var to either let or const intelligently or are you saying you do a no-var --fix, then a prefer-const --fix or can I add both rules and get the result Im trying to get?

Yes, if you enable both rules, you should get what you want when you use the --fix option.

**Comment by revisionfour** [comment]
Ok, that answers my question, thank you :)
