### ISSUE TITLE
Bug with no-unused-expressions (possibly ternary problem?)

### ISSUE THREAD

**Issue by naomiajacobs** [eslint/eslint#7469]
**Tell us about your environment**

* **ESLint Version:**
```js
{
  "eslint": "^3.7.0",
  "eslint-config-airbnb": "^10.0.1",
  "eslint-loader": "^1.5.0",
  "eslint-plugin-import": "^1.13.0",
  "eslint-plugin-jsx-a11y": "^2.1.0",
  "eslint-plugin-react": "^6.1.2",
}
```
* **Node Version:**
6.5.0

* **npm Version:**
3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
```js
{
  "babel-core": "^6.14.0",
  "babel-loader": "^6.2.5",
  "babel-plugin-transform-runtime": "^6.15.0",
  "babel-preset-es2015": "^6.14.0",
  "babel-preset-react": "^6.11.1",
  "babel-runtime": "^6.18.0",
}
```

**Please show your full configuration:**

```js
module.exports = {
  extends: 'airbnb',
  rules: {
    'import/no-extraneous-dependencies': [
      'off',
      { devDependencies: true, optionalDependencies: false, peerDependencies: false },
    ],
    'import/no-unresolved': 'off',
    'max-len': ['error', {
      code: 120,
      ignoreComments: true,
      ignoreStrings: true,
    }],
    'import/no-commonjs': 'error',
    'eol-last': ['error', 'always'],
  },
  env: {
    browser: true,
    node: true,
    jasmine: true,
  },
  globals: {
    _: true,
    $: true,
    moment: true,
  },
};
```

**What did you do? Please include the actual source code causing the issue.**

```js
// centuryNotSpecified is a boolean
// startDate and year are numbers
if (centuryNotSpecified) { year < startDate ? year = `20${year}` : year = `19${year}`; }
```

**What did you expect to happen?**
Since `year` is being assigned in the ternary, there is state change as a result of this `if` block, we expect this line not to error. Not sure if this is an issue with eslint not understanding ternaries or what, but it seems like this line should be fine.

**What actually happened? Please include the actual, raw output from ESLint.**
`error  Expected an assignment or function call and instead saw an expression  no-unused-expressions`

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

You can use the [`allowTernary`](http://eslint.org/docs/rules/no-unused-expressions#options) option to allow this pattern:

```json
{
  "rules": {
    "no-unused-expressions": ["error", {"allowTernary": true}]
  }
}
```

By default, `allowTernary` is false, so I think this is working as intended.

**Comment by naomiajacobs** [comment]
Ah, thanks so much!
