### ISSUE TITLE
Code style problem

### ISSUE THREAD

**Issue by rshmiraf** [eslint/eslint#7491]
**Tell us about your environment**
- **ESLint Version:** v3.9.0
- **Node Version:** v6.8.1
- **npm Version:** 4.0.0

**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true
  },
  "extends": "airbnb",
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "rules": {
    "no-plusplus": 0,
    "jsx-a11y/no-static-element-interactions": 0,
    "import/no-unresolved": 0,
    "max-len": 0,
    "new-cap": 0,
    "global-require": 0,
    "no-underscore-dangle": 0,
    "arrow-body-style": 0,
    "no-console": 0,
    "react/forbid-prop-types": 0,
    "jsx-a11y/href-no-hash": 0,
    "import/prefer-default-export": 0,
    "react/prop-types": 0,
    "react/prefer-stateless-function": 0,
    "react/jsx-first-prop-new-line": 0,
    "react/jsx-closing-bracket-location": 0
  }
}

```

**What actually happened? Please include the actual, raw output from ESLint.**

Can I change my indention style to remove issues like this? 
Second option of code looks much more cleaner. Of course i can have everything in one line but this is terrible. I know i can turn off this fully but i very like this helpers :)

![screen shot 2016-10-30 at 22 54 51](https://cloud.githubusercontent.com/assets/14861637/19840370/59ad0316-9ef4-11e6-8f19-9220f3dfa69b.png)
![screen shot 2016-10-30 at 22 54 16](https://cloud.githubusercontent.com/assets/14861637/19840371/59ae6044-9ef4-11e6-8d05-cb4ad6fd2e25.png)

**Comment by gyandeeps** [comment]
Eslint react plugin has specific indent rules around this. You can propose these changes thier as they makes more sense inside react than in general.
Ref: https://github.com/yannickcr/eslint-plugin-react

**Comment by not-an-aardvark** [comment]
I'm closing this issue since it looks like the question has been answered, but feel free to continue the discussion.
