### ISSUE TITLE
Question: How do you add more paths to the CLIEngine to search for plugins and modules?

### ISSUE THREAD

**Issue by the-simian** [eslint/eslint#7508]
Is it possible to have the CLIEngine search additional directories for plugins and modules if defined explicitly. Looking in the code I see there is a ModuleResolver that can take extra lookup paths, but I don't see where one would configure that when defining a CLIEngine object.

My use-case is that I have a project trying to lint another project, where the project being linted owns its own plugins, but the 'linter' project owns other things, like the reporter. I'd like to be able to search the project being acted upon for its plugins and modules.

Currently of course it can't find any of them.

**Comment by platinumazure** [comment]
As I mentioned in our Gitter chat, it's possible to add a plugin object (which you can require from any directory you like) using the [`addPlugin`](http://eslint.org/docs/developer-guide/nodejs-api#addplugin) method of CLIEngine. For your use case, this might possibly work if the plugin(s) is/are the only thing you need to load from the project being linted.

However, in general, I don't know if we have a way to configure what directories might be searched by ESLint for loading plugins or other relevant modules.

**Comment by the-simian** [comment]
I saw the documentation for add-plugin, but that unfortunately won't work, because I won't know which plugins are declared. Your second point speaks to what I am trying to do: add more directories to be searched.

Earlier when I was testing it might also be possible that I was getting errors because I was using `npm link` to test the module I was working on. I'm going to try without linking and see if it is able to find the plugins.

**Comment by nzakas** [comment]
I'm sorry, this isn't something we can support easily, as there are a lot of assumptions built into how ESLint looks up paths right now. 

We unfortunately have too many other open and active issues affecting a larger number of people, so it's unlikely that a change will be pursued anytime soon. 

Thanks for the feedback.

**Comment by the-simian** [comment]
thats fine @nzakas , thanks for the response and the great project
