### ISSUE TITLE
Scheduled Release for November 11, 2016

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7512]
The scheduled release on Friday, November 11, 2016 is assigned to:

@ilyavolodin 
@btmills

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by platinumazure** [comment]
@eslint/eslint-tsc Do we have volunteers for this release? If so, can someone please update this issue? Otherwise it's a bit scary that we don't have anyone scheduled to manage the release :smile:

**Comment by nzakas** [comment]
We have TSC meeting today, we'll be sure someone gets assigned.

**Comment by btmills** [comment]
To keep this issue up to date, we just did a 3.10.1 patch release. We're hoping to get in a fix for #7573 and do another patch release this week, so please continue merging only semver-patch PRs.

**Comment by ilyavolodin** [comment]
Released 3.10.2 yesterday to fix 3 issues with autofixing breaking code. This concludes this release cycle and repository is open for merging now.
