### ISSUE TITLE
Add option to exclude ES6 imports from no-unused-vars

### ISSUE THREAD

**Issue by luchsamapparat** [eslint/eslint#7519]
I'd like to propose an `ignoreModules` option for the `no-unused-vars` rule which ignores unused module imports. A common scenario is importing polyfills so that Webpack includes them in a bundle. I don't need to actually use that dependency, I just import it to make sure it is loaded. 

**What rule do you want to change?**
no-unused-vars

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
new option

**Please provide some example code that this change will affect:**
```js
import WebComponents from 'webcomponents.js/webcomponents-lite';
```

**What does the rule currently do for this code?**
```
error: 'WebComponents' is defined but never used (no-unused-vars) at...
```

**What will the rule do after it's changed?**
When using the rule with an optional option `ignoreModules` like this, unused imports are ignored:
```
/*eslint no-unused-vars: ["error", { "ignoreModules": true }]*/

import WebComponents from 'webcomponents.js/webcomponents-lite';
```

**Comment by luchsamapparat** [comment]
nevermind. i just realized that I can just import like this:
```
import 'webcomponents.js/webcomponents-lite';
```

**Comment by ragzovskii** [comment]
Actually I would like to have option to ignore unused imports and warn about unused vars. Because why not? Given approach works only for default export
