### ISSUE TITLE
Weird CLI output

### ISSUE THREAD

**Issue by ryanmt** [eslint/eslint#7541]
**Tell us about your environment**
Fedora 24
* **ESLint Version:**
v3.9.1
* **Node Version:**
v4.6.1
* **npm Version:**
2.15.9
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

```
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "globals": {
    "expect": true,
    "sinon": true,
    "createTestbed": true
  },
  "settings": {
    "ecmascript": 6,
    "jsx": true,
    "format-message": {
      "sourceLocale": "en",
      "generateId": "underscored_crc32",
      "translations": "./translations"
    }
  },
  "plugins": [
    "format-message",
    "react",
    "mocha"
  ],
  "rules": {
    "generator-star-spacing": 0, # https://github.com/babel/babel-eslint/issues/316
    "max-len": [2, 120, 2],
    "jsx-quotes": [2, "prefer-double"],
    "key-spacing": [2, {
      "beforeColon": false,
      "afterColon": true,
      "mode": "minimum"
    }],
    "no-var": 2,
    "no-ternary": 0,
    "prefer-const": 2,
    "no-console": 2,
    "no-param-reassign": [2, { "props": true }],
    "mocha/no-exclusive-tests": "error"
  },
  "extends": [
    "standard",
    "standard-react",
    "plugin:format-message/recommended"
  ]
}
```

**What did you do? Please include the actual source code causing the issue.**
N/A

**What did you expect to happen?**
Would expect a message like this to cause a failure, or at least tell me about the file that is causing issues.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Unexpected token {
Unexpected token {
.... continues for many pages...
Unexpected token {
Unexpected token {
```

I see this same block of weird output for every file processed when running in --debug mode
```
  eslint:config Using config from cache +0ms
Unexpected token {
Unexpected token {
Unexpected token {
Unexpected token {
  eslint:cli-engine Processing /home/...
```

If nothing else, I'd love some tips on debugging this.  It is pretty annoying.

**Comment by nzakas** [comment]
This looks like it's coming from `babel-eslint`. If you aren't using stage 3 or lower features, I'd suggest trying to use the default parser instead and see if you get anything different. 

Otherwise, please include the actual source code you're trying to lint.

**Comment by not-an-aardvark** [comment]
There hasn't been any activity on this issue for awhile and it doesn't look like this is a problem with ESLint, so I'm going to close it. However, feel free to continue the discussion.
