### ISSUE TITLE
Documentation: Links to CLA

### ISSUE THREAD

**Issue by Fransz** [eslint/eslint#7558]
Making my first (tiny) commit to this repo, i had difficulty signing the CLA.

The links in the docs under docs/developer-guide/contributing/ point to https://contribute.jquery.org/cla
In the end i was able to sign by using https://cla.js.foundation/eslint/eslint. I took me quite some time to find the correct URL.

 I think the mentioned documents should link to the correct url.

**Comment by platinumazure** [comment]
Thanks for the issue, @Fransz! I agree, we should change those links. The links used to redirect to the correct page, but we should fix those for sure.

**Comment by vitorbal** [comment]
Thanks for the issue! I will fix this.

**Comment by vitorbal** [comment]
I've opened a PR to fix this in the eslint.github.io repository, where the code for the redirect is, so we can track the fix there.
Closing this, thanks again for reporting it, @Fransz!
