### ISSUE TITLE
Rule Proposal: Don't allow or warn against window.open without setting opener to null.

### ISSUE THREAD

**Issue by t3kk** [eslint/eslint#7560]
**What category of rule is this? (place an "X" next to just one item)**

[ ] Enforces code style 
[ ] Warns about a potential error 
[ ] Suggests an alternate way of doing something 
[X] Other (please specify:)
Prevent security issues related to having the referrer in the window of a page opened in a new tab.

**Provide 2-3 code examples that this rule will warn about:**
```js
window.open('untrustworthy.website.com')
```
```js
var newWin= window.open();
newWin.location = 'https://untrustworthy.website.com')
```
```js
var win = window;
win.open('https://untrustworthy.website.com');
```

**If the opener is set to null it shouldn't need to warn.**
```js
let newWin = window.open();
newWin.opener = null;
newWin.location('https://untrustworthy.website.com');
```

**Why should this rule be included in ESLint (instead of a plugin)?**
It is a security risk and allows control over the page that requested the new page be opened:
https://mathiasbynens.github.io/rel-noopener/
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by platinumazure** [comment]
This seems like a pretty niche use case and might fit better in a plugin.

Can you please provide at least one example of code that your proposed rule *shouldn't* warn against?

**Comment by t3kk** [comment]
Sure.  I've updated the issue now to include an example.

**Comment by vitorbal** [comment]
I agree with @platinumazure that this probably makes more sense as a plugin. Personally, if you can collect a few of these security-related rules, I would think that would be quite a nice plugin!

**Comment by t3kk** [comment]
Thank you for the review.  I'll close this out then.
