### ISSUE TITLE
Invalid dependency install when choosing Airbnb in --init

### ISSUE THREAD

**Issue by msikma** [eslint/eslint#7576]
When following the [getting started guide](http://eslint.org/docs/user-guide/getting-started) and installing a new environment using `eslint --init` and choosing Airbnb, an invalid dependency is installed—`eslint-plugin-jsx-a11y` is installed as version 3.0.1 and not 2.x.x as required.

**Tell us about your environment**

A ReactJS project that did not have linting before now, and has minimal dependencies. Aside from a few new dependencies it's essentially a new project from [create-react-app](https://github.com/facebookincubator/create-react-app).

* **ESLint Version:** v.3.9.1
* **Node Version:** v6.3.1
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

This is the default configuration generated by `eslint --init` as per the [getting started guide](http://eslint.org/docs/user-guide/getting-started).

```
{
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ]
}
```

**What did you do? Please include the actual source code causing the issue.**

I've just set up ESLint for a new project which didn't have any kind of linting before, and I ended up with `eslint-plugin-jsx-a11y@3.0.1` even though Airbnb requires v2. Basically, I installed `eslint` (which installed v3.9.1), ran `./node_modules/.bin/eslint --init`, then chose Airbnb and JSON.

This yields an install which includes `eslint-plugin-jsx-a11y@3.0.1` and this complaint:

    npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.

Linting any file then produces an error message as described [in this bug report on Airbnb](https://github.com/airbnb/javascript/issues/1172).

**What did you expect to happen?**

I expected `eslint-plugin-jsx-a11y@^2.2.3` to be installed instead of `eslint-plugin-jsx-a11y@3.0.1`, and the subsequent linting operation to occur normally.

**What actually happened? Please include the actual, raw output from ESLint.**

`eslint-plugin-jsx-a11y@3.0.1` was installed, and a lint produces this error:

```
/Users/msikma/Projects/my/project/node_modules/eslint-config-airbnb/rules/react-a11y.js:
	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "" is the wrong type.

Referenced from: airbnb
Referenced from: /Users/msikma/Projects/my/project/.eslintrc.json
Error: /Users/msikma/Projects/my/project/node_modules/eslint-config-airbnb/rules/react-a11y.js:
	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "" is the wrong type.

Referenced from: airbnb
Referenced from: /Users/msikma/Projects/my/project/.eslintrc.json
    at validateRuleOptions (/Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-file.js:522:19)
    at /Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-file.js:529:22)
    at /Users/msikma/Projects/my/project/node_modules/eslint/lib/config/config-file.js:391:36
```

Manually setting the correct version in the `package.json` and reinstalling fixes the issue.

**Comment by platinumazure** [comment]
Duplicate of #7338.

See [this comment](https://github.com/eslint/eslint/issues/7338#issuecomment-252785808) for how to handle the issue.

Also, per [this comment](https://github.com/eslint/eslint/issues/7338#issuecomment-252931101), we have an idea on how to fix this, but JSCS compatibility is the main focus of the core team. If you want to submit a PR to implement vitorbal's suggestion, we are happy to review it and merge it in if everything looks good.

**Comment by msikma** [comment]
Sorry for reporting a duplicate 👍
