### ISSUE TITLE
Scheduled Release for November 25, 2016

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7577]
The scheduled release on Friday, November 25, 2016 is assigned to:

@btmills 
@nzakas

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by btmills** [comment]
v3.11.1 was just released, which concludes this release cycle. The minor and patch releases both went smoothly from my perspective. We can resume merging semver-minor PRs!
