### ISSUE TITLE
please compile packages to es5 so that v0.1x can be supported.

### ISSUE THREAD

**Issue by calidion** [eslint/eslint#7585]
some of the packages are use es6+, which will breaks support for v0.1x when testing.

**Comment by alberto** [comment]
If you need ES5 support you should use eslint 2.X

**Comment by mysticatea** [comment]
ESLint 3 does not support Node 0.x. Please see also: http://eslint.org/docs/user-guide/migrating-to-3.0.0

[if-node-version](https://www.npmjs.com/package/if-node-version) module might help you for CI.
