### ISSUE TITLE
Proposal: Implement autofix for `no-return-await`

### ISSUE THREAD

**Issue by Alaneor** [eslint/eslint#7593]
#### Versions

- ESLint: 3.10
- Node: 7.1
- npm: 4.0.2

#### Description

I propose to implement an auto-fixer for the new `no-return-await` rule. Since `return await value` has the same meaning as `return value` in async functions, an auto-fix can be implemented which simply removes the `await` keyword.

There is currently one known exception to this - `try/catch` blocks. See pending issue #7581 (PR with fix also pending merge).

-----

I have an implementation of the auto-fixer ready - if you are interested you may see it [here](https://github.com/eslint/eslint/compare/master...Alaneor:autofix-no-return-await). Once this issue gets accepted I will open a PR with the actual implementation for further review.

**Comment by not-an-aardvark** [comment]
Thanks for the suggestion.

However, the decision to not autofix this rule was actually intentional; the presence of an `await` keyword delays the returned Promise from fulfilling by one tick, which can change the behavior of code and cause working code to break. As such, I don't think we should autofix this.

For example:

```js
const p = Promise.resolve();

async function foo() {
  return await p;
}

async function bar() {
  return p;
}

foo().then(() => console.log('foo'));
bar().then(() => console.log('bar'));

// output:
// bar
// foo
```

```js
const p = Promise.resolve();

async function foo() {
  return p;
}

async function bar() {
  return p;
}

foo().then(() => console.log('foo'));
bar().then(() => console.log('bar'));

// output:
// foo
// bar
```

**Comment by isiahmeadows** [comment]
@not-an-aardvark Some rule auto-fixes already affect semantics. Here's a few of them:

- no-unsafe-negation: `!a < b` and `a < b` are completely different things
- strict: obvious
- prefer-arrow-callback: an issue if you are using an anonymous function as a constructor.

Not sure this is any different.

**Comment by not-an-aardvark** [comment]
The fixer for `strict` only removes redundant `'use strict'` declarations; it doesn't ever change strict code to non-strict or vice versa.

That's a good point about the other two, though. We might want to remove autofixing for those rules if we can't verify that they won't break code.

**Comment by isiahmeadows** [comment]
Oh. I didn't realize `strict` limited itself to that.

I'll also point out that it's generally a bad idea to rely on the resolution order of two independent promises, so I'd be shocked if they would actually break anything in practice. (The above sample already warns, and the autofixer doesn't touch ignored lines IIUC).

If you actually wish for that kind of behavior, it's best to make it explicit, though, so ESLint doesn't complain.

```js
// Option 1
const p = Promise.resolve();

async function foo() {
  // I know it seems odd, but it's intentional.
  return await p; // eslint-disable-line no-return-await
}

async function bar() {
  return p;
}

// Option 2
const p = Promise.resolve();

async function foo() {
  // Very obviously intentional.
  return Promise.resolve().then(() => p);
}

async function bar() {
  return p;
}
```

**Comment by isiahmeadows** [comment]
And the reason I believe `no-unsafe-negation` allows autofixing is because things like `!a instanceof A` instead of `!(a instanceof A)` are a frequent source of bugs for less experienced developers.

**Comment by isiahmeadows** [comment]
With `prefer-arrow-callback`, it usually doesn't matter, and when I need a constructor, I usually use an anonymous class literal. It forces me to be more explicit as to the intent (and discourages my use of that concept because of the extra boilerplate).

**Comment by not-an-aardvark** [comment]
I agree that users generally *shouldn't* be relying on these things, but one of the design goals of ESLint's autofixing is to never break working code under any circumstances, regardless of whether that code is "good". It should be safe enough that people would be comfortable with running `eslint --fix` and then immediately deploying to production.

**Comment by platinumazure** [comment]
@isiahmeadows @not-an-aardvark This is interesting discussion, but can we please keep the issue focused to autofixing (or not) for `no-return-await`? Please feel free to visit our [Gitter chat](https://gitter.im/eslint/eslint) if you wish to continue the general auto-fix discussion, or please feel free to open an issue if you believe you have identified an issue with one of our other rules.

**Comment by isiahmeadows** [comment]
@platinumazure Sorry. (I only brought it up as evidence in favor of implementing autofixing for this particular rule.)

**Comment by not-an-aardvark** [comment]
It looks like there were several team members opposed to adding autofixing for `no-return-await`, so I'm going to go ahead and close this issue.
