### ISSUE TITLE
ESLint doesn't work without running init. But init overwrites existing ESLintRC. 

### ISSUE THREAD

**Issue by jaepage** [eslint/eslint#7598]
**Tell us about your environment**
Mac OS X El Capitan: 10.11.6 (15G1004)
Sublime Text 3: Build 3126

* **ESLint Version:**
v1.9.0

* **Node Version:**
v6.7.0

* **npm Version:**
3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
{
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ],
    "rules": {
        "class-methods-use-this": [1],
        "comma-dangle": [1, "always-multiline"],
        "func-names": [1, "as-needed"],
        "import/extensions": [0],
        "import/no-named-as-default": [0],
        "indent": [1, 4, { "SwitchCase": 1 }],
        "jsx-a11y/label-has-for": [1],
        "jsx-a11y/no-static-element-interactions": [1],
        "max-len": [1, 120],
        "newline-per-chained-call": [1],
        "no-console": [0],
        "no-mixed-operators": [0],
        "no-trailing-spaces": [1],
        "no-undef": [0],
        "no-underscore-dangle": [0],
        "no-unused-expressions": [2, { "allowShortCircuit": true }],
        "no-unused-vars": [1],
        "no-var": [1],
        "react/forbid-prop-types": [1],
        "react/jsx-indent": [1, 4],
        "react/jsx-indent-props": [1, 4],
        "react/jsx-no-bind": [1],
        "react/jsx-wrap-multilines": [0],
        "react/no-danger": [0],
        "react/no-find-dom-node": [1],
        "react/no-string-refs": [1],
        "react/no-unescaped-entities": [1],
        "react/no-unused-prop-types": [0],
        "react/sort-comp": [1],
        "space-before-function-paren": [1, "always"]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**
- Run instructions under "[Local Installation and Usage](http://eslint.org/docs/user-guide/getting-started#local-installation-and-usage)".
- Adjust rules in `.eslintrc.json` as desired.
- Observe linting occurs in JSX files in Sublime.
- Git commit and push. 
- Git clone into test directory. 
- Run NPM install.
- Observe linting is not occuring in JSX files in Sublime.
- Re-run instructions under "Local Installation and Usage". 
- New `.eslintrc.json` is generated. 

How should this be set up for multiple team members to use the same Git-committed `.eslintrc.json` file?

**Comment by platinumazure** [comment]
Hmm. I do think we could/should warn if an .eslintrc file exists in the CWD (and allow a user to bail out, or perhaps forcefully error out) when running `eslint --init` to avoid accidental overrides.

That said, the proper thing to do was just to run `npm install` to get ESLint installed-- since you had an .eslintrc.json, you didn't need to re-run `eslint --init`.

Let's see what the rest of the team thinks.

**Comment by not-an-aardvark** [comment]
I would be fine with emitting a warning on `eslint --init` if a config file already exists. However, I think there is some confusion in this issue; when you already have a config file, ESLint should work without having to run `eslint --init` again.

@jaepage, are you able to reproduce this when using the latest version of ESLint from the command line, rather than through Sublime? I think your issue might be due to something with the Sublime setup, and not with ESLint itself. From ESLint's perspective, once there is a config file, it doesn't matter whether it was generated by `eslint --init` or by cloning a repo.

**Comment by jaepage** [comment]
Regarding ESLint version, my repo is using `"eslint": "^3.10.1",` in its package.json, but my bash seems stuck on v1.9.0: 
```
test $ eslint --version
v1.9.0
test $ npm install -g eslint
/Users/jpage/.nvm/versions/node/v6.7.0/bin/eslint -> /Users/jpage/.nvm/versions/node/v6.7.0/lib/node_modules/eslint/bin/eslint.js
/Users/jpage/.nvm/versions/node/v6.7.0/lib
└── eslint@3.10.1 

test $ eslint --version
v1.9.0
```
Is that odd?

**Comment by not-an-aardvark** [comment]
What happens if you run `which eslint`?

**Comment by jaepage** [comment]
```
test $ which eslint
/usr/local/bin/eslint
```

**Comment by jaepage** [comment]
Also, running ESLint from the command line works in my primary clone of the repo, fails in my test clone of the repo. `ESLint couldn't find the plugin "eslint-plugin-jsx-a11y".`

**Comment by not-an-aardvark** [comment]
It looks like something is configured incorrectly with your node/npm installation; ESLint 3.10.1 gets installed to `/Users/jpage/.nvm/versions/node/v6.7.0/bin/eslint`, but you're using the version of ESLint in `/usr/local/bin/eslint`.

**Comment by jaepage** [comment]
```
test $ which node
/Users/jpage/.nvm/versions/node/v6.7.0/bin/node
test $ which npm
/Users/jpage/.nvm/versions/node/v6.7.0/bin/npm
```

**Comment by jaepage** [comment]
Should I just manually remove `eslint` from `/usr/local/bin/`?

**Comment by not-an-aardvark** [comment]
I think that would probably work, although I'm not sure what the general solution would be for other globally-installed packages.

**Comment by jaepage** [comment]
I suppose I would also want to remove manually `/usr/local/lib/node_modules/eslint/` as well. Weird that `npm uninstall -g eslint` has no visible effect.

**Comment by not-an-aardvark** [comment]
I think your `npm` is configured to use `/Users/jpage/.nvm/versions/node/v6.7.0/bin` for global installations, but you have some existing modules in `/usr/local/bin` for some reason, which aren't getting touched by `npm` at the moment and are overriding the modules in `/Users/jpage/.nvm/versions/node/v6.7.0/bin` when you use `eslint`.

**Comment by jaepage** [comment]
Also, in my `/Users/jpage/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings`: 

```
{
    "user": {
        "debug": false,
        "delay": 0.5,
        "error_color": "e00",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "csslint": {
                "@disable": true,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": [
                    "adjoining-classes",
                    "box-model",
                    "box-sizing",
                    "fallback-colors",
                    "ids",
                    "universal-selector"
                ],
                "warnings": ""
            },
            "eslint": {
                "@disable": false,
                "args": [],
                "config_filename": ".eslintrc",
                "excludes": []
            },
            "jshint": {
                "@disable": true,
                "args": [],
                "config_filename": ".jshintrc",
                "esversion": 6,
                "excludes": []
            },
            "json": {
                "@disable": false,
                "args": [],
                "excludes": [
                    "*.eslintrc"
                ],
                "strict": true
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "sass": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "stippled underline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "bb0",
        "wrap_find": true
    }
}
```

**Comment by jaepage** [comment]
- OK. I manually removed the globally installed ESLint, confirmed my `which eslint` returning nothing. 
- I then re-ran ESLint from the command line (`./node_modules/.bin/eslint resources/assets/js/components/subcomponents/Modal.jsx`). In my primary clone, it works. In my test clone, it fails in the same way as before, `couldn't find the plugin "eslint-plugin-jsx-a11y"`. 
- Also, linting is still visible in Sublime in the primary clone, not visible in the test clone. 
- Re-installing ESLint globally then resulted in `which eslint` reporting `/Users/jpage/.nvm/versions/node/v6.7.0/bin/eslint`, but did not change observed behaviors.

**Comment by jaepage** [comment]
I have an `.eslintrc` file in my `~` directory. Could that be problematic?

**Comment by not-an-aardvark** [comment]
What does the `devDependencies` field in your `package.json` file look like?

Also, what happens if you run `npm install eslint-plugin-jsx-a11y` from your test clone?

**Comment by jaepage** [comment]
So, yes, I checked the Sublime console, and it was showing the same errors, could not find a11y, react, airbnb… 

This prompted me to try installing those dependencies via NPM, and now the issue is resolved. 

I'm not sure why this didn't cause a problem in the primary repo. Could ESLint's `init` have added them without saving them? But oh, well. Thank you.
