### ISSUE TITLE
no-unused-vars: remove unused imports

### ISSUE THREAD

**Issue by fab1an** [eslint/eslint#7619]
It would be awesome if eslint could automatically `--fix` unused es6 `import`s instead of reporting them as unused variables.

Is this feasible?

Thank you!

**Comment by mysticatea** [comment]
Thank you for this issue.

But I don't think it's feasible.
ESLint cannot distinguish whether people will use the unused variables after the autofix.

**Comment by not-an-aardvark** [comment]
This would also prevent the imported files from getting evaluated, which will cause code to break if the modules have side-effects

**Comment by vitorbal** [comment]
Thanks for the issue!
Looks like the team doesn't feel in favor of autofixing no-unused-vars, so I'm gonna go ahead and close this.
