### ISSUE TITLE
Support inline comment to specify configuration file.

### ISSUE THREAD

**Issue by adjohnson916** [eslint/eslint#7628]
**What version are you using?**
3.10.2
**What did you do?**
I have multiple ESLint configuration files, e.g. a default one for source, one for functional tests adding Protractor globals, one for unit tests adding Jasmine globals, etc.
**What happened?**
The Atom editor and its linter plugin (as well as other tools, I'm sure) only understands the default one, so it shows all kinds errors when I'm working on my test files (undefined globals, etc.)
**What did you expect to happen?**
I'd like a new feature allowing an inline comment to specify the location of the configuration file to use to lint the current file, e.g.:
```
/* eslint-config "../.eslint.karma.js" */

describe('my tests', function () {
  // ...
});
```

**Comment by adjohnson916** [comment]
#7629 is arguably more useful.

**Comment by alberto** [comment]
Closing as duplicate
