### ISSUE TITLE
Support configuration file overrides in default configuration.

### ISSUE THREAD

**Issue by adjohnson916** [eslint/eslint#7629]
Relates to #7628.

**What version are you using?**
3.10.2
**What did you do?**
I have multiple ESLint configuration files, e.g. a default one for source, one for functional tests adding Protractor globals, one for unit tests adding Jasmine globals, etc.
**What happened?**
The Atom editor and its linter plugin (as well as other tools, I'm sure) only understands the default one, so it shows all kinds errors when I'm working on my test files (undefined globals, etc.)
**What did you expect to happen?**
I'd like a new feature allowing the default configuration file to specify different configuration file overrides to be used for some files, matched by glob patterns, e.g. in `.eslintrc.js`:
```
module.exports = {
  "configs": {
    ".eslintrc.karma.js": "tests/**/*.js",
    ".eslintrc.protractor.js": "e2e-tests/**/*.js"
  },
  "extends": "eslint:recommended",
  "rules": {
    // ...
  }
};
```

**Comment by not-an-aardvark** [comment]
Thanks for the request. However, I think this is a duplicate of https://github.com/eslint/eslint/issues/3611.

**Comment by adjohnson916** [comment]
@not-an-aardvark I suppose you're right, that's similar enough. I'll close this one out. Thanks!

**Comment by AndersDJohnson** [comment]
Looks like this was introduced in #8081.
