### ISSUE TITLE
Browserify ESlint

### ISSUE THREAD

**Issue by ShirH** [eslint/eslint#7650]
Hi, I'm trying to browserify the ESlint (latest version) and the problem that ES lint contain fs module and when I try to use it I got error, any idea how to overcome this ?

**Comment by ilyavolodin** [comment]
@ShirH Browser is unsupported platform for ESLint. While we have our own browserify build, it's meant for internal use only (our website). If you really need ESLint to run in the browser, you can use our npm script `npm run browserify`. But again, this is unsupported feature.

**Comment by ShirH** [comment]
Thanks Ilya! Can you told me where I can find the code for your npm run browserify?

**Comment by platinumazure** [comment]
Start in package.json (look under "scripts"), then look at the referenced file(s).

**Comment by ilyavolodin** [comment]
@ShirH The actual code is located here: https://github.com/eslint/eslint/blob/master/Makefile.js#L717

**Comment by ShirH** [comment]
Thank you very match! 
Can you told me why your browserify build is for internal use only? and what is the cost for using it?

**Comment by ilyavolodin** [comment]
@ShirH It's internal use only because ESLint was never meant to be run in the browsers. Our only supported platform is Node. And the cost of using it is - no support from the team.

**Comment by vitorbal** [comment]
Closing, as it seems the question has been answered now. Feel free to keep the conversation going if needed!
