### ISSUE TITLE
Problem with RuleTester when errors is just a number

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7657]
Reported in https://github.com/eslint/eslint/pull/7640, however, the submitter was unwilling to follow our contribution guidelines or provide more information, so we need to investigate this a bit.

> If the `errors` field is just a number, then ESLint is currently ignoring the output field. This makes it easy to accidentally not test the output of a rule's auto-fix.

I believe this refers to setting the `errors` field in an invalid test for `RuleTester`. We do allow setting that value to be just a number rather than giving specific details about the error. I think the report is saying that `output` is not being verified if `errors` is a number.

We should verify that's the case, as the PR came with no tests.

**Comment by alberto** [comment]
Ooops! I used the wrong issue number in my commit. This was fixed in #8097). :/
