### ISSUE TITLE
Cannot find plugin if node_modules is in subdirectory

### ISSUE THREAD

**Issue by nealoke** [eslint/eslint#7711]
Hi, I am currently having an issue where eslint can't find the eslint-plugin-react. My folder structure is a bit away from the normal I guess where my node_modules are in tools/node_modules. Might this cause the error of not finding the module?

**Folder structure**
![explenation](https://cloud.githubusercontent.com/assets/17417414/20963803/3f3505ae-bc6f-11e6-958f-8dd143d2bb05.jpg)

**ESLint Version: 3.9.0**
**Node Version: 6.1.0**
**npm Version: 3.10.9**

**What parser (default, Babel-ESLint, etc.) are you using?: Default**

**Please show your full configuration:**

```
{
    "env": {
        "browser": true
    },

    "extends": "eslint:recommended",

    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },

    "plugins": [
        "react"
    ],

    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-unused-vars": ["error", { "varsIgnorePattern": "React" }]
    }
}
```

**What did you expect to happen?**
Eslint running with the plugin "react". Finding the plugin in the root/tools/node_modules folder

**What actually happened?**
```
SublimeLinter: eslint: nav_bar.js ['C:\\Users\\nealv\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team. 

```

**Comment by not-an-aardvark** [comment]
Thanks for the report. I think this is just due to the way Node's module resolution algorithm works. Dependencies are expected to be in `node_modules`, and projects won't be able to find them if they're anywhere else. So I'm not sure if there's anything ESLint can do to fix this.

**Comment by alberto** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the ESLint Gitter if you have any other issues!
