### ISSUE TITLE
Consider moving formatters to separate package.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [eslint/eslint#7718]
A couple of the dependencies of `eslint`, namely `babel-code-frame` and `table`, are only used by non-default formatters.  It would reduce the overall size of the `eslint` package by a couple of megabytes if these were moved.

**Comment by vitorbal** [comment]
@wtgtybhertgeghgtwtg thank you for your issue.
Please correct me if I'm wrong, but I believe this would be a breaking change.
IMO, it would definitely be nice to decrease the overall package size. Let's see what the rest of the team thinks, though. I'll label this as a core change, so we need TSC approval.

**Comment by wtgtybhertgeghgtwtg** [comment]
You are correct, this would be a breaking change.

**Comment by platinumazure** [comment]
At this point I'm :-1: to this, simply because the pain users will experience (as they have to install non-default formatters) seems quite high for a relatively small benefit. Hard drive space is getting very cheap these days.

**Comment by JamesHenry** [comment]
@wtgtybhertgeghgtwtg can you please comment on why/in what situations the download size of eslint is currently an issue? Avoiding bloat in packages is always good, but I agree with @platinumazure that the upside is very minimal.

ESLint is not a run time dependency of users' applications so its overall size will naturally be less of a concern.

**Comment by wtgtybhertgeghgtwtg** [comment]
Shaving off a couple megabytes and simplifying the dependency tree, that's pretty much it.  I can't give any reason more than those.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it.
