### ISSUE TITLE
eslint 3.12.0 indent validation failure with object on new line in function call, expects extra 11 indents

### ISSUE THREAD

**Issue by jdforrester** [eslint/eslint#7733]
**Tell us about your environment**

* **ESLint Version:** 3.12.0
* **Node Version:** 7.1.0
* **npm Version:** 4.0.3

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:** Using eslint-config-wikimedia 0.3.0 (which I maintain) via grunt-eslint 19.0.0; no other rules.

`package.json`:
```
{
  "private": true,
  "scripts": {
    "test": "grunt"
  },
  "devDependencies": {
    "eslint-config-wikimedia": "0.3.0",
    "grunt": "1.0.1",
    "grunt-eslint": "19.0.0"
  }
}
```

`.estlintrc.json`:
```
{
    "extends": "wikimedia"
}
```

**What did you do? Please include the actual source code causing the issue.**

```
/* global window */

window.foo( 'Foo', function () {
	var foo = [
		{
			foo: function () {
				window.foo( 'foo',
					{
						foo: 'bar',
						bar: {
							foo: 'bar'
						}
					}
				);
			}
		}
	];

	window.console.log( foo );
} );
```

(Simplified from the real code as much as I could to keep the failure there.)

**What did you expect to happen?**
WIth eslint 3.11.1 this was validating fine.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Running "eslint:main" (eslint) task

/Users/jdforrester/code/scratch/test.js
   8:6  error  Expected indentation of 16 tabs but found 5  indent
   9:7  error  Expected indentation of 17 tabs but found 6  indent
  10:7  error  Expected indentation of 17 tabs but found 6  indent
  13:6  error  Expected indentation of 16 tabs but found 5  indent

✖ 4 problems (4 errors, 0 warnings)

Warning: Task "eslint:main" failed. Use --force to continue.

Aborted due to warnings.
```

Note that moving 'foo' into an indented item makes this pass; presumably it's thinking that the indentation should be based from the last inline parameter, rather than the beginning of the function? I've [worked around it](https://gerrit.wikimedia.org/r/326170) for now but I imagine this isn't intended behaviour in the fix for #7473 ?

**Comment by not-an-aardvark** [comment]
Thanks for the report. I can reproduce this issue.

**Comment by roastlechon** [comment]
I can reproduce this too....

in this situation it prefers 39 spaces instead of 8 spaces for the first object curly brace as specified by the arrow comment
```
const mainLinks = React.Children.map(children,
      (child, i) => React.cloneElement(child,
        { // <---------------------------------------------------
          index: i,
          isHidden: isDroppedToOne ? true : !this.isVisibleIndex(i)
        }
      )
    );
```
