### ISSUE TITLE
Auto-fix support for object-property-newline

### ISSUE THREAD

**Issue by wegry** [eslint/eslint#7740]
**What rule do you want to change?**

object-property-newline

**Does this change cause the rule to produce more or fewer warnings?**

It will produce the same number of warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**

When the --fix flag is applied, code will be changed

**Please provide some example code that this change will affect:**

```js
const w = {x,
  y, z
}
```

As well as code without object shorthand.

```js
const w = {x: x,
  y: y, z: z
}
```

**What does the rule currently do for this code?**

Warns or fails depending on severity set.

**What will the rule do after it's changed?**

Take the above

```js
const w = {x,
  y, z
}
```
and transform it into
```js
const w = {
  x,
  y,
  z
}
```

**Comment by not-an-aardvark** [comment]
This seems like a good idea to me. To make it easier for other people reading the issue, would you mind filling out our [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md)?

**Comment by wegry** [comment]
**What rule do you want to change?**

object-property-newline

**Does this change cause the rule to produce more or fewer warnings?**

It will produce the same number of warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**

When the --fix flag is applied, code will be changed

**Please provide some example code that this change will affect:**

```js
const w = {x,
  y, z
}
```

As well as code without object shorthand.

```js
const w = {x: x,
  y: y, z: z
}
```

**What does the rule currently do for this code?**

Warns or fails depending on severity set.

**What will the rule do after it's changed?**

Take the above

```js
const w = {x,
  y, z
}
```
and transform it into
```js
const w = {
  x,
  y,
  z
}
```

**Comment by platinumazure** [comment]
@wegry What are your thoughts on how comments in between those properties should be handled?

Example test case:

```js
const obj = { x, // a comment
    y /* another comment */, /* yet another comment */ z
};
```

If we can get that sorted out, I'm :+1: on this.

**Comment by wegry** [comment]
```js
const obj = { 
  x, // a comment
  y /* another comment */, /* yet another comment */ 
  z 
};
```
The last comment is tricky and might play weird with `line-comment-position`.

**Comment by wegry** [comment]
```js
const obj = { 
  x, // a comment
  y /* another comment */, /* yet another comment */ 
  z 
};
```

The last comment is tricky and might play weird with `line-comment-position`.

**Comment by wegry** [comment]
With `line-comment-position: above`, the above might be rendered as

```js
const obj = { 
  // a comment
  x,
  /* another comment */ /* yet another comment */ 
  y, 
  z 
};
```

or 

```js
const obj = { 
  // a comment
  x,
  /* another comment */
  y, 
 /* yet another comment */ 
  z 
};
```
I doubt the latter is currently supported (especially by `line-comment-position`).

**Comment by platinumazure** [comment]
@wegry Note that the comma was separating those comments. With that in mind, would this rendering make sense?

```js
const obj = {
  x, // a comment
  y /* another comment */,
  /* yet another comment */ z
};
```

It's not ideal, of course, but this rendering involves the least number of token moves (e.g., comments don't move before or after other tokens). We also have other rules with auto-fix that should at least help make things better.

What do you think?

**Comment by wegry** [comment]
@platinumazure There's a certain amount of ambiguity either way. ;) But your rendering seems like it plays better, especially with line comments. There isn't currently a block comment position rule, right?

**Comment by not-an-aardvark** [comment]
I think it would be better if we just didn't perform a fix in cases where there are comments between two properties.

**Comment by not-an-aardvark** [comment]
I'll champion this proposal.

We need two more :+1:s from team members to accept it.

**Comment by vitorbal** [comment]
@not-an-aardvark we got 3 thumbs up now, so marking this as accepted!
