### ISSUE TITLE
Camel Case not picking up errors

### ISSUE THREAD

**Issue by nwhite89** [eslint/eslint#7751]
**Tell us about your environment**

* **ESLint Version:** `3.11.1`
* **Node Version:** `v4.3.2`
* **npm Version:** `2.14.12`

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "globals": {},
  "rules": {
    "no-debugger": 2,
    "no-eval": 2,
    "no-implied-eval": 2,
    "eqeqeq": 2,
    /*"newline-after-var": 2,*/
    /*"no-unused-vars": 2,*/
    /*"new-cap": 2,*/
    "no-multi-str": 2,
    "no-new-wrappers": 2,
    "no-array-constructor": 2,
    "no-new-object": 2,
    "no-dupe-keys": 2,
    "no-dupe-args": 2,
    "indent": 2,
    "no-new": 2,
    "no-redeclare": 2,
    "no-undefined": 2,
    "semi": 2,
    "camelcase": [
        2, {
            "properties": "always"
        }
    ],
    "dot-notation": [2, {
        "allowPattern": "^[a-z|1-9]+(_[a-z|1-9]+)+$"
    }],
    "curly": [
      2,
      "all"
    ],
    "space-return-throw-case": 0,
    "keyword-spacing": [
      "error",
      {
        "before": true,
        "after": true
      }
    ],
    "space-before-blocks": [
      2,
      "always"
    ],
    "space-before-function-paren": [
      2,
      "always"
    ],
    "no-empty": 2,
    "space-in-parens": [
      2,
      "never"
    ],
    "key-spacing": [
      2,
      {
        "beforeColon": false,
        "afterColon": true
      }
    ],
    "block-scoped-var": 2,
    "no-multi-spaces": 2,
    "comma-style": [
      2,
      "last"
    ],
    "operator-linebreak": [
      2,
      "after"
    ],
    "space-infix-ops": 2,
    "space-unary-ops": 2,
    "no-implicit-coercion": [
      2,
      {
        "number": true,
        "boolean": true,
        "string": true
      }
    ],
    "no-with": 2,
    "no-multiple-empty-lines": 2,
    "linebreak-style": [
      2,
      "unix"
    ],
    "quotes": [
      2,
      "single"
    ],
    "no-mixed-spaces-and-tabs": 2,
    "no-trailing-spaces": 2,
    "no-path-concat": 2,
    "comma-dangle": [
      2,
      "never"
    ],
    "brace-style": 2,
    "max-len": [
      2,
      120
    ],
    "consistent-this": [
      2,
      "$this"
    ],
    "yoda": [
      2,
      "never"
    ]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
var p = {};
p.some_non_camel = 122;
var a = p.some_non_camel;
var usage = '?some=' + safeTagReplacement(p.some_non_camel);
```

**What did you expect to happen?**
Expected an error to be raised for all three lines raising that 'some_non_camel' is not camelcase.

**What actually happened? Please include the actual, raw output from ESLint.**
```
55:19  error  Identifier 'some_non_camel' is not in camel case  camelcase

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:target" failed. Use --force to continue.
```

**Comment by platinumazure** [comment]
Is line 55 the second line in your example (`p.some_non_camel = 122;`)?

It might be that the rule intentionally focuses only on assignments/declarations, rather than uses (because you might be forced to use a non-camelcase from a third-party library, for example).

**Comment by nwhite89** [comment]
Yeah I thought this may be the case coming from `JSHint` for example it forces you at all times thought this would be the case for ESLint also the way around it would be not using dot notation such as.

```
var a = p['some_non_camel'];
```

for example?

**Comment by platinumazure** [comment]
@nwhite89 We have a separate rule, `dot-notation`, which could flag the workaround case you proposed. In general, we don't like it when rules overlap with each other, so in all likelihood, `dot-notation` would not have an exception case for if underscores were present.

You got your warning when the assignment occurred-- is that not sufficient? Are you worried about gaps as a result of this behavior?

**Comment by nwhite89** [comment]
@platinumazure thanks my personal opinion is that I would assume CamelCase to prevent the use over using it at any point that's coming from my experience with JSHint and I believe JSCS did this as well. For example in my project I noticed this with JSHint complaining when opening a file within my editor the reason the code passed ESLint is because the `p.some_non_camel` etc. came from an API. In the past this would need to be done as `p['some_non_camel']`. I understand that this wasn't the expected behaviour so indeed it's not a bug that's my oversight on coming from other Linters I'm happy for this to be closed unless you think that maybe this is something that ESLint should pick up on?

**Comment by not-an-aardvark** [comment]
Based on the [docs](http://eslint.org/docs/rules/camelcase) for the camelcase rule, it looks like the rule is only supposed to check for assigning camelcase properties rather than accessing them. Personally, I think this is the most reasonable behavior, because if an external API exposes non-camelcase properties, the code needs to be able to access it. (Using `p['some_non_camel']` instead of `p.some_non_camel` to get around the linter rule is a hack that takes advantage of unintended linter behavior, and I don't think we should encourage that.)

**Comment by gyandeeps** [comment]
I think the discussion here has reached a conclusion. So i am going to close this, feel free to reopen if you feel otherwise.
