### ISSUE TITLE
Unable to eslint init locally on windows.

### ISSUE THREAD

**Issue by kahneraja** [eslint/eslint#7752]
**Tell us about your environment**

Environment: Windows 7.
EsLint Version: v3.12.0.
Node Version: v6.9.2.
NPM Version: 3.10.9.

**What did you do? Please include the actual source code causing the issue.**

```
> npm install eslint --save-dev
> node_modules\eslint\bin\eslint.js --init
```
I expected the eslint process would begin with it's usual questions.

I got a VB script error prompt.

![image](https://cloud.githubusercontent.com/assets/5403386/21107818/fdbdd2f4-c060-11e6-822d-7feae6ebe0fc.png)

## Other notes

```
> npm install -g eslint
```

When I install eslint globally it works fine.

**Comment by platinumazure** [comment]
I assume the first character is a hash (as part of a shebang)... I thought Windows had a way of ignoring those, but I can't recall offhand what that would be.

@kahneraja Possible workaround: Can you prepend the node binary?

```shell
> node node_modules\eslint\bin\eslint.js --init
```

**Comment by thepiscean** [comment]
To run a "bin" tool locally installed by NPM, it's best to execute the file found in your local `node_modules\.bin` directory. From your package root in a Windows shell or command prompt, that would be:

```
> node_modules\.bin\eslint.cmd
```

Note: generally, when installing command-line tools with NPM it's recommended that you do so globally.

**Comment by platinumazure** [comment]
@thepiscean Note that we don't generally recommend installing ESLint globally because then it won't detect locally-installed plugins or sharable configurations. Instead, I think @kahneraja's best bet is to run this with the node binary.

**Comment by kahneraja** [comment]
_goes and tries it with node binary..._

**Comment by kahneraja** [comment]
very exciting.
this seems to make our windows and mac builds very very happy.
thank you @platinumazure and @thepiscean.
great stuff!

**Comment by ilyavolodin** [comment]
Closing as the question has been answered.

**Comment by gclinux** [comment]
when i  "eslint --init " ,after the answer show,i cannot input anythings

**Comment by besopmac** [comment]
The @gclinux tip works fine for me. Just type _eslint --init_ and go ahead.

**Comment by varunchandran333** [comment]
**_root@varunchandran:~# `npm install -g eslint`
/home/varun/.npm-global/bin/eslint -> /home/varun/.npm-global/lib/node_modules/eslint/bin/eslint.js
+ eslint@4.16.0
added 138 packages in 22.077s_**
-------------------------------------------------------------------------------------------------------------------------------------------
After this..
-------------------------------------------
when i try **`eslint --init`** , it shows 
----------------------------------------------
## No command 'eslint' found,
did you mean:
 Command 'nslint' from package 'nslint' (universe)
**eslint: command not found**
