### ISSUE TITLE
`func-call-spacing` fix creating bugs

### ISSUE THREAD

**Issue by isiahmeadows** [eslint/eslint#7787]
**Edit:** fix post to reflect real bug.

In the latest ESLint (v3.12.2), the `func-call-spacing` fix is really unhelpful for multiline call expressions (overlap with `no-unexpected-multiline`), especially when going without semicolons.

```js
// Short snippet
this.cancelled.add(request)
this.decrement(request)
(0, request.reject)(new api.Cancel())
```

These are likely meant to be separate statements, with the below being (99.99% of the time) what was meant:

```js
// Short snippet
this.cancelled.add(request)
this.decrement(request)
;(0, request.reject)(new api.Cancel())
```

Instead, `func-call-spacing` very unhelpfully fixes it to this, leading to runtime errors nearly every time in practice:

```js
// Short snippet
this.cancelled.add(request)
this.decrement(request)(0, request.reject)(new api.Cancel())
```

---

Here's the same issue, but with trailing semicolons:

Input:

```js
// Short snippet
this.cancelled.add(request);
this.decrement(request)
(0, request.reject)(new api.Cancel());
```

Meant:

```js
// Short snippet
this.cancelled.add(request);
this.decrement(request);
(0, request.reject)(new api.Cancel());
```

"Fixed":

```js
// Short snippet
this.cancelled.add(request);
this.decrement(request)(0, request.reject)(new api.Cancel());
```

-----

Any chance this could be fixed to be a little *less* over-zealous?

**Comment by isiahmeadows** [comment]
This has been causing me way too much of a productivity hit due to my editor autofixing on save.

**Comment by platinumazure** [comment]
I agree, I think `no-unexpected-multiline` is one of those rules where the correct fix can be one of two things (either add a necessary semicolon, or put the lines together). We shouldn't be assuming one or the other in the fixer. I would be :+1: for removing the fixer here and letting the user choose.

This is similar (IMO) to why we have no fixer for `no-useless-escape`. In that case, we can't know if the user wanted a backslash (in which case the escape should be doubled up) or if the escape truly was useless (in which case the backslash can be removed).

**Comment by isiahmeadows** [comment]
Actually, I'm working on narrowing down a more precise repro. It's actually a fix for another rule conflicting with `no-unexpected-multilline`.

**Comment by mysticatea** [comment]
I'm confusing.
`no-unexpected-multiline` is not fixable.

**Comment by isiahmeadows** [comment]
@mysticatea See my latest comment. I'm working on a better repro, since it's actually a conflict apparently not being detected.

**Comment by platinumazure** [comment]
So it isn't.

@isiahmeadows Looking forward to the more precise repro steps. The research failure is on me, but please do me a favor and in future open issues when you have precise repro steps, not when you're still working on them. Thanks!

**Comment by mysticatea** [comment]
Ah, it was at the same time.
Maybe `func-call-spacing`?

**Comment by isiahmeadows** [comment]
@platinumazure Will do. (I thought I had the cause nailed down initially, when I didn't.)

**Comment by platinumazure** [comment]
Ack, I didn't mean you had to close this one. Just edit your initial post when you figure it out. Thanks!

**Comment by isiahmeadows** [comment]
@mysticatea Yes.

@platinumazure Sorry!

-----

Here's a complete, fairly small repro:

```
$ cat test.js
// Short snippet
this.cancelled.add(request)
this.decrement(request)
(0, request.reject)(new api.Cancel())

$ cat config.json
{
    "rules": {
        "no-unexpected-multiline": 2,
        "func-call-spacing": [2, "never"]
    }
}

$ eslint --no-eslintrc --config config.json --fix test.js
<no output>

$ cat test.js
// Short snippet
this.cancelled.add(request)
this.decrement(request)(0, request.reject)(new api.Cancel())
```

**Comment by platinumazure** [comment]
@isiahmeadows Thanks!

I guess the proposal here would be to have the func-call-spacing fixer not fix if the CallExpression's opening parenthesis is on the next line?

I think this also could be an example?

```js
const a = foo
(function(global) {}(this));
```

So it wouldn't just be call expression chains that could be affected by this.

**Comment by isiahmeadows** [comment]
@platinumazure That would be best. I can confirm it's only function calls that are affected.

**Comment by isiahmeadows** [comment]
And yes, that is another example/

**Comment by isiahmeadows** [comment]
I updated the original post accordingly.

**Comment by mysticatea** [comment]
I think the autofix was not wrong since it does not change semantics. But surely this is similar to `no-useless-escape` rule's case as @platinumazure mentioned.
I agree that people expect `func-call-spacing` to not fix it automatically if the spaces include line terminators.

**Comment by platinumazure** [comment]
I'll work on a fix, unless someone's already on it.
