### ISSUE TITLE
Correct code usage examples incorrect?

### ISSUE THREAD

**Issue by butlermd** [eslint/eslint#7802]
I noticed this on the [website](http://eslint.org/docs/rules/prefer-spread#examples), but it appears to be this way in the [repo](https://github.com/eslint/eslint/blob/master/docs/rules/prefer-spread.md) as well. 

The "correct" examples are not showing the use of the spread operator for the `prefer-spread` rule.

**Comment by not-an-aardvark** [comment]
Thanks for bringing this up. It looks like the examples are technically correct, but I agree that it would be good to have some examples for how to use the spread operator.

Feel free to make a pull request to add some examples, if you'd like.

**Comment by butlermd** [comment]
Docs updated.
