### ISSUE TITLE
no-multiple-empty-lines is slow

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#7803]
**Tell us about your environment**

* **ESLint Version:** 3.11.1
* **Node Version:** 6.9.2
* **npm Version:** 3.8.9

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

```json
{
    "extends": ["mysticatea", "mysticatea/node", "mysticatea/mocha"]
}
```

**What did you do? Please include the actual source code causing the issue.**

Linted a large js file (4.7MB, 189,451 lines)

**What did you expect to happen?**

-

**What actually happened? Please include the actual, raw output from ESLint.**

`no-multiple-empty-lines` rule has spent about 87.4% time in the rules.

```
Rule                         |  Time (ms) | Relative
:----------------------------|-----------:|--------:
no-multiple-empty-lines      | 146929.718 |    87.4%
quote-props                  |   4130.071 |     2.5%
indent                       |   3075.474 |     1.8%
no-dupe-keys                 |   1003.162 |     0.6%
node/no-unsupported-features |    876.428 |     0.5%
no-control-regex             |    821.354 |     0.5%
key-spacing                  |    616.895 |     0.4%
no-implied-eval              |    580.792 |     0.3%
no-script-url                |    566.984 |     0.3%
no-octal-escape              |    555.832 |     0.3%
```

**Comment by not-an-aardvark** [comment]
It's possible that [this](https://github.com/eslint/eslint/blob/aafebb2958416b825283bc428d64bd96b3adf63b/lib/rules/no-multiple-empty-lines.js#L60) is the cause.

I think we can replace that logic now that `astUtils.getRangeIndexFromLocation` exists.

**Comment by not-an-aardvark** [comment]
Actually, I figured out the issue: [this line](https://github.com/eslint/eslint/blob/7122205b5cdf69de0c08753a093b3ca9a8c4d8e8/lib/rules/no-multiple-empty-lines.js#L84) is creating a new array for every line in the source file. It would be better to just us the same array with `.push` instead of `.concat`.
