### ISSUE TITLE
Conflict between new-line-after-var and new-line-before-return when use automatic fix

### ISSUE THREAD

**Issue by ipxwork** [eslint/eslint#7844]
**Tell us about your environment**

* **ESLint Version:** 3.10.2
* **Node Version:** 4.2.6
* **npm Version:** 3.10.7

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

```js
{
  "root": true,
  "env": {
    "browser": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaFeatures": {
      "impliedStrict": true
    }
  },
  "rules": {
    "newline-after-var": [
      "error",
      "always"
    ],
    "newline-before-return": "error"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
i use automatic fix (--fix) with rules **newline-after-var** and **newline-before-return** 

```js

    vm.interventionStatus = function (btnNameProperty) {
      var btnStates = {
        INTERVENTION_CANCEL: ['CREATED', 'ADDRESSED', 'BANK_CARD_DATA_VALIDATED', 'ACCEPTED', 'LATER_ACCEPTED', 'VALIDATION_CREATED_BY_PARTNER_IMMEDIATE'],
        INTERVENTION_ASSIGN_SP: ['VALIDATED', 'PUBLISHED']
      };

      if (typeof vm.intervention !== 'undefined') {
        var status = vm.intervention.interventionStatus;
        return btnStates[btnNameProperty].indexOf(status) !== -1;
      }
    };

```

**What did you expect to happen?**
between **var** and **return** need to be only one blank line

```js

    vm.interventionStatus = function (btnNameProperty) {
      var btnStates = {
        INTERVENTION_CANCEL: ['CREATED', 'ADDRESSED', 'BANK_CARD_DATA_VALIDATED', 'ACCEPTED', 'LATER_ACCEPTED', 'VALIDATION_CREATED_BY_PARTNER_IMMEDIATE'],
        INTERVENTION_ASSIGN_SP: ['VALIDATED', 'PUBLISHED']
      };

      if (typeof vm.intervention !== 'undefined') {
        var status = vm.intervention.interventionStatus;

        return btnStates[btnNameProperty].indexOf(status) !== -1;
      }
    };

```
**What actually happened? Please include the actual, raw output from ESLint.**
between **var** and **return** is added 2 blank lines instead of one

```js

    vm.interventionStatus = function (btnNameProperty) {
      var btnStates = {
        INTERVENTION_CANCEL: ['CREATED', 'ADDRESSED', 'BANK_CARD_DATA_VALIDATED', 'ACCEPTED', 'LATER_ACCEPTED', 'VALIDATION_CREATED_BY_PARTNER_IMMEDIATE'],
        INTERVENTION_ASSIGN_SP: ['VALIDATED', 'PUBLISHED']
      };

      if (typeof vm.intervention !== 'undefined') {
        var status = vm.intervention.interventionStatus;


        return btnStates[btnNameProperty].indexOf(status) !== -1;
      }
    };

```

**Comment by platinumazure** [comment]
Definitely a bug, but it's not immediately obvious how we should resolve this. (Basically, we'd have to decide that one of the rules should "give way to" the other, for example having `newline-before-return` completely ignore returns immediately preceded by VariableDeclaration statements or vice versa.)

As a short-term workaround, you could use the [`no-multiple-empty-lines`](http://eslint.org/docs/rules/no-multiple-empty-lines) rule, which is also fixable; by using all three rules here, the net result should be what you're expecting.

**Comment by not-an-aardvark** [comment]
I'm a bit confused about how both fixes got applied. I would have expected the fixes to conflict with each other because they both modify the same location, resulting in only one fix getting applied and everything working correctly.

**Comment by nzakas** [comment]
Yeah, I had the same reaction. It seems like the fixes would overlap, so only one would be applied, and then the next time around the rules wouldn't trigger, so not fixes would be applied. There must be a difference in the fix location between the two rules?

**Comment by alberto** [comment]
The location is indeed different:

```
  8:5  error  Expected blank line after variable declarations  newline-after-var
  9:5  error  Expected newline before return statement         newline-before-return
```

**Comment by alberto** [comment]
I don't think adding an exception to any of the rules is the right solution here. It looks similar to https://github.com/eslint/eslint/issues/7928#issuecomment-277595227
