### ISSUE TITLE
Refactor prototypes to ES6 classes

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#7849]
In the spirit of https://github.com/eslint/eslint/issues/6407 and https://github.com/eslint/eslint/issues/7810#issuecomment-268941225, I was thinking we could update the codebase to use ES6 classes. I'd love to put the "help wanted" label on this as I think it could be a great first contribution for new contributors.

Here's a list of places where these changes could be made (please let me know if I missed any!):
- [x] [lib/config](https://github.com/eslint/eslint/blob/master/lib/config.js#L187)
- [x] [lib/file-finder](https://github.com/eslint/eslint/blob/master/lib/file-finder.js#L44)
- [x] [lib/ignored-paths](https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js#L80)
- [x] [lib/rule-context](https://github.com/eslint/eslint/blob/master/lib/rule-context.js#L76)
- [x] [lib/code-path-analysis/code-path-analyzer](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/code-path-analyzer.js#L576)
- [x] [lib/code-path-analysis/code-path-segment](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/code-path-segment.js#L78)
- [x] [lib/code-path-analysis/code-path-state](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/code-path-state.js#L230)
- [x] [lib/code-path-analysis/code-path](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/code-path.js#L27)
- [x] [lib/code-path-analysis/fork-context](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/fork-context.js#L108)
- [x] [lib/code-path-analysis/id-generator](https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/id-generator.js#L22)
- [x] [lib/config/autoconfig](https://github.com/eslint/eslint/blob/master/lib/config/autoconfig.js#L72)
- [x] [lib/config/config-rule](https://github.com/eslint/eslint/blob/master/lib/config/config-rule.js#L182)
- [x] [lib/util/comment-event-generator](https://github.com/eslint/eslint/blob/master/lib/util/comment-event-generator.js#L77)
- [x] [lib/util/module-resolver](https://github.com/eslint/eslint/blob/master/lib/util/module-resolver.js#L38)
- [x] [lib/util/node-event-generator](https://github.com/eslint/eslint/blob/master/lib/util/node-event-generator.js#L27)
- [x] [lib/util/rule-fixer](https://github.com/eslint/eslint/blob/master/lib/util/rule-fixer.js#L39)

**Comment by kaicataldo** [comment]
Sorry, got my tabs mixed up 😅

**Comment by gyandeeps** [comment]
I already started the work:

* https://github.com/eslint/eslint/pull/7847
* https://github.com/eslint/eslint/pull/7846

**Comment by kaicataldo** [comment]
Oh wow, I actually hadn't seen your PRs...Great minds, eh?

**Comment by skindle** [comment]
Hello, interested in porting rule-fixer to a es6 class. I forked and pushed a commit but I am a bit overwhelmed by what is expected in the pull request message from me :D (which is a good thing) any pointers?

**Comment by qlaire** [comment]
@kaicataldo I've found some more places where changes could be made:

- [ ] lib/cli-engine.js
- [ ] lib/testers/rule-tester.js
- [ ] lib/util/source-code-fixer.js
- [ ] lib/util/source-code.js
- [ ] lib/util/traverser.js
- [ ] tests/lib/config-file.js

Please let me know if I should go ahead and work on those as well.

**Comment by gyandeeps** [comment]
@qlaire Thanks for taking the time.
To start, lets go with what we have in the issue (unchecked) because some of the file we have deliberately ignored because they are exposed on the API.
Let us know if you have any question or need any help to get started. Feel free to stop by our chat room for quick response: https://gitter.im/eslint/eslint?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by kaicataldo** [comment]
@qlaire Thanks for contributing! Here's some more info for some context around what @gyandeeps mentioned: https://github.com/eslint/eslint/pull/7846#discussion_r94493456

**Comment by qlaire** [comment]
@gyandeeps @kaicataldo thanks, both!

**Comment by qlaire** [comment]
@kaicataldo PR in: #7891 😄

**Comment by oksas** [comment]
Looks like @qlaire's PR #7891 takes care of all of this except `lib/util/glob`; is there anyone already working on that one? I would love to take a stab at it if not!

**Comment by vedatmahir** [comment]
Hi, @oksas!
I've already started working on that file.

**Comment by kaicataldo** [comment]
Thanks everyone for contributing!

**Comment by kaicataldo** [comment]
It looks like we're done with all the ones in the original issue (lib/util/glob turned out to be a case where should leave it as is), but would we like to update the issue with any @qlaire's suggestions? I believe `lib/cli-engine.js` and `lib/testers/rule-tester.js` are out because they're part of the public API, but how about the other suggestions?

**Comment by kaicataldo** [comment]
I believe this issue has been completed. If there are any other instances where we can convert to ES6 classes, please feel free to make a new issue/PR.
