### ISSUE TITLE
prefer-const with --fix doesn't fix multiple destructuring assignments

### ISSUE THREAD

**Issue by afhole** [eslint/eslint#7852]
**Tell us about your environment**

* **ESLint Version:** v3.12.2
* **Node Version:** v7.3.0
* **npm Version:** 4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

```
{
    "root": true,
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "parser": "babel-eslint",
    "plugins": [
        "react"
    ],
    
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        }
    },
    
    "env": {
        "es6": true,
        "browser": true
    },

    "settings": {
        "react": {
            "pragma": "React"
        }
    },

    "rules": {
        "semi": ["error", "always"],
        "no-param-reassign": [2, {"props": true }],
        "react/jsx-no-undef": 2,
        "react/jsx-pascal-case": 2,
        "react/jsx-key": 2,
        "no-unused-vars": [1, {"args": "all", "argsIgnorePattern": "^_"}],
        "eqeqeq": 1,
        "eol-last": 1,
        "quotes": [1, "single"],
        "jsx-quotes": [1, "prefer-double"],
        "no-trailing-spaces": 1,
        "semi-spacing": 1,
        "no-console": 1,
        "no-multi-spaces": 1,
        "block-spacing": 1,
        "arrow-body-style": [1, "as-needed"],
        "space-before-function-paren": 1,
        "react/jsx-curly-spacing": [1, "always"],
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "prefer-const": 1,
        "react/prop-types": 1,
        "react/display-name": 1
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
let { list } = this.props;
let { onClick, value } = this.props;
```

**What did you expect to happen?**
```js
const { list } = this.props;
const { onClick, value } = this.props;
```

**What actually happened? Please include the actual, raw output from ESLint.**
Was `--fix`ed into:
```js
const { list } = this.props;
let { onClick, value } = this.props;
```

**Comment by vitorbal** [comment]
Thanks for the report, this definitely looks like a bug. Just to be sure, if you run eslint without the `--fix` flag on the snippet you provided, do you get 2 errors reported or just one?

**Comment by afhole** [comment]
Two - the reporting is fine. Thanks! :)

**Comment by platinumazure** [comment]
I'm vaguely remembering we had to make a change to the rule to get around two `let` declarations being allowed in some version of Node. I haven't got time to investigate but I'm wondering if that change is now inadvertently breaking destructured assignments?

**Comment by not-an-aardvark** [comment]
@platinumazure I think you're referring to https://github.com/eslint/eslint/pull/7717. I haven't tested reverting it, but I don't think that would cause this issue, because that change checks for multiple declarations of a particular variable, whereas this issue appears to be related to multiple declarations of different variables in a particular declarator.
