### ISSUE TITLE
Add --fix support for no-else-return

### ISSUE THREAD

**Issue by xdumaine** [eslint/eslint#7863]
**What version are you using?**
3.12.2

**What did you do?**
Ran eslint with `no-else-return` enabled and the `--fix` flag

**What happened?**
It didn't fix the errors!

**What did you expect to happen?**
It to fix the errors!

I'll be opening a PR for this momentarily, to discuss the change.

**Comment by not-an-aardvark** [comment]
This seems like a useful enhancement to me. :+1:

**Comment by not-an-aardvark** [comment]
@eslint/eslint-team Can we get two more :+1:s on this issue so that we can accept it? There is already an implementation ready to go.

**Comment by mikesherov** [comment]
:+1:

**Comment by markelog** [comment]
👍
