### ISSUE TITLE
`eol-last` and `no-trailing-spaces` --fix interfere with each other

### ISSUE THREAD

**Issue by feross** [eslint/eslint#7866]
**Tell us about your environment**

* **ESLint Version:** 3.12.2
* **Node Version:** 7.3.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
{
    "eol-last": 2,
    "no-trailing-spaces": 2
}
```

**What did you do? Please include the actual source code causing the issue.**
**What did you expect to happen?**
**What actually happened? Please include the actual, raw output from ESLint.**

If there are spaces on the last line, `--fix` will remove the spaces, but still add a newline. 

In the following example I added characters to visualize newlines and spaces. An empty line is marked with a `_` (underscore) and a space is marked with a `.` (dot).

## Correct:
```js
console.log('test')
```
becomes
```js
console.log('test')
_
```

## Wrong:
```js
console.log('test')\n
..
```
becomes
```js
console.log('test')
_
_
```

(Originally reported here: https://github.com/feross/standard/issues/733)

**Comment by platinumazure** [comment]
What do you get for this case?

```js
console.log('test')..\n
```

**Comment by johannes-z** [comment]
```javascript
console.log('test')..\n
```
becomes
```javascript
console.log('test') // all whitespaces were removed.
```

**Comment by feross** [comment]
Yes, all whitespaces are removed, and the `/n` remains. So it becomes:

```js
console.log('test')\n
```

**Comment by alberto** [comment]
If you don't want multiple empty lines at the end of file, you should use `no-multiple-empty-lines` with `{maxEOF: 1}`

**Comment by feross** [comment]
@alberto We're already doing `"no-multiple-empty-lines": [2, { "max": 1 }]` which sets `maxEOF` and `maxBOF`.

**Comment by feross** [comment]
Indeed, changing the setting to:

```js
"no-multiple-empty-lines": [2, { "max": 1, "maxEOF": 1, "maxBOF": 1 }]
```

Does not solve the problem. The fixer still adds an extra newline at the end.

**Comment by not-an-aardvark** [comment]
Correction: `no-multiple-empty-lines` does not count the trailing line ending in a file as a new line, so the correct config is `maxEOF: 0`.

**Comment by feross** [comment]
@not-an-aardvark Ah, I think you're right.

**Comment by feross** [comment]
Closing, as I don't think there's an ESLint bug here anymore.

Cheers, @not-an-aardvark!
