### ISSUE TITLE
Providing a mechanism to perform unsafe fixes

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7873]
At the moment, core rules only autofix problems if they can guarantee that the fixes will never break the code. This is a useful guarantee, because people can run `--fix` without worrying about whether their code will break. However, it's also an unfortunate roadblock in some situations. Rules like [`sort-keys`](http://eslint.org/docs/rules/sort-keys) and [`no-return-await`](http://eslint.org/docs/rules/no-return-await) will never be fixable under the current system, because autofixing these rules could break the code in exceedingly unusual cases (even though the autofix would be convenient for the user in the vast majority of cases).

To make autofix more useful for these cases, I think we should consider adding a way for a rule to suggest an "unsafe" fix. This has been brought up several times in previous issues (e.g. https://github.com/eslint/eslint/issues/7714). While I'm not sure about what the behavior should be here (or if it's worth doing at all), I think it's at least worth discussing the idea.

First, here are some general design constraints for unsafe fixes:

* A rule should be able to specify that its fixes are unsafe, preferably on the level of an individual fix (rather than applying the label to every fix produced by the rule).
* It should still be possible to quickly and easily run "safe" fixes with no additional interaction.

---

Given those constraints, I see two possible approaches. The first approach is to have a CLI flag like `--unsafe-fix` that allows the user to opt-in to unsafe fixes. The second approach is to interactively prompt the user about each unsafe fix.

### `--unsafe-fix` CLI flag

**Pros**:

* There is precedent for this; for example, [Uglify](https://github.com/mishoo/uglifyjs2) has an opt-in flag for unsafe minification.
* This is the easiest option, assuming everything goes well and it doesn't break your code.

**Cons**:

* This might cause subtle bugs in the user's code. Even if the user is kind of opting into it and it happens rarely, I'm still not entirely comfortable with that.
* Some fixes might be more "unsafe" than others. If a user has lots of rules enabled and they're worried about unsafe fixes, they might only want to apply some unsafe fixes, e.g. if they read the docs for a few rules and confirm that those particular fixes won't break their code. (Possible solution: we could allow the user to opt-in to unsafe fixes for particular rules with the flag.)

### Interactive prompts for unsafe fixes

**Pros**:

* This is much less likely to break the user's code.
* The user can easily choose to apply only specific fixes.

**Cons**: 

* This is much less convenient for the user.
* In order to be worthwhile at all, it would have to be significantly faster than fixing the code manually.
* The user might be confused about why a particular fix is unsafe -- some fixes are unsafe for very subtle reasons. In order to clarify this, a rule would probably have be able to provide an explanation somehow.

### No changes (i.e. keep the current behavior)

**Pros**:

* The UI remains simple.
* ESLint never breaks anyone's code.

**Cons**:

* There is a lot of missed potential for autofixes that could save the user's time.

---

I'm interested in hearing feedback (from both the team and the community) on these options. Do you agree with my analysis of the available options? Is there a solution I've missed? Is it worth adding a feature like this?

**Comment by ilyavolodin** [comment]
@not-an-aardvark I think allowing people to do unsafe fixes from the command line will lead to a lot of complains where ESLint will fix and break user's code in some low traffic file and that file will get deployed in production. I think it's much better to handle unsafe fixes through API only (so that editors could use them). I think your interactive prompt suggestion is the same as my "recommendations" that I mentioned here: https://github.com/eslint/eslint/issues/6733#issuecomment-234656842

**Comment by aboyton** [comment]
I agree that there's definitely a place for tools that do unsafe fixes. As a way of example I've used (and contributed to, so I'm biased) a tool called [lebab](https://github.com/lebab/lebab) made by @nene which does a bunch of transformations to turn ES5 code into idiomatic ES6 code. Some of it's transformations do the same as auto-fixers in ESLint (like `var` to `let` or `const` done by the rule `no-var`), and others are potentially unsafe but really useful (like the `default-param` transformation).

The documentation for lebab states:
> The recommended way of using Lebab is to apply one transform at a time, read what exactly the transform does and what are its limitations, apply it for your code and inspect the diff carefully.

The idea of turning ESLint into a more generic tool useful for an editor to do potentially unsafe transformation (similar say to what lebab does and suggested in #6733) I think would be a great way forward, although I wonder if having a CLI mode as well could be useful as well if done like lebab, one type of transformation at a time.

**Comment by nene** [comment]
Well, regarding this warning in Lebab documentation: it doesn't really assure that people follow the advice. I get reports from time to time about uses of Lebab where people blindly apply lots of these unsafe transforms together and expect good results.

However I have to point out that the spectrum of safe & unsafe isn't really a binary thing:

- Fixes that should be completely safe, can cause bugs when somebody e.g. relies on the exact size of a file.
- A fix for `sort-imports` can cause bugs when there's a dependency on the order of execution between imported modules.
- A fix for `prefer-template` isn't really safe. Lebab actually has the same transform, but classifies it as unsafe. See: https://github.com/lebab/lebab/issues/107
- A fix for `sort-keys` can encounter both safe-to-fix (an object with plain literals) and unsafe-to-fix code (an object with function calls). The approach that Lebab often takes is to only perform changes that it determines as safe, and print out warnings abut the changes it won't be willing to do, letting the user perform them by himself.

**Comment by nzakas** [comment]
I'm really against doing unsafe fixes. I don't see there being enough value to offset the potential damage such a feature could cause, let alone the bugs we will have filed and have to deal with. 

There are plenty of other tools people can use to automate changes to their codebase, I don't think this is something ESLint should attempt to do.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by tsheaff** [comment]
I see that this was closed last month.  For what it's worth, I'm a big proponent of the Interactive prompts proposal.

In my case, our large codebase has highly inconsistent usage of camelCase and snake_case, and even though a `--fix` option for `camelcase` has some subtle edge-cases that may cause bugs, the vast majority of these would actually be much *safer* to do with an automatic tool.

@nzakas you mention other tools that automatically make complex changes to a js codebase, but I'm not familiar with any that are nearly as reliable as eslint. Any specific packages you had in mind?

My two cents strongly in favor of the `Interactive prompts` option — would save me any my team a lot of time and almost certainly reduce the number of bugs in our migration, not increase it.
