### ISSUE TITLE
Indent expects incorrect indentation level if case contains block

### ISSUE THREAD

**Issue by cowwoc** [eslint/eslint#7892]
**Version of ESLint**
3.4.0

**The problem you want to solve.**

Given the configuration:

```
"indent": [
	"error",
	"tab",
	{
		"SwitchCase": 1
	}
],
```

and the code:

```
switch (Utilities.getTypeName(exception))
{
	case "Undefined":
		throw new TypeError("exception may not be undefined");
	case "Function":
		if (Utilities.extends(exception, Error))
			break;
	// Otherwise, fallthrough
	default:
	{
		throw new TypeError("exception must be an Error.\n" +
			"Actual: " + Utilities.getTypeName(exception));
	}
}
```

The rule complains:

`65:3   error  Expected indentation of 3 tab characters but found 2               indent`

on the line containing the opening brace of the `default` block. I am expecting an indentation of 2. Removing the braces (block) fixes the problem (indentation level of 2 is expected)

**Your take on the correct solution to problem.**
Nesting a block inside a case statement should not affect its expected indentation level.

**Comment by not-an-aardvark** [comment]
I can reproduce this. It is fixed by https://github.com/eslint/eslint/pull/7618.
