### ISSUE TITLE
[request] white-label features

### ISSUE THREAD

**Issue by mightyiam** [eslint/eslint#7894]
FWIW: v3.13.1

@feross @Flet

Following the success of [standard](http://standardjs.com/), more curated and re-branded ESLint linters have showed up. It seems that most of them are using [standard-engine](https://github.com/Flet/standard-engine)—a kind of ESLint whitelabel wrapper.

The attempt at white-labeling is not entirely successful, because of at least these things:
- ESLint reads only branded `package.json` field (`eslintConfig`)
- ESLint reads only branded inline comments (`/* eslint-disable */`)
- ESLint reads only branded ignore files (`.eslintignore`)

Is ESLint open to a feature, where `require('./package.json').standardConfig`, `/* standard-disable */` and `.standardignore` are be possible?

Perhaps through a `CLIEngine` option `whiteLabel` (e.g. `whiteLabel: 'standard'`)?

I imagine that it could be natural for the developers of ESLint to not see the value of tools like standard. If this is so for anyone, then please, try to understand, because people use these tools daily and eventually, they are your end users, as well.

**Comment by nzakas** [comment]
I'm not sure I understand the value proposition here. To me, there's value in having common configuration file names and comments, as it allows people to easily transition between tools as necessary and lets people know they are part of a larger ecosystem. Obscuring that seems like it would do more harm to end users than good as the number of ways to configure the same thing explodes.

**Comment by mightyiam** [comment]
I tend to agree with @nzakas. A white-label would hurt end-users and is not necessary for the concept of a curated linter. [It is transparent](http://standardjs.com/#how-do-i-hide-a-certain-warning) and should be transparent that the backend is ESLint.

I'm attempting to make the correct abstraction in https://github.com/mightyiam/curated-linter. Feedback on that will be welcomed.
