### ISSUE TITLE
no-extra-boolean-cast --fix

### ISSUE THREAD

**Issue by sprzybylski** [eslint/eslint#7912]
* **ESLint Version:**
3.13.1
* **Node Version:**
7.4.0
* **npm Version:**
4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```
{
  "rules": {
    "no-extra-boolean-cast": "error"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
run ```eslint --fix``` on the code below:
```js
function baz(foo)  { return !Boolean(foo && foo.bar); }
```
**What did you expect to happen?**
I expect to "Boolean" to be removed from the code.

**What actually happened? Please include the actual, raw output from ESLint.**
The brackets get dropped causing change of the behaviour of my code.
```js
function baz(foo)  { return !foo && foo.bar; }
```

**Comment by sprzybylski** [comment]
I've prepare a bit naive fix. It's my first time diving into this codebase. Let me know how can I improve it.

**Comment by platinumazure** [comment]
@sprzybylski The first thing you can do is open a pull request, so we have GitHub's review tooling available. :smile: If you haven't created one before, you can look [here](https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request) for GitHub's instructions. Find one of us in the [ESLint Gitter chat room](https://gitter.im/eslint/eslint) if you get stuck. Thanks!

**Comment by platinumazure** [comment]
Dang it, accidentally deleted my earlier comment.

@sprzybylski If you could create a pull request for us to review, that would be great, thanks!
