### ISSUE TITLE
Support different working directories in cache JSON

### ISSUE THREAD

**Issue by jakubzitny** [eslint/eslint#7931]
* **ESLint Version: latest**
* **Node Version: 6**
* **npm Version: 3**

Hi, I am trying to speed up `eslint` on our CI. We have the cache turned on, however, different CI tasks have different locations so the cache does not work across different CI builds. I think it could be cool to be able to share the cache between different working directories.

Right now it is not possible because the file cache keys are absolute paths of the file that is being cached. Do you think it would make sense to (optionally) change the keys to relative paths from working directory?

Developers can have different clones of the same repository in multiple paths and most of the files go without change for a long time. CI tasks also run in different locations, but most of the files do not change, so the caching could speed `eslint` up.

I know this opens up a lot of questions on changing the cache json, e.g. when multiple lints are running in parallel. One of the solutions could be splitting the cache for every file into separate cache file in defined directory and reading all of them before the linting starts. Using CI cache might be another solution for the CI speed, but I am curious what do you think about this proposal anyway.

**Comment by not-an-aardvark** [comment]
I don't think it's feasible to do this, because the cache works by checking file mtimes, which are not shared between different clones of the same repository. Using a relative cache path could cause ESLint to return incorrect results.

**Comment by jakubzitny** [comment]
Yeah, when I thought about it more I realised that there might be incorrect results.

The solution for speeding up eslint might be manually (in a script) checking the changed files for a specific branch/commit(s) and linting only these.


Closing.
