### ISSUE TITLE
why eslint dosen't support .vue extensions and webpack alias?

### ISSUE THREAD

**Issue by zp1112** [eslint/eslint#7932]
**Tell us about your environment**

* **ESLint Version:**3.13.1
* **Node Version:**v6.9.0
* **npm Version:**3.10.8
* **webpack Version:**1.14.0
* **vue Version:**2.1.9

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: [path.resolve(__dirname, '../app/index.js')],
  output: {
    path: path.resolve(__dirname, '../output/static'),
    publicPath: 'static/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[chunkhash].js'
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.vue'],
    alias: {
      vue: 'vue/dist/vue.js',
      components: path.resolve(__dirname, '../app/components')
    }
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: '../index.html',
      template: path.resolve(__dirname, '../app/index.html'),
      inject: true
    })
  ]
};




```

**What did you do? Please include the actual source code causing the issue.**

```js
// using extensions['.vue'] error png1
import Vue from 'vue';
import App from './components/app';

// using alias error png2
import Vue from 'vue';
import App from 'components/app.vue';

```

png1
![image](https://cloud.githubusercontent.com/assets/14245159/22013948/769cd3d2-dcd6-11e6-88af-8eeef9ddd805.png)

png2
![image](https://cloud.githubusercontent.com/assets/14245159/22013987/9351b326-dcd6-11e6-8d59-4a993670baab.png)

**What did you expect to happen?**

no eslint error

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by not-an-aardvark** [comment]
It looks like the `import/no-unresolved` rule is reporting an error. This is a rule from the `eslint-plugin-import` plugin, which is not maintained by the ESLint team. I would recommend reporting an issue on the [eslint-plugin-import repo](https://github.com/benmosher/eslint-plugin-import) instead.

**Comment by zp1112** [comment]
@not-an-aardvark thx

**Comment by zp1112** [comment]
@not-an-aardvark I fixed it.
![image](https://cloud.githubusercontent.com/assets/14245159/22048968/6d425ac4-dd6b-11e6-9f09-856f43babd2c.png)

**Comment by not-an-aardvark** [comment]
@zp1112 Great! I'll close this issue then.
