### ISSUE TITLE
When running eslint with npm script, npm throws error.

### ISSUE THREAD

**Issue by stsiarzhanau** [eslint/eslint#7933]
**Tell us about your environment**
Windows_NT 10.0.14393
ESLint is installed as devDependency

* **ESLint Version:** v3.13.1
* **Node Version:** v6.9.1
* **npm Version:** v3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**
Dead simple `.eslintrc.js` in the root folder:
```
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'script',
  },
  rules: {
    'no-unused-vars': 2,
    'no-console': 1
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
Dead simple test file in the root folder to emit both error and warning.
```js
const a = console.log('');
```

**What did you expect to happen?**
I should see standard ESLint output (lint error, warning, etc.)

**What actually happened? Please include the actual, raw output from ESLint.**
1. When I run eslint directly from CL with  `node_modules\.bin\eslint tst.js` I get expected output:
```
λ node_modules\.bin\eslint tst.js

C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js
  1:9   error    'a' is assigned a value but never used  no-unused-vars
  1:13  warning  Unexpected console statement            no-console

✖ 2 problems (1 error, 1 warning)
```

2. But when I run simple npm script...
```
"scripts": {
    "lint": "eslint tst.js"
}
```
... I get standard ESLint at first and then **npm error**:

```
λ npm run lint

> webpack-react-redux-starter@0.1.0 lint C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter
> eslint tst.js


C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js
  1:9   error    'a' is assigned a value but never used  no-unused-vars
  1:13  warning  Unexpected console statement            no-console

✖ 2 problems (1 error, 1 warning)


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-redux-starter@0.1.0 lint: `eslint tst.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-react-redux-starter@0.1.0 lint script 'eslint tst.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint tst.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\npm-debug.log
```
Output in debug mode with `"lint": "eslint tst.js --debug"`:

```
λ npm run lint

> webpack-react-redux-starter@0.1.0 lint C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter
> eslint tst.js --debug

  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +31ms
  eslint:ignored-paths Looking for ignore file in C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter +0ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cli-engine Processing C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js +0ms
  eslint:cli-engine Linting C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js +0ms
  eslint:config Constructing config for C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\.eslintrc.js +0ms
  eslint:config-file Loading JS config file: C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\.eslintrc.js +0ms
  eslint:config Using C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\.eslintrc.js +16ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:cli-engine Linting complete in: 54ms +38ms

C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js
  1:7   error    'a' is assigned a value but never used  no-unused-vars
  1:11  warning  Unexpected console statement            no-console

✖ 2 problems (1 error, 1 warning)


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-redux-starter@0.1.0 lint: `eslint tst.js --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-react-redux-starter@0.1.0 lint script 'eslint tst.js --debug'.npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint tst.js --debug
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-redux-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-redux-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\npm-debug.log
```

3. If I change my tst.js code so it triggers only lint warning I get expected output (**no npm error**):

```
λ npm run lint

> webpack-react-redux-starter@0.1.0 lint C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter
> eslint tst.js


C:\OpenServer\domains\EXAMPLES\webpack-react-redux-starter\tst.js
  1:1  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)
```
It's not a big problem, when I just want to lint some files.
But it becomes a problem when I chain my `lint` task with other tasks, cause all subsequent tasks don't run after error occurs.

P.S. There's closed issue #7402 related to the same problem. I wrote there too. But since get no responce file a new one.

**Comment by stsiarzhanau** [comment]
I've just upgraded Node.js to latest v6.9.4 LTS (which ships with npm v3.10.10) and tried the same steps as above.
I also tried different terminals: **cmder, gitBash, Windows default console, Wimdows PowerShell**.
Nothing have changed. I still have **npm error** when lint error occurs.

**Comment by BYK** [comment]
You get the npm error because when your code has linting errors in it, ESLint returns with a non-zero exit code indicating a problem running the script.

**Comment by stsiarzhanau** [comment]
So, it's considered normal and ESLint behaves exactly the same on Unix machines?

**Comment by platinumazure** [comment]
Yes, npm won't run any later scripts if an earlier script exits with a non-zero exit code.

**Comment by stsiarzhanau** [comment]
I'm not very happy to see that ugly NPM errors.
But if it is considered normal than OK.
Thanks for response.

**Comment by platinumazure** [comment]
@stsiarzhanau Unfortunately it's an npm issue, not ESLint. I agree it would be nice to be able to suppress that output. But even if you create a script that does `exit 1`, rather than running ESLint or a different tool, you'll still see that output.

**Comment by stsiarzhanau** [comment]
Sorry about possibly dumb question. But is it absolutely necessary to exit with non-zero code when we have lint error?

[eslint-loader](https://github.com/MoOx/eslint-loader) for example have an option `emitWarning`. If I set it to `true` I can see lint errors marked as errors and warnings as warnings, but package itself as I understand don't throw errors.

**Comment by platinumazure** [comment]
@stsiarzhanau ESLint will exit with non-zero status code if any errors are reported, by design. You can work around this in npm scripts by using a script like: `eslint .; exit 0` (although it means that any scripts which call that script will continue to execute on lint failure).

**Comment by i3games** [comment]
`npm run lint -s` displays the linter output and silences the npm output.

**Comment by someok** [comment]
or use this:
> "lint": "eslint app/;exit 0"

**Comment by jodriscoll** [comment]
@i3games any chance you could provide documentation as to what `-s` "does" and where it's outlined in the npm docs? I just poked around their docs and wasn't able to find much on this argument.

It solves the issue with the error code 1 (when executing ESLint through an npm script definition), but I just attempted to better understand what this argument it is "doing" and am struggling.

**Constructive feedback:**
I've learned that far too often solutions are provided to individual "familiar" with the subject matter –
 however, little to no reference is typically provided, with people copy+pasting the suggestive solution and immediately moving on (obviously after +1'ing the comment).

It's similar a great paper/thesis/term paper/etc., and then providing zero references to what made it _great_.
