### ISSUE TITLE
is it possible to customize a subset of rules are ran with --fix

### ISSUE THREAD

**Issue by dcartertwo** [eslint/eslint#7940]
As a question (not feature request) I did not see anything in the docs indicating whether or not we can define which rules are auto fixed with --fix.  Is this possible? For example, if my eslintrc contains 10 rules, but I only want 3 of them to be auto fixed can this be done?

**Comment by not-an-aardvark** [comment]
It's not possible to do this directly, but you can use this as a workaround:

```
eslint yourFile.js --fix --no-eslintrc --rule 'first-rule: error' --rule 'second-rule: error' --rule 'third-rule: error'
```

Out of interest, why do you only want 3 of the rules to be autofixed?

**Comment by dcartertwo** [comment]
thanks for the speedy reply.  that was a contrived example, my situation is actually the opposite.  we have a very large eslintrc and want to explicitly define which are autofixed, while removing a few that we don't.  i know --fix only fixes the ones it can, but is there a list somewhere of which ones it will attempt to?

**Comment by ilyavolodin** [comment]
@dcartertwo Yes. You can see all of the fixable rules on this page: http://eslint.org/docs/rules/ they are marked with "wrench" icon. If you want to fix most (but not all) of the rules, I suggest you create two config files, one for linting and one for fixing. After that you can run `eslint --fix -c fixconfig.json --no-eslintrc yourpath`.

**Comment by dcartertwo** [comment]
Awesome, thank you.  Was not expecting to get an answer so quickly.
