### ISSUE TITLE
"  78:6  error  Don't use process.exit(); throw an error instead  no-process-exit"

### ISSUE THREAD

**Issue by tj** [eslint/eslint#795]
wat, this shouldn't even be a rule haha

**Comment by olalonde** [comment]
Could this rule be only disabled on files that start with `#!/usr/bin/env node` or that are `+x`?

**Comment by IanVS** [comment]
@olalonde In `v1.0` of ESLint, all rules are turned off by default.  You will need to explicitly set the rule, or extend a configuration which has it turned on.  

If you're asking for a new feature feel free to open an issue, but I believe the best way to handle individual cases like executables is with a [configuration comment](http://eslint.org/docs/user-guide/configuring#configuring-rules) at the top of the file.

**Comment by olalonde** [comment]
@IanVS ok thanks that's what I ended up doing. By the way, I just did a `npm install -g eslint` but `eslint --version` returns `v0.24.1`, why is that?

**Comment by ilyavolodin** [comment]
We marked version 1.0.0-rc1 as `next` in npm, and 0.24.1 as `latest`. So if you install eslint using command above, you get latest stable version. You'll have to install with the following command `npm install -g eslint@next` to get 1.0 RC. We had some complaints from people that 1.0RC was marked as latest.

**Comment by olalonde** [comment]
@ilyavolodin oh thanks! didn't know about that npm feature.

**Comment by jtwebman** [comment]
It would have been at least nice if @nzakas would give an example of why this is on by default.

**Comment by IanVS** [comment]
@jtwebman, it is no longer on by default.  What version of ESLint are you using?

**Comment by jtwebman** [comment]
@IanVS I am using the version that installs with npm install eslint -g 1.7.3 but I am using the atom.io add in so let me make sure it is using the correct one.

**Comment by IanVS** [comment]
The default which comes with the atom linter is still on the old `0.24` version, and I've heard reports that the `use global` option doesn't always work correctly.
