### ISSUE TITLE
Scheduled Release for January 20, 2017

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#7956]
The scheduled release on Friday, January 20, 2017 is assigned to:

@btmills 
@gyandeeps

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by btmills** [comment]
v3.14.0 has been released. Please merge only semver-patch changes until we have either done a patch release or determined that one is not necessary.

We encountered an issue during this release with the Jenkins build. It appeared to be failing after `npm install`, and the last log entry had to do with PhantomJS. @gyandeeps changed the build script in Jenkins to remove the `--silent` flag, which showed us errors unpacking `core-js`. Adding `npm cache clean` to the build script immediately before `npm install` fixed the issue, and the release proceeded normally from there. The `--silent` flag is now reenabled, and the `npm cache clean` step was left in the build script to prevent future problems of this nature.

**Comment by btmills** [comment]
Today's patch release is being postponed due to low disk space on the build server. We'll try again tomorrow, provided we've been able to clear some space by then.

**Comment by btmills** [comment]
v3.14.1 has been released. This concludes this release cycle, and we can resume merging semver-minor PRs.

I don't know what caused the Jenkins server to run out of disk space, but it's back to normal now, and more people now have access to the server in case it happens again.
