### ISSUE TITLE
Extend no-restricted-properties configuration from shared config

### ISSUE THREAD

**Issue by TheSavior** [eslint/eslint#7957]
I have a shared config that configures [no-restricted-properties](http://eslint.org/docs/rules/no-restricted-properties):

```
    "no-restricted-properties": [2,
      {
        "object": "context",
        "property": "only"
      }, {
        "object": "context",
        "property": "skip"
      }, {
        "object": "describe",
        "property": "only"
      }, {
        "object": "describe",
        "property": "skip"
      }, {
        "object": "it",
        "property": "only"
      }, {
        "object": "it",
        "property": "skip"
      }
    ],
```

In my app's configuration, I want to add one value to this configuration without having to copy and paste the original list. Is there any way to do this?

**Comment by platinumazure** [comment]
At the moment, I don't think there is. This is a pretty good example of why such a feature would be useful, but we haven't been able to come up with a good way to do it (without breaking the use case of users wanting to override the configuration).

**Comment by nzakas** [comment]
Yeah, unfortunately there's no way to do this without copy-pasting.

**Comment by alberto** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the ESLint Gitter if you have any other issues!
