### ISSUE TITLE
prefer-destructuring with complex scoping

### ISSUE THREAD

**Issue by maxlapides** [eslint/eslint#7979]
* **ESLint Version:**
3.14.0
* **Node Version:**
6.9.1
* **npm Version:**
4.1.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**What did you do? Please include the actual source code causing the issue.**

```js
let id
if (condition) {
    id = params.id
}
else {
    someOtherStuff()
    id = args.id
}
doSomething(id)
```

With the `prefer-destructuring` rule on, I get errors here. But I'm not sure how to restructure this code so that it works and also makes ESLint happy. Thoughts?

**Comment by not-an-aardvark** [comment]
```js
let id
if (condition) {
    ({ id } = params)
} else {
    someOtherStuff()
    ({ id } = args)
}
doSomething(id)
```

**Comment by maxlapides** [comment]
@not-an-aardvark wow that was fast! thanks so much!

**Comment by not-an-aardvark** [comment]
No problem!
