### ISSUE TITLE
Does this tool have the capability to send report via email?

### ISSUE THREAD

**Issue by arjungowdaa** [eslint/eslint#7990]
Hi,

Am running the static code analysis report via Jenkins job and my intention is to capture and send the report via email before the Jenkins job ends. Is this possible?
Basically from command line can we send the eslint report via an email?

Regards, AG.

**Comment by not-an-aardvark** [comment]
ESLint itself cannot send emails. However, you can probably accomplish the same thing by piping ESLint's output into a program that sends emails.

**Comment by arjungowdaa** [comment]
Thank you for the reply.
I didn't understand when you say ping the output of ESLint. Can you please give more information?

**Comment by platinumazure** [comment]
@arjungowdaa See http://linuxcommand.org/lc3_lts0070.php (Linux) or https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/redirection.mspx?mfr=true (Windows). If you knew of an e-mail program that would e-mail its standard input, then you can pipe ESLint into that program.

Another possibility is to store the ESLint output in a file (using the `-o` CLI flag) and then have an e-mail program read that file.

This is slightly off-topic for the ESLint issues forum, so I'm going to go ahead and close this. If you need further help, you're welcome to stop by our Gitter chat: https://gitter.im/eslint/eslint
