### ISSUE TITLE
Scheduled Release for February 3, 2017

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#8001]
The scheduled release on Friday, February 3, 2017 is assigned to:

@ilyavolodin
@btmills 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by ilyavolodin** [comment]
v3.15.0 has been released. Please merge only semver-patch changes until we have either done a patch release or determined that one is not necessary.

No issues during the release.

**Comment by btmills** [comment]
We don't see anything that would require a patch release, so this release cycle is complete. We can resume merging semver-minor PRs.
