### ISSUE TITLE
Category for ES7 Rules

### ISSUE THREAD

**Issue by danny-andrews** [eslint/eslint#8003]
I noticed we have three rules relating to the es7 `await function` feature: 'no-await-in-loop', 'no-return-await', and 'require-await', but we don't have an es7 rule category like we do for es6. Is this something we would like to move forward on?

**Comment by platinumazure** [comment]
We have a discussion [here](https://github.com/eslint/eslint/issues/7991) about doing the opposite for ES6.

In my view (as I've made clear in the other issue), the best approach is to have only three categories based on severity of the error: Possible Errors, Best Practices, and Stylistic Issues; and then anything else (ES6, Variables, Strict Mode, and now possibly ES7) would be tags that could be filtered on, and a rule could have zero or more tags. (But this is just my view, and the team has not come to a consensus on how to handle this.)

**Comment by vitorbal** [comment]
@platinumazure I'm +1 for your proposal as well. @danny-andrews do you mind if we move this discussion to #7991 to keep things more focused?

**Comment by danny-andrews** [comment]
Not at all, I figured this was a discussion somewhere else, I just couldn't find the ticket. Thanks!
