### ISSUE TITLE
indent + tabs + jsx does not work with --fix

### ISSUE THREAD

**Issue by kentcdodds** [eslint/eslint#8009]
Relevant config:

```
{
  parserOptions: {
    ecmaVersion: 6,
    ecmaFeatures: {
      jsx: true
    }
  },
  rules: {
    indent: ["error", "tab"]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

Input:

```javascript
import React from 'react'

function MyComponent() {
  return (
    <foo
      prop1={true}
      prop2={false}
      prop3={32}
    >
    bar</foo>
  )
}
```

Output:

```javascript
import React from 'react'

function MyComponent() {
	return (
    <foo
      prop1={true}
      prop2={false}
      prop3={32}
    >
    bar</foo>
	)
}
```

If you look closely, you'll notice that there's a tab character on line 4 (`return`) and line 11 (`)`), but not on the lines with JSX.

I have a pull request (#8008) open with a failing test. Any tips on how to fix the bug are appreciated!

**Comment by vitorbal** [comment]
@kentcdodds thanks for the report! Just to be sure, if you run the same example without --fix, do you get errors or not? AFAIR the indent rule ignores any indentation inside JSX syntax.

Perhaps you could take a look at eslint-plugin-react's [jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md) rule?

**Comment by kentcdodds** [comment]
Ah, yes, I get no errors after the tab is on the `return` and `)` lines. I suppose that this is a bigger issue in that `indent` doesn't support `jsx` at all. I'll look into the `jsx-indent` rule. Should we leave this open? Or just close because `jsx-indent` exists?

**Comment by vitorbal** [comment]
I think the team agreed on not supporting indentation for JSX in favor of the plugin rule. I would say we can close this now and if there are any issues with the fixing implementation of `jsx-indent` we can open an issue there directly!
