### ISSUE TITLE
Configurable Extension Filter

### ISSUE THREAD

**Issue by dfreeman** [eslint/eslint#801]
Currently it appears the `.js` extension filter is hard coded when traversing a directory hierarchy for files to lint. It would be nice for this to be configurable, particularly as ES6 support starts to come up.
As an example use case, we're currently using `.js.es6` as an extension for files that have ES6 module syntax transpiled to AMD, and it would be nice to be able to lint the original source files.

**Comment by SimenB** [comment]
Is it possible to define the `extensions`-array in `.eslintrc`?

**Comment by mjw56** [comment]
I'm seeing the same behavior as @SimenB where the ```ecmaFeatures: { jsx: true }``` is not working for including jsx files. 

If possible, I'd like to stick with ```.jsx``` extension because it is offering the best dev experience with the ide my team is using. Having eslint support for this would be nice.

**Comment by ilyavolodin** [comment]
You have to use `--ext` CLI option in order to lint `jsx` files.

**Comment by mjw56** [comment]
Thanks @ilyavolodin, --ext=js --ext=jsx does work. Is there a way to configure this from .eslintrc? Thanks.

**Comment by SimenB** [comment]
I tried digging in the source, and it seems `.eslintrc` is only read _AFTER_ a file is loaded. So I'm guessing no, but don't quote me on that

**Comment by ilyavolodin** [comment]
You are correct. We can't configure this through .eslintrc because we only read configuration after we build up a list of files to lint. And I think there's an open issue somewhere to make `jsx` files be linted by default.
