### ISSUE TITLE
Docs: Rules are not Sorted Correctly

### ISSUE THREAD

**Issue by danny-andrews** [eslint/eslint#8013]
If you look at the list of rules for a given category, there are some rules that are not sorted correctly: namely, any rule that has a prefix consisting of another rule name. For example, under [Best Practices](http://eslint.org/docs/rules/#best-practices), we have listed:

[no-new-func](http://eslint.org/docs/rules/no-new-func)
[no-new-wrappers](http://eslint.org/docs/rules/no-new-wrappers)
[no-new](http://eslint.org/docs/rules/no-new)

but the order should be:

[no-new](http://eslint.org/docs/rules/no-new)
[no-new-func](http://eslint.org/docs/rules/no-new-func)
[no-new-wrappers](http://eslint.org/docs/rules/no-new-wrappers)

(To test, run `['no-new-func', 'no-new-wrappers', 'no-new'].sort()` in a node prompt.)

I figured out that the rules are sorted this way, because when we're building our [rules index page](https://github.com/eslint/eslint.github.io/blob/master/docs/rules/README.md) we are using the sorted order based on the **filename** not the rule name (e.g. "no-new.js" vs "no-new"). If you run `['no-new-func.js', 'no-new-wrappers.js', 'no-new.js'].sort()` you'll find you do indeed get `['no-new-func.js', 'no-new-wrappers.js', 'no-new.js']`. To fix this, I believe we need to do a sort [here](https://github.com/eslint/eslint/blob/master/Makefile.js#L216) based on the `basename` (not `filename`).

I'd be happy to submit a PR, but I have no way of testing this since it's part of the build script.

**Comment by platinumazure** [comment]
Fixing this would be awesome (additionally, using `basename` might make more sense in case we ever write rules with difference extensions).

**Comment by platinumazure** [comment]
@danny-andrews I think in this case, you could probably submit a PR and we can review it and see if there's a good way to add tests. If you want, you can wait until the team reviews and accepts this issue, to avoid possibly wasting time on a PR we might not accept. (That said, I consider that scenario unlikely, so I would welcome a PR.)

**Comment by kaicataldo** [comment]
I'm for fixing this in the documentation :+1:. Could we start writing tests for Makefile.js piecemeal - i.e., starting with the work done for this issue? If not, seems like something we should fix anyway to me.

**Comment by danny-andrews** [comment]
Finally got a chance to make a PR for this. @platinumazure
