### ISSUE TITLE
Hook eslint-config-eslint up to CI

### ISSUE THREAD

**Issue by danny-andrews** [eslint/eslint#8025]
It appears the [eslint-config-eslint](https://github.com/eslint/eslint/tree/master/packages/eslint-config-eslint) package is not getting published to npm when we do a release. Latest version on npm shows [3.0.0](https://www.npmjs.com/package/eslint-config-eslint), but we are up to 3.14.3.

**Comment by not-an-aardvark** [comment]
Related: https://github.com/eslint/eslint/issues/7414

**Comment by platinumazure** [comment]
Hi @danny-andrews, thanks for the issue. FYI, the published version of eslint-config-eslint is not correlated in any way with the published version of ESLint.

**Comment by danny-andrews** [comment]
Got it, thanks @platinumazure! This may just be a dupe of #7414 then.

**Comment by nzakas** [comment]
Closing, as this isn't done automatically.
