### ISSUE TITLE
indent autofixer causes odd formatting of multi-line object literal argument

### ISSUE THREAD

**Issue by jeff-bernstein** [eslint/eslint#8038]
**Tell us about your environment**

* **ESLint Version:** 3.15.0
* **Node Version:** 7.5.0
* **npm Version:** 4.1.2

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
```
module.exports = {
    env: {
        es6: true
    },
    rules: {
        indent: "error",
    }
};
```

**What did you do? Please include the actual source code causing the issue.**
I ran eslint --fix on a file containing this code:
```
foofoo
    .barbar()
    .bazbaz(
        { a: 1},
        {
            b: 'aVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
            c: 'anotherVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
        },
        { d: 4}
    );
```

**What did you expect to happen?**
I expected the file to remain unchanged.

**What actually happened? Please include the actual, raw output from ESLint.**
The file was fixed as follows:
```
foofoo
    .barbar()
    .bazbaz(
        { a: 1},
    {
        b: 'aVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
        c: 'anotherVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
    },
        { d: 4}
    );
```

Please note the indentation change for lines 5-8 (the 2nd argument to bazbaz). This indentation seems counterintuitive to me. Is this behavior intentional?

**Comment by platinumazure** [comment]
Seems unintuitive to me.

@not-an-aardvark, is this covered by your rewrite?

**Comment by not-an-aardvark** [comment]
> @not-an-aardvark, is this covered by your rewrite?

Yes.

**Comment by jeff-bernstein** [comment]
Thanks guys!

Also, something similar happens with array literals. The following code:
```
foofoo
    .barbar()
    .bazbaz(
        [1],
        [
            'aVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
            'anotherVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
        ],
        [4]
    );

```

...gets fixed to this:
```
foofoo
    .barbar()
    .bazbaz(
        [1],
    [
        'aVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
        'anotherVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString',
    ],
        [4]
    );
```

I assume this is probably the same issue, but thought I should mention this too on the off chance the root cause is different.
