### ISSUE TITLE
No-Unused-Vars with Default Parameters

### ISSUE THREAD

**Issue by gmattie** [eslint/eslint#8040]
When writing ECMAScript 2015+ functions with default parameters, only the last default parameter of the method signature will be recognized as an unused variable.

![eslintdefaultparams](https://cloud.githubusercontent.com/assets/933921/22723434/5324d316-ed8c-11e6-803e-a337691252b4.png)

**Comment by mysticatea** [comment]
Thank you for this issue.

This is intended and actually not related to default parameters.
If you want to warn all parameters, use [`{args: "all"}` option](http://eslint.org/docs/rules/no-unused-vars#args).

**Comment by nzakas** [comment]
Closing as answered.
