### ISSUE TITLE
how to specify which rule --fix applies

### ISSUE THREAD

**Issue by zzzgit** [eslint/eslint#8074]
could i specify which rule --fix will apply for?
if not,will you add this functionality?

**Comment by mysticatea** [comment]
Hi.

You can specify a rule with CLI option.
For example, `eslint . --fix --no-eslintrc --rule "semi:error"`

**Comment by zzzgit** [comment]
@mysticatea 
that is not all i want
i want to lint for many rules,but only fix some of them

**Comment by mysticatea** [comment]
Currently, auto-fixing and linting are separated commend; `eslint .` and `eslint . --fix`.
It can be realized as using different config between the 2 commands.

Related issue is: #8018.

**Comment by vitorbal** [comment]
Closing, as the issue seems to be resolved. Please reopen if there is more to discuss.
