### ISSUE TITLE
Possible to add a feature to enable all rules across plugins?

### ISSUE THREAD

**Issue by mockdeep** [eslint/eslint#8079]
**Tell us about your environment**

* **ESLint Version:** 3.14.1
* **Node Version:** 6.8.0
* **npm Version:** 4.1.2

We [got the `eslint:all` configuration](https://github.com/eslint/eslint/issues/6240) merged, but one side effect seems to be there is a trickle down effect of [similar arguments](https://github.com/benmosher/eslint-plugin-import/issues/551) happening on various ESlint plugins. One thing that might be nice, both for me as a user and for various maintainers not to have to implement this same functionality over and over, is if `eslint:all` or some other configuration also included all of the rules from plugins as well. Does this seem like something that is reasonable and doable? I'd be happy to take a look if people are amenable and I can get a push in the right direction.

**Comment by not-an-aardvark** [comment]
Thanks for the feature request. I think I'm :-1: on this feature due to the reasons listed [here](https://github.com/benmosher/eslint-plugin-import/issues/551#issuecomment-247301605). However, let's see what the rest of the team thinks.

**Comment by mockdeep** [comment]
@not-an-aardvark I actually argue a lot of that [here](https://github.com/eslint/eslint/issues/6240#issuecomment-221123719). For me I don't really care if rules are compatible or not, or whether they are considered a best practice or not. I'm still up for making my own decisions on these things, I just want a streamlined process for integrating new rules into my application.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
