### ISSUE TITLE
unicode-bom fixer insert BOM in appropriate location

### ISSUE THREAD

**Issue by pantosha** [eslint/eslint#8083]
**Tell us about your environment**
Win 10, 64bit
* **ESLint Version:** v.3.15.0
* **Node Version:** v.7.5.0
* **npm Version:** v.4.1.2
**What parser (default, Babel-ESLint, etc.) are you using?**
    default
**Please show your full configuration:**

```
"unicode-bom" :  "error"
```

**What did you do? Please include the actual source code causing the issue.**
I called `eslint --fix some.js`. 

```js
// Some comments.
function someFunction() {
    // some code...
}
```

**What did you expect to happen?**
```js
<U+FEFF>// Some comments.
function someFunction() {
    // some code...
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
// Some comments.
<U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF><U+FEFF>function someFunction() {
    // some code...
}
```

**Comment by platinumazure** [comment]
@pantosha Looks like this is happening due to multipass autofix (and not detecting that the BOM was already inserted in a previous run). Thanks for reporting this!
