### ISSUE TITLE
Rule for allowing upper camel case only in Class names and constructor functions (that require new)

### ISSUE THREAD

**Issue by mugli** [eslint/eslint#8085]
I'd like to setup eslint so that I can:

- Use lower camel case for all variable names (`myImportedModule`, `myObject`). 
- Except:
  - Use upper camel case **_only_** for class and constructor function names (`MyClass`), _and nowhere else_.
  - Allow all upper snake cases for constants (`MY_CONSTANT`). This is already covered by `camelcase` rule.

I have tried:
```
new-cap: [2, {newIsCap: true, capIsNew: true, properties: true}]
```
But `capIsNew` option here only works on function names, not on other variables/object names. For example, 
```
// Expecting lint error: MyLogger has to be lower camel-case (myLogger)
// but it works
const MyLogger = require('my-logger'); 
MyLogger.log('...');
```

I've also considered `id-match`, but it doesn't distinguish between identifier types (classes/constructors vs other variables). I cannot totally disable upper camel case names.

Can it be done?

**Comment by not-an-aardvark** [comment]
Does the [`camelcase`](http://eslint.org/docs/rules/camelcase) rule do what you're looking for?

**Comment by mugli** [comment]
No. `camelcase` doesn't care if the first letter is upper or lower. It just looks for underscores (`_`) in identifier names (with the exception of all cap constants).

**Comment by platinumazure** [comment]
`id-match` is close except that its pattern applies to all identifiers. Could it be expanded to allow an object-based configuration for constructors, functions, identifiers, and properties, each possibly with a different pattern?

**Comment by alberto** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the ESLint Gitter if you have any other issues!

**Comment by ratracegrad** [comment]
Saw this was closed and wondering what is the correct setting if you are getting new-cap error messages for creation of class in a Polymer 2 app?  I have this line which generates 2 new-cap error messages:
class ShopView extends ReduxMixin(Polymer.Element)

I have this rule:
"new-cap": ["error", { "capIsNewExceptions": ["Polymer", "PolymerRedux"] }],
