### ISSUE TITLE
Scheduled Release for February 17, 2017

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#8089]
The scheduled release on Friday, February 17, 2017 is assigned to:

@kaicataldo 
@gyandeeps 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by kaicataldo** [comment]
We were unable to release today due to scheduling issues (we forgot to discuss who was doing the release at the last TSC meeting and tried to fill in last minute). @gyandeeps and I are planning to do a release on Monday.

For the future, let's try to remember to schedule these a few weeks out.

**Comment by kaicataldo** [comment]
v3.16.0 release was successful. Please only merge bug fixes and doc changes until we evaluate if a patch release is necessary in a few days.

**Comment by gyandeeps** [comment]
we released v3.16.1 today. We will just wait till 23rd afternoon CST before we start merging stuff. Just giving some time to let this patch release sink in.

**Comment by kaicataldo** [comment]
Doesn't seem like we have any more regressions. This concludes this release cycle. Please feel free to merge all PRs again!
