### ISSUE TITLE
Make `id-blacklist` accept an array as option

### ISSUE THREAD

**Issue by rasenplanscher** [eslint/eslint#8094]
**What rule do you want to change?**
`id-blacklist`

**Does this change cause the rule to produce more or fewer warnings?**
neither

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option type

**Please provide some example code that this change will affect:**
This setting:
```yaml
"id-blacklist": ["error", ["data", "err", "e", "cb", "callback"] ]
```

**What does the rule currently do for this code?**
Throw an error because the option is not a string.

**What will the rule do after it's changed?**
Be equivalent to this setting:
```yaml
"id-blacklist": ["error", "data", "err", "e", "cb", "callback"]
```
To me, this variant makes it look like `error` were blacklisted. Therefore, I'd like to avoid it.

**Comment by not-an-aardvark** [comment]
Thanks for the proposal.

I think I'm :-1: for this suggestion because I don't see the benefit of having two ways to do the same thing. If you want to avoid making it look like `"error"` is blacklisted, you can use something like this:

```yml
id-blacklist: [2, "data", "err", "e", "cb", "callback"]
```

**Comment by platinumazure** [comment]
I would honestly be open to the breaking change- I don't like having "varargs" style rule configurations honestly.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
