### ISSUE TITLE
Officially deprecate shorthand options

### ISSUE THREAD

**Issue by rasenplanscher** [eslint/eslint#8112]
According to the discussion on #8092, shorthands like `max-depth: ["error", 4]` for `max-depth: ["error", { max: 4}]` are intentionally not added for newer rules, like `max-statements-per-line` in that case. The rationale is that there should not be multiple ways to do the same thing, and that such shorthands are basically magic numbers.

Personally, I can get behind that from a consistency stand-point. In the interest of consistency, I think all shorthands should be deprecated, just like the `maximum` option has been deprecated in favor of a standard `max` option.

This may be tied to #7443, but I think the shorthands should at least be discouraged in the docs. As it stands, the docs are actually kind of propagating the shorthands. From my personal case: for convenience, I used the snippets from the rules examples, so from [the `max-depth` rule page](http://eslint.org/docs/rules/max-depth) I took `max-depth: ["error", 4]`. I guess, this applies to others as well. Also, [the `complexity` rule page](http://eslint.org/docs/rules/complexity) lists the shorthand as the default way, and the explicit way as the optional alternative.

**Comment by platinumazure** [comment]
I guess I see two issues here: First is getting the documentation to use non-shorthand options when they are available, and second is actually changing rules with shorthand options to deprecate or remove shorthand options. The latter will probably require TSC approval.

I'm :+1: to getting the rule docs to use explicit options in examples, for sure.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
