### ISSUE TITLE
ES5 and ES6 in one project

### ISSUE THREAD

**Issue by misantronic** [eslint/eslint#8124]
**What version are you using?** 3.9.1

**What did you do?** Add ES6 (*.es6) to a big ES5 (*.js) project

**What happened?** Cannot lint ES6-files with ES2015-files since eslint will complain about js-files (e.g. object-shorthand)

**What did you expect to happen?** Apply rules to specific file-types.

Is there a way, to apply rules to a specific file-type?
In my project, I have both es6 and es5 files. I want eslint to apply the default-rules to all files but the ES2015-rules only to my *.es6-files.

**Comment by ljharb** [comment]
eslint doesn't currently support glob-based configuration. What's done here is making a separate directory tree for your ES5 and ES6 files, and you'd put an `.eslintrc` in each.

**Comment by misantronic** [comment]
thanks for clarifying. that really is a lot of effort for some linting. i think i'll wait for support of glob-based configuration.
