### ISSUE TITLE
New exception type in id-length rule

### ISSUE THREAD

**Issue by sarkiroka** [eslint/eslint#8125]
**What rule do you want to change?**
`id-length`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New exception type (for-loop) with default value (i,j,k)

**Please provide some example code that this change will affect:**

```
var i=42; // warning, because min is default 2 and not in for-loop declaration;
for(var i=0;i<10;i++){...} // no warning, because i,j,k is standard in for-loop and it is in for-loop declaration
```

**Comment by not-an-aardvark** [comment]
Thanks for the feature request.

Personally, I'm not convinced that it's worth adding an option specifically for `for` loops. However, let's see what the rest of the team thinks.

**Comment by platinumazure** [comment]
I could maybe get behind a new option with no change in default behavior (that is, it's fully opt in). But loops do feel like a rather specific case here. Not sure which way I want to go here.

**Comment by ilyavolodin** [comment]
I agree with @not-an-aardvark I think this is too specific to be added to the core rule. This is the reason why we have `exceptions` property in this rule. I know it doesn't fully cover your case, but it does allow specific variables like `i`, `j`, etc. to be ignored by the rule.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
