### ISSUE TITLE
Disable eslint

### ISSUE THREAD

**Issue by tavo379** [eslint/eslint#8131]
how can i disable eslint to the web stater kit by google?

**Comment by corbinu** [comment]
It is the lint task in the gulp file their docs are here: https://github.com/gulpjs/gulp/blob/master/docs/API.md

**Comment by not-an-aardvark** [comment]
Closing this issue since the question is answered and it doesn't appear to be a problem with ESLint. Please feel free to ask on our [Gitter chat](https://gitter.im/eslint/eslint) if you have any other questions.
