### ISSUE TITLE
ESLint ignoring .eslintignore

### ISSUE THREAD

**Issue by xavicolomer** [eslint/eslint#8135]
Hi there,

I'm trying to ignore certain patterns on eslint. I tried both --ignore-pattern and .eslintignore but none is working. I also tried different patterns.

I can see that without removing ** everything works. Is when adding (**) that the rule is not applied correctly.

**Tell us about your environment**

* **OS:** Windows 10
* **ESLint Version:** v3.15.0
* **Node Version:** v6.9.5
* **npm Version:** 3.10.10

**File Structure:**

node_modules
.eslintrc.js
src
--api
---- news
------node_modules
------handler.js
------ ...

**Command**

Does not work
`eslint . --quiet --ignore-pattern **\node_modules\ ** \ *.js`

Works
`eslint . --quiet --ignore-pattern *.test.js
`

**Comment by platinumazure** [comment]
Have you tried quoting your glob patterns? Sometimes glob patterns get expanded by your shell before they get to ESLint, resulting in weird behavior.

It could be something else for sure, but you should give this a try if you can.

**Comment by xavicolomer** [comment]
I tried 
`eslint . --quiet --ignore-pattern "**\node_modules\**\*.js"`

but it didn't work. thanks @platinumazure

**Comment by xavicolomer** [comment]
Oh...

I am new on a Windows platform, at least in the last 10 years. I copied the path form the console, the slashes are on the opposite direction (￣ー￣；

eslint . --quiet --ignore-pattern **/node_modules/**/*.js

**Comment by platinumazure** [comment]
@xavicolomer I apologize, I should have spotted that. Our ignore patterns match the gitignore spec, which requires forward slashes.

I opened #8139 for further discussion. I doubt we'll change the patterns we support, but we could probably improve the documentation a little. Please feel free to comment in that issue if you have any particular suggestions for us. Thanks!
