### ISSUE TITLE
Improving ignore pattern documentation and UX for Windows users

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8139]
Inspired by #8135. Root cause of that issue was that the user was using a Windows path (with backslash delimiters) as an ignore pattern (which require forward slash delimiters).

Currently we use node-ignore to provide support for gitignore style patterns. Should we consider expanding that to support Windows paths (basically replacing \ with / before feeding the patterns to node-ignore)? Or would that add too much confusion?

Observations about current documentation (as of 2/23/2017):

* CLI docs for [`--ignore-pattern`](http://eslint.org/docs/user-guide/command-line-interface#--ignore-pattern) do use the term "patterns" rather than "paths", but no direct mention of gitignore syntax. It does mention that it's the same format as .eslintignore, but no cross-linking. I think that would be an easy fix.
* [Configuring](http://eslint.org/docs/user-guide/configuring) docs mention node-ignore and use "pattern" terminology throughout. I wouldn't mind a link to node-ignore occurring sooner but otherwise this is probably good.

Any other documentation we should update?

**Comment by borela** [comment]
No need to convert the slashes as most windows users(who are using git) are already used to it. But I believe that the documentation should state clearly that `--ignore-pattern` uses the `.gitignore` syntax.

**Comment by platinumazure** [comment]
Thanks @borela for your feedback.

I think we can turn this into a documentation-only issue, and we can discuss any core code changes elsewhere. So I've marked the issue "accepted" and added "help wanted" label as well. Thanks!

**Comment by santanaG** [comment]
Hi! @platinumazure what are the changes you are suggesting exactly? Is this still relevant?

**Comment by platinumazure** [comment]
Hi @santanaG, thanks for commenting.

The general idea is this: In our .eslintignore documentation, we want to make it clear that the syntax is the same as .gitignore (and, in particular, that all paths should use forward slash as the path separator).

As far as I know, this is still relevant.

Hope this helps!
