### ISSUE TITLE
Support async generators

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/eslint#8140]
Would it be possible to add support for async generators?

Proposal: https://github.com/tc39/proposal-async-iteration
Stage 3

ESLint version 3.16.1

Example of async generators

``` js
async function* foo() {

}
```

This currently leads to:

```
Parsing error: Unexpected token *
```

**Comment by OliverJAsh** [comment]
My bad, it already does when specifying ecma version 2018.

**Comment by not-an-aardvark** [comment]
Thanks for the feature request. However, we generally don't support experimental features until they reach stage 4 (see our [FAQ](https://github.com/eslint/eslint/blob/cbd7ded15df21d40e70852b83c0b7a855def6036/README.md#what-about-experimental-features)). Please use [babel-eslint](https://github.com/babel/babel-eslint) for now, and we'll support this feature when it reaches stage 4.

**Comment by alberto** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the ESLint Gitter if you have any other issues!
