### ISSUE TITLE
Cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by pixelass** [eslint/eslint#8147]
**Tell us about your environment**

* **ESLint Version: 3.16.1**
* **Node Version: 6.10.0**
* **npm Version: 4.3.0**

**What parser (default, Babel-ESLint, etc.) are you using?**

JSX

**Please show your full configuration:**

```

module.exports = {
  "extends": ["eslint:recommended", "plugin:react/recommended", "standard"],
  "plugins": [
      "standard",
      "react"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
};



```

**What did you do? Please include the actual source code causing the issue.**

does not happen in my code but inside a node_module

**What did you expect to happen?**
Linting should work
**What actually happened? Please include the actual, raw output from ESLint.**
Linting fails due to the following error

```bash
> eslint ./src

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ME/SOME_PLACE/SOME_REPO/node_modules/.bin/eslint:31:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by gyandeeps** [comment]
Can you please make sure you have eslint installed correctly? It seems like that eslint is not present tho the executable is.

**Comment by not-an-aardvark** [comment]
Closing this since the author hasn't responded.

**Comment by pixelass** [comment]
Sorry. I forgot to answer. Thing got busy ;). I think I removed all node_moduels and then reinstalled. As far as I rememeber it was resolved after that. It's one of my private projects and I don't even rememeber which. 

Thx for the support. Totally ok that this is closed.
