### ISSUE TITLE
In-file sourceType configuration

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#8148]
Currently, the [`sourceType`](http://eslint.org/docs/user-guide/configuring#specifying-parser-options) parser option can only be set in the configuration file for all files in a directory. If one has a mix of both `script` and `module` files in the same directory, there's currently no way discern which file is which type.

The prime example of this issue should be [ava](https://github.com/avajs/ava) which expects its tests to be written in module syntax, while other files can be plain scripts.

I think a new inline configuration option could elegantly solve the issue:

```js
// eslint-source-type module
```

**Comment by not-an-aardvark** [comment]
I'm not sure this is feasible because source type is a parser option, which needs to be known before the file starts getting parsed and the comments are available.

**Comment by platinumazure** [comment]
I agree with @not-an-aardvark that this might not be feasible.

Glob-based configuration could potentially solve this, if the tests can be easily denoted via glob expressions. See #3611 for more information.

**Comment by silverwind** [comment]
Right, this seems something better solved by globs, which could be applied on all parser options, not just `sourceType`. I'll watch https://github.com/eslint/eslint/issues/3611 and workaround through a `test` directory in the meanwhile. Thanks!
