### ISSUE TITLE
Feature Request: Rule Sets

### ISSUE THREAD

**Issue by Undistraction** [eslint/eslint#8152]
I find that some rules are rules I want while developing day-to-day, and some I would prefer to run periodically. A good example is `arrow-body-style` when building out React components - Temporarily adding some logging before rendering means changing between implicit and explicit return and the addition of curly braces. I would prefer to allow both day-to-day, however this is something I would want to run before a release. It might be nice to allow rules to be gathered into named sets that can easily be toggled on or off. One set could contain ongoing rules and one rules that are run occasionally. Obviously I can do this on an individual basis, but doing to as a set would make more sense.

**Comment by gyandeeps** [comment]
Configure file is a JSCS file ('.eslintrc.js'). You can setup your lint using 'env' variables and then return a different set using different env variable from your .eslintrc.js file.
I don't see set functionality to be in core since it can be easily achieved. Let see what the team has to say.

**Comment by mysticatea** [comment]
There are some approaches.

1. Prepare several `.eslintrc` files. For example: `eslint src` and `eslint src --config .eslintrc-release.json`
2. Use `.eslintrc.js` and tweak configuration by environment variables such as `process.env.NODE_ENV`.

**Comment by Undistraction** [comment]
@gyandeeps @mysticatea Thanks for the suggestions. I think using env vars is a workable solution, however what I'm asking for doesn't really translate across to separate environments in the traditional sense, and it means splitting the config into separate files and I think there is something to be said for keeping them in a single place for what is a  single (development) environment. Although I mentioned using one set specifically before release, in which case there is something of a mapping between release and a staging or production environment, this could easily just be something done pre-commit or for some other reason not related to release, in which case there isn't really a mapping to a separate environment.

**Comment by platinumazure** [comment]
I agree that multiple configurations is the best way to go. To minimize duplication in your configuration, you can have one primary configuration file and then have others that extend that file and only do minor tweaks, so that most of the configuration is in the primary file.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
