### ISSUE TITLE
Autofix confliction: arrow-body-style and object-shorthand

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#8153]
**Tell us about your environment**

* **ESLint Version:** 3.16.1
* **Node Version:** 7.6.0
* **npm Version:** 4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**

- default

**Please show your full configuration:**

- nothing

**What did you do? Please include the actual source code causing the issue.**

I did autofix to the following code:

```js
/* eslint
    arrow-body-style: error,
    object-shorthand: [error, always, {avoidExplicitReturnArrows: true}]
*/

const obj = {
    foo: () => {
        return 1
    }
}
```

```bash
$ eslint test.js --fix --env es6 --no-eslintrc --no-ignore
```

**What did you expect to happen?**

The code is fixed to:

```js
/* eslint
    arrow-body-style: error,
    object-shorthand: [error, always, {avoidExplicitReturnArrows: true}]
*/

const obj = {
    foo: () => 1
}
```

Or

```js
/* eslint
    arrow-body-style: error,
    object-shorthand: [error, always, {avoidExplicitReturnArrows: true}]
*/

const obj = {
    foo() {
        return 1
    }
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

The code was fixed to:

```js
/* eslint
    arrow-body-style: error,
    object-shorthand: [error, always, {avoidExplicitReturnArrows: true}]
*/

const obj = {
    foo() 1
}
```

Then the autofix stopped by a syntax error.

```
$ eslint test.js --fix --env es6 --no-eslintrc --no-ignore

/path/to/test.js
  7:11  error  Parsing error: Unexpected token 1

✖ 1 problem (1 error, 0 warnings)

```

**Comment by mysticatea** [comment]
- When `arrow-body-style` removes a block body, it should lock the `=>` token because it makes an expression body which can exist at the location preceded by `=>`.
- When `object-shorthand` converts an arrow function to a method, it should lock the opening brace of the arrow body because this autofix relies on that the function body is a block.

**Comment by not-an-aardvark** [comment]
In general, I think it will be easier if rules lock nodes, not tokens. That way, a rule can focus on the semantics of the code, rather than worrying about how specific tokens can affect the semantics. (This will also make it easier for rules to handle custom parsers, which might not have the same rules about where tokens can appear.)

> * When object-shorthand converts an arrow function to a method, it should lock the opening brace of the arrow body because this autofix relies on that the function body is a block.

I agree, but I think it would be better to just lock the entire `Property`, since it used that to determine that code should be reported.

> * When arrow-body-style removes a block body, it should lock the => token because it makes an expression body which can exist at the location preceded by =>.

I think it would be better to lock the entire `ArrowFunctionExpression`, since that was used to determine that the method should be reported.

**Comment by mysticatea** [comment]
Just I thought, I'd like to not lock wide-range such as function bodies. :thinking:

**Comment by not-an-aardvark** [comment]
This was fixed by https://github.com/eslint/eslint/commit/2d883d7c62b0dca01ee31e6cc3751283acb9c330.
