### ISSUE TITLE
Proposal – Support for multiple output formats

### ISSUE THREAD

**Issue by KELiON** [eslint/eslint#8185]
There is a CLI option `-f`, that you can use to specify output format. But there could be a case when you need to support several formats with one run of eslint. 

Our case: we use TravisCI and cli options `-f checkstyle -o eslint.xml`. After the build we process eslint.xml by our internal tool. In this case we should specify two scripts in TravisCI – one for internal tool with xml output and another for people so they can see eslint output in TravisCI log.

Would be better to support something like `-f checkstyle -o eslint.xml -f stylish` so users can run eslint only once, but have xml file and human-readable output in stdint.

**Comment by ilyavolodin** [comment]
There are couple of problems with this suggestion. First of all, `-o` flag redirects all of the output into a file. Which means that you will end up with a file that contains both checkstyle as well as stylish output. There wouldn't really be any way to differentiate between those two formatters and only output checkstyle into a file. Second issue is, what if you don't specify output file? Should both formatters print out results to the console?
There's currently nothing in the code that differentiates between human-readable formatters, and machine-readable ones. Nor do I think it would be a good idea to introduce something like that.

**Comment by KELiON** [comment]
@platinumazure It sounds good, I think it covers all our cases, thanks!
