### ISSUE TITLE
max-len - ignoreStrings / ignoreTemplateLiterals too aggressive

### ISSUE THREAD

**Issue by michalg42** [eslint/eslint#8189]
* **ESLint Version: 3.16.1
* **Node Version:6.6.0
* **npm Version:3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "no-unused-vars-rest"
  ],
  "env": {
    "browser": true,
    "jest": true
  },
  "globals": {
    "__DEV__": true,
    "__PROD__": true,
    "__DEBUG__": true,
    "__COVERAGE__": true,
    "__BASENAME__": true
  },
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "webpack/webpack.config.js"
      }
    }
  },
  "rules": {
    "arrow-parens": [2, "always"],
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'ignore',
    }],
    "import/no-extraneous-dependencies": [2, {"devDependencies": ["**/*.test.js", "**/*.stories.js"]}],
    "no-console": 2,
    "react/jsx-boolean-value": [2, "always"],
    "react/jsx-filename-extension": [2, {"extensions": [".js", ".jsx"]}]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
Created line

    const date = this.props.intl.formatDate(new Date(), { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: 'numeric', timeZone: 'UTC' });

which has about 180 signs.

**What did you expect to happen?**

Show error, as default setting is set to 100 signs. Yet no error.

**What actually happened?**

No error was shown, because "ignoreStrings"/"ignoreTemplateLiterals" is set to true. That's fantastic settings, as partitioning template literals isn't quite good code for me. But now this setting is too aggressive and ignores line like the one inserted before. There are strings, but I don't think that's enough not to parse this line.

Unfortunatelly I have no idea how to make it less aggressive, so that lines that contains ie. objects with string values could still be parsed. :(

**Comment by vitorbal** [comment]
Thank you for your issue!

I'm not very familiar with the ignoreStrings / ignoreTemplateLiterals implementation. My guess is that it looks for *any* `Literal` or `TemplateLiteral` nodes in the line and if found, disables the maxlen warning for that line.
I wonder if it would make sense to fine-tune it to only disable the warning if the *last* token is a `Literal` or `TemplateLiteral`..

**Comment by danny-andrews** [comment]
I second this. The current behavior is very confusing:
```js
const notOk = { a: 2, reallyLongKey: 8, reallyreallyreallylongkey: 10, otherThing: 19, oneMoreThingTooLong: 10 }; // no error
const imOk = { a: 2, reallyLongKey: 8, reallyreallyreallylongkey: 10, otherThing: 'haha', oneMoreThingTooLong: 10 }; // eslint complains
```

**Comment by danny-andrews** [comment]
@vitorbal Your solution might work well, taking semicolons and comments into consideration, of course.

**Comment by ljharb** [comment]
The intent is to not allow string length to contribute to line length limits.

However, like the other preexisting ignore settings, it was instead made to ignore the entire line when a string appears on it.

I think an ideal (breaking) change would be to change all of the ignore settings to subtract "ignored item length" (string, URL, comment, etc) from the total line length, and *then* apply the max warning if needed.

However, unless all of them can be changed at once to "ignore the item when calculating line length", I think they should all remain as "ignore the line this item appears on" for consistency.

**Comment by danny-andrews** [comment]
I think that would be even more confusing, because then you'd have lines of different lengths throwing `max-len` errors and you would have to do the maths in your head to figure it out.

Maybe we could change the rule to ignore strings which are broken over the `max-len` limit. E.g., if `max-len` was set to 20:
```js
                 // Ruler
                 // |
const str = 'my string'; // No error, string would have to be broken onto multiple lines to meet `max-len` constraint
const o = { a: 'hi' }; // Error, string would not have to be broken onto multiple lines to meet `max-len` constraint
const obj = { a: 'hi fdsafsa' }; // No error, string would have to be broken onto multiple lines to meet `max-len` constraint
                 // |
                 // Ruler
```

**Comment by ljharb** [comment]
Yes but what if the line was `f('a long string but one that fits under the limit', a, b, c, d, e, thisVarPassesTheLimit);`?

The only two situations I think that make sense and are consistent are a) ignore the entire line if a long "Ignored thing" appears on it (what we have now), or b) subtract the length of the ignored thing from the line when calculating its length (https://github.com/eslint/eslint/issues/8189#issuecomment-300836133)

**Comment by danny-andrews** [comment]
Hmmm...yes, you're right. I think option `b` would be a good solution. Looks like that's how jscs implemented similar functionality for their [`maximumLineLength` rule](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/maximum-line-length.js#L149).

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
