### ISSUE TITLE
Switch back to the version of mock-fs from npm

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8194]
To fix https://github.com/eslint/eslint/issues/8177, we are currently depending on a patched version of the `mock-fs` module downloaded from GitHub. When the upstream `mock-fs` module gets updated with the patch, we should switch back to depending on the npm module.

Also see: https://github.com/tschaub/mock-fs/pull/198

**Comment by tschaub** [comment]
Fix published as `mock-fs@4.2.0`.

**Comment by not-an-aardvark** [comment]
Thanks @tschaub!
