### ISSUE TITLE
[Change request]Recognition JSON codes which is embedded in JavaScript code.

### ISSUE THREAD

**Issue by libook** [eslint/eslint#8210]
* **ESLint Version:3.17.1**
* **Node Version:7.7.1**
* **npm Version:4.1.2**

**default and airbnb-base**

**My full configuration:**

```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "extends": [
    "airbnb-base"
  ],
  "globals": {
    "STATICCONFIG": true
  },
  "rules": {
    "no-console": "off",
    "no-param-reassign": [
      "error",
      {
        "props": false
      }
    ],
    "func-names": [
      "warn",
      "never"
    ],
    "quote-props": [
      "error",
      "always"
    ]
  }
}

```

For quotes, I prefer this style:

```javascript
const v1 = 'Use single quotes as default in JavaScript codes.';
const v2 = {
  "Use double quotes as default in JSON code" : "even though they are embedded in JavaScript codes."
};
```

I apologize;
if there is already a way to make this;
or I made mistakes in my description.

**Comment by ilyavolodin** [comment]
JSON inside JavaScript code is just JavaScript code. I'm not sure I understand what you mean. Are you saying you want to use one quote style for objects and another for strings?

**Comment by libook** [comment]
@ilyavolodin Thanks for your reply.
Yes, but just for JSON (or 'JSON style JavaScript').
It's true, that JSON inside JavaScript is just JavaScript code. But I used to copy them for pure JSON usage. So I have to convert JavaScript style to JSON style, or write with JSON style in JavaScript code.
This is why I need two styles for JavaScript code.

Is this weird or unreasonable?

**Comment by not-an-aardvark** [comment]
How would the rule distinguish between a value that is intended as "JSON" and a value that is intended as "regular code"?

In my opinion, this isn't a good idea -- once a value is in your JS file, it's JavaScript and should be treated as such.

**Comment by ilyavolodin** [comment]
@libook I'm not sure if it's weird, I don't think it's unreasonable, but I also think that this is an edge-case style that is not a "must have" for core rule. I think this is perfectly reasonable rule to create a plugin for, though. The bar for adding things into the core is pretty high, as we already have a very large number of rules and options, and I don't think this style meets that high bar. But let's see what others think.

**Comment by libook** [comment]
@not-an-aardvark 

> once a value is in your JS file, it's JavaScript and should be treated as such.

I don't think so. JavaScript can be written in HTML codes; and it should not be treated as HTML.

But you are right that it may be difficult to do:

> How would the rule distinguish between a value that is intended as "JSON" and a value that is intended as "regular code"?

**Comment by libook** [comment]
@ilyavolodin 
You are right that this is not "must have" rule. I think plugin way is good.
Or I just need to change my coding habit.

**Comment by libook** [comment]
Thank you all.
By the way;
please tell me, if there is already plugins can do this.
