### ISSUE TITLE
docs: no-global-assign is not displaying as part of eslint:recommended

### ISSUE THREAD

**Issue by hulbert** [eslint/eslint#8215]
Apologies if this is filed in the wrong location. `no-global-assign` appears to be enabled as part of `eslint:recommended` but this is not reflected on this page http://eslint.org/docs/rules/no-global-assign or in the [rules list](http://eslint.org/docs/rules/)

**Comment by platinumazure** [comment]
Confirmed that `no-global-assign` appears in `conf/eslint-recommended.js` but the rule's `meta.docs.recommended` is set to `false`.

I assume that `no-global-assign` should in fact be recommended, so the fix here would be to set `meta.docs.recommended` to `true`, and then the docs will update themselves in the next release.

**Comment by vitorbal** [comment]
This would be a good first bug for new contributors!

**Comment by liubinyi** [comment]
Hi I am new to eslint but i would like to try!
