### ISSUE TITLE
Conditionally controlling env

### ISSUE THREAD

**Issue by unphased** [eslint/eslint#8217]
In node.js scripts the variable name `name` often gets used (as a function parameter for example). 

Incidentally `name` is a global in the `browser` env. So these get flagged incorrectly by no-shadow because `name` isn't a global we need to worry about in node.js.

I simply happen to have both `node` and `browser` envs enabled in my global eslintrc. This was a reasonable approach to ensure it works reliably in all JS files.

So I wonder how we can improve the situation. A few thoughts. 

- Detect `#!/usr/bin/env node` and similar shebang to automatically enable `node` env and disable `browser` env. Since I expect to leave `browser` env set in global eslint config as its a reasonable default.
- It would be best if there was some way of specifying (via config, somehow) this sort of conditional behavior.
- it seems like for any JS scripts that are intended for use in both environments, specifying both envs manually somewhere seems unavoidable. for code cleanliness it'd have to live in the filesystem.
- now it is starting to seem like I should simply avoid using the varname `name` altogether because it's too nontrivial a problem

**Comment by kaicataldo** [comment]
Is there any reason why you can't use the `allow` option for `no-shadow`?

http://eslint.org/docs/rules/no-shadow#allow

**Comment by unphased** [comment]
seems like a good workaround for this situation. It seems like having both envs enabled across the board is not ideal however?

**Comment by kaicataldo** [comment]
Yeah, I would only recommend that for cases where the module is used both in the browser and in Node.

Generally, if most of a project is client-side code, I just enable the `browser` `env` and put `/* eslint-env node */` at the top of the new files that might be executed in a Node environment (config files, etc.). Another option would be to have nested ESLint configs and enable the correct `env` scoped to whatever directory level you want.

**Comment by unphased** [comment]
This all sounds extremely reasonable and see no further reason for this issue to remain open. Thanks.

**Comment by kaicataldo** [comment]
Happy to help :)
