### ISSUE TITLE
no-unused-vars doesn't recognize the use of imported modules as jsx components

### ISSUE THREAD

**Issue by iliran11** [eslint/eslint#8226]
Enviroment:
* **ESLint Version:**  v3.17.1
* **Node Version:** v6.9.5
* **npm Version:** 3.10.10
* **Visual Studio Code:** 1.10.2 
* **ESLint Extension for Visual Studio Code**:  1.2.7

 Parser for building the project:
*  **Babel, using this .babelrc:**

```
{
  "presets": ["react", "es2015", "stage-1"]
}
```

**full configuration:**

```
module.exports = {
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

`App` and `Provider` are giving error for `no-unused-vars`
but they are used inside the jsx as components.

```js
import ReactDOM from 'react-dom';
import  {Provider} from 'react-redux';  // gives no-unused-vars error
import { createStore, applyMiddleware } from 'redux';

import App from './components/app'; //// gives no-unused-vars error
import reducers from './reducers';

const createStoreWithMiddleware = applyMiddleware()(createStore);

ReactDOM.render(
  <Provider store={createStoreWithMiddleware(reducers)}>
    <App />
  </Provider>
  , document.querySelector('.container'));
```

**What did you expect to happen?**

ESLint should have recognized that App and Provider vars are used inside the jsx, and consider them as used vars.

**raw output from ESLint.**
```
file: 'file:///c%3A/projects/weather-redux/src/index.js'
severity: 'Error'
message: ''Provider' is defined but never used. (no-unused-vars)'
at: '2,10'
source: 'eslint'
```

```
file: 'file:///c%3A/projects/weather-redux/src/index.js'
severity: 'Error'
message: ''App' is defined but never used. (no-unused-vars)'
at: '5,8'
source: 'eslint'
```

**Comment by platinumazure** [comment]
Hi @iliran11, thanks for the issue.

I see that you're using eslint-plugin-react. I think you want to enable [`react/jsx-uses-vars`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md) in order to fix this issue. React applies semantics to JSX that aren't actually part of the JSX standard, so there are some eslint-plugin-react rules that allow ESLint to treat JSX in a similar way.

**Comment by iliran11** [comment]
thanks ... i created those settings via the wizard.
eslint --init

would make sense to add it to the wizard no? :) 
it's a very common scenario

**Comment by anthonybrown** [comment]
So the answer is the use `"react/jsx-uses-vars": true` in the .eslintrc.js file?

**Comment by anthonybrown** [comment]
This configuration is fine for React.js

```
module.exports = {
  "parser": 'babel-eslint',
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true,
      "react/jsx-uses-vars": true
    },
    "sourceType": "module"
  },
  "plugins": [ "react" ],
  "rules": {
    "indent": ["error", 2],
    "linebreak-style": ["error","unix"],
    "quotes": ["warn","single"],
    "semi": ["warn","always"],
    "no-console": ["warn", { "allow": ["info", "error"] }]
  }
};
```

**Comment by ilyavolodin** [comment]
No, `react/jsx-uses-vars: ["error"]` should be under `rules` section.

**Comment by anthonybrown** [comment]
I don't want the error for React
```
import React, { Component } from 'react';

class App extends Component {
  constructor() {
    super();
  }
  //....
}
```

**Comment by anthonybrown** [comment]
so it seems that using the `extends: ['plugin:react/recommended']`
the `unused-vars` error goes away.
