### ISSUE TITLE
Regular Expressions starting with /* treated as comment.

### ISSUE THREAD

**Issue by rhalff** [eslint/eslint#8227]
**ESLint Version**: 3.17.1
**Node Version:**: v7.6.0
**npm Version:** 4.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```js
{
  "parser": "babel-eslint",
  "env": {
    "browser": true
  },
  "extends": "auth0",
  "rules": {
    "array-callback-return": 0,
    "camelcase": 0,
    "consistent-return": 0,
    "import/no-extraneous-dependencies": 0,
    "no-mixed-operators": 0,
    "no-restricted-syntax": 0,
    "no-underscore-dangle": 0,
    "react/no-find-dom-node": 0,
    "react/prefer-stateless-function": 0,
    "react/prop-types": 0
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
export default () => /*@cc_on!@*/false;
```

**What did you expect to happen?**

The code above should not be formatted and left untouched when using `--fix`

**What actually happened? Please include the actual, raw output from ESLint.**

The regexp seems to be interpreted as a comment and an extra space is added to the regexp.
```js
export default () => /* @cc_on!@*/false;
```

Output using lint:
```js
$ ./node_modules/.bin/eslint src/utils/isIE.js 

/srv/git/webtask-graph/src/utils/isIE.js
  1:22  error  Expected exception block, space or tab after '/*' in comment  spaced-comment
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. I think this is correct behavior -- your code contains a comment, not a regular expression. `*` would not be a valid first character of a regular expression.

**Comment by rhalff** [comment]
Thanks, my bad...
