### ISSUE TITLE
Convert externally-exposed modules to ES6 classes

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8231]
Some modules like `RuleTester` and `CLIEngine` expose a class-like pattern, but they're not actually ES6 classes. In https://github.com/eslint/eslint/issues/7849 and https://github.com/eslint/eslint/pull/7846, we discussed converting them to ES6 classes, but we decided this would be a breaking change if someone was using the APIs in undocumented ways (e.g. calling `SourceCode` without `new`). Since this change would affect very few users and would make the code easier to maintain, I think we should convert them to ES6 classes for 4.0.0.

- [x] lib/cli-engine.js
- [x] lib/testers/rule-tester.js
- [x] lib/util/source-code.js

**Comment by kaicataldo** [comment]
Added the "tsc agenda" label since this is technically a core breaking change.

**Comment by not-an-aardvark** [comment]
This was accepted by the TSC in today's TSC meeting.
