### ISSUE TITLE
Update eslint:recommended for 4.0.0

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8236]
Like we always do with major releases, we should update `eslint:recommended` with new rules for detecting possible errors.

**Comment by not-an-aardvark** [comment]
My suggestions:

  - [`no-useless-escape`](http://eslint.org/docs/rules/no-useless-escape)
  - [`no-template-curly-in-string`](http://eslint.org/docs/rules/no-template-curly-in-string)
  - [`no-compare-neg-zero`](http://eslint.org/docs/rules/no-compare-neg-zero)
  - [`array-callback-return`](http://eslint.org/docs/rules/array-callback-return)
  - Replace [`no-negated-in-lhs`](http://eslint.org/docs/rules/no-negated-in-lhs) (deprecated) with [`no-unsafe-negation`](http://eslint.org/docs/rules/no-unsafe-negation)
  - Replace [`no-native-reassign`](http://eslint.org/docs/rules/no-native-reassign) (deprecated) with [`no-global-assign`](http://eslint.org/docs/rules/no-global-assign)

**Comment by not-an-aardvark** [comment]
Adding this to the TSC agenda so that we can make a decision on it.

**Comment by not-an-aardvark** [comment]
In today's [TSC meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2017/2017-03-30.md), the TSC mostly accepted the suggestions from https://github.com/eslint/eslint/issues/8236#issuecomment-285914084, with the caveat that we should possibly remove `no-template-curly-in-string` if libraries use strings like that for custom templating. @kaicataldo is going to look into whether libraries do this.

**Comment by kaicataldo** [comment]
As @alberto mentioned earlier, https://github.com/BorisMoore/jquery-tmpl uses `${ }` syntax, so I don't think we can include `no-template-curly-in-string` in this.

**Comment by not-an-aardvark** [comment]
I don't doubt that there are other libraries with `${ }` syntax, but I notice that `jquery-tmpl` has been deprecated for 3 years and replaced with a library that uses a different syntax. Are there newer popular libraries that use `${ }` syntax?

**Comment by ilyavolodin** [comment]
Knockout.js is using `${ }` bindings. And while it's pretty old, I think there are still quite a bit of people using it.

**Comment by not-an-aardvark** [comment]
True, but it seems like they only do that because of jQuery.tmpl, and their [docs](http://knockoutjs.com/documentation/template-binding.html) recommend against using it. Do you think enough people still do that that it's worth removing the rule from `eslint:recommended` anyway?

**Comment by platinumazure** [comment]
Users can also override eslint:recommended in their own config, right? It's not like those users are completely up a creek if we include that rule.I think the question I would ask is, are these libraries remotely common enough that we would be inflicting too much unnecessary pain?

**Comment by kaicataldo** [comment]
After thinking on it some more in light of our discussion earlier, I'm of the opinion that it's too opinionated and we should not include it in `eslint:recommended`.

**Comment by ilyavolodin** [comment]
I think I agree with @kaicataldo This rule will only help people who are writing ES6 code and using template literals. However it might affect unknown number of users who don't do ES6. I'm of the opinion we should lean towards safer side and not include it.

**Comment by not-an-aardvark** [comment]
Ok, I'll remove it from the list.

**Comment by not-an-aardvark** [comment]
It turns out that `no-unsafe-negation` and `no-global-assign` were already added to `eslint:recommended` in https://github.com/eslint/eslint/pull/7467. More details are in https://github.com/eslint/eslint/issues/8370.
