### ISSUE TITLE
Eslint 'space-comment' not accepting colon as exception

### ISSUE THREAD

**Issue by psiphi75** [eslint/eslint#8240]
**Tell us about your environment**
Linux Ubuntu 16.10.  Running eslint on Atom (same issue with cli tool).

* **ESLint Version:**
v3.1.0

* **Node Version:**
v4.8.0

* **npm Version:**
2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**
```JSON
{
    "plugins": [
        "jsdoc"
    ],
    "env": {
        "node": true,
        "es6": true
    },
    "extends": "airbnb-base",
    "rules": {
        "no-multi-spaces": "off",
        "indent": "off",
        "padded-blocks": "off",
        "no-bitwise": "off",
        "strict": "off",
        "comma-dangle": "off",
        "no-restricted-properties": "off",
        "no-console": "off",
        "prefer-spread": "off",
        "lines-around-directive": "off",
        "spaced-comment": ["error", "always", {
            "exceptions": [":", "*"]
        }],

        "prefer-rest-params": "off",

        "jsdoc/check-param-names": 1,
        "jsdoc/check-tag-names": 1,
        "jsdoc/check-types": 1,
        "jsdoc/require-description-complete-sentence": 0,
        "jsdoc/require-hyphen-before-param-description": 1,
        "jsdoc/require-param": 1,
        "jsdoc/require-param-description": 1,
        "jsdoc/require-param-type": 1,
        "jsdoc/require-returns-description": 1,
        "jsdoc/require-returns-type": 1
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
     const logger /*: Logger */ = {
         levels: LEVELS
     };
```

**What did you expect to happen?**
No eslint errors or warnings.

**What actually happened? Please include the actual, raw output from ESLint.**

`  119:19  error  Expected exception block, space or tab after '/*' in comment  spaced-comment`

**Comment by alberto** [comment]
Not entirely sure from the rule description or the tests, but it looks like "exception" is intended to match full-lines (ASCII art), so I don't know if it's working by design or it is a bug.

Anyways, you can use `markers: ["!"]` to achieve what you want.

**Comment by psiphi75** [comment]
Thanks.  I used `"markers": [":", "::"]` and it solved the problem.  Not a bug.
