### ISSUE TITLE
Inspect your JavaScript file(s) read EINVAL

### ISSUE THREAD

**Issue by Mac-lp3** [eslint/eslint#8252]
**Tell us about your environment**
Windows 7 SP1

* **ESLint Version:**
v3.17.1

* **Node Version:**
v6.10.0

* **npm Version:**
3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**What did you do? Please include the actual source code causing the issue.**

I ran `npm install JSLint --save-dev` which ran successfully.
However, when I try to run `node_modules\.bin\eslint --init` I receive the following exception:

```js

? How would you like to configure ESLint? (Use arrow keys)
> Answer questions about your style
  Use a popular style guide
  Inspect your JavaScript file(s) read EINVAL
Error: read EINVAL
    at exports._errnoException (util.js:1022:11)
    at TTY.onread (net.js:569:26)
tty.js:38
  this._handle.setRawMode(flag);
              ^

TypeError: Cannot read property 'setRawMode' of null
    at ReadStream.setRawMode (tty.js:38:15)
    at Interface._setRawMode (readline.js:200:16)
    at Interface.close (readline.js:317:10)
    at UI.close (C:\Users\C42056\Documents\dev\CignaScreen\CignaScreen-TH\node_modules\inquirer\lib\ui\baseUI.js:54:11)
    at UI.onForceClose (C:\Users\C42056\Documents\dev\CignaScreen\CignaScreen-TH\node_modules\inquirer\lib\ui\baseUI.js:34:8)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)

```

The script crashes before I can input anything into the first question about style guides.

I have not had the chance to modify anything either. Do you know what could be causing this?

Thanks!

**Comment by not-an-aardvark** [comment]
What terminal are you using to run `node_modules/.bin/eslint --init`?

**Comment by Mac-lp3** [comment]
Just the command prompt in admin mode

**Comment by vitorbal** [comment]
Any chance you are using Cygwin? This looks like a known issue with Cygwin and Inquirer: https://github.com/SBoudrias/Inquirer.js/issues/194

**Comment by Mac-lp3** [comment]
No, I don't have Cygwin installed on this machine. Just using the basic command prompt (in admin mode).

**Comment by not-an-aardvark** [comment]
Is this issue still occurring?

**Comment by not-an-aardvark** [comment]
Closing because there was no response. Feel free to create a new issue if this is still occurring.
