### ISSUE TITLE
Change Rule: Object in Arrays new line

### ISSUE THREAD

**Issue by JPeer264** [eslint/eslint#8254]
**What rule do you want to change?**
`array-bracket-spacing` - option `objectsInArrays` maybe also `arraysInArrays`

**Does this change cause the rule to produce more or fewer warnings?**
Yes - if the option is set

**How will the change be implemented? (New option, new default behavior, etc.)?**

A new option for `objectsInArrays` would be implemented: `newLine`. `newLine` would be available with the option `always` and `never` (see code examples below)

**Please provide some example code that this change will affect:**

```js
/*eslint array-bracket-spacing: ["error", "always", { "objectsInArray": false }]*/

const otherArray = [ 1, 2, 3 ];
const someArray = [{
  one: 'value',
  two: 'value',
}, {
  one: 'value',
  two: 'value',
}];
```
or
```js
/*eslint array-bracket-spacing: ["error", "always", { "objectsInArray": "newLine" }]*/
const otherArray = [ 1, 2, 3 ];
const someArray = [
  {
    one: 'value',
    two: 'value',
  },
  {
    one: 'value',
    two: 'value',
  },
];
```
or
```js
/*eslint array-bracket-spacing: ["error", "never", { "objectsInArray": "newLine" }]*/
const otherArray = [1, 2, 3];
const someArray = [
  {
    one: 'value',
    two: 'value',
  },
  {
    one: 'value',
    two: 'value',
  },
];
```

**What does the rule currently do for this code?**
It does not care about new lines for objects in arrays

**What will the rule do after it's changed?**
It will enforce you to start the object in a new line

**Comment by not-an-aardvark** [comment]
Would this functionality be covered by https://github.com/eslint/eslint/issues/6073?

**Comment by JPeer264** [comment]
If there would be the option `"objectsInArrays": true/false` or `arraysInArrays` then yes.

**Comment by JPeer264** [comment]
`array-bracket-newline` will cover my expected behavior.
