### ISSUE TITLE
Regression: ESLint is slow generating file lists for directories with large dot folders, e.g. Mercurial repositories, even when not including dot files

### ISSUE THREAD

**Issue by Standard8** [eslint/eslint#8259]
**Tell us about your environment**

* **ESLint Version:** 3.12.2 / 3.4.0
* **Node Version:** 7.7.2
* **npm Version:** 4.1.2
MacBook Pro Mid 2015.

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

Please see https://dxr.mozilla.org/mozilla-central/source/

**What did you do? Please include the actual source code causing the issue.**

Run eslint on the repository, and compared the timings. For a full run on our repository, a git cinnabar checkout runs in 2m 13. For a Mercurial checkout it runs in 3m 45.

**What did you expect to happen?**

The repositories should take about the same time - the repository format shouldn't matter.

This seemed to be regressed in version 3.5.0 by #6844.

**What actually happened? Please include the actual, raw output from ESLint.**

The Mercurial has a large `.hg` folder (320268 files on my checkout). Whereas a git checkout has a much smaller `.git` folder (3857 files).

If the repository is checked out via Mercurial, then for an eslint run, the start of the debug looks like:

```
$ ./tools/lint/eslint/node_modules/.bin/eslint --debug .
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +26ms
  eslint:ignored-paths Looking for ignore file in /Users/mark/dev/mozilla-central +3ms
  eslint:ignored-paths Loaded ignore file /Users/mark/dev/mozilla-central/.eslintignore +0ms
  eslint:ignored-paths Adding /Users/mark/dev/mozilla-central/.eslintignore +0ms
  eslint:cli-engine Processing /Users/mark/dev/mozilla-central/accessible/jsat/content-script.js +52s
```

If the repository is checked out into a git repository (via git-cinnabar), then the eslint run looks like:

```
$ ./tools/lint/eslint/node_modules/.bin/eslint --debug .
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +24ms
  eslint:ignored-paths Looking for ignore file in /Users/mark/dev/gecko +3ms
  eslint:ignored-paths Loaded ignore file /Users/mark/dev/gecko/.eslintignore +0ms
  eslint:ignored-paths Adding /Users/mark/dev/gecko/.eslintignore +0ms
  eslint:cli-engine Processing /Users/mark/dev/gecko/accessible/jsat/content-script.js +7s
```

The +52s -> +7s is quite a big difference. If I include all the extensions that we process via `--ext` then this gets even worse (2m vs 12s).

#6844 enabled parsing of dot files, and enabled searching for them via `GlobSync`. If, as a temporary test, I change the glob options to set `dot` to `false`, then the timings are about the same for both repositories.

https://github.com/eslint/eslint/blob/d6150e300e86e2e55a6a3d048dfb6072ac2b6489/lib/util/glob-util.js#L167

**Comment by alberto** [comment]
So, use git? ¯\_(ツ)_/¯

Just kidding :D. While we decide what to do here, I think adding '.hg' to your `.eslintignore` file should fix it for you.

**Comment by Standard8** [comment]
> Just kidding :D. While we decide what to do here, I think adding '.hg' to your .eslintignore file should fix it for you.

So from my limited understanding of the code, I didn't think it would, however, I can confirm it does help a lot (3m40 -> 2m).

Thanks!

**Comment by alberto** [comment]
The magic is [here](https://github.com/eslint/eslint/blob/13eead9fc9809acfecf4838536c7392c72d974e3/lib/ignored-paths.js#L200) ;)

**Comment by alberto** [comment]
@IanVS I didn't check, but it looks like https://github.com/eslint/eslint/pull/6844 changed the behaviour for hidden folders and that would be unintentionally?

**Comment by IanVS** [comment]
I'll need to think about it some more, but I don't think it was unintentional.  The point of the PR was to allow linting dot files/folders.

My immediate reaction is to suggest we add `.git` and `.hg` to the list of default ignored folders, the same way we ignore `node_modules` and `bower_components`.  I can't think that users would ever want to lint the files in those folders (besides, there's still an escape hatch if they do).

**Comment by platinumazure** [comment]
@IanVS Maybe `.svn` as well?

**Comment by alberto** [comment]
LOL, it looks like we already had this discussion.

https://github.com/eslint/eslint/issues/4828#issuecomment-201626456

My understanding from that is we didn't intend to lint hidden folders by default unless explicitly passed in as targets, just to add a way to allow it. I would argue this should be the default if it's currently not.

**Comment by IanVS** [comment]
I think I've figured out what's going on here, and will have a PR shortly.

As @alberto correctly pointed out, we do already ignore dotfiles and dotfolders by default.  _But_ we aren't correctly preventing globs from traversing through dotfolders.  We had a PR a while back to improve our performance by not returning all of the files within `node_modules` from the glob (https://github.com/eslint/eslint/pull/6783), and this will be similar.

@Standard8 the reason that adding `.hg` to your ignore file improved performance is because we are preventing glob traversal through custom ignore patterns and `node_modules`, but not dotfolders.  :man_facepalming: After my PR, I would expect you to be able to remove `.hg` from your ignore file without a performance hit.

**Comment by alberto** [comment]
Awesome, that was my initial thought, but I was unsure why `.*` didn't ignore dotfolders. I guess that's a glob vs git thing?

I think we should try to get this into v.4.0.0

**Comment by not-an-aardvark** [comment]
It's not a breaking change anyway, is it? We could still merge it in a patch release even if it doesn't end up going into v4.0.0.

**Comment by alberto** [comment]
It changes the logic of the files we lint, so...

**Comment by not-an-aardvark** [comment]
Based in @IanVS's comment, my understanding was that we're already ignoring `.hg` either way -- the issue is that we're still matching globs against it, which hurts performance even though we get rid of the matches afterwards.

**Comment by IanVS** [comment]
Yes, they are not linted currently.  The end result will be the same, it should just be a performance improvement.

**Comment by not-an-aardvark** [comment]
Removing this from the milestone because it doesn't need to go in a major release.
