### ISSUE TITLE
Rule: forbid escaped quotes

### ISSUE THREAD

**Issue by FarSeeing** [eslint/eslint#826]
Up to now in quotes rule the `avoid-escape` option just allows you to use another type of  quotes to skip escaping of inline ones.
I. e. when you set rule to `[1, "single", "avoid-escape"]` it will not complain about
`"it's a quote"` string.
But it will also accept `'it\'s a quote'` string.
Any ability to forbid escaping quotes at all?

**Comment by IanVS** [comment]
This issue has been around for over a year with no movement.  Is that an indication that demand is low and it can be closed?

**Comment by FarSeeing** [comment]
I guess so.

**Comment by nzakas** [comment]
Agree. @FarSeeing you are still free to create a custom rule if you need this functionality.
