### ISSUE TITLE
Scheduled release for April 7, 2017

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8261]
The scheduled release on Friday, April 7, 2017 is assigned to:

* @ilyavolodin
* @kaicataldo 

**Note**: This release will be a 4.x alpha release.

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by platinumazure** [comment]
Assigning @ilyavolodin and @kaicataldo to this release based on discussion from last TSC meeting. Please arrange a substitute if you can't do the release on 7 April. Thanks!

**Comment by not-an-aardvark** [comment]
Closing this issue because the release is finished.
