### ISSUE TITLE
Change from escope to eslint-scope

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#8266]
Now that we forked escope, we should update eslint to use `eslint-scope`. This should be part of 4.0 release, as it would enable people to write rules for type annotations.

**Comment by not-an-aardvark** [comment]
I thought the TSC already approved this from https://github.com/eslint/tsc-meetings/issues/16#issuecomment-251245605.

**Comment by ilyavolodin** [comment]
Good catch. I created this issue just so we don't forget about it. Will mark as accepted.

**Comment by nzakas** [comment]
Just a reminder - this is breaking for babel-eslint, so we should coordinate.
