### ISSUE TITLE
Proposal: enhance `no-restricted-syntax` to support custom error messages

### ISSUE THREAD

**Issue by vitorbal** [eslint/eslint#8298]
**What version are you using?**
v3.18.0

**What did you do?**
```js
/* eslint no-restricted-syntax: ["error", "CallExpression[callee.name='setTimeout'][arguments.length!=2]"] */
setTimeout(() => {}, 100, 'foo');
```

**What happened?**
I got the following error message:
```bash
  2:1  error  Using 'CallExpression[callee.name='setTimeout'][arguments.length!=2]' is not allowed  no-restricted-syntax
```

**What did you expect to happen?**
I would like to be able to provide custom error messages for the syntax patterns I prohibit using `no-restricted-syntax`. For the example above:

```js
/*
 * eslint no-restricted-syntax: [
 *     "error",
 *     {
 *         "pattern": "CallExpression[callee.name='setTimeout'][arguments.length!=2]",
 *         "message": "invoking setTimeout with more than 2 arguments is not allowed"
 *     }
 * ]
 */
setTimeout(() => {}, 100, 'foo');
```

Would provide the following error message:
```bash
  2:1  error  invoking setTimeout with more than 2 arguments is not allowed  no-restricted-syntax
```

**Rationale**
With the release of the AST selectors feature, the `no-restricted-syntax` rule just got super powerful, which is awesome.
However, when a complex selector is used to prohibit a certain syntax pattern, the error message can be quite cryptic for devs that are not familiar with the AST selectors.

This proposal aims to allow the customization of the error messages for each of the syntax patterns configured for `no-restricted-syntax`.

This proposal would be backwards compatible, since the rule logic can check if the passed-in option is a string (old format) or an object (new format). For example:
```js
"no-restricted-syntax": [
    "error",
    "WithStatement",
    "FunctionDeclaration[params.length>3]",
    {
        "pattern": "CallExpression[callee.name='setTimeout'][arguments.length!=2]",
        "message": "invoking setTimeout with more than 2 arguments is not allowed"
    }
]    
```

**Comment by not-an-aardvark** [comment]
:+1:

I'd been planning to suggest this as well, and I'm willing to champion it. One bikeshed is that maybe the option should be called `selector` instead of `pattern`.

**Comment by platinumazure** [comment]
Who's championing? If @vitorbal counts as a :+1: or champion as a result of creating this issue, we can accept now :smile:

**Comment by vitorbal** [comment]
I would also be willing champion this, but I guess it doesn't matter :D 
I'm willing to implement it as well, if @not-an-aardvark doesn't mind?

**Comment by dwelle** [comment]
It'd be great if this was implemented for all `no-restricted-*` rules. In fact, I can see it useful even for other rules, but I'd say custom messages for `no-restricted-*` rules is the bare minimum.

Related https://github.com/eslint/eslint/issues/8315

**Comment by vitorbal** [comment]
@dwelle thanks for your suggestion, I think that's a good idea! Could you open a separate issue with the proposal to add custom messages to the other `no-restricted-` rules?

**Comment by dwelle** [comment]
@vitorbal https://github.com/eslint/eslint/issues/8400
