### ISSUE TITLE
Remove Changelog from npm package

### ISSUE THREAD

**Issue by baweaver** [eslint/eslint#8316]
While looking for some larger files in `node_modules`, I'd noticed that the CHANGELOG is getting bundled:

```
268K    ./node_modules/eslint/CHANGELOG.md
```

This appears to be happening on `3.18.0`

Thanks for your time in reading!

**Comment by not-an-aardvark** [comment]
I think the changelog is an important part of our documentation, so it makes sense to include it in the package. This is also why [npm always includes changelogs in the package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

**Comment by baweaver** [comment]
That may be the case, but after a while that size can get out of hand, no?

**Comment by baweaver** [comment]
That, and it's very easily findable on Github.

**Comment by platinumazure** [comment]
@baweaver As noted in @not-an-aardvark's link, npm will always include the changelog even if we try to tell npm to ignore it. Thus, the only way we could get it out of the package is to remove it from GitHub, which means nobody could read it.

I suppose theoretically, we could remove older release notes from CHANGELOG and put it in some sort of archive that doesn't get included in the package, but why should we do that really? Just seems like an extra maintenance burden for not a lot of gain.

**Comment by not-an-aardvark** [comment]
Looks like the team isn't in favor of this proposal, so I'm closing it.
