### ISSUE TITLE
Parsing error: Unexpected token = with class properties

### ISSUE THREAD

**Issue by Drapegnik** [eslint/eslint#8346]
**mac os**

* **ESLint Version:** `3.18.0`
* **Node Version:** `6.9.4`
* **npm Version:** `3.10.10`

**What parser (default, Babel-ESLint, etc.) are you using?** `default`

```
{
  "extends": "airbnb",
  "env": {
    "browser": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
static propTypes = { <-- error here
```

**What did you expect to happen?** 
I've see a lot of related issues, but they was fixed, and I don't understand how to fix it

**What actually happened? Please include the actual, raw output from ESLint.**
`error  Parsing error: Unexpected token =`

**Comment by platinumazure** [comment]
Hi @Drapegnik, thanks for the issue. Class properties are experimental syntax and are not supported by espree at this time. Please use the babel-eslint parser.

**Comment by not-an-aardvark** [comment]
Closing this issue since the question seems to be answered.

**Comment by OKNoah** [comment]
This issues began suddenly for me as well,

```
"settings": {
    "import/parser": "babel-eslint",
    "import/resolve": {
      "moduleDirectory": ["node_modules", "src"]
    }
  },
```

**Comment by AlexMiroshnikov** [comment]
I also have such a problem - `error  Parsing error: Unexpected token =`
Config:
```
"settings": {
    "import/parser": "babel-eslint",
    "import/resolve": {
      "moduleDirectory": ["node_modules", "src"]
    }
  },
```
Versions:
```
./node_modules/eslint/bin/eslint.js -v
v3.19.0

node -v
v7.10.0

npm -v
4.2.0

npm list | grep -P 'eslint|babel' | grep -P '^├'
├─┬ babel-core@6.25.0
├── babel-eslint@7.2.3
├─┬ babel-loader@7.0.0
├── babel-plugin-add-module-exports@0.2.1
├── babel-plugin-react-transform@2.0.2
├─┬ babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-react-display-name@6.25.0
├── babel-plugin-transform-runtime@6.23.0
├── babel-plugin-typecheck@3.9.0
├─┬ babel-polyfill@6.23.0
├─┬ babel-preset-es2015@6.24.1
├─┬ babel-preset-react@6.24.1
├─┬ babel-preset-stage-0@6.24.1
├─┬ babel-register@6.24.1
├── babel-runtime@6.23.0
├─┬ eslint@3.19.0
├─┬ eslint-config-airbnb@14.1.0
├─┬ eslint-loader@1.8.0
├─┬ eslint-plugin-import@2.3.0
├─┬ eslint-plugin-jsx-a11y@4.0.0
├─┬ eslint-plugin-react@6.10.3
```
Code:
```
static asyncRequest = (dispatch, getState) => ...
```

**Comment by platinumazure** [comment]
@AlexMiroshnikov Please open an issue in the babel-eslint repo. Thanks!
