### ISSUE TITLE
error on non-standard global, warn on deprecated globals in no-undef

### ISSUE THREAD

**Issue by graingert** [eslint/eslint#8352]
**Tell us about your environment**

* **ESLint Version:** v3.17.1
* **Node Version:** 7.6
* **npm Version:** yarn

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint (n/a)
**Please show your full configuration:**
n/a

With no-undef and env: {browser: true} and code:
```js
event.preventDefault()
```

no undef error is thrown.

This is because event exists as a global temporally in some browsers, however it's a non-standard property: https://developer.mozilla.org/en-US/docs/Web/API/Window/event

**Comment by alberto** [comment]
Previous discussion: https://github.com/eslint/eslint/issues/3964

**Comment by graingert** [comment]
I think this is worth re-considering now that IE8, IE9, IE10 are EOL.

**Comment by ilyavolodin** [comment]
@graingert As far as I know global `event` also exists in WebKit browsers (so Chrome, Safari and Opera). Basically, the only browser that doesn't have it is Firefox. We have `no-restricted-globals` rule that you can use to blacklist this global.

**Comment by mysticatea** [comment]
I hadn't noticed that the `event` global variable is non standard. In that case, the ` event` variable is environment specific matter, ` browser` environment should not include it. `IE`, `webkit` or something like should include it.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
