### ISSUE TITLE
`eslint --quiet --fix` fixes warnings

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#8353]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** v6.10.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
{
  "globals": {},
  "env": {},
  "rules": {
    "quotes": "warn",
    "semi": "error",
    "no-unused-vars": "error"
  },
  "parserOptions": {},
  "root": true
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
var foo = 'foo'
```

This produces the following errors running: `eslint foo.js`
```
  1:5   error    'foo' is assigned a value but never used  no-unused-vars
  1:11  warning  Strings must use doublequote              quotes
  1:16  error    Missing semicolon                         semi
```

Running `eslint --quiet` only outputs errors, as expected:
```
  1:5   error  'foo' is assigned a value but never used  no-unused-vars
  1:16  error  Missing semicolon                         semi
```
**What did you expect to happen?**
Running `eslint foo.js --quiet  --fix` would only report and fix errors

**What actually happened? Please include the actual, raw output from ESLint.**
eslint also fixed the warning on "quotes"
```js
var foo = "foo";
```

**Comment by Slayer95** [comment]
I disagree with the notion of this being a bug.
--quiet is interpreted as a logging modifier flag, kind of the opposite of --verbose, and it therefore shouldn't suppress the side effects of --fix.

**Comment by gyandeeps** [comment]
I think it makes sense what @Slayer95 said above. `quite` is a log level modifier and not a operation level modifier. With that being said, its working as expected.
@eslint/eslint-team thoughts?

**Comment by platinumazure** [comment]
I can see it both ways. The fact that the behavior can be seen as extremely unexpected and/or damaging to the user is definitely a bad thing, in my mind.

I think the best way to fix this is to allow users the option to go either way and to be very explicit about how the options work.

Here's one proposal along those lines:
* Rename `--quiet` to `--no-report-warnings` (supporting `--quiet` as an alias and preserving its behavior), to avoid reporting warnings but possibly fix them
* Add option `--no-fix-warnings` to support not running autofix on warnings but possibly report them
* Users can use both to completely ignore warnings altogether

The first point above isn't critical for the situation alberto described, but it does allow ESLint CLI to be much more intuitive to users.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
