### ISSUE TITLE
eslint '' checks your entire filesystem

### ISSUE THREAD

**Issue by w0rp** [eslint/eslint#8362]
* **ESLint Version:** v3.18.0
* **Node Version:** v6.4.0
* **npm Version:** _yarn_ v0.16.1

If you run `eslint ''`, eslint will check for errors across your entire filesystem. I first noticed this when I made a mistake in writing a script which ran eslint, and wrote `"$fix"` for a variable which was either `'--fix'` or `''`. When I didn't pass the `--fix` option to my own script, this then caused eslint to check the entire filesystem.

I suggest handling empty string paths, and either ignoring them completely, or throwing an exception.

**Comment by not-an-aardvark** [comment]
I can reproduce this issue. Thanks for reporting.
