### ISSUE TITLE
'Parsing error: Unexpected token function' using async/await + ecmaVersion 2017

### ISSUE THREAD

**Issue by BlueRaja** [eslint/eslint#8366]
**Tell us about your environment**

* **ESLint Version:** 3.18.0
* **Node Version:** 7.7.3
* **npm Version:** 4.1.2

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  extends: ['eslint:recommended', 'airbnb-base'],
  env: {
    'node': true
  },
  rules: {
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'func-names': 'off',
    'no-multi-spaces': 'off',
    'spaced-comment': ["error", "always", { "markers": ["/"] }],
    'comma-dangle': ['error', 'always-multiline'],
    'padded-blocks': 'off',
    'linebreak-style': 'off',
    'class-methods-use-this': 'off',
    'indent': ['error', 2],
    'max-len': ['error', 120, 2, { ignoreComments: true }],
    'no-unused-vars': ['error', { vars: 'local', args: 'after-used' }],
    'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
    'no-nested-ternary': 'off',
    'no-underscore-dangle': ['error', {'allow': ['_super', '_lookupFactory']}],
    'object-shorthand': ['error', 'methods'],
  }
```

**What did you do? Please include the actual source code causing the issue.**

```js
describe('Some Mocha Test', () => {
  let target, context, exampleGame;
  ...
  const checkAttributes = function (callback) {
    return async function () { // Error here
      return callback(await target.getAttributesAsync(exampleGame, context));
    };
  };
}
```

**What did you expect to happen?**
eslint passes

**What actually happened? Please include the actual, raw output from ESLint.**
eslint fails with
```
error  Parsing error: Unexpected token function
```

A similar issue happens with `=>`, as noted [here](https://github.com/eslint/eslint/issues/1657#issuecomment-290515043)

**Comment by BlueRaja** [comment]
I think I discovered the issue, it looks like it's our fault ^_^'

There was an .eslint.rc file overriding the `ecmaVersion` in a subfolder

**Comment by platinumazure** [comment]
This code fails in our [parser demo](http://eslint.org/parser/) with ecmaVersion at 8. Is our demo wrong/misconfigured, or is this code invalid syntax?

```js
describe('Some Mocha Test', () => {
  let target, context, exampleGame;

  const checkAttributes = function (callback) {
    return async function () { // Error here
      return callback(await target.getAttributesAsync(exampleGame, context));
    };
  };
});
```

**Comment by not-an-aardvark** [comment]
@platinumazure I think that's caused by https://github.com/eslint/eslint.github.io/issues/339.

**Comment by maicss** [comment]
Has this fixed?

I installed version `4.1.1`, still shows the same error.

**Comment by not-an-aardvark** [comment]
This was not a bug. Feel free to visit our [gitter channel](https://gitter.im/eslint/eslint) if you're having trouble configuring ESLint.

**Comment by nojvek** [comment]
So what is the correct config for this. Gitter channel is super noisy to find an actual answer to such a common problem.

**Comment by not-an-aardvark** [comment]
To enable parsing for async functions, you should include this in your config:

```json
{
    "parserOptions": {
        "ecmaVersion": 2017
    }
}
```

**Comment by nojvek** [comment]
Thanks a lot.

**Comment by vuongtran** [comment]
Many thanks.
