### ISSUE TITLE
Docs: no-use-before-define docs reference "blockBindings"

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8368]
Examples in [no-use-before-define docs](http://eslint.org/docs/rules/no-use-before-define) refer to obsolete blockBindings property (part of ecmaFeatures but was subsumed into ecmaVersion:6).

I'm not 100% sure what to do with the examples, so I'm leaving this as an issue.

**Comment by not-an-aardvark** [comment]
If `blockBindings` was just used to enable `let` and `const` parsing, could we just replace the `blockBindings` references with `ecmaVersion: 6`?

**Comment by platinumazure** [comment]
Given that `/* eslint-env: es6 */` is already present in the examples, that's what I was hoping.

However, I was confused by this section (from correct examples):

```js
// With blockBindings: true
{
    let C;
    c++;
}
```

Observe the different casing. I can't tell if that's a typo or if that is significant in some way.

**Comment by entergmode** [comment]
Hi @not-an-aardvark , I would like to help with this issue if it's okay. This is my first PR to open source, so please kindly advise :). I like eslint, hopefully can contribute to code and tests someday, but now I would like to get started with improving the documentation.

Would you mind indicating what we need here to get it done please?  From what I see we would like:
1. Fix the typo (declaring variable `c` before using it `c++`)
2. Remove the comment `// With blockBindings: true` ?

Thanks a lot and look forward to your reply! Appreciate your patience on me :)

Cheers,
Steven

**Comment by not-an-aardvark** [comment]
@entergmode Thanks for contributing! Yes, I think the two items you mentioned are correct.

Feel free to let me know if you have any other questions. As an unrelated note, our [Pull Request Guide](https://eslint.org/docs/developer-guide/contributing/pull-requests) has some useful guidelines for submitting a PR to ESLint.

**Comment by entergmode** [comment]
@not-an-aardvark Thanks for giving me the chance. I'm on it

**Comment by Divya063** [comment]
@not-an-aardvark Is @entergmode  still working on this issue?

**Comment by not-an-aardvark** [comment]
I don't know anything about work that's been done on this issue aside from what's been discussed in the comments.

That said, if you're interested in making this fix we'd certainly welcome the contribution.
