### ISSUE TITLE
https://github.com/eslint/eslint/issues/8293 closed but node module not updated :(

### ISSUE THREAD

**Issue by bhatyogesh94** [eslint/eslint#8377]
**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

```




```

**What did you do? Please include the actual source code causing the issue.**

```js





```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by vitorbal** [comment]
Hi @bhatyogesh94, thanks for your issue!
ESLint is on a 2-week release cycle, so the ticket you mentioned is ready to be shipped with the new version of ESLint, which will be released later today.
Thanks for your understanding!

**Comment by not-an-aardvark** [comment]
ESLint 3.19.0 was released today with a fix for this.
