### ISSUE TITLE
Lint rules for specific ES6 features?

### ISSUE THREAD

**Issue by kaspnilsson** [eslint/eslint#8379]
Hey all,

I'm looking to migrate my project to ES6, and planning on using ESLint to do it. My team has decided on a specific subset of features to use, some of which _seem_ to not have lint rules. These features are:
- Class inheritance
- Preferring for-of to Array.forEach
- Using the set data structure instead of e.g. object enums

I'd imagine some of these are pretty hard to lint for, so it definitely makes sense that they wouldn't be supported by ESLint -- but it's entirely possible I just missed the rules. Does anyone know if these exist?

Thanks!

**Comment by JPeer264** [comment]
For using `Array.forEach` over `for..of` you can use the rule [no-restricted-syntax](http://eslint.org/docs/rules/no-restricted-syntax):
```js
'no-restricted-syntax': [
  'error',
  'ForOfStatement',
]
```

**Comment by kaspnilsson** [comment]
Actually, it's the opposite. I do want for-of instead of Array.forEach.  I think I can use that rule for Array.forEach, though.

**Comment by vitorbal** [comment]
Thanks for your issue, @kaspnilsson!
I think you can restrict the syntax features you listed using `no-restricted-syntax`, as @JPeer264 suggested, especially now that it supports [AST selectors](http://eslint.org/docs/developer-guide/selectors). Would that not be enough for your use-case?

**Comment by mysticatea** [comment]
There is not a rule like `prefer-for-of` in core, but it exists in [my plugin](https://github.com/mysticatea/eslint-plugin#eslint-plugin-mysticatea).

I thought it's aggressive for core, but if somebody wants the rule, I can transfer the rule to core.

**Comment by kaspnilsson** [comment]
@vitorbal I think using the selectors is good enough, thanks. Truth be told, I was hoping for a full rule to be implemented in the hopes that there was an auto fix as well :)

@mysticatea It would be cool to have it explicitly... I personally don't see an issue with having aggressive rules in core as long as they're optional, but it's not my judgement.

**Comment by not-an-aardvark** [comment]
Closing because it looks like this question has been answered.
