### ISSUE TITLE
`quotes` `avoidEscape`-type option to allow requiring template literals when both quote styles present

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#8380]
Not in a position atm to submit a PR for this, but as I think it fits nicely with an already existing rule, I wanted to suggest either adding a new option to `quotes` or expanding its `avoidEscape` option beyond booleans to allow for enforcing that templates will be used when both single quotes and double quotes are present in a string (and when no tags or embedded expressions are present). I run into this when reporting errors where I otherwise normally prefer single quotes, and then double quotes where single quotes are present, and if not, only then template literals where it helps avoid escaping single and double quotes. (I prefer template literals to be reserved for when substitutions are used.)

**Comment by not-an-aardvark** [comment]
I think this might be a duplicate of https://github.com/eslint/eslint/issues/7660.

If not, may you please fill out the [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md)? This makes it easier for team members to triage enhancement requests. Thanks!

**Comment by brettz9** [comment]
Yes, sorry, it's a dupe. Thanks!
