### ISSUE TITLE
Cyclomatic Complexity rule documentation links to jscomplexity.org which is no longer available.

### ISSUE THREAD

**Issue by Standard8** [eslint/eslint#8396]
**Tell us about your environment**

* **ESLint Version:** Latest

**What did you expect to happen?**

Visit the further detail links on http://eslint.org/docs/rules/complexity#further-reading and find valid sites.

**What actually happened?**

http://jscomplexity.org/complexity is unavailable. The second link also has links to the first one, which is unavailable.

Hence it is difficult to determine the basis for how complexity is calculated without reading the code.

**Comment by gyandeeps** [comment]
Do you want to send a PR to fix it?

**Comment by Standard8** [comment]
Unfortunately I don't know if there's an alternative to that site. I think the rule needs some sort of fuller description available, as otherwise you don't know how it is generated.

The best I could find was an [unmaintained github repo](https://github.com/escomplex/JSComplexity.org) of the original site, but I was hoping that someone would know a better place to look.

**Comment by SpadeAceman** [comment]
The [Wikipedia article](https://en.m.wikipedia.org/wiki/Cyclomatic_complexity) does a decent job of explaining McCabe's cyclomatic complexity, and what the `complexity` rule is generally measuring (though not how it specifically relates to Javascript).

And [this article](https://craftsmanshipforsoftware.com/2015/05/25/complexity-for-javascript/) explains what the `complexity` rule *doesn't* measure in Javascript, which is helpful to know.

Finally, I found a number of other potentially helpful links when researching #4808.

**Comment by vitorbal** [comment]
Thanks for the links, @SpadeAceman! Would you be willing to send a PR to add them?
