### ISSUE TITLE
Add .jsx to the default --ext extensions list

### ISSUE THREAD

**Issue by edmorley** [eslint/eslint#8399]
Using eslint 3.19.0, the default value for `--ext` is `.js`:
http://eslint.org/docs/user-guide/command-line-interface#ext

For projects that use JSX, this needs to be overridden to `--ext .jsx,.js` so that the JSX files are included. However according to #3469 this can only be done via the CLI and not via `.eslintrc`, due to file traversal happening before the configs are read.

Presuming that's still the case, it would be really helpful to change the default for `--ext` such that it also includes .jsx. 

For people who don't have any .jsx files in their repository, this will be a no-op, and for those that do, it will mean the ability to use eslint without CLI boilerplate (or having to wrap with package.json run-scripts) - and mean it's harder to accidentally forget to lint your JSX files (as just happened in one of the projects I work on).

I'm presuming that such a change will need to be semver major, in case people with .jsx files in their repo aren't already using `--ext` and have lint errors in those files.

**Comment by kaicataldo** [comment]
Apologies that we missed this. We can keep the discussion in the PR, but wanted to add some labels.

**Comment by not-an-aardvark** [comment]
Closing because https://github.com/eslint/eslint/pull/8515 was closed.
