### ISSUE TITLE
Scheduled release for April 21, 2017

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8404]
The scheduled release on Friday, April 21, 2017 is assigned to:

* @not-an-aardvark 
* @kaicataldo

**Note**: This release will be a 4.x alpha or beta release.

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by platinumazure** [comment]
**TSC Summary**: Need to schedule two people for this release, per usual procedure. Also, need to determine if we want to have this release on April 14th (to get back in line with TSC meetings) or to push it out a week or two.

**TSC Question**: When should this release occur? Should it be regarded as an alpha or beta release? Who wants to sign up for this release?

**Comment by kaicataldo** [comment]
v4.0.0-alpha.1 has been released. We had a few issues during this release:
- The [changelog](https://github.com/eslint/eslint/commit/1c7efbd299029492b3b25bf3bd08daafb508178f) wasn't populated with the commits in this release
- I was unable to generate the site locally. @not-an-aardvark was able to run it after doing a fresh `npm install` (which I had done before starting the release).

**Comment by not-an-aardvark** [comment]
This release is finished, so I'm removing it from the TSC agenda.

**Comment by platinumazure** [comment]
My apologies. I had assumed that as TSC assigned themselves to the release, that they would remove the label. In future, I can try to keep an eye on the release issues.

**Comment by not-an-aardvark** [comment]
Not a problem, I think someone from the TSC probably should have removed the label.

**Comment by kaicataldo** [comment]
Yeah, we just missed it :)
