### ISSUE TITLE
[Rule Option]arrow-body-style allowReturnForObjectLiteral

### ISSUE THREAD

**Issue by Stupidism** [eslint/eslint#8411]
## What I want to propose
There is a `requireReturnForObjectLiteral` option for `as-needed` mode of rule `arrow-body-style`.
I think it's wrong, or we need another option `allowReturnForObjectLiteral`.
## Current Situation
Normally, we think there are 3 kinds of arrow functions.
1. [need-block]: excutes some expression and returns sth
```
const modifyName = (obj, name) => {
   obj.name = name;
   return obj;
}
```
2. [need-no-block]: only excutes one expression and returns its result
```
const addRandomName = (obj) => modifyName(obj, generateRandomName())
```
3. [return-object]: returns simple object literal like a property change:
```
const newObjWithNameProp = (obj, name) => ({ ...obj, name })
```
## Problem
**However, there's 4th type**
4. [return-map]: returns complex object literal like an object mapper and changes very often:
```
const transfterForSomeUsage = ({ a, b, c, d }) => {
  return {
    a: modifyName(a, 'nameA'),
    b: addRandomName(b),
    c: newObjWithNameProp(c, 'nameC'),
    d: newObjWithNameProp(d, a.id + b.id + c.id),
  }
}
``` 
This function would be required to remove block in mode `as-needed` because the block can be omitted. So we have to write it like this: 
```
const transfterForSomeUsage = ({ a, b, c, d }) => ({
  a: modifyName(a, 'nameA'),
  b: addRandomName(b),
  c: newObjWithNameProp(c, 'nameC'),
  d: newObjWithNameProp(d, a.id + b.id + c.id),
});
```
But if we want to use some middle variables somehow the whole block will be `diffed` instead of `the added variable and fields really been affected`.

**It's causing unnecessary git changes!**
```
const transfterForSomeUsage = ({ a, b, c, d }) => {
  const namePrefixForAD = b.prefix + c.prefix;
  return {
    a: modifyName(a, namePrefixForAD + 'nameA'),
    b: addRandomName(b),
    c: newObjWithNameProp(c, 'nameC'),
    d: newObjWithNameProp(d, namePrefixForAD + a.id + b.id + c.id),
  }
}
``` 
## Temp Solution
**To avoid this unnecessary git changes, I opened the `requireReturnForObjectLiteral` option**
So 3rd type of above arrow functions must change a little bit:
```
const newObjWithNameProp = (obj, name) => {
  return { ...obj, name };
}
```
Obviously, it's a trivial. 

## Conclusion
To reduce unnecessary git diffs or avoid trivial declaration for simple returns-object arrow functions,  
we need one more option `allowReturnForObjectLiteral`. So the 4th type arrow function won't be recogonized as error in `as-needed` mode.

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. Can you clarify the difference between the 3rd and 4th type of arrow function? They both seem to be returning objects, and I'm not sure how you're drawing the distinction between them.

**Comment by Stupidism** [comment]
**The problem is it's causing unnecessary git changes like I expained above!**

It's hard to distinguish them clearly. In my concept:
3rd type returns an object(actually an object)
4th type returns a map(an object map of something)
e.g. prepare props for rendering in react, might change very often and could switch between 1st type and 4th type.

**Comment by not-an-aardvark** [comment]
I'm still not sure I understand the distinction. What do you mean by a "map" in this context? From looking at the code, how would I know that the 3th type is a "actually an object" and the 4th type is a "map" (which is still an object literal)?

**Comment by Stupidism** [comment]
They are the same for a linter.
So I wanted an `allowReturnForObjectLiteral` options for `as-needed` mode.
Because it either `require-no-block`(by default) or `require-block`(with `requireReturnObjectLiteral` set true) now. However, in practice, I need them both to be legal.

**Comment by Stupidism** [comment]
Maybe you can distinguish them by is the object literal in one line or not.
If the properties are put in one line, it means they are treated together.
If the properties are put in lines, it means they are individual fields. And to avoid unnecessary git diffs when the function switch between 1st type to 3rd(4th) type, we can require a block(return).

**Comment by not-an-aardvark** [comment]
I think I understand now, thanks for explaining. If I'm understanding correctly, would your desired option be the same as `as-needed`, but it would always ignore object literals?

**Comment by Stupidism** [comment]
Maybe options like { objectLiterals: { oneLine: (always, as-needed, never), multiLines: (always, as-needed, never) } }

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
