### ISSUE TITLE
Suggestions to improve "Getting Started" article.

### ISSUE THREAD

**Issue by tommai78101** [eslint/eslint#8420]
* **ESLint Version:** 3.17.1
* **Node Version:** 7.4.0
* **npm Version:** 4.0.5

I am also hoping to see a better explanation of the [**Getting Started** article](http://eslint.org/docs/user-guide/getting-started), including:

- Explicitly say each rule do not support multiple options.
- Explicitly say each rule has the potential to support unique severity beyond what we have.
- A list of all options that each rule has. Currently, the options are written in the docs, but they are hard to distinguish against other similarly formatted text or code.
- **Windows** users are being left out. Some of us, like me, are restricted to use Windows due to work. What is lacking is, for example, where the configuration files are at, and how to create a new `.eslintrc` manually without using `eslint --init` command (renaming a file as `.eslintrc.`, with 1 period at the beginning and end of the filename each).

I'm very certain there may be a duplicate issue, but the most important one is the point in boldfaced text.

**Comment by platinumazure** [comment]
This issue was created at my suggestion, but I forgot to mention that this should be on eslint.github.io. I will create a copy of this issue over there unless @tommai78101 beats me to it. Sorry for the inconvenience.

**Comment by platinumazure** [comment]
Closing this issue since I've (finally) created the issue on eslint.github.io. Please see eslint/eslint.github.io#447 for any further updates. Thanks!
