### ISSUE TITLE
Proposal: Update `sourceCode.getAllComments()` with a way to filter by comment type

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#8435]
Now that we are treating shebangs like comments, calls to `sourceCode.getAllComments()` now have to do things like [this](https://github.com/eslint/eslint/blob/867dd2eab85b1a72e3e3492a142c9b49ad810b81/lib/rules/no-inline-comments.js#L61) to filter out unwanted comments. I think it would be a lot nicer to have the method call do this for you.

In addition, if we could cover being able to get all comments of a certain type so that we don't have to do [this](https://github.com/eslint/eslint/blob/867dd2eab85b1a72e3e3492a142c9b49ad810b81/lib/rules/line-comment-position.js#L84), that might be nice too. 

I'd like to propose either adding an argument that will filter out the results for you or adding another method (`sourceCode.getAllCommentsOfType()`?) that would do this. I'm not entirely sure how this would work generically when two types of comments are desired but the third isn't.

Some possible ideas:
```js
sourceCode.getAllComments({ includeShebang: true }); // making another breaking change and having it be `false` by default
sourceCode.getAllComments({ excludeShebang: true });
sourceCode.getAllComments({ exclude: ["Shebang"] });
sourceCode.getAllComments({ include: ["Line", "Block"] });
sourceCode.getAllComments({ filter: t => t.type !== "Shebang" });

sourceCode.getAllComments("Line") or sourceCode.getAllComments(["Line", "Block"]);
sourceCode.getAllCommentsOfType("Line") or sourceCode.getAllCommentsOfType(["Line", "Block"]);
```
I think I currently like either of the last two options best, but am curious what everyone else thinks.

We can also cache these results if need be (potentially using the cache in https://github.com/eslint/eslint/pull/8434 if we decide to keep it).

**Comment by soda0289** [comment]
I like the idea of having a filter function option. It fits the pattern of the skip/count options of the getToken functions. Might want to include it in the getComments function as well, to keep the API consistent.

**Comment by not-an-aardvark** [comment]
I'm not sure I see the advantage of a filter function when `getAllComments({ filter: foo })` could be replaced with `getAllComments().filter(foo)`. Maybe something like `getAllLineComments` or `getAllBlockComments` would be better.

**Comment by kaicataldo** [comment]
@not-an-aardvark If we were to create individual methods for each type, how would a rule author get both line and block comments but not the shebang? I think we would have to have an `ignoreShebang` option for `getAllComments()` and potentially add a `getShebang()` method as well.

I'm personally leaning more and more toward updating getAllComments() to include an optional parameter (accepting either a string or an array of strings) that filters comments might be the easiest to reason about. When no parameters are supplied, it would keep the behavior it does now. 

```js
sourceCode.getAllComments();
sourceCode.getAllComments("Line");
sourceCode.getAllComments(["Line", "Block"]);
```

**Comment by kaicataldo** [comment]
Sorry, typing on my phone is hard 😬

**Comment by not-an-aardvark** [comment]
My thought process: It seems like the main purpose of this enhancement is to save users from having to type the same boilerplate `.filter` function over and over. If that's the case, then we should make sure the enhancement would actually provide a tangible benefit to users, other than "the boilerplate is now an argument" (the `filter` idea) or "the boilerplate is slightly shorter".

One way to do this would be to provide improved error detection. For example, suppose the user makes an error in their filter function:

```js
sourceCode.getAllComments().filter(comment => comment.type === "Blok") // oops, typo
```

Currently, this will result in an empty array, which could be confusing. If we introduced something like `getAllBlockComments()`, then typos would be much easier to detect, because they will result in an error:

```js
sourceCode.getAllBlokComments() // oops, typo
```

If we do implement a string/array option, I think we should make sure to validate the argument so that we provide an error-checking benefit to the user. On its own, I'm not sure allowing users to use marginally less code would be a worthwhile justification for increasing API complexity.

**Comment by soda0289** [comment]
@not-an-aardvark You make a good point about filter function increasing the potential for user error. We should validate the json/array object passed in if we choose that route.

Maybe something like this would be sufficient if we wanted to avoid passing in strings
```js
getAllComments({
  ignoreShebang: false,
  ignoreLine: false,
  ignoreBlock: false
});
```
Having three separate functions would work too.

**Comment by kaicataldo** [comment]
@soda0289 I think the double negative configuration is a bit confusing.

@not-an-aardvark Excellent points. Validation should be very easy since we're limited to three possible strings. Might just be a personal preference, but I think having fewer methods with a few more options is easier to reason about (consolidates the documentation and makes them more discoverable) than multiple methods, especially since an argument isn't required and will, by default, do the expected thing (I _think_). I also have spent a lot of time on this comment stuff, so I might be too close to the situation...

**Comment by not-an-aardvark** [comment]
Is this still something we want to add?

**Comment by kaicataldo** [comment]
I still would like it, but since it's more of a QOL change than anything and it doesn't seem like anyone feels very strongly I'm happy to close it too.

**Comment by platinumazure** [comment]
If we can come to agreement on a proposal, I would be happy to support this. Otherwise, though, I wonder if we should close.

**Comment by kaicataldo** [comment]
Though I still think it would be nice to have, I'm not opposed to closing this! I haven't seen any other complaints about the current way of doing things.
