### ISSUE TITLE
Proposal: exceptions of class-methods-use-this for abstract methods

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#8441]
## The version of ESLint you are using.

- 3.19.0

## The problem you want to solve.

I tried to define abstract methods with ES2015 classes.
JSDoc has [@abstract](http://usejsdoc.org/tags-abstract.html) tag for this purpose.
For example:

```js

/*eslint
    class-methods-use-this: error,
    require-jsdoc: error,
    valid-jsdoc: error
*/

/**
 * The test class.
 */
class Foo {
    /**
     * Test method.
     * @abstract
     * @param {string} name The name to show.
     * @returns {void}
     */
    hello(/* name */) {
        throw new Error("Not implemented.")
    }
}
```

In that case, the `class-methods-use-this` rule shows an error.

```
19:10 - Expected 'this' to be used by class method 'hello'. (class-methods-use-this)
```

However, this is unexpected to me. It's natural even if abstract methods don't use `this`.

## Your take on the correct solution to problem.

If the JSDoc comment of a method has the `@abstract` tag, the `class-methods-use-this` should ignore the method. It should be by default in my opinion.

**Comment by ilyavolodin** [comment]
I'm not sure it's a good idea to tie this rule to JSDoc. I understand that it's better then not to handle this case at all, but it still feels pretty magical to me.

**Comment by mysticatea** [comment]
Hmm, OK.
I'll add it into my plugin.
