### ISSUE TITLE
Not having es7/es8 env options = 'Promise' is not defined

### ISSUE THREAD

**Issue by MatthewHerbst** [eslint/eslint#8453]
Can we add an `es7` and `es8` env options please? Otherwise the below happens. Settings the env to `es6` when I'm using es8 feels wrong.

**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`

**Please show your full configuration:**

```js
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:import/recommended',
  ],

  env: {
    browser: true,
    node: true,
  },

  plugins: [
    'import',
  ],
  
  // It's not a parser issue - I get the same problem if I remove this line
  parser: 'babel-eslint',

  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
    ecmaVersion: 2017,
    sourceType: 'module',
  },

  rules: {
    'array-bracket-spacing': [1, 'never'],
    'block-scoped-var': 0,
    'brace-style': [2, '1tbs', { allowSingleLine: false }],
    'camelcase': [2, { properties: 'never' }],
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'complexity': [1, 10],
    'computed-property-spacing': [2, 'never'],
    'consistent-return': 0,
    'curly': 2,
    'dot-notation': 2,
    'eol-last': [2, 'unix'],
    'eqeqeq': 2,
    'func-call-spacing': 2,
    'guard-for-in': 2,
    'indent': [2, 2, { SwitchCase: 1 }],
    'jsx-quotes': [2, 'prefer-single'],
    'import/default': 0,
    'import/extensions': 2,
    'import/first': 2,
    'import/newline-after-import': 2,
    'import/no-absolute-path': 2,
    'import/no-deprecated': 1,
    'import/no-duplicates': 2,
    'import/no-dynamic-require': 2,
    'import/no-extraneous-dependencies': 2,
    'import/no-internal-modules': 2,
    'import/no-mutable-exports': 2,
    'import/no-named-as-default-member': 2,
    'import/no-named-as-default': 2,
    'import/no-named-default': 2,
    'import/no-namespace': 2,
    'import/no-unassigned-import': 2,
    'import/no-webpack-loader-syntax': 2,
    'import/order': [2, {
      groups: [
        'builtin',
        'external',
        'internal',
        ['index', 'sibling', 'parent'],
      ],
    }],
    'import/prefer-default-export': 2,
    'import/unambiguous': 0,
    'object-curly-spacing': [1, 'always'],
    'key-spacing': 0,
    'keyword-spacing': 2,
    'max-len': [2, { code: 100, ignoreComments: true, ignoreUrls: true }],
    'max-nested-callbacks': [2, 3],
    'max-params': [1, 4],
    'new-cap': [2, { newIsCap: true, capIsNew: false }],
    'new-parens': 2,
    'no-alert': 2,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-caller': 2,
    'no-catch-shadow': 0,
    'no-compare-neg-zero': 2,
    'no-duplicate-imports': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-floating-decimal': 2,
    'no-func-assign': 2,
    'no-implied-eval': 2,
    'no-iterator': 2,
    'no-label-var': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-lonely-if': 2,
    'no-loop-func': 0,
    'no-multi-spaces': 0,
    'no-multi-str': 2,
    'no-multiple-empty-lines': 2,
    'no-nested-ternary': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-object': 2,
    'no-new-wrappers': 2,
    'no-octal-escape': 2,
    'no-process-exit': 2,
    'no-proto': 2,
    'no-restricted-globals': [2, 'event'],
    'no-return-assign': 0,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-shadow': 2,
    'no-shadow-restricted-names': 2,
    'no-throw-literal': 2,
    'no-trailing-spaces': 2,
    'no-undef-init': 2,
    'no-underscore-dangle': 0,
    'no-unsafe-negation': 2,
    'no-unused-expressions': 2,
    'no-use-before-define': 2,
    'no-var': 2,
    'no-void': 2,
    'no-with': 2,
    'object-shorthand': [2, 'always'],
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'after'],
    'padded-blocks': [2, 'never'],
    'prefer-const': 2,
    'quotes': [2, 'single', 'avoid-escape'],
    'radix': 2,
    'semi': [2, 'always'],
    'semi-spacing': [2, { before: false, after: true }],
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': 2,
    'spaced-comment': [2, 'always'],
    'strict': [2, 'never'],
    'valid-jsdoc': [2, {
      prefer: { returns: 'return' },
      requireParamDescription: false,
      requireReturn: false,
    }],
    'wrap-iife': [2, 'outside'],
    'yoda': 2,
  },
};

```

**What did you do? Please include the actual source code causing the issue.**

```js
return new Promise((resolve) => {
  this.server = app.listen(port, () => {
    resolve();
  });
});
```

**What did you expect to happen?**
Expected the linter not to treat `Promise` as undefined since it is a Node builtin AND was included in ES6. 

**What actually happened? Please include the actual, raw output from ESLint.**
`error  'Promise' is not defined                               no-undef`

Setting

```js
env: {
  es6: true,
},
```

fixes the problem, but that feels wrong; I'm using ES2017 (es8), not ES2015 (es6)...

**Comment by platinumazure** [comment]
You've only set a parser option for ES6. Unfortunately that doesn't automatically tell ESLint what globals should now be available.

If you use the `es6` environment, in addition to node/browser, then the error should go away. The environments tell ESLint what globals should be available (among other things).

**Comment by MatthewHerbst** [comment]
@platinumazure yes, I realized that as I mentioned above. Maybe this needs to be retitled: "there should be `es7` and `es8` environments as well"?

**Comment by platinumazure** [comment]
No globals were added in ES7 or ES8, so we didn't feel the need to include separate environments for those.

If you think of the `es6` environment as meaning the ES6-introduced globals, combined with specifying an ecmaVersion of 2017 in your parserOptions, then everything should work the way you want it to.

That said, I can't find any previous discussion of this, so I'll leave this open and let other team members weigh in.

**Comment by not-an-aardvark** [comment]
Related: https://github.com/sindresorhus/globals/issues/111

**Comment by MatthewHerbst** [comment]
I feel like the `ecmaVersion` and the `env` are pretty closely tied ([as shown in the fact that setting `es6: true` also auto-sets `ecmaVersion: 6`](http://eslint.org/docs/user-guide/configuring)). Imho, if I set the `ecmaVersion`, I expect the env to at a minimum support that version.

**Comment by ljharb** [comment]
* ES2017 (nobody calls it ES8).

I would definitely expect there to be an env version for every edition, even if no new globals were added - it should just inherit from the previous edition.

**Comment by MatthewHerbst** [comment]
es5/es6 envs were talked about/added due to https://github.com/eslint/eslint/issues/4085

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by ljharb** [comment]
@not-an-aardvark this might be worth reopening; there should be an env for every edition precisely so users don't have to think about it.

**Comment by MatthewHerbst** [comment]
@ljharb Is there a source of truth for globals added in ES2017 and future ESXXXX? I can try and make a PR for this (guessing it would need two, one here and one in [`globals`](https://github.com/sindresorhus/globals/)).

Further, I kind of touched on it in the comments above, but it wasn't really addressed. @not-an-aardvark What is the relationship, if any, between `env.esX` and `parserOptions.ecmaVersion`? As I mentioned above, I think it would be reasonable for one to expect that setting `parserOptions.ecmaVersion` will also set `env.esX` to the matching version.

**Comment by not-an-aardvark** [comment]
> there should be an env for every edition precisely so users don't have to think about it.

Feel free to open a new issue for this if you'd like.

> Is there a source of truth for globals added in ES2017 and future ESXXXX? I can try and make a PR for this (guessing it would need two, one here and one in [`globals`](https://github.com/sindresorhus/globals/)).

The source of truth is generally the `globals` package. There were no globals introduced in ES2016, and two globals introduced in ES2017 (`Atomics` and `SharedArrayBuffer`). Those haven't been added to `globals` yet because they're not shipping in any browsers (see https://github.com/sindresorhus/globals/issues/111).

> What is the relationship, if any, between `env.esX` and `parserOptions.ecmaVersion`? As I mentioned above, I think it would be reasonable for one to expect that setting `parserOptions.ecmaVersion` will also set `env.esX` to the matching version.

`parserOptions.ecmaVersion` configures the parser to handle a given set of syntax features. `env.es6` configures rules like `no-undef` and `no-restricted-globals` to be aware of the globals introduced in ES6. Additionally, `env.es6` sets `parserOptions.ecmaVersion` to 6, if it hasn't been set to a different value elsewhere.

**Comment by ljharb** [comment]
@not-an-aardvark This *is* the issue for it - I can certainly open a new one if you insist, but that seems a bit silly.

**Comment by not-an-aardvark** [comment]
There are a couple reasons why I think creating a new issue would be better:

* The discussion in this issue covers several different topics: the original issue started out as a bug report, then [this comment](https://github.com/eslint/eslint/issues/8453#issuecomment-293726585) proposes basing available globals on the parser options, then [this comment](https://github.com/eslint/eslint/issues/8453#issuecomment-293727708) proposes adding new `env`s for every available `ecmaVersion`. For a team member coming across the issue for the first time, it's difficult to tell what's being discussed or voted on when skimming the issue. Having an issue with a clear proposal can make the discussion more focused and effective.
* Old issues tend to get viewed a lot less, and so they're more likely to be stalled indefinitely.

**Comment by ljharb** [comment]
Filed #9109.
