### ISSUE TITLE
"no-unexpected-multiline" --fix for this rule?

### ISSUE THREAD

**Issue by svipben** [eslint/eslint#8457]
Hello,

**What rule do you want to change?**
no-unexpected-multiline

**Does this change cause the rule to produce more or fewer warnings?**
I think no.

**How will the change be implemented? (New option, new default behavior, etc.)?**
`--fix` function to `"no-unexpected-multiline"`

**Please provide some example code that this change will affect:**
For e.g. if we are using this code:
```
var globalCounter = { }

(function () {
    var n = 0
    globalCounter.increment = function () {
        return ++n
    }
})()
```

It will be auto fixed to this:
```
var globalCounter = { }; // AS YOU CAN SEE ADDED `;` semi

(function () {
    var n = 0
    globalCounter.increment = function () {
        return ++n
    }
})()
```

**Comment by platinumazure** [comment]
Hi @svipben, thanks for the issue! Please edit your first post to use our [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) when you get a chance; this makes it easier for us to evaluate your proposal.

I'm not sure about adding autofix in this case. It's true that probably 95% of the time the correct fix is to add a semicolon, but there might well be times where the property access or function call is in fact desired, so the correct fix would be to move the opening token up to the previous line. So I'd be reluctant to add autofix to this rule.

Example of the other kind of fix:

```js
var something = foo
[0].doSomething();

// Maybe should be fixed to:
var something = foo[
0].doSomething();

// Or, better (but this is probably too large a fix):
var something = foo[0].doSomething();
```

**Comment by not-an-aardvark** [comment]
Based on the number of :+1:s on @platinumazure's comment, it looks like there's consensus that adding a fix for this rule would be problematic, so I'm closing this issue.
