### ISSUE TITLE
[Feature] Allow ignoring paths via package.json

### ISSUE THREAD

**Issue by deckar01** [eslint/eslint#8458]
I propose adding a second top level key to `package.json` named `eslintIgnore` that contains an array of paths to be ignored (or not).

 - #698 landed support for `eslintConfig` in `package.json` and it help keep the root of the project tidy.
 - #4261 proposed merging `.eslintignore` with `.eslintrc`, but it was rejected because "config files cascade, and ignore files do not".

**Comment by ilyavolodin** [comment]
We don't have any statistical data about usage of package.json for configuring ESLint, but my personal feeling from browsing various Github repositories is that very very few people use package.json to configure ESLint. I don't know if adding a feature specifically targeting those people makes sense.

**Comment by deckar01** [comment]
- [Searching for "eslint" in public JSON files](https://github.com/search?l=JSON&o=desc&q=eslint&s=indexed&type=Code) returns 408,836 results
 - [Searching for "eslintConfig" in public JSON files](https://github.com/search?l=JSON&o=desc&q=eslintConfig&s=indexed&type=Code) returns 39,246 results

This sample indicates ~10% of public projects store some amount of eslint configuration in package.json.

**Comment by platinumazure** [comment]
Thanks for the data, that really helps.

I think this could work as long as we follow the same caveats we currently do for `.eslintignore`:
1. Cascading ignore patterns will not be supported; and
1. The ignore patterns must be in the ESLint process's CWD.

Personally, I would assume it to be quite common to run ESLint from package root, so I don't think those restrictions would be too onerous.

That said, this ultimately will have to be evaluated by our Technical Steering Committee.

**Comment by kaicataldo** [comment]
As discussed in today's TSC meeting, this issue is now accepted.

**Comment by danielo515** [comment]
How can I make use of this? There is no documentation about it

**Comment by deckar01** [comment]
@danielo515 It doesn't look like it has been included in a release yet.

https://github.com/eslint/eslint/releases

If you are using master, the docs are in the repo:

https://github.com/eslint/eslint/blob/master/docs/user-guide/configuring.md#using-eslintignore-in-packagejson

**Comment by danielo515** [comment]
Ok, that makes sense. 

I'll wait the next release then. Thanks for the answer

**Comment by HarrisonMc555** [comment]
I just spent a while spinning my wheels because I saw this functionality advertised in the user guide [documentation](http://eslint.org/docs/user-guide/configuring#using-eslintignore-in-packagejson) but didn't realize that it was only a feature of eslint 4.0 (and that I had version 3.19).

Is there a possibility of labeling some of these as "new in 4.0" or something?

Also maybe a note somewhere mentioning how to upgrade to a newer version of eslint? I'm sure to experienced JavaScript developers familiar with npm it's a no-brainer, but I spent a while looking all over the website before finally trying `nmp install eslint@4.0`, which was just an educated guess. It's not mentioned anywhere on any of the "upgrading" pages (at least that I found).

**Comment by kaicataldo** [comment]
@HarrisonMc555 I agree, that would be a helpful thing in the docs. We'd probably have to go through and backfill a bunch of features then.

Regarding this:
> Also maybe a note somewhere mentioning how to upgrade to a newer version of eslint?

Does [this](http://eslint.org/docs/user-guide/migrating-to-4.0.0) satisfy what you're asking about? We have it in the blog posts section, but maybe it could be more visible.

**Comment by HarrisonMc555** [comment]
@kaicataldo yes, it might be a big project. Maybe it's not worth it, but it did take me a while to figure out, and I'm fairly comfortable with the command line (although still relatively new to node and eslint).

> Does this satisfy what you're asking about? We have it in the blog posts section, but maybe it could be more visible.

That was what I looked at (several times), but nowhere does it explain *how* to upgrade, it just guides you through how to fix what breaks *when* you upgrade.

**Comment by kaicataldo** [comment]
@HarrisonMc555 Ah, I see what you're saying. There's definitely assumed knowledge regarding how to upgrade a package using npm, but that isn't specific to ESLint. 

Maybe in the future we could include an install command and a link to npm's docs? That being said, I think it'll be difficult to always anticipate when that's useful and when it's extra noise - I think at some point it's reasonable to assume knowledge about (or the ability to discover) how the package manager works.

**Comment by deckar01** [comment]
I have never seen explicit instructions for updating an npm package in a package's documentation. NPM isn't very user friendly in this area though. You have to tell npm to install the latest version and save it as a dependency (very similar to installing a package for the first time).

```
npm install elint@4 --save
```

https://stackoverflow.com/a/23391365/1440667

**Comment by kaicataldo** [comment]
Agreed - I remember being confused about how to update packages when I first started using npm

**Comment by ljharb** [comment]
Generally updating any software is always the same, unless otherwise stated: rerun the install command, but for a newer version. That's true for `npm`.
