### ISSUE TITLE
`arrow-spacing` defaults are not working as expected.

### ISSUE THREAD

**Issue by mattcollier** [eslint/eslint#8472]
* **ESLint Version:**
v3.19.0
* **Node Version:**]
v7.2.1
* **npm Version:**
3.10.10
**What parser (default, Babel-ESLint, etc.) are you using?**
none
**Please show your full configuration:**

```
{
  "env": {
    "es6": true,
    "node": true
  },
  "rules": {
    # "arrow-spacing": ["error", {"before": true, "after": true}],
    "comma-dangle": ["error", "never"],
    "eol-last": "error",
    "key-spacing": ["error", {"beforeColon": false, "afterColon": true}],
    "keyword-spacing": ["error", {"overrides": {
      "catch": {"after": false},
      "do": {"after": false},
      "for": {"after": false},
      "if": {"after": false},
      "switch": {"after": false},
      "while": {"after": false}
      }}],
    "indent": ["error", 2, {
      "SwitchCase": 1,
      "FunctionExpression": {
        "parameters": 1
      },
      "CallExpression": {"arguments": 1}
    }],
    "linebreak-style": ["error", "unix"],
    "max-len": ["error", 80],
    "no-extra-semi": "error",
    "no-irregular-whitespace": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": ["error", {"max": 1}],
    "no-spaced-func": "error",
    "no-trailing-spaces": "error",
    "no-undef": "error",
    "no-unused-vars": "error",
    "object-curly-spacing": ["error", "never"],
    "semi": ["error", "always"],
    "semi-spacing": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", "never"],
    "space-infix-ops": "error",
    "space-in-parens": ["error", "never"],
    "spaced-comment": ["error", "always", {"block": {"markers": ["!"]}}]
  }
}

```

**What did you do? Please include the actual source code causing the issue.**

Issue can be demonstrated by using my .eslintrc file or not.

Run
```
eslint example.js --no-eslintrc --env es6
```
on the following js code:

```js
const async = require('async');
async.auto({
  start: callback =>{ // no space after arrow
    console.log('eslint is awesome!');
    callback();
  }
});
```

**What did you expect to happen?**
According to the documentation for `arrow-spacing`, `{"before": true, "after": true}` is the default configuration.  http://eslint.org/docs/rules/arrow-spacing

However, I find that no error is raised unless I add the rule explicitly in my .eslintrc file.

**What actually happened? Please include the actual, raw output from ESLint.**
Default configuration does not raise an `arrow-spacing` error.

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is actually intended behavior -- ESLint is designed such that all rules are off by default, and the user needs to specify rules in a config file to enable them.

The "default configuration" mentioned in the `arrow-spacing` docs refers to the configuration if the rule is enabled but none of its configuration options are explicitly used. In other words, `arrow-spacing: "error"` does the same thing as `arrow-spacing: ["error", {"before": true, "after": true}]`.

**Comment by mattcollier** [comment]
OK, great!  That works, thank you!
