### ISSUE TITLE
False Positive Regex Escape 

### ISSUE THREAD

**Issue by patrickml** [eslint/eslint#8474]
When trying to use regex to parse out any `[]` from a string eslint is throwing a false positive for un-needed escape

![image](https://cloud.githubusercontent.com/assets/7581369/25147618/1ff27c6e-2446-11e7-9795-b6aeec5494af.png)

`replace(/[\[\]]/gi, '.')` != `replace(/[[]]/gi, '.')`

**Comment by not-an-aardvark** [comment]
Thanks for the report. It looks like the error message is only referring to escaping `[`. (The `]` character still needs to be escaped.) This would result in a regex like `replace(/[[\]]/gi, '.')`, which behaves the same as the original regex in your code.

**Comment by patrickml** [comment]
ah thank you @not-an-aardvark, that's my bad sorry for the false report
