### ISSUE TITLE
object-curly-newline --fix  erroneously removes comment

### ISSUE THREAD

**Issue by freshp86** [eslint/eslint#8484]
ESLint Version: v3.19.0
Node Version: v7.9.0

```js
module.exports = {
  'env': {
    'browser': true,
    'es6': true
  },
  'extends': 'eslint:recommended',
  'rules': {
    'object-curly-newline': ['error', {multiline: true}],
    'no-unused-vars': 'off',
  }
```

**Before**
```js
var a = {
  // Nothing here yet, but comment should not be removed.
};
```

**After invoking ESLint with the --fix flag the file is modified as follows**
```js
var a = {};
```

**What did you expect to happen?**
The comment should have been preserved.

**What actually happened?**
The comment was removed.

**Comment by platinumazure** [comment]
Thanks for reporting this! We definitely don't want to remove comments via autofix.

**Comment by freshp86** [comment]
Thanks for triaging quickly. Just adding a few more cases that exhibit the same problem

**Before**
```js
let a = { 
  /* comment */ foo: 'hello'
};

let b = { 
  foo: 'hello' /* comment */
};
```
**After --fix both comments are removed**
```js
let a = {foo: 'hello'};

let b = {foo: 'hello'};
```

**Comment by freshp86** [comment]
FYI, I have a condidate fix at https://github.com/freshp86/eslint/commit/496568626008a44652d5e41aebc9295d64f92f97. Tested

```js
let a = {
  /* comment */ foo: 'hello'
};

let b = {
  foo: 'hello' /* comment */
};

let c = { /* comment */
  foo: 'hello'
};
```
and it becomes

```js
let a = {/* comment */ foo: 'hello'};

let b = {foo: 'hello' /* comment */};

let c = { /* comment */
  foo: 'hello'
};
```
which seems correct. If that seems promising I can look on how to add proper tests and send a PR (have not contributed to ESLint before).

Having said that, when I use my complete config object (not posted in this bug), I end up with the comments removed. I'll keep investigating that separately, since that seems to be caused by some other rule.

**Comment by VictorHom** [comment]
I can take a look at this if no one is tackling this one
