### ISSUE TITLE
Add tests for release process

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8489]
There were some issues with the release process today, which could have been caught if we had tests for the release build. We have a lot of untested code in `Makefile.js`, so it would be a good idea to add tests for it.

**Comment by VictorHom** [comment]
@not-an-aardvark I would like to take a look at this. To get a better sense, are the issues documented/noted?

I could definitely add individual unit tests to start off.

**Comment by not-an-aardvark** [comment]
Here are a few of the issues that have occurred:

* https://github.com/eslint/eslint/issues/8766#issuecomment-310806438: An issue with the API caused the release to crash. The issue was that using `baseConfig` with `extends` in `CLIEngine` would result in an error.
* https://github.com/eslint/eslint/issues/8627#issuecomment-305920304: The release failed with an error `/bin/sh: linefix: command not found`. I think this might be because the release script [assumes `linefix` is installed globally](https://github.com/eslint/eslint-release/blob/075bf3684685d1ecfd8d6b4120dc3bcb368259cd/lib/release-ops.js#L400), although it's only a local dependency of [eslint-release](https://github.com/eslint/eslint-release/blob/075bf3684685d1ecfd8d6b4120dc3bcb368259cd/package.json#L53). (Actually, I think it would be nice to just turn on the `linebreak-style` rule on the codebase and get rid of `linefix`, but that's a separate issue.)
* https://github.com/eslint/eslint/issues/8404#issuecomment-296316457: The changelog, which is usually autogenerated from the commits since the previous release, ended up being empty. More details can be found in https://github.com/eslint/eslint-release/issues/15. (tl;dr: we were using a newer version of git than we had used in past releases).
* https://github.com/eslint/eslint/issues/8237: A bug in the website generation resulted in the [demo](http://eslint.org/demo) to use an older version of ESLint.
* There were some infrastructure-related problems in https://github.com/eslint/eslint/issues/7956#issuecomment-274187893, although that's probably beyond the scope this issue.
* https://github.com/eslint/eslint/pull/7754: We autogenerate blogposts, and automatically replace the names of rules in commit messages with a link to the rule's documentation. A bug in the replacement caused some unexpected links to appear.
* https://github.com/eslint/eslint.github.io/issues/288: The part of the build that strips `.md` extensions from links had an error, leading to some broken links on the website.
* https://github.com/eslint/eslint/issues/7419: An issue with the fix for https://github.com/eslint/eslint.github.io/issues/288 caused some more broken links on the website.

I think there are two main problems here:

* There is a lot of untested logic in `Makefile.js` and the `eslint/eslint-release` repo.
* The release script completes all tasks sequentially. In other words, it roughly works in the following order:

    1. Update the package as necessary for publishing a release to GitHub
    1. Publish a release to GitHub
    1. Update the package as necessary for publishing a release to npm
    1. Publish a release to npm
    1. Generate the website
    1. Push the updated website to GitHub

    In the event that an error occurs in step 3 or 5, it's not possible to fix the issue and restart the release, because it has already been published somewhere. Instead, the remaining steps have to be carried out manually, which is tedious. It would be nice if steps 2, 4, and 6 came last, so that a crash in the build steps would just abort the build with no side-effects.

**Comment by VictorHom** [comment]
I've been busy the last few weeks, but this is still on my radar 👍

**Comment by VictorHom** [comment]
Should have a pull request end of week for review 🙏

**Comment by not-an-aardvark** [comment]
I've addressed the second problem from https://github.com/eslint/eslint/issues/8489#issuecomment-318940154 in https://github.com/eslint/eslint-release/pull/27 as part of preparing the release scripts to support 2FA. I don't have plans to add other tests in the near future. How about we close this issue when https://github.com/eslint/eslint-release/pull/27 is merged?

**Comment by kaicataldo** [comment]
I think this is still worth going after, but agree that perhaps we should break down the work into smaller issues. I think the most difficult part will be getting a test file started and getting the first few tests written.

**Comment by nzakas** [comment]
Looks like https://github.com/eslint/eslint-release/pull/27 has been merged. Shall we close this?

**Comment by not-an-aardvark** [comment]
Sounds good, closing.
