### ISSUE TITLE
Suggestion: need label for timed-out issues

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#8490]
IMHO it would be useful to have separate cemetery for timed out issues. Sometime issues become accepted and all agrees those are useful. But if not implemented for a long time, those are closed. I can understand such practice, but it would be useful to track back such issues somehow. Now useful ideas just become lost.

I think, new label will solve this problem.

Examples:

- https://github.com/eslint/eslint/issues/1098#issuecomment-235517870
- https://github.com/eslint/eslint/issues/5073#issue-128750228

**Comment by kaicataldo** [comment]
Thanks for the suggestion. We try to keep our backlog of issues groomed so that it's easier both for us as maintainers to prioritize bugs and enhancements and for contributors to find issues to work on.

Issues that don't have activity for a while are closed for lack of sufficient interest, as the chances of them being completed are pretty slim without someone actively moving the proposal forward. Eventually, it gets lost in the backlog.

Generally, if there's a lot of interest in something, a new issue will be made and we can re-evaluate then.

**Comment by ilyavolodin** [comment]
@kaicataldo if I'm understanding it correctly, @puzrin is not complaining about us closing inactive issues, he is just suggesting that any accepted issue that was closed due to inactivity will be marked with some extra label prior to closing, to make it easier to find in the future.

**Comment by puzrin** [comment]
> Generally, if there's a lot of interest in something, a new issue will be made and we can re-evaluate then.

1. That depends. I consider impolite & abusive to create issue again, after closed by repo owner. This issue is сreated because i see that "generally" does not work well in some cases.
2. Also see upvotes and comments after https://github.com/eslint/eslint/issues/1098#issuecomment-235517870.

> Issues that don't have activity for a while are closed for lack of sufficient interest, as the chances of them being completed are pretty slim without someone actively moving the proposal forward.

See second example, i said in clear form, that i can spend resources and implement it. What kind of "actively moving the proposal forward" do you expect in this case? I've asked only minimal info - will it be accepted. Again - i feel impolite to insist in foreign repo.

**Comment by puzrin** [comment]
@ilyavolodin you are right. I understand desire to keep tracker clear from garbage. But IMHO existing process of close is too illegible. I try to suggest constructive solution.

**Comment by kaicataldo** [comment]
Oh I see, sorry for misunderstanding. I'm not opposed to that!

**Comment by not-an-aardvark** [comment]
> I'm not opposed to that! Though not sure how much value it adds either.

This is also my position.

**Comment by puzrin** [comment]
I'd say, it's not very pleasant to get issue closed with unclear future. If issue is rejected as useless - that's ok. If there are no human resources, and user should participate - that's ok too. Polite but unclear answer - not ok, IMHO.

It's not a problem to close issue. Problem is that sometime feedback from team is completely unclear. I did not analyzed all cases, but i'm 100% sure in examples from first post. Those are closed and it's not clear what to do from my side.

**Comment by puzrin** [comment]
Another solution could be to say officially - "it's normal to create new issue after old one was timed out if team's answer is not clear".

**Comment by platinumazure** [comment]
I like the idea of creating a "no consensus" label (meaning team never really reached a decision, we just closed to keep the backlog clean/relevant). We could also add a policy saying that we encourage new issues if a closed issue merits further discussion, and call out that "no consensus" issues are especially welcomed to be opened as new issues if needed.

A bit of clarity on how we would interpret new issues from closed issues would be nice. For some teams, it's unwelcome spam. For others, it might mean new indication of interest in the issue (or stronger interest if it's the same person reopening the issue). Maybe ESLint is closer to the latter.

All that said, I still think we should also consider adding a note that repeatedly creating issues for the same thing, without adding new discussion, will be construed as spam. But that's just my personal opinion.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
