### ISSUE TITLE
Auto fix `no-unneeded-ternary` changes code behavior

### ISSUE THREAD

**Issue by feross** [eslint/eslint#8507]
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 7.9.0
* **npm Version:** 4.5.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
    "no-unneeded-ternary": ["error", { "defaultAssignment": false }],
```

**What did you do? Please include the actual source code causing the issue.**

The following code (line 3) is considered an error by the `no-unneeded-ternary` rule.

```js
var value = 'a'
var canSet = true
var result = value ? value : canSet ? 'unset' : 'can not set'
// NOTE: `result` is 'a'
```

When `--fix` is used, it is corrected to code that has different behavior. See:

```js
var value = 'a'
var canSet = true
var result = value || canSet ? 'unset' : 'can not set'
// NOTE: `result` is 'unset'
```

**What did you expect to happen?**

Parens should probably be added in this situation. This code would have maintained the same behavior:

```js
var result = value || (canSet ? 'unset' : 'can not set')
```

Related issue: https://github.com/feross/standard/issues/866

**Comment by not-an-aardvark** [comment]
Thanks for reporting, I can reproduce this bug.
