### ISSUE TITLE
[Feature Request] Ability to opt out a style in bracket style

### ISSUE THREAD

**Issue by bigopon** [eslint/eslint#8508]
* **Eslint version**: latest
* **Problem**: I can choose only one among `1tbs`, `stroustrup`  and `allman` but I want to disallow only `allman`.
* Current argument against having more than 1 `if else` bracket styles is to have consistency, but i dont think there much distinction between `1tbs` and `stroustrup`. Enabling this can be helpful, ex `1tbs` can be used where the code inside `if/else` is short and doesn't need additional explanation and where the code is complex with extra comment required, it's more suitable for `stroustrup`.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
