### ISSUE TITLE
Parse Error: Illegal import declaration. React Native project

### ISSUE THREAD

**Issue by gHashTag** [eslint/eslint#8509]
**Tell us about your environment**
![2017-04-26 15 52 12](https://cloud.githubusercontent.com/assets/6774813/25435619/3ea48036-2a99-11e7-969b-e00ba8cd40e9.png)
* **ESLint Version:**
v3.19.0
* **Node Version:**
v7.9.0
* **npm Version:**
4.2.0
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

```
    "extends"       : "airbnb",
    "parser"        : "babel-eslint",
    "parserOptions" : {
        "ecmaVersion"  : 6,
        "sourceType"   : "module",
    },
    "ecmaFeatures" : {
        "jsx": true,
        "modules": true, 
    },
    "env": {
        "browser" : true,
        "node"    : true,
        "jquery"  : true,
    },
    "settings":{
            "react":{
            "pragma":"React",
            "version":"15.1.0"
            },
        "ecmascript":6,
        "jsx":true
    },
    "plugins": [
        "react",
        "react-native"
    ],
    "rules": {
        "strict": 0,
        "quotes": 0,
        "no-unused-vars": 1,
        "camelcase": 1,
        "no-underscore-dangle": 1,
        "comma-dangle":[1,"never"],
        "indent":["error",4],
        "react/jsx-indent":0,
        "react/jsx-equals-spacing": [2, "always"],
        "no-console":0,
        "max-len":1,
        "no-param-reassign":1,
        "key-spacing": [
              2,
        {
                "align": "colon",
                "beforeColon": true,
                "afterColon": true
        }
        ],
        "no-multi-spaces": [
              2,
        {
                "exceptions":{
                    "VariableDeclarator":true,
                    "ImportDeclaration":true,
                    "JSXAttribute":true,
                    "AssignmentExpression":true
                }
        }
        ]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
import React, { Component } from 'react'
```

**What did you expect to happen?**
I want to make no mistake

**Comment by evilebottnawi** [comment]
@gHashTag incorrect `ecmaFeatures` usage, try to use
```shell
"parserOptions" : {
        "ecmaVersion"  : 6,
        "sourceType"   : "module",
        "ecmaFeatures" : {
                "jsx": true,
                "modules": true, 
        }
    }
```

**Comment by gHashTag** [comment]
@evilebottnawi Tried it first and rechecked now, but still the error was omitted

**Comment by gHashTag** [comment]
And tried `rm -rf node_modules && npm install` it`s don`t working

**Comment by platinumazure** [comment]
Ping @kaicataldo @hzoo, can either of you help with this? I'm not familiar with babel-eslint's configuration.

**Comment by kaicataldo** [comment]
`"ecmaVersion"` and `"ecmaFeatures"` aren't required - Babylon supports latest syntax and JSX out of the box. That being said, I don't think that should make it error either.

Here are the configuration docs for [babel-eslint](https://github.com/babel/babel-eslint#configuration).

**Comment by platinumazure** [comment]
@gHashTag Might be worth running `./node_modules/bin/eslint.js --print-config path/to/file.js` so that you can see if a different configuration file is interfering.

**Comment by gHashTag** [comment]
https://medium.com/usevim/in-editor-linting-with-syntastic-6814122bdbec
