### ISSUE TITLE
Scheduled release for May 5, 2017

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8518]
The scheduled release on Friday, April 21, 2017 is assigned to:

* @ilyavolodin
* @not-an-aardvark

**Note**: This release will be a 4.x alpha or beta release.

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by platinumazure** [comment]
Friendly reminders to @eslint/eslint-tsc about the process for documenting release responsibilities:

* If you volunteer to run the release, then besides listing your name to the initial post, please also assign the issue to yourself so we can see it on the issue list
* Please remove "tsc agenda" when two TSC members are assigned to the release (assuming there are no outstanding questions about the release itself)

If we want to change our release process/guidelines, I think that is probably best done as a TSC agenda item as well. (On the other hand, if I'm just misunderstanding the guidelines, please accept my apologies and let me know where I've gone wrong.) Thanks!

**Comment by platinumazure** [comment]
**TSC Summary**: Need to schedule two people for this release, per usual procedure. Also, it is not yet obvious if we should do another alpha release or if we can do a beta release.

**TSC Question**: Should this release be regarded as an alpha or beta release? Who wants to sign up for this release?

Please feel free to remove "tsc agenda" as soon as all questions above are answered, thanks!

**Comment by not-an-aardvark** [comment]
Whoever does this release should make sure to do a release of `eslint-release` first because https://github.com/eslint/eslint-release/issues/15 has been fixed on master.

**Comment by platinumazure** [comment]
@not-an-aardvark Any reason eslint-release has to be released on release day? Wondering if it would be simpler to do eslint-release earlier.

**Comment by platinumazure** [comment]
@eslint/eslint-tsc Still need one more volunteer for the release tomorrow! (Thanks ilyavolodin for volunteering already!)

**Comment by not-an-aardvark** [comment]
I can do this release.

> @not-an-aardvark Any reason eslint-release has to be released on release day? Wondering if it would be simpler to do eslint-release earlier.

I don't feel strongly about it either way, but it seems like it would be nice to have two people around whenever we do a release to make sure we're ready to handle any unexpected issues that could occur.

**Comment by not-an-aardvark** [comment]
ESLint 4.0.0-alpha.2 has been released, concluding this release process.
