### ISSUE TITLE
ESLint searches for config files in parent directories even when `root: true` is specified in a child config

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8561]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.10.0
* **npm Version:** 4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**What did you do? Please include the actual source code causing the issue.**

1. Clone the eslint repo
1. Insert `console.log(directory)` before [this line](https://github.com/eslint/eslint/blob/c70b0eda8794e552bcbfccbc0d5f46dfb4ea7783/lib/file-finder.js#L28)
1. Run `bin/eslint.js Makefile.js`

**What did you expect to happen?**

I expected only the `eslint/` directory to get scanned, because the `.eslintrc.yml` file in the repository root has `root: true` in it.

**What actually happened? Please include the actual, raw output from ESLint.**

All directories were scanned up to the filesystem root.

I think this is strictly a performance issue; even if a config file does appear in a parent directory, it's ignored when ESLint finds `root: true` in the parent config file. However, this could have significant performance impact if a parent directory contains a very large number of files. In theory it might also cause incorrect errors if the user does not have read permissions on the parent directory, but I haven't tested this.

**Comment by kaicataldo** [comment]
Added a "help wanted" label in case someone from the community wants to get to this before us :)

**Comment by VictorHom** [comment]
@kaicataldo Hi, could I help with this issue? I'm new to helping out on open source, but I've read through some of the files in eslint/lib, particularly around config.js and file-finder.js. 

I can recreate the issue and I was wondering what would be a good approach to resolving this issue. I see that the file scanning happens before the configurations are created. Would the general solution around this issue be to read the current directory, check for the eslint specific files, create their configuration, check for root: true, and then move up the directory if needed (whereas I believe right now, all the files are read first before the configurations are created). 

If this isn't right, I'm opened to feedback on how to better tackle this issue. Any advice is welcome.

Also if this isn't the right problem for me to tackle, let me know if there are other issues that would be more fitting.

Thanks!

**Comment by kaicataldo** [comment]
Hi @VictorHom - we'd love it if you'd like to make a contribution!

I've been off the grid and am just getting caught up on things, but conceptually the strategy you outlined makes sense to me. Opening WIP PR as you've done is probably the best way to get feedback :) Thanks for working on this, and please feel free to stop by https://gitter.im/eslint/eslint if you want to chat about anything.
