### ISSUE TITLE
Array/object comma near braces/brackets/parenthesis

### ISSUE THREAD

**Issue by borela** [eslint/eslint#8562]
I looked in the manual and even in the issues but I wasn't able to find the answer.
My current configuration [requires a space after commas](http://eslint.org/docs/rules/comma-spacing#rule-details) but I would like to add an exception and remove the space when the comma is followed by a `{`, `[` or `(`, so that this code:

```js
let a = [{
// ...
}, {
//^ Remove this space.
}]

let b = [[
// ...
], [
//^ Remove this space.
]]
```

Becomes this:

```js
let a = [{
  // ...
},{
  //...
}]

let b = [[
  // ...
],[
  //...
]]
```
Is there any setting/plugin that would allow that? Thank you

**Comment by not-an-aardvark** [comment]
Hi,

No, there is not a setting to allow that. However, you can always disable the `comma-spacing` rule and create a custom rule that enforces your desired spacing.
