### ISSUE TITLE
Object-shorthand breaks when a dynamic key has a dot

### ISSUE THREAD

**Issue by natecavanaugh** [eslint/eslint#8576]
FYI, this is a dupe of #8351, but just including more information:

**Tell us about your environment**
* **ESLint Version:**
3.19.0
* **Node Version:**
7.9.0
* **npm Version:**
4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

```
'object-shorthand': [2, 'always', {'ignoreConstructors': true}],
```

**What did you do? Please include the actual source code causing the issue.**

~~const keys = {~~
~~first: 'first',~~
~~second: 'second',~~
~~};~~

~~const o = {~~
~~[keys.first]: true,~~
~~[keys.last]: true,~~
~~};~~

```js
const actionHandlers = {
	[actionTypes.UPDATE_COLLAPSED_ENTRIES]: state => true
};
```

**What did you expect to happen?**
For it not to error out.

**What actually happened? Please include the actual, raw output from ESLint.**
It through an error:
```
TypeError: Cannot read property 'charAt' of undefined
    at isConstructor (/Users/ncavanaugh/Dev/git/check-source-formatting/node_modules/eslint/lib/rules/object-shorthand.js:120:35)
    at EventEmitter.Property:exit (/Users/ncavanaugh/Dev/git/check-source-formatting/node_modules/eslint/lib/rules/object-shorthand.js:395:48)
...
```

It comes down to keys that have a property don't have a name string attached, and so when it tries to run `charAt` on it, it throws an error.

Let me know if you need more info than the above.

Thanks!

**Comment by not-an-aardvark** [comment]
Thanks for the report. However, I can't seem to reproduce this issue -- ESLint is running successfully on that code without an error.

What version of `babel-eslint` are you using? Does the error also occur if you remove `babel-eslint`?

**Comment by natecavanaugh** [comment]
@not-an-aardvark Thanks for the response.
I'm using babel-eslint v6.1.2, but I also just realized, I never tested the above code directly, so but it's happening without babel-eslint, but only with arrow functions as the property value.

Ala:

```
const actionHandlers = {
	[actionTypes.UPDATE_COLLAPSED_ENTRIES]: state => true
};
```

Let me know if there's any other info you need.

Thanks @not-an-aardvark

**Comment by not-an-aardvark** [comment]
Thanks, I can reproduce the issue.
