### ISSUE TITLE
Scheduled release for May 19, 2017

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#8580]
The scheduled release on Friday, May 19, 2017 is assigned to:

* @not-an-aardvark
* @gyandeeps 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by not-an-aardvark** [comment]
ESLint 4.0.0-beta.0 has been released. This concludes the release process for this week.
