### ISSUE TITLE
no-param-reassign - Array.prototype.reduce and alike exceptions

### ISSUE THREAD

**Issue by langpavel** [eslint/eslint#8581]
Hi and thanks everybody who participated on `no-param-reassign`!
*I know, this is a duplicate of #8007 and #6339*. This is a lobby.

# Summary
**`no-param-reassign`** is pretty useful rule. I'm not breaking this rule all time *except* if I write code using this perfect function:
[`Array.prototype.reduce`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)`(`**`function`**`(accumulator, currentValue) => accumulator, initialAccumulator )`

Currently there is no way to hint `no-param-reassign` rule to relax `reduce` function accumulator in perfectly finest way.

# tl;dr
I really :heart: `no-param-reassign` rule. **But there is *at least one edge case* where assigning to passed variable is perfectly fine**, possibly the best way to write it down — `someArray.reduce()` function.
I'm sure that everyone knows this function, using it time to time for transforming data from one shape to another.

I see misunderstanding of `reduce` with `no-param-reassign` rule leading to wasting a lot of resources. It is so simple. Just use spread operator for copying result of previous iteration:
```js
// this code is perfectly fine, but violates rule:
const firstNameCount = users.reduce((firstNameCount, user) => {
  firstNameCount[user.firstName] = (firstNameCount[user.firstName] || 0) + 1;
  return firstNameCount;
}, {});

// this code is performing poorly, wasting memory and CPU, but fits rule :-(
const firstNameCount = users.reduce((acc, user) => {
  const result = { ...acc };
  result[user.firstName] = (acc[user.firstName] || 0) + 1;
  return result;
}, {});

```

This use case is so special and simple that there is no need for more similar functions. **This is the pattern** in fact. A coding ***primitive***,
so special that famous framework **Redux** is mostly about thinking about this one function, deriving all the possibilities from using this pattern!

### *If you need more…*

This is so special case that it can have it's own syntax, but, you know, this is not needed in javascript. But I can imagine language **expression** construct like this:

**reduce** *&lt;Iterable>* **into** *&lt;lvalue>* [ **=** *&lt;rvalue>* ] **with** *&lt;identifier>* [, *&lt;identifier>*] **as** *&lt;statement using &lt;lvalue> >*

**To be more concrete:**
```js
const firstNameCount = users.reduce((firstNameCount, user) => {
  firstNameCount[user.firstName] = (firstNameCount[user.firstName] || 0) + 1;
  return firstNameCount;
}, {});
```
can be written like this:
```js
const firstNameCount =  reduce users into firstNameCount = {} with user as {
  firstNameCount[user.firstName] = (firstNameCount[user.firstName] || 0) + 1;
}
```

**const** firstNameCount =  **reduce** users **into** firstNameCount = {} **with** user *[, index]* **as** {
&nbsp;&nbsp;firstNameCount[user.firstName] = (firstNameCount[user.firstName] || 0) + 1;
}

*PS: This is only illustrative example of language construct! I cannot imagine language except Pascal which want introduce this…* :smile:

# Is `Array.prototype.reduce` only exception?

I thing no. But I percept it as language primitive so it should be *only default* exception.

**Comment by langpavel** [comment]
I can offer $150 to single one who prepare PR which will be merged. Without taxes.

**Comment by ilyavolodin** [comment]
This would also apply to `reduceRight`, however the problem with creating such enhancement is that we don't know if you are calling `reduce` on the array, or on your custom made object. We don't track variable types in ESLint, so we don't really have a good way to figure out if the current `reduce` function should be excluded or not.

**Comment by langpavel** [comment]
> We don't track variable types in ESLint...

Yes, but it is possible to temporary disable rule by name of calling method? I know this is definitely not bulletproof but can be acceptable exception..
For example I define `reduce` and `reduceRight` as methods which flags function in argument to exception. I think this should be possible.

**Comment by ilyavolodin** [comment]
That's pretty error-prone way of doing it:
```js
var a = {
  reduce: function() { console.log('I'm not the reduce you are looking for');
}
```

**Comment by platinumazure** [comment]
@ilyavolodin It's the same way we've implemented the rule, though, is it not?

**Comment by ljharb** [comment]
Regarding the claim in the OP "// this code is perfectly fine, but violates rule:" - the whole point is that it's *not* fine, it mutates the accumulator. Certainly that entire reduce operation is pure even though the reducer is not, but there's no way for eslint to know for certain that a) it's `Array.prototype.reduce`, and b) you've passed a new value in as the initial accumulator.

Lacking that certainty, the proper solution is to enforce no mutation of arguments, or, for you the developer (who does have that certainty) to use an override comment.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by daaain** [comment]
For anyone who is just looking for the quick solution, this is how you disable the warning:

```
const firstNameCount = users.reduce((firstNameCount, user) => {
  firstNameCount[user.firstName] = (firstNameCount[user.firstName] || 0) + 1; // eslint-disable-line no-param-reassign
  return firstNameCount;
}, {});
```
