### ISSUE TITLE
eqeqeq documentation misleading on eslint.org

### ISSUE THREAD

**Issue by mtbradle-ge** [eslint/eslint#8583]
In the eslint documentation for the [eqeqeq](http://eslint.org/docs/rules/eqeqeq) rule it states:

"The --fix option on the command line can automatically fix some of the problems reported by this rule."

This doesn't seem to actually be the case. After digging around it looks like eqeqeq was updated some time back to not be automatically fixed due to the potential danger ([Issue 4578](https://github.com/eslint/eslint/issues/4578))

Tried on version v3.19.0 and spent some time wondering why it wasn't being fixed.

Apologies if this is the wrong place for this. I did not see a clear way to request changes to eslint.org/docs

**Comment by not-an-aardvark** [comment]
Some cases actually can be fixed (this was added in https://github.com/eslint/eslint/pull/7389). In general, rules with autofixers are not guaranteed to fix all reported problems.

This is also noted in the `eqeqeq` docs:

> The `--fix` option on the command line automatically fixes some problems reported by this rule. A problem is only fixed if one of the operands is a `typeof` expression, or if both operands are literals with the same type.

**Comment by mtbradle-ge** [comment]
Ah, thanks! That makes sense.
