### ISSUE TITLE
brace-style exception for comments

### ISSUE THREAD

**Issue by brigand** [eslint/eslint#8586]
With 1tbs I'd like an exception for when there's a comment above the else.

```js
// should PASS, does PASS
if (true) {
  a();
} else {
  b();
}

// should ERROR, does ERROR
if (true) {
  a();
}
else {
  b();
}

// should PASS, does ERROR
if (true) {
  a();
}
// something something
else {
  b();
}
```

Current config:

```json
    "brace-style": [
      "error",
      "1tbs",
      {
        "allowSingleLine": true
      }
    ],
```

Proposed

```json
    "brace-style": [
      "error",
      "1tbs",
      {
        "allowSingleLine": true,
        "allowComment": true
      }
    ],
```

---

* **ESLint Version:** 3.11.1
* **Node Version:** 6.10.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** Babel

**Comment by not-an-aardvark** [comment]
Thanks for the proposal.

My initial impression is that this seems like a very user-specific preference, so it might be better as a plugin or custom rule rather than an option for a core rule. However, let's see what the rest of the team thinks.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
