### ISSUE TITLE
JSX AST no longer uses Literal nodes inside of JSXElement children

### ISSUE THREAD

**Issue by soda0289** [eslint/eslint#8591]
There was an issues that came in to `typescript-eslint-parser` which suggested we were using the wrong node type for JSX text. (https://github.com/eslint/typescript-eslint-parser/issues/266) This lead to some discussion and eventually Facebook updated the JSX AST spec to use the `JSXText` node type instead of the `Literal` node type inside of `JSXElement` children.

This is a breaking change that will cause eslint rules in `eslint-plugin-react` and `
eslint-plugin-jsx-a11y` to not work if/when the change is made to espree. It does allow the produced AST to be more consistent with babel and flow-parser.

Is this something that we should change in ESLint v4? I think it might effect the JSX indent modification we have planned for this release. I have submitted a PR to acorn-jsx just in case we choose to make the change in espree.

**Comment by not-an-aardvark** [comment]
I agree that it would be nice to change this to conform to the spec, but it seems like this change would be on very short notice given that it would break several popular plugins. How important is it that we get this into v4? I'm thinking maybe it would be better to wait until v5.

**Comment by soda0289** [comment]
It is very short notice and does not provide any enhancement other than conforming to spec. Waiting for v5 makes sense. We can make the change in `typescript-eslint-parser` and hide it behind a flag.

**Comment by ljharb** [comment]
Any chance you'd be able to file issues to (or better, make PRs) both eslint-plugin-react and eslint-plugin-jsx-a11y, so that we (both we's) can prepare for this change ASAP?

**Comment by ljharb** [comment]
(linking to https://github.com/facebook/jsx/issues/50 and https://github.com/RReverser/acorn-jsx/issues/73 / https://github.com/RReverser/acorn-jsx/pull/74)

**Comment by soda0289** [comment]
I'm willing to make PRs if we choose to make the change for ESLint v4. I use both of the mentioned plugins myself and would hate for them to lose compatibility. ESLint v5 will not be out for a while and I think we should wait until ESLint v5 is in alpha before we make breaking changes to those plugin's rules.

**Comment by ljharb** [comment]
I don't think they'd have to be breaking changes; it should be trivial to support both node types simultaneously (the tests would be harder).

**Comment by soda0289** [comment]
It might be possible to support both node types fairly easily. I will look into it and create issues in those plugin's repositories.

**Comment by mysticatea** [comment]
I close this issue since #10152 fixed it.
