### ISSUE TITLE
New config propsal: warn me if my ruleset doesn't cover a rule

### ISSUE THREAD

**Issue by StoneCypher** [eslint/eslint#8595]
I'm in the process of upgrading from an older eslint to a more modern one.  The gap's pretty big.

It would be nice if there was a flag I could throw in the ESlint config that would force me to have a rule specified for every single known rule, by enumerating each missing one.

This would support me in finding new rules I didn't know about, and in making sure that plugin rulesets were fully utilized.

Thank you for your consideration

**Comment by gyandeeps** [comment]
you can always use `[eslint:all](http://eslint.org/docs/user-guide/configuring#using-eslintall)` inside your config to get all the rules..

**Comment by StoneCypher** [comment]
nevermind.  thank you, @gyandeeps

**Comment by StoneCypher** [comment]
No, this isn't what I needed, now that I look at it more closely.

The gag is that I want to be able to set my rules in an npm module like it shows in the docs, and have a newer version of eslint that came up with a new rule warn me "hey, guy, you don't have a rule for `no-foo-when-bar`."

**Comment by platinumazure** [comment]
Yeah, `eslint:all` only covers core rules.

I like this idea but I'm not sure it should be part of ESLint core. I think we should have enough APIs exposed via CLIEngine that maybe someone could build a tool for it. But if the team is open to including this in core, I'm not strongly opposed.

**Comment by gyandeeps** [comment]
Personally I dont see any value in adding this kind of option which has very limited advantage/usage. 
You can use `linter` API and then get all the loaded rules and then match them against your list. So thier are ways to get the info what you are looking for.

Lets see what the team thinks.

**Comment by StoneCypher** [comment]
i am impressed with how quickly multiple community members responded.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/eslint-find-rules with the `--unused` option handles this.

**Comment by StoneCypher** [comment]
that'll do, then.  thanks, @ljharb
