### ISSUE TITLE
minor rephrasing in documentation: about page

### ISSUE THREAD

**Issue by sudarsangp** [eslint/eslint#8600]
Under **Philosophy** section, **Every rule** subsection

existing: Can be **able to be** turned off or on
suggestion: Can be turned off or on

existing: Can be set to **be** a warning or error individually
suggestion: Can be set to a warning or error individually

**Comment by platinumazure** [comment]
Hi @sudarsangp, thanks for the issue. I agree with those changes (especially the first one).

Would you be interested in opening a pull request against [eslint.github.io](https://github.com/eslint/eslint.github.io) to fix these?

**Comment by sudarsangp** [comment]
Hi @platinumazure, yes for sure!

Please refer to the PR here (https://github.com/eslint/eslint.github.io/pull/352)

**Comment by ilyavolodin** [comment]
@platinumazure This change needs to be done in ESLint main repository, as about file is copied from here as part of the release process.

**Comment by platinumazure** [comment]
@ilyavolodin Why is that file, which shouldn't depend on rule metadata, generated from here?
