### ISSUE TITLE
ESLint suggesting to use CONST instead of LET for variable inside loop which is going to get reassigned

### ISSUE THREAD

**Issue by abinashdpatra** [eslint/eslint#8621]
**Tell us about your environment**

* **ESLint Version:v3.19.0**
* **Node Version:v6.10.2**
* **npm Version:3.10.10**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-eslint
**Please show your full configuration:**

```
{
    "parser": "babel-eslint",
    "env": {
        "browser": true,
        "node": true,
        "es6": true,
        "jquery": true,
        "mocha": true
    },
    "globals": {
        "expect": true,
        "sinon": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "arrowFunctions": true,
            "binaryLiterals": true,
            "blockBindings": true,
            "classes": true,
            "defaultParams": true,
            "destructuring": true,
            "forOf": true,
            "generators": true,
            "modules": true,
            "objectLiteralComputedProperties": true,
            "objectLiteralDuplicateProperties": true,
            "objectLiteralShorthandMethods": true,
            "objectLiteralShorthandProperties": true,
            "octalLiterals": true,
            "regexUFlag": true,
            "regexYFlag": true,
            "spread": true,
            "superInFunctions": true,
            "templateStrings": true,
            "unicodeCodePointEscapes": true,
            "globalReturn": true,
            "jsx": true,
            "experimentalObjectRestSpread": true
        }
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "strict": [2, "never"],
        "no-var": 2,
        "prefer-const": 2,
        "no-shadow": 2,
        "no-unused-vars": [2, {
            "vars": "local",
            "args": "after-used"
        }],
        "no-use-before-define": 2,
        "no-redeclare": 2,
        "no-proto": 2,
        "no-invalid-regexp": 2,
        "camelcase": [2, {
            "properties": "never"
        }],
        "vars-on-top": 2,
        "semi": 2
    }
}



```

**What did you do? Please include the actual source code causing the issue.**

```js

for (let i = 2; i < 100; i++) {
        let newSomeObj = new someObjModel({someProp: 'mock_'+i});
}




```

**What did you expect to happen?**
no suggestions
**What actually happened? Please include the actual, raw output from ESLint.**
suggesting to replace LET with CONST, but as the variable is inside for-loop, its going to get reassigned and will result in an error

[eslint] 'newSomeObj' is never reassigned. Use 'const' instead. (prefer-const)

**Comment by platinumazure** [comment]
`let` bindings are block scoped, meaning the variable becomes inaccessible once you leave the for loop or even when you get to the end and loop again. So this rule is correctly detecting that there is no reassignment of the variable and letting you know it could be made `const`.

**Comment by jeffbyrnes** [comment]
I must be missing something, b/c when I try this out very simply in the Node REPL:

```
> for (const i = 1; i < 3; i++) {
... console.log(`We now have ${i}`);
... }
We now have 1
TypeError: Assignment to constant variable.
> for (let i = 1; i < 3; i++) {
... console.log(`We now have ${i}`); }
We now have 1
We now have 2
undefined
```

That would seem to suggest that ESLint should not make this recommendation. I do understand the scoping for a `let`, but within the block, it would seem that `const` would prevent you from changing the value of `i` (or any other var, e.g., `for (let user of users) { … }`)

**Comment by not-an-aardvark** [comment]
@jeffbyrnes The original issue was referring to the `newSomeObj` variable, not the `i` variable. As you noted, the `i` variable needs to be declared with `let` (and ESLint correctly does not report it).

**Comment by jeffbyrnes** [comment]
@not-an-aardvark ah! I misunderstood. I ended up here b/c this code:

```javascript
for (let user of users) {
  memberships.push(add_membership(group_id, user));
}
```

Triggers this:

```
/Users/jeffbyrnes/dev/devsite/bin/create-admin
  34:12  error  'user' is never reassigned. Use 'const' instead  prefer-const
```

Which I’ve demonstrated is incorrect. I’ll see about finding a more appropriate issue, or opening one.

**Comment by not-an-aardvark** [comment]
In fact, with a `for-of` loop you can use `const` rather than `let` (unlike with a regular `for` loop), because the variable is never explicitly reassigned (it effectively goes out of scope after every iteration of the loop).

**Comment by jeffbyrnes** [comment]
Thanks for the clarification. Rather subtle nuance there.
