### ISSUE TITLE
Scheduled Release for June 2, 2017

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8627]
The scheduled release on Friday, June 2, 2017 is assigned to:

* @btmills
* @ilyavolodin

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by btmills** [comment]
ESLint v4.0.0-rc.0 has been released! http://eslint.org/blog/2017/06/eslint-v4.0.0-rc.0-released

The release process was not the most fun, and I'll document what went wrong later. For now, please merge only semver-patch changes until v4.0.0 has been released.

**Comment by not-an-aardvark** [comment]
Thanks for doing the release :tada:

---

What's the schedule for v4.0.0? If we're only merging semver-patch changes until then, maybe it's not worth blocking everything else for two weeks (assuming we don't suddenly get a lot of bug reports).

Also, should we make semver-minor bugfixes to rules before the release? For example, fixing #8666 will result in the rule reporting more errors, so it's semver-minor.
