### ISSUE TITLE
Scheduled release for June 11, 2017

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8628]
The scheduled release on Sunday, June 11, 2017 is assigned to:

* @not-an-aardvark
* @kaicataldo 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by not-an-aardvark** [comment]
After some internal discussion we decided to reschedule the release because we didn't want to block all semver-minor changes from getting worked on for two weeks. So we're planning to release 4.0.0 tomorrow.

**Comment by not-an-aardvark** [comment]
ESLint 4.0.0 has been released: http://eslint.org/blog/2017/06/eslint-v4.0.0-released

Now that we're done doing prereleases, we're going back to our normal release cycle, which sometimes requires patch releases. Please only merge semver-patch PRs until we determine whether a patch release is necessary on Wednesday.

**Comment by not-an-aardvark** [comment]
We decided not to do a patch release. This concludes this release cycle; feel free to merge semver-minor commits again.
