### ISSUE TITLE
Shorten commit message length limit to 64 characters

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8634]
We currently have a commit message length limit of 72 characters. I suspect this number was chosen because GitHub truncates messages longer than 72 characters and puts them on a new line.

However, since we use GitHub's "squash and merge" feature, the PR number gets appended to the end of a commit message when we merge it, e.g. " (#1234)". This often makes the commit message longer than 72 characters when it gets merged, even though the commit message on the PR was within the length limit on the PR.

" (#1234)" is 8 characters long, so if it's still important to us that commit messages display on one line, we should reduce the length limit to 64 characters to accommodate for the added length. (We would reduce it to 63 characters when we start having five-digit PR IDs.)

Commit messages are also displayed in changelogs and blogposts, so we might also decide that it's worth having the extra space for descriptive messages even if they overflow on GitHub.

**Comment by soda0289** [comment]
In my opinion I think its more important to have a descriptive commit message/title then it is for them to show up on github commit list untruncated. I don't like abbreviations or code words and think this change would encourage their use. Maybe if we enforced a more detailed commit message, or moved the `(fixes #1234)` into the commit body, this change would work better.

**Comment by not-an-aardvark** [comment]
> In my opinion I think its more important to have a descriptive commit message/title then it is for them to show up on github commit list untruncated. I don't like abbreviations or code words and think this change would encourage their use. Maybe if we enforced a more detailed commit message, or moved the `(fixes #1234)` into the commit body, this change would work better.

I agree. My one concern about putting the `(fixes #1234)` in the commit body is that it won't display in the changelog or blogpost, and it seems like that might be useful for readers. Maybe we could update the release tooling to search for `fixes` messages in the commit message body, and append them to the end of the changelog entries.

**Comment by not-an-aardvark** [comment]
Closing because it seems like there's not much interest in changing this.
