### ISSUE TITLE
indent with jsx and ternary indents 2nd expression by an extra level

### ISSUE THREAD

**Issue by lukeapage** [eslint/eslint#8637]
**Tell us about your environment**

* **ESLint Version:** 4.0.0-beta.0
* **Node Version:** v4
* **npm Version:** v3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
```

**What did you do? Please include the actual source code causing the issue.**

```js
export function HeaderTooltip({ primaryTitle, secondaryTitle }) {
    return secondaryTitle ? (
        <div>
            <p>{primaryTitle}</p>
            <p>{secondaryTitle}</p>
        </div>
    ) : (
        <p>{primaryTitle}</p>
    );
}
```

**What did you expect to happen?**

No error

**What actually happened? Please include the actual, raw output from ESLint.**

The fixed output is:

```js
export function HeaderTooltip({ primaryTitle, secondaryTitle }) {
    return secondaryTitle ? (
        <div>
            <p>{primaryTitle}</p>
            <p>{secondaryTitle}</p>
        </div>
    ) : (
            <p>{primaryTitle}</p>
        );
}
```

**Comment by soda0289** [comment]
I have seen this style often in JSX code. When people write JSX they use many ternary expressions. I think that if you remove the parenthesis the indent would not be forced on the 2nd expression. This could be considered a bug.

**Comment by not-an-aardvark** [comment]
I agree.
