### ISSUE TITLE
Override the required "eslint-config-" prefix for shareable configs 

### ISSUE THREAD

**Issue by agaray913** [eslint/eslint#8644]
**What version are you using?**
v3.19.0

**What did you do?**
Did not prefix the name of my shareable config with "eslint-config-".

**What happened?**
When I tried to use the shareable config in a different module, eslint adds "eslint-config-" to the beginning of the name of the shareable config when trying to look up the shareable config module.
This causes eslint to not find the shareable config.

**What did you expect to happen?**
I expected eslint not to prepended "eslint-config-" to the name of my shareable config or some way to op-out of the naming convention.

**Comment by platinumazure** [comment]
Hi @agaray913, thanks for the issue.

This is covered in our Shareable Configs [documentation](http://eslint.org/docs/developer-guide/shareable-configs). We look for prefixed configuration files because npm doesn't provide great APIs for searching by descriptive tags or any other fields-- instead, we have established a naming convention for this purpose.

**Comment by cleavera** [comment]
Hi @platinumazure, could you go into a bit more detail around the reasoning. This is my example:
```
{
  "extends": "@mhrwebcommon/config",
}
```
If I'm providing the path to the config why does it need to be prefixed with `eslint-config` in my example this module contains a `.eslintrc` file as well others such as `tslint.json` and `.stylelintrc`, which makes the enforcement of a naming convention rather obstructive.

**Comment by agaray913** [comment]
Hi @platinumazure,

I plan on publishing this shareable config to a private repo with its own naming conventions, not the public npm repo. So it would be nice to have eslint not add the prefix when it looks up the shareable config.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
