### ISSUE TITLE
MaxListenersExceededWarning installing eslint 3.19.0 with node 7.8.0

### ISSUE THREAD

**Issue by adjavaherian** [eslint/eslint#8645]
A simple install of 3.19.0 seems to cause a Node 7.8.0 memory leak.  

`npm i eslint@3.19.0 -g --loglevel verbose`

```
(node:91584) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit when doing an npm install of eslint 3.19.0
```

```
npm info using npm@4.6.1
npm info using node@v7.8.0
```

I don't really see any other relevant info, just a lot of these warnings.  Perhaps, I'm missing something?

**Comment by not-an-aardvark** [comment]
If it just happens when installing, it's probably an issue with npm, not eslint.

**Comment by adjavaherian** [comment]
verified.  doesn't happen with npm@3.10.8.
