### ISSUE TITLE
Allow using {} as an indicator of an unused function argument

### ISSUE THREAD

**Issue by jeremejevs** [eslint/eslint#8651]
In **3.15.0**, the following gets flagged by `no-empty-pattern`:

```js
const a = ({}, {}, x) => console.log(x)
```

But it's the only clean way to skip multiple arguments that I'm aware of (multiple underscores don't fly in strict mode). Would be nice to be able to add it as an exception to `no-empty-pattern`.

**Comment by not-an-aardvark** [comment]
I think using an empty destructuring pattern has the side-effect of throwing when the argument is `undefined` or `null`. In my opinion, it would be better to name the arguments `_` and `__` (or something like that) rather than using an empty pattern.

**Comment by jeremejevs** [comment]
Thanks for a prompt reply, you're right; didn't think this through. Closing.

About `_` and `__` - that can get ugly past 3-4 arguments. Doesn't happen often, but still. Also, this clashes with Lodash and such, unfortunately.
