### ISSUE TITLE
PolyGerrit using ESLint!

### ISSUE THREAD

**Issue by kaspnilsson** [eslint/eslint#8653]
Not an issue!

Just wanted to let the ESLint team know that we on PolyGerrit, an open source project funded by Google, are using ESLint as of about a month ago. https://gerrit.googlesource.com/gerrit/+/master/polygerrit-ui/

We really appreciate all of the work you all put into this tool! It helped us modernize our codebase from es5 to es6 much quicker than we could've otherwise.

**Comment by platinumazure** [comment]
Glad to hear ESLint has worked so well for you!

Would you like us to add you to our list of people using ESLint? If you can throw in a logo, we can add you to said list.

**Comment by not-an-aardvark** [comment]
Also see ["How to add your company/project logo to the site"](https://github.com/eslint/eslint.github.io/blob/36e532b0120a0e7b181fe8b853df701af7c4c2ad/README.md#how-to-add-your-companyproject-logo-to-the-site)

**Comment by soda0289** [comment]
I'm huge fan of Gerrit myself and use it daily. Its a very powerful source code review tool with great features I wish GitHub had. Love the work done with PolyGerrit and the 2.14 release so far.

**Comment by not-an-aardvark** [comment]
Glad to hear ESLint is working well for you!

I'm closing this issue because this isn't an issue with eslint, but feel to make a PR to the website if you want to add your logo.
