### ISSUE TITLE
strict rule does not insert `use strict` with --fix flag

### ISSUE THREAD

**Issue by vitalets** [eslint/eslint#8665]
* **ESLint Version:** v3.19.0
* **Node Version:** v7.2.0
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint

**Please show your full configuration:**
```json
{
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 6
  },

  "env": {
    "commonjs": true,
    "browser": true,
    "node": true,
    "es6": true,
    "worker": true
  },

  "rules": {
    "strict": ["error", "global"]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
I have following simple file `temp.js`:
```js
(function () {})();
```
When I run `eslint --fix ./temp.js` I'm still getting error:
```
1:1  error  Use the global form of 'use strict'  strict
```
**What did you expect to happen?**
`use strict` will be inserted into the file according to point 3 of https://github.com/eslint/eslint/issues/6668#issuecomment-232524648
```js
'use strict';
(function () {})();
```
**What actually happened? Please include the actual, raw output from ESLint.**
`use strict` is not inserted into the file.
```
1:1  error  Use the global form of 'use strict'  strict
✖ 1 problem (1 error, 0 warnings)
```

**Comment by gyandeeps** [comment]
Based on the source code, the fixer only **remove** `use strict`. there is no fixer to **add** `use strict`.

**Comment by platinumazure** [comment]
Hi @vitalets, thanks for the issue. Just want to note that whenever a rule is listed as fixable, we do not guarantee that a rule is fixable in all cases. This is because we want to avoid potentially doing fixes that could cause other problems.

I'm not sure we should add a fixer for adding `"use strict";` because adding statements can be pretty hard (due to needing to consider things like indentation, whether ASI should be used, linebreak style, etc.).

**Comment by not-an-aardvark** [comment]
The fixer for `strict` only removes redundant `use strict` statements. It intentionally doesn't do anything that would make strict mode code non-strict (or vice versa) because this could unexpextedly break the code at runtime.

**Comment by vitalets** [comment]
Ok, I get your points. Maybe mention this in docs? Now it's not clear that `use strict` is only removed and I spent a lot of time figuring out why.

Btw, finally I used https://www.npmjs.com/package/use-strict that just inserts `use strict` into the first line of file.

**Comment by not-an-aardvark** [comment]
Feel free to make a PR to clarify this if you'd like.

I'm glad that you found a solution that works for you. I would caution that the `use-strict` package will put *all* packages in strict mode, even third-party code which is not intended to be in strict mode. This could cause some runtime errors or unexpected behavior in third-party modules.

**Comment by vitalets** [comment]
@not-an-aardvark could you help me where I can change this in docs?
I've checked https://github.com/eslint/eslint/blob/master/docs/rules/strict.md but there is nothing about fixability. Although other fixable rules are contain, e.g. https://github.com/eslint/eslint/blob/f9b70b3718e9d44dc4e729e82ba1beb19c2ff7fd/docs/rules/space-return-throw-case.md
```
(fixable) The --fix option on the command line automatically fixed problems reported by this rule.
```

**Comment by ilyavolodin** [comment]
@vitalets You linked the right file. Fixibility blob is inserted by our release script from rule's metadata. So you can't modify that bit. But you can just a `Note` explaining that this rule does not insert new `use strict` statements, but only remove unneeded statements.

**Comment by not-an-aardvark** [comment]
There is a similar note in the docs for the `eqeqeq` rule, if that helps as an example.
