### ISSUE TITLE
Change request: add idiomatic JS (derived from jQuery style guide)

### ISSUE THREAD

**Issue by mikemaccana** [eslint/eslint#8673]
[idiomatic.js](https://github.com/rwaldron/idiomatic.js/) - derived from the jQuery style guide but suitable to JS everywhere - is one of the oldest and most established JS style guides. I was surprised that newer guides like AirBnB were included but idiomatic wasn't!

I suspect there's a few folk (maybe using jslint now) using either idiomatic or the original jQuery style guide. It would be useful to have these in eslint!

**Comment by ilyavolodin** [comment]
Could you clarify what you mean by "included". ESLint does not include any styleguides at all. We have a couple of them in the `eslint --init` command for user's convenience, but they are not created or maintained by ESLint's team. In regards to the question of why idiomatic was not included vs. AirBnB, AirBnB has a shareable eslint config that is maintained by the creator of that guide. I don't think there's an official idiomatic configuration out there.

**Comment by not-an-aardvark** [comment]
Closing because there was no response. Please feel free to open an issue if this is still something you would like to see included in ESLint.

**Comment by mikemaccana** [comment]
Sorry about the wait.

> We have a couple of them in the eslint --init command for user's convenience

Yes, that's what I meant.

> In regards to the question of why idiomatic was not included vs. AirBnB, AirBnB has a shareable eslint config that is maintained by the creator of that guide.

Ah, this looks like more something idiomatic would need to maintain. Makes sense. Thanks for the response.
