### ISSUE TITLE
chore: add greenkeeper to eslint

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8685]
[greenkeeper](https://greenkeeper.io/) is a useful tool, for automated dependency management.

**Comment by gyandeeps** [comment]
I dont think we have a problem which greenkeeper will solve for us. We are an active project and we have been very efficient  when it comes to updating our dependencies. And some time we deliberately hold off on it.
Secondly, greenkeeper creates a lot of PR noise and we already have so many PR.

With all that, i am 👎 for this. But thanks for opening the issue for discussion. Lets see what @eslint/eslint-team  thinks about this.

**Comment by platinumazure** [comment]
I agree, this isn't something we need. We could use david to look at
dependencies and just track them manually- we're pretty good about that.

**Comment by ilyavolodin** [comment]
We don't usually allow update of the dependancies just because new version came out. We should have a good reason why we are updating dependency (bug fix, new feature, etc.). There's too many people relying on ESLint for us to update dependencies as they come out.

**Comment by hzoo** [comment]
> Secondly, greenkeeper creates a lot of PR noise and we already have so many PR.

Just as FYI the issues you are probably talking about are from earlier versions of it. Because it's an integration now it can be smarter about the PRs so there isn't 100 PRs if someone pushes multiple versions (just one pr that is updated for a dep)

**Comment by not-an-aardvark** [comment]
> There's too many people relying on ESLint for us to update dependencies as they come out.

@ilyavolodin I don't understand what you mean by this -- since we use `^` in `package.json`, all our users will get the latest versions anyway (for non-semver-major changes).

**Comment by ilyavolodin** [comment]
@not-an-aardvark I'm talking about semver-major upgrades.

**Comment by mikesherov** [comment]
Semver major upgrades can be ignored by Greenkeeper. Version 2.0 is pretty darn configurable and not-so-noisy.

If anything, you should consider it an early warning system. All it really does, if we choose to ignore / not merge the PRs it generates is let you know if the dependencies you've already expressed are not broken.

I can't really see a downside to using it, even if the policy is "completely ignore the PRs it generates except if it not semver major but breaking".

That said, I don't do active maintenance on this repo, so easier said than done for me ;-)

**Comment by kaicataldo** [comment]
Thanks for the contribution, @Aladdin-ADD! While I see the value in a tool like this, I personally don't think this solves a problem we're currently experiencing, and I'd like to avoid using a new tool/integration without it solving a concrete problem we have.

I'm open to discussing though - do you feel like we're struggling with updating deps, @Aladdin-ADD?

**Comment by Aladdin-ADD** [comment]
Impressed by the kindness of eslint community. ❤️ 

To this point, actually we have been doing well in upgrade deps. But if these jobs can be automated, and have no downside( (greenkeeper v2 has a big improvement), it would be better. Personally I don't have a strong opinion.

**Comment by Aladdin-ADD** [comment]
as discussed in #8684 , we do not introduce greenkeeper, and will update deps periodically.
