### ISSUE TITLE
`globals` suppress all when defined only for variable in config

### ISSUE THREAD

**Issue by vitaly-zdanevich** [eslint/eslint#8688]
* **ESLint Version:** `v3.19.0`
* **Node Version:** `7.7.1`
* **npm Version:** `4.1.2`

**What parser (default, Babel-ESLint, etc.) are you using?**
`default`

**configuration:**
```
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "indent": [
            "error",
            2
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "globals": {
            "chrome": false
        }
    }
};
```

**js**:

```js
chrome.browserAction.onClicked.addListener();
// I want `no-undef` only here without specifying eslint config in my js file

dfgdfg.xxfdfdf();

```
I want to suppress `no-undef` for `chrome` (this is extension for browser) - for that I altered config - but this suppress *ALL* `no-undef` - not only `chrome` - my workaround is to use `/* globals chrome */`.

**Comment by gyandeeps** [comment]
I dont quite understand the question here (sorry about that).

But i will say that your config is not correct. `globals` is inside `rules` which is not correct. It has to be outside that.
Docs: http://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by vitaly-zdanevich** [comment]
Yes, my config was incorrect, thank you for help.

Maybe for such cases some config validator can warning about `globals` in `rules`?
