### ISSUE TITLE
Discussion: Improving TSC meetings

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8691]
Following up on [this topic](https://github.com/eslint/tsc-meetings/blob/0b69c20b635e569c405c03b0ea63dff8026c00f8/notes/2017/2017-06-01.md#avoiding-rescheduled-tsc-meetings) from the last TSC meeting: This issue is intended for discussion about how we can improve our process for TSC meetings. In my mind, there are a few problems that we should consider addressing (although feel free to edit this issue if there are any I've missed):

1. We sometimes have difficulty reaching quorum for meetings, so we need to reschedule them.
1. Since we [need to have a TSC meeting to approve certain types of changes](http://eslint.org/docs/maintainer-guide/issues.html#evaluating-core-features-and-enhancements-tsc-members-only), issues are sometimes blocked for awhile before the TSC can approve them.
1. The person championing the issue is sometimes not on the TSC, and TSC members raise objections that they can't address because they're not in the meeting (example: https://github.com/eslint/eslint/issues/8392)

cc @eslint/eslint-tsc

**Comment by not-an-aardvark** [comment]
My personal opinions on how we could address these:

1. We can look into rescheduling the meetings for a more convenient time, but aside from that there's probably not much we can do.
1. I think there is value in requiring TSC consensus for core changes (because it's important to get them right), but maybe we should update the policy to allow the change to be approved if a majority of the TSC votes on the issue, rather than needing to wait for a meeting.
1. This is where I think we can make the most improvement. At the moment, it seems like we sometimes add issues to the TSC agenda before ideas have been fully discussed. The result is that people bring up objections during the TSC meeting, and it's sometimes not possible to get a response from the author. I think it would be better to have more of the discussion on the issue itself, and discuss all the details there before having the TSC vote as a formality (or if consensus can't be reached).

**Comment by ilyavolodin** [comment]
I agree with point 2, we should add something to the documentation that says that if 5+ TSC members voted on the issue and nobody voted against, we can accept the issue without discussing it on the meeting.
In regards to number 3, we used to require summary and question to be posted on any issue marked for TSC discussion. Unfortunately, we haven't been doing it much lately, so in a lot of cases, TSC is left to guess what is the question that they are supposed to approve. I think we should bring back that policy.

**Comment by kaicataldo** [comment]
1) I'm not sure what the answer is for this. It's difficult with multiple time zones to find a time that works for everyone. That being said, I think if we can strive to do more more work asynchronously on the issues themselves, that will alleviate this problem by virtue of the meeting being less necessary :) Could we some kind of label or project that groups issues that require TSC attention so that they're more easily discoverable by us?
2) Totally agree! This is a sensible policy.
3) I know I've been guilty of this, hoping that we would be able to come to hash something out that was struggling to reach consensus in the issue. That obviously hasn't worked. @not-an-aardvark I like your idea of making it clear that issues should go to the TSC only once they have been discussed and the issue has become a concrete proposal.

**Comment by not-an-aardvark** [comment]
I guess there is one slight complication with the solution for issue 2 -- sometimes I :+1: an issue when I'm generally supportive of the idea, even though there are some details that need to be worked out. I think the point of the original policy was to make sure the TSC approves all those details, so if we changed the policy to not require a meeting, we would probably want to refrain from giving a :+1: until all the details were settled.

**Comment by platinumazure** [comment]
Would it be worth requiring that any TSC agenda issues also have a champion, whose responsibility it would be to be able to fully speak to the issue before or during a meeting (including, but not necessarily limited to, owning the TSC Summary/Question write-ups)?

Other reasons this could be a good idea:
* Sometimes I've been guilty of throwing "TSC agenda" on issues as soon as they are core changes. This runs the risk of issues not being fleshed out before then, unless the issue creator can fully speak to it.
* It's a natural extension of champions' existing responsibilities (which are, in a nutshell, do whatever it takes to get the proposal implemented). Basically, it would spell out that champions are responsible for helping TSC be able to review issues they need to review, as part of that process.
* Core changes that lack support on the team are likely to be rejected anyway- better to do that outside of a TSC meeting if possible.

**Comment by not-an-aardvark** [comment]
Looks like I lost track of this issue. Is https://github.com/eslint/eslint/issues/8691#issuecomment-306705179 still something we'd like to pursue? Personally I think we've gotten better at requesting design details for discussion in TSC meetings, so it's possible that no further modifications are necessary.

**Comment by not-an-aardvark** [comment]
Closing because I think the original problem from this issue has been resolved, but I'd be fine with discussing https://github.com/eslint/eslint/issues/8691#issuecomment-306705179 as a separate proposal.
