### ISSUE TITLE
Eslint crashing v8 on "eslint ." command

### ISSUE THREAD

**Issue by Syzygy24** [eslint/eslint#8698]
**Tell us about your environment**

* **ESLint Version:**
 3.19.0
* **Node Version:** 
6.10.2
* **npm Version:**
2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?**
 default

**Please show your full configuration:**

```
---
rules:
  max-len: 0
  valid-jsdoc: 1
```

**What did you do? Please include the actual source code causing the issue.**

```js
eslint .




```

**What did you expect to happen?**
Expected it to run lint

**What actually happened? Please include the actual, raw output from ESLint.**
> eslint .

FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [node]
 2: 0x109e13c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0x10c8048 [node]
 5: 0x1cdb0a515518

**Comment by not-an-aardvark** [comment]
That's strange, I wonder if it's a bug in Node.

Does the directory have any files in it, or does this happen with an empty directory too? It would be useful if you can create a reproducible case that causes the crash.

**Comment by Syzygy24** [comment]
Ok. I just figured out the problem. The directory did have files, but I didn't have my tmp/ directory added to .eslintignore. Added that and it fixed it! I'm gonna have trouble reproducing a crash case... tmp/ was massive and I can't think of way of telling which file was causing the crash.

**Comment by not-an-aardvark** [comment]
I'm glad you got it working. If you're willing to help a bit more -- what happens if you run eslint with the `--debug` flag (after removing `tmp/` from .eslintignore)?

```
eslint . --debug
```

That might help narrow down which file was causing the problem, if the crash occurred while linting a particular file.

(It's possible that this is still a bug that affects other users, so ideally it would be nice to figure out what was causing it.)

**Comment by Syzygy24** [comment]
Unfortunately, I cleared out the tmp/ folder before I added it to .eslintignore. I'll avoid doing that again for a while and see if I can get it to happen again.

**Comment by not-an-aardvark** [comment]
Ok, thanks. I'm going to close this issue for now (assuming it was a Node bug or something else and not an ESLint issue) but feel free to comment and/or open a new issue if you manage to reproduce it again.
