### ISSUE TITLE
configFile entries should be overridded by a local .eslintrc

### ISSUE THREAD

**Issue by drugan** [eslint/eslint#8738]
**What version are you using?**
![eslint-versions](https://user-images.githubusercontent.com/3609840/27174268-318e8ffc-51c4-11e7-92a3-9c51c851b346.png)

**What did you do?**
I develop some projects (a theme & a module) which are the subprojects of other big parent project [Drupal CMS](https://www.drupal.org/). The parent project by default has [.eslintrc.json](http://cgit.drupalcode.org/drupal/tree/core/.eslintrc.json?h=8.3.x) file with the CMS specific settings embedded into its [8.x core version](https://www.drupal.org/project/drupal).  To automate the process of files' linting/fixing I use the 4.0.0 version of [gulp-eslint](https://github.com/adametry/gulp-eslint). It accepts all the [eslint CLI](https://github.com/adametry/gulp-eslint#eslintoptions) options,  the **configFile** including. I resolve the path to the Drupal core parent project's .eslintrc.json programmatically in a gulp task and set it to the  **configFile** option's value to be in compliance with the CMS coding standards.

For the Drupal themes and modules it is pretty common to use external libraries embedded into their repositories (not node_modules installed with npm or similar). Sometimes the code on the libraries requires some changes because it has some issues. Obviously that after the code is changed it should be linted according coding standards accepted by a library developers team. Just in order to make it easier to open pull request. As the eslint also looks for the local .eslint* file while resolving config for the linting I've put the .eslintrc.json with the library specific settings into its folder.

**What happened?**
Basically, only the settings which don't exist in the core's  .eslintrc.json **configFile** have effect when linting the library folder. If any setting exists in both files then the core's one is in effect.

[Docs](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy): 

> By default, ESLint will look for configuration files in all parent folders up to the root directory. This can be useful if you want all of your projects to follow a certain convention, but can sometimes lead to unexpected results. To limit ESLint to a specific project, place "root": true inside the eslintConfig field of the package.json file or in the .eslintrc.* file at your project’s root level. ESLint will stop looking in parent folders once it finds a configuration with "root": true.

The cited above does not work.

**What did you expect to happen?**

I want the local .eslintrc* to have prirority when resolving config settings. See more on the [PR](https://github.com/eslint/eslint/pull/8731).

**Comment by kaicataldo** [comment]
Hi! Thanks for making issue.

ESLint already does [configuration cascading](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) - does the built in behavior not work for this case?

If that doesn't work, have you tried using the [`extends`](http://eslint.org/docs/user-guide/configuring#extending-configuration-files) option in your local .eslintrc?

**Comment by drugan** [comment]
Yes, I've read about configuration cascading and even put the link to it in my first comment ([Docs](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)).  Also, I know that configurations can be overridden by a custom module, *.json file having **extends** entry, inline rules, etc..

The Drupal projects I develop are a kind of starter kit for further developing and I want to make initial set up of the projects as simple as it possible. Just to instruct a user to run `npm install` and then copy the core's [.eslintrc.json](http://cgit.drupalcode.org/drupal/tree/core/.eslintrc.json?h=8.3.x) and put it in a library folder where this file file should be adjusted to the library coding standards (adding **"root": true** entry). That's it.

Note, that the exact path from my project to the core's  [.eslintrc.json](http://cgit.drupalcode.org/drupal/tree/core/.eslintrc.json?h=8.3.x) can only be detected dynamically. So it can be done in a custom node module or in a gulpfile.js file as in my case. That's because of the Drupal file structure which may differ on different projects. The same with the external libraries used by a user. The existence and the path to those libraries in a module or theme are not known previously.

**Comment by gyandeeps** [comment]
Can you please create a repro case on GitHub and share that project? Also it will be awesome if you can use eslint directly and not include glup in the mix.
This will help us better understand the issue in hand. Thanks.

**Comment by drugan** [comment]
@gyandeeps 

Please, do the following:

run this first:

`git clone https://github.com/drugan/repro-eslint-issue-8738.git;cd ./repro-eslint-issue-8738/parent_project;npm install;`

It installs the eslint and creates the simple project which has similar of the Drupal CMS file structure. So, you should to be in the **parent_project** folder after installing. Open the files below in your editor:

**./core/.eslintrc.json  ./child_project/main.js  ./child_project/.eslintrc.json ./child_project/folder1/child.js  ./child_project/folder1/.eslintrc.json  ./child_project/folder1/folder2/child.js**

run this:

`./node_modules/eslint/bin/eslint.js -c core/.eslintrc.json child_project/*`

You'll see that only settings in the **./core/.eslintrc.json** are applied. None of the **./child_project/** **.eslintrc.json** files are in the effect, no matter if they have **"root": true** entry or not.

run this:

`cd node_modules/eslint; wget https://patch-diff.githubusercontent.com/raw/eslint/eslint/pull/8731.diff;patch -p1 < 8731.diff;cd ../../`

run this again:

`./node_modules/eslint/bin/eslint.js -c core/.eslintrc.json child_project/*`

You should see that the settings **./child_project/** **.eslintrc.json** files are in the effect now. Starting from the first file having **"root": true** and going deeper in the child folders all the settings of the previous file(s) are overridden with the current local one.

For the sake of simplicity I've made this example as much simple as it possible. Add more complex code to *.js and settings to *.eslintrc.json files and play around moving or removing **"root": true** from config files.

**Comment by platinumazure** [comment]
I haven't had a chance to look at the repo or try it out, but I can tell you that `-c some-config` will result in the specified config file having highest precedence compared to everything else. So if that base config has lots of options specified, it could very well look like no other options are being read in the other config files.

If your goal is for the config file you call out on the command line to be used with every ESLint config, while still taking advantage of directory cascading and `root: true`, your best bet is to use the `extends` configuration option and just use a path as its value. E.g., `extends: "../../core/.eslintrc.json`

Sorry if I missed the mark.

**Comment by drugan** [comment]
@platinumazure

As I said in my [previous comment](https://github.com/eslint/eslint/issues/8738#issuecomment-308785704) the exact path to the **core/.eslintrc.json** is unknown. If I go this way I have to instruct a user to figure out this path which might look like this:

`extends: "../../../../../../../../core/.eslintrc.json"`

What if you need to extend this file in multiple places? This feature may become pretty complex to use if usable at all.

Instead I suggest a straightforward copy/paste workflow if a user needs something to override in a specific directory.

**Comment by not-an-aardvark** [comment]
To clarify, are you suggesting that we change the `-c <path>` option to give the config file at `<path>` low precedence, rather than high precedence? I would be concerned about doing this because it seems like it would be a significant breaking change.

**Comment by drugan** [comment]
@not-an-aardvark

I can't figure out where it may break something. The schema suggested will work if both the `-c path` and `path` with **"root": true** exist. 

If there is just a single `-c path` then this file is applied as the main configuration. If there is no `-c path` file and `path` file with **"root": true** exist then this file is applied as the main configuration. That's exactly how it happens now without [PR](https://github.com/eslint/eslint/pull/8731) applied.

Did I miss something? Could you give me an example of a `significant breaking change`.

**Comment by not-an-aardvark** [comment]
By "significant" I mean that it would break any users that are relying on the opposite behavior (i.e. that config files with the `-c` flag have highest precedence). If I had to guess, I would say this affects a nontrivial number of users, although probably not a huge number.

I'm also not sure this change is a good idea. It seems like this would be overloading the meaning of `root: true` config option to mean something completely different from what it means now. There is already a way to do what you want with the `extends` option. (I acknowledge that it's not ideal to have to explicitly state a file path in the local configs -- although this comes with several other advantages, such as allowing editor integrations to statically determine the config without having access to the `-c` command line flag.) Overall, I'm unconvinced that this is a big enough problem for enough users to warrant changing the behavior.

**Comment by drugan** [comment]
@not-an-aardvark

OK, I see your considerations. Seems that my needs are quite specific and can only be satisfied on my own eslint fork/npm package. If I go that way additionally there is a possibility to add Drupal core's .eslintrc.json as a default config. So, any who uses the package from inside Drupal CMS can run the eslint without any previous set up and be sure that all the files are processed according Drupal coding standards. At the same time, they can override those standards by using the workflow suggested on the current issue/PR.

Please, close the issue and thanks to everyone for taking a look into it.
