### ISSUE TITLE
space-before-function-paren with anon async arrow functions

### ISSUE THREAD

**Issue by iCrawl** [eslint/eslint#8739]
**Tell us about your environment**

* **ESLint Version: 4.0.0**
* **Node Version: 8.1.1**
* **npm Version: 5.0.3**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
https://github.com/iCrawl/eslint-config-aqua/blob/master/index.js#L8
https://github.com/iCrawl/eslint-config-aqua/blob/master/index.js#L133

**What did you do? Please include the actual source code causing the issue.**
```js
Experience.addExperience(message.author.id, xpEarned).then(async () => {
	const newLevel = await Experience.getLevel(message.author.id);
	if (newLevel > oldLevel) {
		Currency._changeBalance(message.author.id, 100 * newLevel);
	}
});
```

**What did you expect to happen?**
The async in `[...].then(async () =>` to not error on me for space-before-function-paren, because its obviously not a function in that sense, its an anon async arrow function (lol).

**What actually happened? Please include the actual, raw output from ESLint.**
![](https://u.nya.is/mpalhn.png)
![](https://u.nya.is/nujzhe.png)

This happens on other spots where I use the same anon async arrow functions too.

I'm sorry if this already existed, I found 1 other issue that was similar, but in that issue it was talking about cases like `async (reaction, user) =>` or `async message =>` which do both work fine.

**Comment by soda0289** [comment]
`space-before-function-paren` has an option called `asyncArrow` that can be used to ignore or enforce a space between async and arrow functions. Would that solve your problem?

**Comment by iCrawl** [comment]
Oh yes, this definitely solves my issue.
Was I just not reading the changelog or was it not emphasized as a breaking change? I'm very very sorry if I overlooked this.

Thank you very much!

**Comment by soda0289** [comment]
It was added in ESLint v4. The changelog that is on the blog and in github only covers changes from the RC to final release. It is covered in the migration guide along with all the other changes in v4.
https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-4.0.0.md#-the-space-before-function-paren-rule-is-more-strict-by-default

I had a similar issue myself, glad you were able to find a solution.
