### ISSUE TITLE
no-extra-parens docs do not mention arrow function parameters

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#8741]
The [`no-extra-parens` rule docs](http://eslint.org/docs/rules/no-extra-parens) don't mention that arrow function parameter parens are always/intentionally ignored by the rule (contrast with regex literals and IIFEs, which are explicitly listed as always ignored).

In addition, the Related Rules section does not mention the arrow-parens rule.

Unsure if it might be worth adding a quick paragraph of prose about arrow parameter parens being covered by the other rule as well.

**Comment by TheGrandmother** [comment]
Why is the ignoring of arrow functions intentional?

And I second this addition, the current docs are a bit misleading about this.

**Comment by platinumazure** [comment]
@TheGrandmother Because that functionality is already covered by the `arrow-parens` rule. We intentionally try to avoid multiple rules writing functionality identical lint errors, because otherwise it could be confusing to users.

Of course, this also requires that our documentation explain those design decisions. :smile: When the documentation isn't doing that, that is also confusing to users.

Make sense?

**Comment by TheGrandmother** [comment]
@platinumazure Yes I know that you don't want overlapping rules (which is a good thing!) but why are there two different rules? Intuitive it feels like the `no-extra-parens` rule should cover arrow functions as well?

**Comment by mysticatea** [comment]
That reason is simple; parentheses of arrow function parameters are not parenthesized expressions which can change precedence.
