### ISSUE TITLE
New default parserOptions in eslint 4.0 breaks babel-eslint

### ISSUE THREAD

**Issue by danez** [eslint/eslint#8744]
As of eslint 4.0 there is no way anymore for a parser to determine what parser options the user supplied, because there are [default parserOptions](https://github.com/eslint/eslint/blob/master/conf/default-config-options.js#L28-L32) now merged into the user supplied options before they are handed over to the parser.

This breaks the behaviour of babel-eslint, as we were relying on getting the raw parserOptions from the user and if not set applying our [own defaults](https://github.com/babel/babel-eslint/blob/master/index.js#L362-L369) for this options.

With the current defaults in eslint 4.0 there is no way for us to know what the user supplied.

It would be nice to have the possibility to influence the default parserOptions in some standardized way. We are also [monkeypatching](https://github.com/babel/babel-eslint/blob/master/index.js#L64-L74) escope to be able to set our default values, which is really ugly and could probably be removed if the parser creates the default config. There are probably even more cases where eslint does different things based on this options, which are now out of sync with the options babel-eslint uses. (see babel/babel-eslint#458)

Maybe it would be possible that a parser exposes an optional API that sets the default values for the parser options.

```js
export function getDefaultOptions(rawConfig) {
  return {...};
}
```

Then eslint could consume this if available and merge it with your own default configs.

```js
let parserOptions = Object.assign({}, defaultConfig.parserOptions, parser.getDefaultOptions(config.parserOptions));
```

Would that be something you would be open to? Or can you think of any other solutions.

**Comment by not-an-aardvark** [comment]
Oops, this seems like a bug. I think this was caused by https://github.com/eslint/eslint/pull/8381, which was supposed to just be a refactor and not change the options that get passed to parsers.

**Comment by danez** [comment]
Thanks very much for the quick reply and PR. 

But even though this might be a bug, it brought up a general problem that we are currently facing, which is that the parser cannot supply default `parserOptions`. In the case of babel-eslint we set `sourceType` to `module` and `ecmaVersion` to the latest available by default, but this also means that the rest of eslint - outside of the parser - does not know about our default settings and therefore might produce unpredictable results.

**Comment by not-an-aardvark** [comment]
I think the parser can communicate the `sourceType` because there is a `sourceType` property on the root of the AST. (That said, I'm not sure the rest of eslint actually uses that property -- if it doesn't, it probably should.)

Is there a reason the other parts of eslint would need to know the `ecmaVersion`? The `sourceType` affects the semantics of the file, but it seems like the `ecmaVersion` is just a parser-specific detail in most cases.

**Comment by danez** [comment]
There are certainly some rules behaving differently when having a different ecmaVersion
https://github.com/eslint/eslint/blob/6a718ba/lib/rules/func-name-matching.js#L40-L51
https://github.com/eslint/eslint/blob/6a718ba/lib/rules/no-redeclare.js#L86-L98
