### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#8758]
I'd like to propose we add an official code of conduct to all ESLint org projects. While I think the team is overall conscious of making the process of contributing to ESLint a welcoming experience, it would be great to have readily available documentation about how we as maintainers and contributors should conduct ourselves as we work together.

If you haven't yet, check out the results from the [Open Source Survey](http://opensourcesurvey.org/2017/). The results are rather grim (not unexpectedly, unfortunately). I'd love for ESLint to be a shining example of inclusivity, and having a code of conduct is an actionable and important part of that.

My assumption is that no one would be against this (let's talk about it if you are!), but I'd like to discuss what that code of conduct should contain, whether we use and commit to upholding a code that is already in existence, such as the [Contributor Covenant](http://contributor-covenant.org/), or if we want to come up with our own language.

cc @eslint/eslint-team

**Comment by Aladdin-ADD** [comment]
if we do this, I would be very very glad to translate it to Chinese. :)

**Comment by platinumazure** [comment]
Did we do this already with https://github.com/eslint/eslint/issues/3095?

**Comment by kaicataldo** [comment]
Good find. How can we make this more visible? I'm a _maintainer_ and I had no idea we had this...

**Comment by alberto** [comment]
It looks like that was replaced by [this](https://js.foundation/community/code-of-conduct) when we joined the jquery foundation

**Comment by kaicataldo** [comment]
I have a few ideas:
* I think it would be helpful to call it out at the top of the contributing documentation
* Maybe we can add a CODE_OF_CONDUCT.md file that either copies the text from JS Foundation code of conduct or simply links to it

**Comment by kaicataldo** [comment]
@kborchers Is there a shareable markdown version of the foundation's code of conduct? Would the foundation be up for making that downloadable so that projects could easily copy and paste it into their own repos?

**Comment by not-an-aardvark** [comment]
I think the best thing to do would be to create `CODE_OF_CONDUCT.md` that just links to https://js.foundation/community/code-of-conduct. That way we can stay up to date with any changes to it.

**Comment by kborchers** [comment]
@kaicataldo Currently the JSF code of conduct just lives in WordPress. We could look into making a downloadable version but as @not-an-aardvark mentioned, though changes are likely few and far between, it's probably better to just link to ours to know you have the most up to date version. Most projects tend to just link via their README but if you wanted to use a CODE_OF_CONDUCT.md that would be fine too.

**Comment by kaicataldo** [comment]
@kborchers Thanks for the info!

I'll make a PR shortly.
