### ISSUE TITLE
Add optional opt in to change var to const with prefer-const

### ISSUE THREAD

**Issue by BridgeAR** [eslint/eslint#8759]
**ESLint Version:** 4.0.0

**Reasoning:**
Working on either Node.js or any other performance sensitive code where you still want to support some "older" Node.js versions, using `let` is not an option. It often results in deopts, is slower in general (older v8 versions) and IMHO has little benefit over `var`. Using `const` does not have those problems (there are exceptions) and it has a couple benefits over `var` like better readability.
It does have a different hoisting but this is often not a real issue and the hoisting is already detected in the `no-var` rule.

So I think it would be nice if you're open for adding a optional argument to the prefer-const rule to opt-in to also change var to const instead of only let.

**Comment by ilyavolodin** [comment]
To the best of my knowledge, `prefer-const` will automatically change `var` into `const` where possible. If the value of the variable is modified, it will change it into `let`.

**Comment by not-an-aardvark** [comment]
@ilyavolodin I don't think that's correct -- `prefer-const` ignores `var` entirely, and only considers `let` variables. We generally tell people to use `no-var` to address `var` variables.

**Comment by ilyavolodin** [comment]
Oh, right, sorry, I mixed up `prefer-const` and `no-var`

**Comment by xPaw** [comment]
I agree with this. I have a lot of `var something = require("module");` on top of my files and I'd like for this rule to catch these.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Comment by BridgeAR** [comment]
@not-an-aardvark I think it would be good to reopen this. As far as I know the necessary change would also be relatively small to include this as a new option.

My reasoning for reopening this is here https://github.com/nodejs/node/pull/15648#issuecomment-333030885
