### ISSUE TITLE
Eslint hangs when postcss is a project dependency

### ISSUE THREAD

**Issue by mikeyGlitz** [eslint/eslint#8768]
Adding `postcss` causes linting in my project to take a long time.
This is my config file:
```js
{
"env": {
"browser": true,
"node": true,
"jest": true
},
"extends": "airbnb"
}
```

Nowhere in my configuration does it require `eslint-config-postcss` or `eslint-config-cssnano`, but when I try to run eslint without them, the linter crashes.

I have `node_modules/**` in my `.eslintignore` file.

`eslint-config-postcss` and `eslint-config-cssnano` are both listed as devDependencies for `postcss`, but I don't know why my project would care.

I'm using the following:
eslint: 3.9.1
node: 6.10
yarn: 0.23.4
postcss: 6.0.2

I've already posted on the[ postcss issue tracker](https://github.com/postcss/postcss/issues/1041). The author seems to think it's related to my configuration.

**Comment by soda0289** [comment]
Can you run eslint with debugging and output and post the last couple lines into the issue:
`eslint --debug`

**Comment by kaicataldo** [comment]
@mikeyGlitz Just FYI, [ESLint ignores node_modules by default](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories):

> In addition to any patterns in a .eslintignore file, ESLint always ignores files in /node_modules/* and /bower_components/*.

**Comment by mikeyGlitz** [comment]
OK it was a configuration issue. I forgot to ignore my built artifacts folder

**Comment by kaicataldo** [comment]
Glad you solved it!
