### ISSUE TITLE
ESLint Error: Cannot find module 'locate-path'

### ISSUE THREAD

**Issue by mcmunder** [eslint/eslint#8786]
### my setup and config:

I am running eslint via plugins in both atom and vscode. 

vscode: 1.13.1
atom: 1.18.0
ESlint version: 4.0.0
Node version: 8.1.2
npm version: 5.0.3
parser: babel-eslint

.eslintrc.json:
```
{
  "extends": [
    "standard",
    "standard-react"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "promise",
    "import"
  ],
  "rules": {
    "object-curly-spacing": 2,
    "import/no-unresolved": 2,
    "import/named": 2,
    "import/namespace": 2,
    "import/default": 2,
    "import/export": 2
  },
  "env": {
    "browser": true,
    "jest": true
  }
}
```
Please be aware that this is in a create-react-app project so I do not know what other (eslint) magic might be going on behind the scenes.

### issue
I am opening a new file in vscode or atom and editor throws an error:
- vscode: `error Cannot find module 'locate-path'`
- atom (from dev tools console): 
```
[Linter] Error running ESLint Error: Cannot find module 'locate-path' linter-registry.js [sm]:137 
```

Hope this is enough information to get an idea what might be the issue...

**Comment by ilyavolodin** [comment]
This actually sounds like a problem with VSC plugin for ESLint. Can you try running ESLint from the command line, and see if it works?

**Comment by mcmunder** [comment]
ESLint is running without any errors from the command line. Sorry, should of course have tested that before submitting the issue... Guess I was still half asleep. I will report the issue in the VSC plugin repo then ;-)

**Comment by platinumazure** [comment]
No worries, thanks for checking and good luck with the VSC plugin.

Closing as this is not an ESLint issue.
