### ISSUE TITLE
Turn off branch builds for Travis and AppVeyor

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#8804]
Currently any PR made by core member of ESLint team is built 10 times on Travis. 5 as PR and 5 as branch. I think we can safely turn off branch builds in both Travis and AppVeyor and lower the load we put on those services (also it's sometimes takes longer for both branch and PR builds to complete).

**Comment by platinumazure** [comment]
:+1: especially if team members can do branch builds on demand.

**Comment by not-an-aardvark** [comment]
@platinumazure I'm not sure that would be possible. Could you elaborate on why you would find this useful? (It seems like it would be easier to just run `npm test` locally, but there might be a component that I'm missing.)

**Comment by platinumazure** [comment]
Well, npm test only runs tests on one Node version, so it would be nice to
have Travis branch build functionality for testing occasionally on all
environments- but only on demand rather than on every branch push, to
achieve the stated goal of faster builds.

**Comment by ilyavolodin** [comment]
One additional extra. I noticed that our CI builds are for some reason building jsDoc documentation after each build. Not really sure why that's necessary. We should remove it to speed builds up.

**Comment by platinumazure** [comment]
@eslint/eslint-team Any thoughts on this issue?

**Comment by gyandeeps** [comment]
I think we have majority vote for this. Do we still need to discuss this in TSC meeting?

**Comment by alberto** [comment]
I don't think so. Marking as accepted.
