### ISSUE TITLE
Feature request: better error for forgotten 'async' when await is used.

### ISSUE THREAD

**Issue by mikemaccana** [eslint/eslint#8811]
# What you did:

Uses `await` within a function and forgot `async` 

# What you would like to happen.

A message like:

> await requires an 'async' function 

or better.

# What actually happened.

> Unexpected token

This message is correct, but vague. 

Thanks for listening. I know the current behavior is correct, but `await` is becoming very popular and so is forgetting to add `async` to the parent function!

**Comment by platinumazure** [comment]
Unfortunately this is something that the parser throws before ESLint can lint the file (the message may look like a lint message, but in reality it's a parser error).

I'm all for fixing this, but I think we would have to fix this upstream in espree.

**Comment by not-an-aardvark** [comment]
Closing because this isn't something we can fix in ESLint -- we just get the error messages from whatever parser is configured. Feel free to open an issue on [acorn](https://github.com/ternjs/acorn) if you'd like to see this improve in our default parser.
