### ISSUE TITLE
indent rule should be more lax on line comments on consecutive lines

### ISSUE THREAD

**Issue by Canop** [eslint/eslint#8812]
**Tell us about your environment**

* **ESLint Version:** 4.1.0
* **Node Version:** 7.9.0
* **npm Version:** 4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```
			"indent": [ 2, "tab", {
				"MemberExpression": "off"
			}],
```

Full configuration here: https://github.com/Canop/miaou/blob/master/gulpfile.js#L80

**What did you do? Please include the actual source code causing the issue.**

```js

			var now = (Date.now()/1000|0);
			m.room = shoe.room.id;  // to trigger a security exception if user tried
						// to mod_delete a message of another room
			m.content = "!!deleted by:" + shoe.publicUser.id + ' on:'+ now + ' ' + m.content;
			return this.storeMessage(m, true)

```

code around: https://github.com/Canop/miaou/blob/44970cf80b4f26a127744af64432aca9f536f0ca/libs/ws.js#L783

**What did you expect to happen?**

I expected eslint to either

* accept this comments formatting without triggering an error (as in previous eslint versions)
* let me disable indent checks on comments
* let me configure the indent rule to accept (not exclusively) this kind of comment formatting (self aligned on the first possible tab indent (which depends on the number of spaces per tab))

**What actually happened? Please include the actual, raw output from ESLint.**

I didn't find any way to keep this comment as is without disabling the whole indent rule.

**Comment by platinumazure** [comment]
Edited the title to make it a little more clear (I interpreted "multi-line comments" as "block comments" on initial read).

Currently, comments are allowed to be indented in one of three ways:
* Align with first token of previous line
* Align with first token of next line
* The "correct" location based on immediate previous tokens (i.e., the same location a statement would be expected to go)

The comment in your example is none of those.

It might be worth enhancing the rule (either by default, or via new option) to allow a line comment's indentation to be the same location as the beginning of the previous line's line comment (where there is one).

@not-an-aardvark Thoughts?

**Comment by not-an-aardvark** [comment]
I'm not really convinced that this is a good behavior (it seems strange to have comments aligned with each other if one of them has nothing before it), but I have no strong objection to adding a behavior like that either. My only concern is that this would be increasing the internal complexity of the rule, as well as the number of potentially-surprising cases for the user, for questionable benefit.

**Comment by yairEO** [comment]
I want ESLIST to completely ignore comments. it's pissing me off that I don't have full control and then my stack shows a TON of warnings for my code comments in million files. so annoying.

**Comment by platinumazure** [comment]
@yairEO I've created issue #9018, containing a proposed enhancement to ignore comment indenting entirely. Please follow that issue.

@not-an-aardvark @Canop I've :+1:'d the proposal to support an option for allowing a comment-first line to be aligned with a trailing comment on the previous line. That said, I think this needs more bikeshedding/design before we could consider accepting and implementing the proposal.

**Comment by not-an-aardvark** [comment]
Is this still something that should be implemented, or does the `ignoreComments` option make this obsolete?

**Comment by Canop** [comment]
`ignoreComments` might be enough right now. Smart alignment checks would be interesting but are probably not necessary.
