### ISSUE TITLE
arrow-parens fixer gets tripped up with trailing comma in args

### ISSUE THREAD

**Issue by lencioni** [eslint/eslint#8834]
**Tell us about your environment**

* **ESLint Version:** v4.1.1
* **Node Version:** v6.2.2
* **npm Version:** v3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**
```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": 8
  },

  "rules": {
    "arrow-parens": ["error", "as-needed", {
      "requireForBlockBody": true
    }]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

With this code:
```js
const foo = (
  bar,
) => ({});
```

and then running `eslint --fix`

**What did you expect to happen?**

```js
const foo = bar => ({});
```

**What actually happened? Please include the actual, raw output from ESLint.**

The file was transformed to this syntax error.
```js
const foo = bar
) => ({});
```

The eslint output complains about the syntax error it introduced:

>  2:1  error  Parsing error: Unexpected token )

The fixer seems to work correctly if I remove the trailing comma from the argument.

**Comment by not-an-aardvark** [comment]
Thanks for reporting, I can reproduce this issue.
