### ISSUE TITLE
Jscs throws error when flow is used in the project

### ISSUE THREAD

**Issue by pramodsvidyarthi** [eslint/eslint#8836]
Hi, I get these below mentioned error when i run jscs on the solution 

jscs node expected but identifier found
cannot iterate TypeAlias
Unexpected end of node list but "punctuator" found

I'm currently uses jscs and eslint version 3

Any particular rule i can override in my .jsrc config to dissolve these error. Thanks

**Comment by ilyavolodin** [comment]
JSCS has been deprecated over a year ago, and no longer supported. ESLint has support for almost all of the JSCS rules now. And you can use `babel-eslint` as parser to allow parsing flow code.

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
