### ISSUE TITLE
Interest in ownership of the eslint formatter sublime plugin?

### ISSUE THREAD

**Issue by TheSavior** [eslint/eslint#8842]
I don't use the sublime plugin anymore and haven't been able to sufficiently maintain it for a while. That hasn't been fair to the people using it. Would the esling org be interested in taking ownership of the project? https://packagecontrol.io/packages/ESLint-Formatter

![screen shot 2017-06-29 at 8 19 25 pm](https://user-images.githubusercontent.com/249164/27719576-458b9226-5d08-11e7-85f0-922a775e1b1a.png)

**Comment by kaicataldo** [comment]
@TheSavior Does the project have anyone else who'd be interested in helping the org maintain it?

My biggest concern is that it's already difficult for the team to stay on top of all of the projects in the org. Let's see what the other team members have to say.

**Comment by TheSavior** [comment]
@mrjoelkemp used to help maintain the JSCS version. I'm not sure if he'd be interested. It looks like he may not have come over to the eslint org with the merger.

**Comment by kaicataldo** [comment]
Yes, he decided to continue on with other pursuits.

**Comment by not-an-aardvark** [comment]
This was discussed in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/df5bb3c39c6a87f0e11dbb1e5c0fda7f54563972/notes/2017/2017-07-06.md#interest-in-ownership-of-the-eslint-formatter-sublime-plugin). Unfortunately, while we wish we could adopt the project, there was consensus that the ESLint team doesn't have the capacity to maintain it.

That said, we can help promote the request for a maintainer (e.g. by tweeting about it) if you'd like.

**Comment by TheSavior** [comment]
Thanks for discussing it. A retweet would be great: https://twitter.com/Eli_White/status/883155753191657472
