### ISSUE TITLE
eslint accesses .eslintrc in current directory even if other config with "root": true was specified

### ISSUE THREAD

**Issue by irengrig** [eslint/eslint#8845]
[extraConfigAccess.zip](https://github.com/eslint/eslint/files/1115060/extraConfigAccess.zip)

**Tell us about your environment**

* **ESLint Version:*4.1.1*
* **Node Version:*6.10.0*
* **npm Version:*3.10.10*

**What parser (default, Babel-ESLint, etc.) are you using?*default*

**Please show your full configuration:**

```

please see the example project in attached .zip
[extraConfigAccess.zip](https://github.com/eslint/eslint/files/1115027/extraConfigAccess.zip)



```

**What did you do? Please include the actual source code causing the issue.**

1 extract project from zip
2 install dependencies (eslint) with npm i .
3 in command line, go to the root directory of the project and run eslint, get error:
PS D:\testProjects\ESLint\extraConfigAccess> node ./node_modules/eslint/bin/eslint.js -c ./inner/.eslintrc.json index.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\bin\eslint.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
PS D:\testProjects\ESLint\extraConfigAccess> node ./node_modules/eslint/bin/eslint.js -c ./inner/.eslintrc.json index.js

[object Object]:
        Configuration for rule "semi" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"rror"').

Error: [object Object]:
        Configuration for rule "semi" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"rror"').

    at validateRuleOptions (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-validator.js:
111:15)
    at Object.keys.forEach.id (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-validator.
js:151:9)
    at Array.forEach (native)
    at validateRules (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-validator.js:150:30
)
    at Object.validate (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-validator.js:201:
5)
    at loadFromDisk (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-file.js:549:19)
    at Object.load (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config\config-file.js:592:20)
    at Config.getLocalConfigHierarchy (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config.js:228:44
)
    at Config.getConfigHierarchy (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config.js:182:43)
    at Config.getConfigVector (D:\testProjects\ESLint\extraConfigAccess\node_modules\eslint\lib\config.js:287:21)

if you run the same from ./inner folder to check ./inner/index.js, no problem

```js

```

**What did you expect to happen?**
There are 2 eslint config files in the project: one in the root of the project, the other is in 'inner' folder.
In the command line, I specified -c ./inner/.eslintrc.json
In this ./inner/.eslintrc.json, the property "root": true is specified.
According to documentation, eslint should start search for config files from this file, and do not go into parent directories, because of "root": true

in reality, it also accesses .eslintrc.json from the parent directory (and the file is incirrect, so we get an error)

**What actually happened? Please include the actual, raw output from ESLint.**

only config file in ./inner directory is accessed; eslint works without problems

!! this issue was originally reported here: https://youtrack.jetbrains.com/issue/WEB-27273#u=1498136331948

Thank you for help in advance

**Comment by platinumazure** [comment]
If you want to avoid the directory traversal that finds `.eslintrc` in ancestor directories, you should use `--no-eslintrc` on the command line.

If you want the inner config to be used for files in the inner directory, then it should be sufficient to let the normal directory traversal find the inner config and use `root: true` to avoid getting the outer config. You shouldn't need to use `-c` in that case.

All of this is without having looked at the project, which I can't easily extract on mobile, so I apologize if I missed something.

**Comment by irengrig** [comment]
Thank you for the quick response.
Actually, neither of those.
We call eslint from WebStorm to show eslint errors in IDE editor.
We also want that the users were flexible to use whatever configuration they want.
We have 2 options about specifying eslint config file: 
1)"search" - this will run eslint without -c or other options in each file's parent directory.
2) the issue is about this option - for the specified config file.
config, specified by the user, is passed with -c option, but the user themselves decides whether to use "root": true in their config.
And so, in this case, the user specifies config in ./inner/ directory, and we should use eslint -c ./inner/.eslintrc.json for all files - both inside or outside the directory.

So, when we are running "eslint -c ./inner/eslintrc.json index.js" we are getting this error about error in ./eslintrc.json - which means that eslint accesses ./eslintrc.json despite it was given ./inner/.eslintrc.json, in which (./inner/.eslintrc.json) there is this "stop" option "root": true

**Comment by not-an-aardvark** [comment]
Closing because this is working as intended.
