### ISSUE TITLE
handeling of ternary based assignment changed in indent

### ISSUE THREAD

**Issue by futagoza** [eslint/eslint#8847]
**Tell us about your environment**

* **ESLint Version:** 4.1.1
* **Node Version:** 8.1.3
* **npm Version:** 5.0.3

**What parser are you using?** babel-eslint (via preset [eslint-config-futagozaryuu](https://github.com/futagoza/eslint-config-futagozaryuu))

**Please show your full configuration:**

_https://github.com/futagoza/babel-preset-futagozaryuu/blob/master/src/.eslintrc.js_
```js
"use strict";

module.exports = {

    "extends": [
        "futagozaryuu/esnext",
        "futagozaryuu/node"
    ],

    "root": true

};
```

**What did you do? Please include the actual source code causing the issue.**

_https://github.com/futagoza/babel-preset-futagozaryuu/blob/master/src/buildOptions.js#L79_
```js
// ...

export default function buildOptions( _config = {} ) {

    // ...

    if ( ! config.node ) {

        const engines = getPackage( config.cwd || defaultOptions.cwd ).engines;

        config.node = engines && engines.node
                    ? majorSemver( String( engines.node ) )
                    : defaultOptions.defaultNodeVersion;

    }

    if ( typeof config.node === "string" ) {

        config.node = config.node.includes( "." )
                    ? parseFloat( config.node )
                    : parseInt( config.node, 10 );

    }

    // ...

}
```

**What did you expect to happen?**

Before the upgrade to ESLint v4, the rule `ident` allowed the above.

**What actually happened? Please include the actual, raw output from ESLint.**

After the upgrade to ESLint v4, the rule `ident` throws the error:

_https://travis-ci.org/futagoza/babel-preset-futagozaryuu/builds/248821808_
```bash
C:\projects\babel-preset-futagozaryuu\src\buildOptions.js
  84:1  error  Expected indentation of 12 spaces but found 22  indent
  85:1  error  Expected indentation of 12 spaces but found 22  indent
  92:1  error  Expected indentation of 12 spaces but found 20  indent
  93:1  error  Expected indentation of 12 spaces but found 20  indent

✖ 4 problems (4 errors, 0 warnings)
  4 errors, 0 warnings potentially fixable with the `--fix` option.
```

Modifiing the [eslint command at the top of the file (for this)](https://github.com/futagoza/babel-preset-futagozaryuu/blob/master/src/buildOptions.js) returns the orignal behaviour, but I'd prefer not to do this:

```js
/* eslint prefer-const: 0, indent: 0, indent-legacy: ["error", 4, { "SwitchCase": 1 }]*/
```

**Suggestion:**

1) Restore the way `indent` checks ternary based assignments.

2) Add a new boolean option for the `indent` rule called `ignoreTernaryAssignment`

**Comment by kaicataldo** [comment]
Thanks for the issue. The indent rule in 3.0 was extremely buggy and so was completely rewritten in v4. The new version of the rule is more strict (the trade off is that it's autofixable now!). That being said, we left the [legacy indent rule](http://eslint.org/docs/rules/indent-legacy) in for those who prefer the old behavior. You can change `indent` to `indent-legacy` in your configuration and it will use the old rule instead.

**Comment by kaicataldo** [comment]
There's also a proposal to enhance the rule to be able to ignore nodes, which I think would also solve your issue: https://github.com/eslint/eslint/issues/8594

**Comment by futagoza** [comment]
@kaicataldo Yea, it actually would 😄, thanks for informing me

**Comment by kaicataldo** [comment]
Closing this since https://github.com/eslint/eslint/issues/8594 exists and is being tracked!
