### ISSUE TITLE
Cannot read property 'superCalled' of undefined

### ISSUE THREAD

**Issue by warent** [eslint/eslint#8848]
**Tell us about your environment**

* **ESLint Version:**
^3.8.1
* **Node Version:**
7.6.0
* **npm Version:**
4.1.2

**What parser (default, Babel-ESLint, etc.) are you using?**
    "babel-eslint": "^7.0.0",
    "eslint": "^3.8.1",
    "eslint-config-react-app": "^0.6.2",
    "eslint-plugin-flowtype": "^2.21.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.10.0"

**Please show your full configuration:**

```
{
  "extends": "react-app",
  "rules": {
    "semi": "warn",
    "no-mixed-spaces-and-tabs": "warn",
    "space-before-blocks": "warn",
    "space-unary-ops": "warn",
    "space-in-parens": "warn",
    "semi-spacing": "warn",
    "indent": ["warn", 2],
    "quotes": ["warn", "single"],
    "no-duplicate-imports": "warn",
    "jsx-quotes": ["warn", "prefer-double"],
    "react/jsx-curly-spacing": [2, "always"],
    "constructor-super": "warn",
    "prefer-spread": "warn",
    "no-var": "warn",
    "no-trailing-spaces": "warn",
    "object-curly-spacing": ["warn", "always"],
    "import/order": ["warn", { "groups": ["builtin", "external", "internal", "parent", "sibling", "index"], "newlines-between": "always" }],
    "no-multiple-empty-lines": ["warn", { "max": 1, "maxEOF": 1 }],
    "import/no-webpack-loader-syntax": "warn"
  },
  "globals": {
    "chrome": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
class Extender {}
class BugProof extends Extender {

  constructor(props) {
    super(props);

    try {
      let arr = [];
      for (let a of arr) {

      }
    } catch (err) {

    }
  }
  
}
```

**What did you expect to happen?**
It shouldn't give any error

**What actually happened? Please include the actual, raw output from ESLint.**
<img width="1248" alt="screen shot 2017-06-30 at 9 15 18 am" src="https://user-images.githubusercontent.com/13342266/27744534-ab05eb3a-5d74-11e7-8edc-a8207e721704.png">

```
file: 'bug.js'
severity: 'Error'
message: 'Parsing error: Unexpected token

  19 |   
  20 | 
> 21 | 
     | ^'
at: '21,1'
source: 'eslint'
```

The location of the "Parsing error: Unexpected token" will change depending on the last line edited.

**Comment by warent** [comment]
<img width="1030" alt="screen shot 2017-06-30 at 9 14 35 am" src="https://user-images.githubusercontent.com/13342266/27744497-90be3340-5d74-11e7-952f-c31b7640119f.png">

**Comment by kaicataldo** [comment]
I haven't been able to reproduce, but whoever is looking into this should start with the `no-this-before-super` rule.

**Comment by warent** [comment]
Please note that the error goes away when the `for` loop is altered:
```js
class Extender {}
class BugProof extends Extender {

  constructor(props) {
    super(props);

    try {
      for (let i = 0; i < 1; i++) {

      }
    } catch (err) {

    }
  }
}
```

**Comment by kaicataldo** [comment]
I can recreate this with the latest version of ESLint.

**Comment by Aladdin-ADD** [comment]
@kaicataldo I find the error seems occur in rule `constructor-super`:

**Comment by not-an-aardvark** [comment]
It's possible that this is a bug in the core code path analysis logic.

**Comment by gyandeeps** [comment]
@mysticatea Any insight on this?

**Comment by mysticatea** [comment]
Oh, I'm sorry, I had overlooked this issue.
I will take a look.

**Comment by mysticatea** [comment]
It looks a bug in code path analysis. If `ForInStatement#right` is the first location which can throw a reference error in the outer `try` block, it has generated wrong code path. I need more investigation.
