### ISSUE TITLE
consistent-return and getter-return has a similar option property

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8854]
# consistent-return and getter-return has a similar option property, but naming different.

## consistent-return option:

+ "treatUndefinedAsUnspecified": false (default) always either specify values or return undefined implicitly only.
+ "treatUndefinedAsUnspecified": true always either specify values or return undefined explicitly or implicitly.

## getter-return option:
+ "allowImplicit": false (default) disallows implicitly returning undefined with a return; statement.

it is confusing to users, better to be consistent.

**Comment by not-an-aardvark** [comment]
Good catch. It seems like `getter-return` hasn't made it into a release yet, so it might be safe to rename the option if we can do it before the release on Friday.

**Comment by not-an-aardvark** [comment]
Closing because https://github.com/eslint/eslint/pull/8866 was closed.
