### ISSUE TITLE
cli-engine.js has a low test coverage.

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8860]
![image](https://user-images.githubusercontent.com/13050025/27767879-ce737528-5f37-11e7-8a0b-336e88ee10a1.png)

**Comment by not-an-aardvark** [comment]
Hmm, I'm confused -- it seems to have a high test coverage for me after running `npm test`.

![](https://i.gyazo.com/5d1ef7672a2eceb2e4cfc0cba428a904.png)

**Comment by Aladdin-ADD** [comment]
oh, some tests failed because of timeout in my computer.
![image](https://user-images.githubusercontent.com/13050025/27768021-3192a98c-5f3b-11e7-9a8c-f3e948c08513.png)
