### ISSUE TITLE
padding-line-between-statements: support top-of-file STATEMENT(?)_TYPE 

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#8884]
* **ESLint Version:** 4.1.1
* **Node Version:** 8.1.3
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```js
    'lines-around-directive': ['error', { before: 'never', after: 'always' }],

    'padding-line-between-statements': ['error',
      { blankLine: 'never', prev: '*', next: 'directive' },
      { blankLine: 'always', prev: 'directive', next: '*' },
    ],
```

**What did you do? Please include the actual source code causing the issue.**

```js
<empty line>
'use strict';
console.log(1);
```

**What did you expect to happen?**
Both old (deprecated) rule and new rule warn about the unexpected and the expected empty lines.

**What actually happened? Please include the actual, raw output from ESLint.**
Only old (deprecated) rule warns about the unexpected empty line:

```console
  2:1  error  Unexpected newline before "use strict" directive  lines-around-directive
  2:1  error  Expected newline after "use strict" directive     lines-around-directive
  3:1  error  Expected blank line before this statement         padding-line-between-statements
```

**Comment by platinumazure** [comment]
Oh dear, we really let this one slip through the cracks...

@vsemozhetbyt Please accept our apologies for letting this slip through the cracks.

I'm :+1: for this, but let's see what @eslint/eslint-team thinks.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
