### ISSUE TITLE
comma-dangle: Unexpected fix applied to arrow functions with implicit return

### ISSUE THREAD

**Issue by robertrossmann** [eslint/eslint#8887]
**Tell us about your environment**

* **ESLint Version:** 4.1.1
* **Node Version:** 8.1.3
* **npm Version:** 5.0.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  rules: {
    'comma-dangle': ['warn', {
      functions: "always-multiline",
    }],
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

The following code snippet gets (in my opinion) an invalid auto-fix by the `comma-dangle` rule. The rule's documentation refers to this option only applying to function invocations and declarations, however the `console.log` expression is not an argument to any function nor is it part of any function declaration, therefore a comma **should not** be inserted after it.

```js
fs.readFile('path', data =>
  console.log(data)
)
```

**What did you expect to happen?**

No code changes applied by the auto-fixer.

**What actually happened? Please include the actual, raw output from ESLint.**

A dangling comma is added after `console.log` by the `comma-dangle` auto-fixer.

```js
fs.readFile('path', data =>
  console.log(data),
)
```

**Note:** Re-formatting the above snippet into a single line does not result in the comma being added after `console.log`.

**Comment by platinumazure** [comment]
Can you please include your configuration (at very least for `comma-dangle`)? Thanks!

**Comment by robertrossmann** [comment]
Hi @platinumazure, it's there, you have to expand the `Configuration` section. 👍

**Comment by not-an-aardvark** [comment]
I think this is working as intended -- `data => console.log(data)` is an argument to the `fs.readFile` function call, so a comma is added after it. Since you have the rule's configuration set to `always-multiline`, the comma is only added when the arrow function ends on a different line than the other arguments.

**Comment by robertrossmann** [comment]
Aaaaah of course! I thought the comma belongs to the arrow function's body, or something...

*Works As Advertised™* -> closing. Thanks for all your help!
