### ISSUE TITLE
Setup Code Owners

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#8896]
GitHub just implemented code owners: https://github.com/blog/2392-introducing-code-owners

Seems like if we setup everything in lib/ to be owned by the TSC, then we should be able to effectively prevent accidental merging of core features by non-TSC members. It also helps make it easier for TSC members to filter PRs based on this ownership.

**Comment by platinumazure** [comment]
I assume we could also then make `lib/rules/` mergeable by all team members, to reflect current maintainer guidelines?

**Comment by not-an-aardvark** [comment]
Would assigning lib/ to the TSC also prevent non-TSC members from merging bugfixes to core?

**Comment by nzakas** [comment]
Sorry, I meant assign owners inside of lib/, so lib/rules/ would be everyone, lib/config/ would be TSC, and so on, based on the guidelines we have set out.

**Comment by platinumazure** [comment]
Awesome, works for me. :+1: Thanks for clarifying!

**Comment by not-an-aardvark** [comment]
Is this still something we want to do?

**Comment by nzakas** [comment]
Seems like we are doing ok without this, so closing. We can always revisit later if necessary.
