### ISSUE TITLE
Scheduled release for July 21, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8921]
The scheduled release on Friday, July 21, 2017 is assigned to:

* @ilyavolodin
* @btmills

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by btmills** [comment]
v4.3.0 has been released. As a reminder, please merge only semver-patch changes until we have either done a patch release or determined that one is not necessary.

**Comment by btmills** [comment]
We've determined that a patch release is not necessary. This concludes the v4.3.0 release process, and you may resume merging semver-minor changes!
