### ISSUE TITLE
Suggestion: Prevent common typo mistakes (length, constructor, etc.)

### ISSUE THREAD

**Issue by yvele** [eslint/eslint#8940]
First of all thanks for eslint :thumbsup:

As a non native english developper I lost a huge amount of time fixing the same typos again and again.

I already fixed common **`constructor`** typos using [id-blacklist](http://eslint.org/docs/rules/id-blacklist) rule. It's safe because who would ever use those IDs:

```js
{
  "id-blacklist" : ["error",
    // Prevent "constructor" typos
    "contructor",
    "contrutor",
    "construtor",
    "construcor",
    "constuctor"
  ]
}
```

This one is more tricky. I would like to do the same with **`length`** typos, because I spent so much time spotting `lenght`. Who would ever use `lenght` in any code!

I cannot achieve that using [id-blacklist](http://eslint.org/docs/rules/id-blacklist) because it's only for declaration.

Could we have a basic blacklist for field access? Something I could use to prevent **`length`** typos (because again.. what evil mind in the world would explicitly use `lenght` in any code?!)

This could save me (and my team (and the whole world)) a huge amount of time!

PS: I'm pretty sure there is many other use cases, for example this related issue about `propTypes` typos: https://github.com/yannickcr/eslint-plugin-react/issues/65 (and see also [react/no-typos](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md))

**Comment by not-an-aardvark** [comment]
You can do this with

```yml
rules:
  no-restricted-properties: [error, {property: lenght}]
```

**Comment by yvele** [comment]
@not-an-aardvark oh really? Thank you so much.. Sorry 😭
