### ISSUE TITLE
[object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".

### ISSUE THREAD

**Issue by RealBlazeIt** [eslint/eslint#8948]
**Tell us about your environment**

* **ESLint Version:** 4.2.0
* **Node Version:** 8.1.2
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

<details>
<summary>Configuration</summary>

```js

{
  "env": {
    "node": true,
    "es6": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "rules": {
    "indent": [
      "error",
      2,
      { "SwitchCase": 1 }
    ],
    "linebreak-style": "off",
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ],
    "no-unused-vars": [
      "error",
      { "args": "none" }
    ],
    "eqeqeq": [
      "error", 
      "always"
    ],
    "no-multiple-empty-lines": [
      "error",
      { "max": 1 }
    ],
    "yoda": [
      "error", 
      "never"
    ],
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "one-var-declaration-per-line": [
      "error", 
      "always"
    ],
    "space-before-function-paren": [
      "error",
      { "named": "never" }
    ],
    "multiline-ternary": [
      "error", 
      "never"
    ],
    "array-bracket-spacing": "error",
    "no-var": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-implicit-coercion": "error",
    "no-new-func": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-self-compare": "error",
    "no-useless-return": "error",
    "no-nested-ternary": "error",
    "no-path-concat": "error",
    "no-new-require": "error",
    "no-sync": "error",
    "no-useless-constructor": "error",
    "block-spacing": "error",
    "brace-style": "error",
    "curly": "error",
    "camelcase": "error",
    "comma-dangle": "error",
    "comma-spacing": "error",
    "no-mixed-operators": "error",
    "no-lonely-if": "error",
    "no-array-constructor": "error",
    "no-multi-assign": "error",
    "no-new-object": "error",
    "no-trailing-spaces": "error",
    "no-unneeded-ternary": "error",
    "operator-assignment": "error",
    "space-before-blocks": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "arrow-spacing": "error",
    "key-spacing": "error",
    "switch-colon-spacing": "error",
    "eol-last": "error",
    "no-console": "off"
  }
}

```

</details>

The error `[object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".` was printed out on startup of VS Code. I do not have the `emcaFeatures` property set in my config file, so I do not understand why I am getting this error. Furthermore, I was getting an error regarding not having the `babel-eslint` module, while I wasn't even using the `babel` parser. Installing it fixed this issue, but it created this one.

**Comment by not-an-aardvark** [comment]
I'm guessing you have another config file active which has an `ecmaFeatures` property and specifies `babel-eslint` as a parser. Try looking for config files in parent directories, or in your home directory.

You can run `eslint --debug yourFile.js` from the command line to see which config files are getting loaded (look for lines starting with `eslint:config`).

**Comment by ljharb** [comment]
@RealBlazeIt are you using the airbnb eslint config? Does `npm ls` exit nonzero?

If `npm ls` exits nonzero, nothing will work. In case it applies, the airbnb config requires v3 of the eslint config, for which this error doesn't occur. If you do use the airbnb config, use the install command in the readme, and everything will be correct (and you'll have eslint v3)

**Comment by RealBlazeIt** [comment]
@not-an-aardvrak Whenever I run ESLint via command line, it works perfectly, with none of the errors I get in VS Code. When testing with the `--debug` argument, it showed that it was using my provided eslint config file.

**Comment by RealBlazeIt** [comment]
@ljharb `npm ls` exits with a 0 code.

**Comment by RealBlazeIt** [comment]
@not-an-aardvark Whenever I run ESLint via command line, it works perfectly, with none of the errors I get in VS Code. When testing with the `--debug` argument, it showed that it was using my provided eslint config file.

**Comment by ljharb** [comment]
Any chance VS Code is running a global eslint, instead of the local one? Try `npm uninstall -g eslint`, since you shouldn't ever need a global one.

**Comment by RealBlazeIt** [comment]
@ljharb Already did that a while ago to ensure it was only using the config file I provided.

**Comment by not-an-aardvark** [comment]
Thanks for the info. If the issue occurs in VSCode but not on the command line, it's probably not an issue with ESLint. I would recommend filing an issue on your editor integration's repo instead.
