### ISSUE TITLE
'indent' find wrong error for multiline ternary operator in template curly

### ISSUE THREAD

**Issue by sigorilla** [eslint/eslint#8982]
**Tell us about your environment**

* **ESLint Version:** 4.2.0
* **Node Version:** 6.10.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** none

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    root: true,
    parserOptions: {
        sourceType: 'module'
    },
    rules: {
        indent: ['error', 4, {SwitchCase: 1}]
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
export default function renderHead(options) {
    return `
        <meta name="viewport" content="width=device-width, user-scalable=no,initial-scale=1.0, maximum-scale=1.0"/>

        <meta property="og:type" content="website"/>
        <meta property="og:url" content="${options.meta.ogUrl}"/>
        ${options.meta.ogTitle ? `<meta property="og:title" content="${options.meta.ogTitle}"/>` : ''}
        ${options.meta.ogDescription ?
            `<meta property="og:description" content="${options.meta.ogDescription}"/>` :
            ''
        }
        <meta property="og:image" content="${options.meta.ogImage}"/>
        <meta property="og:image:secure_url" content="${options.meta.ogImage}"/>

        <title>${options.meta.title}</title>
        <meta name="description" content="${options.meta.description}">
    `;
}
```

**What did you expect to happen?**

There is no errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
/projects/render-head.js
   9:1  error  Expected indentation of 8 spaces but found 12  indent
  10:1  error  Expected indentation of 8 spaces but found 12  indent
  11:1  error  Expected indentation of 0 spaces but found 8   indent

✖ 3 problems (3 errors, 0 warnings)
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. However, this is working as intended. The explanation in https://github.com/eslint/eslint/issues/8880#issuecomment-313027996 also applies here.

**Comment by not-an-aardvark** [comment]
As an unrelated note, I would caution against using untagged template literals to format HTML. If any of the values in the literal can be modified by user input, your page will be vulnerable to [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) attacks.

**Comment by sigorilla** [comment]
Oh, your explanation has sense.

Thank your for note about XSS, but we don't render any user input exactly in HTML.

**Comment by not-an-aardvark** [comment]
Closing because this is working as intended.
