### ISSUE TITLE
Scheduled release for August 4th, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8996]
The scheduled release on Friday, August 4th, 2017 is assigned to:

* @kaicataldo
* @gyandeeps 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

Resources:

* [Release guidelines](http://eslint.org/docs/maintainer-guide/releases)

**Comment by not-an-aardvark** [comment]
This release process should also involve a release of Espree, which now supports the `ecmaVersion: 2018` flag and the template literal revision.

**Comment by ctcpip** [comment]
is this happening today?

**Comment by not-an-aardvark** [comment]
Yes.

**Comment by gyandeeps** [comment]
Release has been postponed to Saturday Afternoon (EST), 5th Aug.

**Comment by kaicataldo** [comment]
Espree v3.5.0 and ESLint v4.4.0 have been released. @eslint/eslint-team Friendly reminder to only merge semver-patch PRs until we conclude the release cycle on Monday.

**Comment by kaicataldo** [comment]
ESLint v4.4.1 has been released. This concludes this release cycle. Please feel free to resume merging semver-minor PRs!
