### ISSUE TITLE
Ignore JSX markup between /*eslint-disable*/

### ISSUE THREAD

**Issue by victor-homyakov** [eslint/eslint#900]
React JS uses [JSX](http://facebook.github.io/react/docs/jsx-in-depth.html) for markup, e.g.

``` js
    return React.createClass({
        // code
        render: function() {
            /*jshint ignore:start*/
            /*eslint-disable*/
            return <div>
                <input value={this.props.value} onChange={this.props.onChange} />
            </div>;
            /*eslint-enable*/
            /*jshint ignore:end*/
        }
    });
```

I want to lint all the code except for JSX markup in `render()`. In order to achieve this I add comments to disable JSHint and ESLint checks.

But ESLint still tries to parse text between `/*eslint-disable*/` and `/*eslint-enable*/` and issues `error  Unexpected token <`.

**Comment by L5eoneill** [comment]
I know this is really old, but the render should return (<div>...</div>) with parens around it. Our eslint has no problem with the jsx using this syntax. (Or maybe something else changed since 2014!)

**Comment by platinumazure** [comment]
@L5eoneill We support JSX parsing in espree now, that's what changed. :smile:
