### ISSUE TITLE
Methods are added to Linter in a suboptimal way

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9000]
In `lib/linter.js`, there are a few methods [here](https://github.com/eslint/eslint/blob/3d020b9083de105ce8adc67bc3efae0aac01e03f/lib/linter.js#L1263-L1298) that need to be copied onto `Linter.prototype`. The current implementation works, but it's not ideal, for a few reasons:

* It assumes that all of the copied methods will have no more than 5 arguments. This is true at the moment, but it could result in subtle bugs in the future if a new method is added and someone forgets about the 5-argument limit.
* The resulting property on `Linter.prototype` is enumerable. This isn't really a problem, but it would be better if it was consistent with other class methods, which are non-enumerable.

The pattern used [here](https://github.com/eslint/eslint/blob/9ba6982b48fb0bc482dc0e5024a2277c7f23541b/lib/rule-context.js#L229-L239) addresses both of these issues for the `RuleContext` class. A similar pattern should probably be used to copy the `Linter` methods.

**Comment by seandenison26** [comment]
Hey, I am new to open source and looking for a first PR. Mind if I try?

**Comment by not-an-aardvark** [comment]
Sure, feel free!

**Comment by seandenison26** [comment]
Hey, just wanted to clarify a few things with the `Object.defineProperty()' application: 

Should the `configurable` and `writable` properties be set to `true` as they are in the `RuleContext` pattern example?

If I am understanding the pattern correctly I should being replacing `this._linter` with `this.sourceCode` as the value property, yes?

**Comment by not-an-aardvark** [comment]
> Should the `configurable` and `writable` properties be set to `true` as they are in the `RuleContext` pattern example?

Yes, I think so. Basically, the goal is to make the properties be the same as other methods that were declared on the class.

```js
Object.getOwnPropertyDescriptor(class Foo { someMethod() {} }.prototype, 'someMethod')

// => {writable: true, enumerable: false, configurable: true, value: [Function]}
```

> If I am understanding the pattern correctly I should being replacing `this._linter` with `this.sourceCode` as the value property, yes?

Yes, that sounds right.
