### ISSUE TITLE
Error: Unknown node type AssignmentPattern

### ISSUE THREAD

**Issue by Noxxys** [eslint/eslint#9016]
**Tell us about your environment**

* **ESLint Version:** 4.3.0
* **Node Version:** 8.1.1
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  env: {
    es6: true,
    node: true,
  },
  extends: 'eslint:recommended',
  rules: {
    indent: ['error', 2],
    'linebreak-style': ['error', 'windows'],
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'no-console': 'off',
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

Running eslint on a specific file of my Nodejs/Express project throws an exception (see below).
This only happens with the app.js file, and not the other files in my project. Here's the source code of app.js:

```js
/**
 * Created by Bruno Bertomeu on 2017-06-12.
 * http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Athena.html
 */
'use strict';
const port = 8000;
const contextPath = '/athena-query-backend';

const express = require('express');
const app = express();
const router = express.Router();
const bodyParser = require('body-parser');
const athenaClient = require('./athena-client');

function errorHandler(err, req, res, next, statusCode = 500) {
  console.log(err);

  // some errors not generated by me might be inside an error key
  let error = err.error ? err.error : err;

  // for some reason Express doesn't want to send my error text without toString()
  res.status(statusCode).send({ err: error.toString() });
}

app.use(contextPath, router);
app.use(errorHandler);

router.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});

router.use(bodyParser.json());

// the normal endpoint used by the frontend
router.route('/query')
  .post((req, res) => {
    if (!req.body || typeof req.body !== 'object') {
      console.log('Request contains an invalid body: ', req.body);
      errorHandler({
        error: "The request's body should be a json object (empty, or containing an array of filters)"
      }, req, res, null, 400);
    } else {
      athenaClient.runQuery(req.body)
        .then(results => {
          return res.send(results);
        })
        .catch(error => {
          errorHandler(error, req, res);
        })
    }
  });

// a debug endpoint to see the raw output from Athena. Edit the SQL query in runQueryDebug()
router.route('/debug')
  .post((req, res) => {
    if (!req.body || typeof req.body !== 'object') {
      console.log('Request contains an invalid body: ', req.body);
      errorHandler({
        error: "The request's body should be a json object (empty, or containing an array of filters)"
      }, req, res, null, 400);
    } else {
      athenaClient.runQueryDebug(req.body)
        .then(results => {
          console.log('done');
          return res.send(results);
        })
        .catch(error => {
          errorHandler(error, req, res);
        })
    }
  });

router.route('/health')
  .get((req, res) => {
    res.send('ok');
  });

app.listen(port);
console.log(`Server started on http://localhost:${port}${contextPath}`);
```

**What did you expect to happen?**
ESlint should not throw an exception

**What actually happened? Please include the actual, raw output from ESLint.**
The following exception is thrown every time:

Error: Unknown node type AssignmentPattern.
    at Traverser.traverse (C:\git-root\athena-query-backend\node_modules\estraverse\estraverse.js:517:31)
    at Traverser.traverse (C:\git-root\athena-query-backend\node_modules\eslint\lib\util\traverser.js:31:22)
    at Linter.verify (C:\git-root\athena-query-backend\node_modules\eslint\lib\linter.js:919:28)
    at processText (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli-engine.js:203:31)
    at processFile (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli-engine.js:245:18)
    at executeOnFile (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli-engine.js:585:25)
    at fileList.forEach.fileInfo (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli-engine.js:622:13)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli-engine.js:621:18)
    at Object.execute (C:\git-root\athena-query-backend\node_modules\eslint\lib\cli.js:181:107)

**Comment by not-an-aardvark** [comment]
Thanks for the report. However, I can't seem to reproduce this issue.

Does it still occur if you reinstall eslint? I recall some earlier versions of npm had bugs where dependences might have been getting installed incorrectly.

**Comment by Noxxys** [comment]
Thanks. No more problems after doing the following:
- uninstall nvm (Node Version Manager for Windows)
- install node 8.2.1
- remove node_modules in my app
- npm install
Cheers

**Comment by not-an-aardvark** [comment]
Ok, I'll close this. It is a bit strange that the issue occurred, but I'm pretty sure it was an issue with the package manager and not with ESLint.
