### ISSUE TITLE
global-require ignore for some filetypes

### ISSUE THREAD

**Issue by rogerkerse** [eslint/eslint#9028]
Is there a way to ignore global-require error only on .png & .jpg requires in react native?

React Native's practice is something like this and linter isn't very happy about this, but of course I wouldn't want to disable it for other cases.
`
<Image
    source={require('./img/favicon.png')}
/>
`

**Comment by not-an-aardvark** [comment]
No, it's not possible to do this with the the `global-require` rule. However, you could create a custom rule that ignores particular file extensions.

**Comment by not-an-aardvark** [comment]
Closing because the question has been answered.
