### ISSUE TITLE
add eslint version to error output

### ISSUE THREAD

**Issue by artin-phares** [eslint/eslint#9037]
it would be useful to have eslint version in error output  

eg. #9024 - when eslint cannot parse configuration, output should clearly state exactly with what version of eslint we dealing with. it should help to realize you use wrong version of eslint.

eg. when users file new bugs and copy error output, they can forget to include eslint version into bug description. with version injected into output it is not a problem.

**Comment by platinumazure** [comment]
I'm absolutely :+1: to this- it could aid users in detecting if they are accidentally using global instead of local ESLint (or vice versa) and help ensure accurate bug reporting.

**Comment by platinumazure** [comment]
I'll champion this.

@eslint/eslint-tsc Are CLI issues like rule issues where 3 :+1:'s and a champion allow for accepting the issue? Or are these more like core issues where we need to have TSC review?

**Comment by btmills** [comment]
I had to check the [issue guide](https://eslint.org/docs/maintainer-guide/issues.html#evaluating-core-features-and-enhancements-tsc-members-only), but it mentions this case:

> changes to the core (including CLI changes) that would result in a minor or major version release must be approved by the TSC

Should be a pretty quick approval at the next meeting - it already has four :+1:s from TSC members!

**Comment by platinumazure** [comment]
Then I don't need to champion this. :smile:

**Comment by not-an-aardvark** [comment]
The TSC accepted this proposal yesterday.
