### ISSUE TITLE
Discussion: enable object-curly-newline on eslint codebase.

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9042]
I found we have been inconsistent on this. what about enable this rule? and options to set?

**Comment by not-an-aardvark** [comment]
I have no strong opinion on this either way. If we can find a config that doesn't hurt readability, then I'm :+1: for enabling it. (If not, maybe we should consider whether we can enhance the rule.)

**Comment by Aladdin-ADD** [comment]
here is some statistics:

object-curly-newline: ["error", "never"]
![image](https://user-images.githubusercontent.com/13050025/28834900-3b8d15ba-7716-11e7-9421-1c05c797b51d.png)

object-curly-newline: ["error", "always"]
![image](https://user-images.githubusercontent.com/13050025/28835004-8d51b662-7716-11e7-810d-9377e4d59671.png)

object-curly-newline: ["error", {"multiline": true}]
![image](https://user-images.githubusercontent.com/13050025/28835258-5ac1760a-7717-11e7-836d-21c5b93a3bd6.png)

object-curly-newline: ["error", {"consistent": true}]
![image](https://user-images.githubusercontent.com/13050025/28835477-02374c3e-7718-11e7-83b8-1ba9f34a34aa.png)
