### ISSUE TITLE
sort-keys documentation is unclear about what "natural ordering" means

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9043]
The [`sort-keys`](http://eslint.org/docs/rules/sort-keys#options) rule has a `natural` option, which indicates that keys should be ordered "naturally". This is implemented using the [natural-compare-lite](https://github.com/litejs/natural-compare-lite) library, and the goal is apparently to handle numeric keys as a human would expect (e.g. `10` should come after `2` in the sort order, even though it comes first alphabetically).

The documentation of `sort-keys` doesn't describe what "natural order" means, which is confusing. We should update the documentation to at least give a general description of how the `natural` option changes the behavior.

**Comment by karansharma27** [comment]
Sent a pull request for the same.
