### ISSUE TITLE
ESLint indent rule is indecisive in jsx

### ISSUE THREAD

**Issue by markogresak** [eslint/eslint#9047]
**Tell us about your environment**

* **ESLint Version:** 4.3.0
* **Node Version:** 8.1.2
* **npm Version:** 5.2.0 (w/ yarn 0.27.5)

**What parser (default, Babel-ESLint, etc.) are you using?**

`babel-eslint`: 7.2.3

**Please show your full configuration:**

- `eslint-config-airbnb`: 15.1.0
- `eslint-plugin-import`: 2.7.0
- `eslint-plugin-jsx-a11y`: 5.1.1
- `eslint-plugin-react`: 7.0.1

<details>
<summary>Configuration</summary>

```js
extends:
  eslint-config-airbnb

parser:
  babel-eslint

settings:
  ecmascript: 6

parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
    destructuring: true
    classes: true
    forOf: true
    blockBindings: true
    arrowFunctions: true

env:
  browser: true

globals:
  MathJax: false

rules:
  no-shadow: 0
  max-len: 0
  arrow-body-style: 0
  arrow-parens: 0
  class-methods-use-this: 0
  func-names: 0
  indent: 2
  new-cap: 0
  no-plusplus: 0
  no-return-assign: 0
  quote-props: 0
  template-curly-spacing: [2, "never"]
  object-curly-spacing: [2, "never"]
  comma-dangle: ["error", {
    "arrays": "always-multiline",
    "objects": "always-multiline",
    "imports": "always-multiline",
    "exports": "always-multiline",
    "functions": "never"
  }]
  jsx-quotes: [2, "prefer-double"]
  jsx-a11y/no-static-element-interactions: 0
  react/forbid-prop-types: 0
  react/jsx-curly-spacing: [2, "never"]
  react/jsx-filename-extension: 0
  react/jsx-boolean-value: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 2
  import/prefer-default-export: 0
  react/sort-comp: 0
  jsx-a11y/media-has-caption: 0
  jsx-a11y/iframe-has-title: 0
```

</details>

**What did you do? Please include the actual source code causing the issue.**

Trying to return a component with a ternary expression, example:

```js
render() {
    const {currentRole} = this.props;

    return (
      currentRole &&
        !canUserInteract(currentRole, minimumRoleForUsers) ?
          <Redirect to={routeCodes.COURSE_LIST} /> :
          <div className="users-list mt-4">
            {/* Redacted to keep the code shorter */}
          </div>
    );
  }
```

**What did you expect to happen?**

I expect the linter to decide which indentation level is correct.

**What actually happened? Please include the actual, raw output from ESLint.**

I get a loop of indentation errors, first saying that it's expecting an indentation of 10 spaces but got 8 and after using the `--fix` option, it's expecting 8 spaces but got 10:

![linter-err](https://user-images.githubusercontent.com/6675751/28753162-149e404c-7530-11e7-8474-c695fe1a2b29.gif)

**Comment by not-an-aardvark** [comment]
Thanks for the report. It looks like half of the errors are coming from the `indent` rule, and half of the errors are coming from the `react/jsx-indent` rule. The "indecision" is occurring because `indent` and `react/jsx-indent` disagree about the correct indentation for your code.

Since `currentRole && !canUserInteract(currentRole, minimumRoleForUsers)` is the predicate of the ternary expression, the two following clauses should be offset by two spaces from `currentRole`, so I think the `indent` rule is behaving as intended here.

I think the `react/jsx-indent` rule is actually redundant with the `indent` rule now, because in ESLint 4 the `indent` rule also checks JSX. So a quick workaround would be to disable the `react/jsx-indent` rule.

**Comment by markogresak** [comment]
@not-an-aardvark I haven't even noticed that there are two competing rules.
Adding a rule `react/jsx-indent: "off"` fixed this behavior. 
I'm guessing the rule comes from `eslint-config-airbnb` and the config itself is not fully fixed for eslint v4.
