### ISSUE TITLE
Implement --quiet to only output errors and not warnings

### ISSUE THREAD

**Issue by mgol** [eslint/eslint#905]
Contrary to jsHint, when ESlint lints an ignored files, it doesn't exit silently but warns. It might seem a good idea at first sight but when you pass files to ESLint via a glob pattern like `app/**/*.js` and put sth like `app/vendor/**` in `.eslintignore`, then you'll get flooded with a massive amount of warnings, even though everything what happens is expected.

**Comment by yaycmyk** [comment]
Can this also be added as an .eslintrc option @nzakas?

**Comment by massimocode** [comment]
+1 This would be really helpful as an .eslintrc option

**Comment by ilyavolodin** [comment]
This can't be config option, because configs cascade and cascading is processed in the much higher level than output.
