### ISSUE TITLE
proposal: add `--fix` to `one-var`

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9072]
```js
// one-var: ["error", "never"]
const foo = 0,
  bar = 1;
```
can be fixed to:
```js
const foo = 0;
const bar = 1;
```

**Comment by not-an-aardvark** [comment]
:+1: I made a WIP branch for this awhile ago [here](https://github.com/not-an-aardvark/eslint/commit/fc14d56ea257aa2a920d0c67894ea16eecbad7ea), but never ended up finishing. I think it only fixed the `never` case, and not the `always` case.

**Comment by the-spyke** [comment]
I need this so much... @not-an-aardvark Are you going to finish your WIP or should I try by myself?

**Comment by not-an-aardvark** [comment]
It's not a high priority for me right now, so feel free to work on it if you'd like.

**Comment by the-spyke** [comment]
Okay, thanks.

**Comment by the-spyke** [comment]
Sorry, but I gave up on this.

**Comment by not-an-aardvark** [comment]
No worries, thanks for working on it!

**Comment by j-f1** [comment]
I’m taking a look at this, although I’m only going to attempt fixes for cases where the two `var` declarations are next to each other (`var a = 2; var b = 3`, not `var a = 2; for (var b in foo) {}`)
