### ISSUE TITLE
New rule: circular-dependency

### ISSUE THREAD

**Issue by RealBlazeIt** [eslint/eslint#9096]
**Please describe what the rule should do:**
This rule will detect any circular dependencies between files and error/warn the user about it. Circular dependencies will lead to empty objects being returned from the `require()` function, which is often not intended.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Enforces code style
[X] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

Book.js
```js
var Author = require('./Author.js');

function Book(name) {
  this.name = name;
  this.author = new Author('John');
}

module.exports = Book;
```

Author.js
```js
var Book = require('./Book.js');

function Author(name) {
  this.name = name;
  this.books = [new Book('Why Circular Dependencies Are Bad')];
}

module.exports = Author;
```

In this example, the `Author` export in the `Book.js` file would return an empty object, due to the circular dependency, which in almost all cases is never the intended result.

**Why should this rule be included in ESLint (instead of a plugin)?**
This is a very basic concept that should be a recommended rule simply because circular dependencies are almost never intentional, and can lead to multiple issues if they are not fixed from the start.

**Comment by platinumazure** [comment]
I'm :-1: to including in core, because ESLint core only looks at one file at a time and we would need to make some serious changes (with performance implications) to support a rule like this.

I think this might potentially be a fit for eslint-plugin-import, if they cover CommonJS require() calls (I think they do). They could also implement this for ES2015 modules.

**Comment by not-an-aardvark** [comment]
It looks like there are three team members opposed to including this in core, so I'm going to close it. Thanks for the proposal regardless!
