### ISSUE TITLE
.eslintignore: can't exclude files from node_modules once ignored

### ISSUE THREAD

**Issue by Zephir77167** [eslint/eslint#9097]
**Tell us about your environment**

* **ESLint Version:** 4.4.1
* **Node Version:** 8.2.1
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** 

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
  extends: 'airbnb',
  parser: 'babel-eslint',
  plugins: [
    'react',
    'import',
  ],
  rules: {
    'max-len': 'off',
    'react/jsx-filename-extension': ['error', { extensions: ['.js', '.jsx'] }],
    'import/first': ['error', { 'absolute-first': false }],
    'import/no-extraneous-dependencies': ['error', { devDependencies: true, optionalDependencies: false, peerDependencies: true }],
    curly: ['error', 'all'],
  },
  env: {
    browser: true,
    jest: true,
  },
  settings: {
    'import/cache:': {
      lifetime: 2,
    },
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, 'webpack.config.dev.js'),
      },
    },
  },
};
```

```js
!.*
node_modules/
coverage/
junit/
dist/
mobiles/
!node_modules/some-package/

```

</details>

**What did you do? Please include the actual source code causing the issue.**

Introduce linting error in node_modules/some-package/test.js

```js
const test = 1 // missing semi (also unused const)
```

**What did you expect to happen?**

A linting error. When I comment `node_modules` in `.eslintignore` it works, but also lints `node_modules`.

**What actually happened? Please include the actual, raw output from ESLint.**

```js
eslint .
can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
Done in 47.24s.
```
Thanks in advance!

**Comment by not-an-aardvark** [comment]
Thanks for the report. I'm a bit confused about what happened -- it would be helpful if you could clarify some things:

> When I comment `node_modules` in `.eslintignore` it works, but also lints `node_modules`

* Could you be more specific about how you changed your `.eslintignore` file? What did it look like before, and how did you modify it?
* What do you mean by "it works"? Do you mean a linting error got reported?
* I'm interpreting your phrasing of "but also lints `node_modules`" to mean that you didn't want `node_modules` to be linted. Could you clarify what you were trying to do? Did you want to only lint some files in `node_modules`, but not others?

**Comment by Zephir77167** [comment]
Hi, thanks for the quick response time, and sorry for the misunderstanding. I will try to clarify things:

Before (no lint error in `test.js`):
```js
!.*
node_modules/
coverage/
junit/
dist/
mobiles/
!node_modules/some-package/
```

After (lint error in `test.js`):
```js
!.*
#node_modules/
coverage/
junit/
dist/
mobiles/
!node_modules/some-package/
```

Problem is, I would like for `node_modules/some-package/` content to be linted, but for all other folders in `node_modules` not to. And when I run `eslint .` with the second version, I get linting errors from dependencies I have installed.

I would expect `node_modules/some-package/` to be linted with the first version. For the record, I have a `.stylelintignore` with the same content as `.eslintignore`, and `node_modules/some-package/test.scss` gets linted well

**Comment by Zephir77167** [comment]
I also tested `node_modules/!(some-package)/` which should work according to http://www.globtester.com/, but with the same results as the second example.

**Comment by platinumazure** [comment]
Does `!node_modules/some-package/**` work?

**Comment by Zephir77167** [comment]
I tried, and also tried `!node_modules/some-package/test.js`, same result.

**Comment by kaelzhang** [comment]
Have a try with this?

```
!.*
node_modules/*
coverage/
junit/
dist/
mobiles/
!node_modules/some-package/
```

**Comment by Zephir77167** [comment]
This one works, and I guess it also makes more sense when I think about it. Thanks a lot!

**Comment by not-an-aardvark** [comment]
Thanks @kaelzhang. Out of interest, why does `node_modules/*` work here when `node_modules/` doesn't work?

**Comment by Zephir77167** [comment]
Sorry, I forgot to perform the whole test suite, @kaelzhang doesn't exclude other node_modules when running `eslint .` (so same result as the second example from my post). Reopening

**Comment by Zephir77167** [comment]
Ok figured it out. It was a mix of @kaelzhang 's solution, and the fact that I have nested node_modules in my project.

```
!.*
coverage/
junit/
dist/
mobiles/
**/node_modules/*
!**/node_modules/some-package/
```

did the trick. Thanks to all!

**Comment by kaelzhang** [comment]
According to the .gitignore rules

> It is not possible to re-include a file if a parent directory of that file is excluded.

`node_modules/*` only ignores the things inside the directory.

While `node_modules/` ignores the directory and everything inside it, then `node_modules/some-packages` could not be re-included because its parent dir `node_modules/` is ignored.
