### ISSUE TITLE
Query: Can we have a rule which basically enforces that throw at a function is caught in same stack?

### ISSUE THREAD

**Issue by raghav135** [eslint/eslint#9113]
I could not find any existing feature of eslint, just wondering if it is possible to implement this requirement in existing eslint.

All "throw"s should be caught in the same stack within the project, eslint error should be given if throw is on callback method (async method).

Any ideas?

**Comment by not-an-aardvark** [comment]
I don't understand what you mean by the "same stack". Could you provide a few examples of code that you would want the rule to warn?

**Comment by raghav135** [comment]
For example: 
1. Throw from same call stack:
In this example, the throw in f1 function is caught in f3->f2->f1 stack, but not caught in f4->f2->f1 stack, hence eslint error should be thrown for that stack.

function f1(something) {
  if (something > 10) {
    return something*2;
  else
    throw new Error("some error");
}
function f2(something) {
  return f1(something);
}
function f3(data) {
  var ret;
  try {
    ret = f2(data);
  } catch (ex) {
    ret = ex;
  }
  return ret;
}
function f4(data) {
  return f2(data);
}

2. Throw from Async stack (Example from https://nodejs.org/api/errors.html):

// THIS WILL NOT WORK:
const fs = require('fs');

try {
  fs.readFile('/some/file/that/does-not-exist', (err, data) => {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}

The above throw cannot be caught at all , and even if it is caught at top level, the context is lost, making the "api" call hang indefinitely, and timeout.

**Comment by not-an-aardvark** [comment]
Unfortunately, it's not possible in general to tell where a function is being called from using static analysis, because objects can be modified and created at runtime. Additionally, I'm not sure validating that all thrown errors are caught is a good idea, because some errors are intentionally designed to halt a process.

**Comment by platinumazure** [comment]
I don't think this is a good fit for ESLint core due to the concerns @not-an-aardvark has raised.

If we don't accept this for core, please do feel free to create or augment a plugin with this functionality, if you would find it useful.

**Comment by raghav135** [comment]
Thanks @not-an-aardvark and @platinumazure for your time.

**Comment by not-an-aardvark** [comment]
Closing because there seems to be consensus that this isn't a good fit for ESLint core.
