### ISSUE TITLE
Links to sign the CLA are broken/misleading

### ISSUE THREAD

**Issue by Standard8** [eslint/eslint#9133]
I was preparing to submit a PR and trying to follow the documentation. I came across this page first:

https://eslint.org/docs/developer-guide/contributing/

which said I should sign the CLA, and linking to https://contribute.jquery.org/cla - that was confusing as it was saying I should enter my details but didn't tell me where.

It should either link to https://cla.js.foundation/eslint/eslint, or be reworded to say that you'll get a link to sign it when you submit the PR.

**Comment by platinumazure** [comment]
Yowzer, I thought we had fixed all of those. Thank you for the issue! I think we'll just mention that a link will come up, because I've seen issues when people just go straight to the CLA page without having first come from a pull request.

**Comment by kaicataldo** [comment]
@Standard8 Would you like to make a PR? We'd love the help!

**Comment by i-ron-y** [comment]
Likewise, the "Contributing Code" section in [eslint/CONTRIBUTING.md](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md) is similarly misleading.

Anyone mind if I take on this issue?

**Comment by kaicataldo** [comment]
@i-ron-y Go for it! Feel free to ping back here or to stop by the [ESLint Gitter](https://gitter.im/eslint/eslint) with any questions you might have. Thanks for taking this on!

**Comment by i-ron-y** [comment]
Hmm... as the [Pull Request Guidelines](https://eslint.org/docs/developer-guide/contributing/pull-requests) page links to https://cla.js.foundation/eslint/eslint, to keep it all consistent, I decided to have all mentions of the CLA link to https://cla.js.foundation/eslint/eslint...

But I'm just as happy to revise all three pages to omit said link and instead inform the potential contributor that a link to sign the CLA will appear when they submit a pull request, if that's the preferred option.

**Comment by Standard8** [comment]
I think you need to give a people a link to the CLA before they start submitting, in case they disagree to it for some reason. The current link just didn't work with the text - it said sign here, but then there was nothing to sign. The PR bot that checks it, is then just a backup in case they didn't read everything.

**Comment by ilyavolodin** [comment]
This issue has been fixed with PR #9232 closing.
