### ISSUE TITLE
Update: Add "consistent" option to array-bracket-newline

### ISSUE THREAD

**Issue by EthanRutherford** [eslint/eslint#9136]
`object-curly-newline` (https://eslint.org/docs/rules/object-curly-newline)
and the soon to be merged `function-paren-newline` (https://github.com/eslint/eslint/pull/8102#issuecomment-323196147)
both support the "consistent" option, allowing users to either use a newline on both or neither end.

`array-bracket-newline` ought to have a similar option, as it is a similar rule.

**Comment by kaicataldo** [comment]
Just to be clear, did you mean the "soon to be merged `function-paren-newline`" rule?

**Comment by EthanRutherford** [comment]
Yep, I'll correct that typo.

**Comment by platinumazure** [comment]
@eslint/eslint-team This needs a champion and one more :+1: to be accepted, any takers?

**Comment by EthanRutherford** [comment]
Still need a champion.

**Comment by platinumazure** [comment]
I'll champion, but then we need one more :+1:.

@eslint/eslint-team This is a pretty straightforward enhancement request, should be a shoe-in. Anyone else want to support this?

**Comment by btmills** [comment]
Just added my :+1:. This is now accepted!

**Comment by EthanRutherford** [comment]
https://github.com/eslint/eslint/pull/9206
