### ISSUE TITLE
Cannot find module 'eslint-plugin-react' with eslint --init

### ISSUE THREAD

**Issue by manastunga787** [eslint/eslint#9167]
* **ESLint Version: 4.5.0**
* **Node Version: 6.11.2**
* **npm Version:3.10.10**
* **operating system:windows 10 pro**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js



```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
i installed eslint globally by the command npm install eslint -g
then i run the  comand eslint --init

How do you like to configure ESLint?
  >> Inspect your javascript file(s)
How would you like to configure ESLint?
 >> ./
 What format do you want your config file to be in?
 >> javascript
Are you using ECMAScript 6 features?
 >> y
Are you using ES6 modules?
 >> y
 Where will your code run?
>> Node
 Do you use CommonJS?
>> y
 Do you use JSX?
>> y
 Do you use React?
>> y

Installing eslint-plugin-react@latest
rocket@0.0.1 D:\projects\rocket
`-- eslint-plugin-react@7.3.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\react-native\node_modules\jest-haste-map\n
ode_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})


Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Plugins.load (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\config\plugins.js:133:29)
    at Array.forEach (native)
    at Plugins.loadAll (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\config\plugins.js:173:21)
    at processText (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:165:30)
    at processFile (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:245:18)
    at executeOnFile (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:585:25)
    at fileList.forEach.fileInfo (C:\Users\manas\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:622:13)
    at Array.forEach (native)











```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by platinumazure** [comment]
Hmm. It looks to me like we might be installing configs/plugins locally in `eslint --init` even when running ESLint globally.

Seems to me we should at least have a question about whether to install locally or globally and then go from there.

Wondering if we already have an issue for this, though...

**Comment by not-an-aardvark** [comment]
I thought I remembered that we decided to always install locally, and print a message to use the local installation from now on. However, I might be remembering incorrectly.

**Comment by kaicataldo** [comment]
`eslint --init` only supports local installations. The intent is to create a config per project rather than a reusable global config/setup.

It's not entirely clear to me what the actual issue is - @manastunga787 Does the following happen during `init`, or did you run another command when you got this error?

`Failed to load plugin react: Cannot find module 'eslint-plugin-react'`

**Comment by manastunga787** [comment]
i installed eslint globally by the command npm install eslint -g

then i run the  comand `eslint --init` (this command i run inside my react project for local installation )

but getting the above mentioned error

**Comment by iegik** [comment]
After install eslint locally (`npm i eslint` installs ESLint v4.18.2), I want to view current configuration from console.

Here is mu config:
```
{
    "env": {
        "browser": true,
        "amd": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "indent": [
            "error",
            4,
            {"SwitchCase": 1}
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

Try to print config:
```
>  $ node_modules/.bin/eslint --print-config .eslintrc.json

Oops! Something went wrong! :(

ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Here is any of ESLint plugin dependencies
```
> $ npm show eslint
...
devDependencies: {
...
     'eslint-plugin-eslint-plugin': '^1.2.0',
     'eslint-plugin-node': '^5.1.0',
     'eslint-plugin-rulesdir': '^0.1.0',
```

Why eslint requires eslint-plugin-react ? Why it si not shown in devDependencies?
Is it real dependency or something really goes wrong?

**Comment by kaicataldo** [comment]
@iegik Glad you figured it out!

**Comment by kaicataldo** [comment]
@manastunga787 Is this still an issue for you? How are you actually running eslint? It's still not clear to me when you're seeing this error.

**Comment by manastunga787** [comment]
I am using eslint v4.5.0 and this is no more a problem. This works fine
