### ISSUE TITLE
[Feature Request] Extend rule from Git repository URL

### ISSUE THREAD

**Issue by mpyw** [eslint/eslint#9170]
I'm using GitHub Enterprise. I don't want to publish any npm packages, but want to share eslint configuration file.

I need new feature like this:

```json
{
    "extends": "git@git.example.com:myrepo/eslint-config-myrule.git"
}
```

Is it implementable?

**Comment by not-an-aardvark** [comment]
ESLint doesn't fetch any shareable configurations over the network -- it will just use whatever it finds in `node_modules/eslint-config-myrule`. However, `npm` supports installing packages from `git` URLs, so I think you could do something like this:

`package.json`:

```json
{
    "devDependencies": {
        "eslint-config-myrule": "git@git.example.com:myrepo/eslint-config-myrule.git"
    }
}
```

`.eslintrc.json`:

```json
{
    "extends": "myrule"
}
```

**Comment by mpyw** [comment]
Thank you!
