### ISSUE TITLE
Improve performance benchmark

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9184]
Currently, we use the `npm run perf` script to benchmark to measure ESLint's end-to-end performance. The script does the following:

* [Clones ESLint v1.10.3](https://github.com/eslint/eslint/blob/2d900306da5e095ba3ae20453d3f858df858f681/Makefile.js#L1013) into the user's temp directory, as a static corpus
* [Creates a config that enables all rules in the current ESLint version](https://github.com/eslint/eslint/blob/2d900306da5e095ba3ae20453d3f858df858f681/Makefile.js#L1022-L1037)
* Lints a single file ([JSHint 2.1.8](https://github.com/eslint/eslint/blob/2d900306da5e095ba3ae20453d3f858df858f681/tests/performance/jshint.js), ~300KB) 5 times with all rules enabled, and outputs the end-to-end times for each run as well as the median time.
* Lints a set of many files (the `lib/` and `tests/lib/` directories of ESLint v1.10.3) 5 times with all rules enabled, and outputs the end-to-end times for each run as well as the median time.

The script is good for measuring the performance effect of core changes. However, I've noticed it has a few disadvantages:

1. Since all rules are enabled with the default options, ESLint reports a very large number of errors in the performance test (39871 errors for the single-file benchmark, and 90575 errors for the multi-file benchmark). It seems like it would be very uncommon for linting runs to report this many errors in practice. I would estimate that on average, ESLint reports close to zero errors per file when linting an entire project in CI, or less than 10 errors per file when using an editor integration.

    This is a problem because it means we're not optimizing for the common case. If we could make a change such that we improve performance in the case where there are no errors, at the cost of slightly decreasing performance in the case where there are a lot of errors, I think it would be a net win, because most linting runs don't report any errors. However, it would make the `npm run perf` script slower, which might mislead us into thinking that the change is a bad idea.

    I think the solution to this would be to have a script (possibly as a separate benchmark) that lints a large project with that project's config, so that no errors are reported.

1. Since the benchmark enables all rules, it naturally takes longer to run as we add more core rules. This makes it difficult to measure long-term performance trends over time. For example, the performance script runs significantly longer for ESLint v4.5.0 than for ESLint v3.19.0, but it's unclear how much of that is actually caused by performance regressions, and how much is caused by the fact that the benchmark is now running 9 more rules.

    I don't consider this a big problem, since the performance script is most useful when measuring the effect of a single change. However, it might be good to have a way to make the script consistent over time.

**Comment by nzakas** [comment]
@not-an-aardvark are you still working on this? It looks like one PR related to this has already been merged.

**Comment by not-an-aardvark** [comment]
I'm not actively working on this at the moment -- I'd be fine with closing this if no one else wants to pick it up, or we could add the "help wanted" label for a little while to see if anyone else contributes.

By "one PR related to this" I assuming you're referring to https://github.com/eslint/eslint/pull/9221 -- just to make sure there's no confusion, I noted the state of this issue https://github.com/eslint/eslint/pull/9221 (in that it inhibited collecting accurate performance results for that PR), but I didn't attempt to address this issue in that PR.

**Comment by nzakas** [comment]
This has been open for over a year without any other movement, so I'm going to close it. We can always revisit in the future if we feel there's a need.
