### ISSUE TITLE
wrong "indent" rule behaviour with some arrays and jsdoc comments

### ISSUE THREAD

**Issue by noelmace** [eslint/eslint#9185]
**Tell us about your environment**

* **ESLint Version:** 4.5.0
* **Node Version:**  6.11.2
* **npm Version:** 3.10.10 - using yarn 0.27.5

**What parser (default, Babel-ESLint, etc.) are you using?** typescript-eslint-parser (reproduced with versions from 3.0.0 to 7.0.0)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "parser": "typescript-eslint-parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true
    }
  },
  "env": {
    "browser": true,
    "es6": true
  },
  "rules": {
    "no-extra-boolean-cast": "error",
    "no-extra-semi": "error",
    "no-regex-spaces": "error",
    "curly": "error",
    "no-multi-spaces": [
      "error",
      {
        "exceptions": {
          "Property": true,
          "VariableDeclarator": true
        }
      }
    ],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "comma-style": ["error", "last"],
    "eol-last": ["error", "always"],
    "func-call-spacing": ["error", "never"],
    "indent": ["error", 2, { "SwitchCase": 1 }],
    "no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 0 }],
    "no-trailing-spaces": "error",
    "no-whitespace-before-property": "error",
    "quotes": ["error", "single", { "avoidEscape": true }],
    "semi-spacing": ["error", { "before": false, "after": true }],
    "semi": ["error", "always"],
    "spaced-comment": ["error", "always"],
    "no-var": ["error"],
    "prefer-const": ["error"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
const directives = [
  MyDirective,
];

@NgModule({
  imports: [
    CommonModule, // Expected indentation of 2 spaces but found 4  indent
  ],
  declarations: directives,
  exports: directives
}) // Expected indentation of 2 spaces but found 0  indent
export class MyModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MyModule,
      providers: [
        MyService,
      ]
    };
  }
}
```
```js
export interface SomeInterface {

  /**
   * lorem ipsum
   * @param {string} baz               // Expected indentation of 12 spaces but found 5  indent
   * @returns {boolean}                // Expected indentation of 14 spaces but found 5  indent
   */
  fooBar(baz: string): boolean;
}
```

**What did you expect to happen?**

There shouldn't be any error here.

**What actually happened? Please include the actual, raw output from ESLint.**

$ yarn eslint
yarn eslint v0.27.5
$ eslint "src/**/*.ts"

C:\Users\foo\bar\my.module.ts
  13:1  error  Expected indentation of 2 spaces but found 4  indent
  17:1  error  Expected indentation of 2 spaces but found 0  indent

C:\Users\foo\bar\my.service.ts
   15:1  error  Expected indentation of 12 spaces but found 5  indent
   16:1  error  Expected indentation of 14 spaces but found 5  indent

This is a big issue when using --fix. Here is the code after ``eslint --fix "src/**/*.ts"`` : 

```js
const directives = [
  MyDirective,
];

@NgModule({
  imports: [
  CommonModule,
  ],
  declarations: directives,
  exports: directives
  })
export class MyModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MyModule,
      providers: [
        MyService,
      ]
    };
  }
}
```

```js
export interface MyInterface {

  /**
   * lorem ipsum
            {string} baz
              {boolean}
   */
  fooBar(baz: string): boolean;
}
```

**(Maybe) some related issues**

https://github.com/eslint/typescript-eslint-parser/issues/377
https://github.com/eslint/typescript-eslint-parser/issues/344

**Comment by ilyavolodin** [comment]
This has something to do with typescript parser, since the error doesn't happen when you convert it to regular JS code.

**Comment by noelmace** [comment]
Oh yeah sorry for that. I figured it out but forgot to close this issue and open a new one in https://github.com/eslint/typescript-eslint-parser.
