### ISSUE TITLE
Do not require modules with shareable config to be named eslint-config-*

### ISSUE THREAD

**Issue by dotchev** [eslint/eslint#9188]
In our team we use eslint with a bunch of projects. Naturally we want to use the same eslint configuration in our projects. To do that we have created a separate package with the shared .eslintrc. We include it as dev dependency in our projects and pass its .eslintrc on the command line via -c option.
This works but then we found that we cannot use local .eslintrc files to extend/override the shared configuration.
Now I have found [Shareable Configs](https://eslint.org/docs/developer-guide/shareable-configs) which is a great idea. Unfortunately it requires that "the module name begins with `eslint-config-`". This seems rather restrictive. To use it, we would have to rename our package with shared config, which would be a breaking change.

Why not make this an optional prefix?
For example if we have
```yml
extends: xyz
```
Then search for package:
1. eslint-config-xyz
2. xyz

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. I'm pretty sure there was a reason for requiring configs to be prefixed with `eslint-config-`, but I'm not sure what that reason was, so I'll let someone who has been around longer address whether this would be a good idea.

Keep in mind that you can also specify a relative path in the `extends` clause. So as a workaround, I think you could do something like this:

```yml
extends: './node_modules/my-config'
```

**Comment by klaasman** [comment]
It looks like this package is related: https://github.com/eslint/eslint/issues/2415

**Comment by ljharb** [comment]
@not-an-aardvark it'd be nice if when a path to a specific file was provided, the prefix wasn't added. Specifically, `package/path/to/file.js`.

**Comment by not-an-aardvark** [comment]
That makes sense, although I think some people use files in shareable configs which are intended to be resolved in that manner. For example, if I put `browser.js` in the root of `eslint-config-foo`, then I could do something like `extends: foo/browser` to easily reference a browser-specific set of rules.

As a workaround, you could use `extends: ./node_modules/package/path/to/file.js`.

**Comment by platinumazure** [comment]
@eslint/eslint-team Could someone comment on why we required sharable configs to start with `eslint-config-` in all cases, even when using path resolution?

> I'm pretty sure there was a reason for requiring configs to be prefixed with `eslint-config-`, but I'm not sure what that reason was, so I'll let someone who has been around longer address whether this would be a good idea.

**Comment by ilyavolodin** [comment]
I don't remember the exact reasoning behind having a prefix, but when shareable configs were created, one of the reasons was discoverability, as well as a way to differentiate between configs and plugins. Also I think we used prefixes to avoid naming collisions.

**Comment by ljharb** [comment]
All of that makes perfect sense, but doesn't necessitate the prefix when including a relative file path :-)

**Comment by yhaskell** [comment]
Also it breaks everyone who use one repo for all linters (not only for eslint) in the same repo. Plus it actually breaks the nodejs resolution which is a bad practice in the first place.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
