### ISSUE TITLE
no-useless-escape error in Regex

### ISSUE THREAD

**Issue by micheleangioni** [eslint/eslint#9241]
**Tell us about your environment**

[Eslint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiJ215Lm5hbWUud2l0aC5kb3RzJy5yZXBsYWNlKC9bXFwuXSsvZywgJ18nKVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

**What did you do? Please include the actual source code causing the issue.**

```js
'my.name.with.dots'.replace(/[\.]+/g, '_')
```

**What did you expect to happen?**

No errors

**What actually happened? Please include the actual, raw output from ESLint.**

`Unnecessary escape character: \..`

**Comment by platinumazure** [comment]
Thanks for the issue!

Period/dot/full stop does not need to be escaped inside a character class. This is working as intended. :smile:

**Comment by micheleangioni** [comment]
I confirm you are right, thanks for your fast answer :)

**Comment by tdmalone** [comment]
Hi @platinumazure, I was about to log an issue but found this existing one. Rather than opening a new issue, is this the same problem?

![image](https://user-images.githubusercontent.com/900469/32029383-d0daf21a-ba3f-11e7-94df-430972cde39b.png)

It's not in a character class, it's in a match, and the regex is explicitly intended to match a fullstop before the file extension. Without it being escaped, it would match any character... right? Or am I misunderstanding this?

**Comment by platinumazure** [comment]
The key in your case is, this is a string, not a regex literal. Therefore,
the string escape rules control, and `\.` is a useless escape.

If you want to match a literal period, you need `\\.` (double the backslash
so it becomes literal backslash). If you want to match any character, just
`.` will do. Right now, in a string, `\.` will be evaluated the same as
`.`, which is probably not what you want.

Hope this helps!

**Comment by tdmalone** [comment]
Ahhh, of course. Thanks so much!
