### ISSUE TITLE
Add CLI option to report unused eslint-disable directives

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9249]
(Repost of https://github.com/eslint/eslint/issues/6190)

`/* eslint-disable */` comments are useful to document when code is an exception to a given rule. If a piece of code was previously an exception, but now the rule is no longer being violated, it's useful to remove the comment so that it doesn't hide unintended problems in the future. Unfortunately, ESLint doesn't provide any way to detect unused comments, and it's not possible to do this with a custom rule using the public rule API because rules can't view the configurations of other rules to determine whether a directive is used.

When this was discussed in https://github.com/eslint/eslint/issues/6190, there was consensus that if a behavior like this was added to core, it would have to be implemented as a CLI flag. The TSC [decided](https://github.com/eslint/tsc-meetings/blob/00824ca375f62abd5d98931a2fecc80cae811964/notes/2016/2016-07-07.md#httpsgithubcomeslinteslintissues6190) to wait for a prototype before determining whether to accept the feature. A few months later, the issue was closed because [`eslint-plugin-eslint-comments`](https://github.com/mysticatea/eslint-plugin-eslint-comments) was released, which achieves the same behavior in a plugin by monkeypatching ESLint's APIs.

I'd like to reopen discussion on this because I think this would still be a useful feature, and I don't think using a plugin that monkeypatches core APIs is an acceptable solution in the long term, given that it breaks down the boundaries that we enforce between rules.

(Case in point: We recently refactored the `context.report` internals, causing `eslint-plugin-eslint-comments` to break because it was trying to monkeypatch an API that no longer existed (https://github.com/eslint/eslint/issues/9193). We ended up adding [this](https://github.com/eslint/eslint/blob/82d8b734acd44b0c320d0ab24ce3dff92120d735/lib/linter.js#L799-L810) and [this](https://github.com/eslint/eslint/blob/82d8b734acd44b0c320d0ab24ce3dff92120d735/lib/linter.js#L853-L869) to prevent the monkeypatches in `eslint-plugin-eslint-comments` from breaking, but those are hacks and I'd like to get rid of them.)

The proposal is to add a `--report-unused-disable-directives` CLI flag (along with corresponding `reportUnusedDisableDirectives` options in `CLIEngine` and `Linter`). When the flag is enabled, ESLint adds a new reported problem with error severity when it encounters an unused `eslint-disable` comment (or variants like `eslint-disable-line`).

---

I've created a prototype implementation (#9250). The implementation is actually fairly simple -- most of the diff in the PR comes from additional tests, docs, and passthrough options.

There are a few edge cases to consider -- I've written a bit about them below.

<details>
<summary>Edge cases</summary>

Definitions:

* "unused directive": A directive that would prevent errors from being reported, but no errors were actually reported, so it didn't suppress anything.
* "redundant directive": A directive that has no effect because the list of disabled rules is the same before and after applying it.

Unused directives would need to be detected in core, since they depend on whether other rules report errors. Redundant directives could be detected by external rules (although they would sometimes have to use strange report locations to prevent their own reports from being suppressed).  Because of this, I decided that the flag should only cause unused directives to be reported. Redundant directives are not reported unless they are also unused.

Examples:

1. First comment is unused, second comment is unused and redundant

    ```js
    /* eslint-disable */
    /* eslint-disable */
    ```

1. First comment is unused, second comment is redundant

    ```js
    /* eslint-disable */
    /* eslint-disable */
    (reported problem)
    ```

1. First comment is unused

    ```js
    /* eslint-disable foo */
    /* eslint-disable */
    (reported problem from foo)
    ```

1. First comment is unused

    ```js
    /* eslint-disable foo */
    /* eslint-disable */
    (reported problem from an unrelated rule)
    ```

1. First comment is unused, second comment is redundant

    ```js
    /* eslint-disable */
    /* eslint-disable foo */
    (reported problem from foo)
    ```

1. Second comment is redundant and unused

    ```js
    /* eslint-disable */
    /* eslint-disable foo */
    (reported problem from an unrelated rule)
    ```

1. First comment is unused, second comment is redundant and unused

    ```js
    /* eslint-disable */
    /* eslint-disable foo */
    /* eslint-enable foo */
    (reported problem from foo)
    ```

1. Comment is redundant

    ```js
    /* eslint-enable */
    ```
</details>

**Comment by not-an-aardvark** [comment]
**TSC Summary**: This issue proposes adding a CLI flag to report unused `eslint-disable` directives.

**TSC Question**: Should we accept this proposal?

**Comment by not-an-aardvark** [comment]
This was accepted in [today's TSC meeting](https://gitter.im/eslint/tsc-meetings/archives/2017/09/14).

**Comment by klimashkin** [comment]
Thanks for great work @not-an-aardvark.
From description I didn't quit get, is it possible to use `reportUnusedDisableDirectives` option right in `.eslintrc` or we still need to use `eslint-plugin-eslint-comments` which will use that option internally?

**Comment by not-an-aardvark** [comment]
This is only available as a command-line flag at the moment, and can't be enabled in a configuration file. (Since this is not a rule, it was decided in https://github.com/eslint/eslint/issues/6190 that it shouldn't be configured in the same way as a rule.)

One potential solution would be a `reportUnusedDisableDirectives` top-level option in a config. I would be slightly concerned about allowing this option to be specified in shareable configs (given the potential footgun described in the [documentation](https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives), it seems like a good idea to make users explicitly opt-in).
