### ISSUE TITLE
no-unused-vars when variable is used in quotes in jsx

### ISSUE THREAD

**Issue by cs01** [eslint/eslint#9257]
**Tell us about your environment**

* **ESLint Version:** "eslint": "^4.6.1", "eslint-plugin-react": "^7.3.0"
* **Node Version:** v6.11.2
* **npm Version:** yarn -- 0.27.5

**What parser (default, Babel-ESLint, etc.) are you using?**
```
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  },
  "dependencies": {
    "eslint-loader": "^1.9.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "webpack": "^3.5.5"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "eslint": "^4.6.1",
    "eslint-plugin-react": "^7.3.0"
  }
```

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "es6": true,
        "jquery": true
    },
    "globals":{
        "module": true,
        "_": true,
        "moment": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "no-console": [
            0
        ],
        "react/jsx-uses-vars": 1
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
let is_current_thread_being_rendered = (parseInt(t.id) === this.state.current_thread_id)
, cls = is_current_thread_being_rendered ? 'bold' : ''

let thread_text = <span className='{cls}'>thread id {t.id}, core {t.core} ({t.store})</span>
```

**What did you expect to happen?** Expected the variable `cls` to be recognized as used even though it's inside string quotes

**What actually happened? Please include the actual, raw output from ESLint.**

`cls` is not recognized as being used. When I remove the quotes around `{cls}`, eslint then recognizes that it's used.

```
ERROR in ./gdbgui/static/js/src/Threads.jsx

/home/csmith/git/gdbgui/gdbgui/static/js/src/Threads.jsx
  114:19  error  'cls' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

 @ ./gdbgui/static/js/src/gdbgui.js 53:15-39
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. I'm confused about why you were expecting the variable to be recognized as used -- could you clarify? The variable isn't getting used here -- your attribute has the value `'{cls}'`, which has nothing to do with the variable named `cls`.

**Comment by cs01** [comment]
Ah thanks. I am new to JSX and I thought the replacement occurred within strings too. Will close.
