### ISSUE TITLE
Make `eslint.linter` non-enumerable

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9270]
When using ESLint on `master` and Node 8.4.0, running `require("eslint")` in the REPL produces this output:

```js
$ node
> require('eslint')
{ linter:
   Linter {
     sourceCode: null,
     version: '4.6.1',
     rules: Rules { _rules: [Object] },
     environments: Environments { _environments: [Object] } },
  Linter: [Function: Linter],
  CLIEngine: { [Function: CLIEngine] version: '4.6.1', getFormatter: [Function: getFormatter] },
  RuleTester: { [Function: RuleTester] [Symbol(it)]: null, [Symbol(describe)]: null },
  SourceCode: [Function: SourceCode] }
```

Note that `eslint.linter` is the first property that appears in the list, and `eslint.Linter` comes afterwards. This could be confusing for users who are figuring out how to use the API with the REPL, because they might be inclined to use `eslint.linter` despite the fact that `eslint.linter` is deprecated. The distinction between `eslint.linter` and `eslint.Linter` is also likely to be unclear.

To avoid this, I think we should make `eslint.linter` non-enumerable. That way, it will still be available to old integrations using `eslint.linter`, but it's unlikely to create confusion for new users.

I'm unsure whether this should be considered a breaking change -- it could change the behavior of something like `Object.keys(require("eslint"))`, but I don't know why anyone would do that.

**Comment by not-an-aardvark** [comment]
**TSC Summary**: This issue proposes making the deprecated `eslint.linter` property non-enumerable, to make it clearer to users that they should use `eslint.Linter` instead. This could be a breaking change for some unusual uses of the API, such as `Object.keys(require('eslint'))`.
**TSC Question**: Should we accept this issue?

**Comment by kaicataldo** [comment]
**TSC Resolution**: This is now accepted as a breaking change.

**Comment by j-f1** [comment]
I’m looking into doing this.

**Comment by not-an-aardvark** [comment]
@j-f1 Thanks! To be honest, I'm not sure we should add a deprecation warning -- the main goal of this change is to deter new users, not to issue warnings for old users. I haven't looked into how many integrations are still using `eslint.linter`, but in general deprecation warnings can occasionally cause problems (e.g. if all messages from stdout are relayed to the user in an obtrusive way).

If we do add a deprecation warning, I think we should use something like [`process.emitWarning`](https://nodejs.org/api/process.html#process_process_emitwarning_warning_options) so that we respect Node's `--no-warnings` CLI flag.
