### ISSUE TITLE
Running eslint with npm isn't showing me any errors

### ISSUE THREAD

**Issue by mven** [eslint/eslint#9287]
**Tell us about your environment**

* **ESLint Version:**
4.6.1

* **Node Version:**
6.8

* **npm Version:**
5.3.0

**What did you do? Please include the actual source code causing the issue.**
I'm trying to run eslint in an npm script task, but for some reason it's not returning errors.

```js
// package.json scripts property
"lint:js": "node node_modules/eslint/bin/eslint src/**/*.js",

// trying to run the script doesn't output any problems
npm run lint:js

// though, when I run the same command in terminal, I'm shown problems in the .js files
node node_modules/eslint/bin/eslint src/**/*.js
```

**What did you expect to happen?**
I expect when I run `npm run lint:js` to show me problems in my JS files.

**What actually happened? Please include the actual, raw output from ESLint.**
Problems with my code aren't shown when I run eslint through an npm script.

`npm run lint:js` output:
```
~ npm run lint:js

> pricing@0.0.1 lint:js /Users/mv/testrepo
> eslint src/**/*.js
```

`node node_modules/eslint/bin/eslint src/**/*.js` output (correct behavior):

``` 
~ node node_modules/eslint/bin/eslint src/**/*.js

/Users/Users/mv/testrepo/routes/routes.js
   48:1  error  Expected indentation of 0 spaces but found 1  indent
  112:6  error  Missing trailing comma                        comma-dangle

✖ 2 problems (2 errors, 0 warnings)
  2 errors, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by gyandeeps** [comment]
Change this line to 

```
// package.json scripts property
"lint:js": "eslint src/**/*.js",
```

and then try again. Makesure you have eslint locally installed.

**Comment by mven** [comment]
@gyandeeps Thanks, I tried that as well and I'm still getting the same result (no issues showing). Also, my `eslint` is in my devDependencies. https://docs.npmjs.com/cli/run-script

**Comment by mven** [comment]
FWIW, `stylelint` properly shows me errors on my .scss files when I do `npm run lint:scss` and that's configured the same as eslint.

```
// package.json
"lint:scss": "stylelint src/**/*.scss",
```

**Comment by gyandeeps** [comment]
Can you share a reproducible case so that I can try it on my machine?

**Comment by mven** [comment]
Interesting, I started fresh and it's working for some reason. Going to have to dig into this large repo to figure out what's the issue. Thanks for the help so far.

**Comment by stoberov** [comment]
What fixed for me was using double quotes and an escaping slash like so:
"lint": "eslint \"**/*.{js,jsx}\" --quiet",

Previously, it would not work with single quotes:
"lint": "eslint '**/*.{js,jsx}' --quiet",
