### ISSUE TITLE
eslint --init always use npm to install dependency, but I use yarn as package manager

### ISSUE THREAD

**Issue by erlangxk** [eslint/eslint#9290]
eslint v4.6.1
yarn 1.0.1

C:\study\mxaccount\apiserver>eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? JavaScript
Checking peerDependencies of eslint-config-standard@latest
Installing eslint-config-standard@latest, eslint-plugin-import@>=2.2.0, eslint-plugin-node@>=4.2.2, eslint-plugin-promise@>=3.5.0, eslint-plugin-standard@>=3.0
.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-plugin-import@2.7.0 requires a peer of eslint@2.x - 4.x but none was installed.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint@>=3.19.0 but none was installed.
npm WARN eslint-plugin-node@5.1.1 requires a peer of eslint@>=3.1.0 but none was installed.
npm WARN eslint-plugin-standard@3.0.1 requires a peer of eslint@>=3.19.0 but none was installed.

+ eslint-plugin-import@2.7.0
+ eslint-config-standard@10.2.1
+ eslint-plugin-promise@3.5.0
+ eslint-plugin-node@5.1.1
+ eslint-plugin-standard@3.0.1
added 36 packages, removed 188 packages and updated 1 package in 11.057s
Successfully created .eslintrc.js file in C:\study\mxaccount\apiserver

Can I tell eslint to use yarn to install other packages?

**Comment by erlangxk** [comment]
checked the source code of eslint, 

bin/eslint.js -->lib/config/config-initializer.js -->util/npm-util-->

function installSyncSaveDev(packages) {
    if (!Array.isArray(packages)) {
        packages = [packages];
    }
    const npmProcess = spawn.sync("npm", ["i", "--save-dev"].concat(packages),
        { stdio: "inherit" });
    const error = npmProcess.error;

    if (error && error.code === "ENOENT") {
        const pluralS = packages.length > 1 ? "s" : "";

        log.error(`Could not execute npm. Please install the following package${pluralS} with your package manager of choice: ${packages.join(", ")}`);
    }
}

npm is hardcoded here, and no way to change to use yarn to install.

**Comment by not-an-aardvark** [comment]
Thanks for the report. However, this was discussed in https://github.com/eslint/eslint/pull/9023 and the team ended up deciding not to add an option to use yarn.

**Comment by wesharehoodies** [comment]
Boo! Let's add the option!
