### ISSUE TITLE
Is there a no es2016 or no es2017 rule ?

### ISSUE THREAD

**Issue by Alphapage** [eslint/eslint#9299]
Hello,

I'd like to know if there is a way to avoid es2016 or future es features.

Is it possible to detect when es2016 is used  for example ?

Thanks in advance for your help.

**Comment by platinumazure** [comment]
Hi @Alphapage, thanks for the issue.

If you're using the default parser, you can configure the `parserOptions.ecmaVersion` to be something before ES2016 (e.g., 2015 or 6, or 5 if you need ES5). See our [parser options documentation](http://eslint.org/docs/user-guide/configuring) for more info.

If you're using a different parser, you could use the [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) rule to block certain syntaxes.
