### ISSUE TITLE
[enhancement] add --fix to sort-keys.

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9310]
hope code like this can be autofixed.
```js
var rules = {
   "no-console": 0,
   "debugger": 0,
};

==>

var rules = {
   "debugger": 0,
   "no-console": 0,
};
```

**Comment by not-an-aardvark** [comment]
I think we decided not to do this in https://github.com/eslint/eslint/issues/7714.

**Comment by Slapbox** [comment]
Just want to speak up and say how nice this feature would be to have. I'd love to use this rule (sort-keys), but it would take so much time to maintain manually that it would never be worth it.
