### ISSUE TITLE
eslint-visitor-keys package

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#9312]
As discussed in [yesterday's TSC Meeting](https://gitter.im/eslint/tsc-meetings/archives/2017/09/14), we need to hammer out the details of the proposed [`eslint-visitor-keys` package](https://github.com/eslint/tsc-meetings/issues/58#issuecomment-328612081). This was proposed to extract and share visitor keys between parsers.

Questions to answer: 
1. What does the package exactly contain? Does it contain traversal logic or is just a static object of the default visitor keys (my understanding was the latter but there was some uncertainty during the meeting)?
1. If it contains more than the default visitor keys, should we name is something different?

We can create the repo once we hash this out!

@eslint/eslint-tsc @JamesHenry

**Comment by not-an-aardvark** [comment]
If we're planning to remove the `estraverse` dependency in https://github.com/eslint/eslint/pull/8755, would it be better to include all of `Traverser` in the new package to avoid code duplication? That way, other modules could use the new package as a substitute for `estraverse`.

**Comment by platinumazure** [comment]
@not-an-aardvark Would it be better to create an `eslint-traverse` as well as `eslint-visitor-keys` (the latter of which would be consumed by `eslint-traverse` and `eslint-scope`)?

**Comment by not-an-aardvark** [comment]
I suppose, although it seems like the visitor keys could be exported by `eslint-traverse` too.

**Comment by mysticatea** [comment]
IMO, it should separate about visitor-keys from `eslint-traverse`. packages such as `esrecurse` have `estraverse` as a dependency but it does not use their traversing logic. `eslint-scope` is same. It's the sign that `estraverse` has 2 responsibilities we can separate.

**Comment by not-an-aardvark** [comment]
Ok, sounds fine to me.

**Comment by mysticatea** [comment]
Please check it: https://github.com/eslint/eslint-visitor-keys/pull/1

**Comment by not-an-aardvark** [comment]
Closing because the package has been created.
