### ISSUE TITLE
eslint --init wipes node_config/.bin

### ISSUE THREAD

**Issue by lsiden** [eslint/eslint#9315]
Running eslint --init wipes node_modules/.bin before repopulating it with other scripts.  I then have to run 'yarn' again to get back the scripts that were wiped.

eslint version 4.7.0
node 8.5.0
yarn 1.0.2

**Comment by not-an-aardvark** [comment]
This is probably because eslint --init runs `npm install` to install plugins. However, I'm not sure why files in `node_modules/.bin` were removed. How did the files get there in the first place?

**Comment by lsiden** [comment]
Somehow I wound up with an unwanted node_modules/ in my src/ directory.  So eslint was reading .eslintrc in many subdirectories under src/node_modules/ which wreaked havoc with --init.  Resolved.
