### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by shiioo** [eslint/eslint#9319]
**Tell us about your environment**

* **ESLint Version:** 4.7.0
* **Node Version:** 8.5.0
* **npm Version:** 5.4.2

> pi@raspberrypi:~ $ eslint --version
v4.7.0

> pi@raspberrypi:~ $ npm install -g babel-eslint eslint-plugin-react eslint-plugin-import eslint-plugin-node eslint-plugin-jsx-a11y eslint-plugin-flowtype
npm WARN eslint-plugin-react@7.3.0 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.7.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@5.1.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.0.2 requires a peer of eslint@^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-flowtype@2.35.1 requires a peer of eslint@>=2.0.0 but none is installed. You must install peer dependencies yourself.

I think that speaks for itself. Why don't they see it's installed?

**Comment by not-an-aardvark** [comment]
Thanks for the report. I'm not quite sure why that's happening, although if anything it's an issue with npm, not ESLint.

**Comment by fenec** [comment]
I've got the same error after updating npm to 5.4.2

**Comment by ilyavolodin** [comment]
This has been an issue with npm 5 for a while. It works fine with all earlier versions. So either is a breaking change that hasn't been documented or it's a bug in npm 5.

**Comment by ceeyang** [comment]
I have got the same error too.
```
➜  best-resume-ever git:(master) ✗ npm install
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-promise@>=3.5.0 but none is installed. You must install peer dependencies yourself.

up to date in 4.36s
➜  best-resume-ever git:(master) ✗
```

**Comment by not-an-aardvark** [comment]
Closing because this isn't an issue with ESLint.
