### ISSUE TITLE
Eslint glob (**) does not recursively search all directories

### ISSUE THREAD

**Issue by am80l** [eslint/eslint#9330]
My project uses Lerna so my directory structure looks something like this:
```
└── packages
|  ├── package1
|  ├── package2
|  |  ├── dist
|  |  ├── examples
|  |  ├── images
|  |  ├── src
|  |  ├── templates
|  |  └── test
```
Eslint v4.7.1
Node v6.3
npm 3.10.3

Parser: babel-eslint

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "ecmaFeatures": true,
      "arrowFunctions": true,
      "classes": true,
      "sourceType": "module",
      "templateStrings": true,
      "jsx": true,
      "blockBindings": true
    },
    "ecmaVersion": 6
  },
  "extends": "eslint:recommended",
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "rules": {
    "key-spacing": [1, { "afterColon": true }],
    "semi": [2, "always"],
    "comma-dangle": [2, "always-multiline"],
    "indent": [2, 2],
    "jsx-quotes": [2, "prefer-single"],
    "no-console": 1,
    "no-unreachable": 2,
    "valid-typeof": 2,
    "quotes": [2, "single", "avoid-escape"],
    "curly": [2, "multi-or-nest", "consistent"],
    "no-var": 2,
    "object-curly-spacing": [2, "always"],
    "space-before-blocks": [2, "always"],
    "react/jsx-boolean-value": 1,
    "react/jsx-closing-bracket-location": 1,
    "react/jsx-curly-spacing": [2, "never"],
    "react/jsx-max-props-per-line": [1, { "maximum" : 2 }],
    "react/jsx-no-duplicate-props": 1,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-props": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/jsx-wrap-multilines": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 1,
    "react/sort-prop-types": 1
  },
  "plugins": [
    "react"
  ]
}
```

</details>

From the package root (above packages), this command does not catch all .js files
```eslint packages/**/*.js```
Specifically, my .js files in `templates` are not linted. 

However, with this:
```eslint packages/**/**/*.js```
All files are linted as was expected with the original command.

My expectation is that `**` would traverse the full directory depth without requiring `**/**`

**Comment by gyandeeps** [comment]
Can you share how do you run this command?
Using npm scripts or directly on CLI? Can you share how you do it.

**Comment by platinumazure** [comment]
If you don't quote your glob patterns, your shell can intercept them and then we can't guarantee the results. If you quote your glob patterns such that they are not intercepted by the shell, then ESLint can expand the globs in the way you expect.

Not 100% sure that there isn't something else going on, but that's where I would start from the information so far.

**Comment by am80l** [comment]
@gyandeeps Yes this is run as an npm script i.e.
```js
        "eslint": "eslint packages/**/**/*.js",
```

@platinumazure I had not considered quoting the glob pattern. I gave it a go and am seeing a lot of new files being linted. This was most likely the issue, thank you!
