### ISSUE TITLE
one-var should not trigger when a state-change happens between declarations

### ISSUE THREAD

**Issue by freaktechnik** [eslint/eslint#9333]
**Tell us about your environment**

* **ESLint Version:** 3.7.0
* **Node Version:** 8.0.0
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint (also noticed it with stock parser)

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
    "env": {
        "commonjs": true,
        "webextensions": true
    },
    "plugins": [
        "babel",
        "xss"
    ],
    "rules": {
        "node/no-missing-require": 0,
        "node/no-unpublished-require": 0,
        "node/no-unsupported-features": 0,
        "arrow-parens": 1,
        "generator-star-spacing": 1,
        "xss/no-mixed-html": 2,
        "xss/no-location-href-assign": 2,
        "jsdoc/require-param": 0,
        "jsdoc/require-description-complete-sentence": 0
    },
    "extends": "plugin:freaktechnik/browser"
}
```
(`one-var` is inherited from the freaktechnik plugin, and set to warn [here](https://github.com/freaktechnik/eslint-plugin-freaktechnik/blob/845c089f62383cf0c447f07b3ca23fb1086c459d/index.js#L97))

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
... // line 158
if(alarm.name === alarmName) {
    const urls = await getURLs();
    if(!urls.length) {
        this.unqueueUpdateRequest(priority);
        return;
    }
    const promises = urls.map((url) => this.queueRequest(url, headers, requeue, false).then((result) => {
        return onComplete(result, url);
    }).catch((e) => console.error("Error during", priority, "update request", url, "for", this.type, ":", e)));
    await Promise.all(promises);
    const interval = await this.interval;
    browser.alarms.create(alarmName, {
        when: Date.now() + (interval * intervalModifier)
    });
}
... // line 174
```
(see [source](https://github.com/freaktechnik/justintv-stream-notifications/blob/8b17f49468f04adc5762c5129538d516e4715d60/src/background/queue/service.js#L159-L173))

**What did you expect to happen?**
`one-var` should never trigger for this bit of code.

**What actually happened? Please include the actual, raw output from ESLint.**
`one-var` triggers for both the `const promises` and `const interval` assignments. Especially in the case of `interval` it would totally change the behavior of the code, while `promises` is just potential work that wasn't needed if `!urls.length` is true.

There is also another unexpected `one-var` trigger when the value relies on a value only defined after the last definition ([example](https://github.com/freaktechnik/justintv-stream-notifications/blob/ccda1dbabdecd2d9a6862edfa34d4a1ccb3f3667/src/background/providers/youtube.js#L433) which relies on `streamIds` which is even declared after the last const block. And this also has a throw in between, which should also break up the declaration blocks)

ESLint output:
```
/home/martin/dev/justintv-stream-notifications/src/background/queue/service.js
  165:17  warning  Combine this with the previous 'const' statement  one-var
  169:17  warning  Combine this with the previous 'const' statement  one-var
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. I think this is a just design limitation of the `one-var` rule -- it's generally not possible to statically determine if any given line modifies external state.

**Comment by platinumazure** [comment]
I think I agree with @not-an-aardvark. This rule is one of our more opinionated ones and it is basically designed to encourage the use of functions/subroutines for compartmentalizing the code a bit. Also, the rule was created before ES6. Personally, I just don't use it.

**Comment by not-an-aardvark** [comment]
Closing because this is working as intended.
