### ISSUE TITLE
Update the docs/developer-guide/architecture page

### ISSUE THREAD

**Issue by VictorHom** [eslint/eslint#9337]
Page link - https://eslint.org/docs/developer-guide/architecture

I believe the architecture has changed over time and it makes sense to update this page so new contributors can acclimate more quickly to what/which file does what (at least a high level overview)

Most of the page is still accurate, but one part didn't seem up-to-date (since the file doesn't exist anymore):

> lib/eslint.js - this is the core eslint object that does code verifying based on configuration options. This file does no file I/O and does not interact with the console at all. For other Node.js programs that have JavaScript text to verify, they would be able to use this interface directly.

**Comment by VictorHom** [comment]
if the issue makes sense, I can look into and help with updating the documentation :)

**Comment by platinumazure** [comment]
Hi @VictorHom, thanks for the issue!

Yes, we absolutely should update this document! `lib/eslint.js` has basically been replaced by `lib/linter.js` (exports class Linter), but there has also been a lot of decomposition of some of the functionality previously in `lib/eslint.js` into ancillary files.

We could probably start by replacing `lib/eslint.js` with `lib/linter.js`.
