### ISSUE TITLE
eslint no-unused-vars

### ISSUE THREAD

**Issue by Cleanshooter** [eslint/eslint#9355]
**Tell us about your environment**

* **ESLint Version:**
eslint@3.19.0
eslint-config-airbnb@15.1.0
eslint-plugin-import@2.7.0
eslint-plugin-jsx-a11y@5.1.1
eslint-plugin-react@7.3.0
* **Node Version:**
v6.7.0
* **npm Version:**
3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint@7.2.3

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
 "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "forOf": true,
      "jsx": true,
      "es6": true,
      "experimentalObjectRestSpread" : true
    }
  },
  "rules": {
    "comma-dangle": 0,
    "indent": 0,
    "react/prop-types": 0,
    "react/jsx-indent" : [0, 'tab'],
    "react/jsx-indent-props" : [0, 'tab'],
    "linebreak-style": 0,
    "react/jsx-closing-bracket-location" : 0,
    "object-curly-spacing" : 0,
    "arrow-body-style": 0,
    "no-console": 0,
    "max-len": 0,
    "prefer-template": 0,
    "import/no-unresolved": 0,
    "global-require": 0,
    "no-underscore-dangle": 0,
    "no-shadow": "off",
  },
  "plugins": [
    "react"
  ],
  "globals": {
    "__DEVSERVER__": true,
    "__DEVCLIENT__": true
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**
Using Mongoose to pull config form my DB then axios to pull additional info before sending it back.   The warning is saying that "config" (line 2 below) is the problem, however, it is clearly being used by the arrow function in line 8.  

```js
export function get(req, res) {
  Config.findOne({}, (err, config) => {
    if (err) {
      console.log(err);
      return res.status(500).send('We failed to fetch the config for some reason');
    }

    return config => axios.request({
      method: 'GET',
      url: 'https://myurl.com/things-I-want'
    })
    .catch((error, res) => {
      res.statusMessage = 'Please check the logs for more information.';
      return res.status(400).end();
    })
    .then((response, res) => {
      const configuration = config[0];
      configuration.stuff = response.data;
      return res.json(configuration);
    });
  });
}
```

**What did you expect to happen?**
I would expect that since I'm using the variable in an arrow function that I would NOT get the "no-unused-vars" warning but I am. 

**What actually happened? Please include the actual, raw output from ESLint.**
  10:28  error  'config' is defined but never used  no-unused-vars

Thanks to anyone who takes time to review and give feedback.

**Comment by platinumazure** [comment]
It looks like you have two `config` variables in scope:

```js
export function get(req, res) {
  Config.findOne({}, (err, config) => {   // <---- First declaration of config
    if (err) {
      console.log(err);
      return res.status(500).send('We failed to fetch the config for some reason');
    }

    return config => axios.request({  // <--- Second declaration of config (shadows first one)
      method: 'GET',
      url: 'https://myurl.com/things-I-want'
    })
    .catch((error, res) => {
      res.statusMessage = 'Please check the logs for more information.';
      return res.status(400).end();
    })
    .then((response, res) => {
      const configuration = config[0];   // <---- This uses the second declaration
      configuration.stuff = response.data;
      return res.json(configuration);
    });
  });
}
```

First declaration is unused (it is shadowed by second `config`).

If you're trying to return a promise from `get` (rather than a function that returns a promise), you should probably just remove `config =>` and return the promise itself.

**Comment by Cleanshooter** [comment]
this code had other bugs so I'm thinking it's safe to close it anyway... BUT

when using the babel compiler doesn't it treat the (config) => {stuff} the same as config => {stuff}?  

Writing it like (config) => {stuff} throws the "arrow-parens" lint warning.

**Comment by platinumazure** [comment]
@Cleanshooter `(config) => {}` is the same as `config => {}`, whether parsing via Babel or any other parser. It will run exactly the same.

arrow-parens is a stylistic rule and it might be configured to prefer the use or absence of parentheses for single-argument arrow functions.

**Comment by ilyavolodin** [comment]
Closing this issue, as it seems resolved.
