### ISSUE TITLE
is it possible to turn off 'no-use-before-define' rule for arrow functions?

### ISSUE THREAD

**Issue by xexys** [eslint/eslint#9368]
**Tell us about your environment**

* **ESLint Version: 4.7.2**
* **Node Version: 6.9.2**
* **npm Version: 3.10.9**

**What parser (default, Babel-ESLint, etc.) are you using?**
```js
    parser: 'babel-eslint',
    parserOptions: {
        sourceType: 'script',
        generators: true,
        ecmaVersion: 6,
        ecmaFeatures: {
            "arrowFunctions": true
        }
    },
```

**Comment by not-an-aardvark** [comment]
No, this is not possible. However, you could [create a custom rule](https://eslint.org/docs/developer-guide/working-with-rules) that does this.

**Comment by not-an-aardvark** [comment]
Closing because the question has been answered.
