### ISSUE TITLE
No Undefined being thrown when I use Class Properties

### ISSUE THREAD

**Issue by captDaylight** [eslint/eslint#9381]
eslint: 3.19.0
node: 8.4.0
npm: 5.3.0

using the Airbnb setup (15.0.1)

I recently found out about [class properties](https://babeljs.io/docs/plugins/transform-class-properties/)/fields but when trying to use them I'm getting a [no-undef](https://eslint.org/docs/rules/no-undef) error.

Before you might write something like 
```
class MyClass extends React.PureComponent {
  constructor() {
    this.myFunction = this.myFunction.bind(this);
  }
  myFunction() {
    const { myVar } = this.props;
  }
  
  ... etc
}
```
but with class properties you can do:
```
class MyClass extends React.PureComponent {
  myFunction = () => {
    const { myVar } = this.props;
  }
  
  ... etc
}
```
The code runs, but I'm getting errors on each line that declares a class property in this way. The [class fields proposal](https://github.com/tc39/proposal-class-fields) is currently stage 3 so far along its way to approval.

Any thoughts on supporting this or are things added once they are fully part if JS?

**Comment by not-an-aardvark** [comment]
Sorry, but we only support syntax features once they reach stage 4 (see our [readme](https://github.com/eslint/eslint/blob/ee99876ccc76585b0af2c8673d7eb25bb0b972fa/README.md#what-about-experimental-features)).
