### ISSUE TITLE
Mixing script and module files

### ISSUE THREAD

**Issue by dinoboff** [eslint/eslint#9400]
I am trying to use eslint with standard-things/esm which require to mix module and script files. Most file are authored with module with a few script to bridge with node's `require`.

AFAIK, the only way to currently support different source types is to put them in different folder* but it's incompatible with node current ES Module Interoperability proposal, with which cjs and esm share the same location except for their file extensions: .js for script and .mjs for modules.

Although, most package will be authored in one mode and transpiled to both, supporting source types via file extension will be useful in cases like  standard-things/esm or in tests.

**Comment by platinumazure** [comment]
If you're using a recent version of ESLint, you could use [glob-based configuration overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) for this scenario.

Basically you could create an override for `"**/*.mjs"` and specify `parserOptions: { sourceType: "module" }` there (using "script" everywhere else), or vice versa.

**Comment by dinoboff** [comment]
@platinumazure Thanks, it works. I see it's been added in v4.1.

**Comment by platinumazure** [comment]
@dinoboff Glad to help. I'll go ahead and close this issue, but please feel free to comment here or stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need anything else.
