### ISSUE TITLE
Use strict equality comparisons in RuleTester

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9417]
As of ESLint v4.8, `RuleTester` performs loose equality comparisons [here](https://github.com/eslint/eslint/blob/d7610f57abd304b318d1e7d2ec20e9d58fb70cbc/lib/testers/rule-tester.js#L468) for values like error line numbers. For example, providing the string `"3"` or the array `["3"]` as an expected line number will cause the test to pass, even when the actual line number is the number `3`. I think this isn't ideal, for the same reason that loose equality is a bad idea in general (it can conceal potential errors in code).

I think we should update `RuleTester` to use strict equality checks. This would be a breaking change since it could cause some new test failures, but I suspect very few people are relying on this behavior.

**Comment by not-an-aardvark** [comment]
Adding this to the TSC agenda because I don't expect it to be contentious, and there is a TSC meeting later today anyway.

**TSC Summary**: This proposes using strict equality checks in `RuleTester` rather than loose equality checks. It would be a breaking change.
**TSC Question**: Should we accept this proposal?

**Comment by not-an-aardvark** [comment]
In [today's meeting](https://gitter.im/eslint/tsc-meetings/archives/2017/10/12), the TSC decided to accept this as a breaking change for 5.0.

**Comment by Orlandster1998** [comment]
@not-an-aardvark I could do that. Do I understand it right, you want to replace all of the `assert.equal` with `assert.strictEqual` ?

**Comment by not-an-aardvark** [comment]
@Orlandster1998 Yes, and we also want to replace [this `assert.deepEqual`](https://github.com/eslint/eslint/blob/0b898651c2386e3551327d5052818da0fc94b175/lib/testers/rule-tester.js#L373) with `assert.deepStrictEqual`.

That said, keep in mind that this is scheduled as a breaking change for the v5.0.0 release, which probably isn't going to happen for a few months. So if you do make a PR now, we won't end up merging it for a few months, and it's possible you would need to fix merge conflicts when we do end up merging it. Because of this, I had been planning to make a PR closer to when we do the v5.0.0 release. (That said, if you want to make a PR now, I certainly won't stop you.)
