### ISSUE TITLE
Scheduled release for October 13th, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9425]
The scheduled release on Friday, October 13th, 2017 is assigned to:

* @kaicataldo
* @ilyavolodin 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

Resources:

* [Release guidelines](https://eslint.org/docs/maintainer-guide/releases)

**Comment by ilyavolodin** [comment]
ESLint v4.9.0 has been released.

@eslint/eslint-team Please remember to only merge semver-patch patches until we evaluate on Monday whether we need to do a patch release.

**Comment by ilyavolodin** [comment]
No patch release was necessary. This concludes the v4.9.x release cycle; please feel free to merge semver-minor changes again.
