### ISSUE TITLE
Configurable message for rules

### ISSUE THREAD

**Issue by jasonxia23** [eslint/eslint#9427]
**What version are you using?**
4.8.0
**What did you do?**
N/A
**What happened?**
N/A
**What did you expect to happen?**
It seems to be better if I can config message for a certain rule myself.

**Comment by not-an-aardvark** [comment]
Could you elaborate on this proposal? Is there something about the current messages that isn't working for you? How would the proposed message configuration work? Providing a lot of detail will make it easier to evaluate your proposal.

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided. If this is still something you'd like to propose, please create a new issue and provide the information described [here](https://eslint.org/docs/developer-guide/contributing/changes).
