### ISSUE TITLE
"camelcase" rule conflicts with Vue.js style guide

### ISSUE THREAD

**Issue by jpickwell** [eslint/eslint#9435]
**Tell us about your environment**

* **ESLint Version: 4.8.0**
* **Node Version: 8.2.1**
* **yarn Version: 1.2.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint v8.0.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: 'eslint:recommended',
  parser: 'babel-eslint',
  plugins: [
    'babel',
    'html',
    'lodash',
    'you-dont-need-lodash-underscore'
  ],
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module'
  },
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jquery: true,
    node: true
  },
  rules: {
    camelcase: [2, { properties: 'always' }]
  }
}
```
</details>

**What did you do? Please include the actual source code causing the issue.**

```js
export default {
  methods: {
    zfSetup()
    {
      this.$_zfComponent = this.$_zfComponent || this.setupFoundation()
    },

    zfTearDown()
    {
      if(!this.$_zfComponent)
      {
        return
      }

      this.tearDownFoundation()

      this.$_zfComponent = null
    }
  },

  mounted()
  {
    this.zfSetup()
  },

  activated()
  {
    this.zfSetup()
  },

  destroyed()
  {
    this.zfTearDown()
  },

  deactivated()
  {
    this.zfTearDown()
  }
}
```

**What did you expect to happen?**
No errors.

**What actually happened? Please include the actual, raw output from ESLint.**
```
   5:12  error  Identifier '$_zfComponent' is not in camel case  camelcase
  17:12  error  Identifier '$_zfComponent' is not in camel case  camelcase

✖ 2 problems (2 errors, 0 warnings)
```

The Vue.js Style Guide has a section about private property names (https://vuejs.org/v2/style-guide/#Private-property-names-essential). It states that private property names should start with `$_` to avoid conflicts with Vue.js properties. However, following this rule causes ESLint's `camelcase` rule to complain because the underscore is seen as being in the "middle" of the variable name.

I propose adding prefix/suffix options to the `camelcase` rule. The options would default to an empty string. The options could support multiple values. The enhanced rule would ignore the prefix/suffix values and check the remaining variable name against the existing rule logic.

A `prefix` option of type `String` is the bare minimum to solve my issue.

**Comment by kaicataldo** [comment]
Hi, and thanks for the issue! I'm actually not convinced this belongs in core, as requiring/disallowing camelcasing is a pretty straightforward rule and muddying that might make it confusing. 

There is currently work happening in the eslint-plugin-vue repo to create a preset that will enforce as much of the style guide as possible (see https://github.com/vuejs/eslint-plugin-vue/issues/77). Perhaps this could be a custom rule?

Alternatively, if we decide that we do want to change the existing rule in core, I would prefer an option that would either ignore or allow exceptions matched by a regex to make it as flexible as possible.

**Comment by jpickwell** [comment]
I wasn't aware of eslint-plugin-vue. Thanks for letting me know. I made such a comment on #9233.
