### ISSUE TITLE
Improve the documentation for no-restricted-modules

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#9437]
The current [documentation for `no-restricted-modules`](https://eslint.org/docs/rules/no-restricted-modules) would benefit from more information and about its configuration and clearer examples of what its configuration options do. A good place to start would be to emulate the documentation for the similar [no-restricted-imports rule](https://eslint.org/docs/rules/no-restricted-imports).

**Comment by vibss2397** [comment]
@kaicataldo i would definitely like to help,this will be my first contribution though so can i get a more clear idea on how to submit this.

**Comment by platinumazure** [comment]
@vibss2397 Awesome, we would love to see what you come up with! :smile: Start by taking a quick look at our [contributing guide](https://eslint.org/docs/developer-guide/contributing/), and please feel free to post here or come by our [Gitter chat](https://gitter.im/eslint/eslint) if you run into issues.

**Comment by kaicataldo** [comment]
@vibss2397 Thanks for looking at this! As @platinumazure said, please don't hesitate to reach out.

**Comment by vibss2397** [comment]
@platinumazure @kaicataldo just one last thing do i have to subkut the chabge as a rule change template or the way it is written in the docs or website

**Comment by kaicataldo** [comment]
@vibss2397 Sorry, I'm not sure I understand the question - mind explaining? The file to edit would be https://github.com/eslint/eslint/blob/master/docs/rules/no-restricted-modules.md, and to submit a PR you would follow the steps outlined in the [Contributing documentation](https://eslint.org/docs/developer-guide/contributing/pull-requests).

**Comment by vibss2397** [comment]
hey sorry for making this change so late,was busy,however do check it and tell if it was the thing you required.
