### ISSUE TITLE
no-unused-vars error

### ISSUE THREAD

**Issue by CatWithApple** [eslint/eslint#9459]
**Tell us about your environment**

* **ESLint Version: 4.9.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 5,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "no-unused-vars": 2
    },
    "env": {}
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
function test(a, b, c, d, e, f) { }
test();
```

**What did you expect to happen?**
1:15 - 'a' is defined but never used. (no-unused-vars)
1:18 - 'b' is defined but never used. (no-unused-vars)
1:21 - 'c' is defined but never used. (no-unused-vars)
1:24 - 'b' is defined but never used. (no-unused-vars)
1:27 - 'e' is defined but never used. (no-unused-vars)
1:30 - 'f' is defined but never used. (no-unused-vars)
**What actually happened? Please include the actual, raw output from ESLint.**
1:30 - 'f' is defined but never used. (no-unused-vars)

![screenshot-area-2017-10-16-160854](https://user-images.githubusercontent.com/4551350/31613688-84056bce-b28c-11e7-82fc-b52a27bcd903.png)

**Comment by ilyavolodin** [comment]
no-unused-vars defaults to `{ "args": "after-used" }` configuration, meaning only the last unused argument is going to be marked. If you want to check all of the arguments, please use the following configuration: `no-unused-vars: ["error", { "args": "all" }]`. For more information please see our [documentation](https://eslint.org/docs/rules/no-unused-vars#args).
