### ISSUE TITLE
discussion: replaced babelify with rollup/webpack

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9478]
+ babelify has some limitations ([babelify/issue#235](https://github.com/babel/babelify/issues/235)), and seems to be no longer maintained.
+ rollup/webpack is more future-proof, better perf, tree-shaking, etc.

so which one do you prefer? 🙉

**Comment by platinumazure** [comment]
For what it's worth, QUnit uses rollup to do a very simple transform/combine of ES6 to ES5/browser-friendly. I think we chose rollup because it was a lot simpler to configure.

That said, I'm also not convinced that we for sure need to move, since we don't officially support a browser build anyway.

**Comment by not-an-aardvark** [comment]
I'm fine with switching as long as I don't have to handle the configuration 😄 

It's possible we will also encounter issues with webpack related to dynamic `require` calls, since I think it handles those differently from browserify.

**Comment by kaicataldo** [comment]
I'm fine with either, though I'm personally more familiar with Webpack. As mentioned [here](https://github.com/eslint/eslint/pull/9460#pullrequestreview-71043286), we'll need to move away from `browserify` if we want to update to use `babel-preset-env`.

**Comment by kaicataldo** [comment]
Additionally, I don't think the Webpack configuration will be very complicated in this case, and I'd be happy to take that task on.

**Comment by not-an-aardvark** [comment]
Is this still something we want to do?

**Comment by Aladdin-ADD** [comment]
time is changing, perhaps we can reconsider parcel?

**Comment by Aladdin-ADD** [comment]
The author of rollup wrote a post to clarify the difference between rollup and webpack: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

> Use webpack for apps, and Rollup for libraries

I slightly prefer using rollup, if we only want to build ESLint package. But if we want to build assets for the site, webpack would be a better choice.

**Comment by kaicataldo** [comment]
I'm not against using Rollup, but I do have some concerns. From the same article:

> And perhaps the biggest pain point for people coming to Rollup — while it handles most CommonJS files (via a plugin), some things just don’t translate to ES2015, whereas webpack handles everything you throw at it with aplomb.

> If you need code-splitting, or you have lots of static assets, or you’re building something with lots of CommonJS dependencies, Webpack is a better choice. If your codebase is ES2015 modules and you’re making something to be used by other people, you probably want Rollup.

We aren't using ES2015 modules and we have a good number of dependencies, so I would want to make sure the above isn't a concern for us.

I'm also a lot bit confused -- the above seems like an argument for Rollup, but the [corresponding PR](https://github.com/eslint/eslint/pull/10390) is cutting over bundling to Parcel. @Aladdin-ADD Would you mind clarifying what you think the right way forward is here?

**Comment by Aladdin-ADD** [comment]
After thinking for a while, I'm not sure parcel is what we want -- we don't need most of these advanced features.


> We aren't using ES2015 modules and we have a good number of dependencies, so I would want to make sure the above isn't a concern for us.

Rollup can work well with CommonJS, though it can work better on ES modules. And some of ESlint deps can also support ESM(e.g.  acorn), so it might not be a concern for us.

I can open a PR if it being accepted. 😄
