### ISSUE TITLE
bug: multiline-comment-style incorrectly autofix (option separate-lines).

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9485]
**Tell us about your environment**

* **ESLint Version:**master

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
                "rules": {
                    "multiline-comment-style": [
                        2,
                        "separate-lines"
                    ]
                },


```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/* foo
 bar */qux;
```

**What did you expect to happen?**
```js
// foo
// bar
qux;
```
**What actually happened? Please include the actual, raw output from ESLint.**
```js
// foo
// barqux;
```

**Comment by gpiress** [comment]
I'd like to take a look at this one, but it might take a bit :)
