### ISSUE TITLE
Warn on non-existent files

### ISSUE THREAD

**Issue by HaleTom** [eslint/eslint#9494]
**Tell us about your environment**

```
$ eslint --version
v4.9.0
$ node --version
v8.5.0
$ npm --version
5.3.0
$ uname -a
Linux svelte 4.9.52-1-MANJARO #1 SMP PREEMPT Wed Sep 27 16:40:38 UTC 2017 x86_64 GNU/Linux
```

**What parser (default, Babel-ESLint, etc.) are you using?**
`default`

**Please show your full configuration:**
```
$ cat ~/.eslintrc 
extends: airbnb-base
eslint._legacyModuleResolve: true
eslint.nodePath: "/home/ravi/.config/yarn/global/node_modules/"
```
**What did you do? Please include the actual source code causing the issue.**

```
$ eslint non-existent-file
```

**What did you expect to happen?**
To receive a warning like: 
```
non-existent-file: does not exist
```

**What actually happened? Please include the actual, raw output from ESLint.**

Null output

**Comment by Aladdin-ADD** [comment]
Thanks for the report. This is working as intended -- see #7395.
