### ISSUE TITLE
can't redirect stdout when execute eslint via npm run

### ISSUE THREAD

**Issue by jare-talend** [eslint/eslint#9503]
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.5.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**

my package json :
```json
....
   "scripts": {
      "lint": "eslint src",
    }
....


```

**What did you expect to happen?**

npm run lint > /tmp/output
 triggers an error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lint: `eslint src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

0 info it worked if it ends with ok
1 verbose cli [ '/home/xxx/.nvm/versions/node/v8.5.0/bin/node',
1 verbose cli   '/home/xxx/.nvm/versions/node/v8.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle @~prelint: @
6 info lifecycle @~lint: @
7 verbose lifecycle @~lint: unsafe-perm in lifecycle true
8 verbose lifecycle @~lint: PATH: /home/xxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/bin/node-gyp-bin:/tmp/eslint/node_modules/.bin:/home/xxx/.nvm/versions/node/v8.5.0/bin:/opt/apache-maven-3.2.5/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~lint: CWD: /tmp/eslint
10 silly lifecycle @~lint: Args: [ '-c', 'eslint src' ]
11 silly lifecycle @~lint: Returned: code: 1  signal: null
12 info lifecycle @~lint: Failed to exec lint script
13 verbose stack Error: @ lint: `eslint src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/xxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/xxx/.nvm/versions/node/v8.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid @
15 verbose cwd /tmp/eslint
16 verbose Linux 4.4.0-97-generic
17 verbose argv "/home/xxx/.nvm/versions/node/v8.5.0/bin/node" "/home/xxx/.nvm/versions/node/v8.5.0/bin/npm" "run" "lint"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ lint: `eslint src`
22 error Exit status 1
23 error Failed at the @ lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**What actually happened? Please include the actual, raw output from ESLint.**

The result of this command should create a file /tmp/output with stdout

**Comment by not-an-aardvark** [comment]
Are you sure no `/tmp/output` file was created? If ESLint finds any linting errors, it exits with an exit code of 1. This would cause an error to get output to stderr like the one you've pasted, but the linting problems would still get reported and placed in `/tmp/output`.

If it still doesn't work you might be interested in the [`--output-file`](https://eslint.org/docs/user-guide/command-line-interface#-o---output-file) CLI flag.

**Comment by jare-talend** [comment]
Yes, i'm sure.

I saw the option --output-file but in my case, I want when we launch "npm run lint" normally, the result is on the terminal. In another case, we launch npm run lint, with travis for sample, get the result on a file by redirecting the output to a file without have 2 scripts on the package.json.

**Comment by not-an-aardvark** [comment]
I see there is this line in the output:

> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is there any additional logging output above that line that you've omitted, or is that the only logging output?

**Comment by not-an-aardvark** [comment]
Closing because there hasn't been a response in awhile -- feel free to create a new issue if you'er still having trouble.
