### ISSUE TITLE
output eslint version more than error output

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9507]
refs: #9486 

in v4.6.0, we added eslint version to error output (#9071). but it seems not ideal. version message is also important in some other cases:

* eslint config validation.(esp. rule option)
* multi-version eslint installed (e.g. gulp-eslint has its own depedent eslint)
* eslint --debug

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
