### ISSUE TITLE
Request: Extend `arrow-spacing` rule to support class properties

### ISSUE THREAD

**Issue by EvHaus** [eslint/eslint#9516]
I would like to extend the [`arrow-spacing` rule](https://eslint.org/docs/rules/arrow-spacing) to support class property functions. For example:

The following rule: `"arrow-spacing": ["error", {"before": true, "after": true}` should result in this change:

```js
// Before
class Test {
    test=()=>{ }
}

// After
class Test {
    test = () => { }
}
```

However, at the moment, the `arrow-spacing` seems to ignore class properties entirely. Is there any reason NOT to update the rule to support class properties?

<details>
<summary>Environment</summary>
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.8.0
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint
</details>

<details>
<summary>Configuration</summary>

```js
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
    "rules": {
        "arrow-spacing": ["error", {"before": true, "after": true}]
    }
}
```
</details>

**Comment by not-an-aardvark** [comment]
Hi,

Class properties are experimental syntax, and ESLint does not support experimental syntax in core rules. I would recommend checking if [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel) has a custom rule for this.
