### ISSUE TITLE
Appveyor build is flaky

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9533]
For the past few weeks, the Appveyor build has been occasionally been failing with messages like this:

![](https://i.gyazo.com/8cf6092eba37247dd56b0bcdd9123b8c.png)

It's not clear what's going on. (It says "no coverage files found", but I'm not sure why that's the case, or why it only happens sometimes.)

**Comment by not-an-aardvark** [comment]
The "ERROR: no coverage files found" message occurs when [this command](https://github.com/eslint/eslint/blob/8e1a095f4cc3b371a0a424b66e13ec77734193a2/Makefile.js#L570) is run and no `coverage/` folder was generated by the [above command](https://github.com/eslint/eslint/blob/8e1a095f4cc3b371a0a424b66e13ec77734193a2/Makefile.js#L564). However, I'm not sure why that would be happening.

**Comment by Aladdin-ADD** [comment]
it was occasionally and I've never seen it in my local, so I guess it might be related to mocha timeout. can we set it to be bigger to see if it happens again?

**Comment by not-an-aardvark** [comment]
I noticed that the error usually happens when the progress bar is at this stage:


[▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬..]

I think that's the point where the tests in [`tests/bin/eslint.js`](https://github.com/eslint/eslint/blob/master/tests/bin/eslint.js) tests run. It makes sense that the `tests/bin/eslint.js` tests could be causing the problem, because:

* Those tests run other processes, which could have odd side-effects
* Those tests take longer than other tests

**Comment by not-an-aardvark** [comment]
I don't think the issue is a timeout, because when I apply this diff:

```diff
diff --git a/tests/bin/eslint.js b/tests/bin/eslint.js
index 7742eb71..830672e5 100644
--- a/tests/bin/eslint.js
+++ b/tests/bin/eslint.js
@@ -46,7 +46,9 @@ function getOutput(runningProcess) {
     return awaitExit(runningProcess).then(() => ({ stdout, stderr }));
 }
 
-describe("bin/eslint.js", () => {
+describe("bin/eslint.js", function() {
+    this.timeout(200); // eslint-disable-line no-invalid-this
+
     const forkedProcesses = new Set();
 
     /**

```

...I get a bunch of error messages that the test timed out. On Appveyor, there are no error messages.

**Comment by not-an-aardvark** [comment]
It's also interesting that the test bar *stops* at [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬..] and it never reaches the end, and then the "ERROR: no coverage files found" is printed immediately afterwards. Under normal circumstances, a `coverage/` folder is created after the tests finish, and then `istanbul check-coverage` is run to verify the coverage. If the `coverage` folder doesn't have any coverage info yet (e.g. because the tests are still running), then istanbul will output "ERROR: no coverage files found".

So my guess is that when we do `child_process.fork()` in `tests/bin/eslint.js` and then the forked process stops, somehow that is getting interpreted as if the parent test process stopped, so the `Makefile.js` script continues even though the tests haven't finished.

**Comment by not-an-aardvark** [comment]
Looks like this is still a problem (e.g. the build failed for https://github.com/eslint/eslint/pull/9589)

**Comment by not-an-aardvark** [comment]
Should this be closed? I haven't seen the build fail for awhile.

**Comment by ilyavolodin** [comment]
I think it's fine to close it. Occasional errors in the build happens. We've had them on Travis during last release, for example. I don't think there a way to completely eliminate them. As long as they are within reasonable boundaries, we just have to live with them.
