### ISSUE TITLE
Scheduled release for November 10th, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9546]
The scheduled release on Friday, November 10th, 2017 is assigned to:

* @ilyavolodin
* @kaicataldo 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

Resources:

* [Release guidelines](https://eslint.org/docs/maintainer-guide/releases)

**Comment by not-an-aardvark** [comment]
This release process should also involve doing a release of `espree` and upgrading the version in ESLint's `package.json`, to fix https://github.com/eslint/eslint/issues/9536.

**Comment by Aladdin-ADD** [comment]
`doctrine` also has some bugfixes, maybe need a release?

**Comment by kaicataldo** [comment]
Espree v3.5.2 and ESLint v4.11.0 have been released.

We had problems releasing Doctrine, and will revisit in the near future.

@eslint/eslint-team Please only merge semver-patch PRs until we have evaluated whether we need to do a patch release next Monday.

**Comment by kaicataldo** [comment]
It does not appear we need to do a patch release today. This concludes this release cycle. Please feel free to merge semver-minor PRs again.
