### ISSUE TITLE
Parsing error: Unexpected token when using union types in TypeScript

### ISSUE THREAD

**Issue by ibufu** [eslint/eslint#9549]
**Tell us about your environment**

* **ESLint Version:** 3.19
* **Node Version:** 8.2.1
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": "./node_modules/eslint-config-elemefe/index.js",
  "plugins": ["vue"],
  "env": {
    "es6": true,
    "browser": true
  },
  "globals": {
    "AMap": true,
    "lazyAMapApiLoaderInstance": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
}



```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
data() {
    return {
      form: {
        startDate: <Date | undefined> undefined
      }
    };
}
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
  ✘  http://eslint.org/docs/rules/  Parsing error: Unexpected token
          startDate: <Date | undefined> undefined
```

**Comment by Aladdin-ADD** [comment]
I don't think babel-eslint support typescript, you can use `typescript-eslint-parser`.

**Comment by ibufu** [comment]
@Aladdin-ADD There is the same issue with typescript-eslint-parser.

**Comment by ibufu** [comment]
It works as
```js
startDate: <undefined> undefined
```
fail when:
```
startDate: <Date | undefined> undefined
```

**Comment by not-an-aardvark** [comment]
If that's valid typescript and it's not parsing with `typescript-eslint-parser`, I would recommend filing an issue on the [`typescript-eslint-parser` repo](https://github.com/eslint/typescript-eslint-parser).

**Comment by Aladdin-ADD** [comment]
closing, as it seems not ESLint's issue.
