### ISSUE TITLE
Allow new scopes to be generated and variables/scopes to be added to existing scopes

### ISSUE THREAD

**Issue by isiahmeadows** [eslint/eslint#9550]
I know this is a bit of an unusual request, but I'd like a way to inject variables into scopes so `no-undef` doesn't complain over their presence. This would come into use the most with Babel-related code gen stuff, such as with [`babel-macros`](https://github.com/kentcdodds/babel-macros) and [`babel-plugin-macros`](https://github.com/codemix/babel-plugin-macros). Also, it'd open the door to a potential Sweet.js parser/plugin combo similar to `eslint-parser-typescript`, since Sweet.js can generate bindings and scopes in places JS would otherwise consider invalid.

(It also may necessitate having `eslint-scope` further deviate from `escope`.)

**Comment by not-an-aardvark** [comment]
Would this be solved by https://github.com/eslint/eslint/pull/8755 ?

**Comment by isiahmeadows** [comment]
Yes.

**Comment by isiahmeadows** [comment]
I'll close this as a dupe of #8392.
