### ISSUE TITLE
Document how to use a plugin with Node API

### ISSUE THREAD

**Issue by slorber** [eslint/eslint#9551]
Hi,

I am reading the doc of the Node API but I am unable to understand how I am supposed to load a plugin in my ESLint config.

Purpose:
- I have a string input (memory, no file)
- I want to run ESLint --fix on this string input with Node API (no cli)
- My ESLint config need to load plugins (eslint-react)
- I want to output a string (memory, no file)

This method does the job well for core rules: https://eslint.org/docs/developer-guide/nodejs-api#linterverifyandfix

But I have no idea how can I load plugins. ESLint says that definition of rules is not found.

The method takes a configuration object:

> config - a configuration object that has been processed and normalized by CLIEngine using eslintrc files and/or other configuration arguments.
> Note: If you want to lint text and have your configuration be read and processed, use CLIEngine’s executeOnFiles or executeOnText instead.

It is not clear to me how to get this configuration object from `CLIEngine` and to normalize it.

Any additional example in the doc would be welcome

**Comment by mysticatea** [comment]
Thank you for this issue.

I guess you can use [`CLIEngine#executeOnText`](https://eslint.org/docs/developer-guide/nodejs-api#executeontext) method.

```js
const eslint = require("eslint")
const engine = new eslint.CLIEngine({ fix: true })
const report = engine.executeOnText(yourCode, yourFilePathOptionally) // eslintrc is loaded automatically. Plugins also.
const result = report.results[0]

console.log(result.messages) // errors which were not fixed.
console.log(result.output)   // fixed code.
```

If you want to do without `.eslintrc` file:

```js
const eslint = require("eslint")
const engine = new eslint.CLIEngine({
    fix: true,
    useEslintrc: false,
    plugins: [
        //...
    ],
    rules: {
        //...
    },
})
const report = engine.executeOnText(yourCode, yourFilePathOptionally) // eslintrc is loaded automatically. Plugins also.
const result = report.results[0]

console.log(result.messages) // errors which were not fixed.
console.log(result.output)   // fixed code.
```

**Comment by slorber** [comment]
thanks :) it seems to work fine this way

**Comment by platinumazure** [comment]
@slorber Do you believe we need to improve our documentation, based on what you saw there and what mysticatea posted? We'd be happy to reopen this issue if so.

**Comment by slorber** [comment]
Hi,

Yes this would be helpful to improve doc I guess, at least mention that `verify` / `verifyAndFix` should be replaced by `cli.executeOnText` if using plugins is required

**Comment by platinumazure** [comment]
Thanks for the feedback. I think what you're suggesting can be generalized
to this: If you have a fully normalized configuration you can use
linter.verifyAndFix, but for anything that involves reading configuration
or loading plugins, it works better to use the CLIEngine methods.

To be completely honest, I don't even fully understand the use case for
using Linter directly. I find it much easier to work with CLIEngine.

**Comment by slorber** [comment]
@platinumazure I don't know either, this came first in doc order and api seemed simpleto use so I tried ;)
