### ISSUE TITLE
Docs: not shown supporting json5

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9558]
is eslint config supporting json5?
I found it is very useful to users, but not shown in the docs.

**Comment by not-an-aardvark** [comment]
No, I don't think ESLint supports json5.

**Comment by Aladdin-ADD** [comment]
I see. I'm using `.eslintrc`, which support some json5 features.(like single-quoted string, unquoted object keys). while `.eslintrc.json` do not support these features.

https://github.com/eslint/eslint/blob/cc2c7c9380368658add0daccad73c2cc7fd94509/lib/config/config-file.js#L136
