### ISSUE TITLE
Async class method Unexpected token

### ISSUE THREAD

**Issue by bm-stschneider** [eslint/eslint#9572]
**Tell us about your environment**

* **ESLint Version: 4.10.0**
* **Node Version: v.8.9.0**
* **npm Version: 5.5.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js



```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class test {
	constructor(){
    	this.help();
    }
  
  async help() {
  	const bla = await this.hello();
  }
  
  hello() {
  	return setTimeout(() => console.log('1'), 3000);
  }
}

new test();
```

```bash
REPL
```

**What did you expect to happen?**
No error.

**What actually happened? Please include the actual, raw output from ESLint.**
Parsing error: Unexpected token help

**Comment by mysticatea** [comment]
Thank you for the issue.

If you don't have configuration file, you need to create it.
ESLint parses source codes in ES5 mode by default. You can configure it via configuration file. For example:

```json
// .eslintrc.json
{
    "parserOptions": {
        "ecmaVersion": 2017
    }
}
```

**Comment by bm-stschneider** [comment]
I used https://eslint.org/demo/ with ECMA Version 7.

**Comment by mysticatea** [comment]
Async functions have been added in ES2017 (ecmaVersion 8) :smile:

**Comment by bm-stschneider** [comment]
Okay thank you. I always get confused with versions these days.
