### ISSUE TITLE
Ignoring certain strings

### ISSUE THREAD

**Issue by TomYeoman** [eslint/eslint#9579]
Hi all, I have string templates in my work codebase which looks like this

        <h3 class='visible-xs hidden-sm hidden-md hidden-lg'>Step 3. Absence type</h3>
        <table class='table responsive-stacked-table'>
            <thead>
                <tr class='rowheader'>
                    <th colspan=2>Step 3. Absence type</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-label='Reasons'>
                        Reasons
                    </td>
                    <td class='text-left'>
                        <select id="absence-reason-dropdown" class="form-control" >
                        ${
							[...absenceReasonNodes].map((dataItem, index) =>
                                `<option value="${responseGetChildNodeValue(absenceReasonNodes, index, 'AbsenceCode')}" ${responseGetChildNodeValue(absenceReasonNodes, index, 'AbsenceCode') === chosenReasonCode ? 'selected' : ''} >
                                    ${responseGetChildNodeValue(absenceReasonNodes, index, 'AbsenceDescription')}
                                </option>`,
                            )
                        }
                        </select>
                    </td>
                </tr>
                <tr>

eslint complains that this code block is incorectly indented  ( it should be sitting with no tabbing )

`                        ${
				[...absenceReasonNodes].map((dataItem, index) =>
                                <option value="${responseGetChildNodeValue(absenceReasonNodes, index, 
                                </option>,
                            )
                        }`

We've using a legacy codebase so quite a lot of strings are formatted in this way ( Indenting in multi line strings in order to create HTML templates)

Is it possible to ignore the indentation rule just for backtick strings?

Thanks!

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue. Please feel free to create a new issue and fill out the [bug report template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md).
