### ISSUE TITLE
Feature request: --silent flag

### ISSUE THREAD

**Issue by jmeas** [eslint/eslint#9597]
Hi there!

I was wondering if there was a way to silence all output from ESLint. Warnings, errors – all of it. I see that there's a `--quiet` flag, but that only stops warnings.

One idea would be to write a custom reporter that simply outputs nothing, but that seems a little roundabout. Another idea I had would be sending the output to a file such as `/dev/null`, or some other file that gets cleaned up. This also seems roundabout.

Is there a way to do this already that I'm missing?

If not, would you be open to introducing a new `--silent` flag?

The reason for this request is that I want the exit error status, but no other output.

Thanks for reading!

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. Could you clarify what would be wrong with sending the output to `/dev/null`? I think that's the usual way to silence a command, so it doesn't seem roundabout to me.

**Comment by jmeas** [comment]
It feels a little roundabout to me because it's too platform-specific, @not-an-aardvark . I suppose I could write or find an npm module that looks around for a per-platform location to send it off to, but that feels a little less than ideal than just making eslint not log anything, which works on every OS.

This solution would work, though, so if that's what you recommend doing, then I can do that. ESLint has been around forever, and since it seems that nobody else has asked for it, I suppose it's a niche need. Thanks for the quick reply!

**Comment by platinumazure** [comment]
I'm slightly :-1: because this seems like something that has plenty of workarounds (custom formatter, redirect output, etc.).

**Comment by j-f1** [comment]
This could be implemented as a core `--formatter silent` option. Would a PR for this be accepted?

**Comment by platinumazure** [comment]
@j-f1 I'm not opposed since hopefully that formatter will have very little logic and no real maintenance cost. But I don't know if the rest of the team will feel the same.

Would you mind creating a new issue with that specific proposal, so we can evaluate it in its own context? Thanks!

**Comment by jmeas** [comment]
I found a workaround for what I was trying to do, so I no longer need this feature. Feel free to close this issue if nobody else has a use case for it :v:

**Comment by not-an-aardvark** [comment]
Closing since it seems like there's not much interest in implementing it and the OP found a workaround.
