### ISSUE TITLE
prefer-destructuring error raised in a case I cannot use destructuring

### ISSUE THREAD

**Issue by pandaiolo** [eslint/eslint#9601]
**Tell us about your environment**

* **ESLint Version:** 4.10
* **Node Version:** 8.7.0
* **npm Version:** 5.5.1, yarn 1.1.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint@8.0.2

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true
    },
    sourceType: 'module'
  },
  settings: {
    'import/resolver': {
      node: {
        moduleDirectory: ['app/javascript', 'node_modules']
      }
    }
  },
  plugins: ['import', 'react', 'prettier'],
  extends: [
    'eslint:recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:react/recommended',
    'airbnb',
    'prettier'
  ],
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true
  },
  rules: {
    'no-unused-expressions': [
      'error',
      { allowShortCircuit: true, allowTernary: true }
    ],
    camelcase: 'warn',
    'class-methods-use-this': 'off',
    'import/prefer-default-export': 'off',
    'jsx-a11y/label-has-for': [
      'error',
      { required: { some: ['nesting', 'id'] } }
    ],
    'jsx-a11y/anchor-is-valid': [
      'error',
      {
        components: []
      }
    ],
    'jsx-a11y/no-noninteractive-element-interactions': 'warn',
    'no-console': 'off',
    'no-shadow': 'off',
    'no-use-before-define': ['error', { functions: false }],
    'react/forbid-prop-types': 'off',
    'react/jsx-closing-bracket-location': 'off',
    'react/require-default-props': 'off',
    'react/sort-comp': 'off'
  },
  globals: {
    noop: false,
    shallow: false,
    mount: false,
    expect: false,
    expectToContain: false,
    fullMount: false,
    fullShallow: false
  }
}


```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let val
try {
  // [.. some code..]
  // This reports eslint prefer-destructuring error
  val = obj.val
  // [...some other code..]
}  catch() {
  // something went wrong, report the value of val
  console.error('blabla', val)
}
```

```bash
I just use sublime text eslint plugin
```

**What did you expect to happen?**

No error reported, because I cannot use destructuring in that use case. Or maybe I'm doing it wrong?

**What actually happened? Please include the actual, raw output from ESLint.**

`prefer-destructuring` error reported

**Comment by platinumazure** [comment]
You need to parenthesize the expression:

```js
({ val } = obj);
```

Without parentheses, the language grammar requires the interpreter to try to interpret the braces as the start/end of a block.

**Comment by pandaiolo** [comment]
ok thanks for the explanation!

And sorry I just found this when about to ask about option to excude this use case https://github.com/eslint/eslint/issues/7886 ... already replied :)

**Comment by kholiavko-roman** [comment]
I have a problem with `prefer-destructuring` options.
```
const driverId = this.props.appState.driverId;
const messages = this.props.messages;
```
In this case linter show me error, but I cant assign exactly driverId from my pops.appState.
