### ISSUE TITLE
Transfarring eslint-cli to eslint organization

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#9602]
[eslint-cli] is the package which provides CLI command `eslint` which finds local-installed ESLint and runs it. I would like to transfer [eslint-cli] to [eslint organization](https://github.com/eslint).

I think that [eslint-cli] improves https://github.com/eslint/eslint/issues/6732#issuecomment-340708991 with updating "Getting started" page. This transferring would make peace of mind as the tool is supported by the eslint team.

Also, I think that we can move `--init` feature to [eslint-cli]. It lets us separate some dependencies that linting does not use.

[eslint-cli]: https://github.com/mysticatea/eslint-cli

**Comment by platinumazure** [comment]
This would probably require a TSC motion to accept, and it would definitely require input from the JSF to make sure all the copyright is transitioned successfully (or else explicitly not assumed by the ESLint project, similar to what we did for eslint-canary).

I'm generally :+1: to this idea, both because it would help resolve our most commonly asked question and because it would allow us to move some dependencies. That said, my guess is this would definitely have to be semver-major.

**Comment by not-an-aardvark** [comment]
Would the plain `eslint` package still be runnable from the command line if we recommend `eslint-cli`?

It seems like the a goal of this change is to reduce user confusion about local/global installations. But if a user doesn't understand the difference between local and global installations, they might not understand why they need `eslint-cli`, because `eslint` would seem to work on its own.

(I don't think we could realistically remove command-line support for `eslint` on its own, because almost all users depend on it.)

**Comment by mysticatea** [comment]
I don't worry about copyrights because all commits of `eslint-cli` are mine and all dependencies are MIT license.

> Would the plain eslint package still be runnable from the command line if we recommend eslint-cli?

Yes, I think so. Running via npm-scripts is a popular use case, and npm-scripts should not depend on global-installed packages.

For the explanation to users, I can say:

1. In dependency management perspective, it's important that ESLint entity is in project-local. There are multiple option to run it; long command (e.g. `.\node_modules\.bin\eslint`), npm-scripts, editor integrations, or via Node API. Also, If you want to use the short command `eslint` on your terminal, `eslint-cli` in global is a good option (another option is `PATH` management for each project).
2. Two instances (global and project-local) cause confusing which is running. ESLint is getting new rules/options/syntax in each minor update, so it's important that people are sure which is running now.

Additionally, I think `eslint` command can check whether itself is in global or project-local. Maybe with `require.resolve("eslint", {paths: [process.cwd()]})` is itself or not. It can report a warning "ESLint recommend to install into project-local".

**Comment by platinumazure** [comment]
Could we provide the option and then see if users want it to become the
main CLI in the future? Then we could make eslint-cli the main CLI in a
later major release if user feedback is positive and we remove any
inconsistencies or bugs.

**Comment by mysticatea** [comment]
**TSC Summary:**

[eslint-cli] is the package which provides CLI command `eslint` which finds local-installed ESLint and runs it. I would like to transfer [eslint-cli] to [eslint organization](https://github.com/eslint).
I think that [eslint-cli] improves https://github.com/eslint/eslint/issues/6732#issuecomment-340708991 with updating "Getting started" page. This transferring would make peace of mind to users as the tool is supported by the eslint team.

I don't worry about copyrights because all commits of eslint-cli are mine and all dependencies are MIT license.

**TSC Question:**

Do we accept this proposal?

[eslint-cli]: https://github.com/mysticatea/eslint-cli

**Comment by not-an-aardvark** [comment]
There was an internal discussion about this in `@eslint/eslint-team`. As discussed in today's TSC meeting (and with the consent of everyone involved in the discussion), I'm posting it publicly:

![global_local_installation_discussion](https://user-images.githubusercontent.com/11638619/34282299-46c53a48-e692-11e7-9caf-c85157d825e0.png)

**Comment by kaicataldo** [comment]
This was discussed at today's TSC meeting. The TSC resolved to move `eslint-cli` into the `eslint` organization and gather feedback from users to determine whether or not we should officially recommend it

**Comment by mysticatea** [comment]
Thank you. I have done transferring it: https://github.com/eslint/eslint-cli

**Comment by platinumazure** [comment]
Do we need to inform the JSF? (We could link to [this comment](https://github.com/eslint/eslint/issues/9602#issuecomment-343642988) to show that mysticatea consents to his contributions being used here, but I don't know if they might have more formal paperwork around this.

**Comment by not-an-aardvark** [comment]
cc @kborchers

**Comment by kborchers** [comment]
As mentioned in https://github.com/eslint/eslint-canary/issues/9 (and admittedly we still need better docs and I have that on my list for my next meeting with the TAC), the JSF needs to be involved before the transfer takes place. That said, this is luckily a similar situation and an update of the copyright statement to "Copyright contributors" by @mysticatea like we did for eslint-canary is all that's left to finish the transfer.

The reason it is important to ping us before a transfer is that as soon as the repo enters the eslint org, it falls under our CLA checker which is technically not a correct representation to any contributor licensing their contribution if the copyrights, etc are incorrect. It's a minor thing that likely wouldn't result in any issue but our goal is to keep projects from falling into a situation where it did matter. ;)

**Comment by mysticatea** [comment]
Thank you. I opened PR to update LICENSE file: https://github.com/eslint/eslint-cli/pull/6

**Comment by not-an-aardvark** [comment]
Closing because the transfer is complete and the license has been updated.
