### ISSUE TITLE
Should we rename "beginner" label to "good first issue"?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#9609]
**TSC Summary**:

Per [this article](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/) on GitHub Help, it seems that GitHub is flagging issues with the "help wanted" or "good first issue" label for new contributors.

We're already using "help wanted", and "beginner" seems semantically equivalent. So I'd like to propose changing the label from "beginner" to "good first issue" to take advantage. (Also, as a small side benefit, it avoids any risk that the "beginner" label could seem pejorative to someone who has experience coding but has not contributed to this repository before.)

**TSC Question**:

Should we do this for the ESLint repo? Should we do this for other repos in the ESLint organization?

**Comment by alberto** [comment]
@platinumazure assuming you also want this, I think we can accept it right away.

**Comment by platinumazure** [comment]
It wouldn't hurt to bring it up in the meeting to make sure of no objections (under consensus-seeking model, majority vote is supposed to be last resort). But I'm :+1: for this and certainly won't object if we make the switch.

**Comment by not-an-aardvark** [comment]
This was accepted in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/3ef527b67712b5cecd0e2231dfb1a8a59a052155/notes/2017/2017-12-07.md#should-we-rename-beginner-label-to-good-first-issue). I just updated the label, so I'm closing this issue.
