### ISSUE TITLE
Support yarn default if exist yarn.lock or init command with a flag?

### ISSUE THREAD

**Issue by pierreneter** [eslint/eslint#9610]
**Tell us about your environment**

* **ESLint Version:** v4.9.0
* **Node Version:** v9.1.0
* **npm Version:** v5.5.1

**What did you expect to happen?**

`eslint --init` with `yarn install` dependencies.
of `eslint --init --yarn`

**Comment by pierreneter** [comment]
@not-an-aardvark it's just a requirement of the feature. Can select the way to install dependencies eslint need to work.

**Comment by platinumazure** [comment]
Hi @pierreneter, thanks for the issue!

I think we already discussed this in #9023 and the team decided not to accept the proposal there.

I'm going to close this for now, but please do comment here or in the other issue if there's a factor we missed in the last discussion that would justify reconsidering the proposal.
