### ISSUE TITLE
Semi colon added on new line with auto fix.

### ISSUE THREAD

**Issue by vim2meta** [eslint/eslint#9615]
**Tell us about your environment**

* **ESLint Version:4.11.0**
* **Node Version:8.8.1**
* **npm Version:5.5.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "node": true,
    "es6": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "rules": {
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "linebreak-style": "off",
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ],
    "no-unused-vars": [
      "error",
      {
        "args": "none"
      }
    ],
    "eqeqeq": [
      "error",
      "always"
    ],
    "no-multiple-empty-lines": [
      "error",
      {
        "max": 1
      }
    ],
    "yoda": [
      "error",
      "never"
    ],
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "one-var-declaration-per-line": [
      "error",
      "always"
    ],
    "space-before-function-paren": [
      "error",
      {
        "named": "never"
      }
    ],
    "multiline-ternary": [
      "error",
      "never"
    ],
    "no-empty": [
      "error",
      {
        "allowEmptyCatch": true
      }
    ],
    "padded-blocks": [
      "error",
      "never"
    ],
    "quote-props": [
      "error",
      "as-needed"
    ],
    "no-shadow": [
      "error",
      {
        "builtinGlobals": true
      }
    ],
    "one-var": [
      "error",
      "never"
    ],
    "dot-location": [
      "error",
      "property"
    ],
    "array-bracket-spacing": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-implicit-coercion": "error",
    "no-new-func": "error",
    "no-return-assign": "error",
    "no-sequences": "error",
    "no-return-await": "error",
    "no-self-compare": "error",
    "no-useless-return": "error",
    "no-useless-concat": "error",
    "no-useless-call": "error",
    "no-nested-ternary": "error",
    "no-path-concat": "error",
    "no-new-require": "error",
    "no-new-wrappers": "error",
    "no-floating-decimal": "error",
    "no-with": "error",
    "no-multi-spaces": "error",
    "block-spacing": "error",
    "brace-style": "error",
    "curly": "error",
    "comma-dangle": "error",
    "comma-spacing": "error",
    "no-mixed-operators": "error",
    "no-lonely-if": "error",
    "no-lone-blocks": "error",
    "no-array-constructor": "error",
    "no-useless-constructor": "error",
    "no-multi-assign": "error",
    "no-new-object": "error",
    "no-trailing-spaces": "error",
    "no-unneeded-ternary": "error",
    "no-invalid-this": "error",
    "no-void": "error",
    "operator-assignment": "error",
    "spaced-comment": "error",
    "space-before-blocks": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "arrow-spacing": "error",
    "key-spacing": "error",
    "switch-colon-spacing": "error",
    "eol-last": "error",
    "no-console": "off",
    "guard-for-in": "error",
    "no-undef-init": "error",
    "no-use-before-define": "error",
    "keyword-spacing": "error",
    "no-loop-func": "error",
    "no-label-var": "error",
    "dot-notation": "error",
    "no-extra-label": "error",
    "prefer-promise-reject-errors": "error",
    "arrow-parens": "error"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const a = 5
```

```bash
eslint --fix test.js
```

**What did you expect to happen?**
I expected a semicolon to be added at the end of the line.

**What actually happened? Please include the actual, raw output from ESLint.**
A semi colon was added on the next line that was created by the rule `eol-last`. When the rules `eol-last` and `semi` are not respected on the same line, the auto fix will put a semi colon on the new line it creates at the end of file, instead of at the end of the statement. This issue started happening since I upgraded to 4.11.0. Downgrading to 4.10.0 fixes the issue.

File after running the eslint command:
```js
const a = 5
;

```

**Comment by Aladdin-ADD** [comment]
thanks for the report! however, I was not able to repro it, could you repro it in [eslint demo](https://eslint.org/demo), please?

**Comment by ilyavolodin** [comment]
I also can't reproduce this issue with the config you provided. However, if it's happening, it's most likely the result of the auto-fixer for `semi-style` kicking in. Could you run `eslint --print-config yourfile.js` and see what `semi-style` is set to? This is most likely due to https://github.com/eslint/eslint/commit/7e3bf6a

**Comment by vim2meta** [comment]
@ilyavolodin `semi-style` is set to off. Here is the full output of `eslint --print-config test.js`: https://pastebin.com/raw/PNzK4DZL.

**Comment by mysticatea** [comment]
I could not reproduce this with your configuration in the post.

A side note, `semi-style` handles the semicolons between two statements. It does not touch one at the last of statement list.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
