### ISSUE TITLE
Functional programming and getJSDocComment method

### ISSUE THREAD

**Issue by mrmlnc** [eslint/eslint#9617]
**Tell us about your environment**

* **ESLint Version:**  `4.11.0`
* **Node Version:** `8.9.0`
* **npm Version:** `5.5.1`

#### The problem

> **Disclaimer**
>
> I understand that is non-trivial issue. Also I understand that `var a = pkg.method()` and `var a = R.method()` has same AST, but... feel free to close :)

So, I'm using [Ramda](http://ramdajs.com) (functional library) in my project. In some cases ESLint does not check my JSDoc. Gradually, I began to understand what could be the problem. And I found the following situation.

My code:

```js
/**
 * Description.
 *
 * @function
 * @param {Object} document
 * @returns {string[]}
 */
var getSections = R.propOr([], 'sections');

// Call
var sections = getSections({ sections: ['first'] });
```

At first I looked at the generated AST from your site:

<details>
<summary>AST from ESLint parser</summary>

```json
{
  "type": "Program",
  "start": 0,
  "end": 63,
  "body": [
    {
      "type": "VariableDeclaration",
      "start": 23,
      "end": 63,
      "declarations": [
        {
          "type": "VariableDeclarator",
          "start": 27,
          "end": 62,
          "id": {
            "type": "Identifier",
            "start": 27,
            "end": 35,
            "name": "getSections"
          },
          "init": {
            "type": "CallExpression",
            "start": 38,
            "end": 62,
            "callee": {
              "type": "MemberExpression",
              "start": 38,
              "end": 46,
              "object": {
                "type": "Identifier",
                "start": 38,
                "end": 39,
                "name": "R"
              },
              "property": {
                "type": "Identifier",
                "start": 40,
                "end": 46,
                "name": "propOr"
              },
              "computed": false
            },
            "arguments": [
              {
                "type": "ArrayExpression",
                "start": 47,
                "end": 49,
                "elements": []
              },
              {
                "type": "Literal",
                "start": 51,
                "end": 61,
                "value": "sections",
                "raw": "'sections'"
              }
            ]
          }
        }
      ],
      "kind": "var"
    }
  ],
  "sourceType": "module"
}
```
</details>

From AST I understand that `R` has `MemberExpression` type and variable definition has `CallExpression` type.

I read the ESLint code and see that [`getJSDocComment`](https://github.com/eslint/eslint/blob/master/lib/util/source-code.js#L310-L344) method has no `case` for `MemberExpression` or `CallExpression`.

It turns out that some JSDoc never been tested. Well, any idea for this issue? :)

#### My idea

We can prefer `@function` directive in comments above `MemberExpression` or `CallExpression`?

If provided `@function` then `getJSDocComment` returns `JSDoc` :P

```js
/**
 * @function
 * @param {Object} document
 * @returns {string[]}
 */
var getSections = R.propOr([], 'sections');
```

But in this case it is possible to break the behavior of the current plugins for ESLint.

#### Test bench

Without configuration. I use the follow code in the ESLint repository to explain the problem:

```js
const sourceCode = require('./lib/util/source-code');
const Linter = require('./lib/linter');

const linter = new Linter();

const code = [
    "/** Description */",
    "var getSections = R.propOr([], 'sections');"
].join("\n");

linter.defineRule('checker', () => ({
    MemberExpression: (node) => {
        const sourceCode = linter.getSourceCode();
        const jsdoc = sourceCode.getJSDocComment(node);

        console.dir(jsdoc, { colors: true });
    }
}));

const res = linter.verify(code, { rules: { checker: "error" } });

console.log(res);
```

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
