### ISSUE TITLE
Defining class in a separate file causes '(..) is defined but never used'

### ISSUE THREAD

**Issue by awegrzyn** [eslint/eslint#9619]
* **ESLint Version: 4.11.0**
* **Node Version: 8.3.0**
* **npm Version: 5.5.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
Default
<details>
<summary>Configuration</summary>

```js
module.exports = { 
  "root": true,
  "extends": ["eslint:recommended", "google"],
  "env": {
    "es6": true,
    "node": true,
    "jquery" : true,
    "browser": true,
    "mocha": true
  },  
  "globals": {
    "Promise": true
  },  
  "parserOptions": {
    "ecmaVersion": 6
  },  
  "rules": {
    "max-len": ['error', {code: 100}], // default 80
    "indent": ['error', 2, {"SwitchCase": 1}], // not set by default
    "comma-dangle": ["error", "never"], // do not enforce trailing comma
    "curly": [2, "all"], // enfornce curly braces even in single line if-else
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class Test {}
```

```bash
./node_modules/.bin/eslint test.js
```
**What did you expect to happen?**
No error

**What actually happened? Please include the actual, raw output from ESLint.**
1:7  error  'Test' is defined but never used  no-unused-vars

**Comment by ilyavolodin** [comment]
What do you do with this class after you define it? Are you using CommonJS or ES6 modules? If you are, then the file requires either `module.exports` or `export`. If you are not, then you might have to turn off this rule, since ESLint doesn't know what to do with this class you just declared.

**Comment by awegrzyn** [comment]
Hi @ilyavolodin,
I just included in HTML file, I'm not using ES6 modules. I'll turn off this rule.

**Comment by platinumazure** [comment]
If you're not using ES6 modules or CommonJS modules, you could also include this comment somewhere in the file:

```js
/* exported Test */
```

Which will tell the rule that you're using the Identifier in a different file via script concatenation or similar.
