### ISSUE TITLE
Chore: use cosmiconfig to load config

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9637]
refs: https://github.com/davidtheclark/cosmiconfig

`cosmiconfig` is used by several oss to load config, it can load from

+ `package.json`
+ `rc`
+ `.config.js`

**Comment by not-an-aardvark** [comment]
It doesn't seem like this cosmiconfig supports all of our config files features, so I don't see how this would work. Am I missing something?

**Comment by sudo-suhas** [comment]
+1 to what @not-an-aardvark said. For example, [`eslint` supports cascading configuration files](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) but `cosmiconfig` does not.

Snippet from the [readme](https://github.com/davidtheclark/cosmiconfig#differences-from-rc):
> - Stops at the first configuration found, instead of finding all that can be found up the directory tree and merging them automatically.

**Comment by davidtheclark** [comment]
> It doesn't seem like this cosmiconfig supports all of our config files features

It may not have to. Seems to me that the key question is whether outsourcing whatever functionality cosmiconfig *does* support would be worth it. And then, whether cosmiconfig is extensible in the right ways so you can add your custom functionality on top. I could imagine a cascading system being built on top of cosmiconfig, for example.

Maybe that would work. However, ESLint's config loading system has been in place for such a long time and is so thoroughly battle-tested —— sounds scary to change it 😬

**Comment by Aladdin-ADD** [comment]
thanks for the explanation, totally agreed!
