### ISSUE TITLE
new rule: Prefer using async/await instead of Promise.prototype.then/catch/finally

### ISSUE THREAD

**Issue by dnalborczyk** [eslint/eslint#9649]
In our company we have an _unwritten_ rule to use **async functions**, instead of **Promise.prototype.then/catch/finally** with the advantage of having synchronous code with an asynchronous control flow. I believe that Promises are also harder to gasp for beginners, and require quite a bit of discipline, and are also prone to many misunderstandings in the order of execution and resolution, including discouraged patterns, e.g. .then(onFulfilled[, onRejected]).

in addition, performance of async functions is also on par with Promises now (https://v8project.blogspot.com/2017/02/v8-release-57.html)

we also encourage to wrap callbacks from third party modules and return Promises, if applicable (does not apply to events etc.), but that's a different story...

**Please describe what the rule should do:**

Disallows the usage of Promise.prototype.then/catch/finally, and suggest to use async/await instead. I would leave the static methods (all, race, reject, resolve) to be allowed - if one doesn't like those for whichever reason, one could just disallow the global Promise object with no-restricted-globals.

the idea might be the same (or similar) to:
https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/prefer-async-await.md
https://github.com/avajs/eslint-plugin-ava/blob/master/rules/prefer-async-await.js

**What category of rule is this? (place an "X" next to just one item)**

[x] Enforces code style
[ ] Warns about a potential error
[x] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
// some hypothetical promise-returning function:
function promise() {
  return Promise.resolve(true);
}

// disallow
promise().then((bool) => ... );

// allow/suggest
const bool = await promise();

// disallow
promise().catch((err) => ...)

// allow/suggest
try {
  const bool = await promise();
}
catch (err) {
   // ... err
}

// disallow
promise().finally(() => {})

// allow/suggest
try {
  const bool = await promise();
}
finally {
   // ... cleanup
}

or in combination:

// disallow
promise()
  .then(bool => ... )
  .catch(err => ...)
  .finally(() => ...);

// allow/suggest
try {
   const bool = await promise();
}
catch (err) {
   // error handling
}
finally {
  // cleanup
}

// disallow
promise().then(...).then(...).then(...)

// allow/suggest
await ..
await ..
await ...
```

**Why should this rule be included in ESLint (instead of a plugin)?**

I can imagine that a lot of developers and companies might have a desire to use this rule, mainly for code style (synchronous code flow) as well as consistency.

_edit: just fixed some missing await_

**Comment by not-an-aardvark** [comment]
@eslint/eslint-team It looks like this proposal has a lot of :+1:s from the community. Is anyone willing to champion it?

**Comment by michaelficarra** [comment]
Do we want this rule to be auto-fixable? What does it do at the top level? Does it need to know whether changing to `await` will introduce conflicting/shadowing bindings?

**Comment by mysticatea** [comment]
I'll champion this proposal.

**Comment by michaelficarra** [comment]
Maybe it should only produce warnings when it sees this pattern in an async function. Outside an async function, it seems like it will add too much confusion for novice users. Also, the conflicting binding check is probably necessary to avoid confusion during naïve rewrites.

**Comment by nzakas** [comment]
I agree with @mysticatea that we should start without autofixing for this rule.

I think it's okay to warn outside of async functions, as I think that would be a more common case. If people are already using an async function, they are probably more likely to be already be using `await`.  We can be sure to include some good documentation for this rule that can clear up any confusion.

**Comment by nzakas** [comment]
@dnalborczyk if this proposal is accepted, are you willing to submit a pull request to implement this rule?

**Comment by xjamundx** [comment]
We have something like this here as well:
https://github.com/xjamundx/eslint-plugin-promise

Feel free to copy/ take whatever.

**Comment by jimmywarting** [comment]
I so which we had this in our company right now!

I will talk from experiences and tell you what async/await can do appart from being more readable and give you 2 good example of what async/await can do that then/catch can't do for you

You have probably found yourself in a situation where you call a promise1 and then use what it returns to call promise2, then use the results of both promises to call a promise3. Your code most likely looked like this

```js
const makeRequest = () => {
  return promise1()
    .then(value1 => {
      // do something
      return promise2(value1)
        .then(value2 => {
          // do something          
          return promise3(value1, value2)
        })
    })
}
```

If promise3 didn’t require value1 it would be easy to flatten the promise nesting a bit. If you are the kind of person who couldn’t live with this, you could wrap both values 1 & 2 in a Promise.all and avoid deeper nesting, like this

```js
const makeRequest = () => {
  return promise1()
    .then(value1 => {
      // do something
      return Promise.all([value1, promise2(value1)])
    })
    .then(([value1, value2]) => {
      // do something          
      return promise3(value1, value2)
    })
}
```

This approach sacrifices semantics for the sake of readability. There is no reason for value1 & value2 to belong in an array together, except to avoid nesting promises.

This same logic becomes ridiculously simple and intuitive with async/await. It makes you wonder about all the things you could have done in the time that you spent struggling to make promises look less hideous.

```js
const makeRequest = async () => {
  const value1 = await promise1()
  const value2 = await promise2(value1)
  return promise3(value1, value2)
}
```


----

Another example where you want to write something in serial one after the other:

```js
async function runSerial(tasks) {
  for (const task of tasks) {
    await task()
  }
  console.log('Done with all tasks')
}
```

compared to: 

```js
function runSerial(tasks) {
  let result = Promise.resolve()
  
  tasks.forEach(task => {
    result = result.then(() => task())
  })

  result.then(() => console.log('Done with all tasks'))
}
```

The first one can be optimised by the engine cuz there are now anonymous functions

You are creating a many distinct function objects `() => task()` when you call `runSerial` even though they have the same body of code and no binding to the lexical scope. That's unnecessary.

**Comment by manniL** [comment]
are there still plans to create this rule? ☺️

**Comment by kaicataldo** [comment]
It looks like there is an orphaned PR right now (#11033). PRs are welcome!

**Comment by manniL** [comment]
@kaicataldo 	I'm on it :relaxed:

**Comment by kaicataldo** [comment]
Closing this issue since, after further discussion, the team decided not to accept this in core.

**Comment by jimmywarting** [comment]
Reason being?

**Comment by kaicataldo** [comment]
Ah, should have left a link to the PR where that discussion occurred. Sorry! More info can be found [here](https://github.com/eslint/eslint/pull/11961).
