### ISSUE TITLE
How to implement automatic formatting code ,use eslint  detection code 

### ISSUE THREAD

**Issue by Ckefan** [eslint/eslint#9650]
I use eslint detection code 
I think it will help me  fix  my code , Is there any way?

**Comment by platinumazure** [comment]
Hi @ckefan! You can use the [`--fix` CLI flag](https://eslint.org/docs/user-guide/command-line-interface#--fix) to automatically fix some of the problems reported by ESLint.

If you have any specific questions after trying that out, feel free to stop by our [Gitter chat](https://gitter.im/eslint/eslint).

**Comment by Ckefan** [comment]
@platinumazure  very thankful

**Comment by platinumazure** [comment]
Closing as the question has been answered.
