### ISSUE TITLE
JSX Fragment Syntax Support

### ISSUE THREAD

**Issue by clemmy** [eslint/eslint#9662]
JSX has official fragment syntax (https://github.com/facebook/jsx/pull/93)! Can we add support for that when JSX is enabled? I'd be happy to make a PR for this if someone can point me in the right direction. 🙂

**Comment by not-an-aardvark** [comment]
Thanks for creating an issue. I think this would be implemented by adding support to [`acorn-jsx`](https://github.com/RReverser/acorn-jsx), which is used by [`espree`](https://github.com/eslint/espree), ESLint's default parser.

Separately, we would also need to upgrade `espree` to the latest version of `acorn-jsx` in order for the change to take effect. This isn't a big problem, but it is nontrivial (see https://github.com/eslint/espree/issues/345).

**Comment by not-an-aardvark** [comment]
Actually, it seems like JSX fragments have already been added to `acorn-jsx` in https://github.com/RReverser/acorn-jsx/commit/1a71881bad60e96be607f7cb25ee28dad9a8fbb5, so we would just need to upgrade `acorn-jsx` in `espree` to support them.

**Comment by mysticatea** [comment]
As far as I know, upgrading `acorn-jsx` has a breaking change about `JSXText` node. This might need to wait for the next major version of ESLint.

**Comment by not-an-aardvark** [comment]
In https://github.com/eslint/espree/issues/345, there was some discussion about adding an option to Espree to avoid the breaking change in `acorn-jsx`.

**Comment by chucksellick** [comment]
The fragment syntax is working for me with Babel 7 beta 3, however using fragments is triggering eslint's quotes rule ("Strings must use doublequote").

**Comment by Mati365** [comment]
@chucksellick +1, same here

**Comment by ackvf** [comment]
Any news?

**Comment by mbavio** [comment]
Why was this issue closed? I see no solution, and it's not working for me with latest eslint.

**Comment by vladshcherbin** [comment]
@mbavio I think it's in the latest version (v5 alpha/rc)
