### ISSUE TITLE
Add TypeScript type definititions

### ISSUE THREAD

**Issue by j-f1** [eslint/eslint#9685]
This would allow TypeScript users to just `npm install eslint` and use it to write plugins or lint their code from Node.js.

Additionally, the types will allow users of regular JS to take advantage of type safety in some editors, like VS Code and Atom. These editors will use the TypeScript declarations to provide documentation on ESLint APIs by just hovering over method calls.

**Comment by not-an-aardvark** [comment]
This seems like it would be nice to have, but I'm concerned it would add extra overhead to the contribution process. For example, users might not realize that they have to update a TypeScript definition, and we would have to make sure the definitions stay up-to-date.

I'm not sure I see the advantage of having the definitions in the eslint repository itself as opposed to being maintained separately.

**Comment by ilyavolodin** [comment]
This was proposed a while back (and PR was made), but we decided that we don't want to choose a winner between TypeScript and Flow and maintain definitions in our repository. As far as I know TypeScript has a central repository where definitions could be stored, so I think it would be better to add it there.

**Comment by pmdartus** [comment]
I just opened a [PR to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23237) to add type definition to eslint. I would be interested if someone can review the types before it gets merged.
