### ISSUE TITLE
Curly rule fixer doesn't produce the expected result

### ISSUE THREAD

**Issue by bary12** [eslint/eslint#9694]
**Tell us about your environment**

* **ESLint Version:** 4.12.1
* **Node Version:** 6.10.3
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```JSON

{
    "env": {
        "browser": true,
        "es6": true
    },
    "parserOptions": {
        "sourceType": "module"
    },
    "extends": "eslint:recommended",
    "rules": {
        "no-undef": "off",
        "no-unused-vars": "off",
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single",
            {
                "avoidEscape": true,
                "allowTemplateLiterals": true
            }
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-var": "error",
        "require-jsdoc": [
            "error",
            {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true,
                    "ArrowFunctionExpression": true,
                    "FunctionExpression": true
                }
            }
        ],
        "valid-jsdoc": [
            "error",
            {
                "requireReturn": false
            }
        ],
        "eqeqeq": [
            "error",
            "always"
        ],
        "curly": "error",
        "max-len": [
            "error",
            120
        ]
    }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

if (value === 1)
    this.send(true);

```

```bash
$ ./node_modules/.bin/eslint src/plugins --color -f table --fix
```

**What did you expect to happen?**

The code

```js
if (value === 1)
    this.send(true);
```

was supposed to be fixed to 

```js
if (value === 1) {
    this.send(true);
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

The code was converted to

```js
if (value === 1) 
{this.send(true);}

```

**Comment by mysticatea** [comment]
Thank you for this issue.

You can get expected result with a combination of some rules:

- `curly` ... adds the enclosing block.
- `brace-style` ... adds linebreaks about the block as specified style.
- `indent` ... adds indentation to the block.

[Demo](https://mysticatea.github.io/vue-eslint-demo/#eMKcPU/DkQrDgjAMw7zClcKSwqc5KgUfw4cQRMOwB8Omw6NeZsKbQcKgwrQlw63DgDnDtsOvwrZaDQRyR3J3w5lAe8KDw5BBHzVTSMOnwpFHwqdawozCllwSemHCu3YCwpk9S8Oxw6BJw6MxwqbDlcOiwp8jZ8OQwqUKRcKrw4p5acKaRTMdw4okcsONw543H8OQwqtqAxJ4wrEYwqHDm3YJX8KVwoFeOcOJw6kHw69rKMOBYsOIwq55HQ0lw4/ClSzCoS/DjsOcw6jCicOmWh7DmMOfXMKWRRY=)

**Comment by gyandeeps** [comment]
Hopefully the question has been answered. Feel free to reopen. Thanks
