### ISSUE TITLE
Framework around deprecation warnings?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#9697]
This might not be super valuable, but I was thinking it might be good for us to have some sort of design in place in case we want to issue deprecation warnings for features in the future.

If we create a small framework, then we could be careful to ensure that deprecation warnings do or don't get into formatter output, etc., as desired. We could also leverage Node's `process.emitWarning` if desired.

There isn't a lot of immediate value, but I think this could add value for cases where we really want to deprecate/remove something but we want to do so over a longer period of time and with explicit warnings to users.

**Comment by not-an-aardvark** [comment]
Could you elaborate on what the framework would do? To me, it seems like just using `process.emitWarning` would be sufficient without creating a separate framework, but there might be a requirement that I'm forgetting about.

**Comment by platinumazure** [comment]
Maybe it is that simple, but I would like for us to put proper consideration into exactly how deprecation warnings should be shown to the user given the nonsense described in #9373.

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
