### ISSUE TITLE
release an updated browserify build

### ISSUE THREAD

**Issue by ronami** [eslint/eslint#9711]
Hey,

I'm running `eslint` in a browser along with `monaco-editor` (an online ide). I saw there's a `browserify` build (https://github.com/eslint/eslint/blob/master/package.json#L20), but it's not being released as part of the `eslint` npm package. I was able to find `eslint-browserify` (https://www.npmjs.com/package/eslint-browserify) but the last time it was released was 2 years ago.

Can we manually release a new and updated version for `eslint-browserify` and possibly make a release part of the regular release cycle for future builds? If not, is there anything I can do other than to clone `eslint` and build it myself?

I will be happy to make a PR to support that, please let me know if any of this makes sense.

Thanks!

**Comment by not-an-aardvark** [comment]
I don't think `eslint-browserify` is maintained by the ESLint team; it looks like it was released by someone else.

There was some discussion about supporting browser builds in https://github.com/eslint/eslint/issues/8348. The team decided that we don't want to officially support a browser build, but we are willing to accept changes that would make it easier for others to bundle ESLint into a browser build.

**Comment by ronami** [comment]
Thanks for the quick response, very appreciated :)

Would you consider releasing a `browserify` build as part of the `eslint` npm package? Or possibly as a separate package?

**Comment by not-an-aardvark** [comment]
As discussed in https://github.com/eslint/eslint/issues/8348 (see https://github.com/eslint/eslint/issues/8348#issuecomment-326413115 in particular), we don't want to officially support a browser build because it could pose a significant maintenance burden. However, we'll still consider accepting individual code changes that make ESLint easier to run in the browser (when bundled externally), as long as the changes are small and don't have an adverse impact.

**Comment by mysticatea** [comment]
[Playground for eslint-plugin-vue](https://mysticatea.github.io/vue-eslint-demo/) might help you. This site is using `monaco-editor` and `eslint` together.

- [src/app-state/eslint.js#L1](https://github.com/mysticatea/vue-eslint-demo/blob/master/src/app-state/eslint.js#L1) imports ESLint.
- [webpack.config.js#L104-L113](https://github.com/mysticatea/vue-eslint-demo/blob/master/webpack.config.js#L104-L113) is necessary shimming.

**Comment by ronami** [comment]
Thank you @mysticatea, I was able to use `webpack` to bundle eslint and it works nicely :)

Should I close the issue?
