### ISSUE TITLE
comment at end of line confuses indent's handling of ternary operator

### ISSUE THREAD

**Issue by Kovensky** [eslint/eslint#9729]
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** 9.2.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  rules: {
    'indent': ['error', 2, { SwitchCase: 1 }]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const obj = {
  foo () {
    return condition ? // comment
    1 :
      2
  }
}
```

```bash
npx eslint path/to/file.js
```

**What did you expect to happen?**
`1` to be indented at the same level as `2`

**What actually happened? Please include the actual, raw output from ESLint.**
The source code above is formatted according to `eslint --fix`.

`indent` wants to indent the `1` at the same level as the `return` statement. Removing the `// comment` after the `?` clears `indent`'s confusion and it does put `1` at the same indent level as `2`.

Putting the `?` on the next line also works around the problem.

**Comment by platinumazure** [comment]
This sounds like a bug to me, but I'll defer to @not-an-aardvark.

**Comment by platinumazure** [comment]
Working on this.

**Comment by not-an-aardvark** [comment]
I think I see what's wrong -- I'll work on it for a bit.
