### ISSUE TITLE
Configuration for rule "semi" is invalid: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by matheusgrieger** [eslint/eslint#9730]
**Tell us about your environment**

* **ESLint Version:**
^3.19.0

* **Node Version:**
8.9.3

* **npm Version:**
5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

// https://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true, jquery: true
  },
  // https://github.com/standard/standard/blob/master/docs/RULES-en.md
  extends: ['standard'],
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': (process.env.NODE_ENV === 'production' ? 2 : 0),
    // force semicolon
    'semi': [2, 'always'],
    // remove space before function paren
    'space-before-function-paren': [2, 'never'],
    // vue
    'html-self-closing': 0,
    'html-end-tags': 0,
    'max-attributes-per-line': 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

It appears the error is caused by the configuration. The only thing I did was running `npm run lint`, which translates to:

``` bash
eslint --ext .js,.vue src --fix
```

It is what came with Vue Webpack template, only thing is that I added the `--fix` at the end.

**What did you expect to happen?**

Wanted to fix linting errors with current files, such as semicolons.

**What actually happened? Please include the actual, raw output from ESLint.**

It throws error with lots of configurations, even if I remove the last rules up until the `semi` rule. ESLint does not work in any setup for me, even without `--fix`. The full output is the issue title:

 "/home/full/path/.eslintrc.js:
Configuration for rule "semi" is invalid:
Cannot read property 'concat' of undefined"

**Comment by zoe-andrews** [comment]
I'm experiencing similar issues.  

Nothing in my code changed, it was working fine and then after a fresh npm install it wasn't.

It is not specific to the rule, I have seen the same error message for indent, semi and max-len rules.

I am also using the babel-eslint parser.

**Comment by voxpelli** [comment]
Probably caused by https://github.com/mafintosh/is-my-json-valid/issues/149 – which has been fixed now

**Comment by zoe-andrews** [comment]
Yes it is fixed for me now too, thanks.

**Comment by LinusU** [comment]
Hi 👋 

I was the one who published the broken is-my-json-valid 🙈 sorry about that!

A new version was published shortly after, and the broken one have been deprecated on npm.

You can either just reinstall eslint, or manually update is-my-json-valid by running `npm install is-my-json-valid@2.17.1`

**Comment by matheusgrieger** [comment]
Thank you all for your time. After updating the package, ESLint is working once again!

**Comment by platinumazure** [comment]
Leaving a note to myself that I want to figure out which of our dependencies consumes is-my-json-valid and ensure that those dependencies pin to the new is-my-json-valid so we can then do the same with the direct dependencies here.

Thanks everyone for your help!

**Comment by LinusU** [comment]
@platinumazure with "pin", do you mean setting it to `"is-my-json-valid": "2.17.1"` as an exact version?

I would personally recommend against that since it will prevent you from getting any other bugfixes in the future. I understand that it's annoying when tings break, and I assure you that I do not taking breaking a such widely used module as is-my-json-valid lightly, but I really think that the correct course of action here is to utilise package-lock.json or yarn.lock in the upmost project.

Pinning the versions here and in your dependencies will require you to go thru all those dependencies and bump, then release new versions of those dependencies, then bump in eslint and then release a new version, should we discover a new bug in is-my-json-valid.

I'm very open to further discussion on this, and my mind is always open to different solutions :)

**Comment by platinumazure** [comment]
@LinusU Agreed 100%, and I should have worded it differently. I want to get our dependencies to a version where their `is-my-json-valid` version is `^2.17.1`. (That said, we don't have a direct dependency on `is-my-json-valid`, so it's a slightly more complicated issue.) I just want to make sure all of our users have the fix :smile:

**Comment by LinusU** [comment]
Perfect 🙌

**Comment by platinumazure** [comment]
@LinusU I missed this bit in your last comment:

> I understand that it's annoying when tings break, and I assure you that I do not taking breaking a such widely used module as is-my-json-valid lightly

Hopefully you were just speaking generally, but just in case you weren't: I did not mean to imply that you were negligent or that you didn't care about breaking a module. If I did inadvertently imply either of those, please accept my apologies and please know that I appreciate your diligence in getting a fix out so quickly. Thanks!

**Comment by LinusU** [comment]
Were absolutely speaking generally, did not feel any negative implications from you whatsoever 👍
