### ISSUE TITLE
Doc : Indicate default value on each rule page.

### ISSUE THREAD

**Issue by Delapouite** [eslint/eslint#974]
Hi.

Last month @albertosantini introduced a way to make sure that a rule which is *off by default* was listed as such on the [rules index page](http://eslint.org/docs/rules/) of the documentation in this PR : https://github.com/eslint/eslint/issues/865

This is great already, but I reckon that the default value of a rule should also be mentioned on the page rule itself.

Let's consider [space-after-keyword](http://eslint.org/docs/rules/space-after-keywords.html) for instance. Currently, there's no way to tell what is default value is.

My proposal is to add a new H2 section, just before *Rules Details*, called *Default Value* with the following : 
```
"space-after-keywords": [0, "always"]
```

I'm willing to go over each markdown file to add this block.

Of course, we should also add an automatic check in the Makefile to make sure that it's kept in sync with /conf/eslint.json

**Comment by nzakas** [comment]
No easy way to do this, and no followups, so closing.
