### ISSUE TITLE
no-useless-escape warns about \+, \* in regex

### ISSUE THREAD

**Issue by CapacitorSet** [eslint/eslint#9759]
**Tell us about your environment**

* **ESLint Version:** v4.13.1
* **Node Version:** v9.3.0
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "rules": {
        "no-useless-escape": "error"
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
function escapeRegExp(str) {
    return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
```

```bash
node node_modules/.bin/eslint src/test.js
```

**What did you expect to happen?**

I expected errors about \-, \{, \}.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint marked as "unnecessary escape character" many characters that do need to be escaped, like `[` and  `*`:

```
  2:26  error  Unnecessary escape character: \-  no-useless-escape
  2:28  error  Unnecessary escape character: \[  no-useless-escape
  2:32  error  Unnecessary escape character: \/  no-useless-escape
  2:34  error  Unnecessary escape character: \{  no-useless-escape
  2:36  error  Unnecessary escape character: \}  no-useless-escape
  2:38  error  Unnecessary escape character: \(  no-useless-escape
  2:40  error  Unnecessary escape character: \)  no-useless-escape
  2:42  error  Unnecessary escape character: \*  no-useless-escape
  2:44  error  Unnecessary escape character: \+  no-useless-escape
  2:46  error  Unnecessary escape character: \?  no-useless-escape
  2:48  error  Unnecessary escape character: \.  no-useless-escape
  2:52  error  Unnecessary escape character: \^  no-useless-escape
  2:54  error  Unnecessary escape character: \$  no-useless-escape
  2:56  error  Unnecessary escape character: \|  no-useless-escape
```

**Comment by j-f1** [comment]
Those characters don’t need to be escaped inside `[...]` in a regular expression.

**Comment by CapacitorSet** [comment]
Oh well, might as well close the issue then. Thank you.
