### ISSUE TITLE
Conflicting rules: comma-spacing & array-bracket-spacing

### ISSUE THREAD

**Issue by shaheenp** [eslint/eslint#9760]
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** 6.12.2
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
default

<details>

**Please show your full configuration:**
```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "extends": "eslint:recommended",
  "rules": {
    "indent": [
      "error",
      4,
      {
        "SwitchCase": 1
      }
    ],
    "brace-style": [
      "error",
      "1tbs"
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ],
    "space-in-parens": [
      "error",
      "never"
    ],
    "comma-spacing": [
      "error",
      {
        "before": false,
        "after": true
      }
    ],
    "array-bracket-spacing": [
      "error",
      "never"
    ],
    "object-curly-spacing": [
      "error",
      "never"
    ],
    "no-unused-vars": [
      "error",
      {
        "args": "none"
      }
    ],
    "strict": [
      "error",
      "global"
    ],
    "array-bracket-newline": [
      "error",
      {
        "multiline": true
      }
    ],
    "implicit-arrow-linebreak": [
      "error",
      "beside"
    ]
  }
}

```
</details>

<summary>Configuration</summary>

```js
"comma-spacing": ["error", {"before": false, "after": true}]
"array-bracket-spacing": ["error", "never"]
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let [, b,] = [1, 2, 3];
```

```bash
eslint .
```

**What did you expect to happen?**
For the linting to succeed because it followed the comma-spacing rule but then I realized the conflict. If run with `--fix`, it is not fixed because of the conflicting rules.

**What actually happened? Please include the actual, raw output from ESLint.**
`array-bracket-spacing` requires there to be no space before the close bracket in the destruction but `comma-spacing` requires there to be a space after the final comma in the destruction. Therefore, a conflict occurs.
```
~/conflict.js
  3:9  error  A space is required after ','           comma-spacing
```

**Comment by platinumazure** [comment]
I'm not sure if this would be a bug or enhancement request, but I think it would make sense for array-bracket-spacing to control here and for comma-spacing to focus on commas between items in a list only (rather than commas between the last list item and the closing token).

**Comment by shaheenp** [comment]
@platinumazure That's the behavior I was expecting before I discovered the conflict

**Comment by platinumazure** [comment]
@eslint/eslint-team Let's address this rule conflict if we can. Should we regard this as a bug or enhancement request? Which rule should we change? (My thoughts are in [this comment](https://github.com/eslint/eslint/issues/9760#issuecomment-353699544)).

**Comment by michaelficarra** [comment]
You can just omit the trailing comma, no?

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
