### ISSUE TITLE
feat: inline comment degrade from error to warning

### ISSUE THREAD

**Issue by AndersDJohnson** [eslint/eslint#9777]
**Tell us about your environment**

* **ESLint Version:** 4.11
* **Node Version:** 8.9.0
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Feature Request**

I would like the ability to change the level of a rule - degrade from error to warning or upgrade from warning to error - with inline-comments - without redefining it entirely. Will it inherit the configuration options from the eslintrc if I only specify the level when redefining it?

**Comment by mysticatea** [comment]
I think that you can use `/*eslint ... */` comment. For example: `/*eslint no-console: "off" */`. See also https://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by AndersDJohnson** [comment]
@mysticatea But I think that will reset its options too. What if I want to keep the same options, but just change the level from warning to error or vice versa?

**Comment by not-an-aardvark** [comment]
It won't reset the options.
