### ISSUE TITLE
cannot install eslint on Linux

### ISSUE THREAD

**Issue by oprogramador** [eslint/eslint#9780]
* ESLint Version: latest
* Node Version: 8.6.0
* npm Version: 5.2.0
* OS: Linux Mint 17 Qiana (kernel: 3.13.0-24-generic)

**What did you do?**
`npm i --save-dev eslint`

**What did you expect to happen?**
eslint should be installed

**What actually happened?**
I wait very long and installing stops

![screenshot from 2017-12-28 11 57 38](https://user-images.githubusercontent.com/8701039/34408848-6f2ef31e-ebc6-11e7-870a-1a3f2143c28b.png)

The problem is not about `minimatch` package because `npm i --save-dev minimatch@3.0.4` works.

Moreover installing eslint works for the same `node` and `npm` version and in the same time on Mac. 

Installing `eslint` was working for the same computer with the same Linux version few weeks ago.

Of course, I did `rm -rf node_modules`. Beside `eslint` I have no other dependencies in my `package.json`.

**Comment by mysticatea** [comment]
Would you try `npm cache clean && rm -rf node_modules package-lock.json` then re-install?

Anyway, it looks like an issue of `npm`. I'd like to recommend to open an issue on https://github.com/npm/npm.

**Comment by oprogramador** [comment]
`npm cache clean` hangs as well

I finally managed to install `eslint` after previously installing `eslint-config-airbnb-improved`.

**Comment by mysticatea** [comment]
In that case, I suspect that your npm-cache has broken.

**Comment by platinumazure** [comment]
Closing as it seems like the question has been answered, but please feel free to comment if there's anything we (ESLint team) need to look at.
