### ISSUE TITLE
prefer-destructuring should not check non-numeric indexes

### ISSUE THREAD

**Issue by aparajita** [eslint/eslint#9784]
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **Node Version:** 9.3.9
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },

  "extends": [
    "airbnb-base"
  ],

  "rules": {
    "class-methods-use-this": "off",
    "import/no-extraneous-dependencies": ["off", {"devDependencies": ["webpack-config/*.js"]}],
    "no-prototype-builtins": "off",
    "no-param-reassign": [0],
    "prefer-default-export": "off"
  }
}
```

</details>

**What rule do you want to change?**  prefer-destructuring

**Does this change cause the rule to produce more or fewer warnings?**  Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?** New default behavior

**Please provide some example code that this change will affect:**

```js
const INTEGER_WORDS = {
  one: 1,
  two: 2,
  three: 3,
  four: 4,
 };

let num = 1;
num = INTEGER_WORDS[num]; 
```

**What does the rule currently do for this code?**

Generates a warning for `num = INTEGER_WORDS[num];`

**What will the rule do after it's changed?**

It will ignore array indexes/keys that are not constants. I would argue this should **always** be the case, as it must be considered bad practice to destructure from a computed index or key.

**Comment by j-f1** [comment]
You *could* do `let { [num]: num } = INTEGER_WORDS`, but I agree that that should be an exception.

**Comment by platinumazure** [comment]
Hi @aparajita, I agree with @j-f1 that the rule is currently working as designed but that we could consider an enhancement to avoid warning when a computed property access is being used.

Would you mind editing your original post to match our [Rule Change Proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) so we can evaluate the proposed enhancement more easily? Thanks!

**Comment by aparajita** [comment]
@j-f1 That is invalid syntax; you're trying to declare and reference `num` at the same time. Even it were valid, it's a tortured syntax at best and indecipherable to mere mortals at worst.

```js
const words = { one: 1, two: 2 };
let num = 1;
let { [num]: num } = words;
```

Run that, you get:

```sh
SyntaxError: Identifier 'num' has already been declared
```

Remove `let num = 1`:

```sh
ReferenceError: num is not defined
```

**Comment by not-an-aardvark** [comment]
The correct way to do this is

```js
({ [num]: num} = INTEGER_WORDS);
```

**Comment by aparajita** [comment]
@not-an-aardvark Correct, but looking at it I still can't decipher what's happening without seriously scratching my head, and I've written Javascript parsers and compilers. So under **normal** circumstances I think `prefer-destructuring` should have pity on us mere mortals and not complain if we use `num = INTEGER_WORDS[num]`. And I still think it's bad practice to destructure a computed index/key.

**Comment by not-an-aardvark** [comment]
Oh, I see what's going on. The issue is that the `enforceForRenamedProperties` option for `prefer-destructuring` should consider any computed property access to be a "renaming".

The current behavior is intended to report something like this:

```js
num = foo.num;

// should be replaced with

({ num } = foo);
```

But it should not report an issue when the right-hand side is `foo[num]` instead.

**Comment by aparajita** [comment]
@not-an-aardvark That explains it.

**Comment by aparajita** [comment]
The fix seems to be quite easy. I haven't thought through it deeply, but this works:

Change [these lines](https://github.com/eslint/eslint/blob/61e5fa09a624f1faf310e8bc3fe553afefb37c22/lib/rules/prefer-destructuring.js#L167-L168) to:

```js
if (!rightNode.computed && ((property.type === "Literal" && leftNode.name === property.value) ||
    (property.type === "Identifier" && leftNode.name === property.name))) {
```

I added the check for `rightNode.computed`. If that's true, a non-literal expression is being used.
