### ISSUE TITLE
quotes rule

### ISSUE THREAD

**Issue by adityavardhan2017** [eslint/eslint#9790]
Would like to see quotes rule extended. Want seperate configuration for strings and objects. My team follows single quotes on strings and doubles quotes on objects and json files. I'm a lazy guy and use lot of eslint --fix. Please help me with this if there is any other way to configure. Thanks.

"quotes": [
"warn",
{"strings": "single"},
{"objects": "double"}
]

**Comment by Aladdin-ADD** [comment]
@adityavardhan2017 , why do you want a different way for strings and objects? IMHO, this seems very rare, and I have not seen it in any coding style.

**Comment by platinumazure** [comment]
I think you might be able to accomplish this with `no-restricted-syntax` by using the right kind of selectors. But I haven't had a chance to explore further and provide actual useful selectors yet...

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.
