### ISSUE TITLE
"eslint --ignore-path" should accept multiple file paths

### ISSUE THREAD

**Issue by ratson** [eslint/eslint#9794]
Current, `eslint --ignore-path` accept only one ignore file, it is useful if `.gitignore` and `.eslintignore` could be used together.

As of `ESLint v4.14.0`, `--ignore-path` command line argument is accepting `path::String`, is is proposed to change to `[path::String]`, so addition files could be included.

**Comment by ratson** [comment]
Update issue body with the following, hope it is clear enough. 

> As of ESLint v4.14.0, --ignore-path command line argument is accepting path::String, is is proposed to change to [path::String], so addition files could be included.

**Comment by platinumazure** [comment]
I'm :+1: to this enhancement as long as we have a clear path for how the ignores will be applied and whether the ignore patterns apply from the location of the ignore file or from the current working directory.

My suggestions on those points:

* Process each file in order, with ignore paths from later files overriding/complementing those from earlier files
* Each set of ignore patterns should be resolved relative to the location of the file containing them (to be consistent with current behavior for the single file case).

**Comment by ilyavolodin** [comment]
Second bullet point would add a bunch of additional complexity to the code to cover an edge case scenario. Not sure how necessary this is.

**Comment by graingert** [comment]
@ilyavolodin .gitignore + .eslintignore is a really common case. I've got a vendor directory in source control and I want to ignore my /build directories etc.

Currently both ignore files are in the root of the repo so it's less important.

**Comment by MaxMilton** [comment]
Ideally this should also be configurable via the config file (e.g. `eslintrc.js`) instead of _just_ the CLI.

**Comment by platinumazure** [comment]
@MaxMilton See #3529 for previous discussion on why config files cannot have ESLint ignore paths/patterns. Basically, we read and resolve configurations only after knowing what directories to traverse, which means we have to know what directories to ignore before we start reading configuration files. So I don't think that's going to change.

**Comment by MaxMilton** [comment]
@platinumazure thank you for clarifying, I hadn't seen that issue thread before. I'll continue to maintain multiple ignore files in my projects.

**Comment by platinumazure** [comment]
Seems discussion has stalled on this...

I would love to see support for multiple ignore files specified in `--ignore-path`. I would *not* like to see any form of auto-cascade/finding ignore files in ancestor directories.

Maybe it would be worth trying to prove the concept with a CLIEngine change first? E.g., add a method `addIgnoreFile` which would read the file and process the ignore patterns within, which would then be respected in a call to `executeOnFiles`. If we could prove something like that out, then it would be easy to add CLI options on top of that functionality.

**Comment by edele** [comment]
Here is an actual usecase.

I want eslint to only check files I can modify so I do `--ignore-path .gitignore`.
But additionally I don't want eslint to check my [flow-typed](https://github.com/flowtype/flow-typed) annotations.

The only way I can do this now is to copy everything from .gitignore to .eslintignore and add flow-typed/* there. But then I have to always add lines to .gitignore and .eslintignore every time I want to ignore something.

This is kinda minor but I would love to know about a better way

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.

**Comment by borekb** [comment]
For reference, Prettier currently cannot accept multiple `--ignore-path` options as well. It has been implemented in https://github.com/prettier/prettier/pull/3737 but not merged in the end.
