### ISSUE TITLE
Using decorators crashes eslint

### ISSUE THREAD

**Issue by jsg2021** [eslint/eslint#9799]
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **Node Version:** 8.9.3
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

eslint crashes when decorators are used.
https://gist.github.com/jsg2021/e61f6d4de37423842fd5b504b77967c9

I expect the decorator to not cause a crash in the tool. I suspect this may be a babel-eslint issue...since babel-eslint@8 seems to fix the crash... but causes a false positive for the `semi` rule. See second gist: 
https://gist.github.com/jsg2021/171b419b831d0e8a69c7bda22c7036fd

**Comment by jsg2021** [comment]
eslint@4.13.1 does not crash.

**Comment by not-an-aardvark** [comment]
Hi,

This issue is fixed in the latest version of `babel-eslint`. To avoid a crash, try upgrading to `babel-eslint@8.1.2`.

**Comment by jsg2021** [comment]
I already noted that in my description. But that brings in beta babel deps, as well as [a false positive semi rule violation](https://github.com/babel/babel-eslint/issues/567) when used with esline@4.14.

**Comment by not-an-aardvark** [comment]
I think the false positive `semi` violation is an unrelated issue. This might be a bug in `babel-eslint` that should be fixed, but the crash that you're reporting has already been fixed in recent versions of `babel-eslint`.

**Comment by jsg2021** [comment]
you don't think requiring jumping major versions isn't problem, when that change will pull in a beta version of babel?

**Comment by jsg2021** [comment]
I have actually updated to babel-eslint@8.1.2 but noticed it has babel 7 beta deps... my tool chain isn't using babel 7 betas... so there is a potential for conflict... then I noticed the semi rule issue.
