### ISSUE TITLE
false positive semi rule violation with decorators

### ISSUE THREAD

**Issue by jsg2021** [eslint/eslint#9800]
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **Node Version:** 8.9.3
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint@8.1.2

**Please show your full configuration:**

After updating eslint (from 4.13.1 to 4.14.0) and then babel-eslint from 7.2.3 to 8.1.2 (to fix a [crash](https://github.com/eslint/eslint/issues/9799) exposed by 4.14.0) I started to see new errors for the `semi` rule... I narrowed it down to classes being decorated... but only when the export statement is before the decorator. see this [thread](https://twitter.com/left_pad/status/876182750193176577) for why I put the export statement before.

See gist for reproduction & config: https://gist.github.com/jsg2021/171b419b831d0e8a69c7bda22c7036fd

**Comment by jsg2021** [comment]
I'm not sure where this needs to go. I also have an issue in [babel-eslint](https://github.com/babel/babel-eslint/issues/567)

**Comment by mysticatea** [comment]
Thank you for the report. I'm sorry for slow response.

This is not a bug of ESLint.
`babel-eslint@>=8.0.0` seems to generate wrong AST in that case. In `export default`, it needs a semicolon if the declaration is `ClassExpression`, but doesn't need if the declaration is `ClassDeclaration`.
`babel-eslint@>=8.0.0` generated `ClassExpression`.
