### ISSUE TITLE
When using mobx decorators，ESLint error

### ISSUE THREAD

**Issue by mzyailqq** [eslint/eslint#9833]
Error while running ESLint: Cannot read property 'type' of undefined
![image](https://user-images.githubusercontent.com/1835371/34712813-24b564ec-f55f-11e7-9a5c-d9b7701a8f9b.png)

**Comment by jnrepo** [comment]
I'm not sure why I'm getting this as well. It seems that after I upgrade from `4.13.1` to anything above or equal to `4.14.0` this error will be thrown by eslint.

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.

It's possible that you need to upgrade `babel-eslint` to the latest version to fix this problem.
