### ISSUE TITLE
[bug] JavaScript heap out of memory

### ISSUE THREAD

**Issue by cyw3** [eslint/eslint#9834]
![image](https://user-images.githubusercontent.com/11549103/34717276-78a5f63a-f56d-11e7-8f23-0f3cc89085b9.png)

centos
eslintv4.10.0
 
How can I handle with this?

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to triage this issue.

**Comment by Slapbox** [comment]
I'm having this issue. I don't see it as a bug, but is there any way to increase the memory available? With `node` you can pass `--max-old-space-size=7192`, for example.
