### ISSUE TITLE
Override does not work if rule is defined as "off" by default

### ISSUE THREAD

**Issue by bvaughn** [eslint/eslint#9836]
This works:
```js
module.exports = {
  'root': true,
  plugins: [
    'example-internal',
  ],
  rules: {},
  overrides: [{
    files: '**/__tests__/*.js',
    rules: {
      'example-internal/no-focused-tests': 2,
    }
  }],
};
```

But this does not:
```js
module.exports = {
  'root': true,
  plugins: [
    'example-internal',
  ],
  rules: {
    'example-internal/no-focused-tests': 0,
  },
  overrides: [{
    files: '**/__tests__/*.js',
    rules: {
      'example-internal/no-focused-tests': 2,
    }
  }],
};
```

I've pushed a [minimum repro here](https://github.com/bvaughn/example-eslint-rule-override-issue).

### Original bug report (outdated, see below discussion)

Based on [these docs](https://eslint.org/docs/user-guide/configuring#example-configuration) and discussion threads [like this one](https://github.com/eslint/eslint/issues/2274#issuecomment-344982591), I would expect the following rule override to be supported:

```js
'use strict';

module.exports = {
  'root': true,

  plugins: [
    'example-internal',
  ],

  rules: {
    // Off by default
    'example-internal/no-focused-tests': 0,
  },

  overrides: [
    {
      files: '**/__tests__/*.js',
      rules: {
        // On for tests
        'example-internal/no-focused-tests': 2,
      }
    }
  ],
};
```

Unfortunately my override does not seem to be working. I've pushed a [minimum repro here](https://github.com/bvaughn/example-eslint-rule-override-issue). Am I overlooking something obvious?

FWIW, this relates to facebook/react/pull/11977.

**Comment by platinumazure** [comment]
It looks like you're using ESLint 3.x (your package.json says `^3.10.2` I believe). This feature was introduced in ESLint 4.1.0. Please try upgrading to ESLint 4.1.0 or later.

**Comment by bvaughn** [comment]
Ah, I see. I wasn't aware of which version the feature was introduced in from the docs. That makes sense. Thank you!

**Comment by bvaughn** [comment]
I've updated my repro to ESLint 4.1 and the problem persists.

**Comment by bvaughn** [comment]
Ah. It seems the solution is _not_ to define the rule at all in the default `rules` block (rather than defining it as off).

**Comment by platinumazure** [comment]
@bvaughn That seems like a bug. An unspecified rule should be the same as a rule set to off/0. Does this happen in latest ESLint out of curiosity?

**Comment by bvaughn** [comment]
That was my assumption as well, but it doesn't hold.

Yes, also happens in latest. (Can be seen in my project currently.)

**Comment by platinumazure** [comment]
Thanks, I'll clone and investigate when I get home from work.

**Comment by not-an-aardvark** [comment]
Friendly ping: @platinumazure Were you able to investigate this issue?

**Comment by platinumazure** [comment]
I was not, sorry. Please feel free to investigate if you have time, otherwise I'll try to find some time soon.
