### ISSUE TITLE
Lock issues that have been closed for awhile

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9837]
Users occasionally leave comments on issues that have been closed for a long time. These comments usually take one of two forms:

1. The user believes they are encountering a bug which was purportedly already fixed
1. The user is expressing support for a feature request which was closed due to lack of interest (or other reasons)

I've noticed that in most cases, these comments are not actionable. In case 1, users often don't provide enough information to triage the new report, so we encourage them to create a new issue. In case 2, we encourage users to create a new issue anyway in order to get more attention to the feature request.

I think we should consider locking issues and PRs that have been closed for a long time (e.g. a month). This might encourage users to create a new issue with more information, rather than appending discussion which is often irrelevant to the original subject of the issue.

Some other open-source repositories that do this:

* [`go`](https://github.com/golang/go)
* [`fastlane`](https://github.com/fastlane/fastlane)

I like Go's approach of [adding a label](https://github.com/golang/go/issues/100#event-703575249) to the locked issue to describe why it was locked without spamming everyone with notifications.

**Comment by ljharb** [comment]
If an old issue is locked, and it's referred to in a new issue, will a reference to the new issue pop up on the old issue? If so, this seems like a good idea.

However, I don't think a month is "a long time" enough; a year might be, maybe 6 months, but a month isn't long enough for many folks to upgrade eslint.

**Comment by not-an-aardvark** [comment]
I'm not sure, but I think the reference will pop up only if the user that creates the reference has write access to the repository.

Maybe we could have a bot parrot any references to locked issues so that references appear.

**Comment by ljharb** [comment]
In that case, locking issues seems like it excessively prevents discovery of new issues by those visiting old ones :-/

**Comment by ilyavolodin** [comment]
I'm not sure this is a good idea. First of all, I think it has a possibility of creating a lot of additional noise. If people can't post "I just ran into this" in the closed issues, they might create a slew of new issues that we have no resolution for (either because they are non-issues, or because we already decided not to address them).
I think it might also disway some people from posting as well. Our rules for creating new issue are pretty strict, and a lot of people will not go through with them.
In general, I don't see people posting on closed issues as a big problem. It's easy to click through them in the issue tracker (at least for me). All of the above is a personal opinion.

**Comment by mysticatea** [comment]
Sounds good to me. I had a plan to propose a similar thing (half year though) since I found [Microsoft/vscode](https://github.com/Microsoft/vscode) locks old issues.

**Comment by platinumazure** [comment]
> If people can't post "I just ran into this" in the closed issues, they might create a slew of new issues

Cripes. I think if I had to choose extra posts in closed issues vs extra new issues, I would prefer extra posts in closed issues.

**Comment by not-an-aardvark** [comment]
In the [TSC meeting a few days ago](https://github.com/eslint/tsc-meetings/blob/1119e79b1d7962d9f6365b977a41aa44f2c8baf4/notes/2018/2018-01-18.md#lock-issues-that-have-been-closed-for-awhile), we decided to start locking issues 6 months after they are closed, and to reevaluate how the strategy is working in 2 months.
