### ISSUE TITLE
Creating and extending custom rules in eslint.

### ISSUE THREAD

**Issue by dashokkumar93** [eslint/eslint#9851]
In my code i wrote on VS Code(Containing eslint) most of the cases where a line containing a string.
like the below one.
```
var temp = "Stackoverflow";
var other=temp+" javascript";
```

I need an auto-fix option in es-lint such that it adds a (a static) comment at the end of line for the lines containing string on VS Code. like this
```
var temp = "Stackoverflow";//Custom comment
var other=temp+" javascript";//Custom comment
```

Is there any way of achieving this on eslint using node or VSCode?

**Comment by pmcelhaney** [comment]
Technically, yes, you can create a custom rule with a fixer. The rule would check that every string literal appears on a line that ends in a comment, and add the comment if necessary. 

https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes

If you can share more information on the purpose of the custom comment, we may be able to provide better guidance.

**Comment by ilyavolodin** [comment]
As mentioned, technically it's possible, but that would be improper use of the tool. ESLint isn't meant for things like that. You might want to look into jscodeshift and similar tools.

**Comment by dashokkumar93** [comment]
@pmcelhaney Thanks for the info. Also I need to add the custom comment at the end of the line. fixer object doesnt have the function to add comment at the end of the line? How could i achieve that?

**Comment by dashokkumar93** [comment]
@pmcelhaney _Technically, yes, you can create a custom rule with a fixer. The rule would check that every string literal appears on a line that ends in a comment, and add the comment if necessary._

String could appear anywhere in a line like this
```
 var js="javascript";
var temp="github"+ js;
```
should result in 
```
 var js="javascript"; //Not for translation
var temp="github"+ js; //Not for translation
```
Since the fixer object doesn't have property to add a text at the end of the line? How could i achieve that?

**Comment by pmcelhaney** [comment]
As @ilyavolodin said, ESLint's fixer is probably not the right tool. The fixer is intended to only make one or two character changes. Adding comments to the end of a line is probably possible, but it would be hacky. 

Now that I know your use case, here's another idea. Create a rule that makes sure all string literals are translated. Disable it in places where you don't need to translate.

 var js="javascript"; //eslint-disable-line localize-strings
var temp="github"+ js; //eslint-disable-line localize-strings

If you want to automatically add the comments one time up front, a tool like [jscodeshift](https://github.com/facebook/jscodeshift) is a better option.

**Comment by not-an-aardvark** [comment]
Closing because the question has been answered.
