### ISSUE TITLE
How to let ESLint ignore output file of webpack?

### ISSUE THREAD

**Issue by Jiaaa1014** [eslint/eslint#9862]
* **ESLint Version: ^4.15.0**
* **`babel-esLint` as my parser**

### `package.json`
```js
{
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "babel-loader": "^7.1.2",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.9",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "style-loader": "^0.19.1",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.0"
  }
}

```

### `.eslintrc`
```js
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "extends": "airbnb",
  "plugins": [
    "react"
  ],
  "rules": {
    "semi": [
      2,
      "never"
    ],
    "arrow-body-style": [
      "error",
      "as-needed"
    ],
    "comma-dangle": [
      "error",
      "never"
    ],
    "no-console": 0,
    "class-methods-use-this": "off",
    "react/jsx-uses-vars": "error",
    "react/jsx-uses-react": "error",
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    ]
  }
}
```
I have added `webpack` as a wrapping tool, after adding some eslint packages, it triggers lots of errors at my bundle.js (output of webpack).

Just like these two ![err, ](https://github.com/Jiaaa1014/MusicMaster-React/blob/master/public/musicMaster.gif)![err2](https://github.com/Jiaaa1014/Debugging/blob/master/error2.png), uploaded at my repository.

I wonder if there is `rules` or `env` key to config in `.eslintrc`, and it should turned out that ESLint is expected to ignore the webpack output file.

**Comment by not-an-aardvark** [comment]
Thanks for the issue. Have you tried using an [`.eslintignore file`](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories)?

**Comment by Jiaaa1014** [comment]
yeah, I'll try it. Thank for your help

**Comment by not-an-aardvark** [comment]
Closing because there hasn't been any activity on this issue for awhile. Feel free to open a new issue if you're still having trouble.
