### ISSUE TITLE
Rule: logical expressions that always constant

### ISSUE THREAD

**Issue by rlidwka** [eslint/eslint#987]
```js
if (a == 1 && a == 2) {...}
if (a != 1 || a != 2) {...}
assert(a == 1 && a == 2)
```

JavaScript is dynamic enough so it's not always an error, but I'd bet in most cases it is.

ref https://github.com/rlidwka/sinopia/issues/77

**Comment by denis-sokolov** [comment]
#2581 has been denied for performance reasons.
I might, of course, be wrong, but it seems to me there were no major algorithmic improvements possible to my implementation, which suggests this issue can be closed as there is no way to implement this.

**Comment by nzakas** [comment]
I agree. This has been open nearly a year and we aren't even close, so likely won't happen.
