### ISSUE TITLE
Ending line with &nbsp; breaks indent linting rules

### ISSUE THREAD

**Issue by ccicchitelli** [eslint/eslint#9878]
**Tell us about your environment**

* **ESLint Version:**4.6.1
* **Node Version:**6.11.3
* **npm Version:**3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint, babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "react",
    "import"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "jest": true
  },
  "settings": {
    "import/resolver": "webpack"
  },
  "rules": {
    "jsx-a11y/label-has-for": [ 2, {
      "components": [ "Label" ],
      "required": {
        "some": [ "nesting", "id" ]
      },
      "allowChildren": false
    }],
    "arrow-body-style": 1,
    "arrow-parens": 0,
    "indent": [2, 2],
    "linebreak-style": [2, "unix"],
    "no-tabs": 2,
    "no-unused-expressions": 0,
    "semi": [2, "never"],
    "import/extensions": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0,
    "import/prefer-default-export": 1,
    "jsx-a11y/href-no-hash": 2,
    "react/forbid-prop-types":   [2, { "forbid": ["any"] } ],
    "react/jsx-filename-extension": [2, { "extensions": [".js"] }],
    "react/jsx-indent": [2, 2]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
            <small>By choosing to continue, you acknowledge you have reviewed our&nbsp;
              <a>information disclosure</a>.
            </small>
```

```bash
eslint [folder]
```

**What did you expect to happen?**
The code above should pass indent linting rules.

**What actually happened? Please include the actual, raw output from ESLint.**
It generated the following error:

```bash
  62:1  error  Expected indentation of 12 spaces but found 14  indent
```

Removing two spaces generates the same error, inverted:

```bash
[eslint] Expected indentation of 14 space characters but found 12. 
```

However, moving the non-breaking space to the same line as the anchor tag, with 14 spaces, does not generate an error. It appears the line ending with the non-breaking space is breaking linting on the next line, at least partially (no other errors are generated). 

This works:
```js
            <small>By choosing to continue, you acknowledge you have reviewed our
              &nbsp;<a>information disclosure</a>.
            </small>
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. I noticed you put "all" as your ESLint version, but I assume you haven't actually tried this on *every* ESLint version. Could you be more specific about what version you're using?

**Comment by ccicchitelli** [comment]
Sorry, I meant to update that before submitting. What that was meant to indicate is that it's apparently present in all recent versions. I've tested 4.6.1 and the latest.

**Comment by Florian-R** [comment]
FWIW, I noticed that while trying to upgrade from 4.15.0 to 4.16.0. Same behavior on 4.17.0.

**Comment by apost** [comment]
I have the same problem. For now I find this stylistic compromise acceptable for my style guide:

            <small>
              By choosing to continue, you acknowledge you have reviewed our &nbsp;
              <a>information disclosure</a>.
            </small>
