### ISSUE TITLE
No indent rule for method declarations

### ISSUE THREAD

**Issue by benjamin-demarteau** [eslint/eslint#9886]
**Tell us about your environment**

* **ESLint Version:** 4.6.1
* **Node Version:** v9.4.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
```json
"parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
}
```

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
{
    "globals": {
        "angular": true
    },
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "rules": {
        // warnings
        "one-var": [1, "never"],
        "no-unused-vars": [1, { "args": "none" }],
        "no-useless-escape": [0],
        "no-console": [1],

        // errors
        "array-bracket-spacing": [2, "never"],
        "block-spacing": [2, "always"],
        "brace-style": [2, "1tbs"],
        "comma-dangle": [2, "always-multiline"],
        "comma-spacing": [2, { "after": true }],
        "eol-last": [2, "always"],
        "indent": [2, 4, {
            "FunctionDeclaration": { "body": 1, "parameters": 2 }
        }],
        "key-spacing": [2],
        "keyword-spacing": [2, { "before": true, "after": true }],
        "linebreak-style": [2, "unix"],
        "new-parens": [2],
        "no-unneeded-ternary": [2],
        "no-whitespace-before-property": [2],
        "curly": [2, "all"],
        "object-curly-spacing": [2, "always"],
        "space-before-blocks": [2, "always"],
        "space-before-function-paren": [2, "never"],
        "space-in-parens": [2, "never"],
        "space-unary-ops": [2, { "words": true, "nonwords": false }],
        "switch-colon-spacing": [2, { "before": false, "after": true }],
        "arrow-spacing": [2, { "before": true, "after": true }],
        "no-var": [2],
        "dot-location": [2, "property"],
        "arrow-parens": [2, "as-needed"],
        "no-trailing-spaces": [2]
        // TODO Add some of these
        // https://github.com/Gillespie59/eslint-plugin-angular
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
```js
class Something {
    constructor(
            p1,
            p2) {
        this.something();
    }

    something() {
    }
}
```

```bash
./node_modules/.bin/eslint --fix test.js
```

**What did you expect to happen?**
Nothing, the file is already correctly formatted.

**What actually happened? Please include the actual, raw output from ESLint.**
As per `"indent": [2, 4, { "FunctionDeclaration": { "body": 1, "parameters": 2 } }]`, nothing should happen. Instead, it unindented the constructor parameters. I couldn't find anything related specifically to methods but I'd expect `FunctionDeclaration` to apply to both methods and functions.

```js
class Something {
    constructor(
        p1,
        p2) {
        this.something();
    }

    something() {
    }
}

```

**Comment by not-an-aardvark** [comment]
Does it work if you use the `FunctionExpression` option rather than the `FunctionDeclaration` option? (ESLint uses the [ESTree AST format](https://github.com/estree/estree), which considers a class method to be a `FunctionExpression` rather than a `FunctionDeclaration`.)

**Comment by benjamin-demarteau** [comment]
Yup, that works. Thanks! Should it be documented? Or fixed upstream even?

**Comment by not-an-aardvark** [comment]
Glad to hear that it works. I think it's working as intended upstream, but feel free to make a PR if you think the documentation could be made more clear (e.g. by adding an example).
