### ISSUE TITLE
RegExp enhancements in ES2018

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#9893]
Several RegExp enhancements have arrived at Stage 4.

- [x] Update Espree to support the syntax in `ecmaVersion:2018`.
  - [x] RegExp `s` (dotAll) flag (https://github.com/tc39/proposals/commit/6feba532251379f6ff35faaa3786c7fc03c855a0) (`/foo.bar/s`)
  - [x] RegExp named capture groups (https://github.com/tc39/proposals/commit/c521bd5c24cdd811455879807eb14137d82915d4) (`/(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/`)
  - [x] RegExp Lookbehind Assertions (https://github.com/tc39/proposals/commit/7715a873847cea2808bd6f5cd3303f9f7634d69d) (`/(?<=a)b/`)
  - [x] RegExp Unicode Property Escapes (https://github.com/tc39/proposals/commit/7715a873847cea2808bd6f5cd3303f9f7634d69d) (`/\p{Script=Greek}/u`)
- [x] Update core rules to support the syntax.

**Comment by ilyavolodin** [comment]
Probably `no-useless-escape` needs to be updated.

**Comment by not-an-aardvark** [comment]
`no-unexpected-multiline` needs to be updated [here](https://github.com/eslint/eslint/blob/d64fbb41d344f70f155ee334c5eddac4c9d0861c/lib/rules/no-unexpected-multiline.js#L36) to check an intended `s` flag when it sees division.

**Comment by mysticatea** [comment]
I have done to implement parsing (https://github.com/eslint/espree/pull/369).
I'll work on this for core rules.
