### ISSUE TITLE
require-jsdoc on fat arrow class functions

### ISSUE THREAD

**Issue by grydstedt** [eslint/eslint#9894]
require-jsdoc does not seem to pick up on fat arrow class functions through babel-eslint. I understand it's an experimental feature but wondering if it's an easy add.

```js

class MyClass {

  myFunction = () => {
    return "foo"
  }

}

```

**Tell us about your environment**

* **ESLint Version:**
4.16.0
* **Node Version:**
8.9.0
* **npm Version:**
5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**
{
  parser: "babel-eslint",
  parserOptions: {
    ecmaVersion: 6,
    sourceType: "module",
    ecmaFeatures: {
      modules: true,
      jsx: true,
      arrowFunctions: true,
      classes: true,
      spread: true
    }
  },
  env: {
    browser: true,
    node: true,
    mocha: true,
    jest: true,
    es6: true
  },
  plugins: [
    "react",
    "no-console-log",
    "babel",
    "flowtype",
    "require-jsdoc-except"
  ],
  settings: {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": false
    }
  },
  rules: {
    /*
    **  VARIABLES
    **  These rules have to do with variable declarations.
    */
    "init-declarations": 0, // `[2, "always"]` is default
    "no-catch-shadow": 0, // `2` is default
    "no-delete-var": 1, // `2` is default
    "no-label-var": 2,
    "no-shadow-restricted-names": 2,
    "no-shadow": [1, {"builtinGlobals": false, "hoist": "all"}], // `[2, {"builtinGlobals": false, "hoist": "functions"}]` is default
    "no-undef-init": 1, // `2` is default
    "no-undef": 2,
    "no-unused-vars": [1, {"vars": "all", "args": "none"}],

    /*
    **  POSSIBLE ERRORS
    **  The following rules point out areas where you might
    **  have made mistakes.
    */
    "no-cond-assign": [2, "except-parens"],
    "no-constant-condition": 2,
    "no-control-regex": 2,
    "no-debugger": 2,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty-character-class": 2,
    "no-empty": 2,
    "no-ex-assign": 2,
    "no-extra-boolean-cast": 2,
    "no-extra-semi": 1, // `2` is default
    "no-func-assign": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-negated-in-lhs": 2,
    "no-obj-calls": 2,
    "no-regex-spaces": 2,
    "no-sparse-arrays": 2,
    "no-throw-literal": 2,
    "no-unreachable": 2,
    "use-isnan": 2,
    "valid-jsdoc": 0, // `2` is default
    "valid-typeof": 2,
    "no-unexpected-multiline": 2,

    /*
    **  BEST PRACTICES
    **  These are rules designed to prevent you from making mistakes.
    **  They either prescribe a better way of doing something or help
    **  you avoid footguns.
    */
    "accessor-pairs": [2, {"getWithoutSet": false, "setWithoutGet": true}],
    "block-scoped-var": 2,
    "default-case": 2,
    "dot-location": [2, "property"], // `[2, "object"]` is recommended
    "eqeqeq": 2, // `2` is recommended, optionally set `[2, "smart"]` or `[2, "allow-null"]`
    "guard-for-in": 2,
    "no-alert": 1, // `2` is recommended
    "no-caller": 2,
    "no-div-regex": 2,
    "no-eq-null": 2,
    "no-eval": 2,
    "no-extend-native": 2, // `2` is recommended, optionally set `[2, {"exceptions": ["Object"]}]`
    "no-extra-bind": 2,
    "no-fallthrough": 1, // `2` is recommended
    "no-floating-decimal": 1, // `2` is recommended
    "no-implied-eval": 2,
    "no-invalid-this": 0, // `2` is recommended
    "no-iterator": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 0,
    "no-multi-spaces": [2, {"exceptions": {"VariableDeclarator": true, "ImportDeclaration": true, "AssignmentExpression": true, "ObjectExpression": true}}], // `2` is recommended
    "no-multi-str": 2,
    "no-native-reassign": 2, // `2` is recommended, optionally set `[2, {"exceptions": ["Object"]}]`
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-new": 0,
    "no-octal-escape": 2,
    "no-octal": 2,
    "no-process-env": 0,
    "no-proto": 2,
    "no-redeclare": [2, {"builtinGlobals": true}], // `2` is recommended and actually defaults to `[2, {"builtinGlobals": false}]`
    "no-return-assign": [2, "except-parens"],
    "no-script-url": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-useless-call": 1, // `2` is recommended
    "no-useless-concat": 2,
    "no-void": 2,
    "no-warning-comments": [1, {"terms": ["todo", "fixme"], "location": "start"}], // `[0, { "terms": ["todo", "fixme", "xxx"], "location": "start" }]` is recommended
    "no-with": 2,
    "radix": 1, // `2` is recommended
    "wrap-iife": [2, "inside"], // `[2, "outside"]` is recommended
    "yoda": [1, "never"], // `[2, "never"]` is recommended, optionally set `[2, "never", {"exceptRange": true, "onlyEquality": false}]

    /*
    **  STYLISTIC ISSUES
    **  These rules are purely matters of style and are
    **  quite subjective.
    */
    "array-bracket-spacing": [1, "never"], // optionally set `[2, "never", {"singleValue": true, "objectsInArrays": true, "arraysInArrays": true}]`
    "block-spacing": [1, "always"],
    "brace-style": [1, "1tbs", {"allowSingleLine": false}],
    "comma-spacing": [1, {"before": false, "after": true}],
    "comma-style": [1, "last"], // optionally set `[2, "first", {"exceptions": {"ArrayExpression": true, "ObjectExpression": true}}]`
    "computed-property-spacing": [1, "never"],
    "consistent-this": [1, "self"],
    "eol-last": 1,
    "func-names": 0,
    "func-style": 0, // optionally set `[2, "expression"]`
    "id-length": 0, // optionally set `[2, {"min": 3, "max": 10, "properties": "never", "exceptions": ["x"]}]`
    "id-match": 0, // optionally set `[2, "^[a-z]+([A-Z][a-z]+)*$", {"properties": false}]`
    "indent": [1, 2, {"SwitchCase": 1, "VariableDeclarator": 2}], // optionally set `[2, 2, {"SwitchCase": 1, "VariableDeclarator": {"var": 2, "let": 2, "const": 3}}]`
    "jsx-quotes": [1, "prefer-double"],
    "key-spacing": [1, {"beforeColon": false, "afterColon": true, "mode": "minimum"}], // optionally set `[2, {"beforeColon": false, "afterColon": true, "mode": "strict", "align": "colon"}]`
    "lines-around-comment": 0, // optionally set `[2, {"beforeBlockComment": true, "beforeLineComment": true, "allowBlockStart": true}]`
    "linebreak-style": 0, // optionally set `[1, "unix"]`
    "new-parens": 1,
    "no-array-constructor": 1,
    "no-inline-comments": 0,
    "no-mixed-spaces-and-tabs": 1, // optionally set `[2, "smart-tabs"]`
    "no-multiple-empty-lines": [1, {"max": 1}],
    "no-nested-ternary": 0,
    "no-new-object": 1,
    "no-restricted-syntax": 0, // optionally set `[2, "FunctionExpression", "WithStatement"]`
    "no-spaced-func": 1,
    "no-ternary": 0,
    "no-trailing-spaces": [1, {"skipBlankLines": false}],
    "no-underscore-dangle": 0,
    "no-unneeded-ternary": [1, {"defaultAssignment": true}],
    "object-curly-spacing": [0, "never"], // optionally set `[2, "always", {"objectsInObjects": false, "arraysInObjects": false}]`
    "one-var": [1, {"uninitialized": "always", "initialized": "never"}], // optionally set `[2, {"var": "always", "let": "never", "const": "never"}]`
    "operator-assignment": 0, // optionally set `[2, "always"]`
    "padded-blocks": [1, "never"],
    "quotes": [1, "single", "avoid-escape"],
    "semi-spacing": [1, {"before": false, "after": true}],
    "semi": [1, "always"],
    "sort-vars": 0, // optaionlly set `[2, {"ignoreCase": true}]`
    "keyword-spacing": [1],
    "space-before-blocks": [1, "always"], // optionally set `[2, {"functions": "never", "keywords": "always"}]`
    "space-before-function-paren": [1, {"anonymous": "never", "named": "never", "asyncArrow": "ignore"}],
    "space-in-parens": [1, "never"], // optionally set `[2, "always", {"exceptions": ["empty"]}]`
    "space-infix-ops": [1, {"int32Hint": false}],
    "space-unary-ops": [1, {"words": true, "nonwords": false}],
    "spaced-comment": [1, "always", {"exceptions": ["/"]}], // optionally set `[2, "always", {"exceptions": ["-", "+"], "markers": ["/"]}]`
    "wrap-regex": 1,

    /*
    **  ECMASCRIPT 6
    **  These rules are only relevant to ES6 environments.
    */
    "arrow-spacing": [2, {"before": true, "after": true}],
    "constructor-super": 2,
    "generator-star-spacing": 0,
    "no-class-assign": 2,
    "no-const-assign": 2,
    "no-dupe-class-members": 0, // `2` is default, only use on ES6+ environments
    "no-this-before-super": 2,
    "no-var": 1, // `2` is default, only use on ES6+ environments - when using this set `"blockBindings": true` in `ecmaFeatures` object
    "object-shorthand": 0, // `[2, "always"]` is default
    "prefer-arrow-callback": 0, // `2` is default, only use on ES6+ environments
    "prefer-const": 1, // `2` is default
    "prefer-spread": 0, // `2` is default, only use on ES6+ environments
    "prefer-reflect": 0, // `2` is default, only use on ES6+ environments, optionally set `[2, {exceptions: ["apply", "call"]}]`
    "prefer-template": 0, // `2` is default, only use on ES6+ environments
    "require-yield": 2,

    /*
    **  NODE.JS AND COMMONJS
    **  These rules are specific to JavaScript running on Node.js or
    **  using CommonJS in the browser.
    */
    "callback-return": 0, // `2` is default, optionally set `[2, ["callback", "cb", "next"]]`
    "global-require": 0, // `2` is default
    "handle-callback-err": 0, // `2` is default, optionally set `[2, "^(err|error)$"]`
    "no-mixed-requires": 0, // [2, false] is default
    "no-new-require": 0, // `2` is default
    "no-path-concat": 0, // `2` is default
    "no-process-exit": 0, // `2` is default
    "no-restricted-modules": 0, // no default, optionally set `[2, "fs", "os"]`
    "no-sync": 0, // `2` is default

    /*
    **  LEGACY
    **  The following rules are included for compatibility with JSHint and
    **  JSLint. While the names of the rules may not match up with the
    **  JSHint/JSLint counterpart, the functionality is the same.
    */
    "max-depth": 0, // `[2, 4]` is default
    "max-len": [0, 80, 4, {"ignoreComments": true, "ignoreUrls": true}],
    "max-params": 0, // no default, optionally set `[2, 3]`
    "max-statements": 0, // no default, optionally set `[2, 2]`
    "no-bitwise": 1, // `2` is default
    "no-plusplus": 0, // `2` is default

    "react/jsx-closing-bracket-location": 1,
    "react/jsx-curly-spacing": 1,
    "react/jsx-indent-props": [1, 2],
    "react/jsx-key": 1,
    "react/jsx-no-duplicate-props": 1,
    "react/jsx-no-undef": 2,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": [1, "allow-in-func"],
    "react/no-did-update-set-state": 1,
    "react/no-direct-mutation-state": 1,
    "react/no-unknown-property": 1,
    "react/prefer-es6-class": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 2,
    "react/require-extension": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": [0, {
      "order": [
        "static-methods",
        "lifecycle",
        "/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/",
        "everything-else",
        "/^render.+$/",
        "render"
      ]
    }],
    "react/wrap-multilines": 1,

    "babel/object-curly-spacing": 1,

    "flowtype/boolean-style": [
      2,
      "boolean"
    ],
    "flowtype/define-flow-type": 1,
    "flowtype/delimiter-dangle": [
      2,
      "never"
    ],
    "flowtype/generic-spacing": [
      2,
      "never"
    ],
    "flowtype/no-primitive-constructor-types": 2,
    "flowtype/no-weak-types": 0,
    "flowtype/object-type-delimiter": [
      2,
      "comma"
    ],
    "flowtype/require-parameter-type": 0,
    "flowtype/require-return-type": [
      0,
      "always",
      {
        "annotateUndefined": "never"
      }
    ],
    "flowtype/require-valid-file-annotation": 2,
    "flowtype/semi": [
      2,
      "always"
    ],
    "flowtype/space-after-type-colon": [
      2,
      "always"
    ],
    "flowtype/space-before-generic-bracket": [
      2,
      "never"
    ],
    "flowtype/space-before-type-colon": [
      2,
      "never"
    ],
    "flowtype/type-id-match": [
      2,
      "^([A-Z][a-z0-9]+)+Type$"
    ],
    "flowtype/union-intersection-spacing": [
      2,
      "always"
    ],
    "flowtype/use-flow-type": 1,
    "flowtype/valid-syntax": 1,
    "require-jsdoc-except/require-jsdoc": [
      1,
      {
        "require": {
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "ClassDeclaration": false,
          "ArrowFunctionExpression": true,
          "FunctionExpression": true
        },
        "ignore": [
          "constructor",
          "componentWillReceiveProps",
          "souldComponentUpdate",
          "render",
          "componentWillUpdate",
          "componentDidUpdate",
          "componentWillUnmount",
          "componentDidCatch"
        ]
      }
    ]
  }
}

<details>
<summary>Configuration</summary>

```js



```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

class MyClass {

  myFunction = () => {
    return "foo"
  }

}

```

```bash

```

**What did you expect to happen?**
Complain about missing comment

**What actually happened? Please include the actual, raw output from ESLint.**
Does not complain

**Comment by platinumazure** [comment]
Given that static class properties is not yet Stage 4, it's unlikely we'll accept a change in the core `require-jsdoc` rule at this time (although we are presently working to clarify our stance on changes for experimental features).

Is there a `require-jsdoc` rule in eslint-plugin-babel? I think that would be the place to request a new rule or a rule change, if we don't accept this proposal. Thanks!

**Comment by grydstedt** [comment]
Got it, thank you. Should I close this issue?

**Comment by platinumazure** [comment]
No worries, I've got it.

Please do let us know if you file an issue or PR in eslint-plugin-babel, for future users that might stumble across this issue.

Thanks again!
