### ISSUE TITLE
Clean up key-spacing documentation

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9900]
As of ESLint v4.16.0, the [`key-spacing` documentation](https://eslint.org/docs/rules/key-spacing) is difficult to understand. All of the options are presented in a single list in the [Options section](https://eslint.org/docs/rules/key-spacing#options), but there are actually multiple categories of options, and some options can be nested under other options, and it's not clear what is allowed from reading the top of the file. I think we should reorganize the documentation to more clearly describe what configurations are allowed without relying so much on examples.

**Comment by abiduzz420** [comment]
Let me look into the issue. I shall take it up.

**Comment by platinumazure** [comment]
Thanks @abiduzz420! Let us know if we can help.

**Comment by abiduzz420** [comment]
What do you guys think about it: https://gist.github.com/abiduzz420/75d6f8b8508eb3d9fed8137c2ccefc20
Open to changes.

**Comment by platinumazure** [comment]
@abiduzz420 Looks promising! Go ahead and open a PR and we can take a closer look.

**Comment by abiduzz420** [comment]
One of the problems I faced while reading the examples are they're not properly highlighted. Meaning I need to clearly read whether it's the correct code or incorrect code. May be we could have incorrect code examples in warning boxes (bootstrap way) and show correct code snippets in green. 
Another alternative of showing code examples could be showing it side by side (incorrect and the correct code)

**Comment by platinumazure** [comment]
Strange, we are supposed to have code that highlights examples based on the immediately preceding text (to wit, `Examples of **incorrect** code` vs `Examples of **correct** code`). Let me dig into that on the side...

**Comment by abiduzz420** [comment]
Yeah sure I will do it.

**Comment by platinumazure** [comment]
@abiduzz420 Actually I decided to try to see if I could solve the example styling problem and I came up with something simple pretty quickly. So no need to create an issue. Please feel free to follow eslint/eslint.github.io#453 if you want to track the progress of that enhancement 😄

**Comment by abiduzz420** [comment]
I'll look into it in the evening. Differentiating incorrect code snippet from correct code would help.

**Comment by platinumazure** [comment]
@abiduzz420 I did some preliminary digging and documented my findings here: eslint/eslint.github.io#454
