### ISSUE TITLE
consuming config package with multiple rules

### ISSUE THREAD

**Issue by unional** [eslint/eslint#9914]
**ESLint Version:** 4.16.0

I try to use a config package that exposes multiple styles.

// eslintrc.json
```json
{
  "extends": "unional/latest"
}
```

In IDE (VSCode 1.19.3 with Eslint plugin), this config seems to be working fine.

However, cli doesn't work:
```sh
> eslint src
Error: Cannot find module 'unional/latest'
```

To make cli happy, I have to change the config to:
```json
{
  "extends": "./node_modules/eslint-config-unional/latest.json"
}
```

Which I know is a supported way. But it would be much nicer to keep it as `unional/latest`.

By the way, are the `eslint:recommended` and `eslint:all` hardcoded? Is it possible to make the config package to be consumable as `unional:latest`?

**Comment by platinumazure** [comment]
If it works in VSCode but not in the CLI, that might imply you're using different versions of ESLint in those cases. Try investigating that and shoring that up first.

------

Shameless plug for ESLint plugins here:

The best way to expose and consume multiple potential configurations is as a plugin. Plugins can export multiple configurations.

See [this section](https://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin) for more info on how to consume a plugin configuration.

See [here](https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins) for more info on how to create configurations in plugins.

**Comment by unional** [comment]
It is not due to versioning. I check and upgraded cli to match with latest: 4.16.0. It is working on the IDE but not cli.

**Comment by platinumazure** [comment]
@unional Could you please try running with the `--debug` flag in CLI to see if there's anything unexpected going on? If you can't spot anything, please post the output here. Thanks!

**Comment by unional** [comment]
Sure. I don't see anything suspicious. It just seems like it cannot understand `eslint-config-unional/latest` to lookup the package `eslint-config-unional` and get the config `latest.json`
```sh
eslint src --debug
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +0ms
  eslint:ignored-paths Looking for ignore file in /...projectA +0ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cli-engine Processing /...projectA/src/api-spec-generator.js +0ms
  eslint:cli-engine Linting /...projectA/src/api-spec-generator.js +0ms
  eslint:config Constructing config file hierarchy for /...projectA/src +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /...projectA/package.json +1ms
  eslint:config-file Loading package.json config file: /...projectA/package.json +0ms
  eslint:config-file Loading JSON config file: /...projectA/package.json +0ms
  eslint:config-file Loading unional/latest +118ms
  eslint:config-file Attempting to resolve eslint-config-unional/latest +0ms
Cannot find module 'eslint-config-unional/latest'
Referenced from: /...projectA/package.json
Error: Cannot find module 'eslint-config-unional/latest'
Referenced from: /...projectA/package.json
    at ModuleResolver.resolve (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/hwong/.nvm/versions/node/v9.4.0/lib/node_modules/eslint/lib/config.js:180:43)
```

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
