### ISSUE TITLE
Parsing Error: Unexpected token <

### ISSUE THREAD

**Issue by Albert-Gao** [eslint/eslint#9917]
**Tell us about your environment**

* **ESLint Version:** 4.16.0
* **Node Version:** 8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Webstorm built-in

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "es6": true,
    "node": true,
    "jest": true,
    "browser": true
  },
  "parserOptions": {
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "extends": "eslint:recommended",
  "rules": {
    "indent": [
      "error",
      2
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ],
    "arrow-parens": [
      "error",
      "as-needed"
    ]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const HeroImage = () =>
  <Container>
    <Image src="/static/hero.png" />
  </Container>;
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
Parsing Error: Unexpected token <

For this part `<Container>`, ESLint has a parsing error on the first char `<`

**Comment by platinumazure** [comment]
I think you need to enable JSX parsing in your configuration:

```js
{
    "parserOptions": {
        // ...
        "ecmaFeatures": {
            "jsx": true
        }
    }
}
```

Give that a shot and let us know how it goes.

Note that if this is a ReactJS project, you'll need to look at [eslint-plugin-react](https://github.com/yannickr/eslint-plugin-react) to get React semantics in your linting.

**Comment by Albert-Gao** [comment]
Thanks, works now!
