### ISSUE TITLE
Prompt users before installing dependencies in `eslint --init`

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9918]
# Problem

As of ESLint v4.16.0, `eslint --init` installs dependencies with `npm` when the user chooses a shareable config. This can cause problems for people who use other package managers. For example, if a project is using `yarn`, then the `yarn.lock` file will not be updated when ESLint installs dependencies with `npm`. This can result in confusing issues due to the mismatch between `package.json` and `yarn.lock`. In https://github.com/eslint/eslint/pull/9023, the team decided that we do not want to support `yarn` explicitly (and even if we did, the process would end up breaking again if the user is using a different package manager).

# Proposed solution

We should add a prompt like before installing the dependencies:

```
The config that you've selected requires the following dependencies:

eslint-config-foo@^5.0.0 eslint-plugin-bar@3 eslint-plugin-baz@~1.3.5

Would you like to install them now with npm?

* Yes
  No
```

If the user selects "yes", `eslint --init` would proceed as usual and install the dependencies. If the user selects "no", `eslint --init` would proceed as usual but would not install the dependencies. The user would then be expected to install the dependencies themself (e.g. by copy-pasting the list into a `yarn` command).

**Comment by sgalizia** [comment]
This is a huge pain point for me and I would really like to see this happen! I agree with not explicitly supporting a package manager but the option to not automatically install would be greatly appreciated. Would like to give a hand with this if possible.

**Comment by platinumazure** [comment]
Adding to the TSC agenda.

**TSC Summary:**

When a user runs `eslint --init` and chooses to use a shareable config, we determine what dependencies are needed and install those via calls to `npm install`. This can be confusing for users who use a different package manager, especially if the other package manager is fully integrated into their project and they are only adding ESLint later.

The proposed solution is to add a question to `eslint --init` which lists the dependencies to be installed and asks the user if s/he wishes to install via npm. If the user says no, `eslint --init` will not install the dependencies. (The user could copy/paste the dependency list into some other package manager command.) Assumption is there is still no desire to explicitly support other package managers in `eslint --init`.

**TSC Question:**

Should we accept this CLI enhancement proposal?

**Comment by not-an-aardvark** [comment]
This issue was accepted in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/adef4bed53b4e3160c19e82e7736ee651f540ee0/notes/2018/2018-05-10.md#prompt-users-before-installing-dependencies-in-eslint---init).
