### ISSUE TITLE
Global install eslint, not found

### ISSUE THREAD

**Issue by zigang93** [eslint/eslint#9923]
* **ESLint Version:** 4.16.0
* **Node Version:** 9.3.0
* **npm Version:** 5.6.0
* **OS:** mac os 10.13.2
* **Editor:** VS Code

**Step install** 
run `npm install -g eslint`

then in my terminal run `npm list -g --depth=0`
├── eslint@4.16.0
├── gulp-cli@2.0.1
└── yarn@1.3.2

**What happen ?** 
try to check eslint install or not, I run `eslint -v`

I am sure that I already install the eslint, but eslint still not found on bash.
show: `-bash: eslint: command not found`

I tried restart terminal , still same problem.. what happen?

**Comment by platinumazure** [comment]
Is npm properly installed and on your system PATH? That's the only thing I can think of...

**Comment by zigang93** [comment]
run `npm config set prefix /usr/local`
then reinstall `npm i -g eslint`

everything working now..
@platinumazure ya.. you are right.
