### ISSUE TITLE
Dynamic import()

### ISSUE THREAD

**Issue by jennydaman** [eslint/eslint#9927]
Dynamic import() statements can be programatically included, potentially reducing overhead. See https://developers.google.com/web/updates/2017/11/dynamic-import

This concept is rejected by eslint. (import statements in the middle of files goes against the spec. Moreover, eslint doesn't even recognize import() as legal syntax)

Should a new rule be introduced to support this feature?

**Comment by mysticatea** [comment]
Thank you for this issue.

See the "What about experimental features?" section in https://github.com/eslint/eslint#what-about-experimental-features.
You need to use `babel-eslint` to use experimental syntactic features.

**Comment by jennydaman** [comment]
I am using babel-eslint in my own project. The "allowImportExportEverywhere" feels more like a workaround, which would be appropriate though dynamic imports is going to be an official feature. (Already supported in Chrome 63, not yet in Firefox)

Though thanks for the clarification, it was a small issue.
