### ISSUE TITLE
UTF-8 Large Characters in Source Breaks Fixers

### ISSUE THREAD

**Issue by alex288ms** [eslint/eslint#9928]
When there is a UTF-8 large character (eg the 3-byte long U+2019 right single quote mark in the example below) in the source code (for example in a string literal) then any ESLint fixers that try to fix things below that will be off due to the extra bytes from the UTF-8 character.

In the example below the "a" variable is assigned to a string literal with a 3-byte UTF-8 character inside it (U+2019 right single quote mark). The next line on the assignment of "b" has a missing semicolon, and the fixer for the missing semicolon ESLint rule will then insert the semi-colon 2 characters to the left of where it should have gone.

So it seems like that 3-byte character, which is 2 bytes more than probably expected, is shifting things by those extra 2 bytes in the fixer.

Since it's easy for these UTF-8 characters to get unnoticed into code (it's just a copy+paste away), and likewise probably easy for some of the fixer's inserted mistakes to go unnoticed, sort of a rough bug.

I tried looking around for an ESLint rule that would warn if such multi-byte characters were present in a file but didn't find one, is there such a thing? That would help mitigate the problem.

```
function foo() {
  const a = "’";
  const b = 1
};
```
Auto-fixes to this:

```
function foo() {
  const a = "’";
  const b =; 1
}
```

Below is the ESLint output:

 ```
Warning  (ESLINT1) semi
    Missing semicolon. (semi)

               1 function foo() {
               2   const a = "’";
    >>> -      3   const b = 1
        +          const b =; 1
               4 }
```

**Comment by mysticatea** [comment]
Thank you for the report.

I could not reproduce it.
I have always used large Unicode characters because all Japanese characters are so, but I never heard such problem.

**Comment by alex288ms** [comment]
Apologies. Debugged further and it seems like ESLint is in fact working fine (did a clean install from the site, and didn't repro as was mentioned). The problem lies with some customizations with my company's setup...
