### ISSUE TITLE
Support the `default` JSON Schema keyword

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#9929]
Would be nice to be able to specify default values for the rule options in the schema.

See: https://github.com/epoberezkin/ajv#assigning-defaults

I think all you have to do is to set the `useDefaults: true` option in https://github.com/eslint/eslint/blob/2af94466fe8f87058fad4bd168958d2a7612a79d/lib/util/ajv.js#L18-L23

**Comment by platinumazure** [comment]
I would be wary of potential side-effects for users. Schema validation is already pretty tricky in some ways.

If you're strongly interested in this change, would you mind seeing if you can check the effect this would have on some downstream repositories? We have the [eslint-canary](https://github.com/eslint/eslint-canary) tool that could be used for this purpose. Thanks!

**Comment by not-an-aardvark** [comment]
@platinumazure If I'm understanding correctly, this would only affect users that are currently using a (non-functional) `default` key. Were those the users you had in mind, or is there something I'm missing?

**Comment by platinumazure** [comment]
@not-an-aardvark Yes; but in particular I would also like to know if there's any part of the JSON Schema grammar where "default" used to mean a property or value of "default", but would now be a metadata property indicating a default value for the object/property described by the schema.

**Comment by platinumazure** [comment]
@sindresorhus Sorry for letting this slide. Could you please provide an example of how this would benefit end users or plugin developers? E.g., would it somehow allow options to be automatically hydrated?

-------

Also, going back to my earlier comments, I've thought about this some more and I think I remember that property names such as "default" tend to be in `properties` or `elements` objects within an object or array schema definition-- that is, default-as-a-keyword should be outside of those elements so there should be no collision. So I'm less concerned about a breaking change possibility here.

**Comment by ilyavolodin** [comment]
@platinumazure This would potentially benefit us as well as integrations developers. For example, currently for `semi` rule, `always` is a default option. It's not marked anywhere as a default, and the only way to figure this out is either through documentation, or by reading the code. However, if we were to use `default` property, you could also figure that out through schema. More than that, we could write generic code that would run before the rule executes that would set all of the defaults up, if configuration doesn't specify anything. That way, we could possibly remove a bunch of code from our rules that handles setting defaults now.

**Comment by platinumazure** [comment]
Thanks @ilyavolodin for that explanation-- I think I'm sold.

(That said, this needs TSC review anyway. I'll work on getting this on the agenda.)

**Comment by platinumazure** [comment]
**TSC Summary**: JSON Schema supports a "default" keyword which allows schema authors to specify default values for optional properties in an object schema (among other cases). By allowing schemas to have defaults (a 1-line change in the ajv wrapper code), both core rules and custom rules could have default values in schemas. Additionally (although maybe as a separate proposal), we could write some generic code when creating rule instances which would hydrate default values for any rule options not provided by the user, which would allow us to remove some code in all rules related to option defaults. There shouldn't be any impact to users because the default keyword only has its semantic meaning as a keyword outside of property lists (i.e., rules with a "default" named option should not be affected).

**TSC Question**: Should we enable use of "default" keyword in rule schemas?

**Comment by platinumazure** [comment]
This issue was accepted in the 2018/09/13 TSC meeting.

**Comment by platinumazure** [comment]
I've started working on this. I have the basic AJV changes in a branch.

Tasks remaining:
1. Add at least some defaults to core ESLint rules
1. Ensure that user-supplied configurations are not mutated by AJV (via defensive cloning where needed)

If anyone wants to try the branch for local testing, it can be found here: https://github.com/eslint/eslint/tree/json-schema-default

**Comment by nzakas** [comment]
@platinumazure are you still working on this?

**Comment by platinumazure** [comment]
@nzakas Yes, though I've been busy.

**Comment by g-plane** [comment]
@platinumazure Do you mind I help you? If so, can I push commits to `json-schema-default` branch directly?

**Comment by platinumazure** [comment]
@g-plane Please feel free to help and please feel free to push directly. Thanks!
