### ISSUE TITLE
CLI : eslint -h rule-id -> displays /docs/rules/rule-id.md in terminal

### ISSUE THREAD

**Issue by Delapouite** [eslint/eslint#993]
Hi

Being able to read the documentation for a given rule directly from in the terminal would be a nice addition.

What about allowing an optional rule-id after the --help flag to get access to the relevant informations?

Example
`$ eslint -h no-new-wrappers`

would read the content of docs/rules/no-new-wrappers.md and displays it right in the terminal. (possibly using something like less as a pager).

**Comment by gyandeeps** [comment]
@nzakas I think we nearly made a decision here (I am not sure tho)
I think we should add the appropriate labels if we are going to do this.

**Comment by nzakas** [comment]
No one has taken it up, so closing.
