### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Quadriphobs1** [eslint/eslint#9932]
I am using windows and i have just setup eslint in my project.

In my package,json i have a script to run eslint using `npm run lint` with the configuration

```
"scripts": {
    ...
    "lint": "node ./node_modules/.bin/eslint **/*.js",
    ...
  },
```

In my  .eslintrc.js i have 
```
module.exports = {
    "extends": "standard"
};
```

each time i run the eslint with `npm run lint` i get error such as 

```
npm run lint


> doctorx@1.0.0 lint Directory\Workspace\doctorx\server
> node ./node_modules/.bin/eslint **/*.js src/app.js

Directory\project\server\node_modules\.bin\eslint:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doctorx@1.0.0 lint: `node ./node_modules/.bin/eslint **/*.js src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project @1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

```

Eslint version and configuration

> "devDependencies": {
>     "eslint": "^4.17.0",
>     "eslint-config-standard": "^11.0.0-beta.0",
>     "eslint-plugin-import": "^2.8.0",
>     "eslint-plugin-node": "^5.2.1",
>     "eslint-plugin-promise": "^3.6.0",
>     "eslint-plugin-standard": "^3.0.1",
>   }

How can i solve this

**Comment by platinumazure** [comment]
In npm scripts, you can just use the name of the binary without finding it in `./node_modules/.bin`. Additionally, that script you are calling is a shell script, not a JS file, so it can't be run by Node.

Try this: `'eslint "**/*.js"'`

Note: This should work on Windows because cmd will look for eslint.cmd in the local npm bin folder.

Note 2: I suggest quoting your glob patterns with double quotes so you get consistent behavior across shells and operating system.

Hope this helps!

**Comment by Quadriphobs1** [comment]
Ohhh okay, i guess i have to do `"eslint '**/*.js'"`

**Comment by platinumazure** [comment]
That will probably work in most cases, yes. Feel free to stop by our [Gitter chat](https://Gitter.im/eslint/eslint) if you run into any trouble. Thanks!

Closing as the question has been answered.
