### ISSUE TITLE
ignoreComments issue with some comments in Typescript

### ISSUE THREAD

**Issue by ssannttoss** [eslint/eslint#9933]
#9018 
#9752 

ignoreComments not working with some comments
     * @type {express.Application}
     * @returns {void}

`
  rules:
    indent: ["warn", 4, { "ignoreComments": true }]
    no-trailing-spaces: ["warn", { "ignoreComments": true }]
  `

![image](https://user-images.githubusercontent.com/28936664/35773161-47fd60cc-0931-11e8-97fe-3d305c79d455.png)
![image](https://user-images.githubusercontent.com/28936664/35773165-56dae48e-0931-11e8-85e7-c630388b1ae7.png)

If I use the --fix the code brakes.

![image](https://user-images.githubusercontent.com/28936664/35773174-9318a1ac-0931-11e8-8c52-73fa3c9175d8.png)
![image](https://user-images.githubusercontent.com/28936664/35773177-a75a32b6-0931-11e8-9733-3790adcc9b01.png)

Bellow more issues after using --fix. 

![image](https://user-images.githubusercontent.com/28936664/35773211-8cf60d2c-0932-11e8-83e2-0edc1b8f7b69.png)

![image](https://user-images.githubusercontent.com/28936664/35773184-dbed9824-0931-11e8-9b2e-cdd2a20a2a5e.png)

![image](https://user-images.githubusercontent.com/28936664/35773188-f66ec6e6-0931-11e8-8c49-12e7c4013929.png)

![image](https://user-images.githubusercontent.com/28936664/35773192-31f8e976-0932-11e8-8b50-a948d1aae2ed.png)

![image](https://user-images.githubusercontent.com/28936664/35773197-55172fbc-0932-11e8-9eac-2774587314a8.png)

![image](https://user-images.githubusercontent.com/28936664/35773207-6fc8bbb4-0932-11e8-8583-3a4247d12bc0.png)

**Comment by ssannttoss** [comment]
The version of ESLint you are using (run eslint -v)
v4.17.0

What you did (the source code and ESLint configuration)
Check the code [here](https://gist.github.com/ssannttoss/11a82a3244e6fdfaebf488829c5be1f8) 
Issue9933.ts
Issue9933_with_fix.ts

The actual ESLint output complete with numbers
Check the code [here](https://gist.github.com/ssannttoss/11a82a3244e6fdfaebf488829c5be1f8) 
lint.txt

What you expected to happen instead
This type of comment `* @type {String} ` should be ignored. Using the --fix option breaks the code to ` {String}` without the * and the @type

**Comment by stanbluijs** [comment]
Is there any more information needed to solve this issue?
I have the same issue on multi line comments where using @ sign.

ESLint version:
```
eslint -v
v4.19.1
```

Example with ESLint errors (source code):
```
/**
 * Create a Node with a value and with the path of it's parent.
 *
 * @param {string} label
 * @param {Node} parent
 * @returns {Node}
 */
```
Messages are:
`4:1 error  Expected indentation of 0 spaces but found 3  indent`
`5:1 error  Expected indentation of 0 spaces but found 3  indent`
`6:1 error  Expected indentation of 0 spaces but found 3  indent`

Example without ESLint errors:
```
/**
 * Create a Node with a value and with the path of it's parent.
 *
 * {string} label
 * {Node} parent
 * {Node}
 */
```

Expectation:
That a comment where using `@param` or `@returns` will not break ESLint with message `error  Expected indentation of 0 spaces but found 3  indent`.

ESLint configuration:
```
{
  "parser": "typescript-eslint-parser",
  "plugins": [
    "typescript"
  ],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "semi": ["error", "always"],
    "quotes": ["error", "double"],
    "indent": ["error", 4, {
      "ignoreComments": true
    }],
    "max-len": ["error", { "code": 120 }],
    "typescript/no-unused-vars": "error"
  }
}
```

Dependencies
```
{
    "@types/auth0": "^2.7.2",
    "@types/bson": "^1.0.8",
    "@types/chai": "^4.1.3",
    "@types/express": "^4.11.0",
    "@types/graphql": "^0.12.7",
    "@types/mocha": "^2.2.46",
    "@types/mongodb": "^3.0.15",
    "@types/node": "^9.6.6",
    "@types/request-promise": "^4.1.41",
    "chai": "^4.1.2",
    "eslint": "^4.19.1",
    "eslint-plugin-typescript": "^0.8.1",
    "mocha": "^5.1.1",
    "request": "^2.83.0",
    "request-promise": "^4.2.2",
    "ts-node": "^4.1.0",
    "tslint": "^5.9.1",
    "typescript": "^2.8.3",
    "typescript-eslint-parser": "^12.0.0"
  }
```

**Comment by platinumazure** [comment]
Can this be reproduced outside of using typescript-eslint-parser? If not, I think it makes sense to open up an issue on the typescript-eslint-parser repository.

My guess is that parser is creating an AST with either extra nodes or incorrect range/location information, resulting in indent autofix getting confused.

**Comment by stanbluijs** [comment]
@platinumazure thank you for your quick reply. I left out typescript-eslint-parser and this will indeed ignore the comment as expected. 

I will post the issue on the typescript-eslint-parser repository.

**Comment by not-an-aardvark** [comment]
This might be the same issue as https://github.com/eslint/typescript-eslint-parser/issues/422.

**Comment by kaicataldo** [comment]
Is this worth keeping open to track this? Or should we go ahead and close now that there's a corresponding issue in typescript-eslint-parser.
