### ISSUE TITLE
Limit callback and params from breaking into multiple lines

### ISSUE THREAD

**Issue by cenjennifer** [eslint/eslint#9934]
I'm struggling with trying to prevent function params from breaking a function into multiple lines. I tried to use `"function-paren-newline": ["error", { "minItems": 3 }]`, but I think this just breaks the parens to new lines. Is there a way to limit the params/callback from breaking into new line? 

For example (in angular): 
```
$scope.$watch(
  'hello',
  function() {
    sayHi($scope.name)
  },
  true
);
```

Ideally, I would like it to be like below:
```
$scope.$watch('hello', function() {
  sayHi($scope.name)
}, true);
```

I don't want the 3 params in the watch function to be broken down to multiple lines (This happens when I have timeout within a function). Is there a way to do this?

**Comment by platinumazure** [comment]
I'm not seeing any rule for that after a quick search in the rules list. Hopefully someone else on the team will comment if I've missed something. I'll take a closer look later, as well.

**Comment by nzakas** [comment]
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
