### ISSUE TITLE
feature request: relative directories to plugins/parsers/etc

### ISSUE THREAD

**Issue by devsnek** [eslint/eslint#9939]
refs: https://github.com/nodejs/node/pull/18566

a fantastic alternative to what we did in that pr would be your resolving system allowing relative directories for plugins and parsers like
```js
plugins: ['markdown', './tools/node_modules/eslint-plugin-node'],
parser: './tools/node_modules/babel-eslint',
```

**Comment by not-an-aardvark** [comment]
Closing as a duplicate of https://github.com/eslint/eslint/issues/6237
