### ISSUE TITLE
ESLint initializer uses double quotes even when single selected

### ISSUE THREAD

**Issue by SaladFork** [eslint/eslint#9947]
* **ESLint Version:** `v3.19.0`
* **Node Version:** `v9.4.0`
* **npm Version:** `5.6.0`

**What parser (default, Babel-ESLint, etc.) are you using?**
`eslint` command line

**Please show your full configuration:**
starting with no configuration

```bash
$ eslint --init
? How would you like to configure ESLint? Answer questions about your style
? Are you using ECMAScript 6 features? Yes
? Are you using ES6 modules? Yes
? Where will your code run? Browser
? Do you use CommonJS? No
? Do you use JSX? No
? What style of indentation do you use? Spaces
? What quotes do you use for strings? Single
? What line endings do you use? Unix
? Do you require semicolons? Yes
? What format do you want your config file to be in? JavaScript
```

**What did you expect to happen?**
A configuration file will be created using single quotes (as answered in "What quotes do you use for strings?" question)

**What actually happened? Please include the actual, raw output from ESLint.**
A configuration file is created using double quotes for strings:
```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};
```

**Comment by platinumazure** [comment]
Ooh, that's interesting. We probably are just generating a JSON-stringified version of the configuration and embedding that into the config file.

I suspect this also applies to any other question (i.e., might ignore Windows/Unix line endings, might ignore indent settings, will preserve semicolon even if semicolons are stated not to be used, etc.).

I wonder if, for JavaScript configs only, we should just new up a CLIEngine instance and lint the config file (with that same file passed in as the config)? Seems like that could allow us to add more options to `eslint --init` in future without having to explicitly code for each option (i.e., no need to specifically write templates for single-quote vs double-quote, etc.).

I'll be curious to know what the rest of the team thinks.

**Comment by platinumazure** [comment]
Labeling as an "enhancement" for now under the assumption that this is not something we really designed for (i.e., current design = JSON.stringify or similar and we honestly didn't think about ensuring the JS config file would pass linting). Team: If I have that wrong, please relabel as needed. Thanks!

**Comment by not-an-aardvark** [comment]
I agree, running the equivalent of `eslint --fix` on the config file before writing it to the filesystem seems like it would be useful.

**Comment by SaladFork** [comment]
Thanks for the quick response! I confirmed the behavior is the same on `eslint` `v4.17.0` (the output seems the same).

Running fix seems a clever way to handle this. Would this be a good task for someone new to the ESLint codebase to try and tackle?

**Comment by mysticatea** [comment]
I agree with `eslint --fix`. I did so when I wrote `--init` functionality on `eslint-cli`: https://github.com/eslint/eslint-cli/pull/5/files#diff-547d8fc032c76afa0bd0a4dde5206e3f

**Comment by platinumazure** [comment]
@SaladFork 

> Would this be a good task for someone new to the ESLint codebase to try and tackle?

Yes, I think it might be. I would suggest using CLIEngine, similar to what mysticatea described in [this comment](https://github.com/eslint/eslint/issues/9947#issuecomment-363309514), to lint the generated config with itself and run autofix.

Very sorry for the delayed reply.

**Comment by ilyavolodin** [comment]
I'll champion this change, so it's now accepted.
