### ISSUE TITLE
[valid-jsdoc] Syntax error with curried function as return value

### ISSUE THREAD

**Issue by lgraziani2712** [eslint/eslint#9949]
**Tell us about your environment**

* **ESLint Version:** v4.16.0
* **Node Version:** v9.0.0
* **npm Version:** v5.5.1
* **yarn Version:** v1.3.2

**What parser (default, Babel-ESLint, etc.) are you using?**

Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
  extends: ['eslint:recommended'],
  plugins: ['filenames'],
  env: {
    es6: true,
    node: true,
  },
  parserOptions: {
    ecmaVersion: 8,
    sourceType: 'script',
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
  },
  rules: {
    'array-callback-return': 1,
    'arrow-body-style': 1,
    'arrow-parens': 0,
    camelcase: 2,
    curly: [1, 'all'],
    'dot-notation': 1,
    'eol-last': 0,
    eqeqeq: 1,
    'linebreak-style': 1,
    'lines-around-directive': 1,
    'new-cap': [1, { properties: false }],
    'newline-after-var': 1,
    'newline-before-return': 1,
    'no-alert': 0,
    'no-array-constructor': 2,
    'no-case-declarations': 2,
    'no-console': 1,
    'no-const-assign': 1,
    'no-debugger': 1,
    'no-dupe-class-members': 2,
    'no-extra-semi': 0,
    'no-irregular-whitespace': 2,
    'no-iterator': 1,
    'no-lone-blocks': 0,
    'no-loop-func': 2,
    'no-mixed-spaces-and-tabs': 0,
    'no-new-object': 1,
    'no-nested-ternary': 2,
    'no-param-reassign': 1,
    'no-template-curly-in-string': 2,
    'no-underscore-dangle': [2, { allow: ['_id', '_rev'] }],
    'no-unexpected-multiline': 0,
    'no-unneeded-ternary': [1, { defaultAssignment: false }],
    'no-unused-vars': [2, { ignoreRestSiblings: true }],
    'no-useless-concat': 1,
    'no-useless-constructor': 1,
    'no-useless-escape': 1,
    'no-var': 1,
    'object-shorthand': 1,
    'one-var': [2, 'never'],
    'prefer-arrow-callback': 1,
    'prefer-const': 1,
    'prefer-rest-params': 1,
    'prefer-template': 1,
    strict: 2,
    'valid-jsdoc': 2,
    //////////////////////
    // Filenames
    //////////////////////
    'filenames/match-exported': 2,
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I wrote a JSDoc for a curried function.

```js
/**
 * Return true if some of the children props exist.
 *
 * @param {string} pkgProp Parent prop
 * @return {(props: string | Array<string>) => boolean} 
 */
const hasPkgSubProp = pkgProp => props =>
  hasPkgProp(arrify(props).map(p => `${pkgProp}.${p}`));
```

```bash
eslint /* folders */ --fix
```

**What did you expect to happen?**

To not mark the JSDoc as an error.

**What actually happened? Please include the actual, raw output from ESLint.**

![image](https://user-images.githubusercontent.com/15050200/35835890-1b7da28c-0abc-11e8-8d58-8738502db006.png)

It marks the JSDoc as if it had a syntax error. Is this correct? VSCode doesn't complain, by the way.

And there is this only issue on the jsdoc repo https://github.com/jsdoc3/jsdoc/issues/1286

Thank you for your work!

**Comment by kaicataldo** [comment]
I apologize that we lost track of this. Have you resolved this? If not, can you share the error message from ESLint? It's hard to know what it's warning about without it. Thanks!

**Comment by lgraziani2712** [comment]
No problemo! At least you could make time for it! Thank you :)

It seems the bug still exists: [Demo link](https://eslint.org/demo/#eyJ0ZXh0IjoiLyoqXHJcbiAqIFJldHVybiB0cnVlIGlmIHNvbWUgb2YgdGhlIGNoaWxkcmVuIHByb3BzIGV4aXN0LlxyXG4gKlxyXG4gKiBAcGFyYW0ge3N0cmluZ30gcGtnUHJvcCBQYXJlbnQgcHJvcFxyXG4gKiBAcmV0dXJuIHsocHJvcHM6IHN0cmluZyB8IEFycmF5PHN0cmluZz4pID0+IGJvb2xlYW59XHJcbiAqICBDdXJyaWVkIGZ1bmN0aW9uXHJcbiAqL1xyXG5jb25zdCBoYXNQa2dTdWJQcm9wID0gcGtnUHJvcCA9PiBwcm9wcyA9PlxyXG4gIGhhc1BrZ1Byb3AoYXJyaWZ5KHByb3BzKS5tYXAocCA9PiBgJHtwa2dQcm9wfS4ke3B9YCkpO1xyXG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zb2xlIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWVtcHR5IjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6MiwicmVxdWlyZS1qc2RvYyI6MiwidmFsaWQtanNkb2MiOjJ9LCJlbnYiOnt9fX0=).

If it's any I can do to help, ask!

Thank you, Luciano.

**Comment by kaicataldo** [comment]
Thanks for the info. Here's the error: 
```
1:1 - JSDoc syntax error. (valid-jsdoc)
```

It looks like Doctrine, our JSDoc parser, doesn't know how to parse arrow functions in param types. Replacing `(props: string | Array<string>) => boolean` with a type like `boolean` makes the error go away.

**Comment by lgraziani2712** [comment]
I'm.... not exactly sure if this is _really_ a valid jsdoc: I cannot find any documentation related to it.

Here is the only issue related, and it's still open: https://github.com/jsdoc3/jsdoc/issues/1286#issuecomment-341911947

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
