### ISSUE TITLE
`max-len` `ignoreStrings` does not ignore jsx prop strings

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#9954]
**Tell us about your environment**

* **ESLint Version:** v4.16.0
* **Node Version:** v8.9.1
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "rules": {
    "max-len": [2, { "code": 5", "ignoreStrings": true }],
  },
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
<input placeholder="something long" />
```

```bash
eslint foo.js
```

**What did you expect to happen?**
No error.

**What actually happened? Please include the actual, raw output from ESLint.**
 1:1  error  Line 1 exceeds the maximum line length of 5  max-len

**Comment by cking** [comment]
I have the same problem. Right now I'm using an ugly workaround:
```jsx
        <div
          className={
            'flex-100 layout-row layout-wrap ' +
            'layout-align-space-between-center input_box_full'
          }
        >
          <input type="text" value={editor.city} name="city" onChange={this.handleChange} />
        </div>
```

As you can see, it's very ugly and distracting/confusing

**Comment by rachx** [comment]
Working on this
