### ISSUE TITLE
[react] [jsx] Object spread fails in props values

### ISSUE THREAD

**Issue by caub** [eslint/eslint#9960]
I get `ESLint: Cannot read property 'expression' of undefined. Please see the 'ESLint' output channel for details.`

```
~/dev/repo $ npx eslint file/with/code
Cannot read property 'expression' of undefined
~/dev/repo $ 
```

when running eslint on this code:
```jsx
const a = {};
const foo = () => (
	<Link
		to={{
			pathname: '/bar',
			query: { ...a },
		}}
	/>
);
```

config:

```json
{
  "parser": "babel-eslint",
  "extends": [
    "plugin:import/errors",
    "plugin:import/warnings",
    "airbnb"
  ],
  "plugins": [ "babel", "react", "jest" ],
  //...
}
```

versions:
```
"babel-eslint": "^8.2.1",
"eslint": "^4.17.0",
"eslint-plugin-babel": "^4.1.2",
"eslint-plugin-react": "^7.6.1",
```

Hmm it might belong to babel-eslint

**Comment by not-an-aardvark** [comment]
Can you provide more information about the crash (e.g. a stack trace)? As-is, it's hard to tell where the error is coming from.

**Comment by caub** [comment]
@not-an-aardvark I updated description, the error is only `Cannot read property 'expression' of undefined`  is there a way to get more?

**Comment by ilyavolodin** [comment]
Can you try linting the same file without `babel-eslint` chances are, the error is coming from there, but that would verify it.

**Comment by caub** [comment]
@ilyavolodin Thanks good point, 

code: 
```js
import React from 'react';

const a = {};
const foo = () => (
	<Link
		to={{
			pathname: '/bar',
			query: { ...a },
		}}
	/>
);
```

with eslint 4.17.0

.eslintrc:
```json
{
	"extends": [
		"plugin:import/errors",
		"plugin:import/warnings",
		"eslint:recommended"
	],
	// "parser": "babel-eslint",
	// "settings": {
	// 	"import/resolver": "webpack"
	// },
	"env": {
		"browser": true,
		"node": true
	},
	"parserOptions": {
		"ecmaVersion": 2018,
		"sourceType": "module",
		"ecmaFeatures": {
				"jsx": true
		}
	}
}
```
gives: `10:13  error  Parsing error: Unexpected token ..`

with this .eslint using airbnb config:
```
{
	"extends": [
		"plugin:import/errors",
		"plugin:import/warnings",
		"airbnb"
	],
	"plugins": ["react"],
	// "parser": "babel-eslint",

	"env": {
		"browser": true,
		"node": true
	},
	"parserOptions": {
		"ecmaVersion": 2018,
		"sourceType": "module",
		"ecmaFeatures": {
				"jsx": true
		}
	}
}
```

I get `Cannot read property 'expression' of undefined`

Both configs can parse

```js
const a = {};
const b = { ...a };
console.log(b);
```

so it's an issue in jsx  props, and interestingly babel-eslint produce the same error, it probably means it skip jsx values and let eslint handle them

**Comment by ilyavolodin** [comment]
Hmm.. OK, so it's not babel-eslint. The reason it's failing with the first config is you need to also add `experimentalObjectRestSpread: true` under `ecmaFeatures`. Could you try to limit your extends with a test run to see which one might contain the rule that's failing?

**Comment by caub** [comment]
@ilyavolodin oh nice for `experimentalObjectRestSpread`, it works now with eslint:recommended. With airbnb, I noticed this rule:

```json
"jsx-a11y/anchor-is-valid": ["error", {
	"components": [ "Link" ],
	"specialLink": [ "to" ],
	"aspects": [ "noHref", "invalidHref", "preferButton" ]
}]
```
makes it fail with the `Cannot read property 'expression' of undefined`

with "warn" as value I get  
```
  7:7  warning  'foo' is assigned a value but never used                                                           no-unused-vars
  8:2  warning  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid

✖ 2 problems (0 errors, 2 warnings)
```

So it's an error with https://github.com/evcohen/eslint-plugin-jsx-a11y, I'd continue there, many thanks again

(using nodejs api https://runkit.com/caub/5a8294d1b466e700128c0a6f but I don't know how I'd use plugins there, maybe CLIEngine)
