### ISSUE TITLE
Match tester output to production behavior

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [eslint/eslint#9976]
This is a request for a change of the RuleTester I already have an implementation for but that would break some test cases.

**The version of ESLint you are using.**

4.17.0

**The problem you want to solve.**

Over at yannickcr/eslint-plugin-react, this issue has been lying around for a while: yannickcr/eslint-plugin-react#1414
While working out how to fix it, I realized that the problem is that the tester doesn't do multiple passes over the code. Which is noted in multiple comments in workaround test cases (see e.g. "Other case is fixed in the second pass." in no-else-return).

So currently, there is this mismatch between production and testing - example no-else-return:
**IN**
`function foo4() { if (true) { if (false) return x; else return y; } else { return z; } }`
**OUT (testing)**
`function foo4() { if (true) { if (false) return x; return y; } else { return z; } }`
**OUT (production)** (github swallows some spaces)
`function foo4() { if (true) { if (false) return x; return y; }  return z;  }`

**Your take on the correct solution to problem.**

Just like in production, the tester should loop until no more fixes are left.
Of course... all of those workaround tests will have to be adjusted. Which in this repo was a whopping 5.
But of course it'll also affect plugins.

Like I said, I'd already have an implementation for this (less than 10 lines of code) - please let me know whether you want me to go ahead with a PR.

**Comment by platinumazure** [comment]
Hi @s-h-a-d-o-w, thanks for the proposal.

I'm slightly :-1: to this change, because RuleTester is designed for unit testing individual rules and should test fixers as a unit, which (to me) only makes sense when running the rule and fixer once.

I would say that if you need to test how multiple passes of rule fixers work, you could create an integration test in your project which uses CLIEngine#executeOnText to perform multi-pass autofixing, and you could assert an expected result output there.

**Comment by s-h-a-d-o-w** [comment]
Sounds fair enough, thanks for the explanation.

I would like to add though that in this case, it seems to me that those 5 test cases that I mentioned that rely on multiple passes (currently in no-else-return.js and no-useless-return.js) should be either removed or redesigned in a way that they are "accurately resolved" in a single pass?

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
